Castor3D: Castor3D::ChunkParser< T > Class Template Reference
Castor3D::ChunkParser< T > Class Template Reference
Chunk parser.
Static Public Member Functions
static bool Parse (T *p_values, size_t p_count, BinaryChunk &p_chunk)
Retrieves a value array from a chunk.
static bool Parse (T &p_value, BinaryChunk &p_chunk)
Retrieves a value from a chunk.
Static Public Member Functions inherited from Castor3D::ChunkParserBase
static bool Parse (uint8_t *p_values, size_t p_size, BinaryChunk &p_chunk)
Retrieves a value array from a chunk.
Detailed Description
template<typename T>
class Castor3D::ChunkParser< T >
Chunk parser.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
08/04/2014
Member Function Documentation
Parse() [1/2]
template<typename T > static bool Castor3D::ChunkParser< T >::Parse (T * p_values, size_t p_count, BinaryChunk & p_chunk) inline static
Retrieves a value array from a chunk.
Parameters
[out] p_values Receives the parsed values
[out] p_count The values count
[in] p_chunk The chunk containing the values
Returns
false if any error occured
References Castor3D::ChunkParserBase::Parse(), and Castor3D::PrepareChunkData().
Referenced by Castor3D::BinaryParserBase< Skeleton >::DoParseChunk().
Parse() [2/2]
template<typename T > static bool Castor3D::ChunkParser< T >::Parse (T & p_value, BinaryChunk & p_chunk) inline static
Retrieves a value from a chunk.
Parameters
[out] p_value Receives the parsed value
[in] p_chunk The chunk containing the value
Returns
false if any error occured
References Castor3D::GetBuffer(), Castor3D::GetDataSize(), Castor3D::ChunkParserBase::Parse(), and Castor3D::PrepareChunkData().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Binary/ChunkParser.hpp