Castor3D: castor3d::shader::SpotLight Struct Reference
castor3d::shader::SpotLight Struct Reference
#include <GlslLight.hpp>
Public Member Functions
C3D_API SpotLight (sdw::ShaderWriter &writer, ast::expr::ExprPtr expr, bool enabled)
C3D_API void getAttenuationFactor (sdw::Float const &distance, sdw::Float &attenuation) const
auto base () const
auto colour () const
auto intensity () const
auto range () const
auto shadowMapIndex () const
auto position () const
auto exponent () const
auto direction () const
auto innerCutOff () const
auto outerCutOff () const
auto innerCutOffCos () const
auto outerCutOffCos () const
auto innerCutOffSin () const
auto outerCutOffSin () const
auto outerCutOffTan () const
auto cutOffsCosDiff () const
Constructor & Destructor Documentation
SpotLight()
C3D_API castor3d::shader::SpotLight::SpotLight (sdw::ShaderWriter & writer, ast::expr::ExprPtr expr, bool enabled) inline
Member Function Documentation
base()
auto castor3d::shader::SpotLight::base () const inline
Referenced by colour(), castor3d::shader::computeRange(), exponent(), intensity(), position(), range(), and shadowMapIndex().
colour()
auto castor3d::shader::SpotLight::colour () const inline
References base().
cutOffsCosDiff()
auto castor3d::shader::SpotLight::cutOffsCosDiff () const inline
References innerCutOffCos(), and outerCutOffCos().
direction()
auto castor3d::shader::SpotLight::direction () const inline
exponent()
auto castor3d::shader::SpotLight::exponent () const inline
References base().
getAttenuationFactor()
C3D_API void castor3d::shader::SpotLight::getAttenuationFactor (sdw::Float const & distance, sdw::Float & attenuation) const
innerCutOff()
auto castor3d::shader::SpotLight::innerCutOff () const inline
innerCutOffCos()
auto castor3d::shader::SpotLight::innerCutOffCos () const inline
Referenced by cutOffsCosDiff().
innerCutOffSin()
auto castor3d::shader::SpotLight::innerCutOffSin () const inline
intensity()
auto castor3d::shader::SpotLight::intensity () const inline
References base().
outerCutOff()
auto castor3d::shader::SpotLight::outerCutOff () const inline
outerCutOffCos()
auto castor3d::shader::SpotLight::outerCutOffCos () const inline
Referenced by cutOffsCosDiff().
outerCutOffSin()
auto castor3d::shader::SpotLight::outerCutOffSin () const inline
outerCutOffTan()
auto castor3d::shader::SpotLight::outerCutOffTan () const inline
position()
auto castor3d::shader::SpotLight::position () const inline
References base().
range()
auto castor3d::shader::SpotLight::range () const inline
References base().
shadowMapIndex()
auto castor3d::shader::SpotLight::shadowMapIndex () const inline
References base().
The documentation for this struct was generated from the following file:
Castor3D/Shader/Shaders/GlslLight.hpp