Castor3D: castor3d::StagingData Class Reference
castor3d::StagingData Class Reference
#include <StagingData.hpp>
Public Member Functions
C3D_API StagingData (RenderDevice const &device, std::string const &debugName)
C3D_API void upload (void const *data, VkDeviceSize size, VkDeviceSize offset, ashes::BufferBase const &buffer)
C3D_API void uploadNoWait (void const *data, VkDeviceSize size, VkDeviceSize offset, ashes::BufferBase const &buffer)
void upload (castor::ByteArray const &data, VkDeviceSize offset, ashes::BufferBase const &buffer)
void uploadNoWait (castor::ByteArray const &data, VkDeviceSize offset, ashes::BufferBase const &buffer)
Constructor & Destructor Documentation
StagingData()
C3D_API castor3d::StagingData::StagingData (RenderDevice const & device, std::string const & debugName)
Member Function Documentation
upload() [1/2]
void castor3d::StagingData::upload (castor::ByteArray const & data, VkDeviceSize offset, ashes::BufferBase const & buffer) inline
References upload().
upload() [2/2]
C3D_API void castor3d::StagingData::upload (void const * data, VkDeviceSize size, VkDeviceSize offset, ashes::BufferBase const & buffer)
Referenced by upload().
uploadNoWait() [1/2]
void castor3d::StagingData::uploadNoWait (castor::ByteArray const & data, VkDeviceSize offset, ashes::BufferBase const & buffer) inline
References uploadNoWait().
uploadNoWait() [2/2]
C3D_API void castor3d::StagingData::uploadNoWait (void const * data, VkDeviceSize size, VkDeviceSize offset, ashes::BufferBase const & buffer)
Referenced by uploadNoWait().
The documentation for this class was generated from the following file:
Miscellaneous/StagingData.hpp