Castor3D: Castor3D::Submesh Class Reference
Castor3D::Submesh Class Reference
The submesh representation.
Public Member Functions
C3D_API Submesh (Scene &p_scene, Mesh &p_mesh, uint32_t p_id=1)
Constructor.
C3D_API ~Submesh ()
Destructor.
C3D_API void Initialise ()
Initialises the submesh.
C3D_API void Cleanup ()
Cleans the submesh.
C3D_API void ComputeContainers ()
Computes the containers (cube and sphere)
C3D_API uint32_t GetFaceCount () const
C3D_API uint32_t GetPointsCount () const
C3D_API int IsInMyPoints (Castor::Point3r const &p_vertex, double p_precision)
Tests if the given Point3r is in mine.
C3D_API BufferElementGroupSPtr AddPoint (real x, real y, real z)
Creates and adds a vertex to my list.
C3D_API BufferElementGroupSPtr AddPoint (Castor::Point3r const &p_v)
Adds a vertex to my list.
C3D_API BufferElementGroupSPtr AddPoint (real *p_v)
Creates and adds a vertex to my list.
C3D_API BufferElementGroupSPtr AddPoint (InterleavedVertex const &p_v)
Creates and adds a vertex to my list.
C3D_API void AddPoints (InterleavedVertex const *const p_begin, InterleavedVertex const *const p_end)
Adds a points list to my list.
C3D_API void AddBoneDatas (VertexBoneData const *const p_begin, VertexBoneData const *const p_end)
Adds bone datas.
C3D_API void ClearFaces ()
Clears this submesh's face array.
C3D_API Face AddFace (uint32_t a, uint32_t b, uint32_t c)
Creates and adds a face to the submesh.
C3D_API void AddFaceGroup (FaceIndices const *const p_begin, FaceIndices const *const p_end)
Creates and adds faces to the submesh.
C3D_API void AddQuadFace (uint32_t a, uint32_t b, uint32_t c, uint32_t d, Castor::Point3r const &p_minUV=Castor::Point3r(), Castor::Point3r const &p_maxUV=Castor::Point3r(1, 1, 1))
Creates and adds a quad face to the submesh.
C3D_API void ResetGpuBuffers ()
Recreates the buffers.
C3D_API void ResetMatrixBuffers ()
Recreates the Matrix buffers.
C3D_API void Draw (GeometryBuffers const &p_geometryBuffers)
Draws the submesh.
C3D_API void DrawInstanced (GeometryBuffers const &p_geometryBuffers, uint32_t p_count)
Draws the submesh.
C3D_API void ComputeFacesFromPolygonVertex ()
Creates faces from the points.
C3D_API void ComputeNormals (bool p_reverted=false)
Generates normals and tangents.
C3D_API void ComputeNormals (Face const &p_face)
Computes normal and tangent for each vertex of the given face.
C3D_API void ComputeTangents (Face const &p_face)
Computes tangent for each vertex of the given face.
C3D_API void ComputeTangentsFromNormals ()
Computes tangent for each vertex of the submesh.
C3D_API void ComputeTangentsFromBitangents ()
Computes tangent for each vertex of the submesh.
C3D_API void ComputeBitangents ()
Computes bitangent for each vertex of the submesh.
C3D_API void SortByDistance (Castor::Point3r const &p_cameraPosition)
Sorts the face from farthest to nearest from the camera.
C3D_API uint32_t Ref (MaterialSPtr p_material)
Increments instance count.
C3D_API uint32_t UnRef (MaterialSPtr p_material)
Decrements instance count.
C3D_API uint32_t GetRefCount (MaterialSPtr p_material) const
Retrieves the instances count.
C3D_API Topology GetTopology () const
C3D_API void SetTopology (Topology p_value)
Sets the topology.
C3D_API GeometryBuffersSPtr GetGeometryBuffers (ShaderProgram const &p_program)
Retrieves a GeometryBuffers for given program.
C3D_API void SetAnimated (bool p_animated)
void AddPoints (std::vector< InterleavedVertex > const &p_vertices)
Adds a points list to my list.
template<size_t Count>
void AddPoints (std::array< InterleavedVertex, Count > const &p_vertices)
Adds a points list to my list.
void AddBoneDatas (std::vector< VertexBoneData > const &p_boneData)
Adds bone datas.
template<size_t Count>
void AddBoneDatas (std::array< VertexBoneData, Count > const &p_boneData)
Adds bone datas.
void AddFaceGroup (std::vector< FaceIndices > const &p_faces)
Creates and adds faces to the submesh.
template<size_t Count>
void AddFaceGroup (std::array< FaceIndices, Count > const &p_faces)
Creates and adds faces to the submesh.
SkeletonSPtr GetSkeleton () const
void SetDefaultMaterial (MaterialSPtr p_mat)
Sets the material.
BufferElementGroupSPtr operator[] (uint32_t p_index) const
Retrieves the point at given index.
BufferElementGroupSPtr GetPoint (uint32_t p_index) const
Retrieves the point at given index.
MaterialSPtr GetDefaultMaterial () const
Castor::CubeBox const & GetCollisionBox () const
Castor::CubeBox & GetCollisionBox ()
Castor::SphereBox const & GetCollisionSphere () const
Castor::SphereBox & GetCollisionSphere ()
VertexPtrArray const & GetPoints () const
VertexPtrArray & GetPoints ()
Face const & GetFace (uint32_t p_index) const
Retrieves the face at given index.
FaceArray const & GetFaces () const
FaceArray & GetFaces ()
bool HasVertexBuffer () const
bool HasAnimationBuffer () const
bool HasIndexBuffer () const
bool HasBonesBuffer () const
bool HasMatrixBuffer () const
VertexBuffer const & GetVertexBuffer () const
VertexBuffer & GetVertexBuffer ()
VertexBuffer const & GetAnimationBuffer () const
VertexBuffer & GetAnimationBuffer ()
IndexBuffer const & GetIndexBuffer () const
IndexBuffer & GetIndexBuffer ()
VertexBuffer const & GetBonesBuffer () const
VertexBuffer & GetBonesBuffer ()
VertexBuffer const & GetMatrixBuffer () const
VertexBuffer & GetMatrixBuffer ()
bool IsInitialised () const
Mesh const & GetParent () const
Mesh & GetParent ()
ProgramFlags const & GetProgramFlags () const
uint32_t GetId () const
void NeedUpdate ()
Sets the submesh to be updated.
template<uint32_t Count>
void AddFaceGroup (FaceIndices(&p_faces)[Count])
Creates and adds faces to the submesh.
Friends
class GeometryBuffers
class BinaryWriter< Submesh >
class BinaryParser< Submesh >
Detailed Description
The submesh representation.
Author
Sylvain DOREMUS
Date
14/02/2010
Remarks
A submesh holds its buffers (vertex, normals and texture) and its combobox.
Constructor & Destructor Documentation
Submesh()
C3D_API Castor3D::Submesh::Submesh (Scene & p_scene, Mesh & p_mesh, uint32_t p_id = 1)
Constructor.
Parameters
[in] p_mesh The parent mesh.
[in] p_scene The scene.
[in] p_id The submesh ID.
~Submesh()
C3D_API Castor3D::Submesh::~Submesh ()
Destructor.
Member Function Documentation
AddBoneDatas() [1/3]
C3D_API void Castor3D::Submesh::AddBoneDatas (VertexBoneData const *const p_begin, VertexBoneData const *const p_end)
Adds bone datas.
Parameters
[in] p_begin The bones data begin.
[in] p_end The bones data end.
Referenced by AddBoneDatas().
AddBoneDatas() [2/3]
void Castor3D::Submesh::AddBoneDatas (std::vector< VertexBoneData > const & p_boneData) inline
Adds bone datas.
Parameters
[in] p_boneData The bone datas.
References AddBoneDatas().
AddBoneDatas() [3/3]
template<size_t Count> void Castor3D::Submesh::AddBoneDatas (std::array< VertexBoneData, Count > const & p_boneData) inline
Adds bone datas.
Parameters
[in] p_boneData The bone datas.
References AddBoneDatas().
AddFace()
C3D_API Face Castor3D::Submesh::AddFace (uint32_t a, uint32_t b, uint32_t c)
Creates and adds a face to the submesh.
Parameters
[in] a The first face's vertex index
[in] b The second face's vertex index
[in] c The third face's vertex index
Returns
The created face
AddFaceGroup() [1/4]
C3D_API void Castor3D::Submesh::AddFaceGroup (FaceIndices const *const p_begin, FaceIndices const *const p_end)
Creates and adds faces to the submesh.
Parameters
[in] p_begin The faces data begin.
[in] p_end The faces data end.
Referenced by AddFaceGroup().
AddFaceGroup() [2/4]
void Castor3D::Submesh::AddFaceGroup (std::vector< FaceIndices > const & p_faces) inline
Creates and adds faces to the submesh.
Parameters
[in] p_faces The faces
References AddFaceGroup().
AddFaceGroup() [3/4]
template<size_t Count> void Castor3D::Submesh::AddFaceGroup (std::array< FaceIndices, Count > const & p_faces) inline
Creates and adds faces to the submesh.
Parameters
[in] p_faces The faces
References AddFaceGroup().
AddFaceGroup() [4/4]
template<uint32_t Count> void Castor3D::Submesh::AddFaceGroup (FaceIndices(&) p_faces[Count]) inline
Creates and adds faces to the submesh.
Parameters
[in] p_faces The faces
References AddFaceGroup().
AddPoint() [1/4]
C3D_API BufferElementGroupSPtr Castor3D::Submesh::AddPoint (real x, real y, real z)
Creates and adds a vertex to my list.
Parameters
[in] x The vertex X coordinate
[in] y The vertex Y coordinate
[in] z The vertex Z coordinate
Returns
The created vertex
AddPoint() [2/4]
C3D_API BufferElementGroupSPtr Castor3D::Submesh::AddPoint (Castor::Point3r const & p_v)
Adds a vertex to my list.
Parameters
[in] p_v The vertex to add
Returns
The vertex
AddPoint() [3/4]
C3D_API BufferElementGroupSPtr Castor3D::Submesh::AddPoint (real * p_v)
Creates and adds a vertex to my list.
Parameters
[in] p_v The vertex coordinates
Returns
The created vertex
AddPoint() [4/4]
C3D_API BufferElementGroupSPtr Castor3D::Submesh::AddPoint (InterleavedVertex const & p_v)
Creates and adds a vertex to my list.
Parameters
[in] p_v The vertex.
Returns
The created vertex.
AddPoints() [1/3]
C3D_API void Castor3D::Submesh::AddPoints (InterleavedVertex const *const p_begin, InterleavedVertex const *const p_end)
Adds a points list to my list.
Parameters
[in] p_begin The vertices data begin.
[in] p_end The vertices data end.
Referenced by AddPoints().
AddPoints() [2/3]
void Castor3D::Submesh::AddPoints (std::vector< InterleavedVertex > const & p_vertices) inline
Adds a points list to my list.
Parameters
[in] p_vertices The vertices
References AddPoints().
AddPoints() [3/3]
template<size_t Count> void Castor3D::Submesh::AddPoints (std::array< InterleavedVertex, Count > const & p_vertices) inline
Adds a points list to my list.
Parameters
[in] p_vertices The vertices
References AddPoints().
AddQuadFace()
C3D_API void Castor3D::Submesh::AddQuadFace (uint32_t a, uint32_t b, uint32_t c, uint32_t d, Castor::Point3r const & p_minUV = Castor::Point3r(), Castor::Point3r const & p_maxUV = Castor::Point3r(1, 1, 1))
Creates and adds a quad face to the submesh.
Parameters
[in] a The first face's vertex index
[in] b The second face's vertex index
[in] c The third face's vertex index
[in] d The fourth face's vertex index
[in] p_minUV The UV of the bottom left corner
[in] p_maxUV The UV of the top right corner
Returns
The created face
Cleanup()
C3D_API void Castor3D::Submesh::Cleanup ()
Cleans the submesh.
ClearFaces()
C3D_API void Castor3D::Submesh::ClearFaces ()
Clears this submesh's face array.
ComputeBitangents()
C3D_API void Castor3D::Submesh::ComputeBitangents ()
Computes bitangent for each vertex of the submesh.
Remarks
This function supposes the tangents and normals are defined
ComputeContainers()
C3D_API void Castor3D::Submesh::ComputeContainers ()
Computes the containers (cube and sphere)
ComputeFacesFromPolygonVertex()
C3D_API void Castor3D::Submesh::ComputeFacesFromPolygonVertex ()
Creates faces from the points.
Remarks
This function assumes the points are sorted like triangles fan
ComputeNormals() [1/2]
C3D_API void Castor3D::Submesh::ComputeNormals (bool p_reverted = false)
Generates normals and tangents.
ComputeNormals() [2/2]
C3D_API void Castor3D::Submesh::ComputeNormals (Face const & p_face)
Computes normal and tangent for each vertex of the given face.
Parameters
[in] p_face The face
ComputeTangents()
C3D_API void Castor3D::Submesh::ComputeTangents (Face const & p_face)
Computes tangent for each vertex of the given face.
Parameters
[in] p_face The face
ComputeTangentsFromBitangents()
C3D_API void Castor3D::Submesh::ComputeTangentsFromBitangents ()
Computes tangent for each vertex of the submesh.
Remarks
This function supposes bitangents and normals are defined
ComputeTangentsFromNormals()
C3D_API void Castor3D::Submesh::ComputeTangentsFromNormals ()
Computes tangent for each vertex of the submesh.
Remarks
This function supposes the normals are defined
Draw()
C3D_API void Castor3D::Submesh::Draw (GeometryBuffers const & p_geometryBuffers)
Draws the submesh.
Parameters
[in] p_geometryBuffers The geometry buffers used to draw this submesh.
DrawInstanced()
C3D_API void Castor3D::Submesh::DrawInstanced (GeometryBuffers const & p_geometryBuffers, uint32_t p_count)
Draws the submesh.
Parameters
[in] p_geometryBuffers The geometry buffers used to draw this submesh.
[in] p_count The instances count.
GetAnimationBuffer() [1/2]
VertexBuffer const& Castor3D::Submesh::GetAnimationBuffer () const inline
Returns
The VertexBuffer.
GetAnimationBuffer() [2/2]
VertexBuffer& Castor3D::Submesh::GetAnimationBuffer () inline
Returns
The VertexBuffer.
GetBonesBuffer() [1/2]
VertexBuffer const& Castor3D::Submesh::GetBonesBuffer () const inline
Returns
The bones VertexBuffer.
GetBonesBuffer() [2/2]
VertexBuffer& Castor3D::Submesh::GetBonesBuffer () inline
Returns
The bones VertexBuffer.
GetCollisionBox() [1/2]
Castor::CubeBox const& Castor3D::Submesh::GetCollisionBox () const inline
Returns
The cube bounding box.
GetCollisionBox() [2/2]
Castor::CubeBox& Castor3D::Submesh::GetCollisionBox () inline
Returns
The cube bounding box.
GetCollisionSphere() [1/2]
Castor::SphereBox const& Castor3D::Submesh::GetCollisionSphere () const inline
Returns
The sphere bounding box.
GetCollisionSphere() [2/2]
Castor::SphereBox& Castor3D::Submesh::GetCollisionSphere () inline
Returns
The sphere bounding box.
GetDefaultMaterial()
MaterialSPtr Castor3D::Submesh::GetDefaultMaterial () const inline
Returns
The material.
GetFace()
Face const& Castor3D::Submesh::GetFace (uint32_t p_index) const inline
Retrieves the face at given index.
Parameters
[in] p_index The index
Returns
The value
GetFaceCount()
C3D_API uint32_t Castor3D::Submesh::GetFaceCount () const
Returns
The faces number
GetFaces() [1/2]
FaceArray const& Castor3D::Submesh::GetFaces () const inline
Returns
The faces array.
GetFaces() [2/2]
FaceArray& Castor3D::Submesh::GetFaces () inline
Returns
The faces array.
GetGeometryBuffers()
C3D_API GeometryBuffersSPtr Castor3D::Submesh::GetGeometryBuffers (ShaderProgram const & p_program)
Retrieves a GeometryBuffers for given program.
Parameters
[in] p_program The program.
GetId()
uint32_t Castor3D::Submesh::GetId () const inline
Returns
The submesh ID.
GetIndexBuffer() [1/2]
IndexBuffer const& Castor3D::Submesh::GetIndexBuffer () const inline
Returns
The IndexBuffer.
GetIndexBuffer() [2/2]
IndexBuffer& Castor3D::Submesh::GetIndexBuffer () inline
Returns
The IndexBuffer.
GetMatrixBuffer() [1/2]
VertexBuffer const& Castor3D::Submesh::GetMatrixBuffer () const inline
Returns
The instantiation VertexBuffer.
GetMatrixBuffer() [2/2]
VertexBuffer& Castor3D::Submesh::GetMatrixBuffer () inline
Returns
The instantiation VertexBuffer.
GetParent() [1/2]
Mesh const& Castor3D::Submesh::GetParent () const inline
Returns
The parent mesh.
Referenced by GetSkeleton().
GetParent() [2/2]
Mesh& Castor3D::Submesh::GetParent () inline
Returns
The parent mesh.
GetPoint()
BufferElementGroupSPtr Castor3D::Submesh::GetPoint (uint32_t p_index) const inline
Retrieves the point at given index.
Parameters
[in] p_index The index
Returns
The value
GetPoints() [1/2]
VertexPtrArray const& Castor3D::Submesh::GetPoints () const inline
Returns
The points array.
GetPoints() [2/2]
VertexPtrArray& Castor3D::Submesh::GetPoints () inline
Returns
The points array.
GetPointsCount()
C3D_API uint32_t Castor3D::Submesh::GetPointsCount () const
Returns
The points count
GetProgramFlags()
ProgramFlags const& Castor3D::Submesh::GetProgramFlags () const inline
Returns
The shader program flags.
GetRefCount()
C3D_API uint32_t Castor3D::Submesh::GetRefCount (MaterialSPtr p_material) const
Retrieves the instances count.
Parameters
[in] p_material The material for which the instance count is retrieved
Returns
The value
GetSkeleton()
SkeletonSPtr Castor3D::Submesh::GetSkeleton () const inline
Returns
The skeleton.
References GetParent(), and Castor3D::Mesh::GetSkeleton().
GetTopology()
C3D_API Topology Castor3D::Submesh::GetTopology () const
Returns
The topology.
GetVertexBuffer() [1/2]
VertexBuffer const& Castor3D::Submesh::GetVertexBuffer () const inline
Returns
The VertexBuffer.
GetVertexBuffer() [2/2]
VertexBuffer& Castor3D::Submesh::GetVertexBuffer () inline
Returns
The VertexBuffer.
HasAnimationBuffer()
bool Castor3D::Submesh::HasAnimationBuffer () const inline
Returns
The IndexBuffer.
HasBonesBuffer()
bool Castor3D::Submesh::HasBonesBuffer () const inline
Returns
The bones VertexBuffer.
HasIndexBuffer()
bool Castor3D::Submesh::HasIndexBuffer () const inline
Returns
The IndexBuffer.
HasMatrixBuffer()
bool Castor3D::Submesh::HasMatrixBuffer () const inline
Returns
The instantiation VertexBuffer.
HasVertexBuffer()
bool Castor3D::Submesh::HasVertexBuffer () const inline
Returns
The VertexBuffer.
Initialise()
C3D_API void Castor3D::Submesh::Initialise ()
Initialises the submesh.
IsInitialised()
bool Castor3D::Submesh::IsInitialised () const inline
Returns
The initialisation status.
IsInMyPoints()
C3D_API int Castor3D::Submesh::IsInMyPoints (Castor::Point3r const & p_vertex, double p_precision)
Tests if the given Point3r is in mine.
Parameters
[in] p_vertex The vertex to test
[in] p_precision The comparison precision
Returns
The index of the vertex equal to parameter, -1 if not found
NeedUpdate()
void Castor3D::Submesh::NeedUpdate () inline
Sets the submesh to be updated.
operator[]()
BufferElementGroupSPtr Castor3D::Submesh::operator[] (uint32_t p_index) const inline
Retrieves the point at given index.
Parameters
[in] p_index The index
Returns
The value
Ref()
C3D_API uint32_t Castor3D::Submesh::Ref (MaterialSPtr p_material)
Increments instance count.
Parameters
[in] p_material The material for which the instance count is incremented.
Returns
The previous instance count.
ResetGpuBuffers()
C3D_API void Castor3D::Submesh::ResetGpuBuffers ()
Recreates the buffers.
ResetMatrixBuffers()
C3D_API void Castor3D::Submesh::ResetMatrixBuffers ()
Recreates the Matrix buffers.
SetAnimated()
C3D_API void Castor3D::Submesh::SetAnimated (bool p_animated)
Returns
The animated status.
SetDefaultMaterial()
void Castor3D::Submesh::SetDefaultMaterial (MaterialSPtr p_mat) inline
Sets the material.
Parameters
[in] p_mat The new value
SetTopology()
C3D_API void Castor3D::Submesh::SetTopology (Topology p_value)
Sets the topology.
Parameters
[in] p_value The new value.
SortByDistance()
C3D_API void Castor3D::Submesh::SortByDistance (Castor::Point3r const & p_cameraPosition)
Sorts the face from farthest to nearest from the camera.
Parameters
[in] p_cameraPosition The camera position, relative to submesh
UnRef()
C3D_API uint32_t Castor3D::Submesh::UnRef (MaterialSPtr p_material)
Decrements instance count.
Parameters
[in] p_material The material for which the instance count is decremented.
Returns
The previous instance count.
Friends And Related Function Documentation
BinaryParser< Submesh >
friend class BinaryParser< Submesh > friend
BinaryWriter< Submesh >
friend class BinaryWriter< Submesh > friend
GeometryBuffers
friend class GeometryBuffers friend
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Mesh/Submesh.hpp