Castor3D: castor3d::LpvGridConfigUbo Class Reference
castor3d::LpvGridConfigUbo Class Reference
#include <LpvGridConfigUbo.hpp>
Public Types
using Configuration = LpvGridConfigUboConfiguration
Public Member Functions
C3D_API LpvGridConfigUbo (LpvGridConfigUbo const &rhs)=delete
C3D_API LpvGridConfigUbo & operator= (LpvGridConfigUbo const &rhs)=delete
C3D_API LpvGridConfigUbo (LpvGridConfigUbo &&rhs) noexcept=default
C3D_API LpvGridConfigUbo & operator= (LpvGridConfigUbo &&rhs) noexcept=delete
C3D_API LpvGridConfigUbo (RenderDevice const &device)
C3D_API ~LpvGridConfigUbo () noexcept
C3D_API castor::Grid const & cpuUpdate (castor::BoundingBox const &aabb, castor::Point3f const &cameraPos, uint32_t gridDim, float indirectAttenuation)
C3D_API castor::Grid const & cpuUpdate (float gridLevelScale, castor::Grid const &grid, castor::Point3f const &cameraPos, castor::Point3f const &cameraDir, float indirectAttenuation)
UniformBufferOffsetT< Configuration > & getUbo ()
UniformBufferOffsetT< Configuration > const & getUbo () const
void createPassBinding (crg::FramePass &pass, uint32_t binding) const
void createSizedBinding (ashes::DescriptorSet &descriptorSet, VkDescriptorSetLayoutBinding const &layoutBinding) const
ashes::WriteDescriptorSet getDescriptorWrite (uint32_t dstBinding, uint32_t dstArrayElement=0u) const
void addDescriptorWrite (ashes::WriteDescriptorSetArray &descriptorWrites, uint32_t &dstBinding, uint32_t dstArrayElement=0u) const
Member Typedef Documentation
Configuration
using castor3d::LpvGridConfigUbo::Configuration = LpvGridConfigUboConfiguration
Constructor & Destructor Documentation
LpvGridConfigUbo() [1/3]
C3D_API castor3d::LpvGridConfigUbo::LpvGridConfigUbo (LpvGridConfigUbo const & rhs) delete
LpvGridConfigUbo() [2/3]
C3D_API castor3d::LpvGridConfigUbo::LpvGridConfigUbo (LpvGridConfigUbo && rhs) default noexcept
LpvGridConfigUbo() [3/3]
C3D_API castor3d::LpvGridConfigUbo::LpvGridConfigUbo (RenderDevice const & device) explicit
~LpvGridConfigUbo()
C3D_API castor3d::LpvGridConfigUbo::~LpvGridConfigUbo () noexcept
Member Function Documentation
addDescriptorWrite()
void castor3d::LpvGridConfigUbo::addDescriptorWrite (ashes::WriteDescriptorSetArray & descriptorWrites, uint32_t & dstBinding, uint32_t dstArrayElement = 0u) const inline
References getDescriptorWrite().
cpuUpdate() [1/2]
C3D_API castor::Grid const & castor3d::LpvGridConfigUbo::cpuUpdate (castor::BoundingBox const & aabb, castor::Point3f const & cameraPos, uint32_t gridDim, float indirectAttenuation)
cpuUpdate() [2/2]
C3D_API castor::Grid const & castor3d::LpvGridConfigUbo::cpuUpdate (float gridLevelScale, castor::Grid const & grid, castor::Point3f const & cameraPos, castor::Point3f const & cameraDir, float indirectAttenuation)
createPassBinding()
void castor3d::LpvGridConfigUbo::createPassBinding (crg::FramePass & pass, uint32_t binding) const inline
References castor3d::UniformBufferOffsetT< DataT >::createPassBinding().
createSizedBinding()
void castor3d::LpvGridConfigUbo::createSizedBinding (ashes::DescriptorSet & descriptorSet, VkDescriptorSetLayoutBinding const & layoutBinding) const inline
References castor3d::UniformBufferOffsetT< DataT >::createSizedBinding().
getDescriptorWrite()
ashes::WriteDescriptorSet castor3d::LpvGridConfigUbo::getDescriptorWrite (uint32_t dstBinding, uint32_t dstArrayElement = 0u) const inline
References castor3d::UniformBufferOffsetT< DataT >::getDescriptorWrite().
Referenced by addDescriptorWrite().
getUbo() [1/2]
UniformBufferOffsetT< Configuration > & castor3d::LpvGridConfigUbo::getUbo () inline
getUbo() [2/2]
UniformBufferOffsetT< Configuration > const & castor3d::LpvGridConfigUbo::getUbo () const inline
operator=() [1/2]
C3D_API LpvGridConfigUbo & castor3d::LpvGridConfigUbo::operator= (LpvGridConfigUbo && rhs) delete noexcept
operator=() [2/2]
C3D_API LpvGridConfigUbo & castor3d::LpvGridConfigUbo::operator= (LpvGridConfigUbo const & rhs) delete
The documentation for this class was generated from the following file:
Castor3D/Shader/Ubos/LpvGridConfigUbo.hpp