Castor3D: castor3d::MovableObject Class Reference
castor3d::MovableObject Class Reference
#include <MovableObject.hpp>
Public Member Functions
C3D_API MovableObject (castor::String const &name, Scene &scene, MovableType type, SceneNode &node)
Constructor.
C3D_API MovableObject (castor::String const &name, Scene &scene, MovableType type)
Constructor.
virtual C3D_API ~MovableObject () noexcept
Destructor.
C3D_API void detach ()
Detaches the movable object from it's parent.
virtual C3D_API void attachTo (SceneNode &node)
Attaches the movable object to a node.
C3D_API void markDirty ()
Adds the object to dirty object list in the scene.
C3D_API EngineRPtr getEngine () const noexcept
SceneNode * getParent () const noexcept
MovableType getMovableType () const noexcept
Public Member Functions inherited from castor::OwnedBy< Scene >
Scene * getOwner () const
Public Member Functions inherited from castor::NamedBaseT< T >
NamedBaseT (T name) noexcept
Constructor.
T const & getName () const noexcept
Retrieves the name.
void rename (T name) noexcept
Protected Attributes
MovableType m_type
SceneNode * m_sceneNode {}
OnSceneNodeChangedConnection m_notifyIndex
Protected Attributes inherited from castor::NamedBaseT< T >
T m_name
Additional Inherited Members
Protected Member Functions inherited from castor::OwnedBy< Scene >
OwnedBy (Scene &owner)
Constructor.
Constructor & Destructor Documentation
MovableObject() [1/2]
C3D_API castor3d::MovableObject::MovableObject (castor::String const & name, Scene & scene, MovableType type, SceneNode & node)
Constructor.
Parameters
[in] name The name
[in] scene The parent scene
[in] node Parent node
[in] type MovableObject type
MovableObject() [2/2]
C3D_API castor3d::MovableObject::MovableObject (castor::String const & name, Scene & scene, MovableType type)
Constructor.
Parameters
[in] name The name
[in] scene The parent scene
[in] type MovableObject type
~MovableObject()
virtual C3D_API castor3d::MovableObject::~MovableObject () virtual noexcept
Destructor.
Member Function Documentation
attachTo()
virtual C3D_API void castor3d::MovableObject::attachTo (SceneNode & node) virtual
Attaches the movable object to a node.
Reimplemented in castor3d::BillboardList.
detach()
C3D_API void castor3d::MovableObject::detach ()
Detaches the movable object from it's parent.
getEngine()
C3D_API EngineRPtr castor3d::MovableObject::getEngine () const noexcept
name Getters.
getMovableType()
MovableType castor3d::MovableObject::getMovableType () const inline noexcept
References m_type.
getParent()
SceneNode * castor3d::MovableObject::getParent () const inline noexcept
References m_sceneNode.
markDirty()
C3D_API void castor3d::MovableObject::markDirty ()
Adds the object to dirty object list in the scene.
Referenced by castor3d::Camera::resize(), castor3d::Light::setGlobalIlluminationType(), castor3d::Light::setShadowConfig(), castor3d::Camera::setView(), and castor3d::Camera::setViewportType().
Member Data Documentation
m_notifyIndex
OnSceneNodeChangedConnection castor3d::MovableObject::m_notifyIndex protected
The node change notification index.
m_sceneNode
SceneNode* castor3d::MovableObject::m_sceneNode {} protected
The parent scene node.
Referenced by getParent().
m_type
MovableType castor3d::MovableObject::m_type protected
Movable object type.
Referenced by getMovableType().
The documentation for this class was generated from the following file:
Castor3D/Scene/MovableObject.hpp