Castor3D: castor3d::SceneUbo Class Reference
castor3d::SceneUbo Class Reference
#include <SceneUbo.hpp>
Public Member Functions
C3D_API SceneUbo (SceneUbo const &rhs)=delete
C3D_API SceneUbo & operator= (SceneUbo const &rhs)=delete
C3D_API SceneUbo (SceneUbo &&rhs) noexcept=default
C3D_API SceneUbo & operator= (SceneUbo &&rhs) noexcept=delete
C3D_API SceneUbo (RenderDevice const &device)
C3D_API ~SceneUbo () noexcept
C3D_API Configuration & cpuUpdate (Fog const &fog)
Updates the UBO from given values.
C3D_API Configuration & cpuUpdate (Scene const &scene)
Updates the UBO from given values.
void createPassBinding (crg::FramePass &pass, uint32_t binding) const
void createSizedBinding (ashes::DescriptorSet &descriptorSet, VkDescriptorSetLayoutBinding const &layoutBinding) const
ashes::WriteDescriptorSet getDescriptorWrite (uint32_t dstBinding, uint32_t dstArrayElement=0u) const
UniformBufferOffsetT< Configuration > const & getUbo () const
Constructor & Destructor Documentation
SceneUbo() [1/3]
C3D_API castor3d::SceneUbo::SceneUbo (SceneUbo const & rhs) delete
SceneUbo() [2/3]
C3D_API castor3d::SceneUbo::SceneUbo (SceneUbo && rhs) default noexcept
SceneUbo() [3/3]
C3D_API castor3d::SceneUbo::SceneUbo (RenderDevice const & device) explicit
~SceneUbo()
C3D_API castor3d::SceneUbo::~SceneUbo () noexcept
Member Function Documentation
cpuUpdate() [1/2]
C3D_API Configuration & castor3d::SceneUbo::cpuUpdate (Fog const & fog)
Updates the UBO from given values.
Parameters
[in] fog The fog configuration.
cpuUpdate() [2/2]
C3D_API Configuration & castor3d::SceneUbo::cpuUpdate (Scene const & scene)
Updates the UBO from given values.
Parameters
[in] scene The rendered scene.
createPassBinding()
void castor3d::SceneUbo::createPassBinding (crg::FramePass & pass, uint32_t binding) const inline
References castor3d::UniformBufferOffsetT< DataT >::createPassBinding().
createSizedBinding()
void castor3d::SceneUbo::createSizedBinding (ashes::DescriptorSet & descriptorSet, VkDescriptorSetLayoutBinding const & layoutBinding) const inline
References castor3d::UniformBufferOffsetT< DataT >::createSizedBinding().
getDescriptorWrite()
ashes::WriteDescriptorSet castor3d::SceneUbo::getDescriptorWrite (uint32_t dstBinding, uint32_t dstArrayElement = 0u) const inline
References castor3d::UniformBufferOffsetT< DataT >::getDescriptorWrite().
getUbo()
UniformBufferOffsetT< Configuration > const & castor3d::SceneUbo::getUbo () const inline
operator=() [1/2]
C3D_API SceneUbo & castor3d::SceneUbo::operator= (SceneUbo && rhs) delete noexcept
operator=() [2/2]
C3D_API SceneUbo & castor3d::SceneUbo::operator= (SceneUbo const & rhs) delete
The documentation for this class was generated from the following file:
Castor3D/Shader/Ubos/SceneUbo.hpp