Castor3D: castor3d::ObjectBufferOffset::GpuBufferChunk Struct Reference
castor3d::ObjectBufferOffset::GpuBufferChunk Struct Reference
#include <ObjectBufferOffset.hpp>
Public Member Functions
ashes::BufferBase const & getBuffer () const
bool hasData () const
uint32_t getSize () const
template<typename DataT >
castor::ArrayView< DataT > getData () const
template<typename DataT >
uint32_t getCount () const
VkDeviceSize getOffset () const
template<typename DataT >
uint32_t getFirst () const
void markDirty (VkAccessFlags dstAccessFlags=VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT, VkPipelineStageFlags dstPipelineFlags=VK_PIPELINE_STAGE_VERTEX_INPUT_BIT) const
void reset ()
void directUpload (ashes::Queue const &queue, ashes::CommandPool const &commandPool, VkAccessFlags dstAccessFlags, VkPipelineStageFlags dstPipelineFlags)
void createUniformPassBinding (crg::FramePass &pass, uint32_t binding, std::string const &name) const
void createInputStoragePassBinding (crg::FramePass &pass, uint32_t binding, std::string const &name) const
void createInOutStoragePassBinding (crg::FramePass &pass, uint32_t binding, std::string const &name) const
void createOutputStoragePassBinding (crg::FramePass &pass, uint32_t binding, std::string const &name) const
ashes::WriteDescriptorSet getUniformBinding (uint32_t binding) const
ashes::WriteDescriptorSet getStorageBinding (uint32_t binding) const
Public Attributes
GpuPackedBuffer * buffer {}
MemChunk chunk {}
Member Function Documentation
createInOutStoragePassBinding()
void castor3d::ObjectBufferOffset::GpuBufferChunk::createInOutStoragePassBinding (crg::FramePass & pass, uint32_t binding, std::string const & name) const inline
References castor3d::createInOutStoragePassBinding(), getBuffer(), getOffset(), and getSize().
Referenced by castor3d::ObjectBufferOffset::createInOutStoragePassBinding().
createInputStoragePassBinding()
void castor3d::ObjectBufferOffset::GpuBufferChunk::createInputStoragePassBinding (crg::FramePass & pass, uint32_t binding, std::string const & name) const inline
References castor3d::createInputStoragePassBinding(), getBuffer(), getOffset(), and getSize().
Referenced by castor3d::ObjectBufferOffset::createInputStoragePassBinding().
createOutputStoragePassBinding()
void castor3d::ObjectBufferOffset::GpuBufferChunk::createOutputStoragePassBinding (crg::FramePass & pass, uint32_t binding, std::string const & name) const inline
References castor3d::createOutputStoragePassBinding(), getBuffer(), getOffset(), and getSize().
Referenced by castor3d::ObjectBufferOffset::createOutputStoragePassBinding().
createUniformPassBinding()
void castor3d::ObjectBufferOffset::GpuBufferChunk::createUniformPassBinding (crg::FramePass & pass, uint32_t binding, std::string const & name) const inline
References castor3d::createUniformPassBinding(), getBuffer(), getOffset(), and getSize().
Referenced by castor3d::ObjectBufferOffset::createUniformPassBinding().
directUpload()
void castor3d::ObjectBufferOffset::GpuBufferChunk::directUpload (ashes::Queue const & queue, ashes::CommandPool const & commandPool, VkAccessFlags dstAccessFlags, VkPipelineStageFlags dstPipelineFlags) inline
References castor3d::MemChunk::askedSize, buffer, chunk, castor3d::MemChunk::offset, and castor3d::GpuBufferBase::uploadDirect().
Referenced by castor3d::ObjectBufferOffset::directUpload().
getBuffer()
ashes::BufferBase const & castor3d::ObjectBufferOffset::GpuBufferChunk::getBuffer () const inline
References buffer, and castor3d::GpuBufferBase::getBuffer().
Referenced by createInOutStoragePassBinding(), createInputStoragePassBinding(), createOutputStoragePassBinding(), createUniformPassBinding(), castor3d::ObjectBufferOffset::getBuffer(), getStorageBinding(), and getUniformBinding().
getCount()
template<typename DataT > uint32_t castor3d::ObjectBufferOffset::GpuBufferChunk::getCount () const inline
References getSize().
Referenced by castor3d::ObjectBufferOffset::getCount().
getData()
template<typename DataT > castor::ArrayView< DataT > castor3d::ObjectBufferOffset::GpuBufferChunk::getData () const inline
References castor3d::MemChunk::askedSize, buffer, chunk, castor3d::GpuBufferBase::getDatas(), getOffset(), and hasData().
Referenced by castor3d::ObjectBufferOffset::getData().
getFirst()
template<typename DataT > uint32_t castor3d::ObjectBufferOffset::GpuBufferChunk::getFirst () const inline
References getOffset().
Referenced by castor3d::ObjectBufferOffset::getFirst().
getOffset()
VkDeviceSize castor3d::ObjectBufferOffset::GpuBufferChunk::getOffset () const inline
References chunk, and castor3d::MemChunk::offset.
Referenced by createInOutStoragePassBinding(), createInputStoragePassBinding(), createOutputStoragePassBinding(), createUniformPassBinding(), getData(), getFirst(), castor3d::ObjectBufferOffset::getOffset(), getStorageBinding(), getUniformBinding(), and markDirty().
getSize()
uint32_t castor3d::ObjectBufferOffset::GpuBufferChunk::getSize () const inline
References castor3d::MemChunk::askedSize, and chunk.
Referenced by createInOutStoragePassBinding(), createInputStoragePassBinding(), createOutputStoragePassBinding(), createUniformPassBinding(), getCount(), castor3d::ObjectBufferOffset::getSize(), getStorageBinding(), getUniformBinding(), and markDirty().
getStorageBinding()
ashes::WriteDescriptorSet castor3d::ObjectBufferOffset::GpuBufferChunk::getStorageBinding (uint32_t binding) const inline
References getBuffer(), getOffset(), and getSize().
Referenced by castor3d::ObjectBufferOffset::getStorageBinding().
getUniformBinding()
ashes::WriteDescriptorSet castor3d::ObjectBufferOffset::GpuBufferChunk::getUniformBinding (uint32_t binding) const inline
References getBuffer(), getOffset(), and getSize().
Referenced by castor3d::ObjectBufferOffset::getUniformBinding().
hasData()
bool castor3d::ObjectBufferOffset::GpuBufferChunk::hasData () const inline
References castor3d::MemChunk::askedSize, and chunk.
Referenced by getData(), and castor3d::ObjectBufferOffset::hasData().
markDirty()
void castor3d::ObjectBufferOffset::GpuBufferChunk::markDirty (VkAccessFlags dstAccessFlags = VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT, VkPipelineStageFlags dstPipelineFlags = VK_PIPELINE_STAGE_VERTEX_INPUT_BIT) const inline
References buffer, getOffset(), getSize(), and castor3d::GpuBufferBase::markDirty().
Referenced by castor3d::ObjectBufferOffset::markDirty().
reset()
void castor3d::ObjectBufferOffset::GpuBufferChunk::reset () inline
References castor3d::MemChunk::askedSize, buffer, chunk, castor3d::MemChunk::offset, and castor3d::MemChunk::size.
Member Data Documentation
buffer
GpuPackedBuffer* castor3d::ObjectBufferOffset::GpuBufferChunk::buffer {}
Referenced by directUpload(), getBuffer(), getData(), markDirty(), and reset().
chunk
MemChunk castor3d::ObjectBufferOffset::GpuBufferChunk::chunk {}
Referenced by directUpload(), getData(), getOffset(), getSize(), hasData(), and reset().
The documentation for this struct was generated from the following file:
Buffer/ObjectBufferOffset.hpp