Castor3D: castor3d::BonesComponent Class Reference
castor3d::BonesComponent Class Reference
Public Member Functions
C3D_API BonesComponent (Submesh &submesh)
Constructor.
C3D_API void addBoneDatas (VertexBoneData const *const begin, VertexBoneData const *const end)
adds bone datas.
C3D_API SkeletonSPtr getSkeleton () const
C3D_API void gather (MaterialSPtr material, ashes::BufferCRefArray &buffers, std::vector< uint64_t > &offsets, ashes::PipelineVertexInputStateCreateInfoCRefArray &layouts, uint32_t instanceMult) override
Gathers buffers that need to go in a VAO.
C3D_API void addBoneDatas (std::vector< VertexBoneData > const &boneData)
adds bone datas.
template<size_t Count>
void addBoneDatas (std::array< VertexBoneData, Count > const &boneData)
adds bone datas.
bool hasBoneData () const
VertexBoneDataArray const & getBonesData () const
ashes::VertexBuffer< VertexBoneData > const & getBonesBuffer () const
ashes::VertexBuffer< VertexBoneData > & getBonesBuffer ()
ProgramFlags getProgramFlags (MaterialSPtr material) const override
Public Member Functions inherited from castor3d::SubmeshComponent
C3D_API SubmeshComponent (Submesh &submesh, castor::String const &type)
Constructor.
virtual C3D_API ~SubmeshComponent () noexcept=default
Destructor.
C3D_API bool initialise (RenderDevice const &device)
Initialises the submesh.
C3D_API void cleanup ()
Cleans the submesh.
C3D_API void fill (RenderDevice const &device)
Initialises the submesh.
C3D_API void upload ()
Uploads data on VRAM.
virtual C3D_API void setMaterial (MaterialSPtr oldMaterial, MaterialSPtr newMaterial, bool update)
Sets the material.
castor::String const & getType () const
void needsUpdate ()
Sets the component to be updated.
Static Public Attributes
static C3D_API castor::String const Name
static C3D_API uint32_t constexpr BindingPoint = 3u
Friends
class BinaryWriter< BonesComponent >
class BinaryParser< BonesComponent >
Constructor & Destructor Documentation
BonesComponent()
C3D_API castor3d::BonesComponent::BonesComponent (Submesh & submesh) explicit
Constructor.
Parameters
[in] submesh The parent submesh.
Member Function Documentation
addBoneDatas() [1/3]
C3D_API void castor3d::BonesComponent::addBoneDatas (VertexBoneData const *const begin, VertexBoneData const *const end)
adds bone datas.
Parameters
[in] begin The bones data begin.
[in] end The bones data end.
Referenced by addBoneDatas().
addBoneDatas() [2/3]
C3D_API void castor3d::BonesComponent::addBoneDatas (std::vector< VertexBoneData > const & boneData)
adds bone datas.
Parameters
[in] boneData The bone datas.
addBoneDatas() [3/3]
template<size_t Count> void castor3d::BonesComponent::addBoneDatas (std::array< VertexBoneData, Count > const & boneData) inline
adds bone datas.
Parameters
[in] boneData The bone datas.
References addBoneDatas().
gather()
C3D_API void castor3d::BonesComponent::gather (MaterialSPtr material, ashes::BufferCRefArray & buffers, std::vector< uint64_t > & offsets, ashes::PipelineVertexInputStateCreateInfoCRefArray & layouts, uint32_t instanceMult) override virtual
Gathers buffers that need to go in a VAO.
Implements castor3d::SubmeshComponent.
getBonesBuffer() [1/2]
ashes::VertexBuffer< VertexBoneData > const& castor3d::BonesComponent::getBonesBuffer () const inline
Returns
The bones VertexBuffer.
getBonesBuffer() [2/2]
ashes::VertexBuffer< VertexBoneData >& castor3d::BonesComponent::getBonesBuffer () inline
Returns
The bones VertexBuffer.
getBonesData()
VertexBoneDataArray const& castor3d::BonesComponent::getBonesData () const inline
Returns
The bone data.
getProgramFlags()
ProgramFlags castor3d::BonesComponent::getProgramFlags (MaterialSPtr material) const inline override virtual
Returns
The shader program flags.
Implements castor3d::SubmeshComponent.
References castor3d::eSkinning, and hasBoneData().
getSkeleton()
C3D_API SkeletonSPtr castor3d::BonesComponent::getSkeleton () const
Returns
The skeleton.
Referenced by castor3d::BonesInstantiationComponent::getSkeleton().
hasBoneData()
bool castor3d::BonesComponent::hasBoneData () const inline
Returns
true if the submesh has bone data.
Referenced by getProgramFlags().
Friends And Related Function Documentation
BinaryParser< BonesComponent >
friend class BinaryParser< BonesComponent > friend
BinaryWriter< BonesComponent >
friend class BinaryWriter< BonesComponent > friend
Member Data Documentation
BindingPoint
C3D_API uint32_t constexpr castor3d::BonesComponent::BindingPoint = 3u static
Name
C3D_API castor::String const castor3d::BonesComponent::Name static
The documentation for this class was generated from the following file:
Model/Mesh/Submesh/Component/BonesComponent.hpp