Castor3D: Castor3D::CpuBuffer< T > Class Template Reference
Castor3D::CpuBuffer< T > Class Template Reference
3D Buffer management class
Public Member Functions
void Destroy ()
Destruction function.
void Cleanup ()
Cleanup function.
bool Initialise (eBUFFER_ACCESS_TYPE p_type, eBUFFER_ACCESS_NATURE p_nature)
Initialisation function, initialises GPU buffer.
T * Lock (uint32_t p_offset, uint32_t p_count, uint32_t p_flags)
Locks the buffer, id est maps it into memory so we can modify it.
void Unlock ()
Unlocks the buffer, id est unmaps it from memory so no modification can be made after that.
bool Fill (T const *p_buffer, ptrdiff_t p_size, Castor3D::eBUFFER_ACCESS_TYPE p_type, Castor3D::eBUFFER_ACCESS_NATURE p_nature)
Transmits data to the GPU buffer from RAM.
bool Bind ()
Activation function, to tell the GPU it is active.
void Unbind ()
Deactivation function, to tell the GPU it is inactive.
void SetElement (uint32_t p_index, T const &p_value)
Sets element value at given index.
void AddElement (T const &p_value)
Adds a value at the end of the buffer.
uint32_t GetSize () const
Retrieves the filled buffer size.
uint32_t GetCapacity () const
Retrieves the allocated buffer size.
void Resize (uint32_t p_uiNewSize)
Sets the allocated size of the buffer.
void Reserve (uint32_t p_uiIncrement)
Increases the allocated size of the buffer.
void Clear ()
Clears the buffer.
bool IsToDelete () const
Retrieves the delete status of the buffer.
bool IsAssigned () const
Retrieves the assignment status of the buffer.
GpuBufferSPtr GetGpuBuffer () const
Retrieves the GPU buffer.
void Assign ()
Sets the assignment status to true.
void Unassign ()
Sets the assignment status to false.
T const * data () const
Retrieves the data pointer.
T * data ()
Retrieves the data pointer.
Protected Types
typedef std::shared_ptr< GpuBuffer< T > > GpuBufferSPtr
typedef std::weak_ptr< GpuBuffer< T > > GpuBufferWPtr
typedef std::weak_ptr< CpuBuffer< T > > CpuBufferWPtr
Protected Member Functions
DECLARE_TPL_VECTOR (T, T)
CpuBuffer (Engine &p_engine)
Constructor.
~CpuBuffer ()
Destructor.
Protected Attributes
bool m_bToDelete
Tells the buffer is to be deleted at next render loop.
bool m_bAssigned
Tells the buffer has it's GPU buffer assigned.
GpuBufferSPtr m_pBuffer
The GPU buffer.
TArray m_arrayData
The buffer data.
uint32_t m_uiSavedSize
Detailed Description
template<typename T>
class Castor3D::CpuBuffer< T >
3D Buffer management class
Author
Sylvain DOREMUS
Version
0.1
Date
09/02/2010
Remarks
Class which holds the buffers used in 3D (texture, VBO ...)
Not to be used to manage usual buffers of data, use Castor::Buffer for that
Member Typedef Documentation
CpuBufferWPtr
template<typename T> typedef std::weak_ptr< CpuBuffer< T > > Castor3D::CpuBuffer< T >::CpuBufferWPtr protected
GpuBufferSPtr
template<typename T> typedef std::shared_ptr< GpuBuffer< T > > Castor3D::CpuBuffer< T >::GpuBufferSPtr protected
GpuBufferWPtr
template<typename T> typedef std::weak_ptr< GpuBuffer< T > > Castor3D::CpuBuffer< T >::GpuBufferWPtr protected
Constructor & Destructor Documentation
CpuBuffer()
template<typename T> Castor3D::CpuBuffer< T >::CpuBuffer (Engine & p_engine) inline protected
Constructor.
Parameters
[in] p_engine The engine
~CpuBuffer()
template<typename T> Castor3D::CpuBuffer< T >::~CpuBuffer () inline protected
Destructor.
Member Function Documentation
AddElement()
template<typename T> void Castor3D::CpuBuffer< T >::AddElement (T const & p_value) inline
Adds a value at the end of the buffer.
Parameters
[in] p_value The value
Assign()
template<typename T> void Castor3D::CpuBuffer< T >::Assign () inline
Sets the assignment status to true.
Bind()
template<typename T> bool Castor3D::CpuBuffer< T >::Bind () inline
Activation function, to tell the GPU it is active.
Returns
true if successful
Cleanup()
template<typename T> void Castor3D::CpuBuffer< T >::Cleanup (void) inline
Cleanup function.
Clear()
template<typename T> void Castor3D::CpuBuffer< T >::Clear () inline
Clears the buffer.
data() [1/2]
template<typename T> T const* Castor3D::CpuBuffer< T >::data () const inline
Retrieves the data pointer.
Returns
The data pointer
Referenced by Castor3D::VertexBuffer::LinkCoords().
data() [2/2]
template<typename T> T* Castor3D::CpuBuffer< T >::data () inline
Retrieves the data pointer.
Returns
The data pointer
DECLARE_TPL_VECTOR()
template<typename T> Castor3D::CpuBuffer< T >::DECLARE_TPL_VECTOR (T , T) protected
Destroy()
template<typename T> void Castor3D::CpuBuffer< T >::Destroy () inline
Destruction function.
Fill()
template<typename T> bool Castor3D::CpuBuffer< T >::Fill (T const * p_buffer, ptrdiff_t p_size, Castor3D::eBUFFER_ACCESS_TYPE p_type, Castor3D::eBUFFER_ACCESS_NATURE p_nature) inline
Transmits data to the GPU buffer from RAM.
Parameters
[in] p_buffer The data
[in] p_size Data buffer size
[in] p_type Transfer type
[in] p_nature Transfer nature
Returns
true if successful
GetCapacity()
template<typename T> uint32_t Castor3D::CpuBuffer< T >::GetCapacity () const inline
Retrieves the allocated buffer size.
Returns
The size
Referenced by Castor3D::CpuBuffer< uint8_t >::Reserve().
GetGpuBuffer()
template<typename T> GpuBufferSPtr Castor3D::CpuBuffer< T >::GetGpuBuffer () const inline
Retrieves the GPU buffer.
Returns
The GPU buffer
Referenced by Castor3D::CpuBuffer< uint8_t >::Bind(), Castor3D::CpuBuffer< uint8_t >::Cleanup(), Castor3D::CpuBuffer< uint8_t >::Destroy(), Castor3D::CpuBuffer< uint8_t >::Fill(), Castor3D::CpuBuffer< uint8_t >::Initialise(), Castor3D::CpuBuffer< uint8_t >::Lock(), Castor3D::CpuBuffer< uint8_t >::Unbind(), and Castor3D::CpuBuffer< uint8_t >::Unlock().
GetSize()
template<typename T> uint32_t Castor3D::CpuBuffer< T >::GetSize () const inline
Retrieves the filled buffer size.
Returns
The size
Initialise()
template<typename T> bool Castor3D::CpuBuffer< T >::Initialise (eBUFFER_ACCESS_TYPE p_type, eBUFFER_ACCESS_NATURE p_nature) inline
Initialisation function, initialises GPU buffer.
Parameters
[in] p_type Buffer access type
[in] p_nature Buffer access nature
Returns
true if OK
IsAssigned()
template<typename T> bool Castor3D::CpuBuffer< T >::IsAssigned () const inline
Retrieves the assignment status of the buffer.
Returns
The assignment status
IsToDelete()
template<typename T> bool Castor3D::CpuBuffer< T >::IsToDelete () const inline
Retrieves the delete status of the buffer.
Returns
The delete status
Lock()
template<typename T> T* Castor3D::CpuBuffer< T >::Lock (uint32_t p_offset, uint32_t p_count, uint32_t p_flags) inline
Locks the buffer, id est maps it into memory so we can modify it.
Remarks
Maps from buffer[p_offset*sizeof(T)] to buffer[(p_offset+p_uiSize-1)*sizeof(T)]
Parameters
[in] p_offset The start offset in the buffer
[in] p_count The mapped elements count
[in] p_flags The lock flags
Returns
The mapped buffer address
Reserve()
template<typename T> void Castor3D::CpuBuffer< T >::Reserve (uint32_t p_uiIncrement) inline
Increases the allocated size of the buffer.
Parameters
[in] p_uiIncrement The size increment
Resize()
template<typename T> void Castor3D::CpuBuffer< T >::Resize (uint32_t p_uiNewSize) inline
Sets the allocated size of the buffer.
Parameters
[in] p_uiNewSize The new size
SetElement()
template<typename T> void Castor3D::CpuBuffer< T >::SetElement (uint32_t p_index, T const & p_value) inline
Sets element value at given index.
Parameters
[in] p_index The index
[in] p_value The value
Unassign()
template<typename T> void Castor3D::CpuBuffer< T >::Unassign () inline
Sets the assignment status to false.
Unbind()
template<typename T> void Castor3D::CpuBuffer< T >::Unbind () inline
Deactivation function, to tell the GPU it is inactive.
Returns
true if successful
Unlock()
template<typename T> void Castor3D::CpuBuffer< T >::Unlock () inline
Unlocks the buffer, id est unmaps it from memory so no modification can be made after that.
Remarks
All modifications made in the mapped buffer are put into GPU memory
Member Data Documentation
m_arrayData
template<typename T> TArray Castor3D::CpuBuffer< T >::m_arrayData protected
The buffer data.
The saved buffer size (to still have a size after clear)
Referenced by Castor3D::CpuBuffer< uint8_t >::AddElement(), Castor3D::CpuBuffer< uint8_t >::Clear(), Castor3D::CpuBuffer< uint8_t >::data(), Castor3D::CpuBuffer< uint8_t >::GetCapacity(), Castor3D::CpuBuffer< uint8_t >::GetSize(), Castor3D::CpuBuffer< uint8_t >::Reserve(), Castor3D::CpuBuffer< uint8_t >::Resize(), and Castor3D::CpuBuffer< uint8_t >::SetElement().
m_bAssigned
template<typename T> bool Castor3D::CpuBuffer< T >::m_bAssigned protected
Tells the buffer has it's GPU buffer assigned.
Referenced by Castor3D::CpuBuffer< uint8_t >::Assign(), Castor3D::CpuBuffer< uint8_t >::IsAssigned(), and Castor3D::CpuBuffer< uint8_t >::Unassign().
m_bToDelete
template<typename T> bool Castor3D::CpuBuffer< T >::m_bToDelete protected
Tells the buffer is to be deleted at next render loop.
Referenced by Castor3D::CpuBuffer< uint8_t >::IsToDelete().
m_pBuffer
template<typename T> GpuBufferSPtr Castor3D::CpuBuffer< T >::m_pBuffer protected
The GPU buffer.
Referenced by Castor3D::CpuBuffer< uint8_t >::Destroy(), and Castor3D::CpuBuffer< uint8_t >::GetGpuBuffer().
m_uiSavedSize
template<typename T> uint32_t Castor3D::CpuBuffer< T >::m_uiSavedSize protected
Referenced by Castor3D::CpuBuffer< uint8_t >::Clear(), and Castor3D::CpuBuffer< uint8_t >::GetSize().
The documentation for this class was generated from the following files:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Castor3DPrerequisites_Render.hpp
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/CpuBuffer.hpp