Castor3D: castor3d::ChunkParser< castor::String > Class Template Reference
castor3d::ChunkParser< castor::String > Class Template Reference
ChunkParser specialisation for castor::String.
Static Public Member Functions
static bool parse (castor::String &p_value, BinaryChunk &p_chunk)
Retrieves a value from a chunk.
Static Public Member Functions inherited from castor3d::ChunkParserBase
static bool parse (uint8_t *p_values, size_t p_size, BinaryChunk &p_chunk)
Retrieves a value array from a chunk.
Detailed Description
template<>
class castor3d::ChunkParser< castor::String >
ChunkParser specialisation for castor::String.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
08/04/2014
Member Function Documentation
parse()
static bool castor3d::ChunkParser< castor::String >::parse (castor::String & p_value, BinaryChunk & p_chunk) inline static
Retrieves a value from a chunk.
Parameters
[out] p_value Receives the parsed value
[in] p_chunk The chunk containing the value
Returns
false if any error occured
References castor3d::BinaryChunk::checkAvailable(), castor3d::BinaryChunk::getRemaining(), and castor3d::ChunkParserBase::parse().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Binary/ChunkParser.hpp