Castor3D: Castor3D::ChunkParser< T > Class Template Reference
Castor3D::ChunkParser< T > Class Template Reference
Chunk parser.
Public Member Functions
bool operator() (T *p_values, uint32_t p_count, BinaryChunk &p_chunk)
Retrieves a value array from a chunk.
template<uint32_t Count>
bool operator() (T(&p_values)[Count], BinaryChunk &p_chunk)
Retrieves a value array from a chunk.
bool operator() (T &p_value, BinaryChunk &p_chunk)
Retrieves a value from a chunk.
Public Member Functions inherited from Castor3D::ChunkParserBase
bool operator() (uint8_t *p_pValues, uint32_t p_uiSize, BinaryChunk &p_chunk)
Retrieves a value array from a chunk.
Detailed Description
template<typename T>
class Castor3D::ChunkParser< T >
Chunk parser.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
08/04/2014
Member Function Documentation
operator()() [1/3]
template<typename T > bool Castor3D::ChunkParser< T >::operator() (T * p_values, uint32_t p_count, BinaryChunk & p_chunk) inline
Retrieves a value array from a chunk.
Parameters
[out] p_values Receives the parsed values
[out] p_count The values count
[in] p_chunk The chunk containing the values
Returns
false if any error occured
References Castor3D::ChunkParserBase::operator()().
operator()() [2/3]
template<typename T > template<uint32_t Count> bool Castor3D::ChunkParser< T >::operator() (T(&) p_values[Count], BinaryChunk & p_chunk) inline
Retrieves a value array from a chunk.
Parameters
[out] p_values Receives the parsed values
[in] p_chunk The chunk containing the values
Returns
false if any error occured
References Castor3D::ChunkParserBase::operator()().
operator()() [3/3]
template<typename T > bool Castor3D::ChunkParser< T >::operator() (T & p_value, BinaryChunk & p_chunk) inline
Retrieves a value from a chunk.
Parameters
[out] p_value Receives the parsed value
[in] p_chunk The chunk containing the value
Returns
false if any error occured
References Castor3D::ChunkParserBase::operator()().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/ChunkParser.hpp