Castor3D: castor3d::shader::DebugOutput Class Reference
castor3d::shader::DebugOutput Class Reference
#include <GlslDebugOutput.hpp>
Public Member Functions
C3D_API DebugOutput (DebugConfig &config, castor::String category, sdw::UInt const index, sdw::Vec4 const output, bool enable)
C3D_API ~DebugOutput () noexcept
C3D_API void registerOutput (castor::String category, castor::String name, sdw::Vec4 const value)
C3D_API void registerOutput (castor::String category, castor::String name, sdw::Vec3 const value)
C3D_API void registerOutput (castor::String category, castor::String name, sdw::Vec2 const value)
C3D_API void registerOutput (castor::String category, castor::String name, sdw::Float const value)
C3D_API DebugOutputCategory pushBlock (castor::String category)
template<typename ValueT >
void registerOutput (castor::String name, ValueT const value)
bool isEnabled () const
Friends
class DebugOutputCategory
Constructor & Destructor Documentation
DebugOutput()
C3D_API castor3d::shader::DebugOutput::DebugOutput (DebugConfig & config, castor::String category, sdw::UInt const index, sdw::Vec4 const output, bool enable)
~DebugOutput()
C3D_API castor3d::shader::DebugOutput::~DebugOutput () noexcept
Member Function Documentation
isEnabled()
bool castor3d::shader::DebugOutput::isEnabled () const inline
pushBlock()
C3D_API DebugOutputCategory castor3d::shader::DebugOutput::pushBlock (castor::String category)
registerOutput() [1/5]
C3D_API void castor3d::shader::DebugOutput::registerOutput (castor::String category, castor::String name, sdw::Float const value)
registerOutput() [2/5]
C3D_API void castor3d::shader::DebugOutput::registerOutput (castor::String category, castor::String name, sdw::Vec2 const value)
registerOutput() [3/5]
C3D_API void castor3d::shader::DebugOutput::registerOutput (castor::String category, castor::String name, sdw::Vec3 const value)
registerOutput() [4/5]
C3D_API void castor3d::shader::DebugOutput::registerOutput (castor::String category, castor::String name, sdw::Vec4 const value)
Referenced by registerOutput(), and castor3d::shader::DebugOutputCategory::registerOutput().
registerOutput() [5/5]
template<typename ValueT > void castor3d::shader::DebugOutput::registerOutput (castor::String name, ValueT const value) inline
References registerOutput().
Friends And Related Symbol Documentation
DebugOutputCategory
friend class DebugOutputCategory friend
The documentation for this class was generated from the following file:
Castor3D/Shader/Shaders/GlslDebugOutput.hpp