Castor3D: castor3d::EnvironmentMap Class Reference
castor3d::EnvironmentMap Class Reference
Reflection mapping implementation.
Public Types
using CubeMatrices = std::array< castor::Matrix4x4r, size_t(CubeMapFace::eCount) >
using CubeColourAttachment = std::array< TextureAttachmentSPtr, size_t(CubeMapFace::eCount) >
using CubeCameras = std::array< CameraSPtr, size_t(CubeMapFace::eCount) >
using CubeDepthAttachment = RenderBufferAttachmentSPtr
using EnvironmentMapPasses = std::array< std::unique_ptr< EnvironmentMapPass >, size_t(CubeMapFace::eCount) >
Public Member Functions
C3D_API EnvironmentMap (Engine &engine, SceneNode &p_node)
Constructor.
C3D_API ~EnvironmentMap ()
Destructor.
C3D_API bool initialise ()
Initialises the frame buffer.
C3D_API void cleanup ()
Cleans up the frame buffer.
C3D_API void update (RenderQueueArray &p_queues)
Updates the passes.
C3D_API void render ()
Renders the environment map.
C3D_API void debugDisplay (castor::Size const &size, uint32_t index)
Dumps the environment map on screen.
TextureUnit & getTexture ()
TextureUnit const & getTexture () const
castor::Size getSize () const
uint32_t getIndex () const
Detailed Description
Reflection mapping implementation.
Author
Sylvain DOREMUS
Version
0.9.0
Date
30/08/2016
Member Typedef Documentation
CubeCameras
using castor3d::EnvironmentMap::CubeCameras = std::array< CameraSPtr, size_t (CubeMapFace::eCount) >
CubeColourAttachment
using castor3d::EnvironmentMap::CubeColourAttachment = std::array< TextureAttachmentSPtr, size_t (CubeMapFace::eCount) >
CubeDepthAttachment
using castor3d::EnvironmentMap::CubeDepthAttachment = RenderBufferAttachmentSPtr
CubeMatrices
using castor3d::EnvironmentMap::CubeMatrices = std::array< castor::Matrix4x4r, size_t (CubeMapFace::eCount) >
EnvironmentMapPasses
using castor3d::EnvironmentMap::EnvironmentMapPasses = std::array< std::unique_ptr< EnvironmentMapPass >, size_t (CubeMapFace::eCount) >
Constructor & Destructor Documentation
EnvironmentMap()
C3D_API castor3d::EnvironmentMap::EnvironmentMap (Engine & engine, SceneNode & p_node)
Constructor.
Parameters
[in] engine The engine.
[in] p_node The scene node.
~EnvironmentMap()
C3D_API castor3d::EnvironmentMap::~EnvironmentMap ()
Destructor.
Member Function Documentation
cleanup()
C3D_API void castor3d::EnvironmentMap::cleanup ()
Cleans up the frame buffer.
debugDisplay()
C3D_API void castor3d::EnvironmentMap::debugDisplay (castor::Size const & size, uint32_t index)
Dumps the environment map on screen.
Parameters
[in] size The dump dimensions.
[in] index The environment map index (to compute its position).
getIndex()
uint32_t castor3d::EnvironmentMap::getIndex () const inline
Returns
The reflection map index.
L'indice de la texture d'environnement.
Referenced by castor3d::doBindPass().
getSize()
castor::Size castor3d::EnvironmentMap::getSize () const inline
Returns
The reflection map dimensions.
Les dimensions de la texture d'environnement.
References castor3d::TextureUnit::getTexture().
getTexture() [1/2]
TextureUnit& castor3d::EnvironmentMap::getTexture () inline
Returns
The reflection map.
La texture d'environnement.
Referenced by castor3d::doBindPass().
getTexture() [2/2]
TextureUnit const& castor3d::EnvironmentMap::getTexture () const inline
Returns
The reflection map.
La texture d'environnement.
initialise()
C3D_API bool castor3d::EnvironmentMap::initialise ()
Initialises the frame buffer.
render()
C3D_API void castor3d::EnvironmentMap::render ()
Renders the environment map.
update()
C3D_API void castor3d::EnvironmentMap::update (RenderQueueArray & p_queues)
Updates the passes.
Remarks
Gather the render queues, for further update.
Parameters
[out] p_queues Receives the render queues needed for the rendering of the frame.
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/EnvironmentMap/EnvironmentMap.hpp