Castor3D: castor3d::RenderTechnique Class Reference
castor3d::RenderTechnique Class Reference
#include <RenderTechnique.hpp>
Public Types
using ShadowMapArray = std::vector< ShadowMapUPtr >
Public Member Functions
C3D_API RenderTechnique (castor::String const &name, RenderTarget &renderTarget, RenderDevice const &device, QueueData const &queueData, Parameters const &parameters, Texture const &colour, Texture const &intermediate, SsaoConfig const &ssaoConfig, ProgressBar *progress, bool deferred, bool visbuffer, bool weightedBlended)
Constructor.
C3D_API ~RenderTechnique ()
Destructor.
C3D_API void listIntermediates (std::vector< IntermediateView > &intermediates)
Lists the intermediate view used by the whole technique.
C3D_API void update (CpuUpdater &updater)
Updates the render pass, CPU wise.
C3D_API void update (GpuUpdater &updater)
Updates the render pass, GPU wise.
C3D_API crg::SemaphoreWaitArray preRender (crg::SemaphoreWaitArray const &toWait, ashes::Queue const &queue)
Renders maps needed for the actual rendering.
C3D_API bool writeInto (castor::TextFile &file)
Writes the technique into a text file.
C3D_API void accept (RenderTechniqueVisitor &visitor)
Visitor acceptance function.
C3D_API crg::FramePass const & getLastPass () const
C3D_API SsaoConfig const & getSsaoConfig () const
C3D_API SsaoConfig & getSsaoConfig ()
C3D_API Texture const & getSsaoResult () const
C3D_API Texture const & getFirstVctBounce () const
C3D_API Texture const & getSecondaryVctBounce () const
C3D_API TechniquePassVector getCustomRenderPasses () const
C3D_API Texture const & getDiffuseLightingResult () const
C3D_API Texture const & getScatteringLightingResult () const
C3D_API Texture const & getBaseColourResult () const
C3D_API crg::ResourcesCache & getResources () const
C3D_API bool isOpaqueEnabled () const
castor::Size const & getSize () const
crg::ImageViewIdArray getSampledResult () const
crg::ImageViewIdArray getTargetResult () const
crg::ImageViewIdArray getSampledIntermediate () const
crg::ImageViewIdArray getTargetIntermediate () const
crg::ImageViewIdArray getTargetDepth () const
Texture const & getResult () const
Texture const & getIntermediate () const
VkExtent3D const & getTargetExtent () const
VkFormat getTargetFormat () const
Texture const & getNormal () const
Texture const & getDepthObj () const
ashes::Buffer< int32_t > const & getDepthRange () const
void setNeedsDepthRange (bool v)
ShadowMapResult const & getDirectionalShadowPassResult () const
ShadowMapResult const & getPointShadowPassResult () const
ShadowMapResult const & getSpotShadowPassResult () const
LightVolumePassResult const & getLpvResult () const
LightVolumePassResultArray const & getLlpvResult () const
CameraUbo const & getCameraUbo () const
CameraUbo & getCameraUbo ()
SceneUbo const & getSceneUbo () const
SceneUbo & getSceneUbo ()
LpvGridConfigUbo const & getLpvConfigUbo () const
LayeredLpvGridConfigUbo const & getLlpvConfigUbo () const
VoxelizerUbo const & getVctConfigUbo () const
ShadowMapLightTypeArray const & getShadowMaps () const
RenderTarget const & getRenderTarget () const
RenderTarget & getRenderTarget ()
bool isMultisampling () const
ashes::Buffer< uint32_t > const & getMaterialsCounts () const
ashes::Buffer< uint32_t > const & getMaterialsStarts () const
ashes::Buffer< castor::Point2ui > const & getPixelXY () const
bool hasVisibility () const
OpaquePassResult const & getOpaqueResult () const
Texture const & getVisibilityResult () const
crg::FramePass const & getGetLastDepthPass () const
crg::FramePass const & getDepthRangePass () const
crg::FramePass const & getGetLastOpaquePass () const
crg::FramePass const & getGetLastTransparentPass () const
crg::FramePassGroup & getGraph ()
Static Public Member Functions
static C3D_API uint32_t countInitialisationSteps ()
Friends
class RenderTechniquePass
Member Typedef Documentation
ShadowMapArray
using castor3d::RenderTechnique::ShadowMapArray = std::vector< ShadowMapUPtr >
Constructor & Destructor Documentation
RenderTechnique()
C3D_API castor3d::RenderTechnique::RenderTechnique (castor::String const & name, RenderTarget & renderTarget, RenderDevice const & device, QueueData const & queueData, Parameters const & parameters, Texture const & colour, Texture const & intermediate, SsaoConfig const & ssaoConfig, ProgressBar * progress, bool deferred, bool visbuffer, bool weightedBlended)
Constructor.
Parameters
[in] name The technique name.
[in] renderTarget The render target for this technique.
[in] device The GPU device.
[in] queueData The queue receiving the GPU commands.
[in] parameters The technique parameters.
[in] colour The result colour image.
[in] intermediate The intermediate colour image.
[in] ssaoConfig The SSAO configuration.
[in] progress The optional progress bar.
[in] deferred true to enable deferred rendering.
[in] visbuffer true to enable visibility buffer.
[in] weightedBlended true to enable weighted blended rendering.
~RenderTechnique()
C3D_API castor3d::RenderTechnique::~RenderTechnique ()
Destructor.
Member Function Documentation
accept()
C3D_API void castor3d::RenderTechnique::accept (RenderTechniqueVisitor & visitor)
Visitor acceptance function.
Parameters
visitor The ... visitor.
countInitialisationSteps()
static C3D_API uint32_t castor3d::RenderTechnique::countInitialisationSteps () static
Returns
The number of steps needed for initialisation, to show progression.
getBaseColourResult()
C3D_API Texture const & castor3d::RenderTechnique::getBaseColourResult () const
getCameraUbo() [1/2]
CameraUbo & castor3d::RenderTechnique::getCameraUbo () inline
getCameraUbo() [2/2]
CameraUbo const & castor3d::RenderTechnique::getCameraUbo () const inline
getCustomRenderPasses()
C3D_API TechniquePassVector castor3d::RenderTechnique::getCustomRenderPasses () const
getDepthObj()
Texture const & castor3d::RenderTechnique::getDepthObj () const inline
References castor3d::PrepassRendering::getDepthObj().
getDepthRange()
ashes::Buffer< int32_t > const & castor3d::RenderTechnique::getDepthRange () const inline
References castor3d::PrepassRendering::getDepthRange().
getDepthRangePass()
crg::FramePass const & castor3d::RenderTechnique::getDepthRangePass () const inline
getDiffuseLightingResult()
C3D_API Texture const & castor3d::RenderTechnique::getDiffuseLightingResult () const
getDirectionalShadowPassResult()
ShadowMapResult const & castor3d::RenderTechnique::getDirectionalShadowPassResult () const inline
getFirstVctBounce()
C3D_API Texture const & castor3d::RenderTechnique::getFirstVctBounce () const
getGetLastDepthPass()
crg::FramePass const & castor3d::RenderTechnique::getGetLastDepthPass () const inline
getGetLastOpaquePass()
crg::FramePass const & castor3d::RenderTechnique::getGetLastOpaquePass () const inline
getGetLastTransparentPass()
crg::FramePass const & castor3d::RenderTechnique::getGetLastTransparentPass () const inline
getGraph()
crg::FramePassGroup & castor3d::RenderTechnique::getGraph () inline
getIntermediate()
Texture const & castor3d::RenderTechnique::getIntermediate () const inline
getLastPass()
C3D_API crg::FramePass const & castor3d::RenderTechnique::getLastPass () const
name Getters.
getLlpvConfigUbo()
LayeredLpvGridConfigUbo const & castor3d::RenderTechnique::getLlpvConfigUbo () const inline
getLlpvResult()
LightVolumePassResultArray const & castor3d::RenderTechnique::getLlpvResult () const inline
getLpvConfigUbo()
LpvGridConfigUbo const & castor3d::RenderTechnique::getLpvConfigUbo () const inline
getLpvResult()
LightVolumePassResult const & castor3d::RenderTechnique::getLpvResult () const inline
getMaterialsCounts()
ashes::Buffer< uint32_t > const & castor3d::RenderTechnique::getMaterialsCounts () const inline
References castor3d::OpaqueRendering::getMaterialsCounts().
getMaterialsStarts()
ashes::Buffer< uint32_t > const & castor3d::RenderTechnique::getMaterialsStarts () const inline
References castor3d::OpaqueRendering::getMaterialsStarts().
getNormal()
Texture const & castor3d::RenderTechnique::getNormal () const inline
getOpaqueResult()
OpaquePassResult const & castor3d::RenderTechnique::getOpaqueResult () const inline
References castor3d::OpaqueRendering::getOpaqueResult().
getPixelXY()
ashes::Buffer< castor::Point2ui > const & castor3d::RenderTechnique::getPixelXY () const inline
References castor3d::OpaqueRendering::getPixelXY().
getPointShadowPassResult()
ShadowMapResult const & castor3d::RenderTechnique::getPointShadowPassResult () const inline
getRenderTarget() [1/2]
RenderTarget & castor3d::RenderTechnique::getRenderTarget () inline
getRenderTarget() [2/2]
RenderTarget const & castor3d::RenderTechnique::getRenderTarget () const inline
getResources()
C3D_API crg::ResourcesCache & castor3d::RenderTechnique::getResources () const
getResult()
Texture const & castor3d::RenderTechnique::getResult () const inline
getSampledIntermediate()
crg::ImageViewIdArray castor3d::RenderTechnique::getSampledIntermediate () const inline
References castor3d::Texture::sampledViewId.
getSampledResult()
crg::ImageViewIdArray castor3d::RenderTechnique::getSampledResult () const inline
References castor3d::Texture::sampledViewId.
getScatteringLightingResult()
C3D_API Texture const & castor3d::RenderTechnique::getScatteringLightingResult () const
getSceneUbo() [1/2]
SceneUbo & castor3d::RenderTechnique::getSceneUbo () inline
getSceneUbo() [2/2]
SceneUbo const & castor3d::RenderTechnique::getSceneUbo () const inline
getSecondaryVctBounce()
C3D_API Texture const & castor3d::RenderTechnique::getSecondaryVctBounce () const
getShadowMaps()
ShadowMapLightTypeArray const & castor3d::RenderTechnique::getShadowMaps () const inline
getSize()
castor::Size const & castor3d::RenderTechnique::getSize () const inline
getSpotShadowPassResult()
ShadowMapResult const & castor3d::RenderTechnique::getSpotShadowPassResult () const inline
getSsaoConfig() [1/2]
C3D_API SsaoConfig & castor3d::RenderTechnique::getSsaoConfig ()
getSsaoConfig() [2/2]
C3D_API SsaoConfig const & castor3d::RenderTechnique::getSsaoConfig () const
getSsaoResult()
C3D_API Texture const & castor3d::RenderTechnique::getSsaoResult () const
getTargetDepth()
crg::ImageViewIdArray castor3d::RenderTechnique::getTargetDepth () const inline
getTargetExtent()
VkExtent3D const & castor3d::RenderTechnique::getTargetExtent () const inline
References castor3d::Texture::getExtent().
getTargetFormat()
VkFormat castor3d::RenderTechnique::getTargetFormat () const inline
References castor3d::Texture::getFormat().
getTargetIntermediate()
crg::ImageViewIdArray castor3d::RenderTechnique::getTargetIntermediate () const inline
References castor3d::Texture::targetViewId.
getTargetResult()
crg::ImageViewIdArray castor3d::RenderTechnique::getTargetResult () const inline
References castor3d::Texture::targetViewId.
getVctConfigUbo()
VoxelizerUbo const & castor3d::RenderTechnique::getVctConfigUbo () const inline
getVisibilityResult()
Texture const & castor3d::RenderTechnique::getVisibilityResult () const inline
References castor3d::PrepassRendering::getVisibility().
hasVisibility()
bool castor3d::RenderTechnique::hasVisibility () const inline
References castor3d::PrepassRendering::hasVisibility().
isMultisampling()
bool castor3d::RenderTechnique::isMultisampling () const inline
isOpaqueEnabled()
C3D_API bool castor3d::RenderTechnique::isOpaqueEnabled () const
listIntermediates()
C3D_API void castor3d::RenderTechnique::listIntermediates (std::vector< IntermediateView > & intermediates)
Lists the intermediate view used by the whole technique.
Parameters
[out] intermediates Receives the intermediate views.
preRender()
C3D_API crg::SemaphoreWaitArray castor3d::RenderTechnique::preRender (crg::SemaphoreWaitArray const & toWait, ashes::Queue const & queue)
Renders maps needed for the actual rendering.
Parameters
[in] toWait The semaphores to wait.
[in] queue The queue receiving the render commands.
Returns
The semaphores signaled by this render.
setNeedsDepthRange()
void castor3d::RenderTechnique::setNeedsDepthRange (bool v) inline
References castor3d::PrepassRendering::setNeedsDepthRange().
update() [1/2]
C3D_API void castor3d::RenderTechnique::update (CpuUpdater & updater)
Updates the render pass, CPU wise.
Parameters
[in,out] updater The update data.
update() [2/2]
C3D_API void castor3d::RenderTechnique::update (GpuUpdater & updater)
Updates the render pass, GPU wise.
Parameters
[in,out] updater The update data.
writeInto()
C3D_API bool castor3d::RenderTechnique::writeInto (castor::TextFile & file)
Writes the technique into a text file.
Parameters
[in] file The file.
Friends And Related Function Documentation
RenderTechniquePass
friend class RenderTechniquePass friend
The documentation for this class was generated from the following file:
Render/RenderTechnique.hpp