Castor3D: castor3d::LayeredLpvGridConfigUbo Class Reference
castor3d::LayeredLpvGridConfigUbo Class Reference
#include <LayeredLpvGridConfigUbo.hpp>
Public Types
using Configuration = LayeredLpvGridConfigUboConfiguration
Public Member Functions
C3D_API LayeredLpvGridConfigUbo (LayeredLpvGridConfigUbo const &rhs)=delete
C3D_API LayeredLpvGridConfigUbo & operator= (LayeredLpvGridConfigUbo const &rhs)=delete
C3D_API LayeredLpvGridConfigUbo (LayeredLpvGridConfigUbo &&rhs) noexcept=default
C3D_API LayeredLpvGridConfigUbo & operator= (LayeredLpvGridConfigUbo &&rhs) noexcept=delete
C3D_API LayeredLpvGridConfigUbo (RenderDevice const &device)
C3D_API ~LayeredLpvGridConfigUbo () noexcept
C3D_API void cpuUpdate (castor::Array< castor::Grid const *, LpvMaxCascadesCount > const &grids, float indirectAttenuation)
void createPassBinding (crg::FramePass &pass, uint32_t dstBinding) const
void createSizedBinding (ashes::DescriptorSet &descriptorSet, VkDescriptorSetLayoutBinding const &layoutBinding) const
ashes::WriteDescriptorSet getDescriptorWrite (uint32_t dstBinding, uint32_t dstArrayElement=0u) const
void addDescriptorWrite (ashes::WriteDescriptorSetArray &descriptorWrites, uint32_t &dstBinding, uint32_t dstArrayElement=0u) const
UniformBufferOffsetT< Configuration > const & getUbo () const
Member Typedef Documentation
Configuration
using castor3d::LayeredLpvGridConfigUbo::Configuration = LayeredLpvGridConfigUboConfiguration
Constructor & Destructor Documentation
LayeredLpvGridConfigUbo() [1/3]
C3D_API castor3d::LayeredLpvGridConfigUbo::LayeredLpvGridConfigUbo (LayeredLpvGridConfigUbo const & rhs) delete
LayeredLpvGridConfigUbo() [2/3]
C3D_API castor3d::LayeredLpvGridConfigUbo::LayeredLpvGridConfigUbo (LayeredLpvGridConfigUbo && rhs) default noexcept
LayeredLpvGridConfigUbo() [3/3]
C3D_API castor3d::LayeredLpvGridConfigUbo::LayeredLpvGridConfigUbo (RenderDevice const & device) explicit
~LayeredLpvGridConfigUbo()
C3D_API castor3d::LayeredLpvGridConfigUbo::~LayeredLpvGridConfigUbo () noexcept
Member Function Documentation
addDescriptorWrite()
void castor3d::LayeredLpvGridConfigUbo::addDescriptorWrite (ashes::WriteDescriptorSetArray & descriptorWrites, uint32_t & dstBinding, uint32_t dstArrayElement = 0u) const inline
References getDescriptorWrite().
cpuUpdate()
C3D_API void castor3d::LayeredLpvGridConfigUbo::cpuUpdate (castor::Array< castor::Grid const *, LpvMaxCascadesCount > const & grids, float indirectAttenuation)
createPassBinding()
void castor3d::LayeredLpvGridConfigUbo::createPassBinding (crg::FramePass & pass, uint32_t dstBinding) const inline
References castor3d::UniformBufferOffsetT< DataT >::createPassBinding().
createSizedBinding()
void castor3d::LayeredLpvGridConfigUbo::createSizedBinding (ashes::DescriptorSet & descriptorSet, VkDescriptorSetLayoutBinding const & layoutBinding) const inline
References castor3d::UniformBufferOffsetT< DataT >::createSizedBinding().
getDescriptorWrite()
ashes::WriteDescriptorSet castor3d::LayeredLpvGridConfigUbo::getDescriptorWrite (uint32_t dstBinding, uint32_t dstArrayElement = 0u) const inline
References castor3d::UniformBufferOffsetT< DataT >::getDescriptorWrite().
Referenced by addDescriptorWrite().
getUbo()
UniformBufferOffsetT< Configuration > const & castor3d::LayeredLpvGridConfigUbo::getUbo () const inline
operator=() [1/2]
C3D_API LayeredLpvGridConfigUbo & castor3d::LayeredLpvGridConfigUbo::operator= (LayeredLpvGridConfigUbo && rhs) delete noexcept
operator=() [2/2]
C3D_API LayeredLpvGridConfigUbo & castor3d::LayeredLpvGridConfigUbo::operator= (LayeredLpvGridConfigUbo const & rhs) delete
The documentation for this class was generated from the following file:
Castor3D/Shader/Ubos/LayeredLpvGridConfigUbo.hpp