Castor3D: castor3d::ObjectBufferOffset Struct Reference
castor3d::ObjectBufferOffset Struct Reference
#include <ObjectBufferOffset.hpp>
Public Member Functions
operator bool () const
ashes::BufferBase const & getIndexBuffer () const
ashes::BufferBase const & getVertexBuffer () const
ashes::BufferBase const & getBonesBuffer () const
bool hasIndices () const
bool hasVertices () const
bool hasBones () const
template<typename IndexT >
castor::ArrayView< IndexT > getIndexData () const
template<typename VertexT >
castor::ArrayView< VertexT > getVertexData () const
castor::ArrayView< VertexBoneData > getBoneData () const
uint32_t getIndexSize () const
uint32_t getVertexSize () const
uint32_t getBonesSize () const
uint32_t getIndexCount () const
template<typename VertexT >
uint32_t getVertexCount () const
uint32_t getBonesCount () const
VkDeviceSize getIndexOffset () const
VkDeviceSize getVertexOffset () const
VkDeviceSize getBonesOffset () const
uint32_t getFirstIndex () const
template<typename VertexT >
uint32_t getFirstVertex () const
uint32_t getFirstBone () const
void markVertexDirty (VkAccessFlags dstAccessFlags=VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT, VkPipelineStageFlags dstPipelineFlags=VK_PIPELINE_STAGE_VERTEX_INPUT_BIT) const
void markIndexDirty (VkAccessFlags dstAccessFlags=VK_ACCESS_INDEX_READ_BIT, VkPipelineStageFlags dstPipelineFlags=VK_PIPELINE_STAGE_VERTEX_INPUT_BIT) const
void markBonesDirty (VkAccessFlags dstAccessFlags=VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT, VkPipelineStageFlags dstPipelineFlags=VK_PIPELINE_STAGE_VERTEX_INPUT_BIT) const
Public Attributes
GpuPackedBuffer * vtxBuffer {}
GpuPackedBuffer * idxBuffer {}
GpuPackedBuffer * bonBuffer {}
MemChunk vtxChunk {}
MemChunk idxChunk {}
MemChunk bonChunk {}
Member Function Documentation
getBoneData()
castor::ArrayView< VertexBoneData > castor3d::ObjectBufferOffset::getBoneData () const inline
References bonBuffer, getBonesCount(), getBonesOffset(), castor3d::GpuBufferBase::getDatas(), and hasBones().
getBonesBuffer()
ashes::BufferBase const & castor3d::ObjectBufferOffset::getBonesBuffer () const inline
References bonBuffer, and castor3d::GpuBufferBase::getBuffer().
getBonesCount()
uint32_t castor3d::ObjectBufferOffset::getBonesCount () const inline
References getBonesSize().
Referenced by getBoneData().
getBonesOffset()
VkDeviceSize castor3d::ObjectBufferOffset::getBonesOffset () const inline
References bonChunk, and castor3d::MemChunk::offset.
Referenced by getBoneData(), getFirstBone(), and markBonesDirty().
getBonesSize()
uint32_t castor3d::ObjectBufferOffset::getBonesSize () const inline
References castor3d::MemChunk::askedSize, and bonChunk.
Referenced by getBonesCount(), and markBonesDirty().
getFirstBone()
uint32_t castor3d::ObjectBufferOffset::getFirstBone () const inline
References getBonesOffset().
getFirstIndex()
uint32_t castor3d::ObjectBufferOffset::getFirstIndex () const inline
References getIndexOffset().
getFirstVertex()
template<typename VertexT > uint32_t castor3d::ObjectBufferOffset::getFirstVertex () const inline
References getVertexOffset().
getIndexBuffer()
ashes::BufferBase const & castor3d::ObjectBufferOffset::getIndexBuffer () const inline
References castor3d::GpuBufferBase::getBuffer(), and idxBuffer.
getIndexCount()
uint32_t castor3d::ObjectBufferOffset::getIndexCount () const inline
References getIndexSize().
getIndexData()
template<typename IndexT > castor::ArrayView< IndexT > castor3d::ObjectBufferOffset::getIndexData () const inline
References castor3d::MemChunk::askedSize, castor3d::GpuBufferBase::getDatas(), getIndexOffset(), hasIndices(), idxBuffer, and idxChunk.
getIndexOffset()
VkDeviceSize castor3d::ObjectBufferOffset::getIndexOffset () const inline
References idxChunk, and castor3d::MemChunk::offset.
Referenced by getFirstIndex(), getIndexData(), and markIndexDirty().
getIndexSize()
uint32_t castor3d::ObjectBufferOffset::getIndexSize () const inline
References castor3d::MemChunk::askedSize, and idxChunk.
Referenced by getIndexCount(), and markIndexDirty().
getVertexBuffer()
ashes::BufferBase const & castor3d::ObjectBufferOffset::getVertexBuffer () const inline
References castor3d::GpuBufferBase::getBuffer(), and vtxBuffer.
getVertexCount()
template<typename VertexT > uint32_t castor3d::ObjectBufferOffset::getVertexCount () const inline
References getVertexSize().
getVertexData()
template<typename VertexT > castor::ArrayView< VertexT > castor3d::ObjectBufferOffset::getVertexData () const inline
References castor3d::GpuBufferBase::getDatas(), getVertexOffset(), hasVertices(), and vtxBuffer.
getVertexOffset()
VkDeviceSize castor3d::ObjectBufferOffset::getVertexOffset () const inline
References castor3d::MemChunk::offset, and vtxChunk.
Referenced by getFirstVertex(), getVertexData(), and markVertexDirty().
getVertexSize()
uint32_t castor3d::ObjectBufferOffset::getVertexSize () const inline
References castor3d::MemChunk::askedSize, and vtxChunk.
Referenced by getVertexCount(), and markVertexDirty().
hasBones()
bool castor3d::ObjectBufferOffset::hasBones () const inline
References castor3d::MemChunk::askedSize, and bonChunk.
Referenced by getBoneData().
hasIndices()
bool castor3d::ObjectBufferOffset::hasIndices () const inline
References castor3d::MemChunk::askedSize, and idxChunk.
Referenced by getIndexData().
hasVertices()
bool castor3d::ObjectBufferOffset::hasVertices () const inline
References castor3d::MemChunk::askedSize, and vtxChunk.
Referenced by getVertexData().
markBonesDirty()
void castor3d::ObjectBufferOffset::markBonesDirty (VkAccessFlags dstAccessFlags = VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT, VkPipelineStageFlags dstPipelineFlags = VK_PIPELINE_STAGE_VERTEX_INPUT_BIT) const inline
References bonBuffer, getBonesOffset(), getBonesSize(), and castor3d::GpuBufferBase::markDirty().
markIndexDirty()
void castor3d::ObjectBufferOffset::markIndexDirty (VkAccessFlags dstAccessFlags = VK_ACCESS_INDEX_READ_BIT, VkPipelineStageFlags dstPipelineFlags = VK_PIPELINE_STAGE_VERTEX_INPUT_BIT) const inline
References getIndexOffset(), getIndexSize(), idxBuffer, and castor3d::GpuBufferBase::markDirty().
markVertexDirty()
void castor3d::ObjectBufferOffset::markVertexDirty (VkAccessFlags dstAccessFlags = VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT, VkPipelineStageFlags dstPipelineFlags = VK_PIPELINE_STAGE_VERTEX_INPUT_BIT) const inline
References getVertexOffset(), getVertexSize(), castor3d::GpuBufferBase::markDirty(), and vtxBuffer.
operator bool()
castor3d::ObjectBufferOffset::operator bool () const inline explicit
References vtxBuffer.
Member Data Documentation
bonBuffer
GpuPackedBuffer* castor3d::ObjectBufferOffset::bonBuffer {}
Referenced by getBoneData(), getBonesBuffer(), and markBonesDirty().
bonChunk
MemChunk castor3d::ObjectBufferOffset::bonChunk {}
Referenced by getBonesOffset(), getBonesSize(), and hasBones().
idxBuffer
GpuPackedBuffer* castor3d::ObjectBufferOffset::idxBuffer {}
Referenced by getIndexBuffer(), getIndexData(), and markIndexDirty().
idxChunk
MemChunk castor3d::ObjectBufferOffset::idxChunk {}
Referenced by getIndexData(), getIndexOffset(), getIndexSize(), and hasIndices().
vtxBuffer
GpuPackedBuffer* castor3d::ObjectBufferOffset::vtxBuffer {}
Referenced by getVertexBuffer(), getVertexData(), markVertexDirty(), and operator bool().
vtxChunk
MemChunk castor3d::ObjectBufferOffset::vtxChunk {}
Referenced by getVertexOffset(), getVertexSize(), and hasVertices().
The documentation for this struct was generated from the following file:
Buffer/ObjectBufferOffset.hpp