Castor3D: castor3d::InstantiationComponent Class Reference
castor3d::InstantiationComponent Class Reference
Classes
struct Data
Public Types
using DataArray = std::vector< Data >
using InstanceDataMap = std::map< MaterialSPtr, DataArray >
Public Member Functions
C3D_API InstantiationComponent (Submesh &submesh, uint32_t threshold=1u)
Constructor.
C3D_API uint32_t ref (MaterialSPtr material)
Increments instance count.
C3D_API uint32_t unref (MaterialSPtr material)
Decrements instance count.
C3D_API uint32_t getRefCount (MaterialSPtr material) const
Retrieves the instances count.
bool isInstanced (MaterialSPtr material) const
C3D_API uint32_t getMaxRefCount () const
C3D_API void gather (MaterialSPtr material, ashes::BufferCRefArray &buffers, std::vector< uint64_t > &offsets, ashes::PipelineVertexInputStateCreateInfoCRefArray &layouts, uint32_t instanceMult) override
Gathers buffers that need to go in a VAO.
C3D_API void setMaterial (MaterialSPtr oldMaterial, MaterialSPtr newMaterial, bool update) override
Sets the material.
C3D_API InstanceDataMap::const_iterator find (MaterialSPtr material, uint32_t instanceMult) const
C3D_API InstanceDataMap::iterator find (MaterialSPtr material, uint32_t instanceMult)
C3D_API ProgramFlags getProgramFlags (MaterialSPtr material) const override
uint32_t getThreshold () const
InstanceDataMap::const_iterator end () const
InstanceDataMap::iterator end ()
InstanceDataMap::const_iterator find (MaterialSPtr material) const
InstanceDataMap::iterator find (MaterialSPtr material)
uint32_t getIndex (uint32_t instanceMult) const
Public Member Functions inherited from castor3d::SubmeshComponent
C3D_API SubmeshComponent (Submesh &submesh, castor::String const &type)
Constructor.
virtual C3D_API ~SubmeshComponent () noexcept=default
Destructor.
C3D_API bool initialise (RenderDevice const &device)
Initialises the submesh.
C3D_API void cleanup ()
Cleans the submesh.
C3D_API void fill (RenderDevice const &device)
Initialises the submesh.
C3D_API void upload ()
Uploads data on VRAM.
castor::String const & getType () const
void needsUpdate ()
Sets the component to be updated.
Static Public Attributes
static C3D_API castor::String const Name
static C3D_API uint32_t constexpr BindingPoint = 2u
Member Typedef Documentation
DataArray
using castor3d::InstantiationComponent::DataArray = std::vector< Data >
InstanceDataMap
using castor3d::InstantiationComponent::InstanceDataMap = std::map< MaterialSPtr, DataArray >
Constructor & Destructor Documentation
InstantiationComponent()
C3D_API castor3d::InstantiationComponent::InstantiationComponent (Submesh & submesh, uint32_t threshold = 1u) explicit
Constructor.
Parameters
[in] submesh The parent submesh.
[in] threshold The threshold from which a submesh will be instantiated.
Member Function Documentation
end() [1/2]
InstanceDataMap::const_iterator castor3d::InstantiationComponent::end () const inline
end() [2/2]
InstanceDataMap::iterator castor3d::InstantiationComponent::end () inline
find() [1/4]
C3D_API InstanceDataMap::const_iterator castor3d::InstantiationComponent::find (MaterialSPtr material, uint32_t instanceMult) const
name Getters.
find() [2/4]
C3D_API InstanceDataMap::iterator castor3d::InstantiationComponent::find (MaterialSPtr material, uint32_t instanceMult)
find() [3/4]
InstanceDataMap::const_iterator castor3d::InstantiationComponent::find (MaterialSPtr material) const inline
find() [4/4]
InstanceDataMap::iterator castor3d::InstantiationComponent::find (MaterialSPtr material) inline
References castor3d::SubmeshComponent::needsUpdate().
gather()
C3D_API void castor3d::InstantiationComponent::gather (MaterialSPtr material, ashes::BufferCRefArray & buffers, std::vector< uint64_t > & offsets, ashes::PipelineVertexInputStateCreateInfoCRefArray & layouts, uint32_t instanceMult) override virtual
Gathers buffers that need to go in a VAO.
Implements castor3d::SubmeshComponent.
getIndex()
uint32_t castor3d::InstantiationComponent::getIndex (uint32_t instanceMult) const inline
getMaxRefCount()
C3D_API uint32_t castor3d::InstantiationComponent::getMaxRefCount () const
Returns
The maximum instances count, amongst all materials.
getProgramFlags()
C3D_API ProgramFlags castor3d::InstantiationComponent::getProgramFlags (MaterialSPtr material) const override virtual
Returns
The shader program flags.
Implements castor3d::SubmeshComponent.
getRefCount()
C3D_API uint32_t castor3d::InstantiationComponent::getRefCount (MaterialSPtr material) const
Retrieves the instances count.
Parameters
[in] material The material for which the instance count is retrieved
Returns
The value
Referenced by isInstanced().
getThreshold()
uint32_t castor3d::InstantiationComponent::getThreshold () const inline
Referenced by isInstanced().
isInstanced()
bool castor3d::InstantiationComponent::isInstanced (MaterialSPtr material) const inline
Parameters
[in] material The material.
Returns
true if the instance count for given material is greater than the threshold.
References getRefCount(), and getThreshold().
ref()
C3D_API uint32_t castor3d::InstantiationComponent::ref (MaterialSPtr material)
Increments instance count.
Parameters
[in] material The material for which the instance count is incremented.
Returns
The previous instance count.
setMaterial()
C3D_API void castor3d::InstantiationComponent::setMaterial (MaterialSPtr oldMaterial, MaterialSPtr newMaterial, bool update) override virtual
Sets the material.
Parameters
[in] oldMaterial The old material.
[in] newMaterial The new material.
[in] update Tells if the buffers must be updated.
Reimplemented from castor3d::SubmeshComponent.
unref()
C3D_API uint32_t castor3d::InstantiationComponent::unref (MaterialSPtr material)
Decrements instance count.
Parameters
[in] material The material for which the instance count is decremented.
Returns
The previous instance count.
Member Data Documentation
BindingPoint
C3D_API uint32_t constexpr castor3d::InstantiationComponent::BindingPoint = 2u static
Name
C3D_API castor::String const castor3d::InstantiationComponent::Name static
The documentation for this class was generated from the following file:
Model/Mesh/Submesh/Component/InstantiationComponent.hpp