Castor3D: castor3d::EventHandler Class Reference
castor3d::EventHandler Class Reference abstract
#include <EventHandler.hpp>
Public Types
using ClientMouseFunction = castor::Function< void(MouseEvent const &) >
using ClientKeyboardFunction = castor::Function< void(KeyboardEvent const &) >
using ClientHandlerFunction = castor::Function< void(HandlerEvent const &) >
using EnableFunction = castor::Function< void(bool) >
using OnClientMouseEvent = castor::SignalT< ClientMouseFunction >
using OnClientKeyboardEvent = castor::SignalT< ClientKeyboardFunction >
using OnClientHandlerEvent = castor::SignalT< ClientHandlerFunction >
using OnEnable = castor::SignalT< EnableFunction >
using OnClientMouseEventConnection = OnClientMouseEvent::connection
using OnClientKeyboardEventConnection = OnClientKeyboardEvent::connection
using OnClientHandlerEventConnection = OnClientHandlerEvent::connection
using OnEnableConnection = OnEnable::connection
Public Member Functions
Mouse events
void pushEvent (MouseEvent const &event)
Adds a mouse event to the events queue.
void connect (MouseEventType event, ClientMouseFunction function)
Connects a function to a mouse event.
bool catchesMouseEvents () const
Tells if the control catches mouse events.
void setCatchesMouseEvents (bool value)
Sets if the control can catch mouse events.
Keyboard events
void pushEvent (KeyboardEvent const &event)
Adds a keyboard event to the events queue.
void connect (KeyboardEventType event, ClientKeyboardFunction function)
Connects a function to a keyboard event.
bool catchesTabKey () const
Tells if the control catches 'tab' key.
bool catchesReturnKey () const
Tells if the control catches 'return' key.
Public Member Functions inherited from castor::NamedBaseT< T >
NamedBaseT (T name) noexcept
Constructor.
T const & getName () const noexcept
Retrieves the name.
void rename (T name) noexcept
Protected Types
using EventHandlerFunction = castor::Function< void() >
using EventQueue = castor::Deque< castor::Pair< UserInputEventSPtr, EventHandlerFunction > >
General
OnEnable onEnable
EventHandler (castor::String const &name, bool catchMouseEvents)
Constructor.
virtual ~EventHandler () noexcept
Destructor.
void processEvents ()
Processes all queued events.
bool isEnabled () const
void enable ()
Sets if the control is enabled.
void disable ()
Sets if the control is disabled.
Handler events
castor::Array< OnClientMouseEvent, size_t(MouseEventType::eCount) > m_mouseSlots
castor::Array< castor::Vector< OnClientMouseEventConnection >, size_t(MouseEventType::eCount) > m_mouseSlotsConnections
castor::Array< OnClientKeyboardEvent, size_t(KeyboardEventType::eCount) > m_keyboardSlots
castor::Array< castor::Vector< OnClientKeyboardEventConnection >, size_t(KeyboardEventType::eCount) > m_keyboardSlotsConnections
castor::Array< OnClientHandlerEvent, size_t(HandlerEventType::eCount) > m_handlerSlots
castor::Array< castor::Vector< OnClientHandlerEventConnection >, size_t(HandlerEventType::eCount) > m_handlerSlotsConnections
void pushEvent (HandlerEvent const &event)
Adds a handler event to the events queue.
void connect (HandlerEventType event, ClientHandlerFunction function)
Connects a function to a handler event.
void processMouseEvent (MouseEventSPtr event)
Mouse event processing function.
void processKeyboardEvent (KeyboardEventSPtr event)
Keyboard event processing function.
void processHandlerEvent (HandlerEventSPtr event)
Handler event processing function.
Additional Inherited Members
Protected Attributes inherited from castor::NamedBaseT< T >
T m_name
Member Typedef Documentation
ClientHandlerFunction
using castor3d::EventHandler::ClientHandlerFunction = castor::Function< void(HandlerEvent const &) >
Catcher definition for handler events.
ClientKeyboardFunction
using castor3d::EventHandler::ClientKeyboardFunction = castor::Function< void(KeyboardEvent const &) >
Catcher definition for keyboard events.
ClientMouseFunction
using castor3d::EventHandler::ClientMouseFunction = castor::Function< void(MouseEvent const &) >
Catcher definition for mouse events.
EnableFunction
using castor3d::EventHandler::EnableFunction = castor::Function< void(bool) >
Signal function when handler is enabled/disabled.
EventHandlerFunction
using castor3d::EventHandler::EventHandlerFunction = castor::Function< void() > protected
EventQueue
using castor3d::EventHandler::EventQueue = castor::Deque< castor::Pair< UserInputEventSPtr, EventHandlerFunction > > protected
OnClientHandlerEvent
using castor3d::EventHandler::OnClientHandlerEvent = castor::SignalT< ClientHandlerFunction >
Handler event signal definition.
OnClientHandlerEventConnection
using castor3d::EventHandler::OnClientHandlerEventConnection = OnClientHandlerEvent::connection
Handler event signal connection definition.
OnClientKeyboardEvent
using castor3d::EventHandler::OnClientKeyboardEvent = castor::SignalT< ClientKeyboardFunction >
Keyboard event signal definition.
OnClientKeyboardEventConnection
using castor3d::EventHandler::OnClientKeyboardEventConnection = OnClientKeyboardEvent::connection
Keyboard event signal connection definition.
OnClientMouseEvent
using castor3d::EventHandler::OnClientMouseEvent = castor::SignalT< ClientMouseFunction >
Mouse event signal definition.
OnClientMouseEventConnection
using castor3d::EventHandler::OnClientMouseEventConnection = OnClientMouseEvent::connection
Mouse event signal connection definition.
OnEnable
using castor3d::EventHandler::OnEnable = castor::SignalT< EnableFunction >
Signal when handler is enabled/disabled.
OnEnableConnection
using castor3d::EventHandler::OnEnableConnection = OnEnable::connection
Signal connection when handler is enabled/disabled.
Constructor & Destructor Documentation
EventHandler()
castor3d::EventHandler::EventHandler (castor::String const & name, bool catchMouseEvents) inline explicit
Constructor.
Parameters
[in] name The handler name.
[in] catchMouseEvents Defines if the event handler catches mouse event.
~EventHandler()
virtual castor3d::EventHandler::~EventHandler () inline virtual noexcept
Destructor.
References castor::makeUniqueLock().
Member Function Documentation
catchesMouseEvents()
bool castor3d::EventHandler::catchesMouseEvents () const inline
Tells if the control catches mouse events.
Remarks
A control catches mouse events when it is enabled, and when it explicitly catches it (enabled by default, except for static controls).
Returns
false if the mouse events don't affect the control.
catchesReturnKey()
bool castor3d::EventHandler::catchesReturnKey () const inline
Tells if the control catches 'return' key.
Remarks
A control catches 'return' key when it is enabled, and when it explicitly catches it (disabled by default).
Returns
false if the 'return' key doesn't affect the control.
catchesTabKey()
bool castor3d::EventHandler::catchesTabKey () const inline
Tells if the control catches 'tab' key.
Remarks
A control catches 'tab' key when it is enabled, and when it explicitly catches it (disabled by default).
Returns
false if the 'tab' key doesn't affect the control.
connect() [1/3]
void castor3d::EventHandler::connect (HandlerEventType event, ClientHandlerFunction function) inline
Connects a function to a handler event.
Parameters
[in] event The event type.
[in] function The function.
References connect(), m_handlerSlots, and m_handlerSlotsConnections.
connect() [2/3]
void castor3d::EventHandler::connect (KeyboardEventType event, ClientKeyboardFunction function) inline
Connects a function to a keyboard event.
Parameters
[in] event The event type.
[in] function The function.
References connect(), m_keyboardSlots, and m_keyboardSlotsConnections.
connect() [3/3]
void castor3d::EventHandler::connect (MouseEventType event, ClientMouseFunction function) inline
Connects a function to a mouse event.
Parameters
[in] event The event type.
[in] function The function.
References connect(), m_mouseSlots, and m_mouseSlotsConnections.
Referenced by connect(), connect(), connect(), castor3d::NonClientEventHandler< Derived >::connectNC(), castor3d::NonClientEventHandler< Derived >::connectNC(), and castor3d::NonClientEventHandler< Derived >::connectNC().
disable()
void castor3d::EventHandler::disable () inline
Sets if the control is disabled.
References onEnable.
enable()
void castor3d::EventHandler::enable () inline
Sets if the control is enabled.
References onEnable.
isEnabled()
bool castor3d::EventHandler::isEnabled () const inline
Returns
false if the control is disabled.
processEvents()
void castor3d::EventHandler::processEvents () inline
Processes all queued events.
processHandlerEvent()
void castor3d::EventHandler::processHandlerEvent (HandlerEventSPtr event) inline protected
Handler event processing function.
Parameters
[in] event The event.
References m_handlerSlots.
Referenced by pushEvent().
processKeyboardEvent()
void castor3d::EventHandler::processKeyboardEvent (KeyboardEventSPtr event) inline protected
Keyboard event processing function.
Parameters
[in] event The event.
References m_keyboardSlots.
Referenced by pushEvent().
processMouseEvent()
void castor3d::EventHandler::processMouseEvent (MouseEventSPtr event) inline protected
Mouse event processing function.
Parameters
[in] event The event.
References m_mouseSlots.
Referenced by pushEvent().
pushEvent() [1/3]
void castor3d::EventHandler::pushEvent (HandlerEvent const & event) inline
Adds a handler event to the events queue.
Parameters
[in] event The mouse event.
References castor::makeUniqueLock(), and processHandlerEvent().
pushEvent() [2/3]
void castor3d::EventHandler::pushEvent (KeyboardEvent const & event) inline
Adds a keyboard event to the events queue.
Parameters
[in] event The mouse event.
References castor::makeUniqueLock(), and processKeyboardEvent().
pushEvent() [3/3]
void castor3d::EventHandler::pushEvent (MouseEvent const & event) inline
Adds a mouse event to the events queue.
Parameters
[in] event The mouse event.
References castor::makeUniqueLock(), and processMouseEvent().
setCatchesMouseEvents()
void castor3d::EventHandler::setCatchesMouseEvents (bool value) inline
Sets if the control can catch mouse events.
Parameters
[in] value The new value.
Member Data Documentation
m_handlerSlots
castor::Array< OnClientHandlerEvent, size_t(HandlerEventType::eCount) > castor3d::EventHandler::m_handlerSlots protected
The handler events slots.
Referenced by connect(), and processHandlerEvent().
m_handlerSlotsConnections
castor::Array< castor::Vector< OnClientHandlerEventConnection >, size_t(HandlerEventType::eCount) > castor3d::EventHandler::m_handlerSlotsConnections protected
The handler events slots connections.
Referenced by connect().
m_keyboardSlots
castor::Array< OnClientKeyboardEvent, size_t(KeyboardEventType::eCount) > castor3d::EventHandler::m_keyboardSlots protected
The keyboard events slots.
Referenced by connect(), and processKeyboardEvent().
m_keyboardSlotsConnections
castor::Array< castor::Vector< OnClientKeyboardEventConnection >, size_t(KeyboardEventType::eCount) > castor3d::EventHandler::m_keyboardSlotsConnections protected
The keyboard events slots connections.
Referenced by connect().
m_mouseSlots
castor::Array< OnClientMouseEvent, size_t(MouseEventType::eCount) > castor3d::EventHandler::m_mouseSlots protected
The mouse events slots.
Referenced by connect(), and processMouseEvent().
m_mouseSlotsConnections
castor::Array< castor::Vector< OnClientMouseEventConnection >, size_t(MouseEventType::eCount) > castor3d::EventHandler::m_mouseSlotsConnections protected
The mouse events slots connections.
Referenced by connect().
onEnable
OnEnable castor3d::EventHandler::onEnable
Referenced by disable(), and enable().
The documentation for this class was generated from the following file:
Castor3D/Event/UserInput/EventHandler.hpp