Castor3D: castor3d::shader::DirectionalLight Struct Reference
castor3d::shader::DirectionalLight Struct Reference
#include <GlslLight.hpp>
Public Member Functions
DirectionalLight (sdw::ShaderWriter &writer, ast::expr::ExprPtr expr, bool enabled)
auto base () const
auto colour () const
auto intensity () const
auto shadowMapIndex () const
auto cascadeCount () const
auto direction () const
Constructor & Destructor Documentation
DirectionalLight()
castor3d::shader::DirectionalLight::DirectionalLight (sdw::ShaderWriter & writer, ast::expr::ExprPtr expr, bool enabled) inline
Member Function Documentation
base()
auto castor3d::shader::DirectionalLight::base () const inline
Referenced by cascadeCount(), colour(), direction(), intensity(), and shadowMapIndex().
cascadeCount()
auto castor3d::shader::DirectionalLight::cascadeCount () const inline
References base().
colour()
auto castor3d::shader::DirectionalLight::colour () const inline
References base().
direction()
auto castor3d::shader::DirectionalLight::direction () const inline
References base().
intensity()
auto castor3d::shader::DirectionalLight::intensity () const inline
References base().
shadowMapIndex()
auto castor3d::shader::DirectionalLight::shadowMapIndex () const inline
References base().
The documentation for this struct was generated from the following file:
Castor3D/Shader/Shaders/GlslLight.hpp