Castor3D: castor3d::ShaderBuffer Class Reference
castor3d::ShaderBuffer Class Reference
#include <ShaderBuffer.hpp>
Public Member Functions
C3D_API ShaderBuffer (Engine &engine, RenderDevice const &device, VkDeviceSize size, castor::String name)
Constructor.
C3D_API void upload (ashes::CommandBuffer const &commandBuffer) const
Updates the buffer.
C3D_API void upload (ashes::CommandBuffer const &commandBuffer, VkDeviceSize offset, VkDeviceSize size) const
Updates the buffer on GPU.
C3D_API VkDescriptorSetLayoutBinding createLayoutBinding (uint32_t index=0u, VkShaderStageFlags stages=(VK_SHADER_STAGE_FRAGMENT_BIT|VK_SHADER_STAGE_GEOMETRY_BIT|VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT|VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT|VK_SHADER_STAGE_VERTEX_BIT)) const
Creates the descriptor set layout binding at given point.
C3D_API void createPassBinding (crg::FramePass &pass, castor::String const &name, uint32_t binding) const
Creates a frame pass binding.
C3D_API ashes::WriteDescriptorSet getSingleBinding (uint32_t binding, VkDeviceSize offset, VkDeviceSize size) const
Creates the descriptor write for this buffer.
C3D_API ashes::WriteDescriptorSet getBinding (uint32_t binding) const
Creates the descriptor write for this buffer.
C3D_API void createBinding (ashes::DescriptorSet &descriptorSet, VkDescriptorSetLayoutBinding const &binding) const
Creates the descriptor set binding at given point.
uint8_t * getPtr ()
VkDeviceSize getSize ()
RenderDevice const & getDevice () const
void setCount (uint32_t value)
void setSecondaryCount (uint32_t value)
void setTertiaryCount (uint32_t value)
Constructor & Destructor Documentation
ShaderBuffer()
C3D_API castor3d::ShaderBuffer::ShaderBuffer (Engine & engine, RenderDevice const & device, VkDeviceSize size, castor::String name)
Constructor.
Parameters
[in] engine The engine.
[in] device The GPU device.
[in] size The buffer size.
[in] name The shader buffer name.
Member Function Documentation
createBinding()
C3D_API void castor3d::ShaderBuffer::createBinding (ashes::DescriptorSet & descriptorSet, VkDescriptorSetLayoutBinding const & binding) const
Creates the descriptor set binding at given point.
Parameters
[in,out] descriptorSet Receives the created binding.
[in] binding The descriptor set layout binding.
createLayoutBinding()
C3D_API VkDescriptorSetLayoutBinding castor3d::ShaderBuffer::createLayoutBinding (uint32_t index = 0u, VkShaderStageFlags stages = (VK_SHADER_STAGE_FRAGMENT_BIT|VK_SHADER_STAGE_GEOMETRY_BIT|VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT|VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT|VK_SHADER_STAGE_VERTEX_BIT)) const
Creates the descriptor set layout binding at given point.
Parameters
[in] index The binding point index.
[in] stages The shader stages.
createPassBinding()
C3D_API void castor3d::ShaderBuffer::createPassBinding (crg::FramePass & pass, castor::String const & name, uint32_t binding) const
Creates a frame pass binding.
getBinding()
C3D_API ashes::WriteDescriptorSet castor3d::ShaderBuffer::getBinding (uint32_t binding) const
Creates the descriptor write for this buffer.
Parameters
[in] binding The descriptor set layout binding.
getDevice()
RenderDevice const & castor3d::ShaderBuffer::getDevice () const inline
getPtr()
uint8_t * castor3d::ShaderBuffer::getPtr () inline
name Getters.
Referenced by castor3d::LightBuffer::getPtr(), castor3d::PassBuffer::getPtr(), castor3d::SssProfileBuffer::getPtr(), castor3d::TextureAnimationBuffer::getPtr(), and castor3d::TextureConfigurationBuffer::getPtr().
getSingleBinding()
C3D_API ashes::WriteDescriptorSet castor3d::ShaderBuffer::getSingleBinding (uint32_t binding, VkDeviceSize offset, VkDeviceSize size) const
Creates the descriptor write for this buffer.
Parameters
[in] binding The descriptor set layout binding.
[in] offset,size The updated range.
getSize()
VkDeviceSize castor3d::ShaderBuffer::getSize () inline
setCount()
void castor3d::ShaderBuffer::setCount (uint32_t value) inline
name Mutators.
setSecondaryCount()
void castor3d::ShaderBuffer::setSecondaryCount (uint32_t value) inline
setTertiaryCount()
void castor3d::ShaderBuffer::setTertiaryCount (uint32_t value) inline
upload() [1/2]
C3D_API void castor3d::ShaderBuffer::upload (ashes::CommandBuffer const & commandBuffer) const
Updates the buffer.
Parameters
[in] commandBuffer The command buffer receiving upload commands.
upload() [2/2]
C3D_API void castor3d::ShaderBuffer::upload (ashes::CommandBuffer const & commandBuffer, VkDeviceSize offset, VkDeviceSize size) const
Updates the buffer on GPU.
Parameters
[in] commandBuffer The command buffer receiving upload commands.
[in] offset,size The updated range.
The documentation for this class was generated from the following file:
Shader/ShaderBuffer.hpp