Castor3D: castor3d::UniformBufferBase Class Reference
castor3d::UniformBufferBase Class Reference
Public Member Functions
C3D_API UniformBufferBase (RenderSystem const &renderSystem, VkDeviceSize elemCount, VkDeviceSize elemSize, VkBufferUsageFlags usage, VkMemoryPropertyFlags flags, castor::String debugName, ashes::QueueShare sharingMode={})
Constructor.
virtual C3D_API ~UniformBufferBase ()=default
Destructor.
C3D_API uint32_t initialise (RenderDevice const &device)
Initialises the GPU buffer.
C3D_API uint32_t initialise (RenderDevice const &device, ashes::QueueShare sharingMode)
Initialises the GPU buffer.
C3D_API void cleanup ()
Cleans up the GPU buffer.
C3D_API bool hasAvailable () const
C3D_API uint32_t allocate ()
Allocates a memory chunk for a CPU buffer.
C3D_API void deallocate (uint32_t offset)
Deallocates memory.
C3D_API void upload (ashes::BufferBase const &stagingBuffer, ashes::Queue const &queue, ashes::CommandPool const &commandPool, const void *data, size_t size, uint32_t offset, VkPipelineStageFlags flags) const
Transfers data to the GPU buffer from RAM.
void upload (ashes::BufferBase const &stagingBuffer, ashes::Queue const &queue, ashes::CommandPool const &commandPool, ashes::ByteArray const &data, uint32_t offset, VkPipelineStageFlags flags) const
Transfers data to the GPU buffer from RAM.
C3D_API void upload (ashes::BufferBase const &stagingBuffer, ashes::CommandBuffer const &commandBuffer, const void *data, size_t size, uint32_t offset, VkPipelineStageFlags flags) const
Transfers data to the GPU buffer from RAM.
void upload (ashes::BufferBase const &stagingBuffer, ashes::CommandBuffer const &commandBuffer, ashes::ByteArray const &data, uint32_t offset, VkPipelineStageFlags flags) const
Transfers data to the GPU buffer from RAM.
C3D_API void upload (ashes::BufferBase const &stagingBuffer, ashes::Queue const &queue, ashes::CommandPool const &commandPool, const void *data, size_t size, uint32_t offset, VkPipelineStageFlags flags, RenderPassTimer const &timer, uint32_t index) const
Transfers data to the GPU buffer from RAM.
void upload (ashes::BufferBase const &stagingBuffer, ashes::Queue const &queue, ashes::CommandPool const &commandPool, ashes::ByteArray const &data, uint32_t offset, VkPipelineStageFlags flags, RenderPassTimer const &timer, uint32_t index) const
Transfers data to the GPU buffer from RAM.
C3D_API void upload (ashes::BufferBase const &stagingBuffer, ashes::CommandBuffer const &commandBuffer, const void *data, size_t size, uint32_t offset, VkPipelineStageFlags flags, RenderPassTimer const &timer, uint32_t index) const
Transfers data to the GPU buffer from RAM.
void upload (ashes::BufferBase const &stagingBuffer, ashes::CommandBuffer const &commandBuffer, ashes::ByteArray const &data, uint32_t offset, VkPipelineStageFlags flags, RenderPassTimer const &timer, uint32_t index) const
Transfers data to the GPU buffer from RAM.
C3D_API void download (ashes::BufferBase const &stagingBuffer, ashes::Queue const &queue, ashes::CommandPool const &commandPool, void *data, size_t size, uint32_t offset, VkPipelineStageFlags flags, RenderPassTimer const &timer, uint32_t index) const
Transfers data from the GPU buffer to RAM.
void download (ashes::BufferBase const &stagingBuffer, ashes::Queue const &queue, ashes::CommandPool const &commandPool, ashes::ByteArray &data, uint32_t offset, VkPipelineStageFlags flags, RenderPassTimer const &timer, uint32_t index) const
Transfers data from the GPU buffer to RAM.
bool hasBuffer () const
ashes::UniformBuffer const & getBuffer () const
operator ashes::UniformBuffer const & () const
ashes::UniformBuffer & getBuffer ()
operator ashes::UniformBuffer & ()
uint32_t getElementSize () const
uint32_t getAlignedSize (uint32_t size) const
Retrieves the aligned size for an element.
uint32_t getAlignedSize () const
Constructor & Destructor Documentation
UniformBufferBase()
C3D_API castor3d::UniformBufferBase::UniformBufferBase (RenderSystem const & renderSystem, VkDeviceSize elemCount, VkDeviceSize elemSize, VkBufferUsageFlags usage, VkMemoryPropertyFlags flags, castor::String debugName, ashes::QueueShare sharingMode = {})
Constructor.
Parameters
[in] renderSystem The RenderSystem.
[in] elemCount The elements count.
[in] elemSize The elements size.
[in] usage The buffer usage flags.
[in] flags The buffer memory flags.
[in] debugName The buffer debug name.
[in] sharingMode The buffer sharing mode.
~UniformBufferBase()
virtual C3D_API castor3d::UniformBufferBase::~UniformBufferBase () virtual default
Destructor.
Member Function Documentation
allocate()
C3D_API uint32_t castor3d::UniformBufferBase::allocate ()
Allocates a memory chunk for a CPU buffer.
Returns
The memory chunk offset.
cleanup()
C3D_API void castor3d::UniformBufferBase::cleanup ()
Cleans up the GPU buffer.
deallocate()
C3D_API void castor3d::UniformBufferBase::deallocate (uint32_t offset)
Deallocates memory.
Parameters
[in] offset The memory chunk offset.
download() [1/2]
C3D_API void castor3d::UniformBufferBase::download (ashes::BufferBase const & stagingBuffer, ashes::Queue const & queue, ashes::CommandPool const & commandPool, void * data, size_t size, uint32_t offset, VkPipelineStageFlags flags, RenderPassTimer const & timer, uint32_t index) const
Transfers data from the GPU buffer to RAM.
Remarks
Transfers data from buffer[offset*sizeof(T)] to buffer[(offset+count-1)*sizeof(T)].
Parameters
[in] stagingBuffer The staging buffer used to transfer the data.
[in] queue The queue used to execute the transfer.
[in] commandPool The command pool on which the command buffer will be created.
[in] data Receives the data to download, packed.
[in] size The data size.
[in] offset The start offset.
[in] flags The pipeline stage flags for the out memory barrier.
[in] timer The render pass timer.
[in] index The render pass index.
Referenced by download().
download() [2/2]
void castor3d::UniformBufferBase::download (ashes::BufferBase const & stagingBuffer, ashes::Queue const & queue, ashes::CommandPool const & commandPool, ashes::ByteArray & data, uint32_t offset, VkPipelineStageFlags flags, RenderPassTimer const & timer, uint32_t index) const inline
Transfers data from the GPU buffer to RAM.
Remarks
Transfers data from buffer[offset*sizeof(T)] to buffer[(offset+count-1)*sizeof(T)].
Parameters
[in] stagingBuffer The staging buffer used to transfer the data.
[in] queue The queue used to execute the transfer.
[in] commandPool The command pool on which the command buffer will be created.
[in] data Receives the data to download, packed.
[in] offset The start offset.
[in] flags The pipeline stage flags for the out memory barrier.
[in] timer The render pass timer.
[in] index The render pass index.
References download().
getAlignedSize() [1/2]
uint32_t castor3d::UniformBufferBase::getAlignedSize (uint32_t size) const inline
Retrieves the aligned size for an element.
Parameters
[in] size The size of an element.
Returns
The aligned size.
References getAlignedSize(), and getBuffer().
getAlignedSize() [2/2]
uint32_t castor3d::UniformBufferBase::getAlignedSize () const inline
Returns
The aligned size for an element.
References getElementSize().
Referenced by getAlignedSize().
getBuffer() [1/2]
ashes::UniformBuffer const& castor3d::UniformBufferBase::getBuffer () const inline
Returns
The internal buffer.
Referenced by getAlignedSize(), and getElementSize().
getBuffer() [2/2]
ashes::UniformBuffer& castor3d::UniformBufferBase::getBuffer () inline
Returns
The internal buffer.
getElementSize()
uint32_t castor3d::UniformBufferBase::getElementSize () const inline
Returns
The size of one element in the buffer.
References getBuffer().
Referenced by getAlignedSize().
hasAvailable()
C3D_API bool castor3d::UniformBufferBase::hasAvailable () const
Returns
true if there is enough remaining memory for a new element.
hasBuffer()
bool castor3d::UniformBufferBase::hasBuffer () const inline
Returns
false if the internal buffer doesn't exist.
initialise() [1/2]
C3D_API uint32_t castor3d::UniformBufferBase::initialise (RenderDevice const & device)
Initialises the GPU buffer.
Parameters
[in] device The GPU device.
initialise() [2/2]
C3D_API uint32_t castor3d::UniformBufferBase::initialise (RenderDevice const & device, ashes::QueueShare sharingMode)
Initialises the GPU buffer.
Parameters
[in] device The GPU device.
[in] sharingMode The buffer sharing mode.
operator ashes::UniformBuffer &()
castor3d::UniformBufferBase::operator ashes::UniformBuffer & () inline
operator ashes::UniformBuffer const &()
castor3d::UniformBufferBase::operator ashes::UniformBuffer const & () const inline
upload() [1/8]
C3D_API void castor3d::UniformBufferBase::upload (ashes::BufferBase const & stagingBuffer, ashes::Queue const & queue, ashes::CommandPool const & commandPool, const void * data, size_t size, uint32_t offset, VkPipelineStageFlags flags) const
Transfers data to the GPU buffer from RAM.
Remarks
Transfers data from buffer[offset*sizeof(T)] to buffer[(offset+count-1)*sizeof(T)].
Parameters
[in] stagingBuffer The staging buffer used to transfer the data.
[in] queue The queue used to execute the transfer.
[in] commandPool The command pool on which the command buffer will be created.
[in] data The data to upload, packed (will be aligned on upload).
[in] size The data size.
[in] offset The start offset.
[in] flags The pipeline stage flags for the out memory barrier.
Referenced by upload().
upload() [2/8]
void castor3d::UniformBufferBase::upload (ashes::BufferBase const & stagingBuffer, ashes::Queue const & queue, ashes::CommandPool const & commandPool, ashes::ByteArray const & data, uint32_t offset, VkPipelineStageFlags flags) const inline
Transfers data to the GPU buffer from RAM.
Remarks
Transfers data from buffer[offset*sizeof(T)] to buffer[(offset+count-1)*sizeof(T)].
Parameters
[in] stagingBuffer The staging buffer used to transfer the data.
[in] queue The queue used to execute the transfer.
[in] commandPool The command pool on which the command buffer will be created.
[in] data The data to upload, packed (will be aligned on upload).
[in] offset The start offset.
[in] flags The pipeline stage flags for the out memory barrier.
References upload().
upload() [3/8]
C3D_API void castor3d::UniformBufferBase::upload (ashes::BufferBase const & stagingBuffer, ashes::CommandBuffer const & commandBuffer, const void * data, size_t size, uint32_t offset, VkPipelineStageFlags flags) const
Transfers data to the GPU buffer from RAM.
Remarks
Transfers data from buffer[offset*sizeof(T)] to buffer[(offset+count-1)*sizeof(T)].
Parameters
[in] stagingBuffer The staging buffer used to transfer the data.
[in] commandBuffer The command buffer on which the transfer commands are recorded.
[in] data The data to upload, packed (will be aligned on upload).
[in] size The data size.
[in] offset The start offset.
[in] flags The pipeline stage flags for the out memory barrier.
upload() [4/8]
void castor3d::UniformBufferBase::upload (ashes::BufferBase const & stagingBuffer, ashes::CommandBuffer const & commandBuffer, ashes::ByteArray const & data, uint32_t offset, VkPipelineStageFlags flags) const inline
Transfers data to the GPU buffer from RAM.
Remarks
Transfers data from buffer[offset*sizeof(T)] to buffer[(offset+count-1)*sizeof(T)].
Parameters
[in] stagingBuffer The staging buffer used to transfer the data.
[in] commandBuffer The command buffer on which the transfer commands are recorded.
[in] data The data to upload, packed (will be aligned on upload).
[in] offset The start offset.
[in] flags The pipeline stage flags for the out memory barrier.
References upload().
upload() [5/8]
C3D_API void castor3d::UniformBufferBase::upload (ashes::BufferBase const & stagingBuffer, ashes::Queue const & queue, ashes::CommandPool const & commandPool, const void * data, size_t size, uint32_t offset, VkPipelineStageFlags flags, RenderPassTimer const & timer, uint32_t index) const
Transfers data to the GPU buffer from RAM.
Remarks
Transfers data from buffer[offset*sizeof(T)] to buffer[(offset+count-1)*sizeof(T)].
Parameters
[in] stagingBuffer The staging buffer used to transfer the data.
[in] queue The queue used to execute the transfer.
[in] commandPool The command pool on which the command buffer will be created.
[in] data The data to upload, packed (will be aligned on upload).
[in] size The data size.
[in] offset The start offset.
[in] flags The pipeline stage flags for the out memory barrier.
[in] timer The render pass timer.
[in] index The render pass index.
upload() [6/8]
void castor3d::UniformBufferBase::upload (ashes::BufferBase const & stagingBuffer, ashes::Queue const & queue, ashes::CommandPool const & commandPool, ashes::ByteArray const & data, uint32_t offset, VkPipelineStageFlags flags, RenderPassTimer const & timer, uint32_t index) const inline
Transfers data to the GPU buffer from RAM.
Remarks
Transfers data from buffer[offset*sizeof(T)] to buffer[(offset+count-1)*sizeof(T)].
Parameters
[in] stagingBuffer The staging buffer used to transfer the data.
[in] queue The queue used to execute the transfer.
[in] commandPool The command pool on which the command buffer will be created.
[in] data The data to upload, packed (will be aligned on upload).
[in] offset The start offset.
[in] flags The pipeline stage flags for the out memory barrier.
[in] timer The render pass timer.
[in] index The render pass index.
References upload().
upload() [7/8]
C3D_API void castor3d::UniformBufferBase::upload (ashes::BufferBase const & stagingBuffer, ashes::CommandBuffer const & commandBuffer, const void * data, size_t size, uint32_t offset, VkPipelineStageFlags flags, RenderPassTimer const & timer, uint32_t index) const
Transfers data to the GPU buffer from RAM.
Remarks
Transfers data from buffer[offset*sizeof(T)] to buffer[(offset+count-1)*sizeof(T)].
Parameters
[in] stagingBuffer The staging buffer used to transfer the data.
[in] commandBuffer The command buffer on which the transfer commands are recorded.
[in] data The data to upload, packed (will be aligned on upload).
[in] size The data size.
[in] offset The start offset.
[in] flags The pipeline stage flags for the out memory barrier.
[in] timer The render pass timer.
[in] index The render pass index.
upload() [8/8]
void castor3d::UniformBufferBase::upload (ashes::BufferBase const & stagingBuffer, ashes::CommandBuffer const & commandBuffer, ashes::ByteArray const & data, uint32_t offset, VkPipelineStageFlags flags, RenderPassTimer const & timer, uint32_t index) const inline
Transfers data to the GPU buffer from RAM.
Remarks
Transfers data from buffer[offset*sizeof(T)] to buffer[(offset+count-1)*sizeof(T)].
Parameters
[in] stagingBuffer The staging buffer used to transfer the data.
[in] commandBuffer The command buffer on which the transfer commands are recorded.
[in] data The data to upload, packed (will be aligned on upload).
[in] offset The start offset.
[in] flags The pipeline stage flags for the out memory barrier.
[in] timer The render pass timer.
[in] index The render pass index.
References upload().
The documentation for this class was generated from the following file:
Buffer/UniformBufferBase.hpp