Castor3D: Castor3D::Vertex Class Reference
Castor3D::Vertex Class Reference
Representation of a vertex.
Classes
class TextLoader
Vertex loader.
Public Member Functions
Vertex (BufferElementGroup &p_group)
Constructor.
Vertex (Vertex const &p_source)
Copy constructor.
Vertex & operator= (Vertex const &p_source)
Copy assignment operator.
virtual ~Vertex ()
Destructor.
void SetPosition (Castor::Coords3r const &val)
Sets the vertex position.
void SetPosition (Castor::Point3r const &val)
Sets the vertex position.
void SetPosition (real x, real y, real z)
Sets the vertex position.
void SetPosition (real const *p_pCoords)
Sets the vertex position.
void SetNormal (Castor::Coords3r const &val)
Sets the vertex normal.
void SetNormal (Castor::Point3r const &val)
Sets the vertex normal.
void SetNormal (real x, real y, real z)
Sets the vertex normal.
void SetNormal (real const *p_pCoords)
Sets the vertex normal.
void SetTangent (Castor::Coords3r const &val)
Sets the vertex tangent.
void SetTangent (Castor::Point3r const &val)
Sets the vertex tangent.
void SetTangent (real x, real y, real z)
Sets the vertex tangent.
void SetTangent (real const *p_pCoords)
Sets the vertex tangent.
void SetBitangent (Castor::Coords3r const &val)
Sets the vertex bitangent.
void SetBitangent (Castor::Point3r const &val)
Sets the vertex bitangent.
void SetBitangent (real x, real y, real z)
Sets the vertex bitangent.
void SetBitangent (real const *p_pCoords)
Sets the vertex bitangent.
void SetTexCoord (Castor::Coords3r const &val)
Sets the vertex texture coordinates.
void SetTexCoord (Castor::Point3r const &val)
Sets the vertex texture coordinates.
void SetTexCoord (real x, real y, real z=0)
Sets the vertex texture coordinates.
void SetTexCoord (real const *p_pCoords)
Sets the vertex texture coordinates.
Castor::Coords3r & GetPosition (Castor::Coords3r &p_ptPos)
Retrieves the vertex position.
Castor::Point3r & GetPosition (Castor::Point3r &p_ptPos) const
Retrieves the vertex position.
Castor::Coords3r & GetNormal (Castor::Coords3r &p_ptNml)
Retrieves the vertex normal.
Castor::Point3r & GetNormal (Castor::Point3r &p_ptNml) const
Retrieves the vertex normal.
Castor::Coords3r & GetTangent (Castor::Coords3r &p_ptTan)
Retrieves the vertex tangent.
Castor::Point3r & GetTangent (Castor::Point3r &p_ptTan) const
Retrieves the vertex tangent.
Castor::Coords3r & GetBitangent (Castor::Coords3r &p_ptBitan)
Retrieves the vertex bitangent.
Castor::Point3r & GetBitangent (Castor::Point3r &p_ptBitan) const
Retrieves the vertex bitangent.
Castor::Coords3r & GetTexCoord (Castor::Coords3r &p_ptTex)
Retrieves the vertex texture coordinates.
Castor::Point3r & GetTexCoord (Castor::Point3r &p_ptTex) const
Retrieves the vertex texture coordinates.
Static Public Member Functions
static const uint32_t GetCountPos ()
Retrieves position elements count.
static const uint32_t GetCountNml ()
Retrieves normal elements count.
static const uint32_t GetCountTan ()
Retrieves tangent elements count.
static const uint32_t GetCountBin ()
Retrieves bitangent elements count.
static const uint32_t GetCountTex ()
Retrieves texture coordinates elements count.
static const uint32_t GetOffsetPos ()
Retrieves position's buffer offset.
static const uint32_t GetOffsetNml ()
Retrieves normal's buffer offset.
static const uint32_t GetOffsetTan ()
Retrieves tangent's buffer offset.
static const uint32_t GetOffsetBin ()
Retrieves bitangent's buffer offset.
static const uint32_t GetOffsetTex ()
Retrieves texture coordinates' buffer offset.
static const uint32_t GetSizePos ()
Retrieves position binary size.
static const uint32_t GetSizeNml ()
Retrieves normal binary size.
static const uint32_t GetSizeTan ()
Retrieves tangent binary size.
static const uint32_t GetSizeBin ()
Retrieves bitangent binary size.
static const uint32_t GetSizeTex ()
Retrieves texture coordinates binary size.
static Castor::Coords3r GetPosition (void *p_pBuffer)
Retrieves a vertex position from a buffer.
static Castor::Point3r GetPosition (void const *p_pBuffer)
Retrieves a vertex position from a buffer.
static Castor::Coords3r & GetPosition (void *p_pBuffer, Castor::Coords3r &p_coord)
Retrieves a vertex position from a buffer.
static Castor::Point3r & GetPosition (void const *p_pBuffer, Castor::Point3r &p_coord)
Retrieves a vertex position from a buffer.
static Castor::Coords3r GetNormal (void *p_pBuffer)
Retrieves a vertex normal from a buffer.
static Castor::Point3r GetNormal (void const *p_pBuffer)
Retrieves a vertex normal from a buffer.
static Castor::Coords3r & GetNormal (void *p_pBuffer, Castor::Coords3r &p_coord)
Retrieves a vertex normal from a buffer.
static Castor::Point3r & GetNormal (void const *p_pBuffer, Castor::Point3r &p_coord)
Retrieves a vertex normal from a buffer.
static Castor::Coords3r GetTangent (void *p_pBuffer)
Retrieves a vertex tangent from a buffer.
static Castor::Point3r GetTangent (void const *p_pBuffer)
Retrieves a vertex tangent from a buffer.
static Castor::Coords3r & GetTangent (void *p_pBuffer, Castor::Coords3r &p_coord)
Retrieves a vertex tangent from a buffer.
static Castor::Point3r & GetTangent (void const *p_pBuffer, Castor::Point3r &p_coord)
Retrieves a vertex tangent from a buffer.
static Castor::Coords3r GetBitangent (void *p_pBuffer)
Retrieves a vertex bitangent from a buffer.
static Castor::Point3r GetBitangent (void const *p_pBuffer)
Retrieves a vertex bitangent from a buffer.
static Castor::Coords3r & GetBitangent (void *p_pBuffer, Castor::Coords3r &p_coord)
Retrieves a vertex bitangent from a buffer.
static Castor::Point3r & GetBitangent (void const *p_pBuffer, Castor::Point3r &p_coord)
Retrieves a vertex bitangent from a buffer.
static Castor::Coords3r GetTexCoord (void *p_pBuffer)
Retrieves a vertex texture coordinates from a buffer.
static Castor::Point3r GetTexCoord (void const *p_pBuffer)
Retrieves a vertex texture coordinates from a buffer.
static Castor::Coords3r & GetTexCoord (void *p_pBuffer, Castor::Coords3r &p_coord)
Retrieves a vertex texture coordinates from a buffer.
static Castor::Point3r & GetTexCoord (void const *p_pBuffer, Castor::Point3r &p_coord)
Retrieves a vertex texture coordinates from a buffer.
static void SetPosition (void *p_pBuffer, Castor::Coords3r const &p_coord)
Sets the vertex position in a buffer.
static void SetPosition (void *p_pBuffer, Castor::Point3r const &p_coord)
Sets the vertex position in a buffer.
static void SetPosition (void *p_pBuffer, real const *p_coord)
Sets the vertex position in a buffer.
static void SetPosition (void *p_pBuffer, real x, real y, real z)
Sets the vertex position in a buffer.
static void SetNormal (void *p_pBuffer, Castor::Coords3r const &p_coord)
Sets the vertex normal in a buffer.
static void SetNormal (void *p_pBuffer, Castor::Point3r const &p_coord)
Sets the vertex normal in a buffer.
static void SetNormal (void *p_pBuffer, real const *p_coord)
Sets the vertex normal in a buffer.
static void SetNormal (void *p_pBuffer, real x, real y, real z)
Sets the vertex normal in a buffer.
static void SetTangent (void *p_pBuffer, Castor::Coords3r const &p_coord)
Sets the vertex tangent in a buffer.
static void SetTangent (void *p_pBuffer, Castor::Point3r const &p_coord)
Sets the vertex tangent in a buffer.
static void SetTangent (void *p_pBuffer, real const *p_coord)
Sets the vertex tangent in a buffer.
static void SetTangent (void *p_pBuffer, real x, real y, real z)
Sets the vertex tangent in a buffer.
static void SetBitangent (void *p_pBuffer, Castor::Coords3r const &p_coord)
Sets the vertex bitangent in a buffer.
static void SetBitangent (void *p_pBuffer, Castor::Point3r const &p_coord)
Sets the vertex bitangent in a buffer.
static void SetBitangent (void *p_pBuffer, real const *p_coord)
Sets the vertex bitangent in a buffer.
static void SetBitangent (void *p_pBuffer, real x, real y, real z)
Sets the vertex bitangent in a buffer.
static void SetTexCoord (void *p_pBuffer, Castor::Coords3r const &p_coord)
Sets the vertex texture coordinates in a buffer.
static void SetTexCoord (void *p_pBuffer, Castor::Point3r const &p_coord)
Sets the vertex texture coordinates in a buffer.
static void SetTexCoord (void *p_pBuffer, real const *p_coord)
Sets the vertex texture coordinates in a buffer.
static void SetTexCoord (void *p_pBuffer, real x, real y, real z=0)
Sets the vertex texture coordinates in a buffer.
static Castor::Coords3r & GetPosition (BufferElementGroupSPtr p_pElement, Castor::Coords3r &p_coord)
Retrieves the group position.
static Castor::Point3r & GetPosition (BufferElementGroupSPtr p_pElement, Castor::Point3r &p_point)
Retrieves the group position.
static Castor::Coords3r & GetNormal (BufferElementGroupSPtr p_pElement, Castor::Coords3r &p_coord)
Retrieves the group normal.
static Castor::Point3r & GetNormal (BufferElementGroupSPtr p_pElement, Castor::Point3r &p_point)
Retrieves the group normal.
static Castor::Coords3r & GetTangent (BufferElementGroupSPtr p_pElement, Castor::Coords3r &p_coord)
Retrieves the group tangent.
static Castor::Point3r & GetTangent (BufferElementGroupSPtr p_pElement, Castor::Point3r &p_point)
Retrieves the group tangent.
static Castor::Coords3r & GetBitangent (BufferElementGroupSPtr p_pElement, Castor::Coords3r &p_coord)
Retrieves the group bitangent.
static Castor::Point3r & GetBitangent (BufferElementGroupSPtr p_pElement, Castor::Point3r &p_point)
Retrieves the group bitangent.
static Castor::Coords3r & GetTexCoord (BufferElementGroupSPtr p_pElement, Castor::Coords3r &p_coord)
Retrieves the group texture coordinates.
static Castor::Point3r & GetTexCoord (BufferElementGroupSPtr p_pElement, Castor::Point3r &p_point)
Retrieves the group texture coordinates.
static void SetPosition (BufferElementGroupSPtr p_pElement, Castor::Coords3r const &p_coord)
Sets the group position.
static void SetPosition (BufferElementGroupSPtr p_pElement, Castor::Point3r const &p_coord)
Sets the group position.
static void SetPosition (BufferElementGroupSPtr p_pElement, real const *p_coord)
Sets the group position.
static void SetPosition (BufferElementGroupSPtr p_pElement, real x, real y, real z)
Sets the group position.
static void SetNormal (BufferElementGroupSPtr p_pElement, Castor::Coords3r const &p_coord)
Sets the group normal.
static void SetNormal (BufferElementGroupSPtr p_pElement, Castor::Point3r const &p_coord)
Sets the group normal.
static void SetNormal (BufferElementGroupSPtr p_pElement, real const *p_coord)
Sets the group normal.
static void SetNormal (BufferElementGroupSPtr p_pElement, real x, real y, real z)
Sets the group normal.
static void SetTangent (BufferElementGroupSPtr p_pElement, Castor::Coords3r const &p_coord)
Sets the group tangent.
static void SetTangent (BufferElementGroupSPtr p_pElement, Castor::Point3r const &p_coord)
Sets the group tangent.
static void SetTangent (BufferElementGroupSPtr p_pElement, real const *p_coord)
Sets the group tangent.
static void SetTangent (BufferElementGroupSPtr p_pElement, real x, real y, real z)
Sets the group tangent.
static void SetBitangent (BufferElementGroupSPtr p_pElement, Castor::Coords3r const &p_coord)
Sets the group bitangent.
static void SetBitangent (BufferElementGroupSPtr p_pElement, Castor::Point3r const &p_coord)
Sets the group bitangent.
static void SetBitangent (BufferElementGroupSPtr p_pElement, real const *p_coord)
Sets the group bitangent.
static void SetBitangent (BufferElementGroupSPtr p_pElement, real x, real y, real z)
Sets the group bitangent.
static void SetTexCoord (BufferElementGroupSPtr p_pElement, Castor::Coords3r const &p_coord)
Sets the group texture coordinates.
static void SetTexCoord (BufferElementGroupSPtr p_pElement, Castor::Point3r const &p_coord)
Sets the group texture coordinates.
static void SetTexCoord (BufferElementGroupSPtr p_pElement, real const *p_coord)
Sets the group texture coordinates.
static void SetTexCoord (BufferElementGroupSPtr p_pElement, real x, real y, real z=0)
Sets the group texture coordinates.
static Castor::Coords3r & GetPosition (BufferElementGroup &p_element, Castor::Coords3r &p_coord)
Retrieves the group position.
static Castor::Point3r & GetPosition (BufferElementGroup const &p_element, Castor::Point3r &p_point)
Retrieves the group position.
static Castor::Coords3r & GetNormal (BufferElementGroup &p_element, Castor::Coords3r &p_coord)
Retrieves the group normal.
static Castor::Point3r & GetNormal (BufferElementGroup const &p_element, Castor::Point3r &p_point)
Retrieves the group normal.
static Castor::Coords3r & GetTangent (BufferElementGroup &p_element, Castor::Coords3r &p_coord)
Retrieves the group tangent.
static Castor::Point3r & GetTangent (BufferElementGroup const &p_element, Castor::Point3r &p_point)
Retrieves the group tangent.
static Castor::Coords3r & GetBitangent (BufferElementGroup &p_element, Castor::Coords3r &p_coord)
Retrieves the group bitangent.
static Castor::Point3r & GetBitangent (BufferElementGroup const &p_element, Castor::Point3r &p_point)
Retrieves the group bitangent.
static Castor::Coords3r & GetTexCoord (BufferElementGroup &p_element, Castor::Coords3r &p_coord)
Retrieves the group texture coordinates.
static Castor::Point3r & GetTexCoord (BufferElementGroup const &p_element, Castor::Point3r &p_point)
Retrieves the group texture coordinates.
static void SetPosition (BufferElementGroup &p_element, Castor::Coords3r const &p_coord)
Sets the group position.
static void SetPosition (BufferElementGroup &p_element, Castor::Point3r const &p_coord)
Sets the group position.
static void SetPosition (BufferElementGroup &p_element, real const *p_coord)
Sets the group position.
static void SetPosition (BufferElementGroup &p_element, real x, real y, real z)
Sets the group position.
static void SetNormal (BufferElementGroup &p_element, Castor::Coords3r const &p_coord)
Sets the group normal.
static void SetNormal (BufferElementGroup &p_element, Castor::Point3r const &p_coord)
Sets the group normal.
static void SetNormal (BufferElementGroup &p_element, real const *p_coord)
Sets the group normal.
static void SetNormal (BufferElementGroup &p_element, real x, real y, real z)
Sets the group normal.
static void SetTangent (BufferElementGroup &p_element, Castor::Coords3r const &p_coord)
Sets the group tangent.
static void SetTangent (BufferElementGroup &p_element, Castor::Point3r const &p_coord)
Sets the group tangent.
static void SetTangent (BufferElementGroup &p_element, real const *p_coord)
Sets the group tangent.
static void SetTangent (BufferElementGroup &p_element, real x, real y, real z)
Sets the group tangent.
static void SetBitangent (BufferElementGroup &p_element, Castor::Coords3r const &p_coord)
Sets the group bitangent.
static void SetBitangent (BufferElementGroup &p_element, Castor::Point3r const &p_coord)
Sets the group bitangent.
static void SetBitangent (BufferElementGroup &p_element, real const *p_coord)
Sets the group bitangent.
static void SetBitangent (BufferElementGroup &p_element, real x, real y, real z)
Sets the group bitangent.
static void SetTexCoord (BufferElementGroup &p_element, Castor::Coords3r const &p_coord)
Sets the group texture coordinates.
static void SetTexCoord (BufferElementGroup &p_element, Castor::Point3r const &p_coord)
Sets the group texture coordinates.
static void SetTexCoord (BufferElementGroup &p_element, real const *p_coord)
Sets the group texture coordinates.
static void SetTexCoord (BufferElementGroup &p_element, real x, real y, real z=0)
Sets the group texture coordinates.
Protected Attributes
BufferElementGroup & m_group
The wrapped group.
Static Protected Attributes
static const uint32_t sm_uiCountPos = 3
Vertex position elements count.
static const uint32_t sm_uiCountNml = 3
Vertex normal elements count.
static const uint32_t sm_uiCountTan = 3
Vertex tangent elements count.
static const uint32_t sm_uiCountBin = 3
Vertex bitangent elements count.
static const uint32_t sm_uiCountTex = 3
Vertex texture coordinates elements count.
static const uint32_t sm_uiSizePos = uint32_t(sm_uiCountPos * sizeof(real))
Vertex position binary size.
static const uint32_t sm_uiSizeNml = uint32_t(sm_uiCountNml * sizeof(real))
Vertex normal binary size.
static const uint32_t sm_uiSizeTan = uint32_t(sm_uiCountTan * sizeof(real))
Vertex tangent binary size.
static const uint32_t sm_uiSizeBin = uint32_t(sm_uiCountBin * sizeof(real))
Vertex bitangent binary size.
static const uint32_t sm_uiSizeTex = uint32_t(sm_uiCountTex * sizeof(real))
Vertex texture coordinates binary size.
static const uint32_t sm_uiOffsetPos = 0
Vertex position's buffer offset.
static const uint32_t sm_uiOffsetNml = sm_uiOffsetPos + sm_uiSizePos
Vertex normal's buffer offset.
static const uint32_t sm_uiOffsetTan = sm_uiOffsetNml + sm_uiSizeNml
Vertex tangent's buffer offset.
static const uint32_t sm_uiOffsetBin = sm_uiOffsetTan + sm_uiSizeTan
Vertex bitangent's buffer offset.
static const uint32_t sm_uiOffsetTex = sm_uiOffsetBin + sm_uiSizeBin
Vertex texture coordinates' buffer offset.
Detailed Description
Representation of a vertex.
Author
Sylvain DOREMUS
Version
0.7.0
Date
27/06/2013
Remarks
Wraps BufferElementGroup to easily retrieve vertex's position, normal, tangent and texture coordinates, an index
Constructor & Destructor Documentation
Vertex() [1/2]
Castor3D::Vertex::Vertex (BufferElementGroup & p_group)
Constructor.
Parameters
[in] p_group The wrapped group
Vertex() [2/2]
Castor3D::Vertex::Vertex (Vertex const & p_source)
Copy constructor.
Parameters
[in] p_source The source object
~Vertex()
virtual Castor3D::Vertex::~Vertex () virtual
Destructor.
Member Function Documentation
GetBitangent() [1/10]
Castor::Coords3r& Castor3D::Vertex::GetBitangent (Castor::Coords3r & p_ptBitan) inline
Retrieves the vertex bitangent.
Returns
The value
GetBitangent() [2/10]
Castor::Point3r& Castor3D::Vertex::GetBitangent (Castor::Point3r & p_ptBitan) const inline
Retrieves the vertex bitangent.
Returns
The value
GetBitangent() [3/10]
static Castor::Coords3r Castor3D::Vertex::GetBitangent (void * p_pBuffer) static
Retrieves a vertex bitangent from a buffer.
Parameters
[in] p_pBuffer The buffer
Returns
The value
GetBitangent() [4/10]
static Castor::Point3r Castor3D::Vertex::GetBitangent (void const * p_pBuffer) static
Retrieves a vertex bitangent from a buffer.
Parameters
[in] p_pBuffer The buffer
Returns
The value
GetBitangent() [5/10]
static Castor::Coords3r& Castor3D::Vertex::GetBitangent (void * p_pBuffer, Castor::Coords3r & p_coord) inline static
Retrieves a vertex bitangent from a buffer.
Parameters
[in] p_pBuffer The buffer
[out] p_coord Receives the value
Returns
The value
GetBitangent() [6/10]
static Castor::Point3r& Castor3D::Vertex::GetBitangent (void const * p_pBuffer, Castor::Point3r & p_coord) inline static
Retrieves a vertex bitangent from a buffer.
Parameters
[in] p_pBuffer The buffer
[out] p_coord Receives the value
Returns
The value
GetBitangent() [7/10]
static Castor::Coords3r& Castor3D::Vertex::GetBitangent (BufferElementGroupSPtr p_pElement, Castor::Coords3r & p_coord) inline static
Retrieves the group bitangent.
Parameters
[in] p_pElement The group
[out] p_coord Receives the bitangent
Returns
The value
GetBitangent() [8/10]
static Castor::Point3r& Castor3D::Vertex::GetBitangent (BufferElementGroupSPtr p_pElement, Castor::Point3r & p_point) inline static
Retrieves the group bitangent.
Parameters
[in] p_pElement The group
[out] p_point Receives the bitangent
Returns
The value
GetBitangent() [9/10]
static Castor::Coords3r& Castor3D::Vertex::GetBitangent (BufferElementGroup & p_element, Castor::Coords3r & p_coord) inline static
Retrieves the group bitangent.
Parameters
[in] p_element The group
[out] p_coord Receives the bitangent
Returns
The value
References Castor3D::BufferElementGroup::ptr().
GetBitangent() [10/10]
static Castor::Point3r& Castor3D::Vertex::GetBitangent (BufferElementGroup const & p_element, Castor::Point3r & p_point) inline static
Retrieves the group bitangent.
Parameters
[in] p_element The group
[out] p_point Receives the bitangent
Returns
The value
References Castor3D::BufferElementGroup::const_ptr().
GetCountBin()
static const uint32_t Castor3D::Vertex::GetCountBin () inline static
Retrieves bitangent elements count.
Returns
The value
GetCountNml()
static const uint32_t Castor3D::Vertex::GetCountNml () inline static
Retrieves normal elements count.
Returns
The value
GetCountPos()
static const uint32_t Castor3D::Vertex::GetCountPos () inline static
Retrieves position elements count.
Returns
The value
GetCountTan()
static const uint32_t Castor3D::Vertex::GetCountTan () inline static
Retrieves tangent elements count.
Returns
The value
GetCountTex()
static const uint32_t Castor3D::Vertex::GetCountTex () inline static
Retrieves texture coordinates elements count.
Returns
The value
GetNormal() [1/10]
Castor::Coords3r& Castor3D::Vertex::GetNormal (Castor::Coords3r & p_ptNml) inline
Retrieves the vertex normal.
Returns
The value
GetNormal() [2/10]
Castor::Point3r& Castor3D::Vertex::GetNormal (Castor::Point3r & p_ptNml) const inline
Retrieves the vertex normal.
Returns
The value
GetNormal() [3/10]
static Castor::Coords3r Castor3D::Vertex::GetNormal (void * p_pBuffer) static
Retrieves a vertex normal from a buffer.
Parameters
[in] p_pBuffer The buffer
Returns
The value
GetNormal() [4/10]
static Castor::Point3r Castor3D::Vertex::GetNormal (void const * p_pBuffer) static
Retrieves a vertex normal from a buffer.
Parameters
[in] p_pBuffer The buffer
Returns
The value
GetNormal() [5/10]
static Castor::Coords3r& Castor3D::Vertex::GetNormal (void * p_pBuffer, Castor::Coords3r & p_coord) inline static
Retrieves a vertex normal from a buffer.
Parameters
[in] p_pBuffer The buffer
[out] p_coord Receives the value
Returns
The value
GetNormal() [6/10]
static Castor::Point3r& Castor3D::Vertex::GetNormal (void const * p_pBuffer, Castor::Point3r & p_coord) inline static
Retrieves a vertex normal from a buffer.
Parameters
[in] p_pBuffer The buffer
[out] p_coord Receives the value
Returns
The value
GetNormal() [7/10]
static Castor::Coords3r& Castor3D::Vertex::GetNormal (BufferElementGroupSPtr p_pElement, Castor::Coords3r & p_coord) inline static
Retrieves the group normal.
Parameters
[in] p_pElement The group
[out] p_coord Receives the normal
Returns
The value
GetNormal() [8/10]
static Castor::Point3r& Castor3D::Vertex::GetNormal (BufferElementGroupSPtr p_pElement, Castor::Point3r & p_point) inline static
Retrieves the group normal.
Parameters
[in] p_pElement The group
[out] p_point Receives the normal
Returns
The value
GetNormal() [9/10]
static Castor::Coords3r& Castor3D::Vertex::GetNormal (BufferElementGroup & p_element, Castor::Coords3r & p_coord) inline static
Retrieves the group normal.
Parameters
[in] p_element The group
[out] p_coord Receives the normal
Returns
The value
References Castor3D::BufferElementGroup::ptr().
GetNormal() [10/10]
static Castor::Point3r& Castor3D::Vertex::GetNormal (BufferElementGroup const & p_element, Castor::Point3r & p_point) inline static
Retrieves the group normal.
Parameters
[in] p_element The group
[out] p_point Receives the normal
Returns
The value
References Castor3D::BufferElementGroup::const_ptr().
GetOffsetBin()
static const uint32_t Castor3D::Vertex::GetOffsetBin () inline static
Retrieves bitangent's buffer offset.
Returns
The value
GetOffsetNml()
static const uint32_t Castor3D::Vertex::GetOffsetNml () inline static
Retrieves normal's buffer offset.
Returns
The value
GetOffsetPos()
static const uint32_t Castor3D::Vertex::GetOffsetPos () inline static
Retrieves position's buffer offset.
Returns
The value
GetOffsetTan()
static const uint32_t Castor3D::Vertex::GetOffsetTan () inline static
Retrieves tangent's buffer offset.
Returns
The value
GetOffsetTex()
static const uint32_t Castor3D::Vertex::GetOffsetTex () inline static
Retrieves texture coordinates' buffer offset.
Returns
The value
GetPosition() [1/10]
Castor::Coords3r& Castor3D::Vertex::GetPosition (Castor::Coords3r & p_ptPos) inline
Retrieves the vertex position.
Returns
The value
GetPosition() [2/10]
Castor::Point3r& Castor3D::Vertex::GetPosition (Castor::Point3r & p_ptPos) const inline
Retrieves the vertex position.
Returns
The value
GetPosition() [3/10]
static Castor::Coords3r Castor3D::Vertex::GetPosition (void * p_pBuffer) static
Retrieves a vertex position from a buffer.
Parameters
[in] p_pBuffer The buffer
Returns
The value
GetPosition() [4/10]
static Castor::Point3r Castor3D::Vertex::GetPosition (void const * p_pBuffer) static
Retrieves a vertex position from a buffer.
Parameters
[in] p_pBuffer The buffer
Returns
The value
GetPosition() [5/10]
static Castor::Coords3r& Castor3D::Vertex::GetPosition (void * p_pBuffer, Castor::Coords3r & p_coord) inline static
Retrieves a vertex position from a buffer.
Parameters
[in] p_pBuffer The buffer
[out] p_coord Receives the value
Returns
The value
GetPosition() [6/10]
static Castor::Point3r& Castor3D::Vertex::GetPosition (void const * p_pBuffer, Castor::Point3r & p_coord) inline static
Retrieves a vertex position from a buffer.
Parameters
[in] p_pBuffer The buffer
[out] p_coord Receives the value
Returns
The value
GetPosition() [7/10]
static Castor::Coords3r& Castor3D::Vertex::GetPosition (BufferElementGroupSPtr p_pElement, Castor::Coords3r & p_coord) inline static
Retrieves the group position.
Parameters
[in] p_pElement The group
[out] p_coord Receives the coordinates
Returns
The value
GetPosition() [8/10]
static Castor::Point3r& Castor3D::Vertex::GetPosition (BufferElementGroupSPtr p_pElement, Castor::Point3r & p_point) inline static
Retrieves the group position.
Parameters
[in] p_pElement The group
[out] p_point Receives the coordinates
Returns
The value
GetPosition() [9/10]
static Castor::Coords3r& Castor3D::Vertex::GetPosition (BufferElementGroup & p_element, Castor::Coords3r & p_coord) inline static
Retrieves the group position.
Parameters
[in] p_element The group
[out] p_coord Receives the coordinates
Returns
The value
References Castor3D::BufferElementGroup::ptr().
GetPosition() [10/10]
static Castor::Point3r& Castor3D::Vertex::GetPosition (BufferElementGroup const & p_element, Castor::Point3r & p_point) inline static
Retrieves the group position.
Parameters
[in] p_element The group
[out] p_point Receives the coordinates
Returns
The value
References Castor3D::BufferElementGroup::const_ptr().
GetSizeBin()
static const uint32_t Castor3D::Vertex::GetSizeBin () inline static
Retrieves bitangent binary size.
Returns
The value
GetSizeNml()
static const uint32_t Castor3D::Vertex::GetSizeNml () inline static
Retrieves normal binary size.
Returns
The value
GetSizePos()
static const uint32_t Castor3D::Vertex::GetSizePos () inline static
Retrieves position binary size.
Returns
The value
GetSizeTan()
static const uint32_t Castor3D::Vertex::GetSizeTan () inline static
Retrieves tangent binary size.
Returns
The value
GetSizeTex()
static const uint32_t Castor3D::Vertex::GetSizeTex () inline static
Retrieves texture coordinates binary size.
Returns
The value
GetTangent() [1/10]
Castor::Coords3r& Castor3D::Vertex::GetTangent (Castor::Coords3r & p_ptTan) inline
Retrieves the vertex tangent.
Returns
The value
GetTangent() [2/10]
Castor::Point3r& Castor3D::Vertex::GetTangent (Castor::Point3r & p_ptTan) const inline
Retrieves the vertex tangent.
Returns
The value
GetTangent() [3/10]
static Castor::Coords3r Castor3D::Vertex::GetTangent (void * p_pBuffer) static
Retrieves a vertex tangent from a buffer.
Parameters
[in] p_pBuffer The buffer
Returns
The value
GetTangent() [4/10]
static Castor::Point3r Castor3D::Vertex::GetTangent (void const * p_pBuffer) static
Retrieves a vertex tangent from a buffer.
Parameters
[in] p_pBuffer The buffer
Returns
The value
GetTangent() [5/10]
static Castor::Coords3r& Castor3D::Vertex::GetTangent (void * p_pBuffer, Castor::Coords3r & p_coord) inline static
Retrieves a vertex tangent from a buffer.
Parameters
[in] p_pBuffer The buffer
[out] p_coord Receives the value
Returns
The value
GetTangent() [6/10]
static Castor::Point3r& Castor3D::Vertex::GetTangent (void const * p_pBuffer, Castor::Point3r & p_coord) inline static
Retrieves a vertex tangent from a buffer.
Parameters
[in] p_pBuffer The buffer
[out] p_coord Receives the value
Returns
The value
GetTangent() [7/10]
static Castor::Coords3r& Castor3D::Vertex::GetTangent (BufferElementGroupSPtr p_pElement, Castor::Coords3r & p_coord) inline static
Retrieves the group tangent.
Parameters
[in] p_pElement The group
[out] p_coord Receives the tangent
Returns
The value
GetTangent() [8/10]
static Castor::Point3r& Castor3D::Vertex::GetTangent (BufferElementGroupSPtr p_pElement, Castor::Point3r & p_point) inline static
Retrieves the group tangent.
Parameters
[in] p_pElement The group
[out] p_point Receives the tangent
Returns
The value
GetTangent() [9/10]
static Castor::Coords3r& Castor3D::Vertex::GetTangent (BufferElementGroup & p_element, Castor::Coords3r & p_coord) inline static
Retrieves the group tangent.
Parameters
[in] p_element The group
[out] p_coord Receives the tangent
Returns
The value
References Castor3D::BufferElementGroup::ptr().
GetTangent() [10/10]
static Castor::Point3r& Castor3D::Vertex::GetTangent (BufferElementGroup const & p_element, Castor::Point3r & p_point) inline static
Retrieves the group tangent.
Parameters
[in] p_element The group
[out] p_point Receives the tangent
Returns
The value
References Castor3D::BufferElementGroup::const_ptr().
GetTexCoord() [1/10]
Castor::Coords3r& Castor3D::Vertex::GetTexCoord (Castor::Coords3r & p_ptTex) inline
Retrieves the vertex texture coordinates.
Returns
The value
GetTexCoord() [2/10]
Castor::Point3r& Castor3D::Vertex::GetTexCoord (Castor::Point3r & p_ptTex) const inline
Retrieves the vertex texture coordinates.
Returns
The value
GetTexCoord() [3/10]
static Castor::Coords3r Castor3D::Vertex::GetTexCoord (void * p_pBuffer) static
Retrieves a vertex texture coordinates from a buffer.
Parameters
[in] p_pBuffer The buffer
Returns
The value
GetTexCoord() [4/10]
static Castor::Point3r Castor3D::Vertex::GetTexCoord (void const * p_pBuffer) static
Retrieves a vertex texture coordinates from a buffer.
Parameters
[in] p_pBuffer The buffer
Returns
The value
GetTexCoord() [5/10]
static Castor::Coords3r& Castor3D::Vertex::GetTexCoord (void * p_pBuffer, Castor::Coords3r & p_coord) inline static
Retrieves a vertex texture coordinates from a buffer.
Parameters
[in] p_pBuffer The buffer
[out] p_coord Receives the value
Returns
The value
GetTexCoord() [6/10]
static Castor::Point3r& Castor3D::Vertex::GetTexCoord (void const * p_pBuffer, Castor::Point3r & p_coord) inline static
Retrieves a vertex texture coordinates from a buffer.
Parameters
[in] p_pBuffer The buffer
[out] p_coord Receives the value
Returns
The value
GetTexCoord() [7/10]
static Castor::Coords3r& Castor3D::Vertex::GetTexCoord (BufferElementGroupSPtr p_pElement, Castor::Coords3r & p_coord) inline static
Retrieves the group texture coordinates.
Parameters
[in] p_pElement The group
[out] p_coord Receives the texture coordinates
Returns
The value
GetTexCoord() [8/10]
static Castor::Point3r& Castor3D::Vertex::GetTexCoord (BufferElementGroupSPtr p_pElement, Castor::Point3r & p_point) inline static
Retrieves the group texture coordinates.
Parameters
[in] p_pElement The group
[out] p_point Receives the texture coordinates
Returns
The value
GetTexCoord() [9/10]
static Castor::Coords3r& Castor3D::Vertex::GetTexCoord (BufferElementGroup & p_element, Castor::Coords3r & p_coord) inline static
Retrieves the group texture coordinates.
Parameters
[in] p_element The group
[out] p_coord Receives the texture coordinates
Returns
The value
References Castor3D::BufferElementGroup::ptr().
GetTexCoord() [10/10]
static Castor::Point3r& Castor3D::Vertex::GetTexCoord (BufferElementGroup const & p_element, Castor::Point3r & p_point) inline static
Retrieves the group texture coordinates.
Parameters
[in] p_element The group
[out] p_point Receives the texture coordinates
Returns
The value
References Castor3D::BufferElementGroup::const_ptr().
operator=()
Vertex& Castor3D::Vertex::operator= (Vertex const & p_source)
Copy assignment operator.
Parameters
[in] p_source The source object
Returns
A reference to this object
SetBitangent() [1/16]
void Castor3D::Vertex::SetBitangent (Castor::Coords3r const & val) inline
Sets the vertex bitangent.
Parameters
[in] val The value
SetBitangent() [2/16]
void Castor3D::Vertex::SetBitangent (Castor::Point3r const & val) inline
Sets the vertex bitangent.
Parameters
[in] val The value
SetBitangent() [3/16]
void Castor3D::Vertex::SetBitangent (real x, real y, real z) inline
Sets the vertex bitangent.
Parameters
[in] x,y,z The values
SetBitangent() [4/16]
void Castor3D::Vertex::SetBitangent (real const * p_pCoords) inline
Sets the vertex bitangent.
Parameters
[in] p_pCoords The data buffer
SetBitangent() [5/16]
static void Castor3D::Vertex::SetBitangent (void * p_pBuffer, Castor::Coords3r const & p_coord) inline static
Sets the vertex bitangent in a buffer.
Parameters
[in] p_pBuffer The buffer
[in] p_coord The new value
SetBitangent() [6/16]
static void Castor3D::Vertex::SetBitangent (void * p_pBuffer, Castor::Point3r const & p_coord) inline static
Sets the vertex bitangent in a buffer.
Parameters
[in] p_pBuffer The buffer
[in] p_coord The new value
SetBitangent() [7/16]
static void Castor3D::Vertex::SetBitangent (void * p_pBuffer, real const * p_coord) static
Sets the vertex bitangent in a buffer.
Parameters
[in] p_pBuffer The buffer
[in] p_coord The new value
SetBitangent() [8/16]
static void Castor3D::Vertex::SetBitangent (void * p_pBuffer, real x, real y, real z) static
Sets the vertex bitangent in a buffer.
Parameters
[in] p_pBuffer The buffer
[in] x,y,z The new value
SetBitangent() [9/16]
static void Castor3D::Vertex::SetBitangent (BufferElementGroupSPtr p_pElement, Castor::Coords3r const & p_coord) inline static
Sets the group bitangent.
Parameters
[in] p_pElement The group
[in] p_coord The new value
SetBitangent() [10/16]
static void Castor3D::Vertex::SetBitangent (BufferElementGroupSPtr p_pElement, Castor::Point3r const & p_coord) inline static
Sets the group bitangent.
Parameters
[in] p_pElement The group
[in] p_coord The new value
SetBitangent() [11/16]
static void Castor3D::Vertex::SetBitangent (BufferElementGroupSPtr p_pElement, real const * p_coord) inline static
Sets the group bitangent.
Parameters
[in] p_pElement The group
[in] p_coord The new value
SetBitangent() [12/16]
static void Castor3D::Vertex::SetBitangent (BufferElementGroupSPtr p_pElement, real x, real y, real z) inline static
Sets the group bitangent.
Parameters
[in] p_pElement The group
[in] x,y,z The new value
SetBitangent() [13/16]
static void Castor3D::Vertex::SetBitangent (BufferElementGroup & p_element, Castor::Coords3r const & p_coord) inline static
Sets the group bitangent.
Parameters
[out] p_element The group
[in] p_coord The new value
References Castor3D::BufferElementGroup::ptr().
SetBitangent() [14/16]
static void Castor3D::Vertex::SetBitangent (BufferElementGroup & p_element, Castor::Point3r const & p_coord) inline static
Sets the group bitangent.
Parameters
[out] p_element The group
[in] p_coord The new value
References Castor3D::BufferElementGroup::ptr().
SetBitangent() [15/16]
static void Castor3D::Vertex::SetBitangent (BufferElementGroup & p_element, real const * p_coord) inline static
Sets the group bitangent.
Parameters
[out] p_element The group
[in] p_coord The new value
References Castor3D::BufferElementGroup::ptr().
SetBitangent() [16/16]
static void Castor3D::Vertex::SetBitangent (BufferElementGroup & p_element, real x, real y, real z) inline static
Sets the group bitangent.
Parameters
[out] p_element The group
[in] x,y,z The new value
References Castor3D::BufferElementGroup::ptr().
SetNormal() [1/16]
void Castor3D::Vertex::SetNormal (Castor::Coords3r const & val) inline
Sets the vertex normal.
Parameters
[in] val The value
SetNormal() [2/16]
void Castor3D::Vertex::SetNormal (Castor::Point3r const & val) inline
Sets the vertex normal.
Parameters
[in] val The value
SetNormal() [3/16]
void Castor3D::Vertex::SetNormal (real x, real y, real z) inline
Sets the vertex normal.
Parameters
[in] x,y,z The values
SetNormal() [4/16]
void Castor3D::Vertex::SetNormal (real const * p_pCoords) inline
Sets the vertex normal.
Parameters
[in] p_pCoords The data buffer
SetNormal() [5/16]
static void Castor3D::Vertex::SetNormal (void * p_pBuffer, Castor::Coords3r const & p_coord) inline static
Sets the vertex normal in a buffer.
Parameters
[in] p_pBuffer The buffer
[in] p_coord The new value
SetNormal() [6/16]
static void Castor3D::Vertex::SetNormal (void * p_pBuffer, Castor::Point3r const & p_coord) inline static
Sets the vertex normal in a buffer.
Parameters
[in] p_pBuffer The buffer
[in] p_coord The new value
SetNormal() [7/16]
static void Castor3D::Vertex::SetNormal (void * p_pBuffer, real const * p_coord) static
Sets the vertex normal in a buffer.
Parameters
[in] p_pBuffer The buffer
[in] p_coord The new value
SetNormal() [8/16]
static void Castor3D::Vertex::SetNormal (void * p_pBuffer, real x, real y, real z) static
Sets the vertex normal in a buffer.
Parameters
[in] p_pBuffer The buffer
[in] x,y,z The new value
SetNormal() [9/16]
static void Castor3D::Vertex::SetNormal (BufferElementGroupSPtr p_pElement, Castor::Coords3r const & p_coord) inline static
Sets the group normal.
Parameters
[in] p_pElement The group
[in] p_coord The new value
SetNormal() [10/16]
static void Castor3D::Vertex::SetNormal (BufferElementGroupSPtr p_pElement, Castor::Point3r const & p_coord) inline static
Sets the group normal.
Parameters
[in] p_pElement The group
[in] p_coord The new value
SetNormal() [11/16]
static void Castor3D::Vertex::SetNormal (BufferElementGroupSPtr p_pElement, real const * p_coord) inline static
Sets the group normal.
Parameters
[in] p_pElement The group
[in] p_coord The new value
SetNormal() [12/16]
static void Castor3D::Vertex::SetNormal (BufferElementGroupSPtr p_pElement, real x, real y, real z) inline static
Sets the group normal.
Parameters
[in] p_pElement The group
[in] x,y,z The new value
SetNormal() [13/16]
static void Castor3D::Vertex::SetNormal (BufferElementGroup & p_element, Castor::Coords3r const & p_coord) inline static
Sets the group normal.
Parameters
[out] p_element The group
[in] p_coord The new value
References Castor3D::BufferElementGroup::ptr().
SetNormal() [14/16]
static void Castor3D::Vertex::SetNormal (BufferElementGroup & p_element, Castor::Point3r const & p_coord) inline static
Sets the group normal.
Parameters
[out] p_element The group
[in] p_coord The new value
References Castor3D::BufferElementGroup::ptr().
SetNormal() [15/16]
static void Castor3D::Vertex::SetNormal (BufferElementGroup & p_element, real const * p_coord) inline static
Sets the group normal.
Parameters
[out] p_element The group
[in] p_coord The new value
References Castor3D::BufferElementGroup::ptr().
SetNormal() [16/16]
static void Castor3D::Vertex::SetNormal (BufferElementGroup & p_element, real x, real y, real z) inline static
Sets the group normal.
Parameters
[out] p_element The group
[in] x,y,z The new value
References Castor3D::BufferElementGroup::ptr().
SetPosition() [1/16]
void Castor3D::Vertex::SetPosition (Castor::Coords3r const & val) inline
Sets the vertex position.
Parameters
[in] val The new value
SetPosition() [2/16]
void Castor3D::Vertex::SetPosition (Castor::Point3r const & val) inline
Sets the vertex position.
Parameters
[in] val The new value
SetPosition() [3/16]
void Castor3D::Vertex::SetPosition (real x, real y, real z) inline
Sets the vertex position.
Parameters
[in] x,y,z The new value
SetPosition() [4/16]
void Castor3D::Vertex::SetPosition (real const * p_pCoords) inline
Sets the vertex position.
Parameters
[in] p_pCoords The new value
SetPosition() [5/16]
static void Castor3D::Vertex::SetPosition (void * p_pBuffer, Castor::Coords3r const & p_coord) inline static
Sets the vertex position in a buffer.
Parameters
[in] p_pBuffer The buffer
[in] p_coord The new value
SetPosition() [6/16]
static void Castor3D::Vertex::SetPosition (void * p_pBuffer, Castor::Point3r const & p_coord) inline static
Sets the vertex position in a buffer.
Parameters
[in] p_pBuffer The buffer
[in] p_coord The new value
SetPosition() [7/16]
static void Castor3D::Vertex::SetPosition (void * p_pBuffer, real const * p_coord) static
Sets the vertex position in a buffer.
Parameters
[in] p_pBuffer The buffer
[in] p_coord The new value
SetPosition() [8/16]
static void Castor3D::Vertex::SetPosition (void * p_pBuffer, real x, real y, real z) static
Sets the vertex position in a buffer.
Parameters
[in] p_pBuffer The buffer
[in] x,y,z The new value
SetPosition() [9/16]
static void Castor3D::Vertex::SetPosition (BufferElementGroupSPtr p_pElement, Castor::Coords3r const & p_coord) inline static
Sets the group position.
Parameters
[in] p_pElement The group
[in] p_coord The new value
SetPosition() [10/16]
static void Castor3D::Vertex::SetPosition (BufferElementGroupSPtr p_pElement, Castor::Point3r const & p_coord) inline static
Sets the group position.
Parameters
[in] p_pElement The group
[in] p_coord The new value
SetPosition() [11/16]
static void Castor3D::Vertex::SetPosition (BufferElementGroupSPtr p_pElement, real const * p_coord) inline static
Sets the group position.
Parameters
[in] p_pElement The group
[in] p_coord The new value
SetPosition() [12/16]
static void Castor3D::Vertex::SetPosition (BufferElementGroupSPtr p_pElement, real x, real y, real z) inline static
Sets the group position.
Parameters
[in] p_pElement The group
[in] x,y,z The new value
SetPosition() [13/16]
static void Castor3D::Vertex::SetPosition (BufferElementGroup & p_element, Castor::Coords3r const & p_coord) inline static
Sets the group position.
Parameters
[out] p_element The group
[in] p_coord The new value
References Castor3D::BufferElementGroup::ptr().
SetPosition() [14/16]
static void Castor3D::Vertex::SetPosition (BufferElementGroup & p_element, Castor::Point3r const & p_coord) inline static
Sets the group position.
Parameters
[out] p_element The group
[in] p_coord The new value
References Castor3D::BufferElementGroup::ptr().
SetPosition() [15/16]
static void Castor3D::Vertex::SetPosition (BufferElementGroup & p_element, real const * p_coord) inline static
Sets the group position.
Parameters
[out] p_element The group
[in] p_coord The new value
References Castor3D::BufferElementGroup::ptr().
SetPosition() [16/16]
static void Castor3D::Vertex::SetPosition (BufferElementGroup & p_element, real x, real y, real z) inline static
Sets the group position.
Parameters
[out] p_element The group
[in] x,y,z The new value
References Castor3D::BufferElementGroup::ptr().
SetTangent() [1/16]
void Castor3D::Vertex::SetTangent (Castor::Coords3r const & val) inline
Sets the vertex tangent.
Parameters
[in] val The value
SetTangent() [2/16]
void Castor3D::Vertex::SetTangent (Castor::Point3r const & val) inline
Sets the vertex tangent.
Parameters
[in] val The value
SetTangent() [3/16]
void Castor3D::Vertex::SetTangent (real x, real y, real z) inline
Sets the vertex tangent.
Parameters
[in] x,y,z The values
SetTangent() [4/16]
void Castor3D::Vertex::SetTangent (real const * p_pCoords) inline
Sets the vertex tangent.
Parameters
[in] p_pCoords The data buffer
SetTangent() [5/16]
static void Castor3D::Vertex::SetTangent (void * p_pBuffer, Castor::Coords3r const & p_coord) inline static
Sets the vertex tangent in a buffer.
Parameters
[in] p_pBuffer The buffer
[in] p_coord The new value
SetTangent() [6/16]
static void Castor3D::Vertex::SetTangent (void * p_pBuffer, Castor::Point3r const & p_coord) inline static
Sets the vertex tangent in a buffer.
Parameters
[in] p_pBuffer The buffer
[in] p_coord The new value
SetTangent() [7/16]
static void Castor3D::Vertex::SetTangent (void * p_pBuffer, real const * p_coord) static
Sets the vertex tangent in a buffer.
Parameters
[in] p_pBuffer The buffer
[in] p_coord The new value
SetTangent() [8/16]
static void Castor3D::Vertex::SetTangent (void * p_pBuffer, real x, real y, real z) static
Sets the vertex tangent in a buffer.
Parameters
[in] p_pBuffer The buffer
[in] x,y,z The new value
SetTangent() [9/16]
static void Castor3D::Vertex::SetTangent (BufferElementGroupSPtr p_pElement, Castor::Coords3r const & p_coord) inline static
Sets the group tangent.
Parameters
[in] p_pElement The group
[in] p_coord The new value
SetTangent() [10/16]
static void Castor3D::Vertex::SetTangent (BufferElementGroupSPtr p_pElement, Castor::Point3r const & p_coord) inline static
Sets the group tangent.
Parameters
[in] p_pElement The group
[in] p_coord The new value
SetTangent() [11/16]
static void Castor3D::Vertex::SetTangent (BufferElementGroupSPtr p_pElement, real const * p_coord) inline static
Sets the group tangent.
Parameters
[in] p_pElement The group
[in] p_coord The new value
SetTangent() [12/16]
static void Castor3D::Vertex::SetTangent (BufferElementGroupSPtr p_pElement, real x, real y, real z) inline static
Sets the group tangent.
Parameters
[in] p_pElement The group
[in] x,y,z The new value
SetTangent() [13/16]
static void Castor3D::Vertex::SetTangent (BufferElementGroup & p_element, Castor::Coords3r const & p_coord) inline static
Sets the group tangent.
Parameters
[out] p_element The group
[in] p_coord The new value
References Castor3D::BufferElementGroup::ptr().
SetTangent() [14/16]
static void Castor3D::Vertex::SetTangent (BufferElementGroup & p_element, Castor::Point3r const & p_coord) inline static
Sets the group tangent.
Parameters
[out] p_element The group
[in] p_coord The new value
References Castor3D::BufferElementGroup::ptr().
SetTangent() [15/16]
static void Castor3D::Vertex::SetTangent (BufferElementGroup & p_element, real const * p_coord) inline static
Sets the group tangent.
Parameters
[out] p_element The group
[in] p_coord The new value
References Castor3D::BufferElementGroup::ptr().
SetTangent() [16/16]
static void Castor3D::Vertex::SetTangent (BufferElementGroup & p_element, real x, real y, real z) inline static
Sets the group tangent.
Parameters
[out] p_element The group
[in] x,y,z The new value
References Castor3D::BufferElementGroup::ptr().
SetTexCoord() [1/16]
void Castor3D::Vertex::SetTexCoord (Castor::Coords3r const & val) inline
Sets the vertex texture coordinates.
Parameters
[in] val The value
SetTexCoord() [2/16]
void Castor3D::Vertex::SetTexCoord (Castor::Point3r const & val) inline
Sets the vertex texture coordinates.
Parameters
[in] val The value
SetTexCoord() [3/16]
void Castor3D::Vertex::SetTexCoord (real x, real y, real z = 0) inline
Sets the vertex texture coordinates.
Parameters
[in] x,y,z The values
SetTexCoord() [4/16]
void Castor3D::Vertex::SetTexCoord (real const * p_pCoords) inline
Sets the vertex texture coordinates.
Parameters
[in] p_pCoords The data buffer
SetTexCoord() [5/16]
static void Castor3D::Vertex::SetTexCoord (void * p_pBuffer, Castor::Coords3r const & p_coord) inline static
Sets the vertex texture coordinates in a buffer.
Parameters
[in] p_pBuffer The buffer
[in] p_coord The new value
SetTexCoord() [6/16]
static void Castor3D::Vertex::SetTexCoord (void * p_pBuffer, Castor::Point3r const & p_coord) inline static
Sets the vertex texture coordinates in a buffer.
Parameters
[in] p_pBuffer The buffer
[in] p_coord The new value
SetTexCoord() [7/16]
static void Castor3D::Vertex::SetTexCoord (void * p_pBuffer, real const * p_coord) static
Sets the vertex texture coordinates in a buffer.
Parameters
[in] p_pBuffer The buffer
[in] p_coord The new value
SetTexCoord() [8/16]
static void Castor3D::Vertex::SetTexCoord (void * p_pBuffer, real x, real y, real z = 0) static
Sets the vertex texture coordinates in a buffer.
Parameters
[in] p_pBuffer The buffer
[in] x,y,z The new value
SetTexCoord() [9/16]
static void Castor3D::Vertex::SetTexCoord (BufferElementGroupSPtr p_pElement, Castor::Coords3r const & p_coord) inline static
Sets the group texture coordinates.
Parameters
[in] p_pElement The group
[in] p_coord The new value
SetTexCoord() [10/16]
static void Castor3D::Vertex::SetTexCoord (BufferElementGroupSPtr p_pElement, Castor::Point3r const & p_coord) inline static
Sets the group texture coordinates.
Parameters
[in] p_pElement The group
[in] p_coord The new value
SetTexCoord() [11/16]
static void Castor3D::Vertex::SetTexCoord (BufferElementGroupSPtr p_pElement, real const * p_coord) inline static
Sets the group texture coordinates.
Parameters
[in] p_pElement The group
[in] p_coord The new value
SetTexCoord() [12/16]
static void Castor3D::Vertex::SetTexCoord (BufferElementGroupSPtr p_pElement, real x, real y, real z = 0) inline static
Sets the group texture coordinates.
Parameters
[in] p_pElement The group
[in] x,y,z The new value
SetTexCoord() [13/16]
static void Castor3D::Vertex::SetTexCoord (BufferElementGroup & p_element, Castor::Coords3r const & p_coord) inline static
Sets the group texture coordinates.
Parameters
[out] p_element The group
[in] p_coord The new value
References Castor3D::BufferElementGroup::ptr().
SetTexCoord() [14/16]
static void Castor3D::Vertex::SetTexCoord (BufferElementGroup & p_element, Castor::Point3r const & p_coord) inline static
Sets the group texture coordinates.
Parameters
[out] p_element The group
[in] p_coord The new value
References Castor3D::BufferElementGroup::ptr().
SetTexCoord() [15/16]
static void Castor3D::Vertex::SetTexCoord (BufferElementGroup & p_element, real const * p_coord) inline static
Sets the group texture coordinates.
Parameters
[out] p_element The group
[in] p_coord The new value
References Castor3D::BufferElementGroup::ptr().
SetTexCoord() [16/16]
static void Castor3D::Vertex::SetTexCoord (BufferElementGroup & p_element, real x, real y, real z = 0) inline static
Sets the group texture coordinates.
Parameters
[out] p_element The group
[in] x,y,z The new value
References Castor3D::BufferElementGroup::ptr().
Member Data Documentation
m_group
BufferElementGroup& Castor3D::Vertex::m_group protected
The wrapped group.
sm_uiCountBin
const uint32_t Castor3D::Vertex::sm_uiCountBin = 3 static protected
Vertex bitangent elements count.
sm_uiCountNml
const uint32_t Castor3D::Vertex::sm_uiCountNml = 3 static protected
Vertex normal elements count.
sm_uiCountPos
const uint32_t Castor3D::Vertex::sm_uiCountPos = 3 static protected
Vertex position elements count.
sm_uiCountTan
const uint32_t Castor3D::Vertex::sm_uiCountTan = 3 static protected
Vertex tangent elements count.
sm_uiCountTex
const uint32_t Castor3D::Vertex::sm_uiCountTex = 3 static protected
Vertex texture coordinates elements count.
sm_uiOffsetBin
const uint32_t Castor3D::Vertex::sm_uiOffsetBin = sm_uiOffsetTan + sm_uiSizeTan static protected
Vertex bitangent's buffer offset.
sm_uiOffsetNml
const uint32_t Castor3D::Vertex::sm_uiOffsetNml = sm_uiOffsetPos + sm_uiSizePos static protected
Vertex normal's buffer offset.
sm_uiOffsetPos
const uint32_t Castor3D::Vertex::sm_uiOffsetPos = 0 static protected
Vertex position's buffer offset.
sm_uiOffsetTan
const uint32_t Castor3D::Vertex::sm_uiOffsetTan = sm_uiOffsetNml + sm_uiSizeNml static protected
Vertex tangent's buffer offset.
sm_uiOffsetTex
const uint32_t Castor3D::Vertex::sm_uiOffsetTex = sm_uiOffsetBin + sm_uiSizeBin static protected
Vertex texture coordinates' buffer offset.
sm_uiSizeBin
const uint32_t Castor3D::Vertex::sm_uiSizeBin = uint32_t(sm_uiCountBin * sizeof(real)) static protected
Vertex bitangent binary size.
sm_uiSizeNml
const uint32_t Castor3D::Vertex::sm_uiSizeNml = uint32_t(sm_uiCountNml * sizeof(real)) static protected
Vertex normal binary size.
sm_uiSizePos
const uint32_t Castor3D::Vertex::sm_uiSizePos = uint32_t(sm_uiCountPos * sizeof(real)) static protected
Vertex position binary size.
sm_uiSizeTan
const uint32_t Castor3D::Vertex::sm_uiSizeTan = uint32_t(sm_uiCountTan * sizeof(real)) static protected
Vertex tangent binary size.
sm_uiSizeTex
const uint32_t Castor3D::Vertex::sm_uiSizeTex = uint32_t(sm_uiCountTex * sizeof(real)) static protected
Vertex texture coordinates binary size.
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Vertex.hpp