Castor3D: castor3d::CacheBase< ElementType, KeyType > Class Template Reference
castor3d::CacheBase< ElementType, KeyType > Class Template Reference
Base class for an element cache.
Public Types
using MyCacheType = CacheBase< ElementType, KeyType >
using MyCacheTraits = CacheTraits< ElementType, KeyType >
using Element = ElementType
using Key = KeyType
using Collection = castor::Collection< Element, Key >
using LockType = std::unique_lock< Collection >
using ElementPtr = std::shared_ptr< Element >
using Producer = typename MyCacheTraits::Producer
using Merger = typename MyCacheTraits::Merger
using Initialiser = ElementInitialiser< Element >
using Cleaner = ElementCleaner< Element >
Public Member Functions
CacheBase (Engine &engine, Producer &&produce, Initialiser &&initialise, Cleaner &&clean, Merger &&merge)
Constructor.
~CacheBase ()
Destructor.
void cleanup ()
Sets all the elements to be cleaned up.
void clear ()
Flushes the collection.
bool isEmpty () const
template<typename ... Parameters>
ElementPtr create (Key const &name, Parameters &&... parameters)
Creates an element.
ElementPtr add (Key const &name, ElementPtr element)
Removes an element, given a name.
template<typename ... Parameters>
ElementPtr add (Key const &name, Parameters &&... parameters)
Creates an element.
void remove (Key const &name)
Removes an element, given a name.
void mergeInto (MyCacheType &destination)
template<typename FuncType >
void forEach (FuncType func) const
Applies a function to all the elements of this cache.
template<typename FuncType >
void forEach (FuncType func)
Applies a function to all the elements of this cache.
uint32_t getObjectCount () const
Engine * getEngine () const
castor::String const & getObjectTypeName () const
bool has (Key const &name) const
ElementPtr find (Key const &name) const
Looks for an element with given name.
void lock () const
Locks the collection mutex.
void unlock () const
Unlocks the collection mutex.
auto begin ()
auto begin () const
auto end ()
auto end () const
Protected Member Functions
void doReportCreation (castor::String const &name)
void doReportDuplicate (castor::String const &name)
void doReportNull ()
Protected Attributes
Engine & m_engine
Collection m_elements
Producer m_produce
Initialiser m_initialise
Cleaner m_clean
Merger m_merge
Detailed Description
template<typename ElementType, typename KeyType>
class castor3d::CacheBase< ElementType, KeyType >
Base class for an element cache.
Member Typedef Documentation
Cleaner
template<typename ElementType, typename KeyType> using castor3d::CacheBase< ElementType, KeyType >::Cleaner = ElementCleaner< Element >
Collection
template<typename ElementType, typename KeyType> using castor3d::CacheBase< ElementType, KeyType >::Collection = castor::Collection< Element, Key >
Element
template<typename ElementType, typename KeyType> using castor3d::CacheBase< ElementType, KeyType >::Element = ElementType
ElementPtr
template<typename ElementType, typename KeyType> using castor3d::CacheBase< ElementType, KeyType >::ElementPtr = std::shared_ptr< Element >
Initialiser
template<typename ElementType, typename KeyType> using castor3d::CacheBase< ElementType, KeyType >::Initialiser = ElementInitialiser< Element >
Key
template<typename ElementType, typename KeyType> using castor3d::CacheBase< ElementType, KeyType >::Key = KeyType
LockType
template<typename ElementType, typename KeyType> using castor3d::CacheBase< ElementType, KeyType >::LockType = std::unique_lock< Collection >
Merger
template<typename ElementType, typename KeyType> using castor3d::CacheBase< ElementType, KeyType >::Merger = typename MyCacheTraits::Merger
MyCacheTraits
template<typename ElementType, typename KeyType> using castor3d::CacheBase< ElementType, KeyType >::MyCacheTraits = CacheTraits< ElementType, KeyType >
MyCacheType
template<typename ElementType, typename KeyType> using castor3d::CacheBase< ElementType, KeyType >::MyCacheType = CacheBase< ElementType, KeyType >
Producer
template<typename ElementType, typename KeyType> using castor3d::CacheBase< ElementType, KeyType >::Producer = typename MyCacheTraits::Producer
Constructor & Destructor Documentation
CacheBase()
template<typename ElementType, typename KeyType> castor3d::CacheBase< ElementType, KeyType >::CacheBase (Engine & engine, Producer && produce, Initialiser && initialise, Cleaner && clean, Merger && merge) inline
Constructor.
Parameters
[in] engine The engine.
[in] produce The element producer.
[in] initialise The element initialiser.
[in] clean The element cleaner.
[in] merge The element collection merger.
~CacheBase()
template<typename ElementType, typename KeyType> castor3d::CacheBase< ElementType, KeyType >::~CacheBase () inline
Destructor.
Member Function Documentation
add() [1/2]
template<typename ElementType, typename KeyType> ElementPtr castor3d::CacheBase< ElementType, KeyType >::add (Key const & name, ElementPtr element) inline
Removes an element, given a name.
Parameters
[in] name The element name.
[in] element The element.
Referenced by castor3d::Cache< Overlay, castor::String >::add().
add() [2/2]
template<typename ElementType, typename KeyType> template<typename ... Parameters> ElementPtr castor3d::CacheBase< ElementType, KeyType >::add (Key const & name, Parameters &&... parameters) inline
Creates an element.
Parameters
[in] name The element name.
[in] parameters The other constructor parameters.
Returns
The created object.
begin() [1/2]
template<typename ElementType, typename KeyType> auto castor3d::CacheBase< ElementType, KeyType >::begin () inline
Returns
The iterator to the beginning of the collection.
begin() [2/2]
template<typename ElementType, typename KeyType> auto castor3d::CacheBase< ElementType, KeyType >::begin () const inline
Returns
The iterator to the beginning of the collection.
cleanup()
template<typename ElementType, typename KeyType> void castor3d::CacheBase< ElementType, KeyType >::cleanup () inline
Sets all the elements to be cleaned up.
clear()
template<typename ElementType, typename KeyType> void castor3d::CacheBase< ElementType, KeyType >::clear () inline
Flushes the collection.
Referenced by castor3d::CacheBase< Overlay, castor::String >::mergeInto().
create()
template<typename ElementType, typename KeyType> template<typename ... Parameters> ElementPtr castor3d::CacheBase< ElementType, KeyType >::create (Key const & name, Parameters &&... parameters) inline
Creates an element.
Parameters
[in] name The element name.
[in] parameters The other constructor parameters.
Returns
The created element.
Referenced by castor3d::CacheBase< Overlay, castor::String >::add().
doReportCreation()
template<typename ElementType, typename KeyType> void castor3d::CacheBase< ElementType, KeyType >::doReportCreation (castor::String const & name) inline protected
Referenced by castor3d::CacheBase< Overlay, castor::String >::add(), and castor3d::CacheBase< Overlay, castor::String >::create().
doReportDuplicate()
template<typename ElementType, typename KeyType> void castor3d::CacheBase< ElementType, KeyType >::doReportDuplicate (castor::String const & name) inline protected
Referenced by castor3d::CacheBase< Overlay, castor::String >::add().
doReportNull()
template<typename ElementType, typename KeyType> void castor3d::CacheBase< ElementType, KeyType >::doReportNull () inline protected
Referenced by castor3d::CacheBase< Overlay, castor::String >::add().
end() [1/2]
template<typename ElementType, typename KeyType> auto castor3d::CacheBase< ElementType, KeyType >::end () inline
Returns
The iterator to the end of the collection.
end() [2/2]
template<typename ElementType, typename KeyType> auto castor3d::CacheBase< ElementType, KeyType >::end () const inline
Returns
The iterator to the end of the collection.
find()
template<typename ElementType, typename KeyType> ElementPtr castor3d::CacheBase< ElementType, KeyType >::find (Key const & name) const inline
Looks for an element with given name.
Parameters
[in] name The object name.
Returns
The found element, nullptr if not found.
forEach() [1/2]
template<typename ElementType, typename KeyType> template<typename FuncType > void castor3d::CacheBase< ElementType, KeyType >::forEach (FuncType func) const inline
Applies a function to all the elements of this cache.
Parameters
[in] func The function.
forEach() [2/2]
template<typename ElementType, typename KeyType> template<typename FuncType > void castor3d::CacheBase< ElementType, KeyType >::forEach (FuncType func) inline
Applies a function to all the elements of this cache.
Parameters
[in] func The function.
getEngine()
template<typename ElementType, typename KeyType> Engine* castor3d::CacheBase< ElementType, KeyType >::getEngine () const inline
Returns
The Engine.
getObjectCount()
template<typename ElementType, typename KeyType> uint32_t castor3d::CacheBase< ElementType, KeyType >::getObjectCount () const inline
Returns
The elements count.
getObjectTypeName()
template<typename ElementType, typename KeyType> castor::String const& castor3d::CacheBase< ElementType, KeyType >::getObjectTypeName () const inline
Returns
The Engine.
Referenced by castor3d::CacheBase< Overlay, castor::String >::doReportCreation(), castor3d::CacheBase< Overlay, castor::String >::doReportDuplicate(), and castor3d::CacheBase< Overlay, castor::String >::doReportNull().
has()
template<typename ElementType, typename KeyType> bool castor3d::CacheBase< ElementType, KeyType >::has (Key const & name) const inline
Parameters
[in] name The element name.
Returns
true if an element with given name exists.
isEmpty()
template<typename ElementType, typename KeyType> bool castor3d::CacheBase< ElementType, KeyType >::isEmpty () const inline
Returns
true if the cache is empty.
lock()
template<typename ElementType, typename KeyType> void castor3d::CacheBase< ElementType, KeyType >::lock () const inline
Locks the collection mutex.
Referenced by castor3d::CacheBase< Overlay, castor::String >::add(), castor3d::CacheBase< Overlay, castor::String >::cleanup(), castor3d::CacheBase< Overlay, castor::String >::forEach(), and castor3d::CacheBase< Overlay, castor::String >::mergeInto().
mergeInto()
template<typename ElementType, typename KeyType> void castor3d::CacheBase< ElementType, KeyType >::mergeInto (MyCacheType & destination) inline
Returns
Merges this cache's elements to the one given.
Parameters
[out] destination The destination cache.
remove()
template<typename ElementType, typename KeyType> void castor3d::CacheBase< ElementType, KeyType >::remove (Key const & name) inline
Removes an element, given a name.
Parameters
[in] name The element name.
unlock()
template<typename ElementType, typename KeyType> void castor3d::CacheBase< ElementType, KeyType >::unlock () const inline
Unlocks the collection mutex.
Member Data Documentation
m_clean
template<typename ElementType, typename KeyType> Cleaner castor3d::CacheBase< ElementType, KeyType >::m_clean protected
The element cleaner.
Referenced by castor3d::CacheBase< Overlay, castor::String >::cleanup(), and castor3d::Cache< Overlay, castor::String >::remove().
m_elements
template<typename ElementType, typename KeyType> Collection castor3d::CacheBase< ElementType, KeyType >::m_elements mutable protected
The elements collection.
Referenced by castor3d::CacheBase< Overlay, castor::String >::add(), castor3d::CacheBase< Overlay, castor::String >::begin(), castor3d::CacheBase< Overlay, castor::String >::cleanup(), castor3d::CacheBase< Overlay, castor::String >::clear(), castor3d::CacheBase< Overlay, castor::String >::end(), castor3d::CacheBase< Overlay, castor::String >::find(), castor3d::CacheBase< Overlay, castor::String >::forEach(), castor3d::CacheBase< Overlay, castor::String >::getObjectCount(), castor3d::CacheBase< Overlay, castor::String >::has(), castor3d::CacheBase< Overlay, castor::String >::isEmpty(), castor3d::CacheBase< Overlay, castor::String >::lock(), castor3d::CacheBase< Overlay, castor::String >::mergeInto(), castor3d::Cache< Overlay, castor::String >::remove(), castor3d::CacheBase< Overlay, castor::String >::remove(), and castor3d::CacheBase< Overlay, castor::String >::unlock().
m_engine
template<typename ElementType, typename KeyType> Engine& castor3d::CacheBase< ElementType, KeyType >::m_engine protected
The engine.
Referenced by castor3d::CacheBase< Overlay, castor::String >::getEngine().
m_initialise
template<typename ElementType, typename KeyType> Initialiser castor3d::CacheBase< ElementType, KeyType >::m_initialise protected
The element initialiser.
Referenced by castor3d::CacheBase< Overlay, castor::String >::add().
m_merge
template<typename ElementType, typename KeyType> Merger castor3d::CacheBase< ElementType, KeyType >::m_merge protected
The elements collection merger.
Referenced by castor3d::CacheBase< Overlay, castor::String >::mergeInto().
m_produce
template<typename ElementType, typename KeyType> Producer castor3d::CacheBase< ElementType, KeyType >::m_produce protected
The element producer.
Referenced by castor3d::CacheBase< Overlay, castor::String >::create().
The documentation for this class was generated from the following file:
Cache/CacheBase.hpp