Castor3D: castor3d::TPushUniform< Type > Class Template Reference
castor3d::TPushUniform< Type > Class Template Reference
Shader variable representation with variable type.
Public Types
using type = TUniform< Type >
using value_type = typename type::value_type
using value_sub_type = typename type::value_sub_type
using param_type = typename type::param_type
using return_type = typename type::return_type
using return_const_type = typename type::return_const_type
using typed_value = typename type::typed_value
Public Member Functions
TPushUniform (ShaderProgram &p_program, uint32_t p_occurences)
Constructor.
virtual ~TPushUniform ()
Destructor.
return_type & getValue ()
Retrieves the value.
return_const_type const & getValue () const
Retrieves the value.
return_type & getValue (uint32_t p_index)
Retrieves the value at given index.
return_const_type const & getValue (uint32_t p_index) const
Retrieves the value at given index.
void setValue (param_type const &p_value)
Defines the value of the variable.
void setValue (param_type const &p_value, uint32_t p_index)
Defines the value of the variable.
void setValues (param_type const *p_values, size_t p_size)
Defines the values of the variable.
template<size_t N>
void setValues (param_type const(&p_values)[N])
Defines the values of the variable.
template<size_t N>
void setValues (std::array< param_type, N > const &p_values)
Defines the values of the variable.
void setValues (std::vector< param_type > const &p_values)
Defines the values of the variable.
return_type & operator[] (uint32_t p_index)
Array subscript operator.
return_const_type const & operator[] (uint32_t p_index) const
Array subscript operator.
type & getUniform ()
type const & getUniform () const
Uniform & getBaseUniform () override
Uniform const & getBaseUniform () const override
Public Member Functions inherited from castor3d::PushUniform
C3D_API PushUniform (ShaderProgram &p_program)
Constructor.
virtual C3D_API ~PushUniform ()
Destructor.
C3D_API bool initialise ()
Initialises the variable.
C3D_API void update ()
Updates this variable's value, in the shader.
ShaderProgram & getProgram ()
ShaderProgram const & getProgram () const
Static Public Attributes
static constexpr auto stride = type::stride
Protected Attributes
type m_uniform
Protected Attributes inherited from castor3d::PushUniform
ShaderProgram & m_program
Detailed Description
template<UniformType Type>
class castor3d::TPushUniform< Type >
Shader variable representation with variable type.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
14/08/2010
Member Typedef Documentation
param_type
template<UniformType Type> using castor3d::TPushUniform< Type >::param_type = typename type::param_type
return_const_type
template<UniformType Type> using castor3d::TPushUniform< Type >::return_const_type = typename type::return_const_type
return_type
template<UniformType Type> using castor3d::TPushUniform< Type >::return_type = typename type::return_type
type
template<UniformType Type> using castor3d::TPushUniform< Type >::type = TUniform< Type >
typed_value
template<UniformType Type> using castor3d::TPushUniform< Type >::typed_value = typename type::typed_value
value_sub_type
template<UniformType Type> using castor3d::TPushUniform< Type >::value_sub_type = typename type::value_sub_type
value_type
template<UniformType Type> using castor3d::TPushUniform< Type >::value_type = typename type::value_type
Constructor & Destructor Documentation
TPushUniform()
template<UniformType Type> castor3d::TPushUniform< Type >::TPushUniform (ShaderProgram & p_program, uint32_t p_occurences)
Constructor.
Parameters
[in] p_program The program.
[in] p_occurences The array dimensions.
~TPushUniform()
template<UniformType Type> virtual castor3d::TPushUniform< Type >::~TPushUniform () virtual
Destructor.
Member Function Documentation
getBaseUniform() [1/2]
template<UniformType Type> Uniform& castor3d::TPushUniform< Type >::getBaseUniform () inline override virtual
Returns
The uniform variable.
Implements castor3d::PushUniform.
References castor3d::TPushUniform< Type >::m_uniform.
getBaseUniform() [2/2]
template<UniformType Type> Uniform const& castor3d::TPushUniform< Type >::getBaseUniform () const inline override virtual
Returns
The uniform variable.
Implements castor3d::PushUniform.
References castor3d::TPushUniform< Type >::m_uniform.
getUniform() [1/2]
template<UniformType Type> type& castor3d::TPushUniform< Type >::getUniform () inline
Returns
The parent program.
References castor3d::TPushUniform< Type >::m_uniform.
getUniform() [2/2]
template<UniformType Type> type const& castor3d::TPushUniform< Type >::getUniform () const inline
Returns
The parent program.
References castor3d::TPushUniform< Type >::m_uniform.
getValue() [1/4]
template<UniformType Type> return_type& castor3d::TPushUniform< Type >::getValue () inline
Retrieves the value.
Returns
A reference to the value
getValue() [2/4]
template<UniformType Type> return_const_type const& castor3d::TPushUniform< Type >::getValue () const inline
Retrieves the value.
Returns
A constant reference to the value
getValue() [3/4]
template<UniformType Type> return_type& castor3d::TPushUniform< Type >::getValue (uint32_t p_index) inline
Retrieves the value at given index.
Remarks
Check the index bounds
Parameters
[in] p_index The index
Returns
A reference to the value at given index
getValue() [4/4]
template<UniformType Type> return_const_type const& castor3d::TPushUniform< Type >::getValue (uint32_t p_index) const inline
Retrieves the value at given index.
Remarks
Check the index bounds
Parameters
[in] p_index The index
Returns
A constant reference to the value at given index
operator[]() [1/2]
template<UniformType Type> return_type& castor3d::TPushUniform< Type >::operator[] (uint32_t p_index) inline
Array subscript operator.
Remarks
doesn't check the index bounds
Parameters
[in] p_index The index
Returns
A reference to the value at given index
operator[]() [2/2]
template<UniformType Type> return_const_type const& castor3d::TPushUniform< Type >::operator[] (uint32_t p_index) const inline
Array subscript operator.
Remarks
doesn't check the index bounds
Parameters
[in] p_index The index
Returns
A constant reference to the value at given index
setValue() [1/2]
template<UniformType Type> void castor3d::TPushUniform< Type >::setValue (param_type const & p_value) inline
Defines the value of the variable.
Parameters
[in] p_value The new value
Referenced by castor3d::doBindPass(), castor3d::doFillShaderPbrMaps(), and castor3d::doFillShaderShadowMaps().
setValue() [2/2]
template<UniformType Type> void castor3d::TPushUniform< Type >::setValue (param_type const & p_value, uint32_t p_index) inline
Defines the value of the variable.
Parameters
[in] p_value The new value
[in] p_index The index of the value
setValues() [1/4]
template<UniformType Type> void castor3d::TPushUniform< Type >::setValues (param_type const * p_values, size_t p_size) inline
Defines the values of the variable.
Parameters
[in] p_values The values buffer.
[in] p_size The values count.
setValues() [2/4]
template<UniformType Type> template<size_t N> void castor3d::TPushUniform< Type >::setValues (param_type const(&) p_values[N]) inline
Defines the values of the variable.
Parameters
[in] p_values The values buffer.
setValues() [3/4]
template<UniformType Type> template<size_t N> void castor3d::TPushUniform< Type >::setValues (std::array< param_type, N > const & p_values) inline
Defines the values of the variable.
Parameters
[in] p_values The values buffer.
setValues() [4/4]
template<UniformType Type> void castor3d::TPushUniform< Type >::setValues (std::vector< param_type > const & p_values) inline
Defines the values of the variable.
Parameters
[in] p_values The values buffer.
Member Data Documentation
m_uniform
template<UniformType Type> type castor3d::TPushUniform< Type >::m_uniform protected
The parent shader program.
Referenced by castor3d::TPushUniform< Type >::getBaseUniform(), and castor3d::TPushUniform< Type >::getUniform().
stride
template<UniformType Type> constexpr auto castor3d::TPushUniform< Type >::stride = type::stride static
The documentation for this class was generated from the following files:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Prerequisites/Castor3DPrerequisites_Shader.hpp
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Shader/Uniform/PushUniform.hpp