Castor3D: Castor3D::OneFrameVariable< T > Class Template Reference
Castor3D::OneFrameVariable< T > Class Template Reference
Single shader variable with variable type.
Public Member Functions
OneFrameVariable (ShaderProgramBase *p_pProgram)
Constructor.
OneFrameVariable (ShaderProgramBase *p_pProgram, uint32_t p_uiOcc)
Constructor.
OneFrameVariable (OneFrameVariable< T > const &p_object)
Copy constructor.
OneFrameVariable (OneFrameVariable< T > &&p_object)
Move constructor.
OneFrameVariable & operator= (OneFrameVariable< T > const &p_object)
Copy assignment operator.
OneFrameVariable & operator= (OneFrameVariable< T > &&p_object)
Move assignment operator.
virtual ~OneFrameVariable ()
Destructor.
T & operator [] (uint32_t p_uiIndex)
Array subscript operator.
T const & operator [] (uint32_t p_uiIndex) const
Array subscript operator.
T & GetValue () throw (std::out_of_range)
Retrieves the value.
T const & GetValue () const throw (std::out_of_range)
Retrieves the value.
T & GetValue (uint32_t p_uiIndex) throw (std::out_of_range)
Retrieves the value at given index.
T const & GetValue (uint32_t p_uiIndex) const throw (std::out_of_range)
Retrieves the value at given index.
eVARIABLE_TYPE GetType () const
Retrieves the variable type.
eFRAME_VARIABLE_TYPE GetFullType () const
Retrieves the variable full type.
void SetValue (T const &p_tValue)
Defines the value of the variable.
void SetValue (T const &p_tValue, uint32_t p_uiIndex)
Defines the value of the variable.
virtual uint32_t size () const
Retrieves the byte size of the variable.
Public Member Functions inherited from Castor3D::TFrameVariable< T >
TFrameVariable (ShaderProgramBase *p_pProgram)
Constructor.
TFrameVariable (ShaderProgramBase *p_pProgram, uint32_t p_uiOcc)
Constructor.
TFrameVariable (TFrameVariable< T > const &p_object)
Copy constructor.
TFrameVariable (TFrameVariable< T > &&p_object)
Move constructor.
TFrameVariable & operator= (TFrameVariable< T > const &p_object)
Copy assignment operator.
TFrameVariable & operator= (TFrameVariable< T > &&p_object)
Move assignment operator.
virtual ~TFrameVariable ()
Destructor.
Castor::String GetDataType () const
Gives the variable data type.
virtual uint8_t const *const const_ptr () const
Retrieves a pointer to the variable data.
virtual void link (uint8_t *p_pBuffer)
Defines the buffer holding the frame variable.
Public Member Functions inherited from Castor3D::FrameVariable
FrameVariable (ShaderProgramBase *p_pProgram)
Constructor.
FrameVariable (ShaderProgramBase *p_pProgram, uint32_t p_uiOcc)
Constructor.
FrameVariable (FrameVariable const &p_object)
Copy constructor.
FrameVariable (FrameVariable &&p_object)
Move constructor.
FrameVariable & operator= (FrameVariable const &p_object)
Copy assignment operator.
FrameVariable & operator= (FrameVariable &&p_object)
Move assignment operator.
virtual ~FrameVariable ()
Destructor.
virtual bool Initialise ()=0
Initialises the variable.
virtual void Cleanup ()=0
Cleans up the variable.
virtual void Apply ()=0
Applies this variable.
virtual void Bind ()=0
Binds this variable to it's program or object, depending of implementation (Glsl, Hlsl or Cg)
virtual void SetValueStr (Castor::String const &p_strValue)
Defines the value of the variable, from a string.
virtual void SetValueStr (Castor::String const &p_strValue, uint32_t p_uiIndex)
Defines the value of the variable, from a string.
virtual void SetName (Castor::String const &p_strName)
Defines the name of the variable, as it appears in the shader program.
Castor::String GetName () const
Gives the name of the variable, as it appears in the shader program.
Castor::String GetStrValue () const
Retrieves the variable string value.
Castor::String GetStrValue (uint32_t p_uiIndex) const
Retrieves the variable string value at given index.
const uint32_t & GetOccCount () const
Retrieves the occurences count.
ShaderProgramBase * GetProgram () const
Retrieves the parent program.
Static Public Member Functions
static eVARIABLE_TYPE GetVariableType ()
Gives the full type of the variable.
static eFRAME_VARIABLE_TYPE GetFrameVariableType ()
Gives the variable full type.
Static Public Member Functions inherited from Castor3D::TFrameVariable< T >
static Castor::String StGetDataType ()
Gives the variable data type.
Protected Types
typedef Castor::Policy< T > policy
Protected Types inherited from Castor3D::TFrameVariable< T >
typedef Castor::Policy< T > policy
Additional Inherited Members
Static Public Attributes inherited from Castor3D::FrameVariable
static const Castor::String Names []
The names of the frame variable types.
Protected Member Functions inherited from Castor3D::TFrameVariable< T >
void DoCleanupBuffer ()
Protected Attributes inherited from Castor3D::TFrameVariable< T >
bool m_bOwnBuffer
Tells the variable owns it's buffer.
T * m_pValues
The buffer containing all values.
Protected Attributes inherited from Castor3D::FrameVariable
Castor::String m_strName
The variable name as it appears in the shader program.
bool m_bChanged
Tells if the variable has changed since last execution of the shader.
uint32_t m_uiOcc
The array dimension if the variable represents an array.
Castor::StringArray m_strValue
The value of the variable.
ShaderProgramBase * m_pProgram
The parent shader program.
Detailed Description
template<typename T>
class Castor3D::OneFrameVariable< T >
Single shader variable with variable type.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
14/08/2010
Member Typedef Documentation
policy
template<typename T > typedef Castor::Policy<T> Castor3D::OneFrameVariable< T >::policy protected
Constructor & Destructor Documentation
OneFrameVariable() [1/4]
template<typename T > Castor3D::OneFrameVariable< T >::OneFrameVariable (ShaderProgramBase * p_pProgram)
Constructor.
OneFrameVariable() [2/4]
template<typename T > Castor3D::OneFrameVariable< T >::OneFrameVariable (ShaderProgramBase * p_pProgram, uint32_t p_uiOcc)
Constructor.
Parameters
[in] p_uiOcc The array dimension
OneFrameVariable() [3/4]
template<typename T > Castor3D::OneFrameVariable< T >::OneFrameVariable (OneFrameVariable< T > const & p_object)
Copy constructor.
Parameters
[in] p_object The object to copy
OneFrameVariable() [4/4]
template<typename T > Castor3D::OneFrameVariable< T >::OneFrameVariable (OneFrameVariable< T > && p_object)
Move constructor.
Parameters
[in] p_object The object to move
~OneFrameVariable()
template<typename T > virtual Castor3D::OneFrameVariable< T >::~OneFrameVariable () virtual
Destructor.
Member Function Documentation
GetFrameVariableType()
template<typename T > static eFRAME_VARIABLE_TYPE Castor3D::OneFrameVariable< T >::GetFrameVariableType () inline static
Gives the variable full type.
Returns
The type
Donne le type complet de la variable
Returns
Le type
Referenced by Castor3D::OneFrameVariable< T >::GetFullType().
GetFullType()
template<typename T > eFRAME_VARIABLE_TYPE Castor3D::OneFrameVariable< T >::GetFullType () const inline virtual
Retrieves the variable full type.
Returns
The type
Implements Castor3D::FrameVariable.
References Castor3D::OneFrameVariable< T >::GetFrameVariableType().
GetType()
template<typename T > eVARIABLE_TYPE Castor3D::OneFrameVariable< T >::GetType () const inline virtual
Retrieves the variable type.
Returns
The variable type
Implements Castor3D::FrameVariable.
References Castor3D::OneFrameVariable< T >::GetVariableType().
GetValue() [1/4]
template<typename T > T& Castor3D::OneFrameVariable< T >::GetValue () throw (std::out_of_range) inline
Retrieves the value.
Returns
A reference to the value
GetValue() [2/4]
template<typename T > T const& Castor3D::OneFrameVariable< T >::GetValue () const throw (std::out_of_range) inline
Retrieves the value.
Returns
A constant reference to the value
GetValue() [3/4]
template<typename T > T& Castor3D::OneFrameVariable< T >::GetValue (uint32_t p_uiIndex) throw (std::out_of_range) inline
Retrieves the value at given index.
Remarks
Check the index bounds
Parameters
[in] p_uiIndex The index
Returns
A reference to the value at given index
GetValue() [4/4]
template<typename T > T const& Castor3D::OneFrameVariable< T >::GetValue (uint32_t p_uiIndex) const throw (std::out_of_range) inline
Retrieves the value at given index.
Remarks
Check the index bounds
Parameters
[in] p_uiIndex The index
Returns
A constant reference to the value at given index
GetVariableType()
template<typename T > static eVARIABLE_TYPE Castor3D::OneFrameVariable< T >::GetVariableType () inline static
Gives the full type of the variable.
Returns
The type of the variable
Referenced by Castor3D::OneFrameVariable< T >::GetType().
operator []() [1/2]
template<typename T > T& Castor3D::OneFrameVariable< T >::operator [] (uint32_t p_uiIndex) inline
Array subscript operator.
Remarks
Doesn't check the index bounds
Parameters
[in] p_uiIndex The index
Returns
A reference to the value at given index
References Castor3D::TFrameVariable< T >::m_pValues.
operator []() [2/2]
template<typename T > T const& Castor3D::OneFrameVariable< T >::operator [] (uint32_t p_uiIndex) const inline
Array subscript operator.
Remarks
Doesn't check the index bounds
Parameters
[in] p_uiIndex The index
Returns
A constant reference to the value at given index
References Castor3D::TFrameVariable< T >::m_pValues.
operator=() [1/2]
template<typename T > OneFrameVariable& Castor3D::OneFrameVariable< T >::operator= (OneFrameVariable< T > const & p_object)
Copy assignment operator.
Parameters
[in] p_object The object to copy
Returns
A reference to this object
operator=() [2/2]
template<typename T > OneFrameVariable& Castor3D::OneFrameVariable< T >::operator= (OneFrameVariable< T > && p_object)
Move assignment operator.
Parameters
[in] p_object The object to move
Returns
A reference to this object
SetValue() [1/2]
template<typename T > void Castor3D::OneFrameVariable< T >::SetValue (T const & p_tValue) inline
Defines the value of the variable.
Parameters
[in] p_tValue The new value
SetValue() [2/2]
template<typename T > void Castor3D::OneFrameVariable< T >::SetValue (T const & p_tValue, uint32_t p_uiIndex) inline
Defines the value of the variable.
Parameters
[in] p_tValue The new value
[in] p_uiIndex The index of the value
size()
template<typename T > virtual uint32_t Castor3D::OneFrameVariable< T >::size () const virtual
Retrieves the byte size of the variable.
Returns
The size
Implements Castor3D::FrameVariable.
The documentation for this class was generated from the following files:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Castor3DPrerequisites.hpp
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/OneFrameVariable.hpp