Castor3D: castor3d::IblTextures Class Reference
castor3d::IblTextures Class Reference
Holds environment maps used in IBL.
Public Member Functions
C3D_API IblTextures (Scene &scene)
Constructor.
virtual C3D_API ~IblTextures ()
Destructor.
C3D_API void update (TextureLayout const &source)
Updates the environment maps.
C3D_API void debugDisplay (castor::Size const &size) const
Displays the maps.
TextureUnit const & getIrradiance () const
TextureUnit const & getPrefilteredEnvironment () const
TextureUnit const & getPrefilteredBrdf () const
Detailed Description
Holds environment maps used in IBL.
Author
Sylvain DOREMUS
Version
0.9.0
Date
21/05/2016
Constructor & Destructor Documentation
IblTextures()
C3D_API castor3d::IblTextures::IblTextures (Scene & scene) explicit
Constructor.
Parameters
[in] scene The scene.
~IblTextures()
virtual C3D_API castor3d::IblTextures::~IblTextures () virtual
Destructor.
Member Function Documentation
debugDisplay()
C3D_API void castor3d::IblTextures::debugDisplay (castor::Size const & size) const
Displays the maps.
Parameters
[in] size The render size.
getIrradiance()
TextureUnit const& castor3d::IblTextures::getIrradiance () const inline
Returns
The irradiance texture.
Referenced by castor3d::doFillShaderPbrMaps().
getPrefilteredBrdf()
TextureUnit const& castor3d::IblTextures::getPrefilteredBrdf () const inline
Returns
The prefiltered BRDF texture.
Referenced by castor3d::doFillShaderPbrMaps().
getPrefilteredEnvironment()
TextureUnit const& castor3d::IblTextures::getPrefilteredEnvironment () const inline
Returns
The prefiltered environment texture.
Referenced by castor3d::doFillShaderPbrMaps().
update()
C3D_API void castor3d::IblTextures::update (TextureLayout const & source)
Updates the environment maps.
Parameters
[in] source The source environment map.
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/PBR/IblTextures.hpp