Castor3D: castor3d::UniformBufferOffsetT< DataT > Struct Template Reference
castor3d::UniformBufferOffsetT< DataT > Struct Template Reference
A UniformBuffer and an offset from the GpuBuffer.
Public Member Functions
void setPool (PoolUniformBuffer &pool)
operator bool () const
DataT const & getData () const
DataT & getData ()
PoolUniformBuffer const & getPool () const
PoolUniformBuffer & getPool ()
ashes::UniformBuffer const & getBuffer () const
ashes::UniformBuffer & getBuffer ()
uint32_t getAlignedSize () const
void createSizedBinding (ashes::DescriptorSet &descriptorSet, VkDescriptorSetLayoutBinding const &layoutBinding) const
ashes::WriteDescriptorSet getDescriptorWrite (uint32_t dstBinding, uint32_t dstArrayElement=0u) const
Public Attributes
VkMemoryPropertyFlags flags { 0u }
uint32_t offset { 0u }
uint32_t range { 0u }
Detailed Description
template<typename DataT>
struct castor3d::UniformBufferOffsetT< DataT >
A UniformBuffer and an offset from the GpuBuffer.
Member Function Documentation
createSizedBinding()
template<typename DataT> void castor3d::UniformBufferOffsetT< DataT >::createSizedBinding (ashes::DescriptorSet & descriptorSet, VkDescriptorSetLayoutBinding const & layoutBinding) const inline
Referenced by castor3d::PickingUbo::createSizedBinding(), castor3d::LayeredLpvGridConfigUbo::createSizedBinding(), castor3d::GpInfoUbo::createSizedBinding(), castor3d::RsmConfigUbo::createSizedBinding(), castor3d::ModelInstancesUbo::createSizedBinding(), castor3d::ShadowMapUbo::createSizedBinding(), castor3d::LpvLightConfigUbo::createSizedBinding(), castor3d::LpvGridConfigUbo::createSizedBinding(), castor3d::ModelMatrixUbo::createSizedBinding(), castor3d::MatrixUbo::createSizedBinding(), castor3d::VoxelizerUbo::createSizedBinding(), castor3d::SceneUbo::createSizedBinding(), and castor3d::SsaoConfigUbo::createSizedBinding().
getAlignedSize()
template<typename DataT> uint32_t castor3d::UniformBufferOffsetT< DataT >::getAlignedSize () const inline
getBuffer() [1/2]
template<typename DataT> ashes::UniformBuffer const& castor3d::UniformBufferOffsetT< DataT >::getBuffer () const inline
getBuffer() [2/2]
template<typename DataT> ashes::UniformBuffer& castor3d::UniformBufferOffsetT< DataT >::getBuffer () inline
getData() [1/2]
template<typename DataT> DataT const& castor3d::UniformBufferOffsetT< DataT >::getData () const inline
getData() [2/2]
template<typename DataT> DataT& castor3d::UniformBufferOffsetT< DataT >::getData () inline
getDescriptorWrite()
template<typename DataT> ashes::WriteDescriptorSet castor3d::UniformBufferOffsetT< DataT >::getDescriptorWrite (uint32_t dstBinding, uint32_t dstArrayElement = 0u) const inline
Referenced by castor3d::RenderQuad::makeDescriptorWrite().
getPool() [1/2]
template<typename DataT> PoolUniformBuffer const& castor3d::UniformBufferOffsetT< DataT >::getPool () const inline
getPool() [2/2]
template<typename DataT> PoolUniformBuffer& castor3d::UniformBufferOffsetT< DataT >::getPool () inline
operator bool()
template<typename DataT> castor3d::UniformBufferOffsetT< DataT >::operator bool () const inline explicit
setPool()
template<typename DataT> void castor3d::UniformBufferOffsetT< DataT >::setPool (PoolUniformBuffer & pool) inline
Member Data Documentation
flags
template<typename DataT> VkMemoryPropertyFlags castor3d::UniformBufferOffsetT< DataT >::flags { 0u }
offset
template<typename DataT> uint32_t castor3d::UniformBufferOffsetT< DataT >::offset { 0u }
Referenced by castor3d::UniformBufferOffsetT< castor3d::SkinningUboConfiguration >::createSizedBinding(), castor3d::UniformBufferOffsetT< castor3d::SkinningUboConfiguration >::getData(), and castor3d::UniformBufferOffsetT< castor3d::SkinningUboConfiguration >::getDescriptorWrite().
range
template<typename DataT> uint32_t castor3d::UniformBufferOffsetT< DataT >::range { 0u }
Referenced by castor3d::UniformBufferOffsetT< castor3d::SkinningUboConfiguration >::createSizedBinding(), and castor3d::UniformBufferOffsetT< castor3d::SkinningUboConfiguration >::getDescriptorWrite().
The documentation for this struct was generated from the following files:
Buffer/BufferModule.hpp
Buffer/UniformBufferOffset.hpp