FIND_PATH(D3D9_ROOT_DIR Include/d3d9.h 
  HINTS
  PATH_SUFFIXES d3d9 Include
  PATHS
)

FIND_PATH(D3D9_INCLUDE_DIR d3d9.h 
  HINTS
  PATH_SUFFIXES Include
  PATHS
  ${D3D9_ROOT_DIR}
)

FIND_PATH(D3D9_LIBRARY_DIR d3d9.lib
  HINTS
  PATH_SUFFIXES lib64 lib Lib/x86
  PATHS
  ${D3D9_ROOT_DIR}
)

FIND_LIBRARY(D3D9_LIBRARY
  NAMES d3d9.lib
  HINTS
  PATH_SUFFIXES lib64 lib
  PATHS
  ${D3D9_LIBRARY_DIR}
)

FIND_LIBRARY(D3D9_X_LIBRARY
  NAMES d3dx9.lib
  HINTS
  PATH_SUFFIXES lib64 lib
  PATHS
  ${D3D9_LIBRARY_DIR}
)