Castor3D: castor3d::ScrollableStyle Class Reference
castor3d::ScrollableStyle Class Reference
#include <StyleScrollable.hpp>
Public Member Functions
void setVerticalStyle (ScrollBarStyle &v)
void setHorizontalStyle (ScrollBarStyle &v)
bool hasVerticalStyle () const noexcept
bool hasHorizontalStyle () const noexcept
ScrollBarStyle & getVerticalStyle () const noexcept
ScrollBarStyle & getHorizontalStyle () const noexcept
Member Function Documentation
getHorizontalStyle()
ScrollBarStyle & castor3d::ScrollableStyle::getHorizontalStyle () const inline noexcept
References hasHorizontalStyle().
getVerticalStyle()
ScrollBarStyle & castor3d::ScrollableStyle::getVerticalStyle () const inline noexcept
References hasVerticalStyle().
hasHorizontalStyle()
bool castor3d::ScrollableStyle::hasHorizontalStyle () const inline noexcept
Referenced by getHorizontalStyle().
hasVerticalStyle()
bool castor3d::ScrollableStyle::hasVerticalStyle () const inline noexcept
Referenced by getVerticalStyle().
setHorizontalStyle()
void castor3d::ScrollableStyle::setHorizontalStyle (ScrollBarStyle & v) inline
setVerticalStyle()
void castor3d::ScrollableStyle::setVerticalStyle (ScrollBarStyle & v) inline
The documentation for this class was generated from the following file:
Gui/Theme/StyleScrollable.hpp