Castor3D: Castor3D::ChunkWriter< T > Class Template Reference
Castor3D::ChunkWriter< T > Class Template Reference
Chunk data writer.
Static Public Member Functions
static bool Write (T const *p_begin, T const *p_end, ChunkType p_type, BinaryChunk &p_chunk)
Writes a subchunk value into a chunk.
static bool Write (T const &p_value, ChunkType p_type, BinaryChunk &p_chunk)
Writes a subchunk value into a chunk.
Static Public Member Functions inherited from Castor3D::ChunkWriterBase
static bool Write (uint8_t const *p_begin, uint8_t const *p_end, ChunkType p_type, BinaryChunk &p_chunk)
Writes a subchunk value into a chunk.
Detailed Description
template<typename T>
class Castor3D::ChunkWriter< T >
Chunk data writer.
Author
Sylvain DOREMUS
Version
0.9.0
Date
30/05/2016
Member Function Documentation
Write() [1/2]
template<typename T > static bool Castor3D::ChunkWriter< T >::Write (T const * p_begin, T const * p_end, ChunkType p_type, BinaryChunk & p_chunk) inline static
Writes a subchunk value into a chunk.
Parameters
[in] p_begin The values begin
[in] p_end The values end
[in] p_type The subchunk type
[in] p_chunk The chunk
Returns
false if any error occured
References Castor3D::PrepareChunkData(), and Castor3D::ChunkWriterBase::Write().
Referenced by Castor3D::BinaryWriterBase< Skeleton >::DoWriteChunk().
Write() [2/2]
template<typename T > static bool Castor3D::ChunkWriter< T >::Write (T const & p_value, ChunkType p_type, BinaryChunk & p_chunk) inline static
Writes a subchunk value into a chunk.
Parameters
[in] p_value The value
[in] p_type The subchunk type
[in] p_chunk The chunk
Returns
false if any error occured
References Castor3D::GetBuffer(), Castor3D::GetDataSize(), Castor3D::PrepareChunkData(), and Castor3D::ChunkWriterBase::Write().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Binary/ChunkWriter.hpp