Castor3D: castor3d::shader::Materials Class Reference
castor3d::shader::Materials Class Reference
#include <GlslMaterial.hpp>
Public Member Functions
C3D_API Materials (sdw::ShaderWriter &writer, PassShaders &passShaders)
C3D_API Materials (sdw::ShaderWriter &writer, PassShaders &passShaders, uint32_t binding, uint32_t set, bool enable=true)
C3D_API Materials (Engine const &engine, sdw::ShaderWriter &writer, PassShaders &passShaders, uint32_t binding, uint32_t set, uint32_t &specifics, bool enable=true)
C3D_API void fill (sdw::Vec3 const &albedo, sdw::Vec4 const &spcRgh, sdw::Vec4 const &colMtl, sdw::Vec4 const &crTsIr, sdw::Vec4 const &sheen, Material &material)
C3D_API void apply (Material const &material, SurfaceBase const &surface, sdw::Vec4 &spcRgh, sdw::Vec4 &colMtl, sdw::Vec4 &sheen)
C3D_API ComponentModeFlags getFilter () const
template<typename TypeT >
bool hasSpecificsBuffer () const
template<typename TypeT >
BufferT< TypeT > const & getSpecificsBuffer () const
sdw::UInt getPassTypesCount () const
Material getMaterial (sdw::UInt const &index) const
auto & getPassShaders () const
C3D_API void blendMaterials (PipelineFlags const &flags, shader::TextureConfigurations const &textureConfigs, shader::TextureAnimations const &textureAnims, sdw::Array< sdw::CombinedImage2DRgba32 > const &maps, Material &material, sdw::UInt const &materialId, sdw::Array< sdw::Vec4 > const &passMultipliers, BlendComponents &output) const
C3D_API void blendMaterials (VkCompareOp alphaFunc, PipelineFlags const &flags, shader::TextureConfigurations const &textureConfigs, shader::TextureAnimations const &textureAnims, sdw::Array< sdw::CombinedImage2DRgba32 > const &maps, Material &material, sdw::UInt const &materialId, sdw::Array< sdw::Vec4 > const &passMultipliers, BlendComponents &output) const
C3D_API void blendMaterials (bool opaque, PipelineFlags const &flags, shader::TextureConfigurations const &textureConfigs, shader::TextureAnimations const &textureAnims, sdw::Array< sdw::CombinedImage2DRgba32 > const &maps, Material &material, sdw::UInt const &materialId, sdw::Array< sdw::Vec4 > const &passMultipliers, BlendComponents &output) const
C3D_API void applyMaterial (PipelineFlags const &flags, TextureConfigurations const &textureConfigs, TextureAnimations const &textureAnims, sdw::Array< sdw::CombinedImage2DRgba32 > const &maps, Material const &material, BlendComponents &components) const
Public Member Functions inherited from castor3d::shader::BufferT< Material >
BufferT (sdw::ShaderWriter &writer, std::string blockName, std::string variableName, uint32_t binding, uint32_t set, bool enabled=true, ParamsT &&... params)
Material getData (sdw::UInt const &index, ParamsT &&... params) const
Public Member Functions inherited from castor3d::shader::BufferBase
BufferBase (sdw::ShaderWriter &writer, std::string blockName, std::string variableName, uint32_t binding, uint32_t set, bool enabled=true)
sdw::UInt getCount () const
sdw::UInt getSecondaryCount () const
bool isEnabled () const noexcept
sdw::ShaderWriter * getWriter () const noexcept
Additional Inherited Members
Protected Attributes inherited from castor3d::shader::BufferBase
sdw::ShaderWriter & m_writer
std::unique_ptr< sdw::StorageBuffer > m_ssbo
std::string m_variableName
Constructor & Destructor Documentation
Materials() [1/3]
C3D_API castor3d::shader::Materials::Materials (sdw::ShaderWriter & writer, PassShaders & passShaders)
Materials() [2/3]
C3D_API castor3d::shader::Materials::Materials (sdw::ShaderWriter & writer, PassShaders & passShaders, uint32_t binding, uint32_t set, bool enable = true)
Materials() [3/3]
C3D_API castor3d::shader::Materials::Materials (Engine const & engine, sdw::ShaderWriter & writer, PassShaders & passShaders, uint32_t binding, uint32_t set, uint32_t & specifics, bool enable = true)
Member Function Documentation
apply()
C3D_API void castor3d::shader::Materials::apply (Material const & material, SurfaceBase const & surface, sdw::Vec4 & spcRgh, sdw::Vec4 & colMtl, sdw::Vec4 & sheen)
applyMaterial()
C3D_API void castor3d::shader::Materials::applyMaterial (PipelineFlags const & flags, TextureConfigurations const & textureConfigs, TextureAnimations const & textureAnims, sdw::Array< sdw::CombinedImage2DRgba32 > const & maps, Material const & material, BlendComponents & components) const
blendMaterials() [1/3]
C3D_API void castor3d::shader::Materials::blendMaterials (bool opaque, PipelineFlags const & flags, shader::TextureConfigurations const & textureConfigs, shader::TextureAnimations const & textureAnims, sdw::Array< sdw::CombinedImage2DRgba32 > const & maps, Material & material, sdw::UInt const & materialId, sdw::Array< sdw::Vec4 > const & passMultipliers, BlendComponents & output) const
blendMaterials() [2/3]
C3D_API void castor3d::shader::Materials::blendMaterials (PipelineFlags const & flags, shader::TextureConfigurations const & textureConfigs, shader::TextureAnimations const & textureAnims, sdw::Array< sdw::CombinedImage2DRgba32 > const & maps, Material & material, sdw::UInt const & materialId, sdw::Array< sdw::Vec4 > const & passMultipliers, BlendComponents & output) const
blendMaterials() [3/3]
C3D_API void castor3d::shader::Materials::blendMaterials (VkCompareOp alphaFunc, PipelineFlags const & flags, shader::TextureConfigurations const & textureConfigs, shader::TextureAnimations const & textureAnims, sdw::Array< sdw::CombinedImage2DRgba32 > const & maps, Material & material, sdw::UInt const & materialId, sdw::Array< sdw::Vec4 > const & passMultipliers, BlendComponents & output) const
fill()
C3D_API void castor3d::shader::Materials::fill (sdw::Vec3 const & albedo, sdw::Vec4 const & spcRgh, sdw::Vec4 const & colMtl, sdw::Vec4 const & crTsIr, sdw::Vec4 const & sheen, Material & material)
getFilter()
C3D_API ComponentModeFlags castor3d::shader::Materials::getFilter () const
getMaterial()
Material castor3d::shader::Materials::getMaterial (sdw::UInt const & index) const inline
References castor3d::shader::BufferT< Material >::getData().
getPassShaders()
auto & castor3d::shader::Materials::getPassShaders () const inline
getPassTypesCount()
sdw::UInt castor3d::shader::Materials::getPassTypesCount () const inline
References castor3d::shader::BufferBase::getSecondaryCount().
getSpecificsBuffer()
template<typename TypeT > BufferT< TypeT > const & castor3d::shader::Materials::getSpecificsBuffer () const inline
References castor3d::getName().
hasSpecificsBuffer()
template<typename TypeT > bool castor3d::shader::Materials::hasSpecificsBuffer () const inline
References castor3d::getName().
The documentation for this class was generated from the following file:
Shader/Shaders/GlslMaterial.hpp