Castor3D: Castor3D::ChunkParserBase Class Reference
Castor3D::ChunkParserBase Class Reference
Chunk parser.
Static Public Member Functions
static bool Parse (uint8_t *p_values, size_t p_size, BinaryChunk &p_chunk)
Retrieves a value array from a chunk.
Detailed Description
Chunk parser.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
08/04/2014
Member Function Documentation
Parse()
static bool Castor3D::ChunkParserBase::Parse (uint8_t * p_values, size_t p_size, BinaryChunk & p_chunk) inline static
Retrieves a value array from a chunk.
Parameters
[out] p_values Receives the parsed values
[out] p_size The values size
[in] p_chunk The chunk containing the values
Returns
false if any error occured
References Castor3D::BinaryChunk::CheckAvailable(), and Castor3D::BinaryChunk::Get().
Referenced by Castor3D::ChunkParser< T >::Parse(), Castor3D::ChunkParser< Castor::String >::Parse(), and Castor3D::ChunkParser< Castor::Path >::Parse().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Binary/ChunkParser.hpp