Castor3D: castor3d::shader::SpotLight Struct Reference
castor3d::shader::SpotLight Struct Reference
#include <GlslLight.hpp>
Public Member Functions
C3D_API SpotLight (sdw::ShaderWriter &writer, ast::expr::ExprPtr expr, bool enabled)
C3D_API sdw::Float getAttenuationFactor (sdw::Float const &distance) const
auto base () const
auto position () const
auto exponent () const
auto attenuation () const
auto innerCutOff () const
auto direction () const
auto outerCutOff () const
auto transform () const
auto shadows () const
auto cutOffsDiff () const
Constructor & Destructor Documentation
SpotLight()
C3D_API castor3d::shader::SpotLight::SpotLight (sdw::ShaderWriter & writer, ast::expr::ExprPtr expr, bool enabled) inline
Member Function Documentation
attenuation()
auto castor3d::shader::SpotLight::attenuation () const inline
base()
auto castor3d::shader::SpotLight::base () const inline
Referenced by shadows().
cutOffsDiff()
auto castor3d::shader::SpotLight::cutOffsDiff () const inline
References innerCutOff(), and outerCutOff().
direction()
auto castor3d::shader::SpotLight::direction () const inline
exponent()
auto castor3d::shader::SpotLight::exponent () const inline
getAttenuationFactor()
C3D_API sdw::Float castor3d::shader::SpotLight::getAttenuationFactor (sdw::Float const & distance) const
innerCutOff()
auto castor3d::shader::SpotLight::innerCutOff () const inline
Referenced by cutOffsDiff().
outerCutOff()
auto castor3d::shader::SpotLight::outerCutOff () const inline
Referenced by cutOffsDiff().
position()
auto castor3d::shader::SpotLight::position () const inline
shadows()
auto castor3d::shader::SpotLight::shadows () const inline
References base().
transform()
auto castor3d::shader::SpotLight::transform () const inline
The documentation for this struct was generated from the following file:
Shader/Shaders/GlslLight.hpp