#include "GuiCommon/Properties/Math/PointProperties.hpp"

#include <wx/propgrid/propgrid.h>
#include <wx/propgrid/advprops.h>

GC_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( castor, Point2b )
GC_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( castor, Point3b )
GC_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( castor, Point4b )
GC_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( castor, Point2i )
GC_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( castor, Point3i )
GC_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( castor, Point4i )
GC_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( castor, Point2ui )
GC_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( castor, Point3ui )
GC_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( castor, Point4ui )
GC_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( castor, Point2f )
GC_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( castor, Point3f )
GC_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( castor, Point4f )
GC_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( castor, Point2d )
GC_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( castor, Point3d )
GC_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( castor, Point4d )
