#include "GuiCommon/Properties/Math/PointProperties.hpp"

#include <wx/propgrid/propgrid.h>
#include <wx/propgrid/advprops.h>

using namespace castor;

WX_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( Point2b )
WX_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( Point3b )
WX_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( Point4b )
WX_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( Point2i )
WX_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( Point3i )
WX_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( Point4i )
WX_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( Point2ui )
WX_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( Point3ui )
WX_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( Point4ui )
WX_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( Point2f )
WX_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( Point3f )
WX_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( Point4f )
WX_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( Point2d )
WX_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( Point3d )
WX_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( Point4d )
