#include "GuiCommon/Properties/Math/PointProperties.hpp"

#include <wx/propgrid/propgrid.h>
#include <wx/propgrid/advprops.h>

GC_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( c3d, Point2b )
GC_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( c3d, Point3b )
GC_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( c3d, Point4b )
GC_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( c3d, Point2i )
GC_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( c3d, Point3i )
GC_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( c3d, Point4i )
GC_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( c3d, Point2ui )
GC_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( c3d, Point3ui )
GC_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( c3d, Point4ui )
GC_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( c3d, Point2f )
GC_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( c3d, Point3f )
GC_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( c3d, Point4f )
GC_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( c3d, Point2d )
GC_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( c3d, Point3d )
GC_PG_IMPLEMENT_VARIANT_DATA_DUMMY_EQ( c3d, Point4d )
