Castor3D: castor3d::SpecularComponent Struct Reference
castor3d::SpecularComponent Struct Reference
#include <SpecularComponent.hpp>
Classes
struct ComponentsShader
struct MaterialShader
class Plugin
Public Member Functions
C3D_API SpecularComponent (Pass &pass, castor::RgbColour defaultValue=Default)
C3D_API void accept (PassVisitorBase &vis) override
PassVisitor acceptance function.
bool isValueSet () const
castor::RgbColour const & getSpecular () const
void setSpecular (castor::RgbColour const &v)
void setSpecular (castor::HdrRgbColour const &v, float gamma)
void setSpecular (castor::Coords3f const &v)
void setSpecular (castor::Point3f const &v)
Public Member Functions inherited from castor3d::BaseDataPassComponentT< castor::AtomicGroupChangeTracked< castor::AtomicChangeTracked< castor::RgbColour > > >
BaseDataPassComponentT (Pass &pass, castor::String const &type, ParamsT &&... params)
Constructor.
void setData (DataU const &data)
void setData (ParamsT &&... params)
castor::AtomicGroupChangeTracked< castor::AtomicChangeTracked< castor::RgbColour > > & getData ()
castor::AtomicGroupChangeTracked< castor::AtomicChangeTracked< castor::RgbColour > > const & getData () const
Public Member Functions inherited from castor3d::PassComponent
C3D_API PassComponent (Pass &pass, castor::String const &type)
Constructor.
virtual C3D_API ~PassComponent () noexcept=default
C3D_API PassComponentUPtr clone (Pass &pass) const
C3D_API bool writeText (castor::String const &tabs, castor::Path const &folder, castor::String const &subfolder, castor::StringStream &file) const
Writes the component content to text.
C3D_API void fillBuffer (PassBuffer &buffer) const
Fills the pass buffer with this pass data.
virtual C3D_API void update ()
C3D_API void fillChannel (TextureConfiguration &configuration, uint32_t mask)
Fills the texture configuration for use with this component.
virtual C3D_API void fillConfig (TextureConfiguration &config, PassVisitorBase &vis) const
PassVisitor acceptance function, for a specific texture configuration.
virtual C3D_API bool hasColour () const
virtual C3D_API castor::HdrRgbColour const & getColour () const
virtual C3D_API void setColour (castor::HdrRgbColour v)
virtual C3D_API PassComponentFlag getPassFlags () const
castor::String const & getType () const
PassComponentPlugin const & getPlugin () const
PassComponentID getId () const
void setColour (castor::RgbColour const &v, float gamma=2.2f)
void setColour (castor::Coords3f const &v)
void setColour (castor::Point3f const &v)
Static Public Member Functions
static PassComponentPluginUPtr createPlugin (PassComponentRegister const &passComponent)
Static Public Attributes
static C3D_API castor::String const TypeName
static float constexpr DefaultComponent = 0.0f
static float constexpr DefaultPhongComponent = 1.0f
static float constexpr DefaultPbrComponent = 0.04f
static C3D_API castor::RgbColour const Default
static C3D_API castor::RgbColour const DefaultPhong
static C3D_API castor::RgbColour const DefaultPbr
Additional Inherited Members
Protected Attributes inherited from castor3d::BaseDataPassComponentT< castor::AtomicGroupChangeTracked< castor::AtomicChangeTracked< castor::RgbColour > > >
castor::AtomicGroupChangeTracked< castor::AtomicChangeTracked< castor::RgbColour > > m_value
Protected Attributes inherited from castor3d::PassComponent
castor::String m_type
PassComponentID m_id
PassComponentPlugin const & m_plugin
std::atomic_bool & m_dirty
shader::PassMaterialShader * m_materialShader {}
Constructor & Destructor Documentation
SpecularComponent()
C3D_API castor3d::SpecularComponent::SpecularComponent (Pass & pass, castor::RgbColour defaultValue = Default) explicit
Member Function Documentation
accept()
C3D_API void castor3d::SpecularComponent::accept (PassVisitorBase & vis) override virtual
PassVisitor acceptance function.
Parameters
vis The ... visitor.
Reimplemented from castor3d::PassComponent.
createPlugin()
static PassComponentPluginUPtr castor3d::SpecularComponent::createPlugin (PassComponentRegister const & passComponent) inline static
getSpecular()
castor::RgbColour const & castor3d::SpecularComponent::getSpecular () const inline
References castor3d::BaseDataPassComponentT< castor::AtomicGroupChangeTracked< castor::AtomicChangeTracked< castor::RgbColour > > >::getData().
isValueSet()
bool castor3d::SpecularComponent::isValueSet () const inline
References castor3d::BaseDataPassComponentT< castor::AtomicGroupChangeTracked< castor::AtomicChangeTracked< castor::RgbColour > > >::m_value.
setSpecular() [1/4]
void castor3d::SpecularComponent::setSpecular (castor::Coords3f const & v) inline
References setSpecular().
setSpecular() [2/4]
void castor3d::SpecularComponent::setSpecular (castor::HdrRgbColour const & v, float gamma) inline
References setSpecular().
setSpecular() [3/4]
void castor3d::SpecularComponent::setSpecular (castor::Point3f const & v) inline
References setSpecular().
setSpecular() [4/4]
void castor3d::SpecularComponent::setSpecular (castor::RgbColour const & v) inline
References castor3d::BaseDataPassComponentT< castor::AtomicGroupChangeTracked< castor::AtomicChangeTracked< castor::RgbColour > > >::setData().
Referenced by setSpecular().
Member Data Documentation
Default
C3D_API castor::RgbColour const castor3d::SpecularComponent::Default static
DefaultComponent
float constexpr castor3d::SpecularComponent::DefaultComponent = 0.0f static constexpr
DefaultPbr
C3D_API castor::RgbColour const castor3d::SpecularComponent::DefaultPbr static
DefaultPbrComponent
float constexpr castor3d::SpecularComponent::DefaultPbrComponent = 0.04f static constexpr
DefaultPhong
C3D_API castor::RgbColour const castor3d::SpecularComponent::DefaultPhong static
DefaultPhongComponent
float constexpr castor3d::SpecularComponent::DefaultPhongComponent = 1.0f static constexpr
TypeName
C3D_API castor::String const castor3d::SpecularComponent::TypeName static
The documentation for this struct was generated from the following file:
Material/Pass/Component/Lighting/SpecularComponent.hpp