Castor3D: castor3d::PipelineFlags Struct Reference
castor3d::PipelineFlags Struct Reference
Pipeline flags.
#include <PipelineFlags.hpp>
Public Member Functions
PipelineFlags (PipelineHiHashDetails hiDetails, PipelineLoHashDetails loDetails=PipelineLoHashDetails{}, SceneFlags sceneFlags=SceneFlag::eNone, BlendMode colourBlendMode=BlendMode::eNoBlend, BlendMode alphaBlendMode=BlendMode::eNoBlend, RenderPassTypeID renderPassType=0u, VkPrimitiveTopology ptopology=VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST, uint32_t ppatchVertices=3u)
PipelineFlags (PassComponentCombine pcomponents, LightingModelID plightingModelId, BackgroundModelID pbackgroundModelId, BlendMode pcolourBlendMode=BlendMode::eNoBlend, BlendMode palphaBlendMode=BlendMode::eNoBlend, RenderPassTypeID prenderPassType=0u, SubmeshFlags psubmeshFlags=SubmeshFlag::eIndex, ProgramFlags pprogramFlags=ProgramFlag::eNone, SceneFlags psceneFlags=SceneFlag::eNone, ShaderFlags pshaderFlags=ShaderFlag::eNone, VkPrimitiveTopology ptopology=VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST, uint32_t ppatchVertices=3u, VkCompareOp palphaFunc=VK_COMPARE_OP_ALWAYS, TextureCombine textures={}, uint32_t ppassLayerIndex={}, VkDeviceSize pmorphTargetsOffset={}, bool pisStatic=false)
PipelineFlags (PassComponentCombine pcomponents, LightingModelID lightingModelId, BackgroundModelID pbackgroundModelId, SubmeshFlags submeshFlags, ProgramFlags programFlags, TextureCombine textures, ShaderFlags shaderFlags, VkCompareOp alphaFunc, uint32_t passLayerIndex=0u)
C3D_API bool enableTexcoords () const
C3D_API bool enableVertexInput (SubmeshFlag data) const
C3D_API bool enableIndices () const
C3D_API bool enablePosition () const
C3D_API bool enableNormal () const
C3D_API bool enableTangentSpace () const
C3D_API bool enableColours () const
C3D_API bool enablePassMasks () const
C3D_API bool enableTexcoord0 () const
C3D_API bool enableTexcoord1 () const
C3D_API bool enableTexcoord2 () const
C3D_API bool enableTexcoord3 () const
C3D_API bool enableTextures () const
C3D_API bool enableVertexID () const
C3D_API bool enableInstantiation () const
C3D_API bool enableParallaxOcclusionMapping (PassComponentRegister const &passComponents) const
C3D_API bool enableParallaxOcclusionMappingOne (PassComponentRegister const &passComponents) const
C3D_API bool enableVelocity () const
C3D_API bool hasFog () const
ShaderFlags
bool usesWorldSpace () const
bool usesViewSpace () const
bool usesGeometry () const
bool usesTessellation () const
bool usesColour () const
bool usesOpacity () const
bool forceTexCoords () const
bool writeEnvironmentMap () const
bool writeShadowMap () const
bool writeShadowVSM () const
bool writeShadowRSM () const
bool writeVelocity () const
bool writeVisibility () const
bool writeDepth () const
bool writePicking () const
SceneFlags
SceneFlags getShadowFlags () const
SceneFlags getGlobalIlluminationFlags () const
bool hasDiffuseGI () const
SubmeshFlags
bool hasSubmeshData (SubmeshFlag flag) const
bool hasWorldPosInputs () const
bool hasSkinData () const
ProgramFlags
bool isBillboard () const
bool isFrontCulled () const
bool hasInvertNormals () const
bool usesMesh () const
bool usesTask () const
Components
C3D_API bool hasFlag (PassComponentFlag flag) const
Public Member Functions inherited from castor3d::PipelineHiHashDetails
PipelineHiHashDetails (PassComponentCombine pcomponents, LightingModelID plightingModelId, SubmeshFlags submeshFlags=SubmeshFlag::eNone, ProgramFlags programFlags=ProgramFlag::eNone, TextureCombine ptextures=TextureCombine{}, ShaderFlags shaderFlags=ShaderFlag::eNone, VkCompareOp palphaFunc=VkCompareOp::VK_COMPARE_OP_ALWAYS, uint32_t ppassLayerIndex=0u, bool pisStatic=false)
Public Member Functions inherited from castor3d::PipelineLoHashDetails
PipelineLoHashDetails (BackgroundModelID backgroundModelId=0u, VkDeviceSize morphTargetsOffset=0u)
Textures
SceneFlags m_sceneFlags
BlendMode colourBlendMode
BlendMode alphaBlendMode
RenderPassTypeID renderPassType
VkPrimitiveTopology topology
uint32_t patchVertices
C3D_API bool hasMap (PassComponentTextureFlag flag) const
Additional Inherited Members
Public Attributes inherited from castor3d::PipelineHiHashDetails
PassComponentCombine components
TextureCombine textures
LightingModelID lightingModelId
VkCompareOp alphaFunc
uint32_t passLayerIndex
bool isStatic
SubmeshFlags m_submeshFlags
ProgramFlags m_programFlags
ShaderFlags m_shaderFlags
Public Attributes inherited from castor3d::PipelineLoHashDetails
BackgroundModelID backgroundModelId {}
VkDeviceSize morphTargetsOffset {}
Detailed Description
Pipeline flags.
Constructor & Destructor Documentation
PipelineFlags() [1/3]
castor3d::PipelineFlags::PipelineFlags (PipelineHiHashDetails hiDetails, PipelineLoHashDetails loDetails = PipelineLoHashDetails{}, SceneFlags sceneFlags = SceneFlag::eNone, BlendMode colourBlendMode = BlendMode::eNoBlend, BlendMode alphaBlendMode = BlendMode::eNoBlend, RenderPassTypeID renderPassType = 0u, VkPrimitiveTopology ptopology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST, uint32_t ppatchVertices = 3u) inline explicit
PipelineFlags() [2/3]
castor3d::PipelineFlags::PipelineFlags (PassComponentCombine pcomponents, LightingModelID plightingModelId, BackgroundModelID pbackgroundModelId, BlendMode pcolourBlendMode = BlendMode::eNoBlend, BlendMode palphaBlendMode = BlendMode::eNoBlend, RenderPassTypeID prenderPassType = 0u, SubmeshFlags psubmeshFlags = SubmeshFlag::eIndex, ProgramFlags pprogramFlags = ProgramFlag::eNone, SceneFlags psceneFlags = SceneFlag::eNone, ShaderFlags pshaderFlags = ShaderFlag::eNone, VkPrimitiveTopology ptopology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST, uint32_t ppatchVertices = 3u, VkCompareOp palphaFunc = VK_COMPARE_OP_ALWAYS, TextureCombine textures = {}, uint32_t ppassLayerIndex = {}, VkDeviceSize pmorphTargetsOffset = {}, bool pisStatic = false) inline explicit
PipelineFlags() [3/3]
castor3d::PipelineFlags::PipelineFlags (PassComponentCombine pcomponents, LightingModelID lightingModelId, BackgroundModelID pbackgroundModelId, SubmeshFlags submeshFlags, ProgramFlags programFlags, TextureCombine textures, ShaderFlags shaderFlags, VkCompareOp alphaFunc, uint32_t passLayerIndex = 0u) inline
References castor3d::PipelineHiHashDetails::lightingModelId.
Member Function Documentation
enableColours()
C3D_API bool castor3d::PipelineFlags::enableColours () const
enableIndices()
C3D_API bool castor3d::PipelineFlags::enableIndices () const
enableInstantiation()
C3D_API bool castor3d::PipelineFlags::enableInstantiation () const
Referenced by castor3d::shader::getNodeId().
enableNormal()
C3D_API bool castor3d::PipelineFlags::enableNormal () const
enableParallaxOcclusionMapping()
C3D_API bool castor3d::PipelineFlags::enableParallaxOcclusionMapping (PassComponentRegister const & passComponents) const
enableParallaxOcclusionMappingOne()
C3D_API bool castor3d::PipelineFlags::enableParallaxOcclusionMappingOne (PassComponentRegister const & passComponents) const
enablePassMasks()
C3D_API bool castor3d::PipelineFlags::enablePassMasks () const
enablePosition()
C3D_API bool castor3d::PipelineFlags::enablePosition () const
enableTangentSpace()
C3D_API bool castor3d::PipelineFlags::enableTangentSpace () const
enableTexcoord0()
C3D_API bool castor3d::PipelineFlags::enableTexcoord0 () const
enableTexcoord1()
C3D_API bool castor3d::PipelineFlags::enableTexcoord1 () const
enableTexcoord2()
C3D_API bool castor3d::PipelineFlags::enableTexcoord2 () const
enableTexcoord3()
C3D_API bool castor3d::PipelineFlags::enableTexcoord3 () const
enableTexcoords()
C3D_API bool castor3d::PipelineFlags::enableTexcoords () const
enableTextures()
C3D_API bool castor3d::PipelineFlags::enableTextures () const
enableVelocity()
C3D_API bool castor3d::PipelineFlags::enableVelocity () const
enableVertexID()
C3D_API bool castor3d::PipelineFlags::enableVertexID () const
enableVertexInput()
C3D_API bool castor3d::PipelineFlags::enableVertexInput (SubmeshFlag data) const
forceTexCoords()
bool castor3d::PipelineFlags::forceTexCoords () const inline
References castor3d::checkFlag(), castor3d::eForceTexCoords, and castor3d::PipelineHiHashDetails::m_shaderFlags.
getGlobalIlluminationFlags()
SceneFlags castor3d::PipelineFlags::getGlobalIlluminationFlags () const inline
References castor3d::eGIAny, and m_sceneFlags.
getShadowFlags()
SceneFlags castor3d::PipelineFlags::getShadowFlags () const inline
References castor3d::eShadowAny, and m_sceneFlags.
hasDiffuseGI()
bool castor3d::PipelineFlags::hasDiffuseGI () const inline
References castor3d::eGIAny, castor3d::hasAny(), and m_sceneFlags.
hasFlag()
C3D_API bool castor3d::PipelineFlags::hasFlag (PassComponentFlag flag) const
hasFog()
C3D_API bool castor3d::PipelineFlags::hasFog () const
hasInvertNormals()
bool castor3d::PipelineFlags::hasInvertNormals () const inline
References castor3d::checkFlag(), castor3d::eInvertNormals, and castor3d::PipelineHiHashDetails::m_programFlags.
hasMap()
C3D_API bool castor3d::PipelineFlags::hasMap (PassComponentTextureFlag flag) const
hasSkinData()
bool castor3d::PipelineFlags::hasSkinData () const inline
References castor3d::eSkin, and hasSubmeshData().
hasSubmeshData()
bool castor3d::PipelineFlags::hasSubmeshData (SubmeshFlag flag) const inline
References castor3d::checkFlag(), and castor3d::PipelineHiHashDetails::m_submeshFlags.
Referenced by hasSkinData(), and hasWorldPosInputs().
hasWorldPosInputs()
bool castor3d::PipelineFlags::hasWorldPosInputs () const inline
References castor3d::eVelocity, and hasSubmeshData().
isBillboard()
bool castor3d::PipelineFlags::isBillboard () const inline
References castor3d::checkFlag(), castor3d::eBillboards, and castor3d::PipelineHiHashDetails::m_programFlags.
isFrontCulled()
bool castor3d::PipelineFlags::isFrontCulled () const inline
References castor3d::checkFlag(), castor3d::eFrontCulled, and castor3d::PipelineHiHashDetails::m_programFlags.
usesColour()
bool castor3d::PipelineFlags::usesColour () const inline
References castor3d::checkFlag(), castor3d::eColour, and castor3d::PipelineHiHashDetails::m_shaderFlags.
usesGeometry()
bool castor3d::PipelineFlags::usesGeometry () const inline
References castor3d::checkFlag(), castor3d::eGeometry, and castor3d::PipelineHiHashDetails::m_shaderFlags.
usesMesh()
bool castor3d::PipelineFlags::usesMesh () const inline
References castor3d::checkFlag(), castor3d::eHasMesh, and castor3d::PipelineHiHashDetails::m_programFlags.
usesOpacity()
bool castor3d::PipelineFlags::usesOpacity () const inline
References castor3d::checkFlag(), castor3d::eOpacity, and castor3d::PipelineHiHashDetails::m_shaderFlags.
usesTask()
bool castor3d::PipelineFlags::usesTask () const inline
References castor3d::checkFlag(), castor3d::eHasTask, and castor3d::PipelineHiHashDetails::m_programFlags.
usesTessellation()
bool castor3d::PipelineFlags::usesTessellation () const inline
References castor3d::checkFlag(), castor3d::eTessellation, and castor3d::PipelineHiHashDetails::m_shaderFlags.
usesViewSpace()
bool castor3d::PipelineFlags::usesViewSpace () const inline
References castor3d::checkFlag(), castor3d::eViewSpace, and castor3d::PipelineHiHashDetails::m_shaderFlags.
usesWorldSpace()
bool castor3d::PipelineFlags::usesWorldSpace () const inline
References castor3d::checkFlag(), castor3d::eWorldSpace, and castor3d::PipelineHiHashDetails::m_shaderFlags.
writeDepth()
bool castor3d::PipelineFlags::writeDepth () const inline
References castor3d::checkFlag(), castor3d::eDepth, and castor3d::PipelineHiHashDetails::m_shaderFlags.
writeEnvironmentMap()
bool castor3d::PipelineFlags::writeEnvironmentMap () const inline
References castor3d::checkFlag(), castor3d::eEnvironmentMapping, and castor3d::PipelineHiHashDetails::m_shaderFlags.
writePicking()
bool castor3d::PipelineFlags::writePicking () const inline
References castor3d::checkFlag(), castor3d::ePicking, and castor3d::PipelineHiHashDetails::m_shaderFlags.
writeShadowMap()
bool castor3d::PipelineFlags::writeShadowMap () const inline
References castor3d::checkFlag(), castor3d::eShadowMapDirectional, castor3d::eShadowMapPoint, castor3d::eShadowMapSpot, and castor3d::PipelineHiHashDetails::m_shaderFlags.
writeShadowRSM()
bool castor3d::PipelineFlags::writeShadowRSM () const inline
References castor3d::checkFlag(), castor3d::eRsmShadowMap, and castor3d::PipelineHiHashDetails::m_shaderFlags.
writeShadowVSM()
bool castor3d::PipelineFlags::writeShadowVSM () const inline
References castor3d::checkFlag(), castor3d::eVsmShadowMap, and castor3d::PipelineHiHashDetails::m_shaderFlags.
writeVelocity()
bool castor3d::PipelineFlags::writeVelocity () const inline
References castor3d::checkFlag(), castor3d::eVelocity, and castor3d::PipelineHiHashDetails::m_shaderFlags.
writeVisibility()
bool castor3d::PipelineFlags::writeVisibility () const inline
References castor3d::checkFlag(), castor3d::eVisibility, and castor3d::PipelineHiHashDetails::m_shaderFlags.
Member Data Documentation
alphaBlendMode
BlendMode castor3d::PipelineFlags::alphaBlendMode
colourBlendMode
BlendMode castor3d::PipelineFlags::colourBlendMode
m_sceneFlags
SceneFlags castor3d::PipelineFlags::m_sceneFlags
Referenced by getGlobalIlluminationFlags(), getShadowFlags(), and hasDiffuseGI().
patchVertices
uint32_t castor3d::PipelineFlags::patchVertices
renderPassType
RenderPassTypeID castor3d::PipelineFlags::renderPassType
topology
VkPrimitiveTopology castor3d::PipelineFlags::topology
The documentation for this struct was generated from the following file:
Render/PipelineFlags.hpp