Castor3D: castor::Image Class Reference
castor::Image Class Reference
#include <Image.hpp>
Public Member Functions
Construction/Destruction.
CU_API Image (String const &name, Path const &path, Size const &size, PixelFormat format, ByteArray const &buffer, PixelFormat bufferFormat)
CU_API Image (String const &name, Path const &path, Size const &size, PixelFormat format=PixelFormat::eR8G8B8A8_UNORM, uint8_t const *buffer=nullptr, PixelFormat bufferFormat=PixelFormat::eR8G8B8A8_UNORM)
CU_API Image (String const &name, Path const &path, PxBufferBase const &buffer)
CU_API Image (String const &name, Path const &path, ImageLayout layout, PxBufferBaseUPtr buffer=nullptr)
template<PixelFormat PFSrc, PixelFormat PFDst>
Image (String name, Path path, Size const &size, uint8_t const *buffer=nullptr)
Image (String const &name, Size const &size, PixelFormat format, uint8_t const *buffer, PixelFormat bufferFormat)
Image (String const &name, Size const &size, PixelFormat format, ByteArray const &buffer, PixelFormat bufferFormat)
Image (String const &name, PxBufferBase const &buffer)
Image (String const &name, ImageLayout layout, PxBufferBaseUPtr buffer)
virtual CU_API ~Image () noexcept=default
Copy/Move.
CU_API Image (Image const &image)
CU_API Image (Image &&image) noexcept=default
CU_API Image & operator= (Image const &image)
CU_API Image & operator= (Image &&image) noexcept=default
Public Member Functions inherited from castor::NamedBaseT< T >
NamedBaseT (T name) noexcept
Constructor.
T const & getName () const noexcept
Retrieves the name.
void rename (T name) noexcept
Friends
class Font
Modification.
CU_API PxBufferBaseUPtr updateLayerLayout (Size const &extent, PixelFormat format)
CU_API Image & resample (Size const &size)
Resizes the image to the given resolution.
CU_API Image getResampled (Size const &size) const
Resizes the image to the given resolution.
CU_API Image & fill (RgbColour const &colour)
Fills all image pixels with the given colour.
CU_API Image & fill (RgbaColour const &colour)
Fills all image pixels with the given colour.
CU_API Image & setPixel (uint32_t x, uint32_t y, uint8_t const *pixel, PixelFormat format)
Fills the wanted pixel with the given buffer.
CU_API Image & setPixel (uint32_t x, uint32_t y, RgbColour const &colour)
sets the colour of the wanted pixel to the given one
CU_API Image & setPixel (uint32_t x, uint32_t y, RgbaColour const &colour)
sets the colour of the wanted pixel to the given one
template<PixelFormat PF>
Image & setPixel (uint32_t x, uint32_t y, Pixel< PF > const &pixel)
set the wanted pixel to the given pixel
CU_API Image & flip ()
Swaps the image lines.
uint32_t getLevels () const noexcept
Size getDimensions () const noexcept
std::size_t getSize (uint32_t level=0u) const noexcept
uint32_t getWidth () const noexcept
uint32_t getHeight () const noexcept
Path getPath () const noexcept
ImageLayout::Buffer getBuffer ()
ImageLayout::ConstBuffer getBuffer () const
ImageLayout::Buffer getBuffer (uint32_t index)
ImageLayout::ConstBuffer getBuffer (uint32_t index) const
ImageLayout::Buffer getBuffer (uint32_t index, uint32_t level)
ImageLayout::ConstBuffer getBuffer (uint32_t index, uint32_t level) const
bool hasBuffer () const noexcept
PxBufferBase const & getPxBuffer () const noexcept
PxBufferBase & getPxBuffer () noexcept
PxBufferBaseRPtr getPixels () const noexcept
ImageLayout const & getLayout () const noexcept
ImageLayout & getLayout () noexcept
PixelFormat getPixelFormat () const noexcept
void initialise () const noexcept
void cleanup () const noexcept
static CU_API PxBufferBaseUPtr resample (Size const &size, PxBufferBaseUPtr buffer)
Additional Inherited Members
Protected Attributes inherited from castor::NamedBaseT< T >
T m_name
Constructor & Destructor Documentation
Image() [1/11]
CU_API castor::Image::Image (String const & name, Path const & path, Size const & size, PixelFormat format, ByteArray const & buffer, PixelFormat bufferFormat)
Image() [2/11]
CU_API castor::Image::Image (String const & name, Path const & path, Size const & size, PixelFormat format = PixelFormat::eR8G8B8A8_UNORM, uint8_t const * buffer = nullptr, PixelFormat bufferFormat = PixelFormat::eR8G8B8A8_UNORM)
Image() [3/11]
CU_API castor::Image::Image (String const & name, Path const & path, PxBufferBase const & buffer)
Image() [4/11]
CU_API castor::Image::Image (String const & name, Path const & path, ImageLayout layout, PxBufferBaseUPtr buffer = nullptr)
Image() [5/11]
template<PixelFormat PFSrc, PixelFormat PFDst> castor::Image::Image (String name, Path path, Size const & size, uint8_t const * buffer = nullptr) inline
References CU_CheckInvariants.
Image() [6/11]
castor::Image::Image (String const & name, Size const & size, PixelFormat format, uint8_t const * buffer, PixelFormat bufferFormat) inline
Image() [7/11]
castor::Image::Image (String const & name, Size const & size, PixelFormat format, ByteArray const & buffer, PixelFormat bufferFormat) inline
Image() [8/11]
castor::Image::Image (String const & name, PxBufferBase const & buffer) inline
Image() [9/11]
castor::Image::Image (String const & name, ImageLayout layout, PxBufferBaseUPtr buffer) inline
~Image()
virtual CU_API castor::Image::~Image () virtual default noexcept
Image() [10/11]
CU_API castor::Image::Image (Image const & image)
Image() [11/11]
CU_API castor::Image::Image (Image && image) default noexcept
Member Function Documentation
cleanup()
void castor::Image::cleanup () const inline noexcept
fill() [1/2]
CU_API Image & castor::Image::fill (RgbaColour const & colour)
Fills all image pixels with the given colour.
Parameters
[in] colour The fill colour
Returns
A reference to the image
fill() [2/2]
CU_API Image & castor::Image::fill (RgbColour const & colour)
Fills all image pixels with the given colour.
Parameters
[in] colour The fill colour
Returns
A reference to the image
flip()
CU_API Image & castor::Image::flip ()
Swaps the image lines.
Returns
A reference to the image
getBuffer() [1/6]
ImageLayout::Buffer castor::Image::getBuffer () inline
References CU_Require, and castor::makeArrayView().
getBuffer() [2/6]
ImageLayout::ConstBuffer castor::Image::getBuffer () const inline
References CU_Require, and castor::makeArrayView().
getBuffer() [3/6]
ImageLayout::Buffer castor::Image::getBuffer (uint32_t index) inline
References CU_Require, and castor::getLayerBuffer().
getBuffer() [4/6]
ImageLayout::ConstBuffer castor::Image::getBuffer (uint32_t index) const inline
References CU_Require, and castor::getLayerBuffer().
getBuffer() [5/6]
ImageLayout::Buffer castor::Image::getBuffer (uint32_t index, uint32_t level) inline
References CU_Require, and castor::getLayerMipBuffer().
getBuffer() [6/6]
ImageLayout::ConstBuffer castor::Image::getBuffer (uint32_t index, uint32_t level) const inline
References CU_Require, and castor::getLayerMipBuffer().
getDimensions()
Size castor::Image::getDimensions () const inline noexcept
getHeight()
uint32_t castor::Image::getHeight () const inline noexcept
getLayout() [1/2]
ImageLayout const & castor::Image::getLayout () const inline noexcept
getLayout() [2/2]
ImageLayout & castor::Image::getLayout () inline noexcept
getLevels()
uint32_t castor::Image::getLevels () const inline noexcept
name Getters.
getPath()
Path castor::Image::getPath () const inline noexcept
getPixelFormat()
PixelFormat castor::Image::getPixelFormat () const inline noexcept
getPixels()
PxBufferBaseRPtr castor::Image::getPixels () const inline noexcept
getPxBuffer() [1/2]
PxBufferBase const & castor::Image::getPxBuffer () const inline noexcept
References CU_Require.
Referenced by castor3d::TextureSource::getBuffer(), castor3d::TextureSource::getBuffer(), and castor3d::TextureSource::hasBuffer().
getPxBuffer() [2/2]
PxBufferBase & castor::Image::getPxBuffer () inline noexcept
References CU_Require.
getResampled()
CU_API Image castor::Image::getResampled (Size const & size) const inline
Resizes the image to the given resolution.
Parameters
[in] size The new resolution
Returns
A reference to the image
References resample().
getSize()
std::size_t castor::Image::getSize (uint32_t level = 0u) const inline noexcept
getWidth()
uint32_t castor::Image::getWidth () const inline noexcept
hasBuffer()
bool castor::Image::hasBuffer () const inline noexcept
initialise()
void castor::Image::initialise () const inline noexcept
operator=() [1/2]
CU_API Image & castor::Image::operator= (Image && image) default noexcept
operator=() [2/2]
CU_API Image & castor::Image::operator= (Image const & image)
resample() [1/2]
CU_API Image & castor::Image::resample (Size const & size)
Resizes the image to the given resolution.
Parameters
[in] size The new resolution
Returns
A reference to the image
Referenced by getResampled().
resample() [2/2]
static CU_API PxBufferBaseUPtr castor::Image::resample (Size const & size, PxBufferBaseUPtr buffer) static
setPixel() [1/4]
template<PixelFormat PF> Image & castor::Image::setPixel (uint32_t x, uint32_t y, Pixel< PF > const & pixel) inline
set the wanted pixel to the given pixel
Parameters
[in] x,y The pixel coordinates
[in] pixel The pixel
Returns
A reference to the image
References castor::convertPixel(), CU_CheckInvariants, CU_Require, and castor::getPixelFormat().
setPixel() [2/4]
CU_API Image & castor::Image::setPixel (uint32_t x, uint32_t y, RgbaColour const & colour)
sets the colour of the wanted pixel to the given one
Parameters
[in] x,y The pixel coordinates
[in] colour The colour
Returns
A reference to the image
setPixel() [3/4]
CU_API Image & castor::Image::setPixel (uint32_t x, uint32_t y, RgbColour const & colour)
sets the colour of the wanted pixel to the given one
Parameters
[in] x,y The pixel coordinates
[in] colour The colour
Returns
A reference to the image
setPixel() [4/4]
CU_API Image & castor::Image::setPixel (uint32_t x, uint32_t y, uint8_t const * pixel, PixelFormat format)
Fills the wanted pixel with the given buffer.
Parameters
[in] x,y The pixel coordinates
[in] pixel The buffer
[in] format The buffer's pixel format
Returns
A reference to the image
updateLayerLayout()
CU_API PxBufferBaseUPtr castor::Image::updateLayerLayout (Size const & extent, PixelFormat format)
Friends And Related Symbol Documentation
Font
friend class Font friend
The documentation for this class was generated from the following file:
CastorUtils/Graphics/Image.hpp