Castor3D: castor3d::FractalMappingComponent Struct Reference
castor3d::FractalMappingComponent Struct Reference
#include <FractalMappingComponent.hpp>
Classes
struct ComponentsShader
class Plugin
Public Member Functions
C3D_API FractalMappingComponent (Pass &pass)
C3D_API void accept (ConfigurationVisitorBase &vis) override
ConfigurationVisitorBase acceptance function.
C3D_API PassComponentFlag getPassFlags () const override
bool isFractal () const
void setFractal (bool v)
Public Member Functions inherited from castor3d::BaseDataPassComponentT< castor::AtomicGroupChangeTracked< bool > >
BaseDataPassComponentT (Pass &pass, castor::String type, castor::StringArray deps={}, ParamsT &&... params)
Constructor.
void setData (DataU const &data)
void setData (ParamsT &&... params)
castor::AtomicGroupChangeTracked< bool > & getData ()
castor::AtomicGroupChangeTracked< bool > const & getData () const
Public Member Functions inherited from castor3d::PassComponent
C3D_API PassComponent (Pass &pass, castor::String type, castor::StringArray deps={})
Constructor.
virtual C3D_API ~PassComponent () noexcept=default
C3D_API PassComponentUPtr clone (Pass &pass) const
virtual C3D_API void onAddToPass () const
Called when the component is added to the pass.
C3D_API bool writeText (castor::String const &tabs, castor::Path const &folder, castor::String const &subfolder, castor::StringStream &file) const
Writes the component content to text.
C3D_API void fillBuffer (PassBuffer &buffer) const
Fills the pass buffer with this pass data.
virtual C3D_API void update ()
C3D_API void fillChannel (TextureConfiguration &configuration, uint32_t mask) const
Fills the texture configuration for use with this component.
virtual C3D_API void fillConfig (TextureConfiguration &config, ConfigurationVisitorBase &vis) const
ConfigurationVisitorBase acceptance function, for a specific texture configuration.
virtual C3D_API bool hasColour () const
virtual C3D_API castor::HdrRgbColour const & getColour () const
virtual C3D_API void setColour (castor::HdrRgbColour v)
castor::String const & getType () const
castor::StringArray const & getDependencies () const
PassComponentPlugin const & getPlugin () const
PassComponentID getId () const
void setColour (castor::RgbColour const &v, float gamma=2.2f)
void setColour (castor::Coords3f const &v)
void setColour (castor::Point3f const &v)
Public Member Functions inherited from castor::OwnedBy< Pass >
Pass * getOwner () const
Static Public Member Functions
static PassComponentPluginUPtr createPlugin (PassComponentRegister const &passComponent)
Static Public Attributes
static constexpr PassFlag eFractalMapping = PassFlag(0x01u)
static C3D_API castor::String const TypeName
Additional Inherited Members
Protected Member Functions inherited from castor::OwnedBy< Pass >
OwnedBy (Pass &owner)
Constructor.
Protected Attributes inherited from castor3d::BaseDataPassComponentT< castor::AtomicGroupChangeTracked< bool > >
castor::AtomicGroupChangeTracked< bool > m_value
Protected Attributes inherited from castor3d::PassComponent
castor::String m_type
castor::StringArray m_dependencies
PassComponentID m_id
PassComponentPlugin const & m_plugin
std::atomic_bool & m_dirty
shader::PassMaterialShader * m_materialShader {}
Constructor & Destructor Documentation
FractalMappingComponent()
C3D_API castor3d::FractalMappingComponent::FractalMappingComponent (Pass & pass) explicit
Member Function Documentation
accept()
C3D_API void castor3d::FractalMappingComponent::accept (ConfigurationVisitorBase & vis) override virtual
ConfigurationVisitorBase acceptance function.
Parameters
vis The ... visitor.
Reimplemented from castor3d::PassComponent.
createPlugin()
static PassComponentPluginUPtr castor3d::FractalMappingComponent::createPlugin (PassComponentRegister const & passComponent) inline static
getPassFlags()
C3D_API PassComponentFlag castor3d::FractalMappingComponent::getPassFlags () const inline override virtual
Reimplemented from castor3d::PassComponent.
References eFractalMapping, castor3d::eNone, castor3d::PassComponent::getId(), isFractal(), and castor3d::makePassComponentFlag().
isFractal()
bool castor3d::FractalMappingComponent::isFractal () const inline
References castor3d::BaseDataPassComponentT< castor::AtomicGroupChangeTracked< bool > >::getData().
Referenced by getPassFlags().
setFractal()
void castor3d::FractalMappingComponent::setFractal (bool v) inline
References castor3d::BaseDataPassComponentT< castor::AtomicGroupChangeTracked< bool > >::setData().
Member Data Documentation
eFractalMapping
constexpr PassFlag castor3d::FractalMappingComponent::eFractalMapping = PassFlag(0x01u) static constexpr
Referenced by castor3d::FractalMappingComponent::Plugin::getComponentFlags(), getPassFlags(), and castor3d::FractalMappingComponent::ComponentsShader::isMapSampling().
TypeName
C3D_API castor::String const castor3d::FractalMappingComponent::TypeName static
The documentation for this struct was generated from the following file:
Castor3D/Material/Pass/Component/Base/FractalMappingComponent.hpp