Castor3D: castor3d::BinaryParserBase< TParsed > Class Template Reference
castor3d::BinaryParserBase< TParsed > Class Template Reference abstract
Binary data chunk reader base class.
#include <BinaryParser.hpp>
Public Member Functions
BinaryParserBase ()=default
BinaryParserBase (BinaryParserBase const &)=default
BinaryParserBase (BinaryParserBase &&)=default
BinaryParserBase & operator= (BinaryParserBase const &)=default
BinaryParserBase & operator= (BinaryParserBase &&)=default
virtual ~BinaryParserBase ()=default
template<typename T >
BinaryParser< T > createBinaryParser ()
Creates a binary parser.
bool parse (TParsed &obj, castor::BinaryFile &file)
From file reader function.
bool parse (TParsed &obj, BinaryChunk &chunk)
From chunk reader function.
bool parse_v1_1 (TParsed &obj, BinaryChunk &chunk)
From chunk reader function.
bool parse_v1_2 (TParsed &obj, BinaryChunk &chunk)
From chunk reader function.
bool parse_v1_3 (TParsed &obj, BinaryChunk &chunk)
From chunk reader function.
bool parse_v1_4 (TParsed &obj, BinaryChunk &chunk)
From chunk reader function.
bool parse_v1_5 (TParsed &obj, BinaryChunk &chunk)
From chunk reader function.
Protected Member Functions
bool doParseHeader (BinaryChunk &chunk) const
Parses the header chunk.
template<typename T >
bool doParseChunk (T *values, size_t count, BinaryChunk &chunk) const
Retrieves a value array from a chunk.
template<typename T , size_t Count>
bool doParseChunk (T(&values)[Count], BinaryChunk &chunk) const
Retrieves a value array from a chunk.
template<typename T , size_t Count>
bool doParseChunk (std::array< T, Count > &values, BinaryChunk &chunk) const
Retrieves a value array from a chunk.
template<typename T >
bool doParseChunk (std::vector< T > &values, BinaryChunk &chunk) const
Retrieves a value array from a chunk.
template<typename T >
bool doParseChunk (T &value, BinaryChunk &chunk) const
Retrieves a value from a chunk.
bool doGetSubChunk (BinaryChunk &chunk)
Retrieves a subchunk.
void checkError (bool result, castor::String const &text) const
Protected Attributes
BinaryChunk * m_chunk { nullptr }
Version m_fileVersion
Static Protected Attributes
static C3D_API castor::String Name
Friends
template<typename T >
class BinaryParserBase
Detailed Description
template<class TParsed>
class castor3d::BinaryParserBase< TParsed >
Binary data chunk reader base class.
Constructor & Destructor Documentation
BinaryParserBase() [1/3]
template<class TParsed > castor3d::BinaryParserBase< TParsed >::BinaryParserBase () default
BinaryParserBase() [2/3]
template<class TParsed > castor3d::BinaryParserBase< TParsed >::BinaryParserBase (BinaryParserBase< TParsed > const &) default
BinaryParserBase() [3/3]
template<class TParsed > castor3d::BinaryParserBase< TParsed >::BinaryParserBase (BinaryParserBase< TParsed > &&) default
~BinaryParserBase()
template<class TParsed > virtual castor3d::BinaryParserBase< TParsed >::~BinaryParserBase () virtual default
Member Function Documentation
checkError()
template<class TParsed > void castor3d::BinaryParserBase< TParsed >::checkError (bool result, castor::String const & text) const inline protected
References castor3d::log::error, and castor3d::BinaryParserBase< TParsed >::Name.
Referenced by castor3d::BinaryParserBase< TParsed >::doParseHeader(), castor3d::BinaryParserBase< TParsed >::parse(), castor3d::BinaryParserBase< TParsed >::parse_v1_1(), castor3d::BinaryParserBase< TParsed >::parse_v1_2(), castor3d::BinaryParserBase< TParsed >::parse_v1_3(), castor3d::BinaryParserBase< TParsed >::parse_v1_4(), and castor3d::BinaryParserBase< TParsed >::parse_v1_5().
createBinaryParser()
template<class TParsed > template<typename T > BinaryParser< T > castor3d::BinaryParserBase< TParsed >::createBinaryParser () inline
Creates a binary parser.
References castor3d::BinaryParserBase< TParsed >::m_fileVersion.
doGetSubChunk()
template<class TParsed > bool castor3d::BinaryParserBase< TParsed >::doGetSubChunk (BinaryChunk & chunk) inline protected
Retrieves a subchunk.
Parameters
[out] chunk Receives the subchunk.
Returns
false if any error occured.
References castor3d::BinaryChunk::checkAvailable(), castor3d::BinaryChunk::getSubChunk(), and castor3d::BinaryParserBase< TParsed >::m_chunk.
doParseChunk() [1/5]
template<class TParsed > template<typename T , size_t Count> bool castor3d::BinaryParserBase< TParsed >::doParseChunk (std::array< T, Count > & values, BinaryChunk & chunk) const inline protected
Retrieves a value array from a chunk.
Parameters
[out] values Receives the parsed values
[in] chunk The chunk containing the values
Returns
false if any error occured
References castor3d::ChunkParser< T >::parse().
doParseChunk() [2/5]
template<class TParsed > template<typename T > bool castor3d::BinaryParserBase< TParsed >::doParseChunk (std::vector< T > & values, BinaryChunk & chunk) const inline protected
Retrieves a value array from a chunk.
Parameters
[out] values Receives the parsed values
[in] chunk The chunk containing the values
Returns
false if any error occured
References castor3d::ChunkParser< T >::parse().
doParseChunk() [3/5]
template<class TParsed > template<typename T > bool castor3d::BinaryParserBase< TParsed >::doParseChunk (T & value, BinaryChunk & chunk) const inline protected
Retrieves a value from a chunk.
Parameters
[out] value Receives the parsed value
[in] chunk The chunk containing the value
Returns
false if any error occured
References castor3d::ChunkParser< T >::parse().
doParseChunk() [4/5]
template<class TParsed > template<typename T > bool castor3d::BinaryParserBase< TParsed >::doParseChunk (T * values, size_t count, BinaryChunk & chunk) const inline protected
Retrieves a value array from a chunk.
Parameters
[out] values Receives the parsed values
[out] count The values count
[in] chunk The chunk containing the values
Returns
false if any error occured
References castor3d::ChunkParser< T >::parse().
Referenced by castor3d::BinaryParserBase< TParsed >::doParseHeader().
doParseChunk() [5/5]
template<class TParsed > template<typename T , size_t Count> bool castor3d::BinaryParserBase< TParsed >::doParseChunk (T(&) values[Count], BinaryChunk & chunk) const inline protected
Retrieves a value array from a chunk.
Parameters
[out] values Receives the parsed values
[in] chunk The chunk containing the values
Returns
false if any error occured
References castor3d::ChunkParser< T >::parse().
doParseHeader()
template<class TParsed > bool castor3d::BinaryParserBase< TParsed >::doParseHeader (BinaryChunk & chunk) const inline protected
Parses the header chunk.
Parameters
[in,out] chunk The parent chunk.
Returns
false if any error occured.
References castor3d::BinaryChunk::checkAvailable(), castor3d::BinaryParserBase< TParsed >::checkError(), castor3d::CurrentCmshVersion, castor3d::BinaryParserBase< TParsed >::doParseChunk(), castor3d::eCmshHeader, castor3d::eCmshVersion, castor3d::eName, castor3d::BinaryChunk::endParse(), castor3d::BinaryChunk::getChunkType(), castor3d::getCmshMajor(), castor3d::getCmshMinor(), castor3d::getCmshRevision(), castor3d::BinaryChunk::getSubChunk(), castor3d::BinaryParserBase< TParsed >::m_fileVersion, and castor3d::log::warn.
Referenced by castor3d::BinaryParserBase< TParsed >::parse().
operator=() [1/2]
template<class TParsed > BinaryParserBase & castor3d::BinaryParserBase< TParsed >::operator= (BinaryParserBase< TParsed > &&) default
operator=() [2/2]
template<class TParsed > BinaryParserBase & castor3d::BinaryParserBase< TParsed >::operator= (BinaryParserBase< TParsed > const &) default
parse() [1/2]
template<class TParsed > bool castor3d::BinaryParserBase< TParsed >::parse (TParsed & obj, BinaryChunk & chunk) inline
From chunk reader function.
Parameters
[out] obj The object to read
[in] chunk The chunk
Returns
false if any error occured
References castor3d::BinaryParserBase< TParsed >::checkError(), castor3d::BinaryChunk::endParse(), castor3d::BinaryChunk::getChunkType(), castor3d::BinaryParserBase< TParsed >::m_chunk, and castor3d::BinaryChunk::resetParse().
parse() [2/2]
template<class TParsed > bool castor3d::BinaryParserBase< TParsed >::parse (TParsed & obj, castor::BinaryFile & file) inline
From file reader function.
Parameters
[out] obj The object to read
[in] file The file containing the chunk
Returns
false if any error occured
References castor3d::BinaryChunk::checkAvailable(), castor3d::BinaryParserBase< TParsed >::checkError(), castor3d::BinaryParserBase< TParsed >::doParseHeader(), castor3d::eCmshFile, castor3d::BinaryChunk::getChunkType(), castor3d::BinaryChunk::getSubChunk(), castor3d::BinaryParserBase< TParsed >::parse(), and castor3d::BinaryChunk::read().
Referenced by castor3d::BinaryParserBase< TParsed >::parse().
parse_v1_1()
template<class TParsed > bool castor3d::BinaryParserBase< TParsed >::parse_v1_1 (TParsed & obj, BinaryChunk & chunk) inline
From chunk reader function.
Parameters
[out] obj The object to read
[in] chunk The chunk
Returns
false if any error occured
References castor3d::BinaryParserBase< TParsed >::checkError(), castor3d::BinaryChunk::endParse(), castor3d::BinaryChunk::getChunkType(), and castor3d::BinaryParserBase< TParsed >::m_chunk.
parse_v1_2()
template<class TParsed > bool castor3d::BinaryParserBase< TParsed >::parse_v1_2 (TParsed & obj, BinaryChunk & chunk) inline
From chunk reader function.
Parameters
[out] obj The object to read
[in] chunk The chunk
Returns
false if any error occured
References castor3d::BinaryParserBase< TParsed >::checkError(), castor3d::BinaryChunk::endParse(), castor3d::BinaryChunk::getChunkType(), and castor3d::BinaryParserBase< TParsed >::m_chunk.
parse_v1_3()
template<class TParsed > bool castor3d::BinaryParserBase< TParsed >::parse_v1_3 (TParsed & obj, BinaryChunk & chunk) inline
From chunk reader function.
Parameters
[out] obj The object to read
[in] chunk The chunk
Returns
false if any error occured
References castor3d::BinaryParserBase< TParsed >::checkError(), castor3d::BinaryChunk::endParse(), castor3d::BinaryChunk::getChunkType(), and castor3d::BinaryParserBase< TParsed >::m_chunk.
parse_v1_4()
template<class TParsed > bool castor3d::BinaryParserBase< TParsed >::parse_v1_4 (TParsed & obj, BinaryChunk & chunk) inline
From chunk reader function.
Parameters
[out] obj The object to read
[in] chunk The chunk
Returns
false if any error occured
References castor3d::BinaryParserBase< TParsed >::checkError(), castor3d::BinaryChunk::endParse(), castor3d::BinaryChunk::getChunkType(), and castor3d::BinaryParserBase< TParsed >::m_chunk.
parse_v1_5()
template<class TParsed > bool castor3d::BinaryParserBase< TParsed >::parse_v1_5 (TParsed & obj, BinaryChunk & chunk) inline
From chunk reader function.
Parameters
[out] obj The object to read
[in] chunk The chunk
Returns
false if any error occured
References castor3d::BinaryParserBase< TParsed >::checkError(), castor3d::BinaryChunk::endParse(), castor3d::BinaryChunk::getChunkType(), and castor3d::BinaryParserBase< TParsed >::m_chunk.
Friends And Related Function Documentation
BinaryParserBase
template<class TParsed > template<typename T > friend class BinaryParserBase friend
Member Data Documentation
m_chunk
template<class TParsed > BinaryChunk* castor3d::BinaryParserBase< TParsed >::m_chunk { nullptr } protected
The writer's chunk.
Referenced by castor3d::BinaryParserBase< TParsed >::doGetSubChunk(), castor3d::BinaryParserBase< TParsed >::parse(), castor3d::BinaryParserBase< TParsed >::parse_v1_1(), castor3d::BinaryParserBase< TParsed >::parse_v1_2(), castor3d::BinaryParserBase< TParsed >::parse_v1_3(), castor3d::BinaryParserBase< TParsed >::parse_v1_4(), and castor3d::BinaryParserBase< TParsed >::parse_v1_5().
m_fileVersion
template<class TParsed > Version castor3d::BinaryParserBase< TParsed >::m_fileVersion mutable protected
The chunk version from the file.
Referenced by castor3d::BinaryParserBase< TParsed >::createBinaryParser(), and castor3d::BinaryParserBase< TParsed >::doParseHeader().
Name
template<class TParsed > C3D_API castor::String castor3d::BinaryParserBase< TParsed >::Name static protected
Referenced by castor3d::BinaryParserBase< TParsed >::checkError().
The documentation for this class was generated from the following files:
Binary/BinaryModule.hpp
Binary/BinaryParser.hpp