Castor3D: castor3d::ProgressCtrl Class Reference
castor3d::ProgressCtrl Class Reference
#include <CtrlProgress.hpp>
Public Member Functions
C3D_API ProgressCtrl (SceneRPtr scene, castor::String const &name, ProgressStyle *style, ControlRPtr parent)
C3D_API ~ProgressCtrl () noexcept override
C3D_API void setTitle (castor::U32String value)
C3D_API void setRange (castor::Range< int32_t > const &value)
C3D_API void setProgress (int32_t value)
C3D_API void setContainerBorderSize (castor::Point4ui value)
C3D_API void setBarBorderSize (castor::Point4ui value)
C3D_API void setLeftToRight () noexcept
C3D_API void setRightToLeft () noexcept
C3D_API void setTopToBottom () noexcept
C3D_API void setBottomToTop () noexcept
castor::Range< int32_t > const & getRange () const noexcept
int32_t getProgress () const noexcept
void incProgress ()
bool isLeftToRight () const noexcept
bool isRightToLeft () const noexcept
bool isTopToBottom () const noexcept
bool isBottomToTop () const noexcept
bool isVertical () const noexcept
ProgressStyle const & getStyle () const
ProgressStyle & getStyle ()
Public Member Functions inherited from castor3d::Control
C3D_API Control (ControlType type, SceneRPtr scene, castor::String const &name, ControlStyleRPtr style, ControlRPtr parent, castor::Position const &position, castor::Size const &size, ControlFlagType flags=0, bool visible=true)
C3D_API ~Control () noexcept override
C3D_API void setStyle (ControlStyleRPtr value)
C3D_API void setPosition (castor::Position const &value)
C3D_API void setSize (castor::Size const &value)
C3D_API void setUV (castor::Point4d const &value)
C3D_API void setBorderSize (castor::Point4ui const &value)
C3D_API void setBorderInnerUV (castor::Point4d const &value)
C3D_API void setBorderOuterUV (castor::Point4d const &value)
C3D_API void setCaption (castor::U32String const &caption)
C3D_API void setVisible (bool value)
C3D_API castor::Position getAbsolutePosition () const
C3D_API bool isVisible () const
C3D_API bool isBackgroundInvisible () const
C3D_API ControlRPtr getChildControl (ControlID id) const
C3D_API std::array< bool, 4u > isInResizeRange (castor::Position const &position) const
template<ControlFlagTypeT FlagTypeT>
void addFlag (FlagTypeT flag)
template<ControlFlagTypeT FlagTypeT>
void addFlag (castor::FlagCombination< FlagTypeT > flag)
template<ControlFlagTypeT FlagTypeT>
void removeFlag (FlagTypeT flag)
template<ControlFlagTypeT FlagTypeT>
void removeFlag (castor::FlagCombination< FlagTypeT > flag)
C3D_API castor::Point4d const & getBorderInnerUV () const
C3D_API castor::Point4d const & getBorderOuterUV () const
C3D_API BorderPosition getBorderPosition () const
C3D_API castor::Point4d const & getUV () const
C3D_API bool isBackgroundVisible () const
ControlID getId () const noexcept
ControlType getType () const noexcept
uint64_t getFlags () const noexcept
castor::Position const & getPosition () const noexcept
castor::Size const & getSize () const noexcept
ControlRPtr getParent () const noexcept
castor::Point4ui const & getBorderSize () const noexcept
ControlsManagerRPtr getControlsManager () const noexcept
MouseCursor getCursor () const noexcept
Engine & getEngine () const noexcept
ControlStyle const & getBaseStyle () const noexcept
std::vector< ControlRPtr > const & getChildren () const noexcept
bool hasScene () const noexcept
Scene & getScene () const noexcept
uint32_t getResizeBorderSize () const noexcept
castor::Point4ui const & getClientRect () const noexcept
castor::Position getClientOffset () const
castor::Size getClientSize () const
bool isAlwaysOnTop () const noexcept
bool isMovable () const noexcept
bool isResizable () const noexcept
void show ()
void hide ()
Public Member Functions inherited from castor3d::NonClientEventHandler< Control >
NonClientEventHandler (castor::String const &name, bool catchMouseEvents)
Constructor.
void connectNC (MouseEventType event, NonClientMouseFunction function)
Connects a function to a non client mouse event.
void connectNC (KeyboardEventType event, NonClientKeyboardFunction function)
Connects a function to a non client keyboard event.
void connectNC (HandlerEventType event, NonClientHandlerFunction function)
Connects a function to a non client handler event.
Public Member Functions inherited from castor3d::EventHandler
void pushEvent (MouseEvent const &event)
Adds a mouse event to the events queue.
void connect (MouseEventType event, ClientMouseFunction function)
Connects a function to a mouse event.
bool catchesMouseEvents () const
Tells if the control catches mouse events.
void setCatchesMouseEvents (bool value)
Sets if the control can catch mouse events.
void pushEvent (KeyboardEvent const &event)
Adds a keyboard event to the events queue.
void connect (KeyboardEventType event, ClientKeyboardFunction function)
Connects a function to a keyboard event.
bool catchesTabKey () const
Tells if the control catches 'tab' key.
bool catchesReturnKey () const
Tells if the control catches 'return' key.
EventHandler (castor::String const &name, bool catchMouseEvents)
Constructor.
virtual ~EventHandler ()
Destructor.
void processEvents ()
Processes all queued events.
bool isEnabled () const
void enable ()
Sets if the control is enabled.
void disable ()
Sets if the control is disabled.
void pushEvent (HandlerEvent const &event)
Adds a handler event to the events queue.
void connect (HandlerEventType event, ClientHandlerFunction function)
Connects a function to a handler event.
Static Public Attributes
static C3D_API ControlType constexpr Type { ControlType::eProgress }
Additional Inherited Members
Public Types inherited from castor3d::NonClientEventHandler< Control >
using DerivedPtr = Control *
using ClientMouseFunction = EventHandler::ClientMouseFunction
using ClientKeyboardFunction = EventHandler::ClientKeyboardFunction
using ClientHandlerFunction = EventHandler::ClientHandlerFunction
using NonClientMouseFunction = std::function< void(DerivedPtr, MouseEvent const &) >
using NonClientKeyboardFunction = std::function< void(DerivedPtr, KeyboardEvent const &) >
using NonClientHandlerFunction = std::function< void(DerivedPtr, HandlerEvent const &) >
using OnNonClientMouseEvent = castor::SignalT< NonClientMouseFunction >
using OnNonClientKeyboardEvent = castor::SignalT< NonClientKeyboardFunction >
using OnNonClientHandlerEvent = castor::SignalT< NonClientHandlerFunction >
using OnNonClientMouseEventConnection = typename OnNonClientMouseEvent::connection
using OnNonClientKeyboardEventConnection = typename OnNonClientKeyboardEvent::connection
using OnNonClientHandlerEventConnection = typename OnNonClientHandlerEvent::connection
Public Types inherited from castor3d::EventHandler
using ClientMouseFunction = std::function< void(MouseEvent const &) >
using ClientKeyboardFunction = std::function< void(KeyboardEvent const &) >
using ClientHandlerFunction = std::function< void(HandlerEvent const &) >
using EnableFunction = std::function< void(bool) >
using OnClientMouseEvent = castor::SignalT< ClientMouseFunction >
using OnClientKeyboardEvent = castor::SignalT< ClientKeyboardFunction >
using OnClientHandlerEvent = castor::SignalT< ClientHandlerFunction >
using OnEnable = castor::SignalT< EnableFunction >
using OnClientMouseEventConnection = OnClientMouseEvent::connection
using OnClientKeyboardEventConnection = OnClientKeyboardEvent::connection
using OnClientHandlerEventConnection = OnClientHandlerEvent::connection
using OnEnableConnection = OnEnable::connection
Public Attributes inherited from castor3d::Control
OnControlChanged onChanged
Public Attributes inherited from castor3d::EventHandler
OnEnable onEnable
Protected Types inherited from castor3d::NonClientEventHandler< Control >
using EventHandlerFunction = EventHandler::EventHandlerFunction
using EventQueue = EventHandler::EventQueue
Protected Types inherited from castor3d::EventHandler
using EventHandlerFunction = std::function< void() >
using EventQueue = std::deque< std::pair< UserInputEventSPtr, EventHandlerFunction > >
Protected Member Functions inherited from castor3d::Control
C3D_API Overlay & getBackgroundOverlay ()
C3D_API void setBackgroundMaterial (MaterialObs value)
C3D_API void setBackgroundSize (castor::Size const &value)
C3D_API void setBackgroundBorderPosition (BorderPosition value)
C3D_API void setBackgroundBorderMaterial (MaterialObs value)
C3D_API void create (ControlsManager &ctrlManager)
C3D_API void destroy ()
C3D_API void addChild (ControlRPtr control)
C3D_API void removeChild (ControlRPtr control)
ControlStyle & getBaseStyle ()
Protected Member Functions inherited from castor3d::EventHandler
void processMouseEvent (MouseEventSPtr event)
Mouse event processing function.
void processKeyboardEvent (KeyboardEventSPtr event)
Keyboard event processing function.
void processHandlerEvent (HandlerEventSPtr event)
Handler event processing function.
Protected Attributes inherited from castor3d::Control
SceneRPtr m_scene {}
ControlRPtr m_parent {}
The parent control, if any.
MaterialObs m_backgroundMaterial {}
The background material.
MaterialObs m_foregroundMaterial {}
The foreground material.
ControlFlagType m_flags {}
The control flgas.
Protected Attributes inherited from castor3d::NonClientEventHandler< Control >
std::array< OnNonClientMouseEvent, size_t(MouseEventType::eCount) > m_ncMouseSlots
std::array< std::vector< OnNonClientMouseEventConnection >, size_t(MouseEventType::eCount) > m_ncMouseSlotsConnections
std::array< OnNonClientKeyboardEvent, size_t(KeyboardEventType::eCount) > m_ncKeyboardSlots
std::array< std::vector< OnNonClientKeyboardEventConnection >, size_t(KeyboardEventType::eCount) > m_ncKeyboardSlotsConnections
std::array< OnNonClientHandlerEvent, size_t(HandlerEventType::eCount) > m_ncHandlerSlots
std::array< std::vector< OnNonClientHandlerEventConnection >, size_t(HandlerEventType::eCount) > m_ncHandlerSlotsConnections
Protected Attributes inherited from castor3d::EventHandler
std::array< OnClientMouseEvent, size_t(MouseEventType::eCount) > m_mouseSlots
std::array< std::vector< OnClientMouseEventConnection >, size_t(MouseEventType::eCount) > m_mouseSlotsConnections
std::array< OnClientKeyboardEvent, size_t(KeyboardEventType::eCount) > m_keyboardSlots
std::array< std::vector< OnClientKeyboardEventConnection >, size_t(KeyboardEventType::eCount) > m_keyboardSlotsConnections
std::array< OnClientHandlerEvent, size_t(HandlerEventType::eCount) > m_handlerSlots
std::array< std::vector< OnClientHandlerEventConnection >, size_t(HandlerEventType::eCount) > m_handlerSlotsConnections
Constructor & Destructor Documentation
ProgressCtrl()
C3D_API castor3d::ProgressCtrl::ProgressCtrl (SceneRPtr scene, castor::String const & name, ProgressStyle * style, ControlRPtr parent)
Constructor
Parameters
[in] scene The parent scene (nullptr for global).
[in] name The control name
[in] style The control style
[in] parent The parent control, if any
~ProgressCtrl()
C3D_API castor3d::ProgressCtrl::~ProgressCtrl () override noexcept
Member Function Documentation
getProgress()
int32_t castor3d::ProgressCtrl::getProgress () const inline noexcept
getRange()
castor::Range< int32_t > const & castor3d::ProgressCtrl::getRange () const inline noexcept
getStyle() [1/2]
ProgressStyle & castor3d::ProgressCtrl::getStyle () inline
References castor3d::Control::getBaseStyle().
getStyle() [2/2]
ProgressStyle const & castor3d::ProgressCtrl::getStyle () const inline
Returns
The progress style.
References castor3d::Control::getBaseStyle().
incProgress()
void castor3d::ProgressCtrl::incProgress () inline
References setProgress().
isBottomToTop()
bool castor3d::ProgressCtrl::isBottomToTop () const inline noexcept
References castor3d::eBottomTop, and castor3d::Control::getFlags().
Referenced by isVertical().
isLeftToRight()
bool castor3d::ProgressCtrl::isLeftToRight () const inline noexcept
References castor3d::eLeftRight, and castor3d::Control::getFlags().
isRightToLeft()
bool castor3d::ProgressCtrl::isRightToLeft () const inline noexcept
References castor3d::eRightLeft, and castor3d::Control::getFlags().
isTopToBottom()
bool castor3d::ProgressCtrl::isTopToBottom () const inline noexcept
References castor3d::eTopBottom, and castor3d::Control::getFlags().
Referenced by isVertical().
isVertical()
bool castor3d::ProgressCtrl::isVertical () const inline noexcept
References isBottomToTop(), and isTopToBottom().
setBarBorderSize()
C3D_API void castor3d::ProgressCtrl::setBarBorderSize (castor::Point4ui value)
setBottomToTop()
C3D_API void castor3d::ProgressCtrl::setBottomToTop () noexcept
setContainerBorderSize()
C3D_API void castor3d::ProgressCtrl::setContainerBorderSize (castor::Point4ui value)
setLeftToRight()
C3D_API void castor3d::ProgressCtrl::setLeftToRight () noexcept
setProgress()
C3D_API void castor3d::ProgressCtrl::setProgress (int32_t value)
Referenced by incProgress().
setRange()
C3D_API void castor3d::ProgressCtrl::setRange (castor::Range< int32_t > const & value)
setRightToLeft()
C3D_API void castor3d::ProgressCtrl::setRightToLeft () noexcept
setTitle()
C3D_API void castor3d::ProgressCtrl::setTitle (castor::U32String value)
setTopToBottom()
C3D_API void castor3d::ProgressCtrl::setTopToBottom () noexcept
Member Data Documentation
Type
C3D_API ControlType constexpr castor3d::ProgressCtrl::Type { ControlType::eProgress } static constexpr
The documentation for this class was generated from the following file:
Gui/Controls/CtrlProgress.hpp