Castor3D: castor3d::GBufferBase Class Reference
castor3d::GBufferBase Class Reference
#include <GBuffer.hpp>
Public Member Functions
C3D_API GBufferBase (RenderDevice const &device, castor::String name)
Protected Member Functions
C3D_API TexturePtr doCreateTexture (crg::ResourceHandler &handler, castor::String const &name, VkImageCreateFlags createFlags, VkExtent3D const &size, uint32_t layerCount, uint32_t mipLevels, VkFormat format, VkImageUsageFlags usageFlags, VkBorderColor const &borderColor) const
template<typename TextureEnumT >
TextureArray doCreateTextures (crg::ResourceHandler &handler, std::array< TexturePtr, size_t(TextureEnumT::eCount) > const &inputs, castor::String const &prefix, VkImageCreateFlags createFlags, castor::Size const &size, uint32_t layerCount=1u) const
Initialises 2D or 2D array g-buffer textures.
template<typename TextureEnumT >
TextureArray doCreateTextures (crg::ResourceHandler &handler, std::array< TexturePtr, size_t(TextureEnumT::eCount) > const &inputs, castor::String const &prefix, VkImageCreateFlags createFlags, VkExtent3D const &size) const
Initialises 3D g-buffer textures.
Protected Attributes
RenderDevice const & m_device
Constructor & Destructor Documentation
GBufferBase()
C3D_API castor3d::GBufferBase::GBufferBase (RenderDevice const & device, castor::String name) explicit
Member Function Documentation
doCreateTexture()
C3D_API TexturePtr castor3d::GBufferBase::doCreateTexture (crg::ResourceHandler & handler, castor::String const & name, VkImageCreateFlags createFlags, VkExtent3D const & size, uint32_t layerCount, uint32_t mipLevels, VkFormat format, VkImageUsageFlags usageFlags, VkBorderColor const & borderColor) const protected
Referenced by doCreateTextures().
doCreateTextures() [1/2]
template<typename TextureEnumT > TextureArray castor3d::GBufferBase::doCreateTextures (crg::ResourceHandler & handler, std::array< TexturePtr, size_t(TextureEnumT::eCount) > const & inputs, castor::String const & prefix, VkImageCreateFlags createFlags, castor::Size const & size, uint32_t layerCount = 1u) const inline protected
Initialises 2D or 2D array g-buffer textures.
Parameters
[in] handler The render graph resource handler.
[in] inputs The already existing images.
[in] prefix The buffer's textures name's prefix.
[in] createFlags The creation flags for images remaining to create.
[in] size The g-buffer's dimensions.
[in] layerCount The layers count for the g-buffer.
References doCreateTexture(), castor3d::getBorderColor(), castor3d::getFormat(), castor3d::getMipLevels(), castor3d::getName(), and castor3d::getUsageFlags().
doCreateTextures() [2/2]
template<typename TextureEnumT > TextureArray castor3d::GBufferBase::doCreateTextures (crg::ResourceHandler & handler, std::array< TexturePtr, size_t(TextureEnumT::eCount) > const & inputs, castor::String const & prefix, VkImageCreateFlags createFlags, VkExtent3D const & size) const inline protected
Initialises 3D g-buffer textures.
Parameters
[in] handler The render graph resource handler.
[in] inputs The already existing images.
[in] prefix The buffer's textures name's prefix.
[in] createFlags The creation flags for images remaining to create.
[in] size The g-buffer's dimensions.
References doCreateTexture(), castor3d::getBorderColor(), castor3d::getFormat(), castor3d::getMipLevels(), castor3d::getName(), and castor3d::getUsageFlags().
Member Data Documentation
m_device
RenderDevice const& castor3d::GBufferBase::m_device protected
The documentation for this class was generated from the following file:
Render/GBuffer.hpp