Castor3D: castor3d::IblTextures Class Reference
castor3d::IblTextures Class Reference
#include <IblTextures.hpp>
Public Member Functions
C3D_API IblTextures (Scene &scene, RenderDevice const &device, Texture const &source, SamplerResPtr sampler)
Constructor.
C3D_API ~IblTextures ()
C3D_API void update (QueueData const &queueData)
Updates the environment maps.
C3D_API ashes::Semaphore const & update (QueueData const &queueData, ashes::Semaphore const &toWait)
Updates the environment maps.
Texture const & getIrradianceTexture () const
Texture const & getPrefilteredEnvironmentTexture () const
Texture const & getPrefilteredBrdfTexture () const
ashes::Sampler const & getIrradianceSampler () const
ashes::Sampler const & getPrefilteredEnvironmentSampler () const
ashes::Sampler const & getPrefilteredBrdfSampler () const
Constructor & Destructor Documentation
IblTextures()
C3D_API castor3d::IblTextures::IblTextures (Scene & scene, RenderDevice const & device, Texture const & source, SamplerResPtr sampler) explicit
Constructor.
Parameters
[in] scene The scene.
[in] device The GPU device.
[in] source The source environment map.
[in] sampler The sampler used for the environment map.
~IblTextures()
C3D_API castor3d::IblTextures::~IblTextures ()
Member Function Documentation
getIrradianceSampler()
ashes::Sampler const & castor3d::IblTextures::getIrradianceSampler () const inline
References castor3d::RadianceComputer::getSampler().
getIrradianceTexture()
Texture const & castor3d::IblTextures::getIrradianceTexture () const inline
name Getters.
References castor3d::RadianceComputer::getResult().
getPrefilteredBrdfSampler()
ashes::Sampler const & castor3d::IblTextures::getPrefilteredBrdfSampler () const inline
getPrefilteredBrdfTexture()
Texture const & castor3d::IblTextures::getPrefilteredBrdfTexture () const inline
getPrefilteredEnvironmentSampler()
ashes::Sampler const & castor3d::IblTextures::getPrefilteredEnvironmentSampler () const inline
References castor3d::EnvironmentPrefilter::getSampler().
getPrefilteredEnvironmentTexture()
Texture const & castor3d::IblTextures::getPrefilteredEnvironmentTexture () const inline
References castor3d::EnvironmentPrefilter::getResult().
update() [1/2]
C3D_API void castor3d::IblTextures::update (QueueData const & queueData)
Updates the environment maps.
Parameters
[in] queueData The queue receiving the GPU commands.
update() [2/2]
C3D_API ashes::Semaphore const & castor3d::IblTextures::update (QueueData const & queueData, ashes::Semaphore const & toWait)
Updates the environment maps.
Parameters
[in] queueData The queue receiving the GPU commands.
[in] toWait The semaphore from the previous render pass.
Returns
The semaphores signaled by this pass.
The documentation for this class was generated from the following file:
Render/PBR/IblTextures.hpp