Castor3D: castor::FlagCombination< FlagType > Class Template Reference
castor::FlagCombination< FlagType > Class Template Reference
Template class providing implicit conversion from a scoped enum to its integral base type.
#include <FlagCombination.hpp>
Public Types
using BaseType = typename std::underlying_type< FlagType >::type
The basic integer type.
Public Member Functions
Construction.
constexpr FlagCombination (FlagType value) noexcept
constexpr FlagCombination (BaseType value=BaseType{}) noexcept
Casting.
constexpr operator BaseType const & () const noexcept
constexpr BaseType value () const noexcept
Iteration.
constexpr FlagIterator< FlagType > begin () const noexcept
constexpr FlagIterator< FlagType > end () const noexcept
constexpr size_t size () const noexcept
constexpr bool empty () const noexcept
Binary operators.
constexpr FlagCombination & operator&= (BaseType rhs) noexcept
constexpr FlagCombination & operator|= (BaseType rhs) noexcept
constexpr FlagCombination & operator^= (BaseType rhs) noexcept
constexpr FlagCombination & operator&= (FlagType rhs) noexcept
constexpr FlagCombination & operator|= (FlagType rhs) noexcept
constexpr FlagCombination & operator^= (FlagType rhs) noexcept
constexpr FlagCombination & operator&= (FlagCombination< FlagType > const &rhs) noexcept
constexpr FlagCombination & operator|= (FlagCombination< FlagType > const &rhs) noexcept
constexpr FlagCombination & operator^= (FlagCombination< FlagType > const &rhs) noexcept
constexpr FlagCombination & operator~ () noexcept
Detailed Description
template<typename FlagType>
class castor::FlagCombination< FlagType >
Template class providing implicit conversion from a scoped enum to its integral base type.
Remarks
Allows definition of flags, through binary operations (&, |), for which operands will be of same binary size.
Member Typedef Documentation
BaseType
template<typename FlagType > using castor::FlagCombination< FlagType >::BaseType = typename std::underlying_type< FlagType >::type
The basic integer type.
Constructor & Destructor Documentation
FlagCombination() [1/2]
template<typename FlagType > constexpr castor::FlagCombination< FlagType >::FlagCombination (FlagType value) inline constexpr noexcept
References castor::FlagCombination< FlagType >::value().
FlagCombination() [2/2]
template<typename FlagType > constexpr castor::FlagCombination< FlagType >::FlagCombination (BaseType value = BaseType{}) inline explicit constexpr noexcept
Member Function Documentation
begin()
template<typename FlagType > constexpr FlagIterator< FlagType > castor::FlagCombination< FlagType >::begin () const inline constexpr noexcept
Referenced by castor::FlagCombination< FlagType >::size().
empty()
template<typename FlagType > constexpr bool castor::FlagCombination< FlagType >::empty () const inline constexpr noexcept
References castor::FlagCombination< FlagType >::value().
end()
template<typename FlagType > constexpr FlagIterator< FlagType > castor::FlagCombination< FlagType >::end () const inline constexpr noexcept
Referenced by castor::FlagCombination< FlagType >::size().
operator BaseType const &()
template<typename FlagType > constexpr castor::FlagCombination< FlagType >::operator BaseType const & () const inline constexpr noexcept
operator&=() [1/3]
template<typename FlagType > constexpr FlagCombination & castor::FlagCombination< FlagType >::operator&= (BaseType rhs) inline constexpr noexcept
operator&=() [2/3]
template<typename FlagType > constexpr FlagCombination & castor::FlagCombination< FlagType >::operator&= (FlagCombination< FlagType > const & rhs) inline constexpr noexcept
operator&=() [3/3]
template<typename FlagType > constexpr FlagCombination & castor::FlagCombination< FlagType >::operator&= (FlagType rhs) inline constexpr noexcept
operator^=() [1/3]
template<typename FlagType > constexpr FlagCombination & castor::FlagCombination< FlagType >::operator^= (BaseType rhs) inline constexpr noexcept
operator^=() [2/3]
template<typename FlagType > constexpr FlagCombination & castor::FlagCombination< FlagType >::operator^= (FlagCombination< FlagType > const & rhs) inline constexpr noexcept
operator^=() [3/3]
template<typename FlagType > constexpr FlagCombination & castor::FlagCombination< FlagType >::operator^= (FlagType rhs) inline constexpr noexcept
operator|=() [1/3]
template<typename FlagType > constexpr FlagCombination & castor::FlagCombination< FlagType >::operator|= (BaseType rhs) inline constexpr noexcept
operator|=() [2/3]
template<typename FlagType > constexpr FlagCombination & castor::FlagCombination< FlagType >::operator|= (FlagCombination< FlagType > const & rhs) inline constexpr noexcept
operator|=() [3/3]
template<typename FlagType > constexpr FlagCombination & castor::FlagCombination< FlagType >::operator|= (FlagType rhs) inline constexpr noexcept
operator~()
template<typename FlagType > constexpr FlagCombination & castor::FlagCombination< FlagType >::operator~ () inline constexpr noexcept
size()
template<typename FlagType > constexpr size_t castor::FlagCombination< FlagType >::size () const inline constexpr noexcept
References castor::FlagCombination< FlagType >::begin(), and castor::FlagCombination< FlagType >::end().
value()
template<typename FlagType > constexpr BaseType castor::FlagCombination< FlagType >::value () const inline constexpr noexcept
Referenced by castor::FlagCombination< FlagType >::empty(), and castor::FlagCombination< FlagType >::FlagCombination().
The documentation for this class was generated from the following files:
CastorUtils/Design/DesignModule.hpp
CastorUtils/Design/FlagCombination.hpp