Castor3D: castor3d::RenderNodesPass Class Reference
castor3d::RenderNodesPass Class Reference abstract
#include <RenderNodesPass.hpp>
Public Member Functions
C3D_API ~RenderNodesPass () override
Destructor.
virtual C3D_API void update (CpuUpdater &updater)
Updates the render pass, CPU wise.
C3D_API ShaderPtr getTaskShaderSource (PipelineFlags const &flags) const
Retrieves the task shader source matching the given flags.
C3D_API ShaderPtr getMeshShaderSource (PipelineFlags const &flags) const
Retrieves the mesh shader source matching the given flags.
C3D_API ShaderPtr getVertexShaderSource (PipelineFlags const &flags) const
Retrieves the vertex shader source matching the given flags.
C3D_API ShaderPtr getHullShaderSource (PipelineFlags const &flags) const
Retrieves the hull shader source matching the given flags.
C3D_API ShaderPtr getDomainShaderSource (PipelineFlags const &flags) const
Retrieves the domain shader source matching the given flags.
C3D_API ShaderPtr getGeometryShaderSource (PipelineFlags const &flags) const
Retrieves the geometry shader source matching the given flags.
C3D_API ShaderPtr getPixelShaderSource (PipelineFlags const &flags) const
Retrieves the pixel shader source matching the given flags.
C3D_API SubmeshFlags adjustFlags (SubmeshFlags flags) const
Adjusts given flags to match the render pass requirements.
C3D_API PassComponentCombine adjustFlags (PassComponentCombine flags) const
Adjusts given flags to match the render pass requirements.
C3D_API ProgramFlags adjustFlags (ProgramFlags flags) const
Adjusts given flags to match the render pass requirements.
C3D_API SceneFlags adjustFlags (SceneFlags flags) const
Adjusts given flags to match the render pass requirements.
C3D_API TextureCombine adjustFlags (TextureCombine texturesFlags) const
Filters the given textures flags using this pass needed textures.
C3D_API PipelineFlags createPipelineFlags (PassComponentCombine components, BlendMode colourBlendMode, BlendMode alphaBlendMode, RenderPassTypeID renderPassTypeId, LightingModelID lightingModelId, BackgroundModelID backgroundModelId, VkCompareOp alphaFunc, VkCompareOp blendAlphaFunc, TextureCombine const &textures, SubmeshFlags const &submeshFlags, ProgramFlags const &programFlags, SceneFlags const &sceneFlags, VkPrimitiveTopology topology, bool isFrontCulled, bool invertNormals, uint32_t passLayerIndex, GpuBufferOffsetT< castor::Point4f > const &morphTargets) const
Creates the pipeline flags for given configuration.
C3D_API PipelineFlags createPipelineFlags (Pass const &pass, TextureCombine const &textures, SubmeshFlags const &submeshFlags, ProgramFlags const &programFlags, SceneFlags const &sceneFlags, VkPrimitiveTopology topology, bool isFrontCulled, GpuBufferOffsetT< castor::Point4f > const &morphTargets) const
Creates the pipeline flags for given configuration.
C3D_API RenderPipeline & prepareBackPipeline (PipelineFlags pipelineFlags, ashes::PipelineVertexInputStateCreateInfoCRefArray const &vertexLayouts, ashes::DescriptorSetLayout const *meshletDescriptorLayout)
Prepares the pipeline matching the given flags, for back face culling nodes.
C3D_API RenderPipeline & prepareFrontPipeline (PipelineFlags pipelineFlags, ashes::PipelineVertexInputStateCreateInfoCRefArray const &vertexLayouts, ashes::DescriptorSetLayout const *meshletDescriptorLayout)
Prepares the pipeline matching the given flags, for front face culling nodes.
C3D_API void initialiseAdditionalDescriptor (RenderPipeline &pipeline, ShadowMapLightTypeArray const &shadowMaps, GpuBufferOffsetT< castor::Point4f > const &morphTargets)
Initialises the additional descriptor set.
C3D_API void setIgnoredNode (SceneNode const &node)
Sets the node ignored node.
C3D_API void countNodes (RenderInfo &info) const
Registers nodes counts to given RenderInfo.
virtual C3D_API ComponentModeFlags getComponentsMask () const
virtual C3D_API bool areValidPassFlags (PassComponentCombine const &passFlags) const
virtual C3D_API bool isPassEnabled () const
virtual C3D_API ShaderFlags getShaderFlags () const
C3D_API bool isValidPass (Pass const &pass) const
C3D_API bool isValidRenderable (RenderedObject const &object) const
C3D_API bool isValidNode (SceneNode const &node) const
C3D_API bool hasNodes () const
C3D_API Scene & getScene () const
C3D_API SceneNode const * getIgnoredNode () const
C3D_API bool isMeshShading () const
C3D_API NodePtrByPipelineMapT< SubmeshRenderNode > const & getSubmeshNodes () const
C3D_API ObjectNodesPtrByPipelineMapT< SubmeshRenderNode > const & getInstancedSubmeshNodes () const
C3D_API NodePtrByPipelineMapT< BillboardRenderNode > const & getBillboardNodes () const
C3D_API std::pair< uint32_t, uint32_t > fillPipelinesIds (castor::ArrayView< uint32_t > nodesPipelinesIds) const
C3D_API PipelineBufferArray const & getPassPipelineNodes () const
C3D_API uint32_t getPipelineNodesIndex (PipelineBaseHash const &hash, ashes::BufferBase const &buffer) const
C3D_API uint32_t getDrawCallsCount () const
bool isOrderIndependent () const
SceneCuller & getCuller () const
CameraUbo const & getMatrixUbo () const
uint32_t getPipelinesCount () const
bool isDirty () const
bool forceTwoSided () const
RenderFilters getRenderFilters () const
castor::String const & getTypeName () const
RenderPassTypeID getTypeID () const
bool filtersStatic () const
bool filtersNonStatic () const
bool handleStatic () const
Static Public Member Functions
static C3D_API ashes::PipelineColorBlendStateCreateInfo createBlendState (BlendMode colourBlendMode, BlendMode alphaBlendMode, uint32_t attachesCount)
Creates a blend state matching given blend modes.
Public Attributes
PassSortNodesSignal onSortNodes
Protected Member Functions
C3D_API RenderNodesPass (crg::FramePass const &pass, crg::GraphContext &context, crg::RunnableGraph &graph, RenderDevice const &device, castor::String const &typeName, crg::ImageViewIdArray targetImage, crg::ImageViewIdArray targetDepth, RenderNodesPassDesc const &desc)
Constructor.
virtual C3D_API void doUpdateUbos (CpuUpdater &updater)
Updates the render pass, CPU wise.
virtual C3D_API void doFillAdditionalBindings (PipelineFlags const &flags, ashes::VkDescriptorSetLayoutBindingArray &bindings) const =0
Fills the render pass specific descriptor layout bindings.
virtual C3D_API bool doIsValidPass (Pass const &pass) const
virtual C3D_API bool doIsValidRenderable (RenderedObject const &object) const
virtual C3D_API SubmeshFlags doAdjustSubmeshFlags (SubmeshFlags flags) const
virtual C3D_API ProgramFlags doAdjustProgramFlags (ProgramFlags flags) const
virtual C3D_API SceneFlags doAdjustSceneFlags (SceneFlags flags) const
C3D_API ShaderProgramRPtr doGetProgram (PipelineFlags const &flags, VkCullModeFlags cullMode=VK_CULL_MODE_NONE)
C3D_API void doUpdateFlags (PipelineFlags &flags) const
C3D_API void doAddShadowBindings (Scene const &scene, PipelineFlags const &flags, ashes::VkDescriptorSetLayoutBindingArray &bindings, uint32_t &index) const
C3D_API void doAddBackgroundBindings (Scene const &scene, PipelineFlags const &flags, ashes::VkDescriptorSetLayoutBindingArray &bindings, uint32_t &index) const
C3D_API void doAddShadowDescriptor (Scene const &scene, PipelineFlags const &flags, ashes::WriteDescriptorSetArray &descriptorWrites, ShadowMapLightTypeArray const &shadowMaps, uint32_t &index) const
C3D_API void doAddBackgroundDescriptor (Scene const &scene, PipelineFlags const &flags, ashes::WriteDescriptorSetArray &descriptorWrites, crg::ImageViewIdArray const &targetImage, uint32_t &index) const
Protected Attributes
RenderDevice const & m_device
RenderSystem & m_renderSystem
CameraUbo const & m_cameraUbo
SceneCuller & m_culler
crg::ImageViewIdArray m_targetImage
crg::ImageViewIdArray m_targetDepth
castor::String m_typeName
RenderPassTypeID m_typeID {}
RenderFilters m_filters { RenderFilter::eNone }
RenderQueueUPtr m_renderQueue
castor::String m_category
castor::Size m_size
bool m_oit { false }
bool m_forceTwoSided { false }
bool m_safeBand { false }
bool m_isDirty { true }
bool m_meshShading {}
SceneUbo const * m_sceneUbo {}
uint32_t m_index { 0u }
std::optional< bool > m_handleStatic { std::nullopt }
Constructor & Destructor Documentation
RenderNodesPass()
C3D_API castor3d::RenderNodesPass::RenderNodesPass (crg::FramePass const & pass, crg::GraphContext & context, crg::RunnableGraph & graph, RenderDevice const & device, castor::String const & typeName, crg::ImageViewIdArray targetImage, crg::ImageViewIdArray targetDepth, RenderNodesPassDesc const & desc) protected
Constructor.
Parameters
[in] pass The parent frame pass.
[in] context The rendering context.
[in] graph The runnable graph.
[in] device The GPU device.
[in] typeName The pass type name.
[in] targetImage The image this pass renders to.
[in] targetDepth The depth image this pass renders to.
[in] desc The construction data.
~RenderNodesPass()
C3D_API castor3d::RenderNodesPass::~RenderNodesPass () override
Destructor.
Member Function Documentation
adjustFlags() [1/5]
C3D_API PassComponentCombine castor3d::RenderNodesPass::adjustFlags (PassComponentCombine flags) const
Adjusts given flags to match the render pass requirements.
Parameters
[in] flags The flags.
adjustFlags() [2/5]
C3D_API ProgramFlags castor3d::RenderNodesPass::adjustFlags (ProgramFlags flags) const
Adjusts given flags to match the render pass requirements.
Parameters
[in] flags The flags.
adjustFlags() [3/5]
C3D_API SceneFlags castor3d::RenderNodesPass::adjustFlags (SceneFlags flags) const
Adjusts given flags to match the render pass requirements.
Parameters
[in] flags The flags.
adjustFlags() [4/5]
C3D_API SubmeshFlags castor3d::RenderNodesPass::adjustFlags (SubmeshFlags flags) const
Adjusts given flags to match the render pass requirements.
Parameters
[in] flags The flags.
adjustFlags() [5/5]
C3D_API TextureCombine castor3d::RenderNodesPass::adjustFlags (TextureCombine texturesFlags) const
Filters the given textures flags using this pass needed textures.
Parameters
[in] texturesFlags The textures flags.
Returns
The filtered flags.
areValidPassFlags()
virtual C3D_API bool castor3d::RenderNodesPass::areValidPassFlags (PassComponentCombine const & passFlags) const virtual
Reimplemented in castor3d::RenderTechniqueNodesPass.
Referenced by castor3d::RenderTechniqueNodesPass::areValidPassFlags().
countNodes()
C3D_API void castor3d::RenderNodesPass::countNodes (RenderInfo & info) const
Registers nodes counts to given RenderInfo.
Parameters
[in,out] info Receives the counts.
Referenced by castor3d::RenderTechniqueNodesPass::countNodes().
createBlendState()
static C3D_API ashes::PipelineColorBlendStateCreateInfo castor3d::RenderNodesPass::createBlendState (BlendMode colourBlendMode, BlendMode alphaBlendMode, uint32_t attachesCount) static
Creates a blend state matching given blend modes.
Parameters
[in] colourBlendMode The colour blend mode.
[in] alphaBlendMode The alpha blend mode.
[in] attachesCount The wanted blend attaches count.
Returns
createPipelineFlags() [1/2]
C3D_API PipelineFlags castor3d::RenderNodesPass::createPipelineFlags (Pass const & pass, TextureCombine const & textures, SubmeshFlags const & submeshFlags, ProgramFlags const & programFlags, SceneFlags const & sceneFlags, VkPrimitiveTopology topology, bool isFrontCulled, GpuBufferOffsetT< castor::Point4f > const & morphTargets) const
Creates the pipeline flags for given configuration.
Parameters
[in] pass The pass for which the pipeline is created.
[in] textures The textures configuration.
[in] submeshFlags A combination of SubmeshFlag.
[in] programFlags A combination of ProgramFlag.
[in] sceneFlags Scene related flags.
[in] topology The render topology.
[in] isFrontCulled true for front face culling, false for back face culling.
[in] morphTargets The morph targets buffer.
createPipelineFlags() [2/2]
C3D_API PipelineFlags castor3d::RenderNodesPass::createPipelineFlags (PassComponentCombine components, BlendMode colourBlendMode, BlendMode alphaBlendMode, RenderPassTypeID renderPassTypeId, LightingModelID lightingModelId, BackgroundModelID backgroundModelId, VkCompareOp alphaFunc, VkCompareOp blendAlphaFunc, TextureCombine const & textures, SubmeshFlags const & submeshFlags, ProgramFlags const & programFlags, SceneFlags const & sceneFlags, VkPrimitiveTopology topology, bool isFrontCulled, bool invertNormals, uint32_t passLayerIndex, GpuBufferOffsetT< castor::Point4f > const & morphTargets) const
Creates the pipeline flags for given configuration.
Parameters
[in] components The components combination.
[in] colourBlendMode The colour blending mode.
[in] alphaBlendMode The alpha blending mode.
[in] renderPassTypeId The render pass type ID.
[in] lightingModelId The lighting model ID.
[in] backgroundModelId The background model ID.
[in] alphaFunc The alpha comparison function (for opaque nodes).
[in] blendAlphaFunc The alpha comparison function (for transparent nodes).
[in] textures The textures configuration.
[in] submeshFlags A combination of SubmeshFlag.
[in] programFlags A combination of ProgramFlag.
[in] sceneFlags Scene related flags.
[in] topology The render topology.
[in] isFrontCulled true for front face culling, false for back face culling.
[in] invertNormals true to invert normals.
[in] passLayerIndex The material pass layer index.
[in] morphTargets The morph targets buffer.
doAddBackgroundBindings()
C3D_API void castor3d::RenderNodesPass::doAddBackgroundBindings (Scene const & scene, PipelineFlags const & flags, ashes::VkDescriptorSetLayoutBindingArray & bindings, uint32_t & index) const protected
doAddBackgroundDescriptor()
C3D_API void castor3d::RenderNodesPass::doAddBackgroundDescriptor (Scene const & scene, PipelineFlags const & flags, ashes::WriteDescriptorSetArray & descriptorWrites, crg::ImageViewIdArray const & targetImage, uint32_t & index) const protected
doAddShadowBindings()
C3D_API void castor3d::RenderNodesPass::doAddShadowBindings (Scene const & scene, PipelineFlags const & flags, ashes::VkDescriptorSetLayoutBindingArray & bindings, uint32_t & index) const protected
doAddShadowDescriptor()
C3D_API void castor3d::RenderNodesPass::doAddShadowDescriptor (Scene const & scene, PipelineFlags const & flags, ashes::WriteDescriptorSetArray & descriptorWrites, ShadowMapLightTypeArray const & shadowMaps, uint32_t & index) const protected
doAdjustProgramFlags()
virtual C3D_API ProgramFlags castor3d::RenderNodesPass::doAdjustProgramFlags (ProgramFlags flags) const protected virtual
Reimplemented in castor3d::RenderTechniqueNodesPass.
doAdjustSceneFlags()
virtual C3D_API SceneFlags castor3d::RenderNodesPass::doAdjustSceneFlags (SceneFlags flags) const protected virtual
Reimplemented in castor3d::RenderTechniqueNodesPass.
doAdjustSubmeshFlags()
virtual C3D_API SubmeshFlags castor3d::RenderNodesPass::doAdjustSubmeshFlags (SubmeshFlags flags) const protected virtual
doFillAdditionalBindings()
virtual C3D_API void castor3d::RenderNodesPass::doFillAdditionalBindings (PipelineFlags const & flags, ashes::VkDescriptorSetLayoutBindingArray & bindings) const protected pure virtual
Fills the render pass specific descriptor layout bindings.
Parameters
[in] flags The pipeline flags.
[in,out] bindings Receives the additional bindings.
doGetProgram()
C3D_API ShaderProgramRPtr castor3d::RenderNodesPass::doGetProgram (PipelineFlags const & flags, VkCullModeFlags cullMode = VK_CULL_MODE_NONE) protected
doIsValidPass()
virtual C3D_API bool castor3d::RenderNodesPass::doIsValidPass (Pass const & pass) const protected virtual
Parameters
[in] pass The material pass.
Returns
true if the pass is rendered through this nodes pass.
doIsValidRenderable()
virtual C3D_API bool castor3d::RenderNodesPass::doIsValidRenderable (RenderedObject const & object) const protected virtual
Parameters
[in] object The rendered object.
Returns
true if the object is rendered through this nodes pass.
doUpdateFlags()
C3D_API void castor3d::RenderNodesPass::doUpdateFlags (PipelineFlags & flags) const protected
doUpdateUbos()
virtual C3D_API void castor3d::RenderNodesPass::doUpdateUbos (CpuUpdater & updater) protected virtual
Updates the render pass, CPU wise.
Parameters
[in,out] updater The update data.
fillPipelinesIds()
C3D_API std::pair< uint32_t, uint32_t > castor3d::RenderNodesPass::fillPipelinesIds (castor::ArrayView< uint32_t > nodesPipelinesIds) const
filtersNonStatic()
bool castor3d::RenderNodesPass::filtersNonStatic () const inline
References handleStatic(), and m_handleStatic.
filtersStatic()
bool castor3d::RenderNodesPass::filtersStatic () const inline
References handleStatic(), and m_handleStatic.
forceTwoSided()
bool castor3d::RenderNodesPass::forceTwoSided () const inline
References m_forceTwoSided.
getBillboardNodes()
C3D_API NodePtrByPipelineMapT< BillboardRenderNode > const & castor3d::RenderNodesPass::getBillboardNodes () const
getComponentsMask()
virtual C3D_API ComponentModeFlags castor3d::RenderNodesPass::getComponentsMask () const virtual
name Getters.
Reimplemented in castor3d::VoxelizePass, castor3d::OpaquePass, castor3d::ForwardRenderTechniquePass, castor3d::PickingPass, castor3d::DepthPass, castor3d::VisibilityPass, castor3d::ShadowMapPass, and castor3d::TransparentPass.
getCuller()
SceneCuller & castor3d::RenderNodesPass::getCuller () const inline
References m_culler.
getDomainShaderSource()
C3D_API ShaderPtr castor3d::RenderNodesPass::getDomainShaderSource (PipelineFlags const & flags) const
Retrieves the domain shader source matching the given flags.
Parameters
[in] flags The pipeline flags.
getDrawCallsCount()
C3D_API uint32_t castor3d::RenderNodesPass::getDrawCallsCount () const
getGeometryShaderSource()
C3D_API ShaderPtr castor3d::RenderNodesPass::getGeometryShaderSource (PipelineFlags const & flags) const
Retrieves the geometry shader source matching the given flags.
Parameters
[in] flags The pipeline flags.
getHullShaderSource()
C3D_API ShaderPtr castor3d::RenderNodesPass::getHullShaderSource (PipelineFlags const & flags) const
Retrieves the hull shader source matching the given flags.
Parameters
[in] flags The pipeline flags.
getIgnoredNode()
C3D_API SceneNode const * castor3d::RenderNodesPass::getIgnoredNode () const
getInstancedSubmeshNodes()
C3D_API ObjectNodesPtrByPipelineMapT< SubmeshRenderNode > const & castor3d::RenderNodesPass::getInstancedSubmeshNodes () const
getMatrixUbo()
CameraUbo const & castor3d::RenderNodesPass::getMatrixUbo () const inline
References m_cameraUbo.
getMeshShaderSource()
C3D_API ShaderPtr castor3d::RenderNodesPass::getMeshShaderSource (PipelineFlags const & flags) const
Retrieves the mesh shader source matching the given flags.
Parameters
[in] flags The pipeline flags.
getPassPipelineNodes()
C3D_API PipelineBufferArray const & castor3d::RenderNodesPass::getPassPipelineNodes () const
getPipelineNodesIndex()
C3D_API uint32_t castor3d::RenderNodesPass::getPipelineNodesIndex (PipelineBaseHash const & hash, ashes::BufferBase const & buffer) const
getPipelinesCount()
uint32_t castor3d::RenderNodesPass::getPipelinesCount () const inline
getPixelShaderSource()
C3D_API ShaderPtr castor3d::RenderNodesPass::getPixelShaderSource (PipelineFlags const & flags) const
Retrieves the pixel shader source matching the given flags.
Parameters
[in] flags The pipeline flags.
getRenderFilters()
RenderFilters castor3d::RenderNodesPass::getRenderFilters () const inline
References m_filters.
getScene()
C3D_API Scene & castor3d::RenderNodesPass::getScene () const
getShaderFlags()
virtual C3D_API ShaderFlags castor3d::RenderNodesPass::getShaderFlags () const virtual
Reimplemented in castor3d::VoxelizePass, castor3d::OpaquePass, castor3d::PickingPass, castor3d::DepthPass, castor3d::VisibilityPass, castor3d::RenderTechniqueNodesPass, and castor3d::ShadowMapPass.
getSubmeshNodes()
C3D_API NodePtrByPipelineMapT< SubmeshRenderNode > const & castor3d::RenderNodesPass::getSubmeshNodes () const
getTaskShaderSource()
C3D_API ShaderPtr castor3d::RenderNodesPass::getTaskShaderSource (PipelineFlags const & flags) const
Retrieves the task shader source matching the given flags.
Parameters
[in] flags The pipeline flags.
getTypeID()
RenderPassTypeID castor3d::RenderNodesPass::getTypeID () const inline
References m_typeID.
getTypeName()
castor::String const & castor3d::RenderNodesPass::getTypeName () const inline
References m_typeName.
getVertexShaderSource()
C3D_API ShaderPtr castor3d::RenderNodesPass::getVertexShaderSource (PipelineFlags const & flags) const
Retrieves the vertex shader source matching the given flags.
Parameters
[in] flags The pipeline flags.
handleStatic()
bool castor3d::RenderNodesPass::handleStatic () const inline
References m_handleStatic.
Referenced by filtersNonStatic(), and filtersStatic().
hasNodes()
C3D_API bool castor3d::RenderNodesPass::hasNodes () const
initialiseAdditionalDescriptor()
C3D_API void castor3d::RenderNodesPass::initialiseAdditionalDescriptor (RenderPipeline & pipeline, ShadowMapLightTypeArray const & shadowMaps, GpuBufferOffsetT< castor::Point4f > const & morphTargets)
Initialises the additional descriptor set.
Parameters
[in] pipeline The render pipeline.
[in] shadowMaps The shadow maps.
[in] morphTargets The morph targets buffer.
isDirty()
bool castor3d::RenderNodesPass::isDirty () const inline
References m_isDirty.
isMeshShading()
C3D_API bool castor3d::RenderNodesPass::isMeshShading () const
isOrderIndependent()
bool castor3d::RenderNodesPass::isOrderIndependent () const inline
References m_oit.
isPassEnabled()
virtual C3D_API bool castor3d::RenderNodesPass::isPassEnabled () const virtual
Reimplemented in castor3d::VoxelizePass, castor3d::RenderTechniqueNodesPass, and castor3d::ShadowMapPass.
Referenced by castor3d::RenderTechniqueNodesPass::isPassEnabled(), and castor3d::IsRenderPassEnabled::operator()().
isValidNode()
C3D_API bool castor3d::RenderNodesPass::isValidNode (SceneNode const & node) const
isValidPass()
C3D_API bool castor3d::RenderNodesPass::isValidPass (Pass const & pass) const
isValidRenderable()
C3D_API bool castor3d::RenderNodesPass::isValidRenderable (RenderedObject const & object) const
prepareBackPipeline()
C3D_API RenderPipeline & castor3d::RenderNodesPass::prepareBackPipeline (PipelineFlags pipelineFlags, ashes::PipelineVertexInputStateCreateInfoCRefArray const & vertexLayouts, ashes::DescriptorSetLayout const * meshletDescriptorLayout)
Prepares the pipeline matching the given flags, for back face culling nodes.
Parameters
[in] pipelineFlags The pipeline flags.
[in] vertexLayouts The vertex buffers layouts.
[in] meshletDescriptorLayout The optional meshlets descriptor layout.
prepareFrontPipeline()
C3D_API RenderPipeline & castor3d::RenderNodesPass::prepareFrontPipeline (PipelineFlags pipelineFlags, ashes::PipelineVertexInputStateCreateInfoCRefArray const & vertexLayouts, ashes::DescriptorSetLayout const * meshletDescriptorLayout)
Prepares the pipeline matching the given flags, for front face culling nodes.
Parameters
[in] pipelineFlags The pipeline flags.
[in] vertexLayouts The vertex buffers layouts.
[in] meshletDescriptorLayout The optional meshlets descriptor layout.
setIgnoredNode()
C3D_API void castor3d::RenderNodesPass::setIgnoredNode (SceneNode const & node)
Sets the node ignored node.
Remarks
All objects attached to this node will be ignored during rendering.
Parameters
[in] node The node.
update()
virtual C3D_API void castor3d::RenderNodesPass::update (CpuUpdater & updater) virtual
Updates the render pass, CPU wise.
Parameters
[in,out] updater The update data.
Reimplemented in castor3d::VoxelizePass, castor3d::RenderTechniqueNodesPass, castor3d::ShadowMapPassDirectional, castor3d::ShadowMapPassPoint, and castor3d::ShadowMapPassSpot.
Member Data Documentation
m_cameraUbo
CameraUbo const& castor3d::RenderNodesPass::m_cameraUbo protected
Referenced by getMatrixUbo().
m_category
castor::String castor3d::RenderNodesPass::m_category protected
m_culler
SceneCuller& castor3d::RenderNodesPass::m_culler protected
Referenced by getCuller().
m_device
RenderDevice const& castor3d::RenderNodesPass::m_device protected
m_filters
RenderFilters castor3d::RenderNodesPass::m_filters { RenderFilter::eNone } protected
Referenced by getRenderFilters().
m_forceTwoSided
bool castor3d::RenderNodesPass::m_forceTwoSided { false } protected
Referenced by forceTwoSided().
m_handleStatic
std::optional< bool > castor3d::RenderNodesPass::m_handleStatic { std::nullopt } protected
Referenced by filtersNonStatic(), filtersStatic(), and handleStatic().
m_index
uint32_t castor3d::RenderNodesPass::m_index { 0u } protected
m_isDirty
bool castor3d::RenderNodesPass::m_isDirty { true } protected
Referenced by isDirty().
m_meshShading
bool castor3d::RenderNodesPass::m_meshShading {} protected
m_oit
bool castor3d::RenderNodesPass::m_oit { false } protected
Referenced by isOrderIndependent().
m_renderQueue
RenderQueueUPtr castor3d::RenderNodesPass::m_renderQueue protected
m_renderSystem
RenderSystem& castor3d::RenderNodesPass::m_renderSystem protected
m_safeBand
bool castor3d::RenderNodesPass::m_safeBand { false } protected
m_sceneUbo
SceneUbo const* castor3d::RenderNodesPass::m_sceneUbo {} protected
m_size
castor::Size castor3d::RenderNodesPass::m_size protected
m_targetDepth
crg::ImageViewIdArray castor3d::RenderNodesPass::m_targetDepth protected
m_targetImage
crg::ImageViewIdArray castor3d::RenderNodesPass::m_targetImage protected
m_typeID
RenderPassTypeID castor3d::RenderNodesPass::m_typeID {} protected
Referenced by getTypeID().
m_typeName
castor::String castor3d::RenderNodesPass::m_typeName protected
Referenced by getTypeName().
onSortNodes
PassSortNodesSignal castor3d::RenderNodesPass::onSortNodes mutable
The documentation for this class was generated from the following file:
Render/RenderNodesPass.hpp