Castor3D: castor3d::VoxelizerUbo Class Reference
castor3d::VoxelizerUbo Class Reference
#include <VoxelizerUbo.hpp>
Public Types
using Configuration = VoxelizerUboConfiguration
Public Member Functions
C3D_API VoxelizerUbo (VoxelizerUbo const &rhs)=delete
C3D_API VoxelizerUbo & operator= (VoxelizerUbo const &rhs)=delete
C3D_API VoxelizerUbo (VoxelizerUbo &&rhs)=default
C3D_API VoxelizerUbo & operator= (VoxelizerUbo &&rhs)=delete
C3D_API VoxelizerUbo (RenderDevice const &device)
C3D_API ~VoxelizerUbo ()
C3D_API void cpuUpdate (VoxelSceneData const &voxelConfig, float worldToGrid, uint32_t voxelGridSize)
void createPassBinding (crg::FramePass &pass, uint32_t binding) const
void createSizedBinding (ashes::DescriptorSet &descriptorSet, VkDescriptorSetLayoutBinding const &layoutBinding) const
ashes::WriteDescriptorSet getDescriptorWrite (uint32_t dstBinding, uint32_t dstArrayElement=0u) const
UniformBufferOffsetT< Configuration > const & getUbo () const
Static Public Attributes
static C3D_API castor::String const BufferVoxelizer
static C3D_API castor::String const VoxelData
Member Typedef Documentation
Configuration
using castor3d::VoxelizerUbo::Configuration = VoxelizerUboConfiguration
Constructor & Destructor Documentation
VoxelizerUbo() [1/3]
C3D_API castor3d::VoxelizerUbo::VoxelizerUbo (VoxelizerUbo const & rhs) delete
VoxelizerUbo() [2/3]
C3D_API castor3d::VoxelizerUbo::VoxelizerUbo (VoxelizerUbo && rhs) default
VoxelizerUbo() [3/3]
C3D_API castor3d::VoxelizerUbo::VoxelizerUbo (RenderDevice const & device) explicit
~VoxelizerUbo()
C3D_API castor3d::VoxelizerUbo::~VoxelizerUbo ()
Member Function Documentation
cpuUpdate()
C3D_API void castor3d::VoxelizerUbo::cpuUpdate (VoxelSceneData const & voxelConfig, float worldToGrid, uint32_t voxelGridSize)
createPassBinding()
void castor3d::VoxelizerUbo::createPassBinding (crg::FramePass & pass, uint32_t binding) const inline
References castor3d::UniformBufferOffsetT< DataT >::createPassBinding().
createSizedBinding()
void castor3d::VoxelizerUbo::createSizedBinding (ashes::DescriptorSet & descriptorSet, VkDescriptorSetLayoutBinding const & layoutBinding) const inline
References castor3d::UniformBufferOffsetT< DataT >::createSizedBinding().
getDescriptorWrite()
ashes::WriteDescriptorSet castor3d::VoxelizerUbo::getDescriptorWrite (uint32_t dstBinding, uint32_t dstArrayElement = 0u) const inline
References castor3d::UniformBufferOffsetT< DataT >::getDescriptorWrite().
getUbo()
UniformBufferOffsetT< Configuration > const & castor3d::VoxelizerUbo::getUbo () const inline
operator=() [1/2]
C3D_API VoxelizerUbo & castor3d::VoxelizerUbo::operator= (VoxelizerUbo && rhs) delete
operator=() [2/2]
C3D_API VoxelizerUbo & castor3d::VoxelizerUbo::operator= (VoxelizerUbo const & rhs) delete
Member Data Documentation
BufferVoxelizer
C3D_API castor::String const castor3d::VoxelizerUbo::BufferVoxelizer static
VoxelData
C3D_API castor::String const castor3d::VoxelizerUbo::VoxelData static
The documentation for this class was generated from the following file:
Shader/Ubos/VoxelizerUbo.hpp