Castor3D: castor3d::ChunkParser< castor::Path > Class Template Reference
castor3d::ChunkParser< castor::Path > Class Template Reference
ChunkParser specialisation for castor::Path.
Static Public Member Functions
static bool parse (castor::Path &value, BinaryChunk &chunk)
Retrieves a value from a chunk.
Static Public Member Functions inherited from castor3d::ChunkParserBase
static bool parse (uint8_t *values, size_t size, BinaryChunk &chunk)
Retrieves a value array from a chunk.
Detailed Description
template<>
class castor3d::ChunkParser< castor::Path >
ChunkParser specialisation for castor::Path.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
08/04/2014
Member Function Documentation
parse()
static bool castor3d::ChunkParser< castor::Path >::parse (castor::Path & value, BinaryChunk & chunk) inline static
Retrieves a value from a chunk.
Parameters
[out] value Receives the parsed value
[in] chunk The chunk containing the value
Returns
false if any error occured
References castor3d::BinaryChunk::checkAvailable(), castor3d::BinaryChunk::getRemaining(), and castor3d::ChunkParserBase::parse().
The documentation for this class was generated from the following file:
Binary/ChunkParser.hpp