Castor3D: castor3d Namespace Reference
castor3d Namespace Reference
Namespaces
details
lpv
rq
shader
Classes
class AnimableT
Animable public interface.
class AnimatedMesh
class AnimatedObject
class AnimatedObjectGroup
class AnimatedSkeleton
class AnimatedTexture
class AnimationInstance
class AnimationInstanceT
Used to play an Animation on a specific object.
class AnimationKeyFrame
class AnimationT
Animation base class.
struct ArrayView
class BackgroundTextWriter
class BackgroundVisitor
class BillboardBase
class BillboardList
struct BillboardRenderNode
class BillboardUbo
struct BillboardUboConfiguration
Billboards list data.
class BillboardUboPools
class BinaryChunk
class BinaryParser
Specialisable binary data chunk reader class.
class BinaryParser< Animation >
Animation binary loader.
class BinaryParser< Bone >
Animable binary loader.
class BinaryParser< BonesComponent >
BonesComponent loader.
class BinaryParser< Mesh >
MovableObject loader.
class BinaryParser< MeshAnimation >
MeshAnimation binary loader.
class BinaryParser< MeshAnimationKeyFrame >
MeshAnimationKeyFrame binary loader.
class BinaryParser< Skeleton >
Animable binary loader.
class BinaryParser< SkeletonAnimation >
SkeletonAnimation binary loader.
class BinaryParser< SkeletonAnimationBone >
MovingBone binary loader.
class BinaryParser< SkeletonAnimationKeyFrame >
SkeletonAnimationKeyFrame binary loader.
class BinaryParser< SkeletonAnimationNode >
MovingBone binary loader.
class BinaryParser< SkeletonAnimationObject >
SkeletonAnimationObject binary loader.
class BinaryParser< Submesh >
MovableObject loader.
class BinaryParserBase
Binary data chunk reader base class.
class BinaryWriter
Specialisable binary data chunk writer class.
class BinaryWriter< Animation >
Animation binary loader.
class BinaryWriter< Bone >
Animable binary loader.
class BinaryWriter< BonesComponent >
BonesComponent loader.
class BinaryWriter< Mesh >
MovableObject loader.
class BinaryWriter< MeshAnimation >
MeshAnimation binary loader.
class BinaryWriter< MeshAnimationKeyFrame >
MeshAnimationKeyFrame binary loader.
class BinaryWriter< Skeleton >
Animable binary loader.
class BinaryWriter< SkeletonAnimation >
SkeletonAnimation binary loader.
class BinaryWriter< SkeletonAnimationBone >
MovingBone binary loader.
class BinaryWriter< SkeletonAnimationKeyFrame >
SkeletonAnimationKeyFrame binary loader.
class BinaryWriter< SkeletonAnimationNode >
MovingBone binary loader.
class BinaryWriter< SkeletonAnimationObject >
SkeletonAnimationObject binary loader.
class BinaryWriter< Submesh >
MovableObject loader.
class BinaryWriterBase
Binary data chunk writer base class.
class Bone
class BonesComponent
class BonesInstantiationComponent
class BorderPanelOverlay
class BrdfPrefilter
class Cache
Base class for an element cache.
class Cache< AnimatedObjectGroup, castor::String >
AnimatedObjectGroup cache.
class Cache< Overlay, castor::String >
Overlay collection, with additional add and remove functions to manage Z-Index.
class Cache< Plugin, castor::String >
Plug-ins cache.
class CacheBase
Base class for an element cache.
struct CacheTraits
Helper structure to specialise a cache behaviour.
struct CacheTraits< AnimatedObjectGroup, KeyType >
Helper structure to specialise a cache behaviour.
struct CacheTraits< FrameListener, KeyType >
Helper structure to specialise a cache behaviour.
struct CacheTraits< Material, KeyType >
Helper structure to specialise a cache behaviour.
struct CacheTraits< Mesh, KeyType >
Helper structure to specialise a cache behaviour.
struct CacheTraits< Overlay, KeyType >
Helper structure to specialise a cache behaviour.
struct CacheTraits< Plugin, KeyType >
Helper structure to specialise a cache behaviour.
struct CacheTraits< RenderTechnique, KeyType >
Helper structure to specialise a cache behaviour.
struct CacheTraits< RenderWindow, KeyType >
Helper structure to specialise a cache behaviour.
struct CacheTraits< Sampler, KeyType >
Helper structure to specialise a cache behaviour.
struct CacheTraits< Scene, KeyType >
Helper structure to specialise a cache behaviour.
class CacheView
View on a resource cache.
class Camera
class ChunkParser
Chunk parser.
class ChunkParser< castor::Path >
ChunkParser specialisation for castor::Path.
class ChunkParser< castor::String >
ChunkParser specialisation for castor::String.
class ChunkParserBase
struct ChunkTyper
Helper structure to find ChunkType from a type.
struct ChunkTyper< Animation >
Helper structure to find ChunkType from a type.
struct ChunkTyper< Bone >
Helper structure to find ChunkType from a type.
struct ChunkTyper< BonesComponent >
Helper structure to find ChunkType from a type.
struct ChunkTyper< Mesh >
Helper structure to find ChunkType from a type.
struct ChunkTyper< MeshAnimation >
Helper structure to find ChunkType from a type.
struct ChunkTyper< MeshAnimationKeyFrame >
Helper structure to find ChunkType from a type.
struct ChunkTyper< Skeleton >
Helper structure to find ChunkType from a type.
struct ChunkTyper< SkeletonAnimation >
Helper structure to find ChunkType from a type.
struct ChunkTyper< SkeletonAnimationBone >
Helper structure to find ChunkType from a type.
struct ChunkTyper< SkeletonAnimationKeyFrame >
Helper structure to find ChunkType from a type.
struct ChunkTyper< SkeletonAnimationNode >
Helper structure to find ChunkType from a type.
struct ChunkTyper< SkeletonAnimationObject >
Helper structure to find ChunkType from a type.
struct ChunkTyper< Submesh >
Helper structure to find ChunkType from a type.
class ChunkWriter
Chunk data writer.
class ChunkWriter< castor::Path >
ChunkWriter specialisation for castor::Path.
class ChunkWriter< castor::String >
ChunkWriter specialisation for castor::String.
class ChunkWriterBase
class CmshImporter
class ColourBackground
class CombinePass
class CombinePassBuilder
struct CombinePassConfigT
The configuration to create a CombinePass.
struct CommandsSemaphore
class ComputeParticleSystem
class Cone
class CpuFrameEvent
class CpuFunctorEvent
class CpuParticleSystem
struct CpuUpdater
class Cube
struct CubeView
struct CulledBillboard
struct CulledSubmesh
class Cylinder
class DebugCallbacks
struct DebugConfig
class DebugOverlays
class DeferredRendering
class DepthPass
class DirectionalLight
struct DirectionalLightCascade
class DirectionalLightPass
struct DistanceRenderNode
Helper structure used to render distance sorted typed nodes.
struct DistanceRenderNodeBase
class DividerPlugin
class DownscalePass
class DummyCuller
struct ElementProducer
struct ElementProducer< RenderTarget, KeyType >
struct ElementProducer< ShaderProgram, KeyType >
struct ElementTyper
class Engine
class EnvironmentMap
class EnvironmentMapPass
class EnvironmentPrefilter
class EquirectangularToCube
class EventHandler
class Face
struct FaceIndices
struct FaceInfos
class Fog
class FontTexture
class ForwardRenderTechniquePass
class FrameListener
class Frustum
class FrustumCuller
class GaussianBlur
class GBufferBase
class GBufferT
class GeneratorPlugin
class GenericPlugin
class Geometry
struct GeometryBuffers
class GeometryInjectionPass
class GpInfoUbo
struct GpInfoUboConfiguration
Geometry pass data.
class GpuBuffer
struct GpuBufferBuddyAllocatorTraits
struct GpuBufferOffsetT
An offset and range of a GpuBuffer.
class GpuBufferPool
class GpuFrameEvent
class GpuFunctorEvent
class GpuInformations
Holds GPU informations.
class GpuObjectTracker
struct GpuUpdater
struct GroupAnimation
class HandlerEvent
class HdrConfig
class HdrConfigUbo
class IblTextures
class Icosahedron
class ImageBackground
class ImporterPlugin
class IndexMapping
class InstantiatedDummyCuller
class InstantiatedFrustumCuller
class InstantiationComponent
struct InstantiationData
struct InterleavedVertexT
Holds the all components of a vertex.
struct IntermediateView
Holds minimal data for an intermediate view.
class Interpolator
Template class which handles the interpolations, would it be quaternion, point, real, ... interpolations.
class InterpolatorT
Template class which handles the interpolations, would it be quaternion, point, real, ... interpolations.
class InterpolatorT< castor::Quaternion, InterpolatorType::eLinear >
Handles the Quaternion linear interpolations.
class InterpolatorT< DataT, InterpolatorType::eLinear >
Partial specialisation of InterpolatorT, for InterpolatorType::eLinear.
class InterpolatorT< DataT, InterpolatorType::eNearest >
Partial specialisation of InterpolatorT, for InterpolatorType::eNearest.
class KeyboardEvent
struct KeyboardState
Keyboard state.
class LayeredLightPropagationVolumesBase
class LayeredLightPropagationVolumesT
Lighting propagation volumes generation pass.
class LayeredLightVolumeGIPass
class LayeredLpvGridConfigUbo
struct LayeredLpvGridConfigUboConfiguration
Light propagation data.
class Light
class LightCategory
class LightFactory
class LightingPass
class LightInjectionPass
class LightPass
struct LightPassConfig
class LightPassLayeredVolumePropagationShadowT
Base class for all light passes with light propagation volumes.
class LightPassLayeredVolumePropagationShadowT< LightType::eDirectional >
class LightPassReflectiveShadow
Base class for all light passes with reflective shadow maps.
class LightPassResult
class LightPassShadow
Base class for all light passes with shadow.
struct LightPassShadowTraits
Traits structure to specialise light passes with shadows.
struct LightPassShadowTraits< LightType::eDirectional >
Traits structure to specialise light passes with shadows.
struct LightPassShadowTraits< LightType::ePoint >
Traits structure to specialise light passes with shadows.
struct LightPassShadowTraits< LightType::eSpot >
Traits structure to specialise light passes with shadows.
class LightPassVolumePropagationShadowT
Base class for all light passes with light propagation volumes.
class LightPropagationPass
class LightPropagationVolumesBase
class LightPropagationVolumesT
Lighting propagation volumes generation pass.
class LightVolumeGIPass
class LightVolumePassResult
class Line
class LineariseDepthPass
struct LineIndices
class LinesMapping
class log
struct LpvConfig
class LpvGridConfigUbo
struct LpvGridConfigUboConfiguration
Light propagation data.
class LpvLightConfigUbo
struct LpvLightConfigUboConfiguration
Light propagation data.
struct LpvLightPassConfigT
class Material
class MaterialCache
Material collection, with additional functions.
class MatrixUbo
struct MatrixUboConfiguration
Global matrices data.
struct MemChunk
A memory range, in bytes.
class Mesh
class MeshAnimation
class MeshAnimationInstance
class MeshAnimationInstanceSubmesh
class MeshAnimationKeyFrame
class MeshAnimationSubmesh
class MeshFactory
class MeshGenerator
class MeshImporter
class MeshImporterFactory
class MeshLightPass
class MeshSubdivider
class MetallicRoughnessPassBuffer
class MetallicRoughnessPbrPass
struct MipView
class ModelInstancesUbo
struct ModelInstancesUboConfiguration
Model matrices data.
class ModelMatrixUbo
struct ModelMatrixUboConfiguration
Model matrices data.
class ModelUbo
struct ModelUboConfiguration
Model data.
class MorphComponent
struct MorphingRenderNode
class MorphingUbo
struct MorphingUboConfiguration
Morphing data.
class MouseEvent
class MouseEventHandler
struct MouseState
Mouse state.
class MovableObject
class NonClientEventHandler
Description of an event handler, class that can receive event.
struct NonTexturedCube
struct NonTexturedQuad
class ObjectCache
Base class for a scene element cache.
class ObjectCache< BillboardList, castor::String >
BillboardList cache.
class ObjectCache< Geometry, castor::String >
Geometry cache.
class ObjectCache< Light, castor::String >
Light cache.
class ObjectCacheBase
Base class for a scene element cache.
struct ObjectCacheTraits
Helper structure to specialise a scene objects cache behaviour.
struct ObjectCacheTraits< BillboardList, KeyType >
Helper structure to specialise a scene objects cache behaviour.
struct ObjectCacheTraits< Camera, KeyType >
Helper structure to specialise a scene objects cache behaviour.
struct ObjectCacheTraits< Geometry, KeyType >
Helper structure to specialise a scene objects cache behaviour.
struct ObjectCacheTraits< Light, KeyType >
Helper structure to specialise a scene objects cache behaviour.
struct ObjectCacheTraits< ParticleSystem, KeyType >
Helper structure to specialise a scene objects cache behaviour.
struct ObjectCacheTraits< SceneNode, KeyType >
Helper structure to specialise a scene objects cache behaviour.
struct ObjectRenderNode
Helper structure used to render objects.
struct OldInterleavedVertexT
class OpaquePass
class OpaquePassResult
class OpaqueResolvePass
class Overlay
class OverlayCategory
struct OverlayCategorySort
Structure used to sort overlays by order.
class OverlayFactory
class OverlayRenderer
class OverlayUbo
struct OverlayUboConfiguration
Overlay data.
class OverlayVisitor
class PanelOverlay
class ParametersT
Configuration parameters.
class Particle
class ParticleDeclaration
struct ParticleElementDeclaration
class ParticleEmitter
class ParticlePlugin
class ParticleSystem
class ParticleSystemImpl
class ParticleUpdater
class Pass
class PassBuffer
struct PassRenderNode
struct PassTyper
Helper class to retrieve a pass type from a MaterialType.
struct PassTyper< MaterialType::eMetallicRoughness >
Helper class to retrieve a pass type from a MaterialType.
struct PassTyper< MaterialType::ePhong >
Helper class to retrieve a pass type from a MaterialType.
struct PassTyper< MaterialType::eSpecularGlossiness >
Helper class to retrieve a pass type from a MaterialType.
class Pattern
Pattern handler class.
class PhongPass
class PhongPassBuffer
class PickingPass
class PickingUbo
struct PickingUboConfiguration
Picking data.
struct PipelineFlags
Pipeline flags.
class PipelineVisitor
class PipelineVisitorBase
class Plane
class Plugin
class PluginException
class PointLight
class PointLightPass
class PoolUniformBuffer
class PostEffect
struct PostEffectSurface
class PostFxPlugin
class Projection
class RadianceComputer
class Ray
class ReflectiveShadowMapping
class RenderCube
class RenderDepthQuad
struct RenderDevice
class RenderedObject
class RenderGrid
class RenderGridBuilder
class RenderGridBuilderT
Used to create a RenderGrid variable.
struct RenderInfo
class RenderLoop
class RenderLoopAsync
class RenderLoopSync
struct RenderNodesT
The render nodes for a specific scene.
class RenderPassTimer
class RenderPassTimerBlock
class RenderPipeline
class RenderQuad
class RenderQuadBuilder
class RenderQuadBuilderT
Used to create a RenderQuad variable.
class RenderQueue
class RenderSystem
class RenderTarget
class RenderTargetCache
class RenderTechnique
class RenderTechniquePass
class RenderTechniqueVisitor
class RenderWindow
struct RsmConfig
class RsmConfigUbo
class RsmGIPass
class RsmInterpolatePass
struct RsmLightPassConfig
struct RsmUboConfiguration
Reflective Shadow Maps based GI UBO configuration.
class Sampler
class Scene
class SceneBackground
struct SceneCulledRenderNodes
class SceneCuller
class SceneFileContext
class SceneFileParser
class SceneNode
struct SceneRenderNode
struct SceneRenderNodes
class SceneRenderPass
class SceneUbo
struct SceneUboConfiguration
Scene data.
class ShaderBuffer
struct ShaderModule
A non compiled shader module, with its source.
class ShaderProgram
class ShaderProgramCache
struct ShadowConfig
class ShadowMap
class ShadowMapDirectional
class ShadowMapPass
class ShadowMapPassDirectional
class ShadowMapPassPoint
class ShadowMapPassSpot
class ShadowMapPoint
class ShadowMapResult
class ShadowMapSpot
class ShadowMapUbo
struct ShadowMapUboConfiguration
Shadow map data.
class Skeleton
class SkeletonAnimation
class SkeletonAnimationBone
class SkeletonAnimationInstance
class SkeletonAnimationInstanceBone
class SkeletonAnimationInstanceKeyFrame
class SkeletonAnimationInstanceNode
class SkeletonAnimationInstanceObject
class SkeletonAnimationKeyFrame
class SkeletonAnimationNode
class SkeletonAnimationObject
struct SkinningData
struct SkinningRenderNode
class SkinningUbo
struct SkinningUboConfiguration
Skinning data.
class SkyboxBackground
struct SliceView
class SpecularGlossinessPassBuffer
class SpecularGlossinessPbrPass
class Sphere
struct SpirVShader
A SPIR-V shader module, with SPIR-V binary and debug text source.
class SpotLight
class SpotLightPass
class SsaoBlurPass
struct SsaoConfig
class SsaoConfigUbo
class SsaoPass
class SsaoRawAOPass
struct StaticRenderNode
class StencilPass
class StructuredShaderBuffer
Wrapper class to select between SSBO or TBO.
class Submesh
struct SubmeshAnimationBufferT
class SubmeshComponent
struct SubmeshComponentAdder
class SubmeshUtils
Submesh utility functions.
struct SubmeshVertex
class SubsurfaceScattering
class SubsurfaceScatteringPass
class TextOverlay
class Texture3DTo2D
struct Texture3DTo2DData
class TextureAnimation
class TextureAnimationInstance
struct TextureConfiguration
Specifies the usages of a texture, per image component.
class TextureConfigurationBuffer
struct TexturedCube
struct TexturedQuad
struct TextureFactors
Factors applied when displaying a debug texture.
struct TextureFlagsId
class TextureLayout
class TextureProjection
class TextureProjectionToCube
class TextureSource
class TexturesUbo
struct TexturesUboConfiguration
Texture configuration data.
class TextureUnit
class TextureView
class ToneMapping
class ToneMappingPlugin
class ToneMappingVisitor
class Torus
class TransparentPass
class TransparentPassResult
class TransparentResolvePass
struct TransparentResolveProgram
class TriFaceMapping
class UniformBufferBase
struct UniformBufferOffsetT
A UniformBuffer and an offset from the GpuBuffer.
class UniformBufferPool
class UniformBufferPools
class UniformBufferT
A uniform typed buffer, than can contain multiple sub-buffers.
class UserInputEvent
Description of a user input event.
class UserInputListener
class Version
class VersionException
struct VertexBoneData
class Viewport
struct VkTypeTraits
struct VkTypeTraits< VkAccelerationStructureCreateInfoNV >
struct VkTypeTraits< VkAccelerationStructureInfoNV >
struct VkTypeTraits< VkAccelerationStructureMemoryRequirementsInfoNV >
struct VkTypeTraits< VkAcquireNextImageInfoKHR >
struct VkTypeTraits< VkApplicationInfo >
struct VkTypeTraits< VkAttachmentDescription2KHR >
struct VkTypeTraits< VkAttachmentReference2KHR >
struct VkTypeTraits< VkBindAccelerationStructureMemoryInfoNV >
struct VkTypeTraits< VkBindBufferMemoryDeviceGroupInfo >
struct VkTypeTraits< VkBindBufferMemoryInfo >
struct VkTypeTraits< VkBindImageMemoryDeviceGroupInfo >
struct VkTypeTraits< VkBindImageMemoryInfo >
struct VkTypeTraits< VkBindImageMemorySwapchainInfoKHR >
struct VkTypeTraits< VkBindImagePlaneMemoryInfo >
struct VkTypeTraits< VkBindSparseInfo >
struct VkTypeTraits< VkBufferCreateInfo >
struct VkTypeTraits< VkBufferDeviceAddressCreateInfoEXT >
struct VkTypeTraits< VkBufferDeviceAddressInfoEXT >
struct VkTypeTraits< VkBufferMemoryBarrier >
struct VkTypeTraits< VkBufferMemoryRequirementsInfo2 >
struct VkTypeTraits< VkBufferViewCreateInfo >
struct VkTypeTraits< VkCalibratedTimestampInfoEXT >
struct VkTypeTraits< VkCheckpointDataNV >
struct VkTypeTraits< VkCommandBufferAllocateInfo >
struct VkTypeTraits< VkCommandBufferBeginInfo >
struct VkTypeTraits< VkCommandBufferInheritanceConditionalRenderingInfoEXT >
struct VkTypeTraits< VkCommandBufferInheritanceInfo >
struct VkTypeTraits< VkCommandPoolCreateInfo >
struct VkTypeTraits< VkComputePipelineCreateInfo >
struct VkTypeTraits< VkConditionalRenderingBeginInfoEXT >
struct VkTypeTraits< VkCooperativeMatrixPropertiesNV >
struct VkTypeTraits< VkCopyDescriptorSet >
struct VkTypeTraits< VkDebugMarkerMarkerInfoEXT >
struct VkTypeTraits< VkDebugMarkerObjectNameInfoEXT >
struct VkTypeTraits< VkDebugMarkerObjectTagInfoEXT >
struct VkTypeTraits< VkDebugReportCallbackCreateInfoEXT >
struct VkTypeTraits< VkDebugUtilsLabelEXT >
struct VkTypeTraits< VkDebugUtilsMessengerCallbackDataEXT >
struct VkTypeTraits< VkDebugUtilsMessengerCreateInfoEXT >
struct VkTypeTraits< VkDebugUtilsObjectNameInfoEXT >
struct VkTypeTraits< VkDebugUtilsObjectTagInfoEXT >
struct VkTypeTraits< VkDedicatedAllocationBufferCreateInfoNV >
struct VkTypeTraits< VkDedicatedAllocationImageCreateInfoNV >
struct VkTypeTraits< VkDedicatedAllocationMemoryAllocateInfoNV >
struct VkTypeTraits< VkDescriptorPoolCreateInfo >
struct VkTypeTraits< VkDescriptorPoolInlineUniformBlockCreateInfoEXT >
struct VkTypeTraits< VkDescriptorSetAllocateInfo >
struct VkTypeTraits< VkDescriptorSetLayoutBindingFlagsCreateInfoEXT >
struct VkTypeTraits< VkDescriptorSetLayoutCreateInfo >
struct VkTypeTraits< VkDescriptorSetLayoutSupport >
struct VkTypeTraits< VkDescriptorSetVariableDescriptorCountAllocateInfoEXT >
struct VkTypeTraits< VkDescriptorSetVariableDescriptorCountLayoutSupportEXT >
struct VkTypeTraits< VkDescriptorUpdateTemplateCreateInfo >
struct VkTypeTraits< VkDeviceCreateInfo >
struct VkTypeTraits< VkDeviceEventInfoEXT >
struct VkTypeTraits< VkDeviceGroupBindSparseInfo >
struct VkTypeTraits< VkDeviceGroupCommandBufferBeginInfo >
struct VkTypeTraits< VkDeviceGroupDeviceCreateInfo >
struct VkTypeTraits< VkDeviceGroupPresentCapabilitiesKHR >
struct VkTypeTraits< VkDeviceGroupPresentInfoKHR >
struct VkTypeTraits< VkDeviceGroupRenderPassBeginInfo >
struct VkTypeTraits< VkDeviceGroupSubmitInfo >
struct VkTypeTraits< VkDeviceGroupSwapchainCreateInfoKHR >
struct VkTypeTraits< VkDeviceMemoryOverallocationCreateInfoAMD >
struct VkTypeTraits< VkDeviceQueueCreateInfo >
struct VkTypeTraits< VkDeviceQueueGlobalPriorityCreateInfoEXT >
struct VkTypeTraits< VkDeviceQueueInfo2 >
struct VkTypeTraits< VkDisplayEventInfoEXT >
struct VkTypeTraits< VkDisplayModeCreateInfoKHR >
struct VkTypeTraits< VkDisplayModeProperties2KHR >
struct VkTypeTraits< VkDisplayPlaneCapabilities2KHR >
struct VkTypeTraits< VkDisplayPlaneInfo2KHR >
struct VkTypeTraits< VkDisplayPlaneProperties2KHR >
struct VkTypeTraits< VkDisplayPowerInfoEXT >
struct VkTypeTraits< VkDisplayPresentInfoKHR >
struct VkTypeTraits< VkDisplayProperties2KHR >
struct VkTypeTraits< VkDisplaySurfaceCreateInfoKHR >
struct VkTypeTraits< VkDrmFormatModifierPropertiesListEXT >
struct VkTypeTraits< VkEventCreateInfo >
struct VkTypeTraits< VkExportFenceCreateInfo >
struct VkTypeTraits< VkExportMemoryAllocateInfo >
struct VkTypeTraits< VkExportMemoryAllocateInfoNV >
struct VkTypeTraits< VkExportSemaphoreCreateInfo >
struct VkTypeTraits< VkExternalBufferProperties >
struct VkTypeTraits< VkExternalFenceProperties >
struct VkTypeTraits< VkExternalImageFormatProperties >
struct VkTypeTraits< VkExternalMemoryBufferCreateInfo >
struct VkTypeTraits< VkExternalMemoryImageCreateInfo >
struct VkTypeTraits< VkExternalMemoryImageCreateInfoNV >
struct VkTypeTraits< VkExternalSemaphoreProperties >
struct VkTypeTraits< VkFenceCreateInfo >
struct VkTypeTraits< VkFenceGetFdInfoKHR >
struct VkTypeTraits< VkFilterCubicImageViewImageFormatPropertiesEXT >
struct VkTypeTraits< VkFormatProperties2 >
struct VkTypeTraits< VkFramebufferCreateInfo >
struct VkTypeTraits< VkGeometryAABBNV >
struct VkTypeTraits< VkGeometryNV >
struct VkTypeTraits< VkGeometryTrianglesNV >
struct VkTypeTraits< VkGraphicsPipelineCreateInfo >
struct VkTypeTraits< VkHdrMetadataEXT >
struct VkTypeTraits< VkImageCreateInfo >
struct VkTypeTraits< VkImageDrmFormatModifierExplicitCreateInfoEXT >
struct VkTypeTraits< VkImageDrmFormatModifierListCreateInfoEXT >
struct VkTypeTraits< VkImageDrmFormatModifierPropertiesEXT >
struct VkTypeTraits< VkImageFormatListCreateInfoKHR >
struct VkTypeTraits< VkImageFormatProperties2 >
struct VkTypeTraits< VkImageMemoryBarrier >
struct VkTypeTraits< VkImageMemoryRequirementsInfo2 >
struct VkTypeTraits< VkImagePlaneMemoryRequirementsInfo >
struct VkTypeTraits< VkImageSparseMemoryRequirementsInfo2 >
struct VkTypeTraits< VkImageStencilUsageCreateInfoEXT >
struct VkTypeTraits< VkImageSwapchainCreateInfoKHR >
struct VkTypeTraits< VkImageViewASTCDecodeModeEXT >
struct VkTypeTraits< VkImageViewCreateInfo >
struct VkTypeTraits< VkImageViewUsageCreateInfo >
struct VkTypeTraits< VkImportFenceFdInfoKHR >
struct VkTypeTraits< VkImportMemoryFdInfoKHR >
struct VkTypeTraits< VkImportMemoryHostPointerInfoEXT >
struct VkTypeTraits< VkImportSemaphoreFdInfoKHR >
struct VkTypeTraits< VkInstanceCreateInfo >
struct VkTypeTraits< VkMappedMemoryRange >
struct VkTypeTraits< VkMemoryAllocateFlagsInfo >
struct VkTypeTraits< VkMemoryAllocateInfo >
struct VkTypeTraits< VkMemoryBarrier >
struct VkTypeTraits< VkMemoryDedicatedAllocateInfo >
struct VkTypeTraits< VkMemoryDedicatedRequirements >
struct VkTypeTraits< VkMemoryFdPropertiesKHR >
struct VkTypeTraits< VkMemoryGetFdInfoKHR >
struct VkTypeTraits< VkMemoryHostPointerPropertiesEXT >
struct VkTypeTraits< VkMemoryPriorityAllocateInfoEXT >
struct VkTypeTraits< VkMemoryRequirements2 >
struct VkTypeTraits< VkMultisamplePropertiesEXT >
struct VkTypeTraits< VkPhysicalDevice16BitStorageFeatures >
struct VkTypeTraits< VkPhysicalDevice8BitStorageFeaturesKHR >
struct VkTypeTraits< VkPhysicalDeviceASTCDecodeFeaturesEXT >
struct VkTypeTraits< VkPhysicalDeviceBlendOperationAdvancedFeaturesEXT >
struct VkTypeTraits< VkPhysicalDeviceBlendOperationAdvancedPropertiesEXT >
struct VkTypeTraits< VkPhysicalDeviceBufferAddressFeaturesEXT >
struct VkTypeTraits< VkPhysicalDeviceComputeShaderDerivativesFeaturesNV >
struct VkTypeTraits< VkPhysicalDeviceConditionalRenderingFeaturesEXT >
struct VkTypeTraits< VkPhysicalDeviceConservativeRasterizationPropertiesEXT >
struct VkTypeTraits< VkPhysicalDeviceCooperativeMatrixFeaturesNV >
struct VkTypeTraits< VkPhysicalDeviceCooperativeMatrixPropertiesNV >
struct VkTypeTraits< VkPhysicalDeviceCornerSampledImageFeaturesNV >
struct VkTypeTraits< VkPhysicalDeviceDedicatedAllocationImageAliasingFeaturesNV >
struct VkTypeTraits< VkPhysicalDeviceDepthClipEnableFeaturesEXT >
struct VkTypeTraits< VkPhysicalDeviceDepthStencilResolvePropertiesKHR >
struct VkTypeTraits< VkPhysicalDeviceDescriptorIndexingFeaturesEXT >
struct VkTypeTraits< VkPhysicalDeviceDescriptorIndexingPropertiesEXT >
struct VkTypeTraits< VkPhysicalDeviceDiscardRectanglePropertiesEXT >
struct VkTypeTraits< VkPhysicalDeviceDriverPropertiesKHR >
struct VkTypeTraits< VkPhysicalDeviceExclusiveScissorFeaturesNV >
struct VkTypeTraits< VkPhysicalDeviceExternalBufferInfo >
struct VkTypeTraits< VkPhysicalDeviceExternalFenceInfo >
struct VkTypeTraits< VkPhysicalDeviceExternalImageFormatInfo >
struct VkTypeTraits< VkPhysicalDeviceExternalMemoryHostPropertiesEXT >
struct VkTypeTraits< VkPhysicalDeviceExternalSemaphoreInfo >
struct VkTypeTraits< VkPhysicalDeviceFeatures2 >
struct VkTypeTraits< VkPhysicalDeviceFloat16Int8FeaturesKHR >
struct VkTypeTraits< VkPhysicalDeviceFloatControlsPropertiesKHR >
struct VkTypeTraits< VkPhysicalDeviceFragmentDensityMapFeaturesEXT >
struct VkTypeTraits< VkPhysicalDeviceFragmentDensityMapPropertiesEXT >
struct VkTypeTraits< VkPhysicalDeviceFragmentShaderBarycentricFeaturesNV >
struct VkTypeTraits< VkPhysicalDeviceGroupProperties >
struct VkTypeTraits< VkPhysicalDeviceIDProperties >
struct VkTypeTraits< VkPhysicalDeviceImageDrmFormatModifierInfoEXT >
struct VkTypeTraits< VkPhysicalDeviceImageFormatInfo2 >
struct VkTypeTraits< VkPhysicalDeviceImageViewImageFormatInfoEXT >
struct VkTypeTraits< VkPhysicalDeviceInlineUniformBlockFeaturesEXT >
struct VkTypeTraits< VkPhysicalDeviceInlineUniformBlockPropertiesEXT >
struct VkTypeTraits< VkPhysicalDeviceMaintenance3Properties >
struct VkTypeTraits< VkPhysicalDeviceMemoryBudgetPropertiesEXT >
struct VkTypeTraits< VkPhysicalDeviceMemoryPriorityFeaturesEXT >
struct VkTypeTraits< VkPhysicalDeviceMemoryProperties2 >
struct VkTypeTraits< VkPhysicalDeviceMeshShaderFeaturesNV >
struct VkTypeTraits< VkPhysicalDeviceMeshShaderPropertiesNV >
struct VkTypeTraits< VkPhysicalDeviceMultiviewFeatures >
struct VkTypeTraits< VkPhysicalDeviceMultiviewPerViewAttributesPropertiesNVX >
struct VkTypeTraits< VkPhysicalDeviceMultiviewProperties >
struct VkTypeTraits< VkPhysicalDevicePCIBusInfoPropertiesEXT >
struct VkTypeTraits< VkPhysicalDevicePointClippingProperties >
struct VkTypeTraits< VkPhysicalDeviceProperties2 >
struct VkTypeTraits< VkPhysicalDeviceProtectedMemoryFeatures >
struct VkTypeTraits< VkPhysicalDeviceProtectedMemoryProperties >
struct VkTypeTraits< VkPhysicalDevicePushDescriptorPropertiesKHR >
struct VkTypeTraits< VkPhysicalDeviceRayTracingPropertiesNV >
struct VkTypeTraits< VkPhysicalDeviceRepresentativeFragmentTestFeaturesNV >
struct VkTypeTraits< VkPhysicalDeviceSampleLocationsPropertiesEXT >
struct VkTypeTraits< VkPhysicalDeviceSamplerFilterMinmaxPropertiesEXT >
struct VkTypeTraits< VkPhysicalDeviceSamplerYcbcrConversionFeatures >
struct VkTypeTraits< VkPhysicalDeviceScalarBlockLayoutFeaturesEXT >
struct VkTypeTraits< VkPhysicalDeviceShaderAtomicInt64FeaturesKHR >
struct VkTypeTraits< VkPhysicalDeviceShaderCorePropertiesAMD >
struct VkTypeTraits< VkPhysicalDeviceShaderDrawParameterFeatures >
struct VkTypeTraits< VkPhysicalDeviceShaderImageFootprintFeaturesNV >
struct VkTypeTraits< VkPhysicalDeviceShadingRateImageFeaturesNV >
struct VkTypeTraits< VkPhysicalDeviceShadingRateImagePropertiesNV >
struct VkTypeTraits< VkPhysicalDeviceSparseImageFormatInfo2 >
struct VkTypeTraits< VkPhysicalDeviceSubgroupProperties >
struct VkTypeTraits< VkPhysicalDeviceSurfaceInfo2KHR >
struct VkTypeTraits< VkPhysicalDeviceTransformFeedbackFeaturesEXT >
struct VkTypeTraits< VkPhysicalDeviceTransformFeedbackPropertiesEXT >
struct VkTypeTraits< VkPhysicalDeviceVariablePointerFeatures >
struct VkTypeTraits< VkPhysicalDeviceVertexAttributeDivisorFeaturesEXT >
struct VkTypeTraits< VkPhysicalDeviceVertexAttributeDivisorPropertiesEXT >
struct VkTypeTraits< VkPhysicalDeviceVulkanMemoryModelFeaturesKHR >
struct VkTypeTraits< VkPipelineCacheCreateInfo >
struct VkTypeTraits< VkPipelineColorBlendAdvancedStateCreateInfoEXT >
struct VkTypeTraits< VkPipelineColorBlendStateCreateInfo >
struct VkTypeTraits< VkPipelineCoverageModulationStateCreateInfoNV >
struct VkTypeTraits< VkPipelineCoverageToColorStateCreateInfoNV >
struct VkTypeTraits< VkPipelineDepthStencilStateCreateInfo >
struct VkTypeTraits< VkPipelineDiscardRectangleStateCreateInfoEXT >
struct VkTypeTraits< VkPipelineDynamicStateCreateInfo >
struct VkTypeTraits< VkPipelineInputAssemblyStateCreateInfo >
struct VkTypeTraits< VkPipelineLayoutCreateInfo >
struct VkTypeTraits< VkPipelineMultisampleStateCreateInfo >
struct VkTypeTraits< VkPipelineRasterizationConservativeStateCreateInfoEXT >
struct VkTypeTraits< VkPipelineRasterizationDepthClipStateCreateInfoEXT >
struct VkTypeTraits< VkPipelineRasterizationStateCreateInfo >
struct VkTypeTraits< VkPipelineRasterizationStateRasterizationOrderAMD >
struct VkTypeTraits< VkPipelineRasterizationStateStreamCreateInfoEXT >
struct VkTypeTraits< VkPipelineRepresentativeFragmentTestStateCreateInfoNV >
struct VkTypeTraits< VkPipelineSampleLocationsStateCreateInfoEXT >
struct VkTypeTraits< VkPipelineShaderStageCreateInfo >
struct VkTypeTraits< VkPipelineTessellationDomainOriginStateCreateInfo >
struct VkTypeTraits< VkPipelineTessellationStateCreateInfo >
struct VkTypeTraits< VkPipelineVertexInputDivisorStateCreateInfoEXT >
struct VkTypeTraits< VkPipelineVertexInputStateCreateInfo >
struct VkTypeTraits< VkPipelineViewportCoarseSampleOrderStateCreateInfoNV >
struct VkTypeTraits< VkPipelineViewportExclusiveScissorStateCreateInfoNV >
struct VkTypeTraits< VkPipelineViewportShadingRateImageStateCreateInfoNV >
struct VkTypeTraits< VkPipelineViewportStateCreateInfo >
struct VkTypeTraits< VkPipelineViewportSwizzleStateCreateInfoNV >
struct VkTypeTraits< VkPipelineViewportWScalingStateCreateInfoNV >
struct VkTypeTraits< VkPresentInfoKHR >
struct VkTypeTraits< VkPresentRegionsKHR >
struct VkTypeTraits< VkPresentTimesInfoGOOGLE >
struct VkTypeTraits< VkProtectedSubmitInfo >
struct VkTypeTraits< VkQueryPoolCreateInfo >
struct VkTypeTraits< VkQueueFamilyCheckpointPropertiesNV >
struct VkTypeTraits< VkQueueFamilyProperties2 >
struct VkTypeTraits< VkRayTracingPipelineCreateInfoNV >
struct VkTypeTraits< VkRayTracingShaderGroupCreateInfoNV >
struct VkTypeTraits< VkRenderPassBeginInfo >
struct VkTypeTraits< VkRenderPassCreateInfo >
struct VkTypeTraits< VkRenderPassCreateInfo2KHR >
struct VkTypeTraits< VkRenderPassFragmentDensityMapCreateInfoEXT >
struct VkTypeTraits< VkRenderPassInputAttachmentAspectCreateInfo >
struct VkTypeTraits< VkRenderPassMultiviewCreateInfo >
struct VkTypeTraits< VkRenderPassSampleLocationsBeginInfoEXT >
struct VkTypeTraits< VkSampleLocationsInfoEXT >
struct VkTypeTraits< VkSamplerCreateInfo >
struct VkTypeTraits< VkSamplerReductionModeCreateInfoEXT >
struct VkTypeTraits< VkSamplerYcbcrConversionCreateInfo >
struct VkTypeTraits< VkSamplerYcbcrConversionImageFormatProperties >
struct VkTypeTraits< VkSamplerYcbcrConversionInfo >
struct VkTypeTraits< VkSemaphoreCreateInfo >
struct VkTypeTraits< VkSemaphoreGetFdInfoKHR >
struct VkTypeTraits< VkShaderModuleCreateInfo >
struct VkTypeTraits< VkShaderModuleValidationCacheCreateInfoEXT >
struct VkTypeTraits< VkSharedPresentSurfaceCapabilitiesKHR >
struct VkTypeTraits< VkSparseImageFormatProperties2 >
struct VkTypeTraits< VkSparseImageMemoryRequirements2 >
struct VkTypeTraits< VkSubmitInfo >
struct VkTypeTraits< VkSubpassBeginInfoKHR >
struct VkTypeTraits< VkSubpassDependency2KHR >
struct VkTypeTraits< VkSubpassDescription2KHR >
struct VkTypeTraits< VkSubpassDescriptionDepthStencilResolveKHR >
struct VkTypeTraits< VkSubpassEndInfoKHR >
struct VkTypeTraits< VkSurfaceCapabilities2EXT >
struct VkTypeTraits< VkSurfaceCapabilities2KHR >
struct VkTypeTraits< VkSurfaceFormat2KHR >
struct VkTypeTraits< VkSwapchainCounterCreateInfoEXT >
struct VkTypeTraits< VkSwapchainCreateInfoKHR >
struct VkTypeTraits< VkTextureLODGatherFormatPropertiesAMD >
struct VkTypeTraits< VkValidationCacheCreateInfoEXT >
struct VkTypeTraits< VkValidationFeaturesEXT >
struct VkTypeTraits< VkValidationFlagsEXT >
struct VkTypeTraits< VkWriteDescriptorSet >
struct VkTypeTraits< VkWriteDescriptorSetAccelerationStructureNV >
struct VkTypeTraits< VkWriteDescriptorSetInlineUniformBlockEXT >
struct Voxel
class VoxelBufferToTexture
class VoxelizePass
class Voxelizer
class VoxelizerUbo
struct VoxelizerUboConfiguration
class VoxelSceneData
class VoxelSecondaryBounce
class WeightedBlendRendering
Typedefs
using OverlayCategorySet = std::set< OverlayCategorySPtr, OverlayCategorySort >
using DebugCallbacksPtr = std::unique_ptr< DebugCallbacks >
using LineArray = std::vector< Line >
using SceneRenderNodesPtr = castor::UniquePtr< SceneRenderNodes >
using SceneCulledRenderNodesPtr = castor::UniquePtr< SceneCulledRenderNodes >
using CombinePassConfig = CombinePassConfigT< ashes::Optional >
using CombinePassConfigData = CombinePassConfigT< rq::RawTypeT >
using TextureViewCRef = std::reference_wrapper< TextureView const >
using TextureViewCRefArray = std::vector< TextureViewCRef >
using DirectionalLightPassShadow = LightPassShadow< LightType::eDirectional >
using PointLightPassShadow = LightPassShadow< LightType::ePoint >
using SpotLightPassShadow = LightPassShadow< LightType::eSpot >
using FinalCombineProgramPtr = std::unique_ptr< TransparentResolveProgram >
using FinalCombineProgramMap = std::map< FogType, FinalCombineProgramPtr >
using SkeletonAnimationInstanceKeyFrameArray = std::vector< SkeletonAnimationInstanceKeyFrame >
Node
using SubmeshRenderNode = ObjectRenderNode< Submesh, Geometry >
using BillboardListRenderNode = ObjectRenderNode< BillboardBase, BillboardBase >
Enumerations
enum ChunkType : uint64_t {
ChunkType::eUnknown = makeChunkID(' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '), ChunkType::eCmshFile = makeChunkID('C', 'M', 'S', 'H', 'F', 'I', 'L', 'E'), ChunkType::eCmshHeader = makeChunkID('C', 'M', 'S', 'H', 'H', 'D', 'E', 'R'), ChunkType::eCmshVersion = makeChunkID('C', 'M', 'S', 'H', 'V', 'R', 'S', 'N'),
ChunkType::eName = makeChunkID('N', 'A', 'M', 'E', ' ', ' ', ' ', ' '), ChunkType::eMesh = makeChunkID('M', 'E', 'S', 'H', ' ', ' ', ' ', ' '), ChunkType::eSkeleton = makeChunkID('S', 'K', 'E', 'L', 'E', 'T', 'O', 'N'), ChunkType::eSkeletonGlobalInverse = makeChunkID('S', 'K', 'E', 'L', 'G', 'I', 'M', 'X'),
ChunkType::eSkeletonBone = makeChunkID('S', 'K', 'E', 'L', 'B', 'O', 'N', 'E'), ChunkType::eBoneParentName = makeChunkID('B', 'O', 'N', 'E', 'P', 'A', 'R', 'T'), ChunkType::eBoneOffsetMatrix = makeChunkID('B', 'O', 'N', 'E', 'O', 'M', 'T', 'X'), ChunkType::eSubmesh = makeChunkID('S', 'U', 'B', 'M', 'E', 'S', 'H', ' '),
ChunkType::eSubmeshTopology = makeChunkID('S', 'M', 'S', 'H', 'T', 'O', 'P', 'O'), ChunkType::eSubmeshVertexCount = makeChunkID('S', 'M', 'S', 'H', 'V', 'X', 'C', 'T'), ChunkType::eSubmeshVertex = makeChunkID('S', 'M', 'S', 'H', 'V', 'R', 'T', 'X'), ChunkType::eSubmeshBoneCount = makeChunkID('S', 'M', 'S', 'H', 'B', 'N', 'C', 'T'),
ChunkType::eSubmeshBones = makeChunkID('S', 'M', 'S', 'H', 'B', 'O', 'N', 'E'), ChunkType::eSubmeshMatrixCount = makeChunkID('S', 'M', 'S', 'H', 'M', 'X', 'C', 'T'), ChunkType::eSubmeshMatrices = makeChunkID('S', 'M', 'S', 'H', 'M', 'T', 'R', 'X'), ChunkType::eSubmeshFaceCount = makeChunkID('S', 'M', 'S', 'H', 'F', 'C', 'C', 'T'),
ChunkType::eSubmeshFaces = makeChunkID('S', 'M', 'S', 'H', 'F', 'A', 'C', 'E'), ChunkType::eAnimable = makeChunkID('A', 'N', 'I', 'M', 'A', 'B', 'L', 'E'), ChunkType::eAnimation = makeChunkID('A', 'N', 'M', 'A', 'T', 'I', 'O', 'N'), ChunkType::eAnimLength = makeChunkID('A', 'N', 'M', 'L', 'E', 'N', 'G', 'T'),
ChunkType::eSkeletonAnimation = makeChunkID('S', 'K', 'E', 'L', 'A', 'N', 'I', 'M'), ChunkType::eMeshAnimation = makeChunkID('M', 'E', 'S', 'H', 'A', 'N', 'I', 'M'), ChunkType::eAnimInterpolator = makeChunkID('A', 'N', 'M', 'I', 'N', 'T', 'E', 'R'), ChunkType::eAnimationObject = makeChunkID('A', 'N', 'S', 'K', 'O', 'B', 'J', 'T'),
ChunkType::eSkeletonAnimationNode = makeChunkID('A', 'N', 'S', 'K', 'N', 'O', 'D', 'E'), ChunkType::eSkeletonAnimationBone = makeChunkID('A', 'N', 'S', 'K', 'B', 'O', 'N', 'E'), ChunkType::eMovingTransform = makeChunkID('M', 'V', 'N', 'G', 'T', 'S', 'F', 'M'), ChunkType::eKeyframeCount = makeChunkID('K', 'F', 'R', 'M', 'C', 'O', 'N', 'T'),
ChunkType::eKeyframes = makeChunkID('K', 'E', 'Y', 'F', 'R', 'M', 'E', 'S'), ChunkType::eBonesComponent = makeChunkID('B', 'O', 'N', 'E', 'C', 'O', 'M', 'P'), ChunkType::eMeshAnimationKeyFrame = makeChunkID('M', 'S', 'A', 'N', 'K', 'F', 'R', 'M'), ChunkType::eMeshAnimationKeyFrameTime = makeChunkID('M', 'S', 'A', 'N', 'K', 'F', 'T', 'M'),
ChunkType::eMeshAnimationKeyFrameSubmeshID = makeChunkID('M', 'S', 'A', 'N', 'K', 'F', 'I', 'D'), ChunkType::eMeshAnimationKeyFrameBufferSize = makeChunkID('M', 'H', 'A', 'N', 'K', 'F', 'S', 'Z'), ChunkType::eMeshAnimationKeyFrameBufferData = makeChunkID('M', 'H', 'A', 'N', 'K', 'F', 'D', 'T'), ChunkType::eSkeletonAnimationKeyFrame = makeChunkID('S', 'K', 'A', 'N', 'K', 'F', 'R', 'M'),
ChunkType::eSkeletonAnimationKeyFrameTime = makeChunkID('S', 'K', 'A', 'N', 'K', 'F', 'T', 'M'), ChunkType::eSkeletonAnimationKeyFrameObjectType = makeChunkID('S', 'K', 'A', 'N', 'K', 'F', 'O', 'Y'), ChunkType::eSkeletonAnimationKeyFrameObjectName = makeChunkID('S', 'K', 'A', 'N', 'K', 'F', 'O', 'N'), ChunkType::eSkeletonAnimationKeyFrameObjectTransform = makeChunkID('S', 'K', 'A', 'N', 'K', 'F', 'O', 'T'),
ChunkType::eSubmeshIndexComponentCount = makeChunkID('S', 'M', 'F', 'C', 'C', 'P', 'C', 'T'), ChunkType::eSubmeshIndexCount = makeChunkID('S', 'M', 'S', 'H', 'I', 'C', 'C', 'T'), ChunkType::eSubmeshIndices = makeChunkID('S', 'M', 'S', 'H', 'I', 'D', 'C', 'S')
}
Binary data chunk types enumeration.
enum CSCNSection : uint32_t {
CSCNSection::eRoot = CU_MakeSectionName('R', 'O', 'O', 'T'), CSCNSection::eScene = CU_MakeSectionName('S', 'C', 'N', 'E'), CSCNSection::eWindow = CU_MakeSectionName('W', 'N', 'D', 'W'), CSCNSection::eSampler = CU_MakeSectionName('S', 'M', 'P', 'R'),
CSCNSection::eCamera = CU_MakeSectionName('C', 'A', 'M', 'R'), CSCNSection::eViewport = CU_MakeSectionName('V', 'W', 'P', 'T'), CSCNSection::eLight = CU_MakeSectionName('L', 'G', 'H', 'T'), CSCNSection::eNode = CU_MakeSectionName('N', 'O', 'D', 'E'),
CSCNSection::eObject = CU_MakeSectionName('O', 'B', 'J', 'T'), CSCNSection::eObjectMaterials = CU_MakeSectionName('O', 'M', 'T', 'L'), CSCNSection::eFont = CU_MakeSectionName('F', 'O', 'N', 'T'), CSCNSection::ePanelOverlay = CU_MakeSectionName('P', 'O', 'V', 'L'),
CSCNSection::eBorderPanelOverlay = CU_MakeSectionName('B', 'O', 'V', 'L'), CSCNSection::eTextOverlay = CU_MakeSectionName('T', 'O', 'V', 'L'), CSCNSection::eMesh = CU_MakeSectionName('M', 'E', 'S', 'H'), CSCNSection::eSubmesh = CU_MakeSectionName('S', 'M', 'S', 'H'),
CSCNSection::eMaterial = CU_MakeSectionName('M', 'T', 'R', 'L'), CSCNSection::ePass = CU_MakeSectionName('P', 'A', 'S', 'S'), CSCNSection::eTextureUnit = CU_MakeSectionName('U', 'N', 'I', 'T'), CSCNSection::eRenderTarget = CU_MakeSectionName('R', 'T', 'G', 'R'),
CSCNSection::eShaderProgram = CU_MakeSectionName('G', 'L', 'S', 'L'), CSCNSection::eShaderStage = CU_MakeSectionName('S', 'P', 'G', 'M'), CSCNSection::eShaderUBO = CU_MakeSectionName('S', 'U', 'B', 'O'), CSCNSection::eUBOVariable = CU_MakeSectionName('S', 'U', 'B', 'V'),
CSCNSection::eBillboard = CU_MakeSectionName('B', 'L', 'B', 'd'), CSCNSection::eBillboardList = CU_MakeSectionName('B', 'L', 'B', 'L'), CSCNSection::eAnimGroup = CU_MakeSectionName('A', 'N', 'G', 'P'), CSCNSection::eAnimation = CU_MakeSectionName('A', 'N', 'M', 'T'),
CSCNSection::eSkybox = CU_MakeSectionName('S', 'K', 'B', 'X'), CSCNSection::eParticleSystem = CU_MakeSectionName('P', 'L', 'S', 'M'), CSCNSection::eParticle = CU_MakeSectionName('P', 'T', 'C', 'L'), CSCNSection::eSsao = CU_MakeSectionName('S', 'S', 'A', 'O'),
CSCNSection::eSubsurfaceScattering = CU_MakeSectionName('S', 'S', 'S', 'G'), CSCNSection::eTransmittanceProfile = CU_MakeSectionName('T', 'R', 'P', 'R'), CSCNSection::eHdrConfig = CU_MakeSectionName('H', 'D', 'R', 'C'), CSCNSection::eShadows = CU_MakeSectionName('S', 'H', 'D', 'W'),
CSCNSection::eMeshDefaultMaterials = CU_MakeSectionName('M', 'M', 'T', 'L'), CSCNSection::eRsm = CU_MakeSectionName('R', 'F', 'S', 'M'), CSCNSection::eLpv = CU_MakeSectionName('L', 'P', 'V', 'I'), CSCNSection::eRaw = CU_MakeSectionName('R', 'A', 'W', 'S'),
CSCNSection::ePcf = CU_MakeSectionName('P', 'C', 'F', 'S'), CSCNSection::eVsm = CU_MakeSectionName('V', 'S', 'M', 'S'), CSCNSection::eTextureAnimation = CU_MakeSectionName('T', 'X', 'A', 'N'), CSCNSection::eVoxelConeTracing = CU_MakeSectionName('V', 'C', 'T', 'C')
}
Defines all the sections and subsections of a scene file.
Functions
constexpr uint32_t makeCmshVersion (uint32_t maj, uint32_t min, uint32_t rev)
constexpr uint32_t getCmshMajor (uint32_t version)
constexpr uint32_t getCmshMinor (uint32_t version)
constexpr uint32_t getCmshRevision (uint32_t version)
uint64_t constexpr makeChunkID (char a, char b, char c, char d, char e, char f, char g, char h)
static void prepareChunkData (ChunkType &value)
Sets given value to big endian.
static uint8_t const * getBuffer (bool const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (bool &value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (int8_t const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (int8_t &value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (uint8_t const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (uint8_t &value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (int16_t const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (int16_t &value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (uint16_t const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (uint16_t &value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (int32_t const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (int32_t &value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (uint32_t const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (uint32_t &value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (int64_t const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (int64_t &value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (uint64_t const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (uint64_t &value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (float const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (float &value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (double const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (double &value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (long double const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (long double &value)
Retrieves the beginning of the buffer for given value.
template<typename T >
static size_t getDataSize (T const &value)
Retrieves the value binary size.
template<typename T >
static uint8_t const * getBuffer (std::vector< T > const &value)
Retrieves the beginning of the buffer for given value.
template<typename T >
static uint8_t * getBuffer (std::vector< T > &value)
Retrieves the beginning of the buffer for given value.
template<typename T >
static size_t getDataSize (std::vector< T > const &value)
Retrieves the value binary size.
template<typename T , size_t Count>
static uint8_t const * getBuffer (std::array< T, Count > const &value)
Retrieves the beginning of the buffer for given value.
template<typename T , size_t Count>
static uint8_t * getBuffer (std::array< T, Count > &value)
Retrieves the beginning of the buffer for given value.
template<typename T , size_t Count>
static size_t getDataSize (std::array< T, Count > const &value)
Retrieves the value binary size.
template<typename T , uint32_t Count>
static uint8_t const * getBuffer (castor::Point< T, Count > const &value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Count>
static uint8_t * getBuffer (castor::Point< T, Count > &value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Count>
static size_t getDataSize (castor::Point< T, Count > const &value)
Retrieves the value binary size.
template<typename T , uint32_t Count>
static uint8_t const * getBuffer (castor::Coords< T, Count > const &value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Count>
static uint8_t * getBuffer (castor::Coords< T, Count > &value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Count>
static size_t getDataSize (castor::Coords< T, Count > const &value)
Retrieves the value binary size.
template<typename T , uint32_t Columns, uint32_t Rows>
static uint8_t const * getBuffer (castor::Matrix< T, Columns, Rows > const &value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Columns, uint32_t Rows>
static uint8_t * getBuffer (castor::Matrix< T, Columns, Rows > &value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Columns, uint32_t Rows>
static size_t getDataSize (castor::Matrix< T, Columns, Rows > const &value)
Retrieves the value binary size.
template<typename T , uint32_t Count>
static uint8_t const * getBuffer (castor::SquareMatrix< T, Count > const &value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Count>
static uint8_t * getBuffer (castor::SquareMatrix< T, Count > &value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Count>
static size_t getDataSize (castor::SquareMatrix< T, Count > const &value)
Retrieves the value binary size.
static uint8_t const * getBuffer (castor::RgbColour const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (castor::RgbColour &value)
Retrieves the beginning of the buffer for given value.
static size_t getDataSize (castor::RgbColour const &value)
Retrieves the value binary size.
static uint8_t const * getBuffer (castor::RgbaColour const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (castor::RgbaColour &value)
Retrieves the beginning of the buffer for given value.
static size_t getDataSize (castor::RgbaColour const &value)
Retrieves the value binary size.
static uint8_t const * getBuffer (castor::Size const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (castor::Size &value)
Retrieves the beginning of the buffer for given value.
static size_t getDataSize (castor::Size const &value)
Retrieves the value binary size.
static uint8_t const * getBuffer (castor::Position const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (castor::Position &value)
Retrieves the beginning of the buffer for given value.
static size_t getDataSize (castor::Position const &value)
Retrieves the value binary size.
template<typename T >
static uint8_t const * getBuffer (castor::QuaternionT< T > const &value)
Retrieves the beginning of the buffer for given value.
template<typename T >
static uint8_t * getBuffer (castor::QuaternionT< T > &value)
Retrieves the beginning of the buffer for given value.
template<typename T >
static size_t getDataSize (castor::QuaternionT< T > const &value)
Retrieves the value binary size.
static void prepareChunkData (bool &value)
Sets given value to big endian.
static void prepareChunkData (int8_t &value)
Sets given value to big endian.
static void prepareChunkData (uint8_t &value)
Sets given value to big endian.
static void prepareChunkData (int16_t &value)
Sets given value to big endian.
static void prepareChunkData (uint16_t &value)
Sets given value to big endian.
static void prepareChunkData (int32_t &value)
Sets given value to big endian.
static void prepareChunkData (uint32_t &value)
Sets given value to big endian.
static void prepareChunkData (int64_t &value)
Sets given value to big endian.
static void prepareChunkData (uint64_t &value)
Sets given value to big endian.
static void prepareChunkData (float &value)
Sets given value to big endian.
static void prepareChunkData (double &value)
Sets given value to big endian.
static void prepareChunkData (long double &value)
Sets given value to big endian.
template<typename T >
static void prepareChunkData (std::vector< T > &values)
Sets given value to big endian.
template<typename T , size_t Count>
static void prepareChunkData (std::array< T, Count > &values)
Sets given value to big endian.
template<typename T , uint32_t Count>
static void prepareChunkData (castor::SquareMatrix< T, Count > &value)
Sets given value to big endian.
template<typename T , uint32_t Count>
static void prepareChunkData (castor::Point< T, Count > &value)
Sets given value to big endian.
template<typename T , uint32_t Count>
static void prepareChunkData (castor::Coords< T, Count > &value)
Sets given value to big endian.
template<typename T >
static void prepareChunkData (castor::QuaternionT< T > &value)
Sets given value to big endian.
static void prepareChunkData (castor::ColourComponent &value)
Sets given value to big endian.
static void prepareChunkData (castor::RgbColour &value)
Sets given value to big endian.
static void prepareChunkData (castor::RgbaColour &value)
Sets given value to big endian.
template<typename T >
static void prepareChunkData (OldInterleavedVertexT< T > &value)
Sets given value to big endian.
template<typename T >
static void prepareChunkData (InterleavedVertexT< T > &value)
Sets given value to big endian.
template<typename T >
static void prepareChunkData (SubmeshAnimationBufferT< T > &value)
Sets given value to big endian.
static void prepareChunkData (FaceIndices &value)
Sets given value to big endian.
static void prepareChunkData (LineIndices &value)
Sets given value to big endian.
static void prepareChunkData (VertexBoneData &value)
Sets given value to big endian.
template<typename T >
ashes::BufferPtr< T > makeBuffer (RenderDevice const &device, VkDeviceSize count, VkBufferUsageFlags usage, VkMemoryPropertyFlags flags, std::string const &name, ashes::QueueShare sharingMode={})
ashes::BufferBasePtr makeBufferBase (RenderDevice const &device, VkDeviceSize size, VkBufferUsageFlags usage, VkMemoryPropertyFlags flags, std::string const &name, ashes::QueueShare sharingMode={})
template<typename T >
ashes::VertexBufferPtr< T > makeVertexBuffer (RenderDevice const &device, VkDeviceSize count, VkBufferUsageFlags usage, VkMemoryPropertyFlags flags, std::string const &name, ashes::QueueShare sharingMode={})
ashes::VertexBufferBasePtr makeVertexBufferBase (RenderDevice const &device, VkDeviceSize size, VkBufferUsageFlags usage, VkMemoryPropertyFlags flags, std::string const &name, ashes::QueueShare sharingMode={})
PoolUniformBufferUPtr makePoolUniformBuffer (RenderSystem const &renderSystem, castor::ArrayView< uint8_t > data, VkBufferUsageFlags usage, VkMemoryPropertyFlags flags, std::string name, ashes::QueueShare sharingMode={})
template<typename DataT >
UniformBufferUPtrT< DataT > makeUniformBuffer (RenderSystem const &renderSystem, VkDeviceSize count, VkBufferUsageFlags usage, VkMemoryPropertyFlags flags, std::string name, ashes::QueueShare sharingMode={})
UniformBufferBaseUPtr makeUniformBufferBase (RenderSystem const &renderSystem, VkDeviceSize count, VkDeviceSize size, VkBufferUsageFlags usage, VkMemoryPropertyFlags flags, std::string name, ashes::QueueShare sharingMode={})
C3D_API size_t hash (BillboardBase const &billboard, Pass const &pass)
C3D_API size_t hash (BillboardBase const &billboard, Pass const &pass, uint32_t instanceMult)
template<typename ElementType , typename KeyType >
std::unique_ptr< Cache< ElementType, KeyType > > makeCache (Engine &engine, typename CacheTraits< ElementType, KeyType >::Producer &&produce, ElementInitialiser< ElementType > &&initialise=[](std::shared_ptr< ElementType >){}, ElementCleaner< ElementType > &&clean=[](std::shared_ptr< ElementType >){}, typename CacheTraits< ElementType, KeyType >::Merger &&merge=[](CacheBase< ElementType, KeyType > const &, castor::Collection< ElementType, KeyType > &, std::shared_ptr< ElementType >){})
Creates a cache.
C3D_API size_t hash (Geometry const &geometry, Submesh const &submesh, Pass const &pass)
C3D_API size_t hash (Geometry const &geometry, Submesh const &submesh, Pass const &pass, uint32_t instanceMult)
template<typename ElementType , typename KeyType >
std::unique_ptr< ObjectCache< ElementType, KeyType > > makeObjectCache (Engine &engine, Scene &scene, SceneNodeSPtr rootNode, SceneNodeSPtr rootCameraNode, SceneNodeSPtr rootObjectNode, typename ObjectCacheTraits< ElementType, KeyType >::Producer &&produce, ElementInitialiser< ElementType > &&initialise=[](std::shared_ptr< ElementType >){}, ElementCleaner< ElementType > &&clean=[](std::shared_ptr< ElementType >){}, typename ObjectCacheTraits< ElementType, KeyType >::Merger &&merge=[](ObjectCacheBase< ElementType, KeyType > const &, castor::Collection< ElementType, KeyType > &, std::shared_ptr< ElementType >, SceneNodeSPtr, SceneNodeSPtr){}, ElementAttacher< ElementType > &&attach=[](std::shared_ptr< ElementType >, SceneNode &, SceneNodeSPtr, SceneNodeSPtr, SceneNodeSPtr){}, ElementDetacher< ElementType > &&detach=[](std::shared_ptr< ElementType >){})
Creates an object cache.
std::unique_ptr< ShaderProgramCache > makeCache (Engine &engine)
Creates a ashes::ShaderProgram cache.
CU_DeclareSmartPtr (Engine)
castor::LoggerInstance & getLogger (Engine &engine)
castor::Matrix4x4f convert (std::array< float, 16 > const &value)
VkClearColorValue convert (castor::RgbaColour const &value)
castor::RgbaColour convert (VkClearColorValue const &value)
std::array< float, 4u > makeFloatArray (castor::RgbaColour const &value)
CU_DeclareVector (float, Float)
CU_DeclareMap (uint32_t, int, IntUInt)
CU_DeclareMap (castor::String, int, IntStr)
CU_DeclareMap (int, castor::String, StrInt)
VkDescriptorSetLayoutBinding makeDescriptorSetLayoutBinding (uint32_t binding, VkDescriptorType descriptorType, VkShaderStageFlags stageFlags, uint32_t descriptorCount=1u, VkSampler const *pImmutableSamplers=nullptr)
VkExtent2D makeExtent2D (castor::Coords2ui const &size)
VkExtent2D makeExtent2D (castor::Point2ui const &size)
VkExtent3D makeExtent3D (castor::Coords2ui const &size)
VkExtent3D makeExtent3D (castor::Point2ui const &size)
VkOffset2D makeOffset2D (castor::Coords2i const &pos)
VkOffset2D makeOffset2D (castor::Point2i const &pos)
VkOffset3D makeOffset3D (castor::Coords2i const &pos)
VkOffset3D makeOffset3D (castor::Point2i const &pos)
VkViewport makeViewport (castor::Coords2ui const &size, float zMin=0.0f, float zMax=1.0f)
VkViewport makeViewport (castor::Point2ui const &size, float zMin=0.0f, float zMax=1.0f)
VkViewport makeViewport (castor::Coords2i const &pos, castor::Coords2ui const &size, float zMin=0.0f, float zMax=1.0f)
VkViewport makeViewport (castor::Point2i const &pos, castor::Coords2ui const &size, float zMin=0.0f, float zMax=1.0f)
VkViewport makeViewport (castor::Coords2i const &pos, castor::Point2ui const &size, float zMin=0.0f, float zMax=1.0f)
VkViewport makeViewport (castor::Point2i const &pos, castor::Point2ui const &size, float zMin=0.0f, float zMax=1.0f)
VkRect2D makeScissor (castor::Coords2ui const &size)
VkRect2D makeScissor (castor::Point2ui const &size)
VkRect2D makeScissor (castor::Coords2i const &pos, castor::Coords2ui const &size)
VkRect2D makeScissor (castor::Point2i const &pos, castor::Coords2ui const &size)
VkRect2D makeScissor (castor::Coords2i const &pos, castor::Point2ui const &size)
VkRect2D makeScissor (castor::Point2i const &pos, castor::Point2ui const &size)
VkClearValue makeClearValue (float depth, uint32_t stencil=0u)
VkClearValue makeClearValue (float r, float g, float b, float a=1.0f)
bool operator> (VkImageSubresourceRange const &lhs, VkImageSubresourceRange const &rhs)
bool operator< (VkImageSubresourceRange const &lhs, VkImageSubresourceRange const &rhs)
bool operator<= (VkImageSubresourceRange const &lhs, VkImageSubresourceRange const &rhs)
bool operator>= (VkImageSubresourceRange const &lhs, VkImageSubresourceRange const &rhs)
bool operator!= (VkImageSubresourceRange const &lhs, VkImageSubresourceRange const &rhs)
bool operator== (VkImageSubresourceRange const &lhs, VkImageSubresourceRange const &rhs)
template<typename T >
std::unique_ptr< CpuFunctorEvent > makeCpuCleanupEvent (T &object)
Helper function to create a cleanup event.
template<typename T >
std::unique_ptr< GpuFunctorEvent > makeGpuCleanupEvent (T &object)
Helper function to create a cleanup event.
std::unique_ptr< CpuFunctorEvent > makeCpuFunctorEvent (EventType type, CpuFunctorEvent::Functor functor)
Helper function to create a functor event.
std::unique_ptr< GpuFunctorEvent > makeGpuFunctorEvent (EventType type, GpuFunctorEvent::Functor functor)
Helper function to create a functor event.
template<typename T >
std::unique_ptr< CpuFunctorEvent > makeCpuInitialiseEvent (T &object)
Helper function to create an initialise event.
template<typename T >
std::unique_ptr< GpuFunctorEvent > makeGpuInitialiseEvent (T &object)
Helper function to create an initialise event.
SamplerSPtr createSampler (Engine &engine, castor::String const &baseName, VkFilter filter, VkImageSubresourceRange const *range)
C3D_API TextureFlags getFlags (TextureConfiguration const &config)
C3D_API TextureLayoutSPtr createTextureLayout (Engine const &engine, castor::Path const &relative, castor::Path const &folder)
C3D_API TextureLayoutSPtr createTextureLayout (Engine const &engine, castor::String const &name, castor::PxBufferBaseUPtr buffer, bool isStatic=false)
C3D_API uint32_t getMipLevels (VkExtent3D const &extent)
ashes::ImagePtr makeImage (RenderDevice const &device, ashes::ImageCreateInfo createInfo, VkMemoryPropertyFlags flags, std::string const &name)
template<typename ResT >
ashes::DeviceMemoryPtr setupMemory (ashes::Device const &device, ResT &resource, VkMemoryPropertyFlags flags, std::string const &name)
template<typename ResT >
ashes::DeviceMemoryPtr setupMemory (RenderDevice const &device, ResT &resource, VkMemoryPropertyFlags flags, std::string const &name)
C3D_API std::ostream & operator<< (std::ostream &stream, GpuInformations const &object)
Output stream operator.
template<typename VkType , typename ... Params>
VkType makeVkType (Params &&... params)
C3D_API bool operator== (castor3d::Version const &a, castor3d::Version const &b)
Equality operator.
C3D_API bool operator!= (castor3d::Version const &a, castor3d::Version const &b)
Difference operator.
C3D_API bool operator< (castor3d::Version const &a, castor3d::Version const &b)
Less than operator.
C3D_API bool operator> (castor3d::Version const &a, castor3d::Version const &b)
Less than operator.
C3D_API bool operator<= (castor3d::Version const &a, castor3d::Version const &b)
Less than operator.
C3D_API bool operator>= (castor3d::Version const &a, castor3d::Version const &b)
Less than operator.
C3D_API std::ostream & operator<< (std::ostream &stream, castor3d::Version const &version)
C3D_API std::wostream & operator<< (std::wostream &stream, castor3d::Version const &version)
C3D_API castor::String & operator<< (castor::String &stream, castor3d::Version const &version)
std::ostream & operator<< (std::ostream &o, Cone const &c)
std::ostream & operator<< (std::ostream &o, Cube const &c)
std::ostream & operator<< (std::ostream &o, Cylinder const &c)
std::ostream & operator<< (std::ostream &o, Icosahedron const &c)
std::ostream & operator<< (std::ostream &o, Plane const &c)
std::ostream & operator<< (std::ostream &o, Projection const &c)
std::ostream & operator<< (std::ostream &o, Sphere const &c)
size_t hash (CulledSubmesh const &culled)
size_t hash (CulledSubmesh const &culled, uint32_t instanceMult)
bool isVisible (Camera const &camera, CulledSubmesh const &node)
bool isVisible (Frustum const &frustum, CulledSubmesh const &node)
size_t hash (CulledBillboard const &culled)
size_t hash (CulledBillboard const &culled, uint32_t instanceMult)
bool isVisible (Camera const &camera, CulledBillboard const &node)
bool isVisible (Frustum const &frustum, CulledBillboard const &node)
template<typename NodeType >
std::unique_ptr< DistanceRenderNodeBase > makeDistanceNode (NodeType &node)
CU_DeclareMultimap (double, StaticRenderNode *, StaticRenderNodePtrByDistance)
CU_DeclareMultimap (double, SkinningRenderNode *, SkinningRenderNodePtrByDistance)
CU_DeclareMultimap (double, MorphingRenderNode *, MorphingRenderNodePtrByDistance)
CU_DeclareMultimap (double, BillboardRenderNode *, BillboardRenderNodePtrByDistance)
CU_DeclareVector (StaticRenderNode *, StaticRenderNodePtr)
CU_DeclareVector (SkinningRenderNode *, SkinningRenderNodePtr)
CU_DeclareVector (MorphingRenderNode *, MorphingRenderNodePtr)
CU_DeclareVector (BillboardRenderNode *, BillboardRenderNodePtr)
CU_DeclareMap (RenderPipelineRPtr, StaticRenderNodePtrArray, StaticRenderNodesPtrByPipeline)
CU_DeclareMap (RenderPipelineRPtr, SkinningRenderNodePtrArray, SkinningRenderNodesPtrByPipeline)
CU_DeclareMap (RenderPipelineRPtr, MorphingRenderNodePtrArray, MorphingRenderNodesPtrByPipeline)
CU_DeclareMap (RenderPipelineRPtr, BillboardRenderNodePtrArray, BillboardRenderNodesPtrByPipeline)
CU_DeclareMap (SubmeshRPtr, StaticRenderNodePtrArray, SubmeshStaticRenderNodesPtr)
CU_DeclareMap (SubmeshRPtr, SkinningRenderNodePtrArray, SubmeshSkinningRenderNodesPtr)
CU_DeclareMap (PassRPtr, SubmeshStaticRenderNodesPtrMap, SubmeshStaticRenderNodesPtrByPass)
CU_DeclareMap (PassRPtr, SubmeshSkinningRenderNodesPtrMap, SubmeshSkinninRenderNodesPtrByPass)
CU_DeclareMap (RenderPipelineRPtr, SubmeshStaticRenderNodesPtrByPassMap, SubmeshStaticRenderNodesPtrByPipeline)
CU_DeclareMap (RenderPipelineRPtr, SubmeshSkinninRenderNodesPtrByPassMap, SubmeshSkinningRenderNodesPtrByPipeline)
CU_DeclareMultimap (double, StaticRenderNode, StaticRenderNodeByDistance)
CU_DeclareMultimap (double, SkinningRenderNode, SkinningRenderNodeByDistance)
CU_DeclareMultimap (double, MorphingRenderNode, MorphingRenderNodeByDistance)
CU_DeclareMultimap (double, BillboardRenderNode, BillboardRenderNodeByDistance)
CU_DeclareMap (CulledSubmesh const *, StaticRenderNode, StaticRenderNode)
CU_DeclareMap (CulledSubmesh const *, SkinningRenderNode, SkinningRenderNode)
CU_DeclareMap (CulledSubmesh const *, MorphingRenderNode, MorphingRenderNode)
CU_DeclareMap (CulledBillboard const *, BillboardRenderNode, BillboardRenderNode)
CU_DeclareMap (RenderPipelineRPtr, StaticRenderNodeMap, StaticRenderNodesByPipeline)
CU_DeclareMap (RenderPipelineRPtr, SkinningRenderNodeMap, SkinningRenderNodesByPipeline)
CU_DeclareMap (RenderPipelineRPtr, MorphingRenderNodeMap, MorphingRenderNodesByPipeline)
CU_DeclareMap (RenderPipelineRPtr, BillboardRenderNodeMap, BillboardRenderNodesByPipeline)
CU_DeclareMap (SubmeshRPtr, StaticRenderNodeMap, SubmeshStaticRenderNodes)
CU_DeclareMap (SubmeshRPtr, SkinningRenderNodeMap, SubmeshSkinningRenderNodes)
CU_DeclareMap (PassRPtr, SubmeshStaticRenderNodesMap, SubmeshStaticRenderNodesByPass)
CU_DeclareMap (PassRPtr, SubmeshSkinningRenderNodesMap, SubmeshSkinninRenderNodesByPass)
CU_DeclareMap (RenderPipelineRPtr, SubmeshStaticRenderNodesByPassMap, SubmeshStaticRenderNodesByPipeline)
CU_DeclareMap (RenderPipelineRPtr, SubmeshSkinninRenderNodesByPassMap, SubmeshSkinningRenderNodesByPipeline)
C3D_API bool operator== (DirectionalLightCascade const &lhs, DirectionalLightCascade const &rhs)
bool operator!= (DirectionalLightCascade const &lhs, DirectionalLightCascade const &rhs)
VkDeviceSize getSize (ParticleFormat format)
C3D_API bool operator== (ParticleDeclaration const &lhs, ParticleDeclaration const &rhs)
Equality operator.
C3D_API bool operator!= (ParticleDeclaration const &lhs, ParticleDeclaration const &rhs)
Equality operator.
bool operator== (ParticleElementDeclaration const &lhs, ParticleElementDeclaration const &rhs)
Equality operator.
bool operator!= (ParticleElementDeclaration const &lhs, ParticleElementDeclaration const &rhs)
Equality operator.
C3D_API void initialiseGlslang ()
Initialises glslang globals.
C3D_API void cleanupGlslang ()
Cleans up glslang globals.
C3D_API UInt32Array compileGlslToSpv (RenderDevice const &device, VkShaderStageFlagBits stage, std::string const &shader)
Transpiles a GLSL shader to SPIR-V.
C3D_API SpirVShader compileShader (RenderDevice const &device, ShaderModule const &module)
C3D_API SpirVShader compileShader (RenderSystem const &renderSystem, ShaderModule const &module)
ashes::PipelineShaderStageCreateInfo makeShaderState (RenderDevice const &device, VkShaderStageFlagBits stage, SpirVShader code, std::string const &name, std::string mainFuncName="main", ashes::Optional< ashes::SpecializationInfo > specialization=ashes::nullopt)
ashes::PipelineShaderStageCreateInfo makeShaderState (RenderDevice const &device, ShaderModule const &shaderModule, std::string mainFuncName="main", ashes::Optional< ashes::SpecializationInfo > specialization=ashes::nullopt)
void cpuUpdate (UniformBufferOffsetT< ModelInstancesUboConfiguration > &buffer, UInt32Array const &instances)
C3D_API bool operator== (TextureConfiguration const &lhs, TextureConfiguration const &rhs)
C3D_API bool operator!= (TextureConfiguration const &lhs, TextureConfiguration const &rhs)
Generator
CU_DeclareSmartPtr (Cone)
CU_DeclareSmartPtr (Cylinder)
CU_DeclareSmartPtr (Icosahedron)
CU_DeclareSmartPtr (Cube)
CU_DeclareSmartPtr (Plane)
CU_DeclareSmartPtr (Projection)
CU_DeclareSmartPtr (Sphere)
CU_DeclareSmartPtr (Torus)
Component
CU_DeclareSmartPtr (BonesInstantiationComponent)
CU_DeclareSmartPtr (Face)
CU_DeclareSmartPtr (IndexMapping)
CU_DeclareSmartPtr (InstantiationComponent)
CU_DeclareSmartPtr (MorphComponent)
CU_DeclareSmartPtr (SubmeshComponent)
CU_DeclareSmartPtr (TriFaceMapping)
CU_DeclareVector (Face, Face)
Face array.
CU_DeclareVector (FaceSPtr, FacePtr)
Face pointer array.
CU_DeclareMap (castor::String, SubmeshComponentSPtr, SubmeshComponentStr)
EnvironmentMap
CU_DeclareSmartPtr (EnvironmentMap)
CU_DeclareSmartPtr (EnvironmentMapPass)
Passes
CU_DeclareCUSmartPtr (castor3d, CombinePass, C3D_API)
CU_DeclareCUSmartPtr (castor3d, DepthPass, C3D_API)
CU_DeclareCUSmartPtr (castor3d, DownscalePass, C3D_API)
CU_DeclareCUSmartPtr (castor3d, GaussianBlur, C3D_API)
CU_DeclareCUSmartPtr (castor3d, LineariseDepthPass, C3D_API)
CU_DeclareCUSmartPtr (castor3d, RenderQuad, C3D_API)
CU_DeclareCUSmartPtr (castor3d, RenderGrid, C3D_API)
CU_DeclareCUSmartPtr (castor3d, StencilPass, C3D_API)
CU_DeclareVector (CommandsSemaphore, CommandsSemaphore)
PBR
CU_DeclareSmartPtr (IblTextures)
Technique
void bindTexture (ashes::ImageView const &view, ashes::Sampler const &sampler, ashes::WriteDescriptorSetArray &writes, uint32_t &index)
Writes the image view and sampler descriptor to the given writes.
CU_DeclareSmartPtr (RenderTechnique)
CU_DeclareCUSmartPtr (castor3d, RenderTechniquePass, C3D_API)
ToTexture
CU_DeclareSmartPtr (EquirectangularToCube)
CU_DeclareSmartPtr (RenderCube)
CU_DeclareSmartPtr (RenderDepthQuad)
CU_DeclareSmartPtr (TextureProjection)
CU_DeclareSmartPtr (TextureProjectionToCube)
CU_DeclareCUSmartPtr (castor3d, Texture3DTo2D, C3D_API)
Voxelize
CU_DeclareCUSmartPtr (castor3d, VoxelBufferToTexture, C3D_API)
CU_DeclareCUSmartPtr (castor3d, VoxelizePass, C3D_API)
CU_DeclareCUSmartPtr (castor3d, VoxelSecondaryBounce, C3D_API)
CU_DeclareCUSmartPtr (castor3d, Voxelizer, C3D_API)
PassBuffer
CU_DeclareSmartPtr (PassBuffer)
TextureConfigurationBuffer
CU_DeclareSmartPtr (TextureConfigurationBuffer)
UBO
CU_DeclareCUSmartPtr (castor3d, LpvGridConfigUbo, C3D_API)
CU_DeclareCUSmartPtr (castor3d, LpvLightConfigUbo, C3D_API)
CU_DeclareCUSmartPtr (castor3d, LayeredLpvGridConfigUbo, C3D_API)
CU_DeclareVector (LpvLightConfigUbo, LpvLightConfigUbo)
CU_DeclareVector (LpvGridConfigUbo, LpvGridConfigUbo)
Variables
uint32_t constexpr CurrentCmshVersion = makeCmshVersion(0x01u, 0x05u, 0x0000u)
static uint32_t constexpr InvalidIndex = ~(0u)
static VkColorComponentFlags const defaultColorWriteMask { VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT }
static VkClearValue const defaultClearDepthStencil { makeClearValue(1.0f, 0u) }
static VkClearValue const opaqueBlackClearColor { makeClearValue(0.0f, 0.0f, 0.0f, 1.0f) }
static VkClearValue const transparentBlackClearColor { makeClearValue(0.0f, 0.0f, 0.0f, 0.0f) }
static VkClearValue const opaqueWhiteClearColor { makeClearValue(1.0f, 1.0f, 1.0f, 1.0f) }
static VkClearValue const transparentWhiteClearColor { makeClearValue(1.0f, 1.0f, 1.0f, 0.0f) }
Animation
enum AnimationState : uint8_t {
AnimationState::ePlaying, AnimationState::eStopped, AnimationState::ePaused, AnimationState::eCount,
AnimationState::eMin = ePlaying, AnimationState::eMax =eCount-1
}
Animation State Enumerator.
enum AnimationType : uint8_t {
AnimationType::eMovable, AnimationType::eSkeleton, AnimationType::eMesh, AnimationType::eTexture,
AnimationType::eCount, AnimationType::eMin = eMovable, AnimationType::eMax =eCount-1
}
Animation types enumeration.
enum InterpolatorType : uint8_t {
InterpolatorType::eNearest, InterpolatorType::eLinear, InterpolatorType::eCount, InterpolatorType::eMin = eNearest,
InterpolatorType::eMax =eCount-1
}
Interpolation modes enumeration.
using Point3rInterpolator = Interpolator< castor::Point3f >
using QuaternionInterpolator = Interpolator< castor::Quaternion >
using TextureRotateSpeed = castor::SpeedT< castor::Angle, castor::Seconds >
using TextureTranslateSpeed = castor::SpeedT< castor::Point2f, castor::Seconds >
using GroupAnimationMap = std::map< castor::String, GroupAnimation >
using Animable = AnimableT< Engine >
using Animation = AnimationT< Engine >
using OnAnimatedSkeletonChangeFunction = std::function< void(AnimatedObjectGroup const &, AnimatedSkeleton const &) >
using OnAnimatedSkeletonChange = castor::Signal< OnAnimatedSkeletonChangeFunction >
using OnAnimatedSkeletonChangeConnection = OnAnimatedSkeletonChange::connection
using OnAnimatedMeshChangeFunction = std::function< void(AnimatedObjectGroup const &, AnimatedMesh const &) >
using OnAnimatedMeshChange = castor::Signal< OnAnimatedMeshChangeFunction >
using OnAnimatedMeshChangeConnection = OnAnimatedMeshChange::connection
C3D_API castor::String getName (AnimationState value)
C3D_API castor::String getName (AnimationType value)
C3D_API castor::String getName (InterpolatorType value)
CU_DeclareSmartPtr (AnimationKeyFrame)
CU_DeclareVector (AnimationKeyFrameUPtr, AnimationKeyFrame)
CU_DeclareSmartPtr (TextureAnimation)
CU_DeclareSmartPtr (MeshAnimation)
CU_DeclareSmartPtr (MeshAnimationKeyFrame)
CU_DeclareSmartPtr (MeshAnimationSubmesh)
CU_DeclareVector (MeshAnimationSubmesh, MeshAnimationSubmesh)
CU_DeclareSmartPtr (Animable)
CU_DeclareSmartPtr (AnimatedObjectGroup)
CU_DeclareSmartPtr (AnimatedMesh)
CU_DeclareSmartPtr (AnimatedObject)
CU_DeclareSmartPtr (AnimatedSkeleton)
CU_DeclareSmartPtr (Animation)
CU_DeclareSmartPtr (AnimationInstance)
CU_DeclareMap (castor::String, AnimatedObjectGroupSPtr, AnimatedObjectGroupPtrStr)
AnimatedObjectGroup pointer map, sorted by name.
CU_DeclareMap (castor::String, AnimatedObjectSPtr, AnimatedObjectPtrStr)
AnimatedObject pointer map, sorted by name.
CU_DeclareMap (castor::String, AnimationInstanceUPtr, AnimationInstancePtrStr)
Animation pointer map, sorted by name.
CU_DeclareMap (castor::String, AnimationSPtr, AnimationPtrStr)
Animation pointer map, sorted by name.
Buffer
using GpuBufferBuddyAllocator = castor::BuddyAllocatorT< GpuBufferBuddyAllocatorTraits >
using GpuBufferBuddyAllocatorUPtr = std::unique_ptr< GpuBufferBuddyAllocator >
CU_DeclareSmartPtr (GpuBufferPool)
CU_DeclareSmartPtr (UniformBufferBase)
CU_DeclareSmartPtr (UniformBufferPools)
CU_DeclareSmartPtr (PoolUniformBuffer)
CU_DeclareSmartPtr (UniformBufferPool)
CU_DeclareTemplateSmartPtr (UniformBuffer)
bool operator< (MemChunk const &lhs, MemChunk const &rhs)
Cache
using BillboardListCache = ObjectCache< BillboardList, castor::String >
template<typename ElementType >
using ElementInitialiser = std::function< void(std::shared_ptr< ElementType >) >
template<typename ElementType >
using ElementCleaner = std::function< void(std::shared_ptr< ElementType >) >
template<typename ElementType , typename KeyType >
using ElementMerger = std::function< void(CacheBase< ElementType, KeyType > const &, castor::Collection< ElementType, KeyType > &, std::shared_ptr< ElementType >) >
template<typename ElementType >
using ElementAttacher = std::function< void(std::shared_ptr< ElementType >, SceneNode &, SceneNodeSPtr, SceneNodeSPtr, SceneNodeSPtr) >
template<typename ElementType >
using ElementDetacher = std::function< void(std::shared_ptr< ElementType >) >
using OnCacheChangedFunction = std::function< void() >
using OnCacheChanged = castor::Signal< OnCacheChangedFunction >
using AnimatedObjectGroupCache = Cache< AnimatedObjectGroup, castor::String >
using CameraCache = ObjectCache< Camera, castor::String >
using GeometryCache = ObjectCache< Geometry, castor::String >
using LightCache = ObjectCache< Light, castor::String >
using FrameListenerCache = Cache< FrameListener, castor::String >
using MeshCache = Cache< Mesh, castor::String >
using OverlayCache = Cache< Overlay, castor::String >
using ParticleSystemCache = ObjectCache< ParticleSystem, castor::String >
using PluginCache = Cache< Plugin, castor::String >
using SamplerCache = Cache< Sampler, castor::String >
using SceneCache = Cache< Scene, castor::String >
using SceneNodeCache = ObjectCache< SceneNode, castor::String >
using RenderTechniqueCache = Cache< RenderTechnique, castor::String >
using RenderWindowCache = Cache< RenderWindow, castor::String >
static const xchar * InfoCacheCreatedObject = cuT("Cache::create - Created ")
static const xchar * WarningCacheDuplicateObject = cuT("Cache::create - Duplicate ")
static const xchar * WarningCacheNullObject = cuT("Cache::Insert - nullptr ")
CU_DeclareSmartPtr (BillboardListCache)
CU_DeclareSmartPtr (AnimatedObjectGroupCache)
CU_DeclareSmartPtr (BillboardUboPools)
CU_DeclareSmartPtr (CameraCache)
CU_DeclareSmartPtr (GeometryCache)
CU_DeclareSmartPtr (LightCache)
CU_DeclareSmartPtr (FrameListenerCache)
CU_DeclareSmartPtr (MaterialCache)
CU_DeclareSmartPtr (OverlayCache)
CU_DeclareSmartPtr (PluginCache)
CU_DeclareSmartPtr (RenderTargetCache)
CU_DeclareSmartPtr (ShaderProgramCache)
Frame
enum EventType : uint8_t {
EventType::ePreRender, EventType::eQueueRender, EventType::ePostRender, EventType::eCount,
EventType::eMin = ePreRender, EventType::eMax =eCount-1
}
Frame Event Type enumeration.
C3D_API castor::String getName (EventType value)
CU_DeclareSmartPtr (CpuFrameEvent)
CU_DeclareSmartPtr (FrameListener)
CU_DeclareSmartPtr (GpuFrameEvent)
CU_DeclareSmartPtr (CpuFunctorEvent)
CU_DeclareSmartPtr (GpuFunctorEvent)
CU_DeclareVector (CpuFrameEventUPtr, CpuFrameEventPtr)
CU_DeclareVector (GpuFrameEventUPtr, GpuFrameEventPtr)
CU_DeclareMap (castor::String, FrameListenerSPtr, FrameListenerPtrStr)
UserInput
enum UserInputEventType {
UserInputEventType::eMouse, UserInputEventType::eKeyboard, UserInputEventType::eHandler, UserInputEventType::eCount,
UserInputEventType::eMin = eMouse, UserInputEventType::eMax =eCount-1
}
Supported events types enumeration.
enum MouseEventType : uint8_t {
MouseEventType::eMove, MouseEventType::eEnter, MouseEventType::eHover, MouseEventType::eLeave,
MouseEventType::ePushed, MouseEventType::eReleased, MouseEventType::eWheel, MouseEventType::eCount,
MouseEventType::eMin = eMove, MouseEventType::eMax =eCount-1
}
Enumeration of supported mouse events.
enum KeyboardEventType : uint8_t {
KeyboardEventType::ePushed, KeyboardEventType::eReleased, KeyboardEventType::eChar, KeyboardEventType::eCount,
KeyboardEventType::eMin = ePushed, KeyboardEventType::eMax =eCount-1
}
Enumeration of supported keyboard events.
enum HandlerEventType : uint8_t {
HandlerEventType::eActivate, HandlerEventType::eDeactivate, HandlerEventType::eCount, HandlerEventType::eMin = eActivate,
HandlerEventType::eMax =eCount-1
}
Enumeration of supported handler events.
enum MouseButton {
MouseButton::eLeft, MouseButton::eMiddle, MouseButton::eRight, MouseButton::eCount,
MouseButton::eMin = eLeft, MouseButton::eMax =eCount-1
}
Mouse buttons enumeration.
enum KeyboardKey {
KeyboardKey::eNone, KeyboardKey::eBackspace = 0x08, KeyboardKey::eTab = 0x0A, KeyboardKey::eReturn = 0x0D,
KeyboardKey::eEscape = 0x1B, KeyboardKey::eSpace = 0x20, KeyboardKey::eDelete = 0x7F, KeyboardKey::eStart = 0x100,
KeyboardKey::eLButton, KeyboardKey::eRButton, KeyboardKey::eCancel, KeyboardKey::eMButton,
KeyboardKey::eClear, KeyboardKey::eShift, KeyboardKey::eAlt, KeyboardKey::eControl,
KeyboardKey::eMenu, KeyboardKey::ePause, KeyboardKey::eCapital, KeyboardKey::eEnd,
KeyboardKey::eHome, KeyboardKey::eLeft, KeyboardKey::eUp, KeyboardKey::eRight,
KeyboardKey::edown, KeyboardKey::eSelect, KeyboardKey::ePrint, KeyboardKey::eExecute,
KeyboardKey::eSnapshot, KeyboardKey::eInsert, KeyboardKey::eHelp, KeyboardKey::eNumpad0,
KeyboardKey::eNumpad1, KeyboardKey::eNumpad2, KeyboardKey::eNumpad3, KeyboardKey::eNumpad4,
KeyboardKey::eNumpad5, KeyboardKey::eNumpad6, KeyboardKey::eNumpad7, KeyboardKey::eNumpad8,
KeyboardKey::eNumpad9, KeyboardKey::eMultiply, KeyboardKey::eAdd, KeyboardKey::eSeparator,
KeyboardKey::eSubtract, KeyboardKey::eDecimal, KeyboardKey::eDivide, KeyboardKey::eF1,
KeyboardKey::eF2, KeyboardKey::eF3, KeyboardKey::eF4, KeyboardKey::eF5,
KeyboardKey::eF6, KeyboardKey::eF7, KeyboardKey::eF8, KeyboardKey::eF9,
KeyboardKey::eF10, KeyboardKey::eF11, KeyboardKey::eF12, KeyboardKey::eF13,
KeyboardKey::eF14, KeyboardKey::eF15, KeyboardKey::eF16, KeyboardKey::eF17,
KeyboardKey::eF18, KeyboardKey::eF19, KeyboardKey::eF20, KeyboardKey::eF21,
KeyboardKey::eF22, KeyboardKey::eF23, KeyboardKey::eF24, KeyboardKey::eNumlock,
KeyboardKey::eScroll, KeyboardKey::ePageUp, KeyboardKey::ePageDown, KeyboardKey::eNumpadSpace,
KeyboardKey::eNumpadTab, KeyboardKey::eNumpadEnter, KeyboardKey::eNumpadF1, KeyboardKey::eNumpadF2,
KeyboardKey::eNumpadF3, KeyboardKey::eNumpadF4, KeyboardKey::eNumpadHome, KeyboardKey::eNumpadLeft,
KeyboardKey::eNumpadUp, KeyboardKey::eNumpadRight, KeyboardKey::eNumpadDown, KeyboardKey::eNumpadPageUp,
KeyboardKey::eNumpadPageDown, KeyboardKey::eNumpadEnd, KeyboardKey::eNumpadBegin, KeyboardKey::eNumpadInsert,
KeyboardKey::eNumpadDelete, KeyboardKey::eNumpadEqual, KeyboardKey::eNumpadMultiply, KeyboardKey::eNumpadAdd,
KeyboardKey::eNumpadSeparator, KeyboardKey::eNumpadSubtract, KeyboardKey::eNumpadDecimal, KeyboardKey::eNumpadDivide
}
Keyboard keys enumeration.
C3D_API castor::String getName (UserInputEventType value)
C3D_API castor::String getName (MouseEventType value)
C3D_API castor::String getName (KeyboardEventType value)
C3D_API castor::String getName (HandlerEventType value)
C3D_API castor::String getName (MouseButton value)
CU_DeclareSmartPtr (EventHandler)
CU_DeclareSmartPtr (UserInputEvent)
CU_DeclareSmartPtr (KeyboardEvent)
CU_DeclareSmartPtr (MouseEvent)
CU_DeclareSmartPtr (HandlerEvent)
CU_DeclareSmartPtr (UserInputListener)
Material
enum MaterialType {
MaterialType::ePhong, MaterialType::eMetallicRoughness, MaterialType::eSpecularGlossiness, MaterialType::eCount,
MaterialType::eMin = ePhong, MaterialType::eMax =eCount-1
}
Supported material types enumeration.
enum TextureFlag : uint16_t {
TextureFlag::eNone = 0x0000, TextureFlag::eHeight = 0x0001, TextureFlag::eOpacity = 0x0002, TextureFlag::eNormal = 0x0004,
TextureFlag::eEmissive = 0x0008, TextureFlag::eOcclusion = 0x0010, TextureFlag::eTransmittance = 0x0020, TextureFlag::eDiffuse = 0x0040,
TextureFlag::eAlbedo = eDiffuse, TextureFlag::eSpecular = 0x0080, TextureFlag::eMetalness = eSpecular, TextureFlag::eGlossiness = 0x0100,
TextureFlag::eShininess = eGlossiness, TextureFlag::eRoughness = eGlossiness, TextureFlag::eAll = 0x1FF, TextureFlag::eAllButOpacity = eAll & ~(eOpacity),
TextureFlag::eAllButColourAndOpacity = eAllButOpacity & ~(eDiffuse), TextureFlag::eAllButNormalAndOpacity = eAllButOpacity & ~(eNormal)
}
Texture channels flags.
using TextureFlags = castor::FlagCombination< TextureFlag >
using TextureFlagsArray = std::vector< TextureFlagsId >
using OnMaterialChangedFunction = std::function< void(Material const &) >
using OnMaterialChanged = castor::Signal< OnMaterialChangedFunction >
using OnMaterialChangedConnection = OnMaterialChanged::connection
C3D_API castor::String getName (MaterialType value)
C3D_API castor::String getName (TextureFlag value, MaterialType material)
C3D_API bool operator== (TextureFlagsId const &lhs, TextureFlagsId const &rhs)
CU_DeclareSmartPtr (Material)
CU_DeclareVector (MaterialSPtr, MaterialPtr)
Material pointer array.
CU_DeclareMap (castor::String, MaterialSPtr, MaterialPtrStr)
Material pointer map, sorted by name.
CU_DeclareMap (uint32_t, MaterialSPtr, MaterialPtrUInt)
Material pointer map.
C3D_API VkFormat convert (castor::PixelFormat format)
C3D_API castor::PixelFormat convert (VkFormat format)
Pass
enum ParallaxOcclusionMode {
ParallaxOcclusionMode::eNone, ParallaxOcclusionMode::eOne, ParallaxOcclusionMode::eRepeat, ParallaxOcclusionMode::eCount,
ParallaxOcclusionMode::eMin = eNone, ParallaxOcclusionMode::eMax =eCount-1
}
Parallax occlusion modes enumeration.
enum BlendMode : uint8_t {
BlendMode::eNoBlend, BlendMode::eAdditive, BlendMode::eMultiplicative, BlendMode::eInterpolative,
BlendMode::eABuffer, BlendMode::eDepthPeeling, BlendMode::eCount, BlendMode::eMin = eNoBlend,
BlendMode::eMax =eCount-1
}
Blending modes enumeration.
enum PassFlag : uint16_t {
PassFlag::eNone = 0x0000, PassFlag::eAlphaBlending = 0x0001, PassFlag::eAlphaTest = 0x0002, PassFlag::eMetallicRoughness = 0x0004,
PassFlag::eSpecularGlossiness = 0x0008, PassFlag::eSubsurfaceScattering = 0x0010, PassFlag::eDistanceBasedTransmittance = 0x0020, PassFlag::eParallaxOcclusionMappingOne = 0x0040,
PassFlag::eParallaxOcclusionMappingRepeat = 0x0080, PassFlag::eReflection = 0x0100, PassFlag::eRefraction = 0x0200, PassFlag::eAll = 0x03FF
}
Pass specific flags.
using PassFlags = castor::FlagCombination< PassFlag >
using OnPassChangedFunction = std::function< void(Pass const &) >
using OnPassChanged = castor::Signal< OnPassChangedFunction >
using OnPassChangedConnection = OnPassChanged::connection
C3D_API castor::String getName (ParallaxOcclusionMode value)
C3D_API castor::String getName (BlendMode value)
C3D_API castor::String getName (PassFlag value)
CU_DeclareSmartPtr (Pass)
CU_DeclareSmartPtr (PhongPass)
CU_DeclareSmartPtr (MetallicRoughnessPbrPass)
CU_DeclareSmartPtr (SpecularGlossinessPbrPass)
CU_DeclareSmartPtr (SubsurfaceScattering)
CU_DeclareVector (Pass, Pass)
Pass array.
CU_DeclareVector (PassSPtr, PassPtr)
Pass pointer array.
Texture
enum TextureSpace : uint16_t {
TextureSpace::eNormalised = 0x0001 << 0, TextureSpace::eYInverted = 0x0001 << 1, TextureSpace::eColour = 0x0001 << 2, TextureSpace::eDepth = 0x0001 << 3,
TextureSpace::eTangentSpace = 0x0001 << 4, TextureSpace::eObjectSpace = 0x0001 << 5, TextureSpace::eWorldSpace = 0x0001 << 6, TextureSpace::eViewSpace = 0x0001 << 7,
TextureSpace::eClipSpace = 0x0001 << 8, TextureSpace::eStencil = 0x0001 << 9
}
Lists the possible spaces for a texture.
enum CubeMapFace : uint8_t {
CubeMapFace::ePositiveX, CubeMapFace::eNegativeX, CubeMapFace::ePositiveY, CubeMapFace::eNegativeY,
CubeMapFace::ePositiveZ, CubeMapFace::eNegativeZ, CubeMapFace::eCount, CubeMapFace::eMin = ePositiveX,
CubeMapFace::eMax =eCount-1
}
Cube map faces.
using TextureSpaces = castor::FlagCombination< TextureSpace >
using OnTextureUnitChangedFunction = std::function< void(TextureUnit const &) >
using OnTextureUnitChanged = castor::Signal< OnTextureUnitChangedFunction >
using OnTextureUnitChangedConnection = OnTextureUnitChanged::connection
C3D_API castor::String getName (TextureSpace value)
C3D_API castor::String getName (TextureSpaces value)
C3D_API castor::String getName (CubeMapFace value)
CU_DeclareSmartPtr (Sampler)
CU_DeclareSmartPtr (TextureLayout)
CU_DeclareSmartPtr (TextureSource)
CU_DeclareSmartPtr (TextureUnit)
CU_DeclareSmartPtr (TextureView)
CU_DeclareVector (TextureUnit, TextureUnit)
TextureUnit array.
CU_DeclareVector (TextureUnitSPtr, TextureUnitPtr)
TextureUnit pointer array.
CU_DeclareVector (std::reference_wrapper< TextureUnit >, DepthMap)
TextureUnit reference array.
std::ostream & operator<< (std::ostream &stream, TextureLayout const &layout)
CU_DeclareSmartPtr (TextureAnimationInstance)
Miscellaneous
enum GpuFeature : uint32_t { GpuFeature::eStereoRendering = 0x00000001, GpuFeature::eShaderStorageBuffers = 0x00000002 }
All supported GPU feature flags.
enum GpuMax : uint32_t {
GpuMax::eTexture1DSize, GpuMax::eTexture2DSize, GpuMax::eTexture3DSize, GpuMax::eTextureCubeSize,
GpuMax::eTextureLayers, GpuMax::eSamplerLodBias, GpuMax::eClipDistances, GpuMax::eFramebufferWidth,
GpuMax::eFramebufferHeight, GpuMax::eFramebufferLayers, GpuMax::eFramebufferSamples, GpuMax::eTexelBufferSize,
GpuMax::eUniformBufferSize, GpuMax::eStorageBufferSize, GpuMax::eViewportWidth, GpuMax::eViewportHeight,
GpuMax::eViewports, GpuMax::eCount, GpuMax::eMin = eTexture1DSize, GpuMax::eMax =eCount-1
}
All supported GPU feature flags.
using GpuFeatures = castor::FlagCombination< GpuFeature >
using Parameters = ParametersT< castor::String >
C3D_API ashes::DeviceMemoryPtr setupMemory (ashes::Device const &device, VkMemoryRequirements const &requirements, VkMemoryPropertyFlags flags, std::string const &name)
C3D_API ashes::DeviceMemoryPtr setupMemory (RenderDevice const &device, VkMemoryRequirements const &requirements, VkMemoryPropertyFlags flags, std::string const &name)
Model
template<typename T >
using InterleavedVertexTArray = std::vector< InterleavedVertexT< T > >
using InterleavedVertex = InterleavedVertexT< float >
using InterleavedVertexArray = InterleavedVertexTArray< float >
CU_DeclareVector (SubmeshVertex, SubmeshVertex)
SubmeshVertex array.
Mesh
using MeshSubdividerFactory = castor::Factory< MeshSubdivider, castor::String, std::unique_ptr< MeshSubdivider > >
The subdivider factory.
CU_DeclareSmartPtr (Mesh)
CU_DeclareSmartPtr (MeshFactory)
CU_DeclareSmartPtr (MeshGenerator)
CU_DeclareSmartPtr (MeshImporter)
CU_DeclareSmartPtr (MeshImporterFactory)
CU_DeclareSmartPtr (MeshSubdivider)
CU_DeclareSmartPtr (MeshSubdividerFactory)
CU_DeclareMap (castor::String, MeshSPtr, MeshPtrStr)
Mesh pointer array.
CU_DeclareSmartPtr (MeshAnimationInstance)
CU_DeclareMap (uint32_t, MeshAnimationInstanceSubmesh, MeshAnimationInstanceSubmesh)
MeshAnimationInstanceSubmesh map, sorted by submesh ID.
Submesh
using SubmeshAnimationBuffer = SubmeshAnimationBufferT< float >
using SubmeshBoundingBoxList = std::vector< std::pair< Submesh const *, castor::BoundingBox > >
CU_DeclareSmartPtr (Submesh)
CU_DeclareVector (SubmeshSPtr, SubmeshPtr)
Submesh pointer array.
CU_DeclareMap (castor::String, SubmeshSPtr, SubmeshPtrStr)
CU_DeclareMap (Submesh const *, castor::BoundingBox, SubmeshBoundingBox)
CU_DeclareMap (Submesh const *, castor::BoundingSphere, SubmeshBoundingSphere)
CU_DeclareMap (uint32_t, SubmeshAnimationBuffer, SubmeshAnimationBuffer)
Skeleton
enum SkeletonAnimationObjectType : uint8_t {
SkeletonAnimationObjectType::eNode, SkeletonAnimationObjectType::eBone, SkeletonAnimationObjectType::eCount, SkeletonAnimationObjectType::eMin = eNode,
SkeletonAnimationObjectType::eMax =eCount-1
}
Class which represents the moving things.
using ObjectTransform = std::pair< SkeletonAnimationObject *, castor::Matrix4x4f >
using TransformArray = std::vector< ObjectTransform >
static const uint32_t MaxBonesPerVertex = 8
C3D_API castor::String getName (SkeletonAnimationObjectType value)
CU_DeclareSmartPtr (SkeletonAnimation)
CU_DeclareSmartPtr (SkeletonAnimationKeyFrame)
CU_DeclareSmartPtr (SkeletonAnimationObject)
CU_DeclareSmartPtr (SkeletonAnimationBone)
CU_DeclareSmartPtr (SkeletonAnimationNode)
CU_DeclareMap (castor::String, SkeletonAnimationObjectSPtr, SkeletonAnimationObjectPtrStr)
SkeletonAnimationObject pointer map, sorted by name.
CU_DeclareVector (SkeletonAnimationObjectSPtr, SkeletonAnimationObjectPtr)
SkeletonAnimationObject pointer array.
CU_DeclareSmartPtr (Bone)
CU_DeclareSmartPtr (Skeleton)
CU_DeclareVector (VertexBoneData, VertexBoneData)
Skinned vertex data array.
CU_DeclareVector (BoneSPtr, BonePtr)
Bone pointer array.
CU_DeclareMap (castor::String, BoneSPtr, BonePtrStr)
Bone pointer map sorted by name.
CU_DeclareSmartPtr (SkeletonAnimationInstance)
CU_DeclareSmartPtr (SkeletonAnimationInstanceBone)
CU_DeclareSmartPtr (SkeletonAnimationInstanceNode)
CU_DeclareSmartPtr (SkeletonAnimationInstanceObject)
CU_DeclareMap (castor::String, SkeletonAnimationInstanceObjectSPtr, SkeletonAnimationInstanceObjectPtrStr)
MovingObject pointer map, sorted by name.
CU_DeclareVector (SkeletonAnimationInstanceObjectSPtr, SkeletonAnimationInstanceObjectPtr)
SkeletonAnimationInstanceObject pointer array.
CU_DeclareVector (std::reference_wrapper< SkeletonAnimationInstance >, SkeletonAnimationInstance)
Skeleton animation instance pointer array.
Overlay
enum OverlayType : uint8_t {
OverlayType::ePanel, OverlayType::eBorderPanel, OverlayType::eText, OverlayType::eCount,
OverlayType::eMin = ePanel, OverlayType::eMax =eCount-1
}
Overlay types enumeration.
enum TextWrappingMode {
TextWrappingMode::eNone, TextWrappingMode::eBreak, TextWrappingMode::eBreakWords, TextWrappingMode::eCount,
TextWrappingMode::eMin = eNone, TextWrappingMode::eMax =eCount-1
}
Text wrapping modes, handles the way text is cut when it overflows the overlay width.
enum TextTexturingMode {
TextTexturingMode::eLetter, TextTexturingMode::eText, TextTexturingMode::eCount, TextTexturingMode::eMin = eLetter,
TextTexturingMode::eMax =eCount-1
}
Text texturing modes, handles the way textures are appied to text overlays.
enum TextLineSpacingMode {
TextLineSpacingMode::eOwnHeight, TextLineSpacingMode::eMaxLineHeight, TextLineSpacingMode::eMaxFontHeight, TextLineSpacingMode::eCount,
TextLineSpacingMode::eMin = eOwnHeight, TextLineSpacingMode::eMax =eCount-1
}
Text line spacing modes, handles the way lines are spaced, which each other, inside one TextOverlay.
enum HAlign {
HAlign::eLeft, HAlign::eCenter, HAlign::eRight, HAlign::eCount,
HAlign::eMin = eLeft, HAlign::eMax =eCount-1
}
Horizontal alignments for text overlays.
enum VAlign {
VAlign::eTop, VAlign::eCenter, VAlign::eBottom, VAlign::eCount,
VAlign::eMin = eTop, VAlign::eMax =eCount-1
}
Vertical alignments for text overlays.
enum BorderPosition {
BorderPosition::eInternal, BorderPosition::eMiddle, BorderPosition::eExternal, BorderPosition::eCount,
BorderPosition::eMin = eInternal, BorderPosition::eMax =eCount-1
}
Text wrapping modes, handles the way text is cut when it overflows the overlay width.
C3D_API castor::String getName (OverlayType value)
C3D_API castor::String getName (TextWrappingMode value)
C3D_API castor::String getName (TextTexturingMode value)
C3D_API castor::String getName (TextLineSpacingMode value)
C3D_API castor::String getName (HAlign value)
C3D_API castor::String getName (VAlign value)
C3D_API castor::String getName (BorderPosition value)
CU_DeclareCUSmartPtr (castor3d, BorderPanelOverlay, C3D_API)
CU_DeclareCUSmartPtr (castor3d, DebugOverlays, C3D_API)
CU_DeclareCUSmartPtr (castor3d, FontTexture, C3D_API)
CU_DeclareCUSmartPtr (castor3d, Overlay, C3D_API)
CU_DeclareCUSmartPtr (castor3d, OverlayCategory, C3D_API)
CU_DeclareCUSmartPtr (castor3d, OverlayFactory, C3D_API)
CU_DeclareCUSmartPtr (castor3d, OverlayRenderer, C3D_API)
CU_DeclareCUSmartPtr (castor3d, PanelOverlay, C3D_API)
CU_DeclareCUSmartPtr (castor3d, TextOverlay, C3D_API)
CU_DeclareVector (OverlaySPtr, OverlayPtr)
CU_DeclareMap (castor::String, OverlaySPtr, OverlayPtrStr)
Plugin
enum PluginType : uint8_t {
PluginType::eImporter, PluginType::eDivider, PluginType::eGenerator, PluginType::eToneMapping,
PluginType::ePostEffect, PluginType::eGeneric, PluginType::eParticle, PluginType::eCount,
PluginType::eMin = eImporter, PluginType::eMax =eCount-1
}
Plugin types enumeration.
CU_DeclareSmartPtr (Plugin)
CU_DeclareSmartPtr (ImporterPlugin)
CU_DeclareSmartPtr (DividerPlugin)
CU_DeclareSmartPtr (GenericPlugin)
CU_DeclareSmartPtr (PostFxPlugin)
CU_DeclareSmartPtr (ParticlePlugin)
CU_DeclareMap (castor::String, PluginSPtr, PluginStr)
CU_DeclareArray (PluginStrMap, PluginType::eCount, PluginStrMap)
CU_DeclareMap (castor::Path, castor::DynamicLibrarySPtr, DynamicLibraryPtrPath)
CU_DeclareArray (DynamicLibraryPtrPathMap, PluginType::eCount, DynamicLibraryPtrPathMap)
CU_DeclareMap (castor::Path, PluginType, PluginTypePath)
Render
enum FrustumCorner {
FrustumCorner::eFarLeftBottom, FrustumCorner::eFarLeftTop, FrustumCorner::eFarRightTop, FrustumCorner::eFarRightBottom,
FrustumCorner::eNearLeftBottom, FrustumCorner::eNearLeftTop, FrustumCorner::eNearRightTop, FrustumCorner::eNearRightBottom,
FrustumCorner::eCount, FrustumCorner::eMin = eFarLeftBottom, FrustumCorner::eMax =eCount-1
}
Frustum corners enumeration.
enum FrustumPlane {
FrustumPlane::eNear, FrustumPlane::eFar, FrustumPlane::eLeft, FrustumPlane::eRight,
FrustumPlane::eTop, FrustumPlane::eBottom, FrustumPlane::eCount, FrustumPlane::eMin = eNear,
FrustumPlane::eMax =eCount-1
}
Frustum planes enumeration.
enum PickNodeType : uint8_t {
PickNodeType::eNone, PickNodeType::eStatic, PickNodeType::eInstantiatedStatic, PickNodeType::eSkinning,
PickNodeType::eInstantiatedSkinning, PickNodeType::eMorphing, PickNodeType::eBillboard
}
The picking node types.
enum TargetType : uint8_t {
TargetType::eWindow, TargetType::eTexture, TargetType::eCount, TargetType::eMin = eWindow,
TargetType::eMax =eCount-1
}
RenderTarget supported types.
enum ViewportType : uint8_t {
ViewportType::eOrtho, ViewportType::ePerspective, ViewportType::eFrustum, ViewportType::eCount,
ViewportType::eMin = eOrtho, ViewportType::eMax =eCount-1
}
The viewport projection types enumeration.
enum RenderMode : uint8_t {
RenderMode::eOpaqueOnly, RenderMode::eTransparentOnly, RenderMode::eBoth, RenderMode::eCount,
RenderMode::eMin = eOpaqueOnly, RenderMode::eMax =eCount-1
}
The render pass modes, regarding transparency.
using RenderQueueArray = std::vector< std::reference_wrapper< RenderQueue > >
castor::String const RenderTypeUndefined = cuT("Undefined")
C3D_API castor::String getName (FrustumCorner value)
C3D_API castor::String getName (FrustumPlane value)
C3D_API castor::String getName (PickNodeType value)
C3D_API castor::String getName (TargetType value)
C3D_API castor::String getName (ViewportType value)
C3D_API castor::String getName (RenderMode value)
C3D_API bool isValidNodeForPass (PassFlags const &passFlags, RenderMode value)
C3D_API TextureFlagsArray::const_iterator checkFlags (TextureFlagsArray const &flags, TextureFlag flag)
C3D_API TextureFlags merge (TextureFlagsArray const &flags)
C3D_API bool operator< (PipelineFlags const &lhs, PipelineFlags const &rhs)
CU_DeclareCUSmartPtr (castor3d, PickingPass, C3D_API)
CU_DeclareCUSmartPtr (castor3d, RenderDevice, C3D_API)
CU_DeclareCUSmartPtr (castor3d, RenderLoop, C3D_API)
CU_DeclareCUSmartPtr (castor3d, RenderPassTimer, C3D_API)
CU_DeclareCUSmartPtr (castor3d, RenderPipeline, C3D_API)
CU_DeclareCUSmartPtr (castor3d, RenderSystem, C3D_API)
CU_DeclareCUSmartPtr (castor3d, RenderTarget, C3D_API)
CU_DeclareCUSmartPtr (castor3d, RenderWindow, C3D_API)
CU_DeclareCUSmartPtr (castor3d, Viewport, C3D_API)
CU_DeclareVector (RenderWindowSPtr, RenderWindowPtr)
CU_DeclareVector (IntermediateView, IntermediateView)
CU_DeclareMap (uint32_t, RenderWindowSPtr, RenderWindow)
CU_DeclareMap (castor::String, RenderWindowSPtr, RenderWindowPtrStr)
Culling
using SceneCullerSignalFunction = std::function< void(SceneCuller const &) >
using SceneCullerSignal = castor::Signal< SceneCullerSignalFunction >
using SceneCullerSignalConnection = castor::Connection< SceneCullerSignal >
CU_DeclareSmartPtr (SceneCuller)
Global Illumination
enum GlobalIlluminationType : uint8_t {
GlobalIlluminationType::eNone, GlobalIlluminationType::eRsm, GlobalIlluminationType::eVoxelConeTracing, GlobalIlluminationType::eLpv,
GlobalIlluminationType::eLpvG, GlobalIlluminationType::eLayeredLpv, GlobalIlluminationType::eLayeredLpvG, GlobalIlluminationType::eCount,
GlobalIlluminationType::eMin = eNone, GlobalIlluminationType::eMax =eCount-1
}
Enumerator of supported global illumination algorithms.
castor::String getName (GlobalIlluminationType giType)
Light Propagation Volumes
enum LpvTexture : uint8_t {
LpvTexture::eR, LpvTexture::eG, LpvTexture::eB, LpvTexture::eCount,
LpvTexture::eMin = eR, LpvTexture::eMax =eCount-1
}
Enumerator of textures used by the light volume GI passes.
using LayeredLightPropagationVolumes = LayeredLightPropagationVolumesT< false >
using LayeredLightPropagationVolumesG = LayeredLightPropagationVolumesT< true >
using LightPropagationVolumes = LightPropagationVolumesT< false >
using LightPropagationVolumesG = LightPropagationVolumesT< true >
using LightPropagationVolumesLightType = std::array< LightPropagationVolumesUPtr, size_t(LightType::eCount) >
using LayeredLightPropagationVolumesLightType = std::array< LayeredLightPropagationVolumesUPtr, size_t(LightType::eCount) >
using LightPropagationVolumesGLightType = std::array< LightPropagationVolumesGUPtr, size_t(LightType::eCount) >
using LayeredLightPropagationVolumesGLightType = std::array< LayeredLightPropagationVolumesGUPtr, size_t(LightType::eCount) >
using DirectionalLightPassLPVShadow = LightPassVolumePropagationShadowT< LightType::eDirectional >
using SpotLightPassLPVShadow = LightPassVolumePropagationShadowT< LightType::eSpot >
using DirectionalLightPassLayeredLPVShadow = LightPassLayeredVolumePropagationShadowT< LightType::eDirectional >
using LpvLightPassConfig = LpvLightPassConfigT< LightVolumePassResult, LpvGridConfigUbo >
using LayeredLpvLightPassConfig = LpvLightPassConfigT< LightVolumePassResultArray, LayeredLpvGridConfigUbo >
castor::String getTextureName (LpvTexture texture, std::string const &infix)
castor::String getName (LpvTexture texture)
VkFormat getFormat (LpvTexture texture)
VkClearValue getClearValue (LpvTexture texture)
VkImageUsageFlags getUsageFlags (LpvTexture texture)
VkBorderColor getBorderColor (LpvTexture texture)
uint32_t getMipLevels (LpvTexture texture, castor::Size const &size)
uint32_t getMipLevels (LpvTexture texture, VkExtent3D const &size)
CU_DeclareCUSmartPtr (castor3d, GeometryInjectionPass, C3D_API)
CU_DeclareCUSmartPtr (castor3d, LayeredLightPropagationVolumes, C3D_API)
CU_DeclareCUSmartPtr (castor3d, LayeredLightPropagationVolumesG, C3D_API)
CU_DeclareCUSmartPtr (castor3d, LightInjectionPass, C3D_API)
CU_DeclareCUSmartPtr (castor3d, LightPropagationPass, C3D_API)
CU_DeclareCUSmartPtr (castor3d, LightPropagationVolumes, C3D_API)
CU_DeclareCUSmartPtr (castor3d, LightPropagationVolumesG, C3D_API)
CU_DeclareCUSmartPtr (castor3d, LightVolumePassResult, C3D_API)
CU_DeclareArray (LightPropagationPassUPtr, lpv::PropagationPassCount, LightPropagationPass)
CU_DeclareVector (GeometryInjectionPass, GeometryInjectionPass)
CU_DeclareVector (LightInjectionPass, LightInjectionPass)
CU_DeclareVector (LightVolumePassResultUPtr, LightVolumePassResult)
CU_DeclareCUSmartPtr (castor3d, LayeredLightVolumeGIPass, C3D_API)
CU_DeclareCUSmartPtr (castor3d, LightVolumeGIPass, C3D_API)
CU_DeclareArray (LayeredLightVolumeGIPassUPtr, lpv::ResolvePassCount, LayeredLightVolumeGIPass)
CU_DeclareArray (LightVolumeGIPassUPtr, lpv::ResolvePassCount, LightVolumeGIPass)
PostEffect
using PostEffectFactory = castor::Factory< PostEffect, castor::String, std::shared_ptr< PostEffect >, std::function< std::shared_ptr< PostEffect >(RenderTarget &, RenderSystem &, Parameters const &) > >
Post effect factory.
CU_DeclareSmartPtr (PostEffect)
CU_DeclareVector (PostEffectSPtr, PostEffectPtr)
ShadowMap
enum SmTexture : uint8_t {
SmTexture::eDepth, SmTexture::eNormalLinear, SmTexture::eVariance, SmTexture::ePosition,
SmTexture::eFlux, SmTexture::eCount, SmTexture::eMin = eDepth, SmTexture::eMax =eCount-1
}
Enumerator of textures used in deferred rendering.
using ShadowMapRefIds = std::pair< std::reference_wrapper< ShadowMap >, UInt32Array >
using ShadowMapRefArray = std::vector< ShadowMapRefIds >
using ShadowMapLightTypeArray = std::array< ShadowMapRefArray, size_t(LightType::eCount) >
castor::String getTextureName (LightType light, SmTexture texture)
castor::String getName (SmTexture texture)
VkFormat getFormat (SmTexture texture)
VkClearValue getClearValue (SmTexture texture)
VkImageUsageFlags getUsageFlags (SmTexture texture)
VkBorderColor getBorderColor (SmTexture texture)
uint32_t getMipLevels (SmTexture texture, castor::Size const &size)
uint32_t getMipLevels (SmTexture texture, VkExtent3D const &size)
CU_DeclareCUSmartPtr (castor3d, ShadowMap, C3D_API)
CU_DeclareCUSmartPtr (castor3d, ShadowMapPass, C3D_API)
void bindShadowMaps (PipelineFlags const &pipelineFlags, ShadowMapLightTypeArray const &shadowMaps, ashes::WriteDescriptorSetArray &writes, uint32_t &index)
Writes the shadow maps descriptors to the given writes.
Opaque
enum DsTexture : uint8_t {
DsTexture::eDepth, DsTexture::eData1, DsTexture::eData2, DsTexture::eData3,
DsTexture::eData4, DsTexture::eData5, DsTexture::eCount, DsTexture::eMin = eDepth,
DsTexture::eMax =eCount-1
}
Enumerator of textures used by the deferred renderer's GBUffer.
castor::String getTextureName (DsTexture texture)
castor::String getName (DsTexture texture)
VkFormat getFormat (DsTexture texture)
VkClearValue getClearValue (DsTexture texture)
VkImageUsageFlags getUsageFlags (DsTexture texture)
VkBorderColor getBorderColor (DsTexture texture)
uint32_t getMipLevels (DsTexture texture, castor::Size const &size)
CU_DeclareCUSmartPtr (castor3d, DeferredRendering, C3D_API)
CU_DeclareCUSmartPtr (castor3d, OpaqueResolvePass, C3D_API)
CU_DeclareCUSmartPtr (castor3d, SsaoPass, C3D_API)
Lighting
enum LpTexture : uint8_t {
LpTexture::eDepth, LpTexture::eDiffuse, LpTexture::eSpecular, LpTexture::eIndirectDiffuse,
LpTexture::eIndirectSpecular, LpTexture::eCount, LpTexture::eMin = eDepth, LpTexture::eMax =eCount-1
}
Enumerator of textures used by the lighting pass in deferred rendering.
castor::String getTextureName (LpTexture texture)
castor::String getName (LpTexture texture)
VkFormat getFormat (LpTexture texture)
VkClearValue getClearValue (LpTexture texture)
VkImageUsageFlags getUsageFlags (LpTexture texture)
VkBorderColor getBorderColor (LpTexture texture)
uint32_t getMipLevels (LpTexture texture, castor::Size const &size)
uint32_t getMipLevels (LpTexture texture, VkExtent3D const &size)
float getMaxDistance (LightCategory const &light, castor::Point3f const &attenuation)
Retrieve the maximum litten distance for given light and attenuation.
float getMaxDistance (LightCategory const &light, castor::Point3f const &attenuation, float max)
Retrieve the maximum litten distance for given light and attenuation.
CU_DeclareSmartPtr (LightPass)
CU_DeclareCUSmartPtr (castor3d, SubsurfaceScatteringPass, C3D_API)
RSM GI
using DirectionalLightPassReflectiveShadow = LightPassReflectiveShadow< LightType::eDirectional >
using PointLightPassReflectiveShadow = LightPassReflectiveShadow< LightType::ePoint >
using SpotLightPassReflectiveShadow = LightPassReflectiveShadow< LightType::eSpot >
CU_DeclareSmartPtr (RsmGIPass)
CU_DeclareSmartPtr (RsmInterpolatePass)
Transparent
enum WbTexture : uint8_t {
WbTexture::eDepth, WbTexture::eAccumulation, WbTexture::eRevealage, WbTexture::eVelocity,
WbTexture::eCount, WbTexture::eMin = eDepth, WbTexture::eMax =eCount-1
}
Enumerator of textures used in weighted blend OIT.
castor::String getTextureName (WbTexture texture)
castor::String getName (WbTexture texture)
VkFormat getFormat (WbTexture texture)
VkClearValue getClearValue (WbTexture texture)
uint32_t getMipLevels (WbTexture texture, castor::Size const &size)
uint32_t getMipLevels (WbTexture texture, VkExtent3D const &size)
CU_DeclareCUSmartPtr (castor3d, WeightedBlendRendering, C3D_API)
ToneMapping
using ToneMappingFactory = castor::Factory< ToneMapping, castor::String, ToneMappingSPtr, std::function< ToneMappingSPtr(Engine &, RenderDevice const &, HdrConfigUbo &, Parameters const &) > >
Tone mapping factory.
CU_DeclareSmartPtr (ToneMapping)
Scene
enum MovableType : uint8_t {
MovableType::eCamera, MovableType::eGeometry, MovableType::eLight, MovableType::eBillboard,
MovableType::eParticleEmitter, MovableType::eCount, MovableType::eMin = eCamera, MovableType::eMax =eCount-1
}
Movable object types enumerator.
enum ShadowType {
ShadowType::eNone, ShadowType::eRaw, ShadowType::ePCF, ShadowType::eVariance,
ShadowType::eCount, ShadowType::eMin = eNone, ShadowType::eMax =eCount-1
}
Shadow filter types enumeration.
enum FogType {
FogType::eDisabled, FogType::eLinear, FogType::eExponential, FogType::eSquaredExponential,
FogType::eCount, FogType::eMin = eDisabled, FogType::eMax =eCount-1
}
Fog types enumeration.
enum SceneFlag : uint16_t {
SceneFlag::eNone = 0x0000, SceneFlag::eFogLinear = 0x0001 << 0, SceneFlag::eFogExponential = 0x0001 << 1, SceneFlag::eFogSquaredExponential = 0x0001 << 2,
SceneFlag::eShadowBegin = 0x0001 << 3, SceneFlag::eShadowDirectional = eShadowBegin << 0, SceneFlag::eShadowPoint = eShadowBegin << 1, SceneFlag::eShadowSpot = eShadowBegin << 2,
SceneFlag::eShadowEnd = eShadowSpot, SceneFlag::eShadowAny = eShadowSpot | eShadowPoint | eShadowDirectional, SceneFlag::eLpvGI = 0x0001 << 6, SceneFlag::eLayeredLpvGI = 0x0001 << 7,
SceneFlag::eVoxelConeTracing = 0x0001 << 8, SceneFlag::eAll = 0x01FF
}
Scene flags enumeration.
enum BillboardType {
BillboardType::eSpherical, BillboardType::eCylindrical, BillboardType::eCount, BillboardType::eMin = eSpherical,
BillboardType::eMax =eCount-1
}
Billboard rendering types enumeration.
enum BillboardSize {
BillboardSize::eDynamic, BillboardSize::eFixed, BillboardSize::eCount, BillboardSize::eMin = eDynamic,
BillboardSize::eMax =eCount-1
}
Billboard sizing types enumeration.
using SceneFlags = castor::FlagCombination< SceneFlag >
using OnSceneChangedFunction = std::function< void(Scene const &) >
using OnSceneChanged = castor::Signal< OnSceneChangedFunction >
using OnSceneChangedConnection = OnSceneChanged::connection
using OnSceneUpdateFunction = std::function< void(Scene const &) >
using OnSceneUpdate = castor::Signal< OnSceneUpdateFunction >
using OnSceneUpdateConnection = OnSceneUpdate::connection
using OnCameraChangedFunction = std::function< void(Camera const &) >
using OnCameraChanged = castor::Signal< OnCameraChangedFunction >
using OnCameraChangedConnection = OnCameraChanged::connection
using OnSceneNodeChangedFunction = std::function< void(SceneNode const &) >
using OnSceneNodeChanged = castor::Signal< OnSceneNodeChangedFunction >
using OnSceneNodeChangedConnection = OnSceneNodeChanged::connection
using SubmeshMaterialMap = std::map< Submesh const *, MaterialWPtr >
using OnSubmeshMaterialChangedFunction = std::function< void(Geometry const &, Submesh const &, MaterialSPtr oldMaterial, MaterialSPtr newMaterial) >
using OnSubmeshMaterialChanged = castor::Signal< OnSubmeshMaterialChangedFunction >
using OnSubmeshMaterialChangedConnection = OnSubmeshMaterialChanged::connection
using OnBillboardMaterialChangedFunction = std::function< void(BillboardBase const &, MaterialSPtr oldMaterial, MaterialSPtr newMaterial) >
using OnBillboardMaterialChanged = castor::Signal< OnBillboardMaterialChangedFunction >
using OnBillboardMaterialChangedConnection = OnBillboardMaterialChanged::connection
C3D_API castor::String getName (MovableType value)
C3D_API castor::String getName (ShadowType value)
C3D_API castor::String getName (FogType value)
C3D_API FogType getFogType (SceneFlags const &flags)
Gives the fog type matching the given flags.
C3D_API castor::String getName (BillboardType value)
C3D_API castor::String getName (BillboardSize value)
CU_DeclareSmartPtr (BillboardBase)
CU_DeclareSmartPtr (BillboardList)
CU_DeclareSmartPtr (Camera)
CU_DeclareSmartPtr (Geometry)
CU_DeclareSmartPtr (MovableObject)
CU_DeclareSmartPtr (Scene)
CU_DeclareSmartPtr (SceneFileContext)
CU_DeclareSmartPtr (SceneFileParser)
CU_DeclareSmartPtr (SceneImporter)
CU_DeclareSmartPtr (SceneNode)
CU_DeclareVector (CameraSPtr, CameraPtr)
Camera pointer array.
CU_DeclareVector (GeometrySPtr, GeometryPtr)
Geometry pointer array.
CU_DeclareVector (SceneNodeSPtr, SceneNodePtr)
SceneNode pointer array.
CU_DeclareVector (BillboardListSPtr, BillboardList)
BillboardList pointer array.
CU_DeclareMap (castor::String, CameraSPtr, CameraPtrStr)
Camera pointer map, sorted by name.
CU_DeclareMap (castor::String, MovableObjectSPtr, MovableObjectPtrStr)
MovableObject pointer map, sorted by name.
CU_DeclareMap (castor::String, GeometrySPtr, GeometryPtrStr)
Geometry pointer map, sorted by name.
CU_DeclareMap (castor::String, SceneSPtr, ScenePtrStr)
Scene pointer map, sorted by name.
CU_DeclareMap (castor::String, SceneNodeSPtr, SceneNodePtrStr)
SceneNode pointer map, sorted by name.
CU_DeclareMap (castor::String, BillboardListSPtr, BillboardListStr)
BillboardList pointer map, sorted by name.
Background
enum BackgroundType {
BackgroundType::eColour, BackgroundType::eImage, BackgroundType::eSkybox, BackgroundType::eCount,
BackgroundType::eMin = eColour, BackgroundType::eMax =eCount-1
}
Scene background types enumeration.
using BackgroundChangedFunc = std::function< void(SceneBackground const &) >
using OnBackgroundChanged = castor::Signal< BackgroundChangedFunc >
using OnBackgroundChangedConnection = OnBackgroundChanged::connection
C3D_API castor::String getName (BackgroundType value)
CU_DeclareSmartPtr (SceneBackground)
Light
enum LightType : uint8_t {
LightType::eDirectional, LightType::ePoint, LightType::eSpot, LightType::eCount,
LightType::eMin = eDirectional, LightType::eMax =eCount-1
}
Light types enumeration.
using LightsMap = std::array< LightsArray, size_t(LightType::eCount) >
Array of lights per light type.
using OnLightChangedFunction = std::function< void(Light &) >
using OnLightChanged = castor::Signal< OnLightChangedFunction >
using OnLightChangedConnection = OnLightChanged::connection
C3D_API castor::String getName (LightType value)
CU_DeclareSmartPtr (Light)
CU_DeclareSmartPtr (LightFactory)
CU_DeclareSmartPtr (LightCategory)
CU_DeclareSmartPtr (DirectionalLight)
CU_DeclareSmartPtr (PointLight)
CU_DeclareSmartPtr (SpotLight)
CU_DeclareVector (LightSPtr, LightPtr)
Array of lights.
CU_DeclareVector (LightSPtr, Lights)
Array of lights.
CU_DeclareVector (LightRPtr, LightsRef)
Array to non owning light pointers.
CU_DeclareMap (castor::String, LightSPtr, LightPtrStr)
Map of lights, sorted by name.
CU_DeclareMap (int, LightSPtr, LightPtrInt)
Map of lights, sorted by index.
Particle
enum ElementUsage : uint32_t {
ElementUsage::eUnknown = 0x000, ElementUsage::ePosition = 0x001, ElementUsage::eNormal = 0x002, ElementUsage::eTangent = 0x004,
ElementUsage::eBitangent = 0x008, ElementUsage::eDiffuse = 0x010, ElementUsage::eTexCoords = 0x020, ElementUsage::eBoneIds0 = 0x040,
ElementUsage::eBoneIds1 = 0x080, ElementUsage::eBoneWeights0 = 0x100, ElementUsage::eBoneWeights1 = 0x200, ElementUsage::eTransform = 0x400,
ElementUsage::eMatIndex = 0x800
}
Element usage enumeration.
enum ParticleFormat {
ParticleFormat::eInt, ParticleFormat::eVec2i, ParticleFormat::eVec3i, ParticleFormat::eVec4i,
ParticleFormat::eUInt, ParticleFormat::eVec2ui, ParticleFormat::eVec3ui, ParticleFormat::eVec4ui,
ParticleFormat::eFloat, ParticleFormat::eVec2f, ParticleFormat::eVec3f, ParticleFormat::eVec4f,
ParticleFormat::eMat2f, ParticleFormat::eMat3f, ParticleFormat::eMat4f, ParticleFormat::eCount,
ParticleFormat::eMin = eInt, ParticleFormat::eMax =eCount-1
}
using ElementUsages = castor::FlagCombination< ElementUsage >
using ParticleFactory = castor::Factory< CpuParticleSystem, castor::String, std::unique_ptr< CpuParticleSystem >, std::function< std::unique_ptr< CpuParticleSystem >(ParticleSystem &) > >
Particle system factory.
using ParticleValues = ParametersT< size_t >
C3D_API castor::String getName (ElementUsage value)
C3D_API castor::String getName (ParticleFormat value)
CU_DeclareSmartPtr (ComputeParticleSystem)
CU_DeclareSmartPtr (CpuParticleSystem)
CU_DeclareSmartPtr (ParticleElementDeclaration)
CU_DeclareSmartPtr (ParticleEmitter)
CU_DeclareSmartPtr (ParticleFactory)
CU_DeclareSmartPtr (ParticleSystem)
CU_DeclareSmartPtr (ParticleSystemImpl)
CU_DeclareSmartPtr (ParticleUpdater)
CU_DeclareVector (Particle, Particle)
CU_DeclareVector (ParticleEmitterUPtr, ParticleEmitter)
CU_DeclareVector (ParticleUpdaterUPtr, ParticleUpdater)
Shader
enum ProgramFlag : uint32_t {
ProgramFlag::eNone = 0x0000, ProgramFlag::eInstantiation = 0x0001, ProgramFlag::eSkinning = 0x0002, ProgramFlag::eBillboards = 0x0004,
ProgramFlag::eMorphing = 0x0008, ProgramFlag::ePicking = 0x0010, ProgramFlag::eLighting = 0x0020, ProgramFlag::eSpherical = 0x0040,
ProgramFlag::eFixedSize = 0x0080, ProgramFlag::eInstanceMult = 0x0100, ProgramFlag::eShadowMapDirectional = 0x0200, ProgramFlag::eShadowMapSpot = 0x0400,
ProgramFlag::eShadowMapPoint = 0x0800, ProgramFlag::eEnvironmentMapping = 0x1000, ProgramFlag::eDepthPass = 0x2000, ProgramFlag::eInvertNormals = 0x4000,
ProgramFlag::eHasGeometry = 0x8000, ProgramFlag::eConservativeRasterization = 0x10000, ProgramFlag::eAll = 0x1FFFF
}
Flags to use when looking for an automatically generated program.
using ShaderPtr = std::unique_ptr< ast::Shader >
using ProgramFlags = castor::FlagCombination< ProgramFlag >
C3D_API bool isShadowMapProgram (ProgramFlags const &flags)
Tells if the given flags contain a shadow map flag.
C3D_API uint32_t getPassBufferIndex () noexcept
C3D_API uint32_t getTexturesBufferIndex () noexcept
C3D_API uint32_t getLightBufferIndex () noexcept
C3D_API uint32_t getMinBufferIndex () noexcept
C3D_API uint32_t getMinTextureIndex () noexcept
CU_DeclareCUSmartPtr (castor3d, ShaderBuffer, C3D_API)
CU_DeclareCUSmartPtr (castor3d, ShaderProgram, C3D_API)
Typedef Documentation
Animable
using castor3d::Animable = typedef AnimableT< Engine >
AnimatedObjectGroupCache
using castor3d::AnimatedObjectGroupCache = typedef Cache< AnimatedObjectGroup, castor::String >
Animation
using castor3d::Animation = typedef AnimationT< Engine >
BackgroundChangedFunc
using castor3d::BackgroundChangedFunc = typedef std::function< void(SceneBackground const &) >
BillboardListCache
typedef ObjectCache< BillboardList, castor::String > castor3d::BillboardListCache
BillboardListRenderNode
using castor3d::BillboardListRenderNode = typedef ObjectRenderNode< BillboardBase, BillboardBase >
CameraCache
using castor3d::CameraCache = typedef ObjectCache< Camera, castor::String >
CombinePassConfig
using castor3d::CombinePassConfig = typedef CombinePassConfigT< ashes::Optional >
CombinePassConfigData
using castor3d::CombinePassConfigData = typedef CombinePassConfigT< rq::RawTypeT >
DebugCallbacksPtr
using castor3d::DebugCallbacksPtr = typedef std::unique_ptr< DebugCallbacks >
DirectionalLightPassLayeredLPVShadow
using castor3d::DirectionalLightPassLayeredLPVShadow = typedef LightPassLayeredVolumePropagationShadowT< LightType::eDirectional >
The directional lights light pass with shadows and LPV.
DirectionalLightPassLPVShadow
using castor3d::DirectionalLightPassLPVShadow = typedef LightPassVolumePropagationShadowT< LightType::eDirectional >
The directional lights light pass with shadows and LPV.
DirectionalLightPassReflectiveShadow
using castor3d::DirectionalLightPassReflectiveShadow = typedef LightPassReflectiveShadow< LightType::eDirectional >
The directional lights light pass with shadows.
DirectionalLightPassShadow
using castor3d::DirectionalLightPassShadow = typedef LightPassShadow< LightType::eDirectional >
The directional lights light pass with shadows.
ElementAttacher
template<typename ElementType > using castor3d::ElementAttacher = typedef std::function< void(std::shared_ptr< ElementType >, SceneNode &, SceneNodeSPtr, SceneNodeSPtr, SceneNodeSPtr) >
ElementCleaner
template<typename ElementType > using castor3d::ElementCleaner = typedef std::function< void(std::shared_ptr< ElementType >) >
ElementDetacher
template<typename ElementType > using castor3d::ElementDetacher = typedef std::function< void(std::shared_ptr< ElementType >) >
ElementInitialiser
template<typename ElementType > using castor3d::ElementInitialiser = typedef std::function< void(std::shared_ptr< ElementType >) >
ElementMerger
template<typename ElementType , typename KeyType > using castor3d::ElementMerger = typedef std::function< void(CacheBase< ElementType, KeyType > const &, castor::Collection< ElementType, KeyType > &, std::shared_ptr< ElementType >) >
ElementUsages
using castor3d::ElementUsages = typedef castor::FlagCombination< ElementUsage >
FinalCombineProgramMap
using castor3d::FinalCombineProgramMap = typedef std::map< FogType, FinalCombineProgramPtr >
An array of TransparentResolveProgram, one per fog type.
FinalCombineProgramPtr
using castor3d::FinalCombineProgramPtr = typedef std::unique_ptr< TransparentResolveProgram >
FrameListenerCache
using castor3d::FrameListenerCache = typedef Cache< FrameListener, castor::String >
GeometryCache
using castor3d::GeometryCache = typedef ObjectCache< Geometry, castor::String >
GpuBufferBuddyAllocator
using castor3d::GpuBufferBuddyAllocator = typedef castor::BuddyAllocatorT< GpuBufferBuddyAllocatorTraits >
GpuBufferBuddyAllocatorUPtr
using castor3d::GpuBufferBuddyAllocatorUPtr = typedef std::unique_ptr< GpuBufferBuddyAllocator >
GpuFeatures
using castor3d::GpuFeatures = typedef castor::FlagCombination< GpuFeature >
GroupAnimationMap
using castor3d::GroupAnimationMap = typedef std::map< castor::String, GroupAnimation >
InterleavedVertex
using castor3d::InterleavedVertex = typedef InterleavedVertexT< float >
InterleavedVertexArray
using castor3d::InterleavedVertexArray = typedef InterleavedVertexTArray< float >
InterleavedVertexTArray
template<typename T > using castor3d::InterleavedVertexTArray = typedef std::vector< InterleavedVertexT< T > >
LayeredLightPropagationVolumes
using castor3d::LayeredLightPropagationVolumes = typedef LayeredLightPropagationVolumesT< false >
LayeredLightPropagationVolumesG
using castor3d::LayeredLightPropagationVolumesG = typedef LayeredLightPropagationVolumesT< true >
LayeredLightPropagationVolumesGLightType
using castor3d::LayeredLightPropagationVolumesGLightType = typedef std::array< LayeredLightPropagationVolumesGUPtr, size_t(LightType::eCount) >
LayeredLightPropagationVolumesLightType
using castor3d::LayeredLightPropagationVolumesLightType = typedef std::array< LayeredLightPropagationVolumesUPtr, size_t(LightType::eCount) >
LayeredLpvLightPassConfig
using castor3d::LayeredLpvLightPassConfig = typedef LpvLightPassConfigT< LightVolumePassResultArray, LayeredLpvGridConfigUbo >
LightCache
using castor3d::LightCache = typedef ObjectCache< Light, castor::String >
LightPropagationVolumes
using castor3d::LightPropagationVolumes = typedef LightPropagationVolumesT< false >
LightPropagationVolumesG
using castor3d::LightPropagationVolumesG = typedef LightPropagationVolumesT< true >
LightPropagationVolumesGLightType
using castor3d::LightPropagationVolumesGLightType = typedef std::array< LightPropagationVolumesGUPtr, size_t(LightType::eCount) >
LightPropagationVolumesLightType
using castor3d::LightPropagationVolumesLightType = typedef std::array< LightPropagationVolumesUPtr, size_t(LightType::eCount) >
LightsMap
using castor3d::LightsMap = typedef std::array< LightsArray, size_t(LightType::eCount) >
Array of lights per light type.
LineArray
using castor3d::LineArray = typedef std::vector< Line >
An array of Lines.
LpvLightPassConfig
using castor3d::LpvLightPassConfig = typedef LpvLightPassConfigT< LightVolumePassResult, LpvGridConfigUbo >
MeshCache
using castor3d::MeshCache = typedef Cache< Mesh, castor::String >
MeshSubdividerFactory
using castor3d::MeshSubdividerFactory = typedef castor::Factory< MeshSubdivider, castor::String, std::unique_ptr< MeshSubdivider > >
The subdivider factory.
ObjectTransform
using castor3d::ObjectTransform = typedef std::pair< SkeletonAnimationObject *, castor::Matrix4x4f >
OnAnimatedMeshChange
using castor3d::OnAnimatedMeshChange = typedef castor::Signal< OnAnimatedMeshChangeFunction >
OnAnimatedMeshChangeConnection
using castor3d::OnAnimatedMeshChangeConnection = typedef OnAnimatedMeshChange::connection
OnAnimatedMeshChangeFunction
using castor3d::OnAnimatedMeshChangeFunction = typedef std::function< void(AnimatedObjectGroup const &, AnimatedMesh const &) >
OnAnimatedSkeletonChange
using castor3d::OnAnimatedSkeletonChange = typedef castor::Signal< OnAnimatedSkeletonChangeFunction >
OnAnimatedSkeletonChangeConnection
using castor3d::OnAnimatedSkeletonChangeConnection = typedef OnAnimatedSkeletonChange::connection
OnAnimatedSkeletonChangeFunction
using castor3d::OnAnimatedSkeletonChangeFunction = typedef std::function< void(AnimatedObjectGroup const &, AnimatedSkeleton const &) >
OnBackgroundChanged
using castor3d::OnBackgroundChanged = typedef castor::Signal< BackgroundChangedFunc >
OnBackgroundChangedConnection
using castor3d::OnBackgroundChangedConnection = typedef OnBackgroundChanged::connection
OnBillboardMaterialChanged
using castor3d::OnBillboardMaterialChanged = typedef castor::Signal< OnBillboardMaterialChangedFunction >
OnBillboardMaterialChangedConnection
using castor3d::OnBillboardMaterialChangedConnection = typedef OnBillboardMaterialChanged::connection
OnBillboardMaterialChangedFunction
using castor3d::OnBillboardMaterialChangedFunction = typedef std::function< void(BillboardBase const &, MaterialSPtr oldMaterial, MaterialSPtr newMaterial) >
OnCacheChanged
using castor3d::OnCacheChanged = typedef castor::Signal < OnCacheChangedFunction >
OnCacheChangedFunction
using castor3d::OnCacheChangedFunction = typedef std::function< void() >
OnCameraChanged
using castor3d::OnCameraChanged = typedef castor::Signal< OnCameraChangedFunction >
OnCameraChangedConnection
using castor3d::OnCameraChangedConnection = typedef OnCameraChanged::connection
OnCameraChangedFunction
using castor3d::OnCameraChangedFunction = typedef std::function< void(Camera const &) >
OnLightChanged
using castor3d::OnLightChanged = typedef castor::Signal< OnLightChangedFunction >
OnLightChangedConnection
using castor3d::OnLightChangedConnection = typedef OnLightChanged::connection
OnLightChangedFunction
using castor3d::OnLightChangedFunction = typedef std::function< void(Light &) >
OnMaterialChanged
using castor3d::OnMaterialChanged = typedef castor::Signal< OnMaterialChangedFunction >
OnMaterialChangedConnection
using castor3d::OnMaterialChangedConnection = typedef OnMaterialChanged::connection
OnMaterialChangedFunction
using castor3d::OnMaterialChangedFunction = typedef std::function< void(Material const &) >
OnPassChanged
using castor3d::OnPassChanged = typedef castor::Signal< OnPassChangedFunction >
OnPassChangedConnection
using castor3d::OnPassChangedConnection = typedef OnPassChanged::connection
OnPassChangedFunction
using castor3d::OnPassChangedFunction = typedef std::function< void(Pass const &) >
OnSceneChanged
using castor3d::OnSceneChanged = typedef castor::Signal< OnSceneChangedFunction >
OnSceneChangedConnection
using castor3d::OnSceneChangedConnection = typedef OnSceneChanged::connection
OnSceneChangedFunction
using castor3d::OnSceneChangedFunction = typedef std::function< void(Scene const &) >
OnSceneNodeChanged
using castor3d::OnSceneNodeChanged = typedef castor::Signal< OnSceneNodeChangedFunction >
OnSceneNodeChangedConnection
using castor3d::OnSceneNodeChangedConnection = typedef OnSceneNodeChanged::connection
OnSceneNodeChangedFunction
using castor3d::OnSceneNodeChangedFunction = typedef std::function< void(SceneNode const &) >
OnSceneUpdate
using castor3d::OnSceneUpdate = typedef castor::Signal< OnSceneUpdateFunction >
OnSceneUpdateConnection
using castor3d::OnSceneUpdateConnection = typedef OnSceneUpdate::connection
OnSceneUpdateFunction
using castor3d::OnSceneUpdateFunction = typedef std::function< void(Scene const &) >
OnSubmeshMaterialChanged
using castor3d::OnSubmeshMaterialChanged = typedef castor::Signal< OnSubmeshMaterialChangedFunction >
OnSubmeshMaterialChangedConnection
using castor3d::OnSubmeshMaterialChangedConnection = typedef OnSubmeshMaterialChanged::connection
OnSubmeshMaterialChangedFunction
using castor3d::OnSubmeshMaterialChangedFunction = typedef std::function< void(Geometry const &, Submesh const &, MaterialSPtr oldMaterial, MaterialSPtr newMaterial) >
OnTextureUnitChanged
using castor3d::OnTextureUnitChanged = typedef castor::Signal< OnTextureUnitChangedFunction >
OnTextureUnitChangedConnection
using castor3d::OnTextureUnitChangedConnection = typedef OnTextureUnitChanged::connection
OnTextureUnitChangedFunction
using castor3d::OnTextureUnitChangedFunction = typedef std::function< void(TextureUnit const &) >
OverlayCache
using castor3d::OverlayCache = typedef Cache< Overlay, castor::String >
OverlayCategorySet
using castor3d::OverlayCategorySet = typedef std::set< OverlayCategorySPtr, OverlayCategorySort >
Parameters
using castor3d::Parameters = typedef ParametersT< castor::String >
ParticleFactory
using castor3d::ParticleFactory = typedef castor::Factory< CpuParticleSystem , castor::String , std::unique_ptr< CpuParticleSystem > , std::function< std::unique_ptr< CpuParticleSystem >(ParticleSystem &) > >
Particle system factory.
ParticleSystemCache
using castor3d::ParticleSystemCache = typedef ObjectCache< ParticleSystem, castor::String >
ParticleValues
using castor3d::ParticleValues = typedef ParametersT< size_t >
PassFlags
using castor3d::PassFlags = typedef castor::FlagCombination< PassFlag >
PluginCache
using castor3d::PluginCache = typedef Cache< Plugin, castor::String >
Point3rInterpolator
using castor3d::Point3rInterpolator = typedef Interpolator< castor::Point3f >
PointLightPassReflectiveShadow
using castor3d::PointLightPassReflectiveShadow = typedef LightPassReflectiveShadow< LightType::ePoint >
The point lights light pass with shadows.
PointLightPassShadow
using castor3d::PointLightPassShadow = typedef LightPassShadow< LightType::ePoint >
The point lights light pass with shadows.
PostEffectFactory
using castor3d::PostEffectFactory = typedef castor::Factory< PostEffect , castor::String , std::shared_ptr< PostEffect > , std::function< std::shared_ptr< PostEffect >(RenderTarget &, RenderSystem &, Parameters const &) > >
Post effect factory.
ProgramFlags
using castor3d::ProgramFlags = typedef castor::FlagCombination< ProgramFlag >
QuaternionInterpolator
using castor3d::QuaternionInterpolator = typedef Interpolator< castor::Quaternion >
RenderQueueArray
using castor3d::RenderQueueArray = typedef std::vector< std::reference_wrapper< RenderQueue > >
RenderTechniqueCache
using castor3d::RenderTechniqueCache = typedef Cache< RenderTechnique, castor::String >
RenderWindowCache
using castor3d::RenderWindowCache = typedef Cache< RenderWindow, castor::String >
SamplerCache
using castor3d::SamplerCache = typedef Cache< Sampler, castor::String >
SceneCache
using castor3d::SceneCache = typedef Cache< Scene, castor::String >
SceneCulledRenderNodesPtr
using castor3d::SceneCulledRenderNodesPtr = typedef castor::UniquePtr< SceneCulledRenderNodes >
SceneCullerSignal
using castor3d::SceneCullerSignal = typedef castor::Signal< SceneCullerSignalFunction >
SceneCullerSignalConnection
using castor3d::SceneCullerSignalConnection = typedef castor::Connection< SceneCullerSignal >
SceneCullerSignalFunction
using castor3d::SceneCullerSignalFunction = typedef std::function< void(SceneCuller const &) >
SceneFlags
using castor3d::SceneFlags = typedef castor::FlagCombination< SceneFlag >
SceneNodeCache
using castor3d::SceneNodeCache = typedef ObjectCache< SceneNode, castor::String >
SceneRenderNodesPtr
using castor3d::SceneRenderNodesPtr = typedef castor::UniquePtr< SceneRenderNodes >
ShaderPtr
using castor3d::ShaderPtr = typedef std::unique_ptr< ast::Shader >
ShadowMapLightTypeArray
using castor3d::ShadowMapLightTypeArray = typedef std::array< ShadowMapRefArray, size_t(LightType::eCount) >
ShadowMapRefArray
using castor3d::ShadowMapRefArray = typedef std::vector< ShadowMapRefIds >
ShadowMapRefIds
using castor3d::ShadowMapRefIds = typedef std::pair< std::reference_wrapper< ShadowMap >, UInt32Array >
SkeletonAnimationInstanceKeyFrameArray
using castor3d::SkeletonAnimationInstanceKeyFrameArray = typedef std::vector< SkeletonAnimationInstanceKeyFrame >
SpotLightPassLPVShadow
using castor3d::SpotLightPassLPVShadow = typedef LightPassVolumePropagationShadowT< LightType::eSpot >
The spot lights light pass with shadows and LPV.
SpotLightPassReflectiveShadow
using castor3d::SpotLightPassReflectiveShadow = typedef LightPassReflectiveShadow< LightType::eSpot >
The spot lights light pass with shadows.
SpotLightPassShadow
using castor3d::SpotLightPassShadow = typedef LightPassShadow< LightType::eSpot >
The spot lights light pass with shadows.
SubmeshAnimationBuffer
using castor3d::SubmeshAnimationBuffer = typedef SubmeshAnimationBufferT< float >
SubmeshBoundingBoxList
using castor3d::SubmeshBoundingBoxList = typedef std::vector< std::pair< Submesh const *, castor::BoundingBox > >
SubmeshMaterialMap
using castor3d::SubmeshMaterialMap = typedef std::map< Submesh const *, MaterialWPtr >
SubmeshRenderNode
using castor3d::SubmeshRenderNode = typedef ObjectRenderNode< Submesh, Geometry >
TextureFlags
using castor3d::TextureFlags = typedef castor::FlagCombination< TextureFlag >
TextureFlagsArray
using castor3d::TextureFlagsArray = typedef std::vector< TextureFlagsId >
TextureRotateSpeed
using castor3d::TextureRotateSpeed = typedef castor::SpeedT< castor::Angle, castor::Seconds >
TextureSpaces
using castor3d::TextureSpaces = typedef castor::FlagCombination< TextureSpace >
TextureTranslateSpeed
using castor3d::TextureTranslateSpeed = typedef castor::SpeedT< castor::Point2f, castor::Seconds >
TextureViewCRef
using castor3d::TextureViewCRef = typedef std::reference_wrapper< TextureView const >
TextureViewCRefArray
using castor3d::TextureViewCRefArray = typedef std::vector< TextureViewCRef >
ToneMappingFactory
using castor3d::ToneMappingFactory = typedef castor::Factory< ToneMapping , castor::String , ToneMappingSPtr , std::function< ToneMappingSPtr(Engine &, RenderDevice const &, HdrConfigUbo &, Parameters const &) > >
Tone mapping factory.
TransformArray
using castor3d::TransformArray = typedef std::vector< ObjectTransform >
Enumeration Type Documentation
AnimationState
enum castor3d::AnimationState : uint8_t strong
Animation State Enumerator.
Enumerator
ePlaying
Playing animation state.
eStopped
Stopped animation state.
ePaused
Paused animation state.
eCount
eMin
eMax
AnimationType
enum castor3d::AnimationType : uint8_t strong
Animation types enumeration.
Enumerator
eMovable
Scene node animation.
eSkeleton
Skeleton animation.
eMesh
Submesh animation (morphing).
eTexture
Texture animation.
eCount
eMin
eMax
BackgroundType
enum castor3d::BackgroundType strong
Scene background types enumeration.
Enumerator
eColour
eImage
eSkybox
eCount
eMin
eMax
BillboardSize
enum castor3d::BillboardSize strong
Billboard sizing types enumeration.
Enumerator
eDynamic
Billboards size changes with camera position.
eFixed
Billboards size doesn't change.
eCount
eMin
eMax
BillboardType
enum castor3d::BillboardType strong
Billboard rendering types enumeration.
Enumerator
eSpherical
Billboards always face the camera.
eCylindrical
Billboards rotate only on Y axis.
eCount
eMin
eMax
BlendMode
enum castor3d::BlendMode : uint8_t strong
Blending modes enumeration.
Enumerator
eNoBlend
Order dependent blending.
eAdditive
Order independent, add the components.
eMultiplicative
Order independent, multiply the components.
eInterpolative
Order dependent, interpolate the components.
eABuffer
Order independent, using A-buffer, not implemented yet.
eDepthPeeling
Order independent, using depth peeling, not implemented yet.
eCount
eMin
eMax
BorderPosition
enum castor3d::BorderPosition strong
Text wrapping modes, handles the way text is cut when it overflows the overlay width.
Enumerator
eInternal
The border is outside the overlay.
eMiddle
The border is middle outside and middle inside the overlay.
eExternal
The border is outside the overlay.
eCount
eMin
eMax
ChunkType
enum castor3d::ChunkType : uint64_t strong
Binary data chunk types enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
15/04/2013
Enumerator
eUnknown
eCmshFile
eCmshHeader
eCmshVersion
eName
eMesh
eSkeleton
eSkeletonGlobalInverse
eSkeletonBone
eBoneParentName
eBoneOffsetMatrix
eSubmesh
eSubmeshTopology
eSubmeshVertexCount
eSubmeshVertex
eSubmeshBoneCount
eSubmeshBones
eSubmeshMatrixCount
eSubmeshMatrices
eSubmeshFaceCount
eSubmeshFaces
eAnimable
eAnimation
eAnimLength
eSkeletonAnimation
eMeshAnimation
eAnimInterpolator
eAnimationObject
eSkeletonAnimationNode
eSkeletonAnimationBone
eMovingTransform
eKeyframeCount
eKeyframes
eBonesComponent
eMeshAnimationKeyFrame
eMeshAnimationKeyFrameTime
eMeshAnimationKeyFrameSubmeshID
eMeshAnimationKeyFrameBufferSize
eMeshAnimationKeyFrameBufferData
eSkeletonAnimationKeyFrame
eSkeletonAnimationKeyFrameTime
eSkeletonAnimationKeyFrameObjectType
eSkeletonAnimationKeyFrameObjectName
eSkeletonAnimationKeyFrameObjectTransform
eSubmeshIndexComponentCount
eSubmeshIndexCount
eSubmeshIndices
CSCNSection
enum castor3d::CSCNSection : uint32_t strong
Defines all the sections and subsections of a scene file.
Enumerator
eRoot
eScene
eWindow
eSampler
eCamera
eViewport
eLight
eNode
eObject
eObjectMaterials
eFont
ePanelOverlay
eBorderPanelOverlay
eTextOverlay
eMesh
eSubmesh
eMaterial
ePass
eTextureUnit
eRenderTarget
eShaderProgram
eShaderStage
eShaderUBO
eUBOVariable
eBillboard
eBillboardList
eAnimGroup
eAnimation
eSkybox
eParticleSystem
eParticle
eSsao
eSubsurfaceScattering
eTransmittanceProfile
eHdrConfig
eShadows
eMeshDefaultMaterials
eRsm
eLpv
eRaw
ePcf
eVsm
eTextureAnimation
eVoxelConeTracing
CubeMapFace
enum castor3d::CubeMapFace : uint8_t strong
Cube map faces.
Enumerator
ePositiveX
Face on positive X
eNegativeX
Face on negative X
ePositiveY
Face on positive Y
eNegativeY
Face on negative Y
ePositiveZ
Face on positive Z
eNegativeZ
Face on negative Z
eCount
eMin
eMax
DsTexture
enum castor3d::DsTexture : uint8_t strong
Enumerator of textures used by the deferred renderer's GBUffer.
Enumerator
eDepth
eData1
eData2
eData3
eData4
eData5
eCount
eMin
eMax
ElementUsage
enum castor3d::ElementUsage : uint32_t strong
Element usage enumeration.
Enumerator
eUnknown
Position coords.
ePosition
Position coords.
eNormal
Normal coords.
eTangent
Tangent coords.
eBitangent
Bitangent coords.
eDiffuse
Diffuse colour.
eTexCoords
Texture coordinates.
eBoneIds0
Bone IDs 0.
eBoneIds1
Bone IDs 1.
eBoneWeights0
Bone weights 0.
eBoneWeights1
Bone weights 1.
eTransform
Instantiation matrix.
eMatIndex
Instantiation material index.
EventType
enum castor3d::EventType : uint8_t strong
Frame Event Type enumeration.
Enumerator
ePreRender
This kind of event happens before any render, device context is active (so be fast !!).
eQueueRender
This kind of event happens after the render, before buffers' swap.
ePostRender
This kind of event happens after the buffer' swap.
eCount
eMin
eMax
FogType
enum castor3d::FogType strong
Fog types enumeration.
Enumerator
eDisabled
No fog.
eLinear
Fog intensity increases linearly with distance to camera.
eExponential
Fog intensity increases exponentially with distance to camera.
eSquaredExponential
Fog intensity increases even more with distance to camera.
eCount
eMin
eMax
FrustumCorner
enum castor3d::FrustumCorner strong
Frustum corners enumeration.
Enumerator
eFarLeftBottom
Far left bottom corner.
eFarLeftTop
Far left top corner.
eFarRightTop
Far right top corner.
eFarRightBottom
Far right bottom corner.
eNearLeftBottom
Near left bottom corner.
eNearLeftTop
Near left top corner.
eNearRightTop
Near right top corner.
eNearRightBottom
Near right bottom corner.
eCount
eMin
eMax
FrustumPlane
enum castor3d::FrustumPlane strong
Frustum planes enumeration.
Enumerator
eNear
Near plane.
eFar
Far plane.
eLeft
Left plane.
eRight
Right plane.
eTop
Top plane.
eBottom
Bottom plane.
eCount
eMin
eMax
GlobalIlluminationType
enum castor3d::GlobalIlluminationType : uint8_t strong
Enumerator of supported global illumination algorithms.
Enumerator
eNone
eRsm
eVoxelConeTracing
eLpv
eLpvG
eLayeredLpv
eLayeredLpvG
eCount
eMin
eMax
GpuFeature
enum castor3d::GpuFeature : uint32_t strong
All supported GPU feature flags.
Enumerator
eStereoRendering
Tells whether or not the selected render API supports stereographic rendering.
eShaderStorageBuffers
Tells whether or not the selected render API supports shader stoarage buffers.
GpuMax
enum castor3d::GpuMax : uint32_t strong
All supported GPU feature flags.
Enumerator
eTexture1DSize
eTexture2DSize
eTexture3DSize
eTextureCubeSize
eTextureLayers
eSamplerLodBias
eClipDistances
eFramebufferWidth
eFramebufferHeight
eFramebufferLayers
eFramebufferSamples
eTexelBufferSize
eUniformBufferSize
eStorageBufferSize
eViewportWidth
eViewportHeight
eViewports
eCount
eMin
eMax
HAlign
enum castor3d::HAlign strong
Horizontal alignments for text overlays.
Enumerator
eLeft
Aligned on the left.
eCenter
Centered horizontally.
eRight
Aligned on the right.
eCount
eMin
eMax
HandlerEventType
enum castor3d::HandlerEventType : uint8_t strong
Enumeration of supported handler events.
Enumration des vnements de gestionnaire supportes.
Enumerator
eActivate
Handler activated.
eDeactivate
Handler deactivated.
eCount
eMin
eMax
InterpolatorType
enum castor3d::InterpolatorType : uint8_t strong
Interpolation modes enumeration.
Enumerator
eNearest
No interpolation.
eLinear
Linear mode.
eCount
eMin
eMax
KeyboardEventType
enum castor3d::KeyboardEventType : uint8_t strong
Enumeration of supported keyboard events.
Enumration des vnement clavier supports.
Enumerator
ePushed
A key is pushed.
eReleased
A key is released.
eChar
A displayable char key is stroked.
eCount
eMin
eMax
KeyboardKey
enum castor3d::KeyboardKey strong
Keyboard keys enumeration.
Enumerator
eNone
eBackspace
eTab
eReturn
eEscape
eSpace
eDelete
eStart
eLButton
eRButton
eCancel
eMButton
eClear
eShift
eAlt
eControl
eMenu
ePause
eCapital
eEnd
eHome
eLeft
eUp
eRight
edown
eSelect
ePrint
eExecute
eSnapshot
eInsert
eHelp
eNumpad0
eNumpad1
eNumpad2
eNumpad3
eNumpad4
eNumpad5
eNumpad6
eNumpad7
eNumpad8
eNumpad9
eMultiply
eAdd
eSeparator
eSubtract
eDecimal
eDivide
eF1
eF2
eF3
eF4
eF5
eF6
eF7
eF8
eF9
eF10
eF11
eF12
eF13
eF14
eF15
eF16
eF17
eF18
eF19
eF20
eF21
eF22
eF23
eF24
eNumlock
eScroll
ePageUp
ePageDown
eNumpadSpace
eNumpadTab
eNumpadEnter
eNumpadF1
eNumpadF2
eNumpadF3
eNumpadF4
eNumpadHome
eNumpadLeft
eNumpadUp
eNumpadRight
eNumpadDown
eNumpadPageUp
eNumpadPageDown
eNumpadEnd
eNumpadBegin
eNumpadInsert
eNumpadDelete
eNumpadEqual
eNumpadMultiply
eNumpadAdd
eNumpadSeparator
eNumpadSubtract
eNumpadDecimal
eNumpadDivide
LightType
enum castor3d::LightType : uint8_t strong
Light types enumeration.
Enumerator
eDirectional
Directional light type.
ePoint
Point light type.
eSpot
Spot light type.
eCount
eMin
eMax
LpTexture
enum castor3d::LpTexture : uint8_t strong
Enumerator of textures used by the lighting pass in deferred rendering.
Enumerator
eDepth
eDiffuse
eSpecular
eIndirectDiffuse
eIndirectSpecular
eCount
eMin
eMax
LpvTexture
enum castor3d::LpvTexture : uint8_t strong
Enumerator of textures used by the light volume GI passes.
Enumerator
eR
eG
eB
eCount
eMin
eMax
MaterialType
enum castor3d::MaterialType strong
Supported material types enumeration.
Enumerator
ePhong
Phong (non PBR).
eMetallicRoughness
Metallic/Roughness PBR.
eSpecularGlossiness
Specular/Glossiness PBR.
eCount
eMin
eMax
MouseButton
enum castor3d::MouseButton strong
Mouse buttons enumeration.
Enumerator
eLeft
Left mouse button.
eMiddle
Middle mouse button.
eRight
Right mouse button.
eCount
eMin
eMax
MouseEventType
enum castor3d::MouseEventType : uint8_t strong
Enumeration of supported mouse events.
Enumration des vnement de souris supports.
Enumerator
eMove
The mouse moves.
eEnter
The mouse enters an handler's zone.
eHover
The mouse remains still in an handler's zone during hover time.
eLeave
The mouse leaves an handler's zone.
ePushed
One mouse button is pushed.
eReleased
One mouse button is released.
eWheel
One mouse wheel is rolled.
eCount
eMin
eMax
MovableType
enum castor3d::MovableType : uint8_t strong
Movable object types enumerator.
Remarks
There are four movable object types : camera, geometry, light and billboard.
Enumerator
eCamera
eGeometry
eLight
eBillboard
eParticleEmitter
eCount
eMin
eMax
OverlayType
enum castor3d::OverlayType : uint8_t strong
Overlay types enumeration.
Enumerator
ePanel
eBorderPanel
eText
eCount
eMin
eMax
ParallaxOcclusionMode
enum castor3d::ParallaxOcclusionMode strong
Parallax occlusion modes enumeration.
Enumerator
eNone
eOne
eRepeat
eCount
eMin
eMax
ParticleFormat
enum castor3d::ParticleFormat strong
Enumerator
eInt
eVec2i
eVec3i
eVec4i
eUInt
eVec2ui
eVec3ui
eVec4ui
eFloat
eVec2f
eVec3f
eVec4f
eMat2f
eMat3f
eMat4f
eCount
eMin
eMax
PassFlag
enum castor3d::PassFlag : uint16_t strong
Pass specific flags.
Enumerator
eNone
No flag.
eAlphaBlending
Shader using alpha blending.
eAlphaTest
Shader using alpha test.
eMetallicRoughness
Shader for Metallic/Roughness PBR material (if not set, will use phong material code).
eSpecularGlossiness
Shader for Specular/Glossiness PBR material (if not set, will use phong material code).
eSubsurfaceScattering
Shader for Subsurface Scattering.
eDistanceBasedTransmittance
Shader using distance based transmittance when computing Subsurface Scattering.
eParallaxOcclusionMappingOne
Shader using parallax occlusion mapping.
eParallaxOcclusionMappingRepeat
Shader using parallax occlusion mapping.
eReflection
Reflection map.
eRefraction
Refraction map.
eAll
All flags.
PickNodeType
enum castor3d::PickNodeType : uint8_t strong
The picking node types.
Enumerator
eNone
eStatic
eInstantiatedStatic
eSkinning
eInstantiatedSkinning
eMorphing
eBillboard
PluginType
enum castor3d::PluginType : uint8_t strong
Plugin types enumeration.
Enumerator
eImporter
Importer plug-in.
eDivider
Mesh Divider plug-in.
eGenerator
Procedural generator.
eToneMapping
Tone mapping plug-in.
ePostEffect
Post effect plug-in.
eGeneric
Generic plug-in.
eParticle
Particle plug-in.
eCount
eMin
eMax
ProgramFlag
enum castor3d::ProgramFlag : uint32_t strong
Flags to use when looking for an automatically generated program.
Enumerator
eNone
No flag.
eInstantiation
Program using instanciation.
eSkinning
Program using skeleton animations.
eBillboards
Program used by billboards.
eMorphing
Program using per-vertex animations.
ePicking
Picking pass program.
eLighting
Shader supporting lighting.
eSpherical
Shader for spherical billboards.
eFixedSize
Shader for fixed size billboards.
eInstanceMult
Program using and instances multiplier.
eShadowMapDirectional
Shader used to render a shadow map for directional light.
eShadowMapSpot
Shader used to render a shadow map for spot light.
eShadowMapPoint
Shader used to render a shadow map for point light.
eEnvironmentMapping
Shader used to render an environment map.
eDepthPass
Shader for the depth pre-pass.
eInvertNormals
Vertex shader inverts normals (for front culling).
eHasGeometry
Vertex shader inverts normals (for front culling).
eConservativeRasterization
Voxelization uses conservative rasterization.
eAll
All flags.
RenderMode
enum castor3d::RenderMode : uint8_t strong
The render pass modes, regarding transparency.
Enumerator
eOpaqueOnly
eTransparentOnly
eBoth
eCount
eMin
eMax
SceneFlag
enum castor3d::SceneFlag : uint16_t strong
Scene flags enumeration.
Enumerator
eNone
No flag.
eFogLinear
Linear fog.
eFogExponential
Exponential fog.
eFogSquaredExponential
Squared exponential fog.
eShadowBegin
Shadow enabling, by light source type.
eShadowDirectional
eShadowPoint
eShadowSpot
eShadowEnd
eShadowAny
eLpvGI
Light Propagation Volumes enabling.
eLayeredLpvGI
eVoxelConeTracing
Voxel Cone Tracing enabling.
eAll
All flags.
ShadowType
enum castor3d::ShadowType strong
Shadow filter types enumeration.
Enumerator
eNone
No shadows at all.
eRaw
No filtering.
ePCF
PCF filtering.
eVariance
Variance shadow mapping.
eCount
eMin
eMax
SkeletonAnimationObjectType
enum castor3d::SkeletonAnimationObjectType : uint8_t strong
Class which represents the moving things.
Author
Sylvain DOREMUS
Version
0.1
Date
09/02/2010
Remarks
Manages translation, scaling, rotation of the thing.
Enumerator
eNode
Node objects.
eBone
Bone objects.
eCount
eMin
eMax
SmTexture
enum castor3d::SmTexture : uint8_t strong
Enumerator of textures used in deferred rendering.
Enumerator
eDepth
eNormalLinear
eVariance
ePosition
eFlux
eCount
eMin
eMax
TargetType
enum castor3d::TargetType : uint8_t strong
RenderTarget supported types.
Enumerator
eWindow
eTexture
eCount
eMin
eMax
TextLineSpacingMode
enum castor3d::TextLineSpacingMode strong
Text line spacing modes, handles the way lines are spaced, which each other, inside one TextOverlay.
Enumerator
eOwnHeight
The height of each line is its own height.
eMaxLineHeight
The height of the lines is the maximum height between them.
eMaxFontHeight
The height of the lines is the maximum height from the font's characters.
eCount
eMin
eMax
TextTexturingMode
enum castor3d::TextTexturingMode strong
Text texturing modes, handles the way textures are appied to text overlays.
Enumerator
eLetter
The texture is repeated on each character of the text.
eText
The texture is applied on the whole text.
eCount
eMin
eMax
TextureFlag
enum castor3d::TextureFlag : uint16_t strong
Texture channels flags.
Enumerator
eNone
No texture.
eHeight
Height map.
eOpacity
Opacity map.
eNormal
Normal map.
eEmissive
Emissive map.
eOcclusion
Occlusion map.
eTransmittance
Light transmittance map.
eDiffuse
Diffuse map.
eAlbedo
Albedo map.
eSpecular
Specular map.
eMetalness
Metalness map.
eGlossiness
Glossiness map.
eShininess
Shininess map.
eRoughness
Roughness map.
eAll
Mask for all the texture channels.
eAllButOpacity
Mask for all the texture channels except for opacity.
eAllButColourAndOpacity
Mask for all the texture channels except for opacity and colour.
eAllButNormalAndOpacity
Mask for all the texture channels except for opacity and normal.
TextureSpace
enum castor3d::TextureSpace : uint16_t strong
Lists the possible spaces for a texture.
Enumerator
eNormalised
Modifier: Normalized value (Colour in [-1, 1] range, depth in [0, 1] range).
eYInverted
Modifier: Y inverted space.
eColour
Colour texture in R.
eDepth
Depth in [near, far] range.
eTangentSpace
Tangent space data.
eObjectSpace
Object space data.
eWorldSpace
World space data.
eViewSpace
View space data.
eClipSpace
Clip space data.
eStencil
Stencil data.
TextWrappingMode
enum castor3d::TextWrappingMode strong
Text wrapping modes, handles the way text is cut when it overflows the overlay width.
Enumerator
eNone
The text is cut.
eBreak
The text jumps to next line.
eBreakWords
The text jumps to next line without cutting words.
eCount
eMin
eMax
UserInputEventType
enum castor3d::UserInputEventType strong
Supported events types enumeration.
Enumerator
eMouse
Mouse event type.
eKeyboard
Keyboard event type.
eHandler
Handle event type.
eCount
eMin
eMax
VAlign
enum castor3d::VAlign strong
Vertical alignments for text overlays.
Enumerator
eTop
Aligned on the top.
eCenter
Centered vertically.
eBottom
Aligned on the bottom.
eCount
eMin
eMax
ViewportType
enum castor3d::ViewportType : uint8_t strong
The viewport projection types enumeration.
Enumerator
eOrtho
ePerspective
eFrustum
eCount
eMin
eMax
WbTexture
enum castor3d::WbTexture : uint8_t strong
Enumerator of textures used in weighted blend OIT.
Enumerator
eDepth
eAccumulation
eRevealage
eVelocity
eCount
eMin
eMax
Function Documentation
bindShadowMaps()
void castor3d::bindShadowMaps (PipelineFlags const & pipelineFlags, ShadowMapLightTypeArray const & shadowMaps, ashes::WriteDescriptorSetArray & writes, uint32_t & index)
Writes the shadow maps descriptors to the given writes.
bindTexture()
void castor3d::bindTexture (ashes::ImageView const & view, ashes::Sampler const & sampler, ashes::WriteDescriptorSetArray & writes, uint32_t & index)
Writes the image view and sampler descriptor to the given writes.
checkFlags()
C3D_API TextureFlagsArray::const_iterator castor3d::checkFlags (TextureFlagsArray const & flags, TextureFlag flag)
cleanupGlslang()
C3D_API void castor3d::cleanupGlslang ()
Cleans up glslang globals.
compileGlslToSpv()
C3D_API UInt32Array castor3d::compileGlslToSpv (RenderDevice const & device, VkShaderStageFlagBits stage, std::string const & shader)
Transpiles a GLSL shader to SPIR-V.
Parameters
device The GPU device.
stage The shader stage.
shader The GLSL shader.
compileShader() [1/2]
C3D_API SpirVShader castor3d::compileShader (RenderDevice const & device, ShaderModule const & module)
Referenced by makeShaderState().
compileShader() [2/2]
C3D_API SpirVShader castor3d::compileShader (RenderSystem const & renderSystem, ShaderModule const & module)
convert() [1/5]
castor::Matrix4x4f castor3d::convert (std::array< float, 16 > const & value)
convert() [2/5]
VkClearColorValue castor3d::convert (castor::RgbaColour const & value)
convert() [3/5]
castor::RgbaColour castor3d::convert (VkClearColorValue const & value)
convert() [4/5]
C3D_API VkFormat castor3d::convert (castor::PixelFormat format)
convert() [5/5]
C3D_API castor::PixelFormat castor3d::convert (VkFormat format)
cpuUpdate()
void castor3d::cpuUpdate (UniformBufferOffsetT< ModelInstancesUboConfiguration > & buffer, UInt32Array const & instances)
createSampler()
SamplerSPtr castor3d::createSampler (Engine & engine, castor::String const & baseName, VkFilter filter, VkImageSubresourceRange const * range)
createTextureLayout() [1/2]
C3D_API TextureLayoutSPtr castor3d::createTextureLayout (Engine const & engine, castor::Path const & relative, castor::Path const & folder)
createTextureLayout() [2/2]
C3D_API TextureLayoutSPtr castor3d::createTextureLayout (Engine const & engine, castor::String const & name, castor::PxBufferBaseUPtr buffer, bool isStatic = false)
CU_DeclareArray() [1/5]
castor3d::CU_DeclareArray (LayeredLightVolumeGIPassUPtr , lpv::ResolvePassCount , LayeredLightVolumeGIPass)
CU_DeclareArray() [2/5]
castor3d::CU_DeclareArray (LightVolumeGIPassUPtr , lpv::ResolvePassCount , LightVolumeGIPass)
CU_DeclareArray() [3/5]
castor3d::CU_DeclareArray (LightPropagationPassUPtr , lpv::PropagationPassCount , LightPropagationPass)
CU_DeclareArray() [4/5]
castor3d::CU_DeclareArray (PluginStrMap , PluginType::eCount , PluginStrMap)
CU_DeclareArray() [5/5]
castor3d::CU_DeclareArray (DynamicLibraryPtrPathMap , PluginType::eCount , DynamicLibraryPtrPathMap)
CU_DeclareCUSmartPtr() [1/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , VoxelBufferToTexture , C3D_API)
CU_DeclareCUSmartPtr() [2/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , VoxelizePass , C3D_API)
CU_DeclareCUSmartPtr() [3/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , VoxelSecondaryBounce , C3D_API)
CU_DeclareCUSmartPtr() [4/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , Voxelizer , C3D_API)
CU_DeclareCUSmartPtr() [5/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , LayeredLightVolumeGIPass , C3D_API)
CU_DeclareCUSmartPtr() [6/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , Texture3DTo2D , C3D_API)
CU_DeclareCUSmartPtr() [7/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , RenderTechniquePass , C3D_API)
CU_DeclareCUSmartPtr() [8/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , LightVolumeGIPass , C3D_API)
CU_DeclareCUSmartPtr() [9/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , WeightedBlendRendering , C3D_API)
CU_DeclareCUSmartPtr() [10/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , DeferredRendering , C3D_API)
CU_DeclareCUSmartPtr() [11/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , OpaqueResolvePass , C3D_API)
CU_DeclareCUSmartPtr() [12/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , SsaoPass , C3D_API)
CU_DeclareCUSmartPtr() [13/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , GeometryInjectionPass , C3D_API)
CU_DeclareCUSmartPtr() [14/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , LayeredLightPropagationVolumes , C3D_API)
CU_DeclareCUSmartPtr() [15/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , LayeredLightPropagationVolumesG , C3D_API)
CU_DeclareCUSmartPtr() [16/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , LightInjectionPass , C3D_API)
CU_DeclareCUSmartPtr() [17/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , LightPropagationPass , C3D_API)
CU_DeclareCUSmartPtr() [18/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , LightPropagationVolumes , C3D_API)
CU_DeclareCUSmartPtr() [19/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , LightPropagationVolumesG , C3D_API)
CU_DeclareCUSmartPtr() [20/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , ShadowMap , C3D_API)
CU_DeclareCUSmartPtr() [21/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , LightVolumePassResult , C3D_API)
CU_DeclareCUSmartPtr() [22/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , ShadowMapPass , C3D_API)
CU_DeclareCUSmartPtr() [23/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , CombinePass , C3D_API)
CU_DeclareCUSmartPtr() [24/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , DepthPass , C3D_API)
CU_DeclareCUSmartPtr() [25/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , DownscalePass , C3D_API)
CU_DeclareCUSmartPtr() [26/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , GaussianBlur , C3D_API)
CU_DeclareCUSmartPtr() [27/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , LineariseDepthPass , C3D_API)
CU_DeclareCUSmartPtr() [28/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , RenderQuad , C3D_API)
CU_DeclareCUSmartPtr() [29/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , RenderGrid , C3D_API)
CU_DeclareCUSmartPtr() [30/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , StencilPass , C3D_API)
CU_DeclareCUSmartPtr() [31/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , SubsurfaceScatteringPass , C3D_API)
CU_DeclareCUSmartPtr() [32/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , ShaderBuffer , C3D_API)
CU_DeclareCUSmartPtr() [33/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , ShaderProgram , C3D_API)
CU_DeclareCUSmartPtr() [34/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , BorderPanelOverlay , C3D_API)
CU_DeclareCUSmartPtr() [35/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , DebugOverlays , C3D_API)
CU_DeclareCUSmartPtr() [36/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , FontTexture , C3D_API)
CU_DeclareCUSmartPtr() [37/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , Overlay , C3D_API)
CU_DeclareCUSmartPtr() [38/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , OverlayCategory , C3D_API)
CU_DeclareCUSmartPtr() [39/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , OverlayFactory , C3D_API)
CU_DeclareCUSmartPtr() [40/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , OverlayRenderer , C3D_API)
CU_DeclareCUSmartPtr() [41/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , PanelOverlay , C3D_API)
CU_DeclareCUSmartPtr() [42/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , TextOverlay , C3D_API)
CU_DeclareCUSmartPtr() [43/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , LpvGridConfigUbo , C3D_API)
CU_DeclareCUSmartPtr() [44/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , LpvLightConfigUbo , C3D_API)
CU_DeclareCUSmartPtr() [45/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , LayeredLpvGridConfigUbo , C3D_API)
CU_DeclareCUSmartPtr() [46/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , PickingPass , C3D_API)
CU_DeclareCUSmartPtr() [47/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , RenderDevice , C3D_API)
CU_DeclareCUSmartPtr() [48/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , RenderLoop , C3D_API)
CU_DeclareCUSmartPtr() [49/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , RenderPassTimer , C3D_API)
CU_DeclareCUSmartPtr() [50/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , RenderPipeline , C3D_API)
CU_DeclareCUSmartPtr() [51/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , RenderSystem , C3D_API)
CU_DeclareCUSmartPtr() [52/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , RenderTarget , C3D_API)
CU_DeclareCUSmartPtr() [53/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , RenderWindow , C3D_API)
CU_DeclareCUSmartPtr() [54/54]
castor3d::CU_DeclareCUSmartPtr (castor3d , Viewport , C3D_API)
CU_DeclareMap() [1/58]
castor3d::CU_DeclareMap (RenderPipelineRPtr , StaticRenderNodePtrArray , StaticRenderNodesPtrByPipeline)
CU_DeclareMap() [2/58]
castor3d::CU_DeclareMap (RenderPipelineRPtr , SkinningRenderNodePtrArray , SkinningRenderNodesPtrByPipeline)
CU_DeclareMap() [3/58]
castor3d::CU_DeclareMap (RenderPipelineRPtr , MorphingRenderNodePtrArray , MorphingRenderNodesPtrByPipeline)
CU_DeclareMap() [4/58]
castor3d::CU_DeclareMap (RenderPipelineRPtr , BillboardRenderNodePtrArray , BillboardRenderNodesPtrByPipeline)
CU_DeclareMap() [5/58]
castor3d::CU_DeclareMap (SubmeshRPtr , StaticRenderNodePtrArray , SubmeshStaticRenderNodesPtr)
CU_DeclareMap() [6/58]
castor3d::CU_DeclareMap (SubmeshRPtr , SkinningRenderNodePtrArray , SubmeshSkinningRenderNodesPtr)
CU_DeclareMap() [7/58]
castor3d::CU_DeclareMap (PassRPtr , SubmeshStaticRenderNodesPtrMap , SubmeshStaticRenderNodesPtrByPass)
CU_DeclareMap() [8/58]
castor3d::CU_DeclareMap (PassRPtr , SubmeshSkinningRenderNodesPtrMap , SubmeshSkinninRenderNodesPtrByPass)
CU_DeclareMap() [9/58]
castor3d::CU_DeclareMap (RenderPipelineRPtr , SubmeshStaticRenderNodesPtrByPassMap , SubmeshStaticRenderNodesPtrByPipeline)
CU_DeclareMap() [10/58]
castor3d::CU_DeclareMap (RenderPipelineRPtr , SubmeshSkinninRenderNodesPtrByPassMap , SubmeshSkinningRenderNodesPtrByPipeline)
CU_DeclareMap() [11/58]
castor3d::CU_DeclareMap (CulledSubmesh const * , StaticRenderNode , StaticRenderNode)
CU_DeclareMap() [12/58]
castor3d::CU_DeclareMap (CulledSubmesh const * , SkinningRenderNode , SkinningRenderNode)
CU_DeclareMap() [13/58]
castor3d::CU_DeclareMap (uint32_t , MeshAnimationInstanceSubmesh , MeshAnimationInstanceSubmesh)
MeshAnimationInstanceSubmesh map, sorted by submesh ID.
CU_DeclareMap() [14/58]
castor3d::CU_DeclareMap (CulledSubmesh const * , MorphingRenderNode , MorphingRenderNode)
CU_DeclareMap() [15/58]
castor3d::CU_DeclareMap (CulledBillboard const * , BillboardRenderNode , BillboardRenderNode)
CU_DeclareMap() [16/58]
castor3d::CU_DeclareMap (RenderPipelineRPtr , StaticRenderNodeMap , StaticRenderNodesByPipeline)
CU_DeclareMap() [17/58]
castor3d::CU_DeclareMap (RenderPipelineRPtr , SkinningRenderNodeMap , SkinningRenderNodesByPipeline)
CU_DeclareMap() [18/58]
castor3d::CU_DeclareMap (RenderPipelineRPtr , MorphingRenderNodeMap , MorphingRenderNodesByPipeline)
CU_DeclareMap() [19/58]
castor3d::CU_DeclareMap (RenderPipelineRPtr , BillboardRenderNodeMap , BillboardRenderNodesByPipeline)
CU_DeclareMap() [20/58]
castor3d::CU_DeclareMap (SubmeshRPtr , StaticRenderNodeMap , SubmeshStaticRenderNodes)
CU_DeclareMap() [21/58]
castor3d::CU_DeclareMap (castor::String , SubmeshSPtr , SubmeshPtrStr)
CU_DeclareMap() [22/58]
castor3d::CU_DeclareMap (SubmeshRPtr , SkinningRenderNodeMap , SubmeshSkinningRenderNodes)
CU_DeclareMap() [23/58]
castor3d::CU_DeclareMap (Submesh const * , castor::BoundingBox , SubmeshBoundingBox)
CU_DeclareMap() [24/58]
castor3d::CU_DeclareMap (PassRPtr , SubmeshStaticRenderNodesMap , SubmeshStaticRenderNodesByPass)
CU_DeclareMap() [25/58]
castor3d::CU_DeclareMap (Submesh const * , castor::BoundingSphere , SubmeshBoundingSphere)
CU_DeclareMap() [26/58]
castor3d::CU_DeclareMap (PassRPtr , SubmeshSkinningRenderNodesMap , SubmeshSkinninRenderNodesByPass)
CU_DeclareMap() [27/58]
castor3d::CU_DeclareMap (uint32_t , SubmeshAnimationBuffer , SubmeshAnimationBuffer)
CU_DeclareMap() [28/58]
castor3d::CU_DeclareMap (RenderPipelineRPtr , SubmeshStaticRenderNodesByPassMap , SubmeshStaticRenderNodesByPipeline)
CU_DeclareMap() [29/58]
castor3d::CU_DeclareMap (RenderPipelineRPtr , SubmeshSkinninRenderNodesByPassMap , SubmeshSkinningRenderNodesByPipeline)
CU_DeclareMap() [30/58]
castor3d::CU_DeclareMap (castor::String , BoneSPtr , BonePtrStr)
Bone pointer map sorted by name.
CU_DeclareMap() [31/58]
castor3d::CU_DeclareMap (uint32_t , int , IntUInt)
CU_DeclareMap() [32/58]
castor3d::CU_DeclareMap (castor::String , int , IntStr)
CU_DeclareMap() [33/58]
castor3d::CU_DeclareMap (int , castor::String , StrInt)
CU_DeclareMap() [34/58]
castor3d::CU_DeclareMap (castor::String , SkeletonAnimationInstanceObjectSPtr , SkeletonAnimationInstanceObjectPtrStr)
MovingObject pointer map, sorted by name.
CU_DeclareMap() [35/58]
castor3d::CU_DeclareMap (castor::String , MeshSPtr , MeshPtrStr)
Mesh pointer array.
CU_DeclareMap() [36/58]
castor3d::CU_DeclareMap (castor::String , SkeletonAnimationObjectSPtr , SkeletonAnimationObjectPtrStr)
SkeletonAnimationObject pointer map, sorted by name.
CU_DeclareMap() [37/58]
castor3d::CU_DeclareMap (castor::String , AnimatedObjectGroupSPtr , AnimatedObjectGroupPtrStr)
AnimatedObjectGroup pointer map, sorted by name.
CU_DeclareMap() [38/58]
castor3d::CU_DeclareMap (castor::String , AnimatedObjectSPtr , AnimatedObjectPtrStr)
AnimatedObject pointer map, sorted by name.
CU_DeclareMap() [39/58]
castor3d::CU_DeclareMap (castor::String , AnimationInstanceUPtr , AnimationInstancePtrStr)
Animation pointer map, sorted by name.
CU_DeclareMap() [40/58]
castor3d::CU_DeclareMap (castor::String , AnimationSPtr , AnimationPtrStr)
Animation pointer map, sorted by name.
CU_DeclareMap() [41/58]
castor3d::CU_DeclareMap (castor::String , FrameListenerSPtr , FrameListenerPtrStr)
CU_DeclareMap() [42/58]
castor3d::CU_DeclareMap (castor::String , LightSPtr , LightPtrStr)
Map of lights, sorted by name.
CU_DeclareMap() [43/58]
castor3d::CU_DeclareMap (int , LightSPtr , LightPtrInt)
Map of lights, sorted by index.
CU_DeclareMap() [44/58]
castor3d::CU_DeclareMap (castor::String , SubmeshComponentSPtr , SubmeshComponentStr)
CU_DeclareMap() [45/58]
castor3d::CU_DeclareMap (castor::String , MaterialSPtr , MaterialPtrStr)
Material pointer map, sorted by name.
CU_DeclareMap() [46/58]
castor3d::CU_DeclareMap (uint32_t , MaterialSPtr , MaterialPtrUInt)
Material pointer map.
CU_DeclareMap() [47/58]
castor3d::CU_DeclareMap (castor::String , PluginSPtr , PluginStr)
CU_DeclareMap() [48/58]
castor3d::CU_DeclareMap (castor::Path , castor::DynamicLibrarySPtr , DynamicLibraryPtrPath)
CU_DeclareMap() [49/58]
castor3d::CU_DeclareMap (castor::Path , PluginType , PluginTypePath)
CU_DeclareMap() [50/58]
castor3d::CU_DeclareMap (castor::String , OverlaySPtr , OverlayPtrStr)
CU_DeclareMap() [51/58]
castor3d::CU_DeclareMap (castor::String , CameraSPtr , CameraPtrStr)
Camera pointer map, sorted by name.
CU_DeclareMap() [52/58]
castor3d::CU_DeclareMap (castor::String , MovableObjectSPtr , MovableObjectPtrStr)
MovableObject pointer map, sorted by name.
CU_DeclareMap() [53/58]
castor3d::CU_DeclareMap (castor::String , GeometrySPtr , GeometryPtrStr)
Geometry pointer map, sorted by name.
CU_DeclareMap() [54/58]
castor3d::CU_DeclareMap (castor::String , SceneSPtr , ScenePtrStr)
Scene pointer map, sorted by name.
CU_DeclareMap() [55/58]
castor3d::CU_DeclareMap (castor::String , SceneNodeSPtr , SceneNodePtrStr)
SceneNode pointer map, sorted by name.
CU_DeclareMap() [56/58]
castor3d::CU_DeclareMap (castor::String , BillboardListSPtr , BillboardListStr)
BillboardList pointer map, sorted by name.
CU_DeclareMap() [57/58]
castor3d::CU_DeclareMap (uint32_t , RenderWindowSPtr , RenderWindow)
CU_DeclareMap() [58/58]
castor3d::CU_DeclareMap (castor::String , RenderWindowSPtr , RenderWindowPtrStr)
CU_DeclareMultimap() [1/8]
castor3d::CU_DeclareMultimap (double , StaticRenderNode * , StaticRenderNodePtrByDistance)
CU_DeclareMultimap() [2/8]
castor3d::CU_DeclareMultimap (double , SkinningRenderNode * , SkinningRenderNodePtrByDistance)
CU_DeclareMultimap() [3/8]
castor3d::CU_DeclareMultimap (double , MorphingRenderNode * , MorphingRenderNodePtrByDistance)
CU_DeclareMultimap() [4/8]
castor3d::CU_DeclareMultimap (double , BillboardRenderNode * , BillboardRenderNodePtrByDistance)
CU_DeclareMultimap() [5/8]
castor3d::CU_DeclareMultimap (double , StaticRenderNode , StaticRenderNodeByDistance)
CU_DeclareMultimap() [6/8]
castor3d::CU_DeclareMultimap (double , SkinningRenderNode , SkinningRenderNodeByDistance)
CU_DeclareMultimap() [7/8]
castor3d::CU_DeclareMultimap (double , MorphingRenderNode , MorphingRenderNodeByDistance)
CU_DeclareMultimap() [8/8]
castor3d::CU_DeclareMultimap (double , BillboardRenderNode , BillboardRenderNodeByDistance)
CU_DeclareSmartPtr() [1/136]
castor3d::CU_DeclareSmartPtr (TextureAnimation)
CU_DeclareSmartPtr() [2/136]
castor3d::CU_DeclareSmartPtr (MeshAnimation)
CU_DeclareSmartPtr() [3/136]
castor3d::CU_DeclareSmartPtr (MeshAnimationKeyFrame)
CU_DeclareSmartPtr() [4/136]
castor3d::CU_DeclareSmartPtr (MeshAnimationSubmesh)
CU_DeclareSmartPtr() [5/136]
castor3d::CU_DeclareSmartPtr (TextureConfigurationBuffer)
CU_DeclareSmartPtr() [6/136]
castor3d::CU_DeclareSmartPtr (TextureAnimationInstance)
CU_DeclareSmartPtr() [7/136]
castor3d::CU_DeclareSmartPtr (EnvironmentMap)
CU_DeclareSmartPtr() [8/136]
castor3d::CU_DeclareSmartPtr (EnvironmentMapPass)
CU_DeclareSmartPtr() [9/136]
castor3d::CU_DeclareSmartPtr (MeshAnimationInstance)
CU_DeclareSmartPtr() [10/136]
castor3d::CU_DeclareSmartPtr (Submesh)
CU_DeclareSmartPtr() [11/136]
castor3d::CU_DeclareSmartPtr (Bone)
CU_DeclareSmartPtr() [12/136]
castor3d::CU_DeclareSmartPtr (Skeleton)
CU_DeclareSmartPtr() [13/136]
castor3d::CU_DeclareSmartPtr (PassBuffer)
CU_DeclareSmartPtr() [14/136]
castor3d::CU_DeclareSmartPtr (IblTextures)
CU_DeclareSmartPtr() [15/136]
castor3d::CU_DeclareSmartPtr (ToneMapping)
CU_DeclareSmartPtr() [16/136]
castor3d::CU_DeclareSmartPtr (PostEffect)
CU_DeclareSmartPtr() [17/136]
castor3d::CU_DeclareSmartPtr (Engine)
CU_DeclareSmartPtr() [18/136]
castor3d::CU_DeclareSmartPtr (EquirectangularToCube)
CU_DeclareSmartPtr() [19/136]
castor3d::CU_DeclareSmartPtr (RenderCube)
CU_DeclareSmartPtr() [20/136]
castor3d::CU_DeclareSmartPtr (RenderDepthQuad)
CU_DeclareSmartPtr() [21/136]
castor3d::CU_DeclareSmartPtr (TextureProjection)
CU_DeclareSmartPtr() [22/136]
castor3d::CU_DeclareSmartPtr (SceneCuller)
CU_DeclareSmartPtr() [23/136]
castor3d::CU_DeclareSmartPtr (TextureProjectionToCube)
CU_DeclareSmartPtr() [24/136]
castor3d::CU_DeclareSmartPtr (SkeletonAnimationInstance)
CU_DeclareSmartPtr() [25/136]
castor3d::CU_DeclareSmartPtr (RenderTechnique)
CU_DeclareSmartPtr() [26/136]
castor3d::CU_DeclareSmartPtr (SkeletonAnimationInstanceBone)
CU_DeclareSmartPtr() [27/136]
castor3d::CU_DeclareSmartPtr (SkeletonAnimationInstanceNode)
CU_DeclareSmartPtr() [28/136]
castor3d::CU_DeclareSmartPtr (SkeletonAnimationInstanceObject)
CU_DeclareSmartPtr() [29/136]
castor3d::CU_DeclareSmartPtr (RsmGIPass)
CU_DeclareSmartPtr() [30/136]
castor3d::CU_DeclareSmartPtr (RsmInterpolatePass)
CU_DeclareSmartPtr() [31/136]
castor3d::CU_DeclareSmartPtr (Mesh)
CU_DeclareSmartPtr() [32/136]
castor3d::CU_DeclareSmartPtr (MeshFactory)
CU_DeclareSmartPtr() [33/136]
castor3d::CU_DeclareSmartPtr (MeshGenerator)
CU_DeclareSmartPtr() [34/136]
castor3d::CU_DeclareSmartPtr (Cone)
CU_DeclareSmartPtr() [35/136]
castor3d::CU_DeclareSmartPtr (MeshImporter)
CU_DeclareSmartPtr() [36/136]
castor3d::CU_DeclareSmartPtr (MeshImporterFactory)
CU_DeclareSmartPtr() [37/136]
castor3d::CU_DeclareSmartPtr (Cylinder)
CU_DeclareSmartPtr() [38/136]
castor3d::CU_DeclareSmartPtr (Icosahedron)
CU_DeclareSmartPtr() [39/136]
castor3d::CU_DeclareSmartPtr (MeshSubdivider)
CU_DeclareSmartPtr() [40/136]
castor3d::CU_DeclareSmartPtr (Animable)
CU_DeclareSmartPtr() [41/136]
castor3d::CU_DeclareSmartPtr (Cube)
CU_DeclareSmartPtr() [42/136]
castor3d::CU_DeclareSmartPtr (MeshSubdividerFactory)
CU_DeclareSmartPtr() [43/136]
castor3d::CU_DeclareSmartPtr (AnimatedObjectGroup)
CU_DeclareSmartPtr() [44/136]
castor3d::CU_DeclareSmartPtr (Plane)
CU_DeclareSmartPtr() [45/136]
castor3d::CU_DeclareSmartPtr (SkeletonAnimation)
CU_DeclareSmartPtr() [46/136]
castor3d::CU_DeclareSmartPtr (AnimatedMesh)
CU_DeclareSmartPtr() [47/136]
castor3d::CU_DeclareSmartPtr (SceneBackground)
CU_DeclareSmartPtr() [48/136]
castor3d::CU_DeclareSmartPtr (Projection)
CU_DeclareSmartPtr() [49/136]
castor3d::CU_DeclareSmartPtr (AnimatedObject)
CU_DeclareSmartPtr() [50/136]
castor3d::CU_DeclareSmartPtr (SkeletonAnimationKeyFrame)
CU_DeclareSmartPtr() [51/136]
castor3d::CU_DeclareSmartPtr (Sphere)
CU_DeclareSmartPtr() [52/136]
castor3d::CU_DeclareSmartPtr (SkeletonAnimationObject)
CU_DeclareSmartPtr() [53/136]
castor3d::CU_DeclareSmartPtr (AnimatedSkeleton)
CU_DeclareSmartPtr() [54/136]
castor3d::CU_DeclareSmartPtr (Torus)
CU_DeclareSmartPtr() [55/136]
castor3d::CU_DeclareSmartPtr (SkeletonAnimationBone)
CU_DeclareSmartPtr() [56/136]
castor3d::CU_DeclareSmartPtr (Animation)
CU_DeclareSmartPtr() [57/136]
castor3d::CU_DeclareSmartPtr (SkeletonAnimationNode)
CU_DeclareSmartPtr() [58/136]
castor3d::CU_DeclareSmartPtr (AnimationInstance)
CU_DeclareSmartPtr() [59/136]
castor3d::CU_DeclareSmartPtr (CpuFrameEvent)
CU_DeclareSmartPtr() [60/136]
castor3d::CU_DeclareSmartPtr (FrameListener)
CU_DeclareSmartPtr() [61/136]
castor3d::CU_DeclareSmartPtr (GpuFrameEvent)
CU_DeclareSmartPtr() [62/136]
castor3d::CU_DeclareSmartPtr (Light)
CU_DeclareSmartPtr() [63/136]
castor3d::CU_DeclareSmartPtr (CpuFunctorEvent)
CU_DeclareSmartPtr() [64/136]
castor3d::CU_DeclareSmartPtr (LightFactory)
CU_DeclareSmartPtr() [65/136]
castor3d::CU_DeclareSmartPtr (LightCategory)
CU_DeclareSmartPtr() [66/136]
castor3d::CU_DeclareSmartPtr (GpuFunctorEvent)
CU_DeclareSmartPtr() [67/136]
castor3d::CU_DeclareSmartPtr (DirectionalLight)
CU_DeclareSmartPtr() [68/136]
castor3d::CU_DeclareSmartPtr (PointLight)
CU_DeclareSmartPtr() [69/136]
castor3d::CU_DeclareSmartPtr (SpotLight)
CU_DeclareSmartPtr() [70/136]
castor3d::CU_DeclareSmartPtr (BonesInstantiationComponent)
CU_DeclareSmartPtr() [71/136]
castor3d::CU_DeclareSmartPtr (Face)
CU_DeclareSmartPtr() [72/136]
castor3d::CU_DeclareSmartPtr (IndexMapping)
CU_DeclareSmartPtr() [73/136]
castor3d::CU_DeclareSmartPtr (InstantiationComponent)
CU_DeclareSmartPtr() [74/136]
castor3d::CU_DeclareSmartPtr (MorphComponent)
CU_DeclareSmartPtr() [75/136]
castor3d::CU_DeclareSmartPtr (SubmeshComponent)
CU_DeclareSmartPtr() [76/136]
castor3d::CU_DeclareSmartPtr (TriFaceMapping)
CU_DeclareSmartPtr() [77/136]
castor3d::CU_DeclareSmartPtr (Material)
CU_DeclareSmartPtr() [78/136]
castor3d::CU_DeclareSmartPtr (GpuBufferPool)
CU_DeclareSmartPtr() [79/136]
castor3d::CU_DeclareSmartPtr (UniformBufferBase)
CU_DeclareSmartPtr() [80/136]
castor3d::CU_DeclareSmartPtr (UniformBufferPools)
CU_DeclareSmartPtr() [81/136]
castor3d::CU_DeclareSmartPtr (PoolUniformBuffer)
CU_DeclareSmartPtr() [82/136]
castor3d::CU_DeclareSmartPtr (UniformBufferPool)
CU_DeclareSmartPtr() [83/136]
castor3d::CU_DeclareSmartPtr (Plugin)
CU_DeclareSmartPtr() [84/136]
castor3d::CU_DeclareSmartPtr (ImporterPlugin)
CU_DeclareSmartPtr() [85/136]
castor3d::CU_DeclareSmartPtr (DividerPlugin)
CU_DeclareSmartPtr() [86/136]
castor3d::CU_DeclareSmartPtr (AnimationKeyFrame)
CU_DeclareSmartPtr() [87/136]
castor3d::CU_DeclareSmartPtr (GenericPlugin)
CU_DeclareSmartPtr() [88/136]
castor3d::CU_DeclareSmartPtr (PostFxPlugin)
CU_DeclareSmartPtr() [89/136]
castor3d::CU_DeclareSmartPtr (ParticlePlugin)
CU_DeclareSmartPtr() [90/136]
castor3d::CU_DeclareSmartPtr (Sampler)
CU_DeclareSmartPtr() [91/136]
castor3d::CU_DeclareSmartPtr (TextureLayout)
CU_DeclareSmartPtr() [92/136]
castor3d::CU_DeclareSmartPtr (TextureSource)
CU_DeclareSmartPtr() [93/136]
castor3d::CU_DeclareSmartPtr (TextureUnit)
CU_DeclareSmartPtr() [94/136]
castor3d::CU_DeclareSmartPtr (TextureView)
CU_DeclareSmartPtr() [95/136]
castor3d::CU_DeclareSmartPtr (BillboardListCache)
CU_DeclareSmartPtr() [96/136]
castor3d::CU_DeclareSmartPtr (ComputeParticleSystem)
CU_DeclareSmartPtr() [97/136]
castor3d::CU_DeclareSmartPtr (CpuParticleSystem)
CU_DeclareSmartPtr() [98/136]
castor3d::CU_DeclareSmartPtr (ParticleElementDeclaration)
CU_DeclareSmartPtr() [99/136]
castor3d::CU_DeclareSmartPtr (ParticleEmitter)
CU_DeclareSmartPtr() [100/136]
castor3d::CU_DeclareSmartPtr (ParticleFactory)
CU_DeclareSmartPtr() [101/136]
castor3d::CU_DeclareSmartPtr (ParticleSystem)
CU_DeclareSmartPtr() [102/136]
castor3d::CU_DeclareSmartPtr (ParticleSystemImpl)
CU_DeclareSmartPtr() [103/136]
castor3d::CU_DeclareSmartPtr (ParticleUpdater)
CU_DeclareSmartPtr() [104/136]
castor3d::CU_DeclareSmartPtr (LightPass)
CU_DeclareSmartPtr() [105/136]
castor3d::CU_DeclareSmartPtr (Pass)
CU_DeclareSmartPtr() [106/136]
castor3d::CU_DeclareSmartPtr (PhongPass)
CU_DeclareSmartPtr() [107/136]
castor3d::CU_DeclareSmartPtr (MetallicRoughnessPbrPass)
CU_DeclareSmartPtr() [108/136]
castor3d::CU_DeclareSmartPtr (SpecularGlossinessPbrPass)
CU_DeclareSmartPtr() [109/136]
castor3d::CU_DeclareSmartPtr (SubsurfaceScattering)
CU_DeclareSmartPtr() [110/136]
castor3d::CU_DeclareSmartPtr (BillboardBase)
CU_DeclareSmartPtr() [111/136]
castor3d::CU_DeclareSmartPtr (BillboardList)
CU_DeclareSmartPtr() [112/136]
castor3d::CU_DeclareSmartPtr (Camera)
CU_DeclareSmartPtr() [113/136]
castor3d::CU_DeclareSmartPtr (Geometry)
CU_DeclareSmartPtr() [114/136]
castor3d::CU_DeclareSmartPtr (MovableObject)
CU_DeclareSmartPtr() [115/136]
castor3d::CU_DeclareSmartPtr (Scene)
CU_DeclareSmartPtr() [116/136]
castor3d::CU_DeclareSmartPtr (SceneFileContext)
CU_DeclareSmartPtr() [117/136]
castor3d::CU_DeclareSmartPtr (SceneFileParser)
CU_DeclareSmartPtr() [118/136]
castor3d::CU_DeclareSmartPtr (SceneImporter)
CU_DeclareSmartPtr() [119/136]
castor3d::CU_DeclareSmartPtr (SceneNode)
CU_DeclareSmartPtr() [120/136]
castor3d::CU_DeclareSmartPtr (EventHandler)
CU_DeclareSmartPtr() [121/136]
castor3d::CU_DeclareSmartPtr (UserInputEvent)
CU_DeclareSmartPtr() [122/136]
castor3d::CU_DeclareSmartPtr (KeyboardEvent)
CU_DeclareSmartPtr() [123/136]
castor3d::CU_DeclareSmartPtr (MouseEvent)
CU_DeclareSmartPtr() [124/136]
castor3d::CU_DeclareSmartPtr (HandlerEvent)
CU_DeclareSmartPtr() [125/136]
castor3d::CU_DeclareSmartPtr (UserInputListener)
CU_DeclareSmartPtr() [126/136]
castor3d::CU_DeclareSmartPtr (AnimatedObjectGroupCache)
CU_DeclareSmartPtr() [127/136]
castor3d::CU_DeclareSmartPtr (BillboardUboPools)
CU_DeclareSmartPtr() [128/136]
castor3d::CU_DeclareSmartPtr (CameraCache)
CU_DeclareSmartPtr() [129/136]
castor3d::CU_DeclareSmartPtr (GeometryCache)
CU_DeclareSmartPtr() [130/136]
castor3d::CU_DeclareSmartPtr (LightCache)
CU_DeclareSmartPtr() [131/136]
castor3d::CU_DeclareSmartPtr (FrameListenerCache)
CU_DeclareSmartPtr() [132/136]
castor3d::CU_DeclareSmartPtr (MaterialCache)
CU_DeclareSmartPtr() [133/136]
castor3d::CU_DeclareSmartPtr (OverlayCache)
CU_DeclareSmartPtr() [134/136]
castor3d::CU_DeclareSmartPtr (PluginCache)
CU_DeclareSmartPtr() [135/136]
castor3d::CU_DeclareSmartPtr (RenderTargetCache)
CU_DeclareSmartPtr() [136/136]
castor3d::CU_DeclareSmartPtr (ShaderProgramCache)
CU_DeclareTemplateSmartPtr()
castor3d::CU_DeclareTemplateSmartPtr (UniformBuffer)
CU_DeclareVector() [1/44]
castor3d::CU_DeclareVector (StaticRenderNode * , StaticRenderNodePtr)
CU_DeclareVector() [2/44]
castor3d::CU_DeclareVector (SkinningRenderNode * , SkinningRenderNodePtr)
CU_DeclareVector() [3/44]
castor3d::CU_DeclareVector (MorphingRenderNode * , MorphingRenderNodePtr)
CU_DeclareVector() [4/44]
castor3d::CU_DeclareVector (MeshAnimationSubmesh , MeshAnimationSubmesh)
CU_DeclareVector() [5/44]
castor3d::CU_DeclareVector (BillboardRenderNode * , BillboardRenderNodePtr)
CU_DeclareVector() [6/44]
castor3d::CU_DeclareVector (SubmeshVertex , SubmeshVertex)
SubmeshVertex array.
CU_DeclareVector() [7/44]
castor3d::CU_DeclareVector (SubmeshSPtr , SubmeshPtr)
Submesh pointer array.
CU_DeclareVector() [8/44]
castor3d::CU_DeclareVector (VertexBoneData , VertexBoneData)
Skinned vertex data array.
CU_DeclareVector() [9/44]
castor3d::CU_DeclareVector (BoneSPtr , BonePtr)
Bone pointer array.
CU_DeclareVector() [10/44]
castor3d::CU_DeclareVector (PostEffectSPtr , PostEffectPtr)
CU_DeclareVector() [11/44]
castor3d::CU_DeclareVector (float , Float)
CU_DeclareVector() [12/44]
castor3d::CU_DeclareVector (SkeletonAnimationInstanceObjectSPtr , SkeletonAnimationInstanceObjectPtr)
SkeletonAnimationInstanceObject pointer array.
CU_DeclareVector() [13/44]
castor3d::CU_DeclareVector (std::reference_wrapper< SkeletonAnimationInstance > , SkeletonAnimationInstance)
Skeleton animation instance pointer array.
CU_DeclareVector() [14/44]
castor3d::CU_DeclareVector (SkeletonAnimationObjectSPtr , SkeletonAnimationObjectPtr)
SkeletonAnimationObject pointer array.
CU_DeclareVector() [15/44]
castor3d::CU_DeclareVector (CpuFrameEventUPtr , CpuFrameEventPtr)
CU_DeclareVector() [16/44]
castor3d::CU_DeclareVector (GpuFrameEventUPtr , GpuFrameEventPtr)
CU_DeclareVector() [17/44]
castor3d::CU_DeclareVector (LightSPtr , LightPtr)
Array of lights.
CU_DeclareVector() [18/44]
castor3d::CU_DeclareVector (LightSPtr , Lights)
Array of lights.
CU_DeclareVector() [19/44]
castor3d::CU_DeclareVector (LightRPtr , LightsRef)
Array to non owning light pointers.
CU_DeclareVector() [20/44]
castor3d::CU_DeclareVector (Face , Face)
Face array.
CU_DeclareVector() [21/44]
castor3d::CU_DeclareVector (MaterialSPtr , MaterialPtr)
Material pointer array.
CU_DeclareVector() [22/44]
castor3d::CU_DeclareVector (FaceSPtr , FacePtr)
Face pointer array.
CU_DeclareVector() [23/44]
castor3d::CU_DeclareVector (GeometryInjectionPass , GeometryInjectionPass)
CU_DeclareVector() [24/44]
castor3d::CU_DeclareVector (LightInjectionPass , LightInjectionPass)
CU_DeclareVector() [25/44]
castor3d::CU_DeclareVector (LightVolumePassResultUPtr , LightVolumePassResult)
CU_DeclareVector() [26/44]
castor3d::CU_DeclareVector (AnimationKeyFrameUPtr , AnimationKeyFrame)
CU_DeclareVector() [27/44]
castor3d::CU_DeclareVector (CommandsSemaphore , CommandsSemaphore)
CU_DeclareVector() [28/44]
castor3d::CU_DeclareVector (TextureUnit , TextureUnit)
TextureUnit array.
CU_DeclareVector() [29/44]
castor3d::CU_DeclareVector (TextureUnitSPtr , TextureUnitPtr)
TextureUnit pointer array.
CU_DeclareVector() [30/44]
castor3d::CU_DeclareVector (std::reference_wrapper< TextureUnit > , DepthMap)
TextureUnit reference array.
CU_DeclareVector() [31/44]
castor3d::CU_DeclareVector (Particle , Particle)
CU_DeclareVector() [32/44]
castor3d::CU_DeclareVector (ParticleEmitterUPtr , ParticleEmitter)
CU_DeclareVector() [33/44]
castor3d::CU_DeclareVector (ParticleUpdaterUPtr , ParticleUpdater)
CU_DeclareVector() [34/44]
castor3d::CU_DeclareVector (Pass , Pass)
Pass array.
CU_DeclareVector() [35/44]
castor3d::CU_DeclareVector (PassSPtr , PassPtr)
Pass pointer array.
CU_DeclareVector() [36/44]
castor3d::CU_DeclareVector (OverlaySPtr , OverlayPtr)
CU_DeclareVector() [37/44]
castor3d::CU_DeclareVector (CameraSPtr , CameraPtr)
Camera pointer array.
CU_DeclareVector() [38/44]
castor3d::CU_DeclareVector (GeometrySPtr , GeometryPtr)
Geometry pointer array.
CU_DeclareVector() [39/44]
castor3d::CU_DeclareVector (SceneNodeSPtr , SceneNodePtr)
SceneNode pointer array.
CU_DeclareVector() [40/44]
castor3d::CU_DeclareVector (BillboardListSPtr , BillboardList)
BillboardList pointer array.
CU_DeclareVector() [41/44]
castor3d::CU_DeclareVector (LpvLightConfigUbo , LpvLightConfigUbo)
CU_DeclareVector() [42/44]
castor3d::CU_DeclareVector (LpvGridConfigUbo , LpvGridConfigUbo)
CU_DeclareVector() [43/44]
castor3d::CU_DeclareVector (RenderWindowSPtr , RenderWindowPtr)
CU_DeclareVector() [44/44]
castor3d::CU_DeclareVector (IntermediateView , IntermediateView)
getBorderColor() [1/4]
VkBorderColor castor3d::getBorderColor (SmTexture texture)
getBorderColor() [2/4]
VkBorderColor castor3d::getBorderColor (LpvTexture texture)
Referenced by castor3d::GBufferBase::doCreateTextures().
getBorderColor() [3/4]
VkBorderColor castor3d::getBorderColor (DsTexture texture)
getBorderColor() [4/4]
VkBorderColor castor3d::getBorderColor (LpTexture texture)
getBuffer() [1/46]
static uint8_t const* castor3d::getBuffer (bool const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
Referenced by castor3d::ChunkParser< T >::parse(), and castor3d::ChunkWriter< T >::write().
getBuffer() [2/46]
static uint8_t* castor3d::getBuffer (bool & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [3/46]
static uint8_t const* castor3d::getBuffer (int8_t const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [4/46]
static uint8_t* castor3d::getBuffer (int8_t & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [5/46]
static uint8_t const* castor3d::getBuffer (uint8_t const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [6/46]
static uint8_t* castor3d::getBuffer (uint8_t & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [7/46]
static uint8_t const* castor3d::getBuffer (int16_t const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [8/46]
static uint8_t* castor3d::getBuffer (int16_t & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [9/46]
static uint8_t const* castor3d::getBuffer (uint16_t const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [10/46]
static uint8_t* castor3d::getBuffer (uint16_t & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [11/46]
static uint8_t const* castor3d::getBuffer (int32_t const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [12/46]
static uint8_t* castor3d::getBuffer (int32_t & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [13/46]
static uint8_t const* castor3d::getBuffer (uint32_t const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [14/46]
static uint8_t* castor3d::getBuffer (uint32_t & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [15/46]
static uint8_t const* castor3d::getBuffer (int64_t const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [16/46]
static uint8_t* castor3d::getBuffer (int64_t & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [17/46]
static uint8_t const* castor3d::getBuffer (uint64_t const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [18/46]
static uint8_t* castor3d::getBuffer (uint64_t & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [19/46]
static uint8_t const* castor3d::getBuffer (float const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [20/46]
static uint8_t* castor3d::getBuffer (float & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [21/46]
static uint8_t const* castor3d::getBuffer (double const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [22/46]
static uint8_t* castor3d::getBuffer (double & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [23/46]
static uint8_t const* castor3d::getBuffer (long double const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [24/46]
static uint8_t* castor3d::getBuffer (long double & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [25/46]
template<typename T > static uint8_t const* castor3d::getBuffer (std::vector< T > const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [26/46]
template<typename T > static uint8_t* castor3d::getBuffer (std::vector< T > & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [27/46]
template<typename T , size_t Count> static uint8_t const* castor3d::getBuffer (std::array< T, Count > const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [28/46]
template<typename T , size_t Count> static uint8_t* castor3d::getBuffer (std::array< T, Count > & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [29/46]
template<typename T , uint32_t Count> static uint8_t const* castor3d::getBuffer (castor::Point< T, Count > const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [30/46]
template<typename T , uint32_t Count> static uint8_t* castor3d::getBuffer (castor::Point< T, Count > & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [31/46]
template<typename T , uint32_t Count> static uint8_t const* castor3d::getBuffer (castor::Coords< T, Count > const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [32/46]
template<typename T , uint32_t Count> static uint8_t* castor3d::getBuffer (castor::Coords< T, Count > & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [33/46]
template<typename T , uint32_t Columns, uint32_t Rows> static uint8_t const* castor3d::getBuffer (castor::Matrix< T, Columns, Rows > const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [34/46]
template<typename T , uint32_t Columns, uint32_t Rows> static uint8_t* castor3d::getBuffer (castor::Matrix< T, Columns, Rows > & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [35/46]
template<typename T , uint32_t Count> static uint8_t const* castor3d::getBuffer (castor::SquareMatrix< T, Count > const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [36/46]
template<typename T , uint32_t Count> static uint8_t* castor3d::getBuffer (castor::SquareMatrix< T, Count > & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [37/46]
static uint8_t const* castor3d::getBuffer (castor::RgbColour const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [38/46]
static uint8_t* castor3d::getBuffer (castor::RgbColour & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [39/46]
static uint8_t const* castor3d::getBuffer (castor::RgbaColour const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [40/46]
static uint8_t* castor3d::getBuffer (castor::RgbaColour & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [41/46]
static uint8_t const* castor3d::getBuffer (castor::Size const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [42/46]
static uint8_t* castor3d::getBuffer (castor::Size & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [43/46]
static uint8_t const* castor3d::getBuffer (castor::Position const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [44/46]
static uint8_t* castor3d::getBuffer (castor::Position & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [45/46]
template<typename T > static uint8_t const* castor3d::getBuffer (castor::QuaternionT< T > const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [46/46]
template<typename T > static uint8_t* castor3d::getBuffer (castor::QuaternionT< T > & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getClearValue() [1/5]
VkClearValue castor3d::getClearValue (WbTexture texture)
getClearValue() [2/5]
VkClearValue castor3d::getClearValue (SmTexture texture)
getClearValue() [3/5]
VkClearValue castor3d::getClearValue (LpvTexture texture)
getClearValue() [4/5]
VkClearValue castor3d::getClearValue (DsTexture texture)
getClearValue() [5/5]
VkClearValue castor3d::getClearValue (LpTexture texture)
getCmshMajor()
constexpr uint32_t castor3d::getCmshMajor (uint32_t version) inline
Referenced by castor3d::BinaryParserBase< Skeleton >::doParseHeader().
getCmshMinor()
constexpr uint32_t castor3d::getCmshMinor (uint32_t version) inline
Referenced by castor3d::BinaryParserBase< Skeleton >::doParseHeader().
getCmshRevision()
constexpr uint32_t castor3d::getCmshRevision (uint32_t version) inline
Referenced by castor3d::BinaryParserBase< Skeleton >::doParseHeader().
getDataSize() [1/12]
template<typename T > static size_t castor3d::getDataSize (T const & value) inline static
Retrieves the value binary size.
Parameters
[in] value The value.
Returns
The size (sizeof(value) for basic types).
Referenced by castor3d::ChunkParser< T >::parse(), and castor3d::ChunkWriter< T >::write().
getDataSize() [2/12]
template<typename T > static size_t castor3d::getDataSize (std::vector< T > const & value) inline static
Retrieves the value binary size.
Parameters
[in] value The value.
Returns
The size (sizeof(value) for basic types).
getDataSize() [3/12]
template<typename T , size_t Count> static size_t castor3d::getDataSize (std::array< T, Count > const & value) inline static
Retrieves the value binary size.
Parameters
[in] value The value.
Returns
The size (sizeof(value) for basic types).
getDataSize() [4/12]
template<typename T , uint32_t Count> static size_t castor3d::getDataSize (castor::Point< T, Count > const & value) inline static
Retrieves the value binary size.
Parameters
[in] value The value.
Returns
The size (sizeof(value) for basic types).
getDataSize() [5/12]
template<typename T , uint32_t Count> static size_t castor3d::getDataSize (castor::Coords< T, Count > const & value) inline static
Retrieves the value binary size.
Parameters
[in] value The value.
Returns
The size (sizeof(value) for basic types).
getDataSize() [6/12]
template<typename T , uint32_t Columns, uint32_t Rows> static size_t castor3d::getDataSize (castor::Matrix< T, Columns, Rows > const & value) inline static
Retrieves the value binary size.
Parameters
[in] value The value.
Returns
The size (sizeof(value) for basic types).
getDataSize() [7/12]
template<typename T , uint32_t Count> static size_t castor3d::getDataSize (castor::SquareMatrix< T, Count > const & value) inline static
Retrieves the value binary size.
Parameters
[in] value The value.
Returns
The size (sizeof(value) for basic types).
getDataSize() [8/12]
static size_t castor3d::getDataSize (castor::RgbColour const & value) inline static
Retrieves the value binary size.
Parameters
[in] value The value.
Returns
The size (sizeof(value) for basic types).
getDataSize() [9/12]
static size_t castor3d::getDataSize (castor::RgbaColour const & value) inline static
Retrieves the value binary size.
Parameters
[in] value The value.
Returns
The size (sizeof(value) for basic types).
getDataSize() [10/12]
static size_t castor3d::getDataSize (castor::Size const & value) inline static
Retrieves the value binary size.
Parameters
[in] value The value.
Returns
The size (sizeof(value) for basic types).
getDataSize() [11/12]
static size_t castor3d::getDataSize (castor::Position const & value) inline static
Retrieves the value binary size.
Parameters
[in] value The value.
Returns
The size (sizeof(value) for basic types).
getDataSize() [12/12]
template<typename T > static size_t castor3d::getDataSize (castor::QuaternionT< T > const & value) inline static
Retrieves the value binary size.
Parameters
[in] value The value.
Returns
The size (sizeof(value) for basic types).
getFlags()
C3D_API TextureFlags castor3d::getFlags (TextureConfiguration const & config)
getFogType()
C3D_API FogType castor3d::getFogType (SceneFlags const & flags)
Gives the fog type matching the given flags.
Parameters
[in] flags The scene flags.
Returns
The fog type.
getFormat() [1/5]
VkFormat castor3d::getFormat (WbTexture texture)
getFormat() [2/5]
VkFormat castor3d::getFormat (SmTexture texture)
getFormat() [3/5]
VkFormat castor3d::getFormat (LpvTexture texture)
Referenced by castor3d::GBufferBase::doCreateTextures().
getFormat() [4/5]
VkFormat castor3d::getFormat (DsTexture texture)
getFormat() [5/5]
VkFormat castor3d::getFormat (LpTexture texture)
getLightBufferIndex()
C3D_API uint32_t castor3d::getLightBufferIndex () noexcept
Returns
The lights sources buffer index.
getLogger()
castor::LoggerInstance& castor3d::getLogger (Engine & engine)
getMaxDistance() [1/2]
float castor3d::getMaxDistance (LightCategory const & light, castor::Point3f const & attenuation)
Retrieve the maximum litten distance for given light and attenuation.
Parameters
[in] light The light source.
[in] attenuation The attenuation values.
Returns
The value.
getMaxDistance() [2/2]
float castor3d::getMaxDistance (LightCategory const & light, castor::Point3f const & attenuation, float max)
Retrieve the maximum litten distance for given light and attenuation.
Parameters
[in] light The light source.
[in] attenuation The attenuation values.
[in] max The viewer max value.
Returns
The value.
getMinBufferIndex()
C3D_API uint32_t castor3d::getMinBufferIndex () noexcept
Returns
The minimal index for shader buffers (SSBO and UBO).
getMinTextureIndex()
C3D_API uint32_t castor3d::getMinTextureIndex () noexcept
Returns
The minimal index for textures.
getMipLevels() [1/10]
uint32_t castor3d::getMipLevels (WbTexture texture, castor::Size const & size) inline
getMipLevels() [2/10]
uint32_t castor3d::getMipLevels (WbTexture texture, VkExtent3D const & size) inline
References getMipLevels().
getMipLevels() [3/10]
uint32_t castor3d::getMipLevels (SmTexture texture, castor::Size const & size)
getMipLevels() [4/10]
uint32_t castor3d::getMipLevels (LpvTexture texture, castor::Size const & size) inline
getMipLevels() [5/10]
uint32_t castor3d::getMipLevels (SmTexture texture, VkExtent3D const & size) inline
References getMipLevels().
getMipLevels() [6/10]
uint32_t castor3d::getMipLevels (DsTexture texture, castor::Size const & size) inline
getMipLevels() [7/10]
uint32_t castor3d::getMipLevels (LpTexture texture, castor::Size const & size) inline
getMipLevels() [8/10]
uint32_t castor3d::getMipLevels (LpvTexture texture, VkExtent3D const & size) inline
References getMipLevels().
getMipLevels() [9/10]
uint32_t castor3d::getMipLevels (LpTexture texture, VkExtent3D const & size) inline
References getMipLevels().
getMipLevels() [10/10]
C3D_API uint32_t castor3d::getMipLevels (VkExtent3D const & extent)
Referenced by castor3d::GBufferBase::doCreateTextures(), and getMipLevels().
getName() [1/46]
C3D_API castor::String castor3d::getName (OverlayType value)
getName() [2/46]
C3D_API castor::String castor3d::getName (BackgroundType value)
getName() [3/46]
C3D_API castor::String castor3d::getName (ParallaxOcclusionMode value)
getName() [4/46]
castor::String castor3d::getName (WbTexture texture)
getName() [5/46]
C3D_API castor::String castor3d::getName (MaterialType value)
getName() [6/46]
C3D_API castor::String castor3d::getName (AnimationState value)
Referenced by castor3d::GBufferBase::doCreateTextures(), castor3d::LightPassVolumePropagationShadowT< LtType >::initialise(), castor3d::LightPassLayeredVolumePropagationShadowT< LightType::eDirectional >::initialise(), makeShaderState(), and castor3d::TextureSource::toString().
getName() [7/46]
C3D_API castor::String castor3d::getName (EventType value)
getName() [8/46]
C3D_API castor::String castor3d::getName (LightType value)
getName() [9/46]
C3D_API castor::String castor3d::getName (MovableType value)
getName() [10/46]
castor::String castor3d::getName (SmTexture texture)
getName() [11/46]
castor::String castor3d::getName (DsTexture texture)
getName() [12/46]
castor::String castor3d::getName (LpvTexture texture)
getName() [13/46]
C3D_API castor::String castor3d::getName (UserInputEventType value)
getName() [14/46]
castor::String castor3d::getName (GlobalIlluminationType giType)
getName() [15/46]
C3D_API castor::String castor3d::getName (SkeletonAnimationObjectType value)
getName() [16/46]
castor::String castor3d::getName (LpTexture texture)
getName() [17/46]
C3D_API castor::String castor3d::getName (TextWrappingMode value)
getName() [18/46]
C3D_API castor::String castor3d::getName (ElementUsage value)
getName() [19/46]
C3D_API castor::String castor3d::getName (TextureSpace value)
getName() [20/46]
C3D_API castor::String castor3d::getName (TextureSpaces value)
getName() [21/46]
C3D_API castor::String castor3d::getName (AnimationType value)
getName() [22/46]
C3D_API castor::String castor3d::getName (ShadowType value)
getName() [23/46]
C3D_API castor::String castor3d::getName (BlendMode value)
getName() [24/46]
C3D_API castor::String castor3d::getName (TextTexturingMode value)
getName() [25/46]
C3D_API castor::String castor3d::getName (ParticleFormat value)
getName() [26/46]
C3D_API castor::String castor3d::getName (MouseEventType value)
getName() [27/46]
C3D_API castor::String castor3d::getName (InterpolatorType value)
getName() [28/46]
C3D_API castor::String castor3d::getName (FogType value)
getName() [29/46]
C3D_API castor::String castor3d::getName (TextLineSpacingMode value)
getName() [30/46]
C3D_API castor::String castor3d::getName (CubeMapFace value)
getName() [31/46]
C3D_API castor::String castor3d::getName (KeyboardEventType value)
getName() [32/46]
C3D_API castor::String castor3d::getName (TextureFlag value, MaterialType material)
getName() [33/46]
C3D_API castor::String castor3d::getName (FrustumCorner value)
getName() [34/46]
C3D_API castor::String castor3d::getName (PassFlag value)
getName() [35/46]
C3D_API castor::String castor3d::getName (HAlign value)
getName() [36/46]
C3D_API castor::String castor3d::getName (HandlerEventType value)
getName() [37/46]
C3D_API castor::String castor3d::getName (VAlign value)
getName() [38/46]
C3D_API castor::String castor3d::getName (MouseButton value)
getName() [39/46]
C3D_API castor::String castor3d::getName (FrustumPlane value)
getName() [40/46]
C3D_API castor::String castor3d::getName (BorderPosition value)
getName() [41/46]
C3D_API castor::String castor3d::getName (PickNodeType value)
getName() [42/46]
C3D_API castor::String castor3d::getName (BillboardType value)
getName() [43/46]
C3D_API castor::String castor3d::getName (TargetType value)
getName() [44/46]
C3D_API castor::String castor3d::getName (BillboardSize value)
getName() [45/46]
C3D_API castor::String castor3d::getName (ViewportType value)
getName() [46/46]
C3D_API castor::String castor3d::getName (RenderMode value)
getPassBufferIndex()
C3D_API uint32_t castor3d::getPassBufferIndex () noexcept
Returns
The materials passes buffer index.
getSize()
VkDeviceSize castor3d::getSize (ParticleFormat format) inline
Parameters
[in] format The particle format.
Returns
The data size for this particle format.
References eFloat, eInt, eMat2f, eMat3f, eMat4f, eUInt, eVec2f, eVec2i, eVec2ui, eVec3f, eVec3i, eVec3ui, eVec4f, eVec4i, and eVec4ui.
Referenced by castor3d::ParticleDeclaration::emplace_back(), and castor3d::ParticleDeclaration::push_back().
getTextureName() [1/5]
castor::String castor3d::getTextureName (WbTexture texture)
getTextureName() [2/5]
castor::String castor3d::getTextureName (LightType light, SmTexture texture)
getTextureName() [3/5]
castor::String castor3d::getTextureName (LpvTexture texture, std::string const & infix)
getTextureName() [4/5]
castor::String castor3d::getTextureName (DsTexture texture)
getTextureName() [5/5]
castor::String castor3d::getTextureName (LpTexture texture)
getTexturesBufferIndex()
C3D_API uint32_t castor3d::getTexturesBufferIndex () noexcept
Returns
The textures buffer index.
getUsageFlags() [1/4]
VkImageUsageFlags castor3d::getUsageFlags (SmTexture texture)
getUsageFlags() [2/4]
VkImageUsageFlags castor3d::getUsageFlags (LpvTexture texture)
Referenced by castor3d::GBufferBase::doCreateTextures().
getUsageFlags() [3/4]
VkImageUsageFlags castor3d::getUsageFlags (DsTexture texture)
getUsageFlags() [4/4]
VkImageUsageFlags castor3d::getUsageFlags (LpTexture texture)
hash() [1/8]
C3D_API size_t castor3d::hash (BillboardBase const & billboard, Pass const & pass)
hash() [2/8]
C3D_API size_t castor3d::hash (BillboardBase const & billboard, Pass const & pass, uint32_t instanceMult)
hash() [3/8]
C3D_API size_t castor3d::hash (Geometry const & geometry, Submesh const & submesh, Pass const & pass)
hash() [4/8]
size_t castor3d::hash (CulledSubmesh const & culled)
hash() [5/8]
C3D_API size_t castor3d::hash (Geometry const & geometry, Submesh const & submesh, Pass const & pass, uint32_t instanceMult)
hash() [6/8]
size_t castor3d::hash (CulledSubmesh const & culled, uint32_t instanceMult)
hash() [7/8]
size_t castor3d::hash (CulledBillboard const & culled)
hash() [8/8]
size_t castor3d::hash (CulledBillboard const & culled, uint32_t instanceMult)
initialiseGlslang()
C3D_API void castor3d::initialiseGlslang ()
Initialises glslang globals.
isShadowMapProgram()
C3D_API bool castor3d::isShadowMapProgram (ProgramFlags const & flags)
Tells if the given flags contain a shadow map flag.
Parameters
[in] flags The flags to check.
Returns
true if flags contain one of ProgramFlag::eShadowMapDirectional, ProgramFlag::eShadowMapSpot, or ProgramFlag::eShadowMapPoint.
isValidNodeForPass()
C3D_API bool castor3d::isValidNodeForPass (PassFlags const & passFlags, RenderMode value)
isVisible() [1/4]
bool castor3d::isVisible (Camera const & camera, CulledSubmesh const & node)
isVisible() [2/4]
bool castor3d::isVisible (Frustum const & frustum, CulledSubmesh const & node)
isVisible() [3/4]
bool castor3d::isVisible (Camera const & camera, CulledBillboard const & node)
isVisible() [4/4]
bool castor3d::isVisible (Frustum const & frustum, CulledBillboard const & node)
makeBuffer()
template<typename T > ashes::BufferPtr< T > castor3d::makeBuffer (RenderDevice const & device, VkDeviceSize count, VkBufferUsageFlags usage, VkMemoryPropertyFlags flags, std::string const & name, ashes::QueueShare sharingMode = {}) inline
makeBufferBase()
ashes::BufferBasePtr castor3d::makeBufferBase (RenderDevice const & device, VkDeviceSize size, VkBufferUsageFlags usage, VkMemoryPropertyFlags flags, std::string const & name, ashes::QueueShare sharingMode = {}) inline
makeCache() [1/2]
template<typename ElementType , typename KeyType > std::unique_ptr< Cache< ElementType, KeyType > > castor3d::makeCache (Engine & engine, typename CacheTraits< ElementType, KeyType >::Producer && produce, ElementInitialiser< ElementType > && initialise = [](std::shared_ptr< ElementType >){}, ElementCleaner< ElementType > && clean = [](std::shared_ptr< ElementType >){}, typename CacheTraits< ElementType, KeyType >::Merger && merge = [](CacheBase< ElementType, KeyType > const & , castor::Collection< ElementType, KeyType > & , std::shared_ptr< ElementType >){}) inline
Creates a cache.
Parameters
[in] engine The engine.
[in] produce The element producer.
[in] initialise The element initialiser.
[in] clean The element cleaner.
[in] merge The element collection merger.
makeCache() [2/2]
std::unique_ptr< ShaderProgramCache > castor3d::makeCache (Engine & engine) inline
Creates a ashes::ShaderProgram cache.
Parameters
[in] engine The engine.
makeChunkID()
uint64_t constexpr castor3d::makeChunkID (char a, char b, char c, char d, char e, char f, char g, char h)
A define to ease the declaration of a chunk id.
makeClearValue() [1/2]
VkClearValue castor3d::makeClearValue (float depth, uint32_t stencil = 0u) inline
References makeClearValue().
makeClearValue() [2/2]
VkClearValue castor3d::makeClearValue (float r, float g, float b, float a = 1.0f) inline
Referenced by makeClearValue().
makeCmshVersion()
constexpr uint32_t castor3d::makeCmshVersion (uint32_t maj, uint32_t min, uint32_t rev) inline
makeCpuCleanupEvent()
template<typename T > std::unique_ptr< CpuFunctorEvent > castor3d::makeCpuCleanupEvent (T & object)
Helper function to create a cleanup event.
Parameters
[in] object The object to cleanup
References ePreRender, and makeCpuFunctorEvent().
makeCpuFunctorEvent()
std::unique_ptr< CpuFunctorEvent > castor3d::makeCpuFunctorEvent (EventType type, CpuFunctorEvent::Functor functor) inline
Helper function to create a functor event.
Parameters
[in] type The event type
[in] functor The functor to execute
Referenced by makeCpuCleanupEvent(), and makeCpuInitialiseEvent().
makeCpuInitialiseEvent()
template<typename T > std::unique_ptr< CpuFunctorEvent > castor3d::makeCpuInitialiseEvent (T & object)
Helper function to create an initialise event.
Parameters
[in] object The object to initialise.
References ePreRender, and makeCpuFunctorEvent().
makeDescriptorSetLayoutBinding()
VkDescriptorSetLayoutBinding castor3d::makeDescriptorSetLayoutBinding (uint32_t binding, VkDescriptorType descriptorType, VkShaderStageFlags stageFlags, uint32_t descriptorCount = 1u, VkSampler const * pImmutableSamplers = nullptr) inline
makeDistanceNode()
template<typename NodeType > std::unique_ptr< DistanceRenderNodeBase > castor3d::makeDistanceNode (NodeType & node)
makeExtent2D() [1/2]
VkExtent2D castor3d::makeExtent2D (castor::Coords2ui const & size) inline
Referenced by makeScissor(), and makeViewport().
makeExtent2D() [2/2]
VkExtent2D castor3d::makeExtent2D (castor::Point2ui const & size) inline
makeExtent3D() [1/2]
VkExtent3D castor3d::makeExtent3D (castor::Coords2ui const & size) inline
makeExtent3D() [2/2]
VkExtent3D castor3d::makeExtent3D (castor::Point2ui const & size) inline
makeFloatArray()
std::array< float, 4u > castor3d::makeFloatArray (castor::RgbaColour const & value)
makeGpuCleanupEvent()
template<typename T > std::unique_ptr< GpuFunctorEvent > castor3d::makeGpuCleanupEvent (T & object)
Helper function to create a cleanup event.
Parameters
[in] object The object to cleanup
References ePreRender, and makeGpuFunctorEvent().
makeGpuFunctorEvent()
std::unique_ptr< GpuFunctorEvent > castor3d::makeGpuFunctorEvent (EventType type, GpuFunctorEvent::Functor functor) inline
Helper function to create a functor event.
Parameters
[in] type The event type
[in] functor The functor to execute
Referenced by makeGpuCleanupEvent(), and makeGpuInitialiseEvent().
makeGpuInitialiseEvent()
template<typename T > std::unique_ptr< GpuFunctorEvent > castor3d::makeGpuInitialiseEvent (T & object)
Helper function to create an initialise event.
Parameters
[in] object The object to initialise.
References ePreRender, and makeGpuFunctorEvent().
makeImage()
ashes::ImagePtr castor3d::makeImage (RenderDevice const & device, ashes::ImageCreateInfo createInfo, VkMemoryPropertyFlags flags, std::string const & name) inline
makeObjectCache()
template<typename ElementType , typename KeyType > std::unique_ptr< ObjectCache< ElementType, KeyType > > castor3d::makeObjectCache (Engine & engine, Scene & scene, SceneNodeSPtr rootNode, SceneNodeSPtr rootCameraNode, SceneNodeSPtr rootObjectNode, typename ObjectCacheTraits< ElementType, KeyType >::Producer && produce, ElementInitialiser< ElementType > && initialise = [](std::shared_ptr< ElementType >){}, ElementCleaner< ElementType > && clean = [](std::shared_ptr< ElementType >){}, typename ObjectCacheTraits< ElementType, KeyType >::Merger && merge = [](ObjectCacheBase< ElementType, KeyType > const & , castor::Collection< ElementType, KeyType > & , std::shared_ptr< ElementType > , SceneNodeSPtr , SceneNodeSPtr){}, ElementAttacher< ElementType > && attach = [](std::shared_ptr< ElementType >, SceneNode &, SceneNodeSPtr, SceneNodeSPtr, SceneNodeSPtr){}, ElementDetacher< ElementType > && detach = [](std::shared_ptr< ElementType >){}) inline
Creates an object cache.
Parameters
[in] engine The engine.
[in] scene The scene.
[in] rootNode The scene root node.
[in] rootCameraNode The root node for cameras.
[in] rootObjectNode The root node for objects.
[in] produce The element producer.
[in] initialise The element initialiser.
[in] clean The element cleaner.
[in] merge The element collection merger.
[in] attach The element attacher (to a scene node).
[in] detach The element detacher (from a scene node).
makeOffset2D() [1/2]
VkOffset2D castor3d::makeOffset2D (castor::Coords2i const & pos) inline
Referenced by makeScissor(), and makeViewport().
makeOffset2D() [2/2]
VkOffset2D castor3d::makeOffset2D (castor::Point2i const & pos) inline
makeOffset3D() [1/2]
VkOffset3D castor3d::makeOffset3D (castor::Coords2i const & pos) inline
makeOffset3D() [2/2]
VkOffset3D castor3d::makeOffset3D (castor::Point2i const & pos) inline
makePoolUniformBuffer()
PoolUniformBufferUPtr castor3d::makePoolUniformBuffer (RenderSystem const & renderSystem, castor::ArrayView< uint8_t > data, VkBufferUsageFlags usage, VkMemoryPropertyFlags flags, std::string name, ashes::QueueShare sharingMode = {}) inline
makeScissor() [1/6]
VkRect2D castor3d::makeScissor (castor::Coords2ui const & size) inline
References makeExtent2D(), and makeScissor().
makeScissor() [2/6]
VkRect2D castor3d::makeScissor (castor::Point2ui const & size) inline
References makeExtent2D(), and makeScissor().
makeScissor() [3/6]
VkRect2D castor3d::makeScissor (castor::Coords2i const & pos, castor::Coords2ui const & size) inline
References makeExtent2D(), makeOffset2D(), and makeScissor().
makeScissor() [4/6]
VkRect2D castor3d::makeScissor (castor::Point2i const & pos, castor::Coords2ui const & size) inline
References makeExtent2D(), makeOffset2D(), and makeScissor().
makeScissor() [5/6]
VkRect2D castor3d::makeScissor (castor::Coords2i const & pos, castor::Point2ui const & size) inline
References makeExtent2D(), makeOffset2D(), and makeScissor().
makeScissor() [6/6]
VkRect2D castor3d::makeScissor (castor::Point2i const & pos, castor::Point2ui const & size) inline
References makeExtent2D(), and makeOffset2D().
Referenced by makeScissor().
makeShaderState() [1/2]
ashes::PipelineShaderStageCreateInfo castor3d::makeShaderState (RenderDevice const & device, VkShaderStageFlagBits stage, SpirVShader code, std::string const & name, std::string mainFuncName = "main", ashes::Optional< ashes::SpecializationInfo > specialization = ashes::nullopt) inline
References getName(), and castor3d::SpirVShader::spirv.
Referenced by makeShaderState().
makeShaderState() [2/2]
ashes::PipelineShaderStageCreateInfo castor3d::makeShaderState (RenderDevice const & device, ShaderModule const & shaderModule, std::string mainFuncName = "main", ashes::Optional< ashes::SpecializationInfo > specialization = ashes::nullopt) inline
References compileShader(), makeShaderState(), castor3d::ShaderModule::name, and castor3d::ShaderModule::stage.
makeUniformBuffer()
template<typename DataT > UniformBufferUPtrT< DataT > castor3d::makeUniformBuffer (RenderSystem const & renderSystem, VkDeviceSize count, VkBufferUsageFlags usage, VkMemoryPropertyFlags flags, std::string name, ashes::QueueShare sharingMode = {}) inline
makeUniformBufferBase()
UniformBufferBaseUPtr castor3d::makeUniformBufferBase (RenderSystem const & renderSystem, VkDeviceSize count, VkDeviceSize size, VkBufferUsageFlags usage, VkMemoryPropertyFlags flags, std::string name, ashes::QueueShare sharingMode = {}) inline
makeVertexBuffer()
template<typename T > ashes::VertexBufferPtr< T > castor3d::makeVertexBuffer (RenderDevice const & device, VkDeviceSize count, VkBufferUsageFlags usage, VkMemoryPropertyFlags flags, std::string const & name, ashes::QueueShare sharingMode = {}) inline
makeVertexBufferBase()
ashes::VertexBufferBasePtr castor3d::makeVertexBufferBase (RenderDevice const & device, VkDeviceSize size, VkBufferUsageFlags usage, VkMemoryPropertyFlags flags, std::string const & name, ashes::QueueShare sharingMode = {}) inline
makeViewport() [1/6]
VkViewport castor3d::makeViewport (castor::Coords2ui const & size, float zMin = 0.0f, float zMax = 1.0f) inline
References makeExtent2D(), and makeViewport().
makeViewport() [2/6]
VkViewport castor3d::makeViewport (castor::Point2ui const & size, float zMin = 0.0f, float zMax = 1.0f) inline
References makeExtent2D(), and makeViewport().
makeViewport() [3/6]
VkViewport castor3d::makeViewport (castor::Coords2i const & pos, castor::Coords2ui const & size, float zMin = 0.0f, float zMax = 1.0f) inline
References makeExtent2D(), makeOffset2D(), and makeViewport().
makeViewport() [4/6]
VkViewport castor3d::makeViewport (castor::Point2i const & pos, castor::Coords2ui const & size, float zMin = 0.0f, float zMax = 1.0f) inline
References makeExtent2D(), makeOffset2D(), and makeViewport().
makeViewport() [5/6]
VkViewport castor3d::makeViewport (castor::Coords2i const & pos, castor::Point2ui const & size, float zMin = 0.0f, float zMax = 1.0f) inline
References makeExtent2D(), makeOffset2D(), and makeViewport().
makeViewport() [6/6]
VkViewport castor3d::makeViewport (castor::Point2i const & pos, castor::Point2ui const & size, float zMin = 0.0f, float zMax = 1.0f) inline
References makeExtent2D(), and makeOffset2D().
Referenced by makeViewport().
makeVkType()
template<typename VkType , typename ... Params> VkType castor3d::makeVkType (Params &&... params) inline
merge()
C3D_API TextureFlags castor3d::merge (TextureFlagsArray const & flags)
operator!=() [1/6]
bool castor3d::operator!= (DirectionalLightCascade const & lhs, DirectionalLightCascade const & rhs) inline
operator!=() [2/6]
bool castor3d::operator!= (ParticleElementDeclaration const & lhs, ParticleElementDeclaration const & rhs) inline
Equality operator.
Parameters
[in] lhs,rhs The 2 objects to compare.
References castor3d::ParticleElementDeclaration::m_dataType, castor3d::ParticleElementDeclaration::m_divisor, castor3d::ParticleElementDeclaration::m_name, castor3d::ParticleElementDeclaration::m_offset, and castor3d::ParticleElementDeclaration::m_usages.
operator!=() [3/6]
C3D_API bool castor3d::operator!= (castor3d::Version const & a, castor3d::Version const & b)
Difference operator.
Parameters
[in] a,b The versions to compare.
Returns
true if one version number is different from a to b.
operator!=() [4/6]
C3D_API bool castor3d::operator!= (TextureConfiguration const & lhs, TextureConfiguration const & rhs)
operator!=() [5/6]
C3D_API bool castor3d::operator!= (ParticleDeclaration const & lhs, ParticleDeclaration const & rhs)
Equality operator.
Parameters
[in] lhs,rhs The 2 objects to compare.
operator!=() [6/6]
bool castor3d::operator!= (VkImageSubresourceRange const & lhs, VkImageSubresourceRange const & rhs) inline
operator<() [1/4]
C3D_API bool castor3d::operator< (castor3d::Version const & a, castor3d::Version const & b)
Less than operator.
Parameters
[in] a,b The versions to compare.
Returns
true if a.major is less than b.major or if they are equal and a.minor is less than b.minor or if majors and minors are equal and a.build is less than b.build.
operator<() [2/4]
bool castor3d::operator< (MemChunk const & lhs, MemChunk const & rhs) inline
References castor3d::MemChunk::offset.
operator<() [3/4]
C3D_API bool castor3d::operator< (PipelineFlags const & lhs, PipelineFlags const & rhs)
operator<() [4/4]
bool castor3d::operator< (VkImageSubresourceRange const & lhs, VkImageSubresourceRange const & rhs) inline
operator<<() [1/12]
std::ostream& castor3d::operator<< (std::ostream & o, Sphere const & c) inline
operator<<() [2/12]
std::ostream& castor3d::operator<< (std::ostream & o, Icosahedron const & c) inline
operator<<() [3/12]
std::ostream& castor3d::operator<< (std::ostream & o, Cube const & c) inline
operator<<() [4/12]
std::ostream& castor3d::operator<< (std::ostream & o, Cylinder const & c) inline
operator<<() [5/12]
std::ostream& castor3d::operator<< (std::ostream & o, Plane const & c) inline
operator<<() [6/12]
std::ostream& castor3d::operator<< (std::ostream & o, Cone const & c) inline
operator<<() [7/12]
std::ostream& castor3d::operator<< (std::ostream & o, Projection const & c) inline
operator<<() [8/12]
C3D_API std::ostream& castor3d::operator<< (std::ostream & stream, castor3d::Version const & version)
operator<<() [9/12]
C3D_API std::wostream& castor3d::operator<< (std::wostream & stream, castor3d::Version const & version)
operator<<() [10/12]
C3D_API castor::String& castor3d::operator<< (castor::String & stream, castor3d::Version const & version)
operator<<() [11/12]
std::ostream& castor3d::operator<< (std::ostream & stream, TextureLayout const & layout)
operator<<() [12/12]
C3D_API std::ostream& castor3d::operator<< (std::ostream & stream, GpuInformations const & object)
Output stream operator.
Parameters
[in,out] stream The stream.
[in] object The object to put in the stream.
Returns
The stream.
operator<=() [1/2]
C3D_API bool castor3d::operator<= (castor3d::Version const & a, castor3d::Version const & b)
Less than operator.
Parameters
[in] a,b The versions to compare.
Returns
false if a.major is greater than b.major or if they are equal and a.minor is greater than b.minor or if majors and minors are equal and a.build is greater than b.build.
operator<=() [2/2]
bool castor3d::operator<= (VkImageSubresourceRange const & lhs, VkImageSubresourceRange const & rhs) inline
operator==() [1/7]
C3D_API bool castor3d::operator== (DirectionalLightCascade const & lhs, DirectionalLightCascade const & rhs)
operator==() [2/7]
bool castor3d::operator== (ParticleElementDeclaration const & lhs, ParticleElementDeclaration const & rhs) inline
Equality operator.
Parameters
[in] lhs,rhs The 2 objects to compare.
References castor3d::ParticleElementDeclaration::m_dataType, castor3d::ParticleElementDeclaration::m_divisor, castor3d::ParticleElementDeclaration::m_name, castor3d::ParticleElementDeclaration::m_offset, and castor3d::ParticleElementDeclaration::m_usages.
operator==() [3/7]
C3D_API bool castor3d::operator== (castor3d::Version const & a, castor3d::Version const & b)
Equality operator.
Parameters
[in] a,b The versions to compare.
Returns
false if one version number is different from a to b.
operator==() [4/7]
C3D_API bool castor3d::operator== (TextureFlagsId const & lhs, TextureFlagsId const & rhs)
operator==() [5/7]
C3D_API bool castor3d::operator== (TextureConfiguration const & lhs, TextureConfiguration const & rhs)
name Comparison operators.
operator==() [6/7]
C3D_API bool castor3d::operator== (ParticleDeclaration const & lhs, ParticleDeclaration const & rhs)
Equality operator.
Parameters
[in] lhs,rhs The 2 objects to compare.
operator==() [7/7]
bool castor3d::operator== (VkImageSubresourceRange const & lhs, VkImageSubresourceRange const & rhs) inline
operator>() [1/2]
C3D_API bool castor3d::operator> (castor3d::Version const & a, castor3d::Version const & b)
Less than operator.
Parameters
[in] a,b The versions to compare.
Returns
true if a.major is greater than b.major or if they are equal and a.minor is greater than b.minor or if majors and minors are equal and a.build is greater than b.build.
operator>() [2/2]
bool castor3d::operator> (VkImageSubresourceRange const & lhs, VkImageSubresourceRange const & rhs) inline
operator>=() [1/2]
C3D_API bool castor3d::operator>= (castor3d::Version const & a, castor3d::Version const & b)
Less than operator.
Parameters
[in] a,b The versions to compare.
Returns
false if a.major is less than b.major or if they are equal and a.minor is less than b.minor or if majors and minors are equal and a.build is less than b.build.
operator>=() [2/2]
bool castor3d::operator>= (VkImageSubresourceRange const & lhs, VkImageSubresourceRange const & rhs) inline
prepareChunkData() [1/28]
static void castor3d::prepareChunkData (ChunkType & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
Referenced by castor3d::ChunkParser< T >::parse(), prepareChunkData(), and castor3d::ChunkWriter< T >::write().
prepareChunkData() [2/28]
static void castor3d::prepareChunkData (bool & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [3/28]
static void castor3d::prepareChunkData (int8_t & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [4/28]
static void castor3d::prepareChunkData (uint8_t & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [5/28]
static void castor3d::prepareChunkData (int16_t & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [6/28]
static void castor3d::prepareChunkData (uint16_t & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [7/28]
static void castor3d::prepareChunkData (int32_t & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [8/28]
static void castor3d::prepareChunkData (uint32_t & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [9/28]
static void castor3d::prepareChunkData (int64_t & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [10/28]
static void castor3d::prepareChunkData (uint64_t & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [11/28]
static void castor3d::prepareChunkData (float & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [12/28]
static void castor3d::prepareChunkData (double & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [13/28]
static void castor3d::prepareChunkData (long double & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [14/28]
template<typename T > static void castor3d::prepareChunkData (std::vector< T > & values) inline static
Sets given value to big endian.
Parameters
[in,out] values The value.
prepareChunkData() [15/28]
template<typename T , size_t Count> static void castor3d::prepareChunkData (std::array< T, Count > & values) inline static
Sets given value to big endian.
Parameters
[in,out] values The value.
prepareChunkData() [16/28]
template<typename T , uint32_t Count> static void castor3d::prepareChunkData (castor::SquareMatrix< T, Count > & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [17/28]
template<typename T , uint32_t Count> static void castor3d::prepareChunkData (castor::Point< T, Count > & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [18/28]
template<typename T , uint32_t Count> static void castor3d::prepareChunkData (castor::Coords< T, Count > & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [19/28]
template<typename T > static void castor3d::prepareChunkData (castor::QuaternionT< T > & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [20/28]
static void castor3d::prepareChunkData (castor::ColourComponent & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [21/28]
static void castor3d::prepareChunkData (castor::RgbColour & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [22/28]
static void castor3d::prepareChunkData (castor::RgbaColour & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [23/28]
template<typename T > static void castor3d::prepareChunkData (OldInterleavedVertexT< T > & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [24/28]
template<typename T > static void castor3d::prepareChunkData (InterleavedVertexT< T > & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
References castor3d::InterleavedVertexT< T >::nml, castor3d::InterleavedVertexT< T >::pos, castor3d::InterleavedVertexT< T >::tan, and castor3d::InterleavedVertexT< T >::tex.
prepareChunkData() [25/28]
template<typename T > static void castor3d::prepareChunkData (SubmeshAnimationBufferT< T > & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
References castor3d::SubmeshAnimationBufferT< T >::m_buffer, and prepareChunkData().
prepareChunkData() [26/28]
static void castor3d::prepareChunkData (FaceIndices & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
References castor3d::FaceIndices::m_index.
prepareChunkData() [27/28]
static void castor3d::prepareChunkData (LineIndices & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
References castor3d::LineIndices::m_index.
prepareChunkData() [28/28]
static void castor3d::prepareChunkData (VertexBoneData & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
References castor3d::VertexBoneData::Ids::data, castor3d::VertexBoneData::Weights::data, castor3d::VertexBoneData::m_ids, and castor3d::VertexBoneData::m_weights.
setupMemory() [1/4]
template<typename ResT > ashes::DeviceMemoryPtr castor3d::setupMemory (ashes::Device const & device, ResT & resource, VkMemoryPropertyFlags flags, std::string const & name) inline
Referenced by setupMemory().
setupMemory() [2/4]
template<typename ResT > ashes::DeviceMemoryPtr castor3d::setupMemory (RenderDevice const & device, ResT & resource, VkMemoryPropertyFlags flags, std::string const & name) inline
References setupMemory().
setupMemory() [3/4]
C3D_API ashes::DeviceMemoryPtr castor3d::setupMemory (ashes::Device const & device, VkMemoryRequirements const & requirements, VkMemoryPropertyFlags flags, std::string const & name)
setupMemory() [4/4]
C3D_API ashes::DeviceMemoryPtr castor3d::setupMemory (RenderDevice const & device, VkMemoryRequirements const & requirements, VkMemoryPropertyFlags flags, std::string const & name)
Variable Documentation
CurrentCmshVersion
uint32_t constexpr castor3d::CurrentCmshVersion = makeCmshVersion(0x01u, 0x05u, 0x0000u)
The current format version number.
Referenced by castor3d::BinaryParserBase< Skeleton >::doParseHeader(), and castor3d::BinaryWriterBase< Skeleton >::doWriteHeader().
defaultClearDepthStencil
VkClearValue const castor3d::defaultClearDepthStencil { makeClearValue(1.0f, 0u) } static
defaultColorWriteMask
VkColorComponentFlags const castor3d::defaultColorWriteMask { VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT } static
InfoCacheCreatedObject
const xchar* castor3d::InfoCacheCreatedObject = cuT("Cache::create - Created ") static
Referenced by castor3d::CacheBase< Overlay, castor::String >::doReportCreation(), and castor3d::ObjectCacheBase< BillboardList, castor::String >::doReportCreation().
InvalidIndex
uint32_t constexpr castor3d::InvalidIndex = ~(0u) static
MaxBonesPerVertex
const uint32_t castor3d::MaxBonesPerVertex = 8 static
opaqueBlackClearColor
VkClearValue const castor3d::opaqueBlackClearColor { makeClearValue(0.0f, 0.0f, 0.0f, 1.0f) } static
opaqueWhiteClearColor
VkClearValue const castor3d::opaqueWhiteClearColor { makeClearValue(1.0f, 1.0f, 1.0f, 1.0f) } static
RenderTypeUndefined
castor::String const castor3d::RenderTypeUndefined = cuT("Undefined")
transparentBlackClearColor
VkClearValue const castor3d::transparentBlackClearColor { makeClearValue(0.0f, 0.0f, 0.0f, 0.0f) } static
transparentWhiteClearColor
VkClearValue const castor3d::transparentWhiteClearColor { makeClearValue(1.0f, 1.0f, 1.0f, 0.0f) } static
WarningCacheDuplicateObject
const xchar* castor3d::WarningCacheDuplicateObject = cuT("Cache::create - Duplicate ") static
Referenced by castor3d::CacheBase< Overlay, castor::String >::doReportDuplicate(), and castor3d::ObjectCacheBase< BillboardList, castor::String >::doReportDuplicate().
WarningCacheNullObject
const xchar* castor3d::WarningCacheNullObject = cuT("Cache::Insert - nullptr ") static
Referenced by castor3d::CacheBase< Overlay, castor::String >::doReportNull(), and castor3d::ObjectCacheBase< BillboardList, castor::String >::doReportNull().