Castor3D: castor3d::TextureSource Class Reference
castor3d::TextureSource Class Reference
#include <TextureSource.hpp>
Public Member Functions
TextureSource (castor::Image &image, castor::String name, castor::ImageLayout layout)
The texture buffer.
void update (VkExtent3D const &extent, VkFormat format, uint32_t mipLevels, uint32_t arrayLayers)
Public Member Functions inherited from castor::NamedBaseT< T >
NamedBaseT (T name) noexcept
Constructor.
T const & getName () const noexcept
Retrieves the name.
void rename (T name) noexcept
Accessors.
castor::String const & toString () const noexcept
uint32_t getBaseLayer () const noexcept
uint32_t getLayerCount () const noexcept
uint32_t getBaseLevel () const noexcept
uint32_t getLevelCount () const noexcept
uint32_t getDepth () const noexcept
bool hasBuffer () const noexcept
castor::ImageLayout::ConstBuffer getBuffer () const noexcept
castor::ImageLayout::Buffer getBuffer () noexcept
Additional Inherited Members
Protected Attributes inherited from castor::NamedBaseT< T >
T m_name
Constructor & Destructor Documentation
TextureSource()
castor3d::TextureSource::TextureSource (castor::Image & image, castor::String name, castor::ImageLayout layout) inline explicit
The texture buffer.
Parameters
[in] image The CPU image.
[in] name The source name.
[in] layout The CPU image layout.
Member Function Documentation
getBaseLayer()
uint32_t castor3d::TextureSource::getBaseLayer () const inline noexcept
References castor::ImageLayout::baseLayer.
getBaseLevel()
uint32_t castor3d::TextureSource::getBaseLevel () const inline noexcept
References castor::ImageLayout::baseLevel.
getBuffer() [1/2]
castor::ImageLayout::ConstBuffer castor3d::TextureSource::getBuffer () const inline noexcept
References castor::ImageLayout::buffer(), and castor::Image::getPxBuffer().
getBuffer() [2/2]
castor::ImageLayout::Buffer castor3d::TextureSource::getBuffer () inline noexcept
References castor::ImageLayout::buffer(), and castor::Image::getPxBuffer().
getDepth()
uint32_t castor3d::TextureSource::getDepth () const inline noexcept
References castor::ImageLayout::extent.
getLayerCount()
uint32_t castor3d::TextureSource::getLayerCount () const inline noexcept
References castor::ImageLayout::layers.
getLevelCount()
uint32_t castor3d::TextureSource::getLevelCount () const inline noexcept
References castor::ImageLayout::levels.
hasBuffer()
bool castor3d::TextureSource::hasBuffer () const inline noexcept
References castor::Image::getPxBuffer(), and castor::ImageLayout::hasBuffer().
toString()
castor::String const & castor3d::TextureSource::toString () const inline noexcept
References castor::NamedBaseT< T >::getName().
update()
void castor3d::TextureSource::update (VkExtent3D const & extent, VkFormat format, uint32_t mipLevels, uint32_t arrayLayers) inline
References castor::ImageLayout::extent, castor::ImageLayout::format, castor::ImageLayout::layers, and castor::ImageLayout::levels.
The documentation for this class was generated from the following file:
Castor3D/Material/Texture/TextureSource.hpp