Castor3D: Castor3D::ChunkParserBase Struct Reference
Castor3D::ChunkParserBase Struct Reference
Chunk parser.
Public Member Functions
bool operator() (uint8_t *p_pValues, uint32_t p_uiSize, BinaryChunk &p_chunk)
Retrieves a value array from a chunk.
Detailed Description
Chunk parser.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
08/04/2014
Member Function Documentation
operator()()
bool Castor3D::ChunkParserBase::operator() (uint8_t * p_pValues, uint32_t p_uiSize, BinaryChunk & p_chunk) inline
Retrieves a value array from a chunk.
Parameters
[out] p_pValues Receives the parsed values
[out] p_uiSize The values size
[in] p_chunk The chunk containing the values
Returns
false if any error occured
References Castor3D::BinaryChunk::CheckAvailable(), and Castor3D::BinaryChunk::Get().
Referenced by Castor3D::ChunkParser< T >::operator()(), Castor3D::ChunkParser< Castor::String >::operator()(), Castor3D::ChunkParser< Castor::Path >::operator()(), Castor3D::ChunkParser< Castor::Point2f >::operator()(), Castor3D::ChunkParser< Castor::Point3f >::operator()(), Castor3D::ChunkParser< Castor::Point4f >::operator()(), Castor3D::ChunkParser< Castor::Point2d >::operator()(), Castor3D::ChunkParser< Castor::Point3d >::operator()(), Castor3D::ChunkParser< Castor::Point4d >::operator()(), Castor3D::ChunkParser< Castor::Point2i >::operator()(), Castor3D::ChunkParser< Castor::Point3i >::operator()(), Castor3D::ChunkParser< Castor::Point4i >::operator()(), Castor3D::ChunkParser< Castor::Point2ui >::operator()(), Castor3D::ChunkParser< Castor::Point3ui >::operator()(), Castor3D::ChunkParser< Castor::Point4ui >::operator()(), Castor3D::ChunkParser< Castor::Coords2f >::operator()(), Castor3D::ChunkParser< Castor::Coords3f >::operator()(), Castor3D::ChunkParser< Castor::Coords4f >::operator()(), Castor3D::ChunkParser< Castor::Coords2d >::operator()(), Castor3D::ChunkParser< Castor::Coords3d >::operator()(), Castor3D::ChunkParser< Castor::Coords4d >::operator()(), Castor3D::ChunkParser< Castor::Coords2i >::operator()(), Castor3D::ChunkParser< Castor::Coords3i >::operator()(), Castor3D::ChunkParser< Castor::Coords4i >::operator()(), Castor3D::ChunkParser< Castor::Coords2ui >::operator()(), Castor3D::ChunkParser< Castor::Coords3ui >::operator()(), Castor3D::ChunkParser< Castor::Coords4ui >::operator()(), Castor3D::ChunkParser< Castor::Matrix2x2f >::operator()(), Castor3D::ChunkParser< Castor::Matrix3x3f >::operator()(), Castor3D::ChunkParser< Castor::Matrix4x4f >::operator()(), Castor3D::ChunkParser< Castor::Matrix2x2d >::operator()(), Castor3D::ChunkParser< Castor::Matrix3x3d >::operator()(), Castor3D::ChunkParser< Castor::Matrix4x4d >::operator()(), Castor3D::ChunkParser< Castor::Colour >::operator()(), Castor3D::ChunkParser< Castor::Size >::operator()(), Castor3D::ChunkParser< Castor::Position >::operator()(), and Castor3D::ChunkParser< Castor::Quaternion >::operator()().
The documentation for this struct was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/ChunkParser.hpp