Castor3D: castor3d::BinaryWriterBase< TWritten > Class Template Reference
castor3d::BinaryWriterBase< TWritten > Class Template Reference abstract
Binary data chunk writer/reader base class.
Public Member Functions
bool write (TWritten const &p_obj, castor::BinaryFile &p_file)
Writes an object to a file.
bool write (TWritten const &p_obj, BinaryChunk &p_chunk)
To chunk writer function.
Protected Member Functions
bool doWriteHeader (BinaryChunk &p_chunk) const
Writes the header chunk.
template<typename T >
bool doWriteChunk (T const *p_values, size_t p_count, ChunkType p_chunkType, BinaryChunk &p_chunk) const
Writes a subchunk value into a chunk.
template<typename T , size_t Count>
bool doWriteChunk (T const(&p_values)[Count], ChunkType p_chunkType, BinaryChunk &p_chunk) const
Writes a subchunk value into a chunk.
template<typename T , size_t Count>
bool doWriteChunk (std::array< T, Count > const &p_values, ChunkType p_chunkType, BinaryChunk &p_chunk) const
Writes a subchunk value into a chunk.
template<typename T >
bool doWriteChunk (std::vector< T > const &p_values, ChunkType p_chunkType, BinaryChunk &p_chunk) const
Writes a subchunk value into a chunk.
template<typename T >
bool doWriteChunk (T const *p_begin, T const *p_end, ChunkType p_chunkType, BinaryChunk &p_chunk) const
Writes a subchunk value into a chunk.
template<typename T >
bool doWriteChunk (T const &p_value, ChunkType p_chunkType, BinaryChunk &p_chunk) const
Writes a subchunk value into a chunk.
Protected Attributes
BinaryChunk m_chunk { ChunkTyper< TWritten >::Value }
Detailed Description
template<class TWritten>
class castor3d::BinaryWriterBase< TWritten >
Binary data chunk writer/reader base class.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
15/04/2013
Member Function Documentation
doWriteChunk() [1/6]
template<class TWritten> template<typename T > bool castor3d::BinaryWriterBase< TWritten >::doWriteChunk (T const * p_values, size_t p_count, ChunkType p_chunkType, BinaryChunk & p_chunk) const inline protected
Writes a subchunk value into a chunk.
Parameters
[in] p_values The values.
[in] p_count The values count.
[in] p_chunkType The subchunk type.
[in,out] p_chunk The chunk.
Returns
false if any error occured.
Referenced by castor3d::BinaryWriterBase< Skeleton >::doWriteHeader().
doWriteChunk() [2/6]
template<class TWritten> template<typename T , size_t Count> bool castor3d::BinaryWriterBase< TWritten >::doWriteChunk (T const(&) p_values[Count], ChunkType p_chunkType, BinaryChunk & p_chunk) const inline protected
Writes a subchunk value into a chunk.
Parameters
[in] p_values The values.
[in] p_chunkType The subchunk type.
[in,out] p_chunk The chunk.
Returns
false if any error occured.
doWriteChunk() [3/6]
template<class TWritten> template<typename T , size_t Count> bool castor3d::BinaryWriterBase< TWritten >::doWriteChunk (std::array< T, Count > const & p_values, ChunkType p_chunkType, BinaryChunk & p_chunk) const inline protected
Writes a subchunk value into a chunk.
Parameters
[in] p_values The values.
[in] p_chunkType The subchunk type.
[in,out] p_chunk The chunk.
Returns
false if any error occured.
doWriteChunk() [4/6]
template<class TWritten> template<typename T > bool castor3d::BinaryWriterBase< TWritten >::doWriteChunk (std::vector< T > const & p_values, ChunkType p_chunkType, BinaryChunk & p_chunk) const inline protected
Writes a subchunk value into a chunk.
Parameters
[in] p_values The values.
[in] p_chunkType The subchunk type.
[in,out] p_chunk The chunk.
Returns
false if any error occured.
doWriteChunk() [5/6]
template<class TWritten> template<typename T > bool castor3d::BinaryWriterBase< TWritten >::doWriteChunk (T const * p_begin, T const * p_end, ChunkType p_chunkType, BinaryChunk & p_chunk) const inline protected
Writes a subchunk value into a chunk.
Parameters
[in] p_begin The values begin.
[in] p_end The values end.
[in] p_chunkType The subchunk type.
[in,out] p_chunk The chunk.
Returns
false if any error occured.
doWriteChunk() [6/6]
template<class TWritten> template<typename T > bool castor3d::BinaryWriterBase< TWritten >::doWriteChunk (T const & p_value, ChunkType p_chunkType, BinaryChunk & p_chunk) const inline protected
Writes a subchunk value into a chunk.
Parameters
[in] p_value The value.
[in] p_chunkType The subchunk type.
[in,out] p_chunk The chunk.
Returns
false if any error occured.
doWriteHeader()
template<class TWritten> bool castor3d::BinaryWriterBase< TWritten >::doWriteHeader (BinaryChunk & p_chunk) const inline protected
Writes the header chunk.
Parameters
[in,out] p_chunk The parent chunk.
Returns
false if any error occured.
Referenced by castor3d::BinaryWriterBase< Skeleton >::write().
write() [1/2]
template<class TWritten> bool castor3d::BinaryWriterBase< TWritten >::write (TWritten const & p_obj, castor::BinaryFile & p_file) inline
Writes an object to a file.
Parameters
[in] p_obj The object to write.
[in,out] p_file The file.
Returns
false if any error occured.
Referenced by castor3d::BinaryWriterBase< Skeleton >::write().
write() [2/2]
template<class TWritten> bool castor3d::BinaryWriterBase< TWritten >::write (TWritten const & p_obj, BinaryChunk & p_chunk) inline
To chunk writer function.
Parameters
[in] p_obj The object to write.
[in,out] p_chunk The chunk.
Returns
false if any error occured.
Member Data Documentation
m_chunk
template<class TWritten> BinaryChunk castor3d::BinaryWriterBase< TWritten >::m_chunk { ChunkTyper< TWritten >::Value } protected
The writer's chunk.
Referenced by castor3d::BinaryWriterBase< Skeleton >::write().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Binary/BinaryWriter.hpp