Castor3D: castor::NamedBaseT< T > Class Template Reference
castor::NamedBaseT< T > Class Template Reference
Class for named elements.
#include <Named.hpp>
Public Member Functions
NamedBaseT (T name) noexcept
Constructor.
T const & getName () const noexcept
Retrieves the name.
void rename (T name) noexcept
Protected Attributes
T m_name
Detailed Description
template<typename T>
class castor::NamedBaseT< T >
Class for named elements.
Remarks
The name type is a template argument so anything can be a name for this class (default is castor::String)
Constructor & Destructor Documentation
NamedBaseT()
template<typename T > castor::NamedBaseT< T >::NamedBaseT (T name) inline explicit noexcept
Constructor.
Parameters
[in] name The name
Member Function Documentation
getName()
template<typename T > T const & castor::NamedBaseT< T >::getName () const inline noexcept
Retrieves the name.
Returns
The name
References castor::NamedBaseT< T >::m_name.
Referenced by castor3d::ControlStyle::doCreateMaterial(), castor::ResourceMergerT< CacheT >::operator()(), castor3d::MovableMergerT< CacheT >::operator()(), castor3d::SceneNodeMergerT< CacheT >::operator()(), and castor3d::TextureSource::toString().
rename()
template<typename T > void castor::NamedBaseT< T >::rename (T name) inline noexcept
References castor::NamedBaseT< T >::m_name.
Member Data Documentation
m_name
template<typename T > T castor::NamedBaseT< T >::m_name protected
Referenced by castor::NamedBaseT< T >::getName(), and castor::NamedBaseT< T >::rename().
The documentation for this class was generated from the following files:
CastorUtils/Design/DesignModule.hpp
CastorUtils/Design/Named.hpp