Castor3D: castor3d::ShadowMap Class Reference
castor3d::ShadowMap Class Reference abstract
Shadow mapping implementation.
Public Member Functions
C3D_API ShadowMap (Engine &engine, TextureUnit &&shadowMap, TextureUnit &&linearMap, ShadowMapPassSPtr pass)
Constructor.
C3D_API ~ShadowMap ()
Destructor.
C3D_API bool initialise ()
Initialises the frame buffer and light type specific data.
C3D_API void cleanup ()
Cleans up the frame buffer and light type specific data.
virtual C3D_API void update (Camera const &camera, RenderQueueArray &queues, Light &light, uint32_t index)=0
Updates the passes, selecting the lights that will project shadows.
virtual C3D_API void render ()=0
Renders the given light's shadow map.
virtual C3D_API void debugDisplay (castor::Size const &size, uint32_t index)=0
Dumps the shadow map on screen.
C3D_API void updateFlags (PassFlags &passFlags, TextureChannels &textureFlags, ProgramFlags &programFlags, SceneFlags &sceneFlags) const
Modifies the given flags to make them match the render pass requirements.
C3D_API glsl::Shader getVertexShaderSource (PassFlags const &passFlags, TextureChannels const &textureFlags, ProgramFlags const &programFlags, SceneFlags const &sceneFlags, bool invertNormals) const
Retrieves the vertex shader source matching the given flags.
C3D_API glsl::Shader getGeometryShaderSource (PassFlags const &passFlags, TextureChannels const &textureFlags, ProgramFlags const &programFlags, SceneFlags const &sceneFlags) const
Retrieves the geometry shader source matching the given flags.
C3D_API glsl::Shader getPixelShaderSource (PassFlags const &passFlags, TextureChannels const &textureFlags, ProgramFlags const &programFlags, SceneFlags const &sceneFlags, ComparisonFunc alphaFunc) const
Retrieves the pixel shader source matching the given flags.
TextureUnit & getTexture ()
TextureUnit const & getTexture () const
TextureUnit & getDepth ()
TextureUnit const & getDepth () const
Protected Member Functions
void doDiscardAlpha (glsl::GlslWriter &writer, TextureChannels const &textureFlags, ComparisonFunc alphaFunc, glsl::Int const &material, shader::Materials const &materials) const
Discards materials with alpha blend or alpha func, if needed.
Protected Attributes
FrameBufferSPtr m_frameBuffer
std::set< GeometryBuffersSPtr > m_geometryBuffers
ShadowMapPassSPtr m_pass
TextureUnit m_shadowMap
TextureUnit m_linearMap
Detailed Description
Shadow mapping implementation.
Author
Sylvain DOREMUS
Version
0.9.0
Date
30/08/2016
Constructor & Destructor Documentation
ShadowMap()
C3D_API castor3d::ShadowMap::ShadowMap (Engine & engine, TextureUnit && shadowMap, TextureUnit && linearMap, ShadowMapPassSPtr pass)
Constructor.
Parameters
[in] engine The engine.
[in] shadowMap The shadow map.
[in] linearMap The linear depth map.
[in] pass The pass used to render map.
~ShadowMap()
C3D_API castor3d::ShadowMap::~ShadowMap ()
Destructor.
Member Function Documentation
cleanup()
C3D_API void castor3d::ShadowMap::cleanup ()
Cleans up the frame buffer and light type specific data.
debugDisplay()
virtual C3D_API void castor3d::ShadowMap::debugDisplay (castor::Size const & size, uint32_t index) pure virtual
Dumps the shadow map on screen.
Parameters
[in] size The dump dimensions.
[in] index The shadow map index (to compute its position).
Implemented in castor3d::ShadowMapDirectional, castor3d::ShadowMapPoint, and castor3d::ShadowMapSpot.
doDiscardAlpha()
void castor3d::ShadowMap::doDiscardAlpha (glsl::GlslWriter & writer, TextureChannels const & textureFlags, ComparisonFunc alphaFunc, glsl::Int const & material, shader::Materials const & materials) const protected
Discards materials with alpha blend or alpha func, if needed.
Parameters
[in] writer The GLSL writer.
[in] textureFlags The texture flags.
alphaFunc The alpha function.
[in] material The material index.
[in] materials The materials.
getDepth() [1/2]
TextureUnit& castor3d::ShadowMap::getDepth () inline
Returns
The linear depth map.
La texture de profondeur linéaire.
References m_linearMap.
Referenced by castor3d::LightPassShadow< LtType >::render().
getDepth() [2/2]
TextureUnit const& castor3d::ShadowMap::getDepth () const inline
Returns
The linear depth map.
La texture de profondeur linéaire.
References m_linearMap.
getGeometryShaderSource()
C3D_API glsl::Shader castor3d::ShadowMap::getGeometryShaderSource (PassFlags const & passFlags, TextureChannels const & textureFlags, ProgramFlags const & programFlags, SceneFlags const & sceneFlags) const
Retrieves the geometry shader source matching the given flags.
Parameters
[in] passFlags A combination of PassFlag.
[in] textureFlags A combination of TextureChannel.
[in] programFlags A combination of ProgramFlag.
[in] sceneFlags Scene related flags.
getPixelShaderSource()
C3D_API glsl::Shader castor3d::ShadowMap::getPixelShaderSource (PassFlags const & passFlags, TextureChannels const & textureFlags, ProgramFlags const & programFlags, SceneFlags const & sceneFlags, ComparisonFunc alphaFunc) const
Retrieves the pixel shader source matching the given flags.
Parameters
[in] passFlags A combination of PassFlag.
[in] textureFlags A combination of TextureChannel.
[in] programFlags A combination of ProgramFlag.
[in] sceneFlags Scene related flags.
[in] alphaFunc The alpha test function.
getTexture() [1/2]
TextureUnit& castor3d::ShadowMap::getTexture () inline
Returns
The shadow map.
La texture d'ombres.
References m_shadowMap.
Referenced by castor3d::LightPassShadowTraits< LightType::eDirectional >::getTexture(), castor3d::LightPassShadowTraits< LightType::eSpot >::getTexture(), and castor3d::LightPassShadow< LtType >::render().
getTexture() [2/2]
TextureUnit const& castor3d::ShadowMap::getTexture () const inline
Returns
The shadow map.
La texture d'ombres.
References m_shadowMap.
getVertexShaderSource()
C3D_API glsl::Shader castor3d::ShadowMap::getVertexShaderSource (PassFlags const & passFlags, TextureChannels const & textureFlags, ProgramFlags const & programFlags, SceneFlags const & sceneFlags, bool invertNormals) const
Retrieves the vertex shader source matching the given flags.
Parameters
[in] passFlags A combination of PassFlag.
[in] textureFlags A combination of TextureChannel.
[in] programFlags A combination of ProgramFlag.
[in] sceneFlags Scene related flags.
[in] invertNormals Tells if the normals must be inverted, in the program.
initialise()
C3D_API bool castor3d::ShadowMap::initialise ()
Initialises the frame buffer and light type specific data.
render()
virtual C3D_API void castor3d::ShadowMap::render () pure virtual
Renders the given light's shadow map.
Implemented in castor3d::ShadowMapDirectional, castor3d::ShadowMapPoint, and castor3d::ShadowMapSpot.
update()
virtual C3D_API void castor3d::ShadowMap::update (Camera const & camera, RenderQueueArray & queues, Light & light, uint32_t index) pure virtual
Updates the passes, selecting the lights that will project shadows.
Remarks
Gather the render queues, for further update.
Parameters
[in] camera The viewer camera.
[out] queues Receives the render queues needed for the rendering of the frame.
[out] light The light source.
[out] index The map index.
Implemented in castor3d::ShadowMapDirectional, castor3d::ShadowMapPoint, and castor3d::ShadowMapSpot.
updateFlags()
C3D_API void castor3d::ShadowMap::updateFlags (PassFlags & passFlags, TextureChannels & textureFlags, ProgramFlags & programFlags, SceneFlags & sceneFlags) const
Modifies the given flags to make them match the render pass requirements.
Parameters
[in,out] passFlags A combination of PassFlag.
[in,out] textureFlags A combination of TextureChannel.
[in,out] programFlags A combination of ProgramFlag.
[in,out] sceneFlags A combination of SceneFlag.
Member Data Documentation
m_frameBuffer
FrameBufferSPtr castor3d::ShadowMap::m_frameBuffer protected
The frame buffer.
m_geometryBuffers
std::set< GeometryBuffersSPtr > castor3d::ShadowMap::m_geometryBuffers protected
The geometry buffer.
m_linearMap
TextureUnit castor3d::ShadowMap::m_linearMap protected
The linear depth texture.
Referenced by getDepth().
m_pass
ShadowMapPassSPtr castor3d::ShadowMap::m_pass protected
The shadow mapping passes used during the render.
m_shadowMap
TextureUnit castor3d::ShadowMap::m_shadowMap protected
The shadow map texture.
Referenced by castor3d::ShadowMapPoint::getTexture(), and getTexture().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/ShadowMap/ShadowMap.hpp