Castor3D: castor3d::InstantiatedObjectsNodesViewT< NodeT > Struct Template Reference
castor3d::InstantiatedObjectsNodesViewT< NodeT > Struct Template Reference
#include <InstantiatedPipelinesNodes.hpp>
Public Types
using NodeObject = NodeObjectT< NodeT >
using NodeInstance = NodeInstanceT< NodeT >
using RenderedNode = RenderedNodeT< NodeT >
using NodeInstances = castor::Pair< RenderedNode, castor::UnorderedSet< NodeInstance const * > >
Public Member Functions
auto emplace (RenderedNode node)
void clear () noexcept
auto begin () noexcept
auto begin () const noexcept
auto end () noexcept
auto end () const noexcept
auto size () const noexcept
auto empty () const noexcept
size_t occupancy () const noexcept
Static Public Attributes
static uint64_t constexpr maxObjects = 1024ULL
static uint64_t constexpr maxCount = maxObjects
Member Typedef Documentation
NodeInstance
template<typename NodeT > using castor3d::InstantiatedObjectsNodesViewT< NodeT >::NodeInstance = NodeInstanceT< NodeT >
NodeInstances
template<typename NodeT > using castor3d::InstantiatedObjectsNodesViewT< NodeT >::NodeInstances = castor::Pair< RenderedNode, castor::UnorderedSet< NodeInstance const * > >
NodeObject
template<typename NodeT > using castor3d::InstantiatedObjectsNodesViewT< NodeT >::NodeObject = NodeObjectT< NodeT >
RenderedNode
template<typename NodeT > using castor3d::InstantiatedObjectsNodesViewT< NodeT >::RenderedNode = RenderedNodeT< NodeT >
Member Function Documentation
begin() [1/2]
template<typename NodeT > auto castor3d::InstantiatedObjectsNodesViewT< NodeT >::begin () const inline noexcept
begin() [2/2]
template<typename NodeT > auto castor3d::InstantiatedObjectsNodesViewT< NodeT >::begin () inline noexcept
Referenced by castor3d::InstantiatedObjectsNodesViewT< NodeT >::emplace().
clear()
template<typename NodeT > void castor3d::InstantiatedObjectsNodesViewT< NodeT >::clear () inline noexcept
emplace()
template<typename NodeT > auto castor3d::InstantiatedObjectsNodesViewT< NodeT >::emplace (RenderedNode node) inline
References castor3d::InstantiatedObjectsNodesViewT< NodeT >::begin(), castor3d::C3D_EnsureNodesCounts, CU_Assert, CU_Exception, castor3d::InstantiatedObjectsNodesViewT< NodeT >::end(), castor3d::InstantiatedObjectsNodesViewT< NodeT >::maxObjects, and castor3d::InstantiatedObjectsNodesViewT< NodeT >::size().
empty()
template<typename NodeT > auto castor3d::InstantiatedObjectsNodesViewT< NodeT >::empty () const inline noexcept
end() [1/2]
template<typename NodeT > auto castor3d::InstantiatedObjectsNodesViewT< NodeT >::end () const inline noexcept
end() [2/2]
template<typename NodeT > auto castor3d::InstantiatedObjectsNodesViewT< NodeT >::end () inline noexcept
Referenced by castor3d::InstantiatedObjectsNodesViewT< NodeT >::emplace().
occupancy()
template<typename NodeT > size_t castor3d::InstantiatedObjectsNodesViewT< NodeT >::occupancy () const inline noexcept
References castor3d::InstantiatedObjectsNodesViewT< NodeT >::size().
size()
template<typename NodeT > auto castor3d::InstantiatedObjectsNodesViewT< NodeT >::size () const inline noexcept
Referenced by castor3d::InstantiatedObjectsNodesViewT< NodeT >::emplace(), and castor3d::InstantiatedObjectsNodesViewT< NodeT >::occupancy().
Member Data Documentation
maxCount
template<typename NodeT > uint64_t constexpr castor3d::InstantiatedObjectsNodesViewT< NodeT >::maxCount = maxObjects static constexpr
maxObjects
template<typename NodeT > uint64_t constexpr castor3d::InstantiatedObjectsNodesViewT< NodeT >::maxObjects = 1024ULL static constexpr
Referenced by castor3d::InstantiatedObjectsNodesViewT< NodeT >::emplace().
The documentation for this struct was generated from the following file:
Castor3D/Render/Node/InstantiatedPipelinesNodes.hpp