Castor3D: castor3d::ChunkParser< T > Class Template Reference
castor3d::ChunkParser< T > Class Template Reference
Chunk parser.
Static Public Member Functions
static bool parse (T *p_values, size_t p_count, BinaryChunk &p_chunk)
Retrieves a value array from a chunk.
static bool parse (T &p_value, BinaryChunk &p_chunk)
Retrieves a value from a chunk.
Static Public Member Functions inherited from castor3d::ChunkParserBase
static bool parse (uint8_t *p_values, size_t p_size, BinaryChunk &p_chunk)
Retrieves a value array from a chunk.
Detailed Description
template<typename T>
class castor3d::ChunkParser< T >
Chunk parser.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
08/04/2014
Member Function Documentation
parse() [1/2]
template<typename T > static bool castor3d::ChunkParser< T >::parse (T * p_values, size_t p_count, BinaryChunk & p_chunk) inline static
Retrieves a value array from a chunk.
Parameters
[out] p_values Receives the parsed values
[out] p_count The values count
[in] p_chunk The chunk containing the values
Returns
false if any error occured
References castor3d::ChunkParserBase::parse(), and castor3d::prepareChunkData().
Referenced by castor3d::BinaryParserBase< Skeleton >::doParseChunk().
parse() [2/2]
template<typename T > static bool castor3d::ChunkParser< T >::parse (T & p_value, BinaryChunk & p_chunk) inline static
Retrieves a value from a chunk.
Parameters
[out] p_value Receives the parsed value
[in] p_chunk The chunk containing the value
Returns
false if any error occured
References castor3d::getBuffer(), castor3d::getDataSize(), castor3d::ChunkParserBase::parse(), and castor3d::prepareChunkData().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Binary/ChunkParser.hpp