Castor3D: castor3d::Pass Class Reference
castor3d::Pass Class Reference
#include <Pass.hpp>
Public Types
using UnitArray = castor::Vector< TextureUnitRPtr >
using PassTextureSource = castor::Pair< TextureSourceInfo, PassTextureConfig >
using TextureSourceArray = castor::Vector< PassTextureSource >
using UnitDataSources = castor::Map< TextureUnitDataRPtr, castor::Vector< TextureSourceInfo > >
Public Member Functions
C3D_API Pass (Material &parent, LightingModelID lightingModelId)
Constructor.
C3D_API Pass (Material &parent, Pass const &rhs)
Copy constructor.
C3D_API ~Pass () noexcept
Destructor.
C3D_API void initialise ()
Initialises the pass and all it's dependencies.
C3D_API void cleanup ()
Cleans up the pass and all it's dependencies.
C3D_API void update ()
Updates the render pass, CPU wise.
C3D_API TextureUnitRPtr getTextureUnit (uint32_t index) const
Retrieves the TextureUnit at the given index.
C3D_API void registerTexture (TextureSourceInfo sourceInfo, PassTextureConfig configuration)
Adds a texture.
C3D_API void registerTexture (TextureSourceInfo sourceInfo, PassTextureConfig configuration, TextureAnimationUPtr animation)
Adds an animated texture.
C3D_API void unregisterTexture (TextureSourceInfo const &sourceInfo) noexcept
Removes a texture unit.
C3D_API void resetTexture (TextureSourceInfo const &srcSourceInfo, TextureSourceInfo dstSourceInfo)
Replaces a texture source.
C3D_API void updateConfig (TextureSourceInfo const &sourceInfo, TextureConfiguration configuration)
Updates the configuration for a texture.
C3D_API void prepareTextures ()
Reduces the textures.
C3D_API void setColour (castor::HdrRgbColour const &value)
Sets the basic pass colour.
C3D_API castor::HdrRgbColour const & getColour () const
C3D_API PassComponentCombine getPassFlags () const noexcept
C3D_API void accept (ConfigurationVisitorBase &vis)
ConfigurationVisitorBase acceptance function.
C3D_API void fillBuffer (PassBuffer &buffer) const
Fills the pass buffer with this pass data.
C3D_API bool writeText (castor::String const &tabs, castor::Path const &folder, castor::String const &subfolder, castor::StringStream &file) const
Writes the component content to text.
C3D_API void fillConfig (TextureConfiguration &config, ConfigurationVisitorBase &vis)
ConfigurationVisitorBase acceptance function, for a specific texture configuration.
Components handling.
C3D_API void addComponent (PassComponentUPtr component)
C3D_API bool hasComponent (castor::String const &name) const noexcept
C3D_API PassComponent * getComponent (castor::String const &name) const
C3D_API castor::Vector< PassComponentUPtr > removeComponent (castor::String const &name)
C3D_API shader::PassMaterialShader * getMaterialShader (castor::String const &componentType) const
C3D_API PassComponentID getComponentId (castor::String const &componentType) const
C3D_API PassComponentPlugin const & getComponentPlugin (PassComponentID componentId) const
C3D_API PassComponentCombineID getComponentCombineID () const
C3D_API TextureCombineID getTextureCombineID () const
uint32_t getHash () const noexcept
PassComponentPlugin const & getComponentPlugin (castor::String const &componentType) const
template<typename ComponentT >
PassComponentPlugin const & getComponentPlugin () const
template<typename ComponentT >
void removeComponent ()
template<typename ComponentT , typename ... ParamsT>
ComponentT * createComponent (ParamsT &&... params)
template<typename ComponentT >
bool hasComponent () const noexcept
template<typename ComponentT >
ComponentT * getComponent () const noexcept
PassComponentMap const & getComponents () const
C3D_API bool needsAlphaProcessing () const
C3D_API bool hasAlphaBlending () const
C3D_API bool hasOnlyAlphaBlending () const
C3D_API bool hasAlphaTest () const
C3D_API bool hasBlendAlphaTest () const
C3D_API BlendMode getAlphaBlendMode () const
C3D_API BlendMode getColourBlendMode () const
C3D_API VkCompareOp getAlphaFunc () const
C3D_API VkCompareOp getBlendAlphaFunc () const
C3D_API bool hasEnvironmentMapping () const
C3D_API bool hasSubsurfaceScattering () const
C3D_API bool isTwoSided () const
C3D_API UnitArray getTextureUnits () const
C3D_API uint32_t getTextureUnitsCount () const
C3D_API TextureCombine getTexturesMask () const noexcept
C3D_API bool hasLighting () const
C3D_API PassComponentRegister & getPassComponentsRegister () const
C3D_API castor::String getTextureFlagsName (PassComponentTextureFlag flags) const
C3D_API LightingModelID getLightingModelId () const
bool isInitialised () const noexcept
bool isInitialising () const noexcept
bool hasAutomaticShader () const noexcept
uint32_t getId () const noexcept
bool isImplicit () const noexcept
RenderPassRegisterInfo * getRenderPassInfo () const noexcept
uint32_t getIndex () const noexcept
uint32_t getMaxTexCoordSet () const noexcept
PassComponentTextureFlag getColourMapFlags () const noexcept
PassComponentTextureFlag getOpacityMapFlags () const noexcept
PassComponentTextureFlag getNormalMapFlags () const noexcept
PassComponentTextureFlag getHeightMapFlags () const noexcept
PassComponentTextureFlag getOcclusionMapFlags () const noexcept
PassComponentTextureFlag getReflRefrFlags () const noexcept
auto begin () const noexcept
auto begin () noexcept
auto end () const noexcept
auto end () noexcept
C3D_API void enableLighting (bool value) const
C3D_API void enablePicking (bool value) const
void setId (uint32_t value) noexcept
void setImplicit (bool value=true) noexcept
void setColour (castor::RgbColour const &v, float gamma=2.2f)
void setColour (castor::Coords3f const &v)
void setColour (castor::Point3f const &v)
void reset () const noexcept
Public Member Functions inherited from castor::OwnedBy< Material >
Material * getOwner () const
Static Public Member Functions
static C3D_API void addParsers (castor::AttributeParsers &result, castor::UInt32StrMap const &textureChannels)
static C3D_API float computeRoughnessFromGlossiness (float glossiness)
static C3D_API float computeGlossinessFromRoughness (float roughness)
static C3D_API float computeGlossinessFromShininess (float shininess)
static C3D_API float computeShininessFromGlossiness (float glossiness)
static float computeRoughnessFromShininess (float const &shininess)
static float computeShininessFromRoughness (float const &roughness)
Public Attributes
OnPassChanged onChanged
Protected Attributes
std::atomic_bool m_dirty { true }
Friends
struct PassComponent
Additional Inherited Members
Protected Member Functions inherited from castor::OwnedBy< Material >
OwnedBy (Material &owner)
Constructor.
Member Typedef Documentation
PassTextureSource
using castor3d::Pass::PassTextureSource = castor::Pair< TextureSourceInfo, PassTextureConfig >
TextureSourceArray
using castor3d::Pass::TextureSourceArray = castor::Vector< PassTextureSource >
UnitArray
using castor3d::Pass::UnitArray = castor::Vector< TextureUnitRPtr >
UnitDataSources
using castor3d::Pass::UnitDataSources = castor::Map< TextureUnitDataRPtr, castor::Vector< TextureSourceInfo > >
Constructor & Destructor Documentation
Pass() [1/2]
C3D_API castor3d::Pass::Pass (Material & parent, LightingModelID lightingModelId)
Constructor.
Parameters
[in] parent The parent material.
[in] lightingModelId The material's lighting model ID.
Pass() [2/2]
C3D_API castor3d::Pass::Pass (Material & parent, Pass const & rhs)
Copy constructor.
Parameters
[in] parent The parent material.
[in] rhs The pass top copy.
~Pass()
C3D_API castor3d::Pass::~Pass () noexcept
Destructor.
Member Function Documentation
accept()
C3D_API void castor3d::Pass::accept (ConfigurationVisitorBase & vis)
ConfigurationVisitorBase acceptance function.
Parameters
vis The ... visitor.
addComponent()
C3D_API void castor3d::Pass::addComponent (PassComponentUPtr component)
Referenced by createComponent().
addParsers()
static C3D_API void castor3d::Pass::addParsers (castor::AttributeParsers & result, castor::UInt32StrMap const & textureChannels) static
begin() [1/2]
auto castor3d::Pass::begin () const inline noexcept
name Textures iteration.
begin() [2/2]
auto castor3d::Pass::begin () inline noexcept
cleanup()
C3D_API void castor3d::Pass::cleanup ()
Cleans up the pass and all it's dependencies.
computeGlossinessFromRoughness()
static C3D_API float castor3d::Pass::computeGlossinessFromRoughness (float roughness) static
Referenced by computeShininessFromRoughness().
computeGlossinessFromShininess()
static C3D_API float castor3d::Pass::computeGlossinessFromShininess (float shininess) static
Referenced by computeRoughnessFromShininess().
computeRoughnessFromGlossiness()
static C3D_API float castor3d::Pass::computeRoughnessFromGlossiness (float glossiness) static
Referenced by computeRoughnessFromShininess().
computeRoughnessFromShininess()
static float castor3d::Pass::computeRoughnessFromShininess (float const & shininess) inline static
References computeGlossinessFromShininess(), and computeRoughnessFromGlossiness().
computeShininessFromGlossiness()
static C3D_API float castor3d::Pass::computeShininessFromGlossiness (float glossiness) static
Referenced by computeShininessFromRoughness().
computeShininessFromRoughness()
static float castor3d::Pass::computeShininessFromRoughness (float const & roughness) inline static
References computeGlossinessFromRoughness(), and computeShininessFromGlossiness().
createComponent()
template<typename ComponentT , typename ... ParamsT> ComponentT * castor3d::Pass::createComponent (ParamsT &&... params) inline
References addComponent().
enableLighting()
C3D_API void castor3d::Pass::enableLighting (bool value) const
name Mutators.
enablePicking()
C3D_API void castor3d::Pass::enablePicking (bool value) const
end() [1/2]
auto castor3d::Pass::end () const inline noexcept
end() [2/2]
auto castor3d::Pass::end () inline noexcept
fillBuffer()
C3D_API void castor3d::Pass::fillBuffer (PassBuffer & buffer) const
Fills the pass buffer with this pass data.
Parameters
[in,out] buffer The pass buffer.
fillConfig()
C3D_API void castor3d::Pass::fillConfig (TextureConfiguration & config, ConfigurationVisitorBase & vis)
ConfigurationVisitorBase acceptance function, for a specific texture configuration.
Parameters
config The texture configuration.
vis The ... visitor.
getAlphaBlendMode()
C3D_API BlendMode castor3d::Pass::getAlphaBlendMode () const
getAlphaFunc()
C3D_API VkCompareOp castor3d::Pass::getAlphaFunc () const
getBlendAlphaFunc()
C3D_API VkCompareOp castor3d::Pass::getBlendAlphaFunc () const
getColour()
C3D_API castor::HdrRgbColour const & castor3d::Pass::getColour () const
Returns
The basic pass colour.
getColourBlendMode()
C3D_API BlendMode castor3d::Pass::getColourBlendMode () const
getColourMapFlags()
PassComponentTextureFlag castor3d::Pass::getColourMapFlags () const inline noexcept
getComponent() [1/2]
template<typename ComponentT > ComponentT * castor3d::Pass::getComponent () const inline noexcept
References getComponent().
Referenced by getComponent().
getComponent() [2/2]
C3D_API PassComponent * castor3d::Pass::getComponent (castor::String const & name) const
getComponentCombineID()
C3D_API PassComponentCombineID castor3d::Pass::getComponentCombineID () const
Referenced by getHash().
getComponentId()
C3D_API PassComponentID castor3d::Pass::getComponentId (castor::String const & componentType) const
Referenced by getComponentPlugin(), and getComponentPlugin().
getComponentPlugin() [1/3]
template<typename ComponentT > PassComponentPlugin const & castor3d::Pass::getComponentPlugin () const inline
References getComponentId(), and getComponentPlugin().
Referenced by getComponentPlugin(), and getComponentPlugin().
getComponentPlugin() [2/3]
PassComponentPlugin const & castor3d::Pass::getComponentPlugin (castor::String const & componentType) const inline
References getComponentId(), and getComponentPlugin().
getComponentPlugin() [3/3]
C3D_API PassComponentPlugin const & castor3d::Pass::getComponentPlugin (PassComponentID componentId) const
getComponents()
PassComponentMap const & castor3d::Pass::getComponents () const inline
getHash()
uint32_t castor3d::Pass::getHash () const inline noexcept
References getComponentCombineID(), and getTextureCombineID().
getHeightMapFlags()
PassComponentTextureFlag castor3d::Pass::getHeightMapFlags () const inline noexcept
getId()
uint32_t castor3d::Pass::getId () const inline noexcept
getIndex()
uint32_t castor3d::Pass::getIndex () const inline noexcept
getLightingModelId()
C3D_API LightingModelID castor3d::Pass::getLightingModelId () const
getMaterialShader()
C3D_API shader::PassMaterialShader * castor3d::Pass::getMaterialShader (castor::String const & componentType) const
getMaxTexCoordSet()
uint32_t castor3d::Pass::getMaxTexCoordSet () const inline noexcept
getNormalMapFlags()
PassComponentTextureFlag castor3d::Pass::getNormalMapFlags () const inline noexcept
getOcclusionMapFlags()
PassComponentTextureFlag castor3d::Pass::getOcclusionMapFlags () const inline noexcept
getOpacityMapFlags()
PassComponentTextureFlag castor3d::Pass::getOpacityMapFlags () const inline noexcept
getPassComponentsRegister()
C3D_API PassComponentRegister & castor3d::Pass::getPassComponentsRegister () const
getPassFlags()
C3D_API PassComponentCombine castor3d::Pass::getPassFlags () const noexcept
Returns
The pass flags combination.
getReflRefrFlags()
PassComponentTextureFlag castor3d::Pass::getReflRefrFlags () const inline noexcept
getRenderPassInfo()
RenderPassRegisterInfo * castor3d::Pass::getRenderPassInfo () const inline noexcept
getTextureCombineID()
C3D_API TextureCombineID castor3d::Pass::getTextureCombineID () const
Referenced by getHash().
getTextureFlagsName()
C3D_API castor::String castor3d::Pass::getTextureFlagsName (PassComponentTextureFlag flags) const
getTexturesMask()
C3D_API TextureCombine castor3d::Pass::getTexturesMask () const noexcept
getTextureUnit()
C3D_API TextureUnitRPtr castor3d::Pass::getTextureUnit (uint32_t index) const
Retrieves the TextureUnit at the given index.
Parameters
[in] index The index of the TextureUnit to retrieve.
Returns
nullptr if index was out of bounds.
getTextureUnits()
C3D_API UnitArray castor3d::Pass::getTextureUnits () const
getTextureUnitsCount()
C3D_API uint32_t castor3d::Pass::getTextureUnitsCount () const
hasAlphaBlending()
C3D_API bool castor3d::Pass::hasAlphaBlending () const
hasAlphaTest()
C3D_API bool castor3d::Pass::hasAlphaTest () const
hasAutomaticShader()
bool castor3d::Pass::hasAutomaticShader () const inline noexcept
hasBlendAlphaTest()
C3D_API bool castor3d::Pass::hasBlendAlphaTest () const
hasComponent() [1/2]
template<typename ComponentT > bool castor3d::Pass::hasComponent () const inline noexcept
References hasComponent().
Referenced by hasComponent().
hasComponent() [2/2]
C3D_API bool castor3d::Pass::hasComponent (castor::String const & name) const noexcept
hasEnvironmentMapping()
C3D_API bool castor3d::Pass::hasEnvironmentMapping () const
hasLighting()
C3D_API bool castor3d::Pass::hasLighting () const
hasOnlyAlphaBlending()
C3D_API bool castor3d::Pass::hasOnlyAlphaBlending () const
hasSubsurfaceScattering()
C3D_API bool castor3d::Pass::hasSubsurfaceScattering () const
initialise()
C3D_API void castor3d::Pass::initialise ()
Initialises the pass and all it's dependencies.
isImplicit()
bool castor3d::Pass::isImplicit () const inline noexcept
isInitialised()
bool castor3d::Pass::isInitialised () const inline noexcept
isInitialising()
bool castor3d::Pass::isInitialising () const inline noexcept
isTwoSided()
C3D_API bool castor3d::Pass::isTwoSided () const
needsAlphaProcessing()
C3D_API bool castor3d::Pass::needsAlphaProcessing () const
name Getters.
prepareTextures()
C3D_API void castor3d::Pass::prepareTextures ()
Reduces the textures.
registerTexture() [1/2]
C3D_API void castor3d::Pass::registerTexture (TextureSourceInfo sourceInfo, PassTextureConfig configuration)
Adds a texture.
Parameters
[in] sourceInfo The texture source.
[in] configuration The texture configuration.
registerTexture() [2/2]
C3D_API void castor3d::Pass::registerTexture (TextureSourceInfo sourceInfo, PassTextureConfig configuration, TextureAnimationUPtr animation)
Adds an animated texture.
Parameters
[in] sourceInfo The texture source.
[in] configuration The texture configuration.
[in] animation The texture animation.
removeComponent() [1/2]
template<typename ComponentT > void castor3d::Pass::removeComponent () inline
References removeComponent().
Referenced by removeComponent().
removeComponent() [2/2]
C3D_API castor::Vector< PassComponentUPtr > castor3d::Pass::removeComponent (castor::String const & name)
reset()
void castor3d::Pass::reset () const inline noexcept
References m_dirty.
resetTexture()
C3D_API void castor3d::Pass::resetTexture (TextureSourceInfo const & srcSourceInfo, TextureSourceInfo dstSourceInfo)
Replaces a texture source.
Parameters
[in] srcSourceInfo The original texture source.
[in] dstSourceInfo The replacement texture source.
setColour() [1/4]
void castor3d::Pass::setColour (castor::Coords3f const & v) inline
References setColour().
setColour() [2/4]
C3D_API void castor3d::Pass::setColour (castor::HdrRgbColour const & value)
Sets the basic pass colour.
Parameters
[in] value The new value.
Referenced by setColour(), setColour(), and setColour().
setColour() [3/4]
void castor3d::Pass::setColour (castor::Point3f const & v) inline
References setColour().
setColour() [4/4]
void castor3d::Pass::setColour (castor::RgbColour const & v, float gamma = 2.2f) inline
References setColour().
setId()
void castor3d::Pass::setId (uint32_t value) inline noexcept
setImplicit()
void castor3d::Pass::setImplicit (bool value = true) inline noexcept
unregisterTexture()
C3D_API void castor3d::Pass::unregisterTexture (TextureSourceInfo const & sourceInfo) noexcept
Removes a texture unit.
Parameters
[in] sourceInfo The texture source.
update()
C3D_API void castor3d::Pass::update ()
Updates the render pass, CPU wise.
updateConfig()
C3D_API void castor3d::Pass::updateConfig (TextureSourceInfo const & sourceInfo, TextureConfiguration configuration)
Updates the configuration for a texture.
Parameters
[in] sourceInfo The texture source.
[in] configuration The new texture configuration.
writeText()
C3D_API bool castor3d::Pass::writeText (castor::String const & tabs, castor::Path const & folder, castor::String const & subfolder, castor::StringStream & file) const
Writes the component content to text.
Parameters
[in] tabs The current tabulation level.
[in] folder The resources folder.
[in] subfolder The resources subfolder.
[in,out] file The output file.
Friends And Related Symbol Documentation
PassComponent
friend struct PassComponent friend
Member Data Documentation
m_dirty
std::atomic_bool castor3d::Pass::m_dirty { true } mutable protected
Referenced by reset().
onChanged
OnPassChanged castor3d::Pass::onChanged
name Signals.
The documentation for this class was generated from the following file:
Castor3D/Material/Pass/Pass.hpp