Castor3D: castor3d::TextureSourceInfo Class Reference
castor3d::TextureSourceInfo Class Reference
#include <TextureSourceInfo.hpp>
Public Member Functions
C3D_API TextureSourceInfo (SamplerRes sampler, castor::Path folder, castor::Path relative, castor::ImageLoaderConfig loadConfig={ true, true, true })
C3D_API TextureSourceInfo (SamplerRes sampler, castor::String name, castor::String type, castor::ByteArray data, castor::ImageLoaderConfig loadConfig={ true, true, true })
C3D_API TextureSourceInfo (SamplerRes sampler, RenderTargetSPtr renderTarget)
C3D_API TextureSourceInfo (SamplerRes sampler, ashes::ImageCreateInfo const &createInfo)
SamplerRes sampler () const
bool isRenderTarget () const
bool isFileImage () const
bool isBufferImage () const
bool isVulkanImage () const
RenderTargetSPtr renderTarget () const
castor::Path const & folder () const
castor::Path const & relative () const
castor::String name () const
castor::String const & type () const
castor::ByteArray const & buffer () const
bool allowCompression () const
bool generateMips () const
bool layersToTiles () const
castor::ImageLoaderConfig const & config () const
ashes::ImageCreateInfo const & createInfo () const
Constructor & Destructor Documentation
TextureSourceInfo() [1/4]
C3D_API castor3d::TextureSourceInfo::TextureSourceInfo (SamplerRes sampler, castor::Path folder, castor::Path relative, castor::ImageLoaderConfig loadConfig = { true, true, true })
TextureSourceInfo() [2/4]
C3D_API castor3d::TextureSourceInfo::TextureSourceInfo (SamplerRes sampler, castor::String name, castor::String type, castor::ByteArray data, castor::ImageLoaderConfig loadConfig = { true, true, true })
TextureSourceInfo() [3/4]
C3D_API castor3d::TextureSourceInfo::TextureSourceInfo (SamplerRes sampler, RenderTargetSPtr renderTarget)
TextureSourceInfo() [4/4]
C3D_API castor3d::TextureSourceInfo::TextureSourceInfo (SamplerRes sampler, ashes::ImageCreateInfo const & createInfo)
Member Function Documentation
allowCompression()
bool castor3d::TextureSourceInfo::allowCompression () const inline
References isBufferImage(), and isFileImage().
buffer()
castor::ByteArray const & castor3d::TextureSourceInfo::buffer () const inline
References isBufferImage().
config()
castor::ImageLoaderConfig const & castor3d::TextureSourceInfo::config () const inline
References isBufferImage(), and isFileImage().
createInfo()
ashes::ImageCreateInfo const & castor3d::TextureSourceInfo::createInfo () const inline
References isBufferImage(), isFileImage(), and isRenderTarget().
folder()
castor::Path const & castor3d::TextureSourceInfo::folder () const inline
References isFileImage().
generateMips()
bool castor3d::TextureSourceInfo::generateMips () const inline
References isBufferImage(), and isFileImage().
isBufferImage()
bool castor3d::TextureSourceInfo::isBufferImage () const inline
Referenced by allowCompression(), buffer(), config(), createInfo(), generateMips(), layersToTiles(), name(), and type().
isFileImage()
bool castor3d::TextureSourceInfo::isFileImage () const inline
Referenced by allowCompression(), config(), createInfo(), folder(), generateMips(), layersToTiles(), name(), and relative().
isRenderTarget()
bool castor3d::TextureSourceInfo::isRenderTarget () const inline
Referenced by createInfo(), and renderTarget().
isVulkanImage()
bool castor3d::TextureSourceInfo::isVulkanImage () const inline
layersToTiles()
bool castor3d::TextureSourceInfo::layersToTiles () const inline
References isBufferImage(), and isFileImage().
name()
castor::String castor3d::TextureSourceInfo::name () const inline
References isBufferImage(), isFileImage(), and relative().
relative()
castor::Path const & castor3d::TextureSourceInfo::relative () const inline
References isFileImage().
Referenced by name().
renderTarget()
RenderTargetSPtr castor3d::TextureSourceInfo::renderTarget () const inline
References isRenderTarget().
sampler()
SamplerRes castor3d::TextureSourceInfo::sampler () const inline
type()
castor::String const & castor3d::TextureSourceInfo::type () const inline
References isBufferImage().
The documentation for this class was generated from the following file:
Material/Texture/TextureSourceInfo.hpp