Castor3D: castor3d::BonesComponent Class Reference
castor3d::BonesComponent Class Reference
The submesh component used for skinning.
Public Member Functions
C3D_API BonesComponent (Submesh &submesh)
Constructor.
C3D_API ~BonesComponent ()
Destructor.
C3D_API void addBoneDatas (VertexBoneData const *const p_begin, VertexBoneData const *const p_end)
adds bone datas.
C3D_API SkeletonSPtr getSkeleton () const
C3D_API void gather (VertexBufferArray &buffers) override
Gathers buffers that need to go in a VAO.
void addBoneDatas (std::vector< VertexBoneData > const &p_boneData)
adds bone datas.
template<size_t Count>
void addBoneDatas (std::array< VertexBoneData, Count > const &p_boneData)
adds bone datas.
bool hasBoneData () const
VertexPtrArray const & getBonesData () const
VertexBuffer const & getBonesBuffer () const
VertexBuffer & getBonesBuffer ()
ProgramFlags getProgramFlags () const override
Public Member Functions inherited from castor3d::SubmeshComponent
C3D_API SubmeshComponent (Submesh &submesh, castor::String const &type)
Constructor.
virtual C3D_API ~SubmeshComponent () noexcept=default
Destructor.
C3D_API bool initialise ()
Initialises the submesh.
C3D_API void cleanup ()
Cleans the submesh.
C3D_API void fill ()
Initialises the submesh.
C3D_API void upload ()
Uploads data on VRAM.
virtual C3D_API void setMaterial (MaterialSPtr oldMaterial, MaterialSPtr newMaterial, bool update)
Sets the material.
castor::String const & getType () const
void needsUpdate ()
Sets the component to be updated.
Static Public Attributes
static C3D_API castor::String const Name
Detailed Description
The submesh component used for skinning.
Author
Sylvain DOREMUS
Date
09/11/2017
Constructor & Destructor Documentation
BonesComponent()
C3D_API castor3d::BonesComponent::BonesComponent (Submesh & submesh) explicit
Constructor.
Parameters
[in] submesh The parent submesh.
~BonesComponent()
C3D_API castor3d::BonesComponent::~BonesComponent ()
Destructor.
Member Function Documentation
addBoneDatas() [1/3]
C3D_API void castor3d::BonesComponent::addBoneDatas (VertexBoneData const *const p_begin, VertexBoneData const *const p_end)
adds bone datas.
Parameters
[in] p_begin The bones data begin.
[in] p_end The bones data end.
Referenced by addBoneDatas().
addBoneDatas() [2/3]
void castor3d::BonesComponent::addBoneDatas (std::vector< VertexBoneData > const & p_boneData) inline
adds bone datas.
Parameters
[in] p_boneData The bone datas.
References addBoneDatas().
addBoneDatas() [3/3]
template<size_t Count> void castor3d::BonesComponent::addBoneDatas (std::array< VertexBoneData, Count > const & p_boneData) inline
adds bone datas.
Parameters
[in] p_boneData The bone datas.
References addBoneDatas().
gather()
C3D_API void castor3d::BonesComponent::gather (VertexBufferArray & buffers) override virtual
Gathers buffers that need to go in a VAO.
Implements castor3d::SubmeshComponent.
getBonesBuffer() [1/2]
VertexBuffer const& castor3d::BonesComponent::getBonesBuffer () const inline
Returns
The bones VertexBuffer.
getBonesBuffer() [2/2]
VertexBuffer& castor3d::BonesComponent::getBonesBuffer () inline
Returns
The bones VertexBuffer.
getBonesData()
VertexPtrArray const& castor3d::BonesComponent::getBonesData () const inline
Returns
The bone data.
getProgramFlags()
ProgramFlags castor3d::BonesComponent::getProgramFlags () const inline override virtual
Returns
The shader program flags.
Implements castor3d::SubmeshComponent.
References castor3d::eSkinning, and hasBoneData().
getSkeleton()
C3D_API SkeletonSPtr castor3d::BonesComponent::getSkeleton () const
Returns
The skeleton.
Referenced by castor3d::BonesInstantiationComponent::getSkeleton().
hasBoneData()
bool castor3d::BonesComponent::hasBoneData () const inline
Returns
true if the submesh has bone data.
Referenced by getProgramFlags().
Member Data Documentation
Name
C3D_API castor::String const castor3d::BonesComponent::Name static
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Mesh/SubmeshComponent/BonesComponent.hpp