Castor3D: castor3d::Context Class Reference
castor3d::Context Class Reference abstract
Class which holds the rendering context.
Public Member Functions
C3D_API Context (RenderSystem &renderSystem)
Constructor.
virtual C3D_API ~Context ()
Destructor.
C3D_API bool initialise (RenderWindow *window)
Initialises this context.
C3D_API void cleanup ()
Cleans this context up.
C3D_API void setCurrent ()
Defines this context to be the current rendering context.
C3D_API void endCurrent ()
Defines this context not to be the current rendering context.
C3D_API void swapBuffers ()
Swaps render buffers.
C3D_API void memoryBarrier (MemoryBarriers const &barriers)
Raise a memory barrier.
C3D_API void renderTextureCube (castor::Position const &position, castor::Size const &size, TextureLayout const &texture)
Renders the given cube texture to the currently draw-bound frame buffer.
C3D_API void renderTextureCube (castor::Size const &size, TextureLayout const &texture, uint32_t index)
Renders the wanted layer of given cube texture array to the currently draw-bound frame buffer.
C3D_API void renderTexture (castor::Position const &position, castor::Size const &size, TextureLayout const &texture, RenderPipeline &pipeline, MatrixUbo &matrixUbo)
Renders the given 2D texture.
C3D_API void renderTexture (castor::Position const &position, castor::Size const &size, TextureLayout const &texture)
Renders the given 2D texture to the currently draw-bound frame buffer.
C3D_API void renderTextureNearest (castor::Position const &position, castor::Size const &size, TextureLayout const &texture)
Renders the given 2D texture to the currently draw-bound frame buffer.
C3D_API void renderTexture (castor::Position const &position, castor::Size const &size, TextureLayout const &texture, uint32_t index)
Renders the wanted layer of given 2D texture array to the currently draw-bound frame buffer.
C3D_API void renderDepthCube (castor::Position const &position, castor::Size const &size, TextureLayout const &texture)
Renders the given depth cube texture to the currently draw-bound frame buffer.
C3D_API void renderDepthCube (castor::Position const &position, castor::Size const &size, TextureLayout const &texture, uint32_t index)
Renders the wanted layer of given depth cube texture array to the currently draw-bound frame buffer.
C3D_API void renderDepth (castor::Position const &position, castor::Size const &size, TextureLayout const &texture)
Renders the given depth 2D texture to the currently draw-bound frame buffer.
C3D_API void renderDepth (castor::Position const &position, castor::Size const &size, TextureLayout const &texture, uint32_t index)
Renders the wanted layer of given depth 2D texture array to the currently draw-bound frame buffer.
C3D_API void renderVariance (castor::Position const &position, castor::Size const &size, TextureLayout const &texture)
Renders the given variance 2D texture to the currently draw-bound frame buffer.
C3D_API void renderVarianceCube (castor::Position const &position, castor::Size const &size, TextureLayout const &texture)
Renders the given variance cube texture to the currently draw-bound frame buffer.
void renderTexture (castor::Size const &size, TextureLayout const &texture, RenderPipeline &pipeline, MatrixUbo &matrixUbo)
Renders the given 2D texture.
void renderTexture (castor::Size const &size, TextureLayout const &texture)
Renders the given 2D texture to the currently draw-bound frame buffer.
void renderTextureNearest (castor::Size const &size, TextureLayout const &texture)
Renders the given 2D texture to the currently draw-bound frame buffer.
void renderTexture (castor::Size const &size, TextureLayout const &texture, uint32_t index)
Renders the wanted layer of given 2D texture array to the currently draw-bound frame buffer.
void renderTextureCube (castor::Size const &size, TextureLayout const &texture)
Renders the given cube texture to the currently draw-bound frame buffer.
void renderDepth (castor::Size const &size, TextureLayout const &texture)
Renders the given depth 2D texture to the currently draw-bound frame buffer.
void renderDepth (castor::Size const &size, TextureLayout const &texture, uint32_t index)
Renders the wanted layer of given depth 2D texture array to the currently draw-bound frame buffer.
void renderDepthCube (castor::Size const &size, TextureLayout const &texture)
Renders the given depth cube texture to the currently draw-bound frame buffer.
void renderDepthCube (castor::Size const &size, TextureLayout const &texture, uint32_t index)
Renders the wanted layer of given depth cube texture array to the currently draw-bound frame buffer.
void renderEquiToCube (castor::Size const &size, TextureLayout const &texture, TextureLayoutSPtr cubeTexture, FrameBufferSPtr fbo, std::array< FrameBufferAttachmentSPtr, 6 > const &attachs, HdrConfig const &hdrConfig)
Renders an equirectangular texture into a cube texture.
void renderCubeFace (castor::Size const &size, TextureLayoutSPtr texture, CubeMapFace face, RenderPipeline &pipeline, MatrixUbo &matrixUbo)
Renders the wanted face of given cube texture to the currently draw-bound frame buffer.
void renderCubeFace (castor::Size const &size, TextureLayoutSPtr texture, CubeMapFace face)
Renders the wanted face of given cube texture to the currently draw-bound frame buffer.
bool isInitialised () const
Tells the context is initialised.
RenderWindow const & getWindow () const
RenderWindow & getWindow ()
virtual C3D_API bool doInitialise ()=0
virtual C3D_API void doCleanup ()=0
Cleans this context up.
virtual C3D_API void doDestroy ()=0
Destroys the context on GPU.
virtual C3D_API void doSetCurrent ()=0
Defines this context to be the current rendering context.
virtual C3D_API void doEndCurrent ()=0
Defines this context not to be the current rendering context.
virtual C3D_API void doSwapBuffers ()=0
Swaps render buffers.
virtual C3D_API void doMemoryBarrier (MemoryBarriers const &barriers)=0
Raise a memory barrier.
Protected Attributes
RenderWindow * m_window
bool m_initialised
MatrixUbo m_matrixUbo
RenderColourToTexture m_colour
RenderColourCubeToTexture m_colourCube
RenderColourLayerToTexture m_colourLayer
RenderColourLayerCubeToTexture m_colourLayerCube
RenderDepthToTexture m_depth
RenderDepthCubeToTexture m_depthCube
RenderDepthLayerToTexture m_depthLayer
RenderDepthLayerCubeToTexture m_depthLayerCube
RenderVarianceToTexture m_variance
RenderVarianceCubeToTexture m_varianceCube
RenderColourToCube m_cube
Detailed Description
Class which holds the rendering context.
Author
Sylvain DOREMUS
Date
03/01/2011
Version
0.6.1.1
Constructor & Destructor Documentation
Context()
C3D_API castor3d::Context::Context (RenderSystem & renderSystem) explicit
Constructor.
Parameters
[in] renderSystem The RenderSystem.
~Context()
virtual C3D_API castor3d::Context::~Context () virtual
Destructor.
Member Function Documentation
cleanup()
C3D_API void castor3d::Context::cleanup ()
Cleans this context up.
doCleanup()
virtual C3D_API void castor3d::Context::doCleanup () pure virtual
Cleans this context up.
doDestroy()
virtual C3D_API void castor3d::Context::doDestroy () pure virtual
Destroys the context on GPU.
doEndCurrent()
virtual C3D_API void castor3d::Context::doEndCurrent () pure virtual
Defines this context not to be the current rendering context.
doInitialise()
virtual C3D_API bool castor3d::Context::doInitialise () pure virtual
Returns
true if initialised, false if not
doMemoryBarrier()
virtual C3D_API void castor3d::Context::doMemoryBarrier (MemoryBarriers const & barriers) pure virtual
Raise a memory barrier.
Parameters
[in] barriers The barrier to wait.
doSetCurrent()
virtual C3D_API void castor3d::Context::doSetCurrent () pure virtual
Defines this context to be the current rendering context.
doSwapBuffers()
virtual C3D_API void castor3d::Context::doSwapBuffers () pure virtual
Swaps render buffers.
endCurrent()
C3D_API void castor3d::Context::endCurrent ()
Defines this context not to be the current rendering context.
getWindow() [1/2]
RenderWindow const& castor3d::Context::getWindow () const inline
Returns
The render window.
References m_window.
getWindow() [2/2]
RenderWindow& castor3d::Context::getWindow () inline
Returns
The render window.
References m_window.
initialise()
C3D_API bool castor3d::Context::initialise (RenderWindow * window)
Initialises this context.
Parameters
[in] window The RenderWindow
Returns
true if initialised, false if not
isInitialised()
bool castor3d::Context::isInitialised () const inline
Tells the context is initialised.
References m_initialised.
memoryBarrier()
C3D_API void castor3d::Context::memoryBarrier (MemoryBarriers const & barriers)
Raise a memory barrier.
Parameters
[in] barriers The barrier to wait.
renderCubeFace() [1/2]
void castor3d::Context::renderCubeFace (castor::Size const & size, TextureLayoutSPtr texture, CubeMapFace face, RenderPipeline & pipeline, MatrixUbo & matrixUbo) inline
Renders the wanted face of given cube texture to the currently draw-bound frame buffer.
Parameters
[in] size The render viewport size.
[in] texture The texture.
[in] face The face index.
[in] pipeline The pipleline used to render the texture.
[in] matrixUbo The uniform buffer receiving matrices.
References m_colourCube, and castor3d::RenderColourCubeToTexture::renderFace().
renderCubeFace() [2/2]
void castor3d::Context::renderCubeFace (castor::Size const & size, TextureLayoutSPtr texture, CubeMapFace face) inline
Renders the wanted face of given cube texture to the currently draw-bound frame buffer.
Parameters
[in] size The render viewport size.
[in] texture The texture.
[in] face The face index.
References m_colourCube, and castor3d::RenderColourCubeToTexture::renderFace().
renderDepth() [1/4]
C3D_API void castor3d::Context::renderDepth (castor::Position const & position, castor::Size const & size, TextureLayout const & texture)
Renders the given depth 2D texture to the currently draw-bound frame buffer.
Parameters
[in] position The render viewport position.
[in] size The render viewport size.
[in] texture The texture.
Referenced by renderDepth(), and renderDepthCube().
renderDepth() [2/4]
C3D_API void castor3d::Context::renderDepth (castor::Position const & position, castor::Size const & size, TextureLayout const & texture, uint32_t index)
Renders the wanted layer of given depth 2D texture array to the currently draw-bound frame buffer.
Parameters
[in] position The render viewport position.
[in] size The render viewport size.
[in] texture The texture.
[in] index The layer index.
renderDepth() [3/4]
void castor3d::Context::renderDepth (castor::Size const & size, TextureLayout const & texture) inline
Renders the given depth 2D texture to the currently draw-bound frame buffer.
Parameters
[in] size The render viewport size.
[in] texture The texture.
References renderDepth().
renderDepth() [4/4]
void castor3d::Context::renderDepth (castor::Size const & size, TextureLayout const & texture, uint32_t index) inline
Renders the wanted layer of given depth 2D texture array to the currently draw-bound frame buffer.
Parameters
[in] size The render viewport size.
[in] texture The texture.
[in] index The layer index.
References renderDepth().
renderDepthCube() [1/4]
C3D_API void castor3d::Context::renderDepthCube (castor::Position const & position, castor::Size const & size, TextureLayout const & texture)
Renders the given depth cube texture to the currently draw-bound frame buffer.
Parameters
[in] position The render viewport position.
[in] size The render viewport size.
[in] texture The texture.
renderDepthCube() [2/4]
C3D_API void castor3d::Context::renderDepthCube (castor::Position const & position, castor::Size const & size, TextureLayout const & texture, uint32_t index)
Renders the wanted layer of given depth cube texture array to the currently draw-bound frame buffer.
Parameters
[in] position The render viewport position.
[in] size The render viewport size.
[in] texture The texture.
[in] index The layer index.
renderDepthCube() [3/4]
void castor3d::Context::renderDepthCube (castor::Size const & size, TextureLayout const & texture) inline
Renders the given depth cube texture to the currently draw-bound frame buffer.
Parameters
[in] size The render viewport size.
[in] texture The texture.
References renderDepth().
renderDepthCube() [4/4]
void castor3d::Context::renderDepthCube (castor::Size const & size, TextureLayout const & texture, uint32_t index) inline
Renders the wanted layer of given depth cube texture array to the currently draw-bound frame buffer.
Parameters
[in] size The render viewport size.
[in] texture The texture.
[in] index The layer index.
References renderDepth().
renderEquiToCube()
void castor3d::Context::renderEquiToCube (castor::Size const & size, TextureLayout const & texture, TextureLayoutSPtr cubeTexture, FrameBufferSPtr fbo, std::array< FrameBufferAttachmentSPtr, 6 > const & attachs, HdrConfig const & hdrConfig) inline
Renders an equirectangular texture into a cube texture.
Parameters
[in] size The render viewport size.
[in] texture The equirectangular texture.
[in] cubeTexture The cube texture.
[in] fbo The framebuffer used during render.
[in] attachs The framebuffer attaches for the cube texture.
[in] hdrConfig The HDR configuration.
References m_cube, and castor3d::RenderColourToCube::render().
renderTexture() [1/6]
C3D_API void castor3d::Context::renderTexture (castor::Position const & position, castor::Size const & size, TextureLayout const & texture, RenderPipeline & pipeline, MatrixUbo & matrixUbo)
Renders the given 2D texture.
Parameters
[in] position The render viewport position.
[in] size The render viewport size.
[in] texture The texture.
[in] pipeline The pipleline used to render the texture.
[in] matrixUbo The uniform buffer receiving matrices.
Referenced by renderTexture().
renderTexture() [2/6]
C3D_API void castor3d::Context::renderTexture (castor::Position const & position, castor::Size const & size, TextureLayout const & texture)
Renders the given 2D texture to the currently draw-bound frame buffer.
Parameters
[in] position The render viewport position.
[in] size The render viewport size.
[in] texture The texture.
renderTexture() [3/6]
C3D_API void castor3d::Context::renderTexture (castor::Position const & position, castor::Size const & size, TextureLayout const & texture, uint32_t index)
Renders the wanted layer of given 2D texture array to the currently draw-bound frame buffer.
Parameters
[in] position The render viewport position.
[in] size The render viewport size.
[in] texture The texture.
[in] index The layer index.
renderTexture() [4/6]
void castor3d::Context::renderTexture (castor::Size const & size, TextureLayout const & texture, RenderPipeline & pipeline, MatrixUbo & matrixUbo) inline
Renders the given 2D texture.
Parameters
[in] size The render viewport size.
[in] texture The texture.
[in] pipeline The pipleline used to render the texture.
[in] matrixUbo The uniform buffer receiving matrices.
References renderTexture().
renderTexture() [5/6]
void castor3d::Context::renderTexture (castor::Size const & size, TextureLayout const & texture) inline
Renders the given 2D texture to the currently draw-bound frame buffer.
Parameters
[in] size The render viewport size.
[in] texture The texture.
References renderTexture().
renderTexture() [6/6]
void castor3d::Context::renderTexture (castor::Size const & size, TextureLayout const & texture, uint32_t index) inline
Renders the wanted layer of given 2D texture array to the currently draw-bound frame buffer.
Parameters
[in] size The render viewport size.
[in] texture The texture.
[in] index The layer index.
References renderTexture().
renderTextureCube() [1/3]
C3D_API void castor3d::Context::renderTextureCube (castor::Position const & position, castor::Size const & size, TextureLayout const & texture)
Renders the given cube texture to the currently draw-bound frame buffer.
Parameters
[in] position The render viewport position.
[in] size The render viewport size.
[in] texture The texture.
Referenced by renderTextureCube().
renderTextureCube() [2/3]
C3D_API void castor3d::Context::renderTextureCube (castor::Size const & size, TextureLayout const & texture, uint32_t index)
Renders the wanted layer of given cube texture array to the currently draw-bound frame buffer.
Parameters
[in] size The render viewport size.
[in] texture The texture.
[in] index The layer index.
renderTextureCube() [3/3]
void castor3d::Context::renderTextureCube (castor::Size const & size, TextureLayout const & texture) inline
Renders the given cube texture to the currently draw-bound frame buffer.
Parameters
[in] size The render viewport size.
[in] texture The texture.
References renderTextureCube().
renderTextureNearest() [1/2]
C3D_API void castor3d::Context::renderTextureNearest (castor::Position const & position, castor::Size const & size, TextureLayout const & texture)
Renders the given 2D texture to the currently draw-bound frame buffer.
Parameters
[in] position The render viewport position.
[in] size The render viewport size.
[in] texture The texture.
Referenced by renderTextureNearest().
renderTextureNearest() [2/2]
void castor3d::Context::renderTextureNearest (castor::Size const & size, TextureLayout const & texture) inline
Renders the given 2D texture to the currently draw-bound frame buffer.
Parameters
[in] size The render viewport size.
[in] texture The texture.
References renderTextureNearest().
renderVariance()
C3D_API void castor3d::Context::renderVariance (castor::Position const & position, castor::Size const & size, TextureLayout const & texture)
Renders the given variance 2D texture to the currently draw-bound frame buffer.
Parameters
[in] position The render viewport position.
[in] size The render viewport size.
[in] texture The texture.
renderVarianceCube()
C3D_API void castor3d::Context::renderVarianceCube (castor::Position const & position, castor::Size const & size, TextureLayout const & texture)
Renders the given variance cube texture to the currently draw-bound frame buffer.
Parameters
[in] position The render viewport position.
[in] size The render viewport size.
[in] texture The texture.
setCurrent()
C3D_API void castor3d::Context::setCurrent ()
Defines this context to be the current rendering context.
swapBuffers()
C3D_API void castor3d::Context::swapBuffers ()
Swaps render buffers.
Member Data Documentation
m_colour
RenderColourToTexture castor3d::Context::m_colour protected
The pipeline used to render a texture in the current draw-bound framebuffer.
m_colourCube
RenderColourCubeToTexture castor3d::Context::m_colourCube protected
The pipeline used to render a texture in the current draw-bound framebuffer.
Referenced by renderCubeFace().
m_colourLayer
RenderColourLayerToTexture castor3d::Context::m_colourLayer protected
The pipeline used to render a layer from a texture array in the current draw-bound framebuffer.
m_colourLayerCube
RenderColourLayerCubeToTexture castor3d::Context::m_colourLayerCube protected
The pipeline used to render a layer from a cube texture in the current draw-bound framebuffer.
m_cube
RenderColourToCube castor3d::Context::m_cube protected
The pipeline used to render a cube texture in the current draw-bound framebuffer.
Referenced by renderEquiToCube().
m_depth
RenderDepthToTexture castor3d::Context::m_depth protected
The pipeline used to render a depth texture in the current draw-bound framebuffer.
m_depthCube
RenderDepthCubeToTexture castor3d::Context::m_depthCube protected
The pipeline used to render a cube depth texture in the current draw-bound framebuffer.
m_depthLayer
RenderDepthLayerToTexture castor3d::Context::m_depthLayer protected
The pipeline used to render a layer from a depth texture array in the current draw-bound framebuffer.
m_depthLayerCube
RenderDepthLayerCubeToTexture castor3d::Context::m_depthLayerCube protected
The pipeline used to render a layer from a cube depth texture in the current draw-bound framebuffer.
m_initialised
bool castor3d::Context::m_initialised protected
Tells if the context is initialised.
Referenced by isInitialised().
m_matrixUbo
MatrixUbo castor3d::Context::m_matrixUbo protected
The uniform buffer containing matrices data.
m_variance
RenderVarianceToTexture castor3d::Context::m_variance protected
The pipeline used to render a variance texture in the current draw-bound framebuffer.
m_varianceCube
RenderVarianceCubeToTexture castor3d::Context::m_varianceCube protected
The pipeline used to render a variance texture in the current draw-bound framebuffer.
m_window
RenderWindow* castor3d::Context::m_window protected
RenderWindow associated to this context.
Referenced by getWindow().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Render/Context.hpp