Castor3D: castor::Size Class Reference
castor::Size Class Reference
#include <Size.hpp>
Public Member Functions
CU_API Size () noexcept
Constructor.
CU_API Size (uint32_t width, uint32_t height) noexcept
Constructor.
CU_API Size (Size const &obj)
Copy Constructor.
CU_API Size (Size &&obj) noexcept
Move assignment Constructor.
CU_API ~Size () noexcept=default
Destructor.
CU_API Size & operator= (Size const &obj) noexcept
Copy assignment operator.
CU_API Size & operator= (Size &&obj) noexcept
Move assignment operator.
CU_API void set (uint32_t width, uint32_t height) noexcept
sets the size values
uint32_t getWidth () const noexcept
Retrieves the width.
uint32_t & getWidth () noexcept
Retrieves the width.
uint32_t getHeight () const noexcept
Retrieves the height.
uint32_t & getHeight () noexcept
Retrieves the height.
CU_API void grow (int32_t cx, int32_t cy) noexcept
Modifies the size.
Size & operator<<= (uint32_t rhs) noexcept
Size & operator>>= (uint32_t rhs) noexcept
auto operator-> () const noexcept
auto operator-> () noexcept
Public Member Functions inherited from castor::Coords< uint32_t, 2 >
void swap (Coords &rhs) noexcept
Swaps this pont data with the parameter ones.
uint32_t size () const
uint32_t const & operator[] (uint32_t index) const
Retrieves the data at given index.
uint32_t & operator[] (uint32_t index)
Retrieves the data at given index.
uint32_t * ptr ()
Retrieves a non constant pointer on datas.
uint32_t const * constPtr () const
Retrieves a constant pointer on datas.
iterator begin ()
Retrieves an iterator to the first element.
const_iterator begin () const
Retrieves a constant iterator to the first element.
iterator end ()
Retrieves an iterator to the last element.
const_iterator end () const
Retrieves a constant iterator to the last element.
Coords ()=default
Coords (Point< uint32_t, Count > &rhs)
Coords (uint32_t *rhs)
Coords & operator= (uint32_t *rhs)
Coords & operator= (Point< uint32_t, Count > const &rhs)
Coords & operator+= (Coords< U, UCount > const &rhs)
Coords & operator+= (Point< U, UCount > const &rhs)
Coords & operator+= (U const *coords)
Coords & operator+= (uint32_t const &coord)
Coords & operator-= (Coords< U, UCount > const &rhs)
Coords & operator-= (Point< U, UCount > const &rhs)
Coords & operator-= (U const *coords)
Coords & operator-= (uint32_t const &coord)
Coords & operator*= (Coords< U, UCount > const &rhs)
Coords & operator*= (Point< U, UCount > const &rhs)
Coords & operator*= (U const *coords)
Coords & operator*= (uint32_t const &coord)
Coords & operator/= (Coords< U, UCount > const &rhs)
Coords & operator/= (Point< U, UCount > const &rhs)
Coords & operator/= (U const *coords)
Coords & operator/= (uint32_t const &coord)
Additional Inherited Members
Public Types inherited from castor::Coords< uint32_t, 2 >
using iterator
using const_iterator
Constructor & Destructor Documentation
Size() [1/4]
CU_API castor::Size::Size () noexcept
Constructor.
Size() [2/4]
CU_API castor::Size::Size (uint32_t width, uint32_t height) noexcept
Constructor.
Parameters
[in] width,height The dimensions
Size() [3/4]
CU_API castor::Size::Size (Size const & obj)
Copy Constructor.
Parameters
[in] obj The object to copy
Size() [4/4]
CU_API castor::Size::Size (Size && obj) noexcept
Move assignment Constructor.
Parameters
[in] obj The object to move
~Size()
CU_API castor::Size::~Size () default noexcept
Destructor.
Member Function Documentation
getHeight() [1/2]
uint32_t castor::Size::getHeight () const inline noexcept
Retrieves the height.
Returns
The height
References castor::DataHolderT< SizeData >::getData(), castor::SizeData::size, and castor::SizeData::Mbr::y.
Referenced by castor3d::GBufferBase::doCreateTextures(), castor::PxBufferBase::getHeight(), and castor::PxBufferBase::getTileHeight().
getHeight() [2/2]
uint32_t & castor::Size::getHeight () inline noexcept
Retrieves the height.
Returns
The height
References castor::DataHolderT< SizeData >::getData(), castor::SizeData::size, and castor::SizeData::Mbr::y.
getWidth() [1/2]
uint32_t castor::Size::getWidth () const inline noexcept
Retrieves the width.
Returns
The width
References castor::DataHolderT< SizeData >::getData(), castor::SizeData::size, and castor::SizeData::Mbr::x.
Referenced by castor3d::GBufferBase::doCreateTextures(), castor::PxBufferBase::getTileWidth(), and castor::PxBufferBase::getWidth().
getWidth() [2/2]
uint32_t & castor::Size::getWidth () inline noexcept
Retrieves the width.
Returns
The width
References castor::DataHolderT< SizeData >::getData(), castor::SizeData::size, and castor::SizeData::Mbr::x.
grow()
CU_API void castor::Size::grow (int32_t cx, int32_t cy) noexcept
Modifies the size.
Remarks
If width+cx < 0 (or height+cy < 0) then width=0 (respectively height=0)
Parameters
[in] cx,cy The size modifications
operator->() [1/2]
auto castor::Size::operator-> () const inline noexcept
References castor::DataHolderT< SizeData >::getData(), and castor::SizeData::size.
operator->() [2/2]
auto castor::Size::operator-> () inline noexcept
References castor::DataHolderT< SizeData >::getData(), and castor::SizeData::size.
operator<<=()
Size & castor::Size::operator<<= (uint32_t rhs) inline noexcept
References castor::DataHolderT< SizeData >::getData(), castor::SizeData::size, castor::SizeData::Mbr::x, and castor::SizeData::Mbr::y.
operator=() [1/2]
CU_API Size & castor::Size::operator= (Size && obj) noexcept
Move assignment operator.
Parameters
[in] obj The object to move
Returns
A reference to this object
operator=() [2/2]
CU_API Size & castor::Size::operator= (Size const & obj) noexcept
Copy assignment operator.
Parameters
[in] obj The object to copy
Returns
A reference to this object
operator>>=()
Size & castor::Size::operator>>= (uint32_t rhs) inline noexcept
References castor::DataHolderT< SizeData >::getData(), castor::SizeData::size, castor::SizeData::Mbr::x, and castor::SizeData::Mbr::y.
set()
CU_API void castor::Size::set (uint32_t width, uint32_t height) noexcept
sets the size values
Parameters
[in] width,height The dimensions
The documentation for this class was generated from the following file:
CastorUtils/Graphics/Size.hpp