Castor3D: castor3d::FrameStyle Class Reference
castor3d::FrameStyle Class Reference
#include <StyleFrame.hpp>
Public Member Functions
FrameStyle (castor::String const &name, Scene *scene, Engine &engine, castor::String const &fontName)
FrameStyle (castor::String const &name, Engine &engine, castor::String const &fontName)
void setHeaderFont (castor::String const &value)
void setHeaderTextMaterial (MaterialObs value)
castor::String const & getHeaderFontName () const
MaterialObs getHeaderTextMaterial () const
Public Member Functions inherited from castor3d::ControlStyle
virtual C3D_API ~ControlStyle () noexcept=default
ControlStyle (ControlType type, castor::String const &name, Scene *scene, Engine &engine, MouseCursor cursor=MouseCursor::eArrow)
void setBackgroundMaterial (MaterialObs value)
void setForegroundMaterial (MaterialObs value)
void setCursor (MouseCursor value) noexcept
void setBackgroundInvisible (bool value) noexcept
void setForegroundInvisible (bool value) noexcept
bool isBackgroundInvisible () const noexcept
bool isForegroundInvisible () const noexcept
MaterialObs getBackgroundMaterial () const noexcept
MaterialObs getForegroundMaterial () const noexcept
ControlType getType () const noexcept
MouseCursor getCursor () const noexcept
Engine & getEngine () const noexcept
bool hasScene () const noexcept
Scene & getScene () const noexcept
Static Public Attributes
static ControlType constexpr Type = ControlType::eFrame
Friends
class FrameCtrl
Additional Inherited Members
Protected Member Functions inherited from castor3d::ControlStyle
MaterialObs doCreateMaterial (MaterialObs material, float offset, castor::String const &suffix)
Constructor & Destructor Documentation
FrameStyle() [1/2]
castor3d::FrameStyle::FrameStyle (castor::String const & name, Scene * scene, Engine & engine, castor::String const & fontName) inline
References castor3d::ControlStyle::setBackgroundInvisible(), and castor3d::ControlStyle::setForegroundInvisible().
FrameStyle() [2/2]
castor3d::FrameStyle::FrameStyle (castor::String const & name, Engine & engine, castor::String const & fontName) inline
Member Function Documentation
getHeaderFontName()
castor::String const & castor3d::FrameStyle::getHeaderFontName () const inline
References castor3d::StaticStyle::getFontName().
getHeaderTextMaterial()
MaterialObs castor3d::FrameStyle::getHeaderTextMaterial () const inline
References castor3d::StaticStyle::getTextMaterial().
setHeaderFont()
void castor3d::FrameStyle::setHeaderFont (castor::String const & value) inline
References castor3d::StaticStyle::setFont().
setHeaderTextMaterial()
void castor3d::FrameStyle::setHeaderTextMaterial (MaterialObs value) inline
References castor3d::StaticStyle::setTextMaterial().
Friends And Related Function Documentation
FrameCtrl
friend class FrameCtrl friend
Member Data Documentation
Type
ControlType constexpr castor3d::FrameStyle::Type = ControlType::eFrame static constexpr
The documentation for this class was generated from the following file:
Gui/Theme/StyleFrame.hpp