Castor3D: Castor3D::SamplerManager Class Reference
Castor3D::SamplerManager Class Reference
Sampler manager.
Public Member Functions
C3D_API SamplerManager (Engine &p_engine)
Constructor.
C3D_API ~SamplerManager ()
Destructor.
template<typename ... Parameters>
std::shared_ptr< Sampler > Create (Castor::String const &p_name, Parameters &&... p_params)
Creates and returns a Sampler, given a name.
Detailed Description
Sampler manager.
Author
Sylvain DOREMUS
Date
13/10/2015
Version
0.8.0
Constructor & Destructor Documentation
SamplerManager()
C3D_API Castor3D::SamplerManager::SamplerManager (Engine & p_engine)
Constructor.
Parameters
[in] p_engine The engine.
~SamplerManager()
C3D_API Castor3D::SamplerManager::~SamplerManager ()
Destructor.
Member Function Documentation
Create()
template<typename ... Parameters> std::shared_ptr< Sampler > Castor3D::SamplerManager::Create (Castor::String const & p_name, Parameters &&... p_params) inline
Creates and returns a Sampler, given a name.
Remarks
If a Sampler with the same name exists, none is created
Parameters
[in] p_name The Sampler name
[in] p_params The other constructor parameters
Returns
The created or existing Sampler
References Castor3D::RenderSystem::CreateSampler(), Castor3D::Manager< Castor::String, Sampler, Engine, ResourceManagerEngineGetter >::GetEngine(), Castor3D::Manager< Castor::String, Sampler, Engine, ResourceManagerEngineGetter >::GetObjectTypeName(), Castor3D::INFO_MANAGER_CREATED_OBJECT, Castor3D::Manager< Castor::String, Sampler, Engine, ResourceManagerEngineGetter >::m_elements, Castor3D::Manager< Castor::String, Sampler, Engine, ResourceManagerEngineGetter >::m_renderSystem, Castor3D::MakeInitialiseEvent(), Castor3D::Engine::PostEvent(), and Castor3D::WARNING_MANAGER_DUPLICATE_OBJECT.
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/SamplerManager.hpp