Castor3D: castor3d::NodesViewT< NodeT > Struct Template Reference
castor3d::NodesViewT< NodeT > Struct Template Reference
#include <PipelinesNodes.hpp>
Public Types
using RenderedNode = RenderedNodeT< NodeT >
using NodeArray = NodeArrayT< NodeT, RenderedNodeT >
Public Member Functions
RenderedNode * emplace (RenderedNode node)
void clear () noexcept
auto begin () noexcept
auto begin () const noexcept
auto end () noexcept
auto end () const noexcept
auto & front () noexcept
auto & front () const noexcept
auto size () const noexcept
auto empty () const noexcept
Static Public Attributes
static uint64_t constexpr maxNodes = 1024ULL
static uint64_t constexpr maxCount = maxNodes
Member Typedef Documentation
NodeArray
template<typename NodeT > using castor3d::NodesViewT< NodeT >::NodeArray = NodeArrayT< NodeT, RenderedNodeT >
RenderedNode
template<typename NodeT > using castor3d::NodesViewT< NodeT >::RenderedNode = RenderedNodeT< NodeT >
Member Function Documentation
begin() [1/2]
template<typename NodeT > auto castor3d::NodesViewT< NodeT >::begin () const inline noexcept
begin() [2/2]
template<typename NodeT > auto castor3d::NodesViewT< NodeT >::begin () inline noexcept
Referenced by castor3d::NodesViewT< NodeT >::end(), castor3d::NodesViewT< NodeT >::end(), castor3d::NodesViewT< NodeT >::front(), and castor3d::NodesViewT< NodeT >::front().
clear()
template<typename NodeT > void castor3d::NodesViewT< NodeT >::clear () inline noexcept
emplace()
template<typename NodeT > RenderedNode * castor3d::NodesViewT< NodeT >::emplace (RenderedNode node) inline
References castor3d::C3D_EnsureNodesCounts, CU_Assert, CU_Exception, castor3d::NodesViewT< NodeT >::maxNodes, and castor3d::NodesViewT< NodeT >::size().
empty()
template<typename NodeT > auto castor3d::NodesViewT< NodeT >::empty () const inline noexcept
References castor3d::NodesViewT< NodeT >::size().
end() [1/2]
template<typename NodeT > auto castor3d::NodesViewT< NodeT >::end () const inline noexcept
References castor3d::NodesViewT< NodeT >::begin().
end() [2/2]
template<typename NodeT > auto castor3d::NodesViewT< NodeT >::end () inline noexcept
References castor3d::NodesViewT< NodeT >::begin().
front() [1/2]
template<typename NodeT > auto & castor3d::NodesViewT< NodeT >::front () const inline noexcept
References castor3d::NodesViewT< NodeT >::begin().
front() [2/2]
template<typename NodeT > auto & castor3d::NodesViewT< NodeT >::front () inline noexcept
References castor3d::NodesViewT< NodeT >::begin().
size()
template<typename NodeT > auto castor3d::NodesViewT< NodeT >::size () const inline noexcept
Referenced by castor3d::NodesViewT< NodeT >::emplace(), and castor3d::NodesViewT< NodeT >::empty().
Member Data Documentation
maxCount
template<typename NodeT > uint64_t constexpr castor3d::NodesViewT< NodeT >::maxCount = maxNodes static constexpr
maxNodes
template<typename NodeT > uint64_t constexpr castor3d::NodesViewT< NodeT >::maxNodes = 1024ULL static constexpr
Referenced by castor3d::NodesViewT< NodeT >::emplace().
The documentation for this struct was generated from the following file:
Castor3D/Render/Node/PipelinesNodes.hpp