Castor3D: castor::Font Class Reference
castor::Font Class Reference
#include <Font.hpp>
Classes
class BinaryLoader
Font loader.
struct SFontImpl
Structure used to load glyphs on demand.
Public Member Functions
CU_DeclareVector (Glyph, Glyph)
CU_API Font (String const &name, uint32_t height)
Constructor.
CU_API Font (String const &name, uint32_t height, Path const &path)
Constructor.
virtual CU_API ~Font () noexcept=default
Destructor.
CU_API void loadGlyph (char32_t c)
Loads wanted glyph.
CU_API TextMetrics getTextMetrics (std::u32string const &v, uint32_t maxWidth, bool splitLines) const
Retrieves the metrics of given text.
bool hasGlyphAt (char32_t c) const
Tells if the font already has load ed the wanted glyph.
Glyph const & getGlyphAt (char32_t c) const
Retrieves the glyph of wanted chaaracter.
Glyph & getGlyphAt (char32_t c)
Retrieves the glyph of wanted chaaracter.
Glyph const & operator[] (char32_t c) const
Retrieves the glyph of wanted chaaracter.
Glyph & operator[] (char32_t c)
Retrieves the glyph of wanted chaaracter.
uint32_t getHeight () const noexcept
Retrieves the height of the font.
uint32_t getMaxHeight () const noexcept
Retrieves the max height of the glyphs.
Point2i getMaxRange () const noexcept
Retrieves the max height of the glyphs.
uint32_t getMaxWidth () const noexcept
Retrieves the max width of the glyphs.
void setGlyphLoader (castor::RawUniquePtr< SFontImpl > loader) noexcept
sets the glyph loader
bool hasGlyphLoader () const noexcept
Tells if the font has a glyph loader.
SFontImpl & getGlyphLoader () const noexcept
Retrieves the glyph loader.
auto begin () noexcept
Retrieves an iterator on the first glyph.
auto begin () const noexcept
Retrieves an iterator on the first glyph.
auto end () noexcept
Retrieves an iterator on the glyph array end.
auto end () const noexcept
Retrieves an iterator on the glyph array end.
void setFaceName (String name) noexcept
sets The font face name
String const & getFaceName () const noexcept
Retrieves The font face name.
Path const & getFilePath () const noexcept
Retrieves The font file path.
void initialise () const noexcept
void cleanup () const noexcept
bool isSerialisable () const noexcept
void setSerialisable (bool v) noexcept
Public Member Functions inherited from castor::NamedBaseT< T >
NamedBaseT (T name) noexcept
Constructor.
T const & getName () const noexcept
Retrieves the name.
void rename (T name) noexcept
Additional Inherited Members
Protected Attributes inherited from castor::NamedBaseT< T >
T m_name
Constructor & Destructor Documentation
Font() [1/2]
CU_API castor::Font::Font (String const & name, uint32_t height)
Constructor.
Parameters
[in] name The font name
[in] height The font char height
Font() [2/2]
CU_API castor::Font::Font (String const & name, uint32_t height, Path const & path)
Constructor.
Parameters
[in] path The font file path
[in] name The font name
[in] height The font char height
~Font()
virtual CU_API castor::Font::~Font () virtual default noexcept
Destructor.
Remarks
Virtual to enable use as ResourceT.
Member Function Documentation
begin() [1/2]
auto castor::Font::begin () const inline noexcept
Retrieves an iterator on the first glyph.
Returns
The iterator
begin() [2/2]
auto castor::Font::begin () inline noexcept
Retrieves an iterator on the first glyph.
Returns
The iterator
cleanup()
void castor::Font::cleanup () const inline noexcept
CU_DeclareVector()
castor::Font::CU_DeclareVector (Glyph , Glyph)
end() [1/2]
auto castor::Font::end () const inline noexcept
Retrieves an iterator on the glyph array end.
Returns
The iterator
end() [2/2]
auto castor::Font::end () inline noexcept
Retrieves an iterator on the glyph array end.
Returns
The iterator
getFaceName()
String const & castor::Font::getFaceName () const inline noexcept
Retrieves The font face name.
Returns
The value
getFilePath()
Path const & castor::Font::getFilePath () const inline noexcept
Retrieves The font file path.
Returns
The value.
getGlyphAt() [1/2]
Glyph & castor::Font::getGlyphAt (char32_t c) inline
Retrieves the glyph of wanted chaaracter.
Parameters
[in] c The wanted character
Returns
A reference on the glyph
getGlyphAt() [2/2]
Glyph const & castor::Font::getGlyphAt (char32_t c) const inline
Retrieves the glyph of wanted chaaracter.
Parameters
[in] c The wanted character
Returns
A constant reference on the glyph
getGlyphLoader()
SFontImpl & castor::Font::getGlyphLoader () const inline noexcept
Retrieves the glyph loader.
Returns
The loader
getHeight()
uint32_t castor::Font::getHeight () const inline noexcept
Retrieves the height of the font.
Returns
The font height
getMaxHeight()
uint32_t castor::Font::getMaxHeight () const inline noexcept
Retrieves the max height of the glyphs.
Returns
The glyphs max height
getMaxRange()
Point2i castor::Font::getMaxRange () const inline noexcept
Retrieves the max height of the glyphs.
Returns
The glyphs max height
getMaxWidth()
uint32_t castor::Font::getMaxWidth () const inline noexcept
Retrieves the max width of the glyphs.
Returns
The glyphs max width
getTextMetrics()
CU_API TextMetrics castor::Font::getTextMetrics (std::u32string const & v, uint32_t maxWidth, bool splitLines) const
Retrieves the metrics of given text.
Parameters
[in] v The text.
[in] maxWidth The maximum width if splitLines is true.
[in] splitLines true to split lines according to maxWidth.
hasGlyphAt()
bool castor::Font::hasGlyphAt (char32_t c) const inline
Tells if the font already has load ed the wanted glyph.
Parameters
[in] c The character.
Returns
false if not.
Referenced by operator[](), and operator[]().
hasGlyphLoader()
bool castor::Font::hasGlyphLoader () const inline noexcept
Tells if the font has a glyph loader.
Returns
The status
initialise()
void castor::Font::initialise () const inline noexcept
isSerialisable()
bool castor::Font::isSerialisable () const inline noexcept
loadGlyph()
CU_API void castor::Font::loadGlyph (char32_t c)
Loads wanted glyph.
Parameters
[in] c The character.
operator[]() [1/2]
Glyph & castor::Font::operator[] (char32_t c) inline
Retrieves the glyph of wanted chaaracter.
Parameters
[in] c The wanted character
Returns
A reference on the glyph
References CU_Ensure, and hasGlyphAt().
operator[]() [2/2]
Glyph const & castor::Font::operator[] (char32_t c) const inline
Retrieves the glyph of wanted chaaracter.
Parameters
[in] c The wanted character
Returns
A reference on the glyph
References CU_Ensure, and hasGlyphAt().
setFaceName()
void castor::Font::setFaceName (String name) inline noexcept
sets The font face name
Parameters
[in] name The value
setGlyphLoader()
void castor::Font::setGlyphLoader (castor::RawUniquePtr< SFontImpl > loader) inline noexcept
sets the glyph loader
Parameters
[in] loader The value
setSerialisable()
void castor::Font::setSerialisable (bool v) inline noexcept
The documentation for this class was generated from the following file:
CastorUtils/Graphics/Font.hpp