Castor3D: Castor3D::Context Class Reference
Castor3D::Context Class Reference abstract
Class which holds the rendering context.
Public Member Functions
C3D_API Context (RenderSystem &p_renderSystem)
Constructor.
virtual C3D_API ~Context ()
Destructor.
C3D_API bool Initialise (RenderWindow *p_window)
Initialises this context.
C3D_API void Cleanup ()
Cleans this context up.
C3D_API void SetCurrent ()
Defines this context to be the current rendering context.
C3D_API void EndCurrent ()
Defines this context not to be the current rendering context.
C3D_API void SwapBuffers ()
Swaps render buffers.
C3D_API void PrepareSkybox (TextureLayout const &p_texture, Castor::Size const &p_size, Skybox &p_skybox)
Prepares the skybox faces from an equirectangular HDR image.
C3D_API void RenderTextureCube (Castor::Size const &p_size, TextureLayout const &p_texture)
Renders the given cube texture to the currently draw-bound frame buffer.
C3D_API void RenderTextureCube (Castor::Size const &p_size, TextureLayout const &p_texture, uint32_t p_index)
Renders the wanted layer of given cube texture array to the currently draw-bound frame buffer.
C3D_API void RenderTexture (Castor::Position const &p_position, Castor::Size const &p_size, TextureLayout const &p_texture, RenderPipeline &p_pipeline, UniformBuffer &p_matrixUbo)
Renders the given 2D texture.
C3D_API void RenderTexture (Castor::Position const &p_position, Castor::Size const &p_size, TextureLayout const &p_texture)
Renders the given 2D texture to the currently draw-bound frame buffer.
C3D_API void RenderTexture (Castor::Position const &p_position, Castor::Size const &p_size, TextureLayout const &p_texture, uint32_t p_index)
Renders the wanted layer of given 2D texture array to the currently draw-bound frame buffer.
C3D_API void RenderDepthCube (Castor::Position const &p_position, Castor::Size const &p_size, TextureLayout const &p_texture)
Renders the given depth cube texture to the currently draw-bound frame buffer.
C3D_API void RenderDepthCube (Castor::Position const &p_position, Castor::Size const &p_size, TextureLayout const &p_texture, uint32_t p_index)
Renders the wanted layer of given depth cube texture array to the currently draw-bound frame buffer.
C3D_API void RenderDepth (Castor::Position const &p_position, Castor::Size const &p_size, TextureLayout const &p_texture)
Renders the given depth 2D texture to the currently draw-bound frame buffer.
C3D_API void RenderDepth (Castor::Position const &p_position, Castor::Size const &p_size, TextureLayout const &p_texture, uint32_t p_index)
Renders the wanted layer of given depth 2D texture array to the currently draw-bound frame buffer.
void RenderTexture (Castor::Size const &p_size, TextureLayout const &p_texture, RenderPipeline &p_pipeline, UniformBuffer &p_matrixUbo)
Renders the given 2D texture.
void RenderTexture (Castor::Size const &p_size, TextureLayout const &p_texture)
Renders the given 2D texture to the currently draw-bound frame buffer.
void RenderTexture (Castor::Size const &p_size, TextureLayout const &p_texture, uint32_t p_index)
Renders the wanted layer of given 2D texture array to the currently draw-bound frame buffer.
void RenderDepth (Castor::Size const &p_size, TextureLayout const &p_texture)
Renders the given depth 2D texture to the currently draw-bound frame buffer.
void RenderDepth (Castor::Size const &p_size, TextureLayout const &p_texture, uint32_t p_index)
Renders the wanted layer of given depth 2D texture array to the currently draw-bound frame buffer.
void RenderDepthCube (Castor::Size const &p_size, TextureLayout const &p_texture)
Renders the given depth cube texture to the currently draw-bound frame buffer.
void RenderDepthCube (Castor::Size const &p_size, TextureLayout const &p_texture, uint32_t p_index)
Renders the wanted layer of given depth cube texture array to the currently draw-bound frame buffer.
bool IsInitialised () const
Tells the context is initialised.
bool IsMultiSampling () const
Tells the context is using multisampling.
void SetMultiSampling (bool p_value)
Defines the multisampling status.
RenderWindow const & GetWindow () const
RenderWindow & GetWindow ()
Protected Member Functions
C3D_API void DoRenderTextureFace (Castor::Position const &p_position, Castor::Size const &p_size, TextureLayout const &p_texture, CubeMapFace p_face, RenderPipeline &p_pipeline, UniformBuffer &p_matrixUbo, GeometryBuffers const &p_geometryBuffers)
Renders the wanted face of given cube texture.
C3D_API void DoRenderTextureFace (Castor::Position const &p_position, Castor::Size const &p_size, TextureLayout const &p_texture, CubeMapFace p_face, RenderPipeline &p_pipeline, UniformBuffer &p_matrixUbo, GeometryBuffers const &p_geometryBuffers, uint32_t p_index)
Renders the wanted face of wanted layer of given cube texture array.
virtual C3D_API bool DoInitialise ()=0
virtual C3D_API void DoCleanup ()=0
Cleans this context up.
virtual C3D_API void DoDestroy ()=0
Destroys the context on GPU.
virtual C3D_API void DoSetCurrent ()=0
Defines this context to be the current rendering context.
virtual C3D_API void DoEndCurrent ()=0
Defines this context not to be the current rendering context.
virtual C3D_API void DoSwapBuffers ()=0
Swaps render buffers.
Protected Attributes
RenderWindow * m_window
bool m_initialised
bool m_bMultiSampling
std::array< GpuQueryUPtr, 2 > m_timerQuery
uint32_t m_queryIndex = 0
UniformBuffer m_matrixUbo
RenderColourToTexture m_colour
RenderColourCubeToTexture m_colourCube
RenderColourLayerToTexture m_colourLayer
RenderColourLayerCubeToTexture m_colourLayerCube
RenderDepthToTexture m_depth
RenderDepthCubeToTexture m_depthCube
RenderDepthLayerToTexture m_depthLayer
RenderDepthLayerCubeToTexture m_depthLayerCube
RenderColourToCube m_cube
Detailed Description
Class which holds the rendering context.
Author
Sylvain DOREMUS
Date
03/01/2011
Version
0.6.1.1
Constructor & Destructor Documentation
Context()
C3D_API Castor3D::Context::Context (RenderSystem & p_renderSystem) explicit
Constructor.
Parameters
[in] p_renderSystem The RenderSystem.
~Context()
virtual C3D_API Castor3D::Context::~Context () virtual
Destructor.
Member Function Documentation
Cleanup()
C3D_API void Castor3D::Context::Cleanup ()
Cleans this context up.
DoCleanup()
virtual C3D_API void Castor3D::Context::DoCleanup () protected pure virtual
Cleans this context up.
DoDestroy()
virtual C3D_API void Castor3D::Context::DoDestroy () protected pure virtual
Destroys the context on GPU.
DoEndCurrent()
virtual C3D_API void Castor3D::Context::DoEndCurrent () protected pure virtual
Defines this context not to be the current rendering context.
DoInitialise()
virtual C3D_API bool Castor3D::Context::DoInitialise () protected pure virtual
Returns
true if initialised, false if not
DoRenderTextureFace() [1/2]
C3D_API void Castor3D::Context::DoRenderTextureFace (Castor::Position const & p_position, Castor::Size const & p_size, TextureLayout const & p_texture, CubeMapFace p_face, RenderPipeline & p_pipeline, UniformBuffer & p_matrixUbo, GeometryBuffers const & p_geometryBuffers) protected
Renders the wanted face of given cube texture.
Parameters
[in] p_position The render viewport position.
[in] p_size The render viewport size.
[in] p_texture The texture.
[in] p_face The cube face.
[in] p_pipeline The render pipeline.
[in] p_matrixUbo The uniform buffer receiving matrices.
[in] p_geometryBuffers The geometry buffers used to render the texture.
DoRenderTextureFace() [2/2]
C3D_API void Castor3D::Context::DoRenderTextureFace (Castor::Position const & p_position, Castor::Size const & p_size, TextureLayout const & p_texture, CubeMapFace p_face, RenderPipeline & p_pipeline, UniformBuffer & p_matrixUbo, GeometryBuffers const & p_geometryBuffers, uint32_t p_index) protected
Renders the wanted face of wanted layer of given cube texture array.
Parameters
[in] p_position The render viewport position.
[in] p_size The render viewport size.
[in] p_texture The texture.
[in] p_face The cube face.
[in] p_pipeline The render pipeline.
[in] p_matrixUbo The uniform buffer receiving matrices.
[in] p_geometryBuffers The geometry buffers used to render the texture.
[in] p_index The layer index.
DoSetCurrent()
virtual C3D_API void Castor3D::Context::DoSetCurrent () protected pure virtual
Defines this context to be the current rendering context.
DoSwapBuffers()
virtual C3D_API void Castor3D::Context::DoSwapBuffers () protected pure virtual
Swaps render buffers.
EndCurrent()
C3D_API void Castor3D::Context::EndCurrent ()
Defines this context not to be the current rendering context.
GetWindow() [1/2]
RenderWindow const& Castor3D::Context::GetWindow () const inline
Returns
The render window.
References m_window.
GetWindow() [2/2]
RenderWindow& Castor3D::Context::GetWindow () inline
Returns
The render window.
References m_window.
Initialise()
C3D_API bool Castor3D::Context::Initialise (RenderWindow * p_window)
Initialises this context.
Parameters
[in] p_window The RenderWindow
Returns
true if initialised, false if not
IsInitialised()
bool Castor3D::Context::IsInitialised () const inline
Tells the context is initialised.
References m_initialised.
IsMultiSampling()
bool Castor3D::Context::IsMultiSampling () const inline
Tells the context is using multisampling.
References m_bMultiSampling.
PrepareSkybox()
C3D_API void Castor3D::Context::PrepareSkybox (TextureLayout const & p_texture, Castor::Size const & p_size, Skybox & p_skybox)
Prepares the skybox faces from an equirectangular HDR image.
Parameters
[in] p_texture The texture holding the HDR image.
[in] p_size The skybox faces dimensions.
[out] p_skybox The skybox to prepare.
RenderDepth() [1/4]
C3D_API void Castor3D::Context::RenderDepth (Castor::Position const & p_position, Castor::Size const & p_size, TextureLayout const & p_texture)
Renders the given depth 2D texture to the currently draw-bound frame buffer.
Parameters
[in] p_position The render viewport position.
[in] p_size The render viewport size.
[in] p_texture The texture.
Referenced by RenderDepth(), and RenderDepthCube().
RenderDepth() [2/4]
C3D_API void Castor3D::Context::RenderDepth (Castor::Position const & p_position, Castor::Size const & p_size, TextureLayout const & p_texture, uint32_t p_index)
Renders the wanted layer of given depth 2D texture array to the currently draw-bound frame buffer.
Parameters
[in] p_position The render viewport position.
[in] p_size The render viewport size.
[in] p_texture The texture.
[in] p_index The layer index.
RenderDepth() [3/4]
void Castor3D::Context::RenderDepth (Castor::Size const & p_size, TextureLayout const & p_texture) inline
Renders the given depth 2D texture to the currently draw-bound frame buffer.
Parameters
[in] p_size The render viewport size.
[in] p_texture The texture.
References RenderDepth().
RenderDepth() [4/4]
void Castor3D::Context::RenderDepth (Castor::Size const & p_size, TextureLayout const & p_texture, uint32_t p_index) inline
Renders the wanted layer of given depth 2D texture array to the currently draw-bound frame buffer.
Parameters
[in] p_size The render viewport size.
[in] p_texture The texture.
[in] p_index The layer index.
References RenderDepth().
RenderDepthCube() [1/4]
C3D_API void Castor3D::Context::RenderDepthCube (Castor::Position const & p_position, Castor::Size const & p_size, TextureLayout const & p_texture)
Renders the given depth cube texture to the currently draw-bound frame buffer.
Parameters
[in] p_position The render viewport position.
[in] p_size The render viewport size.
[in] p_texture The texture.
RenderDepthCube() [2/4]
C3D_API void Castor3D::Context::RenderDepthCube (Castor::Position const & p_position, Castor::Size const & p_size, TextureLayout const & p_texture, uint32_t p_index)
Renders the wanted layer of given depth cube texture array to the currently draw-bound frame buffer.
Parameters
[in] p_position The render viewport position.
[in] p_size The render viewport size.
[in] p_texture The texture.
[in] p_index The layer index.
RenderDepthCube() [3/4]
void Castor3D::Context::RenderDepthCube (Castor::Size const & p_size, TextureLayout const & p_texture) inline
Renders the given depth cube texture to the currently draw-bound frame buffer.
Parameters
[in] p_size The render viewport size.
[in] p_texture The texture.
References RenderDepth().
RenderDepthCube() [4/4]
void Castor3D::Context::RenderDepthCube (Castor::Size const & p_size, TextureLayout const & p_texture, uint32_t p_index) inline
Renders the wanted layer of given depth cube texture array to the currently draw-bound frame buffer.
Parameters
[in] p_size The render viewport size.
[in] p_texture The texture.
[in] p_index The layer index.
References RenderDepth().
RenderTexture() [1/6]
C3D_API void Castor3D::Context::RenderTexture (Castor::Position const & p_position, Castor::Size const & p_size, TextureLayout const & p_texture, RenderPipeline & p_pipeline, UniformBuffer & p_matrixUbo)
Renders the given 2D texture.
Parameters
[in] p_position The render viewport position.
[in] p_size The render viewport size.
[in] p_texture The texture.
[in] p_pipeline The pipleline used to render the texture.
[in] p_matrixUbo The uniform buffer receiving matrices.
Referenced by RenderTexture().
RenderTexture() [2/6]
C3D_API void Castor3D::Context::RenderTexture (Castor::Position const & p_position, Castor::Size const & p_size, TextureLayout const & p_texture)
Renders the given 2D texture to the currently draw-bound frame buffer.
Parameters
[in] p_position The render viewport position.
[in] p_size The render viewport size.
[in] p_texture The texture.
RenderTexture() [3/6]
C3D_API void Castor3D::Context::RenderTexture (Castor::Position const & p_position, Castor::Size const & p_size, TextureLayout const & p_texture, uint32_t p_index)
Renders the wanted layer of given 2D texture array to the currently draw-bound frame buffer.
Parameters
[in] p_position The render viewport position.
[in] p_size The render viewport size.
[in] p_texture The texture.
[in] p_index The layer index.
RenderTexture() [4/6]
void Castor3D::Context::RenderTexture (Castor::Size const & p_size, TextureLayout const & p_texture, RenderPipeline & p_pipeline, UniformBuffer & p_matrixUbo) inline
Renders the given 2D texture.
Parameters
[in] p_size The render viewport size.
[in] p_texture The texture.
[in] p_pipeline The pipleline used to render the texture.
[in] p_matrixUbo The uniform buffer receiving matrices.
References RenderTexture().
RenderTexture() [5/6]
void Castor3D::Context::RenderTexture (Castor::Size const & p_size, TextureLayout const & p_texture) inline
Renders the given 2D texture to the currently draw-bound frame buffer.
Parameters
[in] p_size The render viewport size.
[in] p_texture The texture.
References RenderTexture().
RenderTexture() [6/6]
void Castor3D::Context::RenderTexture (Castor::Size const & p_size, TextureLayout const & p_texture, uint32_t p_index) inline
Renders the wanted layer of given 2D texture array to the currently draw-bound frame buffer.
Parameters
[in] p_size The render viewport size.
[in] p_texture The texture.
[in] p_index The layer index.
References RenderTexture().
RenderTextureCube() [1/2]
C3D_API void Castor3D::Context::RenderTextureCube (Castor::Size const & p_size, TextureLayout const & p_texture)
Renders the given cube texture to the currently draw-bound frame buffer.
Parameters
[in] p_size The render viewport size.
[in] p_texture The texture.
RenderTextureCube() [2/2]
C3D_API void Castor3D::Context::RenderTextureCube (Castor::Size const & p_size, TextureLayout const & p_texture, uint32_t p_index)
Renders the wanted layer of given cube texture array to the currently draw-bound frame buffer.
Parameters
[in] p_size The render viewport size.
[in] p_texture The texture.
[in] p_index The layer index.
SetCurrent()
C3D_API void Castor3D::Context::SetCurrent ()
Defines this context to be the current rendering context.
SetMultiSampling()
void Castor3D::Context::SetMultiSampling (bool p_value) inline
Defines the multisampling status.
Parameters
[in] p_value The status
References m_bMultiSampling.
SwapBuffers()
C3D_API void Castor3D::Context::SwapBuffers ()
Swaps render buffers.
Member Data Documentation
m_bMultiSampling
bool Castor3D::Context::m_bMultiSampling protected
Tells the context is currently set to use multisampling.
Referenced by IsMultiSampling(), and SetMultiSampling().
m_colour
RenderColourToTexture Castor3D::Context::m_colour protected
The pipeline used to render a texture in the current draw-bound framebuffer.
m_colourCube
RenderColourCubeToTexture Castor3D::Context::m_colourCube protected
The pipeline used to render a texture in the current draw-bound framebuffer.
m_colourLayer
RenderColourLayerToTexture Castor3D::Context::m_colourLayer protected
The pipeline used to render a layer from a texture array in the current draw-bound framebuffer.
m_colourLayerCube
RenderColourLayerCubeToTexture Castor3D::Context::m_colourLayerCube protected
The pipeline used to render a layer from a cube texture in the current draw-bound framebuffer.
m_cube
RenderColourToCube Castor3D::Context::m_cube protected
The pipeline used to render a cube texture in the current draw-bound framebuffer.
m_depth
RenderDepthToTexture Castor3D::Context::m_depth protected
The pipeline used to render a depth texture in the current draw-bound framebuffer.
m_depthCube
RenderDepthCubeToTexture Castor3D::Context::m_depthCube protected
The pipeline used to render a cube depth texture in the current draw-bound framebuffer.
m_depthLayer
RenderDepthLayerToTexture Castor3D::Context::m_depthLayer protected
The pipeline used to render a layer from a depth texture array in the current draw-bound framebuffer.
m_depthLayerCube
RenderDepthLayerCubeToTexture Castor3D::Context::m_depthLayerCube protected
The pipeline used to render a layer from a cube depth texture in the current draw-bound framebuffer.
m_initialised
bool Castor3D::Context::m_initialised protected
Tells if the context is initialised.
Referenced by IsInitialised().
m_matrixUbo
UniformBuffer Castor3D::Context::m_matrixUbo protected
The uniform buffer containing matrices data.
m_queryIndex
uint32_t Castor3D::Context::m_queryIndex = 0 protected
The active query index.
m_timerQuery
std::array< GpuQueryUPtr, 2 > Castor3D::Context::m_timerQuery protected
The GPU time elapsed queries.
m_window
RenderWindow* Castor3D::Context::m_window protected
RenderWindow associated to this context.
Referenced by GetWindow().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Render/Context.hpp