Castor3D: castor3d::FontGlyphBuffer Class Reference
castor3d::FontGlyphBuffer Class Reference
#include <FontGlyphBuffer.hpp>
Classes
struct FontGlyphData
Public Types
using FontGlyphsData = castor::ArrayView< FontGlyphData >
Public Member Functions
C3D_API FontGlyphBuffer (Engine &engine, RenderDevice const &device, FontTexture const &texture, uint32_t count)
Constructor.
C3D_API void add (castor::Glyph const &glyph)
Adds a glyph to the buffer.
C3D_API void update (UploadData &uploader)
Updates the buffer.
C3D_API VkDescriptorSetLayoutBinding createLayoutBinding (uint32_t binding, VkShaderStageFlags stages=(VK_SHADER_STAGE_FRAGMENT_BIT|VK_SHADER_STAGE_GEOMETRY_BIT|VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT|VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT|VK_SHADER_STAGE_VERTEX_BIT)) const
Creates the descriptor set layout binding.
C3D_API ashes::WriteDescriptorSet getBinding (uint32_t binding) const
Creates the descriptor write for this buffer.
C3D_API void createBinding (ashes::DescriptorSet &descriptorSet, VkDescriptorSetLayoutBinding const &binding) const
Creates the descriptor set binding at given point.
uint8_t * getPtr ()
ashes::BufferBase const & getBuffer () const
void setMaxHeight (uint32_t value)
void setImgWidth (uint32_t value)
void setImgHeight (uint32_t value)
Static Public Attributes
static uint32_t constexpr DataSize = uint32_t(sizeof(FontGlyphData))
Member Typedef Documentation
FontGlyphsData
using castor3d::FontGlyphBuffer::FontGlyphsData = castor::ArrayView< FontGlyphData >
Constructor & Destructor Documentation
FontGlyphBuffer()
C3D_API castor3d::FontGlyphBuffer::FontGlyphBuffer (Engine & engine, RenderDevice const & device, FontTexture const & texture, uint32_t count)
Constructor.
Parameters
[in] engine The engine.
[in] device The GPU device.
[in] texture The parent font texture.
[in] count The max configurations count.
Member Function Documentation
add()
C3D_API void castor3d::FontGlyphBuffer::add (castor::Glyph const & glyph)
Adds a glyph to the buffer.
Parameters
[in] glyph The glyph.
createBinding()
C3D_API void castor3d::FontGlyphBuffer::createBinding (ashes::DescriptorSet & descriptorSet, VkDescriptorSetLayoutBinding const & binding) const
Creates the descriptor set binding at given point.
Parameters
[in] descriptorSet The descriptor set that receives the binding.
[in] binding The descriptor set layout binding.
createLayoutBinding()
C3D_API VkDescriptorSetLayoutBinding castor3d::FontGlyphBuffer::createLayoutBinding (uint32_t binding, VkShaderStageFlags stages = (VK_SHADER_STAGE_FRAGMENT_BIT|VK_SHADER_STAGE_GEOMETRY_BIT|VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT|VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT|VK_SHADER_STAGE_VERTEX_BIT)) const
Creates the descriptor set layout binding.
getBinding()
C3D_API ashes::WriteDescriptorSet castor3d::FontGlyphBuffer::getBinding (uint32_t binding) const
Creates the descriptor write for this buffer.
getBuffer()
ashes::BufferBase const & castor3d::FontGlyphBuffer::getBuffer () const inline
References castor3d::ShaderBuffer::getBuffer().
getPtr()
uint8_t * castor3d::FontGlyphBuffer::getPtr () inline
References castor3d::ShaderBuffer::getPtr().
setImgHeight()
void castor3d::FontGlyphBuffer::setImgHeight (uint32_t value) inline
References castor3d::ShaderBuffer::setFourthCount().
setImgWidth()
void castor3d::FontGlyphBuffer::setImgWidth (uint32_t value) inline
References castor3d::ShaderBuffer::setThirdCount().
setMaxHeight()
void castor3d::FontGlyphBuffer::setMaxHeight (uint32_t value) inline
References castor3d::ShaderBuffer::setSecondCount().
update()
C3D_API void castor3d::FontGlyphBuffer::update (UploadData & uploader)
Updates the buffer.
Member Data Documentation
DataSize
uint32_t constexpr castor3d::FontGlyphBuffer::DataSize = uint32_t(sizeof(FontGlyphData)) static constexpr
The documentation for this class was generated from the following file:
Castor3D/Shader/ShaderBuffers/FontGlyphBuffer.hpp