Castor3D: castor3d::ChunkParser< T > Class Template Reference
castor3d::ChunkParser< T > Class Template Reference
Chunk parser.
#include <ChunkParser.hpp>
Static Public Member Functions
static bool parse (T *values, size_t count, BinaryChunk &chunk)
Retrieves a value array from a chunk.
static bool parse (T &value, BinaryChunk &chunk)
Retrieves a value from a chunk.
Static Public Member Functions inherited from castor3d::ChunkParserBase
static bool parse (uint8_t *values, size_t size, BinaryChunk &chunk)
Retrieves a value array from a chunk.
Detailed Description
template<typename T>
class castor3d::ChunkParser< T >
Chunk parser.
Member Function Documentation
parse() [1/2]
template<typename T > static bool castor3d::ChunkParser< T >::parse (T & value, BinaryChunk & chunk) inline static
Retrieves a value from a chunk.
Parameters
[out] value Receives the parsed value
[in] chunk The chunk containing the value
Returns
false if any error occured
References castor3d::getBuffer(), castor3d::getDataSize(), castor3d::ChunkParserBase::parse(), and castor3d::prepareChunkDataT().
parse() [2/2]
template<typename T > static bool castor3d::ChunkParser< T >::parse (T * values, size_t count, BinaryChunk & chunk) inline static
Retrieves a value array from a chunk.
Parameters
[out] values Receives the parsed values
[out] count The values count
[in] chunk The chunk containing the values
Returns
false if any error occured
References castor3d::ChunkParserBase::parse(), and castor3d::prepareChunkDataT().
Referenced by castor3d::BinaryParserBase< TParsed >::doParseChunk(), castor3d::BinaryParserBase< TParsed >::doParseChunk(), castor3d::BinaryParserBase< TParsed >::doParseChunk(), castor3d::BinaryParserBase< TParsed >::doParseChunk(), and castor3d::BinaryParserBase< TParsed >::doParseChunk().
The documentation for this class was generated from the following file:
Castor3D/Binary/ChunkParser.hpp