Castor3D: castor3d::shader::PointLight Struct Reference
castor3d::shader::PointLight Struct Reference
#include <GlslLight.hpp>
Public Member Functions
PointLight (sdw::ShaderWriter &writer, ast::expr::ExprPtr expr, bool enabled)
C3D_API void getAttenuationFactor (sdw::Float const &distance, sdw::Float &attenuation) const
auto base () const
auto colour () const
auto intensity () const
auto range () const
auto shadowMapIndex () const
auto position () const
Constructor & Destructor Documentation
PointLight()
castor3d::shader::PointLight::PointLight (sdw::ShaderWriter & writer, ast::expr::ExprPtr expr, bool enabled) inline
Member Function Documentation
base()
auto castor3d::shader::PointLight::base () const inline
Referenced by colour(), castor3d::shader::computeRange(), intensity(), position(), range(), and shadowMapIndex().
colour()
auto castor3d::shader::PointLight::colour () const inline
References base().
getAttenuationFactor()
C3D_API void castor3d::shader::PointLight::getAttenuationFactor (sdw::Float const & distance, sdw::Float & attenuation) const
intensity()
auto castor3d::shader::PointLight::intensity () const inline
References base().
position()
auto castor3d::shader::PointLight::position () const inline
References base().
range()
auto castor3d::shader::PointLight::range () const inline
References base().
shadowMapIndex()
auto castor3d::shader::PointLight::shadowMapIndex () const inline
References base().
The documentation for this struct was generated from the following file:
Castor3D/Shader/Shaders/GlslLight.hpp