Castor3D: castor3d::OpaqueRendering Class Reference
castor3d::OpaqueRendering Class Reference
#include <OpaqueRendering.hpp>
Public Types
using ShadowMapArray = std::vector< ShadowMapUPtr >
Public Member Functions
C3D_API OpaqueRendering (RenderTechnique &parent, RenderDevice const &device, QueueData const &queueData, PrepassRendering const &previous, crg::FramePassArray const &previousPasses, SsaoConfig const &ssaoConfig, ProgressBar *progress, TexturePtr normal, bool deferred)
Constructor.
C3D_API ~OpaqueRendering ()
Destructor.
C3D_API void listIntermediates (std::vector< IntermediateView > &intermediates)
Lists the intermediate view used by the whole technique.
C3D_API void update (CpuUpdater &updater)
Updates the render pass, CPU wise.
C3D_API void update (GpuUpdater &updater)
Updates the render pass, GPU wise.
C3D_API void accept (RenderTechniqueVisitor &visitor)
Visitor acceptance function.
C3D_API Engine * getEngine () const
C3D_API crg::FramePass const & getLastPass () const
C3D_API Texture const & getSsaoResult () const
C3D_API Texture const & getDiffuseLightingResult () const
C3D_API Texture const & getScatteringLightingResult () const
C3D_API Texture const & getBaseColourResult () const
C3D_API bool isEnabled () const
OpaquePassResult const & getOpaqueResult () const
ashes::Buffer< uint32_t > const & getMaterialsCounts () const
ashes::Buffer< uint32_t > const & getMaterialsStarts () const
ashes::Buffer< castor::Point2ui > const & getPixelXY () const
Static Public Member Functions
static C3D_API uint32_t countInitialisationSteps ()
Member Typedef Documentation
ShadowMapArray
using castor3d::OpaqueRendering::ShadowMapArray = std::vector< ShadowMapUPtr >
Constructor & Destructor Documentation
OpaqueRendering()
C3D_API castor3d::OpaqueRendering::OpaqueRendering (RenderTechnique & parent, RenderDevice const & device, QueueData const & queueData, PrepassRendering const & previous, crg::FramePassArray const & previousPasses, SsaoConfig const & ssaoConfig, ProgressBar * progress, TexturePtr normal, bool deferred)
Constructor.
Parameters
[in] parent The parent technique.
[in] device The GPU device.
[in] queueData The queue receiving the GPU commands.
[in] previous The prepass renderer.
[in] previousPasses The passes this pass depends on.
[in] ssaoConfig The SSAO configuration.
[in] progress The optional progress bar.
[in] normal The scene normals map.
[in] deferred true to enable deferred rendering.
~OpaqueRendering()
C3D_API castor3d::OpaqueRendering::~OpaqueRendering ()
Destructor.
Member Function Documentation
accept()
C3D_API void castor3d::OpaqueRendering::accept (RenderTechniqueVisitor & visitor)
Visitor acceptance function.
Parameters
visitor The ... visitor.
countInitialisationSteps()
static C3D_API uint32_t castor3d::OpaqueRendering::countInitialisationSteps () static
Returns
The number of steps needed for initialisation, to show progression.
getBaseColourResult()
C3D_API Texture const & castor3d::OpaqueRendering::getBaseColourResult () const
getDiffuseLightingResult()
C3D_API Texture const & castor3d::OpaqueRendering::getDiffuseLightingResult () const
getEngine()
C3D_API Engine * castor3d::OpaqueRendering::getEngine () const
name Getters.
getLastPass()
C3D_API crg::FramePass const & castor3d::OpaqueRendering::getLastPass () const
getMaterialsCounts()
ashes::Buffer< uint32_t > const & castor3d::OpaqueRendering::getMaterialsCounts () const inline
Referenced by castor3d::RenderTechnique::getMaterialsCounts().
getMaterialsStarts()
ashes::Buffer< uint32_t > const & castor3d::OpaqueRendering::getMaterialsStarts () const inline
Referenced by castor3d::RenderTechnique::getMaterialsStarts().
getOpaqueResult()
OpaquePassResult const & castor3d::OpaqueRendering::getOpaqueResult () const inline
Referenced by castor3d::RenderTechnique::getOpaqueResult().
getPixelXY()
ashes::Buffer< castor::Point2ui > const & castor3d::OpaqueRendering::getPixelXY () const inline
Referenced by castor3d::RenderTechnique::getPixelXY().
getScatteringLightingResult()
C3D_API Texture const & castor3d::OpaqueRendering::getScatteringLightingResult () const
getSsaoResult()
C3D_API Texture const & castor3d::OpaqueRendering::getSsaoResult () const
isEnabled()
C3D_API bool castor3d::OpaqueRendering::isEnabled () const
listIntermediates()
C3D_API void castor3d::OpaqueRendering::listIntermediates (std::vector< IntermediateView > & intermediates)
Lists the intermediate view used by the whole technique.
Parameters
[out] intermediates Receives the intermediate views.
update() [1/2]
C3D_API void castor3d::OpaqueRendering::update (CpuUpdater & updater)
Updates the render pass, CPU wise.
Parameters
[in,out] updater The update data.
update() [2/2]
C3D_API void castor3d::OpaqueRendering::update (GpuUpdater & updater)
Updates the render pass, GPU wise.
Parameters
[in,out] updater The update data.
The documentation for this class was generated from the following file:
Render/Opaque/OpaqueRendering.hpp