Castor3D: castor3d::GpuInformations Class Reference
castor3d::GpuInformations Class Reference
#include <GpuInformations.hpp>
Public Member Functions
GpuInformations ()
Constructor.
void addFeature (GpuFeature feature)
Adds a supported feature.
void removeFeature (GpuFeature feature)
Removes a supported feature.
void updateFeature (GpuFeature feature, bool supported)
Updates the support for a feature.
bool hasFeature (GpuFeature feature) const
Tells if the feature is supported supports stereo.
bool hasStereoRendering () const
bool hasShaderStorageBuffers () const
bool hasShaderType (VkShaderStageFlagBits type) const
void useShaderType (VkShaderStageFlagBits type, bool value)
Defines the support for given shader type.
uint32_t getValue (GpuMin index) const
void setValue (GpuMin index, uint32_t value)
uint32_t getValue (GpuMax index) const
void setValue (GpuMax index, uint32_t value)
uint32_t getTotalMemorySize () const
void setTotalMemorySize (uint32_t value)
castor::String const & getVendor () const
void setVendor (castor::String const &value)
castor::String const & getRenderer () const
void setRenderer (castor::String const &value)
castor::String const & getVersion () const
void setVersion (castor::String const &value)
Friends
class Context
Constructor & Destructor Documentation
GpuInformations()
castor3d::GpuInformations::GpuInformations () inline
Constructor.
Member Function Documentation
addFeature()
void castor3d::GpuInformations::addFeature (GpuFeature feature) inline
Adds a supported feature.
Referenced by updateFeature().
getRenderer()
castor::String const & castor3d::GpuInformations::getRenderer () const inline
Returns
The GPU platform.
getTotalMemorySize()
uint32_t castor3d::GpuInformations::getTotalMemorySize () const inline
Returns
The total VRAM size.
getValue() [1/2]
uint32_t castor3d::GpuInformations::getValue (GpuMax index) const inline
Parameters
[in] index The index.
Returns
The maximum value for given index.
getValue() [2/2]
uint32_t castor3d::GpuInformations::getValue (GpuMin index) const inline
Parameters
[in] index The index.
Returns
The minimum value for given index.
Referenced by castor3d::RenderSystem::getValue().
getVendor()
castor::String const & castor3d::GpuInformations::getVendor () const inline
Returns
The GPU vendor name.
getVersion()
castor::String const & castor3d::GpuInformations::getVersion () const inline
Returns
The rendering API version.
hasFeature()
bool castor3d::GpuInformations::hasFeature (GpuFeature feature) const inline
Tells if the feature is supported supports stereo.
References castor3d::checkFlag().
Referenced by castor3d::RenderSystem::hasFeature(), hasShaderStorageBuffers(), and hasStereoRendering().
hasShaderStorageBuffers()
bool castor3d::GpuInformations::hasShaderStorageBuffers () const inline
Returns
The SSBO support status.
References castor3d::eShaderStorageBuffers, and hasFeature().
Referenced by castor3d::RenderSystem::hasShaderStorageBuffers().
hasShaderType()
bool castor3d::GpuInformations::hasShaderType (VkShaderStageFlagBits type) const inline
Parameters
[in] type The shader type.
Returns
The shader type support status.
Referenced by castor3d::RenderSystem::hasShaderType().
hasStereoRendering()
bool castor3d::GpuInformations::hasStereoRendering () const inline
Returns
The stereo support status.
References castor3d::eStereoRendering, and hasFeature().
Referenced by castor3d::RenderSystem::hasStereoRendering().
removeFeature()
void castor3d::GpuInformations::removeFeature (GpuFeature feature) inline
Removes a supported feature.
Referenced by updateFeature().
setRenderer()
void castor3d::GpuInformations::setRenderer (castor::String const & value) inline
Parameters
[in] value The GPU platform.
setTotalMemorySize()
void castor3d::GpuInformations::setTotalMemorySize (uint32_t value) inline
Parameters
[in] value The total VRAM size.
setValue() [1/2]
void castor3d::GpuInformations::setValue (GpuMax index, uint32_t value) inline
Parameters
[in] index The index.
[in] value The maximum value for given index.
setValue() [2/2]
void castor3d::GpuInformations::setValue (GpuMin index, uint32_t value) inline
Parameters
[in] index The index.
[in] value The minimum value for given index.
setVendor()
void castor3d::GpuInformations::setVendor (castor::String const & value) inline
Parameters
[in] value The GPU vendor name.
setVersion()
void castor3d::GpuInformations::setVersion (castor::String const & value) inline
Parameters
[in] value The rendering API version.
updateFeature()
void castor3d::GpuInformations::updateFeature (GpuFeature feature, bool supported) inline
Updates the support for a feature.
References addFeature(), and removeFeature().
useShaderType()
void castor3d::GpuInformations::useShaderType (VkShaderStageFlagBits type, bool value) inline
Defines the support for given shader type.
Parameters
[in] type The shader type.
[in] value The new value.
Friends And Related Function Documentation
Context
friend class Context friend
The documentation for this class was generated from the following file:
Miscellaneous/GpuInformations.hpp