Castor3D: castor::ResourceCacheBaseT< ResT, KeyT, TraitsT > Class Template Reference
castor::ResourceCacheBaseT< ResT, KeyT, TraitsT > Class Template Reference
Base class for an element cache.
#include <ResourceCacheBase.hpp>
Public Types
using ElementT = ResT
using ElementKeyT = KeyT
using ElementCacheTraitsT = TraitsT
using ElementCacheBaseT = ResourceCacheBaseT< ElementT, ElementKeyT, ElementCacheTraitsT >
using ElementCacheT = typename ElementCacheTraitsT::ElementCacheT
using ElementPtrT = typename ElementCacheTraitsT::ElementPtrT
using ElementObsT = typename ElementCacheTraitsT::ElementObsT
using ElementContT = typename ElementCacheTraitsT::ElementContT
using ElementInitialiserT = typename ElementCacheTraitsT::ElementInitialiserT
using ElementCleanerT = typename ElementCacheTraitsT::ElementCleanerT
using ElementMergerT = typename ElementCacheTraitsT::ElementMergerT
Public Member Functions
ResourceCacheBaseT (ResourceCacheBaseT const &)=delete
ResourceCacheBaseT & operator= (ResourceCacheBaseT const &)=delete
ResourceCacheBaseT (ResourceCacheBaseT &&) noexcept=delete
ResourceCacheBaseT & operator= (ResourceCacheBaseT &&) noexcept=delete
void cleanup () noexcept
Sets all the elements to be cleaned up.
void clear () noexcept
Flushes the collection.
template<typename ... ParametersT>
ElementPtrT create (ElementKeyT const &name, ParametersT &&... parameters) const
Creates an element.
ElementObsT tryAdd (ElementKeyT const &name, ElementPtrT &element, bool initialise=false)
Adds an element.
ElementObsT tryAddNoLock (ElementKeyT const &name, ElementPtrT &element, bool initialise=false)
Adds an element.
ElementObsT add (ElementKeyT const &name, ElementPtrT &element, bool initialise=true)
Logging version of tryAdd.
ElementObsT addNoLock (ElementKeyT const &name, ElementPtrT &element, bool initialise=true)
Logging version of tryAdd.
template<typename ... ParametersT>
ElementObsT tryAdd (ElementKeyT const &name, bool initialise, ElementObsT &created, ParametersT &&... parameters)
Add an element, constructed in-place.
template<typename ... ParametersT>
ElementObsT tryAddNoLock (ElementKeyT const &name, bool initialise, ElementObsT &created, ParametersT &&... parameters)
Add an element, constructed in-place.
template<typename ... ParametersT>
ElementObsT add (ElementKeyT const &name, ParametersT &&... parameters)
Logging version of tryAdd.
template<typename ... ParametersT>
ElementObsT addNoLock (ElementKeyT const &name, ParametersT &&... parameters)
Logging version of tryAdd.
ElementPtrT tryRemove (ElementKeyT const &name, bool cleanup=false) noexcept
Removes an element, given a name.
ElementPtrT tryRemoveNoLock (ElementKeyT const &name, bool cleanup=false) noexcept
Removes an element, given a name.
ElementPtrT remove (ElementKeyT const &name, bool cleanup=false) noexcept
Logging version of tryRemove.
ElementPtrT removeNoLock (ElementKeyT const &name, bool cleanup=false) noexcept
Logging version of tryRemove.
void rename (ElementKeyT const &oldName, ElementKeyT const &newName)
Renames a resource.
ElementObsT tryFind (ElementKeyT const &name) const noexcept
Looks for an element with given name.
ElementObsT tryFindNoLock (ElementKeyT const &name) const noexcept
Looks for an element with given name.
ElementObsT find (ElementKeyT const &name) const
Logging version of tryRemove.
ElementObsT findNoLock (ElementKeyT const &name) const
Logging version of tryRemove.
void mergeInto (ElementCacheBaseT &destination)
Merges this cache's elements to the one given.
Locked loop.
template<typename FuncType >
void forEach (FuncType func) const
template<typename FuncType >
void forEach (FuncType func)
Getters.
uint32_t getObjectCount () const noexcept
uint32_t getObjectCountNoLock () const noexcept
String const & getObjectTypeName () const noexcept
bool has (ElementKeyT const &name) const noexcept
bool hasNoLock (ElementKeyT const &name) const noexcept
bool isEmpty () const noexcept
bool isEmptyNoLock () const noexcept
Mutex locking.
void lock () const
void unlock () const noexcept
Iteration.
auto begin () noexcept
auto begin () const noexcept
auto end () noexcept
auto end () const noexcept
Logging.
void reportCreation (String const &name) const
void reportAdded (String const &name) const
void reportDuplicate (String const &name) const
void reportNull () const
void reportUnknown (String const &name) const
Protected Types
using MutexT = castor::RecursiveMutex
Protected Member Functions
void doCleanupNoLock () const noexcept
void doClearNoLock () noexcept
template<typename ... ParametersT>
ElementPtrT doCreateT (ElementKeyT const &name, ParametersT &&... parameters) const
ElementObsT doTryAddNoLock (ElementKeyT const &name, ElementPtrT &element, bool initialise=true)
ElementObsT doAddNoLock (ElementKeyT const &name, ElementPtrT &element, bool initialise=true)
template<typename ... ParametersT>
ElementObsT doTryAddNoLockT (ElementKeyT const &name, bool initialise, ElementObsT &created, ParametersT &&... parameters)
template<typename ... ParametersT>
ElementObsT doAddNoLockT (ElementKeyT const &name, ParametersT &&... parameters)
ElementPtrT doTryRemoveNoLock (ElementKeyT const &name, bool cleanup=false) noexcept
ElementObsT doTryFindNoLock (ElementKeyT const &name) const noexcept
ResourceCacheBaseT (LoggerInstance &logger, ElementInitialiserT initialise=ElementInitialiserT{}, ElementCleanerT clean=ElementCleanerT{}, ElementMergerT merge=ElementMergerT{})
virtual ~ResourceCacheBaseT () noexcept=default
Protected Attributes
LoggerInstance & m_logger
CheckedMutexT< MutexT > m_mutex
ElementContT m_resources
ElementInitialiserT m_initialise
ElementCleanerT m_clean
ElementMergerT m_merge
Detailed Description
template<typename ResT, typename KeyT, typename TraitsT>
class castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >
Base class for an element cache.
Member Typedef Documentation
ElementCacheBaseT
template<typename ResT , typename KeyT , typename TraitsT > using castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::ElementCacheBaseT = ResourceCacheBaseT< ElementT, ElementKeyT, ElementCacheTraitsT >
ElementCacheT
template<typename ResT , typename KeyT , typename TraitsT > using castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::ElementCacheT = typename ElementCacheTraitsT::ElementCacheT
ElementCacheTraitsT
template<typename ResT , typename KeyT , typename TraitsT > using castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::ElementCacheTraitsT = TraitsT
ElementCleanerT
template<typename ResT , typename KeyT , typename TraitsT > using castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::ElementCleanerT = typename ElementCacheTraitsT::ElementCleanerT
ElementContT
template<typename ResT , typename KeyT , typename TraitsT > using castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::ElementContT = typename ElementCacheTraitsT::ElementContT
ElementInitialiserT
template<typename ResT , typename KeyT , typename TraitsT > using castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::ElementInitialiserT = typename ElementCacheTraitsT::ElementInitialiserT
ElementKeyT
template<typename ResT , typename KeyT , typename TraitsT > using castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::ElementKeyT = KeyT
ElementMergerT
template<typename ResT , typename KeyT , typename TraitsT > using castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::ElementMergerT = typename ElementCacheTraitsT::ElementMergerT
ElementObsT
template<typename ResT , typename KeyT , typename TraitsT > using castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::ElementObsT = typename ElementCacheTraitsT::ElementObsT
ElementPtrT
template<typename ResT , typename KeyT , typename TraitsT > using castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::ElementPtrT = typename ElementCacheTraitsT::ElementPtrT
ElementT
template<typename ResT , typename KeyT , typename TraitsT > using castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::ElementT = ResT
MutexT
template<typename ResT , typename KeyT , typename TraitsT > using castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::MutexT = castor::RecursiveMutex protected
Constructor & Destructor Documentation
ResourceCacheBaseT() [1/3]
template<typename ResT , typename KeyT , typename TraitsT > castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::ResourceCacheBaseT (ResourceCacheBaseT< ResT, KeyT, TraitsT > const &) delete
ResourceCacheBaseT() [2/3]
template<typename ResT , typename KeyT , typename TraitsT > castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::ResourceCacheBaseT (ResourceCacheBaseT< ResT, KeyT, TraitsT > &&) delete noexcept
ResourceCacheBaseT() [3/3]
template<typename ResT , typename KeyT , typename TraitsT > castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::ResourceCacheBaseT (LoggerInstance & logger, ElementInitialiserT initialise = ElementInitialiserT{}, ElementCleanerT clean = ElementCleanerT{}, ElementMergerT merge = ElementMergerT{}) inline explicit protected
name Construction/Desctruction.
~ResourceCacheBaseT()
template<typename ResT , typename KeyT , typename TraitsT > virtual castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::~ResourceCacheBaseT () protected virtual default noexcept
Member Function Documentation
add() [1/2]
template<typename ResT , typename KeyT , typename TraitsT > ElementObsT castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::add (ElementKeyT const & name, ElementPtrT & element, bool initialise = true) inline
Logging version of tryAdd.
Parameters
[in] name The resource name.
[in,out] element The resource, will be emptied on add (the cache now owns it).
[in] initialise true to initialise the added element (no effect on duplicates).
Returns
The real element (added or duplicate original).
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doAddNoLock(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::lock(), and castor::makeUniqueLock().
Referenced by castor3d::Engine::addFont(), castor3d::Engine::addImage(), castor3d::Engine::addNewFont(), and castor3d::Engine::addNewImage().
add() [2/2]
template<typename ResT , typename KeyT , typename TraitsT > template<typename ... ParametersT> ElementObsT castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::add (ElementKeyT const & name, ParametersT &&... parameters) inline
Logging version of tryAdd.
Parameters
[in] name The element name.
[in] parameters The other constructor parameters.
Returns
The real element (added or duplicate original).
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doAddNoLockT(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::lock(), and castor::makeUniqueLock().
addNoLock() [1/2]
template<typename ResT , typename KeyT , typename TraitsT > ElementObsT castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::addNoLock (ElementKeyT const & name, ElementPtrT & element, bool initialise = true) inline
Logging version of tryAdd.
Parameters
[in] name The resource name.
[in,out] element The resource, will be emptied on add (the cache now owns it).
[in] initialise true to initialise the added element (no effect on duplicates).
Returns
The real element (added or duplicate original).
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doAddNoLock().
addNoLock() [2/2]
template<typename ResT , typename KeyT , typename TraitsT > template<typename ... ParametersT> ElementObsT castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::addNoLock (ElementKeyT const & name, ParametersT &&... parameters) inline
Logging version of tryAdd.
Parameters
[in] name The element name.
[in] parameters The other constructor parameters.
Returns
The real element (added or duplicate original).
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doAddNoLockT().
begin() [1/2]
template<typename ResT , typename KeyT , typename TraitsT > auto castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::begin () const inline noexcept
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_resources.
begin() [2/2]
template<typename ResT , typename KeyT , typename TraitsT > auto castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::begin () inline noexcept
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_resources.
cleanup()
template<typename ResT , typename KeyT , typename TraitsT > void castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::cleanup () inline noexcept
Sets all the elements to be cleaned up.
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doCleanupNoLock(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::lock(), and castor::makeUniqueLock().
Referenced by castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doTryRemoveNoLock(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::remove(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::removeNoLock(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::tryRemove(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::tryRemoveNoLock().
clear()
template<typename ResT , typename KeyT , typename TraitsT > void castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::clear () inline noexcept
Flushes the collection.
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doClearNoLock(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::lock(), and castor::makeUniqueLock().
create()
template<typename ResT , typename KeyT , typename TraitsT > template<typename ... ParametersT> ElementPtrT castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::create (ElementKeyT const & name, ParametersT &&... parameters) const inline
Creates an element.
Parameters
[in] name The element name.
[in] parameters The other constructor parameters.
Returns
The created element.
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doCreateT(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportCreation().
Referenced by castor3d::Engine::createFont(), and castor3d::Engine::createImage().
doAddNoLock()
template<typename ResT , typename KeyT , typename TraitsT > ElementObsT castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doAddNoLock (ElementKeyT const & name, ElementPtrT & element, bool initialise = true) inline protected
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doTryAddNoLock(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportAdded(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportDuplicate(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportNull().
Referenced by castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::add(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::addNoLock().
doAddNoLockT()
template<typename ResT , typename KeyT , typename TraitsT > template<typename ... ParametersT> ElementObsT castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doAddNoLockT (ElementKeyT const & name, ParametersT &&... parameters) inline protected
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doTryAddNoLockT(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportCreation(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportDuplicate().
Referenced by castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::add(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::addNoLock().
doCleanupNoLock()
template<typename ResT , typename KeyT , typename TraitsT > void castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doCleanupNoLock () const inline protected noexcept
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_clean, and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_resources.
Referenced by castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::cleanup().
doClearNoLock()
template<typename ResT , typename KeyT , typename TraitsT > void castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doClearNoLock () inline protected noexcept
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_resources.
Referenced by castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::clear(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::mergeInto().
doCreateT()
template<typename ResT , typename KeyT , typename TraitsT > template<typename ... ParametersT> ElementPtrT castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doCreateT (ElementKeyT const & name, ParametersT &&... parameters) const inline protected
Referenced by castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::create(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doTryAddNoLockT().
doTryAddNoLock()
template<typename ResT , typename KeyT , typename TraitsT > ElementObsT castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doTryAddNoLock (ElementKeyT const & name, ElementPtrT & element, bool initialise = true) inline protected
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_initialise, and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_resources.
Referenced by castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doAddNoLock(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::tryAdd(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::tryAddNoLock().
doTryAddNoLockT()
template<typename ResT , typename KeyT , typename TraitsT > template<typename ... ParametersT> ElementObsT castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doTryAddNoLockT (ElementKeyT const & name, bool initialise, ElementObsT & created, ParametersT &&... parameters) inline protected
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doCreateT(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_initialise, and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_resources.
Referenced by castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doAddNoLockT(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::tryAdd(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::tryAddNoLock().
doTryFindNoLock()
template<typename ResT , typename KeyT , typename TraitsT > ElementObsT castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doTryFindNoLock (ElementKeyT const & name) const inline protected noexcept
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_resources.
Referenced by castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::find(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::findNoLock(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::tryFind(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::tryFindNoLock().
doTryRemoveNoLock()
template<typename ResT , typename KeyT , typename TraitsT > ElementPtrT castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doTryRemoveNoLock (ElementKeyT const & name, bool cleanup = false) inline protected noexcept
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::cleanup(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_clean, and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_resources.
Referenced by castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::remove(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::removeNoLock(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::tryRemove(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::tryRemoveNoLock().
end() [1/2]
template<typename ResT , typename KeyT , typename TraitsT > auto castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::end () const inline noexcept
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_resources.
end() [2/2]
template<typename ResT , typename KeyT , typename TraitsT > auto castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::end () inline noexcept
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_resources.
find()
template<typename ResT , typename KeyT , typename TraitsT > ElementObsT castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::find (ElementKeyT const & name) const inline
Logging version of tryRemove.
Parameters
[in] name The object name.
Returns
The found element, nullptr if not found.
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doTryFindNoLock(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::lock(), castor::makeUniqueLock(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportUnknown().
Referenced by castor3d::Engine::findFont(), and castor3d::Engine::findImage().
findNoLock()
template<typename ResT , typename KeyT , typename TraitsT > ElementObsT castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::findNoLock (ElementKeyT const & name) const inline
Logging version of tryRemove.
Parameters
[in] name The object name.
Returns
The found element, nullptr if not found.
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doTryFindNoLock(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportUnknown().
forEach() [1/2]
template<typename ResT , typename KeyT , typename TraitsT > template<typename FuncType > void castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::forEach (FuncType func) inline
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::lock(), and castor::makeUniqueLock().
forEach() [2/2]
template<typename ResT , typename KeyT , typename TraitsT > template<typename FuncType > void castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::forEach (FuncType func) const inline
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::lock(), and castor::makeUniqueLock().
getObjectCount()
template<typename ResT , typename KeyT , typename TraitsT > uint32_t castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::getObjectCount () const inline noexcept
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::lock(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_resources, and castor::makeUniqueLock().
getObjectCountNoLock()
template<typename ResT , typename KeyT , typename TraitsT > uint32_t castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::getObjectCountNoLock () const inline noexcept
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_resources.
getObjectTypeName()
template<typename ResT , typename KeyT , typename TraitsT > String const & castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::getObjectTypeName () const inline noexcept
Referenced by castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportAdded(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportCreation(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportDuplicate(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportNull(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportUnknown().
has()
template<typename ResT , typename KeyT , typename TraitsT > bool castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::has (ElementKeyT const & name) const inline noexcept
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::tryFind().
Referenced by castor3d::Engine::hasFont(), and castor3d::Engine::hasImage().
hasNoLock()
template<typename ResT , typename KeyT , typename TraitsT > bool castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::hasNoLock (ElementKeyT const & name) const inline noexcept
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::tryFindNoLock().
isEmpty()
template<typename ResT , typename KeyT , typename TraitsT > bool castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::isEmpty () const inline noexcept
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::lock(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_resources, and castor::makeUniqueLock().
isEmptyNoLock()
template<typename ResT , typename KeyT , typename TraitsT > bool castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::isEmptyNoLock () const inline noexcept
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_resources.
lock()
template<typename ResT , typename KeyT , typename TraitsT > void castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::lock () const inline
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_mutex.
Referenced by castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::add(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::add(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::cleanup(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::clear(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::find(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::forEach(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::forEach(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::getObjectCount(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::isEmpty(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::mergeInto(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::remove(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::rename(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::tryAdd(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::tryAdd(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::tryFind(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::tryRemove().
mergeInto()
template<typename ResT , typename KeyT , typename TraitsT > void castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::mergeInto (ElementCacheBaseT & destination) inline
Merges this cache's elements to the one given.
Parameters
[out] destination The destination cache.
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doClearNoLock(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::lock(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_merge, and castor::makeUniqueLock().
operator=() [1/2]
template<typename ResT , typename KeyT , typename TraitsT > ResourceCacheBaseT & castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::operator= (ResourceCacheBaseT< ResT, KeyT, TraitsT > &&) delete noexcept
operator=() [2/2]
template<typename ResT , typename KeyT , typename TraitsT > ResourceCacheBaseT & castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::operator= (ResourceCacheBaseT< ResT, KeyT, TraitsT > const &) delete
remove()
template<typename ResT , typename KeyT , typename TraitsT > ElementPtrT castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::remove (ElementKeyT const & name, bool cleanup = false) inline noexcept
Logging version of tryRemove.
Parameters
[in] name The element name.
[in] cleanup true if the element needs to be cleaned up.
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::cleanup(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doTryRemoveNoLock(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::lock(), castor::makeUniqueLock(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportUnknown().
Referenced by castor3d::Engine::removeFont(), and castor3d::Engine::removeImage().
removeNoLock()
template<typename ResT , typename KeyT , typename TraitsT > ElementPtrT castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::removeNoLock (ElementKeyT const & name, bool cleanup = false) inline noexcept
Logging version of tryRemove.
Parameters
[in] name The element name.
[in] cleanup true if the element needs to be cleaned up.
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::cleanup(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doTryRemoveNoLock(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportUnknown().
rename()
template<typename ResT , typename KeyT , typename TraitsT > void castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::rename (ElementKeyT const & oldName, ElementKeyT const & newName) inline
Renames a resource.
Parameters
[in] oldName The current element name.
[in] newName The new element name.
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::lock(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_resources, castor::makeUniqueLock(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportDuplicate(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportUnknown().
reportAdded()
template<typename ResT , typename KeyT , typename TraitsT > void castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportAdded (String const & name) const inline
References cuT, castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::getObjectTypeName(), castor::LoggerInstance::logTrace(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_logger, and castor::makeStringStream().
Referenced by castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doAddNoLock().
reportCreation()
template<typename ResT , typename KeyT , typename TraitsT > void castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportCreation (String const & name) const inline
References cuT, castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::getObjectTypeName(), castor::LoggerInstance::logTrace(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_logger, and castor::makeStringStream().
Referenced by castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::create(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doAddNoLockT().
reportDuplicate()
template<typename ResT , typename KeyT , typename TraitsT > void castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportDuplicate (String const & name) const inline
References cuT, castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::getObjectTypeName(), castor::LoggerInstance::logWarning(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_logger, and castor::makeStringStream().
Referenced by castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doAddNoLock(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doAddNoLockT(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::rename().
reportNull()
template<typename ResT , typename KeyT , typename TraitsT > void castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportNull () const inline
References cuT, castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::getObjectTypeName(), castor::LoggerInstance::logWarning(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_logger, and castor::makeStringStream().
Referenced by castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doAddNoLock().
reportUnknown()
template<typename ResT , typename KeyT , typename TraitsT > void castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportUnknown (String const & name) const inline
References cuT, castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::getObjectTypeName(), castor::LoggerInstance::logWarning(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_logger, and castor::makeStringStream().
Referenced by castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::find(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::findNoLock(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::remove(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::removeNoLock(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::rename().
tryAdd() [1/2]
template<typename ResT , typename KeyT , typename TraitsT > template<typename ... ParametersT> ElementObsT castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::tryAdd (ElementKeyT const & name, bool initialise, ElementObsT & created, ParametersT &&... parameters) inline
Add an element, constructed in-place.
Parameters
[in] name The element name.
[in] initialise true to initialise the added element (no effect on duplicates).
[out] created The created element.
[in] parameters The other constructor parameters.
Returns
The real element (added or duplicate original).
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doTryAddNoLockT(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::lock(), and castor::makeUniqueLock().
tryAdd() [2/2]
template<typename ResT , typename KeyT , typename TraitsT > ElementObsT castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::tryAdd (ElementKeyT const & name, ElementPtrT & element, bool initialise = false) inline
Adds an element.
Parameters
[in] name The element name.
[in,out] element The resource, will be emptied on add (the cache now owns it).
[in] initialise true to initialise the added element (no effect on duplicates).
Returns
The real element (added or duplicate original).
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doTryAddNoLock(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::lock(), and castor::makeUniqueLock().
Referenced by castor3d::Engine::tryAddImage().
tryAddNoLock() [1/2]
template<typename ResT , typename KeyT , typename TraitsT > template<typename ... ParametersT> ElementObsT castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::tryAddNoLock (ElementKeyT const & name, bool initialise, ElementObsT & created, ParametersT &&... parameters) inline
Add an element, constructed in-place.
Parameters
[in] name The element name.
[in] initialise true to initialise the added element (no effect on duplicates).
[out] created The created element.
[in] parameters The other constructor parameters.
Returns
The real element (added or duplicate original).
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doTryAddNoLockT().
tryAddNoLock() [2/2]
template<typename ResT , typename KeyT , typename TraitsT > ElementObsT castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::tryAddNoLock (ElementKeyT const & name, ElementPtrT & element, bool initialise = false) inline
Adds an element.
Parameters
[in] name The element name.
[in,out] element The resource, will be emptied on add (the cache now owns it).
[in] initialise true to initialise the added element (no effect on duplicates).
Returns
The real element (added or duplicate original).
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doTryAddNoLock().
tryFind()
template<typename ResT , typename KeyT , typename TraitsT > ElementObsT castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::tryFind (ElementKeyT const & name) const inline noexcept
Looks for an element with given name.
Parameters
[in] name The object name.
Returns
The found element, nullptr if not found.
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doTryFindNoLock(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::lock(), and castor::makeUniqueLock().
Referenced by castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::has(), castor3d::Engine::tryFindFont(), and castor3d::Engine::tryFindImage().
tryFindNoLock()
template<typename ResT , typename KeyT , typename TraitsT > ElementObsT castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::tryFindNoLock (ElementKeyT const & name) const inline noexcept
Looks for an element with given name.
Parameters
[in] name The object name.
Returns
The found element, nullptr if not found.
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doTryFindNoLock().
Referenced by castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::hasNoLock().
tryRemove()
template<typename ResT , typename KeyT , typename TraitsT > ElementPtrT castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::tryRemove (ElementKeyT const & name, bool cleanup = false) inline noexcept
Removes an element, given a name.
Parameters
[in] name The element name.
[in] cleanup true if the element needs to be cleaned up.
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::cleanup(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doTryRemoveNoLock(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::lock(), and castor::makeUniqueLock().
tryRemoveNoLock()
template<typename ResT , typename KeyT , typename TraitsT > ElementPtrT castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::tryRemoveNoLock (ElementKeyT const & name, bool cleanup = false) inline noexcept
Removes an element, given a name.
Parameters
[in] name The element name.
[in] cleanup true if the element needs to be cleaned up.
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::cleanup(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doTryRemoveNoLock().
unlock()
template<typename ResT , typename KeyT , typename TraitsT > void castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::unlock () const inline noexcept
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_mutex.
Member Data Documentation
m_clean
template<typename ResT , typename KeyT , typename TraitsT > ElementCleanerT castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_clean protected
The element cleaner.
Referenced by castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doCleanupNoLock(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doTryRemoveNoLock().
m_initialise
template<typename ResT , typename KeyT , typename TraitsT > ElementInitialiserT castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_initialise protected
The element initialiser.
Referenced by castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doTryAddNoLock(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doTryAddNoLockT().
m_logger
template<typename ResT , typename KeyT , typename TraitsT > LoggerInstance& castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_logger protected
Referenced by castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportAdded(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportCreation(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportDuplicate(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportNull(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportUnknown().
m_merge
template<typename ResT , typename KeyT , typename TraitsT > ElementMergerT castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_merge protected
The elements collection merger.
Referenced by castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::mergeInto().
m_mutex
template<typename ResT , typename KeyT , typename TraitsT > CheckedMutexT< MutexT > castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_mutex protected
Referenced by castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::lock(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::unlock().
m_resources
template<typename ResT , typename KeyT , typename TraitsT > ElementContT castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::m_resources mutable protected
The elements collection.
Referenced by castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::begin(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::begin(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doCleanupNoLock(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doClearNoLock(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doTryAddNoLock(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doTryAddNoLockT(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doTryFindNoLock(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::doTryRemoveNoLock(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::end(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::end(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::getObjectCount(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::getObjectCountNoLock(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::isEmpty(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::isEmptyNoLock(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::rename().
The documentation for this class was generated from the following files:
CastorUtils/Design/DesignModule.hpp
CastorUtils/Design/ResourceCacheBase.hpp