Castor3D: castor3d::PipelineVisitorBase Class Reference
castor3d::PipelineVisitorBase Class Reference abstract
#include <PipelineVisitor.hpp>
Classes
struct Config
Public Types
template<typename EnumT >
using OnEnumValueChangeT = std::function< void(EnumT oldV, EnumT newV) >
using OnSEnumValueChange = OnEnumValueChangeT< int32_t >
using OnUEnumValueChange = OnEnumValueChangeT< uint32_t >
Public Member Functions
virtual C3D_API ~PipelineVisitorBase ()=default
virtual C3D_API void visit (ShaderModule const &shader, bool forceProgramsVisit)=0
void visit (ShaderModule const &shader)
virtual C3D_API void visit (DebugConfig const &config)=0
void visit (castor::String const &name, crg::ImageViewId const &viewId, VkImageLayout layout, TextureFactors const &factors={})
void visit (castor::String const &name, Texture const &texture, VkImageLayout layout, TextureFactors const &factors={})
virtual C3D_API void visit (castor::String const &category)=0
virtual C3D_API void visit (castor::String const &name, bool &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, int16_t &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, uint16_t &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, int32_t &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, uint32_t &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, int64_t &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, uint64_t &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, int32_t &enumValue, castor::StringArray const &enumNames, OnSEnumValueChange onChange=[](int32_t, int32_t) {}, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, uint32_t &enumValue, castor::StringArray const &enumNames, OnUEnumValueChange onChange=[](uint32_t, uint32_t) {}, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, float &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, double &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, BlendMode &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, ParallaxOcclusionMode &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkCompareOp &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::RgbColour &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::RgbaColour &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::HdrRgbColour &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::HdrRgbaColour &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::Point2f &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::Point2i &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::Point2ui &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::Point3f &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::Point3i &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::Point3ui &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::Point4f &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::Point4i &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::Point4ui &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::Matrix4x4f &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::RangedValue< float > &range, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::RangedValue< int32_t > &range, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::RangedValue< uint32_t > &range, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, float &value, castor::Range< float > const &range, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, int32_t &value, castor::Range< int32_t > const &range, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, uint32_t &value, castor::Range< uint32_t > const &range, bool *control=nullptr)=0
template<typename TypeT >
void visit (castor::String const &name, castor::ChangeTracked< TypeT > &value)
template<typename TypeT >
void visit (castor::String const &name, castor::GroupChangeTracked< TypeT > &value)
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, float &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, int32_t &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, uint32_t &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, castor::Point2f &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, castor::Point2i &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, castor::Point2ui &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, castor::Point3f &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, castor::Point3i &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, castor::Point3ui &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, castor::Point4f &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, castor::Point4i &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, castor::Point4ui &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, castor::Matrix4x4f &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, castor::RangedValue< float > &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, castor::RangedValue< int32_t > &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, castor::RangedValue< uint32_t > &value, bool *control=nullptr)=0
template<typename TypeT >
void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, castor::ChangeTracked< TypeT > &value)
template<typename TypeT >
void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, castor::GroupChangeTracked< TypeT > &value)
Public Attributes
Config const config
Protected Member Functions
PipelineVisitorBase (Config config)
virtual C3D_API bool doFilter (crg::ImageViewId const &viewId, TextureFactors const &factors) const =0
Member Typedef Documentation
OnEnumValueChangeT
template<typename EnumT > using castor3d::PipelineVisitorBase::OnEnumValueChangeT = std::function< void(EnumT oldV, EnumT newV) >
OnSEnumValueChange
using castor3d::PipelineVisitorBase::OnSEnumValueChange = OnEnumValueChangeT< int32_t >
OnUEnumValueChange
using castor3d::PipelineVisitorBase::OnUEnumValueChange = OnEnumValueChangeT< uint32_t >
Constructor & Destructor Documentation
PipelineVisitorBase()
castor3d::PipelineVisitorBase::PipelineVisitorBase (Config config) inline explicit protected
~PipelineVisitorBase()
virtual C3D_API castor3d::PipelineVisitorBase::~PipelineVisitorBase () virtual default
Member Function Documentation
doFilter()
virtual C3D_API bool castor3d::PipelineVisitorBase::doFilter (crg::ImageViewId const & viewId, TextureFactors const & factors) const protected pure virtual
visit() [1/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & category) pure virtual
name Global pipeline configuration.
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [2/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, BlendMode & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [3/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, bool & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [4/60]
template<typename TypeT > void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::ChangeTracked< TypeT > & value) inline
References visit().
visit() [5/60]
template<typename TypeT > void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::GroupChangeTracked< TypeT > & value) inline
References visit().
visit() [6/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::HdrRgbaColour & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [7/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::HdrRgbColour & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [8/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::Matrix4x4f & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [9/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::Point2f & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [10/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::Point2i & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [11/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::Point2ui & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [12/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::Point3f & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [13/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::Point3i & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [14/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::Point3ui & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [15/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::Point4f & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [16/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::Point4i & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [17/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::Point4ui & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [18/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::RangedValue< float > & range, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [19/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::RangedValue< int32_t > & range, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [20/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::RangedValue< uint32_t > & range, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [21/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::RgbaColour & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [22/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::RgbColour & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [23/60]
void castor3d::PipelineVisitorBase::visit (castor::String const & name, crg::ImageViewId const & viewId, VkImageLayout layout, TextureFactors const & factors = {}) inline
name Intermediate images.
visit() [24/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, double & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [25/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, float & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [26/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, float & value, castor::Range< float > const & range, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [27/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, int16_t & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [28/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, int32_t & enumValue, castor::StringArray const & enumNames, OnSEnumValueChange onChange = [](int32_t, int32_t) {}, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [29/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, int32_t & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [30/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, int32_t & value, castor::Range< int32_t > const & range, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [31/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, int64_t & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [32/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, ParallaxOcclusionMode & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [33/60]
void castor3d::PipelineVisitorBase::visit (castor::String const & name, Texture const & texture, VkImageLayout layout, TextureFactors const & factors = {}) inline
visit() [34/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, uint16_t & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [35/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, uint32_t & enumValue, castor::StringArray const & enumNames, OnUEnumValueChange onChange = [](uint32_t, uint32_t) {}, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [36/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, uint32_t & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [37/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, uint32_t & value, castor::Range< uint32_t > const & range, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [38/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, uint64_t & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [39/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkCompareOp & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [40/60]
template<typename TypeT > void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, castor::ChangeTracked< TypeT > & value) inline
References visit().
visit() [41/60]
template<typename TypeT > void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, castor::GroupChangeTracked< TypeT > & value) inline
References visit().
visit() [42/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, castor::Matrix4x4f & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [43/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, castor::Point2f & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [44/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, castor::Point2i & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [45/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, castor::Point2ui & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [46/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, castor::Point3f & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [47/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, castor::Point3i & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [48/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, castor::Point3ui & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [49/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, castor::Point4f & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [50/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, castor::Point4i & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [51/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, castor::Point4ui & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [52/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, castor::RangedValue< float > & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [53/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, castor::RangedValue< int32_t > & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [54/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, castor::RangedValue< uint32_t > & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [55/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, float & value, bool * control = nullptr) pure virtual
name Shader buffer configuration.
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [56/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, int32_t & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [57/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, uint32_t & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [58/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (DebugConfig const & config) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
visit() [59/60]
void castor3d::PipelineVisitorBase::visit (ShaderModule const & shader) inline
References castor3d::PipelineVisitorBase::Config::allowProgramsVisit, config, and visit().
visit() [60/60]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (ShaderModule const & shader, bool forceProgramsVisit) pure virtual
name Shader source.
Implemented in castor3d::RenderTechniqueVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, castor3d::BackgroundVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundTextWriter, and castor3d::BackgroundVisitor.
Referenced by visit().
Member Data Documentation
config
Config const castor3d::PipelineVisitorBase::config
Referenced by visit().
The documentation for this class was generated from the following file:
Miscellaneous/PipelineVisitor.hpp