Castor3D: castor3d::RenderQuadBuilderT< ConfigT, BuilderT > Class Template Reference
castor3d::RenderQuadBuilderT< ConfigT, BuilderT > Class Template Reference
Used to create a RenderQuad variable.
#include <RenderQuad.hpp>
Public Member Functions
RenderQuadBuilderT ()
BuilderT & texcoordConfig (rq::Texcoord const &config)
BuilderT & range (VkImageSubresourceRange const &range)
BuilderT & blendMode (BlendMode blendMode)
BuilderT & bindings (rq::BindingDescriptionArray const &bindings)
BuilderT & binding (rq::BindingDescription const &binding)
BuilderT & binding (VkDescriptorType descriptor, VkShaderStageFlags stageFlags=VK_SHADER_STAGE_FRAGMENT_BIT)
BuilderT & binding (VkDescriptorType descriptor, VkImageViewType view, VkShaderStageFlags stageFlags=VK_SHADER_STAGE_FRAGMENT_BIT)
BuilderT & tex3DResult (IntermediateView result)
RenderQuadUPtr build (RenderDevice const &device, castor::String const &name, VkFilter samplerFilter)
Protected Attributes
ConfigT m_config
Detailed Description
template<typename ConfigT, typename BuilderT>
class castor3d::RenderQuadBuilderT< ConfigT, BuilderT >
Used to create a RenderQuad variable.
Constructor & Destructor Documentation
RenderQuadBuilderT()
template<typename ConfigT , typename BuilderT > castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::RenderQuadBuilderT () inline
Member Function Documentation
binding() [1/3]
template<typename ConfigT , typename BuilderT > BuilderT & castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::binding (rq::BindingDescription const & binding) inline
Adds an image.
Parameters
[in] binding Contains the binding to add.
References castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::binding(), and castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::m_config.
Referenced by castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::binding(), castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::binding(), and castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::binding().
binding() [2/3]
template<typename ConfigT , typename BuilderT > BuilderT & castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::binding (VkDescriptorType descriptor, VkImageViewType view, VkShaderStageFlags stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT) inline
Adds an image binding.
Parameters
[in] descriptor The descriptor type.
[in] view The image view.
[in] stageFlags The descriptor stage flags.
References castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::binding().
binding() [3/3]
template<typename ConfigT , typename BuilderT > BuilderT & castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::binding (VkDescriptorType descriptor, VkShaderStageFlags stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT) inline
Adds an image.
Parameters
[in] descriptor The descriptor type.
[in] stageFlags The descriptor stage flags.
References castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::binding().
bindings()
template<typename ConfigT , typename BuilderT > BuilderT & castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::bindings (rq::BindingDescriptionArray const & bindings) inline
Parameters
[in] bindings Contains the inputs bindings.
References castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::bindings(), and castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::m_config.
Referenced by castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::bindings().
blendMode()
template<typename ConfigT , typename BuilderT > BuilderT & castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::blendMode (BlendMode blendMode) inline
Parameters
[in] blendMode Contains blendMode to destination status.
References castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::blendMode(), and castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::m_config.
Referenced by castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::blendMode().
build()
template<typename ConfigT , typename BuilderT > RenderQuadUPtr castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::build (RenderDevice const & device, castor::String const & name, VkFilter samplerFilter) inline
Creates the RenderQuad.
Parameters
[in] device The RenderDevice.
[in] name The pass name.
[in] samplerFilter The sampler filter for the source texture.
References castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::m_config.
range()
template<typename ConfigT , typename BuilderT > BuilderT & castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::range (VkImageSubresourceRange const & range) inline
Parameters
[in] range Contains mip levels for the sampler.
References castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::m_config, and castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::range().
Referenced by castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::range().
tex3DResult()
template<typename ConfigT , typename BuilderT > BuilderT & castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::tex3DResult (IntermediateView result) inline
Sets the result used for for 3D texture inputs.
Remarks
The 3D textures must be preprocessed externally to this result.
Parameters
[in] result The result.
References castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::m_config.
texcoordConfig()
template<typename ConfigT , typename BuilderT > BuilderT & castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::texcoordConfig (rq::Texcoord const & config) inline
Parameters
[in] config The texture coordinates configuration.
References castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::m_config.
Member Data Documentation
m_config
template<typename ConfigT , typename BuilderT > ConfigT castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::m_config protected
Referenced by castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::binding(), castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::bindings(), castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::blendMode(), castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::build(), castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::range(), castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::tex3DResult(), and castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::texcoordConfig().
The documentation for this class was generated from the following files:
Castor3D/Render/Passes/PassesModule.hpp
Castor3D/Render/Passes/RenderQuad.hpp