Castor3D: castor3d::AlphaTestComponent Struct Reference
castor3d::AlphaTestComponent Struct Reference
#include <AlphaTestComponent.hpp>
Classes
struct ComponentsShader
struct MaterialShader
class Plugin
Public Member Functions
C3D_API AlphaTestComponent (Pass &pass)
C3D_API void accept (ConfigurationVisitorBase &vis) override
ConfigurationVisitorBase acceptance function.
C3D_API PassComponentFlag getPassFlags () const override
bool hasAlphaTest () const
bool hasBlendAlphaTest () const
VkCompareOp getAlphaFunc () const
VkCompareOp getBlendAlphaFunc () const
float getAlphaRefValue () const
void setAlphaFunc (VkCompareOp value)
void setBlendAlphaFunc (VkCompareOp value)
void setAlphaRefValue (float value)
Public Member Functions inherited from castor3d::BaseDataPassComponentT< AlphaTestData >
BaseDataPassComponentT (Pass &pass, castor::String type, castor::StringArray deps={}, ParamsT &&... params)
Constructor.
void setData (DataU const &data)
void setData (ParamsT &&... params)
AlphaTestData & getData ()
AlphaTestData const & getData () const
Public Member Functions inherited from castor3d::PassComponent
C3D_API PassComponent (Pass &pass, castor::String type, castor::StringArray deps={})
Constructor.
virtual C3D_API ~PassComponent () noexcept=default
C3D_API PassComponentUPtr clone (Pass &pass) const
virtual C3D_API void onAddToPass () const
Called when the component is added to the pass.
C3D_API bool writeText (castor::String const &tabs, castor::Path const &folder, castor::String const &subfolder, castor::StringStream &file) const
Writes the component content to text.
C3D_API void fillBuffer (PassBuffer &buffer) const
Fills the pass buffer with this pass data.
virtual C3D_API void update ()
C3D_API void fillChannel (TextureConfiguration &configuration, uint32_t mask) const
Fills the texture configuration for use with this component.
virtual C3D_API void fillConfig (TextureConfiguration &config, ConfigurationVisitorBase &vis) const
ConfigurationVisitorBase acceptance function, for a specific texture configuration.
virtual C3D_API bool hasColour () const
virtual C3D_API castor::HdrRgbColour const & getColour () const
virtual C3D_API void setColour (castor::HdrRgbColour v)
castor::String const & getType () const
castor::StringArray const & getDependencies () const
PassComponentPlugin const & getPlugin () const
PassComponentID getId () const
void setColour (castor::RgbColour const &v, float gamma=2.2f)
void setColour (castor::Coords3f const &v)
void setColour (castor::Point3f const &v)
Public Member Functions inherited from castor::OwnedBy< Pass >
Pass * getOwner () const
Static Public Member Functions
static PassComponentPluginUPtr createPlugin (PassComponentRegister const &passComponent)
Static Public Attributes
static constexpr PassFlag eAlphaTest = PassFlag(0x01u)
static C3D_API castor::String const TypeName
Additional Inherited Members
Protected Member Functions inherited from castor::OwnedBy< Pass >
OwnedBy (Pass &owner)
Constructor.
Protected Attributes inherited from castor3d::BaseDataPassComponentT< AlphaTestData >
AlphaTestData m_value
Protected Attributes inherited from castor3d::PassComponent
castor::String m_type
castor::StringArray m_dependencies
PassComponentID m_id
PassComponentPlugin const & m_plugin
std::atomic_bool & m_dirty
shader::PassMaterialShader * m_materialShader {}
Constructor & Destructor Documentation
AlphaTestComponent()
C3D_API castor3d::AlphaTestComponent::AlphaTestComponent (Pass & pass) explicit
Member Function Documentation
accept()
C3D_API void castor3d::AlphaTestComponent::accept (ConfigurationVisitorBase & vis) override virtual
ConfigurationVisitorBase acceptance function.
Parameters
vis The ... visitor.
Reimplemented from castor3d::PassComponent.
createPlugin()
static PassComponentPluginUPtr castor3d::AlphaTestComponent::createPlugin (PassComponentRegister const & passComponent) inline static
getAlphaFunc()
VkCompareOp castor3d::AlphaTestComponent::getAlphaFunc () const inline
References castor3d::AlphaTestData::alphaFunc, and castor3d::BaseDataPassComponentT< AlphaTestData >::m_value.
Referenced by hasAlphaTest().
getAlphaRefValue()
float castor3d::AlphaTestComponent::getAlphaRefValue () const inline
References castor3d::AlphaTestData::alphaRefValue, and castor3d::BaseDataPassComponentT< AlphaTestData >::m_value.
getBlendAlphaFunc()
VkCompareOp castor3d::AlphaTestComponent::getBlendAlphaFunc () const inline
References castor3d::AlphaTestData::blendAlphaFunc, and castor3d::BaseDataPassComponentT< AlphaTestData >::m_value.
Referenced by hasBlendAlphaTest().
getPassFlags()
C3D_API PassComponentFlag castor3d::AlphaTestComponent::getPassFlags () const inline override virtual
Reimplemented from castor3d::PassComponent.
References eAlphaTest, castor3d::eNone, castor3d::PassComponent::getId(), hasAlphaTest(), hasBlendAlphaTest(), and castor3d::makePassComponentFlag().
hasAlphaTest()
bool castor3d::AlphaTestComponent::hasAlphaTest () const inline
References getAlphaFunc().
Referenced by getPassFlags().
hasBlendAlphaTest()
bool castor3d::AlphaTestComponent::hasBlendAlphaTest () const inline
References getBlendAlphaFunc().
Referenced by getPassFlags().
setAlphaFunc()
void castor3d::AlphaTestComponent::setAlphaFunc (VkCompareOp value) inline
References castor3d::AlphaTestData::alphaFunc, and castor3d::BaseDataPassComponentT< AlphaTestData >::m_value.
setAlphaRefValue()
void castor3d::AlphaTestComponent::setAlphaRefValue (float value) inline
References castor3d::AlphaTestData::alphaRefValue, and castor3d::BaseDataPassComponentT< AlphaTestData >::m_value.
setBlendAlphaFunc()
void castor3d::AlphaTestComponent::setBlendAlphaFunc (VkCompareOp value) inline
References castor3d::AlphaTestData::blendAlphaFunc, and castor3d::BaseDataPassComponentT< AlphaTestData >::m_value.
Member Data Documentation
eAlphaTest
constexpr PassFlag castor3d::AlphaTestComponent::eAlphaTest = PassFlag(0x01u) static constexpr
Referenced by castor3d::AlphaTestComponent::Plugin::getComponentFlags(), and getPassFlags().
TypeName
C3D_API castor::String const castor3d::AlphaTestComponent::TypeName static
The documentation for this struct was generated from the following file:
Castor3D/Material/Pass/Component/Other/AlphaTestComponent.hpp