Castor3D: castor::TSConnectionT< SignalT > Class Template Reference
castor::TSConnectionT< SignalT > Class Template Reference
Connection to a thread safe signal.
#include <ThreadSafeSignal.hpp>
Public Member Functions
TSConnectionT ()
Constructor.
TSConnectionT (uint32_t connection, my_signal &signal)
Constructor.
TSConnectionT (TSConnectionT< my_signal > &&rhs) noexcept
Move constructor.
TSConnectionT & operator= (TSConnectionT< my_signal > &&rhs) noexcept
Move assignment operator.
~TSConnectionT () noexcept
Destructor.
bool disconnect () noexcept
Disconnects the function from the signal.
operator bool () const noexcept
Additional Inherited Members
Protected Member Functions inherited from castor::NonCopyable
NonCopyable ()=default
Constructor.
~NonCopyable () noexcept=default
Destructor.
Detailed Description
template<typename SignalT>
class castor::TSConnectionT< SignalT >
Connection to a thread safe signal.
Constructor & Destructor Documentation
TSConnectionT() [1/3]
template<typename SignalT > castor::TSConnectionT< SignalT >::TSConnectionT () inline
Constructor.
TSConnectionT() [2/3]
template<typename SignalT > castor::TSConnectionT< SignalT >::TSConnectionT (uint32_t connection, my_signal & signal) inline
Constructor.
Parameters
[in] connection The connection to the signal.
[in] signal The signal.
References castor::makeStringStream().
TSConnectionT() [3/3]
template<typename SignalT > castor::TSConnectionT< SignalT >::TSConnectionT (TSConnectionT< my_signal > && rhs) inline noexcept
Move constructor.
Parameters
[in,out] rhs The object to move.
~TSConnectionT()
template<typename SignalT > castor::TSConnectionT< SignalT >::~TSConnectionT () inline noexcept
Destructor.
Remarks
Disconnects the function from the signal.
References castor::TSConnectionT< SignalT >::disconnect(), and castor::makeUniqueLock().
Member Function Documentation
disconnect()
template<typename SignalT > bool castor::TSConnectionT< SignalT >::disconnect () inline noexcept
Disconnects the function from the signal.
Referenced by castor::TSConnectionT< SignalT >::operator=(), and castor::TSConnectionT< SignalT >::~TSConnectionT().
operator bool()
template<typename SignalT > castor::TSConnectionT< SignalT >::operator bool () const inline noexcept
operator=()
template<typename SignalT > TSConnectionT & castor::TSConnectionT< SignalT >::operator= (TSConnectionT< my_signal > && rhs) inline noexcept
Move assignment operator.
Parameters
[in,out] rhs The object to move.
References castor::TSConnectionT< SignalT >::disconnect().
The documentation for this class was generated from the following files:
CastorUtils/Design/DesignModule.hpp
CastorUtils/Design/ThreadSafeSignal.hpp