Castor3D: castor3d::ProgressBar Class Reference
castor3d::ProgressBar Class Reference
#include <ProgressBar.hpp>
Public Member Functions
C3D_API ProgressBar (Engine &engine, ProgressCtrlRPtr globalProgress, ProgressCtrlRPtr localProgress=nullptr)
C3D_API void update (ProgressCtrlRPtr globalProgress, ProgressCtrlRPtr localProgress=nullptr)
C3D_API void initGlobalRange (uint32_t value)
C3D_API uint32_t incGlobalRange (uint32_t value)
C3D_API void stepGlobal (castor::String const &globalTitle)
C3D_API void setGlobalStep (castor::String const &globalTitle, uint32_t count)
C3D_API void initLocalRange (castor::String const &globalLabel, uint32_t value)
C3D_API void stepLocal (castor::String const &label)
C3D_API void setLocalStep (castor::String const &label, uint32_t count)
C3D_API void setGlobalTitle (castor::String const &globalTitle)
C3D_API void stepGlobalStartLocal (castor::String const &globalLabel, uint32_t rangeMax)
C3D_API void setLocal (castor::String const &globalLabel, castor::String const &localLabel, uint32_t rangeMax, uint32_t value)
void lock ()
void unlock ()
Constructor & Destructor Documentation
ProgressBar()
C3D_API castor3d::ProgressBar::ProgressBar (Engine & engine, ProgressCtrlRPtr globalProgress, ProgressCtrlRPtr localProgress = nullptr)
Member Function Documentation
incGlobalRange()
C3D_API uint32_t castor3d::ProgressBar::incGlobalRange (uint32_t value)
initGlobalRange()
C3D_API void castor3d::ProgressBar::initGlobalRange (uint32_t value)
Referenced by castor3d::LoadingScreen::initGlobalRange().
initLocalRange()
C3D_API void castor3d::ProgressBar::initLocalRange (castor::String const & globalLabel, uint32_t value)
Referenced by castor3d::LoadingScreen::initLocalRange().
lock()
void castor3d::ProgressBar::lock () inline
setGlobalStep()
C3D_API void castor3d::ProgressBar::setGlobalStep (castor::String const & globalTitle, uint32_t count)
setGlobalTitle()
C3D_API void castor3d::ProgressBar::setGlobalTitle (castor::String const & globalTitle)
setLocal()
C3D_API void castor3d::ProgressBar::setLocal (castor::String const & globalLabel, castor::String const & localLabel, uint32_t rangeMax, uint32_t value)
setLocalStep()
C3D_API void castor3d::ProgressBar::setLocalStep (castor::String const & label, uint32_t count)
stepGlobal()
C3D_API void castor3d::ProgressBar::stepGlobal (castor::String const & globalTitle)
Referenced by castor3d::LoadingScreen::stepGlobal().
stepGlobalStartLocal()
C3D_API void castor3d::ProgressBar::stepGlobalStartLocal (castor::String const & globalLabel, uint32_t rangeMax)
stepLocal()
C3D_API void castor3d::ProgressBar::stepLocal (castor::String const & label)
Referenced by castor3d::LoadingScreen::stepLocal().
unlock()
void castor3d::ProgressBar::unlock () inline
update()
C3D_API void castor3d::ProgressBar::update (ProgressCtrlRPtr globalProgress, ProgressCtrlRPtr localProgress = nullptr)
The documentation for this class was generated from the following file:
Castor3D/Miscellaneous/ProgressBar.hpp