Castor3D: castor::format::BasicIndentBufferManager< char_type, traits > Class Template Reference
castor::format::BasicIndentBufferManager< char_type, traits > Class Template Reference
Holds associated streams and stream buffers.
#include <StreamIndentBufferManager.hpp>
Public Member Functions
~BasicIndentBufferManager () noexcept
Destructor.
bool insert (bos &o_s, bsb *b_s)
Inserts a stream and a stream buffer.
size_t size ()
Retrieves the items count.
bsb * getBuffer (std::ios_base &io_s)
Retrieves the stream buffer associated to given stream.
bool erase (std::ios_base &io_s)
Static Public Member Functions
static size_t instances ()
Retrieves the instances count.
static BasicIndentBufferManager< char_type, traits > * instance ()
Retrieves an instance of the BasicIndentBufferManager.
Detailed Description
template<typename char_type, typename traits>
class castor::format::BasicIndentBufferManager< char_type, traits >
Holds associated streams and stream buffers.
Constructor & Destructor Documentation
~BasicIndentBufferManager()
template<typename char_type , typename traits > castor::format::BasicIndentBufferManager< char_type, traits >::~BasicIndentBufferManager () inline noexcept
Destructor.
References castor::makeUniqueLock().
Member Function Documentation
erase()
template<typename char_type , typename traits > bool castor::format::BasicIndentBufferManager< char_type, traits >::erase (std::ios_base & io_s) inline
References castor::format::BasicIndentBufferManager< char_type, traits >::getBuffer(), and castor::makeUniqueLock().
getBuffer()
template<typename char_type , typename traits > bsb * castor::format::BasicIndentBufferManager< char_type, traits >::getBuffer (std::ios_base & io_s) inline
Retrieves the stream buffer associated to given stream.
Parameters
[in] io_s The stream
References castor::makeUniqueLock().
Referenced by castor::format::BasicIndentBufferManager< char_type, traits >::erase().
insert()
template<typename char_type , typename traits > bool castor::format::BasicIndentBufferManager< char_type, traits >::insert (bos & o_s, bsb * b_s) inline
Inserts a stream and a stream buffer.
Parameters
[in] o_s The stream
[in] b_s The stream buffer
Returns
true if the pair wa successfully added
References castor::makeUniqueLock().
instance()
template<typename char_type , typename traits > static BasicIndentBufferManager< char_type, traits > * castor::format::BasicIndentBufferManager< char_type, traits >::instance () inline static
Retrieves an instance of the BasicIndentBufferManager.
Referenced by castor::format::callback().
instances()
template<typename char_type , typename traits > static size_t castor::format::BasicIndentBufferManager< char_type, traits >::instances () inline static
Retrieves the instances count.
Returns
The count
size()
template<typename char_type , typename traits > size_t castor::format::BasicIndentBufferManager< char_type, traits >::size () inline
Retrieves the items count.
Returns
The count
References castor::makeUniqueLock().
The documentation for this class was generated from the following file:
CastorUtils/Stream/StreamIndentBufferManager.hpp