Castor3D: castor3d::ControlStyle Class Reference
castor3d::ControlStyle Class Reference abstract
#include <StyleControl.hpp>
Public Member Functions
virtual C3D_API ~ControlStyle () noexcept=default
ControlStyle (ControlType type, castor::String const &name, Scene *scene, Engine &engine, MouseCursor cursor=MouseCursor::eArrow)
void setBackgroundMaterial (MaterialObs value)
void setForegroundMaterial (MaterialObs value)
void setCursor (MouseCursor value) noexcept
void setBackgroundInvisible (bool value) noexcept
void setForegroundInvisible (bool value) noexcept
bool isBackgroundInvisible () const noexcept
bool isForegroundInvisible () const noexcept
MaterialObs getBackgroundMaterial () const noexcept
MaterialObs getForegroundMaterial () const noexcept
ControlType getType () const noexcept
MouseCursor getCursor () const noexcept
Engine & getEngine () const noexcept
bool hasScene () const noexcept
Scene & getScene () const noexcept
Public Member Functions inherited from castor::NamedBaseT< T >
NamedBaseT (T name) noexcept
Constructor.
T const & getName () const noexcept
Retrieves the name.
void rename (T name) noexcept
Protected Member Functions
MaterialObs doCreateMaterial (MaterialObs material, float offset, castor::String const &suffix) const
Additional Inherited Members
Protected Attributes inherited from castor::NamedBaseT< T >
T m_name
Constructor & Destructor Documentation
~ControlStyle()
virtual C3D_API castor3d::ControlStyle::~ControlStyle () virtual default noexcept
ControlStyle()
castor3d::ControlStyle::ControlStyle (ControlType type, castor::String const & name, Scene * scene, Engine & engine, MouseCursor cursor = MouseCursor::eArrow) inline
Member Function Documentation
doCreateMaterial()
MaterialObs castor3d::ControlStyle::doCreateMaterial (MaterialObs material, float offset, castor::String const & suffix) const inline protected
References castor::RgbColourT< ComponentType >::blue(), castor3d::createMaterial(), getEngine(), castor3d::getMaterialColour(), castor::NamedBaseT< T >::getName(), castor3d::Material::getPass(), castor::RgbColourT< ComponentType >::green(), and castor::RgbColourT< ComponentType >::red().
getBackgroundMaterial()
MaterialObs castor3d::ControlStyle::getBackgroundMaterial () const inline noexcept
getCursor()
MouseCursor castor3d::ControlStyle::getCursor () const inline noexcept
getEngine()
Engine & castor3d::ControlStyle::getEngine () const inline noexcept
Referenced by doCreateMaterial().
getForegroundMaterial()
MaterialObs castor3d::ControlStyle::getForegroundMaterial () const inline noexcept
Referenced by castor3d::ProgressStyle::getTextMaterial().
getScene()
Scene & castor3d::ControlStyle::getScene () const inline noexcept
References CU_Require, and hasScene().
getType()
ControlType castor3d::ControlStyle::getType () const inline noexcept
hasScene()
bool castor3d::ControlStyle::hasScene () const inline noexcept
Referenced by getScene().
isBackgroundInvisible()
bool castor3d::ControlStyle::isBackgroundInvisible () const inline noexcept
isForegroundInvisible()
bool castor3d::ControlStyle::isForegroundInvisible () const inline noexcept
setBackgroundInvisible()
void castor3d::ControlStyle::setBackgroundInvisible (bool value) inline noexcept
Referenced by castor3d::FrameStyle::FrameStyle(), and castor3d::ProgressStyle::ProgressStyle().
setBackgroundMaterial()
void castor3d::ControlStyle::setBackgroundMaterial (MaterialObs value) inline
setCursor()
void castor3d::ControlStyle::setCursor (MouseCursor value) inline noexcept
setForegroundInvisible()
void castor3d::ControlStyle::setForegroundInvisible (bool value) inline noexcept
Referenced by castor3d::FrameStyle::FrameStyle().
setForegroundMaterial()
void castor3d::ControlStyle::setForegroundMaterial (MaterialObs value) inline
The documentation for this class was generated from the following file:
Castor3D/Gui/Theme/StyleControl.hpp