Castor3D: castor3d::RenderQuad Class Reference
castor3d::RenderQuad Class Reference
#include <RenderQuad.hpp>
Public Member Functions
virtual C3D_API ~RenderQuad ()
C3D_API RenderQuad (RenderQuad &&rhs) noexcept
C3D_API void cleanup ()
Cleans up GPU objects.
C3D_API void createPipeline (VkExtent2D const &size, castor::Position const &position, ashes::PipelineShaderStageCreateInfoArray const &program, ashes::RenderPass const &renderPass, ashes::VkPushConstantRangeArray const &pushRanges=ashes::VkPushConstantRangeArray{}, ashes::PipelineDepthStencilStateCreateInfo dsState=ashes::PipelineDepthStencilStateCreateInfo{ 0u, VK_FALSE, VK_FALSE })
Creates the rendering pipeline.
C3D_API void registerPassInputs (ashes::WriteDescriptorSetArray const &writes, bool invertY=false)
Creates the entries for one pass.
C3D_API void initialisePasses ()
Initialises the descriptor sets for all registered passes.
C3D_API void createPipelineAndPass (VkExtent2D const &size, castor::Position const &position, ashes::PipelineShaderStageCreateInfoArray const &program, ashes::RenderPass const &renderPass, ashes::WriteDescriptorSetArray const &writes, ashes::VkPushConstantRangeArray const &pushRanges=ashes::VkPushConstantRangeArray{}, ashes::PipelineDepthStencilStateCreateInfo dsState=ashes::PipelineDepthStencilStateCreateInfo{ 0u, false, false })
Creates the rendering pipeline and initialises the quad for one pass.
C3D_API void registerPass (ashes::CommandBuffer &commandBuffer, uint32_t descriptorSetIndex) const
Prpares the commands to render the quad, inside given command buffer.
void registerPass (ashes::CommandBuffer &commandBuffer) const
Prpares the commands to render the quad, inside given command buffer.
RenderSystem * getRenderSystem () const
RenderDevice const & getDevice () const
Sampler const & getSampler () const
Static Public Member Functions
static C3D_API ashes::WriteDescriptorSet makeDescriptorWrite (VkImageView const &view, VkSampler const &sampler, uint32_t dstBinding, uint32_t dstArrayElement=0u)
Creates a descriptor write for combined image sampler.
static C3D_API ashes::WriteDescriptorSet makeDescriptorWrite (ashes::ImageView const &view, ashes::Sampler const &sampler, uint32_t dstBinding, uint32_t dstArrayElement=0u)
Creates a descriptor write for combined image sampler.
static C3D_API ashes::WriteDescriptorSet makeDescriptorWrite (ashes::UniformBuffer const &buffer, uint32_t dstBinding, uint32_t elemOffset, uint32_t elemRange, uint32_t dstArrayElement=0u)
Creates a descriptor write for uniform buffer.
template<typename DataT >
static ashes::WriteDescriptorSet makeDescriptorWrite (UniformBufferOffsetT< DataT > const &buffer, uint32_t dstBinding, uint32_t dstArrayElement=0u)
Creates a descriptor write for uniform buffer range.
static C3D_API ashes::WriteDescriptorSet makeDescriptorWrite (ashes::BufferBase const &storageBuffer, uint32_t dstBinding, uint32_t byteOffset, uint32_t byteRange, uint32_t dstArrayElement=0u)
Creates a descriptor write for storage buffer.
template<typename DataT >
static ashes::WriteDescriptorSet makeDescriptorWrite (ashes::Buffer< DataT > const &storageBuffer, uint32_t dstBinding, uint32_t elemOffset, uint32_t elemRange, uint32_t dstArrayElement=0u)
Creates a descriptor write for storage buffer.
static C3D_API ashes::WriteDescriptorSet makeDescriptorWrite (ashes::BufferBase const &buffer, ashes::BufferView const &view, uint32_t dstBinding, uint32_t dstArrayElement=0u)
Creates a descriptor write for buffer texel view.
template<typename DataT >
static ashes::WriteDescriptorSet makeDescriptorWrite (ashes::Buffer< DataT > const &buffer, ashes::BufferView const &view, uint32_t dstBinding, uint32_t dstArrayElement=0u)
Creates a descriptor write for buffer texel view.
Protected Member Functions
C3D_API RenderQuad (RenderDevice const &device, castor::String const &name, VkFilter samplerFilter, rq::Config config)
Constructor.
Protected Attributes
RenderSystem & m_renderSystem
RenderDevice const & m_device
SamplerResPtr m_sampler
rq::ConfigData m_config
Friends
template<typename ConfigT , typename BuilderT >
class RenderQuadBuilderT
Constructor & Destructor Documentation
RenderQuad() [1/2]
C3D_API castor3d::RenderQuad::RenderQuad (RenderDevice const & device, castor::String const & name, VkFilter samplerFilter, rq::Config config) protected
Constructor.
Parameters
[in] device The RenderDevice.
[in] name The pass name.
[in] samplerFilter The sampler filter for the source texture.
[in] config The configuration.
~RenderQuad()
virtual C3D_API castor3d::RenderQuad::~RenderQuad () virtual
RenderQuad() [2/2]
C3D_API castor3d::RenderQuad::RenderQuad (RenderQuad && rhs) explicit noexcept
Member Function Documentation
cleanup()
C3D_API void castor3d::RenderQuad::cleanup ()
Cleans up GPU objects.
createPipeline()
C3D_API void castor3d::RenderQuad::createPipeline (VkExtent2D const & size, castor::Position const & position, ashes::PipelineShaderStageCreateInfoArray const & program, ashes::RenderPass const & renderPass, ashes::VkPushConstantRangeArray const & pushRanges = ashes::VkPushConstantRangeArray{}, ashes::PipelineDepthStencilStateCreateInfo dsState = ashes::PipelineDepthStencilStateCreateInfo{ 0u, VK_FALSE, VK_FALSE })
Creates the rendering pipeline.
Parameters
[in] size The render size.
[in] position The render position.
[in] program The shader program.
[in] renderPass The render pass to use.
[in] pushRanges The push constant ranges.
[in] dsState The depth and stencil state.
createPipelineAndPass()
C3D_API void castor3d::RenderQuad::createPipelineAndPass (VkExtent2D const & size, castor::Position const & position, ashes::PipelineShaderStageCreateInfoArray const & program, ashes::RenderPass const & renderPass, ashes::WriteDescriptorSetArray const & writes, ashes::VkPushConstantRangeArray const & pushRanges = ashes::VkPushConstantRangeArray{}, ashes::PipelineDepthStencilStateCreateInfo dsState = ashes::PipelineDepthStencilStateCreateInfo{ 0u, false, false })
Creates the rendering pipeline and initialises the quad for one pass.
Parameters
[in] size The render size.
[in] position The render position.
[in] program The shader program.
[in] renderPass The render pass to use.
[in] writes The pass descriptor writes.
[in] pushRanges The push constant ranges.
[in] dsState The depth stencil state to use.
getDevice()
RenderDevice const & castor3d::RenderQuad::getDevice () const inline
References m_device.
getRenderSystem()
RenderSystem * castor3d::RenderQuad::getRenderSystem () const inline
References m_renderSystem.
getSampler()
Sampler const & castor3d::RenderQuad::getSampler () const inline
References m_sampler.
initialisePasses()
C3D_API void castor3d::RenderQuad::initialisePasses ()
Initialises the descriptor sets for all registered passes.
makeDescriptorWrite() [1/8]
template<typename DataT > static ashes::WriteDescriptorSet castor3d::RenderQuad::makeDescriptorWrite (ashes::Buffer< DataT > const & buffer, ashes::BufferView const & view, uint32_t dstBinding, uint32_t dstArrayElement = 0u) inline static
Creates a descriptor write for buffer texel view.
Parameters
[in] buffer The buffer.
[in] view The texel view.
[in] dstBinding The binding inside the descriptor set.
[in] dstArrayElement The array element index.
References makeDescriptorWrite().
makeDescriptorWrite() [2/8]
template<typename DataT > static ashes::WriteDescriptorSet castor3d::RenderQuad::makeDescriptorWrite (ashes::Buffer< DataT > const & storageBuffer, uint32_t dstBinding, uint32_t elemOffset, uint32_t elemRange, uint32_t dstArrayElement = 0u) inline static
Creates a descriptor write for storage buffer.
Parameters
[in] storageBuffer The storage buffer.
[in] dstBinding The binding inside the descriptor set.
[in] elemOffset The offset, expressed in element count.
[in] elemRange The range, expressed in element count.
[in] dstArrayElement The array element index.
References makeDescriptorWrite().
makeDescriptorWrite() [3/8]
static C3D_API ashes::WriteDescriptorSet castor3d::RenderQuad::makeDescriptorWrite (ashes::BufferBase const & buffer, ashes::BufferView const & view, uint32_t dstBinding, uint32_t dstArrayElement = 0u) static
Creates a descriptor write for buffer texel view.
Parameters
[in] buffer The buffer.
[in] view The texel view.
[in] dstBinding The binding inside the descriptor set.
[in] dstArrayElement The array element index.
makeDescriptorWrite() [4/8]
static C3D_API ashes::WriteDescriptorSet castor3d::RenderQuad::makeDescriptorWrite (ashes::BufferBase const & storageBuffer, uint32_t dstBinding, uint32_t byteOffset, uint32_t byteRange, uint32_t dstArrayElement = 0u) static
Creates a descriptor write for storage buffer.
Parameters
[in] storageBuffer The storage buffer.
[in] dstBinding The binding inside the descriptor set.
[in] byteOffset The offset, expressed in bytes.
[in] byteRange The range, expressed in bytes.
[in] dstArrayElement The array element index.
makeDescriptorWrite() [5/8]
static C3D_API ashes::WriteDescriptorSet castor3d::RenderQuad::makeDescriptorWrite (ashes::ImageView const & view, ashes::Sampler const & sampler, uint32_t dstBinding, uint32_t dstArrayElement = 0u) static
Creates a descriptor write for combined image sampler.
Parameters
[in] view The image view.
[in] sampler The sampler.
[in] dstBinding The binding inside the descriptor set.
[in] dstArrayElement The array element index.
makeDescriptorWrite() [6/8]
static C3D_API ashes::WriteDescriptorSet castor3d::RenderQuad::makeDescriptorWrite (ashes::UniformBuffer const & buffer, uint32_t dstBinding, uint32_t elemOffset, uint32_t elemRange, uint32_t dstArrayElement = 0u) static
Creates a descriptor write for uniform buffer.
Parameters
[in] buffer The uniform buffer.
[in] dstBinding The binding inside the descriptor set.
[in] elemOffset The offset, expressed in element count.
[in] elemRange The range, expressed in element count.
[in] dstArrayElement The array element index.
makeDescriptorWrite() [7/8]
template<typename DataT > static ashes::WriteDescriptorSet castor3d::RenderQuad::makeDescriptorWrite (UniformBufferOffsetT< DataT > const & buffer, uint32_t dstBinding, uint32_t dstArrayElement = 0u) inline static
Creates a descriptor write for uniform buffer range.
Parameters
[in] buffer The uniform buffer range.
[in] dstBinding The binding inside the descriptor set.
[in] dstArrayElement The array element index.
References castor3d::UniformBufferOffsetT< DataT >::getDescriptorWrite().
makeDescriptorWrite() [8/8]
static C3D_API ashes::WriteDescriptorSet castor3d::RenderQuad::makeDescriptorWrite (VkImageView const & view, VkSampler const & sampler, uint32_t dstBinding, uint32_t dstArrayElement = 0u) static
Creates a descriptor write for combined image sampler.
Parameters
[in] view The image view.
[in] sampler The sampler.
[in] dstBinding The binding inside the descriptor set.
[in] dstArrayElement The array element index.
Referenced by makeDescriptorWrite().
registerPass() [1/2]
void castor3d::RenderQuad::registerPass (ashes::CommandBuffer & commandBuffer) const inline
Prpares the commands to render the quad, inside given command buffer.
Parameters
[in,out] commandBuffer The command buffer.
References registerPass().
registerPass() [2/2]
C3D_API void castor3d::RenderQuad::registerPass (ashes::CommandBuffer & commandBuffer, uint32_t descriptorSetIndex) const
Prpares the commands to render the quad, inside given command buffer.
Parameters
[in,out] commandBuffer The command buffer.
[in] descriptorSetIndex The render descriptor set index.
Referenced by registerPass().
registerPassInputs()
C3D_API void castor3d::RenderQuad::registerPassInputs (ashes::WriteDescriptorSetArray const & writes, bool invertY = false)
Creates the entries for one pass.
Parameters
[in] writes The pass descriptor writes.
[in] invertY true to Y invert the sampled image.
Friends And Related Function Documentation
RenderQuadBuilderT
template<typename ConfigT , typename BuilderT > friend class RenderQuadBuilderT friend
Member Data Documentation
m_config
rq::ConfigData castor3d::RenderQuad::m_config protected
m_device
RenderDevice const& castor3d::RenderQuad::m_device protected
Referenced by getDevice().
m_renderSystem
RenderSystem& castor3d::RenderQuad::m_renderSystem protected
Referenced by getRenderSystem().
m_sampler
SamplerResPtr castor3d::RenderQuad::m_sampler protected
Referenced by getSampler().
The documentation for this class was generated from the following file:
Render/Passes/RenderQuad.hpp