Castor3D: castor3d::RenderQuadBuilderT< ConfigT, BuilderT > Class Template Reference
castor3d::RenderQuadBuilderT< ConfigT, BuilderT > Class Template Reference
Used to create a RenderQuad variable.
Public Member Functions
RenderQuadBuilderT ()
BuilderT & texcoordConfig (rq::Texcoord const &config)
BuilderT & range (VkImageSubresourceRange const &range)
BuilderT & blendMode (BlendMode blendMode)
BuilderT & bindings (rq::BindingDescriptionArray const &bindings)
BuilderT & binding (rq::BindingDescription const &binding)
BuilderT & binding (VkDescriptorType descriptor, VkShaderStageFlags stageFlags=VK_SHADER_STAGE_FRAGMENT_BIT)
BuilderT & binding (VkDescriptorType descriptor, VkImageViewType view, VkShaderStageFlags stageFlags=VK_SHADER_STAGE_FRAGMENT_BIT)
RenderQuadUPtr build (RenderDevice const &device, castor::String const &name, VkFilter samplerFilter)
Protected Attributes
ConfigT m_config
Detailed Description
template<typename ConfigT, typename BuilderT>
class castor3d::RenderQuadBuilderT< ConfigT, BuilderT >
Used to create a RenderQuad variable.
Constructor & Destructor Documentation
RenderQuadBuilderT()
template<typename ConfigT, typename BuilderT> castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::RenderQuadBuilderT () inline
Member Function Documentation
binding() [1/3]
template<typename ConfigT, typename BuilderT> BuilderT& castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::binding (rq::BindingDescription const & binding) inline
Adds an image.
Parameters
[in] binding Contains the binding to add.
Referenced by castor3d::RenderQuadBuilderT< CombinePassConfig, CombinePassBuilder >::binding().
binding() [2/3]
template<typename ConfigT, typename BuilderT> BuilderT& castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::binding (VkDescriptorType descriptor, VkShaderStageFlags stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT) inline
Adds an image.
Parameters
[in] descriptor The descriptor type.
[in] stageFlags The descriptor stage flags.
binding() [3/3]
template<typename ConfigT, typename BuilderT> BuilderT& castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::binding (VkDescriptorType descriptor, VkImageViewType view, VkShaderStageFlags stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT) inline
Adds an image binding.
Parameters
[in] descriptor The descriptor type.
[in] view The image view.
[in] stageFlags The descriptor stage flags.
bindings()
template<typename ConfigT, typename BuilderT> BuilderT& castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::bindings (rq::BindingDescriptionArray const & bindings) inline
Parameters
[in] bindings Contains the inputs bindings.
Referenced by castor3d::RenderQuadBuilderT< CombinePassConfig, CombinePassBuilder >::bindings().
blendMode()
template<typename ConfigT, typename BuilderT> BuilderT& castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::blendMode (BlendMode blendMode) inline
Parameters
[in] blendMode Contains blendMode to destination status.
Referenced by castor3d::RenderQuadBuilderT< CombinePassConfig, CombinePassBuilder >::blendMode().
build()
template<typename ConfigT, typename BuilderT> RenderQuadUPtr castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::build (RenderDevice const & device, castor::String const & name, VkFilter samplerFilter) inline
Creates the RenderQuad.
Parameters
[in] device The RenderDevice.
[in] name The pass name.
[in] samplerFilter The sampler filter for the source texture.
range()
template<typename ConfigT, typename BuilderT> BuilderT& castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::range (VkImageSubresourceRange const & range) inline
Parameters
[in] range Contains mip levels for the sampler.
Referenced by castor3d::RenderQuadBuilderT< CombinePassConfig, CombinePassBuilder >::range().
texcoordConfig()
template<typename ConfigT, typename BuilderT> BuilderT& castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::texcoordConfig (rq::Texcoord const & config) inline
Parameters
[in] config The texture coordinates configuration.
Member Data Documentation
m_config
template<typename ConfigT, typename BuilderT> ConfigT castor3d::RenderQuadBuilderT< ConfigT, BuilderT >::m_config protected
Referenced by castor3d::RenderQuadBuilderT< CombinePassConfig, CombinePassBuilder >::binding(), castor3d::RenderQuadBuilderT< CombinePassConfig, CombinePassBuilder >::bindings(), castor3d::RenderQuadBuilderT< CombinePassConfig, CombinePassBuilder >::blendMode(), castor3d::RenderGridBuilderT< rq::Config, RenderGridBuilder >::build(), castor3d::RenderQuadBuilderT< CombinePassConfig, CombinePassBuilder >::build(), castor3d::RenderQuadBuilderT< CombinePassConfig, CombinePassBuilder >::range(), and castor3d::RenderQuadBuilderT< CombinePassConfig, CombinePassBuilder >::texcoordConfig().
The documentation for this class was generated from the following files:
Render/Passes/PassesModule.hpp
Render/Passes/RenderQuad.hpp