Castor3D: castor3d::RenderTechnique Class Reference
castor3d::RenderTechnique Class Reference
#include <RenderTechnique.hpp>
Public Types
using ShadowMapArray = castor::Vector< ShadowMapUPtr >
Public Member Functions
C3D_API RenderTechnique (castor::String const &name, RenderTarget &renderTarget, RenderDevice const &device, Texture const &colour, Texture const &intermediate, crg::FramePassArray previousPasses, ProgressBar *progress, bool visbuffer, bool weightedBlended)
Constructor.
C3D_API ~RenderTechnique () noexcept
Destructor.
C3D_API void update (CpuUpdater &updater)
Updates the render pass, CPU wise.
C3D_API void update (GpuUpdater &updater)
Updates the render pass, GPU wise.
C3D_API crg::SemaphoreWaitArray preRender (crg::SemaphoreWaitArray const &toWait, ashes::Queue const &queue)
Renders maps needed for the actual rendering.
C3D_API void accept (RenderTechniqueVisitor &visitor)
Visitor acceptance function.
C3D_API crg::FramePass const & getLastPass () const
C3D_API SsaoConfig const & getSsaoConfig () const
C3D_API ClustersConfig const * getClustersConfig () const
C3D_API SsaoConfig & getSsaoConfig ()
C3D_API Texture const & getSsaoResult () const
C3D_API Texture const & getSssDiffuse () const
C3D_API TechniquePassVector getCustomRenderPasses () const
C3D_API crg::ResourcesCache & getResources () const
C3D_API bool isOpaqueEnabled () const
C3D_API DebugConfig & getDebugConfig () const
C3D_API bool areDebugTargetsEnabled () const noexcept
castor::Size const & getSize () const noexcept
crg::ImageViewIdArray getSampledResult () const noexcept
crg::ImageViewIdArray getTargetResult () const noexcept
crg::ImageViewIdArray getSampledIntermediate () const noexcept
crg::ImageViewIdArray getTargetIntermediate () const noexcept
crg::ImageViewIdArray getTargetDepth () const noexcept
Texture const & getDepth () const noexcept
Texture const & getResult () const noexcept
Texture const & getIntermediate () const noexcept
VkExtent3D const & getTargetExtent () const noexcept
VkFormat getTargetFormat () const noexcept
Texture const & getNormal () const noexcept
Texture const & getScattering () const noexcept
Texture const & getDiffuse () const noexcept
Texture const & getDepthObj () const noexcept
ashes::Buffer< int32_t > const & getDepthRange () const noexcept
void setNeedsDepthRange (bool v) noexcept
ShadowMapResult const & getDirectionalShadowPassResult () const noexcept
ShadowMapResult const & getPointShadowPassResult () const noexcept
ShadowMapResult const & getSpotShadowPassResult () const noexcept
CameraUbo const & getCameraUbo () const noexcept
CameraUbo & getCameraUbo () noexcept
SceneUbo const & getSceneUbo () const noexcept
SceneUbo & getSceneUbo () noexcept
ShadowMapLightTypeArray const & getShadowMaps () const noexcept
RenderTarget const & getRenderTarget () const noexcept
RenderTarget & getRenderTarget () noexcept
bool isMultisampling () const noexcept
ashes::Buffer< uint32_t > const & getMaterialsCounts () const noexcept
ashes::Buffer< castor::Point3ui > const & getMaterialsIndirectCounts () const noexcept
ashes::Buffer< uint32_t > const & getMaterialsStarts () const noexcept
ashes::Buffer< castor::Point2ui > const & getPixelXY () const noexcept
bool hasVisibility () const noexcept
Texture const & getVisibilityResult () const noexcept
crg::FramePass const & getGetLastDepthPass () const noexcept
crg::FramePass const & getDepthRangePass () const noexcept
crg::FramePass const & getGetLastOpaquePass () const noexcept
crg::FramePass const & getGetLastTransparentPass () const noexcept
crg::FramePassGroup & getGraph () noexcept
IndirectLightingData const & getIndirectLighting () const noexcept
bool hasShadowBuffer () const noexcept
ShadowBuffer & getShadowBuffer () const noexcept
Public Member Functions inherited from castor::OwnedBy< Engine >
Engine * getOwner () const
Public Member Functions inherited from castor::NamedBaseT< T >
NamedBaseT (T name) noexcept
Constructor.
T const & getName () const noexcept
Retrieves the name.
void rename (T name) noexcept
Static Public Member Functions
static uint32_t countInitialisationSteps () noexcept
Friends
class RenderTechniquePass
Additional Inherited Members
Protected Member Functions inherited from castor::OwnedBy< Engine >
OwnedBy (Engine &owner)
Constructor.
Protected Attributes inherited from castor::NamedBaseT< T >
T m_name
Member Typedef Documentation
ShadowMapArray
using castor3d::RenderTechnique::ShadowMapArray = castor::Vector< ShadowMapUPtr >
Constructor & Destructor Documentation
RenderTechnique()
C3D_API castor3d::RenderTechnique::RenderTechnique (castor::String const & name, RenderTarget & renderTarget, RenderDevice const & device, Texture const & colour, Texture const & intermediate, crg::FramePassArray previousPasses, ProgressBar * progress, bool visbuffer, bool weightedBlended)
Constructor.
Parameters
[in] name The technique name.
[in] renderTarget The render target for this technique.
[in] device The GPU device.
[in] colour The result colour image.
[in] intermediate The intermediate colour image.
[in] previousPasses The passes that the technique has to wait for.
[in] progress The optional progress bar.
[in] visbuffer true to enable visibility buffer.
[in] weightedBlended true to enable weighted blended rendering.
~RenderTechnique()
C3D_API castor3d::RenderTechnique::~RenderTechnique () noexcept
Destructor.
Member Function Documentation
accept()
C3D_API void castor3d::RenderTechnique::accept (RenderTechniqueVisitor & visitor)
Visitor acceptance function.
Parameters
visitor The ... visitor.
areDebugTargetsEnabled()
C3D_API bool castor3d::RenderTechnique::areDebugTargetsEnabled () const noexcept
countInitialisationSteps()
static uint32_t castor3d::RenderTechnique::countInitialisationSteps () static noexcept
Returns
The number of steps needed for initialisation, to show progression.
getCameraUbo() [1/2]
CameraUbo const & castor3d::RenderTechnique::getCameraUbo () const inline noexcept
getCameraUbo() [2/2]
CameraUbo & castor3d::RenderTechnique::getCameraUbo () inline noexcept
getClustersConfig()
C3D_API ClustersConfig const * castor3d::RenderTechnique::getClustersConfig () const
getCustomRenderPasses()
C3D_API TechniquePassVector castor3d::RenderTechnique::getCustomRenderPasses () const
getDebugConfig()
C3D_API DebugConfig & castor3d::RenderTechnique::getDebugConfig () const
getDepth()
Texture const & castor3d::RenderTechnique::getDepth () const inline noexcept
getDepthObj()
Texture const & castor3d::RenderTechnique::getDepthObj () const inline noexcept
References castor3d::PrepassRendering::getDepthObj().
getDepthRange()
ashes::Buffer< int32_t > const & castor3d::RenderTechnique::getDepthRange () const inline noexcept
References castor3d::PrepassRendering::getDepthRange().
getDepthRangePass()
crg::FramePass const & castor3d::RenderTechnique::getDepthRangePass () const inline noexcept
getDiffuse()
Texture const & castor3d::RenderTechnique::getDiffuse () const inline noexcept
getDirectionalShadowPassResult()
ShadowMapResult const & castor3d::RenderTechnique::getDirectionalShadowPassResult () const inline noexcept
getGetLastDepthPass()
crg::FramePass const & castor3d::RenderTechnique::getGetLastDepthPass () const inline noexcept
getGetLastOpaquePass()
crg::FramePass const & castor3d::RenderTechnique::getGetLastOpaquePass () const inline noexcept
getGetLastTransparentPass()
crg::FramePass const & castor3d::RenderTechnique::getGetLastTransparentPass () const inline noexcept
getGraph()
crg::FramePassGroup & castor3d::RenderTechnique::getGraph () inline noexcept
getIndirectLighting()
IndirectLightingData const & castor3d::RenderTechnique::getIndirectLighting () const inline noexcept
getIntermediate()
Texture const & castor3d::RenderTechnique::getIntermediate () const inline noexcept
getLastPass()
C3D_API crg::FramePass const & castor3d::RenderTechnique::getLastPass () const
name Getters.
getMaterialsCounts()
ashes::Buffer< uint32_t > const & castor3d::RenderTechnique::getMaterialsCounts () const inline noexcept
References castor3d::OpaqueRendering::getMaterialsCounts().
getMaterialsIndirectCounts()
ashes::Buffer< castor::Point3ui > const & castor3d::RenderTechnique::getMaterialsIndirectCounts () const inline noexcept
References castor3d::OpaqueRendering::getMaterialsIndirectCounts().
getMaterialsStarts()
ashes::Buffer< uint32_t > const & castor3d::RenderTechnique::getMaterialsStarts () const inline noexcept
References castor3d::OpaqueRendering::getMaterialsStarts().
getNormal()
Texture const & castor3d::RenderTechnique::getNormal () const inline noexcept
getPixelXY()
ashes::Buffer< castor::Point2ui > const & castor3d::RenderTechnique::getPixelXY () const inline noexcept
References castor3d::OpaqueRendering::getPixelXY().
getPointShadowPassResult()
ShadowMapResult const & castor3d::RenderTechnique::getPointShadowPassResult () const inline noexcept
getRenderTarget() [1/2]
RenderTarget const & castor3d::RenderTechnique::getRenderTarget () const inline noexcept
getRenderTarget() [2/2]
RenderTarget & castor3d::RenderTechnique::getRenderTarget () inline noexcept
getResources()
C3D_API crg::ResourcesCache & castor3d::RenderTechnique::getResources () const
getResult()
Texture const & castor3d::RenderTechnique::getResult () const inline noexcept
getSampledIntermediate()
crg::ImageViewIdArray castor3d::RenderTechnique::getSampledIntermediate () const inline noexcept
References castor3d::Texture::sampledViewId.
getSampledResult()
crg::ImageViewIdArray castor3d::RenderTechnique::getSampledResult () const inline noexcept
References castor3d::Texture::sampledViewId.
getScattering()
Texture const & castor3d::RenderTechnique::getScattering () const inline noexcept
getSceneUbo() [1/2]
SceneUbo const & castor3d::RenderTechnique::getSceneUbo () const inline noexcept
getSceneUbo() [2/2]
SceneUbo & castor3d::RenderTechnique::getSceneUbo () inline noexcept
getShadowBuffer()
ShadowBuffer & castor3d::RenderTechnique::getShadowBuffer () const inline noexcept
References CU_Require, and hasShadowBuffer().
getShadowMaps()
ShadowMapLightTypeArray const & castor3d::RenderTechnique::getShadowMaps () const inline noexcept
getSize()
castor::Size const & castor3d::RenderTechnique::getSize () const inline noexcept
getSpotShadowPassResult()
ShadowMapResult const & castor3d::RenderTechnique::getSpotShadowPassResult () const inline noexcept
getSsaoConfig() [1/2]
C3D_API SsaoConfig & castor3d::RenderTechnique::getSsaoConfig ()
getSsaoConfig() [2/2]
C3D_API SsaoConfig const & castor3d::RenderTechnique::getSsaoConfig () const
getSsaoResult()
C3D_API Texture const & castor3d::RenderTechnique::getSsaoResult () const
getSssDiffuse()
C3D_API Texture const & castor3d::RenderTechnique::getSssDiffuse () const
getTargetDepth()
crg::ImageViewIdArray castor3d::RenderTechnique::getTargetDepth () const inline noexcept
References castor3d::Texture::targetViewId.
getTargetExtent()
VkExtent3D const & castor3d::RenderTechnique::getTargetExtent () const inline noexcept
References castor3d::Texture::getExtent().
getTargetFormat()
VkFormat castor3d::RenderTechnique::getTargetFormat () const inline noexcept
References castor3d::Texture::getFormat().
getTargetIntermediate()
crg::ImageViewIdArray castor3d::RenderTechnique::getTargetIntermediate () const inline noexcept
References castor3d::Texture::targetViewId.
getTargetResult()
crg::ImageViewIdArray castor3d::RenderTechnique::getTargetResult () const inline noexcept
References castor3d::Texture::targetViewId.
getVisibilityResult()
Texture const & castor3d::RenderTechnique::getVisibilityResult () const inline noexcept
References castor3d::PrepassRendering::getVisibility().
hasShadowBuffer()
bool castor3d::RenderTechnique::hasShadowBuffer () const inline noexcept
Referenced by getShadowBuffer().
hasVisibility()
bool castor3d::RenderTechnique::hasVisibility () const inline noexcept
References castor3d::PrepassRendering::hasVisibility().
isMultisampling()
bool castor3d::RenderTechnique::isMultisampling () const inline noexcept
isOpaqueEnabled()
C3D_API bool castor3d::RenderTechnique::isOpaqueEnabled () const
preRender()
C3D_API crg::SemaphoreWaitArray castor3d::RenderTechnique::preRender (crg::SemaphoreWaitArray const & toWait, ashes::Queue const & queue)
Renders maps needed for the actual rendering.
Parameters
[in] toWait The semaphores to wait.
[in] queue The queue receiving the render commands.
Returns
The semaphores signaled by this render.
setNeedsDepthRange()
void castor3d::RenderTechnique::setNeedsDepthRange (bool v) inline noexcept
References castor3d::PrepassRendering::setNeedsDepthRange().
update() [1/2]
C3D_API void castor3d::RenderTechnique::update (CpuUpdater & updater)
Updates the render pass, CPU wise.
Parameters
[in,out] updater The update data.
update() [2/2]
C3D_API void castor3d::RenderTechnique::update (GpuUpdater & updater)
Updates the render pass, GPU wise.
Parameters
[in,out] updater The update data.
Friends And Related Symbol Documentation
RenderTechniquePass
friend class RenderTechniquePass friend
The documentation for this class was generated from the following file:
Castor3D/Render/RenderTechnique.hpp