Castor3D: castor3d::ControlStyle Class Reference
castor3d::ControlStyle Class Reference abstract
#include <StyleControl.hpp>
Public Member Functions
virtual C3D_API ~ControlStyle () noexcept=default
ControlStyle (ControlType type, castor::String const &name, Scene *scene, Engine &engine, MouseCursor cursor=MouseCursor::eArrow)
void setBackgroundMaterial (MaterialObs value)
void setForegroundMaterial (MaterialObs value)
void setCursor (MouseCursor value) noexcept
void setBackgroundInvisible (bool value) noexcept
void setForegroundInvisible (bool value) noexcept
bool isBackgroundInvisible () const noexcept
bool isForegroundInvisible () const noexcept
MaterialObs getBackgroundMaterial () const noexcept
MaterialObs getForegroundMaterial () const noexcept
ControlType getType () const noexcept
MouseCursor getCursor () const noexcept
Engine & getEngine () const noexcept
bool hasScene () const noexcept
Scene & getScene () const noexcept
Protected Member Functions
MaterialObs doCreateMaterial (MaterialObs material, float offset, castor::String const &suffix)
Constructor & Destructor Documentation
~ControlStyle()
virtual C3D_API castor3d::ControlStyle::~ControlStyle () virtual default noexcept
ControlStyle()
castor3d::ControlStyle::ControlStyle (ControlType type, castor::String const & name, Scene * scene, Engine & engine, MouseCursor cursor = MouseCursor::eArrow) inline
Member Function Documentation
doCreateMaterial()
MaterialObs castor3d::ControlStyle::doCreateMaterial (MaterialObs material, float offset, castor::String const & suffix) inline protected
References castor3d::createMaterial(), getEngine(), castor3d::getMaterialColour(), and castor3d::Material::getPass().
getBackgroundMaterial()
MaterialObs castor3d::ControlStyle::getBackgroundMaterial () const inline noexcept
getCursor()
MouseCursor castor3d::ControlStyle::getCursor () const inline noexcept
getEngine()
Engine & castor3d::ControlStyle::getEngine () const inline noexcept
Referenced by doCreateMaterial().
getForegroundMaterial()
MaterialObs castor3d::ControlStyle::getForegroundMaterial () const inline noexcept
getScene()
Scene & castor3d::ControlStyle::getScene () const inline noexcept
References hasScene().
getType()
ControlType castor3d::ControlStyle::getType () const inline noexcept
hasScene()
bool castor3d::ControlStyle::hasScene () const inline noexcept
Referenced by getScene().
isBackgroundInvisible()
bool castor3d::ControlStyle::isBackgroundInvisible () const inline noexcept
isForegroundInvisible()
bool castor3d::ControlStyle::isForegroundInvisible () const inline noexcept
setBackgroundInvisible()
void castor3d::ControlStyle::setBackgroundInvisible (bool value) inline noexcept
Referenced by castor3d::FrameStyle::FrameStyle().
setBackgroundMaterial()
void castor3d::ControlStyle::setBackgroundMaterial (MaterialObs value) inline
setCursor()
void castor3d::ControlStyle::setCursor (MouseCursor value) inline noexcept
setForegroundInvisible()
void castor3d::ControlStyle::setForegroundInvisible (bool value) inline noexcept
Referenced by castor3d::FrameStyle::FrameStyle().
setForegroundMaterial()
void castor3d::ControlStyle::setForegroundMaterial (MaterialObs value) inline
The documentation for this class was generated from the following file:
Gui/Theme/StyleControl.hpp