Castor3D: castor3d::VertexBuffer Class Reference
castor3d::VertexBuffer Class Reference
Vertex buffer representation.
Public Member Functions
C3D_API VertexBuffer (Engine &engine, BufferDeclaration const &declaration)
Constructor.
C3D_API ~VertexBuffer ()=default
Destructor.
C3D_API bool initialise (BufferAccessType type, BufferAccessNature nature)
Initialises the GPU buffer.
C3D_API void cleanup ()
Clean up the GPU buffer.
BufferDeclaration const & getDeclaration () const
template<typename ItType >
void linkCoords (ItType begin, ItType end)
Link all elements to this buffer.
Public Member Functions inherited from castor3d::CpuBuffer< uint8_t >
uint8_t * lock (uint32_t offset, uint32_t count, AccessTypes const &flags) const
Locks the buffer, id est maps it into memory so we can modify it.
void unlock () const
Unlocks the buffer, id est unmaps it from memory so no modification can be made after that.
void upload (uint32_t offset, uint32_t count, uint8_t const *buffer) const
Transfers data to the GPU buffer from RAM.
void upload () const
Transfers all the CPU buffer to GPU.
void download (uint32_t offset, uint32_t count, uint8_t *buffer)
Transfers data from the GPU buffer to RAM.
void download ()
Transfers all the GPU buffer to CPU.
void bind () const
Activation function, to tell the GPU it is active.
void unbind () const
Deactivation function, to tell the GPU it is inactive.
void copy (GpuBuffer const &src, uint32_t srcOffset, uint32_t size)
Copies data from given buffer to this one.
void copy (CpuBuffer< uint8_t > const &src, uint32_t size)
Copies data from given buffer to this one.
GpuBuffer const & getGpuBuffer () const
uint8_t const & operator[] (uint32_t index) const
Index opertor.
uint8_t & operator[] (uint32_t index)
Index opertor.
void addElement (uint8_t const &value)
adds a value at the end of the buffer.
uint32_t getSize () const
uint32_t isEmpty () const
void resize (uint32_t value)
sets the allocated size of the buffer.
void clear ()
Clears the buffer.
uint8_t const * getData () const
uint8_t * getData ()
auto begin ()
auto begin () const
auto end ()
auto end () const
uint32_t getOffset () const
Protected Attributes
BufferDeclaration m_bufferDeclaration
Protected Attributes inherited from castor3d::CpuBuffer< uint8_t >
GpuBufferSPtr m_gpuBuffer
TArray m_data
uint32_t m_offset
uint32_t m_savedSize
BufferAccessType m_accessType
BufferAccessNature m_accessNature
Additional Inherited Members
Protected Member Functions inherited from castor3d::CpuBuffer< uint8_t >
DECLARE_TPL_VECTOR (uint8_t, uint8_t)
CpuBuffer (Engine &engine)
Constructor.
~CpuBuffer ()
Destructor.
void doInitialise (BufferAccessType accessType, BufferAccessNature accessNature)
Detailed Description
Vertex buffer representation.
Author
Sylvain DOREMUS
Version
0.1
Date
09/02/2010
Remarks
Holds the submesh vertices informations
Constructor & Destructor Documentation
VertexBuffer()
C3D_API castor3d::VertexBuffer::VertexBuffer (Engine & engine, BufferDeclaration const & declaration)
Constructor.
Parameters
[in] engine The engine.
[in] declaration The buffer declaration.
~VertexBuffer()
C3D_API castor3d::VertexBuffer::~VertexBuffer () default
Destructor.
Member Function Documentation
cleanup()
C3D_API void castor3d::VertexBuffer::cleanup ()
Clean up the GPU buffer.
getDeclaration()
BufferDeclaration const& castor3d::VertexBuffer::getDeclaration () const inline
Returns
The buffer declaration.
References m_bufferDeclaration.
initialise()
C3D_API bool castor3d::VertexBuffer::initialise (BufferAccessType type, BufferAccessNature nature)
Initialises the GPU buffer.
Parameters
[in] type Buffer access type.
[in] nature Buffer access nature.
Returns
true if OK.
linkCoords()
template<typename ItType > void castor3d::VertexBuffer::linkCoords (ItType begin, ItType end) inline
Link all elements to this buffer.
Parameters
[in] begin,end The elements array iterators.
References castor3d::CpuBuffer< uint8_t >::begin(), castor3d::CpuBuffer< uint8_t >::end(), castor3d::CpuBuffer< T >::getData(), m_bufferDeclaration, and castor3d::BufferDeclaration::stride().
Member Data Documentation
m_bufferDeclaration
BufferDeclaration castor3d::VertexBuffer::m_bufferDeclaration protected
Buffer elements description.
Referenced by getDeclaration(), and linkCoords().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Mesh/Buffer/VertexBuffer.hpp