Castor3D: castor3d::HeightComponent Struct Reference
castor3d::HeightComponent Struct Reference
#include <HeightComponent.hpp>
Classes
struct ComponentsShader
class Plugin
Public Member Functions
C3D_API HeightComponent (Pass &pass)
C3D_API void accept (ConfigurationVisitorBase &vis) override
ConfigurationVisitorBase acceptance function.
C3D_API PassComponentFlag getPassFlags () const override
void setParallaxOcclusion (ParallaxOcclusionMode v)
ParallaxOcclusionMode getParallaxOcclusion () const
bool hasParallaxOcclusion () const
Public Member Functions inherited from castor3d::BaseDataPassComponentT< castor::AtomicGroupChangeTracked< ParallaxOcclusionMode > >
BaseDataPassComponentT (Pass &pass, castor::String type, castor::StringArray deps={}, ParamsT &&... params)
Constructor.
void setData (DataU const &data)
void setData (ParamsT &&... params)
castor::AtomicGroupChangeTracked< ParallaxOcclusionMode > & getData ()
castor::AtomicGroupChangeTracked< ParallaxOcclusionMode > const & getData () const
Public Member Functions inherited from castor3d::PassComponent
C3D_API PassComponent (Pass &pass, castor::String type, castor::StringArray deps={})
Constructor.
virtual C3D_API ~PassComponent () noexcept=default
C3D_API PassComponentUPtr clone (Pass &pass) const
virtual C3D_API void onAddToPass () const
Called when the component is added to the pass.
C3D_API bool writeText (castor::String const &tabs, castor::Path const &folder, castor::String const &subfolder, castor::StringStream &file) const
Writes the component content to text.
C3D_API void fillBuffer (PassBuffer &buffer) const
Fills the pass buffer with this pass data.
virtual C3D_API void update ()
C3D_API void fillChannel (TextureConfiguration &configuration, uint32_t mask) const
Fills the texture configuration for use with this component.
virtual C3D_API void fillConfig (TextureConfiguration &config, ConfigurationVisitorBase &vis) const
ConfigurationVisitorBase acceptance function, for a specific texture configuration.
virtual C3D_API bool hasColour () const
virtual C3D_API castor::HdrRgbColour const & getColour () const
virtual C3D_API void setColour (castor::HdrRgbColour v)
castor::String const & getType () const
castor::StringArray const & getDependencies () const
PassComponentPlugin const & getPlugin () const
PassComponentID getId () const
void setColour (castor::RgbColour const &v, float gamma=2.2f)
void setColour (castor::Coords3f const &v)
void setColour (castor::Point3f const &v)
Public Member Functions inherited from castor::OwnedBy< Pass >
Pass * getOwner () const
Static Public Member Functions
static PassComponentPluginUPtr createPlugin (PassComponentRegister const &passComponent)
Static Public Attributes
static constexpr PassFlag eParallaxOcclusionMappingOne = PassFlag(0x01u)
static constexpr PassFlag eParallaxOcclusionMappingRepeat = PassFlag(0x02u)
static constexpr PassFlag eAll = PassFlag(0x03u)
static C3D_API castor::String const TypeName
Additional Inherited Members
Protected Member Functions inherited from castor::OwnedBy< Pass >
OwnedBy (Pass &owner)
Constructor.
Protected Attributes inherited from castor3d::BaseDataPassComponentT< castor::AtomicGroupChangeTracked< ParallaxOcclusionMode > >
castor::AtomicGroupChangeTracked< ParallaxOcclusionMode > m_value
Protected Attributes inherited from castor3d::PassComponent
castor::String m_type
castor::StringArray m_dependencies
PassComponentID m_id
PassComponentPlugin const & m_plugin
std::atomic_bool & m_dirty
shader::PassMaterialShader * m_materialShader {}
Constructor & Destructor Documentation
HeightComponent()
C3D_API castor3d::HeightComponent::HeightComponent (Pass & pass) explicit
Member Function Documentation
accept()
C3D_API void castor3d::HeightComponent::accept (ConfigurationVisitorBase & vis) override virtual
ConfigurationVisitorBase acceptance function.
Parameters
vis The ... visitor.
Reimplemented from castor3d::PassComponent.
createPlugin()
static PassComponentPluginUPtr castor3d::HeightComponent::createPlugin (PassComponentRegister const & passComponent) inline static
getParallaxOcclusion()
ParallaxOcclusionMode castor3d::HeightComponent::getParallaxOcclusion () const inline
References castor3d::BaseDataPassComponentT< castor::AtomicGroupChangeTracked< ParallaxOcclusionMode > >::getData().
Referenced by getPassFlags(), and hasParallaxOcclusion().
getPassFlags()
C3D_API PassComponentFlag castor3d::HeightComponent::getPassFlags () const inline override virtual
Reimplemented from castor3d::PassComponent.
References castor3d::eNone, castor3d::eOne, eParallaxOcclusionMappingOne, eParallaxOcclusionMappingRepeat, castor3d::eRepeat, castor3d::PassComponent::getId(), getParallaxOcclusion(), and castor3d::makePassComponentFlag().
hasParallaxOcclusion()
bool castor3d::HeightComponent::hasParallaxOcclusion () const inline
References castor3d::eNone, and getParallaxOcclusion().
setParallaxOcclusion()
void castor3d::HeightComponent::setParallaxOcclusion (ParallaxOcclusionMode v) inline
References castor3d::BaseDataPassComponentT< castor::AtomicGroupChangeTracked< ParallaxOcclusionMode > >::setData().
Member Data Documentation
eAll
constexpr PassFlag castor3d::HeightComponent::eAll = PassFlag(0x03u) static constexpr
Referenced by castor3d::HeightComponent::Plugin::getComponentFlags().
eParallaxOcclusionMappingOne
constexpr PassFlag castor3d::HeightComponent::eParallaxOcclusionMappingOne = PassFlag(0x01u) static constexpr
Referenced by castor3d::HeightComponent::Plugin::getParallaxOcclusionMappingOneFlag(), and getPassFlags().
eParallaxOcclusionMappingRepeat
constexpr PassFlag castor3d::HeightComponent::eParallaxOcclusionMappingRepeat = PassFlag(0x02u) static constexpr
Referenced by castor3d::HeightComponent::Plugin::getParallaxOcclusionMappingRepeatFlag(), and getPassFlags().
TypeName
C3D_API castor::String const castor3d::HeightComponent::TypeName static
The documentation for this struct was generated from the following file:
Castor3D/Material/Pass/Component/Other/HeightComponent.hpp