Castor3D: castor3d::ChunkWriter< T > Class Template Reference
castor3d::ChunkWriter< T > Class Template Reference
Chunk data writer.
Static Public Member Functions
static bool write (T const *p_begin, T const *p_end, ChunkType p_type, BinaryChunk &p_chunk)
Writes a subchunk value into a chunk.
static bool write (T const &p_value, ChunkType p_type, BinaryChunk &p_chunk)
Writes a subchunk value into a chunk.
Static Public Member Functions inherited from castor3d::ChunkWriterBase
static bool write (uint8_t const *p_begin, uint8_t const *p_end, ChunkType p_type, BinaryChunk &p_chunk)
Writes a subchunk value into a chunk.
Detailed Description
template<typename T>
class castor3d::ChunkWriter< T >
Chunk data writer.
Author
Sylvain DOREMUS
Version
0.9.0
Date
30/05/2016
Member Function Documentation
write() [1/2]
template<typename T > static bool castor3d::ChunkWriter< T >::write (T const * p_begin, T const * p_end, ChunkType p_type, BinaryChunk & p_chunk) inline static
Writes a subchunk value into a chunk.
Parameters
[in] p_begin The values begin
[in] p_end The values end
[in] p_type The subchunk type
[in] p_chunk The chunk
Returns
false if any error occured
References castor3d::prepareChunkData(), and castor3d::ChunkWriterBase::write().
Referenced by castor3d::BinaryWriterBase< Skeleton >::doWriteChunk().
write() [2/2]
template<typename T > static bool castor3d::ChunkWriter< T >::write (T const & p_value, ChunkType p_type, BinaryChunk & p_chunk) inline static
Writes a subchunk value into a chunk.
Parameters
[in] p_value The value
[in] p_type The subchunk type
[in] p_chunk The chunk
Returns
false if any error occured
References castor3d::getBuffer(), castor3d::getDataSize(), castor3d::prepareChunkData(), and castor3d::ChunkWriterBase::write().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Binary/ChunkWriter.hpp