Castor3D: castor3d::Theme Class Reference
castor3d::Theme Class Reference
#include <Theme.hpp>
Public Member Functions
Theme (castor::String const &name, Scene *scene, Engine &engine)
Theme (castor::String const &name, Engine &engine)
auto & getName () const noexcept
bool hasScene () const noexcept
Scene & getScene () const noexcept
Public Member Functions inherited from castor3d::StylesHolder
virtual C3D_API ~StylesHolder () noexcept=default
StylesHolder (castor::String name, Engine &engine)
castor::FontResPtr getDefaultFont () const
Retrieves the default font used by controls.
void setDefaultFont (castor::FontResPtr font)
sets the default font used by controls
C3D_API ButtonStyleRPtr createButtonStyle (castor::String name, Scene *scene)
C3D_API ComboBoxStyleRPtr createComboBoxStyle (castor::String name, Scene *scene)
C3D_API EditStyleRPtr createEditStyle (castor::String name, Scene *scene)
C3D_API ExpandablePanelStyleRPtr createExpandablePanelStyle (castor::String name, Scene *scene)
C3D_API FrameStyleRPtr createFrameStyle (castor::String name, Scene *scene)
C3D_API ListBoxStyleRPtr createListBoxStyle (castor::String name, Scene *scene)
C3D_API PanelStyleRPtr createPanelStyle (castor::String name, Scene *scene)
C3D_API ProgressStyleRPtr createProgressStyle (castor::String name, Scene *scene)
C3D_API ScrollBarStyleRPtr createScrollBarStyle (castor::String name, Scene *scene)
C3D_API SliderStyleRPtr createSliderStyle (castor::String name, Scene *scene)
C3D_API StaticStyleRPtr createStaticStyle (castor::String name, Scene *scene)
virtual C3D_API ButtonStyleRPtr getButtonStyle (castor::String const &name) const
virtual C3D_API ComboBoxStyleRPtr getComboBoxStyle (castor::String const &name) const
virtual C3D_API EditStyleRPtr getEditStyle (castor::String const &name) const
virtual C3D_API ExpandablePanelStyleRPtr getExpandablePanelStyle (castor::String const &name) const
virtual C3D_API FrameStyleRPtr getFrameStyle (castor::String const &name) const
virtual C3D_API ListBoxStyleRPtr getListBoxStyle (castor::String const &name) const
virtual C3D_API PanelStyleRPtr getPanelStyle (castor::String const &name) const
virtual C3D_API ProgressStyleRPtr getProgressStyle (castor::String const &name) const
virtual C3D_API ScrollBarStyleRPtr getScrollBarStyle (castor::String const &name) const
virtual C3D_API SliderStyleRPtr getSliderStyle (castor::String const &name) const
virtual C3D_API StaticStyleRPtr getStaticStyle (castor::String const &name) const
template<typename StyleT >
StyleT * getStyle (castor::String const &name) const
auto & getButtonStyles () const noexcept
auto & getComboBoxStyles () const noexcept
auto & getEditStyles () const noexcept
auto & getExpandablePanelStyles () const noexcept
auto & getFrameStyles () const noexcept
auto & getListBoxStyles () const noexcept
auto & getPanelStyles () const noexcept
auto & getProgressStyles () const noexcept
auto & getScrollBarStyles () const noexcept
auto & getSliderStyles () const noexcept
auto & getStaticStyles () const noexcept
Additional Inherited Members
Protected Member Functions inherited from castor3d::StylesHolder
auto & getHolderName () const noexcept
void cleanupStyles () noexcept
Constructor & Destructor Documentation
Theme() [1/2]
castor3d::Theme::Theme (castor::String const & name, Scene * scene, Engine & engine) inline
Theme() [2/2]
castor3d::Theme::Theme (castor::String const & name, Engine & engine) inline
Member Function Documentation
getName()
auto & castor3d::Theme::getName () const inline noexcept
References castor3d::StylesHolder::getHolderName().
getScene()
Scene & castor3d::Theme::getScene () const inline noexcept
References hasScene().
hasScene()
bool castor3d::Theme::hasScene () const inline noexcept
Referenced by getScene().
The documentation for this class was generated from the following file:
Gui/Theme/Theme.hpp