Castor3D: castor::DynamicLibrary Class Reference
castor::DynamicLibrary Class Reference
#include <DynamicLibrary.hpp>
Public Member Functions
CU_API DynamicLibrary (Path const &pathFile) noexcept
Constructor, loads the library.
CU_API DynamicLibrary (String const &pathFile) noexcept
Constructor, loads the library.
CU_API DynamicLibrary (DynamicLibrary const &lib) noexcept
Copy constructor.
CU_API DynamicLibrary (DynamicLibrary &&lib) noexcept
Move constructor.
CU_API ~DynamicLibrary () noexcept
Destructor.
CU_API DynamicLibrary & operator= (DynamicLibrary const &lib)
Copy assignment operator.
CU_API DynamicLibrary & operator= (DynamicLibrary &&lib) noexcept
Move assignment operator.
template<typename FuncType >
bool getFunction (FuncType &function, char const *name) noexcept
Retrieves a function.
template<typename FuncType >
bool getFunction (FuncType &function, wchar_t const *name) noexcept
Retrieves a function.
template<typename FuncType >
bool getFunction (FuncType &function, String const &name) noexcept
Retrieves a function.
template<typename FuncType >
bool getFunction (char const *name, FuncType &function) noexcept
Retrieves a function.
template<typename FuncType >
bool getFunction (wchar_t const *name, FuncType &function) noexcept
Retrieves a function.
template<typename FuncType >
bool getFunction (String const &name, FuncType &function) noexcept
Retrieves a function.
bool isOpen () const
Tells if the DynamicLibrary is opened (loaded)
Path const & getPath () const
Retrieves the file path.
Constructor & Destructor Documentation
DynamicLibrary() [1/4]
CU_API castor::DynamicLibrary::DynamicLibrary (Path const & pathFile) explicit noexcept
Constructor, loads the library.
Parameters
[in] pathFile The file path
DynamicLibrary() [2/4]
CU_API castor::DynamicLibrary::DynamicLibrary (String const & pathFile) explicit noexcept
Constructor, loads the library.
Parameters
[in] pathFile The file path
DynamicLibrary() [3/4]
CU_API castor::DynamicLibrary::DynamicLibrary (DynamicLibrary const & lib) noexcept
Copy constructor.
Parameters
[in] lib The DynamicLibrary to copy
DynamicLibrary() [4/4]
CU_API castor::DynamicLibrary::DynamicLibrary (DynamicLibrary && lib) noexcept
Move constructor.
Parameters
[in] lib The DynamicLibrary to move
~DynamicLibrary()
CU_API castor::DynamicLibrary::~DynamicLibrary () noexcept
Destructor.
Member Function Documentation
getFunction() [1/6]
template<typename FuncType > bool castor::DynamicLibrary::getFunction (char const * name, FuncType & function) inline noexcept
Retrieves a function.
Parameters
[in] function Receives the function
[in] name The function name
Returns
true if the function was correctly retrieved
References getFunction(), and castor::makeString().
getFunction() [2/6]
template<typename FuncType > bool castor::DynamicLibrary::getFunction (FuncType & function, char const * name) inline noexcept
Retrieves a function.
Parameters
[in] function Receives the function
[in] name The function name
Returns
true if the function was correctly retrieved
References getFunction(), and castor::makeString().
Referenced by getFunction(), getFunction(), getFunction(), and getFunction().
getFunction() [3/6]
template<typename FuncType > bool castor::DynamicLibrary::getFunction (FuncType & function, String const & name) inline noexcept
Retrieves a function.
Parameters
[in] function Receives the function
[in] name The function name
Returns
true if the function was correctly retrieved
getFunction() [4/6]
template<typename FuncType > bool castor::DynamicLibrary::getFunction (FuncType & function, wchar_t const * name) inline noexcept
Retrieves a function.
Parameters
[in] function Receives the function
[in] name The function name
Returns
true if the function was correctly retrieved
References getFunction(), and castor::makeString().
getFunction() [5/6]
template<typename FuncType > bool castor::DynamicLibrary::getFunction (String const & name, FuncType & function) inline noexcept
Retrieves a function.
Parameters
[in] function Receives the function
[in] name The function name
Returns
true if the function was correctly retrieved
getFunction() [6/6]
template<typename FuncType > bool castor::DynamicLibrary::getFunction (wchar_t const * name, FuncType & function) inline noexcept
Retrieves a function.
Parameters
[in] function Receives the function
[in] name The function name
Returns
true if the function was correctly retrieved
References getFunction(), and castor::makeString().
getPath()
Path const & castor::DynamicLibrary::getPath () const inline
Retrieves the file path.
Returns
The file path
isOpen()
bool castor::DynamicLibrary::isOpen () const inline
Tells if the DynamicLibrary is opened (loaded)
Returns
true if it is opened, false if not
operator=() [1/2]
CU_API DynamicLibrary & castor::DynamicLibrary::operator= (DynamicLibrary && lib) noexcept
Move assignment operator.
Parameters
[in] lib The DynamicLibrary to move
Returns
A reference to this DynamicLibrary
operator=() [2/2]
CU_API DynamicLibrary & castor::DynamicLibrary::operator= (DynamicLibrary const & lib)
Copy assignment operator.
Parameters
[in] lib The DynamicLibrary to copy
Returns
A reference to this DynamicLibrary
The documentation for this class was generated from the following file:
CastorUtils/Miscellaneous/DynamicLibrary.hpp