Castor3D: castor3d::BinaryWriterBase< TWritten > Class Template Reference
castor3d::BinaryWriterBase< TWritten > Class Template Reference abstract
Binary data chunk writer base class.
#include <BinaryWriter.hpp>
Public Member Functions
virtual ~BinaryWriterBase ()=default
bool write (TWritten const &obj, castor::BinaryFile &file)
Writes an object to a file.
bool write (TWritten const &obj, BinaryChunk &chunk)
To chunk writer function.
Protected Member Functions
bool doWriteHeader (BinaryChunk &chunk) const
Writes the header chunk.
template<typename T >
bool doWriteChunk (T const *values, size_t count, ChunkType chunkType, BinaryChunk &chunk) const
Writes a subchunk value into a chunk.
template<typename T , size_t Count>
bool doWriteChunk (T const(&values)[Count], ChunkType chunkType, BinaryChunk &chunk) const
Writes a subchunk value into a chunk.
template<typename T , size_t Count>
bool doWriteChunk (castor::Array< T, Count > const &values, ChunkType chunkType, BinaryChunk &chunk) const
Writes a subchunk value into a chunk.
template<typename T >
bool doWriteChunk (castor::Vector< T > const &values, ChunkType chunkType, BinaryChunk &chunk) const
Writes a subchunk value into a chunk.
template<typename T >
bool doWriteChunk (T const *begin, T const *end, ChunkType chunkType, BinaryChunk &chunk) const
Writes a subchunk value into a chunk.
template<typename T >
bool doWriteChunk (T const &value, ChunkType chunkType, BinaryChunk &chunk) const
Writes a subchunk value into a chunk.
Protected Attributes
BinaryChunk m_chunk { ChunkTyper< TWritten >::Value }
Detailed Description
template<class TWritten>
class castor3d::BinaryWriterBase< TWritten >
Binary data chunk writer base class.
Constructor & Destructor Documentation
~BinaryWriterBase()
template<class TWritten > virtual castor3d::BinaryWriterBase< TWritten >::~BinaryWriterBase () virtual default
Member Function Documentation
doWriteChunk() [1/6]
template<class TWritten > template<typename T , size_t Count> bool castor3d::BinaryWriterBase< TWritten >::doWriteChunk (castor::Array< T, Count > const & values, ChunkType chunkType, BinaryChunk & chunk) const inline protected
Writes a subchunk value into a chunk.
Parameters
[in] values The values.
[in] chunkType The subchunk type.
[in,out] chunk The chunk.
Returns
false if any error occured.
References castor3d::ChunkWriter< T >::write().
doWriteChunk() [2/6]
template<class TWritten > template<typename T > bool castor3d::BinaryWriterBase< TWritten >::doWriteChunk (castor::Vector< T > const & values, ChunkType chunkType, BinaryChunk & chunk) const inline protected
Writes a subchunk value into a chunk.
Parameters
[in] values The values.
[in] chunkType The subchunk type.
[in,out] chunk The chunk.
Returns
false if any error occured.
References castor3d::ChunkWriter< T >::write().
doWriteChunk() [3/6]
template<class TWritten > template<typename T > bool castor3d::BinaryWriterBase< TWritten >::doWriteChunk (T const & value, ChunkType chunkType, BinaryChunk & chunk) const inline protected
Writes a subchunk value into a chunk.
Parameters
[in] value The value.
[in] chunkType The subchunk type.
[in,out] chunk The chunk.
Returns
false if any error occured.
References castor3d::ChunkWriter< T >::write().
doWriteChunk() [4/6]
template<class TWritten > template<typename T > bool castor3d::BinaryWriterBase< TWritten >::doWriteChunk (T const * begin, T const * end, ChunkType chunkType, BinaryChunk & chunk) const inline protected
Writes a subchunk value into a chunk.
Parameters
[in] begin The values begin.
[in] end The values end.
[in] chunkType The subchunk type.
[in,out] chunk The chunk.
Returns
false if any error occured.
References castor3d::ChunkWriter< T >::write().
doWriteChunk() [5/6]
template<class TWritten > template<typename T > bool castor3d::BinaryWriterBase< TWritten >::doWriteChunk (T const * values, size_t count, ChunkType chunkType, BinaryChunk & chunk) const inline protected
Writes a subchunk value into a chunk.
Parameters
[in] values The values.
[in] count The values count.
[in] chunkType The subchunk type.
[in,out] chunk The chunk.
Returns
false if any error occured.
References castor3d::ChunkWriter< T >::write().
Referenced by castor3d::BinaryWriterBase< TWritten >::doWriteHeader().
doWriteChunk() [6/6]
template<class TWritten > template<typename T , size_t Count> bool castor3d::BinaryWriterBase< TWritten >::doWriteChunk (T const(&) values[Count], ChunkType chunkType, BinaryChunk & chunk) const inline protected
Writes a subchunk value into a chunk.
Parameters
[in] values The values.
[in] chunkType The subchunk type.
[in,out] chunk The chunk.
Returns
false if any error occured.
References castor3d::ChunkWriter< T >::write().
doWriteHeader()
template<class TWritten > bool castor3d::BinaryWriterBase< TWritten >::doWriteHeader (BinaryChunk & chunk) const inline protected
Writes the header chunk.
Parameters
[in,out] chunk The parent chunk.
Returns
false if any error occured.
References castor3d::BinaryChunk::addSubChunk(), castor3d::CurrentCmshVersion, cuT, castor3d::BinaryWriterBase< TWritten >::doWriteChunk(), castor3d::eCmshHeader, castor3d::eCmshVersion, castor3d::eName, and castor::makeStringStream().
Referenced by castor3d::BinaryWriterBase< TWritten >::write().
write() [1/2]
template<class TWritten > bool castor3d::BinaryWriterBase< TWritten >::write (TWritten const & obj, BinaryChunk & chunk) inline
To chunk writer function.
Parameters
[in] obj The object to write.
[in,out] chunk The chunk.
Returns
false if any error occured.
References castor3d::BinaryChunk::addSubChunk(), castor3d::BinaryChunk::finalise(), and castor3d::BinaryWriterBase< TWritten >::m_chunk.
write() [2/2]
template<class TWritten > bool castor3d::BinaryWriterBase< TWritten >::write (TWritten const & obj, castor::BinaryFile & file) inline
Writes an object to a file.
Parameters
[in] obj The object to write.
[in,out] file The file.
Returns
false if any error occured.
References castor3d::BinaryWriterBase< TWritten >::doWriteHeader(), castor3d::eCmshFile, and castor3d::BinaryWriterBase< TWritten >::write().
Referenced by castor3d::BinaryWriterBase< TWritten >::write().
Member Data Documentation
m_chunk
template<class TWritten > BinaryChunk castor3d::BinaryWriterBase< TWritten >::m_chunk { ChunkTyper< TWritten >::Value } protected
The writer's chunk.
Referenced by castor3d::BinaryWriterBase< TWritten >::write().
The documentation for this class was generated from the following files:
Castor3D/Binary/BinaryModule.hpp
Castor3D/Binary/BinaryWriter.hpp