Castor3D: castor::ConnectionT< MySignalT > Class Template Reference
castor::ConnectionT< MySignalT > Class Template Reference
Connection to a signal.
#include <Signal.hpp>
Public Member Functions
ConnectionT ()
Constructor.
ConnectionT (uint32_t connection, signal_type &signal)
Constructor.
ConnectionT (ConnectionT< signal_type > &&rhs) noexcept
Move constructor.
ConnectionT & operator= (ConnectionT< signal_type > &&rhs) noexcept
Move assignment operator.
~ConnectionT () noexcept
Destructor.
bool disconnect () noexcept
Disconnects the function from the signal.
operator bool () const noexcept
Additional Inherited Members
Protected Member Functions inherited from castor::NonCopyable
NonCopyable ()=default
Constructor.
~NonCopyable () noexcept=default
Destructor.
Detailed Description
template<typename MySignalT>
class castor::ConnectionT< MySignalT >
Connection to a signal.
Constructor & Destructor Documentation
ConnectionT() [1/3]
template<typename MySignalT > castor::ConnectionT< MySignalT >::ConnectionT () inline
Constructor.
ConnectionT() [2/3]
template<typename MySignalT > castor::ConnectionT< MySignalT >::ConnectionT (uint32_t connection, signal_type & signal) inline
Constructor.
Parameters
[in] connection The connection to the signal.
[in] signal The signal.
References castor::makeStringStream().
ConnectionT() [3/3]
template<typename MySignalT > castor::ConnectionT< MySignalT >::ConnectionT (ConnectionT< signal_type > && rhs) inline noexcept
Move constructor.
Parameters
[in,out] rhs The object to move.
~ConnectionT()
template<typename MySignalT > castor::ConnectionT< MySignalT >::~ConnectionT () inline noexcept
Destructor.
Remarks
Disconnects the function from the signal.
References castor::ConnectionT< MySignalT >::disconnect().
Member Function Documentation
disconnect()
template<typename MySignalT > bool castor::ConnectionT< MySignalT >::disconnect () inline noexcept
Disconnects the function from the signal.
Referenced by castor::ConnectionT< MySignalT >::operator=(), and castor::ConnectionT< MySignalT >::~ConnectionT().
operator bool()
template<typename MySignalT > castor::ConnectionT< MySignalT >::operator bool () const inline noexcept
operator=()
template<typename MySignalT > ConnectionT & castor::ConnectionT< MySignalT >::operator= (ConnectionT< signal_type > && rhs) inline noexcept
Move assignment operator.
Parameters
[in,out] rhs The object to move.
References castor::ConnectionT< MySignalT >::disconnect().
The documentation for this class was generated from the following files:
CastorUtils/Design/DesignModule.hpp
CastorUtils/Design/Signal.hpp