Castor3D: castor3d::ChunkParserBase Class Reference
castor3d::ChunkParserBase Class Reference
Chunk parser.
Static Public Member Functions
static bool parse (uint8_t *p_values, size_t p_size, BinaryChunk &p_chunk)
Retrieves a value array from a chunk.
Detailed Description
Chunk parser.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
08/04/2014
Member Function Documentation
parse()
static bool castor3d::ChunkParserBase::parse (uint8_t * p_values, size_t p_size, BinaryChunk & p_chunk) inline static
Retrieves a value array from a chunk.
Parameters
[out] p_values Receives the parsed values
[out] p_size The values size
[in] p_chunk The chunk containing the values
Returns
false if any error occured
References castor3d::BinaryChunk::checkAvailable(), and castor3d::BinaryChunk::get().
Referenced by castor3d::ChunkParser< T >::parse(), castor3d::ChunkParser< castor::String >::parse(), and castor3d::ChunkParser< castor::Path >::parse().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Binary/ChunkParser.hpp