Castor3D: Castor3D::BinaryParserBase< TParsed > Class Template Reference
Castor3D::BinaryParserBase< TParsed > Class Template Reference abstract
Binary data chunk writer/reader base class.
Public Member Functions
bool Parse (TParsed &p_obj, Castor::BinaryFile &p_file)
From file reader function.
bool Parse (TParsed &p_obj, BinaryChunk &p_chunk)
From chunk reader function.
Protected Member Functions
bool DoParseHeader (BinaryChunk &p_chunk) const
Parses the header chunk.
template<typename T >
bool DoParseChunk (T *p_values, size_t p_count, BinaryChunk &p_chunk) const
Retrieves a value array from a chunk.
template<typename T , size_t Count>
bool DoParseChunk (T(&p_values)[Count], BinaryChunk &p_chunk) const
Retrieves a value array from a chunk.
template<typename T , size_t Count>
bool DoParseChunk (std::array< T, Count > &p_values, BinaryChunk &p_chunk) const
Retrieves a value array from a chunk.
template<typename T >
bool DoParseChunk (std::vector< T > &p_values, BinaryChunk &p_chunk) const
Retrieves a value array from a chunk.
template<typename T >
bool DoParseChunk (T &p_value, BinaryChunk &p_chunk) const
Retrieves a value from a chunk.
bool DoGetSubChunk (BinaryChunk &p_chunk)
Retrieves a subchunk.
Protected Attributes
BinaryChunk * m_chunk { nullptr }
Detailed Description
template<class TParsed>
class Castor3D::BinaryParserBase< TParsed >
Binary data chunk writer/reader base class.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
15/04/2013
Member Function Documentation
DoGetSubChunk()
template<class TParsed> bool Castor3D::BinaryParserBase< TParsed >::DoGetSubChunk (BinaryChunk & p_chunk) inline protected
Retrieves a subchunk.
Parameters
[out] p_chunk Receives the subchunk.
Returns
false if any error occured.
DoParseChunk() [1/5]
template<class TParsed> template<typename T > bool Castor3D::BinaryParserBase< TParsed >::DoParseChunk (T * p_values, size_t p_count, BinaryChunk & p_chunk) const inline protected
Retrieves a value array from a chunk.
Parameters
[out] p_values Receives the parsed values
[out] p_count The values count
[in] p_chunk The chunk containing the values
Returns
false if any error occured
Referenced by Castor3D::BinaryParserBase< Skeleton >::DoParseHeader().
DoParseChunk() [2/5]
template<class TParsed> template<typename T , size_t Count> bool Castor3D::BinaryParserBase< TParsed >::DoParseChunk (T(&) p_values[Count], BinaryChunk & p_chunk) const inline protected
Retrieves a value array from a chunk.
Parameters
[out] p_values Receives the parsed values
[in] p_chunk The chunk containing the values
Returns
false if any error occured
DoParseChunk() [3/5]
template<class TParsed> template<typename T , size_t Count> bool Castor3D::BinaryParserBase< TParsed >::DoParseChunk (std::array< T, Count > & p_values, BinaryChunk & p_chunk) const inline protected
Retrieves a value array from a chunk.
Parameters
[out] p_values Receives the parsed values
[in] p_chunk The chunk containing the values
Returns
false if any error occured
DoParseChunk() [4/5]
template<class TParsed> template<typename T > bool Castor3D::BinaryParserBase< TParsed >::DoParseChunk (std::vector< T > & p_values, BinaryChunk & p_chunk) const inline protected
Retrieves a value array from a chunk.
Parameters
[out] p_values Receives the parsed values
[in] p_chunk The chunk containing the values
Returns
false if any error occured
DoParseChunk() [5/5]
template<class TParsed> template<typename T > bool Castor3D::BinaryParserBase< TParsed >::DoParseChunk (T & p_value, BinaryChunk & p_chunk) const inline protected
Retrieves a value from a chunk.
Parameters
[out] p_value Receives the parsed value
[in] p_chunk The chunk containing the value
Returns
false if any error occured
DoParseHeader()
template<class TParsed> bool Castor3D::BinaryParserBase< TParsed >::DoParseHeader (BinaryChunk & p_chunk) const inline protected
Parses the header chunk.
Parameters
[in,out] p_chunk The parent chunk.
Returns
false if any error occured.
Referenced by Castor3D::BinaryParserBase< Skeleton >::Parse().
Parse() [1/2]
template<class TParsed> bool Castor3D::BinaryParserBase< TParsed >::Parse (TParsed & p_obj, Castor::BinaryFile & p_file) inline
From file reader function.
Parameters
[out] p_obj The object to read
[in] p_file The file containing the chunk
Returns
false if any error occured
Referenced by Castor3D::BinaryParserBase< Skeleton >::Parse().
Parse() [2/2]
template<class TParsed> bool Castor3D::BinaryParserBase< TParsed >::Parse (TParsed & p_obj, BinaryChunk & p_chunk) inline
From chunk reader function.
Parameters
[out] p_obj The object to read
[in] p_chunk The chunk
Returns
false if any error occured
Member Data Documentation
m_chunk
template<class TParsed> BinaryChunk* Castor3D::BinaryParserBase< TParsed >::m_chunk { nullptr } protected
The writer's chunk.
Referenced by Castor3D::BinaryParserBase< Skeleton >::DoGetSubChunk(), and Castor3D::BinaryParserBase< Skeleton >::Parse().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Binary/BinaryParser.hpp