Castor3D: castor3d::IblTextures Class Reference
castor3d::IblTextures Class Reference
#include <IblTextures.hpp>
Public Member Functions
C3D_API IblTextures (Scene &scene, RenderDevice const &device, Texture const &source, Texture const &brdf, SamplerObs sampler)
Constructor.
C3D_API void update (QueueData const &queueData)
Updates the environment maps.
C3D_API crg::SemaphoreWaitArray update (crg::SemaphoreWaitArray signalsToWait, ashes::Queue const &queue) const
Updates the environment maps.
Texture const & getIrradianceTexture () const noexcept
Texture const & getPrefilteredEnvironmentTexture () const noexcept
Texture const & getPrefilteredEnvironmentSheenTexture () const noexcept
Texture const & getPrefilteredBrdfTexture () const noexcept
ashes::Sampler const & getIrradianceSampler () const noexcept
ashes::Sampler const & getPrefilteredEnvironmentSampler () const noexcept
ashes::Sampler const & getPrefilteredEnvironmentSheenSampler () const noexcept
ashes::Sampler const & getPrefilteredBrdfSampler () const noexcept
Public Member Functions inherited from castor::OwnedBy< Scene >
Scene * getOwner () const
Additional Inherited Members
Protected Member Functions inherited from castor::OwnedBy< Scene >
OwnedBy (Scene &owner)
Constructor.
Constructor & Destructor Documentation
IblTextures()
C3D_API castor3d::IblTextures::IblTextures (Scene & scene, RenderDevice const & device, Texture const & source, Texture const & brdf, SamplerObs sampler) explicit
Constructor.
Parameters
[in] scene The scene.
[in] device The GPU device.
[in] source The source environment map.
[in] brdf The prefiltered BRDF map.
[in] sampler The sampler used for the environment map.
Member Function Documentation
getIrradianceSampler()
ashes::Sampler const & castor3d::IblTextures::getIrradianceSampler () const inline noexcept
References castor3d::RadianceComputer::getSampler().
getIrradianceTexture()
Texture const & castor3d::IblTextures::getIrradianceTexture () const inline noexcept
name Getters.
References castor3d::RadianceComputer::getResult().
getPrefilteredBrdfSampler()
ashes::Sampler const & castor3d::IblTextures::getPrefilteredBrdfSampler () const inline noexcept
References CU_Require, and castor3d::Sampler::getSampler().
getPrefilteredBrdfTexture()
Texture const & castor3d::IblTextures::getPrefilteredBrdfTexture () const inline noexcept
getPrefilteredEnvironmentSampler()
ashes::Sampler const & castor3d::IblTextures::getPrefilteredEnvironmentSampler () const inline noexcept
References castor3d::EnvironmentPrefilter::getSampler().
getPrefilteredEnvironmentSheenSampler()
ashes::Sampler const & castor3d::IblTextures::getPrefilteredEnvironmentSheenSampler () const inline noexcept
References castor3d::EnvironmentPrefilter::getSampler().
getPrefilteredEnvironmentSheenTexture()
Texture const & castor3d::IblTextures::getPrefilteredEnvironmentSheenTexture () const inline noexcept
References castor3d::EnvironmentPrefilter::getResult().
getPrefilteredEnvironmentTexture()
Texture const & castor3d::IblTextures::getPrefilteredEnvironmentTexture () const inline noexcept
References castor3d::EnvironmentPrefilter::getResult().
update() [1/2]
C3D_API crg::SemaphoreWaitArray castor3d::IblTextures::update (crg::SemaphoreWaitArray signalsToWait, ashes::Queue const & queue) const
Updates the environment maps.
Parameters
[in] signalsToWait The semaphore from the previous render pass.
[in] queue The queue receiving the GPU commands.
Returns
The semaphores signaled by this pass.
update() [2/2]
C3D_API void castor3d::IblTextures::update (QueueData const & queueData)
Updates the environment maps.
Parameters
[in] queueData The queue receiving the GPU commands.
The documentation for this class was generated from the following file:
Castor3D/Render/PBR/IblTextures.hpp