Castor3D: castor3d::LoadingScreen Class Reference
castor3d::LoadingScreen Class Reference
#include <LoadingScreen.hpp>
Public Member Functions
C3D_API LoadingScreen (ProgressBar &progressBar, RenderDevice const &device, crg::ResourceHandler &handler, SceneRPtr scene, VkRenderPass renderPass, castor::Size const &size)
C3D_API ~LoadingScreen ()
C3D_API void enable ()
C3D_API void disable ()
C3D_API void update (CpuUpdater &updater)
C3D_API void update (GpuUpdater &updater)
C3D_API void setRenderPass (VkRenderPass renderPass, castor::Size const &renderSize)
C3D_API void upload (ashes::CommandBuffer const &cb)
Uploads overlays GPU buffers to VRAM.
C3D_API crg::SemaphoreWaitArray render (ashes::Queue const &queue, ashes::FrameBuffer const &framebuffer, crg::SemaphoreWaitArray const &toWait, crg::Fence *&fence)
Renders the loading screen.
crg::SemaphoreWaitArray render (ashes::Queue const &queue, ashes::FrameBuffer const &framebuffer, crg::SemaphoreWait const &toWait, crg::Fence *&fence)
Renders the loading screen.
void step (castor::String const &label)
void setRange (uint32_t max)
void incRange (uint32_t mod)
uint32_t getIndex () const
bool isEnabled () const
ProgressBar & getProgressBar ()
Static Public Attributes
static C3D_API castor::String const SceneName
Constructor & Destructor Documentation
LoadingScreen()
C3D_API castor3d::LoadingScreen::LoadingScreen (ProgressBar & progressBar, RenderDevice const & device, crg::ResourceHandler & handler, SceneRPtr scene, VkRenderPass renderPass, castor::Size const & size)
~LoadingScreen()
C3D_API castor3d::LoadingScreen::~LoadingScreen ()
Member Function Documentation
disable()
C3D_API void castor3d::LoadingScreen::disable ()
enable()
C3D_API void castor3d::LoadingScreen::enable ()
getIndex()
uint32_t castor3d::LoadingScreen::getIndex () const inline
name Getters.
References castor3d::ProgressBar::getIndex().
getProgressBar()
ProgressBar & castor3d::LoadingScreen::getProgressBar () inline
incRange()
void castor3d::LoadingScreen::incRange (uint32_t mod) inline
References castor3d::ProgressBar::incRange().
isEnabled()
bool castor3d::LoadingScreen::isEnabled () const inline
render() [1/2]
crg::SemaphoreWaitArray castor3d::LoadingScreen::render (ashes::Queue const & queue, ashes::FrameBuffer const & framebuffer, crg::SemaphoreWait const & toWait, crg::Fence *& fence) inline
Renders the loading screen.
Parameters
[in] queue The queue receiving the render commands.
[in] framebuffer The framebuffer receiving the render.
[in] toWait The semaphore from the previous render pass.
[in] fence The fence to wait, nullptr to prevent waiting.
Returns
The semaphores signaled by this render.
References render().
render() [2/2]
C3D_API crg::SemaphoreWaitArray castor3d::LoadingScreen::render (ashes::Queue const & queue, ashes::FrameBuffer const & framebuffer, crg::SemaphoreWaitArray const & toWait, crg::Fence *& fence)
Renders the loading screen.
Parameters
[in] queue The queue receiving the render commands.
[in] framebuffer The framebuffer receiving the render.
[in] toWait The semaphores from the previous render pass.
[in] fence The fence to wait, nullptr to prevent waiting.
Returns
The semaphores signaled by this render.
Referenced by render().
setRange()
void castor3d::LoadingScreen::setRange (uint32_t max) inline
References castor3d::ProgressBar::setRange().
setRenderPass()
C3D_API void castor3d::LoadingScreen::setRenderPass (VkRenderPass renderPass, castor::Size const & renderSize)
step()
void castor3d::LoadingScreen::step (castor::String const & label) inline
name Mutators.
References castor3d::ProgressBar::step().
update() [1/2]
C3D_API void castor3d::LoadingScreen::update (CpuUpdater & updater)
update() [2/2]
C3D_API void castor3d::LoadingScreen::update (GpuUpdater & updater)
upload()
C3D_API void castor3d::LoadingScreen::upload (ashes::CommandBuffer const & cb)
Uploads overlays GPU buffers to VRAM.
Parameters
[in] cb The command buffer on which transfer commands are recorded.
Member Data Documentation
SceneName
C3D_API castor::String const castor3d::LoadingScreen::SceneName static
The documentation for this class was generated from the following file:
Miscellaneous/LoadingScreen.hpp