Castor3D: castor3d::EventHandler Class Reference
castor3d::EventHandler Class Reference abstract
Description of an event handler, class that can receive event.
Public Types
using ClientMouseFunction = std::function< void(MouseEvent const &) >
using ClientKeyboardFunction = std::function< void(KeyboardEvent const &) >
using ClientHandlerFunction = std::function< void(HandlerEvent const &) >
using OnClientMouseEvent = castor::Signal< ClientMouseFunction >
using OnClientKeyboardEvent = castor::Signal< ClientKeyboardFunction >
using OnClientHandlerEvent = castor::Signal< ClientHandlerFunction >
using OnClientMouseEventConnection = OnClientMouseEvent::connection
using OnClientKeyboardEventConnection = OnClientKeyboardEvent::connection
using OnClientHandlerEventConnection = OnClientHandlerEvent::connection
Public Member Functions
General
EventHandler (bool p_catchMouseEvents)
virtual ~EventHandler ()
void processEvents ()
Mouse events
void pushEvent (MouseEvent const &p_event)
void connect (MouseEventType p_event, ClientMouseFunction p_function)
Keyboard events
void pushEvent (KeyboardEvent const &p_event)
void connect (KeyboardEventType p_event, ClientKeyboardFunction p_function)
bool catchesMouseEvents () const
void setCatchesMouseEvents (bool p_value)
void pushEvent (HandlerEvent const &p_event)
void connect (HandlerEventType p_event, ClientHandlerFunction p_function)
bool catchesTabKey () const
bool catchesReturnKey () const
Protected Types
using EventHandlerFunction = std::function< void() >
using EventQueue = std::deque< std::pair< UserInputEventSPtr, EventHandlerFunction > >
Protected Member Functions
void processMouseEvent (MouseEventSPtr p_event)
void processKeyboardEvent (KeyboardEventSPtr p_event)
void processHandlerEvent (HandlerEventSPtr p_event)
Protected Attributes
std::array< OnClientMouseEvent, size_t(MouseEventType::eCount) > m_mouseSlots
std::array< std::vector< OnClientMouseEventConnection >, size_t(MouseEventType::eCount) > m_mouseSlotsConnections
std::array< OnClientKeyboardEvent, size_t(KeyboardEventType::eCount) > m_keyboardSlots
std::array< std::vector< OnClientKeyboardEventConnection >, size_t(KeyboardEventType::eCount) > m_keyboardSlotsConnections
std::array< OnClientHandlerEvent, size_t(HandlerEventType::eCount) > m_handlerSlots
std::array< std::vector< OnClientHandlerEventConnection >, size_t(HandlerEventType::eCount) > m_handlerSlotsConnections
Detailed Description
Description of an event handler, class that can receive event.
Author
Sylvain DOREMUS
Date
17/04/2016
Version
0.9.0
Member Typedef Documentation
ClientHandlerFunction
using castor3d::EventHandler::ClientHandlerFunction = std::function< void(HandlerEvent const &) >
Catcher definition for handler events.
ClientKeyboardFunction
using castor3d::EventHandler::ClientKeyboardFunction = std::function< void(KeyboardEvent const &) >
Catcher definition for keyboard events.
ClientMouseFunction
using castor3d::EventHandler::ClientMouseFunction = std::function< void(MouseEvent const &) >
Catcher definition for mouse events.
EventHandlerFunction
using castor3d::EventHandler::EventHandlerFunction = std::function< void() > protected
EventQueue
using castor3d::EventHandler::EventQueue = std::deque< std::pair< UserInputEventSPtr, EventHandlerFunction > > protected
OnClientHandlerEvent
using castor3d::EventHandler::OnClientHandlerEvent = castor::Signal< ClientHandlerFunction >
Handler event signal definition.
OnClientHandlerEventConnection
using castor3d::EventHandler::OnClientHandlerEventConnection = OnClientHandlerEvent::connection
Handler event signal connection definition.
OnClientKeyboardEvent
using castor3d::EventHandler::OnClientKeyboardEvent = castor::Signal< ClientKeyboardFunction >
Keyboard event signal definition.
OnClientKeyboardEventConnection
using castor3d::EventHandler::OnClientKeyboardEventConnection = OnClientKeyboardEvent::connection
Keyboard event signal connection definition.
OnClientMouseEvent
using castor3d::EventHandler::OnClientMouseEvent = castor::Signal< ClientMouseFunction >
Mouse event signal definition.
OnClientMouseEventConnection
using castor3d::EventHandler::OnClientMouseEventConnection = OnClientMouseEvent::connection
Mouse event signal connection definition.
Constructor & Destructor Documentation
EventHandler()
castor3d::EventHandler::EventHandler (bool p_catchMouseEvents) inline explicit
~EventHandler()
virtual castor3d::EventHandler::~EventHandler () inline virtual
Member Function Documentation
catchesMouseEvents()
bool castor3d::EventHandler::catchesMouseEvents () const inline
catchesReturnKey()
bool castor3d::EventHandler::catchesReturnKey () const inline
catchesTabKey()
bool castor3d::EventHandler::catchesTabKey () const inline
connect() [1/3]
void castor3d::EventHandler::connect (MouseEventType p_event, ClientMouseFunction p_function) inline
References m_mouseSlots, and m_mouseSlotsConnections.
Referenced by connect(), and castor3d::NonClientEventHandler< Derived >::connectNC().
connect() [2/3]
void castor3d::EventHandler::connect (KeyboardEventType p_event, ClientKeyboardFunction p_function) inline
References connect(), m_keyboardSlots, and m_keyboardSlotsConnections.
connect() [3/3]
void castor3d::EventHandler::connect (HandlerEventType p_event, ClientHandlerFunction p_function) inline
References connect(), m_handlerSlots, and m_handlerSlotsConnections.
processEvents()
void castor3d::EventHandler::processEvents () inline
processHandlerEvent()
void castor3d::EventHandler::processHandlerEvent (HandlerEventSPtr p_event) inline protected
References m_handlerSlots.
Referenced by pushEvent().
processKeyboardEvent()
void castor3d::EventHandler::processKeyboardEvent (KeyboardEventSPtr p_event) inline protected
References m_keyboardSlots.
Referenced by pushEvent().
processMouseEvent()
void castor3d::EventHandler::processMouseEvent (MouseEventSPtr p_event) inline protected
References m_mouseSlots.
Referenced by pushEvent().
pushEvent() [1/3]
void castor3d::EventHandler::pushEvent (MouseEvent const & p_event) inline
References processMouseEvent().
pushEvent() [2/3]
void castor3d::EventHandler::pushEvent (KeyboardEvent const & p_event) inline
References processKeyboardEvent().
pushEvent() [3/3]
void castor3d::EventHandler::pushEvent (HandlerEvent const & p_event) inline
References processHandlerEvent().
setCatchesMouseEvents()
void castor3d::EventHandler::setCatchesMouseEvents (bool p_value) inline
Member Data Documentation
m_handlerSlots
std::array< OnClientHandlerEvent, size_t(HandlerEventType::eCount) > castor3d::EventHandler::m_handlerSlots protected
The keyboard events slots.
Referenced by connect(), and processHandlerEvent().
m_handlerSlotsConnections
std::array< std::vector< OnClientHandlerEventConnection >, size_t(HandlerEventType::eCount) > castor3d::EventHandler::m_handlerSlotsConnections protected
The handler events slots connections.
Referenced by connect().
m_keyboardSlots
std::array< OnClientKeyboardEvent, size_t(KeyboardEventType::eCount) > castor3d::EventHandler::m_keyboardSlots protected
The keyboard events slots.
Referenced by connect(), and processKeyboardEvent().
m_keyboardSlotsConnections
std::array< std::vector< OnClientKeyboardEventConnection >, size_t(KeyboardEventType::eCount) > castor3d::EventHandler::m_keyboardSlotsConnections protected
The handler events slots connections.
Referenced by connect().
m_mouseSlots
std::array< OnClientMouseEvent, size_t(MouseEventType::eCount) > castor3d::EventHandler::m_mouseSlots protected
The mouse events slots.
Referenced by connect(), and processMouseEvent().
m_mouseSlotsConnections
std::array< std::vector< OnClientMouseEventConnection >, size_t(MouseEventType::eCount) > castor3d::EventHandler::m_mouseSlotsConnections protected
The mouse events slots connections.
Referenced by connect().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Event/UserInput/EventHandler.hpp