Castor3D: castor3d::RenderTechniquePass Class Reference
castor3d::RenderTechniquePass Class Reference abstract
#include <RenderTechniquePass.hpp>
Public Member Functions
virtual C3D_API ~RenderTechniquePass () noexcept=default
virtual C3D_API void accept (RenderTechniqueVisitor &visitor)
Visitor acceptance function.
virtual C3D_API void update (CpuUpdater &updater)
Updates the render pass, CPU wise.
virtual C3D_API PipelineFlags createPipelineFlags (PassComponentCombine const &passComponents, SubmeshComponentCombine const &submeshComponents, BlendMode colourBlendMode, BlendMode alphaBlendMode, RenderPassTypeID renderPassTypeId, LightingModelID lightingModelId, BackgroundModelID backgroundModelId, VkCompareOp alphaFunc, VkCompareOp blendAlphaFunc, TextureCombine const &textures, ProgramFlags const &programFlags, SceneFlags const &sceneFlags, VkPrimitiveTopology topology, bool isFrontCulled, uint32_t passLayerIndex, GpuBufferOffsetT< castor::Point4f > const &morphTargets, SubmeshRenderData *submeshData) const =0
Creates the pipeline flags for given configuration.
virtual C3D_API bool areValidPassFlags (PassComponentCombine const &passFlags) const noexcept=0
virtual C3D_API ShaderFlags getShaderFlags () const noexcept=0
virtual C3D_API void countNodes (RenderInfo &info) const noexcept=0
Registers nodes counts to given RenderInfo.
virtual C3D_API bool isPassEnabled () const noexcept=0
C3D_API Engine * getEngine () const noexcept
C3D_API IndirectLightingData const & getIndirectLighting () const noexcept
C3D_API DebugConfig & getDebugConfig () const noexcept
C3D_API bool areDebugTargetsEnabled () const noexcept
virtual C3D_API ClustersConfig const * getClustersConfig () const noexcept=0
virtual C3D_API bool hasSsao () const noexcept=0
Scene const & getScene () noexcept
Scene const & getScene () const noexcept
RenderTechnique const & getTechnique () const noexcept
Protected Member Functions
C3D_API RenderTechniquePass (RenderTechnique *parent, Scene const &scene, bool outputScattering)
Constructor.
virtual C3D_API void doAccept (castor3d::RenderTechniqueVisitor &visitor)=0
Visitor acceptance function.
Protected Attributes
RenderTechnique * m_parent {}
Scene const & m_scene
uint32_t m_drawCalls {}
bool m_outputScattering {}
Constructor & Destructor Documentation
RenderTechniquePass()
C3D_API castor3d::RenderTechniquePass::RenderTechniquePass (RenderTechnique * parent, Scene const & scene, bool outputScattering) protected
Constructor.
Parameters
[in] parent The parent technique.
[in] scene The scene.
[in] outputScattering Defines if the pass outputs scattering data.
~RenderTechniquePass()
virtual C3D_API castor3d::RenderTechniquePass::~RenderTechniquePass () virtual default noexcept
Member Function Documentation
accept()
virtual C3D_API void castor3d::RenderTechniquePass::accept (RenderTechniqueVisitor & visitor) inline virtual
Visitor acceptance function.
Parameters
visitor The ... visitor.
Reimplemented in castor3d::VisibilityResolvePass, castor3d::ForwardRenderTechniquePass, castor3d::VisibilityPass, castor3d::RenderTechniqueNodesPass, and castor3d::TransparentPass.
References doAccept().
areDebugTargetsEnabled()
C3D_API bool castor3d::RenderTechniquePass::areDebugTargetsEnabled () const noexcept
Referenced by castor3d::RenderTechniqueNodesPass::areDebugTargetsEnabled().
areValidPassFlags()
virtual C3D_API bool castor3d::RenderTechniquePass::areValidPassFlags (PassComponentCombine const & passFlags) const pure virtual noexcept
name Getters.
Implemented in castor3d::VisibilityResolvePass, and castor3d::RenderTechniqueNodesPass.
countNodes()
virtual C3D_API void castor3d::RenderTechniquePass::countNodes (RenderInfo & info) const pure virtual noexcept
Registers nodes counts to given RenderInfo.
Parameters
[in,out] info Receives the counts.
Implemented in castor3d::VisibilityResolvePass, and castor3d::RenderTechniqueNodesPass.
createPipelineFlags()
virtual C3D_API PipelineFlags castor3d::RenderTechniquePass::createPipelineFlags (PassComponentCombine const & passComponents, SubmeshComponentCombine const & submeshComponents, BlendMode colourBlendMode, BlendMode alphaBlendMode, RenderPassTypeID renderPassTypeId, LightingModelID lightingModelId, BackgroundModelID backgroundModelId, VkCompareOp alphaFunc, VkCompareOp blendAlphaFunc, TextureCombine const & textures, ProgramFlags const & programFlags, SceneFlags const & sceneFlags, VkPrimitiveTopology topology, bool isFrontCulled, uint32_t passLayerIndex, GpuBufferOffsetT< castor::Point4f > const & morphTargets, SubmeshRenderData * submeshData) const pure virtual
Creates the pipeline flags for given configuration.
Parameters
[in] passComponents The pass components combination.
[in] submeshComponents The submesh components combination.
[in] colourBlendMode The colour blending mode.
[in] alphaBlendMode The alpha blending mode.
[in] renderPassTypeId The render pass type ID.
[in] lightingModelId The lighting model ID.
[in] backgroundModelId The background model ID.
[in] alphaFunc The alpha comparison function (for opaque nodes).
[in] blendAlphaFunc The alpha comparison function (for transparent nodes).
[in] textures The textures configuration.
[in] programFlags A combination of ProgramFlag.
[in] sceneFlags Scene related flags.
[in] topology The render topology.
[in] isFrontCulled true for front face culling, false for back face culling.
[in] passLayerIndex The material pass layer index.
[in] morphTargets The morph targets buffer.
[in] submeshData The submesh render data, if any.
Implemented in castor3d::VisibilityResolvePass, and castor3d::RenderTechniqueNodesPass.
doAccept()
virtual C3D_API void castor3d::RenderTechniquePass::doAccept (castor3d::RenderTechniqueVisitor & visitor) protected pure virtual
Visitor acceptance function.
Parameters
visitor The ... visitor.
Implemented in castor3d::RenderTechniqueNodesPass.
Referenced by accept().
getClustersConfig()
virtual C3D_API ClustersConfig const * castor3d::RenderTechniquePass::getClustersConfig () const pure virtual noexcept
Implemented in castor3d::VisibilityResolvePass, and castor3d::RenderTechniqueNodesPass.
getDebugConfig()
C3D_API DebugConfig & castor3d::RenderTechniquePass::getDebugConfig () const noexcept
Referenced by castor3d::RenderTechniqueNodesPass::getDebugConfig().
getEngine()
C3D_API Engine * castor3d::RenderTechniquePass::getEngine () const noexcept
name Getters.
Referenced by castor3d::RenderTechniqueNodesPass::getEngine().
getIndirectLighting()
C3D_API IndirectLightingData const & castor3d::RenderTechniquePass::getIndirectLighting () const noexcept
getScene() [1/2]
Scene const & castor3d::RenderTechniquePass::getScene () const inline noexcept
References m_scene.
getScene() [2/2]
Scene const & castor3d::RenderTechniquePass::getScene () inline noexcept
References m_scene.
Referenced by castor3d::RenderTechniqueNodesPass::getScene().
getShaderFlags()
virtual C3D_API ShaderFlags castor3d::RenderTechniquePass::getShaderFlags () const pure virtual noexcept
Implemented in castor3d::VisibilityResolvePass, castor3d::DepthPass, castor3d::VisibilityPass, and castor3d::RenderTechniqueNodesPass.
getTechnique()
RenderTechnique const & castor3d::RenderTechniquePass::getTechnique () const inline noexcept
References m_parent.
Referenced by castor3d::RenderTechniqueNodesPass::getTechnique().
hasSsao()
virtual C3D_API bool castor3d::RenderTechniquePass::hasSsao () const pure virtual noexcept
Implemented in castor3d::VisibilityResolvePass, and castor3d::RenderTechniqueNodesPass.
isPassEnabled()
virtual C3D_API bool castor3d::RenderTechniquePass::isPassEnabled () const pure virtual noexcept
Implemented in castor3d::VisibilityResolvePass, and castor3d::RenderTechniqueNodesPass.
update()
virtual C3D_API void castor3d::RenderTechniquePass::update (CpuUpdater & updater) inline virtual
Updates the render pass, CPU wise.
Parameters
[in,out] updater The update data.
Reimplemented in castor3d::VisibilityResolvePass, and castor3d::RenderTechniqueNodesPass.
Member Data Documentation
m_drawCalls
uint32_t castor3d::RenderTechniquePass::m_drawCalls {} protected
m_outputScattering
bool castor3d::RenderTechniquePass::m_outputScattering {} protected
m_parent
RenderTechnique* castor3d::RenderTechniquePass::m_parent {} protected
Referenced by getTechnique().
m_scene
Scene const& castor3d::RenderTechniquePass::m_scene protected
Referenced by getScene(), and getScene().
The documentation for this class was generated from the following file:
Castor3D/Render/RenderTechniquePass.hpp