Castor3D: Castor3D::ShaderProgram Class Reference
Castor3D::ShaderProgram Class Reference abstract
Base shader program implementation, used to share functions through the supported shader languages.
Classes
class TextWriter
ShaderProgram loader.
Public Member Functions
C3D_API ShaderProgram (RenderSystem &p_renderSystem)
Constructor.
virtual C3D_API ~ShaderProgram ()
Destructor.
C3D_API ShaderObjectSPtr CreateObject (ShaderType p_type)
Creates the wanted shader object.
C3D_API void SetFile (ShaderModel p_eModel, Castor::Path const &p_pathFile)
Sets all objects file.
C3D_API ShaderStorageBuffer & CreateStorageBuffer (Castor::String const &p_name, ShaderTypeFlags const &p_shaderMask)
Creates a shader storage buffer.
C3D_API ShaderStorageBufferSPtr FindStorageBuffer (Castor::String const &p_name) const
Finds a storage buffer.
C3D_API AtomicCounterBuffer & CreateAtomicCounterBuffer (Castor::String const &p_name, ShaderTypeFlags const &p_shaderMask)
Creates an atomic counter buffer.
C3D_API AtomicCounterBufferSPtr FindAtomicCounterBuffer (Castor::String const &p_name) const
Finds an atomic counter buffer.
C3D_API void ResetToCompile ()
Resets compilation variables to be able to compile again.
C3D_API void SetInputType (ShaderType p_target, Topology p_topology)
Sets the input primitives type.
C3D_API void SetOutputType (ShaderType p_target, Topology p_topology)
Sets the output primitives type.
C3D_API void SetOutputVtxCount (ShaderType p_target, uint8_t p_count)
Sets the output vertex count.
C3D_API void SetFile (ShaderType p_target, ShaderModel p_eModel, Castor::Path const &p_pathFile)
Sets the shader file for given model.
C3D_API Castor::Path GetFile (ShaderType p_target, ShaderModel p_eModel) const
Retrieves the shader file for given model.
C3D_API bool HasFile (ShaderType p_target) const
Tells if the shader object has a source file, whatever model it is.
C3D_API void SetSource (ShaderType p_target, ShaderModel p_eModel, Castor::String const &p_strSource)
Sets the shader source for given model.
C3D_API Castor::String GetSource (ShaderType p_target, ShaderModel p_eModel) const
Retrieves the shader source for given model.
C3D_API bool HasSource (ShaderType p_target) const
Tells if the shader object has a source code, whatever model it is.
C3D_API bool HasObject (ShaderType p_target) const
Tests if the program has an object for given type.
C3D_API ShaderStatus GetObjectStatus (ShaderType p_target) const
C3D_API PushUniformSPtr CreateUniform (UniformType p_type, Castor::String const &p_name, ShaderType p_shader, int p_nbOcc=1)
Creates a variable.
template<UniformType Type>
std::shared_ptr< TPushUniform< Type > > CreateUniform (Castor::String const &p_name, ShaderType p_shader, int p_nbOcc=1)
Creates a variable.
C3D_API PushUniformSPtr FindUniform (UniformType p_type, Castor::String const &p_name, ShaderType p_shader) const
Looks for a variable.
template<UniformType Type>
std::shared_ptr< TPushUniform< Type > > FindUniform (Castor::String const &p_name, ShaderType p_shader) const
Looks for a variable.
C3D_API PushUniformList & GetUniforms (ShaderType p_type)
Retrieves the frame variables buffer bound to one shader type.
C3D_API PushUniformList const & GetUniforms (ShaderType p_type) const
Retrieves the frame variables bound to one shader type.
virtual C3D_API void Cleanup ()=0
Cleans the program up.
virtual C3D_API bool Initialise ()=0
Initialises the program.
virtual C3D_API void Bind () const =0
Activates the program.
virtual C3D_API void Unbind () const =0
Deactivates the program.
virtual C3D_API bool Link ()=0
Links all shader objects held by the program.
virtual C3D_API ProgramInputLayout const & GetLayout () const =0
virtual C3D_API ProgramInputLayout & GetLayout ()=0
void SetTransformLayout (BufferDeclaration const &p_declaration)
Sets the transform feedback layout.
ShaderStorageBufferPtrList & GetShaderStorageBuffers (ShaderType p_type)
Retrieves the storage buffers bound to one shader type.
ShaderStorageBufferPtrList const & GetShaderStorageBuffers (ShaderType p_type) const
Retrieves the storage buffers bound to one shader type.
ShaderStorageBufferPtrList & GetShaderStorageBuffers ()
ShaderStorageBufferPtrList const & GetShaderStorageBuffers () const
AtomicCounterBufferPtrList & GetAtomicCounterBuffers (ShaderType p_type)
Retrieves the atomic counter buffers bound to one shader type.
AtomicCounterBufferPtrList const & GetAtomicCounterBuffers (ShaderType p_type) const
Retrieves the atomic counter buffers bound to one shader type.
AtomicCounterBufferPtrList & GetAtomicCounterBuffers ()
AtomicCounterBufferPtrList const & GetAtomicCounterBuffers () const
ProgramStatus GetStatus () const
Retrieves the program link status.
Static Public Attributes
Attributes
static C3D_API const Castor::String Position
static C3D_API const Castor::String Normal
static C3D_API const Castor::String Tangent
static C3D_API const Castor::String Bitangent
static C3D_API const Castor::String Texture
static C3D_API const Castor::String Colour
static C3D_API const Castor::String Position2
static C3D_API const Castor::String Normal2
static C3D_API const Castor::String Tangent2
static C3D_API const Castor::String Bitangent2
static C3D_API const Castor::String Texture2
static C3D_API const Castor::String Colour2
static C3D_API const Castor::String Text
static C3D_API const Castor::String BoneIds0
static C3D_API const Castor::String BoneIds1
static C3D_API const Castor::String Weights0
static C3D_API const Castor::String Weights1
static C3D_API const Castor::String Transform
Scene
static C3D_API const Castor::String CameraPos
static C3D_API const Castor::String AmbientLight
static C3D_API const Castor::String BackgroundColour
static C3D_API const Castor::String FogType
static C3D_API const Castor::String FogDensity
static C3D_API const Castor::String LightsCount
static C3D_API const Castor::String Lights
Pass
static C3D_API const Castor::String MatAmbient
static C3D_API const Castor::String MatDiffuse
static C3D_API const Castor::String MatSpecular
static C3D_API const Castor::String MatEmissive
static C3D_API const Castor::String MatShininess
static C3D_API const Castor::String MatOpacity
static C3D_API const Castor::String MapShadow
static C3D_API const Castor::String MapText
Model
static C3D_API const Castor::String ShadowReceiver
Animation
static C3D_API const Castor::String Bones
static C3D_API const Castor::String Time
Billboard
static C3D_API const Castor::String Dimensions
static C3D_API const Castor::String WindowSize
Overlay
static C3D_API const Castor::String OvPosition
Textures
static C3D_API const Castor::String MapColour
static C3D_API const Castor::String MapAmbient
static C3D_API const Castor::String MapDiffuse
static C3D_API const Castor::String MapSpecular
static C3D_API const Castor::String MapEmissive
static C3D_API const Castor::String MapNormal
static C3D_API const Castor::String MapOpacity
static C3D_API const Castor::String MapGloss
static C3D_API const Castor::String MapHeight
Frame Variable Buffers
static C3D_API const Castor::String BufferMatrix
static C3D_API const Castor::String BufferModelMatrix
static C3D_API const Castor::String BufferScene
static C3D_API const Castor::String BufferPass
static C3D_API const Castor::String BufferModel
static C3D_API const Castor::String BufferBillboards
static C3D_API const Castor::String BufferSkinning
static C3D_API const Castor::String BufferMorphing
static C3D_API const Castor::String BufferOverlay
Protected Member Functions
C3D_API void DoCleanup ()
Cleans the program up.
C3D_API bool DoInitialise ()
Initialises the program.
C3D_API void DoBind () const
Activates the program.
C3D_API void DoUnbind () const
Deactivates the program.
C3D_API bool DoLink ()
Links all shader objects held by the program.
Protected Attributes
ProgramStatus m_status { ProgramStatus::eNotLinked }
std::array< ShaderObjectSPtr, size_t(ShaderType::eCount) > m_shaders
std::vector< ShaderObjectSPtr > m_activeShaders
std::array< Castor::Path, size_t(ShaderModel::eCount) > m_arrayFiles
ShaderStorageBufferPtrStrMap m_storageBuffersByName
std::array< ShaderStorageBufferPtrList, size_t(ShaderType::eCount) > m_storageBuffers
ShaderStorageBufferPtrList m_listStorageBuffers
AtomicCounterBufferPtrStrMap m_atomicCounterBuffersByName
std::array< AtomicCounterBufferPtrList, size_t(ShaderType::eCount) > m_atomicCounterBuffers
AtomicCounterBufferPtrList m_listAtomicCounterBuffers
BufferDeclaration m_declaration
Friends
class Castor::TextWriter< Castor3D::ShaderProgram >
Detailed Description
Base shader program implementation, used to share functions through the supported shader languages.
Author
Sylvain DOREMUS
Version
0.6.1.2
Date
24/01/2011
Constructor & Destructor Documentation
ShaderProgram()
C3D_API Castor3D::ShaderProgram::ShaderProgram (RenderSystem & p_renderSystem) explicit
Constructor.
Parameters
[in] p_renderSystem The RenderSystem instance.
~ShaderProgram()
virtual C3D_API Castor3D::ShaderProgram::~ShaderProgram () virtual
Destructor.
Member Function Documentation
Bind()
virtual C3D_API void Castor3D::ShaderProgram::Bind () const pure virtual
Activates the program.
Cleanup()
virtual C3D_API void Castor3D::ShaderProgram::Cleanup () pure virtual
Cleans the program up.
CreateAtomicCounterBuffer()
C3D_API AtomicCounterBuffer& Castor3D::ShaderProgram::CreateAtomicCounterBuffer (Castor::String const & p_name, ShaderTypeFlags const & p_shaderMask)
Creates an atomic counter buffer.
Parameters
[in] p_name The buffer name.
[in] p_shaderMask ShaderTypeFlag combination, to set at what shaders it is to be bound.
Returns
The created or retrieved Frame variable buffer.
CreateObject()
C3D_API ShaderObjectSPtr Castor3D::ShaderProgram::CreateObject (ShaderType p_type)
Creates the wanted shader object.
Parameters
[in] p_type The shader object concerned.
CreateStorageBuffer()
C3D_API ShaderStorageBuffer& Castor3D::ShaderProgram::CreateStorageBuffer (Castor::String const & p_name, ShaderTypeFlags const & p_shaderMask)
Creates a shader storage buffer.
Parameters
[in] p_name The buffer name.
[in] p_shaderMask ShaderTypeFlag combination, to set at what shaders it is to be bound.
Returns
The created or retrieved Frame variable buffer.
CreateUniform() [1/2]
C3D_API PushUniformSPtr Castor3D::ShaderProgram::CreateUniform (UniformType p_type, Castor::String const & p_name, ShaderType p_shader, int p_nbOcc = 1)
Creates a variable.
Parameters
[in] p_type The variable type.
[in] p_name The variable name.
[in] p_shader The shader type.
[in] p_nbOcc The array dimension.
Returns
The created variable, nullptr if failed.
Referenced by CreateUniform().
CreateUniform() [2/2]
template<UniformType Type> std::shared_ptr< TPushUniform< Type > > Castor3D::ShaderProgram::CreateUniform (Castor::String const & p_name, ShaderType p_shader, int p_nbOcc = 1) inline
Creates a variable.
Parameters
[in] p_name The variable name.
[in] p_shader The shader type.
[in] p_nbOcc The array dimension.
Returns
The created variable, nullptr if failed.
References CreateUniform().
DoBind()
C3D_API void Castor3D::ShaderProgram::DoBind () const protected
Activates the program.
DoCleanup()
C3D_API void Castor3D::ShaderProgram::DoCleanup () protected
Cleans the program up.
DoInitialise()
C3D_API bool Castor3D::ShaderProgram::DoInitialise () protected
Initialises the program.
DoLink()
C3D_API bool Castor3D::ShaderProgram::DoLink () protected
Links all shader objects held by the program.
DoUnbind()
C3D_API void Castor3D::ShaderProgram::DoUnbind () const protected
Deactivates the program.
FindAtomicCounterBuffer()
C3D_API AtomicCounterBufferSPtr Castor3D::ShaderProgram::FindAtomicCounterBuffer (Castor::String const & p_name) const
Finds an atomic counter buffer.
Parameters
[in] p_name The buffer name.
Returns
The found buffer, nullptr if failed.
FindStorageBuffer()
C3D_API ShaderStorageBufferSPtr Castor3D::ShaderProgram::FindStorageBuffer (Castor::String const & p_name) const
Finds a storage buffer.
Parameters
[in] p_name The buffer name.
Returns
The found buffer, nullptr if failed.
FindUniform() [1/2]
C3D_API PushUniformSPtr Castor3D::ShaderProgram::FindUniform (UniformType p_type, Castor::String const & p_name, ShaderType p_shader) const
Looks for a variable.
Parameters
[in] p_type The variable type.
[in] p_name The variable name.
[in] p_shader The shader type.
Returns
The found variable, nullptr if failed.
Referenced by FindUniform().
FindUniform() [2/2]
template<UniformType Type> std::shared_ptr< TPushUniform< Type > > Castor3D::ShaderProgram::FindUniform (Castor::String const & p_name, ShaderType p_shader) const inline
Looks for a variable.
Parameters
[in] p_name The variable name.
[in] p_shader The shader type.
Returns
The found variable, nullptr if failed.
References FindUniform().
GetAtomicCounterBuffers() [1/4]
AtomicCounterBufferPtrList& Castor3D::ShaderProgram::GetAtomicCounterBuffers (ShaderType p_type) inline
Retrieves the atomic counter buffers bound to one shader type.
Parameters
[in] p_type The shader type
Returns
The list
References m_atomicCounterBuffers.
GetAtomicCounterBuffers() [2/4]
AtomicCounterBufferPtrList const& Castor3D::ShaderProgram::GetAtomicCounterBuffers (ShaderType p_type) const inline
Retrieves the atomic counter buffers bound to one shader type.
Parameters
[in] p_type The shader type
Returns
The list
References m_atomicCounterBuffers.
GetAtomicCounterBuffers() [3/4]
AtomicCounterBufferPtrList& Castor3D::ShaderProgram::GetAtomicCounterBuffers () inline
Returns
The atomic counter buffers list.
References m_listAtomicCounterBuffers.
GetAtomicCounterBuffers() [4/4]
AtomicCounterBufferPtrList const& Castor3D::ShaderProgram::GetAtomicCounterBuffers () const inline
Returns
The atomic counter buffers list.
References m_listAtomicCounterBuffers.
GetFile()
C3D_API Castor::Path Castor3D::ShaderProgram::GetFile (ShaderType p_target, ShaderModel p_eModel) const
Retrieves the shader file for given model.
Parameters
[in] p_target The shader object concerned.
[in] p_eModel The shader model.
Returns
The file name.
GetLayout() [1/2]
virtual C3D_API ProgramInputLayout const& Castor3D::ShaderProgram::GetLayout () const pure virtual
Returns
The program vertex layout.
GetLayout() [2/2]
virtual C3D_API ProgramInputLayout& Castor3D::ShaderProgram::GetLayout () pure virtual
Returns
The program vertex layout.
GetObjectStatus()
C3D_API ShaderStatus Castor3D::ShaderProgram::GetObjectStatus (ShaderType p_target) const
Returns
The given object type status.
GetShaderStorageBuffers() [1/4]
ShaderStorageBufferPtrList& Castor3D::ShaderProgram::GetShaderStorageBuffers (ShaderType p_type) inline
Retrieves the storage buffers bound to one shader type.
Parameters
[in] p_type The shader type
Returns
The list
References m_storageBuffers.
GetShaderStorageBuffers() [2/4]
ShaderStorageBufferPtrList const& Castor3D::ShaderProgram::GetShaderStorageBuffers (ShaderType p_type) const inline
Retrieves the storage buffers bound to one shader type.
Parameters
[in] p_type The shader type
Returns
The list
References m_storageBuffers.
GetShaderStorageBuffers() [3/4]
ShaderStorageBufferPtrList& Castor3D::ShaderProgram::GetShaderStorageBuffers () inline
Returns
The storage buffers list.
References m_listStorageBuffers.
GetShaderStorageBuffers() [4/4]
ShaderStorageBufferPtrList const& Castor3D::ShaderProgram::GetShaderStorageBuffers () const inline
Returns
The storage buffers list.
References m_listStorageBuffers.
GetSource()
C3D_API Castor::String Castor3D::ShaderProgram::GetSource (ShaderType p_target, ShaderModel p_eModel) const
Retrieves the shader source for given model.
Parameters
[in] p_target The shader object concerned.
[in] p_eModel The shader model.
Returns
The source code.
GetStatus()
ProgramStatus Castor3D::ShaderProgram::GetStatus () const inline
Retrieves the program link status.
Returns
The value.
References m_status.
GetUniforms() [1/2]
C3D_API PushUniformList& Castor3D::ShaderProgram::GetUniforms (ShaderType p_type)
Retrieves the frame variables buffer bound to one shader type.
Parameters
[in] p_type The shader type.
Returns
The list.
GetUniforms() [2/2]
C3D_API PushUniformList const& Castor3D::ShaderProgram::GetUniforms (ShaderType p_type) const
Retrieves the frame variables bound to one shader type.
Parameters
[in] p_type The shader type.
Returns
The list.
HasFile()
C3D_API bool Castor3D::ShaderProgram::HasFile (ShaderType p_target) const
Tells if the shader object has a source file, whatever model it is.
Parameters
[in] p_target The shader object concerned.
Returns
true if the shader object has a source file.
HasObject()
C3D_API bool Castor3D::ShaderProgram::HasObject (ShaderType p_target) const
Tests if the program has an object for given type.
Parameters
[in] p_target The shader object type.
Returns
true if the shader object exists.
HasSource()
C3D_API bool Castor3D::ShaderProgram::HasSource (ShaderType p_target) const
Tells if the shader object has a source code, whatever model it is.
Parameters
[in] p_target The shader object concerned.
Returns
true if the shader object has a source code.
Initialise()
virtual C3D_API bool Castor3D::ShaderProgram::Initialise () pure virtual
Initialises the program.
Link()
virtual C3D_API bool Castor3D::ShaderProgram::Link () pure virtual
Links all shader objects held by the program.
ResetToCompile()
C3D_API void Castor3D::ShaderProgram::ResetToCompile ()
Resets compilation variables to be able to compile again.
SetFile() [1/2]
C3D_API void Castor3D::ShaderProgram::SetFile (ShaderModel p_eModel, Castor::Path const & p_pathFile)
Sets all objects file.
Parameters
[in] p_eModel The shader model.
[in] p_pathFile The file name.
SetFile() [2/2]
C3D_API void Castor3D::ShaderProgram::SetFile (ShaderType p_target, ShaderModel p_eModel, Castor::Path const & p_pathFile)
Sets the shader file for given model.
Remarks
The loaded file will be the one of the highest supported profile.
Parameters
[in] p_target The shader object concerned.
[in] p_eModel The shader model.
[in] p_pathFile The file name.
SetInputType()
C3D_API void Castor3D::ShaderProgram::SetInputType (ShaderType p_target, Topology p_topology)
Sets the input primitives type.
Parameters
[in] p_target The shader object concerned.
[in] p_topology The input primitives type.
SetOutputType()
C3D_API void Castor3D::ShaderProgram::SetOutputType (ShaderType p_target, Topology p_topology)
Sets the output primitives type.
Parameters
[in] p_target The shader object concerned.
[in] p_topology The output primitives type.
SetOutputVtxCount()
C3D_API void Castor3D::ShaderProgram::SetOutputVtxCount (ShaderType p_target, uint8_t p_count)
Sets the output vertex count.
Parameters
[in] p_target The shader object concerned.
[in] p_count The count.
SetSource()
C3D_API void Castor3D::ShaderProgram::SetSource (ShaderType p_target, ShaderModel p_eModel, Castor::String const & p_strSource)
Sets the shader source for given model.
Remarks
The loaded source will be the one of the highest supported profile.
Parameters
[in] p_target The shader object concerned.
[in] p_eModel The shader model.
[in] p_strSource The source code.
SetTransformLayout()
void Castor3D::ShaderProgram::SetTransformLayout (BufferDeclaration const & p_declaration) inline
Sets the transform feedback layout.
Parameters
[in] p_declaration The layout.
References m_declaration.
Unbind()
virtual C3D_API void Castor3D::ShaderProgram::Unbind () const pure virtual
Deactivates the program.
Friends And Related Function Documentation
Castor::TextWriter< Castor3D::ShaderProgram >
friend class Castor::TextWriter< Castor3D::ShaderProgram > friend
Member Data Documentation
AmbientLight
C3D_API const Castor::String Castor3D::ShaderProgram::AmbientLight static
Name of the ambient light frame variable.
BackgroundColour
C3D_API const Castor::String Castor3D::ShaderProgram::BackgroundColour static
Name of the background colour frame variable.
Bitangent
C3D_API const Castor::String Castor3D::ShaderProgram::Bitangent static
Name of the bitangent attribute.
Bitangent2
C3D_API const Castor::String Castor3D::ShaderProgram::Bitangent2 static
Name of the bitangent attribute for per-vertex animations.
BoneIds0
C3D_API const Castor::String Castor3D::ShaderProgram::BoneIds0 static
Name of the first bones ID attribute.
BoneIds1
C3D_API const Castor::String Castor3D::ShaderProgram::BoneIds1 static
Name of the second bones ID attribute.
Bones
C3D_API const Castor::String Castor3D::ShaderProgram::Bones static
Name of the bones matrices attribute.
BufferBillboards
C3D_API const Castor::String Castor3D::ShaderProgram::BufferBillboards static
Name of the billboards frame variable buffer.
BufferMatrix
C3D_API const Castor::String Castor3D::ShaderProgram::BufferMatrix static
Name of the matrix frame variable buffer.
BufferModel
C3D_API const Castor::String Castor3D::ShaderProgram::BufferModel static
Name of the model frame variable buffer.
BufferModelMatrix
C3D_API const Castor::String Castor3D::ShaderProgram::BufferModelMatrix static
Name of the model matrix frame variable buffer.
BufferMorphing
C3D_API const Castor::String Castor3D::ShaderProgram::BufferMorphing static
Name of the morphing animation frame variable buffer.
BufferOverlay
C3D_API const Castor::String Castor3D::ShaderProgram::BufferOverlay static
Name of the overlay information frame variable buffer.
BufferPass
C3D_API const Castor::String Castor3D::ShaderProgram::BufferPass static
Name of the pass frame variable buffer.
BufferScene
C3D_API const Castor::String Castor3D::ShaderProgram::BufferScene static
Name of the scene frame variable buffer.
BufferSkinning
C3D_API const Castor::String Castor3D::ShaderProgram::BufferSkinning static
Name of the skinning animation frame variable buffer.
CameraPos
C3D_API const Castor::String Castor3D::ShaderProgram::CameraPos static
Name of the camera position frame variable.
Colour
C3D_API const Castor::String Castor3D::ShaderProgram::Colour static
Name of the colour attribute.
Colour2
C3D_API const Castor::String Castor3D::ShaderProgram::Colour2 static
Name of the colour attribute for per-vertex animations.
Dimensions
C3D_API const Castor::String Castor3D::ShaderProgram::Dimensions static
Name of the billboard dimensions frame variable.
FogDensity
C3D_API const Castor::String Castor3D::ShaderProgram::FogDensity static
Name of the fog's density frame variable.
FogType
C3D_API const Castor::String Castor3D::ShaderProgram::FogType static
Name of the fog type frame variable.
Lights
C3D_API const Castor::String Castor3D::ShaderProgram::Lights static
Name of the lights frame variable.
LightsCount
C3D_API const Castor::String Castor3D::ShaderProgram::LightsCount static
Name of the lights count frame variable.
m_activeShaders
std::vector< ShaderObjectSPtr > Castor3D::ShaderProgram::m_activeShaders protected
The active shaders array.
m_arrayFiles
std::array< Castor::Path, size_t(ShaderModel::eCount) > Castor3D::ShaderProgram::m_arrayFiles protected
Array of files path, sorted by shader model.
m_atomicCounterBuffers
std::array< AtomicCounterBufferPtrList, size_t(ShaderType::eCount) > Castor3D::ShaderProgram::m_atomicCounterBuffers protected
The atomic counter buffers map, ordered by shader type.
Referenced by GetAtomicCounterBuffers().
m_atomicCounterBuffersByName
AtomicCounterBufferPtrStrMap Castor3D::ShaderProgram::m_atomicCounterBuffersByName protected
The atomic counter buffers map, ordered by name.
m_declaration
BufferDeclaration Castor3D::ShaderProgram::m_declaration protected
The transform feedback layout.
Referenced by SetTransformLayout().
m_listAtomicCounterBuffers
AtomicCounterBufferPtrList Castor3D::ShaderProgram::m_listAtomicCounterBuffers protected
The atomic counter buffers map.
Referenced by GetAtomicCounterBuffers().
m_listStorageBuffers
ShaderStorageBufferPtrList Castor3D::ShaderProgram::m_listStorageBuffers protected
The storage buffers map.
Referenced by GetShaderStorageBuffers().
m_shaders
std::array< ShaderObjectSPtr, size_t(ShaderType::eCount) > Castor3D::ShaderProgram::m_shaders protected
The shaders array.
m_status
ProgramStatus Castor3D::ShaderProgram::m_status { ProgramStatus::eNotLinked } protected
< The program status.
Referenced by GetStatus().
m_storageBuffers
std::array< ShaderStorageBufferPtrList, size_t(ShaderType::eCount) > Castor3D::ShaderProgram::m_storageBuffers protected
The storage buffers map, ordered by shader type.
Referenced by GetShaderStorageBuffers().
m_storageBuffersByName
ShaderStorageBufferPtrStrMap Castor3D::ShaderProgram::m_storageBuffersByName protected
The storage buffers map, ordered by name.
MapAmbient
C3D_API const Castor::String Castor3D::ShaderProgram::MapAmbient static
Name of the ambient texture frame variable.
MapColour
C3D_API const Castor::String Castor3D::ShaderProgram::MapColour static
Name of the colour texture frame variable.
MapDiffuse
C3D_API const Castor::String Castor3D::ShaderProgram::MapDiffuse static
Name of the diffuse texture frame variable.
MapEmissive
C3D_API const Castor::String Castor3D::ShaderProgram::MapEmissive static
Name of the emissive texture frame variable.
MapGloss
C3D_API const Castor::String Castor3D::ShaderProgram::MapGloss static
Name of the shininess texture frame variable.
MapHeight
C3D_API const Castor::String Castor3D::ShaderProgram::MapHeight static
Name of the height texture frame variable.
MapNormal
C3D_API const Castor::String Castor3D::ShaderProgram::MapNormal static
Name of the emissive texture frame variable.
MapOpacity
C3D_API const Castor::String Castor3D::ShaderProgram::MapOpacity static
Name of the opacity texture frame variable.
MapShadow
C3D_API const Castor::String Castor3D::ShaderProgram::MapShadow static
Name of the shadow map image frame variable.
MapSpecular
C3D_API const Castor::String Castor3D::ShaderProgram::MapSpecular static
Name of the specular texture frame variable.
MapText
C3D_API const Castor::String Castor3D::ShaderProgram::MapText static
Name of the overlay text image frame variable.
MatAmbient
C3D_API const Castor::String Castor3D::ShaderProgram::MatAmbient static
Name of the ambient material colour frame variable.
MatDiffuse
C3D_API const Castor::String Castor3D::ShaderProgram::MatDiffuse static
Name of the diffuse material colour frame variable.
MatEmissive
C3D_API const Castor::String Castor3D::ShaderProgram::MatEmissive static
Name of the emissive material colour frame variable.
MatOpacity
C3D_API const Castor::String Castor3D::ShaderProgram::MatOpacity static
Name of the material opacity frame variable.
MatShininess
C3D_API const Castor::String Castor3D::ShaderProgram::MatShininess static
Name of the material shininess frame variable.
MatSpecular
C3D_API const Castor::String Castor3D::ShaderProgram::MatSpecular static
Name of the specular material colour frame variable.
Normal
C3D_API const Castor::String Castor3D::ShaderProgram::Normal static
Name of the normal attribute.
Normal2
C3D_API const Castor::String Castor3D::ShaderProgram::Normal2 static
Name of the normal attribute for per-vertex animations.
OvPosition
C3D_API const Castor::String Castor3D::ShaderProgram::OvPosition static
Name of the overlay position frame variable.
Position
C3D_API const Castor::String Castor3D::ShaderProgram::Position static
Name of the position attribute.
Position2
C3D_API const Castor::String Castor3D::ShaderProgram::Position2 static
Name of the position attribute for per-vertex animations.
ShadowReceiver
C3D_API const Castor::String Castor3D::ShaderProgram::ShadowReceiver static
Name of the shadow receiver status frame variable.
Tangent
C3D_API const Castor::String Castor3D::ShaderProgram::Tangent static
Name of the tangent attribute.
Tangent2
C3D_API const Castor::String Castor3D::ShaderProgram::Tangent2 static
Name of the tangent attribute for per-vertex animations.
Text
C3D_API const Castor::String Castor3D::ShaderProgram::Text static
Name of the text overlay texture attribute.
Texture
C3D_API const Castor::String Castor3D::ShaderProgram::Texture static
Name of the texture attribute.
Texture2
C3D_API const Castor::String Castor3D::ShaderProgram::Texture2 static
Name of the texture attribute for per-vertex animations.
Time
C3D_API const Castor::String Castor3D::ShaderProgram::Time static
Name of the morphing time attribute.
Transform
C3D_API const Castor::String Castor3D::ShaderProgram::Transform static
Name of the instance transform attribute.
Weights0
C3D_API const Castor::String Castor3D::ShaderProgram::Weights0 static
Name of the first bones weight attribute.
Weights1
C3D_API const Castor::String Castor3D::ShaderProgram::Weights1 static
Name of the second bones weight attribute.
WindowSize
C3D_API const Castor::String Castor3D::ShaderProgram::WindowSize static
Name of the window dimensions frame variable.
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Shader/ShaderProgram.hpp