Castor3D: Castor3D::ChunkParser< Castor::String > Class Template Reference
Castor3D::ChunkParser< Castor::String > Class Template Reference
ChunkParser specialisation for Castor::String.
Static Public Member Functions
static bool Parse (Castor::String &p_value, BinaryChunk &p_chunk)
Retrieves a value from a chunk.
Static Public Member Functions inherited from Castor3D::ChunkParserBase
static bool Parse (uint8_t *p_values, size_t p_size, BinaryChunk &p_chunk)
Retrieves a value array from a chunk.
Detailed Description
template<>
class Castor3D::ChunkParser< Castor::String >
ChunkParser specialisation for Castor::String.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
08/04/2014
Member Function Documentation
Parse()
static bool Castor3D::ChunkParser< Castor::String >::Parse (Castor::String & p_value, BinaryChunk & p_chunk) inline static
Retrieves a value from a chunk.
Parameters
[out] p_value Receives the parsed value
[in] p_chunk The chunk containing the value
Returns
false if any error occured
References Castor3D::BinaryChunk::CheckAvailable(), Castor3D::BinaryChunk::GetRemaining(), and Castor3D::ChunkParserBase::Parse().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Binary/ChunkParser.hpp