Castor3D: castor3d::VoxelizerUbo Class Reference
castor3d::VoxelizerUbo Class Reference
#include <VoxelizerUbo.hpp>
Public Types
using Configuration = VoxelizerUboConfiguration
Public Member Functions
C3D_API VoxelizerUbo (VoxelizerUbo const &rhs)=delete
C3D_API VoxelizerUbo & operator= (VoxelizerUbo const &rhs)=delete
C3D_API VoxelizerUbo (VoxelizerUbo &&rhs) noexcept=default
C3D_API VoxelizerUbo & operator= (VoxelizerUbo &&rhs) noexcept=delete
C3D_API VoxelizerUbo (RenderDevice const &device)
C3D_API ~VoxelizerUbo () noexcept
C3D_API void cpuUpdate (VctConfig const &voxelConfig, float worldToGrid, uint32_t voxelGridSize)
void createPassBinding (crg::FramePass &pass, uint32_t binding) const
void createSizedBinding (ashes::DescriptorSet &descriptorSet, VkDescriptorSetLayoutBinding const &layoutBinding) const
ashes::WriteDescriptorSet getDescriptorWrite (uint32_t dstBinding, uint32_t dstArrayElement=0u) const
void addDescriptorWrite (ashes::WriteDescriptorSetArray &descriptorWrites, uint32_t &dstBinding, uint32_t dstArrayElement=0u) const
UniformBufferOffsetT< Configuration > const & getUbo () const
Member Typedef Documentation
Configuration
using castor3d::VoxelizerUbo::Configuration = VoxelizerUboConfiguration
Constructor & Destructor Documentation
VoxelizerUbo() [1/3]
C3D_API castor3d::VoxelizerUbo::VoxelizerUbo (VoxelizerUbo const & rhs) delete
VoxelizerUbo() [2/3]
C3D_API castor3d::VoxelizerUbo::VoxelizerUbo (VoxelizerUbo && rhs) default noexcept
VoxelizerUbo() [3/3]
C3D_API castor3d::VoxelizerUbo::VoxelizerUbo (RenderDevice const & device) explicit
~VoxelizerUbo()
C3D_API castor3d::VoxelizerUbo::~VoxelizerUbo () noexcept
Member Function Documentation
addDescriptorWrite()
void castor3d::VoxelizerUbo::addDescriptorWrite (ashes::WriteDescriptorSetArray & descriptorWrites, uint32_t & dstBinding, uint32_t dstArrayElement = 0u) const inline
References getDescriptorWrite().
cpuUpdate()
C3D_API void castor3d::VoxelizerUbo::cpuUpdate (VctConfig const & voxelConfig, float worldToGrid, uint32_t voxelGridSize)
createPassBinding()
void castor3d::VoxelizerUbo::createPassBinding (crg::FramePass & pass, uint32_t binding) const inline
References castor3d::UniformBufferOffsetT< DataT >::createPassBinding().
createSizedBinding()
void castor3d::VoxelizerUbo::createSizedBinding (ashes::DescriptorSet & descriptorSet, VkDescriptorSetLayoutBinding const & layoutBinding) const inline
References castor3d::UniformBufferOffsetT< DataT >::createSizedBinding().
getDescriptorWrite()
ashes::WriteDescriptorSet castor3d::VoxelizerUbo::getDescriptorWrite (uint32_t dstBinding, uint32_t dstArrayElement = 0u) const inline
References castor3d::UniformBufferOffsetT< DataT >::getDescriptorWrite().
Referenced by addDescriptorWrite().
getUbo()
UniformBufferOffsetT< Configuration > const & castor3d::VoxelizerUbo::getUbo () const inline
operator=() [1/2]
C3D_API VoxelizerUbo & castor3d::VoxelizerUbo::operator= (VoxelizerUbo && rhs) delete noexcept
operator=() [2/2]
C3D_API VoxelizerUbo & castor3d::VoxelizerUbo::operator= (VoxelizerUbo const & rhs) delete
The documentation for this class was generated from the following file:
Castor3D/Shader/Ubos/VoxelizerUbo.hpp