Castor3D: castor3d::GpuBufferBase Class Reference
castor3d::GpuBufferBase Class Reference
#include <GpuBuffer.hpp>
Public Member Functions
C3D_API GpuBufferBase (RenderSystem const &renderSystem, VkBufferUsageFlags usage, VkMemoryPropertyFlags memoryFlags, castor::String const &debugName, ashes::QueueShare sharingMode, VkDeviceSize allocatedSize)
Constructor.
C3D_API void upload (UploadData &uploader)
Uploads all ready memory ranges to VRAM.
C3D_API void upload (UploadData &uploader, VkDeviceSize offset, VkDeviceSize size, VkAccessFlags dstAccessFlags, VkPipelineStageFlags dstPipelineFlags)
Uploads a memory range.
C3D_API void markDirty (VkDeviceSize offset, VkDeviceSize size, VkAccessFlags dstAccessFlags, VkPipelineStageFlags dstPipelineFlags)
Marks a memory range to be ready for upload.
bool hasBuffer () const noexcept
ashes::Buffer< uint8_t > const & getBuffer () const noexcept
ashes::Buffer< uint8_t > & getBuffer () noexcept
template<typename DataT >
DataT const & getData (VkDeviceSize offset) const noexcept
template<typename DataT >
DataT & getData (VkDeviceSize offset) noexcept
castor::ByteArrayView const & getDatas () const noexcept
castor::ByteArrayView & getDatas () noexcept
Friends
class GpuBufferPool
Constructor & Destructor Documentation
GpuBufferBase()
C3D_API castor3d::GpuBufferBase::GpuBufferBase (RenderSystem const & renderSystem, VkBufferUsageFlags usage, VkMemoryPropertyFlags memoryFlags, castor::String const & debugName, ashes::QueueShare sharingMode, VkDeviceSize allocatedSize)
Constructor.
Parameters
[in] renderSystem The device on which the storage is allocated.
[in] usage The buffer targets.
[in] memoryFlags The buffer memory properties.
[in] debugName The debug name.
[in] sharingMode The sharing mode.
[in] allocatedSize The buffer size.
Member Function Documentation
getBuffer() [1/2]
ashes::Buffer< uint8_t > const & castor3d::GpuBufferBase::getBuffer () const inline noexcept
Returns
The internal buffer.
Referenced by castor3d::GpuBufferOffsetT< DataT >::getBuffer(), and castor3d::GpuBufferOffsetT< DataT >::getBuffer().
getBuffer() [2/2]
ashes::Buffer< uint8_t > & castor3d::GpuBufferBase::getBuffer () inline noexcept
Returns
The internal buffer.
getData() [1/2]
template<typename DataT > DataT const & castor3d::GpuBufferBase::getData (VkDeviceSize offset) const inline noexcept
Returns
The N-th instance of the data.
Parameters
[in] offset The memory chunk offset.
getData() [2/2]
template<typename DataT > DataT & castor3d::GpuBufferBase::getData (VkDeviceSize offset) inline noexcept
Returns
The N-th instance of the data.
Parameters
[in] offset The memory chunk offset.
getDatas() [1/2]
castor::ByteArrayView const & castor3d::GpuBufferBase::getDatas () const inline noexcept
Returns
The data.
Referenced by castor3d::GpuBufferOffsetT< DataT >::getData().
getDatas() [2/2]
castor::ByteArrayView & castor3d::GpuBufferBase::getDatas () inline noexcept
Returns
The data.
hasBuffer()
bool castor3d::GpuBufferBase::hasBuffer () const inline noexcept
Returns
The internal buffer.
Referenced by castor3d::GpuBufferOffsetT< DataT >::operator bool().
markDirty()
C3D_API void castor3d::GpuBufferBase::markDirty (VkDeviceSize offset, VkDeviceSize size, VkAccessFlags dstAccessFlags, VkPipelineStageFlags dstPipelineFlags)
Marks a memory range to be ready for upload.
Parameters
[in] offset,size The memory range.
[in] dstAccessFlags The access flags wanted after upload.
[in] dstPipelineFlags The pipeline stage flags wanted after upload.
Referenced by castor3d::GpuBufferOffsetT< DataT >::markDirty().
upload() [1/2]
C3D_API void castor3d::GpuBufferBase::upload (UploadData & uploader)
Uploads all ready memory ranges to VRAM.
Parameters
[in,out] uploader Receives the upload requests.
upload() [2/2]
C3D_API void castor3d::GpuBufferBase::upload (UploadData & uploader, VkDeviceSize offset, VkDeviceSize size, VkAccessFlags dstAccessFlags, VkPipelineStageFlags dstPipelineFlags)
Uploads a memory range.
Parameters
[in,out] uploader Receives the upload requests.
[in] offset,size The memory range.
[in] dstAccessFlags The access flags wanted after upload.
[in] dstPipelineFlags The pipeline stage flags wanted after upload.
Friends And Related Symbol Documentation
GpuBufferPool
friend class GpuBufferPool friend
The documentation for this class was generated from the following file:
Castor3D/Buffer/GpuBuffer.hpp