Castor3D: castor3d::TextureUnit Class Reference
castor3d::TextureUnit Class Reference
Texture unit representation.
Classes
class TextWriter
TextureUnit loader.
Public Member Functions
C3D_API TextureUnit (Engine &engine)
Constructor.
C3D_API ~TextureUnit ()
Destructor.
C3D_API bool initialise ()
Initialises the texture, id est : fills the image buffer, creates the texture in the render system.
C3D_API void cleanup ()
Cleans up the texture.
C3D_API void setTexture (TextureLayoutSPtr texture)
sets the texture.
C3D_API void bind () const
Applies the texture unit.
C3D_API void unbind () const
Removes the texture unit from the stack, in order not to interfere with other ones.
C3D_API TextureType getType () const
castor3d::TextureLayoutSPtr getTexture () const
castor3d::TextureChannel getChannel () const
Retrieves the texture channel.
void setChannel (castor3d::TextureChannel value)
sets the texture channel.
uint32_t getIndex () const
void setIndex (uint32_t value)
sets the unit index.
void setRenderTarget (RenderTargetSPtr value)
sets the target holding the texture.
void setSampler (SamplerSPtr value)
Defines the texture sampler.
SamplerSPtr getSampler () const
bool isTextured () const
void setAutoMipmaps (bool value)
sets the auto mipmaps generation status.
bool getAutoMipmaps () const
RenderTargetSPtr getRenderTarget () const
Friends
class TextureRenderer
Detailed Description
Texture unit representation.
Author
Sylvain DOREMUS
Version
0.1
Date
09/02/2010
Remarks
A texture unit is a texture with few options, like channel, blend modes, transformations...
Constructor & Destructor Documentation
TextureUnit()
C3D_API castor3d::TextureUnit::TextureUnit (Engine & engine) explicit
Constructor.
Parameters
engine The engine.
~TextureUnit()
C3D_API castor3d::TextureUnit::~TextureUnit ()
Destructor.
Member Function Documentation
bind()
C3D_API void castor3d::TextureUnit::bind () const
Applies the texture unit.
Referenced by castor3d::doBindPass().
cleanup()
C3D_API void castor3d::TextureUnit::cleanup ()
Cleans up the texture.
getAutoMipmaps()
bool castor3d::TextureUnit::getAutoMipmaps () const inline
Returns
The the auto mipmaps generation status.
getChannel()
castor3d::TextureChannel castor3d::TextureUnit::getChannel () const inline
Retrieves the texture channel.
Returns
The value.
getIndex()
uint32_t castor3d::TextureUnit::getIndex () const inline
Returns
The unit index.
getRenderTarget()
RenderTargetSPtr castor3d::TextureUnit::getRenderTarget () const inline
Returns
The render target.
getSampler()
SamplerSPtr castor3d::TextureUnit::getSampler () const inline
Returns
The sampler.
Referenced by castor3d::doFillShaderPbrMaps().
getTexture()
castor3d::TextureLayoutSPtr castor3d::TextureUnit::getTexture () const inline
Returns
The texture.
Referenced by castor3d::doFillShaderPbrMaps(), castor3d::EnvironmentMap::getSize(), and castor3d::ReflectionPass::getSsao().
getType()
C3D_API TextureType castor3d::TextureUnit::getType () const
Returns
The texture dimension.
initialise()
C3D_API bool castor3d::TextureUnit::initialise ()
Initialises the texture, id est : fills the image buffer, creates the texture in the render system.
isTextured()
bool castor3d::TextureUnit::isTextured () const inline
Returns
false if the texture is null.
setAutoMipmaps()
void castor3d::TextureUnit::setAutoMipmaps (bool value) inline
sets the auto mipmaps generation status.
Parameters
[in] value The new value.
setChannel()
void castor3d::TextureUnit::setChannel (castor3d::TextureChannel value) inline
sets the texture channel.
Parameters
[in] value The new value.
setIndex()
void castor3d::TextureUnit::setIndex (uint32_t value) inline
sets the unit index.
Parameters
[in] value The new value.
Referenced by castor3d::doBindPass(), and castor3d::LightPassShadow< LtType >::render().
setRenderTarget()
void castor3d::TextureUnit::setRenderTarget (RenderTargetSPtr value) inline
sets the target holding the texture.
Parameters
[in] value The new value.
setSampler()
void castor3d::TextureUnit::setSampler (SamplerSPtr value) inline
Defines the texture sampler.
Parameters
[in] value The sampler.
setTexture()
C3D_API void castor3d::TextureUnit::setTexture (TextureLayoutSPtr texture)
sets the texture.
Parameters
[in] texture The texture.
unbind()
C3D_API void castor3d::TextureUnit::unbind () const
Removes the texture unit from the stack, in order not to interfere with other ones.
Friends And Related Function Documentation
TextureRenderer
friend class TextureRenderer friend
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Texture/TextureUnit.hpp