Castor3D: castor3d::ProgressStyle Class Reference
castor3d::ProgressStyle Class Reference
#include <StyleProgress.hpp>
Public Member Functions
ProgressStyle (castor::String const &name, Engine &engine, castor::String const &fontName)
ProgressStyle (castor::String const &name, Scene *scene, Engine &engine, castor::String const &fontName)
castor::String const & getTitleFontName () const
MaterialObs getTitleMaterial () const
PanelStyle const & getContainerStyle () const
PanelStyle const & getProgressStyle () const
castor::String const & getTextFontName () const
MaterialObs getTextMaterial () const
void setTitleFontName (castor::String value)
void setTitleMaterial (MaterialObs value)
PanelStyle & getContainerStyle ()
PanelStyle & getProgressStyle ()
StaticStyle & getLabelStyle ()
void setTextFontName (castor::StringView value)
void setTextMaterial (MaterialObs value)
Public Member Functions inherited from castor3d::ControlStyle
virtual C3D_API ~ControlStyle () noexcept=default
ControlStyle (ControlType type, castor::String const &name, Scene *scene, Engine &engine, MouseCursor cursor=MouseCursor::eArrow)
void setBackgroundMaterial (MaterialObs value)
void setForegroundMaterial (MaterialObs value)
void setCursor (MouseCursor value) noexcept
void setBackgroundInvisible (bool value) noexcept
void setForegroundInvisible (bool value) noexcept
bool isBackgroundInvisible () const noexcept
bool isForegroundInvisible () const noexcept
MaterialObs getBackgroundMaterial () const noexcept
MaterialObs getForegroundMaterial () const noexcept
ControlType getType () const noexcept
MouseCursor getCursor () const noexcept
Engine & getEngine () const noexcept
bool hasScene () const noexcept
Scene & getScene () const noexcept
Public Member Functions inherited from castor::NamedBaseT< T >
NamedBaseT (T name) noexcept
Constructor.
T const & getName () const noexcept
Retrieves the name.
void rename (T name) noexcept
Static Public Attributes
static ControlType constexpr Type = ControlType::eProgress
Additional Inherited Members
Protected Member Functions inherited from castor3d::ControlStyle
MaterialObs doCreateMaterial (MaterialObs material, float offset, castor::String const &suffix) const
Protected Attributes inherited from castor::NamedBaseT< T >
T m_name
Constructor & Destructor Documentation
ProgressStyle() [1/2]
castor3d::ProgressStyle::ProgressStyle (castor::String const & name, Engine & engine, castor::String const & fontName) inline
ProgressStyle() [2/2]
castor3d::ProgressStyle::ProgressStyle (castor::String const & name, Scene * scene, Engine & engine, castor::String const & fontName) inline
References castor3d::ControlStyle::setBackgroundInvisible(), and setTextMaterial().
Member Function Documentation
getContainerStyle() [1/2]
PanelStyle & castor3d::ProgressStyle::getContainerStyle () inline
getContainerStyle() [2/2]
PanelStyle const & castor3d::ProgressStyle::getContainerStyle () const inline
getLabelStyle()
StaticStyle & castor3d::ProgressStyle::getLabelStyle () inline
getProgressStyle() [1/2]
PanelStyle & castor3d::ProgressStyle::getProgressStyle () inline
getProgressStyle() [2/2]
PanelStyle const & castor3d::ProgressStyle::getProgressStyle () const inline
getTextFontName()
castor::String const & castor3d::ProgressStyle::getTextFontName () const inline
References castor3d::StaticStyle::getFontName().
getTextMaterial()
MaterialObs castor3d::ProgressStyle::getTextMaterial () const inline
References castor3d::ControlStyle::getForegroundMaterial().
getTitleFontName()
castor::String const & castor3d::ProgressStyle::getTitleFontName () const inline
getTitleMaterial()
MaterialObs castor3d::ProgressStyle::getTitleMaterial () const inline
setTextFontName()
void castor3d::ProgressStyle::setTextFontName (castor::StringView value) inline
References castor3d::StaticStyle::setFont().
setTextMaterial()
void castor3d::ProgressStyle::setTextMaterial (MaterialObs value) inline
References castor3d::StaticStyle::setTextMaterial().
Referenced by ProgressStyle().
setTitleFontName()
void castor3d::ProgressStyle::setTitleFontName (castor::String value) inline
setTitleMaterial()
void castor3d::ProgressStyle::setTitleMaterial (MaterialObs value) inline
Member Data Documentation
Type
ControlType constexpr castor3d::ProgressStyle::Type = ControlType::eProgress static constexpr
The documentation for this class was generated from the following file:
Castor3D/Gui/Theme/StyleProgress.hpp