Castor3D: castor3d::OcclusionMapComponent Struct Reference
castor3d::OcclusionMapComponent Struct Reference
#include <OcclusionMapComponent.hpp>
Classes
struct ComponentsShader
struct MaterialShader
class Plugin
Public Member Functions
C3D_API OcclusionMapComponent (Pass &pass)
Public Member Functions inherited from castor3d::PassMapComponent
C3D_API PassMapComponent (Pass &pass, castor::String type, TextureFlags textureFlags, castor::StringArray deps={})
Constructor.
PassComponentTextureFlag getTextureFlags () const noexcept
C3D_API void fillConfig (TextureConfiguration &config, ConfigurationVisitorBase &vis) const override
ConfigurationVisitorBase acceptance function, for a specific texture configuration.
Public Member Functions inherited from castor3d::PassComponent
C3D_API PassComponent (Pass &pass, castor::String type, castor::StringArray deps={})
Constructor.
virtual C3D_API ~PassComponent () noexcept=default
C3D_API PassComponentUPtr clone (Pass &pass) const
virtual C3D_API void onAddToPass () const
Called when the component is added to the pass.
C3D_API bool writeText (castor::String const &tabs, castor::Path const &folder, castor::String const &subfolder, castor::StringStream &file) const
Writes the component content to text.
C3D_API void fillBuffer (PassBuffer &buffer) const
Fills the pass buffer with this pass data.
virtual C3D_API void accept (ConfigurationVisitorBase &vis)
ConfigurationVisitorBase acceptance function.
virtual C3D_API void update ()
C3D_API void fillChannel (TextureConfiguration &configuration, uint32_t mask) const
Fills the texture configuration for use with this component.
virtual C3D_API bool hasColour () const
virtual C3D_API castor::HdrRgbColour const & getColour () const
virtual C3D_API void setColour (castor::HdrRgbColour v)
virtual C3D_API PassComponentFlag getPassFlags () const
castor::String const & getType () const
castor::StringArray const & getDependencies () const
PassComponentPlugin const & getPlugin () const
PassComponentID getId () const
void setColour (castor::RgbColour const &v, float gamma=2.2f)
void setColour (castor::Coords3f const &v)
void setColour (castor::Point3f const &v)
Public Member Functions inherited from castor::OwnedBy< Pass >
Pass * getOwner () const
Static Public Member Functions
static PassComponentPluginUPtr createPlugin (PassComponentRegister const &passComponent)
Static Public Attributes
static constexpr TextureFlag Occlusion = TextureFlag(0x01u)
static C3D_API castor::String const TypeName
Additional Inherited Members
Protected Member Functions inherited from castor::OwnedBy< Pass >
OwnedBy (Pass &owner)
Constructor.
Protected Attributes inherited from castor3d::PassComponent
castor::String m_type
castor::StringArray m_dependencies
PassComponentID m_id
PassComponentPlugin const & m_plugin
std::atomic_bool & m_dirty
shader::PassMaterialShader * m_materialShader {}
Constructor & Destructor Documentation
OcclusionMapComponent()
C3D_API castor3d::OcclusionMapComponent::OcclusionMapComponent (Pass & pass) explicit
Member Function Documentation
createPlugin()
static PassComponentPluginUPtr castor3d::OcclusionMapComponent::createPlugin (PassComponentRegister const & passComponent) inline static
Member Data Documentation
Occlusion
constexpr TextureFlag castor3d::OcclusionMapComponent::Occlusion = TextureFlag(0x01u) static constexpr
Referenced by castor3d::OcclusionMapComponent::ComponentsShader::getTextureFlags(), castor3d::OcclusionMapComponent::Plugin::getTextureFlags(), and castor3d::OcclusionMapComponent::Plugin::getTextureFlagsName().
TypeName
C3D_API castor::String const castor3d::OcclusionMapComponent::TypeName static
The documentation for this struct was generated from the following file:
Castor3D/Material/Pass/Component/Map/OcclusionMapComponent.hpp