Castor3D: castor3d::MipView Struct Reference
castor3d::MipView Struct Reference
#include <TextureLayout.hpp>
Public Member Functions
template<typename FuncT >
void forMipView (FuncT function) const
template<typename FuncT >
void forEachLeafView (FuncT function) const
template<typename FuncT >
void forEachView (FuncT function) const
template<typename FuncT >
void forEachFirstMipView (FuncT function) const
Public Attributes
TextureViewUPtr view
std::vector< TextureViewUPtr > levels
Member Function Documentation
forEachFirstMipView()
template<typename FuncT > void castor3d::MipView::forEachFirstMipView (FuncT function) const inline
References forMipView(), and levels.
Referenced by castor3d::CubeView::forEachFirstMipView(), and castor3d::TextureLayout::forEachFirstMipView().
forEachLeafView()
template<typename FuncT > void castor3d::MipView::forEachLeafView (FuncT function) const inline
References forMipView(), and levels.
Referenced by forEachView().
forEachView()
template<typename FuncT > void castor3d::MipView::forEachView (FuncT function) const inline
References forEachLeafView(), and forMipView().
Referenced by castor3d::CubeView::forEachView(), and castor3d::TextureLayout::forEachView().
forMipView()
template<typename FuncT > void castor3d::MipView::forMipView (FuncT function) const inline
References view.
Referenced by forEachFirstMipView(), forEachLeafView(), and forEachView().
Member Data Documentation
levels
std::vector< TextureViewUPtr > castor3d::MipView::levels
Referenced by forEachFirstMipView(), forEachLeafView(), castor3d::TextureLayout::getLayerCubeFaceMipView(), and castor3d::TextureLayout::getMipView().
view
TextureViewUPtr castor3d::MipView::view
Referenced by forMipView(), castor3d::TextureLayout::getDefaultView(), castor3d::TextureLayout::getLayer2DView(), castor3d::TextureLayout::getLayerCubeFaceView(), castor3d::TextureLayout::getLayerCubeView(), and castor3d::TextureLayout::getSliceView().
The documentation for this struct was generated from the following file:
Material/Texture/TextureLayout.hpp