Castor3D: castor3d::TriFaceMapping Class Reference
castor3d::TriFaceMapping Class Reference
Public Member Functions
C3D_API TriFaceMapping (Submesh &submesh)
Constructor.
C3D_API void clearFaces ()
Clears this submesh's face array.
C3D_API Face addFace (uint32_t a, uint32_t b, uint32_t c)
Creates and adds a face to the submesh.
C3D_API void addFaceGroup (FaceIndices const *const begin, FaceIndices const *const end)
Creates and adds faces to the submesh.
C3D_API void addQuadFace (uint32_t a, uint32_t b, uint32_t c, uint32_t d, castor::Point3f const &minUV=castor::Point3f(), castor::Point3f const &maxUV=castor::Point3f(1, 1, 1))
Creates and adds a quad face to the submesh.
C3D_API void computeFacesFromPolygonVertex ()
Creates faces from the points.
C3D_API void computeNormals (Face const &face)
Computes normal and tangent for each vertex of the given face.
C3D_API void computeTangents (Face const &face)
Computes tangent for each vertex of the given face.
C3D_API void computeTangentsFromNormals ()
Computes tangent for each vertex of the submesh.
C3D_API uint32_t getCount () const override
C3D_API uint32_t getComponentsCount () const override
C3D_API void sortByDistance (castor::Point3f const &cameraPosition) override
Sorts the face from farthest to nearest from the camera.
C3D_API void computeNormals (bool reverted=false) override
Generates normals and tangents.
void addFaceGroup (std::vector< FaceIndices > const &faces)
Creates and adds faces to the submesh.
template<size_t Count>
void addFaceGroup (std::array< FaceIndices, Count > const &faces)
Creates and adds faces to the submesh.
template<uint32_t Count>
void addFaceGroup (FaceIndices(&faces)[Count])
Creates and adds faces to the submesh.
Face const & operator[] (uint32_t index) const
Retrieves the face at given index.
FaceArray const & getFaces () const
FaceArray & getFaces ()
Public Member Functions inherited from castor3d::IndexMapping
C3D_API IndexMapping (Submesh &submesh, castor::String const &type)
Constructor.
void gather (MaterialSPtr material, ashes::BufferCRefArray &buffers, std::vector< uint64_t > &offsets, ashes::PipelineVertexInputStateCreateInfoCRefArray &layouts, uint32_t instanceMult) override
Gathers buffers that need to go in a VAO.
ProgramFlags getProgramFlags (MaterialSPtr material) const override
Public Member Functions inherited from castor3d::SubmeshComponent
C3D_API SubmeshComponent (Submesh &submesh, castor::String const &type)
Constructor.
virtual C3D_API ~SubmeshComponent () noexcept=default
Destructor.
C3D_API bool initialise (RenderDevice const &device)
Initialises the submesh.
C3D_API void cleanup ()
Cleans the submesh.
C3D_API void fill (RenderDevice const &device)
Initialises the submesh.
C3D_API void upload ()
Uploads data on VRAM.
virtual C3D_API void setMaterial (MaterialSPtr oldMaterial, MaterialSPtr newMaterial, bool update)
Sets the material.
castor::String const & getType () const
void needsUpdate ()
Sets the component to be updated.
Static Public Attributes
static C3D_API castor::String const Name
Constructor & Destructor Documentation
TriFaceMapping()
C3D_API castor3d::TriFaceMapping::TriFaceMapping (Submesh & submesh) explicit
Constructor.
Parameters
[in] submesh The parent submesh.
Member Function Documentation
addFace()
C3D_API Face castor3d::TriFaceMapping::addFace (uint32_t a, uint32_t b, uint32_t c)
Creates and adds a face to the submesh.
Parameters
[in] a The first face's vertex index.
[in] b The second face's vertex index.
[in] c The third face's vertex index.
Returns
The created face.
addFaceGroup() [1/4]
C3D_API void castor3d::TriFaceMapping::addFaceGroup (FaceIndices const *const begin, FaceIndices const *const end)
Creates and adds faces to the submesh.
Parameters
[in] begin The faces data begin.
[in] end The faces data end.
Referenced by addFaceGroup().
addFaceGroup() [2/4]
void castor3d::TriFaceMapping::addFaceGroup (std::vector< FaceIndices > const & faces) inline
Creates and adds faces to the submesh.
Parameters
[in] faces The faces.
References addFaceGroup().
addFaceGroup() [3/4]
template<size_t Count> void castor3d::TriFaceMapping::addFaceGroup (std::array< FaceIndices, Count > const & faces) inline
Creates and adds faces to the submesh.
Parameters
[in] faces The faces.
References addFaceGroup().
addFaceGroup() [4/4]
template<uint32_t Count> void castor3d::TriFaceMapping::addFaceGroup (FaceIndices(&) faces[Count]) inline
Creates and adds faces to the submesh.
Parameters
[in] faces The faces.
References addFaceGroup().
addQuadFace()
C3D_API void castor3d::TriFaceMapping::addQuadFace (uint32_t a, uint32_t b, uint32_t c, uint32_t d, castor::Point3f const & minUV = castor::Point3f(), castor::Point3f const & maxUV = castor::Point3f(1, 1, 1))
Creates and adds a quad face to the submesh.
Parameters
[in] a The first face's vertex index.
[in] b The second face's vertex index.
[in] c The third face's vertex index.
[in] d The fourth face's vertex index.
[in] minUV The UV of the bottom left corner.
[in] maxUV The UV of the top right corner.
Returns
The created face.
clearFaces()
C3D_API void castor3d::TriFaceMapping::clearFaces ()
Clears this submesh's face array.
computeFacesFromPolygonVertex()
C3D_API void castor3d::TriFaceMapping::computeFacesFromPolygonVertex ()
Creates faces from the points.
Remarks
This function assumes the points are sorted like triangles fan.
computeNormals() [1/2]
C3D_API void castor3d::TriFaceMapping::computeNormals (Face const & face)
Computes normal and tangent for each vertex of the given face.
Parameters
[in] face The face.
computeNormals() [2/2]
C3D_API void castor3d::TriFaceMapping::computeNormals (bool reverted = false) override virtual
Generates normals and tangents.
Parameters
[in] reverted Tells if normals are inverted.
Implements castor3d::IndexMapping.
computeTangents()
C3D_API void castor3d::TriFaceMapping::computeTangents (Face const & face)
Computes tangent for each vertex of the given face.
Parameters
[in] face The face.
computeTangentsFromNormals()
C3D_API void castor3d::TriFaceMapping::computeTangentsFromNormals ()
Computes tangent for each vertex of the submesh.
Remarks
This function supposes the normals are defined.
getComponentsCount()
C3D_API uint32_t castor3d::TriFaceMapping::getComponentsCount () const override virtual
Returns
The components count in an element.
Implements castor3d::IndexMapping.
getCount()
C3D_API uint32_t castor3d::TriFaceMapping::getCount () const override virtual
Returns
The elements count.
Implements castor3d::IndexMapping.
getFaces() [1/2]
FaceArray const& castor3d::TriFaceMapping::getFaces () const inline
Returns
The faces array.
getFaces() [2/2]
FaceArray& castor3d::TriFaceMapping::getFaces () inline
Returns
The faces array.
operator[]()
Face const& castor3d::TriFaceMapping::operator[] (uint32_t index) const inline
Retrieves the face at given index.
Parameters
[in] index The index.
Returns
The value.
sortByDistance()
C3D_API void castor3d::TriFaceMapping::sortByDistance (castor::Point3f const & cameraPosition) override virtual
Sorts the face from farthest to nearest from the camera.
Parameters
[in] cameraPosition The camera position, relative to submesh
Implements castor3d::IndexMapping.
Member Data Documentation
Name
C3D_API castor::String const castor3d::TriFaceMapping::Name static
The documentation for this class was generated from the following file:
Model/Mesh/Submesh/Component/TriFaceMapping.hpp