Castor3D: castor3d::Parameters Class Reference
castor3d::Parameters Class Reference
Configuration parameters.
Public Member Functions
C3D_API Parameters ()
Constructor.
C3D_API ~Parameters ()
Destructor.
C3D_API void parse (castor::String const &p_text)
Parses the given text into a parameters list.
template<typename T >
bool add (castor::String const &p_name, T *p_values, uint32_t p_count)
adds a parameter
void add (Parameters const &p_parameters)
adds a parameters list.
template<typename T , uint32_t N>
bool add (castor::String const &p_name, T const(&p_values)[N])
adds a parameter
template<typename T >
bool add (castor::String const &p_name, T const &p_value)
adds a parameter
bool add (castor::String const &p_name, castor::String const &p_value)
adds a string parameter
template<typename T >
bool set (castor::String const &p_name, T const &p_value)
sets a parameter value
template<typename T >
bool get (castor::String const &p_name, T *p_values, uint32_t p_count) const
Retrieves a parameter value.
template<typename T >
bool get (castor::String const &p_name, T &p_value) const
Retrieves a parameter value.
template<typename T , uint32_t N>
bool get (castor::String const &p_name, T(&p_values)[N]) const
Retrieves a parameter value.
bool get (castor::String const &p_name, castor::String &p_value) const
Retrieves a parameter value.
Detailed Description
Configuration parameters.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
12/11/2012
Remarks
Pair of a name and binary data
Constructor & Destructor Documentation
Parameters()
C3D_API castor3d::Parameters::Parameters () inline
Constructor.
~Parameters()
C3D_API castor3d::Parameters::~Parameters () inline
Destructor.
Member Function Documentation
add() [1/5]
template<typename T > bool castor3d::Parameters::add (castor::String const & p_name, T * p_values, uint32_t p_count) inline
adds a parameter
Remarks
If a parameter with the given name already exists, nothing is done
Parameters
[in] p_name The parameter name
[in] p_values The parameter values
[in] p_count The values count
Returns
false if a parameter with the given name already exists
Referenced by add(), and parse().
add() [2/5]
void castor3d::Parameters::add (Parameters const & p_parameters) inline
adds a parameters list.
Parameters
[in] p_parameters The parameters list.
add() [3/5]
template<typename T , uint32_t N> bool castor3d::Parameters::add (castor::String const & p_name, T const(&) p_values[N]) inline
adds a parameter
Remarks
If a parameter with the given name already exists, nothing is done
Parameters
[in] p_name The parameter name
[in] p_values The parameter values
Returns
false if a parameter with the given name already exists
References add().
add() [4/5]
template<typename T > bool castor3d::Parameters::add (castor::String const & p_name, T const & p_value) inline
adds a parameter
Remarks
If a parameter with the given name already exists, nothing is done
Parameters
[in] p_name The parameter name
[in] p_value The parameter value
Returns
false if a parameter with the given name already exists
References add().
add() [5/5]
bool castor3d::Parameters::add (castor::String const & p_name, castor::String const & p_value) inline
adds a string parameter
Remarks
If a parameter with the given name already exists, nothing is done
Parameters
[in] p_name The parameter name
[in] p_value The parameter value
Returns
false if a parameter with the given name already exists
get() [1/4]
template<typename T > bool castor3d::Parameters::get (castor::String const & p_name, T * p_values, uint32_t p_count) const inline
Retrieves a parameter value.
Parameters
[in] p_name The parameter name
[out] p_values The parameter values
[in] p_count The values available count
Returns
false if there is no parameter with the given name
Referenced by get().
get() [2/4]
template<typename T > bool castor3d::Parameters::get (castor::String const & p_name, T & p_value) const inline
Retrieves a parameter value.
Parameters
[in] p_name The parameter name
[out] p_value The parameter value
Returns
false if there is no parameter with the given name
References get().
get() [3/4]
template<typename T , uint32_t N> bool castor3d::Parameters::get (castor::String const & p_name, T(&) p_values[N]) const inline
Retrieves a parameter value.
Parameters
[in] p_name The parameter name
[out] p_values The parameter values
Returns
false if there is no parameter with the given name
References get().
get() [4/4]
bool castor3d::Parameters::get (castor::String const & p_name, castor::String & p_value) const inline
Retrieves a parameter value.
Parameters
[in] p_name The parameter name
[out] p_value The parameter value
Returns
false if there is no parameter with the given name
parse()
C3D_API void castor3d::Parameters::parse (castor::String const & p_text) inline
Parses the given text into a parameters list.
Parameters
[in] p_text The source text.
References add().
set()
template<typename T > bool castor3d::Parameters::set (castor::String const & p_name, T const & p_value) inline
sets a parameter value
Parameters
[in] p_name The parameter name
[in] p_value The parameter value
Returns
false if there is no parameter with the given name
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Miscellaneous/Parameter.hpp