#include "GlRenderSystem/PrecompiledHeader.hpp"

#include <CastorUtils/Logger.hpp>
#include <CastorUtils/Pixel.hpp>


#include <Castor3D/BillboardList.hpp>
#include <Castor3D/Buffer.hpp>
#include <Castor3D/Camera.hpp>
#include <Castor3D/Context.hpp>
#include <Castor3D/DirectionalLight.hpp>
#include <Castor3D/Engine.hpp>
#include <Castor3D/Face.hpp>
#include <Castor3D/Font.hpp>
#include <Castor3D/FrameBuffer.hpp>
#include <Castor3D/FrameVariable.hpp>
#include <Castor3D/Geometry.hpp>
#include <Castor3D/Light.hpp>
#include <Castor3D/Material.hpp>
#include <Castor3D/Mesh.hpp>
#include <Castor3D/Overlay.hpp>
#include <Castor3D/Pass.hpp>
#include <Castor3D/Pipeline.hpp>
#include <Castor3D/Plugin.hpp>
#include <Castor3D/PointLight.hpp>
#include <Castor3D/RenderSystem.hpp>
#include <Castor3D/RenderTarget.hpp>
#include <Castor3D/RenderTechnique.hpp>
#include <Castor3D/RenderWindow.hpp>
#include <Castor3D/Sampler.hpp>
#include <Castor3D/SceneNode.hpp>
#include <Castor3D/Scene.hpp>
#include <Castor3D/ShaderManager.hpp>
#include <Castor3D/ShaderObject.hpp>
#include <Castor3D/ShaderProgram.hpp>
#include <Castor3D/SpotLight.hpp>
#include <Castor3D/Submesh.hpp>
#include <Castor3D/TextureUnit.hpp>
#include <Castor3D/Texture.hpp>
#include <Castor3D/Version.hpp>
#include <Castor3D/Vertex.hpp>
#include <Castor3D/Viewport.hpp>
#include <Castor3D/WindowHandle.hpp>