Castor3D: castor3d::shader::AppendArrayT< DataT > Class Template Reference
castor3d::shader::AppendArrayT< DataT > Class Template Reference
#include <GlslAppendBuffer.hpp>
Public Member Functions
SDW_DeclStructInstance (, AppendArrayT)
AppendArrayT (sdw::ShaderWriter &writer, sdw::expr::ExprPtr expr, bool enabled)
template<sdw::type::Kind KindT>
DataT operator[] (sdw::IntegerValue< KindT > const &offset) const
DataT operator[] (int32_t offset) const
DataT operator[] (uint32_t offset) const
void resetCount ()
sdw::UInt getCount () const
sdw::UInt incrementCount () const
void appendData (DataT const data)
void appendData (DataT const data, sdw::UInt maxCount)
void appendData (DataT const data, sdw::Int maxCount)
void appendData (DataT const data, u32 maxCount)
Static Public Member Functions
template<typename ... ParamsT>
static sdw::type::BaseStructPtr makeType (sdw::type::TypesCache &cache, castor::MbString const &name, uint32_t arraySize, ParamsT &&... params)
Constructor & Destructor Documentation
AppendArrayT()
template<typename DataT > castor3d::shader::AppendArrayT< DataT >::AppendArrayT (sdw::ShaderWriter & writer, sdw::expr::ExprPtr expr, bool enabled) inline
Member Function Documentation
appendData() [1/4]
template<typename DataT > void castor3d::shader::AppendArrayT< DataT >::appendData (DataT const data) inline
References castor3d::shader::AppendArrayT< DataT >::incrementCount().
Referenced by castor3d::shader::AppendArrayT< DataT >::appendData(), and castor3d::shader::AppendArrayT< DataT >::appendData().
appendData() [2/4]
template<typename DataT > void castor3d::shader::AppendArrayT< DataT >::appendData (DataT const data, sdw::Int maxCount) inline
References castor3d::shader::AppendArrayT< DataT >::appendData().
appendData() [3/4]
template<typename DataT > void castor3d::shader::AppendArrayT< DataT >::appendData (DataT const data, sdw::UInt maxCount) inline
References castor3d::shader::AppendArrayT< DataT >::incrementCount().
appendData() [4/4]
template<typename DataT > void castor3d::shader::AppendArrayT< DataT >::appendData (DataT const data, u32 maxCount) inline
References castor3d::shader::AppendArrayT< DataT >::appendData().
getCount()
template<typename DataT > sdw::UInt castor3d::shader::AppendArrayT< DataT >::getCount () const inline
incrementCount()
template<typename DataT > sdw::UInt castor3d::shader::AppendArrayT< DataT >::incrementCount () const inline
Referenced by castor3d::shader::AppendArrayT< DataT >::appendData(), and castor3d::shader::AppendArrayT< DataT >::appendData().
makeType()
template<typename DataT > template<typename ... ParamsT> static sdw::type::BaseStructPtr castor3d::shader::AppendArrayT< DataT >::makeType (sdw::type::TypesCache & cache, castor::MbString const & name, uint32_t arraySize, ParamsT &&... params) inline static
operator[]() [1/3]
template<typename DataT > DataT castor3d::shader::AppendArrayT< DataT >::operator[] (int32_t offset) const inline
operator[]() [2/3]
template<typename DataT > template<sdw::type::Kind KindT> DataT castor3d::shader::AppendArrayT< DataT >::operator[] (sdw::IntegerValue< KindT > const & offset) const inline
operator[]() [3/3]
template<typename DataT > DataT castor3d::shader::AppendArrayT< DataT >::operator[] (uint32_t offset) const inline
resetCount()
template<typename DataT > void castor3d::shader::AppendArrayT< DataT >::resetCount () inline
SDW_DeclStructInstance()
template<typename DataT > castor3d::shader::AppendArrayT< DataT >::SDW_DeclStructInstance (AppendArrayT< DataT >)
The documentation for this class was generated from the following file:
Castor3D/Shader/Shaders/GlslAppendBuffer.hpp