Castor3D: castor3d::TextureAnimation Class Reference
castor3d::TextureAnimation Class Reference
Public Member Functions
C3D_API TextureAnimation (TextureUnit &texture, castor::String const &name=castor::cuEmptyString)
Constructor.
C3D_API ~TextureAnimation ()
Destructor.
C3D_API castor::Point3f getTranslate (castor::Milliseconds const &time) const
C3D_API castor::Angle getRotate (castor::Milliseconds const &time) const
TextureTranslateSpeed const & getTranslateSpeed ()
TextureRotateSpeed const & getRotateSpeed ()
void setTranslateSpeed (TextureTranslateSpeed const &translate)
void setRotateSpeed (TextureRotateSpeed const &rotate)
void setTransformSpeed (TextureTranslateSpeed const &translate, TextureRotateSpeed const &rotate)
C3D_API TextureAnimation (TextureAnimation &&rhs)=default
C3D_API TextureAnimation & operator= (TextureAnimation &&rhs)=delete
C3D_API TextureAnimation (TextureAnimation const &rhs)=delete
C3D_API TextureAnimation & operator= (TextureAnimation const &rhs)=delete
Public Member Functions inherited from castor3d::AnimationT< Engine >
AnimationT (AnimationType type, AnimableT< Engine > &animable, castor::String const &name=castor::cuEmptyString)
Constructor.
~AnimationT ()
Destructor.
void addKeyFrame (AnimationKeyFrameUPtr keyFrame)
Adds a keyframe to the animation.
AnimationKeyFrameArray::iterator find (castor::Milliseconds const &time)
Finds a keyframe given a time index.
void findKeyFrame (castor::Milliseconds const &time, AnimationKeyFrameArray::iterator &prv, AnimationKeyFrameArray::iterator &cur) const
Finds a keyframe given a time index.
void updateLength ()
Updates the animation length.
bool isEmpty () const
AnimationKeyFrameArray::const_iterator begin () const
AnimationKeyFrameArray::iterator begin ()
AnimationKeyFrameArray::const_iterator end () const
AnimationKeyFrameArray::iterator end ()
AnimationType getType () const
castor::Milliseconds const & getLength () const
C3D_API AnimationT (AnimationT &&rhs)=default
C3D_API AnimationT (AnimationT const &rhs)=delete
C3D_API AnimationT & operator= (AnimationT &&rhs)=delete
C3D_API AnimationT & operator= (AnimationT const &rhs)=delete
Protected Attributes
TextureTranslateSpeed m_translate
TextureRotateSpeed m_rotate
Protected Attributes inherited from castor3d::AnimationT< Engine >
AnimationType m_type
castor::Milliseconds m_length
AnimationKeyFrameArray m_keyframes
Friends
class BinaryWriter< TextureAnimation >
class BinaryParser< TextureAnimation >
class TextureAnimationInstance
Constructor & Destructor Documentation
TextureAnimation() [1/3]
C3D_API castor3d::TextureAnimation::TextureAnimation (TextureAnimation && rhs) default
name Copy / Move.
TextureAnimation() [2/3]
C3D_API castor3d::TextureAnimation::TextureAnimation (TextureAnimation const & rhs) delete
TextureAnimation() [3/3]
C3D_API castor3d::TextureAnimation::TextureAnimation (TextureUnit & texture, castor::String const & name = castor::cuEmptyString) explicit
Constructor.
Parameters
[in] texture The parent texture.
[in] name The name of the animation.
~TextureAnimation()
C3D_API castor3d::TextureAnimation::~TextureAnimation ()
Destructor.
Member Function Documentation
getRotate()
C3D_API castor::Angle castor3d::TextureAnimation::getRotate (castor::Milliseconds const & time) const
getRotateSpeed()
TextureRotateSpeed const& castor3d::TextureAnimation::getRotateSpeed () inline
References m_rotate.
getTranslate()
C3D_API castor::Point3f castor3d::TextureAnimation::getTranslate (castor::Milliseconds const & time) const
getTranslateSpeed()
TextureTranslateSpeed const& castor3d::TextureAnimation::getTranslateSpeed () inline
References m_translate.
operator=() [1/2]
C3D_API TextureAnimation& castor3d::TextureAnimation::operator= (TextureAnimation && rhs) delete
operator=() [2/2]
C3D_API TextureAnimation& castor3d::TextureAnimation::operator= (TextureAnimation const & rhs) delete
setRotateSpeed()
void castor3d::TextureAnimation::setRotateSpeed (TextureRotateSpeed const & rotate) inline
References m_rotate.
Referenced by setTransformSpeed().
setTransformSpeed()
void castor3d::TextureAnimation::setTransformSpeed (TextureTranslateSpeed const & translate, TextureRotateSpeed const & rotate) inline
References setRotateSpeed(), and setTranslateSpeed().
setTranslateSpeed()
void castor3d::TextureAnimation::setTranslateSpeed (TextureTranslateSpeed const & translate) inline
References m_translate.
Referenced by setTransformSpeed().
Friends And Related Function Documentation
BinaryParser< TextureAnimation >
friend class BinaryParser< TextureAnimation > friend
BinaryWriter< TextureAnimation >
friend class BinaryWriter< TextureAnimation > friend
TextureAnimationInstance
friend class TextureAnimationInstance friend
Member Data Documentation
m_rotate
TextureRotateSpeed castor3d::TextureAnimation::m_rotate protected
Referenced by getRotateSpeed(), and setRotateSpeed().
m_translate
TextureTranslateSpeed castor3d::TextureAnimation::m_translate protected
Referenced by getTranslateSpeed(), and setTranslateSpeed().
The documentation for this class was generated from the following file:
Material/Texture/Animation/TextureAnimation.hpp