Castor3D: Castor3D::Vertex Class Reference
Castor3D::Vertex Class Reference
Representation of a vertex.
Classes
class TextLoader
Vertex loader.
Public Member Functions
C3D_API Vertex (BufferElementGroup &p_group)
Constructor.
C3D_API Vertex (Vertex const &p_source)
Copy constructor.
C3D_API Vertex & operator= (Vertex const &p_source)
Copy assignment operator.
virtual C3D_API ~Vertex ()
Destructor.
void SetPosition (Castor::Coords3r const &val)
Sets the vertex position.
void SetPosition (Castor::Point3r const &val)
Sets the vertex position.
void SetPosition (real x, real y, real z)
Sets the vertex position.
void SetPosition (real const *p_coords)
Sets the vertex position.
void SetNormal (Castor::Coords3r const &val)
Sets the vertex normal.
void SetNormal (Castor::Point3r const &val)
Sets the vertex normal.
void SetNormal (real x, real y, real z)
Sets the vertex normal.
void SetNormal (real const *p_coords)
Sets the vertex normal.
void SetTangent (Castor::Coords3r const &val)
Sets the vertex tangent.
void SetTangent (Castor::Point3r const &val)
Sets the vertex tangent.
void SetTangent (real x, real y, real z)
Sets the vertex tangent.
void SetTangent (real const *p_coords)
Sets the vertex tangent.
void SetBitangent (Castor::Coords3r const &val)
Sets the vertex bitangent.
void SetBitangent (Castor::Point3r const &val)
Sets the vertex bitangent.
void SetBitangent (real x, real y, real z)
Sets the vertex bitangent.
void SetBitangent (real const *p_coords)
Sets the vertex bitangent.
void SetTexCoord (Castor::Coords3r const &val)
Sets the vertex texture coordinates.
void SetTexCoord (Castor::Point3r const &val)
Sets the vertex texture coordinates.
void SetTexCoord (real x, real y, real z=0)
Sets the vertex texture coordinates.
void SetTexCoord (real const *p_coords)
Sets the vertex texture coordinates.
Castor::Coords3r & GetPosition (Castor::Coords3r &p_ptPos)
Retrieves the vertex position.
Castor::Point3r & GetPosition (Castor::Point3r &p_ptPos) const
Retrieves the vertex position.
Castor::Coords3r & GetNormal (Castor::Coords3r &p_ptNml)
Retrieves the vertex normal.
Castor::Point3r & GetNormal (Castor::Point3r &p_ptNml) const
Retrieves the vertex normal.
Castor::Coords3r & GetTangent (Castor::Coords3r &p_ptTan)
Retrieves the vertex tangent.
Castor::Point3r & GetTangent (Castor::Point3r &p_ptTan) const
Retrieves the vertex tangent.
Castor::Coords3r & GetBitangent (Castor::Coords3r &p_ptBitan)
Retrieves the vertex bitangent.
Castor::Point3r & GetBitangent (Castor::Point3r &p_ptBitan) const
Retrieves the vertex bitangent.
Castor::Coords3r & GetTexCoord (Castor::Coords3r &p_ptTex)
Retrieves the vertex texture coordinates.
Castor::Point3r & GetTexCoord (Castor::Point3r &p_ptTex) const
Retrieves the vertex texture coordinates.
Static Public Member Functions
static const uint32_t GetCountPos ()
Retrieves position elements count.
static const uint32_t GetCountNml ()
Retrieves normal elements count.
static const uint32_t GetCountTan ()
Retrieves tangent elements count.
static const uint32_t GetCountBin ()
Retrieves bitangent elements count.
static const uint32_t GetCountTex ()
Retrieves texture coordinates elements count.
static const uint32_t GetOffsetPos ()
Retrieves position's buffer offset.
static const uint32_t GetOffsetNml ()
Retrieves normal's buffer offset.
static const uint32_t GetOffsetTan ()
Retrieves tangent's buffer offset.
static const uint32_t GetOffsetBin ()
Retrieves bitangent's buffer offset.
static const uint32_t GetOffsetTex ()
Retrieves texture coordinates' buffer offset.
static const uint32_t GetSizePos ()
Retrieves position binary size.
static const uint32_t GetSizeNml ()
Retrieves normal binary size.
static const uint32_t GetSizeTan ()
Retrieves tangent binary size.
static const uint32_t GetSizeBin ()
Retrieves bitangent binary size.
static const uint32_t GetSizeTex ()
Retrieves texture coordinates binary size.
static C3D_API Castor::Coords3r GetPosition (void *p_buffer)
Retrieves a vertex position from a buffer.
static C3D_API Castor::Point3r GetPosition (void const *p_buffer)
Retrieves a vertex position from a buffer.
static Castor::Coords3r & GetPosition (void *p_buffer, Castor::Coords3r &p_coord)
Retrieves a vertex position from a buffer.
static Castor::Point3r & GetPosition (void const *p_buffer, Castor::Point3r &p_coord)
Retrieves a vertex position from a buffer.
static C3D_API Castor::Coords3r GetNormal (void *p_buffer)
Retrieves a vertex normal from a buffer.
static C3D_API Castor::Point3r GetNormal (void const *p_buffer)
Retrieves a vertex normal from a buffer.
static Castor::Coords3r & GetNormal (void *p_buffer, Castor::Coords3r &p_coord)
Retrieves a vertex normal from a buffer.
static Castor::Point3r & GetNormal (void const *p_buffer, Castor::Point3r &p_coord)
Retrieves a vertex normal from a buffer.
static C3D_API Castor::Coords3r GetTangent (void *p_buffer)
Retrieves a vertex tangent from a buffer.
static C3D_API Castor::Point3r GetTangent (void const *p_buffer)
Retrieves a vertex tangent from a buffer.
static Castor::Coords3r & GetTangent (void *p_buffer, Castor::Coords3r &p_coord)
Retrieves a vertex tangent from a buffer.
static Castor::Point3r & GetTangent (void const *p_buffer, Castor::Point3r &p_coord)
Retrieves a vertex tangent from a buffer.
static C3D_API Castor::Coords3r GetBitangent (void *p_buffer)
Retrieves a vertex bitangent from a buffer.
static C3D_API Castor::Point3r GetBitangent (void const *p_buffer)
Retrieves a vertex bitangent from a buffer.
static Castor::Coords3r & GetBitangent (void *p_buffer, Castor::Coords3r &p_coord)
Retrieves a vertex bitangent from a buffer.
static Castor::Point3r & GetBitangent (void const *p_buffer, Castor::Point3r &p_coord)
Retrieves a vertex bitangent from a buffer.
static C3D_API Castor::Coords3r GetTexCoord (void *p_buffer)
Retrieves a vertex texture coordinates from a buffer.
static C3D_API Castor::Point3r GetTexCoord (void const *p_buffer)
Retrieves a vertex texture coordinates from a buffer.
static Castor::Coords3r & GetTexCoord (void *p_buffer, Castor::Coords3r &p_coord)
Retrieves a vertex texture coordinates from a buffer.
static Castor::Point3r & GetTexCoord (void const *p_buffer, Castor::Point3r &p_coord)
Retrieves a vertex texture coordinates from a buffer.
static void SetPosition (void *p_buffer, Castor::Coords3r const &p_coord)
Sets the vertex position in a buffer.
static void SetPosition (void *p_buffer, Castor::Point3r const &p_coord)
Sets the vertex position in a buffer.
static C3D_API void SetPosition (void *p_buffer, real const *p_coord)
Sets the vertex position in a buffer.
static C3D_API void SetPosition (void *p_buffer, real x, real y, real z)
Sets the vertex position in a buffer.
static void SetNormal (void *p_buffer, Castor::Coords3r const &p_coord)
Sets the vertex normal in a buffer.
static void SetNormal (void *p_buffer, Castor::Point3r const &p_coord)
Sets the vertex normal in a buffer.
static C3D_API void SetNormal (void *p_buffer, real const *p_coord)
Sets the vertex normal in a buffer.
static C3D_API void SetNormal (void *p_buffer, real x, real y, real z)
Sets the vertex normal in a buffer.
static void SetTangent (void *p_buffer, Castor::Coords3r const &p_coord)
Sets the vertex tangent in a buffer.
static void SetTangent (void *p_buffer, Castor::Point3r const &p_coord)
Sets the vertex tangent in a buffer.
static C3D_API void SetTangent (void *p_buffer, real const *p_coord)
Sets the vertex tangent in a buffer.
static C3D_API void SetTangent (void *p_buffer, real x, real y, real z)
Sets the vertex tangent in a buffer.
static void SetBitangent (void *p_buffer, Castor::Coords3r const &p_coord)
Sets the vertex bitangent in a buffer.
static void SetBitangent (void *p_buffer, Castor::Point3r const &p_coord)
Sets the vertex bitangent in a buffer.
static C3D_API void SetBitangent (void *p_buffer, real const *p_coord)
Sets the vertex bitangent in a buffer.
static C3D_API void SetBitangent (void *p_buffer, real x, real y, real z)
Sets the vertex bitangent in a buffer.
static void SetTexCoord (void *p_buffer, Castor::Coords3r const &p_coord)
Sets the vertex texture coordinates in a buffer.
static void SetTexCoord (void *p_buffer, Castor::Point3r const &p_coord)
Sets the vertex texture coordinates in a buffer.
static C3D_API void SetTexCoord (void *p_buffer, real const *p_coord)
Sets the vertex texture coordinates in a buffer.
static C3D_API void SetTexCoord (void *p_buffer, real x, real y, real z=0)
Sets the vertex texture coordinates in a buffer.
static Castor::Coords3r & GetPosition (BufferElementGroupSPtr p_pElement, Castor::Coords3r &p_coord)
Retrieves the group position.
static Castor::Point3r & GetPosition (BufferElementGroupSPtr p_pElement, Castor::Point3r &p_point)
Retrieves the group position.
static Castor::Coords3r & GetNormal (BufferElementGroupSPtr p_pElement, Castor::Coords3r &p_coord)
Retrieves the group normal.
static Castor::Point3r & GetNormal (BufferElementGroupSPtr p_pElement, Castor::Point3r &p_point)
Retrieves the group normal.
static Castor::Coords3r & GetTangent (BufferElementGroupSPtr p_pElement, Castor::Coords3r &p_coord)
Retrieves the group tangent.
static Castor::Point3r & GetTangent (BufferElementGroupSPtr p_pElement, Castor::Point3r &p_point)
Retrieves the group tangent.
static Castor::Coords3r & GetBitangent (BufferElementGroupSPtr p_pElement, Castor::Coords3r &p_coord)
Retrieves the group bitangent.
static Castor::Point3r & GetBitangent (BufferElementGroupSPtr p_pElement, Castor::Point3r &p_point)
Retrieves the group bitangent.
static Castor::Coords3r & GetTexCoord (BufferElementGroupSPtr p_pElement, Castor::Coords3r &p_coord)
Retrieves the group texture coordinates.
static Castor::Point3r & GetTexCoord (BufferElementGroupSPtr p_pElement, Castor::Point3r &p_point)
Retrieves the group texture coordinates.
static void SetPosition (BufferElementGroupSPtr p_pElement, Castor::Coords3r const &p_coord)
Sets the group position.
static void SetPosition (BufferElementGroupSPtr p_pElement, Castor::Point3r const &p_coord)
Sets the group position.
static void SetPosition (BufferElementGroupSPtr p_pElement, real const *p_coord)
Sets the group position.
static void SetPosition (BufferElementGroupSPtr p_pElement, real x, real y, real z)
Sets the group position.
static void SetNormal (BufferElementGroupSPtr p_pElement, Castor::Coords3r const &p_coord)
Sets the group normal.
static void SetNormal (BufferElementGroupSPtr p_pElement, Castor::Point3r const &p_coord)
Sets the group normal.
static void SetNormal (BufferElementGroupSPtr p_pElement, real const *p_coord)
Sets the group normal.
static void SetNormal (BufferElementGroupSPtr p_pElement, real x, real y, real z)
Sets the group normal.
static void SetTangent (BufferElementGroupSPtr p_pElement, Castor::Coords3r const &p_coord)
Sets the group tangent.
static void SetTangent (BufferElementGroupSPtr p_pElement, Castor::Point3r const &p_coord)
Sets the group tangent.
static void SetTangent (BufferElementGroupSPtr p_pElement, real const *p_coord)
Sets the group tangent.
static void SetTangent (BufferElementGroupSPtr p_pElement, real x, real y, real z)
Sets the group tangent.
static void SetBitangent (BufferElementGroupSPtr p_pElement, Castor::Coords3r const &p_coord)
Sets the group bitangent.
static void SetBitangent (BufferElementGroupSPtr p_pElement, Castor::Point3r const &p_coord)
Sets the group bitangent.
static void SetBitangent (BufferElementGroupSPtr p_pElement, real const *p_coord)
Sets the group bitangent.
static void SetBitangent (BufferElementGroupSPtr p_pElement, real x, real y, real z)
Sets the group bitangent.
static void SetTexCoord (BufferElementGroupSPtr p_pElement, Castor::Coords3r const &p_coord)
Sets the group texture coordinates.
static void SetTexCoord (BufferElementGroupSPtr p_pElement, Castor::Point3r const &p_coord)
Sets the group texture coordinates.
static void SetTexCoord (BufferElementGroupSPtr p_pElement, real const *p_coord)
Sets the group texture coordinates.
static void SetTexCoord (BufferElementGroupSPtr p_pElement, real x, real y, real z=0)
Sets the group texture coordinates.
static Castor::Coords3r & GetPosition (BufferElementGroup &p_element, Castor::Coords3r &p_coord)
Retrieves the group position.
static Castor::Point3r & GetPosition (BufferElementGroup const &p_element, Castor::Point3r &p_point)
Retrieves the group position.
static Castor::Coords3r & GetNormal (BufferElementGroup &p_element, Castor::Coords3r &p_coord)
Retrieves the group normal.
static Castor::Point3r & GetNormal (BufferElementGroup const &p_element, Castor::Point3r &p_point)
Retrieves the group normal.
static Castor::Coords3r & GetTangent (BufferElementGroup &p_element, Castor::Coords3r &p_coord)
Retrieves the group tangent.
static Castor::Point3r & GetTangent (BufferElementGroup const &p_element, Castor::Point3r &p_point)
Retrieves the group tangent.
static Castor::Coords3r & GetBitangent (BufferElementGroup &p_element, Castor::Coords3r &p_coord)
Retrieves the group bitangent.
static Castor::Point3r & GetBitangent (BufferElementGroup const &p_element, Castor::Point3r &p_point)
Retrieves the group bitangent.
static Castor::Coords3r & GetTexCoord (BufferElementGroup &p_element, Castor::Coords3r &p_coord)
Retrieves the group texture coordinates.
static Castor::Point3r & GetTexCoord (BufferElementGroup const &p_element, Castor::Point3r &p_point)
Retrieves the group texture coordinates.
static void SetPosition (BufferElementGroup &p_element, Castor::Coords3r const &p_coord)
Sets the group position.
static void SetPosition (BufferElementGroup &p_element, Castor::Point3r const &p_coord)
Sets the group position.
static void SetPosition (BufferElementGroup &p_element, real const *p_coord)
Sets the group position.
static void SetPosition (BufferElementGroup &p_element, real x, real y, real z)
Sets the group position.
static void SetNormal (BufferElementGroup &p_element, Castor::Coords3r const &p_coord)
Sets the group normal.
static void SetNormal (BufferElementGroup &p_element, Castor::Point3r const &p_coord)
Sets the group normal.
static void SetNormal (BufferElementGroup &p_element, real const *p_coord)
Sets the group normal.
static void SetNormal (BufferElementGroup &p_element, real x, real y, real z)
Sets the group normal.
static void SetTangent (BufferElementGroup &p_element, Castor::Coords3r const &p_coord)
Sets the group tangent.
static void SetTangent (BufferElementGroup &p_element, Castor::Point3r const &p_coord)
Sets the group tangent.
static void SetTangent (BufferElementGroup &p_element, real const *p_coord)
Sets the group tangent.
static void SetTangent (BufferElementGroup &p_element, real x, real y, real z)
Sets the group tangent.
static void SetBitangent (BufferElementGroup &p_element, Castor::Coords3r const &p_coord)
Sets the group bitangent.
static void SetBitangent (BufferElementGroup &p_element, Castor::Point3r const &p_coord)
Sets the group bitangent.
static void SetBitangent (BufferElementGroup &p_element, real const *p_coord)
Sets the group bitangent.
static void SetBitangent (BufferElementGroup &p_element, real x, real y, real z)
Sets the group bitangent.
static void SetTexCoord (BufferElementGroup &p_element, Castor::Coords3r const &p_coord)
Sets the group texture coordinates.
static void SetTexCoord (BufferElementGroup &p_element, Castor::Point3r const &p_coord)
Sets the group texture coordinates.
static void SetTexCoord (BufferElementGroup &p_element, real const *p_coord)
Sets the group texture coordinates.
static void SetTexCoord (BufferElementGroup &p_element, real x, real y, real z=0)
Sets the group texture coordinates.
Detailed Description
Representation of a vertex.
Author
Sylvain DOREMUS
Version
0.7.0
Date
27/06/2013
Remarks
Wraps BufferElementGroup to easily retrieve vertex's position, normal, tangent and texture coordinates, an index
Constructor & Destructor Documentation
Vertex() [1/2]
C3D_API Castor3D::Vertex::Vertex (BufferElementGroup & p_group)
Constructor.
Parameters
[in] p_group The wrapped group
Vertex() [2/2]
C3D_API Castor3D::Vertex::Vertex (Vertex const & p_source)
Copy constructor.
Parameters
[in] p_source The source object
~Vertex()
virtual C3D_API Castor3D::Vertex::~Vertex () virtual
Destructor.
Member Function Documentation
GetBitangent() [1/10]
Castor::Coords3r& Castor3D::Vertex::GetBitangent (Castor::Coords3r & p_ptBitan) inline
Retrieves the vertex bitangent.
Returns
The value
References Castor3D::BufferElementGroup::ptr().
Referenced by GetBitangent().
GetBitangent() [2/10]
Castor::Point3r& Castor3D::Vertex::GetBitangent (Castor::Point3r & p_ptBitan) const inline
Retrieves the vertex bitangent.
Returns
The value
References Castor3D::BufferElementGroup::const_ptr(), and GetBitangent().
GetBitangent() [3/10]
static C3D_API Castor::Coords3r Castor3D::Vertex::GetBitangent (void * p_buffer) static
Retrieves a vertex bitangent from a buffer.
Parameters
[in] p_buffer The buffer
Returns
The value
GetBitangent() [4/10]
static C3D_API Castor::Point3r Castor3D::Vertex::GetBitangent (void const * p_buffer) static
Retrieves a vertex bitangent from a buffer.
Parameters
[in] p_buffer The buffer
Returns
The value
GetBitangent() [5/10]
static Castor::Coords3r& Castor3D::Vertex::GetBitangent (void * p_buffer, Castor::Coords3r & p_coord) inline static
Retrieves a vertex bitangent from a buffer.
Parameters
[in] p_buffer The buffer
[out] p_coord Receives the value
Returns
The value
References GetBitangent().
GetBitangent() [6/10]
static Castor::Point3r& Castor3D::Vertex::GetBitangent (void const * p_buffer, Castor::Point3r & p_coord) inline static
Retrieves a vertex bitangent from a buffer.
Parameters
[in] p_buffer The buffer
[out] p_coord Receives the value
Returns
The value
References GetBitangent().
GetBitangent() [7/10]
static Castor::Coords3r& Castor3D::Vertex::GetBitangent (BufferElementGroupSPtr p_pElement, Castor::Coords3r & p_coord) inline static
Retrieves the group bitangent.
Parameters
[in] p_pElement The group
[out] p_coord Receives the bitangent
Returns
The value
References GetBitangent().
GetBitangent() [8/10]
static Castor::Point3r& Castor3D::Vertex::GetBitangent (BufferElementGroupSPtr p_pElement, Castor::Point3r & p_point) inline static
Retrieves the group bitangent.
Parameters
[in] p_pElement The group
[out] p_point Receives the bitangent
Returns
The value
References GetBitangent().
GetBitangent() [9/10]
static Castor::Coords3r& Castor3D::Vertex::GetBitangent (BufferElementGroup & p_element, Castor::Coords3r & p_coord) inline static
Retrieves the group bitangent.
Parameters
[in] p_element The group
[out] p_coord Receives the bitangent
Returns
The value
References GetBitangent(), and Castor3D::BufferElementGroup::ptr().
GetBitangent() [10/10]
static Castor::Point3r& Castor3D::Vertex::GetBitangent (BufferElementGroup const & p_element, Castor::Point3r & p_point) inline static
Retrieves the group bitangent.
Parameters
[in] p_element The group
[out] p_point Receives the bitangent
Returns
The value
References Castor3D::BufferElementGroup::const_ptr(), and GetBitangent().
GetCountBin()
static const uint32_t Castor3D::Vertex::GetCountBin () inline static
Retrieves bitangent elements count.
Returns
The value
GetCountNml()
static const uint32_t Castor3D::Vertex::GetCountNml () inline static
Retrieves normal elements count.
Returns
The value
GetCountPos()
static const uint32_t Castor3D::Vertex::GetCountPos () inline static
Retrieves position elements count.
Returns
The value
GetCountTan()
static const uint32_t Castor3D::Vertex::GetCountTan () inline static
Retrieves tangent elements count.
Returns
The value
GetCountTex()
static const uint32_t Castor3D::Vertex::GetCountTex () inline static
Retrieves texture coordinates elements count.
Returns
The value
GetNormal() [1/10]
Castor::Coords3r& Castor3D::Vertex::GetNormal (Castor::Coords3r & p_ptNml) inline
Retrieves the vertex normal.
Returns
The value
References Castor3D::BufferElementGroup::ptr().
Referenced by GetNormal().
GetNormal() [2/10]
Castor::Point3r& Castor3D::Vertex::GetNormal (Castor::Point3r & p_ptNml) const inline
Retrieves the vertex normal.
Returns
The value
References Castor3D::BufferElementGroup::const_ptr(), and GetNormal().
GetNormal() [3/10]
static C3D_API Castor::Coords3r Castor3D::Vertex::GetNormal (void * p_buffer) static
Retrieves a vertex normal from a buffer.
Parameters
[in] p_buffer The buffer
Returns
The value
GetNormal() [4/10]
static C3D_API Castor::Point3r Castor3D::Vertex::GetNormal (void const * p_buffer) static
Retrieves a vertex normal from a buffer.
Parameters
[in] p_buffer The buffer
Returns
The value
GetNormal() [5/10]
static Castor::Coords3r& Castor3D::Vertex::GetNormal (void * p_buffer, Castor::Coords3r & p_coord) inline static
Retrieves a vertex normal from a buffer.
Parameters
[in] p_buffer The buffer
[out] p_coord Receives the value
Returns
The value
References GetNormal().
GetNormal() [6/10]
static Castor::Point3r& Castor3D::Vertex::GetNormal (void const * p_buffer, Castor::Point3r & p_coord) inline static
Retrieves a vertex normal from a buffer.
Parameters
[in] p_buffer The buffer
[out] p_coord Receives the value
Returns
The value
References GetNormal().
GetNormal() [7/10]
static Castor::Coords3r& Castor3D::Vertex::GetNormal (BufferElementGroupSPtr p_pElement, Castor::Coords3r & p_coord) inline static
Retrieves the group normal.
Parameters
[in] p_pElement The group
[out] p_coord Receives the normal
Returns
The value
References GetNormal().
GetNormal() [8/10]
static Castor::Point3r& Castor3D::Vertex::GetNormal (BufferElementGroupSPtr p_pElement, Castor::Point3r & p_point) inline static
Retrieves the group normal.
Parameters
[in] p_pElement The group
[out] p_point Receives the normal
Returns
The value
References GetNormal().
GetNormal() [9/10]
static Castor::Coords3r& Castor3D::Vertex::GetNormal (BufferElementGroup & p_element, Castor::Coords3r & p_coord) inline static
Retrieves the group normal.
Parameters
[in] p_element The group
[out] p_coord Receives the normal
Returns
The value
References GetNormal(), and Castor3D::BufferElementGroup::ptr().
GetNormal() [10/10]
static Castor::Point3r& Castor3D::Vertex::GetNormal (BufferElementGroup const & p_element, Castor::Point3r & p_point) inline static
Retrieves the group normal.
Parameters
[in] p_element The group
[out] p_point Receives the normal
Returns
The value
References Castor3D::BufferElementGroup::const_ptr(), and GetNormal().
GetOffsetBin()
static const uint32_t Castor3D::Vertex::GetOffsetBin () inline static
Retrieves bitangent's buffer offset.
Returns
The value
GetOffsetNml()
static const uint32_t Castor3D::Vertex::GetOffsetNml () inline static
Retrieves normal's buffer offset.
Returns
The value
GetOffsetPos()
static const uint32_t Castor3D::Vertex::GetOffsetPos () inline static
Retrieves position's buffer offset.
Returns
The value
GetOffsetTan()
static const uint32_t Castor3D::Vertex::GetOffsetTan () inline static
Retrieves tangent's buffer offset.
Returns
The value
GetOffsetTex()
static const uint32_t Castor3D::Vertex::GetOffsetTex () inline static
Retrieves texture coordinates' buffer offset.
Returns
The value
GetPosition() [1/10]
Castor::Coords3r& Castor3D::Vertex::GetPosition (Castor::Coords3r & p_ptPos) inline
Retrieves the vertex position.
Returns
The value
References Castor3D::BufferElementGroup::ptr().
Referenced by GetPosition().
GetPosition() [2/10]
Castor::Point3r& Castor3D::Vertex::GetPosition (Castor::Point3r & p_ptPos) const inline
Retrieves the vertex position.
Returns
The value
References Castor3D::BufferElementGroup::const_ptr(), and GetPosition().
GetPosition() [3/10]
static C3D_API Castor::Coords3r Castor3D::Vertex::GetPosition (void * p_buffer) static
Retrieves a vertex position from a buffer.
Parameters
[in] p_buffer The buffer
Returns
The value
GetPosition() [4/10]
static C3D_API Castor::Point3r Castor3D::Vertex::GetPosition (void const * p_buffer) static
Retrieves a vertex position from a buffer.
Parameters
[in] p_buffer The buffer
Returns
The value
GetPosition() [5/10]
static Castor::Coords3r& Castor3D::Vertex::GetPosition (void * p_buffer, Castor::Coords3r & p_coord) inline static
Retrieves a vertex position from a buffer.
Parameters
[in] p_buffer The buffer
[out] p_coord Receives the value
Returns
The value
References GetPosition().
GetPosition() [6/10]
static Castor::Point3r& Castor3D::Vertex::GetPosition (void const * p_buffer, Castor::Point3r & p_coord) inline static
Retrieves a vertex position from a buffer.
Parameters
[in] p_buffer The buffer
[out] p_coord Receives the value
Returns
The value
References GetPosition().
GetPosition() [7/10]
static Castor::Coords3r& Castor3D::Vertex::GetPosition (BufferElementGroupSPtr p_pElement, Castor::Coords3r & p_coord) inline static
Retrieves the group position.
Parameters
[in] p_pElement The group
[out] p_coord Receives the coordinates
Returns
The value
References GetPosition().
GetPosition() [8/10]
static Castor::Point3r& Castor3D::Vertex::GetPosition (BufferElementGroupSPtr p_pElement, Castor::Point3r & p_point) inline static
Retrieves the group position.
Parameters
[in] p_pElement The group
[out] p_point Receives the coordinates
Returns
The value
References GetPosition().
GetPosition() [9/10]
static Castor::Coords3r& Castor3D::Vertex::GetPosition (BufferElementGroup & p_element, Castor::Coords3r & p_coord) inline static
Retrieves the group position.
Parameters
[in] p_element The group
[out] p_coord Receives the coordinates
Returns
The value
References GetPosition(), and Castor3D::BufferElementGroup::ptr().
GetPosition() [10/10]
static Castor::Point3r& Castor3D::Vertex::GetPosition (BufferElementGroup const & p_element, Castor::Point3r & p_point) inline static
Retrieves the group position.
Parameters
[in] p_element The group
[out] p_point Receives the coordinates
Returns
The value
References Castor3D::BufferElementGroup::const_ptr(), and GetPosition().
GetSizeBin()
static const uint32_t Castor3D::Vertex::GetSizeBin () inline static
Retrieves bitangent binary size.
Returns
The value
GetSizeNml()
static const uint32_t Castor3D::Vertex::GetSizeNml () inline static
Retrieves normal binary size.
Returns
The value
GetSizePos()
static const uint32_t Castor3D::Vertex::GetSizePos () inline static
Retrieves position binary size.
Returns
The value
GetSizeTan()
static const uint32_t Castor3D::Vertex::GetSizeTan () inline static
Retrieves tangent binary size.
Returns
The value
GetSizeTex()
static const uint32_t Castor3D::Vertex::GetSizeTex () inline static
Retrieves texture coordinates binary size.
Returns
The value
GetTangent() [1/10]
Castor::Coords3r& Castor3D::Vertex::GetTangent (Castor::Coords3r & p_ptTan) inline
Retrieves the vertex tangent.
Returns
The value
References Castor3D::BufferElementGroup::ptr().
Referenced by GetTangent().
GetTangent() [2/10]
Castor::Point3r& Castor3D::Vertex::GetTangent (Castor::Point3r & p_ptTan) const inline
Retrieves the vertex tangent.
Returns
The value
References Castor3D::BufferElementGroup::const_ptr(), and GetTangent().
GetTangent() [3/10]
static C3D_API Castor::Coords3r Castor3D::Vertex::GetTangent (void * p_buffer) static
Retrieves a vertex tangent from a buffer.
Parameters
[in] p_buffer The buffer
Returns
The value
GetTangent() [4/10]
static C3D_API Castor::Point3r Castor3D::Vertex::GetTangent (void const * p_buffer) static
Retrieves a vertex tangent from a buffer.
Parameters
[in] p_buffer The buffer
Returns
The value
GetTangent() [5/10]
static Castor::Coords3r& Castor3D::Vertex::GetTangent (void * p_buffer, Castor::Coords3r & p_coord) inline static
Retrieves a vertex tangent from a buffer.
Parameters
[in] p_buffer The buffer
[out] p_coord Receives the value
Returns
The value
References GetTangent().
GetTangent() [6/10]
static Castor::Point3r& Castor3D::Vertex::GetTangent (void const * p_buffer, Castor::Point3r & p_coord) inline static
Retrieves a vertex tangent from a buffer.
Parameters
[in] p_buffer The buffer
[out] p_coord Receives the value
Returns
The value
References GetTangent().
GetTangent() [7/10]
static Castor::Coords3r& Castor3D::Vertex::GetTangent (BufferElementGroupSPtr p_pElement, Castor::Coords3r & p_coord) inline static
Retrieves the group tangent.
Parameters
[in] p_pElement The group
[out] p_coord Receives the tangent
Returns
The value
References GetTangent().
GetTangent() [8/10]
static Castor::Point3r& Castor3D::Vertex::GetTangent (BufferElementGroupSPtr p_pElement, Castor::Point3r & p_point) inline static
Retrieves the group tangent.
Parameters
[in] p_pElement The group
[out] p_point Receives the tangent
Returns
The value
References GetTangent().
GetTangent() [9/10]
static Castor::Coords3r& Castor3D::Vertex::GetTangent (BufferElementGroup & p_element, Castor::Coords3r & p_coord) inline static
Retrieves the group tangent.
Parameters
[in] p_element The group
[out] p_coord Receives the tangent
Returns
The value
References GetTangent(), and Castor3D::BufferElementGroup::ptr().
GetTangent() [10/10]
static Castor::Point3r& Castor3D::Vertex::GetTangent (BufferElementGroup const & p_element, Castor::Point3r & p_point) inline static
Retrieves the group tangent.
Parameters
[in] p_element The group
[out] p_point Receives the tangent
Returns
The value
References Castor3D::BufferElementGroup::const_ptr(), and GetTangent().
GetTexCoord() [1/10]
Castor::Coords3r& Castor3D::Vertex::GetTexCoord (Castor::Coords3r & p_ptTex) inline
Retrieves the vertex texture coordinates.
Returns
The value
References Castor3D::BufferElementGroup::ptr().
Referenced by GetTexCoord().
GetTexCoord() [2/10]
Castor::Point3r& Castor3D::Vertex::GetTexCoord (Castor::Point3r & p_ptTex) const inline
Retrieves the vertex texture coordinates.
Returns
The value
References Castor3D::BufferElementGroup::const_ptr(), and GetTexCoord().
GetTexCoord() [3/10]
static C3D_API Castor::Coords3r Castor3D::Vertex::GetTexCoord (void * p_buffer) static
Retrieves a vertex texture coordinates from a buffer.
Parameters
[in] p_buffer The buffer
Returns
The value
GetTexCoord() [4/10]
static C3D_API Castor::Point3r Castor3D::Vertex::GetTexCoord (void const * p_buffer) static
Retrieves a vertex texture coordinates from a buffer.
Parameters
[in] p_buffer The buffer
Returns
The value
GetTexCoord() [5/10]
static Castor::Coords3r& Castor3D::Vertex::GetTexCoord (void * p_buffer, Castor::Coords3r & p_coord) inline static
Retrieves a vertex texture coordinates from a buffer.
Parameters
[in] p_buffer The buffer
[out] p_coord Receives the value
Returns
The value
References GetTexCoord().
GetTexCoord() [6/10]
static Castor::Point3r& Castor3D::Vertex::GetTexCoord (void const * p_buffer, Castor::Point3r & p_coord) inline static
Retrieves a vertex texture coordinates from a buffer.
Parameters
[in] p_buffer The buffer
[out] p_coord Receives the value
Returns
The value
References GetTexCoord().
GetTexCoord() [7/10]
static Castor::Coords3r& Castor3D::Vertex::GetTexCoord (BufferElementGroupSPtr p_pElement, Castor::Coords3r & p_coord) inline static
Retrieves the group texture coordinates.
Parameters
[in] p_pElement The group
[out] p_coord Receives the texture coordinates
Returns
The value
References GetTexCoord().
GetTexCoord() [8/10]
static Castor::Point3r& Castor3D::Vertex::GetTexCoord (BufferElementGroupSPtr p_pElement, Castor::Point3r & p_point) inline static
Retrieves the group texture coordinates.
Parameters
[in] p_pElement The group
[out] p_point Receives the texture coordinates
Returns
The value
References GetTexCoord().
GetTexCoord() [9/10]
static Castor::Coords3r& Castor3D::Vertex::GetTexCoord (BufferElementGroup & p_element, Castor::Coords3r & p_coord) inline static
Retrieves the group texture coordinates.
Parameters
[in] p_element The group
[out] p_coord Receives the texture coordinates
Returns
The value
References GetTexCoord(), and Castor3D::BufferElementGroup::ptr().
GetTexCoord() [10/10]
static Castor::Point3r& Castor3D::Vertex::GetTexCoord (BufferElementGroup const & p_element, Castor::Point3r & p_point) inline static
Retrieves the group texture coordinates.
Parameters
[in] p_element The group
[out] p_point Receives the texture coordinates
Returns
The value
References Castor3D::BufferElementGroup::const_ptr(), and GetTexCoord().
operator=()
C3D_API Vertex& Castor3D::Vertex::operator= (Vertex const & p_source)
Copy assignment operator.
Parameters
[in] p_source The source object
Returns
A reference to this object
SetBitangent() [1/16]
void Castor3D::Vertex::SetBitangent (Castor::Coords3r const & val) inline
Sets the vertex bitangent.
Parameters
[in] val The value
References Castor3D::BufferElementGroup::ptr().
Referenced by SetBitangent().
SetBitangent() [2/16]
void Castor3D::Vertex::SetBitangent (Castor::Point3r const & val) inline
Sets the vertex bitangent.
Parameters
[in] val The value
References Castor3D::BufferElementGroup::ptr(), and SetBitangent().
SetBitangent() [3/16]
void Castor3D::Vertex::SetBitangent (real x, real y, real z) inline
Sets the vertex bitangent.
Parameters
[in] x,y,z The values
References Castor3D::BufferElementGroup::ptr(), and SetBitangent().
SetBitangent() [4/16]
void Castor3D::Vertex::SetBitangent (real const * p_coords) inline
Sets the vertex bitangent.
Parameters
[in] p_coords The data buffer
References Castor3D::BufferElementGroup::ptr(), and SetBitangent().
SetBitangent() [5/16]
static void Castor3D::Vertex::SetBitangent (void * p_buffer, Castor::Coords3r const & p_coord) inline static
Sets the vertex bitangent in a buffer.
Parameters
[in] p_buffer The buffer
[in] p_coord The new value
References SetBitangent().
SetBitangent() [6/16]
static void Castor3D::Vertex::SetBitangent (void * p_buffer, Castor::Point3r const & p_coord) inline static
Sets the vertex bitangent in a buffer.
Parameters
[in] p_buffer The buffer
[in] p_coord The new value
References SetBitangent().
SetBitangent() [7/16]
static C3D_API void Castor3D::Vertex::SetBitangent (void * p_buffer, real const * p_coord) static
Sets the vertex bitangent in a buffer.
Parameters
[in] p_buffer The buffer
[in] p_coord The new value
SetBitangent() [8/16]
static C3D_API void Castor3D::Vertex::SetBitangent (void * p_buffer, real x, real y, real z) static
Sets the vertex bitangent in a buffer.
Parameters
[in] p_buffer The buffer
[in] x,y,z The new value
SetBitangent() [9/16]
static void Castor3D::Vertex::SetBitangent (BufferElementGroupSPtr p_pElement, Castor::Coords3r const & p_coord) inline static
Sets the group bitangent.
Parameters
[in] p_pElement The group
[in] p_coord The new value
References SetBitangent().
SetBitangent() [10/16]
static void Castor3D::Vertex::SetBitangent (BufferElementGroupSPtr p_pElement, Castor::Point3r const & p_coord) inline static
Sets the group bitangent.
Parameters
[in] p_pElement The group
[in] p_coord The new value
References SetBitangent().
SetBitangent() [11/16]
static void Castor3D::Vertex::SetBitangent (BufferElementGroupSPtr p_pElement, real const * p_coord) inline static
Sets the group bitangent.
Parameters
[in] p_pElement The group
[in] p_coord The new value
References SetBitangent().
SetBitangent() [12/16]
static void Castor3D::Vertex::SetBitangent (BufferElementGroupSPtr p_pElement, real x, real y, real z) inline static
Sets the group bitangent.
Parameters
[in] p_pElement The group
[in] x,y,z The new value
References SetBitangent().
SetBitangent() [13/16]
static void Castor3D::Vertex::SetBitangent (BufferElementGroup & p_element, Castor::Coords3r const & p_coord) inline static
Sets the group bitangent.
Parameters
[out] p_element The group
[in] p_coord The new value
References Castor3D::BufferElementGroup::ptr(), and SetBitangent().
SetBitangent() [14/16]
static void Castor3D::Vertex::SetBitangent (BufferElementGroup & p_element, Castor::Point3r const & p_coord) inline static
Sets the group bitangent.
Parameters
[out] p_element The group
[in] p_coord The new value
References Castor3D::BufferElementGroup::ptr(), and SetBitangent().
SetBitangent() [15/16]
static void Castor3D::Vertex::SetBitangent (BufferElementGroup & p_element, real const * p_coord) inline static
Sets the group bitangent.
Parameters
[out] p_element The group
[in] p_coord The new value
References Castor3D::BufferElementGroup::ptr(), and SetBitangent().
SetBitangent() [16/16]
static void Castor3D::Vertex::SetBitangent (BufferElementGroup & p_element, real x, real y, real z) inline static
Sets the group bitangent.
Parameters
[out] p_element The group
[in] x,y,z The new value
References Castor3D::BufferElementGroup::ptr(), and SetBitangent().
SetNormal() [1/16]
void Castor3D::Vertex::SetNormal (Castor::Coords3r const & val) inline
Sets the vertex normal.
Parameters
[in] val The value
References Castor3D::BufferElementGroup::ptr().
Referenced by SetNormal().
SetNormal() [2/16]
void Castor3D::Vertex::SetNormal (Castor::Point3r const & val) inline
Sets the vertex normal.
Parameters
[in] val The value
References Castor3D::BufferElementGroup::ptr(), and SetNormal().
SetNormal() [3/16]
void Castor3D::Vertex::SetNormal (real x, real y, real z) inline
Sets the vertex normal.
Parameters
[in] x,y,z The values
References Castor3D::BufferElementGroup::ptr(), and SetNormal().
SetNormal() [4/16]
void Castor3D::Vertex::SetNormal (real const * p_coords) inline
Sets the vertex normal.
Parameters
[in] p_coords The data buffer
References Castor3D::BufferElementGroup::ptr(), and SetNormal().
SetNormal() [5/16]
static void Castor3D::Vertex::SetNormal (void * p_buffer, Castor::Coords3r const & p_coord) inline static
Sets the vertex normal in a buffer.
Parameters
[in] p_buffer The buffer
[in] p_coord The new value
References SetNormal().
SetNormal() [6/16]
static void Castor3D::Vertex::SetNormal (void * p_buffer, Castor::Point3r const & p_coord) inline static
Sets the vertex normal in a buffer.
Parameters
[in] p_buffer The buffer
[in] p_coord The new value
References SetNormal().
SetNormal() [7/16]
static C3D_API void Castor3D::Vertex::SetNormal (void * p_buffer, real const * p_coord) static
Sets the vertex normal in a buffer.
Parameters
[in] p_buffer The buffer
[in] p_coord The new value
SetNormal() [8/16]
static C3D_API void Castor3D::Vertex::SetNormal (void * p_buffer, real x, real y, real z) static
Sets the vertex normal in a buffer.
Parameters
[in] p_buffer The buffer
[in] x,y,z The new value
SetNormal() [9/16]
static void Castor3D::Vertex::SetNormal (BufferElementGroupSPtr p_pElement, Castor::Coords3r const & p_coord) inline static
Sets the group normal.
Parameters
[in] p_pElement The group
[in] p_coord The new value
References SetNormal().
SetNormal() [10/16]
static void Castor3D::Vertex::SetNormal (BufferElementGroupSPtr p_pElement, Castor::Point3r const & p_coord) inline static
Sets the group normal.
Parameters
[in] p_pElement The group
[in] p_coord The new value
References SetNormal().
SetNormal() [11/16]
static void Castor3D::Vertex::SetNormal (BufferElementGroupSPtr p_pElement, real const * p_coord) inline static
Sets the group normal.
Parameters
[in] p_pElement The group
[in] p_coord The new value
References SetNormal().
SetNormal() [12/16]
static void Castor3D::Vertex::SetNormal (BufferElementGroupSPtr p_pElement, real x, real y, real z) inline static
Sets the group normal.
Parameters
[in] p_pElement The group
[in] x,y,z The new value
References SetNormal().
SetNormal() [13/16]
static void Castor3D::Vertex::SetNormal (BufferElementGroup & p_element, Castor::Coords3r const & p_coord) inline static
Sets the group normal.
Parameters
[out] p_element The group
[in] p_coord The new value
References Castor3D::BufferElementGroup::ptr(), and SetNormal().
SetNormal() [14/16]
static void Castor3D::Vertex::SetNormal (BufferElementGroup & p_element, Castor::Point3r const & p_coord) inline static
Sets the group normal.
Parameters
[out] p_element The group
[in] p_coord The new value
References Castor3D::BufferElementGroup::ptr(), and SetNormal().
SetNormal() [15/16]
static void Castor3D::Vertex::SetNormal (BufferElementGroup & p_element, real const * p_coord) inline static
Sets the group normal.
Parameters
[out] p_element The group
[in] p_coord The new value
References Castor3D::BufferElementGroup::ptr(), and SetNormal().
SetNormal() [16/16]
static void Castor3D::Vertex::SetNormal (BufferElementGroup & p_element, real x, real y, real z) inline static
Sets the group normal.
Parameters
[out] p_element The group
[in] x,y,z The new value
References Castor3D::BufferElementGroup::ptr(), and SetNormal().
SetPosition() [1/16]
void Castor3D::Vertex::SetPosition (Castor::Coords3r const & val) inline
Sets the vertex position.
Parameters
[in] val The new value
References Castor3D::BufferElementGroup::ptr().
Referenced by SetPosition().
SetPosition() [2/16]
void Castor3D::Vertex::SetPosition (Castor::Point3r const & val) inline
Sets the vertex position.
Parameters
[in] val The new value
References Castor3D::BufferElementGroup::ptr(), and SetPosition().
SetPosition() [3/16]
void Castor3D::Vertex::SetPosition (real x, real y, real z) inline
Sets the vertex position.
Parameters
[in] x,y,z The new value
References Castor3D::BufferElementGroup::ptr(), and SetPosition().
SetPosition() [4/16]
void Castor3D::Vertex::SetPosition (real const * p_coords) inline
Sets the vertex position.
Parameters
[in] p_coords The new value
References Castor3D::BufferElementGroup::ptr(), and SetPosition().
SetPosition() [5/16]
static void Castor3D::Vertex::SetPosition (void * p_buffer, Castor::Coords3r const & p_coord) inline static
Sets the vertex position in a buffer.
Parameters
[in] p_buffer The buffer
[in] p_coord The new value
References SetPosition().
SetPosition() [6/16]
static void Castor3D::Vertex::SetPosition (void * p_buffer, Castor::Point3r const & p_coord) inline static
Sets the vertex position in a buffer.
Parameters
[in] p_buffer The buffer
[in] p_coord The new value
References SetPosition().
SetPosition() [7/16]
static C3D_API void Castor3D::Vertex::SetPosition (void * p_buffer, real const * p_coord) static
Sets the vertex position in a buffer.
Parameters
[in] p_buffer The buffer
[in] p_coord The new value
SetPosition() [8/16]
static C3D_API void Castor3D::Vertex::SetPosition (void * p_buffer, real x, real y, real z) static
Sets the vertex position in a buffer.
Parameters
[in] p_buffer The buffer
[in] x,y,z The new value
SetPosition() [9/16]
static void Castor3D::Vertex::SetPosition (BufferElementGroupSPtr p_pElement, Castor::Coords3r const & p_coord) inline static
Sets the group position.
Parameters
[in] p_pElement The group
[in] p_coord The new value
References SetPosition().
SetPosition() [10/16]
static void Castor3D::Vertex::SetPosition (BufferElementGroupSPtr p_pElement, Castor::Point3r const & p_coord) inline static
Sets the group position.
Parameters
[in] p_pElement The group
[in] p_coord The new value
References SetPosition().
SetPosition() [11/16]
static void Castor3D::Vertex::SetPosition (BufferElementGroupSPtr p_pElement, real const * p_coord) inline static
Sets the group position.
Parameters
[in] p_pElement The group
[in] p_coord The new value
References SetPosition().
SetPosition() [12/16]
static void Castor3D::Vertex::SetPosition (BufferElementGroupSPtr p_pElement, real x, real y, real z) inline static
Sets the group position.
Parameters
[in] p_pElement The group
[in] x,y,z The new value
References SetPosition().
SetPosition() [13/16]
static void Castor3D::Vertex::SetPosition (BufferElementGroup & p_element, Castor::Coords3r const & p_coord) inline static
Sets the group position.
Parameters
[out] p_element The group
[in] p_coord The new value
References Castor3D::BufferElementGroup::ptr(), and SetPosition().
SetPosition() [14/16]
static void Castor3D::Vertex::SetPosition (BufferElementGroup & p_element, Castor::Point3r const & p_coord) inline static
Sets the group position.
Parameters
[out] p_element The group
[in] p_coord The new value
References Castor3D::BufferElementGroup::ptr(), and SetPosition().
SetPosition() [15/16]
static void Castor3D::Vertex::SetPosition (BufferElementGroup & p_element, real const * p_coord) inline static
Sets the group position.
Parameters
[out] p_element The group
[in] p_coord The new value
References Castor3D::BufferElementGroup::ptr(), and SetPosition().
SetPosition() [16/16]
static void Castor3D::Vertex::SetPosition (BufferElementGroup & p_element, real x, real y, real z) inline static
Sets the group position.
Parameters
[out] p_element The group
[in] x,y,z The new value
References Castor3D::BufferElementGroup::ptr(), and SetPosition().
SetTangent() [1/16]
void Castor3D::Vertex::SetTangent (Castor::Coords3r const & val) inline
Sets the vertex tangent.
Parameters
[in] val The value
References Castor3D::BufferElementGroup::ptr().
Referenced by SetTangent().
SetTangent() [2/16]
void Castor3D::Vertex::SetTangent (Castor::Point3r const & val) inline
Sets the vertex tangent.
Parameters
[in] val The value
References Castor3D::BufferElementGroup::ptr(), and SetTangent().
SetTangent() [3/16]
void Castor3D::Vertex::SetTangent (real x, real y, real z) inline
Sets the vertex tangent.
Parameters
[in] x,y,z The values
References Castor3D::BufferElementGroup::ptr(), and SetTangent().
SetTangent() [4/16]
void Castor3D::Vertex::SetTangent (real const * p_coords) inline
Sets the vertex tangent.
Parameters
[in] p_coords The data buffer
References Castor3D::BufferElementGroup::ptr(), and SetTangent().
SetTangent() [5/16]
static void Castor3D::Vertex::SetTangent (void * p_buffer, Castor::Coords3r const & p_coord) inline static
Sets the vertex tangent in a buffer.
Parameters
[in] p_buffer The buffer
[in] p_coord The new value
References SetTangent().
SetTangent() [6/16]
static void Castor3D::Vertex::SetTangent (void * p_buffer, Castor::Point3r const & p_coord) inline static
Sets the vertex tangent in a buffer.
Parameters
[in] p_buffer The buffer
[in] p_coord The new value
References SetTangent().
SetTangent() [7/16]
static C3D_API void Castor3D::Vertex::SetTangent (void * p_buffer, real const * p_coord) static
Sets the vertex tangent in a buffer.
Parameters
[in] p_buffer The buffer
[in] p_coord The new value
SetTangent() [8/16]
static C3D_API void Castor3D::Vertex::SetTangent (void * p_buffer, real x, real y, real z) static
Sets the vertex tangent in a buffer.
Parameters
[in] p_buffer The buffer
[in] x,y,z The new value
SetTangent() [9/16]
static void Castor3D::Vertex::SetTangent (BufferElementGroupSPtr p_pElement, Castor::Coords3r const & p_coord) inline static
Sets the group tangent.
Parameters
[in] p_pElement The group
[in] p_coord The new value
References SetTangent().
SetTangent() [10/16]
static void Castor3D::Vertex::SetTangent (BufferElementGroupSPtr p_pElement, Castor::Point3r const & p_coord) inline static
Sets the group tangent.
Parameters
[in] p_pElement The group
[in] p_coord The new value
References SetTangent().
SetTangent() [11/16]
static void Castor3D::Vertex::SetTangent (BufferElementGroupSPtr p_pElement, real const * p_coord) inline static
Sets the group tangent.
Parameters
[in] p_pElement The group
[in] p_coord The new value
References SetTangent().
SetTangent() [12/16]
static void Castor3D::Vertex::SetTangent (BufferElementGroupSPtr p_pElement, real x, real y, real z) inline static
Sets the group tangent.
Parameters
[in] p_pElement The group
[in] x,y,z The new value
References SetTangent().
SetTangent() [13/16]
static void Castor3D::Vertex::SetTangent (BufferElementGroup & p_element, Castor::Coords3r const & p_coord) inline static
Sets the group tangent.
Parameters
[out] p_element The group
[in] p_coord The new value
References Castor3D::BufferElementGroup::ptr(), and SetTangent().
SetTangent() [14/16]
static void Castor3D::Vertex::SetTangent (BufferElementGroup & p_element, Castor::Point3r const & p_coord) inline static
Sets the group tangent.
Parameters
[out] p_element The group
[in] p_coord The new value
References Castor3D::BufferElementGroup::ptr(), and SetTangent().
SetTangent() [15/16]
static void Castor3D::Vertex::SetTangent (BufferElementGroup & p_element, real const * p_coord) inline static
Sets the group tangent.
Parameters
[out] p_element The group
[in] p_coord The new value
References Castor3D::BufferElementGroup::ptr(), and SetTangent().
SetTangent() [16/16]
static void Castor3D::Vertex::SetTangent (BufferElementGroup & p_element, real x, real y, real z) inline static
Sets the group tangent.
Parameters
[out] p_element The group
[in] x,y,z The new value
References Castor3D::BufferElementGroup::ptr(), and SetTangent().
SetTexCoord() [1/16]
void Castor3D::Vertex::SetTexCoord (Castor::Coords3r const & val) inline
Sets the vertex texture coordinates.
Parameters
[in] val The value
References Castor3D::BufferElementGroup::ptr().
Referenced by SetTexCoord().
SetTexCoord() [2/16]
void Castor3D::Vertex::SetTexCoord (Castor::Point3r const & val) inline
Sets the vertex texture coordinates.
Parameters
[in] val The value
References Castor3D::BufferElementGroup::ptr(), and SetTexCoord().
SetTexCoord() [3/16]
void Castor3D::Vertex::SetTexCoord (real x, real y, real z = 0) inline
Sets the vertex texture coordinates.
Parameters
[in] x,y,z The values
References Castor3D::BufferElementGroup::ptr(), and SetTexCoord().
SetTexCoord() [4/16]
void Castor3D::Vertex::SetTexCoord (real const * p_coords) inline
Sets the vertex texture coordinates.
Parameters
[in] p_coords The data buffer
References Castor3D::BufferElementGroup::ptr(), and SetTexCoord().
SetTexCoord() [5/16]
static void Castor3D::Vertex::SetTexCoord (void * p_buffer, Castor::Coords3r const & p_coord) inline static
Sets the vertex texture coordinates in a buffer.
Parameters
[in] p_buffer The buffer
[in] p_coord The new value
References SetTexCoord().
SetTexCoord() [6/16]
static void Castor3D::Vertex::SetTexCoord (void * p_buffer, Castor::Point3r const & p_coord) inline static
Sets the vertex texture coordinates in a buffer.
Parameters
[in] p_buffer The buffer
[in] p_coord The new value
References SetTexCoord().
SetTexCoord() [7/16]
static C3D_API void Castor3D::Vertex::SetTexCoord (void * p_buffer, real const * p_coord) static
Sets the vertex texture coordinates in a buffer.
Parameters
[in] p_buffer The buffer
[in] p_coord The new value
SetTexCoord() [8/16]
static C3D_API void Castor3D::Vertex::SetTexCoord (void * p_buffer, real x, real y, real z = 0) static
Sets the vertex texture coordinates in a buffer.
Parameters
[in] p_buffer The buffer
[in] x,y,z The new value
SetTexCoord() [9/16]
static void Castor3D::Vertex::SetTexCoord (BufferElementGroupSPtr p_pElement, Castor::Coords3r const & p_coord) inline static
Sets the group texture coordinates.
Parameters
[in] p_pElement The group
[in] p_coord The new value
References SetTexCoord().
SetTexCoord() [10/16]
static void Castor3D::Vertex::SetTexCoord (BufferElementGroupSPtr p_pElement, Castor::Point3r const & p_coord) inline static
Sets the group texture coordinates.
Parameters
[in] p_pElement The group
[in] p_coord The new value
References SetTexCoord().
SetTexCoord() [11/16]
static void Castor3D::Vertex::SetTexCoord (BufferElementGroupSPtr p_pElement, real const * p_coord) inline static
Sets the group texture coordinates.
Parameters
[in] p_pElement The group
[in] p_coord The new value
References SetTexCoord().
SetTexCoord() [12/16]
static void Castor3D::Vertex::SetTexCoord (BufferElementGroupSPtr p_pElement, real x, real y, real z = 0) inline static
Sets the group texture coordinates.
Parameters
[in] p_pElement The group
[in] x,y,z The new value
References SetTexCoord().
SetTexCoord() [13/16]
static void Castor3D::Vertex::SetTexCoord (BufferElementGroup & p_element, Castor::Coords3r const & p_coord) inline static
Sets the group texture coordinates.
Parameters
[out] p_element The group
[in] p_coord The new value
References Castor3D::BufferElementGroup::ptr(), and SetTexCoord().
SetTexCoord() [14/16]
static void Castor3D::Vertex::SetTexCoord (BufferElementGroup & p_element, Castor::Point3r const & p_coord) inline static
Sets the group texture coordinates.
Parameters
[out] p_element The group
[in] p_coord The new value
References Castor3D::BufferElementGroup::ptr(), and SetTexCoord().
SetTexCoord() [15/16]
static void Castor3D::Vertex::SetTexCoord (BufferElementGroup & p_element, real const * p_coord) inline static
Sets the group texture coordinates.
Parameters
[out] p_element The group
[in] p_coord The new value
References Castor3D::BufferElementGroup::ptr(), and SetTexCoord().
SetTexCoord() [16/16]
static void Castor3D::Vertex::SetTexCoord (BufferElementGroup & p_element, real x, real y, real z = 0) inline static
Sets the group texture coordinates.
Parameters
[out] p_element The group
[in] x,y,z The new value
References Castor3D::BufferElementGroup::ptr(), and SetTexCoord().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Vertex.hpp