Castor3D: castor3d::shader::TextureConfigData Struct Reference
castor3d::shader::TextureConfigData Struct Reference
#include <GlslTextureConfiguration.hpp>
Public Member Functions
C3D_API TextureConfigData (sdw::ShaderWriter &writer, ast::expr::ExprPtr expr, bool enabled)
C3D_API void transformUV (Utils &utils, TextureTransformData const &anim, sdw::Vec2 &uv) const
C3D_API void transformUVW (Utils &utils, TextureTransformData const &anim, sdw::Vec3 &uvw) const
C3D_API void transformUV (Utils &utils, TextureTransformData const &anim, DerivTex &uv) const
auto transform () const
auto translate () const
auto rotateU () const
auto rotateV () const
auto scale () const
auto tileSet () const
auto nmlFact () const
auto nmlGMul () const
auto nml2Chan () const
auto hgtFact () const
auto needsYI () const
auto isTrnfAnim () const
auto isTileAnim () const
auto texSet () const
C3D_API sdw::Vec2 getUv (DerivTex const &uvw) const
C3D_API void setUv (DerivTex &lhs, DerivTex const &rhs) const
C3D_API DerivTex toUv (DerivTex const &uvw) const
sdw::Vec2 getUv (sdw::Vec3 const &uvw) const
sdw::Vec2 toUv (sdw::Vec3 const &uvw) const
void setUv (sdw::Vec3 &lhs, sdw::Vec2 const &rhs) const
Static Public Member Functions
static C3D_API sdw::Float getFloat (sdw::Vec4 const &sampled, sdw::UInt const &mask)
static C3D_API sdw::Vec3 getVec3 (sdw::Vec4 const &sampled, sdw::UInt const &mask)
Public Attributes
sdw::Float fneedYI
Friends
class TextureConfigurations
Constructor & Destructor Documentation
TextureConfigData()
C3D_API castor3d::shader::TextureConfigData::TextureConfigData (sdw::ShaderWriter & writer, ast::expr::ExprPtr expr, bool enabled)
Member Function Documentation
getFloat()
static C3D_API sdw::Float castor3d::shader::TextureConfigData::getFloat (sdw::Vec4 const & sampled, sdw::UInt const & mask) static
getUv() [1/2]
C3D_API sdw::Vec2 castor3d::shader::TextureConfigData::getUv (DerivTex const & uvw) const
getUv() [2/2]
sdw::Vec2 castor3d::shader::TextureConfigData::getUv (sdw::Vec3 const & uvw) const inline
getVec3()
static C3D_API sdw::Vec3 castor3d::shader::TextureConfigData::getVec3 (sdw::Vec4 const & sampled, sdw::UInt const & mask) static
hgtFact()
auto castor3d::shader::TextureConfigData::hgtFact () const inline
isTileAnim()
auto castor3d::shader::TextureConfigData::isTileAnim () const inline
isTrnfAnim()
auto castor3d::shader::TextureConfigData::isTrnfAnim () const inline
needsYI()
auto castor3d::shader::TextureConfigData::needsYI () const inline
nml2Chan()
auto castor3d::shader::TextureConfigData::nml2Chan () const inline
nmlFact()
auto castor3d::shader::TextureConfigData::nmlFact () const inline
nmlGMul()
auto castor3d::shader::TextureConfigData::nmlGMul () const inline
rotateU()
auto castor3d::shader::TextureConfigData::rotateU () const inline
References transform().
rotateV()
auto castor3d::shader::TextureConfigData::rotateV () const inline
References transform().
scale()
auto castor3d::shader::TextureConfigData::scale () const inline
References transform().
setUv() [1/2]
C3D_API void castor3d::shader::TextureConfigData::setUv (DerivTex & lhs, DerivTex const & rhs) const
setUv() [2/2]
void castor3d::shader::TextureConfigData::setUv (sdw::Vec3 & lhs, sdw::Vec2 const & rhs) const inline
texSet()
auto castor3d::shader::TextureConfigData::texSet () const inline
tileSet()
auto castor3d::shader::TextureConfigData::tileSet () const inline
References transform().
toUv() [1/2]
C3D_API DerivTex castor3d::shader::TextureConfigData::toUv (DerivTex const & uvw) const
toUv() [2/2]
sdw::Vec2 castor3d::shader::TextureConfigData::toUv (sdw::Vec3 const & uvw) const inline
transform()
auto castor3d::shader::TextureConfigData::transform () const inline
Referenced by rotateU(), rotateV(), scale(), tileSet(), and translate().
transformUV() [1/2]
C3D_API void castor3d::shader::TextureConfigData::transformUV (Utils & utils, TextureTransformData const & anim, DerivTex & uv) const
transformUV() [2/2]
C3D_API void castor3d::shader::TextureConfigData::transformUV (Utils & utils, TextureTransformData const & anim, sdw::Vec2 & uv) const
transformUVW()
C3D_API void castor3d::shader::TextureConfigData::transformUVW (Utils & utils, TextureTransformData const & anim, sdw::Vec3 & uvw) const
translate()
auto castor3d::shader::TextureConfigData::translate () const inline
References transform().
Friends And Related Symbol Documentation
TextureConfigurations
friend class TextureConfigurations friend
Member Data Documentation
fneedYI
sdw::Float castor3d::shader::TextureConfigData::fneedYI
The documentation for this struct was generated from the following file:
Castor3D/Shader/Shaders/GlslTextureConfiguration.hpp