Castor3D: Castor3D::Engine Class Reference
Castor3D::Engine Class Reference
Main System.
Public Member Functions
C3D_API Engine ()
Constructor.
C3D_API ~Engine ()
Destructor.
C3D_API void Initialise (uint32_t p_wantedFPS=100, bool p_threaded=false)
Initialisation function, sets the wanted frame rate.
C3D_API void Cleanup ()
Cleanup function, destroys everything created from the beginning.
C3D_API bool LoadRenderer (eRENDERER_TYPE p_type)
Loads a renderer plug-in, given the renderer type.
C3D_API void PostEvent (FrameEventSPtr p_pEvent)
Posts a frame event to the default frame listener.
C3D_API bool IsCleaned ()
Retrieves the cleanup status.
C3D_API void SetCleaned ()
Tells the engine is cleaned up.
C3D_API bool SupportsShaderModel (eSHADER_MODEL p_eShaderModel)
Checks the current support for given shader model.
C3D_API void RegisterParsers (Castor::String const &p_name, Castor::FileParser::AttributeParsersBySection &&p_parsers)
Registers additional parsers for SceneFileParser.
C3D_API void RegisterSections (Castor::String const &p_name, Castor::StrUIntMap const &p_sections)
Registers additional sections for SceneFileParser.
C3D_API void UnregisterParsers (Castor::String const &p_name)
Unregisters parsers for SceneFileParser.
C3D_API void UnregisterSections (Castor::String const &p_name)
Unregisters sections for SceneFileParser.
Castor::ImageManager const & GetImageManager () const
Retrieves the images collection.
Castor::ImageManager & GetImageManager ()
Retrieves the images collection.
Castor::FontManager const & GetFontManager () const
Retrieves the fonts collection.
Castor::FontManager & GetFontManager ()
Retrieves the fonts collection.
RenderSystem * GetRenderSystem () const
Retrieves the RenderSystem.
BlendStateSPtr GetDefaultBlendState () const
Retrieves the default BlendState (no blend)
SamplerSPtr GetDefaultSampler () const
Retrieves the default Sampler.
SamplerSPtr GetLightsSampler () const
Retrieves the lighting Sampler.
std::map< Castor::String, Castor::FileParser::AttributeParsersBySection > const & GetAdditionalParsers () const
Retrieves the SceneFileParser additional parsers.
std::map< Castor::String, Castor::StrUIntMap > const & GetAdditionalSections () const
Retrieves the SceneFileParser additional sections.
Version const & GetVersion () const
bool HasRenderLoop () const
RenderLoop const & GetRenderLoop () const
RenderLoop & GetRenderLoop ()
void SetPerObjectLighting (bool p_value)
Sets the need for per object lighting.
bool GetPerObjectLighting ()
bool IsThreaded ()
Static Public Member Functions
static C3D_API Castor::Path GetPluginsDirectory ()
Retrieves plug-ins path.
static C3D_API Castor::Path GetEngineDirectory ()
Gives the Castor directory.
static C3D_API Castor::Path GetDataDirectory ()
Retrieves data path.
Detailed Description
Main System.
Author
Sylvain DOREMUS
Date
09/02/2010
Version
0.1
Remarks
Holds the render windows, the plug-ins, the render drivers...
Constructor & Destructor Documentation
Engine()
C3D_API Castor3D::Engine::Engine ()
Constructor.
~Engine()
C3D_API Castor3D::Engine::~Engine ()
Destructor.
Member Function Documentation
Cleanup()
C3D_API void Castor3D::Engine::Cleanup ()
Cleanup function, destroys everything created from the beginning.
Remarks
Destroys also RenderWindows, the only things left after that is RenderSystem and loaded plug-ins
GetAdditionalParsers()
std::map< Castor::String, Castor::FileParser::AttributeParsersBySection > const& Castor3D::Engine::GetAdditionalParsers () const inline
Retrieves the SceneFileParser additional parsers.
Returns
The parsers.
GetAdditionalSections()
std::map< Castor::String, Castor::StrUIntMap > const& Castor3D::Engine::GetAdditionalSections () const inline
Retrieves the SceneFileParser additional sections.
Returns
The sections.
GetDataDirectory()
static C3D_API Castor::Path Castor3D::Engine::GetDataDirectory () static
Retrieves data path.
Returns
The data path
GetDefaultBlendState()
BlendStateSPtr Castor3D::Engine::GetDefaultBlendState () const inline
Retrieves the default BlendState (no blend)
Returns
The value
GetDefaultSampler()
SamplerSPtr Castor3D::Engine::GetDefaultSampler () const inline
Retrieves the default Sampler.
Returns
The Sampler
GetEngineDirectory()
static C3D_API Castor::Path Castor3D::Engine::GetEngineDirectory () static
Gives the Castor directory.
Returns
The directory
GetFontManager() [1/2]
Castor::FontManager const& Castor3D::Engine::GetFontManager () const inline
Retrieves the fonts collection.
Returns
The collection
GetFontManager() [2/2]
Castor::FontManager& Castor3D::Engine::GetFontManager () inline
Retrieves the fonts collection.
Returns
The collection
GetImageManager() [1/2]
Castor::ImageManager const& Castor3D::Engine::GetImageManager () const inline
Retrieves the images collection.
Returns
The collection
GetImageManager() [2/2]
Castor::ImageManager& Castor3D::Engine::GetImageManager () inline
Retrieves the images collection.
Returns
The collection
GetLightsSampler()
SamplerSPtr Castor3D::Engine::GetLightsSampler () const inline
Retrieves the lighting Sampler.
Returns
The Sampler.
GetPerObjectLighting()
bool Castor3D::Engine::GetPerObjectLighting () inline
Returns
The need for per object lighting.
GetPluginsDirectory()
static C3D_API Castor::Path Castor3D::Engine::GetPluginsDirectory () static
Retrieves plug-ins path.
Returns
The plug-ins path
GetRenderLoop() [1/2]
RenderLoop const& Castor3D::Engine::GetRenderLoop () const inline
Returns
The render loop.
GetRenderLoop() [2/2]
RenderLoop& Castor3D::Engine::GetRenderLoop () inline
Returns
The render loop.
GetRenderSystem()
RenderSystem* Castor3D::Engine::GetRenderSystem () const inline
Retrieves the RenderSystem.
Returns
The RenderSystem
GetVersion()
Version const& Castor3D::Engine::GetVersion () const inline
Returns
The engine version.
HasRenderLoop()
bool Castor3D::Engine::HasRenderLoop () const inline
Returns
The render loop.
Initialise()
C3D_API void Castor3D::Engine::Initialise (uint32_t p_wantedFPS = 100, bool p_threaded = false)
Initialisation function, sets the wanted frame rate.
Parameters
[in] p_wantedFPS The wanted FPS count
[in] p_threaded If false, the render can't be threaded
IsCleaned()
C3D_API bool Castor3D::Engine::IsCleaned ()
Retrieves the cleanup status.
Remarks
Thread-safe
Returns
true if cleaned up
IsThreaded()
bool Castor3D::Engine::IsThreaded () inline
Returns
Tells if the engine uses an asynchronous render loop.
LoadRenderer()
C3D_API bool Castor3D::Engine::LoadRenderer (eRENDERER_TYPE p_type)
Loads a renderer plug-in, given the renderer type.
Parameters
[in] p_type The renderer type
Returns
true if ok
PostEvent()
C3D_API void Castor3D::Engine::PostEvent (FrameEventSPtr p_pEvent)
Posts a frame event to the default frame listener.
Parameters
[in] p_pEvent The event to add
Referenced by Castor3D::ElementCleaner< Elem, typename std::enable_if< is_cleanable< Elem >::value &&!is_instant< Elem >::value >::type >::Cleanup(), Castor3D::SamplerManager::Create(), Castor3D::GeometryManager::Create(), and Castor3D::ElementInitialiser< Elem, typename std::enable_if< is_initialisable< Elem >::value &&!is_instant< Elem >::value >::type >::Initialise().
RegisterParsers()
C3D_API void Castor3D::Engine::RegisterParsers (Castor::String const & p_name, Castor::FileParser::AttributeParsersBySection && p_parsers)
Registers additional parsers for SceneFileParser.
Parameters
[in] p_name The registering name.
[in] p_parsers The parsers.
RegisterSections()
C3D_API void Castor3D::Engine::RegisterSections (Castor::String const & p_name, Castor::StrUIntMap const & p_sections)
Registers additional sections for SceneFileParser.
Parameters
[in] p_name The registering name.
[in] p_sections The sections.
SetCleaned()
C3D_API void Castor3D::Engine::SetCleaned ()
Tells the engine is cleaned up.
Remarks
Thread-safe
SetPerObjectLighting()
void Castor3D::Engine::SetPerObjectLighting (bool p_value) inline
Sets the need for per object lighting.
Parameters
[in] p_value The new value.
SupportsShaderModel()
C3D_API bool Castor3D::Engine::SupportsShaderModel (eSHADER_MODEL p_eShaderModel)
Checks the current support for given shader model.
Parameters
[in] p_eShaderModel The shader model
Returns
true if the shader model is supported in actual configuration
UnregisterParsers()
C3D_API void Castor3D::Engine::UnregisterParsers (Castor::String const & p_name)
Unregisters parsers for SceneFileParser.
Parameters
[in] p_name The registering name.
UnregisterSections()
C3D_API void Castor3D::Engine::UnregisterSections (Castor::String const & p_name)
Unregisters sections for SceneFileParser.
Parameters
[in] p_name The registering name.
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Engine.hpp