Castor3D: castor3d::BufferElementGroup Class Reference
castor3d::BufferElementGroup Class Reference
Holds data of a vertex buffer elements group.
Public Member Functions
C3D_API BufferElementGroup (uint8_t *p_buffer=nullptr, uint32_t p_index=0)
Constructor.
virtual C3D_API ~BufferElementGroup ()
Destructor.
C3D_API void linkCoords (uint8_t *p_buffer)
Links the element values to the ones in parameter.
C3D_API void linkCoords (uint8_t *p_buffer, uint32_t p_stride)
Links the element values to the ones in parameter.
uint8_t * ptr ()
Retrieves a pointer on the data buffer.
uint8_t const * constPtr () const
Retrieves a constant pointer on the data buffer.
uint32_t getIndex () const
Retrieves the group index.
void setIndex (uint32_t p_index)
sets the group index
Protected Attributes
uint8_t * m_buffer
The elements values.
uint32_t m_index
The group index.
Detailed Description
Holds data of a vertex buffer elements group.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
03/01/2011
Constructor & Destructor Documentation
BufferElementGroup()
C3D_API castor3d::BufferElementGroup::BufferElementGroup (uint8_t * p_buffer = nullptr, uint32_t p_index = 0)
Constructor.
Parameters
[in] p_buffer The data buffer
[in] p_index The group index
~BufferElementGroup()
virtual C3D_API castor3d::BufferElementGroup::~BufferElementGroup () virtual
Destructor.
Member Function Documentation
constPtr()
uint8_t const* castor3d::BufferElementGroup::constPtr () const inline
Retrieves a constant pointer on the data buffer.
Returns
The pointer
References m_buffer.
Referenced by castor3d::Vertex::getBitangent(), castor3d::Vertex::getNormal(), castor3d::Vertex::getPosition(), castor3d::Vertex::getTangent(), and castor3d::Vertex::getTexCoord().
getIndex()
uint32_t castor3d::BufferElementGroup::getIndex () const inline
Retrieves the group index.
Returns
The value
References m_index.
linkCoords() [1/2]
C3D_API void castor3d::BufferElementGroup::linkCoords (uint8_t * p_buffer)
Links the element values to the ones in parameter.
linkCoords() [2/2]
C3D_API void castor3d::BufferElementGroup::linkCoords (uint8_t * p_buffer, uint32_t p_stride)
Links the element values to the ones in parameter.
Remarks
Replace buffer values by element values
Parameters
[in] p_buffer The values buffer
[in] p_stride The element binay size
ptr()
uint8_t* castor3d::BufferElementGroup::ptr () inline
Retrieves a pointer on the data buffer.
Returns
The pointer
References m_buffer.
Referenced by castor3d::Vertex::getBitangent(), castor3d::Vertex::getNormal(), castor3d::Vertex::getPosition(), castor3d::Vertex::getTangent(), castor3d::Vertex::getTexCoord(), castor3d::Vertex::setBitangent(), castor3d::Vertex::setNormal(), castor3d::Vertex::setPosition(), castor3d::Vertex::setTangent(), and castor3d::Vertex::setTexCoord().
setIndex()
void castor3d::BufferElementGroup::setIndex (uint32_t p_index) inline
sets the group index
Parameters
[in] p_index The new value
References m_index.
Member Data Documentation
m_buffer
uint8_t* castor3d::BufferElementGroup::m_buffer protected
The elements values.
Referenced by constPtr(), and ptr().
m_index
uint32_t castor3d::BufferElementGroup::m_index protected
The group index.
Referenced by getIndex(), and setIndex().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Mesh/Buffer/BufferElementGroup.hpp