Castor3D: Castor3D Namespace Reference
Castor3D Namespace Reference
Classes
class Animable
Animable public interface.
class AnimatedObject
Represents the animated objects.
class AnimatedObjectGroup
Class which represents the animated object groups.
class AnimatedObjectGroupManager
AnimatedObjectGroup manager.
class Animation
Animation class.
class AnimationObject
Class which represents the moving things.
class BackBuffers
Back buffers class.
class BillboardList
Billboards list.
class BillboardManager
BillboardsList manager.
struct BillboardRenderNode
Helper structure used to render billboards.
class BinaryChunk
Binary data chunk base class.
class BinaryParser
Binary data chunk writer/reader base class.
class BlendState
Blending configurations grouping class.
class BlendStateManager
BlendState manager.
class Bone
Class holding bone data.
class BonedVertex
Vertex with bones infos representation.
class BorderPanelOverlay
A rectangular overlay with a border.
class BufferDeclaration
Description of all elements in a vertex buffer.
struct BufferElementDeclaration
Buffer element description.
class BufferElementGroup
Holds data of a vertex buffer elements group.
class Camera
Class which represents a Camera.
class CameraManager
Camera manager.
class ChunkFiller
Chunk filler.
class ChunkFiller< Castor::Colour >
ChunkFiller specialisation for Castor::Colour.
class ChunkFiller< Castor::Coords2d >
ChunkFiller specialisation for Castor::Coords2d.
class ChunkFiller< Castor::Coords2f >
ChunkFiller specialisation for Castor::Coords2f.
class ChunkFiller< Castor::Coords2i >
ChunkFiller specialisation for Castor::Coords2i.
class ChunkFiller< Castor::Coords2ui >
ChunkFiller specialisation for Castor::Coords2ui.
class ChunkFiller< Castor::Coords3d >
ChunkFiller specialisation for Castor::Coords3d.
class ChunkFiller< Castor::Coords3f >
ChunkFiller specialisation for Castor::Coords3f.
class ChunkFiller< Castor::Coords3i >
ChunkFiller specialisation for Castor::Coords3i.
class ChunkFiller< Castor::Coords3ui >
ChunkFiller specialisation for Castor::Coords3ui.
class ChunkFiller< Castor::Coords4d >
ChunkFiller specialisation for Castor::Coords4d.
class ChunkFiller< Castor::Coords4f >
ChunkFiller specialisation for Castor::Coords4f.
class ChunkFiller< Castor::Coords4i >
ChunkFiller specialisation for Castor::Coords4i.
class ChunkFiller< Castor::Coords4ui >
ChunkFiller specialisation for Castor::Coords4ui.
class ChunkFiller< Castor::Matrix2x2d >
ChunkFiller specialisation for Castor::Matrix2x2d.
class ChunkFiller< Castor::Matrix2x2f >
ChunkFiller specialisation for Castor::Matrix2x2f.
class ChunkFiller< Castor::Matrix3x3d >
ChunkFiller specialisation for Castor::Matrix3x3d.
class ChunkFiller< Castor::Matrix3x3f >
ChunkFiller specialisation for Castor::Matrix3x3f.
class ChunkFiller< Castor::Matrix4x4d >
ChunkFiller specialisation for Castor::Matrix4x4d.
class ChunkFiller< Castor::Matrix4x4f >
ChunkFiller specialisation for Castor::Matrix4x4f.
class ChunkFiller< Castor::Path >
ChunkFiller specialisation for Castor::Path.
class ChunkFiller< Castor::Point2d >
ChunkFiller specialisation for Castor::Point2d.
class ChunkFiller< Castor::Point2f >
ChunkFiller specialisation for Castor::Point2f.
class ChunkFiller< Castor::Point2i >
ChunkFiller specialisation for Castor::Point2i.
class ChunkFiller< Castor::Point2ui >
ChunkFiller specialisation for Castor::Point2ui.
class ChunkFiller< Castor::Point3d >
ChunkFiller specialisation for Castor::Point3d.
class ChunkFiller< Castor::Point3f >
ChunkFiller specialisation for Castor::Point3f.
class ChunkFiller< Castor::Point3i >
ChunkFiller specialisation for Castor::Point3i.
class ChunkFiller< Castor::Point3ui >
ChunkFiller specialisation for Castor::Point3ui.
class ChunkFiller< Castor::Point4d >
ChunkFiller specialisation for Castor::Point4d.
class ChunkFiller< Castor::Point4f >
ChunkFiller specialisation for Castor::Point4f.
class ChunkFiller< Castor::Point4i >
ChunkFiller specialisation for Castor::Point4i.
class ChunkFiller< Castor::Point4ui >
ChunkFiller specialisation for Castor::Point4ui.
class ChunkFiller< Castor::Position >
ChunkFiller specialisation for Castor::Position.
class ChunkFiller< Castor::Quaternion >
ChunkFiller specialisation for Castor::Quaternion.
class ChunkFiller< Castor::Size >
ChunkFiller specialisation for Castor::Size.
class ChunkFiller< Castor::String >
ChunkFiller specialisation for Castor::String.
class ChunkFillerBase
Chunk filler.
class ChunkParser
Chunk parser.
class ChunkParser< Castor::Colour >
ChunkParser specialisation for Castor::Colour.
class ChunkParser< Castor::Coords2d >
ChunkParser specialisation for Castor::Coords2d.
class ChunkParser< Castor::Coords2f >
ChunkParser specialisation for Castor::Coords2f.
class ChunkParser< Castor::Coords2i >
ChunkParser specialisation for Castor::Coords2i.
class ChunkParser< Castor::Coords2ui >
ChunkParser specialisation for Castor::Coords2ui.
class ChunkParser< Castor::Coords3d >
ChunkParser specialisation for Castor::Coords3d.
class ChunkParser< Castor::Coords3f >
ChunkParser specialisation for Castor::Coords3f.
class ChunkParser< Castor::Coords3i >
ChunkParser specialisation for Castor::Coords3i.
class ChunkParser< Castor::Coords3ui >
ChunkParser specialisation for Castor::Coords3ui.
class ChunkParser< Castor::Coords4d >
ChunkParser specialisation for Castor::Coords4d.
class ChunkParser< Castor::Coords4f >
ChunkParser specialisation for Castor::Coords4f.
class ChunkParser< Castor::Coords4i >
ChunkParser specialisation for Castor::Coords4i.
class ChunkParser< Castor::Coords4ui >
ChunkParser specialisation for Castor::Coords4ui.
class ChunkParser< Castor::Matrix2x2d >
ChunkParser specialisation for Castor::Matrix2x2d.
class ChunkParser< Castor::Matrix2x2f >
ChunkParser specialisation for Castor::Matrix2x2f.
class ChunkParser< Castor::Matrix3x3d >
ChunkParser specialisation for Castor::Matrix3x3d.
class ChunkParser< Castor::Matrix3x3f >
ChunkParser specialisation for Castor::Matrix3x3f.
class ChunkParser< Castor::Matrix4x4d >
ChunkParser specialisation for Castor::Matrix4x4d.
class ChunkParser< Castor::Matrix4x4f >
ChunkParser specialisation for Castor::Matrix4x4f.
class ChunkParser< Castor::Path >
ChunkParser specialisation for Castor::Path.
class ChunkParser< Castor::Point2d >
ChunkParser specialisation for Castor::Point2d.
class ChunkParser< Castor::Point2f >
ChunkParser specialisation for Castor::Point2f.
class ChunkParser< Castor::Point2i >
ChunkParser specialisation for Castor::Point2i.
class ChunkParser< Castor::Point2ui >
ChunkParser specialisation for Castor::Point2ui.
class ChunkParser< Castor::Point3d >
ChunkParser specialisation for Castor::Point3d.
class ChunkParser< Castor::Point3f >
ChunkParser specialisation for Castor::Point3f.
class ChunkParser< Castor::Point3i >
ChunkParser specialisation for Castor::Point3i.
class ChunkParser< Castor::Point3ui >
ChunkParser specialisation for Castor::Point3ui.
class ChunkParser< Castor::Point4d >
ChunkParser specialisation for Castor::Point4d.
class ChunkParser< Castor::Point4f >
ChunkParser specialisation for Castor::Point4f.
class ChunkParser< Castor::Point4i >
ChunkParser specialisation for Castor::Point4i.
class ChunkParser< Castor::Point4ui >
ChunkParser specialisation for Castor::Point4ui.
class ChunkParser< Castor::Position >
ChunkParser specialisation for Castor::Position.
class ChunkParser< Castor::Quaternion >
ChunkParser specialisation for Castor::Quaternion.
class ChunkParser< Castor::Size >
ChunkParser specialisation for Castor::Size.
class ChunkParser< Castor::String >
ChunkParser specialisation for Castor::String.
class ChunkParserBase
Chunk parser.
class CleanupEvent
Cleaner event.
class ColourRenderBuffer
Render buffer receiving colour component.
class Cone
The cone is a basic primitive, with a parametrable number of faces.
class Context
Class which holds the rendering context.
class CpuBuffer
3D Buffer management class
class Cube
The cube representation.
class Cylinder
The cylinder representation.
class DebugOverlays
Debug overlays class.
class DepthStencilRenderBuffer
Render buffer receiving depth and/or stencil component.
class DepthStencilState
Depth and stencil buffers configurations class.
class DepthStencilStateManager
DepthStencilState manager.
class DirectionalLight
Class which represents a Directional Light.
class DividerPlugin
Divider Plugin class.
class DynamicTexture
Dynamic texture class.
struct ElementAttacher
Helper structure to enable attaching if a type supports it.
struct ElementAttacher< BillboardList >
Helper structure to enable attaching if a type supports it.
struct ElementAttacher< Camera >
Helper structure to enable attaching if a type supports it.
struct ElementAttacher< Elem, typename std::enable_if< !is_detachable< Elem >::value >::type >
Helper structure to enable attaching if a type supports it.
struct ElementAttacher< Geometry >
Helper structure to enable attaching if a type supports it.
struct ElementAttacher< Light >
Helper structure to enable attaching if a type supports it.
struct ElementAttacher< SceneNode >
Helper structure to enable attaching if a type supports it.
struct ElementCleaner
Helper structure to enable cleanup if a type supports it.
struct ElementCleaner< Elem, typename std::enable_if< !is_cleanable< Elem >::value >::type >
Helper structure to enable cleanup if a type supports it.
struct ElementCleaner< Elem, typename std::enable_if< is_cleanable< Elem >::value &&!is_instant< Elem >::value >::type >
Helper structure to enable cleanup if a type supports it.
struct ElementCleaner< Elem, typename std::enable_if< is_cleanable< Elem >::value &&is_instant< Elem >::value >::type >
Helper structure to enable cleanup if a type supports it.
struct ElementCleaner< FrameListener, FrameListener >
Helper structure to enable cleanup if a type supports it.
struct ElementDetacher
Helper structure to enable detaching if a type supports it.
struct ElementDetacher< Elem, typename std::enable_if< !is_detachable< Elem >::value >::type >
Helper structure to enable detaching if a type supports it.
struct ElementDetacher< Elem, typename std::enable_if< is_detachable< Elem >::value >::type >
Helper structure to enable detaching if a type supports it.
struct ElementInitialiser
Helper structure to enable initialisation if a type supports it.
struct ElementInitialiser< Elem, typename std::enable_if< !is_initialisable< Elem >::value >::type >
Helper structure to enable initialisation if a type supports it.
struct ElementInitialiser< Elem, typename std::enable_if< is_initialisable< Elem >::value &&!is_instant< Elem >::value >::type >
Helper structure to enable cleanup if a type supports it.
struct ElementInitialiser< Elem, typename std::enable_if< is_initialisable< Elem >::value &&is_instant< Elem >::value >::type >
Helper structure to enable cleanup if a type supports it.
struct ElementMerger
Helper structure to enable moving elements from a manager to another.
struct ElementMerger< Key, Elem, typename std::enable_if< !is_detachable< Elem >::value >::type >
Helper structure to enable moving elements from a manager to another.
struct ElementMerger< Key, Elem, typename std::enable_if< is_detachable< Elem >::value >::type >
Helper structure to enable moving elements from a manager to another.
class Engine
Main System.
class Face
Face implementation.
class FontTexture
Contains the font and the texture assiated to this font.
class FrameBuffer
Frame buffer class.
class FrameBufferAttachment
Description of an attachment between a frame buffer and a render buffer.
class FrameEvent
The interface which represents a frame event.
class FrameListener
User event synchronisation class.
class FrameVariable
Shader variable representation.
class FrameVariableBuffer
Shader variables buffer.
struct FrameVariableDataTyper
Helper structure used to retrieve the frame variable data type name.
class FunctorEvent
Functor event.
class Generator
class GeneratorPlugin
Generator Plugin class.
class GenericPlugin
Generic Plugin class.
class Geometry
Geometry handler class.
class GeometryBuffers
Geometry buffers holder.
class GeometryManager
Geometry manager.
struct GeometryRenderNode
Helper structure used to render submeshes.
class GpuBuffer
Base class for renderer dependant buffers.
class GpuQuery
GPU query implementation.
class HaarmPeterDuikerToneMapping
Implements Haarm-Peter Duiker tone mapping algorithm.
class HejlBurgessDawsonToneMapping
Implements Jim Hejl and Richard Burgess-Dawson tone mapping algorithm.
class Icosahedron
The icosahedron representation.
class Importer
Base class for external file import.
class ImporterPlugin
Importer Plugin class.
class IndexBuffer
Index buffer representation.
class InitialiseEvent
Initialiser event.
class Interpolator
Template class which handles the interpolations, would it be quaternion, point, real, ... interpolations.
class InterpolatorT
Template class which handles the interpolations, would it be quaternion, point, real, ... interpolations.
class InterpolatorT< Castor::Quaternion, eINTERPOLATOR_MODE_LINEAR >
Class which handles the Quaternion linear interpolations.
class InterpolatorT< Type, eINTERPOLATOR_MODE_LINEAR >
Partial specialisation of Interpolator, for eINTERPOLATOR_MODE_LINEAR.
class InterpolatorT< Type, eINTERPOLATOR_MODE_NONE >
Partial specialisation of Interpolator, for eINTERPOLATOR_MODE_NONE.
class IPipelineImpl
Implementation of the rendering pipeline.
struct is_cleanable
Helper class, telling if the template parameter has a Cleanup(void) method.
struct is_cleanable< BlendState >
struct is_cleanable< DepthStencilState >
struct is_cleanable< Material >
struct is_cleanable< Mesh >
struct is_cleanable< RasteriserState >
struct is_cleanable< RenderWindow >
struct is_cleanable< Sampler >
struct is_cleanable< Scene >
struct is_detachable
Helper class, telling if the template parameter has the method Detach.
struct is_detachable< BillboardList >
struct is_detachable< Camera >
struct is_detachable< Geometry >
struct is_detachable< Light >
struct is_detachable< MovableObject >
struct is_detachable< SceneNode >
struct is_initialisable
Helper class, telling if the template parameter has an Initialise(void) method.
struct is_initialisable< BlendState >
struct is_initialisable< DepthStencilState >
struct is_initialisable< Material >
struct is_initialisable< RasteriserState >
struct is_initialisable< Sampler >
struct is_initialisable< Scene >
struct is_instant
Helper class, telling if the template parameter Initialise() and Cleanup() methods must be called instantly.
struct is_instant< Scene >
class IWindowHandle
Platform dependant window handle implementation.
class KeyFrame
The class which manages key frames.
class Light
Light source implementation.
class LightCategory
Holds light components.
class LightFactory
The light source factory.
class LightManager
Light manager.
class LinearToneMapping
Implements linear tone mapping algorithm.
class ListenerManager
Frame listener manager.
struct ManagedObjectNamer
Helper structure to get an object type name.
struct ManagedObjectNamer< AnimatedObjectGroup >
Helper structure to get an object type name.
struct ManagedObjectNamer< BillboardList >
Helper structure to get an object type name.
struct ManagedObjectNamer< BlendState >
Helper structure to get an object type name.
struct ManagedObjectNamer< Camera >
Helper structure to get an object type name.
struct ManagedObjectNamer< DepthStencilState >
Helper structure to get an object type name.
struct ManagedObjectNamer< FrameListener >
Helper structure to get an object type name.
struct ManagedObjectNamer< Geometry >
Helper structure to get an object type name.
struct ManagedObjectNamer< Light >
Helper structure to get an object type name.
struct ManagedObjectNamer< Material >
Helper structure to get an object type name.
struct ManagedObjectNamer< Mesh >
Helper structure to get an object type name.
struct ManagedObjectNamer< Overlay >
Helper structure to get an object type name.
struct ManagedObjectNamer< PluginBase >
Helper structure to get an object type name.
struct ManagedObjectNamer< RasteriserState >
Helper structure to get an object type name.
struct ManagedObjectNamer< RenderTarget >
Helper structure to get an object type name.
struct ManagedObjectNamer< RenderTechnique >
Helper structure to get an object type name.
struct ManagedObjectNamer< RenderWindow >
Helper structure to get an object type name.
struct ManagedObjectNamer< Sampler >
Helper structure to get an object type name.
struct ManagedObjectNamer< Scene >
Helper structure to get an object type name.
struct ManagedObjectNamer< SceneNode >
Helper structure to get an object type name.
class Manager
Base class for an element manager.
class ManagerView
View on a resource manager.
class Material
Definition of a material.
class MaterialManager
Material collection, with additional functions.
class MatrixFrameVariable
Matrix shader variable with variable type and dimensions.
class Mesh
The mesh representation.
class MeshFactory
The mesh factory.
class MeshGenerator
Mesh category is used to create a mesh's vertices, it is created by MeshFactory.
class MeshManager
Meshes manager.
class MovableObject
Movable object class.
struct MtxFrameVariableDefinitions
Helper structure containing definitions for a matrix frame variable type.
class ObjectManager
Base class for a scene element manager.
struct ObjectManagerEngineGetter
Helper structure to retrieve an ObjectManager Engine instance.
class OneFrameVariable
Single shader variable with variable type.
struct OneFrameVariableDefinitions
Helper structure containing definitions for a frame variable type.
class Overlay
The overlay class.
class OverlayCategory
Holds specific members for an overlay category.
struct OverlayCategorySort
Structure used to sort overlays by order.
class OverlayFactory
The mesh factory.
class OverlayManager
Overlay collection, with additional add and remove functions to manage Z-Index.
class OverlayRenderer
The overlay renderer.
class PanelOverlay
A simple rectangular overlay.
class Parameters
Configuration parameters.
class Pass
Definition of a material pass.
class Pattern
Pattern handler class.
class Pipeline
The rendering pipeline.
class Plane
The plane representation.
class PluginBase
Plugin Base class.
class PluginException
Plugin loading exception.
class PluginManager
Plug-ins manager.
struct PntFrameVariableDefinitions
Helper structure containing definitions for a point frame variable type.
class PointFrameVariable
Point shader variable with variable type and dimensions.
class PointLight
Class which represents a PointLight.
class PostEffect
Post render effect base class.
class PostFxPlugin
Post effect plug-in class.
class ProgramInputLayout
ProgramInputLayout class.
class Projection
Projection mesh representation.
class RasteriserState
Rasteriser configuration class.
class RasteriserStateManager
RasteriserState manager.
class Ray
Ray representation.
class ReinhardToneMapping
Implements Reinhard tone mapping algorithm.
class RenderBuffer
Render buffer base class.
class RenderBufferAttachment
Description of an attachment between a frame buffer and a render buffer.
struct RendererAdder
Template class used to add a renderer to the list.
struct RendererCreator
Template class used to create a renderer.
class RendererPlugin
Renderer Plugin class.
class RenderLoop
Render loop base class.
class RenderLoopAsync
Main System.
class RenderLoopSync
Synchronous render loop.
struct RenderNode
Helper structure used link a pass and a shader program.
class RenderSystem
The render system representation.
class RenderTarget
Render target class.
class RenderTechnique
Render technique base class.
class RenderTechniqueManager
Render technique manager.
class RenderWindow
Render window representation.
class ResizeWindowEvent
Event used to resize a RenderWindow before rendering it.
class ResourceManager
Base class for an element manager.
struct ResourceManagerEngineGetter
Helper structure to retrieve an ObjectManager Engine instance.
class Sampler
Defines a sampler for a texture.
class SamplerManager
Sampler manager.
class Scene
Scene handler class.
class SceneFileContext
The context used into parsing functions.
class SceneFileParser
ESCN file parser.
class SceneManager
Scene manager.
class SceneNode
The scene node handler class.
class SceneNodeManager
Light manager.
struct SceneRenderNode
Helper structure used to render submeshes.
class ShaderManager
Manager used to hold the shader programs. Holds it, destroys it during a rendering loop.
class ShaderObject
Base shader class.
class ShaderProgram
Base shader program implementation, used to share functions through the supported shader languages.
class Skeleton
The skeleton, holds each bone.
class SkeletonAnimationBone
Implementation of MovingObjectBase for Bones.
class SkeletonAnimationNode
Implementation of MovingObjectBase for abstract nodes.
class SkeletonAnimationObject
Implementation of MovingObjectBase for MovableObject.
class Sphere
The sphere primitive.
class SpotLight
Class which represents a SpotLight.
class StaticTexture
Static texture class.
struct stFACE_INDICES
Holds the 3 vertex indices.
struct stFACE_INFOS
Holds face informations.
struct stVERTEX_BONE_DATA
Holds bone data for one vertex.
struct stVERTEX_GROUP
Holds the all components of a vertex array.
class Subdivider
Subdividers main class C3D_API.
class SubdivisionFrameEvent
Threaded Subdivision Frame event.
class Submesh
The submesh representation.
class TargetManager
RenderTarget manager.
class TechniqueFactory
Render technique factory.
class TechniquePlugin
Render technique plug-in class.
class TextOverlay
An overlay with a text.
class Texture
Texture base class.
class TextureAttachment
Description of an attachment between a frame buffer and a texture.
class TextureUnit
Texture unit representation.
class TFrameVariable
Shader variable representation with variable type.
class ToneMapping
Tone mapping base class.
class ToneMappingFactory
Tone mapping factory.
class Torus
The torus representation.
struct TypeRenderNodesByPassMap
Pass sorted SubmeshRenderNodesMap map.
class Version
Version management class.
class VersionException
Version comparison exception.
class Vertex
Representation of a vertex.
class VertexBuffer
Vertex buffer representation.
class Viewport
Class to represent a viewport.
class WindowHandle
Platform independant window handle implementation.
class WindowManager
Render windows manager.
Typedefs
typedef enum Castor3D::eCHUNK_TYPE eCHUNK_TYPE
Binary data chunk types enumeration.
typedef OverlayManager::iterator OverlayManagerIt
typedef OverlayManager::const_iterator OverlayManagerConstIt
typedef enum Castor3D::eSECTION eSECTION
Scene file sections Enum.
Enumerations
enum eCHUNK_TYPE : uint32_t {
eCHUNK_TYPE_UNKNOWN = MAKE_CHUNK_ID(' ', ' ', ' ', ' '), eCHUNK_TYPE_CBSN_FILE = MAKE_CHUNK_ID('C', 'B', 'S', 'N'), eCHUNK_TYPE_SAMPLER = MAKE_CHUNK_ID('S', 'A', 'M', 'P'), eCHUNK_TYPE_SAMPLER_MINFILTER = MAKE_CHUNK_ID('S', 'A', 'M', 'N'),
eCHUNK_TYPE_SAMPLER_MAGFILTER = MAKE_CHUNK_ID('S', 'A', 'M', 'G'), eCHUNK_TYPE_SAMPLER_MIPFILTER = MAKE_CHUNK_ID('S', 'A', 'M', 'P'), eCHUNK_TYPE_SAMPLER_MINLOD = MAKE_CHUNK_ID('S', 'I', 'L', 'D'), eCHUNK_TYPE_SAMPLER_MAXLOD = MAKE_CHUNK_ID('S', 'A', 'L', 'D'),
eCHUNK_TYPE_SAMPLER_LODBIAS = MAKE_CHUNK_ID('S', 'L', 'B', 'S'), eCHUNK_TYPE_SAMPLER_UWRAP = MAKE_CHUNK_ID('S', 'U', 'W', 'P'), eCHUNK_TYPE_SAMPLER_VWRAP = MAKE_CHUNK_ID('S', 'V', 'W', 'P'), eCHUNK_TYPE_SAMPLER_WWRAP = MAKE_CHUNK_ID('S', 'W', 'W', 'P'),
eCHUNK_TYPE_SAMPLER_BORDER = MAKE_CHUNK_ID('S', 'B', 'D', 'R'), eCHUNK_TYPE_SAMPLER_MAXANISOTROPY = MAKE_CHUNK_ID('S', 'A', 'A', 'N'), eCHUNK_TYPE_SAMPLER_COLOUR = MAKE_CHUNK_ID('S', 'A', 'C', 'R'), eCHUNK_TYPE_MATERIAL = MAKE_CHUNK_ID('M', 'A', 'T', 'L'),
eCHUNK_TYPE_MATERIAL_PASS = MAKE_CHUNK_ID('M', 'P', 'A', 'S'), eCHUNK_TYPE_PASS_DIFFUSE = MAKE_CHUNK_ID('P', 'D', 'I', 'F'), eCHUNK_TYPE_PASS_AMBIENT = MAKE_CHUNK_ID('P', 'A', 'M', 'B'), eCHUNK_TYPE_PASS_SPECULAR = MAKE_CHUNK_ID('P', 'S', 'P', 'C'),
eCHUNK_TYPE_PASS_EMISSIVE = MAKE_CHUNK_ID('P', 'E', 'M', 'S'), eCHUNK_TYPE_PASS_EXPONENT = MAKE_CHUNK_ID('P', 'X', 'P', 'N'), eCHUNK_TYPE_PASS_ALPHA = MAKE_CHUNK_ID('P', 'A', 'L', 'P'), eCHUNK_TYPE_PASS_TWOSIDED = MAKE_CHUNK_ID('P', 'B', 'S', 'D'),
eCHUNK_TYPE_PASS_GLSHADER = MAKE_CHUNK_ID('P', 'G', 'L', 'S'), eCHUNK_TYPE_PASS_HLSHADER = MAKE_CHUNK_ID('P', 'H', 'L', 'S'), eCHUNK_TYPE_SHADER_FILE = MAKE_CHUNK_ID('S', 'F', 'I', 'L'), eCHUNK_TYPE_SHADER_SOURCE = MAKE_CHUNK_ID('S', 'S', 'R', 'C'),
eCHUNK_TYPE_SHADER_PROGRAM = MAKE_CHUNK_ID('S', 'P', 'G', 'M'), eCHUNK_TYPE_SHADER_OBJECT = MAKE_CHUNK_ID('S', 'O', 'B', 'J'), eCHUNK_TYPE_SHADER_OBJECT_TYPE = MAKE_CHUNK_ID('S', 'O', 'T', 'P'), eCHUNK_TYPE_PROGRAM_VARIABLE = MAKE_CHUNK_ID('P', 'V', 'A', 'R'),
eCHUNK_TYPE_VARIABLE_TYPE = MAKE_CHUNK_ID('V', 'T', 'Y', 'P'), eCHUNK_TYPE_VARIABLE_COUNT = MAKE_CHUNK_ID('V', 'C', 'N', 'T'), eCHUNK_TYPE_VARIABLE_VALUE = MAKE_CHUNK_ID('V', 'V', 'A', 'L'), eCHUNK_TYPE_SHADER_OBJECT_ENTRY = MAKE_CHUNK_ID('S', 'O', 'E', 'T'),
eCHUNK_TYPE_SHADER_OBJECT_FILE = MAKE_CHUNK_ID('S', 'O', 'F', 'L'), eCHUNK_TYPE_SHADER_OBJECT_SOURCE = MAKE_CHUNK_ID('S', 'O', 'S', 'C'), eCHUNK_TYPE_SHADER_OBJECT_INPUT = MAKE_CHUNK_ID('S', 'O', 'I', 'P'), eCHUNK_TYPE_SHADER_OBJECT_OUTPUT = MAKE_CHUNK_ID('S', 'O', 'O', 'P'),
eCHUNK_TYPE_SHADER_OBJECT_OUTCOUNT = MAKE_CHUNK_ID('S', 'O', 'O', 'C'), eCHUNK_TYPE_PASS_TEXTURE = MAKE_CHUNK_ID('T', 'X', 'U', 'N'), eCHUNK_TYPE_TEXTURE_FILE = MAKE_CHUNK_ID('T', 'F', 'I', 'L'), eCHUNK_TYPE_TEXTURE_FORMAT = MAKE_CHUNK_ID('T', 'F', 'M', 'T'),
eCHUNK_TYPE_TEXTURE_DIMENSIONS = MAKE_CHUNK_ID('T', 'D', 'I', 'M'), eCHUNK_TYPE_TEXTURE_DATA = MAKE_CHUNK_ID('T', 'D', 'A', 'T'), eCHUNK_TYPE_TEXTURE_MAP = MAKE_CHUNK_ID('T', 'M', 'A', 'P'), eCHUNK_TYPE_TEXTURE_ALPHA_FUNC = MAKE_CHUNK_ID('T', 'A', 'F', 'N'),
eCHUNK_TYPE_TEXTURE_ALPHA_BLEND = MAKE_CHUNK_ID('T', 'A', 'B', 'N'), eCHUNK_TYPE_TEXTURE_ALPHA_BLEND0 = MAKE_CHUNK_ID('T', 'A', 'B', '0'), eCHUNK_TYPE_TEXTURE_ALPHA_BLEND1 = MAKE_CHUNK_ID('T', 'A', 'B', '1'), eCHUNK_TYPE_TEXTURE_ALPHA_BLEND2 = MAKE_CHUNK_ID('T', 'A', 'B', '2'),
eCHUNK_TYPE_TEXTURE_RGB_BLEND = MAKE_CHUNK_ID('T', 'C', 'B', 'N'), eCHUNK_TYPE_TEXTURE_RGB_BLEND0 = MAKE_CHUNK_ID('T', 'C', 'B', '0'), eCHUNK_TYPE_TEXTURE_RGB_BLEND1 = MAKE_CHUNK_ID('T', 'C', 'B', '1'), eCHUNK_TYPE_TEXTURE_RGB_BLEND2 = MAKE_CHUNK_ID('T', 'C', 'B', '2'),
eCHUNK_TYPE_TEXTURE_COLOUR = MAKE_CHUNK_ID('T', 'C', 'O', 'L'), eCHUNK_TYPE_TEXTURE_CHANNEL = MAKE_CHUNK_ID('T', 'C', 'H', 'N'), eCHUNK_TYPE_TEXTURE_SAMPLER = MAKE_CHUNK_ID('T', 'S', 'P', 'R'), eCHUNK_TYPE_PASS_BLEND_FUNC = MAKE_CHUNK_ID('P', 'B', 'F', 'N'),
eCHUNK_TYPE_SCENE = MAKE_CHUNK_ID('S', 'C', 'E', 'N'), eCHUNK_TYPE_SCENE_BACKGROUND = MAKE_CHUNK_ID('S', 'B', 'K', 'C'), eCHUNK_TYPE_SCENE_AMBIENT = MAKE_CHUNK_ID('S', 'A', 'M', 'B'), eCHUNK_TYPE_SCENE_NODE = MAKE_CHUNK_ID('S', 'N', 'O', 'D'),
eCHUNK_TYPE_NODE_PARENT = MAKE_CHUNK_ID('N', 'P', 'A', 'R'), eCHUNK_TYPE_NODE_POSITION = MAKE_CHUNK_ID('N', 'P', 'O', 'S'), eCHUNK_TYPE_NODE_ORIENTATION = MAKE_CHUNK_ID('N', 'R', 'O', 'T'), eCHUNK_TYPE_NODE_SCALE = MAKE_CHUNK_ID('N', 'S', 'C', 'L'),
eCHUNK_TYPE_MOVABLE_NODE = MAKE_CHUNK_ID('M', 'N', 'O', 'D'), eCHUNK_TYPE_LIGHT = MAKE_CHUNK_ID('L', 'G', 'H', 'T'), eCHUNK_TYPE_LIGHT_TYPE = MAKE_CHUNK_ID('L', 'T', 'Y', 'P'), eCHUNK_TYPE_LIGHT_COLOUR = MAKE_CHUNK_ID('L', 'D', 'I', 'F'),
eCHUNK_TYPE_LIGHT_INTENSITY = MAKE_CHUNK_ID('L', 'A', 'M', 'B'), eCHUNK_TYPE_LIGHT_ATTENUATION = MAKE_CHUNK_ID('L', 'A', 'T', 'T'), eCHUNK_TYPE_LIGHT_CUTOFF = MAKE_CHUNK_ID('L', 'C', 'U', 'T'), eCHUNK_TYPE_LIGHT_EXPONENT = MAKE_CHUNK_ID('L', 'X', 'P', 'N'),
eCHUNK_TYPE_CAMERA = MAKE_CHUNK_ID('C', 'A', 'M', 'R'), eCHUNK_TYPE_VIEWPORT = MAKE_CHUNK_ID('V', 'P', 'R', 'T'), eCHUNK_TYPE_VIEWPORT_TYPE = MAKE_CHUNK_ID('V', 'T', 'Y', 'P'), eCHUNK_TYPE_VIEWPORT_LEFT = MAKE_CHUNK_ID('V', 'L', 'F', 'T'),
eCHUNK_TYPE_VIEWPORT_RIGHT = MAKE_CHUNK_ID('V', 'R', 'G', 'T'), eCHUNK_TYPE_VIEWPORT_TOP = MAKE_CHUNK_ID('V', 'T', 'O', 'P'), eCHUNK_TYPE_VIEWPORT_BOTTOM = MAKE_CHUNK_ID('V', 'B', 'T', 'M'), eCHUNK_TYPE_VIEWPORT_NEAR = MAKE_CHUNK_ID('V', 'N', 'E', 'A'),
eCHUNK_TYPE_VIEWPORT_FAR = MAKE_CHUNK_ID('V', 'F', 'A', 'R'), eCHUNK_TYPE_VIEWPORT_SIZE = MAKE_CHUNK_ID('V', 'S', 'I', 'Z'), eCHUNK_TYPE_VIEWPORT_RATIO = MAKE_CHUNK_ID('V', 'R', 'T', 'O'), eCHUNK_TYPE_VIEWPORT_FOVY = MAKE_CHUNK_ID('V', 'F', 'V', 'Y'),
eCHUNK_TYPE_GEOMETRY = MAKE_CHUNK_ID('G', 'E', 'O', 'M'), eCHUNK_TYPE_GEOMETRY_MESH = MAKE_CHUNK_ID('G', 'M', 'S', 'H'), eCHUNK_TYPE_GEOMETRY_MATERIAL_ID = MAKE_CHUNK_ID('G', 'M', 'T', 'I'), eCHUNK_TYPE_GEOMETRY_MATERIAL_NAME = MAKE_CHUNK_ID('G', 'M', 'T', 'N'),
eCHUNK_TYPE_BILLBOARD = MAKE_CHUNK_ID('B', 'L', 'B', 'D'), eCHUNK_TYPE_BILLBOARD_MATERIAL = MAKE_CHUNK_ID('B', 'L', 'M', 'T'), eCHUNK_TYPE_BILLBOARD_DIMENSIONS = MAKE_CHUNK_ID('B', 'L', 'S', 'Z'), eCHUNK_TYPE_BILLBOARD_POSITION = MAKE_CHUNK_ID('B', 'L', 'P', 'T'),
eCHUNK_TYPE_MESH = MAKE_CHUNK_ID('M', 'E', 'S', 'H'), eCHUNK_TYPE_SUBMESH = MAKE_CHUNK_ID('S', 'M', 'S', 'H'), eCHUNK_TYPE_SUBMESH_TOPOLOGY = MAKE_CHUNK_ID('T', 'O', 'P', 'O'), eCHUNK_TYPE_SUBMESH_VERTEX = MAKE_CHUNK_ID('V', 'R', 'T', 'X'),
eCHUNK_TYPE_SUBMESH_FACE = MAKE_CHUNK_ID('F', 'A', 'C', 'E'), eCHUNK_TYPE_WINDOW = MAKE_CHUNK_ID('W', 'I', 'N', 'D'), eCHUNK_TYPE_WINDOW_VSYNC = MAKE_CHUNK_ID('W', 'V', 'S', 'Y'), eCHUNK_TYPE_WINDOW_FULLSCREEN = MAKE_CHUNK_ID('W', 'F', 'S', 'N'),
eCHUNK_TYPE_TARGET = MAKE_CHUNK_ID('R', 'T', 'G', 'T'), eCHUNK_TYPE_TARGET_FORMAT = MAKE_CHUNK_ID('R', 'F', 'M', 'T'), eCHUNK_TYPE_TARGET_SAMPLES = MAKE_CHUNK_ID('R', 'M', 'S', 'A'), eCHUNK_TYPE_TARGET_TECHNIQUE = MAKE_CHUNK_ID('R', 'T', 'E', 'C'),
eCHUNK_TYPE_TARGET_SIZE = MAKE_CHUNK_ID('R', 'S', 'I', 'Z'), eCHUNK_TYPE_TARGET_SCENE = MAKE_CHUNK_ID('R', 'S', 'C', 'N'), eCHUNK_TYPE_TARGET_CAMERA = MAKE_CHUNK_ID('R', 'C', 'A', 'M'), eCHUNK_TYPE_TARGET_STEREO = MAKE_CHUNK_ID('R', 'S', 'T', 'R'),
eCHUNK_TYPE_OVERLAY = MAKE_CHUNK_ID('O', 'V', 'L', 'Y'), eCHUNK_TYPE_OVERLAY_TYPE = MAKE_CHUNK_ID('O', 'V', 'T', 'Y'), eCHUNK_TYPE_OVERLAY_POSITION = MAKE_CHUNK_ID('O', 'V', 'P', 'S'), eCHUNK_TYPE_OVERLAY_SIZE = MAKE_CHUNK_ID('O', 'V', 'S', 'Z'),
eCHUNK_TYPE_OVERLAY_MATERIAL = MAKE_CHUNK_ID('O', 'V', 'M', 'T'), eCHUNK_TYPE_OVERLAY_VISIBLE = MAKE_CHUNK_ID('O', 'V', 'V', 'S'), eCHUNK_TYPE_OVERLAY_ZINDEX = MAKE_CHUNK_ID('O', 'V', 'Z', 'X'), eCHUNK_TYPE_OVERLAY_BORDER_SIZE = MAKE_CHUNK_ID('O', 'B', 'S', 'Z'),
eCHUNK_TYPE_OVERLAY_BORDER_MATERIAL = MAKE_CHUNK_ID('O', 'B', 'M', 'T'), eCHUNK_TYPE_OVERLAY_FONT = MAKE_CHUNK_ID('O', 'T', 'F', 'T'), eCHUNK_TYPE_OVERLAY_CAPTION = MAKE_CHUNK_ID('O', 'T', 'C', 'N'), eCHUNK_TYPE_DEPTHSTENCIL_STATE = MAKE_CHUNK_ID('D', 'S', 'S', 'T'),
eCHUNK_TYPE_RASTERISER_STATE = MAKE_CHUNK_ID('R', 'T', 'S', 'T'), eCHUNK_TYPE_BLEND_STATE = MAKE_CHUNK_ID('B', 'D', 'S', 'T'), eCHUNK_TYPE_NAME = MAKE_CHUNK_ID('N', 'A', 'M', 'E'), eCHUNK_TYPE_ANIMABLE = MAKE_CHUNK_ID('A', 'N', 'B', 'L'),
eCHUNK_TYPE_ANIMATION = MAKE_CHUNK_ID('A', 'N', 'M', 'N'), eCHUNK_TYPE_ANIM_SCALE = MAKE_CHUNK_ID('A', 'S', 'C', 'L'), eCHUNK_TYPE_MOVING_BASE = MAKE_CHUNK_ID('M', 'V', 'G', 'S'), eCHUNK_TYPE_MOVING_NODE = MAKE_CHUNK_ID('M', 'V', 'N', 'D'),
eCHUNK_TYPE_MOVING_OBJECT = MAKE_CHUNK_ID('M', 'V', 'O', 'J'), eCHUNK_TYPE_MOVING_BONE = MAKE_CHUNK_ID('M', 'V', 'B', 'N'), eCHUNK_TYPE_MOVING_TRANSFORM = MAKE_CHUNK_ID('M', 'V', 'T', 'F'), eCHUNK_TYPE_KEYFRAME = MAKE_CHUNK_ID('K', 'F', 'R', 'M'),
eCHUNK_TYPE_KEYFRAME_TIME = MAKE_CHUNK_ID('K', 'F', 'T', 'M'), eCHUNK_TYPE_KEYFRAME_SCALE = MAKE_CHUNK_ID('K', 'F', 'S', 'C'), eCHUNK_TYPE_KEYFRAME_TRANSLATE = MAKE_CHUNK_ID('K', 'F', 'T', 'R'), eCHUNK_TYPE_KEYFRAME_ROTATE = MAKE_CHUNK_ID('K', 'F', 'R', 'T')
}
Binary data chunk types enumeration.
enum eSECTION : uint32_t {
eSECTION_ROOT = MAKE_SECTION_NAME('R', 'O', 'O', 'T'), eSECTION_SCENE = MAKE_SECTION_NAME('S', 'C', 'N', 'E'), eSECTION_WINDOW = MAKE_SECTION_NAME('W', 'N', 'D', 'W'), eSECTION_SAMPLER = MAKE_SECTION_NAME('S', 'M', 'P', 'R'),
eSECTION_CAMERA = MAKE_SECTION_NAME('C', 'A', 'M', 'R'), eSECTION_VIEWPORT = MAKE_SECTION_NAME('V', 'W', 'P', 'T'), eSECTION_LIGHT = MAKE_SECTION_NAME('L', 'G', 'H', 'T'), eSECTION_NODE = MAKE_SECTION_NAME('N', 'O', 'D', 'E'),
eSECTION_OBJECT = MAKE_SECTION_NAME('O', 'B', 'J', 'T'), eSECTION_OBJECT_MATERIALS = MAKE_SECTION_NAME('O', 'M', 'T', 'L'), eSECTION_FONT = MAKE_SECTION_NAME('F', 'O', 'N', 'T'), eSECTION_PANEL_OVERLAY = MAKE_SECTION_NAME('P', 'O', 'V', 'L'),
eSECTION_BORDER_PANEL_OVERLAY = MAKE_SECTION_NAME('B', 'O', 'V', 'L'), eSECTION_TEXT_OVERLAY = MAKE_SECTION_NAME('T', 'O', 'V', 'L'), eSECTION_MESH = MAKE_SECTION_NAME('M', 'E', 'S', 'H'), eSECTION_SUBMESH = MAKE_SECTION_NAME('S', 'M', 'S', 'H'),
eSECTION_MATERIAL = MAKE_SECTION_NAME('M', 'T', 'R', 'L'), eSECTION_PASS = MAKE_SECTION_NAME('P', 'A', 'S', 'S'), eSECTION_TEXTURE_UNIT = MAKE_SECTION_NAME('U', 'N', 'I', 'T'), eSECTION_RENDER_TARGET = MAKE_SECTION_NAME('R', 'T', 'G', 'R'),
eSECTION_GLSL_SHADER = MAKE_SECTION_NAME('G', 'L', 'S', 'L'), eSECTION_SHADER_PROGRAM = MAKE_SECTION_NAME('S', 'P', 'G', 'M'), eSECTION_SHADER_UBO = MAKE_SECTION_NAME('S', 'U', 'B', 'O'), eSECTION_SHADER_UBO_VARIABLE = MAKE_SECTION_NAME('S', 'U', 'B', 'V'),
eSECTION_BILLBOARD = MAKE_SECTION_NAME('B', 'L', 'B', 'd'), eSECTION_BILLBOARD_LIST = MAKE_SECTION_NAME('B', 'L', 'B', 'L'), eSECTION_ANIMGROUP = MAKE_SECTION_NAME('A', 'N', 'G', 'P'), eSECTION_ANIMATED_OBJECT = MAKE_SECTION_NAME('A', 'N', 'O', 'J'),
eSECTION_ANIMATION = MAKE_SECTION_NAME('A', 'N', 'M', 'T')
}
Scene file sections Enum.
Functions
C3D_API bool operator== (BufferDeclaration &p_lhs, BufferDeclaration &p_rhs)
Equality operator.
C3D_API bool operator!= (BufferDeclaration &p_lhs, BufferDeclaration &p_rhs)
Equality operator.
bool operator== (BufferElementDeclaration const &p_lhs, BufferElementDeclaration const &p_rhs)
Equality operator.
bool operator!= (BufferElementDeclaration const &p_lhs, BufferElementDeclaration const &p_rhs)
Equality operator.
template<typename T >
std::shared_ptr< CleanupEvent< T > > MakeCleanupEvent (T &p_object)
Helper function to create a cleanup event.
std::ostream & operator<< (std::ostream &o, Cone const &c)
Stream operator.
std::ostream & operator<< (std::ostream &o, Cube const &c)
Stream operator.
std::ostream & operator<< (std::ostream &o, Cylinder const &c)
Stream operator.
template<typename Functor >
std::shared_ptr< FunctorEvent< Functor > > MakeFunctorEvent (eEVENT_TYPE p_type, Functor p_functor)
Helper function to create a functor event.
int GetCPUCount ()
std::ostream & operator<< (std::ostream &o, Icosahedron const &c)
Stream operator.
template<typename T >
std::shared_ptr< InitialiseEvent< T > > MakeInitialiseEvent (T &p_object)
Helper function to create an initialise event.
std::ostream & operator<< (std::ostream &o, Plane const &c)
Stream operator.
C3D_API bool operator== (ProgramInputLayout const &p_lhs, ProgramInputLayout const &p_rhs)
Equality operator.
C3D_API bool operator!= (ProgramInputLayout const &p_lhs, ProgramInputLayout const &p_rhs)
Equality operator.
std::ostream & operator<< (std::ostream &o, Projection const &c)
Stream operator.
std::ostream & operator<< (std::ostream &o, Sphere const &c)
Stream operator.
std::ostream & operator<< (std::ostream &p_streamOut, TextureUnitSPtr const &p_texture)
Stream operator.
std::ostream & operator<< (std::ostream &o, Torus const &c)
Stream operator.
C3D_API bool operator== (Castor3D::Version const &p_a, Castor3D::Version const &p_b)
Equality operator.
C3D_API bool operator!= (Castor3D::Version const &p_a, Castor3D::Version const &p_b)
Difference operator.
C3D_API bool operator< (Castor3D::Version const &p_a, Castor3D::Version const &p_b)
Less than operator.
C3D_API bool operator> (Castor3D::Version const &p_a, Castor3D::Version const &p_b)
Less than operator.
C3D_API bool operator<= (Castor3D::Version const &p_a, Castor3D::Version const &p_b)
Less than operator.
C3D_API bool operator>= (Castor3D::Version const &p_a, Castor3D::Version const &p_b)
Less than operator.
C3D_API std::ostream & operator<< (std::ostream &p_stream, Castor3D::Version const &p_version)
C3D_API std::wostream & operator<< (std::wostream &p_stream, Castor3D::Version const &p_version)
C3D_API Castor::String & operator<< (Castor::String &p_stream, Castor3D::Version const &p_version)
Importer
DECLARE_SMART_PTR (Importer)
Camera
DECLARE_SMART_PTR (Camera)
DECLARE_SMART_PTR (Viewport)
DECLARE_SMART_PTR (Ray)
DECLARE_MAP (Castor::String, CameraSPtr, CameraPtrStr)
Camera pointer map, sorted by name.
DECLARE_VECTOR (CameraSPtr, CameraPtr)
Camera pointer array.
Scene
DECLARE_SMART_PTR (SceneNode)
DECLARE_SMART_PTR (Scene)
DECLARE_SMART_PTR (SceneFileContext)
DECLARE_SMART_PTR (SceneFileParser)
DECLARE_VECTOR (SceneNodeSPtr, SceneNodePtr)
SceneNode pointer array.
DECLARE_MAP (Castor::String, SceneSPtr, ScenePtrStr)
Scene pointer map, sorted by name.
DECLARE_MAP (Castor::String, SceneNodeSPtr, SceneNodePtrStr)
SceneNode pointer map, sorted by name.
Variables
static const xchar * INFO_MANAGER_CREATED_OBJECT = cuT("Manager::Create - Created ")
static const xchar * WARNING_MANAGER_DUPLICATE_OBJECT = cuT("Manager::Create - Duplicate ")
static const xchar * WARNING_MANAGER_NULL_OBJECT = cuT("Manager::Insert - nullptr ")
static const uint32_t C3D_MAX_TEXTURE_MATRICES = 10
static const uint32_t C3D_MAX_BONES_PER_VERTEX = 8
General
enum eMOVABLE_TYPE : uint8_t { eMOVABLE_TYPE_CAMERA, eMOVABLE_TYPE_GEOMETRY, eMOVABLE_TYPE_LIGHT, eMOVABLE_TYPE_BILLBOARD }
Movable object types enumerator.
enum eTARGET_TYPE : uint8_t { eTARGET_TYPE_WINDOW, eTARGET_TYPE_TEXTURE }
RenderTarget supported types.
enum ePLUGIN_TYPE : uint8_t {
ePLUGIN_TYPE_RENDERER, ePLUGIN_TYPE_IMPORTER, ePLUGIN_TYPE_DIVIDER, ePLUGIN_TYPE_GENERATOR,
ePLUGIN_TYPE_TECHNIQUE, ePLUGIN_TYPE_POSTFX, ePLUGIN_TYPE_GENERIC
}
Plugin types enumeration.
enum eRENDERER_TYPE : int8_t { eRENDERER_TYPE_UNDEFINED = -1, eRENDERER_TYPE_OPENGL = 0 }
Supported renderers enumeration.
enum eBUFFER_COMPONENT : uint8_t { eBUFFER_COMPONENT_COLOUR = 0x01, eBUFFER_COMPONENT_DEPTH = 0x02, eBUFFER_COMPONENT_STENCIL = 0x04 }
Frame buffer components enumeration.
enum eBUFFER : uint8_t {
eBUFFER_NONE, eBUFFER_FRONT_LEFT, eBUFFER_FRONT_RIGHT, eBUFFER_BACK_LEFT,
eBUFFER_BACK_RIGHT, eBUFFER_FRONT, eBUFFER_BACK, eBUFFER_LEFT,
eBUFFER_RIGHT, eBUFFER_FRONT_AND_BACK
}
Frame buffer components enumeration.
enum eFRAMEBUFFER_TARGET : uint8_t { eFRAMEBUFFER_TARGET_DRAW, eFRAMEBUFFER_TARGET_READ, eFRAMEBUFFER_TARGET_BOTH }
Frame buffer binding targets enumeration.
enum eFRAMEBUFFER_MODE : uint8_t { eFRAMEBUFFER_MODE_CONFIG, eFRAMEBUFFER_MODE_AUTOMATIC, eFRAMEBUFFER_MODE_MANUAL }
Frame buffer binding modes enumeration.
enum eATTACHMENT_POINT : uint8_t { eATTACHMENT_POINT_NONE, eATTACHMENT_POINT_COLOUR, eATTACHMENT_POINT_DEPTH, eATTACHMENT_POINT_STENCIL }
Frame buffer attachment points enumeration.
enum eATTACHMENT_TYPE : uint8_t { eATTACHMENT_TYPE_TEXTURE, eATTACHMENT_TYPE_BUFFER }
Frame buffer attachment types enumeration.
enum eVIEWPORT_TYPE : uint8_t { eVIEWPORT_TYPE_ORTHO, eVIEWPORT_TYPE_PERSPECTIVE, eVIEWPORT_TYPE_FRUSTUM }
The viewport projection types enumeration.
enum eFRUSTUM_PLANE : uint8_t {
eFRUSTUM_PLANE_NEAR, eFRUSTUM_PLANE_FAR, eFRUSTUM_PLANE_LEFT, eFRUSTUM_PLANE_RIGHT,
eFRUSTUM_PLANE_TOP, eFRUSTUM_PLANE_BOTTOM
}
Frustum view planes enumeration.
enum eEVENT_TYPE : uint8_t { eEVENT_TYPE_PRE_RENDER, eEVENT_TYPE_POST_RENDER }
Frame Event Type enumeration.
enum eFACE : uint8_t { eFACE_NONE, eFACE_FRONT, eFACE_BACK, eFACE_FRONT_AND_BACK }
Faces orientations enumeration.
enum eFILL_MODE : uint8_t { eFILL_MODE_POINT, eFILL_MODE_LINE, eFILL_MODE_SOLID }
Polygon rasterisation modes enumeration.
enum eQUERY_TYPE : uint32_t {
eQUERY_TYPE_TIME_ELAPSED, eQUERY_TYPE_SAMPLES_PASSED, eQUERY_TYPE_ANY_SAMPLES_PASSED, eQUERY_TYPE_PRIMITIVES_GENERATED,
eQUERY_TYPE_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN, eQUERY_TYPE_ANY_SAMPLES_PASSED_CONSERVATIVE, eQUERY_TYPE_TIMESTAMP
}
GPU query supported types enumeration.
enum eQUERY_INFO : uint32_t { eQUERY_INFO_RESULT, eQUERY_INFO_RESULT_AVAILABLE, eQUERY_INFO_RESULT_NO_WAIT }
GPU query supported informations enumeration.
typedef enum Castor3D::eMOVABLE_TYPE eMOVABLE_TYPE
Movable object types enumerator.
typedef enum Castor3D::eTARGET_TYPE eTARGET_TYPE
RenderTarget supported types.
typedef enum Castor3D::ePLUGIN_TYPE ePLUGIN_TYPE
Plugin types enumeration.
typedef enum Castor3D::eRENDERER_TYPE eRENDERER_TYPE
Supported renderers enumeration.
typedef enum Castor3D::eBUFFER_COMPONENT eBUFFER_COMPONENT
Frame buffer components enumeration.
typedef enum Castor3D::eBUFFER eBUFFER
Frame buffer components enumeration.
typedef enum Castor3D::eFRAMEBUFFER_TARGET eFRAMEBUFFER_TARGET
Frame buffer binding targets enumeration.
typedef enum Castor3D::eFRAMEBUFFER_MODE eFRAMEBUFFER_MODE
Frame buffer binding modes enumeration.
typedef enum Castor3D::eATTACHMENT_POINT eATTACHMENT_POINT
Frame buffer attachment points enumeration.
typedef enum Castor3D::eATTACHMENT_TYPE eATTACHMENT_TYPE
Frame buffer attachment types enumeration.
typedef enum Castor3D::eVIEWPORT_TYPE eVIEWPORT_TYPE
The viewport projection types enumeration.
typedef enum Castor3D::eFRUSTUM_PLANE eFRUSTUM_PLANE
Frustum view planes enumeration.
typedef enum Castor3D::eEVENT_TYPE eEVENT_TYPE
Frame Event Type enumeration.
typedef enum Castor3D::eFACE eFACE
Faces orientations enumeration.
typedef enum Castor3D::eFILL_MODE eFILL_MODE
Polygon rasterisation modes enumeration.
typedef enum Castor3D::eQUERY_TYPE eQUERY_TYPE
GPU query supported types enumeration.
typedef enum Castor3D::eQUERY_INFO eQUERY_INFO
GPU query supported informations enumeration.
typedef std::map< Castor::String, RenderWindowSPtr > WindowPtrStrMap
DECLARE_SMART_PTR (RenderWindow)
DECLARE_SMART_PTR (RenderTarget)
DECLARE_SMART_PTR (RenderBuffer)
DECLARE_SMART_PTR (ColourRenderBuffer)
DECLARE_SMART_PTR (DepthStencilRenderBuffer)
DECLARE_SMART_PTR (FrameBufferAttachment)
DECLARE_SMART_PTR (RenderBufferAttachment)
DECLARE_SMART_PTR (TextureAttachment)
DECLARE_SMART_PTR (FrameBuffer)
DECLARE_SMART_PTR (BackBuffers)
DECLARE_SMART_PTR (RenderTechnique)
DECLARE_SMART_PTR (PostEffect)
DECLARE_SMART_PTR (Engine)
DECLARE_SMART_PTR (RendererServer)
DECLARE_SMART_PTR (PluginBase)
DECLARE_SMART_PTR (RendererPlugin)
DECLARE_SMART_PTR (ImporterPlugin)
DECLARE_SMART_PTR (DividerPlugin)
DECLARE_SMART_PTR (GenericPlugin)
DECLARE_SMART_PTR (PostFxPlugin)
DECLARE_SMART_PTR (FrameEvent)
DECLARE_SMART_PTR (FrameListener)
DECLARE_SMART_PTR (IWindowHandle)
DECLARE_SMART_PTR (BillboardList)
DECLARE_SMART_PTR (RenderLoop)
DECLARE_SMART_PTR (GpuQuery)
DECLARE_SMART_PTR (OverlayManager)
DECLARE_SMART_PTR (ShaderManager)
DECLARE_SMART_PTR (MaterialManager)
DECLARE_SMART_PTR (WindowManager)
DECLARE_SMART_PTR (MeshManager)
DECLARE_SMART_PTR (PluginManager)
DECLARE_SMART_PTR (SceneManager)
DECLARE_SMART_PTR (SamplerManager)
DECLARE_SMART_PTR (DepthStencilStateManager)
DECLARE_SMART_PTR (RasteriserStateManager)
DECLARE_SMART_PTR (BlendStateManager)
DECLARE_SMART_PTR (AnimationManager)
DECLARE_SMART_PTR (TargetManager)
DECLARE_SMART_PTR (ListenerManager)
DECLARE_SMART_PTR (GeometryManager)
DECLARE_SMART_PTR (CameraManager)
DECLARE_SMART_PTR (LightManager)
DECLARE_SMART_PTR (AnimatedObjectGroupManager)
DECLARE_SMART_PTR (SceneNodeManager)
DECLARE_SMART_PTR (BillboardManager)
DECLARE_SMART_PTR (RenderTechniqueManager)
DECLARE_SMART_PTR (TechniqueFactory)
DECLARE_VECTOR (real, Real)
real array
DECLARE_VECTOR (RenderWindowSPtr, RenderWindowPtr)
RenderWindow pointer array.
DECLARE_VECTOR (RenderBufferSPtr, RenderBufferPtr)
RenderBuffer pointer array.
DECLARE_VECTOR (FrameEventSPtr, FrameEventPtr)
FrameEvent pointer array.
DECLARE_MAP (Castor::String, FrameListenerSPtr, FrameListenerPtrStr)
FrameListener pointer map, sorted by name.
DECLARE_MAP (uint32_t, RenderWindowSPtr, RenderWindow)
RenderWindow pointer map, sorted by index.
DECLARE_MAP (Castor::String, PluginBaseSPtr, PluginStr)
Plugin map, sorted by name.
DECLARE_MAP (int, Castor::String, StrInt)
DECLARE_VECTOR (PostEffectSPtr, PostEffectPtr)
DECLARE_VECTOR (BillboardListSPtr, BillboardList)
DECLARE_ARRAY (RendererPluginSPtr, eRENDERER_TYPE_COUNT, RendererPtr)
DECLARE_ARRAY (PluginStrMap, ePLUGIN_TYPE_COUNT, PluginStrMap)
DECLARE_MAP (Castor::Path, Castor::DynamicLibrarySPtr, DynamicLibraryPtrPath)
DECLARE_ARRAY (DynamicLibraryPtrPathMap, ePLUGIN_TYPE_COUNT, DynamicLibraryPtrPathMap)
DECLARE_MAP (Castor::Path, ePLUGIN_TYPE, PluginTypePath)
DECLARE_MAP (Castor::String, BillboardListSPtr, BillboardListStr)
Animation
enum eINTERPOLATOR_MODE { eINTERPOLATOR_MODE_NONE, eINTERPOLATOR_MODE_LINEAR }
Interpolation modes enumeration.
enum eANIMATION_STATE : uint8_t { eANIMATION_STATE_PLAYING, eANIMATION_STATE_STOPPED, eANIMATION_STATE_PAUSED }
Animation State Enumerator.
enum eANIMATION_OBJECT_TYPE : uint8_t { eANIMATION_OBJECT_TYPE_NODE, eANIMATION_OBJECT_TYPE_OBJECT, eANIMATION_OBJECT_TYPE_BONE }
Class which represents the moving things.
typedef enum Castor3D::eINTERPOLATOR_MODE eINTERPOLATOR_MODE
Interpolation modes enumeration.
typedef enum Castor3D::eANIMATION_STATE eANIMATION_STATE
Animation State Enumerator.
typedef enum Castor3D::eANIMATION_OBJECT_TYPE eANIMATION_OBJECT_TYPE
Class which represents the moving things.
using AnimationStateMap = std::map< Castor::String, eANIMATION_STATE >
using Point3rInterpolator = Interpolator< Castor::Point3r >
using QuaternionInterpolator = Interpolator< Castor::Quaternion >
using KeyFrameRealMap = std::map< real, KeyFrame >
using KeyFrameArray = std::vector< KeyFrame >
DECLARE_SMART_PTR (AnimatedObject)
DECLARE_SMART_PTR (AnimationObject)
DECLARE_SMART_PTR (SkeletonAnimationObject)
DECLARE_SMART_PTR (SkeletonAnimationBone)
DECLARE_SMART_PTR (SkeletonAnimationNode)
DECLARE_SMART_PTR (Animation)
DECLARE_SMART_PTR (AnimatedObjectGroup)
DECLARE_SMART_PTR (Bone)
DECLARE_SMART_PTR (Skeleton)
DECLARE_SMART_PTR (Animable)
DECLARE_SMART_PTR (BonedVertex)
DECLARE_MAP (Castor::String, AnimatedObjectGroupSPtr, AnimatedObjectGroupPtrStr)
AnimatedObjectGroup pointer map, sorted by name.
DECLARE_MAP (Castor::String, AnimationSPtr, AnimationPtrStr)
Animation pointer map, sorted by name.
DECLARE_MAP (Castor::String, AnimatedObjectSPtr, AnimatedObjectPtrStr)
AnimatedObject pointer map, sorted by name.
DECLARE_MAP (Castor::String, AnimationObjectSPtr, AnimationObjectPtrStr)
MovingObject pointer map, sorted by name.
DECLARE_VECTOR (AnimationSPtr, AnimationPtr)
Animation pointer array.
DECLARE_VECTOR (BoneSPtr, BonePtr)
Bone pointer array.
DECLARE_VECTOR (AnimationObjectSPtr, AnimationObjectPtr)
AnimationObject pointer array.
DECLARE_VECTOR (BonedVertexSPtr, BonedVertexPtr)
BonedVertex pointer array.
Geometry
enum eMESH_TYPE : uint8_t {
eMESH_TYPE_CUSTOM, eMESH_TYPE_CONE, eMESH_TYPE_CYLINDER, eMESH_TYPE_SPHERE,
eMESH_TYPE_CUBE, eMESH_TYPE_TORUS, eMESH_TYPE_PLANE, eMESH_TYPE_ICOSAHEDRON,
eMESH_TYPE_PROJECTION
}
Mesh type enumeration.
enum eNORMAL : uint8_t { eNORMAL_FLAT, eNORMAL_SMOOTH }
Enumerates supported normal generation.
typedef enum Castor3D::eMESH_TYPE eMESH_TYPE
Mesh type enumeration.
typedef enum Castor3D::eNORMAL eNORMAL
Enumerates supported normal generation.
typedef Pattern< Vertex > VertexPattern
typedef Pattern< Castor::Point3r > Point3rPattern
typedef Pattern< VertexSPtr > VertexPtrPattern
typedef Pattern< Castor::Point3rSPtr > Point3rPtrPattern
DECLARE_SMART_PTR (Vertex)
DECLARE_SMART_PTR (BufferElementGroup)
DECLARE_SMART_PTR (VertexPattern)
DECLARE_SMART_PTR (Point3rPattern)
DECLARE_SMART_PTR (VertexPtrPattern)
DECLARE_SMART_PTR (Face)
DECLARE_SMART_PTR (Graph)
DECLARE_SMART_PTR (Mesh)
DECLARE_SMART_PTR (MeshGenerator)
DECLARE_SMART_PTR (Submesh)
DECLARE_SMART_PTR (Cone)
DECLARE_SMART_PTR (Cylinder)
DECLARE_SMART_PTR (Icosahedron)
DECLARE_SMART_PTR (Cube)
DECLARE_SMART_PTR (Plane)
DECLARE_SMART_PTR (Projection)
DECLARE_SMART_PTR (Sphere)
DECLARE_SMART_PTR (Torus)
DECLARE_SMART_PTR (Geometry)
DECLARE_SMART_PTR (MovableObject)
DECLARE_SMART_PTR (Subdivider)
DECLARE_SMART_PTR (FaceGroup)
DECLARE_SMART_PTR (MeshFactory)
DECLARE_VECTOR (Vertex, Vertex)
Vertex array.
DECLARE_VECTOR (BufferElementGroupSPtr, VertexPtr)
Vertex pointer array.
DECLARE_VECTOR (Face, Face)
Face array.
DECLARE_VECTOR (FaceSPtr, FacePtr)
Face pointer array.
DECLARE_VECTOR (FaceGroupSPtr, FaceGroupPtr)
FaceGroup pointer array.
DECLARE_VECTOR (SubmeshSPtr, SubmeshPtr)
Submesh pointer array.
DECLARE_VECTOR (GeometrySPtr, GeometryPtr)
Geometry pointer array.
DECLARE_LIST (VertexSPtr, VertexPtr)
Vertex pointer list.
DECLARE_MAP (Castor::String, MeshSPtr, MeshPtrStr)
Mesh pointer array.
DECLARE_MAP (Castor::String, MovableObjectSPtr, MovableObjectPtrStr)
MovableObject pointer map, sorted by name.
DECLARE_MAP (Castor::String, GeometrySPtr, GeometryPtrStr)
Geometry pointer map, sorted by name.
DECLARE_MAP (uint32_t, int, IntUInt)
DECLARE_MAP (Castor::String, SubmeshSPtr, SubmeshPtrStr)
DECLARE_MAP (Castor::String, int, IntStr)
Light
enum eLIGHT_TYPE : uint8_t { eLIGHT_TYPE_DIRECTIONAL, eLIGHT_TYPE_POINT, eLIGHT_TYPE_SPOT }
Light types enumeration.
typedef enum Castor3D::eLIGHT_TYPE eLIGHT_TYPE
Light types enumeration.
DECLARE_SMART_PTR (Light)
DECLARE_SMART_PTR (LightCategory)
DECLARE_SMART_PTR (DirectionalLight)
DECLARE_SMART_PTR (PointLight)
DECLARE_SMART_PTR (SpotLight)
DECLARE_SMART_PTR (LightFactory)
DECLARE_VECTOR (LightSPtr, LightPtr)
Array of lights.
DECLARE_MAP (Castor::String, LightSPtr, LightPtrStr)
Map of lights, sorted by name.
DECLARE_MAP (int, LightSPtr, LightPtrInt)
Map of lights, sorted by index.
Material
enum eTEXTURE_MAP_MODE : uint8_t { eTEXTURE_MAP_MODE_NONE, eTEXTURE_MAP_MODE_REFLECTION, eTEXTURE_MAP_MODE_SPHERE }
Texture mapping modes enumeration.
enum eALPHA_FUNC : uint8_t {
eALPHA_FUNC_ALWAYS, eALPHA_FUNC_LESS, eALPHA_FUNC_LESS_OR_EQUAL, eALPHA_FUNC_EQUAL,
eALPHA_FUNC_NOT_EQUAL, eALPHA_FUNC_GREATER_OR_EQUAL, eALPHA_FUNC_GREATER, eALPHA_FUNC_NEVER
}
Alpha functions enumeration.
enum eTEXTURE_UVW : uint8_t { eTEXTURE_UVW_U, eTEXTURE_UVW_V, eTEXTURE_UVW_W }
Texture UVW enumeration.
enum eWRAP_MODE : uint8_t { eWRAP_MODE_REPEAT, eWRAP_MODE_MIRRORED_REPEAT, eWRAP_MODE_CLAMP_TO_BORDER, eWRAP_MODE_CLAMP_TO_EDGE }
Texture wrap modes enumeration.
enum eINTERPOLATION_FILTER : uint8_t { eINTERPOLATION_FILTER_MIN, eINTERPOLATION_FILTER_MAG, eINTERPOLATION_FILTER_MIP, eINTERPOLATION_FILTER_COUNT }
Texture interpolation filters enumeration.
enum eINTERPOLATION_MODE : uint8_t { eINTERPOLATION_MODE_UNDEFINED, eINTERPOLATION_MODE_NEAREST, eINTERPOLATION_MODE_LINEAR }
Texture filter interpolation modes enumeration.
enum eBLEND_SRC_INDEX : uint8_t { eBLEND_SRC_INDEX_0, eBLEND_SRC_INDEX_1, eBLEND_SRC_INDEX_2 }
Texture blending source indices enumeration.
enum eBLEND_SOURCE : uint8_t {
eBLEND_SOURCE_TEXTURE, eBLEND_SOURCE_TEXTURE0, eBLEND_SOURCE_TEXTURE1, eBLEND_SOURCE_TEXTURE2,
eBLEND_SOURCE_TEXTURE3, eBLEND_SOURCE_CONSTANT, eBLEND_SOURCE_DIFFUSE, eBLEND_SOURCE_PREVIOUS
}
Texture blending sources enumeration.
enum eRGB_BLEND_FUNC : uint8_t {
eRGB_BLEND_FUNC_NONE, eRGB_BLEND_FUNC_FIRST_ARG, eRGB_BLEND_FUNC_ADD, eRGB_BLEND_FUNC_ADD_SIGNED,
eRGB_BLEND_FUNC_MODULATE, eRGB_BLEND_FUNC_INTERPOLATE, eRGB_BLEND_FUNC_SUBTRACT, eRGB_BLEND_FUNC_DOT3_RGB,
eRGB_BLEND_FUNC_DOT3_RGBA
}
RGB blending functions enumeration.
enum eALPHA_BLEND_FUNC : uint8_t {
eALPHA_BLEND_FUNC_NONE, eALPHA_BLEND_FUNC_FIRST_ARG, eALPHA_BLEND_FUNC_ADD, eALPHA_BLEND_FUNC_ADD_SIGNED,
eALPHA_BLEND_FUNC_MODULATE, eALPHA_BLEND_FUNC_INTERPOLATE, eALPHA_BLEND_FUNC_SUBSTRACT
}
Alpha blending functions enumeration.
enum eBLEND_OP : uint8_t {
eBLEND_OP_ADD, eBLEND_OP_SUBSTRACT, eBLEND_OP_REV_SUBSTRACT, eBLEND_OP_MIN,
eBLEND_OP_MAX, eBLEND_OP_COUNT
}
Blending operations enumeration.
enum eBLEND_MODE : uint8_t {
eBLEND_MODE_NONE, eBLEND_MODE_ADDITIVE, eBLEND_MODE_MULTIPLICATIVE, eBLEND_MODE_INTERPOLATIVE,
eBLEND_MODE_A_BUFFER, eBLEND_MODE_DEPTH_PEELING
}
Blending modes enumeration.
enum eTEXTURE_TYPE : uint8_t {
eTEXTURE_TYPE_BUFFER, eTEXTURE_TYPE_1D, eTEXTURE_TYPE_1DARRAY, eTEXTURE_TYPE_2D,
eTEXTURE_TYPE_2DARRAY, eTEXTURE_TYPE_2DMS, eTEXTURE_TYPE_2DMSARRAY, eTEXTURE_TYPE_3D,
eTEXTURE_TYPE_CUBE, eTEXTURE_TYPE_CUBEARRAY
}
Texture dimensions enumeration.
enum eTEXTURE_TARGET : uint8_t { eTEXTURE_TARGET_1D, eTEXTURE_TARGET_2D, eTEXTURE_TARGET_3D, eTEXTURE_TARGET_LAYER }
Texture targets enumeration.
enum eTEXTURE_BASE_TYPE : uint8_t { eTEXTURE_BASE_TYPE_STATIC, eTEXTURE_BASE_TYPE_DYNAMIC }
Texture types enumeration.
enum eBLEND : uint8_t {
eBLEND_ZERO, eBLEND_ONE, eBLEND_SRC_COLOUR, eBLEND_INV_SRC_COLOUR,
eBLEND_DST_COLOUR, eBLEND_INV_DST_COLOUR, eBLEND_SRC_ALPHA, eBLEND_INV_SRC_ALPHA,
eBLEND_DST_ALPHA, eBLEND_INV_DST_ALPHA, eBLEND_CONSTANT, eBLEND_INV_CONSTANT,
eBLEND_SRC_ALPHA_SATURATE, eBLEND_SRC1_COLOUR, eBLEND_INV_SRC1_COLOUR, eBLEND_SRC1_ALPHA,
eBLEND_INV_SRC1_ALPHA
}
Blend operators enumeration.
enum eTEXTURE_CHANNEL : uint32_t {
eTEXTURE_CHANNEL_COLOUR = 0x00000001, eTEXTURE_CHANNEL_DIFFUSE = 0x00000002, eTEXTURE_CHANNEL_NORMAL = 0x00000004, eTEXTURE_CHANNEL_OPACITY = 0x00000008,
eTEXTURE_CHANNEL_SPECULAR = 0x00000010, eTEXTURE_CHANNEL_HEIGHT = 0x00000020, eTEXTURE_CHANNEL_AMBIENT = 0x00000040, eTEXTURE_CHANNEL_GLOSS = 0x00000080,
eTEXTURE_CHANNEL_EMISSIVE = 0x00000100, eTEXTURE_CHANNEL_ALL = 0x0000FFFF, eTEXTURE_CHANNEL_TEXT = 0x00010000
}
Texture channels enumeration.
typedef enum Castor3D::eTEXTURE_MAP_MODE eTEXTURE_MAP_MODE
Texture mapping modes enumeration.
typedef enum Castor3D::eALPHA_FUNC eALPHA_FUNC
Alpha functions enumeration.
typedef enum Castor3D::eTEXTURE_UVW eTEXTURE_UVW
Texture UVW enumeration.
typedef enum Castor3D::eWRAP_MODE eWRAP_MODE
Texture wrap modes enumeration.
typedef enum Castor3D::eINTERPOLATION_FILTER eINTERPOLATION_FILTER
Texture interpolation filters enumeration.
typedef enum Castor3D::eINTERPOLATION_MODE eINTERPOLATION_MODE
Texture filter interpolation modes enumeration.
typedef enum Castor3D::eBLEND_SRC_INDEX eBLEND_SRC_INDEX
Texture blending source indices enumeration.
typedef enum Castor3D::eBLEND_SOURCE eBLEND_SOURCE
Texture blending sources enumeration.
typedef enum Castor3D::eRGB_BLEND_FUNC eRGB_BLEND_FUNC
RGB blending functions enumeration.
typedef enum Castor3D::eALPHA_BLEND_FUNC eALPHA_BLEND_FUNC
Alpha blending functions enumeration.
typedef enum Castor3D::eBLEND_OP eBLEND_OP
Blending operations enumeration.
typedef enum Castor3D::eBLEND_MODE eBLEND_MODE
Blending modes enumeration.
typedef enum Castor3D::eTEXTURE_TYPE eTEXTURE_TYPE
Texture dimensions enumeration.
typedef enum Castor3D::eTEXTURE_TARGET eTEXTURE_TARGET
Texture targets enumeration.
typedef enum Castor3D::eTEXTURE_BASE_TYPE eTEXTURE_BASE_TYPE
Texture types enumeration.
typedef enum Castor3D::eBLEND eBLEND
Blend operators enumeration.
typedef enum Castor3D::eTEXTURE_CHANNEL eTEXTURE_CHANNEL
Texture channels enumeration.
DECLARE_SMART_PTR (Texture)
DECLARE_SMART_PTR (StaticTexture)
DECLARE_SMART_PTR (DynamicTexture)
DECLARE_SMART_PTR (TextureUnit)
DECLARE_SMART_PTR (Material)
DECLARE_SMART_PTR (Pass)
DECLARE_SMART_PTR (Sampler)
DECLARE_VECTOR (MaterialSPtr, MaterialPtr)
Material pointer array.
DECLARE_VECTOR (TextureUnit, TextureUnit)
TextureUnit array.
DECLARE_VECTOR (TextureUnitSPtr, TextureUnitPtr)
TextureUnit pointer array.
DECLARE_VECTOR (Pass, Pass)
Pass array.
DECLARE_VECTOR (PassSPtr, PassPtr)
Pass pointer array.
DECLARE_VECTOR (uint32_t, UInt)
uint32_t array
DECLARE_MAP (Castor::String, MaterialSPtr, MaterialPtrStr)
Material pointer map, sorted by name.
DECLARE_MAP (uint32_t, MaterialSPtr, MaterialPtrUInt)
Material pointer map.
Overlay
enum eOVERLAY_TYPE : uint8_t { eOVERLAY_TYPE_PANEL, eOVERLAY_TYPE_BORDER_PANEL, eOVERLAY_TYPE_TEXT }
Overlay types enumeration.
enum eTEXT_WRAPPING_MODE { eTEXT_WRAPPING_MODE_NONE, eTEXT_WRAPPING_MODE_BREAK, eTEXT_WRAPPING_MODE_BREAK_WORDS }
Text wrapping modes, handles the way text is cut when it overflows the overlay width.
enum eTEXT_TEXTURING_MODE { eTEXT_TEXTURING_MODE_LETTER, eTEXT_TEXTURING_MODE_TEXT }
Text texturing modes, handles the way textures are appied to text overlays.
enum eHALIGN { eHALIGN_LEFT, eHALIGN_CENTER, eHALIGN_RIGHT }
Horizontal alignments for text overlays.
enum eVALIGN { eVALIGN_TOP, eVALIGN_CENTER, eVALIGN_BOTTOM }
Vertical alignments for text overlays.
enum eBORDER_POSITION { eBORDER_POSITION_INTERNAL, eBORDER_POSITION_MIDDLE, eBORDER_POSITION_EXTERNAL }
Text wrapping modes, handles the way text is cut when it overflows the overlay width.
typedef enum Castor3D::eOVERLAY_TYPE eOVERLAY_TYPE
Overlay types enumeration.
typedef enum Castor3D::eTEXT_WRAPPING_MODE eTEXT_WRAPPING_MODE
Text wrapping modes, handles the way text is cut when it overflows the overlay width.
typedef enum Castor3D::eTEXT_TEXTURING_MODE eTEXT_TEXTURING_MODE
Text texturing modes, handles the way textures are appied to text overlays.
typedef enum Castor3D::eHALIGN eHALIGN
Horizontal alignments for text overlays.
typedef enum Castor3D::eVALIGN eVALIGN
Vertical alignments for text overlays.
typedef enum Castor3D::eBORDER_POSITION eBORDER_POSITION
Text wrapping modes, handles the way text is cut when it overflows the overlay width.
DECLARE_SMART_PTR (OverlayFactory)
DECLARE_SMART_PTR (OverlayRenderer)
DECLARE_SMART_PTR (FontTexture)
DECLARE_SMART_PTR (Overlay)
DECLARE_SMART_PTR (OverlayCategory)
DECLARE_SMART_PTR (PanelOverlay)
DECLARE_SMART_PTR (BorderPanelOverlay)
DECLARE_SMART_PTR (TextOverlay)
DECLARE_VECTOR (OverlaySPtr, OverlayPtr)
DECLARE_MAP (Castor::String, OverlaySPtr, OverlayPtrStr)
Render
enum eMTXMODE : uint8_t {
eMTXMODE_PROJECTION, eMTXMODE_MODEL, eMTXMODE_VIEW, eMTXMODE_TEXTURE0,
eMTXMODE_TEXTURE1, eMTXMODE_TEXTURE2, eMTXMODE_TEXTURE3, eMTXMODE_TEXTURE4,
eMTXMODE_TEXTURE5, eMTXMODE_TEXTURE6, eMTXMODE_TEXTURE7, eMTXMODE_TEXTURE8,
eMTXMODE_TEXTURE9, eMTXMODE_TEXTURE10, eMTXMODE_TEXTURE11, eMTXMODE_TEXTURE12,
eMTXMODE_TEXTURE13, eMTXMODE_TEXTURE14, eMTXMODE_TEXTURE15, eMTXMODE_TEXTURE16,
eMTXMODE_TEXTURE17, eMTXMODE_TEXTURE18, eMTXMODE_TEXTURE19, eMTXMODE_TEXTURE20,
eMTXMODE_TEXTURE21, eMTXMODE_TEXTURE22, eMTXMODE_TEXTURE23, eMTXMODE_TEXTURE24,
eMTXMODE_TEXTURE25, eMTXMODE_TEXTURE26, eMTXMODE_TEXTURE27, eMTXMODE_TEXTURE28,
eMTXMODE_TEXTURE29, eMTXMODE_TEXTURE30, eMTXMODE_TEXTURE31
}
Matrix modes enumeration.
enum eACCESS_TYPE : uint8_t { eACCESS_TYPE_READ = 1 << 0, eACCESS_TYPE_WRITE = 1 << 1 }
Access types enumeration.
enum eBUFFER_ACCESS_TYPE : uint32_t { eBUFFER_ACCESS_TYPE_STATIC = 1 << 0, eBUFFER_ACCESS_TYPE_DYNAMIC = 1 << 1, eBUFFER_ACCESS_TYPE_STREAM = 1 << 2 }
Buffer access types enumeration.
enum eBUFFER_ACCESS_NATURE : uint32_t { eBUFFER_ACCESS_NATURE_DRAW = 1 << 4, eBUFFER_ACCESS_NATURE_READ = 1 << 5, eBUFFER_ACCESS_NATURE_COPY = 1 << 6 }
Buffer access natures enumeration.
enum eTOPOLOGY : uint8_t {
eTOPOLOGY_POINTS, eTOPOLOGY_LINES, eTOPOLOGY_LINE_LOOP, eTOPOLOGY_LINE_STRIP,
eTOPOLOGY_TRIANGLES, eTOPOLOGY_TRIANGLE_STRIPS, eTOPOLOGY_TRIANGLE_FAN, eTOPOLOGY_QUADS,
eTOPOLOGY_QUAD_STRIPS, eTOPOLOGY_POLYGON
}
Primitive draw types enumeration.
enum eDEPTH_FUNC : uint8_t {
eDEPTH_FUNC_NEVER, eDEPTH_FUNC_LESS, eDEPTH_FUNC_EQUAL, eDEPTH_FUNC_LEQUAL,
eDEPTH_FUNC_GREATER, eDEPTH_FUNC_NOTEQUAL, eDEPTH_FUNC_GEQUAL, eDEPTH_FUNC_ALWAYS
}
Depth functions enumeration.
enum eWRITING_MASK : uint8_t { eWRITING_MASK_ZERO, eWRITING_MASK_ALL }
Wrinting masks enumeration.
enum eSTENCIL_FUNC : uint8_t {
eSTENCIL_FUNC_NEVER, eSTENCIL_FUNC_LESS, eSTENCIL_FUNC_EQUAL, eSTENCIL_FUNC_LEQUAL,
eSTENCIL_FUNC_GREATER, eSTENCIL_FUNC_NOTEQUAL, eSTENCIL_FUNC_GEQUAL, eSTENCIL_FUNC_ALWAYS
}
Stencil functions enumeration.
enum eSTENCIL_OP : uint8_t {
eSTENCIL_OP_KEEP, eSTENCIL_OP_ZERO, eSTENCIL_OP_REPLACE, eSTENCIL_OP_INCR,
eSTENCIL_OP_INCR_WRAP, eSTENCIL_OP_DECR, eSTENCIL_OP_DECR_WRAP, eSTENCIL_OP_INVERT
}
Stencil functions enumeration.
enum eELEMENT_USAGE : uint32_t {
eELEMENT_USAGE_UNKNOWN = 0x000, eELEMENT_USAGE_POSITION = 0x001, eELEMENT_USAGE_NORMAL = 0x002, eELEMENT_USAGE_TANGENT = 0x004,
eELEMENT_USAGE_BITANGENT = 0x008, eELEMENT_USAGE_DIFFUSE = 0x010, eELEMENT_USAGE_TEXCOORDS = 0x020, eELEMENT_USAGE_BONE_IDS0 = 0x040,
eELEMENT_USAGE_BONE_IDS1 = 0x080, eELEMENT_USAGE_BONE_WEIGHTS0 = 0x100, eELEMENT_USAGE_BONE_WEIGHTS1 = 0x200, eELEMENT_USAGE_TRANSFORM = 0x400
}
Element usage enumeration.
enum eELEMENT_TYPE : uint8_t {
eELEMENT_TYPE_1FLOAT, eELEMENT_TYPE_2FLOATS, eELEMENT_TYPE_3FLOATS, eELEMENT_TYPE_4FLOATS,
eELEMENT_TYPE_COLOUR, eELEMENT_TYPE_1INT, eELEMENT_TYPE_2INTS, eELEMENT_TYPE_3INTS,
eELEMENT_TYPE_4INTS, eELEMENT_TYPE_2x2FLOATS, eELEMENT_TYPE_3x3FLOATS, eELEMENT_TYPE_4x4FLOATS
}
Element type enumeration.
enum eTONE_MAPPING_TYPE : uint8_t {
eTONE_MAPPING_TYPE_LINEAR, eTONE_MAPPING_TYPE_REINHARD, eTONE_MAPPING_TYPE_HAARM_PETER_DUIKER, eTONE_MAPPING_TYPE_HEJL_BURGESS_DAWSON,
eTONE_MAPPING_TYPE_HABLE
}
Tone mapping type enumeration.
typedef enum Castor3D::eMTXMODE eMTXMODE
Matrix modes enumeration.
typedef enum Castor3D::eACCESS_TYPE eACCESS_TYPE
Access types enumeration.
typedef enum Castor3D::eBUFFER_ACCESS_TYPE eBUFFER_ACCESS_TYPE
Buffer access types enumeration.
typedef enum Castor3D::eBUFFER_ACCESS_NATURE eBUFFER_ACCESS_NATURE
Buffer access natures enumeration.
typedef enum Castor3D::eTOPOLOGY eTOPOLOGY
Primitive draw types enumeration.
typedef enum Castor3D::eDEPTH_FUNC eDEPTH_FUNC
Depth functions enumeration.
typedef enum Castor3D::eWRITING_MASK eWRITING_MASK
Wrinting masks enumeration.
typedef enum Castor3D::eSTENCIL_FUNC eSTENCIL_FUNC
Stencil functions enumeration.
typedef enum Castor3D::eSTENCIL_OP eSTENCIL_OP
Stencil functions enumeration.
typedef enum Castor3D::eELEMENT_USAGE eELEMENT_USAGE
Element usage enumeration.
typedef enum Castor3D::eELEMENT_TYPE eELEMENT_TYPE
Element type enumeration.
typedef enum Castor3D::eTONE_MAPPING_TYPE eTONE_MAPPING_TYPE
Tone mapping type enumeration.
using SubmeshRenderNodesByPassMap = TypeRenderNodesByPassMap< SubmeshRenderNodesMap >
using BillboardRenderNodesByPassMap = TypeRenderNodesByPassMap< BillboardRenderNodesMap >
static const uint64_t MASK_MTXMODE_PROJECTION = uint64_t(0x1) << eMTXMODE_PROJECTION
Matrix modes masks.
static const uint64_t MASK_MTXMODE_MODEL = uint64_t(0x1) << eMTXMODE_MODEL
static const uint64_t MASK_MTXMODE_VIEW = uint64_t(0x1) << eMTXMODE_VIEW
static const uint64_t MASK_MTXMODE_TEXTURE0 = uint64_t(0x1) << eMTXMODE_TEXTURE0
static const uint64_t MASK_MTXMODE_TEXTURE1 = uint64_t(0x1) << eMTXMODE_TEXTURE1
static const uint64_t MASK_MTXMODE_TEXTURE2 = uint64_t(0x1) << eMTXMODE_TEXTURE2
static const uint64_t MASK_MTXMODE_TEXTURE3 = uint64_t(0x1) << eMTXMODE_TEXTURE3
static const uint64_t MASK_MTXMODE_TEXTURE4 = uint64_t(0x1) << eMTXMODE_TEXTURE4
static const uint64_t MASK_MTXMODE_TEXTURE5 = uint64_t(0x1) << eMTXMODE_TEXTURE5
static const uint64_t MASK_MTXMODE_TEXTURE6 = uint64_t(0x1) << eMTXMODE_TEXTURE6
static const uint64_t MASK_MTXMODE_TEXTURE7 = uint64_t(0x1) << eMTXMODE_TEXTURE7
static const uint64_t MASK_MTXMODE_TEXTURE8 = uint64_t(0x1) << eMTXMODE_TEXTURE8
static const uint64_t MASK_MTXMODE_TEXTURE9 = uint64_t(0x1) << eMTXMODE_TEXTURE9
static const uint64_t MASK_MTXMODE_TEXTURE10 = uint64_t(0x1) << eMTXMODE_TEXTURE10
static const uint64_t MASK_MTXMODE_TEXTURE11 = uint64_t(0x1) << eMTXMODE_TEXTURE11
static const uint64_t MASK_MTXMODE_TEXTURE12 = uint64_t(0x1) << eMTXMODE_TEXTURE12
static const uint64_t MASK_MTXMODE_TEXTURE13 = uint64_t(0x1) << eMTXMODE_TEXTURE13
static const uint64_t MASK_MTXMODE_TEXTURE14 = uint64_t(0x1) << eMTXMODE_TEXTURE14
static const uint64_t MASK_MTXMODE_TEXTURE15 = uint64_t(0x1) << eMTXMODE_TEXTURE15
static const uint64_t MASK_MTXMODE_TEXTURE16 = uint64_t(0x1) << eMTXMODE_TEXTURE16
static const uint64_t MASK_MTXMODE_TEXTURE17 = uint64_t(0x1) << eMTXMODE_TEXTURE17
static const uint64_t MASK_MTXMODE_TEXTURE18 = uint64_t(0x1) << eMTXMODE_TEXTURE18
static const uint64_t MASK_MTXMODE_TEXTURE19 = uint64_t(0x1) << eMTXMODE_TEXTURE19
static const uint64_t MASK_MTXMODE_TEXTURE20 = uint64_t(0x1) << eMTXMODE_TEXTURE20
static const uint64_t MASK_MTXMODE_TEXTURE21 = uint64_t(0x1) << eMTXMODE_TEXTURE21
static const uint64_t MASK_MTXMODE_TEXTURE22 = uint64_t(0x1) << eMTXMODE_TEXTURE22
static const uint64_t MASK_MTXMODE_TEXTURE23 = uint64_t(0x1) << eMTXMODE_TEXTURE23
static const uint64_t MASK_MTXMODE_TEXTURE24 = uint64_t(0x1) << eMTXMODE_TEXTURE24
static const uint64_t MASK_MTXMODE_TEXTURE25 = uint64_t(0x1) << eMTXMODE_TEXTURE25
static const uint64_t MASK_MTXMODE_TEXTURE26 = uint64_t(0x1) << eMTXMODE_TEXTURE26
static const uint64_t MASK_MTXMODE_TEXTURE27 = uint64_t(0x1) << eMTXMODE_TEXTURE27
static const uint64_t MASK_MTXMODE_TEXTURE28 = uint64_t(0x1) << eMTXMODE_TEXTURE28
static const uint64_t MASK_MTXMODE_TEXTURE29 = uint64_t(0x1) << eMTXMODE_TEXTURE29
static const uint64_t MASK_MTXMODE_TEXTURE30 = uint64_t(0x1) << eMTXMODE_TEXTURE30
static const uint64_t MASK_MTXMODE_TEXTURE31 = uint64_t(0x1) << eMTXMODE_TEXTURE31
uint32_t GetSize (eELEMENT_TYPE p_type)
DECLARE_SMART_PTR (GeometryBuffers)
DECLARE_SMART_PTR (BufferElementDeclaration)
DECLARE_SMART_PTR (BufferDeclaration)
DECLARE_SMART_PTR (VertexBuffer)
DECLARE_SMART_PTR (IndexBuffer)
DECLARE_SMART_PTR (TextureBuffer)
DECLARE_SMART_PTR (Context)
DECLARE_SMART_PTR (DepthStencilState)
DECLARE_SMART_PTR (RasteriserState)
DECLARE_SMART_PTR (BlendState)
DECLARE_SMART_PTR (IPipelineImpl)
DECLARE_SMART_PTR (ToneMapping)
DECLARE_MAP (RenderWindow *, ContextSPtr, ContextPtr)
DECLARE_MAP (std::thread::id, ContextPtrMap, ContextPtrMapId)
DECLARE_MULTIMAP (double, GeometryRenderNode, GeometryRenderNodeByDistance)
Multimap of RenderNodes sorted by distance.
DECLARE_MULTIMAP (double, BillboardRenderNode, BillboardRenderNodeByDistance)
DECLARE_VECTOR (GeometryRenderNode, GeometryRenderNode)
GeometryRenderNode array.
DECLARE_MAP (SubmeshSPtr, GeometryRenderNodeArray, SubmeshRenderNodes)
Submesh sorted GeometryRenderNodeArray.
DECLARE_VECTOR (BillboardRenderNode, BillboardRenderNode)
BillboardRenderNode array.
DECLARE_MAP (BillboardListSPtr, BillboardRenderNodeArray, BillboardRenderNodes)
Billboard sorted BillboardRenderNodeArray.
DECLARE_MAP (ShaderProgramSPtr, SubmeshRenderNodesByPassMap, SubmeshRenderNodesByProgram)
Shader program sorted SubmeshRenderNodesMap map.
DECLARE_MAP (ShaderProgramSPtr, BillboardRenderNodesByPassMap, BillboardRenderNodesByProgram)
Shader program sorted BillboardRenderNodesMap map.
Shader
enum eSHADER_MODEL : uint8_t {
eSHADER_MODEL_1, eSHADER_MODEL_2, eSHADER_MODEL_3, eSHADER_MODEL_4,
eSHADER_MODEL_5
}
Enumeration of existing shader models.
enum eSHADER_LANGUAGE : uint8_t { eSHADER_LANGUAGE_GLSL, eSHADER_LANGUAGE_AUTO }
Enumeration of existing shader lnaguages.
enum eSHADER_STATUS : uint8_t { eSHADER_STATUS_DONTEXIST, eSHADER_STATUS_NOTCOMPILED, eSHADER_STATUS_ERROR, eSHADER_STATUS_COMPILED }
Shader status enueration.
enum ePROGRAM_STATUS : uint8_t { ePROGRAM_STATUS_NOTLINKED, ePROGRAM_STATUS_ERROR, ePROGRAM_STATUS_LINKED }
Program status enumeration.
enum eSHADER_TYPE : int8_t {
eSHADER_TYPE_NONE = -1, eSHADER_TYPE_VERTEX, eSHADER_TYPE_HULL, eSHADER_TYPE_DOMAIN,
eSHADER_TYPE_GEOMETRY, eSHADER_TYPE_PIXEL, eSHADER_TYPE_COMPUTE
}
Shader object types enumeration.
enum ePROGRAM_FLAG : uint32_t { ePROGRAM_FLAG_INSTANCIATION = 0x01, ePROGRAM_FLAG_SKINNING = 0x02, ePROGRAM_FLAG_BILLBOARDS = 0x04 }
Flags to use when looking for an automatically generated program.
enum eVARIABLE_TYPE : uint8_t {
eVARIABLE_TYPE_ONE, eVARIABLE_TYPE_VEC1, eVARIABLE_TYPE_VEC2, eVARIABLE_TYPE_VEC3,
eVARIABLE_TYPE_VEC4, eVARIABLE_TYPE_MAT1, eVARIABLE_TYPE_MAT2X2, eVARIABLE_TYPE_MAT2X3,
eVARIABLE_TYPE_MAT2X4, eVARIABLE_TYPE_MAT3X2, eVARIABLE_TYPE_MAT3X3, eVARIABLE_TYPE_MAT3X4,
eVARIABLE_TYPE_MAT4X2, eVARIABLE_TYPE_MAT4X3, eVARIABLE_TYPE_MAT4X4
}
Supported variables dimensions enumeration.
enum eFRAME_VARIABLE_TYPE : uint8_t {
eFRAME_VARIABLE_TYPE_BOOL, eFRAME_VARIABLE_TYPE_INT, eFRAME_VARIABLE_TYPE_UINT, eFRAME_VARIABLE_TYPE_FLOAT,
eFRAME_VARIABLE_TYPE_DOUBLE, eFRAME_VARIABLE_TYPE_SAMPLER, eFRAME_VARIABLE_TYPE_VEC2B, eFRAME_VARIABLE_TYPE_VEC3B,
eFRAME_VARIABLE_TYPE_VEC4B, eFRAME_VARIABLE_TYPE_VEC2I, eFRAME_VARIABLE_TYPE_VEC3I, eFRAME_VARIABLE_TYPE_VEC4I,
eFRAME_VARIABLE_TYPE_VEC2UI, eFRAME_VARIABLE_TYPE_VEC3UI, eFRAME_VARIABLE_TYPE_VEC4UI, eFRAME_VARIABLE_TYPE_VEC2F,
eFRAME_VARIABLE_TYPE_VEC3F, eFRAME_VARIABLE_TYPE_VEC4F, eFRAME_VARIABLE_TYPE_VEC2D, eFRAME_VARIABLE_TYPE_VEC3D,
eFRAME_VARIABLE_TYPE_VEC4D, eFRAME_VARIABLE_TYPE_MAT2X2B, eFRAME_VARIABLE_TYPE_MAT2X3B, eFRAME_VARIABLE_TYPE_MAT2X4B,
eFRAME_VARIABLE_TYPE_MAT3X2B, eFRAME_VARIABLE_TYPE_MAT3X3B, eFRAME_VARIABLE_TYPE_MAT3X4B, eFRAME_VARIABLE_TYPE_MAT4X2B,
eFRAME_VARIABLE_TYPE_MAT4X3B, eFRAME_VARIABLE_TYPE_MAT4X4B, eFRAME_VARIABLE_TYPE_MAT2X2I, eFRAME_VARIABLE_TYPE_MAT2X3I,
eFRAME_VARIABLE_TYPE_MAT2X4I, eFRAME_VARIABLE_TYPE_MAT3X2I, eFRAME_VARIABLE_TYPE_MAT3X3I, eFRAME_VARIABLE_TYPE_MAT3X4I,
eFRAME_VARIABLE_TYPE_MAT4X2I, eFRAME_VARIABLE_TYPE_MAT4X3I, eFRAME_VARIABLE_TYPE_MAT4X4I, eFRAME_VARIABLE_TYPE_MAT2X2UI,
eFRAME_VARIABLE_TYPE_MAT2X3UI, eFRAME_VARIABLE_TYPE_MAT2X4UI, eFRAME_VARIABLE_TYPE_MAT3X2UI, eFRAME_VARIABLE_TYPE_MAT3X3UI,
eFRAME_VARIABLE_TYPE_MAT3X4UI, eFRAME_VARIABLE_TYPE_MAT4X2UI, eFRAME_VARIABLE_TYPE_MAT4X3UI, eFRAME_VARIABLE_TYPE_MAT4X4UI,
eFRAME_VARIABLE_TYPE_MAT2X2F, eFRAME_VARIABLE_TYPE_MAT2X3F, eFRAME_VARIABLE_TYPE_MAT2X4F, eFRAME_VARIABLE_TYPE_MAT3X2F,
eFRAME_VARIABLE_TYPE_MAT3X3F, eFRAME_VARIABLE_TYPE_MAT3X4F, eFRAME_VARIABLE_TYPE_MAT4X2F, eFRAME_VARIABLE_TYPE_MAT4X3F,
eFRAME_VARIABLE_TYPE_MAT4X4F, eFRAME_VARIABLE_TYPE_MAT2X2D, eFRAME_VARIABLE_TYPE_MAT2X3D, eFRAME_VARIABLE_TYPE_MAT2X4D,
eFRAME_VARIABLE_TYPE_MAT3X2D, eFRAME_VARIABLE_TYPE_MAT3X3D, eFRAME_VARIABLE_TYPE_MAT3X4D, eFRAME_VARIABLE_TYPE_MAT4X2D,
eFRAME_VARIABLE_TYPE_MAT4X3D, eFRAME_VARIABLE_TYPE_MAT4X4D
}
Supported variables full type enumeration.
typedef enum Castor3D::eSHADER_MODEL eSHADER_MODEL
Enumeration of existing shader models.
typedef enum Castor3D::eSHADER_LANGUAGE eSHADER_LANGUAGE
Enumeration of existing shader lnaguages.
typedef enum Castor3D::eSHADER_STATUS eSHADER_STATUS
Shader status enueration.
typedef enum Castor3D::ePROGRAM_STATUS ePROGRAM_STATUS
Program status enumeration.
typedef enum Castor3D::eSHADER_TYPE eSHADER_TYPE
Shader object types enumeration.
typedef enum Castor3D::ePROGRAM_FLAG ePROGRAM_FLAG
Flags to use when looking for an automatically generated program.
typedef enum Castor3D::eVARIABLE_TYPE eVARIABLE_TYPE
Supported variables dimensions enumeration.
typedef enum Castor3D::eFRAME_VARIABLE_TYPE eFRAME_VARIABLE_TYPE
Supported variables full type enumeration.
typedef OneFrameVariable< bool > OneBoolFrameVariable
typedef OneFrameVariable< int > OneIntFrameVariable
typedef OneFrameVariable< uint32_t > OneUIntFrameVariable
typedef OneFrameVariable< float > OneFloatFrameVariable
typedef OneFrameVariable< double > OneDoubleFrameVariable
typedef OneFrameVariable< real > OneRealFrameVariable
typedef PointFrameVariable< bool, 2 > Point2bFrameVariable
typedef PointFrameVariable< bool, 3 > Point3bFrameVariable
typedef PointFrameVariable< bool, 4 > Point4bFrameVariable
typedef PointFrameVariable< int, 2 > Point2iFrameVariable
typedef PointFrameVariable< int, 3 > Point3iFrameVariable
typedef PointFrameVariable< int, 4 > Point4iFrameVariable
typedef PointFrameVariable< uint32_t, 2 > Point2uiFrameVariable
typedef PointFrameVariable< uint32_t, 3 > Point3uiFrameVariable
typedef PointFrameVariable< uint32_t, 4 > Point4uiFrameVariable
typedef PointFrameVariable< float, 2 > Point2fFrameVariable
typedef PointFrameVariable< float, 3 > Point3fFrameVariable
typedef PointFrameVariable< float, 4 > Point4fFrameVariable
typedef PointFrameVariable< double, 2 > Point2dFrameVariable
typedef PointFrameVariable< double, 3 > Point3dFrameVariable
typedef PointFrameVariable< double, 4 > Point4dFrameVariable
typedef PointFrameVariable< real, 2 > Point2rFrameVariable
typedef PointFrameVariable< real, 3 > Point3rFrameVariable
typedef PointFrameVariable< real, 4 > Point4rFrameVariable
typedef MatrixFrameVariable< bool, 2, 2 > Matrix2x2bFrameVariable
typedef MatrixFrameVariable< bool, 2, 3 > Matrix2x3bFrameVariable
typedef MatrixFrameVariable< bool, 2, 4 > Matrix2x4bFrameVariable
typedef MatrixFrameVariable< bool, 3, 2 > Matrix3x2bFrameVariable
typedef MatrixFrameVariable< bool, 3, 3 > Matrix3x3bFrameVariable
typedef MatrixFrameVariable< bool, 3, 4 > Matrix3x4bFrameVariable
typedef MatrixFrameVariable< bool, 4, 2 > Matrix4x2bFrameVariable
typedef MatrixFrameVariable< bool, 4, 3 > Matrix4x3bFrameVariable
typedef MatrixFrameVariable< bool, 4, 4 > Matrix4x4bFrameVariable
typedef MatrixFrameVariable< int, 2, 2 > Matrix2x2iFrameVariable
typedef MatrixFrameVariable< int, 2, 3 > Matrix2x3iFrameVariable
typedef MatrixFrameVariable< int, 2, 4 > Matrix2x4iFrameVariable
typedef MatrixFrameVariable< int, 3, 2 > Matrix3x2iFrameVariable
typedef MatrixFrameVariable< int, 3, 3 > Matrix3x3iFrameVariable
typedef MatrixFrameVariable< int, 3, 4 > Matrix3x4iFrameVariable
typedef MatrixFrameVariable< int, 4, 2 > Matrix4x2iFrameVariable
typedef MatrixFrameVariable< int, 4, 3 > Matrix4x3iFrameVariable
typedef MatrixFrameVariable< int, 4, 4 > Matrix4x4iFrameVariable
typedef MatrixFrameVariable< unsigned int, 2, 2 > Matrix2x2uiFrameVariable
typedef MatrixFrameVariable< unsigned int, 2, 3 > Matrix2x3uiFrameVariable
typedef MatrixFrameVariable< unsigned int, 2, 4 > Matrix2x4uiFrameVariable
typedef MatrixFrameVariable< unsigned int, 3, 2 > Matrix3x2uiFrameVariable
typedef MatrixFrameVariable< unsigned int, 3, 3 > Matrix3x3uiFrameVariable
typedef MatrixFrameVariable< unsigned int, 3, 4 > Matrix3x4uiFrameVariable
typedef MatrixFrameVariable< unsigned int, 4, 2 > Matrix4x2uiFrameVariable
typedef MatrixFrameVariable< unsigned int, 4, 3 > Matrix4x3uiFrameVariable
typedef MatrixFrameVariable< unsigned int, 4, 4 > Matrix4x4uiFrameVariable
typedef MatrixFrameVariable< float, 2, 2 > Matrix2x2fFrameVariable
typedef MatrixFrameVariable< float, 2, 3 > Matrix2x3fFrameVariable
typedef MatrixFrameVariable< float, 2, 4 > Matrix2x4fFrameVariable
typedef MatrixFrameVariable< float, 3, 2 > Matrix3x2fFrameVariable
typedef MatrixFrameVariable< float, 3, 3 > Matrix3x3fFrameVariable
typedef MatrixFrameVariable< float, 3, 4 > Matrix3x4fFrameVariable
typedef MatrixFrameVariable< float, 4, 2 > Matrix4x2fFrameVariable
typedef MatrixFrameVariable< float, 4, 3 > Matrix4x3fFrameVariable
typedef MatrixFrameVariable< float, 4, 4 > Matrix4x4fFrameVariable
typedef MatrixFrameVariable< double, 2, 2 > Matrix2x2dFrameVariable
typedef MatrixFrameVariable< double, 2, 3 > Matrix2x3dFrameVariable
typedef MatrixFrameVariable< double, 2, 4 > Matrix2x4dFrameVariable
typedef MatrixFrameVariable< double, 3, 2 > Matrix3x2dFrameVariable
typedef MatrixFrameVariable< double, 3, 3 > Matrix3x3dFrameVariable
typedef MatrixFrameVariable< double, 3, 4 > Matrix3x4dFrameVariable
typedef MatrixFrameVariable< double, 4, 2 > Matrix4x2dFrameVariable
typedef MatrixFrameVariable< double, 4, 3 > Matrix4x3dFrameVariable
typedef MatrixFrameVariable< double, 4, 4 > Matrix4x4dFrameVariable
typedef MatrixFrameVariable< real, 2, 2 > Matrix2x2rFrameVariable
typedef MatrixFrameVariable< real, 2, 3 > Matrix2x3rFrameVariable
typedef MatrixFrameVariable< real, 2, 4 > Matrix2x4rFrameVariable
typedef MatrixFrameVariable< real, 3, 2 > Matrix3x2rFrameVariable
typedef MatrixFrameVariable< real, 3, 3 > Matrix3x3rFrameVariable
typedef MatrixFrameVariable< real, 3, 4 > Matrix3x4rFrameVariable
typedef MatrixFrameVariable< real, 4, 2 > Matrix4x2rFrameVariable
typedef MatrixFrameVariable< real, 4, 3 > Matrix4x3rFrameVariable
typedef MatrixFrameVariable< real, 4, 4 > Matrix4x4rFrameVariable
static const uint64_t MASK_SHADER_TYPE_VERTEX = uint64_t(0x1) << eSHADER_TYPE_VERTEX
Shader object types masks.
static const uint64_t MASK_SHADER_TYPE_HULL = uint64_t(0x1) << eSHADER_TYPE_HULL
static const uint64_t MASK_SHADER_TYPE_DOMAIN = uint64_t(0x1) << eSHADER_TYPE_DOMAIN
static const uint64_t MASK_SHADER_TYPE_GEOMETRY = uint64_t(0x1) << eSHADER_TYPE_GEOMETRY
static const uint64_t MASK_SHADER_TYPE_PIXEL = uint64_t(0x1) << eSHADER_TYPE_PIXEL
static const uint64_t MASK_SHADER_TYPE_COMPUTE = uint64_t(0x1) << eSHADER_TYPE_COMPUTE
DECLARE_SMART_PTR (OneBoolFrameVariable)
DECLARE_SMART_PTR (OneIntFrameVariable)
DECLARE_SMART_PTR (OneUIntFrameVariable)
DECLARE_SMART_PTR (OneFloatFrameVariable)
DECLARE_SMART_PTR (OneDoubleFrameVariable)
DECLARE_SMART_PTR (OneRealFrameVariable)
DECLARE_SMART_PTR (Point2bFrameVariable)
DECLARE_SMART_PTR (Point3bFrameVariable)
DECLARE_SMART_PTR (Point4bFrameVariable)
DECLARE_SMART_PTR (Point2iFrameVariable)
DECLARE_SMART_PTR (Point3iFrameVariable)
DECLARE_SMART_PTR (Point4iFrameVariable)
DECLARE_SMART_PTR (Point2uiFrameVariable)
DECLARE_SMART_PTR (Point3uiFrameVariable)
DECLARE_SMART_PTR (Point4uiFrameVariable)
DECLARE_SMART_PTR (Point2fFrameVariable)
DECLARE_SMART_PTR (Point3fFrameVariable)
DECLARE_SMART_PTR (Point4fFrameVariable)
DECLARE_SMART_PTR (Point2dFrameVariable)
DECLARE_SMART_PTR (Point3dFrameVariable)
DECLARE_SMART_PTR (Point4dFrameVariable)
DECLARE_SMART_PTR (Point2rFrameVariable)
DECLARE_SMART_PTR (Point3rFrameVariable)
DECLARE_SMART_PTR (Point4rFrameVariable)
DECLARE_SMART_PTR (Matrix2x2bFrameVariable)
DECLARE_SMART_PTR (Matrix2x3bFrameVariable)
DECLARE_SMART_PTR (Matrix2x4bFrameVariable)
DECLARE_SMART_PTR (Matrix3x2bFrameVariable)
DECLARE_SMART_PTR (Matrix3x3bFrameVariable)
DECLARE_SMART_PTR (Matrix3x4bFrameVariable)
DECLARE_SMART_PTR (Matrix4x2bFrameVariable)
DECLARE_SMART_PTR (Matrix4x3bFrameVariable)
DECLARE_SMART_PTR (Matrix4x4bFrameVariable)
DECLARE_SMART_PTR (Matrix2x2iFrameVariable)
DECLARE_SMART_PTR (Matrix2x3iFrameVariable)
DECLARE_SMART_PTR (Matrix2x4iFrameVariable)
DECLARE_SMART_PTR (Matrix3x2iFrameVariable)
DECLARE_SMART_PTR (Matrix3x3iFrameVariable)
DECLARE_SMART_PTR (Matrix3x4iFrameVariable)
DECLARE_SMART_PTR (Matrix4x2iFrameVariable)
DECLARE_SMART_PTR (Matrix4x3iFrameVariable)
DECLARE_SMART_PTR (Matrix4x4iFrameVariable)
DECLARE_SMART_PTR (Matrix2x2uiFrameVariable)
DECLARE_SMART_PTR (Matrix2x3uiFrameVariable)
DECLARE_SMART_PTR (Matrix2x4uiFrameVariable)
DECLARE_SMART_PTR (Matrix3x2uiFrameVariable)
DECLARE_SMART_PTR (Matrix3x3uiFrameVariable)
DECLARE_SMART_PTR (Matrix3x4uiFrameVariable)
DECLARE_SMART_PTR (Matrix4x2uiFrameVariable)
DECLARE_SMART_PTR (Matrix4x3uiFrameVariable)
DECLARE_SMART_PTR (Matrix4x4uiFrameVariable)
DECLARE_SMART_PTR (Matrix2x2fFrameVariable)
DECLARE_SMART_PTR (Matrix2x3fFrameVariable)
DECLARE_SMART_PTR (Matrix2x4fFrameVariable)
DECLARE_SMART_PTR (Matrix3x2fFrameVariable)
DECLARE_SMART_PTR (Matrix3x3fFrameVariable)
DECLARE_SMART_PTR (Matrix3x4fFrameVariable)
DECLARE_SMART_PTR (Matrix4x2fFrameVariable)
DECLARE_SMART_PTR (Matrix4x3fFrameVariable)
DECLARE_SMART_PTR (Matrix4x4fFrameVariable)
DECLARE_SMART_PTR (Matrix2x2dFrameVariable)
DECLARE_SMART_PTR (Matrix2x3dFrameVariable)
DECLARE_SMART_PTR (Matrix2x4dFrameVariable)
DECLARE_SMART_PTR (Matrix3x2dFrameVariable)
DECLARE_SMART_PTR (Matrix3x3dFrameVariable)
DECLARE_SMART_PTR (Matrix3x4dFrameVariable)
DECLARE_SMART_PTR (Matrix4x2dFrameVariable)
DECLARE_SMART_PTR (Matrix4x3dFrameVariable)
DECLARE_SMART_PTR (Matrix4x4dFrameVariable)
DECLARE_SMART_PTR (Matrix2x2rFrameVariable)
DECLARE_SMART_PTR (Matrix2x3rFrameVariable)
DECLARE_SMART_PTR (Matrix2x4rFrameVariable)
DECLARE_SMART_PTR (Matrix3x2rFrameVariable)
DECLARE_SMART_PTR (Matrix3x3rFrameVariable)
DECLARE_SMART_PTR (Matrix3x4rFrameVariable)
DECLARE_SMART_PTR (Matrix4x2rFrameVariable)
DECLARE_SMART_PTR (Matrix4x3rFrameVariable)
DECLARE_SMART_PTR (Matrix4x4rFrameVariable)
DECLARE_SMART_PTR (FrameVariableLink)
DECLARE_SMART_PTR (ProgramLinks)
DECLARE_SMART_PTR (FrameVariableBuffer)
DECLARE_SMART_PTR (FrameVariable)
DECLARE_SMART_PTR (ShaderObject)
DECLARE_SMART_PTR (ShaderProgram)
DECLARE_LIST (FrameVariableLinkSPtr, VariableLinkPtr)
DECLARE_MAP (ShaderProgram *, ProgramLinksSPtr, LinksPtrListProgram)
DECLARE_VECTOR (ShaderProgramSPtr, ShaderProgramPtr)
DECLARE_VECTOR (ShaderObjectSPtr, ShaderObjectPtr)
DECLARE_LIST (FrameVariableSPtr, FrameVariablePtr)
DECLARE_LIST (FrameVariableBufferSPtr, FrameVariableBufferPtr)
DECLARE_MAP (Castor::String, FrameVariableWPtr, FrameVariablePtrStr)
DECLARE_MAP (Castor::String, FrameVariableBufferWPtr, FrameVariableBufferPtrStr)
DECLARE_MAP (eSHADER_TYPE, FrameVariableBufferWPtr, FrameVariableBufferPtrShader)
Typedef Documentation
AnimationStateMap
using Castor3D::AnimationStateMap = typedef std::map< Castor::String, eANIMATION_STATE >
BillboardRenderNodesByPassMap
using Castor3D::BillboardRenderNodesByPassMap = typedef TypeRenderNodesByPassMap< BillboardRenderNodesMap >
eACCESS_TYPE
typedef enum Castor3D::eACCESS_TYPE Castor3D::eACCESS_TYPE
Access types enumeration.
Author
Sylvain DOREMUS
Version
0.8.0
Date
16/10/2015
eALPHA_BLEND_FUNC
typedef enum Castor3D::eALPHA_BLEND_FUNC Castor3D::eALPHA_BLEND_FUNC
Alpha blending functions enumeration.
Author
Sylvain DOREMUS
eALPHA_FUNC
typedef enum Castor3D::eALPHA_FUNC Castor3D::eALPHA_FUNC
Alpha functions enumeration.
Author
Sylvain DOREMUS
eANIMATION_OBJECT_TYPE
typedef enum Castor3D::eANIMATION_OBJECT_TYPE Castor3D::eANIMATION_OBJECT_TYPE
Class which represents the moving things.
Author
Sylvain DOREMUS
Version
0.1
Date
09/02/2010
Remarks
Manages translation, scaling, rotation of the thing.
eANIMATION_STATE
typedef enum Castor3D::eANIMATION_STATE Castor3D::eANIMATION_STATE
Animation State Enumerator.
Author
Sylvain DOREMUS
Date
09/02/2010
eATTACHMENT_POINT
typedef enum Castor3D::eATTACHMENT_POINT Castor3D::eATTACHMENT_POINT
Frame buffer attachment points enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
12/11/2012
eATTACHMENT_TYPE
typedef enum Castor3D::eATTACHMENT_TYPE Castor3D::eATTACHMENT_TYPE
Frame buffer attachment types enumeration.
Author
Sylvain DOREMUS
Version
0.8.0.0
Date
11/10/2015
eBLEND
typedef enum Castor3D::eBLEND Castor3D::eBLEND
Blend operators enumeration.
Author
Sylvain DOREMUS
eBLEND_MODE
typedef enum Castor3D::eBLEND_MODE Castor3D::eBLEND_MODE
Blending modes enumeration.
Author
Sylvain DOREMUS
eBLEND_OP
typedef enum Castor3D::eBLEND_OP Castor3D::eBLEND_OP
Blending operations enumeration.
Author
Sylvain DOREMUS
eBLEND_SOURCE
typedef enum Castor3D::eBLEND_SOURCE Castor3D::eBLEND_SOURCE
Texture blending sources enumeration.
Author
Sylvain DOREMUS
eBLEND_SRC_INDEX
typedef enum Castor3D::eBLEND_SRC_INDEX Castor3D::eBLEND_SRC_INDEX
Texture blending source indices enumeration.
Author
Sylvain DOREMUS
eBORDER_POSITION
typedef enum Castor3D::eBORDER_POSITION Castor3D::eBORDER_POSITION
Text wrapping modes, handles the way text is cut when it overflows the overlay width.
Author
Sylvain DOREMUS
Date
28/11/2014
eBUFFER
typedef enum Castor3D::eBUFFER Castor3D::eBUFFER
Frame buffer components enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
12/11/2012
eBUFFER_ACCESS_NATURE
typedef enum Castor3D::eBUFFER_ACCESS_NATURE Castor3D::eBUFFER_ACCESS_NATURE
Buffer access natures enumeration.
Author
Sylvain DOREMUS
See also
eBUFFER_ACCESS_TYPE
Remarks
Made to be combined with eBUFFER_ACCESS_TYPE
eBUFFER_ACCESS_TYPE
typedef enum Castor3D::eBUFFER_ACCESS_TYPE Castor3D::eBUFFER_ACCESS_TYPE
Buffer access types enumeration.
Author
Sylvain DOREMUS
See also
eBUFFER_ACCESS_NATURE
Remarks
Made to be combined with eBUFFER_ACCESS_NATURE
eBUFFER_COMPONENT
typedef enum Castor3D::eBUFFER_COMPONENT Castor3D::eBUFFER_COMPONENT
Frame buffer components enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
12/11/2012
eCHUNK_TYPE
typedef enum Castor3D::eCHUNK_TYPE Castor3D::eCHUNK_TYPE
Binary data chunk types enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
15/04/2013
eDEPTH_FUNC
typedef enum Castor3D::eDEPTH_FUNC Castor3D::eDEPTH_FUNC
Depth functions enumeration.
Author
Sylvain DOREMUS
Version
0.7.0
Date
02/06/2013
eELEMENT_TYPE
typedef enum Castor3D::eELEMENT_TYPE Castor3D::eELEMENT_TYPE
Element type enumeration.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
03/01/2011
eELEMENT_USAGE
typedef enum Castor3D::eELEMENT_USAGE Castor3D::eELEMENT_USAGE
Element usage enumeration.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
03/01/2011
eEVENT_TYPE
typedef enum Castor3D::eEVENT_TYPE Castor3D::eEVENT_TYPE
Frame Event Type enumeration.
Author
Sylvain DOREMUS
eFACE
typedef enum Castor3D::eFACE Castor3D::eFACE
Faces orientations enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
23/05/2013
eFILL_MODE
typedef enum Castor3D::eFILL_MODE Castor3D::eFILL_MODE
Polygon rasterisation modes enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
23/05/2013
eFRAME_VARIABLE_TYPE
typedef enum Castor3D::eFRAME_VARIABLE_TYPE Castor3D::eFRAME_VARIABLE_TYPE
Supported variables full type enumeration.
Author
Sylvain DOREMUS
eFRAMEBUFFER_MODE
typedef enum Castor3D::eFRAMEBUFFER_MODE Castor3D::eFRAMEBUFFER_MODE
Frame buffer binding modes enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
12/11/2012
eFRAMEBUFFER_TARGET
typedef enum Castor3D::eFRAMEBUFFER_TARGET Castor3D::eFRAMEBUFFER_TARGET
Frame buffer binding targets enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
12/11/2012
eFRUSTUM_PLANE
typedef enum Castor3D::eFRUSTUM_PLANE Castor3D::eFRUSTUM_PLANE
Frustum view planes enumeration.
Author
Sylvain DOREMUS
Date
10/06/2013
Version
0.7.0
eHALIGN
typedef enum Castor3D::eHALIGN Castor3D::eHALIGN
Horizontal alignments for text overlays.
Author
Sylvain DOREMUS
Date
23/09/2015
Version
0.8.0
eINTERPOLATION_FILTER
typedef enum Castor3D::eINTERPOLATION_FILTER Castor3D::eINTERPOLATION_FILTER
Texture interpolation filters enumeration.
Author
Sylvain DOREMUS
eINTERPOLATION_MODE
typedef enum Castor3D::eINTERPOLATION_MODE Castor3D::eINTERPOLATION_MODE
Texture filter interpolation modes enumeration.
Author
Sylvain DOREMUS
eINTERPOLATOR_MODE
typedef enum Castor3D::eINTERPOLATOR_MODE Castor3D::eINTERPOLATOR_MODE
Interpolation modes enumeration.
Author
Sylvain DOREMUS
Version
0.1
Date
09/02/2010
eLIGHT_TYPE
typedef enum Castor3D::eLIGHT_TYPE Castor3D::eLIGHT_TYPE
Light types enumeration.
Author
Sylvain DOREMUS
eMESH_TYPE
typedef enum Castor3D::eMESH_TYPE Castor3D::eMESH_TYPE
Mesh type enumeration.
Author
Sylvain DOREMUS
eMOVABLE_TYPE
typedef enum Castor3D::eMOVABLE_TYPE Castor3D::eMOVABLE_TYPE
Movable object types enumerator.
Author
Sylvain DOREMUS
Version
0.1
Date
09/02/2010
Remarks
There are four movable object types : camera, geometry, light and billboard.
eMTXMODE
typedef enum Castor3D::eMTXMODE Castor3D::eMTXMODE
Matrix modes enumeration.
Author
Sylvain DOREMUS
eNORMAL
typedef enum Castor3D::eNORMAL Castor3D::eNORMAL
Enumerates supported normal generation.
Author
Sylvain DOREMUS
eOVERLAY_TYPE
typedef enum Castor3D::eOVERLAY_TYPE Castor3D::eOVERLAY_TYPE
Overlay types enumeration.
Author
Sylvain DOREMUS
ePLUGIN_TYPE
typedef enum Castor3D::ePLUGIN_TYPE Castor3D::ePLUGIN_TYPE
Plugin types enumeration.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
03/01/2011
ePROGRAM_FLAG
typedef enum Castor3D::ePROGRAM_FLAG Castor3D::ePROGRAM_FLAG
Flags to use when looking for an automatically generated program.
Author
Sylvain DOREMUS
Date
20/11/13
Version
0.7.0.0
ePROGRAM_STATUS
typedef enum Castor3D::ePROGRAM_STATUS Castor3D::ePROGRAM_STATUS
Program status enumeration.
Author
Sylvain DOREMUS
Date
22/08/2012
Version
0.7.0.0
eQUERY_INFO
typedef enum Castor3D::eQUERY_INFO Castor3D::eQUERY_INFO
GPU query supported informations enumeration.
Author
Sylvain DOREMUS
Version
0.8.0
Date
16/03/2016
eQUERY_TYPE
typedef enum Castor3D::eQUERY_TYPE Castor3D::eQUERY_TYPE
GPU query supported types enumeration.
Author
Sylvain DOREMUS
Version
0.8.0
Date
16/03/2016
eRENDERER_TYPE
typedef enum Castor3D::eRENDERER_TYPE Castor3D::eRENDERER_TYPE
Supported renderers enumeration.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
01/04/2011
eRGB_BLEND_FUNC
typedef enum Castor3D::eRGB_BLEND_FUNC Castor3D::eRGB_BLEND_FUNC
RGB blending functions enumeration.
Author
Sylvain DOREMUS
eSECTION
typedef enum Castor3D::eSECTION Castor3D::eSECTION
Scene file sections Enum.
The enumeration which defines all the sections and subsections of a scene file
eSHADER_LANGUAGE
typedef enum Castor3D::eSHADER_LANGUAGE Castor3D::eSHADER_LANGUAGE
Enumeration of existing shader lnaguages.
Author
Sylvain DOREMUS
eSHADER_MODEL
typedef enum Castor3D::eSHADER_MODEL Castor3D::eSHADER_MODEL
Enumeration of existing shader models.
Author
Sylvain DOREMUS
eSHADER_STATUS
typedef enum Castor3D::eSHADER_STATUS Castor3D::eSHADER_STATUS
Shader status enueration.
Author
Sylvain DOREMUS
Date
22/08/2012
Version
0.7.0.0
eSHADER_TYPE
typedef enum Castor3D::eSHADER_TYPE Castor3D::eSHADER_TYPE
Shader object types enumeration.
Author
Sylvain DOREMUS
eSTENCIL_FUNC
typedef enum Castor3D::eSTENCIL_FUNC Castor3D::eSTENCIL_FUNC
Stencil functions enumeration.
Author
Sylvain DOREMUS
Version
0.7.0
Date
02/06/2013
eSTENCIL_OP
typedef enum Castor3D::eSTENCIL_OP Castor3D::eSTENCIL_OP
Stencil functions enumeration.
Author
Sylvain DOREMUS
Version
0.7.0
Date
02/06/2013
eTARGET_TYPE
typedef enum Castor3D::eTARGET_TYPE Castor3D::eTARGET_TYPE
RenderTarget supported types.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
19/10/2011
eTEXT_TEXTURING_MODE
typedef enum Castor3D::eTEXT_TEXTURING_MODE Castor3D::eTEXT_TEXTURING_MODE
Text texturing modes, handles the way textures are appied to text overlays.
Author
Sylvain DOREMUS
Date
26/03/2016
eTEXT_WRAPPING_MODE
typedef enum Castor3D::eTEXT_WRAPPING_MODE Castor3D::eTEXT_WRAPPING_MODE
Text wrapping modes, handles the way text is cut when it overflows the overlay width.
Author
Sylvain DOREMUS
Date
28/11/2014
eTEXTURE_BASE_TYPE
typedef enum Castor3D::eTEXTURE_BASE_TYPE Castor3D::eTEXTURE_BASE_TYPE
Texture types enumeration.
Author
Sylvain DOREMUS
eTEXTURE_CHANNEL
typedef enum Castor3D::eTEXTURE_CHANNEL Castor3D::eTEXTURE_CHANNEL
Texture channels enumeration.
Author
Sylvain DOREMUS
eTEXTURE_MAP_MODE
typedef enum Castor3D::eTEXTURE_MAP_MODE Castor3D::eTEXTURE_MAP_MODE
Texture mapping modes enumeration.
Author
Sylvain DOREMUS
eTEXTURE_TARGET
typedef enum Castor3D::eTEXTURE_TARGET Castor3D::eTEXTURE_TARGET
Texture targets enumeration.
Author
Sylvain DOREMUS
eTEXTURE_TYPE
typedef enum Castor3D::eTEXTURE_TYPE Castor3D::eTEXTURE_TYPE
Texture dimensions enumeration.
Author
Sylvain DOREMUS
eTEXTURE_UVW
typedef enum Castor3D::eTEXTURE_UVW Castor3D::eTEXTURE_UVW
Texture UVW enumeration.
Author
Sylvain DOREMUS
eTONE_MAPPING_TYPE
typedef enum Castor3D::eTONE_MAPPING_TYPE Castor3D::eTONE_MAPPING_TYPE
Tone mapping type enumeration.
Author
Sylvain DOREMUS
Version
0.8.0
Date
10/03/2016
eTOPOLOGY
typedef enum Castor3D::eTOPOLOGY Castor3D::eTOPOLOGY
Primitive draw types enumeration.
Author
Sylvain DOREMUS
eVALIGN
typedef enum Castor3D::eVALIGN Castor3D::eVALIGN
Vertical alignments for text overlays.
Author
Sylvain DOREMUS
Date
23/09/2015
Version
0.8.0
eVARIABLE_TYPE
typedef enum Castor3D::eVARIABLE_TYPE Castor3D::eVARIABLE_TYPE
Supported variables dimensions enumeration.
Author
Sylvain DOREMUS
eVIEWPORT_TYPE
typedef enum Castor3D::eVIEWPORT_TYPE Castor3D::eVIEWPORT_TYPE
The viewport projection types enumeration.
Author
Sylvain DOREMUS
eWRAP_MODE
typedef enum Castor3D::eWRAP_MODE Castor3D::eWRAP_MODE
Texture wrap modes enumeration.
Author
Sylvain DOREMUS
eWRITING_MASK
typedef enum Castor3D::eWRITING_MASK Castor3D::eWRITING_MASK
Wrinting masks enumeration.
Author
Sylvain DOREMUS
Version
0.7.0
Date
02/06/2013
KeyFrameArray
using Castor3D::KeyFrameArray = typedef std::vector< KeyFrame >
KeyFrameRealMap
using Castor3D::KeyFrameRealMap = typedef std::map< real, KeyFrame >
Matrix2x2bFrameVariable
typedef MatrixFrameVariable< bool, 2, 2 > Castor3D::Matrix2x2bFrameVariable
Matrix2x2dFrameVariable
typedef MatrixFrameVariable< double, 2, 2 > Castor3D::Matrix2x2dFrameVariable
Matrix2x2fFrameVariable
typedef MatrixFrameVariable< float, 2, 2 > Castor3D::Matrix2x2fFrameVariable
Matrix2x2iFrameVariable
typedef MatrixFrameVariable< int, 2, 2 > Castor3D::Matrix2x2iFrameVariable
Matrix2x2rFrameVariable
typedef MatrixFrameVariable< real, 2, 2 > Castor3D::Matrix2x2rFrameVariable
Matrix2x2uiFrameVariable
typedef MatrixFrameVariable< unsigned int, 2, 2 > Castor3D::Matrix2x2uiFrameVariable
Matrix2x3bFrameVariable
typedef MatrixFrameVariable< bool, 2, 3 > Castor3D::Matrix2x3bFrameVariable
Matrix2x3dFrameVariable
typedef MatrixFrameVariable< double, 2, 3 > Castor3D::Matrix2x3dFrameVariable
Matrix2x3fFrameVariable
typedef MatrixFrameVariable< float, 2, 3 > Castor3D::Matrix2x3fFrameVariable
Matrix2x3iFrameVariable
typedef MatrixFrameVariable< int, 2, 3 > Castor3D::Matrix2x3iFrameVariable
Matrix2x3rFrameVariable
typedef MatrixFrameVariable< real, 2, 3 > Castor3D::Matrix2x3rFrameVariable
Matrix2x3uiFrameVariable
typedef MatrixFrameVariable< unsigned int, 2, 3 > Castor3D::Matrix2x3uiFrameVariable
Matrix2x4bFrameVariable
typedef MatrixFrameVariable< bool, 2, 4 > Castor3D::Matrix2x4bFrameVariable
Matrix2x4dFrameVariable
typedef MatrixFrameVariable< double, 2, 4 > Castor3D::Matrix2x4dFrameVariable
Matrix2x4fFrameVariable
typedef MatrixFrameVariable< float, 2, 4 > Castor3D::Matrix2x4fFrameVariable
Matrix2x4iFrameVariable
typedef MatrixFrameVariable< int, 2, 4 > Castor3D::Matrix2x4iFrameVariable
Matrix2x4rFrameVariable
typedef MatrixFrameVariable< real, 2, 4 > Castor3D::Matrix2x4rFrameVariable
Matrix2x4uiFrameVariable
typedef MatrixFrameVariable< unsigned int, 2, 4 > Castor3D::Matrix2x4uiFrameVariable
Matrix3x2bFrameVariable
typedef MatrixFrameVariable< bool, 3, 2 > Castor3D::Matrix3x2bFrameVariable
Matrix3x2dFrameVariable
typedef MatrixFrameVariable< double, 3, 2 > Castor3D::Matrix3x2dFrameVariable
Matrix3x2fFrameVariable
typedef MatrixFrameVariable< float, 3, 2 > Castor3D::Matrix3x2fFrameVariable
Matrix3x2iFrameVariable
typedef MatrixFrameVariable< int, 3, 2 > Castor3D::Matrix3x2iFrameVariable
Matrix3x2rFrameVariable
typedef MatrixFrameVariable< real, 3, 2 > Castor3D::Matrix3x2rFrameVariable
Matrix3x2uiFrameVariable
typedef MatrixFrameVariable< unsigned int, 3, 2 > Castor3D::Matrix3x2uiFrameVariable
Matrix3x3bFrameVariable
typedef MatrixFrameVariable< bool, 3, 3 > Castor3D::Matrix3x3bFrameVariable
Matrix3x3dFrameVariable
typedef MatrixFrameVariable< double, 3, 3 > Castor3D::Matrix3x3dFrameVariable
Matrix3x3fFrameVariable
typedef MatrixFrameVariable< float, 3, 3 > Castor3D::Matrix3x3fFrameVariable
Matrix3x3iFrameVariable
typedef MatrixFrameVariable< int, 3, 3 > Castor3D::Matrix3x3iFrameVariable
Matrix3x3rFrameVariable
typedef MatrixFrameVariable< real, 3, 3 > Castor3D::Matrix3x3rFrameVariable
Matrix3x3uiFrameVariable
typedef MatrixFrameVariable< unsigned int, 3, 3 > Castor3D::Matrix3x3uiFrameVariable
Matrix3x4bFrameVariable
typedef MatrixFrameVariable< bool, 3, 4 > Castor3D::Matrix3x4bFrameVariable
Matrix3x4dFrameVariable
typedef MatrixFrameVariable< double, 3, 4 > Castor3D::Matrix3x4dFrameVariable
Matrix3x4fFrameVariable
typedef MatrixFrameVariable< float, 3, 4 > Castor3D::Matrix3x4fFrameVariable
Matrix3x4iFrameVariable
typedef MatrixFrameVariable< int, 3, 4 > Castor3D::Matrix3x4iFrameVariable
Matrix3x4rFrameVariable
typedef MatrixFrameVariable< real, 3, 4 > Castor3D::Matrix3x4rFrameVariable
Matrix3x4uiFrameVariable
typedef MatrixFrameVariable< unsigned int, 3, 4 > Castor3D::Matrix3x4uiFrameVariable
Matrix4x2bFrameVariable
typedef MatrixFrameVariable< bool, 4, 2 > Castor3D::Matrix4x2bFrameVariable
Matrix4x2dFrameVariable
typedef MatrixFrameVariable< double, 4, 2 > Castor3D::Matrix4x2dFrameVariable
Matrix4x2fFrameVariable
typedef MatrixFrameVariable< float, 4, 2 > Castor3D::Matrix4x2fFrameVariable
Matrix4x2iFrameVariable
typedef MatrixFrameVariable< int, 4, 2 > Castor3D::Matrix4x2iFrameVariable
Matrix4x2rFrameVariable
typedef MatrixFrameVariable< real, 4, 2 > Castor3D::Matrix4x2rFrameVariable
Matrix4x2uiFrameVariable
typedef MatrixFrameVariable< unsigned int, 4, 2 > Castor3D::Matrix4x2uiFrameVariable
Matrix4x3bFrameVariable
typedef MatrixFrameVariable< bool, 4, 3 > Castor3D::Matrix4x3bFrameVariable
Matrix4x3dFrameVariable
typedef MatrixFrameVariable< double, 4, 3 > Castor3D::Matrix4x3dFrameVariable
Matrix4x3fFrameVariable
typedef MatrixFrameVariable< float, 4, 3 > Castor3D::Matrix4x3fFrameVariable
Matrix4x3iFrameVariable
typedef MatrixFrameVariable< int, 4, 3 > Castor3D::Matrix4x3iFrameVariable
Matrix4x3rFrameVariable
typedef MatrixFrameVariable< real, 4, 3 > Castor3D::Matrix4x3rFrameVariable
Matrix4x3uiFrameVariable
typedef MatrixFrameVariable< unsigned int, 4, 3 > Castor3D::Matrix4x3uiFrameVariable
Matrix4x4bFrameVariable
typedef MatrixFrameVariable< bool, 4, 4 > Castor3D::Matrix4x4bFrameVariable
Matrix4x4dFrameVariable
typedef MatrixFrameVariable< double, 4, 4 > Castor3D::Matrix4x4dFrameVariable
Matrix4x4fFrameVariable
typedef MatrixFrameVariable< float, 4, 4 > Castor3D::Matrix4x4fFrameVariable
Matrix4x4iFrameVariable
typedef MatrixFrameVariable< int, 4, 4 > Castor3D::Matrix4x4iFrameVariable
Matrix4x4rFrameVariable
typedef MatrixFrameVariable< real, 4, 4 > Castor3D::Matrix4x4rFrameVariable
Matrix4x4uiFrameVariable
typedef MatrixFrameVariable< unsigned int, 4, 4 > Castor3D::Matrix4x4uiFrameVariable
OneBoolFrameVariable
typedef OneFrameVariable< bool > Castor3D::OneBoolFrameVariable
OneDoubleFrameVariable
typedef OneFrameVariable< double > Castor3D::OneDoubleFrameVariable
OneFloatFrameVariable
typedef OneFrameVariable< float > Castor3D::OneFloatFrameVariable
OneIntFrameVariable
typedef OneFrameVariable< int > Castor3D::OneIntFrameVariable
OneRealFrameVariable
typedef OneFrameVariable< real > Castor3D::OneRealFrameVariable
OneUIntFrameVariable
typedef OneFrameVariable< uint32_t > Castor3D::OneUIntFrameVariable
OverlayManagerConstIt
typedef OverlayManager::const_iterator Castor3D::OverlayManagerConstIt
OverlayManagerIt
typedef OverlayManager::iterator Castor3D::OverlayManagerIt
Point2bFrameVariable
typedef PointFrameVariable< bool, 2 > Castor3D::Point2bFrameVariable
Point2dFrameVariable
typedef PointFrameVariable< double, 2 > Castor3D::Point2dFrameVariable
Point2fFrameVariable
typedef PointFrameVariable< float, 2 > Castor3D::Point2fFrameVariable
Point2iFrameVariable
typedef PointFrameVariable< int, 2 > Castor3D::Point2iFrameVariable
Point2rFrameVariable
typedef PointFrameVariable< real, 2 > Castor3D::Point2rFrameVariable
Point2uiFrameVariable
typedef PointFrameVariable< uint32_t, 2 > Castor3D::Point2uiFrameVariable
Point3bFrameVariable
typedef PointFrameVariable< bool, 3 > Castor3D::Point3bFrameVariable
Point3dFrameVariable
typedef PointFrameVariable< double, 3 > Castor3D::Point3dFrameVariable
Point3fFrameVariable
typedef PointFrameVariable< float, 3 > Castor3D::Point3fFrameVariable
Point3iFrameVariable
typedef PointFrameVariable< int, 3 > Castor3D::Point3iFrameVariable
Point3rFrameVariable
typedef PointFrameVariable< real, 3 > Castor3D::Point3rFrameVariable
Point3rInterpolator
using Castor3D::Point3rInterpolator = typedef Interpolator< Castor::Point3r >
Point3rPattern
typedef Pattern< Castor::Point3r > Castor3D::Point3rPattern
Point3rPtrPattern
typedef Pattern< Castor::Point3rSPtr > Castor3D::Point3rPtrPattern
Point3uiFrameVariable
typedef PointFrameVariable< uint32_t, 3 > Castor3D::Point3uiFrameVariable
Point4bFrameVariable
typedef PointFrameVariable< bool, 4 > Castor3D::Point4bFrameVariable
Point4dFrameVariable
typedef PointFrameVariable< double, 4 > Castor3D::Point4dFrameVariable
Point4fFrameVariable
typedef PointFrameVariable< float, 4 > Castor3D::Point4fFrameVariable
Point4iFrameVariable
typedef PointFrameVariable< int, 4 > Castor3D::Point4iFrameVariable
Point4rFrameVariable
typedef PointFrameVariable< real, 4 > Castor3D::Point4rFrameVariable
Point4uiFrameVariable
typedef PointFrameVariable< uint32_t, 4 > Castor3D::Point4uiFrameVariable
QuaternionInterpolator
using Castor3D::QuaternionInterpolator = typedef Interpolator< Castor::Quaternion >
SubmeshRenderNodesByPassMap
using Castor3D::SubmeshRenderNodesByPassMap = typedef TypeRenderNodesByPassMap< SubmeshRenderNodesMap >
VertexPattern
typedef Pattern< Vertex > Castor3D::VertexPattern
VertexPtrPattern
typedef Pattern< VertexSPtr > Castor3D::VertexPtrPattern
WindowPtrStrMap
typedef std::map< Castor::String, RenderWindowSPtr > Castor3D::WindowPtrStrMap
Enumeration Type Documentation
eACCESS_TYPE
enum Castor3D::eACCESS_TYPE : uint8_t
Access types enumeration.
Author
Sylvain DOREMUS
Version
0.8.0
Date
16/10/2015
Enumerator
eACCESS_TYPE_READ
Read access type.
eACCESS_TYPE_WRITE
Write access type.
eALPHA_BLEND_FUNC
enum Castor3D::eALPHA_BLEND_FUNC : uint8_t
Alpha blending functions enumeration.
Author
Sylvain DOREMUS
Enumerator
eALPHA_BLEND_FUNC_NONE
No blend
eALPHA_BLEND_FUNC_FIRST_ARG
Arg0
eALPHA_BLEND_FUNC_ADD
Arg0 + Arg1
eALPHA_BLEND_FUNC_ADD_SIGNED
Arg0 + Arg1 - 0.5
eALPHA_BLEND_FUNC_MODULATE
Arg0 x Arg1
eALPHA_BLEND_FUNC_INTERPOLATE
Arg0 Arg2 + Arg1 (1 - Arg2)
eALPHA_BLEND_FUNC_SUBSTRACT
Arg0 - Arg1
eALPHA_FUNC
enum Castor3D::eALPHA_FUNC : uint8_t
Alpha functions enumeration.
Author
Sylvain DOREMUS
Enumerator
eALPHA_FUNC_ALWAYS
Always take texture colour.
eALPHA_FUNC_LESS
Takes texture colour if alpha is less than given value.
eALPHA_FUNC_LESS_OR_EQUAL
Takes texture colour if alpha is less than or equal to given value.
eALPHA_FUNC_EQUAL
Takes texture colour if alpha is equal to given value.
eALPHA_FUNC_NOT_EQUAL
Takes texture colour if alpha is different of given value.
eALPHA_FUNC_GREATER_OR_EQUAL
Takes texture colour if alpha is grater than or equal to given value.
eALPHA_FUNC_GREATER
Takes texture colour if alpha is greater than given value.
eALPHA_FUNC_NEVER
Never take texture colour.
eANIMATION_OBJECT_TYPE
enum Castor3D::eANIMATION_OBJECT_TYPE : uint8_t
Class which represents the moving things.
Author
Sylvain DOREMUS
Version
0.1
Date
09/02/2010
Remarks
Manages translation, scaling, rotation of the thing.
Enumerator
eANIMATION_OBJECT_TYPE_NODE
eANIMATION_OBJECT_TYPE_OBJECT
eANIMATION_OBJECT_TYPE_BONE
eANIMATION_STATE
enum Castor3D::eANIMATION_STATE : uint8_t
Animation State Enumerator.
Author
Sylvain DOREMUS
Date
09/02/2010
Enumerator
eANIMATION_STATE_PLAYING
Playing animation state.
eANIMATION_STATE_STOPPED
Stopped animation state.
eANIMATION_STATE_PAUSED
Paused animation state.
eATTACHMENT_POINT
enum Castor3D::eATTACHMENT_POINT : uint8_t
Frame buffer attachment points enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
12/11/2012
Enumerator
eATTACHMENT_POINT_NONE
eATTACHMENT_POINT_COLOUR
eATTACHMENT_POINT_DEPTH
eATTACHMENT_POINT_STENCIL
eATTACHMENT_TYPE
enum Castor3D::eATTACHMENT_TYPE : uint8_t
Frame buffer attachment types enumeration.
Author
Sylvain DOREMUS
Version
0.8.0.0
Date
11/10/2015
Enumerator
eATTACHMENT_TYPE_TEXTURE
eATTACHMENT_TYPE_BUFFER
eBLEND
enum Castor3D::eBLEND : uint8_t
Blend operators enumeration.
Author
Sylvain DOREMUS
Enumerator
eBLEND_ZERO
eBLEND_ONE
eBLEND_SRC_COLOUR
eBLEND_INV_SRC_COLOUR
eBLEND_DST_COLOUR
eBLEND_INV_DST_COLOUR
eBLEND_SRC_ALPHA
eBLEND_INV_SRC_ALPHA
eBLEND_DST_ALPHA
eBLEND_INV_DST_ALPHA
eBLEND_CONSTANT
eBLEND_INV_CONSTANT
eBLEND_SRC_ALPHA_SATURATE
eBLEND_SRC1_COLOUR
eBLEND_INV_SRC1_COLOUR
eBLEND_SRC1_ALPHA
eBLEND_INV_SRC1_ALPHA
eBLEND_MODE
enum Castor3D::eBLEND_MODE : uint8_t
Blending modes enumeration.
Author
Sylvain DOREMUS
Enumerator
eBLEND_MODE_NONE
Order dependent blending.
eBLEND_MODE_ADDITIVE
Order independent, add the components.
eBLEND_MODE_MULTIPLICATIVE
Order independent, multiply the components.
eBLEND_MODE_INTERPOLATIVE
Order dependent, interpolate the components.
eBLEND_MODE_A_BUFFER
Order independent, using A-buffer, not implemented yet.
eBLEND_MODE_DEPTH_PEELING
Order independent, using depth peeling, not implemented yet.
eBLEND_OP
enum Castor3D::eBLEND_OP : uint8_t
Blending operations enumeration.
Author
Sylvain DOREMUS
Enumerator
eBLEND_OP_ADD
Src2 + Src1.
eBLEND_OP_SUBSTRACT
Src2 - Src1.
eBLEND_OP_REV_SUBSTRACT
Src1 - Src2.
eBLEND_OP_MIN
min(Src1, Src2).
eBLEND_OP_MAX
max(Src1, Src2).
eBLEND_OP_COUNT
eBLEND_SOURCE
enum Castor3D::eBLEND_SOURCE : uint8_t
Texture blending sources enumeration.
Author
Sylvain DOREMUS
Enumerator
eBLEND_SOURCE_TEXTURE
eBLEND_SOURCE_TEXTURE0
eBLEND_SOURCE_TEXTURE1
eBLEND_SOURCE_TEXTURE2
eBLEND_SOURCE_TEXTURE3
eBLEND_SOURCE_CONSTANT
eBLEND_SOURCE_DIFFUSE
eBLEND_SOURCE_PREVIOUS
eBLEND_SRC_INDEX
enum Castor3D::eBLEND_SRC_INDEX : uint8_t
Texture blending source indices enumeration.
Author
Sylvain DOREMUS
Enumerator
eBLEND_SRC_INDEX_0
eBLEND_SRC_INDEX_1
eBLEND_SRC_INDEX_2
eBORDER_POSITION
enum Castor3D::eBORDER_POSITION
Text wrapping modes, handles the way text is cut when it overflows the overlay width.
Author
Sylvain DOREMUS
Date
28/11/2014
Enumerator
eBORDER_POSITION_INTERNAL
The border is outside the overlay.
eBORDER_POSITION_MIDDLE
The border is middle outside and middle inside the overlay.
eBORDER_POSITION_EXTERNAL
The border is outside the overlay.
eBUFFER
enum Castor3D::eBUFFER : uint8_t
Frame buffer components enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
12/11/2012
Enumerator
eBUFFER_NONE
eBUFFER_FRONT_LEFT
eBUFFER_FRONT_RIGHT
eBUFFER_BACK_LEFT
eBUFFER_BACK_RIGHT
eBUFFER_FRONT
eBUFFER_BACK
eBUFFER_LEFT
eBUFFER_RIGHT
eBUFFER_FRONT_AND_BACK
eBUFFER_ACCESS_NATURE
enum Castor3D::eBUFFER_ACCESS_NATURE : uint32_t
Buffer access natures enumeration.
Author
Sylvain DOREMUS
See also
eBUFFER_ACCESS_TYPE
Remarks
Made to be combined with eBUFFER_ACCESS_TYPE
Enumerator
eBUFFER_ACCESS_NATURE_DRAW
Modified by CPU and used by GPU.
eBUFFER_ACCESS_NATURE_READ
Modified by GPU and used by CPU.
eBUFFER_ACCESS_NATURE_COPY
Modified by GPU and used by GPU.
eBUFFER_ACCESS_TYPE
enum Castor3D::eBUFFER_ACCESS_TYPE : uint32_t
Buffer access types enumeration.
Author
Sylvain DOREMUS
See also
eBUFFER_ACCESS_NATURE
Remarks
Made to be combined with eBUFFER_ACCESS_NATURE
Enumerator
eBUFFER_ACCESS_TYPE_STATIC
Modified once and used many times.
eBUFFER_ACCESS_TYPE_DYNAMIC
Modified many times and used many times.
eBUFFER_ACCESS_TYPE_STREAM
Modified oncce and used at most a few times.
eBUFFER_COMPONENT
enum Castor3D::eBUFFER_COMPONENT : uint8_t
Frame buffer components enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
12/11/2012
Enumerator
eBUFFER_COMPONENT_COLOUR
eBUFFER_COMPONENT_DEPTH
eBUFFER_COMPONENT_STENCIL
eCHUNK_TYPE
enum Castor3D::eCHUNK_TYPE : uint32_t
Binary data chunk types enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
15/04/2013
Enumerator
eCHUNK_TYPE_UNKNOWN
eCHUNK_TYPE_CBSN_FILE
eCHUNK_TYPE_SAMPLER
eCHUNK_TYPE_SAMPLER_MINFILTER
eCHUNK_TYPE_SAMPLER_MAGFILTER
eCHUNK_TYPE_SAMPLER_MIPFILTER
eCHUNK_TYPE_SAMPLER_MINLOD
eCHUNK_TYPE_SAMPLER_MAXLOD
eCHUNK_TYPE_SAMPLER_LODBIAS
eCHUNK_TYPE_SAMPLER_UWRAP
eCHUNK_TYPE_SAMPLER_VWRAP
eCHUNK_TYPE_SAMPLER_WWRAP
eCHUNK_TYPE_SAMPLER_BORDER
eCHUNK_TYPE_SAMPLER_MAXANISOTROPY
eCHUNK_TYPE_SAMPLER_COLOUR
eCHUNK_TYPE_MATERIAL
eCHUNK_TYPE_MATERIAL_PASS
eCHUNK_TYPE_PASS_DIFFUSE
eCHUNK_TYPE_PASS_AMBIENT
eCHUNK_TYPE_PASS_SPECULAR
eCHUNK_TYPE_PASS_EMISSIVE
eCHUNK_TYPE_PASS_EXPONENT
eCHUNK_TYPE_PASS_ALPHA
eCHUNK_TYPE_PASS_TWOSIDED
eCHUNK_TYPE_PASS_GLSHADER
eCHUNK_TYPE_PASS_HLSHADER
eCHUNK_TYPE_SHADER_FILE
eCHUNK_TYPE_SHADER_SOURCE
eCHUNK_TYPE_SHADER_PROGRAM
eCHUNK_TYPE_SHADER_OBJECT
eCHUNK_TYPE_SHADER_OBJECT_TYPE
eCHUNK_TYPE_PROGRAM_VARIABLE
eCHUNK_TYPE_VARIABLE_TYPE
eCHUNK_TYPE_VARIABLE_COUNT
eCHUNK_TYPE_VARIABLE_VALUE
eCHUNK_TYPE_SHADER_OBJECT_ENTRY
eCHUNK_TYPE_SHADER_OBJECT_FILE
eCHUNK_TYPE_SHADER_OBJECT_SOURCE
eCHUNK_TYPE_SHADER_OBJECT_INPUT
eCHUNK_TYPE_SHADER_OBJECT_OUTPUT
eCHUNK_TYPE_SHADER_OBJECT_OUTCOUNT
eCHUNK_TYPE_PASS_TEXTURE
eCHUNK_TYPE_TEXTURE_FILE
eCHUNK_TYPE_TEXTURE_FORMAT
eCHUNK_TYPE_TEXTURE_DIMENSIONS
eCHUNK_TYPE_TEXTURE_DATA
eCHUNK_TYPE_TEXTURE_MAP
eCHUNK_TYPE_TEXTURE_ALPHA_FUNC
eCHUNK_TYPE_TEXTURE_ALPHA_BLEND
eCHUNK_TYPE_TEXTURE_ALPHA_BLEND0
eCHUNK_TYPE_TEXTURE_ALPHA_BLEND1
eCHUNK_TYPE_TEXTURE_ALPHA_BLEND2
eCHUNK_TYPE_TEXTURE_RGB_BLEND
eCHUNK_TYPE_TEXTURE_RGB_BLEND0
eCHUNK_TYPE_TEXTURE_RGB_BLEND1
eCHUNK_TYPE_TEXTURE_RGB_BLEND2
eCHUNK_TYPE_TEXTURE_COLOUR
eCHUNK_TYPE_TEXTURE_CHANNEL
eCHUNK_TYPE_TEXTURE_SAMPLER
eCHUNK_TYPE_PASS_BLEND_FUNC
eCHUNK_TYPE_SCENE
eCHUNK_TYPE_SCENE_BACKGROUND
eCHUNK_TYPE_SCENE_AMBIENT
eCHUNK_TYPE_SCENE_NODE
eCHUNK_TYPE_NODE_PARENT
eCHUNK_TYPE_NODE_POSITION
eCHUNK_TYPE_NODE_ORIENTATION
eCHUNK_TYPE_NODE_SCALE
eCHUNK_TYPE_MOVABLE_NODE
eCHUNK_TYPE_LIGHT
eCHUNK_TYPE_LIGHT_TYPE
eCHUNK_TYPE_LIGHT_COLOUR
eCHUNK_TYPE_LIGHT_INTENSITY
eCHUNK_TYPE_LIGHT_ATTENUATION
eCHUNK_TYPE_LIGHT_CUTOFF
eCHUNK_TYPE_LIGHT_EXPONENT
eCHUNK_TYPE_CAMERA
eCHUNK_TYPE_VIEWPORT
eCHUNK_TYPE_VIEWPORT_TYPE
eCHUNK_TYPE_VIEWPORT_LEFT
eCHUNK_TYPE_VIEWPORT_RIGHT
eCHUNK_TYPE_VIEWPORT_TOP
eCHUNK_TYPE_VIEWPORT_BOTTOM
eCHUNK_TYPE_VIEWPORT_NEAR
eCHUNK_TYPE_VIEWPORT_FAR
eCHUNK_TYPE_VIEWPORT_SIZE
eCHUNK_TYPE_VIEWPORT_RATIO
eCHUNK_TYPE_VIEWPORT_FOVY
eCHUNK_TYPE_GEOMETRY
eCHUNK_TYPE_GEOMETRY_MESH
eCHUNK_TYPE_GEOMETRY_MATERIAL_ID
eCHUNK_TYPE_GEOMETRY_MATERIAL_NAME
eCHUNK_TYPE_BILLBOARD
eCHUNK_TYPE_BILLBOARD_MATERIAL
eCHUNK_TYPE_BILLBOARD_DIMENSIONS
eCHUNK_TYPE_BILLBOARD_POSITION
eCHUNK_TYPE_MESH
eCHUNK_TYPE_SUBMESH
eCHUNK_TYPE_SUBMESH_TOPOLOGY
eCHUNK_TYPE_SUBMESH_VERTEX
eCHUNK_TYPE_SUBMESH_FACE
eCHUNK_TYPE_WINDOW
eCHUNK_TYPE_WINDOW_VSYNC
eCHUNK_TYPE_WINDOW_FULLSCREEN
eCHUNK_TYPE_TARGET
eCHUNK_TYPE_TARGET_FORMAT
eCHUNK_TYPE_TARGET_SAMPLES
eCHUNK_TYPE_TARGET_TECHNIQUE
eCHUNK_TYPE_TARGET_SIZE
eCHUNK_TYPE_TARGET_SCENE
eCHUNK_TYPE_TARGET_CAMERA
eCHUNK_TYPE_TARGET_STEREO
eCHUNK_TYPE_OVERLAY
eCHUNK_TYPE_OVERLAY_TYPE
eCHUNK_TYPE_OVERLAY_POSITION
eCHUNK_TYPE_OVERLAY_SIZE
eCHUNK_TYPE_OVERLAY_MATERIAL
eCHUNK_TYPE_OVERLAY_VISIBLE
eCHUNK_TYPE_OVERLAY_ZINDEX
eCHUNK_TYPE_OVERLAY_BORDER_SIZE
eCHUNK_TYPE_OVERLAY_BORDER_MATERIAL
eCHUNK_TYPE_OVERLAY_FONT
eCHUNK_TYPE_OVERLAY_CAPTION
eCHUNK_TYPE_DEPTHSTENCIL_STATE
eCHUNK_TYPE_RASTERISER_STATE
eCHUNK_TYPE_BLEND_STATE
eCHUNK_TYPE_NAME
eCHUNK_TYPE_ANIMABLE
eCHUNK_TYPE_ANIMATION
eCHUNK_TYPE_ANIM_SCALE
eCHUNK_TYPE_MOVING_BASE
eCHUNK_TYPE_MOVING_NODE
eCHUNK_TYPE_MOVING_OBJECT
eCHUNK_TYPE_MOVING_BONE
eCHUNK_TYPE_MOVING_TRANSFORM
eCHUNK_TYPE_KEYFRAME
eCHUNK_TYPE_KEYFRAME_TIME
eCHUNK_TYPE_KEYFRAME_SCALE
eCHUNK_TYPE_KEYFRAME_TRANSLATE
eCHUNK_TYPE_KEYFRAME_ROTATE
eDEPTH_FUNC
enum Castor3D::eDEPTH_FUNC : uint8_t
Depth functions enumeration.
Author
Sylvain DOREMUS
Version
0.7.0
Date
02/06/2013
Enumerator
eDEPTH_FUNC_NEVER
Never passes.
eDEPTH_FUNC_LESS
Passes if the incoming depth value is less than the stored depth value.
eDEPTH_FUNC_EQUAL
Passes if the incoming depth value is equal to the stored depth value.
eDEPTH_FUNC_LEQUAL
Passes if the incoming depth value is less than or equal to the stored depth value.
eDEPTH_FUNC_GREATER
Passes if the incoming depth value is greater than the stored depth value.
eDEPTH_FUNC_NOTEQUAL
Passes if the incoming depth value is not equal to the stored depth value.
eDEPTH_FUNC_GEQUAL
Passes if the incoming depth value is greater than or equal to the stored depth value.
eDEPTH_FUNC_ALWAYS
Always passes.
eELEMENT_TYPE
enum Castor3D::eELEMENT_TYPE : uint8_t
Element type enumeration.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
03/01/2011
Enumerator
eELEMENT_TYPE_1FLOAT
1 float (GLSL float)
eELEMENT_TYPE_2FLOATS
2 floats (GLSL vec2)
eELEMENT_TYPE_3FLOATS
3 floats (GLSL vec3)
eELEMENT_TYPE_4FLOATS
4 floats (GLSL vec4)
eELEMENT_TYPE_COLOUR
colour (uint32_t)
eELEMENT_TYPE_1INT
1 int (4 bytes each, GLSL int)
eELEMENT_TYPE_2INTS
2 ints (4 bytes each, GLSL ivec2)
eELEMENT_TYPE_3INTS
3 ints (4 bytes each, GLSL ivec3)
eELEMENT_TYPE_4INTS
4 ints (4 bytes each, GLSL ivec4)
eELEMENT_TYPE_2x2FLOATS
2x2 floats (GLSL mat2)
eELEMENT_TYPE_3x3FLOATS
3x3 floats (GLSL mat3)
eELEMENT_TYPE_4x4FLOATS
4x4 floats (GLSL mat4)
eELEMENT_USAGE
enum Castor3D::eELEMENT_USAGE : uint32_t
Element usage enumeration.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
03/01/2011
Enumerator
eELEMENT_USAGE_UNKNOWN
Position coords.
eELEMENT_USAGE_POSITION
Position coords.
eELEMENT_USAGE_NORMAL
Normal coords.
eELEMENT_USAGE_TANGENT
Tangent coords.
eELEMENT_USAGE_BITANGENT
Bitangent coords.
eELEMENT_USAGE_DIFFUSE
Diffuse colour.
eELEMENT_USAGE_TEXCOORDS
Texture coordinates.
eELEMENT_USAGE_BONE_IDS0
Bone IDs 0.
eELEMENT_USAGE_BONE_IDS1
Bone IDs 1.
eELEMENT_USAGE_BONE_WEIGHTS0
Bone weights 0.
eELEMENT_USAGE_BONE_WEIGHTS1
Bone weights 1.
eELEMENT_USAGE_TRANSFORM
Instantiation matrix.
eEVENT_TYPE
enum Castor3D::eEVENT_TYPE : uint8_t
Frame Event Type enumeration.
Author
Sylvain DOREMUS
Enumerator
eEVENT_TYPE_PRE_RENDER
This kind of event happens before any render, device context is active (so be fast !!)
eEVENT_TYPE_POST_RENDER
This kind of event happens after the buffer' swap.
eFACE
enum Castor3D::eFACE : uint8_t
Faces orientations enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
23/05/2013
Enumerator
eFACE_NONE
No face.
eFACE_FRONT
Front face.
eFACE_BACK
Back face.
eFACE_FRONT_AND_BACK
Back and front faces.
eFILL_MODE
enum Castor3D::eFILL_MODE : uint8_t
Polygon rasterisation modes enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
23/05/2013
Enumerator
eFILL_MODE_POINT
Polygon vertices that are marked as the start of a boundary edge are drawn as points.
eFILL_MODE_LINE
Boundary edges of the polygon are drawn as line segments.
eFILL_MODE_SOLID
The interior of the polygon is filled.
eFRAME_VARIABLE_TYPE
enum Castor3D::eFRAME_VARIABLE_TYPE : uint8_t
Supported variables full type enumeration.
Author
Sylvain DOREMUS
Enumerator
eFRAME_VARIABLE_TYPE_BOOL
eFRAME_VARIABLE_TYPE_INT
eFRAME_VARIABLE_TYPE_UINT
eFRAME_VARIABLE_TYPE_FLOAT
eFRAME_VARIABLE_TYPE_DOUBLE
eFRAME_VARIABLE_TYPE_SAMPLER
eFRAME_VARIABLE_TYPE_VEC2B
eFRAME_VARIABLE_TYPE_VEC3B
eFRAME_VARIABLE_TYPE_VEC4B
eFRAME_VARIABLE_TYPE_VEC2I
eFRAME_VARIABLE_TYPE_VEC3I
eFRAME_VARIABLE_TYPE_VEC4I
eFRAME_VARIABLE_TYPE_VEC2UI
eFRAME_VARIABLE_TYPE_VEC3UI
eFRAME_VARIABLE_TYPE_VEC4UI
eFRAME_VARIABLE_TYPE_VEC2F
eFRAME_VARIABLE_TYPE_VEC3F
eFRAME_VARIABLE_TYPE_VEC4F
eFRAME_VARIABLE_TYPE_VEC2D
eFRAME_VARIABLE_TYPE_VEC3D
eFRAME_VARIABLE_TYPE_VEC4D
eFRAME_VARIABLE_TYPE_MAT2X2B
eFRAME_VARIABLE_TYPE_MAT2X3B
eFRAME_VARIABLE_TYPE_MAT2X4B
eFRAME_VARIABLE_TYPE_MAT3X2B
eFRAME_VARIABLE_TYPE_MAT3X3B
eFRAME_VARIABLE_TYPE_MAT3X4B
eFRAME_VARIABLE_TYPE_MAT4X2B
eFRAME_VARIABLE_TYPE_MAT4X3B
eFRAME_VARIABLE_TYPE_MAT4X4B
eFRAME_VARIABLE_TYPE_MAT2X2I
eFRAME_VARIABLE_TYPE_MAT2X3I
eFRAME_VARIABLE_TYPE_MAT2X4I
eFRAME_VARIABLE_TYPE_MAT3X2I
eFRAME_VARIABLE_TYPE_MAT3X3I
eFRAME_VARIABLE_TYPE_MAT3X4I
eFRAME_VARIABLE_TYPE_MAT4X2I
eFRAME_VARIABLE_TYPE_MAT4X3I
eFRAME_VARIABLE_TYPE_MAT4X4I
eFRAME_VARIABLE_TYPE_MAT2X2UI
eFRAME_VARIABLE_TYPE_MAT2X3UI
eFRAME_VARIABLE_TYPE_MAT2X4UI
eFRAME_VARIABLE_TYPE_MAT3X2UI
eFRAME_VARIABLE_TYPE_MAT3X3UI
eFRAME_VARIABLE_TYPE_MAT3X4UI
eFRAME_VARIABLE_TYPE_MAT4X2UI
eFRAME_VARIABLE_TYPE_MAT4X3UI
eFRAME_VARIABLE_TYPE_MAT4X4UI
eFRAME_VARIABLE_TYPE_MAT2X2F
eFRAME_VARIABLE_TYPE_MAT2X3F
eFRAME_VARIABLE_TYPE_MAT2X4F
eFRAME_VARIABLE_TYPE_MAT3X2F
eFRAME_VARIABLE_TYPE_MAT3X3F
eFRAME_VARIABLE_TYPE_MAT3X4F
eFRAME_VARIABLE_TYPE_MAT4X2F
eFRAME_VARIABLE_TYPE_MAT4X3F
eFRAME_VARIABLE_TYPE_MAT4X4F
eFRAME_VARIABLE_TYPE_MAT2X2D
eFRAME_VARIABLE_TYPE_MAT2X3D
eFRAME_VARIABLE_TYPE_MAT2X4D
eFRAME_VARIABLE_TYPE_MAT3X2D
eFRAME_VARIABLE_TYPE_MAT3X3D
eFRAME_VARIABLE_TYPE_MAT3X4D
eFRAME_VARIABLE_TYPE_MAT4X2D
eFRAME_VARIABLE_TYPE_MAT4X3D
eFRAME_VARIABLE_TYPE_MAT4X4D
eFRAMEBUFFER_MODE
enum Castor3D::eFRAMEBUFFER_MODE : uint8_t
Frame buffer binding modes enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
12/11/2012
Enumerator
eFRAMEBUFFER_MODE_CONFIG
Frame buffer is bound for configuration.
eFRAMEBUFFER_MODE_AUTOMATIC
Frame buffer is bound and FrameBuffer::SetDrawBuffers is called automatically.
eFRAMEBUFFER_MODE_MANUAL
Frame buffer is bound and user must call FrameBuffer::SetDrawBuffers if he wants.
eFRAMEBUFFER_TARGET
enum Castor3D::eFRAMEBUFFER_TARGET : uint8_t
Frame buffer binding targets enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
12/11/2012
Enumerator
eFRAMEBUFFER_TARGET_DRAW
Frame buffer is bound as a target for draws.
eFRAMEBUFFER_TARGET_READ
Frame buffer is bound as a target for reads.
eFRAMEBUFFER_TARGET_BOTH
Frame buffer is bound as a target for reads and draws.
eFRUSTUM_PLANE
enum Castor3D::eFRUSTUM_PLANE : uint8_t
Frustum view planes enumeration.
Author
Sylvain DOREMUS
Date
10/06/2013
Version
0.7.0
Enumerator
eFRUSTUM_PLANE_NEAR
Near plane.
eFRUSTUM_PLANE_FAR
Far plane.
eFRUSTUM_PLANE_LEFT
Left plane.
eFRUSTUM_PLANE_RIGHT
Right plane.
eFRUSTUM_PLANE_TOP
Top plane.
eFRUSTUM_PLANE_BOTTOM
Bottom plane.
eHALIGN
enum Castor3D::eHALIGN
Horizontal alignments for text overlays.
Author
Sylvain DOREMUS
Date
23/09/2015
Version
0.8.0
Enumerator
eHALIGN_LEFT
Aligned on the left.
eHALIGN_CENTER
Centered horizontally.
eHALIGN_RIGHT
Aligned on the right.
eINTERPOLATION_FILTER
enum Castor3D::eINTERPOLATION_FILTER : uint8_t
Texture interpolation filters enumeration.
Author
Sylvain DOREMUS
Enumerator
eINTERPOLATION_FILTER_MIN
eINTERPOLATION_FILTER_MAG
eINTERPOLATION_FILTER_MIP
eINTERPOLATION_FILTER_COUNT
eINTERPOLATION_MODE
enum Castor3D::eINTERPOLATION_MODE : uint8_t
Texture filter interpolation modes enumeration.
Author
Sylvain DOREMUS
Enumerator
eINTERPOLATION_MODE_UNDEFINED
eINTERPOLATION_MODE_NEAREST
eINTERPOLATION_MODE_LINEAR
eINTERPOLATOR_MODE
enum Castor3D::eINTERPOLATOR_MODE
Interpolation modes enumeration.
Author
Sylvain DOREMUS
Version
0.1
Date
09/02/2010
Enumerator
eINTERPOLATOR_MODE_NONE
No interpolation.
eINTERPOLATOR_MODE_LINEAR
Linear mode.
eLIGHT_TYPE
enum Castor3D::eLIGHT_TYPE : uint8_t
Light types enumeration.
Author
Sylvain DOREMUS
Enumerator
eLIGHT_TYPE_DIRECTIONAL
Directional light type.
eLIGHT_TYPE_POINT
Point light type.
eLIGHT_TYPE_SPOT
Spot light type.
eMESH_TYPE
enum Castor3D::eMESH_TYPE : uint8_t
Mesh type enumeration.
Author
Sylvain DOREMUS
Enumerator
eMESH_TYPE_CUSTOM
Custom mesh type => User defined vertex, imported mesh...
eMESH_TYPE_CONE
Cone mesh type.
eMESH_TYPE_CYLINDER
Cylinder mesh type.
eMESH_TYPE_SPHERE
Rectangular faces sphere mesh type.
eMESH_TYPE_CUBE
Cube mesh type.
eMESH_TYPE_TORUS
Torus mesh type.
eMESH_TYPE_PLANE
Plane mesh type.
eMESH_TYPE_ICOSAHEDRON
Triangular faces sphere mesh type.
eMESH_TYPE_PROJECTION
Projection mesh type.
eMOVABLE_TYPE
enum Castor3D::eMOVABLE_TYPE : uint8_t
Movable object types enumerator.
Author
Sylvain DOREMUS
Version
0.1
Date
09/02/2010
Remarks
There are four movable object types : camera, geometry, light and billboard.
Enumerator
eMOVABLE_TYPE_CAMERA
eMOVABLE_TYPE_GEOMETRY
eMOVABLE_TYPE_LIGHT
eMOVABLE_TYPE_BILLBOARD
eMTXMODE
enum Castor3D::eMTXMODE : uint8_t
Matrix modes enumeration.
Author
Sylvain DOREMUS
Enumerator
eMTXMODE_PROJECTION
eMTXMODE_MODEL
Object to World transform.
eMTXMODE_VIEW
World to Eye transform.
eMTXMODE_TEXTURE0
Texture transforms.
eMTXMODE_TEXTURE1
Texture transforms.
eMTXMODE_TEXTURE2
Texture transforms.
eMTXMODE_TEXTURE3
Texture transforms.
eMTXMODE_TEXTURE4
Texture transforms.
eMTXMODE_TEXTURE5
Texture transforms.
eMTXMODE_TEXTURE6
Texture transforms.
eMTXMODE_TEXTURE7
Texture transforms.
eMTXMODE_TEXTURE8
Texture transforms.
eMTXMODE_TEXTURE9
Texture transforms.
eMTXMODE_TEXTURE10
Texture transforms.
eMTXMODE_TEXTURE11
Texture transforms.
eMTXMODE_TEXTURE12
Texture transforms.
eMTXMODE_TEXTURE13
Texture transforms.
eMTXMODE_TEXTURE14
Texture transforms.
eMTXMODE_TEXTURE15
Texture transforms.
eMTXMODE_TEXTURE16
Texture transforms.
eMTXMODE_TEXTURE17
Texture transforms.
eMTXMODE_TEXTURE18
Texture transforms.
eMTXMODE_TEXTURE19
Texture transforms.
eMTXMODE_TEXTURE20
Texture transforms.
eMTXMODE_TEXTURE21
Texture transforms.
eMTXMODE_TEXTURE22
Texture transforms.
eMTXMODE_TEXTURE23
Texture transforms.
eMTXMODE_TEXTURE24
Texture transforms.
eMTXMODE_TEXTURE25
Texture transforms.
eMTXMODE_TEXTURE26
Texture transforms.
eMTXMODE_TEXTURE27
Texture transforms.
eMTXMODE_TEXTURE28
Texture transforms.
eMTXMODE_TEXTURE29
Texture transforms.
eMTXMODE_TEXTURE30
Texture transforms.
eMTXMODE_TEXTURE31
Texture transforms.
eNORMAL
enum Castor3D::eNORMAL : uint8_t
Enumerates supported normal generation.
Author
Sylvain DOREMUS
Enumerator
eNORMAL_FLAT
Flat (face) normals.
eNORMAL_SMOOTH
Smooth normals.
eOVERLAY_TYPE
enum Castor3D::eOVERLAY_TYPE : uint8_t
Overlay types enumeration.
Author
Sylvain DOREMUS
Enumerator
eOVERLAY_TYPE_PANEL
eOVERLAY_TYPE_BORDER_PANEL
eOVERLAY_TYPE_TEXT
ePLUGIN_TYPE
enum Castor3D::ePLUGIN_TYPE : uint8_t
Plugin types enumeration.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
03/01/2011
Enumerator
ePLUGIN_TYPE_RENDERER
Renderer plug-in.
ePLUGIN_TYPE_IMPORTER
Importer plug-in.
ePLUGIN_TYPE_DIVIDER
Mesh Divider plug-in.
ePLUGIN_TYPE_GENERATOR
Procedural generator.
ePLUGIN_TYPE_TECHNIQUE
Render technique plug-in.
ePLUGIN_TYPE_POSTFX
Post effect plug-in.
ePLUGIN_TYPE_GENERIC
Generic plug-in.
ePROGRAM_FLAG
enum Castor3D::ePROGRAM_FLAG : uint32_t
Flags to use when looking for an automatically generated program.
Author
Sylvain DOREMUS
Date
20/11/13
Version
0.7.0.0
Enumerator
ePROGRAM_FLAG_INSTANCIATION
Program using instanciation.
ePROGRAM_FLAG_SKINNING
Program using skeleton animations.
ePROGRAM_FLAG_BILLBOARDS
Program used by billboards.
ePROGRAM_STATUS
enum Castor3D::ePROGRAM_STATUS : uint8_t
Program status enumeration.
Author
Sylvain DOREMUS
Date
22/08/2012
Version
0.7.0.0
Enumerator
ePROGRAM_STATUS_NOTLINKED
ePROGRAM_STATUS_ERROR
ePROGRAM_STATUS_LINKED
eQUERY_INFO
enum Castor3D::eQUERY_INFO : uint32_t
GPU query supported informations enumeration.
Author
Sylvain DOREMUS
Version
0.8.0
Date
16/03/2016
Enumerator
eQUERY_INFO_RESULT
eQUERY_INFO_RESULT_AVAILABLE
eQUERY_INFO_RESULT_NO_WAIT
eQUERY_TYPE
enum Castor3D::eQUERY_TYPE : uint32_t
GPU query supported types enumeration.
Author
Sylvain DOREMUS
Version
0.8.0
Date
16/03/2016
Enumerator
eQUERY_TYPE_TIME_ELAPSED
eQUERY_TYPE_SAMPLES_PASSED
eQUERY_TYPE_ANY_SAMPLES_PASSED
eQUERY_TYPE_PRIMITIVES_GENERATED
eQUERY_TYPE_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN
eQUERY_TYPE_ANY_SAMPLES_PASSED_CONSERVATIVE
eQUERY_TYPE_TIMESTAMP
eRENDERER_TYPE
enum Castor3D::eRENDERER_TYPE : int8_t
Supported renderers enumeration.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
01/04/2011
Enumerator
eRENDERER_TYPE_UNDEFINED
No Renderer selected.
eRENDERER_TYPE_OPENGL
OpenGl Renderer.
eRGB_BLEND_FUNC
enum Castor3D::eRGB_BLEND_FUNC : uint8_t
RGB blending functions enumeration.
Author
Sylvain DOREMUS
Enumerator
eRGB_BLEND_FUNC_NONE
No blend
eRGB_BLEND_FUNC_FIRST_ARG
Arg0
eRGB_BLEND_FUNC_ADD
Arg0 + Arg1
eRGB_BLEND_FUNC_ADD_SIGNED
Arg0 + Arg1 - 0.5
eRGB_BLEND_FUNC_MODULATE
Arg0 x Arg1
eRGB_BLEND_FUNC_INTERPOLATE
Arg0 Arg2 + Arg1 (1 - Arg2)
eRGB_BLEND_FUNC_SUBTRACT
Arg0 - Arg1
eRGB_BLEND_FUNC_DOT3_RGB
4 (((Arg0.r - 0.5) (Arg1.r - 0.5)) + ((Arg0.g - 0.5) (Arg1.g - 0.5)) + ((Arg0.b - 0.5) (Arg1.b - 0.5)))
eRGB_BLEND_FUNC_DOT3_RGBA
4 (((Arg0.r - 0.5) (Arg1.r - 0.5)) + ((Arg0.g - 0.5) (Arg1.g - 0.5)) + ((Arg0.b - 0.5) (Arg1.b - 0.5)) + ((Arg0.a - 0.5) (Arg1.a - 0.5)))
eSECTION
enum Castor3D::eSECTION : uint32_t
Scene file sections Enum.
The enumeration which defines all the sections and subsections of a scene file
Enumerator
eSECTION_ROOT
eSECTION_SCENE
eSECTION_WINDOW
eSECTION_SAMPLER
eSECTION_CAMERA
eSECTION_VIEWPORT
eSECTION_LIGHT
eSECTION_NODE
eSECTION_OBJECT
eSECTION_OBJECT_MATERIALS
eSECTION_FONT
eSECTION_PANEL_OVERLAY
eSECTION_BORDER_PANEL_OVERLAY
eSECTION_TEXT_OVERLAY
eSECTION_MESH
eSECTION_SUBMESH
eSECTION_MATERIAL
eSECTION_PASS
eSECTION_TEXTURE_UNIT
eSECTION_RENDER_TARGET
eSECTION_GLSL_SHADER
eSECTION_SHADER_PROGRAM
eSECTION_SHADER_UBO
eSECTION_SHADER_UBO_VARIABLE
eSECTION_BILLBOARD
eSECTION_BILLBOARD_LIST
eSECTION_ANIMGROUP
eSECTION_ANIMATED_OBJECT
eSECTION_ANIMATION
eSHADER_LANGUAGE
enum Castor3D::eSHADER_LANGUAGE : uint8_t
Enumeration of existing shader lnaguages.
Author
Sylvain DOREMUS
Enumerator
eSHADER_LANGUAGE_GLSL
eSHADER_LANGUAGE_AUTO
eSHADER_MODEL
enum Castor3D::eSHADER_MODEL : uint8_t
Enumeration of existing shader models.
Author
Sylvain DOREMUS
Enumerator
eSHADER_MODEL_1
Vertex shaders.
eSHADER_MODEL_2
Pixel shaders.
eSHADER_MODEL_3
Geometry shaders.
eSHADER_MODEL_4
Tessellation shaders.
eSHADER_MODEL_5
Compute shaders.
eSHADER_STATUS
enum Castor3D::eSHADER_STATUS : uint8_t
Shader status enueration.
Author
Sylvain DOREMUS
Date
22/08/2012
Version
0.7.0.0
Enumerator
eSHADER_STATUS_DONTEXIST
eSHADER_STATUS_NOTCOMPILED
eSHADER_STATUS_ERROR
eSHADER_STATUS_COMPILED
eSHADER_TYPE
enum Castor3D::eSHADER_TYPE : int8_t
Shader object types enumeration.
Author
Sylvain DOREMUS
Enumerator
eSHADER_TYPE_NONE
eSHADER_TYPE_VERTEX
eSHADER_TYPE_HULL
eSHADER_TYPE_DOMAIN
eSHADER_TYPE_GEOMETRY
eSHADER_TYPE_PIXEL
eSHADER_TYPE_COMPUTE
eSTENCIL_FUNC
enum Castor3D::eSTENCIL_FUNC : uint8_t
Stencil functions enumeration.
Author
Sylvain DOREMUS
Version
0.7.0
Date
02/06/2013
Enumerator
eSTENCIL_FUNC_NEVER
Never passes.
eSTENCIL_FUNC_LESS
Passes if the incoming stencil value is less than the stored stencil value.
eSTENCIL_FUNC_EQUAL
Passes if the incoming stencil value is equal to the stored stencil value.
eSTENCIL_FUNC_LEQUAL
Passes if the incoming stencil value is less than or equal to the stored stencil value.
eSTENCIL_FUNC_GREATER
Passes if the incoming stencil value is greater than the stored stencil value.
eSTENCIL_FUNC_NOTEQUAL
Passes if the incoming stencil value is not equal to the stored stencil value.
eSTENCIL_FUNC_GEQUAL
Passes if the incoming stencil value is greater than or equal to the stored stencil value.
eSTENCIL_FUNC_ALWAYS
Always passes.
eSTENCIL_OP
enum Castor3D::eSTENCIL_OP : uint8_t
Stencil functions enumeration.
Author
Sylvain DOREMUS
Version
0.7.0
Date
02/06/2013
Enumerator
eSTENCIL_OP_KEEP
Keeps the current value.
eSTENCIL_OP_ZERO
Sets the stencil buffer value to 0.
eSTENCIL_OP_REPLACE
Sets the stencil buffer value by the one given.
eSTENCIL_OP_INCR
Increments the current stencil buffer value. Clamps to the maximum representable unsigned value.
eSTENCIL_OP_INCR_WRAP
Increments the current stencil buffer value. Wraps stencil buffer value to zero when incrementing the maximum representable unsigned value.
eSTENCIL_OP_DECR
Decrements the current stencil buffer value. Clamps to 0.
eSTENCIL_OP_DECR_WRAP
Decrements the current stencil buffer value. Wraps stencil buffer value to the maximum representable unsigned value when decrementing a stencil buffer value of zero.
eSTENCIL_OP_INVERT
Bitwise inverts the current stencil buffer value.
eTARGET_TYPE
enum Castor3D::eTARGET_TYPE : uint8_t
RenderTarget supported types.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
19/10/2011
Enumerator
eTARGET_TYPE_WINDOW
eTARGET_TYPE_TEXTURE
eTEXT_TEXTURING_MODE
enum Castor3D::eTEXT_TEXTURING_MODE
Text texturing modes, handles the way textures are appied to text overlays.
Author
Sylvain DOREMUS
Date
26/03/2016
Enumerator
eTEXT_TEXTURING_MODE_LETTER
The texture is repeated on each character of the text.
eTEXT_TEXTURING_MODE_TEXT
The texture is applied on the whole text.
eTEXT_WRAPPING_MODE
enum Castor3D::eTEXT_WRAPPING_MODE
Text wrapping modes, handles the way text is cut when it overflows the overlay width.
Author
Sylvain DOREMUS
Date
28/11/2014
Enumerator
eTEXT_WRAPPING_MODE_NONE
The text is cut.
eTEXT_WRAPPING_MODE_BREAK
The text jumps to next line.
eTEXT_WRAPPING_MODE_BREAK_WORDS
The text jumps to next line without cutting words.
eTEXTURE_BASE_TYPE
enum Castor3D::eTEXTURE_BASE_TYPE : uint8_t
Texture types enumeration.
Author
Sylvain DOREMUS
Enumerator
eTEXTURE_BASE_TYPE_STATIC
eTEXTURE_BASE_TYPE_DYNAMIC
eTEXTURE_CHANNEL
enum Castor3D::eTEXTURE_CHANNEL : uint32_t
Texture channels enumeration.
Author
Sylvain DOREMUS
Enumerator
eTEXTURE_CHANNEL_COLOUR
Colour map.
eTEXTURE_CHANNEL_DIFFUSE
Diffuse map.
eTEXTURE_CHANNEL_NORMAL
Normal map.
eTEXTURE_CHANNEL_OPACITY
Opacity map.
eTEXTURE_CHANNEL_SPECULAR
Specular map.
eTEXTURE_CHANNEL_HEIGHT
Height map.
eTEXTURE_CHANNEL_AMBIENT
Ambient map.
eTEXTURE_CHANNEL_GLOSS
Gloss map.
eTEXTURE_CHANNEL_EMISSIVE
Emissive map.
eTEXTURE_CHANNEL_ALL
Mask for all the texture channels.
eTEXTURE_CHANNEL_TEXT
Not really a texture channel (it is out of eTEXTURE_CHANNEL_ALL), used to tell we want text overlay shader source
eTEXTURE_MAP_MODE
enum Castor3D::eTEXTURE_MAP_MODE : uint8_t
Texture mapping modes enumeration.
Author
Sylvain DOREMUS
Enumerator
eTEXTURE_MAP_MODE_NONE
Usual map mode.
eTEXTURE_MAP_MODE_REFLECTION
Reflexion map mode.
eTEXTURE_MAP_MODE_SPHERE
Sphere map mode.
eTEXTURE_TARGET
enum Castor3D::eTEXTURE_TARGET : uint8_t
Texture targets enumeration.
Author
Sylvain DOREMUS
Enumerator
eTEXTURE_TARGET_1D
1 dimension texture
eTEXTURE_TARGET_2D
2 dimensions texture
eTEXTURE_TARGET_3D
3 dimensions texture
eTEXTURE_TARGET_LAYER
Layer texture.
eTEXTURE_TYPE
enum Castor3D::eTEXTURE_TYPE : uint8_t
Texture dimensions enumeration.
Author
Sylvain DOREMUS
Enumerator
eTEXTURE_TYPE_BUFFER
1 dimension texture buffer, used to store data.
eTEXTURE_TYPE_1D
1 dimension textures => one coordinate => U mapping
eTEXTURE_TYPE_1DARRAY
1 dimension textures array => one coordinate => U mapping
eTEXTURE_TYPE_2D
2 dimensions textures => two coordinates => UV mapping
eTEXTURE_TYPE_2DARRAY
2 dimensions textures array => two coordinates => UV mapping
eTEXTURE_TYPE_2DMS
2 dimensions textures with multisample support => two coordinates => UV mapping
eTEXTURE_TYPE_2DMSARRAY
2 dimensions textures array with multisample support => two coordinates => UV mapping
eTEXTURE_TYPE_3D
3 dimensions textures => three coordinates => UVW mapping
eTEXTURE_TYPE_CUBE
Cube texture.
eTEXTURE_TYPE_CUBEARRAY
Cube textures array.
eTEXTURE_UVW
enum Castor3D::eTEXTURE_UVW : uint8_t
Texture UVW enumeration.
Author
Sylvain DOREMUS
Enumerator
eTEXTURE_UVW_U
eTEXTURE_UVW_V
eTEXTURE_UVW_W
eTONE_MAPPING_TYPE
enum Castor3D::eTONE_MAPPING_TYPE : uint8_t
Tone mapping type enumeration.
Author
Sylvain DOREMUS
Version
0.8.0
Date
10/03/2016
Enumerator
eTONE_MAPPING_TYPE_LINEAR
eTONE_MAPPING_TYPE_REINHARD
eTONE_MAPPING_TYPE_HAARM_PETER_DUIKER
eTONE_MAPPING_TYPE_HEJL_BURGESS_DAWSON
eTONE_MAPPING_TYPE_HABLE
eTOPOLOGY
enum Castor3D::eTOPOLOGY : uint8_t
Primitive draw types enumeration.
Author
Sylvain DOREMUS
Enumerator
eTOPOLOGY_POINTS
Display textured points.
eTOPOLOGY_LINES
Display textured edges.
eTOPOLOGY_LINE_LOOP
Display textured edge loops.
eTOPOLOGY_LINE_STRIP
Display textured edge strips.
eTOPOLOGY_TRIANGLES
Display textured triangles.
eTOPOLOGY_TRIANGLE_STRIPS
Display triangle strips.
eTOPOLOGY_TRIANGLE_FAN
Display triangle fan.
eTOPOLOGY_QUADS
Display quads.
eTOPOLOGY_QUAD_STRIPS
Display quad strips.
eTOPOLOGY_POLYGON
Display quad strips.
eVALIGN
enum Castor3D::eVALIGN
Vertical alignments for text overlays.
Author
Sylvain DOREMUS
Date
23/09/2015
Version
0.8.0
Enumerator
eVALIGN_TOP
Aligned on the top.
eVALIGN_CENTER
Centered vertically.
eVALIGN_BOTTOM
Aligned on the bottom.
eVARIABLE_TYPE
enum Castor3D::eVARIABLE_TYPE : uint8_t
Supported variables dimensions enumeration.
Author
Sylvain DOREMUS
Enumerator
eVARIABLE_TYPE_ONE
One variable.
eVARIABLE_TYPE_VEC1
1 variable array
eVARIABLE_TYPE_VEC2
2 variables array
eVARIABLE_TYPE_VEC3
3 variables array
eVARIABLE_TYPE_VEC4
4 variables array
eVARIABLE_TYPE_MAT1
1x1 matrix
eVARIABLE_TYPE_MAT2X2
2x2 matrix
eVARIABLE_TYPE_MAT2X3
2x3 matrix
eVARIABLE_TYPE_MAT2X4
2x4 matrix
eVARIABLE_TYPE_MAT3X2
3x2 matrix
eVARIABLE_TYPE_MAT3X3
3x3 matrix
eVARIABLE_TYPE_MAT3X4
3x4 matrix
eVARIABLE_TYPE_MAT4X2
4x2 matrix
eVARIABLE_TYPE_MAT4X3
4x3 matrix
eVARIABLE_TYPE_MAT4X4
4x4 matrix
eVIEWPORT_TYPE
enum Castor3D::eVIEWPORT_TYPE : uint8_t
The viewport projection types enumeration.
Author
Sylvain DOREMUS
Enumerator
eVIEWPORT_TYPE_ORTHO
eVIEWPORT_TYPE_PERSPECTIVE
eVIEWPORT_TYPE_FRUSTUM
eWRAP_MODE
enum Castor3D::eWRAP_MODE : uint8_t
Texture wrap modes enumeration.
Author
Sylvain DOREMUS
Enumerator
eWRAP_MODE_REPEAT
eWRAP_MODE_MIRRORED_REPEAT
eWRAP_MODE_CLAMP_TO_BORDER
eWRAP_MODE_CLAMP_TO_EDGE
eWRITING_MASK
enum Castor3D::eWRITING_MASK : uint8_t
Wrinting masks enumeration.
Author
Sylvain DOREMUS
Version
0.7.0
Date
02/06/2013
Enumerator
eWRITING_MASK_ZERO
Writing disabled.
eWRITING_MASK_ALL
Writing enabled.
Function Documentation
DECLARE_ARRAY() [1/3]
Castor3D::DECLARE_ARRAY (RendererPluginSPtr , eRENDERER_TYPE_COUNT , RendererPtr)
DECLARE_ARRAY() [2/3]
Castor3D::DECLARE_ARRAY (PluginStrMap , ePLUGIN_TYPE_COUNT , PluginStrMap)
DECLARE_ARRAY() [3/3]
Castor3D::DECLARE_ARRAY (DynamicLibraryPtrPathMap , ePLUGIN_TYPE_COUNT , DynamicLibraryPtrPathMap)
DECLARE_LIST() [1/4]
Castor3D::DECLARE_LIST (VertexSPtr , VertexPtr)
Vertex pointer list.
DECLARE_LIST() [2/4]
Castor3D::DECLARE_LIST (FrameVariableLinkSPtr , VariableLinkPtr)
DECLARE_LIST() [3/4]
Castor3D::DECLARE_LIST (FrameVariableSPtr , FrameVariablePtr)
DECLARE_LIST() [4/4]
Castor3D::DECLARE_LIST (FrameVariableBufferSPtr , FrameVariableBufferPtr)
DECLARE_MAP() [1/35]
Castor3D::DECLARE_MAP (Castor::String , CameraSPtr , CameraPtrStr)
Camera pointer map, sorted by name.
DECLARE_MAP() [2/35]
Castor3D::DECLARE_MAP (Castor::String , SceneSPtr , ScenePtrStr)
Scene pointer map, sorted by name.
DECLARE_MAP() [3/35]
Castor3D::DECLARE_MAP (Castor::String , SceneNodeSPtr , SceneNodePtrStr)
SceneNode pointer map, sorted by name.
DECLARE_MAP() [4/35]
Castor3D::DECLARE_MAP (Castor::String , LightSPtr , LightPtrStr)
Map of lights, sorted by name.
DECLARE_MAP() [5/35]
Castor3D::DECLARE_MAP (int , LightSPtr , LightPtrInt)
Map of lights, sorted by index.
DECLARE_MAP() [6/35]
Castor3D::DECLARE_MAP (Castor::String , AnimatedObjectGroupSPtr , AnimatedObjectGroupPtrStr)
AnimatedObjectGroup pointer map, sorted by name.
DECLARE_MAP() [7/35]
Castor3D::DECLARE_MAP (Castor::String , AnimationSPtr , AnimationPtrStr)
Animation pointer map, sorted by name.
DECLARE_MAP() [8/35]
Castor3D::DECLARE_MAP (Castor::String , AnimatedObjectSPtr , AnimatedObjectPtrStr)
AnimatedObject pointer map, sorted by name.
DECLARE_MAP() [9/35]
Castor3D::DECLARE_MAP (SubmeshSPtr , GeometryRenderNodeArray , SubmeshRenderNodes)
Submesh sorted GeometryRenderNodeArray.
DECLARE_MAP() [10/35]
Castor3D::DECLARE_MAP (Castor::String , AnimationObjectSPtr , AnimationObjectPtrStr)
MovingObject pointer map, sorted by name.
DECLARE_MAP() [11/35]
Castor3D::DECLARE_MAP (BillboardListSPtr , BillboardRenderNodeArray , BillboardRenderNodes)
Billboard sorted BillboardRenderNodeArray.
DECLARE_MAP() [12/35]
Castor3D::DECLARE_MAP (Castor::String , MeshSPtr , MeshPtrStr)
Mesh pointer array.
DECLARE_MAP() [13/35]
Castor3D::DECLARE_MAP (Castor::String , MovableObjectSPtr , MovableObjectPtrStr)
MovableObject pointer map, sorted by name.
DECLARE_MAP() [14/35]
Castor3D::DECLARE_MAP (Castor::String , GeometrySPtr , GeometryPtrStr)
Geometry pointer map, sorted by name.
DECLARE_MAP() [15/35]
Castor3D::DECLARE_MAP (uint32_t , int , IntUInt)
DECLARE_MAP() [16/35]
Castor3D::DECLARE_MAP (Castor::String , SubmeshSPtr , SubmeshPtrStr)
DECLARE_MAP() [17/35]
Castor3D::DECLARE_MAP (Castor::String , int , IntStr)
DECLARE_MAP() [18/35]
Castor3D::DECLARE_MAP (Castor::String , OverlaySPtr , OverlayPtrStr)
DECLARE_MAP() [19/35]
Castor3D::DECLARE_MAP (ShaderProgramSPtr , SubmeshRenderNodesByPassMap , SubmeshRenderNodesByProgram)
Shader program sorted SubmeshRenderNodesMap map.
DECLARE_MAP() [20/35]
Castor3D::DECLARE_MAP (ShaderProgramSPtr , BillboardRenderNodesByPassMap , BillboardRenderNodesByProgram)
Shader program sorted BillboardRenderNodesMap map.
DECLARE_MAP() [21/35]
Castor3D::DECLARE_MAP (Castor::String , MaterialSPtr , MaterialPtrStr)
Material pointer map, sorted by name.
DECLARE_MAP() [22/35]
Castor3D::DECLARE_MAP (uint32_t , MaterialSPtr , MaterialPtrUInt)
Material pointer map.
DECLARE_MAP() [23/35]
Castor3D::DECLARE_MAP (ShaderProgram * , ProgramLinksSPtr , LinksPtrListProgram)
DECLARE_MAP() [24/35]
Castor3D::DECLARE_MAP (Castor::String , FrameVariableWPtr , FrameVariablePtrStr)
DECLARE_MAP() [25/35]
Castor3D::DECLARE_MAP (Castor::String , FrameVariableBufferWPtr , FrameVariableBufferPtrStr)
DECLARE_MAP() [26/35]
Castor3D::DECLARE_MAP (eSHADER_TYPE , FrameVariableBufferWPtr , FrameVariableBufferPtrShader)
DECLARE_MAP() [27/35]
Castor3D::DECLARE_MAP (Castor::String , FrameListenerSPtr , FrameListenerPtrStr)
FrameListener pointer map, sorted by name.
DECLARE_MAP() [28/35]
Castor3D::DECLARE_MAP (uint32_t , RenderWindowSPtr , RenderWindow)
RenderWindow pointer map, sorted by index.
DECLARE_MAP() [29/35]
Castor3D::DECLARE_MAP (Castor::String , PluginBaseSPtr , PluginStr)
Plugin map, sorted by name.
DECLARE_MAP() [30/35]
Castor3D::DECLARE_MAP (int , Castor::String , StrInt)
DECLARE_MAP() [31/35]
Castor3D::DECLARE_MAP (Castor::Path , Castor::DynamicLibrarySPtr , DynamicLibraryPtrPath)
DECLARE_MAP() [32/35]
Castor3D::DECLARE_MAP (Castor::Path , ePLUGIN_TYPE , PluginTypePath)
DECLARE_MAP() [33/35]
Castor3D::DECLARE_MAP (Castor::String , BillboardListSPtr , BillboardListStr)
DECLARE_MAP() [34/35]
Castor3D::DECLARE_MAP (RenderWindow * , ContextSPtr , ContextPtr)
DECLARE_MAP() [35/35]
Castor3D::DECLARE_MAP (std::thread::id , ContextPtrMap , ContextPtrMapId)
DECLARE_MULTIMAP() [1/2]
Castor3D::DECLARE_MULTIMAP (double , GeometryRenderNode , GeometryRenderNodeByDistance)
Multimap of RenderNodes sorted by distance.
DECLARE_MULTIMAP() [2/2]
Castor3D::DECLARE_MULTIMAP (double , BillboardRenderNode , BillboardRenderNodeByDistance)
DECLARE_SMART_PTR() [1/207]
Castor3D::DECLARE_SMART_PTR (Camera)
DECLARE_SMART_PTR() [2/207]
Castor3D::DECLARE_SMART_PTR (Viewport)
DECLARE_SMART_PTR() [3/207]
Castor3D::DECLARE_SMART_PTR (Ray)
DECLARE_SMART_PTR() [4/207]
Castor3D::DECLARE_SMART_PTR (SceneNode)
DECLARE_SMART_PTR() [5/207]
Castor3D::DECLARE_SMART_PTR (Scene)
DECLARE_SMART_PTR() [6/207]
Castor3D::DECLARE_SMART_PTR (SceneFileContext)
DECLARE_SMART_PTR() [7/207]
Castor3D::DECLARE_SMART_PTR (SceneFileParser)
DECLARE_SMART_PTR() [8/207]
Castor3D::DECLARE_SMART_PTR (Light)
DECLARE_SMART_PTR() [9/207]
Castor3D::DECLARE_SMART_PTR (LightCategory)
DECLARE_SMART_PTR() [10/207]
Castor3D::DECLARE_SMART_PTR (DirectionalLight)
DECLARE_SMART_PTR() [11/207]
Castor3D::DECLARE_SMART_PTR (PointLight)
DECLARE_SMART_PTR() [12/207]
Castor3D::DECLARE_SMART_PTR (SpotLight)
DECLARE_SMART_PTR() [13/207]
Castor3D::DECLARE_SMART_PTR (LightFactory)
DECLARE_SMART_PTR() [14/207]
Castor3D::DECLARE_SMART_PTR (Importer)
DECLARE_SMART_PTR() [15/207]
Castor3D::DECLARE_SMART_PTR (Vertex)
DECLARE_SMART_PTR() [16/207]
Castor3D::DECLARE_SMART_PTR (BufferElementGroup)
DECLARE_SMART_PTR() [17/207]
Castor3D::DECLARE_SMART_PTR (AnimatedObject)
DECLARE_SMART_PTR() [18/207]
Castor3D::DECLARE_SMART_PTR (VertexPattern)
DECLARE_SMART_PTR() [19/207]
Castor3D::DECLARE_SMART_PTR (AnimationObject)
DECLARE_SMART_PTR() [20/207]
Castor3D::DECLARE_SMART_PTR (Point3rPattern)
DECLARE_SMART_PTR() [21/207]
Castor3D::DECLARE_SMART_PTR (SkeletonAnimationObject)
DECLARE_SMART_PTR() [22/207]
Castor3D::DECLARE_SMART_PTR (VertexPtrPattern)
DECLARE_SMART_PTR() [23/207]
Castor3D::DECLARE_SMART_PTR (SkeletonAnimationBone)
DECLARE_SMART_PTR() [24/207]
Castor3D::DECLARE_SMART_PTR (SkeletonAnimationNode)
DECLARE_SMART_PTR() [25/207]
Castor3D::DECLARE_SMART_PTR (Face)
DECLARE_SMART_PTR() [26/207]
Castor3D::DECLARE_SMART_PTR (Animation)
DECLARE_SMART_PTR() [27/207]
Castor3D::DECLARE_SMART_PTR (Graph)
DECLARE_SMART_PTR() [28/207]
Castor3D::DECLARE_SMART_PTR (AnimatedObjectGroup)
DECLARE_SMART_PTR() [29/207]
Castor3D::DECLARE_SMART_PTR (Mesh)
DECLARE_SMART_PTR() [30/207]
Castor3D::DECLARE_SMART_PTR (Bone)
DECLARE_SMART_PTR() [31/207]
Castor3D::DECLARE_SMART_PTR (MeshGenerator)
DECLARE_SMART_PTR() [32/207]
Castor3D::DECLARE_SMART_PTR (Skeleton)
DECLARE_SMART_PTR() [33/207]
Castor3D::DECLARE_SMART_PTR (Submesh)
DECLARE_SMART_PTR() [34/207]
Castor3D::DECLARE_SMART_PTR (Animable)
DECLARE_SMART_PTR() [35/207]
Castor3D::DECLARE_SMART_PTR (Cone)
DECLARE_SMART_PTR() [36/207]
Castor3D::DECLARE_SMART_PTR (BonedVertex)
DECLARE_SMART_PTR() [37/207]
Castor3D::DECLARE_SMART_PTR (Cylinder)
DECLARE_SMART_PTR() [38/207]
Castor3D::DECLARE_SMART_PTR (Icosahedron)
DECLARE_SMART_PTR() [39/207]
Castor3D::DECLARE_SMART_PTR (Cube)
DECLARE_SMART_PTR() [40/207]
Castor3D::DECLARE_SMART_PTR (Plane)
DECLARE_SMART_PTR() [41/207]
Castor3D::DECLARE_SMART_PTR (Projection)
DECLARE_SMART_PTR() [42/207]
Castor3D::DECLARE_SMART_PTR (Sphere)
DECLARE_SMART_PTR() [43/207]
Castor3D::DECLARE_SMART_PTR (Torus)
DECLARE_SMART_PTR() [44/207]
Castor3D::DECLARE_SMART_PTR (Geometry)
DECLARE_SMART_PTR() [45/207]
Castor3D::DECLARE_SMART_PTR (MovableObject)
DECLARE_SMART_PTR() [46/207]
Castor3D::DECLARE_SMART_PTR (Subdivider)
DECLARE_SMART_PTR() [47/207]
Castor3D::DECLARE_SMART_PTR (FaceGroup)
DECLARE_SMART_PTR() [48/207]
Castor3D::DECLARE_SMART_PTR (MeshFactory)
DECLARE_SMART_PTR() [49/207]
Castor3D::DECLARE_SMART_PTR (OverlayFactory)
DECLARE_SMART_PTR() [50/207]
Castor3D::DECLARE_SMART_PTR (OverlayRenderer)
DECLARE_SMART_PTR() [51/207]
Castor3D::DECLARE_SMART_PTR (FontTexture)
DECLARE_SMART_PTR() [52/207]
Castor3D::DECLARE_SMART_PTR (Overlay)
DECLARE_SMART_PTR() [53/207]
Castor3D::DECLARE_SMART_PTR (OverlayCategory)
DECLARE_SMART_PTR() [54/207]
Castor3D::DECLARE_SMART_PTR (PanelOverlay)
DECLARE_SMART_PTR() [55/207]
Castor3D::DECLARE_SMART_PTR (BorderPanelOverlay)
DECLARE_SMART_PTR() [56/207]
Castor3D::DECLARE_SMART_PTR (TextOverlay)
DECLARE_SMART_PTR() [57/207]
Castor3D::DECLARE_SMART_PTR (OneBoolFrameVariable)
DECLARE_SMART_PTR() [58/207]
Castor3D::DECLARE_SMART_PTR (OneIntFrameVariable)
DECLARE_SMART_PTR() [59/207]
Castor3D::DECLARE_SMART_PTR (OneUIntFrameVariable)
DECLARE_SMART_PTR() [60/207]
Castor3D::DECLARE_SMART_PTR (OneFloatFrameVariable)
DECLARE_SMART_PTR() [61/207]
Castor3D::DECLARE_SMART_PTR (OneDoubleFrameVariable)
DECLARE_SMART_PTR() [62/207]
Castor3D::DECLARE_SMART_PTR (OneRealFrameVariable)
DECLARE_SMART_PTR() [63/207]
Castor3D::DECLARE_SMART_PTR (Point2bFrameVariable)
DECLARE_SMART_PTR() [64/207]
Castor3D::DECLARE_SMART_PTR (Point3bFrameVariable)
DECLARE_SMART_PTR() [65/207]
Castor3D::DECLARE_SMART_PTR (Point4bFrameVariable)
DECLARE_SMART_PTR() [66/207]
Castor3D::DECLARE_SMART_PTR (Point2iFrameVariable)
DECLARE_SMART_PTR() [67/207]
Castor3D::DECLARE_SMART_PTR (Point3iFrameVariable)
DECLARE_SMART_PTR() [68/207]
Castor3D::DECLARE_SMART_PTR (Point4iFrameVariable)
DECLARE_SMART_PTR() [69/207]
Castor3D::DECLARE_SMART_PTR (Point2uiFrameVariable)
DECLARE_SMART_PTR() [70/207]
Castor3D::DECLARE_SMART_PTR (Point3uiFrameVariable)
DECLARE_SMART_PTR() [71/207]
Castor3D::DECLARE_SMART_PTR (Point4uiFrameVariable)
DECLARE_SMART_PTR() [72/207]
Castor3D::DECLARE_SMART_PTR (Point2fFrameVariable)
DECLARE_SMART_PTR() [73/207]
Castor3D::DECLARE_SMART_PTR (Point3fFrameVariable)
DECLARE_SMART_PTR() [74/207]
Castor3D::DECLARE_SMART_PTR (Point4fFrameVariable)
DECLARE_SMART_PTR() [75/207]
Castor3D::DECLARE_SMART_PTR (Point2dFrameVariable)
DECLARE_SMART_PTR() [76/207]
Castor3D::DECLARE_SMART_PTR (Point3dFrameVariable)
DECLARE_SMART_PTR() [77/207]
Castor3D::DECLARE_SMART_PTR (Point4dFrameVariable)
DECLARE_SMART_PTR() [78/207]
Castor3D::DECLARE_SMART_PTR (Point2rFrameVariable)
DECLARE_SMART_PTR() [79/207]
Castor3D::DECLARE_SMART_PTR (Point3rFrameVariable)
DECLARE_SMART_PTR() [80/207]
Castor3D::DECLARE_SMART_PTR (Point4rFrameVariable)
DECLARE_SMART_PTR() [81/207]
Castor3D::DECLARE_SMART_PTR (Matrix2x2bFrameVariable)
DECLARE_SMART_PTR() [82/207]
Castor3D::DECLARE_SMART_PTR (Matrix2x3bFrameVariable)
DECLARE_SMART_PTR() [83/207]
Castor3D::DECLARE_SMART_PTR (Matrix2x4bFrameVariable)
DECLARE_SMART_PTR() [84/207]
Castor3D::DECLARE_SMART_PTR (Matrix3x2bFrameVariable)
DECLARE_SMART_PTR() [85/207]
Castor3D::DECLARE_SMART_PTR (Matrix3x3bFrameVariable)
DECLARE_SMART_PTR() [86/207]
Castor3D::DECLARE_SMART_PTR (Matrix3x4bFrameVariable)
DECLARE_SMART_PTR() [87/207]
Castor3D::DECLARE_SMART_PTR (Matrix4x2bFrameVariable)
DECLARE_SMART_PTR() [88/207]
Castor3D::DECLARE_SMART_PTR (Matrix4x3bFrameVariable)
DECLARE_SMART_PTR() [89/207]
Castor3D::DECLARE_SMART_PTR (Matrix4x4bFrameVariable)
DECLARE_SMART_PTR() [90/207]
Castor3D::DECLARE_SMART_PTR (Matrix2x2iFrameVariable)
DECLARE_SMART_PTR() [91/207]
Castor3D::DECLARE_SMART_PTR (Matrix2x3iFrameVariable)
DECLARE_SMART_PTR() [92/207]
Castor3D::DECLARE_SMART_PTR (Matrix2x4iFrameVariable)
DECLARE_SMART_PTR() [93/207]
Castor3D::DECLARE_SMART_PTR (Matrix3x2iFrameVariable)
DECLARE_SMART_PTR() [94/207]
Castor3D::DECLARE_SMART_PTR (Matrix3x3iFrameVariable)
DECLARE_SMART_PTR() [95/207]
Castor3D::DECLARE_SMART_PTR (Matrix3x4iFrameVariable)
DECLARE_SMART_PTR() [96/207]
Castor3D::DECLARE_SMART_PTR (Matrix4x2iFrameVariable)
DECLARE_SMART_PTR() [97/207]
Castor3D::DECLARE_SMART_PTR (Matrix4x3iFrameVariable)
DECLARE_SMART_PTR() [98/207]
Castor3D::DECLARE_SMART_PTR (Matrix4x4iFrameVariable)
DECLARE_SMART_PTR() [99/207]
Castor3D::DECLARE_SMART_PTR (Matrix2x2uiFrameVariable)
DECLARE_SMART_PTR() [100/207]
Castor3D::DECLARE_SMART_PTR (Matrix2x3uiFrameVariable)
DECLARE_SMART_PTR() [101/207]
Castor3D::DECLARE_SMART_PTR (Matrix2x4uiFrameVariable)
DECLARE_SMART_PTR() [102/207]
Castor3D::DECLARE_SMART_PTR (Matrix3x2uiFrameVariable)
DECLARE_SMART_PTR() [103/207]
Castor3D::DECLARE_SMART_PTR (Matrix3x3uiFrameVariable)
DECLARE_SMART_PTR() [104/207]
Castor3D::DECLARE_SMART_PTR (Matrix3x4uiFrameVariable)
DECLARE_SMART_PTR() [105/207]
Castor3D::DECLARE_SMART_PTR (Texture)
DECLARE_SMART_PTR() [106/207]
Castor3D::DECLARE_SMART_PTR (Matrix4x2uiFrameVariable)
DECLARE_SMART_PTR() [107/207]
Castor3D::DECLARE_SMART_PTR (StaticTexture)
DECLARE_SMART_PTR() [108/207]
Castor3D::DECLARE_SMART_PTR (RenderWindow)
DECLARE_SMART_PTR() [109/207]
Castor3D::DECLARE_SMART_PTR (Matrix4x3uiFrameVariable)
DECLARE_SMART_PTR() [110/207]
Castor3D::DECLARE_SMART_PTR (DynamicTexture)
DECLARE_SMART_PTR() [111/207]
Castor3D::DECLARE_SMART_PTR (Matrix4x4uiFrameVariable)
DECLARE_SMART_PTR() [112/207]
Castor3D::DECLARE_SMART_PTR (RenderTarget)
DECLARE_SMART_PTR() [113/207]
Castor3D::DECLARE_SMART_PTR (RenderBuffer)
DECLARE_SMART_PTR() [114/207]
Castor3D::DECLARE_SMART_PTR (TextureUnit)
DECLARE_SMART_PTR() [115/207]
Castor3D::DECLARE_SMART_PTR (Matrix2x2fFrameVariable)
DECLARE_SMART_PTR() [116/207]
Castor3D::DECLARE_SMART_PTR (ColourRenderBuffer)
DECLARE_SMART_PTR() [117/207]
Castor3D::DECLARE_SMART_PTR (Material)
DECLARE_SMART_PTR() [118/207]
Castor3D::DECLARE_SMART_PTR (Matrix2x3fFrameVariable)
DECLARE_SMART_PTR() [119/207]
Castor3D::DECLARE_SMART_PTR (Pass)
DECLARE_SMART_PTR() [120/207]
Castor3D::DECLARE_SMART_PTR (DepthStencilRenderBuffer)
DECLARE_SMART_PTR() [121/207]
Castor3D::DECLARE_SMART_PTR (Matrix2x4fFrameVariable)
DECLARE_SMART_PTR() [122/207]
Castor3D::DECLARE_SMART_PTR (Sampler)
DECLARE_SMART_PTR() [123/207]
Castor3D::DECLARE_SMART_PTR (FrameBufferAttachment)
DECLARE_SMART_PTR() [124/207]
Castor3D::DECLARE_SMART_PTR (Matrix3x2fFrameVariable)
DECLARE_SMART_PTR() [125/207]
Castor3D::DECLARE_SMART_PTR (RenderBufferAttachment)
DECLARE_SMART_PTR() [126/207]
Castor3D::DECLARE_SMART_PTR (Matrix3x3fFrameVariable)
DECLARE_SMART_PTR() [127/207]
Castor3D::DECLARE_SMART_PTR (TextureAttachment)
DECLARE_SMART_PTR() [128/207]
Castor3D::DECLARE_SMART_PTR (Matrix3x4fFrameVariable)
DECLARE_SMART_PTR() [129/207]
Castor3D::DECLARE_SMART_PTR (FrameBuffer)
DECLARE_SMART_PTR() [130/207]
Castor3D::DECLARE_SMART_PTR (Matrix4x2fFrameVariable)
DECLARE_SMART_PTR() [131/207]
Castor3D::DECLARE_SMART_PTR (BackBuffers)
DECLARE_SMART_PTR() [132/207]
Castor3D::DECLARE_SMART_PTR (Matrix4x3fFrameVariable)
DECLARE_SMART_PTR() [133/207]
Castor3D::DECLARE_SMART_PTR (RenderTechnique)
DECLARE_SMART_PTR() [134/207]
Castor3D::DECLARE_SMART_PTR (Matrix4x4fFrameVariable)
DECLARE_SMART_PTR() [135/207]
Castor3D::DECLARE_SMART_PTR (PostEffect)
DECLARE_SMART_PTR() [136/207]
Castor3D::DECLARE_SMART_PTR (Matrix2x2dFrameVariable)
DECLARE_SMART_PTR() [137/207]
Castor3D::DECLARE_SMART_PTR (Engine)
DECLARE_SMART_PTR() [138/207]
Castor3D::DECLARE_SMART_PTR (Matrix2x3dFrameVariable)
DECLARE_SMART_PTR() [139/207]
Castor3D::DECLARE_SMART_PTR (RendererServer)
DECLARE_SMART_PTR() [140/207]
Castor3D::DECLARE_SMART_PTR (Matrix2x4dFrameVariable)
DECLARE_SMART_PTR() [141/207]
Castor3D::DECLARE_SMART_PTR (PluginBase)
DECLARE_SMART_PTR() [142/207]
Castor3D::DECLARE_SMART_PTR (Matrix3x2dFrameVariable)
DECLARE_SMART_PTR() [143/207]
Castor3D::DECLARE_SMART_PTR (RendererPlugin)
DECLARE_SMART_PTR() [144/207]
Castor3D::DECLARE_SMART_PTR (Matrix3x3dFrameVariable)
DECLARE_SMART_PTR() [145/207]
Castor3D::DECLARE_SMART_PTR (ImporterPlugin)
DECLARE_SMART_PTR() [146/207]
Castor3D::DECLARE_SMART_PTR (Matrix3x4dFrameVariable)
DECLARE_SMART_PTR() [147/207]
Castor3D::DECLARE_SMART_PTR (DividerPlugin)
DECLARE_SMART_PTR() [148/207]
Castor3D::DECLARE_SMART_PTR (Matrix4x2dFrameVariable)
DECLARE_SMART_PTR() [149/207]
Castor3D::DECLARE_SMART_PTR (Matrix4x3dFrameVariable)
DECLARE_SMART_PTR() [150/207]
Castor3D::DECLARE_SMART_PTR (GenericPlugin)
DECLARE_SMART_PTR() [151/207]
Castor3D::DECLARE_SMART_PTR (Matrix4x4dFrameVariable)
DECLARE_SMART_PTR() [152/207]
Castor3D::DECLARE_SMART_PTR (PostFxPlugin)
DECLARE_SMART_PTR() [153/207]
Castor3D::DECLARE_SMART_PTR (Matrix2x2rFrameVariable)
DECLARE_SMART_PTR() [154/207]
Castor3D::DECLARE_SMART_PTR (FrameEvent)
DECLARE_SMART_PTR() [155/207]
Castor3D::DECLARE_SMART_PTR (Matrix2x3rFrameVariable)
DECLARE_SMART_PTR() [156/207]
Castor3D::DECLARE_SMART_PTR (FrameListener)
DECLARE_SMART_PTR() [157/207]
Castor3D::DECLARE_SMART_PTR (Matrix2x4rFrameVariable)
DECLARE_SMART_PTR() [158/207]
Castor3D::DECLARE_SMART_PTR (IWindowHandle)
DECLARE_SMART_PTR() [159/207]
Castor3D::DECLARE_SMART_PTR (Matrix3x2rFrameVariable)
DECLARE_SMART_PTR() [160/207]
Castor3D::DECLARE_SMART_PTR (BillboardList)
DECLARE_SMART_PTR() [161/207]
Castor3D::DECLARE_SMART_PTR (Matrix3x3rFrameVariable)
DECLARE_SMART_PTR() [162/207]
Castor3D::DECLARE_SMART_PTR (RenderLoop)
DECLARE_SMART_PTR() [163/207]
Castor3D::DECLARE_SMART_PTR (GpuQuery)
DECLARE_SMART_PTR() [164/207]
Castor3D::DECLARE_SMART_PTR (Matrix3x4rFrameVariable)
DECLARE_SMART_PTR() [165/207]
Castor3D::DECLARE_SMART_PTR (Matrix4x2rFrameVariable)
DECLARE_SMART_PTR() [166/207]
Castor3D::DECLARE_SMART_PTR (Matrix4x3rFrameVariable)
DECLARE_SMART_PTR() [167/207]
Castor3D::DECLARE_SMART_PTR (Matrix4x4rFrameVariable)
DECLARE_SMART_PTR() [168/207]
Castor3D::DECLARE_SMART_PTR (FrameVariableLink)
DECLARE_SMART_PTR() [169/207]
Castor3D::DECLARE_SMART_PTR (ProgramLinks)
DECLARE_SMART_PTR() [170/207]
Castor3D::DECLARE_SMART_PTR (FrameVariableBuffer)
DECLARE_SMART_PTR() [171/207]
Castor3D::DECLARE_SMART_PTR (FrameVariable)
DECLARE_SMART_PTR() [172/207]
Castor3D::DECLARE_SMART_PTR (ShaderObject)
DECLARE_SMART_PTR() [173/207]
Castor3D::DECLARE_SMART_PTR (ShaderProgram)
DECLARE_SMART_PTR() [174/207]
Castor3D::DECLARE_SMART_PTR (OverlayManager)
DECLARE_SMART_PTR() [175/207]
Castor3D::DECLARE_SMART_PTR (ShaderManager)
DECLARE_SMART_PTR() [176/207]
Castor3D::DECLARE_SMART_PTR (MaterialManager)
DECLARE_SMART_PTR() [177/207]
Castor3D::DECLARE_SMART_PTR (WindowManager)
DECLARE_SMART_PTR() [178/207]
Castor3D::DECLARE_SMART_PTR (MeshManager)
DECLARE_SMART_PTR() [179/207]
Castor3D::DECLARE_SMART_PTR (PluginManager)
DECLARE_SMART_PTR() [180/207]
Castor3D::DECLARE_SMART_PTR (SceneManager)
DECLARE_SMART_PTR() [181/207]
Castor3D::DECLARE_SMART_PTR (SamplerManager)
DECLARE_SMART_PTR() [182/207]
Castor3D::DECLARE_SMART_PTR (DepthStencilStateManager)
DECLARE_SMART_PTR() [183/207]
Castor3D::DECLARE_SMART_PTR (RasteriserStateManager)
DECLARE_SMART_PTR() [184/207]
Castor3D::DECLARE_SMART_PTR (BlendStateManager)
DECLARE_SMART_PTR() [185/207]
Castor3D::DECLARE_SMART_PTR (AnimationManager)
DECLARE_SMART_PTR() [186/207]
Castor3D::DECLARE_SMART_PTR (TargetManager)
DECLARE_SMART_PTR() [187/207]
Castor3D::DECLARE_SMART_PTR (ListenerManager)
DECLARE_SMART_PTR() [188/207]
Castor3D::DECLARE_SMART_PTR (GeometryManager)
DECLARE_SMART_PTR() [189/207]
Castor3D::DECLARE_SMART_PTR (CameraManager)
DECLARE_SMART_PTR() [190/207]
Castor3D::DECLARE_SMART_PTR (LightManager)
DECLARE_SMART_PTR() [191/207]
Castor3D::DECLARE_SMART_PTR (AnimatedObjectGroupManager)
DECLARE_SMART_PTR() [192/207]
Castor3D::DECLARE_SMART_PTR (SceneNodeManager)
DECLARE_SMART_PTR() [193/207]
Castor3D::DECLARE_SMART_PTR (BillboardManager)
DECLARE_SMART_PTR() [194/207]
Castor3D::DECLARE_SMART_PTR (RenderTechniqueManager)
DECLARE_SMART_PTR() [195/207]
Castor3D::DECLARE_SMART_PTR (TechniqueFactory)
DECLARE_SMART_PTR() [196/207]
Castor3D::DECLARE_SMART_PTR (GeometryBuffers)
DECLARE_SMART_PTR() [197/207]
Castor3D::DECLARE_SMART_PTR (BufferElementDeclaration)
DECLARE_SMART_PTR() [198/207]
Castor3D::DECLARE_SMART_PTR (BufferDeclaration)
DECLARE_SMART_PTR() [199/207]
Castor3D::DECLARE_SMART_PTR (VertexBuffer)
DECLARE_SMART_PTR() [200/207]
Castor3D::DECLARE_SMART_PTR (IndexBuffer)
DECLARE_SMART_PTR() [201/207]
Castor3D::DECLARE_SMART_PTR (TextureBuffer)
DECLARE_SMART_PTR() [202/207]
Castor3D::DECLARE_SMART_PTR (Context)
DECLARE_SMART_PTR() [203/207]
Castor3D::DECLARE_SMART_PTR (DepthStencilState)
DECLARE_SMART_PTR() [204/207]
Castor3D::DECLARE_SMART_PTR (RasteriserState)
DECLARE_SMART_PTR() [205/207]
Castor3D::DECLARE_SMART_PTR (BlendState)
DECLARE_SMART_PTR() [206/207]
Castor3D::DECLARE_SMART_PTR (IPipelineImpl)
DECLARE_SMART_PTR() [207/207]
Castor3D::DECLARE_SMART_PTR (ToneMapping)
DECLARE_VECTOR() [1/31]
Castor3D::DECLARE_VECTOR (CameraSPtr , CameraPtr)
Camera pointer array.
DECLARE_VECTOR() [2/31]
Castor3D::DECLARE_VECTOR (SceneNodeSPtr , SceneNodePtr)
SceneNode pointer array.
DECLARE_VECTOR() [3/31]
Castor3D::DECLARE_VECTOR (LightSPtr , LightPtr)
Array of lights.
DECLARE_VECTOR() [4/31]
Castor3D::DECLARE_VECTOR (GeometryRenderNode , GeometryRenderNode)
GeometryRenderNode array.
DECLARE_VECTOR() [5/31]
Castor3D::DECLARE_VECTOR (BillboardRenderNode , BillboardRenderNode)
BillboardRenderNode array.
DECLARE_VECTOR() [6/31]
Castor3D::DECLARE_VECTOR (AnimationSPtr , AnimationPtr)
Animation pointer array.
DECLARE_VECTOR() [7/31]
Castor3D::DECLARE_VECTOR (BoneSPtr , BonePtr)
Bone pointer array.
DECLARE_VECTOR() [8/31]
Castor3D::DECLARE_VECTOR (AnimationObjectSPtr , AnimationObjectPtr)
AnimationObject pointer array.
DECLARE_VECTOR() [9/31]
Castor3D::DECLARE_VECTOR (Vertex , Vertex)
Vertex array.
DECLARE_VECTOR() [10/31]
Castor3D::DECLARE_VECTOR (BonedVertexSPtr , BonedVertexPtr)
BonedVertex pointer array.
DECLARE_VECTOR() [11/31]
Castor3D::DECLARE_VECTOR (BufferElementGroupSPtr , VertexPtr)
Vertex pointer array.
DECLARE_VECTOR() [12/31]
Castor3D::DECLARE_VECTOR (Face , Face)
Face array.
DECLARE_VECTOR() [13/31]
Castor3D::DECLARE_VECTOR (FaceSPtr , FacePtr)
Face pointer array.
DECLARE_VECTOR() [14/31]
Castor3D::DECLARE_VECTOR (FaceGroupSPtr , FaceGroupPtr)
FaceGroup pointer array.
DECLARE_VECTOR() [15/31]
Castor3D::DECLARE_VECTOR (SubmeshSPtr , SubmeshPtr)
Submesh pointer array.
DECLARE_VECTOR() [16/31]
Castor3D::DECLARE_VECTOR (GeometrySPtr , GeometryPtr)
Geometry pointer array.
DECLARE_VECTOR() [17/31]
Castor3D::DECLARE_VECTOR (OverlaySPtr , OverlayPtr)
DECLARE_VECTOR() [18/31]
Castor3D::DECLARE_VECTOR (MaterialSPtr , MaterialPtr)
Material pointer array.
DECLARE_VECTOR() [19/31]
Castor3D::DECLARE_VECTOR (TextureUnit , TextureUnit)
TextureUnit array.
DECLARE_VECTOR() [20/31]
Castor3D::DECLARE_VECTOR (TextureUnitSPtr , TextureUnitPtr)
TextureUnit pointer array.
DECLARE_VECTOR() [21/31]
Castor3D::DECLARE_VECTOR (Pass , Pass)
Pass array.
DECLARE_VECTOR() [22/31]
Castor3D::DECLARE_VECTOR (PassSPtr , PassPtr)
Pass pointer array.
DECLARE_VECTOR() [23/31]
Castor3D::DECLARE_VECTOR (uint32_t , UInt)
uint32_t array
DECLARE_VECTOR() [24/31]
Castor3D::DECLARE_VECTOR (ShaderProgramSPtr , ShaderProgramPtr)
DECLARE_VECTOR() [25/31]
Castor3D::DECLARE_VECTOR (ShaderObjectSPtr , ShaderObjectPtr)
DECLARE_VECTOR() [26/31]
Castor3D::DECLARE_VECTOR (real , Real)
real array
DECLARE_VECTOR() [27/31]
Castor3D::DECLARE_VECTOR (RenderWindowSPtr , RenderWindowPtr)
RenderWindow pointer array.
DECLARE_VECTOR() [28/31]
Castor3D::DECLARE_VECTOR (RenderBufferSPtr , RenderBufferPtr)
RenderBuffer pointer array.
DECLARE_VECTOR() [29/31]
Castor3D::DECLARE_VECTOR (FrameEventSPtr , FrameEventPtr)
FrameEvent pointer array.
DECLARE_VECTOR() [30/31]
Castor3D::DECLARE_VECTOR (PostEffectSPtr , PostEffectPtr)
DECLARE_VECTOR() [31/31]
Castor3D::DECLARE_VECTOR (BillboardListSPtr , BillboardList)
GetCPUCount()
int Castor3D::GetCPUCount ()
GetSize()
uint32_t Castor3D::GetSize (eELEMENT_TYPE p_type) inline
References eELEMENT_TYPE_1FLOAT, eELEMENT_TYPE_1INT, eELEMENT_TYPE_2FLOATS, eELEMENT_TYPE_2INTS, eELEMENT_TYPE_2x2FLOATS, eELEMENT_TYPE_3FLOATS, eELEMENT_TYPE_3INTS, eELEMENT_TYPE_3x3FLOATS, eELEMENT_TYPE_4FLOATS, eELEMENT_TYPE_4INTS, eELEMENT_TYPE_4x4FLOATS, and eELEMENT_TYPE_COLOUR.
MakeCleanupEvent()
template<typename T > std::shared_ptr< CleanupEvent< T > > Castor3D::MakeCleanupEvent (T & p_object)
Helper function to create a cleanup event.
Parameters
[in] p_object The object to cleanup
Referenced by Castor3D::ElementCleaner< Elem, typename std::enable_if< is_cleanable< Elem >::value &&!is_instant< Elem >::value >::type >::Cleanup().
MakeFunctorEvent()
template<typename Functor > std::shared_ptr< FunctorEvent< Functor > > Castor3D::MakeFunctorEvent (eEVENT_TYPE p_type, Functor p_functor) inline
Helper function to create a functor event.
Parameters
[in] p_type The event type
[in] p_functor The functor to execute
Referenced by Castor3D::GeometryManager::Create().
MakeInitialiseEvent()
template<typename T > std::shared_ptr< InitialiseEvent< T > > Castor3D::MakeInitialiseEvent (T & p_object)
Helper function to create an initialise event.
Parameters
[in] p_object The object to initialise
Referenced by Castor3D::SamplerManager::Create(), and Castor3D::ElementInitialiser< Elem, typename std::enable_if< is_initialisable< Elem >::value &&!is_instant< Elem >::value >::type >::Initialise().
operator!=() [1/4]
bool Castor3D::operator!= (BufferElementDeclaration const & p_lhs, BufferElementDeclaration const & p_rhs) inline
Equality operator.
Parameters
[in] p_lhs,p_rhs The 2 objects to compare.
References Castor3D::BufferElementDeclaration::m_dataType, Castor3D::BufferElementDeclaration::m_name, Castor3D::BufferElementDeclaration::m_offset, and Castor3D::BufferElementDeclaration::m_usages.
operator!=() [2/4]
C3D_API bool Castor3D::operator!= (Castor3D::Version const & p_a, Castor3D::Version const & p_b)
Difference operator.
Parameters
[in] p_a,p_b The versions to compare
Returns
true if one version number is different from p_a to p_b
operator!=() [3/4]
C3D_API bool Castor3D::operator!= (ProgramInputLayout const & p_lhs, ProgramInputLayout const & p_rhs)
Equality operator.
Parameters
[in] p_lhs,p_rhs The 2 objects to compare.
operator!=() [4/4]
C3D_API bool Castor3D::operator!= (BufferDeclaration & p_lhs, BufferDeclaration & p_rhs)
Equality operator.
Parameters
[in] p_lhs,p_rhs The 2 objects to compare.
operator<()
C3D_API bool Castor3D::operator< (Castor3D::Version const & p_a, Castor3D::Version const & p_b)
Less than operator.
Parameters
[in] p_a,p_b The versions to compare
Returns
true if p_a.major is less than p_b.major or if they are equal and p_a.minor is less than p_b.minor or if majors and minors are equal and p_a.build is less than p_b.build
operator<<() [1/12]
std::ostream& Castor3D::operator<< (std::ostream & o, Sphere const & c) inline
Stream operator.
operator<<() [2/12]
std::ostream& Castor3D::operator<< (std::ostream & o, Icosahedron const & c) inline
Stream operator.
operator<<() [3/12]
std::ostream& Castor3D::operator<< (std::ostream & o, Projection const & c) inline
Stream operator.
operator<<() [4/12]
std::ostream& Castor3D::operator<< (std::ostream & o, Cube const & c) inline
Stream operator.
operator<<() [5/12]
std::ostream& Castor3D::operator<< (std::ostream & o, Cylinder const & c) inline
Stream operator.
operator<<() [6/12]
std::ostream& Castor3D::operator<< (std::ostream & o, Cone const & c) inline
Stream operator.
operator<<() [7/12]
std::ostream& Castor3D::operator<< (std::ostream & o, Plane const & c) inline
Stream operator.
operator<<() [8/12]
std::ostream& Castor3D::operator<< (std::ostream & o, Torus const & c) inline
Stream operator.
operator<<() [9/12]
C3D_API std::ostream& Castor3D::operator<< (std::ostream & p_stream, Castor3D::Version const & p_version)
operator<<() [10/12]
C3D_API std::wostream& Castor3D::operator<< (std::wostream & p_stream, Castor3D::Version const & p_version)
operator<<() [11/12]
C3D_API Castor::String& Castor3D::operator<< (Castor::String & p_stream, Castor3D::Version const & p_version)
operator<<() [12/12]
std::ostream& Castor3D::operator<< (std::ostream & p_streamOut, TextureUnitSPtr const & p_texture) inline
Stream operator.
Parameters
[in,out] p_streamOut The stream receiving texture's data
[in] p_texture The input texture
Returns
A reference to the stream
operator<=()
C3D_API bool Castor3D::operator<= (Castor3D::Version const & p_a, Castor3D::Version const & p_b)
Less than operator.
Parameters
[in] p_a,p_b The versions to compare
Returns
false if p_a.major is greater than p_b.major or if they are equal and p_a.minor is greater than p_b.minor or if majors and minors are equal and p_a.build is greater than p_b.build
operator==() [1/4]
bool Castor3D::operator== (BufferElementDeclaration const & p_lhs, BufferElementDeclaration const & p_rhs) inline
Equality operator.
Parameters
[in] p_lhs,p_rhs The 2 objects to compare.
References Castor3D::BufferElementDeclaration::m_dataType, Castor3D::BufferElementDeclaration::m_name, Castor3D::BufferElementDeclaration::m_offset, and Castor3D::BufferElementDeclaration::m_usages.
operator==() [2/4]
C3D_API bool Castor3D::operator== (Castor3D::Version const & p_a, Castor3D::Version const & p_b)
Equality operator.
Parameters
[in] p_a,p_b The versions to compare
Returns
false if one version number is different from p_a to p_b
operator==() [3/4]
C3D_API bool Castor3D::operator== (ProgramInputLayout const & p_lhs, ProgramInputLayout const & p_rhs)
Equality operator.
Parameters
[in] p_lhs,p_rhs The 2 objects to compare.
operator==() [4/4]
C3D_API bool Castor3D::operator== (BufferDeclaration & p_lhs, BufferDeclaration & p_rhs)
Equality operator.
Parameters
[in] p_lhs,p_rhs The 2 objects to compare.
operator>()
C3D_API bool Castor3D::operator> (Castor3D::Version const & p_a, Castor3D::Version const & p_b)
Less than operator.
Parameters
[in] p_a,p_b The versions to compare
Returns
true if p_a.major is greater than p_b.major or if they are equal and p_a.minor is greater than p_b.minor or if majors and minors are equal and p_a.build is greater than p_b.build
operator>=()
C3D_API bool Castor3D::operator>= (Castor3D::Version const & p_a, Castor3D::Version const & p_b)
Less than operator.
Parameters
[in] p_a,p_b The versions to compare
Returns
false if p_a.major is less than p_b.major or if they are equal and p_a.minor is less than p_b.minor or if majors and minors are equal and p_a.build is less than p_b.build
Variable Documentation
C3D_MAX_BONES_PER_VERTEX
const uint32_t Castor3D::C3D_MAX_BONES_PER_VERTEX = 8 static
C3D_MAX_TEXTURE_MATRICES
const uint32_t Castor3D::C3D_MAX_TEXTURE_MATRICES = 10 static
Referenced by Castor3D::Pipeline::GetTextureMatrix(), and Castor3D::Pipeline::SetTextureMatrix().
INFO_MANAGER_CREATED_OBJECT
const xchar* Castor3D::INFO_MANAGER_CREATED_OBJECT = cuT("Manager::Create - Created ") static
Referenced by Castor3D::SamplerManager::Create(), Castor3D::AnimatedObjectGroupManager::Create(), Castor3D::SceneNodeManager::Create(), Castor3D::GeometryManager::Create(), Castor3D::ObjectManager< Castor::String, AnimatedObjectGroup >::Create(), and Castor3D::Manager< Castor::String, Sampler, Engine, ResourceManagerEngineGetter >::Create().
MASK_MTXMODE_MODEL
const uint64_t Castor3D::MASK_MTXMODE_MODEL = uint64_t(0x1) << eMTXMODE_MODEL static
MASK_MTXMODE_PROJECTION
const uint64_t Castor3D::MASK_MTXMODE_PROJECTION = uint64_t(0x1) << eMTXMODE_PROJECTION static
Matrix modes masks.
Author
Sylvain DOREMUS
MASK_MTXMODE_TEXTURE0
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE0 = uint64_t(0x1) << eMTXMODE_TEXTURE0 static
MASK_MTXMODE_TEXTURE1
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE1 = uint64_t(0x1) << eMTXMODE_TEXTURE1 static
MASK_MTXMODE_TEXTURE10
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE10 = uint64_t(0x1) << eMTXMODE_TEXTURE10 static
MASK_MTXMODE_TEXTURE11
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE11 = uint64_t(0x1) << eMTXMODE_TEXTURE11 static
MASK_MTXMODE_TEXTURE12
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE12 = uint64_t(0x1) << eMTXMODE_TEXTURE12 static
MASK_MTXMODE_TEXTURE13
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE13 = uint64_t(0x1) << eMTXMODE_TEXTURE13 static
MASK_MTXMODE_TEXTURE14
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE14 = uint64_t(0x1) << eMTXMODE_TEXTURE14 static
MASK_MTXMODE_TEXTURE15
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE15 = uint64_t(0x1) << eMTXMODE_TEXTURE15 static
MASK_MTXMODE_TEXTURE16
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE16 = uint64_t(0x1) << eMTXMODE_TEXTURE16 static
MASK_MTXMODE_TEXTURE17
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE17 = uint64_t(0x1) << eMTXMODE_TEXTURE17 static
MASK_MTXMODE_TEXTURE18
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE18 = uint64_t(0x1) << eMTXMODE_TEXTURE18 static
MASK_MTXMODE_TEXTURE19
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE19 = uint64_t(0x1) << eMTXMODE_TEXTURE19 static
MASK_MTXMODE_TEXTURE2
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE2 = uint64_t(0x1) << eMTXMODE_TEXTURE2 static
MASK_MTXMODE_TEXTURE20
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE20 = uint64_t(0x1) << eMTXMODE_TEXTURE20 static
MASK_MTXMODE_TEXTURE21
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE21 = uint64_t(0x1) << eMTXMODE_TEXTURE21 static
MASK_MTXMODE_TEXTURE22
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE22 = uint64_t(0x1) << eMTXMODE_TEXTURE22 static
MASK_MTXMODE_TEXTURE23
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE23 = uint64_t(0x1) << eMTXMODE_TEXTURE23 static
MASK_MTXMODE_TEXTURE24
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE24 = uint64_t(0x1) << eMTXMODE_TEXTURE24 static
MASK_MTXMODE_TEXTURE25
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE25 = uint64_t(0x1) << eMTXMODE_TEXTURE25 static
MASK_MTXMODE_TEXTURE26
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE26 = uint64_t(0x1) << eMTXMODE_TEXTURE26 static
MASK_MTXMODE_TEXTURE27
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE27 = uint64_t(0x1) << eMTXMODE_TEXTURE27 static
MASK_MTXMODE_TEXTURE28
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE28 = uint64_t(0x1) << eMTXMODE_TEXTURE28 static
MASK_MTXMODE_TEXTURE29
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE29 = uint64_t(0x1) << eMTXMODE_TEXTURE29 static
MASK_MTXMODE_TEXTURE3
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE3 = uint64_t(0x1) << eMTXMODE_TEXTURE3 static
MASK_MTXMODE_TEXTURE30
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE30 = uint64_t(0x1) << eMTXMODE_TEXTURE30 static
MASK_MTXMODE_TEXTURE31
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE31 = uint64_t(0x1) << eMTXMODE_TEXTURE31 static
MASK_MTXMODE_TEXTURE4
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE4 = uint64_t(0x1) << eMTXMODE_TEXTURE4 static
MASK_MTXMODE_TEXTURE5
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE5 = uint64_t(0x1) << eMTXMODE_TEXTURE5 static
MASK_MTXMODE_TEXTURE6
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE6 = uint64_t(0x1) << eMTXMODE_TEXTURE6 static
MASK_MTXMODE_TEXTURE7
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE7 = uint64_t(0x1) << eMTXMODE_TEXTURE7 static
MASK_MTXMODE_TEXTURE8
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE8 = uint64_t(0x1) << eMTXMODE_TEXTURE8 static
MASK_MTXMODE_TEXTURE9
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE9 = uint64_t(0x1) << eMTXMODE_TEXTURE9 static
MASK_MTXMODE_VIEW
const uint64_t Castor3D::MASK_MTXMODE_VIEW = uint64_t(0x1) << eMTXMODE_VIEW static
MASK_SHADER_TYPE_COMPUTE
const uint64_t Castor3D::MASK_SHADER_TYPE_COMPUTE = uint64_t(0x1) << eSHADER_TYPE_COMPUTE static
MASK_SHADER_TYPE_DOMAIN
const uint64_t Castor3D::MASK_SHADER_TYPE_DOMAIN = uint64_t(0x1) << eSHADER_TYPE_DOMAIN static
MASK_SHADER_TYPE_GEOMETRY
const uint64_t Castor3D::MASK_SHADER_TYPE_GEOMETRY = uint64_t(0x1) << eSHADER_TYPE_GEOMETRY static
MASK_SHADER_TYPE_HULL
const uint64_t Castor3D::MASK_SHADER_TYPE_HULL = uint64_t(0x1) << eSHADER_TYPE_HULL static
MASK_SHADER_TYPE_PIXEL
const uint64_t Castor3D::MASK_SHADER_TYPE_PIXEL = uint64_t(0x1) << eSHADER_TYPE_PIXEL static
MASK_SHADER_TYPE_VERTEX
const uint64_t Castor3D::MASK_SHADER_TYPE_VERTEX = uint64_t(0x1) << eSHADER_TYPE_VERTEX static
Shader object types masks.
Author
Sylvain DOREMUS
WARNING_MANAGER_DUPLICATE_OBJECT
const xchar* Castor3D::WARNING_MANAGER_DUPLICATE_OBJECT = cuT("Manager::Create - Duplicate ") static
Referenced by Castor3D::SamplerManager::Create(), Castor3D::AnimatedObjectGroupManager::Create(), Castor3D::SceneNodeManager::Create(), Castor3D::GeometryManager::Create(), Castor3D::ObjectManager< Castor::String, AnimatedObjectGroup >::Create(), Castor3D::Manager< Castor::String, Sampler, Engine, ResourceManagerEngineGetter >::Create(), and Castor3D::Manager< Castor::String, Sampler, Engine, ResourceManagerEngineGetter >::Insert().
WARNING_MANAGER_NULL_OBJECT
const xchar* Castor3D::WARNING_MANAGER_NULL_OBJECT = cuT("Manager::Insert - nullptr ") static
Referenced by Castor3D::Manager< Castor::String, Sampler, Engine, ResourceManagerEngineGetter >::Insert().