Castor3D: castor3d::ChunkWriterBase Class Reference
castor3d::ChunkWriterBase Class Reference
#include <ChunkWriter.hpp>
Static Public Member Functions
static bool write (uint8_t const *begin, uint8_t const *end, ChunkType type, BinaryChunk &chunk) noexcept
Writes a subchunk value into a chunk.
Member Function Documentation
write()
static bool castor3d::ChunkWriterBase::write (uint8_t const * begin, uint8_t const * end, ChunkType type, BinaryChunk & chunk) inline static noexcept
Writes a subchunk value into a chunk.
Parameters
[in] begin The values begin
[in] end The values end
[in] type The subchunk type
[in] chunk The chunk
Returns
false if any error occured
References castor3d::BinaryChunk::setData().
Referenced by castor3d::ChunkWriter< castor::Path >::write(), castor3d::ChunkWriter< castor::String >::write(), castor3d::ChunkWriter< T >::write(), and castor3d::ChunkWriter< T >::write().
The documentation for this class was generated from the following file:
Castor3D/Binary/ChunkWriter.hpp