Castor3D: castor3d::shader::LightingModel Class Reference
castor3d::shader::LightingModel Class Reference abstract
#include <GlslLighting.hpp>
Public Member Functions
C3D_API LightingModel (sdw::ShaderWriter &writer, Utils &utils, ShadowOptions shadowOptions, SssProfiles const *sssProfiles, bool isOpaqueProgram, std::string prefix)
virtual C3D_API ~LightingModel ()=default
virtual C3D_API sdw::Vec3 combine (sdw::Vec3 const &directDiffuse, sdw::Vec3 const &indirectDiffuse, sdw::Vec3 const &directSpecular, sdw::Vec3 const &indirectSpecular, sdw::Vec3 const &ambient, sdw::Vec3 const &indirectAmbient, sdw::Float const &ambientOcclusion, sdw::Vec3 const &emissive, sdw::Vec3 const &reflected, sdw::Vec3 const &refracted, sdw::Vec3 const &materialAlbedo)=0
virtual C3D_API std::unique_ptr< LightMaterial > declMaterial (std::string const &name)=0
virtual C3D_API ReflectionModelPtr getReflectionModel (uint32_t &envMapBinding, uint32_t envMapSet) const =0
Deferred renderring
C3D_API void declareDirectionalModel (bool lightUbo, uint32_t lightBinding, uint32_t lightSet, uint32_t &shadowMapBinding, uint32_t shadowMapSet)
C3D_API void declarePointModel (bool lightUbo, uint32_t lightBinding, uint32_t lightSet, uint32_t &shadowMapBinding, uint32_t shadowMapSet)
C3D_API void declareSpotModel (bool lightUbo, uint32_t lightBinding, uint32_t lightSet, uint32_t &shadowMapBinding, uint32_t shadowMapSet)
Diffuse + Specular
virtual C3D_API void compute (DirectionalLight const &light, LightMaterial const &material, Surface const &surface, sdw::Vec3 const &worldEye, sdw::Int const &receivesShadows, OutputComponents &output) const =0
virtual C3D_API void compute (PointLight const &light, LightMaterial const &material, Surface const &surface, sdw::Vec3 const &worldEye, sdw::Int const &receivesShadows, OutputComponents &output) const =0
virtual C3D_API void compute (SpotLight const &light, LightMaterial const &material, Surface const &surface, sdw::Vec3 const &worldEye, sdw::Int const &receivesShadows, OutputComponents &output) const =0
virtual C3D_API void computeMapContributions (PassFlags const &passFlags, TextureFlagsArray const &textures, TextureConfigurations const &textureConfigs, TextureAnimations const &textureAnims, sdw::Array< sdw::CombinedImage2DRgba32 > const &maps, sdw::UVec4 const &textures0, sdw::UVec4 const &textures1, sdw::Vec3 &texCoords, sdw::Vec3 &normal, sdw::Vec3 &tangent, sdw::Vec3 &bitangent, sdw::Vec3 &emissive, sdw::Float &opacity, sdw::Float &occlusion, sdw::Float &transmittance, LightMaterial &lightMat, sdw::Vec3 &tangentSpaceViewPosition, sdw::Vec3 &tangentSpaceFragPosition)=0
Diffuse only
virtual C3D_API sdw::Vec3 computeDiffuse (DirectionalLight const &light, LightMaterial const &material, Surface const &surface, sdw::Vec3 const &worldEye, sdw::Int const &receivesShadows) const =0
virtual C3D_API sdw::Vec3 computeDiffuse (PointLight const &light, LightMaterial const &material, Surface const &surface, sdw::Vec3 const &worldEye, sdw::Int const &receivesShadows) const =0
virtual C3D_API sdw::Vec3 computeDiffuse (SpotLight const &light, LightMaterial const &material, Surface const &surface, sdw::Vec3 const &worldEye, sdw::Int const &receivesShadows) const =0
virtual C3D_API void computeMapDiffuseContributions (PassFlags const &passFlags, TextureFlagsArray const &textures, TextureConfigurations const &textureConfigs, TextureAnimations const &textureAnims, sdw::Array< sdw::CombinedImage2DRgba32 > const &maps, sdw::UVec4 const &textures0, sdw::UVec4 const &textures1, sdw::Vec3 const &texCoords, sdw::Vec3 &emissive, sdw::Float &opacity, sdw::Float &occlusion, LightMaterial &lightMat)=0
Light accessors
sdw::ShaderWriter & m_writer
Utils & m_utils
std::unique_ptr< sdw::Struct > m_type
std::unique_ptr< sdw::Ssbo > m_ssbo
std::unique_ptr< sdw::RImageBufferRgba32 > m_tbo
bool m_isOpaqueProgram
std::string m_prefix
std::shared_ptr< Shadow > m_shadowModel
std::shared_ptr< SssTransmittance > m_sssTransmittance
sdw::Function< sdw::Vec3, sdw::InVec3, sdw::InVec4, sdw::InUInt > m_getCascadeFactors
sdw::Function< sdw::Vec3, sdw::InVec3, sdw::InVec4Array, sdw::InUInt > m_getTileFactors
sdw::Function< shader::Light, sdw::InOutUInt > m_getBaseLight
sdw::Function< shader::DirectionalLight, sdw::InUInt > m_getDirectionalLight
sdw::Function< shader::PointLight, sdw::InUInt > m_getPointLight
sdw::Function< shader::SpotLight, sdw::InUInt > m_getSpotLight
C3D_API DirectionalLight getDirectionalLight (sdw::UInt const &index) const
C3D_API PointLight getPointLight (sdw::UInt const &index) const
C3D_API SpotLight getSpotLight (sdw::UInt const &index) const
Shadow & getShadowModel () const
C3D_API Light getBaseLight (sdw::UInt &offset) const
C3D_API void doDeclareLightsBuffer (uint32_t binding, uint32_t set)
C3D_API void doDeclareDirectionalLightUbo (uint32_t binding, uint32_t set)
C3D_API void doDeclarePointLightUbo (uint32_t binding, uint32_t set)
C3D_API void doDeclareSpotLightUbo (uint32_t binding, uint32_t set)
C3D_API void doDeclareGetBaseLight ()
C3D_API void doDeclareGetDirectionalLight ()
C3D_API void doDeclareGetPointLight ()
C3D_API void doDeclareGetSpotLight ()
C3D_API void doDeclareGetCascadeFactors ()
virtual void doDeclareModel ()=0
virtual void doDeclareComputeDirectionalLight ()=0
virtual void doDeclareComputePointLight ()=0
virtual void doDeclareComputeSpotLight ()=0
virtual void doDeclareDiffuseModel ()=0
virtual void doDeclareComputeDirectionalLightDiffuse ()=0
virtual void doDeclareComputePointLightDiffuse ()=0
virtual void doDeclareComputeSpotLightDiffuse ()=0
Diffuse + Specular
C3D_API void declareModel (uint32_t lightsBufBinding, uint32_t lightsBufSet, uint32_t &shadowMapBinding, uint32_t shadowMapSet)
C3D_API void computeCombined (LightMaterial const &material, SceneData const &sceneData, Surface const &surface, sdw::Vec3 const &worldEye, sdw::Int const &receivesShadows, OutputComponents &output) const
static C3D_API LightingModelPtr createModel (Utils &utils, castor::String const &name, uint32_t lightsBufBinding, uint32_t lightsBufSet, ShadowOptions const &shadows, SssProfiles const *sssProfiles, uint32_t &shadowMapBinding, uint32_t shadowMapSet, bool isOpaqueProgram)
template<typename LightsBufBindingT >
static LightingModelPtr createModelT (Utils &utils, castor::String const &name, LightsBufBindingT lightsBufBinding, uint32_t lightsBufSet, ShadowOptions const &shadows, SssProfiles const *sssProfiles, uint32_t &shadowMapBinding, uint32_t shadowMapSet, bool isOpaqueProgram)
template<typename LightBindingT >
static LightingModelPtr createModel (Utils &utils, castor::String const &name, LightType light, LightBindingT lightBinding, uint32_t lightSet, bool lightUbo, ShadowOptions const &shadows, SssProfiles const *sssProfiles, uint32_t &shadowMapBinding, uint32_t shadowMapSet)
Diffuse only
C3D_API void declareDiffuseModel (uint32_t lightsBufBinding, uint32_t lightsBufSet, uint32_t &shadowMapBinding, uint32_t shadowMapSet)
C3D_API sdw::Vec3 computeCombinedDiffuse (LightMaterial const &material, SceneData const &sceneData, Surface const &surface, sdw::Vec3 const &worldEye, sdw::Int const &receivesShadows) const
static C3D_API LightingModelPtr createDiffuseModel (Utils &utils, castor::String const &name, uint32_t lightsBufBinding, uint32_t lightsBufSet, ShadowOptions const &shadows, uint32_t &shadowMapBinding, uint32_t shadowMapSet, bool isOpaqueProgram)
template<typename LightsBufBindingT >
static LightingModelPtr createDiffuseModelT (Utils &utils, castor::String const &name, LightsBufBindingT lightsBufBinding, uint32_t lightsBufSet, ShadowOptions const &shadows, uint32_t &shadowMapBinding, uint32_t shadowMapSet, bool isOpaqueProgram)
Constructor & Destructor Documentation
LightingModel()
C3D_API castor3d::shader::LightingModel::LightingModel (sdw::ShaderWriter & writer, Utils & utils, ShadowOptions shadowOptions, SssProfiles const * sssProfiles, bool isOpaqueProgram, std::string prefix)
~LightingModel()
virtual C3D_API castor3d::shader::LightingModel::~LightingModel () virtual default
Member Function Documentation
combine()
virtual C3D_API sdw::Vec3 castor3d::shader::LightingModel::combine (sdw::Vec3 const & directDiffuse, sdw::Vec3 const & indirectDiffuse, sdw::Vec3 const & directSpecular, sdw::Vec3 const & indirectSpecular, sdw::Vec3 const & ambient, sdw::Vec3 const & indirectAmbient, sdw::Float const & ambientOcclusion, sdw::Vec3 const & emissive, sdw::Vec3 const & reflected, sdw::Vec3 const & refracted, sdw::Vec3 const & materialAlbedo) pure virtual
Implemented in castor3d::shader::PbrLightingModel, and castor3d::shader::PhongLightingModel.
compute() [1/3]
virtual C3D_API void castor3d::shader::LightingModel::compute (DirectionalLight const & light, LightMaterial const & material, Surface const & surface, sdw::Vec3 const & worldEye, sdw::Int const & receivesShadows, OutputComponents & output) const pure virtual
Implemented in castor3d::shader::PbrLightingModel, and castor3d::shader::PhongLightingModel.
compute() [2/3]
virtual C3D_API void castor3d::shader::LightingModel::compute (PointLight const & light, LightMaterial const & material, Surface const & surface, sdw::Vec3 const & worldEye, sdw::Int const & receivesShadows, OutputComponents & output) const pure virtual
Implemented in castor3d::shader::PbrLightingModel, and castor3d::shader::PhongLightingModel.
compute() [3/3]
virtual C3D_API void castor3d::shader::LightingModel::compute (SpotLight const & light, LightMaterial const & material, Surface const & surface, sdw::Vec3 const & worldEye, sdw::Int const & receivesShadows, OutputComponents & output) const pure virtual
Implemented in castor3d::shader::PbrLightingModel, and castor3d::shader::PhongLightingModel.
computeCombined()
C3D_API void castor3d::shader::LightingModel::computeCombined (LightMaterial const & material, SceneData const & sceneData, Surface const & surface, sdw::Vec3 const & worldEye, sdw::Int const & receivesShadows, OutputComponents & output) const
computeCombinedDiffuse()
C3D_API sdw::Vec3 castor3d::shader::LightingModel::computeCombinedDiffuse (LightMaterial const & material, SceneData const & sceneData, Surface const & surface, sdw::Vec3 const & worldEye, sdw::Int const & receivesShadows) const
computeDiffuse() [1/3]
virtual C3D_API sdw::Vec3 castor3d::shader::LightingModel::computeDiffuse (DirectionalLight const & light, LightMaterial const & material, Surface const & surface, sdw::Vec3 const & worldEye, sdw::Int const & receivesShadows) const pure virtual
Implemented in castor3d::shader::PbrLightingModel, and castor3d::shader::PhongLightingModel.
computeDiffuse() [2/3]
virtual C3D_API sdw::Vec3 castor3d::shader::LightingModel::computeDiffuse (PointLight const & light, LightMaterial const & material, Surface const & surface, sdw::Vec3 const & worldEye, sdw::Int const & receivesShadows) const pure virtual
Implemented in castor3d::shader::PbrLightingModel, and castor3d::shader::PhongLightingModel.
computeDiffuse() [3/3]
virtual C3D_API sdw::Vec3 castor3d::shader::LightingModel::computeDiffuse (SpotLight const & light, LightMaterial const & material, Surface const & surface, sdw::Vec3 const & worldEye, sdw::Int const & receivesShadows) const pure virtual
Implemented in castor3d::shader::PbrLightingModel, and castor3d::shader::PhongLightingModel.
computeMapContributions()
virtual C3D_API void castor3d::shader::LightingModel::computeMapContributions (PassFlags const & passFlags, TextureFlagsArray const & textures, TextureConfigurations const & textureConfigs, TextureAnimations const & textureAnims, sdw::Array< sdw::CombinedImage2DRgba32 > const & maps, sdw::UVec4 const & textures0, sdw::UVec4 const & textures1, sdw::Vec3 & texCoords, sdw::Vec3 & normal, sdw::Vec3 & tangent, sdw::Vec3 & bitangent, sdw::Vec3 & emissive, sdw::Float & opacity, sdw::Float & occlusion, sdw::Float & transmittance, LightMaterial & lightMat, sdw::Vec3 & tangentSpaceViewPosition, sdw::Vec3 & tangentSpaceFragPosition) pure virtual
Implemented in castor3d::shader::PbrLightingModel, and castor3d::shader::PhongLightingModel.
computeMapDiffuseContributions()
virtual C3D_API void castor3d::shader::LightingModel::computeMapDiffuseContributions (PassFlags const & passFlags, TextureFlagsArray const & textures, TextureConfigurations const & textureConfigs, TextureAnimations const & textureAnims, sdw::Array< sdw::CombinedImage2DRgba32 > const & maps, sdw::UVec4 const & textures0, sdw::UVec4 const & textures1, sdw::Vec3 const & texCoords, sdw::Vec3 & emissive, sdw::Float & opacity, sdw::Float & occlusion, LightMaterial & lightMat) pure virtual
Implemented in castor3d::shader::PbrLightingModel, and castor3d::shader::PhongLightingModel.
createDiffuseModel()
static C3D_API LightingModelPtr castor3d::shader::LightingModel::createDiffuseModel (Utils & utils, castor::String const & name, uint32_t lightsBufBinding, uint32_t lightsBufSet, ShadowOptions const & shadows, uint32_t & shadowMapBinding, uint32_t shadowMapSet, bool isOpaqueProgram) static
Referenced by createDiffuseModelT().
createDiffuseModelT()
template<typename LightsBufBindingT > static LightingModelPtr castor3d::shader::LightingModel::createDiffuseModelT (Utils & utils, castor::String const & name, LightsBufBindingT lightsBufBinding, uint32_t lightsBufSet, ShadowOptions const & shadows, uint32_t & shadowMapBinding, uint32_t shadowMapSet, bool isOpaqueProgram) inline static
References createDiffuseModel().
createModel() [1/2]
template<typename LightBindingT > static LightingModelPtr castor3d::shader::LightingModel::createModel (Utils & utils, castor::String const & name, LightType light, LightBindingT lightBinding, uint32_t lightSet, bool lightUbo, ShadowOptions const & shadows, SssProfiles const * sssProfiles, uint32_t & shadowMapBinding, uint32_t shadowMapSet) inline static
References createModel().
createModel() [2/2]
static C3D_API LightingModelPtr castor3d::shader::LightingModel::createModel (Utils & utils, castor::String const & name, uint32_t lightsBufBinding, uint32_t lightsBufSet, ShadowOptions const & shadows, SssProfiles const * sssProfiles, uint32_t & shadowMapBinding, uint32_t shadowMapSet, bool isOpaqueProgram) static
Referenced by createModel(), and createModelT().
createModelT()
template<typename LightsBufBindingT > static LightingModelPtr castor3d::shader::LightingModel::createModelT (Utils & utils, castor::String const & name, LightsBufBindingT lightsBufBinding, uint32_t lightsBufSet, ShadowOptions const & shadows, SssProfiles const * sssProfiles, uint32_t & shadowMapBinding, uint32_t shadowMapSet, bool isOpaqueProgram) inline static
References createModel().
declareDiffuseModel()
C3D_API void castor3d::shader::LightingModel::declareDiffuseModel (uint32_t lightsBufBinding, uint32_t lightsBufSet, uint32_t & shadowMapBinding, uint32_t shadowMapSet)
declareDirectionalModel()
C3D_API void castor3d::shader::LightingModel::declareDirectionalModel (bool lightUbo, uint32_t lightBinding, uint32_t lightSet, uint32_t & shadowMapBinding, uint32_t shadowMapSet)
declareModel()
C3D_API void castor3d::shader::LightingModel::declareModel (uint32_t lightsBufBinding, uint32_t lightsBufSet, uint32_t & shadowMapBinding, uint32_t shadowMapSet)
declarePointModel()
C3D_API void castor3d::shader::LightingModel::declarePointModel (bool lightUbo, uint32_t lightBinding, uint32_t lightSet, uint32_t & shadowMapBinding, uint32_t shadowMapSet)
declareSpotModel()
C3D_API void castor3d::shader::LightingModel::declareSpotModel (bool lightUbo, uint32_t lightBinding, uint32_t lightSet, uint32_t & shadowMapBinding, uint32_t shadowMapSet)
declMaterial()
virtual C3D_API std::unique_ptr< LightMaterial > castor3d::shader::LightingModel::declMaterial (std::string const & name) pure virtual
Implemented in castor3d::shader::PbrMRLightingModel, castor3d::shader::PbrSGLightingModel, and castor3d::shader::PhongLightingModel.
doDeclareComputeDirectionalLight()
virtual void castor3d::shader::LightingModel::doDeclareComputeDirectionalLight () protected pure virtual
Implemented in castor3d::shader::PbrLightingModel, and castor3d::shader::PhongLightingModel.
doDeclareComputeDirectionalLightDiffuse()
virtual void castor3d::shader::LightingModel::doDeclareComputeDirectionalLightDiffuse () protected pure virtual
Implemented in castor3d::shader::PbrLightingModel, and castor3d::shader::PhongLightingModel.
doDeclareComputePointLight()
virtual void castor3d::shader::LightingModel::doDeclareComputePointLight () protected pure virtual
Implemented in castor3d::shader::PbrLightingModel, and castor3d::shader::PhongLightingModel.
doDeclareComputePointLightDiffuse()
virtual void castor3d::shader::LightingModel::doDeclareComputePointLightDiffuse () protected pure virtual
Implemented in castor3d::shader::PbrLightingModel, and castor3d::shader::PhongLightingModel.
doDeclareComputeSpotLight()
virtual void castor3d::shader::LightingModel::doDeclareComputeSpotLight () protected pure virtual
Implemented in castor3d::shader::PbrLightingModel, and castor3d::shader::PhongLightingModel.
doDeclareComputeSpotLightDiffuse()
virtual void castor3d::shader::LightingModel::doDeclareComputeSpotLightDiffuse () protected pure virtual
Implemented in castor3d::shader::PbrLightingModel, and castor3d::shader::PhongLightingModel.
doDeclareDiffuseModel()
virtual void castor3d::shader::LightingModel::doDeclareDiffuseModel () protected pure virtual
Implemented in castor3d::shader::PbrLightingModel, and castor3d::shader::PhongLightingModel.
doDeclareDirectionalLightUbo()
C3D_API void castor3d::shader::LightingModel::doDeclareDirectionalLightUbo (uint32_t binding, uint32_t set) protected
doDeclareGetBaseLight()
C3D_API void castor3d::shader::LightingModel::doDeclareGetBaseLight () protected
doDeclareGetCascadeFactors()
C3D_API void castor3d::shader::LightingModel::doDeclareGetCascadeFactors () protected
doDeclareGetDirectionalLight()
C3D_API void castor3d::shader::LightingModel::doDeclareGetDirectionalLight () protected
doDeclareGetPointLight()
C3D_API void castor3d::shader::LightingModel::doDeclareGetPointLight () protected
doDeclareGetSpotLight()
C3D_API void castor3d::shader::LightingModel::doDeclareGetSpotLight () protected
doDeclareLightsBuffer()
C3D_API void castor3d::shader::LightingModel::doDeclareLightsBuffer (uint32_t binding, uint32_t set) protected
doDeclareModel()
virtual void castor3d::shader::LightingModel::doDeclareModel () protected pure virtual
Implemented in castor3d::shader::PbrLightingModel, and castor3d::shader::PhongLightingModel.
doDeclarePointLightUbo()
C3D_API void castor3d::shader::LightingModel::doDeclarePointLightUbo (uint32_t binding, uint32_t set) protected
doDeclareSpotLightUbo()
C3D_API void castor3d::shader::LightingModel::doDeclareSpotLightUbo (uint32_t binding, uint32_t set) protected
getBaseLight()
C3D_API Light castor3d::shader::LightingModel::getBaseLight (sdw::UInt & offset) const protected
getDirectionalLight()
C3D_API DirectionalLight castor3d::shader::LightingModel::getDirectionalLight (sdw::UInt const & index) const
getPointLight()
C3D_API PointLight castor3d::shader::LightingModel::getPointLight (sdw::UInt const & index) const
getReflectionModel()
virtual C3D_API ReflectionModelPtr castor3d::shader::LightingModel::getReflectionModel (uint32_t & envMapBinding, uint32_t envMapSet) const pure virtual
Implemented in castor3d::shader::PbrLightingModel, and castor3d::shader::PhongLightingModel.
getShadowModel()
Shadow & castor3d::shader::LightingModel::getShadowModel () const inline
References m_shadowModel.
getSpotLight()
C3D_API SpotLight castor3d::shader::LightingModel::getSpotLight (sdw::UInt const & index) const
Member Data Documentation
m_getBaseLight
sdw::Function< shader::Light , sdw::InOutUInt > castor3d::shader::LightingModel::m_getBaseLight protected
m_getCascadeFactors
sdw::Function< sdw::Vec3 , sdw::InVec3 , sdw::InVec4 , sdw::InUInt > castor3d::shader::LightingModel::m_getCascadeFactors protected
m_getDirectionalLight
sdw::Function< shader::DirectionalLight , sdw::InUInt > castor3d::shader::LightingModel::m_getDirectionalLight protected
m_getPointLight
sdw::Function< shader::PointLight , sdw::InUInt > castor3d::shader::LightingModel::m_getPointLight protected
m_getSpotLight
sdw::Function< shader::SpotLight , sdw::InUInt > castor3d::shader::LightingModel::m_getSpotLight protected
m_getTileFactors
sdw::Function< sdw::Vec3 , sdw::InVec3 , sdw::InVec4Array , sdw::InUInt > castor3d::shader::LightingModel::m_getTileFactors protected
m_isOpaqueProgram
bool castor3d::shader::LightingModel::m_isOpaqueProgram protected
m_prefix
std::string castor3d::shader::LightingModel::m_prefix protected
m_shadowModel
std::shared_ptr< Shadow > castor3d::shader::LightingModel::m_shadowModel protected
Referenced by getShadowModel().
m_ssbo
std::unique_ptr< sdw::Ssbo > castor3d::shader::LightingModel::m_ssbo protected
m_sssTransmittance
std::shared_ptr< SssTransmittance > castor3d::shader::LightingModel::m_sssTransmittance protected
m_tbo
std::unique_ptr< sdw::RImageBufferRgba32 > castor3d::shader::LightingModel::m_tbo protected
m_type
std::unique_ptr< sdw::Struct > castor3d::shader::LightingModel::m_type protected
m_utils
Utils& castor3d::shader::LightingModel::m_utils protected
m_writer
sdw::ShaderWriter& castor3d::shader::LightingModel::m_writer protected
The documentation for this class was generated from the following file:
Shader/Shaders/GlslLighting.hpp