Castor3D: castor3d Namespace Reference
castor3d Namespace Reference
Namespaces
details
shader
Classes
class Animable
Animable public interface.
class AnimatedMesh
Represents the animated submeshes.
class AnimatedObject
Represents the animated objects.
class AnimatedObjectGroup
Class which represents the animated object groups.
class AnimatedSkeleton
Represents the animated objects.
class Animation
Animation base class.
class AnimationInstance
Animation instance class.
class AnimationKeyFrame
Key frames are the frames where the animation must be at a precise state.
class AtomicCounterBuffer
Atomic counter buffer interface.
class BackBuffers
Back buffers class.
class BillboardBase
Billboards list.
class BillboardList
Billboards list.
struct BillboardRenderNode
Helper structure used to render billboards.
class BillboardUbo
Model Uniform buffer management.
class BinaryChunk
Binary data chunk base class.
class BinaryParser
class BinaryParser< Animation >
Animation binary loader.
class BinaryParser< Bone >
Animable binary loader.
class BinaryParser< BonesComponent >
BonesComponent loader.
class BinaryParser< Mesh >
MovableObject loader.
class BinaryParser< MeshAnimation >
MeshAnimation binary loader.
class BinaryParser< MeshAnimationKeyFrame >
MeshAnimationKeyFrame binary loader.
class BinaryParser< Skeleton >
Animable binary loader.
class BinaryParser< SkeletonAnimation >
SkeletonAnimation binary loader.
class BinaryParser< SkeletonAnimationBone >
MovingBone binary loader.
class BinaryParser< SkeletonAnimationKeyFrame >
SkeletonAnimationKeyFrame binary loader.
class BinaryParser< SkeletonAnimationNode >
MovingBone binary loader.
class BinaryParser< SkeletonAnimationObject >
SkeletonAnimationObject binary loader.
class BinaryParser< Submesh >
MovableObject loader.
class BinaryParserBase
Binary data chunk writer/reader base class.
class BinaryWriter
class BinaryWriter< Animation >
Animation binary loader.
class BinaryWriter< Bone >
Animable binary loader.
class BinaryWriter< BonesComponent >
BonesComponent loader.
class BinaryWriter< Mesh >
MovableObject loader.
class BinaryWriter< MeshAnimation >
MeshAnimation binary loader.
class BinaryWriter< MeshAnimationKeyFrame >
MeshAnimationKeyFrame binary loader.
class BinaryWriter< Skeleton >
Animable binary loader.
class BinaryWriter< SkeletonAnimation >
SkeletonAnimation binary loader.
class BinaryWriter< SkeletonAnimationBone >
MovingBone binary loader.
class BinaryWriter< SkeletonAnimationKeyFrame >
SkeletonAnimationKeyFrame binary loader.
class BinaryWriter< SkeletonAnimationNode >
MovingBone binary loader.
class BinaryWriter< SkeletonAnimationObject >
SkeletonAnimationObject binary loader.
class BinaryWriter< Submesh >
MovableObject loader.
class BinaryWriterBase
Binary data chunk writer/reader base class.
class BlendState
Blending configurations grouping class.
class Bone
Class holding bone data.
class BonedVertex
Vertex with bones infos representation.
class BonesComponent
The submesh component used for skinning.
class BonesInstantiationComponent
The submesh component used for instantiated submeshes with bones.
class BorderPanelOverlay
A rectangular overlay with a border.
class BrdfPrefilter
Class used to render colour equirectangular textures to cube maps.
class BufferDeclaration
Description of all elements in a vertex buffer.
struct BufferElementDeclaration
Buffer element description.
class BufferElementGroup
Holds data of a vertex buffer elements group.
class Cache
Base class for an element cache.
class Cache< Material, castor::String >
Material collection, with additional functions.
class Cache< Overlay, castor::String >
Overlay collection, with additional add and remove functions to manage Z-Index.
class Cache< Plugin, castor::String >
Plug-ins cache.
class CacheBase
Base class for an element cache.
struct CacheTraits
Helper structure to specialise a cache behaviour.
struct CacheTraits< AnimatedObjectGroup, KeyType >
Helper structure to specialise a cache behaviour.
struct CacheTraits< FrameListener, KeyType >
Helper structure to specialise a cache behaviour.
struct CacheTraits< Material, KeyType >
Helper structure to specialise a cache behaviour.
struct CacheTraits< Mesh, KeyType >
Helper structure to specialise a cache behaviour.
struct CacheTraits< Overlay, KeyType >
Helper structure to specialise a cache behaviour.
struct CacheTraits< Plugin, KeyType >
Helper structure to specialise a cache behaviour.
struct CacheTraits< RenderTechnique, KeyType >
Helper structure to specialise a cache behaviour.
struct CacheTraits< RenderWindow, KeyType >
Helper structure to specialise a cache behaviour.
struct CacheTraits< Sampler, KeyType >
Helper structure to specialise a cache behaviour.
struct CacheTraits< Scene, KeyType >
Helper structure to specialise a cache behaviour.
class CacheView
View on a resource cache.
class Camera
Class which represents a Camera.
class ChunkParser
Chunk parser.
class ChunkParser< castor::Path >
ChunkParser specialisation for castor::Path.
class ChunkParser< castor::String >
ChunkParser specialisation for castor::String.
class ChunkParserBase
Chunk parser.
struct ChunkTyper
Helper structure to find ChunkType from a type.
struct ChunkTyper< Animation >
Helper structure to find ChunkType from a type.
struct ChunkTyper< Bone >
Helper structure to find ChunkType from a type.
struct ChunkTyper< BonesComponent >
Helper structure to find ChunkType from a type.
struct ChunkTyper< Mesh >
Helper structure to find ChunkType from a type.
struct ChunkTyper< MeshAnimation >
Helper structure to find ChunkType from a type.
struct ChunkTyper< MeshAnimationKeyFrame >
Helper structure to find ChunkType from a type.
struct ChunkTyper< Skeleton >
Helper structure to find ChunkType from a type.
struct ChunkTyper< SkeletonAnimation >
Helper structure to find ChunkType from a type.
struct ChunkTyper< SkeletonAnimationBone >
Helper structure to find ChunkType from a type.
struct ChunkTyper< SkeletonAnimationKeyFrame >
Helper structure to find ChunkType from a type.
struct ChunkTyper< SkeletonAnimationNode >
Helper structure to find ChunkType from a type.
struct ChunkTyper< SkeletonAnimationObject >
Helper structure to find ChunkType from a type.
struct ChunkTyper< Submesh >
Helper structure to find ChunkType from a type.
class ChunkWriter
Chunk data writer.
class ChunkWriter< castor::Path >
ChunkWriter specialisation for castor::Path.
class ChunkWriter< castor::String >
ChunkWriter specialisation for castor::String.
class ChunkWriterBase
Chunk writer.
class CleanupEvent
Cleaner event.
class CmshImporter
Used to import meshes from cmsh files.
class ColourRenderBuffer
Render buffer receiving colour PixelComponents.
class ColourSkybox
A skybox with no image but a colour.
class ComputeParticleSystem
Compute shader Particle system implementation.
class ComputePipeline
The computing pipeline.
class Cone
The cone is a basic primitive, with a parametrable number of faces.
class Context
Class which holds the rendering context.
class CpuBuffer
3D Buffer management class
class CpuParticleSystem
CPU only Particle system implementation.
class Cube
The cube representation.
class Cylinder
The cylinder representation.
class DebugOverlays
Debug overlays class.
class DeferredRendering
The deferred rendering class.
class DepthPass
Deferred lighting Render technique pass.
class DepthStencilRenderBuffer
Render buffer receiving depth and/or stencil PixelComponents.
class DepthStencilState
Depth and stencil buffers configurations class.
class DirectionalLight
Class which represents a Directional Light.
class DirectionalLightPass
Directional light pass.
struct DistanceRenderNode
Helper structure used to render objects.
struct DistanceRenderNodeBase
Helper structure used to render billboards.
class DividerPlugin
Divider Plugin class.
struct ElementProducer
struct ElementProducer< RenderTarget, KeyType >
struct ElementProducer< ShaderProgram, KeyType >
struct ElementTyper
class Engine
Main System.
class EnvironmentMap
Reflection mapping implementation.
class EnvironmentMapPass
Reflection mapping pass implementation.
class EnvironmentPrefilter
Class used to render colour equirectangular textures to cube maps.
class EventHandler
Description of an event handler, class that can receive event.
class Face
Face implementation.
struct FaceIndices
Holds the 3 vertex indices.
struct FaceInfos
Holds face informations.
class FinalCombinePass
Pass used to combine the transparent and opaque passes.
struct FinalCombineProgram
Program used to combine the transparent and opaque passes.
class Fog
Fog implementation.
class FontTexture
Contains the font and the texture assiated to this font.
class ForwardRenderTechniquePass
Forward render technique pass class.
class FrameBuffer
Frame buffer class.
class FrameBufferAttachment
Description of an attachment between a frame buffer and a render buffer.
class FrameEvent
The interface which represents a frame event.
class FrameListener
User event synchronisation class.
class Frustum
Implements a frustum and the checks related to frustum culling.
class FunctorEvent
Functor event.
class GaussianBlur
Gaussian blur pass.
class Generator
class GeneratorPlugin
Generator Plugin class.
class GenericPlugin
Generic Plugin class.
class Geometry
Geometry handler class.
class GeometryBuffers
Geometry buffers holder.
class GpInfoUbo
class GpuBuffer
Base class for renderer dependant buffers.
struct GpuBufferBuddyAllocatorTraits
struct GpuBufferOffset
class GpuBufferPool
Buddy allocator implementation.
class GpuInformations
Holds GPU informations.
class GpuObjectTracker
Tracks objects allocated on GPU.
class GpuQuery
GPU query implementation.
struct GroupAnimation
class HandlerEvent
Description of a handler event.
class HdrConfig
HDR configuration (expsure and gamma correction).
class HdrConfigUbo
HDR configuration Uniform buffer management.
class IblTextures
Holds environment maps used in IBL.
class Icosahedron
The icosahedron representation.
class Importer
Base class for external file import.
class ImporterFactory
The importer factory.
class ImporterPlugin
Importer Plugin class.
class IndexBuffer
Index buffer representation.
class IndexMapping
A submesh component for faces.
class InitialiseEvent
Initialiser event.
class InstantiationComponent
The submesh component used for hardware instantiation.
struct InterleavedVertexT
Holds the all components of a vertex.
class Interpolator
Template class which handles the interpolations, would it be quaternion, point, real, ... interpolations.
class InterpolatorT
Template class which handles the interpolations, would it be quaternion, point, real, ... interpolations.
class InterpolatorT< castor::Quaternion, InterpolatorType::eLinear >
Class which handles the Quaternion linear interpolations.
class InterpolatorT< Type, InterpolatorType::eLinear >
Partial specialisation of Interpolator, for eINTERPOLATOR_MODE_LINEAR.
class InterpolatorT< Type, InterpolatorType::eNearest >
Partial specialisation of Interpolator, for eINTERPOLATOR_MODE_NONE.
struct IsMatrixType
Tells if a UniformType is a matrix type.
struct IsOneType
Tells if a UniformType is a single value type.
struct IsPointType
Tells if a UniformType is a point type.
class IViewportImpl
Render API specific viewport implementation.
class IWindowHandle
Platform dependant window handle implementation.
class KeyboardEvent
Description of a keyboard event.
struct KeyboardState
Structure holding mouse state.
class LegacyPass
Definition of a traditional (pre-PBR) pass.
class LegacyPassBuffer
SSBO holding the LegacyPasses data.
class Light
Light source implementation.
class LightCategory
Holds light components.
class LightFactory
The light source factory.
class LightingPass
Handles the light passes.
class LightPass
Base class for all light passes.
class LightPassShadow
Base class for all light passes with shadow.
struct LightPassShadowTraits
Traits structure to specialise light passes with shadows.
struct LightPassShadowTraits< LightType::eDirectional >
Traits structure to specialise light passes with shadows.
struct LightPassShadowTraits< LightType::ePoint >
Traits structure to specialise light passes with shadows.
struct LightPassShadowTraits< LightType::eSpot >
Traits structure to specialise light passes with shadows.
class Line
Line implementation.
class LineariseDepthPass
Depth linearisation pass, with mipmaps generation.
struct LineIndices
Holds the 2 vertex indices of a ligne.
class LinesMapping
The submesh component for lines.
class Material
Definition of a material.
class MatrixUbo
Matrices Uniform buffer management.
class Mesh
The mesh representation.
class MeshAnimation
Submesh animation class.
class MeshAnimationInstance
Mesh animation instance.
class MeshAnimationInstanceSubmesh
Class which represents the moving things.
class MeshAnimationKeyFrame
A keyframe for a mesh animation.
class MeshAnimationSubmesh
Class which represents the mesh animation submeshes.
class MeshFactory
The mesh factory.
class MeshGenerator
Mesh category is used to create a mesh's vertices, it is created by MeshFactory.
class MeshLightPass
Base class for light passes that need a mesh instead of a quad.
class MetallicRoughnessPassBuffer
SSBO holding the Passes data.
class MetallicRoughnessPbrPass
Definition of a PBR Metallic/Roughness pass.
class ModelMatrixUbo
Matrices Uniform buffer management.
class ModelUbo
Model Uniform buffer management.
class MorphComponent
The submesh component used for morphing.
struct MorphingRenderNode
Helper structure used to render animated submeshes.
class MorphingUbo
Matrices Uniform buffer management.
class MouseEvent
Description of a mouse event.
struct MouseState
Structure holding mouse state.
class MovableObject
Movable object class.
class MultisampleState
Multisample configurations grouping class.
class NonClientEventHandler
Description of an event handler, class that can receive event.
class ObjectCache
Base class for a scene element cache.
class ObjectCache< Geometry, castor::String >
Geometry cache.
class ObjectCache< Light, castor::String >
Light cache.
class ObjectCache< SceneNode, castor::String >
SceneNode cache.
class ObjectCacheBase
Base class for a scene element cache.
struct ObjectCacheTraits
Helper structure to specialise a cache behaviour.
struct ObjectCacheTraits< BillboardList, KeyType >
Helper structure to specialise a scene cache behaviour.
struct ObjectCacheTraits< Camera, KeyType >
Helper structure to specialise a scene cache behaviour.
struct ObjectCacheTraits< Geometry, KeyType >
Helper structure to specialise a scene cache behaviour.
struct ObjectCacheTraits< Light, KeyType >
Helper structure to specialise a scene cache behaviour.
struct ObjectCacheTraits< ParticleSystem, KeyType >
Helper structure to specialise a scene cache behaviour.
struct ObjectCacheTraits< SceneNode, KeyType >
Helper structure to specialise a scene cache behaviour.
struct ObjectRenderNode
Helper structure used to render objects.
class OpaquePass
Deferred lighting Render technique pass.
class Overlay
The overlay class.
class OverlayCategory
Holds specific members for an overlay category.
struct OverlayCategorySort
Structure used to sort overlays by order.
class OverlayFactory
The mesh factory.
class OverlayRenderer
The overlay renderer.
class OverlayUbo
Matrices Uniform buffer management.
class PanelOverlay
A simple rectangular overlay.
class Parameters
Configuration parameters.
class Particle
Holds one particle data.
class ParticlePlugin
Particle plug-in class.
class ParticleSystem
Particle system implementation.
class ParticleSystemImpl
Particle system implementation base class.
class Pass
Base class of a material pass.
class PassBuffer
ShaderBuffer holding the Passes data.
struct PassRenderNode
Helper structure used link a pass and a shader program.
struct PassTyper
Helper class to retrieve a pass type from a MaterialType.
struct PassTyper< MaterialType::eLegacy >
Helper class to retrieve a pass type from a MaterialType.
struct PassTyper< MaterialType::ePbrMetallicRoughness >
Helper class to retrieve a pass type from a MaterialType.
struct PassTyper< MaterialType::ePbrSpecularGlossiness >
Helper class to retrieve a pass type from a MaterialType.
class Pattern
Pattern handler class.
class PickingPass
Picking pass, using FBO.
struct PipelineFlags
Pipeline flags.
class Plane
The plane representation.
class Plugin
Plugin Base class.
class PluginException
Plugin loading exception.
class PointLight
Class which represents a PointLight.
class PointLightPass
Point light pass.
class PostEffect
Post render effect base class.
class PostFxPlugin
Post effect plug-in class.
class ProgramInputLayout
ProgramInputLayout class.
class Projection
Projection mesh representation.
class PushUniform
Shader variable representation.
class RadianceComputer
Class used to render colour equirectangular textures to cube maps.
class RasteriserState
Rasteriser configuration class.
class RawSsaoPass
Raw ambient occlusion pass.
class Ray
Ray representation.
class ReflectionPass
The post lighting reflection pass.
class RenderBuffer
Render buffer base class.
class RenderBufferAttachment
Description of an attachment between a frame buffer and a render buffer.
class RenderColourCubeToTexture
Class used to render a colour cube texture.
class RenderColourLayerCubeToTexture
Class used to render a colour cube texture array layer.
class RenderColourLayerToTexture
Class used to render a colour texture array's layer.
class RenderColourToCube
Class used to render colour equirectangular textures to cube maps.
class RenderColourToTexture
Class used to render colour textures.
class RenderDepthCubeToTexture
Class used to render a depth cube texture.
class RenderDepthLayerCubeToTexture
Class used to render a depth cube texture array layer.
class RenderDepthLayerToTexture
Class used to render a depth texture array's layer.
class RenderDepthToTexture
Class used to render depth textures.
class RenderedObject
Handles object's visibility, and behavior with shadows.
class RendererPlugin
Renderer Plugin class.
struct RenderInfo
Holds render informations.
class RenderLoop
Render loop base class.
class RenderLoopAsync
Main System.
class RenderLoopSync
Synchronous render loop.
struct RenderNodesT
The render nodes for a specific scene.
class RenderPass
Render pass base class.
class RenderPassTimer
Class that holds data needed to compute a render pass times.
class RenderPipeline
The rendering pipeline.
class RenderQueue
Render technique base class.
class RenderSystem
The render system representation.
class RenderTarget
Render target class.
class RenderTargetCache
RenderTarget cache.
class RenderTechnique
Render technique base class.
struct RenderTechniqueFbo
Internal struct holding a complete frame buffer.
class RenderTechniquePass
Render technique pass base class.
class RenderVarianceCubeToTexture
Class used to render a variance cube texture.
class RenderVarianceToTexture
Class used to render variance textures.
class RenderWindow
Render window representation.
class Sampler
Defines a sampler for a texture.
class Scene
Scene handler class.
class SceneFileContext
The context used into parsing functions.
class SceneFileParser
CSCN file parser.
class SceneNode
The scene node handler class.
struct SceneRenderNode
Helper structure used to render submeshes.
struct SceneRenderNodes
The render nodes for a specific scene.
class SceneUbo
Scene Uniform buffer management.
class ShaderBuffer
Wrapper class to select between SSBO or TBO.
class ShaderObject
Base shader class.
class ShaderProgram
Base shader program implementation, used to share functions through the supported shader languages.
class ShaderProgramCache
Cache used to hold the shader programs. Holds it, destroys it during a rendering loop.
class ShaderStorageBuffer
Shader storage buffer interface.
class Shadow
Shadows configuration class.
class ShadowMap
Shadow mapping implementation.
class ShadowMapDirectional
Shadow mapping implementation for spot lights.
class ShadowMapPass
Shadow mapping implementation.
class ShadowMapPassDirectional
Shadow mapping implementation for spot lights.
class ShadowMapPassPoint
Shadow mapping implementation.
class ShadowMapPassSpot
Shadow mapping implementation for spot lights.
class ShadowMapPoint
Shadow mapping implementation.
class ShadowMapSpot
Shadow mapping implementation for spot lights.
class Skeleton
The skeleton, holds each bone.
class SkeletonAnimation
Skeleton animation class.
class SkeletonAnimationBone
Implementation of SkeletonAnimationObject for Bones.
class SkeletonAnimationInstance
Skeleton animation instance.
class SkeletonAnimationInstanceBone
Implementation of SkeletonAnimationObject for Bones.
class SkeletonAnimationInstanceKeyFrame
The class which manages key frames.
class SkeletonAnimationInstanceNode
Implementation of SkeletonAnimationNode for abstract nodes.
class SkeletonAnimationInstanceObject
Class which represents the moving things.
class SkeletonAnimationKeyFrame
The class which manages key frames.
class SkeletonAnimationNode
Implementation of SkeletonAnimationObject for abstract nodes.
class SkeletonAnimationObject
Class which represents the skeleton animation objects.
struct SkinningRenderNode
Helper structure used to render animated submeshes.
class SkinningUbo
Matrices Uniform buffer management.
class Skybox
Skybox implementation.
class SpecularGlossinessPassBuffer
SSBO holding the SpecularGlossinessPbrPasses data.
class SpecularGlossinessPbrPass
Definition of a PBR Metallic/Roughness pass.
class Sphere
The sphere primitive.
class SpotLight
Class which represents a SpotLight.
class SpotLightPass
Spot light pass.
class SsaoBlurPass
Ambient occlusion blur pass.
struct SsaoConfig
SSAO configuration values.
class SsaoConfigUbo
Ambient occlusion configuration UBO.
class SsaoPass
Screen Space Ambient Occlusion pass.
struct StaticRenderNode
Helper structure used to render static submeshes.
class StencilPass
Stencil pre-pass for light passes needing a mesh.
class StructuredShaderBuffer
Wrapper class to select between SSBO or TBO.
class Subdivider
Subdividers main class C3D_API.
class Submesh
The submesh representation.
struct SubmeshAnimationBufferT
Class which represents the mesh animation submeshes buffers.
class SubmeshComponent
Component for a submesh.
struct SubmeshComponentAdder
class SubmeshUtils
Submesh utility functions.
class SubsurfaceScattering
Extended pass information, related to subsurface scattering.
class SubsurfaceScatteringPass
Gaussian blur pass.
class TechniquePlugin
Render technique plug-in class.
class TextOverlay
An overlay with a text.
class TextureAttachment
Description of an attachment between a frame buffer and a texture.
class TextureImage
Texture image.
class TextureLayout
Texture base class.
class TextureProjection
Class used to render colour equirectangular textures to cube maps.
class TextureSource
Texture image source.
class TextureStorage
GPU texture storage base class.
class TextureUnit
Texture unit representation.
class ToneMapping
Tone mapping base class.
class ToneMappingPlugin
Tone mapping plug-in class.
struct TopologyNamer
Helper structure to get a topology name.
class Torus
The torus representation.
class TPushUniform
Shader variable representation with variable type.
class TransformFeedback
Transform feedback implementation.
class TransformFeedbackParticleSystem
Transform feedback Particle system implementation.
class TransparentPass
Transparent nodes pass using Weighted Blend OIT.
class TriFaceMapping
The submesh component for triangular faces.
class TUniform
Shader variable representation with variable type.
struct TypeRenderNodesByPassMap
class Uniform
Shader variable representation.
class UniformBuffer
Shader variables buffer.
class UniformBufferBinding
Represents the binding between a uniform buffer and a program.
struct UniformMatrixType
Helper structure to retrieve a matrix type from a UniformType.
struct UniformMatrixType< T, Columns, Rows, typename std::enable_if< Columns !=Rows >::type >
Helper structure to retrieve a matrix type from a UniformType.
struct UniformMatrixType< T, Columns, Rows, typename std::enable_if< Columns==Rows >::type >
Helper structure to retrieve a matrix type from a UniformType.
struct UniformSubType
Helper structure to retrieve a sub type from a UniformType.
struct UniformSubType< Type, typename std::enable_if< Type==UniformType::eBool||Type==UniformType::eVec2b||Type==UniformType::eVec3b||Type==UniformType::eVec4b||Type==UniformType::eMat2x2b||Type==UniformType::eMat2x3b||Type==UniformType::eMat2x4b||Type==UniformType::eMat3x2b||Type==UniformType::eMat3x3b||Type==UniformType::eMat3x4b||Type==UniformType::eMat4x2b||Type==UniformType::eMat4x3b||Type==UniformType::eMat4x4b >::type >
Helper structure to retrieve a frame variable type from a UniformType.
struct UniformSubType< Type, typename std::enable_if< Type==UniformType::eDouble||Type==UniformType::eVec2d||Type==UniformType::eVec3d||Type==UniformType::eVec4d||Type==UniformType::eMat2x2d||Type==UniformType::eMat2x3d||Type==UniformType::eMat2x4d||Type==UniformType::eMat3x2d||Type==UniformType::eMat3x3d||Type==UniformType::eMat3x4d||Type==UniformType::eMat4x2d||Type==UniformType::eMat4x3d||Type==UniformType::eMat4x4d >::type >
Helper structure to retrieve a frame variable type from a UniformType.
struct UniformSubType< Type, typename std::enable_if< Type==UniformType::eFloat||Type==UniformType::eVec2f||Type==UniformType::eVec3f||Type==UniformType::eVec4f||Type==UniformType::eMat2x2f||Type==UniformType::eMat2x3f||Type==UniformType::eMat2x4f||Type==UniformType::eMat3x2f||Type==UniformType::eMat3x3f||Type==UniformType::eMat3x4f||Type==UniformType::eMat4x2f||Type==UniformType::eMat4x3f||Type==UniformType::eMat4x4f >::type >
Helper structure to retrieve a frame variable type from a UniformType.
struct UniformSubType< Type, typename std::enable_if< Type==UniformType::eInt||Type==UniformType::eVec2i||Type==UniformType::eVec3i||Type==UniformType::eVec4i||Type==UniformType::eMat2x2i||Type==UniformType::eMat2x3i||Type==UniformType::eMat2x4i||Type==UniformType::eMat3x2i||Type==UniformType::eMat3x3i||Type==UniformType::eMat3x4i||Type==UniformType::eMat4x2i||Type==UniformType::eMat4x3i||Type==UniformType::eMat4x4i >::type >
Helper structure to retrieve a frame variable type from a UniformType.
struct UniformSubType< Type, typename std::enable_if< Type==UniformType::eSampler >::type >
Helper structure to retrieve a sub type from a UniformType.
struct UniformSubType< Type, typename std::enable_if< Type==UniformType::eUInt||Type==UniformType::eVec2ui||Type==UniformType::eVec3ui||Type==UniformType::eVec4ui||Type==UniformType::eMat2x2ui||Type==UniformType::eMat2x3ui||Type==UniformType::eMat2x4ui||Type==UniformType::eMat3x2ui||Type==UniformType::eMat3x3ui||Type==UniformType::eMat3x4ui||Type==UniformType::eMat4x2ui||Type==UniformType::eMat4x3ui||Type==UniformType::eMat4x4ui >::type >
Helper structure to retrieve a frame variable type from a UniformType.
struct UniformTypeName
Retrieves the name of a UniformType.
struct UniformTypeTraits
Helper structure to retrieve a frame variable type from a UniformType.
struct UniformTypeTraits< Type, typename std::enable_if< IsMatrixType< Type >::value >::type >
Helper structure to retrieve a frame variable type from a UniformType.
struct UniformTypeTraits< Type, typename std::enable_if< IsOneType< Type >::value >::type >
Helper structure to retrieve a frame variable type from a UniformType.
struct UniformTypeTraits< Type, typename std::enable_if< IsPointType< Type >::value >::type >
Helper structure to retrieve a frame variable type from a UniformType.
class UserInputEvent
Description of a user input event.
class UserInputListener
Class used to to manage the user input events.
struct VariableTypeTraits
Retrieves the VariableType of a UniformType.
struct VariableTypeTraits< Type, typename std::enable_if< Type==UniformType::eBool||Type==UniformType::eInt||Type==UniformType::eUInt||Type==UniformType::eFloat||Type==UniformType::eDouble||Type==UniformType::eSampler >::type >
Retrieves the VariableType of a UniformType.
struct VariableTypeTraits< Type, typename std::enable_if< Type==UniformType::eMat2x2b||Type==UniformType::eMat2x2i||Type==UniformType::eMat2x2ui||Type==UniformType::eMat2x2f||Type==UniformType::eMat2x2d >::type >
Retrieves the VariableType of a UniformType.
struct VariableTypeTraits< Type, typename std::enable_if< Type==UniformType::eMat2x3b||Type==UniformType::eMat2x3i||Type==UniformType::eMat2x3ui||Type==UniformType::eMat2x3f||Type==UniformType::eMat2x3d >::type >
Retrieves the VariableType of a UniformType.
struct VariableTypeTraits< Type, typename std::enable_if< Type==UniformType::eMat2x4b||Type==UniformType::eMat2x4i||Type==UniformType::eMat2x4ui||Type==UniformType::eMat2x4f||Type==UniformType::eMat2x4d >::type >
Retrieves the VariableType of a UniformType.
struct VariableTypeTraits< Type, typename std::enable_if< Type==UniformType::eMat3x2b||Type==UniformType::eMat3x2i||Type==UniformType::eMat3x2ui||Type==UniformType::eMat3x2f||Type==UniformType::eMat3x2d >::type >
Retrieves the VariableType of a UniformType.
struct VariableTypeTraits< Type, typename std::enable_if< Type==UniformType::eMat3x3b||Type==UniformType::eMat3x3i||Type==UniformType::eMat3x3ui||Type==UniformType::eMat3x3f||Type==UniformType::eMat3x3d >::type >
Retrieves the VariableType of a UniformType.
struct VariableTypeTraits< Type, typename std::enable_if< Type==UniformType::eMat3x4b||Type==UniformType::eMat3x4i||Type==UniformType::eMat3x4ui||Type==UniformType::eMat3x4f||Type==UniformType::eMat3x4d >::type >
Retrieves the VariableType of a UniformType.
struct VariableTypeTraits< Type, typename std::enable_if< Type==UniformType::eMat4x2b||Type==UniformType::eMat4x2i||Type==UniformType::eMat4x2ui||Type==UniformType::eMat4x2f||Type==UniformType::eMat4x2d >::type >
Retrieves the VariableType of a UniformType.
struct VariableTypeTraits< Type, typename std::enable_if< Type==UniformType::eMat4x3b||Type==UniformType::eMat4x3i||Type==UniformType::eMat4x3ui||Type==UniformType::eMat4x3f||Type==UniformType::eMat4x3d >::type >
Retrieves the VariableType of a UniformType.
struct VariableTypeTraits< Type, typename std::enable_if< Type==UniformType::eMat4x4b||Type==UniformType::eMat4x4i||Type==UniformType::eMat4x4ui||Type==UniformType::eMat4x4f||Type==UniformType::eMat4x4d >::type >
Retrieves the VariableType of a UniformType.
struct VariableTypeTraits< Type, typename std::enable_if< Type==UniformType::eVec2b||Type==UniformType::eVec2i||Type==UniformType::eVec2ui||Type==UniformType::eVec2f||Type==UniformType::eVec2d >::type >
Retrieves the VariableType of a UniformType.
struct VariableTypeTraits< Type, typename std::enable_if< Type==UniformType::eVec3b||Type==UniformType::eVec3i||Type==UniformType::eVec3ui||Type==UniformType::eVec3f||Type==UniformType::eVec3d >::type >
Retrieves the VariableType of a UniformType.
struct VariableTypeTraits< Type, typename std::enable_if< Type==UniformType::eVec4b||Type==UniformType::eVec4i||Type==UniformType::eVec4ui||Type==UniformType::eVec4f||Type==UniformType::eVec4d >::type >
Retrieves the VariableType of a UniformType.
class Version
Version management class.
class VersionException
Version comparison exception.
class Vertex
Representation of a vertex.
struct VertexBoneData
Holds bone data for one vertex.
class VertexBuffer
Vertex buffer representation.
class Viewport
Class to represent a viewport.
class WeightedBlendRendering
Handles the weighted blend rendering.
class WindowHandle
Platform independant window handle implementation.
Typedefs
using ObjectTransform = std::pair< SkeletonAnimationObject *, castor::Matrix4x4r >
using TransformArray = std::vector< ObjectTransform >
using GeometryCache = ObjectCache< Geometry, castor::String >
using LightsRefArray = std::vector< Light * >
using LightsArray = std::vector< LightSPtr >
using LightsMap = std::array< LightsArray, size_t(LightType::eCount) >
using LightCache = ObjectCache< Light, castor::String >
using MaterialCache = Cache< Material, castor::String >
using OverlayCategorySet = std::set< OverlayCategorySPtr, OverlayCategorySort >
using OverlayCache = Cache< Overlay, castor::String >
using PluginCache = Cache< Plugin, castor::String >
using SceneNodeCache = ObjectCache< SceneNode, castor::String >
using ToneMappingFactory = castor::Factory< ToneMapping, castor::String, ToneMappingSPtr, std::function< ToneMappingSPtr(Engine &, Parameters const &) > >
Tone mapping factory.
using GpuBufferAllocator = castor::BuddyAllocatorT< GpuBufferBuddyAllocatorTraits >
using GpuBufferAllocatorUPtr = std::unique_ptr< GpuBufferAllocator >
using SubdividerFactory = castor::Factory< Subdivider, castor::String, SubdividerUPtr >
The subdivider factory.
using LineArray = std::vector< Line >
template<typename T >
using InterleavedVertexTArray = std::vector< InterleavedVertexT< T > >
using InterleavedVertex = InterleavedVertexT< real >
using InterleavedVertexArray = InterleavedVertexTArray< real >
using PostEffectFactory = castor::Factory< PostEffect, castor::String, std::shared_ptr< PostEffect >, std::function< PostEffectSPtr(RenderTarget &, RenderSystem &, Parameters const &) > >
Post effect factory.
using SubmeshRenderNode = ObjectRenderNode< Submesh, Geometry >
using BillboardListRenderNode = ObjectRenderNode< BillboardBase, BillboardBase >
using SubmeshStaticRenderNodesByPassMap = TypeRenderNodesByPassMap< SubmeshStaticRenderNodesMap >
using SubmeshSkinninRenderNodesByPassMap = TypeRenderNodesByPassMap< SubmeshSkinningRenderNodesMap >
using RenderSystemFactory = castor::Factory< RenderSystem, castor::String, RenderSystemUPtr, std::function< RenderSystemUPtr(Engine &) > >
Render technique factory.
using SkeletonAnimationInstanceKeyFrameArray = std::vector< SkeletonAnimationInstanceKeyFrame >
using ParticleArray = std::vector< Particle >
using GeometryPassResult = std::array< TextureUnitUPtr, size_t(DsTexture::eCount) >
using DirectionalLightPassShadow = LightPassShadow< LightType::eDirectional >
using PointLightPassShadow = LightPassShadow< LightType::ePoint >
using SpotLightPassShadow = LightPassShadow< LightType::eSpot >
using FinalCombinePrograms = std::array< FinalCombineProgram, size_t(FogType::eCount) >
using WeightedBlendPassResult = std::array< TextureUnitUPtr, size_t(WbTexture::eCount) >
Enumerations
enum ChunkType : uint64_t {
ChunkType::eUnknown = MAKE_CHUNK_ID(' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '), ChunkType::eCmshFile = MAKE_CHUNK_ID('C', 'M', 'S', 'H', 'F', 'I', 'L', 'E'), ChunkType::eCmshHeader = MAKE_CHUNK_ID('C', 'M', 'S', 'H', 'H', 'D', 'E', 'R'), ChunkType::eCmshVersion = MAKE_CHUNK_ID('C', 'M', 'S', 'H', 'V', 'R', 'S', 'N'),
ChunkType::eName = MAKE_CHUNK_ID('N', 'A', 'M', 'E', ' ', ' ', ' ', ' '), ChunkType::eMesh = MAKE_CHUNK_ID('M', 'E', 'S', 'H', ' ', ' ', ' ', ' '), ChunkType::eSkeleton = MAKE_CHUNK_ID('S', 'K', 'E', 'L', 'E', 'T', 'O', 'N'), ChunkType::eSkeletonGlobalInverse = MAKE_CHUNK_ID('S', 'K', 'E', 'L', 'G', 'I', 'M', 'X'),
ChunkType::eSkeletonBone = MAKE_CHUNK_ID('S', 'K', 'E', 'L', 'B', 'O', 'N', 'E'), ChunkType::eBoneParentName = MAKE_CHUNK_ID('B', 'O', 'N', 'E', 'P', 'A', 'R', 'T'), ChunkType::eBoneOffsetMatrix = MAKE_CHUNK_ID('B', 'O', 'N', 'E', 'O', 'M', 'T', 'X'), ChunkType::eSubmesh = MAKE_CHUNK_ID('S', 'U', 'B', 'M', 'E', 'S', 'H', ' '),
ChunkType::eSubmeshTopology = MAKE_CHUNK_ID('S', 'M', 'S', 'H', 'T', 'O', 'P', 'O'), ChunkType::eSubmeshVertexCount = MAKE_CHUNK_ID('S', 'M', 'S', 'H', 'V', 'X', 'C', 'T'), ChunkType::eSubmeshVertex = MAKE_CHUNK_ID('S', 'M', 'S', 'H', 'V', 'R', 'T', 'X'), ChunkType::eSubmeshBoneCount = MAKE_CHUNK_ID('S', 'M', 'S', 'H', 'B', 'N', 'C', 'T'),
ChunkType::eSubmeshBones = MAKE_CHUNK_ID('S', 'M', 'S', 'H', 'B', 'O', 'N', 'E'), ChunkType::eSubmeshMatrixCount = MAKE_CHUNK_ID('S', 'M', 'S', 'H', 'M', 'X', 'C', 'T'), ChunkType::eSubmeshMatrices = MAKE_CHUNK_ID('S', 'M', 'S', 'H', 'M', 'T', 'R', 'X'), ChunkType::eSubmeshFaceCount = MAKE_CHUNK_ID('S', 'M', 'S', 'H', 'F', 'C', 'C', 'T'),
ChunkType::eSubmeshFaces = MAKE_CHUNK_ID('S', 'M', 'S', 'H', 'F', 'A', 'C', 'E'), ChunkType::eAnimable = MAKE_CHUNK_ID('A', 'N', 'I', 'M', 'A', 'B', 'L', 'E'), ChunkType::eAnimation = MAKE_CHUNK_ID('A', 'N', 'M', 'A', 'T', 'I', 'O', 'N'), ChunkType::eAnimLength = MAKE_CHUNK_ID('A', 'N', 'M', 'L', 'E', 'N', 'G', 'T'),
ChunkType::eSkeletonAnimation = MAKE_CHUNK_ID('S', 'K', 'E', 'L', 'A', 'N', 'I', 'M'), ChunkType::eMeshAnimation = MAKE_CHUNK_ID('M', 'E', 'S', 'H', 'A', 'N', 'I', 'M'), ChunkType::eAnimInterpolator = MAKE_CHUNK_ID('A', 'N', 'M', 'I', 'N', 'T', 'E', 'R'), ChunkType::eAnimationObject = MAKE_CHUNK_ID('A', 'N', 'S', 'K', 'O', 'B', 'J', 'T'),
ChunkType::eSkeletonAnimationNode = MAKE_CHUNK_ID('A', 'N', 'S', 'K', 'N', 'O', 'D', 'E'), ChunkType::eSkeletonAnimationBone = MAKE_CHUNK_ID('A', 'N', 'S', 'K', 'B', 'O', 'N', 'E'), ChunkType::eMovingTransform = MAKE_CHUNK_ID('M', 'V', 'N', 'G', 'T', 'S', 'F', 'M'), ChunkType::eKeyframeCount = MAKE_CHUNK_ID('K', 'F', 'R', 'M', 'C', 'O', 'N', 'T'),
ChunkType::eKeyframes = MAKE_CHUNK_ID('K', 'E', 'Y', 'F', 'R', 'M', 'E', 'S'), ChunkType::eBonesComponent = MAKE_CHUNK_ID('B', 'O', 'N', 'E', 'C', 'O', 'M', 'P'), ChunkType::eMeshAnimationKeyFrame = MAKE_CHUNK_ID('M', 'S', 'A', 'N', 'K', 'F', 'R', 'M'), ChunkType::eMeshAnimationKeyFrameTime = MAKE_CHUNK_ID('M', 'S', 'A', 'N', 'K', 'F', 'T', 'M'),
ChunkType::eMeshAnimationKeyFrameSubmeshID = MAKE_CHUNK_ID('M', 'S', 'A', 'N', 'K', 'F', 'I', 'D'), ChunkType::eMeshAnimationKeyFrameBufferSize = MAKE_CHUNK_ID('M', 'H', 'A', 'N', 'K', 'F', 'S', 'Z'), ChunkType::eMeshAnimationKeyFrameBufferData = MAKE_CHUNK_ID('M', 'H', 'A', 'N', 'K', 'F', 'D', 'T'), ChunkType::eSkeletonAnimationKeyFrame = MAKE_CHUNK_ID('S', 'K', 'A', 'N', 'K', 'F', 'R', 'M'),
ChunkType::eSkeletonAnimationKeyFrameTime = MAKE_CHUNK_ID('S', 'K', 'A', 'N', 'K', 'F', 'T', 'M'), ChunkType::eSkeletonAnimationKeyFrameObjectType = MAKE_CHUNK_ID('S', 'K', 'A', 'N', 'K', 'F', 'O', 'Y'), ChunkType::eSkeletonAnimationKeyFrameObjectName = MAKE_CHUNK_ID('S', 'K', 'A', 'N', 'K', 'F', 'O', 'N'), ChunkType::eSkeletonAnimationKeyFrameObjectTransform = MAKE_CHUNK_ID('S', 'K', 'A', 'N', 'K', 'F', 'O', 'T')
}
Binary data chunk types enumeration.
enum GpuFeature : uint32_t {
GpuFeature::eInstancing = 0x00000001, GpuFeature::eAccumulationBuffer = 0x00000002, GpuFeature::eNonPowerOfTwoTextures = 0x00000004, GpuFeature::eStereo = 0x00000008,
GpuFeature::eConstantsBuffers = 0x00000010, GpuFeature::eTextureBuffers = 0x00000020, GpuFeature::eShaderStorageBuffers = 0x00000040, GpuFeature::eAtomicCounterBuffers = 0x00000080,
GpuFeature::eTransformFeedback = 0x00000100, GpuFeature::eImmutableTextureStorage = 0x00000200
}
All supported GPU feature flags.
enum GpuMin : uint32_t { GpuMin::eMapBufferAlignment, GpuMin::eProgramTexelOffset }
All supported GPU feature flags.
enum GpuMax : uint32_t {
GpuMax::eShaderStorageBufferBindings, GpuMax::eVertexShaderStorageBlocks, GpuMax::eVertexAtomicCounters, GpuMax::eVertexAttribs,
GpuMax::eVertexOutputComponents, GpuMax::eVertexTextureImageUnits, GpuMax::eVertexUniformComponents, GpuMax::eVertexUniformBlocks,
GpuMax::eVertexUniformVectors, GpuMax::eVertexCombinedUniformComponents, GpuMax::eGeometryAtomicCounters, GpuMax::eGeometryShaderStorageBlocks,
GpuMax::eGeometryInputComponents, GpuMax::eGeometryOutputComponents, GpuMax::eGeometryTextureImageUnits, GpuMax::eGeometryUniformComponents,
GpuMax::eGeometryUniformBlocks, GpuMax::eGeometryCombinedUniformComponents, GpuMax::eTessControlAtomicCounters, GpuMax::eTessControlShaderStorageBlocks,
GpuMax::eTessEvaluationAtomicCounters, GpuMax::eTessEvaluationShaderStorageBlocks, GpuMax::eComputeAtomicCounters, GpuMax::eComputeAtomicCounterBuffers,
GpuMax::eComputeShaderStorageBlocks, GpuMax::eComputeTextureImageUnits, GpuMax::eComputeUniformComponents, GpuMax::eComputeUniformBlocks,
GpuMax::eComputeCombinedUniformComponents, GpuMax::eComputeWorkGroupInvocations, GpuMax::eComputeWorkGroupCount, GpuMax::eComputeWorkGroupSize,
GpuMax::eFragmentAtomicCounters, GpuMax::eFragmentShaderStorageBlocks, GpuMax::eFragmentInputComponents, GpuMax::eFragmentUniformComponents,
GpuMax::eFragmentUniformBlocks, GpuMax::eFragmentUniformVectors, GpuMax::eFragmentCombinedUniformComponents, GpuMax::eCombinedAtomicCounters,
GpuMax::eCombinedShaderStorageBlocks, GpuMax::eDebugGroupStackDepth, GpuMax::eLabelLength, GpuMax::eIntegerSamples,
GpuMax::eProgramTexelOffset, GpuMax::eServerWaitTimeout, GpuMax::eSampleMaskWords, GpuMax::eSamples,
GpuMax::eTexture3DSize, GpuMax::eTextureRectangleSize, GpuMax::eTextureCubeMapSize, GpuMax::eTextureBufferSize,
GpuMax::eTextureSize, GpuMax::eTextureImageUnits, GpuMax::eTextureLodBias, GpuMax::eArrayTextureLayers,
GpuMax::eClipDistances, GpuMax::eColourTextureSamples, GpuMax::eDepthTextureSamples, GpuMax::eCombinedTextureImageUnits,
GpuMax::eCombinedUniformBlocks, GpuMax::eDrawBuffers, GpuMax::eDualSourceDrawBuffers, GpuMax::eElementIndices,
GpuMax::eElementVertices, GpuMax::eFramebufferWidth, GpuMax::eFramebufferHeight, GpuMax::eFramebufferLayers,
GpuMax::eFramebufferSamples, GpuMax::eRenderbufferSize, GpuMax::eUniformBufferBindings, GpuMax::eUniformBlockSize,
GpuMax::eUniformLocations, GpuMax::eVaryingComponents, GpuMax::eVaryingVectors, GpuMax::eVaryingFloats,
GpuMax::eViewportWidth, GpuMax::eViewportHeight, GpuMax::eViewports
}
All supported GPU feature flags.
enum UserInputEventType { UserInputEventType::eMouse, UserInputEventType::eKeyboard, UserInputEventType::eHandler }
Supported events types enumeration.
enum MouseEventType : uint8_t {
MouseEventType::eMove, MouseEventType::eEnter, MouseEventType::eHover, MouseEventType::eLeave,
MouseEventType::ePushed, MouseEventType::eReleased, MouseEventType::eWheel
}
Enumeration of supported mouse events.
enum KeyboardEventType : uint8_t { KeyboardEventType::ePushed, KeyboardEventType::eReleased, KeyboardEventType::eChar }
Enumeration of supported keyboard events.
enum HandlerEventType : uint8_t { HandlerEventType::eActivate, HandlerEventType::eDeactivate }
Enumeration of supported handler events.
enum MouseButton { MouseButton::eLeft, MouseButton::eMiddle, MouseButton::eRight }
Mouse buttons enumeration.
enum KeyboardKey {
KeyboardKey::eNone, KeyboardKey::eBackspace = 0x08, KeyboardKey::eTab = 0x0A, KeyboardKey::eReturn = 0x0D,
KeyboardKey::eEscape = 0x1B, KeyboardKey::eSpace = 0x20, KeyboardKey::eDelete = 0x7F, KeyboardKey::eStart = 0x100,
KeyboardKey::eLButton, KeyboardKey::eRButton, KeyboardKey::eCancel, KeyboardKey::eMButton,
KeyboardKey::eClear, KeyboardKey::eShift, KeyboardKey::eAlt, KeyboardKey::eControl,
KeyboardKey::eMenu, KeyboardKey::ePause, KeyboardKey::eCapital, KeyboardKey::eEnd,
KeyboardKey::eHome, KeyboardKey::eLeft, KeyboardKey::eUp, KeyboardKey::eRight,
KeyboardKey::edown, KeyboardKey::eSelect, KeyboardKey::ePrint, KeyboardKey::eExecute,
KeyboardKey::eSnapshot, KeyboardKey::eInsert, KeyboardKey::eHelp, KeyboardKey::eNumpad0,
KeyboardKey::eNumpad1, KeyboardKey::eNumpad2, KeyboardKey::eNumpad3, KeyboardKey::eNumpad4,
KeyboardKey::eNumpad5, KeyboardKey::eNumpad6, KeyboardKey::eNumpad7, KeyboardKey::eNumpad8,
KeyboardKey::eNumpad9, KeyboardKey::eMultiply, KeyboardKey::eAdd, KeyboardKey::eSeparator,
KeyboardKey::eSubtract, KeyboardKey::eDecimal, KeyboardKey::eDivide, KeyboardKey::eF1,
KeyboardKey::eF2, KeyboardKey::eF3, KeyboardKey::eF4, KeyboardKey::eF5,
KeyboardKey::eF6, KeyboardKey::eF7, KeyboardKey::eF8, KeyboardKey::eF9,
KeyboardKey::eF10, KeyboardKey::eF11, KeyboardKey::eF12, KeyboardKey::eF13,
KeyboardKey::eF14, KeyboardKey::eF15, KeyboardKey::eF16, KeyboardKey::eF17,
KeyboardKey::eF18, KeyboardKey::eF19, KeyboardKey::eF20, KeyboardKey::eF21,
KeyboardKey::eF22, KeyboardKey::eF23, KeyboardKey::eF24, KeyboardKey::eNumlock,
KeyboardKey::eScroll, KeyboardKey::ePageUp, KeyboardKey::ePageDown, KeyboardKey::eNumpadSpace,
KeyboardKey::eNumpadTab, KeyboardKey::eNumpadEnter, KeyboardKey::eNumpadF1, KeyboardKey::eNumpadF2,
KeyboardKey::eNumpadF3, KeyboardKey::eNumpadF4, KeyboardKey::eNumpadHome, KeyboardKey::eNumpadLeft,
KeyboardKey::eNumpadUp, KeyboardKey::eNumpadRight, KeyboardKey::eNumpadDown, KeyboardKey::eNumpadPageUp,
KeyboardKey::eNumpadPageDown, KeyboardKey::eNumpadEnd, KeyboardKey::eNumpadBegin, KeyboardKey::eNumpadInsert,
KeyboardKey::eNumpadDelete, KeyboardKey::eNumpadEqual, KeyboardKey::eNumpadMultiply, KeyboardKey::eNumpadAdd,
KeyboardKey::eNumpadSeparator, KeyboardKey::eNumpadSubtract, KeyboardKey::eNumpadDecimal, KeyboardKey::eNumpadDivide
}
Keyboard keys enumeration.
enum CSCNSection : uint32_t {
CSCNSection::eRoot = MAKE_SECTION_NAME('R', 'O', 'O', 'T'), CSCNSection::eScene = MAKE_SECTION_NAME('S', 'C', 'N', 'E'), CSCNSection::eWindow = MAKE_SECTION_NAME('W', 'N', 'D', 'W'), CSCNSection::eSampler = MAKE_SECTION_NAME('S', 'M', 'P', 'R'),
CSCNSection::eCamera = MAKE_SECTION_NAME('C', 'A', 'M', 'R'), CSCNSection::eViewport = MAKE_SECTION_NAME('V', 'W', 'P', 'T'), CSCNSection::eLight = MAKE_SECTION_NAME('L', 'G', 'H', 'T'), CSCNSection::eNode = MAKE_SECTION_NAME('N', 'O', 'D', 'E'),
CSCNSection::eObject = MAKE_SECTION_NAME('O', 'B', 'J', 'T'), CSCNSection::eObjectMaterials = MAKE_SECTION_NAME('O', 'M', 'T', 'L'), CSCNSection::eFont = MAKE_SECTION_NAME('F', 'O', 'N', 'T'), CSCNSection::ePanelOverlay = MAKE_SECTION_NAME('P', 'O', 'V', 'L'),
CSCNSection::eBorderPanelOverlay = MAKE_SECTION_NAME('B', 'O', 'V', 'L'), CSCNSection::eTextOverlay = MAKE_SECTION_NAME('T', 'O', 'V', 'L'), CSCNSection::eMesh = MAKE_SECTION_NAME('M', 'E', 'S', 'H'), CSCNSection::eSubmesh = MAKE_SECTION_NAME('S', 'M', 'S', 'H'),
CSCNSection::eMaterial = MAKE_SECTION_NAME('M', 'T', 'R', 'L'), CSCNSection::ePass = MAKE_SECTION_NAME('P', 'A', 'S', 'S'), CSCNSection::eTextureUnit = MAKE_SECTION_NAME('U', 'N', 'I', 'T'), CSCNSection::eRenderTarget = MAKE_SECTION_NAME('R', 'T', 'G', 'R'),
CSCNSection::eShaderProgram = MAKE_SECTION_NAME('G', 'L', 'S', 'L'), CSCNSection::eShaderObject = MAKE_SECTION_NAME('S', 'P', 'G', 'M'), CSCNSection::eShaderUBO = MAKE_SECTION_NAME('S', 'U', 'B', 'O'), CSCNSection::eUBOVariable = MAKE_SECTION_NAME('S', 'U', 'B', 'V'),
CSCNSection::eBillboard = MAKE_SECTION_NAME('B', 'L', 'B', 'd'), CSCNSection::eBillboardList = MAKE_SECTION_NAME('B', 'L', 'B', 'L'), CSCNSection::eAnimGroup = MAKE_SECTION_NAME('A', 'N', 'G', 'P'), CSCNSection::eAnimation = MAKE_SECTION_NAME('A', 'N', 'M', 'T'),
CSCNSection::eSkybox = MAKE_SECTION_NAME('S', 'K', 'B', 'X'), CSCNSection::eParticleSystem = MAKE_SECTION_NAME('P', 'L', 'S', 'M'), CSCNSection::eParticle = MAKE_SECTION_NAME('P', 'T', 'C', 'L'), CSCNSection::eSsao = MAKE_SECTION_NAME('S', 'S', 'A', 'O'),
CSCNSection::eSubsurfaceScattering = MAKE_SECTION_NAME('S', 'S', 'S', 'G'), CSCNSection::eTransmittanceProfile = MAKE_SECTION_NAME('T', 'R', 'P', 'R'), CSCNSection::eHdrConfig = MAKE_SECTION_NAME('H', 'D', 'R', 'C')
}
Scene file sections Enum.
enum DsTexture : uint8_t {
DsTexture::eDepth, DsTexture::eData1, DsTexture::eData2, DsTexture::eData3,
DsTexture::eData4, DsTexture::eData5, DsTexture::CASTOR_SCOPED_ENUM_BOUNDS =(eDepth)
}
Enumerator of textures used in deferred rendering.
enum WbTexture : uint8_t { WbTexture::eDepth, WbTexture::eAccumulation, WbTexture::eRevealage, WbTexture::CASTOR_SCOPED_ENUM_BOUNDS =(eDepth) }
Enumerator of textures used in weighted blend OIT.
Functions
static void prepareChunkData (ChunkType &p_value)
sets given value to big endian.
static uint8_t const * getBuffer (bool const &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (bool &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (int8_t const &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (int8_t &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (uint8_t const &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (uint8_t &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (int16_t const &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (int16_t &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (uint16_t const &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (uint16_t &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (int32_t const &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (int32_t &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (uint32_t const &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (uint32_t &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (int64_t const &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (int64_t &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (uint64_t const &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (uint64_t &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (float const &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (float &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (double const &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (double &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (long double const &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (long double &p_value)
Retrieves the beginning of the buffer for given value.
template<typename T >
static size_t getDataSize (T const &p_value)
Retrieves the value binary size.
template<typename T >
static uint8_t const * getBuffer (std::vector< T > const &p_value)
Retrieves the beginning of the buffer for given value.
template<typename T >
static uint8_t * getBuffer (std::vector< T > &p_value)
Retrieves the beginning of the buffer for given value.
template<typename T >
static size_t getDataSize (std::vector< T > const &p_value)
Retrieves the value binary size.
template<typename T , size_t Count>
static uint8_t const * getBuffer (std::array< T, Count > const &p_value)
Retrieves the beginning of the buffer for given value.
template<typename T , size_t Count>
static uint8_t * getBuffer (std::array< T, Count > &p_value)
Retrieves the beginning of the buffer for given value.
template<typename T , size_t Count>
static size_t getDataSize (std::array< T, Count > const &p_value)
Retrieves the value binary size.
template<typename T , uint32_t Count>
static uint8_t const * getBuffer (castor::Point< T, Count > const &p_value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Count>
static uint8_t * getBuffer (castor::Point< T, Count > &p_value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Count>
static size_t getDataSize (castor::Point< T, Count > const &p_value)
Retrieves the value binary size.
template<typename T , uint32_t Count>
static uint8_t const * getBuffer (castor::Coords< T, Count > const &p_value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Count>
static uint8_t * getBuffer (castor::Coords< T, Count > &p_value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Count>
static size_t getDataSize (castor::Coords< T, Count > const &p_value)
Retrieves the value binary size.
template<typename T , uint32_t Columns, uint32_t Rows>
static uint8_t const * getBuffer (castor::Matrix< T, Columns, Rows > const &p_value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Columns, uint32_t Rows>
static uint8_t * getBuffer (castor::Matrix< T, Columns, Rows > &p_value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Columns, uint32_t Rows>
static size_t getDataSize (castor::Matrix< T, Columns, Rows > const &p_value)
Retrieves the value binary size.
template<typename T , uint32_t Count>
static uint8_t const * getBuffer (castor::SquareMatrix< T, Count > const &p_value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Count>
static uint8_t * getBuffer (castor::SquareMatrix< T, Count > &p_value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Count>
static size_t getDataSize (castor::SquareMatrix< T, Count > const &p_value)
Retrieves the value binary size.
static uint8_t const * getBuffer (castor::RgbColour const &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (castor::RgbColour &p_value)
Retrieves the beginning of the buffer for given value.
static size_t getDataSize (castor::RgbColour const &p_value)
Retrieves the value binary size.
static uint8_t const * getBuffer (castor::RgbaColour const &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (castor::RgbaColour &p_value)
Retrieves the beginning of the buffer for given value.
static size_t getDataSize (castor::RgbaColour const &p_value)
Retrieves the value binary size.
static uint8_t const * getBuffer (castor::Size const &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (castor::Size &p_value)
Retrieves the beginning of the buffer for given value.
static size_t getDataSize (castor::Size const &p_value)
Retrieves the value binary size.
static uint8_t const * getBuffer (castor::Position const &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (castor::Position &p_value)
Retrieves the beginning of the buffer for given value.
static size_t getDataSize (castor::Position const &p_value)
Retrieves the value binary size.
template<typename T >
static uint8_t const * getBuffer (castor::QuaternionT< T > const &p_value)
Retrieves the beginning of the buffer for given value.
template<typename T >
static uint8_t * getBuffer (castor::QuaternionT< T > &p_value)
Retrieves the beginning of the buffer for given value.
template<typename T >
static size_t getDataSize (castor::QuaternionT< T > const &p_value)
Retrieves the value binary size.
static void prepareChunkData (bool &p_value)
sets given value to big endian.
static void prepareChunkData (int8_t &p_value)
sets given value to big endian.
static void prepareChunkData (uint8_t &p_value)
sets given value to big endian.
static void prepareChunkData (int16_t &p_value)
sets given value to big endian.
static void prepareChunkData (uint16_t &p_value)
sets given value to big endian.
static void prepareChunkData (int32_t &p_value)
sets given value to big endian.
static void prepareChunkData (uint32_t &p_value)
sets given value to big endian.
static void prepareChunkData (int64_t &p_value)
sets given value to big endian.
static void prepareChunkData (uint64_t &p_value)
sets given value to big endian.
static void prepareChunkData (float &p_value)
sets given value to big endian.
static void prepareChunkData (double &p_value)
sets given value to big endian.
static void prepareChunkData (long double &p_value)
sets given value to big endian.
template<typename T >
static void prepareChunkData (std::vector< T > &p_value)
sets given value to big endian.
template<typename T , size_t Count>
static void prepareChunkData (std::array< T, Count > &p_value)
sets given value to big endian.
template<typename T , uint32_t Count>
static void prepareChunkData (castor::SquareMatrix< T, Count > &p_value)
sets given value to big endian.
template<typename T , uint32_t Count>
static void prepareChunkData (castor::Point< T, Count > &p_value)
sets given value to big endian.
template<typename T , uint32_t Count>
static void prepareChunkData (castor::Coords< T, Count > &p_value)
sets given value to big endian.
template<typename T >
static void prepareChunkData (castor::QuaternionT< T > &p_value)
sets given value to big endian.
static void prepareChunkData (castor::ColourComponent &p_value)
sets given value to big endian.
static void prepareChunkData (castor::RgbColour &p_value)
sets given value to big endian.
static void prepareChunkData (castor::RgbaColour &p_value)
sets given value to big endian.
template<typename T >
static void prepareChunkData (InterleavedVertexT< T > &p_value)
sets given value to big endian.
template<typename T >
static void prepareChunkData (SubmeshAnimationBufferT< T > &p_value)
sets given value to big endian.
static void prepareChunkData (FaceIndices &p_value)
sets given value to big endian.
static void prepareChunkData (VertexBoneData &p_value)
sets given value to big endian.
template<typename ElementType , typename KeyType >
std::unique_ptr< Cache< ElementType, KeyType > > makeCache (Engine &engine, typename CacheTraits< ElementType, KeyType >::Producer &&produce, ElementInitialiser< ElementType > &&initialise=[](std::shared_ptr< ElementType >){}, ElementCleaner< ElementType > &&clean=[](std::shared_ptr< ElementType >){}, typename CacheTraits< ElementType, KeyType >::Merger &&merge=[](CacheBase< ElementType, KeyType > const &, castor::Collection< ElementType, KeyType > &, std::shared_ptr< ElementType >){})
Creates a cache.
DECLARE_SMART_PTR (GeometryCache)
DECLARE_SMART_PTR (LightCache)
DECLARE_SMART_PTR (MaterialCache)
template<typename ElementType , typename KeyType >
std::unique_ptr< ObjectCache< ElementType, KeyType > > makeObjectCache (Engine &engine, Scene &p_scene, SceneNodeSPtr p_rootNode, SceneNodeSPtr p_rootCameraNode, SceneNodeSPtr p_rootObjectNode, typename ObjectCacheTraits< ElementType, KeyType >::Producer &&p_produce, ElementInitialiser< ElementType > &&p_initialise=[](std::shared_ptr< ElementType >){}, ElementCleaner< ElementType > &&p_clean=[](std::shared_ptr< ElementType >){}, typename ObjectCacheTraits< ElementType, KeyType >::Merger &&p_merge=[](ObjectCacheBase< ElementType, KeyType > const &, castor::Collection< ElementType, KeyType > &, std::shared_ptr< ElementType >, SceneNodeSPtr, SceneNodeSPtr){}, ElementAttacher< ElementType > &&p_attach=[](std::shared_ptr< ElementType >, SceneNodeSPtr, SceneNodeSPtr, SceneNodeSPtr, SceneNodeSPtr){}, ElementDetacher< ElementType > &&p_detach=[](std::shared_ptr< ElementType >){})
Creates an object cache.
DECLARE_SMART_PTR (OverlayCache)
DECLARE_SMART_PTR (PluginCache)
DECLARE_SMART_PTR (SceneNodeCache)
std::unique_ptr< ShaderProgramCache > makeCache (Engine &engine)
Creates a ShaderProgram cache.
template<typename T >
std::unique_ptr< CleanupEvent< T > > makeCleanupEvent (T &p_object)
Helper function to create a cleanup event.
template<typename Functor >
std::unique_ptr< FunctorEvent< Functor > > makeFunctorEvent (EventType p_type, Functor p_functor)
Helper function to create a functor event.
template<typename T >
std::unique_ptr< InitialiseEvent< T > > makeInitialiseEvent (T &p_object)
Helper function to create an initialise event.
C3D_API bool operator== (BufferDeclaration &p_lhs, BufferDeclaration &p_rhs)
Equality operator.
C3D_API bool operator!= (BufferDeclaration &p_lhs, BufferDeclaration &p_rhs)
Equality operator.
bool operator== (BufferElementDeclaration const &p_lhs, BufferElementDeclaration const &p_rhs)
Equality operator.
bool operator!= (BufferElementDeclaration const &p_lhs, BufferElementDeclaration const &p_rhs)
Equality operator.
std::ostream & operator<< (std::ostream &o, Cone const &c)
Stream operator.
std::ostream & operator<< (std::ostream &o, Cube const &c)
Stream operator.
std::ostream & operator<< (std::ostream &o, Cylinder const &c)
Stream operator.
std::ostream & operator<< (std::ostream &o, Icosahedron const &c)
Stream operator.
std::ostream & operator<< (std::ostream &o, Plane const &c)
Stream operator.
std::ostream & operator<< (std::ostream &o, Projection const &c)
Stream operator.
std::ostream & operator<< (std::ostream &o, Sphere const &c)
Stream operator.
int getCPUCount ()
C3D_API bool operator== (castor3d::Version const &p_a, castor3d::Version const &p_b)
Equality operator.
C3D_API bool operator!= (castor3d::Version const &p_a, castor3d::Version const &p_b)
Difference operator.
C3D_API bool operator< (castor3d::Version const &p_a, castor3d::Version const &p_b)
Less than operator.
C3D_API bool operator> (castor3d::Version const &p_a, castor3d::Version const &p_b)
Less than operator.
C3D_API bool operator<= (castor3d::Version const &p_a, castor3d::Version const &p_b)
Less than operator.
C3D_API bool operator>= (castor3d::Version const &p_a, castor3d::Version const &p_b)
Less than operator.
C3D_API std::ostream & operator<< (std::ostream &p_stream, castor3d::Version const &p_version)
C3D_API std::wostream & operator<< (std::wostream &p_stream, castor3d::Version const &p_version)
C3D_API castor::String & operator<< (castor::String &p_stream, castor3d::Version const &p_version)
DECLARE_SMART_PTR (EventHandler)
DECLARE_SMART_PTR (UserInputEvent)
DECLARE_SMART_PTR (KeyboardEvent)
DECLARE_SMART_PTR (MouseEvent)
DECLARE_SMART_PTR (HandlerEvent)
DECLARE_SMART_PTR (UserInputListener)
DECLARE_MULTIMAP (double, StaticRenderNode, StaticRenderNodeByDistance)
DECLARE_MULTIMAP (double, SkinningRenderNode, SkinningRenderNodeByDistance)
DECLARE_MULTIMAP (double, MorphingRenderNode, MorphingRenderNodeByDistance)
DECLARE_MULTIMAP (double, BillboardRenderNode, BillboardRenderNodeByDistance)
DECLARE_VECTOR (StaticRenderNode, StaticRenderNode)
DECLARE_VECTOR (SkinningRenderNode, SkinningRenderNode)
DECLARE_VECTOR (MorphingRenderNode, MorphingRenderNode)
DECLARE_VECTOR (BillboardRenderNode, BillboardRenderNode)
DECLARE_MAP (RenderPipelineRPtr, StaticRenderNodeArray, StaticRenderNodesByPipeline)
DECLARE_MAP (RenderPipelineRPtr, SkinningRenderNodeArray, SkinningRenderNodesByPipeline)
DECLARE_MAP (RenderPipelineRPtr, MorphingRenderNodeArray, MorphingRenderNodesByPipeline)
DECLARE_MAP (RenderPipelineRPtr, BillboardRenderNodeArray, BillboardRenderNodesByPipeline)
DECLARE_MAP (SubmeshRPtr, StaticRenderNodeArray, SubmeshStaticRenderNodes)
DECLARE_MAP (SubmeshRPtr, SkinningRenderNodeArray, SubmeshSkinningRenderNodes)
DECLARE_MAP (RenderPipelineRPtr, SubmeshStaticRenderNodesByPassMap, SubmeshStaticRenderNodesByPipeline)
DECLARE_MAP (RenderPipelineRPtr, SubmeshSkinninRenderNodesByPassMap, SubmeshSkinningRenderNodesByPipeline)
uint32_t doFillShaderShadowMaps (RenderPipeline &pipeline, ShadowMapLightTypeArray &shadowMaps, uint32_t &index)
uint32_t doFillShaderPbrMaps (RenderPipeline &pipeline, Scene &scene, SceneNode &sceneNode, uint32_t index)
void doBindPass (SceneNode &sceneNode, PassRenderNode &node, Scene &scene, RenderPipeline &pipeline, ShadowMapLightTypeArray &shadowMaps, ModelUbo &model, EnvironmentMap *&envMap)
void doBindPassOpacityMap (PassRenderNode &node, Pass &pass)
void doUnbindPassOpacityMap (PassRenderNode &node, Pass &pass)
template<typename DataType , typename InstanceType >
void doRenderObjectNode (ObjectRenderNode< DataType, InstanceType > &node)
void doRenderNodeNoPass (StaticRenderNode &node)
void doRenderNodeNoPass (BillboardRenderNode &node)
void doRenderNodeNoPass (MorphingRenderNode &node)
void doRenderNodeNoPass (SkinningRenderNode &node)
template<typename NodeType >
void doRenderNode (NodeType &node)
bool operator< (PipelineFlags const &lhs, PipelineFlags const &rhs)
C3D_API bool operator== (ProgramInputLayout const &p_lhs, ProgramInputLayout const &p_rhs)
Equality operator.
C3D_API bool operator!= (ProgramInputLayout const &p_lhs, ProgramInputLayout const &p_rhs)
Equality operator.
castor::String getTextureName (DsTexture texture)
Retrieve the name for given texture enum value.
castor::PixelFormat getTextureFormat (DsTexture texture)
Retrieve the pixel format for given texture enum value.
AttachmentPoint getTextureAttachmentPoint (DsTexture texture)
Retrieve the attachment point for given texture enum value.
uint32_t getTextureAttachmentIndex (DsTexture texture)
Retrieve the attachment index for given texture enum value.
float getMaxDistance (LightCategory const &light, castor::Point3f const &attenuation)
Retrieve the maximum litten distance for given light and attenuation.
float getMaxDistance (LightCategory const &light, castor::Point3f const &attenuation, float max)
Retrieve the maximum litten distance for given light and attenuation.
void declareEncodeMaterial (glsl::GlslWriter &writer)
Declares the GLSL function used to encode the material specifics into a vec4.
void declareDecodeMaterial (glsl::GlslWriter &writer)
Declares the GLSL function used to decode the material specifics from a vec4.
void declareDecodeReceiver (glsl::GlslWriter &writer)
Declares the GLSL function used to decode the shadow receiver status from a vec4.
void encodeMaterial (glsl::GlslWriter &writer, glsl::Int const &receiver, glsl::Int const &reflection, glsl::Int const &refraction, glsl::Int const &envMapIndex, glsl::Float const &encoded)
Calls the GLSL function used to encode the material specifics into a vec4.
void decodeMaterial (glsl::GlslWriter &writer, glsl::Float const &encoded, glsl::Int const &receiver, glsl::Int const &reflection, glsl::Int const &refraction, glsl::Int const &envMapIndex)
Calls the GLSL function used to dencode the material specifics from a vec4.
void decodeReceiver (glsl::GlslWriter &writer, glsl::Int &encoded, glsl::Int const &receiver)
Calls the GLSL function used to decode the shadow receiver status from a vec4.
castor::String getTextureName (WbTexture texture)
Retrieve the name for given texture enum value.
castor::PixelFormat getTextureFormat (WbTexture texture)
Retrieve the pixel format for given texture enum value.
AttachmentPoint getTextureAttachmentPoint (WbTexture texture)
Retrieve the attachment point for given texture enum value.
uint32_t getTextureAttachmentIndex (WbTexture texture)
Retrieve the attachment index for given texture enum value.
std::ostream & operator<< (std::ostream &streamOut, TextureUnitSPtr const &texture)
Stream operator.
Importer
DECLARE_SMART_PTR (Importer)
Camera
DECLARE_SMART_PTR (Camera)
DECLARE_SMART_PTR (Viewport)
DECLARE_SMART_PTR (IViewportImpl)
DECLARE_SMART_PTR (Ray)
DECLARE_MAP (castor::String, CameraSPtr, CameraPtrStr)
Camera pointer map, sorted by name.
DECLARE_VECTOR (CameraSPtr, CameraPtr)
Camera pointer array.
Variables
uint32_t const CMSH_VERSION = MAKE_CMSH_VERSION(0x01, 0x03, 0x0000)
static const xchar * INFO_CACHE_CREATED_OBJECT = cuT("Cache::create - Created ")
static const xchar * WARNING_CACHE_DUPLICATE_OBJECT = cuT("Cache::create - Duplicate ")
static const xchar * WARNING_CACHE_NULL_OBJECT = cuT("Cache::Insert - nullptr ")
castor::String const RENDERER_TYPE_UNDEFINED = cuT("Undefined")
static const uint32_t C3D_MAX_BONES_PER_VERTEX = 8
static uint32_t constexpr PassBufferIndex = 0u
static uint32_t constexpr LightBufferIndex = 1u
static uint32_t constexpr MinTextureIndex = 2u
static const uint32_t C3D_MAX_TEXTURE_MATRICES = 4
General
enum MovableType : uint8_t {
MovableType::eCamera, MovableType::eGeometry, MovableType::eLight, MovableType::eBillboard,
MovableType::eParticleEmitter
}
Movable object types enumerator.
enum TargetType : uint8_t { TargetType::eWindow, TargetType::eTexture }
RenderTarget supported types.
enum PluginType : uint8_t {
PluginType::eRenderer, PluginType::eImporter, PluginType::eDivider, PluginType::eGenerator,
PluginType::eTechnique, PluginType::eToneMapping, PluginType::ePostEffect, PluginType::eGeneric,
PluginType::eParticle
}
Plugin types enumeration.
enum BufferComponent : uint8_t { BufferComponent::eNone = 0, BufferComponent::eColour = 1 << 0, BufferComponent::eDepth = 1 << 1, BufferComponent::eStencil = 1 << 2 }
Frame buffer components enumeration.
enum WindowBuffer : uint8_t {
WindowBuffer::eNone, WindowBuffer::eFrontLeft, WindowBuffer::eFrontRight, WindowBuffer::eBackLeft,
WindowBuffer::eBackRight, WindowBuffer::eFront, WindowBuffer::eBack, WindowBuffer::eLeft,
WindowBuffer::eRight, WindowBuffer::eFrontAndBack
}
Frame buffer components enumeration.
enum FrameBufferTarget : uint8_t { FrameBufferTarget::eDraw, FrameBufferTarget::eRead, FrameBufferTarget::eBoth }
Frame buffer binding targets enumeration.
enum FrameBufferMode : uint8_t { FrameBufferMode::eConfig, FrameBufferMode::eAutomatic, FrameBufferMode::eManual }
Frame buffer binding modes enumeration.
enum AttachmentPoint : uint8_t {
AttachmentPoint::eNone, AttachmentPoint::eColour, AttachmentPoint::eDepth, AttachmentPoint::eStencil,
AttachmentPoint::eDepthStencil
}
Frame buffer attachment points enumeration.
enum AttachmentType : uint8_t { AttachmentType::eTexture, AttachmentType::eBuffer }
Frame buffer attachment types enumeration.
enum ViewportType : uint8_t { ViewportType::eOrtho, ViewportType::ePerspective, ViewportType::eFrustum }
The viewport projection types enumeration.
enum FrustumPlane {
FrustumPlane::eNear, FrustumPlane::eFar, FrustumPlane::eLeft, FrustumPlane::eRight,
FrustumPlane::eTop, FrustumPlane::eBottom
}
Frustum view planes enumeration.
enum FrustumCorner {
FrustumCorner::eFarLeftBottom, FrustumCorner::eFarLeftTop, FrustumCorner::eFarRightTop, FrustumCorner::eFarRightBottom,
FrustumCorner::eNearLeftBottom, FrustumCorner::eNearLeftTop, FrustumCorner::eNearRightTop, FrustumCorner::eNearRightBottom
}
Frustum view planes enumeration.
enum EventType : uint8_t { EventType::ePreRender, EventType::eQueueRender, EventType::ePostRender }
Frame Event Type enumeration.
enum Culling : uint8_t { Culling::eNone, Culling::eFront, Culling::eBack, Culling::eFrontAndBack }
Culled faces enumeration.
enum FillMode : uint8_t { FillMode::ePoint, FillMode::eLine, FillMode::eSolid }
Polygon rasterisation modes enumeration.
enum QueryType : uint32_t {
QueryType::eTimeElapsed, QueryType::eSamplesPassed, QueryType::eAnySamplesPassed, QueryType::ePrimitivesGenerated,
QueryType::eTransformFeedbackPrimitivesWritten, QueryType::eAnySamplesPassedConservative, QueryType::eTimestamp
}
GPU query supported types enumeration.
enum QueryInfo : uint32_t { QueryInfo::eResult, QueryInfo::eResultAvailable, QueryInfo::eResultNoWait }
GPU query supported informations enumeration.
enum MemoryBarrier : uint32_t {
MemoryBarrier::eVertexBuffer = 0x01 << 0, MemoryBarrier::eIndexBuffer = 0x01 << 1, MemoryBarrier::eUniformBuffer = 0x01 << 2, MemoryBarrier::eAtomicCounterBuffer = 0x01 << 3,
MemoryBarrier::eQueryBuffer = 0x01 << 4, MemoryBarrier::eShaderStorageBuffer = 0x01 << 5, MemoryBarrier::eTextureFetch = 0x01 << 6, MemoryBarrier::eTextureUpdate = 0x01 << 7,
MemoryBarrier::eFrameBuffer = 0x01 << 8, MemoryBarrier::ePixelBuffer = 0x01 << 9, MemoryBarrier::eAll = 0xFFFFFFFF
}
Supported memory barriers enumeration.
using ParticleFactory = castor::Factory< CpuParticleSystem, castor::String, CpuParticleSystemUPtr, std::function< CpuParticleSystemUPtr(ParticleSystem &) > >
template<typename ElementType >
using ElementInitialiser = std::function< void(std::shared_ptr< ElementType >) >
template<typename ElementType >
using ElementCleaner = std::function< void(std::shared_ptr< ElementType >) >
template<typename ElementType , typename KeyType >
using ElementMerger = std::function< void(CacheBase< ElementType, KeyType > const &, castor::Collection< ElementType, KeyType > &, std::shared_ptr< ElementType >) >
using ListenerCache = Cache< FrameListener, castor::String >
using MeshCache = Cache< Mesh, castor::String >
using SamplerCache = Cache< Sampler, castor::String >
using SceneCache = Cache< Scene, castor::String >
using RenderTechniqueCache = Cache< RenderTechnique, castor::String >
using RenderWindowCache = Cache< RenderWindow, castor::String >
template<typename ElementType >
using ElementAttacher = std::function< void(std::shared_ptr< ElementType >, SceneNodeSPtr, SceneNodeSPtr, SceneNodeSPtr, SceneNodeSPtr) >
template<typename ElementType >
using ElementDetacher = std::function< void(std::shared_ptr< ElementType >) >
using AnimatedObjectGroupCache = Cache< AnimatedObjectGroup, castor::String >
using BillboardListCache = ObjectCache< BillboardList, castor::String >
using CameraCache = ObjectCache< Camera, castor::String >
typedef std::map< castor::String, RenderWindowSPtr > WindowPtrStrMap
DECLARE_SMART_PTR (RenderBuffer)
DECLARE_SMART_PTR (ColourRenderBuffer)
DECLARE_SMART_PTR (DepthStencilRenderBuffer)
DECLARE_SMART_PTR (FrameBufferAttachment)
DECLARE_SMART_PTR (RenderBufferAttachment)
DECLARE_SMART_PTR (TextureAttachment)
DECLARE_SMART_PTR (FrameBuffer)
DECLARE_SMART_PTR (BackBuffers)
DECLARE_SMART_PTR (Engine)
DECLARE_SMART_PTR (Plugin)
DECLARE_SMART_PTR (RendererPlugin)
DECLARE_SMART_PTR (ImporterPlugin)
DECLARE_SMART_PTR (DividerPlugin)
DECLARE_SMART_PTR (GenericPlugin)
DECLARE_SMART_PTR (PostFxPlugin)
DECLARE_SMART_PTR (ParticlePlugin)
DECLARE_SMART_PTR (FrameEvent)
DECLARE_SMART_PTR (FrameListener)
DECLARE_SMART_PTR (IWindowHandle)
DECLARE_SMART_PTR (GpuQuery)
DECLARE_SMART_PTR (PickingPass)
DECLARE_SMART_PTR (TransformFeedback)
DECLARE_SMART_PTR (ComputePipeline)
DECLARE_SMART_PTR (RenderPassTimer)
DECLARE_SMART_PTR (GaussianBlur)
DECLARE_SMART_PTR (ListenerCache)
DECLARE_SMART_PTR (ShaderProgramCache)
DECLARE_SMART_PTR (RenderTargetCache)
DECLARE_SMART_PTR (BillboardListCache)
DECLARE_VECTOR (real, Real)
real array
DECLARE_VECTOR (RenderWindowSPtr, RenderWindowPtr)
RenderWindow pointer array.
DECLARE_VECTOR (RenderBufferSPtr, RenderBufferPtr)
RenderBuffer pointer array.
DECLARE_VECTOR (FrameEventUPtr, FrameEventPtr)
FrameEvent pointer array.
DECLARE_MAP (castor::String, FrameListenerSPtr, FrameListenerPtrStr)
FrameListener pointer map, sorted by name.
DECLARE_MAP (uint32_t, RenderWindowSPtr, RenderWindow)
RenderWindow pointer map, sorted by index.
DECLARE_MAP (castor::String, PluginSPtr, PluginStr)
Plugin map, sorted by name.
DECLARE_MAP (int, castor::String, StrInt)
DECLARE_VECTOR (PostEffectSPtr, PostEffectPtr)
DECLARE_VECTOR (BillboardListSPtr, BillboardList)
DECLARE_MAP (castor::String, RendererPluginSPtr, RendererPtr)
DECLARE_ARRAY (PluginStrMap, PluginType::eCount, PluginStrMap)
DECLARE_MAP (castor::Path, castor::DynamicLibrarySPtr, DynamicLibraryPtrPath)
DECLARE_ARRAY (DynamicLibraryPtrPathMap, PluginType::eCount, DynamicLibraryPtrPathMap)
DECLARE_MAP (castor::Path, PluginType, PluginTypePath)
DECLARE_MAP (castor::String, BillboardListSPtr, BillboardListStr)
Animation
enum AnimationType : uint8_t { AnimationType::eMovable, AnimationType::eSkeleton, AnimationType::eMesh }
Animation types enumeration.
enum InterpolatorType : uint8_t { InterpolatorType::eNearest, InterpolatorType::eLinear }
Interpolation modes enumeration.
enum AnimationState : uint8_t { AnimationState::ePlaying, AnimationState::eStopped, AnimationState::ePaused }
Animation State Enumerator.
enum SkeletonAnimationObjectType : uint8_t { SkeletonAnimationObjectType::eNode, SkeletonAnimationObjectType::eBone }
Class which represents the moving things.
using SubmeshAnimationBuffer = SubmeshAnimationBufferT< float >
using SubmeshAnimationBufferMap = std::map< uint32_t, SubmeshAnimationBuffer >
using GroupAnimationMap = std::map< castor::String, GroupAnimation >
using Point3rInterpolator = Interpolator< castor::Point3r >
using QuaternionInterpolator = Interpolator< castor::Quaternion >
using AnimationKeyFrameArray = std::vector< AnimationKeyFrameUPtr >
DECLARE_SMART_PTR (Animation)
DECLARE_SMART_PTR (AnimationKeyFrame)
DECLARE_SMART_PTR (SkeletonAnimation)
DECLARE_SMART_PTR (SkeletonAnimationKeyFrame)
DECLARE_SMART_PTR (SkeletonAnimationObject)
DECLARE_SMART_PTR (SkeletonAnimationBone)
DECLARE_SMART_PTR (SkeletonAnimationNode)
DECLARE_SMART_PTR (MeshAnimation)
DECLARE_SMART_PTR (MeshAnimationKeyFrame)
DECLARE_SMART_PTR (MeshAnimationSubmesh)
DECLARE_SMART_PTR (Animable)
DECLARE_MAP (castor::String, AnimationSPtr, AnimationPtrStr)
Animation pointer map, sorted by name.
DECLARE_MAP (castor::String, SkeletonAnimationObjectSPtr, SkeletonAnimationObjectPtrStr)
SkeletonAnimationObject pointer map, sorted by name.
DECLARE_VECTOR (SkeletonAnimationObjectSPtr, SkeletonAnimationObjectPtr)
SkeletonAnimationObject pointer array.
DECLARE_VECTOR (MeshAnimationSubmesh, MeshAnimationSubmesh)
SkeletonAnimationObject array.
Geometry
enum MeshType : uint8_t {
MeshType::eCustom, MeshType::eCone, MeshType::eCylinder, MeshType::eSphere,
MeshType::eCube, MeshType::eTorus, MeshType::ePlane, MeshType::eIcosahedron,
MeshType::eProjection
}
Mesh type enumeration.
using VertexPattern = Pattern< Vertex >
using Point3rPattern = Pattern< castor::Point3r >
using VertexPtrPattern = Pattern< VertexSPtr >
using Point3rPtrPattern = Pattern< castor::Point3rSPtr >
DECLARE_SMART_PTR (Vertex)
DECLARE_SMART_PTR (BufferElementGroup)
DECLARE_SMART_PTR (VertexPattern)
DECLARE_SMART_PTR (Point3rPattern)
DECLARE_SMART_PTR (VertexPtrPattern)
DECLARE_SMART_PTR (Face)
DECLARE_SMART_PTR (Graph)
DECLARE_SMART_PTR (Mesh)
DECLARE_SMART_PTR (MeshGenerator)
DECLARE_SMART_PTR (Submesh)
DECLARE_SMART_PTR (SubmeshComponent)
DECLARE_SMART_PTR (InstantiationComponent)
DECLARE_SMART_PTR (BonesInstantiationComponent)
DECLARE_SMART_PTR (IndexMapping)
DECLARE_SMART_PTR (Cone)
DECLARE_SMART_PTR (Cylinder)
DECLARE_SMART_PTR (Icosahedron)
DECLARE_SMART_PTR (Cube)
DECLARE_SMART_PTR (Plane)
DECLARE_SMART_PTR (Projection)
DECLARE_SMART_PTR (Sphere)
DECLARE_SMART_PTR (Torus)
DECLARE_SMART_PTR (Geometry)
DECLARE_SMART_PTR (MovableObject)
DECLARE_SMART_PTR (Subdivider)
DECLARE_SMART_PTR (FaceGroup)
DECLARE_SMART_PTR (Bone)
DECLARE_SMART_PTR (Skeleton)
DECLARE_SMART_PTR (BonedVertex)
DECLARE_SMART_PTR (MeshFactory)
DECLARE_VECTOR (Vertex, Vertex)
Vertex array.
DECLARE_VECTOR (BufferElementGroupSPtr, VertexPtr)
Vertex pointer array.
DECLARE_VECTOR (Face, Face)
Face array.
DECLARE_VECTOR (FaceSPtr, FacePtr)
Face pointer array.
DECLARE_VECTOR (FaceGroupSPtr, FaceGroupPtr)
FaceGroup pointer array.
DECLARE_VECTOR (SubmeshSPtr, SubmeshPtr)
Submesh pointer array.
DECLARE_VECTOR (GeometrySPtr, GeometryPtr)
Geometry pointer array.
DECLARE_LIST (VertexSPtr, VertexPtr)
Vertex pointer list.
DECLARE_MAP (castor::String, MeshSPtr, MeshPtrStr)
Mesh pointer array.
DECLARE_MAP (castor::String, MovableObjectSPtr, MovableObjectPtrStr)
MovableObject pointer map, sorted by name.
DECLARE_MAP (castor::String, GeometrySPtr, GeometryPtrStr)
Geometry pointer map, sorted by name.
DECLARE_MAP (uint32_t, int, IntUInt)
DECLARE_MAP (castor::String, SubmeshSPtr, SubmeshPtrStr)
DECLARE_MAP (castor::String, int, IntStr)
DECLARE_VECTOR (BoneSPtr, BonePtr)
Bone pointer array.
DECLARE_MAP (castor::String, BoneSPtr, BonePtrStr)
Bone pointer map sorted by name.
DECLARE_VECTOR (BonedVertexSPtr, BonedVertexPtr)
BonedVertex pointer array.
DECLARE_MAP (castor::String, SubmeshComponentSPtr, SubmeshComponentStr)
Light
enum LightType : uint8_t { LightType::eDirectional, LightType::ePoint, LightType::eSpot }
Light types enumeration.
using OnLightChangedFunction = std::function< void(Light &) >
using OnLightChanged = castor::Signal< OnLightChangedFunction >
using OnLightChangedConnection = OnLightChanged::connection
DECLARE_SMART_PTR (Light)
DECLARE_SMART_PTR (LightCategory)
DECLARE_SMART_PTR (DirectionalLight)
DECLARE_SMART_PTR (PointLight)
DECLARE_SMART_PTR (SpotLight)
DECLARE_SMART_PTR (LightFactory)
DECLARE_VECTOR (LightSPtr, LightPtr)
Array of lights.
DECLARE_MAP (castor::String, LightSPtr, LightPtrStr)
Map of lights, sorted by name.
DECLARE_MAP (int, LightSPtr, LightPtrInt)
Map of lights, sorted by index.
Material
enum MaterialType { MaterialType::eLegacy, MaterialType::ePbrMetallicRoughness, MaterialType::ePbrSpecularGlossiness }
Supported material types enumeration.
enum PassFlag : uint8_t {
PassFlag::eAlphaBlending = 0x01, PassFlag::eAlphaTest = 0x02, PassFlag::ePbrMetallicRoughness = 0x04, PassFlag::ePbrSpecularGlossiness = 0x08,
PassFlag::eSubsurfaceScattering = 0x10, PassFlag::eDistanceBasedTransmittance = 0x20, PassFlag::eParallaxOcclusionMapping = 0x40
}
Pass specific flags.
enum ComparisonFunc : uint8_t {
ComparisonFunc::eAlways = 0x0, ComparisonFunc::eLess = 0x1, ComparisonFunc::eLEqual = 0x2, ComparisonFunc::eEqual = 0x3,
ComparisonFunc::eNEqual = 0x4, ComparisonFunc::eGEqual = 0x5, ComparisonFunc::eGreater = 0x6, ComparisonFunc::eNever = 0x7
}
Alpha functions enumeration.
enum TextureUVW : uint8_t { TextureUVW::eU, TextureUVW::eV, TextureUVW::eW }
Texture UVW enumeration.
enum WrapMode : uint8_t { WrapMode::eRepeat, WrapMode::eMirroredRepeat, WrapMode::eClampToBorder, WrapMode::eClampToEdge }
Texture wrap modes enumeration.
enum InterpolationFilter : uint8_t { InterpolationFilter::eMin, InterpolationFilter::eMag, InterpolationFilter::eMip, InterpolationFilter::eCount }
Texture interpolation filters enumeration.
enum ComparisonMode : uint8_t { ComparisonMode::eNone, ComparisonMode::eRefToTexture }
Texture comparison modes enumeration.
enum InterpolationMode : uint8_t { InterpolationMode::eUndefined, InterpolationMode::eNearest, InterpolationMode::eLinear }
Texture filter interpolation modes enumeration.
enum BlendSrcIndex : uint8_t { BlendSrcIndex::eIndex0, BlendSrcIndex::eIndex1, BlendSrcIndex::eIndex2 }
Texture blending source indices enumeration.
enum BlendSource : uint8_t {
BlendSource::eTexture, BlendSource::eTexture0, BlendSource::eTexture1, BlendSource::eTexture2,
BlendSource::eTexture3, BlendSource::eConstant, BlendSource::eDiffuse, BlendSource::ePrevious
}
Texture blending sources enumeration.
enum TextureBlendFunc : uint8_t {
TextureBlendFunc::eNoBlend, TextureBlendFunc::eFirstArg, TextureBlendFunc::eAdd, TextureBlendFunc::eAddSigned,
TextureBlendFunc::eModulate, TextureBlendFunc::eInterpolate, TextureBlendFunc::eSubtract
}
RGB blending functions enumeration.
enum BlendOperation : uint8_t {
BlendOperation::eAdd, BlendOperation::eSubtract, BlendOperation::eRevSubtract, BlendOperation::eMin,
BlendOperation::eMax, BlendOperation::eCount
}
Blending operations enumeration.
enum BlendOperand : uint8_t {
BlendOperand::eZero, BlendOperand::eOne, BlendOperand::eSrcColour, BlendOperand::eInvSrcColour,
BlendOperand::eDstColour, BlendOperand::eInvDstColour, BlendOperand::eSrcAlpha, BlendOperand::eInvSrcAlpha,
BlendOperand::eDstAlpha, BlendOperand::eInvDstAlpha, BlendOperand::eConstant, BlendOperand::eInvConstant,
BlendOperand::eSrcAlphaSaturate, BlendOperand::eSrc1Colour, BlendOperand::eInvSrc1Colour, BlendOperand::eSrc1Alpha,
BlendOperand::eInvSrc1Alpha
}
Blend operands enumeration.
enum BlendMode : uint8_t {
BlendMode::eNoBlend, BlendMode::eAdditive, BlendMode::eMultiplicative, BlendMode::eInterpolative,
BlendMode::eABuffer, BlendMode::eDepthPeeling
}
Blending modes enumeration.
enum TextureType : uint8_t {
TextureType::eBuffer, TextureType::eOneDimension, TextureType::eOneDimensionArray, TextureType::eTwoDimensions,
TextureType::eTwoDimensionsArray, TextureType::eTwoDimensionsMS, TextureType::eTwoDimensionsMSArray, TextureType::eThreeDimensions,
TextureType::eCube, TextureType::eCubeArray
}
Texture dimensions enumeration.
enum TextureStorageType : uint8_t {
TextureStorageType::eBuffer, TextureStorageType::eOneDimension, TextureStorageType::eOneDimensionArray, TextureStorageType::eTwoDimensions,
TextureStorageType::eTwoDimensionsArray, TextureStorageType::eTwoDimensionsMS, TextureStorageType::eThreeDimensions, TextureStorageType::eCubeMap,
TextureStorageType::eCubeMapArray
}
Texture dimensions enumeration.
enum CubeMapFace : uint8_t {
CubeMapFace::ePositiveX, CubeMapFace::eNegativeX, CubeMapFace::ePositiveY, CubeMapFace::eNegativeY,
CubeMapFace::ePositiveZ, CubeMapFace::eNegativeZ
}
Cube map faces.
enum TextureChannel : uint16_t {
TextureChannel::eUndefined = 0x0000, TextureChannel::eDiffuse = 0x0001, TextureChannel::eAlbedo = eDiffuse, TextureChannel::eNormal = 0x0002,
TextureChannel::eOpacity = 0x0004, TextureChannel::eSpecular = 0x0008, TextureChannel::eRoughness = eSpecular, TextureChannel::eHeight = 0x0010,
TextureChannel::eGloss = 0x0020, TextureChannel::eMetallic = eGloss, TextureChannel::eEmissive = 0x040, TextureChannel::eReflection = 0x0080,
TextureChannel::eRefraction = 0x0100, TextureChannel::eAmbientOcclusion = 0x0200, TextureChannel::eTransmittance = 0x0400, TextureChannel::eAll = 0x0FFF,
TextureChannel::eText = 0x1000
}
Texture channels enumeration.
using OnPassChangedFunction = std::function< void(Pass const &) >
using OnPassChanged = castor::Signal< OnPassChangedFunction >
using OnPassChangedConnection = OnPassChanged::connection
using OnMaterialChangedFunction = std::function< void(Material const &) >
using OnMaterialChanged = castor::Signal< OnMaterialChangedFunction >
using OnMaterialChangedConnection = OnMaterialChanged::connection
DECLARE_SMART_PTR (TextureImage)
DECLARE_SMART_PTR (TextureLayout)
DECLARE_SMART_PTR (TextureStorage)
DECLARE_SMART_PTR (TextureUnit)
DECLARE_SMART_PTR (Material)
DECLARE_SMART_PTR (Pass)
DECLARE_SMART_PTR (LegacyPass)
DECLARE_SMART_PTR (MetallicRoughnessPbrPass)
DECLARE_SMART_PTR (SpecularGlossinessPbrPass)
DECLARE_SMART_PTR (Sampler)
DECLARE_SMART_PTR (SubsurfaceScattering)
DECLARE_VECTOR (MaterialSPtr, MaterialPtr)
Material pointer array.
DECLARE_VECTOR (TextureUnit, TextureUnit)
TextureUnit array.
DECLARE_VECTOR (TextureUnitSPtr, TextureUnitPtr)
TextureUnit pointer array.
DECLARE_VECTOR (Pass, Pass)
Pass array.
DECLARE_VECTOR (PassSPtr, PassPtr)
Pass pointer array.
DECLARE_VECTOR (uint32_t, UInt)
uint32_t array
DECLARE_MAP (castor::String, MaterialSPtr, MaterialPtrStr)
Material pointer map, sorted by name.
DECLARE_MAP (uint32_t, MaterialSPtr, MaterialPtrUInt)
Material pointer map.
DECLARE_VECTOR (std::reference_wrapper< TextureUnit >, DepthMap)
TextureUnit reference array.
Overlay
enum OverlayType : uint8_t { OverlayType::ePanel, OverlayType::eBorderPanel, OverlayType::eText }
Overlay types enumeration.
enum TextWrappingMode { TextWrappingMode::eNone, TextWrappingMode::eBreak, TextWrappingMode::eBreakWords }
Text wrapping modes, handles the way text is cut when it overflows the overlay width.
enum TextTexturingMode { TextTexturingMode::eLetter, TextTexturingMode::eText }
Text texturing modes, handles the way textures are appied to text overlays.
enum TextLineSpacingMode { TextLineSpacingMode::eOwnHeight, TextLineSpacingMode::eMaxLineHeight, TextLineSpacingMode::eMaxFontHeight }
Text line spacing modes, handles the way lines are spaced, which each other, inside one TextOverlay.
enum HAlign { HAlign::eLeft, HAlign::eCenter, HAlign::eRight }
Horizontal alignments for text overlays.
enum VAlign { VAlign::eTop, VAlign::eCenter, VAlign::eBottom }
Vertical alignments for text overlays.
enum BorderPosition { BorderPosition::eInternal, BorderPosition::eMiddle, BorderPosition::eExternal }
Text wrapping modes, handles the way text is cut when it overflows the overlay width.
DECLARE_SMART_PTR (OverlayFactory)
DECLARE_SMART_PTR (OverlayRenderer)
DECLARE_SMART_PTR (FontTexture)
DECLARE_SMART_PTR (Overlay)
DECLARE_SMART_PTR (OverlayCategory)
DECLARE_SMART_PTR (PanelOverlay)
DECLARE_SMART_PTR (BorderPanelOverlay)
DECLARE_SMART_PTR (TextOverlay)
DECLARE_VECTOR (OverlaySPtr, OverlayPtr)
DECLARE_MAP (castor::String, OverlaySPtr, OverlayPtrStr)
Render
enum AccessType : uint8_t { AccessType::eNone = 0, AccessType::eRead = 1 << 0, AccessType::eWrite = 1 << 1 }
Access types enumeration.
enum BufferAccessType : uint32_t { BufferAccessType::eStatic = 1 << 0, BufferAccessType::eDynamic = 1 << 1, BufferAccessType::eStream = 1 << 2 }
Buffer access types enumeration.
enum BufferAccessNature : uint32_t { BufferAccessNature::eDraw = 1 << 4, BufferAccessNature::eRead = 1 << 5, BufferAccessNature::eCopy = 1 << 6 }
Buffer access natures enumeration.
enum Topology : uint8_t {
Topology::ePoints, Topology::eLines, Topology::eLineLoop, Topology::eLineStrip,
Topology::eTriangles, Topology::eTriangleStrips, Topology::eTriangleFan
}
Primitive draw types enumeration.
enum DepthFunc : uint8_t {
DepthFunc::eNever, DepthFunc::eLess, DepthFunc::eEqual, DepthFunc::eLEqual,
DepthFunc::eGreater, DepthFunc::eNEqual, DepthFunc::eGEqual, DepthFunc::eAlways
}
Depth functions enumeration.
enum WritingMask : uint8_t { WritingMask::eZero, WritingMask::eAll }
Wrinting masks enumeration.
enum StencilFunc : uint8_t {
StencilFunc::eNever, StencilFunc::eLess, StencilFunc::eEqual, StencilFunc::eLEqual,
StencilFunc::eGreater, StencilFunc::eNEqual, StencilFunc::eGEqual, StencilFunc::eAlways
}
Stencil functions enumeration.
enum StencilOp : uint8_t {
StencilOp::eKeep, StencilOp::eZero, StencilOp::eReplace, StencilOp::eIncrement,
StencilOp::eIncrWrap, StencilOp::eDecrement, StencilOp::eDecrWrap, StencilOp::eInvert
}
Stencil functions enumeration.
enum ElementUsage : uint32_t {
ElementUsage::eUnknown = 0x000, ElementUsage::ePosition = 0x001, ElementUsage::eNormal = 0x002, ElementUsage::eTangent = 0x004,
ElementUsage::eBitangent = 0x008, ElementUsage::eDiffuse = 0x010, ElementUsage::eTexCoords = 0x020, ElementUsage::eBoneIds0 = 0x040,
ElementUsage::eBoneIds1 = 0x080, ElementUsage::eBoneWeights0 = 0x100, ElementUsage::eBoneWeights1 = 0x200, ElementUsage::eTransform = 0x400,
ElementUsage::eMatIndex = 0x800
}
Element usage enumeration.
enum ElementType : uint8_t {
ElementType::eFloat, ElementType::eVec2, ElementType::eVec3, ElementType::eVec4,
ElementType::eColour, ElementType::eInt, ElementType::eIVec2, ElementType::eIVec3,
ElementType::eIVec4, ElementType::eUInt, ElementType::eUIVec2, ElementType::eUIVec3,
ElementType::eUIVec4, ElementType::eMat2, ElementType::eMat3, ElementType::eMat4
}
Element type enumeration.
enum BufferType : uint32_t {
BufferType::eArray, BufferType::eElementArray, BufferType::eUniform, BufferType::eAtomicCounter,
BufferType::eShaderStorage
}
GPU buffers types enumeration.
using VertexBufferArray = std::vector< std::reference_wrapper< VertexBuffer > >
using RenderQueueArray = std::vector< std::reference_wrapper< RenderQueue > >
using ShadowMapRefArray = std::vector< std::reference_wrapper< ShadowMap > >
using ShadowMapLightTypeArray = std::array< ShadowMapRefArray, size_t(LightType::eCount) >
static castor::String const getTopologyName (Topology p_topology)
gets the name of the given topology.
uint32_t getSize (ElementType p_type)
gets the byte size of the given element type.
C3D_API castor::String getName (ElementType p_type)
gets the name of the given element type.
DECLARE_SMART_PTR (BlendState)
DECLARE_SMART_PTR (BufferDeclaration)
DECLARE_SMART_PTR (BufferElementDeclaration)
DECLARE_SMART_PTR (Context)
DECLARE_SMART_PTR (DepthStencilState)
DECLARE_SMART_PTR (EnvironmentMap)
DECLARE_SMART_PTR (EnvironmentMapPass)
DECLARE_SMART_PTR (GeometryBuffers)
DECLARE_SMART_PTR (GpuBuffer)
DECLARE_SMART_PTR (IblTextures)
DECLARE_SMART_PTR (IndexBuffer)
DECLARE_SMART_PTR (MultisampleState)
DECLARE_SMART_PTR (PostEffect)
DECLARE_SMART_PTR (RasteriserState)
DECLARE_SMART_PTR (RenderColourCubeLayerToTexture)
DECLARE_SMART_PTR (RenderColourCubeToTexture)
DECLARE_SMART_PTR (RenderColourLayerToTexture)
DECLARE_SMART_PTR (RenderColourToCube)
DECLARE_SMART_PTR (RenderColourToTexture)
DECLARE_SMART_PTR (RenderDepthCubeLayerToTexture)
DECLARE_SMART_PTR (RenderDepthCubeToTexture)
DECLARE_SMART_PTR (RenderDepthLayerToTexture)
DECLARE_SMART_PTR (RenderDepthToCube)
DECLARE_SMART_PTR (RenderLoop)
DECLARE_SMART_PTR (RenderPipeline)
DECLARE_SMART_PTR (RenderSystem)
DECLARE_SMART_PTR (RenderTarget)
DECLARE_SMART_PTR (RenderTechnique)
DECLARE_SMART_PTR (RenderWindow)
DECLARE_SMART_PTR (ShadowMap)
DECLARE_SMART_PTR (ShadowMapPass)
DECLARE_SMART_PTR (TextureBuffer)
DECLARE_SMART_PTR (TextureProjection)
DECLARE_SMART_PTR (ToneMapping)
DECLARE_SMART_PTR (VertexBuffer)
DECLARE_MAP (RenderWindow *, ContextSPtr, ContextPtr)
DECLARE_MAP (std::thread::id, ContextPtrMap, ContextPtrMapId)
Scene
enum ShadowType { ShadowType::eNone, ShadowType::ePCF }
Shadow filter types enumeration.
enum FogType { FogType::eDisabled, FogType::eLinear, FogType::eExponential, FogType::eSquaredExponential }
Fog types enumeration.
enum SceneFlag : uint16_t {
SceneFlag::eNone = 0x000, SceneFlag::eFogLinear = 0x001, SceneFlag::eFogExponential = 0x002, SceneFlag::eFogSquaredExponential = 0x003,
SceneFlag::eShadowFilterPcf = 0x004
}
Scene flags enumeration.
enum BillboardType { BillboardType::eSpherical, BillboardType::eCylindrical }
Billboard rendering types enumeration.
enum BillboardSize { BillboardSize::eDynamic, BillboardSize::eFixed }
Billboard sizing types enumeration.
using OnSceneChangedFunction = std::function< void(Scene const &) >
using OnSceneChanged = castor::Signal< OnSceneChangedFunction >
using OnSceneChangedConnection = OnSceneChanged::connection
using OnSceneUpdateFunction = std::function< void(Scene const &) >
using OnSceneUpdate = castor::Signal< OnSceneUpdateFunction >
using OnSceneUpdateConnection = OnSceneUpdate::connection
using OnCameraChangedFunction = std::function< void(Camera const &) >
using OnCameraChanged = castor::Signal< OnCameraChangedFunction >
using OnCameraChangedConnection = OnCameraChanged::connection
using OnSceneNodeChangedFunction = std::function< void(SceneNode const &) >
using OnSceneNodeChanged = castor::Signal< OnSceneNodeChangedFunction >
using OnSceneNodeChangedConnection = OnSceneNodeChanged::connection
using SubmeshBoundingBoxList = std::vector< std::pair< Submesh const *, castor::BoundingBox > >
using SubmeshBoundingBoxMap = std::map< Submesh const *, castor::BoundingBox >
using SubmeshBoundingSphereMap = std::map< Submesh const *, castor::BoundingSphere >
using SubmeshMaterialMap = std::map< Submesh const *, MaterialWPtr >
C3D_API ShadowType getShadowType (SceneFlags const &p_flags)
Gives the shadow filter type matching the given flags.
C3D_API FogType getFogType (SceneFlags const &p_flags)
Gives the fog type matching the given flags.
DECLARE_SMART_PTR (SceneNode)
DECLARE_SMART_PTR (Scene)
DECLARE_SMART_PTR (SceneFileContext)
DECLARE_SMART_PTR (SceneFileParser)
DECLARE_SMART_PTR (Skybox)
DECLARE_SMART_PTR (ParticleSystem)
DECLARE_SMART_PTR (ParticleSystemImpl)
DECLARE_SMART_PTR (CpuParticleSystem)
DECLARE_SMART_PTR (TransformFeedbackParticleSystem)
DECLARE_SMART_PTR (ComputeParticleSystem)
DECLARE_SMART_PTR (AnimatedObject)
DECLARE_SMART_PTR (AnimatedObjectGroup)
DECLARE_SMART_PTR (AnimatedSkeleton)
DECLARE_SMART_PTR (AnimatedMesh)
DECLARE_SMART_PTR (AnimationInstance)
DECLARE_SMART_PTR (SkeletonAnimationInstance)
DECLARE_SMART_PTR (SkeletonAnimationInstanceObject)
DECLARE_SMART_PTR (SkeletonAnimationInstanceNode)
DECLARE_SMART_PTR (SkeletonAnimationInstanceBone)
DECLARE_SMART_PTR (MeshAnimationInstance)
DECLARE_SMART_PTR (BillboardBase)
DECLARE_SMART_PTR (BillboardList)
DECLARE_VECTOR (SceneNodeSPtr, SceneNodePtr)
SceneNode pointer array.
DECLARE_MAP (castor::String, SceneSPtr, ScenePtrStr)
Scene pointer map, sorted by name.
DECLARE_MAP (castor::String, SceneNodeSPtr, SceneNodePtrStr)
SceneNode pointer map, sorted by name.
DECLARE_MAP (castor::String, AnimatedObjectGroupSPtr, AnimatedObjectGroupPtrStr)
AnimatedObjectGroup pointer map, sorted by name.
DECLARE_MAP (castor::String, AnimatedObjectSPtr, AnimatedObjectPtrStr)
AnimatedObject pointer map, sorted by name.
DECLARE_MAP (castor::String, SkeletonAnimationInstanceObjectSPtr, SkeletonAnimationInstanceObjectPtrStr)
MovingObject pointer map, sorted by name.
DECLARE_VECTOR (SkeletonAnimationInstanceObjectSPtr, SkeletonAnimationInstanceObjectPtr)
SkeletonAnimationInstanceObject pointer array.
DECLARE_MAP (uint32_t, MeshAnimationInstanceSubmesh, MeshAnimationInstanceSubmesh)
MeshAnimationInstanceSubmesh map, sorted by submesh ID.
DECLARE_MAP (castor::String, AnimationInstanceUPtr, AnimationInstancePtrStr)
Animation pointer map, sorted by name.
DECLARE_VECTOR (std::reference_wrapper< SkeletonAnimationInstance >, SkeletonAnimationInstance)
Skeleton animation instance pointer array.
Shader
enum ShaderModel : uint8_t {
ShaderModel::eModel1, ShaderModel::eModel2, ShaderModel::eModel3, ShaderModel::eModel4,
ShaderModel::eModel5
}
Enumeration of existing shader models.
enum ShaderStatus : uint8_t { ShaderStatus::edontExist, ShaderStatus::eNotCompiled, ShaderStatus::eError, ShaderStatus::eCompiled }
Shader status enueration.
enum ProgramStatus : uint8_t { ProgramStatus::eNotLinked, ProgramStatus::eError, ProgramStatus::eLinked }
Program status enumeration.
enum ShaderType : int8_t {
ShaderType::eNone = -1, ShaderType::eVertex, ShaderType::eHull, ShaderType::eDomain,
ShaderType::eGeometry, ShaderType::ePixel, ShaderType::eCompute
}
Shader object types enumeration.
enum ShaderTypeFlag : uint8_t {
ShaderTypeFlag::eVertex = uint8_t(0x1) << int(ShaderType::eVertex), ShaderTypeFlag::eHull = uint8_t(0x1) << int(ShaderType::eHull), ShaderTypeFlag::eDomain = uint8_t(0x1) << int(ShaderType::eDomain), ShaderTypeFlag::eGeometry = uint8_t(0x1) << int(ShaderType::eGeometry),
ShaderTypeFlag::ePixel = uint8_t(0x1) << int(ShaderType::ePixel), ShaderTypeFlag::eCompute = uint8_t(0x1) << int(ShaderType::eCompute)
}
Shader object types masks.
enum ProgramFlag : uint16_t {
ProgramFlag::eInstantiation = 0x0001, ProgramFlag::eSkinning = 0x0002, ProgramFlag::eBillboards = 0x0004, ProgramFlag::eMorphing = 0x0008,
ProgramFlag::ePicking = 0x0010, ProgramFlag::eLighting = 0x0020, ProgramFlag::eSpherical = 0x0040, ProgramFlag::eFixedSize = 0x0080,
ProgramFlag::eShadowMapDirectional = 0x0100, ProgramFlag::eShadowMapSpot = 0x0200, ProgramFlag::eShadowMapPoint = 0x0400, ProgramFlag::eEnvironmentMapping = 0x0800,
ProgramFlag::eDepthPass = 0x1000
}
Flags to use when looking for an automatically generated program.
enum VariableType : uint8_t {
VariableType::eOne, VariableType::eVec1, VariableType::eVec2, VariableType::eVec3,
VariableType::eVec4, VariableType::eMat1, VariableType::eMat2x2, VariableType::eMat2x3,
VariableType::eMat2x4, VariableType::eMat3x2, VariableType::eMat3x3, VariableType::eMat3x4,
VariableType::eMat4x2, VariableType::eMat4x3, VariableType::eMat4x4
}
Supported variables dimensions enumeration.
enum UniformType : uint8_t {
UniformType::eBool, UniformType::eInt, UniformType::eUInt, UniformType::eFloat,
UniformType::eDouble, UniformType::eSampler, UniformType::eVec2b, UniformType::eVec3b,
UniformType::eVec4b, UniformType::eVec2i, UniformType::eVec3i, UniformType::eVec4i,
UniformType::eVec2ui, UniformType::eVec3ui, UniformType::eVec4ui, UniformType::eVec2f,
UniformType::eVec3f, UniformType::eVec4f, UniformType::eVec2d, UniformType::eVec3d,
UniformType::eVec4d, UniformType::eMat2x2b, UniformType::eMat2x3b, UniformType::eMat2x4b,
UniformType::eMat3x2b, UniformType::eMat3x3b, UniformType::eMat3x4b, UniformType::eMat4x2b,
UniformType::eMat4x3b, UniformType::eMat4x4b, UniformType::eMat2x2i, UniformType::eMat2x3i,
UniformType::eMat2x4i, UniformType::eMat3x2i, UniformType::eMat3x3i, UniformType::eMat3x4i,
UniformType::eMat4x2i, UniformType::eMat4x3i, UniformType::eMat4x4i, UniformType::eMat2x2ui,
UniformType::eMat2x3ui, UniformType::eMat2x4ui, UniformType::eMat3x2ui, UniformType::eMat3x3ui,
UniformType::eMat3x4ui, UniformType::eMat4x2ui, UniformType::eMat4x3ui, UniformType::eMat4x4ui,
UniformType::eMat2x2f, UniformType::eMat2x3f, UniformType::eMat2x4f, UniformType::eMat3x2f,
UniformType::eMat3x3f, UniformType::eMat3x4f, UniformType::eMat4x2f, UniformType::eMat4x3f,
UniformType::eMat4x4f, UniformType::eMat2x2d, UniformType::eMat2x3d, UniformType::eMat2x4d,
UniformType::eMat3x2d, UniformType::eMat3x3d, UniformType::eMat3x4d, UniformType::eMat4x2d,
UniformType::eMat4x3d, UniformType::eMat4x4d, UniformType::eReal = eFloat, UniformType::eVec2r = eVec2f,
UniformType::eVec3r = eVec3f, UniformType::eVec4r = eVec4f, UniformType::eMat2x2r = eMat2x2f, UniformType::eMat2x3r = eMat2x3f,
UniformType::eMat2x4r = eMat2x4f, UniformType::eMat3x2r = eMat3x2f, UniformType::eMat3x3r = eMat3x3f, UniformType::eMat3x4r = eMat3x4f,
UniformType::eMat4x2r = eMat4x2f, UniformType::eMat4x3r = eMat4x3f, UniformType::eMat4x4r = eMat4x4f
}
Supported variables full type enumeration.
using Uniform1b = TUniform< UniformType::eBool >
using Uniform1i = TUniform< UniformType::eInt >
using Uniform1s = TUniform< UniformType::eSampler >
using Uniform1ui = TUniform< UniformType::eUInt >
using Uniform1f = TUniform< UniformType::eFloat >
using Uniform1d = TUniform< UniformType::eDouble >
using Uniform1r = TUniform< UniformType::eReal >
using Uniform2b = TUniform< UniformType::eVec2b >
using Uniform3b = TUniform< UniformType::eVec3b >
using Uniform4b = TUniform< UniformType::eVec4b >
using Uniform2i = TUniform< UniformType::eVec2i >
using Uniform3i = TUniform< UniformType::eVec3i >
using Uniform4i = TUniform< UniformType::eVec4i >
using Uniform2ui = TUniform< UniformType::eVec2ui >
using Uniform3ui = TUniform< UniformType::eVec3ui >
using Uniform4ui = TUniform< UniformType::eVec4ui >
using Uniform2f = TUniform< UniformType::eVec2f >
using Uniform3f = TUniform< UniformType::eVec3f >
using Uniform4f = TUniform< UniformType::eVec4f >
using Uniform2d = TUniform< UniformType::eVec2d >
using Uniform3d = TUniform< UniformType::eVec3d >
using Uniform4d = TUniform< UniformType::eVec4d >
using Uniform2r = TUniform< UniformType::eVec2r >
using Uniform3r = TUniform< UniformType::eVec3r >
using Uniform4r = TUniform< UniformType::eVec4r >
using Uniform2x2b = TUniform< UniformType::eMat2x2b >
using Uniform2x3b = TUniform< UniformType::eMat2x3b >
using Uniform2x4b = TUniform< UniformType::eMat2x4b >
using Uniform3x2b = TUniform< UniformType::eMat3x2b >
using Uniform3x3b = TUniform< UniformType::eMat3x3b >
using Uniform3x4b = TUniform< UniformType::eMat3x4b >
using Uniform4x2b = TUniform< UniformType::eMat4x2b >
using Uniform4x3b = TUniform< UniformType::eMat4x3b >
using Uniform4x4b = TUniform< UniformType::eMat4x4b >
using Uniform2x2i = TUniform< UniformType::eMat2x2i >
using Uniform2x3i = TUniform< UniformType::eMat2x3i >
using Uniform2x4i = TUniform< UniformType::eMat2x4i >
using Uniform3x2i = TUniform< UniformType::eMat3x2i >
using Uniform3x3i = TUniform< UniformType::eMat3x3i >
using Uniform3x4i = TUniform< UniformType::eMat3x4i >
using Uniform4x2i = TUniform< UniformType::eMat4x2i >
using Uniform4x3i = TUniform< UniformType::eMat4x3i >
using Uniform4x4i = TUniform< UniformType::eMat4x4i >
using Uniform2x2ui = TUniform< UniformType::eMat2x2ui >
using Uniform2x3ui = TUniform< UniformType::eMat2x3ui >
using Uniform2x4ui = TUniform< UniformType::eMat2x4ui >
using Uniform3x2ui = TUniform< UniformType::eMat3x2ui >
using Uniform3x3ui = TUniform< UniformType::eMat3x3ui >
using Uniform3x4ui = TUniform< UniformType::eMat3x4ui >
using Uniform4x2ui = TUniform< UniformType::eMat4x2ui >
using Uniform4x3ui = TUniform< UniformType::eMat4x3ui >
using Uniform4x4ui = TUniform< UniformType::eMat4x4ui >
using Uniform2x2f = TUniform< UniformType::eMat2x2f >
using Uniform2x3f = TUniform< UniformType::eMat2x3f >
using Uniform2x4f = TUniform< UniformType::eMat2x4f >
using Uniform3x2f = TUniform< UniformType::eMat3x2f >
using Uniform3x3f = TUniform< UniformType::eMat3x3f >
using Uniform3x4f = TUniform< UniformType::eMat3x4f >
using Uniform4x2f = TUniform< UniformType::eMat4x2f >
using Uniform4x3f = TUniform< UniformType::eMat4x3f >
using Uniform4x4f = TUniform< UniformType::eMat4x4f >
using Uniform2x2d = TUniform< UniformType::eMat2x2d >
using Uniform2x3d = TUniform< UniformType::eMat2x3d >
using Uniform2x4d = TUniform< UniformType::eMat2x4d >
using Uniform3x2d = TUniform< UniformType::eMat3x2d >
using Uniform3x3d = TUniform< UniformType::eMat3x3d >
using Uniform3x4d = TUniform< UniformType::eMat3x4d >
using Uniform4x2d = TUniform< UniformType::eMat4x2d >
using Uniform4x3d = TUniform< UniformType::eMat4x3d >
using Uniform4x4d = TUniform< UniformType::eMat4x4d >
using Uniform2x2r = TUniform< UniformType::eMat2x2r >
using Uniform2x3r = TUniform< UniformType::eMat2x3r >
using Uniform2x4r = TUniform< UniformType::eMat2x4r >
using Uniform3x2r = TUniform< UniformType::eMat3x2r >
using Uniform3x3r = TUniform< UniformType::eMat3x3r >
using Uniform3x4r = TUniform< UniformType::eMat3x4r >
using Uniform4x2r = TUniform< UniformType::eMat4x2r >
using Uniform4x3r = TUniform< UniformType::eMat4x3r >
using Uniform4x4r = TUniform< UniformType::eMat4x4r >
using PushUniform1b = TPushUniform< UniformType::eBool >
using PushUniform1i = TPushUniform< UniformType::eInt >
using PushUniform1s = TPushUniform< UniformType::eSampler >
using PushUniform1ui = TPushUniform< UniformType::eUInt >
using PushUniform1f = TPushUniform< UniformType::eFloat >
using PushUniform1d = TPushUniform< UniformType::eDouble >
using PushUniform1r = TPushUniform< UniformType::eReal >
using PushUniform2b = TPushUniform< UniformType::eVec2b >
using PushUniform3b = TPushUniform< UniformType::eVec3b >
using PushUniform4b = TPushUniform< UniformType::eVec4b >
using PushUniform2i = TPushUniform< UniformType::eVec2i >
using PushUniform3i = TPushUniform< UniformType::eVec3i >
using PushUniform4i = TPushUniform< UniformType::eVec4i >
using PushUniform2ui = TPushUniform< UniformType::eVec2ui >
using PushUniform3ui = TPushUniform< UniformType::eVec3ui >
using PushUniform4ui = TPushUniform< UniformType::eVec4ui >
using PushUniform2f = TPushUniform< UniformType::eVec2f >
using PushUniform3f = TPushUniform< UniformType::eVec3f >
using PushUniform4f = TPushUniform< UniformType::eVec4f >
using PushUniform2d = TPushUniform< UniformType::eVec2d >
using PushUniform3d = TPushUniform< UniformType::eVec3d >
using PushUniform4d = TPushUniform< UniformType::eVec4d >
using PushUniform2r = TPushUniform< UniformType::eVec2r >
using PushUniform3r = TPushUniform< UniformType::eVec3r >
using PushUniform4r = TPushUniform< UniformType::eVec4r >
using PushUniform2x2b = TPushUniform< UniformType::eMat2x2b >
using PushUniform2x3b = TPushUniform< UniformType::eMat2x3b >
using PushUniform2x4b = TPushUniform< UniformType::eMat2x4b >
using PushUniform3x2b = TPushUniform< UniformType::eMat3x2b >
using PushUniform3x3b = TPushUniform< UniformType::eMat3x3b >
using PushUniform3x4b = TPushUniform< UniformType::eMat3x4b >
using PushUniform4x2b = TPushUniform< UniformType::eMat4x2b >
using PushUniform4x3b = TPushUniform< UniformType::eMat4x3b >
using PushUniform4x4b = TPushUniform< UniformType::eMat4x4b >
using PushUniform2x2i = TPushUniform< UniformType::eMat2x2i >
using PushUniform2x3i = TPushUniform< UniformType::eMat2x3i >
using PushUniform2x4i = TPushUniform< UniformType::eMat2x4i >
using PushUniform3x2i = TPushUniform< UniformType::eMat3x2i >
using PushUniform3x3i = TPushUniform< UniformType::eMat3x3i >
using PushUniform3x4i = TPushUniform< UniformType::eMat3x4i >
using PushUniform4x2i = TPushUniform< UniformType::eMat4x2i >
using PushUniform4x3i = TPushUniform< UniformType::eMat4x3i >
using PushUniform4x4i = TPushUniform< UniformType::eMat4x4i >
using PushUniform2x2ui = TPushUniform< UniformType::eMat2x2ui >
using PushUniform2x3ui = TPushUniform< UniformType::eMat2x3ui >
using PushUniform2x4ui = TPushUniform< UniformType::eMat2x4ui >
using PushUniform3x2ui = TPushUniform< UniformType::eMat3x2ui >
using PushUniform3x3ui = TPushUniform< UniformType::eMat3x3ui >
using PushUniform3x4ui = TPushUniform< UniformType::eMat3x4ui >
using PushUniform4x2ui = TPushUniform< UniformType::eMat4x2ui >
using PushUniform4x3ui = TPushUniform< UniformType::eMat4x3ui >
using PushUniform4x4ui = TPushUniform< UniformType::eMat4x4ui >
using PushUniform2x2f = TPushUniform< UniformType::eMat2x2f >
using PushUniform2x3f = TPushUniform< UniformType::eMat2x3f >
using PushUniform2x4f = TPushUniform< UniformType::eMat2x4f >
using PushUniform3x2f = TPushUniform< UniformType::eMat3x2f >
using PushUniform3x3f = TPushUniform< UniformType::eMat3x3f >
using PushUniform3x4f = TPushUniform< UniformType::eMat3x4f >
using PushUniform4x2f = TPushUniform< UniformType::eMat4x2f >
using PushUniform4x3f = TPushUniform< UniformType::eMat4x3f >
using PushUniform4x4f = TPushUniform< UniformType::eMat4x4f >
using PushUniform2x2d = TPushUniform< UniformType::eMat2x2d >
using PushUniform2x3d = TPushUniform< UniformType::eMat2x3d >
using PushUniform2x4d = TPushUniform< UniformType::eMat2x4d >
using PushUniform3x2d = TPushUniform< UniformType::eMat3x2d >
using PushUniform3x3d = TPushUniform< UniformType::eMat3x3d >
using PushUniform3x4d = TPushUniform< UniformType::eMat3x4d >
using PushUniform4x2d = TPushUniform< UniformType::eMat4x2d >
using PushUniform4x3d = TPushUniform< UniformType::eMat4x3d >
using PushUniform4x4d = TPushUniform< UniformType::eMat4x4d >
using PushUniform2x2r = TPushUniform< UniformType::eMat2x2r >
using PushUniform2x3r = TPushUniform< UniformType::eMat2x3r >
using PushUniform2x4r = TPushUniform< UniformType::eMat2x4r >
using PushUniform3x2r = TPushUniform< UniformType::eMat3x2r >
using PushUniform3x3r = TPushUniform< UniformType::eMat3x3r >
using PushUniform3x4r = TPushUniform< UniformType::eMat3x4r >
using PushUniform4x2r = TPushUniform< UniformType::eMat4x2r >
using PushUniform4x3r = TPushUniform< UniformType::eMat4x3r >
using PushUniform4x4r = TPushUniform< UniformType::eMat4x4r >
bool isShadowMapProgram (ProgramFlags const &p_flags)
Tells if the given flags contain a shadow map flag.
DECLARE_SMART_PTR (Uniform1b)
DECLARE_SMART_PTR (PushUniform1b)
DECLARE_SMART_PTR (UniformBuffer)
DECLARE_SMART_PTR (UniformBufferBinding)
DECLARE_SMART_PTR (Uniform)
DECLARE_SMART_PTR (PushUniform)
DECLARE_SMART_PTR (ShaderObject)
DECLARE_SMART_PTR (ShaderProgram)
DECLARE_SMART_PTR (ShaderStorageBuffer)
DECLARE_SMART_PTR (AtomicCounterBuffer)
DECLARE_VECTOR (ShaderProgramSPtr, ShaderProgramPtr)
DECLARE_VECTOR (ShaderObjectSPtr, ShaderObjectPtr)
DECLARE_LIST (PushUniformSPtr, PushUniform)
DECLARE_LIST (UniformSPtr, Uniform)
DECLARE_LIST (UniformBufferSPtr, UniformBufferPtr)
DECLARE_LIST (ShaderStorageBufferSPtr, ShaderStorageBufferPtr)
DECLARE_LIST (AtomicCounterBufferSPtr, AtomicCounterBufferPtr)
DECLARE_MAP (castor::String, PushUniformWPtr, PushUniform)
DECLARE_MAP (castor::String, UniformWPtr, Uniform)
DECLARE_MAP (ShaderProgramRPtr, UniformBufferBindingUPtr, UniformBufferBinding)
DECLARE_MAP (castor::String, UniformBufferWPtr, UniformBufferPtrStr)
DECLARE_MAP (castor::String, ShaderStorageBufferWPtr, ShaderStorageBufferPtrStr)
DECLARE_MAP (castor::String, AtomicCounterBufferWPtr, AtomicCounterBufferPtrStr)
DECLARE_MAP (ShaderType, UniformBufferWPtr, UniformBufferPtrShader)
DECLARE_MAP (ShaderType, ShaderStorageBufferWPtr, ShaderStorageBufferPtrShader)
DECLARE_MAP (ShaderType, AtomicCounterBufferWPtr, AtomicCounterBufferPtrShader)
Typedef Documentation
AnimatedObjectGroupCache
using castor3d::AnimatedObjectGroupCache = typedef Cache< AnimatedObjectGroup, castor::String >
AnimationKeyFrameArray
using castor3d::AnimationKeyFrameArray = typedef std::vector< AnimationKeyFrameUPtr >
BillboardListCache
using castor3d::BillboardListCache = typedef ObjectCache< BillboardList, castor::String >
BillboardListRenderNode
using castor3d::BillboardListRenderNode = typedef ObjectRenderNode< BillboardBase, BillboardBase >
CameraCache
using castor3d::CameraCache = typedef ObjectCache< Camera, castor::String >
DirectionalLightPassShadow
using castor3d::DirectionalLightPassShadow = typedef LightPassShadow< LightType::eDirectional >
The directional lights light pass with shadows.
ElementAttacher
template<typename ElementType > using castor3d::ElementAttacher = typedef std::function< void(std::shared_ptr< ElementType >, SceneNodeSPtr, SceneNodeSPtr, SceneNodeSPtr, SceneNodeSPtr) >
ElementCleaner
template<typename ElementType > using castor3d::ElementCleaner = typedef std::function< void(std::shared_ptr< ElementType >) >
ElementDetacher
template<typename ElementType > using castor3d::ElementDetacher = typedef std::function< void(std::shared_ptr< ElementType >) >
ElementInitialiser
template<typename ElementType > using castor3d::ElementInitialiser = typedef std::function< void(std::shared_ptr< ElementType >) >
ElementMerger
template<typename ElementType , typename KeyType > using castor3d::ElementMerger = typedef std::function< void(CacheBase< ElementType, KeyType > const &, castor::Collection< ElementType, KeyType > &, std::shared_ptr< ElementType >) >
FinalCombinePrograms
using castor3d::FinalCombinePrograms = typedef std::array< FinalCombineProgram, size_t(FogType::eCount) >
An array of FinalCombineProgram, one per fog type.
GeometryCache
using castor3d::GeometryCache = typedef ObjectCache< Geometry, castor::String >
GeometryPassResult
using castor3d::GeometryPassResult = typedef std::array< TextureUnitUPtr, size_t(DsTexture::eCount) >
The geometry pass result.
GpuBufferAllocator
using castor3d::GpuBufferAllocator = typedef castor::BuddyAllocatorT< GpuBufferBuddyAllocatorTraits >
GpuBufferAllocatorUPtr
using castor3d::GpuBufferAllocatorUPtr = typedef std::unique_ptr< GpuBufferAllocator >
GroupAnimationMap
using castor3d::GroupAnimationMap = typedef std::map< castor::String, GroupAnimation >
InterleavedVertex
using castor3d::InterleavedVertex = typedef InterleavedVertexT< real >
InterleavedVertexArray
using castor3d::InterleavedVertexArray = typedef InterleavedVertexTArray< real >
InterleavedVertexTArray
template<typename T > using castor3d::InterleavedVertexTArray = typedef std::vector< InterleavedVertexT< T > >
LightCache
using castor3d::LightCache = typedef ObjectCache< Light, castor::String >
LightsArray
using castor3d::LightsArray = typedef std::vector< LightSPtr >
LightsMap
using castor3d::LightsMap = typedef std::array< LightsArray, size_t(LightType::eCount) >
LightsRefArray
using castor3d::LightsRefArray = typedef std::vector< Light * >
LineArray
using castor3d::LineArray = typedef std::vector< Line >
An array of Lines.
ListenerCache
using castor3d::ListenerCache = typedef Cache< FrameListener, castor::String >
MaterialCache
using castor3d::MaterialCache = typedef Cache< Material, castor::String >
MeshCache
using castor3d::MeshCache = typedef Cache< Mesh, castor::String >
ObjectTransform
using castor3d::ObjectTransform = typedef std::pair< SkeletonAnimationObject *, castor::Matrix4x4r >
OnCameraChanged
using castor3d::OnCameraChanged = typedef castor::Signal< OnCameraChangedFunction >
OnCameraChangedConnection
using castor3d::OnCameraChangedConnection = typedef OnCameraChanged::connection
OnCameraChangedFunction
using castor3d::OnCameraChangedFunction = typedef std::function< void(Camera const &) >
OnLightChanged
using castor3d::OnLightChanged = typedef castor::Signal< OnLightChangedFunction >
OnLightChangedConnection
using castor3d::OnLightChangedConnection = typedef OnLightChanged::connection
OnLightChangedFunction
using castor3d::OnLightChangedFunction = typedef std::function< void(Light &) >
OnMaterialChanged
using castor3d::OnMaterialChanged = typedef castor::Signal< OnMaterialChangedFunction >
OnMaterialChangedConnection
using castor3d::OnMaterialChangedConnection = typedef OnMaterialChanged::connection
OnMaterialChangedFunction
using castor3d::OnMaterialChangedFunction = typedef std::function< void(Material const &) >
OnPassChanged
using castor3d::OnPassChanged = typedef castor::Signal< OnPassChangedFunction >
OnPassChangedConnection
using castor3d::OnPassChangedConnection = typedef OnPassChanged::connection
OnPassChangedFunction
using castor3d::OnPassChangedFunction = typedef std::function< void(Pass const &) >
OnSceneChanged
using castor3d::OnSceneChanged = typedef castor::Signal< OnSceneChangedFunction >
OnSceneChangedConnection
using castor3d::OnSceneChangedConnection = typedef OnSceneChanged::connection
OnSceneChangedFunction
using castor3d::OnSceneChangedFunction = typedef std::function< void(Scene const &) >
OnSceneNodeChanged
using castor3d::OnSceneNodeChanged = typedef castor::Signal< OnSceneNodeChangedFunction >
OnSceneNodeChangedConnection
using castor3d::OnSceneNodeChangedConnection = typedef OnSceneNodeChanged::connection
OnSceneNodeChangedFunction
using castor3d::OnSceneNodeChangedFunction = typedef std::function< void(SceneNode const &) >
OnSceneUpdate
using castor3d::OnSceneUpdate = typedef castor::Signal< OnSceneUpdateFunction >
OnSceneUpdateConnection
using castor3d::OnSceneUpdateConnection = typedef OnSceneUpdate::connection
OnSceneUpdateFunction
using castor3d::OnSceneUpdateFunction = typedef std::function< void(Scene const &) >
OverlayCache
using castor3d::OverlayCache = typedef Cache< Overlay, castor::String >
OverlayCategorySet
using castor3d::OverlayCategorySet = typedef std::set< OverlayCategorySPtr, OverlayCategorySort >
ParticleArray
using castor3d::ParticleArray = typedef std::vector< Particle >
ParticleFactory
using castor3d::ParticleFactory = typedef castor::Factory< CpuParticleSystem, castor::String, CpuParticleSystemUPtr, std::function< CpuParticleSystemUPtr(ParticleSystem &) > >
PluginCache
using castor3d::PluginCache = typedef Cache< Plugin, castor::String >
Point3rInterpolator
using castor3d::Point3rInterpolator = typedef Interpolator< castor::Point3r >
Point3rPattern
using castor3d::Point3rPattern = typedef Pattern< castor::Point3r >
Point3rPtrPattern
using castor3d::Point3rPtrPattern = typedef Pattern< castor::Point3rSPtr >
PointLightPassShadow
using castor3d::PointLightPassShadow = typedef LightPassShadow< LightType::ePoint >
The point lights light pass with shadows.
PostEffectFactory
using castor3d::PostEffectFactory = typedef castor::Factory< PostEffect, castor::String, std::shared_ptr< PostEffect >, std::function< PostEffectSPtr(RenderTarget &, RenderSystem &, Parameters const &) > >
Post effect factory.
Author
Sylvain DOREMUS
Version
0.9.0
Date
03/07/2016
PushUniform1b
using castor3d::PushUniform1b = typedef TPushUniform< UniformType::eBool >
PushUniform1d
using castor3d::PushUniform1d = typedef TPushUniform< UniformType::eDouble >
PushUniform1f
using castor3d::PushUniform1f = typedef TPushUniform< UniformType::eFloat >
PushUniform1i
using castor3d::PushUniform1i = typedef TPushUniform< UniformType::eInt >
PushUniform1r
using castor3d::PushUniform1r = typedef TPushUniform< UniformType::eReal >
PushUniform1s
using castor3d::PushUniform1s = typedef TPushUniform< UniformType::eSampler >
PushUniform1ui
using castor3d::PushUniform1ui = typedef TPushUniform< UniformType::eUInt >
PushUniform2b
using castor3d::PushUniform2b = typedef TPushUniform< UniformType::eVec2b >
PushUniform2d
using castor3d::PushUniform2d = typedef TPushUniform< UniformType::eVec2d >
PushUniform2f
using castor3d::PushUniform2f = typedef TPushUniform< UniformType::eVec2f >
PushUniform2i
using castor3d::PushUniform2i = typedef TPushUniform< UniformType::eVec2i >
PushUniform2r
using castor3d::PushUniform2r = typedef TPushUniform< UniformType::eVec2r >
PushUniform2ui
using castor3d::PushUniform2ui = typedef TPushUniform< UniformType::eVec2ui >
PushUniform2x2b
using castor3d::PushUniform2x2b = typedef TPushUniform< UniformType::eMat2x2b >
PushUniform2x2d
using castor3d::PushUniform2x2d = typedef TPushUniform< UniformType::eMat2x2d >
PushUniform2x2f
using castor3d::PushUniform2x2f = typedef TPushUniform< UniformType::eMat2x2f >
PushUniform2x2i
using castor3d::PushUniform2x2i = typedef TPushUniform< UniformType::eMat2x2i >
PushUniform2x2r
using castor3d::PushUniform2x2r = typedef TPushUniform< UniformType::eMat2x2r >
PushUniform2x2ui
using castor3d::PushUniform2x2ui = typedef TPushUniform< UniformType::eMat2x2ui >
PushUniform2x3b
using castor3d::PushUniform2x3b = typedef TPushUniform< UniformType::eMat2x3b >
PushUniform2x3d
using castor3d::PushUniform2x3d = typedef TPushUniform< UniformType::eMat2x3d >
PushUniform2x3f
using castor3d::PushUniform2x3f = typedef TPushUniform< UniformType::eMat2x3f >
PushUniform2x3i
using castor3d::PushUniform2x3i = typedef TPushUniform< UniformType::eMat2x3i >
PushUniform2x3r
using castor3d::PushUniform2x3r = typedef TPushUniform< UniformType::eMat2x3r >
PushUniform2x3ui
using castor3d::PushUniform2x3ui = typedef TPushUniform< UniformType::eMat2x3ui >
PushUniform2x4b
using castor3d::PushUniform2x4b = typedef TPushUniform< UniformType::eMat2x4b >
PushUniform2x4d
using castor3d::PushUniform2x4d = typedef TPushUniform< UniformType::eMat2x4d >
PushUniform2x4f
using castor3d::PushUniform2x4f = typedef TPushUniform< UniformType::eMat2x4f >
PushUniform2x4i
using castor3d::PushUniform2x4i = typedef TPushUniform< UniformType::eMat2x4i >
PushUniform2x4r
using castor3d::PushUniform2x4r = typedef TPushUniform< UniformType::eMat2x4r >
PushUniform2x4ui
using castor3d::PushUniform2x4ui = typedef TPushUniform< UniformType::eMat2x4ui >
PushUniform3b
using castor3d::PushUniform3b = typedef TPushUniform< UniformType::eVec3b >
PushUniform3d
using castor3d::PushUniform3d = typedef TPushUniform< UniformType::eVec3d >
PushUniform3f
using castor3d::PushUniform3f = typedef TPushUniform< UniformType::eVec3f >
PushUniform3i
using castor3d::PushUniform3i = typedef TPushUniform< UniformType::eVec3i >
PushUniform3r
using castor3d::PushUniform3r = typedef TPushUniform< UniformType::eVec3r >
PushUniform3ui
using castor3d::PushUniform3ui = typedef TPushUniform< UniformType::eVec3ui >
PushUniform3x2b
using castor3d::PushUniform3x2b = typedef TPushUniform< UniformType::eMat3x2b >
PushUniform3x2d
using castor3d::PushUniform3x2d = typedef TPushUniform< UniformType::eMat3x2d >
PushUniform3x2f
using castor3d::PushUniform3x2f = typedef TPushUniform< UniformType::eMat3x2f >
PushUniform3x2i
using castor3d::PushUniform3x2i = typedef TPushUniform< UniformType::eMat3x2i >
PushUniform3x2r
using castor3d::PushUniform3x2r = typedef TPushUniform< UniformType::eMat3x2r >
PushUniform3x2ui
using castor3d::PushUniform3x2ui = typedef TPushUniform< UniformType::eMat3x2ui >
PushUniform3x3b
using castor3d::PushUniform3x3b = typedef TPushUniform< UniformType::eMat3x3b >
PushUniform3x3d
using castor3d::PushUniform3x3d = typedef TPushUniform< UniformType::eMat3x3d >
PushUniform3x3f
using castor3d::PushUniform3x3f = typedef TPushUniform< UniformType::eMat3x3f >
PushUniform3x3i
using castor3d::PushUniform3x3i = typedef TPushUniform< UniformType::eMat3x3i >
PushUniform3x3r
using castor3d::PushUniform3x3r = typedef TPushUniform< UniformType::eMat3x3r >
PushUniform3x3ui
using castor3d::PushUniform3x3ui = typedef TPushUniform< UniformType::eMat3x3ui >
PushUniform3x4b
using castor3d::PushUniform3x4b = typedef TPushUniform< UniformType::eMat3x4b >
PushUniform3x4d
using castor3d::PushUniform3x4d = typedef TPushUniform< UniformType::eMat3x4d >
PushUniform3x4f
using castor3d::PushUniform3x4f = typedef TPushUniform< UniformType::eMat3x4f >
PushUniform3x4i
using castor3d::PushUniform3x4i = typedef TPushUniform< UniformType::eMat3x4i >
PushUniform3x4r
using castor3d::PushUniform3x4r = typedef TPushUniform< UniformType::eMat3x4r >
PushUniform3x4ui
using castor3d::PushUniform3x4ui = typedef TPushUniform< UniformType::eMat3x4ui >
PushUniform4b
using castor3d::PushUniform4b = typedef TPushUniform< UniformType::eVec4b >
PushUniform4d
using castor3d::PushUniform4d = typedef TPushUniform< UniformType::eVec4d >
PushUniform4f
using castor3d::PushUniform4f = typedef TPushUniform< UniformType::eVec4f >
PushUniform4i
using castor3d::PushUniform4i = typedef TPushUniform< UniformType::eVec4i >
PushUniform4r
using castor3d::PushUniform4r = typedef TPushUniform< UniformType::eVec4r >
PushUniform4ui
using castor3d::PushUniform4ui = typedef TPushUniform< UniformType::eVec4ui >
PushUniform4x2b
using castor3d::PushUniform4x2b = typedef TPushUniform< UniformType::eMat4x2b >
PushUniform4x2d
using castor3d::PushUniform4x2d = typedef TPushUniform< UniformType::eMat4x2d >
PushUniform4x2f
using castor3d::PushUniform4x2f = typedef TPushUniform< UniformType::eMat4x2f >
PushUniform4x2i
using castor3d::PushUniform4x2i = typedef TPushUniform< UniformType::eMat4x2i >
PushUniform4x2r
using castor3d::PushUniform4x2r = typedef TPushUniform< UniformType::eMat4x2r >
PushUniform4x2ui
using castor3d::PushUniform4x2ui = typedef TPushUniform< UniformType::eMat4x2ui >
PushUniform4x3b
using castor3d::PushUniform4x3b = typedef TPushUniform< UniformType::eMat4x3b >
PushUniform4x3d
using castor3d::PushUniform4x3d = typedef TPushUniform< UniformType::eMat4x3d >
PushUniform4x3f
using castor3d::PushUniform4x3f = typedef TPushUniform< UniformType::eMat4x3f >
PushUniform4x3i
using castor3d::PushUniform4x3i = typedef TPushUniform< UniformType::eMat4x3i >
PushUniform4x3r
using castor3d::PushUniform4x3r = typedef TPushUniform< UniformType::eMat4x3r >
PushUniform4x3ui
using castor3d::PushUniform4x3ui = typedef TPushUniform< UniformType::eMat4x3ui >
PushUniform4x4b
using castor3d::PushUniform4x4b = typedef TPushUniform< UniformType::eMat4x4b >
PushUniform4x4d
using castor3d::PushUniform4x4d = typedef TPushUniform< UniformType::eMat4x4d >
PushUniform4x4f
using castor3d::PushUniform4x4f = typedef TPushUniform< UniformType::eMat4x4f >
PushUniform4x4i
using castor3d::PushUniform4x4i = typedef TPushUniform< UniformType::eMat4x4i >
PushUniform4x4r
using castor3d::PushUniform4x4r = typedef TPushUniform< UniformType::eMat4x4r >
PushUniform4x4ui
using castor3d::PushUniform4x4ui = typedef TPushUniform< UniformType::eMat4x4ui >
QuaternionInterpolator
using castor3d::QuaternionInterpolator = typedef Interpolator< castor::Quaternion >
RenderQueueArray
using castor3d::RenderQueueArray = typedef std::vector< std::reference_wrapper< RenderQueue > >
RenderSystemFactory
using castor3d::RenderSystemFactory = typedef castor::Factory< RenderSystem, castor::String, RenderSystemUPtr, std::function< RenderSystemUPtr(Engine &) > >
Render technique factory.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
24/11/2014
RenderTechniqueCache
using castor3d::RenderTechniqueCache = typedef Cache< RenderTechnique, castor::String >
RenderWindowCache
using castor3d::RenderWindowCache = typedef Cache< RenderWindow, castor::String >
SamplerCache
using castor3d::SamplerCache = typedef Cache< Sampler, castor::String >
SceneCache
using castor3d::SceneCache = typedef Cache< Scene, castor::String >
SceneNodeCache
using castor3d::SceneNodeCache = typedef ObjectCache< SceneNode, castor::String >
ShadowMapLightTypeArray
using castor3d::ShadowMapLightTypeArray = typedef std::array< ShadowMapRefArray, size_t(LightType::eCount) >
ShadowMapRefArray
using castor3d::ShadowMapRefArray = typedef std::vector< std::reference_wrapper< ShadowMap > >
SkeletonAnimationInstanceKeyFrameArray
using castor3d::SkeletonAnimationInstanceKeyFrameArray = typedef std::vector< SkeletonAnimationInstanceKeyFrame >
SpotLightPassShadow
using castor3d::SpotLightPassShadow = typedef LightPassShadow< LightType::eSpot >
The spot lights light pass with shadows.
SubdividerFactory
using castor3d::SubdividerFactory = typedef castor::Factory< Subdivider, castor::String, SubdividerUPtr >
The subdivider factory.
Author
Sylvain DOREMUS
Version
0.9.0
Date
22/07/2016
SubmeshAnimationBuffer
using castor3d::SubmeshAnimationBuffer = typedef SubmeshAnimationBufferT< float >
SubmeshAnimationBufferMap
using castor3d::SubmeshAnimationBufferMap = typedef std::map< uint32_t, SubmeshAnimationBuffer >
SubmeshBoundingBoxList
using castor3d::SubmeshBoundingBoxList = typedef std::vector< std::pair< Submesh const *, castor::BoundingBox > >
SubmeshBoundingBoxMap
using castor3d::SubmeshBoundingBoxMap = typedef std::map< Submesh const *, castor::BoundingBox >
SubmeshBoundingSphereMap
using castor3d::SubmeshBoundingSphereMap = typedef std::map< Submesh const *, castor::BoundingSphere >
SubmeshMaterialMap
using castor3d::SubmeshMaterialMap = typedef std::map< Submesh const *, MaterialWPtr >
SubmeshRenderNode
using castor3d::SubmeshRenderNode = typedef ObjectRenderNode< Submesh, Geometry >
SubmeshSkinninRenderNodesByPassMap
using castor3d::SubmeshSkinninRenderNodesByPassMap = typedef TypeRenderNodesByPassMap< SubmeshSkinningRenderNodesMap >
SubmeshStaticRenderNodesByPassMap
using castor3d::SubmeshStaticRenderNodesByPassMap = typedef TypeRenderNodesByPassMap< SubmeshStaticRenderNodesMap >
ToneMappingFactory
using castor3d::ToneMappingFactory = typedef castor::Factory< ToneMapping, castor::String, ToneMappingSPtr, std::function< ToneMappingSPtr(Engine &, Parameters const &) > >
Tone mapping factory.
Author
Sylvain DOREMUS
Version
0.8.0
Date
11/03/2016
TransformArray
using castor3d::TransformArray = typedef std::vector< ObjectTransform >
Uniform1b
using castor3d::Uniform1b = typedef TUniform< UniformType::eBool >
Uniform1d
using castor3d::Uniform1d = typedef TUniform< UniformType::eDouble >
Uniform1f
using castor3d::Uniform1f = typedef TUniform< UniformType::eFloat >
Uniform1i
using castor3d::Uniform1i = typedef TUniform< UniformType::eInt >
Uniform1r
using castor3d::Uniform1r = typedef TUniform< UniformType::eReal >
Uniform1s
using castor3d::Uniform1s = typedef TUniform< UniformType::eSampler >
Uniform1ui
using castor3d::Uniform1ui = typedef TUniform< UniformType::eUInt >
Uniform2b
using castor3d::Uniform2b = typedef TUniform< UniformType::eVec2b >
Uniform2d
using castor3d::Uniform2d = typedef TUniform< UniformType::eVec2d >
Uniform2f
using castor3d::Uniform2f = typedef TUniform< UniformType::eVec2f >
Uniform2i
using castor3d::Uniform2i = typedef TUniform< UniformType::eVec2i >
Uniform2r
using castor3d::Uniform2r = typedef TUniform< UniformType::eVec2r >
Uniform2ui
using castor3d::Uniform2ui = typedef TUniform< UniformType::eVec2ui >
Uniform2x2b
using castor3d::Uniform2x2b = typedef TUniform< UniformType::eMat2x2b >
Uniform2x2d
using castor3d::Uniform2x2d = typedef TUniform< UniformType::eMat2x2d >
Uniform2x2f
using castor3d::Uniform2x2f = typedef TUniform< UniformType::eMat2x2f >
Uniform2x2i
using castor3d::Uniform2x2i = typedef TUniform< UniformType::eMat2x2i >
Uniform2x2r
using castor3d::Uniform2x2r = typedef TUniform< UniformType::eMat2x2r >
Uniform2x2ui
using castor3d::Uniform2x2ui = typedef TUniform< UniformType::eMat2x2ui >
Uniform2x3b
using castor3d::Uniform2x3b = typedef TUniform< UniformType::eMat2x3b >
Uniform2x3d
using castor3d::Uniform2x3d = typedef TUniform< UniformType::eMat2x3d >
Uniform2x3f
using castor3d::Uniform2x3f = typedef TUniform< UniformType::eMat2x3f >
Uniform2x3i
using castor3d::Uniform2x3i = typedef TUniform< UniformType::eMat2x3i >
Uniform2x3r
using castor3d::Uniform2x3r = typedef TUniform< UniformType::eMat2x3r >
Uniform2x3ui
using castor3d::Uniform2x3ui = typedef TUniform< UniformType::eMat2x3ui >
Uniform2x4b
using castor3d::Uniform2x4b = typedef TUniform< UniformType::eMat2x4b >
Uniform2x4d
using castor3d::Uniform2x4d = typedef TUniform< UniformType::eMat2x4d >
Uniform2x4f
using castor3d::Uniform2x4f = typedef TUniform< UniformType::eMat2x4f >
Uniform2x4i
using castor3d::Uniform2x4i = typedef TUniform< UniformType::eMat2x4i >
Uniform2x4r
using castor3d::Uniform2x4r = typedef TUniform< UniformType::eMat2x4r >
Uniform2x4ui
using castor3d::Uniform2x4ui = typedef TUniform< UniformType::eMat2x4ui >
Uniform3b
using castor3d::Uniform3b = typedef TUniform< UniformType::eVec3b >
Uniform3d
using castor3d::Uniform3d = typedef TUniform< UniformType::eVec3d >
Uniform3f
using castor3d::Uniform3f = typedef TUniform< UniformType::eVec3f >
Uniform3i
using castor3d::Uniform3i = typedef TUniform< UniformType::eVec3i >
Uniform3r
using castor3d::Uniform3r = typedef TUniform< UniformType::eVec3r >
Uniform3ui
using castor3d::Uniform3ui = typedef TUniform< UniformType::eVec3ui >
Uniform3x2b
using castor3d::Uniform3x2b = typedef TUniform< UniformType::eMat3x2b >
Uniform3x2d
using castor3d::Uniform3x2d = typedef TUniform< UniformType::eMat3x2d >
Uniform3x2f
using castor3d::Uniform3x2f = typedef TUniform< UniformType::eMat3x2f >
Uniform3x2i
using castor3d::Uniform3x2i = typedef TUniform< UniformType::eMat3x2i >
Uniform3x2r
using castor3d::Uniform3x2r = typedef TUniform< UniformType::eMat3x2r >
Uniform3x2ui
using castor3d::Uniform3x2ui = typedef TUniform< UniformType::eMat3x2ui >
Uniform3x3b
using castor3d::Uniform3x3b = typedef TUniform< UniformType::eMat3x3b >
Uniform3x3d
using castor3d::Uniform3x3d = typedef TUniform< UniformType::eMat3x3d >
Uniform3x3f
using castor3d::Uniform3x3f = typedef TUniform< UniformType::eMat3x3f >
Uniform3x3i
using castor3d::Uniform3x3i = typedef TUniform< UniformType::eMat3x3i >
Uniform3x3r
using castor3d::Uniform3x3r = typedef TUniform< UniformType::eMat3x3r >
Uniform3x3ui
using castor3d::Uniform3x3ui = typedef TUniform< UniformType::eMat3x3ui >
Uniform3x4b
using castor3d::Uniform3x4b = typedef TUniform< UniformType::eMat3x4b >
Uniform3x4d
using castor3d::Uniform3x4d = typedef TUniform< UniformType::eMat3x4d >
Uniform3x4f
using castor3d::Uniform3x4f = typedef TUniform< UniformType::eMat3x4f >
Uniform3x4i
using castor3d::Uniform3x4i = typedef TUniform< UniformType::eMat3x4i >
Uniform3x4r
using castor3d::Uniform3x4r = typedef TUniform< UniformType::eMat3x4r >
Uniform3x4ui
using castor3d::Uniform3x4ui = typedef TUniform< UniformType::eMat3x4ui >
Uniform4b
using castor3d::Uniform4b = typedef TUniform< UniformType::eVec4b >
Uniform4d
using castor3d::Uniform4d = typedef TUniform< UniformType::eVec4d >
Uniform4f
using castor3d::Uniform4f = typedef TUniform< UniformType::eVec4f >
Uniform4i
using castor3d::Uniform4i = typedef TUniform< UniformType::eVec4i >
Uniform4r
using castor3d::Uniform4r = typedef TUniform< UniformType::eVec4r >
Uniform4ui
using castor3d::Uniform4ui = typedef TUniform< UniformType::eVec4ui >
Uniform4x2b
using castor3d::Uniform4x2b = typedef TUniform< UniformType::eMat4x2b >
Uniform4x2d
using castor3d::Uniform4x2d = typedef TUniform< UniformType::eMat4x2d >
Uniform4x2f
using castor3d::Uniform4x2f = typedef TUniform< UniformType::eMat4x2f >
Uniform4x2i
using castor3d::Uniform4x2i = typedef TUniform< UniformType::eMat4x2i >
Uniform4x2r
using castor3d::Uniform4x2r = typedef TUniform< UniformType::eMat4x2r >
Uniform4x2ui
using castor3d::Uniform4x2ui = typedef TUniform< UniformType::eMat4x2ui >
Uniform4x3b
using castor3d::Uniform4x3b = typedef TUniform< UniformType::eMat4x3b >
Uniform4x3d
using castor3d::Uniform4x3d = typedef TUniform< UniformType::eMat4x3d >
Uniform4x3f
using castor3d::Uniform4x3f = typedef TUniform< UniformType::eMat4x3f >
Uniform4x3i
using castor3d::Uniform4x3i = typedef TUniform< UniformType::eMat4x3i >
Uniform4x3r
using castor3d::Uniform4x3r = typedef TUniform< UniformType::eMat4x3r >
Uniform4x3ui
using castor3d::Uniform4x3ui = typedef TUniform< UniformType::eMat4x3ui >
Uniform4x4b
using castor3d::Uniform4x4b = typedef TUniform< UniformType::eMat4x4b >
Uniform4x4d
using castor3d::Uniform4x4d = typedef TUniform< UniformType::eMat4x4d >
Uniform4x4f
using castor3d::Uniform4x4f = typedef TUniform< UniformType::eMat4x4f >
Uniform4x4i
using castor3d::Uniform4x4i = typedef TUniform< UniformType::eMat4x4i >
Uniform4x4r
using castor3d::Uniform4x4r = typedef TUniform< UniformType::eMat4x4r >
Uniform4x4ui
using castor3d::Uniform4x4ui = typedef TUniform< UniformType::eMat4x4ui >
VertexBufferArray
using castor3d::VertexBufferArray = typedef std::vector< std::reference_wrapper< VertexBuffer > >
VertexPattern
using castor3d::VertexPattern = typedef Pattern< Vertex >
VertexPtrPattern
using castor3d::VertexPtrPattern = typedef Pattern< VertexSPtr >
WeightedBlendPassResult
using castor3d::WeightedBlendPassResult = typedef std::array< TextureUnitUPtr, size_t(WbTexture::eCount) >
The weighted blend pass result.
WindowPtrStrMap
typedef std::map< castor::String, RenderWindowSPtr > castor3d::WindowPtrStrMap
Enumeration Type Documentation
AccessType
enum castor3d::AccessType : uint8_t strong
Access types enumeration.
Author
Sylvain DOREMUS
Version
0.8.0
Date
16/10/2015
Enumerator
eNone
No access.
eRead
read only access type.
eWrite
write only access type.
AnimationState
enum castor3d::AnimationState : uint8_t strong
Animation State Enumerator.
Author
Sylvain DOREMUS
Date
09/02/2010
Enumerator
ePlaying
Playing animation state.
eStopped
Stopped animation state.
ePaused
Paused animation state.
AnimationType
enum castor3d::AnimationType : uint8_t strong
Animation types enumeration.
Author
Sylvain DOREMUS
Version
0.9.0
Date
31/05/2016
Enumerator
eMovable
Scene node animation.
eSkeleton
Skeleton animation.
eMesh
Submesh animation (morphing).
AttachmentPoint
enum castor3d::AttachmentPoint : uint8_t strong
Frame buffer attachment points enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
12/11/2012
Enumerator
eNone
eColour
eDepth
eStencil
eDepthStencil
AttachmentType
enum castor3d::AttachmentType : uint8_t strong
Frame buffer attachment types enumeration.
Author
Sylvain DOREMUS
Version
0.8.0.0
Date
11/10/2015
Enumerator
eTexture
eBuffer
BillboardSize
enum castor3d::BillboardSize strong
Billboard sizing types enumeration.
Author
Sylvain DOREMUS
Version
0.9.0
Date
16/11/2016
Enumerator
eDynamic
Billboards size changes with camera position.
eFixed
Billboards size doesn't change.
BillboardType
enum castor3d::BillboardType strong
Billboard rendering types enumeration.
Author
Sylvain DOREMUS
Version
0.9.0
Date
16/11/2016
Enumerator
eSpherical
Billboards always face the camera.
eCylindrical
Billboards rotate only on Y axis.
BlendMode
enum castor3d::BlendMode : uint8_t strong
Blending modes enumeration.
Author
Sylvain DOREMUS
Enumerator
eNoBlend
Order dependent blending.
eAdditive
Order independent, add the components.
eMultiplicative
Order independent, multiply the components.
eInterpolative
Order dependent, interpolate the components.
eABuffer
Order independent, using A-buffer, not implemented yet.
eDepthPeeling
Order independent, using depth peeling, not implemented yet.
BlendOperand
enum castor3d::BlendOperand : uint8_t strong
Blend operands enumeration.
Author
Sylvain DOREMUS
Enumerator
eZero
eOne
eSrcColour
eInvSrcColour
eDstColour
eInvDstColour
eSrcAlpha
eInvSrcAlpha
eDstAlpha
eInvDstAlpha
eConstant
eInvConstant
eSrcAlphaSaturate
eSrc1Colour
eInvSrc1Colour
eSrc1Alpha
eInvSrc1Alpha
BlendOperation
enum castor3d::BlendOperation : uint8_t strong
Blending operations enumeration.
Author
Sylvain DOREMUS
Enumerator
eAdd
Src2 + Src1.
eSubtract
Src2 - Src1.
eRevSubtract
Src1 - Src2.
eMin
min(Src1, Src2).
eMax
max(Src1, Src2).
eCount
BlendSource
enum castor3d::BlendSource : uint8_t strong
Texture blending sources enumeration.
Author
Sylvain DOREMUS
Enumerator
eTexture
eTexture0
eTexture1
eTexture2
eTexture3
eConstant
eDiffuse
ePrevious
BlendSrcIndex
enum castor3d::BlendSrcIndex : uint8_t strong
Texture blending source indices enumeration.
Author
Sylvain DOREMUS
Enumerator
eIndex0
eIndex1
eIndex2
BorderPosition
enum castor3d::BorderPosition strong
Text wrapping modes, handles the way text is cut when it overflows the overlay width.
Author
Sylvain DOREMUS
Date
28/11/2014
Enumerator
eInternal
The border is outside the overlay.
eMiddle
The border is middle outside and middle inside the overlay.
eExternal
The border is outside the overlay.
BufferAccessNature
enum castor3d::BufferAccessNature : uint32_t strong
Buffer access natures enumeration.
Author
Sylvain DOREMUS
See also
BufferAccessType
Remarks
Made to be combined with BufferAccessType
Enumerator
eDraw
Modified by CPU and used by GPU.
eRead
Modified by GPU and used by CPU.
eCopy
Modified by GPU and used by GPU.
BufferAccessType
enum castor3d::BufferAccessType : uint32_t strong
Buffer access types enumeration.
Author
Sylvain DOREMUS
See also
BufferAccessNature
Remarks
Made to be combined with BufferAccessNature
Enumerator
eStatic
Modified once and used many times.
eDynamic
Modified many times and used many times.
eStream
Modified oncce and used at most a few times.
BufferComponent
enum castor3d::BufferComponent : uint8_t strong
Frame buffer components enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
12/11/2012
Enumerator
eNone
eColour
eDepth
eStencil
BufferType
enum castor3d::BufferType : uint32_t strong
GPU buffers types enumeration.
Author
Sylvain DOREMUS
Version
0.9.0
Date
12/12/2016
Enumerator
eArray
Data array => Vertex buffers.
eElementArray
Element array => Index buffers.
eUniform
Uniform buffer.
eAtomicCounter
Atomic counters buffer.
eShaderStorage
Shader storage buffer.
ChunkType
enum castor3d::ChunkType : uint64_t strong
Binary data chunk types enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
15/04/2013
Enumerator
eUnknown
eCmshFile
eCmshHeader
eCmshVersion
eName
eMesh
eSkeleton
eSkeletonGlobalInverse
eSkeletonBone
eBoneParentName
eBoneOffsetMatrix
eSubmesh
eSubmeshTopology
eSubmeshVertexCount
eSubmeshVertex
eSubmeshBoneCount
eSubmeshBones
eSubmeshMatrixCount
eSubmeshMatrices
eSubmeshFaceCount
eSubmeshFaces
eAnimable
eAnimation
eAnimLength
eSkeletonAnimation
eMeshAnimation
eAnimInterpolator
eAnimationObject
eSkeletonAnimationNode
eSkeletonAnimationBone
eMovingTransform
eKeyframeCount
eKeyframes
eBonesComponent
eMeshAnimationKeyFrame
eMeshAnimationKeyFrameTime
eMeshAnimationKeyFrameSubmeshID
eMeshAnimationKeyFrameBufferSize
eMeshAnimationKeyFrameBufferData
eSkeletonAnimationKeyFrame
eSkeletonAnimationKeyFrameTime
eSkeletonAnimationKeyFrameObjectType
eSkeletonAnimationKeyFrameObjectName
eSkeletonAnimationKeyFrameObjectTransform
ComparisonFunc
enum castor3d::ComparisonFunc : uint8_t strong
Alpha functions enumeration.
Author
Sylvain DOREMUS
Enumerator
eAlways
Always take texture colour
eLess
Takes texture colour if alpha is less than given value
eLEqual
Takes texture colour if alpha is less than or equal to given value
eEqual
Takes texture colour if alpha is equal to given value
eNEqual
Takes texture colour if alpha is different of given value
eGEqual
Takes texture colour if alpha is grater than or equal to given value
eGreater
Takes texture colour if alpha is greater than given value
eNever
Never take texture colour
ComparisonMode
enum castor3d::ComparisonMode : uint8_t strong
Texture comparison modes enumeration.
Author
Sylvain DOREMUS
Enumerator
eNone
eRefToTexture
CSCNSection
enum castor3d::CSCNSection : uint32_t strong
Scene file sections Enum.
The enumeration which defines all the sections and subsections of a scene file
Enumerator
eRoot
eScene
eWindow
eSampler
eCamera
eViewport
eLight
eNode
eObject
eObjectMaterials
eFont
ePanelOverlay
eBorderPanelOverlay
eTextOverlay
eMesh
eSubmesh
eMaterial
ePass
eTextureUnit
eRenderTarget
eShaderProgram
eShaderObject
eShaderUBO
eUBOVariable
eBillboard
eBillboardList
eAnimGroup
eAnimation
eSkybox
eParticleSystem
eParticle
eSsao
eSubsurfaceScattering
eTransmittanceProfile
eHdrConfig
CubeMapFace
enum castor3d::CubeMapFace : uint8_t strong
Cube map faces.
Author
Sylvain DOREMUS
Enumerator
ePositiveX
Face on positive X
eNegativeX
Face on negative X
ePositiveY
Face on positive Y
eNegativeY
Face on negative Y
ePositiveZ
Face on positive Z
eNegativeZ
Face on negative Z
Culling
enum castor3d::Culling : uint8_t strong
Culled faces enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
23/05/2013
Enumerator
eNone
No face culled.
eFront
Front faces are culled.
eBack
Back face are culled.
eFrontAndBack
Back and front faces are culled.
DepthFunc
enum castor3d::DepthFunc : uint8_t strong
Depth functions enumeration.
Author
Sylvain DOREMUS
Version
0.7.0
Date
02/06/2013
Enumerator
eNever
Never passes.
eLess
Passes if the incoming depth value is less than the stored depth value.
eEqual
Passes if the incoming depth value is equal to the stored depth value.
eLEqual
Passes if the incoming depth value is less than or equal to the stored depth value.
eGreater
Passes if the incoming depth value is greater than the stored depth value.
eNEqual
Passes if the incoming depth value is not equal to the stored depth value.
eGEqual
Passes if the incoming depth value is greater than or equal to the stored depth value.
eAlways
Always passes.
DsTexture
enum castor3d::DsTexture : uint8_t strong
Enumerator of textures used in deferred rendering.
Author
Sylvain DOREMUS
Version
0.10.0
Date
08/06/2017
Enumerator
eDepth
eData1
eData2
eData3
eData4
eData5
CASTOR_SCOPED_ENUM_BOUNDS
ElementType
enum castor3d::ElementType : uint8_t strong
Element type enumeration.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
03/01/2011
Enumerator
eFloat
1 float (GLSL float)
eVec2
2 floats (GLSL vec2)
eVec3
3 floats (GLSL vec3)
eVec4
4 floats (GLSL vec4)
eColour
colour (uint32_t)
eInt
1 int (4 bytes each, GLSL int)
eIVec2
2 ints (4 bytes each, GLSL ivec2)
eIVec3
3 ints (4 bytes each, GLSL ivec3)
eIVec4
4 ints (4 bytes each, GLSL ivec4)
eUInt
1 uint (4 bytes each, GLSL uint)
eUIVec2
2 uints (4 bytes each, GLSL uivec2)
eUIVec3
3 uints (4 bytes each, GLSL uivec3)
eUIVec4
4 uints (4 bytes each, GLSL uivec4)
eMat2
2x2 floats (GLSL mat2)
eMat3
3x3 floats (GLSL mat3)
eMat4
4x4 floats (GLSL mat4)
ElementUsage
enum castor3d::ElementUsage : uint32_t strong
Element usage enumeration.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
03/01/2011
Enumerator
eUnknown
Position coords.
ePosition
Position coords.
eNormal
Normal coords.
eTangent
Tangent coords.
eBitangent
Bitangent coords.
eDiffuse
Diffuse colour.
eTexCoords
Texture coordinates.
eBoneIds0
Bone IDs 0.
eBoneIds1
Bone IDs 1.
eBoneWeights0
Bone weights 0.
eBoneWeights1
Bone weights 1.
eTransform
Instantiation matrix.
eMatIndex
Instantiation material index.
EventType
enum castor3d::EventType : uint8_t strong
Frame Event Type enumeration.
Author
Sylvain DOREMUS
Enumerator
ePreRender
This kind of event happens before any render, device context is active (so be fast !!).
eQueueRender
This kind of event happens after the render, before buffers' swap.
ePostRender
This kind of event happens after the buffer' swap.
FillMode
enum castor3d::FillMode : uint8_t strong
Polygon rasterisation modes enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
23/05/2013
Enumerator
ePoint
Polygon vertices that are marked as the start of a boundary edge are drawn as points.
eLine
Boundary edges of the polygon are drawn as line segments.
eSolid
The interior of the polygon is filled.
FogType
enum castor3d::FogType strong
Fog types enumeration.
Author
Sylvain DOREMUS
Version
0.9.0
Date
31/05/2016
Enumerator
eDisabled
No fog.
eLinear
Fog intensity increases linearly with distance to camera.
eExponential
Fog intensity increases exponentially with distance to camera.
eSquaredExponential
Fog intensity increases even more with distance to camera.
FrameBufferMode
enum castor3d::FrameBufferMode : uint8_t strong
Frame buffer binding modes enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
12/11/2012
Enumerator
eConfig
Frame buffer is bound for configuration.
eAutomatic
Frame buffer is bound and FrameBuffer::setDrawBuffers is called automatically.
eManual
Frame buffer is bound and user must call FrameBuffer::SetDrawBuffers if he wants.
FrameBufferTarget
enum castor3d::FrameBufferTarget : uint8_t strong
Frame buffer binding targets enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
12/11/2012
Enumerator
eDraw
Frame buffer is bound as a target for draws.
eRead
Frame buffer is bound as a target for reads.
eBoth
Frame buffer is bound as a target for reads and draws.
FrustumCorner
enum castor3d::FrustumCorner strong
Frustum view planes enumeration.
Author
Sylvain DOREMUS
Date
10/06/2013
Version
0.7.0
Enumerator
eFarLeftBottom
Far left bottom corner.
eFarLeftTop
Far left top corner.
eFarRightTop
Far right top corner.
eFarRightBottom
Far right bottom corner.
eNearLeftBottom
Near left bottom corner.
eNearLeftTop
Near left top corner.
eNearRightTop
Near right top corner.
eNearRightBottom
Near right bottom corner.
FrustumPlane
enum castor3d::FrustumPlane strong
Frustum view planes enumeration.
Author
Sylvain DOREMUS
Date
10/06/2013
Version
0.7.0
Enumerator
eNear
Near plane.
eFar
Far plane.
eLeft
Left plane.
eRight
Right plane.
eTop
Top plane.
eBottom
Bottom plane.
GpuFeature
enum castor3d::GpuFeature : uint32_t strong
All supported GPU feature flags.
Author
Sylvain DOREMUS
Date
04/05/2016
Version
0.9.0
Enumerator
eInstancing
Tells whether or not the selected render API supports instanced draw calls.
eAccumulationBuffer
Tells whether or not the selected render API supports accumulation buffers.
eNonPowerOfTwoTextures
Tells whether or not the selected render API supports non power of two textures.
eStereo
Tells whether or not the selected render API supports stereo.
eConstantsBuffers
Tells whether or not the selected render API supports constants buffers.
eTextureBuffers
Tells whether or not the selected render API supports texture buffers.
eShaderStorageBuffers
Tells whether or not the selected render API supports shader stoarage buffers.
eAtomicCounterBuffers
Tells whether or not the selected render API supports atomic counter buffers.
eTransformFeedback
Tells whether or not the selected render API supports transform feedback.
eImmutableTextureStorage
Tells whether or not the selected render API supports texture immutable storages.
GpuMax
enum castor3d::GpuMax : uint32_t strong
All supported GPU feature flags.
Author
Sylvain DOREMUS
Date
04/05/2016
Version
0.9.0
Enumerator
eShaderStorageBufferBindings
eVertexShaderStorageBlocks
eVertexAtomicCounters
eVertexAttribs
eVertexOutputComponents
eVertexTextureImageUnits
eVertexUniformComponents
eVertexUniformBlocks
eVertexUniformVectors
eVertexCombinedUniformComponents
eGeometryAtomicCounters
eGeometryShaderStorageBlocks
eGeometryInputComponents
eGeometryOutputComponents
eGeometryTextureImageUnits
eGeometryUniformComponents
eGeometryUniformBlocks
eGeometryCombinedUniformComponents
eTessControlAtomicCounters
eTessControlShaderStorageBlocks
eTessEvaluationAtomicCounters
eTessEvaluationShaderStorageBlocks
eComputeAtomicCounters
eComputeAtomicCounterBuffers
eComputeShaderStorageBlocks
eComputeTextureImageUnits
eComputeUniformComponents
eComputeUniformBlocks
eComputeCombinedUniformComponents
eComputeWorkGroupInvocations
eComputeWorkGroupCount
eComputeWorkGroupSize
eFragmentAtomicCounters
eFragmentShaderStorageBlocks
eFragmentInputComponents
eFragmentUniformComponents
eFragmentUniformBlocks
eFragmentUniformVectors
eFragmentCombinedUniformComponents
eCombinedAtomicCounters
eCombinedShaderStorageBlocks
eDebugGroupStackDepth
eLabelLength
eIntegerSamples
eProgramTexelOffset
eServerWaitTimeout
eSampleMaskWords
eSamples
eTexture3DSize
eTextureRectangleSize
eTextureCubeMapSize
eTextureBufferSize
eTextureSize
eTextureImageUnits
eTextureLodBias
eArrayTextureLayers
eClipDistances
eColourTextureSamples
eDepthTextureSamples
eCombinedTextureImageUnits
eCombinedUniformBlocks
eDrawBuffers
eDualSourceDrawBuffers
eElementIndices
eElementVertices
eFramebufferWidth
eFramebufferHeight
eFramebufferLayers
eFramebufferSamples
eRenderbufferSize
eUniformBufferBindings
eUniformBlockSize
eUniformLocations
eVaryingComponents
eVaryingVectors
eVaryingFloats
eViewportWidth
eViewportHeight
eViewports
GpuMin
enum castor3d::GpuMin : uint32_t strong
All supported GPU feature flags.
Author
Sylvain DOREMUS
Date
04/05/2016
Version
0.9.0
Enumerator
eMapBufferAlignment
eProgramTexelOffset
HAlign
enum castor3d::HAlign strong
Horizontal alignments for text overlays.
Author
Sylvain DOREMUS
Date
23/09/2015
Version
0.8.0
Enumerator
eLeft
Aligned on the left.
eCenter
Centered horizontally.
eRight
Aligned on the right.
HandlerEventType
enum castor3d::HandlerEventType : uint8_t strong
Enumeration of supported handler events.
Author
Sylvain DOREMUS
Date
17/04/2016
Version
0.9.0
Enumration des vnements de gestionnaire supportes.
Enumerator
eActivate
Handler activated.
eDeactivate
Handler deactivated.
InterpolationFilter
enum castor3d::InterpolationFilter : uint8_t strong
Texture interpolation filters enumeration.
Author
Sylvain DOREMUS
Enumerator
eMin
eMag
eMip
eCount
InterpolationMode
enum castor3d::InterpolationMode : uint8_t strong
Texture filter interpolation modes enumeration.
Author
Sylvain DOREMUS
Enumerator
eUndefined
eNearest
eLinear
InterpolatorType
enum castor3d::InterpolatorType : uint8_t strong
Interpolation modes enumeration.
Author
Sylvain DOREMUS
Version
0.1
Date
09/02/2010
Enumerator
eNearest
No interpolation.
eLinear
Linear mode.
KeyboardEventType
enum castor3d::KeyboardEventType : uint8_t strong
Enumeration of supported keyboard events.
Author
Sylvain DOREMUS
Date
17/04/2016
Version
0.9.0
Enumration des vnement clavier supports.
Enumerator
ePushed
A key is pushed.
eReleased
A key is released.
eChar
A displayable char key is stroked.
KeyboardKey
enum castor3d::KeyboardKey strong
Keyboard keys enumeration.
Author
Sylvain DOREMUS
Date
17/04/2016
Version
0.9.0
Enumerator
eNone
eBackspace
eTab
eReturn
eEscape
eSpace
eDelete
eStart
eLButton
eRButton
eCancel
eMButton
eClear
eShift
eAlt
eControl
eMenu
ePause
eCapital
eEnd
eHome
eLeft
eUp
eRight
edown
eSelect
ePrint
eExecute
eSnapshot
eInsert
eHelp
eNumpad0
eNumpad1
eNumpad2
eNumpad3
eNumpad4
eNumpad5
eNumpad6
eNumpad7
eNumpad8
eNumpad9
eMultiply
eAdd
eSeparator
eSubtract
eDecimal
eDivide
eF1
eF2
eF3
eF4
eF5
eF6
eF7
eF8
eF9
eF10
eF11
eF12
eF13
eF14
eF15
eF16
eF17
eF18
eF19
eF20
eF21
eF22
eF23
eF24
eNumlock
eScroll
ePageUp
ePageDown
eNumpadSpace
eNumpadTab
eNumpadEnter
eNumpadF1
eNumpadF2
eNumpadF3
eNumpadF4
eNumpadHome
eNumpadLeft
eNumpadUp
eNumpadRight
eNumpadDown
eNumpadPageUp
eNumpadPageDown
eNumpadEnd
eNumpadBegin
eNumpadInsert
eNumpadDelete
eNumpadEqual
eNumpadMultiply
eNumpadAdd
eNumpadSeparator
eNumpadSubtract
eNumpadDecimal
eNumpadDivide
LightType
enum castor3d::LightType : uint8_t strong
Light types enumeration.
Author
Sylvain DOREMUS
Enumerator
eDirectional
Directional light type.
ePoint
Point light type.
eSpot
Spot light type.
MaterialType
enum castor3d::MaterialType strong
Supported material types enumeration.
Author
Sylvain DOREMUS
Version
0.9.0
Date
02/12/2016
Enumerator
eLegacy
Traditional (pre-PBR).
ePbrMetallicRoughness
Metallic/Roughness PBR.
ePbrSpecularGlossiness
Specular/Glossiness PBR.
MemoryBarrier
enum castor3d::MemoryBarrier : uint32_t strong
Supported memory barriers enumeration.
Author
Sylvain DOREMUS
Version
0.8.0
Date
16/03/2016
Enumerator
eVertexBuffer
eIndexBuffer
eUniformBuffer
eAtomicCounterBuffer
eQueryBuffer
eShaderStorageBuffer
eTextureFetch
eTextureUpdate
eFrameBuffer
ePixelBuffer
eAll
MeshType
enum castor3d::MeshType : uint8_t strong
Mesh type enumeration.
Author
Sylvain DOREMUS
Enumerator
eCustom
Custom mesh type => User defined vertex, imported mesh...
eCone
Cone mesh type.
eCylinder
Cylinder mesh type.
eSphere
Rectangular faces sphere mesh type.
eCube
Cube mesh type.
eTorus
Torus mesh type.
ePlane
Plane mesh type.
eIcosahedron
Triangular faces sphere mesh type.
eProjection
Projection mesh type.
MouseButton
enum castor3d::MouseButton strong
Mouse buttons enumeration.
Author
Sylvain DOREMUS
Date
17/04/2016
Version
0.9.0
Enumerator
eLeft
Left mouse button.
eMiddle
Middle mouse button.
eRight
Right mouse button.
MouseEventType
enum castor3d::MouseEventType : uint8_t strong
Enumeration of supported mouse events.
Author
Sylvain DOREMUS
Date
17/04/2016
Version
0.9.0
Enumration des vnement de souris supports.
Enumerator
eMove
The mouse moves.
eEnter
The mouse enters an handler's zone.
eHover
The mouse remains still in an handler's zone during hover time.
eLeave
The mouse leaves an handler's zone.
ePushed
One mouse button is pushed.
eReleased
One mouse button is released.
eWheel
One mouse wheel is rolled.
MovableType
enum castor3d::MovableType : uint8_t strong
Movable object types enumerator.
Author
Sylvain DOREMUS
Version
0.1
Date
09/02/2010
Remarks
There are four movable object types : camera, geometry, light and billboard.
Enumerator
eCamera
eGeometry
eLight
eBillboard
eParticleEmitter
OverlayType
enum castor3d::OverlayType : uint8_t strong
Overlay types enumeration.
Author
Sylvain DOREMUS
Enumerator
ePanel
eBorderPanel
eText
PassFlag
enum castor3d::PassFlag : uint8_t strong
Pass specific flags.
Author
Sylvain DOREMUS
Date
13/09/2017
Version
0.10.0
Enumerator
eAlphaBlending
eAlphaTest
Shader using alpha test.
ePbrMetallicRoughness
Shader for Metallic/Roughness PBR material (if not set, will use legacy material code).
ePbrSpecularGlossiness
Shader for Specular/Glossiness PBR material (if not set, will use legacy material code).
eSubsurfaceScattering
Shader for Subsurface Scattering.
eDistanceBasedTransmittance
Shader using distance based transmittance when computing Subsurface Scattering.
eParallaxOcclusionMapping
Shader using parallax occlusion mapping.
PluginType
enum castor3d::PluginType : uint8_t strong
Plugin types enumeration.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
03/01/2011
Enumerator
eRenderer
Renderer plug-in.
eImporter
Importer plug-in.
eDivider
Mesh Divider plug-in.
eGenerator
Procedural generator.
eTechnique
Render technique plug-in.
eToneMapping
Tone mapping plug-in.
ePostEffect
Post effect plug-in.
eGeneric
Generic plug-in.
eParticle
Particle plug-in.
ProgramFlag
enum castor3d::ProgramFlag : uint16_t strong
Flags to use when looking for an automatically generated program.
Author
Sylvain DOREMUS
Date
20/11/13
Version
0.7.0.0
Enumerator
eInstantiation
Program using instanciation.
eSkinning
Program using skeleton animations.
eBillboards
Program used by billboards.
eMorphing
Program using per-vertex animations.
ePicking
Picking pass program.
eLighting
Shader supporting lighting.
eSpherical
Shader for spherical billboards.
eFixedSize
Shader for fixed size billboards.
eShadowMapDirectional
Shader used to render a shadow map for directional light.
eShadowMapSpot
Shader used to render a shadow map for spot light.
eShadowMapPoint
Shader used to render a shadow map for point light.
eEnvironmentMapping
Shader used to render an environment map.
eDepthPass
Shader for the depth pre-pass.
ProgramStatus
enum castor3d::ProgramStatus : uint8_t strong
Program status enumeration.
Author
Sylvain DOREMUS
Date
22/08/2012
Version
0.7.0.0
Enumerator
eNotLinked
eError
eLinked
QueryInfo
enum castor3d::QueryInfo : uint32_t strong
GPU query supported informations enumeration.
Author
Sylvain DOREMUS
Version
0.8.0
Date
16/03/2016
Enumerator
eResult
eResultAvailable
eResultNoWait
QueryType
enum castor3d::QueryType : uint32_t strong
GPU query supported types enumeration.
Author
Sylvain DOREMUS
Version
0.8.0
Date
16/03/2016
Enumerator
eTimeElapsed
eSamplesPassed
eAnySamplesPassed
ePrimitivesGenerated
eTransformFeedbackPrimitivesWritten
eAnySamplesPassedConservative
eTimestamp
SceneFlag
enum castor3d::SceneFlag : uint16_t strong
Scene flags enumeration.
Author
Sylvain DOREMUS
Version
0.9.0
Date
08/03/2017
Enumerator
eNone
No flag.
eFogLinear
Linear fog.
eFogExponential
Exponential fog.
eFogSquaredExponential
Squared exponential fog.
eShadowFilterPcf
PCF filtering.
ShaderModel
enum castor3d::ShaderModel : uint8_t strong
Enumeration of existing shader models.
Author
Sylvain DOREMUS
Enumerator
eModel1
Vertex shaders.
eModel2
Pixel shaders.
eModel3
Geometry shaders.
eModel4
Tessellation shaders.
eModel5
Compute shaders.
ShaderStatus
enum castor3d::ShaderStatus : uint8_t strong
Shader status enueration.
Author
Sylvain DOREMUS
Date
22/08/2012
Version
0.7.0.0
Enumerator
edontExist
eNotCompiled
eError
eCompiled
ShaderType
enum castor3d::ShaderType : int8_t strong
Shader object types enumeration.
Author
Sylvain DOREMUS
Enumerator
eNone
eVertex
eHull
eDomain
eGeometry
ePixel
eCompute
ShaderTypeFlag
enum castor3d::ShaderTypeFlag : uint8_t strong
Shader object types masks.
Author
Sylvain DOREMUS
Enumerator
eVertex
eHull
eDomain
eGeometry
ePixel
eCompute
ShadowType
enum castor3d::ShadowType strong
Shadow filter types enumeration.
Author
Sylvain DOREMUS
Version
0.9.0
Date
31/05/2016
Enumerator
eNone
No shadows at all.
ePCF
PCF filtering.
SkeletonAnimationObjectType
enum castor3d::SkeletonAnimationObjectType : uint8_t strong
Class which represents the moving things.
Author
Sylvain DOREMUS
Version
0.1
Date
09/02/2010
Remarks
Manages translation, scaling, rotation of the thing.
Enumerator
eNode
Node objects.
eBone
Bone objects.
StencilFunc
enum castor3d::StencilFunc : uint8_t strong
Stencil functions enumeration.
Author
Sylvain DOREMUS
Version
0.7.0
Date
02/06/2013
Enumerator
eNever
Never passes.
eLess
Passes if the incoming stencil value is less than the stored stencil value.
eEqual
Passes if the incoming stencil value is equal to the stored stencil value.
eLEqual
Passes if the incoming stencil value is less than or equal to the stored stencil value.
eGreater
Passes if the incoming stencil value is greater than the stored stencil value.
eNEqual
Passes if the incoming stencil value is not equal to the stored stencil value.
eGEqual
Passes if the incoming stencil value is greater than or equal to the stored stencil value.
eAlways
Always passes.
StencilOp
enum castor3d::StencilOp : uint8_t strong
Stencil functions enumeration.
Author
Sylvain DOREMUS
Version
0.7.0
Date
02/06/2013
Enumerator
eKeep
Keeps the current value.
eZero
sets the stencil buffer value to 0.
eReplace
sets the stencil buffer value by the one given
eIncrement
Increments the current stencil buffer value. Clamps to the maximum representable unsigned value.
eIncrWrap
Increments the current stencil buffer value. Wraps stencil buffer value to zero when incrementing the maximum representable unsigned value.
eDecrement
Decrements the current stencil buffer value. Clamps to 0.
eDecrWrap
Decrements the current stencil buffer value. Wraps stencil buffer value to the maximum representable unsigned value when decrementing a stencil buffer value of zero.
eInvert
Bitwise inverts the current stencil buffer value.
TargetType
enum castor3d::TargetType : uint8_t strong
RenderTarget supported types.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
19/10/2011
Enumerator
eWindow
eTexture
TextLineSpacingMode
enum castor3d::TextLineSpacingMode strong
Text line spacing modes, handles the way lines are spaced, which each other, inside one TextOverlay.
Author
Sylvain DOREMUS
Date
16/04/2016
Enumerator
eOwnHeight
The height of each line is its own height.
eMaxLineHeight
The height of the lines is the maximum height between them.
eMaxFontHeight
The height of the lines is the maximum height from the font's characters.
TextTexturingMode
enum castor3d::TextTexturingMode strong
Text texturing modes, handles the way textures are appied to text overlays.
Author
Sylvain DOREMUS
Date
26/03/2016
Enumerator
eLetter
The texture is repeated on each character of the text.
eText
The texture is applied on the whole text.
TextureBlendFunc
enum castor3d::TextureBlendFunc : uint8_t strong
RGB blending functions enumeration.
Author
Sylvain DOREMUS
Enumerator
eNoBlend
No blend
eFirstArg
Arg0
eAdd
Arg0 + Arg1
eAddSigned
Arg0 + Arg1 - 0.5
eModulate
Arg0 x Arg1
eInterpolate
Arg0 Arg2 + Arg1 (1 - Arg2)
eSubtract
Arg0 - Arg1
TextureChannel
enum castor3d::TextureChannel : uint16_t strong
Texture channels enumeration.
Author
Sylvain DOREMUS
Enumerator
eUndefined
Undefined channel.
eDiffuse
Diffuse map
eAlbedo
Diffuse map
eNormal
Normal map
eOpacity
Opacity map
eSpecular
Specular map
eRoughness
Specular map
eHeight
Height map
eGloss
Gloss map
eMetallic
Specular map
eEmissive
Emissive map
eReflection
Reflection map
eRefraction
Refraction map
eAmbientOcclusion
Ambient occlusion map
eTransmittance
Light transmittance map
eAll
Mask for all the texture channels
eText
Not really a texture channel (it is out of TextureChannel::eAll), used to tell we want text overlay shader source
TextureStorageType
enum castor3d::TextureStorageType : uint8_t strong
Texture dimensions enumeration.
Author
Sylvain DOREMUS
Enumerator
eBuffer
1 dimension texture buffer, used to store data.
eOneDimension
1 dimension textures.
eOneDimensionArray
1 dimension texture arrays.
eTwoDimensions
2 dimensions textures.
eTwoDimensionsArray
2 dimensions texture arrays.
eTwoDimensionsMS
2 dimensions textures with multisample support.
eThreeDimensions
3 dimensions textures.
eCubeMap
Cube map.
eCubeMapArray
Cube map array.
TextureType
enum castor3d::TextureType : uint8_t strong
Texture dimensions enumeration.
Author
Sylvain DOREMUS
Enumerator
eBuffer
1 dimension texture buffer, used to store data.
eOneDimension
1 dimension textures => one coordinate => U mapping
eOneDimensionArray
1 dimension textures array => one coordinate => U mapping
eTwoDimensions
2 dimensions textures => two coordinates => UV mapping
eTwoDimensionsArray
2 dimensions textures array => two coordinates => UV mapping
eTwoDimensionsMS
2 dimensions textures with multisample support => two coordinates => UV mapping
eTwoDimensionsMSArray
2 dimensions textures array with multisample support => two coordinates => UV mapping
eThreeDimensions
3 dimensions textures => three coordinates => UVW mapping
eCube
Cube texture.
eCubeArray
Cube textures array.
TextureUVW
enum castor3d::TextureUVW : uint8_t strong
Texture UVW enumeration.
Author
Sylvain DOREMUS
Enumerator
eU
eV
eW
TextWrappingMode
enum castor3d::TextWrappingMode strong
Text wrapping modes, handles the way text is cut when it overflows the overlay width.
Author
Sylvain DOREMUS
Date
28/11/2014
Enumerator
eNone
The text is cut.
eBreak
The text jumps to next line.
eBreakWords
The text jumps to next line without cutting words.
Topology
enum castor3d::Topology : uint8_t strong
Primitive draw types enumeration.
Author
Sylvain DOREMUS
Enumerator
ePoints
Display textured points.
eLines
Display textured edges.
eLineLoop
Display textured edge loops.
eLineStrip
Display textured edge strips.
eTriangles
Display textured triangles.
eTriangleStrips
Display triangle strips.
eTriangleFan
Display triangle fan.
UniformType
enum castor3d::UniformType : uint8_t strong
Supported variables full type enumeration.
Author
Sylvain DOREMUS
Enumerator
eBool
eInt
eUInt
eFloat
eDouble
eSampler
eVec2b
eVec3b
eVec4b
eVec2i
eVec3i
eVec4i
eVec2ui
eVec3ui
eVec4ui
eVec2f
eVec3f
eVec4f
eVec2d
eVec3d
eVec4d
eMat2x2b
eMat2x3b
eMat2x4b
eMat3x2b
eMat3x3b
eMat3x4b
eMat4x2b
eMat4x3b
eMat4x4b
eMat2x2i
eMat2x3i
eMat2x4i
eMat3x2i
eMat3x3i
eMat3x4i
eMat4x2i
eMat4x3i
eMat4x4i
eMat2x2ui
eMat2x3ui
eMat2x4ui
eMat3x2ui
eMat3x3ui
eMat3x4ui
eMat4x2ui
eMat4x3ui
eMat4x4ui
eMat2x2f
eMat2x3f
eMat2x4f
eMat3x2f
eMat3x3f
eMat3x4f
eMat4x2f
eMat4x3f
eMat4x4f
eMat2x2d
eMat2x3d
eMat2x4d
eMat3x2d
eMat3x3d
eMat3x4d
eMat4x2d
eMat4x3d
eMat4x4d
eReal
eVec2r
eVec3r
eVec4r
eMat2x2r
eMat2x3r
eMat2x4r
eMat3x2r
eMat3x3r
eMat3x4r
eMat4x2r
eMat4x3r
eMat4x4r
UserInputEventType
enum castor3d::UserInputEventType strong
Supported events types enumeration.
Author
Sylvain DOREMUS
Date
17/04/2016
Version
0.9.0
Enumerator
eMouse
Mouse event type.
eKeyboard
Keyboard event type.
eHandler
Keyboard event type.
VAlign
enum castor3d::VAlign strong
Vertical alignments for text overlays.
Author
Sylvain DOREMUS
Date
23/09/2015
Version
0.8.0
Enumerator
eTop
Aligned on the top.
eCenter
Centered vertically.
eBottom
Aligned on the bottom.
VariableType
enum castor3d::VariableType : uint8_t strong
Supported variables dimensions enumeration.
Author
Sylvain DOREMUS
Enumerator
eOne
One variable.
eVec1
1 variable array.
eVec2
2 variables array.
eVec3
3 variables array.
eVec4
4 variables array.
eMat1
1x1 matrix.
eMat2x2
2x2 matrix.
eMat2x3
2x3 matrix.
eMat2x4
2x4 matrix.
eMat3x2
3x2 matrix.
eMat3x3
3x3 matrix.
eMat3x4
3x4 matrix.
eMat4x2
4x2 matrix.
eMat4x3
4x3 matrix.
eMat4x4
4x4 matrix.
ViewportType
enum castor3d::ViewportType : uint8_t strong
The viewport projection types enumeration.
Author
Sylvain DOREMUS
Enumerator
eOrtho
ePerspective
eFrustum
WbTexture
enum castor3d::WbTexture : uint8_t strong
Enumerator of textures used in weighted blend OIT.
Author
Sylvain DOREMUS
Version
0.10.0
Date
08/06/2017
Enumerator
eDepth
eAccumulation
eRevealage
CASTOR_SCOPED_ENUM_BOUNDS
WindowBuffer
enum castor3d::WindowBuffer : uint8_t strong
Frame buffer components enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
12/11/2012
Enumerator
eNone
eFrontLeft
eFrontRight
eBackLeft
eBackRight
eFront
eBack
eLeft
eRight
eFrontAndBack
WrapMode
enum castor3d::WrapMode : uint8_t strong
Texture wrap modes enumeration.
Author
Sylvain DOREMUS
Enumerator
eRepeat
eMirroredRepeat
eClampToBorder
eClampToEdge
WritingMask
enum castor3d::WritingMask : uint8_t strong
Wrinting masks enumeration.
Author
Sylvain DOREMUS
Version
0.7.0
Date
02/06/2013
Enumerator
eZero
Writing disabled.
eAll
Writing enabled.
Function Documentation
DECLARE_ARRAY() [1/2]
castor3d::DECLARE_ARRAY (PluginStrMap , PluginType::eCount , PluginStrMap)
DECLARE_ARRAY() [2/2]
castor3d::DECLARE_ARRAY (DynamicLibraryPtrPathMap , PluginType::eCount , DynamicLibraryPtrPathMap)
DECLARE_LIST() [1/6]
castor3d::DECLARE_LIST (VertexSPtr , VertexPtr)
Vertex pointer list.
DECLARE_LIST() [2/6]
castor3d::DECLARE_LIST (PushUniformSPtr , PushUniform)
DECLARE_LIST() [3/6]
castor3d::DECLARE_LIST (UniformSPtr , Uniform)
DECLARE_LIST() [4/6]
castor3d::DECLARE_LIST (UniformBufferSPtr , UniformBufferPtr)
DECLARE_LIST() [5/6]
castor3d::DECLARE_LIST (ShaderStorageBufferSPtr , ShaderStorageBufferPtr)
DECLARE_LIST() [6/6]
castor3d::DECLARE_LIST (AtomicCounterBufferSPtr , AtomicCounterBufferPtr)
DECLARE_MAP() [1/50]
castor3d::DECLARE_MAP (castor::String , CameraSPtr , CameraPtrStr)
Camera pointer map, sorted by name.
DECLARE_MAP() [2/50]
castor3d::DECLARE_MAP (castor::String , LightSPtr , LightPtrStr)
Map of lights, sorted by name.
DECLARE_MAP() [3/50]
castor3d::DECLARE_MAP (int , LightSPtr , LightPtrInt)
Map of lights, sorted by index.
DECLARE_MAP() [4/50]
castor3d::DECLARE_MAP (RenderPipelineRPtr , StaticRenderNodeArray , StaticRenderNodesByPipeline)
DECLARE_MAP() [5/50]
castor3d::DECLARE_MAP (RenderPipelineRPtr , SkinningRenderNodeArray , SkinningRenderNodesByPipeline)
DECLARE_MAP() [6/50]
castor3d::DECLARE_MAP (RenderPipelineRPtr , MorphingRenderNodeArray , MorphingRenderNodesByPipeline)
DECLARE_MAP() [7/50]
castor3d::DECLARE_MAP (RenderPipelineRPtr , BillboardRenderNodeArray , BillboardRenderNodesByPipeline)
DECLARE_MAP() [8/50]
castor3d::DECLARE_MAP (SubmeshRPtr , StaticRenderNodeArray , SubmeshStaticRenderNodes)
DECLARE_MAP() [9/50]
castor3d::DECLARE_MAP (SubmeshRPtr , SkinningRenderNodeArray , SubmeshSkinningRenderNodes)
DECLARE_MAP() [10/50]
castor3d::DECLARE_MAP (RenderPipelineRPtr , SubmeshStaticRenderNodesByPassMap , SubmeshStaticRenderNodesByPipeline)
DECLARE_MAP() [11/50]
castor3d::DECLARE_MAP (RenderPipelineRPtr , SubmeshSkinninRenderNodesByPassMap , SubmeshSkinningRenderNodesByPipeline)
DECLARE_MAP() [12/50]
castor3d::DECLARE_MAP (castor::String , MeshSPtr , MeshPtrStr)
Mesh pointer array.
DECLARE_MAP() [13/50]
castor3d::DECLARE_MAP (castor::String , MovableObjectSPtr , MovableObjectPtrStr)
MovableObject pointer map, sorted by name.
DECLARE_MAP() [14/50]
castor3d::DECLARE_MAP (castor::String , GeometrySPtr , GeometryPtrStr)
Geometry pointer map, sorted by name.
DECLARE_MAP() [15/50]
castor3d::DECLARE_MAP (uint32_t , int , IntUInt)
DECLARE_MAP() [16/50]
castor3d::DECLARE_MAP (castor::String , SubmeshSPtr , SubmeshPtrStr)
DECLARE_MAP() [17/50]
castor3d::DECLARE_MAP (castor::String , int , IntStr)
DECLARE_MAP() [18/50]
castor3d::DECLARE_MAP (castor::String , BoneSPtr , BonePtrStr)
Bone pointer map sorted by name.
DECLARE_MAP() [19/50]
castor3d::DECLARE_MAP (castor::String , SubmeshComponentSPtr , SubmeshComponentStr)
DECLARE_MAP() [20/50]
castor3d::DECLARE_MAP (castor::String , AnimationSPtr , AnimationPtrStr)
Animation pointer map, sorted by name.
DECLARE_MAP() [21/50]
castor3d::DECLARE_MAP (castor::String , SkeletonAnimationObjectSPtr , SkeletonAnimationObjectPtrStr)
SkeletonAnimationObject pointer map, sorted by name.
DECLARE_MAP() [22/50]
castor3d::DECLARE_MAP (castor::String , OverlaySPtr , OverlayPtrStr)
DECLARE_MAP() [23/50]
castor3d::DECLARE_MAP (castor::String , SceneSPtr , ScenePtrStr)
Scene pointer map, sorted by name.
DECLARE_MAP() [24/50]
castor3d::DECLARE_MAP (castor::String , SceneNodeSPtr , SceneNodePtrStr)
SceneNode pointer map, sorted by name.
DECLARE_MAP() [25/50]
castor3d::DECLARE_MAP (castor::String , AnimatedObjectGroupSPtr , AnimatedObjectGroupPtrStr)
AnimatedObjectGroup pointer map, sorted by name.
DECLARE_MAP() [26/50]
castor3d::DECLARE_MAP (castor::String , AnimatedObjectSPtr , AnimatedObjectPtrStr)
AnimatedObject pointer map, sorted by name.
DECLARE_MAP() [27/50]
castor3d::DECLARE_MAP (castor::String , SkeletonAnimationInstanceObjectSPtr , SkeletonAnimationInstanceObjectPtrStr)
MovingObject pointer map, sorted by name.
DECLARE_MAP() [28/50]
castor3d::DECLARE_MAP (uint32_t , MeshAnimationInstanceSubmesh , MeshAnimationInstanceSubmesh)
MeshAnimationInstanceSubmesh map, sorted by submesh ID.
DECLARE_MAP() [29/50]
castor3d::DECLARE_MAP (castor::String , AnimationInstanceUPtr , AnimationInstancePtrStr)
Animation pointer map, sorted by name.
DECLARE_MAP() [30/50]
castor3d::DECLARE_MAP (castor::String , MaterialSPtr , MaterialPtrStr)
Material pointer map, sorted by name.
DECLARE_MAP() [31/50]
castor3d::DECLARE_MAP (uint32_t , MaterialSPtr , MaterialPtrUInt)
Material pointer map.
DECLARE_MAP() [32/50]
castor3d::DECLARE_MAP (RenderWindow * , ContextSPtr , ContextPtr)
DECLARE_MAP() [33/50]
castor3d::DECLARE_MAP (std::thread::id , ContextPtrMap , ContextPtrMapId)
DECLARE_MAP() [34/50]
castor3d::DECLARE_MAP (castor::String , FrameListenerSPtr , FrameListenerPtrStr)
FrameListener pointer map, sorted by name.
DECLARE_MAP() [35/50]
castor3d::DECLARE_MAP (uint32_t , RenderWindowSPtr , RenderWindow)
RenderWindow pointer map, sorted by index.
DECLARE_MAP() [36/50]
castor3d::DECLARE_MAP (castor::String , PluginSPtr , PluginStr)
Plugin map, sorted by name.
DECLARE_MAP() [37/50]
castor3d::DECLARE_MAP (int , castor::String , StrInt)
DECLARE_MAP() [38/50]
castor3d::DECLARE_MAP (castor::String , RendererPluginSPtr , RendererPtr)
DECLARE_MAP() [39/50]
castor3d::DECLARE_MAP (castor::Path , castor::DynamicLibrarySPtr , DynamicLibraryPtrPath)
DECLARE_MAP() [40/50]
castor3d::DECLARE_MAP (castor::Path , PluginType , PluginTypePath)
DECLARE_MAP() [41/50]
castor3d::DECLARE_MAP (castor::String , BillboardListSPtr , BillboardListStr)
DECLARE_MAP() [42/50]
castor3d::DECLARE_MAP (castor::String , PushUniformWPtr , PushUniform)
DECLARE_MAP() [43/50]
castor3d::DECLARE_MAP (castor::String , UniformWPtr , Uniform)
DECLARE_MAP() [44/50]
castor3d::DECLARE_MAP (ShaderProgramRPtr , UniformBufferBindingUPtr , UniformBufferBinding)
DECLARE_MAP() [45/50]
castor3d::DECLARE_MAP (castor::String , UniformBufferWPtr , UniformBufferPtrStr)
DECLARE_MAP() [46/50]
castor3d::DECLARE_MAP (castor::String , ShaderStorageBufferWPtr , ShaderStorageBufferPtrStr)
DECLARE_MAP() [47/50]
castor3d::DECLARE_MAP (castor::String , AtomicCounterBufferWPtr , AtomicCounterBufferPtrStr)
DECLARE_MAP() [48/50]
castor3d::DECLARE_MAP (ShaderType , UniformBufferWPtr , UniformBufferPtrShader)
DECLARE_MAP() [49/50]
castor3d::DECLARE_MAP (ShaderType , ShaderStorageBufferWPtr , ShaderStorageBufferPtrShader)
DECLARE_MAP() [50/50]
castor3d::DECLARE_MAP (ShaderType , AtomicCounterBufferWPtr , AtomicCounterBufferPtrShader)
DECLARE_MULTIMAP() [1/4]
castor3d::DECLARE_MULTIMAP (double , StaticRenderNode , StaticRenderNodeByDistance)
DECLARE_MULTIMAP() [2/4]
castor3d::DECLARE_MULTIMAP (double , SkinningRenderNode , SkinningRenderNodeByDistance)
DECLARE_MULTIMAP() [3/4]
castor3d::DECLARE_MULTIMAP (double , MorphingRenderNode , MorphingRenderNodeByDistance)
DECLARE_MULTIMAP() [4/4]
castor3d::DECLARE_MULTIMAP (double , BillboardRenderNode , BillboardRenderNodeByDistance)
DECLARE_SMART_PTR() [1/179]
castor3d::DECLARE_SMART_PTR (Camera)
DECLARE_SMART_PTR() [2/179]
castor3d::DECLARE_SMART_PTR (Viewport)
DECLARE_SMART_PTR() [3/179]
castor3d::DECLARE_SMART_PTR (IViewportImpl)
DECLARE_SMART_PTR() [4/179]
castor3d::DECLARE_SMART_PTR (Ray)
DECLARE_SMART_PTR() [5/179]
castor3d::DECLARE_SMART_PTR (Light)
DECLARE_SMART_PTR() [6/179]
castor3d::DECLARE_SMART_PTR (LightCategory)
DECLARE_SMART_PTR() [7/179]
castor3d::DECLARE_SMART_PTR (DirectionalLight)
DECLARE_SMART_PTR() [8/179]
castor3d::DECLARE_SMART_PTR (PointLight)
DECLARE_SMART_PTR() [9/179]
castor3d::DECLARE_SMART_PTR (SpotLight)
DECLARE_SMART_PTR() [10/179]
castor3d::DECLARE_SMART_PTR (LightFactory)
DECLARE_SMART_PTR() [11/179]
castor3d::DECLARE_SMART_PTR (Vertex)
DECLARE_SMART_PTR() [12/179]
castor3d::DECLARE_SMART_PTR (BufferElementGroup)
DECLARE_SMART_PTR() [13/179]
castor3d::DECLARE_SMART_PTR (Importer)
DECLARE_SMART_PTR() [14/179]
castor3d::DECLARE_SMART_PTR (VertexPattern)
DECLARE_SMART_PTR() [15/179]
castor3d::DECLARE_SMART_PTR (Point3rPattern)
DECLARE_SMART_PTR() [16/179]
castor3d::DECLARE_SMART_PTR (VertexPtrPattern)
DECLARE_SMART_PTR() [17/179]
castor3d::DECLARE_SMART_PTR (Face)
DECLARE_SMART_PTR() [18/179]
castor3d::DECLARE_SMART_PTR (Graph)
DECLARE_SMART_PTR() [19/179]
castor3d::DECLARE_SMART_PTR (Mesh)
DECLARE_SMART_PTR() [20/179]
castor3d::DECLARE_SMART_PTR (MeshGenerator)
DECLARE_SMART_PTR() [21/179]
castor3d::DECLARE_SMART_PTR (Submesh)
DECLARE_SMART_PTR() [22/179]
castor3d::DECLARE_SMART_PTR (SubmeshComponent)
DECLARE_SMART_PTR() [23/179]
castor3d::DECLARE_SMART_PTR (InstantiationComponent)
DECLARE_SMART_PTR() [24/179]
castor3d::DECLARE_SMART_PTR (BonesInstantiationComponent)
DECLARE_SMART_PTR() [25/179]
castor3d::DECLARE_SMART_PTR (IndexMapping)
DECLARE_SMART_PTR() [26/179]
castor3d::DECLARE_SMART_PTR (Cone)
DECLARE_SMART_PTR() [27/179]
castor3d::DECLARE_SMART_PTR (Cylinder)
DECLARE_SMART_PTR() [28/179]
castor3d::DECLARE_SMART_PTR (Icosahedron)
DECLARE_SMART_PTR() [29/179]
castor3d::DECLARE_SMART_PTR (Cube)
DECLARE_SMART_PTR() [30/179]
castor3d::DECLARE_SMART_PTR (Plane)
DECLARE_SMART_PTR() [31/179]
castor3d::DECLARE_SMART_PTR (Projection)
DECLARE_SMART_PTR() [32/179]
castor3d::DECLARE_SMART_PTR (Sphere)
DECLARE_SMART_PTR() [33/179]
castor3d::DECLARE_SMART_PTR (Torus)
DECLARE_SMART_PTR() [34/179]
castor3d::DECLARE_SMART_PTR (Geometry)
DECLARE_SMART_PTR() [35/179]
castor3d::DECLARE_SMART_PTR (MovableObject)
DECLARE_SMART_PTR() [36/179]
castor3d::DECLARE_SMART_PTR (Subdivider)
DECLARE_SMART_PTR() [37/179]
castor3d::DECLARE_SMART_PTR (FaceGroup)
DECLARE_SMART_PTR() [38/179]
castor3d::DECLARE_SMART_PTR (Bone)
DECLARE_SMART_PTR() [39/179]
castor3d::DECLARE_SMART_PTR (Skeleton)
DECLARE_SMART_PTR() [40/179]
castor3d::DECLARE_SMART_PTR (BonedVertex)
DECLARE_SMART_PTR() [41/179]
castor3d::DECLARE_SMART_PTR (MeshFactory)
DECLARE_SMART_PTR() [42/179]
castor3d::DECLARE_SMART_PTR (GeometryCache)
DECLARE_SMART_PTR() [43/179]
castor3d::DECLARE_SMART_PTR (Animation)
DECLARE_SMART_PTR() [44/179]
castor3d::DECLARE_SMART_PTR (AnimationKeyFrame)
DECLARE_SMART_PTR() [45/179]
castor3d::DECLARE_SMART_PTR (SkeletonAnimation)
DECLARE_SMART_PTR() [46/179]
castor3d::DECLARE_SMART_PTR (SkeletonAnimationKeyFrame)
DECLARE_SMART_PTR() [47/179]
castor3d::DECLARE_SMART_PTR (SkeletonAnimationObject)
DECLARE_SMART_PTR() [48/179]
castor3d::DECLARE_SMART_PTR (SkeletonAnimationBone)
DECLARE_SMART_PTR() [49/179]
castor3d::DECLARE_SMART_PTR (SkeletonAnimationNode)
DECLARE_SMART_PTR() [50/179]
castor3d::DECLARE_SMART_PTR (MeshAnimation)
DECLARE_SMART_PTR() [51/179]
castor3d::DECLARE_SMART_PTR (MeshAnimationKeyFrame)
DECLARE_SMART_PTR() [52/179]
castor3d::DECLARE_SMART_PTR (MeshAnimationSubmesh)
DECLARE_SMART_PTR() [53/179]
castor3d::DECLARE_SMART_PTR (PluginCache)
DECLARE_SMART_PTR() [54/179]
castor3d::DECLARE_SMART_PTR (Animable)
DECLARE_SMART_PTR() [55/179]
castor3d::DECLARE_SMART_PTR (SceneNodeCache)
DECLARE_SMART_PTR() [56/179]
castor3d::DECLARE_SMART_PTR (OverlayFactory)
DECLARE_SMART_PTR() [57/179]
castor3d::DECLARE_SMART_PTR (OverlayRenderer)
DECLARE_SMART_PTR() [58/179]
castor3d::DECLARE_SMART_PTR (FontTexture)
DECLARE_SMART_PTR() [59/179]
castor3d::DECLARE_SMART_PTR (Overlay)
DECLARE_SMART_PTR() [60/179]
castor3d::DECLARE_SMART_PTR (OverlayCategory)
DECLARE_SMART_PTR() [61/179]
castor3d::DECLARE_SMART_PTR (PanelOverlay)
DECLARE_SMART_PTR() [62/179]
castor3d::DECLARE_SMART_PTR (BorderPanelOverlay)
DECLARE_SMART_PTR() [63/179]
castor3d::DECLARE_SMART_PTR (TextOverlay)
DECLARE_SMART_PTR() [64/179]
castor3d::DECLARE_SMART_PTR (SceneNode)
DECLARE_SMART_PTR() [65/179]
castor3d::DECLARE_SMART_PTR (Scene)
DECLARE_SMART_PTR() [66/179]
castor3d::DECLARE_SMART_PTR (SceneFileContext)
DECLARE_SMART_PTR() [67/179]
castor3d::DECLARE_SMART_PTR (SceneFileParser)
DECLARE_SMART_PTR() [68/179]
castor3d::DECLARE_SMART_PTR (Skybox)
DECLARE_SMART_PTR() [69/179]
castor3d::DECLARE_SMART_PTR (ParticleSystem)
DECLARE_SMART_PTR() [70/179]
castor3d::DECLARE_SMART_PTR (ParticleSystemImpl)
DECLARE_SMART_PTR() [71/179]
castor3d::DECLARE_SMART_PTR (CpuParticleSystem)
DECLARE_SMART_PTR() [72/179]
castor3d::DECLARE_SMART_PTR (TransformFeedbackParticleSystem)
DECLARE_SMART_PTR() [73/179]
castor3d::DECLARE_SMART_PTR (ComputeParticleSystem)
DECLARE_SMART_PTR() [74/179]
castor3d::DECLARE_SMART_PTR (AnimatedObject)
DECLARE_SMART_PTR() [75/179]
castor3d::DECLARE_SMART_PTR (AnimatedObjectGroup)
DECLARE_SMART_PTR() [76/179]
castor3d::DECLARE_SMART_PTR (AnimatedSkeleton)
DECLARE_SMART_PTR() [77/179]
castor3d::DECLARE_SMART_PTR (AnimatedMesh)
DECLARE_SMART_PTR() [78/179]
castor3d::DECLARE_SMART_PTR (AnimationInstance)
DECLARE_SMART_PTR() [79/179]
castor3d::DECLARE_SMART_PTR (SkeletonAnimationInstance)
DECLARE_SMART_PTR() [80/179]
castor3d::DECLARE_SMART_PTR (SkeletonAnimationInstanceObject)
DECLARE_SMART_PTR() [81/179]
castor3d::DECLARE_SMART_PTR (SkeletonAnimationInstanceNode)
DECLARE_SMART_PTR() [82/179]
castor3d::DECLARE_SMART_PTR (SkeletonAnimationInstanceBone)
DECLARE_SMART_PTR() [83/179]
castor3d::DECLARE_SMART_PTR (MeshAnimationInstance)
DECLARE_SMART_PTR() [84/179]
castor3d::DECLARE_SMART_PTR (BillboardBase)
DECLARE_SMART_PTR() [85/179]
castor3d::DECLARE_SMART_PTR (BillboardList)
DECLARE_SMART_PTR() [86/179]
castor3d::DECLARE_SMART_PTR (MaterialCache)
DECLARE_SMART_PTR() [87/179]
castor3d::DECLARE_SMART_PTR (LightCache)
DECLARE_SMART_PTR() [88/179]
castor3d::DECLARE_SMART_PTR (EventHandler)
DECLARE_SMART_PTR() [89/179]
castor3d::DECLARE_SMART_PTR (UserInputEvent)
DECLARE_SMART_PTR() [90/179]
castor3d::DECLARE_SMART_PTR (KeyboardEvent)
DECLARE_SMART_PTR() [91/179]
castor3d::DECLARE_SMART_PTR (MouseEvent)
DECLARE_SMART_PTR() [92/179]
castor3d::DECLARE_SMART_PTR (HandlerEvent)
DECLARE_SMART_PTR() [93/179]
castor3d::DECLARE_SMART_PTR (UserInputListener)
DECLARE_SMART_PTR() [94/179]
castor3d::DECLARE_SMART_PTR (OverlayCache)
DECLARE_SMART_PTR() [95/179]
castor3d::DECLARE_SMART_PTR (Uniform1b)
DECLARE_SMART_PTR() [96/179]
castor3d::DECLARE_SMART_PTR (RenderBuffer)
DECLARE_SMART_PTR() [97/179]
castor3d::DECLARE_SMART_PTR (ColourRenderBuffer)
DECLARE_SMART_PTR() [98/179]
castor3d::DECLARE_SMART_PTR (DepthStencilRenderBuffer)
DECLARE_SMART_PTR() [99/179]
castor3d::DECLARE_SMART_PTR (FrameBufferAttachment)
DECLARE_SMART_PTR() [100/179]
castor3d::DECLARE_SMART_PTR (RenderBufferAttachment)
DECLARE_SMART_PTR() [101/179]
castor3d::DECLARE_SMART_PTR (TextureAttachment)
DECLARE_SMART_PTR() [102/179]
castor3d::DECLARE_SMART_PTR (TextureImage)
DECLARE_SMART_PTR() [103/179]
castor3d::DECLARE_SMART_PTR (FrameBuffer)
DECLARE_SMART_PTR() [104/179]
castor3d::DECLARE_SMART_PTR (TextureLayout)
DECLARE_SMART_PTR() [105/179]
castor3d::DECLARE_SMART_PTR (BackBuffers)
DECLARE_SMART_PTR() [106/179]
castor3d::DECLARE_SMART_PTR (TextureStorage)
DECLARE_SMART_PTR() [107/179]
castor3d::DECLARE_SMART_PTR (Engine)
DECLARE_SMART_PTR() [108/179]
castor3d::DECLARE_SMART_PTR (TextureUnit)
DECLARE_SMART_PTR() [109/179]
castor3d::DECLARE_SMART_PTR (Plugin)
DECLARE_SMART_PTR() [110/179]
castor3d::DECLARE_SMART_PTR (Material)
DECLARE_SMART_PTR() [111/179]
castor3d::DECLARE_SMART_PTR (RendererPlugin)
DECLARE_SMART_PTR() [112/179]
castor3d::DECLARE_SMART_PTR (Pass)
DECLARE_SMART_PTR() [113/179]
castor3d::DECLARE_SMART_PTR (ImporterPlugin)
DECLARE_SMART_PTR() [114/179]
castor3d::DECLARE_SMART_PTR (LegacyPass)
DECLARE_SMART_PTR() [115/179]
castor3d::DECLARE_SMART_PTR (DividerPlugin)
DECLARE_SMART_PTR() [116/179]
castor3d::DECLARE_SMART_PTR (MetallicRoughnessPbrPass)
DECLARE_SMART_PTR() [117/179]
castor3d::DECLARE_SMART_PTR (SpecularGlossinessPbrPass)
DECLARE_SMART_PTR() [118/179]
castor3d::DECLARE_SMART_PTR (GenericPlugin)
DECLARE_SMART_PTR() [119/179]
castor3d::DECLARE_SMART_PTR (Sampler)
DECLARE_SMART_PTR() [120/179]
castor3d::DECLARE_SMART_PTR (PostFxPlugin)
DECLARE_SMART_PTR() [121/179]
castor3d::DECLARE_SMART_PTR (SubsurfaceScattering)
DECLARE_SMART_PTR() [122/179]
castor3d::DECLARE_SMART_PTR (ParticlePlugin)
DECLARE_SMART_PTR() [123/179]
castor3d::DECLARE_SMART_PTR (FrameEvent)
DECLARE_SMART_PTR() [124/179]
castor3d::DECLARE_SMART_PTR (FrameListener)
DECLARE_SMART_PTR() [125/179]
castor3d::DECLARE_SMART_PTR (IWindowHandle)
DECLARE_SMART_PTR() [126/179]
castor3d::DECLARE_SMART_PTR (GpuQuery)
DECLARE_SMART_PTR() [127/179]
castor3d::DECLARE_SMART_PTR (PickingPass)
DECLARE_SMART_PTR() [128/179]
castor3d::DECLARE_SMART_PTR (TransformFeedback)
DECLARE_SMART_PTR() [129/179]
castor3d::DECLARE_SMART_PTR (ComputePipeline)
DECLARE_SMART_PTR() [130/179]
castor3d::DECLARE_SMART_PTR (RenderPassTimer)
DECLARE_SMART_PTR() [131/179]
castor3d::DECLARE_SMART_PTR (GaussianBlur)
DECLARE_SMART_PTR() [132/179]
castor3d::DECLARE_SMART_PTR (BlendState)
DECLARE_SMART_PTR() [133/179]
castor3d::DECLARE_SMART_PTR (BufferDeclaration)
DECLARE_SMART_PTR() [134/179]
castor3d::DECLARE_SMART_PTR (BufferElementDeclaration)
DECLARE_SMART_PTR() [135/179]
castor3d::DECLARE_SMART_PTR (Context)
DECLARE_SMART_PTR() [136/179]
castor3d::DECLARE_SMART_PTR (DepthStencilState)
DECLARE_SMART_PTR() [137/179]
castor3d::DECLARE_SMART_PTR (EnvironmentMap)
DECLARE_SMART_PTR() [138/179]
castor3d::DECLARE_SMART_PTR (EnvironmentMapPass)
DECLARE_SMART_PTR() [139/179]
castor3d::DECLARE_SMART_PTR (GeometryBuffers)
DECLARE_SMART_PTR() [140/179]
castor3d::DECLARE_SMART_PTR (GpuBuffer)
DECLARE_SMART_PTR() [141/179]
castor3d::DECLARE_SMART_PTR (IblTextures)
DECLARE_SMART_PTR() [142/179]
castor3d::DECLARE_SMART_PTR (IndexBuffer)
DECLARE_SMART_PTR() [143/179]
castor3d::DECLARE_SMART_PTR (MultisampleState)
DECLARE_SMART_PTR() [144/179]
castor3d::DECLARE_SMART_PTR (PostEffect)
DECLARE_SMART_PTR() [145/179]
castor3d::DECLARE_SMART_PTR (RasteriserState)
DECLARE_SMART_PTR() [146/179]
castor3d::DECLARE_SMART_PTR (RenderColourCubeLayerToTexture)
DECLARE_SMART_PTR() [147/179]
castor3d::DECLARE_SMART_PTR (RenderColourCubeToTexture)
DECLARE_SMART_PTR() [148/179]
castor3d::DECLARE_SMART_PTR (RenderColourLayerToTexture)
DECLARE_SMART_PTR() [149/179]
castor3d::DECLARE_SMART_PTR (RenderColourToCube)
DECLARE_SMART_PTR() [150/179]
castor3d::DECLARE_SMART_PTR (RenderColourToTexture)
DECLARE_SMART_PTR() [151/179]
castor3d::DECLARE_SMART_PTR (RenderDepthCubeLayerToTexture)
DECLARE_SMART_PTR() [152/179]
castor3d::DECLARE_SMART_PTR (RenderDepthCubeToTexture)
DECLARE_SMART_PTR() [153/179]
castor3d::DECLARE_SMART_PTR (RenderDepthLayerToTexture)
DECLARE_SMART_PTR() [154/179]
castor3d::DECLARE_SMART_PTR (RenderDepthToCube)
DECLARE_SMART_PTR() [155/179]
castor3d::DECLARE_SMART_PTR (RenderLoop)
DECLARE_SMART_PTR() [156/179]
castor3d::DECLARE_SMART_PTR (RenderPipeline)
DECLARE_SMART_PTR() [157/179]
castor3d::DECLARE_SMART_PTR (RenderSystem)
DECLARE_SMART_PTR() [158/179]
castor3d::DECLARE_SMART_PTR (RenderTarget)
DECLARE_SMART_PTR() [159/179]
castor3d::DECLARE_SMART_PTR (RenderTechnique)
DECLARE_SMART_PTR() [160/179]
castor3d::DECLARE_SMART_PTR (RenderWindow)
DECLARE_SMART_PTR() [161/179]
castor3d::DECLARE_SMART_PTR (ShadowMap)
DECLARE_SMART_PTR() [162/179]
castor3d::DECLARE_SMART_PTR (ShadowMapPass)
DECLARE_SMART_PTR() [163/179]
castor3d::DECLARE_SMART_PTR (TextureBuffer)
DECLARE_SMART_PTR() [164/179]
castor3d::DECLARE_SMART_PTR (TextureProjection)
DECLARE_SMART_PTR() [165/179]
castor3d::DECLARE_SMART_PTR (ToneMapping)
DECLARE_SMART_PTR() [166/179]
castor3d::DECLARE_SMART_PTR (VertexBuffer)
DECLARE_SMART_PTR() [167/179]
castor3d::DECLARE_SMART_PTR (ListenerCache)
DECLARE_SMART_PTR() [168/179]
castor3d::DECLARE_SMART_PTR (ShaderProgramCache)
DECLARE_SMART_PTR() [169/179]
castor3d::DECLARE_SMART_PTR (RenderTargetCache)
DECLARE_SMART_PTR() [170/179]
castor3d::DECLARE_SMART_PTR (PushUniform1b)
DECLARE_SMART_PTR() [171/179]
castor3d::DECLARE_SMART_PTR (BillboardListCache)
DECLARE_SMART_PTR() [172/179]
castor3d::DECLARE_SMART_PTR (UniformBuffer)
DECLARE_SMART_PTR() [173/179]
castor3d::DECLARE_SMART_PTR (UniformBufferBinding)
DECLARE_SMART_PTR() [174/179]
castor3d::DECLARE_SMART_PTR (Uniform)
DECLARE_SMART_PTR() [175/179]
castor3d::DECLARE_SMART_PTR (PushUniform)
DECLARE_SMART_PTR() [176/179]
castor3d::DECLARE_SMART_PTR (ShaderObject)
DECLARE_SMART_PTR() [177/179]
castor3d::DECLARE_SMART_PTR (ShaderProgram)
DECLARE_SMART_PTR() [178/179]
castor3d::DECLARE_SMART_PTR (ShaderStorageBuffer)
DECLARE_SMART_PTR() [179/179]
castor3d::DECLARE_SMART_PTR (AtomicCounterBuffer)
DECLARE_VECTOR() [1/36]
castor3d::DECLARE_VECTOR (CameraSPtr , CameraPtr)
Camera pointer array.
DECLARE_VECTOR() [2/36]
castor3d::DECLARE_VECTOR (LightSPtr , LightPtr)
Array of lights.
DECLARE_VECTOR() [3/36]
castor3d::DECLARE_VECTOR (StaticRenderNode , StaticRenderNode)
DECLARE_VECTOR() [4/36]
castor3d::DECLARE_VECTOR (SkinningRenderNode , SkinningRenderNode)
DECLARE_VECTOR() [5/36]
castor3d::DECLARE_VECTOR (MorphingRenderNode , MorphingRenderNode)
DECLARE_VECTOR() [6/36]
castor3d::DECLARE_VECTOR (BillboardRenderNode , BillboardRenderNode)
DECLARE_VECTOR() [7/36]
castor3d::DECLARE_VECTOR (Vertex , Vertex)
Vertex array.
DECLARE_VECTOR() [8/36]
castor3d::DECLARE_VECTOR (BufferElementGroupSPtr , VertexPtr)
Vertex pointer array.
DECLARE_VECTOR() [9/36]
castor3d::DECLARE_VECTOR (Face , Face)
Face array.
DECLARE_VECTOR() [10/36]
castor3d::DECLARE_VECTOR (FaceSPtr , FacePtr)
Face pointer array.
DECLARE_VECTOR() [11/36]
castor3d::DECLARE_VECTOR (FaceGroupSPtr , FaceGroupPtr)
FaceGroup pointer array.
DECLARE_VECTOR() [12/36]
castor3d::DECLARE_VECTOR (SubmeshSPtr , SubmeshPtr)
Submesh pointer array.
DECLARE_VECTOR() [13/36]
castor3d::DECLARE_VECTOR (GeometrySPtr , GeometryPtr)
Geometry pointer array.
DECLARE_VECTOR() [14/36]
castor3d::DECLARE_VECTOR (BoneSPtr , BonePtr)
Bone pointer array.
DECLARE_VECTOR() [15/36]
castor3d::DECLARE_VECTOR (BonedVertexSPtr , BonedVertexPtr)
BonedVertex pointer array.
DECLARE_VECTOR() [16/36]
castor3d::DECLARE_VECTOR (OverlaySPtr , OverlayPtr)
DECLARE_VECTOR() [17/36]
castor3d::DECLARE_VECTOR (SkeletonAnimationObjectSPtr , SkeletonAnimationObjectPtr)
SkeletonAnimationObject pointer array.
DECLARE_VECTOR() [18/36]
castor3d::DECLARE_VECTOR (MeshAnimationSubmesh , MeshAnimationSubmesh)
SkeletonAnimationObject array.
DECLARE_VECTOR() [19/36]
castor3d::DECLARE_VECTOR (SceneNodeSPtr , SceneNodePtr)
SceneNode pointer array.
DECLARE_VECTOR() [20/36]
castor3d::DECLARE_VECTOR (SkeletonAnimationInstanceObjectSPtr , SkeletonAnimationInstanceObjectPtr)
SkeletonAnimationInstanceObject pointer array.
DECLARE_VECTOR() [21/36]
castor3d::DECLARE_VECTOR (std::reference_wrapper< SkeletonAnimationInstance > , SkeletonAnimationInstance)
Skeleton animation instance pointer array.
DECLARE_VECTOR() [22/36]
castor3d::DECLARE_VECTOR (MaterialSPtr , MaterialPtr)
Material pointer array.
DECLARE_VECTOR() [23/36]
castor3d::DECLARE_VECTOR (TextureUnit , TextureUnit)
TextureUnit array.
DECLARE_VECTOR() [24/36]
castor3d::DECLARE_VECTOR (TextureUnitSPtr , TextureUnitPtr)
TextureUnit pointer array.
DECLARE_VECTOR() [25/36]
castor3d::DECLARE_VECTOR (Pass , Pass)
Pass array.
DECLARE_VECTOR() [26/36]
castor3d::DECLARE_VECTOR (PassSPtr , PassPtr)
Pass pointer array.
DECLARE_VECTOR() [27/36]
castor3d::DECLARE_VECTOR (uint32_t , UInt)
uint32_t array
DECLARE_VECTOR() [28/36]
castor3d::DECLARE_VECTOR (std::reference_wrapper< TextureUnit > , DepthMap)
TextureUnit reference array.
DECLARE_VECTOR() [29/36]
castor3d::DECLARE_VECTOR (real , Real)
real array
DECLARE_VECTOR() [30/36]
castor3d::DECLARE_VECTOR (RenderWindowSPtr , RenderWindowPtr)
RenderWindow pointer array.
DECLARE_VECTOR() [31/36]
castor3d::DECLARE_VECTOR (RenderBufferSPtr , RenderBufferPtr)
RenderBuffer pointer array.
DECLARE_VECTOR() [32/36]
castor3d::DECLARE_VECTOR (FrameEventUPtr , FrameEventPtr)
FrameEvent pointer array.
DECLARE_VECTOR() [33/36]
castor3d::DECLARE_VECTOR (PostEffectSPtr , PostEffectPtr)
DECLARE_VECTOR() [34/36]
castor3d::DECLARE_VECTOR (BillboardListSPtr , BillboardList)
DECLARE_VECTOR() [35/36]
castor3d::DECLARE_VECTOR (ShaderProgramSPtr , ShaderProgramPtr)
DECLARE_VECTOR() [36/36]
castor3d::DECLARE_VECTOR (ShaderObjectSPtr , ShaderObjectPtr)
declareDecodeMaterial()
void castor3d::declareDecodeMaterial (glsl::GlslWriter & writer)
Declares the GLSL function used to decode the material specifics from a vec4.
Parameters
[in] writer The GLSL writer.
declareDecodeReceiver()
void castor3d::declareDecodeReceiver (glsl::GlslWriter & writer)
Declares the GLSL function used to decode the shadow receiver status from a vec4.
Parameters
[in] writer The GLSL writer.
declareEncodeMaterial()
void castor3d::declareEncodeMaterial (glsl::GlslWriter & writer)
Declares the GLSL function used to encode the material specifics into a vec4.
Parameters
[in] writer The GLSL writer.
decodeMaterial()
void castor3d::decodeMaterial (glsl::GlslWriter & writer, glsl::Float const & encoded, glsl::Int const & receiver, glsl::Int const & reflection, glsl::Int const & refraction, glsl::Int const & envMapIndex)
Calls the GLSL function used to dencode the material specifics from a vec4.
Parameters
[in] writer The GLSL writer.
[in] encoded The encoded value.
[in] receiver The variable that contains the shadow receiver status.
[in] reflection The variable that contains the reflection status.
[in] refraction The variable that contains the refraction status.
[in] envMapIndex The variable that contains the environment map index.
decodeReceiver()
void castor3d::decodeReceiver (glsl::GlslWriter & writer, glsl::Int & encoded, glsl::Int const & receiver)
Calls the GLSL function used to decode the shadow receiver status from a vec4.
Parameters
[in] writer The GLSL writer.
[in] encoded The encoded value.
[in] receiver The variable that contains the shadow receiver status.
doBindPass()
void castor3d::doBindPass (SceneNode & sceneNode, PassRenderNode & node, Scene & scene, RenderPipeline & pipeline, ShadowMapLightTypeArray & shadowMaps, ModelUbo & model, EnvironmentMap *& envMap) inline
References castor3d::TextureUnit::bind(), castor3d::Pass::bindTextures(), doFillShaderPbrMaps(), doFillShaderShadowMaps(), castor3d::Scene::getEnvironmentMap(), castor3d::RenderPipeline::getEnvironmentMapVariable(), castor3d::RenderPipeline::getFlags(), castor3d::EnvironmentMap::getIndex(), castor3d::EnvironmentMap::getTexture(), castor3d::RenderPipeline::getTexturesCount(), castor3d::Pass::hasEnvironmentMapping(), castor3d::PassRenderNode::m_pass, castor3d::PipelineFlags::m_passFlags, castor3d::PipelineFlags::m_programFlags, castor3d::PassRenderNode::m_textures, MinTextureIndex, castor3d::ModelUbo::setEnvMapIndex(), castor3d::TextureUnit::setIndex(), and castor3d::TPushUniform< Type >::setValue().
doBindPassOpacityMap()
void castor3d::doBindPassOpacityMap (PassRenderNode & node, Pass & pass) inline
References castor3d::Pass::getTextureUnit(), and castor3d::PassRenderNode::m_textures.
doFillShaderPbrMaps()
uint32_t castor3d::doFillShaderPbrMaps (RenderPipeline & pipeline, Scene & scene, SceneNode & sceneNode, uint32_t index) inline
References castor3d::RenderPipeline::getBrdfMapVariable(), castor3d::Skybox::getIbl(), castor3d::Scene::getIbl(), castor3d::IblTextures::getIrradiance(), castor3d::RenderPipeline::getIrradianceMapVariable(), castor3d::IblTextures::getPrefilteredBrdf(), castor3d::IblTextures::getPrefilteredEnvironment(), castor3d::RenderPipeline::getPrefilteredMapVariable(), castor3d::TextureUnit::getSampler(), castor3d::Scene::getSkybox(), castor3d::TextureUnit::getTexture(), and castor3d::TPushUniform< Type >::setValue().
Referenced by doBindPass().
doFillShaderShadowMaps()
uint32_t castor3d::doFillShaderShadowMaps (RenderPipeline & pipeline, ShadowMapLightTypeArray & shadowMaps, uint32_t & index) inline
References castor3d::RenderPipeline::getDirectionalShadowMapsVariable(), castor3d::RenderPipeline::getFlags(), castor3d::RenderPipeline::getPointShadowMapsVariable(), getShadowType(), castor3d::RenderPipeline::getSpotShadowMapsVariable(), castor3d::PipelineFlags::m_sceneFlags, and castor3d::TPushUniform< Type >::setValue().
Referenced by doBindPass().
doRenderNode()
template<typename NodeType > void castor3d::doRenderNode (NodeType & node) inline
References doRenderNodeNoPass().
Referenced by castor3d::DistanceRenderNode< NodeType >::render().
doRenderNodeNoPass() [1/4]
void castor3d::doRenderNodeNoPass (StaticRenderNode & node) inline
References doRenderObjectNode().
doRenderNodeNoPass() [2/4]
void castor3d::doRenderNodeNoPass (BillboardRenderNode & node) inline
References doRenderObjectNode(), castor3d::BillboardRenderNode::m_billboardUbo, castor3d::ObjectRenderNode< DataTypeT, InstanceTypeT >::m_instance, and castor3d::BillboardUbo::update().
doRenderNodeNoPass() [3/4]
void castor3d::doRenderNodeNoPass (MorphingRenderNode & node) inline
References doRenderObjectNode(), castor3d::MeshAnimationInstance::getAnimationSubmesh(), castor3d::AnimatedMesh::getPlayingAnimation(), castor3d::AnimatedMesh::isPlayingAnimation(), castor3d::ObjectRenderNode< DataTypeT, InstanceTypeT >::m_data, castor3d::MorphingRenderNode::m_mesh, castor3d::MorphingRenderNode::m_morphingUbo, and castor3d::MorphingUbo::update().
doRenderNodeNoPass() [4/4]
void castor3d::doRenderNodeNoPass (SkinningRenderNode & node) inline
References doRenderObjectNode(), castor3d::RenderPipeline::getFlags(), castor3d::ObjectRenderNode< DataTypeT, InstanceTypeT >::m_pipeline, castor3d::PipelineFlags::m_programFlags, castor3d::SkinningRenderNode::m_skeleton, castor3d::SkinningRenderNode::m_skinningUbo, and castor3d::SkinningUbo::update().
Referenced by doRenderNode().
doRenderObjectNode()
template<typename DataType , typename InstanceType > void castor3d::doRenderObjectNode (ObjectRenderNode< DataType, InstanceType > & node) inline
References castor3d::ObjectRenderNode< DataTypeT, InstanceTypeT >::m_buffers, castor3d::ObjectRenderNode< DataTypeT, InstanceTypeT >::m_data, castor3d::ObjectRenderNode< DataTypeT, InstanceTypeT >::m_modelMatrixUbo, and castor3d::ObjectRenderNode< DataTypeT, InstanceTypeT >::m_sceneNode.
Referenced by doRenderNodeNoPass().
doUnbindPassOpacityMap()
void castor3d::doUnbindPassOpacityMap (PassRenderNode & node, Pass & pass) inline
References castor3d::Pass::getTextureUnit().
encodeMaterial()
void castor3d::encodeMaterial (glsl::GlslWriter & writer, glsl::Int const & receiver, glsl::Int const & reflection, glsl::Int const & refraction, glsl::Int const & envMapIndex, glsl::Float const & encoded)
Calls the GLSL function used to encode the material specifics into a vec4.
Parameters
[in] writer The GLSL writer.
[in] receiver The shadow receiver status.
[in] reflection The reflection status.
[in] refraction The refraction status.
[in] envMapIndex The environment map index.
[in] encoded The variable that will receive the encoded value.
getBuffer() [1/46]
static uint8_t const* castor3d::getBuffer (bool const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
Referenced by castor3d::ChunkParser< T >::parse(), and castor3d::ChunkWriter< T >::write().
getBuffer() [2/46]
static uint8_t* castor3d::getBuffer (bool & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
getBuffer() [3/46]
static uint8_t const* castor3d::getBuffer (int8_t const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
getBuffer() [4/46]
static uint8_t* castor3d::getBuffer (int8_t & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
getBuffer() [5/46]
static uint8_t const* castor3d::getBuffer (uint8_t const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
getBuffer() [6/46]
static uint8_t* castor3d::getBuffer (uint8_t & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
getBuffer() [7/46]
static uint8_t const* castor3d::getBuffer (int16_t const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
getBuffer() [8/46]
static uint8_t* castor3d::getBuffer (int16_t & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
getBuffer() [9/46]
static uint8_t const* castor3d::getBuffer (uint16_t const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
getBuffer() [10/46]
static uint8_t* castor3d::getBuffer (uint16_t & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
getBuffer() [11/46]
static uint8_t const* castor3d::getBuffer (int32_t const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
getBuffer() [12/46]
static uint8_t* castor3d::getBuffer (int32_t & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
getBuffer() [13/46]
static uint8_t const* castor3d::getBuffer (uint32_t const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
getBuffer() [14/46]
static uint8_t* castor3d::getBuffer (uint32_t & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
getBuffer() [15/46]
static uint8_t const* castor3d::getBuffer (int64_t const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
getBuffer() [16/46]
static uint8_t* castor3d::getBuffer (int64_t & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
getBuffer() [17/46]
static uint8_t const* castor3d::getBuffer (uint64_t const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
getBuffer() [18/46]
static uint8_t* castor3d::getBuffer (uint64_t & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
getBuffer() [19/46]
static uint8_t const* castor3d::getBuffer (float const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
getBuffer() [20/46]
static uint8_t* castor3d::getBuffer (float & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
getBuffer() [21/46]
static uint8_t const* castor3d::getBuffer (double const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
getBuffer() [22/46]
static uint8_t* castor3d::getBuffer (double & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
getBuffer() [23/46]
static uint8_t const* castor3d::getBuffer (long double const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
getBuffer() [24/46]
static uint8_t* castor3d::getBuffer (long double & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
getBuffer() [25/46]
template<typename T > static uint8_t const* castor3d::getBuffer (std::vector< T > const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
getBuffer() [26/46]
template<typename T > static uint8_t* castor3d::getBuffer (std::vector< T > & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
getBuffer() [27/46]
template<typename T , size_t Count> static uint8_t const* castor3d::getBuffer (std::array< T, Count > const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
getBuffer() [28/46]
template<typename T , size_t Count> static uint8_t* castor3d::getBuffer (std::array< T, Count > & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
getBuffer() [29/46]
template<typename T , uint32_t Count> static uint8_t const* castor3d::getBuffer (castor::Point< T, Count > const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
getBuffer() [30/46]
template<typename T , uint32_t Count> static uint8_t* castor3d::getBuffer (castor::Point< T, Count > & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
getBuffer() [31/46]
template<typename T , uint32_t Count> static uint8_t const* castor3d::getBuffer (castor::Coords< T, Count > const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
getBuffer() [32/46]
template<typename T , uint32_t Count> static uint8_t* castor3d::getBuffer (castor::Coords< T, Count > & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
getBuffer() [33/46]
template<typename T , uint32_t Columns, uint32_t Rows> static uint8_t const* castor3d::getBuffer (castor::Matrix< T, Columns, Rows > const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
getBuffer() [34/46]
template<typename T , uint32_t Columns, uint32_t Rows> static uint8_t* castor3d::getBuffer (castor::Matrix< T, Columns, Rows > & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
getBuffer() [35/46]
template<typename T , uint32_t Count> static uint8_t const* castor3d::getBuffer (castor::SquareMatrix< T, Count > const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
getBuffer() [36/46]
template<typename T , uint32_t Count> static uint8_t* castor3d::getBuffer (castor::SquareMatrix< T, Count > & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
getBuffer() [37/46]
static uint8_t const* castor3d::getBuffer (castor::RgbColour const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
getBuffer() [38/46]
static uint8_t* castor3d::getBuffer (castor::RgbColour & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
getBuffer() [39/46]
static uint8_t const* castor3d::getBuffer (castor::RgbaColour const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
getBuffer() [40/46]
static uint8_t* castor3d::getBuffer (castor::RgbaColour & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
getBuffer() [41/46]
static uint8_t const* castor3d::getBuffer (castor::Size const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
getBuffer() [42/46]
static uint8_t* castor3d::getBuffer (castor::Size & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
getBuffer() [43/46]
static uint8_t const* castor3d::getBuffer (castor::Position const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
getBuffer() [44/46]
static uint8_t* castor3d::getBuffer (castor::Position & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
getBuffer() [45/46]
template<typename T > static uint8_t const* castor3d::getBuffer (castor::QuaternionT< T > const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
getBuffer() [46/46]
template<typename T > static uint8_t* castor3d::getBuffer (castor::QuaternionT< T > & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
getCPUCount()
int castor3d::getCPUCount ()
getDataSize() [1/12]
template<typename T > static size_t castor3d::getDataSize (T const & p_value) inline static
Retrieves the value binary size.
Parameters
[in] p_value The value.
Returns
The size (sizeof(p_value) for basic types).
Referenced by castor3d::ChunkParser< T >::parse(), and castor3d::ChunkWriter< T >::write().
getDataSize() [2/12]
template<typename T > static size_t castor3d::getDataSize (std::vector< T > const & p_value) inline static
Retrieves the value binary size.
Parameters
[in] p_value The value.
Returns
The size (sizeof(p_value) for basic types).
getDataSize() [3/12]
template<typename T , size_t Count> static size_t castor3d::getDataSize (std::array< T, Count > const & p_value) inline static
Retrieves the value binary size.
Parameters
[in] p_value The value.
Returns
The size (sizeof(p_value) for basic types).
getDataSize() [4/12]
template<typename T , uint32_t Count> static size_t castor3d::getDataSize (castor::Point< T, Count > const & p_value) inline static
Retrieves the value binary size.
Parameters
[in] p_value The value.
Returns
The size (sizeof(p_value) for basic types).
getDataSize() [5/12]
template<typename T , uint32_t Count> static size_t castor3d::getDataSize (castor::Coords< T, Count > const & p_value) inline static
Retrieves the value binary size.
Parameters
[in] p_value The value.
Returns
The size (sizeof(p_value) for basic types).
getDataSize() [6/12]
template<typename T , uint32_t Columns, uint32_t Rows> static size_t castor3d::getDataSize (castor::Matrix< T, Columns, Rows > const & p_value) inline static
Retrieves the value binary size.
Parameters
[in] p_value The value.
Returns
The size (sizeof(p_value) for basic types).
getDataSize() [7/12]
template<typename T , uint32_t Count> static size_t castor3d::getDataSize (castor::SquareMatrix< T, Count > const & p_value) inline static
Retrieves the value binary size.
Parameters
[in] p_value The value.
Returns
The size (sizeof(p_value) for basic types).
getDataSize() [8/12]
static size_t castor3d::getDataSize (castor::RgbColour const & p_value) inline static
Retrieves the value binary size.
Parameters
[in] p_value The value.
Returns
The size (sizeof(p_value) for basic types).
getDataSize() [9/12]
static size_t castor3d::getDataSize (castor::RgbaColour const & p_value) inline static
Retrieves the value binary size.
Parameters
[in] p_value The value.
Returns
The size (sizeof(p_value) for basic types).
getDataSize() [10/12]
static size_t castor3d::getDataSize (castor::Size const & p_value) inline static
Retrieves the value binary size.
Parameters
[in] p_value The value.
Returns
The size (sizeof(p_value) for basic types).
getDataSize() [11/12]
static size_t castor3d::getDataSize (castor::Position const & p_value) inline static
Retrieves the value binary size.
Parameters
[in] p_value The value.
Returns
The size (sizeof(p_value) for basic types).
getDataSize() [12/12]
template<typename T > static size_t castor3d::getDataSize (castor::QuaternionT< T > const & p_value) inline static
Retrieves the value binary size.
Parameters
[in] p_value The value.
Returns
The size (sizeof(p_value) for basic types).
getFogType()
C3D_API FogType castor3d::getFogType (SceneFlags const & p_flags)
Gives the fog type matching the given flags.
Parameters
[in] p_flags The scene flags.
Returns
The fog type.
getMaxDistance() [1/2]
float castor3d::getMaxDistance (LightCategory const & light, castor::Point3f const & attenuation)
Retrieve the maximum litten distance for given light and attenuation.
Parameters
[in] light The light source.
[in] attenuation The attenuation values.
Returns
The value.
getMaxDistance() [2/2]
float castor3d::getMaxDistance (LightCategory const & light, castor::Point3f const & attenuation, float max)
Retrieve the maximum litten distance for given light and attenuation.
Parameters
[in] light The light source.
[in] attenuation The attenuation values.
[in] max The viewer max value.
Returns
The value.
getName()
C3D_API castor::String castor3d::getName (ElementType p_type)
gets the name of the given element type.
Parameters
[in] p_type The element type.
Returns
The name.
getShadowType()
C3D_API ShadowType castor3d::getShadowType (SceneFlags const & p_flags)
Gives the shadow filter type matching the given flags.
Parameters
[in] p_flags The scene flags.
Returns
The shadow filter type.
Referenced by doFillShaderShadowMaps().
getSize()
uint32_t castor3d::getSize (ElementType p_type) inline
gets the byte size of the given element type.
Parameters
[in] p_type The element type.
Returns
The size.
References eColour, eFloat, eInt, eIVec2, eIVec3, eIVec4, eMat2, eMat3, eMat4, eUInt, eUIVec2, eUIVec3, eUIVec4, eVec2, eVec3, and eVec4.
Referenced by castor3d::BufferDeclaration::push_back().
getTextureAttachmentIndex() [1/2]
uint32_t castor3d::getTextureAttachmentIndex (WbTexture texture)
Retrieve the attachment index for given texture enum value.
Parameters
[in] texture The value.
Returns
The name.
getTextureAttachmentIndex() [2/2]
uint32_t castor3d::getTextureAttachmentIndex (DsTexture texture)
Retrieve the attachment index for given texture enum value.
Parameters
[in] texture The value.
Returns
The name.
getTextureAttachmentPoint() [1/2]
AttachmentPoint castor3d::getTextureAttachmentPoint (WbTexture texture)
Retrieve the attachment point for given texture enum value.
Parameters
[in] texture The value.
Returns
The name.
getTextureAttachmentPoint() [2/2]
AttachmentPoint castor3d::getTextureAttachmentPoint (DsTexture texture)
Retrieve the attachment point for given texture enum value.
Parameters
[in] texture The value.
Returns
The name.
getTextureFormat() [1/2]
castor::PixelFormat castor3d::getTextureFormat (WbTexture texture)
Retrieve the pixel format for given texture enum value.
Parameters
[in] texture The value.
Returns
The name.
getTextureFormat() [2/2]
castor::PixelFormat castor3d::getTextureFormat (DsTexture texture)
Retrieve the pixel format for given texture enum value.
Parameters
[in] texture The value.
Returns
The name.
getTextureName() [1/2]
castor::String castor3d::getTextureName (WbTexture texture)
Retrieve the name for given texture enum value.
Parameters
[in] texture The value.
Returns
The name.
getTextureName() [2/2]
castor::String castor3d::getTextureName (DsTexture texture)
Retrieve the name for given texture enum value.
Parameters
[in] texture The value.
Returns
The name.
getTopologyName()
static castor::String const castor3d::getTopologyName (Topology p_topology) inline static
gets the name of the given topology.
Parameters
[in] p_topology The topology.
Returns
The name.
References eLineLoop, eLines, eLineStrip, ePoints, eTriangleFan, eTriangles, and eTriangleStrips.
isShadowMapProgram()
bool castor3d::isShadowMapProgram (ProgramFlags const & p_flags)
Tells if the given flags contain a shadow map flag.
Parameters
[in] p_flags The flags to check.
Returns
true if p_flags contain one of ProgramFlag::eShadowMapDirectional, ProgramFlag::eShadowMapSpot, or ProgramFlag::eShadowMapPoint.
makeCache() [1/2]
std::unique_ptr< ShaderProgramCache > castor3d::makeCache (Engine & engine) inline
Creates a ShaderProgram cache.
Parameters
[in] engine The engine.
makeCache() [2/2]
template<typename ElementType , typename KeyType > std::unique_ptr< Cache< ElementType, KeyType > > castor3d::makeCache (Engine & engine, typename CacheTraits< ElementType, KeyType >::Producer && produce, ElementInitialiser< ElementType > && initialise = [](std::shared_ptr< ElementType >){}, ElementCleaner< ElementType > && clean = [](std::shared_ptr< ElementType >){}, typename CacheTraits< ElementType, KeyType >::Merger && merge = [](CacheBase< ElementType, KeyType > const & , castor::Collection< ElementType, KeyType > & , std::shared_ptr< ElementType >){}) inline
Creates a cache.
Parameters
[in] engine The engine.
[in] produce The element producer.
[in] initialise The element initialiser.
[in] clean The element cleaner.
[in] merge The element collection merger.
makeCleanupEvent()
template<typename T > std::unique_ptr< CleanupEvent< T > > castor3d::makeCleanupEvent (T & p_object)
Helper function to create a cleanup event.
Parameters
[in] p_object The object to cleanup
makeFunctorEvent()
template<typename Functor > std::unique_ptr< FunctorEvent< Functor > > castor3d::makeFunctorEvent (EventType p_type, Functor p_functor) inline
Helper function to create a functor event.
Parameters
[in] p_type The event type
[in] p_functor The functor to execute
makeInitialiseEvent()
template<typename T > std::unique_ptr< InitialiseEvent< T > > castor3d::makeInitialiseEvent (T & p_object)
Helper function to create an initialise event.
Parameters
[in] p_object The object to initialise
makeObjectCache()
template<typename ElementType , typename KeyType > std::unique_ptr< ObjectCache< ElementType, KeyType > > castor3d::makeObjectCache (Engine & engine, Scene & p_scene, SceneNodeSPtr p_rootNode, SceneNodeSPtr p_rootCameraNode, SceneNodeSPtr p_rootObjectNode, typename ObjectCacheTraits< ElementType, KeyType >::Producer && p_produce, ElementInitialiser< ElementType > && p_initialise = [](std::shared_ptr< ElementType >){}, ElementCleaner< ElementType > && p_clean = [](std::shared_ptr< ElementType >){}, typename ObjectCacheTraits< ElementType, KeyType >::Merger && p_merge = [](ObjectCacheBase< ElementType, KeyType > const & , castor::Collection< ElementType, KeyType > & , std::shared_ptr< ElementType > , SceneNodeSPtr , SceneNodeSPtr){}, ElementAttacher< ElementType > && p_attach = [](std::shared_ptr< ElementType >, SceneNodeSPtr, SceneNodeSPtr, SceneNodeSPtr, SceneNodeSPtr){}, ElementDetacher< ElementType > && p_detach = [](std::shared_ptr< ElementType >){}) inline
Creates an object cache.
Parameters
[in] engine The engine.
[in] p_scene The scene.
[in] p_rootNode The scene root node.
[in] p_rootCameraNode The root node for cameras.
[in] p_rootObjectNode The root node for objects.
[in] p_produce The element producer.
[in] p_initialise The element initialiser.
[in] p_clean The element cleaner.
[in] p_merge The element collection merger.
[in] p_attach The element attacher (to a scene node).
[in] p_detach The element detacher (from a scene node).
operator!=() [1/4]
bool castor3d::operator!= (BufferElementDeclaration const & p_lhs, BufferElementDeclaration const & p_rhs) inline
Equality operator.
Parameters
[in] p_lhs,p_rhs The 2 objects to compare.
References castor3d::BufferElementDeclaration::m_dataType, castor3d::BufferElementDeclaration::m_divisor, castor3d::BufferElementDeclaration::m_name, castor3d::BufferElementDeclaration::m_offset, and castor3d::BufferElementDeclaration::m_usages.
operator!=() [2/4]
C3D_API bool castor3d::operator!= (castor3d::Version const & p_a, castor3d::Version const & p_b)
Difference operator.
Parameters
[in] p_a,p_b The versions to compare.
Returns
true if one version number is different from p_a to p_b.
operator!=() [3/4]
C3D_API bool castor3d::operator!= (ProgramInputLayout const & p_lhs, ProgramInputLayout const & p_rhs)
Equality operator.
Parameters
[in] p_lhs,p_rhs The 2 objects to compare.
operator!=() [4/4]
C3D_API bool castor3d::operator!= (BufferDeclaration & p_lhs, BufferDeclaration & p_rhs)
Equality operator.
Parameters
[in] p_lhs,p_rhs The 2 objects to compare.
operator<() [1/2]
bool castor3d::operator< (PipelineFlags const & lhs, PipelineFlags const & rhs) inline
References castor3d::PipelineFlags::m_alphaBlendMode, castor3d::PipelineFlags::m_colourBlendMode, castor3d::PipelineFlags::m_passFlags, castor3d::PipelineFlags::m_programFlags, castor3d::PipelineFlags::m_sceneFlags, and castor3d::PipelineFlags::m_textureFlags.
operator<() [2/2]
C3D_API bool castor3d::operator< (castor3d::Version const & p_a, castor3d::Version const & p_b)
Less than operator.
Parameters
[in] p_a,p_b The versions to compare.
Returns
true if p_a.major is less than p_b.major or if they are equal and p_a.minor is less than p_b.minor or if majors and minors are equal and p_a.build is less than p_b.build.
operator<<() [1/11]
std::ostream& castor3d::operator<< (std::ostream & o, Sphere const & c) inline
Stream operator.
operator<<() [2/11]
std::ostream& castor3d::operator<< (std::ostream & o, Cylinder const & c) inline
Stream operator.
operator<<() [3/11]
std::ostream& castor3d::operator<< (std::ostream & o, Cube const & c) inline
Stream operator.
operator<<() [4/11]
std::ostream& castor3d::operator<< (std::ostream & o, Plane const & c) inline
Stream operator.
operator<<() [5/11]
std::ostream& castor3d::operator<< (std::ostream & o, Cone const & c) inline
Stream operator.
operator<<() [6/11]
std::ostream& castor3d::operator<< (std::ostream & o, Icosahedron const & c) inline
Stream operator.
operator<<() [7/11]
std::ostream& castor3d::operator<< (std::ostream & o, Projection const & c) inline
Stream operator.
operator<<() [8/11]
C3D_API std::ostream& castor3d::operator<< (std::ostream & p_stream, castor3d::Version const & p_version)
operator<<() [9/11]
C3D_API std::wostream& castor3d::operator<< (std::wostream & p_stream, castor3d::Version const & p_version)
operator<<() [10/11]
C3D_API castor::String& castor3d::operator<< (castor::String & p_stream, castor3d::Version const & p_version)
operator<<() [11/11]
std::ostream& castor3d::operator<< (std::ostream & streamOut, TextureUnitSPtr const & texture) inline
Stream operator.
Parameters
[in,out] streamOut The stream receiving texture's data.
[in] texture The input texture.
Returns
A reference to the stream.
operator<=()
C3D_API bool castor3d::operator<= (castor3d::Version const & p_a, castor3d::Version const & p_b)
Less than operator.
Parameters
[in] p_a,p_b The versions to compare.
Returns
false if p_a.major is greater than p_b.major or if they are equal and p_a.minor is greater than p_b.minor or if majors and minors are equal and p_a.build is greater than p_b.build.
operator==() [1/4]
bool castor3d::operator== (BufferElementDeclaration const & p_lhs, BufferElementDeclaration const & p_rhs) inline
Equality operator.
Parameters
[in] p_lhs,p_rhs The 2 objects to compare.
References castor3d::BufferElementDeclaration::m_dataType, castor3d::BufferElementDeclaration::m_divisor, castor3d::BufferElementDeclaration::m_name, castor3d::BufferElementDeclaration::m_offset, and castor3d::BufferElementDeclaration::m_usages.
operator==() [2/4]
C3D_API bool castor3d::operator== (castor3d::Version const & p_a, castor3d::Version const & p_b)
Equality operator.
Parameters
[in] p_a,p_b The versions to compare.
Returns
false if one version number is different from p_a to p_b.
operator==() [3/4]
C3D_API bool castor3d::operator== (ProgramInputLayout const & p_lhs, ProgramInputLayout const & p_rhs)
Equality operator.
Parameters
[in] p_lhs,p_rhs The 2 objects to compare.
operator==() [4/4]
C3D_API bool castor3d::operator== (BufferDeclaration & p_lhs, BufferDeclaration & p_rhs)
Equality operator.
Parameters
[in] p_lhs,p_rhs The 2 objects to compare.
operator>()
C3D_API bool castor3d::operator> (castor3d::Version const & p_a, castor3d::Version const & p_b)
Less than operator.
Parameters
[in] p_a,p_b The versions to compare.
Returns
true if p_a.major is greater than p_b.major or if they are equal and p_a.minor is greater than p_b.minor or if majors and minors are equal and p_a.build is greater than p_b.build.
operator>=()
C3D_API bool castor3d::operator>= (castor3d::Version const & p_a, castor3d::Version const & p_b)
Less than operator.
Parameters
[in] p_a,p_b The versions to compare.
Returns
false if p_a.major is less than p_b.major or if they are equal and p_a.minor is less than p_b.minor or if majors and minors are equal and p_a.build is less than p_b.build.
prepareChunkData() [1/26]
static void castor3d::prepareChunkData (ChunkType & p_value) inline static
sets given value to big endian.
Parameters
[in,out] p_value The value.
Referenced by castor3d::ChunkParser< T >::parse(), prepareChunkData(), and castor3d::ChunkWriter< T >::write().
prepareChunkData() [2/26]
static void castor3d::prepareChunkData (bool & p_value) inline static
sets given value to big endian.
Parameters
[in,out] p_value The value.
prepareChunkData() [3/26]
static void castor3d::prepareChunkData (int8_t & p_value) inline static
sets given value to big endian.
Parameters
[in,out] p_value The value.
prepareChunkData() [4/26]
static void castor3d::prepareChunkData (uint8_t & p_value) inline static
sets given value to big endian.
Parameters
[in,out] p_value The value.
prepareChunkData() [5/26]
static void castor3d::prepareChunkData (int16_t & p_value) inline static
sets given value to big endian.
Parameters
[in,out] p_value The value.
prepareChunkData() [6/26]
static void castor3d::prepareChunkData (uint16_t & p_value) inline static
sets given value to big endian.
Parameters
[in,out] p_value The value.
prepareChunkData() [7/26]
static void castor3d::prepareChunkData (int32_t & p_value) inline static
sets given value to big endian.
Parameters
[in,out] p_value The value.
prepareChunkData() [8/26]
static void castor3d::prepareChunkData (uint32_t & p_value) inline static
sets given value to big endian.
Parameters
[in,out] p_value The value.
prepareChunkData() [9/26]
static void castor3d::prepareChunkData (int64_t & p_value) inline static
sets given value to big endian.
Parameters
[in,out] p_value The value.
prepareChunkData() [10/26]
static void castor3d::prepareChunkData (uint64_t & p_value) inline static
sets given value to big endian.
Parameters
[in,out] p_value The value.
prepareChunkData() [11/26]
static void castor3d::prepareChunkData (float & p_value) inline static
sets given value to big endian.
Parameters
[in,out] p_value The value.
prepareChunkData() [12/26]
static void castor3d::prepareChunkData (double & p_value) inline static
sets given value to big endian.
Parameters
[in,out] p_value The value.
prepareChunkData() [13/26]
static void castor3d::prepareChunkData (long double & p_value) inline static
sets given value to big endian.
Parameters
[in,out] p_value The value.
prepareChunkData() [14/26]
template<typename T > static void castor3d::prepareChunkData (std::vector< T > & p_value) inline static
sets given value to big endian.
Parameters
[in,out] p_value The value.
prepareChunkData() [15/26]
template<typename T , size_t Count> static void castor3d::prepareChunkData (std::array< T, Count > & p_value) inline static
sets given value to big endian.
Parameters
[in,out] p_value The value.
prepareChunkData() [16/26]
template<typename T , uint32_t Count> static void castor3d::prepareChunkData (castor::SquareMatrix< T, Count > & p_value) inline static
sets given value to big endian.
Parameters
[in,out] p_value The value.
prepareChunkData() [17/26]
template<typename T , uint32_t Count> static void castor3d::prepareChunkData (castor::Point< T, Count > & p_value) inline static
sets given value to big endian.
Parameters
[in,out] p_value The value.
prepareChunkData() [18/26]
template<typename T , uint32_t Count> static void castor3d::prepareChunkData (castor::Coords< T, Count > & p_value) inline static
sets given value to big endian.
Parameters
[in,out] p_value The value.
prepareChunkData() [19/26]
template<typename T > static void castor3d::prepareChunkData (castor::QuaternionT< T > & p_value) inline static
sets given value to big endian.
Parameters
[in,out] p_value The value.
prepareChunkData() [20/26]
static void castor3d::prepareChunkData (castor::ColourComponent & p_value) inline static
sets given value to big endian.
Parameters
[in,out] p_value The value.
prepareChunkData() [21/26]
static void castor3d::prepareChunkData (castor::RgbColour & p_value) inline static
sets given value to big endian.
Parameters
[in,out] p_value The value.
prepareChunkData() [22/26]
static void castor3d::prepareChunkData (castor::RgbaColour & p_value) inline static
sets given value to big endian.
Parameters
[in,out] p_value The value.
prepareChunkData() [23/26]
template<typename T > static void castor3d::prepareChunkData (InterleavedVertexT< T > & p_value) inline static
sets given value to big endian.
Parameters
[in,out] p_value The value.
References castor3d::InterleavedVertexT< T >::m_bin, castor3d::InterleavedVertexT< T >::m_nml, castor3d::InterleavedVertexT< T >::m_pos, castor3d::InterleavedVertexT< T >::m_tan, and castor3d::InterleavedVertexT< T >::m_tex.
prepareChunkData() [24/26]
template<typename T > static void castor3d::prepareChunkData (SubmeshAnimationBufferT< T > & p_value) inline static
sets given value to big endian.
Parameters
[in,out] p_value The value.
References castor3d::SubmeshAnimationBufferT< T >::m_buffer, and prepareChunkData().
prepareChunkData() [25/26]
static void castor3d::prepareChunkData (FaceIndices & p_value) inline static
sets given value to big endian.
Parameters
[in,out] p_value The value.
References castor3d::FaceIndices::m_index.
prepareChunkData() [26/26]
static void castor3d::prepareChunkData (VertexBoneData & p_value) inline static
sets given value to big endian.
Parameters
[in,out] p_value The value.
References castor3d::VertexBoneData::m_ids, and castor3d::VertexBoneData::m_weights.
Variable Documentation
C3D_MAX_BONES_PER_VERTEX
const uint32_t castor3d::C3D_MAX_BONES_PER_VERTEX = 8 static
C3D_MAX_TEXTURE_MATRICES
const uint32_t castor3d::C3D_MAX_TEXTURE_MATRICES = 4 static
CMSH_VERSION
uint32_t const castor3d::CMSH_VERSION = MAKE_CMSH_VERSION(0x01, 0x03, 0x0000)
The current format version number.
Referenced by castor3d::BinaryParserBase< Skeleton >::doParseHeader(), and castor3d::BinaryWriterBase< Skeleton >::doWriteHeader().
INFO_CACHE_CREATED_OBJECT
const xchar* castor3d::INFO_CACHE_CREATED_OBJECT = cuT("Cache::create - Created ") static
Referenced by castor3d::ObjectCache< SceneNode, castor::String >::add(), castor3d::CacheBase< Overlay, castor::String >::add(), and castor3d::ObjectCacheBase< Light, castor::String >::add().
LightBufferIndex
uint32_t constexpr castor3d::LightBufferIndex = 1u static
MinTextureIndex
uint32_t constexpr castor3d::MinTextureIndex = 2u static
Referenced by doBindPass().
PassBufferIndex
uint32_t constexpr castor3d::PassBufferIndex = 0u static
RENDERER_TYPE_UNDEFINED
castor::String const castor3d::RENDERER_TYPE_UNDEFINED = cuT("Undefined")
WARNING_CACHE_DUPLICATE_OBJECT
const xchar* castor3d::WARNING_CACHE_DUPLICATE_OBJECT = cuT("Cache::create - Duplicate ") static
Referenced by castor3d::ObjectCache< SceneNode, castor::String >::add(), castor3d::CacheBase< Overlay, castor::String >::add(), and castor3d::ObjectCacheBase< Light, castor::String >::add().
WARNING_CACHE_NULL_OBJECT
const xchar* castor3d::WARNING_CACHE_NULL_OBJECT = cuT("Cache::Insert - nullptr ") static
Referenced by castor3d::CacheBase< Overlay, castor::String >::add(), and castor3d::ObjectCacheBase< Light, castor::String >::add().