Castor3D: castor3d::SceneFileParser Class Reference
castor3d::SceneFileParser Class Reference
#include <SceneFileParser.hpp>
Public Member Functions
C3D_API SceneFileParser (Engine &engine, ProgressBar *progress=nullptr)
Constructor.
C3D_API castor::FileParserContextUPtr initialiseParser (castor::Path const &path)
RenderWindowDesc getRenderWindow ()
ScenePtrStrMap::iterator scenesBegin ()
ScenePtrStrMap::const_iterator scenesBegin () const
ScenePtrStrMap::const_iterator scenesEnd () const
Public Member Functions inherited from castor::OwnedBy< Engine >
Engine * getOwner () const
Public Member Functions inherited from castor::DataHolderT< RootContext >
DataHolderT () noexcept=default
DataHolderT (RootContext d) noexcept
RootContext & getData ()
RootContext const & getData () const
void setData (RootContext data)
Public Member Functions inherited from castor::FileParser
CU_API FileParser (SectionId rootSectionId, void *rootBlockContext=nullptr)
Constructor.
CU_API FileParser (LoggerInstance &logger, SectionId rootSectionId, void *rootBlockContext=nullptr)
Constructor.
virtual CU_API ~FileParser () noexcept=default
Destructor.
CU_API void registerParsers (String const &name, AdditionalParsers const &parsers)
Registers additional parsers.
CU_API void processFile (String const &appName, Path path, PreprocessedFile &preprocessed)
Parsing function.
CU_API void processFile (Path const &path, PreprocessedFile &preprocessed)
Parsing function.
CU_API void processFile (Path const &path, String const &content, PreprocessedFile &preprocessed)
Parsing function.
CU_API PreprocessedFile processFile (String const &appName, Path const &path)
Parsing function.
CU_API PreprocessedFile processFile (Path const &path)
Parsing function.
CU_API PreprocessedFile processFile (Path const &path, String const &content)
Parsing function.
CU_API bool parseFile (String const &appName, Path const &path)
Parsing function.
CU_API bool parseFile (Path const &path)
Parsing function.
CU_API bool parseFile (Path const &path, String const &content)
Parsing function.
CU_API void parseError (String const &functionName, uint64_t lineIndex, String const &error)
Logs an error in the log file.
CU_API void parseWarning (String const &functionName, uint64_t lineIndex, String const &warning)
Logs a warning in the log file.
CU_API void addParser (SectionId oldSection, SectionId newSection, String const &name, ParserFunction const &function, ParserParameterArray const &params=ParserParameterArray())
adds a parser function to the parsers list.
CU_API void addParser (SectionId section, String const &name, ParserFunction const &function, ParserParameterArray const &params=ParserParameterArray())
adds a parser function to the parsers list.
bool isIgnored () const
Tells if the read lines are to be ignored.
void ignore ()
Increments ignore level.
LoggerInstance & getLogger () const
SectionId getRootSectionId () const
void * getRootBlockContext () const
void validate (PreprocessedFile &preprocessed)
String getSectionName (SectionId section) const
void cleanupParser (PreprocessedFile &preprocessed)
auto const & getAdditionalParsers () const
Additional Inherited Members
Protected Member Functions inherited from castor::OwnedBy< Engine >
OwnedBy (Engine &owner)
Constructor.
Protected Member Functions inherited from castor::FileParser
virtual CU_API bool doDiscardParser (PreprocessedFile &preprocessed, StringView line)
Function called when no parser is found for the line.
Protected Member Functions inherited from castor::NonMovable
NonMovable ()=default
Constructor.
~NonMovable () noexcept=default
Destructor.
Protected Attributes inherited from castor::FileParser
LoggerInstance & m_logger
AttributeParsers m_parsers
bool m_ignored { false }
StrStrMap m_defines
Constructor & Destructor Documentation
SceneFileParser()
C3D_API castor3d::SceneFileParser::SceneFileParser (Engine & engine, ProgressBar * progress = nullptr) explicit
Constructor.
Parameters
[in] engine The engine.
[in,out] progress Optional progress bar.
Member Function Documentation
getRenderWindow()
RenderWindowDesc castor3d::SceneFileParser::getRenderWindow () inline
Returns
The render window defined by the scene.
References castor::DataHolderT< RootContext >::getData().
initialiseParser()
C3D_API castor::FileParserContextUPtr castor3d::SceneFileParser::initialiseParser (castor::Path const & path)
scenesBegin() [1/2]
ScenePtrStrMap::iterator castor3d::SceneFileParser::scenesBegin () inline
References castor::DataHolderT< RootContext >::getData().
scenesBegin() [2/2]
ScenePtrStrMap::const_iterator castor3d::SceneFileParser::scenesBegin () const inline
References castor::DataHolderT< RootContext >::getData().
scenesEnd()
ScenePtrStrMap::const_iterator castor3d::SceneFileParser::scenesEnd () const inline
References castor::DataHolderT< RootContext >::getData().
The documentation for this class was generated from the following file:
Castor3D/Scene/SceneFileParser.hpp