Castor3D: castor3d::ChunkParserBase Class Reference
castor3d::ChunkParserBase Class Reference
#include <ChunkParser.hpp>
Static Public Member Functions
static bool parse (uint8_t *values, size_t size, BinaryChunk &chunk)
Retrieves a value array from a chunk.
Member Function Documentation
parse()
static bool castor3d::ChunkParserBase::parse (uint8_t * values, size_t size, BinaryChunk & chunk) inline static
Retrieves a value array from a chunk.
Parameters
[out] values Receives the parsed values
[out] size The values size
[in] chunk The chunk containing the values
Returns
false if any error occured
References castor3d::BinaryChunk::checkAvailable(), and castor3d::BinaryChunk::get().
Referenced by castor3d::ChunkParser< castor::Path >::parse(), castor3d::ChunkParser< castor::String >::parse(), castor3d::ChunkParser< T >::parse(), and castor3d::ChunkParser< T >::parse().
The documentation for this class was generated from the following file:
Castor3D/Binary/ChunkParser.hpp