Castor3D: castor3d::ConfigurationVisitorBase Class Reference
castor3d::ConfigurationVisitorBase Class Reference abstract
#include <ConfigurationVisitor.hpp>
Classes
struct Config
struct ConfigurationVisitorBlock
Public Types
using Callback = castor::Function< void() >
template<typename ControlT >
using ControlsListT = castor::Vector< castor::Pair< ControlT *, Callback > >
template<typename EnumT >
using OnEnumValueChangeT = castor::Function< void(EnumT oldV, EnumT newV) >
using ControlsList = ControlsListT< bool >
using AtomicControlsList = ControlsListT< std::atomic_bool >
using OnSEnumValueChange = OnEnumValueChangeT< int32_t >
using OnUEnumValueChange = OnEnumValueChangeT< uint32_t >
Public Member Functions
virtual C3D_API ~ConfigurationVisitorBase ()=default
ConfigurationVisitorBlock visit (castor::String const &name, ControlsList const &)
ConfigurationVisitorBlock visit (castor::String const &name, AtomicControlsList const &)
template<typename ControlT = bool>
ConfigurationVisitorBlock visit (castor::String const &name, ControlT *control=nullptr)
virtual C3D_API void visit (ShaderModule const &shader, bool forceProgramsVisit)=0
virtual C3D_API void visit (ProgramModule const &shader, ast::EntryPoint entryPoint, bool forceProgramsVisit)=0
void visit (ShaderModule const &shader)
void visit (ProgramModule const &shader, ast::EntryPoint entryPoint)
void visit (ProgramModule const &shader)
virtual C3D_API void visit (DebugConfig const &debugConfig)=0
void visit (castor::String const &name, crg::ImageViewId const &viewId, VkImageLayout layout, TextureFactors const &factors={})
void visit (castor::String const &name, Texture const &texture, VkImageLayout layout, TextureFactors const &factors={})
virtual C3D_API void visit (castor::String const &name, bool &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, int16_t &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, uint16_t &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, int32_t &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, uint32_t &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, int64_t &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, uint64_t &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, float &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, double &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Angle &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::RgbColour &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::RgbaColour &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::HdrRgbColour &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::HdrRgbaColour &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, ColourWrapper value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point2f &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point2i &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point2ui &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point3f &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point3i &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point3ui &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point4f &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point4i &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point4ui &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Matrix4x4f &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::RangedValue< float > &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::RangedValue< int32_t > &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::RangedValue< uint32_t > &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, float &value, castor::Range< float > const &range, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, int32_t &value, castor::Range< int32_t > const &range, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, uint32_t &value, castor::Range< uint32_t > const &range, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, PassComponentTextureFlag textureFlag, TextureFlagConfiguration &value, uint32_t componentsCount, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, int32_t &enumValue, castor::StringArray const &enumNames, OnSEnumValueChange onChange, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, uint32_t &enumValue, castor::StringArray const &enumNames, OnUEnumValueChange onChange, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, bool &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, int16_t &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, uint16_t &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, int32_t &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, uint32_t &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, int64_t &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, uint64_t &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, float &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, double &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Angle &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::RgbColour &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::RgbaColour &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::HdrRgbColour &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::HdrRgbaColour &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, ColourWrapper value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point2f &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point2i &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point2ui &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point3f &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point3i &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point3ui &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point4f &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point4i &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point4ui &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Matrix4x4f &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::RangedValue< float > &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::RangedValue< int32_t > &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::RangedValue< uint32_t > &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, float &value, castor::Range< float > const &range, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, int32_t &value, castor::Range< int32_t > const &range, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, uint32_t &value, castor::Range< uint32_t > const &range, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, PassComponentTextureFlag textureFlag, TextureFlagConfiguration &value, uint32_t componentsCount, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, int32_t &enumValue, castor::StringArray const &enumNames, OnSEnumValueChange onChange, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, uint32_t &enumValue, castor::StringArray const &enumNames, OnUEnumValueChange onChange, AtomicControlsList controls)=0
template<typename ValueT , typename ControlT = bool>
void visit (castor::String const &name, ValueT &value, ControlT *control=nullptr)
template<typename ControlT = bool>
void visit (castor::String const &name, ColourWrapper value, ControlT *control=nullptr)
template<typename ValueT , typename ControlT = bool>
void visit (castor::String const &name, ValueT &value, castor::Range< ValueT > const &range, ControlT *control=nullptr)
template<typename ControlT = bool>
void visit (castor::String const &name, PassComponentTextureFlag textureFlag, TextureFlagConfiguration &value, uint32_t componentsCount, ControlT *control=nullptr)
template<typename ValueT , typename ControlT = bool*>
void visit (castor::String const &name, ValueT &enumValue, castor::StringArray const &enumNames, OnEnumValueChangeT< ValueT > onChange, ControlT control=ControlT{})
template<typename TypeT , typename ControlT , typename ... ParamsT>
void visit (castor::String const &name, castor::ChangeTrackedT< TypeT, ControlT > &value, ParamsT &&... params)
template<typename TypeT , typename ControlT , typename ... ParamsT>
void visit (castor::String const &name, castor::GroupChangeTrackedT< TypeT, ControlT > &value, ParamsT &&... params)
Static Public Member Functions
template<typename ControlT >
static ControlsListT< ControlT > makeControlsList (ControlT *control)
template<typename ControlT >
static ControlsListT< ControlT > makeControlsList (ControlsListT< ControlT > controls)
Public Attributes
Config const config
Protected Member Functions
ConfigurationVisitorBase (Config config={ false })
ConfigurationVisitorBlock doPushConfigurationBlock (castor::String const &category)
virtual C3D_API bool doFilter (crg::ImageViewId const &viewId, TextureFactors const &factors) const =0
virtual C3D_API castor::RawUniquePtr< ConfigurationVisitorBase > doGetSubConfiguration (castor::String const &category)=0
Member Typedef Documentation
AtomicControlsList
using castor3d::ConfigurationVisitorBase::AtomicControlsList = ControlsListT< std::atomic_bool >
Callback
using castor3d::ConfigurationVisitorBase::Callback = castor::Function< void() >
ControlsList
using castor3d::ConfigurationVisitorBase::ControlsList = ControlsListT< bool >
ControlsListT
template<typename ControlT > using castor3d::ConfigurationVisitorBase::ControlsListT = castor::Vector< castor::Pair< ControlT *, Callback > >
OnEnumValueChangeT
template<typename EnumT > using castor3d::ConfigurationVisitorBase::OnEnumValueChangeT = castor::Function< void(EnumT oldV, EnumT newV) >
OnSEnumValueChange
using castor3d::ConfigurationVisitorBase::OnSEnumValueChange = OnEnumValueChangeT< int32_t >
OnUEnumValueChange
using castor3d::ConfigurationVisitorBase::OnUEnumValueChange = OnEnumValueChangeT< uint32_t >
Constructor & Destructor Documentation
ConfigurationVisitorBase()
castor3d::ConfigurationVisitorBase::ConfigurationVisitorBase (Config config = { false }) inline explicit protected
~ConfigurationVisitorBase()
virtual C3D_API castor3d::ConfigurationVisitorBase::~ConfigurationVisitorBase () virtual default
Member Function Documentation
doFilter()
virtual C3D_API bool castor3d::ConfigurationVisitorBase::doFilter (crg::ImageViewId const & viewId, TextureFactors const & factors) const protected pure virtual
Implemented in castor3d::ConfigurationVisitor.
doGetSubConfiguration()
virtual C3D_API castor::RawUniquePtr< ConfigurationVisitorBase > castor3d::ConfigurationVisitorBase::doGetSubConfiguration (castor::String const & category) protected pure virtual
Referenced by doPushConfigurationBlock().
doPushConfigurationBlock()
ConfigurationVisitorBlock castor3d::ConfigurationVisitorBase::doPushConfigurationBlock (castor::String const & category) inline protected
References doGetSubConfiguration().
Referenced by visit(), and visit().
makeControlsList() [1/2]
template<typename ControlT > static ControlsListT< ControlT > castor3d::ConfigurationVisitorBase::makeControlsList (ControlsListT< ControlT > controls) inline static
makeControlsList() [2/2]
template<typename ControlT > static ControlsListT< ControlT > castor3d::ConfigurationVisitorBase::makeControlsList (ControlT * control) inline static
Referenced by visit(), visit(), visit(), visit(), and visit().
visit() [1/86]
ConfigurationVisitorBlock castor3d::ConfigurationVisitorBase::visit (castor::String const & name, AtomicControlsList const &) inline
References doPushConfigurationBlock().
visit() [2/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, bool & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [3/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, bool & value, ControlsList controls) pure virtual
name Values.
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [4/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::Angle & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [5/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::Angle & value, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [6/86]
template<typename TypeT , typename ControlT , typename ... ParamsT> void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::ChangeTrackedT< TypeT, ControlT > & value, ParamsT &&... params) inline
References visit().
visit() [7/86]
template<typename TypeT , typename ControlT , typename ... ParamsT> void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::GroupChangeTrackedT< TypeT, ControlT > & value, ParamsT &&... params) inline
References visit().
visit() [8/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::HdrRgbaColour & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [9/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::HdrRgbaColour & value, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [10/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::HdrRgbColour & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [11/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::HdrRgbColour & value, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [12/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::Matrix4x4f & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [13/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::Matrix4x4f & value, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [14/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::Point2f & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [15/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::Point2f & value, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [16/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::Point2i & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [17/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::Point2i & value, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [18/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::Point2ui & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [19/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::Point2ui & value, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [20/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::Point3f & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [21/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::Point3f & value, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [22/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::Point3i & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [23/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::Point3i & value, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [24/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::Point3ui & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [25/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::Point3ui & value, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [26/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::Point4f & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [27/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::Point4f & value, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [28/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::Point4i & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [29/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::Point4i & value, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [30/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::Point4ui & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [31/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::Point4ui & value, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [32/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::RangedValue< float > & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [33/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::RangedValue< float > & value, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [34/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::RangedValue< int32_t > & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [35/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::RangedValue< int32_t > & value, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [36/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::RangedValue< uint32_t > & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [37/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::RangedValue< uint32_t > & value, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [38/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::RgbaColour & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [39/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::RgbaColour & value, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [40/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::RgbColour & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [41/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, castor::RgbColour & value, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [42/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, ColourWrapper value, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [43/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, ColourWrapper value, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [44/86]
template<typename ControlT = bool> void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, ColourWrapper value, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [45/86]
ConfigurationVisitorBlock castor3d::ConfigurationVisitorBase::visit (castor::String const & name, ControlsList const &) inline
name Names.
References doPushConfigurationBlock().
Referenced by visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
visit() [46/86]
template<typename ControlT = bool> ConfigurationVisitorBlock castor3d::ConfigurationVisitorBase::visit (castor::String const & name, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [47/86]
void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, crg::ImageViewId const & viewId, VkImageLayout layout, TextureFactors const & factors = {}) inline
name Intermediate images.
visit() [48/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, double & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [49/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, double & value, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [50/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, float & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [51/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, float & value, castor::Range< float > const & range, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [52/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, float & value, castor::Range< float > const & range, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [53/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, float & value, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [54/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, int16_t & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [55/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, int16_t & value, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [56/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, int32_t & enumValue, castor::StringArray const & enumNames, OnSEnumValueChange onChange, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [57/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, int32_t & enumValue, castor::StringArray const & enumNames, OnSEnumValueChange onChange, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [58/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, int32_t & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [59/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, int32_t & value, castor::Range< int32_t > const & range, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [60/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, int32_t & value, castor::Range< int32_t > const & range, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [61/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, int32_t & value, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [62/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, int64_t & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [63/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, int64_t & value, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [64/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, PassComponentTextureFlag textureFlag, TextureFlagConfiguration & value, uint32_t componentsCount, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [65/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, PassComponentTextureFlag textureFlag, TextureFlagConfiguration & value, uint32_t componentsCount, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [66/86]
template<typename ControlT = bool> void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, PassComponentTextureFlag textureFlag, TextureFlagConfiguration & value, uint32_t componentsCount, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [67/86]
void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, Texture const & texture, VkImageLayout layout, TextureFactors const & factors = {}) inline
visit() [68/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, uint16_t & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [69/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, uint16_t & value, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [70/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, uint32_t & enumValue, castor::StringArray const & enumNames, OnUEnumValueChange onChange, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [71/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, uint32_t & enumValue, castor::StringArray const & enumNames, OnUEnumValueChange onChange, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [72/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, uint32_t & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [73/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, uint32_t & value, castor::Range< uint32_t > const & range, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [74/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, uint32_t & value, castor::Range< uint32_t > const & range, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [75/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, uint32_t & value, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [76/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, uint64_t & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [77/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, uint64_t & value, ControlsList controls) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [78/86]
template<typename ValueT , typename ControlT = bool*> void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, ValueT & enumValue, castor::StringArray const & enumNames, OnEnumValueChangeT< ValueT > onChange, ControlT control = ControlT{}) inline
visit() [79/86]
template<typename ValueT , typename ControlT = bool> void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, ValueT & value, castor::Range< ValueT > const & range, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [80/86]
template<typename ValueT , typename ControlT = bool> void castor3d::ConfigurationVisitorBase::visit (castor::String const & name, ValueT & value, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [81/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (DebugConfig const & debugConfig) pure virtual
name Debug configuration.
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [82/86]
void castor3d::ConfigurationVisitorBase::visit (ProgramModule const & shader) inline
References castor3d::ConfigurationVisitorBase::Config::allowProgramsVisit, castor3d::ProgramModule::compiled, config, castor3d::getEntryPointType(), and visit().
visit() [83/86]
void castor3d::ConfigurationVisitorBase::visit (ProgramModule const & shader, ast::EntryPoint entryPoint) inline
References castor3d::ConfigurationVisitorBase::Config::allowProgramsVisit, castor3d::ProgramModule::compiled, config, castor3d::getShaderStage(), castor3d::ProgramModule::shader, and visit().
visit() [84/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (ProgramModule const & shader, ast::EntryPoint entryPoint, bool forceProgramsVisit) pure virtual
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
visit() [85/86]
void castor3d::ConfigurationVisitorBase::visit (ShaderModule const & shader) inline
References castor3d::ConfigurationVisitorBase::Config::allowProgramsVisit, castor3d::ShaderModule::compiled, config, castor3d::ShaderModule::shader, castor3d::ShaderModule::source, castor3d::SpirVShader::spirv, castor3d::SpirVShader::text, and visit().
visit() [86/86]
virtual C3D_API void castor3d::ConfigurationVisitorBase::visit (ShaderModule const & shader, bool forceProgramsVisit) pure virtual
name Shader source.
Implemented in castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::BackgroundVisitor, castor3d::ConfigurationVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, and castor3d::BackgroundVisitor.
Member Data Documentation
config
Config const castor3d::ConfigurationVisitorBase::config
Referenced by visit(), visit(), and visit().
The documentation for this class was generated from the following file:
Castor3D/Miscellaneous/ConfigurationVisitor.hpp