Castor3D: castor3d::ObjectBufferOffset::GpuBufferChunk Struct Reference
castor3d::ObjectBufferOffset::GpuBufferChunk Struct Reference
#include <ObjectBufferOffset.hpp>
Public Member Functions
ashes::BufferBase const & getBuffer () const
bool hasData () const
uint32_t getAskedSize () const
uint32_t getAllocSize () const
template<typename DataT >
uint32_t getCount () const
VkDeviceSize getOffset () const
template<typename DataT >
uint32_t getFirst () const
void reset ()
void createUniformPassBinding (crg::FramePass &pass, uint32_t binding, castor::String const &name) const
void createInputStoragePassBinding (crg::FramePass &pass, uint32_t binding, castor::String const &name) const
void createInOutStoragePassBinding (crg::FramePass &pass, uint32_t binding, castor::String const &name) const
void createOutputStoragePassBinding (crg::FramePass &pass, uint32_t binding, castor::String const &name) const
ashes::WriteDescriptorSet getUniformBinding (uint32_t binding) const
ashes::WriteDescriptorSet getStorageBinding (uint32_t binding) const
Public Attributes
GpuPackedBaseBuffer * buffer {}
MemChunk chunk {}
Member Function Documentation
createInOutStoragePassBinding()
void castor3d::ObjectBufferOffset::GpuBufferChunk::createInOutStoragePassBinding (crg::FramePass & pass, uint32_t binding, castor::String const & name) const inline
References castor3d::createInOutStoragePassBinding(), getAskedSize(), getBuffer(), and getOffset().
Referenced by castor3d::ObjectBufferOffset::createInOutStoragePassBinding().
createInputStoragePassBinding()
void castor3d::ObjectBufferOffset::GpuBufferChunk::createInputStoragePassBinding (crg::FramePass & pass, uint32_t binding, castor::String const & name) const inline
References castor3d::createInputStoragePassBinding(), getAskedSize(), getBuffer(), and getOffset().
Referenced by castor3d::ObjectBufferOffset::createInputStoragePassBinding().
createOutputStoragePassBinding()
void castor3d::ObjectBufferOffset::GpuBufferChunk::createOutputStoragePassBinding (crg::FramePass & pass, uint32_t binding, castor::String const & name) const inline
References castor3d::createOutputStoragePassBinding(), getAskedSize(), getBuffer(), and getOffset().
Referenced by castor3d::ObjectBufferOffset::createOutputStoragePassBinding().
createUniformPassBinding()
void castor3d::ObjectBufferOffset::GpuBufferChunk::createUniformPassBinding (crg::FramePass & pass, uint32_t binding, castor::String const & name) const inline
References castor3d::createUniformPassBinding(), getAskedSize(), getBuffer(), and getOffset().
Referenced by castor3d::ObjectBufferOffset::createUniformPassBinding().
getAllocSize()
uint32_t castor3d::ObjectBufferOffset::GpuBufferChunk::getAllocSize () const inline
References chunk, and castor3d::MemChunk::size.
getAskedSize()
uint32_t castor3d::ObjectBufferOffset::GpuBufferChunk::getAskedSize () const inline
References castor3d::MemChunk::askedSize, and chunk.
Referenced by createInOutStoragePassBinding(), createInputStoragePassBinding(), createOutputStoragePassBinding(), createUniformPassBinding(), castor3d::ObjectBufferOffset::getAskedSize(), getCount(), getStorageBinding(), and getUniformBinding().
getBuffer()
ashes::BufferBase const & castor3d::ObjectBufferOffset::GpuBufferChunk::getBuffer () const inline
References buffer, and castor3d::GpuBaseBufferT< AllocatorT >::getBuffer().
Referenced by createInOutStoragePassBinding(), createInputStoragePassBinding(), createOutputStoragePassBinding(), createUniformPassBinding(), castor3d::ObjectBufferOffset::getBuffer(), getStorageBinding(), and getUniformBinding().
getCount()
template<typename DataT > uint32_t castor3d::ObjectBufferOffset::GpuBufferChunk::getCount () const inline
References getAskedSize().
Referenced by castor3d::ObjectBufferOffset::getCount().
getFirst()
template<typename DataT > uint32_t castor3d::ObjectBufferOffset::GpuBufferChunk::getFirst () const inline
References getOffset().
Referenced by castor3d::ObjectBufferOffset::getFirst().
getOffset()
VkDeviceSize castor3d::ObjectBufferOffset::GpuBufferChunk::getOffset () const inline
References chunk, and castor3d::MemChunk::offset.
Referenced by createInOutStoragePassBinding(), createInputStoragePassBinding(), createOutputStoragePassBinding(), createUniformPassBinding(), getFirst(), castor3d::ObjectBufferOffset::getOffset(), getStorageBinding(), and getUniformBinding().
getStorageBinding()
ashes::WriteDescriptorSet castor3d::ObjectBufferOffset::GpuBufferChunk::getStorageBinding (uint32_t binding) const inline
References getAskedSize(), getBuffer(), and getOffset().
Referenced by castor3d::ObjectBufferOffset::getStorageBinding().
getUniformBinding()
ashes::WriteDescriptorSet castor3d::ObjectBufferOffset::GpuBufferChunk::getUniformBinding (uint32_t binding) const inline
References getAskedSize(), getBuffer(), and getOffset().
Referenced by castor3d::ObjectBufferOffset::getUniformBinding().
hasData()
bool castor3d::ObjectBufferOffset::GpuBufferChunk::hasData () const inline
References castor3d::MemChunk::askedSize, and chunk.
Referenced by castor3d::ObjectBufferOffset::hasData().
reset()
void castor3d::ObjectBufferOffset::GpuBufferChunk::reset () inline
References castor3d::MemChunk::askedSize, buffer, chunk, castor3d::MemChunk::offset, and castor3d::MemChunk::size.
Member Data Documentation
buffer
GpuPackedBaseBuffer* castor3d::ObjectBufferOffset::GpuBufferChunk::buffer {}
Referenced by getBuffer(), and reset().
chunk
MemChunk castor3d::ObjectBufferOffset::GpuBufferChunk::chunk {}
Referenced by getAllocSize(), getAskedSize(), getOffset(), hasData(), and reset().
The documentation for this struct was generated from the following file:
Castor3D/Buffer/ObjectBufferOffset.hpp