Castor3D: castor3d::SubmeshComponent Class Reference
castor3d::SubmeshComponent Class Reference abstract
#include <SubmeshComponent.hpp>
Public Member Functions
C3D_API SubmeshComponent (Submesh &submesh, castor::String const &type, SubmeshComponentDataUPtr data={}, castor::StringArray deps={})
Constructor.
virtual C3D_API ~SubmeshComponent () noexcept=default
Destructor.
virtual C3D_API bool writeText (castor::String const &tabs, castor::Path const &folder, castor::String const &subfolder, castor::StringStream &file) const
Writes the component content to text.
virtual C3D_API void accept (ConfigurationVisitorBase &vis)
ConfigurationVisitorBase acceptance function.
virtual C3D_API SubmeshComponentFlag getSubmeshFlags () const noexcept
virtual C3D_API SubmeshComponentUPtr clone (Submesh &submesh) const =0
Clones this component into given submesh.
virtual C3D_API ProgramFlags getProgramFlags (Pass const &pass) const noexcept
C3D_API void initialiseRenderData ()
Initialises the render data specific for this component's submesh.
Getters.
castor::String const & getType () const noexcept
castor::StringArray const & getDependencies () const noexcept
SubmeshComponentPlugin const & getPlugin () const noexcept
SubmeshComponentID getId () const noexcept
SubmeshComponentDataRPtr getBaseData () const noexcept
SubmeshRenderData * getRenderData () const noexcept
template<typename DataT >
DataT * getDataT () const noexcept
template<typename DataT >
DataT * getRenderDataT () const noexcept
Public Member Functions inherited from castor::OwnedBy< Submesh >
Submesh * getOwner () const
Protected Attributes
SubmeshComponentDataUPtr m_data
SubmeshRenderDataPtr m_renderData
Additional Inherited Members
Protected Member Functions inherited from castor::OwnedBy< Submesh >
OwnedBy (Submesh &owner)
Constructor.
Constructor & Destructor Documentation
SubmeshComponent()
C3D_API castor3d::SubmeshComponent::SubmeshComponent (Submesh & submesh, castor::String const & type, SubmeshComponentDataUPtr data = {}, castor::StringArray deps = {})
Constructor.
Parameters
[in] submesh The parent submesh.
[in] type The component type.
[in] data The component data.
[in] deps The components this one depends on.
~SubmeshComponent()
virtual C3D_API castor3d::SubmeshComponent::~SubmeshComponent () virtual default noexcept
Destructor.
Member Function Documentation
accept()
virtual C3D_API void castor3d::SubmeshComponent::accept (ConfigurationVisitorBase & vis) inline virtual
ConfigurationVisitorBase acceptance function.
Parameters
[in,out] vis The ... visitor.
clone()
virtual C3D_API SubmeshComponentUPtr castor3d::SubmeshComponent::clone (Submesh & submesh) const pure virtual
Clones this component into given submesh.
Parameters
[in,out] submesh Receives the cloned component.
Implemented in castor3d::BaseDataComponentT< SubmeshDataT, DataT >, castor3d::DefaultRenderComponent, castor3d::InstantiationComponent, castor3d::LinesMapping, castor3d::MeshletComponent, castor3d::MorphComponent, castor3d::PassMasksComponent, castor3d::SkinComponent, and castor3d::TriFaceMapping.
getBaseData()
SubmeshComponentDataRPtr castor3d::SubmeshComponent::getBaseData () const inline noexcept
getDataT()
template<typename DataT > DataT * castor3d::SubmeshComponent::getDataT () const inline noexcept
getDependencies()
castor::StringArray const & castor3d::SubmeshComponent::getDependencies () const inline noexcept
getId()
SubmeshComponentID castor3d::SubmeshComponent::getId () const inline noexcept
Referenced by castor3d::PassMasksComponent::getSubmeshFlags(), and castor3d::SkinComponent::getSubmeshFlags().
getPlugin()
SubmeshComponentPlugin const & castor3d::SubmeshComponent::getPlugin () const inline noexcept
getProgramFlags()
virtual C3D_API ProgramFlags castor3d::SubmeshComponent::getProgramFlags (Pass const & pass) const inline virtual noexcept
Returns
The program flags.
Parameters
[in] pass The material pass.
Reimplemented in castor3d::InstantiationComponent, and castor3d::MeshletComponent.
getRenderData()
SubmeshRenderData * castor3d::SubmeshComponent::getRenderData () const inline noexcept
getRenderDataT()
template<typename DataT > DataT * castor3d::SubmeshComponent::getRenderDataT () const inline noexcept
getSubmeshFlags()
virtual C3D_API SubmeshComponentFlag castor3d::SubmeshComponent::getSubmeshFlags () const inline virtual noexcept
Returns
The submesh flags.
Reimplemented in castor3d::PassMasksComponent, and castor3d::SkinComponent.
References castor3d::makeSubmeshComponentFlag().
getType()
castor::String const & castor3d::SubmeshComponent::getType () const inline noexcept
initialiseRenderData()
C3D_API void castor3d::SubmeshComponent::initialiseRenderData ()
Initialises the render data specific for this component's submesh.
writeText()
virtual C3D_API bool castor3d::SubmeshComponent::writeText (castor::String const & tabs, castor::Path const & folder, castor::String const & subfolder, castor::StringStream & file) const inline virtual
Writes the component content to text.
Parameters
[in] tabs The current tabulation level.
[in] folder The resources folder.
[in] subfolder The resources subfolder.
[in,out] file The output file.
Member Data Documentation
m_data
SubmeshComponentDataUPtr castor3d::SubmeshComponent::m_data protected
m_renderData
SubmeshRenderDataPtr castor3d::SubmeshComponent::m_renderData protected
The documentation for this class was generated from the following file:
Castor3D/Model/Mesh/Submesh/Component/SubmeshComponent.hpp