Castor3D: castor3d::Scene Class Reference
castor3d::Scene Class Reference
Scene handler class.
Classes
class TextWriter
Scene loader.
Public Member Functions
C3D_API Scene (castor::String const &name, Engine &engine)
Constructor.
C3D_API ~Scene ()
Destructor.
C3D_API void initialise ()
Initialises the scene.
C3D_API void cleanup ()
Clears the maps, leaves the root nodes.
C3D_API void renderBackground (castor::Size const &size, Camera const &camera)
Renders the scene background (skybox or image).
C3D_API void update ()
Updates the scene before render.
C3D_API bool setBackground (castor::Path const &folder, castor::Path const &relative)
Sets the background image for the scene.
C3D_API bool setForeground (SkyboxUPtr &&skybox)
Sets the skybox for the scene.
C3D_API bool importExternal (castor::Path const &fileName, Importer &importer)
Imports a scene from an foreign file.
C3D_API void merge (SceneSPtr scene)
Merges the content of the given scene to this scene.
C3D_API uint32_t getVertexCount () const
Retrieves the vertices count.
C3D_API uint32_t getFaceCount () const
Retrieves the faces count.
C3D_API SceneFlags getFlags () const
C3D_API bool hasShadows () const
C3D_API void createEnvironmentMap (SceneNode &node)
C3D_API bool hasEnvironmentMap (SceneNode const &node) const
C3D_API EnvironmentMap & getEnvironmentMap (SceneNode const &node)
C3D_API IblTextures const & getIbl (SceneNode const &node) const
C3D_API Skybox const & getSkybox () const
std::vector< std::reference_wrapper< EnvironmentMap > > & getEnvironmentMaps ()
std::vector< std::reference_wrapper< EnvironmentMap > > const & getEnvironmentMaps () const
void setBackgroundColour (castor::RgbColour const &value)
Sets the background colour.
castor::RgbColour const & getBackgroundColour () const
SceneNodeSPtr getRootNode () const
SceneNodeSPtr getCameraRootNode () const
SceneNodeSPtr getObjectRootNode () const
TextureLayoutSPtr getBackgroundImage () const
bool hasChanged () const
void setChanged ()
Sets the scene changed status to true.
castor::RgbColour const & getAmbientLight () const
void setAmbientLight (castor::RgbColour const &value)
Sets the ambient light colour.
bool hasSkybox () const
Fog const & getFog () const
Fog & getFog ()
Shadow const & getShadow () const
Shadow & getShadow ()
MaterialType getMaterialsType () const
void setMaterialsType (MaterialType value)
Sets the materials type.
FrameListener const & getListener () const
FrameListener & getListener ()
bool isInitialised () const
void setExposure (float value)
Sets the exposure value.
void setGamma (float value)
Sets the gamma correction value.
HdrConfig const & getHdrConfig () const
bool needsSubsurfaceScattering () const
bool hasOpaqueObjects () const
bool hasTransparentObjects () const
Public Attributes
OnSceneChanged onChanged
OnSceneUpdate onUpdate
Static Public Attributes
static castor::String CameraRootNode
static castor::String ObjectRootNode
static castor::String RootNode
Detailed Description
Scene handler class.
Author
Sylvain DOREMUS
Version
0.1
Date
09/02/2010
Remarks
A scene is a collection of lights, scene nodes and geometries.
It has at least one camera to render it
Constructor & Destructor Documentation
Scene()
C3D_API castor3d::Scene::Scene (castor::String const & name, Engine & engine)
Constructor.
Parameters
[in] name The scene name
[in] engine The core engine
~Scene()
C3D_API castor3d::Scene::~Scene ()
Destructor.
Member Function Documentation
cleanup()
C3D_API void castor3d::Scene::cleanup ()
Clears the maps, leaves the root nodes.
createEnvironmentMap()
C3D_API void castor3d::Scene::createEnvironmentMap (SceneNode & node)
Returns
Creates a reflection map for given node.
Parameters
[in] node The scene node from which the reflection map is generated.
getAmbientLight()
castor::RgbColour const& castor3d::Scene::getAmbientLight () const inline
Returns
The ambient light colour
getBackgroundColour()
castor::RgbColour const& castor3d::Scene::getBackgroundColour () const inline
Returns
The background colour
getBackgroundImage()
TextureLayoutSPtr castor3d::Scene::getBackgroundImage () const inline
Returns
The scene background image.
getCameraRootNode()
SceneNodeSPtr castor3d::Scene::getCameraRootNode () const inline
Returns
The cameras root node.
getEnvironmentMap()
C3D_API EnvironmentMap& castor3d::Scene::getEnvironmentMap (SceneNode const & node)
Remarks
Call hasEnvironmentMap before calling this function (since this one returns a reference to an existing EnvironmentMap).
Returns
Retrieves the reflection map for given node.
Parameters
[in] node The scene node.
Referenced by castor3d::doBindPass().
getEnvironmentMaps() [1/2]
std::vector< std::reference_wrapper< EnvironmentMap > >& castor3d::Scene::getEnvironmentMaps () inline
Returns
The reflection maps list.
getEnvironmentMaps() [2/2]
std::vector< std::reference_wrapper< EnvironmentMap > > const& castor3d::Scene::getEnvironmentMaps () const inline
Returns
The reflection maps list.
getFaceCount()
C3D_API uint32_t castor3d::Scene::getFaceCount () const
Retrieves the faces count.
Returns
The value
getFlags()
C3D_API SceneFlags castor3d::Scene::getFlags () const
Returns
The scene flags.
getFog() [1/2]
Fog const& castor3d::Scene::getFog () const inline
Returns
The fog's parameters.
getFog() [2/2]
Fog& castor3d::Scene::getFog () inline
Returns
The fog's parameters.
getHdrConfig()
HdrConfig const& castor3d::Scene::getHdrConfig () const inline
Returns
The HDR configuration.
getIbl()
C3D_API IblTextures const& castor3d::Scene::getIbl (SceneNode const & node) const
Returns
the IBL textures for given node, the skybox's one if no environment map exists for this SceneNode.
Parameters
[in] node The scene node.
Referenced by castor3d::doFillShaderPbrMaps().
getListener() [1/2]
FrameListener const& castor3d::Scene::getListener () const inline
Returns
The scene's frame listener.
getListener() [2/2]
FrameListener& castor3d::Scene::getListener () inline
Returns
The scene's frame listener.
getMaterialsType()
MaterialType castor3d::Scene::getMaterialsType () const inline
Returns
The materials type.
getObjectRootNode()
SceneNodeSPtr castor3d::Scene::getObjectRootNode () const inline
Returns
The objects root node
getRootNode()
SceneNodeSPtr castor3d::Scene::getRootNode () const inline
Returns
The root node
getShadow() [1/2]
Shadow const& castor3d::Scene::getShadow () const inline
Returns
The shadows parameters.
getShadow() [2/2]
Shadow& castor3d::Scene::getShadow () inline
Returns
The shadows parameters.
getSkybox()
C3D_API Skybox const& castor3d::Scene::getSkybox () const
Returns
The skybox.
Referenced by castor3d::doFillShaderPbrMaps().
getVertexCount()
C3D_API uint32_t castor3d::Scene::getVertexCount () const
Retrieves the vertices count.
Returns
The value
hasChanged()
bool castor3d::Scene::hasChanged () const inline
Returns
The scene change status.
hasEnvironmentMap()
C3D_API bool castor3d::Scene::hasEnvironmentMap (SceneNode const & node) const
Returns
Tells if there is a reflection map for given node.
Parameters
[in] node The scene node.
hasOpaqueObjects()
bool castor3d::Scene::hasOpaqueObjects () const inline
Returns
Tells if the scene has opaque objects.
hasShadows()
C3D_API bool castor3d::Scene::hasShadows () const
Returns
Tells if the scene has a shadow projecting light.
hasSkybox()
bool castor3d::Scene::hasSkybox () const inline
Returns
true if the skybox is defined.
hasTransparentObjects()
bool castor3d::Scene::hasTransparentObjects () const inline
Returns
Tells if the scene has opaque objects.
importExternal()
C3D_API bool castor3d::Scene::importExternal (castor::Path const & fileName, Importer & importer)
Imports a scene from an foreign file.
Parameters
[in] fileName file to read from
[in] importer The importer, which is in charge of loading the scene
Returns
true if successful, false if not
initialise()
C3D_API void castor3d::Scene::initialise ()
Initialises the scene.
isInitialised()
bool castor3d::Scene::isInitialised () const inline
Returns
true if the scene is initialised.
merge()
C3D_API void castor3d::Scene::merge (SceneSPtr scene)
Merges the content of the given scene to this scene.
Parameters
[in] scene The scene to merge into this one
needsSubsurfaceScattering()
bool castor3d::Scene::needsSubsurfaceScattering () const inline
Returns
Tells if the scene needs a subsurface scattering pass.
renderBackground()
C3D_API void castor3d::Scene::renderBackground (castor::Size const & size, Camera const & camera)
Renders the scene background (skybox or image).
Parameters
[in] size The target dimensions.
[in] camera The current camera.
setAmbientLight()
void castor3d::Scene::setAmbientLight (castor::RgbColour const & value) inline
Sets the ambient light colour.
Parameters
[in] value The new value.
setBackground()
C3D_API bool castor3d::Scene::setBackground (castor::Path const & folder, castor::Path const & relative)
Sets the background image for the scene.
Parameters
[in] folder The folder containing the image.
[in] relative The image file path, relative to folder.
setBackgroundColour()
void castor3d::Scene::setBackgroundColour (castor::RgbColour const & value) inline
Sets the background colour.
Parameters
[in] value The new colour
setChanged()
void castor3d::Scene::setChanged () inline
Sets the scene changed status to true.
References onChanged.
setExposure()
void castor3d::Scene::setExposure (float value) inline
Sets the exposure value.
Parameters
[in] value The new value.
References castor3d::HdrConfig::setExposure().
setForeground()
C3D_API bool castor3d::Scene::setForeground (SkyboxUPtr && skybox)
Sets the skybox for the scene.
Parameters
[in] skybox The skybox.
setGamma()
void castor3d::Scene::setGamma (float value) inline
Sets the gamma correction value.
Parameters
[in] value The new value.
References castor3d::HdrConfig::setGamma().
setMaterialsType()
void castor3d::Scene::setMaterialsType (MaterialType value) inline
Sets the materials type.
Parameters
[in] value The new value.
update()
C3D_API void castor3d::Scene::update ()
Updates the scene before render.
Member Data Documentation
CameraRootNode
castor::String castor3d::Scene::CameraRootNode static
The cameras root node name.
ObjectRootNode
castor::String castor3d::Scene::ObjectRootNode static
The objects root node name.
onChanged
OnSceneChanged castor3d::Scene::onChanged mutable
The signal raised when the scene has changed.
Referenced by setChanged().
onUpdate
OnSceneUpdate castor3d::Scene::onUpdate mutable
The signal raised when the scene is updating.
RootNode
castor::String castor3d::Scene::RootNode static
The root node name.
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Scene/Scene.hpp