Castor3D: castor3d::shader::MorphingWeightsData Struct Reference
castor3d::shader::MorphingWeightsData Struct Reference
#include <MorphingUbo.hpp>
Public Member Functions
C3D_API MorphingWeightsData (sdw::ShaderWriter &writer, ast::expr::ExprPtr expr, bool enabled)
SDW_DeclStructInstance (C3D_API, MorphingWeightsData)
C3D_API void morph (sdw::Array< shader::MorphTargetsData > const &targets, sdw::UInt vertexId, sdw::Vec4 &pos, sdw::Vec3 &uvw0, sdw::Vec3 &uvw1, sdw::Vec3 &uvw2, sdw::Vec3 &uvw3, sdw::Vec3 &col) const
C3D_API void morph (sdw::Array< shader::MorphTargetsData > const &targets, sdw::UInt vertexId, sdw::Vec4 &pos, sdw::Vec4 &nml, sdw::Vec3 &uvw0, sdw::Vec3 &uvw1, sdw::Vec3 &uvw2, sdw::Vec3 &uvw3, sdw::Vec3 &col) const
C3D_API void morph (sdw::Array< shader::MorphTargetsData > const &targets, sdw::UInt vertexId, sdw::Vec4 &pos, sdw::Vec4 &nml, sdw::Vec4 &tan, sdw::Vec3 &uvw0, sdw::Vec3 &uvw1, sdw::Vec3 &uvw2, sdw::Vec3 &uvw3, sdw::Vec3 &col) const
C3D_API void morph (sdw::Array< shader::MorphTargetsData > const &targets, sdw::UInt vertexId, sdw::Vec4 &pos, sdw::Vec4 &nml, sdw::Vec4 &tan, sdw::Vec4 &bit, sdw::Vec3 &uvw0, sdw::Vec3 &uvw1, sdw::Vec3 &uvw2, sdw::Vec3 &uvw3, sdw::Vec3 &col) const
C3D_API void morph (sdw::ArrayStorageBufferT< shader::MorphTargetsData > const &targets, sdw::UInt vertexId, sdw::Vec4 &pos, sdw::Vec4 &nml, sdw::Vec4 &tan, sdw::Vec3 &uvw0, sdw::Vec3 &uvw1, sdw::Vec3 &uvw2, sdw::Vec3 &uvw3, sdw::Vec3 &col) const
C3D_API void morph (sdw::ArrayStorageBufferT< shader::MorphTargetsData > const &targets, sdw::UInt vertexId, sdw::Vec4 &pos, sdw::Vec4 &nml, sdw::Vec4 &tan, sdw::Vec4 &bit, sdw::Vec3 &uvw0, sdw::Vec3 &uvw1, sdw::Vec3 &uvw2, sdw::Vec3 &uvw3, sdw::Vec3 &col) const
sdw::UInt index (sdw::UInt const &index) const
sdw::Float weight (sdw::UInt const &index) const
Static Public Member Functions
static ast::type::BaseStructPtr makeType (ast::type::TypesCache &cache)
static C3D_API void morphNoAnim (sdw::ArrayStorageBufferT< shader::MorphTargetsData > const &targets, sdw::UInt vertexId, sdw::Vec4 &pos, sdw::Vec4 &nml, sdw::Vec4 &tan, sdw::Vec4 &bit, sdw::Vec3 &uvw0, sdw::Vec3 &uvw1, sdw::Vec3 &uvw2, sdw::Vec3 &uvw3, sdw::Vec3 &col)
Public Attributes
sdw::UInt morphTargetsCount
Constructor & Destructor Documentation
MorphingWeightsData()
C3D_API castor3d::shader::MorphingWeightsData::MorphingWeightsData (sdw::ShaderWriter & writer, ast::expr::ExprPtr expr, bool enabled)
Member Function Documentation
index()
sdw::UInt castor3d::shader::MorphingWeightsData::index (sdw::UInt const & index) const inline
References index().
Referenced by index(), and weight().
makeType()
static ast::type::BaseStructPtr castor3d::shader::MorphingWeightsData::makeType (ast::type::TypesCache & cache) static
morph() [1/6]
C3D_API void castor3d::shader::MorphingWeightsData::morph (sdw::Array< shader::MorphTargetsData > const & targets, sdw::UInt vertexId, sdw::Vec4 & pos, sdw::Vec3 & uvw0, sdw::Vec3 & uvw1, sdw::Vec3 & uvw2, sdw::Vec3 & uvw3, sdw::Vec3 & col) const
morph() [2/6]
C3D_API void castor3d::shader::MorphingWeightsData::morph (sdw::Array< shader::MorphTargetsData > const & targets, sdw::UInt vertexId, sdw::Vec4 & pos, sdw::Vec4 & nml, sdw::Vec3 & uvw0, sdw::Vec3 & uvw1, sdw::Vec3 & uvw2, sdw::Vec3 & uvw3, sdw::Vec3 & col) const
morph() [3/6]
C3D_API void castor3d::shader::MorphingWeightsData::morph (sdw::Array< shader::MorphTargetsData > const & targets, sdw::UInt vertexId, sdw::Vec4 & pos, sdw::Vec4 & nml, sdw::Vec4 & tan, sdw::Vec3 & uvw0, sdw::Vec3 & uvw1, sdw::Vec3 & uvw2, sdw::Vec3 & uvw3, sdw::Vec3 & col) const
morph() [4/6]
C3D_API void castor3d::shader::MorphingWeightsData::morph (sdw::Array< shader::MorphTargetsData > const & targets, sdw::UInt vertexId, sdw::Vec4 & pos, sdw::Vec4 & nml, sdw::Vec4 & tan, sdw::Vec4 & bit, sdw::Vec3 & uvw0, sdw::Vec3 & uvw1, sdw::Vec3 & uvw2, sdw::Vec3 & uvw3, sdw::Vec3 & col) const
morph() [5/6]
C3D_API void castor3d::shader::MorphingWeightsData::morph (sdw::ArrayStorageBufferT< shader::MorphTargetsData > const & targets, sdw::UInt vertexId, sdw::Vec4 & pos, sdw::Vec4 & nml, sdw::Vec4 & tan, sdw::Vec3 & uvw0, sdw::Vec3 & uvw1, sdw::Vec3 & uvw2, sdw::Vec3 & uvw3, sdw::Vec3 & col) const
morph() [6/6]
C3D_API void castor3d::shader::MorphingWeightsData::morph (sdw::ArrayStorageBufferT< shader::MorphTargetsData > const & targets, sdw::UInt vertexId, sdw::Vec4 & pos, sdw::Vec4 & nml, sdw::Vec4 & tan, sdw::Vec4 & bit, sdw::Vec3 & uvw0, sdw::Vec3 & uvw1, sdw::Vec3 & uvw2, sdw::Vec3 & uvw3, sdw::Vec3 & col) const
morphNoAnim()
static C3D_API void castor3d::shader::MorphingWeightsData::morphNoAnim (sdw::ArrayStorageBufferT< shader::MorphTargetsData > const & targets, sdw::UInt vertexId, sdw::Vec4 & pos, sdw::Vec4 & nml, sdw::Vec4 & tan, sdw::Vec4 & bit, sdw::Vec3 & uvw0, sdw::Vec3 & uvw1, sdw::Vec3 & uvw2, sdw::Vec3 & uvw3, sdw::Vec3 & col) static
SDW_DeclStructInstance()
castor3d::shader::MorphingWeightsData::SDW_DeclStructInstance (C3D_API , MorphingWeightsData)
weight()
sdw::Float castor3d::shader::MorphingWeightsData::weight (sdw::UInt const & index) const inline
References index().
Member Data Documentation
morphTargetsCount
sdw::UInt castor3d::shader::MorphingWeightsData::morphTargetsCount
The documentation for this struct was generated from the following file:
Castor3D/Shader/Ubos/MorphingUbo.hpp