Castor3D: Castor3D::ChunkFillerBase Struct Reference
Castor3D::ChunkFillerBase Struct Reference
Chunk filler.
Public Member Functions
bool operator() (uint8_t const *p_pValues, uint32_t p_uiSize, eCHUNK_TYPE p_eChunkType, BinaryChunk &p_chunk)
Writes a subchunk value into a chunk.
Detailed Description
Chunk filler.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
08/04/2014
Member Function Documentation
operator()()
bool Castor3D::ChunkFillerBase::operator() (uint8_t const * p_pValues, uint32_t p_uiSize, eCHUNK_TYPE p_eChunkType, BinaryChunk & p_chunk) inline
Writes a subchunk value into a chunk.
Parameters
[in] p_tValue The values
[in] p_uiSize The values size
[in] p_eChunkType The subchunk type
[in] p_chunk The chunk
Returns
false if any error occured
References Castor3D::BinaryChunk::AddSubChunk(), and Castor3D::BinaryChunk::SetData().
Referenced by Castor3D::ChunkFiller< T >::operator()(), Castor3D::ChunkFiller< Castor::String >::operator()(), Castor3D::ChunkFiller< Castor::Path >::operator()(), Castor3D::ChunkFiller< Castor::Point2f >::operator()(), Castor3D::ChunkFiller< Castor::Point3f >::operator()(), Castor3D::ChunkFiller< Castor::Point4f >::operator()(), Castor3D::ChunkFiller< Castor::Point2d >::operator()(), Castor3D::ChunkFiller< Castor::Point3d >::operator()(), Castor3D::ChunkFiller< Castor::Point4d >::operator()(), Castor3D::ChunkFiller< Castor::Point2i >::operator()(), Castor3D::ChunkFiller< Castor::Point3i >::operator()(), Castor3D::ChunkFiller< Castor::Point4i >::operator()(), Castor3D::ChunkFiller< Castor::Point2ui >::operator()(), Castor3D::ChunkFiller< Castor::Point3ui >::operator()(), Castor3D::ChunkFiller< Castor::Point4ui >::operator()(), Castor3D::ChunkFiller< Castor::Coords2f >::operator()(), Castor3D::ChunkFiller< Castor::Coords3f >::operator()(), Castor3D::ChunkFiller< Castor::Coords4f >::operator()(), Castor3D::ChunkFiller< Castor::Coords2d >::operator()(), Castor3D::ChunkFiller< Castor::Coords3d >::operator()(), Castor3D::ChunkFiller< Castor::Coords4d >::operator()(), Castor3D::ChunkFiller< Castor::Coords2i >::operator()(), Castor3D::ChunkFiller< Castor::Coords3i >::operator()(), Castor3D::ChunkFiller< Castor::Coords4i >::operator()(), Castor3D::ChunkFiller< Castor::Coords2ui >::operator()(), Castor3D::ChunkFiller< Castor::Coords3ui >::operator()(), Castor3D::ChunkFiller< Castor::Coords4ui >::operator()(), Castor3D::ChunkFiller< Castor::Matrix2x2f >::operator()(), Castor3D::ChunkFiller< Castor::Matrix3x3f >::operator()(), Castor3D::ChunkFiller< Castor::Matrix4x4f >::operator()(), Castor3D::ChunkFiller< Castor::Matrix2x2d >::operator()(), Castor3D::ChunkFiller< Castor::Matrix3x3d >::operator()(), Castor3D::ChunkFiller< Castor::Matrix4x4d >::operator()(), Castor3D::ChunkFiller< Castor::Colour >::operator()(), Castor3D::ChunkFiller< Castor::Size >::operator()(), Castor3D::ChunkFiller< Castor::Position >::operator()(), and Castor3D::ChunkFiller< Castor::Quaternion >::operator()().
The documentation for this struct was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/ChunkFiller.hpp