Castor3D: castor3d::LightPassShadow< LtType > Class Template Reference
castor3d::LightPassShadow< LtType > Class Template Reference
Base class for all light passes with shadow.
Public Types
using my_traits = LightPassShadowTraits< LtType >
using my_light_type = typename my_traits::light_type
using my_pass_type = typename my_traits::light_pass_type
using my_shadow_map_type = typename my_traits::shadow_pass_type
Public Member Functions
LightPassShadow (Engine &engine, FrameBuffer &frameBuffer, FrameBufferAttachment &depthAttach, GpInfoUbo &gpInfoUbo)
Constructor.
void render (castor::Size const &size, GeometryPassResult const &gp, Light const &light, Camera const &camera, bool first, ShadowMap *shadowMapOpt) override
Renders the light pass on currently bound framebuffer.
Detailed Description
template<LightType LtType>
class castor3d::LightPassShadow< LtType >
Base class for all light passes with shadow.
Author
Sylvain DOREMUS
Version
0.10.0
Date
08/06/2017
Member Typedef Documentation
my_light_type
template<LightType LtType> using castor3d::LightPassShadow< LtType >::my_light_type = typename my_traits::light_type
my_pass_type
template<LightType LtType> using castor3d::LightPassShadow< LtType >::my_pass_type = typename my_traits::light_pass_type
my_shadow_map_type
template<LightType LtType> using castor3d::LightPassShadow< LtType >::my_shadow_map_type = typename my_traits::shadow_pass_type
my_traits
template<LightType LtType> using castor3d::LightPassShadow< LtType >::my_traits = LightPassShadowTraits< LtType >
Constructor & Destructor Documentation
LightPassShadow()
template<LightType LtType> castor3d::LightPassShadow< LtType >::LightPassShadow (Engine & engine, FrameBuffer & frameBuffer, FrameBufferAttachment & depthAttach, GpInfoUbo & gpInfoUbo) inline
Constructor.
Parameters
[in] engine The engine.
[in] frameBuffer The target framebuffer.
[in] depthAttach The depth buffer attach.
[in] gpInfoUbo The geometry pass UBO.
Member Function Documentation
render()
template<LightType LtType> void castor3d::LightPassShadow< LtType >::render (castor::Size const & size, GeometryPassResult const & gp, Light const & light, Camera const & camera, bool first, ShadowMap * shadowMapOpt) inline override
Renders the light pass on currently bound framebuffer.
Parameters
[in] size The render area dimensions.
[in] gp The geometry pass result.
[in] light The light.
[in] camera The viewing camera.
[in] first Tells if this is the first light pass (true) or not (false).
[in] shadowMapOpt Optional shadow maps.
References castor3d::ShadowMap::getDepth(), castor3d::ShadowMap::getTexture(), and castor3d::TextureUnit::setIndex().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Technique/Opaque/LightPassShadow.hpp