Castor3D: castor3d::ObjectBufferOffset Struct Reference
castor3d::ObjectBufferOffset Struct Reference
#include <ObjectBufferOffset.hpp>
Classes
struct GpuBufferChunk
Public Member Functions
operator bool () const
GpuBufferChunk & getBufferChunk (SubmeshFlag flag)
GpuBufferChunk const & getBufferChunk (SubmeshFlag flag) const
void reset ()
void directUpload (SubmeshFlag flag, ashes::Queue const &queue, ashes::CommandPool const &commandPool, VkAccessFlags dstAccessFlags, VkPipelineStageFlags dstPipelineFlags)
ashes::BufferBase const & getBuffer (SubmeshFlag flag) const
bool hasData (SubmeshFlag flag) const
template<typename DataT >
castor::ArrayView< DataT > getData (SubmeshFlag flag) const
uint32_t getSize (SubmeshFlag flag) const
template<typename DataT >
uint32_t getCount (SubmeshFlag flag) const
VkDeviceSize getOffset (SubmeshFlag flag) const
template<typename DataT >
uint32_t getFirst (SubmeshFlag flag) const
template<typename IndexT >
uint32_t getFirstIndex () const
template<typename PositionT >
uint32_t getFirstVertex () const
void markDirty (SubmeshFlag flag, VkAccessFlags dstAccessFlags=VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT, VkPipelineStageFlags dstPipelineFlags=VK_PIPELINE_STAGE_VERTEX_INPUT_BIT) const
void createUniformPassBinding (SubmeshFlag flag, crg::FramePass &pass, uint32_t binding, std::string const &name) const
void createInputStoragePassBinding (SubmeshFlag flag, crg::FramePass &pass, uint32_t binding, std::string const &name) const
void createInOutStoragePassBinding (SubmeshFlag flag, crg::FramePass &pass, uint32_t binding, std::string const &name) const
void createOutputStoragePassBinding (SubmeshFlag flag, crg::FramePass &pass, uint32_t binding, std::string const &name) const
ashes::WriteDescriptorSet getUniformBinding (SubmeshFlag flag, uint32_t binding) const
ashes::WriteDescriptorSet getStorageBinding (SubmeshFlag flag, uint32_t binding) const
Public Attributes
size_t hash {}
std::array< GpuBufferChunk, size_t(SubmeshData::eCount) > buffers {}
Member Function Documentation
createInOutStoragePassBinding()
void castor3d::ObjectBufferOffset::createInOutStoragePassBinding (SubmeshFlag flag, crg::FramePass & pass, uint32_t binding, std::string const & name) const inline
References castor3d::ObjectBufferOffset::GpuBufferChunk::createInOutStoragePassBinding(), and getBufferChunk().
createInputStoragePassBinding()
void castor3d::ObjectBufferOffset::createInputStoragePassBinding (SubmeshFlag flag, crg::FramePass & pass, uint32_t binding, std::string const & name) const inline
References castor3d::ObjectBufferOffset::GpuBufferChunk::createInputStoragePassBinding(), and getBufferChunk().
createOutputStoragePassBinding()
void castor3d::ObjectBufferOffset::createOutputStoragePassBinding (SubmeshFlag flag, crg::FramePass & pass, uint32_t binding, std::string const & name) const inline
References castor3d::ObjectBufferOffset::GpuBufferChunk::createOutputStoragePassBinding(), and getBufferChunk().
createUniformPassBinding()
void castor3d::ObjectBufferOffset::createUniformPassBinding (SubmeshFlag flag, crg::FramePass & pass, uint32_t binding, std::string const & name) const inline
References castor3d::ObjectBufferOffset::GpuBufferChunk::createUniformPassBinding(), and getBufferChunk().
directUpload()
void castor3d::ObjectBufferOffset::directUpload (SubmeshFlag flag, ashes::Queue const & queue, ashes::CommandPool const & commandPool, VkAccessFlags dstAccessFlags, VkPipelineStageFlags dstPipelineFlags) inline
References castor3d::ObjectBufferOffset::GpuBufferChunk::directUpload(), and getBufferChunk().
getBuffer()
ashes::BufferBase const & castor3d::ObjectBufferOffset::getBuffer (SubmeshFlag flag) const inline
References castor3d::ObjectBufferOffset::GpuBufferChunk::getBuffer(), and getBufferChunk().
getBufferChunk() [1/2]
GpuBufferChunk & castor3d::ObjectBufferOffset::getBufferChunk (SubmeshFlag flag) inline
References buffers, and castor3d::getIndex().
Referenced by createInOutStoragePassBinding(), createInputStoragePassBinding(), createOutputStoragePassBinding(), createUniformPassBinding(), directUpload(), getBuffer(), getCount(), getData(), getFirst(), getOffset(), getSize(), getStorageBinding(), getUniformBinding(), hasData(), and markDirty().
getBufferChunk() [2/2]
GpuBufferChunk const & castor3d::ObjectBufferOffset::getBufferChunk (SubmeshFlag flag) const inline
References buffers, and castor3d::getIndex().
getCount()
template<typename DataT > uint32_t castor3d::ObjectBufferOffset::getCount (SubmeshFlag flag) const inline
References getBufferChunk(), and castor3d::ObjectBufferOffset::GpuBufferChunk::getCount().
getData()
template<typename DataT > castor::ArrayView< DataT > castor3d::ObjectBufferOffset::getData (SubmeshFlag flag) const inline
References getBufferChunk(), and castor3d::ObjectBufferOffset::GpuBufferChunk::getData().
getFirst()
template<typename DataT > uint32_t castor3d::ObjectBufferOffset::getFirst (SubmeshFlag flag) const inline
References getBufferChunk(), and castor3d::ObjectBufferOffset::GpuBufferChunk::getFirst().
getFirstIndex()
template<typename IndexT > uint32_t castor3d::ObjectBufferOffset::getFirstIndex () const inline
References castor3d::eIndex.
getFirstVertex()
template<typename PositionT > uint32_t castor3d::ObjectBufferOffset::getFirstVertex () const inline
References castor3d::ePositions.
getOffset()
VkDeviceSize castor3d::ObjectBufferOffset::getOffset (SubmeshFlag flag) const inline
References getBufferChunk(), and castor3d::ObjectBufferOffset::GpuBufferChunk::getOffset().
getSize()
uint32_t castor3d::ObjectBufferOffset::getSize (SubmeshFlag flag) const inline
References getBufferChunk(), and castor3d::ObjectBufferOffset::GpuBufferChunk::getSize().
getStorageBinding()
ashes::WriteDescriptorSet castor3d::ObjectBufferOffset::getStorageBinding (SubmeshFlag flag, uint32_t binding) const inline
References getBufferChunk(), and castor3d::ObjectBufferOffset::GpuBufferChunk::getStorageBinding().
getUniformBinding()
ashes::WriteDescriptorSet castor3d::ObjectBufferOffset::getUniformBinding (SubmeshFlag flag, uint32_t binding) const inline
References getBufferChunk(), and castor3d::ObjectBufferOffset::GpuBufferChunk::getUniformBinding().
hasData()
bool castor3d::ObjectBufferOffset::hasData (SubmeshFlag flag) const inline
References getBufferChunk(), and castor3d::ObjectBufferOffset::GpuBufferChunk::hasData().
Referenced by operator bool().
markDirty()
void castor3d::ObjectBufferOffset::markDirty (SubmeshFlag flag, VkAccessFlags dstAccessFlags = VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT, VkPipelineStageFlags dstPipelineFlags = VK_PIPELINE_STAGE_VERTEX_INPUT_BIT) const inline
References getBufferChunk(), and castor3d::ObjectBufferOffset::GpuBufferChunk::markDirty().
operator bool()
castor3d::ObjectBufferOffset::operator bool () const inline explicit
References castor3d::ePositions, and hasData().
reset()
void castor3d::ObjectBufferOffset::reset () inline
References buffers.
Member Data Documentation
buffers
std::array< GpuBufferChunk, size_t(SubmeshData::eCount) > castor3d::ObjectBufferOffset::buffers {}
Referenced by getBufferChunk(), and reset().
hash
size_t castor3d::ObjectBufferOffset::hash {}
The documentation for this struct was generated from the following file:
Buffer/ObjectBufferOffset.hpp