Castor3D: castor3d::shader::PassComponentsShader Struct Reference
castor3d::shader::PassComponentsShader Struct Reference
#include <PassComponent.hpp>
Public Member Functions
PassComponentsShader (PassComponentPlugin const &plugin)
virtual C3D_API void fillComponents (sdw::type::BaseStruct &components, Materials const &materials, sdw::StructInstance const *surface) const
Fills the components shader struct with the members provided by this component.
virtual C3D_API void fillComponentsInits (sdw::type::BaseStruct const &components, Materials const &materials, Material const *material, sdw::StructInstance const *surface, sdw::Vec4 const *clrCot, sdw::expr::ExprList &inits) const
Fills the components shader struct members initialiser with the ones provided by this component.
virtual C3D_API void computeTexcoord (PipelineFlags const &flags, TextureConfigData const &config, sdw::U32Vec3 const &imgCompConfig, sdw::CombinedImage2DRgba32 const &map, sdw::Vec3 &texCoords, sdw::Vec2 &texCoord, BlendComponents &components) const
Use this component ta alter texture coordinates.
virtual C3D_API void computeTexcoord (PipelineFlags const &flags, TextureConfigData const &config, sdw::U32Vec3 const &imgCompConfig, sdw::CombinedImage2DRgba32 const &map, DerivTex &texCoords, DerivTex &texCoord, BlendComponents &components) const
Use this component ta alter texture coordinates.
virtual C3D_API void applyComponents (TextureCombine const &combine, PipelineFlags const *flags, shader::TextureConfigData const &config, sdw::U32Vec3 const &imgCompConfig, sdw::Vec4 const &sampled, BlendComponents &components) const
Fills this component's values with the data retrieved from a texture.
virtual C3D_API void blendComponents (shader::Materials const &materials, sdw::Float const &passMultiplier, BlendComponents &res, BlendComponents const &src) const
Used to mix components when multiple passes are blended together.
virtual C3D_API void updateComponent (TextureCombine const &combine, shader::BlendComponents &components) const
virtual C3D_API sdw::Vec4 sampleMap (sdw::CombinedImage2DRgba32 const &map, sdw::Vec3 const &texCoords, shader::BlendComponents const &components) const
virtual C3D_API sdw::Vec4 sampleMap (sdw::CombinedImage2DRgba32 const &map, shader::DerivTex const &texCoords, shader::BlendComponents const &components) const
virtual C3D_API bool isMapSampling (PipelineFlags const &flags) const
Getters.
C3D_API PassComponentID getId () const
PassComponentPlugin const & getPlugin () const
Public Member Functions inherited from castor3d::shader::PassShader
PassShader ()=default
PassShader (PassShader const &)=delete
PassShader & operator= (PassShader const &)=delete
C3D_API PassShader (PassShader &&)=default
C3D_API PassShader & operator= (PassShader &&)=default
virtual C3D_API ~PassShader ()=default
virtual C3D_API void updateOutputs (sdw::StructInstance const &components, sdw::StructInstance const &surface, sdw::Vec4 &spcRgh, sdw::Vec4 &colMtl, sdw::Vec4 &sheen) const
Updates the values needed for lighting (specular, metalness, roughness and colour).
Protected Member Functions
C3D_API void applyFloatComponent (std::string const &name, PassComponentTextureFlag flag, shader::TextureConfigData const &config, sdw::U32Vec3 const &imgCompConfig, sdw::Vec4 const &sampled, shader::BlendComponents &components) const
C3D_API void applyVec3Component (std::string const &name, PassComponentTextureFlag flag, shader::TextureConfigData const &config, sdw::U32Vec3 const &imgCompConfig, sdw::Vec4 const &sampled, shader::BlendComponents &components) const
Constructor & Destructor Documentation
PassComponentsShader()
castor3d::shader::PassComponentsShader::PassComponentsShader (PassComponentPlugin const & plugin) inline explicit
Member Function Documentation
applyComponents()
virtual C3D_API void castor3d::shader::PassComponentsShader::applyComponents (TextureCombine const & combine, PipelineFlags const * flags, shader::TextureConfigData const & config, sdw::U32Vec3 const & imgCompConfig, sdw::Vec4 const & sampled, BlendComponents & components) const inline virtual
Fills this component's values with the data retrieved from a texture.
Parameters
[in] combine Used to check if the component's textures are enabled.
[in] flags Used to check if the render pass is configured so the component is usable.
[in] config Used to say if the texture has the needed configuration for this component.
[in] imgCompConfig The current image component(s) to use.
[in] sampled The data retrieved from the texture.
[in] components Contains the component members.
Reimplemented in castor3d::AttenuationMapComponent::ComponentsShader, castor3d::ClearcoatMapComponent::ComponentsShader, castor3d::ClearcoatNormalMapComponent::ComponentsShader, castor3d::ClearcoatRoughnessMapComponent::ComponentsShader, castor3d::ColourMapComponent::ComponentsShader, castor3d::EmissiveMapComponent::ComponentsShader, castor3d::GlossinessMapComponent::ComponentsShader, castor3d::IridescenceMapComponent::ComponentsShader, castor3d::IridescenceThicknessMapComponent::ComponentsShader, castor3d::MetalnessMapComponent::ComponentsShader, castor3d::NormalMapComponent::ComponentsShader, castor3d::OcclusionMapComponent::ComponentsShader, castor3d::OpacityMapComponent::ComponentsShader, castor3d::RoughnessMapComponent::ComponentsShader, castor3d::SheenMapComponent::ComponentsShader, castor3d::SheenRoughnessMapComponent::ComponentsShader, castor3d::SpecularMapComponent::ComponentsShader, castor3d::TransmissionMapComponent::ComponentsShader, and castor3d::TransmittanceMapComponent::ComponentsShader.
applyFloatComponent()
C3D_API void castor3d::shader::PassComponentsShader::applyFloatComponent (std::string const & name, PassComponentTextureFlag flag, shader::TextureConfigData const & config, sdw::U32Vec3 const & imgCompConfig, sdw::Vec4 const & sampled, shader::BlendComponents & components) const protected
applyVec3Component()
C3D_API void castor3d::shader::PassComponentsShader::applyVec3Component (std::string const & name, PassComponentTextureFlag flag, shader::TextureConfigData const & config, sdw::U32Vec3 const & imgCompConfig, sdw::Vec4 const & sampled, shader::BlendComponents & components) const protected
blendComponents()
virtual C3D_API void castor3d::shader::PassComponentsShader::blendComponents (shader::Materials const & materials, sdw::Float const & passMultiplier, BlendComponents & res, BlendComponents const & src) const inline virtual
Used to mix components when multiple passes are blended together.
Parameters
[in] materials Used to check if the current render pass needs this component.
[in] passMultiplier The factor for the current pass.
[in,out] res Receives the blending result.
[in] src The current pass data.
Reimplemented in castor3d::NormalComponent::ComponentsShader, castor3d::TexturesComponent::ComponentsShader, castor3d::AttenuationComponent::ComponentsShader, castor3d::ClearcoatComponent::ComponentsShader, castor3d::EmissiveComponent::ComponentsShader, castor3d::IridescenceComponent::ComponentsShader, castor3d::MetalnessComponent::ComponentsShader, castor3d::RoughnessComponent::ComponentsShader, castor3d::SheenComponent::ComponentsShader, castor3d::SpecularComponent::ComponentsShader, castor3d::SubsurfaceScatteringComponent::ComponentsShader, castor3d::ThicknessComponent::ComponentsShader, castor3d::TransmissionComponent::ComponentsShader, castor3d::OcclusionMapComponent::ComponentsShader, castor3d::TransmittanceMapComponent::ComponentsShader, castor3d::AlphaTestComponent::ComponentsShader, castor3d::ColourComponent::ComponentsShader, castor3d::HeightComponent::ComponentsShader, castor3d::OpacityComponent::ComponentsShader, castor3d::ReflectionComponent::ComponentsShader, and castor3d::RefractionComponent::ComponentsShader.
computeTexcoord() [1/2]
virtual C3D_API void castor3d::shader::PassComponentsShader::computeTexcoord (PipelineFlags const & flags, TextureConfigData const & config, sdw::U32Vec3 const & imgCompConfig, sdw::CombinedImage2DRgba32 const & map, DerivTex & texCoords, DerivTex & texCoord, BlendComponents & components) const inline virtual
Use this component ta alter texture coordinates.
Parameters
[in] flags Used to check if the render pass is configured so the component is usable.
[in] config Used to say if the texture has the needed configuration for this component.
[in] imgCompConfig The current image component(s) to use.
[in] map The texture to use.
[in] texCoords The 3D texture coordinates.
[in] texCoord The 2D texture coordinates.
[in] components Contains the component members.
Reimplemented in castor3d::HeightMapComponent::ComponentsShader.
computeTexcoord() [2/2]
virtual C3D_API void castor3d::shader::PassComponentsShader::computeTexcoord (PipelineFlags const & flags, TextureConfigData const & config, sdw::U32Vec3 const & imgCompConfig, sdw::CombinedImage2DRgba32 const & map, sdw::Vec3 & texCoords, sdw::Vec2 & texCoord, BlendComponents & components) const inline virtual
Use this component ta alter texture coordinates.
Parameters
[in] flags Used to check if the render pass is configured so the component is usable.
[in] config Used to say if the texture has the needed configuration for this component.
[in] imgCompConfig The current image component(s) to use.
[in] map The texture to use.
[in] texCoords The 3D texture coordinates.
[in] texCoord The 2D texture coordinates.
[in] components Contains the component members.
Reimplemented in castor3d::HeightMapComponent::ComponentsShader.
fillComponents()
virtual C3D_API void castor3d::shader::PassComponentsShader::fillComponents (sdw::type::BaseStruct & components, Materials const & materials, sdw::StructInstance const * surface) const inline virtual
Fills the components shader struct with the members provided by this component.
Parameters
[in,out] components Receives the struct members.
[in] materials Used to check if the current render pass needs this component.
[in] surface Used to check if the surface supports needed data for this component.
Reimplemented in castor3d::FractalMappingComponent::ComponentsShader, castor3d::NormalComponent::ComponentsShader, castor3d::TexturesComponent::ComponentsShader, castor3d::AttenuationComponent::ComponentsShader, castor3d::ClearcoatComponent::ComponentsShader, castor3d::EmissiveComponent::ComponentsShader, castor3d::IridescenceComponent::ComponentsShader, castor3d::MetalnessComponent::ComponentsShader, castor3d::RoughnessComponent::ComponentsShader, castor3d::SheenComponent::ComponentsShader, castor3d::SpecularComponent::ComponentsShader, castor3d::SubsurfaceScatteringComponent::ComponentsShader, castor3d::ThicknessComponent::ComponentsShader, castor3d::TransmissionComponent::ComponentsShader, castor3d::OcclusionMapComponent::ComponentsShader, castor3d::TransmittanceMapComponent::ComponentsShader, castor3d::AlphaTestComponent::ComponentsShader, castor3d::ColourComponent::ComponentsShader, castor3d::HeightComponent::ComponentsShader, castor3d::OpacityComponent::ComponentsShader, castor3d::ReflectionComponent::ComponentsShader, and castor3d::RefractionComponent::ComponentsShader.
fillComponentsInits()
virtual C3D_API void castor3d::shader::PassComponentsShader::fillComponentsInits (sdw::type::BaseStruct const & components, Materials const & materials, Material const * material, sdw::StructInstance const * surface, sdw::Vec4 const * clrCot, sdw::expr::ExprList & inits) const inline virtual
Fills the components shader struct members initialiser with the ones provided by this component.
Remarks
The initialisers order and count must match the ones in fillComponent.
Parameters
[in] components Receives the struct members.
[in] materials Used to check if the current render pass needs this component.
[in] material Used to retrieve needed data for this component.
[in] surface Used to retrieve needed data for this component.
[in] clrCot Used to retrieve needed data for this component.
[in,out] inits Receives the initialisers.
Reimplemented in castor3d::FractalMappingComponent::ComponentsShader, castor3d::NormalComponent::ComponentsShader, castor3d::TexturesComponent::ComponentsShader, castor3d::AttenuationComponent::ComponentsShader, castor3d::ClearcoatComponent::ComponentsShader, castor3d::EmissiveComponent::ComponentsShader, castor3d::IridescenceComponent::ComponentsShader, castor3d::MetalnessComponent::ComponentsShader, castor3d::RoughnessComponent::ComponentsShader, castor3d::SheenComponent::ComponentsShader, castor3d::SpecularComponent::ComponentsShader, castor3d::SubsurfaceScatteringComponent::ComponentsShader, castor3d::ThicknessComponent::ComponentsShader, castor3d::TransmissionComponent::ComponentsShader, castor3d::OcclusionMapComponent::ComponentsShader, castor3d::TransmittanceMapComponent::ComponentsShader, castor3d::AlphaTestComponent::ComponentsShader, castor3d::ColourComponent::ComponentsShader, castor3d::HeightComponent::ComponentsShader, castor3d::OpacityComponent::ComponentsShader, castor3d::ReflectionComponent::ComponentsShader, and castor3d::RefractionComponent::ComponentsShader.
getId()
C3D_API PassComponentID castor3d::shader::PassComponentsShader::getId () const
Referenced by castor3d::AttenuationMapComponent::ComponentsShader::getTextureFlags(), castor3d::ClearcoatMapComponent::ComponentsShader::getTextureFlags(), castor3d::ClearcoatNormalMapComponent::ComponentsShader::getTextureFlags(), castor3d::ClearcoatRoughnessMapComponent::ComponentsShader::getTextureFlags(), castor3d::ColourMapComponent::ComponentsShader::getTextureFlags(), castor3d::EmissiveMapComponent::ComponentsShader::getTextureFlags(), castor3d::GlossinessMapComponent::ComponentsShader::getTextureFlags(), castor3d::HeightMapComponent::ComponentsShader::getTextureFlags(), castor3d::IridescenceMapComponent::ComponentsShader::getTextureFlags(), castor3d::IridescenceThicknessMapComponent::ComponentsShader::getTextureFlags(), castor3d::MetalnessMapComponent::ComponentsShader::getTextureFlags(), castor3d::NormalMapComponent::ComponentsShader::getTextureFlags(), castor3d::OcclusionMapComponent::ComponentsShader::getTextureFlags(), castor3d::OpacityMapComponent::ComponentsShader::getTextureFlags(), castor3d::RoughnessMapComponent::ComponentsShader::getTextureFlags(), castor3d::SheenMapComponent::ComponentsShader::getTextureFlags(), castor3d::SheenRoughnessMapComponent::ComponentsShader::getTextureFlags(), castor3d::SpecularMapComponent::ComponentsShader::getTextureFlags(), castor3d::TransmissionMapComponent::ComponentsShader::getTextureFlags(), castor3d::TransmittanceMapComponent::ComponentsShader::getTextureFlags(), castor3d::FractalMappingComponent::ComponentsShader::isMapSampling(), and castor3d::UntileMappingComponent::ComponentsShader::isMapSampling().
getPlugin()
PassComponentPlugin const & castor3d::shader::PassComponentsShader::getPlugin () const inline
isMapSampling()
virtual C3D_API bool castor3d::shader::PassComponentsShader::isMapSampling (PipelineFlags const & flags) const inline virtual
Returns
true if the component map sampling is usable with given flags.
Reimplemented in castor3d::FractalMappingComponent::ComponentsShader, and castor3d::UntileMappingComponent::ComponentsShader.
sampleMap() [1/2]
virtual C3D_API sdw::Vec4 castor3d::shader::PassComponentsShader::sampleMap (sdw::CombinedImage2DRgba32 const & map, sdw::Vec3 const & texCoords, shader::BlendComponents const & components) const virtual
Lets the component sample the map.
Parameters
[in] map The texture.
[in] texCoords The texture coordinates.
[in] components Contains the component members.
Reimplemented in castor3d::FractalMappingComponent::ComponentsShader, and castor3d::UntileMappingComponent::ComponentsShader.
sampleMap() [2/2]
virtual C3D_API sdw::Vec4 castor3d::shader::PassComponentsShader::sampleMap (sdw::CombinedImage2DRgba32 const & map, shader::DerivTex const & texCoords, shader::BlendComponents const & components) const virtual
Lets the component sample the map.
Parameters
[in] map The texture.
[in] texCoords The texture coordinates.
[in] components Contains the component members.
Reimplemented in castor3d::FractalMappingComponent::ComponentsShader, and castor3d::UntileMappingComponent::ComponentsShader.
updateComponent()
virtual C3D_API void castor3d::shader::PassComponentsShader::updateComponent (TextureCombine const & combine, shader::BlendComponents & components) const inline virtual
Adjusts the component data after textures have been parsed.
Parameters
[in] combine Used to check if the component's textures are enabled.
[in,out] components Contains the component members.
The documentation for this struct was generated from the following file:
Material/Pass/Component/PassComponent.hpp