Castor3D: Castor3D Namespace Reference
Castor3D Namespace Reference
Classes
class Animable
Animable public interface.
class AnimatedMesh
Represents the animated submeshes.
class AnimatedObject
Represents the animated objects.
class AnimatedObjectGroup
Class which represents the animated object groups.
class AnimatedSkeleton
Represents the animated objects.
class Animation
Animation base class.
class AnimationInstance
Animation instance class.
class AtomicCounterBuffer
Atomic counter buffer interface.
class BackBuffers
Back buffers class.
class BillboardBase
Billboards list.
class BillboardList
Billboards list.
struct BillboardRenderNode
Helper structure used to render billboards.
class BinaryChunk
Binary data chunk base class.
class BinaryParser
class BinaryParser< Animation >
Animation binary loader.
class BinaryParser< Bone >
Animable binary loader.
class BinaryParser< Mesh >
MovableObject loader.
class BinaryParser< MeshAnimation >
MeshAnimation binary loader.
class BinaryParser< MeshAnimationSubmesh >
MeshAnimationSubmesh binary loader.
class BinaryParser< Skeleton >
Animable binary loader.
class BinaryParser< SkeletonAnimation >
SkeletonAnimation binary loader.
class BinaryParser< SkeletonAnimationBone >
MovingBone binary loader.
class BinaryParser< SkeletonAnimationNode >
MovingBone binary loader.
class BinaryParser< SkeletonAnimationObject >
SkeletonAnimationObject binary loader.
class BinaryParser< Submesh >
MovableObject loader.
class BinaryParserBase
Binary data chunk writer/reader base class.
class BinaryWriter
class BinaryWriter< Animation >
Animation binary loader.
class BinaryWriter< Bone >
Animable binary loader.
class BinaryWriter< Mesh >
MovableObject loader.
class BinaryWriter< MeshAnimation >
MeshAnimation binary loader.
class BinaryWriter< MeshAnimationSubmesh >
MeshAnimationSubmesh binary loader.
class BinaryWriter< Skeleton >
Animable binary loader.
class BinaryWriter< SkeletonAnimation >
SkeletonAnimation binary loader.
class BinaryWriter< SkeletonAnimationBone >
MovingBone binary loader.
class BinaryWriter< SkeletonAnimationNode >
MovingBone binary loader.
class BinaryWriter< SkeletonAnimationObject >
SkeletonAnimationObject binary loader.
class BinaryWriter< Submesh >
MovableObject loader.
class BinaryWriterBase
Binary data chunk writer/reader base class.
class BlendState
Blending configurations grouping class.
class Bone
Class holding bone data.
class BonedVertex
Vertex with bones infos representation.
class BorderPanelOverlay
A rectangular overlay with a border.
class BufferDeclaration
Description of all elements in a vertex buffer.
struct BufferElementDeclaration
Buffer element description.
class BufferElementGroup
Holds data of a vertex buffer elements group.
class Cache
Base class for an element cache.
class Cache< Material, Castor::String >
Material collection, with additional functions.
class Cache< Overlay, Castor::String >
Overlay collection, with additional add and remove functions to manage Z-Index.
class Cache< Plugin, Castor::String >
Plug-ins cache.
class CacheBase
Base class for an element cache.
struct CacheTraits
Helper structure to specialise a cache behaviour.
struct CacheTraits< AnimatedObjectGroup, KeyType >
Helper structure to specialise a cache behaviour.
struct CacheTraits< FrameListener, KeyType >
Helper structure to specialise a cache behaviour.
struct CacheTraits< Material, KeyType >
Helper structure to specialise a cache behaviour.
struct CacheTraits< Mesh, KeyType >
Helper structure to specialise a cache behaviour.
struct CacheTraits< Overlay, KeyType >
Helper structure to specialise a cache behaviour.
struct CacheTraits< Plugin, KeyType >
Helper structure to specialise a cache behaviour.
struct CacheTraits< RenderTechnique, KeyType >
Helper structure to specialise a cache behaviour.
struct CacheTraits< RenderWindow, KeyType >
Helper structure to specialise a cache behaviour.
struct CacheTraits< Sampler, KeyType >
Helper structure to specialise a cache behaviour.
struct CacheTraits< Scene, KeyType >
Helper structure to specialise a cache behaviour.
class CacheView
View on a resource cache.
class Camera
Class which represents a Camera.
class ChunkParser
Chunk parser.
class ChunkParser< Castor::Path >
ChunkParser specialisation for Castor::Path.
class ChunkParser< Castor::String >
ChunkParser specialisation for Castor::String.
class ChunkParserBase
Chunk parser.
struct ChunkTyper
Helper structure to find ChunkType from a type.
struct ChunkTyper< Animation >
Helper structure to find ChunkType from a type.
struct ChunkTyper< Bone >
Helper structure to find ChunkType from a type.
struct ChunkTyper< Mesh >
Helper structure to find ChunkType from a type.
struct ChunkTyper< MeshAnimation >
Helper structure to find ChunkType from a type.
struct ChunkTyper< MeshAnimationSubmesh >
Helper structure to find ChunkType from a type.
struct ChunkTyper< Skeleton >
Helper structure to find ChunkType from a type.
struct ChunkTyper< SkeletonAnimation >
Helper structure to find ChunkType from a type.
struct ChunkTyper< SkeletonAnimationBone >
Helper structure to find ChunkType from a type.
struct ChunkTyper< SkeletonAnimationNode >
Helper structure to find ChunkType from a type.
struct ChunkTyper< SkeletonAnimationObject >
Helper structure to find ChunkType from a type.
struct ChunkTyper< Submesh >
Helper structure to find ChunkType from a type.
class ChunkWriter
Chunk data writer.
class ChunkWriter< Castor::Path >
ChunkWriter specialisation for Castor::Path.
class ChunkWriter< Castor::String >
ChunkWriter specialisation for Castor::String.
class ChunkWriterBase
Chunk writer.
class CleanupEvent
Cleaner event.
class CmshImporter
Used to import meshes from cmsh files.
class ColourRenderBuffer
Render buffer receiving colour component.
class ComputeParticleSystem
Compute shader Particle system implementation.
class ComputePipeline
The computing pipeline.
class Cone
The cone is a basic primitive, with a parametrable number of faces.
class Context
Class which holds the rendering context.
class CpuBuffer
3D Buffer management class
class CpuParticleSystem
CPU only Particle system implementation.
class Cube
The cube representation.
class Cylinder
The cylinder representation.
class DebugOverlays
Debug overlays class.
class DepthStencilRenderBuffer
Render buffer receiving depth and/or stencil component.
class DepthStencilState
Depth and stencil buffers configurations class.
class DirectionalLight
Class which represents a Directional Light.
struct DistanceRenderNode
Helper structure used to render objects.
struct DistanceRenderNodeBase
Helper structure used to render billboards.
class DividerPlugin
Divider Plugin class.
struct ElementProducer
struct ElementProducer< RenderTarget, KeyType >
struct ElementProducer< ShaderProgram, KeyType >
struct ElementTyper
class Engine
Main System.
class EventHandler
Description of an event handler, class that can receive event.
class Face
Face implementation.
struct FaceIndices
Holds the 3 vertex indices.
class Fog
Fog implementation.
class FontTexture
Contains the font and the texture assiated to this font.
class ForwardRenderTechniquePass
Forward render technique pass class.
class FrameBuffer
Frame buffer class.
class FrameBufferAttachment
Description of an attachment between a frame buffer and a render buffer.
class FrameEvent
The interface which represents a frame event.
class FrameListener
User event synchronisation class.
class Frustum
Implements a frustum and the checks related to frustum culling.
class FunctorEvent
Functor event.
class Generator
class GeneratorPlugin
Generator Plugin class.
class GenericPlugin
Generic Plugin class.
class Geometry
Geometry handler class.
class GeometryBuffers
Geometry buffers holder.
class GpuBuffer
Base class for renderer dependant buffers.
class GpuInformations
Holds GPU informations.
class GpuObjectTracker
Tracks objects allocated on GPU.
class GpuQuery
GPU query implementation.
struct GroupAnimation
class HandlerEvent
Description of a handler event.
class Icosahedron
The icosahedron representation.
class Importer
Base class for external file import.
class ImporterFactory
The importer factory.
class ImporterPlugin
Importer Plugin class.
class IndexBuffer
Index buffer representation.
class InitialiseEvent
Initialiser event.
struct InterleavedVertexT
Holds the all components of a vertex.
class Interpolator
Template class which handles the interpolations, would it be quaternion, point, real, ... interpolations.
class InterpolatorT
Template class which handles the interpolations, would it be quaternion, point, real, ... interpolations.
class InterpolatorT< Castor::Quaternion, InterpolatorType::eLinear >
Class which handles the Quaternion linear interpolations.
class InterpolatorT< Type, InterpolatorType::eLinear >
Partial specialisation of Interpolator, for eINTERPOLATOR_MODE_LINEAR.
class InterpolatorT< Type, InterpolatorType::eNearest >
Partial specialisation of Interpolator, for eINTERPOLATOR_MODE_NONE.
struct is_matrix_type
Tells if a UniformType is a matrix type.
struct is_one_type
Tells if a UniformType is a single value type.
struct is_point_type
Tells if a UniformType is a point type.
class IViewportImpl
Render API specific viewport implementation.
class IWindowHandle
Platform dependant window handle implementation.
class KeyboardEvent
Description of a keyboard event.
struct KeyboardState
Structure holding mouse state.
class KeyFrame
The class which manages key frames.
class LegacyPass
Definition of a traditional (pre-PBR) pass.
class Light
Light source implementation.
class LightCategory
Holds light components.
class LightFactory
The light source factory.
class Material
Definition of a material.
class Mesh
The mesh representation.
class MeshAnimation
Submesh animation class.
class MeshAnimationInstance
Mesh animation instance.
class MeshAnimationInstanceSubmesh
Class which represents the moving things.
class MeshAnimationSubmesh
Class which represents the mesh animation submeshes.
class MeshFactory
The mesh factory.
class MeshGenerator
Mesh category is used to create a mesh's vertices, it is created by MeshFactory.
struct MorphingRenderNode
Helper structure used to render animated submeshes.
class MouseEvent
Description of a mouse event.
struct MouseState
Structure holding mouse state.
class MovableObject
Movable object class.
class MultisampleState
Multisample configurations grouping class.
class NonClientEventHandler
Description of an event handler, class that can receive event.
class ObjectCache
Base class for a scene element cache.
class ObjectCache< Geometry, Castor::String >
Geometry cache.
class ObjectCache< Light, Castor::String >
Light cache.
class ObjectCache< SceneNode, Castor::String >
SceneNode cache.
class ObjectCacheBase
Base class for a scene element cache.
struct ObjectCacheTraits
Helper structure to specialise a cache behaviour.
struct ObjectCacheTraits< BillboardList, KeyType >
Helper structure to specialise a scene cache behaviour.
struct ObjectCacheTraits< Camera, KeyType >
Helper structure to specialise a scene cache behaviour.
struct ObjectCacheTraits< Geometry, KeyType >
Helper structure to specialise a scene cache behaviour.
struct ObjectCacheTraits< Light, KeyType >
Helper structure to specialise a scene cache behaviour.
struct ObjectCacheTraits< ParticleSystem, KeyType >
Helper structure to specialise a scene cache behaviour.
struct ObjectCacheTraits< SceneNode, KeyType >
Helper structure to specialise a scene cache behaviour.
struct ObjectRenderNode
Helper structure used to render objects.
class Overlay
The overlay class.
class OverlayCategory
Holds specific members for an overlay category.
struct OverlayCategorySort
Structure used to sort overlays by order.
class OverlayFactory
The mesh factory.
class OverlayRenderer
The overlay renderer.
class PanelOverlay
A simple rectangular overlay.
class Parameters
Configuration parameters.
class Particle
Holds one particle data.
class ParticlePlugin
Particle plug-in class.
class ParticleSystem
Particle system implementation.
class ParticleSystemImpl
Particle system implementation base class.
class Pass
Base class of a material pass.
struct PassRenderNode
Helper structure used link a pass and a shader program.
struct PassRenderNodeUniforms
Helper structure used link a pass and a shader program.
struct PassTyper
Helper class to retrieve a pass type from a MaterialType.
struct PassTyper< MaterialType::eLegacy >
Helper class to retrieve a pass type from a MaterialType.
class Pattern
Pattern handler class.
class PickingPass
Picking pass, using FBO.
struct PipelineFlags
Pipeline flags.
class Plane
The plane representation.
class Plugin
Plugin Base class.
class PluginException
Plugin loading exception.
class PointLight
Class which represents a PointLight.
class PostEffect
Post render effect base class.
class PostFxPlugin
Post effect plug-in class.
class ProgramInputLayout
ProgramInputLayout class.
class Projection
Projection mesh representation.
class PushUniform
Shader variable representation.
class RasteriserState
Rasteriser configuration class.
class Ray
Ray representation.
class RenderBuffer
Render buffer base class.
class RenderBufferAttachment
Description of an attachment between a frame buffer and a render buffer.
class RenderColourCubeToTexture
Class used to render a colour cube texture.
class RenderColourLayerCubeToTexture
Class used to render a colour cube texture array layer.
class RenderColourLayerToTexture
Class used to render a colour texture array's layer.
class RenderColourToCube
Class used to render colour equirectangular textures to cube maps.
class RenderColourToTexture
Class used to render colour textures.
class RenderDepthCubeToTexture
Class used to render a depth cube texture.
class RenderDepthLayerCubeToTexture
Class used to render a depth cube texture array layer.
class RenderDepthLayerToTexture
Class used to render a depth texture array's layer.
class RenderDepthToTexture
Class used to render depth textures.
class RenderedObject
Handles object's visibility, and behavior with shadows.
class RendererPlugin
Renderer Plugin class.
struct RenderInfo
Holds render informations.
class RenderLoop
Render loop base class.
class RenderLoopAsync
Main System.
class RenderLoopSync
Synchronous render loop.
struct RenderNodesT
The render nodes for a specific scene.
class RenderPass
Render pass base class.
class RenderPipeline
The rendering pipeline.
class RenderQueue
Render technique base class.
class RenderSystem
The render system representation.
class RenderTarget
Render target class.
class RenderTargetCache
RenderTarget cache.
class RenderTechnique
Render technique base class.
class RenderTechniquePass
Render technique pass base class.
class RenderWindow
Render window representation.
class Sampler
Defines a sampler for a texture.
class Scene
Scene handler class.
class SceneFileContext
The context used into parsing functions.
class SceneFileParser
ESCN file parser.
class SceneNode
The scene node handler class.
struct SceneRenderNode
Helper structure used to render submeshes.
struct SceneRenderNodes
The render nodes for a specific scene.
class ShaderObject
Base shader class.
class ShaderProgram
Base shader program implementation, used to share functions through the supported shader languages.
class ShaderProgramCache
Cache used to hold the shader programs. Holds it, destroys it during a rendering loop.
class ShaderStorageBuffer
Shader storage buffer interface.
class Shadow
Shadows configuration class.
class ShadowMap
Shadow mapping implementation.
class ShadowMapDirectional
Shadow mapping implementation for spot lights.
class ShadowMapPass
Shadow mapping implementation.
class ShadowMapPassDirectional
Shadow mapping implementation for spot lights.
class ShadowMapPassPoint
Shadow mapping implementation.
class ShadowMapPassSpot
Shadow mapping implementation for spot lights.
class ShadowMapPoint
Shadow mapping implementation.
class ShadowMapSpot
Shadow mapping implementation for spot lights.
class Skeleton
The skeleton, holds each bone.
class SkeletonAnimation
Skeleton animation class.
class SkeletonAnimationBone
Implementation of SkeletonAnimationObject for Bones.
class SkeletonAnimationInstance
Skeleton animation instance.
class SkeletonAnimationInstanceBone
Implementation of SkeletonAnimationObject for Bones.
class SkeletonAnimationInstanceNode
Implementation of SkeletonAnimationNode for abstract nodes.
class SkeletonAnimationInstanceObject
Class which represents the moving things.
class SkeletonAnimationNode
Implementation of SkeletonAnimationObject for abstract nodes.
class SkeletonAnimationObject
Class which represents the skeleton animation objects.
struct SkinningRenderNode
Helper structure used to render animated submeshes.
class Skybox
Skybox implementation.
class Sphere
The sphere primitive.
class SpotLight
Class which represents a SpotLight.
struct StaticRenderNode
Helper structure used to render static submeshes.
struct stFACE_INFOS
Holds face informations.
class Subdivider
Subdividers main class C3D_API.
class Submesh
The submesh representation.
struct SubmeshAnimationBufferT
Class which represents the mesh animation submeshes buffers.
class TechniquePlugin
Render technique plug-in class.
class TextOverlay
An overlay with a text.
class TextureAttachment
Description of an attachment between a frame buffer and a texture.
class TextureImage
Texture image.
class TextureLayout
Texture base class.
class TextureProjection
Class used to render colour equirectangular textures to cube maps.
class TextureSource
Texture image source.
class TextureStorage
GPU texture storage base class.
class TextureUnit
Texture unit representation.
class ToneMapping
Tone mapping base class.
class ToneMappingPlugin
Tone mapping plug-in class.
struct TopologyNamer
Helper structure to get a topology name.
class Torus
The torus representation.
class TPushUniform
Shader variable representation with variable type.
class TransformFeedback
Transform feedback implementation.
class TransformFeedbackParticleSystem
Transform feedback Particle system implementation.
class TUniform
Shader variable representation with variable type.
struct TypeRenderNodesByPassMap
class Uniform
Shader variable representation.
struct uniform_matrix_type
Helper structure to retrieve a matrix type from a UniformType.
struct uniform_matrix_type< T, Columns, Rows, typename std::enable_if< Columns !=Rows >::type >
Helper structure to retrieve a matrix type from a UniformType.
struct uniform_matrix_type< T, Columns, Rows, typename std::enable_if< Columns==Rows >::type >
Helper structure to retrieve a matrix type from a UniformType.
struct uniform_sub_type
Helper structure to retrieve a sub type from a UniformType.
struct uniform_sub_type< Type, typename std::enable_if< Type==UniformType::eBool||Type==UniformType::eVec2b||Type==UniformType::eVec3b||Type==UniformType::eVec4b||Type==UniformType::eMat2x2b||Type==UniformType::eMat2x3b||Type==UniformType::eMat2x4b||Type==UniformType::eMat3x2b||Type==UniformType::eMat3x3b||Type==UniformType::eMat3x4b||Type==UniformType::eMat4x2b||Type==UniformType::eMat4x3b||Type==UniformType::eMat4x4b >::type >
Helper structure to retrieve a frame variable type from a UniformType.
struct uniform_sub_type< Type, typename std::enable_if< Type==UniformType::eDouble||Type==UniformType::eVec2d||Type==UniformType::eVec3d||Type==UniformType::eVec4d||Type==UniformType::eMat2x2d||Type==UniformType::eMat2x3d||Type==UniformType::eMat2x4d||Type==UniformType::eMat3x2d||Type==UniformType::eMat3x3d||Type==UniformType::eMat3x4d||Type==UniformType::eMat4x2d||Type==UniformType::eMat4x3d||Type==UniformType::eMat4x4d >::type >
Helper structure to retrieve a frame variable type from a UniformType.
struct uniform_sub_type< Type, typename std::enable_if< Type==UniformType::eFloat||Type==UniformType::eVec2f||Type==UniformType::eVec3f||Type==UniformType::eVec4f||Type==UniformType::eMat2x2f||Type==UniformType::eMat2x3f||Type==UniformType::eMat2x4f||Type==UniformType::eMat3x2f||Type==UniformType::eMat3x3f||Type==UniformType::eMat3x4f||Type==UniformType::eMat4x2f||Type==UniformType::eMat4x3f||Type==UniformType::eMat4x4f >::type >
Helper structure to retrieve a frame variable type from a UniformType.
struct uniform_sub_type< Type, typename std::enable_if< Type==UniformType::eInt||Type==UniformType::eVec2i||Type==UniformType::eVec3i||Type==UniformType::eVec4i||Type==UniformType::eMat2x2i||Type==UniformType::eMat2x3i||Type==UniformType::eMat2x4i||Type==UniformType::eMat3x2i||Type==UniformType::eMat3x3i||Type==UniformType::eMat3x4i||Type==UniformType::eMat4x2i||Type==UniformType::eMat4x3i||Type==UniformType::eMat4x4i >::type >
Helper structure to retrieve a frame variable type from a UniformType.
struct uniform_sub_type< Type, typename std::enable_if< Type==UniformType::eSampler >::type >
Helper structure to retrieve a sub type from a UniformType.
struct uniform_sub_type< Type, typename std::enable_if< Type==UniformType::eUInt||Type==UniformType::eVec2ui||Type==UniformType::eVec3ui||Type==UniformType::eVec4ui||Type==UniformType::eMat2x2ui||Type==UniformType::eMat2x3ui||Type==UniformType::eMat2x4ui||Type==UniformType::eMat3x2ui||Type==UniformType::eMat3x3ui||Type==UniformType::eMat3x4ui||Type==UniformType::eMat4x2ui||Type==UniformType::eMat4x3ui||Type==UniformType::eMat4x4ui >::type >
Helper structure to retrieve a frame variable type from a UniformType.
struct uniform_type
Helper structure to retrieve a frame variable type from a UniformType.
struct uniform_type< Type, typename std::enable_if< is_matrix_type< Type >::value >::type >
Helper structure to retrieve a frame variable type from a UniformType.
struct uniform_type< Type, typename std::enable_if< is_one_type< Type >::value >::type >
Helper structure to retrieve a frame variable type from a UniformType.
struct uniform_type< Type, typename std::enable_if< is_point_type< Type >::value >::type >
Helper structure to retrieve a frame variable type from a UniformType.
struct uniform_type_name
Retrieves the name of a UniformType.
class UniformBuffer
Shader variables buffer.
class UniformBufferBinding
Represents the binding between a uniform buffer and a program.
class UserInputEvent
Description of a user input event.
class UserInputListener
Class used to to manage the user input events.
struct variable_type
Retrieves the VariableType of a UniformType.
struct variable_type< Type, typename std::enable_if< Type==UniformType::eBool||Type==UniformType::eInt||Type==UniformType::eUInt||Type==UniformType::eFloat||Type==UniformType::eDouble||Type==UniformType::eSampler >::type >
Retrieves the VariableType of a UniformType.
struct variable_type< Type, typename std::enable_if< Type==UniformType::eMat2x2b||Type==UniformType::eMat2x2i||Type==UniformType::eMat2x2ui||Type==UniformType::eMat2x2f||Type==UniformType::eMat2x2d >::type >
Retrieves the VariableType of a UniformType.
struct variable_type< Type, typename std::enable_if< Type==UniformType::eMat2x3b||Type==UniformType::eMat2x3i||Type==UniformType::eMat2x3ui||Type==UniformType::eMat2x3f||Type==UniformType::eMat2x3d >::type >
Retrieves the VariableType of a UniformType.
struct variable_type< Type, typename std::enable_if< Type==UniformType::eMat2x4b||Type==UniformType::eMat2x4i||Type==UniformType::eMat2x4ui||Type==UniformType::eMat2x4f||Type==UniformType::eMat2x4d >::type >
Retrieves the VariableType of a UniformType.
struct variable_type< Type, typename std::enable_if< Type==UniformType::eMat3x2b||Type==UniformType::eMat3x2i||Type==UniformType::eMat3x2ui||Type==UniformType::eMat3x2f||Type==UniformType::eMat3x2d >::type >
Retrieves the VariableType of a UniformType.
struct variable_type< Type, typename std::enable_if< Type==UniformType::eMat3x3b||Type==UniformType::eMat3x3i||Type==UniformType::eMat3x3ui||Type==UniformType::eMat3x3f||Type==UniformType::eMat3x3d >::type >
Retrieves the VariableType of a UniformType.
struct variable_type< Type, typename std::enable_if< Type==UniformType::eMat3x4b||Type==UniformType::eMat3x4i||Type==UniformType::eMat3x4ui||Type==UniformType::eMat3x4f||Type==UniformType::eMat3x4d >::type >
Retrieves the VariableType of a UniformType.
struct variable_type< Type, typename std::enable_if< Type==UniformType::eMat4x2b||Type==UniformType::eMat4x2i||Type==UniformType::eMat4x2ui||Type==UniformType::eMat4x2f||Type==UniformType::eMat4x2d >::type >
Retrieves the VariableType of a UniformType.
struct variable_type< Type, typename std::enable_if< Type==UniformType::eMat4x3b||Type==UniformType::eMat4x3i||Type==UniformType::eMat4x3ui||Type==UniformType::eMat4x3f||Type==UniformType::eMat4x3d >::type >
Retrieves the VariableType of a UniformType.
struct variable_type< Type, typename std::enable_if< Type==UniformType::eMat4x4b||Type==UniformType::eMat4x4i||Type==UniformType::eMat4x4ui||Type==UniformType::eMat4x4f||Type==UniformType::eMat4x4d >::type >
Retrieves the VariableType of a UniformType.
struct variable_type< Type, typename std::enable_if< Type==UniformType::eVec2b||Type==UniformType::eVec2i||Type==UniformType::eVec2ui||Type==UniformType::eVec2f||Type==UniformType::eVec2d >::type >
Retrieves the VariableType of a UniformType.
struct variable_type< Type, typename std::enable_if< Type==UniformType::eVec3b||Type==UniformType::eVec3i||Type==UniformType::eVec3ui||Type==UniformType::eVec3f||Type==UniformType::eVec3d >::type >
Retrieves the VariableType of a UniformType.
struct variable_type< Type, typename std::enable_if< Type==UniformType::eVec4b||Type==UniformType::eVec4i||Type==UniformType::eVec4ui||Type==UniformType::eVec4f||Type==UniformType::eVec4d >::type >
Retrieves the VariableType of a UniformType.
class Version
Version management class.
class VersionException
Version comparison exception.
class Vertex
Representation of a vertex.
struct VertexBoneData
Holds bone data for one vertex.
class VertexBuffer
Vertex buffer representation.
class Viewport
Class to represent a viewport.
class WindowHandle
Platform independant window handle implementation.
Typedefs
using GeometryCache = ObjectCache< Geometry, Castor::String >
using LightsArray = std::vector< LightSPtr >
using LightsMap = std::array< LightsArray, size_t(LightType::eCount) >
using LightCache = ObjectCache< Light, Castor::String >
using MaterialCache = Cache< Material, Castor::String >
using OverlayCategorySet = std::set< OverlayCategorySPtr, OverlayCategorySort >
using OverlayCache = Cache< Overlay, Castor::String >
using PluginCache = Cache< Plugin, Castor::String >
using SceneNodeCache = ObjectCache< SceneNode, Castor::String >
using ToneMappingFactory = Castor::Factory< ToneMapping, Castor::String, ToneMappingSPtr, std::function< ToneMappingSPtr(Engine &, Parameters const &) > >
Tone mapping factory.
using SubdividerFactory = Castor::Factory< Subdivider, Castor::String, SubdividerUPtr >
The subdivider factory.
using InterleavedVertex = InterleavedVertexT< real >
using InterleavedVertexArray = std::vector< InterleavedVertex >
using PostEffectFactory = Castor::Factory< PostEffect, Castor::String, std::shared_ptr< PostEffect >, std::function< PostEffectSPtr(RenderTarget &, RenderSystem &, Parameters const &) > >
Post effect factory.
using SubmeshRenderNode = ObjectRenderNode< Submesh, Geometry >
using BillboardListRenderNode = ObjectRenderNode< BillboardBase, BillboardBase >
using SubmeshStaticRenderNodesByPassMap = TypeRenderNodesByPassMap< SubmeshStaticRenderNodesMap >
using RenderSystemFactory = Castor::Factory< RenderSystem, Castor::String, RenderSystemUPtr, std::function< RenderSystemUPtr(Engine &) > >
Render technique factory.
using ParticleArray = std::vector< Particle >
using TechniqueFactory = Castor::Factory< RenderTechnique, Castor::String, RenderTechniqueSPtr, std::function< RenderTechniqueSPtr(RenderTarget &, RenderSystem &, Parameters const &) > >
Render technique factory.
Enumerations
enum ChunkType : uint64_t {
ChunkType::eUnknown = MAKE_CHUNK_ID(' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '), ChunkType::eCmshFile = MAKE_CHUNK_ID('C', 'M', 'S', 'H', 'F', 'I', 'L', 'E'), ChunkType::eCmshHeader = MAKE_CHUNK_ID('C', 'M', 'S', 'H', 'H', 'D', 'E', 'R'), ChunkType::eCmshVersion = MAKE_CHUNK_ID('C', 'M', 'S', 'H', 'V', 'R', 'S', 'N'),
ChunkType::eName = MAKE_CHUNK_ID('N', 'A', 'M', 'E', ' ', ' ', ' ', ' '), ChunkType::eMesh = MAKE_CHUNK_ID('M', 'E', 'S', 'H', ' ', ' ', ' ', ' '), ChunkType::eSkeleton = MAKE_CHUNK_ID('S', 'K', 'E', 'L', 'E', 'T', 'O', 'N'), ChunkType::eSkeletonGlobalInverse = MAKE_CHUNK_ID('S', 'K', 'E', 'L', 'G', 'I', 'M', 'X'),
ChunkType::eSkeletonBone = MAKE_CHUNK_ID('S', 'K', 'E', 'L', 'B', 'O', 'N', 'E'), ChunkType::eBoneParentName = MAKE_CHUNK_ID('B', 'O', 'N', 'E', 'P', 'A', 'R', 'T'), ChunkType::eBoneOffsetMatrix = MAKE_CHUNK_ID('B', 'O', 'N', 'E', 'O', 'M', 'T', 'X'), ChunkType::eSubmesh = MAKE_CHUNK_ID('S', 'U', 'B', 'M', 'E', 'S', 'H', ' '),
ChunkType::eSubmeshTopology = MAKE_CHUNK_ID('S', 'M', 'S', 'H', 'T', 'O', 'P', 'O'), ChunkType::eSubmeshVertexCount = MAKE_CHUNK_ID('S', 'M', 'S', 'H', 'V', 'X', 'C', 'T'), ChunkType::eSubmeshVertex = MAKE_CHUNK_ID('S', 'M', 'S', 'H', 'V', 'R', 'T', 'X'), ChunkType::eSubmeshBoneCount = MAKE_CHUNK_ID('S', 'M', 'S', 'H', 'B', 'N', 'C', 'T'),
ChunkType::eSubmeshBones = MAKE_CHUNK_ID('S', 'M', 'S', 'H', 'B', 'O', 'N', 'E'), ChunkType::eSubmeshMatrixCount = MAKE_CHUNK_ID('S', 'M', 'S', 'H', 'M', 'X', 'C', 'T'), ChunkType::eSubmeshMatrices = MAKE_CHUNK_ID('S', 'M', 'S', 'H', 'M', 'T', 'R', 'X'), ChunkType::eSubmeshFaceCount = MAKE_CHUNK_ID('S', 'M', 'S', 'H', 'F', 'C', 'C', 'T'),
ChunkType::eSubmeshFaces = MAKE_CHUNK_ID('S', 'M', 'S', 'H', 'F', 'A', 'C', 'E'), ChunkType::eAnimable = MAKE_CHUNK_ID('A', 'N', 'I', 'M', 'A', 'B', 'L', 'E'), ChunkType::eAnimation = MAKE_CHUNK_ID('A', 'N', 'M', 'A', 'T', 'I', 'O', 'N'), ChunkType::eAnimLength = MAKE_CHUNK_ID('A', 'N', 'M', 'L', 'E', 'N', 'G', 'T'),
ChunkType::eSkeletonAnimation = MAKE_CHUNK_ID('S', 'K', 'E', 'L', 'A', 'N', 'I', 'M'), ChunkType::eMeshAnimation = MAKE_CHUNK_ID('M', 'E', 'S', 'H', 'A', 'N', 'I', 'M'), ChunkType::eAnimInterpolator = MAKE_CHUNK_ID('A', 'N', 'M', 'I', 'N', 'T', 'E', 'R'), ChunkType::eAnimationObject = MAKE_CHUNK_ID('A', 'N', 'S', 'K', 'O', 'B', 'J', 'T'),
ChunkType::eSkeletonAnimationNode = MAKE_CHUNK_ID('A', 'N', 'S', 'K', 'N', 'O', 'D', 'E'), ChunkType::eSkeletonAnimationBone = MAKE_CHUNK_ID('A', 'N', 'S', 'K', 'B', 'O', 'N', 'E'), ChunkType::eMovingTransform = MAKE_CHUNK_ID('M', 'V', 'N', 'G', 'T', 'S', 'F', 'M'), ChunkType::eKeyframeCount = MAKE_CHUNK_ID('K', 'F', 'R', 'M', 'C', 'O', 'N', 'T'),
ChunkType::eKeyframes = MAKE_CHUNK_ID('K', 'E', 'Y', 'F', 'R', 'M', 'E', 'S'), ChunkType::eMeshAnimationSubmeshID = MAKE_CHUNK_ID('M', 'H', 'A', 'N', 'S', 'H', 'I', 'D'), ChunkType::eMeshAnimationSubmesh = MAKE_CHUNK_ID('M', 'S', 'H', 'A', 'N', 'S', 'M', 'H'), ChunkType::eSubmeshAnimationBuffer = MAKE_CHUNK_ID('M', 'H', 'A', 'N', 'S', 'H', 'B', 'F'),
ChunkType::eSubmeshAnimationBufferSize = MAKE_CHUNK_ID('A', 'N', 'S', 'H', 'B', 'F', 'S', 'Z'), ChunkType::eSubmeshAnimationBuffersCount = MAKE_CHUNK_ID('A', 'N', 'S', 'H', 'B', 'F', 'C', 'T'), ChunkType::eSubmeshAnimationBuffers = MAKE_CHUNK_ID('A', 'N', 'S', 'H', 'B', 'U', 'F', 'S')
}
Binary data chunk types enumeration.
enum GpuFeature : uint32_t {
GpuFeature::eInstancing = 0x00000001, GpuFeature::eAccumulationBuffer = 0x00000002, GpuFeature::eNonPowerOfTwoTextures = 0x00000004, GpuFeature::eStereo = 0x00000008,
GpuFeature::eConstantsBuffers = 0x00000010, GpuFeature::eTextureBuffers = 0x00000020, GpuFeature::eShaderStorageBuffers = 0x00000040, GpuFeature::eAtomicCounterBuffers = 0x00000080,
GpuFeature::eTransformFeedback = 0x00000100, GpuFeature::eImmutableTextureStorage = 0x00000200
}
All supported GPU feature flags.
enum GpuMin : uint32_t { GpuMin::eMapBufferAlignment, GpuMin::eProgramTexelOffset }
All supported GPU feature flags.
enum GpuMax : uint32_t {
GpuMax::eShaderStorageBufferBindings, GpuMax::eVertexShaderStorageBlocks, GpuMax::eVertexAtomicCounters, GpuMax::eVertexAttribs,
GpuMax::eVertexOutputComponents, GpuMax::eVertexTextureImageUnits, GpuMax::eVertexUniformComponents, GpuMax::eVertexUniformBlocks,
GpuMax::eVertexUniformVectors, GpuMax::eVertexCombinedUniformComponents, GpuMax::eGeometryAtomicCounters, GpuMax::eGeometryShaderStorageBlocks,
GpuMax::eGeometryInputComponents, GpuMax::eGeometryOutputComponents, GpuMax::eGeometryTextureImageUnits, GpuMax::eGeometryUniformComponents,
GpuMax::eGeometryUniformBlocks, GpuMax::eGeometryCombinedUniformComponents, GpuMax::eTessControlAtomicCounters, GpuMax::eTessControlShaderStorageBlocks,
GpuMax::eTessEvaluationAtomicCounters, GpuMax::eTessEvaluationShaderStorageBlocks, GpuMax::eComputeAtomicCounters, GpuMax::eComputeAtomicCounterBuffers,
GpuMax::eComputeShaderStorageBlocks, GpuMax::eComputeTextureImageUnits, GpuMax::eComputeUniformComponents, GpuMax::eComputeUniformBlocks,
GpuMax::eComputeCombinedUniformComponents, GpuMax::eComputeWorkGroupInvocations, GpuMax::eComputeWorkGroupCount, GpuMax::eComputeWorkGroupSize,
GpuMax::eFragmentAtomicCounters, GpuMax::eFragmentShaderStorageBlocks, GpuMax::eFragmentInputComponents, GpuMax::eFragmentUniformComponents,
GpuMax::eFragmentUniformBlocks, GpuMax::eFragmentUniformVectors, GpuMax::eFragmentCombinedUniformComponents, GpuMax::eCombinedAtomicCounters,
GpuMax::eCombinedShaderStorageBlocks, GpuMax::eDebugGroupStackDepth, GpuMax::eLabelLength, GpuMax::eIntegerSamples,
GpuMax::eProgramTexelOffset, GpuMax::eServerWaitTimeout, GpuMax::eSampleMaskWords, GpuMax::eSamples,
GpuMax::eTexture3DSize, GpuMax::eTextureRectangleSize, GpuMax::eTextureCubeMapSize, GpuMax::eTextureBufferSize,
GpuMax::eTextureSize, GpuMax::eTextureImageUnits, GpuMax::eTextureLodBias, GpuMax::eArrayTextureLayers,
GpuMax::eClipDistances, GpuMax::eColourTextureSamples, GpuMax::eDepthTextureSamples, GpuMax::eCombinedTextureImageUnits,
GpuMax::eCombinedUniformBlocks, GpuMax::eDrawBuffers, GpuMax::eDualSourceDrawBuffers, GpuMax::eElementIndices,
GpuMax::eElementVertices, GpuMax::eFramebufferWidth, GpuMax::eFramebufferHeight, GpuMax::eFramebufferLayers,
GpuMax::eFramebufferSamples, GpuMax::eRenderbufferSize, GpuMax::eUniformBufferBindings, GpuMax::eUniformBlockSize,
GpuMax::eUniformLocations, GpuMax::eVaryingComponents, GpuMax::eVaryingVectors, GpuMax::eVaryingFloats,
GpuMax::eViewportWidth, GpuMax::eViewportHeight, GpuMax::eViewports
}
All supported GPU feature flags.
enum UserInputEventType { UserInputEventType::eMouse, UserInputEventType::eKeyboard, UserInputEventType::eHandler }
Supported events types enumeration.
enum MouseEventType : uint8_t {
MouseEventType::eMove, MouseEventType::eEnter, MouseEventType::eHover, MouseEventType::eLeave,
MouseEventType::ePushed, MouseEventType::eReleased, MouseEventType::eWheel
}
Enumeration of supported mouse events.
enum KeyboardEventType : uint8_t { KeyboardEventType::ePushed, KeyboardEventType::eReleased, KeyboardEventType::eChar }
Enumeration of supported keyboard events.
enum HandlerEventType : uint8_t { HandlerEventType::eActivate, HandlerEventType::eDeactivate }
Enumeration of supported handler events.
enum MouseButton { MouseButton::eLeft, MouseButton::eMiddle, MouseButton::eRight }
Mouse buttons enumeration.
enum KeyboardKey {
KeyboardKey::eNone, KeyboardKey::eBackspace = 0x08, KeyboardKey::eTab = 0x0A, KeyboardKey::eReturn = 0x0D,
KeyboardKey::eEscape = 0x1B, KeyboardKey::eSpace = 0x20, KeyboardKey::eDelete = 0x7F, KeyboardKey::eStart = 0x100,
KeyboardKey::eLButton, KeyboardKey::eRButton, KeyboardKey::eCancel, KeyboardKey::eMButton,
KeyboardKey::eClear, KeyboardKey::eShift, KeyboardKey::eAlt, KeyboardKey::eControl,
KeyboardKey::eMenu, KeyboardKey::ePause, KeyboardKey::eCapital, KeyboardKey::eEnd,
KeyboardKey::eHome, KeyboardKey::eLeft, KeyboardKey::eUp, KeyboardKey::eRight,
KeyboardKey::eDown, KeyboardKey::eSelect, KeyboardKey::ePrint, KeyboardKey::eExecute,
KeyboardKey::eSnapshot, KeyboardKey::eInsert, KeyboardKey::eHelp, KeyboardKey::eNumpad0,
KeyboardKey::eNumpad1, KeyboardKey::eNumpad2, KeyboardKey::eNumpad3, KeyboardKey::eNumpad4,
KeyboardKey::eNumpad5, KeyboardKey::eNumpad6, KeyboardKey::eNumpad7, KeyboardKey::eNumpad8,
KeyboardKey::eNumpad9, KeyboardKey::eMultiply, KeyboardKey::eAdd, KeyboardKey::eSeparator,
KeyboardKey::eSubtract, KeyboardKey::eDecimal, KeyboardKey::eDivide, KeyboardKey::eF1,
KeyboardKey::eF2, KeyboardKey::eF3, KeyboardKey::eF4, KeyboardKey::eF5,
KeyboardKey::eF6, KeyboardKey::eF7, KeyboardKey::eF8, KeyboardKey::eF9,
KeyboardKey::eF10, KeyboardKey::eF11, KeyboardKey::eF12, KeyboardKey::eF13,
KeyboardKey::eF14, KeyboardKey::eF15, KeyboardKey::eF16, KeyboardKey::eF17,
KeyboardKey::eF18, KeyboardKey::eF19, KeyboardKey::eF20, KeyboardKey::eF21,
KeyboardKey::eF22, KeyboardKey::eF23, KeyboardKey::eF24, KeyboardKey::eNumlock,
KeyboardKey::eScroll, KeyboardKey::ePageUp, KeyboardKey::ePageDown, KeyboardKey::eNumpadSpace,
KeyboardKey::eNumpadTab, KeyboardKey::eNumpadEnter, KeyboardKey::eNumpadF1, KeyboardKey::eNumpadF2,
KeyboardKey::eNumpadF3, KeyboardKey::eNumpadF4, KeyboardKey::eNumpadHome, KeyboardKey::eNumpadLeft,
KeyboardKey::eNumpadUp, KeyboardKey::eNumpadRight, KeyboardKey::eNumpadDown, KeyboardKey::eNumpadPageUp,
KeyboardKey::eNumpadPageDown, KeyboardKey::eNumpadEnd, KeyboardKey::eNumpadBegin, KeyboardKey::eNumpadInsert,
KeyboardKey::eNumpadDelete, KeyboardKey::eNumpadEqual, KeyboardKey::eNumpadMultiply, KeyboardKey::eNumpadAdd,
KeyboardKey::eNumpadSeparator, KeyboardKey::eNumpadSubtract, KeyboardKey::eNumpadDecimal, KeyboardKey::eNumpadDivide
}
Keyboard keys enumeration.
enum CSCNSection : uint32_t {
CSCNSection::eRoot = MAKE_SECTION_NAME('R', 'O', 'O', 'T'), CSCNSection::eScene = MAKE_SECTION_NAME('S', 'C', 'N', 'E'), CSCNSection::eWindow = MAKE_SECTION_NAME('W', 'N', 'D', 'W'), CSCNSection::eSampler = MAKE_SECTION_NAME('S', 'M', 'P', 'R'),
CSCNSection::eCamera = MAKE_SECTION_NAME('C', 'A', 'M', 'R'), CSCNSection::eViewport = MAKE_SECTION_NAME('V', 'W', 'P', 'T'), CSCNSection::eLight = MAKE_SECTION_NAME('L', 'G', 'H', 'T'), CSCNSection::eNode = MAKE_SECTION_NAME('N', 'O', 'D', 'E'),
CSCNSection::eObject = MAKE_SECTION_NAME('O', 'B', 'J', 'T'), CSCNSection::eObjectMaterials = MAKE_SECTION_NAME('O', 'M', 'T', 'L'), CSCNSection::eFont = MAKE_SECTION_NAME('F', 'O', 'N', 'T'), CSCNSection::ePanelOverlay = MAKE_SECTION_NAME('P', 'O', 'V', 'L'),
CSCNSection::eBorderPanelOverlay = MAKE_SECTION_NAME('B', 'O', 'V', 'L'), CSCNSection::eTextOverlay = MAKE_SECTION_NAME('T', 'O', 'V', 'L'), CSCNSection::eMesh = MAKE_SECTION_NAME('M', 'E', 'S', 'H'), CSCNSection::eSubmesh = MAKE_SECTION_NAME('S', 'M', 'S', 'H'),
CSCNSection::eMaterial = MAKE_SECTION_NAME('M', 'T', 'R', 'L'), CSCNSection::ePass = MAKE_SECTION_NAME('P', 'A', 'S', 'S'), CSCNSection::eTextureUnit = MAKE_SECTION_NAME('U', 'N', 'I', 'T'), CSCNSection::eRenderTarget = MAKE_SECTION_NAME('R', 'T', 'G', 'R'),
CSCNSection::eShaderProgram = MAKE_SECTION_NAME('G', 'L', 'S', 'L'), CSCNSection::eShaderObject = MAKE_SECTION_NAME('S', 'P', 'G', 'M'), CSCNSection::eShaderUBO = MAKE_SECTION_NAME('S', 'U', 'B', 'O'), CSCNSection::eUBOVariable = MAKE_SECTION_NAME('S', 'U', 'B', 'V'),
CSCNSection::eBillboard = MAKE_SECTION_NAME('B', 'L', 'B', 'd'), CSCNSection::eBillboardList = MAKE_SECTION_NAME('B', 'L', 'B', 'L'), CSCNSection::eAnimGroup = MAKE_SECTION_NAME('A', 'N', 'G', 'P'), CSCNSection::eAnimation = MAKE_SECTION_NAME('A', 'N', 'M', 'T'),
CSCNSection::eSkybox = MAKE_SECTION_NAME('S', 'K', 'B', 'X'), CSCNSection::eParticleSystem = MAKE_SECTION_NAME('P', 'L', 'S', 'M'), CSCNSection::eParticle = MAKE_SECTION_NAME('P', 'T', 'C', 'L')
}
Scene file sections Enum.
Functions
static void PrepareChunkData (ChunkType &p_value)
Sets given value to big endian.
static uint8_t const * GetBuffer (bool const &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t * GetBuffer (bool &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * GetBuffer (int8_t const &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t * GetBuffer (int8_t &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * GetBuffer (uint8_t const &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t * GetBuffer (uint8_t &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * GetBuffer (int16_t const &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t * GetBuffer (int16_t &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * GetBuffer (uint16_t const &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t * GetBuffer (uint16_t &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * GetBuffer (int32_t const &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t * GetBuffer (int32_t &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * GetBuffer (uint32_t const &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t * GetBuffer (uint32_t &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * GetBuffer (int64_t const &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t * GetBuffer (int64_t &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * GetBuffer (uint64_t const &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t * GetBuffer (uint64_t &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * GetBuffer (float const &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t * GetBuffer (float &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * GetBuffer (double const &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t * GetBuffer (double &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * GetBuffer (long double const &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t * GetBuffer (long double &p_value)
Retrieves the beginning of the buffer for given value.
template<typename T >
static size_t GetDataSize (T const &p_value)
Retrieves the value binary size.
template<typename T >
static uint8_t const * GetBuffer (std::vector< T > const &p_value)
Retrieves the beginning of the buffer for given value.
template<typename T >
static uint8_t * GetBuffer (std::vector< T > &p_value)
Retrieves the beginning of the buffer for given value.
template<typename T >
static size_t GetDataSize (std::vector< T > const &p_value)
Retrieves the value binary size.
template<typename T , size_t Count>
static uint8_t const * GetBuffer (std::array< T, Count > const &p_value)
Retrieves the beginning of the buffer for given value.
template<typename T , size_t Count>
static uint8_t * GetBuffer (std::array< T, Count > &p_value)
Retrieves the beginning of the buffer for given value.
template<typename T , size_t Count>
static size_t GetDataSize (std::array< T, Count > const &p_value)
Retrieves the value binary size.
template<typename T , uint32_t Count>
static uint8_t const * GetBuffer (Castor::Point< T, Count > const &p_value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Count>
static uint8_t * GetBuffer (Castor::Point< T, Count > &p_value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Count>
static size_t GetDataSize (Castor::Point< T, Count > const &p_value)
Retrieves the value binary size.
template<typename T , uint32_t Count>
static uint8_t const * GetBuffer (Castor::Coords< T, Count > const &p_value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Count>
static uint8_t * GetBuffer (Castor::Coords< T, Count > &p_value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Count>
static size_t GetDataSize (Castor::Coords< T, Count > const &p_value)
Retrieves the value binary size.
template<typename T , uint32_t Columns, uint32_t Rows>
static uint8_t const * GetBuffer (Castor::Matrix< T, Columns, Rows > const &p_value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Columns, uint32_t Rows>
static uint8_t * GetBuffer (Castor::Matrix< T, Columns, Rows > &p_value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Columns, uint32_t Rows>
static size_t GetDataSize (Castor::Matrix< T, Columns, Rows > const &p_value)
Retrieves the value binary size.
template<typename T , uint32_t Count>
static uint8_t const * GetBuffer (Castor::SquareMatrix< T, Count > const &p_value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Count>
static uint8_t * GetBuffer (Castor::SquareMatrix< T, Count > &p_value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Count>
static size_t GetDataSize (Castor::SquareMatrix< T, Count > const &p_value)
Retrieves the value binary size.
static uint8_t const * GetBuffer (Castor::Colour const &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t * GetBuffer (Castor::Colour &p_value)
Retrieves the beginning of the buffer for given value.
static size_t GetDataSize (Castor::Colour const &p_value)
Retrieves the value binary size.
static uint8_t const * GetBuffer (Castor::Size const &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t * GetBuffer (Castor::Size &p_value)
Retrieves the beginning of the buffer for given value.
static size_t GetDataSize (Castor::Size const &p_value)
Retrieves the value binary size.
static uint8_t const * GetBuffer (Castor::Position const &p_value)
Retrieves the beginning of the buffer for given value.
static uint8_t * GetBuffer (Castor::Position &p_value)
Retrieves the beginning of the buffer for given value.
static size_t GetDataSize (Castor::Position const &p_value)
Retrieves the value binary size.
template<typename T >
static uint8_t const * GetBuffer (Castor::QuaternionT< T > const &p_value)
Retrieves the beginning of the buffer for given value.
template<typename T >
static uint8_t * GetBuffer (Castor::QuaternionT< T > &p_value)
Retrieves the beginning of the buffer for given value.
template<typename T >
static size_t GetDataSize (Castor::QuaternionT< T > const &p_value)
Retrieves the value binary size.
static void PrepareChunkData (bool &p_value)
Sets given value to big endian.
static void PrepareChunkData (int8_t &p_value)
Sets given value to big endian.
static void PrepareChunkData (uint8_t &p_value)
Sets given value to big endian.
static void PrepareChunkData (int16_t &p_value)
Sets given value to big endian.
static void PrepareChunkData (uint16_t &p_value)
Sets given value to big endian.
static void PrepareChunkData (int32_t &p_value)
Sets given value to big endian.
static void PrepareChunkData (uint32_t &p_value)
Sets given value to big endian.
static void PrepareChunkData (int64_t &p_value)
Sets given value to big endian.
static void PrepareChunkData (uint64_t &p_value)
Sets given value to big endian.
static void PrepareChunkData (float &p_value)
Sets given value to big endian.
static void PrepareChunkData (double &p_value)
Sets given value to big endian.
static void PrepareChunkData (long double &p_value)
Sets given value to big endian.
template<typename T >
static void PrepareChunkData (std::vector< T > &p_value)
Sets given value to big endian.
template<typename T , size_t Count>
static void PrepareChunkData (std::array< T, Count > &p_value)
Sets given value to big endian.
template<typename T , uint32_t Count>
static void PrepareChunkData (Castor::SquareMatrix< T, Count > &p_value)
Sets given value to big endian.
template<typename T , uint32_t Count>
static void PrepareChunkData (Castor::Point< T, Count > &p_value)
Sets given value to big endian.
template<typename T , uint32_t Count>
static void PrepareChunkData (Castor::Coords< T, Count > &p_value)
Sets given value to big endian.
template<typename T >
static void PrepareChunkData (Castor::QuaternionT< T > &p_value)
Sets given value to big endian.
static void PrepareChunkData (Castor::ColourComponent &p_value)
Sets given value to big endian.
static void PrepareChunkData (Castor::Colour &p_value)
Sets given value to big endian.
template<typename T >
static void PrepareChunkData (InterleavedVertexT< T > &p_value)
Sets given value to big endian.
template<typename T >
static void PrepareChunkData (SubmeshAnimationBufferT< T > &p_value)
Sets given value to big endian.
static void PrepareChunkData (FaceIndices &p_value)
Sets given value to big endian.
static void PrepareChunkData (VertexBoneData &p_value)
Sets given value to big endian.
static void PrepareChunkData (KeyFrame &p_value)
Sets given value to big endian.
template<typename ElementType , typename KeyType >
std::unique_ptr< Cache< ElementType, KeyType > > MakeCache (Engine &p_engine, typename CacheTraits< ElementType, KeyType >::Producer &&p_produce, ElementInitialiser< ElementType > &&p_initialise=[](std::shared_ptr< ElementType >){}, ElementCleaner< ElementType > &&p_clean=[](std::shared_ptr< ElementType >){}, typename CacheTraits< ElementType, KeyType >::Merger &&p_merge=[](CacheBase< ElementType, KeyType > const &, Castor::Collection< ElementType, KeyType > &, std::shared_ptr< ElementType >){})
Creates a cache.
DECLARE_SMART_PTR (GeometryCache)
DECLARE_SMART_PTR (LightCache)
DECLARE_SMART_PTR (MaterialCache)
template<typename ElementType , typename KeyType >
std::unique_ptr< ObjectCache< ElementType, KeyType > > MakeObjectCache (Engine &p_engine, Scene &p_scene, SceneNodeSPtr p_rootNode, SceneNodeSPtr p_rootCameraNode, SceneNodeSPtr p_rootObjectNode, typename ObjectCacheTraits< ElementType, KeyType >::Producer &&p_produce, ElementInitialiser< ElementType > &&p_initialise=[](std::shared_ptr< ElementType >){}, ElementCleaner< ElementType > &&p_clean=[](std::shared_ptr< ElementType >){}, typename ObjectCacheTraits< ElementType, KeyType >::Merger &&p_merge=[](ObjectCacheBase< ElementType, KeyType > const &, Castor::Collection< ElementType, KeyType > &, std::shared_ptr< ElementType >, SceneNodeSPtr, SceneNodeSPtr){}, ElementAttacher< ElementType > &&p_attach=[](std::shared_ptr< ElementType >, SceneNodeSPtr, SceneNodeSPtr, SceneNodeSPtr, SceneNodeSPtr){}, ElementDetacher< ElementType > &&p_detach=[](std::shared_ptr< ElementType >){})
Creates an object cache.
DECLARE_SMART_PTR (OverlayCache)
DECLARE_SMART_PTR (PluginCache)
DECLARE_SMART_PTR (SceneNodeCache)
std::unique_ptr< ShaderProgramCache > MakeCache (Engine &p_engine)
Creates a ShaderProgram cache.
C3D_API void ComputePreLightingMapContributions (GLSL::GlslWriter &p_writer, GLSL::Vec3 &p_normal, GLSL::Float &p_shininess, TextureChannels const &p_textureFlags, ProgramFlags const &p_programFlags, SceneFlags const &p_sceneFlags)
C3D_API void ComputePostLightingMapContributions (GLSL::GlslWriter &p_writer, GLSL::Vec3 &p_ambient, GLSL::Vec3 &p_diffuse, GLSL::Vec3 &p_specular, GLSL::Vec3 &p_emissive, TextureChannels const &p_textureFlags, ProgramFlags const &p_programFlags, SceneFlags const &p_sceneFlags)
template<typename T >
std::unique_ptr< CleanupEvent< T > > MakeCleanupEvent (T &p_object)
Helper function to create a cleanup event.
template<typename Functor >
std::unique_ptr< FunctorEvent< Functor > > MakeFunctorEvent (EventType p_type, Functor p_functor)
Helper function to create a functor event.
template<typename T >
std::unique_ptr< InitialiseEvent< T > > MakeInitialiseEvent (T &p_object)
Helper function to create an initialise event.
C3D_API bool operator== (BufferDeclaration &p_lhs, BufferDeclaration &p_rhs)
Equality operator.
C3D_API bool operator!= (BufferDeclaration &p_lhs, BufferDeclaration &p_rhs)
Equality operator.
bool operator== (BufferElementDeclaration const &p_lhs, BufferElementDeclaration const &p_rhs)
Equality operator.
bool operator!= (BufferElementDeclaration const &p_lhs, BufferElementDeclaration const &p_rhs)
Equality operator.
std::ostream & operator<< (std::ostream &o, Cone const &c)
Stream operator.
std::ostream & operator<< (std::ostream &o, Cube const &c)
Stream operator.
std::ostream & operator<< (std::ostream &o, Cylinder const &c)
Stream operator.
std::ostream & operator<< (std::ostream &o, Icosahedron const &c)
Stream operator.
std::ostream & operator<< (std::ostream &o, Plane const &c)
Stream operator.
std::ostream & operator<< (std::ostream &o, Projection const &c)
Stream operator.
std::ostream & operator<< (std::ostream &o, Sphere const &c)
Stream operator.
std::ostream & operator<< (std::ostream &o, Torus const &c)
Stream operator.
int GetCPUCount ()
C3D_API bool operator== (Castor3D::Version const &p_a, Castor3D::Version const &p_b)
Equality operator.
C3D_API bool operator!= (Castor3D::Version const &p_a, Castor3D::Version const &p_b)
Difference operator.
C3D_API bool operator< (Castor3D::Version const &p_a, Castor3D::Version const &p_b)
Less than operator.
C3D_API bool operator> (Castor3D::Version const &p_a, Castor3D::Version const &p_b)
Less than operator.
C3D_API bool operator<= (Castor3D::Version const &p_a, Castor3D::Version const &p_b)
Less than operator.
C3D_API bool operator>= (Castor3D::Version const &p_a, Castor3D::Version const &p_b)
Less than operator.
C3D_API std::ostream & operator<< (std::ostream &p_stream, Castor3D::Version const &p_version)
C3D_API std::wostream & operator<< (std::wostream &p_stream, Castor3D::Version const &p_version)
C3D_API Castor::String & operator<< (Castor::String &p_stream, Castor3D::Version const &p_version)
DECLARE_SMART_PTR (EventHandler)
DECLARE_SMART_PTR (UserInputEvent)
DECLARE_SMART_PTR (KeyboardEvent)
DECLARE_SMART_PTR (MouseEvent)
DECLARE_SMART_PTR (HandlerEvent)
DECLARE_SMART_PTR (UserInputListener)
DECLARE_MULTIMAP (double, StaticRenderNode, StaticRenderNodeByDistance)
DECLARE_MULTIMAP (double, SkinningRenderNode, SkinningRenderNodeByDistance)
DECLARE_MULTIMAP (double, MorphingRenderNode, MorphingRenderNodeByDistance)
DECLARE_MULTIMAP (double, BillboardRenderNode, BillboardRenderNodeByDistance)
DECLARE_VECTOR (StaticRenderNode, StaticRenderNode)
DECLARE_VECTOR (SkinningRenderNode, SkinningRenderNode)
DECLARE_VECTOR (MorphingRenderNode, MorphingRenderNode)
DECLARE_VECTOR (BillboardRenderNode, BillboardRenderNode)
DECLARE_MAP (RenderPipelineRPtr, StaticRenderNodeArray, StaticRenderNodesByPipeline)
DECLARE_MAP (RenderPipelineRPtr, SkinningRenderNodeArray, SkinningRenderNodesByPipeline)
DECLARE_MAP (RenderPipelineRPtr, MorphingRenderNodeArray, MorphingRenderNodesByPipeline)
DECLARE_MAP (RenderPipelineRPtr, BillboardRenderNodeArray, BillboardRenderNodesByPipeline)
DECLARE_MAP (SubmeshRPtr, StaticRenderNodeArray, SubmeshStaticRenderNodes)
DECLARE_MAP (RenderPipelineRPtr, SubmeshStaticRenderNodesByPassMap, SubmeshStaticRenderNodesByPipeline)
void DoFillShaderDepthMaps (RenderPipeline &p_pipeline, DepthMapArray &p_depthMaps)
void DoBindPass (PassRenderNodeUniforms &p_node, Pass &p_pass, Scene const &p_scene, RenderPipeline &p_pipeline, DepthMapArray &p_depthMaps)
void DoUnbindPass (PassRenderNodeUniforms &p_node, Pass &p_pass, Scene const &p_scene, RenderPipeline &p_pipeline, DepthMapArray const &p_depthMaps)
void DoBindPassOpacityMap (PassRenderNodeUniforms &p_node, Pass &p_pass)
void DoUnbindPassOpacityMap (PassRenderNodeUniforms &p_node, Pass &p_pass)
template<typename DataType , typename InstanceType >
void DoRenderObjectNode (ObjectRenderNode< DataType, InstanceType > &p_node)
void DoRenderNodeNoPass (StaticRenderNode &p_node)
void DoRenderNodeNoPass (BillboardRenderNode &p_node)
void DoRenderNodeNoPass (MorphingRenderNode &p_node)
void DoRenderNodeNoPass (SkinningRenderNode &p_node)
template<typename NodeType >
void DoRenderNode (NodeType &p_node)
bool operator< (PipelineFlags const &p_lhs, PipelineFlags const &p_rhs)
C3D_API bool operator== (ProgramInputLayout const &p_lhs, ProgramInputLayout const &p_rhs)
Equality operator.
C3D_API bool operator!= (ProgramInputLayout const &p_lhs, ProgramInputLayout const &p_rhs)
Equality operator.
std::ostream & operator<< (std::ostream &p_streamOut, TextureUnitSPtr const &p_texture)
Stream operator.
Importer
DECLARE_SMART_PTR (Importer)
Camera
DECLARE_SMART_PTR (Camera)
DECLARE_SMART_PTR (Viewport)
DECLARE_SMART_PTR (IViewportImpl)
DECLARE_SMART_PTR (Ray)
DECLARE_MAP (Castor::String, CameraSPtr, CameraPtrStr)
Camera pointer map, sorted by name.
DECLARE_VECTOR (CameraSPtr, CameraPtr)
Camera pointer array.
Variables
uint32_t const CMSH_VERSION = MAKE_CMSH_VERSION(0x01, 0x01, 0x0000)
static const xchar * INFO_CACHE_CREATED_OBJECT = cuT("Cache::Create - Created ")
static const xchar * WARNING_CACHE_DUPLICATE_OBJECT = cuT("Cache::Create - Duplicate ")
static const xchar * WARNING_CACHE_NULL_OBJECT = cuT("Cache::Insert - nullptr ")
Castor::String const RENDERER_TYPE_UNDEFINED = cuT("Undefined")
static const uint32_t C3D_MAX_BONES_PER_VERTEX = 8
static const uint32_t C3D_MAX_TEXTURE_MATRICES = 4
General
enum MovableType : uint8_t {
MovableType::eCamera, MovableType::eGeometry, MovableType::eLight, MovableType::eBillboard,
MovableType::eParticleEmitter
}
Movable object types enumerator.
enum TargetType : uint8_t { TargetType::eWindow, TargetType::eTexture }
RenderTarget supported types.
enum PluginType : uint8_t {
PluginType::eRenderer, PluginType::eImporter, PluginType::eDivider, PluginType::eGenerator,
PluginType::eTechnique, PluginType::eToneMapping, PluginType::ePostEffect, PluginType::eGeneric,
PluginType::eParticle
}
Plugin types enumeration.
enum BufferComponent : uint8_t { BufferComponent::eNone = 0, BufferComponent::eColour = 1 << 0, BufferComponent::eDepth = 1 << 1, BufferComponent::eStencil = 1 << 2 }
Frame buffer components enumeration.
enum WindowBuffer : uint8_t {
WindowBuffer::eNone, WindowBuffer::eFrontLeft, WindowBuffer::eFrontRight, WindowBuffer::eBackLeft,
WindowBuffer::eBackRight, WindowBuffer::eFront, WindowBuffer::eBack, WindowBuffer::eLeft,
WindowBuffer::eRight, WindowBuffer::eFrontAndBack
}
Frame buffer components enumeration.
enum FrameBufferTarget : uint8_t { FrameBufferTarget::eDraw, FrameBufferTarget::eRead, FrameBufferTarget::eBoth }
Frame buffer binding targets enumeration.
enum FrameBufferMode : uint8_t { FrameBufferMode::eConfig, FrameBufferMode::eAutomatic, FrameBufferMode::eManual }
Frame buffer binding modes enumeration.
enum AttachmentPoint : uint8_t {
AttachmentPoint::eNone, AttachmentPoint::eColour, AttachmentPoint::eDepth, AttachmentPoint::eStencil,
AttachmentPoint::eDepthStencil
}
Frame buffer attachment points enumeration.
enum AttachmentType : uint8_t { AttachmentType::eTexture, AttachmentType::eBuffer }
Frame buffer attachment types enumeration.
enum ViewportType : uint8_t { ViewportType::eOrtho, ViewportType::ePerspective, ViewportType::eFrustum }
The viewport projection types enumeration.
enum FrustumPlane {
FrustumPlane::eNear, FrustumPlane::eFar, FrustumPlane::eLeft, FrustumPlane::eRight,
FrustumPlane::eTop, FrustumPlane::eBottom
}
Frustum view planes enumeration.
enum EventType : uint8_t { EventType::ePreRender, EventType::eQueueRender, EventType::ePostRender }
Frame Event Type enumeration.
enum Culling : uint8_t { Culling::eNone, Culling::eFront, Culling::eBack, Culling::eFrontAndBack }
Culled faces enumeration.
enum FillMode : uint8_t { FillMode::ePoint, FillMode::eLine, FillMode::eSolid }
Polygon rasterisation modes enumeration.
enum QueryType : uint32_t {
QueryType::eTimeElapsed, QueryType::eSamplesPassed, QueryType::eAnySamplesPassed, QueryType::ePrimitivesGenerated,
QueryType::eTransformFeedbackPrimitivesWritten, QueryType::eAnySamplesPassedConservative, QueryType::eTimestamp
}
GPU query supported types enumeration.
enum QueryInfo : uint32_t { QueryInfo::eResult, QueryInfo::eResultAvailable, QueryInfo::eResultNoWait }
GPU query supported informations enumeration.
enum MemoryBarrier : uint32_t {
MemoryBarrier::eVertexBuffer = 0x01 << 0, MemoryBarrier::eIndexBuffer = 0x01 << 1, MemoryBarrier::eUniformBuffer = 0x01 << 2, MemoryBarrier::eAtomicCounterBuffer = 0x01 << 3,
MemoryBarrier::eQueryBuffer = 0x01 << 4, MemoryBarrier::eShaderStorageBuffer = 0x01 << 5, MemoryBarrier::eAll = 0xFFFFFFFF
}
Supported memory barriers enumeration.
using ParticleFactory = Castor::Factory< CpuParticleSystem, Castor::String, CpuParticleSystemUPtr, std::function< CpuParticleSystemUPtr(ParticleSystem &) > >
template<typename ElementType >
using ElementInitialiser = std::function< void(std::shared_ptr< ElementType >) >
template<typename ElementType >
using ElementCleaner = std::function< void(std::shared_ptr< ElementType >) >
template<typename ElementType , typename KeyType >
using ElementMerger = std::function< void(CacheBase< ElementType, KeyType > const &, Castor::Collection< ElementType, KeyType > &, std::shared_ptr< ElementType >) >
using ListenerCache = Cache< FrameListener, Castor::String >
using MeshCache = Cache< Mesh, Castor::String >
using SamplerCache = Cache< Sampler, Castor::String >
using SceneCache = Cache< Scene, Castor::String >
using RenderTechniqueCache = Cache< RenderTechnique, Castor::String >
using RenderWindowCache = Cache< RenderWindow, Castor::String >
template<typename ElementType >
using ElementAttacher = std::function< void(std::shared_ptr< ElementType >, SceneNodeSPtr, SceneNodeSPtr, SceneNodeSPtr, SceneNodeSPtr) >
template<typename ElementType >
using ElementDetacher = std::function< void(std::shared_ptr< ElementType >) >
using AnimatedObjectGroupCache = Cache< AnimatedObjectGroup, Castor::String >
using BillboardListCache = ObjectCache< BillboardList, Castor::String >
using CameraCache = ObjectCache< Camera, Castor::String >
typedef std::map< Castor::String, RenderWindowSPtr > WindowPtrStrMap
DECLARE_SMART_PTR (RenderBuffer)
DECLARE_SMART_PTR (ColourRenderBuffer)
DECLARE_SMART_PTR (DepthStencilRenderBuffer)
DECLARE_SMART_PTR (FrameBufferAttachment)
DECLARE_SMART_PTR (RenderBufferAttachment)
DECLARE_SMART_PTR (TextureAttachment)
DECLARE_SMART_PTR (FrameBuffer)
DECLARE_SMART_PTR (BackBuffers)
DECLARE_SMART_PTR (Engine)
DECLARE_SMART_PTR (Plugin)
DECLARE_SMART_PTR (RendererPlugin)
DECLARE_SMART_PTR (ImporterPlugin)
DECLARE_SMART_PTR (DividerPlugin)
DECLARE_SMART_PTR (GenericPlugin)
DECLARE_SMART_PTR (PostFxPlugin)
DECLARE_SMART_PTR (ParticlePlugin)
DECLARE_SMART_PTR (FrameEvent)
DECLARE_SMART_PTR (FrameListener)
DECLARE_SMART_PTR (IWindowHandle)
DECLARE_SMART_PTR (GpuQuery)
DECLARE_SMART_PTR (PickingPass)
DECLARE_SMART_PTR (TransformFeedback)
DECLARE_SMART_PTR (ComputePipeline)
DECLARE_SMART_PTR (ListenerCache)
DECLARE_SMART_PTR (ShaderProgramCache)
DECLARE_SMART_PTR (RenderTargetCache)
DECLARE_SMART_PTR (BillboardListCache)
DECLARE_VECTOR (real, Real)
real array
DECLARE_VECTOR (RenderWindowSPtr, RenderWindowPtr)
RenderWindow pointer array.
DECLARE_VECTOR (RenderBufferSPtr, RenderBufferPtr)
RenderBuffer pointer array.
DECLARE_VECTOR (FrameEventUPtr, FrameEventPtr)
FrameEvent pointer array.
DECLARE_MAP (Castor::String, FrameListenerSPtr, FrameListenerPtrStr)
FrameListener pointer map, sorted by name.
DECLARE_MAP (uint32_t, RenderWindowSPtr, RenderWindow)
RenderWindow pointer map, sorted by index.
DECLARE_MAP (Castor::String, PluginSPtr, PluginStr)
Plugin map, sorted by name.
DECLARE_MAP (int, Castor::String, StrInt)
DECLARE_VECTOR (PostEffectSPtr, PostEffectPtr)
DECLARE_VECTOR (BillboardListSPtr, BillboardList)
DECLARE_MAP (Castor::String, RendererPluginSPtr, RendererPtr)
DECLARE_ARRAY (PluginStrMap, PluginType::eCount, PluginStrMap)
DECLARE_MAP (Castor::Path, Castor::DynamicLibrarySPtr, DynamicLibraryPtrPath)
DECLARE_ARRAY (DynamicLibraryPtrPathMap, PluginType::eCount, DynamicLibraryPtrPathMap)
DECLARE_MAP (Castor::Path, PluginType, PluginTypePath)
DECLARE_MAP (Castor::String, BillboardListSPtr, BillboardListStr)
Animation
enum AnimationType : uint8_t { AnimationType::eMovable, AnimationType::eSkeleton, AnimationType::eMesh }
Animation types enumeration.
enum InterpolatorType : uint8_t { InterpolatorType::eNearest, InterpolatorType::eLinear }
Interpolation modes enumeration.
enum AnimationState : uint8_t { AnimationState::ePlaying, AnimationState::eStopped, AnimationState::ePaused }
Animation State Enumerator.
enum SkeletonAnimationObjectType : uint8_t { SkeletonAnimationObjectType::eNode, SkeletonAnimationObjectType::eBone }
Class which represents the moving things.
using SubmeshAnimationBuffer = SubmeshAnimationBufferT< float >
using SubmeshAnimationBufferArray = std::vector< SubmeshAnimationBuffer >
using GroupAnimationMap = std::map< Castor::String, GroupAnimation >
using Point3rInterpolator = Interpolator< Castor::Point3r >
using QuaternionInterpolator = Interpolator< Castor::Quaternion >
using KeyFrameRealMap = std::map< real, KeyFrame >
using KeyFrameArray = std::vector< KeyFrame >
DECLARE_SMART_PTR (Animation)
DECLARE_SMART_PTR (SkeletonAnimation)
DECLARE_SMART_PTR (SkeletonAnimationObject)
DECLARE_SMART_PTR (SkeletonAnimationBone)
DECLARE_SMART_PTR (SkeletonAnimationNode)
DECLARE_SMART_PTR (MeshAnimation)
DECLARE_SMART_PTR (MeshAnimationSubmesh)
DECLARE_SMART_PTR (Animable)
DECLARE_MAP (Castor::String, AnimationSPtr, AnimationPtrStr)
Animation pointer map, sorted by name.
DECLARE_MAP (Castor::String, SkeletonAnimationObjectSPtr, SkeletonAnimationObjectPtrStr)
SkeletonAnimationObject pointer map, sorted by name.
DECLARE_VECTOR (SkeletonAnimationObjectSPtr, SkeletonAnimationObjectPtr)
SkeletonAnimationObject pointer array.
DECLARE_VECTOR (MeshAnimationSubmesh, MeshAnimationSubmesh)
SkeletonAnimationObject array.
Geometry
enum MeshType : uint8_t {
MeshType::eCustom, MeshType::eCone, MeshType::eCylinder, MeshType::eSphere,
MeshType::eCube, MeshType::eTorus, MeshType::ePlane, MeshType::eIcosahedron,
MeshType::eProjection
}
Mesh type enumeration.
typedef Pattern< Vertex > VertexPattern
typedef Pattern< Castor::Point3r > Point3rPattern
typedef Pattern< VertexSPtr > VertexPtrPattern
typedef Pattern< Castor::Point3rSPtr > Point3rPtrPattern
DECLARE_SMART_PTR (Vertex)
DECLARE_SMART_PTR (BufferElementGroup)
DECLARE_SMART_PTR (VertexPattern)
DECLARE_SMART_PTR (Point3rPattern)
DECLARE_SMART_PTR (VertexPtrPattern)
DECLARE_SMART_PTR (Face)
DECLARE_SMART_PTR (Graph)
DECLARE_SMART_PTR (Mesh)
DECLARE_SMART_PTR (MeshGenerator)
DECLARE_SMART_PTR (Submesh)
DECLARE_SMART_PTR (Cone)
DECLARE_SMART_PTR (Cylinder)
DECLARE_SMART_PTR (Icosahedron)
DECLARE_SMART_PTR (Cube)
DECLARE_SMART_PTR (Plane)
DECLARE_SMART_PTR (Projection)
DECLARE_SMART_PTR (Sphere)
DECLARE_SMART_PTR (Torus)
DECLARE_SMART_PTR (Geometry)
DECLARE_SMART_PTR (MovableObject)
DECLARE_SMART_PTR (Subdivider)
DECLARE_SMART_PTR (FaceGroup)
DECLARE_SMART_PTR (Bone)
DECLARE_SMART_PTR (Skeleton)
DECLARE_SMART_PTR (BonedVertex)
DECLARE_SMART_PTR (MeshFactory)
DECLARE_VECTOR (Vertex, Vertex)
Vertex array.
DECLARE_VECTOR (BufferElementGroupSPtr, VertexPtr)
Vertex pointer array.
DECLARE_VECTOR (Face, Face)
Face array.
DECLARE_VECTOR (FaceSPtr, FacePtr)
Face pointer array.
DECLARE_VECTOR (FaceGroupSPtr, FaceGroupPtr)
FaceGroup pointer array.
DECLARE_VECTOR (SubmeshSPtr, SubmeshPtr)
Submesh pointer array.
DECLARE_VECTOR (GeometrySPtr, GeometryPtr)
Geometry pointer array.
DECLARE_LIST (VertexSPtr, VertexPtr)
Vertex pointer list.
DECLARE_MAP (Castor::String, MeshSPtr, MeshPtrStr)
Mesh pointer array.
DECLARE_MAP (Castor::String, MovableObjectSPtr, MovableObjectPtrStr)
MovableObject pointer map, sorted by name.
DECLARE_MAP (Castor::String, GeometrySPtr, GeometryPtrStr)
Geometry pointer map, sorted by name.
DECLARE_MAP (uint32_t, int, IntUInt)
DECLARE_MAP (Castor::String, SubmeshSPtr, SubmeshPtrStr)
DECLARE_MAP (Castor::String, int, IntStr)
DECLARE_VECTOR (BoneSPtr, BonePtr)
Bone pointer array.
DECLARE_MAP (Castor::String, BoneSPtr, BonePtrStr)
Bone pointer map sorted by name.
DECLARE_VECTOR (BonedVertexSPtr, BonedVertexPtr)
BonedVertex pointer array.
Light
enum LightType : uint8_t { LightType::eDirectional, LightType::ePoint, LightType::eSpot }
Light types enumeration.
DECLARE_SMART_PTR (Light)
DECLARE_SMART_PTR (LightCategory)
DECLARE_SMART_PTR (DirectionalLight)
DECLARE_SMART_PTR (PointLight)
DECLARE_SMART_PTR (SpotLight)
DECLARE_SMART_PTR (LightFactory)
DECLARE_VECTOR (LightSPtr, LightPtr)
Array of lights.
DECLARE_MAP (Castor::String, LightSPtr, LightPtrStr)
Map of lights, sorted by name.
DECLARE_MAP (int, LightSPtr, LightPtrInt)
Map of lights, sorted by index.
Material
enum MaterialType { MaterialType::eLegacy }
Supported material types enumeration.
enum ComparisonFunc : uint8_t {
ComparisonFunc::eAlways, ComparisonFunc::eLess, ComparisonFunc::eLEqual, ComparisonFunc::eEqual,
ComparisonFunc::eNEqual, ComparisonFunc::eGEqual, ComparisonFunc::eGreater, ComparisonFunc::eNever
}
Alpha functions enumeration.
enum TextureUVW : uint8_t { TextureUVW::eU, TextureUVW::eV, TextureUVW::eW }
Texture UVW enumeration.
enum WrapMode : uint8_t { WrapMode::eRepeat, WrapMode::eMirroredRepeat, WrapMode::eClampToBorder, WrapMode::eClampToEdge }
Texture wrap modes enumeration.
enum InterpolationFilter : uint8_t { InterpolationFilter::eMin, InterpolationFilter::eMag, InterpolationFilter::eMip, InterpolationFilter::eCount }
Texture interpolation filters enumeration.
enum ComparisonMode : uint8_t { ComparisonMode::eNone, ComparisonMode::eRefToTexture }
Texture comparison modes enumeration.
enum InterpolationMode : uint8_t { InterpolationMode::eUndefined, InterpolationMode::eNearest, InterpolationMode::eLinear }
Texture filter interpolation modes enumeration.
enum BlendSrcIndex : uint8_t { BlendSrcIndex::eIndex0, BlendSrcIndex::eIndex1, BlendSrcIndex::eIndex2 }
Texture blending source indices enumeration.
enum BlendSource : uint8_t {
BlendSource::eTexture, BlendSource::eTexture0, BlendSource::eTexture1, BlendSource::eTexture2,
BlendSource::eTexture3, BlendSource::eConstant, BlendSource::eDiffuse, BlendSource::ePrevious
}
Texture blending sources enumeration.
enum ColourBlendFunc : uint8_t {
ColourBlendFunc::eNoBlend, ColourBlendFunc::eFirstArg, ColourBlendFunc::eAdd, ColourBlendFunc::eAddSigned,
ColourBlendFunc::eModulate, ColourBlendFunc::eInterpolate, ColourBlendFunc::eSubtract, ColourBlendFunc::eDot3RGB,
ColourBlendFunc::eDot3RGBA
}
RGB blending functions enumeration.
enum AlphaBlendFunc : uint8_t {
AlphaBlendFunc::eNoBlend, AlphaBlendFunc::eFirstArg, AlphaBlendFunc::eAdd, AlphaBlendFunc::eAddSigned,
AlphaBlendFunc::eModulate, AlphaBlendFunc::eInterpolate, AlphaBlendFunc::eSubtract
}
Alpha blending functions enumeration.
enum BlendOperation : uint8_t {
BlendOperation::eAdd, BlendOperation::eSubtract, BlendOperation::eRevSubtract, BlendOperation::eMin,
BlendOperation::eMax, BlendOperation::eCount
}
Blending operations enumeration.
enum BlendOperand : uint8_t {
BlendOperand::eZero, BlendOperand::eOne, BlendOperand::eSrcColour, BlendOperand::eInvSrcColour,
BlendOperand::eDstColour, BlendOperand::eInvDstColour, BlendOperand::eSrcAlpha, BlendOperand::eInvSrcAlpha,
BlendOperand::eDstAlpha, BlendOperand::eInvDstAlpha, BlendOperand::eConstant, BlendOperand::eInvConstant,
BlendOperand::eSrcAlphaSaturate, BlendOperand::eSrc1Colour, BlendOperand::eInvSrc1Colour, BlendOperand::eSrc1Alpha,
BlendOperand::eInvSrc1Alpha
}
Blend operands enumeration.
enum BlendMode : uint8_t {
BlendMode::eNoBlend, BlendMode::eAdditive, BlendMode::eMultiplicative, BlendMode::eInterpolative,
BlendMode::eABuffer, BlendMode::eDepthPeeling
}
Blending modes enumeration.
enum TextureType : uint8_t {
TextureType::eBuffer, TextureType::eOneDimension, TextureType::eOneDimensionArray, TextureType::eTwoDimensions,
TextureType::eTwoDimensionsArray, TextureType::eTwoDimensionsMS, TextureType::eTwoDimensionsMSArray, TextureType::eThreeDimensions,
TextureType::eCube, TextureType::eCubeArray
}
Texture dimensions enumeration.
enum TextureStorageType : uint8_t {
TextureStorageType::eBuffer, TextureStorageType::eOneDimension, TextureStorageType::eOneDimensionArray, TextureStorageType::eTwoDimensions,
TextureStorageType::eTwoDimensionsArray, TextureStorageType::eTwoDimensionsMS, TextureStorageType::eThreeDimensions, TextureStorageType::eCubeMap,
TextureStorageType::eCubeMapArray
}
Texture dimensions enumeration.
enum CubeMapFace : uint8_t {
CubeMapFace::ePositiveX, CubeMapFace::eNegativeX, CubeMapFace::ePositiveY, CubeMapFace::eNegativeY,
CubeMapFace::ePositiveZ, CubeMapFace::eNegativeZ
}
Cube map faces.
enum TextureChannel : uint16_t {
TextureChannel::eUndefined = 0x0000, TextureChannel::eColour = 0x0001, TextureChannel::eDiffuse = 0x0002, TextureChannel::eNormal = 0x0004,
TextureChannel::eOpacity = 0x0008, TextureChannel::eSpecular = 0x0010, TextureChannel::eHeight = 0x0020, TextureChannel::eAmbient = 0x0040,
TextureChannel::eGloss = 0x0080, TextureChannel::eEmissive = 0x0100, TextureChannel::eAll = 0x0FFF, TextureChannel::eText = 0x1000
}
Texture channels enumeration.
DECLARE_SMART_PTR (TextureImage)
DECLARE_SMART_PTR (TextureLayout)
DECLARE_SMART_PTR (TextureStorage)
DECLARE_SMART_PTR (TextureUnit)
DECLARE_SMART_PTR (Material)
DECLARE_SMART_PTR (Pass)
DECLARE_SMART_PTR (LegacyPass)
DECLARE_SMART_PTR (Sampler)
DECLARE_VECTOR (MaterialSPtr, MaterialPtr)
Material pointer array.
DECLARE_VECTOR (TextureUnit, TextureUnit)
TextureUnit array.
DECLARE_VECTOR (TextureUnitSPtr, TextureUnitPtr)
TextureUnit pointer array.
DECLARE_VECTOR (Pass, Pass)
Pass array.
DECLARE_VECTOR (PassSPtr, PassPtr)
Pass pointer array.
DECLARE_VECTOR (uint32_t, UInt)
uint32_t array
DECLARE_MAP (Castor::String, MaterialSPtr, MaterialPtrStr)
Material pointer map, sorted by name.
DECLARE_MAP (uint32_t, MaterialSPtr, MaterialPtrUInt)
Material pointer map.
DECLARE_VECTOR (std::reference_wrapper< TextureUnit >, DepthMap)
TextureUnit reference array.
Overlay
enum OverlayType : uint8_t { OverlayType::ePanel, OverlayType::eBorderPanel, OverlayType::eText }
Overlay types enumeration.
enum TextWrappingMode { TextWrappingMode::eNone, TextWrappingMode::eBreak, TextWrappingMode::eBreakWords }
Text wrapping modes, handles the way text is cut when it overflows the overlay width.
enum TextTexturingMode { TextTexturingMode::eLetter, TextTexturingMode::eText }
Text texturing modes, handles the way textures are appied to text overlays.
enum TextLineSpacingMode { TextLineSpacingMode::eOwnHeight, TextLineSpacingMode::eMaxLineHeight, TextLineSpacingMode::eMaxFontHeight }
Text line spacing modes, handles the way lines are spaced, which each other, inside one TextOverlay.
enum HAlign { HAlign::eLeft, HAlign::eCenter, HAlign::eRight }
Horizontal alignments for text overlays.
enum VAlign { VAlign::eTop, VAlign::eCenter, VAlign::eBottom }
Vertical alignments for text overlays.
enum BorderPosition { BorderPosition::eInternal, BorderPosition::eMiddle, BorderPosition::eExternal }
Text wrapping modes, handles the way text is cut when it overflows the overlay width.
DECLARE_SMART_PTR (OverlayFactory)
DECLARE_SMART_PTR (OverlayRenderer)
DECLARE_SMART_PTR (FontTexture)
DECLARE_SMART_PTR (Overlay)
DECLARE_SMART_PTR (OverlayCategory)
DECLARE_SMART_PTR (PanelOverlay)
DECLARE_SMART_PTR (BorderPanelOverlay)
DECLARE_SMART_PTR (TextOverlay)
DECLARE_VECTOR (OverlaySPtr, OverlayPtr)
DECLARE_MAP (Castor::String, OverlaySPtr, OverlayPtrStr)
Render
enum MatrixMode : uint8_t {
MatrixMode::eProjection, MatrixMode::eModel, MatrixMode::eView, MatrixMode::eTexture0,
MatrixMode::eTexture1, MatrixMode::eTexture2, MatrixMode::eTexture3, MatrixMode::eTexture4,
MatrixMode::eTexture5, MatrixMode::eTexture6, MatrixMode::eTexture7, MatrixMode::eTexture8,
MatrixMode::eTexture9, MatrixMode::eTexture10, MatrixMode::eTexture11, MatrixMode::eTexture12,
MatrixMode::eTexture13, MatrixMode::eTexture14, MatrixMode::eTexture15
}
Matrix modes enumeration.
enum AccessType : uint8_t { AccessType::eNone = 0, AccessType::eRead = 1 << 0, AccessType::eWrite = 1 << 1 }
Access types enumeration.
enum BufferAccessType : uint32_t { BufferAccessType::eStatic = 1 << 0, BufferAccessType::eDynamic = 1 << 1, BufferAccessType::eStream = 1 << 2 }
Buffer access types enumeration.
enum BufferAccessNature : uint32_t { BufferAccessNature::eDraw = 1 << 4, BufferAccessNature::eRead = 1 << 5, BufferAccessNature::eCopy = 1 << 6 }
Buffer access natures enumeration.
enum Topology : uint8_t {
Topology::ePoints, Topology::eLines, Topology::eLineLoop, Topology::eLineStrip,
Topology::eTriangles, Topology::eTriangleStrips, Topology::eTriangleFan, Topology::eQuads,
Topology::eQuadStrips, Topology::ePolygon
}
Primitive draw types enumeration.
enum DepthFunc : uint8_t {
DepthFunc::eNever, DepthFunc::eLess, DepthFunc::eEqual, DepthFunc::eLEqual,
DepthFunc::eGreater, DepthFunc::eNEqual, DepthFunc::eGEqual, DepthFunc::eAlways
}
Depth functions enumeration.
enum WritingMask : uint8_t { WritingMask::eZero, WritingMask::eAll }
Wrinting masks enumeration.
enum StencilFunc : uint8_t {
StencilFunc::eNever, StencilFunc::eLess, StencilFunc::eEqual, StencilFunc::eLEqual,
StencilFunc::eGreater, StencilFunc::eNEqual, StencilFunc::eGEqual, StencilFunc::eAlways
}
Stencil functions enumeration.
enum StencilOp : uint8_t {
StencilOp::eKeep, StencilOp::eZero, StencilOp::eReplace, StencilOp::eIncrement,
StencilOp::eIncrWrap, StencilOp::eDecrement, StencilOp::eDecrWrap, StencilOp::eInvert
}
Stencil functions enumeration.
enum ElementUsage : uint32_t {
ElementUsage::eUnknown = 0x000, ElementUsage::ePosition = 0x001, ElementUsage::eNormal = 0x002, ElementUsage::eTangent = 0x004,
ElementUsage::eBitangent = 0x008, ElementUsage::eDiffuse = 0x010, ElementUsage::eTexCoords = 0x020, ElementUsage::eBoneIds0 = 0x040,
ElementUsage::eBoneIds1 = 0x080, ElementUsage::eBoneWeights0 = 0x100, ElementUsage::eBoneWeights1 = 0x200, ElementUsage::eTransform = 0x400
}
Element usage enumeration.
enum ElementType : uint8_t {
ElementType::eFloat, ElementType::eVec2, ElementType::eVec3, ElementType::eVec4,
ElementType::eColour, ElementType::eInt, ElementType::eIVec2, ElementType::eIVec3,
ElementType::eIVec4, ElementType::eUInt, ElementType::eUIVec2, ElementType::eUIVec3,
ElementType::eUIVec4, ElementType::eMat2, ElementType::eMat3, ElementType::eMat4
}
Element type enumeration.
enum BufferType : uint32_t {
BufferType::eArray, BufferType::eElementArray, BufferType::eUniform, BufferType::eAtomicCounter,
BufferType::eShaderStorage
}
GPU buffers types enumeration.
using VertexBufferArray = std::vector< std::reference_wrapper< VertexBuffer > >
using RenderQueueArray = std::vector< std::reference_wrapper< RenderQueue > >
static const uint64_t MASK_MTXMODE_PROJECTION = uint64_t(0x1) << int(MatrixMode::eProjection)
Matrix modes masks.
static const uint64_t MASK_MTXMODE_MODEL = uint64_t(0x1) << int(MatrixMode::eModel)
static const uint64_t MASK_MTXMODE_VIEW = uint64_t(0x1) << int(MatrixMode::eView)
static const uint64_t MASK_MTXMODE_TEXTURE0 = uint64_t(0x1) << int(MatrixMode::eTexture0)
static const uint64_t MASK_MTXMODE_TEXTURE1 = uint64_t(0x1) << int(MatrixMode::eTexture1)
static const uint64_t MASK_MTXMODE_TEXTURE2 = uint64_t(0x1) << int(MatrixMode::eTexture2)
static const uint64_t MASK_MTXMODE_TEXTURE3 = uint64_t(0x1) << int(MatrixMode::eTexture3)
static const uint64_t MASK_MTXMODE_TEXTURE4 = uint64_t(0x1) << int(MatrixMode::eTexture4)
static const uint64_t MASK_MTXMODE_TEXTURE5 = uint64_t(0x1) << int(MatrixMode::eTexture5)
static const uint64_t MASK_MTXMODE_TEXTURE6 = uint64_t(0x1) << int(MatrixMode::eTexture6)
static const uint64_t MASK_MTXMODE_TEXTURE7 = uint64_t(0x1) << int(MatrixMode::eTexture7)
static const uint64_t MASK_MTXMODE_TEXTURE8 = uint64_t(0x1) << int(MatrixMode::eTexture8)
static const uint64_t MASK_MTXMODE_TEXTURE9 = uint64_t(0x1) << int(MatrixMode::eTexture9)
static const uint64_t MASK_MTXMODE_TEXTURE10 = uint64_t(0x1) << int(MatrixMode::eTexture10)
static const uint64_t MASK_MTXMODE_TEXTURE11 = uint64_t(0x1) << int(MatrixMode::eTexture11)
static const uint64_t MASK_MTXMODE_TEXTURE12 = uint64_t(0x1) << int(MatrixMode::eTexture12)
static const uint64_t MASK_MTXMODE_TEXTURE13 = uint64_t(0x1) << int(MatrixMode::eTexture13)
static const uint64_t MASK_MTXMODE_TEXTURE14 = uint64_t(0x1) << int(MatrixMode::eTexture14)
static const uint64_t MASK_MTXMODE_TEXTURE15 = uint64_t(0x1) << int(MatrixMode::eTexture15)
static Castor::String const GetTopologyName (Topology p_topology)
Gets the name of the given topology.
uint32_t GetSize (ElementType p_type)
Gets the byte size of the given element type.
C3D_API Castor::String GetName (ElementType p_type)
Gets the name of the given element type.
DECLARE_SMART_PTR (RenderSystem)
DECLARE_SMART_PTR (GeometryBuffers)
DECLARE_SMART_PTR (BufferElementDeclaration)
DECLARE_SMART_PTR (BufferDeclaration)
DECLARE_SMART_PTR (VertexBuffer)
DECLARE_SMART_PTR (IndexBuffer)
DECLARE_SMART_PTR (TextureBuffer)
DECLARE_SMART_PTR (Context)
DECLARE_SMART_PTR (DepthStencilState)
DECLARE_SMART_PTR (RasteriserState)
DECLARE_SMART_PTR (BlendState)
DECLARE_SMART_PTR (MultisampleState)
DECLARE_SMART_PTR (RenderPipeline)
DECLARE_SMART_PTR (ToneMapping)
DECLARE_SMART_PTR (PostEffect)
DECLARE_SMART_PTR (ShadowMapPass)
DECLARE_SMART_PTR (RenderTechnique)
DECLARE_SMART_PTR (RenderWindow)
DECLARE_SMART_PTR (RenderLoop)
DECLARE_SMART_PTR (RenderTarget)
DECLARE_SMART_PTR (ShadowMap)
DECLARE_MAP (RenderWindow *, ContextSPtr, ContextPtr)
DECLARE_MAP (std::thread::id, ContextPtrMap, ContextPtrMapId)
Scene
enum SceneFlag : uint16_t {
SceneFlag::eNone = 0x0000, SceneFlag::eFogLinear = 0x0001, SceneFlag::eFogExponential = 0x0002, SceneFlag::eFogSquaredExponential = 0x0003,
SceneFlag::eShadowFilterRaw = 0x0004, SceneFlag::eShadowFilterPoisson = 0x0008, SceneFlag::eShadowFilterStratifiedPoisson = 0x000C
}
Scene flags enumeration.
enum BillboardType { BillboardType::eSpherical, BillboardType::eCylindrical }
Billboard rendering types enumeration.
enum BillboardSize { BillboardSize::eDynamic, BillboardSize::eFixed }
Billboard sizing types enumeration.
C3D_API GLSL::ShadowType GetShadowType (SceneFlags const &p_flags)
Gives the shadow filter type matching the given flags.
C3D_API GLSL::FogType GetFogType (SceneFlags const &p_flags)
Gives the fog type matching the given flags.
DECLARE_SMART_PTR (SceneNode)
DECLARE_SMART_PTR (Scene)
DECLARE_SMART_PTR (SceneFileContext)
DECLARE_SMART_PTR (SceneFileParser)
DECLARE_SMART_PTR (Skybox)
DECLARE_SMART_PTR (ParticleSystem)
DECLARE_SMART_PTR (ParticleSystemImpl)
DECLARE_SMART_PTR (CpuParticleSystem)
DECLARE_SMART_PTR (TransformFeedbackParticleSystem)
DECLARE_SMART_PTR (ComputeParticleSystem)
DECLARE_SMART_PTR (AnimatedObject)
DECLARE_SMART_PTR (AnimatedObjectGroup)
DECLARE_SMART_PTR (AnimatedSkeleton)
DECLARE_SMART_PTR (AnimatedMesh)
DECLARE_SMART_PTR (AnimationInstance)
DECLARE_SMART_PTR (SkeletonAnimationInstance)
DECLARE_SMART_PTR (SkeletonAnimationInstanceObject)
DECLARE_SMART_PTR (SkeletonAnimationInstanceNode)
DECLARE_SMART_PTR (SkeletonAnimationInstanceBone)
DECLARE_SMART_PTR (MeshAnimationInstance)
DECLARE_SMART_PTR (BillboardBase)
DECLARE_SMART_PTR (BillboardList)
DECLARE_VECTOR (SceneNodeSPtr, SceneNodePtr)
SceneNode pointer array.
DECLARE_MAP (Castor::String, SceneSPtr, ScenePtrStr)
Scene pointer map, sorted by name.
DECLARE_MAP (Castor::String, SceneNodeSPtr, SceneNodePtrStr)
SceneNode pointer map, sorted by name.
DECLARE_MAP (Castor::String, AnimatedObjectGroupSPtr, AnimatedObjectGroupPtrStr)
AnimatedObjectGroup pointer map, sorted by name.
DECLARE_MAP (Castor::String, AnimatedObjectSPtr, AnimatedObjectPtrStr)
AnimatedObject pointer map, sorted by name.
DECLARE_MAP (Castor::String, SkeletonAnimationInstanceObjectSPtr, SkeletonAnimationInstanceObjectPtrStr)
MovingObject pointer map, sorted by name.
DECLARE_VECTOR (SkeletonAnimationInstanceObjectSPtr, SkeletonAnimationInstanceObjectPtr)
SkeletonAnimationInstanceObject pointer array.
DECLARE_MAP (uint32_t, MeshAnimationInstanceSubmesh, MeshAnimationInstanceSubmesh)
MeshAnimationInstanceSubmesh map, sorted by submesh ID.
DECLARE_MAP (Castor::String, AnimationInstanceUPtr, AnimationInstancePtrStr)
Animation pointer map, sorted by name.
DECLARE_VECTOR (std::reference_wrapper< SkeletonAnimationInstance >, SkeletonAnimationInstance)
Skeleton animation instance pointer array.
Shader
enum ShaderModel : uint8_t {
ShaderModel::eModel1, ShaderModel::eModel2, ShaderModel::eModel3, ShaderModel::eModel4,
ShaderModel::eModel5
}
Enumeration of existing shader models.
enum ShaderStatus : uint8_t { ShaderStatus::eDontExist, ShaderStatus::eNotCompiled, ShaderStatus::eError, ShaderStatus::eCompiled }
Shader status enueration.
enum ProgramStatus : uint8_t { ProgramStatus::eNotLinked, ProgramStatus::eError, ProgramStatus::eLinked }
Program status enumeration.
enum ShaderType : int8_t {
ShaderType::eNone = -1, ShaderType::eVertex, ShaderType::eHull, ShaderType::eDomain,
ShaderType::eGeometry, ShaderType::ePixel, ShaderType::eCompute
}
Shader object types enumeration.
enum ShaderTypeFlag : uint8_t {
ShaderTypeFlag::eVertex = uint8_t(0x1) << int(ShaderType::eVertex), ShaderTypeFlag::eHull = uint8_t(0x1) << int(ShaderType::eHull), ShaderTypeFlag::eDomain = uint8_t(0x1) << int(ShaderType::eDomain), ShaderTypeFlag::eGeometry = uint8_t(0x1) << int(ShaderType::eGeometry),
ShaderTypeFlag::ePixel = uint8_t(0x1) << int(ShaderType::ePixel), ShaderTypeFlag::eCompute = uint8_t(0x1) << int(ShaderType::eCompute)
}
Shader object types masks.
enum ProgramFlag : uint16_t {
ProgramFlag::eInstantiation = 0x0001, ProgramFlag::eSkinning = 0x0002, ProgramFlag::eBillboards = 0x0004, ProgramFlag::eMorphing = 0x0008,
ProgramFlag::eAlphaBlending = 0x0010, ProgramFlag::ePicking = 0x0020, ProgramFlag::eLighting = 0x0040, ProgramFlag::eSpherical = 0x0080,
ProgramFlag::eFixedSize = 0x0100, ProgramFlag::eShadowMapDirectional = 0x0200, ProgramFlag::eShadowMapSpot = 0x0400, ProgramFlag::eShadowMapPoint = 0x0800
}
Flags to use when looking for an automatically generated program.
enum VariableType : uint8_t {
VariableType::eOne, VariableType::eVec1, VariableType::eVec2, VariableType::eVec3,
VariableType::eVec4, VariableType::eMat1, VariableType::eMat2x2, VariableType::eMat2x3,
VariableType::eMat2x4, VariableType::eMat3x2, VariableType::eMat3x3, VariableType::eMat3x4,
VariableType::eMat4x2, VariableType::eMat4x3, VariableType::eMat4x4
}
Supported variables dimensions enumeration.
enum UniformType : uint8_t {
UniformType::eBool, UniformType::eInt, UniformType::eUInt, UniformType::eFloat,
UniformType::eDouble, UniformType::eSampler, UniformType::eVec2b, UniformType::eVec3b,
UniformType::eVec4b, UniformType::eVec2i, UniformType::eVec3i, UniformType::eVec4i,
UniformType::eVec2ui, UniformType::eVec3ui, UniformType::eVec4ui, UniformType::eVec2f,
UniformType::eVec3f, UniformType::eVec4f, UniformType::eVec2d, UniformType::eVec3d,
UniformType::eVec4d, UniformType::eMat2x2b, UniformType::eMat2x3b, UniformType::eMat2x4b,
UniformType::eMat3x2b, UniformType::eMat3x3b, UniformType::eMat3x4b, UniformType::eMat4x2b,
UniformType::eMat4x3b, UniformType::eMat4x4b, UniformType::eMat2x2i, UniformType::eMat2x3i,
UniformType::eMat2x4i, UniformType::eMat3x2i, UniformType::eMat3x3i, UniformType::eMat3x4i,
UniformType::eMat4x2i, UniformType::eMat4x3i, UniformType::eMat4x4i, UniformType::eMat2x2ui,
UniformType::eMat2x3ui, UniformType::eMat2x4ui, UniformType::eMat3x2ui, UniformType::eMat3x3ui,
UniformType::eMat3x4ui, UniformType::eMat4x2ui, UniformType::eMat4x3ui, UniformType::eMat4x4ui,
UniformType::eMat2x2f, UniformType::eMat2x3f, UniformType::eMat2x4f, UniformType::eMat3x2f,
UniformType::eMat3x3f, UniformType::eMat3x4f, UniformType::eMat4x2f, UniformType::eMat4x3f,
UniformType::eMat4x4f, UniformType::eMat2x2d, UniformType::eMat2x3d, UniformType::eMat2x4d,
UniformType::eMat3x2d, UniformType::eMat3x3d, UniformType::eMat3x4d, UniformType::eMat4x2d,
UniformType::eMat4x3d, UniformType::eMat4x4d, UniformType::eReal = eFloat, UniformType::eVec2r = eVec2f,
UniformType::eVec3r = eVec3f, UniformType::eVec4r = eVec4f, UniformType::eMat2x2r = eMat2x2f, UniformType::eMat2x3r = eMat2x3f,
UniformType::eMat2x4r = eMat2x4f, UniformType::eMat3x2r = eMat3x2f, UniformType::eMat3x3r = eMat3x3f, UniformType::eMat3x4r = eMat3x4f,
UniformType::eMat4x2r = eMat4x2f, UniformType::eMat4x3r = eMat4x3f, UniformType::eMat4x4r = eMat4x4f
}
Supported variables full type enumeration.
using Uniform1b = TUniform< UniformType::eBool >
using Uniform1i = TUniform< UniformType::eInt >
using Uniform1s = TUniform< UniformType::eSampler >
using Uniform1ui = TUniform< UniformType::eUInt >
using Uniform1f = TUniform< UniformType::eFloat >
using Uniform1d = TUniform< UniformType::eDouble >
using Uniform1r = TUniform< UniformType::eReal >
using Uniform2b = TUniform< UniformType::eVec2b >
using Uniform3b = TUniform< UniformType::eVec3b >
using Uniform4b = TUniform< UniformType::eVec4b >
using Uniform2i = TUniform< UniformType::eVec2i >
using Uniform3i = TUniform< UniformType::eVec3i >
using Uniform4i = TUniform< UniformType::eVec4i >
using Uniform2ui = TUniform< UniformType::eVec2ui >
using Uniform3ui = TUniform< UniformType::eVec3ui >
using Uniform4ui = TUniform< UniformType::eVec4ui >
using Uniform2f = TUniform< UniformType::eVec2f >
using Uniform3f = TUniform< UniformType::eVec3f >
using Uniform4f = TUniform< UniformType::eVec4f >
using Uniform2d = TUniform< UniformType::eVec2d >
using Uniform3d = TUniform< UniformType::eVec3d >
using Uniform4d = TUniform< UniformType::eVec4d >
using Uniform2r = TUniform< UniformType::eVec2r >
using Uniform3r = TUniform< UniformType::eVec3r >
using Uniform4r = TUniform< UniformType::eVec4r >
using Uniform2x2b = TUniform< UniformType::eMat2x2b >
using Uniform2x3b = TUniform< UniformType::eMat2x3b >
using Uniform2x4b = TUniform< UniformType::eMat2x4b >
using Uniform3x2b = TUniform< UniformType::eMat3x2b >
using Uniform3x3b = TUniform< UniformType::eMat3x3b >
using Uniform3x4b = TUniform< UniformType::eMat3x4b >
using Uniform4x2b = TUniform< UniformType::eMat4x2b >
using Uniform4x3b = TUniform< UniformType::eMat4x3b >
using Uniform4x4b = TUniform< UniformType::eMat4x4b >
using Uniform2x2i = TUniform< UniformType::eMat2x2i >
using Uniform2x3i = TUniform< UniformType::eMat2x3i >
using Uniform2x4i = TUniform< UniformType::eMat2x4i >
using Uniform3x2i = TUniform< UniformType::eMat3x2i >
using Uniform3x3i = TUniform< UniformType::eMat3x3i >
using Uniform3x4i = TUniform< UniformType::eMat3x4i >
using Uniform4x2i = TUniform< UniformType::eMat4x2i >
using Uniform4x3i = TUniform< UniformType::eMat4x3i >
using Uniform4x4i = TUniform< UniformType::eMat4x4i >
using Uniform2x2ui = TUniform< UniformType::eMat2x2ui >
using Uniform2x3ui = TUniform< UniformType::eMat2x3ui >
using Uniform2x4ui = TUniform< UniformType::eMat2x4ui >
using Uniform3x2ui = TUniform< UniformType::eMat3x2ui >
using Uniform3x3ui = TUniform< UniformType::eMat3x3ui >
using Uniform3x4ui = TUniform< UniformType::eMat3x4ui >
using Uniform4x2ui = TUniform< UniformType::eMat4x2ui >
using Uniform4x3ui = TUniform< UniformType::eMat4x3ui >
using Uniform4x4ui = TUniform< UniformType::eMat4x4ui >
using Uniform2x2f = TUniform< UniformType::eMat2x2f >
using Uniform2x3f = TUniform< UniformType::eMat2x3f >
using Uniform2x4f = TUniform< UniformType::eMat2x4f >
using Uniform3x2f = TUniform< UniformType::eMat3x2f >
using Uniform3x3f = TUniform< UniformType::eMat3x3f >
using Uniform3x4f = TUniform< UniformType::eMat3x4f >
using Uniform4x2f = TUniform< UniformType::eMat4x2f >
using Uniform4x3f = TUniform< UniformType::eMat4x3f >
using Uniform4x4f = TUniform< UniformType::eMat4x4f >
using Uniform2x2d = TUniform< UniformType::eMat2x2d >
using Uniform2x3d = TUniform< UniformType::eMat2x3d >
using Uniform2x4d = TUniform< UniformType::eMat2x4d >
using Uniform3x2d = TUniform< UniformType::eMat3x2d >
using Uniform3x3d = TUniform< UniformType::eMat3x3d >
using Uniform3x4d = TUniform< UniformType::eMat3x4d >
using Uniform4x2d = TUniform< UniformType::eMat4x2d >
using Uniform4x3d = TUniform< UniformType::eMat4x3d >
using Uniform4x4d = TUniform< UniformType::eMat4x4d >
using Uniform2x2r = TUniform< UniformType::eMat2x2r >
using Uniform2x3r = TUniform< UniformType::eMat2x3r >
using Uniform2x4r = TUniform< UniformType::eMat2x4r >
using Uniform3x2r = TUniform< UniformType::eMat3x2r >
using Uniform3x3r = TUniform< UniformType::eMat3x3r >
using Uniform3x4r = TUniform< UniformType::eMat3x4r >
using Uniform4x2r = TUniform< UniformType::eMat4x2r >
using Uniform4x3r = TUniform< UniformType::eMat4x3r >
using Uniform4x4r = TUniform< UniformType::eMat4x4r >
using PushUniform1b = TPushUniform< UniformType::eBool >
using PushUniform1i = TPushUniform< UniformType::eInt >
using PushUniform1s = TPushUniform< UniformType::eSampler >
using PushUniform1ui = TPushUniform< UniformType::eUInt >
using PushUniform1f = TPushUniform< UniformType::eFloat >
using PushUniform1d = TPushUniform< UniformType::eDouble >
using PushUniform1r = TPushUniform< UniformType::eReal >
using PushUniform2b = TPushUniform< UniformType::eVec2b >
using PushUniform3b = TPushUniform< UniformType::eVec3b >
using PushUniform4b = TPushUniform< UniformType::eVec4b >
using PushUniform2i = TPushUniform< UniformType::eVec2i >
using PushUniform3i = TPushUniform< UniformType::eVec3i >
using PushUniform4i = TPushUniform< UniformType::eVec4i >
using PushUniform2ui = TPushUniform< UniformType::eVec2ui >
using PushUniform3ui = TPushUniform< UniformType::eVec3ui >
using PushUniform4ui = TPushUniform< UniformType::eVec4ui >
using PushUniform2f = TPushUniform< UniformType::eVec2f >
using PushUniform3f = TPushUniform< UniformType::eVec3f >
using PushUniform4f = TPushUniform< UniformType::eVec4f >
using PushUniform2d = TPushUniform< UniformType::eVec2d >
using PushUniform3d = TPushUniform< UniformType::eVec3d >
using PushUniform4d = TPushUniform< UniformType::eVec4d >
using PushUniform2r = TPushUniform< UniformType::eVec2r >
using PushUniform3r = TPushUniform< UniformType::eVec3r >
using PushUniform4r = TPushUniform< UniformType::eVec4r >
using PushUniform2x2b = TPushUniform< UniformType::eMat2x2b >
using PushUniform2x3b = TPushUniform< UniformType::eMat2x3b >
using PushUniform2x4b = TPushUniform< UniformType::eMat2x4b >
using PushUniform3x2b = TPushUniform< UniformType::eMat3x2b >
using PushUniform3x3b = TPushUniform< UniformType::eMat3x3b >
using PushUniform3x4b = TPushUniform< UniformType::eMat3x4b >
using PushUniform4x2b = TPushUniform< UniformType::eMat4x2b >
using PushUniform4x3b = TPushUniform< UniformType::eMat4x3b >
using PushUniform4x4b = TPushUniform< UniformType::eMat4x4b >
using PushUniform2x2i = TPushUniform< UniformType::eMat2x2i >
using PushUniform2x3i = TPushUniform< UniformType::eMat2x3i >
using PushUniform2x4i = TPushUniform< UniformType::eMat2x4i >
using PushUniform3x2i = TPushUniform< UniformType::eMat3x2i >
using PushUniform3x3i = TPushUniform< UniformType::eMat3x3i >
using PushUniform3x4i = TPushUniform< UniformType::eMat3x4i >
using PushUniform4x2i = TPushUniform< UniformType::eMat4x2i >
using PushUniform4x3i = TPushUniform< UniformType::eMat4x3i >
using PushUniform4x4i = TPushUniform< UniformType::eMat4x4i >
using PushUniform2x2ui = TPushUniform< UniformType::eMat2x2ui >
using PushUniform2x3ui = TPushUniform< UniformType::eMat2x3ui >
using PushUniform2x4ui = TPushUniform< UniformType::eMat2x4ui >
using PushUniform3x2ui = TPushUniform< UniformType::eMat3x2ui >
using PushUniform3x3ui = TPushUniform< UniformType::eMat3x3ui >
using PushUniform3x4ui = TPushUniform< UniformType::eMat3x4ui >
using PushUniform4x2ui = TPushUniform< UniformType::eMat4x2ui >
using PushUniform4x3ui = TPushUniform< UniformType::eMat4x3ui >
using PushUniform4x4ui = TPushUniform< UniformType::eMat4x4ui >
using PushUniform2x2f = TPushUniform< UniformType::eMat2x2f >
using PushUniform2x3f = TPushUniform< UniformType::eMat2x3f >
using PushUniform2x4f = TPushUniform< UniformType::eMat2x4f >
using PushUniform3x2f = TPushUniform< UniformType::eMat3x2f >
using PushUniform3x3f = TPushUniform< UniformType::eMat3x3f >
using PushUniform3x4f = TPushUniform< UniformType::eMat3x4f >
using PushUniform4x2f = TPushUniform< UniformType::eMat4x2f >
using PushUniform4x3f = TPushUniform< UniformType::eMat4x3f >
using PushUniform4x4f = TPushUniform< UniformType::eMat4x4f >
using PushUniform2x2d = TPushUniform< UniformType::eMat2x2d >
using PushUniform2x3d = TPushUniform< UniformType::eMat2x3d >
using PushUniform2x4d = TPushUniform< UniformType::eMat2x4d >
using PushUniform3x2d = TPushUniform< UniformType::eMat3x2d >
using PushUniform3x3d = TPushUniform< UniformType::eMat3x3d >
using PushUniform3x4d = TPushUniform< UniformType::eMat3x4d >
using PushUniform4x2d = TPushUniform< UniformType::eMat4x2d >
using PushUniform4x3d = TPushUniform< UniformType::eMat4x3d >
using PushUniform4x4d = TPushUniform< UniformType::eMat4x4d >
using PushUniform2x2r = TPushUniform< UniformType::eMat2x2r >
using PushUniform2x3r = TPushUniform< UniformType::eMat2x3r >
using PushUniform2x4r = TPushUniform< UniformType::eMat2x4r >
using PushUniform3x2r = TPushUniform< UniformType::eMat3x2r >
using PushUniform3x3r = TPushUniform< UniformType::eMat3x3r >
using PushUniform3x4r = TPushUniform< UniformType::eMat3x4r >
using PushUniform4x2r = TPushUniform< UniformType::eMat4x2r >
using PushUniform4x3r = TPushUniform< UniformType::eMat4x3r >
using PushUniform4x4r = TPushUniform< UniformType::eMat4x4r >
bool IsShadowMapProgram (ProgramFlags const &p_flags)
Tells if the given flags contain a shadow map flag.
DECLARE_SMART_PTR (Uniform1b)
DECLARE_SMART_PTR (PushUniform1b)
DECLARE_SMART_PTR (UniformBuffer)
DECLARE_SMART_PTR (UniformBufferBinding)
DECLARE_SMART_PTR (Uniform)
DECLARE_SMART_PTR (PushUniform)
DECLARE_SMART_PTR (ShaderObject)
DECLARE_SMART_PTR (ShaderProgram)
DECLARE_SMART_PTR (ShaderStorageBuffer)
DECLARE_SMART_PTR (AtomicCounterBuffer)
DECLARE_VECTOR (ShaderProgramSPtr, ShaderProgramPtr)
DECLARE_VECTOR (ShaderObjectSPtr, ShaderObjectPtr)
DECLARE_LIST (PushUniformSPtr, PushUniform)
DECLARE_LIST (UniformSPtr, Uniform)
DECLARE_LIST (UniformBufferSPtr, UniformBufferPtr)
DECLARE_LIST (ShaderStorageBufferSPtr, ShaderStorageBufferPtr)
DECLARE_LIST (AtomicCounterBufferSPtr, AtomicCounterBufferPtr)
DECLARE_MAP (Castor::String, PushUniformWPtr, PushUniform)
DECLARE_MAP (Castor::String, UniformWPtr, Uniform)
DECLARE_MAP (ShaderProgramRPtr, UniformBufferBindingUPtr, UniformBufferBinding)
DECLARE_MAP (Castor::String, UniformBufferWPtr, UniformBufferPtrStr)
DECLARE_MAP (Castor::String, ShaderStorageBufferWPtr, ShaderStorageBufferPtrStr)
DECLARE_MAP (Castor::String, AtomicCounterBufferWPtr, AtomicCounterBufferPtrStr)
DECLARE_MAP (ShaderType, UniformBufferWPtr, UniformBufferPtrShader)
DECLARE_MAP (ShaderType, ShaderStorageBufferWPtr, ShaderStorageBufferPtrShader)
DECLARE_MAP (ShaderType, AtomicCounterBufferWPtr, AtomicCounterBufferPtrShader)
Typedef Documentation
AnimatedObjectGroupCache
using Castor3D::AnimatedObjectGroupCache = typedef Cache< AnimatedObjectGroup, Castor::String >
BillboardListCache
using Castor3D::BillboardListCache = typedef ObjectCache< BillboardList, Castor::String >
BillboardListRenderNode
using Castor3D::BillboardListRenderNode = typedef ObjectRenderNode< BillboardBase, BillboardBase >
CameraCache
using Castor3D::CameraCache = typedef ObjectCache< Camera, Castor::String >
ElementAttacher
template<typename ElementType > using Castor3D::ElementAttacher = typedef std::function< void(std::shared_ptr< ElementType >, SceneNodeSPtr, SceneNodeSPtr, SceneNodeSPtr, SceneNodeSPtr) >
ElementCleaner
template<typename ElementType > using Castor3D::ElementCleaner = typedef std::function< void(std::shared_ptr< ElementType >) >
ElementDetacher
template<typename ElementType > using Castor3D::ElementDetacher = typedef std::function< void(std::shared_ptr< ElementType >) >
ElementInitialiser
template<typename ElementType > using Castor3D::ElementInitialiser = typedef std::function< void(std::shared_ptr< ElementType >) >
ElementMerger
template<typename ElementType , typename KeyType > using Castor3D::ElementMerger = typedef std::function< void(CacheBase< ElementType, KeyType > const &, Castor::Collection< ElementType, KeyType > &, std::shared_ptr< ElementType >) >
GeometryCache
using Castor3D::GeometryCache = typedef ObjectCache< Geometry, Castor::String >
GroupAnimationMap
using Castor3D::GroupAnimationMap = typedef std::map< Castor::String, GroupAnimation >
InterleavedVertex
using Castor3D::InterleavedVertex = typedef InterleavedVertexT< real >
InterleavedVertexArray
using Castor3D::InterleavedVertexArray = typedef std::vector< InterleavedVertex >
KeyFrameArray
using Castor3D::KeyFrameArray = typedef std::vector< KeyFrame >
KeyFrameRealMap
using Castor3D::KeyFrameRealMap = typedef std::map< real, KeyFrame >
LightCache
using Castor3D::LightCache = typedef ObjectCache< Light, Castor::String >
LightsArray
using Castor3D::LightsArray = typedef std::vector< LightSPtr >
LightsMap
using Castor3D::LightsMap = typedef std::array< LightsArray, size_t(LightType::eCount) >
ListenerCache
using Castor3D::ListenerCache = typedef Cache< FrameListener, Castor::String >
MaterialCache
using Castor3D::MaterialCache = typedef Cache< Material, Castor::String >
MeshCache
using Castor3D::MeshCache = typedef Cache< Mesh, Castor::String >
OverlayCache
using Castor3D::OverlayCache = typedef Cache< Overlay, Castor::String >
OverlayCategorySet
using Castor3D::OverlayCategorySet = typedef std::set< OverlayCategorySPtr, OverlayCategorySort >
ParticleArray
using Castor3D::ParticleArray = typedef std::vector< Particle >
ParticleFactory
using Castor3D::ParticleFactory = typedef Castor::Factory< CpuParticleSystem, Castor::String, CpuParticleSystemUPtr, std::function< CpuParticleSystemUPtr(ParticleSystem &) > >
PluginCache
using Castor3D::PluginCache = typedef Cache< Plugin, Castor::String >
Point3rInterpolator
using Castor3D::Point3rInterpolator = typedef Interpolator< Castor::Point3r >
Point3rPattern
typedef Pattern< Castor::Point3r > Castor3D::Point3rPattern
Point3rPtrPattern
typedef Pattern< Castor::Point3rSPtr > Castor3D::Point3rPtrPattern
PostEffectFactory
using Castor3D::PostEffectFactory = typedef Castor::Factory< PostEffect, Castor::String, std::shared_ptr< PostEffect >, std::function< PostEffectSPtr(RenderTarget &, RenderSystem &, Parameters const &) > >
Post effect factory.
Author
Sylvain DOREMUS
Version
0.9.0
Date
03/07/2016
PushUniform1b
using Castor3D::PushUniform1b = typedef TPushUniform< UniformType::eBool >
PushUniform1d
using Castor3D::PushUniform1d = typedef TPushUniform< UniformType::eDouble >
PushUniform1f
using Castor3D::PushUniform1f = typedef TPushUniform< UniformType::eFloat >
PushUniform1i
using Castor3D::PushUniform1i = typedef TPushUniform< UniformType::eInt >
PushUniform1r
using Castor3D::PushUniform1r = typedef TPushUniform< UniformType::eReal >
PushUniform1s
using Castor3D::PushUniform1s = typedef TPushUniform< UniformType::eSampler >
PushUniform1ui
using Castor3D::PushUniform1ui = typedef TPushUniform< UniformType::eUInt >
PushUniform2b
using Castor3D::PushUniform2b = typedef TPushUniform< UniformType::eVec2b >
PushUniform2d
using Castor3D::PushUniform2d = typedef TPushUniform< UniformType::eVec2d >
PushUniform2f
using Castor3D::PushUniform2f = typedef TPushUniform< UniformType::eVec2f >
PushUniform2i
using Castor3D::PushUniform2i = typedef TPushUniform< UniformType::eVec2i >
PushUniform2r
using Castor3D::PushUniform2r = typedef TPushUniform< UniformType::eVec2r >
PushUniform2ui
using Castor3D::PushUniform2ui = typedef TPushUniform< UniformType::eVec2ui >
PushUniform2x2b
using Castor3D::PushUniform2x2b = typedef TPushUniform< UniformType::eMat2x2b >
PushUniform2x2d
using Castor3D::PushUniform2x2d = typedef TPushUniform< UniformType::eMat2x2d >
PushUniform2x2f
using Castor3D::PushUniform2x2f = typedef TPushUniform< UniformType::eMat2x2f >
PushUniform2x2i
using Castor3D::PushUniform2x2i = typedef TPushUniform< UniformType::eMat2x2i >
PushUniform2x2r
using Castor3D::PushUniform2x2r = typedef TPushUniform< UniformType::eMat2x2r >
PushUniform2x2ui
using Castor3D::PushUniform2x2ui = typedef TPushUniform< UniformType::eMat2x2ui >
PushUniform2x3b
using Castor3D::PushUniform2x3b = typedef TPushUniform< UniformType::eMat2x3b >
PushUniform2x3d
using Castor3D::PushUniform2x3d = typedef TPushUniform< UniformType::eMat2x3d >
PushUniform2x3f
using Castor3D::PushUniform2x3f = typedef TPushUniform< UniformType::eMat2x3f >
PushUniform2x3i
using Castor3D::PushUniform2x3i = typedef TPushUniform< UniformType::eMat2x3i >
PushUniform2x3r
using Castor3D::PushUniform2x3r = typedef TPushUniform< UniformType::eMat2x3r >
PushUniform2x3ui
using Castor3D::PushUniform2x3ui = typedef TPushUniform< UniformType::eMat2x3ui >
PushUniform2x4b
using Castor3D::PushUniform2x4b = typedef TPushUniform< UniformType::eMat2x4b >
PushUniform2x4d
using Castor3D::PushUniform2x4d = typedef TPushUniform< UniformType::eMat2x4d >
PushUniform2x4f
using Castor3D::PushUniform2x4f = typedef TPushUniform< UniformType::eMat2x4f >
PushUniform2x4i
using Castor3D::PushUniform2x4i = typedef TPushUniform< UniformType::eMat2x4i >
PushUniform2x4r
using Castor3D::PushUniform2x4r = typedef TPushUniform< UniformType::eMat2x4r >
PushUniform2x4ui
using Castor3D::PushUniform2x4ui = typedef TPushUniform< UniformType::eMat2x4ui >
PushUniform3b
using Castor3D::PushUniform3b = typedef TPushUniform< UniformType::eVec3b >
PushUniform3d
using Castor3D::PushUniform3d = typedef TPushUniform< UniformType::eVec3d >
PushUniform3f
using Castor3D::PushUniform3f = typedef TPushUniform< UniformType::eVec3f >
PushUniform3i
using Castor3D::PushUniform3i = typedef TPushUniform< UniformType::eVec3i >
PushUniform3r
using Castor3D::PushUniform3r = typedef TPushUniform< UniformType::eVec3r >
PushUniform3ui
using Castor3D::PushUniform3ui = typedef TPushUniform< UniformType::eVec3ui >
PushUniform3x2b
using Castor3D::PushUniform3x2b = typedef TPushUniform< UniformType::eMat3x2b >
PushUniform3x2d
using Castor3D::PushUniform3x2d = typedef TPushUniform< UniformType::eMat3x2d >
PushUniform3x2f
using Castor3D::PushUniform3x2f = typedef TPushUniform< UniformType::eMat3x2f >
PushUniform3x2i
using Castor3D::PushUniform3x2i = typedef TPushUniform< UniformType::eMat3x2i >
PushUniform3x2r
using Castor3D::PushUniform3x2r = typedef TPushUniform< UniformType::eMat3x2r >
PushUniform3x2ui
using Castor3D::PushUniform3x2ui = typedef TPushUniform< UniformType::eMat3x2ui >
PushUniform3x3b
using Castor3D::PushUniform3x3b = typedef TPushUniform< UniformType::eMat3x3b >
PushUniform3x3d
using Castor3D::PushUniform3x3d = typedef TPushUniform< UniformType::eMat3x3d >
PushUniform3x3f
using Castor3D::PushUniform3x3f = typedef TPushUniform< UniformType::eMat3x3f >
PushUniform3x3i
using Castor3D::PushUniform3x3i = typedef TPushUniform< UniformType::eMat3x3i >
PushUniform3x3r
using Castor3D::PushUniform3x3r = typedef TPushUniform< UniformType::eMat3x3r >
PushUniform3x3ui
using Castor3D::PushUniform3x3ui = typedef TPushUniform< UniformType::eMat3x3ui >
PushUniform3x4b
using Castor3D::PushUniform3x4b = typedef TPushUniform< UniformType::eMat3x4b >
PushUniform3x4d
using Castor3D::PushUniform3x4d = typedef TPushUniform< UniformType::eMat3x4d >
PushUniform3x4f
using Castor3D::PushUniform3x4f = typedef TPushUniform< UniformType::eMat3x4f >
PushUniform3x4i
using Castor3D::PushUniform3x4i = typedef TPushUniform< UniformType::eMat3x4i >
PushUniform3x4r
using Castor3D::PushUniform3x4r = typedef TPushUniform< UniformType::eMat3x4r >
PushUniform3x4ui
using Castor3D::PushUniform3x4ui = typedef TPushUniform< UniformType::eMat3x4ui >
PushUniform4b
using Castor3D::PushUniform4b = typedef TPushUniform< UniformType::eVec4b >
PushUniform4d
using Castor3D::PushUniform4d = typedef TPushUniform< UniformType::eVec4d >
PushUniform4f
using Castor3D::PushUniform4f = typedef TPushUniform< UniformType::eVec4f >
PushUniform4i
using Castor3D::PushUniform4i = typedef TPushUniform< UniformType::eVec4i >
PushUniform4r
using Castor3D::PushUniform4r = typedef TPushUniform< UniformType::eVec4r >
PushUniform4ui
using Castor3D::PushUniform4ui = typedef TPushUniform< UniformType::eVec4ui >
PushUniform4x2b
using Castor3D::PushUniform4x2b = typedef TPushUniform< UniformType::eMat4x2b >
PushUniform4x2d
using Castor3D::PushUniform4x2d = typedef TPushUniform< UniformType::eMat4x2d >
PushUniform4x2f
using Castor3D::PushUniform4x2f = typedef TPushUniform< UniformType::eMat4x2f >
PushUniform4x2i
using Castor3D::PushUniform4x2i = typedef TPushUniform< UniformType::eMat4x2i >
PushUniform4x2r
using Castor3D::PushUniform4x2r = typedef TPushUniform< UniformType::eMat4x2r >
PushUniform4x2ui
using Castor3D::PushUniform4x2ui = typedef TPushUniform< UniformType::eMat4x2ui >
PushUniform4x3b
using Castor3D::PushUniform4x3b = typedef TPushUniform< UniformType::eMat4x3b >
PushUniform4x3d
using Castor3D::PushUniform4x3d = typedef TPushUniform< UniformType::eMat4x3d >
PushUniform4x3f
using Castor3D::PushUniform4x3f = typedef TPushUniform< UniformType::eMat4x3f >
PushUniform4x3i
using Castor3D::PushUniform4x3i = typedef TPushUniform< UniformType::eMat4x3i >
PushUniform4x3r
using Castor3D::PushUniform4x3r = typedef TPushUniform< UniformType::eMat4x3r >
PushUniform4x3ui
using Castor3D::PushUniform4x3ui = typedef TPushUniform< UniformType::eMat4x3ui >
PushUniform4x4b
using Castor3D::PushUniform4x4b = typedef TPushUniform< UniformType::eMat4x4b >
PushUniform4x4d
using Castor3D::PushUniform4x4d = typedef TPushUniform< UniformType::eMat4x4d >
PushUniform4x4f
using Castor3D::PushUniform4x4f = typedef TPushUniform< UniformType::eMat4x4f >
PushUniform4x4i
using Castor3D::PushUniform4x4i = typedef TPushUniform< UniformType::eMat4x4i >
PushUniform4x4r
using Castor3D::PushUniform4x4r = typedef TPushUniform< UniformType::eMat4x4r >
PushUniform4x4ui
using Castor3D::PushUniform4x4ui = typedef TPushUniform< UniformType::eMat4x4ui >
QuaternionInterpolator
using Castor3D::QuaternionInterpolator = typedef Interpolator< Castor::Quaternion >
RenderQueueArray
using Castor3D::RenderQueueArray = typedef std::vector< std::reference_wrapper< RenderQueue > >
RenderSystemFactory
using Castor3D::RenderSystemFactory = typedef Castor::Factory< RenderSystem, Castor::String, RenderSystemUPtr, std::function< RenderSystemUPtr(Engine &) > >
Render technique factory.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
24/11/2014
RenderTechniqueCache
using Castor3D::RenderTechniqueCache = typedef Cache< RenderTechnique, Castor::String >
RenderWindowCache
using Castor3D::RenderWindowCache = typedef Cache< RenderWindow, Castor::String >
SamplerCache
using Castor3D::SamplerCache = typedef Cache< Sampler, Castor::String >
SceneCache
using Castor3D::SceneCache = typedef Cache< Scene, Castor::String >
SceneNodeCache
using Castor3D::SceneNodeCache = typedef ObjectCache< SceneNode, Castor::String >
SubdividerFactory
using Castor3D::SubdividerFactory = typedef Castor::Factory< Subdivider, Castor::String, SubdividerUPtr >
The subdivider factory.
Author
Sylvain DOREMUS
Version
0.9.0
Date
22/07/2016
SubmeshAnimationBuffer
using Castor3D::SubmeshAnimationBuffer = typedef SubmeshAnimationBufferT< float >
SubmeshAnimationBufferArray
using Castor3D::SubmeshAnimationBufferArray = typedef std::vector< SubmeshAnimationBuffer >
SubmeshRenderNode
using Castor3D::SubmeshRenderNode = typedef ObjectRenderNode< Submesh, Geometry >
SubmeshStaticRenderNodesByPassMap
using Castor3D::SubmeshStaticRenderNodesByPassMap = typedef TypeRenderNodesByPassMap< SubmeshStaticRenderNodesMap >
TechniqueFactory
using Castor3D::TechniqueFactory = typedef Castor::Factory< RenderTechnique, Castor::String, RenderTechniqueSPtr, std::function< RenderTechniqueSPtr(RenderTarget &, RenderSystem &, Parameters const &) > >
Render technique factory.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
24/11/2014
ToneMappingFactory
using Castor3D::ToneMappingFactory = typedef Castor::Factory< ToneMapping, Castor::String, ToneMappingSPtr, std::function< ToneMappingSPtr(Engine &, Parameters const &) > >
Tone mapping factory.
Author
Sylvain DOREMUS
Version
0.8.0
Date
11/03/2016
Uniform1b
using Castor3D::Uniform1b = typedef TUniform< UniformType::eBool >
Uniform1d
using Castor3D::Uniform1d = typedef TUniform< UniformType::eDouble >
Uniform1f
using Castor3D::Uniform1f = typedef TUniform< UniformType::eFloat >
Uniform1i
using Castor3D::Uniform1i = typedef TUniform< UniformType::eInt >
Uniform1r
using Castor3D::Uniform1r = typedef TUniform< UniformType::eReal >
Uniform1s
using Castor3D::Uniform1s = typedef TUniform< UniformType::eSampler >
Uniform1ui
using Castor3D::Uniform1ui = typedef TUniform< UniformType::eUInt >
Uniform2b
using Castor3D::Uniform2b = typedef TUniform< UniformType::eVec2b >
Uniform2d
using Castor3D::Uniform2d = typedef TUniform< UniformType::eVec2d >
Uniform2f
using Castor3D::Uniform2f = typedef TUniform< UniformType::eVec2f >
Uniform2i
using Castor3D::Uniform2i = typedef TUniform< UniformType::eVec2i >
Uniform2r
using Castor3D::Uniform2r = typedef TUniform< UniformType::eVec2r >
Uniform2ui
using Castor3D::Uniform2ui = typedef TUniform< UniformType::eVec2ui >
Uniform2x2b
using Castor3D::Uniform2x2b = typedef TUniform< UniformType::eMat2x2b >
Uniform2x2d
using Castor3D::Uniform2x2d = typedef TUniform< UniformType::eMat2x2d >
Uniform2x2f
using Castor3D::Uniform2x2f = typedef TUniform< UniformType::eMat2x2f >
Uniform2x2i
using Castor3D::Uniform2x2i = typedef TUniform< UniformType::eMat2x2i >
Uniform2x2r
using Castor3D::Uniform2x2r = typedef TUniform< UniformType::eMat2x2r >
Uniform2x2ui
using Castor3D::Uniform2x2ui = typedef TUniform< UniformType::eMat2x2ui >
Uniform2x3b
using Castor3D::Uniform2x3b = typedef TUniform< UniformType::eMat2x3b >
Uniform2x3d
using Castor3D::Uniform2x3d = typedef TUniform< UniformType::eMat2x3d >
Uniform2x3f
using Castor3D::Uniform2x3f = typedef TUniform< UniformType::eMat2x3f >
Uniform2x3i
using Castor3D::Uniform2x3i = typedef TUniform< UniformType::eMat2x3i >
Uniform2x3r
using Castor3D::Uniform2x3r = typedef TUniform< UniformType::eMat2x3r >
Uniform2x3ui
using Castor3D::Uniform2x3ui = typedef TUniform< UniformType::eMat2x3ui >
Uniform2x4b
using Castor3D::Uniform2x4b = typedef TUniform< UniformType::eMat2x4b >
Uniform2x4d
using Castor3D::Uniform2x4d = typedef TUniform< UniformType::eMat2x4d >
Uniform2x4f
using Castor3D::Uniform2x4f = typedef TUniform< UniformType::eMat2x4f >
Uniform2x4i
using Castor3D::Uniform2x4i = typedef TUniform< UniformType::eMat2x4i >
Uniform2x4r
using Castor3D::Uniform2x4r = typedef TUniform< UniformType::eMat2x4r >
Uniform2x4ui
using Castor3D::Uniform2x4ui = typedef TUniform< UniformType::eMat2x4ui >
Uniform3b
using Castor3D::Uniform3b = typedef TUniform< UniformType::eVec3b >
Uniform3d
using Castor3D::Uniform3d = typedef TUniform< UniformType::eVec3d >
Uniform3f
using Castor3D::Uniform3f = typedef TUniform< UniformType::eVec3f >
Uniform3i
using Castor3D::Uniform3i = typedef TUniform< UniformType::eVec3i >
Uniform3r
using Castor3D::Uniform3r = typedef TUniform< UniformType::eVec3r >
Uniform3ui
using Castor3D::Uniform3ui = typedef TUniform< UniformType::eVec3ui >
Uniform3x2b
using Castor3D::Uniform3x2b = typedef TUniform< UniformType::eMat3x2b >
Uniform3x2d
using Castor3D::Uniform3x2d = typedef TUniform< UniformType::eMat3x2d >
Uniform3x2f
using Castor3D::Uniform3x2f = typedef TUniform< UniformType::eMat3x2f >
Uniform3x2i
using Castor3D::Uniform3x2i = typedef TUniform< UniformType::eMat3x2i >
Uniform3x2r
using Castor3D::Uniform3x2r = typedef TUniform< UniformType::eMat3x2r >
Uniform3x2ui
using Castor3D::Uniform3x2ui = typedef TUniform< UniformType::eMat3x2ui >
Uniform3x3b
using Castor3D::Uniform3x3b = typedef TUniform< UniformType::eMat3x3b >
Uniform3x3d
using Castor3D::Uniform3x3d = typedef TUniform< UniformType::eMat3x3d >
Uniform3x3f
using Castor3D::Uniform3x3f = typedef TUniform< UniformType::eMat3x3f >
Uniform3x3i
using Castor3D::Uniform3x3i = typedef TUniform< UniformType::eMat3x3i >
Uniform3x3r
using Castor3D::Uniform3x3r = typedef TUniform< UniformType::eMat3x3r >
Uniform3x3ui
using Castor3D::Uniform3x3ui = typedef TUniform< UniformType::eMat3x3ui >
Uniform3x4b
using Castor3D::Uniform3x4b = typedef TUniform< UniformType::eMat3x4b >
Uniform3x4d
using Castor3D::Uniform3x4d = typedef TUniform< UniformType::eMat3x4d >
Uniform3x4f
using Castor3D::Uniform3x4f = typedef TUniform< UniformType::eMat3x4f >
Uniform3x4i
using Castor3D::Uniform3x4i = typedef TUniform< UniformType::eMat3x4i >
Uniform3x4r
using Castor3D::Uniform3x4r = typedef TUniform< UniformType::eMat3x4r >
Uniform3x4ui
using Castor3D::Uniform3x4ui = typedef TUniform< UniformType::eMat3x4ui >
Uniform4b
using Castor3D::Uniform4b = typedef TUniform< UniformType::eVec4b >
Uniform4d
using Castor3D::Uniform4d = typedef TUniform< UniformType::eVec4d >
Uniform4f
using Castor3D::Uniform4f = typedef TUniform< UniformType::eVec4f >
Uniform4i
using Castor3D::Uniform4i = typedef TUniform< UniformType::eVec4i >
Uniform4r
using Castor3D::Uniform4r = typedef TUniform< UniformType::eVec4r >
Uniform4ui
using Castor3D::Uniform4ui = typedef TUniform< UniformType::eVec4ui >
Uniform4x2b
using Castor3D::Uniform4x2b = typedef TUniform< UniformType::eMat4x2b >
Uniform4x2d
using Castor3D::Uniform4x2d = typedef TUniform< UniformType::eMat4x2d >
Uniform4x2f
using Castor3D::Uniform4x2f = typedef TUniform< UniformType::eMat4x2f >
Uniform4x2i
using Castor3D::Uniform4x2i = typedef TUniform< UniformType::eMat4x2i >
Uniform4x2r
using Castor3D::Uniform4x2r = typedef TUniform< UniformType::eMat4x2r >
Uniform4x2ui
using Castor3D::Uniform4x2ui = typedef TUniform< UniformType::eMat4x2ui >
Uniform4x3b
using Castor3D::Uniform4x3b = typedef TUniform< UniformType::eMat4x3b >
Uniform4x3d
using Castor3D::Uniform4x3d = typedef TUniform< UniformType::eMat4x3d >
Uniform4x3f
using Castor3D::Uniform4x3f = typedef TUniform< UniformType::eMat4x3f >
Uniform4x3i
using Castor3D::Uniform4x3i = typedef TUniform< UniformType::eMat4x3i >
Uniform4x3r
using Castor3D::Uniform4x3r = typedef TUniform< UniformType::eMat4x3r >
Uniform4x3ui
using Castor3D::Uniform4x3ui = typedef TUniform< UniformType::eMat4x3ui >
Uniform4x4b
using Castor3D::Uniform4x4b = typedef TUniform< UniformType::eMat4x4b >
Uniform4x4d
using Castor3D::Uniform4x4d = typedef TUniform< UniformType::eMat4x4d >
Uniform4x4f
using Castor3D::Uniform4x4f = typedef TUniform< UniformType::eMat4x4f >
Uniform4x4i
using Castor3D::Uniform4x4i = typedef TUniform< UniformType::eMat4x4i >
Uniform4x4r
using Castor3D::Uniform4x4r = typedef TUniform< UniformType::eMat4x4r >
Uniform4x4ui
using Castor3D::Uniform4x4ui = typedef TUniform< UniformType::eMat4x4ui >
VertexBufferArray
using Castor3D::VertexBufferArray = typedef std::vector< std::reference_wrapper< VertexBuffer > >
VertexPattern
typedef Pattern< Vertex > Castor3D::VertexPattern
VertexPtrPattern
typedef Pattern< VertexSPtr > Castor3D::VertexPtrPattern
WindowPtrStrMap
typedef std::map< Castor::String, RenderWindowSPtr > Castor3D::WindowPtrStrMap
Enumeration Type Documentation
AccessType
enum Castor3D::AccessType : uint8_t strong
Access types enumeration.
Author
Sylvain DOREMUS
Version
0.8.0
Date
16/10/2015
Enumerator
eNone
No access.
eRead
Read only access type.
eWrite
Write only access type.
AlphaBlendFunc
enum Castor3D::AlphaBlendFunc : uint8_t strong
Alpha blending functions enumeration.
Author
Sylvain DOREMUS
Enumerator
eNoBlend
No blend
eFirstArg
Arg0
eAdd
Arg0 + Arg1
eAddSigned
Arg0 + Arg1 - 0.5
eModulate
Arg0 x Arg1
eInterpolate
Arg0 Arg2 + Arg1 (1 - Arg2)
eSubtract
Arg0 - Arg1
AnimationState
enum Castor3D::AnimationState : uint8_t strong
Animation State Enumerator.
Author
Sylvain DOREMUS
Date
09/02/2010
Enumerator
ePlaying
Playing animation state.
eStopped
Stopped animation state.
ePaused
Paused animation state.
AnimationType
enum Castor3D::AnimationType : uint8_t strong
Animation types enumeration.
Author
Sylvain DOREMUS
Version
0.9.0
Date
31/05/2016
Enumerator
eMovable
Scene node animation.
eSkeleton
Skeleton animation.
eMesh
Submesh animation (morphing).
AttachmentPoint
enum Castor3D::AttachmentPoint : uint8_t strong
Frame buffer attachment points enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
12/11/2012
Enumerator
eNone
eColour
eDepth
eStencil
eDepthStencil
AttachmentType
enum Castor3D::AttachmentType : uint8_t strong
Frame buffer attachment types enumeration.
Author
Sylvain DOREMUS
Version
0.8.0.0
Date
11/10/2015
Enumerator
eTexture
eBuffer
BillboardSize
enum Castor3D::BillboardSize strong
Billboard sizing types enumeration.
Author
Sylvain DOREMUS
Version
0.9.0
Date
16/11/2016
Enumerator
eDynamic
Billboards size changes with camera position.
eFixed
Billboards size doesn't change.
BillboardType
enum Castor3D::BillboardType strong
Billboard rendering types enumeration.
Author
Sylvain DOREMUS
Version
0.9.0
Date
16/11/2016
Enumerator
eSpherical
Billboards always face the camera.
eCylindrical
Billboards rotate only on Y axis.
BlendMode
enum Castor3D::BlendMode : uint8_t strong
Blending modes enumeration.
Author
Sylvain DOREMUS
Enumerator
eNoBlend
Order dependent blending.
eAdditive
Order independent, add the components.
eMultiplicative
Order independent, multiply the components.
eInterpolative
Order dependent, interpolate the components.
eABuffer
Order independent, using A-buffer, not implemented yet.
eDepthPeeling
Order independent, using depth peeling, not implemented yet.
BlendOperand
enum Castor3D::BlendOperand : uint8_t strong
Blend operands enumeration.
Author
Sylvain DOREMUS
Enumerator
eZero
eOne
eSrcColour
eInvSrcColour
eDstColour
eInvDstColour
eSrcAlpha
eInvSrcAlpha
eDstAlpha
eInvDstAlpha
eConstant
eInvConstant
eSrcAlphaSaturate
eSrc1Colour
eInvSrc1Colour
eSrc1Alpha
eInvSrc1Alpha
BlendOperation
enum Castor3D::BlendOperation : uint8_t strong
Blending operations enumeration.
Author
Sylvain DOREMUS
Enumerator
eAdd
Src2 + Src1.
eSubtract
Src2 - Src1.
eRevSubtract
Src1 - Src2.
eMin
min(Src1, Src2).
eMax
max(Src1, Src2).
eCount
BlendSource
enum Castor3D::BlendSource : uint8_t strong
Texture blending sources enumeration.
Author
Sylvain DOREMUS
Enumerator
eTexture
eTexture0
eTexture1
eTexture2
eTexture3
eConstant
eDiffuse
ePrevious
BlendSrcIndex
enum Castor3D::BlendSrcIndex : uint8_t strong
Texture blending source indices enumeration.
Author
Sylvain DOREMUS
Enumerator
eIndex0
eIndex1
eIndex2
BorderPosition
enum Castor3D::BorderPosition strong
Text wrapping modes, handles the way text is cut when it overflows the overlay width.
Author
Sylvain DOREMUS
Date
28/11/2014
Enumerator
eInternal
The border is outside the overlay.
eMiddle
The border is middle outside and middle inside the overlay.
eExternal
The border is outside the overlay.
BufferAccessNature
enum Castor3D::BufferAccessNature : uint32_t strong
Buffer access natures enumeration.
Author
Sylvain DOREMUS
See also
BufferAccessType
Remarks
Made to be combined with BufferAccessType
Enumerator
eDraw
Modified by CPU and used by GPU.
eRead
Modified by GPU and used by CPU.
eCopy
Modified by GPU and used by GPU.
BufferAccessType
enum Castor3D::BufferAccessType : uint32_t strong
Buffer access types enumeration.
Author
Sylvain DOREMUS
See also
BufferAccessNature
Remarks
Made to be combined with BufferAccessNature
Enumerator
eStatic
Modified once and used many times.
eDynamic
Modified many times and used many times.
eStream
Modified oncce and used at most a few times.
BufferComponent
enum Castor3D::BufferComponent : uint8_t strong
Frame buffer components enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
12/11/2012
Enumerator
eNone
eColour
eDepth
eStencil
BufferType
enum Castor3D::BufferType : uint32_t strong
GPU buffers types enumeration.
Author
Sylvain DOREMUS
Version
0.9.0
Date
12/12/2016
Enumerator
eArray
Data array => Vertex buffers.
eElementArray
Element array => Index buffers.
eUniform
Uniform buffer.
eAtomicCounter
Atomic counters buffer.
eShaderStorage
Shader storage buffer.
ChunkType
enum Castor3D::ChunkType : uint64_t strong
Binary data chunk types enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
15/04/2013
Enumerator
eUnknown
eCmshFile
eCmshHeader
eCmshVersion
eName
eMesh
eSkeleton
eSkeletonGlobalInverse
eSkeletonBone
eBoneParentName
eBoneOffsetMatrix
eSubmesh
eSubmeshTopology
eSubmeshVertexCount
eSubmeshVertex
eSubmeshBoneCount
eSubmeshBones
eSubmeshMatrixCount
eSubmeshMatrices
eSubmeshFaceCount
eSubmeshFaces
eAnimable
eAnimation
eAnimLength
eSkeletonAnimation
eMeshAnimation
eAnimInterpolator
eAnimationObject
eSkeletonAnimationNode
eSkeletonAnimationBone
eMovingTransform
eKeyframeCount
eKeyframes
eMeshAnimationSubmeshID
eMeshAnimationSubmesh
eSubmeshAnimationBuffer
eSubmeshAnimationBufferSize
eSubmeshAnimationBuffersCount
eSubmeshAnimationBuffers
ColourBlendFunc
enum Castor3D::ColourBlendFunc : uint8_t strong
RGB blending functions enumeration.
Author
Sylvain DOREMUS
Enumerator
eNoBlend
No blend
eFirstArg
Arg0
eAdd
Arg0 + Arg1
eAddSigned
Arg0 + Arg1 - 0.5
eModulate
Arg0 x Arg1
eInterpolate
Arg0 Arg2 + Arg1 (1 - Arg2)
eSubtract
Arg0 - Arg1
eDot3RGB
4 (((Arg0.r - 0.5) (Arg1.r - 0.5)) + ((Arg0.g - 0.5) (Arg1.g - 0.5)) + ((Arg0.b - 0.5) (Arg1.b - 0.5)))
eDot3RGBA
4 (((Arg0.r - 0.5) (Arg1.r - 0.5)) + ((Arg0.g - 0.5) (Arg1.g - 0.5)) + ((Arg0.b - 0.5) (Arg1.b - 0.5)) + ((Arg0.a - 0.5) (Arg1.a - 0.5)))
ComparisonFunc
enum Castor3D::ComparisonFunc : uint8_t strong
Alpha functions enumeration.
Author
Sylvain DOREMUS
Enumerator
eAlways
Always take texture colour
eLess
Takes texture colour if alpha is less than given value
eLEqual
Takes texture colour if alpha is less than or equal to given value
eEqual
Takes texture colour if alpha is equal to given value
eNEqual
Takes texture colour if alpha is different of given value
eGEqual
Takes texture colour if alpha is grater than or equal to given value
eGreater
Takes texture colour if alpha is greater than given value
eNever
Never take texture colour
ComparisonMode
enum Castor3D::ComparisonMode : uint8_t strong
Texture comparison modes enumeration.
Author
Sylvain DOREMUS
Enumerator
eNone
eRefToTexture
CSCNSection
enum Castor3D::CSCNSection : uint32_t strong
Scene file sections Enum.
The enumeration which defines all the sections and subsections of a scene file
Enumerator
eRoot
eScene
eWindow
eSampler
eCamera
eViewport
eLight
eNode
eObject
eObjectMaterials
eFont
ePanelOverlay
eBorderPanelOverlay
eTextOverlay
eMesh
eSubmesh
eMaterial
ePass
eTextureUnit
eRenderTarget
eShaderProgram
eShaderObject
eShaderUBO
eUBOVariable
eBillboard
eBillboardList
eAnimGroup
eAnimation
eSkybox
eParticleSystem
eParticle
CubeMapFace
enum Castor3D::CubeMapFace : uint8_t strong
Cube map faces.
Author
Sylvain DOREMUS
Enumerator
ePositiveX
Face on positive X
eNegativeX
Face on negative X
ePositiveY
Face on positive Y
eNegativeY
Face on negative Y
ePositiveZ
Face on positive Z
eNegativeZ
Face on negative Z
Culling
enum Castor3D::Culling : uint8_t strong
Culled faces enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
23/05/2013
Enumerator
eNone
No face culled.
eFront
Front faces are culled.
eBack
Back face are culled.
eFrontAndBack
Back and front faces are culled.
DepthFunc
enum Castor3D::DepthFunc : uint8_t strong
Depth functions enumeration.
Author
Sylvain DOREMUS
Version
0.7.0
Date
02/06/2013
Enumerator
eNever
Never passes.
eLess
Passes if the incoming depth value is less than the stored depth value.
eEqual
Passes if the incoming depth value is equal to the stored depth value.
eLEqual
Passes if the incoming depth value is less than or equal to the stored depth value.
eGreater
Passes if the incoming depth value is greater than the stored depth value.
eNEqual
Passes if the incoming depth value is not equal to the stored depth value.
eGEqual
Passes if the incoming depth value is greater than or equal to the stored depth value.
eAlways
Always passes.
ElementType
enum Castor3D::ElementType : uint8_t strong
Element type enumeration.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
03/01/2011
Enumerator
eFloat
1 float (GLSL float)
eVec2
2 floats (GLSL vec2)
eVec3
3 floats (GLSL vec3)
eVec4
4 floats (GLSL vec4)
eColour
colour (uint32_t)
eInt
1 int (4 bytes each, GLSL int)
eIVec2
2 ints (4 bytes each, GLSL ivec2)
eIVec3
3 ints (4 bytes each, GLSL ivec3)
eIVec4
4 ints (4 bytes each, GLSL ivec4)
eUInt
1 uint (4 bytes each, GLSL uint)
eUIVec2
2 uints (4 bytes each, GLSL uivec2)
eUIVec3
3 uints (4 bytes each, GLSL uivec3)
eUIVec4
4 uints (4 bytes each, GLSL uivec4)
eMat2
2x2 floats (GLSL mat2)
eMat3
3x3 floats (GLSL mat3)
eMat4
4x4 floats (GLSL mat4)
ElementUsage
enum Castor3D::ElementUsage : uint32_t strong
Element usage enumeration.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
03/01/2011
Enumerator
eUnknown
Position coords.
ePosition
Position coords.
eNormal
Normal coords.
eTangent
Tangent coords.
eBitangent
Bitangent coords.
eDiffuse
Diffuse colour.
eTexCoords
Texture coordinates.
eBoneIds0
Bone IDs 0.
eBoneIds1
Bone IDs 1.
eBoneWeights0
Bone weights 0.
eBoneWeights1
Bone weights 1.
eTransform
Instantiation matrix.
EventType
enum Castor3D::EventType : uint8_t strong
Frame Event Type enumeration.
Author
Sylvain DOREMUS
Enumerator
ePreRender
This kind of event happens before any render, device context is active (so be fast !!).
eQueueRender
This kind of event happens after the render, before buffers' swap.
ePostRender
This kind of event happens after the buffer' swap.
FillMode
enum Castor3D::FillMode : uint8_t strong
Polygon rasterisation modes enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
23/05/2013
Enumerator
ePoint
Polygon vertices that are marked as the start of a boundary edge are drawn as points.
eLine
Boundary edges of the polygon are drawn as line segments.
eSolid
The interior of the polygon is filled.
FrameBufferMode
enum Castor3D::FrameBufferMode : uint8_t strong
Frame buffer binding modes enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
12/11/2012
Enumerator
eConfig
Frame buffer is bound for configuration.
eAutomatic
Frame buffer is bound and FrameBuffer::SetDrawBuffers is called automatically.
eManual
Frame buffer is bound and user must call FrameBuffer::SetDrawBuffers if he wants.
FrameBufferTarget
enum Castor3D::FrameBufferTarget : uint8_t strong
Frame buffer binding targets enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
12/11/2012
Enumerator
eDraw
Frame buffer is bound as a target for draws.
eRead
Frame buffer is bound as a target for reads.
eBoth
Frame buffer is bound as a target for reads and draws.
FrustumPlane
enum Castor3D::FrustumPlane strong
Frustum view planes enumeration.
Author
Sylvain DOREMUS
Date
10/06/2013
Version
0.7.0
Enumerator
eNear
Near plane.
eFar
Far plane.
eLeft
Left plane.
eRight
Right plane.
eTop
Top plane.
eBottom
Bottom plane.
GpuFeature
enum Castor3D::GpuFeature : uint32_t strong
All supported GPU feature flags.
Author
Sylvain DOREMUS
Date
04/05/2016
Version
0.9.0
Enumerator
eInstancing
Tells whether or not the selected render API supports instanced draw calls.
eAccumulationBuffer
Tells whether or not the selected render API supports accumulation buffers.
eNonPowerOfTwoTextures
Tells whether or not the selected render API supports non power of two textures.
eStereo
Tells whether or not the selected render API supports stereo.
eConstantsBuffers
Tells whether or not the selected render API supports constants buffers.
eTextureBuffers
Tells whether or not the selected render API supports texture buffers.
eShaderStorageBuffers
Tells whether or not the selected render API supports shader stoarage buffers.
eAtomicCounterBuffers
Tells whether or not the selected render API supports atomic counter buffers.
eTransformFeedback
Tells whether or not the selected render API supports transform feedback.
eImmutableTextureStorage
Tells whether or not the selected render API supports texture immutable storages.
GpuMax
enum Castor3D::GpuMax : uint32_t strong
All supported GPU feature flags.
Author
Sylvain DOREMUS
Date
04/05/2016
Version
0.9.0
Enumerator
eShaderStorageBufferBindings
eVertexShaderStorageBlocks
eVertexAtomicCounters
eVertexAttribs
eVertexOutputComponents
eVertexTextureImageUnits
eVertexUniformComponents
eVertexUniformBlocks
eVertexUniformVectors
eVertexCombinedUniformComponents
eGeometryAtomicCounters
eGeometryShaderStorageBlocks
eGeometryInputComponents
eGeometryOutputComponents
eGeometryTextureImageUnits
eGeometryUniformComponents
eGeometryUniformBlocks
eGeometryCombinedUniformComponents
eTessControlAtomicCounters
eTessControlShaderStorageBlocks
eTessEvaluationAtomicCounters
eTessEvaluationShaderStorageBlocks
eComputeAtomicCounters
eComputeAtomicCounterBuffers
eComputeShaderStorageBlocks
eComputeTextureImageUnits
eComputeUniformComponents
eComputeUniformBlocks
eComputeCombinedUniformComponents
eComputeWorkGroupInvocations
eComputeWorkGroupCount
eComputeWorkGroupSize
eFragmentAtomicCounters
eFragmentShaderStorageBlocks
eFragmentInputComponents
eFragmentUniformComponents
eFragmentUniformBlocks
eFragmentUniformVectors
eFragmentCombinedUniformComponents
eCombinedAtomicCounters
eCombinedShaderStorageBlocks
eDebugGroupStackDepth
eLabelLength
eIntegerSamples
eProgramTexelOffset
eServerWaitTimeout
eSampleMaskWords
eSamples
eTexture3DSize
eTextureRectangleSize
eTextureCubeMapSize
eTextureBufferSize
eTextureSize
eTextureImageUnits
eTextureLodBias
eArrayTextureLayers
eClipDistances
eColourTextureSamples
eDepthTextureSamples
eCombinedTextureImageUnits
eCombinedUniformBlocks
eDrawBuffers
eDualSourceDrawBuffers
eElementIndices
eElementVertices
eFramebufferWidth
eFramebufferHeight
eFramebufferLayers
eFramebufferSamples
eRenderbufferSize
eUniformBufferBindings
eUniformBlockSize
eUniformLocations
eVaryingComponents
eVaryingVectors
eVaryingFloats
eViewportWidth
eViewportHeight
eViewports
GpuMin
enum Castor3D::GpuMin : uint32_t strong
All supported GPU feature flags.
Author
Sylvain DOREMUS
Date
04/05/2016
Version
0.9.0
Enumerator
eMapBufferAlignment
eProgramTexelOffset
HAlign
enum Castor3D::HAlign strong
Horizontal alignments for text overlays.
Author
Sylvain DOREMUS
Date
23/09/2015
Version
0.8.0
Enumerator
eLeft
Aligned on the left.
eCenter
Centered horizontally.
eRight
Aligned on the right.
HandlerEventType
enum Castor3D::HandlerEventType : uint8_t strong
Enumeration of supported handler events.
Author
Sylvain DOREMUS
Date
17/04/2016
Version
0.9.0
Enumration des vnements de gestionnaire supportes.
Enumerator
eActivate
Handler activated.
eDeactivate
Handler deactivated.
InterpolationFilter
enum Castor3D::InterpolationFilter : uint8_t strong
Texture interpolation filters enumeration.
Author
Sylvain DOREMUS
Enumerator
eMin
eMag
eMip
eCount
InterpolationMode
enum Castor3D::InterpolationMode : uint8_t strong
Texture filter interpolation modes enumeration.
Author
Sylvain DOREMUS
Enumerator
eUndefined
eNearest
eLinear
InterpolatorType
enum Castor3D::InterpolatorType : uint8_t strong
Interpolation modes enumeration.
Author
Sylvain DOREMUS
Version
0.1
Date
09/02/2010
Enumerator
eNearest
No interpolation.
eLinear
Linear mode.
KeyboardEventType
enum Castor3D::KeyboardEventType : uint8_t strong
Enumeration of supported keyboard events.
Author
Sylvain DOREMUS
Date
17/04/2016
Version
0.9.0
Enumration des vnement clavier supports.
Enumerator
ePushed
A key is pushed.
eReleased
A key is released.
eChar
A displayable char key is stroked.
KeyboardKey
enum Castor3D::KeyboardKey strong
Keyboard keys enumeration.
Author
Sylvain DOREMUS
Date
17/04/2016
Version
0.9.0
Enumerator
eNone
eBackspace
eTab
eReturn
eEscape
eSpace
eDelete
eStart
eLButton
eRButton
eCancel
eMButton
eClear
eShift
eAlt
eControl
eMenu
ePause
eCapital
eEnd
eHome
eLeft
eUp
eRight
eDown
eSelect
ePrint
eExecute
eSnapshot
eInsert
eHelp
eNumpad0
eNumpad1
eNumpad2
eNumpad3
eNumpad4
eNumpad5
eNumpad6
eNumpad7
eNumpad8
eNumpad9
eMultiply
eAdd
eSeparator
eSubtract
eDecimal
eDivide
eF1
eF2
eF3
eF4
eF5
eF6
eF7
eF8
eF9
eF10
eF11
eF12
eF13
eF14
eF15
eF16
eF17
eF18
eF19
eF20
eF21
eF22
eF23
eF24
eNumlock
eScroll
ePageUp
ePageDown
eNumpadSpace
eNumpadTab
eNumpadEnter
eNumpadF1
eNumpadF2
eNumpadF3
eNumpadF4
eNumpadHome
eNumpadLeft
eNumpadUp
eNumpadRight
eNumpadDown
eNumpadPageUp
eNumpadPageDown
eNumpadEnd
eNumpadBegin
eNumpadInsert
eNumpadDelete
eNumpadEqual
eNumpadMultiply
eNumpadAdd
eNumpadSeparator
eNumpadSubtract
eNumpadDecimal
eNumpadDivide
LightType
enum Castor3D::LightType : uint8_t strong
Light types enumeration.
Author
Sylvain DOREMUS
Enumerator
eDirectional
Directional light type.
ePoint
Point light type.
eSpot
Spot light type.
MaterialType
enum Castor3D::MaterialType strong
Supported material types enumeration.
Author
Sylvain DOREMUS
Version
0.9.0
Date
02/12/2016
Enumerator
eLegacy
Traditional (pre-PBR).
MatrixMode
enum Castor3D::MatrixMode : uint8_t strong
Matrix modes enumeration.
Author
Sylvain DOREMUS
Enumerator
eProjection
Eye to Clip transform.
eModel
Object to World transform.
eView
World to Eye transform.
eTexture0
Texture transforms.
eTexture1
Texture transforms.
eTexture2
Texture transforms.
eTexture3
Texture transforms.
eTexture4
Texture transforms.
eTexture5
Texture transforms.
eTexture6
Texture transforms.
eTexture7
Texture transforms.
eTexture8
Texture transforms.
eTexture9
Texture transforms.
eTexture10
Texture transforms.
eTexture11
Texture transforms.
eTexture12
Texture transforms.
eTexture13
Texture transforms.
eTexture14
Texture transforms.
eTexture15
Texture transforms.
MemoryBarrier
enum Castor3D::MemoryBarrier : uint32_t strong
Supported memory barriers enumeration.
Author
Sylvain DOREMUS
Version
0.8.0
Date
16/03/2016
Enumerator
eVertexBuffer
eIndexBuffer
eUniformBuffer
eAtomicCounterBuffer
eQueryBuffer
eShaderStorageBuffer
eAll
MeshType
enum Castor3D::MeshType : uint8_t strong
Mesh type enumeration.
Author
Sylvain DOREMUS
Enumerator
eCustom
Custom mesh type => User defined vertex, imported mesh...
eCone
Cone mesh type.
eCylinder
Cylinder mesh type.
eSphere
Rectangular faces sphere mesh type.
eCube
Cube mesh type.
eTorus
Torus mesh type.
ePlane
Plane mesh type.
eIcosahedron
Triangular faces sphere mesh type.
eProjection
Projection mesh type.
MouseButton
enum Castor3D::MouseButton strong
Mouse buttons enumeration.
Author
Sylvain DOREMUS
Date
17/04/2016
Version
0.9.0
Enumerator
eLeft
Left mouse button.
eMiddle
Middle mouse button.
eRight
Right mouse button.
MouseEventType
enum Castor3D::MouseEventType : uint8_t strong
Enumeration of supported mouse events.
Author
Sylvain DOREMUS
Date
17/04/2016
Version
0.9.0
Enumration des vnement de souris supports.
Enumerator
eMove
The mouse moves.
eEnter
The mouse enters an handler's zone.
eHover
The mouse remains still in an handler's zone during hover time.
eLeave
The mouse leaves an handler's zone.
ePushed
One mouse button is pushed.
eReleased
One mouse button is released.
eWheel
One mouse wheel is rolled.
MovableType
enum Castor3D::MovableType : uint8_t strong
Movable object types enumerator.
Author
Sylvain DOREMUS
Version
0.1
Date
09/02/2010
Remarks
There are four movable object types : camera, geometry, light and billboard.
Enumerator
eCamera
eGeometry
eLight
eBillboard
eParticleEmitter
OverlayType
enum Castor3D::OverlayType : uint8_t strong
Overlay types enumeration.
Author
Sylvain DOREMUS
Enumerator
ePanel
eBorderPanel
eText
PluginType
enum Castor3D::PluginType : uint8_t strong
Plugin types enumeration.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
03/01/2011
Enumerator
eRenderer
Renderer plug-in.
eImporter
Importer plug-in.
eDivider
Mesh Divider plug-in.
eGenerator
Procedural generator.
eTechnique
Render technique plug-in.
eToneMapping
Tone mapping plug-in.
ePostEffect
Post effect plug-in.
eGeneric
Generic plug-in.
eParticle
Particle plug-in.
ProgramFlag
enum Castor3D::ProgramFlag : uint16_t strong
Flags to use when looking for an automatically generated program.
Author
Sylvain DOREMUS
Date
20/11/13
Version
0.7.0.0
Enumerator
eInstantiation
Program using instanciation.
eSkinning
Program using skeleton animations.
eBillboards
Program used by billboards.
eMorphing
Program using per-vertex animations.
eAlphaBlending
Program used in transparent pipeline.
ePicking
Picking pass program.
eLighting
Shader supporting lighting.
eSpherical
Shader for spherical billboards.
eFixedSize
Shader for fixed size billboards.
eShadowMapDirectional
Shader used to render a shadow map for directional light.
eShadowMapSpot
Shader used to render a shadow map for spot light.
eShadowMapPoint
Shader used to render a shadow map for point light.
ProgramStatus
enum Castor3D::ProgramStatus : uint8_t strong
Program status enumeration.
Author
Sylvain DOREMUS
Date
22/08/2012
Version
0.7.0.0
Enumerator
eNotLinked
eError
eLinked
QueryInfo
enum Castor3D::QueryInfo : uint32_t strong
GPU query supported informations enumeration.
Author
Sylvain DOREMUS
Version
0.8.0
Date
16/03/2016
Enumerator
eResult
eResultAvailable
eResultNoWait
QueryType
enum Castor3D::QueryType : uint32_t strong
GPU query supported types enumeration.
Author
Sylvain DOREMUS
Version
0.8.0
Date
16/03/2016
Enumerator
eTimeElapsed
eSamplesPassed
eAnySamplesPassed
ePrimitivesGenerated
eTransformFeedbackPrimitivesWritten
eAnySamplesPassedConservative
eTimestamp
SceneFlag
enum Castor3D::SceneFlag : uint16_t strong
Scene flags enumeration.
Author
Sylvain DOREMUS
Version
0.9.0
Date
08/03/2017
Enumerator
eNone
No flag.
eFogLinear
Linear fog.
eFogExponential
Exponential fog.
eFogSquaredExponential
Squared exponential fog.
eShadowFilterRaw
No filtering.
eShadowFilterPoisson
Poisson filtering.
eShadowFilterStratifiedPoisson
Stratified poisson filtering.
ShaderModel
enum Castor3D::ShaderModel : uint8_t strong
Enumeration of existing shader models.
Author
Sylvain DOREMUS
Enumerator
eModel1
Vertex shaders.
eModel2
Pixel shaders.
eModel3
Geometry shaders.
eModel4
Tessellation shaders.
eModel5
Compute shaders.
ShaderStatus
enum Castor3D::ShaderStatus : uint8_t strong
Shader status enueration.
Author
Sylvain DOREMUS
Date
22/08/2012
Version
0.7.0.0
Enumerator
eDontExist
eNotCompiled
eError
eCompiled
ShaderType
enum Castor3D::ShaderType : int8_t strong
Shader object types enumeration.
Author
Sylvain DOREMUS
Enumerator
eNone
eVertex
eHull
eDomain
eGeometry
ePixel
eCompute
ShaderTypeFlag
enum Castor3D::ShaderTypeFlag : uint8_t strong
Shader object types masks.
Author
Sylvain DOREMUS
Enumerator
eVertex
eHull
eDomain
eGeometry
ePixel
eCompute
SkeletonAnimationObjectType
enum Castor3D::SkeletonAnimationObjectType : uint8_t strong
Class which represents the moving things.
Author
Sylvain DOREMUS
Version
0.1
Date
09/02/2010
Remarks
Manages translation, scaling, rotation of the thing.
Enumerator
eNode
Node objects.
eBone
Bone objects.
StencilFunc
enum Castor3D::StencilFunc : uint8_t strong
Stencil functions enumeration.
Author
Sylvain DOREMUS
Version
0.7.0
Date
02/06/2013
Enumerator
eNever
Never passes.
eLess
Passes if the incoming stencil value is less than the stored stencil value.
eEqual
Passes if the incoming stencil value is equal to the stored stencil value.
eLEqual
Passes if the incoming stencil value is less than or equal to the stored stencil value.
eGreater
Passes if the incoming stencil value is greater than the stored stencil value.
eNEqual
Passes if the incoming stencil value is not equal to the stored stencil value.
eGEqual
Passes if the incoming stencil value is greater than or equal to the stored stencil value.
eAlways
Always passes.
StencilOp
enum Castor3D::StencilOp : uint8_t strong
Stencil functions enumeration.
Author
Sylvain DOREMUS
Version
0.7.0
Date
02/06/2013
Enumerator
eKeep
Keeps the current value.
eZero
Sets the stencil buffer value to 0.
eReplace
Sets the stencil buffer value by the one given.
eIncrement
Increments the current stencil buffer value. Clamps to the maximum representable unsigned value.
eIncrWrap
Increments the current stencil buffer value. Wraps stencil buffer value to zero when incrementing the maximum representable unsigned value.
eDecrement
Decrements the current stencil buffer value. Clamps to 0.
eDecrWrap
Decrements the current stencil buffer value. Wraps stencil buffer value to the maximum representable unsigned value when decrementing a stencil buffer value of zero.
eInvert
Bitwise inverts the current stencil buffer value.
TargetType
enum Castor3D::TargetType : uint8_t strong
RenderTarget supported types.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
19/10/2011
Enumerator
eWindow
eTexture
TextLineSpacingMode
enum Castor3D::TextLineSpacingMode strong
Text line spacing modes, handles the way lines are spaced, which each other, inside one TextOverlay.
Author
Sylvain DOREMUS
Date
16/04/2016
Enumerator
eOwnHeight
The height of each line is its own height.
eMaxLineHeight
The height of the lines is the maximum height between them.
eMaxFontHeight
The height of the lines is the maximum height from the font's characters.
TextTexturingMode
enum Castor3D::TextTexturingMode strong
Text texturing modes, handles the way textures are appied to text overlays.
Author
Sylvain DOREMUS
Date
26/03/2016
Enumerator
eLetter
The texture is repeated on each character of the text.
eText
The texture is applied on the whole text.
TextureChannel
enum Castor3D::TextureChannel : uint16_t strong
Texture channels enumeration.
Author
Sylvain DOREMUS
Enumerator
eUndefined
Undefined channel.
eColour
Colour map
eDiffuse
Diffuse map
eNormal
Normal map
eOpacity
Opacity map
eSpecular
Specular map
eHeight
Height map
eAmbient
Ambient map
eGloss
Gloss map
eEmissive
Emissive map
eAll
Mask for all the texture channels
eText
Not really a texture channel (it is out of TextureChannel::eAll), used to tell we want text overlay shader source
TextureStorageType
enum Castor3D::TextureStorageType : uint8_t strong
Texture dimensions enumeration.
Author
Sylvain DOREMUS
Enumerator
eBuffer
1 dimension texture buffer, used to store data.
eOneDimension
1 dimension textures.
eOneDimensionArray
1 dimension texture arrays.
eTwoDimensions
2 dimensions textures.
eTwoDimensionsArray
2 dimensions texture arrays.
eTwoDimensionsMS
2 dimensions textures with multisample support.
eThreeDimensions
3 dimensions textures.
eCubeMap
Cube map.
eCubeMapArray
Cube map array.
TextureType
enum Castor3D::TextureType : uint8_t strong
Texture dimensions enumeration.
Author
Sylvain DOREMUS
Enumerator
eBuffer
1 dimension texture buffer, used to store data.
eOneDimension
1 dimension textures => one coordinate => U mapping
eOneDimensionArray
1 dimension textures array => one coordinate => U mapping
eTwoDimensions
2 dimensions textures => two coordinates => UV mapping
eTwoDimensionsArray
2 dimensions textures array => two coordinates => UV mapping
eTwoDimensionsMS
2 dimensions textures with multisample support => two coordinates => UV mapping
eTwoDimensionsMSArray
2 dimensions textures array with multisample support => two coordinates => UV mapping
eThreeDimensions
3 dimensions textures => three coordinates => UVW mapping
eCube
Cube texture.
eCubeArray
Cube textures array.
TextureUVW
enum Castor3D::TextureUVW : uint8_t strong
Texture UVW enumeration.
Author
Sylvain DOREMUS
Enumerator
eU
eV
eW
TextWrappingMode
enum Castor3D::TextWrappingMode strong
Text wrapping modes, handles the way text is cut when it overflows the overlay width.
Author
Sylvain DOREMUS
Date
28/11/2014
Enumerator
eNone
The text is cut.
eBreak
The text jumps to next line.
eBreakWords
The text jumps to next line without cutting words.
Topology
enum Castor3D::Topology : uint8_t strong
Primitive draw types enumeration.
Author
Sylvain DOREMUS
Enumerator
ePoints
Display textured points.
eLines
Display textured edges.
eLineLoop
Display textured edge loops.
eLineStrip
Display textured edge strips.
eTriangles
Display textured triangles.
eTriangleStrips
Display triangle strips.
eTriangleFan
Display triangle fan.
eQuads
Display quads.
eQuadStrips
Display quad strips.
ePolygon
Display quad strips.
UniformType
enum Castor3D::UniformType : uint8_t strong
Supported variables full type enumeration.
Author
Sylvain DOREMUS
Enumerator
eBool
eInt
eUInt
eFloat
eDouble
eSampler
eVec2b
eVec3b
eVec4b
eVec2i
eVec3i
eVec4i
eVec2ui
eVec3ui
eVec4ui
eVec2f
eVec3f
eVec4f
eVec2d
eVec3d
eVec4d
eMat2x2b
eMat2x3b
eMat2x4b
eMat3x2b
eMat3x3b
eMat3x4b
eMat4x2b
eMat4x3b
eMat4x4b
eMat2x2i
eMat2x3i
eMat2x4i
eMat3x2i
eMat3x3i
eMat3x4i
eMat4x2i
eMat4x3i
eMat4x4i
eMat2x2ui
eMat2x3ui
eMat2x4ui
eMat3x2ui
eMat3x3ui
eMat3x4ui
eMat4x2ui
eMat4x3ui
eMat4x4ui
eMat2x2f
eMat2x3f
eMat2x4f
eMat3x2f
eMat3x3f
eMat3x4f
eMat4x2f
eMat4x3f
eMat4x4f
eMat2x2d
eMat2x3d
eMat2x4d
eMat3x2d
eMat3x3d
eMat3x4d
eMat4x2d
eMat4x3d
eMat4x4d
eReal
eVec2r
eVec3r
eVec4r
eMat2x2r
eMat2x3r
eMat2x4r
eMat3x2r
eMat3x3r
eMat3x4r
eMat4x2r
eMat4x3r
eMat4x4r
UserInputEventType
enum Castor3D::UserInputEventType strong
Supported events types enumeration.
Author
Sylvain DOREMUS
Date
17/04/2016
Version
0.9.0
Enumerator
eMouse
Mouse event type.
eKeyboard
Keyboard event type.
eHandler
Keyboard event type.
VAlign
enum Castor3D::VAlign strong
Vertical alignments for text overlays.
Author
Sylvain DOREMUS
Date
23/09/2015
Version
0.8.0
Enumerator
eTop
Aligned on the top.
eCenter
Centered vertically.
eBottom
Aligned on the bottom.
VariableType
enum Castor3D::VariableType : uint8_t strong
Supported variables dimensions enumeration.
Author
Sylvain DOREMUS
Enumerator
eOne
One variable.
eVec1
1 variable array.
eVec2
2 variables array.
eVec3
3 variables array.
eVec4
4 variables array.
eMat1
1x1 matrix.
eMat2x2
2x2 matrix.
eMat2x3
2x3 matrix.
eMat2x4
2x4 matrix.
eMat3x2
3x2 matrix.
eMat3x3
3x3 matrix.
eMat3x4
3x4 matrix.
eMat4x2
4x2 matrix.
eMat4x3
4x3 matrix.
eMat4x4
4x4 matrix.
ViewportType
enum Castor3D::ViewportType : uint8_t strong
The viewport projection types enumeration.
Author
Sylvain DOREMUS
Enumerator
eOrtho
ePerspective
eFrustum
WindowBuffer
enum Castor3D::WindowBuffer : uint8_t strong
Frame buffer components enumeration.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
12/11/2012
Enumerator
eNone
eFrontLeft
eFrontRight
eBackLeft
eBackRight
eFront
eBack
eLeft
eRight
eFrontAndBack
WrapMode
enum Castor3D::WrapMode : uint8_t strong
Texture wrap modes enumeration.
Author
Sylvain DOREMUS
Enumerator
eRepeat
eMirroredRepeat
eClampToBorder
eClampToEdge
WritingMask
enum Castor3D::WritingMask : uint8_t strong
Wrinting masks enumeration.
Author
Sylvain DOREMUS
Version
0.7.0
Date
02/06/2013
Enumerator
eZero
Writing disabled.
eAll
Writing enabled.
Function Documentation
ComputePostLightingMapContributions()
C3D_API void Castor3D::ComputePostLightingMapContributions (GLSL::GlslWriter & p_writer, GLSL::Vec3 & p_ambient, GLSL::Vec3 & p_diffuse, GLSL::Vec3 & p_specular, GLSL::Vec3 & p_emissive, TextureChannels const & p_textureFlags, ProgramFlags const & p_programFlags, SceneFlags const & p_sceneFlags)
ComputePreLightingMapContributions()
C3D_API void Castor3D::ComputePreLightingMapContributions (GLSL::GlslWriter & p_writer, GLSL::Vec3 & p_normal, GLSL::Float & p_shininess, TextureChannels const & p_textureFlags, ProgramFlags const & p_programFlags, SceneFlags const & p_sceneFlags)
DECLARE_ARRAY() [1/2]
Castor3D::DECLARE_ARRAY (PluginStrMap , PluginType::eCount , PluginStrMap)
DECLARE_ARRAY() [2/2]
Castor3D::DECLARE_ARRAY (DynamicLibraryPtrPathMap , PluginType::eCount , DynamicLibraryPtrPathMap)
DECLARE_LIST() [1/6]
Castor3D::DECLARE_LIST (VertexSPtr , VertexPtr)
Vertex pointer list.
DECLARE_LIST() [2/6]
Castor3D::DECLARE_LIST (PushUniformSPtr , PushUniform)
DECLARE_LIST() [3/6]
Castor3D::DECLARE_LIST (UniformSPtr , Uniform)
DECLARE_LIST() [4/6]
Castor3D::DECLARE_LIST (UniformBufferSPtr , UniformBufferPtr)
DECLARE_LIST() [5/6]
Castor3D::DECLARE_LIST (ShaderStorageBufferSPtr , ShaderStorageBufferPtr)
DECLARE_LIST() [6/6]
Castor3D::DECLARE_LIST (AtomicCounterBufferSPtr , AtomicCounterBufferPtr)
DECLARE_MAP() [1/47]
Castor3D::DECLARE_MAP (Castor::String , CameraSPtr , CameraPtrStr)
Camera pointer map, sorted by name.
DECLARE_MAP() [2/47]
Castor3D::DECLARE_MAP (Castor::String , LightSPtr , LightPtrStr)
Map of lights, sorted by name.
DECLARE_MAP() [3/47]
Castor3D::DECLARE_MAP (int , LightSPtr , LightPtrInt)
Map of lights, sorted by index.
DECLARE_MAP() [4/47]
Castor3D::DECLARE_MAP (RenderPipelineRPtr , StaticRenderNodeArray , StaticRenderNodesByPipeline)
DECLARE_MAP() [5/47]
Castor3D::DECLARE_MAP (RenderPipelineRPtr , SkinningRenderNodeArray , SkinningRenderNodesByPipeline)
DECLARE_MAP() [6/47]
Castor3D::DECLARE_MAP (RenderPipelineRPtr , MorphingRenderNodeArray , MorphingRenderNodesByPipeline)
DECLARE_MAP() [7/47]
Castor3D::DECLARE_MAP (RenderPipelineRPtr , BillboardRenderNodeArray , BillboardRenderNodesByPipeline)
DECLARE_MAP() [8/47]
Castor3D::DECLARE_MAP (SubmeshRPtr , StaticRenderNodeArray , SubmeshStaticRenderNodes)
DECLARE_MAP() [9/47]
Castor3D::DECLARE_MAP (RenderPipelineRPtr , SubmeshStaticRenderNodesByPassMap , SubmeshStaticRenderNodesByPipeline)
DECLARE_MAP() [10/47]
Castor3D::DECLARE_MAP (Castor::String , MeshSPtr , MeshPtrStr)
Mesh pointer array.
DECLARE_MAP() [11/47]
Castor3D::DECLARE_MAP (Castor::String , MovableObjectSPtr , MovableObjectPtrStr)
MovableObject pointer map, sorted by name.
DECLARE_MAP() [12/47]
Castor3D::DECLARE_MAP (Castor::String , GeometrySPtr , GeometryPtrStr)
Geometry pointer map, sorted by name.
DECLARE_MAP() [13/47]
Castor3D::DECLARE_MAP (uint32_t , int , IntUInt)
DECLARE_MAP() [14/47]
Castor3D::DECLARE_MAP (Castor::String , SubmeshSPtr , SubmeshPtrStr)
DECLARE_MAP() [15/47]
Castor3D::DECLARE_MAP (Castor::String , int , IntStr)
DECLARE_MAP() [16/47]
Castor3D::DECLARE_MAP (Castor::String , BoneSPtr , BonePtrStr)
Bone pointer map sorted by name.
DECLARE_MAP() [17/47]
Castor3D::DECLARE_MAP (Castor::String , OverlaySPtr , OverlayPtrStr)
DECLARE_MAP() [18/47]
Castor3D::DECLARE_MAP (Castor::String , AnimationSPtr , AnimationPtrStr)
Animation pointer map, sorted by name.
DECLARE_MAP() [19/47]
Castor3D::DECLARE_MAP (Castor::String , SkeletonAnimationObjectSPtr , SkeletonAnimationObjectPtrStr)
SkeletonAnimationObject pointer map, sorted by name.
DECLARE_MAP() [20/47]
Castor3D::DECLARE_MAP (Castor::String , SceneSPtr , ScenePtrStr)
Scene pointer map, sorted by name.
DECLARE_MAP() [21/47]
Castor3D::DECLARE_MAP (Castor::String , SceneNodeSPtr , SceneNodePtrStr)
SceneNode pointer map, sorted by name.
DECLARE_MAP() [22/47]
Castor3D::DECLARE_MAP (Castor::String , AnimatedObjectGroupSPtr , AnimatedObjectGroupPtrStr)
AnimatedObjectGroup pointer map, sorted by name.
DECLARE_MAP() [23/47]
Castor3D::DECLARE_MAP (Castor::String , AnimatedObjectSPtr , AnimatedObjectPtrStr)
AnimatedObject pointer map, sorted by name.
DECLARE_MAP() [24/47]
Castor3D::DECLARE_MAP (Castor::String , SkeletonAnimationInstanceObjectSPtr , SkeletonAnimationInstanceObjectPtrStr)
MovingObject pointer map, sorted by name.
DECLARE_MAP() [25/47]
Castor3D::DECLARE_MAP (uint32_t , MeshAnimationInstanceSubmesh , MeshAnimationInstanceSubmesh)
MeshAnimationInstanceSubmesh map, sorted by submesh ID.
DECLARE_MAP() [26/47]
Castor3D::DECLARE_MAP (Castor::String , AnimationInstanceUPtr , AnimationInstancePtrStr)
Animation pointer map, sorted by name.
DECLARE_MAP() [27/47]
Castor3D::DECLARE_MAP (Castor::String , MaterialSPtr , MaterialPtrStr)
Material pointer map, sorted by name.
DECLARE_MAP() [28/47]
Castor3D::DECLARE_MAP (uint32_t , MaterialSPtr , MaterialPtrUInt)
Material pointer map.
DECLARE_MAP() [29/47]
Castor3D::DECLARE_MAP (Castor::String , FrameListenerSPtr , FrameListenerPtrStr)
FrameListener pointer map, sorted by name.
DECLARE_MAP() [30/47]
Castor3D::DECLARE_MAP (uint32_t , RenderWindowSPtr , RenderWindow)
RenderWindow pointer map, sorted by index.
DECLARE_MAP() [31/47]
Castor3D::DECLARE_MAP (Castor::String , PluginSPtr , PluginStr)
Plugin map, sorted by name.
DECLARE_MAP() [32/47]
Castor3D::DECLARE_MAP (int , Castor::String , StrInt)
DECLARE_MAP() [33/47]
Castor3D::DECLARE_MAP (Castor::String , RendererPluginSPtr , RendererPtr)
DECLARE_MAP() [34/47]
Castor3D::DECLARE_MAP (Castor::Path , Castor::DynamicLibrarySPtr , DynamicLibraryPtrPath)
DECLARE_MAP() [35/47]
Castor3D::DECLARE_MAP (Castor::Path , PluginType , PluginTypePath)
DECLARE_MAP() [36/47]
Castor3D::DECLARE_MAP (Castor::String , BillboardListSPtr , BillboardListStr)
DECLARE_MAP() [37/47]
Castor3D::DECLARE_MAP (RenderWindow * , ContextSPtr , ContextPtr)
DECLARE_MAP() [38/47]
Castor3D::DECLARE_MAP (std::thread::id , ContextPtrMap , ContextPtrMapId)
DECLARE_MAP() [39/47]
Castor3D::DECLARE_MAP (Castor::String , PushUniformWPtr , PushUniform)
DECLARE_MAP() [40/47]
Castor3D::DECLARE_MAP (Castor::String , UniformWPtr , Uniform)
DECLARE_MAP() [41/47]
Castor3D::DECLARE_MAP (ShaderProgramRPtr , UniformBufferBindingUPtr , UniformBufferBinding)
DECLARE_MAP() [42/47]
Castor3D::DECLARE_MAP (Castor::String , UniformBufferWPtr , UniformBufferPtrStr)
DECLARE_MAP() [43/47]
Castor3D::DECLARE_MAP (Castor::String , ShaderStorageBufferWPtr , ShaderStorageBufferPtrStr)
DECLARE_MAP() [44/47]
Castor3D::DECLARE_MAP (Castor::String , AtomicCounterBufferWPtr , AtomicCounterBufferPtrStr)
DECLARE_MAP() [45/47]
Castor3D::DECLARE_MAP (ShaderType , UniformBufferWPtr , UniformBufferPtrShader)
DECLARE_MAP() [46/47]
Castor3D::DECLARE_MAP (ShaderType , ShaderStorageBufferWPtr , ShaderStorageBufferPtrShader)
DECLARE_MAP() [47/47]
Castor3D::DECLARE_MAP (ShaderType , AtomicCounterBufferWPtr , AtomicCounterBufferPtrShader)
DECLARE_MULTIMAP() [1/4]
Castor3D::DECLARE_MULTIMAP (double , StaticRenderNode , StaticRenderNodeByDistance)
DECLARE_MULTIMAP() [2/4]
Castor3D::DECLARE_MULTIMAP (double , SkinningRenderNode , SkinningRenderNodeByDistance)
DECLARE_MULTIMAP() [3/4]
Castor3D::DECLARE_MULTIMAP (double , MorphingRenderNode , MorphingRenderNodeByDistance)
DECLARE_MULTIMAP() [4/4]
Castor3D::DECLARE_MULTIMAP (double , BillboardRenderNode , BillboardRenderNodeByDistance)
DECLARE_SMART_PTR() [1/153]
Castor3D::DECLARE_SMART_PTR (Camera)
DECLARE_SMART_PTR() [2/153]
Castor3D::DECLARE_SMART_PTR (Viewport)
DECLARE_SMART_PTR() [3/153]
Castor3D::DECLARE_SMART_PTR (IViewportImpl)
DECLARE_SMART_PTR() [4/153]
Castor3D::DECLARE_SMART_PTR (Ray)
DECLARE_SMART_PTR() [5/153]
Castor3D::DECLARE_SMART_PTR (Light)
DECLARE_SMART_PTR() [6/153]
Castor3D::DECLARE_SMART_PTR (LightCategory)
DECLARE_SMART_PTR() [7/153]
Castor3D::DECLARE_SMART_PTR (DirectionalLight)
DECLARE_SMART_PTR() [8/153]
Castor3D::DECLARE_SMART_PTR (PointLight)
DECLARE_SMART_PTR() [9/153]
Castor3D::DECLARE_SMART_PTR (SpotLight)
DECLARE_SMART_PTR() [10/153]
Castor3D::DECLARE_SMART_PTR (LightFactory)
DECLARE_SMART_PTR() [11/153]
Castor3D::DECLARE_SMART_PTR (Vertex)
DECLARE_SMART_PTR() [12/153]
Castor3D::DECLARE_SMART_PTR (BufferElementGroup)
DECLARE_SMART_PTR() [13/153]
Castor3D::DECLARE_SMART_PTR (Importer)
DECLARE_SMART_PTR() [14/153]
Castor3D::DECLARE_SMART_PTR (VertexPattern)
DECLARE_SMART_PTR() [15/153]
Castor3D::DECLARE_SMART_PTR (Point3rPattern)
DECLARE_SMART_PTR() [16/153]
Castor3D::DECLARE_SMART_PTR (VertexPtrPattern)
DECLARE_SMART_PTR() [17/153]
Castor3D::DECLARE_SMART_PTR (Face)
DECLARE_SMART_PTR() [18/153]
Castor3D::DECLARE_SMART_PTR (Graph)
DECLARE_SMART_PTR() [19/153]
Castor3D::DECLARE_SMART_PTR (Mesh)
DECLARE_SMART_PTR() [20/153]
Castor3D::DECLARE_SMART_PTR (MeshGenerator)
DECLARE_SMART_PTR() [21/153]
Castor3D::DECLARE_SMART_PTR (Submesh)
DECLARE_SMART_PTR() [22/153]
Castor3D::DECLARE_SMART_PTR (Cone)
DECLARE_SMART_PTR() [23/153]
Castor3D::DECLARE_SMART_PTR (Cylinder)
DECLARE_SMART_PTR() [24/153]
Castor3D::DECLARE_SMART_PTR (Icosahedron)
DECLARE_SMART_PTR() [25/153]
Castor3D::DECLARE_SMART_PTR (Cube)
DECLARE_SMART_PTR() [26/153]
Castor3D::DECLARE_SMART_PTR (Plane)
DECLARE_SMART_PTR() [27/153]
Castor3D::DECLARE_SMART_PTR (Projection)
DECLARE_SMART_PTR() [28/153]
Castor3D::DECLARE_SMART_PTR (Sphere)
DECLARE_SMART_PTR() [29/153]
Castor3D::DECLARE_SMART_PTR (Torus)
DECLARE_SMART_PTR() [30/153]
Castor3D::DECLARE_SMART_PTR (Geometry)
DECLARE_SMART_PTR() [31/153]
Castor3D::DECLARE_SMART_PTR (MovableObject)
DECLARE_SMART_PTR() [32/153]
Castor3D::DECLARE_SMART_PTR (Subdivider)
DECLARE_SMART_PTR() [33/153]
Castor3D::DECLARE_SMART_PTR (FaceGroup)
DECLARE_SMART_PTR() [34/153]
Castor3D::DECLARE_SMART_PTR (Bone)
DECLARE_SMART_PTR() [35/153]
Castor3D::DECLARE_SMART_PTR (Skeleton)
DECLARE_SMART_PTR() [36/153]
Castor3D::DECLARE_SMART_PTR (BonedVertex)
DECLARE_SMART_PTR() [37/153]
Castor3D::DECLARE_SMART_PTR (MeshFactory)
DECLARE_SMART_PTR() [38/153]
Castor3D::DECLARE_SMART_PTR (SceneNode)
DECLARE_SMART_PTR() [39/153]
Castor3D::DECLARE_SMART_PTR (Scene)
DECLARE_SMART_PTR() [40/153]
Castor3D::DECLARE_SMART_PTR (SceneFileContext)
DECLARE_SMART_PTR() [41/153]
Castor3D::DECLARE_SMART_PTR (SceneFileParser)
DECLARE_SMART_PTR() [42/153]
Castor3D::DECLARE_SMART_PTR (Skybox)
DECLARE_SMART_PTR() [43/153]
Castor3D::DECLARE_SMART_PTR (ParticleSystem)
DECLARE_SMART_PTR() [44/153]
Castor3D::DECLARE_SMART_PTR (GeometryCache)
DECLARE_SMART_PTR() [45/153]
Castor3D::DECLARE_SMART_PTR (ParticleSystemImpl)
DECLARE_SMART_PTR() [46/153]
Castor3D::DECLARE_SMART_PTR (CpuParticleSystem)
DECLARE_SMART_PTR() [47/153]
Castor3D::DECLARE_SMART_PTR (TransformFeedbackParticleSystem)
DECLARE_SMART_PTR() [48/153]
Castor3D::DECLARE_SMART_PTR (ComputeParticleSystem)
DECLARE_SMART_PTR() [49/153]
Castor3D::DECLARE_SMART_PTR (AnimatedObject)
DECLARE_SMART_PTR() [50/153]
Castor3D::DECLARE_SMART_PTR (AnimatedObjectGroup)
DECLARE_SMART_PTR() [51/153]
Castor3D::DECLARE_SMART_PTR (OverlayFactory)
DECLARE_SMART_PTR() [52/153]
Castor3D::DECLARE_SMART_PTR (OverlayRenderer)
DECLARE_SMART_PTR() [53/153]
Castor3D::DECLARE_SMART_PTR (AnimatedSkeleton)
DECLARE_SMART_PTR() [54/153]
Castor3D::DECLARE_SMART_PTR (FontTexture)
DECLARE_SMART_PTR() [55/153]
Castor3D::DECLARE_SMART_PTR (AnimatedMesh)
DECLARE_SMART_PTR() [56/153]
Castor3D::DECLARE_SMART_PTR (Animation)
DECLARE_SMART_PTR() [57/153]
Castor3D::DECLARE_SMART_PTR (AnimationInstance)
DECLARE_SMART_PTR() [58/153]
Castor3D::DECLARE_SMART_PTR (SkeletonAnimation)
DECLARE_SMART_PTR() [59/153]
Castor3D::DECLARE_SMART_PTR (Overlay)
DECLARE_SMART_PTR() [60/153]
Castor3D::DECLARE_SMART_PTR (SkeletonAnimationInstance)
DECLARE_SMART_PTR() [61/153]
Castor3D::DECLARE_SMART_PTR (SkeletonAnimationObject)
DECLARE_SMART_PTR() [62/153]
Castor3D::DECLARE_SMART_PTR (OverlayCategory)
DECLARE_SMART_PTR() [63/153]
Castor3D::DECLARE_SMART_PTR (SkeletonAnimationInstanceObject)
DECLARE_SMART_PTR() [64/153]
Castor3D::DECLARE_SMART_PTR (MaterialCache)
DECLARE_SMART_PTR() [65/153]
Castor3D::DECLARE_SMART_PTR (SkeletonAnimationBone)
DECLARE_SMART_PTR() [66/153]
Castor3D::DECLARE_SMART_PTR (PanelOverlay)
DECLARE_SMART_PTR() [67/153]
Castor3D::DECLARE_SMART_PTR (SkeletonAnimationInstanceNode)
DECLARE_SMART_PTR() [68/153]
Castor3D::DECLARE_SMART_PTR (SkeletonAnimationNode)
DECLARE_SMART_PTR() [69/153]
Castor3D::DECLARE_SMART_PTR (BorderPanelOverlay)
DECLARE_SMART_PTR() [70/153]
Castor3D::DECLARE_SMART_PTR (MeshAnimation)
DECLARE_SMART_PTR() [71/153]
Castor3D::DECLARE_SMART_PTR (SkeletonAnimationInstanceBone)
DECLARE_SMART_PTR() [72/153]
Castor3D::DECLARE_SMART_PTR (TextOverlay)
DECLARE_SMART_PTR() [73/153]
Castor3D::DECLARE_SMART_PTR (MeshAnimationInstance)
DECLARE_SMART_PTR() [74/153]
Castor3D::DECLARE_SMART_PTR (MeshAnimationSubmesh)
DECLARE_SMART_PTR() [75/153]
Castor3D::DECLARE_SMART_PTR (BillboardBase)
DECLARE_SMART_PTR() [76/153]
Castor3D::DECLARE_SMART_PTR (Animable)
DECLARE_SMART_PTR() [77/153]
Castor3D::DECLARE_SMART_PTR (BillboardList)
DECLARE_SMART_PTR() [78/153]
Castor3D::DECLARE_SMART_PTR (SceneNodeCache)
DECLARE_SMART_PTR() [79/153]
Castor3D::DECLARE_SMART_PTR (PluginCache)
DECLARE_SMART_PTR() [80/153]
Castor3D::DECLARE_SMART_PTR (LightCache)
DECLARE_SMART_PTR() [81/153]
Castor3D::DECLARE_SMART_PTR (EventHandler)
DECLARE_SMART_PTR() [82/153]
Castor3D::DECLARE_SMART_PTR (UserInputEvent)
DECLARE_SMART_PTR() [83/153]
Castor3D::DECLARE_SMART_PTR (KeyboardEvent)
DECLARE_SMART_PTR() [84/153]
Castor3D::DECLARE_SMART_PTR (MouseEvent)
DECLARE_SMART_PTR() [85/153]
Castor3D::DECLARE_SMART_PTR (HandlerEvent)
DECLARE_SMART_PTR() [86/153]
Castor3D::DECLARE_SMART_PTR (UserInputListener)
DECLARE_SMART_PTR() [87/153]
Castor3D::DECLARE_SMART_PTR (OverlayCache)
DECLARE_SMART_PTR() [88/153]
Castor3D::DECLARE_SMART_PTR (Uniform1b)
DECLARE_SMART_PTR() [89/153]
Castor3D::DECLARE_SMART_PTR (RenderBuffer)
DECLARE_SMART_PTR() [90/153]
Castor3D::DECLARE_SMART_PTR (ColourRenderBuffer)
DECLARE_SMART_PTR() [91/153]
Castor3D::DECLARE_SMART_PTR (DepthStencilRenderBuffer)
DECLARE_SMART_PTR() [92/153]
Castor3D::DECLARE_SMART_PTR (FrameBufferAttachment)
DECLARE_SMART_PTR() [93/153]
Castor3D::DECLARE_SMART_PTR (RenderBufferAttachment)
DECLARE_SMART_PTR() [94/153]
Castor3D::DECLARE_SMART_PTR (TextureAttachment)
DECLARE_SMART_PTR() [95/153]
Castor3D::DECLARE_SMART_PTR (FrameBuffer)
DECLARE_SMART_PTR() [96/153]
Castor3D::DECLARE_SMART_PTR (BackBuffers)
DECLARE_SMART_PTR() [97/153]
Castor3D::DECLARE_SMART_PTR (Engine)
DECLARE_SMART_PTR() [98/153]
Castor3D::DECLARE_SMART_PTR (Plugin)
DECLARE_SMART_PTR() [99/153]
Castor3D::DECLARE_SMART_PTR (RendererPlugin)
DECLARE_SMART_PTR() [100/153]
Castor3D::DECLARE_SMART_PTR (ImporterPlugin)
DECLARE_SMART_PTR() [101/153]
Castor3D::DECLARE_SMART_PTR (DividerPlugin)
DECLARE_SMART_PTR() [102/153]
Castor3D::DECLARE_SMART_PTR (GenericPlugin)
DECLARE_SMART_PTR() [103/153]
Castor3D::DECLARE_SMART_PTR (PostFxPlugin)
DECLARE_SMART_PTR() [104/153]
Castor3D::DECLARE_SMART_PTR (ParticlePlugin)
DECLARE_SMART_PTR() [105/153]
Castor3D::DECLARE_SMART_PTR (FrameEvent)
DECLARE_SMART_PTR() [106/153]
Castor3D::DECLARE_SMART_PTR (FrameListener)
DECLARE_SMART_PTR() [107/153]
Castor3D::DECLARE_SMART_PTR (IWindowHandle)
DECLARE_SMART_PTR() [108/153]
Castor3D::DECLARE_SMART_PTR (GpuQuery)
DECLARE_SMART_PTR() [109/153]
Castor3D::DECLARE_SMART_PTR (PickingPass)
DECLARE_SMART_PTR() [110/153]
Castor3D::DECLARE_SMART_PTR (TransformFeedback)
DECLARE_SMART_PTR() [111/153]
Castor3D::DECLARE_SMART_PTR (ComputePipeline)
DECLARE_SMART_PTR() [112/153]
Castor3D::DECLARE_SMART_PTR (TextureImage)
DECLARE_SMART_PTR() [113/153]
Castor3D::DECLARE_SMART_PTR (TextureLayout)
DECLARE_SMART_PTR() [114/153]
Castor3D::DECLARE_SMART_PTR (TextureStorage)
DECLARE_SMART_PTR() [115/153]
Castor3D::DECLARE_SMART_PTR (TextureUnit)
DECLARE_SMART_PTR() [116/153]
Castor3D::DECLARE_SMART_PTR (Material)
DECLARE_SMART_PTR() [117/153]
Castor3D::DECLARE_SMART_PTR (Pass)
DECLARE_SMART_PTR() [118/153]
Castor3D::DECLARE_SMART_PTR (LegacyPass)
DECLARE_SMART_PTR() [119/153]
Castor3D::DECLARE_SMART_PTR (Sampler)
DECLARE_SMART_PTR() [120/153]
Castor3D::DECLARE_SMART_PTR (ListenerCache)
DECLARE_SMART_PTR() [121/153]
Castor3D::DECLARE_SMART_PTR (ShaderProgramCache)
DECLARE_SMART_PTR() [122/153]
Castor3D::DECLARE_SMART_PTR (RenderTargetCache)
DECLARE_SMART_PTR() [123/153]
Castor3D::DECLARE_SMART_PTR (PushUniform1b)
DECLARE_SMART_PTR() [124/153]
Castor3D::DECLARE_SMART_PTR (BillboardListCache)
DECLARE_SMART_PTR() [125/153]
Castor3D::DECLARE_SMART_PTR (RenderSystem)
DECLARE_SMART_PTR() [126/153]
Castor3D::DECLARE_SMART_PTR (GeometryBuffers)
DECLARE_SMART_PTR() [127/153]
Castor3D::DECLARE_SMART_PTR (BufferElementDeclaration)
DECLARE_SMART_PTR() [128/153]
Castor3D::DECLARE_SMART_PTR (BufferDeclaration)
DECLARE_SMART_PTR() [129/153]
Castor3D::DECLARE_SMART_PTR (VertexBuffer)
DECLARE_SMART_PTR() [130/153]
Castor3D::DECLARE_SMART_PTR (IndexBuffer)
DECLARE_SMART_PTR() [131/153]
Castor3D::DECLARE_SMART_PTR (TextureBuffer)
DECLARE_SMART_PTR() [132/153]
Castor3D::DECLARE_SMART_PTR (Context)
DECLARE_SMART_PTR() [133/153]
Castor3D::DECLARE_SMART_PTR (DepthStencilState)
DECLARE_SMART_PTR() [134/153]
Castor3D::DECLARE_SMART_PTR (RasteriserState)
DECLARE_SMART_PTR() [135/153]
Castor3D::DECLARE_SMART_PTR (BlendState)
DECLARE_SMART_PTR() [136/153]
Castor3D::DECLARE_SMART_PTR (MultisampleState)
DECLARE_SMART_PTR() [137/153]
Castor3D::DECLARE_SMART_PTR (RenderPipeline)
DECLARE_SMART_PTR() [138/153]
Castor3D::DECLARE_SMART_PTR (ToneMapping)
DECLARE_SMART_PTR() [139/153]
Castor3D::DECLARE_SMART_PTR (PostEffect)
DECLARE_SMART_PTR() [140/153]
Castor3D::DECLARE_SMART_PTR (ShadowMapPass)
DECLARE_SMART_PTR() [141/153]
Castor3D::DECLARE_SMART_PTR (RenderTechnique)
DECLARE_SMART_PTR() [142/153]
Castor3D::DECLARE_SMART_PTR (RenderWindow)
DECLARE_SMART_PTR() [143/153]
Castor3D::DECLARE_SMART_PTR (RenderLoop)
DECLARE_SMART_PTR() [144/153]
Castor3D::DECLARE_SMART_PTR (RenderTarget)
DECLARE_SMART_PTR() [145/153]
Castor3D::DECLARE_SMART_PTR (ShadowMap)
DECLARE_SMART_PTR() [146/153]
Castor3D::DECLARE_SMART_PTR (UniformBuffer)
DECLARE_SMART_PTR() [147/153]
Castor3D::DECLARE_SMART_PTR (UniformBufferBinding)
DECLARE_SMART_PTR() [148/153]
Castor3D::DECLARE_SMART_PTR (Uniform)
DECLARE_SMART_PTR() [149/153]
Castor3D::DECLARE_SMART_PTR (PushUniform)
DECLARE_SMART_PTR() [150/153]
Castor3D::DECLARE_SMART_PTR (ShaderObject)
DECLARE_SMART_PTR() [151/153]
Castor3D::DECLARE_SMART_PTR (ShaderProgram)
DECLARE_SMART_PTR() [152/153]
Castor3D::DECLARE_SMART_PTR (ShaderStorageBuffer)
DECLARE_SMART_PTR() [153/153]
Castor3D::DECLARE_SMART_PTR (AtomicCounterBuffer)
DECLARE_VECTOR() [1/36]
Castor3D::DECLARE_VECTOR (CameraSPtr , CameraPtr)
Camera pointer array.
DECLARE_VECTOR() [2/36]
Castor3D::DECLARE_VECTOR (LightSPtr , LightPtr)
Array of lights.
DECLARE_VECTOR() [3/36]
Castor3D::DECLARE_VECTOR (StaticRenderNode , StaticRenderNode)
DECLARE_VECTOR() [4/36]
Castor3D::DECLARE_VECTOR (SkinningRenderNode , SkinningRenderNode)
DECLARE_VECTOR() [5/36]
Castor3D::DECLARE_VECTOR (MorphingRenderNode , MorphingRenderNode)
DECLARE_VECTOR() [6/36]
Castor3D::DECLARE_VECTOR (BillboardRenderNode , BillboardRenderNode)
DECLARE_VECTOR() [7/36]
Castor3D::DECLARE_VECTOR (Vertex , Vertex)
Vertex array.
DECLARE_VECTOR() [8/36]
Castor3D::DECLARE_VECTOR (BufferElementGroupSPtr , VertexPtr)
Vertex pointer array.
DECLARE_VECTOR() [9/36]
Castor3D::DECLARE_VECTOR (Face , Face)
Face array.
DECLARE_VECTOR() [10/36]
Castor3D::DECLARE_VECTOR (FaceSPtr , FacePtr)
Face pointer array.
DECLARE_VECTOR() [11/36]
Castor3D::DECLARE_VECTOR (FaceGroupSPtr , FaceGroupPtr)
FaceGroup pointer array.
DECLARE_VECTOR() [12/36]
Castor3D::DECLARE_VECTOR (SubmeshSPtr , SubmeshPtr)
Submesh pointer array.
DECLARE_VECTOR() [13/36]
Castor3D::DECLARE_VECTOR (GeometrySPtr , GeometryPtr)
Geometry pointer array.
DECLARE_VECTOR() [14/36]
Castor3D::DECLARE_VECTOR (BoneSPtr , BonePtr)
Bone pointer array.
DECLARE_VECTOR() [15/36]
Castor3D::DECLARE_VECTOR (BonedVertexSPtr , BonedVertexPtr)
BonedVertex pointer array.
DECLARE_VECTOR() [16/36]
Castor3D::DECLARE_VECTOR (OverlaySPtr , OverlayPtr)
DECLARE_VECTOR() [17/36]
Castor3D::DECLARE_VECTOR (SceneNodeSPtr , SceneNodePtr)
SceneNode pointer array.
DECLARE_VECTOR() [18/36]
Castor3D::DECLARE_VECTOR (SkeletonAnimationObjectSPtr , SkeletonAnimationObjectPtr)
SkeletonAnimationObject pointer array.
DECLARE_VECTOR() [19/36]
Castor3D::DECLARE_VECTOR (MeshAnimationSubmesh , MeshAnimationSubmesh)
SkeletonAnimationObject array.
DECLARE_VECTOR() [20/36]
Castor3D::DECLARE_VECTOR (SkeletonAnimationInstanceObjectSPtr , SkeletonAnimationInstanceObjectPtr)
SkeletonAnimationInstanceObject pointer array.
DECLARE_VECTOR() [21/36]
Castor3D::DECLARE_VECTOR (std::reference_wrapper< SkeletonAnimationInstance > , SkeletonAnimationInstance)
Skeleton animation instance pointer array.
DECLARE_VECTOR() [22/36]
Castor3D::DECLARE_VECTOR (MaterialSPtr , MaterialPtr)
Material pointer array.
DECLARE_VECTOR() [23/36]
Castor3D::DECLARE_VECTOR (TextureUnit , TextureUnit)
TextureUnit array.
DECLARE_VECTOR() [24/36]
Castor3D::DECLARE_VECTOR (TextureUnitSPtr , TextureUnitPtr)
TextureUnit pointer array.
DECLARE_VECTOR() [25/36]
Castor3D::DECLARE_VECTOR (Pass , Pass)
Pass array.
DECLARE_VECTOR() [26/36]
Castor3D::DECLARE_VECTOR (PassSPtr , PassPtr)
Pass pointer array.
DECLARE_VECTOR() [27/36]
Castor3D::DECLARE_VECTOR (uint32_t , UInt)
uint32_t array
DECLARE_VECTOR() [28/36]
Castor3D::DECLARE_VECTOR (std::reference_wrapper< TextureUnit > , DepthMap)
TextureUnit reference array.
DECLARE_VECTOR() [29/36]
Castor3D::DECLARE_VECTOR (real , Real)
real array
DECLARE_VECTOR() [30/36]
Castor3D::DECLARE_VECTOR (RenderWindowSPtr , RenderWindowPtr)
RenderWindow pointer array.
DECLARE_VECTOR() [31/36]
Castor3D::DECLARE_VECTOR (RenderBufferSPtr , RenderBufferPtr)
RenderBuffer pointer array.
DECLARE_VECTOR() [32/36]
Castor3D::DECLARE_VECTOR (FrameEventUPtr , FrameEventPtr)
FrameEvent pointer array.
DECLARE_VECTOR() [33/36]
Castor3D::DECLARE_VECTOR (PostEffectSPtr , PostEffectPtr)
DECLARE_VECTOR() [34/36]
Castor3D::DECLARE_VECTOR (BillboardListSPtr , BillboardList)
DECLARE_VECTOR() [35/36]
Castor3D::DECLARE_VECTOR (ShaderProgramSPtr , ShaderProgramPtr)
DECLARE_VECTOR() [36/36]
Castor3D::DECLARE_VECTOR (ShaderObjectSPtr , ShaderObjectPtr)
DoBindPass()
void Castor3D::DoBindPass (PassRenderNodeUniforms & p_node, Pass & p_pass, Scene const & p_scene, RenderPipeline & p_pipeline, DepthMapArray & p_depthMaps) inline
References Castor3D::Pass::BindTextures(), DoFillShaderDepthMaps(), Castor3D::RenderPipeline::GetFlags(), Castor3D::PassRenderNodeUniforms::m_passUbo, Castor3D::PipelineFlags::m_programFlags, Castor3D::UniformBuffer::Update(), and Castor3D::Pass::UpdateRenderNode().
DoBindPassOpacityMap()
void Castor3D::DoBindPassOpacityMap (PassRenderNodeUniforms & p_node, Pass & p_pass) inline
References Castor3D::Pass::GetTextureUnit(), and Castor3D::PassRenderNodeUniforms::m_textures.
DoFillShaderDepthMaps()
void Castor3D::DoFillShaderDepthMaps (RenderPipeline & p_pipeline, DepthMapArray & p_depthMaps) inline
References Castor3D::RenderPipeline::GetDirectionalShadowMapsVariable(), Castor3D::RenderPipeline::GetFlags(), Castor3D::RenderPipeline::GetPointShadowMapsVariable(), GetShadowType(), Castor3D::RenderPipeline::GetSpotShadowMapsVariable(), Castor3D::RenderPipeline::GetTexturesCount(), Castor3D::PipelineFlags::m_sceneFlags, and Castor3D::TPushUniform< Type >::SetValue().
Referenced by DoBindPass().
DoRenderNode()
template<typename NodeType > void Castor3D::DoRenderNode (NodeType & p_node) inline
References DoRenderNodeNoPass().
Referenced by Castor3D::DistanceRenderNode< NodeType >::Render().
DoRenderNodeNoPass() [1/4]
void Castor3D::DoRenderNodeNoPass (StaticRenderNode & p_node) inline
References DoRenderObjectNode().
DoRenderNodeNoPass() [2/4]
void Castor3D::DoRenderNodeNoPass (BillboardRenderNode & p_node) inline
References DoRenderObjectNode(), Castor3D::BillboardRenderNode::m_billboardUbo, Castor3D::ObjectRenderNode< DataTypeT, InstanceTypeT >::m_data, Castor3D::BillboardRenderNode::m_dimensions, Castor3D::TUniform< Type >::SetValue(), and Castor3D::UniformBuffer::Update().
DoRenderNodeNoPass() [3/4]
void Castor3D::DoRenderNodeNoPass (MorphingRenderNode & p_node) inline
References DoRenderObjectNode(), Castor3D::MeshAnimationInstanceSubmesh::FillShader(), Castor3D::MeshAnimationInstance::GetAnimationSubmesh(), Castor3D::AnimatedMesh::GetPlayingAnimation(), Castor3D::AnimatedMesh::IsPlayingAnimation(), Castor3D::ObjectRenderNode< DataTypeT, InstanceTypeT >::m_data, Castor3D::MorphingRenderNode::m_mesh, Castor3D::MorphingRenderNode::m_morphingUbo, Castor3D::MorphingRenderNode::m_time, Castor3D::TUniform< Type >::SetValue(), and Castor3D::UniformBuffer::Update().
DoRenderNodeNoPass() [4/4]
void Castor3D::DoRenderNodeNoPass (SkinningRenderNode & p_node) inline
References DoRenderObjectNode(), Castor3D::AnimatedSkeleton::FillShader(), Castor3D::SkinningRenderNode::m_bonesMatrix, Castor3D::SkinningRenderNode::m_skeleton, Castor3D::SkinningRenderNode::m_skinningUbo, and Castor3D::UniformBuffer::Update().
Referenced by DoRenderNode().
DoRenderObjectNode()
template<typename DataType , typename InstanceType > void Castor3D::DoRenderObjectNode (ObjectRenderNode< DataType, InstanceType > & p_node) inline
References Castor3D::ObjectRenderNode< DataTypeT, InstanceTypeT >::m_buffers, Castor3D::ObjectRenderNode< DataTypeT, InstanceTypeT >::m_data, Castor3D::ObjectRenderNode< DataTypeT, InstanceTypeT >::m_modelMatrix, Castor3D::ObjectRenderNode< DataTypeT, InstanceTypeT >::m_modelMatrixUbo, Castor3D::ObjectRenderNode< DataTypeT, InstanceTypeT >::m_normalMatrix, Castor3D::ObjectRenderNode< DataTypeT, InstanceTypeT >::m_pipeline, and Castor3D::ObjectRenderNode< DataTypeT, InstanceTypeT >::m_sceneNode.
Referenced by DoRenderNodeNoPass().
DoUnbindPass()
void Castor3D::DoUnbindPass (PassRenderNodeUniforms & p_node, Pass & p_pass, Scene const & p_scene, RenderPipeline & p_pipeline, DepthMapArray const & p_depthMaps) inline
References Castor3D::RenderPipeline::GetFlags(), Castor3D::PipelineFlags::m_programFlags, and Castor3D::Pass::UnbindTextures().
DoUnbindPassOpacityMap()
void Castor3D::DoUnbindPassOpacityMap (PassRenderNodeUniforms & p_node, Pass & p_pass) inline
References Castor3D::Pass::GetTextureUnit().
GetBuffer() [1/44]
static uint8_t const* Castor3D::GetBuffer (bool const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
Referenced by Castor3D::ChunkParser< T >::Parse(), and Castor3D::ChunkWriter< T >::Write().
GetBuffer() [2/44]
static uint8_t* Castor3D::GetBuffer (bool & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
GetBuffer() [3/44]
static uint8_t const* Castor3D::GetBuffer (int8_t const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
GetBuffer() [4/44]
static uint8_t* Castor3D::GetBuffer (int8_t & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
GetBuffer() [5/44]
static uint8_t const* Castor3D::GetBuffer (uint8_t const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
GetBuffer() [6/44]
static uint8_t* Castor3D::GetBuffer (uint8_t & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
GetBuffer() [7/44]
static uint8_t const* Castor3D::GetBuffer (int16_t const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
GetBuffer() [8/44]
static uint8_t* Castor3D::GetBuffer (int16_t & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
GetBuffer() [9/44]
static uint8_t const* Castor3D::GetBuffer (uint16_t const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
GetBuffer() [10/44]
static uint8_t* Castor3D::GetBuffer (uint16_t & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
GetBuffer() [11/44]
static uint8_t const* Castor3D::GetBuffer (int32_t const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
GetBuffer() [12/44]
static uint8_t* Castor3D::GetBuffer (int32_t & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
GetBuffer() [13/44]
static uint8_t const* Castor3D::GetBuffer (uint32_t const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
GetBuffer() [14/44]
static uint8_t* Castor3D::GetBuffer (uint32_t & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
GetBuffer() [15/44]
static uint8_t const* Castor3D::GetBuffer (int64_t const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
GetBuffer() [16/44]
static uint8_t* Castor3D::GetBuffer (int64_t & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
GetBuffer() [17/44]
static uint8_t const* Castor3D::GetBuffer (uint64_t const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
GetBuffer() [18/44]
static uint8_t* Castor3D::GetBuffer (uint64_t & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
GetBuffer() [19/44]
static uint8_t const* Castor3D::GetBuffer (float const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
GetBuffer() [20/44]
static uint8_t* Castor3D::GetBuffer (float & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
GetBuffer() [21/44]
static uint8_t const* Castor3D::GetBuffer (double const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
GetBuffer() [22/44]
static uint8_t* Castor3D::GetBuffer (double & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
GetBuffer() [23/44]
static uint8_t const* Castor3D::GetBuffer (long double const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
GetBuffer() [24/44]
static uint8_t* Castor3D::GetBuffer (long double & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
GetBuffer() [25/44]
template<typename T > static uint8_t const* Castor3D::GetBuffer (std::vector< T > const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
GetBuffer() [26/44]
template<typename T > static uint8_t* Castor3D::GetBuffer (std::vector< T > & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
GetBuffer() [27/44]
template<typename T , size_t Count> static uint8_t const* Castor3D::GetBuffer (std::array< T, Count > const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
GetBuffer() [28/44]
template<typename T , size_t Count> static uint8_t* Castor3D::GetBuffer (std::array< T, Count > & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer (&p_value for basic types).
GetBuffer() [29/44]
template<typename T , uint32_t Count> static uint8_t const* Castor3D::GetBuffer (Castor::Point< T, Count > const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
GetBuffer() [30/44]
template<typename T , uint32_t Count> static uint8_t* Castor3D::GetBuffer (Castor::Point< T, Count > & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
GetBuffer() [31/44]
template<typename T , uint32_t Count> static uint8_t const* Castor3D::GetBuffer (Castor::Coords< T, Count > const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
GetBuffer() [32/44]
template<typename T , uint32_t Count> static uint8_t* Castor3D::GetBuffer (Castor::Coords< T, Count > & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
GetBuffer() [33/44]
template<typename T , uint32_t Columns, uint32_t Rows> static uint8_t const* Castor3D::GetBuffer (Castor::Matrix< T, Columns, Rows > const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
GetBuffer() [34/44]
template<typename T , uint32_t Columns, uint32_t Rows> static uint8_t* Castor3D::GetBuffer (Castor::Matrix< T, Columns, Rows > & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
GetBuffer() [35/44]
template<typename T , uint32_t Count> static uint8_t const* Castor3D::GetBuffer (Castor::SquareMatrix< T, Count > const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
GetBuffer() [36/44]
template<typename T , uint32_t Count> static uint8_t* Castor3D::GetBuffer (Castor::SquareMatrix< T, Count > & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
GetBuffer() [37/44]
static uint8_t const* Castor3D::GetBuffer (Castor::Colour const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
GetBuffer() [38/44]
static uint8_t* Castor3D::GetBuffer (Castor::Colour & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
GetBuffer() [39/44]
static uint8_t const* Castor3D::GetBuffer (Castor::Size const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
GetBuffer() [40/44]
static uint8_t* Castor3D::GetBuffer (Castor::Size & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
GetBuffer() [41/44]
static uint8_t const* Castor3D::GetBuffer (Castor::Position const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
GetBuffer() [42/44]
static uint8_t* Castor3D::GetBuffer (Castor::Position & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
GetBuffer() [43/44]
template<typename T > static uint8_t const* Castor3D::GetBuffer (Castor::QuaternionT< T > const & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
GetBuffer() [44/44]
template<typename T > static uint8_t* Castor3D::GetBuffer (Castor::QuaternionT< T > & p_value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] p_value The value.
Returns
The buffer.
GetCPUCount()
int Castor3D::GetCPUCount ()
GetDataSize() [1/11]
template<typename T > static size_t Castor3D::GetDataSize (T const & p_value) inline static
Retrieves the value binary size.
Parameters
[in] p_value The value.
Returns
The size (sizeof(p_value) for basic types).
Referenced by Castor3D::ChunkParser< T >::Parse(), and Castor3D::ChunkWriter< T >::Write().
GetDataSize() [2/11]
template<typename T > static size_t Castor3D::GetDataSize (std::vector< T > const & p_value) inline static
Retrieves the value binary size.
Parameters
[in] p_value The value.
Returns
The size (sizeof(p_value) for basic types).
GetDataSize() [3/11]
template<typename T , size_t Count> static size_t Castor3D::GetDataSize (std::array< T, Count > const & p_value) inline static
Retrieves the value binary size.
Parameters
[in] p_value The value.
Returns
The size (sizeof(p_value) for basic types).
GetDataSize() [4/11]
template<typename T , uint32_t Count> static size_t Castor3D::GetDataSize (Castor::Point< T, Count > const & p_value) inline static
Retrieves the value binary size.
Parameters
[in] p_value The value.
Returns
The size (sizeof(p_value) for basic types).
GetDataSize() [5/11]
template<typename T , uint32_t Count> static size_t Castor3D::GetDataSize (Castor::Coords< T, Count > const & p_value) inline static
Retrieves the value binary size.
Parameters
[in] p_value The value.
Returns
The size (sizeof(p_value) for basic types).
GetDataSize() [6/11]
template<typename T , uint32_t Columns, uint32_t Rows> static size_t Castor3D::GetDataSize (Castor::Matrix< T, Columns, Rows > const & p_value) inline static
Retrieves the value binary size.
Parameters
[in] p_value The value.
Returns
The size (sizeof(p_value) for basic types).
GetDataSize() [7/11]
template<typename T , uint32_t Count> static size_t Castor3D::GetDataSize (Castor::SquareMatrix< T, Count > const & p_value) inline static
Retrieves the value binary size.
Parameters
[in] p_value The value.
Returns
The size (sizeof(p_value) for basic types).
GetDataSize() [8/11]
static size_t Castor3D::GetDataSize (Castor::Colour const & p_value) inline static
Retrieves the value binary size.
Parameters
[in] p_value The value.
Returns
The size (sizeof(p_value) for basic types).
GetDataSize() [9/11]
static size_t Castor3D::GetDataSize (Castor::Size const & p_value) inline static
Retrieves the value binary size.
Parameters
[in] p_value The value.
Returns
The size (sizeof(p_value) for basic types).
GetDataSize() [10/11]
static size_t Castor3D::GetDataSize (Castor::Position const & p_value) inline static
Retrieves the value binary size.
Parameters
[in] p_value The value.
Returns
The size (sizeof(p_value) for basic types).
GetDataSize() [11/11]
template<typename T > static size_t Castor3D::GetDataSize (Castor::QuaternionT< T > const & p_value) inline static
Retrieves the value binary size.
Parameters
[in] p_value The value.
Returns
The size (sizeof(p_value) for basic types).
GetFogType()
C3D_API GLSL::FogType Castor3D::GetFogType (SceneFlags const & p_flags)
Gives the fog type matching the given flags.
Parameters
[in] p_flags The scene flags.
Returns
The fog type.
GetName()
C3D_API Castor::String Castor3D::GetName (ElementType p_type)
Gets the name of the given element type.
Parameters
[in] p_type The element type.
Returns
The name.
GetShadowType()
C3D_API GLSL::ShadowType Castor3D::GetShadowType (SceneFlags const & p_flags)
Gives the shadow filter type matching the given flags.
Parameters
[in] p_flags The scene flags.
Returns
The shadow filter type.
Referenced by DoFillShaderDepthMaps().
GetSize()
uint32_t Castor3D::GetSize (ElementType p_type) inline
Gets the byte size of the given element type.
Parameters
[in] p_type The element type.
Returns
The size.
References eColour, eFloat, eInt, eIVec2, eIVec3, eIVec4, eMat2, eMat3, eMat4, eUInt, eUIVec2, eUIVec3, eUIVec4, eVec2, eVec3, and eVec4.
Referenced by Castor3D::BufferDeclaration::push_back().
GetTopologyName()
static Castor::String const Castor3D::GetTopologyName (Topology p_topology) inline static
Gets the name of the given topology.
Parameters
[in] p_topology The topology.
Returns
The name.
References eLineLoop, eLines, eLineStrip, ePoints, ePolygon, eQuads, eQuadStrips, eTriangleFan, eTriangles, and eTriangleStrips.
IsShadowMapProgram()
bool Castor3D::IsShadowMapProgram (ProgramFlags const & p_flags)
Tells if the given flags contain a shadow map flag.
Parameters
[in] p_flags The flags to check.
Returns
true if p_flags contain one of ProgramFlag::eShadowMapDirectional, ProgramFlag::eShadowMapSpot, or ProgramFlag::eShadowMapPoint.
MakeCache() [1/2]
std::unique_ptr< ShaderProgramCache > Castor3D::MakeCache (Engine & p_engine) inline
Creates a ShaderProgram cache.
Parameters
[in] p_engine The engine.
MakeCache() [2/2]
template<typename ElementType , typename KeyType > std::unique_ptr< Cache< ElementType, KeyType > > Castor3D::MakeCache (Engine & p_engine, typename CacheTraits< ElementType, KeyType >::Producer && p_produce, ElementInitialiser< ElementType > && p_initialise = [](std::shared_ptr< ElementType >){}, ElementCleaner< ElementType > && p_clean = [](std::shared_ptr< ElementType >){}, typename CacheTraits< ElementType, KeyType >::Merger && p_merge = [](CacheBase< ElementType, KeyType > const & , Castor::Collection< ElementType, KeyType > & , std::shared_ptr< ElementType >){}) inline
Creates a cache.
Parameters
[in] p_engine The engine.
[in] p_produce The element producer.
[in] p_initialise The element initialiser.
[in] p_clean The element cleaner.
[in] p_merge The element collection merger.
MakeCleanupEvent()
template<typename T > std::unique_ptr< CleanupEvent< T > > Castor3D::MakeCleanupEvent (T & p_object)
Helper function to create a cleanup event.
Parameters
[in] p_object The object to cleanup
MakeFunctorEvent()
template<typename Functor > std::unique_ptr< FunctorEvent< Functor > > Castor3D::MakeFunctorEvent (EventType p_type, Functor p_functor) inline
Helper function to create a functor event.
Parameters
[in] p_type The event type
[in] p_functor The functor to execute
MakeInitialiseEvent()
template<typename T > std::unique_ptr< InitialiseEvent< T > > Castor3D::MakeInitialiseEvent (T & p_object)
Helper function to create an initialise event.
Parameters
[in] p_object The object to initialise
MakeObjectCache()
template<typename ElementType , typename KeyType > std::unique_ptr< ObjectCache< ElementType, KeyType > > Castor3D::MakeObjectCache (Engine & p_engine, Scene & p_scene, SceneNodeSPtr p_rootNode, SceneNodeSPtr p_rootCameraNode, SceneNodeSPtr p_rootObjectNode, typename ObjectCacheTraits< ElementType, KeyType >::Producer && p_produce, ElementInitialiser< ElementType > && p_initialise = [](std::shared_ptr< ElementType >){}, ElementCleaner< ElementType > && p_clean = [](std::shared_ptr< ElementType >){}, typename ObjectCacheTraits< ElementType, KeyType >::Merger && p_merge = [](ObjectCacheBase< ElementType, KeyType > const & , Castor::Collection< ElementType, KeyType > & , std::shared_ptr< ElementType > , SceneNodeSPtr , SceneNodeSPtr){}, ElementAttacher< ElementType > && p_attach = [](std::shared_ptr< ElementType >, SceneNodeSPtr, SceneNodeSPtr, SceneNodeSPtr, SceneNodeSPtr){}, ElementDetacher< ElementType > && p_detach = [](std::shared_ptr< ElementType >){}) inline
Creates an object cache.
Parameters
[in] p_engine The engine.
[in] p_scene The scene.
[in] p_rootNode The scene root node.
[in] p_rootCameraNode The root node for cameras.
[in] p_rootObjectNode The root node for objects.
[in] p_produce The element producer.
[in] p_initialise The element initialiser.
[in] p_clean The element cleaner.
[in] p_merge The element collection merger.
[in] p_attach The element attacher (to a scene node).
[in] p_detach The element detacher (from a scene node).
operator!=() [1/4]
bool Castor3D::operator!= (BufferElementDeclaration const & p_lhs, BufferElementDeclaration const & p_rhs) inline
Equality operator.
Parameters
[in] p_lhs,p_rhs The 2 objects to compare.
References Castor3D::BufferElementDeclaration::m_dataType, Castor3D::BufferElementDeclaration::m_divisor, Castor3D::BufferElementDeclaration::m_name, Castor3D::BufferElementDeclaration::m_offset, and Castor3D::BufferElementDeclaration::m_usages.
operator!=() [2/4]
C3D_API bool Castor3D::operator!= (Castor3D::Version const & p_a, Castor3D::Version const & p_b)
Difference operator.
Parameters
[in] p_a,p_b The versions to compare.
Returns
true if one version number is different from p_a to p_b.
operator!=() [3/4]
C3D_API bool Castor3D::operator!= (ProgramInputLayout const & p_lhs, ProgramInputLayout const & p_rhs)
Equality operator.
Parameters
[in] p_lhs,p_rhs The 2 objects to compare.
operator!=() [4/4]
C3D_API bool Castor3D::operator!= (BufferDeclaration & p_lhs, BufferDeclaration & p_rhs)
Equality operator.
Parameters
[in] p_lhs,p_rhs The 2 objects to compare.
operator<() [1/2]
bool Castor3D::operator< (PipelineFlags const & p_lhs, PipelineFlags const & p_rhs) inline
References Castor3D::PipelineFlags::m_alphaBlendMode, Castor3D::PipelineFlags::m_colourBlendMode, Castor3D::PipelineFlags::m_programFlags, Castor3D::PipelineFlags::m_sceneFlags, and Castor3D::PipelineFlags::m_textureFlags.
operator<() [2/2]
C3D_API bool Castor3D::operator< (Castor3D::Version const & p_a, Castor3D::Version const & p_b)
Less than operator.
Parameters
[in] p_a,p_b The versions to compare.
Returns
true if p_a.major is less than p_b.major or if they are equal and p_a.minor is less than p_b.minor or if majors and minors are equal and p_a.build is less than p_b.build.
operator<<() [1/12]
std::ostream& Castor3D::operator<< (std::ostream & o, Sphere const & c) inline
Stream operator.
operator<<() [2/12]
std::ostream& Castor3D::operator<< (std::ostream & o, Icosahedron const & c) inline
Stream operator.
operator<<() [3/12]
std::ostream& Castor3D::operator<< (std::ostream & o, Projection const & c) inline
Stream operator.
operator<<() [4/12]
std::ostream& Castor3D::operator<< (std::ostream & o, Cylinder const & c) inline
Stream operator.
operator<<() [5/12]
std::ostream& Castor3D::operator<< (std::ostream & o, Cube const & c) inline
Stream operator.
operator<<() [6/12]
std::ostream& Castor3D::operator<< (std::ostream & o, Cone const & c) inline
Stream operator.
operator<<() [7/12]
std::ostream& Castor3D::operator<< (std::ostream & o, Plane const & c) inline
Stream operator.
operator<<() [8/12]
std::ostream& Castor3D::operator<< (std::ostream & o, Torus const & c) inline
Stream operator.
operator<<() [9/12]
C3D_API std::ostream& Castor3D::operator<< (std::ostream & p_stream, Castor3D::Version const & p_version)
operator<<() [10/12]
C3D_API std::wostream& Castor3D::operator<< (std::wostream & p_stream, Castor3D::Version const & p_version)
operator<<() [11/12]
C3D_API Castor::String& Castor3D::operator<< (Castor::String & p_stream, Castor3D::Version const & p_version)
operator<<() [12/12]
std::ostream& Castor3D::operator<< (std::ostream & p_streamOut, TextureUnitSPtr const & p_texture) inline
Stream operator.
Parameters
[in,out] p_streamOut The stream receiving texture's data
[in] p_texture The input texture
Returns
A reference to the stream
operator<=()
C3D_API bool Castor3D::operator<= (Castor3D::Version const & p_a, Castor3D::Version const & p_b)
Less than operator.
Parameters
[in] p_a,p_b The versions to compare.
Returns
false if p_a.major is greater than p_b.major or if they are equal and p_a.minor is greater than p_b.minor or if majors and minors are equal and p_a.build is greater than p_b.build.
operator==() [1/4]
bool Castor3D::operator== (BufferElementDeclaration const & p_lhs, BufferElementDeclaration const & p_rhs) inline
Equality operator.
Parameters
[in] p_lhs,p_rhs The 2 objects to compare.
References Castor3D::BufferElementDeclaration::m_dataType, Castor3D::BufferElementDeclaration::m_divisor, Castor3D::BufferElementDeclaration::m_name, Castor3D::BufferElementDeclaration::m_offset, and Castor3D::BufferElementDeclaration::m_usages.
operator==() [2/4]
C3D_API bool Castor3D::operator== (Castor3D::Version const & p_a, Castor3D::Version const & p_b)
Equality operator.
Parameters
[in] p_a,p_b The versions to compare.
Returns
false if one version number is different from p_a to p_b.
operator==() [3/4]
C3D_API bool Castor3D::operator== (ProgramInputLayout const & p_lhs, ProgramInputLayout const & p_rhs)
Equality operator.
Parameters
[in] p_lhs,p_rhs The 2 objects to compare.
operator==() [4/4]
C3D_API bool Castor3D::operator== (BufferDeclaration & p_lhs, BufferDeclaration & p_rhs)
Equality operator.
Parameters
[in] p_lhs,p_rhs The 2 objects to compare.
operator>()
C3D_API bool Castor3D::operator> (Castor3D::Version const & p_a, Castor3D::Version const & p_b)
Less than operator.
Parameters
[in] p_a,p_b The versions to compare.
Returns
true if p_a.major is greater than p_b.major or if they are equal and p_a.minor is greater than p_b.minor or if majors and minors are equal and p_a.build is greater than p_b.build.
operator>=()
C3D_API bool Castor3D::operator>= (Castor3D::Version const & p_a, Castor3D::Version const & p_b)
Less than operator.
Parameters
[in] p_a,p_b The versions to compare.
Returns
false if p_a.major is less than p_b.major or if they are equal and p_a.minor is less than p_b.minor or if majors and minors are equal and p_a.build is less than p_b.build.
PrepareChunkData() [1/26]
static void Castor3D::PrepareChunkData (ChunkType & p_value) inline static
Sets given value to big endian.
Parameters
[in,out] p_value The value.
Referenced by Castor3D::ChunkParser< T >::Parse(), PrepareChunkData(), and Castor3D::ChunkWriter< T >::Write().
PrepareChunkData() [2/26]
static void Castor3D::PrepareChunkData (bool & p_value) inline static
Sets given value to big endian.
Parameters
[in,out] p_value The value.
PrepareChunkData() [3/26]
static void Castor3D::PrepareChunkData (int8_t & p_value) inline static
Sets given value to big endian.
Parameters
[in,out] p_value The value.
PrepareChunkData() [4/26]
static void Castor3D::PrepareChunkData (uint8_t & p_value) inline static
Sets given value to big endian.
Parameters
[in,out] p_value The value.
PrepareChunkData() [5/26]
static void Castor3D::PrepareChunkData (int16_t & p_value) inline static
Sets given value to big endian.
Parameters
[in,out] p_value The value.
PrepareChunkData() [6/26]
static void Castor3D::PrepareChunkData (uint16_t & p_value) inline static
Sets given value to big endian.
Parameters
[in,out] p_value The value.
PrepareChunkData() [7/26]
static void Castor3D::PrepareChunkData (int32_t & p_value) inline static
Sets given value to big endian.
Parameters
[in,out] p_value The value.
PrepareChunkData() [8/26]
static void Castor3D::PrepareChunkData (uint32_t & p_value) inline static
Sets given value to big endian.
Parameters
[in,out] p_value The value.
PrepareChunkData() [9/26]
static void Castor3D::PrepareChunkData (int64_t & p_value) inline static
Sets given value to big endian.
Parameters
[in,out] p_value The value.
PrepareChunkData() [10/26]
static void Castor3D::PrepareChunkData (uint64_t & p_value) inline static
Sets given value to big endian.
Parameters
[in,out] p_value The value.
PrepareChunkData() [11/26]
static void Castor3D::PrepareChunkData (float & p_value) inline static
Sets given value to big endian.
Parameters
[in,out] p_value The value.
PrepareChunkData() [12/26]
static void Castor3D::PrepareChunkData (double & p_value) inline static
Sets given value to big endian.
Parameters
[in,out] p_value The value.
PrepareChunkData() [13/26]
static void Castor3D::PrepareChunkData (long double & p_value) inline static
Sets given value to big endian.
Parameters
[in,out] p_value The value.
PrepareChunkData() [14/26]
template<typename T > static void Castor3D::PrepareChunkData (std::vector< T > & p_value) inline static
Sets given value to big endian.
Parameters
[in,out] p_value The value.
PrepareChunkData() [15/26]
template<typename T , size_t Count> static void Castor3D::PrepareChunkData (std::array< T, Count > & p_value) inline static
Sets given value to big endian.
Parameters
[in,out] p_value The value.
PrepareChunkData() [16/26]
template<typename T , uint32_t Count> static void Castor3D::PrepareChunkData (Castor::SquareMatrix< T, Count > & p_value) inline static
Sets given value to big endian.
Parameters
[in,out] p_value The value.
PrepareChunkData() [17/26]
template<typename T , uint32_t Count> static void Castor3D::PrepareChunkData (Castor::Point< T, Count > & p_value) inline static
Sets given value to big endian.
Parameters
[in,out] p_value The value.
PrepareChunkData() [18/26]
template<typename T , uint32_t Count> static void Castor3D::PrepareChunkData (Castor::Coords< T, Count > & p_value) inline static
Sets given value to big endian.
Parameters
[in,out] p_value The value.
PrepareChunkData() [19/26]
template<typename T > static void Castor3D::PrepareChunkData (Castor::QuaternionT< T > & p_value) inline static
Sets given value to big endian.
Parameters
[in,out] p_value The value.
PrepareChunkData() [20/26]
static void Castor3D::PrepareChunkData (Castor::ColourComponent & p_value) inline static
Sets given value to big endian.
Parameters
[in,out] p_value The value.
PrepareChunkData() [21/26]
static void Castor3D::PrepareChunkData (Castor::Colour & p_value) inline static
Sets given value to big endian.
Parameters
[in,out] p_value The value.
PrepareChunkData() [22/26]
template<typename T > static void Castor3D::PrepareChunkData (InterleavedVertexT< T > & p_value) inline static
Sets given value to big endian.
Parameters
[in,out] p_value The value.
References Castor3D::InterleavedVertexT< T >::m_bin, Castor3D::InterleavedVertexT< T >::m_nml, Castor3D::InterleavedVertexT< T >::m_pos, Castor3D::InterleavedVertexT< T >::m_tan, and Castor3D::InterleavedVertexT< T >::m_tex.
PrepareChunkData() [23/26]
template<typename T > static void Castor3D::PrepareChunkData (SubmeshAnimationBufferT< T > & p_value) inline static
Sets given value to big endian.
Parameters
[in,out] p_value The value.
References Castor3D::SubmeshAnimationBufferT< T >::m_buffer, Castor3D::SubmeshAnimationBufferT< T >::m_timeIndex, and PrepareChunkData().
PrepareChunkData() [24/26]
static void Castor3D::PrepareChunkData (FaceIndices & p_value) inline static
Sets given value to big endian.
Parameters
[in,out] p_value The value.
References Castor3D::FaceIndices::m_index.
PrepareChunkData() [25/26]
static void Castor3D::PrepareChunkData (VertexBoneData & p_value) inline static
Sets given value to big endian.
Parameters
[in,out] p_value The value.
References Castor3D::VertexBoneData::m_ids, and Castor3D::VertexBoneData::m_weights.
PrepareChunkData() [26/26]
static void Castor3D::PrepareChunkData (KeyFrame & p_value) inline static
Sets given value to big endian.
Parameters
[in,out] p_value The value.
References Castor3D::KeyFrame::GetTimeIndex(), and Castor3D::KeyFrame::GetTransform().
Variable Documentation
C3D_MAX_BONES_PER_VERTEX
const uint32_t Castor3D::C3D_MAX_BONES_PER_VERTEX = 8 static
C3D_MAX_TEXTURE_MATRICES
const uint32_t Castor3D::C3D_MAX_TEXTURE_MATRICES = 4 static
Referenced by Castor3D::RenderPipeline::GetTextureMatrix(), and Castor3D::RenderPipeline::SetTextureMatrix().
CMSH_VERSION
uint32_t const Castor3D::CMSH_VERSION = MAKE_CMSH_VERSION(0x01, 0x01, 0x0000)
The current format version number.
Referenced by Castor3D::BinaryWriterBase< Skeleton >::DoWriteHeader().
INFO_CACHE_CREATED_OBJECT
const xchar* Castor3D::INFO_CACHE_CREATED_OBJECT = cuT("Cache::Create - Created ") static
Referenced by Castor3D::ObjectCache< SceneNode, Castor::String >::Add(), Castor3D::CacheBase< Plugin, Castor::String >::Add(), and Castor3D::ObjectCacheBase< SceneNode, Castor::String >::Add().
MASK_MTXMODE_MODEL
const uint64_t Castor3D::MASK_MTXMODE_MODEL = uint64_t(0x1) << int(MatrixMode::eModel) static
MASK_MTXMODE_PROJECTION
const uint64_t Castor3D::MASK_MTXMODE_PROJECTION = uint64_t(0x1) << int(MatrixMode::eProjection) static
Matrix modes masks.
Author
Sylvain DOREMUS
MASK_MTXMODE_TEXTURE0
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE0 = uint64_t(0x1) << int(MatrixMode::eTexture0) static
MASK_MTXMODE_TEXTURE1
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE1 = uint64_t(0x1) << int(MatrixMode::eTexture1) static
MASK_MTXMODE_TEXTURE10
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE10 = uint64_t(0x1) << int(MatrixMode::eTexture10) static
MASK_MTXMODE_TEXTURE11
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE11 = uint64_t(0x1) << int(MatrixMode::eTexture11) static
MASK_MTXMODE_TEXTURE12
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE12 = uint64_t(0x1) << int(MatrixMode::eTexture12) static
MASK_MTXMODE_TEXTURE13
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE13 = uint64_t(0x1) << int(MatrixMode::eTexture13) static
MASK_MTXMODE_TEXTURE14
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE14 = uint64_t(0x1) << int(MatrixMode::eTexture14) static
MASK_MTXMODE_TEXTURE15
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE15 = uint64_t(0x1) << int(MatrixMode::eTexture15) static
MASK_MTXMODE_TEXTURE2
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE2 = uint64_t(0x1) << int(MatrixMode::eTexture2) static
MASK_MTXMODE_TEXTURE3
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE3 = uint64_t(0x1) << int(MatrixMode::eTexture3) static
MASK_MTXMODE_TEXTURE4
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE4 = uint64_t(0x1) << int(MatrixMode::eTexture4) static
MASK_MTXMODE_TEXTURE5
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE5 = uint64_t(0x1) << int(MatrixMode::eTexture5) static
MASK_MTXMODE_TEXTURE6
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE6 = uint64_t(0x1) << int(MatrixMode::eTexture6) static
MASK_MTXMODE_TEXTURE7
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE7 = uint64_t(0x1) << int(MatrixMode::eTexture7) static
MASK_MTXMODE_TEXTURE8
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE8 = uint64_t(0x1) << int(MatrixMode::eTexture8) static
MASK_MTXMODE_TEXTURE9
const uint64_t Castor3D::MASK_MTXMODE_TEXTURE9 = uint64_t(0x1) << int(MatrixMode::eTexture9) static
MASK_MTXMODE_VIEW
const uint64_t Castor3D::MASK_MTXMODE_VIEW = uint64_t(0x1) << int(MatrixMode::eView) static
RENDERER_TYPE_UNDEFINED
Castor::String const Castor3D::RENDERER_TYPE_UNDEFINED = cuT("Undefined")
WARNING_CACHE_DUPLICATE_OBJECT
const xchar* Castor3D::WARNING_CACHE_DUPLICATE_OBJECT = cuT("Cache::Create - Duplicate ") static
Referenced by Castor3D::ObjectCache< SceneNode, Castor::String >::Add(), Castor3D::CacheBase< Plugin, Castor::String >::Add(), and Castor3D::ObjectCacheBase< SceneNode, Castor::String >::Add().
WARNING_CACHE_NULL_OBJECT
const xchar* Castor3D::WARNING_CACHE_NULL_OBJECT = cuT("Cache::Insert - nullptr ") static
Referenced by Castor3D::CacheBase< Plugin, Castor::String >::Add(), and Castor3D::ObjectCacheBase< SceneNode, Castor::String >::Add().