Castor3D: castor3d::Extensions Struct Reference
castor3d::Extensions Struct Reference
#include <RenderDevice.hpp>
Public Member Functions
C3D_API void addExtension (castor::MbString const &extName)
Adds an extension.
C3D_API void addExtension (castor::MbString const &extName, VkStructure *featureStruct, VkStructure *propertyStruct=nullptr)
Adds an extension, and it's optional feature structure, that will be queried on physical device.
template<typename StructT >
void addFeature (castor::MbString const &extName, StructT *featureStruct)
Adds a feature structure, that will be queried on physical device.
template<typename StructT >
void addFeature (StructT *featureStruct)
Adds a feature structure, that will be queried on physical device.
template<typename StructT >
void addProperty (castor::MbString const &extName, StructT *propStruct)
Adds a feature structure, that will be queried on physical device.
template<typename StructT >
void addProperty (StructT *propStruct)
Adds a feature structure, that will be queried on physical device.
ashes::StringArray const & getExtensionsNames () const noexcept
FeatureArray & getFeatures () noexcept
FeatureArray const & getFeatures () const noexcept
PropertyArray & getProperties () noexcept
PropertyArray const & getProperties () const noexcept
Member Function Documentation
addExtension() [1/2]
C3D_API void castor3d::Extensions::addExtension (castor::MbString const & extName)
Adds an extension.
addExtension() [2/2]
C3D_API void castor3d::Extensions::addExtension (castor::MbString const & extName, VkStructure * featureStruct, VkStructure * propertyStruct = nullptr)
Adds an extension, and it's optional feature structure, that will be queried on physical device.
addFeature() [1/2]
template<typename StructT > void castor3d::Extensions::addFeature (castor::MbString const & extName, StructT * featureStruct) inline
Adds a feature structure, that will be queried on physical device.
Referenced by addFeature().
addFeature() [2/2]
template<typename StructT > void castor3d::Extensions::addFeature (StructT * featureStruct) inline
Adds a feature structure, that will be queried on physical device.
References addFeature().
addProperty() [1/2]
template<typename StructT > void castor3d::Extensions::addProperty (castor::MbString const & extName, StructT * propStruct) inline
Adds a feature structure, that will be queried on physical device.
Referenced by addProperty().
addProperty() [2/2]
template<typename StructT > void castor3d::Extensions::addProperty (StructT * propStruct) inline
Adds a feature structure, that will be queried on physical device.
References addProperty().
getExtensionsNames()
ashes::StringArray const & castor3d::Extensions::getExtensionsNames () const inline noexcept
getFeatures() [1/2]
FeatureArray const & castor3d::Extensions::getFeatures () const inline noexcept
getFeatures() [2/2]
FeatureArray & castor3d::Extensions::getFeatures () inline noexcept
getProperties() [1/2]
PropertyArray const & castor3d::Extensions::getProperties () const inline noexcept
getProperties() [2/2]
PropertyArray & castor3d::Extensions::getProperties () inline noexcept
The documentation for this struct was generated from the following file:
Castor3D/Render/RenderDevice.hpp