Castor3D: castor3d::RenderSystem Class Reference
castor3d::RenderSystem Class Reference
#include <RenderSystem.hpp>
Public Member Functions
C3D_API RenderSystem (Engine &engine, AshPluginDescription desc, Extensions instanceExtensions={}, Extensions deviceExtensions={})
C3D_API RenderSystem (Engine &engine, Renderer renderer, Extensions deviceExtensions={})
C3D_API SpirVShader compileShader (VkShaderStageFlagBits stage, castor::String const &name, ast::Shader const &shader, ast::EntryPointConfig const &entryPoint)
C3D_API SpirVShader compileShader (VkShaderStageFlagBits stage, castor::String const &name, castor::MbString const &glsl) const
C3D_API SpirVShader const & compileShader (ShaderModule &shaderModule)
C3D_API SpirVShader const & compileShader (ProgramModule &shaderModule, ast::EntryPointConfig const &entryPoint)
C3D_API castor::Matrix4x4f getFrustum (float left, float right, float bottom, float top, float zNear, float zFar) const
C3D_API castor::Matrix4x4f getPerspective (castor::Angle const &fovy, float aspect, float zNear, float zFar) const
C3D_API castor::Matrix4x4f getOrtho (float left, float right, float bottom, float top, float zNear, float zFar) const
C3D_API castor::Matrix4x4f getInfinitePerspective (castor::Angle const &fovy, float aspect, float zNear) const
Getters.
C3D_API Texture const & getPrefilteredBrdfTexture () const
AshPluginDescription const & getDescription () const noexcept
GpuInformations const & getGpuInformations () const noexcept
castor::String getRendererType () const noexcept
bool hasDevice () const noexcept
RenderDevice & getRenderDevice () const noexcept
bool hasSsbo () const noexcept
ashes::Instance const & getInstance () const noexcept
VkPhysicalDeviceProperties const & getProperties () const noexcept
VkPhysicalDeviceMemoryProperties const & getMemoryProperties () const noexcept
VkPhysicalDeviceFeatures const & getFeatures () const noexcept
ashes::PhysicalDevice const & getPhysicalDevice () const noexcept
bool hasFeature (GpuFeature feature) const noexcept
bool hasStereoRendering () const noexcept
bool hasShaderStorageBuffers () const noexcept
bool hasShaderType (VkShaderStageFlagBits type) const noexcept
uint32_t getValue (GpuMin index) const noexcept
uint32_t getValue (GpuMax index) const noexcept
bool hasLLPV () const noexcept
ashes::Buffer< castor::Point4f > const & getRandomStorage () const noexcept
Public Member Functions inherited from castor::OwnedBy< Engine >
Engine * getOwner () const
Static Public Member Functions
static C3D_API ashes::InstancePtr createInstance (Engine const &engine, AshPluginDescription const &desc, Extensions &instanceExtensions)
static C3D_API void completeLayerNames (Engine const &engine, ashes::VkLayerPropertiesArray const &layers, ashes::StringArray &names)
Additional Inherited Members
Protected Member Functions inherited from castor::OwnedBy< Engine >
OwnedBy (Engine &owner)
Constructor.
Constructor & Destructor Documentation
RenderSystem() [1/2]
C3D_API castor3d::RenderSystem::RenderSystem (Engine & engine, AshPluginDescription desc, Extensions instanceExtensions = {}, Extensions deviceExtensions = {})
Constructor.
Parameters
[in] engine The engine.
[in] desc The Ashes plugin description.
[in] instanceExtensions The instance extensions.
[in] deviceExtensions The device extensions.
RenderSystem() [2/2]
C3D_API castor3d::RenderSystem::RenderSystem (Engine & engine, Renderer renderer, Extensions deviceExtensions = {})
Constructor.
Parameters
[in] engine The engine.
[in] renderer The selected renderer.
[in] deviceExtensions The device extensions.
Member Function Documentation
compileShader() [1/4]
C3D_API SpirVShader const & castor3d::RenderSystem::compileShader (ProgramModule & shaderModule, ast::EntryPointConfig const & entryPoint)
Compiles a shader module to the necessary shader language.
Parameters
[in] shaderModule The shader to compile.
[in] entryPoint The shader entry point to compile.
Returns
The compiled shader.
compileShader() [2/4]
C3D_API SpirVShader const & castor3d::RenderSystem::compileShader (ShaderModule & shaderModule)
Compiles a shader module to the necessary shader language.
Parameters
[in] shaderModule The shader to compile.
Returns
The compiled shader.
compileShader() [3/4]
C3D_API SpirVShader castor3d::RenderSystem::compileShader (VkShaderStageFlagBits stage, castor::String const & name, ast::Shader const & shader, ast::EntryPointConfig const & entryPoint)
Compiles a shader module to the necessary shader language.
Parameters
[in] stage The shader stage.
[in] name The shader name.
[in] shader The shader to compile.
[in] entryPoint The shader entry point to compile.
Returns
The compiled shader.
compileShader() [4/4]
C3D_API SpirVShader castor3d::RenderSystem::compileShader (VkShaderStageFlagBits stage, castor::String const & name, castor::MbString const & glsl) const
Compiles a shader module to the necessary shader language.
Parameters
[in] stage The shader stage.
[in] name The shader name.
[in] glsl The shader to compile.
Returns
The compiled shader.
completeLayerNames()
static C3D_API void castor3d::RenderSystem::completeLayerNames (Engine const & engine, ashes::VkLayerPropertiesArray const & layers, ashes::StringArray & names) static
Adds the instance layers names to the given names.
Parameters
[in] engine The engine.
[in] layers The available layers.
[in,out] names The liste to fill.
createInstance()
static C3D_API ashes::InstancePtr castor3d::RenderSystem::createInstance (Engine const & engine, AshPluginDescription const & desc, Extensions & instanceExtensions) static
Creates a Vulkan instance usable with Castor3D.
Parameters
[in] engine The engine.
[in] desc The Ashes plugin description.
[in] instanceExtensions The instance extensions.
getDescription()
AshPluginDescription const & castor3d::RenderSystem::getDescription () const inline noexcept
References castor3d::Renderer::desc.
Referenced by getRendererType(), and hasSsbo().
getFeatures()
VkPhysicalDeviceFeatures const & castor3d::RenderSystem::getFeatures () const inline noexcept
getFrustum()
C3D_API castor::Matrix4x4f castor3d::RenderSystem::getFrustum (float left, float right, float bottom, float top, float zNear, float zFar) const
Computes an frustum projection matrix.
Parameters
[in] left,right The left and right planes position.
[in] top,bottom The top and bottom planes position.
[in] zNear,zFar The near and far planes position.
getGpuInformations()
GpuInformations const & castor3d::RenderSystem::getGpuInformations () const inline noexcept
getInfinitePerspective()
C3D_API castor::Matrix4x4f castor3d::RenderSystem::getInfinitePerspective (castor::Angle const & fovy, float aspect, float zNear) const
Computes a perspective projection matrix with no far plane clipping.
Parameters
[in] fovy The vertical aperture angle.
[in] aspect The width / height ratio.
[in] zNear The near plane position.
getInstance()
ashes::Instance const & castor3d::RenderSystem::getInstance () const inline noexcept
References castor3d::Renderer::instance.
getMemoryProperties()
VkPhysicalDeviceMemoryProperties const & castor3d::RenderSystem::getMemoryProperties () const inline noexcept
getOrtho()
C3D_API castor::Matrix4x4f castor3d::RenderSystem::getOrtho (float left, float right, float bottom, float top, float zNear, float zFar) const
Computes an orthographic projection matrix.
Parameters
[in] left,right The left and right planes position.
[in] top,bottom The top and bottom planes position.
[in] zNear,zFar The near and far planes position.
getPerspective()
C3D_API castor::Matrix4x4f castor3d::RenderSystem::getPerspective (castor::Angle const & fovy, float aspect, float zNear, float zFar) const
Computes a perspective projection matrix.
Parameters
[in] fovy The vertical aperture angle.
[in] aspect The width / height ratio.
[in] zNear The near plane position.
[in] zFar The far plane position.
getPhysicalDevice()
ashes::PhysicalDevice const & castor3d::RenderSystem::getPhysicalDevice () const inline noexcept
References castor3d::Renderer::gpu.
getPrefilteredBrdfTexture()
C3D_API Texture const & castor3d::RenderSystem::getPrefilteredBrdfTexture () const
getProperties()
VkPhysicalDeviceProperties const & castor3d::RenderSystem::getProperties () const inline noexcept
getRandomStorage()
ashes::Buffer< castor::Point4f > const & castor3d::RenderSystem::getRandomStorage () const inline noexcept
getRenderDevice()
RenderDevice & castor3d::RenderSystem::getRenderDevice () const inline noexcept
References CU_Require, and hasDevice().
getRendererType()
castor::String castor3d::RenderSystem::getRendererType () const inline noexcept
References getDescription(), and castor::makeString().
getValue() [1/2]
uint32_t castor3d::RenderSystem::getValue (GpuMax index) const inline noexcept
References castor3d::GpuInformations::getValue().
getValue() [2/2]
uint32_t castor3d::RenderSystem::getValue (GpuMin index) const inline noexcept
References castor3d::GpuInformations::getValue().
hasDevice()
bool castor3d::RenderSystem::hasDevice () const inline noexcept
Referenced by getRenderDevice().
hasFeature()
bool castor3d::RenderSystem::hasFeature (GpuFeature feature) const inline noexcept
References castor3d::GpuInformations::hasFeature().
hasLLPV()
bool castor3d::RenderSystem::hasLLPV () const inline noexcept
hasShaderStorageBuffers()
bool castor3d::RenderSystem::hasShaderStorageBuffers () const inline noexcept
References castor3d::GpuInformations::hasShaderStorageBuffers().
hasShaderType()
bool castor3d::RenderSystem::hasShaderType (VkShaderStageFlagBits type) const inline noexcept
References castor3d::GpuInformations::hasShaderType().
hasSsbo()
bool castor3d::RenderSystem::hasSsbo () const inline noexcept
References getDescription().
hasStereoRendering()
bool castor3d::RenderSystem::hasStereoRendering () const inline noexcept
References castor3d::GpuInformations::hasStereoRendering().
The documentation for this class was generated from the following file:
Castor3D/Render/RenderSystem.hpp