Castor3D: CastorUtils/Math/Angle.hpp File Reference
Angle.hpp File Reference
Classes
class castor::AngleT< Type >
Angle helper class.
Namespaces
namespace castor
Typedefs
Math
using castor::Angle = AngleT< float >
Functions
template<typename Type >
static AngleT< Type > castor::acosT (double value)
Computes this angle's value from the given cosine value.
template<typename Type >
static AngleT< Type > castor::asinT (double value)
Computes this angle's value from the given sine value.
template<typename Type >
static AngleT< Type > castor::atanT (double value)
Computes this angle's value from the given tangent value.
static AngleT< float > castor::acosf (double value)
Computes this angle's value from the given cosine value.
static AngleT< float > castor::asinf (double value)
Computes this angle's value from the given sine value.
static AngleT< float > castor::atanf (double value)
Computes this angle's value from the given tangent value.
static AngleT< double > castor::acosd (double value)
Computes this angle's value from the given cosine value.
static AngleT< double > castor::asind (double value)
Computes this angle's value from the given sine value.
static AngleT< double > castor::atand (double value)
Computes this angle's value from the given tangent value.
template<typename Type >
bool castor::operator== (AngleT< Type > const &lhs, AngleT< Type > const &rhs) noexcept
Equality operator.
template<typename Type >
bool castor::operator!= (AngleT< Type > const &lhs, AngleT< Type > const &rhs) noexcept
Difference operator.
template<typename Type >
bool castor::operator< (AngleT< Type > const &lhs, AngleT< Type > const &rhs) noexcept
"Less than" operator
template<typename Type >
bool castor::operator>= (AngleT< Type > const &lhs, AngleT< Type > const &rhs) noexcept
"Greater than or equal to" operator
template<typename Type >
bool castor::operator> (AngleT< Type > const &lhs, AngleT< Type > const &rhs) noexcept
"Greater than" operator
template<typename Type >
bool castor::operator<= (AngleT< Type > const &lhs, AngleT< Type > const &rhs) noexcept
"Less than or equal to" operator
template<typename Type >
AngleT< Type > castor::operator+ (AngleT< Type > const &lhs, AngleT< Type > const &rhs) noexcept
addition operator
template<typename Type >
AngleT< Type > castor::operator- (AngleT< Type > const &lhs, AngleT< Type > const &rhs) noexcept
Substraction operator.
template<typename Type >
AngleT< Type > castor::operator* (AngleT< Type > const &lhs, AngleT< Type > const &rhs) noexcept
Multiplication operator.
template<typename Type >
AngleT< Type > castor::operator/ (AngleT< Type > const &lhs, AngleT< Type > const &rhs) noexcept
Division operator.
template<typename Type >
AngleT< Type > castor::operator* (AngleT< Type > const &lhs, double rhs) noexcept
Multiplication operator.
template<typename Type >
AngleT< Type > castor::operator/ (AngleT< Type > const &lhs, double rhs) noexcept
Division operator.
castor::Angle operator""_turns (long double value)
castor::Angle operator""_degrees (long double value)
castor::Angle operator""_radians (long double value)
Function Documentation
operator""_degrees()
castor::Angle operator""_degrees (long double value) inline
References castor::AngleT< Type >::fromDegrees().
operator""_radians()
castor::Angle operator""_radians (long double value) inline
References castor::AngleT< Type >::fromRadians().
operator""_turns()
castor::Angle operator""_turns (long double value) inline
References castor::AngleT< Type >::fromTurns().