Castor3D: castor3d::BinaryParserBase< TParsed > Class Template Reference
castor3d::BinaryParserBase< TParsed > Class Template Reference abstract
Binary data chunk writer/reader base class.
Public Member Functions
bool parse (TParsed &p_obj, castor::BinaryFile &p_file)
From file reader function.
bool parse (TParsed &p_obj, BinaryChunk &p_chunk)
From chunk reader function.
bool parse_v1_1 (TParsed &p_obj, BinaryChunk &p_chunk)
From chunk reader function.
bool parse_v1_2 (TParsed &p_obj, BinaryChunk &p_chunk)
From chunk reader function.
Protected Member Functions
bool doParseHeader (BinaryChunk &p_chunk) const
Parses the header chunk.
template<typename T >
bool doParseChunk (T *p_values, size_t p_count, BinaryChunk &p_chunk) const
Retrieves a value array from a chunk.
template<typename T , size_t Count>
bool doParseChunk (T(&p_values)[Count], BinaryChunk &p_chunk) const
Retrieves a value array from a chunk.
template<typename T , size_t Count>
bool doParseChunk (std::array< T, Count > &p_values, BinaryChunk &p_chunk) const
Retrieves a value array from a chunk.
template<typename T >
bool doParseChunk (std::vector< T > &p_values, BinaryChunk &p_chunk) const
Retrieves a value array from a chunk.
template<typename T >
bool doParseChunk (T &p_value, BinaryChunk &p_chunk) const
Retrieves a value from a chunk.
bool doGetSubChunk (BinaryChunk &p_chunk)
Retrieves a subchunk.
Protected Attributes
BinaryChunk * m_chunk { nullptr }
Detailed Description
template<class TParsed>
class castor3d::BinaryParserBase< TParsed >
Binary data chunk writer/reader base class.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
15/04/2013
Member Function Documentation
doGetSubChunk()
template<class TParsed> bool castor3d::BinaryParserBase< TParsed >::doGetSubChunk (BinaryChunk & p_chunk) inline protected
Retrieves a subchunk.
Parameters
[out] p_chunk Receives the subchunk.
Returns
false if any error occured.
doParseChunk() [1/5]
template<class TParsed> template<typename T > bool castor3d::BinaryParserBase< TParsed >::doParseChunk (T * p_values, size_t p_count, BinaryChunk & p_chunk) const inline protected
Retrieves a value array from a chunk.
Parameters
[out] p_values Receives the parsed values
[out] p_count The values count
[in] p_chunk The chunk containing the values
Returns
false if any error occured
Referenced by castor3d::BinaryParserBase< Skeleton >::doParseHeader().
doParseChunk() [2/5]
template<class TParsed> template<typename T , size_t Count> bool castor3d::BinaryParserBase< TParsed >::doParseChunk (T(&) p_values[Count], BinaryChunk & p_chunk) const inline protected
Retrieves a value array from a chunk.
Parameters
[out] p_values Receives the parsed values
[in] p_chunk The chunk containing the values
Returns
false if any error occured
doParseChunk() [3/5]
template<class TParsed> template<typename T , size_t Count> bool castor3d::BinaryParserBase< TParsed >::doParseChunk (std::array< T, Count > & p_values, BinaryChunk & p_chunk) const inline protected
Retrieves a value array from a chunk.
Parameters
[out] p_values Receives the parsed values
[in] p_chunk The chunk containing the values
Returns
false if any error occured
doParseChunk() [4/5]
template<class TParsed> template<typename T > bool castor3d::BinaryParserBase< TParsed >::doParseChunk (std::vector< T > & p_values, BinaryChunk & p_chunk) const inline protected
Retrieves a value array from a chunk.
Parameters
[out] p_values Receives the parsed values
[in] p_chunk The chunk containing the values
Returns
false if any error occured
doParseChunk() [5/5]
template<class TParsed> template<typename T > bool castor3d::BinaryParserBase< TParsed >::doParseChunk (T & p_value, BinaryChunk & p_chunk) const inline protected
Retrieves a value from a chunk.
Parameters
[out] p_value Receives the parsed value
[in] p_chunk The chunk containing the value
Returns
false if any error occured
doParseHeader()
template<class TParsed> bool castor3d::BinaryParserBase< TParsed >::doParseHeader (BinaryChunk & p_chunk) const inline protected
Parses the header chunk.
Parameters
[in,out] p_chunk The parent chunk.
Returns
false if any error occured.
Referenced by castor3d::BinaryParserBase< Skeleton >::parse().
parse() [1/2]
template<class TParsed> bool castor3d::BinaryParserBase< TParsed >::parse (TParsed & p_obj, castor::BinaryFile & p_file) inline
From file reader function.
Parameters
[out] p_obj The object to read
[in] p_file The file containing the chunk
Returns
false if any error occured
Referenced by castor3d::BinaryParserBase< Skeleton >::parse().
parse() [2/2]
template<class TParsed> bool castor3d::BinaryParserBase< TParsed >::parse (TParsed & p_obj, BinaryChunk & p_chunk) inline
From chunk reader function.
Parameters
[out] p_obj The object to read
[in] p_chunk The chunk
Returns
false if any error occured
parse_v1_1()
template<class TParsed> bool castor3d::BinaryParserBase< TParsed >::parse_v1_1 (TParsed & p_obj, BinaryChunk & p_chunk) inline
From chunk reader function.
Parameters
[out] p_obj The object to read
[in] p_chunk The chunk
Returns
false if any error occured
parse_v1_2()
template<class TParsed> bool castor3d::BinaryParserBase< TParsed >::parse_v1_2 (TParsed & p_obj, BinaryChunk & p_chunk) inline
From chunk reader function.
Parameters
[out] p_obj The object to read
[in] p_chunk The chunk
Returns
false if any error occured
Member Data Documentation
m_chunk
template<class TParsed> BinaryChunk* castor3d::BinaryParserBase< TParsed >::m_chunk { nullptr } protected
The writer's chunk.
Referenced by castor3d::BinaryParserBase< Skeleton >::doGetSubChunk(), castor3d::BinaryParserBase< Skeleton >::parse(), castor3d::BinaryParserBase< Skeleton >::parse_v1_1(), and castor3d::BinaryParserBase< Skeleton >::parse_v1_2().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Binary/BinaryParser.hpp