Castor3D: castor3d::FrustumClusters Class Reference
castor3d::FrustumClusters Class Reference
#include <FrustumClusters.hpp>
Public Member Functions
C3D_API FrustumClusters (FrustumClusters const &)=delete
C3D_API FrustumClusters (FrustumClusters &&) noexcept=delete
C3D_API FrustumClusters & operator= (FrustumClusters const &)=delete
C3D_API FrustumClusters & operator= (FrustumClusters &&) noexcept=delete
C3D_API ~FrustumClusters () noexcept=default
C3D_API FrustumClusters (RenderDevice const &device, Camera const &camera, ClustersConfig const &config)
C3D_API void update (CpuUpdater &updater)
CPU side update.
C3D_API crg::FramePass const & createFramePasses (crg::FramePassGroup &graph, crg::FramePass const *previousPass, RenderTechnique &technique, CameraUbo const &cameraUbo, RenderNodesPass *&nodesPass)
Registers the clusters related frame passes.
castor::Point3ui const & getDimensions () const noexcept
bool const & needsClustersUpdate () const noexcept
bool const & needsLightsUpdate () const noexcept
auto & getClustersUbo () const noexcept
auto & getClustersAABBBuffer () const noexcept
auto & getPointLightClusterGridBuffer () const noexcept
auto & getSpotLightClusterGridBuffer () const noexcept
auto & getPointLightClusterIndexBuffer () const noexcept
auto & getSpotLightClusterIndexBuffer () const noexcept
auto & getAllLightsAABBBuffer () const noexcept
auto & getReducedLightsAABBBuffer () const noexcept
auto & getPointLightBVHBuffer () const noexcept
auto & getSpotLightBVHBuffer () const noexcept
ashes::BufferBase & getPointLightIndicesBuffer (uint32_t index) const noexcept
ashes::BufferBase & getSpotLightIndicesBuffer (uint32_t index) const noexcept
ashes::BufferBase & getPointLightMortonCodesBuffer (uint32_t index) const noexcept
ashes::BufferBase & getSpotLightMortonCodesBuffer (uint32_t index) const noexcept
ashes::BufferBase & getInputPointLightIndicesBuffer () const noexcept
ashes::BufferBase & getInputSpotLightIndicesBuffer () const noexcept
castor::Vector< ashes::BufferBase const * > getOutputPointLightIndicesBuffers () const noexcept
castor::Vector< ashes::BufferBase const * > getOutputSpotLightIndicesBuffers () const noexcept
castor::Vector< ashes::BufferBase const * > getInputPointLightIndicesBuffers () const noexcept
castor::Vector< ashes::BufferBase const * > getInputSpotLightIndicesBuffers () const noexcept
ashes::BufferBase & getOutputPointLightIndicesBuffer () const noexcept
ashes::BufferBase & getOutputSpotLightIndicesBuffer () const noexcept
ashes::BufferBase & getInputPointLightMortonCodesBuffer () const noexcept
ashes::BufferBase & getInputSpotLightMortonCodesBuffer () const noexcept
castor::Vector< ashes::BufferBase const * > getOutputPointLightMortonCodesBuffers () const noexcept
castor::Vector< ashes::BufferBase const * > getOutputSpotLightMortonCodesBuffers () const noexcept
castor::Vector< ashes::BufferBase const * > getInputPointLightMortonCodesBuffers () const noexcept
castor::Vector< ashes::BufferBase const * > getInputSpotLightMortonCodesBuffers () const noexcept
ashes::BufferBase & getOutputPointLightMortonCodesBuffer () const noexcept
ashes::BufferBase & getOutputSpotLightMortonCodesBuffer () const noexcept
ashes::BufferBase & getMergePathPartitionsBuffer () const noexcept
ashes::BufferBase & getClusterFlagsBuffer () const noexcept
ashes::BufferBase & getUniqueClustersBuffer () const noexcept
ashes::BufferBase & getClustersIndirectBuffer () const noexcept
auto & getCamera () const noexcept
auto & getConfig () const noexcept
Static Public Member Functions
static C3D_API uint32_t getNumLevelNodes (uint32_t level)
static C3D_API uint32_t getNumLevels (uint32_t numLeaves)
static C3D_API uint32_t getNumNodes (uint32_t numLeaves)
Public Attributes
OnClustersBuffersChanged onClusterBuffersChanged
Constructor & Destructor Documentation
FrustumClusters() [1/3]
C3D_API castor3d::FrustumClusters::FrustumClusters (FrustumClusters const &) delete
FrustumClusters() [2/3]
C3D_API castor3d::FrustumClusters::FrustumClusters (FrustumClusters &&) delete noexcept
~FrustumClusters()
C3D_API castor3d::FrustumClusters::~FrustumClusters () default noexcept
FrustumClusters() [3/3]
C3D_API castor3d::FrustumClusters::FrustumClusters (RenderDevice const & device, Camera const & camera, ClustersConfig const & config)
Member Function Documentation
createFramePasses()
C3D_API crg::FramePass const & castor3d::FrustumClusters::createFramePasses (crg::FramePassGroup & graph, crg::FramePass const * previousPass, RenderTechnique & technique, CameraUbo const & cameraUbo, RenderNodesPass *& nodesPass)
Registers the clusters related frame passes.
getAllLightsAABBBuffer()
auto & castor3d::FrustumClusters::getAllLightsAABBBuffer () const inline noexcept
getCamera()
auto & castor3d::FrustumClusters::getCamera () const inline noexcept
getClusterFlagsBuffer()
ashes::BufferBase & castor3d::FrustumClusters::getClusterFlagsBuffer () const inline noexcept
getClustersAABBBuffer()
auto & castor3d::FrustumClusters::getClustersAABBBuffer () const inline noexcept
References CU_Require.
getClustersIndirectBuffer()
ashes::BufferBase & castor3d::FrustumClusters::getClustersIndirectBuffer () const inline noexcept
getClustersUbo()
auto & castor3d::FrustumClusters::getClustersUbo () const inline noexcept
getConfig()
auto & castor3d::FrustumClusters::getConfig () const inline noexcept
getDimensions()
castor::Point3ui const & castor3d::FrustumClusters::getDimensions () const inline noexcept
getInputPointLightIndicesBuffer()
ashes::BufferBase & castor3d::FrustumClusters::getInputPointLightIndicesBuffer () const inline noexcept
References getPointLightIndicesBuffer().
getInputPointLightIndicesBuffers()
castor::Vector< ashes::BufferBase const * > castor3d::FrustumClusters::getInputPointLightIndicesBuffers () const inline noexcept
References getPointLightIndicesBuffer().
getInputPointLightMortonCodesBuffer()
ashes::BufferBase & castor3d::FrustumClusters::getInputPointLightMortonCodesBuffer () const inline noexcept
References getPointLightMortonCodesBuffer().
getInputPointLightMortonCodesBuffers()
castor::Vector< ashes::BufferBase const * > castor3d::FrustumClusters::getInputPointLightMortonCodesBuffers () const inline noexcept
References getPointLightMortonCodesBuffer().
getInputSpotLightIndicesBuffer()
ashes::BufferBase & castor3d::FrustumClusters::getInputSpotLightIndicesBuffer () const inline noexcept
References getSpotLightIndicesBuffer().
getInputSpotLightIndicesBuffers()
castor::Vector< ashes::BufferBase const * > castor3d::FrustumClusters::getInputSpotLightIndicesBuffers () const inline noexcept
References getSpotLightIndicesBuffer().
getInputSpotLightMortonCodesBuffer()
ashes::BufferBase & castor3d::FrustumClusters::getInputSpotLightMortonCodesBuffer () const inline noexcept
References getSpotLightMortonCodesBuffer().
getInputSpotLightMortonCodesBuffers()
castor::Vector< ashes::BufferBase const * > castor3d::FrustumClusters::getInputSpotLightMortonCodesBuffers () const inline noexcept
References getSpotLightMortonCodesBuffer().
getMergePathPartitionsBuffer()
ashes::BufferBase & castor3d::FrustumClusters::getMergePathPartitionsBuffer () const inline noexcept
getNumLevelNodes()
static C3D_API uint32_t castor3d::FrustumClusters::getNumLevelNodes (uint32_t level) static
Parameters
[in] level The BVH level.
Returns
The number of nodes for given BVH level.
getNumLevels()
static C3D_API uint32_t castor3d::FrustumClusters::getNumLevels (uint32_t numLeaves) static
Parameters
[in] numLeaves The number of leaf nodes.
Returns
The number of levels needed for a BVH that consists of a number of leaf nodes.
getNumNodes()
static C3D_API uint32_t castor3d::FrustumClusters::getNumNodes (uint32_t numLeaves) static
Parameters
[in] numLeaves The number of leaf nodes.
Returns
The number of (child) nodes needed to represent a BVH that consists of a number of leaf nodes.
getOutputPointLightIndicesBuffer()
ashes::BufferBase & castor3d::FrustumClusters::getOutputPointLightIndicesBuffer () const inline noexcept
References getPointLightIndicesBuffer().
getOutputPointLightIndicesBuffers()
castor::Vector< ashes::BufferBase const * > castor3d::FrustumClusters::getOutputPointLightIndicesBuffers () const inline noexcept
References getPointLightIndicesBuffer().
getOutputPointLightMortonCodesBuffer()
ashes::BufferBase & castor3d::FrustumClusters::getOutputPointLightMortonCodesBuffer () const inline noexcept
References getPointLightMortonCodesBuffer().
getOutputPointLightMortonCodesBuffers()
castor::Vector< ashes::BufferBase const * > castor3d::FrustumClusters::getOutputPointLightMortonCodesBuffers () const inline noexcept
References getPointLightMortonCodesBuffer().
getOutputSpotLightIndicesBuffer()
ashes::BufferBase & castor3d::FrustumClusters::getOutputSpotLightIndicesBuffer () const inline noexcept
References getSpotLightIndicesBuffer().
getOutputSpotLightIndicesBuffers()
castor::Vector< ashes::BufferBase const * > castor3d::FrustumClusters::getOutputSpotLightIndicesBuffers () const inline noexcept
References getSpotLightIndicesBuffer().
getOutputSpotLightMortonCodesBuffer()
ashes::BufferBase & castor3d::FrustumClusters::getOutputSpotLightMortonCodesBuffer () const inline noexcept
References getSpotLightMortonCodesBuffer().
getOutputSpotLightMortonCodesBuffers()
castor::Vector< ashes::BufferBase const * > castor3d::FrustumClusters::getOutputSpotLightMortonCodesBuffers () const inline noexcept
References getSpotLightMortonCodesBuffer().
getPointLightBVHBuffer()
auto & castor3d::FrustumClusters::getPointLightBVHBuffer () const inline noexcept
getPointLightClusterGridBuffer()
auto & castor3d::FrustumClusters::getPointLightClusterGridBuffer () const inline noexcept
References CU_Require.
getPointLightClusterIndexBuffer()
auto & castor3d::FrustumClusters::getPointLightClusterIndexBuffer () const inline noexcept
References CU_Require.
getPointLightIndicesBuffer()
ashes::BufferBase & castor3d::FrustumClusters::getPointLightIndicesBuffer (uint32_t index) const inline noexcept
Referenced by getInputPointLightIndicesBuffer(), getInputPointLightIndicesBuffers(), getOutputPointLightIndicesBuffer(), and getOutputPointLightIndicesBuffers().
getPointLightMortonCodesBuffer()
ashes::BufferBase & castor3d::FrustumClusters::getPointLightMortonCodesBuffer (uint32_t index) const inline noexcept
Referenced by getInputPointLightMortonCodesBuffer(), getInputPointLightMortonCodesBuffers(), getOutputPointLightMortonCodesBuffer(), and getOutputPointLightMortonCodesBuffers().
getReducedLightsAABBBuffer()
auto & castor3d::FrustumClusters::getReducedLightsAABBBuffer () const inline noexcept
getSpotLightBVHBuffer()
auto & castor3d::FrustumClusters::getSpotLightBVHBuffer () const inline noexcept
getSpotLightClusterGridBuffer()
auto & castor3d::FrustumClusters::getSpotLightClusterGridBuffer () const inline noexcept
References CU_Require.
getSpotLightClusterIndexBuffer()
auto & castor3d::FrustumClusters::getSpotLightClusterIndexBuffer () const inline noexcept
References CU_Require.
getSpotLightIndicesBuffer()
ashes::BufferBase & castor3d::FrustumClusters::getSpotLightIndicesBuffer (uint32_t index) const inline noexcept
Referenced by getInputSpotLightIndicesBuffer(), getInputSpotLightIndicesBuffers(), getOutputSpotLightIndicesBuffer(), and getOutputSpotLightIndicesBuffers().
getSpotLightMortonCodesBuffer()
ashes::BufferBase & castor3d::FrustumClusters::getSpotLightMortonCodesBuffer (uint32_t index) const inline noexcept
Referenced by getInputSpotLightMortonCodesBuffer(), getInputSpotLightMortonCodesBuffers(), getOutputSpotLightMortonCodesBuffer(), and getOutputSpotLightMortonCodesBuffers().
getUniqueClustersBuffer()
ashes::BufferBase & castor3d::FrustumClusters::getUniqueClustersBuffer () const inline noexcept
needsClustersUpdate()
bool const & castor3d::FrustumClusters::needsClustersUpdate () const inline noexcept
needsLightsUpdate()
bool const & castor3d::FrustumClusters::needsLightsUpdate () const inline noexcept
operator=() [1/2]
C3D_API FrustumClusters & castor3d::FrustumClusters::operator= (FrustumClusters &&) delete noexcept
operator=() [2/2]
C3D_API FrustumClusters & castor3d::FrustumClusters::operator= (FrustumClusters const &) delete
update()
C3D_API void castor3d::FrustumClusters::update (CpuUpdater & updater)
CPU side update.
Parameters
[in,out] updater The update data.
Member Data Documentation
onClusterBuffersChanged
OnClustersBuffersChanged castor3d::FrustumClusters::onClusterBuffersChanged
The documentation for this class was generated from the following file:
Castor3D/Render/Clustered/FrustumClusters.hpp