Castor3D: castor3d::IridescenceThicknessMapComponent Struct Reference
castor3d::IridescenceThicknessMapComponent Struct Reference
#include <IridescenceThicknessMapComponent.hpp>
Classes
struct ComponentsShader
class Plugin
Public Member Functions
C3D_API IridescenceThicknessMapComponent (Pass &pass)
PassComponentTextureFlag getTextureFlags () const override
Public Member Functions inherited from castor3d::PassMapComponent
C3D_API PassMapComponent (Pass &pass, castor::String const &type)
Constructor.
C3D_API void fillConfig (TextureConfiguration &config, PassVisitorBase &vis) const override
PassVisitor acceptance function, for a specific texture configuration.
void fillChannel (TextureConfiguration &configuration, uint32_t mask) const
Public Member Functions inherited from castor3d::PassComponent
C3D_API PassComponent (Pass &pass, castor::String const &type)
Constructor.
virtual C3D_API ~PassComponent () noexcept=default
C3D_API PassComponentUPtr clone (Pass &pass) const
C3D_API bool writeText (castor::String const &tabs, castor::Path const &folder, castor::String const &subfolder, castor::StringStream &file) const
Writes the component content to text.
C3D_API void fillBuffer (PassBuffer &buffer) const
Fills the pass buffer with this pass data.
virtual C3D_API void accept (PassVisitorBase &vis)
PassVisitor acceptance function.
virtual C3D_API void update ()
C3D_API void fillChannel (TextureConfiguration &configuration, uint32_t mask)
Fills the texture configuration for use with this component.
virtual C3D_API bool hasColour () const
virtual C3D_API castor::HdrRgbColour const & getColour () const
virtual C3D_API void setColour (castor::HdrRgbColour v)
virtual C3D_API PassComponentFlag getPassFlags () const
castor::String const & getType () const
PassComponentPlugin const & getPlugin () const
PassComponentID getId () const
void setColour (castor::RgbColour const &v, float gamma=2.2f)
void setColour (castor::Coords3f const &v)
void setColour (castor::Point3f const &v)
Static Public Member Functions
static PassComponentPluginUPtr createPlugin (PassComponentRegister const &passComponent)
Static Public Attributes
static const TextureFlag IridescenceThickness = TextureFlag(0x01u)
static C3D_API castor::String const TypeName
Additional Inherited Members
Protected Attributes inherited from castor3d::PassComponent
castor::String m_type
PassComponentID m_id
PassComponentPlugin const & m_plugin
std::atomic_bool & m_dirty
shader::PassMaterialShader * m_materialShader {}
Constructor & Destructor Documentation
IridescenceThicknessMapComponent()
C3D_API castor3d::IridescenceThicknessMapComponent::IridescenceThicknessMapComponent (Pass & pass) explicit
Member Function Documentation
createPlugin()
static PassComponentPluginUPtr castor3d::IridescenceThicknessMapComponent::createPlugin (PassComponentRegister const & passComponent) inline static
getTextureFlags()
PassComponentTextureFlag castor3d::IridescenceThicknessMapComponent::getTextureFlags () const inline override virtual
Reimplemented from castor3d::PassMapComponent.
References castor3d::PassComponent::getId(), IridescenceThickness, and castor3d::makeTextureFlag().
Member Data Documentation
IridescenceThickness
const TextureFlag castor3d::IridescenceThicknessMapComponent::IridescenceThickness = TextureFlag(0x01u) static
Referenced by castor3d::IridescenceThicknessMapComponent::ComponentsShader::getTextureFlags(), castor3d::IridescenceThicknessMapComponent::Plugin::getTextureFlags(), getTextureFlags(), and castor3d::IridescenceThicknessMapComponent::Plugin::getTextureFlagsName().
TypeName
C3D_API castor::String const castor3d::IridescenceThicknessMapComponent::TypeName static
The documentation for this struct was generated from the following file:
Material/Pass/Component/Map/IridescenceThicknessMapComponent.hpp