Castor3D: castor3d::RenderTechniquePass Class Reference
castor3d::RenderTechniquePass Class Reference abstract
#include <RenderTechniquePass.hpp>
Public Member Functions
virtual C3D_API ~RenderTechniquePass ()=default
virtual C3D_API void accept (RenderTechniqueVisitor &visitor)
Visitor acceptance function.
virtual C3D_API void update (CpuUpdater &updater)
Updates the render pass, CPU wise.
virtual C3D_API PipelineFlags createPipelineFlags (PassComponentCombine components, BlendMode colourBlendMode, BlendMode alphaBlendMode, RenderPassTypeID renderPassTypeId, LightingModelID lightingModelId, BackgroundModelID backgroundModelId, VkCompareOp alphaFunc, VkCompareOp blendAlphaFunc, TextureCombine const &textures, SubmeshFlags const &submeshFlags, ProgramFlags const &programFlags, SceneFlags const &sceneFlags, VkPrimitiveTopology topology, bool isFrontCulled, bool invertNormals, uint32_t passLayerIndex, GpuBufferOffsetT< castor::Point4f > const &morphTargets) const =0
Creates the pipeline flags for given configuration.
virtual C3D_API bool areValidPassFlags (PassComponentCombine const &passFlags) const =0
virtual C3D_API ShaderFlags getShaderFlags () const =0
virtual C3D_API void countNodes (RenderInfo &info) const =0
Registers nodes counts to given RenderInfo.
virtual C3D_API bool isPassEnabled () const =0
C3D_API Engine * getEngine () const
Scene const & getScene ()
Scene const & getScene () const
RenderTechnique const & getTechnique () const
Protected Member Functions
C3D_API RenderTechniquePass (RenderTechnique *parent, Scene const &scene)
Constructor.
Protected Attributes
RenderTechnique * m_parent {}
Scene const & m_scene
uint32_t m_drawCalls {}
Constructor & Destructor Documentation
RenderTechniquePass()
C3D_API castor3d::RenderTechniquePass::RenderTechniquePass (RenderTechnique * parent, Scene const & scene) protected
Constructor.
Parameters
[in] parent The parent technique.
[in] scene The scene.
~RenderTechniquePass()
virtual C3D_API castor3d::RenderTechniquePass::~RenderTechniquePass () virtual default
Member Function Documentation
accept()
virtual C3D_API void castor3d::RenderTechniquePass::accept (RenderTechniqueVisitor & visitor) inline virtual
Visitor acceptance function.
Parameters
visitor The ... visitor.
Reimplemented in castor3d::OpaquePass, castor3d::VisibilityResolvePass, castor3d::ForwardRenderTechniquePass, castor3d::VisibilityPass, castor3d::RenderTechniqueNodesPass, and castor3d::TransparentPass.
areValidPassFlags()
virtual C3D_API bool castor3d::RenderTechniquePass::areValidPassFlags (PassComponentCombine const & passFlags) const pure virtual
Implemented in castor3d::VisibilityResolvePass, and castor3d::RenderTechniqueNodesPass.
countNodes()
virtual C3D_API void castor3d::RenderTechniquePass::countNodes (RenderInfo & info) const pure virtual
Registers nodes counts to given RenderInfo.
Parameters
[in,out] info Receives the counts.
Implemented in castor3d::VisibilityResolvePass, and castor3d::RenderTechniqueNodesPass.
createPipelineFlags()
virtual C3D_API PipelineFlags castor3d::RenderTechniquePass::createPipelineFlags (PassComponentCombine components, BlendMode colourBlendMode, BlendMode alphaBlendMode, RenderPassTypeID renderPassTypeId, LightingModelID lightingModelId, BackgroundModelID backgroundModelId, VkCompareOp alphaFunc, VkCompareOp blendAlphaFunc, TextureCombine const & textures, SubmeshFlags const & submeshFlags, ProgramFlags const & programFlags, SceneFlags const & sceneFlags, VkPrimitiveTopology topology, bool isFrontCulled, bool invertNormals, uint32_t passLayerIndex, GpuBufferOffsetT< castor::Point4f > const & morphTargets) const pure virtual
Creates the pipeline flags for given configuration.
Parameters
[in] components The components combination.
[in] colourBlendMode The colour blending mode.
[in] alphaBlendMode The alpha blending mode.
[in] renderPassTypeId The render pass type ID.
[in] lightingModelId The lighting model ID.
[in] backgroundModelId The background model ID.
[in] alphaFunc The alpha comparison function (for opaque nodes).
[in] blendAlphaFunc The alpha comparison function (for transparent nodes).
[in] textures The textures configuration.
[in] submeshFlags A combination of SubmeshFlag.
[in] programFlags A combination of ProgramFlag.
[in] sceneFlags Scene related flags.
[in] topology The render topology.
[in] isFrontCulled true for front face culling, false for back face culling.
[in] invertNormals true to invert normals.
[in] passLayerIndex The material pass layer index.
[in] morphTargets The morph targets buffer.
Implemented in castor3d::VisibilityResolvePass, and castor3d::RenderTechniqueNodesPass.
getEngine()
C3D_API Engine * castor3d::RenderTechniquePass::getEngine () const
name Getters.
Referenced by castor3d::RenderTechniqueNodesPass::getEngine().
getScene() [1/2]
Scene const & castor3d::RenderTechniquePass::getScene () inline
References m_scene.
Referenced by castor3d::RenderTechniqueNodesPass::getScene().
getScene() [2/2]
Scene const & castor3d::RenderTechniquePass::getScene () const inline
References m_scene.
getShaderFlags()
virtual C3D_API ShaderFlags castor3d::RenderTechniquePass::getShaderFlags () const pure virtual
Implemented in castor3d::OpaquePass, castor3d::VisibilityResolvePass, castor3d::DepthPass, castor3d::VisibilityPass, and castor3d::RenderTechniqueNodesPass.
getTechnique()
RenderTechnique const & castor3d::RenderTechniquePass::getTechnique () const inline
References m_parent.
Referenced by castor3d::RenderTechniqueNodesPass::getTechnique().
isPassEnabled()
virtual C3D_API bool castor3d::RenderTechniquePass::isPassEnabled () const pure virtual
Implemented in castor3d::VisibilityResolvePass, and castor3d::RenderTechniqueNodesPass.
update()
virtual C3D_API void castor3d::RenderTechniquePass::update (CpuUpdater & updater) inline virtual
Updates the render pass, CPU wise.
Parameters
[in,out] updater The update data.
Reimplemented in castor3d::VisibilityResolvePass, and castor3d::RenderTechniqueNodesPass.
Member Data Documentation
m_drawCalls
uint32_t castor3d::RenderTechniquePass::m_drawCalls {} protected
m_parent
RenderTechnique* castor3d::RenderTechniquePass::m_parent {} protected
Referenced by getTechnique().
m_scene
Scene const& castor3d::RenderTechniquePass::m_scene protected
Referenced by getScene().
The documentation for this class was generated from the following file:
Render/RenderTechniquePass.hpp