Castor3D: castor3d::BinaryChunk Class Reference
castor3d::BinaryChunk Class Reference
Binary data chunk base class.
Public Member Functions
C3D_API BinaryChunk ()
Constructor.
C3D_API BinaryChunk (ChunkType p_type)
Constructor.
C3D_API void finalise ()
Computes the final data buffer from each one added until this call.
C3D_API void add (uint8_t *p_data, uint32_t p_size)
adds data to the chunk
C3D_API void get (uint8_t *p_data, uint32_t p_size)
Retrieves data from the chunk.
C3D_API bool checkAvailable (uint32_t p_size=0) const
Checks that the remaining place can hold the given size.
C3D_API uint32_t getRemaining () const
Retrieves the remaining place.
C3D_API bool getSubChunk (BinaryChunk &p_subchunk)
Retrieves a subchunk.
C3D_API bool addSubChunk (BinaryChunk const &p_subchunk)
Writes a subchunk into a chunk.
C3D_API bool write (castor::BinaryFile &p_file)
To chunk writer function.
C3D_API bool read (castor::BinaryFile &p_file)
From file reader function.
uint8_t const * getRemainingData () const
Retrieves the remaining data.
ChunkType getChunkType () const
Retrieves the chunk type.
uint32_t getDataSize () const
Retrieves the chunk data size.
uint8_t const * getData () const
Retrieves the chunk data.
void setData (uint8_t const *p_begin, uint8_t const *p_end)
sets the chunk's data
void endParse ()
Retrieves the chunk data size.
void resetParse ()
Resets the chunk, to be able to reparse it.
Detailed Description
Binary data chunk base class.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
15/04/2013
Constructor & Destructor Documentation
BinaryChunk() [1/2]
C3D_API castor3d::BinaryChunk::BinaryChunk ()
Constructor.
BinaryChunk() [2/2]
C3D_API castor3d::BinaryChunk::BinaryChunk (ChunkType p_type) explicit
Constructor.
Parameters
[in] p_type The chunk type
Member Function Documentation
add()
C3D_API void castor3d::BinaryChunk::add (uint8_t * p_data, uint32_t p_size)
adds data to the chunk
Parameters
[in] p_data The data buffer
[in] p_size The buffer size
addSubChunk()
C3D_API bool castor3d::BinaryChunk::addSubChunk (BinaryChunk const & p_subchunk)
Writes a subchunk into a chunk.
Parameters
[in] p_subchunk The subchunk
Returns
false if any error occured
Referenced by castor3d::BinaryWriterBase< Skeleton >::doWriteHeader(), castor3d::ChunkWriterBase::write(), and castor3d::BinaryWriterBase< Skeleton >::write().
checkAvailable()
C3D_API bool castor3d::BinaryChunk::checkAvailable (uint32_t p_size = 0) const
Checks that the remaining place can hold the given size.
Parameters
[in] p_size The size
Referenced by castor3d::BinaryParserBase< Skeleton >::doGetSubChunk(), castor3d::BinaryParserBase< Skeleton >::doParseHeader(), castor3d::BinaryParserBase< Skeleton >::parse(), castor3d::ChunkParserBase::parse(), castor3d::ChunkParser< castor::String >::parse(), and castor3d::ChunkParser< castor::Path >::parse().
endParse()
void castor3d::BinaryChunk::endParse () inline
Retrieves the chunk data size.
Referenced by castor3d::BinaryParserBase< Skeleton >::doParseHeader(), castor3d::BinaryParserBase< Skeleton >::parse(), castor3d::BinaryParserBase< Skeleton >::parse_v1_1(), and castor3d::BinaryParserBase< Skeleton >::parse_v1_2().
finalise()
C3D_API void castor3d::BinaryChunk::finalise ()
Computes the final data buffer from each one added until this call.
Referenced by castor3d::BinaryWriterBase< Skeleton >::write().
get()
C3D_API void castor3d::BinaryChunk::get (uint8_t * p_data, uint32_t p_size)
Retrieves data from the chunk.
Parameters
[in] p_data The data buffer to fill
[in] p_size The buffer size
Referenced by castor3d::ChunkParserBase::parse().
getChunkType()
ChunkType castor3d::BinaryChunk::getChunkType () const inline
Retrieves the chunk type.
Returns
The value
Referenced by castor3d::BinaryParserBase< Skeleton >::doParseHeader(), castor3d::BinaryParserBase< Skeleton >::parse(), castor3d::BinaryParserBase< Skeleton >::parse_v1_1(), and castor3d::BinaryParserBase< Skeleton >::parse_v1_2().
getData()
uint8_t const* castor3d::BinaryChunk::getData () const inline
Retrieves the chunk data.
Returns
The value
getDataSize()
uint32_t castor3d::BinaryChunk::getDataSize () const inline
Retrieves the chunk data size.
Returns
The value
getRemaining()
C3D_API uint32_t castor3d::BinaryChunk::getRemaining () const
Retrieves the remaining place.
Returns
The value
Referenced by castor3d::ChunkParser< castor::String >::parse(), and castor3d::ChunkParser< castor::Path >::parse().
getRemainingData()
uint8_t const* castor3d::BinaryChunk::getRemainingData () const inline
Retrieves the remaining data.
Returns
The value
getSubChunk()
C3D_API bool castor3d::BinaryChunk::getSubChunk (BinaryChunk & p_subchunk)
Retrieves a subchunk.
Parameters
[out] p_subchunk Receives the subchunk
Returns
false if any error occured
Referenced by castor3d::BinaryParserBase< Skeleton >::doGetSubChunk(), castor3d::BinaryParserBase< Skeleton >::doParseHeader(), and castor3d::BinaryParserBase< Skeleton >::parse().
read()
C3D_API bool castor3d::BinaryChunk::read (castor::BinaryFile & p_file)
From file reader function.
Parameters
[in] p_file The file containing the chunk
Returns
false if any error occured
Referenced by castor3d::BinaryParserBase< Skeleton >::parse().
resetParse()
void castor3d::BinaryChunk::resetParse () inline
Resets the chunk, to be able to reparse it.
Referenced by castor3d::BinaryParserBase< Skeleton >::parse().
setData()
void castor3d::BinaryChunk::setData (uint8_t const * p_begin, uint8_t const * p_end) inline
sets the chunk's data
Parameters
[in] p_begin The data buffer's begin
[in] p_end The data buffer's end
Referenced by castor3d::ChunkWriterBase::write().
write()
C3D_API bool castor3d::BinaryChunk::write (castor::BinaryFile & p_file)
To chunk writer function.
Parameters
[in] p_file The file
Returns
false if any error occured
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Binary/BinaryChunk.hpp