Castor3D: Castor3D::MatrixFrameVariable< T, Rows, Columns > Class Template Reference
Castor3D::MatrixFrameVariable< T, Rows, Columns > Class Template Reference
Matrix shader variable with variable type and dimensions.
Public Member Functions
MatrixFrameVariable (ShaderProgramBase *p_pProgram)
Constructor.
MatrixFrameVariable (ShaderProgramBase *p_pProgram, uint32_t p_uiOcc)
Constructor.
MatrixFrameVariable (MatrixFrameVariable< T, Rows, Columns > const &p_object)
Copy constructor.
MatrixFrameVariable (MatrixFrameVariable< T, Rows, Columns > &&p_object)
Move constructor.
MatrixFrameVariable & operator= (MatrixFrameVariable< T, Rows, Columns > const &p_object)
Copy assignment operator.
MatrixFrameVariable & operator= (MatrixFrameVariable< T, Rows, Columns > &&p_object)
Move assignment operator.
virtual ~MatrixFrameVariable ()
Destructor.
Castor::Matrix< T, Rows, Columns > & operator [] (uint32_t p_uiIndex)
Array subscript operator.
Castor::Matrix< T, Rows, Columns > const & operator [] (uint32_t p_uiIndex) const
Array subscript operator.
Castor::Matrix< T, Rows, Columns > & GetValue () throw (std::out_of_range)
Retrieves the value.
Castor::Matrix< T, Rows, Columns > const & GetValue () const throw (std::out_of_range)
Retrieves the value.
Castor::Matrix< T, Rows, Columns > & GetValue (uint32_t p_uiIndex) throw (std::out_of_range)
Retrieves the value at given index.
Castor::Matrix< T, Rows, Columns > const & GetValue (uint32_t p_uiIndex) const throw (std::out_of_range)
Retrieves the value at given index.
eVARIABLE_TYPE GetType () const
Retrieves the variable type.
eFRAME_VARIABLE_TYPE GetFullType () const
Retrieves the variable full type.
void SetValue (Castor::Matrix< T, Rows, Columns > const &p_mtxValue)
Defines the value of the variable.
void SetValue (Castor::Matrix< T, Rows, Columns > const &p_mtxValue, uint32_t p_uiIndex)
Defines the value of the variable.
virtual uint32_t size () const
Retrieves the byte size of the variable.
virtual void link (uint8_t *p_pBuffer)
Defines the buffer holding the frame variable.
Public Member Functions inherited from Castor3D::TFrameVariable< T >
TFrameVariable (ShaderProgramBase *p_pProgram)
Constructor.
TFrameVariable (ShaderProgramBase *p_pProgram, uint32_t p_uiOcc)
Constructor.
TFrameVariable (TFrameVariable< T > const &p_object)
Copy constructor.
TFrameVariable (TFrameVariable< T > &&p_object)
Move constructor.
TFrameVariable & operator= (TFrameVariable< T > const &p_object)
Copy assignment operator.
TFrameVariable & operator= (TFrameVariable< T > &&p_object)
Move assignment operator.
virtual ~TFrameVariable ()
Destructor.
Castor::String GetDataType () const
Gives the variable data type.
virtual uint8_t const *const const_ptr () const
Retrieves a pointer to the variable data.
Public Member Functions inherited from Castor3D::FrameVariable
FrameVariable (ShaderProgramBase *p_pProgram)
Constructor.
FrameVariable (ShaderProgramBase *p_pProgram, uint32_t p_uiOcc)
Constructor.
FrameVariable (FrameVariable const &p_object)
Copy constructor.
FrameVariable (FrameVariable &&p_object)
Move constructor.
FrameVariable & operator= (FrameVariable const &p_object)
Copy assignment operator.
FrameVariable & operator= (FrameVariable &&p_object)
Move assignment operator.
virtual ~FrameVariable ()
Destructor.
virtual bool Initialise ()=0
Initialises the variable.
virtual void Cleanup ()=0
Cleans up the variable.
virtual void Apply ()=0
Applies this variable.
virtual void Bind ()=0
Binds this variable to it's program or object, depending of implementation (Glsl, Hlsl or Cg)
virtual void SetValueStr (Castor::String const &p_strValue)
Defines the value of the variable, from a string.
virtual void SetValueStr (Castor::String const &p_strValue, uint32_t p_uiIndex)
Defines the value of the variable, from a string.
virtual void SetName (Castor::String const &p_strName)
Defines the name of the variable, as it appears in the shader program.
Castor::String GetName () const
Gives the name of the variable, as it appears in the shader program.
Castor::String GetStrValue () const
Retrieves the variable string value.
Castor::String GetStrValue (uint32_t p_uiIndex) const
Retrieves the variable string value at given index.
const uint32_t & GetOccCount () const
Retrieves the occurences count.
ShaderProgramBase * GetProgram () const
Retrieves the parent program.
Static Public Member Functions
static eVARIABLE_TYPE GetVariableType ()
Gives the full type of the variable.
static eFRAME_VARIABLE_TYPE GetFrameVariableType ()
Gives the variable full type.
Static Public Member Functions inherited from Castor3D::TFrameVariable< T >
static Castor::String StGetDataType ()
Gives the variable data type.
Protected Types
typedef Castor::Policy< T > policy
Protected Types inherited from Castor3D::TFrameVariable< T >
typedef Castor::Policy< T > policy
Protected Attributes
Castor::Matrix< T, Rows, Columns > * m_mtxValue
The matrix values.
Protected Attributes inherited from Castor3D::TFrameVariable< T >
bool m_bOwnBuffer
Tells the variable owns it's buffer.
T * m_pValues
The buffer containing all values.
Protected Attributes inherited from Castor3D::FrameVariable
Castor::String m_strName
The variable name as it appears in the shader program.
bool m_bChanged
Tells if the variable has changed since last execution of the shader.
uint32_t m_uiOcc
The array dimension if the variable represents an array.
Castor::StringArray m_strValue
The value of the variable.
ShaderProgramBase * m_pProgram
The parent shader program.
Additional Inherited Members
Static Public Attributes inherited from Castor3D::FrameVariable
static const Castor::String Names []
The names of the frame variable types.
Protected Member Functions inherited from Castor3D::TFrameVariable< T >
void DoCleanupBuffer ()
Detailed Description
template<typename T, uint32_t Rows, uint32_t Columns>
class Castor3D::MatrixFrameVariable< T, Rows, Columns >
Matrix shader variable with variable type and dimensions.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
14/08/2010
Member Typedef Documentation
policy
template<typename T , uint32_t Rows, uint32_t Columns> typedef Castor::Policy<T> Castor3D::MatrixFrameVariable< T, Rows, Columns >::policy protected
Constructor & Destructor Documentation
MatrixFrameVariable() [1/4]
template<typename T , uint32_t Rows, uint32_t Columns> Castor3D::MatrixFrameVariable< T, Rows, Columns >::MatrixFrameVariable (ShaderProgramBase * p_pProgram)
Constructor.
MatrixFrameVariable() [2/4]
template<typename T , uint32_t Rows, uint32_t Columns> Castor3D::MatrixFrameVariable< T, Rows, Columns >::MatrixFrameVariable (ShaderProgramBase * p_pProgram, uint32_t p_uiOcc)
Constructor.
Parameters
[in] p_uiOcc The array dimension
MatrixFrameVariable() [3/4]
template<typename T , uint32_t Rows, uint32_t Columns> Castor3D::MatrixFrameVariable< T, Rows, Columns >::MatrixFrameVariable (MatrixFrameVariable< T, Rows, Columns > const & p_object)
Copy constructor.
Parameters
[in] p_object The object to copy
MatrixFrameVariable() [4/4]
template<typename T , uint32_t Rows, uint32_t Columns> Castor3D::MatrixFrameVariable< T, Rows, Columns >::MatrixFrameVariable (MatrixFrameVariable< T, Rows, Columns > && p_object)
Move constructor.
Parameters
[in] p_object The object to move
~MatrixFrameVariable()
template<typename T , uint32_t Rows, uint32_t Columns> virtual Castor3D::MatrixFrameVariable< T, Rows, Columns >::~MatrixFrameVariable () virtual
Destructor.
Member Function Documentation
GetFrameVariableType()
template<typename T , uint32_t Rows, uint32_t Columns> static eFRAME_VARIABLE_TYPE Castor3D::MatrixFrameVariable< T, Rows, Columns >::GetFrameVariableType () inline static
Gives the variable full type.
Returns
The type
Donne le type complet de la variable
Returns
Le type
Referenced by Castor3D::MatrixFrameVariable< T, Rows, Columns >::GetFullType().
GetFullType()
template<typename T , uint32_t Rows, uint32_t Columns> eFRAME_VARIABLE_TYPE Castor3D::MatrixFrameVariable< T, Rows, Columns >::GetFullType () const inline virtual
Retrieves the variable full type.
Returns
The type
Implements Castor3D::FrameVariable.
References Castor3D::MatrixFrameVariable< T, Rows, Columns >::GetFrameVariableType().
GetType()
template<typename T , uint32_t Rows, uint32_t Columns> eVARIABLE_TYPE Castor3D::MatrixFrameVariable< T, Rows, Columns >::GetType () const inline virtual
Retrieves the variable type.
Returns
The variable type
Implements Castor3D::FrameVariable.
References Castor3D::MatrixFrameVariable< T, Rows, Columns >::GetVariableType().
GetValue() [1/4]
template<typename T , uint32_t Rows, uint32_t Columns> Castor::Matrix< T, Rows, Columns >& Castor3D::MatrixFrameVariable< T, Rows, Columns >::GetValue () throw (std::out_of_range) inline
Retrieves the value.
Returns
A reference to the value
GetValue() [2/4]
template<typename T , uint32_t Rows, uint32_t Columns> Castor::Matrix< T, Rows, Columns > const& Castor3D::MatrixFrameVariable< T, Rows, Columns >::GetValue () const throw (std::out_of_range) inline
Retrieves the value.
Returns
A constant reference to the value
GetValue() [3/4]
template<typename T , uint32_t Rows, uint32_t Columns> Castor::Matrix< T, Rows, Columns >& Castor3D::MatrixFrameVariable< T, Rows, Columns >::GetValue (uint32_t p_uiIndex) throw (std::out_of_range) inline
Retrieves the value at given index.
Remarks
Check the index bounds
Parameters
[in] p_uiIndex The index
Returns
A reference to the value at given index
GetValue() [4/4]
template<typename T , uint32_t Rows, uint32_t Columns> Castor::Matrix< T, Rows, Columns > const& Castor3D::MatrixFrameVariable< T, Rows, Columns >::GetValue (uint32_t p_uiIndex) const throw (std::out_of_range) inline
Retrieves the value at given index.
Remarks
Check the index bounds
Parameters
[in] p_uiIndex The index
Returns
A constant reference to the value at given index
GetVariableType()
template<typename T , uint32_t Rows, uint32_t Columns> static eVARIABLE_TYPE Castor3D::MatrixFrameVariable< T, Rows, Columns >::GetVariableType () static
Gives the full type of the variable.
Returns
The type of the variable
Referenced by Castor3D::MatrixFrameVariable< T, Rows, Columns >::GetType().
link()
template<typename T , uint32_t Rows, uint32_t Columns> virtual void Castor3D::MatrixFrameVariable< T, Rows, Columns >::link (uint8_t * p_pBuffer) virtual
Defines the buffer holding the frame variable.
Remarks
The variable no longer owns it's buffer
Parameters
[in] p_pBuffer The buffer
Reimplemented from Castor3D::TFrameVariable< T >.
operator []() [1/2]
template<typename T , uint32_t Rows, uint32_t Columns> Castor::Matrix< T, Rows, Columns >& Castor3D::MatrixFrameVariable< T, Rows, Columns >::operator [] (uint32_t p_uiIndex) inline
Array subscript operator.
Remarks
Doesn't check the index bounds
Parameters
[in] p_uiIndex The index
Returns
A reference to the value at given index
References Castor3D::MatrixFrameVariable< T, Rows, Columns >::m_mtxValue.
operator []() [2/2]
template<typename T , uint32_t Rows, uint32_t Columns> Castor::Matrix< T, Rows, Columns > const& Castor3D::MatrixFrameVariable< T, Rows, Columns >::operator [] (uint32_t p_uiIndex) const inline
Array subscript operator.
Remarks
Doesn't check the index bounds
Parameters
[in] p_uiIndex The index
Returns
A constant reference to the value at given index
References Castor3D::MatrixFrameVariable< T, Rows, Columns >::m_mtxValue.
operator=() [1/2]
template<typename T , uint32_t Rows, uint32_t Columns> MatrixFrameVariable& Castor3D::MatrixFrameVariable< T, Rows, Columns >::operator= (MatrixFrameVariable< T, Rows, Columns > const & p_object)
Copy assignment operator.
Parameters
[in] p_object The object to copy
Returns
A reference to this object
operator=() [2/2]
template<typename T , uint32_t Rows, uint32_t Columns> MatrixFrameVariable& Castor3D::MatrixFrameVariable< T, Rows, Columns >::operator= (MatrixFrameVariable< T, Rows, Columns > && p_object)
Move assignment operator.
Parameters
[in] p_object The object to move
Returns
A reference to this object
SetValue() [1/2]
template<typename T , uint32_t Rows, uint32_t Columns> void Castor3D::MatrixFrameVariable< T, Rows, Columns >::SetValue (Castor::Matrix< T, Rows, Columns > const & p_mtxValue) inline
Defines the value of the variable.
Parameters
[in] p_mtxValue The new value
SetValue() [2/2]
template<typename T , uint32_t Rows, uint32_t Columns> void Castor3D::MatrixFrameVariable< T, Rows, Columns >::SetValue (Castor::Matrix< T, Rows, Columns > const & p_mtxValue, uint32_t p_uiIndex) inline
Defines the value of the variable.
Parameters
[in] p_mtxValue The new value
[in] p_uiIndex The index of the value
size()
template<typename T , uint32_t Rows, uint32_t Columns> virtual uint32_t Castor3D::MatrixFrameVariable< T, Rows, Columns >::size () const virtual
Retrieves the byte size of the variable.
Returns
The size
Implements Castor3D::FrameVariable.
Member Data Documentation
m_mtxValue
template<typename T , uint32_t Rows, uint32_t Columns> Castor::Matrix< T, Rows, Columns >* Castor3D::MatrixFrameVariable< T, Rows, Columns >::m_mtxValue protected
The matrix values.
Referenced by Castor3D::MatrixFrameVariable< T, Rows, Columns >::operator []().
The documentation for this class was generated from the following files:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Castor3DPrerequisites.hpp
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/MatrixFrameVariable.hpp