Castor3D: castor3d::shader::SurfaceBaseT< Position3T, Position4T, NormalT > Struct Template Reference
castor3d::shader::SurfaceBaseT< Position3T, Position4T, NormalT > Struct Template Reference
#include <GlslSurface.hpp>
Public Member Functions
SurfaceBaseT (sdw::ShaderWriter &writer, sdw::expr::ExprPtr expr, bool enabled)
Public Attributes
sdw::Vec3 clipPosition
Position4T viewPosition
Position4T worldPosition
NormalT normal
Static Protected Member Functions
static void fillType (sdw::type::BaseStruct &type)
static void fillIOType (sdw::type::IOStruct &type, PipelineFlags const &flags, uint32_t &index)
static void fillType (sdw::type::BaseStruct &type, PipelineFlags const &flags)
static void fillInit (sdw::expr::ExprList &init, sdw::Vec3 clip, Position4T view, Position4T world, NormalT normal)
static void fillInit (sdw::expr::ExprList &init, PipelineFlags const &flags, sdw::Vec3 clip, Position4T view, Position4T world, NormalT normal)
static Position3T makePosition3 (sdw::Vec3 const &in)
static Position3T makePosition3 (sdw::Vec3 const &in)
static Position3T makePosition3 (sdw::Float const &in)
static Position4T makePosition4 (sdw::Vec4 const &in)
static Position4T makePosition4 (sdw::Vec4 const &in)
static Position4T makePosition4 (sdw::Vec3 const &rgb, sdw::Float const &a)
static Position4T makePosition4 (DerivVec3 const &rgb, DerivFloat const &a)
static Position4T makePosition4 (sdw::Vec3 const &in)
static Position4T makePosition4 (DerivVec3 const &in)
static Position4T makePosition4 (sdw::Float const &in)
static NormalT makeNormal (sdw::Vec3 const &in)
static NormalT makeNormal (sdw::Vec3 const &in)
static NormalT makeNormal (sdw::Float const &in)
Constructor & Destructor Documentation
SurfaceBaseT()
template<typename Position3T , typename Position4T , typename NormalT > castor3d::shader::SurfaceBaseT< Position3T, Position4T, NormalT >::SurfaceBaseT (sdw::ShaderWriter & writer, sdw::expr::ExprPtr expr, bool enabled)
Member Function Documentation
fillInit() [1/2]
template<typename Position3T , typename Position4T , typename NormalT > static void castor3d::shader::SurfaceBaseT< Position3T, Position4T, NormalT >::fillInit (sdw::expr::ExprList & init, PipelineFlags const & flags, sdw::Vec3 clip, Position4T view, Position4T world, NormalT normal) static protected
fillInit() [2/2]
template<typename Position3T , typename Position4T , typename NormalT > static void castor3d::shader::SurfaceBaseT< Position3T, Position4T, NormalT >::fillInit (sdw::expr::ExprList & init, sdw::Vec3 clip, Position4T view, Position4T world, NormalT normal) static protected
fillIOType()
template<typename Position3T , typename Position4T , typename NormalT > static void castor3d::shader::SurfaceBaseT< Position3T, Position4T, NormalT >::fillIOType (sdw::type::IOStruct & type, PipelineFlags const & flags, uint32_t & index) static protected
fillType() [1/2]
template<typename Position3T , typename Position4T , typename NormalT > static void castor3d::shader::SurfaceBaseT< Position3T, Position4T, NormalT >::fillType (sdw::type::BaseStruct & type) static protected
fillType() [2/2]
template<typename Position3T , typename Position4T , typename NormalT > static void castor3d::shader::SurfaceBaseT< Position3T, Position4T, NormalT >::fillType (sdw::type::BaseStruct & type, PipelineFlags const & flags) static protected
makeNormal() [1/3]
template<typename Position3T , typename Position4T , typename NormalT > static NormalT castor3d::shader::SurfaceBaseT< Position3T, Position4T, NormalT >::makeNormal (sdw::Float const & in) inline static protected
References castor3d::shader::SurfaceBaseT< Position3T, Position4T, NormalT >::makeNormal().
makeNormal() [2/3]
template<typename Position3T , typename Position4T , typename NormalT > static NormalT castor3d::shader::SurfaceBaseT< Position3T, Position4T, NormalT >::makeNormal (sdw::Vec3 const & in) inline static protected
Referenced by castor3d::shader::SurfaceBaseT< Position3T, Position4T, NormalT >::makeNormal().
makeNormal() [3/3]
template<typename Position3T , typename Position4T , typename NormalT > static NormalT castor3d::shader::SurfaceBaseT< Position3T, Position4T, NormalT >::makeNormal (sdw::Vec3 const & in) inline static protected
References castor3d::shader::derivVec3().
makePosition3() [1/3]
template<typename Position3T , typename Position4T , typename NormalT > static Position3T castor3d::shader::SurfaceBaseT< Position3T, Position4T, NormalT >::makePosition3 (sdw::Float const & in) inline static protected
References castor3d::shader::SurfaceBaseT< Position3T, Position4T, NormalT >::makePosition3().
makePosition3() [2/3]
template<typename Position3T , typename Position4T , typename NormalT > static Position3T castor3d::shader::SurfaceBaseT< Position3T, Position4T, NormalT >::makePosition3 (sdw::Vec3 const & in) inline static protected
Referenced by castor3d::shader::SurfaceBaseT< Position3T, Position4T, NormalT >::makePosition3().
makePosition3() [3/3]
template<typename Position3T , typename Position4T , typename NormalT > static Position3T castor3d::shader::SurfaceBaseT< Position3T, Position4T, NormalT >::makePosition3 (sdw::Vec3 const & in) inline static protected
References castor3d::shader::derivVec3().
makePosition4() [1/7]
template<typename Position3T , typename Position4T , typename NormalT > static Position4T castor3d::shader::SurfaceBaseT< Position3T, Position4T, NormalT >::makePosition4 (DerivVec3 const & in) inline static protected
References castor3d::shader::derivVec4().
makePosition4() [2/7]
template<typename Position3T , typename Position4T , typename NormalT > static Position4T castor3d::shader::SurfaceBaseT< Position3T, Position4T, NormalT >::makePosition4 (DerivVec3 const & rgb, DerivFloat const & a) inline static protected
References castor3d::shader::derivVec4().
makePosition4() [3/7]
template<typename Position3T , typename Position4T , typename NormalT > static Position4T castor3d::shader::SurfaceBaseT< Position3T, Position4T, NormalT >::makePosition4 (sdw::Float const & in) inline static protected
References castor3d::shader::SurfaceBaseT< Position3T, Position4T, NormalT >::makePosition4().
makePosition4() [4/7]
template<typename Position3T , typename Position4T , typename NormalT > static Position4T castor3d::shader::SurfaceBaseT< Position3T, Position4T, NormalT >::makePosition4 (sdw::Vec3 const & in) inline static protected
makePosition4() [5/7]
template<typename Position3T , typename Position4T , typename NormalT > static Position4T castor3d::shader::SurfaceBaseT< Position3T, Position4T, NormalT >::makePosition4 (sdw::Vec3 const & rgb, sdw::Float const & a) inline static protected
makePosition4() [6/7]
template<typename Position3T , typename Position4T , typename NormalT > static Position4T castor3d::shader::SurfaceBaseT< Position3T, Position4T, NormalT >::makePosition4 (sdw::Vec4 const & in) inline static protected
Referenced by castor3d::shader::SurfaceBaseT< Position3T, Position4T, NormalT >::makePosition4().
makePosition4() [7/7]
template<typename Position3T , typename Position4T , typename NormalT > static Position4T castor3d::shader::SurfaceBaseT< Position3T, Position4T, NormalT >::makePosition4 (sdw::Vec4 const & in) inline static protected
References castor3d::shader::derivVec4().
Member Data Documentation
clipPosition
template<typename Position3T , typename Position4T , typename NormalT > sdw::Vec3 castor3d::shader::SurfaceBaseT< Position3T, Position4T, NormalT >::clipPosition
normal
template<typename Position3T , typename Position4T , typename NormalT > NormalT castor3d::shader::SurfaceBaseT< Position3T, Position4T, NormalT >::normal
viewPosition
template<typename Position3T , typename Position4T , typename NormalT > Position4T castor3d::shader::SurfaceBaseT< Position3T, Position4T, NormalT >::viewPosition
worldPosition
template<typename Position3T , typename Position4T , typename NormalT > Position4T castor3d::shader::SurfaceBaseT< Position3T, Position4T, NormalT >::worldPosition
The documentation for this struct was generated from the following files:
Castor3D/Material/Pass/Component/ComponentModule.hpp
Castor3D/Shader/Shaders/GlslSurface.hpp