Castor3D: castor3d::GBufferBase Class Reference
castor3d::GBufferBase Class Reference
Public Types
using Textures = std::vector< TextureUnit const * >
Public Member Functions
C3D_API GBufferBase (castor::String name)
Static Protected Member Functions
static C3D_API TextureUnit doCreateTexture (Engine &engine, castor::String const &name, VkImageCreateFlags createFlags, VkExtent3D const &size, uint32_t layerCount, uint32_t mipLevels, VkFormat format, VkImageUsageFlags usageFlags, VkBorderColor const &borderColor)
template<typename TextureEnumT >
static C3D_API TextureUnitArray doCreateTextures (Engine &engine, std::array< TextureUnit const *, size_t(TextureEnumT::eCount) > const &inputs, castor::String const &prefix, VkImageCreateFlags createFlags, castor::Size const &size, uint32_t layerCount=1u)
Initialises 2D or 2D array g-buffer textures.
template<typename TextureEnumT >
static C3D_API TextureUnitArray doCreateTextures (Engine &engine, std::array< TextureUnit const *, size_t(TextureEnumT::eCount) > const &inputs, castor::String const &prefix, VkImageCreateFlags createFlags, VkExtent3D const &size)
Initialises 3D g-buffer textures.
Member Typedef Documentation
Textures
using castor3d::GBufferBase::Textures = std::vector< TextureUnit const * >
Constructor & Destructor Documentation
GBufferBase()
C3D_API castor3d::GBufferBase::GBufferBase (castor::String name) inline explicit
Member Function Documentation
doCreateTexture()
static C3D_API TextureUnit castor3d::GBufferBase::doCreateTexture (Engine & engine, castor::String const & name, VkImageCreateFlags createFlags, VkExtent3D const & size, uint32_t layerCount, uint32_t mipLevels, VkFormat format, VkImageUsageFlags usageFlags, VkBorderColor const & borderColor) static protected
Referenced by doCreateTextures().
doCreateTextures() [1/2]
template<typename TextureEnumT > static C3D_API TextureUnitArray castor3d::GBufferBase::doCreateTextures (Engine & engine, std::array< TextureUnit const *, size_t(TextureEnumT::eCount) > const & inputs, castor::String const & prefix, VkImageCreateFlags createFlags, castor::Size const & size, uint32_t layerCount = 1u) inline static protected
Initialises 2D or 2D array g-buffer textures.
Parameters
[in] engine The engine.
[in] inputs The already existing images.
[in] prefix The buffer's textures name's prefix.
[in] createFlags The creation flags for images remaining to create.
[in] size The g-buffer's dimensions.
[in] layerCount The layers count for the g-buffer.
References doCreateTexture(), castor3d::getBorderColor(), castor3d::getFormat(), castor3d::getMipLevels(), castor3d::getName(), and castor3d::getUsageFlags().
doCreateTextures() [2/2]
template<typename TextureEnumT > static C3D_API TextureUnitArray castor3d::GBufferBase::doCreateTextures (Engine & engine, std::array< TextureUnit const *, size_t(TextureEnumT::eCount) > const & inputs, castor::String const & prefix, VkImageCreateFlags createFlags, VkExtent3D const & size) inline static protected
Initialises 3D g-buffer textures.
Parameters
[in] engine The engine.
[in] inputs The already existing images.
[in] prefix The buffer's textures name's prefix.
[in] createFlags The creation flags for images remaining to create.
[in] size The g-buffer's dimensions.
References doCreateTexture(), castor3d::getBorderColor(), castor3d::getFormat(), castor3d::getMipLevels(), castor3d::getName(), and castor3d::getUsageFlags().
The documentation for this class was generated from the following file:
Render/GBuffer.hpp