Castor3D: castor::ParserParameterBase Class Reference
castor::ParserParameterBase Class Reference abstract
#include <ParserParameterBase.hpp>
Public Member Functions
CU_API ParserParameterBase ()=default
Constructor.
CU_API ParserParameterBase (ParserParameterBase const &)=default
CU_API ParserParameterBase (ParserParameterBase &&) noexcept=default
CU_API ParserParameterBase & operator= (ParserParameterBase const &)=default
CU_API ParserParameterBase & operator= (ParserParameterBase &&) noexcept=default
virtual CU_API ~ParserParameterBase () noexcept=default
virtual CU_API ParameterType getType () const =0
virtual CU_API ParameterType getBaseType () const
virtual CU_API StringView getStrType () const =0
virtual CU_API ParserParameterBaseSPtr clone () const =0
virtual CU_API bool parse (LoggerInstance &logger, String &params)=0
Checks the parameter.
virtual CU_API bool isSet ()=0
template<typename T >
T const & get (T &value) const
Retrieves the parameter value.
template<typename T >
T get () const
Constructor & Destructor Documentation
ParserParameterBase() [1/3]
CU_API castor::ParserParameterBase::ParserParameterBase () default
Constructor.
ParserParameterBase() [2/3]
CU_API castor::ParserParameterBase::ParserParameterBase (ParserParameterBase const &) default
ParserParameterBase() [3/3]
CU_API castor::ParserParameterBase::ParserParameterBase (ParserParameterBase &&) default noexcept
~ParserParameterBase()
virtual CU_API castor::ParserParameterBase::~ParserParameterBase () virtual default noexcept
Member Function Documentation
clone()
virtual CU_API ParserParameterBaseSPtr castor::ParserParameterBase::clone () const pure virtual
Returns
A copy of this parameter.
Implemented in castor::ParserParameter< Type, std::enable_if_t< !hasBaseParameterTypeV< Type > &&!isArithmeticTypeV< Type > > >, and castor::ParserParameter< Type, std::enable_if_t< IsArithmeticType< Type >::value > >.
get() [1/2]
template<typename T > T castor::ParserParameterBase::get () const inline
Returns
The parameter value.
References get().
Referenced by get().
get() [2/2]
template<typename T > T const & castor::ParserParameterBase::get (T & value) const
Retrieves the parameter value.
Parameters
[out] value Receives the value.
Returns
The value.
getBaseType()
virtual CU_API ParameterType castor::ParserParameterBase::getBaseType () const inline virtual
Returns
The parameter base type (like ParameterType::eText for ParameterType::eName).
References getType().
getStrType()
virtual CU_API StringView castor::ParserParameterBase::getStrType () const pure virtual
Returns
The parameter string type.
Implemented in castor::ParserParameter< Type, std::enable_if_t< !hasBaseParameterTypeV< Type > &&!isArithmeticTypeV< Type > > >, and castor::ParserParameter< Type, std::enable_if_t< IsArithmeticType< Type >::value > >.
getType()
virtual CU_API ParameterType castor::ParserParameterBase::getType () const pure virtual
Returns
The parameter type.
Implemented in castor::ParserParameter< Type, std::enable_if_t< !hasBaseParameterTypeV< Type > &&!isArithmeticTypeV< Type > > >, and castor::ParserParameter< Type, std::enable_if_t< IsArithmeticType< Type >::value > >.
Referenced by getBaseType().
isSet()
virtual CU_API bool castor::ParserParameterBase::isSet () pure virtual
Returns
false if the parameter is not set.
Implemented in castor::ParserParameter< Type, std::enable_if_t< !hasBaseParameterTypeV< Type > &&!isArithmeticTypeV< Type > > >, and castor::ParserParameter< Type, std::enable_if_t< IsArithmeticType< Type >::value > >.
operator=() [1/2]
CU_API ParserParameterBase & castor::ParserParameterBase::operator= (ParserParameterBase &&) default noexcept
operator=() [2/2]
CU_API ParserParameterBase & castor::ParserParameterBase::operator= (ParserParameterBase const &) default
parse()
virtual CU_API bool castor::ParserParameterBase::parse (LoggerInstance & logger, String & params) pure virtual
Checks the parameter.
Parameters
[in,out] logger The logger instance.
[in,out] params The text containing the parameter value.
Returns
false if any error occured.
Implemented in castor::ParserParameter< Type, std::enable_if_t< !hasBaseParameterTypeV< Type > &&!isArithmeticTypeV< Type > > >, and castor::ParserParameter< Type, std::enable_if_t< IsArithmeticType< Type >::value > >.
The documentation for this class was generated from the following file:
CastorUtils/FileParser/ParserParameterBase.hpp