Castor3D: castor::FileParser Class Reference
castor::FileParser Class Reference abstract
#include <FileParser.hpp>
Public Member Functions
CU_API FileParser (SectionId rootSectionId, void *rootBlockContext=nullptr)
Constructor.
CU_API FileParser (LoggerInstance &logger, SectionId rootSectionId, void *rootBlockContext=nullptr)
Constructor.
virtual CU_API ~FileParser () noexcept=default
Destructor.
CU_API void registerParsers (String const &name, AdditionalParsers const &parsers)
Registers additional parsers.
CU_API void processFile (String const &appName, Path path, PreprocessedFile &preprocessed)
Parsing function.
CU_API void processFile (Path const &path, PreprocessedFile &preprocessed)
Parsing function.
CU_API void processFile (Path const &path, String const &content, PreprocessedFile &preprocessed)
Parsing function.
CU_API PreprocessedFile processFile (String const &appName, Path const &path)
Parsing function.
CU_API PreprocessedFile processFile (Path const &path)
Parsing function.
CU_API PreprocessedFile processFile (Path const &path, String const &content)
Parsing function.
CU_API bool parseFile (String const &appName, Path const &path)
Parsing function.
CU_API bool parseFile (Path const &path)
Parsing function.
CU_API bool parseFile (Path const &path, String const &content)
Parsing function.
CU_API void parseError (String const &functionName, uint64_t lineIndex, String const &error)
Logs an error in the log file.
CU_API void parseWarning (String const &functionName, uint64_t lineIndex, String const &warning)
Logs a warning in the log file.
CU_API void addParser (SectionId oldSection, SectionId newSection, String const &name, ParserFunction const &function, ParserParameterArray const &params=ParserParameterArray())
adds a parser function to the parsers list.
CU_API void addParser (SectionId section, String const &name, ParserFunction const &function, ParserParameterArray const &params=ParserParameterArray())
adds a parser function to the parsers list.
bool isIgnored () const
Tells if the read lines are to be ignored.
void ignore ()
Increments ignore level.
LoggerInstance & getLogger () const
SectionId getRootSectionId () const
void * getRootBlockContext () const
void validate (PreprocessedFile &preprocessed)
String getSectionName (SectionId section) const
void cleanupParser (PreprocessedFile &preprocessed)
auto const & getAdditionalParsers () const
Protected Member Functions
virtual CU_API FileParserContextUPtr doInitialiseParser (Path const &path)
Specific initialisation function.
virtual CU_API void doCleanupParser (PreprocessedFile &preprocessed)=0
Specific cleanup.
virtual CU_API bool doDiscardParser (PreprocessedFile &preprocessed, StringView line)
Function called when no parser is found for the line.
virtual CU_API void doValidate (PreprocessedFile &preprocessed)=0
Function called when file parsing is completed with no error.
virtual CU_API String doGetSectionName (SectionId section) const =0
Gives the name associated to section ID.
virtual CU_API castor::RawUniquePtr< FileParser > doCreateParser () const =0
Protected Member Functions inherited from castor::NonMovable
NonMovable ()=default
Constructor.
~NonMovable () noexcept=default
Destructor.
Protected Attributes
LoggerInstance & m_logger
AttributeParsers m_parsers
bool m_ignored { false }
StrStrMap m_defines
Constructor & Destructor Documentation
FileParser() [1/2]
CU_API castor::FileParser::FileParser (SectionId rootSectionId, void * rootBlockContext = nullptr) explicit
Constructor.
Parameters
[in] rootSectionId The root section id.
[in] rootBlockContext The root block context.
FileParser() [2/2]
CU_API castor::FileParser::FileParser (LoggerInstance & logger, SectionId rootSectionId, void * rootBlockContext = nullptr)
Constructor.
Parameters
[in] logger The logger instance.
[in] rootSectionId The root section id.
[in] rootBlockContext The root block context.
~FileParser()
virtual CU_API castor::FileParser::~FileParser () virtual default noexcept
Destructor.
Member Function Documentation
addParser() [1/2]
CU_API void castor::FileParser::addParser (SectionId oldSection, SectionId newSection, String const & name, ParserFunction const & function, ParserParameterArray const & params = ParserParameterArray())
adds a parser function to the parsers list.
Parameters
[in] oldSection The parser section onto which the function is applied.
[in] newSection The parser section resulting of the function application.
[in] name The parser name.
[in] function The parser function.
[in] params The expected parameters.
addParser() [2/2]
CU_API void castor::FileParser::addParser (SectionId section, String const & name, ParserFunction const & function, ParserParameterArray const & params = ParserParameterArray())
adds a parser function to the parsers list.
Parameters
[in] section The parser section.
[in] name The parser name.
[in] function The parser function.
[in] params The expected parameters.
cleanupParser()
void castor::FileParser::cleanupParser (PreprocessedFile & preprocessed) inline
References doCleanupParser().
doCleanupParser()
virtual CU_API void castor::FileParser::doCleanupParser (PreprocessedFile & preprocessed) protected pure virtual
Specific cleanup.
Referenced by cleanupParser().
doCreateParser()
virtual CU_API castor::RawUniquePtr< FileParser > castor::FileParser::doCreateParser () const protected pure virtual
doDiscardParser()
virtual CU_API bool castor::FileParser::doDiscardParser (PreprocessedFile & preprocessed, StringView line) protected virtual
Function called when no parser is found for the line.
Parameters
[in] preprocessed The preprocessed file.
[in] line The line.
Returns
false if the line must be ignored.
doGetSectionName()
virtual CU_API String castor::FileParser::doGetSectionName (SectionId section) const protected pure virtual
Gives the name associated to section ID.
Parameters
[in] section The section ID.
Returns
The name.
Referenced by getSectionName().
doInitialiseParser()
virtual CU_API FileParserContextUPtr castor::FileParser::doInitialiseParser (Path const & path) protected virtual
Specific initialisation function.
Parameters
[in] path The file access path.
doValidate()
virtual CU_API void castor::FileParser::doValidate (PreprocessedFile & preprocessed) protected pure virtual
Function called when file parsing is completed with no error.
Referenced by validate().
getAdditionalParsers()
auto const & castor::FileParser::getAdditionalParsers () const inline
getLogger()
LoggerInstance & castor::FileParser::getLogger () const inline
References m_logger.
getRootBlockContext()
void * castor::FileParser::getRootBlockContext () const inline
getRootSectionId()
SectionId castor::FileParser::getRootSectionId () const inline
getSectionName()
String castor::FileParser::getSectionName (SectionId section) const inline
References doGetSectionName().
ignore()
void castor::FileParser::ignore () inline
Increments ignore level.
References m_ignored.
isIgnored()
bool castor::FileParser::isIgnored () const inline
Tells if the read lines are to be ignored.
References m_ignored.
parseError()
CU_API void castor::FileParser::parseError (String const & functionName, uint64_t lineIndex, String const & error)
Logs an error in the log file.
Parameters
[in] functionName The error function.
[in] lineIndex The error line.
[in] error The error text.
parseFile() [1/3]
CU_API bool castor::FileParser::parseFile (Path const & path)
Parsing function.
Parameters
[in] path The file access path.
Returns
true if OK.
parseFile() [2/3]
CU_API bool castor::FileParser::parseFile (Path const & path, String const & content)
Parsing function.
Parameters
[in] path The file access path.
[in] content The file content.
Returns
true if OK.
parseFile() [3/3]
CU_API bool castor::FileParser::parseFile (String const & appName, Path const & path)
Parsing function.
Parameters
[in] appName The application name, if a dezip is needed.
[in] path The file access path.
Returns
true if OK.
parseWarning()
CU_API void castor::FileParser::parseWarning (String const & functionName, uint64_t lineIndex, String const & warning)
Logs a warning in the log file.
Parameters
[in] functionName The warning function.
[in] lineIndex The warning line.
[in] warning The warning text.
processFile() [1/6]
CU_API PreprocessedFile castor::FileParser::processFile (Path const & path)
Parsing function.
Parameters
[in] path The file access path.
Returns
The preprocessed file.
processFile() [2/6]
CU_API void castor::FileParser::processFile (Path const & path, PreprocessedFile & preprocessed)
Parsing function.
Parameters
[in] path The file access path.
[in] preprocessed The preprocessed file.
processFile() [3/6]
CU_API PreprocessedFile castor::FileParser::processFile (Path const & path, String const & content)
Parsing function.
Parameters
[in] path The file access path.
[in] content The file content.
Returns
The preprocessed file.
processFile() [4/6]
CU_API void castor::FileParser::processFile (Path const & path, String const & content, PreprocessedFile & preprocessed)
Parsing function.
Parameters
[in] path The file access path.
[in] content The file content.
[in] preprocessed The preprocessed file.
processFile() [5/6]
CU_API PreprocessedFile castor::FileParser::processFile (String const & appName, Path const & path)
Parsing function.
Parameters
[in] appName The application name, if a dezip is needed.
[in] path The file access path.
Returns
The preprocessed file.
processFile() [6/6]
CU_API void castor::FileParser::processFile (String const & appName, Path path, PreprocessedFile & preprocessed)
Parsing function.
Parameters
[in] appName The application name, if a dezip is needed.
[in] path The file access path.
[in] preprocessed The preprocessed file.
registerParsers()
CU_API void castor::FileParser::registerParsers (String const & name, AdditionalParsers const & parsers)
Registers additional parsers.
Parameters
[in] name The registering name.
[in] parsers The parsers.
validate()
void castor::FileParser::validate (PreprocessedFile & preprocessed) inline
References doValidate().
Member Data Documentation
m_defines
StrStrMap castor::FileParser::m_defines protected
The defines map.
m_ignored
bool castor::FileParser::m_ignored { false } protected
Tells the lines parsed are to be ignored.
Referenced by ignore(), and isIgnored().
m_logger
LoggerInstance& castor::FileParser::m_logger protected
Referenced by getLogger().
m_parsers
AttributeParsers castor::FileParser::m_parsers protected
The parser functions.
The documentation for this class was generated from the following file:
CastorUtils/FileParser/FileParser.hpp