Castor3D: castor3d::Layout::Item Struct Reference
castor3d::Layout::Item Struct Reference
#include <Layout.hpp>
Classes
union Value
Public Types
enum Type { eControl , eSpacer }
Public Member Functions
Item (Control &c, LayoutItemFlags f, OnControlChangedConnection o) noexcept
Item (Spacer &s) noexcept
auto isControl () const noexcept
auto control () const noexcept
auto flags () const noexcept
auto isSpacer () const noexcept
auto spacer () const noexcept
C3D_API castor::Size getPaddedSize () const noexcept
auto hAlign () const noexcept
auto vAlign () const noexcept
auto expand () const noexcept
auto reserveSpaceIfHidden () const noexcept
uint32_t padding (uint32_t i) const noexcept
uint32_t paddingSize (uint32_t i) const noexcept
Member Enumeration Documentation
Type
enum castor3d::Layout::Item::Type
Enumerator
eControl
eSpacer
Constructor & Destructor Documentation
Item() [1/2]
castor3d::Layout::Item::Item (Control & c, LayoutItemFlags f, OnControlChangedConnection o) inline explicit noexcept
Creates a control item.
Parameters
[in] c The item control.
[in] f The item flags.
[in] o The connection to the control changed signal.
References eControl.
Item() [2/2]
castor3d::Layout::Item::Item (Spacer & s) inline explicit noexcept
Creates a spacer item.
Parameters
[in] s The item spacer.
References eSpacer.
Member Function Documentation
control()
auto castor3d::Layout::Item::control () const inline noexcept
Returns
The control if this item is a control, nullptr if not.
References castor3d::Layout::Item::Value::control, and isControl().
expand()
auto castor3d::Layout::Item::expand () const inline noexcept
Returns
The item expand status.
References flags().
flags()
auto castor3d::Layout::Item::flags () const inline noexcept
Returns
The item flags.
Referenced by expand(), hAlign(), padding(), paddingSize(), reserveSpaceIfHidden(), and vAlign().
getPaddedSize()
C3D_API castor::Size castor3d::Layout::Item::getPaddedSize () const noexcept
Returns
The size including padding.
hAlign()
auto castor3d::Layout::Item::hAlign () const inline noexcept
Returns
The item horizontal alignment.
References flags().
isControl()
auto castor3d::Layout::Item::isControl () const inline noexcept
Returns
true if this item is a control, nullptr if not.
References eControl.
Referenced by control().
isSpacer()
auto castor3d::Layout::Item::isSpacer () const inline noexcept
Returns
true if this item is a spacer, nullptr if not.
References eSpacer.
Referenced by spacer().
padding()
uint32_t castor3d::Layout::Item::padding (uint32_t i) const inline noexcept
Returns
The padding value at given index.
References flags().
paddingSize()
uint32_t castor3d::Layout::Item::paddingSize (uint32_t i) const inline noexcept
Returns
The padding size at given index.
References flags().
reserveSpaceIfHidden()
auto castor3d::Layout::Item::reserveSpaceIfHidden () const inline noexcept
Returns
The item reserve space if hidden status.
References flags().
spacer()
auto castor3d::Layout::Item::spacer () const inline noexcept
Returns
The spacer if this item is a spacer, nullptr if not.
References isSpacer(), and castor3d::Layout::Item::Value::spacer.
vAlign()
auto castor3d::Layout::Item::vAlign () const inline noexcept
Returns
The item vertical alignment.
References flags().
The documentation for this struct was generated from the following file:
Gui/Layout/Layout.hpp