Castor3D: castor3d::PassBuffer::PassDataPtr Struct Reference
castor3d::PassBuffer::PassDataPtr Struct Reference
#include <PassBuffer.hpp>
Public Member Functions
C3D_API PassDataPtr (castor::ByteArrayView data)
C3D_API VkDeviceSize write (MemChunk const &chunk, uint32_t v, VkDeviceSize offset)
C3D_API VkDeviceSize write (MemChunk const &chunk, int32_t v, VkDeviceSize offset)
C3D_API VkDeviceSize write (MemChunk const &chunk, float v, VkDeviceSize offset)
template<typename DataA , typename DataB >
VkDeviceSize write (MemChunk const &chunk, DataA a, DataB b, VkDeviceSize offset)
template<typename DataA , typename DataB , typename DataC >
VkDeviceSize write (MemChunk const &chunk, DataA a, DataB b, DataC c, VkDeviceSize offset)
template<typename DataA , typename DataB , typename DataC , typename DataD >
VkDeviceSize write (MemChunk const &chunk, DataA a, DataB b, DataC c, DataD d, VkDeviceSize offset)
template<typename DataT , size_t SizeT>
VkDeviceSize write (MemChunk const &chunk, castor::Array< DataT, SizeT > const &v, VkDeviceSize offset)
template<typename DataT , uint32_t CountT>
VkDeviceSize write (MemChunk const &chunk, castor::Point< DataT, CountT > const &v, VkDeviceSize offset)
VkDeviceSize write (MemChunk const &chunk, castor::RgbColour const &v, VkDeviceSize offset)
VkDeviceSize write (MemChunk const &chunk, castor::HdrRgbColour const &v, VkDeviceSize offset)
VkDeviceSize write (MemChunk const &chunk, castor::RgbaColour const &v, VkDeviceSize offset)
VkDeviceSize write (MemChunk const &chunk, castor::HdrRgbaColour const &v, VkDeviceSize offset)
Constructor & Destructor Documentation
PassDataPtr()
C3D_API castor3d::PassBuffer::PassDataPtr::PassDataPtr (castor::ByteArrayView data) inline explicit
Member Function Documentation
write() [1/12]
template<typename DataT , size_t SizeT> VkDeviceSize castor3d::PassBuffer::PassDataPtr::write (MemChunk const & chunk, castor::Array< DataT, SizeT > const & v, VkDeviceSize offset) inline
References write().
write() [2/12]
VkDeviceSize castor3d::PassBuffer::PassDataPtr::write (MemChunk const & chunk, castor::HdrRgbaColour const & v, VkDeviceSize offset) inline
References write().
write() [3/12]
VkDeviceSize castor3d::PassBuffer::PassDataPtr::write (MemChunk const & chunk, castor::HdrRgbColour const & v, VkDeviceSize offset) inline
References write().
write() [4/12]
template<typename DataT , uint32_t CountT> VkDeviceSize castor3d::PassBuffer::PassDataPtr::write (MemChunk const & chunk, castor::Point< DataT, CountT > const & v, VkDeviceSize offset) inline
References write().
write() [5/12]
VkDeviceSize castor3d::PassBuffer::PassDataPtr::write (MemChunk const & chunk, castor::RgbaColour const & v, VkDeviceSize offset) inline
References write().
write() [6/12]
VkDeviceSize castor3d::PassBuffer::PassDataPtr::write (MemChunk const & chunk, castor::RgbColour const & v, VkDeviceSize offset) inline
References write().
write() [7/12]
template<typename DataA , typename DataB , typename DataC , typename DataD > VkDeviceSize castor3d::PassBuffer::PassDataPtr::write (MemChunk const & chunk, DataA a, DataB b, DataC c, DataD d, VkDeviceSize offset) inline
References write().
write() [8/12]
template<typename DataA , typename DataB , typename DataC > VkDeviceSize castor3d::PassBuffer::PassDataPtr::write (MemChunk const & chunk, DataA a, DataB b, DataC c, VkDeviceSize offset) inline
References write().
write() [9/12]
template<typename DataA , typename DataB > VkDeviceSize castor3d::PassBuffer::PassDataPtr::write (MemChunk const & chunk, DataA a, DataB b, VkDeviceSize offset) inline
References write().
write() [10/12]
C3D_API VkDeviceSize castor3d::PassBuffer::PassDataPtr::write (MemChunk const & chunk, float v, VkDeviceSize offset)
write() [11/12]
C3D_API VkDeviceSize castor3d::PassBuffer::PassDataPtr::write (MemChunk const & chunk, int32_t v, VkDeviceSize offset)
write() [12/12]
C3D_API VkDeviceSize castor3d::PassBuffer::PassDataPtr::write (MemChunk const & chunk, uint32_t v, VkDeviceSize offset)
Referenced by write(), write(), write(), write(), write(), write(), write(), write(), and write().
The documentation for this struct was generated from the following file:
Castor3D/Shader/ShaderBuffers/PassBuffer.hpp