Castor3D: castor3d::InstantUploadDataT< UploaderT > Class Template Reference
castor3d::InstantUploadDataT< UploaderT > Class Template Reference
#include <InstantUploadData.hpp>
Public Member Functions
InstantUploadDataT (InstantUploadDataT const &)=delete
InstantUploadDataT (InstantUploadDataT &&) noexcept=delete
InstantUploadDataT & operator= (InstantUploadDataT const &)=delete
InstantUploadDataT & operator= (InstantUploadDataT &&)=delete
template<typename ... ParamsT>
InstantUploadDataT (ashes::Queue const &queue, ParamsT &&... params)
~InstantUploadDataT ()
operator UploaderT & ()
UploaderT * operator-> ()
Constructor & Destructor Documentation
InstantUploadDataT() [1/3]
template<UploadDataT UploaderT> castor3d::InstantUploadDataT< UploaderT >::InstantUploadDataT (InstantUploadDataT< UploaderT > const &) delete
InstantUploadDataT() [2/3]
template<UploadDataT UploaderT> castor3d::InstantUploadDataT< UploaderT >::InstantUploadDataT (InstantUploadDataT< UploaderT > &&) delete noexcept
InstantUploadDataT() [3/3]
template<UploadDataT UploaderT> template<typename ... ParamsT> castor3d::InstantUploadDataT< UploaderT >::InstantUploadDataT (ashes::Queue const & queue, ParamsT &&... params) inline
~InstantUploadDataT()
template<UploadDataT UploaderT> castor3d::InstantUploadDataT< UploaderT >::~InstantUploadDataT () inline
References castor3d::UploadData::end(), castor3d::UploadData::getDevice(), castor3d::UploadData::getName(), castor3d::UploadData::process(), and castor::toUtf8().
Member Function Documentation
operator UploaderT &()
template<UploadDataT UploaderT> castor3d::InstantUploadDataT< UploaderT >::operator UploaderT & () inline
operator->()
template<UploadDataT UploaderT> UploaderT * castor3d::InstantUploadDataT< UploaderT >::operator-> () inline
operator=() [1/2]
template<UploadDataT UploaderT> InstantUploadDataT & castor3d::InstantUploadDataT< UploaderT >::operator= (InstantUploadDataT< UploaderT > &&) delete
operator=() [2/2]
template<UploadDataT UploaderT> InstantUploadDataT & castor3d::InstantUploadDataT< UploaderT >::operator= (InstantUploadDataT< UploaderT > const &) delete
The documentation for this class was generated from the following files:
Castor3D/Buffer/BufferModule.hpp
Castor3D/Buffer/InstantUploadData.hpp