Castor3D: castor3d::shader::OverlaySurfaceT< FlagT > Struct Template Reference
castor3d::shader::OverlaySurfaceT< FlagT > Struct Template Reference
#include <GlslOverlaySurface.hpp>
Public Member Functions
OverlaySurfaceT (sdw::ShaderWriter &writer, sdw::expr::ExprPtr expr, bool enabled)
OverlaySurfaceT (sdw::Vec2 const pos, sdw::Vec2 const uv)
OverlaySurfaceT (sdw::Vec2 const pos, sdw::Vec2 const uv, sdw::Vec2 const text)
SDW_DeclStructInstance (, OverlaySurfaceT)
void set (sdw::Vec2 const &pos, sdw::Vec2 const &uv)
void set (sdw::Vec2 const &pos, sdw::Vec2 const &uv, sdw::Vec2 const &text)
Static Public Member Functions
static ast::expr::ExprPtr makeInitExpr (sdw::Vec2 const pos, sdw::Vec2 const uv)
static ast::expr::ExprPtr makeInitExpr (sdw::Vec2 const pos, sdw::Vec2 const uv, sdw::Vec2 const text)
static ast::type::BaseStructPtr makeType (ast::type::TypesCache &cache, bool isTextOverlay, bool hasTextures)
static ast::type::IOStructPtr makeIOType (ast::type::TypesCache &cache, sdw::EntryPoint entryPoint, bool hasPosition, bool isTextOverlay, bool hasTextures, bool isTransition)
Public Attributes
sdw::Vec2 position
sdw::Vec2 texUV
sdw::Vec2 fontUV
sdw::UInt materialId
Constructor & Destructor Documentation
OverlaySurfaceT() [1/3]
template<ast::var::Flag FlagT> castor3d::shader::OverlaySurfaceT< FlagT >::OverlaySurfaceT (sdw::ShaderWriter & writer, sdw::expr::ExprPtr expr, bool enabled) inline
OverlaySurfaceT() [2/3]
template<ast::var::Flag FlagT> castor3d::shader::OverlaySurfaceT< FlagT >::OverlaySurfaceT (sdw::Vec2 const pos, sdw::Vec2 const uv) inline
OverlaySurfaceT() [3/3]
template<ast::var::Flag FlagT> castor3d::shader::OverlaySurfaceT< FlagT >::OverlaySurfaceT (sdw::Vec2 const pos, sdw::Vec2 const uv, sdw::Vec2 const text) inline
Member Function Documentation
makeInitExpr() [1/2]
template<ast::var::Flag FlagT> static ast::expr::ExprPtr castor3d::shader::OverlaySurfaceT< FlagT >::makeInitExpr (sdw::Vec2 const pos, sdw::Vec2 const uv) inline static
References castor3d::shader::OverlaySurfaceT< FlagT >::makeType().
makeInitExpr() [2/2]
template<ast::var::Flag FlagT> static ast::expr::ExprPtr castor3d::shader::OverlaySurfaceT< FlagT >::makeInitExpr (sdw::Vec2 const pos, sdw::Vec2 const uv, sdw::Vec2 const text) inline static
References castor3d::shader::OverlaySurfaceT< FlagT >::makeType().
makeIOType()
template<ast::var::Flag FlagT> static ast::type::IOStructPtr castor3d::shader::OverlaySurfaceT< FlagT >::makeIOType (ast::type::TypesCache & cache, sdw::EntryPoint entryPoint, bool hasPosition, bool isTextOverlay, bool hasTextures, bool isTransition) inline static
makeType()
template<ast::var::Flag FlagT> static ast::type::BaseStructPtr castor3d::shader::OverlaySurfaceT< FlagT >::makeType (ast::type::TypesCache & cache, bool isTextOverlay, bool hasTextures) inline static
Referenced by castor3d::shader::OverlaySurfaceT< FlagT >::makeInitExpr(), and castor3d::shader::OverlaySurfaceT< FlagT >::makeInitExpr().
SDW_DeclStructInstance()
template<ast::var::Flag FlagT> castor3d::shader::OverlaySurfaceT< FlagT >::SDW_DeclStructInstance (OverlaySurfaceT< FlagT >)
set() [1/2]
template<ast::var::Flag FlagT> void castor3d::shader::OverlaySurfaceT< FlagT >::set (sdw::Vec2 const & pos, sdw::Vec2 const & uv) inline
References castor3d::shader::OverlaySurfaceT< FlagT >::position, and castor3d::shader::OverlaySurfaceT< FlagT >::texUV.
set() [2/2]
template<ast::var::Flag FlagT> void castor3d::shader::OverlaySurfaceT< FlagT >::set (sdw::Vec2 const & pos, sdw::Vec2 const & uv, sdw::Vec2 const & text) inline
References castor3d::shader::OverlaySurfaceT< FlagT >::fontUV, castor3d::shader::OverlaySurfaceT< FlagT >::position, and castor3d::shader::OverlaySurfaceT< FlagT >::texUV.
Member Data Documentation
fontUV
template<ast::var::Flag FlagT> sdw::Vec2 castor3d::shader::OverlaySurfaceT< FlagT >::fontUV
Referenced by castor3d::shader::OverlaySurfaceT< FlagT >::set().
materialId
template<ast::var::Flag FlagT> sdw::UInt castor3d::shader::OverlaySurfaceT< FlagT >::materialId
position
template<ast::var::Flag FlagT> sdw::Vec2 castor3d::shader::OverlaySurfaceT< FlagT >::position
Referenced by castor3d::shader::OverlaySurfaceT< FlagT >::set(), and castor3d::shader::OverlaySurfaceT< FlagT >::set().
texUV
template<ast::var::Flag FlagT> sdw::Vec2 castor3d::shader::OverlaySurfaceT< FlagT >::texUV
Referenced by castor3d::shader::OverlaySurfaceT< FlagT >::set(), and castor3d::shader::OverlaySurfaceT< FlagT >::set().
The documentation for this struct was generated from the following file:
Castor3D/Shader/Shaders/GlslOverlaySurface.hpp