Castor3D: castor3d::OpaqueRendering Class Reference
castor3d::OpaqueRendering Class Reference
#include <OpaqueRendering.hpp>
Public Types
using ShadowMapArray = castor::Vector< ShadowMapUPtr >
Public Member Functions
C3D_API OpaqueRendering (RenderTechnique &parent, RenderDevice const &device, PrepassRendering const &previous, crg::FramePassArray const &previousPasses, ProgressBar *progress)
Constructor.
C3D_API void listIntermediates (castor::Vector< IntermediateView > &intermediates)
Lists the intermediate view used by the whole technique.
C3D_API void update (CpuUpdater &updater)
Updates the render pass, CPU wise.
C3D_API void update (GpuUpdater &updater) const
Updates the render pass, GPU wise.
C3D_API void accept (RenderTechniqueVisitor &visitor)
Visitor acceptance function.
C3D_API Engine * getEngine () const noexcept
C3D_API crg::FramePass const & getLastPass () const noexcept
C3D_API Texture const & getSsaoResult () const noexcept
C3D_API Texture const & getSssDiffuse () const noexcept
C3D_API bool isEnabled () const noexcept
ashes::Buffer< uint32_t > const & getMaterialsCounts () const noexcept
ashes::Buffer< castor::Point3ui > const & getMaterialsIndirectCounts () const noexcept
ashes::Buffer< uint32_t > const & getMaterialsStarts () const noexcept
ashes::Buffer< castor::Point2ui > const & getPixelXY () const noexcept
Public Member Functions inherited from castor::OwnedBy< RenderTechnique >
RenderTechnique * getOwner () const
Static Public Member Functions
static uint32_t countInitialisationSteps () noexcept
Additional Inherited Members
Protected Member Functions inherited from castor::OwnedBy< RenderTechnique >
OwnedBy (RenderTechnique &owner)
Constructor.
Member Typedef Documentation
ShadowMapArray
using castor3d::OpaqueRendering::ShadowMapArray = castor::Vector< ShadowMapUPtr >
Constructor & Destructor Documentation
OpaqueRendering()
C3D_API castor3d::OpaqueRendering::OpaqueRendering (RenderTechnique & parent, RenderDevice const & device, PrepassRendering const & previous, crg::FramePassArray const & previousPasses, ProgressBar * progress)
Constructor.
Parameters
[in] parent The parent technique.
[in] device The GPU device.
[in] previous The prepass renderer.
[in] previousPasses The passes this pass depends on.
[in] progress The optional progress bar.
Member Function Documentation
accept()
C3D_API void castor3d::OpaqueRendering::accept (RenderTechniqueVisitor & visitor)
Visitor acceptance function.
Parameters
visitor The ... visitor.
countInitialisationSteps()
static uint32_t castor3d::OpaqueRendering::countInitialisationSteps () static noexcept
Returns
The number of steps needed for initialisation, to show progression.
getEngine()
C3D_API Engine * castor3d::OpaqueRendering::getEngine () const noexcept
name Getters.
getLastPass()
C3D_API crg::FramePass const & castor3d::OpaqueRendering::getLastPass () const noexcept
getMaterialsCounts()
ashes::Buffer< uint32_t > const & castor3d::OpaqueRendering::getMaterialsCounts () const inline noexcept
Referenced by castor3d::RenderTechnique::getMaterialsCounts().
getMaterialsIndirectCounts()
ashes::Buffer< castor::Point3ui > const & castor3d::OpaqueRendering::getMaterialsIndirectCounts () const inline noexcept
Referenced by castor3d::RenderTechnique::getMaterialsIndirectCounts().
getMaterialsStarts()
ashes::Buffer< uint32_t > const & castor3d::OpaqueRendering::getMaterialsStarts () const inline noexcept
Referenced by castor3d::RenderTechnique::getMaterialsStarts().
getPixelXY()
ashes::Buffer< castor::Point2ui > const & castor3d::OpaqueRendering::getPixelXY () const inline noexcept
Referenced by castor3d::RenderTechnique::getPixelXY().
getSsaoResult()
C3D_API Texture const & castor3d::OpaqueRendering::getSsaoResult () const noexcept
getSssDiffuse()
C3D_API Texture const & castor3d::OpaqueRendering::getSssDiffuse () const noexcept
isEnabled()
C3D_API bool castor3d::OpaqueRendering::isEnabled () const noexcept
listIntermediates()
C3D_API void castor3d::OpaqueRendering::listIntermediates (castor::Vector< IntermediateView > & intermediates)
Lists the intermediate view used by the whole technique.
Parameters
[out] intermediates Receives the intermediate views.
update() [1/2]
C3D_API void castor3d::OpaqueRendering::update (CpuUpdater & updater)
Updates the render pass, CPU wise.
Parameters
[in,out] updater The update data.
update() [2/2]
C3D_API void castor3d::OpaqueRendering::update (GpuUpdater & updater) const
Updates the render pass, GPU wise.
Parameters
[in,out] updater The update data.
The documentation for this class was generated from the following file:
Castor3D/Render/Opaque/OpaqueRendering.hpp