Castor3D: castor3d::Layout Class Reference
castor3d::Layout Class Reference abstract
#include <Layout.hpp>
Classes
struct Item
Public Member Functions
General
C3D_API Layout (Layout const &) noexcept=delete
C3D_API Layout & operator= (Layout const &) noexcept=delete
C3D_API Layout (Layout &&) noexcept=delete
C3D_API Layout & operator= (Layout &&) noexcept=delete
virtual C3D_API ~Layout () noexcept
C3D_API Layout (castor::String const &typeName, ControlsManager &manager)
C3D_API Layout (castor::String const &typeName, LayoutControl &container)
C3D_API void markDirty ()
Public Member Functions inherited from castor::NamedBaseT< T >
NamedBaseT (T name) noexcept
Constructor.
T const & getName () const noexcept
Retrieves the name.
void rename (T name) noexcept
Controls management
ControlsManager * m_manager {}
LayoutControl * m_container {}
castor::Vector< Item > m_items
castor::Vector< SpacerUPtr > m_spacers
CpuFrameEvent * m_event {}
std::atomic_bool m_updating { false }
C3D_API void addControl (Control &control, LayoutItemFlags flags={})
C3D_API void removeControl (Control const &control, bool checkPresent=true)
C3D_API void addSpacer (uint32_t size=Spacer::Dynamic)
bool hasManager () const noexcept
ControlsManager & getManager () const noexcept
bool hasContainer () const noexcept
LayoutControl & getContainer () const noexcept
auto begin () const noexcept
auto end () const noexcept
C3D_API void update ()
Additional Inherited Members
Protected Attributes inherited from castor::NamedBaseT< T >
T m_name
Constructor & Destructor Documentation
Layout() [1/4]
C3D_API castor3d::Layout::Layout (Layout const &) delete noexcept
Layout() [2/4]
C3D_API castor3d::Layout::Layout (Layout &&) delete noexcept
~Layout()
virtual C3D_API castor3d::Layout::~Layout () virtual noexcept
Layout() [3/4]
C3D_API castor3d::Layout::Layout (castor::String const & typeName, ControlsManager & manager) explicit
Constructor for global layout
Parameters
[in] typeName The layout type name.
[in] manager The parent controls manager.
Layout() [4/4]
C3D_API castor3d::Layout::Layout (castor::String const & typeName, LayoutControl & container) explicit
Constructor
Parameters
[in] typeName The layout type name.
[in] container The parent layout control.
Member Function Documentation
addControl()
C3D_API void castor3d::Layout::addControl (Control & control, LayoutItemFlags flags = {})
Adds a control.
Parameters
[in] control The control.
[in] flags The layout flags for the control.
addSpacer()
C3D_API void castor3d::Layout::addSpacer (uint32_t size = Spacer::Dynamic)
Adds a space.
Parameters
[in] size The space size
begin()
auto castor3d::Layout::begin () const inline noexcept
References m_items.
end()
auto castor3d::Layout::end () const inline noexcept
References m_items.
getContainer()
LayoutControl & castor3d::Layout::getContainer () const inline noexcept
References CU_Require, hasContainer(), and m_container.
getManager()
ControlsManager & castor3d::Layout::getManager () const inline noexcept
References CU_Require, hasManager(), and m_manager.
hasContainer()
bool castor3d::Layout::hasContainer () const inline noexcept
References m_container.
Referenced by getContainer().
hasManager()
bool castor3d::Layout::hasManager () const inline noexcept
References m_manager.
Referenced by getManager().
markDirty()
C3D_API void castor3d::Layout::markDirty ()
Marks the layout as dirty.
Referenced by castor3d::LayoutBox::setHorizontal().
operator=() [1/2]
C3D_API Layout & castor3d::Layout::operator= (Layout &&) delete noexcept
operator=() [2/2]
C3D_API Layout & castor3d::Layout::operator= (Layout const &) delete noexcept
removeControl()
C3D_API void castor3d::Layout::removeControl (Control const & control, bool checkPresent = true)
Removes a control.
Parameters
[in] control The control.
[in] checkPresent true to log a warning if not found.
update()
C3D_API void castor3d::Layout::update () protected
Updates the layout and its controls.
Member Data Documentation
m_container
LayoutControl* castor3d::Layout::m_container {} protected
Referenced by getContainer(), and hasContainer().
m_event
CpuFrameEvent* castor3d::Layout::m_event {} protected
m_items
castor::Vector< Item > castor3d::Layout::m_items protected
Referenced by begin(), and end().
m_manager
ControlsManager* castor3d::Layout::m_manager {} protected
Referenced by getManager(), and hasManager().
m_spacers
castor::Vector< SpacerUPtr > castor3d::Layout::m_spacers protected
m_updating
std::atomic_bool castor3d::Layout::m_updating { false } protected
The documentation for this class was generated from the following file:
Castor3D/Gui/Layout/Layout.hpp