Castor3D: Castor3D::ChunkWriterBase Class Reference
Castor3D::ChunkWriterBase Class Reference
Chunk writer.
Static Public Member Functions
static bool Write (uint8_t const *p_begin, uint8_t const *p_end, ChunkType p_type, BinaryChunk &p_chunk)
Writes a subchunk value into a chunk.
Detailed Description
Chunk writer.
Author
Sylvain DOREMUS
Version
0.9.0
Date
30/05/2016
Member Function Documentation
Write()
static bool Castor3D::ChunkWriterBase::Write (uint8_t const * p_begin, uint8_t const * p_end, ChunkType p_type, BinaryChunk & p_chunk) inline static
Writes a subchunk value into a chunk.
Parameters
[in] p_begin The values begin
[in] p_end The values end
[in] p_type The subchunk type
[in] p_chunk The chunk
Returns
false if any error occured
References Castor3D::BinaryChunk::AddSubChunk(), and Castor3D::BinaryChunk::SetData().
Referenced by Castor3D::ChunkWriter< T >::Write(), Castor3D::ChunkWriter< Castor::String >::Write(), and Castor3D::ChunkWriter< Castor::Path >::Write().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Binary/ChunkWriter.hpp