Castor3D: castor3d::shader::BufferT< DataT > Class Template Reference
castor3d::shader::BufferT< DataT > Class Template Reference
#include <GlslBuffer.hpp>
Public Member Functions
template<typename ... ParamsT>
BufferT (sdw::ShaderWriter &writer, castor::MbString blockName, castor::MbString variableName, uint32_t binding, uint32_t set, bool enabled=true, ParamsT &&... params)
template<typename ... ParamsT>
DataT getData (sdw::UInt const &index, ParamsT &&... params) const
Public Member Functions inherited from castor3d::shader::BufferBase
BufferBase (sdw::ShaderWriter &writer, castor::MbString blockName, castor::MbString variableName, uint32_t binding, uint32_t set, bool enabled=true)
sdw::UInt getFirstCount () const
sdw::UInt getSecondCount () const
sdw::UInt getThirdCount () const
sdw::UInt getFourthCount () const
sdw::UInt getCount () const
bool isEnabled () const noexcept
sdw::ShaderWriter * getWriter () const noexcept
Additional Inherited Members
Protected Attributes inherited from castor3d::shader::BufferBase
sdw::ShaderWriter & m_writer
castor::RawUniquePtr< sdw::StorageBuffer > m_ssbo
castor::MbString m_variableName
Constructor & Destructor Documentation
BufferT()
template<typename DataT > template<typename ... ParamsT> castor3d::shader::BufferT< DataT >::BufferT (sdw::ShaderWriter & writer, castor::MbString blockName, castor::MbString variableName, uint32_t binding, uint32_t set, bool enabled = true, ParamsT &&... params) inline
References castor3d::shader::BufferBase::isEnabled(), and castor3d::shader::BufferBase::m_ssbo.
Member Function Documentation
getData()
template<typename DataT > template<typename ... ParamsT> DataT castor3d::shader::BufferT< DataT >::getData (sdw::UInt const & index, ParamsT &&... params) const inline
References castor3d::shader::BufferBase::isEnabled(), castor3d::shader::BufferBase::m_ssbo, castor3d::shader::BufferBase::m_variableName, and castor3d::shader::BufferBase::m_writer.
Referenced by castor3d::shader::SssProfiles::getProfile(), castor3d::shader::TextureAnimations::getTextureAnimation(), and castor3d::shader::TextureConfigurations::getTextureConfiguration().
The documentation for this class was generated from the following file:
Castor3D/Shader/Shaders/GlslBuffer.hpp