Castor3D: castor3d::LayoutItemFlags Struct Reference
castor3d::LayoutItemFlags Struct Reference
#include <LayoutItemFlags.hpp>
Public Member Functions
LayoutItemFlags & align (HAlign v) noexcept
LayoutItemFlags & align (VAlign v) noexcept
LayoutItemFlags & centerHorizontal () noexcept
LayoutItemFlags & centerVertical () noexcept
LayoutItemFlags & top () noexcept
LayoutItemFlags & bottom () noexcept
LayoutItemFlags & left () noexcept
LayoutItemFlags & right () noexcept
LayoutItemFlags & stretch (bool v) noexcept
LayoutItemFlags & reserveSpaceIfHidden (bool v) noexcept
LayoutItemFlags & padding (castor::Point4ui v) noexcept
LayoutItemFlags & padLeft (uint32_t v) noexcept
LayoutItemFlags & padTop (uint32_t v) noexcept
LayoutItemFlags & padRight (uint32_t v) noexcept
LayoutItemFlags & padBottom (uint32_t v) noexcept
auto hAlign () const noexcept
auto vAlign () const noexcept
auto expand () const noexcept
auto reserveSpaceIfHidden () const noexcept
castor::Point4ui padding () const noexcept
uint32_t padding (uint32_t i) const noexcept
uint32_t paddingSize (uint32_t i) const noexcept
Member Function Documentation
align() [1/2]
LayoutItemFlags & castor3d::LayoutItemFlags::align (HAlign v) inline noexcept
Referenced by bottom(), centerHorizontal(), centerVertical(), left(), right(), and top().
align() [2/2]
LayoutItemFlags & castor3d::LayoutItemFlags::align (VAlign v) inline noexcept
bottom()
LayoutItemFlags & castor3d::LayoutItemFlags::bottom () inline noexcept
References align(), and castor3d::eBottom.
centerHorizontal()
LayoutItemFlags & castor3d::LayoutItemFlags::centerHorizontal () inline noexcept
References align(), and castor3d::eCenter.
centerVertical()
LayoutItemFlags & castor3d::LayoutItemFlags::centerVertical () inline noexcept
References align(), and castor3d::eCenter.
expand()
auto castor3d::LayoutItemFlags::expand () const inline noexcept
hAlign()
auto castor3d::LayoutItemFlags::hAlign () const inline noexcept
left()
LayoutItemFlags & castor3d::LayoutItemFlags::left () inline noexcept
References align(), and castor3d::eLeft.
padBottom()
LayoutItemFlags & castor3d::LayoutItemFlags::padBottom (uint32_t v) inline noexcept
padding() [1/3]
castor::Point4ui castor3d::LayoutItemFlags::padding () const inline noexcept
padding() [2/3]
LayoutItemFlags & castor3d::LayoutItemFlags::padding (castor::Point4ui v) inline noexcept
padding() [3/3]
uint32_t castor3d::LayoutItemFlags::padding (uint32_t i) const inline noexcept
paddingSize()
uint32_t castor3d::LayoutItemFlags::paddingSize (uint32_t i) const inline noexcept
padLeft()
LayoutItemFlags & castor3d::LayoutItemFlags::padLeft (uint32_t v) inline noexcept
padRight()
LayoutItemFlags & castor3d::LayoutItemFlags::padRight (uint32_t v) inline noexcept
padTop()
LayoutItemFlags & castor3d::LayoutItemFlags::padTop (uint32_t v) inline noexcept
reserveSpaceIfHidden() [1/2]
auto castor3d::LayoutItemFlags::reserveSpaceIfHidden () const inline noexcept
reserveSpaceIfHidden() [2/2]
LayoutItemFlags & castor3d::LayoutItemFlags::reserveSpaceIfHidden (bool v) inline noexcept
right()
LayoutItemFlags & castor3d::LayoutItemFlags::right () inline noexcept
References align(), and castor3d::eRight.
stretch()
LayoutItemFlags & castor3d::LayoutItemFlags::stretch (bool v) inline noexcept
top()
LayoutItemFlags & castor3d::LayoutItemFlags::top () inline noexcept
References align(), and castor3d::eTop.
vAlign()
auto castor3d::LayoutItemFlags::vAlign () const inline noexcept
The documentation for this struct was generated from the following file:
Castor3D/Gui/Layout/LayoutItemFlags.hpp