Castor3D: castor3d::TextureSourceInfo Class Reference
castor3d::TextureSourceInfo Class Reference
#include <TextureSourceInfo.hpp>
Public Member Functions
C3D_API TextureSourceInfo () noexcept=default
C3D_API TextureSourceInfo (TextureSourceInfo const &rhs, TextureConfiguration textureConfig)
C3D_API TextureSourceInfo (castor::String name, TextureConfiguration textureConfig, castor::Path folder, castor::Path relative, castor::ImageLoaderConfig loadConfig={ true, true, true })
C3D_API TextureSourceInfo (castor::String name, TextureConfiguration textureConfig, castor::String type, castor::ByteArray data, castor::ImageLoaderConfig loadConfig={ true, true, true })
C3D_API TextureSourceInfo (castor::String name, TextureConfiguration textureConfig, RenderTargetRPtr renderTarget)
C3D_API TextureSourceInfo (castor::String name, TextureConfiguration textureConfig, ashes::ImageCreateInfo const &createInfo)
bool isSerialisable () const noexcept
bool isRenderTarget () const noexcept
bool isFileImage () const noexcept
bool isBufferImage () const noexcept
bool isVulkanImage () const noexcept
TextureConfiguration const & textureConfig () const noexcept
RenderTargetRPtr renderTarget () const noexcept
castor::Path const & folder () const noexcept
castor::Path const & relative () const noexcept
castor::String name () const noexcept
castor::String const & type () const noexcept
castor::ByteArray const & buffer () const noexcept
bool allowCompression () const noexcept
void allowCompression (bool v) noexcept
bool allowSRGB () const noexcept
void allowSRGB (bool v) noexcept
bool generateMips () const noexcept
bool layersToTiles () const noexcept
castor::ImageLoaderConfig const & loadConfig () const noexcept
ashes::ImageCreateInfo const & createInfo () const noexcept
void setBuffer (castor::ByteArray data) noexcept
void setSerialisable (bool v) noexcept
Constructor & Destructor Documentation
TextureSourceInfo() [1/6]
C3D_API castor3d::TextureSourceInfo::TextureSourceInfo () default noexcept
TextureSourceInfo() [2/6]
C3D_API castor3d::TextureSourceInfo::TextureSourceInfo (TextureSourceInfo const & rhs, TextureConfiguration textureConfig)
TextureSourceInfo() [3/6]
C3D_API castor3d::TextureSourceInfo::TextureSourceInfo (castor::String name, TextureConfiguration textureConfig, castor::Path folder, castor::Path relative, castor::ImageLoaderConfig loadConfig = { true, true, true })
TextureSourceInfo() [4/6]
C3D_API castor3d::TextureSourceInfo::TextureSourceInfo (castor::String name, TextureConfiguration textureConfig, castor::String type, castor::ByteArray data, castor::ImageLoaderConfig loadConfig = { true, true, true })
TextureSourceInfo() [5/6]
C3D_API castor3d::TextureSourceInfo::TextureSourceInfo (castor::String name, TextureConfiguration textureConfig, RenderTargetRPtr renderTarget)
TextureSourceInfo() [6/6]
C3D_API castor3d::TextureSourceInfo::TextureSourceInfo (castor::String name, TextureConfiguration textureConfig, ashes::ImageCreateInfo const & createInfo)
Member Function Documentation
allowCompression() [1/2]
bool castor3d::TextureSourceInfo::allowCompression () const inline noexcept
References castor::ImageLoaderConfig::allowCompression, CU_Require, isBufferImage(), and isFileImage().
allowCompression() [2/2]
void castor3d::TextureSourceInfo::allowCompression (bool v) inline noexcept
References castor::ImageLoaderConfig::allowCompression, CU_Require, isBufferImage(), and isFileImage().
allowSRGB() [1/2]
bool castor3d::TextureSourceInfo::allowSRGB () const inline noexcept
References castor::ImageLoaderConfig::allowSRGB.
allowSRGB() [2/2]
void castor3d::TextureSourceInfo::allowSRGB (bool v) inline noexcept
References castor::ImageLoaderConfig::allowSRGB.
buffer()
castor::ByteArray const & castor3d::TextureSourceInfo::buffer () const inline noexcept
References CU_Require, and isBufferImage().
createInfo()
ashes::ImageCreateInfo const & castor3d::TextureSourceInfo::createInfo () const inline noexcept
References CU_Require, and isVulkanImage().
folder()
castor::Path const & castor3d::TextureSourceInfo::folder () const inline noexcept
References CU_Require, and isFileImage().
generateMips()
bool castor3d::TextureSourceInfo::generateMips () const inline noexcept
References CU_Require, castor::ImageLoaderConfig::generateMips, isBufferImage(), and isFileImage().
isBufferImage()
bool castor3d::TextureSourceInfo::isBufferImage () const inline noexcept
Referenced by allowCompression(), allowCompression(), buffer(), generateMips(), layersToTiles(), loadConfig(), and type().
isFileImage()
bool castor3d::TextureSourceInfo::isFileImage () const inline noexcept
Referenced by allowCompression(), allowCompression(), folder(), generateMips(), layersToTiles(), loadConfig(), and relative().
isRenderTarget()
bool castor3d::TextureSourceInfo::isRenderTarget () const inline noexcept
Referenced by castor3d::TextureUnit::isRenderTarget(), renderTarget(), and setBuffer().
isSerialisable()
bool castor3d::TextureSourceInfo::isSerialisable () const inline noexcept
isVulkanImage()
bool castor3d::TextureSourceInfo::isVulkanImage () const inline noexcept
Referenced by createInfo().
layersToTiles()
bool castor3d::TextureSourceInfo::layersToTiles () const inline noexcept
References CU_Require, isBufferImage(), isFileImage(), and castor::ImageLoaderConfig::layersToTiles.
loadConfig()
castor::ImageLoaderConfig const & castor3d::TextureSourceInfo::loadConfig () const inline noexcept
References CU_Require, isBufferImage(), and isFileImage().
name()
castor::String castor3d::TextureSourceInfo::name () const inline noexcept
relative()
castor::Path const & castor3d::TextureSourceInfo::relative () const inline noexcept
References CU_Require, and isFileImage().
renderTarget()
RenderTargetRPtr castor3d::TextureSourceInfo::renderTarget () const inline noexcept
References CU_Require, and isRenderTarget().
setBuffer()
void castor3d::TextureSourceInfo::setBuffer (castor::ByteArray data) inline noexcept
References CU_Require, and isRenderTarget().
setSerialisable()
void castor3d::TextureSourceInfo::setSerialisable (bool v) inline noexcept
textureConfig()
TextureConfiguration const & castor3d::TextureSourceInfo::textureConfig () const inline noexcept
type()
castor::String const & castor3d::TextureSourceInfo::type () const inline noexcept
References CU_Require, and isBufferImage().
The documentation for this class was generated from the following file:
Castor3D/Material/Texture/TextureSourceInfo.hpp