Castor3D: castor3d::ShaderBuffer Class Reference
castor3d::ShaderBuffer Class Reference
Public Member Functions
C3D_API ShaderBuffer (Engine &engine, RenderDevice const &device, uint32_t size, castor::String name, VkFormat tboFormat=VK_FORMAT_R32G32B32A32_SFLOAT)
Constructor.
C3D_API ~ShaderBuffer ()
Destructor.
C3D_API void update ()
Updates the buffer.
C3D_API void update (VkDeviceSize offset, VkDeviceSize size)
Updates the buffer on GPU.
C3D_API VkDescriptorSetLayoutBinding createLayoutBinding (uint32_t index=0u) const
Creates the descriptor set layout binding at given point.
C3D_API ashes::WriteDescriptorSet getBinding (uint32_t binding) const
Creates the descriptor write for this buffer.
C3D_API void createBinding (ashes::DescriptorSet &descriptorSet, VkDescriptorSetLayoutBinding const &binding) const
Creates the descriptor set binding at given point.
uint8_t * getPtr ()
VkDeviceSize getSize ()
VkDescriptorType getType () const
Constructor & Destructor Documentation
ShaderBuffer()
C3D_API castor3d::ShaderBuffer::ShaderBuffer (Engine & engine, RenderDevice const & device, uint32_t size, castor::String name, VkFormat tboFormat = VK_FORMAT_R32G32B32A32_SFLOAT)
Constructor.
Parameters
[in] engine The engine.
[in] device The GPU device.
[in] size The buffer size.
[in] name The shader buffer name.
[in] tboFormat The format wanted for the TBO.
~ShaderBuffer()
C3D_API castor3d::ShaderBuffer::~ShaderBuffer ()
Destructor.
Member Function Documentation
createBinding()
C3D_API void castor3d::ShaderBuffer::createBinding (ashes::DescriptorSet & descriptorSet, VkDescriptorSetLayoutBinding const & binding) const
Creates the descriptor set binding at given point.
Parameters
[in,out] descriptorSet Receives the created binding.
[in] binding The descriptor set layout binding.
createLayoutBinding()
C3D_API VkDescriptorSetLayoutBinding castor3d::ShaderBuffer::createLayoutBinding (uint32_t index = 0u) const
Creates the descriptor set layout binding at given point.
Parameters
[in] index The binding point index.
getBinding()
C3D_API ashes::WriteDescriptorSet castor3d::ShaderBuffer::getBinding (uint32_t binding) const
Creates the descriptor write for this buffer.
Parameters
[in] binding The descriptor set layout binding.
getPtr()
uint8_t* castor3d::ShaderBuffer::getPtr () inline
Returns
The pointer to the buffer.
Referenced by castor3d::TextureConfigurationBuffer::getPtr(), and castor3d::PassBuffer::getPtr().
getSize()
VkDeviceSize castor3d::ShaderBuffer::getSize () inline
Returns
The buffer size.
getType()
VkDescriptorType castor3d::ShaderBuffer::getType () const inline
Returns
The buffer descriptor type.
Referenced by castor3d::PassBuffer::getType().
update() [1/2]
C3D_API void castor3d::ShaderBuffer::update ()
Updates the buffer.
update() [2/2]
C3D_API void castor3d::ShaderBuffer::update (VkDeviceSize offset, VkDeviceSize size)
Updates the buffer on GPU.
Parameters
[in] offset The starting offset.
[in] size The update range.
The documentation for this class was generated from the following file:
Shader/ShaderBuffer.hpp