Castor3D: castor3d::InstantiatedBuffersNodesViewT< NodeT > Struct Template Reference
castor3d::InstantiatedBuffersNodesViewT< NodeT > Struct Template Reference
#include <InstantiatedPipelinesNodes.hpp>
Classes
struct BufferNodes
Public Types
using RenderedNode = RenderedNodeT< NodeT >
using NodesView = InstantiatedObjectsNodesViewT< NodeT >
Public Member Functions
auto emplace (ashes::BufferBase const &buffer)
void emplace (ashes::BufferBase const &buffer, RenderedNode node)
void clear () noexcept
auto begin () noexcept
auto begin () const noexcept
auto end () noexcept
auto end () const noexcept
auto size () const noexcept
auto empty () const noexcept
size_t occupancy () const noexcept
Static Public Attributes
static uint64_t constexpr maxBuffers = BuffersNodesViewT< NodeT >::maxBuffers
static uint64_t constexpr maxCount = NodesView::maxCount * maxBuffers
Member Typedef Documentation
NodesView
template<typename NodeT > using castor3d::InstantiatedBuffersNodesViewT< NodeT >::NodesView = InstantiatedObjectsNodesViewT< NodeT >
RenderedNode
template<typename NodeT > using castor3d::InstantiatedBuffersNodesViewT< NodeT >::RenderedNode = RenderedNodeT< NodeT >
Member Function Documentation
begin() [1/2]
template<typename NodeT > auto castor3d::InstantiatedBuffersNodesViewT< NodeT >::begin () const inline noexcept
begin() [2/2]
template<typename NodeT > auto castor3d::InstantiatedBuffersNodesViewT< NodeT >::begin () inline noexcept
Referenced by castor3d::InstantiatedBuffersNodesViewT< NodeT >::emplace().
clear()
template<typename NodeT > void castor3d::InstantiatedBuffersNodesViewT< NodeT >::clear () inline noexcept
emplace() [1/2]
template<typename NodeT > auto castor3d::InstantiatedBuffersNodesViewT< NodeT >::emplace (ashes::BufferBase const & buffer) inline
References castor3d::InstantiatedBuffersNodesViewT< NodeT >::begin(), castor3d::C3D_EnsureNodesCounts, CU_Assert, CU_Exception, castor3d::InstantiatedBuffersNodesViewT< NodeT >::end(), castor3d::InstantiatedBuffersNodesViewT< NodeT >::maxBuffers, and castor3d::InstantiatedBuffersNodesViewT< NodeT >::size().
Referenced by castor3d::InstantiatedBuffersNodesViewT< NodeT >::emplace().
emplace() [2/2]
template<typename NodeT > void castor3d::InstantiatedBuffersNodesViewT< NodeT >::emplace (ashes::BufferBase const & buffer, RenderedNode node) inline
References castor3d::InstantiatedBuffersNodesViewT< NodeT >::emplace().
empty()
template<typename NodeT > auto castor3d::InstantiatedBuffersNodesViewT< NodeT >::empty () const inline noexcept
end() [1/2]
template<typename NodeT > auto castor3d::InstantiatedBuffersNodesViewT< NodeT >::end () const inline noexcept
end() [2/2]
template<typename NodeT > auto castor3d::InstantiatedBuffersNodesViewT< NodeT >::end () inline noexcept
Referenced by castor3d::InstantiatedBuffersNodesViewT< NodeT >::emplace().
occupancy()
template<typename NodeT > size_t castor3d::InstantiatedBuffersNodesViewT< NodeT >::occupancy () const inline noexcept
References castor3d::InstantiatedBuffersNodesViewT< NodeT >::size().
size()
template<typename NodeT > auto castor3d::InstantiatedBuffersNodesViewT< NodeT >::size () const inline noexcept
Referenced by castor3d::InstantiatedBuffersNodesViewT< NodeT >::emplace(), and castor3d::InstantiatedBuffersNodesViewT< NodeT >::occupancy().
Member Data Documentation
maxBuffers
template<typename NodeT > uint64_t constexpr castor3d::InstantiatedBuffersNodesViewT< NodeT >::maxBuffers = BuffersNodesViewT< NodeT >::maxBuffers static constexpr
Referenced by castor3d::InstantiatedBuffersNodesViewT< NodeT >::emplace().
maxCount
template<typename NodeT > uint64_t constexpr castor3d::InstantiatedBuffersNodesViewT< NodeT >::maxCount = NodesView::maxCount * maxBuffers static constexpr
The documentation for this struct was generated from the following file:
Castor3D/Render/Node/InstantiatedPipelinesNodes.hpp