Castor3D: Castor3D::EventHandler Class Reference
Castor3D::EventHandler Class Reference abstract
Description of an event handler, class that can receive event.
Public Types
using ClientMouseFunction = std::function< void(MouseEvent const &) >
using ClientKeyboardFunction = std::function< void(KeyboardEvent const &) >
using ClientHandlerFunction = std::function< void(HandlerEvent const &) >
using OnClientMouseEvent = Castor::Signal< ClientMouseFunction >
using OnClientKeyboardEvent = Castor::Signal< ClientKeyboardFunction >
using OnClientHandlerEvent = Castor::Signal< ClientHandlerFunction >
using OnClientMouseEventConnection = OnClientMouseEvent::connection
using OnClientKeyboardEventConnection = OnClientKeyboardEvent::connection
using OnClientHandlerEventConnection = OnClientHandlerEvent::connection
Public Member Functions
General
EventHandler (bool p_catchMouseEvents)
virtual ~EventHandler ()
void ProcessEvents ()
Mouse events
void PushEvent (MouseEvent const &p_event)
void Connect (MouseEventType p_event, ClientMouseFunction p_function)
Keyboard events
void PushEvent (KeyboardEvent const &p_event)
void Connect (KeyboardEventType p_event, ClientKeyboardFunction p_function)
bool CatchesMouseEvents () const
void SetCatchesMouseEvents (bool p_value)
void PushEvent (HandlerEvent const &p_event)
void Connect (HandlerEventType p_event, ClientHandlerFunction p_function)
bool CatchesTabKey () const
bool CatchesReturnKey () const
Protected Types
using EventHandlerFunction = std::function< void() >
using EventQueue = std::deque< std::pair< UserInputEventSPtr, EventHandlerFunction > >
Protected Member Functions
void ProcessMouseEvent (MouseEventSPtr p_event)
void ProcessKeyboardEvent (KeyboardEventSPtr p_event)
void ProcessHandlerEvent (HandlerEventSPtr p_event)
Protected Attributes
std::array< OnClientMouseEvent, size_t(MouseEventType::eCount) > m_mouseSlots
std::array< std::vector< OnClientMouseEventConnection >, size_t(MouseEventType::eCount) > m_mouseSlotsConnections
std::array< OnClientKeyboardEvent, size_t(KeyboardEventType::eCount) > m_keyboardSlots
std::array< std::vector< OnClientKeyboardEventConnection >, size_t(KeyboardEventType::eCount) > m_keyboardSlotsConnections
std::array< OnClientHandlerEvent, size_t(HandlerEventType::eCount) > m_handlerSlots
std::array< std::vector< OnClientHandlerEventConnection >, size_t(HandlerEventType::eCount) > m_handlerSlotsConnections
Detailed Description
Description of an event handler, class that can receive event.
Author
Sylvain DOREMUS
Date
17/04/2016
Version
0.9.0
Member Typedef Documentation
ClientHandlerFunction
using Castor3D::EventHandler::ClientHandlerFunction = std::function< void(HandlerEvent const &) >
Catcher definition for handler events.
ClientKeyboardFunction
using Castor3D::EventHandler::ClientKeyboardFunction = std::function< void(KeyboardEvent const &) >
Catcher definition for keyboard events.
ClientMouseFunction
using Castor3D::EventHandler::ClientMouseFunction = std::function< void(MouseEvent const &) >
Catcher definition for mouse events.
EventHandlerFunction
using Castor3D::EventHandler::EventHandlerFunction = std::function< void() > protected
EventQueue
using Castor3D::EventHandler::EventQueue = std::deque< std::pair< UserInputEventSPtr, EventHandlerFunction > > protected
OnClientHandlerEvent
using Castor3D::EventHandler::OnClientHandlerEvent = Castor::Signal< ClientHandlerFunction >
Handler event signal definition.
OnClientHandlerEventConnection
using Castor3D::EventHandler::OnClientHandlerEventConnection = OnClientHandlerEvent::connection
Handler event signal connection definition.
OnClientKeyboardEvent
using Castor3D::EventHandler::OnClientKeyboardEvent = Castor::Signal< ClientKeyboardFunction >
Keyboard event signal definition.
OnClientKeyboardEventConnection
using Castor3D::EventHandler::OnClientKeyboardEventConnection = OnClientKeyboardEvent::connection
Keyboard event signal connection definition.
OnClientMouseEvent
using Castor3D::EventHandler::OnClientMouseEvent = Castor::Signal< ClientMouseFunction >
Mouse event signal definition.
OnClientMouseEventConnection
using Castor3D::EventHandler::OnClientMouseEventConnection = OnClientMouseEvent::connection
Mouse event signal connection definition.
Constructor & Destructor Documentation
EventHandler()
Castor3D::EventHandler::EventHandler (bool p_catchMouseEvents) inline explicit
~EventHandler()
virtual Castor3D::EventHandler::~EventHandler () inline virtual
Member Function Documentation
CatchesMouseEvents()
bool Castor3D::EventHandler::CatchesMouseEvents () const inline
CatchesReturnKey()
bool Castor3D::EventHandler::CatchesReturnKey () const inline
CatchesTabKey()
bool Castor3D::EventHandler::CatchesTabKey () const inline
Connect() [1/3]
void Castor3D::EventHandler::Connect (MouseEventType p_event, ClientMouseFunction p_function) inline
References m_mouseSlots, and m_mouseSlotsConnections.
Connect() [2/3]
void Castor3D::EventHandler::Connect (KeyboardEventType p_event, ClientKeyboardFunction p_function) inline
References m_keyboardSlots, and m_keyboardSlotsConnections.
Connect() [3/3]
void Castor3D::EventHandler::Connect (HandlerEventType p_event, ClientHandlerFunction p_function) inline
References m_handlerSlots, and m_handlerSlotsConnections.
ProcessEvents()
void Castor3D::EventHandler::ProcessEvents () inline
ProcessHandlerEvent()
void Castor3D::EventHandler::ProcessHandlerEvent (HandlerEventSPtr p_event) inline protected
References m_handlerSlots.
Referenced by PushEvent().
ProcessKeyboardEvent()
void Castor3D::EventHandler::ProcessKeyboardEvent (KeyboardEventSPtr p_event) inline protected
References m_keyboardSlots.
Referenced by PushEvent().
ProcessMouseEvent()
void Castor3D::EventHandler::ProcessMouseEvent (MouseEventSPtr p_event) inline protected
References m_mouseSlots.
Referenced by PushEvent().
PushEvent() [1/3]
void Castor3D::EventHandler::PushEvent (MouseEvent const & p_event) inline
References ProcessMouseEvent().
PushEvent() [2/3]
void Castor3D::EventHandler::PushEvent (KeyboardEvent const & p_event) inline
References ProcessKeyboardEvent().
PushEvent() [3/3]
void Castor3D::EventHandler::PushEvent (HandlerEvent const & p_event) inline
References ProcessHandlerEvent().
SetCatchesMouseEvents()
void Castor3D::EventHandler::SetCatchesMouseEvents (bool p_value) inline
Member Data Documentation
m_handlerSlots
std::array< OnClientHandlerEvent, size_t(HandlerEventType::eCount) > Castor3D::EventHandler::m_handlerSlots protected
The keyboard events slots.
Referenced by Connect(), and ProcessHandlerEvent().
m_handlerSlotsConnections
std::array< std::vector< OnClientHandlerEventConnection >, size_t(HandlerEventType::eCount) > Castor3D::EventHandler::m_handlerSlotsConnections protected
The handler events slots connections.
Referenced by Connect().
m_keyboardSlots
std::array< OnClientKeyboardEvent, size_t(KeyboardEventType::eCount) > Castor3D::EventHandler::m_keyboardSlots protected
The keyboard events slots.
Referenced by Connect(), and ProcessKeyboardEvent().
m_keyboardSlotsConnections
std::array< std::vector< OnClientKeyboardEventConnection >, size_t(KeyboardEventType::eCount) > Castor3D::EventHandler::m_keyboardSlotsConnections protected
The handler events slots connections.
Referenced by Connect().
m_mouseSlots
std::array< OnClientMouseEvent, size_t(MouseEventType::eCount) > Castor3D::EventHandler::m_mouseSlots protected
The mouse events slots.
Referenced by Connect(), and ProcessMouseEvent().
m_mouseSlotsConnections
std::array< std::vector< OnClientMouseEventConnection >, size_t(MouseEventType::eCount) > Castor3D::EventHandler::m_mouseSlotsConnections protected
The mouse events slots connections.
Referenced by Connect().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Event/UserInput/EventHandler.hpp