Castor3D: castor3d::Engine Class Reference
castor3d::Engine Class Reference
#include <Engine.hpp>
Public Member Functions
C3D_API Engine (EngineConfig config)
Constructor.
C3D_API Engine (EngineConfig config, castor::LoggerInstance &logger)
Constructor.
C3D_API ~Engine () noexcept
Destructor.
C3D_API void initialise (uint32_t wantedFPS=100, bool threaded=false)
Initialisation function, Sets the wanted frame rate.
C3D_API void cleanup ()
Cleanup function, destroys everything created from the beginning.
C3D_API bool loadRenderer (castor::String const &type)
Loads a renderer plug-in, given the renderer type.
C3D_API void loadRenderer (Renderer renderer)
Loads a renderer plug-in, given the renderer type.
C3D_API CpuFrameEvent * postEvent (CpuFrameEventUPtr event) const
Posts a frame event to the default frame listener.
C3D_API void sendEvent (GpuFrameEventUPtr event) const
If a device is enabled, executes the given event, if not posts it to the default frame listener.
C3D_API GpuFrameEvent * postEvent (GpuFrameEventUPtr event) const
Posts a frame event to the default frame listener.
C3D_API bool fireMouseMove (castor::Position const &position, bool ctrl, bool alt, bool shift)
Fires a mouse move event.
C3D_API void update (CpuUpdater &updater)
Updates the engine, CPU wise.
C3D_API void update (GpuUpdater &updater)
Updates the engine, GPU wise.
C3D_API void upload (UploadData &uploader)
Updates the buffers.
C3D_API bool isCleaned () const noexcept
Retrieves the cleanup status.
C3D_API void setCleaned () noexcept
Tells the engine is cleaned up.
C3D_API void pushCpuJob (castor::AsyncJobQueue::Job job)
Enqueues the given CPU job.
C3D_API castor::RgbaColour getNextRainbowColour () const
Retrieves a colour issued from a rainbow colours iterator.
C3D_API void registerWindow (RenderWindow &window)
Registers a RenderWindow.
C3D_API void unregisterWindow (RenderWindow const &window)
Unregisters a RenderWindow.
C3D_API void registerParsers (castor::String name, castor::AttributeParsers parsers, castor::StrUInt32Map sections, castor::UserContextCreator contextCreator)
Registers additional parsers for SceneFileParser.
C3D_API void unregisterParsers (castor::String const &name) noexcept
Unregisters parsers for SceneFileParser.
C3D_API void registerTimer (castor::String const &category, FramePassTimer &timer)
Registers a render pass timer.
C3D_API void unregisterTimer (castor::String const &category, FramePassTimer &timer) noexcept
Unregisters a render pass timer.
C3D_API LightingModelID registerLightingModel (castor::String const &name, shader::LightingModelCreator creator, BackgroundModelID backgroundModelId) const
Registers a Lighting Model.
C3D_API void unregisterLightingModel (LightingModelID lightingModelId, BackgroundModelID backgroundModelId) const
Unregisters a combination of Lighting Model and Background Model.
C3D_API void unregisterLightingModel (castor::String const &name, BackgroundModelID backgroundModelId) const
Unregisters a Lighting Model.
C3D_API BackgroundModelID registerBackgroundModel (castor::String const &name, shader::BackgroundModelCreator creator)
Registers a Background Model.
C3D_API BackgroundModelID unregisterBackgroundModel (castor::String const &name)
Unregisters a Background Model.
C3D_API void registerBuffer (ShaderBuffer const &buffer)
Registers a ShaderBuffer.
C3D_API void unregisterBuffer (ShaderBuffer const &buffer)
Unregisters a ShaderBuffer.
C3D_API void registerPassModel (BackgroundModelID backgroundModelId, PassRegisterInfo const &info) const
Registers the pass info with given background model.
C3D_API void registerPassModels (PassRegisterInfo const &info) const
Registers the given pass info with all background models.
C3D_API void unregisterPassModel (BackgroundModelID backgroundModelId, LightingModelID lightingModelId) const
Unregisters a combination of lighting model and background model.
C3D_API void unregisterPassModels (castor::String const &type) const
Unregisters all combinations of given lighting model and background models.
C3D_API void registerSpecificsBuffer (castor::String const &name, castor3d::SpecificsBuffer buffer) const
Registers a specific data shader buffer.
C3D_API void unregisterSpecificsBuffer (castor::String const &name) const
Unregisters a pass' specific data buffer.
C3D_API void addSpecificsBuffersBindings (ashes::VkDescriptorSetLayoutBindingArray &bindings, VkShaderStageFlags shaderStages, uint32_t &index) const
Addw the pass' specific data buffer into the given descriptor layout bindings array.
C3D_API void addSpecificsBuffersDescriptors (ashes::WriteDescriptorSetArray &descriptorWrites, uint32_t &index) const
Writes the pass' specific data buffer into the given descriptor writes array.
C3D_API void createSpecificsBuffersPassBindings (crg::FramePass &pass, uint32_t &index) const
Writes the pass' specific data buffer bindings into given frame pass.
C3D_API void declareSpecificsShaderBuffers (sdw::ShaderWriter &writer, castor::StringMap< castor3d::shader::BufferBaseUPtr > &buffers, uint32_t &binding, uint32_t set) const
Declares pass' specific data shader buffers.
C3D_API PassComponentID registerPassComponent (castor::String const &type, PassComponentPluginUPtr componentPlugin) const
Registers a pass component.
C3D_API void unregisterPassComponent (castor::String const &type) const
Unregisters a pass component.
C3D_API SubmeshComponentID registerSubmeshComponent (castor::String const &type, SubmeshComponentPluginUPtr componentPlugin) const
Registers a pass component.
C3D_API void unregisterSubmeshComponent (castor::String const &type) const
Unregisters a pass component.
C3D_API void registerRenderPassType (castor::String const &renderPassType, castor::UniquePtr< RenderPassRegisterInfo > info)
Registers a scene render pass type, used to render given material pass type.
C3D_API void setRenderPassTypeConfiguration (castor::String const &renderPassType, Parameters parameters)
Registers a scene render pass type's configuration parameters.
C3D_API Parameters getRenderPassTypeConfiguration (castor::String const &renderPassType) const
Retrieve a scene render pass type's configuration parameters.
C3D_API RenderPassTypeID getRenderPassTypeID (castor::String const &renderPassType) const
Retrieves the ID for given scene render pass type name.
C3D_API RenderPassRegisterInfo * getRenderPassInfo (castor::String const &renderPassType) const
Retrieves a scene render pass type's creation informations.
C3D_API castor::Vector< RenderPassRegisterInfo * > getRenderPassInfos (TechniquePassEvent event) const
Retrieves the scene render passes type creation informations.
C3D_API void unregisterRenderPassType (castor::String const &renderPassType)
Unregisters a scene render pass type.
Getters.
C3D_API castor::String getDefaultLightingModelName () const
C3D_API ToneMappingFactory const & getToneMappingFactory () const
C3D_API ToneMappingFactory & getToneMappingFactory ()
C3D_API PostEffectFactory const & getPostEffectFactory () const
C3D_API PostEffectFactory & getPostEffectFactory ()
C3D_API uint32_t getWantedFps () const
C3D_API castor3d::MaterialObs getDefaultMaterial () const
C3D_API bool hasMeshShaders () const
C3D_API uint32_t getMaxPassTypeCount () const
C3D_API RenderDevice * getRenderDevice () const
C3D_API ControlsManager * getControlsManager () const
C3D_API UploadData & getUploadData () const noexcept
C3D_API ast::ShaderAllocator & getShaderAllocator ()
castor::String const & getAppName () const noexcept
Version const & getAppVersion () const noexcept
bool isShaderValidationEnabled () const noexcept
bool isValidationEnabled () const noexcept
uint32_t getShaderDebugLevel () const noexcept
bool areUpdateOptimisationsEnabled () const noexcept
bool isRandomisationEnabled () const noexcept
bool isApiTraceEnabled () const noexcept
bool areTextShadersKept () const noexcept
bool areDebugTargetsEnabled () const noexcept
castor::ImageCache const & getImageCache () const noexcept
castor::ImageCache & getImageCache () noexcept
castor::FontCache const & getFontCache () const noexcept
castor::FontCache & getFontCache () noexcept
UserInputListenerRPtr getUserInputListener () noexcept
RenderSystem * getRenderSystem () const noexcept
auto getDefaultSampler () const noexcept
auto getLightsSampler () const noexcept
auto const & getAdditionalParsers () const noexcept
Version const & getVersion () const noexcept
bool hasRenderLoop () const noexcept
RenderLoop & getRenderLoop () const noexcept
bool isThreaded () const noexcept
MeshFactory & getMeshFactory () const noexcept
PassFactory & getPassFactory () const noexcept
PassComponentRegister & getPassComponentsRegister () const noexcept
SubmeshComponentRegister & getSubmeshComponentsRegister () const noexcept
ImporterFileFactory & getImporterFileFactory () const noexcept
ParticleFactory & getParticleFactory () const noexcept
castor::CpuInformations const & getCpuInformations () const noexcept
LightingModelID getDefaultLightingModel () const noexcept
castor::ImageLoader const & getImageLoader () const noexcept
castor::ImageLoader & getImageLoader () noexcept
castor::ImageWriter const & getImageWriter () const noexcept
ashes::RendererList const & getRenderersList () const noexcept
castor::LoggerInstance & getLogger () const noexcept
uint32_t getLpvGridSize () const noexcept
uint32_t getMaxImageSize () const noexcept
auto const & getRenderWindows () const noexcept
crg::ResourceHandler & getGraphResourceHandler () noexcept
LightingModelFactory & getLightingModelFactory () const noexcept
shader::BackgroundModelFactory const & getBackgroundModelFactory () const noexcept
shader::BackgroundModelFactory & getBackgroundModelFactory () noexcept
SceneRPtr getLoadingScene () const noexcept
Texture const & getPrefilteredBrdfTexture () const noexcept
castor::LengthUnit getLengthUnit () const noexcept
Mutators.
C3D_API void setLoadingScene (SceneUPtr scene)
void setUserInputListener (UserInputListenerUPtr listener) noexcept
template<typename ListenerT >
void setUserInputListenerT (castor::UniquePtr< ListenerT > listener) noexcept
void setDefaultLightingModel (LightingModelID value) noexcept
void setMaxImageSize (uint32_t size) noexcept
void setLpvGridSize (uint32_t size) noexcept
template<typename ComponentT >
PassComponentID registerPassComponent (CreatePassComponentPlugin const &createPlugin=&ComponentT::createPlugin)
template<typename ComponentT >
SubmeshComponentID registerSubmeshComponent (CreateSubmeshComponentPlugin const &createPlugin=&ComponentT::createPlugin)
void setLengthUnit (castor::LengthUnit value) noexcept
Fonts.
template<typename ... ParametersT>
castor::FontCache::ElementPtrT createFont (castor::FontCache::ElementKeyT const &key, ParametersT &&... parameters) const
template<typename ... ParametersT>
castor::FontCache::ElementObsT addNewFont (castor::FontCache::ElementKeyT const &key, ParametersT &&... parameters)
castor::FontCache::ElementObsT addFont (castor::FontCache::ElementKeyT const &key, castor::FontCache::ElementPtrT &element, bool initialise=false)
void removeFont (castor::FontCache::ElementKeyT const &key, bool cleanup=false)
castor::FontCache::ElementObsT findFont (castor::FontCache::ElementKeyT const &key) const
bool hasFont (castor::FontCache::ElementKeyT const &key) const
castor::FontCache::ElementObsT tryFindFont (castor::FontCache::ElementKeyT const &key) const
Images.
template<typename ... ParametersT>
castor::ImageCache::ElementPtrT createImage (castor::ImageCache::ElementKeyT const &key, ParametersT &&... parameters) const
template<typename ... ParametersT>
castor::ImageCache::ElementObsT addNewImage (castor::ImageCache::ElementKeyT const &key, ParametersT &&... parameters)
castor::ImageCache::ElementObsT addImage (castor::ImageCache::ElementKeyT const &key, castor::ImageCache::ElementPtrT &element, bool initialise=false)
void removeImage (castor::ImageCache::ElementKeyT const &key, bool cleanup=false) noexcept
castor::ImageCache::ElementObsT findImage (castor::ImageCache::ElementKeyT const &key) const
bool hasImage (castor::ImageCache::ElementKeyT const &key) const
castor::ImageCache::ElementObsT tryFindImage (castor::ImageCache::ElementKeyT const &key) const noexcept
template<typename ... ParametersT>
castor::ImageCache::ElementObsT tryAddImage (castor::ImageCache::ElementKeyT const &name, bool initialise, castor::ImageCache::ElementObsT &created, ParametersT &&... parameters)
Static Public Member Functions
static C3D_API castor::Path getPluginsDirectory ()
Retrieves plug-ins path.
static C3D_API castor::Path getEngineDirectory ()
Gives the Castor directory.
static C3D_API castor::Path getDataDirectory ()
Retrieves data path.
static C3D_API std::locale const & getLocale ()
Retrieves data path.
Additional Inherited Members
Protected Member Functions inherited from castor::Unique< Engine >
Unique (Engine *pThis)
Constructor.
~Unique () noexcept
Destructor.
Constructor & Destructor Documentation
Engine() [1/2]
C3D_API castor3d::Engine::Engine (EngineConfig config) explicit
Constructor.
Parameters
[in] config The engine configuration.
Engine() [2/2]
C3D_API castor3d::Engine::Engine (EngineConfig config, castor::LoggerInstance & logger)
Constructor.
Parameters
[in] config The engine configuration.
[in] logger The logger instance.
~Engine()
C3D_API castor3d::Engine::~Engine () noexcept
Destructor.
Member Function Documentation
addFont()
castor::FontCache::ElementObsT castor3d::Engine::addFont (castor::FontCache::ElementKeyT const & key, castor::FontCache::ElementPtrT & element, bool initialise = false) inline
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::add(), getFontCache(), and initialise().
addImage()
castor::ImageCache::ElementObsT castor3d::Engine::addImage (castor::ImageCache::ElementKeyT const & key, castor::ImageCache::ElementPtrT & element, bool initialise = false) inline
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::add(), getImageCache(), and initialise().
addNewFont()
template<typename ... ParametersT> castor::FontCache::ElementObsT castor3d::Engine::addNewFont (castor::FontCache::ElementKeyT const & key, ParametersT &&... parameters) inline
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::add(), and getFontCache().
addNewImage()
template<typename ... ParametersT> castor::ImageCache::ElementObsT castor3d::Engine::addNewImage (castor::ImageCache::ElementKeyT const & key, ParametersT &&... parameters) inline
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::add(), and getImageCache().
addSpecificsBuffersBindings()
C3D_API void castor3d::Engine::addSpecificsBuffersBindings (ashes::VkDescriptorSetLayoutBindingArray & bindings, VkShaderStageFlags shaderStages, uint32_t & index) const
Addw the pass' specific data buffer into the given descriptor layout bindings array.
Parameters
[in,out] bindings Receives the buffers descriptor layout bindings.
[in] shaderStages The shader stage flags.
[in,out] index The binding index.
addSpecificsBuffersDescriptors()
C3D_API void castor3d::Engine::addSpecificsBuffersDescriptors (ashes::WriteDescriptorSetArray & descriptorWrites, uint32_t & index) const
Writes the pass' specific data buffer into the given descriptor writes array.
Parameters
[in,out] descriptorWrites Receives the buffers descriptor writes.
[in,out] index The binding index.
areDebugTargetsEnabled()
bool castor3d::Engine::areDebugTargetsEnabled () const inline noexcept
References castor3d::EngineConfig::enableDebugTargets.
areTextShadersKept()
bool castor3d::Engine::areTextShadersKept () const inline noexcept
References castor3d::EngineConfig::keepTextShaders.
areUpdateOptimisationsEnabled()
bool castor3d::Engine::areUpdateOptimisationsEnabled () const inline noexcept
References castor3d::EngineConfig::enableUpdateOptimisations.
cleanup()
C3D_API void castor3d::Engine::cleanup ()
Cleanup function, destroys everything created from the beginning.
Remarks
Destroys also RenderWindows, the only things left after that is RenderSystem and loaded plug-ins
Referenced by removeFont(), and removeImage().
createFont()
template<typename ... ParametersT> castor::FontCache::ElementPtrT castor3d::Engine::createFont (castor::FontCache::ElementKeyT const & key, ParametersT &&... parameters) const inline
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::create(), and getFontCache().
createImage()
template<typename ... ParametersT> castor::ImageCache::ElementPtrT castor3d::Engine::createImage (castor::ImageCache::ElementKeyT const & key, ParametersT &&... parameters) const inline
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::create(), and getImageCache().
createSpecificsBuffersPassBindings()
C3D_API void castor3d::Engine::createSpecificsBuffersPassBindings (crg::FramePass & pass, uint32_t & index) const
Writes the pass' specific data buffer bindings into given frame pass.
Parameters
[in,out] pass The target frame pass.
[in,out] index The binding index.
declareSpecificsShaderBuffers()
C3D_API void castor3d::Engine::declareSpecificsShaderBuffers (sdw::ShaderWriter & writer, castor::StringMap< castor3d::shader::BufferBaseUPtr > & buffers, uint32_t & binding, uint32_t set) const
Declares pass' specific data shader buffers.
Parameters
[in,out] writer The shader writer.
[out] buffers Receives the registered shader buffers.
[in,out] binding The descriptor binding index.
[in] set The descriptor set index.
findFont()
castor::FontCache::ElementObsT castor3d::Engine::findFont (castor::FontCache::ElementKeyT const & key) const inline
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::find(), and getFontCache().
findImage()
castor::ImageCache::ElementObsT castor3d::Engine::findImage (castor::ImageCache::ElementKeyT const & key) const inline
References castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::find(), and getImageCache().
fireMouseMove()
C3D_API bool castor3d::Engine::fireMouseMove (castor::Position const & position, bool ctrl, bool alt, bool shift)
Fires a mouse move event.
Parameters
[in] position The mouse position.
[in] ctrl Tells if the Ctrl key is down.
[in] alt Tells if the Alt key is down.
[in] shift Tells if the Shift key is down.
Returns
true if the event is processed by a handler.
getAdditionalParsers()
auto const & castor3d::Engine::getAdditionalParsers () const inline noexcept
getAppName()
castor::String const & castor3d::Engine::getAppName () const inline noexcept
References castor3d::EngineConfig::appName.
getAppVersion()
Version const & castor3d::Engine::getAppVersion () const inline noexcept
References castor3d::EngineConfig::appVersion.
getBackgroundModelFactory() [1/2]
shader::BackgroundModelFactory const & castor3d::Engine::getBackgroundModelFactory () const inline noexcept
getBackgroundModelFactory() [2/2]
shader::BackgroundModelFactory & castor3d::Engine::getBackgroundModelFactory () inline noexcept
getControlsManager()
C3D_API ControlsManager * castor3d::Engine::getControlsManager () const
getCpuInformations()
castor::CpuInformations const & castor3d::Engine::getCpuInformations () const inline noexcept
getDataDirectory()
static C3D_API castor::Path castor3d::Engine::getDataDirectory () static
Retrieves data path.
Returns
The data path
getDefaultLightingModel()
LightingModelID castor3d::Engine::getDefaultLightingModel () const inline noexcept
getDefaultLightingModelName()
C3D_API castor::String castor3d::Engine::getDefaultLightingModelName () const
getDefaultMaterial()
C3D_API castor3d::MaterialObs castor3d::Engine::getDefaultMaterial () const
getDefaultSampler()
auto castor3d::Engine::getDefaultSampler () const inline noexcept
getEngineDirectory()
static C3D_API castor::Path castor3d::Engine::getEngineDirectory () static
Gives the Castor directory.
Returns
The directory
getFontCache() [1/2]
castor::FontCache const & castor3d::Engine::getFontCache () const inline noexcept
Referenced by addFont(), addNewFont(), createFont(), findFont(), hasFont(), removeFont(), and tryFindFont().
getFontCache() [2/2]
castor::FontCache & castor3d::Engine::getFontCache () inline noexcept
getGraphResourceHandler()
crg::ResourceHandler & castor3d::Engine::getGraphResourceHandler () inline noexcept
getImageCache() [1/2]
castor::ImageCache const & castor3d::Engine::getImageCache () const inline noexcept
Referenced by addImage(), addNewImage(), createImage(), findImage(), hasImage(), removeImage(), tryAddImage(), and tryFindImage().
getImageCache() [2/2]
castor::ImageCache & castor3d::Engine::getImageCache () inline noexcept
getImageLoader() [1/2]
castor::ImageLoader const & castor3d::Engine::getImageLoader () const inline noexcept
getImageLoader() [2/2]
castor::ImageLoader & castor3d::Engine::getImageLoader () inline noexcept
getImageWriter()
castor::ImageWriter const & castor3d::Engine::getImageWriter () const inline noexcept
getImporterFileFactory()
ImporterFileFactory & castor3d::Engine::getImporterFileFactory () const inline noexcept
getLengthUnit()
castor::LengthUnit castor3d::Engine::getLengthUnit () const inline noexcept
getLightingModelFactory()
LightingModelFactory & castor3d::Engine::getLightingModelFactory () const inline noexcept
getLightsSampler()
auto castor3d::Engine::getLightsSampler () const inline noexcept
getLoadingScene()
SceneRPtr castor3d::Engine::getLoadingScene () const inline noexcept
getLocale()
static C3D_API std::locale const & castor3d::Engine::getLocale () static
Retrieves data path.
Returns
The data path
getLogger()
castor::LoggerInstance & castor3d::Engine::getLogger () const inline noexcept
getLpvGridSize()
uint32_t castor3d::Engine::getLpvGridSize () const inline noexcept
getMaxImageSize()
uint32_t castor3d::Engine::getMaxImageSize () const inline noexcept
getMaxPassTypeCount()
C3D_API uint32_t castor3d::Engine::getMaxPassTypeCount () const
getMeshFactory()
MeshFactory & castor3d::Engine::getMeshFactory () const inline noexcept
getNextRainbowColour()
C3D_API castor::RgbaColour castor3d::Engine::getNextRainbowColour () const
Retrieves a colour issued from a rainbow colours iterator.
getParticleFactory()
ParticleFactory & castor3d::Engine::getParticleFactory () const inline noexcept
getPassComponentsRegister()
PassComponentRegister & castor3d::Engine::getPassComponentsRegister () const inline noexcept
getPassFactory()
PassFactory & castor3d::Engine::getPassFactory () const inline noexcept
getPluginsDirectory()
static C3D_API castor::Path castor3d::Engine::getPluginsDirectory () static
Retrieves plug-ins path.
Returns
The plug-ins path
getPostEffectFactory() [1/2]
C3D_API PostEffectFactory & castor3d::Engine::getPostEffectFactory ()
getPostEffectFactory() [2/2]
C3D_API PostEffectFactory const & castor3d::Engine::getPostEffectFactory () const
getPrefilteredBrdfTexture()
Texture const & castor3d::Engine::getPrefilteredBrdfTexture () const inline noexcept
getRenderDevice()
C3D_API RenderDevice * castor3d::Engine::getRenderDevice () const
getRenderersList()
ashes::RendererList const & castor3d::Engine::getRenderersList () const inline noexcept
getRenderLoop()
RenderLoop & castor3d::Engine::getRenderLoop () const inline noexcept
getRenderPassInfo()
C3D_API RenderPassRegisterInfo * castor3d::Engine::getRenderPassInfo (castor::String const & renderPassType) const
Retrieves a scene render pass type's creation informations.
Parameters
[in] renderPassType The pass type name.
getRenderPassInfos()
C3D_API castor::Vector< RenderPassRegisterInfo * > castor3d::Engine::getRenderPassInfos (TechniquePassEvent event) const
Retrieves the scene render passes type creation informations.
Parameters
[in] event The event type for wanted passes.
getRenderPassTypeConfiguration()
C3D_API Parameters castor3d::Engine::getRenderPassTypeConfiguration (castor::String const & renderPassType) const
Retrieve a scene render pass type's configuration parameters.
Parameters
[in] renderPassType The pass type name.
Returns
The pass configuration parameters.
getRenderPassTypeID()
C3D_API RenderPassTypeID castor3d::Engine::getRenderPassTypeID (castor::String const & renderPassType) const
Retrieves the ID for given scene render pass type name.
Parameters
[in] renderPassType The pass type name.
getRenderSystem()
RenderSystem * castor3d::Engine::getRenderSystem () const inline noexcept
getRenderWindows()
auto const & castor3d::Engine::getRenderWindows () const inline noexcept
getShaderAllocator()
C3D_API ast::ShaderAllocator & castor3d::Engine::getShaderAllocator ()
getShaderDebugLevel()
uint32_t castor3d::Engine::getShaderDebugLevel () const inline noexcept
References castor3d::EngineConfig::shaderDebugLevel.
getSubmeshComponentsRegister()
SubmeshComponentRegister & castor3d::Engine::getSubmeshComponentsRegister () const inline noexcept
getToneMappingFactory() [1/2]
C3D_API ToneMappingFactory & castor3d::Engine::getToneMappingFactory ()
getToneMappingFactory() [2/2]
C3D_API ToneMappingFactory const & castor3d::Engine::getToneMappingFactory () const
getUploadData()
C3D_API UploadData & castor3d::Engine::getUploadData () const noexcept
getUserInputListener()
UserInputListenerRPtr castor3d::Engine::getUserInputListener () inline noexcept
getVersion()
Version const & castor3d::Engine::getVersion () const inline noexcept
getWantedFps()
C3D_API uint32_t castor3d::Engine::getWantedFps () const
hasFont()
bool castor3d::Engine::hasFont (castor::FontCache::ElementKeyT const & key) const inline
References getFontCache(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::has().
hasImage()
bool castor3d::Engine::hasImage (castor::ImageCache::ElementKeyT const & key) const inline
References getImageCache(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::has().
hasMeshShaders()
C3D_API bool castor3d::Engine::hasMeshShaders () const
hasRenderLoop()
bool castor3d::Engine::hasRenderLoop () const inline noexcept
initialise()
C3D_API void castor3d::Engine::initialise (uint32_t wantedFPS = 100, bool threaded = false)
Initialisation function, Sets the wanted frame rate.
Parameters
[in] wantedFPS The wanted FPS count
[in] threaded If false, the render can't be threaded
Referenced by addFont(), addImage(), and tryAddImage().
isApiTraceEnabled()
bool castor3d::Engine::isApiTraceEnabled () const inline noexcept
References castor3d::EngineConfig::enableApiTrace.
isCleaned()
C3D_API bool castor3d::Engine::isCleaned () const noexcept
Retrieves the cleanup status.
Remarks
Thread-safe
Returns
true if cleaned up
isRandomisationEnabled()
bool castor3d::Engine::isRandomisationEnabled () const inline noexcept
References castor3d::EngineConfig::enableRandom.
isShaderValidationEnabled()
bool castor3d::Engine::isShaderValidationEnabled () const inline noexcept
References castor3d::EngineConfig::enableShaderValidation.
isThreaded()
bool castor3d::Engine::isThreaded () const inline noexcept
isValidationEnabled()
bool castor3d::Engine::isValidationEnabled () const inline noexcept
References castor3d::EngineConfig::enableValidation.
loadRenderer() [1/2]
C3D_API bool castor3d::Engine::loadRenderer (castor::String const & type)
Loads a renderer plug-in, given the renderer type.
Parameters
[in] type The renderer type.
Returns
true if ok
loadRenderer() [2/2]
C3D_API void castor3d::Engine::loadRenderer (Renderer renderer)
Loads a renderer plug-in, given the renderer type.
Parameters
[in] renderer The renderer.
postEvent() [1/2]
C3D_API CpuFrameEvent * castor3d::Engine::postEvent (CpuFrameEventUPtr event) const
Posts a frame event to the default frame listener.
Parameters
[in] event The event to add
postEvent() [2/2]
C3D_API GpuFrameEvent * castor3d::Engine::postEvent (GpuFrameEventUPtr event) const
Posts a frame event to the default frame listener.
Parameters
[in] event The event to add
pushCpuJob()
C3D_API void castor3d::Engine::pushCpuJob (castor::AsyncJobQueue::Job job)
Enqueues the given CPU job.
Parameters
[in] job The job to execute.
registerBackgroundModel()
C3D_API BackgroundModelID castor3d::Engine::registerBackgroundModel (castor::String const & name, shader::BackgroundModelCreator creator)
Registers a Background Model.
Parameters
[in] name The model name.
[in] creator The model creation function.
Returns
The model ID.
registerBuffer()
C3D_API void castor3d::Engine::registerBuffer (ShaderBuffer const & buffer)
Registers a ShaderBuffer.
Parameters
[in] buffer The ShaderBuffer.
registerLightingModel()
C3D_API LightingModelID castor3d::Engine::registerLightingModel (castor::String const & name, shader::LightingModelCreator creator, BackgroundModelID backgroundModelId) const
Registers a Lighting Model.
Parameters
[in] name The model name.
[in] backgroundModelId The background model ID.
[in] creator The model creation function.
Returns
The model ID.
registerParsers()
C3D_API void castor3d::Engine::registerParsers (castor::String name, castor::AttributeParsers parsers, castor::StrUInt32Map sections, castor::UserContextCreator contextCreator)
Registers additional parsers for SceneFileParser.
Parameters
[in] name The registering name.
[in] parsers The parsers.
[in] sections The sections.
[in] contextCreator The user parser context creation function.
registerPassComponent() [1/2]
C3D_API PassComponentID castor3d::Engine::registerPassComponent (castor::String const & type, PassComponentPluginUPtr componentPlugin) const
Registers a pass component.
Parameters
[in] type The component type name.
[in] componentPlugin The component's specific functions.
Referenced by registerPassComponent().
registerPassComponent() [2/2]
template<typename ComponentT > PassComponentID castor3d::Engine::registerPassComponent (CreatePassComponentPlugin const & createPlugin = &ComponentT::createPlugin) inline
References registerPassComponent().
registerPassModel()
C3D_API void castor3d::Engine::registerPassModel (BackgroundModelID backgroundModelId, PassRegisterInfo const & info) const
Registers the pass info with given background model.
Parameters
[in] backgroundModelId The background model.
[in] info The pass registering info.
registerPassModels()
C3D_API void castor3d::Engine::registerPassModels (PassRegisterInfo const & info) const
Registers the given pass info with all background models.
Parameters
[in] info The pass registering info.
registerRenderPassType()
C3D_API void castor3d::Engine::registerRenderPassType (castor::String const & renderPassType, castor::UniquePtr< RenderPassRegisterInfo > info)
Registers a scene render pass type, used to render given material pass type.
Parameters
[in] renderPassType The pass type name.
[in] info The pass creation informations.
registerSpecificsBuffer()
C3D_API void castor3d::Engine::registerSpecificsBuffer (castor::String const & name, castor3d::SpecificsBuffer buffer) const
Registers a specific data shader buffer.
Parameters
[in,out] name The shader buffer name.
[out] buffer The shader buffer.
registerSubmeshComponent() [1/2]
C3D_API SubmeshComponentID castor3d::Engine::registerSubmeshComponent (castor::String const & type, SubmeshComponentPluginUPtr componentPlugin) const
Registers a pass component.
Parameters
[in] type The component type name.
[in] componentPlugin The component's specific functions.
Referenced by registerSubmeshComponent().
registerSubmeshComponent() [2/2]
template<typename ComponentT > SubmeshComponentID castor3d::Engine::registerSubmeshComponent (CreateSubmeshComponentPlugin const & createPlugin = &ComponentT::createPlugin) inline
References registerSubmeshComponent().
registerTimer()
C3D_API void castor3d::Engine::registerTimer (castor::String const & category, FramePassTimer & timer)
Registers a render pass timer.
Parameters
[in] category The timer category name.
[in] timer The timer to register.
registerWindow()
C3D_API void castor3d::Engine::registerWindow (RenderWindow & window)
Registers a RenderWindow.
Parameters
[in] window The RenderWindow.
removeFont()
void castor3d::Engine::removeFont (castor::FontCache::ElementKeyT const & key, bool cleanup = false) inline
References cleanup(), getFontCache(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::remove().
removeImage()
void castor3d::Engine::removeImage (castor::ImageCache::ElementKeyT const & key, bool cleanup = false) inline noexcept
References cleanup(), getImageCache(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::remove().
sendEvent()
C3D_API void castor3d::Engine::sendEvent (GpuFrameEventUPtr event) const
If a device is enabled, executes the given event, if not posts it to the default frame listener.
Parameters
[in] event The event.
setCleaned()
C3D_API void castor3d::Engine::setCleaned () noexcept
Tells the engine is cleaned up.
Remarks
Thread-safe
setDefaultLightingModel()
void castor3d::Engine::setDefaultLightingModel (LightingModelID value) inline noexcept
setLengthUnit()
void castor3d::Engine::setLengthUnit (castor::LengthUnit value) inline noexcept
setLoadingScene()
C3D_API void castor3d::Engine::setLoadingScene (SceneUPtr scene)
setLpvGridSize()
void castor3d::Engine::setLpvGridSize (uint32_t size) inline noexcept
setMaxImageSize()
void castor3d::Engine::setMaxImageSize (uint32_t size) inline noexcept
setRenderPassTypeConfiguration()
C3D_API void castor3d::Engine::setRenderPassTypeConfiguration (castor::String const & renderPassType, Parameters parameters)
Registers a scene render pass type's configuration parameters.
Parameters
[in] renderPassType The pass type name.
[in] parameters The pass configuration parameters.
setUserInputListener()
void castor3d::Engine::setUserInputListener (UserInputListenerUPtr listener) inline noexcept
setUserInputListenerT()
template<typename ListenerT > void castor3d::Engine::setUserInputListenerT (castor::UniquePtr< ListenerT > listener) inline noexcept
tryAddImage()
template<typename ... ParametersT> castor::ImageCache::ElementObsT castor3d::Engine::tryAddImage (castor::ImageCache::ElementKeyT const & name, bool initialise, castor::ImageCache::ElementObsT & created, ParametersT &&... parameters) inline
References getImageCache(), initialise(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::tryAdd().
tryFindFont()
castor::FontCache::ElementObsT castor3d::Engine::tryFindFont (castor::FontCache::ElementKeyT const & key) const inline
References getFontCache(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::tryFind().
tryFindImage()
castor::ImageCache::ElementObsT castor3d::Engine::tryFindImage (castor::ImageCache::ElementKeyT const & key) const inline noexcept
References getImageCache(), and castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::tryFind().
unregisterBackgroundModel()
C3D_API BackgroundModelID castor3d::Engine::unregisterBackgroundModel (castor::String const & name)
Unregisters a Background Model.
Parameters
[in] name The model name.
unregisterBuffer()
C3D_API void castor3d::Engine::unregisterBuffer (ShaderBuffer const & buffer)
Unregisters a ShaderBuffer.
Parameters
[in] buffer The ShaderBuffer.
unregisterLightingModel() [1/2]
C3D_API void castor3d::Engine::unregisterLightingModel (castor::String const & name, BackgroundModelID backgroundModelId) const
Unregisters a Lighting Model.
Parameters
[in] name The model name.
[in] backgroundModelId The background model ID.
unregisterLightingModel() [2/2]
C3D_API void castor3d::Engine::unregisterLightingModel (LightingModelID lightingModelId, BackgroundModelID backgroundModelId) const
Unregisters a combination of Lighting Model and Background Model.
Parameters
[in] lightingModelId The lighting model ID.
[in] backgroundModelId The bavkground model ID.
unregisterParsers()
C3D_API void castor3d::Engine::unregisterParsers (castor::String const & name) noexcept
Unregisters parsers for SceneFileParser.
Parameters
[in] name The registering name.
unregisterPassComponent()
C3D_API void castor3d::Engine::unregisterPassComponent (castor::String const & type) const
Unregisters a pass component.
Parameters
[in] type The component type name.
unregisterPassModel()
C3D_API void castor3d::Engine::unregisterPassModel (BackgroundModelID backgroundModelId, LightingModelID lightingModelId) const
Unregisters a combination of lighting model and background model.
Parameters
[in] backgroundModelId The background model.
[in] lightingModelId The lighting model.
unregisterPassModels()
C3D_API void castor3d::Engine::unregisterPassModels (castor::String const & type) const
Unregisters all combinations of given lighting model and background models.
Parameters
[in] type The lighting model name.
unregisterRenderPassType()
C3D_API void castor3d::Engine::unregisterRenderPassType (castor::String const & renderPassType)
Unregisters a scene render pass type.
Parameters
[in] renderPassType The pass type name.
unregisterSpecificsBuffer()
C3D_API void castor3d::Engine::unregisterSpecificsBuffer (castor::String const & name) const
Unregisters a pass' specific data buffer.
Parameters
[in,out] name The shader buffer name.
unregisterSubmeshComponent()
C3D_API void castor3d::Engine::unregisterSubmeshComponent (castor::String const & type) const
Unregisters a pass component.
Parameters
[in] type The component type name.
unregisterTimer()
C3D_API void castor3d::Engine::unregisterTimer (castor::String const & category, FramePassTimer & timer) noexcept
Unregisters a render pass timer.
Parameters
[in] category The timer category name.
[in] timer The timer to unregister.
unregisterWindow()
C3D_API void castor3d::Engine::unregisterWindow (RenderWindow const & window)
Unregisters a RenderWindow.
Parameters
[in] window The RenderWindow.
update() [1/2]
C3D_API void castor3d::Engine::update (CpuUpdater & updater)
Updates the engine, CPU wise.
Parameters
[in,out] updater The update data.
update() [2/2]
C3D_API void castor3d::Engine::update (GpuUpdater & updater)
Updates the engine, GPU wise.
Parameters
[in,out] updater The update data.
upload()
C3D_API void castor3d::Engine::upload (UploadData & uploader)
Updates the buffers.
Parameters
[in,out] uploader Receives the upload requests.
The documentation for this class was generated from the following file:
Castor3D/Engine.hpp