Castor3D: castor3d::Overlay Class Reference
castor3d::Overlay Class Reference final
#include <Overlay.hpp>
Public Types
using iterator = OverlayPtrArray::iterator
using const_iterator = OverlayPtrArray::const_iterator
Public Member Functions
C3D_API Overlay (castor::String const &name, Engine &engine, OverlayType type, Scene *scene, OverlayRPtr parent, uint32_t level=0u)
Constructor.
C3D_API Overlay (Engine &engine, OverlayType type, Scene *scene, OverlayRPtr parent, uint32_t level=0u)
Constructor.
C3D_API Overlay (Engine &engine, OverlayType type, uint32_t level=0u)
Constructor.
C3D_API uint32_t getChildrenCount (uint32_t level) const
C3D_API PanelOverlayRPtr getPanelOverlay () const
C3D_API BorderPanelOverlayRPtr getBorderPanelOverlay () const
C3D_API TextOverlayRPtr getTextOverlay () const
C3D_API bool isVisible () const
C3D_API bool isDisplayable () const
C3D_API uint32_t computeLevel () const
Getters.
OverlayCategory & getCategory () const noexcept
castor::Position getAbsolutePosition (castor::Size const &size) const noexcept
castor::Size getAbsoluteSize (castor::Size const &size) const noexcept
castor::Point2d getAbsolutePosition () const noexcept
castor::Point2d getAbsoluteSize () const noexcept
bool isSizeChanged () const noexcept
bool isPositionChanged () const noexcept
castor::String const & getName () const noexcept
castor::Point2d const & getRelativePosition () const noexcept
castor::Point2d const & getRelativeSize () const noexcept
OverlayType getType () const noexcept
OverlayRPtr getParent () const noexcept
MaterialObs getMaterial () const noexcept
SceneRPtr getScene () const noexcept
uint32_t getIndex () const noexcept
uint32_t getLevel () const noexcept
Array access to childs.
size_t size () const noexcept
bool empty () const noexcept
iterator begin ()
const_iterator begin () const noexcept
iterator end ()
const_iterator end () const noexcept
Mutators.
void setVisible (bool val)
void setMaterial (MaterialObs material)
void setRelativePosition (castor::Point2d const &position)
void setRelativeSize (castor::Point2d const &size)
void setPixelPosition (castor::Position const &position)
void setPixelSize (castor::Size const &size)
void rename (castor::String const &name)
void reparent (OverlayRPtr parent)
Friends
class castor::ResourceCacheT< Overlay, castor::String, OverlayCacheTraits >
Member Typedef Documentation
const_iterator
using castor3d::Overlay::const_iterator = OverlayPtrArray::const_iterator
iterator
using castor3d::Overlay::iterator = OverlayPtrArray::iterator
Constructor & Destructor Documentation
Overlay() [1/3]
C3D_API castor3d::Overlay::Overlay (castor::String const & name, Engine & engine, OverlayType type, Scene * scene, OverlayRPtr parent, uint32_t level = 0u)
Constructor.
Parameters
[in] name The overlay name.
[in] engine The engine.
[in] type The overlay type.
[in] scene The scene holding the overlay.
[in] parent The parent overlay (if any).
[in] level The overlay base level.
Overlay() [2/3]
C3D_API castor3d::Overlay::Overlay (Engine & engine, OverlayType type, Scene * scene, OverlayRPtr parent, uint32_t level = 0u)
Constructor.
Parameters
[in] engine The engine.
[in] type The overlay type.
[in] scene The scene holding the overlay.
[in] parent The parent overlay (if any).
[in] level The overlay base level.
Overlay() [3/3]
C3D_API castor3d::Overlay::Overlay (Engine & engine, OverlayType type, uint32_t level = 0u)
Constructor.
Parameters
[in] engine The engine.
[in] type The overlay type.
[in] level The overlay base level.
Member Function Documentation
begin() [1/2]
iterator castor3d::Overlay::begin () inline
begin() [2/2]
const_iterator castor3d::Overlay::begin () const inline noexcept
computeLevel()
C3D_API uint32_t castor3d::Overlay::computeLevel () const
Returns
The hierarchy level for this overlay
empty()
bool castor3d::Overlay::empty () const inline noexcept
end() [1/2]
iterator castor3d::Overlay::end () inline
end() [2/2]
const_iterator castor3d::Overlay::end () const inline noexcept
getAbsolutePosition() [1/2]
castor::Point2d castor3d::Overlay::getAbsolutePosition () const inline noexcept
getAbsolutePosition() [2/2]
castor::Position castor3d::Overlay::getAbsolutePosition (castor::Size const & size) const inline noexcept
References size().
getAbsoluteSize() [1/2]
castor::Point2d castor3d::Overlay::getAbsoluteSize () const inline noexcept
getAbsoluteSize() [2/2]
castor::Size castor3d::Overlay::getAbsoluteSize (castor::Size const & size) const inline noexcept
References size().
getBorderPanelOverlay()
C3D_API BorderPanelOverlayRPtr castor3d::Overlay::getBorderPanelOverlay () const
Returns
The border panel overlay.
getCategory()
OverlayCategory & castor3d::Overlay::getCategory () const inline noexcept
getChildrenCount()
C3D_API uint32_t castor3d::Overlay::getChildrenCount (uint32_t level) const
Parameters
[in] level The wanted level
Returns
The childs count at given level.
getIndex()
uint32_t castor3d::Overlay::getIndex () const inline noexcept
getLevel()
uint32_t castor3d::Overlay::getLevel () const inline noexcept
getMaterial()
MaterialObs castor3d::Overlay::getMaterial () const inline noexcept
getName()
castor::String const & castor3d::Overlay::getName () const inline noexcept
getPanelOverlay()
C3D_API PanelOverlayRPtr castor3d::Overlay::getPanelOverlay () const
Returns
The panel overlay.
getParent()
OverlayRPtr castor3d::Overlay::getParent () const inline noexcept
getRelativePosition()
castor::Point2d const & castor3d::Overlay::getRelativePosition () const inline noexcept
getRelativeSize()
castor::Point2d const & castor3d::Overlay::getRelativeSize () const inline noexcept
getScene()
SceneRPtr castor3d::Overlay::getScene () const inline noexcept
getTextOverlay()
C3D_API TextOverlayRPtr castor3d::Overlay::getTextOverlay () const
Returns
The text overlay.
getType()
OverlayType castor3d::Overlay::getType () const inline noexcept
isDisplayable()
C3D_API bool castor3d::Overlay::isDisplayable () const
Returns
The siplayability status.
isPositionChanged()
bool castor3d::Overlay::isPositionChanged () const inline noexcept
isSizeChanged()
bool castor3d::Overlay::isSizeChanged () const inline noexcept
isVisible()
C3D_API bool castor3d::Overlay::isVisible () const
Returns
The visibility status.
rename()
void castor3d::Overlay::rename (castor::String const & name) inline
reparent()
void castor3d::Overlay::reparent (OverlayRPtr parent) inline
setMaterial()
void castor3d::Overlay::setMaterial (MaterialObs material) inline
setPixelPosition()
void castor3d::Overlay::setPixelPosition (castor::Position const & position) inline
setPixelSize()
void castor3d::Overlay::setPixelSize (castor::Size const & size) inline
References size().
setRelativePosition()
void castor3d::Overlay::setRelativePosition (castor::Point2d const & position) inline
setRelativeSize()
void castor3d::Overlay::setRelativeSize (castor::Point2d const & size) inline
References size().
setVisible()
void castor3d::Overlay::setVisible (bool val) inline
size()
size_t castor3d::Overlay::size () const inline noexcept
Referenced by getAbsolutePosition(), getAbsoluteSize(), setPixelSize(), and setRelativeSize().
Friends And Related Function Documentation
castor::ResourceCacheT< Overlay, castor::String, OverlayCacheTraits >
friend class castor::ResourceCacheT< Overlay, castor::String, OverlayCacheTraits > friend
The documentation for this class was generated from the following file:
Overlay/Overlay.hpp