Castor3D: castor::PixelIterator< PF > Struct Template Reference
castor::PixelIterator< PF > Struct Template Reference
Pixel buffer iterator.
#include <PixelIterator.hpp>
Public Types
using value_type = Pixel< PF >
using difference_type = std::ptrdiff_t
using pointer = Pixel< PF > *
using reference = Pixel< PF > &
using pixel_type = Pixel< PF >
using array_type = PxBufferBase::PxArray
using internal_type = array_type::iterator
using const_internal_type = array_type::const_iterator
using iterator_category = internal_type::iterator_category
Public Member Functions
~PixelIterator () noexcept=default
PixelIterator (array_type const &array, internal_type const &iter)
PixelIterator (PixelIterator const &iter)
PixelIterator (PixelIterator &&iter) noexcept
PixelIterator & operator= (PixelIterator const &it)
PixelIterator & operator= (PixelIterator &&it) noexcept
PixelIterator & operator+= (size_t offset)
PixelIterator & operator-= (size_t offset)
PixelIterator & operator++ ()
PixelIterator operator++ (int)
PixelIterator & operator-- ()
PixelIterator operator-- (int)
pixel_type const & operator* () const
pixel_type & operator* ()
pixel_type * operator-> ()
bool operator== (PixelIterator const &it) const
bool operator!= (PixelIterator const &it) const
Static Public Member Functions
static difference_type diffIt (PixelIterator const &lhs, PixelIterator const &rhs)
Friends
template<PixelFormat PiF>
struct ConstPixelIterator
Detailed Description
template<PixelFormat PF>
struct castor::PixelIterator< PF >
Pixel buffer iterator.
Member Typedef Documentation
array_type
template<PixelFormat PF> using castor::PixelIterator< PF >::array_type = PxBufferBase::PxArray
const_internal_type
template<PixelFormat PF> using castor::PixelIterator< PF >::const_internal_type = array_type::const_iterator
difference_type
template<PixelFormat PF> using castor::PixelIterator< PF >::difference_type = std::ptrdiff_t
internal_type
template<PixelFormat PF> using castor::PixelIterator< PF >::internal_type = array_type::iterator
iterator_category
template<PixelFormat PF> using castor::PixelIterator< PF >::iterator_category = internal_type::iterator_category
pixel_type
template<PixelFormat PF> using castor::PixelIterator< PF >::pixel_type = Pixel< PF >
pointer
template<PixelFormat PF> using castor::PixelIterator< PF >::pointer = Pixel< PF > *
reference
template<PixelFormat PF> using castor::PixelIterator< PF >::reference = Pixel< PF > &
value_type
template<PixelFormat PF> using castor::PixelIterator< PF >::value_type = Pixel< PF >
Constructor & Destructor Documentation
~PixelIterator()
template<PixelFormat PF> castor::PixelIterator< PF >::~PixelIterator () default noexcept
PixelIterator() [1/3]
template<PixelFormat PF> castor::PixelIterator< PF >::PixelIterator (array_type const & array, internal_type const & iter) inline
PixelIterator() [2/3]
template<PixelFormat PF> castor::PixelIterator< PF >::PixelIterator (PixelIterator< PF > const & iter) inline
PixelIterator() [3/3]
template<PixelFormat PF> castor::PixelIterator< PF >::PixelIterator (PixelIterator< PF > && iter) inline noexcept
Member Function Documentation
diffIt()
template<PixelFormat PF> static difference_type castor::PixelIterator< PF >::diffIt (PixelIterator< PF > const & lhs, PixelIterator< PF > const & rhs) inline static
Referenced by castor::operator-().
operator!=()
template<PixelFormat PF> bool castor::PixelIterator< PF >::operator!= (PixelIterator< PF > const & it) const inline
operator*() [1/2]
template<PixelFormat PF> pixel_type & castor::PixelIterator< PF >::operator* () inline
References CU_Require.
operator*() [2/2]
template<PixelFormat PF> pixel_type const & castor::PixelIterator< PF >::operator* () const inline
References CU_Require.
operator++() [1/2]
template<PixelFormat PF> PixelIterator & castor::PixelIterator< PF >::operator++ () inline
References castor::PixelIterator< PF >::operator+=().
operator++() [2/2]
template<PixelFormat PF> PixelIterator castor::PixelIterator< PF >::operator++ (int) inline
operator+=()
template<PixelFormat PF> PixelIterator & castor::PixelIterator< PF >::operator+= (size_t offset) inline
Referenced by castor::PixelIterator< PF >::operator++().
operator--() [1/2]
template<PixelFormat PF> PixelIterator & castor::PixelIterator< PF >::operator-- () inline
References castor::PixelIterator< PF >::operator-=().
operator--() [2/2]
template<PixelFormat PF> PixelIterator castor::PixelIterator< PF >::operator-- (int) inline
operator-=()
template<PixelFormat PF> PixelIterator & castor::PixelIterator< PF >::operator-= (size_t offset) inline
Referenced by castor::PixelIterator< PF >::operator--().
operator->()
template<PixelFormat PF> pixel_type * castor::PixelIterator< PF >::operator-> () inline
References CU_Require.
operator=() [1/2]
template<PixelFormat PF> PixelIterator & castor::PixelIterator< PF >::operator= (PixelIterator< PF > && it) inline noexcept
operator=() [2/2]
template<PixelFormat PF> PixelIterator & castor::PixelIterator< PF >::operator= (PixelIterator< PF > const & it) inline
operator==()
template<PixelFormat PF> bool castor::PixelIterator< PF >::operator== (PixelIterator< PF > const & it) const inline
Friends And Related Symbol Documentation
ConstPixelIterator
template<PixelFormat PF> template<PixelFormat PiF> friend struct ConstPixelIterator friend
The documentation for this struct was generated from the following files:
CastorUtils/Graphics/GraphicsModule.hpp
CastorUtils/Graphics/PixelIterator.hpp