
set TEST_CMAKE_FLAGS=-DPROJECTS_USE_PRECOMPILED_HEADERS=OFF -DCASTOR_BUILD_CASTOR3D=OFF -DCASTOR_BUILDGRP_TEST=ON -DCASTOR_BUILD_TEST_CASTORUTILS=ON

set IMPORTERS_CMAKE_FLAGS=-DPROJECTS_USE_PRECOMPILED_HEADERS=OFF -DCASTOR_BUILDGRP_TEST=OFF -DCASTOR_BUILDGRP_INTEROP=OFF -DCASTOR_BUILDGRP_SAMPLE=OFF -DCASTOR_BUILDGRP_DIVIDER=OFF -DCASTOR_BUILDGRP_TONEMAPS=OFF -DCASTOR_BUILDGRP_GENERIC=OFF -DCASTOR_BUILDGRP_IMPORTER=ON -DCASTOR_BUILDGRP_POSTFX=OFF -DCASTOR_BUILD_TEST_RENDERER_OGL=OFF -DCASTOR_FORCE_ALL_IMPORTERS=ON

set DIVIDERS_CMAKE_FLAGS=-DPROJECTS_USE_PRECOMPILED_HEADERS=OFF -DCASTOR_BUILDGRP_TEST=OFF -DCASTOR_BUILDGRP_INTEROP=OFF -DCASTOR_BUILDGRP_SAMPLE=OFF -DCASTOR_BUILDGRP_DIVIDER=ON -DCASTOR_BUILDGRP_TONEMAPS=OFF -DCASTOR_BUILDGRP_GENERIC=OFF -DCASTOR_BUILDGRP_IMPORTER=OFF -DCASTOR_BUILDGRP_POSTFX=OFF -DCASTOR_BUILD_TEST_RENDERER_OGL=OFF

set POSTFX_CMAKE_FLAGS=-DPROJECTS_USE_PRECOMPILED_HEADERS=OFF -DCASTOR_BUILDGRP_TEST=OFF -DCASTOR_BUILDGRP_INTEROP=OFF -DCASTOR_BUILDGRP_SAMPLE=OFF -DCASTOR_BUILDGRP_DIVIDER=OFF -DCASTOR_BUILDGRP_TONEMAPS=OFF -DCASTOR_BUILDGRP_GENERIC=OFF -DCASTOR_BUILDGRP_IMPORTER=OFF -DCASTOR_BUILDGRP_POSTFX=ON -DCASTOR_BUILD_TEST_RENDERER_OGL=OFF

set TONEMAPS_CMAKE_FLAGS=-DPROJECTS_USE_PRECOMPILED_HEADERS=OFF -DCASTOR_BUILDGRP_TEST=OFF -DCASTOR_BUILDGRP_INTEROP=OFF -DCASTOR_BUILDGRP_SAMPLE=OFF -DCASTOR_BUILDGRP_DIVIDER=OFF -DCASTOR_BUILDGRP_TONEMAPS=ON -DCASTOR_BUILDGRP_GENERIC=ON -DCASTOR_BUILDGRP_IMPORTER=OFF -DCASTOR_BUILDGRP_POSTFX=OFF -DCASTOR_BUILD_TEST_RENDERER_OGL=OFF

set INSTALL_CMAKE_FLAGS=-DPROJECTS_USE_PRECOMPILED_HEADERS=OFF -DCASTOR_BUILDGRP_TEST=OFF -DCASTOR_BUILDGRP_INTEROP=OFF -DCASTOR_BUILDGRP_SAMPLE=ON -DCASTOR_BUILDGRP_DIVIDER=ON -DCASTOR_BUILDGRP_TONEMAPS=ON -DCASTOR_BUILDGRP_GENERIC=ON -DCASTOR_BUILDGRP_IMPORTER=ON -DCASTOR_BUILDGRP_POSTFX=ON -DCASTOR_BUILD_SAMPLE_CASTOR_TD=OFF -DCASTOR_BUILD_SAMPLE_CASTOR_VIEWER=ON -DCASTOR_BUILD_TEST_RENDERER_OGL=ON -DCASTOR_FORCE_ALL_IMPORTERS=OFF

if $CU_TEST
then
	cmake -DCMAKE_BUILD_TYPE=Release ../source $TEST_CMAKE_FLAGS
	make -j4
	make test
elif $CU_IMPORTERS
then
	cmake -DCMAKE_BUILD_TYPE=Release ../source $IMPORTERS_CMAKE_FLAGS
	make -j4
elif $CU_DIVIDERS
then
	cmake -DCMAKE_BUILD_TYPE=Release ../source $DIVIDER_CMAKE_FLAGS
	make -j4
elif $CU_POSTFX
then
	cmake -DCMAKE_BUILD_TYPE=Release ../source $POSTFX_CMAKE_FLAGS
	make -j4
elif $CU_TONEMAPS
then
	cmake -DCMAKE_BUILD_TYPE=Release ../source $TONEMAPS_CMAKE_FLAGS
	make -j4
fi
