Castor3D: castor3d::StaticStyle Class Reference
castor3d::StaticStyle Class Reference
#include <StyleStatic.hpp>
Public Member Functions
StaticStyle (castor::String const &name, Engine &engine, castor::String const &fontName)
StaticStyle (castor::String const &name, Scene *scene, Engine &engine, castor::String const &fontName)
void setFont (castor::StringView value)
void setTextMaterial (MaterialObs value)
castor::String const & getFontName () const
MaterialObs getTextMaterial () const
Public Member Functions inherited from castor3d::ControlStyle
virtual C3D_API ~ControlStyle () noexcept=default
ControlStyle (ControlType type, castor::String const &name, Scene *scene, Engine &engine, MouseCursor cursor=MouseCursor::eArrow)
void setBackgroundMaterial (MaterialObs value)
void setForegroundMaterial (MaterialObs value)
void setCursor (MouseCursor value) noexcept
void setBackgroundInvisible (bool value) noexcept
void setForegroundInvisible (bool value) noexcept
bool isBackgroundInvisible () const noexcept
bool isForegroundInvisible () const noexcept
MaterialObs getBackgroundMaterial () const noexcept
MaterialObs getForegroundMaterial () const noexcept
ControlType getType () const noexcept
MouseCursor getCursor () const noexcept
Engine & getEngine () const noexcept
bool hasScene () const noexcept
Scene & getScene () const noexcept
Public Member Functions inherited from castor::NamedBaseT< T >
NamedBaseT (T name) noexcept
Constructor.
T const & getName () const noexcept
Retrieves the name.
void rename (T name) noexcept
Static Public Attributes
static ControlType constexpr Type = ControlType::eStatic
Additional Inherited Members
Protected Member Functions inherited from castor3d::ControlStyle
MaterialObs doCreateMaterial (MaterialObs material, float offset, castor::String const &suffix) const
Protected Attributes inherited from castor::NamedBaseT< T >
T m_name
Constructor & Destructor Documentation
StaticStyle() [1/2]
castor3d::StaticStyle::StaticStyle (castor::String const & name, Engine & engine, castor::String const & fontName) inline
StaticStyle() [2/2]
castor3d::StaticStyle::StaticStyle (castor::String const & name, Scene * scene, Engine & engine, castor::String const & fontName) inline
Member Function Documentation
getFontName()
castor::String const & castor3d::StaticStyle::getFontName () const inline
Referenced by castor3d::FrameStyle::getHeaderFontName(), and castor3d::ProgressStyle::getTextFontName().
getTextMaterial()
MaterialObs castor3d::StaticStyle::getTextMaterial () const inline
Referenced by castor3d::FrameStyle::getHeaderTextMaterial().
setFont()
void castor3d::StaticStyle::setFont (castor::StringView value) inline
Referenced by castor3d::FrameStyle::setHeaderFont(), and castor3d::ProgressStyle::setTextFontName().
setTextMaterial()
void castor3d::StaticStyle::setTextMaterial (MaterialObs value) inline
Referenced by castor3d::FrameStyle::setHeaderTextMaterial(), and castor3d::ProgressStyle::setTextMaterial().
Member Data Documentation
Type
ControlType constexpr castor3d::StaticStyle::Type = ControlType::eStatic static constexpr
The documentation for this class was generated from the following file:
Castor3D/Gui/Theme/StyleStatic.hpp