Castor3D: castor3d::PipelinesNodesT< NodeT > Class Template Reference
castor3d::PipelinesNodesT< NodeT > Class Template Reference
#include <PipelinesNodes.hpp>
Classes
struct PipelineNodes
Public Types
using CulledNode = CulledNodeT< NodeT >
using NodeCommand = NodeCommandT< NodeT >
using RenderedNode = RenderedNodeT< NodeT >
using NodesView = BuffersNodesViewT< NodeT >
Public Member Functions
auto emplace (PipelineAndID const &pipeline, bool isFrontCulled)
void emplace (PipelineAndID const &pipeline, ashes::BufferBase const &buffer, CulledNode const &culled, NodeCommand command, bool isFrontCulled)
void clear () noexcept
auto begin () noexcept
auto begin () const noexcept
auto end () noexcept
auto end () const noexcept
auto size () const noexcept
auto nodesCount () const noexcept
auto empty () const noexcept
size_t occupancy () const noexcept
Static Public Attributes
static uint64_t constexpr maxPipelines = 128ULL
static uint64_t constexpr maxCount = NodesView::maxCount * maxPipelines
Member Typedef Documentation
CulledNode
template<typename NodeT > using castor3d::PipelinesNodesT< NodeT >::CulledNode = CulledNodeT< NodeT >
NodeCommand
template<typename NodeT > using castor3d::PipelinesNodesT< NodeT >::NodeCommand = NodeCommandT< NodeT >
NodesView
template<typename NodeT > using castor3d::PipelinesNodesT< NodeT >::NodesView = BuffersNodesViewT< NodeT >
RenderedNode
template<typename NodeT > using castor3d::PipelinesNodesT< NodeT >::RenderedNode = RenderedNodeT< NodeT >
Member Function Documentation
begin() [1/2]
template<typename NodeT > auto castor3d::PipelinesNodesT< NodeT >::begin () const inline noexcept
begin() [2/2]
template<typename NodeT > auto castor3d::PipelinesNodesT< NodeT >::begin () inline noexcept
clear()
template<typename NodeT > void castor3d::PipelinesNodesT< NodeT >::clear () inline noexcept
emplace() [1/2]
template<typename NodeT > void castor3d::PipelinesNodesT< NodeT >::emplace (PipelineAndID const & pipeline, ashes::BufferBase const & buffer, CulledNode const & culled, NodeCommand command, bool isFrontCulled) inline
References CU_Assert, CU_Exception, castor3d::PipelinesNodesT< NodeT >::emplace(), castor3d::hash(), castor::hashCombine(), castor3d::PipelinesNodesT< NodeT >::maxCount, and castor3d::PipelinesNodesT< NodeT >::nodesCount().
emplace() [2/2]
template<typename NodeT > auto castor3d::PipelinesNodesT< NodeT >::emplace (PipelineAndID const & pipeline, bool isFrontCulled) inline
References castor3d::C3D_EnsureNodesCounts, CU_Assert, CU_Exception, castor3d::PipelineAndID::id, and castor3d::PipelinesNodesT< NodeT >::maxPipelines.
Referenced by castor3d::PipelinesNodesT< NodeT >::emplace().
empty()
template<typename NodeT > auto castor3d::PipelinesNodesT< NodeT >::empty () const inline noexcept
end() [1/2]
template<typename NodeT > auto castor3d::PipelinesNodesT< NodeT >::end () const inline noexcept
end() [2/2]
template<typename NodeT > auto castor3d::PipelinesNodesT< NodeT >::end () inline noexcept
nodesCount()
template<typename NodeT > auto castor3d::PipelinesNodesT< NodeT >::nodesCount () const inline noexcept
Referenced by castor3d::PipelinesNodesT< NodeT >::emplace().
occupancy()
template<typename NodeT > size_t castor3d::PipelinesNodesT< NodeT >::occupancy () const inline noexcept
size()
template<typename NodeT > auto castor3d::PipelinesNodesT< NodeT >::size () const inline noexcept
Member Data Documentation
maxCount
template<typename NodeT > uint64_t constexpr castor3d::PipelinesNodesT< NodeT >::maxCount = NodesView::maxCount * maxPipelines static constexpr
Referenced by castor3d::PipelinesNodesT< NodeT >::emplace().
maxPipelines
template<typename NodeT > uint64_t constexpr castor3d::PipelinesNodesT< NodeT >::maxPipelines = 128ULL static constexpr
Referenced by castor3d::PipelinesNodesT< NodeT >::emplace().
The documentation for this class was generated from the following file:
Castor3D/Render/Node/PipelinesNodes.hpp