Castor3D: castor3d::GpuInformations Class Reference
castor3d::GpuInformations Class Reference
Holds GPU informations.
Public Member Functions
GpuInformations ()
Constructor.
void addFeature (GpuFeature p_feature)
adds a supported feature.
void removeFeature (GpuFeature p_feature)
Removes a supported feature.
void updateFeature (GpuFeature p_feature, bool p_supported)
Updates the support for a feature.
bool hasFeature (GpuFeature p_feature) const
Tells if the feature is supported supports stereo.
bool isStereoAvailable () const
bool hasInstancing () const
bool hasAccumulationBuffer () const
bool hasNonPowerOfTwoTextures () const
bool hasConstantsBuffers () const
bool hasTextureBuffers () const
bool hasShaderStorageBuffers () const
bool checkSupport (ShaderModel p_model) const
Checks support for given shader model.
ShaderModel getMaxShaderModel () const
void updateMaxShaderModel ()
bool hasShaderType (ShaderType p_type) const
void useShaderType (ShaderType p_type, bool p_value)
Defines the support for given shader type.
uint32_t getShaderLanguageVersion () const
void setShaderLanguageVersion (uint32_t p_value)
Defines the shader language version.
int32_t getMinValue (GpuMin p_index) const
void setMinValue (GpuMin p_index, int32_t p_value)
int32_t getMaxValue (GpuMax p_index) const
void setMaxValue (GpuMax p_index, int32_t p_value)
uint32_t getTotalMemorySize () const
void setTotalMemorySize (uint32_t p_value)
castor::String const & getVendor () const
void setVendor (castor::String const &p_value)
castor::String const & getRenderer () const
void setRenderer (castor::String const &p_value)
castor::String const & getVersion () const
void setVersion (castor::String const &p_value)
Protected Attributes
uint32_t m_features { false }
Combination of GpuFeature.
ShaderModel m_maxShaderModel { ShaderModel::eMin }
The maximum supported shader model.
uint32_t m_shaderLanguageVersion { 0 }
The shader language version.
std::array< bool, size_t(ShaderType::eCount) > m_useShader
Tells which types of shaders are supported.
std::map< GpuMin, int32_t > m_minValues
The minimum values.
std::map< GpuMax, int32_t > m_maxValues
The maximum values.
uint32_t m_totalMemorySize
The total VRAM size.
castor::String m_vendor
The GPU vendor name.
castor::String m_renderer
The GPU platform.
castor::String m_version
The rendering API version.
Friends
class Context
Detailed Description
Holds GPU informations.
Author
Sylvain DOREMUS
Date
04/05/2016
Version
0.9.0
Constructor & Destructor Documentation
GpuInformations()
castor3d::GpuInformations::GpuInformations () inline
Constructor.
References castor3d::eCount, m_maxValues, m_minValues, and m_useShader.
Member Function Documentation
addFeature()
void castor3d::GpuInformations::addFeature (GpuFeature p_feature) inline
adds a supported feature.
References m_features.
Referenced by updateFeature().
checkSupport()
bool castor3d::GpuInformations::checkSupport (ShaderModel p_model) const inline
Checks support for given shader model.
Parameters
[in] p_model The shader model.
Returns
false if the given model is not supported by current API.
References m_maxShaderModel.
getMaxShaderModel()
ShaderModel castor3d::GpuInformations::getMaxShaderModel () const inline
Returns
The maximum supported shader model.
References m_maxShaderModel.
getMaxValue()
int32_t castor3d::GpuInformations::getMaxValue (GpuMax p_index) const inline
Parameters
[in] p_index The index.
Returns
The maximum value for given index.
References m_maxValues.
getMinValue()
int32_t castor3d::GpuInformations::getMinValue (GpuMin p_index) const inline
Parameters
[in] p_index The index.
Returns
The minimum value for given index.
References m_minValues.
getRenderer()
castor::String const& castor3d::GpuInformations::getRenderer () const inline
Returns
The GPU platform.
References m_renderer.
getShaderLanguageVersion()
uint32_t castor3d::GpuInformations::getShaderLanguageVersion () const inline
Returns
The shader language version.
References m_shaderLanguageVersion.
getTotalMemorySize()
uint32_t castor3d::GpuInformations::getTotalMemorySize () const inline
Returns
The total VRAM size.
References m_totalMemorySize.
getVendor()
castor::String const& castor3d::GpuInformations::getVendor () const inline
Returns
The GPU vendor name.
References m_vendor.
getVersion()
castor::String const& castor3d::GpuInformations::getVersion () const inline
Returns
The rendering API version.
References m_version.
hasAccumulationBuffer()
bool castor3d::GpuInformations::hasAccumulationBuffer () const inline
Returns
The accumulation buffer support status.
References castor3d::eAccumulationBuffer, and hasFeature().
hasConstantsBuffers()
bool castor3d::GpuInformations::hasConstantsBuffers () const inline
Returns
The constant buffers support status.
References castor3d::eConstantsBuffers, and hasFeature().
hasFeature()
bool castor3d::GpuInformations::hasFeature (GpuFeature p_feature) const inline
Tells if the feature is supported supports stereo.
References m_features.
Referenced by hasAccumulationBuffer(), hasConstantsBuffers(), hasInstancing(), hasNonPowerOfTwoTextures(), hasShaderStorageBuffers(), hasTextureBuffers(), and isStereoAvailable().
hasInstancing()
bool castor3d::GpuInformations::hasInstancing () const inline
Returns
The instanced draw calls support status.
References castor3d::eInstancing, and hasFeature().
hasNonPowerOfTwoTextures()
bool castor3d::GpuInformations::hasNonPowerOfTwoTextures () const inline
Returns
The non power of two textures support status.
References castor3d::eNonPowerOfTwoTextures, and hasFeature().
hasShaderStorageBuffers()
bool castor3d::GpuInformations::hasShaderStorageBuffers () const inline
Returns
The SSBO support status.
References castor3d::eShaderStorageBuffers, and hasFeature().
hasShaderType()
bool castor3d::GpuInformations::hasShaderType (ShaderType p_type) const inline
Parameters
[in] p_type The shader type.
Returns
The shader type support status.
References m_useShader.
hasTextureBuffers()
bool castor3d::GpuInformations::hasTextureBuffers () const inline
Returns
The texture buffers support status.
References castor3d::eTextureBuffers, and hasFeature().
isStereoAvailable()
bool castor3d::GpuInformations::isStereoAvailable () const inline
Returns
The stereo support status.
References castor3d::eStereo, and hasFeature().
removeFeature()
void castor3d::GpuInformations::removeFeature (GpuFeature p_feature) inline
Removes a supported feature.
References m_features.
Referenced by updateFeature().
setMaxValue()
void castor3d::GpuInformations::setMaxValue (GpuMax p_index, int32_t p_value) inline
Parameters
[in] p_index The index.
[in] p_value The maximum value for given index.
References m_maxValues.
setMinValue()
void castor3d::GpuInformations::setMinValue (GpuMin p_index, int32_t p_value) inline
Parameters
[in] p_index The index.
[in] p_value The minimum value for given index.
References m_minValues.
setRenderer()
void castor3d::GpuInformations::setRenderer (castor::String const & p_value) inline
Parameters
[in] p_value The GPU platform.
References m_renderer.
setShaderLanguageVersion()
void castor3d::GpuInformations::setShaderLanguageVersion (uint32_t p_value) inline
Defines the shader language version.
Parameters
[in] p_value The version.
References m_shaderLanguageVersion.
setTotalMemorySize()
void castor3d::GpuInformations::setTotalMemorySize (uint32_t p_value) inline
Parameters
[in] p_value The total VRAM size.
References m_totalMemorySize.
setVendor()
void castor3d::GpuInformations::setVendor (castor::String const & p_value) inline
Parameters
[in] p_value The GPU vendor name.
References m_vendor.
setVersion()
void castor3d::GpuInformations::setVersion (castor::String const & p_value) inline
Parameters
[in] p_value The rendering API version.
References m_version.
updateFeature()
void castor3d::GpuInformations::updateFeature (GpuFeature p_feature, bool p_supported) inline
Updates the support for a feature.
References addFeature(), and removeFeature().
updateMaxShaderModel()
void castor3d::GpuInformations::updateMaxShaderModel () inline
Returns
The maximum supported shader model.
References castor3d::eCompute, castor3d::eGeometry, castor3d::eHull, castor3d::eModel1, castor3d::eModel2, castor3d::eModel3, castor3d::eModel4, castor3d::eModel5, castor3d::ePixel, m_maxShaderModel, and m_useShader.
useShaderType()
void castor3d::GpuInformations::useShaderType (ShaderType p_type, bool p_value) inline
Defines the support for given shader type.
Parameters
[in] p_type The shader type.
[in] p_value The new value.
References m_useShader.
Friends And Related Function Documentation
Context
friend class Context friend
Member Data Documentation
m_features
uint32_t castor3d::GpuInformations::m_features { false } protected
Combination of GpuFeature.
Referenced by addFeature(), hasFeature(), and removeFeature().
m_maxShaderModel
ShaderModel castor3d::GpuInformations::m_maxShaderModel { ShaderModel::eMin } protected
The maximum supported shader model.
Referenced by checkSupport(), getMaxShaderModel(), and updateMaxShaderModel().
m_maxValues
std::map< GpuMax, int32_t > castor3d::GpuInformations::m_maxValues protected
The maximum values.
Referenced by getMaxValue(), GpuInformations(), and setMaxValue().
m_minValues
std::map< GpuMin, int32_t > castor3d::GpuInformations::m_minValues protected
The minimum values.
Referenced by getMinValue(), GpuInformations(), and setMinValue().
m_renderer
castor::String castor3d::GpuInformations::m_renderer protected
The GPU platform.
Referenced by getRenderer(), and setRenderer().
m_shaderLanguageVersion
uint32_t castor3d::GpuInformations::m_shaderLanguageVersion { 0 } protected
The shader language version.
Referenced by getShaderLanguageVersion(), and setShaderLanguageVersion().
m_totalMemorySize
uint32_t castor3d::GpuInformations::m_totalMemorySize protected
The total VRAM size.
Referenced by getTotalMemorySize(), and setTotalMemorySize().
m_useShader
std::array< bool, size_t(ShaderType::eCount) > castor3d::GpuInformations::m_useShader protected
Tells which types of shaders are supported.
Referenced by GpuInformations(), hasShaderType(), updateMaxShaderModel(), and useShaderType().
m_vendor
castor::String castor3d::GpuInformations::m_vendor protected
The GPU vendor name.
Referenced by getVendor(), and setVendor().
m_version
castor::String castor3d::GpuInformations::m_version protected
The rendering API version.
Referenced by getVersion(), and setVersion().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Miscellaneous/GpuInformations.hpp