Castor3D: castor Namespace Reference
castor Namespace Reference
Namespaces
namespace debug
namespace details
namespace format
namespace hashcomb
namespace manip
namespace matrix
Matrix basic operations.
namespace point
Point helper functions.
namespace string
String functions namespace.
namespace system
Classes
struct AdditionalParsers
class Aligned
Templated class that provide alignment support.
class AlignedFrom
Templated class that provide alignment support.
class AlignedMemoryAllocator
Memory allocator.
class AngleT
Angle helper class.
class ArrayView
Templated class that provide std::array style buffer view.
class AsyncJobQueue
class BinaryFile
User friendly File class.
class BinaryLoader
Partial castor::Loader specialisation for binary files.
class BinaryWriter
Partial castor::Loader specialisation for binary files.
struct BlockContext
struct BlockGuard
Allows to declare a scoped variable with an action on construction
and an action on destruction.
class BlockTimer
class BlockTracker
class BlueNoise
class BoundingBox
class BoundingContainer
Box container class.
class BoundingSphere
class BuddyAllocatorT
Buddy allocator implementation.
struct BuddyAllocatorTraits
struct CallTraits
Struct used to select best way to put type in parameter : 'value' or 'const reference'.
class ChangeTrackedT
Templated class that provide std::array style buffer view.
struct CheckedMutexT
class ColourComponent
class ConnectionT
Connection to a signal.
class ConsoleImpl
struct ConstPixelIterator
Pixel buffer iterator.
struct ContextDeleter
struct ContextDeleterT
class Coords
Templated static dimensions point representation.
class CpuInformations
Retrieves the basic CPU informations.
class DataHolderT
Some data holder.
class DataImageLoader
Raw data image loader.
struct DebugLoggerStreambufTraitsT
Streambuf traits for debug logging.
struct Deleter
struct Deleter< castor3d::BaseDataComponentT< SubmeshDataT, DataT > >
struct Deleter< ResourceT< ResT, KeyT > >
struct DummyFunctorT
Cached resource dummy functor (for initialise and clean).
class DynamicBitsetT
Dynamic bitset class, with configurable block type.
class DynamicLibrary
struct ErrorLoggerStreambufTraitsT
Streambuf traits for error logging.
class Exception
class ExrImageLoader
Image loader based on stb_image.
struct Fact
Factorial recursive case.
struct Fact< T, 0 >
Factorial end case.
class Factory
Factory concept implementation.
struct FactoryEntryT
class File
class FileParser
class FileParserContext
struct FileTyper
Helper structure to find File type (BinaryFile or TextFile) from FileType.
struct FileTyper< FileType::eBinary >
struct FileTyper< FileType::eText >
Helper structure to find File type (BinaryFile or TextFile) from FileType.
class FileWriter
Main resource writer class.
class FlagCombination
Template class providing implicit conversion from a scoped enum to its integral base type.
struct FlagIterator
Template iterator class on a binary combination of flags.
struct FlagIteratorTraitsT
Template iterator traits class on a binary combination of flags.
class Font
class FractalNoiseT
Fractal noise generator for PerlinNoise or SimplexNoise.
class FreeImageLoader
Image loader based on stb_image.
class GliImageLoader
Image loader based on gli.
class GliImageWriter
class Glyph
class Grid
class GroupChangeTrackedT
Templated class that provide std::array style buffer view.
struct HasAlpha
Helper struct to tell if a pixel format is compressed.
struct HasBaseParameterType
Structure used to tell if an ParameterType has a base parameter type.
struct HasBaseParameterType< ParameterType::eBitwiseOred32BitsCheckedText >
HasBaseParameterType specialisation for ParameterType::eBitwiseOred32BitsCheckedText.
struct HasBaseParameterType< ParameterType::eBitwiseOred64BitsCheckedText >
HasBaseParameterType specialisation for ParameterType::eBitwiseOred64BitsCheckedText.
struct HasBaseParameterType< ParameterType::eCheckedText >
HasBaseParameterType specialisation for ParameterType::eCheckedText.
struct HasBaseParameterType< ParameterType::eName >
HasBaseParameterType specialisation for ParameterType::eName.
class HdrColourComponent
class Image
struct ImageCreateParams
struct ImageLayout
class ImageLoader
struct ImageLoaderConfig
The image loading configuration.
class ImageLoaderImpl
class ImageWriter
class ImageWriterImpl
class IndexedRangeT
A range inside a sequence.
struct InfoLoggerStreambufTraitsT
Streambuf traits for info logging.
struct Is16FComponents
Helper struct to tell if a pixel format uses floating point 16 bits components.
struct Is16SComponents
Helper struct to tell if a pixel format uses signed 16 bits components.
struct Is16UComponents
Helper struct to tell if a pixel format uses unsigned 16 bits components.
struct Is32FComponents
Helper struct to tell if a pixel format uses floating point 32 bits components.
struct Is32SComponents
Helper struct to tell if a pixel format uses signed 32 bits components.
struct Is32UComponents
Helper struct to tell if a pixel format uses unsigned 32 bits components.
struct Is64FComponents
Helper struct to tell if a pixel format uses floating point 64 bits components.
struct Is64SComponents
Helper struct to tell if a pixel format uses signed 64 bits components.
struct Is64UComponents
Helper struct to tell if a pixel format uses unsigned 64 bits components.
struct Is8SComponents
Helper struct to tell if a pixel format uses signed 8 bits components.
struct Is8SRGBComponents
Helper struct to tell if a pixel format uses unsigned 8 bits components.
struct Is8UComponents
Helper struct to tell if a pixel format uses unsigned 8 bits components.
struct IsArithmeticType
Structure used to tell if a ParameterType is an arithmetic type.
struct IsArithmeticType< ParameterType::eDouble >
Structure used to tell if a ParameterType is an arithmetic type.
struct IsArithmeticType< ParameterType::eFloat >
Structure used to tell if a ParameterType is an arithmetic type.
struct IsArithmeticType< ParameterType::eInt16 >
Structure used to tell if a ParameterType is an arithmetic type.
struct IsArithmeticType< ParameterType::eInt32 >
Structure used to tell if a ParameterType is an arithmetic type.
struct IsArithmeticType< ParameterType::eInt64 >
Structure used to tell if a ParameterType is an arithmetic type.
struct IsArithmeticType< ParameterType::eInt8 >
Structure used to tell if a ParameterType is an arithmetic type.
struct IsArithmeticType< ParameterType::eLongDouble >
Structure used to tell if a ParameterType is an arithmetic type.
struct IsArithmeticType< ParameterType::eUInt16 >
Structure used to tell if a ParameterType is an arithmetic type.
struct IsArithmeticType< ParameterType::eUInt32 >
Structure used to tell if a ParameterType is an arithmetic type.
struct IsArithmeticType< ParameterType::eUInt64 >
Structure used to tell if a ParameterType is an arithmetic type.
struct IsArithmeticType< ParameterType::eUInt8 >
Structure used to tell if a ParameterType is an arithmetic type.
struct IsChangeTrackedT
struct IsChangeTrackedT< ChangeTrackedT< ValueT, ControlT > >
struct IsChangeTrackedT< GroupChangeTrackedT< ValueT, ControlT > >
struct IsColourFormat
Helper struct to tell if a pixel format represents a colour.
struct IsCompressed
Helper struct to tell if a pixel format is compressed.
struct IsD16UComponent
Helper struct to tell if a pixel format uses unsigned 16 bits depth component.
struct IsD24UComponent
Helper struct to tell if a pixel format uses unsigned 24 bits depth component.
struct IsD32FComponent
Helper struct to tell if a pixel format uses floating point 32 bits depth component.
struct IsDepthFormat
Helper struct to tell if a pixel format represents a depth pixel.
struct IsDepthStencilFormat
Helper struct to tell if a pixel format represents a depth or stencil pixel.
struct IsGroupChangeTrackedT
struct IsGroupChangeTrackedT< GroupChangeTrackedT< ValueT, ControlT > >
struct IsLengthT
struct IsLengthT< LengthT< TypeT > >
struct IsRangedValueT
struct IsRangedValueT< RangedValue< T > >
struct IsS8UComponent
Helper struct to tell if a pixel format uses only an unsigned 8 bits stencil component.
struct IsSpeedT
struct IsSpeedT< SpeedT< ValueT, Microseconds > >
struct IsSpeedT< SpeedT< ValueT, Milliseconds > >
struct IsSpeedT< SpeedT< ValueT, Nanoseconds > >
struct IsSpeedT< SpeedT< ValueT, Seconds > >
struct IsStencilFormat
Helper struct to tell if a pixel format represents a stencil pixel.
struct IteratorTraits
struct IteratorTraits< TypeT * >
struct KernelBoxFilterT
struct KernelLanczosFilterT
struct LargerTyperT
Retrieves the type larger than the given one.
class LengthT
Length helper class.
class Line2D
2D line equation
class Line3D
3D line equation
struct Ln
Neperian Logarithm using template implementation.
class Loader
Main resource loader class.
class LoaderException
Resource loading exception.
class Logger
class LoggerImpl
class LoggerInstance
class LoggerStreambufT
struct LoggerStreamT
struct LogN
Neperian Logarithm recursive case.
struct LogN< 0, T >
Neperian Logarithm end case.
class Matrix
Templated column major matrix representation.
struct MaxValue
Used to have the maximum value of two, at compile time.
struct MaxValue< A, B, std::enable_if_t<(A >=B) > >
Used to have the maximum value of two, at compile time.
struct MaxValue< A, B, std::enable_if_t<(B > A) > >
Used to have the maximum value of two, at compile time.
struct Message
Message representation.
struct MinValue
Used to have the minimum value of two, at compile time.
struct MinValue< A, B, std::enable_if_t<(A<=B) > >
Used to have the minimum value of two, at compile time.
struct MinValue< A, B, std::enable_if_t<(B< A) > >
Used to have the minimum value of two, at compile time.
class NamedBaseT
Class for named elements.
struct NoInit
Structure used to construct objects but without initialisation.
class NonAlignedMemoryAllocator
class NonCopyable
class NonMovable
class OwnedBy
Class used to have an object owned by another one.
struct ParserEnumTraits
Parser parameter helper structure.
struct ParserEnumTraits< castor3d::BillboardSize >
struct ParserEnumTraits< castor3d::BillboardType >
struct ParserEnumTraits< castor3d::BlendMode >
struct ParserEnumTraits< castor3d::BorderPosition >
struct ParserEnumTraits< castor3d::FogType >
struct ParserEnumTraits< castor3d::GlobalIlluminationType >
struct ParserEnumTraits< castor3d::HAlign >
struct ParserEnumTraits< castor3d::InterpolatorType >
struct ParserEnumTraits< castor3d::LightType >
struct ParserEnumTraits< castor3d::LimitedType< VkCompareOp > >
struct ParserEnumTraits< castor3d::LimitedType< VkPrimitiveTopology > >
struct ParserEnumTraits< castor3d::MovableType >
struct ParserEnumTraits< castor3d::ParallaxOcclusionMode >
struct ParserEnumTraits< castor3d::ParticleFormat >
struct ParserEnumTraits< castor3d::ShadowType >
struct ParserEnumTraits< castor3d::TextLineSpacingMode >
struct ParserEnumTraits< castor3d::TextTexturingMode >
struct ParserEnumTraits< castor3d::TextWrappingMode >
struct ParserEnumTraits< castor3d::VAlign >
struct ParserEnumTraits< castor3d::ViewportType >
struct ParserEnumTraits< LengthUnit >
struct ParserEnumTraits< VkBlendFactor >
struct ParserEnumTraits< VkBlendOp >
struct ParserEnumTraits< VkBorderColor >
struct ParserEnumTraits< VkCompareOp >
struct ParserEnumTraits< VkFilter >
struct ParserEnumTraits< VkImageType >
struct ParserEnumTraits< VkPrimitiveTopology >
struct ParserEnumTraits< VkSamplerAddressMode >
struct ParserEnumTraits< VkSamplerMipmapMode >
struct ParserEnumTraits< VkShaderStageFlagBits >
struct ParserFunctionAndParams
The parser function and expected parameters.
class ParserParameter
Specified parser parameter.
class ParserParameter< ParameterType::eBitwiseOred32BitsCheckedText >
ParserParameter specialisation for ePARAMETER_TYPE_BITWISE_ORED_CHECKED_TEXT.
class ParserParameter< ParameterType::eBitwiseOred64BitsCheckedText >
ParserParameter specialisation for ParameterType::eBitwiseOred64BitsCheckedText.
class ParserParameter< ParameterType::eCheckedText >
ParserParameter specialisation for ParameterType::eCheckedText.
class ParserParameter< ParameterType::eName >
ParserParameter specialisation for ParameterType::eName.
class ParserParameter< Type, std::enable_if_t< !hasBaseParameterTypeV< Type > &&!isArithmeticTypeV< Type > > >
Specified parser parameter.
class ParserParameter< Type, std::enable_if_t< IsArithmeticType< Type >::value > >
Specified parser parameter.
class ParserParameterBase
struct ParserParameterHelper
Parser parameter helper structure.
struct ParserParameterHelper< ParameterType::eBitwiseOred32BitsCheckedText >
ParserParameterHelper specialisation for ParameterType::eBitwiseOred32BitsCheckedText.
struct ParserParameterHelper< ParameterType::eBitwiseOred64BitsCheckedText >
ParserParameterHelper specialisation for ParameterType::eBitwiseOred64BitsCheckedText.
struct ParserParameterHelper< ParameterType::eBool >
ParserParameterHelper specialisation for ParameterType::eBool.
struct ParserParameterHelper< ParameterType::eCheckedText >
ParserParameterHelper specialisation for ParameterType::eCheckedText.
struct ParserParameterHelper< ParameterType::eDouble >
ParserParameterHelper specialisation for ParameterType::eDouble.
struct ParserParameterHelper< ParameterType::eFloat >
ParserParameterHelper specialisation for ParameterType::eFloat.
struct ParserParameterHelper< ParameterType::eHdrRgbaColour >
ParserParameterHelper specialisation for ParameterType::eHdrColour.
struct ParserParameterHelper< ParameterType::eHdrRgbColour >
ParserParameterHelper specialisation for ParameterType::eHdrColour.
struct ParserParameterHelper< ParameterType::eInt16 >
ParserParameterHelper specialisation for ParameterType::eInt16.
struct ParserParameterHelper< ParameterType::eInt32 >
ParserParameterHelper specialisation for ParameterType::eInt32.
struct ParserParameterHelper< ParameterType::eInt64 >
ParserParameterHelper specialisation for ParameterType::eInt64.
struct ParserParameterHelper< ParameterType::eInt8 >
ParserParameterHelper specialisation for ParameterType::eInt8.
struct ParserParameterHelper< ParameterType::eLongDouble >
ParserParameterHelper specialisation for ParameterType::eLongDouble.
struct ParserParameterHelper< ParameterType::eName >
ParserParameterHelper specialisation for ParameterType::eName.
struct ParserParameterHelper< ParameterType::ePath >
ParserParameterHelper specialisation for ParameterType::ePath.
struct ParserParameterHelper< ParameterType::ePixelFormat >
ParserParameterHelper specialisation for ParameterType::ePixelFormat.
struct ParserParameterHelper< ParameterType::ePoint2D >
ParserParameterHelper specialisation for ParameterType::ePoint2D.
struct ParserParameterHelper< ParameterType::ePoint2F >
ParserParameterHelper specialisation for ParameterType::ePoint2F.
struct ParserParameterHelper< ParameterType::ePoint2I >
ParserParameterHelper specialisation for ParameterType::ePoint2I.
struct ParserParameterHelper< ParameterType::ePoint2U >
ParserParameterHelper specialisation for ParameterType::ePoint2U.
struct ParserParameterHelper< ParameterType::ePoint3D >
ParserParameterHelper specialisation for ParameterType::ePoint3D.
struct ParserParameterHelper< ParameterType::ePoint3F >
ParserParameterHelper specialisation for ParameterType::ePoint3F.
struct ParserParameterHelper< ParameterType::ePoint3I >
ParserParameterHelper specialisation for ParameterType::ePoint3I.
struct ParserParameterHelper< ParameterType::ePoint3U >
ParserParameterHelper specialisation for ParameterType::ePoint3U.
struct ParserParameterHelper< ParameterType::ePoint4D >
ParserParameterHelper specialisation for ParameterType::ePoint4D.
struct ParserParameterHelper< ParameterType::ePoint4F >
ParserParameterHelper specialisation for ParameterType::ePoint4F.
struct ParserParameterHelper< ParameterType::ePoint4I >
ParserParameterHelper specialisation for ParameterType::ePoint4I.
struct ParserParameterHelper< ParameterType::ePoint4U >
ParserParameterHelper specialisation for ParameterType::ePoint4U.
struct ParserParameterHelper< ParameterType::ePosition >
ParserParameterHelper specialisation for ParameterType::ePosition.
struct ParserParameterHelper< ParameterType::eRectangle >
ParserParameterHelper specialisation for ParameterType::eRectangle.
struct ParserParameterHelper< ParameterType::eRgbaColour >
ParserParameterHelper specialisation for ParameterType::eColour.
struct ParserParameterHelper< ParameterType::eRgbColour >
ParserParameterHelper specialisation for ParameterType::eColour.
struct ParserParameterHelper< ParameterType::eSize >
ParserParameterHelper specialisation for ParameterType::eSize.
struct ParserParameterHelper< ParameterType::eText >
ParserParameterHelper specialisation for ParameterType::eText.
struct ParserParameterHelper< ParameterType::eUInt16 >
ParserParameterHelper specialisation for ParameterType::eUInt16.
struct ParserParameterHelper< ParameterType::eUInt32 >
ParserParameterHelper specialisation for ParameterType::eUInt32.
struct ParserParameterHelper< ParameterType::eUInt64 >
ParserParameterHelper specialisation for ParameterType::eUInt64.
struct ParserParameterHelper< ParameterType::eUInt8 >
ParserParameterHelper specialisation for ParameterType::eUInt8.
class ParserParameterTypeException
Exception thrown when the user tries to retrieve a parameter of a wrong type.
class Path
class PerlinNoiseT
3D Perlin noise generator.
class Pixel
Pixel definition.
struct PixelComponentsT
Holds colour/depth/stencil PixelComponentsT helper functions.
struct PixelDefinitionsT
Helper struct that holds pixel size, toString and converion functions.
struct PixelIterator
Pixel buffer iterator.
class PlaneEquation
class Point
Templated static dimensions point representation.
struct PointComponentGetT
struct PointComponentGetT< LengthT< TypeT > >
struct PointComponentGetT< Point< TypeT, 2u > >
struct PointComponentGetT< Point< TypeT, 3u > >
struct PointComponentGetT< Point< TypeT, 4u > >
struct PointData
Data holder for a point.
struct PointData< T, 2u >
struct PointData< T, 3u >
struct PointData< T, 4u >
struct PointTyperT
struct PointTyperT< LengthT< SrcT >, DstCompT >
struct PointTyperT< Point< SrcCompT, CountT >, DstCompT >
class Position
union PositionData
struct Power
Power recursive case.
struct Power< T, 0 >
Power end case.
struct Power< T, 1 >
Power end case.
class PreciseTimer
class PreprocessedFile
class ProgramConsole
struct PtAssignOperators
Point assignment operators.
struct PtOperators
Point operators.
class PxBuffer
Pixel buffer class, with pixel format as a template param.
class PxBufferBase
struct PxBufferConvertOptions
struct PxCompressionSupport
class QuaternionT
Quaternion representation class.
class Range
A range class.
class RangedValue
A value inside a range.
struct RangedValueGetterT
struct RangedValueGetterT< RangedValue< T > >
class RangeSequenceT
A contiguous ranges sequence.
class Rectangle
union RectangleData
struct RegexFormat
Gives the regex format for given type.
struct RegexFormat< double >
RegexFormat specialisation for double.
struct RegexFormat< float >
RegexFormat specialisation for float.
struct RegexFormat< HdrRgbaColour >
RegexFormat specialisation for HdrRgbaColour.
struct RegexFormat< HdrRgbColour >
RegexFormat specialisation for HdrRgbColour.
struct RegexFormat< int16_t >
RegexFormat specialisation for int16_t.
struct RegexFormat< int32_t >
RegexFormat specialisation for int32_t.
struct RegexFormat< int64_t >
RegexFormat specialisation for int64_t.
struct RegexFormat< int8_t >
RegexFormat specialisation for int8_t.
struct RegexFormat< long double >
RegexFormat specialisation for long double.
struct RegexFormat< RgbaColour >
RegexFormat specialisation for RgbaColour.
struct RegexFormat< RgbColour >
RegexFormat specialisation for RgbColour.
struct RegexFormat< uint16_t >
RegexFormat specialisation for uint16_t.
struct RegexFormat< uint32_t >
RegexFormat specialisation for uint32_t.
struct RegexFormat< uint64_t >
RegexFormat specialisation for uint64_t.
struct RegexFormat< uint8_t >
RegexFormat specialisation for uint8_t.
class ResourceCacheBaseT
Base class for an element cache.
class ResourceCacheT
Base class for an element cache.
class ResourceCacheT< castor3d::AnimatedObjectGroup, String, castor3d::AnimatedObjectGroupCacheTraits >
AnimatedObjectGroup cache.
class ResourceCacheT< castor3d::Material, String, castor3d::MaterialCacheTraits >
Material collection, with additional functions.
class ResourceCacheT< castor3d::Overlay, String, castor3d::OverlayCacheTraits >
Overlay collection, with additional add and remove functions to manage Z-Index.
class ResourceCacheT< castor3d::Plugin, String, castor3d::PluginCacheTraits >
Plug-ins cache.
class ResourceCacheT< Font, String, FontCacheTraits >
class ResourceCacheT< Image, String, ImageCacheTraits >
struct ResourceCacheTraitsBaseT
struct ResourceCacheTraitsT
struct ResourceCacheTraitsT< Font, String >
struct ResourceCacheTraitsT< Image, String >
struct ResourceCleanerT
Cached resource cleaner.
struct ResourceInitialiserT
Cached resource initialiser.
struct ResourceMergerT
Cached resources merger.
class ResourceT
External resource representation.
class RgbaColourT
RGBA colour representation.
class RgbColourT
RGB colour representation.
class ScopeGuard
Class used to execute code at scope exit.
class SignalT
Basic signal class.
class SimplexNoiseT
3D Simplex noise generator.
struct SingleComponentT
Gives the format of a single component of a pixel format.
class Size
union SizeData
class SpeedT
A speed.
struct SpeedTraitsT
The traits for aspeed.
struct SpeedTraitsT< AngleT< ValueT > >
struct SpeedTraitsT< Point< ValueT, 2 > >
struct SpeedTraitsT< Point< ValueT, 3 > >
struct SpeedTraitsT< Point< ValueT, 4 > >
class SphericalVertex
class SpinMutex
class SquareMatrix
Templated column major square matrix representation.
class StbImageLoader
Image loader based on stb_image.
class StbImageWriter
struct StringHash
class TextFile
Text file class.
struct TextLineMetrics
The metrics for a line of text.
class TextLoaderT
struct TextMetrics
The metrics for a text.
class TextWriter
class TextWriter< Coords< ValueT, 1u > >
class TextWriter< Coords< ValueT, 2u > >
class TextWriter< Coords< ValueT, 3u > >
class TextWriter< Coords< ValueT, 4u > >
class TextWriter< double >
class TextWriter< float >
class TextWriter< Font >
class TextWriter< int16_t >
class TextWriter< int32_t >
class TextWriter< int64_t >
class TextWriter< int8_t >
class TextWriter< Point< ValueT, 1u > >
class TextWriter< Point< ValueT, 2u > >
class TextWriter< Point< ValueT, 3u > >
class TextWriter< Point< ValueT, 4u > >
class TextWriter< Position >
class TextWriter< QuaternionT< ValueT > >
class TextWriter< RgbaColourT< ComponentT > >
class TextWriter< RgbColourT< ComponentT > >
class TextWriter< Size >
class TextWriter< String >
class TextWriter< uint16_t >
class TextWriter< uint32_t >
class TextWriter< uint64_t >
class TextWriter< uint8_t >
class TextWriterBase
class TextWriterT
Partial castor::Writer specialisation for text files.
class ThreadPool
struct TraceLoggerStreambufTraitsT
Streambuf traits for trace logging.
class TSConnectionT
Connection to a thread safe signal.
class TSSignalT
Thread safe signal class.
class UnicityException
class Unique
Representation of a Unique instance class.
class UnsupportedFormatException
struct ValueParser
Helper structure to parse a value.
struct WarningLoggerStreambufTraitsT
Streambuf traits for warning logging.
class WhiteNoise
class WorkerThread
class Writer
Main resource writer class.
class XpmImageLoader
class ZipArchive
Concepts
concept FloatingT
concept Vector2T
concept Vector3T
concept Vector4T
concept Vector2fT
concept Vector3fT
concept Vector4fT
concept Vector2dT
concept Vector3dT
concept Vector4dT
Typedefs
using s8 = int8_t
using u8 = uint8_t
using byte = uint8_t
using s16 = int16_t
using u16 = uint16_t
using s32 = int32_t
using u32 = uint32_t
using s64 = int64_t
using u64 = uint64_t
using usize = size_t
using f32 = float
using f64 = double
using xchar = char
using mbchar = char
using wchar = wchar_t
using u32char = char32_t
using String = std::basic_string< xchar >
using StringView = std::basic_string_view< xchar >
using StringStream = std::basic_stringstream< xchar >
using OutputStringStream = std::basic_ostringstream< xchar >
using InputStringStream = std::basic_istringstream< xchar >
using OutputStream = std::basic_ostream< xchar >
using InputStream = std::basic_istream< xchar >
using MbString = std::basic_string< mbchar >
using MbStringView = std::basic_string_view< mbchar >
using MbStringStream = std::basic_stringstream< mbchar >
using MbOutputStringStream = std::basic_ostringstream< mbchar >
using MbInputStringStream = std::basic_istringstream< mbchar >
using MbOutputStream = std::basic_ostream< mbchar >
using MbInputStream = std::basic_istream< mbchar >
using WString = std::basic_string< wchar >
using WStringView = std::basic_string_view< wchar >
using WStringStream = std::basic_stringstream< wchar >
using WOutputStringStream = std::basic_ostringstream< wchar >
using WInputStringStream = std::basic_istringstream< wchar >
using WOutputStream = std::basic_ostream< wchar >
using WInputStream = std::basic_istream< wchar >
using U32String = std::basic_string< u32char >
using U32StringView = std::basic_string_view< u32char >
using U32StringStream = std::basic_stringstream< u32char >
using U32OutputStringStream = std::basic_ostringstream< u32char >
using U32InputStringStream = std::basic_istringstream< u32char >
using U32OutputStream = std::basic_ostream< u32char >
using U32InputStream = std::basic_istream< u32char >
template<class FuncT >
using Function = std::function< FuncT >
template<typename FirstT , typename SecondT >
using Pair = std::pair< FirstT, SecondT >
template<typename KeyT , typename PredT = std::less<>, typename AllocT = std::allocator< KeyT >>
using Set = std::set< KeyT, PredT, AllocT >
template<typename KeyT , typename DataT , typename PredT = std::less<>, typename AllocT = std::allocator< Pair< KeyT const, DataT > >>
using Map = std::map< KeyT, DataT, PredT, AllocT >
template<typename KeyT , typename DataT , typename PredT = std::less<>, typename AllocT = std::allocator< Pair< KeyT const, DataT > >>
using MultiMap = std::multimap< KeyT, DataT, PredT, AllocT >
template<typename KeyT , typename DataT , typename PredT = std::less<>, typename AllocT = std::allocator< KeyT >>
using MultiSet = std::multiset< KeyT, PredT, AllocT >
template<typename KeyT , typename DataT , typename HashT = std::hash< KeyT >, typename KeyEqT = std::equal_to<>, typename AllocT = std::allocator< Pair< KeyT const, DataT > >>
using UnorderedMap = std::unordered_map< KeyT, DataT, HashT, KeyEqT, AllocT >
template<typename KeyT , typename HashT = std::hash< KeyT >, typename KeyEqT = std::equal_to<>, typename AllocT = std::allocator< KeyT >>
using UnorderedSet = std::unordered_set< KeyT, HashT, KeyEqT >
template<typename DataT , typename AllocT = std::allocator< DataT >>
using Vector = std::vector< DataT, AllocT >
template<typename DataT , typename AllocT = std::allocator< DataT >>
using List = std::list< DataT, AllocT >
template<typename DataT , size_t SizeT>
using Array = std::array< DataT, SizeT >
template<class DataT , class AllocT = std::allocator< DataT >>
using Deque = std::deque< DataT, AllocT >
template<typename DataT , class ContainerT = Deque< DataT >>
using Stack = std::stack< DataT, ContainerT >
template<typename DataT >
using StringMap = Map< String, DataT >
template<typename DataT >
using UnorderedStringMap = std::unordered_map< String, DataT, StringHash, std::equal_to<> >
using StringSet = std::set< String, StringHash, std::equal_to<> >
using UnorderedStringSet = std::unordered_set< String, StringHash, std::equal_to<> >
using Seconds = std::chrono::seconds
using Milliseconds = std::chrono::milliseconds
using Microseconds = std::chrono::microseconds
using Nanoseconds = std::chrono::nanoseconds
template<typename Lockable >
using UniqueLock = std::unique_lock< Lockable >
using Mutex = std::mutex
using RecursiveMutex = std::recursive_mutex
using CheckedMutex = CheckedMutexT< castor::Mutex >
template<class DataT >
using ReferenceWrapper = std::reference_wrapper< DataT >
template<class DataT >
using SharedPtr = std::shared_ptr< DataT >
template<typename TypeT , class DelT = std::default_delete< TypeT >>
using RawUniquePtr = std::unique_ptr< TypeT, DelT >
template<typename TypeT >
using UniquePtr = RawUniquePtr< TypeT, Deleter< TypeT > >
using FileOpenModes = castor::FlagCombination< File :: OpenMode >
using FileCreateModes = castor::FlagCombination< File :: CreateMode >
using ContextDeleterPtr = castor::RawUniquePtr< ContextDeleter >
using FontRes = FontCacheTraits::ElementPtrT
using FontResPtr = FontCacheTraits::ElementObsT
using ImageCacheTraits = ResourceCacheTraitsT< Image, String >
using ImageCache = ResourceCacheT< Image, String, ImageCacheTraits >
using ImageRes = ImageCacheTraits::ElementPtrT
using ImageResPtr = ImageCacheTraits::ElementObsT
template<typename CharT >
using TraceLoggerStreambufT = LoggerStreambufT< CharT, TraceLoggerStreambufTraitsT< CharT > >
template<typename CharT >
using DebugLoggerStreambufT = LoggerStreambufT< CharT, DebugLoggerStreambufTraitsT< CharT > >
template<typename CharT >
using InfoLoggerStreambufT = LoggerStreambufT< CharT, InfoLoggerStreambufTraitsT< CharT > >
template<typename CharT >
using WarningLoggerStreambufT = LoggerStreambufT< CharT, WarningLoggerStreambufTraitsT< CharT > >
template<typename CharT >
using ErrorLoggerStreambufT = LoggerStreambufT< CharT, ErrorLoggerStreambufTraitsT< CharT > >
template<typename T >
using QuaternionDataT = PointData< T, 4u >
template<typename T >
using UnRangedValueT = typename RangedValueGetterT< T >::Type
using VoidFnType = void(CU_stdcall *)()
using BuddyAllocator = BuddyAllocatorT< BuddyAllocatorTraits >
STL typedefs
using Regex = std::basic_regex< xchar >
using RegexIterator = std::regex_iterator< String::const_iterator >
using MatchResults = std::match_results< String::const_iterator >
Log
using MessageQueue = Deque< Message >
The message queue.
using LogCallback = castor::Function< void(MbString const & text, LogType type, bool newLine) >
Logging callback function.
using LoggerInstancePtr = castor::RawUniquePtr< LoggerInstance >
Enumerations
enum class UnicityError { eNoInstance = 0 , eAnInstance = 1 , eCount , eMin = eNoInstance }
Unicity errors enumeration.
enum class LogType : uint8_t {
eTrace , eDebug , eInfo , eWarning ,
eError , eCount
}
Defines the various log types.
File Parser
enum class ParameterType : uint8_t {
eText = 0 , eName = 1 , ePath = 2 , eCheckedText = 3 ,
eBitwiseOred32BitsCheckedText = 4 , eBitwiseOred64BitsCheckedText = 5 , eBool = 6 , eInt8 = 7 ,
eInt16 = 8 , eInt32 = 9 , eInt64 = 10 , eUInt8 = 11 ,
eUInt16 = 12 , eUInt32 = 13 , eUInt64 = 14 , eFloat = 15 ,
eDouble = 16 , eLongDouble = 17 , ePixelFormat = 18 , ePoint2I = 19 ,
ePoint3I = 20 , ePoint4I = 21 , ePoint2U = 22 , ePoint3U = 23 ,
ePoint4U = 24 , ePoint2F = 25 , ePoint3F = 26 , ePoint4F = 27 ,
ePoint2D = 28 , ePoint3D = 29 , ePoint4D = 30 , eSize = 31 ,
ePosition = 32 , eRectangle = 33 , eRgbColour = 34 , eRgbaColour = 35 ,
eHdrRgbColour = 36 , eHdrRgbaColour = 37 , eCount , eMin = eText
}
Parser function parameter types enumeration.
Functions
CU_API void * alignedAlloc (size_t alignment, size_t size)
Allocates aligned memory.
CU_API void alignedFree (void *memory)
Deallocates aligned memory.
template<typename T >
T * alignedAlloc (size_t alignment, size_t size)
Allocates aligned memory.
template<int A>
class CU_Alignas (A) Aligned
template<typename T >
class CU_Alignas (alignof(T)) AlignedFrom
CU_DeclareVector (byte, Byte)
CU_DeclareVector (s32, Int32)
CU_DeclareVector (u32, UInt32)
CU_DeclareVector (MbString, MbString)
CU_DeclareVector (String, String)
CU_DeclareVector (StringView, StringView)
CU_DeclareVector (MbStringView, MbStringView)
CU_DeclareMap (String, uint32_t, UInt32Str)
CU_DeclareMap (String, uint64_t, UInt64Str)
CU_DeclareMap (String, bool, BoolStr)
CU_DeclareMap (String, String, StrStr)
CU_DeclareSet (String, Str)
CU_DeclareMap (uint32_t, String, StrUInt32)
template<typename CharT >
std::basic_stringstream< CharT > makeStringStreamT ()
StringStream makeStringStream ()
CU_API String makeString (MbStringView const &in)
CU_API String makeString (WStringView const &in)
CU_API String makeString (U32StringView const &in)
CU_API MbString toUtf8 (WStringView in)
CU_API WString toSystemWide (MbStringView in)
CU_API U32String toUtf8U32String (StringView in)
String makeString (MbString const &in)
String makeString (WString const &in)
String makeString (U32String const &in)
String makeString (mbchar const *in)
String makeString (wchar const *in)
String makeString (u32char const *in)
String makeString (mbchar const *in, size_t length)
String makeString (wchar const *in, size_t length)
String makeString (u32char const *in, size_t length)
MbString toUtf8 (MbStringView in)
MbString toUtf8 (MbString const &in)
MbString toUtf8 (mbchar const *in)
MbString toUtf8 (mbchar const *in, size_t length)
MbString toUtf8 (WString const &in)
MbString toUtf8 (wchar const *in, size_t length)
MbString toUtf8 (wchar const *in)
WString toSystemWide (MbString const &in)
WString toSystemWide (mbchar const *in, size_t length)
WString toSystemWide (mbchar const *in)
WString toSystemWide (WStringView in)
WString toSystemWide (WString const &in)
WString toSystemWide (wchar const *in)
WString toSystemWide (wchar const *in, size_t length)
U32String toUtf8U32String (String const &in)
U32String toUtf8U32String (xchar const *in, size_t length)
template<typename Lockable >
UniqueLock< Lockable > makeUniqueLock (Lockable &lockable)
template<typename TypeT , typename TypeU , typename ... ParamsT>
UniquePtr< TypeT > makeUniqueDerived (ParamsT &&... params)
template<typename TypeT , typename ... ParamsT>
UniquePtr< TypeT > makeUnique (ParamsT &&... params)
template<typename TypeU , typename TypeT >
UniquePtr< TypeU > ptrCast (UniquePtr< TypeT > ptr)
template<typename TypeU , typename TypeT >
UniquePtr< TypeU > ptrRefCast (UniquePtr< TypeT > &ptr)
template<typename TypeU , typename TypeT >
RawUniquePtr< TypeU > ptrCast (RawUniquePtr< TypeT > ptr)
template<typename TypeU , typename TypeT >
RawUniquePtr< TypeU > ptrRefCast (RawUniquePtr< TypeT > &ptr)
template<typename T >
BinaryFile & operator<< (BinaryFile &file, T const &toWrite)
open mode dependant write function
template<typename T >
BinaryFile & operator>> (BinaryFile &file, T &toRead)
open mode dependant read function
constexpr bool isBigEndian () noexcept
Detects if the current system is big endian.
constexpr bool isLittleEndian () noexcept
Detects if the current system is little endian.
template<typename T >
constexpr T & switchEndianness (T &value) noexcept
Convert from little or big endian to the other.
template<typename T >
constexpr T switchEndianness (T const &value)
Convert from little or big endian to the other.
template<typename T >
constexpr T & systemEndianToBigEndian (T &value) noexcept
Convert the given value to big endian if needed.
template<typename T >
constexpr T systemEndianToBigEndian (T const &value)
Convert the given value to big endian if needed.
template<typename T , size_t N>
constexpr Array< T, N > & systemEndianToBigEndian (Array< T, N > &value) noexcept
Convert the given value to big endian if needed.
template<typename T , size_t N>
constexpr Array< T, N > systemEndianToBigEndian (Array< T, N > const &value)
Convert the given value to big endian if needed.
template<typename T >
constexpr Vector< T > & systemEndianToBigEndian (Vector< T > &value) noexcept
Convert the given value to big endian if needed.
template<typename T >
constexpr Vector< T > systemEndianToBigEndian (Vector< T > const &value)
Convert the given value to big endian if needed.
template<typename T >
constexpr T & systemEndianToLittleEndian (T &value) noexcept
Convert the given value to little endian if needed.
template<typename T >
constexpr T systemEndianToLittleEndian (T const &value)
Convert the given value to little endian if needed.
template<typename T , size_t N>
constexpr Array< T, N > & systemEndianToLittleEndian (Array< T, N > &value) noexcept
Convert the given value to little endian if needed.
template<typename T , size_t N>
constexpr Array< T, N > systemEndianToLittleEndian (Array< T, N > const &value)
Convert the given value to little endian if needed.
template<typename T >
Vector< T > & systemEndianToLittleEndian (Vector< T > &value) noexcept
Convert the given value to little endian if needed.
template<typename T >
Vector< T > systemEndianToLittleEndian (Vector< T > const &value)
Convert the given value to little endian if needed.
template<typename T >
constexpr T & bigEndianToSystemEndian (T &value) noexcept
Convert the given big endian value to system endian if needed.
template<typename T >
constexpr T bigEndianToSystemEndian (T const &value)
Convert the given big endian value to system endian if needed.
template<typename T , size_t N>
constexpr Array< T, N > & bigEndianToSystemEndian (Array< T, N > &value) noexcept
Convert the given value to big endian if needed.
template<typename T , size_t N>
constexpr Array< T, N > bigEndianToSystemEndian (Array< T, N > const &value)
Convert the given value to big endian if needed.
template<typename T >
Vector< T > & bigEndianToSystemEndian (Vector< T > &value) noexcept
Convert the given value to big endian if needed.
template<typename T >
Vector< T > bigEndianToSystemEndian (Vector< T > const &value)
Convert the given value to big endian if needed.
template<typename T >
constexpr T & littleEndianToSystemEndian (T &value) noexcept
Convert the given little endian value to system endian if needed.
template<typename T >
constexpr T littleEndianToSystemEndian (T const &value)
Convert the given little endian value to system endian if needed.
template<typename T , size_t N>
constexpr Array< T, N > & littleEndianToSystemEndian (Array< T, N > &value) noexcept
Convert the given value to little endian if needed.
template<typename T , size_t N>
constexpr Array< T, N > littleEndianToSystemEndian (Array< T, N > const &value)
Convert the given value to little endian if needed.
template<typename T >
Vector< T > & littleEndianToSystemEndian (Vector< T > &value) noexcept
Convert the given value to little endian if needed.
template<typename T >
Vector< T > littleEndianToSystemEndian (Vector< T > const &value)
Convert the given value to little endian if needed.
CU_API bool fileOpen (FILE *&file, std::filesystem::path const &path, char const *mode)
Opens a file.
CU_API bool fileOpen64 (FILE *&file, std::filesystem::path const &path, char const *mode)
Opens a file.
CU_API bool fileSeek (FILE *file, int64_t offset, int origin)
Seeks into a file.
CU_API int64_t fileTell (FILE *file)
Retrieves the file cursor position.
CU_API Path operator/ (Path const &lhs, Path const &rhs)
Appends 2 paths. adds the separator if needed.
CU_API Path operator/ (Path const &lhs, String const &rhs)
adds a string to a path. Adds the separator if needed
CU_API Path operator/ (Path const &lhs, char const *rhs)
adds a string to a path. Adds the separator if needed
CU_API Path operator/ (Path const &lhs, wchar_t const *rhs)
adds a string to a path. Adds the separator if needed
CU_API Path operator/ (String const &lhs, Path const &rhs)
adds a string to a path. Adds the separator if needed
CU_API Path operator/ (char const *lhs, Path const &rhs)
adds a string to a path. Adds the separator if needed
CU_API Path operator/ (wchar_t const *lhs, Path const &rhs)
adds a string to a path. Adds the separator if needed
CU_API std::filesystem::path makePath (StringView str)
template<typename T >
TextFile & operator<< (TextFile &file, T const &toWrite)
open mode dependant write function
template<typename T >
TextFile & operator>> (TextFile &file, T &toRead)
open mode dependant read function
template<typename IterT >
bool operator== (ArrayView< IterT > const &lhs, ArrayView< IterT > const &rhs)
template<typename IterT >
bool operator!= (ArrayView< IterT > const &lhs, ArrayView< IterT > const &rhs)
template<typename IterT , typename ValueT = typename IteratorTraits< IterT >::value_type>
ArrayView< ValueT > makeArrayView (IterT begin, IterT end)
template<typename ValueT >
ArrayView< ValueT > makeArrayView (ValueT *begin, ValueT *end)
template<typename IterT >
auto makeArrayView (IterT begin, uint32_t size)
template<typename IterT >
auto makeArrayView (IterT begin, uint64_t size)
template<typename ValueT , size_t N>
auto makeArrayView (ValueT(&buffer)[N])
CU_DeclareArrayView (byte, Byte)
CU_DeclareArrayView (s32, Int32)
CU_DeclareArrayView (u32, UInt32)
CU_DeclareArrayView (byte const, ConstByte)
CU_DeclareArrayView (s32 const, ConstInt32)
CU_DeclareArrayView (u32 const, ConstUInt32)
template<typename InitFunc , typename CleanFunc >
BlockGuard< CleanFunc > makeBlockGuard (InitFunc init, CleanFunc clean)
Helper function to declare a BlockGuard.
template<typename CleanFunc >
BlockGuard< CleanFunc > makeBlockGuard (CleanFunc clean)
Helper function to declare a BlockGuard.
template<typename ValueT , typename ControlT >
bool operator== (ChangeTrackedT< ValueT, ControlT > const &lhs, ValueT const &rhs)
template<typename ValueT , typename ControlT >
bool operator== (ValueT const &lhs, ChangeTrackedT< ValueT, ControlT > const &rhs)
template<typename ValueT , typename ControlT >
bool operator== (ChangeTrackedT< ValueT, ControlT > const &lhs, ChangeTrackedT< ValueT, ControlT > const &rhs)
template<typename ValueT , typename ControlT >
bool operator!= (ChangeTrackedT< ValueT, ControlT > const &lhs, ValueT const &rhs)
template<typename ValueT , typename ControlT >
bool operator!= (ValueT const &lhs, ChangeTrackedT< ValueT, ControlT > const &rhs)
template<typename ValueT , typename ControlT >
bool operator!= (ChangeTrackedT< ValueT, ControlT > const &lhs, ChangeTrackedT< ValueT, ControlT > const &rhs)
template<typename ControlT , typename ValueT >
ChangeTrackedT< ValueT, ControlT > makeChangeTrackedT (ValueT const &value)
template<typename ValueT >
ChangeTracked< ValueT > makeChangeTracked (ValueT const &value)
template<typename FlagTypeT , typename IteratorTraitsT >
constexpr bool operator== (FlagIterator< FlagTypeT, IteratorTraitsT > const &lhs, FlagIterator< FlagTypeT, IteratorTraitsT > const &rhs)
template<typename FlagTypeT , typename IteratorTraitsT >
constexpr bool operator!= (FlagIterator< FlagTypeT, IteratorTraitsT > const &lhs, FlagIterator< FlagTypeT, IteratorTraitsT > const &rhs)
template<typename T , typename U >
constexpr bool hasAll (T const &value, U const &rhs) noexcept
template<typename FlagType >
constexpr bool hasAll (FlagCombination< FlagType > const &value, FlagType const &rhs) noexcept
template<typename FlagType >
constexpr bool hasAll (FlagType const &value, FlagCombination< FlagType > const &rhs) noexcept
template<typename FlagType >
constexpr bool hasAll (typename FlagCombination< FlagType >::BaseType const &value, FlagCombination< FlagType > const &rhs) noexcept
template<typename FlagType >
constexpr bool hasAll (FlagCombination< FlagType > const &value, typename FlagCombination< FlagType >::BaseType const &rhs) noexcept
template<typename FlagType >
constexpr bool hasAll (FlagCombination< FlagType > const &value, FlagCombination< FlagType > const &rhs) noexcept
template<typename T , typename U >
constexpr bool hasAny (T const &value, U const &rhs) noexcept
template<typename FlagType >
constexpr bool hasAny (FlagCombination< FlagType > const &value, FlagType const &rhs) noexcept
template<typename FlagType , typename Type >
constexpr bool hasAny (FlagCombination< FlagType > const &value, Type const &rhs) noexcept
template<typename T , typename U >
constexpr bool checkFlag (T const &value, U const &flag) noexcept
template<typename FlagType >
constexpr bool checkFlag (FlagCombination< FlagType > const &value, FlagType const &flag) noexcept
template<typename FlagType , typename Type >
constexpr bool checkFlag (FlagCombination< FlagType > const &value, Type const &flag) noexcept
template<typename FlagType >
constexpr FlagCombination< FlagType > & addFlag (FlagCombination< FlagType > &value, FlagType const &flag) noexcept
adds a flag to the given value.
template<typename FlagType >
constexpr FlagCombination< FlagType > & addFlags (FlagCombination< FlagType > &value, FlagCombination< FlagType > const &flags) noexcept
adds a flag combination to the given value.
template<typename FlagType >
constexpr FlagCombination< FlagType > & remFlags (FlagCombination< FlagType > &value, FlagCombination< FlagType > const &flags) noexcept
Removes a flag combination from the given value.
template<typename FlagType >
constexpr FlagCombination< FlagType > & remFlag (FlagCombination< FlagType > &value, FlagType const &flag) noexcept
Removes a flag from the given value.
template<typename FlagType >
constexpr FlagCombination< FlagType > addFlag (FlagCombination< FlagType > const &value, FlagType const &flag) noexcept
adds a flag to the given value.
template<typename FlagType >
constexpr FlagCombination< FlagType > remFlag (FlagCombination< FlagType > const &value, FlagType const &flag) noexcept
Removes a flag from the given value.
template<typename ValueT , typename ControlT >
bool operator== (GroupChangeTrackedT< ValueT, ControlT > const &lhs, ValueT const &rhs)
template<typename ValueT , typename ControlT >
bool operator== (ValueT const &lhs, GroupChangeTrackedT< ValueT, ControlT > const &rhs)
template<typename ValueT , typename ControlT >
bool operator== (GroupChangeTrackedT< ValueT, ControlT > const &lhs, GroupChangeTrackedT< ValueT, ControlT > const &rhs)
template<typename ValueT , typename ControlT >
bool operator!= (GroupChangeTrackedT< ValueT, ControlT > const &lhs, ValueT const &rhs)
template<typename ValueT , typename ControlT >
bool operator!= (ValueT const &lhs, GroupChangeTrackedT< ValueT, ControlT > const &rhs)
template<typename ValueT , typename ControlT >
bool operator!= (GroupChangeTrackedT< ValueT, ControlT > const &lhs, GroupChangeTrackedT< ValueT, ControlT > const &rhs)
template<typename ValueT , typename ControlT >
GroupChangeTrackedT< ValueT, ControlT > makeGroupChangeTracked (ControlT &dirty, ValueT const &value)
template<typename ResT , typename KeyT , typename TraitsT , typename ... ParametersT>
ResourceCachePtrT< ResT, KeyT, TraitsT > makeCache (ParametersT &&... parameters)
Creates a cache.
template<typename ScopeExitFuncType >
ScopeGuard< ScopeExitFuncType > makeScopeGuard (ScopeExitFuncType const &function)
Helper function to create a ScopeGuard.
CU_API void cuLogError (char const *const description)
CU_API void cuFailure (char const *const description)
template<typename ContextT >
ContextDeleterPtr makeContextDeleter ()
template<ParameterType Type>
ParserParameterBaseSPtr makeParameter ()
Creates a parameter of given type.
template<ParameterType Type, typename ... Params>
ParserParameterBaseSPtr makeDefaultedParameter (ParserParameterValueType< Type > defaultValue, Params &&... params)
Creates a parameter of given type.
template<ParameterType Type, typename T >
ParserParameterBaseSPtr makeParameter (Range< T > const &range)
Creates a parameter of given type.
template<ParameterType Type>
ParserParameterBaseSPtr makeParameter (StringView name, UInt32StrMap const &values)
Creates a parameter of given type.
template<ParameterType Type>
ParserParameterBaseSPtr makeParameter (StringView name, UInt64StrMap const &values)
Creates a parameter of given type.
template<ParameterType Type, typename EnumType >
ParserParameterBaseSPtr makeParameter ()
Creates a parameter of given type.
CU_API void getParameterValue (ParserParameterBase const &parameter, bool &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, int8_t &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, uint8_t &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, int16_t &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, uint16_t &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, int32_t &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, uint32_t &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, int64_t &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, uint64_t &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, float &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, double &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, long double &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, String &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, Path &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, PixelFormat &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, Point2i &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, Point3i &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, Point4i &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, Point2ui &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, Point3ui &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, Point4ui &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, Point2f &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, Point3f &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, Point4f &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, Point2d &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, Point3d &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, Point4d &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, Size &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, Position &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, Rectangle &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, RgbColour &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, RgbaColour &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, HdrRgbColour &value)
CU_API void getParameterValue (ParserParameterBase const &parameter, HdrRgbaColour &value)
CU_API StringView getTypeName (ParameterType type)
Retrieves the given parameter type's name.
bool operator== (BoundingBox const &lhs, BoundingBox const &rhs)
bool operator!= (BoundingBox const &lhs, BoundingBox const &rhs)
bool operator== (BoundingSphere const &lhs, BoundingSphere const &rhs)
bool operator!= (BoundingSphere const &lhs, BoundingSphere const &rhs)
CU_API bool operator== (ColourComponent const &lhs, ColourComponent const &rhs)
Equality operator.
CU_API bool operator!= (ColourComponent const &lhs, ColourComponent const &rhs)
Inequality operator.
template<typename T >
float operator+ (ColourComponent const &lhs, T const &rhs)
addition assignment operator
template<typename T >
float operator- (ColourComponent const &lhs, T const &rhs)
Substraction assignment operator.
template<typename T >
float operator/ (ColourComponent const &lhs, T const &rhs)
Division assignment operator.
template<typename T >
float operator* (ColourComponent const &lhs, T const &rhs)
Multiplication assignment operator.
CU_API float operator+ (ColourComponent const &lhs, ColourComponent const &rhs)
addition operator
CU_API float operator- (ColourComponent const &lhs, ColourComponent const &rhs)
Subtraction operator.
CU_API float operator* (ColourComponent const &lhs, ColourComponent const &rhs)
Multiplication operator.
CU_API float operator/ (ColourComponent const &lhs, ColourComponent const &rhs)
Division operator.
bool operator== (Glyph const &lhs, Glyph const &rhs)
Equality comparison operator.
bool operator!= (Glyph const &lhs, Glyph const &rhs)
Difference comparison operator.
bool operator< (Glyph const &lhs, Glyph const &rhs)
Less than comparison operator.
bool operator> (Glyph const &lhs, Glyph const &rhs)
Greater than comparison operator.
bool operator<= (Glyph const &lhs, Glyph const &rhs)
Less than or equal to comparison operator.
bool operator>= (Glyph const &lhs, Glyph const &rhs)
Greater than or equal to comparison operator.
CU_API bool operator== (HdrColourComponent const &lhs, HdrColourComponent const &rhs)
Equality operator.
CU_API bool operator!= (HdrColourComponent const &lhs, HdrColourComponent const &rhs)
Inequality operator.
template<typename T >
float operator+ (HdrColourComponent const &lhs, T const &rhs)
addition assignment operator
template<typename T >
float operator- (HdrColourComponent const &lhs, T const &rhs)
Substraction assignment operator.
template<typename T >
float operator/ (HdrColourComponent const &lhs, T const &rhs)
Division assignment operator.
template<typename T >
float operator* (HdrColourComponent const &lhs, T const &rhs)
Multiplication assignment operator.
CU_API float operator+ (HdrColourComponent const &lhs, HdrColourComponent const &rhs)
addition operator
CU_API float operator- (HdrColourComponent const &lhs, HdrColourComponent const &rhs)
Subtraction operator.
CU_API float operator* (HdrColourComponent const &lhs, HdrColourComponent const &rhs)
Multiplication operator.
CU_API float operator/ (HdrColourComponent const &lhs, HdrColourComponent const &rhs)
Division operator.
CU_API bool convertToNormalMap (float strength, Image &image) noexcept
ImageLayout::DeviceSize getSliceSize (ImageLayout const &layout)
ImageLayout::DeviceSize getSliceMipSize (ImageLayout const &layout, uint32_t level)
ImageLayout::DeviceSize getLayerSize (ImageLayout const &layout)
ImageLayout::DeviceSize getLayerMipSize (ImageLayout const &layout, uint32_t level)
ImageLayout::DeviceSize getSliceOffset (ImageLayout const &layout, uint32_t index)
ImageLayout::DeviceSize getSliceMipOffset (ImageLayout const &layout, uint32_t index, uint32_t level)
ImageLayout::DeviceSize getLayerOffset (ImageLayout const &layout, uint32_t index)
ImageLayout::DeviceSize getLayerMipOffset (ImageLayout const &layout, uint32_t index, uint32_t level)
ImageLayout::Buffer getBuffer (ImageLayout const &layout, PxBufferBase &buffer)
ImageLayout::ConstBuffer getBuffer (ImageLayout const &layout, PxBufferBase const &buffer)
ImageLayout::Buffer getLayerBuffer (ImageLayout const &layout, PxBufferBase &buffer, uint32_t index)
ImageLayout::Buffer getLayerMipBuffer (ImageLayout const &layout, PxBufferBase &buffer, uint32_t index, uint32_t level)
ImageLayout::ConstBuffer getLayerBuffer (ImageLayout const &layout, PxBufferBase const &buffer, uint32_t index)
ImageLayout::ConstBuffer getLayerMipBuffer (ImageLayout const &layout, PxBufferBase const &buffer, uint32_t index, uint32_t level)
bool hasLayerBuffer (ImageLayout const &layout, PxBufferBase const &buffer, uint32_t index)
bool hasLayerMipBuffer (ImageLayout const &layout, PxBufferBase const &buffer, uint32_t index, uint32_t level)
ImageLayout::Buffer getSliceBuffer (ImageLayout const &layout, PxBufferBase &buffer, uint32_t index)
ImageLayout::Buffer getSliceMipBuffer (ImageLayout const &layout, PxBufferBase &buffer, uint32_t index, uint32_t level)
ImageLayout::ConstBuffer getSliceBuffer (ImageLayout const &layout, PxBufferBase const &buffer, uint32_t index)
ImageLayout::ConstBuffer getSliceMipBuffer (ImageLayout const &layout, PxBufferBase const &buffer, uint32_t index, uint32_t level)
bool hasSliceBuffer (ImageLayout const &layout, PxBufferBase const &buffer, uint32_t index)
bool hasSliceMipBuffer (ImageLayout const &layout, PxBufferBase const &buffer, uint32_t index, uint32_t level)
template<PixelFormat FT, PixelFormat FU>
bool operator== (Pixel< FT > const &lhs, Pixel< FU > const &rhs)
Equality operator.
template<PixelFormat PFT, PixelComponent PCT>
uint8_t getX8U (uint8_t const *buffer)
template<PixelFormat PFT, PixelComponent PCT>
int8_t getX8S (uint8_t const *buffer)
template<PixelFormat PFT, PixelComponent PCT>
uint16_t getX16U (uint8_t const *buffer)
template<PixelFormat PFT, PixelComponent PCT>
int16_t getX16S (uint8_t const *buffer)
template<PixelFormat PFT, PixelComponent PCT>
int16_t getX16F (uint8_t const *buffer)
template<PixelFormat PFT, PixelComponent PCT>
uint32_t getX32U (uint8_t const *buffer)
template<PixelFormat PFT, PixelComponent PCT>
int32_t getX32S (uint8_t const *buffer)
template<PixelFormat PFT, PixelComponent PCT>
float getX32F (uint8_t const *buffer)
template<PixelFormat PFT, PixelComponent PCT>
uint64_t getX64U (uint8_t const *buffer)
template<PixelFormat PFT, PixelComponent PCT>
int64_t getX64S (uint8_t const *buffer)
template<PixelFormat PFT, PixelComponent PCT>
double getX64F (uint8_t const *buffer)
template<PixelFormat PFT, PixelComponent PCT>
void setX8U (uint8_t *buffer, uint8_t value)
template<PixelFormat PFT, PixelComponent PCT>
void setX8S (uint8_t *buffer, int8_t value)
template<PixelFormat PFT, PixelComponent PCT>
void setX16U (uint8_t *buffer, uint16_t value)
template<PixelFormat PFT, PixelComponent PCT>
void setX16S (uint8_t *buffer, int16_t value)
template<PixelFormat PFT, PixelComponent PCT>
void setX16F (uint8_t *buffer, int16_t value)
template<PixelFormat PFT, PixelComponent PCT>
void setX32U (uint8_t *buffer, uint32_t value)
template<PixelFormat PFT, PixelComponent PCT>
void setX32S (uint8_t *buffer, int32_t value)
template<PixelFormat PFT, PixelComponent PCT>
void setX32F (uint8_t *buffer, float value)
template<PixelFormat PFT, PixelComponent PCT>
void setX64U (uint8_t *buffer, uint64_t value)
template<PixelFormat PFT, PixelComponent PCT>
void setX64S (uint8_t *buffer, int64_t value)
template<PixelFormat PFT, PixelComponent PCT>
void setX64F (uint8_t *buffer, double value)
template<PixelFormat PFT>
uint8_t getR8U (uint8_t const *buffer)
template<PixelFormat PFT>
int8_t getR8S (uint8_t const *buffer)
template<PixelFormat PFT>
uint16_t getR16U (uint8_t const *buffer)
template<PixelFormat PFT>
int16_t getR16S (uint8_t const *buffer)
template<PixelFormat PFT>
int16_t getR16F (uint8_t const *buffer)
template<PixelFormat PFT>
uint32_t getR32U (uint8_t const *buffer)
template<PixelFormat PFT>
int32_t getR32S (uint8_t const *buffer)
template<PixelFormat PFT>
float getR32F (uint8_t const *buffer)
template<PixelFormat PFT>
uint64_t getR64U (uint8_t const *buffer)
template<PixelFormat PFT>
int64_t getR64S (uint8_t const *buffer)
template<PixelFormat PFT>
double getR64F (uint8_t const *buffer)
template<PixelFormat PFT>
uint8_t getG8U (uint8_t const *buffer)
template<PixelFormat PFT>
int8_t getG8S (uint8_t const *buffer)
template<PixelFormat PFT>
uint16_t getG16U (uint8_t const *buffer)
template<PixelFormat PFT>
int16_t getG16S (uint8_t const *buffer)
template<PixelFormat PFT>
int16_t getG16F (uint8_t const *buffer)
template<PixelFormat PFT>
uint32_t getG32U (uint8_t const *buffer)
template<PixelFormat PFT>
int32_t getG32S (uint8_t const *buffer)
template<PixelFormat PFT>
float getG32F (uint8_t const *buffer)
template<PixelFormat PFT>
uint64_t getG64U (uint8_t const *buffer)
template<PixelFormat PFT>
int64_t getG64S (uint8_t const *buffer)
template<PixelFormat PFT>
double getG64F (uint8_t const *buffer)
template<PixelFormat PFT>
uint8_t getB8U (uint8_t const *buffer)
template<PixelFormat PFT>
int8_t getB8S (uint8_t const *buffer)
template<PixelFormat PFT>
uint16_t getB16U (uint8_t const *buffer)
template<PixelFormat PFT>
int16_t getB16S (uint8_t const *buffer)
template<PixelFormat PFT>
int16_t getB16F (uint8_t const *buffer)
template<PixelFormat PFT>
uint32_t getB32U (uint8_t const *buffer)
template<PixelFormat PFT>
int32_t getB32S (uint8_t const *buffer)
template<PixelFormat PFT>
float getB32F (uint8_t const *buffer)
template<PixelFormat PFT>
uint64_t getB64U (uint8_t const *buffer)
template<PixelFormat PFT>
int64_t getB64S (uint8_t const *buffer)
template<PixelFormat PFT>
double getB64F (uint8_t const *buffer)
template<PixelFormat PFT>
uint8_t getA8U (uint8_t const *buffer)
template<PixelFormat PFT>
int8_t getA8S (uint8_t const *buffer)
template<PixelFormat PFT>
uint16_t getA16U (uint8_t const *buffer)
template<PixelFormat PFT>
int16_t getA16S (uint8_t const *buffer)
template<PixelFormat PFT>
int16_t getA16F (uint8_t const *buffer)
template<PixelFormat PFT>
uint32_t getA32U (uint8_t const *buffer)
template<PixelFormat PFT>
int32_t getA32S (uint8_t const *buffer)
template<PixelFormat PFT>
float getA32F (uint8_t const *buffer)
template<PixelFormat PFT>
uint64_t getA64U (uint8_t const *buffer)
template<PixelFormat PFT>
int64_t getA64S (uint8_t const *buffer)
template<PixelFormat PFT>
double getA64F (uint8_t const *buffer)
template<PixelFormat PFT>
uint16_t getD16U (uint8_t const *buffer)
template<PixelFormat PFT>
uint32_t getD24U (uint8_t const *buffer)
template<PixelFormat PFT>
float getD32F (uint8_t const *buffer)
template<PixelFormat PFT>
uint8_t getS8U (uint8_t const *buffer)
template<PixelFormat PFT>
void setR8U (uint8_t *buffer, uint8_t value)
template<PixelFormat PFT>
void setR8S (uint8_t *buffer, int8_t value)
template<PixelFormat PFT>
void setR16U (uint8_t *buffer, uint16_t value)
template<PixelFormat PFT>
void setR16S (uint8_t *buffer, int16_t value)
template<PixelFormat PFT>
void setR16F (uint8_t *buffer, int16_t value)
template<PixelFormat PFT>
void setR32S (uint8_t *buffer, uint32_t value)
template<PixelFormat PFT>
void setR32U (uint8_t *buffer, int32_t value)
template<PixelFormat PFT>
void setR32F (uint8_t *buffer, float value)
template<PixelFormat PFT>
void setR64U (uint8_t *buffer, uint64_t value)
template<PixelFormat PFT>
void setR64S (uint8_t *buffer, int64_t value)
template<PixelFormat PFT>
void setR64F (uint8_t *buffer, double value)
template<PixelFormat PFT>
void setG8U (uint8_t *buffer, uint8_t value)
template<PixelFormat PFT>
void setG8S (uint8_t *buffer, int8_t value)
template<PixelFormat PFT>
void setG16U (uint8_t *buffer, uint16_t value)
template<PixelFormat PFT>
void setG16S (uint8_t *buffer, int16_t value)
template<PixelFormat PFT>
void setG16F (uint8_t *buffer, int16_t value)
template<PixelFormat PFT>
void setG32U (uint8_t *buffer, uint32_t value)
template<PixelFormat PFT>
void setG32S (uint8_t *buffer, int32_t value)
template<PixelFormat PFT>
void setG32F (uint8_t *buffer, float value)
template<PixelFormat PFT>
void setG64U (uint8_t *buffer, uint64_t value)
template<PixelFormat PFT>
void setG64S (uint8_t *buffer, int64_t value)
template<PixelFormat PFT>
void setG64F (uint8_t *buffer, double value)
template<PixelFormat PFT>
void setB8U (uint8_t *buffer, uint8_t value)
template<PixelFormat PFT>
void setB8S (uint8_t *buffer, int8_t value)
template<PixelFormat PFT>
void setB16U (uint8_t *buffer, uint16_t value)
template<PixelFormat PFT>
void setB16S (uint8_t *buffer, int16_t value)
template<PixelFormat PFT>
void setB16F (uint8_t *buffer, int16_t value)
template<PixelFormat PFT>
void setB32U (uint8_t *buffer, uint32_t value)
template<PixelFormat PFT>
void setB32S (uint8_t *buffer, int32_t value)
template<PixelFormat PFT>
void setB32F (uint8_t *buffer, float value)
template<PixelFormat PFT>
void setB64U (uint8_t *buffer, uint64_t value)
template<PixelFormat PFT>
void setB64S (uint8_t *buffer, int64_t value)
template<PixelFormat PFT>
void setB64F (uint8_t *buffer, double value)
template<PixelFormat PFT>
void setA8U (uint8_t *buffer, uint8_t value)
template<PixelFormat PFT>
void setA8S (uint8_t *buffer, int8_t value)
template<PixelFormat PFT>
void setA16U (uint8_t *buffer, uint16_t value)
template<PixelFormat PFT>
void setA16S (uint8_t *buffer, int16_t value)
template<PixelFormat PFT>
void setA16F (uint8_t *buffer, int16_t value)
template<PixelFormat PFT>
void setA32U (uint8_t *buffer, uint32_t value)
template<PixelFormat PFT>
void setA32S (uint8_t *buffer, int32_t value)
template<PixelFormat PFT>
void setA32F (uint8_t *buffer, float value)
template<PixelFormat PFT>
void setA64U (uint8_t *buffer, uint64_t value)
template<PixelFormat PFT>
void setA64S (uint8_t *buffer, int64_t value)
template<PixelFormat PFT>
void setA64F (uint8_t *buffer, double value)
template<PixelFormat PFT>
void setD16U (uint8_t *buffer, uint16_t value)
template<PixelFormat PFT>
void setD24U (uint8_t *buffer, uint32_t value)
template<PixelFormat PFT>
void setD32F (uint8_t *buffer, float value)
template<PixelFormat PFT>
void setS8U (uint8_t *buffer, uint8_t value)
template<PixelFormat PF>
float getR32F (Pixel< PF > const &pixel)
Function to retrieve pixel colour component in float.
template<PixelFormat PF>
void setR32F (Pixel< PF > const &pixel, float value)
Function to define pixel colour component in float.
template<PixelFormat PF>
uint8_t getR8U (Pixel< PF > const &pixel)
Function to retrieve pixel red component in byte.
template<PixelFormat PF>
void setR8U (Pixel< PF > &pixel, uint8_t value)
Function to define pixel red component in byte.
template<PixelFormat PF>
float getG32F (Pixel< PF > const &pixel)
Function to retrieve pixel green component in float.
template<PixelFormat PF>
void setG32F (Pixel< PF > &pixel, float value)
Function to define pixel green component in float.
template<PixelFormat PF>
uint8_t getG8U (Pixel< PF > const &pixel)
Function to retrieve pixel green component in byte.
template<PixelFormat PF>
void setG8U (Pixel< PF > &pixel, uint8_t value)
Function to define pixel green component in byte.
template<PixelFormat PF>
float getB32F (Pixel< PF > const &pixel)
Function to retrieve pixel blue component in float.
template<PixelFormat PF>
void setB32F (Pixel< PF > &pixel, float value)
Function to define pixel blue component in float.
template<PixelFormat PF>
uint8_t getB8U (Pixel< PF > const &pixel)
Function to retrieve pixel blue component in byte.
template<PixelFormat PF>
void setB8U (Pixel< PF > &pixel, uint8_t value)
Function to define pixel blue component in byte.
template<PixelFormat PF>
float getA32F (Pixel< PF > const &pixel)
Function to retrieve pixel alpha component in float.
template<PixelFormat PF>
void setA32F (Pixel< PF > &pixel, float value)
Function to define pixel alpha component in float.
template<PixelFormat PF>
uint8_t getA8U (Pixel< PF > const &pixel)
Function to retrieve pixel alpha component in byte.
template<PixelFormat PF>
void setA8U (Pixel< PF > &pixel, uint8_t value)
Function to define pixel alpha component in byte.
template<PixelFormat PF>
float getD32F (Pixel< PF > const &pixel)
Function to retrieve pixel depth component in float.
template<PixelFormat PF>
void setD32F (Pixel< PF > &pixel, float value)
Function to define pixel depth component in float.
template<PixelFormat PF>
uint16_t getD16U (Pixel< PF > const &pixel)
Function to retrieve pixel depth component in uint16_t.
template<PixelFormat PF>
void setD16U (Pixel< PF > &pixel, uint16_t value)
Function to define pixel depth component in uint16_t.
template<PixelFormat PF>
uint32_t getD24U (Pixel< PF > const &pixel)
Function to retrieve pixel depth component in uint32_t, with 24 relevant bits.
template<PixelFormat PF>
void setD24U (Pixel< PF > &pixel, uint32_t value)
Function to define pixel depth component in uint32_t, with 24 relevant bits.
template<PixelFormat PF>
uint8_t getS8U (Pixel< PF > const &pixel)
Function to retrieve pixel depth stencil in byte.
template<PixelFormat PF>
void setS8U (Pixel< PF > &pixel, uint8_t value)
Function to define pixel depth stencil in byte.
PixelComponents getPixelComponents (PixelFormat format)
template<PixelFormat PF>
ConstPixelIterator< PF > operator+ (ConstPixelIterator< PF > const &it, size_t offset)
template<PixelFormat PF>
ConstPixelIterator< PF > operator- (ConstPixelIterator< PF > const &it, size_t offset)
template<PixelFormat PF>
ConstPixelIterator< PF >::difference_type operator- (ConstPixelIterator< PF > const &lhs, ConstPixelIterator< PF > const &rhs)
template<PixelFormat PF>
ConstPixelIterator< PF >::difference_type operator- (PixelIterator< PF > const &lhs, ConstPixelIterator< PF > const &rhs)
template<PixelFormat PF>
ConstPixelIterator< PF >::difference_type operator- (ConstPixelIterator< PF > const &lhs, PixelIterator< PF > const &rhs)
bool decompressBC1Block (uint8_t const *bitstring, uint8_t *pixelBuffer)
bool decompressBC3Block (uint8_t const *bitstring, uint8_t *pixelBuffer)
bool decompressBC5Block (uint8_t const *bitstring, uint8_t *pixelBuffer)
constexpr VkDeviceSize getBytesPerPixel (PixelFormat format)
Function to retrieve Pixel size without templates.
CU_API String getFormatName (PixelFormat format)
Function to retrieve pixel format name.
constexpr uint8_t getComponentsCount (PixelFormat format)
Function to retrieve the number of components of a pixel format.
constexpr bool hasAlpha (PixelFormat format)
constexpr bool hasComponent (PixelFormat format, PixelComponent component)
constexpr PixelFormat getSingleComponent (PixelFormat format)
constexpr bool isInt8 (PixelFormat format)
constexpr bool isInt8 (VkFormat format)
constexpr bool isInt16 (PixelFormat format)
constexpr bool isInt16 (VkFormat format)
constexpr bool isInt32 (PixelFormat format)
constexpr bool isInt32 (VkFormat format)
constexpr bool isFloatingPoint (PixelFormat format)
constexpr bool isFloatingPoint (VkFormat format)
constexpr bool isCompressed (PixelFormat format)
constexpr bool isSRGBFormat (PixelFormat format)
Tells if the given format is an SRGB one.
constexpr bool isRGFormat (PixelFormat format)
constexpr bool isRGBFormat (PixelFormat format)
constexpr bool isBGRFormat (PixelFormat format)
constexpr bool isRGBAFormat (PixelFormat format)
constexpr bool isARGBFormat (PixelFormat format)
constexpr bool isBGRAFormat (PixelFormat format)
constexpr bool isABGRFormat (PixelFormat format)
constexpr PixelFormat getSRGBFormat (PixelFormat format)
constexpr PixelFormat getNonSRGBFormat (PixelFormat format)
constexpr bool isDepthOrStencilFormat (PixelFormat format)
constexpr PixelFormat getPFWithoutAlpha (PixelFormat format)
Retrieves the pixel format without alpha that is close to the one given.
constexpr PixelFormat getPFWithAlpha (PixelFormat format)
Retrieves the pixel format with alpha that is close to the one given.
constexpr uint32_t getComponentIndex (PixelComponent component)
constexpr uint32_t getComponentIndex (PixelComponent component, PixelFormat format)
constexpr PixelComponent getIndexComponent (uint32_t index, PixelFormat format)
constexpr PixelComponents getComponents (PixelFormat format)
CU_API PixelFormat getFormatByName (StringView formatName)
Function to retrieve pixel format from a name.
CU_API PixelFormat getPixelFormat (PixelFormat format, PixelComponents components)
CU_API void convertPixel (PixelFormat srcFormat, uint8_t const *&src, PixelFormat dstFormat, uint8_t *&dst)
Function to perform convertion without templates.
CU_API void convertBuffer (Size const &srcDimensions, Size const &dstDimensions, PixelFormat srcFormat, uint8_t const *srcBuffer, uint32_t srcSize, PixelFormat dstFormat, uint8_t *dstBuffer, uint32_t dstSize)
Function to perform convertion without templates.
static void convertBuffer (Size const &dimensions, PixelFormat srcFormat, uint8_t const *srcBuffer, uint32_t srcSize, PixelFormat dstFormat, uint8_t *dstBuffer, uint32_t dstSize)
Function to perform convertion without templates.
CU_API void compressBuffer (PxBufferConvertOptions const *options, std::atomic_bool const *interrupt, Size const &srcDimensions, Size const &dstDimensions, PixelFormat srcFormat, uint8_t const *srcBuffer, uint32_t srcSize, PixelFormat dstFormat, uint8_t *dstBuffer, uint32_t dstSize)
Function to perform convertion without templates.
CU_API PxBufferBaseUPtr decompressBuffer (PxBufferBase const &src)
Decompresses the given compressed pixel buffer.
CU_API PxBufferBaseUPtr extractComponent (PxBufferBaseRPtr src, PixelComponent component)
Extracts pixel component values from a source buffer holding alpha and puts it in a destination buffer.
CU_API PxBufferBaseUPtr extractComponents (PxBufferBaseRPtr src, PixelComponents component)
Extracts pixel component values from a source buffer holding alpha and puts it in a destination buffer.
CU_API void copyBufferComponents (PixelComponents srcComponents, PixelComponents dstComponents, PxBufferBase const &srcBuffer, PxBufferBase &dstBuffer)
Copies some pixel components from a source buffer into pixel components of a destination buffer.
template<PixelFormat PF>
PixelIterator< PF > operator+ (PixelIterator< PF > it, size_t offset)
template<PixelFormat PF>
PixelIterator< PF > operator- (PixelIterator< PF > it, size_t offset)
template<PixelFormat PF>
PixelIterator< PF >::difference_type operator- (PixelIterator< PF > const &lhs, PixelIterator< PF > const &rhs)
CU_API bool operator== (Position const &a, Position const &b)
Equality operator.
CU_API bool operator!= (Position const &a, Position const &b)
Difference operator.
static String getPredefinedName (PredefinedRgbaColour predefined)
Retrieves predefined colour name.
static PredefinedRgbaColour getPredefinedRgba (String const &name)
Retrieves predefined colour from a name.
template<typename ComponentType >
bool operator== (RgbaColourT< ComponentType > const &lhs, RgbaColourT< ComponentType > const &rhs)
Equality operator.
template<typename ComponentType >
bool operator!= (RgbaColourT< ComponentType > const &lhs, RgbaColourT< ComponentType > const &rhs)
Inequality operator.
template<typename ComponentType >
RgbaColourT< ComponentType > operator+ (RgbaColourT< ComponentType > const &lhs, RgbaColourT< ComponentType > const &rhs)
addition operator
template<typename ComponentType >
RgbaColourT< ComponentType > operator- (RgbaColourT< ComponentType > const &lhs, RgbaColourT< ComponentType > const &rhs)
Substraction operator.
template<typename ComponentType , typename T >
RgbaColourT< ComponentType > operator+ (RgbaColourT< ComponentType > const &lhs, T rhs)
addition operator
template<typename ComponentType , typename T >
RgbaColourT< ComponentType > operator- (RgbaColourT< ComponentType > const &lhs, T rhs)
Subtraction operator.
template<typename ComponentType , typename T >
RgbaColourT< ComponentType > operator* (RgbaColourT< ComponentType > const &lhs, T rhs)
Multiplication operator.
template<typename ComponentType , typename T >
RgbaColourT< ComponentType > operator/ (RgbaColourT< ComponentType > const &lhs, T rhs)
Division operator.
Point3ub toRGBByte (RgbaColourT< ColourComponent > const &colour)
Stores a colour's components into a point in RGB format.
Point3ub toBGRByte (RgbaColourT< ColourComponent > const &colour)
Stores a colour's components into a point in BGR format.
Point4ub toRGBAByte (RgbaColourT< ColourComponent > const &colour)
Stores a colour's components into a point in RGBA format.
Point4ub toBGRAByte (RgbaColourT< ColourComponent > const &colour)
Stores a colour's components into a point in BGRA format.
Point4ub toARGBByte (RgbaColourT< ColourComponent > const &colour)
Stores a colour's components into a point in ARGB format.
Point4ub toABGRByte (RgbaColourT< ColourComponent > const &colour)
Stores a colour's components into a point in ABGR format.
template<typename ComponentType >
Point3f toRGBFloat (RgbaColourT< ComponentType > const &colour)
Stores a colour's components into a point in RGB format.
template<typename ComponentType >
Point3f toBGRFloat (RgbaColourT< ComponentType > const &colour)
Stores a colour's components into a point in BGR format.
template<typename ComponentType >
Point4f toRGBAFloat (RgbaColourT< ComponentType > const &colour)
Stores a colour's components into a point in RGBA format.
template<typename ComponentType >
Point4f toARGBFloat (RgbaColourT< ComponentType > const &colour)
Stores a colour's components into a point in ARGB format.
template<typename ComponentType >
Point4f toABGRFloat (RgbaColourT< ComponentType > const &colour)
Stores a colour's components into a point in ABGR format.
template<typename ComponentType >
Point4f toBGRAFloat (RgbaColourT< ComponentType > const &colour)
Stores a colour's components into a point in BGRA format.
uint32_t toRGBPacked (RgbaColourT< ColourComponent > const &colour)
Packs a colour's components into an uint32_t in the RGB format (0x00RRGGBB).
uint32_t toBGRPacked (RgbaColourT< ColourComponent > const &colour)
Packs a colour's components into an uint32_t in the BGR format (0x00BBGGRR).
uint32_t toARGBPacked (RgbaColourT< ColourComponent > const &colour)
Packs a colour's components into an uint32_t in the ARGB format (0xAARRGGBB).
uint32_t toRGBAPacked (RgbaColourT< ColourComponent > const &colour)
Packs a colour's components into an uint32_t in the RGBA format (0xRRGGBBAA).
uint32_t toABGRPacked (RgbaColourT< ColourComponent > const &colour)
Packs a colour's components into an uint32_t in the ABGR format (0xAABBGGRR).
uint32_t toBGRAPacked (RgbaColourT< ColourComponent > const &colour)
Packs a colour's components into an uint32_t in the BGRA format (0xBBGGRRAA).
static String getPredefinedName (PredefinedRgbColour predefined)
Retrieves predefined colour name.
static PredefinedRgbColour getPredefinedRgb (String const &name)
Retrieves predefined colour from a name.
template<typename ComponentType >
bool operator== (RgbColourT< ComponentType > const &lhs, RgbColourT< ComponentType > const &rhs)
Equality operator.
template<typename ComponentType >
bool operator!= (RgbColourT< ComponentType > const &lhs, RgbColourT< ComponentType > const &rhs)
Inequality operator.
template<typename ComponentType >
RgbColourT< ComponentType > operator+ (RgbColourT< ComponentType > const &lhs, RgbColourT< ComponentType > const &rhs)
addition operator
template<typename ComponentType >
RgbColourT< ComponentType > operator- (RgbColourT< ComponentType > const &lhs, RgbColourT< ComponentType > const &rhs)
Substraction operator.
template<typename ComponentType , typename T >
RgbColourT< ComponentType > operator+ (RgbColourT< ComponentType > const &lhs, T rhs)
addition operator
template<typename ComponentType , typename T >
RgbColourT< ComponentType > operator- (RgbColourT< ComponentType > const &lhs, T rhs)
Subtraction operator.
template<typename ComponentType , typename T >
RgbColourT< ComponentType > operator* (RgbColourT< ComponentType > const &lhs, T rhs)
Multiplication operator.
template<typename ComponentType , typename T >
RgbColourT< ComponentType > operator/ (RgbColourT< ComponentType > const &lhs, T rhs)
Division operator.
Point3ub toRGBByte (RgbColourT< ColourComponent > const &colour)
Stores a colour's components into a point in RGB format.
Point3ub toBGRByte (RgbColourT< ColourComponent > const &colour)
Stores a colour's components into a point in BGR format.
Point4ub toRGBAByte (RgbColourT< ColourComponent > const &colour)
Stores a colour's components into a point in RGBA format.
Point4ub toBGRAByte (RgbColourT< ColourComponent > const &colour)
Stores a colour's components into a point in BGRA format.
Point4ub toARGBByte (RgbColourT< ColourComponent > const &colour)
Stores a colour's components into a point in ARGB format.
Point4ub toABGRByte (RgbColourT< ColourComponent > const &colour)
Stores a colour's components into a point in ABGR format.
template<typename ComponentType >
Point3f toRGBFloat (RgbColourT< ComponentType > const &colour)
Stores a colour's components into a point in RGB format.
template<typename ComponentType >
Point3f toBGRFloat (RgbColourT< ComponentType > const &colour)
Stores a colour's components into a point in BGR format.
template<typename ComponentType >
Point4f toRGBAFloat (RgbColourT< ComponentType > const &colour)
Stores a colour's components into a point in RGBA format.
template<typename ComponentType >
Point4f toARGBFloat (RgbColourT< ComponentType > const &colour)
Stores a colour's components into a point in ARGB format.
template<typename ComponentType >
Point4f toABGRFloat (RgbColourT< ComponentType > const &colour)
Stores a colour's components into a point in ABGR format.
template<typename ComponentType >
Point4f toBGRAFloat (RgbColourT< ComponentType > const &colour)
Stores a colour's components into a point in BGRA format.
uint32_t toRGBPacked (RgbColourT< ColourComponent > const &colour)
Packs a colour's components into an uint32_t in the RGB format (0x00RRGGBB).
uint32_t toBGRPacked (RgbColourT< ColourComponent > const &colour)
Packs a colour's components into an uint32_t in the BGR format (0x00BBGGRR).
uint32_t toARGBPacked (RgbColourT< ColourComponent > const &colour)
Packs a colour's components into an uint32_t in the ARGB format (0xAARRGGBB).
uint32_t toRGBAPacked (RgbColourT< ColourComponent > const &colour)
Packs a colour's components into an uint32_t in the RGBA format (0xRRGGBBAA).
uint32_t toABGRPacked (RgbColourT< ColourComponent > const &colour)
Packs a colour's components into an uint32_t in the ABGR format (0xAABBGGRR).
uint32_t toBGRAPacked (RgbColourT< ColourComponent > const &colour)
Packs a colour's components into an uint32_t in the BGRA format (0xBBGGRRAA).
CU_API bool operator== (Size const &a, Size const &b) noexcept
Equality operator.
CU_API bool operator!= (Size const &a, Size const &b) noexcept
Difference operator.
Size operator<< (Size const &lhs, uint32_t rhs) noexcept
Size operator>> (Size const &lhs, uint32_t rhs) noexcept
template<typename Type >
static AngleT< Type > acosT (double value)
Computes this angle's value from the given cosine value.
template<typename Type >
static AngleT< Type > asinT (double value)
Computes this angle's value from the given sine value.
template<typename Type >
static AngleT< Type > atanT (double value)
Computes this angle's value from the given tangent value.
static AngleT< float > acosf (double value)
Computes this angle's value from the given cosine value.
static AngleT< float > asinf (double value)
Computes this angle's value from the given sine value.
static AngleT< float > atanf (double value)
Computes this angle's value from the given tangent value.
static AngleT< double > acosd (double value)
Computes this angle's value from the given cosine value.
static AngleT< double > asind (double value)
Computes this angle's value from the given sine value.
static AngleT< double > atand (double value)
Computes this angle's value from the given tangent value.
template<typename Type >
bool operator== (AngleT< Type > const &lhs, AngleT< Type > const &rhs) noexcept
Equality operator.
template<typename Type >
bool operator!= (AngleT< Type > const &lhs, AngleT< Type > const &rhs) noexcept
Difference operator.
template<typename Type >
bool operator< (AngleT< Type > const &lhs, AngleT< Type > const &rhs) noexcept
"Less than" operator
template<typename Type >
bool operator>= (AngleT< Type > const &lhs, AngleT< Type > const &rhs) noexcept
"Greater than or equal to" operator
template<typename Type >
bool operator> (AngleT< Type > const &lhs, AngleT< Type > const &rhs) noexcept
"Greater than" operator
template<typename Type >
bool operator<= (AngleT< Type > const &lhs, AngleT< Type > const &rhs) noexcept
"Less than or equal to" operator
template<typename Type >
AngleT< Type > operator+ (AngleT< Type > const &lhs, AngleT< Type > const &rhs) noexcept
addition operator
template<typename Type >
AngleT< Type > operator- (AngleT< Type > const &lhs, AngleT< Type > const &rhs) noexcept
Substraction operator.
template<typename Type >
AngleT< Type > operator* (AngleT< Type > const &lhs, AngleT< Type > const &rhs) noexcept
Multiplication operator.
template<typename Type >
AngleT< Type > operator/ (AngleT< Type > const &lhs, AngleT< Type > const &rhs) noexcept
Division operator.
template<typename Type >
AngleT< Type > operator* (AngleT< Type > const &lhs, double rhs) noexcept
Multiplication operator.
template<typename Type >
AngleT< Type > operator/ (AngleT< Type > const &lhs, double rhs) noexcept
Division operator.
template<typename TypeT >
static TypeT convert (TypeT const &value, LengthUnit from, LengthUnit to)
template<std::integral TypeT>
constexpr TypeT divRoundUp (TypeT num, TypeT denom)
Division rounded up.
CU_API bool operator== (PlaneEquation const &lhs, PlaneEquation const &rhs)
Checks if this plane is equal to another one.
CU_API bool operator!= (PlaneEquation const &lhs, PlaneEquation const &rhs)
Checks if this plane is different from another one.
template<typename T >
QuaternionT< T > operator+ (QuaternionT< T > const &lhs, QuaternionT< T > const &rhs)
addition operator
template<typename T >
QuaternionT< T > operator- (QuaternionT< T > const &lhs, QuaternionT< T > const &rhs)
Substraction operator.
template<typename T >
QuaternionT< T > operator* (QuaternionT< T > const &lhs, QuaternionT< T > const &rhs)
Multiplication operator.
template<typename T >
QuaternionT< T > operator* (QuaternionT< T > const &lhs, double rhs)
Multiplication operator.
template<typename T >
QuaternionT< T > operator* (QuaternionT< T > const &lhs, float rhs)
Multiplication operator.
template<typename T >
QuaternionT< T > operator* (double lhs, QuaternionT< T > const &rhs)
Multiplication operator.
template<typename T >
QuaternionT< T > operator* (float lhs, QuaternionT< T > const &rhs)
Multiplication operator.
template<typename T >
QuaternionT< T > operator- (QuaternionT< T > const &quat)
Negation operator.
template<typename CharT , typename T >
std::basic_ostream< CharT > & operator<< (std::basic_ostream< CharT > &stream, QuaternionT< T > const &quat)
Stream operator.
template<typename T >
Range< T > makeRange (T const &min, T const &max) noexcept
Helper function to create a range.
template<typename T >
RangedValue< T > makeRangedValue (T const &value, T const &min, T const &max) noexcept
Helper function to create a ranged value.
template<typename T >
RangeSequenceT< T > makeRangeSequence (Vector< T > const &sequence)
template<typename DurationT , typename ValueT >
SpeedT< ValueT, DurationT > makeSpeed (ValueT const &value)
template<typename DurationT , typename ValueT >
SpeedT< ValueT, DurationT > makeSpeed (ValueT const &value, DurationT const &)
static constexpr uint32_t getBitSize (uint64_t value)
static constexpr uint32_t getBitSize (uint32_t value)
static constexpr uint32_t getNextPowerOfTwo (uint32_t value)
static constexpr bool isPowerOfTwo (uint32_t value)
CU_API OutputStream & operator<< (OutputStream &stream, CpuInformations const &object)
Output stream operator.
template<typename T >
uint32_t hashCombine32 (uint32_t &hash, T const &rhs)
template<typename T >
uint32_t hashCombinePtr32 (uint32_t &hash, T const &rhs)
template<typename T >
uint64_t hashCombine64 (uint64_t &hash, T const &rhs)
template<typename T >
uint64_t hashCombinePtr64 (uint64_t &hash, T const &rhs)
template<typename T >
size_t hashCombine (size_t &hash, T const &rhs)
template<typename T >
size_t hashCombinePtr (size_t &hash, T const &rhs)
CU_API void getLocaltime (std::tm *tm, time_t const *time)
template<typename T , size_t N>
size_t getCountOf (T const(&data)[N])
template<typename NoiseT >
FractalNoiseT< NoiseT > makeFractalNoise (uint32_t octaves, NoiseT noise)
template<typename CharType >
std::basic_ostream< CharType > & operator<< (std::basic_ostream< CharType > &stream, format::Indent const &ind)
Stream operator.
template<typename CharType , typename PrefixType >
std::basic_ostream< CharType > & operator<< (std::basic_ostream< CharType > &stream, format::BasePrefixer< CharType, PrefixType > const &)
Stream operator.
template<typename BlockTypeT >
bool operator== (DynamicBitsetT< BlockTypeT > const &lhs, DynamicBitsetT< BlockTypeT > const &rhs)
template<typename BlockTypeT >
bool operator!= (DynamicBitsetT< BlockTypeT > const &lhs, DynamicBitsetT< BlockTypeT > const &rhs)
template<typename BlockTypeT >
DynamicBitsetT< BlockTypeT > operator<< (DynamicBitsetT< BlockTypeT > const &lhs, int rhs)
template<typename BlockTypeT >
DynamicBitsetT< BlockTypeT > operator>> (DynamicBitsetT< BlockTypeT > const &lhs, int rhs)
template<typename BlockTypeT >
DynamicBitsetT< BlockTypeT > operator& (DynamicBitsetT< BlockTypeT > const &lhs, DynamicBitsetT< BlockTypeT > const &rhs)
template<typename BlockTypeT >
DynamicBitsetT< BlockTypeT > operator| (DynamicBitsetT< BlockTypeT > const &lhs, DynamicBitsetT< BlockTypeT > const &rhs)
template<typename BlockTypeT >
DynamicBitsetT< BlockTypeT > operator^ (DynamicBitsetT< BlockTypeT > const &lhs, DynamicBitsetT< BlockTypeT > const &rhs)
template<typename BlockTypeT >
bool operator== (typename DynamicBitsetT< BlockTypeT >::Bit const &lhs, typename DynamicBitsetT< BlockTypeT >::Bit const &rhs)
template<typename BlockTypeT >
bool operator!= (typename DynamicBitsetT< BlockTypeT >::Bit const &lhs, typename DynamicBitsetT< BlockTypeT >::Bit const &rhs)
template<typename BlockTypeT >
DynamicBitsetT< BlockTypeT >::Bit operator| (typename DynamicBitsetT< BlockTypeT >::Bit const &lhs, bool rhs)
template<typename BlockTypeT >
DynamicBitsetT< BlockTypeT >::Bit operator& (typename DynamicBitsetT< BlockTypeT >::Bit const &lhs, bool rhs)
template<typename BlockTypeT >
DynamicBitsetT< BlockTypeT >::Bit operator^ (typename DynamicBitsetT< BlockTypeT >::Bit const &lhs, bool rhs)
Comparison operators.
template<typename FlagType >
constexpr bool operator== (FlagCombination< FlagType > const &lhs, FlagCombination< FlagType > const &rhs) noexcept
template<typename FlagType >
constexpr bool operator== (FlagCombination< FlagType > const &lhs, FlagType const &rhs) noexcept
template<typename FlagType >
constexpr bool operator!= (FlagCombination< FlagType > const &lhs, FlagCombination< FlagType > const &rhs) noexcept
template<typename FlagType >
constexpr bool operator!= (FlagCombination< FlagType > const &lhs, FlagType const &rhs) noexcept
Binary operators.
template<typename FlagType >
constexpr FlagCombination< FlagType > operator& (FlagCombination< FlagType > const &lhs, FlagType const &rhs) noexcept
template<typename FlagType >
constexpr FlagCombination< FlagType > operator| (FlagCombination< FlagType > const &lhs, FlagType const &rhs) noexcept
template<typename FlagType >
constexpr FlagCombination< FlagType > operator^ (FlagCombination< FlagType > const &lhs, FlagType const &rhs) noexcept
template<typename FlagType >
constexpr FlagCombination< FlagType > operator& (FlagCombination< FlagType > const &lhs, typename FlagCombination< FlagType >::BaseType const &rhs) noexcept
template<typename FlagType >
constexpr FlagCombination< FlagType > operator| (FlagCombination< FlagType > const &lhs, typename FlagCombination< FlagType >::BaseType const &rhs) noexcept
template<typename FlagType >
constexpr FlagCombination< FlagType > operator^ (FlagCombination< FlagType > const &lhs, typename FlagCombination< FlagType >::BaseType const &rhs) noexcept
template<typename FlagType >
constexpr FlagCombination< FlagType > operator& (FlagCombination< FlagType > const &lhs, FlagCombination< FlagType > const &rhs) noexcept
template<typename FlagType >
constexpr FlagCombination< FlagType > operator| (FlagCombination< FlagType > const &lhs, FlagCombination< FlagType > const &rhs) noexcept
template<typename FlagType >
constexpr FlagCombination< FlagType > operator^ (FlagCombination< FlagType > const &lhs, FlagCombination< FlagType > const &rhs) noexcept
Arithmetic operators.
template<PixelFormat FT, PixelFormat FU>
Pixel< FT > operator+ (Pixel< FT > const &lhs, Pixel< FU > const &rhs)
template<PixelFormat FT, PixelFormat FU>
Pixel< FT > operator- (Pixel< FT > const &lhs, Pixel< FU > const &rhs)
template<PixelFormat FT, PixelFormat FU>
Pixel< FT > operator/ (Pixel< FT > const &lhs, Pixel< FU > const &rhs)
template<PixelFormat FT, PixelFormat FU>
Pixel< FT > operator* (Pixel< FT > const &lhs, Pixel< FU > const &rhs)
template<typename TypeT >
LengthT< TypeT > operator+ (LengthT< TypeT > const &lhs, LengthT< TypeT > const &rhs) noexcept
template<typename TypeT >
LengthT< TypeT > operator- (LengthT< TypeT > const &lhs, LengthT< TypeT > const &rhs) noexcept
template<typename TypeT >
LengthT< TypeT > operator+ (TypeT const &lhs, LengthT< TypeT > const &rhs) noexcept
template<typename TypeT >
LengthT< TypeT > operator- (TypeT const &lhs, LengthT< TypeT > const &rhs) noexcept
template<typename TypeT >
LengthT< TypeT > operator+ (LengthT< TypeT > const &lhs, TypeT const &rhs) noexcept
template<typename TypeT >
LengthT< TypeT > operator- (LengthT< TypeT > const &lhs, TypeT const &rhs) noexcept
template<typename TypeT >
LengthT< TypeT > operator* (LengthT< TypeT > const &lhs, double rhs) noexcept
template<typename TypeT >
LengthT< TypeT > operator/ (LengthT< TypeT > const &lhs, double rhs) noexcept
template<typename T >
T operator+ (T const &lhs, RangedValue< T > const &rhs) noexcept
template<typename T >
T operator- (T const &lhs, RangedValue< T > const &rhs) noexcept
template<typename T >
T operator* (T const &lhs, RangedValue< T > const &rhs) noexcept
template<typename T >
T operator/ (T const &lhs, RangedValue< T > const &rhs) noexcept
template<typename T >
T operator+ (RangedValue< T > const &lhs, T const &rhs) noexcept
template<typename T >
T operator- (RangedValue< T > const &lhs, T const &rhs) noexcept
template<typename T >
T operator* (RangedValue< T > const &lhs, T const &rhs) noexcept
template<typename T >
T operator/ (RangedValue< T > const &lhs, T const &rhs) noexcept
template<typename T >
T operator+ (RangedValue< T > const &lhs, RangedValue< T > const &rhs) noexcept
template<typename T >
T operator- (RangedValue< T > const &lhs, RangedValue< T > const &rhs) noexcept
template<typename T >
T operator* (RangedValue< T > const &lhs, RangedValue< T > const &rhs) noexcept
template<typename T >
T operator/ (RangedValue< T > const &lhs, RangedValue< T > const &rhs) noexcept
template<typename T , uint32_t Count, typename U , uint32_t UCount>
bool operator== (Coords< T, Count > const &lhs, Coords< U, UCount > const &rhs)
template<typename T , uint32_t Count, typename U , uint32_t UCount>
bool operator!= (Coords< T, Count > const &lhs, Coords< U, UCount > const &rhs)
template<typename T , uint32_t Count>
Point< std::remove_cv_t< T >, Count > operator- (Coords< T, Count > const &rhs)
template<typename T , uint32_t Count, typename U , uint32_t UCount>
Point< std::remove_cv_t< T >, Count > operator+ (Coords< T, Count > const &lhs, Coords< U, UCount > const &rhs)
template<typename T , uint32_t Count, typename U , uint32_t UCount>
Point< std::remove_cv_t< T >, Count > operator- (Coords< T, Count > const &lhs, Coords< U, UCount > const &rhs)
template<typename T , uint32_t Count, typename U , uint32_t UCount>
Point< std::remove_cv_t< T >, Count > operator* (Coords< T, Count > const &lhs, Coords< U, UCount > const &rhs)
template<typename T , uint32_t Count, typename U , uint32_t UCount>
Point< std::remove_cv_t< T >, Count > operator/ (Coords< T, Count > const &lhs, Coords< U, UCount > const &rhs)
template<typename T , uint32_t Count, typename U >
Point< std::remove_cv_t< T >, Count > operator+ (Coords< T, Count > const &lhs, U const *rhs)
template<typename T , uint32_t Count, typename U >
Point< std::remove_cv_t< T >, Count > operator- (Coords< T, Count > const &lhs, U const *rhs)
template<typename T , uint32_t Count, typename U >
Point< std::remove_cv_t< T >, Count > operator* (Coords< T, Count > const &lhs, U const *rhs)
template<typename T , uint32_t Count, typename U >
Point< std::remove_cv_t< T >, Count > operator/ (Coords< T, Count > const &lhs, U const *rhs)
template<typename T , uint32_t Count, typename U >
Point< std::remove_cv_t< T >, Count > operator+ (Coords< T, Count > const &lhs, T const &rhs)
template<typename T , uint32_t Count, typename U >
Point< std::remove_cv_t< T >, Count > operator- (Coords< T, Count > const &lhs, T const &rhs)
template<typename T , uint32_t Count>
Point< std::remove_cv_t< T >, Count > operator* (Coords< T, Count > const &lhs, T const &rhs)
template<typename T , uint32_t Count>
Point< std::remove_cv_t< T >, Count > operator/ (Coords< T, Count > const &lhs, T const &rhs)
template<typename T , uint32_t Count>
String & operator<< (String &out, Coords< T, Count > const &in)
template<typename T , uint32_t Count>
String & operator>> (String &in, Coords< T, Count > &out)
template<typename T , uint32_t Count, typename CharType >
std::basic_ostream< CharType > & operator<< (std::basic_ostream< CharType > &out, Coords< T, Count > const &in)
template<typename T , uint32_t Count, typename CharType >
std::basic_istream< CharType > & operator>> (std::basic_istream< CharType > &in, Coords< T, Count > &out)
Logic operators.
template<typename TypeT >
bool operator== (LengthT< TypeT > const &lhs, LengthT< TypeT > const &rhs) noexcept
template<typename TypeT >
bool operator!= (LengthT< TypeT > const &lhs, LengthT< TypeT > const &rhs) noexcept
template<typename TypeT >
bool operator< (LengthT< TypeT > const &lhs, LengthT< TypeT > const &rhs) noexcept
template<typename TypeT >
bool operator>= (LengthT< TypeT > const &lhs, LengthT< TypeT > const &rhs) noexcept
template<typename TypeT >
bool operator> (LengthT< TypeT > const &lhs, LengthT< TypeT > const &rhs) noexcept
template<typename TypeT >
bool operator<= (LengthT< TypeT > const &lhs, LengthT< TypeT > const &rhs) noexcept
template<typename T >
bool operator== (RangedValue< T > const &lhs, T const &rhs) noexcept
template<typename T >
bool operator!= (RangedValue< T > const &lhs, T const &rhs) noexcept
template<typename T >
bool operator> (RangedValue< T > const &lhs, T const &rhs) noexcept
template<typename T >
bool operator< (RangedValue< T > const &lhs, T const &rhs) noexcept
template<typename T >
bool operator>= (RangedValue< T > const &lhs, T const &rhs) noexcept
template<typename T >
bool operator<= (RangedValue< T > const &lhs, T const &rhs) noexcept
template<typename T >
bool operator== (T const &lhs, RangedValue< T > const &rhs) noexcept
template<typename T >
bool operator!= (T const &lhs, RangedValue< T > const &rhs) noexcept
template<typename T >
bool operator> (T const &lhs, RangedValue< T > const &rhs) noexcept
template<typename T >
bool operator< (T const &lhs, RangedValue< T > const &rhs) noexcept
template<typename T >
bool operator>= (T const &lhs, RangedValue< T > const &rhs) noexcept
template<typename T >
bool operator<= (T const &lhs, RangedValue< T > const &rhs) noexcept
template<typename T >
bool operator== (RangedValue< T > const &lhs, RangedValue< T > const &rhs) noexcept
template<typename T >
bool operator!= (RangedValue< T > const &lhs, RangedValue< T > const &rhs) noexcept
template<typename T >
bool operator> (RangedValue< T > const &lhs, RangedValue< T > const &rhs) noexcept
template<typename T >
bool operator< (RangedValue< T > const &lhs, RangedValue< T > const &rhs) noexcept
template<typename T >
bool operator>= (RangedValue< T > const &lhs, RangedValue< T > const &rhs) noexcept
template<typename T >
bool operator<= (RangedValue< T > const &lhs, RangedValue< T > const &rhs) noexcept
template<typename T , uint32_t Columns, uint32_t Rows>
bool operator== (Matrix< T, Columns, Rows > const &lhs, Matrix< T, Columns, Rows > const &rhs)
template<typename T , uint32_t Columns, uint32_t Rows>
bool operator!= (Matrix< T, Columns, Rows > const &lhs, Matrix< T, Columns, Rows > const &rhs)
template<typename T , uint32_t Columns, uint32_t Rows, typename U >
Matrix< T, Columns, Rows > operator+ (Matrix< T, Columns, Rows > const &lhs, Matrix< U, Columns, Rows > const &rhs)
template<typename T , uint32_t Columns, uint32_t Rows, typename U >
Matrix< T, Columns, Rows > operator- (Matrix< T, Columns, Rows > const &lhs, Matrix< U, Columns, Rows > const &rhs)
template<typename T , uint32_t Columns, uint32_t Rows, typename U , uint32_t ColumnsU>
Matrix< T, ColumnsU, Rows > operator* (Matrix< T, Columns, Rows > const &lhs, Matrix< U, ColumnsU, Columns > const &rhs)
template<typename T , uint32_t Columns, uint32_t Rows, typename U >
Point< T, Rows > operator* (Matrix< T, Columns, Rows > const &lhs, Point< U, Columns > const &rhs)
template<typename T , uint32_t Columns, uint32_t Rows, typename U >
Point< T, Columns > operator* (Point< T, Rows > const &lhs, Matrix< U, Columns, Rows > const &rhs)
template<typename T , uint32_t Columns, uint32_t Rows, typename U >
Matrix< T, Columns, Rows > operator+ (Matrix< T, Columns, Rows > const &lhs, U const *rhs)
template<typename T , uint32_t Columns, uint32_t Rows, typename U >
Matrix< T, Columns, Rows > operator- (Matrix< T, Columns, Rows > const &lhs, U const *rhs)
template<typename T , uint32_t Columns, uint32_t Rows, typename U >
Matrix< T, Columns, Rows > operator+ (Matrix< T, Columns, Rows > const &lhs, T const &rhs)
template<typename T , uint32_t Columns, uint32_t Rows, typename U >
Matrix< T, Columns, Rows > operator- (Matrix< T, Columns, Rows > const &lhs, T const &rhs)
template<typename T , uint32_t Columns, uint32_t Rows, typename U >
Matrix< T, Columns, Rows > operator* (Matrix< T, Columns, Rows > const &lhs, T const &rhs)
template<typename T , uint32_t Columns, uint32_t Rows, typename U >
Matrix< T, Columns, Rows > operator/ (Matrix< T, Columns, Rows > const &lhs, T const &rhs)
template<typename T , uint32_t Columns, uint32_t Rows, typename U >
Matrix< T, Columns, Rows > operator+ (T const &lhs, Matrix< U, Columns, Rows > const &rhs)
template<typename T , uint32_t Columns, uint32_t Rows, typename U >
Matrix< T, Columns, Rows > operator- (T const &lhs, Matrix< U, Columns, Rows > const &rhs)
template<typename T , uint32_t Columns, uint32_t Rows, typename U >
Matrix< T, Columns, Rows > operator* (T const &lhs, Matrix< U, Columns, Rows > const &rhs)
template<typename T , uint32_t Columns, uint32_t Rows>
Matrix< T, Columns, Rows > operator- (Matrix< T, Columns, Rows > const &rhs)
template<typename T , uint32_t Columns, uint32_t Rows>
String & operator<< (String &stream, Matrix< T, Columns, Rows > const &matrix)
template<typename T , uint32_t Columns, uint32_t Rows>
String & operator>> (String &stream, Matrix< T, Columns, Rows > &matrix)
template<typename CharT , typename T , uint32_t Columns, uint32_t Rows>
std::basic_ostream< CharT > & operator<< (std::basic_ostream< CharT > &stream, Matrix< T, Columns, Rows > const &matrix)
template<typename CharT , typename T , uint32_t Columns, uint32_t Rows>
std::basic_istream< CharT > & operator>> (std::basic_istream< CharT > &stream, Matrix< T, Columns, Rows > &matrix)
template<typename T , uint32_t TCount, typename U , uint32_t UCount>
bool operator== (Point< T, TCount > const &lhs, Point< U, UCount > const &rhs)
template<typename T , uint32_t TCount, typename U , uint32_t UCount>
bool operator!= (Point< T, TCount > const &lhs, Point< U, UCount > const &rhs)
template<typename T , uint32_t TCount, typename U , uint32_t UCount>
bool operator== (Point< T, TCount > const &lhs, Coords< U, UCount > const &rhs)
template<typename T , uint32_t TCount, typename U , uint32_t UCount>
bool operator!= (Point< T, TCount > const &lhs, Coords< U, UCount > const &rhs)
template<typename T , uint32_t TCount, typename U , uint32_t UCount>
bool operator== (Coords< T, TCount > const &lhs, Point< U, UCount > const &rhs)
template<typename T , uint32_t TCount, typename U , uint32_t UCount>
bool operator!= (Coords< T, TCount > const &lhs, Point< U, UCount > const &rhs)
template<typename T , uint32_t TCount>
Point< std::remove_cv_t< T >, TCount > operator- (Point< T, TCount > const &rhs)
template<typename T , uint32_t TCount, typename U , uint32_t UCount>
Point< std::remove_cv_t< T >, TCount > operator+ (Point< T, TCount > const &lhs, Point< U, UCount > const &rhs)
template<typename T , uint32_t TCount, typename U , uint32_t UCount>
Point< std::remove_cv_t< T >, TCount > operator- (Point< T, TCount > const &lhs, Point< U, UCount > const &rhs)
template<typename T , uint32_t TCount, typename U , uint32_t UCount>
Point< std::remove_cv_t< T >, TCount > operator* (Point< T, TCount > const &lhs, Point< U, UCount > const &rhs)
template<typename T , uint32_t TCount, typename U , uint32_t UCount>
Point< std::remove_cv_t< T >, TCount > operator/ (Point< T, TCount > const &lhs, Point< U, UCount > const &rhs)
template<typename T , uint32_t TCount, typename U , uint32_t UCount>
Point< std::remove_cv_t< T >, TCount > operator+ (Point< T, TCount > const &lhs, Coords< U, UCount > const &rhs)
template<typename T , uint32_t TCount, typename U , uint32_t UCount>
Point< std::remove_cv_t< T >, TCount > operator- (Point< T, TCount > const &lhs, Coords< U, UCount > const &rhs)
template<typename T , uint32_t TCount, typename U , uint32_t UCount>
Point< std::remove_cv_t< T >, TCount > operator* (Point< T, TCount > const &lhs, Coords< U, UCount > const &rhs)
template<typename T , uint32_t TCount, typename U , uint32_t UCount>
Point< std::remove_cv_t< T >, TCount > operator/ (Point< T, TCount > const &lhs, Coords< U, UCount > const &rhs)
template<typename T , uint32_t TCount, typename U , uint32_t UCount>
Point< std::remove_cv_t< T >, TCount > operator+ (Coords< T, TCount > const &lhs, Point< U, UCount > const &rhs)
template<typename T , uint32_t TCount, typename U , uint32_t UCount>
Point< std::remove_cv_t< T >, TCount > operator- (Coords< T, TCount > const &lhs, Point< U, UCount > const &rhs)
template<typename T , uint32_t TCount, typename U , uint32_t UCount>
Point< std::remove_cv_t< T >, TCount > operator* (Coords< T, TCount > const &lhs, Point< U, UCount > const &rhs)
template<typename T , uint32_t TCount, typename U , uint32_t UCount>
Point< std::remove_cv_t< T >, TCount > operator/ (Coords< T, TCount > const &lhs, Point< U, UCount > const &rhs)
template<typename T , uint32_t TCount, typename U >
Point< std::remove_cv_t< T >, TCount > operator+ (Point< T, TCount > const &lhs, U const *rhs)
template<typename T , uint32_t TCount, typename U >
Point< std::remove_cv_t< T >, TCount > operator- (Point< T, TCount > const &lhs, U const *rhs)
template<typename T , uint32_t TCount, typename U >
Point< std::remove_cv_t< T >, TCount > operator* (Point< T, TCount > const &lhs, U const *rhs)
template<typename T , uint32_t TCount, typename U >
Point< std::remove_cv_t< T >, TCount > operator/ (Point< T, TCount > const &lhs, U const *rhs)
template<typename T , uint32_t TCount>
Point< std::remove_cv_t< T >, TCount > operator+ (Point< T, TCount > const &lhs, T const &rhs)
template<typename T , uint32_t TCount>
Point< std::remove_cv_t< T >, TCount > operator- (Point< T, TCount > const &lhs, T const &rhs)
template<typename T , uint32_t TCount>
Point< std::remove_cv_t< T >, TCount > operator* (Point< T, TCount > const &lhs, T const &rhs)
template<typename T , uint32_t TCount>
Point< std::remove_cv_t< T >, TCount > operator/ (Point< T, TCount > const &lhs, T const &rhs)
template<typename DstCompT , typename SrcT >
PointTypeT< SrcT, DstCompT > pointCast (SrcT const &src)
template<typename T , uint32_t TCount>
String & operator<< (String &out, Point< T, TCount > const &in)
template<typename T , uint32_t TCount>
String & operator>> (String &in, Point< T, TCount > &out)
template<typename T , uint32_t TCount, typename CharType >
std::basic_ostream< CharType > & operator<< (std::basic_ostream< CharType > &out, Point< T, TCount > const &in)
template<typename T , uint32_t TCount, typename CharType >
std::basic_istream< CharType > & operator>> (std::basic_istream< CharType > &in, Point< T, TCount > &out)
Comparaison.
template<typename ValueT , typename DurationT , typename TraitsT >
bool operator== (SpeedT< ValueT, DurationT, TraitsT > const &lhs, SpeedT< ValueT, DurationT, TraitsT > const &rhs)
template<typename ValueT , typename DurationT , typename TraitsT >
bool operator!= (SpeedT< ValueT, DurationT, TraitsT > const &lhs, SpeedT< ValueT, DurationT, TraitsT > const &rhs)
template<typename ValueT , typename DurationT , typename TraitsT >
bool operator< (SpeedT< ValueT, DurationT, TraitsT > const &lhs, SpeedT< ValueT, DurationT, TraitsT > const &rhs)
template<typename ValueT , typename DurationT , typename TraitsT >
bool operator>= (SpeedT< ValueT, DurationT, TraitsT > const &lhs, SpeedT< ValueT, DurationT, TraitsT > const &rhs)
template<typename ValueT , typename DurationT , typename TraitsT >
bool operator> (SpeedT< ValueT, DurationT, TraitsT > const &lhs, SpeedT< ValueT, DurationT, TraitsT > const &rhs)
template<typename ValueT , typename DurationT , typename TraitsT >
bool operator<= (SpeedT< ValueT, DurationT, TraitsT > const &lhs, SpeedT< ValueT, DurationT, TraitsT > const &rhs)
template<typename T , uint32_t Count>
bool operator== (SquareMatrix< T, Count > const &lhs, SquareMatrix< T, Count > const &rhs)
template<typename T , uint32_t Count>
bool operator!= (SquareMatrix< T, Count > const &lhs, SquareMatrix< T, Count > const &rhs)
template<typename T , uint32_t Count, typename U >
SquareMatrix< T, Count > operator+ (SquareMatrix< T, Count > const &lhs, SquareMatrix< U, Count > const &rhs)
template<typename T , uint32_t Count, typename U >
SquareMatrix< T, Count > operator- (SquareMatrix< T, Count > const &lhs, SquareMatrix< U, Count > const &rhs)
template<typename T , uint32_t Count, typename U >
SquareMatrix< T, Count > operator* (SquareMatrix< T, Count > const &lhs, SquareMatrix< U, Count > const &rhs)
template<typename T , uint32_t Count, typename U , uint32_t Columns>
SquareMatrix< T, Count > operator* (SquareMatrix< T, Count > const &lhs, Matrix< U, Columns, Count > const &rhs)
template<typename T , uint32_t Count, typename U >
SquareMatrix< T, Count > operator+ (SquareMatrix< T, Count > const &lhs, U const *rhs)
template<typename T , uint32_t Count, typename U >
SquareMatrix< T, Count > operator- (SquareMatrix< T, Count > const &lhs, U const *rhs)
template<typename T , uint32_t Count, typename U >
SquareMatrix< T, Count > operator* (SquareMatrix< T, Count > const &lhs, U const *rhs)
template<typename T , uint32_t Count, typename U >
SquareMatrix< T, Count > operator+ (SquareMatrix< T, Count > const &lhs, T const &rhs)
template<typename T , uint32_t Count, typename U >
SquareMatrix< T, Count > operator- (SquareMatrix< T, Count > const &lhs, T const &rhs)
template<typename T , uint32_t Count, typename U >
SquareMatrix< T, Count > operator* (SquareMatrix< T, Count > const &lhs, T const &rhs)
template<typename T , uint32_t Count, typename U >
SquareMatrix< T, Count > operator/ (SquareMatrix< T, Count > const &lhs, T const &rhs)
template<typename T , uint32_t Count, typename U , uint32_t Rows>
Matrix< T, Count, Rows > operator* (Matrix< U, Count, Rows > const &lhs, SquareMatrix< T, Count > const &rhs)
template<typename T , uint32_t Count>
SquareMatrix< T, Count > operator+ (T const &lhs, SquareMatrix< T, Count > const &rhs)
template<typename T , uint32_t Count>
SquareMatrix< T, Count > operator- (T const &lhs, SquareMatrix< T, Count > const &rhs)
template<typename T , uint32_t Count>
SquareMatrix< T, Count > operator* (T const &lhs, SquareMatrix< T, Count > const &rhs)
template<typename T , uint32_t Count>
SquareMatrix< T, Count > operator- (SquareMatrix< T, Count > const &rhs)
template<typename CharT , typename T , uint32_t Count>
std::basic_ostream< CharT > & operator<< (std::basic_ostream< CharT > &streamOut, SquareMatrix< T, Count > const &matrix)
template<typename CharT , typename T , uint32_t Count>
std::basic_istream< CharT > & operator>> (std::basic_istream< CharT > &streamIn, SquareMatrix< T, Count > &matrix)
Variables
static NoInit constexpr noInit
static const MbString ERROR_UNKNOWN_OBJECT = "Unknown object type"
static Array< MbStringView, size_t(UnicityError::eCount) > const STR_UNICITY_ERROR
Unicity error texts.
template<ParameterType Type>
bool constexpr isArithmeticTypeV = IsArithmeticType< Type >::value
template<details::ValueTypeT DataT, DataT ... ValuesT>
static DataT minValueT = details::MinRecT< DataT, ValuesT... >::value
template<details::ValueTypeT DataT, DataT ... ValuesT>
static DataT constexpr maxValueT = details::MaxRecT< DataT, ValuesT... >::value
template<typename T >
static bool constexpr isRangedValueT = IsRangedValueT< T >::value
template<typename ValueT >
static bool constexpr isSpeedT = IsSpeedT< ValueT >::value
Data
enum class FileType : uint8_t { eBinary = 0 , eText = 1 , eCount , eMin = eBinary }
castor::Loader supported file types enumeration
CU_DeclareVector (Path, Path)
Graphics
enum class PixelFormat : uint32_t { CUPF_ENUM_VALUE , eCount , eMin = eUNDEFINED }
Pixel format enumeration.
enum class PredefinedRgbaColour : uint32_t {
eTransparentBlack = 0x00000000 , eLowAlphaBlack = 0x00000040 , eMedAlphaBlack = 0x0000007F , eHighAlphaBlack = 0x000000BF ,
eOpaqueBlack = 0x000000FF , eTransparentDarkBlue = 0x00007F00 , eLowAlphaDarkBlue = 0x00007F40 , eMedAlphaDarkBlue = 0x00007F7F ,
eHighAlphaDarkBlue = 0x00007FBF , eOpaqueDarkBlue = 0x00007FFF , eTransparentBlue = 0x0000FF00 , eLowAlphaBlue = 0x0000FF40 ,
eMedAlphaBlue = 0x0000FF7F , eHighAlphaBlue = 0x0000FFBF , eOpaqueBlue = 0x0000FFFF , eTransparentDarkGreen = 0x007F0000 ,
eLowAlphaDarkGreen = 0x007F0040 , eMedAlphaDarkGreen = 0x007F007F , eHighAlphaDarkGreen = 0x007F00BF , eOpaqueDarkGreen = 0x007F00FF ,
eTransparentGreen = 0x00FF0000 , eLowAlphaGreen = 0x00FF0040 , eMedAlphaGreen = 0x00FF007F , eHighAlphaGreen = 0x00FF00BF ,
eOpaqueGreen = 0x00FF00FF , eTransparentDarkRed = 0x7F000000 , eLowAlphaDarkRed = 0x7F000040 , eMedAlphaDarkRed = 0x7F00007F ,
eHighAlphaDarkRed = 0x7F0000BF , eOpaqueDarkRed = 0x7F0000FF , eTransparentRed = 0xFF000000 , eLowAlphaRed = 0xFF000040 ,
eMedAlphaRed = 0xFF00007F , eHighAlphaRed = 0xFF0000BF , eOpaqueRed = 0xFF0000FF , eTransparentLightBlue = 0x7F7FFF00 ,
eLowAlphaLightBlue = 0x7F7FFF40 , eMedAlphaLightBlue = 0x7F7FFF7F , eHighAlphaLightBlue = 0x7F7FFFBF , eOpaqueLightBlue = 0x7F7FFFFF ,
eTransparentLightGreen = 0x7FFF7F00 , eLowAlphaLightGreen = 0x7FFF7F40 , eMedAlphaLightGreen = 0x7FFF7F7F , eHighAlphaLightGreen = 0x7FFF7FBF ,
eOpaqueLightGreen = 0x7FFF7FFF , eTransparentLightRed = 0xFF7F7F00 , eLowAlphaLightRed = 0xFF7F7F40 , eMedAlphaLightRed = 0xFF7F7F7F ,
eHighAlphaLightRed = 0xFF7F7FBF , eOpaqueLightRed = 0xFF7F7FFF , eTransparentWhite = 0xFFFFFF00 , eLowAlphaWhite = 0xFFFFFF40 ,
eMedAlphaWhite = 0xFFFFFF7F , eHighAlphaWhite = 0xFFFFFFBF , eOpaqueWhite = 0xFFFFFFFF
}
Predefined colours enumeration.
enum class PredefinedRgbColour : uint32_t {
eBlack = 0x000000FF , eDarkBlue = 0x00007FFF , eBlue = 0x0000FFFF , eDarkGreen = 0x007F00FF ,
eGreen = 0x00FF00FF , eDarkRed = 0x7F0000FF , eRed = 0xFF0000FF , eLightBlue = 0x7F7FFFFF ,
eLightGreen = 0x7FFF7FFF , eLightRed = 0xFF7F7FFF , eWhite = 0xFFFFFFFF
}
Predefined colours enumeration.
enum class RgbaComponent : uint8_t {
eRed = 0 , eGreen = 1 , eBlue = 2 , eAlpha = 3 ,
eCount , eMin = eRed
}
RgbaColourT components enumeration.
enum class RgbComponent : uint8_t {
eRed = 0 , eGreen = 1 , eBlue = 2 , eCount ,
eMin = eRed
}
RgbColourT components enumeration.
enum class Intersection : uint8_t {
eIn = 0 , eOut = 1 , eIntersect = 2 , eCount ,
eMin = eIn
}
Intersection types.
enum class PixelComponent : uint8_t {
eRed = 0x01 , eGreen = 0x02 , eBlue = 0x04 , eAlpha = 0x08 ,
eDepth = 0x10 , eStencil = 0x20
}
Pixel PixelComponentsT enumeration.
using BoundingContainer2D = BoundingContainer< 2 >
Typedef on a 2 dimensions BoundingContainer.
using BoundingContainer3D = BoundingContainer< 3 >
Typedef on a 3 dimensions BoundingContainer.
using UbPixel = Pixel< PixelFormat::eR8G8B8A8_UNORM >
Typedef over a pixel in A8R8G8B8 format.
using PixelComponents = castor::FlagCombination< PixelComponent >
template<typename TypeT >
using LargerTypeT = typename LargerTyperT< TypeT >::Type
using FontCacheTraits = ResourceCacheTraitsT< Font, String >
using ImageLoaderPtr = castor::RawUniquePtr< ImageLoaderImpl >
using ImageWriterPtr = castor::RawUniquePtr< ImageWriterImpl >
using PixelBuffer = PxBuffer< PixelFormat::eR8G8B8A8_UNORM >
using FontCache = ResourceCacheT< Font, String, FontCacheTraits >
using RgbColour = RgbColourT< ColourComponent >
using RgbaColour = RgbaColourT< ColourComponent >
using HdrRgbColour = RgbColourT< HdrColourComponent >
using HdrRgbaColour = RgbaColourT< HdrColourComponent >
template<PixelFormat PixelFormatT>
static PixelFormat constexpr singleComponentV = SingleComponentT< PixelFormatT >::value
template<PixelFormat PixelFormatT>
static bool constexpr isColourFormatV = IsColourFormat< PixelFormatT >::value
template<PixelFormat PixelFormatT>
static bool constexpr isDepthFormatV = IsDepthFormat< PixelFormatT >::value
template<PixelFormat PixelFormatT>
static bool constexpr isStencilFormatV = IsStencilFormat< PixelFormatT >::value
template<PixelFormat PixelFormatT>
static bool constexpr isDepthStencilFormatV = IsDepthStencilFormat< PixelFormatT >::value
template<PixelFormat PixelFormatT>
static bool constexpr isCompressedV = IsCompressed< PixelFormatT >::value
template<PixelFormat PixelFormatT>
static bool constexpr hasAlphaV = HasAlpha< PixelFormatT >::value
template<PixelFormat PixelFormatT>
static bool constexpr is8SRGBComponentsV = Is8SRGBComponents< PixelFormatT >::value
template<PixelFormat PixelFormatT>
static bool constexpr is8UComponentsV = Is8UComponents< PixelFormatT >::value
template<PixelFormat PixelFormatT>
static bool constexpr is16UComponentsV = Is16UComponents< PixelFormatT >::value
template<PixelFormat PixelFormatT>
static bool constexpr is32UComponentsV = Is32UComponents< PixelFormatT >::value
template<PixelFormat PixelFormatT>
static bool constexpr is64UComponentsV = Is64UComponents< PixelFormatT >::value
template<PixelFormat PixelFormatT>
static bool constexpr is8SComponentsV = Is8SComponents< PixelFormatT >::value
template<PixelFormat PixelFormatT>
static bool constexpr is16SComponentsV = Is16SComponents< PixelFormatT >::value
template<PixelFormat PixelFormatT>
static bool constexpr is32SComponentsV = Is32SComponents< PixelFormatT >::value
template<PixelFormat PixelFormatT>
static bool constexpr is64SComponentsV = Is64SComponents< PixelFormatT >::value
template<PixelFormat PixelFormatT>
static bool constexpr is16FComponentsV = Is16FComponents< PixelFormatT >::value
template<PixelFormat PixelFormatT>
static bool constexpr is32FComponentsV = Is32FComponents< PixelFormatT >::value
template<PixelFormat PixelFormatT>
static bool constexpr is64FComponentsV = Is64FComponents< PixelFormatT >::value
template<PixelFormat PixelFormatT>
static bool constexpr isD16UComponentV = IsD16UComponent< PixelFormatT >::value
template<PixelFormat PixelFormatT>
static bool constexpr isD24UComponentV = IsD24UComponent< PixelFormatT >::value
template<PixelFormat PixelFormatT>
static bool constexpr isD32FComponentV = IsD32FComponent< PixelFormatT >::value
template<PixelFormat PixelFormatT>
static bool constexpr isS8UComponentV = IsS8UComponent< PixelFormatT >::value
CU_API String getName (PixelComponent const &component)
CU_API String getName (PixelComponents const &components)
CU_DeclareSmartPtr (castor, BoundingBox, CU_API)
CU_DeclareSmartPtr (castor, BoundingSphere, CU_API)
CU_DeclareSmartPtr (castor, Image, CU_API)
CU_DeclareSmartPtr (castor, Font, CU_API)
CU_DeclareSmartPtr (castor, PxBufferBase, CU_API)
CU_DeclareSmartPtr (castor, FontCache, CU_API)
CU_API bool hasAlphaChannel (Image const &image)
Math
enum class LengthUnit {
eKilometre = 0 , eMetre = 1 , eCentimetre = 2 , eMillimetre = 3 ,
eYard = 4 , eFoot = 5 , eInch = 6 , eCount ,
eMin = eKilometre
}
using Angle = AngleT< float >
template<typename T >
using Point2 = Point< T, 2 >
template<typename T >
using Point3 = Point< T, 3 >
template<typename T >
using Point4 = Point< T, 4 >
template<typename T >
using Coords2 = Coords< T, 2 >
template<typename T >
using Coords3 = Coords< T, 3 >
template<typename T >
using Coords4 = Coords< T, 4 >
template<typename T >
using Matrix2x2 = SquareMatrix< T, 2 >
template<typename T >
using Matrix3x3 = SquareMatrix< T, 3 >
template<typename T >
using Matrix4x4 = SquareMatrix< T, 4 >
using Length = LengthT< float >
using Quaternion = QuaternionT< float >
using QuaternionArray = Vector< Quaternion >
using Vector2f = LengthT< Point2f >
using Vector3f = LengthT< Point3f >
using Vector4f = LengthT< Point4f >
using Vector2d = LengthT< Point2d >
using Vector3d = LengthT< Point3d >
using Vector4d = LengthT< Point4d >
template<typename SrcT , typename DstCompT >
using PointTypeT = typename PointTyperT< SrcT, DstCompT >::Type
template<typename TypeT >
using PointComponentT = typename PointComponentGetT< TypeT >::Type
template<typename Type >
static constexpr Type Pi { Type(3.1415926535897932384626433832795028841968) }
template<typename Type >
static constexpr Type PiMult2 { Type(3.1415926535897932384626433832795028841968 * 2.0) }
template<typename Type >
static constexpr Type Tau { Type(3.1415926535897932384626433832795028841968 * 2.0) }
template<typename Type >
static constexpr Type PiDiv2 { Type(3.1415926535897932384626433832795028841968 / 2.0) }
template<typename TypeT >
static constexpr bool isLengthV = IsLengthT< TypeT >::value
template<typename TypeT >
static constexpr bool isFloatingV
template<typename TypeT , typename CoordT , uint32_t CountT>
static constexpr bool isPointV
template<typename TypeT , typename CoordT >
static constexpr bool isPoint2V = isPointV< TypeT, CoordT, 2u >
template<typename TypeT , typename CoordT >
static constexpr bool isPoint3V = isPointV< TypeT, CoordT, 3u >
template<typename TypeT , typename CoordT >
static constexpr bool isPoint4V = isPointV< TypeT, CoordT, 4u >
template<typename TypeT >
static constexpr bool isPoint2f = isPoint2V< TypeT, float >
template<typename TypeT >
static constexpr bool isPoint3f = isPoint3V< TypeT, float >
template<typename TypeT >
static constexpr bool isPoint4f = isPoint4V< TypeT, float >
template<typename TypeT >
static constexpr bool isPoint2d = isPoint2V< TypeT, double >
template<typename TypeT >
static constexpr bool isPoint3d = isPoint3V< TypeT, double >
template<typename TypeT >
static constexpr bool isPoint4d = isPoint4V< TypeT, double >
CU_API String getName (LengthUnit value)
CU_DeclarePoint (bool, 4, b)
CU_DeclarePoint (bool, 3, b)
CU_DeclarePoint (bool, 2, b)
CU_DeclarePoint (int8_t, 4, c)
CU_DeclarePoint (int8_t, 3, c)
CU_DeclarePoint (int8_t, 2, c)
CU_DeclarePoint (uint8_t, 4, ub)
CU_DeclarePoint (uint8_t, 3, ub)
CU_DeclarePoint (uint8_t, 2, ub)
CU_DeclarePoint (int16_t, 4, s)
CU_DeclarePoint (int16_t, 3, s)
CU_DeclarePoint (int16_t, 2, s)
CU_DeclarePoint (uint16_t, 4, us)
CU_DeclarePoint (uint16_t, 3, us)
CU_DeclarePoint (uint16_t, 2, us)
CU_DeclarePoint (int32_t, 4, i)
CU_DeclarePoint (int32_t, 3, i)
CU_DeclarePoint (int32_t, 2, i)
CU_DeclarePoint (uint32_t, 4, ui)
CU_DeclarePoint (uint32_t, 3, ui)
CU_DeclarePoint (uint32_t, 2, ui)
CU_DeclarePoint (float, 4, f)
CU_DeclarePoint (float, 3, f)
CU_DeclarePoint (float, 2, f)
CU_DeclarePoint (double, 4, d)
CU_DeclarePoint (double, 3, d)
CU_DeclarePoint (double, 2, d)
CU_DeclareCoord (bool, 4, b)
CU_DeclareCoord (bool, 3, b)
CU_DeclareCoord (bool, 2, b)
CU_DeclareCoord (int8_t, 4, c)
CU_DeclareCoord (int8_t, 3, c)
CU_DeclareCoord (int8_t, 2, c)
CU_DeclareCoord (uint8_t, 4, ub)
CU_DeclareCoord (uint8_t, 3, ub)
CU_DeclareCoord (uint8_t, 2, ub)
CU_DeclareCoord (int16_t, 4, s)
CU_DeclareCoord (int16_t, 3, s)
CU_DeclareCoord (int16_t, 2, s)
CU_DeclareCoord (uint16_t, 4, us)
CU_DeclareCoord (uint16_t, 3, us)
CU_DeclareCoord (uint16_t, 2, us)
CU_DeclareCoord (int32_t, 4, i)
CU_DeclareCoord (int32_t, 3, i)
CU_DeclareCoord (int32_t, 2, i)
CU_DeclareCoord (uint32_t, 4, ui)
CU_DeclareCoord (uint32_t, 3, ui)
CU_DeclareCoord (uint32_t, 2, ui)
CU_DeclareCoord (float, 4, f)
CU_DeclareCoord (float, 3, f)
CU_DeclareCoord (float, 2, f)
CU_DeclareCoord (double, 4, d)
CU_DeclareCoord (double, 3, d)
CU_DeclareCoord (double, 2, d)
CU_DeclareConstCoord (bool, 4, b)
CU_DeclareConstCoord (bool, 3, b)
CU_DeclareConstCoord (bool, 2, b)
CU_DeclareConstCoord (int8_t, 4, c)
CU_DeclareConstCoord (int8_t, 3, c)
CU_DeclareConstCoord (int8_t, 2, c)
CU_DeclareConstCoord (uint8_t, 4, ub)
CU_DeclareConstCoord (uint8_t, 3, ub)
CU_DeclareConstCoord (uint8_t, 2, ub)
CU_DeclareConstCoord (int16_t, 4, s)
CU_DeclareConstCoord (int16_t, 3, s)
CU_DeclareConstCoord (int16_t, 2, s)
CU_DeclareConstCoord (uint16_t, 4, us)
CU_DeclareConstCoord (uint16_t, 3, us)
CU_DeclareConstCoord (uint16_t, 2, us)
CU_DeclareConstCoord (int32_t, 4, i)
CU_DeclareConstCoord (int32_t, 3, i)
CU_DeclareConstCoord (int32_t, 2, i)
CU_DeclareConstCoord (uint32_t, 4, ui)
CU_DeclareConstCoord (uint32_t, 3, ui)
CU_DeclareConstCoord (uint32_t, 2, ui)
CU_DeclareConstCoord (float, 4, f)
CU_DeclareConstCoord (float, 3, f)
CU_DeclareConstCoord (float, 2, f)
CU_DeclareConstCoord (double, 4, d)
CU_DeclareConstCoord (double, 3, d)
CU_DeclareConstCoord (double, 2, d)
CU_DeclareSqMtx (bool, 4, b)
CU_DeclareSqMtx (bool, 3, b)
CU_DeclareSqMtx (bool, 2, b)
CU_DeclareSqMtx (int32_t, 4, i)
CU_DeclareSqMtx (int32_t, 3, i)
CU_DeclareSqMtx (int32_t, 2, i)
CU_DeclareSqMtx (uint32_t, 4, ui)
CU_DeclareSqMtx (uint32_t, 3, ui)
CU_DeclareSqMtx (uint32_t, 2, ui)
CU_DeclareSqMtx (float, 4, f)
CU_DeclareSqMtx (float, 3, f)
CU_DeclareSqMtx (float, 2, f)
CU_DeclareSqMtx (double, 4, d)
CU_DeclareSqMtx (double, 3, d)
CU_DeclareSqMtx (double, 2, d)
CU_DeclareMtx (bool, 2, 3, b)
CU_DeclareMtx (bool, 2, 4, b)
CU_DeclareMtx (bool, 3, 2, b)
CU_DeclareMtx (bool, 3, 4, b)
CU_DeclareMtx (bool, 4, 2, b)
CU_DeclareMtx (bool, 4, 3, b)
CU_DeclareMtx (int32_t, 2, 3, i)
CU_DeclareMtx (int32_t, 2, 4, i)
CU_DeclareMtx (int32_t, 3, 2, i)
CU_DeclareMtx (int32_t, 3, 4, i)
CU_DeclareMtx (int32_t, 4, 2, i)
CU_DeclareMtx (int32_t, 4, 3, i)
CU_DeclareMtx (uint32_t, 2, 3, ui)
CU_DeclareMtx (uint32_t, 2, 4, ui)
CU_DeclareMtx (uint32_t, 3, 2, ui)
CU_DeclareMtx (uint32_t, 3, 4, ui)
CU_DeclareMtx (uint32_t, 4, 2, ui)
CU_DeclareMtx (uint32_t, 4, 3, ui)
CU_DeclareMtx (float, 2, 3, f)
CU_DeclareMtx (float, 2, 4, f)
CU_DeclareMtx (float, 3, 2, f)
CU_DeclareMtx (float, 3, 4, f)
CU_DeclareMtx (float, 4, 2, f)
CU_DeclareMtx (float, 4, 3, f)
CU_DeclareMtx (double, 2, 3, d)
CU_DeclareMtx (double, 2, 4, d)
CU_DeclareMtx (double, 3, 2, d)
CU_DeclareMtx (double, 3, 4, d)
CU_DeclareMtx (double, 4, 2, d)
CU_DeclareMtx (double, 4, 3, d)
CU_API Point3f operator* (Matrix4x4f const &lhs, Point3f const &rhs)
CU_API Point3f operator* (Point3f const &lhs, Matrix4x4f const &rhs)
CU_API Point4f operator* (Matrix4x4f const &lhs, Point4f const &rhs)
CU_API Point4f operator* (Point4f const &lhs, Matrix4x4f const &rhs)
Design
template<typename ResT , typename KeyT >
using ResourcePtrT = UniquePtr< ResourceT< ResT, KeyT > >
Pointer to a resource view.
template<typename ResT , typename KeyT >
using ResourceObsT = ResourceT< ResT, KeyT > *
Pointer to a resource view.
using Named = NamedBaseT< String >
using DynamicBitset = DynamicBitsetT< uint32_t >
template<typename ValueT >
using ChangeTracked = ChangeTrackedT< ValueT, bool >
template<typename ValueT >
using AtomicChangeTracked = ChangeTrackedT< ValueT, std::atomic_bool >
template<typename ValueT >
using GroupChangeTracked = GroupChangeTrackedT< ValueT, bool >
template<typename ValueT >
using AtomicGroupChangeTracked = GroupChangeTrackedT< ValueT, std::atomic_bool >
using OnCacheChangedFunction = castor::Function< void() >
using OnCacheChanged = SignalT< OnCacheChangedFunction >
using OnCacheChangedConnection = ConnectionT< OnCacheChanged >
template<typename ResT , typename KeyT , typename TraitsT >
using ResourceCachePtrT = UniquePtr< ResourceCacheT< ResT, KeyT, TraitsT > >
template<typename T >
static bool constexpr isChangeTrackedT = IsChangeTrackedT< T >::value
template<typename T >
static bool constexpr isGroupChangeTrackedT = IsGroupChangeTrackedT< T >::value
template<typename ResT , typename KeyT , typename ... ParametersT>
ResourcePtrT< ResT, KeyT > makeResource (ParametersT &&... params)
Parsers holders
using SectionId = uint32_t
The type for a section ID.
template<ParameterType Type, typename ParserValueHelperT = void>
using ParserParameterValueType = typename ParserParameterHelper< Type, ParserValueHelperT >::ValueType
using ParserParameterBaseSPtr = castor::SharedPtr< ParserParameterBase >
using ParserFunction = castor::Function< bool(FileParserContext &, void *, ParserParameterArray const &) >
Parser function definition.
using RawParserFunction = bool(*)(FileParserContext &, void *, ParserParameterArray const &)
template<typename BlockContextT >
using ParserFunctionT = castor::Function< bool(FileParserContext &, BlockContextT *, ParserParameterArray const &) >
Parser function definition.
template<typename BlockContextT >
using RawParserFunctionT = bool(*)(FileParserContext &, BlockContextT *, ParserParameterArray const &)
using SectionAttributeParsers = Map< SectionId, ParserFunctionAndParams >
The parsers sorted per section. This will be used to store the functions associated to a unique token.
using AttributeParsers = StringMap< SectionAttributeParsers >
The parsers sorted per token name.
using UserContextCreator = castor::Function< void * (FileParserContext &) >
User defined parsing context creator.
template<typename BlockContextT >
using BlockParserFunctionT = bool(*)(FileParserContext &, BlockContextT *, ParserParameterArray const &)
static constexpr SectionId PreviousSection = ((castor::SectionId('P') << 24) | (castor::SectionId('R') << 16) | (castor::SectionId('E') << 8) | (castor::SectionId('V') << 0))
Indicates that the next section for a parser is the previous one.
template<ParameterType Type, typename ParserValueHelperT = void>
ParameterType constexpr ParserParameterParamType = ParserParameterHelper< Type, ParserValueHelperT >::ParamType
template<ParameterType Type, typename ParserValueHelperT = void>
StringView constexpr ParserParameterStringType = ParserParameterHelper< Type, ParserValueHelperT >::StringType
template<ParameterType Type>
bool constexpr hasBaseParameterTypeV = HasBaseParameterType< Type >::value
CU_DeclareSmartPtr (castor, FileParserContext, CU_API)
CU_DeclareVector (ParserParameterBaseSPtr, ParserParameter)
CU_API void addParser (AttributeParsers &parsers, uint32_t oldSection, uint32_t newSection, String const &name, ParserFunction function, ParserParameterArray params=ParserParameterArray{})
Adds a parser function to the parsers list.
static void addParser (AttributeParsers &parsers, uint32_t section, String const &name, ParserFunction function, ParserParameterArray params=ParserParameterArray{})
Adds a parser function to the parsers list.
template<typename SectionT , typename BlockContextT >
void addParserT (AttributeParsers &parsers, SectionT section, String const &name, BlockParserFunctionT< BlockContextT > function, ParserParameterArray params=ParserParameterArray{})
template<typename SectionT , typename SectionU , typename BlockContextT >
void addParserT (AttributeParsers &parsers, SectionT oldSection, SectionU newSection, String const &name, BlockParserFunctionT< BlockContextT > function, ParserParameterArray params=ParserParameterArray{})
Miscellaneous
static const String cuEmptyString
CU_DeclareSmartPtr (castor, DynamicLibrary, CU_API)
Typedef Documentation
Angle
typedef AngleT< float > castor::Angle = AngleT< float >
Array
template<typename DataT , size_t SizeT> using castor::Array = std::array< DataT, SizeT >
AtomicChangeTracked
template<typename ValueT > using castor::AtomicChangeTracked = ChangeTrackedT< ValueT, std::atomic_bool >
AtomicGroupChangeTracked
template<typename ValueT > using castor::AtomicGroupChangeTracked = GroupChangeTrackedT< ValueT, std::atomic_bool >
AttributeParsers
using castor::AttributeParsers = StringMap< SectionAttributeParsers >
The parsers sorted per token name.
BlockParserFunctionT
template<typename BlockContextT > using castor::BlockParserFunctionT = bool(*)(FileParserContext &, BlockContextT *, ParserParameterArray const &)
BoundingContainer2D
using castor::BoundingContainer2D = BoundingContainer< 2 >
Typedef on a 2 dimensions BoundingContainer.
BoundingContainer3D
using castor::BoundingContainer3D = BoundingContainer< 3 >
Typedef on a 3 dimensions BoundingContainer.
BuddyAllocator
using castor::BuddyAllocator = BuddyAllocatorT< BuddyAllocatorTraits >
byte
using castor::byte = uint8_t
ChangeTracked
template<typename ValueT > using castor::ChangeTracked = ChangeTrackedT< ValueT, bool >
CheckedMutex
using castor::CheckedMutex = CheckedMutexT< castor::Mutex >
ContextDeleterPtr
using castor::ContextDeleterPtr = castor::RawUniquePtr< ContextDeleter >
Coords2
template<typename T > using castor::Coords2 = Coords< T, 2 >
Coords3
template<typename T > using castor::Coords3 = Coords< T, 3 >
Coords4
template<typename T > using castor::Coords4 = Coords< T, 4 >
DebugLoggerStreambufT
template<typename CharT > using castor::DebugLoggerStreambufT = LoggerStreambufT< CharT, DebugLoggerStreambufTraitsT< CharT > >
Deque
template<class DataT , class AllocT = std::allocator< DataT >> using castor::Deque = std::deque< DataT, AllocT >
DynamicBitset
using castor::DynamicBitset = DynamicBitsetT< uint32_t >
ErrorLoggerStreambufT
template<typename CharT > using castor::ErrorLoggerStreambufT = LoggerStreambufT< CharT, ErrorLoggerStreambufTraitsT< CharT > >
f32
using castor::f32 = float
f64
using castor::f64 = double
FileCreateModes
using castor::FileCreateModes = castor::FlagCombination< File :: CreateMode >
FileOpenModes
using castor::FileOpenModes = castor::FlagCombination< File :: OpenMode >
FontCache
using castor::FontCache = ResourceCacheT< Font, String, FontCacheTraits >
FontCacheTraits
using castor::FontCacheTraits = ResourceCacheTraitsT< Font, String >
FontRes
using castor::FontRes = FontCacheTraits::ElementPtrT
FontResPtr
using castor::FontResPtr = FontCacheTraits::ElementObsT
Function
template<class FuncT > using castor::Function = std::function< FuncT >
GroupChangeTracked
template<typename ValueT > using castor::GroupChangeTracked = GroupChangeTrackedT< ValueT, bool >
HdrRgbaColour
using castor::HdrRgbaColour = RgbaColourT< HdrColourComponent >
HdrRgbColour
using castor::HdrRgbColour = RgbColourT< HdrColourComponent >
ImageCache
using castor::ImageCache = ResourceCacheT< Image, String, ImageCacheTraits >
ImageCacheTraits
using castor::ImageCacheTraits = ResourceCacheTraitsT< Image, String >
ImageLoaderPtr
using castor::ImageLoaderPtr = castor::RawUniquePtr< ImageLoaderImpl >
ImageRes
using castor::ImageRes = ImageCacheTraits::ElementPtrT
ImageResPtr
using castor::ImageResPtr = ImageCacheTraits::ElementObsT
ImageWriterPtr
using castor::ImageWriterPtr = castor::RawUniquePtr< ImageWriterImpl >
InfoLoggerStreambufT
template<typename CharT > using castor::InfoLoggerStreambufT = LoggerStreambufT< CharT, InfoLoggerStreambufTraitsT< CharT > >
InputStream
using castor::InputStream = std::basic_istream< xchar >
InputStringStream
using castor::InputStringStream = std::basic_istringstream< xchar >
LargerTypeT
template<typename TypeT > using castor::LargerTypeT = typename LargerTyperT< TypeT >::Type
Length
using castor::Length = LengthT< float >
List
template<typename DataT , typename AllocT = std::allocator< DataT >> using castor::List = std::list< DataT, AllocT >
LogCallback
using castor::LogCallback = castor::Function< void(MbString const & text, LogType type, bool newLine) >
Logging callback function.
Parameters
[in] text The logged text.
[in] type The log type.
[in] newLine Tells if we add the end line character.
LoggerInstancePtr
using castor::LoggerInstancePtr = castor::RawUniquePtr< LoggerInstance >
Map
template<typename KeyT , typename DataT , typename PredT = std::less<>, typename AllocT = std::allocator< Pair< KeyT const, DataT > >> using castor::Map = std::map< KeyT, DataT, PredT, AllocT >
MatchResults
using castor::MatchResults = std::match_results< String::const_iterator >
Matrix2x2
template<typename T > using castor::Matrix2x2 = SquareMatrix< T, 2 >
Matrix3x3
template<typename T > using castor::Matrix3x3 = SquareMatrix< T, 3 >
Matrix4x4
template<typename T > using castor::Matrix4x4 = SquareMatrix< T, 4 >
mbchar
using castor::mbchar = char
MbInputStream
using castor::MbInputStream = std::basic_istream< mbchar >
MbInputStringStream
using castor::MbInputStringStream = std::basic_istringstream< mbchar >
MbOutputStream
using castor::MbOutputStream = std::basic_ostream< mbchar >
MbOutputStringStream
using castor::MbOutputStringStream = std::basic_ostringstream< mbchar >
MbString
using castor::MbString = std::basic_string< mbchar >
MbStringStream
using castor::MbStringStream = std::basic_stringstream< mbchar >
MbStringView
using castor::MbStringView = std::basic_string_view< mbchar >
MessageQueue
using castor::MessageQueue = Deque< Message >
The message queue.
Microseconds
using castor::Microseconds = std::chrono::microseconds
Milliseconds
using castor::Milliseconds = std::chrono::milliseconds
MultiMap
template<typename KeyT , typename DataT , typename PredT = std::less<>, typename AllocT = std::allocator< Pair< KeyT const, DataT > >> using castor::MultiMap = std::multimap< KeyT, DataT, PredT, AllocT >
MultiSet
template<typename KeyT , typename DataT , typename PredT = std::less<>, typename AllocT = std::allocator< KeyT >> using castor::MultiSet = std::multiset< KeyT, PredT, AllocT >
Mutex
using castor::Mutex = std::mutex
Named
using castor::Named = NamedBaseT< String >
Nanoseconds
using castor::Nanoseconds = std::chrono::nanoseconds
OnCacheChanged
using castor::OnCacheChanged = SignalT< OnCacheChangedFunction >
OnCacheChangedConnection
using castor::OnCacheChangedConnection = ConnectionT< OnCacheChanged >
OnCacheChangedFunction
using castor::OnCacheChangedFunction = castor::Function< void() >
OutputStream
using castor::OutputStream = std::basic_ostream< xchar >
OutputStringStream
using castor::OutputStringStream = std::basic_ostringstream< xchar >
Pair
template<typename FirstT , typename SecondT > using castor::Pair = std::pair< FirstT, SecondT >
ParserFunction
using castor::ParserFunction = castor::Function< bool(FileParserContext &, void *, ParserParameterArray const &) >
Parser function definition.
Parameters
[in] parser The file parser.
[in] block The block context, if any.
[in] params The params contained in the line.
Returns
true if a brace is to be opened on next line.
ParserFunctionT
template<typename BlockContextT > using castor::ParserFunctionT = castor::Function< bool(FileParserContext &, BlockContextT *, ParserParameterArray const &) >
Parser function definition.
Parameters
[in] parser The file parser.
[in] block The block context, if any.
[in] params The params contained in the line.
Returns
true if a brace is to be opened on next line.
ParserParameterBaseSPtr
using castor::ParserParameterBaseSPtr = castor::SharedPtr< ParserParameterBase >
ParserParameterValueType
template<ParameterType Type, typename ParserValueHelperT = void> using castor::ParserParameterValueType = typename ParserParameterHelper< Type, ParserValueHelperT >::ValueType
PixelBuffer
using castor::PixelBuffer = PxBuffer< PixelFormat::eR8G8B8A8_UNORM >
PixelComponents
using castor::PixelComponents = castor::FlagCombination< PixelComponent >
Point2
template<typename T > using castor::Point2 = Point< T, 2 >
Point3
template<typename T > using castor::Point3 = Point< T, 3 >
Point4
template<typename T > using castor::Point4 = Point< T, 4 >
PointComponentT
template<typename TypeT > using castor::PointComponentT = typename PointComponentGetT< TypeT >::Type
PointTypeT
template<typename SrcT , typename DstCompT > using castor::PointTypeT = typename PointTyperT< SrcT, DstCompT >::Type
Quaternion
using castor::Quaternion = QuaternionT< float >
QuaternionArray
using castor::QuaternionArray = Vector< Quaternion >
QuaternionDataT
template<typename T > using castor::QuaternionDataT = PointData< T, 4u >
RawParserFunction
using castor::RawParserFunction = bool(*)(FileParserContext &, void *, ParserParameterArray const &)
RawParserFunctionT
template<typename BlockContextT > using castor::RawParserFunctionT = bool(*)(FileParserContext &, BlockContextT *, ParserParameterArray const &)
RawUniquePtr
template<typename TypeT , class DelT = std::default_delete< TypeT >> using castor::RawUniquePtr = std::unique_ptr< TypeT, DelT >
RecursiveMutex
using castor::RecursiveMutex = std::recursive_mutex
ReferenceWrapper
template<class DataT > using castor::ReferenceWrapper = std::reference_wrapper< DataT >
Regex
using castor::Regex = std::basic_regex< xchar >
RegexIterator
using castor::RegexIterator = std::regex_iterator< String::const_iterator >
ResourceCachePtrT
template<typename ResT , typename KeyT , typename TraitsT > using castor::ResourceCachePtrT = UniquePtr< ResourceCacheT< ResT, KeyT, TraitsT > >
ResourceObsT
template<typename ResT , typename KeyT > using castor::ResourceObsT = ResourceT< ResT, KeyT > *
Pointer to a resource view.
ResourcePtrT
template<typename ResT , typename KeyT > using castor::ResourcePtrT = UniquePtr< ResourceT< ResT, KeyT > >
Pointer to a resource view.
RgbaColour
using castor::RgbaColour = RgbaColourT< ColourComponent >
RgbColour
using castor::RgbColour = RgbColourT< ColourComponent >
s16
using castor::s16 = int16_t
s32
using castor::s32 = int32_t
s64
using castor::s64 = int64_t
s8
using castor::s8 = int8_t
Seconds
using castor::Seconds = std::chrono::seconds
SectionAttributeParsers
using castor::SectionAttributeParsers = Map< SectionId, ParserFunctionAndParams >
The parsers sorted per section. This will be used to store the functions associated to a unique token.
SectionId
using castor::SectionId = uint32_t
The type for a section ID.
Set
template<typename KeyT , typename PredT = std::less<>, typename AllocT = std::allocator< KeyT >> using castor::Set = std::set< KeyT, PredT, AllocT >
SharedPtr
template<class DataT > using castor::SharedPtr = std::shared_ptr< DataT >
Stack
template<typename DataT , class ContainerT = Deque< DataT >> using castor::Stack = std::stack< DataT, ContainerT >
String
using castor::String = std::basic_string< xchar >
StringMap
template<typename DataT > using castor::StringMap = Map< String, DataT >
StringSet
using castor::StringSet = std::set< String, StringHash, std::equal_to<> >
StringStream
using castor::StringStream = std::basic_stringstream< xchar >
StringView
using castor::StringView = std::basic_string_view< xchar >
TraceLoggerStreambufT
template<typename CharT > using castor::TraceLoggerStreambufT = LoggerStreambufT< CharT, TraceLoggerStreambufTraitsT< CharT > >
u16
using castor::u16 = uint16_t
u32
using castor::u32 = uint32_t
u32char
using castor::u32char = char32_t
U32InputStream
using castor::U32InputStream = std::basic_istream< u32char >
U32InputStringStream
using castor::U32InputStringStream = std::basic_istringstream< u32char >
U32OutputStream
using castor::U32OutputStream = std::basic_ostream< u32char >
U32OutputStringStream
using castor::U32OutputStringStream = std::basic_ostringstream< u32char >
U32String
using castor::U32String = std::basic_string< u32char >
U32StringStream
using castor::U32StringStream = std::basic_stringstream< u32char >
U32StringView
using castor::U32StringView = std::basic_string_view< u32char >
u64
using castor::u64 = uint64_t
u8
using castor::u8 = uint8_t
UbPixel
using castor::UbPixel = Pixel< PixelFormat::eR8G8B8A8_UNORM >
Typedef over a pixel in A8R8G8B8 format.
Author
Sylvain DOREMUS
UniqueLock
template<typename Lockable > using castor::UniqueLock = std::unique_lock< Lockable >
UniquePtr
template<typename TypeT > using castor::UniquePtr = RawUniquePtr< TypeT, Deleter< TypeT > >
UnorderedMap
template<typename KeyT , typename DataT , typename HashT = std::hash< KeyT >, typename KeyEqT = std::equal_to<>, typename AllocT = std::allocator< Pair< KeyT const, DataT > >> using castor::UnorderedMap = std::unordered_map< KeyT, DataT, HashT, KeyEqT, AllocT >
UnorderedSet
template<typename KeyT , typename HashT = std::hash< KeyT >, typename KeyEqT = std::equal_to<>, typename AllocT = std::allocator< KeyT >> using castor::UnorderedSet = std::unordered_set< KeyT, HashT, KeyEqT >
UnorderedStringMap
template<typename DataT > using castor::UnorderedStringMap = std::unordered_map< String, DataT, StringHash, std::equal_to<> >
UnorderedStringSet
using castor::UnorderedStringSet = std::unordered_set< String, StringHash, std::equal_to<> >
UnRangedValueT
template<typename T > using castor::UnRangedValueT = typename RangedValueGetterT< T >::Type
UserContextCreator
using castor::UserContextCreator = castor::Function< void * (FileParserContext &) >
User defined parsing context creator.
usize
using castor::usize = size_t
Vector
template<typename DataT , typename AllocT = std::allocator< DataT >> using castor::Vector = std::vector< DataT, AllocT >
Vector2d
using castor::Vector2d = LengthT< Point2d >
Vector2f
using castor::Vector2f = LengthT< Point2f >
Vector3d
using castor::Vector3d = LengthT< Point3d >
Vector3f
using castor::Vector3f = LengthT< Point3f >
Vector4d
using castor::Vector4d = LengthT< Point4d >
Vector4f
using castor::Vector4f = LengthT< Point4f >
VoidFnType
using castor::VoidFnType = void(CU_stdcall *)()
WarningLoggerStreambufT
template<typename CharT > using castor::WarningLoggerStreambufT = LoggerStreambufT< CharT, WarningLoggerStreambufTraitsT< CharT > >
wchar
using castor::wchar = wchar_t
WInputStream
using castor::WInputStream = std::basic_istream< wchar >
WInputStringStream
using castor::WInputStringStream = std::basic_istringstream< wchar >
WOutputStream
using castor::WOutputStream = std::basic_ostream< wchar >
WOutputStringStream
using castor::WOutputStringStream = std::basic_ostringstream< wchar >
WString
using castor::WString = std::basic_string< wchar >
WStringStream
using castor::WStringStream = std::basic_stringstream< wchar >
WStringView
using castor::WStringView = std::basic_string_view< wchar >
xchar
using castor::xchar = char
Enumeration Type Documentation
FileType
enum class castor::FileType : uint8_t strong
castor::Loader supported file types enumeration
Enumerator
eBinary
Binary file.
eText
Text file.
eCount
eMin
Intersection
enum class castor::Intersection : uint8_t strong
Intersection types.
Remarks
Enumerates the different intersection types.
Enumerator
eIn
Completely inside.
eOut
Completely outside.
eIntersect
Intersection.
eCount
eMin
LengthUnit
enum class castor::LengthUnit strong
Enumerator
eKilometre
eMetre
eCentimetre
eMillimetre
eYard
eFoot
eInch
eCount
eMin
LogType
enum class castor::LogType : uint8_t strong
Defines the various log types.
Enumerator
eTrace
Trace type log.
eDebug
Debug type log.
eInfo
Information type log.
eWarning
Warning type log.
eError
Error type log.
eCount
Log types count.
ParameterType
enum class castor::ParameterType : uint8_t strong
Parser function parameter types enumeration.
Enumerator
eText
eName
ePath
eCheckedText
eBitwiseOred32BitsCheckedText
eBitwiseOred64BitsCheckedText
eBool
eInt8
eInt16
eInt32
eInt64
eUInt8
eUInt16
eUInt32
eUInt64
eFloat
eDouble
eLongDouble
ePixelFormat
ePoint2I
ePoint3I
ePoint4I
ePoint2U
ePoint3U
ePoint4U
ePoint2F
ePoint3F
ePoint4F
ePoint2D
ePoint3D
ePoint4D
eSize
ePosition
eRectangle
eRgbColour
eRgbaColour
eHdrRgbColour
eHdrRgbaColour
eCount
eMin
PixelComponent
enum class castor::PixelComponent : uint8_t strong
Pixel PixelComponentsT enumeration.
Enumerator
eRed
Red.
eGreen
Green.
eBlue
Blue.
eAlpha
Alpha.
eDepth
Depth.
eStencil
Stencil.
PixelFormat
enum class castor::PixelFormat : uint32_t strong
Pixel format enumeration.
Enumerator
CUPF_ENUM_VALUE
eCount
eMin
PredefinedRgbaColour
enum class castor::PredefinedRgbaColour : uint32_t strong
Predefined colours enumeration.
Enumerator
eTransparentBlack
eLowAlphaBlack
eMedAlphaBlack
eHighAlphaBlack
eOpaqueBlack
eTransparentDarkBlue
eLowAlphaDarkBlue
eMedAlphaDarkBlue
eHighAlphaDarkBlue
eOpaqueDarkBlue
eTransparentBlue
eLowAlphaBlue
eMedAlphaBlue
eHighAlphaBlue
eOpaqueBlue
eTransparentDarkGreen
eLowAlphaDarkGreen
eMedAlphaDarkGreen
eHighAlphaDarkGreen
eOpaqueDarkGreen
eTransparentGreen
eLowAlphaGreen
eMedAlphaGreen
eHighAlphaGreen
eOpaqueGreen
eTransparentDarkRed
eLowAlphaDarkRed
eMedAlphaDarkRed
eHighAlphaDarkRed
eOpaqueDarkRed
eTransparentRed
eLowAlphaRed
eMedAlphaRed
eHighAlphaRed
eOpaqueRed
eTransparentLightBlue
eLowAlphaLightBlue
eMedAlphaLightBlue
eHighAlphaLightBlue
eOpaqueLightBlue
eTransparentLightGreen
eLowAlphaLightGreen
eMedAlphaLightGreen
eHighAlphaLightGreen
eOpaqueLightGreen
eTransparentLightRed
eLowAlphaLightRed
eMedAlphaLightRed
eHighAlphaLightRed
eOpaqueLightRed
eTransparentWhite
eLowAlphaWhite
eMedAlphaWhite
eHighAlphaWhite
eOpaqueWhite
PredefinedRgbColour
enum class castor::PredefinedRgbColour : uint32_t strong
Predefined colours enumeration.
Enumerator
eBlack
eDarkBlue
eBlue
eDarkGreen
eGreen
eDarkRed
eRed
eLightBlue
eLightGreen
eLightRed
eWhite
RgbaComponent
enum class castor::RgbaComponent : uint8_t strong
RgbaColourT components enumeration.
Enumerator
eRed
Red component
eGreen
Green component
eBlue
Blue component
eAlpha
Alpha component
eCount
eMin
RgbComponent
enum class castor::RgbComponent : uint8_t strong
RgbColourT components enumeration.
Enumerator
eRed
Red component
eGreen
Green component
eBlue
Blue component
eCount
eMin
UnicityError
enum class castor::UnicityError strong
Unicity errors enumeration.
Enumerator
eNoInstance
eAnInstance
eCount
eMin
Function Documentation
acosd()
static AngleT< double > castor::acosd (double value) inline static
Computes this angle's value from the given cosine value.
Parameters
[in] value The cosine value
acosf()
static AngleT< float > castor::acosf (double value) inline static
Computes this angle's value from the given cosine value.
Parameters
[in] value The cosine value
acosT()
template<typename Type > static AngleT< Type > castor::acosT (double value) inline static
Computes this angle's value from the given cosine value.
Parameters
[in] value The cosine value
addFlag() [1/2]
template<typename FlagType > constexpr FlagCombination< FlagType > & castor::addFlag (FlagCombination< FlagType > & value, FlagType const & flag) constexpr noexcept
adds a flag to the given value.
Parameters
[in,out] value The value.
[in] flag The flag to add.
Returns
The value.
addFlag() [2/2]
template<typename FlagType > constexpr FlagCombination< FlagType > castor::addFlag (FlagCombination< FlagType > const & value, FlagType const & flag) constexpr noexcept
adds a flag to the given value.
Parameters
[in] value The value.
[in] flag The flag to add.
Returns
The new value.
addFlags()
template<typename FlagType > constexpr FlagCombination< FlagType > & castor::addFlags (FlagCombination< FlagType > & value, FlagCombination< FlagType > const & flags) constexpr noexcept
adds a flag combination to the given value.
Parameters
[in,out] value The value.
[in] flags The flag combination to add.
Returns
The value.
addParser() [1/2]
CU_API void castor::addParser (AttributeParsers & parsers, uint32_t oldSection, uint32_t newSection, String const & name, ParserFunction function, ParserParameterArray params = ParserParameterArray{})
Adds a parser function to the parsers list.
Parameters
[in,out] parsers Receives the added parser.
[in] oldSection The parser section onto which the function is applied.
[in] newSection The parser section resulting of the application oof the function.
[in] name The parser name.
[in] function The parser function.
[in] params The expected parameters.
Referenced by castor3d::CU_DeclareAttributeParser().
addParser() [2/2]
static void castor::addParser (AttributeParsers & parsers, uint32_t section, String const & name, ParserFunction function, ParserParameterArray params = ParserParameterArray{}) static
Adds a parser function to the parsers list.
Parameters
[in,out] parsers Receives the added parser.
[in] section The parser section.
[in] name The parser name.
[in] function The parser function.
[in] params The expected parameters.
addParserT() [1/2]
template<typename SectionT , typename SectionU , typename BlockContextT > void castor::addParserT (AttributeParsers & parsers, SectionT oldSection, SectionU newSection, String const & name, BlockParserFunctionT< BlockContextT > function, ParserParameterArray params = ParserParameterArray{}) inline
addParserT() [2/2]
template<typename SectionT , typename BlockContextT > void castor::addParserT (AttributeParsers & parsers, SectionT section, String const & name, BlockParserFunctionT< BlockContextT > function, ParserParameterArray params = ParserParameterArray{}) inline
alignedAlloc() [1/2]
CU_API void * castor::alignedAlloc (size_t alignment, size_t size)
Allocates aligned memory.
Parameters
[in] alignment The alignment value, must be a power of two.
[in] size The wanted size.
Returns
The allocated memory, nullptr on error.
Referenced by alignedAlloc(), and castor::AlignedMemoryAllocator< Align >::allocate().
alignedAlloc() [2/2]
template<typename T > T * castor::alignedAlloc (size_t alignment, size_t size)
Allocates aligned memory.
Parameters
[in] alignment The alignment value, must be a power of two.
[in] size The wanted size.
Returns
The allocated memory, nullptr on error.
References alignedAlloc().
alignedFree()
CU_API void castor::alignedFree (void * memory)
Deallocates aligned memory.
Parameters
[in] memory The memory.
Referenced by castor::AlignedMemoryAllocator< Align >::deallocate().
asind()
static AngleT< double > castor::asind (double value) inline static
Computes this angle's value from the given sine value.
Parameters
[in] value The sine value
asinf()
static AngleT< float > castor::asinf (double value) inline static
Computes this angle's value from the given sine value.
Parameters
[in] value The sine value
asinT()
template<typename Type > static AngleT< Type > castor::asinT (double value) inline static
Computes this angle's value from the given sine value.
Parameters
[in] value The sine value
atand()
static AngleT< double > castor::atand (double value) inline static
Computes this angle's value from the given tangent value.
Parameters
[in] value The tangent value
atanf()
static AngleT< float > castor::atanf (double value) inline static
Computes this angle's value from the given tangent value.
Parameters
[in] value The tangent value
atanT()
template<typename Type > static AngleT< Type > castor::atanT (double value) inline static
Computes this angle's value from the given tangent value.
Parameters
[in] value The tangent value
bigEndianToSystemEndian() [1/6]
template<typename T , size_t N> constexpr Array< T, N > & castor::bigEndianToSystemEndian (Array< T, N > & value) constexpr noexcept
Convert the given value to big endian if needed.
Parameters
[in,out] value Value to be converted.
References isBigEndian(), and switchEndianness().
bigEndianToSystemEndian() [2/6]
template<typename T , size_t N> constexpr Array< T, N > castor::bigEndianToSystemEndian (Array< T, N > const & value) constexpr
Convert the given value to big endian if needed.
Parameters
[in,out] value Value to be converted.
References isBigEndian(), and switchEndianness().
bigEndianToSystemEndian() [3/6]
template<typename T > constexpr T & castor::bigEndianToSystemEndian (T & value) constexpr noexcept
Convert the given big endian value to system endian if needed.
Parameters
[in,out] value Value to be converted.
References isBigEndian(), and switchEndianness().
bigEndianToSystemEndian() [4/6]
template<typename T > constexpr T castor::bigEndianToSystemEndian (T const & value) constexpr
Convert the given big endian value to system endian if needed.
Parameters
[in,out] value Value to be converted.
References isBigEndian(), and switchEndianness().
bigEndianToSystemEndian() [5/6]
template<typename T > Vector< T > & castor::bigEndianToSystemEndian (Vector< T > & value) inline noexcept
Convert the given value to big endian if needed.
Parameters
[in,out] value Value to be converted.
References isBigEndian(), and switchEndianness().
bigEndianToSystemEndian() [6/6]
template<typename T > Vector< T > castor::bigEndianToSystemEndian (Vector< T > const & value) inline
Convert the given value to big endian if needed.
Parameters
[in,out] value Value to be converted.
References isBigEndian(), and switchEndianness().
checkFlag() [1/3]
template<typename FlagType > constexpr bool castor::checkFlag (FlagCombination< FlagType > const & value, FlagType const & flag) constexpr noexcept
Parameters
[in] value The value.
[in] flag The flag looked for.
Returns
true if flags contain flag.
checkFlag() [2/3]
template<typename FlagType , typename Type > constexpr bool castor::checkFlag (FlagCombination< FlagType > const & value, Type const & flag) constexpr noexcept
Parameters
[in] value The value.
[in] flag The flag looked for.
Returns
true if flags contain flag.
checkFlag() [3/3]
template<typename T , typename U > constexpr bool castor::checkFlag (T const & value, U const & flag) constexpr noexcept
Parameters
[in] value The value.
[in] flag The flag looked for.
Returns
true if flags contain flag.
Referenced by castor3d::ProgressCtrl::hasTitle(), castor3d::Control::isAlwaysOnTop(), castor3d::ProgressCtrl::isBottomToTop(), castor3d::ScrollBarCtrl::isHorizontal(), castor3d::ProgressCtrl::isLeftToRight(), castor3d::Control::isMovable(), castor3d::EditCtrl::isMultiLine(), castor3d::Control::isResizable(), castor3d::ProgressCtrl::isRightToLeft(), castor3d::ProgressCtrl::isTopToBottom(), and castor3d::ScrollBarCtrl::isVertical().
compressBuffer()
CU_API void castor::compressBuffer (PxBufferConvertOptions const * options, std::atomic_bool const * interrupt, Size const & srcDimensions, Size const & dstDimensions, PixelFormat srcFormat, uint8_t const * srcBuffer, uint32_t srcSize, PixelFormat dstFormat, uint8_t * dstBuffer, uint32_t dstSize)
Function to perform convertion without templates.
Parameters
[in] options The convertion options.
[in] interrupt Tells if the convertion is to be interrupted.
[in] srcDimensions The source dimensions.
[in] dstDimensions The destination dimensions (used only when block compressing).
[in] srcFormat The source format.
[in] srcBuffer The source buffer.
[in] srcSize The source size.
[in] dstFormat The destination format.
[in] dstBuffer The destination buffer.
[in] dstSize The destination size.
convert()
template<typename TypeT > static TypeT castor::convert (TypeT const & value, LengthUnit from, LengthUnit to) inline static
convertBuffer() [1/2]
static void castor::convertBuffer (Size const & dimensions, PixelFormat srcFormat, uint8_t const * srcBuffer, uint32_t srcSize, PixelFormat dstFormat, uint8_t * dstBuffer, uint32_t dstSize) inline static
Function to perform convertion without templates.
Parameters
[in] dimensions The source dimensions.
[in] srcFormat The source format.
[in] srcBuffer The source buffer.
[in] srcSize The source size.
[in] dstFormat The destination format.
[in] dstBuffer The destination buffer.
[in] dstSize The destination size.
References convertBuffer().
convertBuffer() [2/2]
CU_API void castor::convertBuffer (Size const & srcDimensions, Size const & dstDimensions, PixelFormat srcFormat, uint8_t const * srcBuffer, uint32_t srcSize, PixelFormat dstFormat, uint8_t * dstBuffer, uint32_t dstSize)
Function to perform convertion without templates.
Parameters
[in] srcDimensions The source dimensions.
[in] dstDimensions The destination dimensions (used only when block compressing).
[in] srcFormat The source format.
[in] srcBuffer The source buffer.
[in] srcSize The source size.
[in] dstFormat The destination format.
[in] dstBuffer The destination buffer.
[in] dstSize The destination size.
Referenced by convertBuffer().
convertPixel()
CU_API void castor::convertPixel (PixelFormat srcFormat, uint8_t const *& src, PixelFormat dstFormat, uint8_t *& dst)
Function to perform convertion without templates.
Parameters
[in] srcFormat The source format
[in,out] src The source pixel
[in] dstFormat The destination format
[in,out] dst The destination pixel
Referenced by castor::Image::setPixel().
convertToNormalMap()
CU_API bool castor::convertToNormalMap (float strength, Image & image) noexcept
copyBufferComponents()
CU_API void castor::copyBufferComponents (PixelComponents srcComponents, PixelComponents dstComponents, PxBufferBase const & srcBuffer, PxBufferBase & dstBuffer)
Copies some pixel components from a source buffer into pixel components of a destination buffer.
Parameters
[in] srcComponents The components to read from the source buffer.
[in] dstComponents The components to write into the destination buffer.
[in] srcBuffer The source buffer.
[in,out] dstBuffer The destination buffer.
CU_Alignas() [1/2]
template<int A> class castor::CU_Alignas (A)
CU_Alignas() [2/2]
template<typename T > class castor::CU_Alignas (alignof(T))
CU_DeclareArrayView() [1/6]
castor::CU_DeclareArrayView (byte const , ConstByte)
CU_DeclareArrayView() [2/6]
castor::CU_DeclareArrayView (byte , Byte)
CU_DeclareArrayView() [3/6]
castor::CU_DeclareArrayView (s32 const , ConstInt32)
CU_DeclareArrayView() [4/6]
castor::CU_DeclareArrayView (s32 , Int32)
CU_DeclareArrayView() [5/6]
castor::CU_DeclareArrayView (u32 const , ConstUInt32)
CU_DeclareArrayView() [6/6]
castor::CU_DeclareArrayView (u32 , UInt32)
CU_DeclareConstCoord() [1/27]
castor::CU_DeclareConstCoord (bool , 2 , b)
CU_DeclareConstCoord() [2/27]
castor::CU_DeclareConstCoord (bool , 3 , b)
CU_DeclareConstCoord() [3/27]
castor::CU_DeclareConstCoord (bool , 4 , b)
CU_DeclareConstCoord() [4/27]
castor::CU_DeclareConstCoord (double , 2 , d)
CU_DeclareConstCoord() [5/27]
castor::CU_DeclareConstCoord (double , 3 , d)
CU_DeclareConstCoord() [6/27]
castor::CU_DeclareConstCoord (double , 4 , d)
CU_DeclareConstCoord() [7/27]
castor::CU_DeclareConstCoord (float , 2 , f)
CU_DeclareConstCoord() [8/27]
castor::CU_DeclareConstCoord (float , 3 , f)
CU_DeclareConstCoord() [9/27]
castor::CU_DeclareConstCoord (float , 4 , f)
CU_DeclareConstCoord() [10/27]
castor::CU_DeclareConstCoord (int16_t , 2 , s)
CU_DeclareConstCoord() [11/27]
castor::CU_DeclareConstCoord (int16_t , 3 , s)
CU_DeclareConstCoord() [12/27]
castor::CU_DeclareConstCoord (int16_t , 4 , s)
CU_DeclareConstCoord() [13/27]
castor::CU_DeclareConstCoord (int32_t , 2 , i)
CU_DeclareConstCoord() [14/27]
castor::CU_DeclareConstCoord (int32_t , 3 , i)
CU_DeclareConstCoord() [15/27]
castor::CU_DeclareConstCoord (int32_t , 4 , i)
CU_DeclareConstCoord() [16/27]
castor::CU_DeclareConstCoord (int8_t , 2 , c)
CU_DeclareConstCoord() [17/27]
castor::CU_DeclareConstCoord (int8_t , 3 , c)
CU_DeclareConstCoord() [18/27]
castor::CU_DeclareConstCoord (int8_t , 4 , c)
CU_DeclareConstCoord() [19/27]
castor::CU_DeclareConstCoord (uint16_t , 2 , us)
CU_DeclareConstCoord() [20/27]
castor::CU_DeclareConstCoord (uint16_t , 3 , us)
CU_DeclareConstCoord() [21/27]
castor::CU_DeclareConstCoord (uint16_t , 4 , us)
CU_DeclareConstCoord() [22/27]
castor::CU_DeclareConstCoord (uint32_t , 2 , ui)
CU_DeclareConstCoord() [23/27]
castor::CU_DeclareConstCoord (uint32_t , 3 , ui)
CU_DeclareConstCoord() [24/27]
castor::CU_DeclareConstCoord (uint32_t , 4 , ui)
CU_DeclareConstCoord() [25/27]
castor::CU_DeclareConstCoord (uint8_t , 2 , ub)
CU_DeclareConstCoord() [26/27]
castor::CU_DeclareConstCoord (uint8_t , 3 , ub)
CU_DeclareConstCoord() [27/27]
castor::CU_DeclareConstCoord (uint8_t , 4 , ub)
CU_DeclareCoord() [1/27]
castor::CU_DeclareCoord (bool , 2 , b)
CU_DeclareCoord() [2/27]
castor::CU_DeclareCoord (bool , 3 , b)
CU_DeclareCoord() [3/27]
castor::CU_DeclareCoord (bool , 4 , b)
CU_DeclareCoord() [4/27]
castor::CU_DeclareCoord (double , 2 , d)
CU_DeclareCoord() [5/27]
castor::CU_DeclareCoord (double , 3 , d)
CU_DeclareCoord() [6/27]
castor::CU_DeclareCoord (double , 4 , d)
CU_DeclareCoord() [7/27]
castor::CU_DeclareCoord (float , 2 , f)
CU_DeclareCoord() [8/27]
castor::CU_DeclareCoord (float , 3 , f)
CU_DeclareCoord() [9/27]
castor::CU_DeclareCoord (float , 4 , f)
CU_DeclareCoord() [10/27]
castor::CU_DeclareCoord (int16_t , 2 , s)
CU_DeclareCoord() [11/27]
castor::CU_DeclareCoord (int16_t , 3 , s)
CU_DeclareCoord() [12/27]
castor::CU_DeclareCoord (int16_t , 4 , s)
CU_DeclareCoord() [13/27]
castor::CU_DeclareCoord (int32_t , 2 , i)
CU_DeclareCoord() [14/27]
castor::CU_DeclareCoord (int32_t , 3 , i)
CU_DeclareCoord() [15/27]
castor::CU_DeclareCoord (int32_t , 4 , i)
CU_DeclareCoord() [16/27]
castor::CU_DeclareCoord (int8_t , 2 , c)
CU_DeclareCoord() [17/27]
castor::CU_DeclareCoord (int8_t , 3 , c)
CU_DeclareCoord() [18/27]
castor::CU_DeclareCoord (int8_t , 4 , c)
CU_DeclareCoord() [19/27]
castor::CU_DeclareCoord (uint16_t , 2 , us)
CU_DeclareCoord() [20/27]
castor::CU_DeclareCoord (uint16_t , 3 , us)
CU_DeclareCoord() [21/27]
castor::CU_DeclareCoord (uint16_t , 4 , us)
CU_DeclareCoord() [22/27]
castor::CU_DeclareCoord (uint32_t , 2 , ui)
CU_DeclareCoord() [23/27]
castor::CU_DeclareCoord (uint32_t , 3 , ui)
CU_DeclareCoord() [24/27]
castor::CU_DeclareCoord (uint32_t , 4 , ui)
CU_DeclareCoord() [25/27]
castor::CU_DeclareCoord (uint8_t , 2 , ub)
CU_DeclareCoord() [26/27]
castor::CU_DeclareCoord (uint8_t , 3 , ub)
CU_DeclareCoord() [27/27]
castor::CU_DeclareCoord (uint8_t , 4 , ub)
CU_DeclareMap() [1/5]
castor::CU_DeclareMap (String , bool , BoolStr)
CU_DeclareMap() [2/5]
castor::CU_DeclareMap (String , String , StrStr)
CU_DeclareMap() [3/5]
castor::CU_DeclareMap (String , uint32_t , UInt32Str)
CU_DeclareMap() [4/5]
castor::CU_DeclareMap (String , uint64_t , UInt64Str)
CU_DeclareMap() [5/5]
castor::CU_DeclareMap (uint32_t , String , StrUInt32)
CU_DeclareMtx() [1/30]
castor::CU_DeclareMtx (bool , 2 , 3 , b)
CU_DeclareMtx() [2/30]
castor::CU_DeclareMtx (bool , 2 , 4 , b)
CU_DeclareMtx() [3/30]
castor::CU_DeclareMtx (bool , 3 , 2 , b)
CU_DeclareMtx() [4/30]
castor::CU_DeclareMtx (bool , 3 , 4 , b)
CU_DeclareMtx() [5/30]
castor::CU_DeclareMtx (bool , 4 , 2 , b)
CU_DeclareMtx() [6/30]
castor::CU_DeclareMtx (bool , 4 , 3 , b)
CU_DeclareMtx() [7/30]
castor::CU_DeclareMtx (double , 2 , 3 , d)
CU_DeclareMtx() [8/30]
castor::CU_DeclareMtx (double , 2 , 4 , d)
CU_DeclareMtx() [9/30]
castor::CU_DeclareMtx (double , 3 , 2 , d)
CU_DeclareMtx() [10/30]
castor::CU_DeclareMtx (double , 3 , 4 , d)
CU_DeclareMtx() [11/30]
castor::CU_DeclareMtx (double , 4 , 2 , d)
CU_DeclareMtx() [12/30]
castor::CU_DeclareMtx (double , 4 , 3 , d)
CU_DeclareMtx() [13/30]
castor::CU_DeclareMtx (float , 2 , 3 , f)
CU_DeclareMtx() [14/30]
castor::CU_DeclareMtx (float , 2 , 4 , f)
CU_DeclareMtx() [15/30]
castor::CU_DeclareMtx (float , 3 , 2 , f)
CU_DeclareMtx() [16/30]
castor::CU_DeclareMtx (float , 3 , 4 , f)
CU_DeclareMtx() [17/30]
castor::CU_DeclareMtx (float , 4 , 2 , f)
CU_DeclareMtx() [18/30]
castor::CU_DeclareMtx (float , 4 , 3 , f)
CU_DeclareMtx() [19/30]
castor::CU_DeclareMtx (int32_t , 2 , 3 , i)
CU_DeclareMtx() [20/30]
castor::CU_DeclareMtx (int32_t , 2 , 4 , i)
CU_DeclareMtx() [21/30]
castor::CU_DeclareMtx (int32_t , 3 , 2 , i)
CU_DeclareMtx() [22/30]
castor::CU_DeclareMtx (int32_t , 3 , 4 , i)
CU_DeclareMtx() [23/30]
castor::CU_DeclareMtx (int32_t , 4 , 2 , i)
CU_DeclareMtx() [24/30]
castor::CU_DeclareMtx (int32_t , 4 , 3 , i)
CU_DeclareMtx() [25/30]
castor::CU_DeclareMtx (uint32_t , 2 , 3 , ui)
CU_DeclareMtx() [26/30]
castor::CU_DeclareMtx (uint32_t , 2 , 4 , ui)
CU_DeclareMtx() [27/30]
castor::CU_DeclareMtx (uint32_t , 3 , 2 , ui)
CU_DeclareMtx() [28/30]
castor::CU_DeclareMtx (uint32_t , 3 , 4 , ui)
CU_DeclareMtx() [29/30]
castor::CU_DeclareMtx (uint32_t , 4 , 2 , ui)
CU_DeclareMtx() [30/30]
castor::CU_DeclareMtx (uint32_t , 4 , 3 , ui)
CU_DeclarePoint() [1/27]
castor::CU_DeclarePoint (bool , 2 , b)
CU_DeclarePoint() [2/27]
castor::CU_DeclarePoint (bool , 3 , b)
CU_DeclarePoint() [3/27]
castor::CU_DeclarePoint (bool , 4 , b)
CU_DeclarePoint() [4/27]
castor::CU_DeclarePoint (double , 2 , d)
CU_DeclarePoint() [5/27]
castor::CU_DeclarePoint (double , 3 , d)
CU_DeclarePoint() [6/27]
castor::CU_DeclarePoint (double , 4 , d)
CU_DeclarePoint() [7/27]
castor::CU_DeclarePoint (float , 2 , f)
CU_DeclarePoint() [8/27]
castor::CU_DeclarePoint (float , 3 , f)
CU_DeclarePoint() [9/27]
castor::CU_DeclarePoint (float , 4 , f)
CU_DeclarePoint() [10/27]
castor::CU_DeclarePoint (int16_t , 2 , s)
CU_DeclarePoint() [11/27]
castor::CU_DeclarePoint (int16_t , 3 , s)
CU_DeclarePoint() [12/27]
castor::CU_DeclarePoint (int16_t , 4 , s)
CU_DeclarePoint() [13/27]
castor::CU_DeclarePoint (int32_t , 2 , i)
CU_DeclarePoint() [14/27]
castor::CU_DeclarePoint (int32_t , 3 , i)
CU_DeclarePoint() [15/27]
castor::CU_DeclarePoint (int32_t , 4 , i)
CU_DeclarePoint() [16/27]
castor::CU_DeclarePoint (int8_t , 2 , c)
CU_DeclarePoint() [17/27]
castor::CU_DeclarePoint (int8_t , 3 , c)
CU_DeclarePoint() [18/27]
castor::CU_DeclarePoint (int8_t , 4 , c)
CU_DeclarePoint() [19/27]
castor::CU_DeclarePoint (uint16_t , 2 , us)
CU_DeclarePoint() [20/27]
castor::CU_DeclarePoint (uint16_t , 3 , us)
CU_DeclarePoint() [21/27]
castor::CU_DeclarePoint (uint16_t , 4 , us)
CU_DeclarePoint() [22/27]
castor::CU_DeclarePoint (uint32_t , 2 , ui)
CU_DeclarePoint() [23/27]
castor::CU_DeclarePoint (uint32_t , 3 , ui)
CU_DeclarePoint() [24/27]
castor::CU_DeclarePoint (uint32_t , 4 , ui)
CU_DeclarePoint() [25/27]
castor::CU_DeclarePoint (uint8_t , 2 , ub)
CU_DeclarePoint() [26/27]
castor::CU_DeclarePoint (uint8_t , 3 , ub)
CU_DeclarePoint() [27/27]
castor::CU_DeclarePoint (uint8_t , 4 , ub)
CU_DeclareSet()
castor::CU_DeclareSet (String , Str)
CU_DeclareSmartPtr() [1/8]
castor::CU_DeclareSmartPtr (castor , BoundingBox , CU_API)
CU_DeclareSmartPtr() [2/8]
castor::CU_DeclareSmartPtr (castor , BoundingSphere , CU_API)
CU_DeclareSmartPtr() [3/8]
castor::CU_DeclareSmartPtr (castor , DynamicLibrary , CU_API)
CU_DeclareSmartPtr() [4/8]
castor::CU_DeclareSmartPtr (castor , FileParserContext , CU_API)
CU_DeclareSmartPtr() [5/8]
castor::CU_DeclareSmartPtr (castor , Font , CU_API)
CU_DeclareSmartPtr() [6/8]
castor::CU_DeclareSmartPtr (castor , FontCache , CU_API)
CU_DeclareSmartPtr() [7/8]
castor::CU_DeclareSmartPtr (castor , Image , CU_API)
CU_DeclareSmartPtr() [8/8]
castor::CU_DeclareSmartPtr (castor , PxBufferBase , CU_API)
CU_DeclareSqMtx() [1/15]
castor::CU_DeclareSqMtx (bool , 2 , b)
CU_DeclareSqMtx() [2/15]
castor::CU_DeclareSqMtx (bool , 3 , b)
CU_DeclareSqMtx() [3/15]
castor::CU_DeclareSqMtx (bool , 4 , b)
CU_DeclareSqMtx() [4/15]
castor::CU_DeclareSqMtx (double , 2 , d)
CU_DeclareSqMtx() [5/15]
castor::CU_DeclareSqMtx (double , 3 , d)
CU_DeclareSqMtx() [6/15]
castor::CU_DeclareSqMtx (double , 4 , d)
CU_DeclareSqMtx() [7/15]
castor::CU_DeclareSqMtx (float , 2 , f)
CU_DeclareSqMtx() [8/15]
castor::CU_DeclareSqMtx (float , 3 , f)
CU_DeclareSqMtx() [9/15]
castor::CU_DeclareSqMtx (float , 4 , f)
CU_DeclareSqMtx() [10/15]
castor::CU_DeclareSqMtx (int32_t , 2 , i)
CU_DeclareSqMtx() [11/15]
castor::CU_DeclareSqMtx (int32_t , 3 , i)
CU_DeclareSqMtx() [12/15]
castor::CU_DeclareSqMtx (int32_t , 4 , i)
CU_DeclareSqMtx() [13/15]
castor::CU_DeclareSqMtx (uint32_t , 2 , ui)
CU_DeclareSqMtx() [14/15]
castor::CU_DeclareSqMtx (uint32_t , 3 , ui)
CU_DeclareSqMtx() [15/15]
castor::CU_DeclareSqMtx (uint32_t , 4 , ui)
CU_DeclareVector() [1/9]
castor::CU_DeclareVector (byte , Byte)
CU_DeclareVector() [2/9]
castor::CU_DeclareVector (MbString , MbString)
CU_DeclareVector() [3/9]
castor::CU_DeclareVector (MbStringView , MbStringView)
CU_DeclareVector() [4/9]
castor::CU_DeclareVector (ParserParameterBaseSPtr , ParserParameter)
CU_DeclareVector() [5/9]
castor::CU_DeclareVector (Path , Path)
CU_DeclareVector() [6/9]
castor::CU_DeclareVector (s32 , Int32)
CU_DeclareVector() [7/9]
castor::CU_DeclareVector (String , String)
CU_DeclareVector() [8/9]
castor::CU_DeclareVector (StringView , StringView)
CU_DeclareVector() [9/9]
castor::CU_DeclareVector (u32 , UInt32)
cuFailure()
CU_API void castor::cuFailure (char const *const description)
cuLogError()
CU_API void castor::cuLogError (char const *const description)
decompressBC1Block()
bool castor::decompressBC1Block (uint8_t const * bitstring, uint8_t * pixelBuffer)
decompressBC3Block()
bool castor::decompressBC3Block (uint8_t const * bitstring, uint8_t * pixelBuffer)
decompressBC5Block()
bool castor::decompressBC5Block (uint8_t const * bitstring, uint8_t * pixelBuffer)
decompressBuffer()
CU_API PxBufferBaseUPtr castor::decompressBuffer (PxBufferBase const & src)
Decompresses the given compressed pixel buffer.
Parameters
[in] src The compressed pixel buffer.
Returns
The decompressed pixel buffer.
divRoundUp()
template<std::integral TypeT> constexpr TypeT castor::divRoundUp (TypeT num, TypeT denom) constexpr
Division rounded up.
extractComponent()
CU_API PxBufferBaseUPtr castor::extractComponent (PxBufferBaseRPtr src, PixelComponent component)
Extracts pixel component values from a source buffer holding alpha and puts it in a destination buffer.
Parameters
[in] src The source buffer.
[in] component The component to extract.
Returns
A castor::PixelFormat::eR8 buffer containing the extracted component, nullptr if source didn't have the wanted component.
extractComponents()
CU_API PxBufferBaseUPtr castor::extractComponents (PxBufferBaseRPtr src, PixelComponents component)
Extracts pixel component values from a source buffer holding alpha and puts it in a destination buffer.
Parameters
[in] src The source buffer.
[in] component The component to extract.
Returns
A castor::PixelFormat::eR8 buffer containing the extracted component, nullptr if source didn't have the wanted component.
fileOpen()
CU_API bool castor::fileOpen (FILE *& file, std::filesystem::path const & path, char const * mode)
Opens a file.
Parameters
[out] file Receives the file descriptor
[in] path The file path
[in] mode The opening mode
Returns
true on success
fileOpen64()
CU_API bool castor::fileOpen64 (FILE *& file, std::filesystem::path const & path, char const * mode)
Opens a file.
Parameters
[out] file Receives the file descriptor
[in] path The file path
[in] mode The opening mode
Returns
true on success
fileSeek()
CU_API bool castor::fileSeek (FILE * file, int64_t offset, int origin)
Seeks into a file.
Parameters
[in] file The file descriptor
[in] offset The seek offset
[in] origin The seek origin
Returns
true on success
fileTell()
CU_API int64_t castor::fileTell (FILE * file)
Retrieves the file cursor position.
Parameters
[out] file The file descriptor
Returns
The position
getA16F()
template<PixelFormat PFT> int16_t castor::getA16F (uint8_t const * buffer)
getA16S()
template<PixelFormat PFT> int16_t castor::getA16S (uint8_t const * buffer)
getA16U()
template<PixelFormat PFT> uint16_t castor::getA16U (uint8_t const * buffer)
getA32F() [1/2]
template<PixelFormat PF> float castor::getA32F (Pixel< PF > const & pixel)
Function to retrieve pixel alpha component in float.
Parameters
[in] pixel The pixel
Returns
The component value
getA32F() [2/2]
template<PixelFormat PFT> float castor::getA32F (uint8_t const * buffer)
getA32S()
template<PixelFormat PFT> int32_t castor::getA32S (uint8_t const * buffer)
getA32U()
template<PixelFormat PFT> uint32_t castor::getA32U (uint8_t const * buffer)
getA64F()
template<PixelFormat PFT> double castor::getA64F (uint8_t const * buffer)
getA64S()
template<PixelFormat PFT> int64_t castor::getA64S (uint8_t const * buffer)
getA64U()
template<PixelFormat PFT> uint64_t castor::getA64U (uint8_t const * buffer)
getA8S()
template<PixelFormat PFT> int8_t castor::getA8S (uint8_t const * buffer)
getA8U() [1/2]
template<PixelFormat PF> uint8_t castor::getA8U (Pixel< PF > const & pixel)
Function to retrieve pixel alpha component in byte.
Parameters
[in] pixel The pixel
Returns
The component value
getA8U() [2/2]
template<PixelFormat PFT> uint8_t castor::getA8U (uint8_t const * buffer)
getB16F()
template<PixelFormat PFT> int16_t castor::getB16F (uint8_t const * buffer)
getB16S()
template<PixelFormat PFT> int16_t castor::getB16S (uint8_t const * buffer)
getB16U()
template<PixelFormat PFT> uint16_t castor::getB16U (uint8_t const * buffer)
getB32F() [1/2]
template<PixelFormat PF> float castor::getB32F (Pixel< PF > const & pixel)
Function to retrieve pixel blue component in float.
Parameters
[in] pixel The pixel
Returns
The component value
getB32F() [2/2]
template<PixelFormat PFT> float castor::getB32F (uint8_t const * buffer)
getB32S()
template<PixelFormat PFT> int32_t castor::getB32S (uint8_t const * buffer)
getB32U()
template<PixelFormat PFT> uint32_t castor::getB32U (uint8_t const * buffer)
getB64F()
template<PixelFormat PFT> double castor::getB64F (uint8_t const * buffer)
getB64S()
template<PixelFormat PFT> int64_t castor::getB64S (uint8_t const * buffer)
getB64U()
template<PixelFormat PFT> uint64_t castor::getB64U (uint8_t const * buffer)
getB8S()
template<PixelFormat PFT> int8_t castor::getB8S (uint8_t const * buffer)
getB8U() [1/2]
template<PixelFormat PF> uint8_t castor::getB8U (Pixel< PF > const & pixel)
Function to retrieve pixel blue component in byte.
Parameters
[in] pixel The pixel
Returns
The component value
getB8U() [2/2]
template<PixelFormat PFT> uint8_t castor::getB8U (uint8_t const * buffer)
getBitSize() [1/2]
static constexpr uint32_t castor::getBitSize (uint32_t value) static constexpr
References getBitSize().
getBitSize() [2/2]
static constexpr uint32_t castor::getBitSize (uint64_t value) static constexpr
Referenced by getBitSize(), and getNextPowerOfTwo().
getBuffer() [1/2]
ImageLayout::Buffer castor::getBuffer (ImageLayout const & layout, PxBufferBase & buffer) inline
References castor::ImageLayout::buffer().
getBuffer() [2/2]
ImageLayout::ConstBuffer castor::getBuffer (ImageLayout const & layout, PxBufferBase const & buffer) inline
References castor::ImageLayout::buffer().
getBytesPerPixel()
constexpr VkDeviceSize castor::getBytesPerPixel (PixelFormat format) constexpr
Function to retrieve Pixel size without templates.
Parameters
[in] format The pixel format
Referenced by castor::WhiteNoise::generate().
getComponentIndex() [1/2]
constexpr uint32_t castor::getComponentIndex (PixelComponent component) constexpr
Returns
The index matching the given PixelComponent.
getComponentIndex() [2/2]
constexpr uint32_t castor::getComponentIndex (PixelComponent component, PixelFormat format) constexpr
Returns
The index matching the given PixelComponent and PixelFormat.
getComponents()
constexpr PixelComponents castor::getComponents (PixelFormat format) constexpr
Returns
The PixelComponents matching the given PixelFormat.
getComponentsCount()
constexpr uint8_t castor::getComponentsCount (PixelFormat format) constexpr
Function to retrieve the number of components of a pixel format.
Parameters
[in] format The pixel format
getCountOf()
template<typename T , size_t N> size_t castor::getCountOf (T const(&) data[N]) inline
Returns
The buffer's elements count.
getD16U() [1/2]
template<PixelFormat PF> uint16_t castor::getD16U (Pixel< PF > const & pixel)
Function to retrieve pixel depth component in uint16_t.
Parameters
[in] pixel The pixel
Returns
The component value
getD16U() [2/2]
template<PixelFormat PFT> uint16_t castor::getD16U (uint8_t const * buffer)
getD24U() [1/2]
template<PixelFormat PF> uint32_t castor::getD24U (Pixel< PF > const & pixel)
Function to retrieve pixel depth component in uint32_t, with 24 relevant bits.
Parameters
[in] pixel The pixel
Returns
The component value
getD24U() [2/2]
template<PixelFormat PFT> uint32_t castor::getD24U (uint8_t const * buffer)
getD32F() [1/2]
template<PixelFormat PF> float castor::getD32F (Pixel< PF > const & pixel)
Function to retrieve pixel depth component in float.
Parameters
[in] pixel The pixel
Returns
The component value
getD32F() [2/2]
template<PixelFormat PFT> float castor::getD32F (uint8_t const * buffer)
getFormatByName()
CU_API PixelFormat castor::getFormatByName (StringView formatName)
Function to retrieve pixel format from a name.
Parameters
[in] formatName The pixel format name
getFormatName()
CU_API String castor::getFormatName (PixelFormat format)
Function to retrieve pixel format name.
Parameters
[in] format The pixel format
getG16F()
template<PixelFormat PFT> int16_t castor::getG16F (uint8_t const * buffer)
getG16S()
template<PixelFormat PFT> int16_t castor::getG16S (uint8_t const * buffer)
getG16U()
template<PixelFormat PFT> uint16_t castor::getG16U (uint8_t const * buffer)
getG32F() [1/2]
template<PixelFormat PF> float castor::getG32F (Pixel< PF > const & pixel)
Function to retrieve pixel green component in float.
Parameters
[in] pixel The pixel
Returns
The component value
getG32F() [2/2]
template<PixelFormat PFT> float castor::getG32F (uint8_t const * buffer)
getG32S()
template<PixelFormat PFT> int32_t castor::getG32S (uint8_t const * buffer)
getG32U()
template<PixelFormat PFT> uint32_t castor::getG32U (uint8_t const * buffer)
getG64F()
template<PixelFormat PFT> double castor::getG64F (uint8_t const * buffer)
getG64S()
template<PixelFormat PFT> int64_t castor::getG64S (uint8_t const * buffer)
getG64U()
template<PixelFormat PFT> uint64_t castor::getG64U (uint8_t const * buffer)
getG8S()
template<PixelFormat PFT> int8_t castor::getG8S (uint8_t const * buffer)
getG8U() [1/2]
template<PixelFormat PF> uint8_t castor::getG8U (Pixel< PF > const & pixel)
Function to retrieve pixel green component in byte.
Parameters
[in] pixel The pixel
Returns
The component value
getG8U() [2/2]
template<PixelFormat PFT> uint8_t castor::getG8U (uint8_t const * buffer)
getIndexComponent()
constexpr PixelComponent castor::getIndexComponent (uint32_t index, PixelFormat format) constexpr
Returns
The PixelComponent matching the given index and PixelFormat.
getLayerBuffer() [1/2]
ImageLayout::Buffer castor::getLayerBuffer (ImageLayout const & layout, PxBufferBase & buffer, uint32_t index) inline
References castor::ImageLayout::layerBuffer().
Referenced by castor::Image::getBuffer(), and castor::Image::getBuffer().
getLayerBuffer() [2/2]
ImageLayout::ConstBuffer castor::getLayerBuffer (ImageLayout const & layout, PxBufferBase const & buffer, uint32_t index) inline
References castor::ImageLayout::layerBuffer().
getLayerMipBuffer() [1/2]
ImageLayout::Buffer castor::getLayerMipBuffer (ImageLayout const & layout, PxBufferBase & buffer, uint32_t index, uint32_t level) inline
References castor::ImageLayout::layerMipBuffer().
Referenced by castor::Image::getBuffer(), and castor::Image::getBuffer().
getLayerMipBuffer() [2/2]
ImageLayout::ConstBuffer castor::getLayerMipBuffer (ImageLayout const & layout, PxBufferBase const & buffer, uint32_t index, uint32_t level) inline
References castor::ImageLayout::layerMipBuffer().
getLayerMipOffset()
ImageLayout::DeviceSize castor::getLayerMipOffset (ImageLayout const & layout, uint32_t index, uint32_t level) inline
References castor::ImageLayout::layerMipOffset().
getLayerMipSize()
ImageLayout::DeviceSize castor::getLayerMipSize (ImageLayout const & layout, uint32_t level) inline
References castor::ImageLayout::layerMipSize().
getLayerOffset()
ImageLayout::DeviceSize castor::getLayerOffset (ImageLayout const & layout, uint32_t index) inline
References castor::ImageLayout::layerOffset().
getLayerSize()
ImageLayout::DeviceSize castor::getLayerSize (ImageLayout const & layout) inline
References castor::ImageLayout::layerSize().
getLocaltime()
CU_API void castor::getLocaltime (std::tm * tm, time_t const * time)
See also
localtime
getName() [1/3]
CU_API String castor::getName (LengthUnit value)
getName() [2/3]
CU_API String castor::getName (PixelComponent const & component)
getName() [3/3]
CU_API String castor::getName (PixelComponents const & components)
getNextPowerOfTwo()
static constexpr uint32_t castor::getNextPowerOfTwo (uint32_t value) static constexpr
References getBitSize().
getNonSRGBFormat()
constexpr PixelFormat castor::getNonSRGBFormat (PixelFormat format) constexpr
Returns
The non SRGB format matching format, format if not found.
getParameterValue() [1/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, bool & value)
getParameterValue() [2/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, double & value)
getParameterValue() [3/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, float & value)
getParameterValue() [4/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, HdrRgbaColour & value)
getParameterValue() [5/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, HdrRgbColour & value)
getParameterValue() [6/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, int16_t & value)
getParameterValue() [7/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, int32_t & value)
getParameterValue() [8/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, int64_t & value)
getParameterValue() [9/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, int8_t & value)
getParameterValue() [10/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, long double & value)
getParameterValue() [11/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, Path & value)
getParameterValue() [12/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, PixelFormat & value)
getParameterValue() [13/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, Point2d & value)
getParameterValue() [14/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, Point2f & value)
getParameterValue() [15/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, Point2i & value)
getParameterValue() [16/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, Point2ui & value)
getParameterValue() [17/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, Point3d & value)
getParameterValue() [18/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, Point3f & value)
getParameterValue() [19/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, Point3i & value)
getParameterValue() [20/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, Point3ui & value)
getParameterValue() [21/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, Point4d & value)
getParameterValue() [22/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, Point4f & value)
getParameterValue() [23/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, Point4i & value)
getParameterValue() [24/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, Point4ui & value)
getParameterValue() [25/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, Position & value)
getParameterValue() [26/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, Rectangle & value)
getParameterValue() [27/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, RgbaColour & value)
getParameterValue() [28/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, RgbColour & value)
getParameterValue() [29/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, Size & value)
getParameterValue() [30/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, String & value)
getParameterValue() [31/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, uint16_t & value)
getParameterValue() [32/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, uint32_t & value)
getParameterValue() [33/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, uint64_t & value)
getParameterValue() [34/34]
CU_API void castor::getParameterValue (ParserParameterBase const & parameter, uint8_t & value)
getPFWithAlpha()
constexpr PixelFormat castor::getPFWithAlpha (PixelFormat format) constexpr
Retrieves the pixel format with alpha that is close to the one given.
Parameters
[in] format The pixel format
Returns
The given pixel format if none found
getPFWithoutAlpha()
constexpr PixelFormat castor::getPFWithoutAlpha (PixelFormat format) constexpr
Retrieves the pixel format without alpha that is close to the one given.
Parameters
[in] format The pixel format
Returns
The given pixel format if none found
getPixelComponents()
PixelComponents castor::getPixelComponents (PixelFormat format)
getPixelFormat()
CU_API PixelFormat castor::getPixelFormat (PixelFormat format, PixelComponents components)
Returns
The pixel format matching the given format and components.
Referenced by castor::Image::setPixel().
getPredefinedName() [1/2]
static String castor::getPredefinedName (PredefinedRgbaColour predefined) inline static
Retrieves predefined colour name.
Parameters
[in] predefined The predefined colour
Returns
The colour name
getPredefinedName() [2/2]
static String castor::getPredefinedName (PredefinedRgbColour predefined) static
Retrieves predefined colour name.
Parameters
[in] predefined The predefined colour
Returns
The colour name
getPredefinedRgb()
static PredefinedRgbColour castor::getPredefinedRgb (String const & name) inline static
Retrieves predefined colour from a name.
Parameters
[in] name The predefined colour name
Returns
The predefined colour
getPredefinedRgba()
static PredefinedRgbaColour castor::getPredefinedRgba (String const & name) inline static
Retrieves predefined colour from a name.
Parameters
[in] name The predefined colour name
Returns
The predefined colour
getR16F()
template<PixelFormat PFT> int16_t castor::getR16F (uint8_t const * buffer)
getR16S()
template<PixelFormat PFT> int16_t castor::getR16S (uint8_t const * buffer)
getR16U()
template<PixelFormat PFT> uint16_t castor::getR16U (uint8_t const * buffer)
getR32F() [1/2]
template<PixelFormat PF> float castor::getR32F (Pixel< PF > const & pixel)
Function to retrieve pixel colour component in float.
Parameters
[in] pixel The pixel
Returns
The component value
getR32F() [2/2]
template<PixelFormat PFT> float castor::getR32F (uint8_t const * buffer)
getR32S()
template<PixelFormat PFT> int32_t castor::getR32S (uint8_t const * buffer)
getR32U()
template<PixelFormat PFT> uint32_t castor::getR32U (uint8_t const * buffer)
getR64F()
template<PixelFormat PFT> double castor::getR64F (uint8_t const * buffer)
getR64S()
template<PixelFormat PFT> int64_t castor::getR64S (uint8_t const * buffer)
getR64U()
template<PixelFormat PFT> uint64_t castor::getR64U (uint8_t const * buffer)
getR8S()
template<PixelFormat PFT> int8_t castor::getR8S (uint8_t const * buffer)
getR8U() [1/2]
template<PixelFormat PF> uint8_t castor::getR8U (Pixel< PF > const & pixel)
Function to retrieve pixel red component in byte.
Parameters
[in] pixel The pixel
Returns
The component value
getR8U() [2/2]
template<PixelFormat PFT> uint8_t castor::getR8U (uint8_t const * buffer)
getS8U() [1/2]
template<PixelFormat PF> uint8_t castor::getS8U (Pixel< PF > const & pixel)
Function to retrieve pixel depth stencil in byte.
Parameters
[in] pixel The pixel
Returns
The component value
getS8U() [2/2]
template<PixelFormat PFT> uint8_t castor::getS8U (uint8_t const * buffer)
getSingleComponent()
constexpr PixelFormat castor::getSingleComponent (PixelFormat format) constexpr
Returns
The single component format for given pixel format.
getSliceBuffer() [1/2]
ImageLayout::Buffer castor::getSliceBuffer (ImageLayout const & layout, PxBufferBase & buffer, uint32_t index) inline
References castor::ImageLayout::sliceBuffer().
getSliceBuffer() [2/2]
ImageLayout::ConstBuffer castor::getSliceBuffer (ImageLayout const & layout, PxBufferBase const & buffer, uint32_t index) inline
References castor::ImageLayout::sliceBuffer().
getSliceMipBuffer() [1/2]
ImageLayout::Buffer castor::getSliceMipBuffer (ImageLayout const & layout, PxBufferBase & buffer, uint32_t index, uint32_t level) inline
References castor::ImageLayout::sliceMipBuffer().
getSliceMipBuffer() [2/2]
ImageLayout::ConstBuffer castor::getSliceMipBuffer (ImageLayout const & layout, PxBufferBase const & buffer, uint32_t index, uint32_t level) inline
References castor::ImageLayout::sliceMipBuffer().
getSliceMipOffset()
ImageLayout::DeviceSize castor::getSliceMipOffset (ImageLayout const & layout, uint32_t index, uint32_t level) inline
References castor::ImageLayout::sliceMipOffset().
getSliceMipSize()
ImageLayout::DeviceSize castor::getSliceMipSize (ImageLayout const & layout, uint32_t level) inline
References castor::ImageLayout::sliceMipSize().
getSliceOffset()
ImageLayout::DeviceSize castor::getSliceOffset (ImageLayout const & layout, uint32_t index) inline
References castor::ImageLayout::sliceOffset().
getSliceSize()
ImageLayout::DeviceSize castor::getSliceSize (ImageLayout const & layout) inline
References castor::ImageLayout::sliceSize().
getSRGBFormat()
constexpr PixelFormat castor::getSRGBFormat (PixelFormat format) constexpr
Returns
The SRGB format matching format, format if not found.
getTypeName()
CU_API StringView castor::getTypeName (ParameterType type)
Retrieves the given parameter type's name.
Parameters
[in] type The parameter type.
getX16F()
template<PixelFormat PFT, PixelComponent PCT> int16_t castor::getX16F (uint8_t const * buffer)
getX16S()
template<PixelFormat PFT, PixelComponent PCT> int16_t castor::getX16S (uint8_t const * buffer)
getX16U()
template<PixelFormat PFT, PixelComponent PCT> uint16_t castor::getX16U (uint8_t const * buffer)
getX32F()
template<PixelFormat PFT, PixelComponent PCT> float castor::getX32F (uint8_t const * buffer)
getX32S()
template<PixelFormat PFT, PixelComponent PCT> int32_t castor::getX32S (uint8_t const * buffer)
getX32U()
template<PixelFormat PFT, PixelComponent PCT> uint32_t castor::getX32U (uint8_t const * buffer)
getX64F()
template<PixelFormat PFT, PixelComponent PCT> double castor::getX64F (uint8_t const * buffer)
getX64S()
template<PixelFormat PFT, PixelComponent PCT> int64_t castor::getX64S (uint8_t const * buffer)
getX64U()
template<PixelFormat PFT, PixelComponent PCT> uint64_t castor::getX64U (uint8_t const * buffer)
getX8S()
template<PixelFormat PFT, PixelComponent PCT> int8_t castor::getX8S (uint8_t const * buffer)
getX8U()
template<PixelFormat PFT, PixelComponent PCT> uint8_t castor::getX8U (uint8_t const * buffer)
hasAll() [1/6]
template<typename FlagType > constexpr bool castor::hasAll (FlagCombination< FlagType > const & value, FlagCombination< FlagType > const & rhs) constexpr noexcept
Parameters
[in] value The value.
[in] rhs The flags looked for.
Returns
true if flags contain any of rhs.
hasAll() [2/6]
template<typename FlagType > constexpr bool castor::hasAll (FlagCombination< FlagType > const & value, FlagType const & rhs) constexpr noexcept
Parameters
[in] value The value.
[in] rhs The flags looked for.
Returns
true if flags contain any of rhs.
hasAll() [3/6]
template<typename FlagType > constexpr bool castor::hasAll (FlagCombination< FlagType > const & value, typename FlagCombination< FlagType >::BaseType const & rhs) constexpr noexcept
Parameters
[in] value The value.
[in] rhs The flags looked for.
Returns
true if flags contain any of rhs.
References hasAll().
hasAll() [4/6]
template<typename FlagType > constexpr bool castor::hasAll (FlagType const & value, FlagCombination< FlagType > const & rhs) constexpr noexcept
Parameters
[in] value The value.
[in] rhs The flags looked for.
Returns
true if flags contain any of rhs.
hasAll() [5/6]
template<typename T , typename U > constexpr bool castor::hasAll (T const & value, U const & rhs) constexpr noexcept
Parameters
[in] value The value.
[in] rhs The flags looked for.
Returns
true if flags contain any of rhs.
Referenced by hasAll(), and hasAll().
hasAll() [6/6]
template<typename FlagType > constexpr bool castor::hasAll (typename FlagCombination< FlagType >::BaseType const & value, FlagCombination< FlagType > const & rhs) constexpr noexcept
Parameters
[in] value The value.
[in] rhs The flags looked for.
Returns
true if flags contain any of rhs.
References hasAll().
hasAlpha()
constexpr bool castor::hasAlpha (PixelFormat format) constexpr
Returns
false if format is depth, stencil or one without alpha.
hasAlphaChannel()
CU_API bool castor::hasAlphaChannel (Image const & image)
hasAny() [1/3]
template<typename FlagType > constexpr bool castor::hasAny (FlagCombination< FlagType > const & value, FlagType const & rhs) constexpr noexcept
Parameters
[in] value The value.
[in] rhs The flags looked for.
Returns
true if flags contain any of rhs.
hasAny() [2/3]
template<typename FlagType , typename Type > constexpr bool castor::hasAny (FlagCombination< FlagType > const & value, Type const & rhs) constexpr noexcept
Parameters
[in] value The value.
[in] rhs The flags looked for.
Returns
true if flags contain any of rhs.
hasAny() [3/3]
template<typename T , typename U > constexpr bool castor::hasAny (T const & value, U const & rhs) constexpr noexcept
Parameters
[in] value The value.
[in] rhs The flags looked for.
Returns
true if flags contain any of rhs.
hasComponent()
constexpr bool castor::hasComponent (PixelFormat format, PixelComponent component) constexpr
Parameters
[in] format The pixel format.
[in] component The pixel component.
Returns
true if the given pixel format contains the wanted pixel component.
hashCombine()
template<typename T > size_t castor::hashCombine (size_t & hash, T const & rhs) inline
Referenced by castor3d::InstantiatedPipelinesNodesT< NodeT >::emplace(), and castor3d::PipelinesNodesT< NodeT >::emplace().
hashCombine32()
template<typename T > uint32_t castor::hashCombine32 (uint32_t & hash, T const & rhs) inline
Referenced by castor::hashcomb::HashCombinerT< HashT, std::enable_if_t< std::is_same_v< HashT, uint32_t > > >::combine(), and castor::hashcomb::HashCombinerT< HashT, std::enable_if_t< !std::is_same_v< HashT, uint32_t > &&sizeof(HashT)==4u > >::combine().
hashCombine64()
template<typename T > uint64_t castor::hashCombine64 (uint64_t & hash, T const & rhs) inline
Referenced by castor::hashcomb::HashCombinerT< HashT, std::enable_if_t< std::is_same_v< HashT, uint64_t > > >::combine(), and castor::hashcomb::HashCombinerT< HashT, std::enable_if_t< !std::is_same_v< HashT, uint64_t > &&sizeof(HashT)==8u > >::combine().
hashCombinePtr()
template<typename T > size_t castor::hashCombinePtr (size_t & hash, T const & rhs) inline
hashCombinePtr32()
template<typename T > uint32_t castor::hashCombinePtr32 (uint32_t & hash, T const & rhs) inline
Referenced by castor::hashcomb::HashCombinerT< HashT, std::enable_if_t< std::is_same_v< HashT, uint32_t > > >::combinePtr(), and castor::hashcomb::HashCombinerT< HashT, std::enable_if_t< !std::is_same_v< HashT, uint32_t > &&sizeof(HashT)==4u > >::combinePtr().
hashCombinePtr64()
template<typename T > uint64_t castor::hashCombinePtr64 (uint64_t & hash, T const & rhs) inline
Referenced by castor::hashcomb::HashCombinerT< HashT, std::enable_if_t< std::is_same_v< HashT, uint64_t > > >::combinePtr(), and castor::hashcomb::HashCombinerT< HashT, std::enable_if_t< !std::is_same_v< HashT, uint64_t > &&sizeof(HashT)==8u > >::combinePtr().
hasLayerBuffer()
bool castor::hasLayerBuffer (ImageLayout const & layout, PxBufferBase const & buffer, uint32_t index) inline
References castor::ImageLayout::hasLayerBuffer().
hasLayerMipBuffer()
bool castor::hasLayerMipBuffer (ImageLayout const & layout, PxBufferBase const & buffer, uint32_t index, uint32_t level) inline
References castor::ImageLayout::hasLayerMipBuffer().
hasSliceBuffer()
bool castor::hasSliceBuffer (ImageLayout const & layout, PxBufferBase const & buffer, uint32_t index) inline
References castor::ImageLayout::hasSliceBuffer().
hasSliceMipBuffer()
bool castor::hasSliceMipBuffer (ImageLayout const & layout, PxBufferBase const & buffer, uint32_t index, uint32_t level) inline
References castor::ImageLayout::hasSliceMipBuffer().
isABGRFormat()
constexpr bool castor::isABGRFormat (PixelFormat format) constexpr
Returns
true if format is an ABGR format.
isARGBFormat()
constexpr bool castor::isARGBFormat (PixelFormat format) constexpr
Returns
true if format is an ARGB format.
isBGRAFormat()
constexpr bool castor::isBGRAFormat (PixelFormat format) constexpr
Returns
true if format is an BGRA format.
isBGRFormat()
constexpr bool castor::isBGRFormat (PixelFormat format) constexpr
Returns
true if format is an BGR format.
isBigEndian()
constexpr bool castor::isBigEndian () constexpr noexcept
Detects if the current system is big endian.
Referenced by bigEndianToSystemEndian(), bigEndianToSystemEndian(), bigEndianToSystemEndian(), bigEndianToSystemEndian(), bigEndianToSystemEndian(), bigEndianToSystemEndian(), systemEndianToBigEndian(), systemEndianToBigEndian(), systemEndianToBigEndian(), systemEndianToBigEndian(), systemEndianToBigEndian(), and systemEndianToBigEndian().
isCompressed()
constexpr bool castor::isCompressed (PixelFormat format) constexpr
Returns
true if the given pixel format is a compressed one.
isDepthOrStencilFormat()
constexpr bool castor::isDepthOrStencilFormat (PixelFormat format) constexpr
Returns
true if format is a depth and/or stencil format.
isFloatingPoint() [1/2]
constexpr bool castor::isFloatingPoint (PixelFormat format) constexpr
Returns
true if the given pixel format is a floating point one.
Referenced by isFloatingPoint().
isFloatingPoint() [2/2]
constexpr bool castor::isFloatingPoint (VkFormat format) constexpr
References isFloatingPoint().
isInt16() [1/2]
constexpr bool castor::isInt16 (PixelFormat format) constexpr
Returns
true if the given pixel format is a int16 one.
Referenced by isInt16().
isInt16() [2/2]
constexpr bool castor::isInt16 (VkFormat format) constexpr
References isInt16().
isInt32() [1/2]
constexpr bool castor::isInt32 (PixelFormat format) constexpr
Returns
true if the given pixel format is a int32 one.
Referenced by isInt32().
isInt32() [2/2]
constexpr bool castor::isInt32 (VkFormat format) constexpr
References isInt32().
isInt8() [1/2]
constexpr bool castor::isInt8 (PixelFormat format) constexpr
Returns
true if the given pixel format is a int8 one.
Referenced by isInt8().
isInt8() [2/2]
constexpr bool castor::isInt8 (VkFormat format) constexpr
References isInt8().
isLittleEndian()
constexpr bool castor::isLittleEndian () constexpr noexcept
Detects if the current system is little endian.
Referenced by castor3d::chunkEndianToSystemEndian(), castor3d::BinaryParserBase< TParsed >::doIsLittleEndian(), littleEndianToSystemEndian(), littleEndianToSystemEndian(), littleEndianToSystemEndian(), littleEndianToSystemEndian(), littleEndianToSystemEndian(), littleEndianToSystemEndian(), castor3d::prepareChunkDataT(), systemEndianToLittleEndian(), systemEndianToLittleEndian(), systemEndianToLittleEndian(), systemEndianToLittleEndian(), systemEndianToLittleEndian(), and systemEndianToLittleEndian().
isPowerOfTwo()
static constexpr bool castor::isPowerOfTwo (uint32_t value) static constexpr
isRGBAFormat()
constexpr bool castor::isRGBAFormat (PixelFormat format) constexpr
Returns
true if format is an RGBA format.
isRGBFormat()
constexpr bool castor::isRGBFormat (PixelFormat format) constexpr
Returns
true if format is an RGB format.
isRGFormat()
constexpr bool castor::isRGFormat (PixelFormat format) constexpr
Returns
true if format is an RG format.
isSRGBFormat()
constexpr bool castor::isSRGBFormat (PixelFormat format) constexpr
Tells if the given format is an SRGB one.
Parameters
[in] format The pixel format
littleEndianToSystemEndian() [1/6]
template<typename T , size_t N> constexpr Array< T, N > & castor::littleEndianToSystemEndian (Array< T, N > & value) constexpr noexcept
Convert the given value to little endian if needed.
Parameters
[in,out] value Value to be converted.
References isLittleEndian(), and switchEndianness().
littleEndianToSystemEndian() [2/6]
template<typename T , size_t N> constexpr Array< T, N > castor::littleEndianToSystemEndian (Array< T, N > const & value) constexpr
Convert the given value to little endian if needed.
Parameters
[in,out] value Value to be converted.
References isLittleEndian(), and switchEndianness().
littleEndianToSystemEndian() [3/6]
template<typename T > constexpr T & castor::littleEndianToSystemEndian (T & value) constexpr noexcept
Convert the given little endian value to system endian if needed.
Parameters
[in,out] value Value to be converted.
References isLittleEndian(), and switchEndianness().
littleEndianToSystemEndian() [4/6]
template<typename T > constexpr T castor::littleEndianToSystemEndian (T const & value) constexpr
Convert the given little endian value to system endian if needed.
Parameters
[in,out] value Value to be converted.
References isLittleEndian(), and switchEndianness().
littleEndianToSystemEndian() [5/6]
template<typename T > Vector< T > & castor::littleEndianToSystemEndian (Vector< T > & value) inline noexcept
Convert the given value to little endian if needed.
Parameters
[in,out] value Value to be converted.
References isLittleEndian(), and switchEndianness().
littleEndianToSystemEndian() [6/6]
template<typename T > Vector< T > castor::littleEndianToSystemEndian (Vector< T > const & value) inline
Convert the given value to little endian if needed.
Parameters
[in,out] value Value to be converted.
References isLittleEndian(), and switchEndianness().
makeArrayView() [1/5]
template<typename IterT , typename ValueT = typename IteratorTraits< IterT >::value_type> ArrayView< ValueT > castor::makeArrayView (IterT begin, IterT end)
Referenced by castor3d::TextWord::chars(), castor3d::TextLine::chars(), castor::Image::getBuffer(), castor::Image::getBuffer(), castor3d::GpuBufferOffsetT< DataT >::getData(), castor3d::OverlayLines::lines(), castor3d::OverlayLines::lines(), makeArrayView(), makeArrayView(), makeArrayView(), castor3d::OverlayWords::words(), castor3d::OverlayWords::words(), and castor3d::TextLine::words().
makeArrayView() [2/5]
template<typename IterT > auto castor::makeArrayView (IterT begin, uint32_t size)
References makeArrayView().
makeArrayView() [3/5]
template<typename IterT > auto castor::makeArrayView (IterT begin, uint64_t size)
References makeArrayView().
makeArrayView() [4/5]
template<typename ValueT > ArrayView< ValueT > castor::makeArrayView (ValueT * begin, ValueT * end)
makeArrayView() [5/5]
template<typename ValueT , size_t N> auto castor::makeArrayView (ValueT(&) buffer[N])
References makeArrayView().
makeBlockGuard() [1/2]
template<typename CleanFunc > BlockGuard< CleanFunc > castor::makeBlockGuard (CleanFunc clean)
Helper function to declare a BlockGuard.
Parameters
[in] clean The action executed on destruction.
Returns
The block guard.
makeBlockGuard() [2/2]
template<typename InitFunc , typename CleanFunc > BlockGuard< CleanFunc > castor::makeBlockGuard (InitFunc init, CleanFunc clean)
Helper function to declare a BlockGuard.
Parameters
[in] init The action executed on construction.
[in] clean The action executed on destruction.
Returns
The block guard.
makeCache()
template<typename ResT , typename KeyT , typename TraitsT , typename ... ParametersT> ResourceCachePtrT< ResT, KeyT, TraitsT > castor::makeCache (ParametersT &&... parameters)
Creates a cache.
Parameters
[in] parameters The cache ctor parameters.
makeChangeTracked()
template<typename ValueT > ChangeTracked< ValueT > castor::makeChangeTracked (ValueT const & value)
makeChangeTrackedT()
template<typename ControlT , typename ValueT > ChangeTrackedT< ValueT, ControlT > castor::makeChangeTrackedT (ValueT const & value)
makeContextDeleter()
template<typename ContextT > ContextDeleterPtr castor::makeContextDeleter ()
makeDefaultedParameter()
template<ParameterType Type, typename ... Params> ParserParameterBaseSPtr castor::makeDefaultedParameter (ParserParameterValueType< Type > defaultValue, Params &&... params)
Creates a parameter of given type.
Returns
The created parameter.
makeFractalNoise()
template<typename NoiseT > FractalNoiseT< NoiseT > castor::makeFractalNoise (uint32_t octaves, NoiseT noise)
References makeFractalNoise().
Referenced by makeFractalNoise().
makeGroupChangeTracked()
template<typename ValueT , typename ControlT > GroupChangeTrackedT< ValueT, ControlT > castor::makeGroupChangeTracked (ControlT & dirty, ValueT const & value)
makeParameter() [1/5]
template<ParameterType Type> ParserParameterBaseSPtr castor::makeParameter ()
Creates a parameter of given type.
Returns
The created parameter.
makeParameter() [2/5]
template<ParameterType Type, typename EnumType > ParserParameterBaseSPtr castor::makeParameter ()
Creates a parameter of given type.
Returns
The created parameter.
References eBitwiseOred32BitsCheckedText, eBitwiseOred64BitsCheckedText, and eCheckedText.
makeParameter() [3/5]
template<ParameterType Type, typename T > ParserParameterBaseSPtr castor::makeParameter (Range< T > const & range)
Creates a parameter of given type.
Returns
The created parameter.
References eDouble, eFloat, eInt16, eInt32, eInt64, eInt8, eLongDouble, eUInt16, eUInt32, eUInt64, and eUInt8.
makeParameter() [4/5]
template<ParameterType Type> ParserParameterBaseSPtr castor::makeParameter (StringView name, UInt32StrMap const & values)
Creates a parameter of given type.
Parameters
[in] name The parameter type name.
[in] values The values used to validate the parsed value.
Returns
The created parameter.
References eBitwiseOred32BitsCheckedText, and eCheckedText.
makeParameter() [5/5]
template<ParameterType Type> ParserParameterBaseSPtr castor::makeParameter (StringView name, UInt64StrMap const & values)
Creates a parameter of given type.
Parameters
[in] name The parameter type name.
[in] values The values used to validate the parsed value.
Returns
The created parameter.
References eBitwiseOred64BitsCheckedText.
makePath()
CU_API std::filesystem::path castor::makePath (StringView str)
makeRange()
template<typename T > Range< T > castor::makeRange (T const & min, T const & max) inline noexcept
Helper function to create a range.
Parameters
[in] min,max The range.
Returns
The created range.
Referenced by makeRangedValue().
makeRangedValue()
template<typename T > RangedValue< T > castor::makeRangedValue (T const & value, T const & min, T const & max) inline noexcept
Helper function to create a ranged value.
Parameters
[in] value The value.
[in] min,max The range.
Returns
The created ranged value.
References makeRange().
makeRangeSequence()
template<typename T > RangeSequenceT< T > castor::makeRangeSequence (Vector< T > const & sequence) inline
makeResource()
template<typename ResT , typename KeyT , typename ... ParametersT> ResourcePtrT< ResT, KeyT > castor::makeResource (ParametersT &&... params) inline
Resource creation helper.
makeScopeGuard()
template<typename ScopeExitFuncType > ScopeGuard< ScopeExitFuncType > castor::makeScopeGuard (ScopeExitFuncType const & function)
Helper function to create a ScopeGuard.
Parameters
[in] function The function.
Returns
The ScopeGuard.
makeSpeed() [1/2]
template<typename DurationT , typename ValueT > SpeedT< ValueT, DurationT > castor::makeSpeed (ValueT const & value)
makeSpeed() [2/2]
template<typename DurationT , typename ValueT > SpeedT< ValueT, DurationT > castor::makeSpeed (ValueT const & value, DurationT const &)
makeString() [1/12]
String castor::makeString (mbchar const * in) inline
References makeString().
makeString() [2/12]
String castor::makeString (mbchar const * in, size_t length) inline
References makeString().
makeString() [3/12]
String castor::makeString (MbString const & in) inline
References makeString().
makeString() [4/12]
CU_API String castor::makeString (MbStringView const & in)
Referenced by castor3d::getEnumMapT(), castor::DynamicLibrary::getFunction(), castor::DynamicLibrary::getFunction(), castor::DynamicLibrary::getFunction(), castor::DynamicLibrary::getFunction(), castor3d::RenderSystem::getRendererType(), makeString(), makeString(), makeString(), makeString(), makeString(), makeString(), makeString(), makeString(), makeString(), castor3d::ChunkParser< castor::Path >::parse(), and castor3d::ChunkParser< castor::String >::parse().
makeString() [5/12]
String castor::makeString (u32char const * in) inline
References makeString().
makeString() [6/12]
String castor::makeString (u32char const * in, size_t length) inline
References makeString().
makeString() [7/12]
String castor::makeString (U32String const & in) inline
References makeString().
makeString() [8/12]
CU_API String castor::makeString (U32StringView const & in)
makeString() [9/12]
String castor::makeString (wchar const * in) inline
References makeString().
makeString() [10/12]
String castor::makeString (wchar const * in, size_t length) inline
References makeString().
makeString() [11/12]
String castor::makeString (WString const & in) inline
References makeString().
makeString() [12/12]
CU_API String castor::makeString (WStringView const & in)
makeStringStream()
StringStream castor::makeStringStream () inline
Returns
A std::stringstream using C locale.
Referenced by castor::ConnectionT< MySignalT >::ConnectionT(), castor3d::BinaryWriterBase< TWritten >::doWriteHeader(), castor::Exception::Exception(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportAdded(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportCreation(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportDuplicate(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportNull(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::reportUnknown(), and castor::TSConnectionT< SignalT >::TSConnectionT().
makeStringStreamT()
template<typename CharT > std::basic_stringstream< CharT > castor::makeStringStreamT () inline
Returns
A std::stringstream using C locale.
makeUnique()
template<typename TypeT , typename ... ParamsT> UniquePtr< TypeT > castor::makeUnique (ParamsT &&... params)
makeUniqueDerived()
template<typename TypeT , typename TypeU , typename ... ParamsT> UniquePtr< TypeT > castor::makeUniqueDerived (ParamsT &&... params)
makeUniqueLock()
template<typename Lockable > UniqueLock< Lockable > castor::makeUniqueLock (Lockable & lockable)
Referenced by castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::add(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::add(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::cleanup(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::clear(), castor::TSSignalT< Function >::connect(), castor3d::UserInputListener::doAddHandler(), castor3d::UserInputListener::doGetHandlers(), castor3d::UserInputListener::doHasHandlers(), castor3d::UserInputListener::doRemoveHandler(), castor::format::BasicIndentBufferManager< char_type, traits >::erase(), castor::format::BasicPrefixBufferManager< prefix_type, char_type, traits >::erase(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::find(), castor3d::RenderTargetCache::forEach(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::forEach(), castor3d::RenderTargetCache::forEach(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::forEach(), castor::format::BasicIndentBufferManager< char_type, traits >::getBuffer(), castor::format::BasicPrefixBufferManager< prefix_type, char_type, traits >::getBuffer(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::getObjectCount(), castor::format::BasicIndentBufferManager< char_type, traits >::insert(), castor::format::BasicPrefixBufferManager< prefix_type, char_type, traits >::insert(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::isEmpty(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::mergeInto(), castor3d::ObjectCacheBaseT< ObjT, KeyT, TraitsT >::mergeInto(), castor::TSSignalT< Function >::operator()(), castor::TSSignalT< Function >::operator()(), castor::TSSignalT< Function >::operator=(), castor::LoggerStreambufT< CharT, TraitsT >::overflow(), castor3d::EventHandler::pushEvent(), castor3d::EventHandler::pushEvent(), castor3d::EventHandler::pushEvent(), castor::LoggerInstance::pushMessage(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::remove(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::rename(), castor::format::BasicIndentBufferManager< char_type, traits >::size(), castor::format::BasicPrefixBufferManager< prefix_type, char_type, traits >::size(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::tryAdd(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::tryAdd(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::tryFind(), castor::ResourceCacheBaseT< ResT, KeyT, TraitsT >::tryRemove(), castor::TSSignalT< Function >::TSSignalT(), castor::format::BasicIndentBufferManager< char_type, traits >::~BasicIndentBufferManager(), castor::format::BasicPrefixBufferManager< prefix_type, char_type, traits >::~BasicPrefixBufferManager(), castor3d::EventHandler::~EventHandler(), castor::TSConnectionT< SignalT >::~TSConnectionT(), and castor::TSSignalT< Function >::~TSSignalT().
operator!=() [1/34]
template<typename Type > bool castor::operator!= (AngleT< Type > const & lhs, AngleT< Type > const & rhs) inline noexcept
Difference operator.
Parameters
[in] lhs First operand
[in] rhs Second operand
Returns
true if lhs is different from rhs
operator!=() [2/34]
template<typename IterT > bool castor::operator!= (ArrayView< IterT > const & lhs, ArrayView< IterT > const & rhs)
operator!=() [3/34]
bool castor::operator!= (BoundingBox const & lhs, BoundingBox const & rhs) inline
operator!=() [4/34]
bool castor::operator!= (BoundingSphere const & lhs, BoundingSphere const & rhs) inline
operator!=() [5/34]
template<typename ValueT , typename ControlT > bool castor::operator!= (ChangeTrackedT< ValueT, ControlT > const & lhs, ChangeTrackedT< ValueT, ControlT > const & rhs)
References operator==().
operator!=() [6/34]
template<typename ValueT , typename ControlT > bool castor::operator!= (ChangeTrackedT< ValueT, ControlT > const & lhs, ValueT const & rhs)
References operator==().
operator!=() [7/34]
CU_API bool castor::operator!= (ColourComponent const & lhs, ColourComponent const & rhs)
Inequality operator.
Parameters
[in] lhs,rhs The components to compare
operator!=() [8/34]
template<typename T , uint32_t Count, typename U , uint32_t UCount> bool castor::operator!= (Coords< T, Count > const & lhs, Coords< U, UCount > const & rhs)
operator!=() [9/34]
template<typename T , uint32_t TCount, typename U , uint32_t UCount> bool castor::operator!= (Coords< T, TCount > const & lhs, Point< U, UCount > const & rhs)
operator!=() [10/34]
template<typename BlockTypeT > bool castor::operator!= (DynamicBitsetT< BlockTypeT > const & lhs, DynamicBitsetT< BlockTypeT > const & rhs) inline
operator!=() [11/34]
template<typename FlagType > constexpr bool castor::operator!= (FlagCombination< FlagType > const & lhs, FlagCombination< FlagType > const & rhs) constexpr noexcept
operator!=() [12/34]
template<typename FlagType > constexpr bool castor::operator!= (FlagCombination< FlagType > const & lhs, FlagType const & rhs) constexpr noexcept
operator!=() [13/34]
template<typename FlagTypeT , typename IteratorTraitsT > constexpr bool castor::operator!= (FlagIterator< FlagTypeT, IteratorTraitsT > const & lhs, FlagIterator< FlagTypeT, IteratorTraitsT > const & rhs) constexpr
operator!=() [14/34]
bool castor::operator!= (Glyph const & lhs, Glyph const & rhs) inline
Difference comparison operator.
Parameters
[in] lhs,rhs The values to compare.
operator!=() [15/34]
template<typename ValueT , typename ControlT > bool castor::operator!= (GroupChangeTrackedT< ValueT, ControlT > const & lhs, GroupChangeTrackedT< ValueT, ControlT > const & rhs)
References operator==().
operator!=() [16/34]
template<typename ValueT , typename ControlT > bool castor::operator!= (GroupChangeTrackedT< ValueT, ControlT > const & lhs, ValueT const & rhs)
References operator==().
operator!=() [17/34]
CU_API bool castor::operator!= (HdrColourComponent const & lhs, HdrColourComponent const & rhs)
Inequality operator.
Parameters
[in] lhs,rhs The components to compare
operator!=() [18/34]
template<typename TypeT > bool castor::operator!= (LengthT< TypeT > const & lhs, LengthT< TypeT > const & rhs) inline noexcept
operator!=() [19/34]
template<typename T , uint32_t Columns, uint32_t Rows> bool castor::operator!= (Matrix< T, Columns, Rows > const & lhs, Matrix< T, Columns, Rows > const & rhs)
operator!=() [20/34]
CU_API bool castor::operator!= (PlaneEquation const & lhs, PlaneEquation const & rhs)
Checks if this plane is different from another one.
operator!=() [21/34]
template<typename T , uint32_t TCount, typename U , uint32_t UCount> bool castor::operator!= (Point< T, TCount > const & lhs, Coords< U, UCount > const & rhs)
operator!=() [22/34]
template<typename T , uint32_t TCount, typename U , uint32_t UCount> bool castor::operator!= (Point< T, TCount > const & lhs, Point< U, UCount > const & rhs)
operator!=() [23/34]
CU_API bool castor::operator!= (Position const & a, Position const & b)
Difference operator.
Parameters
[in] a,b The positions to compare
Returns
false if positions have same coordinates
operator!=() [24/34]
template<typename T > bool castor::operator!= (RangedValue< T > const & lhs, RangedValue< T > const & rhs) inline noexcept
operator!=() [25/34]
template<typename T > bool castor::operator!= (RangedValue< T > const & lhs, T const & rhs) inline noexcept
operator!=() [26/34]
template<typename ComponentType > bool castor::operator!= (RgbaColourT< ComponentType > const & lhs, RgbaColourT< ComponentType > const & rhs) inline
Inequality operator.
Parameters
[in] lhs,rhs The colours to compare
operator!=() [27/34]
template<typename ComponentType > bool castor::operator!= (RgbColourT< ComponentType > const & lhs, RgbColourT< ComponentType > const & rhs) inline
Inequality operator.
Parameters
[in] lhs,rhs The colours to compare
operator!=() [28/34]
CU_API bool castor::operator!= (Size const & a, Size const & b) noexcept
Difference operator.
Parameters
[in] a,b The sizes to compare
Returns
false if sizes have same dimensions
operator!=() [29/34]
template<typename ValueT , typename DurationT , typename TraitsT > bool castor::operator!= (SpeedT< ValueT, DurationT, TraitsT > const & lhs, SpeedT< ValueT, DurationT, TraitsT > const & rhs)
operator!=() [30/34]
template<typename T , uint32_t Count> bool castor::operator!= (SquareMatrix< T, Count > const & lhs, SquareMatrix< T, Count > const & rhs)
operator!=() [31/34]
template<typename T > bool castor::operator!= (T const & lhs, RangedValue< T > const & rhs) inline noexcept
operator!=() [32/34]
template<typename BlockTypeT > bool castor::operator!= (typename DynamicBitsetT< BlockTypeT >::Bit const & lhs, typename DynamicBitsetT< BlockTypeT >::Bit const & rhs) inline
operator!=() [33/34]
template<typename ValueT , typename ControlT > bool castor::operator!= (ValueT const & lhs, ChangeTrackedT< ValueT, ControlT > const & rhs)
References operator==().
operator!=() [34/34]
template<typename ValueT , typename ControlT > bool castor::operator!= (ValueT const & lhs, GroupChangeTrackedT< ValueT, ControlT > const & rhs)
References operator==().
operator&() [1/5]
template<typename BlockTypeT > DynamicBitsetT< BlockTypeT > castor::operator& (DynamicBitsetT< BlockTypeT > const & lhs, DynamicBitsetT< BlockTypeT > const & rhs) inline
operator&() [2/5]
template<typename FlagType > constexpr FlagCombination< FlagType > castor::operator& (FlagCombination< FlagType > const & lhs, FlagCombination< FlagType > const & rhs) constexpr noexcept
operator&() [3/5]
template<typename FlagType > constexpr FlagCombination< FlagType > castor::operator& (FlagCombination< FlagType > const & lhs, FlagType const & rhs) constexpr noexcept
operator&() [4/5]
template<typename FlagType > constexpr FlagCombination< FlagType > castor::operator& (FlagCombination< FlagType > const & lhs, typename FlagCombination< FlagType >::BaseType const & rhs) constexpr noexcept
operator&() [5/5]
template<typename BlockTypeT > DynamicBitsetT< BlockTypeT >::Bit castor::operator& (typename DynamicBitsetT< BlockTypeT >::Bit const & lhs, bool rhs)
operator*() [1/41]
template<typename Type > AngleT< Type > castor::operator* (AngleT< Type > const & lhs, AngleT< Type > const & rhs) inline noexcept
Multiplication operator.
Parameters
[in] lhs First operand
[in] rhs Second operand
Returns
Result of multiplication
operator*() [2/41]
template<typename Type > AngleT< Type > castor::operator* (AngleT< Type > const & lhs, double rhs) inline noexcept
Multiplication operator.
Parameters
[in] lhs First operand
[in] rhs Second operand
Returns
Result of multiplication
operator*() [3/41]
CU_API float castor::operator* (ColourComponent const & lhs, ColourComponent const & rhs)
Multiplication operator.
Parameters
[in] lhs,rhs The components to multiply
Returns
Result of lhs * rhs
operator*() [4/41]
template<typename T > float castor::operator* (ColourComponent const & lhs, T const & rhs)
Multiplication assignment operator.
Parameters
[in] lhs,rhs The components to multiply
Returns
Result of lhs * rhs
operator*() [5/41]
template<typename T , uint32_t Count, typename U , uint32_t UCount> Point< std::remove_cv_t< T >, Count > castor::operator* (Coords< T, Count > const & lhs, Coords< U, UCount > const & rhs)
operator*() [6/41]
template<typename T , uint32_t Count> Point< std::remove_cv_t< T >, Count > castor::operator* (Coords< T, Count > const & lhs, T const & rhs)
operator*() [7/41]
template<typename T , uint32_t Count, typename U > Point< std::remove_cv_t< T >, Count > castor::operator* (Coords< T, Count > const & lhs, U const * rhs)
operator*() [8/41]
template<typename T , uint32_t TCount, typename U , uint32_t UCount> Point< std::remove_cv_t< T >, TCount > castor::operator* (Coords< T, TCount > const & lhs, Point< U, UCount > const & rhs)
operator*() [9/41]
template<typename T > QuaternionT< T > castor::operator* (double lhs, QuaternionT< T > const & rhs) inline
Multiplication operator.
Parameters
[in] lhs The scalar to multiply
[in] rhs The Quaternion object to multiply
Returns
The multiplication result
operator*() [10/41]
template<typename T > QuaternionT< T > castor::operator* (float lhs, QuaternionT< T > const & rhs) inline
Multiplication operator.
Parameters
[in] lhs The scalar to multiply
[in] rhs The Quaternion object to multiply
Returns
The multiplication result
operator*() [11/41]
CU_API float castor::operator* (HdrColourComponent const & lhs, HdrColourComponent const & rhs)
Multiplication operator.
Parameters
[in] lhs,rhs The components to multiply
Returns
Result of lhs * rhs
operator*() [12/41]
template<typename T > float castor::operator* (HdrColourComponent const & lhs, T const & rhs)
Multiplication assignment operator.
Parameters
[in] lhs,rhs The components to multiply
Returns
Result of lhs * rhs
operator*() [13/41]
template<typename TypeT > LengthT< TypeT > castor::operator* (LengthT< TypeT > const & lhs, double rhs) inline noexcept
operator*() [14/41]
CU_API Point3f castor::operator* (Matrix4x4f const & lhs, Point3f const & rhs)
operator*() [15/41]
CU_API Point4f castor::operator* (Matrix4x4f const & lhs, Point4f const & rhs)
operator*() [16/41]
template<typename T , uint32_t Columns, uint32_t Rows, typename U , uint32_t ColumnsU> Matrix< T, ColumnsU, Rows > castor::operator* (Matrix< T, Columns, Rows > const & lhs, Matrix< U, ColumnsU, Columns > const & rhs)
operator*() [17/41]
template<typename T , uint32_t Columns, uint32_t Rows, typename U > Point< T, Rows > castor::operator* (Matrix< T, Columns, Rows > const & lhs, Point< U, Columns > const & rhs)
operator*() [18/41]
template<typename T , uint32_t Columns, uint32_t Rows, typename U > Matrix< T, Columns, Rows > castor::operator* (Matrix< T, Columns, Rows > const & lhs, T const & rhs)
operator*() [19/41]
template<typename T , uint32_t Count, typename U , uint32_t Rows> Matrix< T, Count, Rows > castor::operator* (Matrix< U, Count, Rows > const & lhs, SquareMatrix< T, Count > const & rhs)
operator*() [20/41]
template<PixelFormat FT, PixelFormat FU> Pixel< FT > castor::operator* (Pixel< FT > const & lhs, Pixel< FU > const & rhs)
operator*() [21/41]
CU_API Point3f castor::operator* (Point3f const & lhs, Matrix4x4f const & rhs)
operator*() [22/41]
CU_API Point4f castor::operator* (Point4f const & lhs, Matrix4x4f const & rhs)
operator*() [23/41]
template<typename T , uint32_t Columns, uint32_t Rows, typename U > Point< T, Columns > castor::operator* (Point< T, Rows > const & lhs, Matrix< U, Columns, Rows > const & rhs)
operator*() [24/41]
template<typename T , uint32_t TCount, typename U , uint32_t UCount> Point< std::remove_cv_t< T >, TCount > castor::operator* (Point< T, TCount > const & lhs, Coords< U, UCount > const & rhs)
operator*() [25/41]
template<typename T , uint32_t TCount, typename U , uint32_t UCount> Point< std::remove_cv_t< T >, TCount > castor::operator* (Point< T, TCount > const & lhs, Point< U, UCount > const & rhs)
operator*() [26/41]
template<typename T , uint32_t TCount> Point< std::remove_cv_t< T >, TCount > castor::operator* (Point< T, TCount > const & lhs, T const & rhs)
operator*() [27/41]
template<typename T , uint32_t TCount, typename U > Point< std::remove_cv_t< T >, TCount > castor::operator* (Point< T, TCount > const & lhs, U const * rhs)
operator*() [28/41]
template<typename T > QuaternionT< T > castor::operator* (QuaternionT< T > const & lhs, double rhs) inline
Multiplication operator.
Parameters
[in] lhs The Quaternion object to multiply
[in] rhs The scalar to multiply
Returns
The multiplication result
operator*() [29/41]
template<typename T > QuaternionT< T > castor::operator* (QuaternionT< T > const & lhs, float rhs) inline
Multiplication operator.
Parameters
[in] lhs The Quaternion object to multiply
[in] rhs The scalar to multiply
Returns
The multiplication result
operator*() [30/41]
template<typename T > QuaternionT< T > castor::operator* (QuaternionT< T > const & lhs, QuaternionT< T > const & rhs) inline
Multiplication operator.
Parameters
[in] lhs The first Quaternion object to multiply
[in] rhs The second Quaternion object to multiply
Returns
The multiplication result
operator*() [31/41]
template<typename T > T castor::operator* (RangedValue< T > const & lhs, RangedValue< T > const & rhs) inline noexcept
operator*() [32/41]
template<typename T > T castor::operator* (RangedValue< T > const & lhs, T const & rhs) inline noexcept
operator*() [33/41]
template<typename ComponentType , typename T > RgbaColourT< ComponentType > castor::operator* (RgbaColourT< ComponentType > const & lhs, T rhs)
Multiplication operator.
Parameters
[in] lhs,rhs The values to multiply
Returns
Result of lhs * rhs
operator*() [34/41]
template<typename ComponentType , typename T > RgbColourT< ComponentType > castor::operator* (RgbColourT< ComponentType > const & lhs, T rhs)
Multiplication operator.
Parameters
[in] lhs,rhs The values to multiply
Returns
Result of lhs * rhs
operator*() [35/41]
template<typename T , uint32_t Count, typename U , uint32_t Columns> SquareMatrix< T, Count > castor::operator* (SquareMatrix< T, Count > const & lhs, Matrix< U, Columns, Count > const & rhs)
operator*() [36/41]
template<typename T , uint32_t Count, typename U > SquareMatrix< T, Count > castor::operator* (SquareMatrix< T, Count > const & lhs, SquareMatrix< U, Count > const & rhs)
operator*() [37/41]
template<typename T , uint32_t Count, typename U > SquareMatrix< T, Count > castor::operator* (SquareMatrix< T, Count > const & lhs, T const & rhs)
operator*() [38/41]
template<typename T , uint32_t Count, typename U > SquareMatrix< T, Count > castor::operator* (SquareMatrix< T, Count > const & lhs, U const * rhs)
operator*() [39/41]
template<typename T , uint32_t Columns, uint32_t Rows, typename U > Matrix< T, Columns, Rows > castor::operator* (T const & lhs, Matrix< U, Columns, Rows > const & rhs)
operator*() [40/41]
template<typename T > T castor::operator* (T const & lhs, RangedValue< T > const & rhs) inline noexcept
operator*() [41/41]
template<typename T , uint32_t Count> SquareMatrix< T, Count > castor::operator* (T const & lhs, SquareMatrix< T, Count > const & rhs)
operator+() [1/35]
template<typename Type > AngleT< Type > castor::operator+ (AngleT< Type > const & lhs, AngleT< Type > const & rhs) inline noexcept
addition operator
Parameters
[in] lhs First operand
[in] rhs Second operand
Returns
Result of addition
operator+() [2/35]
CU_API float castor::operator+ (ColourComponent const & lhs, ColourComponent const & rhs)
addition operator
Parameters
[in] lhs,rhs The components to add
Returns
Result of lhs + rhs
operator+() [3/35]
template<typename T > float castor::operator+ (ColourComponent const & lhs, T const & rhs)
addition assignment operator
Parameters
[in] lhs,rhs The components to add
Returns
Result of lhs + rhs
operator+() [4/35]
template<PixelFormat PF> ConstPixelIterator< PF > castor::operator+ (ConstPixelIterator< PF > const & it, size_t offset) inline
operator+() [5/35]
template<typename T , uint32_t Count, typename U , uint32_t UCount> Point< std::remove_cv_t< T >, Count > castor::operator+ (Coords< T, Count > const & lhs, Coords< U, UCount > const & rhs)
operator+() [6/35]
template<typename T , uint32_t Count, typename U > Point< std::remove_cv_t< T >, Count > castor::operator+ (Coords< T, Count > const & lhs, T const & rhs)
operator+() [7/35]
template<typename T , uint32_t Count, typename U > Point< std::remove_cv_t< T >, Count > castor::operator+ (Coords< T, Count > const & lhs, U const * rhs)
operator+() [8/35]
template<typename T , uint32_t TCount, typename U , uint32_t UCount> Point< std::remove_cv_t< T >, TCount > castor::operator+ (Coords< T, TCount > const & lhs, Point< U, UCount > const & rhs)
operator+() [9/35]
CU_API float castor::operator+ (HdrColourComponent const & lhs, HdrColourComponent const & rhs)
addition operator
Parameters
[in] lhs,rhs The components to add
Returns
Result of lhs + rhs
operator+() [10/35]
template<typename T > float castor::operator+ (HdrColourComponent const & lhs, T const & rhs)
addition assignment operator
Parameters
[in] lhs,rhs The components to add
Returns
Result of lhs + rhs
operator+() [11/35]
template<typename TypeT > LengthT< TypeT > castor::operator+ (LengthT< TypeT > const & lhs, LengthT< TypeT > const & rhs) inline noexcept
operator+() [12/35]
template<typename TypeT > LengthT< TypeT > castor::operator+ (LengthT< TypeT > const & lhs, TypeT const & rhs) inline noexcept
operator+() [13/35]
template<typename T , uint32_t Columns, uint32_t Rows, typename U > Matrix< T, Columns, Rows > castor::operator+ (Matrix< T, Columns, Rows > const & lhs, Matrix< U, Columns, Rows > const & rhs)
name Arithmetic operators.
operator+() [14/35]
template<typename T , uint32_t Columns, uint32_t Rows, typename U > Matrix< T, Columns, Rows > castor::operator+ (Matrix< T, Columns, Rows > const & lhs, T const & rhs)
operator+() [15/35]
template<typename T , uint32_t Columns, uint32_t Rows, typename U > Matrix< T, Columns, Rows > castor::operator+ (Matrix< T, Columns, Rows > const & lhs, U const * rhs)
operator+() [16/35]
template<PixelFormat FT, PixelFormat FU> Pixel< FT > castor::operator+ (Pixel< FT > const & lhs, Pixel< FU > const & rhs)
operator+() [17/35]
template<PixelFormat PF> PixelIterator< PF > castor::operator+ (PixelIterator< PF > it, size_t offset) inline
operator+() [18/35]
template<typename T , uint32_t TCount, typename U , uint32_t UCount> Point< std::remove_cv_t< T >, TCount > castor::operator+ (Point< T, TCount > const & lhs, Coords< U, UCount > const & rhs)
operator+() [19/35]
template<typename T , uint32_t TCount, typename U , uint32_t UCount> Point< std::remove_cv_t< T >, TCount > castor::operator+ (Point< T, TCount > const & lhs, Point< U, UCount > const & rhs)
operator+() [20/35]
template<typename T , uint32_t TCount> Point< std::remove_cv_t< T >, TCount > castor::operator+ (Point< T, TCount > const & lhs, T const & rhs)
operator+() [21/35]
template<typename T , uint32_t TCount, typename U > Point< std::remove_cv_t< T >, TCount > castor::operator+ (Point< T, TCount > const & lhs, U const * rhs)
operator+() [22/35]
template<typename T > QuaternionT< T > castor::operator+ (QuaternionT< T > const & lhs, QuaternionT< T > const & rhs) inline
addition operator
Parameters
[in] lhs The first Quaternion object to add
[in] rhs The second Quaternion object to add
Returns
The addition result
operator+() [23/35]
template<typename T > T castor::operator+ (RangedValue< T > const & lhs, RangedValue< T > const & rhs) inline noexcept
operator+() [24/35]
template<typename T > T castor::operator+ (RangedValue< T > const & lhs, T const & rhs) inline noexcept
operator+() [25/35]
template<typename ComponentType > RgbaColourT< ComponentType > castor::operator+ (RgbaColourT< ComponentType > const & lhs, RgbaColourT< ComponentType > const & rhs) inline
addition operator
Parameters
[in] lhs,rhs The colours to add
Returns
Result of lhs + rhs
operator+() [26/35]
template<typename ComponentType , typename T > RgbaColourT< ComponentType > castor::operator+ (RgbaColourT< ComponentType > const & lhs, T rhs)
addition operator
Parameters
[in] lhs,rhs The values to add
Returns
Result of lhs + rhs
operator+() [27/35]
template<typename ComponentType > RgbColourT< ComponentType > castor::operator+ (RgbColourT< ComponentType > const & lhs, RgbColourT< ComponentType > const & rhs) inline
addition operator
Parameters
[in] lhs,rhs The colours to add
Returns
Result of lhs + rhs
operator+() [28/35]
template<typename ComponentType , typename T > RgbColourT< ComponentType > castor::operator+ (RgbColourT< ComponentType > const & lhs, T rhs)
addition operator
Parameters
[in] lhs,rhs The values to add
Returns
Result of lhs + rhs
operator+() [29/35]
template<typename T , uint32_t Count, typename U > SquareMatrix< T, Count > castor::operator+ (SquareMatrix< T, Count > const & lhs, SquareMatrix< U, Count > const & rhs)
name Arithmetic operators.
operator+() [30/35]
template<typename T , uint32_t Count, typename U > SquareMatrix< T, Count > castor::operator+ (SquareMatrix< T, Count > const & lhs, T const & rhs)
operator+() [31/35]
template<typename T , uint32_t Count, typename U > SquareMatrix< T, Count > castor::operator+ (SquareMatrix< T, Count > const & lhs, U const * rhs)
operator+() [32/35]
template<typename T , uint32_t Columns, uint32_t Rows, typename U > Matrix< T, Columns, Rows > castor::operator+ (T const & lhs, Matrix< U, Columns, Rows > const & rhs)
operator+() [33/35]
template<typename T > T castor::operator+ (T const & lhs, RangedValue< T > const & rhs) inline noexcept
operator+() [34/35]
template<typename T , uint32_t Count> SquareMatrix< T, Count > castor::operator+ (T const & lhs, SquareMatrix< T, Count > const & rhs)
operator+() [35/35]
template<typename TypeT > LengthT< TypeT > castor::operator+ (TypeT const & lhs, LengthT< TypeT > const & rhs) inline noexcept
operator-() [1/44]
template<typename Type > AngleT< Type > castor::operator- (AngleT< Type > const & lhs, AngleT< Type > const & rhs) inline noexcept
Substraction operator.
Parameters
[in] lhs First operand
[in] rhs Second operand
Returns
Result of substraction
operator-() [2/44]
CU_API float castor::operator- (ColourComponent const & lhs, ColourComponent const & rhs)
Subtraction operator.
Parameters
[in] lhs,rhs The components to subtract
Returns
Result of lhs - rhs
operator-() [3/44]
template<typename T > float castor::operator- (ColourComponent const & lhs, T const & rhs)
Substraction assignment operator.
Parameters
[in] lhs,rhs The components to subtract
Returns
Result of lhs - rhs
operator-() [4/44]
template<PixelFormat PF> ConstPixelIterator< PF > castor::operator- (ConstPixelIterator< PF > const & it, size_t offset) inline
operator-() [5/44]
template<PixelFormat PF> ConstPixelIterator< PF >::difference_type castor::operator- (ConstPixelIterator< PF > const & lhs, ConstPixelIterator< PF > const & rhs) inline
References castor::ConstPixelIterator< PF >::diffIt().
operator-() [6/44]
template<PixelFormat PF> ConstPixelIterator< PF >::difference_type castor::operator- (ConstPixelIterator< PF > const & lhs, PixelIterator< PF > const & rhs) inline
References castor::ConstPixelIterator< PF >::diffIt().
operator-() [7/44]
template<typename T , uint32_t Count, typename U , uint32_t UCount> Point< std::remove_cv_t< T >, Count > castor::operator- (Coords< T, Count > const & lhs, Coords< U, UCount > const & rhs)
operator-() [8/44]
template<typename T , uint32_t Count, typename U > Point< std::remove_cv_t< T >, Count > castor::operator- (Coords< T, Count > const & lhs, T const & rhs)
operator-() [9/44]
template<typename T , uint32_t Count, typename U > Point< std::remove_cv_t< T >, Count > castor::operator- (Coords< T, Count > const & lhs, U const * rhs)
operator-() [10/44]
template<typename T , uint32_t Count> Point< std::remove_cv_t< T >, Count > castor::operator- (Coords< T, Count > const & rhs)
name Arithmetic operators.
operator-() [11/44]
template<typename T , uint32_t TCount, typename U , uint32_t UCount> Point< std::remove_cv_t< T >, TCount > castor::operator- (Coords< T, TCount > const & lhs, Point< U, UCount > const & rhs)
operator-() [12/44]
CU_API float castor::operator- (HdrColourComponent const & lhs, HdrColourComponent const & rhs)
Subtraction operator.
Parameters
[in] lhs,rhs The components to subtract
Returns
Result of lhs - rhs
operator-() [13/44]
template<typename T > float castor::operator- (HdrColourComponent const & lhs, T const & rhs)
Substraction assignment operator.
Parameters
[in] lhs,rhs The components to subtract
Returns
Result of lhs - rhs
operator-() [14/44]
template<typename TypeT > LengthT< TypeT > castor::operator- (LengthT< TypeT > const & lhs, LengthT< TypeT > const & rhs) inline noexcept
operator-() [15/44]
template<typename TypeT > LengthT< TypeT > castor::operator- (LengthT< TypeT > const & lhs, TypeT const & rhs) inline noexcept
operator-() [16/44]
template<typename T , uint32_t Columns, uint32_t Rows, typename U > Matrix< T, Columns, Rows > castor::operator- (Matrix< T, Columns, Rows > const & lhs, Matrix< U, Columns, Rows > const & rhs)
operator-() [17/44]
template<typename T , uint32_t Columns, uint32_t Rows, typename U > Matrix< T, Columns, Rows > castor::operator- (Matrix< T, Columns, Rows > const & lhs, T const & rhs)
operator-() [18/44]
template<typename T , uint32_t Columns, uint32_t Rows, typename U > Matrix< T, Columns, Rows > castor::operator- (Matrix< T, Columns, Rows > const & lhs, U const * rhs)
operator-() [19/44]
template<typename T , uint32_t Columns, uint32_t Rows> Matrix< T, Columns, Rows > castor::operator- (Matrix< T, Columns, Rows > const & rhs)
operator-() [20/44]
template<PixelFormat FT, PixelFormat FU> Pixel< FT > castor::operator- (Pixel< FT > const & lhs, Pixel< FU > const & rhs)
operator-() [21/44]
template<PixelFormat PF> ConstPixelIterator< PF >::difference_type castor::operator- (PixelIterator< PF > const & lhs, ConstPixelIterator< PF > const & rhs) inline
References castor::ConstPixelIterator< PF >::diffIt().
operator-() [22/44]
template<PixelFormat PF> PixelIterator< PF >::difference_type castor::operator- (PixelIterator< PF > const & lhs, PixelIterator< PF > const & rhs) inline
References castor::PixelIterator< PF >::diffIt().
operator-() [23/44]
template<PixelFormat PF> PixelIterator< PF > castor::operator- (PixelIterator< PF > it, size_t offset) inline
operator-() [24/44]
template<typename T , uint32_t TCount, typename U , uint32_t UCount> Point< std::remove_cv_t< T >, TCount > castor::operator- (Point< T, TCount > const & lhs, Coords< U, UCount > const & rhs)
operator-() [25/44]
template<typename T , uint32_t TCount, typename U , uint32_t UCount> Point< std::remove_cv_t< T >, TCount > castor::operator- (Point< T, TCount > const & lhs, Point< U, UCount > const & rhs)
operator-() [26/44]
template<typename T , uint32_t TCount> Point< std::remove_cv_t< T >, TCount > castor::operator- (Point< T, TCount > const & lhs, T const & rhs)
operator-() [27/44]
template<typename T , uint32_t TCount, typename U > Point< std::remove_cv_t< T >, TCount > castor::operator- (Point< T, TCount > const & lhs, U const * rhs)
operator-() [28/44]
template<typename T , uint32_t TCount> Point< std::remove_cv_t< T >, TCount > castor::operator- (Point< T, TCount > const & rhs)
name Arithmetic operators.
operator-() [29/44]
template<typename T > QuaternionT< T > castor::operator- (QuaternionT< T > const & lhs, QuaternionT< T > const & rhs) inline
Substraction operator.
Parameters
[in] lhs The first Quaternion object to subtract
[in] rhs The second Quaternion object to subtract
Returns
The substraction result
operator-() [30/44]
template<typename T > QuaternionT< T > castor::operator- (QuaternionT< T > const & quat) inline
Negation operator.
Parameters
[in] quat The Quaternion object to negate
Returns
The negation result
operator-() [31/44]
template<typename T > T castor::operator- (RangedValue< T > const & lhs, RangedValue< T > const & rhs) inline noexcept
operator-() [32/44]
template<typename T > T castor::operator- (RangedValue< T > const & lhs, T const & rhs) inline noexcept
operator-() [33/44]
template<typename ComponentType > RgbaColourT< ComponentType > castor::operator- (RgbaColourT< ComponentType > const & lhs, RgbaColourT< ComponentType > const & rhs) inline
Substraction operator.
Parameters
[in] lhs,rhs The colours to subtract
Returns
Result of lhs - rhs
operator-() [34/44]
template<typename ComponentType , typename T > RgbaColourT< ComponentType > castor::operator- (RgbaColourT< ComponentType > const & lhs, T rhs)
Subtraction operator.
Parameters
[in] lhs,rhs The values to subtract
Returns
Result of lhs - rhs
operator-() [35/44]
template<typename ComponentType > RgbColourT< ComponentType > castor::operator- (RgbColourT< ComponentType > const & lhs, RgbColourT< ComponentType > const & rhs) inline
Substraction operator.
Parameters
[in] lhs,rhs The colours to subtract
Returns
Result of lhs - rhs
operator-() [36/44]
template<typename ComponentType , typename T > RgbColourT< ComponentType > castor::operator- (RgbColourT< ComponentType > const & lhs, T rhs)
Subtraction operator.
Parameters
[in] lhs,rhs The values to subtract
Returns
Result of lhs - rhs
operator-() [37/44]
template<typename T , uint32_t Count, typename U > SquareMatrix< T, Count > castor::operator- (SquareMatrix< T, Count > const & lhs, SquareMatrix< U, Count > const & rhs)
operator-() [38/44]
template<typename T , uint32_t Count, typename U > SquareMatrix< T, Count > castor::operator- (SquareMatrix< T, Count > const & lhs, T const & rhs)
operator-() [39/44]
template<typename T , uint32_t Count, typename U > SquareMatrix< T, Count > castor::operator- (SquareMatrix< T, Count > const & lhs, U const * rhs)
operator-() [40/44]
template<typename T , uint32_t Count> SquareMatrix< T, Count > castor::operator- (SquareMatrix< T, Count > const & rhs)
operator-() [41/44]
template<typename T , uint32_t Columns, uint32_t Rows, typename U > Matrix< T, Columns, Rows > castor::operator- (T const & lhs, Matrix< U, Columns, Rows > const & rhs)
operator-() [42/44]
template<typename T > T castor::operator- (T const & lhs, RangedValue< T > const & rhs) inline noexcept
operator-() [43/44]
template<typename T , uint32_t Count> SquareMatrix< T, Count > castor::operator- (T const & lhs, SquareMatrix< T, Count > const & rhs)
operator-() [44/44]
template<typename TypeT > LengthT< TypeT > castor::operator- (TypeT const & lhs, LengthT< TypeT > const & rhs) inline noexcept
operator/() [1/30]
template<typename Type > AngleT< Type > castor::operator/ (AngleT< Type > const & lhs, AngleT< Type > const & rhs) inline noexcept
Division operator.
Parameters
[in] lhs First operand
[in] rhs Second operand
Returns
Result of division
operator/() [2/30]
template<typename Type > AngleT< Type > castor::operator/ (AngleT< Type > const & lhs, double rhs) inline noexcept
Division operator.
Parameters
[in] lhs First operand
[in] rhs Second operand
Returns
Result of division
operator/() [3/30]
CU_API Path castor::operator/ (char const * lhs, Path const & rhs)
adds a string to a path. Adds the separator if needed
Parameters
[in] lhs The path to add
[in] rhs The first path to add
operator/() [4/30]
CU_API float castor::operator/ (ColourComponent const & lhs, ColourComponent const & rhs)
Division operator.
Parameters
[in] lhs,rhs The components to divide
Returns
Result of lhs / rhs
operator/() [5/30]
template<typename T > float castor::operator/ (ColourComponent const & lhs, T const & rhs)
Division assignment operator.
Parameters
[in] lhs,rhs The components to divide
Returns
Result of lhs / rhs
operator/() [6/30]
template<typename T , uint32_t Count, typename U , uint32_t UCount> Point< std::remove_cv_t< T >, Count > castor::operator/ (Coords< T, Count > const & lhs, Coords< U, UCount > const & rhs)
operator/() [7/30]
template<typename T , uint32_t Count> Point< std::remove_cv_t< T >, Count > castor::operator/ (Coords< T, Count > const & lhs, T const & rhs)
operator/() [8/30]
template<typename T , uint32_t Count, typename U > Point< std::remove_cv_t< T >, Count > castor::operator/ (Coords< T, Count > const & lhs, U const * rhs)
operator/() [9/30]
template<typename T , uint32_t TCount, typename U , uint32_t UCount> Point< std::remove_cv_t< T >, TCount > castor::operator/ (Coords< T, TCount > const & lhs, Point< U, UCount > const & rhs)
operator/() [10/30]
CU_API float castor::operator/ (HdrColourComponent const & lhs, HdrColourComponent const & rhs)
Division operator.
Parameters
[in] lhs,rhs The components to divide
Returns
Result of lhs / rhs
operator/() [11/30]
template<typename T > float castor::operator/ (HdrColourComponent const & lhs, T const & rhs)
Division assignment operator.
Parameters
[in] lhs,rhs The components to divide
Returns
Result of lhs / rhs
operator/() [12/30]
template<typename TypeT > LengthT< TypeT > castor::operator/ (LengthT< TypeT > const & lhs, double rhs) inline noexcept
operator/() [13/30]
template<typename T , uint32_t Columns, uint32_t Rows, typename U > Matrix< T, Columns, Rows > castor::operator/ (Matrix< T, Columns, Rows > const & lhs, T const & rhs)
operator/() [14/30]
CU_API Path castor::operator/ (Path const & lhs, char const * rhs)
adds a string to a path. Adds the separator if needed
Parameters
[in] lhs The first path to add
[in] rhs The path to add
operator/() [15/30]
CU_API Path castor::operator/ (Path const & lhs, Path const & rhs)
Appends 2 paths. adds the separator if needed.
Parameters
[in] lhs The first path to add
[in] rhs The second path to add
operator/() [16/30]
CU_API Path castor::operator/ (Path const & lhs, String const & rhs)
adds a string to a path. Adds the separator if needed
Parameters
[in] lhs The first path to add
[in] rhs The path to add
operator/() [17/30]
CU_API Path castor::operator/ (Path const & lhs, wchar_t const * rhs)
adds a string to a path. Adds the separator if needed
Parameters
[in] lhs The first path to add
[in] rhs The path to add
operator/() [18/30]
template<PixelFormat FT, PixelFormat FU> Pixel< FT > castor::operator/ (Pixel< FT > const & lhs, Pixel< FU > const & rhs)
operator/() [19/30]
template<typename T , uint32_t TCount, typename U , uint32_t UCount> Point< std::remove_cv_t< T >, TCount > castor::operator/ (Point< T, TCount > const & lhs, Coords< U, UCount > const & rhs)
operator/() [20/30]
template<typename T , uint32_t TCount, typename U , uint32_t UCount> Point< std::remove_cv_t< T >, TCount > castor::operator/ (Point< T, TCount > const & lhs, Point< U, UCount > const & rhs)
operator/() [21/30]
template<typename T , uint32_t TCount> Point< std::remove_cv_t< T >, TCount > castor::operator/ (Point< T, TCount > const & lhs, T const & rhs)
operator/() [22/30]
template<typename T , uint32_t TCount, typename U > Point< std::remove_cv_t< T >, TCount > castor::operator/ (Point< T, TCount > const & lhs, U const * rhs)
operator/() [23/30]
template<typename T > T castor::operator/ (RangedValue< T > const & lhs, RangedValue< T > const & rhs) inline noexcept
operator/() [24/30]
template<typename T > T castor::operator/ (RangedValue< T > const & lhs, T const & rhs) inline noexcept
operator/() [25/30]
template<typename ComponentType , typename T > RgbaColourT< ComponentType > castor::operator/ (RgbaColourT< ComponentType > const & lhs, T rhs)
Division operator.
Parameters
[in] lhs,rhs The values to divide
Returns
Result of lhs / rhs
operator/() [26/30]
template<typename ComponentType , typename T > RgbColourT< ComponentType > castor::operator/ (RgbColourT< ComponentType > const & lhs, T rhs)
Division operator.
Parameters
[in] lhs,rhs The values to divide
Returns
Result of lhs / rhs
operator/() [27/30]
template<typename T , uint32_t Count, typename U > SquareMatrix< T, Count > castor::operator/ (SquareMatrix< T, Count > const & lhs, T const & rhs)
operator/() [28/30]
CU_API Path castor::operator/ (String const & lhs, Path const & rhs)
adds a string to a path. Adds the separator if needed
Parameters
[in] lhs The path to add
[in] rhs The first path to add
operator/() [29/30]
template<typename T > T castor::operator/ (T const & lhs, RangedValue< T > const & rhs) inline noexcept
operator/() [30/30]
CU_API Path castor::operator/ (wchar_t const * lhs, Path const & rhs)
adds a string to a path. Adds the separator if needed
Parameters
[in] lhs The path to add
[in] rhs The first path to add
operator<() [1/7]
template<typename Type > bool castor::operator< (AngleT< Type > const & lhs, AngleT< Type > const & rhs) inline noexcept
"Less than" operator
Parameters
[in] lhs First operand
[in] rhs Second operand
Returns
true if lhs is less than rhs.
operator<() [2/7]
bool castor::operator< (Glyph const & lhs, Glyph const & rhs) inline
Less than comparison operator.
Parameters
[in] lhs,rhs The values to compare.
operator<() [3/7]
template<typename TypeT > bool castor::operator< (LengthT< TypeT > const & lhs, LengthT< TypeT > const & rhs) inline noexcept
operator<() [4/7]
template<typename T > bool castor::operator< (RangedValue< T > const & lhs, RangedValue< T > const & rhs) inline noexcept
operator<() [5/7]
template<typename T > bool castor::operator< (RangedValue< T > const & lhs, T const & rhs) inline noexcept
operator<() [6/7]
template<typename ValueT , typename DurationT , typename TraitsT > bool castor::operator< (SpeedT< ValueT, DurationT, TraitsT > const & lhs, SpeedT< ValueT, DurationT, TraitsT > const & rhs)
operator<() [7/7]
template<typename T > bool castor::operator< (T const & lhs, RangedValue< T > const & rhs) inline noexcept
operator<<() [1/15]
template<typename T > BinaryFile & castor::operator<< (BinaryFile & file, T const & toWrite)
open mode dependant write function
Parameters
[in] file The file
[in] toWrite The data to write in the file
Returns
A reference to this file
operator<<() [2/15]
template<typename BlockTypeT > DynamicBitsetT< BlockTypeT > castor::operator<< (DynamicBitsetT< BlockTypeT > const & lhs, int rhs) inline
name Bit operations.
operator<<() [3/15]
CU_API OutputStream & castor::operator<< (OutputStream & stream, CpuInformations const & object)
Output stream operator.
Parameters
[in,out] stream The stream.
[in] object The object to put in the stream.
Returns
The stream.
operator<<() [4/15]
Size castor::operator<< (Size const & lhs, uint32_t rhs) inline noexcept
operator<<() [5/15]
template<typename CharT , typename T , uint32_t Columns, uint32_t Rows> std::basic_ostream< CharT > & castor::operator<< (std::basic_ostream< CharT > & stream, Matrix< T, Columns, Rows > const & matrix)
operator<<() [6/15]
template<typename CharT , typename T > std::basic_ostream< CharT > & castor::operator<< (std::basic_ostream< CharT > & stream, QuaternionT< T > const & quat) inline
Stream operator.
Parameters
[in,out] stream The stream.
[in] quat The Quaternion object to put in stream.
Returns
The stream.
operator<<() [7/15]
template<typename CharT , typename T , uint32_t Count> std::basic_ostream< CharT > & castor::operator<< (std::basic_ostream< CharT > & streamOut, SquareMatrix< T, Count > const & matrix)
name Stream operators.
operator<<() [8/15]
template<typename T , uint32_t Count, typename CharType > std::basic_ostream< CharType > & castor::operator<< (std::basic_ostream< CharType > & out, Coords< T, Count > const & in)
operator<<() [9/15]
template<typename T , uint32_t TCount, typename CharType > std::basic_ostream< CharType > & castor::operator<< (std::basic_ostream< CharType > & out, Point< T, TCount > const & in)
operator<<() [10/15]
template<typename CharType , typename PrefixType > std::basic_ostream< CharType > & castor::operator<< (std::basic_ostream< CharType > & stream, format::BasePrefixer< CharType, PrefixType > const &) inline
Stream operator.
Remarks
Initializes the stream in order to prefix it.
Parameters
[in] stream The stream.
operator<<() [11/15]
template<typename CharType > std::basic_ostream< CharType > & castor::operator<< (std::basic_ostream< CharType > & stream, format::Indent const & ind) inline
Stream operator.
Remarks
Initializes the stream in order to indent it
Parameters
[in] stream The stream
[in] ind The indent
operator<<() [12/15]
template<typename T , uint32_t Count> String & castor::operator<< (String & out, Coords< T, Count > const & in)
name Stream operators.
operator<<() [13/15]
template<typename T , uint32_t TCount> String & castor::operator<< (String & out, Point< T, TCount > const & in)
name Stream operators.
operator<<() [14/15]
template<typename T , uint32_t Columns, uint32_t Rows> String & castor::operator<< (String & stream, Matrix< T, Columns, Rows > const & matrix)
name Stream operators.
operator<<() [15/15]
template<typename T > TextFile & castor::operator<< (TextFile & file, T const & toWrite)
open mode dependant write function
Parameters
[in] file The file
[in] toWrite The data to write in the file
Returns
A reference to this file
operator<=() [1/7]
template<typename Type > bool castor::operator<= (AngleT< Type > const & lhs, AngleT< Type > const & rhs) inline noexcept
"Less than or equal to" operator
Parameters
[in] lhs First operand
[in] rhs Second operand
Returns
true if lhs is less than or equal to rhs.
operator<=() [2/7]
bool castor::operator<= (Glyph const & lhs, Glyph const & rhs) inline
Less than or equal to comparison operator.
Parameters
[in] lhs,rhs The values to compare.
operator<=() [3/7]
template<typename TypeT > bool castor::operator<= (LengthT< TypeT > const & lhs, LengthT< TypeT > const & rhs) inline noexcept
operator<=() [4/7]
template<typename T > bool castor::operator<= (RangedValue< T > const & lhs, RangedValue< T > const & rhs) inline noexcept
operator<=() [5/7]
template<typename T > bool castor::operator<= (RangedValue< T > const & lhs, T const & rhs) inline noexcept
operator<=() [6/7]
template<typename ValueT , typename DurationT , typename TraitsT > bool castor::operator<= (SpeedT< ValueT, DurationT, TraitsT > const & lhs, SpeedT< ValueT, DurationT, TraitsT > const & rhs)
operator<=() [7/7]
template<typename T > bool castor::operator<= (T const & lhs, RangedValue< T > const & rhs) inline noexcept
operator==() [1/35]
template<typename Type > bool castor::operator== (AngleT< Type > const & lhs, AngleT< Type > const & rhs) inline noexcept
Equality operator.
Parameters
[in] lhs First operand
[in] rhs Second operand
Returns
true if lhs is equal to rhs
operator==() [2/35]
template<typename IterT > bool castor::operator== (ArrayView< IterT > const & lhs, ArrayView< IterT > const & rhs)
Referenced by operator!=(), operator!=(), operator!=(), operator!=(), operator!=(), and operator!=().
operator==() [3/35]
bool castor::operator== (BoundingBox const & lhs, BoundingBox const & rhs) inline
operator==() [4/35]
bool castor::operator== (BoundingSphere const & lhs, BoundingSphere const & rhs) inline
operator==() [5/35]
template<typename ValueT , typename ControlT > bool castor::operator== (ChangeTrackedT< ValueT, ControlT > const & lhs, ChangeTrackedT< ValueT, ControlT > const & rhs)
operator==() [6/35]
template<typename ValueT , typename ControlT > bool castor::operator== (ChangeTrackedT< ValueT, ControlT > const & lhs, ValueT const & rhs)
operator==() [7/35]
CU_API bool castor::operator== (ColourComponent const & lhs, ColourComponent const & rhs)
Equality operator.
Parameters
[in] lhs,rhs The components to compare
operator==() [8/35]
template<typename T , uint32_t Count, typename U , uint32_t UCount> bool castor::operator== (Coords< T, Count > const & lhs, Coords< U, UCount > const & rhs)
name Comparison operators.
operator==() [9/35]
template<typename T , uint32_t TCount, typename U , uint32_t UCount> bool castor::operator== (Coords< T, TCount > const & lhs, Point< U, UCount > const & rhs)
operator==() [10/35]
template<typename BlockTypeT > bool castor::operator== (DynamicBitsetT< BlockTypeT > const & lhs, DynamicBitsetT< BlockTypeT > const & rhs) inline
name Logic operators.
operator==() [11/35]
template<typename FlagType > constexpr bool castor::operator== (FlagCombination< FlagType > const & lhs, FlagCombination< FlagType > const & rhs) constexpr noexcept
operator==() [12/35]
template<typename FlagType > constexpr bool castor::operator== (FlagCombination< FlagType > const & lhs, FlagType const & rhs) constexpr noexcept
operator==() [13/35]
template<typename FlagTypeT , typename IteratorTraitsT > constexpr bool castor::operator== (FlagIterator< FlagTypeT, IteratorTraitsT > const & lhs, FlagIterator< FlagTypeT, IteratorTraitsT > const & rhs) constexpr
operator==() [14/35]
bool castor::operator== (Glyph const & lhs, Glyph const & rhs) inline
Equality comparison operator.
Parameters
[in] lhs,rhs The values to compare.
operator==() [15/35]
template<typename ValueT , typename ControlT > bool castor::operator== (GroupChangeTrackedT< ValueT, ControlT > const & lhs, GroupChangeTrackedT< ValueT, ControlT > const & rhs)
operator==() [16/35]
template<typename ValueT , typename ControlT > bool castor::operator== (GroupChangeTrackedT< ValueT, ControlT > const & lhs, ValueT const & rhs)
operator==() [17/35]
CU_API bool castor::operator== (HdrColourComponent const & lhs, HdrColourComponent const & rhs)
Equality operator.
Parameters
[in] lhs,rhs The components to compare
operator==() [18/35]
template<typename TypeT > bool castor::operator== (LengthT< TypeT > const & lhs, LengthT< TypeT > const & rhs) inline noexcept
operator==() [19/35]
template<typename T , uint32_t Columns, uint32_t Rows> bool castor::operator== (Matrix< T, Columns, Rows > const & lhs, Matrix< T, Columns, Rows > const & rhs)
name Logic operators.
operator==() [20/35]
template<PixelFormat FT, PixelFormat FU> bool castor::operator== (Pixel< FT > const & lhs, Pixel< FU > const & rhs)
Equality operator.
Parameters
[in] lhs,rhs The pixels to compare
Returns
true if points have same dimensions and same values
operator==() [21/35]
CU_API bool castor::operator== (PlaneEquation const & lhs, PlaneEquation const & rhs)
Checks if this plane is equal to another one.
Remarks
A plane is equal to another one if it is parallel to it and if normals and d coeff are equal
operator==() [22/35]
template<typename T , uint32_t TCount, typename U , uint32_t UCount> bool castor::operator== (Point< T, TCount > const & lhs, Coords< U, UCount > const & rhs)
operator==() [23/35]
template<typename T , uint32_t TCount, typename U , uint32_t UCount> bool castor::operator== (Point< T, TCount > const & lhs, Point< U, UCount > const & rhs)
name Logic operators.
operator==() [24/35]
CU_API bool castor::operator== (Position const & a, Position const & b)
Equality operator.
Parameters
[in] a,b The positions to compare
Returns
true if positions have same coordinates
operator==() [25/35]
template<typename T > bool castor::operator== (RangedValue< T > const & lhs, RangedValue< T > const & rhs) inline noexcept
operator==() [26/35]
template<typename T > bool castor::operator== (RangedValue< T > const & lhs, T const & rhs) inline noexcept
operator==() [27/35]
template<typename ComponentType > bool castor::operator== (RgbaColourT< ComponentType > const & lhs, RgbaColourT< ComponentType > const & rhs) inline
Equality operator.
Parameters
[in] lhs,rhs The colours to compare
operator==() [28/35]
template<typename ComponentType > bool castor::operator== (RgbColourT< ComponentType > const & lhs, RgbColourT< ComponentType > const & rhs) inline
Equality operator.
Parameters
[in] lhs,rhs The colours to compare
operator==() [29/35]
CU_API bool castor::operator== (Size const & a, Size const & b) noexcept
Equality operator.
Parameters
[in] a,b The sizes to compare
Returns
true if sizes have same dimensions
operator==() [30/35]
template<typename ValueT , typename DurationT , typename TraitsT > bool castor::operator== (SpeedT< ValueT, DurationT, TraitsT > const & lhs, SpeedT< ValueT, DurationT, TraitsT > const & rhs)
operator==() [31/35]
template<typename T , uint32_t Count> bool castor::operator== (SquareMatrix< T, Count > const & lhs, SquareMatrix< T, Count > const & rhs)
name Logic operators.
operator==() [32/35]
template<typename T > bool castor::operator== (T const & lhs, RangedValue< T > const & rhs) inline noexcept
operator==() [33/35]
template<typename BlockTypeT > bool castor::operator== (typename DynamicBitsetT< BlockTypeT >::Bit const & lhs, typename DynamicBitsetT< BlockTypeT >::Bit const & rhs) inline
name Logic operators.
operator==() [34/35]
template<typename ValueT , typename ControlT > bool castor::operator== (ValueT const & lhs, ChangeTrackedT< ValueT, ControlT > const & rhs)
operator==() [35/35]
template<typename ValueT , typename ControlT > bool castor::operator== (ValueT const & lhs, GroupChangeTrackedT< ValueT, ControlT > const & rhs)
operator>() [1/7]
template<typename Type > bool castor::operator> (AngleT< Type > const & lhs, AngleT< Type > const & rhs) inline noexcept
"Greater than" operator
Parameters
[in] lhs First operand
[in] rhs Second operand
Returns
true if lhs is greater than rhs.
operator>() [2/7]
bool castor::operator> (Glyph const & lhs, Glyph const & rhs) inline
Greater than comparison operator.
Parameters
[in] lhs,rhs The values to compare.
operator>() [3/7]
template<typename TypeT > bool castor::operator> (LengthT< TypeT > const & lhs, LengthT< TypeT > const & rhs) inline noexcept
operator>() [4/7]
template<typename T > bool castor::operator> (RangedValue< T > const & lhs, RangedValue< T > const & rhs) inline noexcept
operator>() [5/7]
template<typename T > bool castor::operator> (RangedValue< T > const & lhs, T const & rhs) inline noexcept
operator>() [6/7]
template<typename ValueT , typename DurationT , typename TraitsT > bool castor::operator> (SpeedT< ValueT, DurationT, TraitsT > const & lhs, SpeedT< ValueT, DurationT, TraitsT > const & rhs)
operator>() [7/7]
template<typename T > bool castor::operator> (T const & lhs, RangedValue< T > const & rhs) inline noexcept
operator>=() [1/7]
template<typename Type > bool castor::operator>= (AngleT< Type > const & lhs, AngleT< Type > const & rhs) inline noexcept
"Greater than or equal to" operator
Parameters
[in] lhs First operand
[in] rhs Second operand
Returns
true if lhs is greater than or equal to rhs.
operator>=() [2/7]
bool castor::operator>= (Glyph const & lhs, Glyph const & rhs) inline
Greater than or equal to comparison operator.
Parameters
[in] lhs,rhs The values to compare.
operator>=() [3/7]
template<typename TypeT > bool castor::operator>= (LengthT< TypeT > const & lhs, LengthT< TypeT > const & rhs) inline noexcept
operator>=() [4/7]
template<typename T > bool castor::operator>= (RangedValue< T > const & lhs, RangedValue< T > const & rhs) inline noexcept
operator>=() [5/7]
template<typename T > bool castor::operator>= (RangedValue< T > const & lhs, T const & rhs) inline noexcept
operator>=() [6/7]
template<typename ValueT , typename DurationT , typename TraitsT > bool castor::operator>= (SpeedT< ValueT, DurationT, TraitsT > const & lhs, SpeedT< ValueT, DurationT, TraitsT > const & rhs)
operator>=() [7/7]
template<typename T > bool castor::operator>= (T const & lhs, RangedValue< T > const & rhs) inline noexcept
operator>>() [1/11]
template<typename T > BinaryFile & castor::operator>> (BinaryFile & file, T & toRead)
open mode dependant read function
Parameters
[in] file The file
[out] toRead The data to read from the file
Returns
A reference to this file
operator>>() [2/11]
template<typename BlockTypeT > DynamicBitsetT< BlockTypeT > castor::operator>> (DynamicBitsetT< BlockTypeT > const & lhs, int rhs) inline
operator>>() [3/11]
Size castor::operator>> (Size const & lhs, uint32_t rhs) inline noexcept
operator>>() [4/11]
template<typename CharT , typename T , uint32_t Columns, uint32_t Rows> std::basic_istream< CharT > & castor::operator>> (std::basic_istream< CharT > & stream, Matrix< T, Columns, Rows > & matrix)
operator>>() [5/11]
template<typename CharT , typename T , uint32_t Count> std::basic_istream< CharT > & castor::operator>> (std::basic_istream< CharT > & streamIn, SquareMatrix< T, Count > & matrix)
operator>>() [6/11]
template<typename T , uint32_t Count, typename CharType > std::basic_istream< CharType > & castor::operator>> (std::basic_istream< CharType > & in, Coords< T, Count > & out)
operator>>() [7/11]
template<typename T , uint32_t TCount, typename CharType > std::basic_istream< CharType > & castor::operator>> (std::basic_istream< CharType > & in, Point< T, TCount > & out)
operator>>() [8/11]
template<typename T , uint32_t Count> String & castor::operator>> (String & in, Coords< T, Count > & out)
operator>>() [9/11]
template<typename T , uint32_t TCount> String & castor::operator>> (String & in, Point< T, TCount > & out)
operator>>() [10/11]
template<typename T , uint32_t Columns, uint32_t Rows> String & castor::operator>> (String & stream, Matrix< T, Columns, Rows > & matrix)
operator>>() [11/11]
template<typename T > TextFile & castor::operator>> (TextFile & file, T & toRead)
open mode dependant read function
Parameters
[in] file The file
[out] toRead The data to read from the file
Returns
A reference to this file
operator^() [1/5]
template<typename BlockTypeT > DynamicBitsetT< BlockTypeT > castor::operator^ (DynamicBitsetT< BlockTypeT > const & lhs, DynamicBitsetT< BlockTypeT > const & rhs) inline
operator^() [2/5]
template<typename FlagType > constexpr FlagCombination< FlagType > castor::operator^ (FlagCombination< FlagType > const & lhs, FlagCombination< FlagType > const & rhs) constexpr noexcept
operator^() [3/5]
template<typename FlagType > constexpr FlagCombination< FlagType > castor::operator^ (FlagCombination< FlagType > const & lhs, FlagType const & rhs) constexpr noexcept
operator^() [4/5]
template<typename FlagType > constexpr FlagCombination< FlagType > castor::operator^ (FlagCombination< FlagType > const & lhs, typename FlagCombination< FlagType >::BaseType const & rhs) constexpr noexcept
operator^() [5/5]
template<typename BlockTypeT > DynamicBitsetT< BlockTypeT >::Bit castor::operator^ (typename DynamicBitsetT< BlockTypeT >::Bit const & lhs, bool rhs)
operator|() [1/5]
template<typename BlockTypeT > DynamicBitsetT< BlockTypeT > castor::operator| (DynamicBitsetT< BlockTypeT > const & lhs, DynamicBitsetT< BlockTypeT > const & rhs) inline
operator|() [2/5]
template<typename FlagType > constexpr FlagCombination< FlagType > castor::operator| (FlagCombination< FlagType > const & lhs, FlagCombination< FlagType > const & rhs) constexpr noexcept
operator|() [3/5]
template<typename FlagType > constexpr FlagCombination< FlagType > castor::operator| (FlagCombination< FlagType > const & lhs, FlagType const & rhs) constexpr noexcept
operator|() [4/5]
template<typename FlagType > constexpr FlagCombination< FlagType > castor::operator| (FlagCombination< FlagType > const & lhs, typename FlagCombination< FlagType >::BaseType const & rhs) constexpr noexcept
operator|() [5/5]
template<typename BlockTypeT > DynamicBitsetT< BlockTypeT >::Bit castor::operator| (typename DynamicBitsetT< BlockTypeT >::Bit const & lhs, bool rhs)
name Bit operations.
pointCast()
template<typename DstCompT , typename SrcT > PointTypeT< SrcT, DstCompT > castor::pointCast (SrcT const & src)
ptrCast() [1/2]
template<typename TypeU , typename TypeT > RawUniquePtr< TypeU > castor::ptrCast (RawUniquePtr< TypeT > ptr)
ptrCast() [2/2]
template<typename TypeU , typename TypeT > UniquePtr< TypeU > castor::ptrCast (UniquePtr< TypeT > ptr)
ptrRefCast() [1/2]
template<typename TypeU , typename TypeT > RawUniquePtr< TypeU > castor::ptrRefCast (RawUniquePtr< TypeT > & ptr)
ptrRefCast() [2/2]
template<typename TypeU , typename TypeT > UniquePtr< TypeU > castor::ptrRefCast (UniquePtr< TypeT > & ptr)
remFlag() [1/2]
template<typename FlagType > constexpr FlagCombination< FlagType > & castor::remFlag (FlagCombination< FlagType > & value, FlagType const & flag) constexpr noexcept
Removes a flag from the given value.
Parameters
[in,out] value The value.
[in] flag The flag to remove.
Returns
The value.
remFlag() [2/2]
template<typename FlagType > constexpr FlagCombination< FlagType > castor::remFlag (FlagCombination< FlagType > const & value, FlagType const & flag) constexpr noexcept
Removes a flag from the given value.
Parameters
[in] value The value.
[in] flag The flag to remove.
Returns
The new value.
remFlags()
template<typename FlagType > constexpr FlagCombination< FlagType > & castor::remFlags (FlagCombination< FlagType > & value, FlagCombination< FlagType > const & flags) constexpr noexcept
Removes a flag combination from the given value.
Parameters
[in,out] value The value.
[in] flags The flags to remove.
Returns
The value.
setA16F()
template<PixelFormat PFT> void castor::setA16F (uint8_t * buffer, int16_t value)
setA16S()
template<PixelFormat PFT> void castor::setA16S (uint8_t * buffer, int16_t value)
setA16U()
template<PixelFormat PFT> void castor::setA16U (uint8_t * buffer, uint16_t value)
setA32F() [1/2]
template<PixelFormat PF> void castor::setA32F (Pixel< PF > & pixel, float value)
Function to define pixel alpha component in float.
Parameters
[in] pixel The pixel
[in] value The component value
setA32F() [2/2]
template<PixelFormat PFT> void castor::setA32F (uint8_t * buffer, float value)
setA32S()
template<PixelFormat PFT> void castor::setA32S (uint8_t * buffer, int32_t value)
setA32U()
template<PixelFormat PFT> void castor::setA32U (uint8_t * buffer, uint32_t value)
setA64F()
template<PixelFormat PFT> void castor::setA64F (uint8_t * buffer, double value)
setA64S()
template<PixelFormat PFT> void castor::setA64S (uint8_t * buffer, int64_t value)
setA64U()
template<PixelFormat PFT> void castor::setA64U (uint8_t * buffer, uint64_t value)
setA8S()
template<PixelFormat PFT> void castor::setA8S (uint8_t * buffer, int8_t value)
setA8U() [1/2]
template<PixelFormat PF> void castor::setA8U (Pixel< PF > & pixel, uint8_t value)
Function to define pixel alpha component in byte.
Parameters
[in] pixel The pixel
[in] value The component value
setA8U() [2/2]
template<PixelFormat PFT> void castor::setA8U (uint8_t * buffer, uint8_t value)
setB16F()
template<PixelFormat PFT> void castor::setB16F (uint8_t * buffer, int16_t value)
setB16S()
template<PixelFormat PFT> void castor::setB16S (uint8_t * buffer, int16_t value)
setB16U()
template<PixelFormat PFT> void castor::setB16U (uint8_t * buffer, uint16_t value)
setB32F() [1/2]
template<PixelFormat PF> void castor::setB32F (Pixel< PF > & pixel, float value)
Function to define pixel blue component in float.
Parameters
[in] pixel The pixel
[in] value The component value
setB32F() [2/2]
template<PixelFormat PFT> void castor::setB32F (uint8_t * buffer, float value)
setB32S()
template<PixelFormat PFT> void castor::setB32S (uint8_t * buffer, int32_t value)
setB32U()
template<PixelFormat PFT> void castor::setB32U (uint8_t * buffer, uint32_t value)
setB64F()
template<PixelFormat PFT> void castor::setB64F (uint8_t * buffer, double value)
setB64S()
template<PixelFormat PFT> void castor::setB64S (uint8_t * buffer, int64_t value)
setB64U()
template<PixelFormat PFT> void castor::setB64U (uint8_t * buffer, uint64_t value)
setB8S()
template<PixelFormat PFT> void castor::setB8S (uint8_t * buffer, int8_t value)
setB8U() [1/2]
template<PixelFormat PF> void castor::setB8U (Pixel< PF > & pixel, uint8_t value)
Function to define pixel blue component in byte.
Parameters
[in] pixel The pixel
[in] value The component value
setB8U() [2/2]
template<PixelFormat PFT> void castor::setB8U (uint8_t * buffer, uint8_t value)
setD16U() [1/2]
template<PixelFormat PF> void castor::setD16U (Pixel< PF > & pixel, uint16_t value)
Function to define pixel depth component in uint16_t.
Parameters
[in] pixel The pixel
[in] value The component value
setD16U() [2/2]
template<PixelFormat PFT> void castor::setD16U (uint8_t * buffer, uint16_t value)
setD24U() [1/2]
template<PixelFormat PF> void castor::setD24U (Pixel< PF > & pixel, uint32_t value)
Function to define pixel depth component in uint32_t, with 24 relevant bits.
Parameters
[in] pixel The pixel
[in] value The component value
setD24U() [2/2]
template<PixelFormat PFT> void castor::setD24U (uint8_t * buffer, uint32_t value)
setD32F() [1/2]
template<PixelFormat PF> void castor::setD32F (Pixel< PF > & pixel, float value)
Function to define pixel depth component in float.
Parameters
[in] pixel The pixel
[in] value The component value
setD32F() [2/2]
template<PixelFormat PFT> void castor::setD32F (uint8_t * buffer, float value)
setG16F()
template<PixelFormat PFT> void castor::setG16F (uint8_t * buffer, int16_t value)
setG16S()
template<PixelFormat PFT> void castor::setG16S (uint8_t * buffer, int16_t value)
setG16U()
template<PixelFormat PFT> void castor::setG16U (uint8_t * buffer, uint16_t value)
setG32F() [1/2]
template<PixelFormat PF> void castor::setG32F (Pixel< PF > & pixel, float value)
Function to define pixel green component in float.
Parameters
[in] pixel The pixel
[in] value The component value
setG32F() [2/2]
template<PixelFormat PFT> void castor::setG32F (uint8_t * buffer, float value)
setG32S()
template<PixelFormat PFT> void castor::setG32S (uint8_t * buffer, int32_t value)
setG32U()
template<PixelFormat PFT> void castor::setG32U (uint8_t * buffer, uint32_t value)
setG64F()
template<PixelFormat PFT> void castor::setG64F (uint8_t * buffer, double value)
setG64S()
template<PixelFormat PFT> void castor::setG64S (uint8_t * buffer, int64_t value)
setG64U()
template<PixelFormat PFT> void castor::setG64U (uint8_t * buffer, uint64_t value)
setG8S()
template<PixelFormat PFT> void castor::setG8S (uint8_t * buffer, int8_t value)
setG8U() [1/2]
template<PixelFormat PF> void castor::setG8U (Pixel< PF > & pixel, uint8_t value)
Function to define pixel green component in byte.
Parameters
[in] pixel The pixel
[in] value The component value
setG8U() [2/2]
template<PixelFormat PFT> void castor::setG8U (uint8_t * buffer, uint8_t value)
setR16F()
template<PixelFormat PFT> void castor::setR16F (uint8_t * buffer, int16_t value)
setR16S()
template<PixelFormat PFT> void castor::setR16S (uint8_t * buffer, int16_t value)
setR16U()
template<PixelFormat PFT> void castor::setR16U (uint8_t * buffer, uint16_t value)
setR32F() [1/2]
template<PixelFormat PF> void castor::setR32F (Pixel< PF > const & pixel, float value)
Function to define pixel colour component in float.
Parameters
[in] pixel The pixel
[in] value The component value
setR32F() [2/2]
template<PixelFormat PFT> void castor::setR32F (uint8_t * buffer, float value)
setR32S()
template<PixelFormat PFT> void castor::setR32S (uint8_t * buffer, uint32_t value)
setR32U()
template<PixelFormat PFT> void castor::setR32U (uint8_t * buffer, int32_t value)
setR64F()
template<PixelFormat PFT> void castor::setR64F (uint8_t * buffer, double value)
setR64S()
template<PixelFormat PFT> void castor::setR64S (uint8_t * buffer, int64_t value)
setR64U()
template<PixelFormat PFT> void castor::setR64U (uint8_t * buffer, uint64_t value)
setR8S()
template<PixelFormat PFT> void castor::setR8S (uint8_t * buffer, int8_t value)
setR8U() [1/2]
template<PixelFormat PF> void castor::setR8U (Pixel< PF > & pixel, uint8_t value)
Function to define pixel red component in byte.
Parameters
[in] pixel The pixel
[in] value The component value
setR8U() [2/2]
template<PixelFormat PFT> void castor::setR8U (uint8_t * buffer, uint8_t value)
setS8U() [1/2]
template<PixelFormat PF> void castor::setS8U (Pixel< PF > & pixel, uint8_t value)
Function to define pixel depth stencil in byte.
Parameters
[in] pixel The pixel
[in] value The component value
setS8U() [2/2]
template<PixelFormat PFT> void castor::setS8U (uint8_t * buffer, uint8_t value)
setX16F()
template<PixelFormat PFT, PixelComponent PCT> void castor::setX16F (uint8_t * buffer, int16_t value)
setX16S()
template<PixelFormat PFT, PixelComponent PCT> void castor::setX16S (uint8_t * buffer, int16_t value)
setX16U()
template<PixelFormat PFT, PixelComponent PCT> void castor::setX16U (uint8_t * buffer, uint16_t value)
setX32F()
template<PixelFormat PFT, PixelComponent PCT> void castor::setX32F (uint8_t * buffer, float value)
setX32S()
template<PixelFormat PFT, PixelComponent PCT> void castor::setX32S (uint8_t * buffer, int32_t value)
setX32U()
template<PixelFormat PFT, PixelComponent PCT> void castor::setX32U (uint8_t * buffer, uint32_t value)
setX64F()
template<PixelFormat PFT, PixelComponent PCT> void castor::setX64F (uint8_t * buffer, double value)
setX64S()
template<PixelFormat PFT, PixelComponent PCT> void castor::setX64S (uint8_t * buffer, int64_t value)
setX64U()
template<PixelFormat PFT, PixelComponent PCT> void castor::setX64U (uint8_t * buffer, uint64_t value)
setX8S()
template<PixelFormat PFT, PixelComponent PCT> void castor::setX8S (uint8_t * buffer, int8_t value)
setX8U()
template<PixelFormat PFT, PixelComponent PCT> void castor::setX8U (uint8_t * buffer, uint8_t value)
switchEndianness() [1/2]
template<typename T > constexpr T & castor::switchEndianness (T & value) constexpr noexcept
Convert from little or big endian to the other.
Parameters
[in,out] value Value to be converted.
Referenced by bigEndianToSystemEndian(), bigEndianToSystemEndian(), bigEndianToSystemEndian(), bigEndianToSystemEndian(), bigEndianToSystemEndian(), bigEndianToSystemEndian(), castor3d::chunkEndianToSystemEndian(), littleEndianToSystemEndian(), littleEndianToSystemEndian(), littleEndianToSystemEndian(), littleEndianToSystemEndian(), littleEndianToSystemEndian(), littleEndianToSystemEndian(), castor3d::prepareChunkData(), castor3d::prepareChunkData(), castor3d::prepareChunkData(), castor3d::prepareChunkData(), castor3d::prepareChunkData(), castor3d::prepareChunkData(), castor3d::prepareChunkData(), castor3d::prepareChunkData(), castor3d::prepareChunkData(), castor3d::prepareChunkData(), castor3d::prepareChunkData(), castor3d::prepareChunkData(), castor3d::prepareChunkData(), castor3d::prepareChunkData(), castor3d::prepareChunkData(), castor3d::prepareChunkData(), castor3d::prepareChunkData(), castor3d::prepareChunkData(), castor3d::prepareChunkData(), castor3d::prepareChunkData(), castor3d::prepareChunkData(), castor3d::prepareChunkData(), castor3d::prepareChunkData(), castor3d::prepareChunkData(), castor3d::prepareChunkData(), castor3d::prepareChunkData(), switchEndianness(), systemEndianToBigEndian(), systemEndianToBigEndian(), systemEndianToBigEndian(), systemEndianToBigEndian(), systemEndianToBigEndian(), systemEndianToBigEndian(), systemEndianToLittleEndian(), systemEndianToLittleEndian(), systemEndianToLittleEndian(), systemEndianToLittleEndian(), systemEndianToLittleEndian(), and systemEndianToLittleEndian().
switchEndianness() [2/2]
template<typename T > constexpr T castor::switchEndianness (T const & value) constexpr
Convert from little or big endian to the other.
Parameters
[in,out] value Value to be converted.
References switchEndianness().
systemEndianToBigEndian() [1/6]
template<typename T , size_t N> constexpr Array< T, N > & castor::systemEndianToBigEndian (Array< T, N > & value) constexpr noexcept
Convert the given value to big endian if needed.
Parameters
[in,out] value Value to be converted.
References isBigEndian(), and switchEndianness().
systemEndianToBigEndian() [2/6]
template<typename T , size_t N> constexpr Array< T, N > castor::systemEndianToBigEndian (Array< T, N > const & value) constexpr
Convert the given value to big endian if needed.
Parameters
[in,out] value Value to be converted.
References isBigEndian(), and switchEndianness().
systemEndianToBigEndian() [3/6]
template<typename T > constexpr T & castor::systemEndianToBigEndian (T & value) constexpr noexcept
Convert the given value to big endian if needed.
Parameters
[in,out] value Value to be converted.
References isBigEndian(), and switchEndianness().
systemEndianToBigEndian() [4/6]
template<typename T > constexpr T castor::systemEndianToBigEndian (T const & value) constexpr
Convert the given value to big endian if needed.
Parameters
[in,out] value Value to be converted.
References isBigEndian(), and switchEndianness().
systemEndianToBigEndian() [5/6]
template<typename T > constexpr Vector< T > & castor::systemEndianToBigEndian (Vector< T > & value) constexpr noexcept
Convert the given value to big endian if needed.
Parameters
[in,out] value Value to be converted.
References isBigEndian(), and switchEndianness().
systemEndianToBigEndian() [6/6]
template<typename T > constexpr Vector< T > castor::systemEndianToBigEndian (Vector< T > const & value) constexpr
Convert the given value to big endian if needed.
Parameters
[in,out] value Value to be converted.
References isBigEndian(), and switchEndianness().
systemEndianToLittleEndian() [1/6]
template<typename T , size_t N> constexpr Array< T, N > & castor::systemEndianToLittleEndian (Array< T, N > & value) constexpr noexcept
Convert the given value to little endian if needed.
Parameters
[in,out] value Value to be converted.
References isLittleEndian(), and switchEndianness().
systemEndianToLittleEndian() [2/6]
template<typename T , size_t N> constexpr Array< T, N > castor::systemEndianToLittleEndian (Array< T, N > const & value) constexpr
Convert the given value to little endian if needed.
Parameters
[in,out] value Value to be converted.
References isLittleEndian(), and switchEndianness().
systemEndianToLittleEndian() [3/6]
template<typename T > constexpr T & castor::systemEndianToLittleEndian (T & value) constexpr noexcept
Convert the given value to little endian if needed.
Parameters
[in,out] value Value to be converted.
References isLittleEndian(), and switchEndianness().
systemEndianToLittleEndian() [4/6]
template<typename T > constexpr T castor::systemEndianToLittleEndian (T const & value) constexpr
Convert the given value to little endian if needed.
Parameters
[in,out] value Value to be converted.
References isLittleEndian(), and switchEndianness().
systemEndianToLittleEndian() [5/6]
template<typename T > Vector< T > & castor::systemEndianToLittleEndian (Vector< T > & value) inline noexcept
Convert the given value to little endian if needed.
Parameters
[in,out] value Value to be converted.
References isLittleEndian(), and switchEndianness().
systemEndianToLittleEndian() [6/6]
template<typename T > Vector< T > castor::systemEndianToLittleEndian (Vector< T > const & value) inline
Convert the given value to little endian if needed.
Parameters
[in,out] value Value to be converted.
References isLittleEndian(), and switchEndianness().
toABGRByte() [1/2]
Point4ub castor::toABGRByte (RgbaColourT< ColourComponent > const & colour) inline
Stores a colour's components into a point in ABGR format.
Parameters
[in] colour The colour.
Returns
The colour's components.
toABGRByte() [2/2]
Point4ub castor::toABGRByte (RgbColourT< ColourComponent > const & colour) inline
Stores a colour's components into a point in ABGR format.
Parameters
[in] colour The colour.
Returns
The colour's components.
toABGRFloat() [1/2]
template<typename ComponentType > Point4f castor::toABGRFloat (RgbaColourT< ComponentType > const & colour) inline
Stores a colour's components into a point in ABGR format.
Parameters
[in] colour The colour.
Returns
The colour's components.
toABGRFloat() [2/2]
template<typename ComponentType > Point4f castor::toABGRFloat (RgbColourT< ComponentType > const & colour) inline
Stores a colour's components into a point in ABGR format.
Parameters
[in] colour The colour.
Returns
The colour's components.
toABGRPacked() [1/2]
uint32_t castor::toABGRPacked (RgbaColourT< ColourComponent > const & colour) inline
Packs a colour's components into an uint32_t in the ABGR format (0xAABBGGRR).
Parameters
[in] colour The colour.
Returns
The packed colour.
toABGRPacked() [2/2]
uint32_t castor::toABGRPacked (RgbColourT< ColourComponent > const & colour) inline
Packs a colour's components into an uint32_t in the ABGR format (0xAABBGGRR).
Parameters
[in] colour The colour.
Returns
The packed colour.
toARGBByte() [1/2]
Point4ub castor::toARGBByte (RgbaColourT< ColourComponent > const & colour) inline
Stores a colour's components into a point in ARGB format.
Parameters
[in] colour The colour.
Returns
The colour's components.
toARGBByte() [2/2]
Point4ub castor::toARGBByte (RgbColourT< ColourComponent > const & colour) inline
Stores a colour's components into a point in ARGB format.
Parameters
[in] colour The colour.
Returns
The colour's components.
toARGBFloat() [1/2]
template<typename ComponentType > Point4f castor::toARGBFloat (RgbaColourT< ComponentType > const & colour) inline
Stores a colour's components into a point in ARGB format.
Parameters
[in] colour The colour.
Returns
The colour's components.
toARGBFloat() [2/2]
template<typename ComponentType > Point4f castor::toARGBFloat (RgbColourT< ComponentType > const & colour) inline
Stores a colour's components into a point in ARGB format.
Parameters
[in] colour The colour.
Returns
The colour's components.
toARGBPacked() [1/2]
uint32_t castor::toARGBPacked (RgbaColourT< ColourComponent > const & colour) inline
Packs a colour's components into an uint32_t in the ARGB format (0xAARRGGBB).
Parameters
[in] colour The colour.
Returns
The packed colour.
toARGBPacked() [2/2]
uint32_t castor::toARGBPacked (RgbColourT< ColourComponent > const & colour) inline
Packs a colour's components into an uint32_t in the ARGB format (0xAARRGGBB).
Parameters
[in] colour The colour.
Returns
The packed colour.
toBGRAByte() [1/2]
Point4ub castor::toBGRAByte (RgbaColourT< ColourComponent > const & colour) inline
Stores a colour's components into a point in BGRA format.
Parameters
[in] colour The colour.
Returns
The colour's components.
toBGRAByte() [2/2]
Point4ub castor::toBGRAByte (RgbColourT< ColourComponent > const & colour) inline
Stores a colour's components into a point in BGRA format.
Parameters
[in] colour The colour.
Returns
The colour's components.
toBGRAFloat() [1/2]
template<typename ComponentType > Point4f castor::toBGRAFloat (RgbaColourT< ComponentType > const & colour) inline
Stores a colour's components into a point in BGRA format.
Parameters
[in] colour The colour.
Returns
The colour's components.
toBGRAFloat() [2/2]
template<typename ComponentType > Point4f castor::toBGRAFloat (RgbColourT< ComponentType > const & colour) inline
Stores a colour's components into a point in BGRA format.
Parameters
[in] colour The colour.
Returns
The colour's components.
toBGRAPacked() [1/2]
uint32_t castor::toBGRAPacked (RgbaColourT< ColourComponent > const & colour) inline
Packs a colour's components into an uint32_t in the BGRA format (0xBBGGRRAA).
Parameters
[in] colour The colour.
Returns
The packed colour.
toBGRAPacked() [2/2]
uint32_t castor::toBGRAPacked (RgbColourT< ColourComponent > const & colour) inline
Packs a colour's components into an uint32_t in the BGRA format (0xBBGGRRAA).
Parameters
[in] colour The colour.
Returns
The packed colour.
toBGRByte() [1/2]
Point3ub castor::toBGRByte (RgbaColourT< ColourComponent > const & colour) inline
Stores a colour's components into a point in BGR format.
Parameters
[in] colour The colour.
Returns
The colour's components.
toBGRByte() [2/2]
Point3ub castor::toBGRByte (RgbColourT< ColourComponent > const & colour) inline
Stores a colour's components into a point in BGR format.
Parameters
[in] colour The colour.
Returns
The colour's components.
toBGRFloat() [1/2]
template<typename ComponentType > Point3f castor::toBGRFloat (RgbaColourT< ComponentType > const & colour) inline
Stores a colour's components into a point in BGR format.
Parameters
[in] colour The colour.
Returns
The colour's components.
toBGRFloat() [2/2]
template<typename ComponentType > Point3f castor::toBGRFloat (RgbColourT< ComponentType > const & colour) inline
Stores a colour's components into a point in BGR format.
Parameters
[in] colour The colour.
Returns
The colour's components.
toBGRPacked() [1/2]
uint32_t castor::toBGRPacked (RgbaColourT< ColourComponent > const & colour) inline
Packs a colour's components into an uint32_t in the BGR format (0x00BBGGRR).
Parameters
[in] colour The colour.
Returns
The packed colour.
toBGRPacked() [2/2]
uint32_t castor::toBGRPacked (RgbColourT< ColourComponent > const & colour) inline
Packs a colour's components into an uint32_t in the BGR format (0x00BBGGRR).
Parameters
[in] colour The colour.
Returns
The packed colour.
toRGBAByte() [1/2]
Point4ub castor::toRGBAByte (RgbaColourT< ColourComponent > const & colour) inline
Stores a colour's components into a point in RGBA format.
Parameters
[in] colour The colour.
Returns
The colour's components.
toRGBAByte() [2/2]
Point4ub castor::toRGBAByte (RgbColourT< ColourComponent > const & colour) inline
Stores a colour's components into a point in RGBA format.
Parameters
[in] colour The colour.
Returns
The colour's components.
toRGBAFloat() [1/2]
template<typename ComponentType > Point4f castor::toRGBAFloat (RgbaColourT< ComponentType > const & colour) inline
Stores a colour's components into a point in RGBA format.
Parameters
[in] colour The colour.
Returns
The colour's components.
toRGBAFloat() [2/2]
template<typename ComponentType > Point4f castor::toRGBAFloat (RgbColourT< ComponentType > const & colour) inline
Stores a colour's components into a point in RGBA format.
Parameters
[in] colour The colour.
Returns
The colour's components.
toRGBAPacked() [1/2]
uint32_t castor::toRGBAPacked (RgbaColourT< ColourComponent > const & colour) inline
Packs a colour's components into an uint32_t in the RGBA format (0xRRGGBBAA).
Parameters
[in] colour The colour.
Returns
The packed colour.
toRGBAPacked() [2/2]
uint32_t castor::toRGBAPacked (RgbColourT< ColourComponent > const & colour) inline
Packs a colour's components into an uint32_t in the RGBA format (0xRRGGBBAA).
Parameters
[in] colour The colour.
Returns
The packed colour.
toRGBByte() [1/2]
Point3ub castor::toRGBByte (RgbaColourT< ColourComponent > const & colour) inline
Stores a colour's components into a point in RGB format.
Parameters
[in] colour The colour.
Returns
The colour's components.
toRGBByte() [2/2]
Point3ub castor::toRGBByte (RgbColourT< ColourComponent > const & colour) inline
Stores a colour's components into a point in RGB format.
Parameters
[in] colour The colour.
Returns
The colour's components.
toRGBFloat() [1/2]
template<typename ComponentType > Point3f castor::toRGBFloat (RgbaColourT< ComponentType > const & colour) inline
Stores a colour's components into a point in RGB format.
Parameters
[in] colour The colour.
Returns
The colour's components.
toRGBFloat() [2/2]
template<typename ComponentType > Point3f castor::toRGBFloat (RgbColourT< ComponentType > const & colour) inline
Stores a colour's components into a point in RGB format.
Parameters
[in] colour The colour.
Returns
The colour's components.
toRGBPacked() [1/2]
uint32_t castor::toRGBPacked (RgbaColourT< ColourComponent > const & colour) inline
Packs a colour's components into an uint32_t in the RGB format (0x00RRGGBB).
Parameters
[in] colour The colour.
Returns
The packed colour.
toRGBPacked() [2/2]
uint32_t castor::toRGBPacked (RgbColourT< ColourComponent > const & colour) inline
Packs a colour's components into an uint32_t in the RGB format (0x00RRGGBB).
Parameters
[in] colour The colour.
Returns
The packed colour.
toSystemWide() [1/8]
WString castor::toSystemWide (mbchar const * in) inline
References toSystemWide().
toSystemWide() [2/8]
WString castor::toSystemWide (mbchar const * in, size_t length) inline
References toSystemWide().
toSystemWide() [3/8]
WString castor::toSystemWide (MbString const & in) inline
References toSystemWide().
toSystemWide() [4/8]
CU_API WString castor::toSystemWide (MbStringView in)
Referenced by toSystemWide(), toSystemWide(), and toSystemWide().
toSystemWide() [5/8]
WString castor::toSystemWide (wchar const * in) inline
toSystemWide() [6/8]
WString castor::toSystemWide (wchar const * in, size_t length) inline
toSystemWide() [7/8]
WString castor::toSystemWide (WString const & in) inline
toSystemWide() [8/8]
WString castor::toSystemWide (WStringView in) inline
toUtf8() [1/8]
MbString castor::toUtf8 (mbchar const * in) inline
toUtf8() [2/8]
MbString castor::toUtf8 (mbchar const * in, size_t length) inline
toUtf8() [3/8]
MbString castor::toUtf8 (MbString const & in) inline
toUtf8() [4/8]
MbString castor::toUtf8 (MbStringView in) inline
toUtf8() [5/8]
MbString castor::toUtf8 (wchar const * in) inline
References toUtf8().
toUtf8() [6/8]
MbString castor::toUtf8 (wchar const * in, size_t length) inline
References toUtf8().
toUtf8() [7/8]
MbString castor::toUtf8 (WString const & in) inline
References toUtf8().
toUtf8() [8/8]
CU_API MbString castor::toUtf8 (WStringView in)
Referenced by castor::Exception::Exception(), castor::LoggerInstance::lockedLogDebug(), castor::LoggerInstance::lockedLogDebugNoLF(), castor::LoggerInstance::lockedLogError(), castor::LoggerInstance::lockedLogErrorNoLF(), castor::LoggerInstance::lockedLogInfo(), castor::LoggerInstance::lockedLogInfoNoLF(), castor::LoggerInstance::lockedLogTrace(), castor::LoggerInstance::lockedLogTraceNoLF(), castor::LoggerInstance::lockedLogWarning(), castor::LoggerInstance::lockedLogWarningNoLF(), castor::Logger::logDebug(), castor::Logger::logDebug(), castor::Logger::logDebug(), castor::Logger::logDebugNoNL(), castor::Logger::logDebugNoNL(), castor::Logger::logDebugNoNL(), castor::Logger::logError(), castor::Logger::logError(), castor::Logger::logError(), castor::Logger::logErrorNoNL(), castor::Logger::logErrorNoNL(), castor::Logger::logErrorNoNL(), castor::Logger::logInfo(), castor::Logger::logInfo(), castor::Logger::logInfo(), castor::Logger::logInfoNoNL(), castor::Logger::logInfoNoNL(), castor::Logger::logInfoNoNL(), castor::Logger::logTrace(), castor::Logger::logTrace(), castor::Logger::logTrace(), castor::Logger::logTraceNoNL(), castor::Logger::logTraceNoNL(), castor::Logger::logTraceNoNL(), castor::Logger::logWarning(), castor::Logger::logWarning(), castor::Logger::logWarning(), castor::Logger::logWarningNoNL(), castor::Logger::logWarningNoNL(), castor::Logger::logWarningNoNL(), castor3d::makeImage(), castor3d::makeShaderState(), castor::LoggerImpl::printMessage(), castor::LoggerInstance::pushMessage(), toUtf8(), toUtf8(), toUtf8(), castor3d::ChunkWriter< castor::Path >::write(), castor3d::ChunkWriter< castor::String >::write(), and castor3d::InstantUploadDataT< UploaderT >::~InstantUploadDataT().
toUtf8U32String() [1/3]
U32String castor::toUtf8U32String (String const & in) inline
References toUtf8U32String().
toUtf8U32String() [2/3]
CU_API U32String castor::toUtf8U32String (StringView in)
Referenced by toUtf8U32String(), and toUtf8U32String().
toUtf8U32String() [3/3]
U32String castor::toUtf8U32String (xchar const * in, size_t length) inline
References toUtf8U32String().
Variable Documentation
cuEmptyString
const String castor::cuEmptyString static
ERROR_UNKNOWN_OBJECT
const MbString castor::ERROR_UNKNOWN_OBJECT = "Unknown object type" static
Referenced by castor::Factory< ObjT, KeyT, PtrTypeT, CreatorT, IdT, EntryT >::create(), and castor3d::LightingModelFactory::create().
hasAlphaV
template<PixelFormat PixelFormatT> bool constexpr castor::hasAlphaV = HasAlpha< PixelFormatT >::value static constexpr
hasBaseParameterTypeV
template<ParameterType Type> bool constexpr castor::hasBaseParameterTypeV = HasBaseParameterType< Type >::value inline constexpr
is16FComponentsV
template<PixelFormat PixelFormatT> bool constexpr castor::is16FComponentsV = Is16FComponents< PixelFormatT >::value static constexpr
is16SComponentsV
template<PixelFormat PixelFormatT> bool constexpr castor::is16SComponentsV = Is16SComponents< PixelFormatT >::value static constexpr
is16UComponentsV
template<PixelFormat PixelFormatT> bool constexpr castor::is16UComponentsV = Is16UComponents< PixelFormatT >::value static constexpr
is32FComponentsV
template<PixelFormat PixelFormatT> bool constexpr castor::is32FComponentsV = Is32FComponents< PixelFormatT >::value static constexpr
is32SComponentsV
template<PixelFormat PixelFormatT> bool constexpr castor::is32SComponentsV = Is32SComponents< PixelFormatT >::value static constexpr
is32UComponentsV
template<PixelFormat PixelFormatT> bool constexpr castor::is32UComponentsV = Is32UComponents< PixelFormatT >::value static constexpr
is64FComponentsV
template<PixelFormat PixelFormatT> bool constexpr castor::is64FComponentsV = Is64FComponents< PixelFormatT >::value static constexpr
is64SComponentsV
template<PixelFormat PixelFormatT> bool constexpr castor::is64SComponentsV = Is64SComponents< PixelFormatT >::value static constexpr
is64UComponentsV
template<PixelFormat PixelFormatT> bool constexpr castor::is64UComponentsV = Is64UComponents< PixelFormatT >::value static constexpr
is8SComponentsV
template<PixelFormat PixelFormatT> bool constexpr castor::is8SComponentsV = Is8SComponents< PixelFormatT >::value static constexpr
is8SRGBComponentsV
template<PixelFormat PixelFormatT> bool constexpr castor::is8SRGBComponentsV = Is8SRGBComponents< PixelFormatT >::value static constexpr
is8UComponentsV
template<PixelFormat PixelFormatT> bool constexpr castor::is8UComponentsV = Is8UComponents< PixelFormatT >::value static constexpr
isArithmeticTypeV
template<ParameterType Type> bool constexpr castor::isArithmeticTypeV = IsArithmeticType< Type >::value inline constexpr
isChangeTrackedT
template<typename T > bool constexpr castor::isChangeTrackedT = IsChangeTrackedT< T >::value inline static constexpr
isColourFormatV
template<PixelFormat PixelFormatT> bool constexpr castor::isColourFormatV = IsColourFormat< PixelFormatT >::value static constexpr
isCompressedV
template<PixelFormat PixelFormatT> bool constexpr castor::isCompressedV = IsCompressed< PixelFormatT >::value static constexpr
isD16UComponentV
template<PixelFormat PixelFormatT> bool constexpr castor::isD16UComponentV = IsD16UComponent< PixelFormatT >::value static constexpr
isD24UComponentV
template<PixelFormat PixelFormatT> bool constexpr castor::isD24UComponentV = IsD24UComponent< PixelFormatT >::value static constexpr
isD32FComponentV
template<PixelFormat PixelFormatT> bool constexpr castor::isD32FComponentV = IsD32FComponent< PixelFormatT >::value static constexpr
isDepthFormatV
template<PixelFormat PixelFormatT> bool constexpr castor::isDepthFormatV = IsDepthFormat< PixelFormatT >::value static constexpr
isDepthStencilFormatV
template<PixelFormat PixelFormatT> bool constexpr castor::isDepthStencilFormatV = IsDepthStencilFormat< PixelFormatT >::value static constexpr
isFloatingV
template<typename TypeT > constexpr bool castor::isFloatingV static constexpr
Initial value:
= std::is_same_v< float, TypeT >
        || std::is_same_v< double, TypeT >
isGroupChangeTrackedT
template<typename T > bool constexpr castor::isGroupChangeTrackedT = IsGroupChangeTrackedT< T >::value inline static constexpr
isLengthV
template<typename TypeT > constexpr bool castor::isLengthV = IsLengthT< TypeT >::value static constexpr
isPoint2d
template<typename TypeT > constexpr bool castor::isPoint2d = isPoint2V< TypeT, double > static constexpr
isPoint2f
template<typename TypeT > constexpr bool castor::isPoint2f = isPoint2V< TypeT, float > static constexpr
isPoint2V
template<typename TypeT , typename CoordT > constexpr bool castor::isPoint2V = isPointV< TypeT, CoordT, 2u > static constexpr
isPoint3d
template<typename TypeT > constexpr bool castor::isPoint3d = isPoint3V< TypeT, double > static constexpr
isPoint3f
template<typename TypeT > constexpr bool castor::isPoint3f = isPoint3V< TypeT, float > static constexpr
isPoint3V
template<typename TypeT , typename CoordT > constexpr bool castor::isPoint3V = isPointV< TypeT, CoordT, 3u > static constexpr
isPoint4d
template<typename TypeT > constexpr bool castor::isPoint4d = isPoint4V< TypeT, double > static constexpr
isPoint4f
template<typename TypeT > constexpr bool castor::isPoint4f = isPoint4V< TypeT, float > static constexpr
isPoint4V
template<typename TypeT , typename CoordT > constexpr bool castor::isPoint4V = isPointV< TypeT, CoordT, 4u > static constexpr
isPointV
template<typename TypeT , typename CoordT , uint32_t CountT> constexpr bool castor::isPointV static constexpr
Initial value:
= std::is_same_v< Point< CoordT, CountT >, TypeT >
        || std::is_same_v< LengthT< Point< CoordT, CountT > >, TypeT >
isRangedValueT
template<typename T > bool constexpr castor::isRangedValueT = IsRangedValueT< T >::value inline static constexpr
isS8UComponentV
template<PixelFormat PixelFormatT> bool constexpr castor::isS8UComponentV = IsS8UComponent< PixelFormatT >::value static constexpr
isSpeedT
template<typename ValueT > bool constexpr castor::isSpeedT = IsSpeedT< ValueT >::value static constexpr
isStencilFormatV
template<PixelFormat PixelFormatT> bool constexpr castor::isStencilFormatV = IsStencilFormat< PixelFormatT >::value static constexpr
maxValueT
template<details::ValueTypeT DataT, DataT ... ValuesT> DataT constexpr castor::maxValueT = details::MaxRecT< DataT, ValuesT... >::value static constexpr
minValueT
template<details::ValueTypeT DataT, DataT ... ValuesT> DataT castor::minValueT = details::MinRecT< DataT, ValuesT... >::value static
noInit
NoInit constexpr castor::noInit static constexpr
ParserParameterParamType
template<ParameterType Type, typename ParserValueHelperT = void> ParameterType constexpr castor::ParserParameterParamType = ParserParameterHelper< Type, ParserValueHelperT >::ParamType inline constexpr
ParserParameterStringType
template<ParameterType Type, typename ParserValueHelperT = void> StringView constexpr castor::ParserParameterStringType = ParserParameterHelper< Type, ParserValueHelperT >::StringType inline constexpr
Pi
template<typename Type > constexpr Type castor::Pi { Type(3.1415926535897932384626433832795028841968) } static constexpr
PiDiv2
template<typename Type > constexpr Type castor::PiDiv2 { Type(3.1415926535897932384626433832795028841968 / 2.0) } static constexpr
PiMult2
template<typename Type > constexpr Type castor::PiMult2 { Type(3.1415926535897932384626433832795028841968 * 2.0) } static constexpr
PreviousSection
constexpr SectionId castor::PreviousSection = ((castor::SectionId('P') << 24) | (castor::SectionId('R') << 16) | (castor::SectionId('E') << 8) | (castor::SectionId('V') << 0)) static constexpr
Indicates that the next section for a parser is the previous one.
Referenced by castor3d::CU_DeclareAttributeParser().
singleComponentV
template<PixelFormat PixelFormatT> PixelFormat constexpr castor::singleComponentV = SingleComponentT< PixelFormatT >::value static constexpr
STR_UNICITY_ERROR
Array< MbStringView, size_t(UnicityError::eCount) > const castor::STR_UNICITY_ERROR static
Initial value:
{
        "No instance for Unique class ",
        "Duplicate instance for Unique class ",
    }
Unicity error texts.
Tau
template<typename Type > constexpr Type castor::Tau { Type(3.1415926535897932384626433832795028841968 * 2.0) } static constexpr