Castor3D: castor3d::PassVisitorBase Class Reference
castor3d::PassVisitorBase Class Reference abstract
#include <PassVisitor.hpp>
Classes
struct Config
Public Types
template<typename ControlT >
using ControlsListT = std::vector< ControlT * >
using ControlsList = ControlsListT< bool >
using AtomicControlsList = ControlsListT< std::atomic_bool >
Public Member Functions
virtual C3D_API ~PassVisitorBase ()=default
virtual C3D_API void visit (castor::String const &name, bool &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, int16_t &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, uint16_t &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, int32_t &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, uint32_t &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, int64_t &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, uint64_t &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, float &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, double &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, BlendMode &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, ParallaxOcclusionMode &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, VkCompareOp &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::RgbColour &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::RgbaColour &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::HdrRgbColour &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::HdrRgbaColour &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point2f &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point2i &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point2ui &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point3f &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point3i &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point3ui &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point4f &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point4i &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point4ui &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Matrix4x4f &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::RangedValue< float > &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::RangedValue< int32_t > &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::RangedValue< uint32_t > &value, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, PassComponentTextureFlag textureFlag, TextureFlagConfiguration &value, uint32_t componentsCount, ControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, bool &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, int16_t &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, uint16_t &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, int32_t &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, uint32_t &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, int64_t &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, uint64_t &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, float &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, double &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, BlendMode &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, ParallaxOcclusionMode &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, VkCompareOp &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::RgbColour &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::RgbaColour &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::HdrRgbColour &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::HdrRgbaColour &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point2f &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point2i &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point2ui &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point3f &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point3i &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point3ui &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point4f &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point4i &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Point4ui &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::Matrix4x4f &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::RangedValue< float > &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::RangedValue< int32_t > &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, castor::RangedValue< uint32_t > &value, AtomicControlsList controls)=0
virtual C3D_API void visit (castor::String const &name, PassComponentTextureFlag textureFlag, TextureFlagConfiguration &value, uint32_t componentsCount, AtomicControlsList controls)=0
template<typename ControlT = bool>
void visit (castor::String const &name, bool &value, ControlT *control=nullptr)
template<typename ControlT = bool>
void visit (castor::String const &name, int16_t &value, ControlT *control=nullptr)
template<typename ControlT = bool>
void visit (castor::String const &name, uint16_t &value, ControlT *control=nullptr)
template<typename ControlT = bool>
void visit (castor::String const &name, int32_t &value, ControlT *control=nullptr)
template<typename ControlT = bool>
void visit (castor::String const &name, uint32_t &value, ControlT *control=nullptr)
template<typename ControlT = bool>
void visit (castor::String const &name, int64_t &value, ControlT *control=nullptr)
template<typename ControlT = bool>
void visit (castor::String const &name, uint64_t &value, ControlT *control=nullptr)
template<typename ControlT = bool>
void visit (castor::String const &name, float &value, ControlT *control=nullptr)
template<typename ControlT = bool>
void visit (castor::String const &name, double &value, ControlT *control=nullptr)
template<typename ControlT = bool>
void visit (castor::String const &name, BlendMode &value, ControlT *control=nullptr)
template<typename ControlT = bool>
void visit (castor::String const &name, ParallaxOcclusionMode &value, ControlT *control=nullptr)
template<typename ControlT = bool>
void visit (castor::String const &name, VkCompareOp &value, ControlT *control=nullptr)
template<typename ControlT = bool>
void visit (castor::String const &name, castor::RgbaColour &value, ControlT *control=nullptr)
template<typename ControlT = bool>
void visit (castor::String const &name, castor::HdrRgbColour &value, ControlT *control=nullptr)
template<typename ControlT = bool>
void visit (castor::String const &name, castor::HdrRgbaColour &value, ControlT *control=nullptr)
template<typename ControlT = bool>
void visit (castor::String const &name, castor::Point2f &value, ControlT *control=nullptr)
template<typename ControlT = bool>
void visit (castor::String const &name, castor::Point2i &value, ControlT *control=nullptr)
template<typename ControlT = bool>
void visit (castor::String const &name, castor::Point2ui &value, ControlT *control=nullptr)
template<typename ControlT = bool>
void visit (castor::String const &name, castor::Point3f &value, ControlT *control=nullptr)
template<typename ControlT = bool>
void visit (castor::String const &name, castor::Point3i &value, ControlT *control=nullptr)
template<typename ControlT = bool>
void visit (castor::String const &name, castor::Point3ui &value, ControlT *control=nullptr)
template<typename ControlT = bool>
void visit (castor::String const &name, castor::Point4f &value, ControlT *control=nullptr)
template<typename ControlT = bool>
void visit (castor::String const &name, castor::Point4i &value, ControlT *control=nullptr)
template<typename ControlT = bool>
void visit (castor::String const &name, castor::Point4ui &value, ControlT *control=nullptr)
template<typename ControlT = bool>
void visit (castor::String const &name, castor::Matrix4x4f &value, ControlT *control=nullptr)
template<typename ControlT = bool>
void visit (castor::String const &name, castor::RangedValue< float > &value, ControlT *control=nullptr)
template<typename ControlT = bool>
void visit (castor::String const &name, castor::RangedValue< int32_t > &value, ControlT *control=nullptr)
template<typename ControlT = bool>
void visit (castor::String const &name, castor::RangedValue< uint32_t > &value, ControlT *control=nullptr)
template<typename ControlT = bool>
void visit (castor::String const &name, PassComponentTextureFlag textureFlag, TextureFlagConfiguration &value, uint32_t componentsCount, ControlT *control=nullptr)
template<typename TypeT , typename ControlT >
void visit (castor::String const &name, castor::ChangeTrackedT< TypeT, ControlT > &value, ControlsListT< ControlT > controls=ControlsListT< ControlT >{})
template<typename TypeT , typename ControlT >
void visit (castor::String const &name, castor::GroupChangeTrackedT< TypeT, ControlT > &value, ControlsListT< ControlT > controls=ControlsListT< ControlT >{})
Static Public Member Functions
template<typename ControlT >
static ControlsListT< ControlT > makeControlsList (ControlT *control)
Public Attributes
Config const config
Protected Member Functions
PassVisitorBase (Config config)
Member Typedef Documentation
AtomicControlsList
using castor3d::PassVisitorBase::AtomicControlsList = ControlsListT< std::atomic_bool >
ControlsList
using castor3d::PassVisitorBase::ControlsList = ControlsListT< bool >
ControlsListT
template<typename ControlT > using castor3d::PassVisitorBase::ControlsListT = std::vector< ControlT * >
Constructor & Destructor Documentation
PassVisitorBase()
castor3d::PassVisitorBase::PassVisitorBase (Config config) inline explicit protected
~PassVisitorBase()
virtual C3D_API castor3d::PassVisitorBase::~PassVisitorBase () virtual default
Member Function Documentation
makeControlsList()
template<typename ControlT > static ControlsListT< ControlT > castor3d::PassVisitorBase::makeControlsList (ControlT * control) inline static
Referenced by visit().
visit() [1/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, BlendMode & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [2/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, BlendMode & value, ControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [3/91]
template<typename ControlT = bool> void castor3d::PassVisitorBase::visit (castor::String const & name, BlendMode & value, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [4/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, bool & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [5/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, bool & value, ControlsList controls) pure virtual
name Values.
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
Referenced by visit().
visit() [6/91]
template<typename ControlT = bool> void castor3d::PassVisitorBase::visit (castor::String const & name, bool & value, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [7/91]
template<typename TypeT , typename ControlT > void castor3d::PassVisitorBase::visit (castor::String const & name, castor::ChangeTrackedT< TypeT, ControlT > & value, ControlsListT< ControlT > controls = ControlsListT< ControlT >{}) inline
visit() [8/91]
template<typename TypeT , typename ControlT > void castor3d::PassVisitorBase::visit (castor::String const & name, castor::GroupChangeTrackedT< TypeT, ControlT > & value, ControlsListT< ControlT > controls = ControlsListT< ControlT >{}) inline
visit() [9/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::HdrRgbaColour & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [10/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::HdrRgbaColour & value, ControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [11/91]
template<typename ControlT = bool> void castor3d::PassVisitorBase::visit (castor::String const & name, castor::HdrRgbaColour & value, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [12/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::HdrRgbColour & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [13/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::HdrRgbColour & value, ControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [14/91]
template<typename ControlT = bool> void castor3d::PassVisitorBase::visit (castor::String const & name, castor::HdrRgbColour & value, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [15/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Matrix4x4f & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [16/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Matrix4x4f & value, ControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [17/91]
template<typename ControlT = bool> void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Matrix4x4f & value, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [18/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point2f & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [19/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point2f & value, ControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [20/91]
template<typename ControlT = bool> void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point2f & value, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [21/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point2i & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [22/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point2i & value, ControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [23/91]
template<typename ControlT = bool> void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point2i & value, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [24/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point2ui & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [25/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point2ui & value, ControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [26/91]
template<typename ControlT = bool> void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point2ui & value, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [27/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point3f & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [28/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point3f & value, ControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [29/91]
template<typename ControlT = bool> void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point3f & value, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [30/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point3i & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [31/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point3i & value, ControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [32/91]
template<typename ControlT = bool> void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point3i & value, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [33/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point3ui & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [34/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point3ui & value, ControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [35/91]
template<typename ControlT = bool> void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point3ui & value, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [36/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point4f & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [37/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point4f & value, ControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [38/91]
template<typename ControlT = bool> void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point4f & value, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [39/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point4i & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [40/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point4i & value, ControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [41/91]
template<typename ControlT = bool> void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point4i & value, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [42/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point4ui & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [43/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point4ui & value, ControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [44/91]
template<typename ControlT = bool> void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point4ui & value, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [45/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::RangedValue< float > & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [46/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::RangedValue< float > & value, ControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [47/91]
template<typename ControlT = bool> void castor3d::PassVisitorBase::visit (castor::String const & name, castor::RangedValue< float > & value, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [48/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::RangedValue< int32_t > & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [49/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::RangedValue< int32_t > & value, ControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [50/91]
template<typename ControlT = bool> void castor3d::PassVisitorBase::visit (castor::String const & name, castor::RangedValue< int32_t > & value, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [51/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::RangedValue< uint32_t > & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [52/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::RangedValue< uint32_t > & value, ControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [53/91]
template<typename ControlT = bool> void castor3d::PassVisitorBase::visit (castor::String const & name, castor::RangedValue< uint32_t > & value, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [54/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::RgbaColour & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [55/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::RgbaColour & value, ControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [56/91]
template<typename ControlT = bool> void castor3d::PassVisitorBase::visit (castor::String const & name, castor::RgbaColour & value, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [57/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::RgbColour & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [58/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::RgbColour & value, ControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [59/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, double & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [60/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, double & value, ControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [61/91]
template<typename ControlT = bool> void castor3d::PassVisitorBase::visit (castor::String const & name, double & value, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [62/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, float & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [63/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, float & value, ControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [64/91]
template<typename ControlT = bool> void castor3d::PassVisitorBase::visit (castor::String const & name, float & value, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [65/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, int16_t & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [66/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, int16_t & value, ControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [67/91]
template<typename ControlT = bool> void castor3d::PassVisitorBase::visit (castor::String const & name, int16_t & value, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [68/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, int32_t & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [69/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, int32_t & value, ControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [70/91]
template<typename ControlT = bool> void castor3d::PassVisitorBase::visit (castor::String const & name, int32_t & value, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [71/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, int64_t & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [72/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, int64_t & value, ControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [73/91]
template<typename ControlT = bool> void castor3d::PassVisitorBase::visit (castor::String const & name, int64_t & value, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [74/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, ParallaxOcclusionMode & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [75/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, ParallaxOcclusionMode & value, ControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [76/91]
template<typename ControlT = bool> void castor3d::PassVisitorBase::visit (castor::String const & name, ParallaxOcclusionMode & value, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [77/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, PassComponentTextureFlag textureFlag, TextureFlagConfiguration & value, uint32_t componentsCount, AtomicControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [78/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, PassComponentTextureFlag textureFlag, TextureFlagConfiguration & value, uint32_t componentsCount, ControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [79/91]
template<typename ControlT = bool> void castor3d::PassVisitorBase::visit (castor::String const & name, PassComponentTextureFlag textureFlag, TextureFlagConfiguration & value, uint32_t componentsCount, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [80/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, uint16_t & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [81/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, uint16_t & value, ControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [82/91]
template<typename ControlT = bool> void castor3d::PassVisitorBase::visit (castor::String const & name, uint16_t & value, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [83/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, uint32_t & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [84/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, uint32_t & value, ControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [85/91]
template<typename ControlT = bool> void castor3d::PassVisitorBase::visit (castor::String const & name, uint32_t & value, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [86/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, uint64_t & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [87/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, uint64_t & value, ControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [88/91]
template<typename ControlT = bool> void castor3d::PassVisitorBase::visit (castor::String const & name, uint64_t & value, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
visit() [89/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, VkCompareOp & value, AtomicControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [90/91]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, VkCompareOp & value, ControlsList controls) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [91/91]
template<typename ControlT = bool> void castor3d::PassVisitorBase::visit (castor::String const & name, VkCompareOp & value, ControlT * control = nullptr) inline
References makeControlsList(), and visit().
Member Data Documentation
config
Config const castor3d::PassVisitorBase::config
The documentation for this class was generated from the following file:
Material/Pass/PassVisitor.hpp