Castor3D: castor3d::GBufferBase Class Reference
castor3d::GBufferBase Class Reference
#include <GBuffer.hpp>
Public Member Functions
C3D_API GBufferBase (RenderDevice const &device, castor::String name)
Public Member Functions inherited from castor::NamedBaseT< T >
NamedBaseT (T name) noexcept
Constructor.
T const & getName () const noexcept
Retrieves the name.
void rename (T name) noexcept
Protected Member Functions
C3D_API TextureUPtr doCreateTexture (crg::ResourcesCache &resources, castor::String const &name, VkImageCreateFlags createFlags, VkExtent3D const &size, uint32_t layerCount, VkSampleCountFlagBits sampleCount, uint32_t mipLevels, VkFormat format, VkImageUsageFlags usageFlags, VkBorderColor const &borderColor, VkCompareOp compareOp) const
template<typename TextureEnumT >
castor::Vector< Texture const * > doCreateTextures (crg::ResourcesCache &resources, castor::Array< Texture const *, size_t(TextureEnumT::eCount) > const &inputs, castor::String const &prefix, VkImageCreateFlags createFlags, castor::Size const &size, uint32_t layerCount, VkSampleCountFlagBits sampleCount, castor::Vector< TextureUPtr > &owned) const
Initialises 2D or 2D array g-buffer textures.
template<typename TextureEnumT >
castor::Vector< Texture const * > doCreateTextures (crg::ResourcesCache &resources, castor::Array< Texture const *, size_t(TextureEnumT::eCount) > const &inputs, castor::String const &prefix, VkImageCreateFlags createFlags, VkExtent3D const &size, VkSampleCountFlagBits sampleCount, castor::Vector< TextureUPtr > &owned) const
Initialises 3D g-buffer textures.
Protected Attributes
RenderDevice const & m_device
Protected Attributes inherited from castor::NamedBaseT< T >
T m_name
Constructor & Destructor Documentation
GBufferBase()
C3D_API castor3d::GBufferBase::GBufferBase (RenderDevice const & device, castor::String name) explicit
Member Function Documentation
doCreateTexture()
C3D_API TextureUPtr castor3d::GBufferBase::doCreateTexture (crg::ResourcesCache & resources, castor::String const & name, VkImageCreateFlags createFlags, VkExtent3D const & size, uint32_t layerCount, VkSampleCountFlagBits sampleCount, uint32_t mipLevels, VkFormat format, VkImageUsageFlags usageFlags, VkBorderColor const & borderColor, VkCompareOp compareOp) const protected
Referenced by doCreateTextures(), and doCreateTextures().
doCreateTextures() [1/2]
template<typename TextureEnumT > castor::Vector< Texture const * > castor3d::GBufferBase::doCreateTextures (crg::ResourcesCache & resources, castor::Array< Texture const *, size_t(TextureEnumT::eCount) > const & inputs, castor::String const & prefix, VkImageCreateFlags createFlags, castor::Size const & size, uint32_t layerCount, VkSampleCountFlagBits sampleCount, castor::Vector< TextureUPtr > & owned) const inline protected
Initialises 2D or 2D array g-buffer textures.
Parameters
[in] resources The render graph resource handler.
[in] inputs The already existing images.
[in] prefix The buffer's textures name's prefix.
[in] createFlags The creation flags for images remaining to create.
[in] size The g-buffer's dimensions.
[in] layerCount The layers count for the g-buffer.
[in] sampleCount The images samples count.
[out] owned The images that are owned by the g-buffer.
References doCreateTexture(), castor3d::getBorderColor(), castor3d::getCompareOp(), castor3d::getFormat(), castor::Size::getHeight(), castor3d::getMipLevels(), castor3d::getTexName(), castor3d::getUsageFlags(), castor::Size::getWidth(), and m_device.
doCreateTextures() [2/2]
template<typename TextureEnumT > castor::Vector< Texture const * > castor3d::GBufferBase::doCreateTextures (crg::ResourcesCache & resources, castor::Array< Texture const *, size_t(TextureEnumT::eCount) > const & inputs, castor::String const & prefix, VkImageCreateFlags createFlags, VkExtent3D const & size, VkSampleCountFlagBits sampleCount, castor::Vector< TextureUPtr > & owned) const inline protected
Initialises 3D g-buffer textures.
Parameters
[in] resources The render graph resource handler.
[in] inputs The already existing images.
[in] prefix The buffer's textures name's prefix.
[in] createFlags The creation flags for images remaining to create.
[in] size The g-buffer's dimensions.
[in] sampleCount The images samples count.
[out] owned The images that are owned by the g-buffer.
References doCreateTexture(), castor3d::getBorderColor(), castor3d::getCompareOp(), castor3d::getFormat(), castor3d::getMipLevels(), castor3d::getTexName(), castor3d::getUsageFlags(), and m_device.
Member Data Documentation
m_device
RenderDevice const& castor3d::GBufferBase::m_device protected
Referenced by doCreateTextures(), and doCreateTextures().
The documentation for this class was generated from the following file:
Castor3D/Render/GBuffer.hpp