Castor3D: Castor3D::RenderPipeline Class Reference
Castor3D::RenderPipeline Class Reference abstract
The rendering pipeline.
Public Member Functions
C3D_API RenderPipeline (RenderSystem &p_renderSystem, DepthStencilState &&p_dsState, RasteriserState &&p_rsState, BlendState &&p_blState, MultisampleState &&p_msState, ShaderProgram &p_program, PipelineFlags const &p_flags)
Constructor.
virtual C3D_API ~RenderPipeline ()
Denstructor.
C3D_API void Cleanup ()
Cleans up the pipeline.
virtual C3D_API void Apply () const =0
Applies the pipeline.
C3D_API void AddUniformBuffer (UniformBuffer &p_ubo)
Adds a uniform buffer to the pipeline.
C3D_API bool Project (Castor::Point3r const &p_screen, Castor::Point4r const &p_viewport, Castor::Point3r &p_result)
Projects the given screen point to 3D scene point.
C3D_API bool UnProject (Castor::Point3i const &p_scene, Castor::Point4r const &p_viewport, Castor::Point3r &p_result)
Unprojects the given scene point to screen point.
C3D_API void ApplyProjection (UniformBuffer const &p_matrixBuffer) const
Puts the current projection matrix into the given frame variables buffer.
C3D_API void ApplyModel (UniformBuffer const &p_matrixBuffer) const
Puts the current model matrix into the given frame variables buffer.
C3D_API void ApplyView (UniformBuffer const &p_matrixBuffer) const
Puts the current vieww matrix into the given frame variables buffer.
C3D_API void ApplyNormal (UniformBuffer const &p_matrixBuffer)
Puts the current normals matrix into the given frame variables buffer.
C3D_API void ApplyTexture (uint32_t p_index, UniformBuffer const &p_matrixBuffer) const
Puts the current texture 0 matrix into the given frame variables buffer.
C3D_API void ApplyMatrices (UniformBuffer const &p_matrixBuffer, uint64_t p_matricesMask)
Puts all the matrices in the given frame variables buffer.
void SetModelMatrix (Castor::Matrix4x4r const &p_mtx)
Sets the model matrix.
void SetViewMatrix (Castor::Matrix4x4r const &p_mtx)
Sets the view matrix.
void SetProjectionMatrix (Castor::Matrix4x4r const &p_mtx)
Sets the projection matrix.
void SetTextureMatrix (uint32_t p_index, Castor::Matrix4x4r const &p_mtx)
Sets the projection matrix.
Castor::Matrix4x4r const & GetModelMatrix () const
Castor::Matrix4x4r const & GetViewMatrix () const
Castor::Matrix4x4r const & GetProjectionMatrix () const
Castor::Matrix4x4r const & GetTextureMatrix (uint32_t p_index) const
Retrieves the texture matrix for given index.
ShaderProgram const & GetProgram () const
ShaderProgram & GetProgram ()
PipelineFlags const & GetFlags () const
uint32_t GetTexturesCount ()
PushUniform1s & GetDirectionalShadowMapsVariable ()
PushUniform1s & GetSpotShadowMapsVariable ()
PushUniform1s & GetPointShadowMapsVariable ()
Static Public Attributes
static C3D_API const Castor::String MtxProjection
static C3D_API const Castor::String MtxModel
static C3D_API const Castor::String MtxView
static C3D_API const Castor::String MtxNormal
static C3D_API const Castor::String MtxTexture [C3D_MAX_TEXTURE_MATRICES]
Protected Attributes
Castor::Matrix4x4r m_mtxModel
Castor::Matrix4x4r m_mtxView
Castor::Matrix4x4r m_mtxProjection
Castor::Matrix4x4r m_mtxNormal
Castor::Matrix4x4r m_mtxTexture [C3D_MAX_TEXTURE_MATRICES]
DepthStencilState m_dsState
RasteriserState m_rsState
BlendState m_blState
MultisampleState m_msState
ShaderProgram & m_program
UniformBufferSPtr m_sceneUbo
PushUniform1sSPtr m_directionalShadowMaps
PushUniform1sSPtr m_spotShadowMaps
PushUniform1sSPtr m_pointShadowMaps
PipelineFlags m_flags
uint32_t m_textureCount { 0u }
std::vector< std::reference_wrapper< UniformBufferBinding > > m_bindings
Detailed Description
The rendering pipeline.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
03/01/2011
Remarks
Defines the various matrices, applies the transformations it can support.
Constructor & Destructor Documentation
RenderPipeline()
C3D_API Castor3D::RenderPipeline::RenderPipeline (RenderSystem & p_renderSystem, DepthStencilState && p_dsState, RasteriserState && p_rsState, BlendState && p_blState, MultisampleState && p_msState, ShaderProgram & p_program, PipelineFlags const & p_flags) explicit
Constructor.
Parameters
[in] p_renderSystem The parent RenderSystem.
[in] p_dsState The depth stencil state.
[in] p_rsState The rateriser state.
[in] p_blState The blend state.
[in] p_msState The multisample state.
[in] p_program The shader program.
[in] p_flags The creation flags.
~RenderPipeline()
virtual C3D_API Castor3D::RenderPipeline::~RenderPipeline () virtual
Denstructor.
Member Function Documentation
AddUniformBuffer()
C3D_API void Castor3D::RenderPipeline::AddUniformBuffer (UniformBuffer & p_ubo)
Adds a uniform buffer to the pipeline.
Remarks
Creates the binding for this uniform buffer, using the pipeline's program.
Apply()
virtual C3D_API void Castor3D::RenderPipeline::Apply () const pure virtual
Applies the pipeline.
ApplyMatrices()
C3D_API void Castor3D::RenderPipeline::ApplyMatrices (UniformBuffer const & p_matrixBuffer, uint64_t p_matricesMask)
Puts all the matrices in the given frame variables buffer.
Parameters
[in] p_matrixBuffer The matrix variables buffer.
[in] p_matricesMask A bitwise OR combination of MASK_MTXMODE, to select the matrices to apply.
ApplyModel()
C3D_API void Castor3D::RenderPipeline::ApplyModel (UniformBuffer const & p_matrixBuffer) const
Puts the current model matrix into the given frame variables buffer.
Parameters
[in] p_matrixBuffer The matrix variables buffer.
ApplyNormal()
C3D_API void Castor3D::RenderPipeline::ApplyNormal (UniformBuffer const & p_matrixBuffer)
Puts the current normals matrix into the given frame variables buffer.
Parameters
[in] p_matrixBuffer The matrix variables buffer.
ApplyProjection()
C3D_API void Castor3D::RenderPipeline::ApplyProjection (UniformBuffer const & p_matrixBuffer) const
Puts the current projection matrix into the given frame variables buffer.
Parameters
[in] p_matrixBuffer The matrix variables buffer.
ApplyTexture()
C3D_API void Castor3D::RenderPipeline::ApplyTexture (uint32_t p_index, UniformBuffer const & p_matrixBuffer) const
Puts the current texture 0 matrix into the given frame variables buffer.
Parameters
[in] p_index The texture index.
[in] p_matrixBuffer The matrix variables buffer.
ApplyView()
C3D_API void Castor3D::RenderPipeline::ApplyView (UniformBuffer const & p_matrixBuffer) const
Puts the current vieww matrix into the given frame variables buffer.
Parameters
[in] p_matrixBuffer The matrix variables buffer.
Cleanup()
C3D_API void Castor3D::RenderPipeline::Cleanup ()
Cleans up the pipeline.
GetDirectionalShadowMapsVariable()
PushUniform1s& Castor3D::RenderPipeline::GetDirectionalShadowMapsVariable () inline
Returns
The directional lights shadow maps frame variable.
References m_directionalShadowMaps.
Referenced by Castor3D::DoFillShaderDepthMaps().
GetFlags()
PipelineFlags const& Castor3D::RenderPipeline::GetFlags () const inline
Returns
The creation flags.
References m_flags.
Referenced by Castor3D::DoBindPass(), Castor3D::DoFillShaderDepthMaps(), and Castor3D::DoUnbindPass().
GetModelMatrix()
Castor::Matrix4x4r const& Castor3D::RenderPipeline::GetModelMatrix () const inline
Returns
The model matrix.
References m_mtxModel.
GetPointShadowMapsVariable()
PushUniform1s& Castor3D::RenderPipeline::GetPointShadowMapsVariable () inline
Returns
The point lights shadow maps frame variable.
References m_pointShadowMaps.
Referenced by Castor3D::DoFillShaderDepthMaps().
GetProgram() [1/2]
ShaderProgram const& Castor3D::RenderPipeline::GetProgram () const inline
Returns
The shader program.
References m_program.
GetProgram() [2/2]
ShaderProgram& Castor3D::RenderPipeline::GetProgram () inline
Returns
The shader program.
References m_program.
GetProjectionMatrix()
Castor::Matrix4x4r const& Castor3D::RenderPipeline::GetProjectionMatrix () const inline
Returns
The projection matrix.
References m_mtxProjection.
GetSpotShadowMapsVariable()
PushUniform1s& Castor3D::RenderPipeline::GetSpotShadowMapsVariable () inline
Returns
The spot lights shadow maps frame variable.
References m_spotShadowMaps.
Referenced by Castor3D::DoFillShaderDepthMaps().
GetTextureMatrix()
Castor::Matrix4x4r const& Castor3D::RenderPipeline::GetTextureMatrix (uint32_t p_index) const inline
Retrieves the texture matrix for given index.
Parameters
[in] p_index The texture index.
Returns
The matrix.
References Castor3D::C3D_MAX_TEXTURE_MATRICES, and m_mtxTexture.
GetTexturesCount()
uint32_t Castor3D::RenderPipeline::GetTexturesCount () inline
Returns
The count of textures used by the program.
References m_textureCount.
Referenced by Castor3D::DoFillShaderDepthMaps().
GetViewMatrix()
Castor::Matrix4x4r const& Castor3D::RenderPipeline::GetViewMatrix () const inline
Returns
The view matrix.
References m_mtxView.
Project()
C3D_API bool Castor3D::RenderPipeline::Project (Castor::Point3r const & p_screen, Castor::Point4r const & p_viewport, Castor::Point3r & p_result)
Projects the given screen point to 3D scene point.
Parameters
[in] p_screen The screen coordinates.
[in] p_viewport The viewport.
[out] p_result Receives the scene coordinates.
Returns
false if the current mode is not valid.
SetModelMatrix()
void Castor3D::RenderPipeline::SetModelMatrix (Castor::Matrix4x4r const & p_mtx) inline
Sets the model matrix.
Parameters
[in] p_mtx The new matrix.
References m_mtxModel.
SetProjectionMatrix()
void Castor3D::RenderPipeline::SetProjectionMatrix (Castor::Matrix4x4r const & p_mtx) inline
Sets the projection matrix.
Parameters
[in] p_mtx The new matrix.
References m_mtxProjection.
SetTextureMatrix()
void Castor3D::RenderPipeline::SetTextureMatrix (uint32_t p_index, Castor::Matrix4x4r const & p_mtx) inline
Sets the projection matrix.
Parameters
[in] p_index The texture index.
[in] p_mtx The new matrix.
References Castor3D::C3D_MAX_TEXTURE_MATRICES, and m_mtxTexture.
SetViewMatrix()
void Castor3D::RenderPipeline::SetViewMatrix (Castor::Matrix4x4r const & p_mtx) inline
Sets the view matrix.
Parameters
[in] p_mtx The new matrix.
References m_mtxView.
UnProject()
C3D_API bool Castor3D::RenderPipeline::UnProject (Castor::Point3i const & p_scene, Castor::Point4r const & p_viewport, Castor::Point3r & p_result)
Unprojects the given scene point to screen point.
Parameters
[in] p_scene The scene coordinates.
[in] p_viewport The viewport.
[out] p_result Receives the screen coordinates.
Returns
false if the current mode is not valid.
Member Data Documentation
m_bindings
std::vector< std::reference_wrapper< UniformBufferBinding > > Castor3D::RenderPipeline::m_bindings protected
The uniform buffer bindings.
m_blState
BlendState Castor3D::RenderPipeline::m_blState protected
The blend state.
m_directionalShadowMaps
PushUniform1sSPtr Castor3D::RenderPipeline::m_directionalShadowMaps protected
The directional lights shadow maps frame variable.
Referenced by GetDirectionalShadowMapsVariable().
m_dsState
DepthStencilState Castor3D::RenderPipeline::m_dsState protected
The depth stencil state.
m_flags
PipelineFlags Castor3D::RenderPipeline::m_flags protected
The creation flags.
Referenced by GetFlags().
m_msState
MultisampleState Castor3D::RenderPipeline::m_msState protected
The muultisampling state.
m_mtxModel
Castor::Matrix4x4r Castor3D::RenderPipeline::m_mtxModel protected
The model matrix.
Referenced by GetModelMatrix(), and SetModelMatrix().
m_mtxNormal
Castor::Matrix4x4r Castor3D::RenderPipeline::m_mtxNormal protected
The normals matrix.
m_mtxProjection
Castor::Matrix4x4r Castor3D::RenderPipeline::m_mtxProjection protected
The projection matrix.
Referenced by GetProjectionMatrix(), and SetProjectionMatrix().
m_mtxTexture
Castor::Matrix4x4r Castor3D::RenderPipeline::m_mtxTexture[C3D_MAX_TEXTURE_MATRICES] protected
The texture matrices.
Referenced by GetTextureMatrix(), and SetTextureMatrix().
m_mtxView
Castor::Matrix4x4r Castor3D::RenderPipeline::m_mtxView protected
The view matrix.
Referenced by GetViewMatrix(), and SetViewMatrix().
m_pointShadowMaps
PushUniform1sSPtr Castor3D::RenderPipeline::m_pointShadowMaps protected
The point lights shadow maps frame variable.
Referenced by GetPointShadowMapsVariable().
m_program
ShaderProgram& Castor3D::RenderPipeline::m_program protected
The shader program.
Referenced by GetProgram().
m_rsState
RasteriserState Castor3D::RenderPipeline::m_rsState protected
The rateriser state.
m_sceneUbo
UniformBufferSPtr Castor3D::RenderPipeline::m_sceneUbo protected
The scene frame variable buffer.
m_spotShadowMaps
PushUniform1sSPtr Castor3D::RenderPipeline::m_spotShadowMaps protected
The spot lights shadow maps frame variable.
Referenced by GetSpotShadowMapsVariable().
m_textureCount
uint32_t Castor3D::RenderPipeline::m_textureCount { 0u } protected
The count of textures used by the program.
Referenced by GetTexturesCount().
MtxModel
C3D_API const Castor::String Castor3D::RenderPipeline::MtxModel static
MtxNormal
C3D_API const Castor::String Castor3D::RenderPipeline::MtxNormal static
MtxProjection
C3D_API const Castor::String Castor3D::RenderPipeline::MtxProjection static
MtxTexture
C3D_API const Castor::String Castor3D::RenderPipeline::MtxTexture[C3D_MAX_TEXTURE_MATRICES] static
MtxView
C3D_API const Castor::String Castor3D::RenderPipeline::MtxView static
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Render/RenderPipeline.hpp