Castor3D: castor3d::ChunkWriterBase Class Reference
castor3d::ChunkWriterBase Class Reference
Chunk writer.
Static Public Member Functions
static bool write (uint8_t const *p_begin, uint8_t const *p_end, ChunkType p_type, BinaryChunk &p_chunk)
Writes a subchunk value into a chunk.
Detailed Description
Chunk writer.
Author
Sylvain DOREMUS
Version
0.9.0
Date
30/05/2016
Member Function Documentation
write()
static bool castor3d::ChunkWriterBase::write (uint8_t const * p_begin, uint8_t const * p_end, ChunkType p_type, BinaryChunk & p_chunk) inline static
Writes a subchunk value into a chunk.
Parameters
[in] p_begin The values begin
[in] p_end The values end
[in] p_type The subchunk type
[in] p_chunk The chunk
Returns
false if any error occured
References castor3d::BinaryChunk::addSubChunk(), and castor3d::BinaryChunk::setData().
Referenced by castor3d::ChunkWriter< T >::write(), castor3d::ChunkWriter< castor::String >::write(), and castor3d::ChunkWriter< castor::Path >::write().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Binary/ChunkWriter.hpp