Castor3D: castor3d::SubmeshComponent Class Reference
castor3d::SubmeshComponent Class Reference abstract
#include <SubmeshComponent.hpp>
Public Member Functions
C3D_API SubmeshComponent (Submesh &submesh, castor::String const &type, uint32_t id)
Constructor.
virtual C3D_API ~SubmeshComponent () noexcept=default
Destructor.
C3D_API bool initialise (RenderDevice const &device)
Initialises the submesh.
C3D_API void cleanup (RenderDevice const &device)
Cleans the submesh.
C3D_API void upload ()
Uploads data on VRAM.
virtual C3D_API void gather (ShaderFlags const &shaderFlags, ProgramFlags const &programFlags, SubmeshFlags const &submeshFlags, MaterialRPtr material, TextureFlagsArray const &mask, ashes::BufferCRefArray &buffers, std::vector< uint64_t > &offsets, ashes::PipelineVertexInputStateCreateInfoCRefArray &layouts, uint32_t &currentBinding, uint32_t &currentLocation)=0
Gathers buffers that need to go in a vertex layout.
virtual C3D_API ProgramFlags getProgramFlags (Material const &material) const
virtual C3D_API SubmeshFlags getSubmeshFlags (Pass const *pass) const
virtual C3D_API VkBufferUsageFlags getUsageFlags () const
virtual C3D_API SubmeshComponentSPtr clone (Submesh &submesh) const =0
castor::String const & getType () const
void needsUpdate ()
Sets the component to be updated.
uint32_t getID ()
Constructor & Destructor Documentation
SubmeshComponent()
C3D_API castor3d::SubmeshComponent::SubmeshComponent (Submesh & submesh, castor::String const & type, uint32_t id)
Constructor.
Parameters
[in] submesh The parent submesh.
[in] type The component type.
[in] id The component ID.
~SubmeshComponent()
virtual C3D_API castor3d::SubmeshComponent::~SubmeshComponent () virtual default noexcept
Destructor.
Member Function Documentation
cleanup()
C3D_API void castor3d::SubmeshComponent::cleanup (RenderDevice const & device)
Cleans the submesh.
clone()
virtual C3D_API SubmeshComponentSPtr castor3d::SubmeshComponent::clone (Submesh & submesh) const pure virtual
Returns
Clones this component into given submesh.
Parameters
[in,out] submesh Receives the cloned component.
Implemented in castor3d::BaseDataComponentT< SubmeshFlagT >, castor3d::InstantiationComponent, castor3d::LinesMapping, castor3d::MeshletComponent, castor3d::MorphComponent, castor3d::SkinComponent, and castor3d::TriFaceMapping.
gather()
virtual C3D_API void castor3d::SubmeshComponent::gather (ShaderFlags const & shaderFlags, ProgramFlags const & programFlags, SubmeshFlags const & submeshFlags, MaterialRPtr material, TextureFlagsArray const & mask, ashes::BufferCRefArray & buffers, std::vector< uint64_t > & offsets, ashes::PipelineVertexInputStateCreateInfoCRefArray & layouts, uint32_t & currentBinding, uint32_t & currentLocation) pure virtual
Gathers buffers that need to go in a vertex layout.
Parameters
[in] shaderFlags The shader flags.
[in] programFlags The program flags.
[in] submeshFlags The submesh flags.
[in] material The material.
[in] mask The textures mask.
[in,out] buffers Receives the buffers.
[in,out] offsets Receives the buffers offsets.
[in,out] layouts Receives the vertex layouts.
[in,out] currentBinding The current buffer binding.
[in,out] currentLocation The current attribute location.
Implemented in castor3d::BaseDataComponentT< SubmeshFlagT >, castor3d::IndexMapping, castor3d::InstantiationComponent, castor3d::MeshletComponent, castor3d::MorphComponent, and castor3d::SkinComponent.
getID()
uint32_t castor3d::SubmeshComponent::getID () inline
Returns
The component binding ID.
getProgramFlags()
virtual C3D_API ProgramFlags castor3d::SubmeshComponent::getProgramFlags (Material const & material) const inline virtual
Returns
The program flags.
Parameters
[in] material The material.
Reimplemented in castor3d::InstantiationComponent, and castor3d::MeshletComponent.
getSubmeshFlags()
virtual C3D_API SubmeshFlags castor3d::SubmeshComponent::getSubmeshFlags (Pass const * pass) const inline virtual
Returns
The submesh flags.
Reimplemented in castor3d::BaseDataComponentT< SubmeshFlagT >, castor3d::IndexMapping, and castor3d::SkinComponent.
getType()
castor::String const & castor3d::SubmeshComponent::getType () const inline
Returns
The component type name.
getUsageFlags()
virtual C3D_API VkBufferUsageFlags castor3d::SubmeshComponent::getUsageFlags () const inline virtual
Returns
The buffer usage flags.
Reimplemented in castor3d::IndexMapping.
initialise()
C3D_API bool castor3d::SubmeshComponent::initialise (RenderDevice const & device)
Initialises the submesh.
needsUpdate()
void castor3d::SubmeshComponent::needsUpdate () inline
Sets the component to be updated.
Referenced by castor3d::InstantiationComponent::find(), castor3d::MeshletComponent::getCullData(), and castor3d::MeshletComponent::getMeshletsData().
upload()
C3D_API void castor3d::SubmeshComponent::upload ()
Uploads data on VRAM.
Remarks
For host visible buffers.
The documentation for this class was generated from the following file:
Model/Mesh/Submesh/Component/SubmeshComponent.hpp