Castor3D: castor3d::SkinComponent Class Reference
castor3d::SkinComponent Class Reference
#include <SkinComponent.hpp>
Public Member Functions
C3D_API SkinComponent (Submesh &submesh)
Constructor.
C3D_API void addDatas (VertexBoneData const *const begin, VertexBoneData const *const end)
adds bone datas.
C3D_API SkeletonRPtr getSkeleton () const
C3D_API void gather (ShaderFlags const &shaderFlags, ProgramFlags const &programFlags, SubmeshFlags const &submeshFlags, MaterialRPtr material, TextureFlagsArray const &mask, ashes::BufferCRefArray &buffers, std::vector< uint64_t > &offsets, ashes::PipelineVertexInputStateCreateInfoCRefArray &layouts, uint32_t &currentBinding, uint32_t &currentLocation) override
Gathers buffers that need to go in a vertex layout.
C3D_API SubmeshComponentSPtr clone (Submesh &submesh) const override
C3D_API void addDatas (std::vector< VertexBoneData > const &boneData)
adds bone datas.
template<size_t Count>
void addDatas (std::array< VertexBoneData, Count > const &boneData)
adds bone datas.
SubmeshFlags getSubmeshFlags (Pass const *pass) const override
bool hasData () const
VertexBoneDataArray & getData ()
VertexBoneDataArray const & getData () const
Public Member Functions inherited from castor3d::SubmeshComponent
C3D_API SubmeshComponent (Submesh &submesh, castor::String const &type, uint32_t id)
Constructor.
virtual C3D_API ~SubmeshComponent () noexcept=default
Destructor.
C3D_API bool initialise (RenderDevice const &device)
Initialises the submesh.
C3D_API void cleanup (RenderDevice const &device)
Cleans the submesh.
C3D_API void upload ()
Uploads data on VRAM.
virtual C3D_API void gather (ShaderFlags const &shaderFlags, ProgramFlags const &programFlags, SubmeshFlags const &submeshFlags, MaterialRPtr material, TextureFlagsArray const &mask, ashes::BufferCRefArray &buffers, std::vector< uint64_t > &offsets, ashes::PipelineVertexInputStateCreateInfoCRefArray &layouts, uint32_t &currentBinding, uint32_t &currentLocation)=0
Gathers buffers that need to go in a vertex layout.
virtual C3D_API ProgramFlags getProgramFlags (Material const &material) const
virtual C3D_API SubmeshFlags getSubmeshFlags (Pass const *pass) const
virtual C3D_API VkBufferUsageFlags getUsageFlags () const
virtual C3D_API SubmeshComponentSPtr clone (Submesh &submesh) const =0
castor::String const & getType () const
void needsUpdate ()
Sets the component to be updated.
uint32_t getID ()
Static Public Attributes
static C3D_API castor::String const Name
static C3D_API uint32_t constexpr Id = getIndex(SubmeshFlag::eSkin) - 1u
Friends
class BinaryWriter< SkinComponent >
class BinaryParser< SkinComponent >
Constructor & Destructor Documentation
SkinComponent()
C3D_API castor3d::SkinComponent::SkinComponent (Submesh & submesh) explicit
Constructor.
Parameters
[in] submesh The parent submesh.
Member Function Documentation
addDatas() [1/3]
template<size_t Count> void castor3d::SkinComponent::addDatas (std::array< VertexBoneData, Count > const & boneData) inline
adds bone datas.
Parameters
[in] boneData The bone datas.
References addDatas().
addDatas() [2/3]
C3D_API void castor3d::SkinComponent::addDatas (std::vector< VertexBoneData > const & boneData)
adds bone datas.
Parameters
[in] boneData The bone datas.
addDatas() [3/3]
C3D_API void castor3d::SkinComponent::addDatas (VertexBoneData const *const begin, VertexBoneData const *const end)
adds bone datas.
Parameters
[in] begin The bones data begin.
[in] end The bones data end.
Referenced by addDatas().
clone()
C3D_API SubmeshComponentSPtr castor3d::SkinComponent::clone (Submesh & submesh) const override virtual
Returns
Clones this component into given submesh.
Parameters
[in,out] submesh Receives the cloned component.
Implements castor3d::SubmeshComponent.
gather()
C3D_API void castor3d::SkinComponent::gather (ShaderFlags const & shaderFlags, ProgramFlags const & programFlags, SubmeshFlags const & submeshFlags, MaterialRPtr material, TextureFlagsArray const & mask, ashes::BufferCRefArray & buffers, std::vector< uint64_t > & offsets, ashes::PipelineVertexInputStateCreateInfoCRefArray & layouts, uint32_t & currentBinding, uint32_t & currentLocation) inline override virtual
Gathers buffers that need to go in a vertex layout.
Parameters
[in] shaderFlags The shader flags.
[in] programFlags The program flags.
[in] submeshFlags The submesh flags.
[in] material The material.
[in] mask The textures mask.
[in,out] buffers Receives the buffers.
[in,out] offsets Receives the buffers offsets.
[in,out] layouts Receives the vertex layouts.
[in,out] currentBinding The current buffer binding.
[in,out] currentLocation The current attribute location.
Implements castor3d::SubmeshComponent.
getData() [1/2]
VertexBoneDataArray & castor3d::SkinComponent::getData () inline
getData() [2/2]
VertexBoneDataArray const & castor3d::SkinComponent::getData () const inline
getSkeleton()
C3D_API SkeletonRPtr castor3d::SkinComponent::getSkeleton () const
Returns
The skeleton.
getSubmeshFlags()
SubmeshFlags castor3d::SkinComponent::getSubmeshFlags (Pass const * pass) const inline override virtual
Returns
The submesh flags.
Reimplemented from castor3d::SubmeshComponent.
References castor3d::eSkin, and hasData().
hasData()
bool castor3d::SkinComponent::hasData () const inline
Referenced by getSubmeshFlags().
Friends And Related Function Documentation
BinaryParser< SkinComponent >
friend class BinaryParser< SkinComponent > friend
BinaryWriter< SkinComponent >
friend class BinaryWriter< SkinComponent > friend
Member Data Documentation
Id
C3D_API uint32_t constexpr castor3d::SkinComponent::Id = getIndex(SubmeshFlag::eSkin) - 1u static constexpr
Name
C3D_API castor::String const castor3d::SkinComponent::Name static
The documentation for this class was generated from the following file:
Model/Mesh/Submesh/Component/SkinComponent.hpp