Castor3D: Castor3D::UniformBuffer Class Reference
Castor3D::UniformBuffer Class Reference
Shader variables buffer.
Classes
class TextWriter
UniformBuffer loader.
Public Member Functions
UniformBuffer (UniformBuffer const &)=delete
UniformBuffer (UniformBuffer &&)=default
UniformBuffer & operator= (UniformBuffer const &)=delete
UniformBuffer & operator= (UniformBuffer &&)=default
C3D_API UniformBuffer (Castor::String const &p_name, RenderSystem &p_renderSystem)
Constructor.
virtual C3D_API ~UniformBuffer ()
Destructor.
C3D_API void Cleanup ()
Cleans all the variables up and the GPU buffer associated.
C3D_API void Update ()
Updates the GPU storage.
C3D_API UniformBufferBinding & CreateBinding (ShaderProgram &p_program)
Creates a binding of this unifor buffer to given program.
C3D_API UniformBufferBinding & GetBinding (ShaderProgram &p_program) const
Retrieves the binding for given program.
C3D_API UniformSPtr CreateUniform (UniformType p_type, Castor::String const &p_name, uint32_t p_occurences=1)
Creates a variable of the wanted type.
template<UniformType Type>
std::shared_ptr< typename uniform_type< Type >::type > CreateUniform (Castor::String const &p_name, int p_occurences=1)
Creates a variable.
C3D_API void RemoveUniform (Castor::String const &p_name)
Removes a variable from this buffer.
template<UniformType Type>
std::shared_ptr< TUniform< Type > > GetUniform (Castor::String const &p_name) const
Retrieves a variable by name.
GpuBuffer< uint8_t > & GetStorage () const
UniformList::iterator begin ()
UniformList::const_iterator begin () const
UniformList::iterator end ()
UniformList::const_iterator end () const
Static Public Member Functions
static C3D_API void FillMatrixBuffer (UniformBuffer &p_ubo)
Fills a UBO with matrix related variables.
static C3D_API void FillModelMatrixBuffer (UniformBuffer &p_ubo)
Fills a UBO with model matrix related variables.
static C3D_API void FillSceneBuffer (UniformBuffer &p_ubo)
Fills a UBO with scene related variables.
static C3D_API void FillPassBuffer (UniformBuffer &p_ubo)
Fills a UBO with pass related variables.
static C3D_API void FillModelBuffer (UniformBuffer &p_ubo)
Fills a UBO with model related variables.
static C3D_API void FillSkinningBuffer (UniformBuffer &p_ubo)
Fills a UBO with skinning animation related variables.
static C3D_API void FillMorphingBuffer (UniformBuffer &p_ubo)
Fills a UBO with morphing animation related variables.
static C3D_API void FillBillboardBuffer (UniformBuffer &p_ubo)
Fills a UBO with billboard related variables.
static C3D_API void FillOverlayBuffer (UniformBuffer &p_ubo)
Fills a UBO with overlay related variables.
Protected Attributes
UniformList m_listVariables
UniformMap m_mapVariables
Castor::ByteArray m_buffer
std::unique_ptr< GpuBuffer< uint8_t > > m_storage
UniformBufferBindingMap m_bindings
Friends
class Castor::TextWriter< Castor3D::UniformBuffer >
Detailed Description
Shader variables buffer.
Author
Sylvain DOREMUS
Version
0.7.0.0
Date
19/04/2013
Remarks
It stores all variables held by a ShaderProgram or a ShaderObject
It is also in charge of the creation of the variables
Uses GPU buffers if supported (OpenGL Uniform Buffer Objects, Direct3D Constants buffers)
Constructor & Destructor Documentation
UniformBuffer() [1/3]
Castor3D::UniformBuffer::UniformBuffer (UniformBuffer const &) delete
UniformBuffer() [2/3]
Castor3D::UniformBuffer::UniformBuffer (UniformBuffer &&) default
UniformBuffer() [3/3]
C3D_API Castor3D::UniformBuffer::UniformBuffer (Castor::String const & p_name, RenderSystem & p_renderSystem)
Constructor.
Parameters
[in] p_name The buffer name.
[in] p_renderSystem The render system.
~UniformBuffer()
virtual C3D_API Castor3D::UniformBuffer::~UniformBuffer () virtual
Destructor.
Member Function Documentation
begin() [1/2]
UniformList::iterator Castor3D::UniformBuffer::begin () inline
Returns
The iterator to the beginnning of the variables list.
References m_listVariables.
begin() [2/2]
UniformList::const_iterator Castor3D::UniformBuffer::begin () const inline
Returns
The iterator to the beginnning of the variables list.
References m_listVariables.
Cleanup()
C3D_API void Castor3D::UniformBuffer::Cleanup ()
Cleans all the variables up and the GPU buffer associated.
CreateBinding()
C3D_API UniformBufferBinding& Castor3D::UniformBuffer::CreateBinding (ShaderProgram & p_program)
Creates a binding of this unifor buffer to given program.
Remarks
If this is the first binding created, the GPU storage and variables will be initialised.
Parameters
[in] p_program The program.
Returns
The created binding.
CreateUniform() [1/2]
C3D_API UniformSPtr Castor3D::UniformBuffer::CreateUniform (UniformType p_type, Castor::String const & p_name, uint32_t p_occurences = 1)
Creates a variable of the wanted type.
Parameters
[in] p_type The wanted type.
[in] p_name The variable name.
[in] p_occurences The array dimension.
Returns
The created variable, nullptr if failed.
Referenced by CreateUniform().
CreateUniform() [2/2]
template<UniformType Type> std::shared_ptr< typename uniform_type< Type >::type > Castor3D::UniformBuffer::CreateUniform (Castor::String const & p_name, int p_occurences = 1) inline
Creates a variable.
Parameters
[in] p_name The variable name.
[in] p_occurences The array dimension.
Returns
The created variable, nullptr if failed.
References CreateUniform().
end() [1/2]
UniformList::iterator Castor3D::UniformBuffer::end () inline
Returns
The iterator to the end of the variables list.
References m_listVariables.
end() [2/2]
UniformList::const_iterator Castor3D::UniformBuffer::end () const inline
Returns
The iterator to the end of the variables list.
References m_listVariables.
FillBillboardBuffer()
static C3D_API void Castor3D::UniformBuffer::FillBillboardBuffer (UniformBuffer & p_ubo) static
Fills a UBO with billboard related variables.
Parameters
[in] p_ubo The UBO to fill.
FillMatrixBuffer()
static C3D_API void Castor3D::UniformBuffer::FillMatrixBuffer (UniformBuffer & p_ubo) static
Fills a UBO with matrix related variables.
Parameters
[in] p_ubo The UBO to fill.
FillModelBuffer()
static C3D_API void Castor3D::UniformBuffer::FillModelBuffer (UniformBuffer & p_ubo) static
Fills a UBO with model related variables.
Parameters
[in] p_ubo The UBO to fill.
FillModelMatrixBuffer()
static C3D_API void Castor3D::UniformBuffer::FillModelMatrixBuffer (UniformBuffer & p_ubo) static
Fills a UBO with model matrix related variables.
Parameters
[in] p_ubo The UBO to fill.
FillMorphingBuffer()
static C3D_API void Castor3D::UniformBuffer::FillMorphingBuffer (UniformBuffer & p_ubo) static
Fills a UBO with morphing animation related variables.
Parameters
[in] p_ubo The UBO to fill.
FillOverlayBuffer()
static C3D_API void Castor3D::UniformBuffer::FillOverlayBuffer (UniformBuffer & p_ubo) static
Fills a UBO with overlay related variables.
Parameters
[in] p_ubo The UBO to fill.
FillPassBuffer()
static C3D_API void Castor3D::UniformBuffer::FillPassBuffer (UniformBuffer & p_ubo) static
Fills a UBO with pass related variables.
Parameters
[in] p_ubo The UBO to fill.
FillSceneBuffer()
static C3D_API void Castor3D::UniformBuffer::FillSceneBuffer (UniformBuffer & p_ubo) static
Fills a UBO with scene related variables.
Parameters
[in] p_ubo The UBO to fill.
FillSkinningBuffer()
static C3D_API void Castor3D::UniformBuffer::FillSkinningBuffer (UniformBuffer & p_ubo) static
Fills a UBO with skinning animation related variables.
Parameters
[in] p_ubo The UBO to fill.
GetBinding()
C3D_API UniformBufferBinding& Castor3D::UniformBuffer::GetBinding (ShaderProgram & p_program) const
Retrieves the binding for given program.
Parameters
[in] p_program The program.
Returns
The retrieved binding.
GetStorage()
GpuBuffer< uint8_t >& Castor3D::UniformBuffer::GetStorage () const inline
Returns
The GPU storage.
References m_storage.
GetUniform()
template<UniformType Type> std::shared_ptr< TUniform< Type > > Castor3D::UniformBuffer::GetUniform (Castor::String const & p_name) const inline
Retrieves a variable by name.
Parameters
[in] p_name The variable name.
Returns
The retrieved variable, nullptr if not found.
operator=() [1/2]
UniformBuffer& Castor3D::UniformBuffer::operator= (UniformBuffer const &) delete
operator=() [2/2]
UniformBuffer& Castor3D::UniformBuffer::operator= (UniformBuffer &&) default
RemoveUniform()
C3D_API void Castor3D::UniformBuffer::RemoveUniform (Castor::String const & p_name)
Removes a variable from this buffer.
Parameters
[in] p_name The variable name.
Update()
C3D_API void Castor3D::UniformBuffer::Update ()
Updates the GPU storage.
Referenced by Castor3D::DoBindPass(), and Castor3D::DoRenderNodeNoPass().
Friends And Related Function Documentation
Castor::TextWriter< Castor3D::UniformBuffer >
friend class Castor::TextWriter< Castor3D::UniformBuffer > friend
Member Data Documentation
m_bindings
UniformBufferBindingMap Castor3D::UniformBuffer::m_bindings protected
The bindings per program.
m_buffer
Castor::ByteArray Castor3D::UniformBuffer::m_buffer protected
The data buffer.
m_listVariables
UniformList Castor3D::UniformBuffer::m_listVariables protected
The variables list.
Referenced by begin(), and end().
m_mapVariables
UniformMap Castor3D::UniformBuffer::m_mapVariables protected
The variables ordered by name.
m_storage
std::unique_ptr< GpuBuffer< uint8_t > > Castor3D::UniformBuffer::m_storage protected
The GPU buffer.
Referenced by GetStorage().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Shader/UniformBuffer.hpp