Castor3D: castor3d::TextOverlay Class Reference
castor3d::TextOverlay Class Reference
Classes
struct Vertex
Holds specific vertex data for a TextOverlay.
Public Member Functions
CU_DeclareVector (Vertex, Vertex)
CU_DeclareMap (char32_t, castor::Position, GlyphPosition)
C3D_API TextOverlay ()
Constructor.
C3D_API ~TextOverlay ()
Destructor.
C3D_API void accept (OverlayVisitor &visitor) const override
Draws the overlay.
C3D_API void setFont (castor::String const &value)
Sets the text font.
castor::String const & getFontName () const
Retrieves the font name.
bool isChanged () const override
FontTextureSPtr getFontTexture () const
bool isFontChanged () const
VertexArray const & getTextVertex () const
Retrieves the panel vertex buffer.
castor::String getCaption () const
Retrieves the overlay text.
void setCaption (castor::String const &value)
Sets the overlay text.
void setCaption (castor::OutputStream const &value)
Sets the overlay text.
TextWrappingMode getTextWrappingMode () const
void setTextWrappingMode (TextWrappingMode value)
Sets text wrapping mode.
HAlign getHAlign () const
void setHAlign (HAlign value)
Defines the horizontal alignment.
VAlign getVAlign () const
void setVAlign (VAlign value)
Defines the vertical alignment.
TextTexturingMode getTexturingMode () const
void setTexturingMode (TextTexturingMode value)
Defines the text texture mapping mode.
TextLineSpacingMode getLineSpacingMode () const
void setLineSpacingMode (TextLineSpacingMode value)
Defines the lines spacing mode.
Public Member Functions inherited from castor3d::OverlayCategory
CU_DeclareVector (Vertex, Vertex)
C3D_API OverlayCategory (OverlayType type)
Constructor.
virtual C3D_API ~OverlayCategory ()
Destructor.
C3D_API void update (OverlayRenderer const &renderer)
Updates the overlay position, size...
virtual C3D_API void setMaterial (MaterialSPtr material)
Sets the material.
C3D_API castor::String const & getOverlayName () const
Retrieves the overlay name.
C3D_API castor::Position getAbsolutePosition (castor::Size const &size) const
Retrieves the absolute overlay position, in pixels.
C3D_API castor::Size getAbsoluteSize (castor::Size const &size) const
Retrieves the absolute overlay size, in pixels.
C3D_API castor::Point2f getRenderRatio (castor::Size const &size) const
C3D_API castor::Point2d getAbsolutePosition () const
Retrieves the absolute overlay position.
C3D_API castor::Point2d getAbsoluteSize () const
Retrieves the absolute overlay size.
C3D_API bool isSizeChanged () const
C3D_API bool isPositionChanged () const
void setPosition (castor::Point2d const &position)
Sets the overlay position.
void setSize (castor::Point2d const &size)
Sets the overlay size.
castor::Point2d const & getSize () const
Retrieves the overlay size.
castor::Point2d const & getPosition () const
Retrieves the overlay position.
castor::Size const & getPixelSize () const
Retrieves the overlay size.
castor::Position const & getPixelPosition () const
Retrieves the overlay position.
castor::Point2d & getSize ()
Retrieves the overlay size.
castor::Point2d & getPosition ()
Retrieves the overlay position.
castor::Size & getPixelSize ()
Retrieves the overlay size.
castor::Position & getPixelPosition ()
Retrieves the overlay position.
OverlayType getType () const
Retrieves the overlay type.
bool isVisible () const
Retrieves the visibility status.
MaterialSPtr getMaterial () const
Retrieves the material.
int getIndex () const
Retrieves the index.
int getLevel () const
Retrieves the level.
Overlay const & getOverlay () const
Retrieves the overlay.
Overlay & getOverlay ()
Retrieves the overlay.
void setOverlay (Overlay *value)
Sets the overlay.
void setVisible (bool value)
Sets the visibility status.
void setPixelPosition (castor::Position const &value)
Sets the overlay position.
void setPixelSize (castor::Size const &value)
Sets the overlay size.
void setOrder (int index, int level)
Sets the overlay order.
void setUV (castor::Point4d const &value)
Sets the overlay UV.
castor::Point4d const & getUV () const
Retrieves the overlay UV.
Static Public Member Functions
static C3D_API OverlayCategorySPtr create ()
Creation function, used by the factory.
Additional Inherited Members
Protected Member Functions inherited from castor3d::OverlayCategory
castor::Point2d doGetTotalSize (OverlayRenderer const &renderer) const
virtual void doUpdatePosition (OverlayRenderer const &renderer)
Updates the overlay position, taking care of wanted pixel position.
virtual void doUpdateSize (OverlayRenderer const &renderer)
Updates the overlay size, taking care of wanted pixel size.
Protected Attributes inherited from castor3d::OverlayCategory
Overlay * m_pOverlay { nullptr }
castor::Point2d m_position
castor::Point2d m_ptSize
castor::Position m_pxPosition
castor::Size m_size
castor::Size m_computeSize
bool m_visible { true }
MaterialWPtr m_pMaterial
int m_index { 0 }
int m_level { 0 }
castor::String m_strMatName
OverlayType m_type
bool m_sizeChanged { true }
bool m_positionChanged { true }
castor::Point4d m_uv { 0.0, 0.0, 1.0, 1.0 }
Constructor & Destructor Documentation
TextOverlay()
C3D_API castor3d::TextOverlay::TextOverlay ()
Constructor.
~TextOverlay()
C3D_API castor3d::TextOverlay::~TextOverlay ()
Destructor.
Member Function Documentation
accept()
C3D_API void castor3d::TextOverlay::accept (OverlayVisitor & visitor) const override virtual
Draws the overlay.
Implements castor3d::OverlayCategory.
create()
static C3D_API OverlayCategorySPtr castor3d::TextOverlay::create () static
Creation function, used by the factory.
Returns
An overlay
CU_DeclareMap()
castor3d::TextOverlay::CU_DeclareMap (char32_t , castor::Position , GlyphPosition)
CU_DeclareVector()
castor3d::TextOverlay::CU_DeclareVector (Vertex , Vertex)
getCaption()
castor::String castor3d::TextOverlay::getCaption () const inline
Retrieves the overlay text.
Returns
The value
getFontName()
castor::String const& castor3d::TextOverlay::getFontName () const inline
Retrieves the font name.
Returns
The value.
References getFontTexture().
getFontTexture()
FontTextureSPtr castor3d::TextOverlay::getFontTexture () const inline
Returns
The FontTexture.
Referenced by getFontName().
getHAlign()
HAlign castor3d::TextOverlay::getHAlign () const inline
Returns
The horizontal alignment.
getLineSpacingMode()
TextLineSpacingMode castor3d::TextOverlay::getLineSpacingMode () const inline
Returns
The lines spacing mode.
getTexturingMode()
TextTexturingMode castor3d::TextOverlay::getTexturingMode () const inline
Returns
The text texture mapping mode.
getTextVertex()
VertexArray const& castor3d::TextOverlay::getTextVertex () const inline
Retrieves the panel vertex buffer.
Returns
The buffer
getTextWrappingMode()
TextWrappingMode castor3d::TextOverlay::getTextWrappingMode () const inline
Returns
The text wrapping mode.
getVAlign()
VAlign castor3d::TextOverlay::getVAlign () const inline
Returns
The vertical alignment.
isChanged()
bool castor3d::TextOverlay::isChanged () const inline override virtual
Returns
true if this overlay's has changed.
Reimplemented from castor3d::OverlayCategory.
isFontChanged()
bool castor3d::TextOverlay::isFontChanged () const inline
Returns
true if this overlay's font has changed.
setCaption() [1/2]
void castor3d::TextOverlay::setCaption (castor::String const & value) inline
Sets the overlay text.
Parameters
[in] value The new value
Referenced by setCaption().
setCaption() [2/2]
void castor3d::TextOverlay::setCaption (castor::OutputStream const & value) inline
Sets the overlay text.
Parameters
[in] value The new value
References setCaption().
setFont()
C3D_API void castor3d::TextOverlay::setFont (castor::String const & value)
Sets the text font.
Parameters
[in] value The new value
setHAlign()
void castor3d::TextOverlay::setHAlign (HAlign value) inline
Defines the horizontal alignment.
Parameters
[in] value The new value
setLineSpacingMode()
void castor3d::TextOverlay::setLineSpacingMode (TextLineSpacingMode value) inline
Defines the lines spacing mode.
Parameters
[in] value The new value.
setTexturingMode()
void castor3d::TextOverlay::setTexturingMode (TextTexturingMode value) inline
Defines the text texture mapping mode.
Parameters
[in] value The new value.
setTextWrappingMode()
void castor3d::TextOverlay::setTextWrappingMode (TextWrappingMode value) inline
Sets text wrapping mode.
Parameters
[in] value The new value
setVAlign()
void castor3d::TextOverlay::setVAlign (VAlign value) inline
Defines the vertical alignment.
Parameters
[in] value The new value
The documentation for this class was generated from the following file:
Overlay/TextOverlay.hpp