Castor3D: castor::RgbColourT< ComponentType > Class Template Reference
castor::RgbColourT< ComponentType > Class Template Reference
RGB colour representation.
#include <RgbColour.hpp>
Public Member Functions
RgbColourT ()=default
RgbColourT (RgbColourT const &rhs)=default
RgbColourT & operator= (RgbColourT const &rhs)=default
RgbColourT (RgbColourT &&rhs) noexcept=default
RgbColourT & operator= (RgbColourT &&rhs) noexcept=default
~RgbColourT () noexcept=default
template<typename ComponentU >
RgbColourT (RgbColourT< ComponentU > const &rhs, float gamma=2.2f)
Constructor from other component type.
RgbColourT (float r, float g, float b)
Specified Constructor.
ColourComponentArrayIt begin ()
Retrieves an iterator to the first ColourComponent.
ColourComponentArrayConstIt begin () const
Retrieves a constant iterator to the first ColourComponent.
ColourComponentArrayIt end ()
Retrieves an iterator to beyond the last ColourComponent.
ColourComponentArrayConstIt end () const
Retrieves a constant iterator to beyond the last ColourComponent.
float const * constPtr () const
Retrieves a constant pointer to the colour values.
float * ptr ()
Retrieves a pointer to the colour values.
ComponentType & operator[] (RgbComponent component)
Retrieves the asked component value.
ComponentType const & operator[] (RgbComponent component) const
Retrieves the asked component value.
ComponentType & operator[] (size_t component)
Retrieves the asked component value.
ComponentType const & operator[] (size_t component) const
Retrieves the asked component value.
ComponentType & get (RgbComponent component)
Retrieves the asked component value.
ComponentType const & get (RgbComponent component) const
Retrieves the asked component value.
ComponentType & red ()
Retrieves the red component value.
ComponentType const & red () const
Retrieves the red component value.
ComponentType & green ()
Retrieves the green component value.
ComponentType const & green () const
Retrieves the green component value.
ComponentType & blue ()
Retrieves the blue component value.
ComponentType const & blue () const
Retrieves the blue component value.
RgbColourT & operator+= (RgbColourT const &rhs)
addition assignment operator
RgbColourT & operator-= (RgbColourT const &rhs)
Substraction assignment operator.
template<typename T >
RgbColourT & operator+= (T scalar)
addition assignment operator
template<typename T >
RgbColourT & operator-= (T scalar)
Substraction assignment operator.
template<typename T >
RgbColourT & operator*= (T scalar)
Multiplication assignment operator.
template<typename T >
RgbColourT & operator/= (T scalar)
Division assignment operator.
RgbColourT & operator+= (ComponentType const &component)
addition assignment operator
RgbColourT & operator-= (ComponentType const &component)
Substraction assignment operator.
RgbColourT & operator*= (ComponentType const &component)
Multiplication assignment operator.
RgbColourT & operator/= (ComponentType const &component)
Division assignment operator.
Static Public Member Functions
template<typename T1 , typename T2 , typename T3 >
static RgbColourT fromComponents (T1 const &r, T2 const &g, T3 const &b)
Constructor from components.
static RgbColourT fromPredefined (PredefinedRgbColour predefined)
Constructor from a predefined colour.
static RgbColourT fromRGB (Point3ub const &colour)
Constructor from a point representing RGB components.
static RgbColourT fromBGR (Point3ub const &colour)
Constructor from a point representing BGR components.
static RgbColourT fromRGBA (Point4ub const &colour)
Constructor from a point representing RGBA components.
static RgbColourT fromBGRA (Point4ub const &colour)
Constructor from a point representing BGRA components.
static RgbColourT fromARGB (Point4ub const &colour)
Constructor from a point representing ARGB components.
static RgbColourT fromABGR (Point4ub const &colour)
Constructor from a point representing ABGR components.
static RgbColourT fromRGB (Point3f const &colour)
Constructor from a point representing RGB components.
static RgbColourT fromBGR (Point3f const &colour)
Constructor from a point representing BGR components.
static RgbColourT fromRGBA (Point4f const &colour)
Constructor from a point representing RGBA components.
static RgbColourT fromARGB (Point4f const &colour)
Constructor from a point representing ARGB components.
static RgbColourT fromABGR (Point4f const &colour)
Constructor from a point representing ABGR components.
static RgbColourT fromBGRA (Point4f const &colour)
Constructor from a point representing BGRA components.
static RgbColourT fromRGB (uint8_t const(&colour)[3])
Constructor from a point representing RGB components.
static RgbColourT fromBGR (uint8_t const(&colour)[3])
Constructor from a point representing BGR components.
static RgbColourT fromRGBA (uint8_t const(&colour)[4])
Constructor from a point representing RGBA components.
static RgbColourT fromBGRA (uint8_t const(&colour)[4])
Constructor from a point representing BGRA components.
static RgbColourT fromARGB (uint8_t const(&colour)[4])
Constructor from a point representing ARGB components.
static RgbColourT fromABGR (uint8_t const(&colour)[4])
Constructor from a point representing ABGR components.
static RgbColourT fromRGB (float const(&colour)[3])
Constructor from a point representing RGB components.
static RgbColourT fromBGR (float const(&colour)[3])
Constructor from a point representing BGR components.
static RgbColourT fromRGBA (float const(&colour)[4])
Constructor from a point representing RGBA components.
static RgbColourT fromARGB (float const(&colour)[4])
Constructor from a point representing ARGB components.
static RgbColourT fromABGR (float const(&colour)[4])
Constructor from a point representing ABGR components.
static RgbColourT fromBGRA (float const(&colour)[4])
Constructor from a point representing BGRA components.
static RgbColourT fromRGB (uint32_t colour)
Constructor from an uint32_t representing RGB components.
static RgbColourT fromBGR (uint32_t colour)
Constructor from an uint32_t representing BGR components.
static RgbColourT fromARGB (uint32_t colour)
Constructor from an uint32_t representing ARGB components.
static RgbColourT fromRGBA (uint32_t colour)
Constructor from an uint32_t representing RGBA components.
static RgbColourT fromABGR (uint32_t colour)
Constructor from an uint32_t representing ABGR components.
static RgbColourT fromBGRA (uint32_t colour)
Constructor from an uint32_t representing BGRA components.
static RgbColourT fromHSB (float hue, float saturation, float brightness)
Constructor from an HSB components.
Friends
template<typename ComponentU >
class RgbColourT
Detailed Description
template<typename ComponentType>
class castor::RgbColourT< ComponentType >
RGB colour representation.
Remarks
Predefines numerous colours
Allows conversion to different colour formats (RGB, ARGB, BGR, ...) and different data types (long, float, char, ...)
Constructor & Destructor Documentation
RgbColourT() [1/5]
template<typename ComponentType > castor::RgbColourT< ComponentType >::RgbColourT () default
RgbColourT() [2/5]
template<typename ComponentType > castor::RgbColourT< ComponentType >::RgbColourT (RgbColourT< ComponentType > const & rhs) default
RgbColourT() [3/5]
template<typename ComponentType > castor::RgbColourT< ComponentType >::RgbColourT (RgbColourT< ComponentType > && rhs) default noexcept
~RgbColourT()
template<typename ComponentType > castor::RgbColourT< ComponentType >::~RgbColourT () default noexcept
RgbColourT() [4/5]
template<typename ComponentType > template<typename ComponentU > castor::RgbColourT< ComponentType >::RgbColourT (RgbColourT< ComponentU > const & rhs, float gamma = 2.2f) explicit
Constructor from other component type.
Parameters
[in] rhs The colour value.
[in] gamma The gamma correction value.
RgbColourT() [5/5]
template<typename ComponentType > castor::RgbColourT< ComponentType >::RgbColourT (float r, float g, float b)
Specified Constructor.
Member Function Documentation
begin() [1/2]
template<typename ComponentType > ColourComponentArrayIt castor::RgbColourT< ComponentType >::begin () inline
Retrieves an iterator to the first ColourComponent.
Returns
The iterator
begin() [2/2]
template<typename ComponentType > ColourComponentArrayConstIt castor::RgbColourT< ComponentType >::begin () const inline
Retrieves a constant iterator to the first ColourComponent.
Returns
The iterator
blue() [1/2]
template<typename ComponentType > ComponentType & castor::RgbColourT< ComponentType >::blue () inline
Retrieves the blue component value.
Returns
The component value
References castor::eBlue, and castor::RgbColourT< ComponentType >::get().
Referenced by castor3d::ControlStyle::doCreateMaterial().
blue() [2/2]
template<typename ComponentType > ComponentType const & castor::RgbColourT< ComponentType >::blue () const inline
Retrieves the blue component value.
Returns
The component value
References castor::eBlue, and castor::RgbColourT< ComponentType >::get().
constPtr()
template<typename ComponentType > float const * castor::RgbColourT< ComponentType >::constPtr () const inline
Retrieves a constant pointer to the colour values.
Returns
The pointer
Referenced by castor3d::getBuffer().
end() [1/2]
template<typename ComponentType > ColourComponentArrayIt castor::RgbColourT< ComponentType >::end () inline
Retrieves an iterator to beyond the last ColourComponent.
Returns
The iterator
end() [2/2]
template<typename ComponentType > ColourComponentArrayConstIt castor::RgbColourT< ComponentType >::end () const inline
Retrieves a constant iterator to beyond the last ColourComponent.
Returns
The iterator
fromABGR() [1/5]
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromABGR (float const(&) colour[4]) static
Constructor from a point representing ABGR components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromABGR() [2/5]
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromABGR (Point4f const & colour) static
Constructor from a point representing ABGR components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromABGR() [3/5]
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromABGR (Point4ub const & colour) static
Constructor from a point representing ABGR components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromABGR() [4/5]
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromABGR (uint32_t colour) static
Constructor from an uint32_t representing ABGR components.
Parameters
[in] colour The uint32_t containing the colour (0xAABBGGRR)
Returns
The built RgbColourT
fromABGR() [5/5]
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromABGR (uint8_t const(&) colour[4]) static
Constructor from a point representing ABGR components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromARGB() [1/5]
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromARGB (float const(&) colour[4]) static
Constructor from a point representing ARGB components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromARGB() [2/5]
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromARGB (Point4f const & colour) static
Constructor from a point representing ARGB components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromARGB() [3/5]
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromARGB (Point4ub const & colour) static
Constructor from a point representing ARGB components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromARGB() [4/5]
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromARGB (uint32_t colour) static
Constructor from an uint32_t representing ARGB components.
Parameters
[in] colour The uint32_t containing the colour (0xAARRGGBB)
Returns
The built RgbColourT
fromARGB() [5/5]
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromARGB (uint8_t const(&) colour[4]) static
Constructor from a point representing ARGB components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromBGR() [1/5]
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromBGR (float const(&) colour[3]) static
Constructor from a point representing BGR components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromBGR() [2/5]
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromBGR (Point3f const & colour) static
Constructor from a point representing BGR components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromBGR() [3/5]
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromBGR (Point3ub const & colour) static
Constructor from a point representing BGR components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromBGR() [4/5]
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromBGR (uint32_t colour) static
Constructor from an uint32_t representing BGR components.
Parameters
[in] colour The uint32_t containing the colour (0x00BBGGRR)
Returns
The built RgbColourT
fromBGR() [5/5]
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromBGR (uint8_t const(&) colour[3]) static
Constructor from a point representing BGR components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromBGRA() [1/5]
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromBGRA (float const(&) colour[4]) static
Constructor from a point representing BGRA components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromBGRA() [2/5]
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromBGRA (Point4f const & colour) static
Constructor from a point representing BGRA components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromBGRA() [3/5]
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromBGRA (Point4ub const & colour) static
Constructor from a point representing BGRA components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromBGRA() [4/5]
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromBGRA (uint32_t colour) static
Constructor from an uint32_t representing BGRA components.
Parameters
[in] colour The uint32_t containing the colour (0xBBGGRRAA)
Returns
The built RgbColourT
fromBGRA() [5/5]
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromBGRA (uint8_t const(&) colour[4]) static
Constructor from a point representing BGRA components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromComponents()
template<typename ComponentType > template<typename T1 , typename T2 , typename T3 > static RgbColourT castor::RgbColourT< ComponentType >::fromComponents (T1 const & r, T2 const & g, T3 const & b) inline static
Constructor from components.
Parameters
[in] r,g,b The colour components
Returns
The built RgbColourT
References castor::eBlue, castor::eGreen, and castor::eRed.
fromHSB()
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromHSB (float hue, float saturation, float brightness) static
Constructor from an HSB components.
Parameters
[in] hue,saturation,brightness The HSB components.
Returns
The built RgbaColourT.
fromPredefined()
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromPredefined (PredefinedRgbColour predefined) inline static
Constructor from a predefined colour.
Parameters
[in] predefined
Returns
The built RgbColourT
References castor::RgbColourT< ComponentType >::fromRGBA().
fromRGB() [1/5]
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromRGB (float const(&) colour[3]) static
Constructor from a point representing RGB components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromRGB() [2/5]
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromRGB (Point3f const & colour) static
Constructor from a point representing RGB components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromRGB() [3/5]
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromRGB (Point3ub const & colour) static
Constructor from a point representing RGB components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromRGB() [4/5]
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromRGB (uint32_t colour) static
Constructor from an uint32_t representing RGB components.
Parameters
[in] colour The uint32_t containing the colour (0x00RRGGBB)
Returns
The built RgbColourT
fromRGB() [5/5]
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromRGB (uint8_t const(&) colour[3]) static
Constructor from a point representing RGB components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromRGBA() [1/5]
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromRGBA (float const(&) colour[4]) static
Constructor from a point representing RGBA components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromRGBA() [2/5]
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromRGBA (Point4f const & colour) static
Constructor from a point representing RGBA components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
fromRGBA() [3/5]
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromRGBA (Point4ub const & colour) static
Constructor from a point representing RGBA components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
Referenced by castor::RgbColourT< ComponentType >::fromPredefined().
fromRGBA() [4/5]
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromRGBA (uint32_t colour) static
Constructor from an uint32_t representing RGBA components.
Parameters
[in] colour The uint32_t containing the colour (0xRRGGBBAA)
Returns
The built RgbColourT
fromRGBA() [5/5]
template<typename ComponentType > static RgbColourT castor::RgbColourT< ComponentType >::fromRGBA (uint8_t const(&) colour[4]) static
Constructor from a point representing RGBA components.
Parameters
[in] colour The point containing the colour components
Returns
The built RgbColourT
get() [1/2]
template<typename ComponentType > ComponentType & castor::RgbColourT< ComponentType >::get (RgbComponent component) inline
Retrieves the asked component value.
Parameters
[in] component The asked component
Returns
The component value
Referenced by castor::RgbColourT< ComponentType >::blue(), castor::RgbColourT< ComponentType >::blue(), castor::RgbColourT< ComponentType >::green(), castor::RgbColourT< ComponentType >::green(), castor::RgbColourT< ComponentType >::red(), and castor::RgbColourT< ComponentType >::red().
get() [2/2]
template<typename ComponentType > ComponentType const & castor::RgbColourT< ComponentType >::get (RgbComponent component) const inline
Retrieves the asked component value.
Parameters
[in] component The asked component
Returns
The component value
green() [1/2]
template<typename ComponentType > ComponentType & castor::RgbColourT< ComponentType >::green () inline
Retrieves the green component value.
Returns
The component value
References castor::eGreen, and castor::RgbColourT< ComponentType >::get().
Referenced by castor3d::ControlStyle::doCreateMaterial().
green() [2/2]
template<typename ComponentType > ComponentType const & castor::RgbColourT< ComponentType >::green () const inline
Retrieves the green component value.
Returns
The component value
References castor::eGreen, and castor::RgbColourT< ComponentType >::get().
operator*=() [1/2]
template<typename ComponentType > RgbColourT & castor::RgbColourT< ComponentType >::operator*= (ComponentType const & component)
Multiplication assignment operator.
Parameters
[in] component The value to multiply
Returns
Result of this * component
operator*=() [2/2]
template<typename ComponentType > template<typename T > RgbColourT & castor::RgbColourT< ComponentType >::operator*= (T scalar) inline
Multiplication assignment operator.
Parameters
[in] scalar The value to multiply
Returns
Result of this * scalar
References castor::eCount.
operator+=() [1/3]
template<typename ComponentType > RgbColourT & castor::RgbColourT< ComponentType >::operator+= (ComponentType const & component)
addition assignment operator
Parameters
[in] component The value to add
Returns
Result of this + component
operator+=() [2/3]
template<typename ComponentType > RgbColourT & castor::RgbColourT< ComponentType >::operator+= (RgbColourT< ComponentType > const & rhs)
addition assignment operator
Parameters
[in] rhs The colours to add
Returns
Result of this + rhs
operator+=() [3/3]
template<typename ComponentType > template<typename T > RgbColourT & castor::RgbColourT< ComponentType >::operator+= (T scalar) inline
addition assignment operator
Parameters
[in] scalar The value to add
Returns
Result of this + scalar
References castor::eCount.
operator-=() [1/3]
template<typename ComponentType > RgbColourT & castor::RgbColourT< ComponentType >::operator-= (ComponentType const & component)
Substraction assignment operator.
Parameters
[in] component The value to subtract
Returns
Result of this - component
operator-=() [2/3]
template<typename ComponentType > RgbColourT & castor::RgbColourT< ComponentType >::operator-= (RgbColourT< ComponentType > const & rhs)
Substraction assignment operator.
Parameters
[in] rhs The colours to subtract
Returns
Result of this - rhs
operator-=() [3/3]
template<typename ComponentType > template<typename T > RgbColourT & castor::RgbColourT< ComponentType >::operator-= (T scalar) inline
Substraction assignment operator.
Parameters
[in] scalar The value to subtract
Returns
Result of this - scalar
References castor::eCount.
operator/=() [1/2]
template<typename ComponentType > RgbColourT & castor::RgbColourT< ComponentType >::operator/= (ComponentType const & component)
Division assignment operator.
Parameters
[in] component The value to divide
Returns
Result of this / component
operator/=() [2/2]
template<typename ComponentType > template<typename T > RgbColourT & castor::RgbColourT< ComponentType >::operator/= (T scalar) inline
Division assignment operator.
Parameters
[in] scalar The value to divide
Returns
Result of this / scalar
References castor::eCount.
operator=() [1/2]
template<typename ComponentType > RgbColourT & castor::RgbColourT< ComponentType >::operator= (RgbColourT< ComponentType > && rhs) default noexcept
operator=() [2/2]
template<typename ComponentType > RgbColourT & castor::RgbColourT< ComponentType >::operator= (RgbColourT< ComponentType > const & rhs) default
operator[]() [1/4]
template<typename ComponentType > ComponentType & castor::RgbColourT< ComponentType >::operator[] (RgbComponent component) inline
Retrieves the asked component value.
Parameters
[in] component The asked component
Returns
The component value
operator[]() [2/4]
template<typename ComponentType > ComponentType const & castor::RgbColourT< ComponentType >::operator[] (RgbComponent component) const inline
Retrieves the asked component value.
Parameters
[in] component The asked component
Returns
The component value
operator[]() [3/4]
template<typename ComponentType > ComponentType & castor::RgbColourT< ComponentType >::operator[] (size_t component) inline
Retrieves the asked component value.
Parameters
[in] component The asked component
Returns
The component value
operator[]() [4/4]
template<typename ComponentType > ComponentType const & castor::RgbColourT< ComponentType >::operator[] (size_t component) const inline
Retrieves the asked component value.
Parameters
[in] component The asked component
Returns
The component value
ptr()
template<typename ComponentType > float * castor::RgbColourT< ComponentType >::ptr () inline
Retrieves a pointer to the colour values.
Returns
The pointer
Referenced by castor3d::getBuffer().
red() [1/2]
template<typename ComponentType > ComponentType & castor::RgbColourT< ComponentType >::red () inline
Retrieves the red component value.
Returns
The component value
References castor::eRed, and castor::RgbColourT< ComponentType >::get().
Referenced by castor3d::ControlStyle::doCreateMaterial().
red() [2/2]
template<typename ComponentType > ComponentType const & castor::RgbColourT< ComponentType >::red () const inline
Retrieves the red component value.
Returns
The component value
References castor::eRed, and castor::RgbColourT< ComponentType >::get().
Friends And Related Symbol Documentation
RgbColourT
template<typename ComponentType > template<typename ComponentU > friend class RgbColourT friend
The documentation for this class was generated from the following files:
CastorUtils/Graphics/GraphicsModule.hpp
CastorUtils/Graphics/RgbColour.hpp