Castor3D: castor3d::StylesHolder Class Reference
castor3d::StylesHolder Class Reference
#include <StylesHolder.hpp>
Public Member Functions
virtual C3D_API ~StylesHolder () noexcept=default
StylesHolder (castor::String name, Engine &engine)
castor::FontResPtr getDefaultFont () const
Retrieves the default font used by controls.
void setDefaultFont (castor::FontResPtr font)
sets the default font used by controls
C3D_API ButtonStyleRPtr createButtonStyle (castor::String name, Scene *scene)
C3D_API ComboBoxStyleRPtr createComboBoxStyle (castor::String name, Scene *scene)
C3D_API EditStyleRPtr createEditStyle (castor::String name, Scene *scene)
C3D_API ExpandablePanelStyleRPtr createExpandablePanelStyle (castor::String name, Scene *scene)
C3D_API FrameStyleRPtr createFrameStyle (castor::String name, Scene *scene)
C3D_API ListBoxStyleRPtr createListBoxStyle (castor::String name, Scene *scene)
C3D_API PanelStyleRPtr createPanelStyle (castor::String name, Scene *scene)
C3D_API ProgressStyleRPtr createProgressStyle (castor::String name, Scene *scene)
C3D_API ScrollBarStyleRPtr createScrollBarStyle (castor::String name, Scene *scene)
C3D_API SliderStyleRPtr createSliderStyle (castor::String name, Scene *scene)
C3D_API StaticStyleRPtr createStaticStyle (castor::String name, Scene *scene)
virtual C3D_API ButtonStyleRPtr getButtonStyle (castor::String const &name) const
virtual C3D_API ComboBoxStyleRPtr getComboBoxStyle (castor::String const &name) const
virtual C3D_API EditStyleRPtr getEditStyle (castor::String const &name) const
virtual C3D_API ExpandablePanelStyleRPtr getExpandablePanelStyle (castor::String const &name) const
virtual C3D_API FrameStyleRPtr getFrameStyle (castor::String const &name) const
virtual C3D_API ListBoxStyleRPtr getListBoxStyle (castor::String const &name) const
virtual C3D_API PanelStyleRPtr getPanelStyle (castor::String const &name) const
virtual C3D_API ProgressStyleRPtr getProgressStyle (castor::String const &name) const
virtual C3D_API ScrollBarStyleRPtr getScrollBarStyle (castor::String const &name) const
virtual C3D_API SliderStyleRPtr getSliderStyle (castor::String const &name) const
virtual C3D_API StaticStyleRPtr getStaticStyle (castor::String const &name) const
template<typename StyleT >
StyleT * getStyle (castor::String const &name) const
auto & getButtonStyles () const noexcept
auto & getComboBoxStyles () const noexcept
auto & getEditStyles () const noexcept
auto & getExpandablePanelStyles () const noexcept
auto & getFrameStyles () const noexcept
auto & getListBoxStyles () const noexcept
auto & getPanelStyles () const noexcept
auto & getProgressStyles () const noexcept
auto & getScrollBarStyles () const noexcept
auto & getSliderStyles () const noexcept
auto & getStaticStyles () const noexcept
bool isEmpty () const noexcept
Protected Member Functions
auto & getHolderName () const noexcept
void cleanupStyles () noexcept
Constructor & Destructor Documentation
~StylesHolder()
virtual C3D_API castor3d::StylesHolder::~StylesHolder () virtual default noexcept
StylesHolder()
castor3d::StylesHolder::StylesHolder (castor::String name, Engine & engine) inline explicit
Member Function Documentation
cleanupStyles()
void castor3d::StylesHolder::cleanupStyles () inline protected noexcept
createButtonStyle()
C3D_API ButtonStyleRPtr castor3d::StylesHolder::createButtonStyle (castor::String name, Scene * scene)
createComboBoxStyle()
C3D_API ComboBoxStyleRPtr castor3d::StylesHolder::createComboBoxStyle (castor::String name, Scene * scene)
createEditStyle()
C3D_API EditStyleRPtr castor3d::StylesHolder::createEditStyle (castor::String name, Scene * scene)
createExpandablePanelStyle()
C3D_API ExpandablePanelStyleRPtr castor3d::StylesHolder::createExpandablePanelStyle (castor::String name, Scene * scene)
createFrameStyle()
C3D_API FrameStyleRPtr castor3d::StylesHolder::createFrameStyle (castor::String name, Scene * scene)
createListBoxStyle()
C3D_API ListBoxStyleRPtr castor3d::StylesHolder::createListBoxStyle (castor::String name, Scene * scene)
createPanelStyle()
C3D_API PanelStyleRPtr castor3d::StylesHolder::createPanelStyle (castor::String name, Scene * scene)
createProgressStyle()
C3D_API ProgressStyleRPtr castor3d::StylesHolder::createProgressStyle (castor::String name, Scene * scene)
createScrollBarStyle()
C3D_API ScrollBarStyleRPtr castor3d::StylesHolder::createScrollBarStyle (castor::String name, Scene * scene)
createSliderStyle()
C3D_API SliderStyleRPtr castor3d::StylesHolder::createSliderStyle (castor::String name, Scene * scene)
createStaticStyle()
C3D_API StaticStyleRPtr castor3d::StylesHolder::createStaticStyle (castor::String name, Scene * scene)
getButtonStyle()
virtual C3D_API ButtonStyleRPtr castor3d::StylesHolder::getButtonStyle (castor::String const & name) const virtual
Reimplemented in castor3d::ControlsManager.
Referenced by getStyle().
getButtonStyles()
auto & castor3d::StylesHolder::getButtonStyles () const inline noexcept
getComboBoxStyle()
virtual C3D_API ComboBoxStyleRPtr castor3d::StylesHolder::getComboBoxStyle (castor::String const & name) const virtual
Reimplemented in castor3d::ControlsManager.
Referenced by getStyle().
getComboBoxStyles()
auto & castor3d::StylesHolder::getComboBoxStyles () const inline noexcept
getDefaultFont()
castor::FontResPtr castor3d::StylesHolder::getDefaultFont () const inline
Retrieves the default font used by controls.
Returns
The font
getEditStyle()
virtual C3D_API EditStyleRPtr castor3d::StylesHolder::getEditStyle (castor::String const & name) const virtual
Reimplemented in castor3d::ControlsManager.
Referenced by getStyle().
getEditStyles()
auto & castor3d::StylesHolder::getEditStyles () const inline noexcept
getExpandablePanelStyle()
virtual C3D_API ExpandablePanelStyleRPtr castor3d::StylesHolder::getExpandablePanelStyle (castor::String const & name) const virtual
Reimplemented in castor3d::ControlsManager.
Referenced by getStyle().
getExpandablePanelStyles()
auto & castor3d::StylesHolder::getExpandablePanelStyles () const inline noexcept
getFrameStyle()
virtual C3D_API FrameStyleRPtr castor3d::StylesHolder::getFrameStyle (castor::String const & name) const virtual
Reimplemented in castor3d::ControlsManager.
Referenced by getStyle().
getFrameStyles()
auto & castor3d::StylesHolder::getFrameStyles () const inline noexcept
getHolderName()
auto & castor3d::StylesHolder::getHolderName () const inline protected noexcept
Referenced by castor3d::Theme::getName().
getListBoxStyle()
virtual C3D_API ListBoxStyleRPtr castor3d::StylesHolder::getListBoxStyle (castor::String const & name) const virtual
Reimplemented in castor3d::ControlsManager.
Referenced by getStyle().
getListBoxStyles()
auto & castor3d::StylesHolder::getListBoxStyles () const inline noexcept
getPanelStyle()
virtual C3D_API PanelStyleRPtr castor3d::StylesHolder::getPanelStyle (castor::String const & name) const virtual
Reimplemented in castor3d::ControlsManager.
Referenced by getStyle().
getPanelStyles()
auto & castor3d::StylesHolder::getPanelStyles () const inline noexcept
getProgressStyle()
virtual C3D_API ProgressStyleRPtr castor3d::StylesHolder::getProgressStyle (castor::String const & name) const virtual
Reimplemented in castor3d::ControlsManager.
Referenced by getStyle().
getProgressStyles()
auto & castor3d::StylesHolder::getProgressStyles () const inline noexcept
getScrollBarStyle()
virtual C3D_API ScrollBarStyleRPtr castor3d::StylesHolder::getScrollBarStyle (castor::String const & name) const virtual
Reimplemented in castor3d::ControlsManager.
Referenced by getStyle().
getScrollBarStyles()
auto & castor3d::StylesHolder::getScrollBarStyles () const inline noexcept
getSliderStyle()
virtual C3D_API SliderStyleRPtr castor3d::StylesHolder::getSliderStyle (castor::String const & name) const virtual
Reimplemented in castor3d::ControlsManager.
Referenced by getStyle().
getSliderStyles()
auto & castor3d::StylesHolder::getSliderStyles () const inline noexcept
getStaticStyle()
virtual C3D_API StaticStyleRPtr castor3d::StylesHolder::getStaticStyle (castor::String const & name) const virtual
Reimplemented in castor3d::ControlsManager.
Referenced by getStyle().
getStaticStyles()
auto & castor3d::StylesHolder::getStaticStyles () const inline noexcept
getStyle()
template<typename StyleT > StyleT * castor3d::StylesHolder::getStyle (castor::String const & name) const inline
References cuT, castor3d::log::error, getButtonStyle(), getComboBoxStyle(), getEditStyle(), getExpandablePanelStyle(), getFrameStyle(), getListBoxStyle(), getPanelStyle(), getProgressStyle(), getScrollBarStyle(), getSliderStyle(), and getStaticStyle().
isEmpty()
bool castor3d::StylesHolder::isEmpty () const inline noexcept
setDefaultFont()
void castor3d::StylesHolder::setDefaultFont (castor::FontResPtr font) inline
sets the default font used by controls
Parameters
[in] font The font
The documentation for this class was generated from the following file:
Castor3D/Gui/Theme/StylesHolder.hpp