Castor3D: castor3d::SubsurfaceScatteringComponent Struct Reference
castor3d::SubsurfaceScatteringComponent Struct Reference
#include <SubsurfaceScatteringComponent.hpp>
Classes
struct ComponentsShader
struct MaterialShader
class Plugin
Public Member Functions
C3D_API SubsurfaceScatteringComponent (Pass &pass)
C3D_API void accept (PassVisitorBase &vis) override
PassVisitor acceptance function.
C3D_API void update () override
C3D_API PassComponentFlag getPassFlags () const override
C3D_API void setSubsurfaceScattering (SubsurfaceScatteringUPtr value)
C3D_API void fillProfileBuffer (SssProfileBuffer &buffer) const
Fills the pass buffer with this pass data.
bool hasSubsurfaceScattering () const
SubsurfaceScattering const & getSubsurfaceScattering () const
uint32_t getSssProfileId () const
void setSssProfileId (uint32_t value)
Public Member Functions inherited from castor3d::BaseDataPassComponentT< castor::AtomicGroupChangeTracked< SubsurfaceScatteringUPtr > >
BaseDataPassComponentT (Pass &pass, castor::String type, castor::StringArray deps={}, ParamsT &&... params)
Constructor.
void setData (DataU const &data)
void setData (ParamsT &&... params)
castor::AtomicGroupChangeTracked< SubsurfaceScatteringUPtr > & getData ()
castor::AtomicGroupChangeTracked< SubsurfaceScatteringUPtr > const & getData () const
Public Member Functions inherited from castor3d::PassComponent
C3D_API PassComponent (Pass &pass, castor::String type, castor::StringArray deps={})
Constructor.
virtual C3D_API ~PassComponent () noexcept=default
C3D_API PassComponentUPtr clone (Pass &pass) const
C3D_API bool writeText (castor::String const &tabs, castor::Path const &folder, castor::String const &subfolder, castor::StringStream &file) const
Writes the component content to text.
C3D_API void fillBuffer (PassBuffer &buffer) const
Fills the pass buffer with this pass data.
C3D_API void fillChannel (TextureConfiguration &configuration, uint32_t mask)
Fills the texture configuration for use with this component.
virtual C3D_API void fillConfig (TextureConfiguration &config, PassVisitorBase &vis) const
PassVisitor acceptance function, for a specific texture configuration.
virtual C3D_API bool hasColour () const
virtual C3D_API castor::HdrRgbColour const & getColour () const
virtual C3D_API void setColour (castor::HdrRgbColour v)
virtual C3D_API bool areNormalsInverted () const
castor::String const & getType () const
castor::StringArray const & getDependencies () const
PassComponentPlugin const & getPlugin () const
PassComponentID getId () const
void setColour (castor::RgbColour const &v, float gamma=2.2f)
void setColour (castor::Coords3f const &v)
void setColour (castor::Point3f const &v)
Static Public Member Functions
static PassComponentPluginUPtr createPlugin (PassComponentRegister const &passComponent)
Public Attributes
OnSssProfileChanged onProfileChanged
Static Public Attributes
static constexpr PassFlag eSubsurfaceScattering = PassFlag(0x01u)
static constexpr PassFlag eDistanceBasedTransmittance = PassFlag(0x02u)
static constexpr PassFlag eAll = PassFlag(0x03u)
static C3D_API castor::String const TypeName
Additional Inherited Members
Protected Attributes inherited from castor3d::BaseDataPassComponentT< castor::AtomicGroupChangeTracked< SubsurfaceScatteringUPtr > >
castor::AtomicGroupChangeTracked< SubsurfaceScatteringUPtr > m_value
Protected Attributes inherited from castor3d::PassComponent
castor::String m_type
castor::StringArray m_dependencies
PassComponentID m_id
PassComponentPlugin const & m_plugin
std::atomic_bool & m_dirty
shader::PassMaterialShader * m_materialShader {}
Constructor & Destructor Documentation
SubsurfaceScatteringComponent()
C3D_API castor3d::SubsurfaceScatteringComponent::SubsurfaceScatteringComponent (Pass & pass) explicit
Member Function Documentation
accept()
C3D_API void castor3d::SubsurfaceScatteringComponent::accept (PassVisitorBase & vis) override virtual
PassVisitor acceptance function.
Parameters
vis The ... visitor.
Reimplemented from castor3d::PassComponent.
createPlugin()
static PassComponentPluginUPtr castor3d::SubsurfaceScatteringComponent::createPlugin (PassComponentRegister const & passComponent) inline static
fillProfileBuffer()
C3D_API void castor3d::SubsurfaceScatteringComponent::fillProfileBuffer (SssProfileBuffer & buffer) const
Fills the pass buffer with this pass data.
Parameters
[in,out] buffer The pass buffer.
getPassFlags()
C3D_API PassComponentFlag castor3d::SubsurfaceScatteringComponent::getPassFlags () const inline override virtual
Reimplemented from castor3d::PassComponent.
References castor3d::eNone, eSubsurfaceScattering, castor3d::PassComponent::getId(), hasSubsurfaceScattering(), and castor3d::makePassComponentFlag().
getSssProfileId()
uint32_t castor3d::SubsurfaceScatteringComponent::getSssProfileId () const inline
getSubsurfaceScattering()
SubsurfaceScattering const & castor3d::SubsurfaceScatteringComponent::getSubsurfaceScattering () const inline
References hasSubsurfaceScattering(), and castor3d::BaseDataPassComponentT< castor::AtomicGroupChangeTracked< SubsurfaceScatteringUPtr > >::m_value.
hasSubsurfaceScattering()
bool castor3d::SubsurfaceScatteringComponent::hasSubsurfaceScattering () const inline
References castor3d::BaseDataPassComponentT< castor::AtomicGroupChangeTracked< SubsurfaceScatteringUPtr > >::m_value.
Referenced by getPassFlags(), and getSubsurfaceScattering().
setSssProfileId()
void castor3d::SubsurfaceScatteringComponent::setSssProfileId (uint32_t value) inline
setSubsurfaceScattering()
C3D_API void castor3d::SubsurfaceScatteringComponent::setSubsurfaceScattering (SubsurfaceScatteringUPtr value)
update()
C3D_API void castor3d::SubsurfaceScatteringComponent::update () override virtual
Reimplemented from castor3d::PassComponent.
Member Data Documentation
eAll
constexpr PassFlag castor3d::SubsurfaceScatteringComponent::eAll = PassFlag(0x03u) static constexpr
Referenced by castor3d::SubsurfaceScatteringComponent::Plugin::getComponentFlags().
eDistanceBasedTransmittance
constexpr PassFlag castor3d::SubsurfaceScatteringComponent::eDistanceBasedTransmittance = PassFlag(0x02u) static constexpr
eSubsurfaceScattering
constexpr PassFlag castor3d::SubsurfaceScatteringComponent::eSubsurfaceScattering = PassFlag(0x01u) static constexpr
Referenced by getPassFlags().
onProfileChanged
OnSssProfileChanged castor3d::SubsurfaceScatteringComponent::onProfileChanged
TypeName
C3D_API castor::String const castor3d::SubsurfaceScatteringComponent::TypeName static
The documentation for this struct was generated from the following file:
Material/Pass/Component/Lighting/SubsurfaceScatteringComponent.hpp