Castor3D: castor3d::UniformBufferOffsetT< DataT > Struct Template Reference
castor3d::UniformBufferOffsetT< DataT > Struct Template Reference
A UniformBuffer and an offset from the GpuBuffer.
#include <UniformBufferOffset.hpp>
Public Member Functions
void setPool (PoolUniformBuffer &pool)
operator bool () const
VkDeviceSize getByteOffset () const
VkDeviceSize getByteRange () const
DataT const & getData () const
DataT & getData ()
PoolUniformBuffer const & getPool () const
PoolUniformBuffer & getPool ()
ashes::UniformBuffer const & getBuffer () const
ashes::UniformBuffer & getBuffer ()
uint32_t getAlignedSize () const
void createPassBinding (crg::FramePass &pass, castor::MbString const &name, uint32_t binding) const
void createSizedBinding (ashes::DescriptorSet &descriptorSet, VkDescriptorSetLayoutBinding const &layoutBinding) const
ashes::WriteDescriptorSet getDescriptorWrite (uint32_t dstBinding, uint32_t dstArrayElement=0u) const
Public Attributes
VkMemoryPropertyFlags flags { 0u }
uint32_t offset { 0u }
uint32_t range { 0u }
Detailed Description
template<typename DataT>
struct castor3d::UniformBufferOffsetT< DataT >
A UniformBuffer and an offset from the GpuBuffer.
Member Function Documentation
createPassBinding()
template<typename DataT > void castor3d::UniformBufferOffsetT< DataT >::createPassBinding (crg::FramePass & pass, castor::MbString const & name, uint32_t binding) const inline
References castor3d::UniformBufferOffsetT< DataT >::getBuffer(), castor3d::UniformBufferOffsetT< DataT >::getByteOffset(), and castor3d::UniformBufferOffsetT< DataT >::getByteRange().
Referenced by castor3d::CameraUbo::createPassBinding(), castor3d::ClustersUbo::createPassBinding(), castor3d::ColourGradingUbo::createPassBinding(), castor3d::LpvGridConfigUbo::createPassBinding(), castor3d::LpvLightConfigUbo::createPassBinding(), castor3d::SceneUbo::createPassBinding(), castor3d::SsaoConfigUbo::createPassBinding(), castor3d::VoxelizerUbo::createPassBinding(), and castor3d::LayeredLpvGridConfigUbo::createPassBinding().
createSizedBinding()
template<typename DataT > void castor3d::UniformBufferOffsetT< DataT >::createSizedBinding (ashes::DescriptorSet & descriptorSet, VkDescriptorSetLayoutBinding const & layoutBinding) const inline
References castor3d::PoolUniformBuffer::getBuffer(), castor3d::UniformBufferOffsetT< DataT >::offset, and castor3d::UniformBufferOffsetT< DataT >::range.
Referenced by castor3d::CameraUbo::createSizedBinding(), castor3d::ClustersUbo::createSizedBinding(), castor3d::ColourGradingUbo::createSizedBinding(), castor3d::LayeredLpvGridConfigUbo::createSizedBinding(), castor3d::LpvGridConfigUbo::createSizedBinding(), castor3d::LpvLightConfigUbo::createSizedBinding(), castor3d::SceneUbo::createSizedBinding(), castor3d::ShadowMapUbo::createSizedBinding(), castor3d::SsaoConfigUbo::createSizedBinding(), and castor3d::VoxelizerUbo::createSizedBinding().
getAlignedSize()
template<typename DataT > uint32_t castor3d::UniformBufferOffsetT< DataT >::getAlignedSize () const inline
References castor3d::PoolUniformBuffer::getAlignedSize().
getBuffer() [1/2]
template<typename DataT > ashes::UniformBuffer & castor3d::UniformBufferOffsetT< DataT >::getBuffer () inline
References castor3d::PoolUniformBuffer::getBuffer().
getBuffer() [2/2]
template<typename DataT > ashes::UniformBuffer const & castor3d::UniformBufferOffsetT< DataT >::getBuffer () const inline
References castor3d::PoolUniformBuffer::getBuffer().
Referenced by castor3d::UniformBufferOffsetT< DataT >::createPassBinding().
getByteOffset()
template<typename DataT > VkDeviceSize castor3d::UniformBufferOffsetT< DataT >::getByteOffset () const inline
References castor3d::PoolUniformBuffer::getBuffer(), and castor3d::UniformBufferOffsetT< DataT >::offset.
Referenced by castor3d::UniformBufferOffsetT< DataT >::createPassBinding().
getByteRange()
template<typename DataT > VkDeviceSize castor3d::UniformBufferOffsetT< DataT >::getByteRange () const inline
References castor3d::PoolUniformBuffer::getBuffer(), and castor3d::UniformBufferOffsetT< DataT >::range.
Referenced by castor3d::UniformBufferOffsetT< DataT >::createPassBinding().
getData() [1/2]
template<typename DataT > DataT & castor3d::UniformBufferOffsetT< DataT >::getData () inline
References castor3d::PoolUniformBuffer::getAlignedSize(), castor3d::PoolUniformBuffer::getData(), and castor3d::UniformBufferOffsetT< DataT >::offset.
getData() [2/2]
template<typename DataT > DataT const & castor3d::UniformBufferOffsetT< DataT >::getData () const inline
References castor3d::PoolUniformBuffer::getAlignedSize(), castor3d::PoolUniformBuffer::getData(), and castor3d::UniformBufferOffsetT< DataT >::offset.
getDescriptorWrite()
template<typename DataT > ashes::WriteDescriptorSet castor3d::UniformBufferOffsetT< DataT >::getDescriptorWrite (uint32_t dstBinding, uint32_t dstArrayElement = 0u) const inline
References castor3d::PoolUniformBuffer::getBuffer(), castor3d::UniformBufferOffsetT< DataT >::offset, and castor3d::UniformBufferOffsetT< DataT >::range.
Referenced by castor3d::CameraUbo::getDescriptorWrite(), castor3d::ClustersUbo::getDescriptorWrite(), castor3d::LayeredLpvGridConfigUbo::getDescriptorWrite(), castor3d::LpvGridConfigUbo::getDescriptorWrite(), castor3d::SceneUbo::getDescriptorWrite(), castor3d::ShadowMapUbo::getDescriptorWrite(), and castor3d::VoxelizerUbo::getDescriptorWrite().
getPool() [1/2]
template<typename DataT > PoolUniformBuffer & castor3d::UniformBufferOffsetT< DataT >::getPool () inline
getPool() [2/2]
template<typename DataT > PoolUniformBuffer const & castor3d::UniformBufferOffsetT< DataT >::getPool () const inline
operator bool()
template<typename DataT > castor3d::UniformBufferOffsetT< DataT >::operator bool () const inline explicit
References castor3d::PoolUniformBuffer::hasBuffer().
setPool()
template<typename DataT > void castor3d::UniformBufferOffsetT< DataT >::setPool (PoolUniformBuffer & pool) inline
Member Data Documentation
flags
template<typename DataT > VkMemoryPropertyFlags castor3d::UniformBufferOffsetT< DataT >::flags { 0u }
offset
template<typename DataT > uint32_t castor3d::UniformBufferOffsetT< DataT >::offset { 0u }
Referenced by castor3d::UniformBufferOffsetT< DataT >::createSizedBinding(), castor3d::UniformBufferOffsetT< DataT >::getByteOffset(), castor3d::UniformBufferOffsetT< DataT >::getData(), castor3d::UniformBufferOffsetT< DataT >::getData(), and castor3d::UniformBufferOffsetT< DataT >::getDescriptorWrite().
range
template<typename DataT > uint32_t castor3d::UniformBufferOffsetT< DataT >::range { 0u }
Referenced by castor3d::UniformBufferOffsetT< DataT >::createSizedBinding(), castor3d::UniformBufferOffsetT< DataT >::getByteRange(), and castor3d::UniformBufferOffsetT< DataT >::getDescriptorWrite().
The documentation for this struct was generated from the following files:
Castor3D/Buffer/BufferModule.hpp
Castor3D/Buffer/UniformBufferOffset.hpp