Castor3D: castor3d::Camera Class Reference
castor3d::Camera Class Reference
Public Member Functions
C3D_API Camera (castor::String const &name, Scene &scene, SceneNode &node, Viewport viewport, bool ownProjMtx=false)
Constructor.
C3D_API Camera (castor::String const &name, Scene &scene, SceneNode &node, bool ownProjMtx=false)
Constructor, needs the camera renderer, the name, window size and projection type. Creates a viewport renderer and a viewport.
C3D_API ~Camera ()
Destructor.
C3D_API void attachTo (SceneNode &node) override
Attaches this light to a Material.
C3D_API void updateFrustum ()
Updates the frustum.
C3D_API void update ()
Updates the viewport, the view matrix, and the frustum.
C3D_API void setProjection (castor::Matrix4x4f const &projection)
Sets the projection matrix, updates the viewport and the frustum.
C3D_API bool isVisible (Geometry const &geometry, Submesh const &submesh) const
Checks if a submesh is visible, through a geometry.
Viewport const & getViewport () const
Viewport & getViewport ()
castor::Matrix4x4f const & getView () const
castor::Matrix4x4f const & getProjection () const
ViewportType getViewportType () const
castor::Size const & getSize () const
uint32_t getWidth () const
uint32_t getHeight () const
float getNear () const
float getFar () const
float getRatio () const
castor::Angle const & getFovY () const
float getProjectionScale () const
bool isVisible (castor::BoundingBox const &box, castor::Matrix4x4f const &transformations) const
bool isVisible (castor::BoundingSphere const &sphere, castor::Matrix4x4f const &transformations, castor::Point3f const &scale) const
bool isVisible (castor::Point3f const &point) const
Frustum const & getFrustum () const
HdrConfig const & getHdrConfig () const
HdrConfig & getHdrConfig ()
void setView (castor::Matrix4x4f const &view)
void resize (uint32_t width, uint32_t height)
void resize (castor::Size const &size)
void setViewportType (ViewportType value)
void setExposure (float value)
void setGamma (float value)
Public Member Functions inherited from castor3d::MovableObject
C3D_API MovableObject (castor::String const &name, Scene &scene, MovableType type, SceneNode &node)
Constructor.
C3D_API MovableObject (castor::String const &name, Scene &scene, MovableType type)
Constructor.
virtual C3D_API ~MovableObject ()
Destructor.
C3D_API void detach ()
Detaches the movable object from it's parent.
SceneNode * getParent () const
Retrieves the parent node.
MovableType getType () const
Retrieves the object type.
Scene * getScene () const
Public Member Functions inherited from castor3d::AnimableT< AnimableHanlerT >
void cleanupAnimations ()
Empties the animations map.
bool hasAnimation (castor::String const &name) const
Retrieves an animation.
Animation const & getAnimation (castor::String const &name) const
Retrieves an animation.
Animation & getAnimation (castor::String const &name)
Retrieves an animation.
void addAnimation (AnimationPtr animation)
Adds an animation.
AnimationPtrStrMap const & getAnimations () const
Public Attributes
OnCameraChanged onChanged
Friends
class Scene
Additional Inherited Members
Protected Types inherited from castor3d::AnimableT< AnimableHanlerT >
using Animation = AnimationT< AnimableHanlerT >
using AnimationPtr = std::unique_ptr< Animation >
using AnimationPtrStrMap = std::map< castor::String, AnimationPtr >
Protected Member Functions inherited from castor3d::AnimableT< AnimableHanlerT >
void doRemoveAnimation (castor::String const &name)
Removes an animation.
template<typename AnimationType >
AnimationType & doGetAnimation (castor::String const &name)
Retrieves an animation.
AnimableT (AnimableHanlerT &owner)
virtual C3D_API ~AnimableT ()=default
C3D_API AnimableT (AnimableT &&rhs)=default
C3D_API AnimableT & operator= (AnimableT &&rhs)=delete
C3D_API AnimableT (AnimableT const &rhs)=delete
C3D_API AnimableT & operator= (AnimableT const &rhs)=delete
Protected Attributes inherited from castor3d::MovableObject
Scene * m_scene
MovableType m_type
castor::String m_strNodeName
SceneNode * m_sceneNode
OnSceneNodeChangedConnection m_notifyIndex
Protected Attributes inherited from castor3d::AnimableT< AnimableHanlerT >
AnimationPtrStrMap m_animations
Constructor & Destructor Documentation
Camera() [1/2]
C3D_API castor3d::Camera::Camera (castor::String const & name, Scene & scene, SceneNode & node, Viewport viewport, bool ownProjMtx = false)
Constructor.
Parameters
[in] name The camera name.
[in] scene The parent scene.
[in] node The parent scene node.
[in] viewport Viewport to copy.
[in] ownProjMtx Tells if the projection matrix is held by the viewport false, or not true.
Camera() [2/2]
C3D_API castor3d::Camera::Camera (castor::String const & name, Scene & scene, SceneNode & node, bool ownProjMtx = false)
Constructor, needs the camera renderer, the name, window size and projection type. Creates a viewport renderer and a viewport.
Parameters
[in] name The camera name.
[in] scene The parent scene.
[in] node The parent scene node.
[in] ownProjMtx Tells if the projection matrix is held by the viewport false, or not true.
~Camera()
C3D_API castor3d::Camera::~Camera ()
Destructor.
Member Function Documentation
attachTo()
C3D_API void castor3d::Camera::attachTo (SceneNode & node) override virtual
Attaches this light to a Material.
Parameters
[in] node The new light's parent node
Reimplemented from castor3d::MovableObject.
getFar()
float castor3d::Camera::getFar () const inline
References castor3d::Viewport::getFar().
getFovY()
castor::Angle const& castor3d::Camera::getFovY () const inline
References castor3d::Viewport::getFovY().
getFrustum()
Frustum const& castor3d::Camera::getFrustum () const inline
getHdrConfig() [1/2]
HdrConfig const& castor3d::Camera::getHdrConfig () const inline
getHdrConfig() [2/2]
HdrConfig& castor3d::Camera::getHdrConfig () inline
getHeight()
uint32_t castor3d::Camera::getHeight () const inline
References castor3d::Viewport::getHeight().
getNear()
float castor3d::Camera::getNear () const inline
References castor3d::Viewport::getNear().
getProjection()
castor::Matrix4x4f const& castor3d::Camera::getProjection () const inline
References castor3d::Viewport::getProjection().
getProjectionScale()
float castor3d::Camera::getProjectionScale () const inline
References castor3d::Viewport::getProjectionScale().
getRatio()
float castor3d::Camera::getRatio () const inline
References castor3d::Viewport::getRatio().
getSize()
castor::Size const& castor3d::Camera::getSize () const inline
References castor3d::Viewport::getSize().
getView()
castor::Matrix4x4f const& castor3d::Camera::getView () const inline
getViewport() [1/2]
Viewport const& castor3d::Camera::getViewport () const inline
name Getters.
getViewport() [2/2]
Viewport& castor3d::Camera::getViewport () inline
getViewportType()
ViewportType castor3d::Camera::getViewportType () const inline
References castor3d::Viewport::getType().
getWidth()
uint32_t castor3d::Camera::getWidth () const inline
References castor3d::Viewport::getWidth().
isVisible() [1/4]
C3D_API bool castor3d::Camera::isVisible (Geometry const & geometry, Submesh const & submesh) const
Checks if a submesh is visible, through a geometry.
Parameters
[in] geometry The geometry.
[in] submesh The submesh.
Returns
false if the submesh is not visible.
isVisible() [2/4]
bool castor3d::Camera::isVisible (castor::BoundingBox const & box, castor::Matrix4x4f const & transformations) const inline
References castor3d::Frustum::isVisible().
isVisible() [3/4]
bool castor3d::Camera::isVisible (castor::BoundingSphere const & sphere, castor::Matrix4x4f const & transformations, castor::Point3f const & scale) const inline
References castor3d::Frustum::isVisible().
isVisible() [4/4]
bool castor3d::Camera::isVisible (castor::Point3f const & point) const inline
References castor3d::Frustum::isVisible().
resize() [1/2]
void castor3d::Camera::resize (uint32_t width, uint32_t height) inline
resize() [2/2]
void castor3d::Camera::resize (castor::Size const & size) inline
References castor3d::Viewport::getSize(), onChanged, and castor3d::Viewport::resize().
setExposure()
void castor3d::Camera::setExposure (float value) inline
References castor3d::HdrConfig::exposure, and onChanged.
setGamma()
void castor3d::Camera::setGamma (float value) inline
References castor3d::HdrConfig::gamma, and onChanged.
setProjection()
C3D_API void castor3d::Camera::setProjection (castor::Matrix4x4f const & projection)
Sets the projection matrix, updates the viewport and the frustum.
Parameters
[in] projection The projection matrix.
setView()
void castor3d::Camera::setView (castor::Matrix4x4f const & view) inline
name Mutators.
References onChanged.
setViewportType()
void castor3d::Camera::setViewportType (ViewportType value) inline
References onChanged, and castor3d::Viewport::updateType().
update()
C3D_API void castor3d::Camera::update ()
Updates the viewport, the view matrix, and the frustum.
updateFrustum()
C3D_API void castor3d::Camera::updateFrustum ()
Updates the frustum.
Friends And Related Function Documentation
Scene
friend class Scene friend
Member Data Documentation
onChanged
OnCameraChanged castor3d::Camera::onChanged mutable
The signal raised when the camera has changed.
Referenced by resize(), setExposure(), setGamma(), setView(), and setViewportType().
The documentation for this class was generated from the following file:
Scene/Camera.hpp