Castor3D: castor3d::Vertex Class Reference
castor3d::Vertex Class Reference
Representation of a vertex.
Public Member Functions
C3D_API Vertex (BufferElementGroup &p_group)
Constructor.
C3D_API Vertex (Vertex const &p_source)
Copy constructor.
C3D_API Vertex & operator= (Vertex const &p_source)
Copy assignment operator.
virtual C3D_API ~Vertex ()
Destructor.
void setPosition (castor::Coords3r const &val)
sets the vertex position
void setPosition (castor::Point3r const &val)
sets the vertex position
void setPosition (real x, real y, real z)
sets the vertex position
void setPosition (real const *p_coords)
sets the vertex position
void setNormal (castor::Coords3r const &val)
sets the vertex normal
void setNormal (castor::Point3r const &val)
sets the vertex normal
void setNormal (real x, real y, real z)
sets the vertex normal
void setNormal (real const *p_coords)
sets the vertex normal
void setTangent (castor::Coords3r const &val)
sets the vertex tangent
void setTangent (castor::Point3r const &val)
sets the vertex tangent
void setTangent (real x, real y, real z)
sets the vertex tangent
void setTangent (real const *p_coords)
sets the vertex tangent
void setBitangent (castor::Coords3r const &val)
sets the vertex bitangent
void setBitangent (castor::Point3r const &val)
sets the vertex bitangent
void setBitangent (real x, real y, real z)
sets the vertex bitangent
void setBitangent (real const *p_coords)
sets the vertex bitangent
void setTexCoord (castor::Coords3r const &val)
sets the vertex texture coordinates
void setTexCoord (castor::Point3r const &val)
sets the vertex texture coordinates
void setTexCoord (real x, real y, real z=0)
sets the vertex texture coordinates
void setTexCoord (real const *p_coords)
sets the vertex texture coordinates
castor::Coords3r & getPosition (castor::Coords3r &p_ptPos)
Retrieves the vertex position.
castor::Point3r & getPosition (castor::Point3r &p_ptPos) const
Retrieves the vertex position.
castor::Coords3r & getNormal (castor::Coords3r &p_ptNml)
Retrieves the vertex normal.
castor::Point3r & getNormal (castor::Point3r &p_ptNml) const
Retrieves the vertex normal.
castor::Coords3r & getTangent (castor::Coords3r &p_ptTan)
Retrieves the vertex tangent.
castor::Point3r & getTangent (castor::Point3r &p_ptTan) const
Retrieves the vertex tangent.
castor::Coords3r & getBitangent (castor::Coords3r &p_ptBitan)
Retrieves the vertex bitangent.
castor::Point3r & getBitangent (castor::Point3r &p_ptBitan) const
Retrieves the vertex bitangent.
castor::Coords3r & getTexCoord (castor::Coords3r &p_ptTex)
Retrieves the vertex texture coordinates.
castor::Point3r & getTexCoord (castor::Point3r &p_ptTex) const
Retrieves the vertex texture coordinates.
Static Public Member Functions
static const uint32_t getCountPos ()
Retrieves position elements count.
static const uint32_t getCountNml ()
Retrieves normal elements count.
static const uint32_t getCountTan ()
Retrieves tangent elements count.
static const uint32_t getCountBin ()
Retrieves bitangent elements count.
static const uint32_t getCountTex ()
Retrieves texture coordinates elements count.
static const uint32_t getOffsetPos ()
Retrieves position's buffer offset.
static const uint32_t getOffsetNml ()
Retrieves normal's buffer offset.
static const uint32_t getOffsetTan ()
Retrieves tangent's buffer offset.
static const uint32_t getOffsetBin ()
Retrieves bitangent's buffer offset.
static const uint32_t getOffsetTex ()
Retrieves texture coordinates' buffer offset.
static const uint32_t getSizePos ()
Retrieves position binary size.
static const uint32_t getSizeNml ()
Retrieves normal binary size.
static const uint32_t getSizeTan ()
Retrieves tangent binary size.
static const uint32_t getSizeBin ()
Retrieves bitangent binary size.
static const uint32_t getSizeTex ()
Retrieves texture coordinates binary size.
static C3D_API castor::Coords3r getPosition (void *p_buffer)
Retrieves a vertex position from a buffer.
static C3D_API castor::Point3r getPosition (void const *p_buffer)
Retrieves a vertex position from a buffer.
static castor::Coords3r & getPosition (void *p_buffer, castor::Coords3r &p_coord)
Retrieves a vertex position from a buffer.
static castor::Point3r & getPosition (void const *p_buffer, castor::Point3r &p_coord)
Retrieves a vertex position from a buffer.
static void getPosition (void const *p_buffer, std::array< real, 3 > &p_coord)
Retrieves a vertex position from a buffer.
static C3D_API castor::Coords3r getNormal (void *p_buffer)
Retrieves a vertex normal from a buffer.
static C3D_API castor::Point3r getNormal (void const *p_buffer)
Retrieves a vertex normal from a buffer.
static castor::Coords3r & getNormal (void *p_buffer, castor::Coords3r &p_coord)
Retrieves a vertex normal from a buffer.
static castor::Point3r & getNormal (void const *p_buffer, castor::Point3r &p_coord)
Retrieves a vertex normal from a buffer.
static void getNormal (void const *p_buffer, std::array< real, 3 > &p_coord)
Retrieves a vertex normal from a buffer.
static C3D_API castor::Coords3r getTangent (void *p_buffer)
Retrieves a vertex tangent from a buffer.
static C3D_API castor::Point3r getTangent (void const *p_buffer)
Retrieves a vertex tangent from a buffer.
static castor::Coords3r & getTangent (void *p_buffer, castor::Coords3r &p_coord)
Retrieves a vertex tangent from a buffer.
static void getTangent (void const *p_buffer, std::array< real, 3 > &p_coord)
Retrieves a vertex tangent from a buffer.
static castor::Point3r & getTangent (void const *p_buffer, castor::Point3r &p_coord)
Retrieves a vertex tangent from a buffer.
static C3D_API castor::Coords3r getBitangent (void *p_buffer)
Retrieves a vertex bitangent from a buffer.
static C3D_API castor::Point3r getBitangent (void const *p_buffer)
Retrieves a vertex bitangent from a buffer.
static castor::Coords3r & getBitangent (void *p_buffer, castor::Coords3r &p_coord)
Retrieves a vertex bitangent from a buffer.
static castor::Point3r & getBitangent (void const *p_buffer, castor::Point3r &p_coord)
Retrieves a vertex bitangent from a buffer.
static void getBitangent (void const *p_buffer, std::array< real, 3 > &p_coord)
Retrieves a vertex bitangent from a buffer.
static C3D_API castor::Coords3r getTexCoord (void *p_buffer)
Retrieves a vertex texture coordinates from a buffer.
static C3D_API castor::Point3r getTexCoord (void const *p_buffer)
Retrieves a vertex texture coordinates from a buffer.
static castor::Coords3r & getTexCoord (void *p_buffer, castor::Coords3r &p_coord)
Retrieves a vertex texture coordinates from a buffer.
static castor::Point3r & getTexCoord (void const *p_buffer, castor::Point3r &p_coord)
Retrieves a vertex texture coordinates from a buffer.
static void getTexCoord (void const *p_buffer, std::array< real, 3 > &p_coord)
Retrieves a vertex texture coordinates from a buffer.
static void setPosition (void *p_buffer, castor::Coords3r const &p_coord)
sets the vertex position in a buffer
static void setPosition (void *p_buffer, castor::Point3r const &p_coord)
sets the vertex position in a buffer
static C3D_API void setPosition (void *p_buffer, real const *p_coord)
sets the vertex position in a buffer
static C3D_API void setPosition (void *p_buffer, real x, real y, real z)
sets the vertex position in a buffer
static void setNormal (void *p_buffer, castor::Coords3r const &p_coord)
sets the vertex normal in a buffer
static void setNormal (void *p_buffer, castor::Point3r const &p_coord)
sets the vertex normal in a buffer
static C3D_API void setNormal (void *p_buffer, real const *p_coord)
sets the vertex normal in a buffer
static C3D_API void setNormal (void *p_buffer, real x, real y, real z)
sets the vertex normal in a buffer
static void setTangent (void *p_buffer, castor::Coords3r const &p_coord)
sets the vertex tangent in a buffer
static void setTangent (void *p_buffer, castor::Point3r const &p_coord)
sets the vertex tangent in a buffer
static C3D_API void setTangent (void *p_buffer, real const *p_coord)
sets the vertex tangent in a buffer
static C3D_API void setTangent (void *p_buffer, real x, real y, real z)
sets the vertex tangent in a buffer
static void setBitangent (void *p_buffer, castor::Coords3r const &p_coord)
sets the vertex bitangent in a buffer
static void setBitangent (void *p_buffer, castor::Point3r const &p_coord)
sets the vertex bitangent in a buffer
static C3D_API void setBitangent (void *p_buffer, real const *p_coord)
sets the vertex bitangent in a buffer
static C3D_API void setBitangent (void *p_buffer, real x, real y, real z)
sets the vertex bitangent in a buffer
static void setTexCoord (void *p_buffer, castor::Coords3r const &p_coord)
sets the vertex texture coordinates in a buffer
static void setTexCoord (void *p_buffer, castor::Point3r const &p_coord)
sets the vertex texture coordinates in a buffer
static C3D_API void setTexCoord (void *p_buffer, real const *p_coord)
sets the vertex texture coordinates in a buffer
static C3D_API void setTexCoord (void *p_buffer, real x, real y, real z=0)
sets the vertex texture coordinates in a buffer
static castor::Coords3r & getPosition (BufferElementGroupSPtr p_pElement, castor::Coords3r &p_coord)
Retrieves the group position.
static castor::Point3r & getPosition (BufferElementGroupSPtr p_pElement, castor::Point3r &p_point)
Retrieves the group position.
static castor::Coords3r & getNormal (BufferElementGroupSPtr p_pElement, castor::Coords3r &p_coord)
Retrieves the group normal.
static castor::Point3r & getNormal (BufferElementGroupSPtr p_pElement, castor::Point3r &p_point)
Retrieves the group normal.
static castor::Coords3r & getTangent (BufferElementGroupSPtr p_pElement, castor::Coords3r &p_coord)
Retrieves the group tangent.
static castor::Point3r & getTangent (BufferElementGroupSPtr p_pElement, castor::Point3r &p_point)
Retrieves the group tangent.
static castor::Coords3r & getBitangent (BufferElementGroupSPtr p_pElement, castor::Coords3r &p_coord)
Retrieves the group bitangent.
static castor::Point3r & getBitangent (BufferElementGroupSPtr p_pElement, castor::Point3r &p_point)
Retrieves the group bitangent.
static castor::Coords3r & getTexCoord (BufferElementGroupSPtr p_pElement, castor::Coords3r &p_coord)
Retrieves the group texture coordinates.
static castor::Point3r & getTexCoord (BufferElementGroupSPtr p_pElement, castor::Point3r &p_point)
Retrieves the group texture coordinates.
static void setPosition (BufferElementGroupSPtr p_pElement, castor::Coords3r const &p_coord)
sets the group position
static void setPosition (BufferElementGroupSPtr p_pElement, castor::Point3r const &p_coord)
sets the group position
static void setPosition (BufferElementGroupSPtr p_pElement, real const *p_coord)
sets the group position
static void setPosition (BufferElementGroupSPtr p_pElement, real x, real y, real z)
sets the group position
static void setNormal (BufferElementGroupSPtr p_pElement, castor::Coords3r const &p_coord)
sets the group normal
static void setNormal (BufferElementGroupSPtr p_pElement, castor::Point3r const &p_coord)
sets the group normal
static void setNormal (BufferElementGroupSPtr p_pElement, real const *p_coord)
sets the group normal
static void setNormal (BufferElementGroupSPtr p_pElement, real x, real y, real z)
sets the group normal
static void setTangent (BufferElementGroupSPtr p_pElement, castor::Coords3r const &p_coord)
sets the group tangent
static void setTangent (BufferElementGroupSPtr p_pElement, castor::Point3r const &p_coord)
sets the group tangent
static void setTangent (BufferElementGroupSPtr p_pElement, real const *p_coord)
sets the group tangent
static void setTangent (BufferElementGroupSPtr p_pElement, real x, real y, real z)
sets the group tangent
static void setBitangent (BufferElementGroupSPtr p_pElement, castor::Coords3r const &p_coord)
sets the group bitangent
static void setBitangent (BufferElementGroupSPtr p_pElement, castor::Point3r const &p_coord)
sets the group bitangent
static void setBitangent (BufferElementGroupSPtr p_pElement, real const *p_coord)
sets the group bitangent
static void setBitangent (BufferElementGroupSPtr p_pElement, real x, real y, real z)
sets the group bitangent
static void setTexCoord (BufferElementGroupSPtr p_pElement, castor::Coords3r const &p_coord)
sets the group texture coordinates
static void setTexCoord (BufferElementGroupSPtr p_pElement, castor::Point3r const &p_coord)
sets the group texture coordinates
static void setTexCoord (BufferElementGroupSPtr p_pElement, real const *p_coord)
sets the group texture coordinates
static void setTexCoord (BufferElementGroupSPtr p_pElement, real x, real y, real z=0)
sets the group texture coordinates
static castor::Coords3r & getPosition (BufferElementGroup &p_element, castor::Coords3r &p_coord)
Retrieves the group position.
static castor::Point3r & getPosition (BufferElementGroup const &p_element, castor::Point3r &p_point)
Retrieves the group position.
static void getPosition (BufferElementGroup const &p_element, std::array< real, 3 > &p_point)
Retrieves the group position.
static castor::Coords3r & getNormal (BufferElementGroup &p_element, castor::Coords3r &p_coord)
Retrieves the group normal.
static castor::Point3r & getNormal (BufferElementGroup const &p_element, castor::Point3r &p_point)
Retrieves the group normal.
static void getNormal (BufferElementGroup const &p_element, std::array< real, 3 > &p_point)
Retrieves the group normal.
static castor::Coords3r & getTangent (BufferElementGroup &p_element, castor::Coords3r &p_coord)
Retrieves the group tangent.
static castor::Point3r & getTangent (BufferElementGroup const &p_element, castor::Point3r &p_point)
Retrieves the group tangent.
static void getTangent (BufferElementGroup const &p_element, std::array< real, 3 > &p_point)
Retrieves the group tangent.
static castor::Coords3r & getBitangent (BufferElementGroup &p_element, castor::Coords3r &p_coord)
Retrieves the group bitangent.
static castor::Point3r & getBitangent (BufferElementGroup const &p_element, castor::Point3r &p_point)
Retrieves the group bitangent.
static void getBitangent (BufferElementGroup const &p_element, std::array< real, 3 > &p_point)
Retrieves the group bitangent.
static castor::Coords3r & getTexCoord (BufferElementGroup &p_element, castor::Coords3r &p_coord)
Retrieves the group texture coordinates.
static castor::Point3r & getTexCoord (BufferElementGroup const &p_element, castor::Point3r &p_point)
Retrieves the group texture coordinates.
static void getTexCoord (BufferElementGroup const &p_element, std::array< real, 3 > &p_point)
Retrieves the group texture coordinates.
static void setPosition (BufferElementGroup &p_element, castor::Coords3r const &p_coord)
sets the group position
static void setPosition (BufferElementGroup &p_element, castor::Point3r const &p_coord)
sets the group position
static void setPosition (BufferElementGroup &p_element, real const *p_coord)
sets the group position
static void setPosition (BufferElementGroup &p_element, real x, real y, real z)
sets the group position
static void setNormal (BufferElementGroup &p_element, castor::Coords3r const &p_coord)
sets the group normal
static void setNormal (BufferElementGroup &p_element, castor::Point3r const &p_coord)
sets the group normal
static void setNormal (BufferElementGroup &p_element, real const *p_coord)
sets the group normal
static void setNormal (BufferElementGroup &p_element, real x, real y, real z)
sets the group normal
static void setTangent (BufferElementGroup &p_element, castor::Coords3r const &p_coord)
sets the group tangent
static void setTangent (BufferElementGroup &p_element, castor::Point3r const &p_coord)
sets the group tangent
static void setTangent (BufferElementGroup &p_element, real const *p_coord)
sets the group tangent
static void setTangent (BufferElementGroup &p_element, real x, real y, real z)
sets the group tangent
static void setBitangent (BufferElementGroup &p_element, castor::Coords3r const &p_coord)
sets the group bitangent
static void setBitangent (BufferElementGroup &p_element, castor::Point3r const &p_coord)
sets the group bitangent
static void setBitangent (BufferElementGroup &p_element, real const *p_coord)
sets the group bitangent
static void setBitangent (BufferElementGroup &p_element, real x, real y, real z)
sets the group bitangent
static void setTexCoord (BufferElementGroup &p_element, castor::Coords3r const &p_coord)
sets the group texture coordinates
static void setTexCoord (BufferElementGroup &p_element, castor::Point3r const &p_coord)
sets the group texture coordinates
static void setTexCoord (BufferElementGroup &p_element, real const *p_coord)
sets the group texture coordinates
static void setTexCoord (BufferElementGroup &p_element, real x, real y, real z=0)
sets the group texture coordinates
Detailed Description
Representation of a vertex.
Author
Sylvain DOREMUS
Version
0.7.0
Date
27/06/2013
Remarks
Wraps BufferElementGroup to easily retrieve vertex's position, normal, tangent and texture coordinates, an index
Constructor & Destructor Documentation
Vertex() [1/2]
C3D_API castor3d::Vertex::Vertex (BufferElementGroup & p_group) explicit
Constructor.
Parameters
[in] p_group The wrapped group
Vertex() [2/2]
C3D_API castor3d::Vertex::Vertex (Vertex const & p_source)
Copy constructor.
Parameters
[in] p_source The source object
~Vertex()
virtual C3D_API castor3d::Vertex::~Vertex () virtual
Destructor.
Member Function Documentation
getBitangent() [1/12]
castor::Coords3r& castor3d::Vertex::getBitangent (castor::Coords3r & p_ptBitan) inline
Retrieves the vertex bitangent.
Returns
The value
References castor3d::BufferElementGroup::ptr().
Referenced by getBitangent().
getBitangent() [2/12]
castor::Point3r& castor3d::Vertex::getBitangent (castor::Point3r & p_ptBitan) const inline
Retrieves the vertex bitangent.
Returns
The value
References castor3d::BufferElementGroup::constPtr(), and getBitangent().
getBitangent() [3/12]
static C3D_API castor::Coords3r castor3d::Vertex::getBitangent (void * p_buffer) static
Retrieves a vertex bitangent from a buffer.
Parameters
[in] p_buffer The buffer
Returns
The value
getBitangent() [4/12]
static C3D_API castor::Point3r castor3d::Vertex::getBitangent (void const * p_buffer) static
Retrieves a vertex bitangent from a buffer.
Parameters
[in] p_buffer The buffer
Returns
The value
getBitangent() [5/12]
static castor::Coords3r& castor3d::Vertex::getBitangent (void * p_buffer, castor::Coords3r & p_coord) inline static
Retrieves a vertex bitangent from a buffer.
Parameters
[in] p_buffer The buffer
[out] p_coord Receives the value
Returns
The value
References getBitangent().
getBitangent() [6/12]
static castor::Point3r& castor3d::Vertex::getBitangent (void const * p_buffer, castor::Point3r & p_coord) inline static
Retrieves a vertex bitangent from a buffer.
Parameters
[in] p_buffer The buffer
[out] p_coord Receives the value
Returns
The value
References getBitangent().
getBitangent() [7/12]
static void castor3d::Vertex::getBitangent (void const * p_buffer, std::array< real, 3 > & p_coord) inline static
Retrieves a vertex bitangent from a buffer.
Parameters
[in] p_buffer The buffer
[out] p_coord Receives the value
Returns
The value
References getBitangent().
getBitangent() [8/12]
static castor::Coords3r& castor3d::Vertex::getBitangent (BufferElementGroupSPtr p_pElement, castor::Coords3r & p_coord) inline static
Retrieves the group bitangent.
Parameters
[in] p_pElement The group
[out] p_coord Receives the bitangent
Returns
The value
References getBitangent().
getBitangent() [9/12]
static castor::Point3r& castor3d::Vertex::getBitangent (BufferElementGroupSPtr p_pElement, castor::Point3r & p_point) inline static
Retrieves the group bitangent.
Parameters
[in] p_pElement The group
[out] p_point Receives the bitangent
Returns
The value
References getBitangent().
getBitangent() [10/12]
static castor::Coords3r& castor3d::Vertex::getBitangent (BufferElementGroup & p_element, castor::Coords3r & p_coord) inline static
Retrieves the group bitangent.
Parameters
[in] p_element The group
[out] p_coord Receives the bitangent
Returns
The value
References getBitangent(), and castor3d::BufferElementGroup::ptr().
getBitangent() [11/12]
static castor::Point3r& castor3d::Vertex::getBitangent (BufferElementGroup const & p_element, castor::Point3r & p_point) inline static
Retrieves the group bitangent.
Parameters
[in] p_element The group
[out] p_point Receives the bitangent
Returns
The value
References castor3d::BufferElementGroup::constPtr(), and getBitangent().
getBitangent() [12/12]
static void castor3d::Vertex::getBitangent (BufferElementGroup const & p_element, std::array< real, 3 > & p_point) inline static
Retrieves the group bitangent.
Parameters
[in] p_element The group
[out] p_point Receives the bitangent
Returns
The value
References castor3d::BufferElementGroup::constPtr(), and getBitangent().
getCountBin()
static const uint32_t castor3d::Vertex::getCountBin () inline static
Retrieves bitangent elements count.
Returns
The value
getCountNml()
static const uint32_t castor3d::Vertex::getCountNml () inline static
Retrieves normal elements count.
Returns
The value
getCountPos()
static const uint32_t castor3d::Vertex::getCountPos () inline static
Retrieves position elements count.
Returns
The value
getCountTan()
static const uint32_t castor3d::Vertex::getCountTan () inline static
Retrieves tangent elements count.
Returns
The value
getCountTex()
static const uint32_t castor3d::Vertex::getCountTex () inline static
Retrieves texture coordinates elements count.
Returns
The value
getNormal() [1/12]
castor::Coords3r& castor3d::Vertex::getNormal (castor::Coords3r & p_ptNml) inline
Retrieves the vertex normal.
Returns
The value
References castor3d::BufferElementGroup::ptr().
Referenced by getNormal().
getNormal() [2/12]
castor::Point3r& castor3d::Vertex::getNormal (castor::Point3r & p_ptNml) const inline
Retrieves the vertex normal.
Returns
The value
References castor3d::BufferElementGroup::constPtr(), and getNormal().
getNormal() [3/12]
static C3D_API castor::Coords3r castor3d::Vertex::getNormal (void * p_buffer) static
Retrieves a vertex normal from a buffer.
Parameters
[in] p_buffer The buffer
Returns
The value
getNormal() [4/12]
static C3D_API castor::Point3r castor3d::Vertex::getNormal (void const * p_buffer) static
Retrieves a vertex normal from a buffer.
Parameters
[in] p_buffer The buffer
Returns
The value
getNormal() [5/12]
static castor::Coords3r& castor3d::Vertex::getNormal (void * p_buffer, castor::Coords3r & p_coord) inline static
Retrieves a vertex normal from a buffer.
Parameters
[in] p_buffer The buffer
[out] p_coord Receives the value
Returns
The value
References getNormal().
getNormal() [6/12]
static castor::Point3r& castor3d::Vertex::getNormal (void const * p_buffer, castor::Point3r & p_coord) inline static
Retrieves a vertex normal from a buffer.
Parameters
[in] p_buffer The buffer
[out] p_coord Receives the value
Returns
The value
References getNormal().
getNormal() [7/12]
static void castor3d::Vertex::getNormal (void const * p_buffer, std::array< real, 3 > & p_coord) inline static
Retrieves a vertex normal from a buffer.
Parameters
[in] p_buffer The buffer
[out] p_coord Receives the value
Returns
The value
References getNormal().
getNormal() [8/12]
static castor::Coords3r& castor3d::Vertex::getNormal (BufferElementGroupSPtr p_pElement, castor::Coords3r & p_coord) inline static
Retrieves the group normal.
Parameters
[in] p_pElement The group
[out] p_coord Receives the normal
Returns
The value
References getNormal().
getNormal() [9/12]
static castor::Point3r& castor3d::Vertex::getNormal (BufferElementGroupSPtr p_pElement, castor::Point3r & p_point) inline static
Retrieves the group normal.
Parameters
[in] p_pElement The group
[out] p_point Receives the normal
Returns
The value
References getNormal().
getNormal() [10/12]
static castor::Coords3r& castor3d::Vertex::getNormal (BufferElementGroup & p_element, castor::Coords3r & p_coord) inline static
Retrieves the group normal.
Parameters
[in] p_element The group
[out] p_coord Receives the normal
Returns
The value
References getNormal(), and castor3d::BufferElementGroup::ptr().
getNormal() [11/12]
static castor::Point3r& castor3d::Vertex::getNormal (BufferElementGroup const & p_element, castor::Point3r & p_point) inline static
Retrieves the group normal.
Parameters
[in] p_element The group
[out] p_point Receives the normal
Returns
The value
References castor3d::BufferElementGroup::constPtr(), and getNormal().
getNormal() [12/12]
static void castor3d::Vertex::getNormal (BufferElementGroup const & p_element, std::array< real, 3 > & p_point) inline static
Retrieves the group normal.
Parameters
[in] p_element The group
[out] p_point Receives the normal
Returns
The value
References castor3d::BufferElementGroup::constPtr(), and getNormal().
getOffsetBin()
static const uint32_t castor3d::Vertex::getOffsetBin () inline static
Retrieves bitangent's buffer offset.
Returns
The value
getOffsetNml()
static const uint32_t castor3d::Vertex::getOffsetNml () inline static
Retrieves normal's buffer offset.
Returns
The value
getOffsetPos()
static const uint32_t castor3d::Vertex::getOffsetPos () inline static
Retrieves position's buffer offset.
Returns
The value
getOffsetTan()
static const uint32_t castor3d::Vertex::getOffsetTan () inline static
Retrieves tangent's buffer offset.
Returns
The value
getOffsetTex()
static const uint32_t castor3d::Vertex::getOffsetTex () inline static
Retrieves texture coordinates' buffer offset.
Returns
The value
getPosition() [1/12]
castor::Coords3r& castor3d::Vertex::getPosition (castor::Coords3r & p_ptPos) inline
Retrieves the vertex position.
Returns
The value
References castor3d::BufferElementGroup::ptr().
Referenced by getPosition().
getPosition() [2/12]
castor::Point3r& castor3d::Vertex::getPosition (castor::Point3r & p_ptPos) const inline
Retrieves the vertex position.
Returns
The value
References castor3d::BufferElementGroup::constPtr(), and getPosition().
getPosition() [3/12]
static C3D_API castor::Coords3r castor3d::Vertex::getPosition (void * p_buffer) static
Retrieves a vertex position from a buffer.
Parameters
[in] p_buffer The buffer
Returns
The value
getPosition() [4/12]
static C3D_API castor::Point3r castor3d::Vertex::getPosition (void const * p_buffer) static
Retrieves a vertex position from a buffer.
Parameters
[in] p_buffer The buffer
Returns
The value
getPosition() [5/12]
static castor::Coords3r& castor3d::Vertex::getPosition (void * p_buffer, castor::Coords3r & p_coord) inline static
Retrieves a vertex position from a buffer.
Parameters
[in] p_buffer The buffer
[out] p_coord Receives the value
Returns
The value
References getPosition().
getPosition() [6/12]
static castor::Point3r& castor3d::Vertex::getPosition (void const * p_buffer, castor::Point3r & p_coord) inline static
Retrieves a vertex position from a buffer.
Parameters
[in] p_buffer The buffer
[out] p_coord Receives the value
Returns
The value
References getPosition().
getPosition() [7/12]
static void castor3d::Vertex::getPosition (void const * p_buffer, std::array< real, 3 > & p_coord) inline static
Retrieves a vertex position from a buffer.
Parameters
[in] p_buffer The buffer
[out] p_coord Receives the value
References getPosition().
getPosition() [8/12]
static castor::Coords3r& castor3d::Vertex::getPosition (BufferElementGroupSPtr p_pElement, castor::Coords3r & p_coord) inline static
Retrieves the group position.
Parameters
[in] p_pElement The group
[out] p_coord Receives the coordinates
Returns
The value
References getPosition().
getPosition() [9/12]
static castor::Point3r& castor3d::Vertex::getPosition (BufferElementGroupSPtr p_pElement, castor::Point3r & p_point) inline static
Retrieves the group position.
Parameters
[in] p_pElement The group
[out] p_point Receives the coordinates
Returns
The value
References getPosition().
getPosition() [10/12]
static castor::Coords3r& castor3d::Vertex::getPosition (BufferElementGroup & p_element, castor::Coords3r & p_coord) inline static
Retrieves the group position.
Parameters
[in] p_element The group
[out] p_coord Receives the coordinates
Returns
The value
References getPosition(), and castor3d::BufferElementGroup::ptr().
getPosition() [11/12]
static castor::Point3r& castor3d::Vertex::getPosition (BufferElementGroup const & p_element, castor::Point3r & p_point) inline static
Retrieves the group position.
Parameters
[in] p_element The group
[out] p_point Receives the coordinates
Returns
The value
References castor3d::BufferElementGroup::constPtr(), and getPosition().
getPosition() [12/12]
static void castor3d::Vertex::getPosition (BufferElementGroup const & p_element, std::array< real, 3 > & p_point) inline static
Retrieves the group position.
Parameters
[in] p_element The group
[out] p_point Receives the coordinates
Returns
The value
References castor3d::BufferElementGroup::constPtr(), and getPosition().
getSizeBin()
static const uint32_t castor3d::Vertex::getSizeBin () inline static
Retrieves bitangent binary size.
Returns
The value
getSizeNml()
static const uint32_t castor3d::Vertex::getSizeNml () inline static
Retrieves normal binary size.
Returns
The value
getSizePos()
static const uint32_t castor3d::Vertex::getSizePos () inline static
Retrieves position binary size.
Returns
The value
getSizeTan()
static const uint32_t castor3d::Vertex::getSizeTan () inline static
Retrieves tangent binary size.
Returns
The value
getSizeTex()
static const uint32_t castor3d::Vertex::getSizeTex () inline static
Retrieves texture coordinates binary size.
Returns
The value
getTangent() [1/12]
castor::Coords3r& castor3d::Vertex::getTangent (castor::Coords3r & p_ptTan) inline
Retrieves the vertex tangent.
Returns
The value
References castor3d::BufferElementGroup::ptr().
Referenced by getTangent().
getTangent() [2/12]
castor::Point3r& castor3d::Vertex::getTangent (castor::Point3r & p_ptTan) const inline
Retrieves the vertex tangent.
Returns
The value
References castor3d::BufferElementGroup::constPtr(), and getTangent().
getTangent() [3/12]
static C3D_API castor::Coords3r castor3d::Vertex::getTangent (void * p_buffer) static
Retrieves a vertex tangent from a buffer.
Parameters
[in] p_buffer The buffer
Returns
The value
getTangent() [4/12]
static C3D_API castor::Point3r castor3d::Vertex::getTangent (void const * p_buffer) static
Retrieves a vertex tangent from a buffer.
Parameters
[in] p_buffer The buffer
Returns
The value
getTangent() [5/12]
static castor::Coords3r& castor3d::Vertex::getTangent (void * p_buffer, castor::Coords3r & p_coord) inline static
Retrieves a vertex tangent from a buffer.
Parameters
[in] p_buffer The buffer
[out] p_coord Receives the value
Returns
The value
References getTangent().
getTangent() [6/12]
static void castor3d::Vertex::getTangent (void const * p_buffer, std::array< real, 3 > & p_coord) inline static
Retrieves a vertex tangent from a buffer.
Parameters
[in] p_buffer The buffer
[out] p_coord Receives the value
Returns
The value
References getTangent().
getTangent() [7/12]
static castor::Point3r& castor3d::Vertex::getTangent (void const * p_buffer, castor::Point3r & p_coord) inline static
Retrieves a vertex tangent from a buffer.
Parameters
[in] p_buffer The buffer
[out] p_coord Receives the value
Returns
The value
References getTangent().
getTangent() [8/12]
static castor::Coords3r& castor3d::Vertex::getTangent (BufferElementGroupSPtr p_pElement, castor::Coords3r & p_coord) inline static
Retrieves the group tangent.
Parameters
[in] p_pElement The group
[out] p_coord Receives the tangent
Returns
The value
References getTangent().
getTangent() [9/12]
static castor::Point3r& castor3d::Vertex::getTangent (BufferElementGroupSPtr p_pElement, castor::Point3r & p_point) inline static
Retrieves the group tangent.
Parameters
[in] p_pElement The group
[out] p_point Receives the tangent
Returns
The value
References getTangent().
getTangent() [10/12]
static castor::Coords3r& castor3d::Vertex::getTangent (BufferElementGroup & p_element, castor::Coords3r & p_coord) inline static
Retrieves the group tangent.
Parameters
[in] p_element The group
[out] p_coord Receives the tangent
Returns
The value
References getTangent(), and castor3d::BufferElementGroup::ptr().
getTangent() [11/12]
static castor::Point3r& castor3d::Vertex::getTangent (BufferElementGroup const & p_element, castor::Point3r & p_point) inline static
Retrieves the group tangent.
Parameters
[in] p_element The group
[out] p_point Receives the tangent
Returns
The value
References castor3d::BufferElementGroup::constPtr(), and getTangent().
getTangent() [12/12]
static void castor3d::Vertex::getTangent (BufferElementGroup const & p_element, std::array< real, 3 > & p_point) inline static
Retrieves the group tangent.
Parameters
[in] p_element The group
[out] p_point Receives the tangent
Returns
The value
References castor3d::BufferElementGroup::constPtr(), and getTangent().
getTexCoord() [1/12]
castor::Coords3r& castor3d::Vertex::getTexCoord (castor::Coords3r & p_ptTex) inline
Retrieves the vertex texture coordinates.
Returns
The value
References castor3d::BufferElementGroup::ptr().
Referenced by getTexCoord().
getTexCoord() [2/12]
castor::Point3r& castor3d::Vertex::getTexCoord (castor::Point3r & p_ptTex) const inline
Retrieves the vertex texture coordinates.
Returns
The value
References castor3d::BufferElementGroup::constPtr(), and getTexCoord().
getTexCoord() [3/12]
static C3D_API castor::Coords3r castor3d::Vertex::getTexCoord (void * p_buffer) static
Retrieves a vertex texture coordinates from a buffer.
Parameters
[in] p_buffer The buffer
Returns
The value
getTexCoord() [4/12]
static C3D_API castor::Point3r castor3d::Vertex::getTexCoord (void const * p_buffer) static
Retrieves a vertex texture coordinates from a buffer.
Parameters
[in] p_buffer The buffer
Returns
The value
getTexCoord() [5/12]
static castor::Coords3r& castor3d::Vertex::getTexCoord (void * p_buffer, castor::Coords3r & p_coord) inline static
Retrieves a vertex texture coordinates from a buffer.
Parameters
[in] p_buffer The buffer
[out] p_coord Receives the value
Returns
The value
References getTexCoord().
getTexCoord() [6/12]
static castor::Point3r& castor3d::Vertex::getTexCoord (void const * p_buffer, castor::Point3r & p_coord) inline static
Retrieves a vertex texture coordinates from a buffer.
Parameters
[in] p_buffer The buffer
[out] p_coord Receives the value
Returns
The value
References getTexCoord().
getTexCoord() [7/12]
static void castor3d::Vertex::getTexCoord (void const * p_buffer, std::array< real, 3 > & p_coord) inline static
Retrieves a vertex texture coordinates from a buffer.
Parameters
[in] p_buffer The buffer
[out] p_coord Receives the value
Returns
The value
References getTexCoord().
getTexCoord() [8/12]
static castor::Coords3r& castor3d::Vertex::getTexCoord (BufferElementGroupSPtr p_pElement, castor::Coords3r & p_coord) inline static
Retrieves the group texture coordinates.
Parameters
[in] p_pElement The group
[out] p_coord Receives the texture coordinates
Returns
The value
References getTexCoord().
getTexCoord() [9/12]
static castor::Point3r& castor3d::Vertex::getTexCoord (BufferElementGroupSPtr p_pElement, castor::Point3r & p_point) inline static
Retrieves the group texture coordinates.
Parameters
[in] p_pElement The group
[out] p_point Receives the texture coordinates
Returns
The value
References getTexCoord().
getTexCoord() [10/12]
static castor::Coords3r& castor3d::Vertex::getTexCoord (BufferElementGroup & p_element, castor::Coords3r & p_coord) inline static
Retrieves the group texture coordinates.
Parameters
[in] p_element The group
[out] p_coord Receives the texture coordinates
Returns
The value
References getTexCoord(), and castor3d::BufferElementGroup::ptr().
getTexCoord() [11/12]
static castor::Point3r& castor3d::Vertex::getTexCoord (BufferElementGroup const & p_element, castor::Point3r & p_point) inline static
Retrieves the group texture coordinates.
Parameters
[in] p_element The group
[out] p_point Receives the texture coordinates
Returns
The value
References castor3d::BufferElementGroup::constPtr(), and getTexCoord().
getTexCoord() [12/12]
static void castor3d::Vertex::getTexCoord (BufferElementGroup const & p_element, std::array< real, 3 > & p_point) inline static
Retrieves the group texture coordinates.
Parameters
[in] p_element The group
[out] p_point Receives the texture coordinates
Returns
The value
References castor3d::BufferElementGroup::constPtr(), and getTexCoord().
operator=()
C3D_API Vertex& castor3d::Vertex::operator= (Vertex const & p_source)
Copy assignment operator.
Parameters
[in] p_source The source object
Returns
A reference to this object
setBitangent() [1/16]
void castor3d::Vertex::setBitangent (castor::Coords3r const & val) inline
sets the vertex bitangent
Parameters
[in] val The value
References castor3d::BufferElementGroup::ptr().
Referenced by setBitangent().
setBitangent() [2/16]
void castor3d::Vertex::setBitangent (castor::Point3r const & val) inline
sets the vertex bitangent
Parameters
[in] val The value
References castor3d::BufferElementGroup::ptr(), and setBitangent().
setBitangent() [3/16]
void castor3d::Vertex::setBitangent (real x, real y, real z) inline
sets the vertex bitangent
Parameters
[in] x,y,z The values
References castor3d::BufferElementGroup::ptr(), and setBitangent().
setBitangent() [4/16]
void castor3d::Vertex::setBitangent (real const * p_coords) inline
sets the vertex bitangent
Parameters
[in] p_coords The data buffer
References castor3d::BufferElementGroup::ptr(), and setBitangent().
setBitangent() [5/16]
static void castor3d::Vertex::setBitangent (void * p_buffer, castor::Coords3r const & p_coord) inline static
sets the vertex bitangent in a buffer
Parameters
[in] p_buffer The buffer
[in] p_coord The new value
References setBitangent().
setBitangent() [6/16]
static void castor3d::Vertex::setBitangent (void * p_buffer, castor::Point3r const & p_coord) inline static
sets the vertex bitangent in a buffer
Parameters
[in] p_buffer The buffer
[in] p_coord The new value
References setBitangent().
setBitangent() [7/16]
static C3D_API void castor3d::Vertex::setBitangent (void * p_buffer, real const * p_coord) static
sets the vertex bitangent in a buffer
Parameters
[in] p_buffer The buffer
[in] p_coord The new value
setBitangent() [8/16]
static C3D_API void castor3d::Vertex::setBitangent (void * p_buffer, real x, real y, real z) static
sets the vertex bitangent in a buffer
Parameters
[in] p_buffer The buffer
[in] x,y,z The new value
setBitangent() [9/16]
static void castor3d::Vertex::setBitangent (BufferElementGroupSPtr p_pElement, castor::Coords3r const & p_coord) inline static
sets the group bitangent
Parameters
[in] p_pElement The group
[in] p_coord The new value
References setBitangent().
setBitangent() [10/16]
static void castor3d::Vertex::setBitangent (BufferElementGroupSPtr p_pElement, castor::Point3r const & p_coord) inline static
sets the group bitangent
Parameters
[in] p_pElement The group
[in] p_coord The new value
References setBitangent().
setBitangent() [11/16]
static void castor3d::Vertex::setBitangent (BufferElementGroupSPtr p_pElement, real const * p_coord) inline static
sets the group bitangent
Parameters
[in] p_pElement The group
[in] p_coord The new value
References setBitangent().
setBitangent() [12/16]
static void castor3d::Vertex::setBitangent (BufferElementGroupSPtr p_pElement, real x, real y, real z) inline static
sets the group bitangent
Parameters
[in] p_pElement The group
[in] x,y,z The new value
References setBitangent().
setBitangent() [13/16]
static void castor3d::Vertex::setBitangent (BufferElementGroup & p_element, castor::Coords3r const & p_coord) inline static
sets the group bitangent
Parameters
[out] p_element The group
[in] p_coord The new value
References castor3d::BufferElementGroup::ptr(), and setBitangent().
setBitangent() [14/16]
static void castor3d::Vertex::setBitangent (BufferElementGroup & p_element, castor::Point3r const & p_coord) inline static
sets the group bitangent
Parameters
[out] p_element The group
[in] p_coord The new value
References castor3d::BufferElementGroup::ptr(), and setBitangent().
setBitangent() [15/16]
static void castor3d::Vertex::setBitangent (BufferElementGroup & p_element, real const * p_coord) inline static
sets the group bitangent
Parameters
[out] p_element The group
[in] p_coord The new value
References castor3d::BufferElementGroup::ptr(), and setBitangent().
setBitangent() [16/16]
static void castor3d::Vertex::setBitangent (BufferElementGroup & p_element, real x, real y, real z) inline static
sets the group bitangent
Parameters
[out] p_element The group
[in] x,y,z The new value
References castor3d::BufferElementGroup::ptr(), and setBitangent().
setNormal() [1/16]
void castor3d::Vertex::setNormal (castor::Coords3r const & val) inline
sets the vertex normal
Parameters
[in] val The value
References castor3d::BufferElementGroup::ptr().
Referenced by setNormal().
setNormal() [2/16]
void castor3d::Vertex::setNormal (castor::Point3r const & val) inline
sets the vertex normal
Parameters
[in] val The value
References castor3d::BufferElementGroup::ptr(), and setNormal().
setNormal() [3/16]
void castor3d::Vertex::setNormal (real x, real y, real z) inline
sets the vertex normal
Parameters
[in] x,y,z The values
References castor3d::BufferElementGroup::ptr(), and setNormal().
setNormal() [4/16]
void castor3d::Vertex::setNormal (real const * p_coords) inline
sets the vertex normal
Parameters
[in] p_coords The data buffer
References castor3d::BufferElementGroup::ptr(), and setNormal().
setNormal() [5/16]
static void castor3d::Vertex::setNormal (void * p_buffer, castor::Coords3r const & p_coord) inline static
sets the vertex normal in a buffer
Parameters
[in] p_buffer The buffer
[in] p_coord The new value
References setNormal().
setNormal() [6/16]
static void castor3d::Vertex::setNormal (void * p_buffer, castor::Point3r const & p_coord) inline static
sets the vertex normal in a buffer
Parameters
[in] p_buffer The buffer
[in] p_coord The new value
References setNormal().
setNormal() [7/16]
static C3D_API void castor3d::Vertex::setNormal (void * p_buffer, real const * p_coord) static
sets the vertex normal in a buffer
Parameters
[in] p_buffer The buffer
[in] p_coord The new value
setNormal() [8/16]
static C3D_API void castor3d::Vertex::setNormal (void * p_buffer, real x, real y, real z) static
sets the vertex normal in a buffer
Parameters
[in] p_buffer The buffer
[in] x,y,z The new value
setNormal() [9/16]
static void castor3d::Vertex::setNormal (BufferElementGroupSPtr p_pElement, castor::Coords3r const & p_coord) inline static
sets the group normal
Parameters
[in] p_pElement The group
[in] p_coord The new value
References setNormal().
setNormal() [10/16]
static void castor3d::Vertex::setNormal (BufferElementGroupSPtr p_pElement, castor::Point3r const & p_coord) inline static
sets the group normal
Parameters
[in] p_pElement The group
[in] p_coord The new value
References setNormal().
setNormal() [11/16]
static void castor3d::Vertex::setNormal (BufferElementGroupSPtr p_pElement, real const * p_coord) inline static
sets the group normal
Parameters
[in] p_pElement The group
[in] p_coord The new value
References setNormal().
setNormal() [12/16]
static void castor3d::Vertex::setNormal (BufferElementGroupSPtr p_pElement, real x, real y, real z) inline static
sets the group normal
Parameters
[in] p_pElement The group
[in] x,y,z The new value
References setNormal().
setNormal() [13/16]
static void castor3d::Vertex::setNormal (BufferElementGroup & p_element, castor::Coords3r const & p_coord) inline static
sets the group normal
Parameters
[out] p_element The group
[in] p_coord The new value
References castor3d::BufferElementGroup::ptr(), and setNormal().
setNormal() [14/16]
static void castor3d::Vertex::setNormal (BufferElementGroup & p_element, castor::Point3r const & p_coord) inline static
sets the group normal
Parameters
[out] p_element The group
[in] p_coord The new value
References castor3d::BufferElementGroup::ptr(), and setNormal().
setNormal() [15/16]
static void castor3d::Vertex::setNormal (BufferElementGroup & p_element, real const * p_coord) inline static
sets the group normal
Parameters
[out] p_element The group
[in] p_coord The new value
References castor3d::BufferElementGroup::ptr(), and setNormal().
setNormal() [16/16]
static void castor3d::Vertex::setNormal (BufferElementGroup & p_element, real x, real y, real z) inline static
sets the group normal
Parameters
[out] p_element The group
[in] x,y,z The new value
References castor3d::BufferElementGroup::ptr(), and setNormal().
setPosition() [1/16]
void castor3d::Vertex::setPosition (castor::Coords3r const & val) inline
sets the vertex position
Parameters
[in] val The new value
References castor3d::BufferElementGroup::ptr().
Referenced by setPosition().
setPosition() [2/16]
void castor3d::Vertex::setPosition (castor::Point3r const & val) inline
sets the vertex position
Parameters
[in] val The new value
References castor3d::BufferElementGroup::ptr(), and setPosition().
setPosition() [3/16]
void castor3d::Vertex::setPosition (real x, real y, real z) inline
sets the vertex position
Parameters
[in] x,y,z The new value
References castor3d::BufferElementGroup::ptr(), and setPosition().
setPosition() [4/16]
void castor3d::Vertex::setPosition (real const * p_coords) inline
sets the vertex position
Parameters
[in] p_coords The new value
References castor3d::BufferElementGroup::ptr(), and setPosition().
setPosition() [5/16]
static void castor3d::Vertex::setPosition (void * p_buffer, castor::Coords3r const & p_coord) inline static
sets the vertex position in a buffer
Parameters
[in] p_buffer The buffer
[in] p_coord The new value
References setPosition().
setPosition() [6/16]
static void castor3d::Vertex::setPosition (void * p_buffer, castor::Point3r const & p_coord) inline static
sets the vertex position in a buffer
Parameters
[in] p_buffer The buffer
[in] p_coord The new value
References setPosition().
setPosition() [7/16]
static C3D_API void castor3d::Vertex::setPosition (void * p_buffer, real const * p_coord) static
sets the vertex position in a buffer
Parameters
[in] p_buffer The buffer
[in] p_coord The new value
setPosition() [8/16]
static C3D_API void castor3d::Vertex::setPosition (void * p_buffer, real x, real y, real z) static
sets the vertex position in a buffer
Parameters
[in] p_buffer The buffer
[in] x,y,z The new value
setPosition() [9/16]
static void castor3d::Vertex::setPosition (BufferElementGroupSPtr p_pElement, castor::Coords3r const & p_coord) inline static
sets the group position
Parameters
[in] p_pElement The group
[in] p_coord The new value
References setPosition().
setPosition() [10/16]
static void castor3d::Vertex::setPosition (BufferElementGroupSPtr p_pElement, castor::Point3r const & p_coord) inline static
sets the group position
Parameters
[in] p_pElement The group
[in] p_coord The new value
References setPosition().
setPosition() [11/16]
static void castor3d::Vertex::setPosition (BufferElementGroupSPtr p_pElement, real const * p_coord) inline static
sets the group position
Parameters
[in] p_pElement The group
[in] p_coord The new value
References setPosition().
setPosition() [12/16]
static void castor3d::Vertex::setPosition (BufferElementGroupSPtr p_pElement, real x, real y, real z) inline static
sets the group position
Parameters
[in] p_pElement The group
[in] x,y,z The new value
References setPosition().
setPosition() [13/16]
static void castor3d::Vertex::setPosition (BufferElementGroup & p_element, castor::Coords3r const & p_coord) inline static
sets the group position
Parameters
[out] p_element The group
[in] p_coord The new value
References castor3d::BufferElementGroup::ptr(), and setPosition().
setPosition() [14/16]
static void castor3d::Vertex::setPosition (BufferElementGroup & p_element, castor::Point3r const & p_coord) inline static
sets the group position
Parameters
[out] p_element The group
[in] p_coord The new value
References castor3d::BufferElementGroup::ptr(), and setPosition().
setPosition() [15/16]
static void castor3d::Vertex::setPosition (BufferElementGroup & p_element, real const * p_coord) inline static
sets the group position
Parameters
[out] p_element The group
[in] p_coord The new value
References castor3d::BufferElementGroup::ptr(), and setPosition().
setPosition() [16/16]
static void castor3d::Vertex::setPosition (BufferElementGroup & p_element, real x, real y, real z) inline static
sets the group position
Parameters
[out] p_element The group
[in] x,y,z The new value
References castor3d::BufferElementGroup::ptr(), and setPosition().
setTangent() [1/16]
void castor3d::Vertex::setTangent (castor::Coords3r const & val) inline
sets the vertex tangent
Parameters
[in] val The value
References castor3d::BufferElementGroup::ptr().
Referenced by setTangent().
setTangent() [2/16]
void castor3d::Vertex::setTangent (castor::Point3r const & val) inline
sets the vertex tangent
Parameters
[in] val The value
References castor3d::BufferElementGroup::ptr(), and setTangent().
setTangent() [3/16]
void castor3d::Vertex::setTangent (real x, real y, real z) inline
sets the vertex tangent
Parameters
[in] x,y,z The values
References castor3d::BufferElementGroup::ptr(), and setTangent().
setTangent() [4/16]
void castor3d::Vertex::setTangent (real const * p_coords) inline
sets the vertex tangent
Parameters
[in] p_coords The data buffer
References castor3d::BufferElementGroup::ptr(), and setTangent().
setTangent() [5/16]
static void castor3d::Vertex::setTangent (void * p_buffer, castor::Coords3r const & p_coord) inline static
sets the vertex tangent in a buffer
Parameters
[in] p_buffer The buffer
[in] p_coord The new value
References setTangent().
setTangent() [6/16]
static void castor3d::Vertex::setTangent (void * p_buffer, castor::Point3r const & p_coord) inline static
sets the vertex tangent in a buffer
Parameters
[in] p_buffer The buffer
[in] p_coord The new value
References setTangent().
setTangent() [7/16]
static C3D_API void castor3d::Vertex::setTangent (void * p_buffer, real const * p_coord) static
sets the vertex tangent in a buffer
Parameters
[in] p_buffer The buffer
[in] p_coord The new value
setTangent() [8/16]
static C3D_API void castor3d::Vertex::setTangent (void * p_buffer, real x, real y, real z) static
sets the vertex tangent in a buffer
Parameters
[in] p_buffer The buffer
[in] x,y,z The new value
setTangent() [9/16]
static void castor3d::Vertex::setTangent (BufferElementGroupSPtr p_pElement, castor::Coords3r const & p_coord) inline static
sets the group tangent
Parameters
[in] p_pElement The group
[in] p_coord The new value
References setTangent().
setTangent() [10/16]
static void castor3d::Vertex::setTangent (BufferElementGroupSPtr p_pElement, castor::Point3r const & p_coord) inline static
sets the group tangent
Parameters
[in] p_pElement The group
[in] p_coord The new value
References setTangent().
setTangent() [11/16]
static void castor3d::Vertex::setTangent (BufferElementGroupSPtr p_pElement, real const * p_coord) inline static
sets the group tangent
Parameters
[in] p_pElement The group
[in] p_coord The new value
References setTangent().
setTangent() [12/16]
static void castor3d::Vertex::setTangent (BufferElementGroupSPtr p_pElement, real x, real y, real z) inline static
sets the group tangent
Parameters
[in] p_pElement The group
[in] x,y,z The new value
References setTangent().
setTangent() [13/16]
static void castor3d::Vertex::setTangent (BufferElementGroup & p_element, castor::Coords3r const & p_coord) inline static
sets the group tangent
Parameters
[out] p_element The group
[in] p_coord The new value
References castor3d::BufferElementGroup::ptr(), and setTangent().
setTangent() [14/16]
static void castor3d::Vertex::setTangent (BufferElementGroup & p_element, castor::Point3r const & p_coord) inline static
sets the group tangent
Parameters
[out] p_element The group
[in] p_coord The new value
References castor3d::BufferElementGroup::ptr(), and setTangent().
setTangent() [15/16]
static void castor3d::Vertex::setTangent (BufferElementGroup & p_element, real const * p_coord) inline static
sets the group tangent
Parameters
[out] p_element The group
[in] p_coord The new value
References castor3d::BufferElementGroup::ptr(), and setTangent().
setTangent() [16/16]
static void castor3d::Vertex::setTangent (BufferElementGroup & p_element, real x, real y, real z) inline static
sets the group tangent
Parameters
[out] p_element The group
[in] x,y,z The new value
References castor3d::BufferElementGroup::ptr(), and setTangent().
setTexCoord() [1/16]
void castor3d::Vertex::setTexCoord (castor::Coords3r const & val) inline
sets the vertex texture coordinates
Parameters
[in] val The value
References castor3d::BufferElementGroup::ptr().
Referenced by setTexCoord().
setTexCoord() [2/16]
void castor3d::Vertex::setTexCoord (castor::Point3r const & val) inline
sets the vertex texture coordinates
Parameters
[in] val The value
References castor3d::BufferElementGroup::ptr(), and setTexCoord().
setTexCoord() [3/16]
void castor3d::Vertex::setTexCoord (real x, real y, real z = 0) inline
sets the vertex texture coordinates
Parameters
[in] x,y,z The values
References castor3d::BufferElementGroup::ptr(), and setTexCoord().
setTexCoord() [4/16]
void castor3d::Vertex::setTexCoord (real const * p_coords) inline
sets the vertex texture coordinates
Parameters
[in] p_coords The data buffer
References castor3d::BufferElementGroup::ptr(), and setTexCoord().
setTexCoord() [5/16]
static void castor3d::Vertex::setTexCoord (void * p_buffer, castor::Coords3r const & p_coord) inline static
sets the vertex texture coordinates in a buffer
Parameters
[in] p_buffer The buffer
[in] p_coord The new value
References setTexCoord().
setTexCoord() [6/16]
static void castor3d::Vertex::setTexCoord (void * p_buffer, castor::Point3r const & p_coord) inline static
sets the vertex texture coordinates in a buffer
Parameters
[in] p_buffer The buffer
[in] p_coord The new value
References setTexCoord().
setTexCoord() [7/16]
static C3D_API void castor3d::Vertex::setTexCoord (void * p_buffer, real const * p_coord) static
sets the vertex texture coordinates in a buffer
Parameters
[in] p_buffer The buffer
[in] p_coord The new value
setTexCoord() [8/16]
static C3D_API void castor3d::Vertex::setTexCoord (void * p_buffer, real x, real y, real z = 0) static
sets the vertex texture coordinates in a buffer
Parameters
[in] p_buffer The buffer
[in] x,y,z The new value
setTexCoord() [9/16]
static void castor3d::Vertex::setTexCoord (BufferElementGroupSPtr p_pElement, castor::Coords3r const & p_coord) inline static
sets the group texture coordinates
Parameters
[in] p_pElement The group
[in] p_coord The new value
References setTexCoord().
setTexCoord() [10/16]
static void castor3d::Vertex::setTexCoord (BufferElementGroupSPtr p_pElement, castor::Point3r const & p_coord) inline static
sets the group texture coordinates
Parameters
[in] p_pElement The group
[in] p_coord The new value
References setTexCoord().
setTexCoord() [11/16]
static void castor3d::Vertex::setTexCoord (BufferElementGroupSPtr p_pElement, real const * p_coord) inline static
sets the group texture coordinates
Parameters
[in] p_pElement The group
[in] p_coord The new value
References setTexCoord().
setTexCoord() [12/16]
static void castor3d::Vertex::setTexCoord (BufferElementGroupSPtr p_pElement, real x, real y, real z = 0) inline static
sets the group texture coordinates
Parameters
[in] p_pElement The group
[in] x,y,z The new value
References setTexCoord().
setTexCoord() [13/16]
static void castor3d::Vertex::setTexCoord (BufferElementGroup & p_element, castor::Coords3r const & p_coord) inline static
sets the group texture coordinates
Parameters
[out] p_element The group
[in] p_coord The new value
References castor3d::BufferElementGroup::ptr(), and setTexCoord().
setTexCoord() [14/16]
static void castor3d::Vertex::setTexCoord (BufferElementGroup & p_element, castor::Point3r const & p_coord) inline static
sets the group texture coordinates
Parameters
[out] p_element The group
[in] p_coord The new value
References castor3d::BufferElementGroup::ptr(), and setTexCoord().
setTexCoord() [15/16]
static void castor3d::Vertex::setTexCoord (BufferElementGroup & p_element, real const * p_coord) inline static
sets the group texture coordinates
Parameters
[out] p_element The group
[in] p_coord The new value
References castor3d::BufferElementGroup::ptr(), and setTexCoord().
setTexCoord() [16/16]
static void castor3d::Vertex::setTexCoord (BufferElementGroup & p_element, real x, real y, real z = 0) inline static
sets the group texture coordinates
Parameters
[out] p_element The group
[in] x,y,z The new value
References castor3d::BufferElementGroup::ptr(), and setTexCoord().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Mesh/Vertex.hpp