Castor3D: castor3d::BlendComponent Struct Reference
castor3d::BlendComponent Struct Reference
#include <BlendComponent.hpp>
Classes
class Plugin
Public Member Functions
C3D_API BlendComponent (Pass &pass)
C3D_API void accept (ConfigurationVisitorBase &vis) override
ConfigurationVisitorBase acceptance function.
C3D_API PassComponentFlag getPassFlags () const override
bool hasAlphaBlending () const
BlendMode getAlphaBlendMode () const
BlendMode getColourBlendMode () const
void setAlphaBlendMode (BlendMode value)
void setColourBlendMode (BlendMode value)
Public Member Functions inherited from castor3d::BaseDataPassComponentT< BlendData >
BaseDataPassComponentT (Pass &pass, castor::String type, castor::StringArray deps={}, ParamsT &&... params)
Constructor.
void setData (DataU const &data)
void setData (ParamsT &&... params)
BlendData & getData ()
BlendData const & getData () const
Public Member Functions inherited from castor3d::PassComponent
C3D_API PassComponent (Pass &pass, castor::String type, castor::StringArray deps={})
Constructor.
virtual C3D_API ~PassComponent () noexcept=default
C3D_API PassComponentUPtr clone (Pass &pass) const
virtual C3D_API void onAddToPass () const
Called when the component is added to the pass.
C3D_API bool writeText (castor::String const &tabs, castor::Path const &folder, castor::String const &subfolder, castor::StringStream &file) const
Writes the component content to text.
C3D_API void fillBuffer (PassBuffer &buffer) const
Fills the pass buffer with this pass data.
virtual C3D_API void update ()
C3D_API void fillChannel (TextureConfiguration &configuration, uint32_t mask) const
Fills the texture configuration for use with this component.
virtual C3D_API void fillConfig (TextureConfiguration &config, ConfigurationVisitorBase &vis) const
ConfigurationVisitorBase acceptance function, for a specific texture configuration.
virtual C3D_API bool hasColour () const
virtual C3D_API castor::HdrRgbColour const & getColour () const
virtual C3D_API void setColour (castor::HdrRgbColour v)
castor::String const & getType () const
castor::StringArray const & getDependencies () const
PassComponentPlugin const & getPlugin () const
PassComponentID getId () const
void setColour (castor::RgbColour const &v, float gamma=2.2f)
void setColour (castor::Coords3f const &v)
void setColour (castor::Point3f const &v)
Public Member Functions inherited from castor::OwnedBy< Pass >
Pass * getOwner () const
Static Public Member Functions
static PassComponentPluginUPtr createPlugin (PassComponentRegister const &passComponent)
Static Public Attributes
static constexpr PassFlag eAlphaBlending = PassFlag(0x01u)
static C3D_API castor::String const TypeName
Additional Inherited Members
Protected Member Functions inherited from castor::OwnedBy< Pass >
OwnedBy (Pass &owner)
Constructor.
Protected Attributes inherited from castor3d::BaseDataPassComponentT< BlendData >
BlendData m_value
Protected Attributes inherited from castor3d::PassComponent
castor::String m_type
castor::StringArray m_dependencies
PassComponentID m_id
PassComponentPlugin const & m_plugin
std::atomic_bool & m_dirty
shader::PassMaterialShader * m_materialShader {}
Constructor & Destructor Documentation
BlendComponent()
C3D_API castor3d::BlendComponent::BlendComponent (Pass & pass) explicit
Member Function Documentation
accept()
C3D_API void castor3d::BlendComponent::accept (ConfigurationVisitorBase & vis) override virtual
ConfigurationVisitorBase acceptance function.
Parameters
vis The ... visitor.
Reimplemented from castor3d::PassComponent.
createPlugin()
static PassComponentPluginUPtr castor3d::BlendComponent::createPlugin (PassComponentRegister const & passComponent) inline static
getAlphaBlendMode()
BlendMode castor3d::BlendComponent::getAlphaBlendMode () const inline
References castor3d::BlendData::alphaBlendMode, and castor3d::BaseDataPassComponentT< BlendData >::m_value.
Referenced by hasAlphaBlending().
getColourBlendMode()
BlendMode castor3d::BlendComponent::getColourBlendMode () const inline
References castor3d::BlendData::colourBlendMode, and castor3d::BaseDataPassComponentT< BlendData >::m_value.
getPassFlags()
C3D_API PassComponentFlag castor3d::BlendComponent::getPassFlags () const inline override virtual
Reimplemented from castor3d::PassComponent.
References eAlphaBlending, castor3d::eNone, castor3d::PassComponent::getId(), hasAlphaBlending(), and castor3d::makePassComponentFlag().
hasAlphaBlending()
bool castor3d::BlendComponent::hasAlphaBlending () const inline
References castor3d::eNoBlend, and getAlphaBlendMode().
Referenced by getPassFlags().
setAlphaBlendMode()
void castor3d::BlendComponent::setAlphaBlendMode (BlendMode value) inline
References castor3d::BlendData::alphaBlendMode, and castor3d::BaseDataPassComponentT< BlendData >::m_value.
setColourBlendMode()
void castor3d::BlendComponent::setColourBlendMode (BlendMode value) inline
References castor3d::BlendData::colourBlendMode, and castor3d::BaseDataPassComponentT< BlendData >::m_value.
Member Data Documentation
eAlphaBlending
constexpr PassFlag castor3d::BlendComponent::eAlphaBlending = PassFlag(0x01u) static constexpr
Referenced by castor3d::BlendComponent::Plugin::getComponentFlags(), and getPassFlags().
TypeName
C3D_API castor::String const castor3d::BlendComponent::TypeName static
The documentation for this struct was generated from the following file:
Castor3D/Material/Pass/Component/Base/BlendComponent.hpp