Castor3D: castor3d::HeightComponent::Plugin Class Reference
castor3d::HeightComponent::Plugin Class Reference
#include <HeightComponent.hpp>
Public Member Functions
PassComponentUPtr createComponent (Pass &pass) const override
void createParsers (castor::AttributeParsers &parsers, ChannelFillers &channelFillers) const override
Fills the given lists with this component's parsers.
bool isComponentNeeded (TextureCombine const &textures, ComponentModeFlags const &filter) const override
Tells if the component's lighting shaders are needed.
shader::PassComponentsShaderPtr createComponentsShader () const override
Creates the component's lighting shaders.
PassComponentFlag getParallaxOcclusionMappingOneFlag () const override
PassComponentFlag getParallaxOcclusionMappingRepeatFlag () const override
PassComponentFlag getComponentFlags () const override
void filterComponentFlags (ComponentModeFlags filter, PassComponentCombine &componentsFlags) const override
Removes from given component flags the ones that are useless given the provided filter.
PassComponentPlugin (PassComponentPlugin const &)=delete
C3D_API PassComponentPlugin (PassComponentPlugin &&rhs) noexcept=default
C3D_API PassComponentPlugin (PassComponentRegister const &passComponents, UpdateComponent const &pupdateComponent=nullptr, FinishComponent const &pfinishComponent=nullptr)
Public Member Functions inherited from castor3d::PassComponentPlugin
PassComponentPlugin (PassComponentPlugin const &)=delete
PassComponentPlugin & operator= (PassComponentPlugin const &)=delete
PassComponentPlugin & operator= (PassComponentPlugin &&rhs) noexcept=delete
virtual C3D_API ~PassComponentPlugin ()=default
C3D_API PassComponentPlugin (PassComponentPlugin &&rhs) noexcept=default
C3D_API PassComponentPlugin (PassComponentRegister const &passComponents, UpdateComponent const &pupdateComponent=nullptr, FinishComponent const &pfinishComponent=nullptr)
virtual C3D_API void createSections (castor::StrUInt32Map &sections) const
Fills the sections list with the ones created by this component.
virtual C3D_API bool writeTextureConfig (TextureConfiguration const &configuration, castor::String const &tabs, castor::StringStream &file) const
Writes the texture configuration for this component in a scene file.
virtual C3D_API void zeroBuffer (Pass const &pass, shader::PassMaterialShader const &materialShader, PassBuffer &buffer) const
Fills the material buffer with zero values fot the component data.
virtual C3D_API PassComponentFlag getAlphaBlendingFlag () const
virtual C3D_API PassComponentFlag getAlphaTestFlag () const
virtual C3D_API PassComponentFlag getTransmissionFlag () const
virtual C3D_API PassComponentFlag getDeferredDiffuseLightingFlag () const
virtual C3D_API shader::PassReflRefrShaderPtr createReflRefrShader () const
Creates the component's reflection and refraction shader.
virtual C3D_API shader::PassMaterialShaderPtr createMaterialShader () const
Creates the component's material shaders.
PassComponentID getId () const
PassComponentRegister const & getRegister () const
virtual C3D_API void createMapComponent (Pass &pass, castor::Vector< PassComponentUPtr > &result) const
Creates the map component.
virtual C3D_API bool isMapComponent () const
virtual C3D_API bool isReflRefrComponent () const
virtual C3D_API bool replacesMapSampling () const
virtual C3D_API bool hasTexcoordModif (PassComponentRegister const &passComponents, PipelineFlags const *flags) const
virtual C3D_API void filterTextureFlags (ComponentModeFlags filter, TextureCombine &texturesFlags) const
Removes from given texture flags the ones that are useless given the provided filter.
virtual C3D_API void fillTextureConfiguration (TextureConfiguration &configuration, uint32_t mask=0) const
Fills the texture configuration for use with this component.
TextureConfiguration getBaseTextureConfiguration () const
virtual C3D_API PassComponentTextureFlag getTextureFlags () const
virtual C3D_API castor::String getTextureFlagsName (PassComponentTextureFlag const &flags) const
virtual C3D_API PassComponentTextureFlag getColourMapFlags () const
virtual C3D_API PassComponentTextureFlag getOpacityMapFlags () const
virtual C3D_API PassComponentTextureFlag getNormalMapFlags () const
virtual C3D_API PassComponentTextureFlag getHeightMapFlags () const
virtual C3D_API PassComponentTextureFlag getOcclusionMapFlags () const
Additional Inherited Members
Public Attributes inherited from castor3d::PassComponentPlugin
FinishComponent finishComponent
Applies component's transformations before lighting happens.
UpdateComponent updateComponent
Member Function Documentation
createComponent()
PassComponentUPtr castor3d::HeightComponent::Plugin::createComponent (Pass & pass) const inline override virtual
Creates a component for given pass.
Remarks
Doesn't add the component to the pass.
Parameters
[in] pass The pass.
Implements castor3d::PassComponentPlugin.
createComponentsShader()
shader::PassComponentsShaderPtr castor3d::HeightComponent::Plugin::createComponentsShader () const inline override virtual
Creates the component's lighting shaders.
Reimplemented from castor3d::PassComponentPlugin.
createParsers()
void castor3d::HeightComponent::Plugin::createParsers (castor::AttributeParsers & parsers, ChannelFillers & channelFillers) const override virtual
Fills the given lists with this component's parsers.
Parameters
[in,out] parsers Receives the parsers.
[in,out] channelFillers Receives the texture channels and the way to fill them.
Reimplemented from castor3d::PassComponentPlugin.
filterComponentFlags()
void castor3d::HeightComponent::Plugin::filterComponentFlags (ComponentModeFlags filter, PassComponentCombine & componentsFlags) const inline override virtual
Removes from given component flags the ones that are useless given the provided filter.
Reimplemented from castor3d::PassComponentPlugin.
References castor3d::checkFlag(), castor3d::eGeometry, getComponentFlags(), and castor3d::remFlags().
getComponentFlags()
PassComponentFlag castor3d::HeightComponent::Plugin::getComponentFlags () const inline override virtual
Returns
The pass flags for this component.
Reimplemented from castor3d::PassComponentPlugin.
References castor3d::HeightComponent::eAll, castor3d::PassComponentPlugin::getId(), and castor3d::makePassComponentFlag().
Referenced by filterComponentFlags().
getParallaxOcclusionMappingOneFlag()
PassComponentFlag castor3d::HeightComponent::Plugin::getParallaxOcclusionMappingOneFlag () const inline override virtual
Returns
The flags for non repeated parallax occlusion mapping.
Reimplemented from castor3d::PassComponentPlugin.
References castor3d::HeightComponent::eParallaxOcclusionMappingOne, castor3d::PassComponentPlugin::getId(), and castor3d::makePassComponentFlag().
getParallaxOcclusionMappingRepeatFlag()
PassComponentFlag castor3d::HeightComponent::Plugin::getParallaxOcclusionMappingRepeatFlag () const inline override virtual
Returns
The flags for repeated parallax occlusion mapping.
Reimplemented from castor3d::PassComponentPlugin.
References castor3d::HeightComponent::eParallaxOcclusionMappingRepeat, castor3d::PassComponentPlugin::getId(), and castor3d::makePassComponentFlag().
isComponentNeeded()
bool castor3d::HeightComponent::Plugin::isComponentNeeded (TextureCombine const & textures, ComponentModeFlags const & filter) const override virtual
Tells if the component's lighting shaders are needed.
Parameters
[in] textures To check from texturing viewpoint.
[in,out] filter To check from render pass viewpoint.
Reimplemented from castor3d::PassComponentPlugin.
PassComponentPlugin() [1/3]
C3D_API castor3d::PassComponentPlugin::PassComponentPlugin (PassComponentPlugin && rhs) default noexcept
PassComponentPlugin() [2/3]
castor3d::PassComponentPlugin::PassComponentPlugin (PassComponentPlugin const &) delete
PassComponentPlugin() [3/3]
C3D_API castor3d::PassComponentPlugin::PassComponentPlugin (PassComponentRegister const & passComponents, UpdateComponent const & pupdateComponent = nullptr, FinishComponent const & pfinishComponent = nullptr) inline explicit
Parameters
[in] passComponents The components registrar.
[in] pupdateComponent The function to adjust the component data after textures have been parsed.
[in] pfinishComponent The function to adjust the component data after materials are blended.
The documentation for this class was generated from the following file:
Castor3D/Material/Pass/Component/Other/HeightComponent.hpp