Castor3D: castor3d::ProgressBar Class Reference
castor3d::ProgressBar Class Reference
#include <ProgressBar.hpp>
Public Member Functions
C3D_API ProgressBar (Engine &engine, ProgressCtrlRPtr progress)
C3D_API void update (ProgressCtrlRPtr progress)
C3D_API void setTitle (castor::String const &value)
C3D_API void setLabel (castor::String const &value)
C3D_API void step (castor::String const &label)
C3D_API void step ()
C3D_API void setRange (int32_t max)
C3D_API void incRange (int32_t mod)
C3D_API int32_t getIndex () const
void lock ()
void unlock ()
Constructor & Destructor Documentation
ProgressBar()
C3D_API castor3d::ProgressBar::ProgressBar (Engine & engine, ProgressCtrlRPtr progress)
Member Function Documentation
getIndex()
C3D_API int32_t castor3d::ProgressBar::getIndex () const
Referenced by castor3d::LoadingScreen::getIndex().
incRange()
C3D_API void castor3d::ProgressBar::incRange (int32_t mod)
Referenced by castor3d::LoadingScreen::incRange().
lock()
void castor3d::ProgressBar::lock () inline
setLabel()
C3D_API void castor3d::ProgressBar::setLabel (castor::String const & value)
setRange()
C3D_API void castor3d::ProgressBar::setRange (int32_t max)
Referenced by castor3d::LoadingScreen::setRange().
setTitle()
C3D_API void castor3d::ProgressBar::setTitle (castor::String const & value)
step() [1/2]
C3D_API void castor3d::ProgressBar::step ()
step() [2/2]
C3D_API void castor3d::ProgressBar::step (castor::String const & label)
Referenced by castor3d::LoadingScreen::step().
unlock()
void castor3d::ProgressBar::unlock () inline
update()
C3D_API void castor3d::ProgressBar::update (ProgressCtrlRPtr progress)
The documentation for this class was generated from the following file:
Miscellaneous/ProgressBar.hpp