Castor3D: castor3d Namespace Reference
castor3d Namespace Reference
Namespaces
namespace rq
namespace shader
Classes
struct AlphaTestComponent
struct AlphaTestData
struct AmbientComponent
struct AmbientData
class AnimableT
Animable public interface.
class AnimatedMesh
class AnimatedObject
class AnimatedObjectGroup
class AnimatedSceneNode
class AnimatedSkeleton
class AnimatedTexture
class AnimationImporter
class AnimationImporterFactory
class AnimationInstance
class AnimationInstanceT
Used to play an Animation on a specific object.
class AnimationKeyFrame
class AnimationT
Animation base class.
struct ArrayView
struct AttenuationComponent
struct AttenuationData
struct AttenuationMapComponent
class BackgroundPassBase
class BackgroundRenderer
class BackgroundTextWriter
class BackgroundVisitor
class BaseDataComponentT
Submesh component holding base submesh data.
struct BaseDataPassComponentT
Pass component holding base pass data.
class BillboardBase
class BillboardList
struct BillboardRenderNode
struct BillboardUboConfiguration
Billboards list data.
struct BillboardVertex
class BinaryChunk
class BinaryParser
Specialisable binary data chunk reader class.
class BinaryParser< Animation >
Animation binary loader.
class BinaryParser< BoneNode >
Animable binary loader.
class BinaryParser< Mesh >
MovableObject loader.
class BinaryParser< MeshAnimation >
MeshAnimation binary loader.
class BinaryParser< MeshMorphTarget >
MeshMorphTarget binary loader.
class BinaryParser< MorphComponent >
MorphComponent loader.
class BinaryParser< SceneNodeAnimation >
SceneNodeAnimation binary loader.
class BinaryParser< SceneNodeAnimationKeyFrame >
SceneNodeAnimationKeyFrame binary loader.
class BinaryParser< Skeleton >
Animable binary loader.
class BinaryParser< SkeletonAnimation >
SkeletonAnimation binary loader.
class BinaryParser< SkeletonAnimationBone >
MovingBone binary loader.
class BinaryParser< SkeletonAnimationKeyFrame >
SkeletonAnimationKeyFrame binary loader.
class BinaryParser< SkeletonAnimationNode >
MovingBone binary loader.
class BinaryParser< SkeletonAnimationObject >
SkeletonAnimationObject binary loader.
class BinaryParser< SkeletonNode >
Animable binary loader.
class BinaryParser< SkinComponent >
SkinComponent loader.
class BinaryParser< Submesh >
MovableObject loader.
class BinaryParserBase
Binary data chunk reader base class.
class BinaryWriter
Specialisable binary data chunk writer class.
class BinaryWriter< Animation >
Animation binary loader.
class BinaryWriter< BoneNode >
Animable binary loader.
class BinaryWriter< Mesh >
MovableObject loader.
class BinaryWriter< MeshAnimation >
MeshAnimation binary loader.
class BinaryWriter< MeshMorphTarget >
MeshMorphTarget binary loader.
class BinaryWriter< MorphComponent >
MorphComponent loader.
class BinaryWriter< SceneNodeAnimation >
SceneNodeAnimation binary loader.
class BinaryWriter< SceneNodeAnimationKeyFrame >
SceneNodeAnimationKeyFrame binary loader.
class BinaryWriter< Skeleton >
Animable binary loader.
class BinaryWriter< SkeletonAnimation >
SkeletonAnimation binary loader.
class BinaryWriter< SkeletonAnimationBone >
MovingBone binary loader.
class BinaryWriter< SkeletonAnimationKeyFrame >
SkeletonAnimationKeyFrame binary loader.
class BinaryWriter< SkeletonAnimationNode >
MovingBone binary loader.
class BinaryWriter< SkeletonAnimationObject >
SkeletonAnimationObject binary loader.
class BinaryWriter< SkeletonNode >
Animable binary loader.
class BinaryWriter< SkinComponent >
SkinComponent loader.
class BinaryWriter< Submesh >
MovableObject loader.
class BinaryWriterBase
Binary data chunk writer base class.
struct BlendComponent
struct BlendData
class BoneNode
class BorderPanelOverlay
struct BoundsTransformPipeline
class BrdfPrefilter
class ButtonCtrl
class ButtonStyle
class CacheViewT
class Camera
class CameraUbo
struct CameraUboConfiguration
Global matrices data.
class ChunkParser
Chunk parser.
class ChunkParser< castor::Path >
ChunkParser specialisation for castor::Path.
class ChunkParser< castor::String >
ChunkParser specialisation for castor::String.
class ChunkParserBase
struct ChunkTyper
Helper structure to find ChunkType from a type.
struct ChunkTyper< Animation >
Helper structure to find ChunkType from a type.
struct ChunkTyper< BoneNode >
Helper structure to find ChunkType from a type.
struct ChunkTyper< Mesh >
Helper structure to find ChunkType from a type.
struct ChunkTyper< MeshAnimation >
Helper structure to find ChunkType from a type.
struct ChunkTyper< MeshMorphTarget >
Helper structure to find ChunkType from a type.
struct ChunkTyper< MorphComponent >
Helper structure to find ChunkType from a type.
struct ChunkTyper< SceneNodeAnimation >
Helper structure to find ChunkType from a type.
struct ChunkTyper< SceneNodeAnimationKeyFrame >
Helper structure to find ChunkType from a type.
struct ChunkTyper< Skeleton >
Helper structure to find ChunkType from a type.
struct ChunkTyper< SkeletonAnimation >
Helper structure to find ChunkType from a type.
struct ChunkTyper< SkeletonAnimationBone >
Helper structure to find ChunkType from a type.
struct ChunkTyper< SkeletonAnimationKeyFrame >
Helper structure to find ChunkType from a type.
struct ChunkTyper< SkeletonAnimationNode >
Helper structure to find ChunkType from a type.
struct ChunkTyper< SkeletonAnimationObject >
Helper structure to find ChunkType from a type.
struct ChunkTyper< SkeletonNode >
Helper structure to find ChunkType from a type.
struct ChunkTyper< SkinComponent >
Helper structure to find ChunkType from a type.
struct ChunkTyper< Submesh >
Helper structure to find ChunkType from a type.
class ChunkWriter
Chunk data writer.
class ChunkWriter< castor::Path >
ChunkWriter specialisation for castor::Path.
class ChunkWriter< castor::String >
ChunkWriter specialisation for castor::String.
class ChunkWriterBase
struct ClearcoatComponent
struct ClearcoatData
struct ClearcoatMapComponent
struct ClearcoatNormalMapComponent
struct ClearcoatRoughnessMapComponent
class CmshAnimationImporter
class CmshImporterFile
class CmshMeshImporter
class CmshSkeletonImporter
class ColourBackground
struct ColourComponent
struct ColourMapComponent
struct CombinePassConfigT
The configuration to create a CombinePass.
class ComboBoxCtrl
class ComboBoxStyle
struct CommandsSemaphore
class ComputeDepthRange
class ComputeParticleSystem
class Cone
class Control
class ControlsManager
class ControlStyle
struct CountedNodeT
struct CpuEventCleanerT
struct CpuEventInitialiserT
class CpuFrameEvent
class CpuFunctorEvent
class CpuParticleSystem
struct CpuUpdater
class Cube
struct CubeView
class Cylinder
class DebugCallbacks
struct DebugConfig
class DebugOverlays
class DeferredRendering
class DepthPass
class DirectionalLight
struct DirectionalLightCascade
class DirectionalLightPass
class DividerPlugin
class DoubleBufferedResourceT
class DownscalePass
struct DrawConstants
Draw constants for one render node.
struct DrawParamsConfiguration
Meshlet draw parameters.
class DummyCuller
class EditCtrl
class EditStyle
struct ElementTyper
struct EmissiveComponent
struct EmissiveData
struct EmissiveMapComponent
class Engine
class EnvironmentMap
class EnvironmentMapPass
class EnvironmentPrefilter
class EquirectangularToCube
class EventHandler
class ExpandablePanelCtrl
class ExpandablePanelStyle
struct Extensions
struct ExtensionStruct
class Face
struct FaceIndices
struct FaceInfos
class Fog
class FontGlyphBuffer
class FontTexture
class ForwardRenderTechniquePass
struct FractalMappingComponent
class FrameCtrl
class FrameListener
class FrameStyle
class Frustum
class FrustumCuller
class GaussianBlur
class GBufferBase
class GBufferT
class GeneratorPlugin
class GenericPlugin
class Geometry
struct GeometryBuffers
class GeometryInjectionPass
struct GlossinessMapComponent
class GpuBufferBase
struct GpuBufferBuddyAllocatorTraits
struct GpuBufferLinearAllocator
struct GpuBufferOffsetT
An offset and range of a GpuBuffer.
struct GpuBufferPackedAllocator
class GpuBufferPool
class GpuBufferT
A GPU buffer pool, that uses an allocator to allocate sub-buffers.
struct GpuEventCleanerT
struct GpuEventInitialiserT
class GpuFrameEvent
class GpuFunctorEvent
class GpuInformations
class GpuLinearAllocatorT
class GpuObjectTracker
struct GpuUpdater
struct GroupAnimation
struct GuiParserContext
class HandlerEvent
class HdrConfig
class HdrConfigUbo
struct HeightComponent
struct HeightMapComponent
class IblTextures
class Icosahedron
class ImageBackground
class ImporterFile
class ImporterFileFactory
class ImporterPlugin
class IndexMapping
class IndirectLightingPass
class InstantiationComponent
struct InstantiationData
struct InterleavedVertex
struct IntermediateView
class Interpolator
Template class which handles the interpolations, would it be quaternion, point, real, ... interpolations.
class InterpolatorT
Template class which handles the interpolations, would it be quaternion, point, real, ... interpolations.
class InterpolatorT< castor::Quaternion, InterpolatorType::eLinear >
Handles the Quaternion linear interpolations.
class InterpolatorT< DataT, InterpolatorType::eLinear >
Partial specialisation of InterpolatorT, for InterpolatorType::eLinear.
class InterpolatorT< DataT, InterpolatorType::eNearest >
Partial specialisation of InterpolatorT, for InterpolatorType::eNearest.
struct IridescenceComponent
struct IridescenceData
struct IridescenceMapComponent
struct IridescenceThicknessMapComponent
struct IsRenderPassEnabled
class KeyboardEvent
struct KeyboardState
Keyboard state.
class LayeredLightPropagationVolumesBase
class LayeredLightPropagationVolumesT
Lighting propagation volumes generation pass.
class LayeredLpvGridConfigUbo
struct LayeredLpvGridConfigUboConfiguration
Light propagation data.
class Layout
class LayoutBox
class LayoutControl
struct LayoutItemFlags
class Light
class LightBuffer
class LightCategory
struct LightDescriptors
class LightFactory
class LightImporter
struct LightingModelComponent
class LightingModelFactory
class LightingPass
class LightInjectionPass
class LightPass
class LightPassResult
class LightPipeline
struct LightPipelineConfig
class LightPropagationPass
class LightPropagationVolumesBase
class LightPropagationVolumesT
Lighting propagation volumes generation pass.
struct LightRenderPass
struct LightsPipeline
class LightVolumePassResult
struct LimitedType
class Line
class LineariseDepthPass
struct LineIndices
class LinesMapping
class ListBoxCtrl
class ListBoxStyle
class LoadingScreen
class log
struct LpvConfig
class LpvGridConfigUbo
struct LpvGridConfigUboConfiguration
Light propagation data.
class LpvLightConfigUbo
struct LpvLightConfigUboConfiguration
Light propagation data.
class Material
class MaterialImporter
struct MemChunk
A memory range, in bytes.
class Mesh
class MeshAnimation
class MeshAnimationInstance
class MeshAnimationInstanceSubmesh
class MeshAnimationSubmesh
class MeshFactory
class MeshGenerator
class MeshImporter
struct MeshInfoConfiguration
Meshlet draw informations.
struct Meshlet
Data for one meshlet.
class MeshletBoundsTransformingPass
class MeshletBoundsTransformPass
class MeshletComponent
struct MeshletCullData
Cull data for one meshlet.
struct MeshletDrawConstants
Draw constants for one meshlet.
class MeshLightPass
class MeshMorphTarget
class MeshPreparer
struct MetalnessComponent
struct MetalnessMapComponent
struct MipView
struct ModelBufferConfiguration
Model index data.
class MorphComponent
struct MorphingWeightsConfiguration
Morphing data.
class MouseEvent
class MouseEventHandler
struct MouseState
Mouse state.
struct MovableAttacherT
struct MovableDetacherT
struct MovableMergerT
class MovableObject
struct NodeTransform
class NonClientEventHandler
Description of an event handler, class that can receive event.
struct NonTexturedCube
A cube without UV.
struct NonTexturedQuad
A quad without UV.
struct NormalComponent
struct NormalMapComponent
struct ObjectBufferOffset
class ObjectBufferPool
class ObjectCacheBaseT
class ObjectCacheT
class ObjectCacheT< BillboardList, castor::String, BillboardCacheTraits >
BillboardList cache.
class ObjectCacheT< Geometry, castor::String, GeometryCacheTraits >
Geometry cache.
class ObjectCacheT< Light, castor::String, LightCacheTraits >
Light cache.
class ObjectCacheT< SceneNode, castor::String, SceneNodeCacheTraits >
SceneNode cache.
struct ObjectCacheTraitsBaseT
struct ObjectCacheTraitsT
Helper structure to specialise a scene objects cache behaviour.
struct ObjectCacheTraitsT< BillboardList, castor::String >
struct ObjectCacheTraitsT< Camera, castor::String >
struct ObjectCacheTraitsT< Geometry, castor::String >
struct ObjectCacheTraitsT< Light, castor::String >
struct ObjectCacheTraitsT< ParticleSystem, castor::String >
struct ObjectCacheTraitsT< SceneNode, castor::String >
struct ObjectIdsConfiguration
Objects ID data.
struct ObjectTransform
struct OcclusionMapComponent
struct OldInterleavedVertexT
struct OpacityComponent
struct OpacityData
struct OpacityMapComponent
class OpaquePass
class OpaquePassResult
class OpaqueRendering
class OpaqueResolvePass
class Overlay
class OverlayCategory
struct OverlayDrawData
struct OverlayDrawNode
struct OverlayDrawPipeline
class OverlayFactory
struct OverlayLines
Contains the lines forming the overlay.
class OverlayPass
struct OverlayPipelineData
class OverlayPreparer
class OverlayRenderer
struct OverlaysCounts
struct OverlayTextBuffer
struct OverlayTextBufferIndex
struct OverlayTextBufferPool
struct OverlayUboConfiguration
Overlay data.
struct OverlayVertexBufferPoolT
Pool for the overlays vertices.
class OverlayVisitor
struct OverlayWords
Contains the words forming the overlay.
class PanelCtrl
class PanelOverlay
class PanelStyle
class ParametersT
Configuration parameters.
class Particle
class ParticleDeclaration
struct ParticleElementDeclaration
class ParticleEmitter
class ParticlePlugin
class ParticleSystem
class ParticleSystemImpl
class ParticleUpdater
class Pass
class PassBuffer
struct PassComponent
struct PassComponentCombine
class PassComponentPlugin
class PassComponentRegister
class PassFactory
struct PassFactoryEntry
struct PassHeaderComponent
struct PassMapComponent
class PassMapComponentPlugin
struct PassMasks
class PassMasksComponent
struct PassRegisterInfo
struct PassTextureConfig
class PassVisitor
class PassVisitorBase
class Pattern
Pattern handler class.
class PbrPass
class PhongPass
struct PickableComponent
class Picking
class PickingPass
struct PipelineBaseHash
struct PipelineFlags
Pipeline flags.
struct PipelineHiHashDetails
struct PipelineLoHashDetails
class PipelineVisitor
class PipelineVisitorBase
class Plane
class Plugin
class PluginException
class PointLight
class PoolUniformBuffer
class PostEffect
struct PostEffectSurface
class PostFxPlugin
class PrepassRendering
class PrepassResult
class ProgressBar
class ProgressCtrl
class ProgressStyle
class Projection
struct PtrCacheTraitsBaseT
struct PtrCacheTraitsT
struct PtrCacheTraitsT< AnimatedObjectGroup, castor::String >
struct PtrCacheTraitsT< FrameListener, castor::String >
struct PtrCacheTraitsT< Material, castor::String >
struct PtrCacheTraitsT< Overlay, castor::String >
struct PtrCacheTraitsT< Plugin, castor::String >
struct PtrCacheTraitsT< Sampler, castor::String >
struct PtrCacheTraitsT< Scene, castor::String >
struct PtrCacheTraitsT< Skeleton, castor::String >
struct QueueData
struct QueueDataWrapper
struct QueueRenderNodes
struct QueuesData
class RadianceComputer
class Ray
struct ReflectionComponent
struct RefractionComponent
class RenderCube
struct RenderDevice
class RenderedObject
struct Renderer
class RenderGridBuilderT
Used to create a RenderGrid variable.
struct RenderInfo
class RenderLoop
class RenderLoopAsync
class RenderLoopSync
class RenderNodesPass
struct RenderNodesPassDesc
struct RenderNodesT
The render nodes for a specific scene.
struct RenderNodeTraitsT
struct RenderNodeTraitsT< BillboardRenderNode >
struct RenderPassRegisterInfo
class RenderPipeline
class RenderQuad
class RenderQuadBuilder
class RenderQuadBuilderT
Used to create a RenderQuad variable.
class RenderQueue
class RenderSystem
class RenderTarget
class RenderTargetCache
class RenderTechnique
class RenderTechniqueNodesPass
class RenderTechniquePass
struct RenderTechniquePassDesc
class RenderTechniqueVisitor
class RenderWindow
struct RenderWindowDesc
struct ResourceCacheTraitsT
struct ResourceCacheTraitsT< Mesh, castor::String >
struct RoughnessComponent
struct RoughnessMapComponent
struct RsmConfig
class RsmConfigUbo
struct RsmUboConfiguration
Reflective Shadow Maps based GI UBO configuration.
class RunnableLightingPass
class Sampler
class Scene
class SceneBackground
class SceneCuller
class SceneFileContext
class SceneFileParser
class SceneImporter
class SceneNode
class SceneNodeAnimation
class SceneNodeAnimationInstance
class SceneNodeAnimationKeyFrame
struct SceneNodeAttacherT
struct SceneNodeDetacherT
class SceneNodeImporter
struct SceneNodeMergerT
struct SceneRenderNodes
class SceneUbo
struct SceneUboConfiguration
Scene data.
class ScrollableCtrl
class ScrollableStyle
class ScrollBarCtrl
class ScrollBarStyle
class ShaderBuffer
struct ShaderBufferTypes
struct ShaderModule
A non compiled shader module, with its source.
class ShaderProgram
class ShaderProgramCache
struct ShadowConfig
class ShadowMap
class ShadowMapDirectional
struct ShadowMapLightIds
class ShadowMapPass
class ShadowMapPassDirectional
class ShadowMapPassPoint
class ShadowMapPassSpot
class ShadowMapPoint
class ShadowMapResult
class ShadowMapSpot
class ShadowMapUbo
struct ShadowMapUboConfiguration
Shadow map data.
struct SheenComponent
struct SheenData
struct SheenMapComponent
struct SheenRoughnessMapComponent
class Skeleton
class SkeletonAnimation
class SkeletonAnimationBone
class SkeletonAnimationInstance
class SkeletonAnimationInstanceBone
class SkeletonAnimationInstanceKeyFrame
class SkeletonAnimationInstanceNode
class SkeletonAnimationInstanceObject
class SkeletonAnimationKeyFrame
class SkeletonAnimationNode
class SkeletonAnimationObject
class SkeletonImporter
class SkeletonNode
class SkinComponent
struct SkinningTransformsConfiguration
Skinning data.
class SkinningUbo
class SkyboxBackground
struct SliceView
class SliderCtrl
class SliderStyle
class Spacer
struct SpecificsBuffer
struct SpecularComponent
struct SpecularData
struct SpecularFactorMapComponent
struct SpecularMapComponent
class Sphere
class SphereSection
struct SpirVShader
A SPIR-V shader module, with SPIR-V binary and debug text source.
class SpotLight
class SsaoBlurPass
struct SsaoConfig
class SsaoConfigUbo
class SsaoPass
class SsaoRawAOPass
class SssProfileBuffer
class StagingData
class StaticCtrl
class StaticStyle
class StencilPipeline
class StructuredShaderBuffer
Wrapper class to select between SSBO or TBO.
class StylesHolder
class Submesh
struct SubmeshAnimationBuffer
class SubmeshComponent
struct SubmeshComponentAdder
struct SubmeshRenderNode
class SubmeshUtils
Submesh utility functions.
struct SubmeshVertex
class SubsurfaceScattering
struct SubsurfaceScatteringComponent
class SubsurfaceScatteringPass
struct TechniqueQueues
struct TextChar
A character, along with its size and relative position.
struct TextLine
A text chars container, along with its size and position.
class TextOverlay
struct Texture
class Texture3DTo2D
struct Texture3DTo2DData
class TextureAnimation
class TextureAnimationBuffer
struct TextureAnimationData
class TextureAnimationInstance
class TextureAnimationKeyFrame
struct TextureCombine
struct TextureConfiguration
class TextureConfigurationBuffer
struct TextureCountComponent
struct TexturedCube
A cube with UV.
struct TexturedQuad
A quad with UV.
struct TextureFactors
Factors applied when displaying a debug texture.
struct TextureFlagConfiguration
class TextureLayout
struct TexturesComponent
class TextureSource
class TextureSourceInfo
struct TextureSourceInfoHasher
struct TextureTransform
class TextureUnit
class TextureUnitCache
struct TextureUnitData
class TextureView
struct TextWord
A text chars container, along with its size and position.
class Theme
struct ThicknessComponent
class ToneMapping
class ToneMappingPlugin
class ToneMappingVisitor
class Torus
struct TransformPipeline
struct TransmissionComponent
struct TransmissionMapComponent
struct TransmittanceMapComponent
class TransparentPass
class TransparentPassResult
class TransparentRendering
class TriFaceMapping
struct TwoSidedComponent
class UniformBufferBase
struct UniformBufferOffsetT
A UniformBuffer and an offset from the GpuBuffer.
class UniformBufferPool
class UniformBufferT
A uniform typed buffer, than can contain multiple sub-buffers.
struct UntileMappingComponent
class UserInputEvent
Description of a user input event.
class UserInputListener
class Version
class VersionException
struct VertexBoneData
class VertexBufferPool
class VertexTransforming
class VertexTransformingPass
class VertexTransformPass
class Viewport
class VisibilityPass
class VisibilityReorderPass
class VisibilityResolvePass
struct VkStructTraits
struct VkStructTraits< VkApplicationInfo >
struct VkStructTraits< VkBindBufferMemoryDeviceGroupInfo >
struct VkStructTraits< VkBindBufferMemoryInfo >
struct VkStructTraits< VkBindImageMemoryDeviceGroupInfo >
struct VkStructTraits< VkBindImageMemoryInfo >
struct VkStructTraits< VkBindSparseInfo >
struct VkStructTraits< VkBufferCreateInfo >
struct VkStructTraits< VkBufferMemoryBarrier >
struct VkStructTraits< VkBufferViewCreateInfo >
struct VkStructTraits< VkCommandBufferAllocateInfo >
struct VkStructTraits< VkCommandBufferBeginInfo >
struct VkStructTraits< VkCommandBufferInheritanceInfo >
struct VkStructTraits< VkCommandPoolCreateInfo >
struct VkStructTraits< VkComputePipelineCreateInfo >
struct VkStructTraits< VkCopyDescriptorSet >
struct VkStructTraits< VkDescriptorPoolCreateInfo >
struct VkStructTraits< VkDescriptorSetAllocateInfo >
struct VkStructTraits< VkDescriptorSetLayoutCreateInfo >
struct VkStructTraits< VkDeviceCreateInfo >
struct VkStructTraits< VkDeviceGroupBindSparseInfo >
struct VkStructTraits< VkDeviceGroupCommandBufferBeginInfo >
struct VkStructTraits< VkDeviceGroupDeviceCreateInfo >
struct VkStructTraits< VkDeviceGroupRenderPassBeginInfo >
struct VkStructTraits< VkDeviceGroupSubmitInfo >
struct VkStructTraits< VkDeviceQueueCreateInfo >
struct VkStructTraits< VkEventCreateInfo >
struct VkStructTraits< VkFenceCreateInfo >
struct VkStructTraits< VkFramebufferCreateInfo >
struct VkStructTraits< VkGraphicsPipelineCreateInfo >
struct VkStructTraits< VkImageCreateInfo >
struct VkStructTraits< VkImageMemoryBarrier >
struct VkStructTraits< VkImageViewCreateInfo >
struct VkStructTraits< VkInstanceCreateInfo >
struct VkStructTraits< VkMappedMemoryRange >
struct VkStructTraits< VkMemoryAllocateFlagsInfo >
struct VkStructTraits< VkMemoryAllocateInfo >
struct VkStructTraits< VkMemoryBarrier >
struct VkStructTraits< VkMemoryDedicatedAllocateInfo >
struct VkStructTraits< VkMemoryDedicatedRequirements >
struct VkStructTraits< VkPhysicalDevice16BitStorageFeatures >
struct VkStructTraits< VkPhysicalDeviceGroupProperties >
struct VkStructTraits< VkPhysicalDeviceSubgroupProperties >
struct VkStructTraits< VkPipelineCacheCreateInfo >
struct VkStructTraits< VkPipelineColorBlendStateCreateInfo >
struct VkStructTraits< VkPipelineDepthStencilStateCreateInfo >
struct VkStructTraits< VkPipelineDynamicStateCreateInfo >
struct VkStructTraits< VkPipelineInputAssemblyStateCreateInfo >
struct VkStructTraits< VkPipelineLayoutCreateInfo >
struct VkStructTraits< VkPipelineMultisampleStateCreateInfo >
struct VkStructTraits< VkPipelineRasterizationStateCreateInfo >
struct VkStructTraits< VkPipelineShaderStageCreateInfo >
struct VkStructTraits< VkPipelineTessellationStateCreateInfo >
struct VkStructTraits< VkPipelineVertexInputStateCreateInfo >
struct VkStructTraits< VkPipelineViewportStateCreateInfo >
struct VkStructTraits< VkQueryPoolCreateInfo >
struct VkStructTraits< VkRenderPassBeginInfo >
struct VkStructTraits< VkRenderPassCreateInfo >
struct VkStructTraits< VkSamplerCreateInfo >
struct VkStructTraits< VkSemaphoreCreateInfo >
struct VkStructTraits< VkShaderModuleCreateInfo >
struct VkStructTraits< VkSubmitInfo >
struct VkStructTraits< VkWriteDescriptorSet >
struct VkStructure
struct Voxel
class VoxelBufferToTexture
class VoxelizePass
class Voxelizer
class VoxelizerUbo
struct VoxelizerUboConfiguration
class VoxelSceneData
class VoxelSecondaryBounce
class WeightedBlendRendering
Concepts
concept ControlFlagTypeT
Typedefs
using BillboardCacheTraits = ObjectCacheTraitsT< BillboardList, castor::String >
template<typename CacheT >
using CacheViewTraitsT = typename CacheT::ElementCacheTraitsT
using ControlID = size_t
using ControlFlagType = uint64_t
using ControlFlags = castor::FlagCombination< ControlFlag >
using ComboBoxFlags = castor::FlagCombination< ComboBoxFlag >
using EditFlags = castor::FlagCombination< EditFlag >
using SliderFlags = castor::FlagCombination< SliderFlag >
using StaticFlags = castor::FlagCombination< StaticFlag >
using ScrollBarFlags = castor::FlagCombination< ScrollBarFlag >
using ProgressFlags = castor::FlagCombination< ProgressFlag >
using OnControlEventFunction = std::function< void() >
using OnControlEvent = castor::SignalT< OnControlEventFunction >
using OnControlEventConnection = OnControlEvent::connection
using OnButtonEventFunction = std::function< void() >
using OnButtonEvent = castor::SignalT< OnButtonEventFunction >
using OnButtonEventConnection = OnButtonEvent::connection
using OnComboEventFunction = std::function< void(int32_t) >
using OnComboEvent = castor::SignalT< OnComboEventFunction >
using OnComboEventConnection = OnComboEvent::connection
using OnEditEventFunction = std::function< void(castor::U32String const &) >
using OnEditEvent = castor::SignalT< OnEditEventFunction >
using OnEditEventConnection = OnEditEvent::connection
using OnExpandablePanelEventFunction = std::function< void() >
using OnExpandablePanelEvent = castor::SignalT< OnExpandablePanelEventFunction >
using OnExpandablePanelEventConnection = OnExpandablePanelEvent::connection
using OnListEventFunction = std::function< void(int32_t) >
using OnListEvent = castor::SignalT< OnListEventFunction >
using OnListEventConnection = OnListEvent::connection
using OnSliderEventFunction = std::function< void(int32_t) >
using OnSliderEvent = castor::SignalT< OnSliderEventFunction >
using OnSliderEventConnection = OnSliderEvent::connection
using OnScrollBarEventFunction = std::function< void(int32_t) >
using OnScrollBarEvent = castor::SignalT< OnScrollBarEventFunction >
using OnScrollBarEventConnection = OnScrollBarEvent::connection
using OnControlChangedFunction = std::function< void(Control const &) >
using OnControlChanged = castor::SignalT< OnControlChangedFunction >
using OnControlChangedConnection = OnControlChanged::connection
using ControlArray = std::vector< ControlRPtr >
using TexturesData = std::array< uint32_t, MaxPassTextures >
using TextureSourceMap = std::unordered_map< TextureSourceInfo, PassTextureConfig, TextureSourceInfoHasher >
using TextureSourceMapVT = TextureSourceMap::value_type
using TextureSourceSet = std::unordered_set< TextureSourceInfo, TextureSourceInfoHasher >
using DebugCallbacksPtr = std::unique_ptr< DebugCallbacks >
using LineArray = std::vector< Line >
using DoubleBufferedTextureLayout = DoubleBufferedResourceT< TextureLayout, castor::UniquePtr >
using LightRenderPassArray = std::vector< LightRenderPass >
using LightsPipelinePtr = std::unique_ptr< LightsPipeline >
using StencilPipelinePtr = std::unique_ptr< StencilPipeline >
template<typename VertexT , uint32_t CountT>
using OverlayVertexBufferPoolPtrT = std::unique_ptr< OverlayVertexBufferPoolT< VertexT, CountT > >
using OverlayTextBufferPtr = std::unique_ptr< OverlayTextBuffer >
using TextureViewCRef = std::reference_wrapper< TextureView const >
using TextureViewCRefArray = std::vector< TextureViewCRef >
using FeatureArray = std::vector< ExtensionStruct >
using PropertyArray = std::vector< ExtensionStruct >
using QueueFamilyFlags = castor::FlagCombination< QueueFamilyFlag >
using QueueDataPtr = std::unique_ptr< QueueData >
using QueueFamilies = std::vector< QueuesData >
using SkeletonAnimationInstanceKeyFrameArray = std::vector< SkeletonAnimationInstanceKeyFrame >
Traits
template<typename NodeT >
using NodeObjectT = typename RenderNodeTraitsT< NodeT >::Object
using PipelineBufferArray = std::vector< PipelineBuffer >
Non instanced
template<typename NodeT >
using NodeArrayT = std::vector< CountedNodeT< NodeT > >
template<typename NodeT >
using NodePtrByBufferMapT = std::unordered_map< ashes::BufferBase const *, NodeArrayT< NodeT > >
template<typename NodeT >
using NodePtrByPipelineMapT = std::unordered_map< RenderPipeline *, NodePtrByBufferMapT< NodeT > >
Instanced
template<typename NodeT >
using ObjectNodesPtrMapT = std::unordered_map< NodeObjectT< NodeT > *, NodeArrayT< NodeT > >
template<typename NodeT >
using ObjectNodesPtrByPassT = std::unordered_map< PassRPtr, ObjectNodesPtrMapT< NodeT > >
template<typename NodeT >
using ObjectNodesPtrByBufferMapT = std::unordered_map< ashes::BufferBase const *, ObjectNodesPtrByPassT< NodeT > >
template<typename NodeT >
using ObjectNodesPtrByPipelineMapT = std::unordered_map< RenderPipeline *, ObjectNodesPtrByBufferMapT< NodeT > >
Enumerations
enum class ChunkType : uint64_t {
eUnknown = makeChunkID(' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ') , eCmshFile = makeChunkID('C', 'M', 'S', 'H', 'F', 'I', 'L', 'E') , eCmshHeader = makeChunkID('C', 'M', 'S', 'H', 'H', 'D', 'E', 'R') , eCmshVersion = makeChunkID('C', 'M', 'S', 'H', 'V', 'R', 'S', 'N') ,
eName = makeChunkID('N', 'A', 'M', 'E', ' ', ' ', ' ', ' ') , eMesh = makeChunkID('M', 'E', 'S', 'H', ' ', ' ', ' ', ' ') , eSkeleton = makeChunkID('S', 'K', 'E', 'L', 'E', 'T', 'O', 'N') , eSkeletonGlobalInverse = makeChunkID('S', 'K', 'E', 'L', 'G', 'I', 'M', 'X') ,
eSkeletonBone = makeChunkID('S', 'K', 'E', 'L', 'B', 'O', 'N', 'E') , eSkeletonNode = makeChunkID('S', 'K', 'E', 'L', 'N', 'O', 'D', 'E') , eBoneParentName = makeChunkID('B', 'O', 'N', 'E', 'P', 'A', 'R', 'T') , eBoneOffsetMatrix = makeChunkID('B', 'O', 'N', 'E', 'O', 'M', 'T', 'X') ,
eSubmesh = makeChunkID('S', 'U', 'B', 'M', 'E', 'S', 'H', ' ') , eSubmeshTopology = makeChunkID('S', 'M', 'S', 'H', 'T', 'O', 'P', 'O') , eSubmeshVertexCount = makeChunkID('S', 'M', 'S', 'H', 'V', 'X', 'C', 'T') , eSubmeshBoneCount = makeChunkID('S', 'M', 'S', 'H', 'B', 'N', 'C', 'T') ,
eSubmeshBones = makeChunkID('S', 'M', 'S', 'H', 'B', 'O', 'N', 'E') , eSubmeshMatrixCount = makeChunkID('S', 'M', 'S', 'H', 'M', 'X', 'C', 'T') , eSubmeshMatrices = makeChunkID('S', 'M', 'S', 'H', 'M', 'T', 'R', 'X') , eAnimable = makeChunkID('A', 'N', 'I', 'M', 'A', 'B', 'L', 'E') ,
eAnimation = makeChunkID('A', 'N', 'M', 'A', 'T', 'I', 'O', 'N') , eAnimLength = makeChunkID('A', 'N', 'M', 'L', 'E', 'N', 'G', 'T') , eSkeletonAnimation = makeChunkID('S', 'K', 'E', 'L', 'A', 'N', 'I', 'M') , eMeshAnimation = makeChunkID('M', 'E', 'S', 'H', 'A', 'N', 'I', 'M') ,
eAnimInterpolator = makeChunkID('A', 'N', 'M', 'I', 'N', 'T', 'E', 'R') , eAnimationObject = makeChunkID('A', 'N', 'S', 'K', 'O', 'B', 'J', 'T') , eSkeletonAnimationNode = makeChunkID('A', 'N', 'S', 'K', 'N', 'O', 'D', 'E') , eSkeletonAnimationBone = makeChunkID('A', 'N', 'S', 'K', 'B', 'O', 'N', 'E') ,
eMovingTransform = makeChunkID('M', 'V', 'N', 'G', 'T', 'S', 'F', 'M') , eBonesComponent = makeChunkID('B', 'O', 'N', 'E', 'C', 'O', 'M', 'P') , eKeyframeCount = makeChunkID('K', 'F', 'R', 'M', 'C', 'O', 'N', 'T') , eKeyframes = makeChunkID('K', 'E', 'Y', 'F', 'R', 'M', 'E', 'S') ,
eSkeletonAnimationKeyFrame = makeChunkID('S', 'K', 'A', 'N', 'K', 'F', 'R', 'M') , eSkeletonAnimationKeyFrameTime = makeChunkID('S', 'K', 'A', 'N', 'K', 'F', 'T', 'M') , eSkeletonAnimationKeyFrameObjectType = makeChunkID('S', 'K', 'A', 'N', 'K', 'F', 'O', 'Y') , eSkeletonAnimationKeyFrameObjectName = makeChunkID('S', 'K', 'A', 'N', 'K', 'F', 'O', 'N') ,
eSubmeshFaceCount = makeChunkID('S', 'M', 'S', 'H', 'F', 'C', 'C', 'T') , eSubmeshIndexComponentCount = makeChunkID('S', 'M', 'F', 'C', 'C', 'P', 'C', 'T') , eSubmeshIndexCount = makeChunkID('S', 'M', 'S', 'H', 'I', 'C', 'C', 'T') , eSubmeshFaces = makeChunkID('S', 'M', 'S', 'H', 'F', 'A', 'C', 'E') ,
eSubmeshIndices = makeChunkID('S', 'M', 'S', 'H', 'I', 'D', 'C', 'S') , eSceneNodeAnimation = makeChunkID('S', 'C', 'N', 'D', 'A', 'N', 'I', 'M') , eSceneNodeAnimationKeyFrame = makeChunkID('S', 'N', 'A', 'N', 'K', 'F', 'R', 'M') , eSceneNodeAnimationKeyFrameTime = makeChunkID('S', 'N', 'A', 'N', 'K', 'F', 'T', 'M') ,
eSceneNodeAnimationKeyFrameTranslate = makeChunkID('S', 'N', 'A', 'N', 'K', 'F', 'T', 'R') , eSceneNodeAnimationKeyFrameRotate = makeChunkID('S', 'N', 'A', 'N', 'K', 'F', 'R', 'T') , eSceneNodeAnimationKeyFrameScale = makeChunkID('S', 'N', 'A', 'N', 'K', 'F', 'S', 'L') , eBoneId = makeChunkID('B', 'O', 'N', 'E', 'I', 'D', ' ', ' ') ,
eSubmeshVertex = makeChunkID('S', 'M', 'S', 'H', 'V', 'R', 'T', 'X') , eSubmeshPositions = makeChunkID('S', 'M', 'S', 'H', 'P', 'O', 'S', 'I') , eSubmeshNormals = makeChunkID('S', 'M', 'S', 'H', 'N', 'O', 'R', 'M') , eSubmeshTangents = makeChunkID('S', 'M', 'S', 'H', 'T', 'A', 'N', 'G') ,
eSubmeshTexcoords0 = makeChunkID('S', 'M', 'S', 'H', 'T', 'E', 'X', 'C') , eSubmeshTexcoords1 = makeChunkID('S', 'M', 'S', 'H', 'T', 'E', 'X', '1') , eSubmeshTexcoords2 = makeChunkID('S', 'M', 'S', 'H', 'T', 'E', 'X', '2') , eSubmeshTexcoords3 = makeChunkID('S', 'M', 'S', 'H', 'T', 'E', 'X', '3') ,
eSubmeshColours = makeChunkID('S', 'M', 'S', 'H', 'C', 'O', 'L', 'R') , eMeshAnimationKeyFrame = makeChunkID('M', 'S', 'A', 'N', 'K', 'F', 'R', 'M') , eMeshAnimationKeyFrameTime = makeChunkID('M', 'S', 'A', 'N', 'K', 'F', 'T', 'M') , eMeshAnimationKeyFrameBufferData = makeChunkID('M', 'H', 'A', 'N', 'K', 'F', 'D', 'T') ,
eMeshAnimationKeyFrameSubmeshID = makeChunkID('M', 'S', 'A', 'N', 'K', 'F', 'I', 'D') , eMeshAnimationKeyFrameBufferSize = makeChunkID('M', 'H', 'A', 'N', 'K', 'F', 'S', 'Z') , eMorphComponent = makeChunkID('M', 'O', 'R', 'P', 'C', 'O', 'M', 'P') , eMorphTargetBufferSize = makeChunkID('S', 'M', 'S', 'H', 'M', 'T', 'S', 'Z') ,
eMorphTargetPositions = makeChunkID('S', 'M', 'S', 'H', 'M', 'T', 'P', 'O') , eMorphTargetNormals = makeChunkID('S', 'M', 'S', 'H', 'M', 'T', 'N', 'M') , eMorphTargetTangents = makeChunkID('S', 'M', 'S', 'H', 'M', 'T', 'T', 'A') , eMorphTargetTexcoords0 = makeChunkID('S', 'M', 'S', 'H', 'M', 'T', 'T', 'X') ,
eMorphTargetTexcoords1 = makeChunkID('S', 'M', 'S', 'H', 'M', 'T', 'T', '1') , eMorphTargetTexcoords2 = makeChunkID('S', 'M', 'S', 'H', 'M', 'T', 'T', '2') , eMorphTargetTexcoords3 = makeChunkID('S', 'M', 'S', 'H', 'M', 'T', 'T', '3') , eMorphTargetColours = makeChunkID('S', 'M', 'S', 'H', 'K', 'F', 'C', 'L') ,
eMeshMorphTarget = makeChunkID('M', 'H', 'A', 'N', 'M', 'P', 'T', 'G') , eMeshMorphTargetTime = makeChunkID('S', 'M', 'S', 'H', 'M', 'T', 'T', 'M') , eMeshMorphTargetSubmeshID = makeChunkID('M', 'H', 'A', 'N', 'M', 'T', 'I', 'D') , eMeshMorphTargetWeights = makeChunkID('M', 'H', 'A', 'N', 'M', 'T', 'W', 'T') ,
eSkeletonAnimationKeyFrameObjectTransform = makeChunkID('S', 'K', 'A', 'N', 'K', 'F', 'O', 'T') , eSkeletonAnimationKeyFrameObjectTranslate = makeChunkID('S', 'K', 'A', 'N', 'K', 'F', 'O', 'R') , eSkeletonAnimationKeyFrameObjectRotate = makeChunkID('S', 'K', 'A', 'N', 'K', 'F', 'O', 'O') , eSkeletonAnimationKeyFrameObjectScale = makeChunkID('S', 'K', 'A', 'N', 'K', 'F', 'O', 'S')
}
Binary data chunk types enumeration.
enum class GUISection : uint32_t {
eGUI = CU_MakeSectionName('C', 'G', 'U', 'I') , eTheme = CU_MakeSectionName('C', 'G', 'T', 'H') , eButtonStyle = CU_MakeSectionName('C', 'T', 'B', 'T') , eEditStyle = CU_MakeSectionName('C', 'T', 'E', 'D') ,
eComboStyle = CU_MakeSectionName('C', 'T', 'C', 'X') , eListStyle = CU_MakeSectionName('C', 'T', 'L', 'B') , eSliderStyle = CU_MakeSectionName('C', 'T', 'S', 'L') , eStaticStyle = CU_MakeSectionName('C', 'T', 'S', 'T') ,
ePanelStyle = CU_MakeSectionName('P', 'N', 'S', 'T') , eProgressStyle = CU_MakeSectionName('P', 'G', 'S', 'T') , eExpandablePanelStyle = CU_MakeSectionName('X', 'P', 'S', 'T') , eFrameStyle = CU_MakeSectionName('F', 'M', 'S', 'T') ,
eScrollBarStyle = CU_MakeSectionName('S', 'C', 'S', 'T') , eButton = CU_MakeSectionName('B', 'U', 'T', 'N') , eStatic = CU_MakeSectionName('S', 'T', 'T', 'C') , eSlider = CU_MakeSectionName('S', 'L', 'D', 'R') ,
eComboBox = CU_MakeSectionName('C', 'M', 'B', 'O') , eListBox = CU_MakeSectionName('L', 'S', 'B', 'X') , eEdit = CU_MakeSectionName('E', 'D', 'I', 'T') , ePanel = CU_MakeSectionName('P', 'A', 'N', 'L') ,
eProgress = CU_MakeSectionName('P', 'R', 'G', 'S') , eExpandablePanel = CU_MakeSectionName('X', 'P', 'N', 'L') , eExpandablePanelHeader = CU_MakeSectionName('X', 'P', 'H', 'D') , eExpandablePanelExpand = CU_MakeSectionName('X', 'P', 'X', 'p') ,
eExpandablePanelContent = CU_MakeSectionName('X', 'P', 'C', 'T') , eFrame = CU_MakeSectionName('F', 'R', 'A', 'M') , eFrameContent = CU_MakeSectionName('F', 'M', 'C', 'T') , eBoxLayout = CU_MakeSectionName('B', 'X', 'L', 'T') ,
eLayoutCtrl = CU_MakeSectionName('L', 'T', 'C', 'T')
}
Scene file sections Enum.
enum class ControlType : uint8_t {
eNone , ePanel , eStatic , eEdit ,
eSlider , eComboBox , eListBox , eButton ,
eExpandablePanel , eFrame , eScrollBar , eProgress
}
Enumeration of supported control types.
enum class ControlEvent : uint8_t { eDrag , eDrop , eCount }
Enumeration of supported control events.
enum class ComboBoxEvent : uint8_t { eSelected , eCount }
Enumeration of supported combobox events.
enum class EditEvent : uint8_t { eUpdated , eReturn , eCount }
Enumeration of supported edit events.
enum class ExpandablePanelEvent : uint8_t { eExpand , eRetract , eCount }
Enumeration of supported expandable panel events.
enum class ListBoxEvent : uint8_t { eSelected , eCount }
Enumeration of supported listbox events.
enum class ButtonEvent : uint8_t { eClicked , eCount }
Enumeration of supported button events.
enum class SliderEvent : uint8_t { eThumbRelease , eThumbTrack , eCount }
Enumeration of supported slider events.
enum class ScrollBarEvent : uint8_t { eThumbRelease , eThumbTrack , eCount }
Enumeration of supported combobox events.
enum class ControlFlag : ControlFlagType { eAlwaysOnTop = 0x0000000000000001 , eMovable = 0x0000000000000002 , eResizable = 0x0000000000000004 }
Listbox control supported flags.
enum class ComboBoxFlag : ControlFlagType { eReadOnly = 0x0000000000000100 }
Combo control supported flags.
enum class EditFlag : ControlFlagType { eProcessEnter = 0x0000000000001000 , eMultiline = 0x0000000000002000 , eProcessTab = 0x0000000000004000 , eWordWrap = 0x0000000000008000 }
Edit control supported flags.
enum class SliderFlag : ControlFlagType { eHorizontal = 0x0000000000100000 , eVertical = 0x0000000000200000 }
Slider control supported flags.
enum class StaticFlag : ControlFlagType {
eHAlignLeft = 0x0000000001000000 , eHAlignCenter = 0x0000000002000000 , eHAlignRight = 0x0000000004000000 , eVAlignTop = 0x0000000010000000 ,
eVAlignCenter = 0x0000000020000000 , eVAlignBottom = 0x0000000040000000
}
Static control supported flags.
enum class ScrollBarFlag : ControlFlagType { eHorizontal = 0x0000000100000000 , eVertical = 0x0000000200000000 }
ScrollBar control supported flags.
enum class ProgressFlag : ControlFlagType { eLeftRight = 0x0000001000000000 , eRightLeft = 0x0000002000000000 , eTopBottom = 0x0000004000000000 , eBottomTop = 0x0000008000000000 }
Progress control supported flags.
enum class GuiEvent : uint8_t { eShowMessageBox , eResizeParent }
Enumeration of supported GUI events in ControlInfos.
enum class OverlayBindingId : uint32_t {
eMaterials , eTexConfigs , eTexAnims , eCamera ,
eOverlays , eOverlaysIDs , eOverlaysSurfaces
}
The descriptor binding indices for overlay rendering.
enum class QueueFamilyFlag {
eNone = 0x00 , ePresent = 0x01 , eGraphics = 0x02 , eTransfer = 0x04 ,
eCompute = 0x08
}
enum class CSCNSection : uint32_t {
eRoot = CU_MakeSectionName('R', 'O', 'O', 'T') , eScene = CU_MakeSectionName('S', 'C', 'N', 'E') , eWindow = CU_MakeSectionName('W', 'N', 'D', 'W') , eSampler = CU_MakeSectionName('S', 'M', 'P', 'R') ,
eCamera = CU_MakeSectionName('C', 'A', 'M', 'R') , eViewport = CU_MakeSectionName('V', 'W', 'P', 'T') , eLight = CU_MakeSectionName('L', 'G', 'H', 'T') , eNode = CU_MakeSectionName('N', 'O', 'D', 'E') ,
eObject = CU_MakeSectionName('O', 'B', 'J', 'T') , eObjectMaterials = CU_MakeSectionName('O', 'M', 'T', 'L') , eFont = CU_MakeSectionName('F', 'O', 'N', 'T') , ePanelOverlay = CU_MakeSectionName('P', 'O', 'V', 'L') ,
eBorderPanelOverlay = CU_MakeSectionName('B', 'O', 'V', 'L') , eTextOverlay = CU_MakeSectionName('T', 'O', 'V', 'L') , eMesh = CU_MakeSectionName('M', 'E', 'S', 'H') , eSubmesh = CU_MakeSectionName('S', 'M', 'S', 'H') ,
eMaterial = CU_MakeSectionName('M', 'T', 'R', 'L') , ePass = CU_MakeSectionName('P', 'A', 'S', 'S') , eTextureUnit = CU_MakeSectionName('U', 'N', 'I', 'T') , eRenderTarget = CU_MakeSectionName('R', 'T', 'G', 'R') ,
eShaderProgram = CU_MakeSectionName('G', 'L', 'S', 'L') , eShaderStage = CU_MakeSectionName('S', 'P', 'G', 'M') , eShaderUBO = CU_MakeSectionName('S', 'U', 'B', 'O') , eUBOVariable = CU_MakeSectionName('S', 'U', 'B', 'V') ,
eBillboard = CU_MakeSectionName('B', 'L', 'B', 'd') , eBillboardList = CU_MakeSectionName('B', 'L', 'B', 'L') , eAnimGroup = CU_MakeSectionName('A', 'N', 'G', 'P') , eAnimation = CU_MakeSectionName('A', 'N', 'M', 'T') ,
eSkybox = CU_MakeSectionName('S', 'K', 'B', 'X') , eParticleSystem = CU_MakeSectionName('P', 'L', 'S', 'M') , eParticle = CU_MakeSectionName('P', 'T', 'C', 'L') , eSsao = CU_MakeSectionName('S', 'S', 'A', 'O') ,
eHdrConfig = CU_MakeSectionName('H', 'D', 'R', 'C') , eShadows = CU_MakeSectionName('S', 'H', 'D', 'W') , eMeshDefaultMaterials = CU_MakeSectionName('M', 'M', 'T', 'L') , eRsm = CU_MakeSectionName('R', 'F', 'S', 'M') ,
eLpv = CU_MakeSectionName('L', 'P', 'V', 'I') , eRaw = CU_MakeSectionName('R', 'A', 'W', 'S') , ePcf = CU_MakeSectionName('P', 'C', 'F', 'S') , eVsm = CU_MakeSectionName('V', 'S', 'M', 'S') ,
eTextureAnimation = CU_MakeSectionName('T', 'X', 'A', 'N') , eVoxelConeTracing = CU_MakeSectionName('V', 'C', 'T', 'C') , eTextureTransform = CU_MakeSectionName('T', 'X', 'T', 'R') , eSceneImport = CU_MakeSectionName('I', 'M', 'P', 'T') ,
eSkeleton = CU_MakeSectionName('S', 'K', 'E', 'L') , eMorphAnimation = CU_MakeSectionName('M', 'T', 'A', 'N') , eTextureRemapChannel = CU_MakeSectionName('T', 'X', 'R', 'C') , eTextureRemap = CU_MakeSectionName('T', 'X', 'R', 'P')
}
Defines all the sections and subsections of a scene file.
Functions
template<typename DataT >
InterpolatorPtr< DataT > makeInterpolator (InterpolatorType type)
constexpr uint32_t makeCmshVersion (uint32_t maj, uint32_t min, uint32_t rev)
constexpr uint32_t getCmshMajor (uint32_t version)
constexpr uint32_t getCmshMinor (uint32_t version)
constexpr uint32_t getCmshRevision (uint32_t version)
uint64_t constexpr makeChunkID (char a, char b, char c, char d, char e, char f, char g, char h)
static void prepareChunkData (ChunkType &value)
Sets given value to big endian.
static uint8_t const * getBuffer (bool const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (bool &value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (int8_t const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (int8_t &value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (uint8_t const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (uint8_t &value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (int16_t const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (int16_t &value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (uint16_t const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (uint16_t &value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (int32_t const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (int32_t &value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (uint32_t const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (uint32_t &value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (int64_t const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (int64_t &value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (uint64_t const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (uint64_t &value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (float const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (float &value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (double const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (double &value)
Retrieves the beginning of the buffer for given value.
static uint8_t const * getBuffer (long double const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (long double &value)
Retrieves the beginning of the buffer for given value.
template<typename T >
static size_t getDataSize (T const &value)
Retrieves the value binary size.
template<typename T >
static uint8_t const * getBuffer (std::vector< T > const &value)
Retrieves the beginning of the buffer for given value.
template<typename T >
static uint8_t * getBuffer (std::vector< T > &value)
Retrieves the beginning of the buffer for given value.
template<typename T >
static size_t getDataSize (std::vector< T > const &value)
Retrieves the value binary size.
template<typename T , size_t Count>
static uint8_t const * getBuffer (std::array< T, Count > const &value)
Retrieves the beginning of the buffer for given value.
template<typename T , size_t Count>
static uint8_t * getBuffer (std::array< T, Count > &value)
Retrieves the beginning of the buffer for given value.
template<typename T , size_t Count>
static size_t getDataSize (std::array< T, Count > const &value)
Retrieves the value binary size.
template<typename T , uint32_t Count>
static uint8_t const * getBuffer (castor::Point< T, Count > const &value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Count>
static uint8_t * getBuffer (castor::Point< T, Count > &value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Count>
static size_t getDataSize (castor::Point< T, Count > const &value)
Retrieves the value binary size.
template<typename T , uint32_t Count>
static uint8_t const * getBuffer (castor::Coords< T, Count > const &value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Count>
static uint8_t * getBuffer (castor::Coords< T, Count > &value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Count>
static size_t getDataSize (castor::Coords< T, Count > const &value)
Retrieves the value binary size.
template<typename T , uint32_t Columns, uint32_t Rows>
static uint8_t const * getBuffer (castor::Matrix< T, Columns, Rows > const &value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Columns, uint32_t Rows>
static uint8_t * getBuffer (castor::Matrix< T, Columns, Rows > &value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Columns, uint32_t Rows>
static size_t getDataSize (castor::Matrix< T, Columns, Rows > const &value)
Retrieves the value binary size.
template<typename T , uint32_t Count>
static uint8_t const * getBuffer (castor::SquareMatrix< T, Count > const &value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Count>
static uint8_t * getBuffer (castor::SquareMatrix< T, Count > &value)
Retrieves the beginning of the buffer for given value.
template<typename T , uint32_t Count>
static size_t getDataSize (castor::SquareMatrix< T, Count > const &value)
Retrieves the value binary size.
static uint8_t const * getBuffer (castor::RgbColour const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (castor::RgbColour &value)
Retrieves the beginning of the buffer for given value.
static size_t getDataSize (castor::RgbColour const &value)
Retrieves the value binary size.
static uint8_t const * getBuffer (castor::RgbaColour const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (castor::RgbaColour &value)
Retrieves the beginning of the buffer for given value.
static size_t getDataSize (castor::RgbaColour const &value)
Retrieves the value binary size.
static uint8_t const * getBuffer (castor::Size const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (castor::Size &value)
Retrieves the beginning of the buffer for given value.
static size_t getDataSize (castor::Size const &value)
Retrieves the value binary size.
static uint8_t const * getBuffer (castor::Position const &value)
Retrieves the beginning of the buffer for given value.
static uint8_t * getBuffer (castor::Position &value)
Retrieves the beginning of the buffer for given value.
static size_t getDataSize (castor::Position const &value)
Retrieves the value binary size.
template<typename T >
static uint8_t const * getBuffer (castor::QuaternionT< T > const &value)
Retrieves the beginning of the buffer for given value.
template<typename T >
static uint8_t * getBuffer (castor::QuaternionT< T > &value)
Retrieves the beginning of the buffer for given value.
template<typename T >
static size_t getDataSize (castor::QuaternionT< T > const &value)
Retrieves the value binary size.
static void prepareChunkData (bool &value)
Sets given value to big endian.
static void prepareChunkData (int8_t &value)
Sets given value to big endian.
static void prepareChunkData (uint8_t &value)
Sets given value to big endian.
static void prepareChunkData (int16_t &value)
Sets given value to big endian.
static void prepareChunkData (uint16_t &value)
Sets given value to big endian.
static void prepareChunkData (int32_t &value)
Sets given value to big endian.
static void prepareChunkData (uint32_t &value)
Sets given value to big endian.
static void prepareChunkData (int64_t &value)
Sets given value to big endian.
static void prepareChunkData (uint64_t &value)
Sets given value to big endian.
static void prepareChunkData (float &value)
Sets given value to big endian.
static void prepareChunkData (double &value)
Sets given value to big endian.
static void prepareChunkData (long double &value)
Sets given value to big endian.
template<typename T >
static void prepareChunkData (std::vector< T > &values)
Sets given value to big endian.
template<typename T , size_t Count>
static void prepareChunkData (std::array< T, Count > &values)
Sets given value to big endian.
template<typename T , uint32_t Count>
static void prepareChunkData (castor::SquareMatrix< T, Count > &value)
Sets given value to big endian.
template<typename T , uint32_t Count>
static void prepareChunkData (castor::Point< T, Count > &value)
Sets given value to big endian.
template<typename T , uint32_t Count>
static void prepareChunkData (castor::Coords< T, Count > &value)
Sets given value to big endian.
template<typename T >
static void prepareChunkData (castor::QuaternionT< T > &value)
Sets given value to big endian.
static void prepareChunkData (castor::ColourComponent &value)
Sets given value to big endian.
static void prepareChunkData (castor::RgbColour &value)
Sets given value to big endian.
static void prepareChunkData (castor::RgbaColour &value)
Sets given value to big endian.
template<typename T >
static void prepareChunkData (OldInterleavedVertexT< T > &value)
Sets given value to big endian.
static void prepareChunkData (InterleavedVertex &value)
Sets given value to big endian.
static void prepareChunkData (SubmeshAnimationBuffer &value)
Sets given value to big endian.
static void prepareChunkData (FaceIndices &value)
Sets given value to big endian.
static void prepareChunkData (LineIndices &value)
Sets given value to big endian.
static void prepareChunkData (VertexBoneData &value)
Sets given value to big endian.
template<typename T >
ashes::BufferPtr< T > makeBuffer (RenderDevice const &device, VkDeviceSize count, VkBufferUsageFlags usage, VkMemoryPropertyFlags flags, std::string const &name, ashes::QueueShare sharingMode={})
ashes::BufferBasePtr makeBufferBase (RenderDevice const &device, VkDeviceSize size, VkBufferUsageFlags usage, VkMemoryPropertyFlags flags, std::string const &name, ashes::QueueShare sharingMode={})
template<typename T >
ashes::VertexBufferPtr< T > makeVertexBuffer (RenderDevice const &device, VkDeviceSize count, VkBufferUsageFlags usage, VkMemoryPropertyFlags flags, std::string const &name, ashes::QueueShare sharingMode={})
ashes::VertexBufferBasePtr makeVertexBufferBase (RenderDevice const &device, VkDeviceSize size, VkBufferUsageFlags usage, VkMemoryPropertyFlags flags, std::string const &name, ashes::QueueShare sharingMode={})
C3D_API void createUniformPassBinding (crg::FramePass &pass, uint32_t binding, std::string const &name, ashes::BufferBase const &buffer, VkDeviceSize offset, VkDeviceSize size)
C3D_API void createInputStoragePassBinding (crg::FramePass &pass, uint32_t binding, std::string const &name, ashes::BufferBase const &buffer, VkDeviceSize offset, VkDeviceSize size)
C3D_API void createInOutStoragePassBinding (crg::FramePass &pass, uint32_t binding, std::string const &name, ashes::BufferBase const &buffer, VkDeviceSize offset, VkDeviceSize size)
C3D_API void createOutputStoragePassBinding (crg::FramePass &pass, uint32_t binding, std::string const &name, ashes::BufferBase const &buffer, VkDeviceSize offset, VkDeviceSize size)
C3D_API void createUniformPassBinding (crg::FramePass &pass, uint32_t binding, std::string const &name, ashes::Buffer< uint8_t > const &buffer, VkDeviceSize offset, VkDeviceSize size)
C3D_API void createInputStoragePassBinding (crg::FramePass &pass, uint32_t binding, std::string const &name, ashes::Buffer< uint8_t > const &buffer, VkDeviceSize offset, VkDeviceSize size)
C3D_API void createInOutStoragePassBinding (crg::FramePass &pass, uint32_t binding, std::string const &name, ashes::Buffer< uint8_t > const &buffer, VkDeviceSize offset, VkDeviceSize size)
C3D_API void createOutputStoragePassBinding (crg::FramePass &pass, uint32_t binding, std::string const &name, ashes::Buffer< uint8_t > const &buffer, VkDeviceSize offset, VkDeviceSize size)
PoolUniformBufferUPtr makePoolUniformBuffer (RenderSystem const &renderSystem, castor::ArrayView< uint8_t > data, VkBufferUsageFlags usage, VkMemoryPropertyFlags flags, std::string name, ashes::QueueShare sharingMode={})
template<typename DataT >
UniformBufferUPtrT< DataT > makeUniformBuffer (RenderSystem const &renderSystem, VkDeviceSize count, VkBufferUsageFlags usage, VkMemoryPropertyFlags flags, std::string name, ashes::QueueShare sharingMode={})
UniformBufferBaseUPtr makeUniformBufferBase (RenderSystem const &renderSystem, VkDeviceSize count, VkDeviceSize size, VkBufferUsageFlags usage, VkMemoryPropertyFlags flags, std::string name, ashes::QueueShare sharingMode={})
template<typename DataT >
ashes::WriteDescriptorSet makeDescriptorWrite (UniformBufferOffsetT< DataT > const &buffer, uint32_t dstBinding, uint32_t dstArrayElement=0u)
Creates a descriptor write for uniform buffer range.
C3D_API size_t hash (BillboardBase const &billboard, Pass const &pass)
template<EventType EventT, typename CacheT >
CacheViewPtrT< CacheT, EventT > makeCacheView (castor::String const &name, CacheT &cache, typename CacheViewTraitsT< CacheT >::ElementInitialiserT initialiser={}, typename CacheViewTraitsT< CacheT >::ElementCleanerT cleaner={})
C3D_API size_t hash (Geometry const &geometry, Submesh const &submesh, Pass const &pass)
template<typename ObjT , typename KeyT , typename TraitsT , typename ... ParametersT>
ObjectCachePtrT< ObjT, KeyT, TraitsT > makeObjectCache (ParametersT &&... parameters)
Creates an object cache.
castor::UniquePtr< ShaderProgramCache > makeCache (Engine &engine)
Creates a ashes::ShaderProgram cache.
CU_DeclareSmartPtr (castor3d, Engine,)
CU_DeclareSmartPtr (castor3d, ImporterFile,)
CU_DeclareSmartPtr (castor3d, FramePassTimer,)
CU_DeclareSmartPtr (castor3d, ImporterFileFactory,)
castor::LoggerInstance & getLogger (Engine &engine)
castor::Matrix4x4f convert (std::array< float, 16 > const &value)
VkClearColorValue convert (castor::RgbaColour const &value)
castor::RgbaColour convert (VkClearColorValue const &value)
std::array< float, 4u > makeFloatArray (castor::RgbaColour const &value)
CU_DeclareVector (float, Float)
CU_DeclareMap (uint32_t, int, IntUInt)
CU_DeclareMap (castor::String, int, IntStr)
CU_DeclareMap (int, castor::String, StrInt)
VkDescriptorSetLayoutBinding makeDescriptorSetLayoutBinding (uint32_t binding, VkDescriptorType descriptorType, VkShaderStageFlags stageFlags, uint32_t descriptorCount=1u, VkSampler const *pImmutableSamplers=nullptr)
castor::Size makeSize (VkExtent2D const &size)
castor::Size makeSize (VkExtent3D const &size)
VkExtent2D makeExtent2D (VkExtent3D const &size)
VkExtent3D makeExtent3D (VkExtent2D const &size)
VkExtent2D makeExtent2D (castor::Coords2ui const &size)
VkExtent2D makeExtent2D (castor::Point2ui const &size)
VkExtent3D makeExtent3D (castor::Coords2ui const &size)
VkExtent3D makeExtent3D (castor::Point2ui const &size)
VkOffset2D makeOffset2D (castor::Coords2i const &pos)
VkOffset2D makeOffset2D (castor::Point2i const &pos)
VkOffset3D makeOffset3D (castor::Coords2i const &pos)
VkOffset3D makeOffset3D (castor::Point2i const &pos)
VkViewport makeViewport (castor::Coords2ui const &size, float zMin=0.0f, float zMax=1.0f)
VkViewport makeViewport (castor::Point2ui const &size, float zMin=0.0f, float zMax=1.0f)
VkViewport makeViewport (castor::Coords2i const &pos, castor::Coords2ui const &size, float zMin=0.0f, float zMax=1.0f)
VkViewport makeViewport (castor::Point2i const &pos, castor::Coords2ui const &size, float zMin=0.0f, float zMax=1.0f)
VkViewport makeViewport (castor::Coords2i const &pos, castor::Point2ui const &size, float zMin=0.0f, float zMax=1.0f)
VkViewport makeViewport (castor::Point2i const &pos, castor::Point2ui const &size, float zMin=0.0f, float zMax=1.0f)
VkRect2D makeScissor (castor::Coords2ui const &size)
VkRect2D makeScissor (castor::Point2ui const &size)
VkRect2D makeScissor (castor::Coords2i const &pos, castor::Coords2ui const &size)
VkRect2D makeScissor (castor::Point2i const &pos, castor::Coords2ui const &size)
VkRect2D makeScissor (castor::Coords2i const &pos, castor::Point2ui const &size)
VkRect2D makeScissor (castor::Point2i const &pos, castor::Point2ui const &size)
VkClearValue makeClearValue (float depth, uint32_t stencil=0u)
VkClearValue makeClearValue (uint32_t r, uint32_t g, uint32_t b, uint32_t a)
VkClearValue makeClearValue (float r, float g, float b, float a=1.0f)
template<typename EnumT >
castor::UInt32StrMap getEnumMapT (EnumT min, EnumT max)
template<typename EnumT >
castor::UInt32StrMap getEnumMapT ()
bool operator> (VkImageSubresourceRange const &lhs, VkImageSubresourceRange const &rhs)
bool operator< (VkImageSubresourceRange const &lhs, VkImageSubresourceRange const &rhs)
bool operator<= (VkImageSubresourceRange const &lhs, VkImageSubresourceRange const &rhs)
bool operator>= (VkImageSubresourceRange const &lhs, VkImageSubresourceRange const &rhs)
bool operator!= (VkImageSubresourceRange const &lhs, VkImageSubresourceRange const &rhs)
bool operator== (VkImageSubresourceRange const &lhs, VkImageSubresourceRange const &rhs)
template<typename EventT , typename ... ParamsT>
CpuFrameEventUPtr makeCpuFrameEvent (ParamsT &&... params)
CpuFrameEventUPtr makeCpuFunctorEvent (EventType type, CpuFunctorEvent::Functor functor)
Helper function to create a functor event.
template<typename T >
CpuFrameEventUPtr makeCpuCleanupEvent (T &object)
Helper function to create a cleanup event.
template<typename T >
CpuFrameEventUPtr makeCpuInitialiseEvent (T &object)
Helper function to create an initialise event.
template<typename EventT , typename ... ParamsT>
GpuFrameEventUPtr makeGpuFrameEvent (ParamsT &&... params)
GpuFrameEventUPtr makeGpuFunctorEvent (EventType type, GpuFunctorEvent::Functor functor)
Helper function to create a functor event.
template<typename T >
GpuFrameEventUPtr makeGpuCleanupEvent (T &object)
Helper function to create a cleanup event.
template<typename T >
GpuFrameEventUPtr makeGpuInitialiseEvent (T &object)
Helper function to create an initialise event.
C3D_API bool isLayoutControl (ControlType type)
C3D_API bool isLayoutControl (Control const &control)
C3D_API bool isScrollableControl (ControlType type)
C3D_API bool isScrollableControl (Control const &control)
CU_DeclareSmartPtr (castor3d, Layout, C3D_API)
CU_DeclareSmartPtr (castor3d, Spacer, C3D_API)
CU_DeclareSmartPtr (castor3d, ControlsManager, C3D_API)
CU_DeclareSmartPtr (castor3d, Control, C3D_API)
CU_DeclareSmartPtr (castor3d, LayoutControl, C3D_API)
CU_DeclareSmartPtr (castor3d, ButtonCtrl, C3D_API)
CU_DeclareSmartPtr (castor3d, ComboBoxCtrl, C3D_API)
CU_DeclareSmartPtr (castor3d, EditCtrl, C3D_API)
CU_DeclareSmartPtr (castor3d, ExpandablePanelCtrl, C3D_API)
CU_DeclareSmartPtr (castor3d, FrameCtrl, C3D_API)
CU_DeclareSmartPtr (castor3d, ListBoxCtrl, C3D_API)
CU_DeclareSmartPtr (castor3d, PanelCtrl, C3D_API)
CU_DeclareSmartPtr (castor3d, ProgressCtrl, C3D_API)
CU_DeclareSmartPtr (castor3d, ScrollableCtrl, C3D_API)
CU_DeclareSmartPtr (castor3d, ScrollBarCtrl, C3D_API)
CU_DeclareSmartPtr (castor3d, SliderCtrl, C3D_API)
CU_DeclareSmartPtr (castor3d, StaticCtrl, C3D_API)
CU_DeclareSmartPtr (castor3d, StylesHolder, C3D_API)
CU_DeclareSmartPtr (castor3d, Theme, C3D_API)
CU_DeclareSmartPtr (castor3d, ControlStyle, C3D_API)
CU_DeclareSmartPtr (castor3d, ButtonStyle, C3D_API)
CU_DeclareSmartPtr (castor3d, ComboBoxStyle, C3D_API)
CU_DeclareSmartPtr (castor3d, EditStyle, C3D_API)
CU_DeclareSmartPtr (castor3d, ExpandablePanelStyle, C3D_API)
CU_DeclareSmartPtr (castor3d, FrameStyle, C3D_API)
CU_DeclareSmartPtr (castor3d, ListBoxStyle, C3D_API)
CU_DeclareSmartPtr (castor3d, PanelStyle, C3D_API)
CU_DeclareSmartPtr (castor3d, ProgressStyle, C3D_API)
CU_DeclareSmartPtr (castor3d, ScrollableStyle, C3D_API)
CU_DeclareSmartPtr (castor3d, ScrollBarStyle, C3D_API)
CU_DeclareSmartPtr (castor3d, SliderStyle, C3D_API)
CU_DeclareSmartPtr (castor3d, StaticStyle, C3D_API)
void setMaterialColour (Pass &pass, castor::HdrRgbColour const &colour)
castor::HdrRgbColour const & getMaterialColour (Pass const &pass)
MaterialObs createMaterial (Engine &engine, castor::String const &name, castor::HdrRgbColour const &colour)
MaterialObs createMaterial (Engine &engine, castor::String const &name, TextureLayoutUPtr texture)
C3D_API bool isStylesHolder (ControlType type)
C3D_API bool isStylesHolder (ControlStyle const &style)
bool parseImportParameters (Parameters const &parameters, castor::Point3f &scale, castor::Quaternion &orientation)
SamplerObs createSampler (Engine &engine, castor::String const &baseName, VkFilter filter, VkImageSubresourceRange const *range)
castor::String getSamplerName (VkCompareOp compareOp, VkFilter minFilter, VkFilter magFilter, VkSamplerMipmapMode mipFilter, VkSamplerAddressMode U, VkSamplerAddressMode V, VkSamplerAddressMode W)
C3D_API TextureLayoutUPtr createTextureLayout (Engine const &engine, castor::Path const &relative, castor::Path const &folder, castor::ImageLoaderConfig config={ true, true, true })
C3D_API TextureLayoutUPtr createTextureLayout (Engine const &engine, castor::String const &name, castor::PxBufferBaseUPtr buffer, bool isStatic=false)
C3D_API uint32_t getMipLevels (VkExtent3D const &extent, VkFormat format)
ashes::ImagePtr makeImage (RenderDevice const &device, ashes::ImageCreateInfo createInfo, VkMemoryPropertyFlags flags, std::string const &name)
template<typename ResT >
ashes::DeviceMemoryPtr setupMemory (ashes::Device const &device, ResT &resource, VkMemoryPropertyFlags flags, std::string const &name)
template<typename ResT >
ashes::DeviceMemoryPtr setupMemory (RenderDevice const &device, ResT &resource, VkMemoryPropertyFlags flags, std::string const &name)
C3D_API std::ostream & operator<< (std::ostream &stream, GpuInformations const &object)
Output stream operator.
template<typename VkStructT , typename ... ParamsT>
VkStructT makeVkStructPNext (void *next, ParamsT &&... params)
template<typename VkStructT , typename ... ParamsT>
VkStructT makeVkStruct (ParamsT &&... params)
C3D_API void setProgressBarTitle (ProgressBar *progress, castor::String const &value)
C3D_API void setProgressBarLabel (ProgressBar *progress, castor::String const &value)
C3D_API void stepProgressBar (ProgressBar *progress, castor::String const &label)
C3D_API void stepProgressBar (ProgressBar *progress)
C3D_API void incProgressBarRange (ProgressBar *progress, int32_t value)
C3D_API bool operator== (castor3d::Version const &a, castor3d::Version const &b)
Equality operator.
C3D_API bool operator!= (castor3d::Version const &a, castor3d::Version const &b)
Difference operator.
C3D_API bool operator< (castor3d::Version const &a, castor3d::Version const &b)
Less than operator.
C3D_API bool operator> (castor3d::Version const &a, castor3d::Version const &b)
Less than operator.
C3D_API bool operator<= (castor3d::Version const &a, castor3d::Version const &b)
Less than operator.
C3D_API bool operator>= (castor3d::Version const &a, castor3d::Version const &b)
Less than operator.
C3D_API std::ostream & operator<< (std::ostream &stream, castor3d::Version const &version)
C3D_API std::wostream & operator<< (std::wostream &stream, castor3d::Version const &version)
C3D_API castor::String & operator<< (castor::String &stream, castor3d::Version const &version)
std::ostream & operator<< (std::ostream &o, Cone const &c)
std::ostream & operator<< (std::ostream &o, Cube const &c)
std::ostream & operator<< (std::ostream &o, Cylinder const &c)
std::ostream & operator<< (std::ostream &o, Icosahedron const &c)
std::ostream & operator<< (std::ostream &o, Projection const &c)
std::ostream & operator<< (std::ostream &o, Sphere const &c)
std::ostream & operator<< (std::ostream &o, SphereSection const &c)
C3D_API void uploadBaseData (SubmeshFlag submeshData, Submesh const &submesh, castor::Point3fArray const &data)
C3D_API void gatherBaseDataBuffer (SubmeshFlag submeshData, PipelineFlags const &flags, ashes::PipelineVertexInputStateCreateInfoCRefArray &layouts, uint32_t &currentBinding, uint32_t &currentLocation, std::unordered_map< size_t, ashes::PipelineVertexInputStateCreateInfo > &cache)
C3D_API void postPreRenderGpuEvent (Engine &engine, std::function< void(RenderDevice const &, QueueData const &) > event)
C3D_API void postQueueRenderCpuEvent (Engine &engine, std::function< void() > event)
void registerPipelineNodes (PipelineBaseHash hash, ashes::BufferBase const &buffer, std::vector< PipelineBuffer > &nodesIds)
uint32_t getPipelineNodeIndex (PipelineBaseHash hash, ashes::BufferBase const &buffer, std::vector< PipelineBuffer > const &cont)
PipelineNodes & getPipelineNodes (PipelineBaseHash hash, ashes::BufferBase const &buffer, std::vector< PipelineBuffer > const &cont, PipelineNodes *nodes, VkDeviceSize maxNodesCount)
AnimatedObjectRPtr findAnimatedObject (Scene const &scene, castor::String const &name)
size_t hash (SubmeshRenderNode const &culled)
bool isVisible (Camera const &camera, SubmeshRenderNode const &node)
bool isVisible (Frustum const &frustum, SubmeshRenderNode const &node)
size_t hash (BillboardRenderNode const &culled)
bool isVisible (Camera const &camera, BillboardRenderNode const &node)
bool isVisible (Frustum const &frustum, BillboardRenderNode const &node)
C3D_API VkFormatFeatureFlags getFeatureFlags (VkImageUsageFlags flags)
uint32_t getLightRenderPassIndex (bool blend, LightType lightType)
CU_DeclareSmartPtr (castor3d, OverlayRenderer, C3D_API)
CU_DeclareSmartPtr (castor3d, OverlayTextBufferPool, C3D_API)
C3D_API bool operator< (PipelineBaseHash const &lhs, PipelineBaseHash const &rhs)
bool operator== (PipelineBaseHash const &lhs, PipelineBaseHash const &rhs)
C3D_API bool operator== (PipelineHiHashDetails const &lhs, PipelineHiHashDetails const &rhs)
C3D_API bool operator== (PipelineLoHashDetails const &lhs, PipelineLoHashDetails const &rhs)
C3D_API bool operator== (PipelineFlags const &lhs, PipelineFlags const &rhs)
C3D_API PipelineBaseHash getPipelineBaseHash (PassComponentRegister const &passComponents, PipelineFlags const &flags)
C3D_API PipelineBaseHash getPipelineBaseHash (RenderNodesPass const &renderPass, Submesh const &data, Pass const &pass, bool isFrontCulled)
C3D_API PipelineBaseHash getPipelineBaseHash (RenderNodesPass const &renderPass, BillboardBase const &data, Pass const &pass, bool isFrontCulled)
C3D_API PipelineHiHashDetails getPipelineHiHashDetails (RenderNodesPass const &renderPass, PipelineBaseHash const &hash, ShaderFlags shaderFlags)
C3D_API PipelineHiHashDetails getPipelineHiHashDetails (RenderTechniquePass const &renderPass, PipelineBaseHash const &hash, ShaderFlags shaderFlags)
CU_DeclareSmartPtr (castor3d, IsRenderPassEnabled, C3D_API)
C3D_API bool operator== (DirectionalLightCascade const &lhs, DirectionalLightCascade const &rhs)
bool operator!= (DirectionalLightCascade const &lhs, DirectionalLightCascade const &rhs)
VkDeviceSize getSize (ParticleFormat format)
C3D_API bool operator== (ParticleDeclaration const &lhs, ParticleDeclaration const &rhs)
Equality operator.
C3D_API bool operator!= (ParticleDeclaration const &lhs, ParticleDeclaration const &rhs)
Equality operator.
bool operator== (ParticleElementDeclaration const &lhs, ParticleElementDeclaration const &rhs)
Equality operator.
bool operator!= (ParticleElementDeclaration const &lhs, ParticleElementDeclaration const &rhs)
Equality operator.
C3D_API std::string print (castor::Point3f const &obj)
C3D_API std::string print (castor::BoundingBox const &obj)
C3D_API SceneFileContext & getSceneParserContext (castor::FileParserContext &context)
C3D_API SceneFileContext & getParserContext (castor::FileParserContext &context)
template<typename ComponentT >
ComponentT & getPassComponent (SceneFileContext &parsingContext)
C3D_API void initialiseGlslang ()
Initialises glslang globals.
C3D_API void cleanupGlslang ()
Cleans up glslang globals.
C3D_API UInt32Array compileGlslToSpv (RenderDevice const &device, VkShaderStageFlagBits stage, std::string const &shader)
Transpiles a GLSL shader to SPIR-V.
C3D_API SpirVShader const & compileShader (RenderDevice const &device, ShaderModule &module)
C3D_API SpirVShader const & compileShader (RenderSystem const &renderSystem, ShaderModule &module)
ashes::PipelineShaderStageCreateInfo makeShaderState (ashes::Device const &device, VkShaderStageFlagBits stage, SpirVShader const &code, std::string const &name, std::string mainFuncName="main", ashes::Optional< ashes::SpecializationInfo > specialization=ashes::nullopt)
ashes::PipelineShaderStageCreateInfo makeShaderState (RenderDevice const &device, ShaderModule &shaderModule, std::string mainFuncName="main", ashes::Optional< ashes::SpecializationInfo > specialization=ashes::nullopt)
Base Components
CU_DeclareSmartPtr (castor3d, BlendComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, FractalMappingComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, NormalComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, PassHeaderComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, PickableComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, TextureCountComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, TexturesComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, TwoSidedComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, UntileMappingComponent, C3D_API)
Lighting Components
CU_DeclareSmartPtr (castor3d, AmbientComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, AttenuationComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, ClearcoatComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, EmissiveComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, IridescenceComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, LightingModelComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, MetalnessComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, RoughnessComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, SheenComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, SpecularComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, SubsurfaceScatteringComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, ThicknessComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, TransmissionComponent, C3D_API)
Texture Components
CU_DeclareSmartPtr (castor3d, AttenuationMapComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, ClearcoatMapComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, ClearcoatNormalMapComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, ClearcoatRoughnessMapComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, ColourMapComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, EmissiveMapComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, GlossinessMapComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, HeightMapComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, IridescenceMapComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, IridescenceThicknessMapComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, MetalnessMapComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, NormalMapComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, OcclusionMapComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, OpacityMapComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, RoughnessMapComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, SheenMapComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, SheenRoughnessMapComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, SpecularFactorMapComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, SpecularMapComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, TransmissionMapComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, TransmittanceMapComponent, C3D_API)
Other components
CU_DeclareSmartPtr (castor3d, AlphaTestComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, ColourComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, HeightComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, OpacityComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, ReflectionComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, RefractionComponent, C3D_API)
C3D_API bool operator== (TextureTransform const &lhs, TextureTransform const &rhs) noexcept
bool operator!= (TextureTransform const &lhs, TextureTransform const &rhs) noexcept
C3D_API bool shallowEqual (TextureFlagConfiguration const &lhs, TextureFlagConfiguration const &rhs)
C3D_API bool operator== (TextureFlagConfiguration const &lhs, TextureFlagConfiguration const &rhs) noexcept
bool operator!= (TextureFlagConfiguration const &lhs, TextureFlagConfiguration const &rhs) noexcept
C3D_API bool shallowEqual (TextureConfiguration const &lhs, TextureConfiguration const &rhs)
C3D_API bool operator== (TextureConfiguration const &lhs, TextureConfiguration const &rhs)
bool operator!= (TextureConfiguration const &lhs, TextureConfiguration const &rhs) noexcept
C3D_API TextureFlagsSet getFlags (TextureConfiguration const &config)
C3D_API castor::PixelComponents getPixelComponents (uint32_t mask)
C3D_API castor::PixelComponents getPixelComponents (castor::PixelFormat format)
C3D_API castor::PixelComponents getPixelComponents (TextureConfiguration const &config)
C3D_API void updateIndices (castor::PixelFormat format, TextureConfiguration &config)
C3D_API TextureFlagConfigurations::const_iterator checkFlag (TextureFlagConfigurations const &lhs, PassComponentTextureFlag rhs)
C3D_API TextureFlagConfigurations::iterator checkFlag (TextureFlagConfigurations &lhs, PassComponentTextureFlag rhs)
C3D_API bool hasAny (TextureFlagConfigurations const &lhs, PassComponentTextureFlag rhs)
C3D_API void removeFlag (TextureConfiguration &config, PassComponentTextureFlag rhs)
C3D_API void removeFlagConfiguration (TextureConfiguration &config, TextureFlagConfiguration const &flagConfiguration)
C3D_API void addFlagConfiguration (TextureConfiguration &config, TextureFlagConfiguration flagConfiguration)
C3D_API TextureFlagConfiguration & getFlagConfiguration (TextureConfiguration &config, PassComponentTextureFlag textureFlag)
C3D_API uint32_t getComponentsMask (TextureConfiguration const &config, PassComponentTextureFlag textureFlag)
C3D_API PassComponentTextureFlag getEnabledFlag (TextureConfiguration const &config)
C3D_API void mergeConfigs (TextureConfiguration const &lhs, TextureConfiguration &rhs)
C3D_API void mergeConfigsBase (TextureConfiguration const &lhs, TextureConfiguration &rhs)
C3D_API TextureFlagConfigurations::const_iterator findFirstEmpty (TextureConfiguration const &config)
C3D_API TextureFlagConfigurations::iterator findFirstEmpty (TextureConfiguration &config)
C3D_API TextureFlagConfigurations::const_iterator findFirstNonEmpty (TextureConfiguration const &config)
C3D_API TextureFlagConfigurations::iterator findFirstNonEmpty (TextureConfiguration &config)
Generator
CU_DeclareSmartPtr (castor3d, Cone, C3D_API)
CU_DeclareSmartPtr (castor3d, Cube, C3D_API)
CU_DeclareSmartPtr (castor3d, Cylinder, C3D_API)
CU_DeclareSmartPtr (castor3d, Icosahedron, C3D_API)
CU_DeclareSmartPtr (castor3d, Plane, C3D_API)
CU_DeclareSmartPtr (castor3d, Projection, C3D_API)
CU_DeclareSmartPtr (castor3d, Sphere, C3D_API)
CU_DeclareSmartPtr (castor3d, SphereSection, C3D_API)
CU_DeclareSmartPtr (castor3d, Torus, C3D_API)
EnvironmentMap
CU_DeclareSmartPtr (castor3d, EnvironmentMap, C3D_API)
CU_DeclareSmartPtr (castor3d, EnvironmentMapPass, C3D_API)
Voxelize
CU_DeclareSmartPtr (castor3d, VoxelBufferToTexture, C3D_API)
CU_DeclareSmartPtr (castor3d, VoxelizePass, C3D_API)
CU_DeclareSmartPtr (castor3d, VoxelSecondaryBounce, C3D_API)
CU_DeclareSmartPtr (castor3d, Voxelizer, C3D_API)
Passes
CU_DeclareSmartPtr (castor3d, BackgroundRenderer, C3D_API)
CU_DeclareSmartPtr (castor3d, CombinePass, C3D_API)
CU_DeclareSmartPtr (castor3d, DownscalePass, C3D_API)
CU_DeclareSmartPtr (castor3d, GaussianBlur, C3D_API)
CU_DeclareSmartPtr (castor3d, LineariseDepthPass, C3D_API)
CU_DeclareSmartPtr (castor3d, PickingPass, C3D_API)
CU_DeclareSmartPtr (castor3d, RenderQuad, C3D_API)
CU_DeclareSmartPtr (castor3d, RenderGrid, C3D_API)
CU_DeclareSmartPtr (castor3d, StencilPass, C3D_API)
CU_DeclareVector (CommandsSemaphore, CommandsSemaphore)
PBR
CU_DeclareSmartPtr (castor3d, IblTextures, C3D_API)
SSAO
CU_DeclareSmartPtr (castor3d, SsaoBlurPass, C3D_API)
CU_DeclareSmartPtr (castor3d, SsaoPass, C3D_API)
CU_DeclareSmartPtr (castor3d, SsaoRawAOPass, C3D_API)
ToTexture
CU_DeclareSmartPtr (castor3d, EquirectangularToCube, C3D_API)
CU_DeclareSmartPtr (castor3d, RenderCube, C3D_API)
CU_DeclareSmartPtr (castor3d, Texture3DTo2D, C3D_API)
Transform
CU_DeclareSmartPtr (castor3d, VertexTransforming, C3D_API)
CU_DeclareSmartPtr (castor3d, VertexTransformPass, C3D_API)
CU_DeclareSmartPtr (castor3d, MeshletBoundsTransformPass, C3D_API)
UBO
CU_DeclareSmartPtr (castor3d, LpvGridConfigUbo, C3D_API)
CU_DeclareSmartPtr (castor3d, LpvLightConfigUbo, C3D_API)
CU_DeclareSmartPtr (castor3d, LayeredLpvGridConfigUbo, C3D_API)
CU_DeclareSmartPtr (castor3d, SceneUbo, C3D_API)
CU_DeclareVector (LpvLightConfigUbo, LpvLightConfigUbo)
CU_DeclareVector (LpvGridConfigUbo, LpvGridConfigUbo)
Variables
uint32_t constexpr CurrentCmshVersion = makeCmshVersion(0x01u, 0x06u, 0x0000u)
static uint32_t constexpr InvalidIndex = ~(0u)
static VkColorComponentFlags const defaultColorWriteMask { VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT }
static VkClearValue const defaultClearDepthStencil { makeClearValue(0.0f, 0u) }
static VkClearValue const opaqueBlackClearColor { makeClearValue(0.0f, 0.0f, 0.0f, 1.0f) }
static VkClearValue const transparentBlackClearColor { makeClearValue(0.0f, 0.0f, 0.0f, 0.0f) }
static VkClearValue const opaqueWhiteClearColor { makeClearValue(1.0f, 1.0f, 1.0f, 1.0f) }
static VkClearValue const transparentWhiteClearColor { makeClearValue(1.0f, 1.0f, 1.0f, 0.0f) }
static uint32_t constexpr InvalidPipelineIndex = ~(0u)
Shaders.
static uint32_t constexpr MaxLightingModels = 63u
static uint32_t constexpr MaxBackgroundModels = 63u
static uint32_t constexpr RandomDataCount = 1024u
Materials.
static uint32_t constexpr MaxPassTextures = 8u
static uint32_t constexpr MaxPassLayers = 15u
static float constexpr MaxPhongShininess = 256.0f
static uint32_t constexpr TransmittanceProfileSize = 10u
Render nodes.
static uint64_t constexpr MaxPipelines = 32'768ull
static uint64_t constexpr MaxNodesPerPipeline = 1'024ull
static uint64_t constexpr MaxSubmeshMeshletDrawIndirectCommand = MaxPipelines
static uint64_t constexpr MaxSubmeshIdxDrawIndirectCommand = MaxPipelines
static uint64_t constexpr MaxSubmeshNIdxDrawIndirectCommand = MaxPipelines
static uint64_t constexpr MaxBillboardDrawIndirectCommand = MaxPipelines
static uint64_t constexpr MaxObjectNodesCount = 262'144ull
PBR.
static uint32_t constexpr RadianceMapSize = 32u
static uint32_t constexpr PrefilteredEnvironmentMapSize = 128u
static uint32_t constexpr PrefilteredBrdfMapSize = 512u
static uint32_t constexpr MaxIblReflectionLod = 4u
Environment maps.
static uint32_t constexpr MaxEnvironmentMapCount = 10u
static uint32_t constexpr EnvironmentMipLevels = 8u
static uint32_t constexpr EnvironmentMapSize = 0x0001u << (EnvironmentMipLevels - 1u)
Light Propagation Volumes.
static uint32_t constexpr LpvMaxPropagationSteps = 8u
static uint32_t constexpr LpvMaxCascadesCount = 3u
Voxel Cone Tracing.
static uint32_t constexpr VctMaxTextureSize = 512u
static uint32_t constexpr VctMaxDiffuseCones = 16u
PCF Filtering.
static uint32_t constexpr MaxPcfFilterSize = 64u
static uint32_t constexpr MaxPcfSampleCount = 64u
Directional Light Shadows.
static uint32_t constexpr ShadowMapDirectionalTextureSize = 2048u
static uint32_t constexpr MaxDirectionalCascadesCount = 6u
Point Light Shadows.
static uint32_t constexpr ShadowMapPointTextureSize = 256u
static uint32_t constexpr MaxPointShadowMapCount = 8u
Spot Light Shadows.
static uint32_t constexpr ShadowMapSpotTextureSize = 256u
static uint32_t constexpr MaxSpotShadowMapCount = 16u
Shader buffers.
static uint32_t constexpr MaxLightsCount = 2'048u
static uint32_t constexpr MaxMaterialsCount = 2'048u
static uint32_t constexpr MaxSssProfilesCount = 128u
static int32_t constexpr MaxMaterialComponentsCount = 8
static uint32_t constexpr MaxTextureConfigurationCount = 4'096u
static uint32_t constexpr MaxTextureAnimationCount = 4'096u
Uniform/Storage buffers.
static uint32_t constexpr MaxObjectIDNodesCount = 16'384u
static uint32_t constexpr MaxMorphingDataCount = 1'024u
static uint32_t constexpr MaxSkinningDataCount = 1'024u
Other.
static uint32_t constexpr MaxOverlaysPerBuffer = 65'536u
static uint32_t constexpr MaxCharsPerOverlay = 1'024u
static uint32_t constexpr MaxLinesPerOverlay = 1'024u
static uint32_t constexpr MaxCharsPerBuffer = 65'536u
static uint32_t constexpr MaxWordsPerBuffer = 16'384u
static uint32_t constexpr MaxLinesPerBuffer = 16'384u
static uint32_t constexpr MaxTextsContsPerOverlay = MaxCharsPerOverlay
static uint32_t constexpr BaseObjectPoolBufferCount = 1'048'576u
static uint32_t constexpr MaxBonesPerVertex = 8u
static uint32_t constexpr MaxBonesCount = 512u
static uint32_t constexpr MaxMorphTargets = 128u
static uint32_t constexpr MaxLinearizedDepthMipLevel = 5u
static uint32_t constexpr PickingAreaWidth = 32u
static uint32_t constexpr MaxRsmRange = 1'024u
static uint32_t constexpr MaxBindlessResources = 16'384u
static uint32_t constexpr MaxTextureCoordinatesSets = 4u
Meshlet.
static uint32_t constexpr MaxMeshletVertexCount = 64u
static uint32_t constexpr MaxMeshletTriangleCount = 124u
Animation
enum class AnimationState : uint8_t {
ePlaying , eStopped , ePaused , eCount ,
eMin = ePlaying , eMax =eCount-1
}
Animation State Enumerator.
enum class AnimationType : uint8_t {
eSceneNode , eSkeleton , eMesh , eTexture ,
eCount , eMin = eSceneNode , eMax =eCount-1
}
Animation types enumeration.
enum class InterpolatorType : uint8_t {
eNearest , eLinear , eCount , eMin = eNearest ,
eMax =eCount-1
}
Interpolation modes enumeration.
using Point3rInterpolator = Interpolator< castor::Point3f >
using QuaternionInterpolator = Interpolator< castor::Quaternion >
template<typename DataT >
using InterpolatorPtr = std::unique_ptr< Interpolator< DataT > >
using AnimationKeyFrameArray = std::vector< AnimationKeyFrameUPtr >
using TextureRotateSpeed = castor::SpeedT< castor::Angle, castor::Seconds >
using TextureTranslateSpeed = castor::SpeedT< castor::Point2f, castor::Seconds >
using TextureScaleSpeed = castor::SpeedT< castor::Point2f, castor::Seconds >
C3D_API castor::String getName (AnimationState value)
C3D_API castor::String getName (AnimationType value)
C3D_API castor::String getName (InterpolatorType value)
CU_DeclareSmartPtr (castor3d, AnimationKeyFrame, C3D_API)
CU_DeclareSmartPtr (castor3d, AnimationImporter, C3D_API)
CU_DeclareSmartPtr (castor3d, AnimationImporterFactory, C3D_API)
CU_DeclareTemplateSmartPtr (castor3d, Animation)
CU_DeclareTemplateSmartPtr (castor3d, AnimationInstance)
CU_DeclareSmartPtr (castor3d, TextureAnimation, C3D_API)
CU_DeclareSmartPtr (castor3d, TextureAnimationKeyFrame, C3D_API)
CU_DeclareSmartPtr (castor3d, MeshAnimation, C3D_API)
CU_DeclareSmartPtr (castor3d, MeshAnimationSubmesh, C3D_API)
CU_DeclareSmartPtr (castor3d, MeshMorphTarget, C3D_API)
CU_DeclareVector (MeshAnimationSubmesh, MeshAnimationSubmesh)
Frame
enum class EventType : uint8_t {
ePreRender , eQueueRender , ePostRender , eCount ,
eMin = ePreRender , eMax =eCount-1
}
Frame Event Type enumeration.
using FrameListenerCacheTraits = PtrCacheTraitsT< FrameListener, castor::String >
using FrameListenerCache = castor::ResourceCacheT< FrameListener, castor::String, FrameListenerCacheTraits >
using FrameListenerRes = FrameListenerCacheTraits::ElementPtrT
using FrameListenerResPtr = FrameListenerCacheTraits::ElementObsT
C3D_API castor::String getName (EventType value)
CU_DeclareSmartPtr (castor3d, CpuFrameEvent, C3D_API)
CU_DeclareSmartPtr (castor3d, FrameListener, C3D_API)
CU_DeclareSmartPtr (castor3d, GpuFrameEvent, C3D_API)
CU_DeclareSmartPtr (castor3d, CpuFunctorEvent, C3D_API)
CU_DeclareSmartPtr (castor3d, GpuFunctorEvent, C3D_API)
CU_DeclareVector (CpuFrameEventUPtr, CpuFrameEventPtr)
CU_DeclareVector (GpuFrameEventUPtr, GpuFrameEventPtr)
CU_DeclareSmartPtr (castor3d, FrameListenerCache, C3D_API)
UserInput
enum class UserInputEventType {
eMouse , eKeyboard , eHandler , eCount ,
eMin = eMouse , eMax =eCount-1
}
Supported events types enumeration.
enum class MouseEventType : uint8_t {
eMove , eEnter , eHover , eLeave ,
ePushed , eReleased , eWheel , eCount ,
eMin = eMove , eMax =eCount-1
}
Enumeration of supported mouse events.
enum class KeyboardEventType : uint8_t {
ePushed , eReleased , eChar , eCount ,
eMin = ePushed , eMax =eCount-1
}
Enumeration of supported keyboard events.
enum class HandlerEventType : uint8_t {
eActivate , eDeactivate , eCount , eMin = eActivate ,
eMax =eCount-1
}
Enumeration of supported handler events.
enum class MouseButton {
eLeft , eMiddle , eRight , eCount ,
eMin = eLeft , eMax =eCount-1
}
Mouse buttons enumeration.
enum class MouseCursor {
eArrow , eHand , eText , eSizeWE ,
eSizeNS , eSizeNWSE , eSizeNESW , eCount ,
eMin = eArrow , eMax =eCount-1
}
Mouse cursors enumeration.
enum class KeyboardKey {
eNone , eBackspace = 0x08 , eTab = 0x0A , eReturn = 0x0D ,
eEscape = 0x1B , eSpace = 0x20 , eAsciiBegin = eSpace , eDelete = 0x7F ,
eAsciiEnd = 0xFF , eStart = 0x100 , eLButton , eRButton ,
eCancel , eMButton , eClear , eShift ,
eAlt , eControl , eMenu , ePause ,
eCapital , eEnd , eHome , eLeft ,
eUp , eRight , eDown , eSelect ,
ePrint , eExecute , eSnapshot , eInsert ,
eHelp , eNumpad0 , eNumpad1 , eNumpad2 ,
eNumpad3 , eNumpad4 , eNumpad5 , eNumpad6 ,
eNumpad7 , eNumpad8 , eNumpad9 , eMultiply ,
eAdd , eSeparator , eSubtract , eDecimal ,
eDivide , eF1 , eF2 , eF3 ,
eF4 , eF5 , eF6 , eF7 ,
eF8 , eF9 , eF10 , eF11 ,
eF12 , eF13 , eF14 , eF15 ,
eF16 , eF17 , eF18 , eF19 ,
eF20 , eF21 , eF22 , eF23 ,
eF24 , eNumlock , eScroll , ePageUp ,
ePageDown , eNumpadSpace , eNumpadTab , eNumpadEnter ,
eNumpadF1 , eNumpadF2 , eNumpadF3 , eNumpadF4 ,
eNumpadHome , eNumpadLeft , eNumpadUp , eNumpadRight ,
eNumpadDown , eNumpadPageUp , eNumpadPageDown , eNumpadEnd ,
eNumpadBegin , eNumpadInsert , eNumpadDelete , eNumpadEqual ,
eNumpadMultiply , eNumpadAdd , eNumpadSeparator , eNumpadSubtract ,
eNumpadDecimal , eNumpadDivide
}
Keyboard keys enumeration.
using UserInputEventSPtr = std::shared_ptr< UserInputEvent >
using KeyboardEventSPtr = std::shared_ptr< KeyboardEvent >
using MouseEventSPtr = std::shared_ptr< MouseEvent >
using HandlerEventSPtr = std::shared_ptr< HandlerEvent >
C3D_API castor::String getName (UserInputEventType value)
C3D_API castor::String getName (MouseEventType value)
C3D_API castor::String getName (KeyboardEventType value)
C3D_API castor::String getName (HandlerEventType value)
C3D_API castor::String getName (MouseButton value)
CU_DeclareSmartPtr (castor3d, EventHandler, C3D_API)
CU_DeclareSmartPtr (castor3d, UserInputListener, C3D_API)
Material
enum class TextureFlag : uint8_t { eNone = 0x00u , eAll = 0xFFu }
Texture flags.
enum class PassFlag : uint16_t { eNone = 0x0000 , eAll = 0xFFu }
Pass specific flags.
using TextureFlags = castor::FlagCombination< TextureFlag >
using PassComponentID = uint16_t
using TextureCombineID = uint16_t
using PassComponentTextureFlag = uint32_t
using TextureFlagsSet = std::set< PassComponentTextureFlag >
using PassFlags = castor::FlagCombination< PassFlag >
using PassComponentCombineID = uint16_t
using PassComponentFlag = uint32_t
using PassComponentFlagsSet = std::set< PassComponentFlag >
using PassTypeID = uint16_t
using OnMaterialChangedFunction = std::function< void(Material const &) >
using OnMaterialChanged = castor::SignalT< OnMaterialChangedFunction >
using OnMaterialChangedConnection = OnMaterialChanged::connection
using MaterialCacheTraits = PtrCacheTraitsT< Material, castor::String >
using MaterialCache = castor::ResourceCacheT< Material, castor::String, MaterialCacheTraits >
using MaterialPtr = MaterialCacheTraits::ElementPtrT
using MaterialObs = MaterialCacheTraits::ElementObsT
PassComponentTextureFlag makeTextureFlag (PassComponentID componentId, TextureFlags componentTextureFlag)
std::pair< PassComponentID, TextureFlags > splitTextureFlag (PassComponentTextureFlag flag)
PassComponentFlag makePassComponentFlag (PassComponentID componentId, PassFlags componentTextureFlag)
std::pair< PassComponentID, PassFlags > splitPassComponentFlag (PassComponentFlag flag)
CU_DeclareSmartPtr (castor3d, Material, C3D_API)
CU_DeclareSmartPtr (castor3d, MaterialImporter, C3D_API)
CU_DeclareSmartPtr (castor3d, MaterialImporterFactory, C3D_API)
C3D_API VkFormat convert (castor::PixelFormat format)
C3D_API castor::PixelFormat convert (VkFormat format)
CU_DeclareSmartPtr (castor3d, MaterialCache, C3D_API)
CU_DeclareVector (MaterialObs, MaterialPtr)
Material pointer array.
CU_DeclareMap (castor::String, MaterialObs, MaterialPtrStr)
Material pointer map, sorted by name.
CU_DeclareMap (uint32_t, MaterialObs, MaterialPtrUInt)
Material pointer map.
C3D_API bool operator== (TextureCombine const &lhs, TextureCombine const &rhs)
C3D_API TextureFlagsSet::const_iterator checkFlag (TextureCombine const &lhs, PassComponentTextureFlag rhs)
C3D_API bool hasAny (TextureFlagsSet const &lhs, PassComponentTextureFlag rhs)
C3D_API bool hasAny (TextureCombine const &lhs, PassComponentTextureFlag rhs)
C3D_API bool hasIntersect (PassComponentTextureFlag lhs, PassComponentTextureFlag rhs)
C3D_API void remFlags (TextureCombine &lhs, PassComponentTextureFlag rhs)
C3D_API void remFlags (TextureCombine &lhs, TextureFlagsSet const &rhs)
C3D_API void addFlags (TextureCombine &lhs, PassComponentTextureFlag rhs)
C3D_API void addFlags (TextureCombine &lhs, TextureFlagsSet const &rhs)
C3D_API bool contains (TextureCombine const &cont, TextureCombine const &test)
Component
enum class ComponentMode : uint16_t {
eNone , eOpacity , eAlphaBlending , eNormals ,
eGeometry , eColour , eDiffuseLighting , eSpecularLighting ,
eSpecifics , eDerivTex , eOcclusion , eCount ,
eMin = eNone , eMax =eCount-1
}
enum class ComponentModeFlag : uint16_t {
eNone = 0x0000u , eOpacity = 0x0001u << uint16_t(ComponentMode::eOpacity) , eAlphaBlending = 0x0001u << uint16_t(ComponentMode::eAlphaBlending) , eNormals = 0x0001u << uint16_t(ComponentMode::eNormals) ,
eGeometry = 0x0001u << uint16_t(ComponentMode::eGeometry) , eColour = 0x0001u << uint16_t(ComponentMode::eColour) , eDiffuseLighting = 0x0001u << uint16_t(ComponentMode::eDiffuseLighting) , eSpecularLighting = 0x0001u << uint16_t(ComponentMode::eSpecularLighting) ,
eSpecifics = 0x0001u << uint16_t(ComponentMode::eSpecifics) , eDerivTex = 0x0001u << uint16_t(ComponentMode::eDerivTex) , eOcclusion = 0x0001u << uint16_t(ComponentMode::eOcclusion) , eAll = ((0x0001u << uint16_t(ComponentMode::eCount)) - 1u)
}
using ComponentModeFlags = castor::FlagCombination< ComponentModeFlag >
using NormalsComponent = BaseDataComponentT< SubmeshFlag::eNormals >
The submesh component holding normals.
using PositionsComponent = BaseDataComponentT< SubmeshFlag::ePositions >
The submesh component holding positions.
using TangentsComponent = BaseDataComponentT< SubmeshFlag::eTangents >
The submesh component holding tangents.
using Texcoords0Component = BaseDataComponentT< SubmeshFlag::eTexcoords0 >
The submesh component holding texture coordinates.
using Texcoords1Component = BaseDataComponentT< SubmeshFlag::eTexcoords1 >
The submesh component holding texture coordinates.
using Texcoords2Component = BaseDataComponentT< SubmeshFlag::eTexcoords2 >
The submesh component holding texture coordinates.
using Texcoords3Component = BaseDataComponentT< SubmeshFlag::eTexcoords3 >
The submesh component holding texture coordinates.
using ColoursComponent = BaseDataComponentT< SubmeshFlag::eColours >
The submesh component holding colours.
CU_DeclareSmartPtr (castor3d, IndexMapping, C3D_API)
CU_DeclareSmartPtr (castor3d, InstantiationComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, LinesMapping, C3D_API)
CU_DeclareSmartPtr (castor3d, MeshletComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, MorphComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, PassMasksComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, SkinComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, SubmeshComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, TriFaceMapping, C3D_API)
CU_DeclareEnumTemplateSmartPtr (castor3d, BaseDataComponent, castor3d::SubmeshFlag)
CU_DeclareVector (Face, Face)
Face array.
CU_DeclareMap (uint32_t, SubmeshComponentUPtr, SubmeshComponentID)
Pass
enum class ParallaxOcclusionMode {
eNone , eOne , eRepeat , eCount ,
eMin = eNone , eMax =eCount-1
}
Parallax occlusion modes enumeration.
enum class BlendMode : uint8_t {
eNoBlend , eAdditive , eMultiplicative , eInterpolative ,
eABuffer , eDepthPeeling , eCount , eMin = eNoBlend ,
eMax =eCount-1
}
Blending modes enumeration.
using OnPassChangedFunction = std::function< void(Pass const &pass, PassComponentCombineID oldComponents, PassComponentCombineID newComponents) >
using OnPassChanged = castor::SignalT< OnPassChangedFunction >
using OnPassChangedConnection = OnPassChanged::connection
using PassCreator = std::function< PassUPtr(LightingModelID, Material &) >
using PassFactoryBase = castor::Factory< Pass, LightingModelID, PassUPtr, PassCreator, PassTypeID, PassFactoryEntry >
using SpecificsBuffers = std::map< std::string, std::pair< SpecificsBuffer, ShaderBufferUPtr > >
C3D_API castor::String getName (ParallaxOcclusionMode value)
C3D_API castor::String getName (BlendMode value)
CU_DeclareSmartPtr (castor3d, Pass, C3D_API)
CU_DeclareSmartPtr (castor3d, PassFactory, C3D_API)
CU_DeclareSmartPtr (castor3d, SubsurfaceScattering, C3D_API)
CU_DeclareVector (Pass, Pass)
Pass array.
CU_DeclareVector (PassUPtr, PassPtr)
Pass pointer array.
CU_DeclareSmartPtr (castor3d, RenderPassRegisterInfo, C3D_API)
Texture
enum class TextureSpace : uint16_t {
eNone = 0x0000 , eNormalised = 0x0001 << 0 , eYInverted = 0x0001 << 1 , eColour = 0x0001 << 2 ,
eDepth = 0x0001 << 3 , eTangentSpace = 0x0001 << 4 , eObjectSpace = 0x0001 << 5 , eWorldSpace = 0x0001 << 6 ,
eViewSpace = 0x0001 << 7 , eClipSpace = 0x0001 << 8 , eStencil = 0x0001 << 9 , eAllowSRGB = 0x0001 << 10
}
Lists the possible spaces for a texture.
enum class CubeMapFace : uint8_t {
ePositiveX , eNegativeX , ePositiveY , eNegativeY ,
ePositiveZ , eNegativeZ , eCount , eMin = ePositiveX ,
eMax =eCount-1
}
Cube map faces.
using TextureSpaces = castor::FlagCombination< TextureSpace >
using TextureFlagConfigurations = std::array< TextureFlagConfiguration, 4u >
using TextureUnitDatas = std::vector< TextureUnitDataUPtr >
using TextureUnitDataRefs = std::vector< TextureUnitDataRPtr >
using TextureUnitDataSet = std::map< PassComponentTextureFlag, TextureUnitDataRPtr >
using OnTextureUnitChangedFunction = std::function< void(TextureUnit const &) >
using OnTextureUnitChanged = castor::SignalT< OnTextureUnitChangedFunction >
using OnTextureUnitChangedConnection = OnTextureUnitChanged::connection
using SamplerCacheTraits = PtrCacheTraitsT< Sampler, castor::String >
using SamplerCache = castor::ResourceCacheT< Sampler, castor::String, SamplerCacheTraits >
using SamplerPtr = SamplerCacheTraits::ElementPtrT
using SamplerObs = SamplerCacheTraits::ElementObsT
C3D_API castor::String getName (TextureSpace value)
C3D_API castor::String getName (TextureSpaces value)
C3D_API castor::String getName (CubeMapFace value)
CU_DeclareSmartPtr (castor3d, Sampler, C3D_API)
CU_DeclareSmartPtr (castor3d, TextureLayout, C3D_API)
CU_DeclareSmartPtr (castor3d, TextureSource, C3D_API)
CU_DeclareSmartPtr (castor3d, TextureUnit, C3D_API)
CU_DeclareSmartPtr (castor3d, TextureView, C3D_API)
CU_DeclareSmartPtr (castor3d, TextureUnitData, C3D_API)
CU_DeclareVector (TextureUnit, TextureUnit)
TextureUnit array.
std::ostream & operator<< (std::ostream &stream, TextureLayout const &layout)
CU_DeclareSmartPtr (castor3d, SamplerCache, C3D_API)
C3D_API bool operator== (TextureSourceInfo const &lhs, TextureSourceInfo const &rhs) noexcept
bool operator!= (TextureSourceInfo const &lhs, TextureSourceInfo const &rhs) noexcept
CU_DeclareSmartPtr (castor3d, TextureAnimationInstance, C3D_API)
Miscellaneous
enum class GpuFeature : uint32_t {
eStereoRendering = 0x00000001 , eShaderStorageBuffers = 0x00000002 , eBindless = 0x00000004 , eGeometry = 0x00000008 ,
eTessellation = 0x00000010 , eRayTracing = 0x00000020 , eMesh = 0x00000040
}
All supported GPU feature flags.
enum class GpuMax : uint32_t {
eTexture1DSize , eTexture2DSize , eTexture3DSize , eTextureCubeSize ,
eTextureLayers , eSamplerLodBias , eClipDistances , eFramebufferWidth ,
eFramebufferHeight , eFramebufferLayers , eFramebufferSamples , eTexelBufferSize ,
eUniformBufferSize , eStorageBufferSize , eViewportWidth , eViewportHeight ,
eViewports , eWorkGroupCountX , eWorkGroupCountY , eWorkGroupCountZ ,
eWorkGroupSizeX , eWorkGroupSizeY , eWorkGroupSizeZ , eWorkGroupInvocations ,
eMeshWorkGroupInvocations , eMeshWorkGroupSizeX , eMeshWorkGroupSizeY , eMeshWorkGroupSizeZ ,
eMeshTotalMemorySize , eMeshOutputVertices , eMeshOutputPrimitives , eDrawMeshTasksCount ,
eTaskWorkGroupInvocations , eTaskWorkGroupSizeX , eTaskWorkGroupSizeY , eTaskWorkGroupSizeZ ,
eTaskTotalMemorySize , eTaskOutputCount , eCount , eMin = eTexture1DSize ,
eMax =eCount-1
}
Maximum values enumerator.
enum class GpuMin : uint32_t {
eBufferMapSize , eUniformBufferOffsetAlignment , eCount , eMin = eBufferMapSize ,
eMax =eCount-1
}
Minimum values enumerator.
using GpuFeatures = castor::FlagCombination< GpuFeature >
using Parameters = ParametersT< castor::String >
CU_DeclareSmartPtr (castor3d, LoadingScreen, C3D_API)
CU_DeclareSmartPtr (castor3d, ProgressBar, C3D_API)
CU_DeclareSmartPtr (castor3d, StagingData, C3D_API)
C3D_API ashes::DeviceMemoryPtr setupMemory (ashes::Device const &device, VkMemoryRequirements const &requirements, VkMemoryPropertyFlags flags, std::string const &name)
C3D_API ashes::DeviceMemoryPtr setupMemory (RenderDevice const &device, VkMemoryRequirements const &requirements, VkMemoryPropertyFlags flags, std::string const &name)
Submesh
enum class SubmeshData : uint8_t {
eIndex , ePositions , eNormals , eTangents ,
eTexcoords0 , eTexcoords1 , eTexcoords2 , eTexcoords3 ,
eColours , eOtherMin , eSkin = eOtherMin , ePassMasks ,
eVelocity , eCount , eMin = eIndex , eMax =eCount-1
}
Lists the supported data kinds for a submesh.
enum class SubmeshFlag : uint16_t {
eNone = 0x0000 , eIndex = 0x0001 << int(SubmeshData::eIndex) , ePositions = 0x0001 << int(SubmeshData::ePositions) , eNormals = 0x0001 << int(SubmeshData::eNormals) ,
eTangents = 0x0001 << int(SubmeshData::eTangents) , eTexcoords0 = 0x0001 << int(SubmeshData::eTexcoords0) , eTexcoords1 = 0x0001 << int(SubmeshData::eTexcoords1) , eTexcoords2 = 0x0001 << int(SubmeshData::eTexcoords2) ,
eTexcoords3 = 0x0001 << int(SubmeshData::eTexcoords3) , eTexcoords = (eTexcoords0 | eTexcoords1 | eTexcoords2 | eTexcoords3) , eColours = 0x0001 << int(SubmeshData::eColours) , ePosNmlTanTex = ePositions | eNormals | eTangents | eTexcoords0 ,
eSkin = 0x0001 << int(SubmeshData::eSkin) , ePassMasks = 0x0001 << int(SubmeshData::ePassMasks) , eVelocity = 0x0001 << int(SubmeshData::eVelocity) , eAllBase = (0x0001 << int(SubmeshData::eCount)) - 1
}
Flags to determine what a submesh is using.
enum class MorphData : uint32_t {
ePositions , eNormals , eTangents , eTexcoords0 ,
eTexcoords1 , eTexcoords2 , eTexcoords3 , eColours ,
eCount , eMin = ePositions , eMax =eCount-1
}
Lists the supported morphing kinds for a submesh.
enum class MorphFlag : uint32_t {
eNone , ePositions = 0x01 << size_t(MorphData::ePositions) , eNormals = 0x01 << size_t(MorphData::eNormals) , eTangents = 0x01 << size_t(MorphData::eTangents) ,
eTexcoords0 = 0x01 << size_t(MorphData::eTexcoords0) , eTexcoords1 = 0x01 << size_t(MorphData::eTexcoords1) , eTexcoords2 = 0x01 << size_t(MorphData::eTexcoords2) , eTexcoords3 = 0x01 << size_t(MorphData::eTexcoords3) ,
eColours = 0x01 << size_t(MorphData::eColours) , eAllBase = (0x0001 << int(MorphData::eCount)) - 1
}
Flags to determine what morphing is enabled on a submesh.
using SubmeshFlags = castor::FlagCombination< SubmeshFlag >
using MorphFlags = castor::FlagCombination< MorphFlag >
using SubmeshBoundingBoxList = std::vector< std::pair< Submesh const *, castor::BoundingBox > >
castor::String getName (SubmeshData value)
constexpr uint32_t getSize (SubmeshData value)
static constexpr SubmeshData getData (SubmeshFlag value)
static constexpr uint32_t getIndex (SubmeshFlag value)
castor::String getName (MorphData value)
CU_DeclareSmartPtr (castor3d, Submesh, C3D_API)
CU_DeclareVector (SubmeshUPtr, SubmeshPtr)
Submesh pointer array.
CU_DeclareMap (Submesh const *, castor::BoundingBox, SubmeshBoundingBox)
CU_DeclareMap (Submesh const *, castor::BoundingSphere, SubmeshBoundingSphere)
CU_DeclareMap (uint32_t, std::vector< float >, SubmeshTargetWeight)
Skeleton
enum class SkeletonNodeType {
eNode , eBone , eCount , eMin = eNode ,
eMax =eCount-1
}
Skeleton node types enumeration.
using TransformArray = std::vector< ObjectTransform >
using SkeletonAnimationObjectArray = std::vector< SkeletonAnimationObjectRPtr >
using SkeletonCacheTraits = PtrCacheTraitsT< Skeleton, castor::String >
using SkeletonCache = castor::ResourceCacheT< Skeleton, castor::String, SkeletonCacheTraits >
using SkeletonRes = SkeletonCacheTraits::ElementPtrT
using SkeletonResPtr = SkeletonCacheTraits::ElementObsT
CU_DeclareSmartPtr (castor3d, SkeletonAnimation, C3D_API)
CU_DeclareSmartPtr (castor3d, SkeletonAnimationKeyFrame, C3D_API)
CU_DeclareSmartPtr (castor3d, SkeletonAnimationObject, C3D_API)
CU_DeclareSmartPtr (castor3d, SkeletonAnimationBone, C3D_API)
CU_DeclareSmartPtr (castor3d, SkeletonAnimationNode, C3D_API)
C3D_API castor::String getName (SkeletonNodeType value)
CU_DeclareSmartPtr (castor3d, BoneNode, C3D_API)
CU_DeclareSmartPtr (castor3d, SkeletonNode, C3D_API)
CU_DeclareSmartPtr (castor3d, Skeleton, C3D_API)
CU_DeclareSmartPtr (castor3d, SkeletonCache, C3D_API)
CU_DeclareSmartPtr (castor3d, SkeletonImporter, C3D_API)
CU_DeclareSmartPtr (castor3d, SkeletonImporterFactory, C3D_API)
CU_DeclareVector (VertexBoneData, VertexBoneData)
Skinned vertex data array.
CU_DeclareVector (SkeletonNodeUPtr, SkeletonNodePtr)
Bone pointer array.
CU_DeclareSmartPtr (castor3d, SkeletonAnimationInstance, C3D_API)
CU_DeclareSmartPtr (castor3d, SkeletonAnimationInstanceBone, C3D_API)
CU_DeclareSmartPtr (castor3d, SkeletonAnimationInstanceNode, C3D_API)
CU_DeclareSmartPtr (castor3d, SkeletonAnimationInstanceObject, C3D_API)
CU_DeclareVector (SkeletonAnimationInstanceObjectUPtr, SkeletonAnimationInstanceObjectPtr)
SkeletonAnimationInstanceObject pointer array.
Overlay
enum class OverlayType : uint8_t {
ePanel , eBorderPanel , eText , eCount ,
eMin = ePanel , eMax =eCount-1
}
Overlay types enumeration.
enum class TextWrappingMode {
eNone , eBreak , eBreakWords , eCount ,
eMin = eNone , eMax =eCount-1
}
Text wrapping modes, handles the way text is cut when it overflows the overlay width.
enum class TextTexturingMode {
eLetter , eText , eCount , eMin = eLetter ,
eMax =eCount-1
}
Text texturing modes, handles the way textures are appied to text overlays.
enum class TextLineSpacingMode {
eOwnHeight , eMaxLineHeight , eMaxFontHeight , eCount ,
eMin = eOwnHeight , eMax =eCount-1
}
Text line spacing modes, handles the way lines are spaced, which each other, inside one TextOverlay.
enum class HAlign {
eLeft , eCenter , eRight , eCount ,
eMin = eLeft , eMax =eCount-1
}
Horizontal alignments for text overlays.
enum class VAlign {
eTop , eCenter , eBottom , eCount ,
eMin = eTop , eMax =eCount-1
}
Vertical alignments for text overlays.
enum class BorderPosition {
eInternal , eMiddle , eExternal , eCount ,
eMin = eInternal , eMax =eCount-1
}
Text wrapping modes, handles the way text is cut when it overflows the overlay width.
using OverlayCacheTraits = PtrCacheTraitsT< Overlay, castor::String >
using OverlayCache = castor::ResourceCacheT< Overlay, castor::String, OverlayCacheTraits >
using OverlayRes = OverlayCacheTraits::ElementPtrT
using OverlayResPtr = OverlayCacheTraits::ElementObsT
C3D_API castor::String getName (OverlayType value)
C3D_API castor::String getName (TextWrappingMode value)
C3D_API castor::String getName (TextTexturingMode value)
C3D_API castor::String getName (TextLineSpacingMode value)
C3D_API castor::String getName (HAlign value)
C3D_API castor::String getName (VAlign value)
C3D_API castor::String getName (BorderPosition value)
CU_DeclareSmartPtr (castor3d, BorderPanelOverlay, C3D_API)
CU_DeclareSmartPtr (castor3d, DebugOverlays, C3D_API)
CU_DeclareSmartPtr (castor3d, FontTexture, C3D_API)
CU_DeclareSmartPtr (castor3d, Overlay, C3D_API)
CU_DeclareSmartPtr (castor3d, OverlayCategory, C3D_API)
CU_DeclareSmartPtr (castor3d, OverlayFactory, C3D_API)
CU_DeclareSmartPtr (castor3d, PanelOverlay, C3D_API)
CU_DeclareSmartPtr (castor3d, TextOverlay, C3D_API)
CU_DeclareSmartPtr (castor3d, OverlayCache, C3D_API)
CU_DeclareVector (OverlayRPtr, OverlayPtr)
CU_DeclareMap (castor::String, OverlayResPtr, OverlayPtrStr)
Plugin
enum class PluginType : uint8_t {
eImporter , eDivider , eGenerator , eToneMapping ,
ePostEffect , eGeneric , eParticle , eCount ,
eMin = eImporter , eMax =eCount-1
}
Plugin types enumeration.
using PluginCacheTraits = PtrCacheTraitsT< Plugin, castor::String >
using PluginCache = castor::ResourceCacheT< Plugin, castor::String, PluginCacheTraits >
using PluginRes = PluginCacheTraits::ElementPtrT
using PluginResPtr = PluginCacheTraits::ElementObsT
CU_DeclareSmartPtr (castor3d, Plugin, C3D_API)
CU_DeclareSmartPtr (castor3d, ImporterPlugin, C3D_API)
CU_DeclareSmartPtr (castor3d, DividerPlugin, C3D_API)
CU_DeclareSmartPtr (castor3d, GeneratorPlugin, C3D_API)
CU_DeclareSmartPtr (castor3d, GenericPlugin, C3D_API)
CU_DeclareSmartPtr (castor3d, PostFxPlugin, C3D_API)
CU_DeclareSmartPtr (castor3d, ParticlePlugin, C3D_API)
CU_DeclareSmartPtr (castor3d, ToneMappingPlugin, C3D_API)
CU_DeclareMap (castor::String, PluginUPtr, PluginStr)
CU_DeclareArray (PluginStrMap, PluginType::eCount, PluginStrMap)
CU_DeclareMap (castor::Path, PluginType, PluginTypePath)
CU_DeclareSmartPtr (castor3d, PluginCache, C3D_API)
Global Illumination
enum class GlobalIlluminationType : uint8_t {
eNone , eRsm , eVoxelConeTracing , eLpv ,
eLpvG , eLayeredLpv , eLayeredLpvG , eCount ,
eMin = eNone , eMax =eCount-1
}
Enumerator of supported global illumination algorithms.
C3D_API castor::String getName (GlobalIlluminationType giType)
Light Propagation Volumes
enum class LpvTexture : uint8_t {
eR , eG , eB , eCount ,
eMin = eR , eMax =eCount-1
}
Enumerator of textures used by the light volume GI passes.
using LayeredLightPropagationVolumes = LayeredLightPropagationVolumesT< false >
using LayeredLightPropagationVolumesG = LayeredLightPropagationVolumesT< true >
using LightPropagationVolumes = LightPropagationVolumesT< false >
using LightPropagationVolumesG = LightPropagationVolumesT< true >
using LightPropagationVolumesLightType = std::array< LightPropagationVolumesUPtr, size_t(LightType::eCount) >
using LayeredLightPropagationVolumesLightType = std::array< LayeredLightPropagationVolumesUPtr, size_t(LightType::eCount) >
using LightPropagationVolumesGLightType = std::array< LightPropagationVolumesGUPtr, size_t(LightType::eCount) >
using LayeredLightPropagationVolumesGLightType = std::array< LayeredLightPropagationVolumesGUPtr, size_t(LightType::eCount) >
C3D_API castor::String getTextureName (LpvTexture texture, std::string const &infix)
C3D_API castor::String getTexName (LpvTexture texture)
C3D_API VkFormat getFormat (RenderDevice const &device, LpvTexture texture)
C3D_API VkClearValue getClearValue (LpvTexture texture)
C3D_API VkImageUsageFlags getUsageFlags (LpvTexture texture)
C3D_API VkBorderColor getBorderColor (LpvTexture texture)
uint32_t getMipLevels (RenderDevice const &device, LpvTexture texture, castor::Size const &size)
uint32_t getMipLevels (RenderDevice const &device, LpvTexture texture, VkExtent3D const &size)
VkCompareOp getCompareOp (LpvTexture texture)
CU_DeclareSmartPtr (castor3d, GeometryInjectionPass, C3D_API)
CU_DeclareSmartPtr (castor3d, LayeredLightPropagationVolumes, C3D_API)
CU_DeclareSmartPtr (castor3d, LayeredLightPropagationVolumesG, C3D_API)
CU_DeclareSmartPtr (castor3d, LightInjectionPass, C3D_API)
CU_DeclareSmartPtr (castor3d, LightPropagationPass, C3D_API)
CU_DeclareSmartPtr (castor3d, LightPropagationVolumes, C3D_API)
CU_DeclareSmartPtr (castor3d, LightPropagationVolumesG, C3D_API)
CU_DeclareSmartPtr (castor3d, LightVolumePassResult, C3D_API)
CU_DeclareVector (GeometryInjectionPass, GeometryInjectionPass)
CU_DeclareVector (LightInjectionPass, LightInjectionPass)
CU_DeclareVector (LightVolumePassResultUPtr, LightVolumePassResult)
Node
enum class RenderNodeType : uint8_t {
eFrontSubmesh , eFrontSubmeshMeshlet , eFrontSubmeshInstanced , eFrontBillboard ,
eBackSubmesh , eBackSubmeshMeshlet , eBackSubmeshInstanced , eBackBillboard ,
eCount , eMin = eFrontSubmesh , eMax =eCount-1
}
using PipelineBuffer = std::pair< PipelineBaseHash, ashes::BufferBase const * >
RenderNodeType getRenderNodeType (ProgramFlags const &flags)
CU_DeclareSmartPtr (castor3d, BillboardRenderNode, C3D_API)
CU_DeclareSmartPtr (castor3d, SubmeshRenderNode, C3D_API)
CU_DeclareSmartPtr (castor3d, QueueRenderNodes, C3D_API)
CU_DeclareSmartPtr (castor3d, SceneRenderNodes, C3D_API)
Lighting
enum class LightPassIdx : uint32_t {
eMaterials , eSssProfiles , eModels , eCamera ,
eDepthObj , eNmlOcc , eColMtl , eSpcRgh ,
eEmsTrn , eClrCot , eCrTsIr , eSheen ,
eCount
}
The lighting passes common bindings index.
enum class LightPassLgtIdx : uint32_t {
eLights , eMatrix , eModelMatrix , eSmLinear ,
eSmLinearCmp , eSmVariance , eRandomStorage , eCount
}
The lighting passes light specific bindings index.
enum class LpTexture : uint8_t {
eDiffuse , eSpecular , eScattering , eCoatingSpecular ,
eSheen , eIndirectDiffuse , eIndirectSpecular , eCount ,
eMin = eDiffuse , eMax =eCount-1
}
Enumerator of textures used by the lighting pass in deferred rendering.
castor::String getTextureName (LpTexture texture)
castor::String getTexName (LpTexture texture)
VkFormat getFormat (RenderDevice const &device, LpTexture texture)
VkClearValue getClearValue (LpTexture texture)
VkImageUsageFlags getUsageFlags (LpTexture texture)
VkBorderColor getBorderColor (LpTexture texture)
uint32_t getMipLevels (RenderDevice const &device, LpTexture texture, castor::Size const &size)
uint32_t getMipLevels (RenderDevice const &device, LpTexture texture, VkExtent3D const &size)
VkCompareOp getCompareOp (LpTexture texture)
float getMaxDistance (LightCategory const &light, castor::Point3f const &attenuation)
Retrieve the maximum litten distance for given light and attenuation.
float getMaxDistance (LightCategory const &light, castor::Point3f const &attenuation, float max)
Retrieve the maximum litten distance for given light and attenuation.
CU_DeclareSmartPtr (castor3d, SubsurfaceScatteringPass, C3D_API)
Opaque
enum class DsTexture : uint8_t {
eNmlOcc , eColMtl , eSpcRgh , eEmsTrn ,
eClrCot , eCrTsIr , eSheen , eCount ,
eMin = eNmlOcc , eMax =eCount-1
}
Enumerator of textures used by the deferred renderer's GBUffer.
C3D_API castor::String getTextureName (DsTexture texture)
C3D_API castor::String getImageName (DsTexture texture)
C3D_API castor::String getTexName (DsTexture texture)
C3D_API VkFormat getFormat (RenderDevice const &device, DsTexture texture)
C3D_API VkClearValue getClearValue (DsTexture texture)
C3D_API VkImageUsageFlags getUsageFlags (DsTexture texture)
C3D_API VkBorderColor getBorderColor (DsTexture texture)
uint32_t getMipLevels (RenderDevice const &device, DsTexture texture, castor::Size const &size)
VkCompareOp getCompareOp (DsTexture texture)
CU_DeclareSmartPtr (castor3d, DeferredRendering, C3D_API)
CU_DeclareSmartPtr (castor3d, IndirectLightingPass, C3D_API)
CU_DeclareSmartPtr (castor3d, LightingPass, C3D_API)
CU_DeclareSmartPtr (castor3d, OpaquePassResult, C3D_API)
CU_DeclareSmartPtr (castor3d, OpaqueRendering, C3D_API)
CU_DeclareSmartPtr (castor3d, OpaqueResolvePass, C3D_API)
CU_DeclareSmartPtr (castor3d, VisibilityReorderPass, C3D_API)
Prepass
enum class PpTexture : uint8_t {
eDepthObj , eVisibility , eCount , eMin = eDepthObj ,
eMax =eCount-1
}
Enumerator of textures used by the deferred renderer's GBUffer.
C3D_API castor::String getTextureName (PpTexture texture)
C3D_API castor::String getTexName (PpTexture texture)
C3D_API VkFormat getFormat (RenderDevice const &device, PpTexture texture)
C3D_API VkClearValue getClearValue (PpTexture texture)
C3D_API VkImageUsageFlags getUsageFlags (PpTexture texture)
C3D_API VkBorderColor getBorderColor (PpTexture texture)
uint32_t getMipLevels (RenderDevice const &device, PpTexture texture, castor::Size const &size)
VkCompareOp getCompareOp (PpTexture texture)
CU_DeclareSmartPtr (castor3d, DepthPass, C3D_API)
CU_DeclareSmartPtr (castor3d, PrepassRendering, C3D_API)
CU_DeclareSmartPtr (castor3d, PrepassResult, C3D_API)
CU_DeclareSmartPtr (castor3d, VisibilityPass, C3D_API)
Render
enum class GlobalBuffersIdx : uint32_t {
eCamera , eScene , eObjectsNodeID , eModelsData ,
eMaterials , eSssProfiles , eTexConfigs , eTexAnims ,
eBillboardsData , eCount , eMin = eCamera , eMax =eCount-1
}
The render pass UBOs binding index.
enum class MeshBuffersIdx : uint32_t {
eMeshlets , eCullData , ePosition , eNormal ,
eTangent , eTexcoord0 , eTexcoord1 , eTexcoord2 ,
eTexcoord3 , eColour , ePassMasks , eVelocity ,
eInstances , eCount , eMin = eMeshlets , eMax =eCount-1
}
The render pass mesh buffers binding index.
enum class FrustumCorner {
eFarLeftBottom , eFarLeftTop , eFarRightTop , eFarRightBottom ,
eNearLeftBottom , eNearLeftTop , eNearRightTop , eNearRightBottom ,
eCount , eMin = eFarLeftBottom , eMax =eCount-1
}
Frustum corners enumeration.
enum class FrustumPlane {
eNear , eFar , eLeft , eRight ,
eTop , eBottom , eCount , eMin = eNear ,
eMax =eCount-1
}
Frustum planes enumeration.
enum class PickNodeType : uint8_t { eNone , eSubmesh , eBillboard }
The picking node types.
enum class TargetType : uint8_t {
eWindow , eTexture , eCount , eMin = eWindow ,
eMax =eCount-1
}
RenderTarget supported types.
enum class ViewportType : uint8_t {
eUndefined , eOrtho , ePerspective , eInfinitePerspective ,
eFrustum , eCount , eMin = eUndefined , eMax =eCount-1
}
The viewport projection types enumeration.
enum class ShaderFlag : uint32_t {
eNone = 0x00000000 , eNormal = 0x00000001 , eTangent = 0x00000002 , eTangentSpace = eTangent | eNormal ,
eVelocity = 0x00000004 , eWorldSpace = 0x00000008 , eViewSpace = 0x00000010 , eDepth = 0x00000020 ,
eVisibility = 0x00000040 , ePicking = 0x00000080 , eLighting = 0x00000100 , eShadowMapDirectional = 0x00000200 ,
eShadowMapSpot = 0x00000400 , eShadowMapPoint = 0x00000800 , eVsmShadowMap = 0x00001000 , eRsmShadowMap = 0x00002000 ,
eEnvironmentMapping = 0x00004000 , eOpacity = 0x00008000 , eGeometry = 0x00010000 , eTessellation = 0x00020000 ,
eForceTexCoords = 0x00040000 , eColour = 0x00080000 , eAll = 0x000FFFFF
}
The render pass shader flags.
enum class RenderFilter : uint8_t {
eNone = 0x00 , eAlphaBlend = 0x01 << 0u , eAlphaTest = 0x01 << 1u , eTransmission = 0x01 << 2u ,
eOpaque = 0x01 << 3u
}
Filters out the opacity channels a render pass doesn't use.
enum class TechniquePassEvent {
eBeforeDepth , eBeforeBackground , eBeforeOpaque , eBeforeTransparent ,
eBeforePostEffects , eCount , eMin = eBeforeDepth , eMax =eCount-1
}
using TexturePtr = std::shared_ptr< Texture >
using TextureArray = std::vector< TexturePtr >
using RenderPassTypeID = uint16_t
using ShaderFlags = castor::FlagCombination< ShaderFlag >
using RenderFilters = castor::FlagCombination< RenderFilter >
using RenderWindowPtr = std::unique_ptr< RenderWindow >
using RenderQueueArray = std::vector< std::reference_wrapper< RenderQueue > >
using ShadowMapRefIds = std::pair< std::reference_wrapper< ShadowMap >, UInt32Array >
using ShadowMapRefArray = std::vector< ShadowMapRefIds >
using ShadowMapLightTypeArray = std::array< ShadowMapRefArray, size_t(LightType::eCount) >
using LightIdArray = std::vector< std::pair< Light *, uint32_t > >
using ShadowMapLightIdArray = std::vector< ShadowMapLightIds >
using ShadowMapLightArray = std::array< ShadowMapLightIdArray, size_t(LightType::eCount) >
using PassSortNodesSignalFunction = std::function< void(RenderNodesPass const &) >
using PassSortNodesSignal = castor::SignalT< PassSortNodesSignalFunction >
using PassSortNodesSignalConnection = castor::ConnectionT< PassSortNodesSignal >
using TechniquePassVector = std::vector< RenderTechniqueNodesPass * >
using TechniquePasses = std::array< TechniquePassVector, size_t(TechniquePassEvent::eCount) >
castor::String const RenderTypeUndefined = cuT("Undefined")
C3D_API castor::String getName (FrustumCorner value)
C3D_API castor::String getName (FrustumPlane value)
C3D_API castor::String getName (PickNodeType value)
C3D_API castor::String getName (TargetType value)
C3D_API castor::String getName (ViewportType value)
C3D_API castor::String getName (RenderFilter value)
CU_DeclareSmartPtr (castor3d, Frustum, C3D_API)
CU_DeclareSmartPtr (castor3d, Picking, C3D_API)
CU_DeclareSmartPtr (castor3d, RenderDevice, C3D_API)
CU_DeclareSmartPtr (castor3d, RenderLoop, C3D_API)
CU_DeclareSmartPtr (castor3d, RenderNodesPass, C3D_API)
CU_DeclareSmartPtr (castor3d, RenderPipeline, C3D_API)
CU_DeclareSmartPtr (castor3d, RenderQueue, C3D_API)
CU_DeclareSmartPtr (castor3d, RenderSystem, C3D_API)
CU_DeclareSmartPtr (castor3d, RenderTarget, C3D_API)
CU_DeclareSmartPtr (castor3d, RenderTechnique, C3D_API)
CU_DeclareSmartPtr (castor3d, RenderTechniquePass, C3D_API)
CU_DeclareSmartPtr (castor3d, RenderWindow, C3D_API)
CU_DeclareSmartPtr (castor3d, Viewport, C3D_API)
CU_DeclareVector (IntermediateView, IntermediateView)
C3D_API uint32_t getSafeBandsSize (castor::Size const &size)
C3D_API uint32_t getSafeBandSize (castor::Size const &size)
C3D_API castor::Size getSafeBandedSize (castor::Size const &size)
C3D_API VkExtent3D getSafeBandedExtent3D (castor::Size const &size)
C3D_API castor::Angle getSafeBandedFovY (castor::Angle const &fovY, castor::Size const &size)
C3D_API float getSafeBandedAspect (float aspect, castor::Size const &size)
C3D_API VkImageMemoryBarrier makeLayoutTransition (VkImage image, VkImageSubresourceRange const &range, VkImageLayout sourceLayout, VkImageLayout destinationLayout, uint32_t srcQueueFamily, uint32_t dstQueueFamily)
C3D_API VkImageMemoryBarrier makeLayoutTransition (VkImage image, VkImageSubresourceRange const &range, VkImageLayout srcLayout, VkImageLayout dstLayout, VkAccessFlags srcAccessFlags, uint32_t srcQueueFamily, uint32_t dstQueueFamily)
C3D_API VkImageMemoryBarrier makeLayoutTransition (VkImage image, VkImageSubresourceRange const &range, VkImageLayout srcLayout, VkImageLayout dstLayout, VkAccessFlags srcAccessFlags, VkAccessFlags dstAccessMask, uint32_t srcQueueFamily, uint32_t dstQueueFamily)
C3D_API void memoryBarrier (crg::RecordContext &context, VkCommandBuffer commandBuffer, ashes::BufferBase const &buffer, crg::BufferSubresourceRange const &range, crg::AccessState after, crg::AccessState before)
C3D_API ashes::Image makeImage (ashes::Device const &device, VkImage image, crg::ImageId data)
C3D_API ashes::Image makeImage (ashes::Device const &device, Texture const &texture)
C3D_API ashes::ImageView makeImageView (ashes::Device const &device, ashes::Image const &image, VkImageView view, crg::ImageViewId data)
C3D_API ashes::ImageView makeTargetImageView (ashes::Device const &device, ashes::Image const &image, Texture const &texture)
C3D_API ashes::ImageView makeSampledImageView (ashes::Device const &device, ashes::Image const &image, Texture const &texture)
C3D_API ashes::ImageView makeWholeImageView (ashes::Device const &device, ashes::Image const &image, Texture const &texture)
C3D_API void printGraph (crg::RunnableGraph const &graph)
C3D_API void bindTexture (VkImageView view, VkSampler sampler, ashes::WriteDescriptorSetArray &writes, uint32_t &index)
Writes the image view and sampler descriptor to the given writes.
C3D_API void bindTexture (ashes::ImageView const &view, ashes::Sampler const &sampler, ashes::WriteDescriptorSetArray &writes, uint32_t &index)
C3D_API void bindTexture (crg::RunnableGraph &graph, crg::ImageViewId const &view, VkSampler const &sampler, ashes::WriteDescriptorSetArray &writes, uint32_t &index)
C3D_API void bindBuffer (VkBuffer buffer, VkDeviceSize offset, VkDeviceSize range, ashes::WriteDescriptorSetArray &writes, uint32_t &index)
Writes the buffer descriptor to the given writes.
C3D_API void bindBuffer (ashes::BufferBase const &buffer, ashes::WriteDescriptorSetArray &writes, uint32_t &index)
C3D_API ashes::WriteDescriptorSet makeImageViewDescriptorWrite (VkImageView const &view, uint32_t dstBinding, uint32_t dstArrayElement=0u)
Creates a descriptor write for storage image.
C3D_API ashes::WriteDescriptorSet makeImageViewDescriptorWrite (VkImageView const &view, VkSampler const &sampler, uint32_t dstBinding, uint32_t dstArrayElement=0u)
Creates a descriptor write for combined image sampler.
C3D_API ashes::WriteDescriptorSet makeDescriptorWrite (ashes::ImageView const &view, uint32_t dstBinding, uint32_t dstArrayElement=0u)
Creates a descriptor write for storage image.
C3D_API ashes::WriteDescriptorSet makeDescriptorWrite (ashes::ImageView const &view, ashes::Sampler const &sampler, uint32_t dstBinding, uint32_t dstArrayElement=0u)
Creates a descriptor write for combined image sampler.
C3D_API ashes::WriteDescriptorSet makeDescriptorWrite (ashes::UniformBuffer const &buffer, uint32_t dstBinding, VkDeviceSize elemOffset, VkDeviceSize elemRange, uint32_t dstArrayElement=0u)
Creates a descriptor write for uniform buffer.
C3D_API ashes::WriteDescriptorSet makeDescriptorWrite (ashes::BufferBase const &storageBuffer, uint32_t dstBinding, VkDeviceSize byteOffset, VkDeviceSize byteRange, uint32_t dstArrayElement=0u)
Creates a descriptor write for storage buffer.
template<typename DataT >
ashes::WriteDescriptorSet makeDescriptorWrite (ashes::Buffer< DataT > const &storageBuffer, uint32_t dstBinding, VkDeviceSize elemOffset, VkDeviceSize elemRange, uint32_t dstArrayElement=0u)
Creates a descriptor write for storage buffer.
C3D_API ashes::WriteDescriptorSet makeDescriptorWrite (ashes::BufferBase const &buffer, ashes::BufferView const &view, uint32_t dstBinding, uint32_t dstArrayElement=0u)
Creates a descriptor write for buffer texel view.
template<typename DataT >
ashes::WriteDescriptorSet makeDescriptorWrite (ashes::Buffer< DataT > const &buffer, ashes::BufferView const &view, uint32_t dstBinding, uint32_t dstArrayElement=0u)
Creates a descriptor write for buffer texel view.
ShadowMap
enum class SmTexture : uint8_t {
eDepth , eLinearDepth , eVariance , eNormal ,
ePosition , eFlux , eCount , eMin = eDepth ,
eMax =eCount-1
}
Enumerator of textures used in deferred rendering.
C3D_API castor::String getTextureName (LightType light, SmTexture texture)
C3D_API castor::String getTexName (SmTexture texture)
C3D_API VkFormat getFormat (RenderDevice const &device, SmTexture texture)
C3D_API VkClearValue getClearValue (SmTexture texture)
C3D_API VkImageUsageFlags getUsageFlags (SmTexture texture)
C3D_API VkBorderColor getBorderColor (SmTexture texture)
C3D_API VkCompareOp getCompareOp (SmTexture texture)
C3D_API uint32_t getMipLevels (RenderDevice const &device, SmTexture texture, castor::Size const &size)
uint32_t getMipLevels (RenderDevice const &device, SmTexture texture, VkExtent3D const &size)
CU_DeclareSmartPtr (castor3d, ShadowMap, C3D_API)
CU_DeclareSmartPtr (castor3d, ShadowMapPass, C3D_API)
Transparent
enum class WbTexture : uint8_t {
eAccumulation , eRevealage , eCount , eMin = eAccumulation ,
eMax =eCount-1
}
Enumerator of textures used in weighted blend OIT.
C3D_API castor::String getTextureName (WbTexture texture)
C3D_API castor::String getTexName (WbTexture texture)
C3D_API VkFormat getFormat (RenderDevice const &device, WbTexture texture)
C3D_API VkClearValue getClearValue (WbTexture texture)
C3D_API VkImageUsageFlags getUsageFlags (WbTexture texture)
C3D_API VkBorderColor getBorderColor (WbTexture texture)
uint32_t getMipLevels (RenderDevice const &device, WbTexture texture, castor::Size const &size)
uint32_t getMipLevels (RenderDevice const &device, WbTexture texture, VkExtent3D const &size)
VkCompareOp getCompareOp (WbTexture texture)
CU_DeclareSmartPtr (castor3d, WeightedBlendRendering, C3D_API)
CU_DeclareSmartPtr (castor3d, TransparentPassResult, C3D_API)
CU_DeclareSmartPtr (castor3d, TransparentRendering, C3D_API)
Light
enum class LightType : uint8_t {
eDirectional , ePoint , eSpot , eCount ,
eMin = eDirectional , eMax =eCount-1
}
Light types enumeration.
using LightCacheTraits = ObjectCacheTraitsT< Light, castor::String >
using LightingModelID = uint8_t
using LightsMap = std::array< LightsArray, size_t(LightType::eCount) >
Array of lights per light type.
using OnLightChangedFunction = std::function< void(Light &) >
using OnLightChanged = castor::SignalT< OnLightChangedFunction >
using OnLightChangedConnection = OnLightChanged::connection
using LightCache = ObjectCacheT< Light, castor::String, LightCacheTraits >
using LightRes = CameraCacheTraits::ElementPtrT
using LightResPtr = CameraCacheTraits::ElementObsT
C3D_API castor::String getName (LightType value)
CU_DeclareSmartPtr (castor3d, Light, C3D_API)
CU_DeclareSmartPtr (castor3d, LightFactory, C3D_API)
CU_DeclareSmartPtr (castor3d, LightCategory, C3D_API)
CU_DeclareSmartPtr (castor3d, LightImporter, C3D_API)
CU_DeclareSmartPtr (castor3d, DirectionalLight, C3D_API)
CU_DeclareSmartPtr (castor3d, PointLight, C3D_API)
CU_DeclareSmartPtr (castor3d, SpotLight, C3D_API)
CU_DeclareVector (LightRPtr, Lights)
Array of lights.
CU_DeclareVector (LightRPtr, LightsRef)
Array to non owning light pointers.
CU_DeclareSmartPtr (castor3d, LightCache, C3D_API)
Particle
enum class ElementUsage : uint32_t {
eUnknown = 0x000 , ePosition = 0x001 , eNormal = 0x002 , eTangent = 0x004 ,
eBitangent = 0x008 , eColour = 0x010 , eTexCoords = 0x020 , eBoneIds0 = 0x040 ,
eBoneIds1 = 0x080 , eBoneWeights0 = 0x100 , eBoneWeights1 = 0x200 , eTransform = 0x400 ,
eMatIndex = 0x800
}
Element usage enumeration.
enum class ParticleFormat {
eInt , eVec2i , eVec3i , eVec4i ,
eUInt , eVec2ui , eVec3ui , eVec4ui ,
eFloat , eVec2f , eVec3f , eVec4f ,
eMat2f , eMat3f , eMat4f , eCount ,
eMin = eInt , eMax =eCount-1
}
using ElementUsages = castor::FlagCombination< ElementUsage >
using ParticleFactory = castor::Factory< CpuParticleSystem, castor::String, CpuParticleSystemUPtr, std::function< CpuParticleSystemUPtr(ParticleSystem &) > >
Particle system factory.
using ParticleValues = ParametersT< size_t >
using ParticleSystemCacheTraits = ObjectCacheTraitsT< ParticleSystem, castor::String >
using ParticleSystemCache = ObjectCacheT< ParticleSystem, castor::String, ParticleSystemCacheTraits >
using ParticleSystemRes = CameraCacheTraits::ElementPtrT
using ParticleSystemResPtr = CameraCacheTraits::ElementObsT
C3D_API castor::String getName (ElementUsage value)
C3D_API castor::String getName (ParticleFormat value)
CU_DeclareSmartPtr (castor3d, CpuParticleSystem, C3D_API)
CU_DeclareSmartPtr (castor3d, ComputeParticleSystem, C3D_API)
CU_DeclareSmartPtr (castor3d, ParticleElementDeclaration, C3D_API)
CU_DeclareSmartPtr (castor3d, ParticleEmitter, C3D_API)
CU_DeclareSmartPtr (castor3d, ParticleSystem, C3D_API)
CU_DeclareSmartPtr (castor3d, ParticleSystemImpl, C3D_API)
CU_DeclareSmartPtr (castor3d, ParticleUpdater, C3D_API)
CU_DeclareSmartPtr (castor3d, ParticleFactory, C3D_API)
CU_DeclareVector (Particle, Particle)
CU_DeclareVector (ParticleEmitterUPtr, ParticleEmitter)
CU_DeclareVector (ParticleUpdaterUPtr, ParticleUpdater)
CU_DeclareSmartPtr (castor3d, ParticleSystemCache, C3D_API)
Scene
enum class MovableType : uint8_t {
eCamera , eGeometry , eLight , eBillboard ,
eParticleEmitter , eCount , eMin = eCamera , eMax =eCount-1
}
Movable object types enumerator.
enum class ShadowType {
eNone , eRaw , ePCF , eVariance ,
eCount , eMin = eNone , eMax =eCount-1
}
Shadow filter types enumeration.
enum class FogType {
eDisabled , eLinear , eExponential , eSquaredExponential ,
eCount , eMin = eDisabled , eMax =eCount-1
}
Fog types enumeration.
enum class SceneFlag : uint16_t {
eNone = 0x0000 , eFogLinear = 0x0001 << 0 , eFogExponential = 0x0001 << 1 , eFogSquaredExponential = 0x0001 << 2 ,
eShadowBegin = 0x0001 << 3 , eShadowDirectional = eShadowBegin << 0 , eShadowPoint = eShadowBegin << 1 , eShadowSpot = eShadowBegin << 2 ,
eShadowEnd = eShadowSpot , eShadowAny = eShadowSpot | eShadowPoint | eShadowDirectional , eLpvGI = 0x0001 << 6 , eLayeredLpvGI = 0x0001 << 7 ,
eVoxelConeTracing = 0x0001 << 8 , eGIAny = eLpvGI | eLayeredLpvGI | eVoxelConeTracing , eAll = 0x01FF
}
Scene flags enumeration.
enum class BillboardType {
eSpherical , eCylindrical , eCount , eMin = eSpherical ,
eMax =eCount-1
}
Billboard rendering types enumeration.
enum class BillboardSize {
eDynamic , eFixed , eCount , eMin = eDynamic ,
eMax =eCount-1
}
Billboard sizing types enumeration.
using SceneFlags = castor::FlagCombination< SceneFlag >
using OnSceneChangedFunction = std::function< void(Scene const &) >
using OnSceneChanged = castor::SignalT< OnSceneChangedFunction >
using OnSceneChangedConnection = OnSceneChanged::connection
using OnSceneUpdateFunction = std::function< void(Scene const &) >
using OnSceneUpdate = castor::SignalT< OnSceneUpdateFunction >
using OnSceneUpdateConnection = OnSceneUpdate::connection
using OnCameraChangedFunction = std::function< void(Camera const &) >
using OnCameraChanged = castor::SignalT< OnCameraChangedFunction >
using OnCameraChangedConnection = OnCameraChanged::connection
using OnSceneNodeChangedFunction = std::function< void(SceneNode const &) >
using OnSceneNodeChanged = castor::SignalT< OnSceneNodeChangedFunction >
using OnSceneNodeChangedConnection = OnSceneNodeChanged::connection
using OnSceneNodeReparentFunction = std::function< void(SceneNode &) >
using OnSceneNodeReparent = castor::SignalT< OnSceneNodeReparentFunction >
using OnSceneNodeReparentConnection = OnSceneNodeReparent::connection
using SubmeshMaterialMap = std::map< Submesh const *, MaterialObs >
using SceneCacheTraits = PtrCacheTraitsT< Scene, castor::String >
using BillboardListCacheTraits = ObjectCacheTraitsT< BillboardList, castor::String >
using CameraCacheTraits = ObjectCacheTraitsT< Camera, castor::String >
using GeometryCacheTraits = ObjectCacheTraitsT< Geometry, castor::String >
using SceneNodeCacheTraits = ObjectCacheTraitsT< SceneNode, castor::String >
using SceneCache = castor::ResourceCacheT< Scene, castor::String, SceneCacheTraits >
using BillboardListCache = ObjectCacheT< BillboardList, castor::String, BillboardListCacheTraits >
using CameraCache = ObjectCacheT< Camera, castor::String, CameraCacheTraits >
using GeometryCache = ObjectCacheT< Geometry, castor::String, GeometryCacheTraits >
using SceneNodeCache = ObjectCacheT< SceneNode, castor::String, SceneNodeCacheTraits >
using SceneRes = SceneCacheTraits::ElementPtrT
using SceneResPtr = SceneCacheTraits::ElementObsT
using BillboardListRes = BillboardListCacheTraits::ElementPtrT
using BillboardListResPtr = BillboardListCacheTraits::ElementObsT
using CameraRes = CameraCacheTraits::ElementPtrT
using CameraResPtr = CameraCacheTraits::ElementObsT
using GeometryRes = CameraCacheTraits::ElementPtrT
using GeometryResPtr = CameraCacheTraits::ElementObsT
using SceneNodeRes = CameraCacheTraits::ElementPtrT
using SceneNodeResPtr = CameraCacheTraits::ElementObsT
using MaterialCacheView = CacheViewT< MaterialCache, EventType::ePreRender >
using SamplerCacheView = CacheViewT< SamplerCache, EventType::ePreRender >
using FontCacheView = CacheViewT< castor::FontCache, EventType::ePreRender >
C3D_API castor::String getName (MovableType value)
C3D_API castor::String getName (ShadowType value)
C3D_API castor::String getName (FogType value)
C3D_API FogType getFogType (SceneFlags const &flags)
Gives the fog type matching the given flags.
C3D_API castor::String getName (BillboardType value)
C3D_API castor::String getName (BillboardSize value)
CU_DeclareSmartPtr (castor3d, BillboardBase, C3D_API)
CU_DeclareSmartPtr (castor3d, BillboardList, C3D_API)
CU_DeclareSmartPtr (castor3d, Camera, C3D_API)
CU_DeclareSmartPtr (castor3d, Geometry, C3D_API)
CU_DeclareSmartPtr (castor3d, MovableObject, C3D_API)
CU_DeclareSmartPtr (castor3d, SceneFileContext, C3D_API)
CU_DeclareSmartPtr (castor3d, SceneFileParser, C3D_API)
CU_DeclareSmartPtr (castor3d, SceneNode, C3D_API)
CU_DeclareSmartPtr (castor3d, Scene, C3D_API)
CU_DeclareSmartPtr (castor3d, SceneImporter, C3D_API)
CU_DeclareSmartPtr (castor3d, SceneNodeImporter, C3D_API)
CU_DeclareVector (SceneNodeRPtr, SceneNodePtr)
SceneNode pointer array.
CU_DeclareMap (castor::String, SceneRPtr, ScenePtrStr)
Scene pointer map, sorted by name.
C3D_API castor::LoggerInstance & getLogger (Scene const &scene)
C3D_API Engine & getEngine (Scene const &scene)
CU_DeclareSmartPtr (castor3d, SceneCache, C3D_API)
CU_DeclareSmartPtr (castor3d, GeometryCache, C3D_API)
CU_DeclareSmartPtr (castor3d, SceneNodeCache, C3D_API)
CU_DeclareSmartPtr (castor3d, MaterialCacheView, C3D_API)
Shader
enum class ProgramFlag : uint16_t {
eNone = 0x0000 , eInstantiation = 0x0001 , eBillboards = 0x0002 , eInvertNormals = 0x0004 ,
eFrontCulled = 0x0008 , eHasMesh = 0x0010 , eAllBase = 0x001F , eHasTask = 0x0020 ,
eAllOptional = 0x0020 , eAll = eAllBase | eAllOptional , eAllVisibility = eFrontCulled | eInvertNormals | eBillboards
}
Flags to use when looking for an automatically generated program.
using ShaderPtr = std::unique_ptr< ast::Shader >
using ProgramFlags = castor::FlagCombination< ProgramFlag >
CU_DeclareSmartPtr (castor3d, ShaderBuffer, C3D_API)
CU_DeclareSmartPtr (castor3d, ShaderProgram, C3D_API)
CU_DeclareSmartPtr (castor3d, LightingModelFactory, C3D_API)
Buffer
using GpuBufferBuddyAllocator = castor::BuddyAllocatorT< GpuBufferBuddyAllocatorTraits >
using GpuBufferBuddyAllocatorUPtr = std::unique_ptr< GpuBufferBuddyAllocator >
using GpuBuddyBuffer = GpuBufferT< GpuBufferBuddyAllocator >
using GpuLinearBuffer = GpuBufferT< GpuBufferLinearAllocator >
using GpuPackedBuffer = GpuBufferT< GpuBufferPackedAllocator >
using GpuLinearBufferPtr = std::unique_ptr< GpuLinearBuffer >
using GpuPackedBufferPtr = std::unique_ptr< GpuPackedBuffer >
CU_DeclareSmartPtr (castor3d, GpuBufferPool, C3D_API)
CU_DeclareSmartPtr (castor3d, ObjectBufferPool, C3D_API)
CU_DeclareSmartPtr (castor3d, PoolUniformBuffer, C3D_API)
CU_DeclareSmartPtr (castor3d, UniformBufferBase, C3D_API)
CU_DeclareSmartPtr (castor3d, UniformBufferPool, C3D_API)
CU_DeclareSmartPtr (castor3d, VertexBufferPool, C3D_API)
CU_DeclareTemplateSmartPtr (castor3d, UniformBuffer)
bool operator< (MemChunk const &lhs, MemChunk const &rhs)
C3D_API void copyBuffer (ashes::CommandBuffer const &commandBuffer, ashes::BufferBase const &src, ashes::BufferBase const &dst, VkDeviceSize offset, VkDeviceSize size, VkPipelineStageFlags flags)
C3D_API void copyBuffer (ashes::CommandBuffer const &commandBuffer, ashes::BufferBase const &src, ashes::BufferBase const &dst, std::vector< VkBufferCopy > const &regions, VkAccessFlags dstAccessFlags, VkPipelineStageFlags dstPipelineFlags)
C3D_API void updateBuffer (ashes::CommandBuffer const &commandBuffer, castor::ByteArray data, ashes::BufferBase const &dst, std::vector< VkBufferCopy > const &regions, VkAccessFlags dstAccessFlags, VkPipelineStageFlags dstPipelineFlags)
Cache
template<typename ObjT , typename KeyT >
using ObjectPtrT = typename ObjectCacheTraitsT< ObjT, KeyT >::ElementPtrT
template<typename ObjT , typename KeyT >
using ObjectObsT = typename ObjectCacheTraitsT< ObjT, KeyT >::ElementObsT
template<typename ObjT , typename KeyT >
using ObjectContT = typename ObjectCacheTraitsT< ObjT, KeyT >::ElementContT
template<typename ObjT , typename KeyT >
using ObjectInitialiserT = typename ObjectCacheTraitsT< ObjT, KeyT >::ElementInitialiserT
template<typename ObjT , typename KeyT >
using ObjectCleanerT = typename ObjectCacheTraitsT< ObjT, KeyT >::ElementCleanerT
template<typename ObjT , typename KeyT >
using ObjectMergerT = typename ObjectCacheTraitsT< ObjT, KeyT >::ElementMergerT
template<typename ObjT , typename KeyT >
using ObjectAttacherT = typename ObjectCacheTraitsT< ObjT, KeyT >::ElementAttacherT
template<typename ObjT , typename KeyT >
using ObjectDetacherT = typename ObjectCacheTraitsT< ObjT, KeyT >::ElementDetacherT
template<typename ObjT , typename KeyT , typename TraitsT >
using ObjectCachePtrT = castor::UniquePtr< ObjectCacheT< ObjT, KeyT, TraitsT > >
template<typename CacheT , EventType EventT>
using CacheViewPtrT = castor::UniquePtr< CacheViewT< CacheT, EventT > >
CU_DeclareSmartPtr (castor3d, RenderTargetCache, C3D_API)
CU_DeclareSmartPtr (castor3d, ShaderProgramCache, C3D_API)
CU_DeclareSmartPtr (castor3d, TextureUnitCache, C3D_API)
Buffers
using SssProfileChangedFunc = std::function< void(SubsurfaceScatteringComponent const &) >
using OnSssProfileChanged = castor::SignalT< SssProfileChangedFunc >
using OnSssProfileChangedConnection = castor::ConnectionT< OnSssProfileChanged >
using PassComponentsBitset = castor::DynamicBitsetT< uint16_t >
using ComponentConfigFiller = std::function< void(SceneFileContext &parsingContext) >
using ChannelFiller = std::pair< PassComponentTextureFlag, ComponentConfigFiller >
using ChannelFillers = std::map< castor::String, ChannelFiller >
using UpdateComponent = std::function< void(PassComponentRegister const &passComponents, TextureCombine const &combine, shader::BlendComponents &components) >
using FinishComponent = std::function< void(shader::SurfaceBase const &surface, sdw::Vec3 const worldEye, shader::Utils &utils, shader::BlendComponents &components) >
using CreatePassComponentPlugin = std::function< PassComponentPluginUPtr(PassComponentRegister const &) >
using GpuDataBufferOffsetPtr = std::unique_ptr< GpuDataBufferOffset >
using GpuDataBufferOffsetModifyFunc = std::function< void(GpuDataBufferOffset const &) >
using GpuDataBufferOffsetModifySignal = castor::SignalT< GpuDataBufferOffsetModifyFunc >
using GpuDataBufferOffsetModifyConnection = castor::ConnectionT< GpuDataBufferOffsetModifySignal >
C3D_API bool operator== (PassComponentCombine const &lhs, PassComponentCombine const &rhs)
C3D_API bool hasAny (PassComponentCombine const &lhs, PassComponentFlag rhs)
C3D_API void remFlags (PassComponentCombine &lhs, PassComponentFlag rhs)
C3D_API void remFlags (PassComponentCombine &lhs, PassComponentFlagsSet const &rhs)
C3D_API void addFlags (PassComponentCombine &lhs, PassComponentFlag rhs)
C3D_API void addFlags (PassComponentCombine &lhs, PassComponentFlagsSet const &rhs)
C3D_API bool contains (PassComponentCombine const &cont, PassComponentFlag test)
C3D_API bool contains (PassComponentCombine const &cont, PassComponentCombine const &test)
CU_DeclareSmartPtr (castor3d, PassComponent, C3D_API)
CU_DeclareSmartPtr (castor3d, PassComponentRegister, C3D_API)
CU_DeclareSmartPtr (castor3d, PassComponentPlugin, C3D_API)
CU_DeclareSmartPtr (castor3d, PassMapComponent, C3D_API)
CU_DeclareMap (PassComponentID, PassComponentUPtr, PassComponent)
C3D_API castor::String const & getPassComponentType (PassComponent const &component)
CU_DeclareSmartPtr (castor3d, FontGlyphBuffer, C3D_API)
CU_DeclareSmartPtr (castor3d, LightBuffer, C3D_API)
CU_DeclareSmartPtr (castor3d, PassBuffer, C3D_API)
CU_DeclareSmartPtr (castor3d, SssProfileBuffer, C3D_API)
CU_DeclareSmartPtr (castor3d, TextureConfigurationBuffer, C3D_API)
CU_DeclareSmartPtr (castor3d, TextureAnimationBuffer, C3D_API)
Mesh
using MeshCacheTraits = ResourceCacheTraitsT< Mesh, castor::String >
using MeshCache = castor::ResourceCacheT< Mesh, castor::String, MeshCacheTraits >
using MeshRes = MeshCacheTraits::ElementPtrT
using MeshResPtr = MeshCacheTraits::ElementObsT
CU_DeclareSmartPtr (castor3d, Mesh, C3D_API)
CU_DeclareSmartPtr (castor3d, MeshFactory, C3D_API)
CU_DeclareSmartPtr (castor3d, MeshGenerator, C3D_API)
CU_DeclareSmartPtr (castor3d, MeshImporter, C3D_API)
CU_DeclareSmartPtr (castor3d, MeshImporterFactory, C3D_API)
CU_DeclareSmartPtr (castor3d, MeshCache, C3D_API)
CU_DeclareMap (castor::String, MeshResPtr, MeshPtrStr)
Mesh pointer array.
CU_DeclareSmartPtr (castor3d, MeshAnimationInstance, C3D_API)
CU_DeclareMap (uint32_t, MeshAnimationInstanceSubmesh, MeshAnimationInstanceSubmesh)
MeshAnimationInstanceSubmesh map, sorted by submesh ID.
Model
using InterleavedVertexArray = std::vector< InterleavedVertex >
CU_DeclareVector (SubmeshVertex, SubmeshVertex)
SubmeshVertex array.
Culling
using SceneCullerSignalFunction = std::function< void(SceneCuller const &) >
using SceneCullerSignal = castor::SignalT< SceneCullerSignalFunction >
using SceneCullerSignalConnection = castor::ConnectionT< SceneCullerSignal >
using PipelineNodes = std::array< uint32_t, MaxNodesPerPipeline >
CU_DeclareSmartPtr (castor3d, SceneCuller, C3D_API)
PostEffect
using PostEffectFactory = castor::Factory< PostEffect, castor::String, PostEffectUPtr, std::function< PostEffectUPtr(RenderTarget &, RenderSystem &, Parameters const &) > >
Post effect factory.
CU_DeclareSmartPtr (castor3d, PostEffect, C3D_API)
ToneMapping
using ToneMappingFactory = castor::Factory< ToneMapping, castor::String, castor3d::ShaderPtr, std::function< castor3d::ShaderPtr() > >
Tone mapping factory.
CU_DeclareSmartPtr (castor3d, ToneMapping, C3D_API)
SceneNode
using GroupAnimationMap = std::map< castor::String, GroupAnimation >
using Animable = AnimableT< Engine >
using Animation = AnimationT< Engine >
using OnAnimatedSkeletonChangeFunction = std::function< void(AnimatedObjectGroup const &, AnimatedSkeleton &) >
using OnAnimatedSkeletonChange = castor::SignalT< OnAnimatedSkeletonChangeFunction >
using OnAnimatedSkeletonChangeConnection = OnAnimatedSkeletonChange::connection
using OnAnimatedMeshChangeFunction = std::function< void(AnimatedObjectGroup const &, AnimatedMesh &) >
using OnAnimatedMeshChange = castor::SignalT< OnAnimatedMeshChangeFunction >
using OnAnimatedMeshChangeConnection = OnAnimatedMeshChange::connection
using OnAnimatedTextureChangeFunction = std::function< void(AnimatedObjectGroup const &, AnimatedTexture &) >
using OnAnimatedTextureChange = castor::SignalT< OnAnimatedTextureChangeFunction >
using OnAnimatedTextureChangeConnection = OnAnimatedTextureChange::connection
using OnAnimatedSceneNodeChangeFunction = std::function< void(AnimatedObjectGroup const &, AnimatedSceneNode &) >
using OnAnimatedSceneNodeChange = castor::SignalT< OnAnimatedSceneNodeChangeFunction >
using OnAnimatedSceneNodeChangeConnection = OnAnimatedSceneNodeChange::connection
using AnimatedObjectGroupCacheTraits = PtrCacheTraitsT< AnimatedObjectGroup, castor::String >
using AnimatedObjectGroupCache = castor::ResourceCacheT< AnimatedObjectGroup, castor::String, AnimatedObjectGroupCacheTraits >
using AnimatedObjectGroupRes = AnimatedObjectGroupCacheTraits::ElementPtrT
using AnimatedObjectGroupResPtr = AnimatedObjectGroupCacheTraits::ElementObsT
CU_DeclareSmartPtr (castor3d, SceneNodeAnimation, C3D_API)
CU_DeclareSmartPtr (castor3d, SceneNodeAnimationKeyFrame, C3D_API)
CU_DeclareSmartPtr (castor3d, Animable, C3D_API)
CU_DeclareSmartPtr (castor3d, AnimatedObjectGroup, C3D_API)
CU_DeclareSmartPtr (castor3d, AnimatedMesh, C3D_API)
CU_DeclareSmartPtr (castor3d, AnimatedObject, C3D_API)
CU_DeclareSmartPtr (castor3d, AnimatedSceneNode, C3D_API)
CU_DeclareSmartPtr (castor3d, AnimatedSkeleton, C3D_API)
CU_DeclareSmartPtr (castor3d, AnimatedTexture, C3D_API)
CU_DeclareSmartPtr (castor3d, Animation, C3D_API)
CU_DeclareSmartPtr (castor3d, AnimationInstance, C3D_API)
CU_DeclareTemplateSmartPtr (castor3d, Animable)
CU_DeclareSmartPtr (castor3d, AnimatedObjectGroupCache, C3D_API)
CU_DeclareSmartPtr (castor3d, SceneNodeAnimationInstance, C3D_API)
Background
using BackgroundModelID = uint8_t
using BackgroundChangedFunc = std::function< void(SceneBackground const &) >
using OnBackgroundChanged = castor::SignalT< BackgroundChangedFunc >
using OnBackgroundChangedConnection = OnBackgroundChanged::connection
CU_DeclareSmartPtr (castor3d, SceneBackground, C3D_API)
CU_DeclareSmartPtr (castor3d, ColourBackground, C3D_API)
CU_DeclareSmartPtr (castor3d, ImageBackground, C3D_API)
CU_DeclareSmartPtr (castor3d, SkyboxBackground, C3D_API)
Typedef Documentation
Animable
using castor3d::Animable = typedef AnimableT< Engine >
AnimatedObjectGroupCache
using castor3d::AnimatedObjectGroupCache = typedef castor::ResourceCacheT< AnimatedObjectGroup , castor::String , AnimatedObjectGroupCacheTraits >
AnimatedObjectGroupCacheTraits
using castor3d::AnimatedObjectGroupCacheTraits = typedef PtrCacheTraitsT< AnimatedObjectGroup, castor::String >
AnimatedObjectGroupRes
using castor3d::AnimatedObjectGroupRes = typedef AnimatedObjectGroupCacheTraits::ElementPtrT
AnimatedObjectGroupResPtr
using castor3d::AnimatedObjectGroupResPtr = typedef AnimatedObjectGroupCacheTraits::ElementObsT
Animation
using castor3d::Animation = typedef AnimationT< Engine >
AnimationKeyFrameArray
using castor3d::AnimationKeyFrameArray = typedef std::vector< AnimationKeyFrameUPtr >
BackgroundChangedFunc
using castor3d::BackgroundChangedFunc = typedef std::function< void(SceneBackground const &) >
BackgroundModelID
using castor3d::BackgroundModelID = typedef uint8_t
BillboardCacheTraits
using castor3d::BillboardCacheTraits = typedef ObjectCacheTraitsT< BillboardList, castor::String >
BillboardListCache
using castor3d::BillboardListCache = typedef ObjectCacheT< BillboardList , castor::String , BillboardListCacheTraits >
BillboardListCacheTraits
using castor3d::BillboardListCacheTraits = typedef ObjectCacheTraitsT< BillboardList, castor::String >
BillboardListRes
using castor3d::BillboardListRes = typedef BillboardListCacheTraits::ElementPtrT
BillboardListResPtr
using castor3d::BillboardListResPtr = typedef BillboardListCacheTraits::ElementObsT
CacheViewPtrT
template<typename CacheT , EventType EventT> using castor3d::CacheViewPtrT = typedef castor::UniquePtr< CacheViewT< CacheT, EventT > >
CacheViewTraitsT
template<typename CacheT > using castor3d::CacheViewTraitsT = typedef typename CacheT::ElementCacheTraitsT
CameraCache
using castor3d::CameraCache = typedef ObjectCacheT< Camera , castor::String , CameraCacheTraits >
CameraCacheTraits
using castor3d::CameraCacheTraits = typedef ObjectCacheTraitsT< Camera, castor::String >
CameraRes
using castor3d::CameraRes = typedef CameraCacheTraits::ElementPtrT
CameraResPtr
using castor3d::CameraResPtr = typedef CameraCacheTraits::ElementObsT
ChannelFiller
using castor3d::ChannelFiller = typedef std::pair< PassComponentTextureFlag, ComponentConfigFiller >
ChannelFillers
using castor3d::ChannelFillers = typedef std::map< castor::String, ChannelFiller >
ColoursComponent
using castor3d::ColoursComponent = typedef BaseDataComponentT< SubmeshFlag::eColours >
The submesh component holding colours.
ComboBoxFlags
using castor3d::ComboBoxFlags = typedef castor::FlagCombination< ComboBoxFlag >
ComponentConfigFiller
using castor3d::ComponentConfigFiller = typedef std::function< void(SceneFileContext & parsingContext) >
ComponentModeFlags
using castor3d::ComponentModeFlags = typedef castor::FlagCombination< ComponentModeFlag >
ControlArray
using castor3d::ControlArray = typedef std::vector< ControlRPtr >
ControlFlags
using castor3d::ControlFlags = typedef castor::FlagCombination< ControlFlag >
ControlFlagType
using castor3d::ControlFlagType = typedef uint64_t
ControlID
using castor3d::ControlID = typedef size_t
CreatePassComponentPlugin
using castor3d::CreatePassComponentPlugin = typedef std::function< PassComponentPluginUPtr(PassComponentRegister const &) >
DebugCallbacksPtr
using castor3d::DebugCallbacksPtr = typedef std::unique_ptr< DebugCallbacks >
DoubleBufferedTextureLayout
using castor3d::DoubleBufferedTextureLayout = typedef DoubleBufferedResourceT< TextureLayout, castor::UniquePtr >
EditFlags
using castor3d::EditFlags = typedef castor::FlagCombination< EditFlag >
ElementUsages
using castor3d::ElementUsages = typedef castor::FlagCombination< ElementUsage >
FeatureArray
using castor3d::FeatureArray = typedef std::vector< ExtensionStruct >
FinishComponent
using castor3d::FinishComponent = typedef std::function< void(shader::SurfaceBase const & surface , sdw::Vec3 const worldEye , shader::Utils & utils , shader::BlendComponents & components) >
FontCacheView
using castor3d::FontCacheView = typedef CacheViewT< castor::FontCache, EventType::ePreRender >
FrameListenerCache
using castor3d::FrameListenerCache = typedef castor::ResourceCacheT< FrameListener , castor::String , FrameListenerCacheTraits >
FrameListenerCacheTraits
using castor3d::FrameListenerCacheTraits = typedef PtrCacheTraitsT< FrameListener, castor::String >
FrameListenerRes
using castor3d::FrameListenerRes = typedef FrameListenerCacheTraits::ElementPtrT
FrameListenerResPtr
using castor3d::FrameListenerResPtr = typedef FrameListenerCacheTraits::ElementObsT
GeometryCache
using castor3d::GeometryCache = typedef ObjectCacheT< Geometry , castor::String , GeometryCacheTraits >
GeometryCacheTraits
using castor3d::GeometryCacheTraits = typedef ObjectCacheTraitsT< Geometry, castor::String >
GeometryRes
using castor3d::GeometryRes = typedef CameraCacheTraits::ElementPtrT
GeometryResPtr
using castor3d::GeometryResPtr = typedef CameraCacheTraits::ElementObsT
GpuBuddyBuffer
using castor3d::GpuBuddyBuffer = typedef GpuBufferT< GpuBufferBuddyAllocator >
GpuBufferBuddyAllocator
using castor3d::GpuBufferBuddyAllocator = typedef castor::BuddyAllocatorT< GpuBufferBuddyAllocatorTraits >
GpuBufferBuddyAllocatorUPtr
using castor3d::GpuBufferBuddyAllocatorUPtr = typedef std::unique_ptr< GpuBufferBuddyAllocator >
GpuDataBufferOffsetModifyConnection
using castor3d::GpuDataBufferOffsetModifyConnection = typedef castor::ConnectionT< GpuDataBufferOffsetModifySignal >
GpuDataBufferOffsetModifyFunc
using castor3d::GpuDataBufferOffsetModifyFunc = typedef std::function< void(GpuDataBufferOffset const &) >
GpuDataBufferOffsetModifySignal
using castor3d::GpuDataBufferOffsetModifySignal = typedef castor::SignalT< GpuDataBufferOffsetModifyFunc >
GpuDataBufferOffsetPtr
using castor3d::GpuDataBufferOffsetPtr = typedef std::unique_ptr< GpuDataBufferOffset >
GpuFeatures
using castor3d::GpuFeatures = typedef castor::FlagCombination< GpuFeature >
GpuLinearBuffer
using castor3d::GpuLinearBuffer = typedef GpuBufferT< GpuBufferLinearAllocator >
GpuLinearBufferPtr
using castor3d::GpuLinearBufferPtr = typedef std::unique_ptr< GpuLinearBuffer >
GpuPackedBuffer
using castor3d::GpuPackedBuffer = typedef GpuBufferT< GpuBufferPackedAllocator >
GpuPackedBufferPtr
using castor3d::GpuPackedBufferPtr = typedef std::unique_ptr< GpuPackedBuffer >
GroupAnimationMap
using castor3d::GroupAnimationMap = typedef std::map< castor::String, GroupAnimation >
HandlerEventSPtr
using castor3d::HandlerEventSPtr = typedef std::shared_ptr< HandlerEvent >
InterleavedVertexArray
using castor3d::InterleavedVertexArray = typedef std::vector< InterleavedVertex >
InterpolatorPtr
template<typename DataT > using castor3d::InterpolatorPtr = typedef std::unique_ptr< Interpolator< DataT > >
KeyboardEventSPtr
using castor3d::KeyboardEventSPtr = typedef std::shared_ptr< KeyboardEvent >
LayeredLightPropagationVolumes
using castor3d::LayeredLightPropagationVolumes = typedef LayeredLightPropagationVolumesT< false >
LayeredLightPropagationVolumesG
using castor3d::LayeredLightPropagationVolumesG = typedef LayeredLightPropagationVolumesT< true >
LayeredLightPropagationVolumesGLightType
using castor3d::LayeredLightPropagationVolumesGLightType = typedef std::array< LayeredLightPropagationVolumesGUPtr, size_t(LightType::eCount) >
LayeredLightPropagationVolumesLightType
using castor3d::LayeredLightPropagationVolumesLightType = typedef std::array< LayeredLightPropagationVolumesUPtr, size_t(LightType::eCount) >
LightCache
using castor3d::LightCache = typedef ObjectCacheT< Light , castor::String , LightCacheTraits >
LightCacheTraits
typedef ObjectCacheTraitsT< Light, castor::String > castor3d::LightCacheTraits
LightIdArray
using castor3d::LightIdArray = typedef std::vector< std::pair< Light *, uint32_t > >
LightingModelID
using castor3d::LightingModelID = typedef uint8_t
LightPropagationVolumes
using castor3d::LightPropagationVolumes = typedef LightPropagationVolumesT< false >
LightPropagationVolumesG
using castor3d::LightPropagationVolumesG = typedef LightPropagationVolumesT< true >
LightPropagationVolumesGLightType
using castor3d::LightPropagationVolumesGLightType = typedef std::array< LightPropagationVolumesGUPtr, size_t(LightType::eCount) >
LightPropagationVolumesLightType
using castor3d::LightPropagationVolumesLightType = typedef std::array< LightPropagationVolumesUPtr, size_t(LightType::eCount) >
LightRenderPassArray
using castor3d::LightRenderPassArray = typedef std::vector< LightRenderPass >
LightRes
using castor3d::LightRes = typedef CameraCacheTraits::ElementPtrT
LightResPtr
using castor3d::LightResPtr = typedef CameraCacheTraits::ElementObsT
LightsMap
using castor3d::LightsMap = typedef std::array< LightsArray, size_t(LightType::eCount) >
Array of lights per light type.
LightsPipelinePtr
using castor3d::LightsPipelinePtr = typedef std::unique_ptr< LightsPipeline >
LineArray
using castor3d::LineArray = typedef std::vector< Line >
An array of Lines.
MaterialCache
using castor3d::MaterialCache = typedef castor::ResourceCacheT< Material , castor::String , MaterialCacheTraits >
MaterialCacheTraits
using castor3d::MaterialCacheTraits = typedef PtrCacheTraitsT< Material, castor::String >
MaterialCacheView
using castor3d::MaterialCacheView = typedef CacheViewT< MaterialCache, EventType::ePreRender >
MaterialObs
using castor3d::MaterialObs = typedef MaterialCacheTraits::ElementObsT
MaterialPtr
using castor3d::MaterialPtr = typedef MaterialCacheTraits::ElementPtrT
MeshCache
using castor3d::MeshCache = typedef castor::ResourceCacheT< Mesh , castor::String , MeshCacheTraits >
MeshCacheTraits
using castor3d::MeshCacheTraits = typedef ResourceCacheTraitsT< Mesh, castor::String >
MeshRes
using castor3d::MeshRes = typedef MeshCacheTraits::ElementPtrT
MeshResPtr
using castor3d::MeshResPtr = typedef MeshCacheTraits::ElementObsT
MorphFlags
using castor3d::MorphFlags = typedef castor::FlagCombination< MorphFlag >
MouseEventSPtr
using castor3d::MouseEventSPtr = typedef std::shared_ptr< MouseEvent >
NodeArrayT
template<typename NodeT > using castor3d::NodeArrayT = typedef std::vector< CountedNodeT< NodeT > >
NodeObjectT
template<typename NodeT > using castor3d::NodeObjectT = typedef typename RenderNodeTraitsT< NodeT >::Object
NodePtrByBufferMapT
template<typename NodeT > using castor3d::NodePtrByBufferMapT = typedef std::unordered_map< ashes::BufferBase const *, NodeArrayT< NodeT > >
NodePtrByPipelineMapT
template<typename NodeT > using castor3d::NodePtrByPipelineMapT = typedef std::unordered_map< RenderPipeline *, NodePtrByBufferMapT< NodeT > >
NormalsComponent
using castor3d::NormalsComponent = typedef BaseDataComponentT< SubmeshFlag::eNormals >
The submesh component holding normals.
ObjectAttacherT
template<typename ObjT , typename KeyT > using castor3d::ObjectAttacherT = typedef typename ObjectCacheTraitsT< ObjT, KeyT >::ElementAttacherT
ObjectCachePtrT
template<typename ObjT , typename KeyT , typename TraitsT > using castor3d::ObjectCachePtrT = typedef castor::UniquePtr< ObjectCacheT< ObjT, KeyT, TraitsT > >
ObjectCleanerT
template<typename ObjT , typename KeyT > using castor3d::ObjectCleanerT = typedef typename ObjectCacheTraitsT< ObjT, KeyT >::ElementCleanerT
ObjectContT
template<typename ObjT , typename KeyT > using castor3d::ObjectContT = typedef typename ObjectCacheTraitsT< ObjT, KeyT >::ElementContT
ObjectDetacherT
template<typename ObjT , typename KeyT > using castor3d::ObjectDetacherT = typedef typename ObjectCacheTraitsT< ObjT, KeyT >::ElementDetacherT
ObjectInitialiserT
template<typename ObjT , typename KeyT > using castor3d::ObjectInitialiserT = typedef typename ObjectCacheTraitsT< ObjT, KeyT >::ElementInitialiserT
ObjectMergerT
template<typename ObjT , typename KeyT > using castor3d::ObjectMergerT = typedef typename ObjectCacheTraitsT< ObjT, KeyT >::ElementMergerT
ObjectNodesPtrByBufferMapT
template<typename NodeT > using castor3d::ObjectNodesPtrByBufferMapT = typedef std::unordered_map< ashes::BufferBase const *, ObjectNodesPtrByPassT< NodeT > >
ObjectNodesPtrByPassT
template<typename NodeT > using castor3d::ObjectNodesPtrByPassT = typedef std::unordered_map< PassRPtr, ObjectNodesPtrMapT< NodeT > >
ObjectNodesPtrByPipelineMapT
template<typename NodeT > using castor3d::ObjectNodesPtrByPipelineMapT = typedef std::unordered_map< RenderPipeline *, ObjectNodesPtrByBufferMapT< NodeT > >
ObjectNodesPtrMapT
template<typename NodeT > using castor3d::ObjectNodesPtrMapT = typedef std::unordered_map< NodeObjectT< NodeT > *, NodeArrayT< NodeT > >
ObjectObsT
template<typename ObjT , typename KeyT > using castor3d::ObjectObsT = typedef typename ObjectCacheTraitsT< ObjT, KeyT >::ElementObsT
ObjectPtrT
template<typename ObjT , typename KeyT > using castor3d::ObjectPtrT = typedef typename ObjectCacheTraitsT< ObjT, KeyT >::ElementPtrT
OnAnimatedMeshChange
using castor3d::OnAnimatedMeshChange = typedef castor::SignalT< OnAnimatedMeshChangeFunction >
OnAnimatedMeshChangeConnection
using castor3d::OnAnimatedMeshChangeConnection = typedef OnAnimatedMeshChange::connection
OnAnimatedMeshChangeFunction
using castor3d::OnAnimatedMeshChangeFunction = typedef std::function< void(AnimatedObjectGroup const &, AnimatedMesh &) >
OnAnimatedSceneNodeChange
using castor3d::OnAnimatedSceneNodeChange = typedef castor::SignalT< OnAnimatedSceneNodeChangeFunction >
OnAnimatedSceneNodeChangeConnection
using castor3d::OnAnimatedSceneNodeChangeConnection = typedef OnAnimatedSceneNodeChange::connection
OnAnimatedSceneNodeChangeFunction
using castor3d::OnAnimatedSceneNodeChangeFunction = typedef std::function< void(AnimatedObjectGroup const &, AnimatedSceneNode &) >
OnAnimatedSkeletonChange
using castor3d::OnAnimatedSkeletonChange = typedef castor::SignalT< OnAnimatedSkeletonChangeFunction >
OnAnimatedSkeletonChangeConnection
using castor3d::OnAnimatedSkeletonChangeConnection = typedef OnAnimatedSkeletonChange::connection
OnAnimatedSkeletonChangeFunction
using castor3d::OnAnimatedSkeletonChangeFunction = typedef std::function< void(AnimatedObjectGroup const &, AnimatedSkeleton &) >
OnAnimatedTextureChange
using castor3d::OnAnimatedTextureChange = typedef castor::SignalT< OnAnimatedTextureChangeFunction >
OnAnimatedTextureChangeConnection
using castor3d::OnAnimatedTextureChangeConnection = typedef OnAnimatedTextureChange::connection
OnAnimatedTextureChangeFunction
using castor3d::OnAnimatedTextureChangeFunction = typedef std::function< void(AnimatedObjectGroup const &, AnimatedTexture &) >
OnBackgroundChanged
using castor3d::OnBackgroundChanged = typedef castor::SignalT< BackgroundChangedFunc >
OnBackgroundChangedConnection
using castor3d::OnBackgroundChangedConnection = typedef OnBackgroundChanged::connection
OnButtonEvent
using castor3d::OnButtonEvent = typedef castor::SignalT< OnButtonEventFunction >
OnButtonEventConnection
using castor3d::OnButtonEventConnection = typedef OnButtonEvent::connection
OnButtonEventFunction
using castor3d::OnButtonEventFunction = typedef std::function< void() >
OnCameraChanged
using castor3d::OnCameraChanged = typedef castor::SignalT< OnCameraChangedFunction >
OnCameraChangedConnection
using castor3d::OnCameraChangedConnection = typedef OnCameraChanged::connection
OnCameraChangedFunction
using castor3d::OnCameraChangedFunction = typedef std::function< void(Camera const &) >
OnComboEvent
using castor3d::OnComboEvent = typedef castor::SignalT< OnComboEventFunction >
OnComboEventConnection
using castor3d::OnComboEventConnection = typedef OnComboEvent::connection
OnComboEventFunction
using castor3d::OnComboEventFunction = typedef std::function< void(int32_t) >
OnControlChanged
using castor3d::OnControlChanged = typedef castor::SignalT< OnControlChangedFunction >
OnControlChangedConnection
using castor3d::OnControlChangedConnection = typedef OnControlChanged::connection
OnControlChangedFunction
using castor3d::OnControlChangedFunction = typedef std::function< void(Control const &) >
OnControlEvent
using castor3d::OnControlEvent = typedef castor::SignalT< OnControlEventFunction >
OnControlEventConnection
using castor3d::OnControlEventConnection = typedef OnControlEvent::connection
OnControlEventFunction
using castor3d::OnControlEventFunction = typedef std::function< void() >
OnEditEvent
using castor3d::OnEditEvent = typedef castor::SignalT< OnEditEventFunction >
OnEditEventConnection
using castor3d::OnEditEventConnection = typedef OnEditEvent::connection
OnEditEventFunction
using castor3d::OnEditEventFunction = typedef std::function< void(castor::U32String const &) >
OnExpandablePanelEvent
using castor3d::OnExpandablePanelEvent = typedef castor::SignalT< OnExpandablePanelEventFunction >
OnExpandablePanelEventConnection
using castor3d::OnExpandablePanelEventConnection = typedef OnExpandablePanelEvent::connection
OnExpandablePanelEventFunction
using castor3d::OnExpandablePanelEventFunction = typedef std::function< void() >
OnLightChanged
using castor3d::OnLightChanged = typedef castor::SignalT< OnLightChangedFunction >
OnLightChangedConnection
using castor3d::OnLightChangedConnection = typedef OnLightChanged::connection
OnLightChangedFunction
using castor3d::OnLightChangedFunction = typedef std::function< void(Light &) >
OnListEvent
using castor3d::OnListEvent = typedef castor::SignalT< OnListEventFunction >
OnListEventConnection
using castor3d::OnListEventConnection = typedef OnListEvent::connection
OnListEventFunction
using castor3d::OnListEventFunction = typedef std::function< void(int32_t) >
OnMaterialChanged
using castor3d::OnMaterialChanged = typedef castor::SignalT< OnMaterialChangedFunction >
OnMaterialChangedConnection
using castor3d::OnMaterialChangedConnection = typedef OnMaterialChanged::connection
OnMaterialChangedFunction
using castor3d::OnMaterialChangedFunction = typedef std::function< void(Material const &) >
OnPassChanged
using castor3d::OnPassChanged = typedef castor::SignalT< OnPassChangedFunction >
OnPassChangedConnection
using castor3d::OnPassChangedConnection = typedef OnPassChanged::connection
OnPassChangedFunction
using castor3d::OnPassChangedFunction = typedef std::function< void(Pass const & pass , PassComponentCombineID oldComponents , PassComponentCombineID newComponents) >
OnSceneChanged
using castor3d::OnSceneChanged = typedef castor::SignalT< OnSceneChangedFunction >
OnSceneChangedConnection
using castor3d::OnSceneChangedConnection = typedef OnSceneChanged::connection
OnSceneChangedFunction
using castor3d::OnSceneChangedFunction = typedef std::function< void(Scene const &) >
OnSceneNodeChanged
using castor3d::OnSceneNodeChanged = typedef castor::SignalT< OnSceneNodeChangedFunction >
OnSceneNodeChangedConnection
using castor3d::OnSceneNodeChangedConnection = typedef OnSceneNodeChanged::connection
OnSceneNodeChangedFunction
using castor3d::OnSceneNodeChangedFunction = typedef std::function< void(SceneNode const &) >
OnSceneNodeReparent
using castor3d::OnSceneNodeReparent = typedef castor::SignalT< OnSceneNodeReparentFunction >
OnSceneNodeReparentConnection
using castor3d::OnSceneNodeReparentConnection = typedef OnSceneNodeReparent::connection
OnSceneNodeReparentFunction
using castor3d::OnSceneNodeReparentFunction = typedef std::function< void(SceneNode &) >
OnSceneUpdate
using castor3d::OnSceneUpdate = typedef castor::SignalT< OnSceneUpdateFunction >
OnSceneUpdateConnection
using castor3d::OnSceneUpdateConnection = typedef OnSceneUpdate::connection
OnSceneUpdateFunction
using castor3d::OnSceneUpdateFunction = typedef std::function< void(Scene const &) >
OnScrollBarEvent
using castor3d::OnScrollBarEvent = typedef castor::SignalT< OnScrollBarEventFunction >
OnScrollBarEventConnection
using castor3d::OnScrollBarEventConnection = typedef OnScrollBarEvent::connection
OnScrollBarEventFunction
using castor3d::OnScrollBarEventFunction = typedef std::function< void(int32_t) >
OnSliderEvent
using castor3d::OnSliderEvent = typedef castor::SignalT< OnSliderEventFunction >
OnSliderEventConnection
using castor3d::OnSliderEventConnection = typedef OnSliderEvent::connection
OnSliderEventFunction
using castor3d::OnSliderEventFunction = typedef std::function< void(int32_t) >
OnSssProfileChanged
using castor3d::OnSssProfileChanged = typedef castor::SignalT< SssProfileChangedFunc >
OnSssProfileChangedConnection
using castor3d::OnSssProfileChangedConnection = typedef castor::ConnectionT< OnSssProfileChanged >
OnTextureUnitChanged
using castor3d::OnTextureUnitChanged = typedef castor::SignalT< OnTextureUnitChangedFunction >
OnTextureUnitChangedConnection
using castor3d::OnTextureUnitChangedConnection = typedef OnTextureUnitChanged::connection
OnTextureUnitChangedFunction
using castor3d::OnTextureUnitChangedFunction = typedef std::function< void(TextureUnit const &) >
OverlayCache
using castor3d::OverlayCache = typedef castor::ResourceCacheT< Overlay , castor::String , OverlayCacheTraits >
OverlayCacheTraits
using castor3d::OverlayCacheTraits = typedef PtrCacheTraitsT< Overlay, castor::String >
OverlayRes
using castor3d::OverlayRes = typedef OverlayCacheTraits::ElementPtrT
OverlayResPtr
using castor3d::OverlayResPtr = typedef OverlayCacheTraits::ElementObsT
OverlayTextBufferPtr
using castor3d::OverlayTextBufferPtr = typedef std::unique_ptr< OverlayTextBuffer >
OverlayVertexBufferPoolPtrT
template<typename VertexT , uint32_t CountT> using castor3d::OverlayVertexBufferPoolPtrT = typedef std::unique_ptr< OverlayVertexBufferPoolT< VertexT, CountT > >
Parameters
using castor3d::Parameters = typedef ParametersT< castor::String >
ParticleFactory
using castor3d::ParticleFactory = typedef castor::Factory< CpuParticleSystem , castor::String , CpuParticleSystemUPtr , std::function< CpuParticleSystemUPtr(ParticleSystem &) > >
Particle system factory.
ParticleSystemCache
using castor3d::ParticleSystemCache = typedef ObjectCacheT< ParticleSystem , castor::String , ParticleSystemCacheTraits >
ParticleSystemCacheTraits
using castor3d::ParticleSystemCacheTraits = typedef ObjectCacheTraitsT< ParticleSystem, castor::String >
ParticleSystemRes
using castor3d::ParticleSystemRes = typedef CameraCacheTraits::ElementPtrT
ParticleSystemResPtr
using castor3d::ParticleSystemResPtr = typedef CameraCacheTraits::ElementObsT
ParticleValues
using castor3d::ParticleValues = typedef ParametersT< size_t >
PassComponentCombineID
using castor3d::PassComponentCombineID = typedef uint16_t
PassComponentFlag
using castor3d::PassComponentFlag = typedef uint32_t
PassComponentFlagsSet
using castor3d::PassComponentFlagsSet = typedef std::set< PassComponentFlag >
PassComponentID
using castor3d::PassComponentID = typedef uint16_t
PassComponentsBitset
using castor3d::PassComponentsBitset = typedef castor::DynamicBitsetT< uint16_t >
PassComponentTextureFlag
using castor3d::PassComponentTextureFlag = typedef uint32_t
PassCreator
using castor3d::PassCreator = typedef std::function< PassUPtr(LightingModelID, Material &) >
PassFactoryBase
using castor3d::PassFactoryBase = typedef castor::Factory< Pass , LightingModelID , PassUPtr , PassCreator , PassTypeID , PassFactoryEntry >
PassFlags
using castor3d::PassFlags = typedef castor::FlagCombination< PassFlag >
PassSortNodesSignal
using castor3d::PassSortNodesSignal = typedef castor::SignalT< PassSortNodesSignalFunction >
PassSortNodesSignalConnection
using castor3d::PassSortNodesSignalConnection = typedef castor::ConnectionT< PassSortNodesSignal >
PassSortNodesSignalFunction
using castor3d::PassSortNodesSignalFunction = typedef std::function< void(RenderNodesPass const &) >
PassTypeID
using castor3d::PassTypeID = typedef uint16_t
PipelineBuffer
using castor3d::PipelineBuffer = typedef std::pair< PipelineBaseHash, ashes::BufferBase const * >
PipelineBufferArray
using castor3d::PipelineBufferArray = typedef std::vector< PipelineBuffer >
PipelineNodes
using castor3d::PipelineNodes = typedef std::array< uint32_t, MaxNodesPerPipeline >
PluginCache
using castor3d::PluginCache = typedef castor::ResourceCacheT< Plugin , castor::String , PluginCacheTraits >
PluginCacheTraits
using castor3d::PluginCacheTraits = typedef PtrCacheTraitsT< Plugin, castor::String >
PluginRes
using castor3d::PluginRes = typedef PluginCacheTraits::ElementPtrT
PluginResPtr
using castor3d::PluginResPtr = typedef PluginCacheTraits::ElementObsT
Point3rInterpolator
using castor3d::Point3rInterpolator = typedef Interpolator< castor::Point3f >
PositionsComponent
using castor3d::PositionsComponent = typedef BaseDataComponentT< SubmeshFlag::ePositions >
The submesh component holding positions.
PostEffectFactory
using castor3d::PostEffectFactory = typedef castor::Factory< PostEffect , castor::String , PostEffectUPtr , std::function< PostEffectUPtr(RenderTarget &, RenderSystem &, Parameters const &) > >
Post effect factory.
ProgramFlags
using castor3d::ProgramFlags = typedef castor::FlagCombination< ProgramFlag >
ProgressFlags
using castor3d::ProgressFlags = typedef castor::FlagCombination< ProgressFlag >
PropertyArray
using castor3d::PropertyArray = typedef std::vector< ExtensionStruct >
QuaternionInterpolator
using castor3d::QuaternionInterpolator = typedef Interpolator< castor::Quaternion >
QueueDataPtr
using castor3d::QueueDataPtr = typedef std::unique_ptr< QueueData >
QueueFamilies
using castor3d::QueueFamilies = typedef std::vector< QueuesData >
QueueFamilyFlags
using castor3d::QueueFamilyFlags = typedef castor::FlagCombination< QueueFamilyFlag >
RenderFilters
using castor3d::RenderFilters = typedef castor::FlagCombination< RenderFilter >
RenderPassTypeID
using castor3d::RenderPassTypeID = typedef uint16_t
RenderQueueArray
using castor3d::RenderQueueArray = typedef std::vector< std::reference_wrapper< RenderQueue > >
RenderWindowPtr
using castor3d::RenderWindowPtr = typedef std::unique_ptr< RenderWindow >
SamplerCache
using castor3d::SamplerCache = typedef castor::ResourceCacheT< Sampler , castor::String , SamplerCacheTraits >
SamplerCacheTraits
using castor3d::SamplerCacheTraits = typedef PtrCacheTraitsT< Sampler, castor::String >
SamplerCacheView
using castor3d::SamplerCacheView = typedef CacheViewT< SamplerCache, EventType::ePreRender >
SamplerObs
using castor3d::SamplerObs = typedef SamplerCacheTraits::ElementObsT
SamplerPtr
using castor3d::SamplerPtr = typedef SamplerCacheTraits::ElementPtrT
SceneCache
using castor3d::SceneCache = typedef castor::ResourceCacheT< Scene , castor::String , SceneCacheTraits >
SceneCacheTraits
using castor3d::SceneCacheTraits = typedef PtrCacheTraitsT< Scene, castor::String >
SceneCullerSignal
using castor3d::SceneCullerSignal = typedef castor::SignalT< SceneCullerSignalFunction >
SceneCullerSignalConnection
using castor3d::SceneCullerSignalConnection = typedef castor::ConnectionT< SceneCullerSignal >
SceneCullerSignalFunction
using castor3d::SceneCullerSignalFunction = typedef std::function< void(SceneCuller const &) >
SceneFlags
using castor3d::SceneFlags = typedef castor::FlagCombination< SceneFlag >
SceneNodeCache
using castor3d::SceneNodeCache = typedef ObjectCacheT< SceneNode , castor::String , SceneNodeCacheTraits >
SceneNodeCacheTraits
using castor3d::SceneNodeCacheTraits = typedef ObjectCacheTraitsT< SceneNode, castor::String >
SceneNodeRes
using castor3d::SceneNodeRes = typedef CameraCacheTraits::ElementPtrT
SceneNodeResPtr
using castor3d::SceneNodeResPtr = typedef CameraCacheTraits::ElementObsT
SceneRes
using castor3d::SceneRes = typedef SceneCacheTraits::ElementPtrT
SceneResPtr
using castor3d::SceneResPtr = typedef SceneCacheTraits::ElementObsT
ScrollBarFlags
using castor3d::ScrollBarFlags = typedef castor::FlagCombination< ScrollBarFlag >
ShaderFlags
using castor3d::ShaderFlags = typedef castor::FlagCombination< ShaderFlag >
ShaderPtr
using castor3d::ShaderPtr = typedef std::unique_ptr< ast::Shader >
ShadowMapLightArray
using castor3d::ShadowMapLightArray = typedef std::array< ShadowMapLightIdArray, size_t(LightType::eCount) >
ShadowMapLightIdArray
using castor3d::ShadowMapLightIdArray = typedef std::vector< ShadowMapLightIds >
ShadowMapLightTypeArray
using castor3d::ShadowMapLightTypeArray = typedef std::array< ShadowMapRefArray, size_t(LightType::eCount) >
ShadowMapRefArray
using castor3d::ShadowMapRefArray = typedef std::vector< ShadowMapRefIds >
ShadowMapRefIds
using castor3d::ShadowMapRefIds = typedef std::pair< std::reference_wrapper< ShadowMap >, UInt32Array >
SkeletonAnimationInstanceKeyFrameArray
using castor3d::SkeletonAnimationInstanceKeyFrameArray = typedef std::vector< SkeletonAnimationInstanceKeyFrame >
SkeletonAnimationObjectArray
using castor3d::SkeletonAnimationObjectArray = typedef std::vector< SkeletonAnimationObjectRPtr >
SkeletonCache
using castor3d::SkeletonCache = typedef castor::ResourceCacheT< Skeleton , castor::String , SkeletonCacheTraits >
SkeletonCacheTraits
using castor3d::SkeletonCacheTraits = typedef PtrCacheTraitsT< Skeleton, castor::String >
SkeletonRes
using castor3d::SkeletonRes = typedef SkeletonCacheTraits::ElementPtrT
SkeletonResPtr
using castor3d::SkeletonResPtr = typedef SkeletonCacheTraits::ElementObsT
SliderFlags
using castor3d::SliderFlags = typedef castor::FlagCombination< SliderFlag >
SpecificsBuffers
using castor3d::SpecificsBuffers = typedef std::map< std::string, std::pair< SpecificsBuffer, ShaderBufferUPtr > >
SssProfileChangedFunc
using castor3d::SssProfileChangedFunc = typedef std::function< void(SubsurfaceScatteringComponent const &) >
StaticFlags
using castor3d::StaticFlags = typedef castor::FlagCombination< StaticFlag >
StencilPipelinePtr
using castor3d::StencilPipelinePtr = typedef std::unique_ptr< StencilPipeline >
SubmeshBoundingBoxList
using castor3d::SubmeshBoundingBoxList = typedef std::vector< std::pair< Submesh const *, castor::BoundingBox > >
SubmeshFlags
using castor3d::SubmeshFlags = typedef castor::FlagCombination< SubmeshFlag >
SubmeshMaterialMap
using castor3d::SubmeshMaterialMap = typedef std::map< Submesh const *, MaterialObs >
TangentsComponent
using castor3d::TangentsComponent = typedef BaseDataComponentT< SubmeshFlag::eTangents >
The submesh component holding tangents.
TechniquePasses
using castor3d::TechniquePasses = typedef std::array< TechniquePassVector, size_t(TechniquePassEvent::eCount) >
TechniquePassVector
using castor3d::TechniquePassVector = typedef std::vector< RenderTechniqueNodesPass * >
Texcoords0Component
using castor3d::Texcoords0Component = typedef BaseDataComponentT< SubmeshFlag::eTexcoords0 >
The submesh component holding texture coordinates.
Texcoords1Component
using castor3d::Texcoords1Component = typedef BaseDataComponentT< SubmeshFlag::eTexcoords1 >
The submesh component holding texture coordinates.
Texcoords2Component
using castor3d::Texcoords2Component = typedef BaseDataComponentT< SubmeshFlag::eTexcoords2 >
The submesh component holding texture coordinates.
Texcoords3Component
using castor3d::Texcoords3Component = typedef BaseDataComponentT< SubmeshFlag::eTexcoords3 >
The submesh component holding texture coordinates.
TextureArray
using castor3d::TextureArray = typedef std::vector< TexturePtr >
TextureCombineID
using castor3d::TextureCombineID = typedef uint16_t
TextureFlagConfigurations
using castor3d::TextureFlagConfigurations = typedef std::array< TextureFlagConfiguration, 4u >
TextureFlags
using castor3d::TextureFlags = typedef castor::FlagCombination< TextureFlag >
TextureFlagsSet
using castor3d::TextureFlagsSet = typedef std::set< PassComponentTextureFlag >
TexturePtr
using castor3d::TexturePtr = typedef std::shared_ptr< Texture >
TextureRotateSpeed
using castor3d::TextureRotateSpeed = typedef castor::SpeedT< castor::Angle, castor::Seconds >
TextureScaleSpeed
using castor3d::TextureScaleSpeed = typedef castor::SpeedT< castor::Point2f, castor::Seconds >
TexturesData
using castor3d::TexturesData = typedef std::array< uint32_t, MaxPassTextures >
TextureSourceMap
using castor3d::TextureSourceMap = typedef std::unordered_map< TextureSourceInfo , PassTextureConfig , TextureSourceInfoHasher >
TextureSourceMapVT
using castor3d::TextureSourceMapVT = typedef TextureSourceMap::value_type
TextureSourceSet
using castor3d::TextureSourceSet = typedef std::unordered_set< TextureSourceInfo, TextureSourceInfoHasher >
TextureSpaces
using castor3d::TextureSpaces = typedef castor::FlagCombination< TextureSpace >
TextureTranslateSpeed
using castor3d::TextureTranslateSpeed = typedef castor::SpeedT< castor::Point2f, castor::Seconds >
TextureUnitDataRefs
using castor3d::TextureUnitDataRefs = typedef std::vector< TextureUnitDataRPtr >
TextureUnitDatas
using castor3d::TextureUnitDatas = typedef std::vector< TextureUnitDataUPtr >
TextureUnitDataSet
using castor3d::TextureUnitDataSet = typedef std::map< PassComponentTextureFlag, TextureUnitDataRPtr >
TextureViewCRef
using castor3d::TextureViewCRef = typedef std::reference_wrapper< TextureView const >
TextureViewCRefArray
using castor3d::TextureViewCRefArray = typedef std::vector< TextureViewCRef >
ToneMappingFactory
using castor3d::ToneMappingFactory = typedef castor::Factory< ToneMapping , castor::String , castor3d::ShaderPtr , std::function< castor3d::ShaderPtr() > >
Tone mapping factory.
TransformArray
using castor3d::TransformArray = typedef std::vector< ObjectTransform >
UpdateComponent
using castor3d::UpdateComponent = typedef std::function< void(PassComponentRegister const & passComponents , TextureCombine const & combine , shader::BlendComponents & components) >
UserInputEventSPtr
using castor3d::UserInputEventSPtr = typedef std::shared_ptr< UserInputEvent >
Enumeration Type Documentation
AnimationState
enum class castor3d::AnimationState : uint8_t strong
Animation State Enumerator.
Enumerator
ePlaying
Playing animation state.
eStopped
Stopped animation state.
ePaused
Paused animation state.
eCount
eMin
eMax
AnimationType
enum class castor3d::AnimationType : uint8_t strong
Animation types enumeration.
Enumerator
eSceneNode
Scene node animation.
eSkeleton
Skeleton animation.
eMesh
Submesh animation (morphing).
eTexture
Texture animation.
eCount
eMin
eMax
BillboardSize
enum class castor3d::BillboardSize strong
Billboard sizing types enumeration.
Enumerator
eDynamic
Billboards size changes with camera position.
eFixed
Billboards size doesn't change.
eCount
eMin
eMax
BillboardType
enum class castor3d::BillboardType strong
Billboard rendering types enumeration.
Enumerator
eSpherical
Billboards always face the camera.
eCylindrical
Billboards rotate only on Y axis.
eCount
eMin
eMax
BlendMode
enum class castor3d::BlendMode : uint8_t strong
Blending modes enumeration.
Enumerator
eNoBlend
Order dependent blending.
eAdditive
Order independent, add the components.
eMultiplicative
Order independent, multiply the components.
eInterpolative
Order dependent, interpolate the components.
eABuffer
Order independent, using A-buffer, not implemented yet.
eDepthPeeling
Order independent, using depth peeling, not implemented yet.
eCount
eMin
eMax
BorderPosition
enum class castor3d::BorderPosition strong
Text wrapping modes, handles the way text is cut when it overflows the overlay width.
Enumerator
eInternal
The border is outside the overlay.
eMiddle
The border is middle outside and middle inside the overlay.
eExternal
The border is outside the overlay.
eCount
eMin
eMax
ButtonEvent
enum class castor3d::ButtonEvent : uint8_t strong
Enumeration of supported button events.
Enumerator
eClicked
Button clicked.
eCount
The button events count.
ChunkType
enum class castor3d::ChunkType : uint64_t strong
Binary data chunk types enumeration.
Enumerator
eUnknown
eCmshFile
eCmshHeader
eCmshVersion
eName
eMesh
eSkeleton
eSkeletonGlobalInverse
eSkeletonBone
eSkeletonNode
eBoneParentName
eBoneOffsetMatrix
eSubmesh
eSubmeshTopology
eSubmeshVertexCount
eSubmeshBoneCount
eSubmeshBones
eSubmeshMatrixCount
eSubmeshMatrices
eAnimable
eAnimation
eAnimLength
eSkeletonAnimation
eMeshAnimation
eAnimInterpolator
eAnimationObject
eSkeletonAnimationNode
eSkeletonAnimationBone
eMovingTransform
eBonesComponent
eKeyframeCount
eKeyframes
eSkeletonAnimationKeyFrame
eSkeletonAnimationKeyFrameTime
eSkeletonAnimationKeyFrameObjectType
eSkeletonAnimationKeyFrameObjectName
eSubmeshFaceCount
eSubmeshIndexComponentCount
eSubmeshIndexCount
eSubmeshFaces
eSubmeshIndices
eSceneNodeAnimation
eSceneNodeAnimationKeyFrame
eSceneNodeAnimationKeyFrameTime
eSceneNodeAnimationKeyFrameTranslate
eSceneNodeAnimationKeyFrameRotate
eSceneNodeAnimationKeyFrameScale
eBoneId
eSubmeshVertex
eSubmeshPositions
eSubmeshNormals
eSubmeshTangents
eSubmeshTexcoords0
eSubmeshTexcoords1
eSubmeshTexcoords2
eSubmeshTexcoords3
eSubmeshColours
eMeshAnimationKeyFrame
eMeshAnimationKeyFrameTime
eMeshAnimationKeyFrameBufferData
eMeshAnimationKeyFrameSubmeshID
eMeshAnimationKeyFrameBufferSize
eMorphComponent
eMorphTargetBufferSize
eMorphTargetPositions
eMorphTargetNormals
eMorphTargetTangents
eMorphTargetTexcoords0
eMorphTargetTexcoords1
eMorphTargetTexcoords2
eMorphTargetTexcoords3
eMorphTargetColours
eMeshMorphTarget
eMeshMorphTargetTime
eMeshMorphTargetSubmeshID
eMeshMorphTargetWeights
eSkeletonAnimationKeyFrameObjectTransform
eSkeletonAnimationKeyFrameObjectTranslate
eSkeletonAnimationKeyFrameObjectRotate
eSkeletonAnimationKeyFrameObjectScale
ComboBoxEvent
enum class castor3d::ComboBoxEvent : uint8_t strong
Enumeration of supported combobox events.
Enumerator
eSelected
Item selected.
eCount
The combo box events count.
ComboBoxFlag
enum class castor3d::ComboBoxFlag : ControlFlagType strong
Combo control supported flags.
Enumerator
eReadOnly
read only combo box
ComponentMode
enum class castor3d::ComponentMode : uint16_t strong
Enumerator
eNone
eOpacity
eAlphaBlending
eNormals
eGeometry
eColour
eDiffuseLighting
eSpecularLighting
eSpecifics
eDerivTex
eOcclusion
eCount
eMin
eMax
ComponentModeFlag
enum class castor3d::ComponentModeFlag : uint16_t strong
Enumerator
eNone
eOpacity
eAlphaBlending
eNormals
eGeometry
eColour
eDiffuseLighting
eSpecularLighting
eSpecifics
eDerivTex
eOcclusion
eAll
ControlEvent
enum class castor3d::ControlEvent : uint8_t strong
Enumeration of supported control events.
Enumerator
eDrag
Control dragged.
eDrop
Control dropped.
eCount
The control events count.
ControlFlag
enum class castor3d::ControlFlag : ControlFlagType strong
Listbox control supported flags.
Enumerator
eAlwaysOnTop
Control is detached and appears on top of every other one.
eMovable
Control can be moved around.
eResizable
Control can be resized.
ControlType
enum class castor3d::ControlType : uint8_t strong
Enumeration of supported control types.
Enumerator
eNone
ePanel
PanelCtrl.
eStatic
StaticCtrl.
eEdit
EditCtrl.
eSlider
SliderCtrl.
eComboBox
ComboBoxCtrl.
eListBox
ListBoxCtrl.
eButton
ButtonCtrl.
eExpandablePanel
ExpandablePanelCtrl.
eFrame
FrameCtrl.
eScrollBar
ScrollBarCtrl.
eProgress
ProgressCtrl.
CSCNSection
enum class castor3d::CSCNSection : uint32_t strong
Defines all the sections and subsections of a scene file.
Enumerator
eRoot
eScene
eWindow
eSampler
eCamera
eViewport
eLight
eNode
eObject
eObjectMaterials
eFont
ePanelOverlay
eBorderPanelOverlay
eTextOverlay
eMesh
eSubmesh
eMaterial
ePass
eTextureUnit
eRenderTarget
eShaderProgram
eShaderStage
eShaderUBO
eUBOVariable
eBillboard
eBillboardList
eAnimGroup
eAnimation
eSkybox
eParticleSystem
eParticle
eSsao
eHdrConfig
eShadows
eMeshDefaultMaterials
eRsm
eLpv
eRaw
ePcf
eVsm
eTextureAnimation
eVoxelConeTracing
eTextureTransform
eSceneImport
eSkeleton
eMorphAnimation
eTextureRemapChannel
eTextureRemap
CubeMapFace
enum class castor3d::CubeMapFace : uint8_t strong
Cube map faces.
Enumerator
ePositiveX
Face on positive X
eNegativeX
Face on negative X
ePositiveY
Face on positive Y
eNegativeY
Face on negative Y
ePositiveZ
Face on positive Z
eNegativeZ
Face on negative Z
eCount
eMin
eMax
DsTexture
enum class castor3d::DsTexture : uint8_t strong
Enumerator of textures used by the deferred renderer's GBUffer.
Enumerator
eNmlOcc
eColMtl
eSpcRgh
eEmsTrn
eClrCot
eCrTsIr
eSheen
eCount
eMin
eMax
EditEvent
enum class castor3d::EditEvent : uint8_t strong
Enumeration of supported edit events.
Enumerator
eUpdated
The edit text has changed.
eReturn
The return key has been hit (the edit must have EditStyle::eProcessEnter style).
eCount
The edit events count.
EditFlag
enum class castor3d::EditFlag : ControlFlagType strong
Edit control supported flags.
Enumerator
eProcessEnter
The edit control process 'return' hit as an event and not as a newline.
eMultiline
The edit control is a multiline edit control.
eProcessTab
The edit control process 'tab' hit as the tab character and not as an event.
eWordWrap
Words are not cut.
ElementUsage
enum class castor3d::ElementUsage : uint32_t strong
Element usage enumeration.
Enumerator
eUnknown
Position coords.
ePosition
Position coords.
eNormal
Normal coords.
eTangent
Tangent coords.
eBitangent
Bitangent coords.
eColour
Colour.
eTexCoords
Texture coordinates.
eBoneIds0
Bone IDs 0.
eBoneIds1
Bone IDs 1.
eBoneWeights0
Bone weights 0.
eBoneWeights1
Bone weights 1.
eTransform
Instantiation matrix.
eMatIndex
Instantiation material index.
EventType
enum class castor3d::EventType : uint8_t strong
Frame Event Type enumeration.
Enumerator
ePreRender
This kind of event happens before any render, device context is active (so be fast !!).
eQueueRender
This kind of event happens after the render, before buffers' swap.
ePostRender
This kind of event happens after the buffer' swap.
eCount
eMin
eMax
ExpandablePanelEvent
enum class castor3d::ExpandablePanelEvent : uint8_t strong
Enumeration of supported expandable panel events.
Enumerator
eExpand
Expand panel.
eRetract
Retract panel, leaving only header visible.
eCount
The expandable panel events count.
FogType
enum class castor3d::FogType strong
Fog types enumeration.
Enumerator
eDisabled
No fog.
eLinear
Fog intensity increases linearly with distance to camera.
eExponential
Fog intensity increases exponentially with distance to camera.
eSquaredExponential
Fog intensity increases even more with distance to camera.
eCount
eMin
eMax
FrustumCorner
enum class castor3d::FrustumCorner strong
Frustum corners enumeration.
Enumerator
eFarLeftBottom
Far left bottom corner.
eFarLeftTop
Far left top corner.
eFarRightTop
Far right top corner.
eFarRightBottom
Far right bottom corner.
eNearLeftBottom
Near left bottom corner.
eNearLeftTop
Near left top corner.
eNearRightTop
Near right top corner.
eNearRightBottom
Near right bottom corner.
eCount
eMin
eMax
FrustumPlane
enum class castor3d::FrustumPlane strong
Frustum planes enumeration.
Enumerator
eNear
Near plane.
eFar
Far plane.
eLeft
Left plane.
eRight
Right plane.
eTop
Top plane.
eBottom
Bottom plane.
eCount
eMin
eMax
GlobalBuffersIdx
enum class castor3d::GlobalBuffersIdx : uint32_t strong
The render pass UBOs binding index.
Enumerator
eCamera
eScene
eObjectsNodeID
eModelsData
eMaterials
eSssProfiles
eTexConfigs
eTexAnims
eBillboardsData
eCount
eMin
eMax
GlobalIlluminationType
enum class castor3d::GlobalIlluminationType : uint8_t strong
Enumerator of supported global illumination algorithms.
Enumerator
eNone
eRsm
eVoxelConeTracing
eLpv
eLpvG
eLayeredLpv
eLayeredLpvG
eCount
eMin
eMax
GpuFeature
enum class castor3d::GpuFeature : uint32_t strong
All supported GPU feature flags.
Enumerator
eStereoRendering
Tells whether or not the selected render API supports stereographic rendering.
eShaderStorageBuffers
Tells whether or not the selected render API supports shader stoarage buffers.
eBindless
Tells whether or not the selected render API supports bindless render.
eGeometry
Tells whether or not the selected render API supports geometry shaders.
eTessellation
Tells whether or not the selected render API supports tessellation shaders.
eRayTracing
Tells whether or not the selected render API supports ray tracing shaders.
eMesh
Tells whether or not the selected render API supports mesh shaders.
GpuMax
enum class castor3d::GpuMax : uint32_t strong
Maximum values enumerator.
Enumerator
eTexture1DSize
eTexture2DSize
eTexture3DSize
eTextureCubeSize
eTextureLayers
eSamplerLodBias
eClipDistances
eFramebufferWidth
eFramebufferHeight
eFramebufferLayers
eFramebufferSamples
eTexelBufferSize
eUniformBufferSize
eStorageBufferSize
eViewportWidth
eViewportHeight
eViewports
eWorkGroupCountX
eWorkGroupCountY
eWorkGroupCountZ
eWorkGroupSizeX
eWorkGroupSizeY
eWorkGroupSizeZ
eWorkGroupInvocations
eMeshWorkGroupInvocations
eMeshWorkGroupSizeX
eMeshWorkGroupSizeY
eMeshWorkGroupSizeZ
eMeshTotalMemorySize
eMeshOutputVertices
eMeshOutputPrimitives
eDrawMeshTasksCount
eTaskWorkGroupInvocations
eTaskWorkGroupSizeX
eTaskWorkGroupSizeY
eTaskWorkGroupSizeZ
eTaskTotalMemorySize
eTaskOutputCount
eCount
eMin
eMax
GpuMin
enum class castor3d::GpuMin : uint32_t strong
Minimum values enumerator.
Enumerator
eBufferMapSize
eUniformBufferOffsetAlignment
eCount
eMin
eMax
GuiEvent
enum class castor3d::GuiEvent : uint8_t strong
Enumeration of supported GUI events in ControlInfos.
Enumerator
eShowMessageBox
Event to ask the main window to show a message box.
eResizeParent
Event to ask the main window to resize to the given size.
GUISection
enum class castor3d::GUISection : uint32_t strong
Scene file sections Enum.
The enumeration which defines all the sections and subsections of a scene file
Enumerator
eGUI
eTheme
eButtonStyle
eEditStyle
eComboStyle
eListStyle
eSliderStyle
eStaticStyle
ePanelStyle
eProgressStyle
eExpandablePanelStyle
eFrameStyle
eScrollBarStyle
eButton
eStatic
eSlider
eComboBox
eListBox
eEdit
ePanel
eProgress
eExpandablePanel
eExpandablePanelHeader
eExpandablePanelExpand
eExpandablePanelContent
eFrame
eFrameContent
eBoxLayout
eLayoutCtrl
HAlign
enum class castor3d::HAlign strong
Horizontal alignments for text overlays.
Enumerator
eLeft
Aligned on the left.
eCenter
Centered horizontally.
eRight
Aligned on the right.
eCount
eMin
eMax
HandlerEventType
enum class castor3d::HandlerEventType : uint8_t strong
Enumeration of supported handler events.
Enumration des vnements de gestionnaire supportes.
Enumerator
eActivate
Handler activated.
eDeactivate
Handler deactivated.
eCount
eMin
eMax
InterpolatorType
enum class castor3d::InterpolatorType : uint8_t strong
Interpolation modes enumeration.
Enumerator
eNearest
No interpolation.
eLinear
Linear mode.
eCount
eMin
eMax
KeyboardEventType
enum class castor3d::KeyboardEventType : uint8_t strong
Enumeration of supported keyboard events.
Enumration des vnement clavier supports.
Enumerator
ePushed
A key is pushed.
eReleased
A key is released.
eChar
A displayable char key is stroked.
eCount
eMin
eMax
KeyboardKey
enum class castor3d::KeyboardKey strong
Keyboard keys enumeration.
Enumerator
eNone
eBackspace
eTab
eReturn
eEscape
eSpace
eAsciiBegin
eDelete
eAsciiEnd
eStart
eLButton
eRButton
eCancel
eMButton
eClear
eShift
eAlt
eControl
eMenu
ePause
eCapital
eEnd
eHome
eLeft
eUp
eRight
eDown
eSelect
ePrint
eExecute
eSnapshot
eInsert
eHelp
eNumpad0
eNumpad1
eNumpad2
eNumpad3
eNumpad4
eNumpad5
eNumpad6
eNumpad7
eNumpad8
eNumpad9
eMultiply
eAdd
eSeparator
eSubtract
eDecimal
eDivide
eF1
eF2
eF3
eF4
eF5
eF6
eF7
eF8
eF9
eF10
eF11
eF12
eF13
eF14
eF15
eF16
eF17
eF18
eF19
eF20
eF21
eF22
eF23
eF24
eNumlock
eScroll
ePageUp
ePageDown
eNumpadSpace
eNumpadTab
eNumpadEnter
eNumpadF1
eNumpadF2
eNumpadF3
eNumpadF4
eNumpadHome
eNumpadLeft
eNumpadUp
eNumpadRight
eNumpadDown
eNumpadPageUp
eNumpadPageDown
eNumpadEnd
eNumpadBegin
eNumpadInsert
eNumpadDelete
eNumpadEqual
eNumpadMultiply
eNumpadAdd
eNumpadSeparator
eNumpadSubtract
eNumpadDecimal
eNumpadDivide
LightPassIdx
enum class castor3d::LightPassIdx : uint32_t strong
The lighting passes common bindings index.
Enumerator
eMaterials
eSssProfiles
eModels
eCamera
eDepthObj
eNmlOcc
eColMtl
eSpcRgh
eEmsTrn
eClrCot
eCrTsIr
eSheen
eCount
LightPassLgtIdx
enum class castor3d::LightPassLgtIdx : uint32_t strong
The lighting passes light specific bindings index.
Enumerator
eLights
eMatrix
eModelMatrix
eSmLinear
eSmLinearCmp
eSmVariance
eRandomStorage
eCount
LightType
enum class castor3d::LightType : uint8_t strong
Light types enumeration.
Enumerator
eDirectional
Directional light type.
ePoint
Point light type.
eSpot
Spot light type.
eCount
eMin
eMax
ListBoxEvent
enum class castor3d::ListBoxEvent : uint8_t strong
Enumeration of supported listbox events.
Enumerator
eSelected
Item selected.
eCount
The combobox events count.
LpTexture
enum class castor3d::LpTexture : uint8_t strong
Enumerator of textures used by the lighting pass in deferred rendering.
Enumerator
eDiffuse
eSpecular
eScattering
eCoatingSpecular
eSheen
eIndirectDiffuse
eIndirectSpecular
eCount
eMin
eMax
LpvTexture
enum class castor3d::LpvTexture : uint8_t strong
Enumerator of textures used by the light volume GI passes.
Enumerator
eR
eG
eB
eCount
eMin
eMax
MeshBuffersIdx
enum class castor3d::MeshBuffersIdx : uint32_t strong
The render pass mesh buffers binding index.
Enumerator
eMeshlets
eCullData
ePosition
eNormal
eTangent
eTexcoord0
eTexcoord1
eTexcoord2
eTexcoord3
eColour
ePassMasks
eVelocity
eInstances
eCount
eMin
eMax
MorphData
enum class castor3d::MorphData : uint32_t strong
Lists the supported morphing kinds for a submesh.
Enumerator
ePositions
The submesh has morphing positions.
eNormals
The submesh has morphing normals.
eTangents
The submesh has morphing tangents.
eTexcoords0
The submesh has morphing texture coordinates.
eTexcoords1
The submesh has a 2nd set of morphing texture coordinates.
eTexcoords2
The submesh has a 3rd set of morphing texture coordinates.
eTexcoords3
The submesh has a 4th set of morphing texture coordinates.
eColours
Submesh has a morphing colours.
eCount
eMin
eMax
MorphFlag
enum class castor3d::MorphFlag : uint32_t strong
Flags to determine what morphing is enabled on a submesh.
Enumerator
eNone
ePositions
The submesh has morphing positions.
eNormals
The submesh has morphing normals.
eTangents
The submesh has morphing tangents.
eTexcoords0
The submesh has morphing texture coordinates.
eTexcoords1
The submesh has a 2nd set of morphing texture coordinates.
eTexcoords2
The submesh has a 3rd set of morphing texture coordinates.
eTexcoords3
The submesh has a 4th set of morphing texture coordinates.
eColours
Submesh has morphing colours.
eAllBase
All flags used in base pipeline flags hashing.
MouseButton
enum class castor3d::MouseButton strong
Mouse buttons enumeration.
Enumerator
eLeft
Left mouse button.
eMiddle
Middle mouse button.
eRight
Right mouse button.
eCount
eMin
eMax
MouseCursor
enum class castor3d::MouseCursor strong
Mouse cursors enumeration.
Enumerator
eArrow
Usual arrow cursor.
eHand
Hand cursor.
eText
Text cursor.
eSizeWE
Arrows pointing left and right cursor.
eSizeNS
Arrows pointing up and down cursor.
eSizeNWSE
Diagonal arrows pointing top-left and bottom-right cursor.
eSizeNESW
Diagonal arrows pointing top-right and bottom-left cursor.
eCount
eMin
eMax
MouseEventType
enum class castor3d::MouseEventType : uint8_t strong
Enumeration of supported mouse events.
Enumration des vnement de souris supports.
Enumerator
eMove
The mouse moves.
eEnter
The mouse enters an handler's zone.
eHover
The mouse remains still in an handler's zone during hover time.
eLeave
The mouse leaves an handler's zone.
ePushed
One mouse button is pushed.
eReleased
One mouse button is released.
eWheel
One mouse wheel is rolled.
eCount
eMin
eMax
MovableType
enum class castor3d::MovableType : uint8_t strong
Movable object types enumerator.
Remarks
There are four movable object types : camera, geometry, light and billboard.
Enumerator
eCamera
eGeometry
eLight
eBillboard
eParticleEmitter
eCount
eMin
eMax
OverlayBindingId
enum class castor3d::OverlayBindingId : uint32_t strong
The descriptor binding indices for overlay rendering.
Enumerator
eMaterials
eTexConfigs
eTexAnims
eCamera
eOverlays
eOverlaysIDs
eOverlaysSurfaces
OverlayType
enum class castor3d::OverlayType : uint8_t strong
Overlay types enumeration.
Enumerator
ePanel
eBorderPanel
eText
eCount
eMin
eMax
ParallaxOcclusionMode
enum class castor3d::ParallaxOcclusionMode strong
Parallax occlusion modes enumeration.
Enumerator
eNone
eOne
eRepeat
eCount
eMin
eMax
ParticleFormat
enum class castor3d::ParticleFormat strong
Enumerator
eInt
eVec2i
eVec3i
eVec4i
eUInt
eVec2ui
eVec3ui
eVec4ui
eFloat
eVec2f
eVec3f
eVec4f
eMat2f
eMat3f
eMat4f
eCount
eMin
eMax
PassFlag
enum class castor3d::PassFlag : uint16_t strong
Pass specific flags.
Enumerator
eNone
No flag.
eAll
Mask for all the flags.
PickNodeType
enum class castor3d::PickNodeType : uint8_t strong
The picking node types.
Enumerator
eNone
eSubmesh
eBillboard
PluginType
enum class castor3d::PluginType : uint8_t strong
Plugin types enumeration.
Enumerator
eImporter
Importer plug-in.
eDivider
Mesh Divider plug-in.
eGenerator
Procedural generator.
eToneMapping
Tone mapping plug-in.
ePostEffect
Post effect plug-in.
eGeneric
Generic plug-in.
eParticle
Particle plug-in.
eCount
eMin
eMax
PpTexture
enum class castor3d::PpTexture : uint8_t strong
Enumerator of textures used by the deferred renderer's GBUffer.
Enumerator
eDepthObj
eVisibility
eCount
eMin
eMax
ProgramFlag
enum class castor3d::ProgramFlag : uint16_t strong
Flags to use when looking for an automatically generated program.
Enumerator
eNone
No flag.
eInstantiation
Program using instanciation.
eBillboards
Program used by billboards.
eInvertNormals
Vertex shader inverts normals.
eFrontCulled
Vertex shader inverts normals (for front culling).
eHasMesh
Render pass uses a mesh shader.
eAllBase
All flags used in base pipeline flags hashing.
eHasTask
Render pass uses a task shader.
eAllOptional
All other flags.
eAll
All flags.
eAllVisibility
All flags related to visibility buffer resolve.
ProgressFlag
enum class castor3d::ProgressFlag : ControlFlagType strong
Progress control supported flags.
Enumerator
eLeftRight
eRightLeft
eTopBottom
eBottomTop
QueueFamilyFlag
enum class castor3d::QueueFamilyFlag strong
Enumerator
eNone
ePresent
eGraphics
eTransfer
eCompute
RenderFilter
enum class castor3d::RenderFilter : uint8_t strong
Filters out the opacity channels a render pass doesn't use.
Enumerator
eNone
eAlphaBlend
Alpha blended opacity.
eAlphaTest
Alpha test opacity.
eTransmission
Materials with refraction.
eOpaque
Fully opaque (no opacity at all).
RenderNodeType
enum class castor3d::RenderNodeType : uint8_t strong
Enumerator
eFrontSubmesh
eFrontSubmeshMeshlet
eFrontSubmeshInstanced
eFrontBillboard
eBackSubmesh
eBackSubmeshMeshlet
eBackSubmeshInstanced
eBackBillboard
eCount
eMin
eMax
SceneFlag
enum class castor3d::SceneFlag : uint16_t strong
Scene flags enumeration.
Enumerator
eNone
No flag.
eFogLinear
Linear fog.
eFogExponential
Exponential fog.
eFogSquaredExponential
Squared exponential fog.
eShadowBegin
Shadow enabling, by light source type.
eShadowDirectional
eShadowPoint
eShadowSpot
eShadowEnd
eShadowAny
eLpvGI
Light Propagation Volumes enabling.
eLayeredLpvGI
eVoxelConeTracing
Voxel Cone Tracing enabling.
eGIAny
eAll
All flags.
ScrollBarEvent
enum class castor3d::ScrollBarEvent : uint8_t strong
Enumeration of supported combobox events.
Enumerator
eThumbRelease
The user has dropped the scroll thumb.
eThumbTrack
The user is dragging the scroll thumb.
eCount
The scrollbar events count.
ScrollBarFlag
enum class castor3d::ScrollBarFlag : ControlFlagType strong
ScrollBar control supported flags.
Enumerator
eHorizontal
eVertical
ShaderFlag
enum class castor3d::ShaderFlag : uint32_t strong
The render pass shader flags.
Enumerator
eNone
eNormal
Shader using normals.
eTangent
Shader using tangents.
eTangentSpace
Shader using tangent space.
eVelocity
Shader using velocity.
eWorldSpace
Shader using world space positions.
eViewSpace
Shader using view space positions.
eDepth
Shader for the depth pre-pass.
eVisibility
Shader for the visibility pre-pass.
ePicking
Shader for the picking pass.
eLighting
Shader supporting lighting.
eShadowMapDirectional
Shader used to render a shadow map for directional light.
eShadowMapSpot
Shader used to render a shadow map for spot light.
eShadowMapPoint
Shader used to render a shadow map for point light.
eVsmShadowMap
Writes to Variance shadow map.
eRsmShadowMap
Writes to Reflective shadow map.
eEnvironmentMapping
Shader used to render an environment map.
eOpacity
Shader using opacity.
eGeometry
Uses a geometry shader.
eTessellation
Uses tessellation shaders.
eForceTexCoords
Forces texcoords binding.
eColour
Shader uses the colour component.
eAll
All shader flags.
ShadowType
enum class castor3d::ShadowType strong
Shadow filter types enumeration.
Enumerator
eNone
No shadows at all.
eRaw
No filtering.
ePCF
PCF filtering.
eVariance
Variance shadow mapping.
eCount
eMin
eMax
SkeletonNodeType
enum class castor3d::SkeletonNodeType strong
Skeleton node types enumeration.
Enumerator
eNode
Node objects.
eBone
Bone objects.
eCount
eMin
eMax
SliderEvent
enum class castor3d::SliderEvent : uint8_t strong
Enumeration of supported slider events.
Enumerator
eThumbRelease
Slider thumb release.
eThumbTrack
Slider thumb track.
eCount
The slider events count.
SliderFlag
enum class castor3d::SliderFlag : ControlFlagType strong
Slider control supported flags.
Enumerator
eHorizontal
eVertical
SmTexture
enum class castor3d::SmTexture : uint8_t strong
Enumerator of textures used in deferred rendering.
Enumerator
eDepth
eLinearDepth
eVariance
eNormal
ePosition
eFlux
eCount
eMin
eMax
StaticFlag
enum class castor3d::StaticFlag : ControlFlagType strong
Static control supported flags.
Enumerator
eHAlignLeft
The static's text is left aligned.
eHAlignCenter
The static's text is horizontally centered.
eHAlignRight
The static's text is right aligned.
eVAlignTop
The static's text is aligned on top.
eVAlignCenter
The static's text is vertically centered.
eVAlignBottom
The static's text is aligned on bottom.
SubmeshData
enum class castor3d::SubmeshData : uint8_t strong
Lists the supported data kinds for a submesh.
Enumerator
eIndex
The submesh has indices.
ePositions
The submesh has positions.
eNormals
The submesh has normals.
eTangents
The submesh has tangents.
eTexcoords0
Submesh has texture coordinates.
eTexcoords1
Submesh has a 2nd set of texture coordinates.
eTexcoords2
Submesh has a 3rd set of texture coordinates.
eTexcoords3
Submesh has a 4th set of texture coordinates.
eColours
Submesh has colours.
eOtherMin
Minimum value for components not derived from BaseDataComponentT.
eSkin
Submesh has skin data.
ePassMasks
Submesh has subpasses masks.
eVelocity
Submesh has velocity data.
eCount
eMin
eMax
SubmeshFlag
enum class castor3d::SubmeshFlag : uint16_t strong
Flags to determine what a submesh is using.
Enumerator
eNone
eIndex
The submesh has indices (always).
ePositions
The submesh has positions.
eNormals
The submesh has normals.
eTangents
The submesh has tangents.
eTexcoords0
Submesh has texture coordinates.
eTexcoords1
Submesh has a 2nd set of texture coordinates.
eTexcoords2
Submesh has a 3rd set of texture coordinates.
eTexcoords3
Submesh has a 4th set of texture coordinates.
eTexcoords
Submesh has texture coordinates.
eColours
Submesh has colours.
ePosNmlTanTex
Base components flags.
eSkin
Submesh has bones data.
ePassMasks
Submesh has velocity data.
eVelocity
Submesh has velocity data.
eAllBase
All flags used in base pipeline flags hashing.
TargetType
enum class castor3d::TargetType : uint8_t strong
RenderTarget supported types.
Enumerator
eWindow
eTexture
eCount
eMin
eMax
TechniquePassEvent
enum class castor3d::TechniquePassEvent strong
Enumerator
eBeforeDepth
eBeforeBackground
eBeforeOpaque
eBeforeTransparent
eBeforePostEffects
eCount
eMin
eMax
TextLineSpacingMode
enum class castor3d::TextLineSpacingMode strong
Text line spacing modes, handles the way lines are spaced, which each other, inside one TextOverlay.
Enumerator
eOwnHeight
The height of each line is its own height.
eMaxLineHeight
The height of the lines is the maximum height between them.
eMaxFontHeight
The height of the lines is the maximum height from the font's characters.
eCount
eMin
eMax
TextTexturingMode
enum class castor3d::TextTexturingMode strong
Text texturing modes, handles the way textures are appied to text overlays.
Enumerator
eLetter
The texture is repeated on each character of the text.
eText
The texture is applied on the whole text.
eCount
eMin
eMax
TextureFlag
enum class castor3d::TextureFlag : uint8_t strong
Texture flags.
Enumerator
eNone
No flag.
eAll
Mask for all the flags.
TextureSpace
enum class castor3d::TextureSpace : uint16_t strong
Lists the possible spaces for a texture.
Enumerator
eNone
eNormalised
Modifier: Normalized value (Colour in [0, 1] range, depth in [0, 1] range).
eYInverted
Modifier: Y inverted space.
eColour
Colour texture.
eDepth
Depth in [near, far] range.
eTangentSpace
Tangent space data.
eObjectSpace
Object space data.
eWorldSpace
World space data.
eViewSpace
View space data.
eClipSpace
Clip space data.
eStencil
Stencil data.
eAllowSRGB
Allows SRGB formats.
TextWrappingMode
enum class castor3d::TextWrappingMode strong
Text wrapping modes, handles the way text is cut when it overflows the overlay width.
Enumerator
eNone
The text is cut.
eBreak
The text jumps to next line.
eBreakWords
The text jumps to next line without cutting words.
eCount
eMin
eMax
UserInputEventType
enum class castor3d::UserInputEventType strong
Supported events types enumeration.
Enumerator
eMouse
Mouse event type.
eKeyboard
Keyboard event type.
eHandler
Handle event type.
eCount
eMin
eMax
VAlign
enum class castor3d::VAlign strong
Vertical alignments for text overlays.
Enumerator
eTop
Aligned on the top.
eCenter
Centered vertically.
eBottom
Aligned on the bottom.
eCount
eMin
eMax
ViewportType
enum class castor3d::ViewportType : uint8_t strong
The viewport projection types enumeration.
Enumerator
eUndefined
eOrtho
ePerspective
eInfinitePerspective
eFrustum
eCount
eMin
eMax
WbTexture
enum class castor3d::WbTexture : uint8_t strong
Enumerator of textures used in weighted blend OIT.
Enumerator
eAccumulation
eRevealage
eCount
eMin
eMax
Function Documentation
addFlagConfiguration()
C3D_API void castor3d::addFlagConfiguration (TextureConfiguration & config, TextureFlagConfiguration flagConfiguration)
Referenced by castor3d::AttenuationMapComponent::Plugin::fillTextureConfiguration(), castor3d::ClearcoatMapComponent::Plugin::fillTextureConfiguration(), castor3d::ClearcoatNormalMapComponent::Plugin::fillTextureConfiguration(), castor3d::ClearcoatRoughnessMapComponent::Plugin::fillTextureConfiguration(), castor3d::ColourMapComponent::Plugin::fillTextureConfiguration(), castor3d::EmissiveMapComponent::Plugin::fillTextureConfiguration(), castor3d::GlossinessMapComponent::Plugin::fillTextureConfiguration(), castor3d::HeightMapComponent::Plugin::fillTextureConfiguration(), castor3d::IridescenceMapComponent::Plugin::fillTextureConfiguration(), castor3d::IridescenceThicknessMapComponent::Plugin::fillTextureConfiguration(), castor3d::MetalnessMapComponent::Plugin::fillTextureConfiguration(), castor3d::NormalMapComponent::Plugin::fillTextureConfiguration(), castor3d::OcclusionMapComponent::Plugin::fillTextureConfiguration(), castor3d::OpacityMapComponent::Plugin::fillTextureConfiguration(), castor3d::RoughnessMapComponent::Plugin::fillTextureConfiguration(), castor3d::SheenMapComponent::Plugin::fillTextureConfiguration(), castor3d::SheenRoughnessMapComponent::Plugin::fillTextureConfiguration(), castor3d::SpecularFactorMapComponent::Plugin::fillTextureConfiguration(), castor3d::SpecularMapComponent::Plugin::fillTextureConfiguration(), castor3d::TransmissionMapComponent::Plugin::fillTextureConfiguration(), and castor3d::TransmittanceMapComponent::Plugin::fillTextureConfiguration().
addFlags() [1/4]
C3D_API void castor3d::addFlags (PassComponentCombine & lhs, PassComponentFlag rhs)
addFlags() [2/4]
C3D_API void castor3d::addFlags (PassComponentCombine & lhs, PassComponentFlagsSet const & rhs)
addFlags() [3/4]
C3D_API void castor3d::addFlags (TextureCombine & lhs, PassComponentTextureFlag rhs)
addFlags() [4/4]
C3D_API void castor3d::addFlags (TextureCombine & lhs, TextureFlagsSet const & rhs)
bindBuffer() [1/2]
C3D_API void castor3d::bindBuffer (ashes::BufferBase const & buffer, ashes::WriteDescriptorSetArray & writes, uint32_t & index)
bindBuffer() [2/2]
C3D_API void castor3d::bindBuffer (VkBuffer buffer, VkDeviceSize offset, VkDeviceSize range, ashes::WriteDescriptorSetArray & writes, uint32_t & index)
Writes the buffer descriptor to the given writes.
bindTexture() [1/3]
C3D_API void castor3d::bindTexture (ashes::ImageView const & view, ashes::Sampler const & sampler, ashes::WriteDescriptorSetArray & writes, uint32_t & index)
bindTexture() [2/3]
C3D_API void castor3d::bindTexture (crg::RunnableGraph & graph, crg::ImageViewId const & view, VkSampler const & sampler, ashes::WriteDescriptorSetArray & writes, uint32_t & index)
bindTexture() [3/3]
C3D_API void castor3d::bindTexture (VkImageView view, VkSampler sampler, ashes::WriteDescriptorSetArray & writes, uint32_t & index)
Writes the image view and sampler descriptor to the given writes.
checkFlag() [1/3]
C3D_API TextureFlagsSet::const_iterator castor3d::checkFlag (TextureCombine const & lhs, PassComponentTextureFlag rhs)
Referenced by castor3d::BlendComponent::Plugin::filterComponentFlags(), castor3d::SubsurfaceScatteringComponent::Plugin::filterComponentFlags(), castor3d::AlphaTestComponent::Plugin::filterComponentFlags(), castor3d::HeightComponent::Plugin::filterComponentFlags(), castor3d::AttenuationMapComponent::Plugin::filterTextureFlags(), castor3d::ClearcoatMapComponent::Plugin::filterTextureFlags(), castor3d::ClearcoatNormalMapComponent::Plugin::filterTextureFlags(), castor3d::ClearcoatRoughnessMapComponent::Plugin::filterTextureFlags(), castor3d::ColourMapComponent::Plugin::filterTextureFlags(), castor3d::EmissiveMapComponent::Plugin::filterTextureFlags(), castor3d::GlossinessMapComponent::Plugin::filterTextureFlags(), castor3d::HeightMapComponent::Plugin::filterTextureFlags(), castor3d::IridescenceMapComponent::Plugin::filterTextureFlags(), castor3d::IridescenceThicknessMapComponent::Plugin::filterTextureFlags(), castor3d::MetalnessMapComponent::Plugin::filterTextureFlags(), castor3d::NormalMapComponent::Plugin::filterTextureFlags(), castor3d::OcclusionMapComponent::Plugin::filterTextureFlags(), castor3d::OpacityMapComponent::Plugin::filterTextureFlags(), castor3d::RoughnessMapComponent::Plugin::filterTextureFlags(), castor3d::SheenMapComponent::Plugin::filterTextureFlags(), castor3d::SheenRoughnessMapComponent::Plugin::filterTextureFlags(), castor3d::SpecularFactorMapComponent::Plugin::filterTextureFlags(), castor3d::SpecularMapComponent::Plugin::filterTextureFlags(), castor3d::TransmissionMapComponent::Plugin::filterTextureFlags(), castor3d::TransmittanceMapComponent::Plugin::filterTextureFlags(), castor3d::PipelineFlags::forceTexCoords(), castor3d::AttenuationMapComponent::Plugin::getTextureFlagsName(), castor3d::ClearcoatMapComponent::Plugin::getTextureFlagsName(), castor3d::ClearcoatNormalMapComponent::Plugin::getTextureFlagsName(), castor3d::ClearcoatRoughnessMapComponent::Plugin::getTextureFlagsName(), castor3d::ColourMapComponent::Plugin::getTextureFlagsName(), castor3d::EmissiveMapComponent::Plugin::getTextureFlagsName(), castor3d::GlossinessMapComponent::Plugin::getTextureFlagsName(), castor3d::HeightMapComponent::Plugin::getTextureFlagsName(), castor3d::IridescenceMapComponent::Plugin::getTextureFlagsName(), castor3d::IridescenceThicknessMapComponent::Plugin::getTextureFlagsName(), castor3d::MetalnessMapComponent::Plugin::getTextureFlagsName(), castor3d::NormalMapComponent::Plugin::getTextureFlagsName(), castor3d::OcclusionMapComponent::Plugin::getTextureFlagsName(), castor3d::OpacityMapComponent::Plugin::getTextureFlagsName(), castor3d::RoughnessMapComponent::Plugin::getTextureFlagsName(), castor3d::SheenMapComponent::Plugin::getTextureFlagsName(), castor3d::SheenRoughnessMapComponent::Plugin::getTextureFlagsName(), castor3d::SpecularFactorMapComponent::Plugin::getTextureFlagsName(), castor3d::SpecularMapComponent::Plugin::getTextureFlagsName(), castor3d::TransmissionMapComponent::Plugin::getTextureFlagsName(), castor3d::TransmittanceMapComponent::Plugin::getTextureFlagsName(), castor3d::GpuInformations::hasFeature(), castor3d::PipelineFlags::hasInvertNormals(), castor3d::PipelineFlags::hasSubmeshData(), castor3d::PipelineFlags::isBillboard(), castor3d::NormalComponent::Plugin::isComponentNeeded(), castor3d::PipelineFlags::isFrontCulled(), castor3d::PipelineFlags::usesColour(), castor3d::PipelineFlags::usesGeometry(), castor3d::PipelineFlags::usesMesh(), castor3d::PipelineFlags::usesOpacity(), castor3d::PipelineFlags::usesTask(), castor3d::PipelineFlags::usesTessellation(), castor3d::PipelineFlags::usesViewSpace(), castor3d::PipelineFlags::usesWorldSpace(), castor3d::PipelineFlags::writeDepth(), castor3d::PipelineFlags::writeEnvironmentMap(), castor3d::PipelineFlags::writePicking(), castor3d::PipelineFlags::writeShadowMap(), castor3d::PipelineFlags::writeShadowRSM(), castor3d::PipelineFlags::writeShadowVSM(), castor3d::PipelineFlags::writeVelocity(), and castor3d::PipelineFlags::writeVisibility().
checkFlag() [2/3]
C3D_API TextureFlagConfigurations::iterator castor3d::checkFlag (TextureFlagConfigurations & lhs, PassComponentTextureFlag rhs)
checkFlag() [3/3]
C3D_API TextureFlagConfigurations::const_iterator castor3d::checkFlag (TextureFlagConfigurations const & lhs, PassComponentTextureFlag rhs)
cleanupGlslang()
C3D_API void castor3d::cleanupGlslang ()
Cleans up glslang globals.
compileGlslToSpv()
C3D_API UInt32Array castor3d::compileGlslToSpv (RenderDevice const & device, VkShaderStageFlagBits stage, std::string const & shader)
Transpiles a GLSL shader to SPIR-V.
Parameters
device The GPU device.
stage The shader stage.
shader The GLSL shader.
compileShader() [1/2]
C3D_API SpirVShader const & castor3d::compileShader (RenderDevice const & device, ShaderModule & module)
compileShader() [2/2]
C3D_API SpirVShader const & castor3d::compileShader (RenderSystem const & renderSystem, ShaderModule & module)
contains() [1/3]
C3D_API bool castor3d::contains (PassComponentCombine const & cont, PassComponentCombine const & test)
contains() [2/3]
C3D_API bool castor3d::contains (PassComponentCombine const & cont, PassComponentFlag test)
contains() [3/3]
C3D_API bool castor3d::contains (TextureCombine const & cont, TextureCombine const & test)
convert() [1/5]
C3D_API VkFormat castor3d::convert (castor::PixelFormat format)
convert() [2/5]
VkClearColorValue castor3d::convert (castor::RgbaColour const & value)
convert() [3/5]
castor::Matrix4x4f castor3d::convert (std::array< float, 16 > const & value)
convert() [4/5]
castor::RgbaColour castor3d::convert (VkClearColorValue const & value)
convert() [5/5]
C3D_API castor::PixelFormat castor3d::convert (VkFormat format)
copyBuffer() [1/2]
C3D_API void castor3d::copyBuffer (ashes::CommandBuffer const & commandBuffer, ashes::BufferBase const & src, ashes::BufferBase const & dst, std::vector< VkBufferCopy > const & regions, VkAccessFlags dstAccessFlags, VkPipelineStageFlags dstPipelineFlags)
copyBuffer() [2/2]
C3D_API void castor3d::copyBuffer (ashes::CommandBuffer const & commandBuffer, ashes::BufferBase const & src, ashes::BufferBase const & dst, VkDeviceSize offset, VkDeviceSize size, VkPipelineStageFlags flags)
createInOutStoragePassBinding() [1/2]
C3D_API void castor3d::createInOutStoragePassBinding (crg::FramePass & pass, uint32_t binding, std::string const & name, ashes::Buffer< uint8_t > const & buffer, VkDeviceSize offset, VkDeviceSize size)
createInOutStoragePassBinding() [2/2]
C3D_API void castor3d::createInOutStoragePassBinding (crg::FramePass & pass, uint32_t binding, std::string const & name, ashes::BufferBase const & buffer, VkDeviceSize offset, VkDeviceSize size)
Referenced by castor3d::GpuBufferOffsetT< DataT >::createInOutStoragePassBinding(), and castor3d::ObjectBufferOffset::GpuBufferChunk::createInOutStoragePassBinding().
createInputStoragePassBinding() [1/2]
C3D_API void castor3d::createInputStoragePassBinding (crg::FramePass & pass, uint32_t binding, std::string const & name, ashes::Buffer< uint8_t > const & buffer, VkDeviceSize offset, VkDeviceSize size)
createInputStoragePassBinding() [2/2]
C3D_API void castor3d::createInputStoragePassBinding (crg::FramePass & pass, uint32_t binding, std::string const & name, ashes::BufferBase const & buffer, VkDeviceSize offset, VkDeviceSize size)
Referenced by castor3d::GpuBufferOffsetT< DataT >::createInputStoragePassBinding(), and castor3d::ObjectBufferOffset::GpuBufferChunk::createInputStoragePassBinding().
createMaterial() [1/2]
MaterialObs castor3d::createMaterial (Engine & engine, castor::String const & name, castor::HdrRgbColour const & colour)
Creates a colour material.
Parameters
[in] engine The engine.
[in] name The material name.
[in] colour The material colour.
Returns
The created material.
Referenced by castor3d::ControlStyle::doCreateMaterial().
createMaterial() [2/2]
MaterialObs castor3d::createMaterial (Engine & engine, castor::String const & name, TextureLayoutUPtr texture)
Creates a texture material.
Parameters
[in] engine The engine.
[in] name The material name.
[in] texture The material texture.
Returns
The created material.
createOutputStoragePassBinding() [1/2]
C3D_API void castor3d::createOutputStoragePassBinding (crg::FramePass & pass, uint32_t binding, std::string const & name, ashes::Buffer< uint8_t > const & buffer, VkDeviceSize offset, VkDeviceSize size)
createOutputStoragePassBinding() [2/2]
C3D_API void castor3d::createOutputStoragePassBinding (crg::FramePass & pass, uint32_t binding, std::string const & name, ashes::BufferBase const & buffer, VkDeviceSize offset, VkDeviceSize size)
Referenced by castor3d::GpuBufferOffsetT< DataT >::createOutputStoragePassBinding(), and castor3d::ObjectBufferOffset::GpuBufferChunk::createOutputStoragePassBinding().
createSampler()
SamplerObs castor3d::createSampler (Engine & engine, castor::String const & baseName, VkFilter filter, VkImageSubresourceRange const * range)
createTextureLayout() [1/2]
C3D_API TextureLayoutUPtr castor3d::createTextureLayout (Engine const & engine, castor::Path const & relative, castor::Path const & folder, castor::ImageLoaderConfig config = { true, true, true })
createTextureLayout() [2/2]
C3D_API TextureLayoutUPtr castor3d::createTextureLayout (Engine const & engine, castor::String const & name, castor::PxBufferBaseUPtr buffer, bool isStatic = false)
createUniformPassBinding() [1/2]
C3D_API void castor3d::createUniformPassBinding (crg::FramePass & pass, uint32_t binding, std::string const & name, ashes::Buffer< uint8_t > const & buffer, VkDeviceSize offset, VkDeviceSize size)
createUniformPassBinding() [2/2]
C3D_API void castor3d::createUniformPassBinding (crg::FramePass & pass, uint32_t binding, std::string const & name, ashes::BufferBase const & buffer, VkDeviceSize offset, VkDeviceSize size)
Referenced by castor3d::GpuBufferOffsetT< DataT >::createUniformPassBinding(), and castor3d::ObjectBufferOffset::GpuBufferChunk::createUniformPassBinding().
CU_DeclareArray()
castor3d::CU_DeclareArray (PluginStrMap , PluginType::eCount , PluginStrMap)
CU_DeclareEnumTemplateSmartPtr()
castor3d::CU_DeclareEnumTemplateSmartPtr (castor3d , BaseDataComponent , castor3d::SubmeshFlag)
CU_DeclareMap() [1/16]
castor3d::CU_DeclareMap (castor::Path , PluginType , PluginTypePath)
CU_DeclareMap() [2/16]
castor3d::CU_DeclareMap (castor::String , int , IntStr)
CU_DeclareMap() [3/16]
castor3d::CU_DeclareMap (castor::String , MaterialObs , MaterialPtrStr)
Material pointer map, sorted by name.
CU_DeclareMap() [4/16]
castor3d::CU_DeclareMap (castor::String , MeshResPtr , MeshPtrStr)
Mesh pointer array.
CU_DeclareMap() [5/16]
castor3d::CU_DeclareMap (castor::String , OverlayResPtr , OverlayPtrStr)
CU_DeclareMap() [6/16]
castor3d::CU_DeclareMap (castor::String , PluginUPtr , PluginStr)
CU_DeclareMap() [7/16]
castor3d::CU_DeclareMap (castor::String , SceneRPtr , ScenePtrStr)
Scene pointer map, sorted by name.
CU_DeclareMap() [8/16]
castor3d::CU_DeclareMap (int , castor::String , StrInt)
CU_DeclareMap() [9/16]
castor3d::CU_DeclareMap (PassComponentID , PassComponentUPtr , PassComponent)
CU_DeclareMap() [10/16]
castor3d::CU_DeclareMap (Submesh const * , castor::BoundingBox , SubmeshBoundingBox)
CU_DeclareMap() [11/16]
castor3d::CU_DeclareMap (Submesh const * , castor::BoundingSphere , SubmeshBoundingSphere)
CU_DeclareMap() [12/16]
castor3d::CU_DeclareMap (uint32_t , int , IntUInt)
CU_DeclareMap() [13/16]
castor3d::CU_DeclareMap (uint32_t , MaterialObs , MaterialPtrUInt)
Material pointer map.
CU_DeclareMap() [14/16]
castor3d::CU_DeclareMap (uint32_t , MeshAnimationInstanceSubmesh , MeshAnimationInstanceSubmesh)
MeshAnimationInstanceSubmesh map, sorted by submesh ID.
CU_DeclareMap() [15/16]
castor3d::CU_DeclareMap (uint32_t , std::vector< float > , SubmeshTargetWeight)
CU_DeclareMap() [16/16]
castor3d::CU_DeclareMap (uint32_t , SubmeshComponentUPtr , SubmeshComponentID)
CU_DeclareSmartPtr() [1/327]
castor3d::CU_DeclareSmartPtr (castor3d , AlphaTestComponent , C3D_API)
CU_DeclareSmartPtr() [2/327]
castor3d::CU_DeclareSmartPtr (castor3d , AmbientComponent , C3D_API)
CU_DeclareSmartPtr() [3/327]
castor3d::CU_DeclareSmartPtr (castor3d , Animable , C3D_API)
CU_DeclareSmartPtr() [4/327]
castor3d::CU_DeclareSmartPtr (castor3d , AnimatedMesh , C3D_API)
CU_DeclareSmartPtr() [5/327]
castor3d::CU_DeclareSmartPtr (castor3d , AnimatedObject , C3D_API)
CU_DeclareSmartPtr() [6/327]
castor3d::CU_DeclareSmartPtr (castor3d , AnimatedObjectGroup , C3D_API)
CU_DeclareSmartPtr() [7/327]
castor3d::CU_DeclareSmartPtr (castor3d , AnimatedObjectGroupCache , C3D_API)
CU_DeclareSmartPtr() [8/327]
castor3d::CU_DeclareSmartPtr (castor3d , AnimatedSceneNode , C3D_API)
CU_DeclareSmartPtr() [9/327]
castor3d::CU_DeclareSmartPtr (castor3d , AnimatedSkeleton , C3D_API)
CU_DeclareSmartPtr() [10/327]
castor3d::CU_DeclareSmartPtr (castor3d , AnimatedTexture , C3D_API)
CU_DeclareSmartPtr() [11/327]
castor3d::CU_DeclareSmartPtr (castor3d , Animation , C3D_API)
CU_DeclareSmartPtr() [12/327]
castor3d::CU_DeclareSmartPtr (castor3d , AnimationImporter , C3D_API)
CU_DeclareSmartPtr() [13/327]
castor3d::CU_DeclareSmartPtr (castor3d , AnimationImporterFactory , C3D_API)
CU_DeclareSmartPtr() [14/327]
castor3d::CU_DeclareSmartPtr (castor3d , AnimationInstance , C3D_API)
CU_DeclareSmartPtr() [15/327]
castor3d::CU_DeclareSmartPtr (castor3d , AnimationKeyFrame , C3D_API)
Referenced by castor3d::shader::CU_DeclareSmartPtr().
CU_DeclareSmartPtr() [16/327]
castor3d::CU_DeclareSmartPtr (castor3d , AttenuationComponent , C3D_API)
CU_DeclareSmartPtr() [17/327]
castor3d::CU_DeclareSmartPtr (castor3d , AttenuationMapComponent , C3D_API)
CU_DeclareSmartPtr() [18/327]
castor3d::CU_DeclareSmartPtr (castor3d , BackgroundRenderer , C3D_API)
CU_DeclareSmartPtr() [19/327]
castor3d::CU_DeclareSmartPtr (castor3d , BillboardBase , C3D_API)
CU_DeclareSmartPtr() [20/327]
castor3d::CU_DeclareSmartPtr (castor3d , BillboardList , C3D_API)
CU_DeclareSmartPtr() [21/327]
castor3d::CU_DeclareSmartPtr (castor3d , BillboardRenderNode , C3D_API)
CU_DeclareSmartPtr() [22/327]
castor3d::CU_DeclareSmartPtr (castor3d , BlendComponent , C3D_API)
CU_DeclareSmartPtr() [23/327]
castor3d::CU_DeclareSmartPtr (castor3d , BoneNode , C3D_API)
CU_DeclareSmartPtr() [24/327]
castor3d::CU_DeclareSmartPtr (castor3d , BorderPanelOverlay , C3D_API)
CU_DeclareSmartPtr() [25/327]
castor3d::CU_DeclareSmartPtr (castor3d , ButtonCtrl , C3D_API)
CU_DeclareSmartPtr() [26/327]
castor3d::CU_DeclareSmartPtr (castor3d , ButtonStyle , C3D_API)
CU_DeclareSmartPtr() [27/327]
castor3d::CU_DeclareSmartPtr (castor3d , Camera , C3D_API)
CU_DeclareSmartPtr() [28/327]
castor3d::CU_DeclareSmartPtr (castor3d , ClearcoatComponent , C3D_API)
CU_DeclareSmartPtr() [29/327]
castor3d::CU_DeclareSmartPtr (castor3d , ClearcoatMapComponent , C3D_API)
CU_DeclareSmartPtr() [30/327]
castor3d::CU_DeclareSmartPtr (castor3d , ClearcoatNormalMapComponent , C3D_API)
CU_DeclareSmartPtr() [31/327]
castor3d::CU_DeclareSmartPtr (castor3d , ClearcoatRoughnessMapComponent , C3D_API)
CU_DeclareSmartPtr() [32/327]
castor3d::CU_DeclareSmartPtr (castor3d , ColourBackground , C3D_API)
CU_DeclareSmartPtr() [33/327]
castor3d::CU_DeclareSmartPtr (castor3d , ColourComponent , C3D_API)
CU_DeclareSmartPtr() [34/327]
castor3d::CU_DeclareSmartPtr (castor3d , ColourMapComponent , C3D_API)
CU_DeclareSmartPtr() [35/327]
castor3d::CU_DeclareSmartPtr (castor3d , CombinePass , C3D_API)
CU_DeclareSmartPtr() [36/327]
castor3d::CU_DeclareSmartPtr (castor3d , ComboBoxCtrl , C3D_API)
CU_DeclareSmartPtr() [37/327]
castor3d::CU_DeclareSmartPtr (castor3d , ComboBoxStyle , C3D_API)
CU_DeclareSmartPtr() [38/327]
castor3d::CU_DeclareSmartPtr (castor3d , ComputeParticleSystem , C3D_API)
CU_DeclareSmartPtr() [39/327]
castor3d::CU_DeclareSmartPtr (castor3d , Cone , C3D_API)
CU_DeclareSmartPtr() [40/327]
castor3d::CU_DeclareSmartPtr (castor3d , Control , C3D_API)
CU_DeclareSmartPtr() [41/327]
castor3d::CU_DeclareSmartPtr (castor3d , ControlsManager , C3D_API)
CU_DeclareSmartPtr() [42/327]
castor3d::CU_DeclareSmartPtr (castor3d , ControlStyle , C3D_API)
CU_DeclareSmartPtr() [43/327]
castor3d::CU_DeclareSmartPtr (castor3d , CpuFrameEvent , C3D_API)
CU_DeclareSmartPtr() [44/327]
castor3d::CU_DeclareSmartPtr (castor3d , CpuFunctorEvent , C3D_API)
CU_DeclareSmartPtr() [45/327]
castor3d::CU_DeclareSmartPtr (castor3d , CpuParticleSystem , C3D_API)
CU_DeclareSmartPtr() [46/327]
castor3d::CU_DeclareSmartPtr (castor3d , Cube , C3D_API)
CU_DeclareSmartPtr() [47/327]
castor3d::CU_DeclareSmartPtr (castor3d , Cylinder , C3D_API)
CU_DeclareSmartPtr() [48/327]
castor3d::CU_DeclareSmartPtr (castor3d , DebugOverlays , C3D_API)
CU_DeclareSmartPtr() [49/327]
castor3d::CU_DeclareSmartPtr (castor3d , DeferredRendering , C3D_API)
CU_DeclareSmartPtr() [50/327]
castor3d::CU_DeclareSmartPtr (castor3d , DepthPass , C3D_API)
CU_DeclareSmartPtr() [51/327]
castor3d::CU_DeclareSmartPtr (castor3d , DirectionalLight , C3D_API)
CU_DeclareSmartPtr() [52/327]
castor3d::CU_DeclareSmartPtr (castor3d , DividerPlugin , C3D_API)
CU_DeclareSmartPtr() [53/327]
castor3d::CU_DeclareSmartPtr (castor3d , DownscalePass , C3D_API)
CU_DeclareSmartPtr() [54/327]
castor3d::CU_DeclareSmartPtr (castor3d , EditCtrl , C3D_API)
CU_DeclareSmartPtr() [55/327]
castor3d::CU_DeclareSmartPtr (castor3d , EditStyle , C3D_API)
CU_DeclareSmartPtr() [56/327]
castor3d::CU_DeclareSmartPtr (castor3d , EmissiveComponent , C3D_API)
CU_DeclareSmartPtr() [57/327]
castor3d::CU_DeclareSmartPtr (castor3d , EmissiveMapComponent , C3D_API)
CU_DeclareSmartPtr() [58/327]
castor3d::CU_DeclareSmartPtr (castor3d , Engine)
CU_DeclareSmartPtr() [59/327]
castor3d::CU_DeclareSmartPtr (castor3d , EnvironmentMap , C3D_API)
CU_DeclareSmartPtr() [60/327]
castor3d::CU_DeclareSmartPtr (castor3d , EnvironmentMapPass , C3D_API)
CU_DeclareSmartPtr() [61/327]
castor3d::CU_DeclareSmartPtr (castor3d , EquirectangularToCube , C3D_API)
CU_DeclareSmartPtr() [62/327]
castor3d::CU_DeclareSmartPtr (castor3d , EventHandler , C3D_API)
CU_DeclareSmartPtr() [63/327]
castor3d::CU_DeclareSmartPtr (castor3d , ExpandablePanelCtrl , C3D_API)
CU_DeclareSmartPtr() [64/327]
castor3d::CU_DeclareSmartPtr (castor3d , ExpandablePanelStyle , C3D_API)
CU_DeclareSmartPtr() [65/327]
castor3d::CU_DeclareSmartPtr (castor3d , FontGlyphBuffer , C3D_API)
CU_DeclareSmartPtr() [66/327]
castor3d::CU_DeclareSmartPtr (castor3d , FontTexture , C3D_API)
CU_DeclareSmartPtr() [67/327]
castor3d::CU_DeclareSmartPtr (castor3d , FractalMappingComponent , C3D_API)
CU_DeclareSmartPtr() [68/327]
castor3d::CU_DeclareSmartPtr (castor3d , FrameCtrl , C3D_API)
CU_DeclareSmartPtr() [69/327]
castor3d::CU_DeclareSmartPtr (castor3d , FrameListener , C3D_API)
CU_DeclareSmartPtr() [70/327]
castor3d::CU_DeclareSmartPtr (castor3d , FrameListenerCache , C3D_API)
CU_DeclareSmartPtr() [71/327]
castor3d::CU_DeclareSmartPtr (castor3d , FramePassTimer)
CU_DeclareSmartPtr() [72/327]
castor3d::CU_DeclareSmartPtr (castor3d , FrameStyle , C3D_API)
CU_DeclareSmartPtr() [73/327]
castor3d::CU_DeclareSmartPtr (castor3d , Frustum , C3D_API)
CU_DeclareSmartPtr() [74/327]
castor3d::CU_DeclareSmartPtr (castor3d , GaussianBlur , C3D_API)
CU_DeclareSmartPtr() [75/327]
castor3d::CU_DeclareSmartPtr (castor3d , GeneratorPlugin , C3D_API)
CU_DeclareSmartPtr() [76/327]
castor3d::CU_DeclareSmartPtr (castor3d , GenericPlugin , C3D_API)
CU_DeclareSmartPtr() [77/327]
castor3d::CU_DeclareSmartPtr (castor3d , Geometry , C3D_API)
CU_DeclareSmartPtr() [78/327]
castor3d::CU_DeclareSmartPtr (castor3d , GeometryCache , C3D_API)
CU_DeclareSmartPtr() [79/327]
castor3d::CU_DeclareSmartPtr (castor3d , GeometryInjectionPass , C3D_API)
CU_DeclareSmartPtr() [80/327]
castor3d::CU_DeclareSmartPtr (castor3d , GlossinessMapComponent , C3D_API)
CU_DeclareSmartPtr() [81/327]
castor3d::CU_DeclareSmartPtr (castor3d , GpuBufferPool , C3D_API)
CU_DeclareSmartPtr() [82/327]
castor3d::CU_DeclareSmartPtr (castor3d , GpuFrameEvent , C3D_API)
CU_DeclareSmartPtr() [83/327]
castor3d::CU_DeclareSmartPtr (castor3d , GpuFunctorEvent , C3D_API)
CU_DeclareSmartPtr() [84/327]
castor3d::CU_DeclareSmartPtr (castor3d , HeightComponent , C3D_API)
CU_DeclareSmartPtr() [85/327]
castor3d::CU_DeclareSmartPtr (castor3d , HeightMapComponent , C3D_API)
CU_DeclareSmartPtr() [86/327]
castor3d::CU_DeclareSmartPtr (castor3d , IblTextures , C3D_API)
CU_DeclareSmartPtr() [87/327]
castor3d::CU_DeclareSmartPtr (castor3d , Icosahedron , C3D_API)
CU_DeclareSmartPtr() [88/327]
castor3d::CU_DeclareSmartPtr (castor3d , ImageBackground , C3D_API)
CU_DeclareSmartPtr() [89/327]
castor3d::CU_DeclareSmartPtr (castor3d , ImporterFile)
CU_DeclareSmartPtr() [90/327]
castor3d::CU_DeclareSmartPtr (castor3d , ImporterFileFactory)
CU_DeclareSmartPtr() [91/327]
castor3d::CU_DeclareSmartPtr (castor3d , ImporterPlugin , C3D_API)
CU_DeclareSmartPtr() [92/327]
castor3d::CU_DeclareSmartPtr (castor3d , IndexMapping , C3D_API)
CU_DeclareSmartPtr() [93/327]
castor3d::CU_DeclareSmartPtr (castor3d , IndirectLightingPass , C3D_API)
CU_DeclareSmartPtr() [94/327]
castor3d::CU_DeclareSmartPtr (castor3d , InstantiationComponent , C3D_API)
CU_DeclareSmartPtr() [95/327]
castor3d::CU_DeclareSmartPtr (castor3d , IridescenceComponent , C3D_API)
CU_DeclareSmartPtr() [96/327]
castor3d::CU_DeclareSmartPtr (castor3d , IridescenceMapComponent , C3D_API)
CU_DeclareSmartPtr() [97/327]
castor3d::CU_DeclareSmartPtr (castor3d , IridescenceThicknessMapComponent , C3D_API)
CU_DeclareSmartPtr() [98/327]
castor3d::CU_DeclareSmartPtr (castor3d , IsRenderPassEnabled , C3D_API)
CU_DeclareSmartPtr() [99/327]
castor3d::CU_DeclareSmartPtr (castor3d , LayeredLightPropagationVolumes , C3D_API)
CU_DeclareSmartPtr() [100/327]
castor3d::CU_DeclareSmartPtr (castor3d , LayeredLightPropagationVolumesG , C3D_API)
CU_DeclareSmartPtr() [101/327]
castor3d::CU_DeclareSmartPtr (castor3d , LayeredLpvGridConfigUbo , C3D_API)
CU_DeclareSmartPtr() [102/327]
castor3d::CU_DeclareSmartPtr (castor3d , Layout , C3D_API)
CU_DeclareSmartPtr() [103/327]
castor3d::CU_DeclareSmartPtr (castor3d , LayoutControl , C3D_API)
CU_DeclareSmartPtr() [104/327]
castor3d::CU_DeclareSmartPtr (castor3d , Light , C3D_API)
CU_DeclareSmartPtr() [105/327]
castor3d::CU_DeclareSmartPtr (castor3d , LightBuffer , C3D_API)
CU_DeclareSmartPtr() [106/327]
castor3d::CU_DeclareSmartPtr (castor3d , LightCache , C3D_API)
CU_DeclareSmartPtr() [107/327]
castor3d::CU_DeclareSmartPtr (castor3d , LightCategory , C3D_API)
CU_DeclareSmartPtr() [108/327]
castor3d::CU_DeclareSmartPtr (castor3d , LightFactory , C3D_API)
CU_DeclareSmartPtr() [109/327]
castor3d::CU_DeclareSmartPtr (castor3d , LightImporter , C3D_API)
CU_DeclareSmartPtr() [110/327]
castor3d::CU_DeclareSmartPtr (castor3d , LightingModelComponent , C3D_API)
CU_DeclareSmartPtr() [111/327]
castor3d::CU_DeclareSmartPtr (castor3d , LightingModelFactory , C3D_API)
CU_DeclareSmartPtr() [112/327]
castor3d::CU_DeclareSmartPtr (castor3d , LightingPass , C3D_API)
CU_DeclareSmartPtr() [113/327]
castor3d::CU_DeclareSmartPtr (castor3d , LightInjectionPass , C3D_API)
CU_DeclareSmartPtr() [114/327]
castor3d::CU_DeclareSmartPtr (castor3d , LightPropagationPass , C3D_API)
CU_DeclareSmartPtr() [115/327]
castor3d::CU_DeclareSmartPtr (castor3d , LightPropagationVolumes , C3D_API)
CU_DeclareSmartPtr() [116/327]
castor3d::CU_DeclareSmartPtr (castor3d , LightPropagationVolumesG , C3D_API)
CU_DeclareSmartPtr() [117/327]
castor3d::CU_DeclareSmartPtr (castor3d , LightVolumePassResult , C3D_API)
CU_DeclareSmartPtr() [118/327]
castor3d::CU_DeclareSmartPtr (castor3d , LineariseDepthPass , C3D_API)
CU_DeclareSmartPtr() [119/327]
castor3d::CU_DeclareSmartPtr (castor3d , LinesMapping , C3D_API)
CU_DeclareSmartPtr() [120/327]
castor3d::CU_DeclareSmartPtr (castor3d , ListBoxCtrl , C3D_API)
CU_DeclareSmartPtr() [121/327]
castor3d::CU_DeclareSmartPtr (castor3d , ListBoxStyle , C3D_API)
CU_DeclareSmartPtr() [122/327]
castor3d::CU_DeclareSmartPtr (castor3d , LoadingScreen , C3D_API)
CU_DeclareSmartPtr() [123/327]
castor3d::CU_DeclareSmartPtr (castor3d , LpvGridConfigUbo , C3D_API)
CU_DeclareSmartPtr() [124/327]
castor3d::CU_DeclareSmartPtr (castor3d , LpvLightConfigUbo , C3D_API)
CU_DeclareSmartPtr() [125/327]
castor3d::CU_DeclareSmartPtr (castor3d , Material , C3D_API)
CU_DeclareSmartPtr() [126/327]
castor3d::CU_DeclareSmartPtr (castor3d , MaterialCache , C3D_API)
CU_DeclareSmartPtr() [127/327]
castor3d::CU_DeclareSmartPtr (castor3d , MaterialCacheView , C3D_API)
CU_DeclareSmartPtr() [128/327]
castor3d::CU_DeclareSmartPtr (castor3d , MaterialImporter , C3D_API)
CU_DeclareSmartPtr() [129/327]
castor3d::CU_DeclareSmartPtr (castor3d , MaterialImporterFactory , C3D_API)
CU_DeclareSmartPtr() [130/327]
castor3d::CU_DeclareSmartPtr (castor3d , Mesh , C3D_API)
CU_DeclareSmartPtr() [131/327]
castor3d::CU_DeclareSmartPtr (castor3d , MeshAnimation , C3D_API)
CU_DeclareSmartPtr() [132/327]
castor3d::CU_DeclareSmartPtr (castor3d , MeshAnimationInstance , C3D_API)
CU_DeclareSmartPtr() [133/327]
castor3d::CU_DeclareSmartPtr (castor3d , MeshAnimationSubmesh , C3D_API)
CU_DeclareSmartPtr() [134/327]
castor3d::CU_DeclareSmartPtr (castor3d , MeshCache , C3D_API)
CU_DeclareSmartPtr() [135/327]
castor3d::CU_DeclareSmartPtr (castor3d , MeshFactory , C3D_API)
CU_DeclareSmartPtr() [136/327]
castor3d::CU_DeclareSmartPtr (castor3d , MeshGenerator , C3D_API)
CU_DeclareSmartPtr() [137/327]
castor3d::CU_DeclareSmartPtr (castor3d , MeshImporter , C3D_API)
CU_DeclareSmartPtr() [138/327]
castor3d::CU_DeclareSmartPtr (castor3d , MeshImporterFactory , C3D_API)
CU_DeclareSmartPtr() [139/327]
castor3d::CU_DeclareSmartPtr (castor3d , MeshletBoundsTransformPass , C3D_API)
CU_DeclareSmartPtr() [140/327]
castor3d::CU_DeclareSmartPtr (castor3d , MeshletComponent , C3D_API)
CU_DeclareSmartPtr() [141/327]
castor3d::CU_DeclareSmartPtr (castor3d , MeshMorphTarget , C3D_API)
CU_DeclareSmartPtr() [142/327]
castor3d::CU_DeclareSmartPtr (castor3d , MetalnessComponent , C3D_API)
CU_DeclareSmartPtr() [143/327]
castor3d::CU_DeclareSmartPtr (castor3d , MetalnessMapComponent , C3D_API)
CU_DeclareSmartPtr() [144/327]
castor3d::CU_DeclareSmartPtr (castor3d , MorphComponent , C3D_API)
CU_DeclareSmartPtr() [145/327]
castor3d::CU_DeclareSmartPtr (castor3d , MovableObject , C3D_API)
CU_DeclareSmartPtr() [146/327]
castor3d::CU_DeclareSmartPtr (castor3d , NormalComponent , C3D_API)
CU_DeclareSmartPtr() [147/327]
castor3d::CU_DeclareSmartPtr (castor3d , NormalMapComponent , C3D_API)
CU_DeclareSmartPtr() [148/327]
castor3d::CU_DeclareSmartPtr (castor3d , ObjectBufferPool , C3D_API)
CU_DeclareSmartPtr() [149/327]
castor3d::CU_DeclareSmartPtr (castor3d , OcclusionMapComponent , C3D_API)
CU_DeclareSmartPtr() [150/327]
castor3d::CU_DeclareSmartPtr (castor3d , OpacityComponent , C3D_API)
CU_DeclareSmartPtr() [151/327]
castor3d::CU_DeclareSmartPtr (castor3d , OpacityMapComponent , C3D_API)
CU_DeclareSmartPtr() [152/327]
castor3d::CU_DeclareSmartPtr (castor3d , OpaquePassResult , C3D_API)
CU_DeclareSmartPtr() [153/327]
castor3d::CU_DeclareSmartPtr (castor3d , OpaqueRendering , C3D_API)
CU_DeclareSmartPtr() [154/327]
castor3d::CU_DeclareSmartPtr (castor3d , OpaqueResolvePass , C3D_API)
CU_DeclareSmartPtr() [155/327]
castor3d::CU_DeclareSmartPtr (castor3d , Overlay , C3D_API)
CU_DeclareSmartPtr() [156/327]
castor3d::CU_DeclareSmartPtr (castor3d , OverlayCache , C3D_API)
CU_DeclareSmartPtr() [157/327]
castor3d::CU_DeclareSmartPtr (castor3d , OverlayCategory , C3D_API)
CU_DeclareSmartPtr() [158/327]
castor3d::CU_DeclareSmartPtr (castor3d , OverlayFactory , C3D_API)
CU_DeclareSmartPtr() [159/327]
castor3d::CU_DeclareSmartPtr (castor3d , OverlayRenderer , C3D_API)
CU_DeclareSmartPtr() [160/327]
castor3d::CU_DeclareSmartPtr (castor3d , OverlayTextBufferPool , C3D_API)
CU_DeclareSmartPtr() [161/327]
castor3d::CU_DeclareSmartPtr (castor3d , PanelCtrl , C3D_API)
CU_DeclareSmartPtr() [162/327]
castor3d::CU_DeclareSmartPtr (castor3d , PanelOverlay , C3D_API)
CU_DeclareSmartPtr() [163/327]
castor3d::CU_DeclareSmartPtr (castor3d , PanelStyle , C3D_API)
CU_DeclareSmartPtr() [164/327]
castor3d::CU_DeclareSmartPtr (castor3d , ParticleElementDeclaration , C3D_API)
CU_DeclareSmartPtr() [165/327]
castor3d::CU_DeclareSmartPtr (castor3d , ParticleEmitter , C3D_API)
CU_DeclareSmartPtr() [166/327]
castor3d::CU_DeclareSmartPtr (castor3d , ParticleFactory , C3D_API)
CU_DeclareSmartPtr() [167/327]
castor3d::CU_DeclareSmartPtr (castor3d , ParticlePlugin , C3D_API)
CU_DeclareSmartPtr() [168/327]
castor3d::CU_DeclareSmartPtr (castor3d , ParticleSystem , C3D_API)
CU_DeclareSmartPtr() [169/327]
castor3d::CU_DeclareSmartPtr (castor3d , ParticleSystemCache , C3D_API)
CU_DeclareSmartPtr() [170/327]
castor3d::CU_DeclareSmartPtr (castor3d , ParticleSystemImpl , C3D_API)
CU_DeclareSmartPtr() [171/327]
castor3d::CU_DeclareSmartPtr (castor3d , ParticleUpdater , C3D_API)
CU_DeclareSmartPtr() [172/327]
castor3d::CU_DeclareSmartPtr (castor3d , Pass , C3D_API)
CU_DeclareSmartPtr() [173/327]
castor3d::CU_DeclareSmartPtr (castor3d , PassBuffer , C3D_API)
CU_DeclareSmartPtr() [174/327]
castor3d::CU_DeclareSmartPtr (castor3d , PassComponent , C3D_API)
CU_DeclareSmartPtr() [175/327]
castor3d::CU_DeclareSmartPtr (castor3d , PassComponentPlugin , C3D_API)
CU_DeclareSmartPtr() [176/327]
castor3d::CU_DeclareSmartPtr (castor3d , PassComponentRegister , C3D_API)
CU_DeclareSmartPtr() [177/327]
castor3d::CU_DeclareSmartPtr (castor3d , PassFactory , C3D_API)
CU_DeclareSmartPtr() [178/327]
castor3d::CU_DeclareSmartPtr (castor3d , PassHeaderComponent , C3D_API)
CU_DeclareSmartPtr() [179/327]
castor3d::CU_DeclareSmartPtr (castor3d , PassMapComponent , C3D_API)
CU_DeclareSmartPtr() [180/327]
castor3d::CU_DeclareSmartPtr (castor3d , PassMasksComponent , C3D_API)
CU_DeclareSmartPtr() [181/327]
castor3d::CU_DeclareSmartPtr (castor3d , PickableComponent , C3D_API)
CU_DeclareSmartPtr() [182/327]
castor3d::CU_DeclareSmartPtr (castor3d , Picking , C3D_API)
CU_DeclareSmartPtr() [183/327]
castor3d::CU_DeclareSmartPtr (castor3d , PickingPass , C3D_API)
CU_DeclareSmartPtr() [184/327]
castor3d::CU_DeclareSmartPtr (castor3d , Plane , C3D_API)
CU_DeclareSmartPtr() [185/327]
castor3d::CU_DeclareSmartPtr (castor3d , Plugin , C3D_API)
CU_DeclareSmartPtr() [186/327]
castor3d::CU_DeclareSmartPtr (castor3d , PluginCache , C3D_API)
CU_DeclareSmartPtr() [187/327]
castor3d::CU_DeclareSmartPtr (castor3d , PointLight , C3D_API)
CU_DeclareSmartPtr() [188/327]
castor3d::CU_DeclareSmartPtr (castor3d , PoolUniformBuffer , C3D_API)
CU_DeclareSmartPtr() [189/327]
castor3d::CU_DeclareSmartPtr (castor3d , PostEffect , C3D_API)
CU_DeclareSmartPtr() [190/327]
castor3d::CU_DeclareSmartPtr (castor3d , PostFxPlugin , C3D_API)
CU_DeclareSmartPtr() [191/327]
castor3d::CU_DeclareSmartPtr (castor3d , PrepassRendering , C3D_API)
CU_DeclareSmartPtr() [192/327]
castor3d::CU_DeclareSmartPtr (castor3d , PrepassResult , C3D_API)
CU_DeclareSmartPtr() [193/327]
castor3d::CU_DeclareSmartPtr (castor3d , ProgressBar , C3D_API)
CU_DeclareSmartPtr() [194/327]
castor3d::CU_DeclareSmartPtr (castor3d , ProgressCtrl , C3D_API)
CU_DeclareSmartPtr() [195/327]
castor3d::CU_DeclareSmartPtr (castor3d , ProgressStyle , C3D_API)
CU_DeclareSmartPtr() [196/327]
castor3d::CU_DeclareSmartPtr (castor3d , Projection , C3D_API)
CU_DeclareSmartPtr() [197/327]
castor3d::CU_DeclareSmartPtr (castor3d , QueueRenderNodes , C3D_API)
CU_DeclareSmartPtr() [198/327]
castor3d::CU_DeclareSmartPtr (castor3d , ReflectionComponent , C3D_API)
CU_DeclareSmartPtr() [199/327]
castor3d::CU_DeclareSmartPtr (castor3d , RefractionComponent , C3D_API)
CU_DeclareSmartPtr() [200/327]
castor3d::CU_DeclareSmartPtr (castor3d , RenderCube , C3D_API)
CU_DeclareSmartPtr() [201/327]
castor3d::CU_DeclareSmartPtr (castor3d , RenderDevice , C3D_API)
CU_DeclareSmartPtr() [202/327]
castor3d::CU_DeclareSmartPtr (castor3d , RenderGrid , C3D_API)
CU_DeclareSmartPtr() [203/327]
castor3d::CU_DeclareSmartPtr (castor3d , RenderLoop , C3D_API)
CU_DeclareSmartPtr() [204/327]
castor3d::CU_DeclareSmartPtr (castor3d , RenderNodesPass , C3D_API)
CU_DeclareSmartPtr() [205/327]
castor3d::CU_DeclareSmartPtr (castor3d , RenderPassRegisterInfo , C3D_API)
CU_DeclareSmartPtr() [206/327]
castor3d::CU_DeclareSmartPtr (castor3d , RenderPipeline , C3D_API)
CU_DeclareSmartPtr() [207/327]
castor3d::CU_DeclareSmartPtr (castor3d , RenderQuad , C3D_API)
CU_DeclareSmartPtr() [208/327]
castor3d::CU_DeclareSmartPtr (castor3d , RenderQueue , C3D_API)
CU_DeclareSmartPtr() [209/327]
castor3d::CU_DeclareSmartPtr (castor3d , RenderSystem , C3D_API)
CU_DeclareSmartPtr() [210/327]
castor3d::CU_DeclareSmartPtr (castor3d , RenderTarget , C3D_API)
CU_DeclareSmartPtr() [211/327]
castor3d::CU_DeclareSmartPtr (castor3d , RenderTargetCache , C3D_API)
CU_DeclareSmartPtr() [212/327]
castor3d::CU_DeclareSmartPtr (castor3d , RenderTechnique , C3D_API)
CU_DeclareSmartPtr() [213/327]
castor3d::CU_DeclareSmartPtr (castor3d , RenderTechniquePass , C3D_API)
CU_DeclareSmartPtr() [214/327]
castor3d::CU_DeclareSmartPtr (castor3d , RenderWindow , C3D_API)
CU_DeclareSmartPtr() [215/327]
castor3d::CU_DeclareSmartPtr (castor3d , RoughnessComponent , C3D_API)
CU_DeclareSmartPtr() [216/327]
castor3d::CU_DeclareSmartPtr (castor3d , RoughnessMapComponent , C3D_API)
CU_DeclareSmartPtr() [217/327]
castor3d::CU_DeclareSmartPtr (castor3d , Sampler , C3D_API)
CU_DeclareSmartPtr() [218/327]
castor3d::CU_DeclareSmartPtr (castor3d , SamplerCache , C3D_API)
CU_DeclareSmartPtr() [219/327]
castor3d::CU_DeclareSmartPtr (castor3d , Scene , C3D_API)
CU_DeclareSmartPtr() [220/327]
castor3d::CU_DeclareSmartPtr (castor3d , SceneBackground , C3D_API)
CU_DeclareSmartPtr() [221/327]
castor3d::CU_DeclareSmartPtr (castor3d , SceneCache , C3D_API)
CU_DeclareSmartPtr() [222/327]
castor3d::CU_DeclareSmartPtr (castor3d , SceneCuller , C3D_API)
CU_DeclareSmartPtr() [223/327]
castor3d::CU_DeclareSmartPtr (castor3d , SceneFileContext , C3D_API)
CU_DeclareSmartPtr() [224/327]
castor3d::CU_DeclareSmartPtr (castor3d , SceneFileParser , C3D_API)
CU_DeclareSmartPtr() [225/327]
castor3d::CU_DeclareSmartPtr (castor3d , SceneImporter , C3D_API)
CU_DeclareSmartPtr() [226/327]
castor3d::CU_DeclareSmartPtr (castor3d , SceneNode , C3D_API)
CU_DeclareSmartPtr() [227/327]
castor3d::CU_DeclareSmartPtr (castor3d , SceneNodeAnimation , C3D_API)
CU_DeclareSmartPtr() [228/327]
castor3d::CU_DeclareSmartPtr (castor3d , SceneNodeAnimationInstance , C3D_API)
CU_DeclareSmartPtr() [229/327]
castor3d::CU_DeclareSmartPtr (castor3d , SceneNodeAnimationKeyFrame , C3D_API)
CU_DeclareSmartPtr() [230/327]
castor3d::CU_DeclareSmartPtr (castor3d , SceneNodeCache , C3D_API)
CU_DeclareSmartPtr() [231/327]
castor3d::CU_DeclareSmartPtr (castor3d , SceneNodeImporter , C3D_API)
CU_DeclareSmartPtr() [232/327]
castor3d::CU_DeclareSmartPtr (castor3d , SceneRenderNodes , C3D_API)
CU_DeclareSmartPtr() [233/327]
castor3d::CU_DeclareSmartPtr (castor3d , SceneUbo , C3D_API)
CU_DeclareSmartPtr() [234/327]
castor3d::CU_DeclareSmartPtr (castor3d , ScrollableCtrl , C3D_API)
CU_DeclareSmartPtr() [235/327]
castor3d::CU_DeclareSmartPtr (castor3d , ScrollableStyle , C3D_API)
CU_DeclareSmartPtr() [236/327]
castor3d::CU_DeclareSmartPtr (castor3d , ScrollBarCtrl , C3D_API)
CU_DeclareSmartPtr() [237/327]
castor3d::CU_DeclareSmartPtr (castor3d , ScrollBarStyle , C3D_API)
CU_DeclareSmartPtr() [238/327]
castor3d::CU_DeclareSmartPtr (castor3d , ShaderBuffer , C3D_API)
CU_DeclareSmartPtr() [239/327]
castor3d::CU_DeclareSmartPtr (castor3d , ShaderProgram , C3D_API)
CU_DeclareSmartPtr() [240/327]
castor3d::CU_DeclareSmartPtr (castor3d , ShaderProgramCache , C3D_API)
CU_DeclareSmartPtr() [241/327]
castor3d::CU_DeclareSmartPtr (castor3d , ShadowMap , C3D_API)
CU_DeclareSmartPtr() [242/327]
castor3d::CU_DeclareSmartPtr (castor3d , ShadowMapPass , C3D_API)
CU_DeclareSmartPtr() [243/327]
castor3d::CU_DeclareSmartPtr (castor3d , SheenComponent , C3D_API)
CU_DeclareSmartPtr() [244/327]
castor3d::CU_DeclareSmartPtr (castor3d , SheenMapComponent , C3D_API)
CU_DeclareSmartPtr() [245/327]
castor3d::CU_DeclareSmartPtr (castor3d , SheenRoughnessMapComponent , C3D_API)
CU_DeclareSmartPtr() [246/327]
castor3d::CU_DeclareSmartPtr (castor3d , Skeleton , C3D_API)
CU_DeclareSmartPtr() [247/327]
castor3d::CU_DeclareSmartPtr (castor3d , SkeletonAnimation , C3D_API)
CU_DeclareSmartPtr() [248/327]
castor3d::CU_DeclareSmartPtr (castor3d , SkeletonAnimationBone , C3D_API)
CU_DeclareSmartPtr() [249/327]
castor3d::CU_DeclareSmartPtr (castor3d , SkeletonAnimationInstance , C3D_API)
CU_DeclareSmartPtr() [250/327]
castor3d::CU_DeclareSmartPtr (castor3d , SkeletonAnimationInstanceBone , C3D_API)
CU_DeclareSmartPtr() [251/327]
castor3d::CU_DeclareSmartPtr (castor3d , SkeletonAnimationInstanceNode , C3D_API)
CU_DeclareSmartPtr() [252/327]
castor3d::CU_DeclareSmartPtr (castor3d , SkeletonAnimationInstanceObject , C3D_API)
CU_DeclareSmartPtr() [253/327]
castor3d::CU_DeclareSmartPtr (castor3d , SkeletonAnimationKeyFrame , C3D_API)
CU_DeclareSmartPtr() [254/327]
castor3d::CU_DeclareSmartPtr (castor3d , SkeletonAnimationNode , C3D_API)
CU_DeclareSmartPtr() [255/327]
castor3d::CU_DeclareSmartPtr (castor3d , SkeletonAnimationObject , C3D_API)
CU_DeclareSmartPtr() [256/327]
castor3d::CU_DeclareSmartPtr (castor3d , SkeletonCache , C3D_API)
CU_DeclareSmartPtr() [257/327]
castor3d::CU_DeclareSmartPtr (castor3d , SkeletonImporter , C3D_API)
CU_DeclareSmartPtr() [258/327]
castor3d::CU_DeclareSmartPtr (castor3d , SkeletonImporterFactory , C3D_API)
CU_DeclareSmartPtr() [259/327]
castor3d::CU_DeclareSmartPtr (castor3d , SkeletonNode , C3D_API)
CU_DeclareSmartPtr() [260/327]
castor3d::CU_DeclareSmartPtr (castor3d , SkinComponent , C3D_API)
CU_DeclareSmartPtr() [261/327]
castor3d::CU_DeclareSmartPtr (castor3d , SkyboxBackground , C3D_API)
CU_DeclareSmartPtr() [262/327]
castor3d::CU_DeclareSmartPtr (castor3d , SliderCtrl , C3D_API)
CU_DeclareSmartPtr() [263/327]
castor3d::CU_DeclareSmartPtr (castor3d , SliderStyle , C3D_API)
CU_DeclareSmartPtr() [264/327]
castor3d::CU_DeclareSmartPtr (castor3d , Spacer , C3D_API)
CU_DeclareSmartPtr() [265/327]
castor3d::CU_DeclareSmartPtr (castor3d , SpecularComponent , C3D_API)
CU_DeclareSmartPtr() [266/327]
castor3d::CU_DeclareSmartPtr (castor3d , SpecularFactorMapComponent , C3D_API)
CU_DeclareSmartPtr() [267/327]
castor3d::CU_DeclareSmartPtr (castor3d , SpecularMapComponent , C3D_API)
CU_DeclareSmartPtr() [268/327]
castor3d::CU_DeclareSmartPtr (castor3d , Sphere , C3D_API)
CU_DeclareSmartPtr() [269/327]
castor3d::CU_DeclareSmartPtr (castor3d , SphereSection , C3D_API)
CU_DeclareSmartPtr() [270/327]
castor3d::CU_DeclareSmartPtr (castor3d , SpotLight , C3D_API)
CU_DeclareSmartPtr() [271/327]
castor3d::CU_DeclareSmartPtr (castor3d , SsaoBlurPass , C3D_API)
CU_DeclareSmartPtr() [272/327]
castor3d::CU_DeclareSmartPtr (castor3d , SsaoPass , C3D_API)
CU_DeclareSmartPtr() [273/327]
castor3d::CU_DeclareSmartPtr (castor3d , SsaoRawAOPass , C3D_API)
CU_DeclareSmartPtr() [274/327]
castor3d::CU_DeclareSmartPtr (castor3d , SssProfileBuffer , C3D_API)
CU_DeclareSmartPtr() [275/327]
castor3d::CU_DeclareSmartPtr (castor3d , StagingData , C3D_API)
CU_DeclareSmartPtr() [276/327]
castor3d::CU_DeclareSmartPtr (castor3d , StaticCtrl , C3D_API)
CU_DeclareSmartPtr() [277/327]
castor3d::CU_DeclareSmartPtr (castor3d , StaticStyle , C3D_API)
CU_DeclareSmartPtr() [278/327]
castor3d::CU_DeclareSmartPtr (castor3d , StencilPass , C3D_API)
CU_DeclareSmartPtr() [279/327]
castor3d::CU_DeclareSmartPtr (castor3d , StylesHolder , C3D_API)
CU_DeclareSmartPtr() [280/327]
castor3d::CU_DeclareSmartPtr (castor3d , Submesh , C3D_API)
CU_DeclareSmartPtr() [281/327]
castor3d::CU_DeclareSmartPtr (castor3d , SubmeshComponent , C3D_API)
CU_DeclareSmartPtr() [282/327]
castor3d::CU_DeclareSmartPtr (castor3d , SubmeshRenderNode , C3D_API)
CU_DeclareSmartPtr() [283/327]
castor3d::CU_DeclareSmartPtr (castor3d , SubsurfaceScattering , C3D_API)
CU_DeclareSmartPtr() [284/327]
castor3d::CU_DeclareSmartPtr (castor3d , SubsurfaceScatteringComponent , C3D_API)
CU_DeclareSmartPtr() [285/327]
castor3d::CU_DeclareSmartPtr (castor3d , SubsurfaceScatteringPass , C3D_API)
CU_DeclareSmartPtr() [286/327]
castor3d::CU_DeclareSmartPtr (castor3d , TextOverlay , C3D_API)
CU_DeclareSmartPtr() [287/327]
castor3d::CU_DeclareSmartPtr (castor3d , Texture3DTo2D , C3D_API)
CU_DeclareSmartPtr() [288/327]
castor3d::CU_DeclareSmartPtr (castor3d , TextureAnimation , C3D_API)
CU_DeclareSmartPtr() [289/327]
castor3d::CU_DeclareSmartPtr (castor3d , TextureAnimationBuffer , C3D_API)
CU_DeclareSmartPtr() [290/327]
castor3d::CU_DeclareSmartPtr (castor3d , TextureAnimationInstance , C3D_API)
CU_DeclareSmartPtr() [291/327]
castor3d::CU_DeclareSmartPtr (castor3d , TextureAnimationKeyFrame , C3D_API)
CU_DeclareSmartPtr() [292/327]
castor3d::CU_DeclareSmartPtr (castor3d , TextureConfigurationBuffer , C3D_API)
CU_DeclareSmartPtr() [293/327]
castor3d::CU_DeclareSmartPtr (castor3d , TextureCountComponent , C3D_API)
CU_DeclareSmartPtr() [294/327]
castor3d::CU_DeclareSmartPtr (castor3d , TextureLayout , C3D_API)
CU_DeclareSmartPtr() [295/327]
castor3d::CU_DeclareSmartPtr (castor3d , TexturesComponent , C3D_API)
CU_DeclareSmartPtr() [296/327]
castor3d::CU_DeclareSmartPtr (castor3d , TextureSource , C3D_API)
CU_DeclareSmartPtr() [297/327]
castor3d::CU_DeclareSmartPtr (castor3d , TextureUnit , C3D_API)
CU_DeclareSmartPtr() [298/327]
castor3d::CU_DeclareSmartPtr (castor3d , TextureUnitCache , C3D_API)
CU_DeclareSmartPtr() [299/327]
castor3d::CU_DeclareSmartPtr (castor3d , TextureUnitData , C3D_API)
CU_DeclareSmartPtr() [300/327]
castor3d::CU_DeclareSmartPtr (castor3d , TextureView , C3D_API)
CU_DeclareSmartPtr() [301/327]
castor3d::CU_DeclareSmartPtr (castor3d , Theme , C3D_API)
CU_DeclareSmartPtr() [302/327]
castor3d::CU_DeclareSmartPtr (castor3d , ThicknessComponent , C3D_API)
CU_DeclareSmartPtr() [303/327]
castor3d::CU_DeclareSmartPtr (castor3d , ToneMapping , C3D_API)
CU_DeclareSmartPtr() [304/327]
castor3d::CU_DeclareSmartPtr (castor3d , ToneMappingPlugin , C3D_API)
CU_DeclareSmartPtr() [305/327]
castor3d::CU_DeclareSmartPtr (castor3d , Torus , C3D_API)
CU_DeclareSmartPtr() [306/327]
castor3d::CU_DeclareSmartPtr (castor3d , TransmissionComponent , C3D_API)
CU_DeclareSmartPtr() [307/327]
castor3d::CU_DeclareSmartPtr (castor3d , TransmissionMapComponent , C3D_API)
CU_DeclareSmartPtr() [308/327]
castor3d::CU_DeclareSmartPtr (castor3d , TransmittanceMapComponent , C3D_API)
CU_DeclareSmartPtr() [309/327]
castor3d::CU_DeclareSmartPtr (castor3d , TransparentPassResult , C3D_API)
CU_DeclareSmartPtr() [310/327]
castor3d::CU_DeclareSmartPtr (castor3d , TransparentRendering , C3D_API)
CU_DeclareSmartPtr() [311/327]
castor3d::CU_DeclareSmartPtr (castor3d , TriFaceMapping , C3D_API)
CU_DeclareSmartPtr() [312/327]
castor3d::CU_DeclareSmartPtr (castor3d , TwoSidedComponent , C3D_API)
CU_DeclareSmartPtr() [313/327]
castor3d::CU_DeclareSmartPtr (castor3d , UniformBufferBase , C3D_API)
CU_DeclareSmartPtr() [314/327]
castor3d::CU_DeclareSmartPtr (castor3d , UniformBufferPool , C3D_API)
CU_DeclareSmartPtr() [315/327]
castor3d::CU_DeclareSmartPtr (castor3d , UntileMappingComponent , C3D_API)
CU_DeclareSmartPtr() [316/327]
castor3d::CU_DeclareSmartPtr (castor3d , UserInputListener , C3D_API)
CU_DeclareSmartPtr() [317/327]
castor3d::CU_DeclareSmartPtr (castor3d , VertexBufferPool , C3D_API)
CU_DeclareSmartPtr() [318/327]
castor3d::CU_DeclareSmartPtr (castor3d , VertexTransforming , C3D_API)
CU_DeclareSmartPtr() [319/327]
castor3d::CU_DeclareSmartPtr (castor3d , VertexTransformPass , C3D_API)
CU_DeclareSmartPtr() [320/327]
castor3d::CU_DeclareSmartPtr (castor3d , Viewport , C3D_API)
CU_DeclareSmartPtr() [321/327]
castor3d::CU_DeclareSmartPtr (castor3d , VisibilityPass , C3D_API)
CU_DeclareSmartPtr() [322/327]
castor3d::CU_DeclareSmartPtr (castor3d , VisibilityReorderPass , C3D_API)
CU_DeclareSmartPtr() [323/327]
castor3d::CU_DeclareSmartPtr (castor3d , VoxelBufferToTexture , C3D_API)
CU_DeclareSmartPtr() [324/327]
castor3d::CU_DeclareSmartPtr (castor3d , VoxelizePass , C3D_API)
CU_DeclareSmartPtr() [325/327]
castor3d::CU_DeclareSmartPtr (castor3d , Voxelizer , C3D_API)
CU_DeclareSmartPtr() [326/327]
castor3d::CU_DeclareSmartPtr (castor3d , VoxelSecondaryBounce , C3D_API)
CU_DeclareSmartPtr() [327/327]
castor3d::CU_DeclareSmartPtr (castor3d , WeightedBlendRendering , C3D_API)
CU_DeclareTemplateSmartPtr() [1/4]
castor3d::CU_DeclareTemplateSmartPtr (castor3d , Animable)
CU_DeclareTemplateSmartPtr() [2/4]
castor3d::CU_DeclareTemplateSmartPtr (castor3d , Animation)
CU_DeclareTemplateSmartPtr() [3/4]
castor3d::CU_DeclareTemplateSmartPtr (castor3d , AnimationInstance)
CU_DeclareTemplateSmartPtr() [4/4]
castor3d::CU_DeclareTemplateSmartPtr (castor3d , UniformBuffer)
CU_DeclareVector() [1/28]
castor3d::CU_DeclareVector (CommandsSemaphore , CommandsSemaphore)
CU_DeclareVector() [2/28]
castor3d::CU_DeclareVector (CpuFrameEventUPtr , CpuFrameEventPtr)
CU_DeclareVector() [3/28]
castor3d::CU_DeclareVector (Face , Face)
Face array.
CU_DeclareVector() [4/28]
castor3d::CU_DeclareVector (float , Float)
CU_DeclareVector() [5/28]
castor3d::CU_DeclareVector (GeometryInjectionPass , GeometryInjectionPass)
CU_DeclareVector() [6/28]
castor3d::CU_DeclareVector (GpuFrameEventUPtr , GpuFrameEventPtr)
CU_DeclareVector() [7/28]
castor3d::CU_DeclareVector (IntermediateView , IntermediateView)
CU_DeclareVector() [8/28]
castor3d::CU_DeclareVector (LightInjectionPass , LightInjectionPass)
CU_DeclareVector() [9/28]
castor3d::CU_DeclareVector (LightRPtr , Lights)
Array of lights.
CU_DeclareVector() [10/28]
castor3d::CU_DeclareVector (LightRPtr , LightsRef)
Array to non owning light pointers.
CU_DeclareVector() [11/28]
castor3d::CU_DeclareVector (LightVolumePassResultUPtr , LightVolumePassResult)
CU_DeclareVector() [12/28]
castor3d::CU_DeclareVector (LpvGridConfigUbo , LpvGridConfigUbo)
CU_DeclareVector() [13/28]
castor3d::CU_DeclareVector (LpvLightConfigUbo , LpvLightConfigUbo)
CU_DeclareVector() [14/28]
castor3d::CU_DeclareVector (MaterialObs , MaterialPtr)
Material pointer array.
CU_DeclareVector() [15/28]
castor3d::CU_DeclareVector (MeshAnimationSubmesh , MeshAnimationSubmesh)
CU_DeclareVector() [16/28]
castor3d::CU_DeclareVector (OverlayRPtr , OverlayPtr)
CU_DeclareVector() [17/28]
castor3d::CU_DeclareVector (Particle , Particle)
CU_DeclareVector() [18/28]
castor3d::CU_DeclareVector (ParticleEmitterUPtr , ParticleEmitter)
CU_DeclareVector() [19/28]
castor3d::CU_DeclareVector (ParticleUpdaterUPtr , ParticleUpdater)
CU_DeclareVector() [20/28]
castor3d::CU_DeclareVector (Pass , Pass)
Pass array.
CU_DeclareVector() [21/28]
castor3d::CU_DeclareVector (PassUPtr , PassPtr)
Pass pointer array.
CU_DeclareVector() [22/28]
castor3d::CU_DeclareVector (SceneNodeRPtr , SceneNodePtr)
SceneNode pointer array.
CU_DeclareVector() [23/28]
castor3d::CU_DeclareVector (SkeletonAnimationInstanceObjectUPtr , SkeletonAnimationInstanceObjectPtr)
SkeletonAnimationInstanceObject pointer array.
CU_DeclareVector() [24/28]
castor3d::CU_DeclareVector (SkeletonNodeUPtr , SkeletonNodePtr)
Bone pointer array.
CU_DeclareVector() [25/28]
castor3d::CU_DeclareVector (SubmeshUPtr , SubmeshPtr)
Submesh pointer array.
CU_DeclareVector() [26/28]
castor3d::CU_DeclareVector (SubmeshVertex , SubmeshVertex)
SubmeshVertex array.
CU_DeclareVector() [27/28]
castor3d::CU_DeclareVector (TextureUnit , TextureUnit)
TextureUnit array.
CU_DeclareVector() [28/28]
castor3d::CU_DeclareVector (VertexBoneData , VertexBoneData)
Skinned vertex data array.
findAnimatedObject()
AnimatedObjectRPtr castor3d::findAnimatedObject (Scene const & scene, castor::String const & name)
findFirstEmpty() [1/2]
C3D_API TextureFlagConfigurations::iterator castor3d::findFirstEmpty (TextureConfiguration & config)
findFirstEmpty() [2/2]
C3D_API TextureFlagConfigurations::const_iterator castor3d::findFirstEmpty (TextureConfiguration const & config)
findFirstNonEmpty() [1/2]
C3D_API TextureFlagConfigurations::iterator castor3d::findFirstNonEmpty (TextureConfiguration & config)
findFirstNonEmpty() [2/2]
C3D_API TextureFlagConfigurations::const_iterator castor3d::findFirstNonEmpty (TextureConfiguration const & config)
gatherBaseDataBuffer()
C3D_API void castor3d::gatherBaseDataBuffer (SubmeshFlag submeshData, PipelineFlags const & flags, ashes::PipelineVertexInputStateCreateInfoCRefArray & layouts, uint32_t & currentBinding, uint32_t & currentLocation, std::unordered_map< size_t, ashes::PipelineVertexInputStateCreateInfo > & cache)
Referenced by castor3d::BaseDataComponentT< SubmeshFlagT >::gather().
getBorderColor() [1/6]
C3D_API VkBorderColor castor3d::getBorderColor (DsTexture texture)
getBorderColor() [2/6]
VkBorderColor castor3d::getBorderColor (LpTexture texture)
getBorderColor() [3/6]
C3D_API VkBorderColor castor3d::getBorderColor (LpvTexture texture)
Referenced by castor3d::GBufferBase::doCreateTextures().
getBorderColor() [4/6]
C3D_API VkBorderColor castor3d::getBorderColor (PpTexture texture)
getBorderColor() [5/6]
C3D_API VkBorderColor castor3d::getBorderColor (SmTexture texture)
getBorderColor() [6/6]
C3D_API VkBorderColor castor3d::getBorderColor (WbTexture texture)
getBuffer() [1/46]
static uint8_t * castor3d::getBuffer (bool & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [2/46]
static uint8_t const * castor3d::getBuffer (bool const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
Referenced by castor3d::ChunkParser< T >::parse(), and castor3d::ChunkWriter< T >::write().
getBuffer() [3/46]
template<typename T , uint32_t Count> static uint8_t * castor3d::getBuffer (castor::Coords< T, Count > & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [4/46]
template<typename T , uint32_t Count> static uint8_t const * castor3d::getBuffer (castor::Coords< T, Count > const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [5/46]
template<typename T , uint32_t Columns, uint32_t Rows> static uint8_t * castor3d::getBuffer (castor::Matrix< T, Columns, Rows > & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [6/46]
template<typename T , uint32_t Columns, uint32_t Rows> static uint8_t const * castor3d::getBuffer (castor::Matrix< T, Columns, Rows > const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [7/46]
template<typename T , uint32_t Count> static uint8_t * castor3d::getBuffer (castor::Point< T, Count > & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [8/46]
template<typename T , uint32_t Count> static uint8_t const * castor3d::getBuffer (castor::Point< T, Count > const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [9/46]
static uint8_t * castor3d::getBuffer (castor::Position & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [10/46]
static uint8_t const * castor3d::getBuffer (castor::Position const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [11/46]
template<typename T > static uint8_t * castor3d::getBuffer (castor::QuaternionT< T > & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [12/46]
template<typename T > static uint8_t const * castor3d::getBuffer (castor::QuaternionT< T > const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [13/46]
static uint8_t * castor3d::getBuffer (castor::RgbaColour & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [14/46]
static uint8_t const * castor3d::getBuffer (castor::RgbaColour const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [15/46]
static uint8_t * castor3d::getBuffer (castor::RgbColour & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [16/46]
static uint8_t const * castor3d::getBuffer (castor::RgbColour const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [17/46]
static uint8_t * castor3d::getBuffer (castor::Size & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [18/46]
static uint8_t const * castor3d::getBuffer (castor::Size const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [19/46]
template<typename T , uint32_t Count> static uint8_t * castor3d::getBuffer (castor::SquareMatrix< T, Count > & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [20/46]
template<typename T , uint32_t Count> static uint8_t const * castor3d::getBuffer (castor::SquareMatrix< T, Count > const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer.
getBuffer() [21/46]
static uint8_t * castor3d::getBuffer (double & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [22/46]
static uint8_t const * castor3d::getBuffer (double const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [23/46]
static uint8_t * castor3d::getBuffer (float & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [24/46]
static uint8_t const * castor3d::getBuffer (float const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [25/46]
static uint8_t * castor3d::getBuffer (int16_t & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [26/46]
static uint8_t const * castor3d::getBuffer (int16_t const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [27/46]
static uint8_t * castor3d::getBuffer (int32_t & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [28/46]
static uint8_t const * castor3d::getBuffer (int32_t const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [29/46]
static uint8_t * castor3d::getBuffer (int64_t & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [30/46]
static uint8_t const * castor3d::getBuffer (int64_t const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [31/46]
static uint8_t * castor3d::getBuffer (int8_t & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [32/46]
static uint8_t const * castor3d::getBuffer (int8_t const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [33/46]
static uint8_t * castor3d::getBuffer (long double & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [34/46]
static uint8_t const * castor3d::getBuffer (long double const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [35/46]
template<typename T , size_t Count> static uint8_t * castor3d::getBuffer (std::array< T, Count > & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [36/46]
template<typename T , size_t Count> static uint8_t const * castor3d::getBuffer (std::array< T, Count > const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [37/46]
template<typename T > static uint8_t * castor3d::getBuffer (std::vector< T > & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [38/46]
template<typename T > static uint8_t const * castor3d::getBuffer (std::vector< T > const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [39/46]
static uint8_t * castor3d::getBuffer (uint16_t & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [40/46]
static uint8_t const * castor3d::getBuffer (uint16_t const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [41/46]
static uint8_t * castor3d::getBuffer (uint32_t & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [42/46]
static uint8_t const * castor3d::getBuffer (uint32_t const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [43/46]
static uint8_t * castor3d::getBuffer (uint64_t & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [44/46]
static uint8_t const * castor3d::getBuffer (uint64_t const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [45/46]
static uint8_t * castor3d::getBuffer (uint8_t & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getBuffer() [46/46]
static uint8_t const * castor3d::getBuffer (uint8_t const & value) inline static
Retrieves the beginning of the buffer for given value.
Parameters
[in] value The value.
Returns
The buffer (&value for basic types).
getClearValue() [1/6]
C3D_API VkClearValue castor3d::getClearValue (DsTexture texture)
getClearValue() [2/6]
VkClearValue castor3d::getClearValue (LpTexture texture)
getClearValue() [3/6]
C3D_API VkClearValue castor3d::getClearValue (LpvTexture texture)
getClearValue() [4/6]
C3D_API VkClearValue castor3d::getClearValue (PpTexture texture)
getClearValue() [5/6]
C3D_API VkClearValue castor3d::getClearValue (SmTexture texture)
getClearValue() [6/6]
C3D_API VkClearValue castor3d::getClearValue (WbTexture texture)
getCmshMajor()
constexpr uint32_t castor3d::getCmshMajor (uint32_t version) inline constexpr
Referenced by castor3d::BinaryParserBase< TParsed >::doParseHeader().
getCmshMinor()
constexpr uint32_t castor3d::getCmshMinor (uint32_t version) inline constexpr
Referenced by castor3d::BinaryParserBase< TParsed >::doParseHeader().
getCmshRevision()
constexpr uint32_t castor3d::getCmshRevision (uint32_t version) inline constexpr
Referenced by castor3d::BinaryParserBase< TParsed >::doParseHeader().
getCompareOp() [1/6]
VkCompareOp castor3d::getCompareOp (DsTexture texture) inline
getCompareOp() [2/6]
VkCompareOp castor3d::getCompareOp (LpTexture texture) inline
getCompareOp() [3/6]
VkCompareOp castor3d::getCompareOp (LpvTexture texture) inline
Referenced by castor3d::GBufferBase::doCreateTextures().
getCompareOp() [4/6]
VkCompareOp castor3d::getCompareOp (PpTexture texture) inline
getCompareOp() [5/6]
C3D_API VkCompareOp castor3d::getCompareOp (SmTexture texture)
getCompareOp() [6/6]
VkCompareOp castor3d::getCompareOp (WbTexture texture) inline
getComponentsMask()
C3D_API uint32_t castor3d::getComponentsMask (TextureConfiguration const & config, PassComponentTextureFlag textureFlag)
getData()
static constexpr SubmeshData castor3d::getData (SubmeshFlag value) static constexpr
Referenced by getIndex().
getDataSize() [1/12]
template<typename T , uint32_t Count> static size_t castor3d::getDataSize (castor::Coords< T, Count > const & value) inline static
Retrieves the value binary size.
Parameters
[in] value The value.
Returns
The size (sizeof(value) for basic types).
getDataSize() [2/12]
template<typename T , uint32_t Columns, uint32_t Rows> static size_t castor3d::getDataSize (castor::Matrix< T, Columns, Rows > const & value) inline static
Retrieves the value binary size.
Parameters
[in] value The value.
Returns
The size (sizeof(value) for basic types).
getDataSize() [3/12]
template<typename T , uint32_t Count> static size_t castor3d::getDataSize (castor::Point< T, Count > const & value) inline static
Retrieves the value binary size.
Parameters
[in] value The value.
Returns
The size (sizeof(value) for basic types).
getDataSize() [4/12]
static size_t castor3d::getDataSize (castor::Position const & value) inline static
Retrieves the value binary size.
Parameters
[in] value The value.
Returns
The size (sizeof(value) for basic types).
getDataSize() [5/12]
template<typename T > static size_t castor3d::getDataSize (castor::QuaternionT< T > const & value) inline static
Retrieves the value binary size.
Parameters
[in] value The value.
Returns
The size (sizeof(value) for basic types).
getDataSize() [6/12]
static size_t castor3d::getDataSize (castor::RgbaColour const & value) inline static
Retrieves the value binary size.
Parameters
[in] value The value.
Returns
The size (sizeof(value) for basic types).
getDataSize() [7/12]
static size_t castor3d::getDataSize (castor::RgbColour const & value) inline static
Retrieves the value binary size.
Parameters
[in] value The value.
Returns
The size (sizeof(value) for basic types).
getDataSize() [8/12]
static size_t castor3d::getDataSize (castor::Size const & value) inline static
Retrieves the value binary size.
Parameters
[in] value The value.
Returns
The size (sizeof(value) for basic types).
getDataSize() [9/12]
template<typename T , uint32_t Count> static size_t castor3d::getDataSize (castor::SquareMatrix< T, Count > const & value) inline static
Retrieves the value binary size.
Parameters
[in] value The value.
Returns
The size (sizeof(value) for basic types).
getDataSize() [10/12]
template<typename T , size_t Count> static size_t castor3d::getDataSize (std::array< T, Count > const & value) inline static
Retrieves the value binary size.
Parameters
[in] value The value.
Returns
The size (sizeof(value) for basic types).
getDataSize() [11/12]
template<typename T > static size_t castor3d::getDataSize (std::vector< T > const & value) inline static
Retrieves the value binary size.
Parameters
[in] value The value.
Returns
The size (sizeof(value) for basic types).
getDataSize() [12/12]
template<typename T > static size_t castor3d::getDataSize (T const & value) inline static
Retrieves the value binary size.
Parameters
[in] value The value.
Returns
The size (sizeof(value) for basic types).
Referenced by castor3d::ChunkParser< T >::parse(), and castor3d::ChunkWriter< T >::write().
getEnabledFlag()
C3D_API PassComponentTextureFlag castor3d::getEnabledFlag (TextureConfiguration const & config)
getEngine()
C3D_API Engine & castor3d::getEngine (Scene const & scene)
Referenced by castor3d::DoubleBufferedResourceT< ResourceT, PointerT >::doRefresh().
getEnumMapT() [1/2]
template<typename EnumT > castor::UInt32StrMap castor3d::getEnumMapT ()
References getEnumMapT().
Referenced by getEnumMapT().
getEnumMapT() [2/2]
template<typename EnumT > castor::UInt32StrMap castor3d::getEnumMapT (EnumT min, EnumT max)
References getName().
getFeatureFlags()
C3D_API VkFormatFeatureFlags castor3d::getFeatureFlags (VkImageUsageFlags flags)
getFlagConfiguration()
C3D_API TextureFlagConfiguration & castor3d::getFlagConfiguration (TextureConfiguration & config, PassComponentTextureFlag textureFlag)
getFlags()
C3D_API TextureFlagsSet castor3d::getFlags (TextureConfiguration const & config)
name Other functions.
getFogType()
C3D_API FogType castor3d::getFogType (SceneFlags const & flags)
Gives the fog type matching the given flags.
Parameters
[in] flags The scene flags.
Returns
The fog type.
getFormat() [1/6]
C3D_API VkFormat castor3d::getFormat (RenderDevice const & device, DsTexture texture)
getFormat() [2/6]
VkFormat castor3d::getFormat (RenderDevice const & device, LpTexture texture)
getFormat() [3/6]
C3D_API VkFormat castor3d::getFormat (RenderDevice const & device, LpvTexture texture)
Referenced by castor3d::GBufferBase::doCreateTextures().
getFormat() [4/6]
C3D_API VkFormat castor3d::getFormat (RenderDevice const & device, PpTexture texture)
getFormat() [5/6]
C3D_API VkFormat castor3d::getFormat (RenderDevice const & device, SmTexture texture)
getFormat() [6/6]
C3D_API VkFormat castor3d::getFormat (RenderDevice const & device, WbTexture texture)
getImageName()
C3D_API castor::String castor3d::getImageName (DsTexture texture)
getIndex()
static constexpr uint32_t castor3d::getIndex (SubmeshFlag value) static constexpr
References getData().
Referenced by castor3d::ObjectBufferOffset::getBufferChunk().
getLightRenderPassIndex()
uint32_t castor3d::getLightRenderPassIndex (bool blend, LightType lightType)
getLogger() [1/2]
castor::LoggerInstance & castor3d::getLogger (Engine & engine)
getLogger() [2/2]
C3D_API castor::LoggerInstance & castor3d::getLogger (Scene const & scene)
getMaterialColour()
castor::HdrRgbColour const & castor3d::getMaterialColour (Pass const & pass)
Retrieves the pass colour.
Parameters
[in] pass The pass.
Returns
The material colour.
Referenced by castor3d::ControlStyle::doCreateMaterial().
getMaxDistance() [1/2]
float castor3d::getMaxDistance (LightCategory const & light, castor::Point3f const & attenuation)
Retrieve the maximum litten distance for given light and attenuation.
Parameters
[in] light The light source.
[in] attenuation The attenuation values.
Returns
The value.
getMaxDistance() [2/2]
float castor3d::getMaxDistance (LightCategory const & light, castor::Point3f const & attenuation, float max)
Retrieve the maximum litten distance for given light and attenuation.
Parameters
[in] light The light source.
[in] attenuation The attenuation values.
[in] max The viewer max value.
Returns
The value.
getMipLevels() [1/11]
uint32_t castor3d::getMipLevels (RenderDevice const & device, DsTexture texture, castor::Size const & size) inline
getMipLevels() [2/11]
uint32_t castor3d::getMipLevels (RenderDevice const & device, LpTexture texture, castor::Size const & size) inline
getMipLevels() [3/11]
uint32_t castor3d::getMipLevels (RenderDevice const & device, LpTexture texture, VkExtent3D const & size) inline
References getMipLevels().
getMipLevels() [4/11]
uint32_t castor3d::getMipLevels (RenderDevice const & device, LpvTexture texture, castor::Size const & size) inline
getMipLevels() [5/11]
uint32_t castor3d::getMipLevels (RenderDevice const & device, LpvTexture texture, VkExtent3D const & size) inline
References getMipLevels().
getMipLevels() [6/11]
uint32_t castor3d::getMipLevels (RenderDevice const & device, PpTexture texture, castor::Size const & size) inline
getMipLevels() [7/11]
C3D_API uint32_t castor3d::getMipLevels (RenderDevice const & device, SmTexture texture, castor::Size const & size)
getMipLevels() [8/11]
uint32_t castor3d::getMipLevels (RenderDevice const & device, SmTexture texture, VkExtent3D const & size) inline
References getMipLevels().
getMipLevels() [9/11]
uint32_t castor3d::getMipLevels (RenderDevice const & device, WbTexture texture, castor::Size const & size) inline
getMipLevels() [10/11]
uint32_t castor3d::getMipLevels (RenderDevice const & device, WbTexture texture, VkExtent3D const & size) inline
References getMipLevels().
getMipLevels() [11/11]
C3D_API uint32_t castor3d::getMipLevels (VkExtent3D const & extent, VkFormat format)
Referenced by castor3d::GBufferBase::doCreateTextures(), and getMipLevels().
getName() [1/39]
C3D_API castor::String castor3d::getName (AnimationState value)
Referenced by getEnumMapT(), castor3d::MovableMergerT< CacheT >::operator()(), castor3d::SceneNodeMergerT< CacheT >::operator()(), and castor3d::TextureSource::toString().
getName() [2/39]
C3D_API castor::String castor3d::getName (AnimationType value)
getName() [3/39]
C3D_API castor::String castor3d::getName (BillboardSize value)
getName() [4/39]
C3D_API castor::String castor3d::getName (BillboardType value)
getName() [5/39]
C3D_API castor::String castor3d::getName (BlendMode value)
getName() [6/39]
C3D_API castor::String castor3d::getName (BorderPosition value)
getName() [7/39]
C3D_API castor::String castor3d::getName (CubeMapFace value)
getName() [8/39]
C3D_API castor::String castor3d::getName (ElementUsage value)
getName() [9/39]
C3D_API castor::String castor3d::getName (EventType value)
getName() [10/39]
C3D_API castor::String castor3d::getName (FogType value)
getName() [11/39]
C3D_API castor::String castor3d::getName (FrustumCorner value)
getName() [12/39]
C3D_API castor::String castor3d::getName (FrustumPlane value)
getName() [13/39]
C3D_API castor::String castor3d::getName (GlobalIlluminationType giType)
getName() [14/39]
C3D_API castor::String castor3d::getName (HAlign value)
getName() [15/39]
C3D_API castor::String castor3d::getName (HandlerEventType value)
getName() [16/39]
C3D_API castor::String castor3d::getName (InterpolatorType value)
getName() [17/39]
C3D_API castor::String castor3d::getName (KeyboardEventType value)
getName() [18/39]
C3D_API castor::String castor3d::getName (LightType value)
getName() [19/39]
castor::String castor3d::getName (MorphData value) inline
References eColours, eNormals, ePositions, eTangents, eTexcoords0, eTexcoords1, eTexcoords2, and eTexcoords3.
getName() [20/39]
C3D_API castor::String castor3d::getName (MouseButton value)
getName() [21/39]
C3D_API castor::String castor3d::getName (MouseEventType value)
getName() [22/39]
C3D_API castor::String castor3d::getName (MovableType value)
getName() [23/39]
C3D_API castor::String castor3d::getName (OverlayType value)
getName() [24/39]
C3D_API castor::String castor3d::getName (ParallaxOcclusionMode value)
getName() [25/39]
C3D_API castor::String castor3d::getName (ParticleFormat value)
getName() [26/39]
C3D_API castor::String castor3d::getName (PickNodeType value)
getName() [27/39]
C3D_API castor::String castor3d::getName (RenderFilter value)
getName() [28/39]
C3D_API castor::String castor3d::getName (ShadowType value)
getName() [29/39]
C3D_API castor::String castor3d::getName (SkeletonNodeType value)
getName() [30/39]
castor::String castor3d::getName (SubmeshData value) inline
References eColours, eIndex, eNormals, ePassMasks, ePositions, eSkin, eTangents, eTexcoords0, eTexcoords1, eTexcoords2, eTexcoords3, and eVelocity.
getName() [31/39]
C3D_API castor::String castor3d::getName (TargetType value)
getName() [32/39]
C3D_API castor::String castor3d::getName (TextLineSpacingMode value)
getName() [33/39]
C3D_API castor::String castor3d::getName (TextTexturingMode value)
getName() [34/39]
C3D_API castor::String castor3d::getName (TextureSpace value)
getName() [35/39]
C3D_API castor::String castor3d::getName (TextureSpaces value)
getName() [36/39]
C3D_API castor::String castor3d::getName (TextWrappingMode value)
getName() [37/39]
C3D_API castor::String castor3d::getName (UserInputEventType value)
getName() [38/39]
C3D_API castor::String castor3d::getName (VAlign value)
getName() [39/39]
C3D_API castor::String castor3d::getName (ViewportType value)
getParserContext()
C3D_API SceneFileContext & castor3d::getParserContext (castor::FileParserContext & context)
getPassComponent()
template<typename ComponentT > ComponentT & castor3d::getPassComponent (SceneFileContext & parsingContext)
References getPassComponentType(), castor3d::SceneFileContext::pass, and castor3d::SceneFileContext::passComponent.
getPassComponentType()
C3D_API castor::String const & castor3d::getPassComponentType (PassComponent const & component)
Referenced by getPassComponent().
getPipelineBaseHash() [1/3]
C3D_API PipelineBaseHash castor3d::getPipelineBaseHash (PassComponentRegister const & passComponents, PipelineFlags const & flags)
getPipelineBaseHash() [2/3]
C3D_API PipelineBaseHash castor3d::getPipelineBaseHash (RenderNodesPass const & renderPass, BillboardBase const & data, Pass const & pass, bool isFrontCulled)
getPipelineBaseHash() [3/3]
C3D_API PipelineBaseHash castor3d::getPipelineBaseHash (RenderNodesPass const & renderPass, Submesh const & data, Pass const & pass, bool isFrontCulled)
getPipelineHiHashDetails() [1/2]
C3D_API PipelineHiHashDetails castor3d::getPipelineHiHashDetails (RenderNodesPass const & renderPass, PipelineBaseHash const & hash, ShaderFlags shaderFlags)
getPipelineHiHashDetails() [2/2]
C3D_API PipelineHiHashDetails castor3d::getPipelineHiHashDetails (RenderTechniquePass const & renderPass, PipelineBaseHash const & hash, ShaderFlags shaderFlags)
getPipelineNodeIndex()
uint32_t castor3d::getPipelineNodeIndex (PipelineBaseHash hash, ashes::BufferBase const & buffer, std::vector< PipelineBuffer > const & cont)
getPipelineNodes()
PipelineNodes & castor3d::getPipelineNodes (PipelineBaseHash hash, ashes::BufferBase const & buffer, std::vector< PipelineBuffer > const & cont, PipelineNodes * nodes, VkDeviceSize maxNodesCount)
getPixelComponents() [1/3]
C3D_API castor::PixelComponents castor3d::getPixelComponents (castor::PixelFormat format)
getPixelComponents() [2/3]
C3D_API castor::PixelComponents castor3d::getPixelComponents (TextureConfiguration const & config)
getPixelComponents() [3/3]
C3D_API castor::PixelComponents castor3d::getPixelComponents (uint32_t mask)
getRenderNodeType()
RenderNodeType castor3d::getRenderNodeType (ProgramFlags const & flags)
getSafeBandedAspect()
C3D_API float castor3d::getSafeBandedAspect (float aspect, castor::Size const & size)
getSafeBandedExtent3D()
C3D_API VkExtent3D castor3d::getSafeBandedExtent3D (castor::Size const & size)
getSafeBandedFovY()
C3D_API castor::Angle castor3d::getSafeBandedFovY (castor::Angle const & fovY, castor::Size const & size)
getSafeBandedSize()
C3D_API castor::Size castor3d::getSafeBandedSize (castor::Size const & size)
getSafeBandSize()
C3D_API uint32_t castor3d::getSafeBandSize (castor::Size const & size)
getSafeBandsSize()
C3D_API uint32_t castor3d::getSafeBandsSize (castor::Size const & size)
getSamplerName()
castor::String castor3d::getSamplerName (VkCompareOp compareOp, VkFilter minFilter, VkFilter magFilter, VkSamplerMipmapMode mipFilter, VkSamplerAddressMode U, VkSamplerAddressMode V, VkSamplerAddressMode W)
getSceneParserContext()
C3D_API SceneFileContext & castor3d::getSceneParserContext (castor::FileParserContext & context)
getSize() [1/2]
VkDeviceSize castor3d::getSize (ParticleFormat format) inline
Parameters
[in] format The particle format.
Returns
The data size for this particle format.
References eFloat, eInt, eMat2f, eMat3f, eMat4f, eUInt, eVec2f, eVec2i, eVec2ui, eVec3f, eVec3i, eVec3ui, eVec4f, eVec4i, and eVec4ui.
getSize() [2/2]
constexpr uint32_t castor3d::getSize (SubmeshData value) inline constexpr
References eCount.
Referenced by castor3d::ParticleDeclaration::emplace_back(), and castor3d::ParticleDeclaration::push_back().
getTexName() [1/6]
C3D_API castor::String castor3d::getTexName (DsTexture texture)
getTexName() [2/6]
castor::String castor3d::getTexName (LpTexture texture)
getTexName() [3/6]
C3D_API castor::String castor3d::getTexName (LpvTexture texture)
Referenced by castor3d::GBufferBase::doCreateTextures().
getTexName() [4/6]
C3D_API castor::String castor3d::getTexName (PpTexture texture)
getTexName() [5/6]
C3D_API castor::String castor3d::getTexName (SmTexture texture)
getTexName() [6/6]
C3D_API castor::String castor3d::getTexName (WbTexture texture)
getTextureName() [1/6]
C3D_API castor::String castor3d::getTextureName (DsTexture texture)
getTextureName() [2/6]
C3D_API castor::String castor3d::getTextureName (LightType light, SmTexture texture)
getTextureName() [3/6]
castor::String castor3d::getTextureName (LpTexture texture)
getTextureName() [4/6]
C3D_API castor::String castor3d::getTextureName (LpvTexture texture, std::string const & infix)
getTextureName() [5/6]
C3D_API castor::String castor3d::getTextureName (PpTexture texture)
getTextureName() [6/6]
C3D_API castor::String castor3d::getTextureName (WbTexture texture)
getUsageFlags() [1/6]
C3D_API VkImageUsageFlags castor3d::getUsageFlags (DsTexture texture)
getUsageFlags() [2/6]
VkImageUsageFlags castor3d::getUsageFlags (LpTexture texture)
getUsageFlags() [3/6]
C3D_API VkImageUsageFlags castor3d::getUsageFlags (LpvTexture texture)
Referenced by castor3d::GBufferBase::doCreateTextures().
getUsageFlags() [4/6]
C3D_API VkImageUsageFlags castor3d::getUsageFlags (PpTexture texture)
getUsageFlags() [5/6]
C3D_API VkImageUsageFlags castor3d::getUsageFlags (SmTexture texture)
getUsageFlags() [6/6]
C3D_API VkImageUsageFlags castor3d::getUsageFlags (WbTexture texture)
hasAny() [1/4]
C3D_API bool castor3d::hasAny (PassComponentCombine const & lhs, PassComponentFlag rhs)
hasAny() [2/4]
C3D_API bool castor3d::hasAny (TextureCombine const & lhs, PassComponentTextureFlag rhs)
hasAny() [3/4]
C3D_API bool castor3d::hasAny (TextureFlagConfigurations const & lhs, PassComponentTextureFlag rhs)
hasAny() [4/4]
C3D_API bool castor3d::hasAny (TextureFlagsSet const & lhs, PassComponentTextureFlag rhs)
Referenced by castor3d::PipelineFlags::hasDiffuseGI(), castor3d::FractalMappingComponent::ComponentsShader::isMapSampling(), and castor3d::UntileMappingComponent::ComponentsShader::isMapSampling().
hash() [1/4]
C3D_API size_t castor3d::hash (BillboardBase const & billboard, Pass const & pass)
hash() [2/4]
size_t castor3d::hash (BillboardRenderNode const & culled)
hash() [3/4]
C3D_API size_t castor3d::hash (Geometry const & geometry, Submesh const & submesh, Pass const & pass)
hash() [4/4]
size_t castor3d::hash (SubmeshRenderNode const & culled)
hasIntersect()
C3D_API bool castor3d::hasIntersect (PassComponentTextureFlag lhs, PassComponentTextureFlag rhs)
incProgressBarRange()
C3D_API void castor3d::incProgressBarRange (ProgressBar * progress, int32_t value)
initialiseGlslang()
C3D_API void castor3d::initialiseGlslang ()
Initialises glslang globals.
isLayoutControl() [1/2]
C3D_API bool castor3d::isLayoutControl (Control const & control)
isLayoutControl() [2/2]
C3D_API bool castor3d::isLayoutControl (ControlType type)
isScrollableControl() [1/2]
C3D_API bool castor3d::isScrollableControl (Control const & control)
isScrollableControl() [2/2]
C3D_API bool castor3d::isScrollableControl (ControlType type)
isStylesHolder() [1/2]
C3D_API bool castor3d::isStylesHolder (ControlStyle const & style)
isStylesHolder() [2/2]
C3D_API bool castor3d::isStylesHolder (ControlType type)
isVisible() [1/4]
bool castor3d::isVisible (Camera const & camera, BillboardRenderNode const & node)
isVisible() [2/4]
bool castor3d::isVisible (Camera const & camera, SubmeshRenderNode const & node)
isVisible() [3/4]
bool castor3d::isVisible (Frustum const & frustum, BillboardRenderNode const & node)
isVisible() [4/4]
bool castor3d::isVisible (Frustum const & frustum, SubmeshRenderNode const & node)
makeBuffer()
template<typename T > ashes::BufferPtr< T > castor3d::makeBuffer (RenderDevice const & device, VkDeviceSize count, VkBufferUsageFlags usage, VkMemoryPropertyFlags flags, std::string const & name, ashes::QueueShare sharingMode = {}) inline
makeBufferBase()
ashes::BufferBasePtr castor3d::makeBufferBase (RenderDevice const & device, VkDeviceSize size, VkBufferUsageFlags usage, VkMemoryPropertyFlags flags, std::string const & name, ashes::QueueShare sharingMode = {}) inline
makeCache()
castor::UniquePtr< ShaderProgramCache > castor3d::makeCache (Engine & engine) inline
Creates a ashes::ShaderProgram cache.
Parameters
[in] engine The engine.
makeCacheView()
template<EventType EventT, typename CacheT > CacheViewPtrT< CacheT, EventT > castor3d::makeCacheView (castor::String const & name, CacheT & cache, typename CacheViewTraitsT< CacheT >::ElementInitialiserT initialiser = {}, typename CacheViewTraitsT< CacheT >::ElementCleanerT cleaner = {})
makeChunkID()
uint64_t constexpr castor3d::makeChunkID (char a, char b, char c, char d, char e, char f, char g, char h) constexpr
A define to ease the declaration of a chunk id.
makeClearValue() [1/3]
VkClearValue castor3d::makeClearValue (float depth, uint32_t stencil = 0u) inline
makeClearValue() [2/3]
VkClearValue castor3d::makeClearValue (float r, float g, float b, float a = 1.0f) inline
makeClearValue() [3/3]
VkClearValue castor3d::makeClearValue (uint32_t r, uint32_t g, uint32_t b, uint32_t a) inline
makeCmshVersion()
constexpr uint32_t castor3d::makeCmshVersion (uint32_t maj, uint32_t min, uint32_t rev) inline constexpr
makeCpuCleanupEvent()
template<typename T > CpuFrameEventUPtr castor3d::makeCpuCleanupEvent (T & object) inline
Helper function to create a cleanup event.
Parameters
[in] object The object to cleanup
References ePreRender, and makeCpuFunctorEvent().
Referenced by castor3d::CpuEventCleanerT< CacheT >::operator()().
makeCpuFrameEvent()
template<typename EventT , typename ... ParamsT> CpuFrameEventUPtr castor3d::makeCpuFrameEvent (ParamsT &&... params) inline
makeCpuFunctorEvent()
CpuFrameEventUPtr castor3d::makeCpuFunctorEvent (EventType type, CpuFunctorEvent::Functor functor) inline
Helper function to create a functor event.
Parameters
[in] type The event type
[in] functor The functor to execute
Referenced by makeCpuCleanupEvent(), and makeCpuInitialiseEvent().
makeCpuInitialiseEvent()
template<typename T > CpuFrameEventUPtr castor3d::makeCpuInitialiseEvent (T & object) inline
Helper function to create an initialise event.
Parameters
[in] object The object to initialise.
References ePreRender, and makeCpuFunctorEvent().
Referenced by castor3d::CpuEventInitialiserT< CacheT >::operator()().
makeDescriptorSetLayoutBinding()
VkDescriptorSetLayoutBinding castor3d::makeDescriptorSetLayoutBinding (uint32_t binding, VkDescriptorType descriptorType, VkShaderStageFlags stageFlags, uint32_t descriptorCount = 1u, VkSampler const * pImmutableSamplers = nullptr) inline
makeDescriptorWrite() [1/8]
template<typename DataT > ashes::WriteDescriptorSet castor3d::makeDescriptorWrite (ashes::Buffer< DataT > const & buffer, ashes::BufferView const & view, uint32_t dstBinding, uint32_t dstArrayElement = 0u)
Creates a descriptor write for buffer texel view.
Parameters
[in] buffer The buffer.
[in] view The texel view.
[in] dstBinding The binding inside the descriptor set.
[in] dstArrayElement The array element index.
References makeDescriptorWrite().
makeDescriptorWrite() [2/8]
template<typename DataT > ashes::WriteDescriptorSet castor3d::makeDescriptorWrite (ashes::Buffer< DataT > const & storageBuffer, uint32_t dstBinding, VkDeviceSize elemOffset, VkDeviceSize elemRange, uint32_t dstArrayElement = 0u)
Creates a descriptor write for storage buffer.
Parameters
[in] storageBuffer The storage buffer.
[in] dstBinding The binding inside the descriptor set.
[in] elemOffset The offset, expressed in element count.
[in] elemRange The range, expressed in element count.
[in] dstArrayElement The array element index.
References makeDescriptorWrite().
makeDescriptorWrite() [3/8]
C3D_API ashes::WriteDescriptorSet castor3d::makeDescriptorWrite (ashes::BufferBase const & buffer, ashes::BufferView const & view, uint32_t dstBinding, uint32_t dstArrayElement = 0u)
Creates a descriptor write for buffer texel view.
Parameters
[in] buffer The buffer.
[in] view The texel view.
[in] dstBinding The binding inside the descriptor set.
[in] dstArrayElement The array element index.
makeDescriptorWrite() [4/8]
C3D_API ashes::WriteDescriptorSet castor3d::makeDescriptorWrite (ashes::BufferBase const & storageBuffer, uint32_t dstBinding, VkDeviceSize byteOffset, VkDeviceSize byteRange, uint32_t dstArrayElement = 0u)
Creates a descriptor write for storage buffer.
Parameters
[in] storageBuffer The storage buffer.
[in] dstBinding The binding inside the descriptor set.
[in] byteOffset The offset, expressed in bytes.
[in] byteRange The range, expressed in bytes.
[in] dstArrayElement The array element index.
makeDescriptorWrite() [5/8]
C3D_API ashes::WriteDescriptorSet castor3d::makeDescriptorWrite (ashes::ImageView const & view, ashes::Sampler const & sampler, uint32_t dstBinding, uint32_t dstArrayElement = 0u)
Creates a descriptor write for combined image sampler.
Parameters
[in] view The image view.
[in] sampler The sampler.
[in] dstBinding The binding inside the descriptor set.
[in] dstArrayElement The array element index.
makeDescriptorWrite() [6/8]
C3D_API ashes::WriteDescriptorSet castor3d::makeDescriptorWrite (ashes::ImageView const & view, uint32_t dstBinding, uint32_t dstArrayElement = 0u)
Creates a descriptor write for storage image.
Parameters
[in] view The image view.
[in] dstBinding The binding inside the descriptor set.
[in] dstArrayElement The array element index.
makeDescriptorWrite() [7/8]
C3D_API ashes::WriteDescriptorSet castor3d::makeDescriptorWrite (ashes::UniformBuffer const & buffer, uint32_t dstBinding, VkDeviceSize elemOffset, VkDeviceSize elemRange, uint32_t dstArrayElement = 0u)
Creates a descriptor write for uniform buffer.
Parameters
[in] buffer The uniform buffer.
[in] dstBinding The binding inside the descriptor set.
[in] elemOffset The offset, expressed in element count.
[in] elemRange The range, expressed in element count.
[in] dstArrayElement The array element index.
makeDescriptorWrite() [8/8]
template<typename DataT > ashes::WriteDescriptorSet castor3d::makeDescriptorWrite (UniformBufferOffsetT< DataT > const & buffer, uint32_t dstBinding, uint32_t dstArrayElement = 0u)
Creates a descriptor write for uniform buffer range.
Parameters
[in] buffer The uniform buffer range.
[in] dstBinding The binding inside the descriptor set.
[in] dstArrayElement The array element index.
References castor3d::UniformBufferOffsetT< DataT >::getDescriptorWrite().
Referenced by makeDescriptorWrite().
makeExtent2D() [1/3]
VkExtent2D castor3d::makeExtent2D (castor::Coords2ui const & size) inline
makeExtent2D() [2/3]
VkExtent2D castor3d::makeExtent2D (castor::Point2ui const & size) inline
makeExtent2D() [3/3]
VkExtent2D castor3d::makeExtent2D (VkExtent3D const & size) inline
Referenced by makeScissor(), and makeViewport().
makeExtent3D() [1/3]
VkExtent3D castor3d::makeExtent3D (castor::Coords2ui const & size) inline
makeExtent3D() [2/3]
VkExtent3D castor3d::makeExtent3D (castor::Point2ui const & size) inline
makeExtent3D() [3/3]
VkExtent3D castor3d::makeExtent3D (VkExtent2D const & size) inline
makeFloatArray()
std::array< float, 4u > castor3d::makeFloatArray (castor::RgbaColour const & value)
makeGpuCleanupEvent()
template<typename T > GpuFrameEventUPtr castor3d::makeGpuCleanupEvent (T & object) inline
Helper function to create a cleanup event.
Parameters
[in] object The object to cleanup
References ePreRender, and makeGpuFunctorEvent().
Referenced by castor3d::GpuEventCleanerT< CacheT >::operator()().
makeGpuFrameEvent()
template<typename EventT , typename ... ParamsT> GpuFrameEventUPtr castor3d::makeGpuFrameEvent (ParamsT &&... params) inline
makeGpuFunctorEvent()
GpuFrameEventUPtr castor3d::makeGpuFunctorEvent (EventType type, GpuFunctorEvent::Functor functor) inline
Helper function to create a functor event.
Parameters
[in] type The event type
[in] functor The functor to execute
Referenced by makeGpuCleanupEvent(), and makeGpuInitialiseEvent().
makeGpuInitialiseEvent()
template<typename T > GpuFrameEventUPtr castor3d::makeGpuInitialiseEvent (T & object) inline
Helper function to create an initialise event.
Parameters
[in] object The object to initialise.
References ePreRender, and makeGpuFunctorEvent().
Referenced by castor3d::GpuEventInitialiserT< CacheT >::operator()().
makeImage() [1/3]
C3D_API ashes::Image castor3d::makeImage (ashes::Device const & device, Texture const & texture)
makeImage() [2/3]
C3D_API ashes::Image castor3d::makeImage (ashes::Device const & device, VkImage image, crg::ImageId data)
makeImage() [3/3]
ashes::ImagePtr castor3d::makeImage (RenderDevice const & device, ashes::ImageCreateInfo createInfo, VkMemoryPropertyFlags flags, std::string const & name) inline
makeImageView()
C3D_API ashes::ImageView castor3d::makeImageView (ashes::Device const & device, ashes::Image const & image, VkImageView view, crg::ImageViewId data)
makeImageViewDescriptorWrite() [1/2]
C3D_API ashes::WriteDescriptorSet castor3d::makeImageViewDescriptorWrite (VkImageView const & view, uint32_t dstBinding, uint32_t dstArrayElement = 0u)
Creates a descriptor write for storage image.
Parameters
[in] view The image view.
[in] dstBinding The binding inside the descriptor set.
[in] dstArrayElement The array element index.
makeImageViewDescriptorWrite() [2/2]
C3D_API ashes::WriteDescriptorSet castor3d::makeImageViewDescriptorWrite (VkImageView const & view, VkSampler const & sampler, uint32_t dstBinding, uint32_t dstArrayElement = 0u)
Creates a descriptor write for combined image sampler.
Parameters
[in] view The image view.
[in] sampler The sampler.
[in] dstBinding The binding inside the descriptor set.
[in] dstArrayElement The array element index.
makeInterpolator()
template<typename DataT > InterpolatorPtr< DataT > castor3d::makeInterpolator (InterpolatorType type)
References eNearest.
makeLayoutTransition() [1/3]
C3D_API VkImageMemoryBarrier castor3d::makeLayoutTransition (VkImage image, VkImageSubresourceRange const & range, VkImageLayout sourceLayout, VkImageLayout destinationLayout, uint32_t srcQueueFamily, uint32_t dstQueueFamily)
makeLayoutTransition() [2/3]
C3D_API VkImageMemoryBarrier castor3d::makeLayoutTransition (VkImage image, VkImageSubresourceRange const & range, VkImageLayout srcLayout, VkImageLayout dstLayout, VkAccessFlags srcAccessFlags, uint32_t srcQueueFamily, uint32_t dstQueueFamily)
makeLayoutTransition() [3/3]
C3D_API VkImageMemoryBarrier castor3d::makeLayoutTransition (VkImage image, VkImageSubresourceRange const & range, VkImageLayout srcLayout, VkImageLayout dstLayout, VkAccessFlags srcAccessFlags, VkAccessFlags dstAccessMask, uint32_t srcQueueFamily, uint32_t dstQueueFamily)
makeObjectCache()
template<typename ObjT , typename KeyT , typename TraitsT , typename ... ParametersT> ObjectCachePtrT< ObjT, KeyT, TraitsT > castor3d::makeObjectCache (ParametersT &&... parameters)
Creates an object cache.
Parameters
[in] parameters The cache ctor parameters.
makeOffset2D() [1/2]
VkOffset2D castor3d::makeOffset2D (castor::Coords2i const & pos) inline
Referenced by makeScissor(), and makeViewport().
makeOffset2D() [2/2]
VkOffset2D castor3d::makeOffset2D (castor::Point2i const & pos) inline
makeOffset3D() [1/2]
VkOffset3D castor3d::makeOffset3D (castor::Coords2i const & pos) inline
makeOffset3D() [2/2]
VkOffset3D castor3d::makeOffset3D (castor::Point2i const & pos) inline
makePassComponentFlag()
PassComponentFlag castor3d::makePassComponentFlag (PassComponentID componentId, PassFlags componentTextureFlag) inline
Referenced by castor3d::PassComponentPlugin::getComponentFlags(), castor3d::BlendComponent::Plugin::getComponentFlags(), castor3d::FractalMappingComponent::Plugin::getComponentFlags(), castor3d::PickableComponent::Plugin::getComponentFlags(), castor3d::UntileMappingComponent::Plugin::getComponentFlags(), castor3d::SubsurfaceScatteringComponent::Plugin::getComponentFlags(), castor3d::AlphaTestComponent::Plugin::getComponentFlags(), castor3d::HeightComponent::Plugin::getComponentFlags(), castor3d::HeightComponent::Plugin::getParallaxOcclusionMappingOneFlag(), castor3d::HeightComponent::Plugin::getParallaxOcclusionMappingRepeatFlag(), castor3d::PassComponent::getPassFlags(), castor3d::BlendComponent::getPassFlags(), castor3d::FractalMappingComponent::getPassFlags(), castor3d::NormalComponent::getPassFlags(), castor3d::PickableComponent::getPassFlags(), castor3d::UntileMappingComponent::getPassFlags(), castor3d::SubsurfaceScatteringComponent::getPassFlags(), castor3d::AlphaTestComponent::getPassFlags(), castor3d::HeightComponent::getPassFlags(), castor3d::FractalMappingComponent::ComponentsShader::isMapSampling(), and castor3d::UntileMappingComponent::ComponentsShader::isMapSampling().
makePoolUniformBuffer()
PoolUniformBufferUPtr castor3d::makePoolUniformBuffer (RenderSystem const & renderSystem, castor::ArrayView< uint8_t > data, VkBufferUsageFlags usage, VkMemoryPropertyFlags flags, std::string name, ashes::QueueShare sharingMode = {}) inline
makeSampledImageView()
C3D_API ashes::ImageView castor3d::makeSampledImageView (ashes::Device const & device, ashes::Image const & image, Texture const & texture)
makeScissor() [1/6]
VkRect2D castor3d::makeScissor (castor::Coords2i const & pos, castor::Coords2ui const & size) inline
References makeExtent2D(), and makeOffset2D().
makeScissor() [2/6]
VkRect2D castor3d::makeScissor (castor::Coords2i const & pos, castor::Point2ui const & size) inline
References makeExtent2D(), and makeOffset2D().
makeScissor() [3/6]
VkRect2D castor3d::makeScissor (castor::Coords2ui const & size) inline
References makeExtent2D().
makeScissor() [4/6]
VkRect2D castor3d::makeScissor (castor::Point2i const & pos, castor::Coords2ui const & size) inline
References makeExtent2D(), and makeOffset2D().
makeScissor() [5/6]
VkRect2D castor3d::makeScissor (castor::Point2i const & pos, castor::Point2ui const & size) inline
References makeExtent2D(), and makeOffset2D().
makeScissor() [6/6]
VkRect2D castor3d::makeScissor (castor::Point2ui const & size) inline
References makeExtent2D().
makeShaderState() [1/2]
ashes::PipelineShaderStageCreateInfo castor3d::makeShaderState (ashes::Device const & device, VkShaderStageFlagBits stage, SpirVShader const & code, std::string const & name, std::string mainFuncName = "main", ashes::Optional< ashes::SpecializationInfo > specialization = ashes::nullopt) inline
References castor3d::SpirVShader::spirv.
makeShaderState() [2/2]
ashes::PipelineShaderStageCreateInfo castor3d::makeShaderState (RenderDevice const & device, ShaderModule & shaderModule, std::string mainFuncName = "main", ashes::Optional< ashes::SpecializationInfo > specialization = ashes::nullopt) inline
makeSize() [1/2]
castor::Size castor3d::makeSize (VkExtent2D const & size) inline
makeSize() [2/2]
castor::Size castor3d::makeSize (VkExtent3D const & size) inline
makeTargetImageView()
C3D_API ashes::ImageView castor3d::makeTargetImageView (ashes::Device const & device, ashes::Image const & image, Texture const & texture)
makeTextureFlag()
PassComponentTextureFlag castor3d::makeTextureFlag (PassComponentID componentId, TextureFlags componentTextureFlag) inline
Referenced by castor3d::AttenuationMapComponent::ComponentsShader::getTextureFlags(), castor3d::ClearcoatMapComponent::ComponentsShader::getTextureFlags(), castor3d::ClearcoatNormalMapComponent::ComponentsShader::getTextureFlags(), castor3d::ClearcoatRoughnessMapComponent::ComponentsShader::getTextureFlags(), castor3d::ColourMapComponent::ComponentsShader::getTextureFlags(), castor3d::EmissiveMapComponent::ComponentsShader::getTextureFlags(), castor3d::GlossinessMapComponent::ComponentsShader::getTextureFlags(), castor3d::HeightMapComponent::ComponentsShader::getTextureFlags(), castor3d::IridescenceMapComponent::ComponentsShader::getTextureFlags(), castor3d::IridescenceThicknessMapComponent::ComponentsShader::getTextureFlags(), castor3d::MetalnessMapComponent::ComponentsShader::getTextureFlags(), castor3d::NormalMapComponent::ComponentsShader::getTextureFlags(), castor3d::OcclusionMapComponent::ComponentsShader::getTextureFlags(), castor3d::OpacityMapComponent::ComponentsShader::getTextureFlags(), castor3d::RoughnessMapComponent::ComponentsShader::getTextureFlags(), castor3d::SheenMapComponent::ComponentsShader::getTextureFlags(), castor3d::SheenRoughnessMapComponent::ComponentsShader::getTextureFlags(), castor3d::SpecularFactorMapComponent::ComponentsShader::getTextureFlags(), castor3d::SpecularMapComponent::ComponentsShader::getTextureFlags(), castor3d::TransmissionMapComponent::ComponentsShader::getTextureFlags(), castor3d::TransmittanceMapComponent::ComponentsShader::getTextureFlags(), castor3d::AttenuationMapComponent::Plugin::getTextureFlags(), castor3d::ClearcoatMapComponent::Plugin::getTextureFlags(), castor3d::ClearcoatNormalMapComponent::Plugin::getTextureFlags(), castor3d::ClearcoatRoughnessMapComponent::Plugin::getTextureFlags(), castor3d::ColourMapComponent::Plugin::getTextureFlags(), castor3d::EmissiveMapComponent::Plugin::getTextureFlags(), castor3d::GlossinessMapComponent::Plugin::getTextureFlags(), castor3d::HeightMapComponent::Plugin::getTextureFlags(), castor3d::IridescenceMapComponent::Plugin::getTextureFlags(), castor3d::IridescenceThicknessMapComponent::Plugin::getTextureFlags(), castor3d::MetalnessMapComponent::Plugin::getTextureFlags(), castor3d::NormalMapComponent::Plugin::getTextureFlags(), castor3d::OcclusionMapComponent::Plugin::getTextureFlags(), castor3d::OpacityMapComponent::Plugin::getTextureFlags(), castor3d::RoughnessMapComponent::Plugin::getTextureFlags(), castor3d::SheenMapComponent::Plugin::getTextureFlags(), castor3d::SheenRoughnessMapComponent::Plugin::getTextureFlags(), castor3d::SpecularFactorMapComponent::Plugin::getTextureFlags(), castor3d::SpecularMapComponent::Plugin::getTextureFlags(), castor3d::TransmissionMapComponent::Plugin::getTextureFlags(), and castor3d::TransmittanceMapComponent::Plugin::getTextureFlags().
makeUniformBuffer()
template<typename DataT > UniformBufferUPtrT< DataT > castor3d::makeUniformBuffer (RenderSystem const & renderSystem, VkDeviceSize count, VkBufferUsageFlags usage, VkMemoryPropertyFlags flags, std::string name, ashes::QueueShare sharingMode = {}) inline
makeUniformBufferBase()
UniformBufferBaseUPtr castor3d::makeUniformBufferBase (RenderSystem const & renderSystem, VkDeviceSize count, VkDeviceSize size, VkBufferUsageFlags usage, VkMemoryPropertyFlags flags, std::string name, ashes::QueueShare sharingMode = {}) inline
makeVertexBuffer()
template<typename T > ashes::VertexBufferPtr< T > castor3d::makeVertexBuffer (RenderDevice const & device, VkDeviceSize count, VkBufferUsageFlags usage, VkMemoryPropertyFlags flags, std::string const & name, ashes::QueueShare sharingMode = {}) inline
makeVertexBufferBase()
ashes::VertexBufferBasePtr castor3d::makeVertexBufferBase (RenderDevice const & device, VkDeviceSize size, VkBufferUsageFlags usage, VkMemoryPropertyFlags flags, std::string const & name, ashes::QueueShare sharingMode = {}) inline
makeViewport() [1/6]
VkViewport castor3d::makeViewport (castor::Coords2i const & pos, castor::Coords2ui const & size, float zMin = 0.0f, float zMax = 1.0f) inline
References makeExtent2D(), and makeOffset2D().
makeViewport() [2/6]
VkViewport castor3d::makeViewport (castor::Coords2i const & pos, castor::Point2ui const & size, float zMin = 0.0f, float zMax = 1.0f) inline
References makeExtent2D(), and makeOffset2D().
makeViewport() [3/6]
VkViewport castor3d::makeViewport (castor::Coords2ui const & size, float zMin = 0.0f, float zMax = 1.0f) inline
References makeExtent2D().
makeViewport() [4/6]
VkViewport castor3d::makeViewport (castor::Point2i const & pos, castor::Coords2ui const & size, float zMin = 0.0f, float zMax = 1.0f) inline
References makeExtent2D(), and makeOffset2D().
makeViewport() [5/6]
VkViewport castor3d::makeViewport (castor::Point2i const & pos, castor::Point2ui const & size, float zMin = 0.0f, float zMax = 1.0f) inline
References makeExtent2D(), and makeOffset2D().
makeViewport() [6/6]
VkViewport castor3d::makeViewport (castor::Point2ui const & size, float zMin = 0.0f, float zMax = 1.0f) inline
References makeExtent2D().
makeVkStruct()
template<typename VkStructT , typename ... ParamsT> VkStructT castor3d::makeVkStruct (ParamsT &&... params) inline
makeVkStructPNext()
template<typename VkStructT , typename ... ParamsT> VkStructT castor3d::makeVkStructPNext (void * next, ParamsT &&... params) inline
makeWholeImageView()
C3D_API ashes::ImageView castor3d::makeWholeImageView (ashes::Device const & device, ashes::Image const & image, Texture const & texture)
memoryBarrier()
C3D_API void castor3d::memoryBarrier (crg::RecordContext & context, VkCommandBuffer commandBuffer, ashes::BufferBase const & buffer, crg::BufferSubresourceRange const & range, crg::AccessState after, crg::AccessState before)
mergeConfigs()
C3D_API void castor3d::mergeConfigs (TextureConfiguration const & lhs, TextureConfiguration & rhs)
mergeConfigsBase()
C3D_API void castor3d::mergeConfigsBase (TextureConfiguration const & lhs, TextureConfiguration & rhs)
operator!=() [1/9]
C3D_API bool castor3d::operator!= (castor3d::Version const & a, castor3d::Version const & b)
Difference operator.
Parameters
[in] a,b The versions to compare.
Returns
true if one version number is different from a to b.
operator!=() [2/9]
bool castor3d::operator!= (DirectionalLightCascade const & lhs, DirectionalLightCascade const & rhs) inline
operator!=() [3/9]
C3D_API bool castor3d::operator!= (ParticleDeclaration const & lhs, ParticleDeclaration const & rhs)
Equality operator.
Parameters
[in] lhs,rhs The 2 objects to compare.
operator!=() [4/9]
bool castor3d::operator!= (ParticleElementDeclaration const & lhs, ParticleElementDeclaration const & rhs) inline
Equality operator.
Parameters
[in] lhs,rhs The 2 objects to compare.
References castor3d::ParticleElementDeclaration::m_dataType, castor3d::ParticleElementDeclaration::m_divisor, castor3d::ParticleElementDeclaration::m_name, castor3d::ParticleElementDeclaration::m_offset, and castor3d::ParticleElementDeclaration::m_usages.
operator!=() [5/9]
bool castor3d::operator!= (TextureConfiguration const & lhs, TextureConfiguration const & rhs) inline noexcept
operator!=() [6/9]
bool castor3d::operator!= (TextureFlagConfiguration const & lhs, TextureFlagConfiguration const & rhs) inline noexcept
operator!=() [7/9]
bool castor3d::operator!= (TextureSourceInfo const & lhs, TextureSourceInfo const & rhs) inline noexcept
operator!=() [8/9]
bool castor3d::operator!= (TextureTransform const & lhs, TextureTransform const & rhs) inline noexcept
operator!=() [9/9]
bool castor3d::operator!= (VkImageSubresourceRange const & lhs, VkImageSubresourceRange const & rhs) inline
operator<() [1/4]
C3D_API bool castor3d::operator< (castor3d::Version const & a, castor3d::Version const & b)
Less than operator.
Parameters
[in] a,b The versions to compare.
Returns
true if a.major is less than b.major or if they are equal and a.minor is less than b.minor or if majors and minors are equal and a.build is less than b.build.
operator<() [2/4]
bool castor3d::operator< (MemChunk const & lhs, MemChunk const & rhs) inline
References castor3d::MemChunk::offset.
operator<() [3/4]
C3D_API bool castor3d::operator< (PipelineBaseHash const & lhs, PipelineBaseHash const & rhs)
operator<() [4/4]
bool castor3d::operator< (VkImageSubresourceRange const & lhs, VkImageSubresourceRange const & rhs) inline
operator<<() [1/12]
C3D_API castor::String & castor3d::operator<< (castor::String & stream, castor3d::Version const & version)
operator<<() [2/12]
std::ostream & castor3d::operator<< (std::ostream & o, Cone const & c) inline
operator<<() [3/12]
std::ostream & castor3d::operator<< (std::ostream & o, Cube const & c) inline
operator<<() [4/12]
std::ostream & castor3d::operator<< (std::ostream & o, Cylinder const & c) inline
operator<<() [5/12]
std::ostream & castor3d::operator<< (std::ostream & o, Icosahedron const & c) inline
operator<<() [6/12]
std::ostream & castor3d::operator<< (std::ostream & o, Projection const & c) inline
operator<<() [7/12]
std::ostream & castor3d::operator<< (std::ostream & o, Sphere const & c) inline
operator<<() [8/12]
std::ostream & castor3d::operator<< (std::ostream & o, SphereSection const & c) inline
operator<<() [9/12]
C3D_API std::ostream & castor3d::operator<< (std::ostream & stream, castor3d::Version const & version)
operator<<() [10/12]
C3D_API std::ostream & castor3d::operator<< (std::ostream & stream, GpuInformations const & object)
Output stream operator.
Parameters
[in,out] stream The stream.
[in] object The object to put in the stream.
Returns
The stream.
operator<<() [11/12]
std::ostream & castor3d::operator<< (std::ostream & stream, TextureLayout const & layout)
operator<<() [12/12]
C3D_API std::wostream & castor3d::operator<< (std::wostream & stream, castor3d::Version const & version)
operator<=() [1/2]
C3D_API bool castor3d::operator<= (castor3d::Version const & a, castor3d::Version const & b)
Less than operator.
Parameters
[in] a,b The versions to compare.
Returns
false if a.major is greater than b.major or if they are equal and a.minor is greater than b.minor or if majors and minors are equal and a.build is greater than b.build.
operator<=() [2/2]
bool castor3d::operator<= (VkImageSubresourceRange const & lhs, VkImageSubresourceRange const & rhs) inline
operator==() [1/15]
C3D_API bool castor3d::operator== (castor3d::Version const & a, castor3d::Version const & b)
Equality operator.
Parameters
[in] a,b The versions to compare.
Returns
false if one version number is different from a to b.
operator==() [2/15]
C3D_API bool castor3d::operator== (DirectionalLightCascade const & lhs, DirectionalLightCascade const & rhs)
operator==() [3/15]
C3D_API bool castor3d::operator== (ParticleDeclaration const & lhs, ParticleDeclaration const & rhs)
Equality operator.
Parameters
[in] lhs,rhs The 2 objects to compare.
operator==() [4/15]
bool castor3d::operator== (ParticleElementDeclaration const & lhs, ParticleElementDeclaration const & rhs) inline
Equality operator.
Parameters
[in] lhs,rhs The 2 objects to compare.
References castor3d::ParticleElementDeclaration::m_dataType, castor3d::ParticleElementDeclaration::m_divisor, castor3d::ParticleElementDeclaration::m_name, castor3d::ParticleElementDeclaration::m_offset, and castor3d::ParticleElementDeclaration::m_usages.
operator==() [5/15]
C3D_API bool castor3d::operator== (PassComponentCombine const & lhs, PassComponentCombine const & rhs)
operator==() [6/15]
bool castor3d::operator== (PipelineBaseHash const & lhs, PipelineBaseHash const & rhs) inline
References castor3d::PipelineBaseHash::hi, and castor3d::PipelineBaseHash::lo.
operator==() [7/15]
C3D_API bool castor3d::operator== (PipelineFlags const & lhs, PipelineFlags const & rhs)
operator==() [8/15]
C3D_API bool castor3d::operator== (PipelineHiHashDetails const & lhs, PipelineHiHashDetails const & rhs)
operator==() [9/15]
C3D_API bool castor3d::operator== (PipelineLoHashDetails const & lhs, PipelineLoHashDetails const & rhs)
operator==() [10/15]
C3D_API bool castor3d::operator== (TextureCombine const & lhs, TextureCombine const & rhs)
operator==() [11/15]
C3D_API bool castor3d::operator== (TextureConfiguration const & lhs, TextureConfiguration const & rhs)
operator==() [12/15]
C3D_API bool castor3d::operator== (TextureFlagConfiguration const & lhs, TextureFlagConfiguration const & rhs) noexcept
operator==() [13/15]
C3D_API bool castor3d::operator== (TextureSourceInfo const & lhs, TextureSourceInfo const & rhs) noexcept
operator==() [14/15]
C3D_API bool castor3d::operator== (TextureTransform const & lhs, TextureTransform const & rhs) noexcept
name Comparison operators.
operator==() [15/15]
bool castor3d::operator== (VkImageSubresourceRange const & lhs, VkImageSubresourceRange const & rhs) inline
operator>() [1/2]
C3D_API bool castor3d::operator> (castor3d::Version const & a, castor3d::Version const & b)
Less than operator.
Parameters
[in] a,b The versions to compare.
Returns
true if a.major is greater than b.major or if they are equal and a.minor is greater than b.minor or if majors and minors are equal and a.build is greater than b.build.
operator>() [2/2]
bool castor3d::operator> (VkImageSubresourceRange const & lhs, VkImageSubresourceRange const & rhs) inline
operator>=() [1/2]
C3D_API bool castor3d::operator>= (castor3d::Version const & a, castor3d::Version const & b)
Less than operator.
Parameters
[in] a,b The versions to compare.
Returns
false if a.major is less than b.major or if they are equal and a.minor is less than b.minor or if majors and minors are equal and a.build is less than b.build.
operator>=() [2/2]
bool castor3d::operator>= (VkImageSubresourceRange const & lhs, VkImageSubresourceRange const & rhs) inline
parseImportParameters()
bool castor3d::parseImportParameters (Parameters const & parameters, castor::Point3f & scale, castor::Quaternion & orientation)
postPreRenderGpuEvent()
C3D_API void castor3d::postPreRenderGpuEvent (Engine & engine, std::function< void(RenderDevice const &, QueueData const &) > event)
Referenced by castor3d::DoubleBufferedResourceT< ResourceT, PointerT >::doRefresh().
postQueueRenderCpuEvent()
C3D_API void castor3d::postQueueRenderCpuEvent (Engine & engine, std::function< void() > event)
Referenced by castor3d::DoubleBufferedResourceT< ResourceT, PointerT >::doRefresh().
prepareChunkData() [1/28]
static void castor3d::prepareChunkData (bool & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [2/28]
static void castor3d::prepareChunkData (castor::ColourComponent & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [3/28]
template<typename T , uint32_t Count> static void castor3d::prepareChunkData (castor::Coords< T, Count > & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [4/28]
template<typename T , uint32_t Count> static void castor3d::prepareChunkData (castor::Point< T, Count > & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [5/28]
template<typename T > static void castor3d::prepareChunkData (castor::QuaternionT< T > & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [6/28]
static void castor3d::prepareChunkData (castor::RgbaColour & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [7/28]
static void castor3d::prepareChunkData (castor::RgbColour & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [8/28]
template<typename T , uint32_t Count> static void castor3d::prepareChunkData (castor::SquareMatrix< T, Count > & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [9/28]
static void castor3d::prepareChunkData (ChunkType & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
Referenced by castor3d::ChunkParser< T >::parse(), and castor3d::ChunkWriter< T >::write().
prepareChunkData() [10/28]
static void castor3d::prepareChunkData (double & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [11/28]
static void castor3d::prepareChunkData (FaceIndices & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
References castor3d::FaceIndices::m_index.
prepareChunkData() [12/28]
static void castor3d::prepareChunkData (float & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [13/28]
static void castor3d::prepareChunkData (int16_t & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [14/28]
static void castor3d::prepareChunkData (int32_t & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [15/28]
static void castor3d::prepareChunkData (int64_t & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [16/28]
static void castor3d::prepareChunkData (int8_t & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [17/28]
static void castor3d::prepareChunkData (InterleavedVertex & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
References castor3d::InterleavedVertex::nml, castor3d::InterleavedVertex::pos, castor3d::InterleavedVertex::tan, and castor3d::InterleavedVertex::tex.
prepareChunkData() [18/28]
static void castor3d::prepareChunkData (LineIndices & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
References castor3d::LineIndices::m_index.
prepareChunkData() [19/28]
static void castor3d::prepareChunkData (long double & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [20/28]
template<typename T > static void castor3d::prepareChunkData (OldInterleavedVertexT< T > & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
References castor3d::OldInterleavedVertexT< T >::nml, castor3d::OldInterleavedVertexT< T >::pos, castor3d::OldInterleavedVertexT< T >::tan, and castor3d::OldInterleavedVertexT< T >::tex.
prepareChunkData() [21/28]
template<typename T , size_t Count> static void castor3d::prepareChunkData (std::array< T, Count > & values) inline static
Sets given value to big endian.
Parameters
[in,out] values The value.
prepareChunkData() [22/28]
template<typename T > static void castor3d::prepareChunkData (std::vector< T > & values) inline static
Sets given value to big endian.
Parameters
[in,out] values The value.
prepareChunkData() [23/28]
static void castor3d::prepareChunkData (SubmeshAnimationBuffer & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
References castor3d::SubmeshAnimationBuffer::normals, castor3d::SubmeshAnimationBuffer::positions, castor3d::SubmeshAnimationBuffer::tangents, castor3d::SubmeshAnimationBuffer::texcoords0, castor3d::SubmeshAnimationBuffer::texcoords1, castor3d::SubmeshAnimationBuffer::texcoords2, and castor3d::SubmeshAnimationBuffer::texcoords3.
prepareChunkData() [24/28]
static void castor3d::prepareChunkData (uint16_t & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [25/28]
static void castor3d::prepareChunkData (uint32_t & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [26/28]
static void castor3d::prepareChunkData (uint64_t & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [27/28]
static void castor3d::prepareChunkData (uint8_t & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
prepareChunkData() [28/28]
static void castor3d::prepareChunkData (VertexBoneData & value) inline static
Sets given value to big endian.
Parameters
[in,out] value The value.
References castor3d::VertexBoneData::Ids::data, castor3d::VertexBoneData::Weights::data, castor3d::VertexBoneData::m_ids, and castor3d::VertexBoneData::m_weights.
print() [1/2]
C3D_API std::string castor3d::print (castor::BoundingBox const & obj)
print() [2/2]
C3D_API std::string castor3d::print (castor::Point3f const & obj)
printGraph()
C3D_API void castor3d::printGraph (crg::RunnableGraph const & graph)
registerPipelineNodes()
void castor3d::registerPipelineNodes (PipelineBaseHash hash, ashes::BufferBase const & buffer, std::vector< PipelineBuffer > & nodesIds)
remFlags() [1/4]
C3D_API void castor3d::remFlags (PassComponentCombine & lhs, PassComponentFlag rhs)
remFlags() [2/4]
C3D_API void castor3d::remFlags (PassComponentCombine & lhs, PassComponentFlagsSet const & rhs)
remFlags() [3/4]
C3D_API void castor3d::remFlags (TextureCombine & lhs, PassComponentTextureFlag rhs)
Referenced by castor3d::BlendComponent::Plugin::filterComponentFlags(), castor3d::SubsurfaceScatteringComponent::Plugin::filterComponentFlags(), castor3d::AlphaTestComponent::Plugin::filterComponentFlags(), castor3d::HeightComponent::Plugin::filterComponentFlags(), castor3d::AttenuationMapComponent::Plugin::filterTextureFlags(), castor3d::ClearcoatMapComponent::Plugin::filterTextureFlags(), castor3d::ClearcoatNormalMapComponent::Plugin::filterTextureFlags(), castor3d::ClearcoatRoughnessMapComponent::Plugin::filterTextureFlags(), castor3d::ColourMapComponent::Plugin::filterTextureFlags(), castor3d::EmissiveMapComponent::Plugin::filterTextureFlags(), castor3d::GlossinessMapComponent::Plugin::filterTextureFlags(), castor3d::HeightMapComponent::Plugin::filterTextureFlags(), castor3d::IridescenceMapComponent::Plugin::filterTextureFlags(), castor3d::IridescenceThicknessMapComponent::Plugin::filterTextureFlags(), castor3d::MetalnessMapComponent::Plugin::filterTextureFlags(), castor3d::NormalMapComponent::Plugin::filterTextureFlags(), castor3d::OcclusionMapComponent::Plugin::filterTextureFlags(), castor3d::OpacityMapComponent::Plugin::filterTextureFlags(), castor3d::RoughnessMapComponent::Plugin::filterTextureFlags(), castor3d::SheenMapComponent::Plugin::filterTextureFlags(), castor3d::SheenRoughnessMapComponent::Plugin::filterTextureFlags(), castor3d::SpecularFactorMapComponent::Plugin::filterTextureFlags(), castor3d::SpecularMapComponent::Plugin::filterTextureFlags(), castor3d::TransmissionMapComponent::Plugin::filterTextureFlags(), and castor3d::TransmittanceMapComponent::Plugin::filterTextureFlags().
remFlags() [4/4]
C3D_API void castor3d::remFlags (TextureCombine & lhs, TextureFlagsSet const & rhs)
removeFlag()
C3D_API void castor3d::removeFlag (TextureConfiguration & config, PassComponentTextureFlag rhs)
removeFlagConfiguration()
C3D_API void castor3d::removeFlagConfiguration (TextureConfiguration & config, TextureFlagConfiguration const & flagConfiguration)
setMaterialColour()
void castor3d::setMaterialColour (Pass & pass, castor::HdrRgbColour const & colour)
Sets the pass colour.
Parameters
[in] pass The pass.
[in] colour The material colour.
setProgressBarLabel()
C3D_API void castor3d::setProgressBarLabel (ProgressBar * progress, castor::String const & value)
setProgressBarTitle()
C3D_API void castor3d::setProgressBarTitle (ProgressBar * progress, castor::String const & value)
setupMemory() [1/4]
template<typename ResT > ashes::DeviceMemoryPtr castor3d::setupMemory (ashes::Device const & device, ResT & resource, VkMemoryPropertyFlags flags, std::string const & name) inline
References setupMemory().
Referenced by setupMemory().
setupMemory() [2/4]
C3D_API ashes::DeviceMemoryPtr castor3d::setupMemory (ashes::Device const & device, VkMemoryRequirements const & requirements, VkMemoryPropertyFlags flags, std::string const & name)
setupMemory() [3/4]
template<typename ResT > ashes::DeviceMemoryPtr castor3d::setupMemory (RenderDevice const & device, ResT & resource, VkMemoryPropertyFlags flags, std::string const & name) inline
References setupMemory().
setupMemory() [4/4]
C3D_API ashes::DeviceMemoryPtr castor3d::setupMemory (RenderDevice const & device, VkMemoryRequirements const & requirements, VkMemoryPropertyFlags flags, std::string const & name)
shallowEqual() [1/2]
C3D_API bool castor3d::shallowEqual (TextureConfiguration const & lhs, TextureConfiguration const & rhs)
name Comparison operators.
shallowEqual() [2/2]
C3D_API bool castor3d::shallowEqual (TextureFlagConfiguration const & lhs, TextureFlagConfiguration const & rhs)
name Comparison operators.
splitPassComponentFlag()
std::pair< PassComponentID, PassFlags > castor3d::splitPassComponentFlag (PassComponentFlag flag) inline
splitTextureFlag()
std::pair< PassComponentID, TextureFlags > castor3d::splitTextureFlag (PassComponentTextureFlag flag) inline
Referenced by castor3d::AttenuationMapComponent::Plugin::getTextureFlagsName(), castor3d::ClearcoatMapComponent::Plugin::getTextureFlagsName(), castor3d::ClearcoatNormalMapComponent::Plugin::getTextureFlagsName(), castor3d::ClearcoatRoughnessMapComponent::Plugin::getTextureFlagsName(), castor3d::ColourMapComponent::Plugin::getTextureFlagsName(), castor3d::EmissiveMapComponent::Plugin::getTextureFlagsName(), castor3d::GlossinessMapComponent::Plugin::getTextureFlagsName(), castor3d::HeightMapComponent::Plugin::getTextureFlagsName(), castor3d::IridescenceMapComponent::Plugin::getTextureFlagsName(), castor3d::IridescenceThicknessMapComponent::Plugin::getTextureFlagsName(), castor3d::MetalnessMapComponent::Plugin::getTextureFlagsName(), castor3d::NormalMapComponent::Plugin::getTextureFlagsName(), castor3d::OcclusionMapComponent::Plugin::getTextureFlagsName(), castor3d::OpacityMapComponent::Plugin::getTextureFlagsName(), castor3d::RoughnessMapComponent::Plugin::getTextureFlagsName(), castor3d::SheenMapComponent::Plugin::getTextureFlagsName(), castor3d::SheenRoughnessMapComponent::Plugin::getTextureFlagsName(), castor3d::SpecularFactorMapComponent::Plugin::getTextureFlagsName(), castor3d::SpecularMapComponent::Plugin::getTextureFlagsName(), castor3d::TransmissionMapComponent::Plugin::getTextureFlagsName(), and castor3d::TransmittanceMapComponent::Plugin::getTextureFlagsName().
stepProgressBar() [1/2]
C3D_API void castor3d::stepProgressBar (ProgressBar * progress)
stepProgressBar() [2/2]
C3D_API void castor3d::stepProgressBar (ProgressBar * progress, castor::String const & label)
updateBuffer()
C3D_API void castor3d::updateBuffer (ashes::CommandBuffer const & commandBuffer, castor::ByteArray data, ashes::BufferBase const & dst, std::vector< VkBufferCopy > const & regions, VkAccessFlags dstAccessFlags, VkPipelineStageFlags dstPipelineFlags)
updateIndices()
C3D_API void castor3d::updateIndices (castor::PixelFormat format, TextureConfiguration & config)
uploadBaseData()
C3D_API void castor3d::uploadBaseData (SubmeshFlag submeshData, Submesh const & submesh, castor::Point3fArray const & data)
Variable Documentation
BaseObjectPoolBufferCount
uint32_t constexpr castor3d::BaseObjectPoolBufferCount = 1'048'576u static constexpr
CurrentCmshVersion
uint32_t constexpr castor3d::CurrentCmshVersion = makeCmshVersion(0x01u, 0x06u, 0x0000u) constexpr
The current format version number.
Referenced by castor3d::BinaryParserBase< TParsed >::doParseHeader(), and castor3d::BinaryWriterBase< TWritten >::doWriteHeader().
defaultClearDepthStencil
VkClearValue const castor3d::defaultClearDepthStencil { makeClearValue(0.0f, 0u) } static
defaultColorWriteMask
VkColorComponentFlags const castor3d::defaultColorWriteMask { VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT } static
EnvironmentMapSize
uint32_t constexpr castor3d::EnvironmentMapSize = 0x0001u << (EnvironmentMipLevels - 1u) static constexpr
EnvironmentMipLevels
uint32_t constexpr castor3d::EnvironmentMipLevels = 8u static constexpr
InvalidIndex
uint32_t constexpr castor3d::InvalidIndex = ~(0u) static constexpr
InvalidPipelineIndex
uint32_t constexpr castor3d::InvalidPipelineIndex = ~(0u) static constexpr
LpvMaxCascadesCount
uint32_t constexpr castor3d::LpvMaxCascadesCount = 3u static constexpr
LpvMaxPropagationSteps
uint32_t constexpr castor3d::LpvMaxPropagationSteps = 8u static constexpr
Referenced by castor3d::LayeredLightPropagationVolumesT< GeometryVolumesT >::countInitialisationSteps(), and castor3d::LightPropagationVolumesT< GeometryVolumesT >::countInitialisationSteps().
MaxBackgroundModels
uint32_t constexpr castor3d::MaxBackgroundModels = 63u static constexpr
MaxBillboardDrawIndirectCommand
uint64_t constexpr castor3d::MaxBillboardDrawIndirectCommand = MaxPipelines static constexpr
MaxBindlessResources
uint32_t constexpr castor3d::MaxBindlessResources = 16'384u static constexpr
MaxBonesCount
uint32_t constexpr castor3d::MaxBonesCount = 512u static constexpr
MaxBonesPerVertex
uint32_t constexpr castor3d::MaxBonesPerVertex = 8u static constexpr
MaxCharsPerBuffer
uint32_t constexpr castor3d::MaxCharsPerBuffer = 65'536u static constexpr
MaxCharsPerOverlay
uint32_t constexpr castor3d::MaxCharsPerOverlay = 1'024u static constexpr
MaxDirectionalCascadesCount
uint32_t constexpr castor3d::MaxDirectionalCascadesCount = 6u static constexpr
MaxEnvironmentMapCount
uint32_t constexpr castor3d::MaxEnvironmentMapCount = 10u static constexpr
MaxIblReflectionLod
uint32_t constexpr castor3d::MaxIblReflectionLod = 4u static constexpr
MaxLightingModels
uint32_t constexpr castor3d::MaxLightingModels = 63u static constexpr
MaxLightsCount
uint32_t constexpr castor3d::MaxLightsCount = 2'048u static constexpr
MaxLinearizedDepthMipLevel
uint32_t constexpr castor3d::MaxLinearizedDepthMipLevel = 5u static constexpr
MaxLinesPerBuffer
uint32_t constexpr castor3d::MaxLinesPerBuffer = 16'384u static constexpr
MaxLinesPerOverlay
uint32_t constexpr castor3d::MaxLinesPerOverlay = 1'024u static constexpr
MaxMaterialComponentsCount
int32_t constexpr castor3d::MaxMaterialComponentsCount = 8 static constexpr
MaxMaterialsCount
uint32_t constexpr castor3d::MaxMaterialsCount = 2'048u static constexpr
MaxMeshletTriangleCount
uint32_t constexpr castor3d::MaxMeshletTriangleCount = 124u static constexpr
MaxMeshletVertexCount
uint32_t constexpr castor3d::MaxMeshletVertexCount = 64u static constexpr
MaxMorphingDataCount
uint32_t constexpr castor3d::MaxMorphingDataCount = 1'024u static constexpr
MaxMorphTargets
uint32_t constexpr castor3d::MaxMorphTargets = 128u static constexpr
MaxNodesPerPipeline
uint64_t constexpr castor3d::MaxNodesPerPipeline = 1'024ull static constexpr
MaxObjectIDNodesCount
uint32_t constexpr castor3d::MaxObjectIDNodesCount = 16'384u static constexpr
MaxObjectNodesCount
uint64_t constexpr castor3d::MaxObjectNodesCount = 262'144ull static constexpr
MaxOverlaysPerBuffer
uint32_t constexpr castor3d::MaxOverlaysPerBuffer = 65'536u static constexpr
MaxPassLayers
uint32_t constexpr castor3d::MaxPassLayers = 15u static constexpr
MaxPassTextures
uint32_t constexpr castor3d::MaxPassTextures = 8u static constexpr
MaxPcfFilterSize
uint32_t constexpr castor3d::MaxPcfFilterSize = 64u static constexpr
MaxPcfSampleCount
uint32_t constexpr castor3d::MaxPcfSampleCount = 64u static constexpr
MaxPhongShininess
float constexpr castor3d::MaxPhongShininess = 256.0f static constexpr
MaxPipelines
uint64_t constexpr castor3d::MaxPipelines = 32'768ull static constexpr
MaxPointShadowMapCount
uint32_t constexpr castor3d::MaxPointShadowMapCount = 8u static constexpr
MaxRsmRange
uint32_t constexpr castor3d::MaxRsmRange = 1'024u static constexpr
MaxSkinningDataCount
uint32_t constexpr castor3d::MaxSkinningDataCount = 1'024u static constexpr
MaxSpotShadowMapCount
uint32_t constexpr castor3d::MaxSpotShadowMapCount = 16u static constexpr
MaxSssProfilesCount
uint32_t constexpr castor3d::MaxSssProfilesCount = 128u static constexpr
MaxSubmeshIdxDrawIndirectCommand
uint64_t constexpr castor3d::MaxSubmeshIdxDrawIndirectCommand = MaxPipelines static constexpr
MaxSubmeshMeshletDrawIndirectCommand
uint64_t constexpr castor3d::MaxSubmeshMeshletDrawIndirectCommand = MaxPipelines static constexpr
MaxSubmeshNIdxDrawIndirectCommand
uint64_t constexpr castor3d::MaxSubmeshNIdxDrawIndirectCommand = MaxPipelines static constexpr
MaxTextsContsPerOverlay
uint32_t constexpr castor3d::MaxTextsContsPerOverlay = MaxCharsPerOverlay static constexpr
MaxTextureAnimationCount
uint32_t constexpr castor3d::MaxTextureAnimationCount = 4'096u static constexpr
MaxTextureConfigurationCount
uint32_t constexpr castor3d::MaxTextureConfigurationCount = 4'096u static constexpr
MaxTextureCoordinatesSets
uint32_t constexpr castor3d::MaxTextureCoordinatesSets = 4u static constexpr
MaxWordsPerBuffer
uint32_t constexpr castor3d::MaxWordsPerBuffer = 16'384u static constexpr
opaqueBlackClearColor
VkClearValue const castor3d::opaqueBlackClearColor { makeClearValue(0.0f, 0.0f, 0.0f, 1.0f) } static
opaqueWhiteClearColor
VkClearValue const castor3d::opaqueWhiteClearColor { makeClearValue(1.0f, 1.0f, 1.0f, 1.0f) } static
PickingAreaWidth
uint32_t constexpr castor3d::PickingAreaWidth = 32u static constexpr
PrefilteredBrdfMapSize
uint32_t constexpr castor3d::PrefilteredBrdfMapSize = 512u static constexpr
PrefilteredEnvironmentMapSize
uint32_t constexpr castor3d::PrefilteredEnvironmentMapSize = 128u static constexpr
RadianceMapSize
uint32_t constexpr castor3d::RadianceMapSize = 32u static constexpr
RandomDataCount
uint32_t constexpr castor3d::RandomDataCount = 1024u static constexpr
RenderTypeUndefined
castor::String const castor3d::RenderTypeUndefined = cuT("Undefined")
ShadowMapDirectionalTextureSize
uint32_t constexpr castor3d::ShadowMapDirectionalTextureSize = 2048u static constexpr
ShadowMapPointTextureSize
uint32_t constexpr castor3d::ShadowMapPointTextureSize = 256u static constexpr
ShadowMapSpotTextureSize
uint32_t constexpr castor3d::ShadowMapSpotTextureSize = 256u static constexpr
TransmittanceProfileSize
uint32_t constexpr castor3d::TransmittanceProfileSize = 10u static constexpr
transparentBlackClearColor
VkClearValue const castor3d::transparentBlackClearColor { makeClearValue(0.0f, 0.0f, 0.0f, 0.0f) } static
transparentWhiteClearColor
VkClearValue const castor3d::transparentWhiteClearColor { makeClearValue(1.0f, 1.0f, 1.0f, 0.0f) } static
VctMaxDiffuseCones
uint32_t constexpr castor3d::VctMaxDiffuseCones = 16u static constexpr
VctMaxTextureSize
uint32_t constexpr castor3d::VctMaxTextureSize = 512u static constexpr