Castor3D: castor3d::ShadowMapUbo Class Reference
castor3d::ShadowMapUbo Class Reference
#include <ShadowMapUbo.hpp>
Public Types
using Configuration = ShadowMapUboConfiguration
Public Member Functions
C3D_API ShadowMapUbo (RenderDevice const &device)
C3D_API ShadowMapUbo (ShadowMapUbo const &rhs)=delete
C3D_API ShadowMapUbo & operator= (ShadowMapUbo const &rhs)=delete
C3D_API ShadowMapUbo (ShadowMapUbo &&rhs) noexcept=default
C3D_API ShadowMapUbo & operator= (ShadowMapUbo &&rhs) noexcept=delete
C3D_API ~ShadowMapUbo () noexcept
C3D_API void update (Light const &light, uint32_t index)
Updates the UBO from given values.
void createSizedBinding (ashes::DescriptorSet &descriptorSet, VkDescriptorSetLayoutBinding const &layoutBinding) const
ashes::WriteDescriptorSet getDescriptorWrite (uint32_t dstBinding, uint32_t dstArrayElement=0u) const
void addDescriptorWrite (ashes::WriteDescriptorSetArray &descriptorWrites, uint32_t &dstBinding, uint32_t dstArrayElement=0u) const
UniformBufferOffsetT< Configuration > const & getUbo () const
Member Typedef Documentation
Configuration
using castor3d::ShadowMapUbo::Configuration = ShadowMapUboConfiguration
Constructor & Destructor Documentation
ShadowMapUbo() [1/3]
C3D_API castor3d::ShadowMapUbo::ShadowMapUbo (RenderDevice const & device) explicit
ShadowMapUbo() [2/3]
C3D_API castor3d::ShadowMapUbo::ShadowMapUbo (ShadowMapUbo const & rhs) delete
ShadowMapUbo() [3/3]
C3D_API castor3d::ShadowMapUbo::ShadowMapUbo (ShadowMapUbo && rhs) default noexcept
~ShadowMapUbo()
C3D_API castor3d::ShadowMapUbo::~ShadowMapUbo () noexcept
Member Function Documentation
addDescriptorWrite()
void castor3d::ShadowMapUbo::addDescriptorWrite (ashes::WriteDescriptorSetArray & descriptorWrites, uint32_t & dstBinding, uint32_t dstArrayElement = 0u) const inline
References getDescriptorWrite().
createSizedBinding()
void castor3d::ShadowMapUbo::createSizedBinding (ashes::DescriptorSet & descriptorSet, VkDescriptorSetLayoutBinding const & layoutBinding) const inline
References castor3d::UniformBufferOffsetT< DataT >::createSizedBinding().
getDescriptorWrite()
ashes::WriteDescriptorSet castor3d::ShadowMapUbo::getDescriptorWrite (uint32_t dstBinding, uint32_t dstArrayElement = 0u) const inline
References castor3d::UniformBufferOffsetT< DataT >::getDescriptorWrite().
Referenced by addDescriptorWrite().
getUbo()
UniformBufferOffsetT< Configuration > const & castor3d::ShadowMapUbo::getUbo () const inline
operator=() [1/2]
C3D_API ShadowMapUbo & castor3d::ShadowMapUbo::operator= (ShadowMapUbo && rhs) delete noexcept
operator=() [2/2]
C3D_API ShadowMapUbo & castor3d::ShadowMapUbo::operator= (ShadowMapUbo const & rhs) delete
update()
C3D_API void castor3d::ShadowMapUbo::update (Light const & light, uint32_t index)
Updates the UBO from given values.
Parameters
[in] light The light source from which the shadow map is generated.
[in] index The shadow pass index.
The documentation for this class was generated from the following file:
Castor3D/Shader/Ubos/ShadowMapUbo.hpp