Castor3D: castor3d::shader::IndirectLighting Struct Reference
castor3d::shader::IndirectLighting Struct Reference
#include <GlslOutputComponents.hpp>
Public Member Functions
IndirectLighting (sdw::ShaderWriter &writer, sdw::expr::ExprPtr expr, bool enabled)
IndirectLighting (sdw::ShaderWriter &writer)
auto ambient () const
auto rawDiffuse () const
auto specular () const
auto occlusion () const
auto diffuseColour () const
auto diffuseBlend () const
Constructor & Destructor Documentation
IndirectLighting() [1/2]
castor3d::shader::IndirectLighting::IndirectLighting (sdw::ShaderWriter & writer, sdw::expr::ExprPtr expr, bool enabled) inline
IndirectLighting() [2/2]
castor3d::shader::IndirectLighting::IndirectLighting (sdw::ShaderWriter & writer) inline explicit
Member Function Documentation
ambient()
auto castor3d::shader::IndirectLighting::ambient () const inline
diffuseBlend()
auto castor3d::shader::IndirectLighting::diffuseBlend () const inline
References rawDiffuse().
diffuseColour()
auto castor3d::shader::IndirectLighting::diffuseColour () const inline
References rawDiffuse().
occlusion()
auto castor3d::shader::IndirectLighting::occlusion () const inline
rawDiffuse()
auto castor3d::shader::IndirectLighting::rawDiffuse () const inline
Referenced by diffuseBlend(), and diffuseColour().
specular()
auto castor3d::shader::IndirectLighting::specular () const inline
The documentation for this struct was generated from the following file:
Castor3D/Shader/Shaders/GlslOutputComponents.hpp