Castor3D: castor3d::PipelineVisitorBase Class Reference
castor3d::PipelineVisitorBase Class Reference abstract
#include <PipelineVisitor.hpp>
Classes
struct Config
Public Member Functions
virtual C3D_API ~PipelineVisitorBase ()=default
virtual C3D_API void visit (ShaderModule const &shader)=0
virtual C3D_API void visit (DebugConfig const &config)=0
void visit (castor::String const &name, crg::ImageViewId const &viewId, VkImageLayout layout, TextureFactors const &factors={})
void visit (castor::String const &name, Texture const &texture, VkImageLayout layout, TextureFactors const &factors={})
virtual C3D_API void visit (castor::String const &name, bool &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, int16_t &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, uint16_t &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, int32_t &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, uint32_t &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, int64_t &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, uint64_t &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, int32_t &enumValue, castor::StringArray const &enumNames, bool *control)=0
virtual C3D_API void visit (castor::String const &name, uint32_t &enumValue, castor::StringArray const &enumNames, bool *control)=0
virtual C3D_API void visit (castor::String const &name, float &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, double &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, BlendMode &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, ParallaxOcclusionMode &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, PassFlags &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkCompareOp &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::RgbColour &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::RgbaColour &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::HdrRgbColour &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::HdrRgbaColour &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::Point2f &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::Point2i &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::Point2ui &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::Point3f &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::Point3i &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::Point3ui &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::Point4f &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::Point4i &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::Point4ui &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::Matrix4x4f &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::RangedValue< float > &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::RangedValue< int32_t > &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::RangedValue< uint32_t > &value, bool *control=nullptr)=0
template<typename TypeT >
void visit (castor::String const &name, castor::ChangeTracked< TypeT > &value)
template<typename TypeT >
void visit (castor::String const &name, castor::GroupChangeTracked< TypeT > &value)
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, float &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, int32_t &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, uint32_t &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, castor::Point2f &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, castor::Point2i &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, castor::Point2ui &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, castor::Point3f &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, castor::Point3i &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, castor::Point3ui &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, castor::Point4f &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, castor::Point4i &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, castor::Point4ui &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, castor::Matrix4x4f &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, castor::RangedValue< float > &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, castor::RangedValue< int32_t > &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, castor::RangedValue< uint32_t > &value, bool *control=nullptr)=0
template<typename TypeT >
void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, castor::ChangeTracked< TypeT > &value)
template<typename TypeT >
void visit (castor::String const &name, VkShaderStageFlags shaders, castor::String const &bufferName, castor::String const &varName, castor::GroupChangeTracked< TypeT > &value)
Public Attributes
Config const config
Protected Member Functions
PipelineVisitorBase (Config config)
virtual C3D_API bool doFilter (crg::ImageViewId const &viewId) const =0
Constructor & Destructor Documentation
PipelineVisitorBase()
castor3d::PipelineVisitorBase::PipelineVisitorBase (Config config) inline explicit protected
~PipelineVisitorBase()
virtual C3D_API castor3d::PipelineVisitorBase::~PipelineVisitorBase () virtual default
Member Function Documentation
doFilter()
virtual C3D_API bool castor3d::PipelineVisitorBase::doFilter (crg::ImageViewId const & viewId) const protected pure virtual
visit() [1/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, BlendMode & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [2/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, bool & value, bool * control = nullptr) pure virtual
name Global pipeline configuration.
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [3/56]
template<typename TypeT > void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::ChangeTracked< TypeT > & value) inline
References visit().
visit() [4/56]
template<typename TypeT > void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::GroupChangeTracked< TypeT > & value) inline
References visit().
visit() [5/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::HdrRgbaColour & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [6/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::HdrRgbColour & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [7/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::Matrix4x4f & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [8/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::Point2f & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [9/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::Point2i & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [10/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::Point2ui & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [11/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::Point3f & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [12/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::Point3i & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [13/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::Point3ui & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [14/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::Point4f & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [15/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::Point4i & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [16/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::Point4ui & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [17/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::RangedValue< float > & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [18/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::RangedValue< int32_t > & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [19/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::RangedValue< uint32_t > & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [20/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::RgbaColour & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [21/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, castor::RgbColour & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [22/56]
void castor3d::PipelineVisitorBase::visit (castor::String const & name, crg::ImageViewId const & viewId, VkImageLayout layout, TextureFactors const & factors = {}) inline
name Intermediate images.
visit() [23/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, double & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [24/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, float & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [25/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, int16_t & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [26/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, int32_t & enumValue, castor::StringArray const & enumNames, bool * control) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [27/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, int32_t & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [28/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, int64_t & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [29/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, ParallaxOcclusionMode & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [30/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, PassFlags & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [31/56]
void castor3d::PipelineVisitorBase::visit (castor::String const & name, Texture const & texture, VkImageLayout layout, TextureFactors const & factors = {}) inline
visit() [32/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, uint16_t & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [33/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, uint32_t & enumValue, castor::StringArray const & enumNames, bool * control) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [34/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, uint32_t & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [35/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, uint64_t & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [36/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkCompareOp & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [37/56]
template<typename TypeT > void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, castor::ChangeTracked< TypeT > & value) inline
References visit().
visit() [38/56]
template<typename TypeT > void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, castor::GroupChangeTracked< TypeT > & value) inline
References visit().
visit() [39/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, castor::Matrix4x4f & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [40/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, castor::Point2f & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [41/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, castor::Point2i & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [42/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, castor::Point2ui & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [43/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, castor::Point3f & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [44/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, castor::Point3i & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [45/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, castor::Point3ui & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [46/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, castor::Point4f & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [47/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, castor::Point4i & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [48/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, castor::Point4ui & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [49/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, castor::RangedValue< float > & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [50/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, castor::RangedValue< int32_t > & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [51/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, castor::RangedValue< uint32_t > & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [52/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, float & value, bool * control = nullptr) pure virtual
name Shader buffer configuration.
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [53/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, int32_t & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [54/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (castor::String const & name, VkShaderStageFlags shaders, castor::String const & bufferName, castor::String const & varName, uint32_t & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [55/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (DebugConfig const & config) pure virtual
Implemented in castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
visit() [56/56]
virtual C3D_API void castor3d::PipelineVisitorBase::visit (ShaderModule const & shader) pure virtual
name Shader source.
Implemented in castor3d::RenderTechniqueVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, castor3d::ToneMappingVisitor, castor3d::PipelineVisitor, castor3d::RenderTechniqueVisitor, and castor3d::ToneMappingVisitor.
Referenced by visit().
Member Data Documentation
config
Config const castor3d::PipelineVisitorBase::config
The documentation for this class was generated from the following file:
Miscellaneous/PipelineVisitor.hpp