Castor3D: castor::RangedValue< T > Class Template Reference
castor::RangedValue< T > Class Template Reference
A value inside a range.
#include <RangedValue.hpp>
Public Member Functions
RangedValue (T const &value, Range< T > const &range) noexcept
Constructor.
RangedValue & operator= (T const &value) noexcept
Assignment from a value.
void updateRange (Range< T > const &range) noexcept
Redefines the range.
float percent () const noexcept
T const & value () const noexcept
Range< T > const & range () const noexcept
Arithmetic operators.
RangedValue< T > & operator+= (RangedValue< T > const &rhs) noexcept
RangedValue< T > & operator-= (RangedValue< T > const &rhs) noexcept
RangedValue< T > & operator*= (RangedValue< T > const &rhs) noexcept
RangedValue< T > & operator/= (RangedValue< T > const &rhs) noexcept
RangedValue< T > & operator+= (T const &rhs) noexcept
RangedValue< T > & operator-= (T const &rhs) noexcept
RangedValue< T > & operator*= (T const &rhs) noexcept
RangedValue< T > & operator/= (T const &rhs) noexcept
Detailed Description
template<typename T>
class castor::RangedValue< T >
A value inside a range.
Remarks
The value can't get out of its range.
Constructor & Destructor Documentation
RangedValue()
template<typename T > castor::RangedValue< T >::RangedValue (T const & value, Range< T > const & range) inline noexcept
Constructor.
Parameters
[in] value The value.
[in] range The range.
References castor::RangedValue< T >::range().
Member Function Documentation
operator*=() [1/2]
template<typename T > RangedValue< T > & castor::RangedValue< T >::operator*= (RangedValue< T > const & rhs) inline noexcept
operator*=() [2/2]
template<typename T > RangedValue< T > & castor::RangedValue< T >::operator*= (T const & rhs) inline noexcept
operator+=() [1/2]
template<typename T > RangedValue< T > & castor::RangedValue< T >::operator+= (RangedValue< T > const & rhs) inline noexcept
operator+=() [2/2]
template<typename T > RangedValue< T > & castor::RangedValue< T >::operator+= (T const & rhs) inline noexcept
operator-=() [1/2]
template<typename T > RangedValue< T > & castor::RangedValue< T >::operator-= (RangedValue< T > const & rhs) inline noexcept
operator-=() [2/2]
template<typename T > RangedValue< T > & castor::RangedValue< T >::operator-= (T const & rhs) inline noexcept
operator/=() [1/2]
template<typename T > RangedValue< T > & castor::RangedValue< T >::operator/= (RangedValue< T > const & rhs) inline noexcept
operator/=() [2/2]
template<typename T > RangedValue< T > & castor::RangedValue< T >::operator/= (T const & rhs) inline noexcept
operator=()
template<typename T > RangedValue & castor::RangedValue< T >::operator= (T const & value) inline noexcept
Assignment from a value.
Parameters
[in] value The value.
References castor::RangedValue< T >::value().
percent()
template<typename T > float castor::RangedValue< T >::percent () const inline noexcept
Returns
0.0 if m_value <= m_range.m_min.
1.0 if m_value >= m_range.m_max.
A value from 0.0 to 1.0, depending on how close the value is from m_range.m_min or from m_range.m_max.
range()
template<typename T > Range< T > const & castor::RangedValue< T >::range () const inline noexcept
Returns
The range.
Referenced by castor3d::SliderCtrl::getRange(), castor3d::ProgressCtrl::getRange(), castor::RangedValue< T >::RangedValue(), and castor::RangedValue< T >::updateRange().
updateRange()
template<typename T > void castor::RangedValue< T >::updateRange (Range< T > const & range) inline noexcept
Redefines the range.
Parameters
[in] range The range.
References castor::RangedValue< T >::range().
value()
template<typename T > T const & castor::RangedValue< T >::value () const inline noexcept
Returns
The value.
Referenced by castor3d::ProgressCtrl::getProgress(), castor3d::SliderCtrl::getValue(), castor3d::ProgressCtrl::incProgress(), and castor::RangedValue< T >::operator=().
The documentation for this class was generated from the following files:
CastorUtils/Math/MathModule.hpp
CastorUtils/Math/RangedValue.hpp