Castor3D: castor3d::PassVisitorBase Class Reference
castor3d::PassVisitorBase Class Reference abstract
#include <PassVisitor.hpp>
Classes
struct Config
Public Member Functions
virtual C3D_API ~PassVisitorBase ()=default
virtual C3D_API void visit (castor::String const &name, bool &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, int16_t &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, uint16_t &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, int32_t &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, uint32_t &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, int64_t &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, uint64_t &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, float &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, double &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, BlendMode &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, ParallaxOcclusionMode &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, PassFlags &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, VkCompareOp &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::RgbColour &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::RgbaColour &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::HdrRgbColour &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::HdrRgbaColour &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::Point2f &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::Point2i &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::Point2ui &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::Point3f &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::Point3i &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::Point3ui &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::Point4f &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::Point4i &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::Point4ui &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::Matrix4x4f &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::RangedValue< float > &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::RangedValue< int32_t > &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, castor::RangedValue< uint32_t > &value, bool *control=nullptr)=0
virtual C3D_API void visit (castor::String const &name, TextureFlag textureFlag, castor::Point2ui &value, uint32_t componentsCount, bool *control=nullptr)=0
template<typename TypeT >
void visit (castor::String const &name, castor::ChangeTracked< TypeT > &value)
template<typename TypeT >
void visit (castor::String const &name, castor::GroupChangeTracked< TypeT > &value)
Public Attributes
Config const config
Protected Member Functions
PassVisitorBase (Config config)
Constructor & Destructor Documentation
PassVisitorBase()
castor3d::PassVisitorBase::PassVisitorBase (Config config) inline explicit protected
~PassVisitorBase()
virtual C3D_API castor3d::PassVisitorBase::~PassVisitorBase () virtual default
Member Function Documentation
visit() [1/33]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, BlendMode & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [2/33]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, bool & value, bool * control = nullptr) pure virtual
name Values.
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
Referenced by visit().
visit() [3/33]
template<typename TypeT > void castor3d::PassVisitorBase::visit (castor::String const & name, castor::ChangeTracked< TypeT > & value) inline
References visit().
visit() [4/33]
template<typename TypeT > void castor3d::PassVisitorBase::visit (castor::String const & name, castor::GroupChangeTracked< TypeT > & value) inline
References visit().
visit() [5/33]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::HdrRgbaColour & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [6/33]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::HdrRgbColour & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [7/33]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Matrix4x4f & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [8/33]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point2f & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [9/33]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point2i & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [10/33]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point2ui & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [11/33]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point3f & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [12/33]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point3i & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [13/33]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point3ui & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [14/33]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point4f & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [15/33]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point4i & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [16/33]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::Point4ui & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [17/33]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::RangedValue< float > & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [18/33]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::RangedValue< int32_t > & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [19/33]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::RangedValue< uint32_t > & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [20/33]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::RgbaColour & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [21/33]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, castor::RgbColour & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [22/33]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, double & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [23/33]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, float & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [24/33]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, int16_t & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [25/33]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, int32_t & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [26/33]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, int64_t & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [27/33]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, ParallaxOcclusionMode & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [28/33]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, PassFlags & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [29/33]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, TextureFlag textureFlag, castor::Point2ui & value, uint32_t componentsCount, bool * control = nullptr) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [30/33]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, uint16_t & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [31/33]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, uint32_t & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [32/33]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, uint64_t & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
visit() [33/33]
virtual C3D_API void castor3d::PassVisitorBase::visit (castor::String const & name, VkCompareOp & value, bool * control = nullptr) pure virtual
Implemented in castor3d::PassVisitor, and castor3d::PassVisitor.
Member Data Documentation
config
Config const castor3d::PassVisitorBase::config
The documentation for this class was generated from the following file:
Material/Pass/PassVisitor.hpp