Castor3D: castor3d::GpuInformations Class Reference
castor3d::GpuInformations Class Reference
#include <GpuInformations.hpp>
Public Member Functions
GpuInformations ()
Constructor.
void addFeature (GpuFeature feature) noexcept
Adds a supported feature.
void removeFeature (GpuFeature feature) noexcept
Removes a supported feature.
void updateFeature (GpuFeature feature, bool supported) noexcept
Updates the support for a feature.
bool hasFeature (GpuFeature feature) const noexcept
Tells if the feature is supported supports stereo.
bool hasStereoRendering () const noexcept
bool hasShaderStorageBuffers () const noexcept
bool hasShaderType (VkShaderStageFlagBits type) const noexcept
void useShaderType (VkShaderStageFlagBits type, bool value) noexcept
Defines the support for given shader type.
uint32_t getValue (GpuMin index) const noexcept
void setValue (GpuMin index, uint32_t value) noexcept
uint32_t getValue (GpuMax index) const noexcept
void setValue (GpuMax index, uint32_t value) noexcept
uint32_t getTotalMemorySize () const noexcept
void setTotalMemorySize (uint32_t value) noexcept
castor::String const & getVendor () const noexcept
void setVendor (castor::StringView value) noexcept
castor::String const & getRenderer () const noexcept
void setRenderer (castor::StringView value) noexcept
castor::String const & getVersion () const noexcept
void setVersion (castor::StringView value) noexcept
Friends
class Context
Constructor & Destructor Documentation
GpuInformations()
castor3d::GpuInformations::GpuInformations () inline
Constructor.
References castor3d::eCount.
Member Function Documentation
addFeature()
void castor3d::GpuInformations::addFeature (GpuFeature feature) inline noexcept
Adds a supported feature.
Referenced by updateFeature().
getRenderer()
castor::String const & castor3d::GpuInformations::getRenderer () const inline noexcept
Returns
The GPU platform.
getTotalMemorySize()
uint32_t castor3d::GpuInformations::getTotalMemorySize () const inline noexcept
Returns
The total VRAM size.
getValue() [1/2]
uint32_t castor3d::GpuInformations::getValue (GpuMax index) const inline noexcept
Parameters
[in] index The index.
Returns
The maximum value for given index.
getValue() [2/2]
uint32_t castor3d::GpuInformations::getValue (GpuMin index) const inline noexcept
Parameters
[in] index The index.
Returns
The minimum value for given index.
Referenced by castor3d::RenderSystem::getValue(), and castor3d::RenderSystem::getValue().
getVendor()
castor::String const & castor3d::GpuInformations::getVendor () const inline noexcept
Returns
The GPU vendor name.
getVersion()
castor::String const & castor3d::GpuInformations::getVersion () const inline noexcept
Returns
The rendering API version.
hasFeature()
bool castor3d::GpuInformations::hasFeature (GpuFeature feature) const inline noexcept
Tells if the feature is supported supports stereo.
References castor3d::checkFlag().
Referenced by castor3d::RenderSystem::hasFeature(), hasShaderStorageBuffers(), and hasStereoRendering().
hasShaderStorageBuffers()
bool castor3d::GpuInformations::hasShaderStorageBuffers () const inline noexcept
Returns
The SSBO support status.
References castor3d::eShaderStorageBuffers, and hasFeature().
Referenced by castor3d::RenderSystem::hasShaderStorageBuffers().
hasShaderType()
bool castor3d::GpuInformations::hasShaderType (VkShaderStageFlagBits type) const inline noexcept
Parameters
[in] type The shader type.
Returns
The shader type support status.
Referenced by castor3d::RenderSystem::hasShaderType().
hasStereoRendering()
bool castor3d::GpuInformations::hasStereoRendering () const inline noexcept
Returns
The stereo support status.
References castor3d::eStereoRendering, and hasFeature().
Referenced by castor3d::RenderSystem::hasStereoRendering().
removeFeature()
void castor3d::GpuInformations::removeFeature (GpuFeature feature) inline noexcept
Removes a supported feature.
Referenced by updateFeature().
setRenderer()
void castor3d::GpuInformations::setRenderer (castor::StringView value) inline noexcept
Parameters
[in] value The GPU platform.
setTotalMemorySize()
void castor3d::GpuInformations::setTotalMemorySize (uint32_t value) inline noexcept
Parameters
[in] value The total VRAM size.
setValue() [1/2]
void castor3d::GpuInformations::setValue (GpuMax index, uint32_t value) inline noexcept
Parameters
[in] index The index.
[in] value The maximum value for given index.
setValue() [2/2]
void castor3d::GpuInformations::setValue (GpuMin index, uint32_t value) inline noexcept
Parameters
[in] index The index.
[in] value The minimum value for given index.
setVendor()
void castor3d::GpuInformations::setVendor (castor::StringView value) inline noexcept
Parameters
[in] value The GPU vendor name.
setVersion()
void castor3d::GpuInformations::setVersion (castor::StringView value) inline noexcept
Parameters
[in] value The rendering API version.
updateFeature()
void castor3d::GpuInformations::updateFeature (GpuFeature feature, bool supported) inline noexcept
Updates the support for a feature.
References addFeature(), and removeFeature().
useShaderType()
void castor3d::GpuInformations::useShaderType (VkShaderStageFlagBits type, bool value) inline noexcept
Defines the support for given shader type.
Parameters
[in] type The shader type.
[in] value The new value.
Friends And Related Symbol Documentation
Context
friend class Context friend
The documentation for this class was generated from the following file:
Castor3D/Miscellaneous/GpuInformations.hpp