Castor3D: castor3d::GBufferBase Class Reference
castor3d::GBufferBase Class Reference
#include <GBuffer.hpp>
Public Member Functions
C3D_API GBufferBase (RenderDevice const &device, castor::String name)
Protected Member Functions
C3D_API TexturePtr doCreateTexture (crg::ResourcesCache &resources, castor::String const &name, VkImageCreateFlags createFlags, VkExtent3D const &size, uint32_t layerCount, VkSampleCountFlagBits sampleCount, uint32_t mipLevels, VkFormat format, VkImageUsageFlags usageFlags, VkBorderColor const &borderColor, VkCompareOp compareOp) const
template<typename TextureEnumT >
TextureArray doCreateTextures (crg::ResourcesCache &resources, std::array< TexturePtr, size_t(TextureEnumT::eCount) > const &inputs, castor::String const &prefix, VkImageCreateFlags createFlags, castor::Size const &size, uint32_t layerCount=1u, VkSampleCountFlagBits sampleCount=VK_SAMPLE_COUNT_1_BIT) const
Initialises 2D or 2D array g-buffer textures.
template<typename TextureEnumT >
TextureArray doCreateTextures (crg::ResourcesCache &resources, std::array< TexturePtr, size_t(TextureEnumT::eCount) > const &inputs, castor::String const &prefix, VkImageCreateFlags createFlags, VkExtent3D const &size, VkSampleCountFlagBits sampleCount=VK_SAMPLE_COUNT_1_BIT) const
Initialises 3D g-buffer textures.
Protected Attributes
RenderDevice const & m_device
Constructor & Destructor Documentation
GBufferBase()
C3D_API castor3d::GBufferBase::GBufferBase (RenderDevice const & device, castor::String name) explicit
Member Function Documentation
doCreateTexture()
C3D_API TexturePtr castor3d::GBufferBase::doCreateTexture (crg::ResourcesCache & resources, castor::String const & name, VkImageCreateFlags createFlags, VkExtent3D const & size, uint32_t layerCount, VkSampleCountFlagBits sampleCount, uint32_t mipLevels, VkFormat format, VkImageUsageFlags usageFlags, VkBorderColor const & borderColor, VkCompareOp compareOp) const protected
Referenced by doCreateTextures().
doCreateTextures() [1/2]
template<typename TextureEnumT > TextureArray castor3d::GBufferBase::doCreateTextures (crg::ResourcesCache & resources, std::array< TexturePtr, size_t(TextureEnumT::eCount) > const & inputs, castor::String const & prefix, VkImageCreateFlags createFlags, castor::Size const & size, uint32_t layerCount = 1u, VkSampleCountFlagBits sampleCount = VK_SAMPLE_COUNT_1_BIT) const inline protected
Initialises 2D or 2D array g-buffer textures.
Parameters
[in] resources The render graph resource handler.
[in] inputs The already existing images.
[in] prefix The buffer's textures name's prefix.
[in] createFlags The creation flags for images remaining to create.
[in] size The g-buffer's dimensions.
[in] layerCount The layers count for the g-buffer.
[in] sampleCount The images samples count.
References doCreateTexture(), castor3d::getBorderColor(), castor3d::getCompareOp(), castor3d::getFormat(), castor3d::getMipLevels(), castor3d::getTexName(), castor3d::getUsageFlags(), and m_device.
doCreateTextures() [2/2]
template<typename TextureEnumT > TextureArray castor3d::GBufferBase::doCreateTextures (crg::ResourcesCache & resources, std::array< TexturePtr, size_t(TextureEnumT::eCount) > const & inputs, castor::String const & prefix, VkImageCreateFlags createFlags, VkExtent3D const & size, VkSampleCountFlagBits sampleCount = VK_SAMPLE_COUNT_1_BIT) const inline protected
Initialises 3D g-buffer textures.
Parameters
[in] resources The render graph resource handler.
[in] inputs The already existing images.
[in] prefix The buffer's textures name's prefix.
[in] createFlags The creation flags for images remaining to create.
[in] size The g-buffer's dimensions.
[in] sampleCount The images samples count.
References doCreateTexture(), castor3d::getBorderColor(), castor3d::getCompareOp(), castor3d::getFormat(), castor3d::getMipLevels(), castor3d::getTexName(), castor3d::getUsageFlags(), and m_device.
Member Data Documentation
m_device
RenderDevice const& castor3d::GBufferBase::m_device protected
Referenced by doCreateTextures().
The documentation for this class was generated from the following file:
Render/GBuffer.hpp