Castor3D: castor3d::ShaderProgram Class Reference
castor3d::ShaderProgram Class Reference abstract
Base shader program implementation, used to share functions through the supported shader languages.
Classes
class TextWriter
ShaderProgram loader.
Public Member Functions
C3D_API ShaderProgram (RenderSystem &renderSystem)
Constructor.
virtual C3D_API ~ShaderProgram ()
Destructor.
C3D_API ShaderObjectSPtr createObject (ShaderType p_type)
Creates the wanted shader object.
C3D_API void setFile (castor::Path const &p_pathFile)
sets all objects file.
C3D_API AtomicCounterBuffer & createAtomicCounterBuffer (castor::String const &p_name, ShaderTypeFlags const &p_shaderMask)
Creates an atomic counter buffer.
C3D_API AtomicCounterBufferSPtr findAtomicCounterBuffer (castor::String const &p_name) const
Finds an atomic counter buffer.
C3D_API void resetToCompile ()
Resets compilation variables to be able to compile again.
C3D_API void setInputType (ShaderType p_target, Topology p_topology)
sets the input primitives type.
C3D_API void setOutputType (ShaderType p_target, Topology p_topology)
sets the output primitives type.
C3D_API void setOutputVtxCount (ShaderType p_target, uint8_t p_count)
sets the output vertex count.
C3D_API void setFile (ShaderType p_target, castor::Path const &p_pathFile)
sets the shader file.
C3D_API castor::Path getFile (ShaderType p_target) const
Retrieves the shader file.
C3D_API bool hasFile (ShaderType p_target) const
Tells if the shader object has a source file.
C3D_API void setSource (ShaderType p_target, castor::String const &p_source)
sets the shader source.
C3D_API void setSource (ShaderType p_target, glsl::Shader const &p_source)
sets the shader source.
C3D_API castor::String getSource (ShaderType p_target) const
Retrieves the shader source.
C3D_API bool hasSource (ShaderType p_target) const
Tells if the shader object has a source code.
C3D_API bool hasObject (ShaderType p_target) const
Tests if the program has an object for given type.
C3D_API ShaderStatus getObjectStatus (ShaderType p_target) const
C3D_API PushUniformSPtr createUniform (UniformType type, castor::String const &name, ShaderType shader, int nbOcc=1)
Creates a variable.
template<UniformType Type>
std::shared_ptr< TPushUniform< Type > > createUniform (castor::String const &name, ShaderType shader, int nbOcc=1)
Creates a variable.
C3D_API PushUniformSPtr findUniform (UniformType type, castor::String const &name, ShaderType shader) const
Looks for a variable.
template<UniformType Type>
std::shared_ptr< TPushUniform< Type > > findUniform (castor::String const &name, ShaderType shader) const
Looks for a variable.
C3D_API PushUniformList & getUniforms (ShaderType p_type)
Retrieves the frame variables buffer bound to one shader type.
C3D_API PushUniformList const & getUniforms (ShaderType p_type) const
Retrieves the frame variables bound to one shader type.
virtual C3D_API void cleanup ()=0
Cleans the program up.
virtual C3D_API bool initialise ()=0
Initialises the program.
virtual C3D_API void bind () const =0
Activates the program.
virtual C3D_API void unbind () const =0
Deactivates the program.
virtual C3D_API bool link ()=0
Links all shader objects held by the program.
virtual C3D_API ProgramInputLayout const & getLayout () const =0
virtual C3D_API ProgramInputLayout & getLayout ()=0
void setTransformLayout (BufferDeclaration const &p_declaration)
sets the transform feedback layout.
AtomicCounterBufferPtrList & getAtomicCounterBuffers (ShaderType p_type)
Retrieves the atomic counter buffers bound to one shader type.
AtomicCounterBufferPtrList const & getAtomicCounterBuffers (ShaderType p_type) const
Retrieves the atomic counter buffers bound to one shader type.
AtomicCounterBufferPtrList & getAtomicCounterBuffers ()
AtomicCounterBufferPtrList const & getAtomicCounterBuffers () const
ProgramStatus getStatus () const
Retrieves the program link status.
Static Public Attributes
Attributes
static C3D_API const castor::String Position
static C3D_API const castor::String Normal
static C3D_API const castor::String Tangent
static C3D_API const castor::String Bitangent
static C3D_API const castor::String Texture
static C3D_API const castor::String Colour
static C3D_API const castor::String Position2
static C3D_API const castor::String Normal2
static C3D_API const castor::String Tangent2
static C3D_API const castor::String Bitangent2
static C3D_API const castor::String Texture2
static C3D_API const castor::String Colour2
static C3D_API const castor::String Text
static C3D_API const castor::String BoneIds0
static C3D_API const castor::String BoneIds1
static C3D_API const castor::String Weights0
static C3D_API const castor::String Weights1
static C3D_API const castor::String Transform
static C3D_API const castor::String Material
Scene
static C3D_API const castor::String Lights
Textures
static C3D_API const castor::String MapAlbedo
static C3D_API const castor::String MapDiffuse
static C3D_API const castor::String MapSpecular
static C3D_API const castor::String MapRoughness
static C3D_API const castor::String MapEmissive
static C3D_API const castor::String MapNormal
static C3D_API const castor::String MapOpacity
static C3D_API const castor::String MapGloss
static C3D_API const castor::String MapMetallic
static C3D_API const castor::String MapHeight
static C3D_API const castor::String MapAmbientOcclusion
static C3D_API const castor::String MapTransmittance
static C3D_API const castor::String MapEnvironment
static C3D_API const castor::String MapIrradiance
static C3D_API const castor::String MapPrefiltered
static C3D_API const castor::String MapBrdf
static C3D_API const castor::String MapText
Protected Member Functions
C3D_API void doCleanup ()
Cleans the program up.
C3D_API bool doInitialise ()
Initialises the program.
C3D_API void doBind () const
Activates the program.
C3D_API void doUnbind () const
Deactivates the program.
C3D_API bool doLink ()
Links all shader objects held by the program.
Protected Attributes
ProgramStatus m_status { ProgramStatus::eNotLinked }
std::array< ShaderObjectSPtr, size_t(ShaderType::eCount) > m_shaders
std::vector< ShaderObjectSPtr > m_activeShaders
castor::Path m_file
AtomicCounterBufferPtrStrMap m_atomicCounterBuffersByName
std::array< AtomicCounterBufferPtrList, size_t(ShaderType::eCount) > m_atomicCounterBuffers
AtomicCounterBufferPtrList m_listAtomicCounterBuffers
BufferDeclaration m_declaration
Friends
class castor::TextWriter< castor3d::ShaderProgram >
Detailed Description
Base shader program implementation, used to share functions through the supported shader languages.
Author
Sylvain DOREMUS
Version
0.6.1.2
Date
24/01/2011
Constructor & Destructor Documentation
ShaderProgram()
C3D_API castor3d::ShaderProgram::ShaderProgram (RenderSystem & renderSystem) explicit
Constructor.
Parameters
[in] renderSystem The RenderSystem instance.
~ShaderProgram()
virtual C3D_API castor3d::ShaderProgram::~ShaderProgram () virtual
Destructor.
Member Function Documentation
bind()
virtual C3D_API void castor3d::ShaderProgram::bind () const pure virtual
Activates the program.
cleanup()
virtual C3D_API void castor3d::ShaderProgram::cleanup () pure virtual
Cleans the program up.
createAtomicCounterBuffer()
C3D_API AtomicCounterBuffer& castor3d::ShaderProgram::createAtomicCounterBuffer (castor::String const & p_name, ShaderTypeFlags const & p_shaderMask)
Creates an atomic counter buffer.
Parameters
[in] p_name The buffer name.
[in] p_shaderMask ShaderTypeFlag combination, to set at what shaders it is to be bound.
Returns
The created or retrieved Frame variable buffer.
createObject()
C3D_API ShaderObjectSPtr castor3d::ShaderProgram::createObject (ShaderType p_type)
Creates the wanted shader object.
Parameters
[in] p_type The shader object concerned.
createUniform() [1/2]
C3D_API PushUniformSPtr castor3d::ShaderProgram::createUniform (UniformType type, castor::String const & name, ShaderType shader, int nbOcc = 1)
Creates a variable.
Parameters
[in] type The variable type.
[in] name The variable name.
[in] shader The shader type.
[in] nbOcc The array dimension.
Returns
The created variable, nullptr if failed.
Referenced by createUniform().
createUniform() [2/2]
template<UniformType Type> std::shared_ptr< TPushUniform< Type > > castor3d::ShaderProgram::createUniform (castor::String const & name, ShaderType shader, int nbOcc = 1) inline
Creates a variable.
Parameters
[in] name The variable name.
[in] shader The shader type.
[in] nbOcc The array dimension.
Returns
The created variable, nullptr if failed.
References createUniform().
doBind()
C3D_API void castor3d::ShaderProgram::doBind () const protected
Activates the program.
doCleanup()
C3D_API void castor3d::ShaderProgram::doCleanup () protected
Cleans the program up.
doInitialise()
C3D_API bool castor3d::ShaderProgram::doInitialise () protected
Initialises the program.
doLink()
C3D_API bool castor3d::ShaderProgram::doLink () protected
Links all shader objects held by the program.
doUnbind()
C3D_API void castor3d::ShaderProgram::doUnbind () const protected
Deactivates the program.
findAtomicCounterBuffer()
C3D_API AtomicCounterBufferSPtr castor3d::ShaderProgram::findAtomicCounterBuffer (castor::String const & p_name) const
Finds an atomic counter buffer.
Parameters
[in] p_name The buffer name.
Returns
The found buffer, nullptr if failed.
findUniform() [1/2]
C3D_API PushUniformSPtr castor3d::ShaderProgram::findUniform (UniformType type, castor::String const & name, ShaderType shader) const
Looks for a variable.
Parameters
[in] type The variable type.
[in] name The variable name.
[in] shader The shader type.
Returns
The found variable, nullptr if failed.
Referenced by findUniform().
findUniform() [2/2]
template<UniformType Type> std::shared_ptr< TPushUniform< Type > > castor3d::ShaderProgram::findUniform (castor::String const & name, ShaderType shader) const inline
Looks for a variable.
Parameters
[in] name The variable name.
[in] shader The shader type.
Returns
The found variable, nullptr if failed.
References findUniform().
getAtomicCounterBuffers() [1/4]
AtomicCounterBufferPtrList& castor3d::ShaderProgram::getAtomicCounterBuffers (ShaderType p_type) inline
Retrieves the atomic counter buffers bound to one shader type.
Parameters
[in] p_type The shader type
Returns
The list
References m_atomicCounterBuffers.
getAtomicCounterBuffers() [2/4]
AtomicCounterBufferPtrList const& castor3d::ShaderProgram::getAtomicCounterBuffers (ShaderType p_type) const inline
Retrieves the atomic counter buffers bound to one shader type.
Parameters
[in] p_type The shader type
Returns
The list
References m_atomicCounterBuffers.
getAtomicCounterBuffers() [3/4]
AtomicCounterBufferPtrList& castor3d::ShaderProgram::getAtomicCounterBuffers () inline
Returns
The atomic counter buffers list.
References m_listAtomicCounterBuffers.
getAtomicCounterBuffers() [4/4]
AtomicCounterBufferPtrList const& castor3d::ShaderProgram::getAtomicCounterBuffers () const inline
Returns
The atomic counter buffers list.
References m_listAtomicCounterBuffers.
getFile()
C3D_API castor::Path castor3d::ShaderProgram::getFile (ShaderType p_target) const
Retrieves the shader file.
Parameters
[in] p_target The shader object concerned.
Returns
The file name.
getLayout() [1/2]
virtual C3D_API ProgramInputLayout const& castor3d::ShaderProgram::getLayout () const pure virtual
Returns
The program vertex layout.
getLayout() [2/2]
virtual C3D_API ProgramInputLayout& castor3d::ShaderProgram::getLayout () pure virtual
Returns
The program vertex layout.
getObjectStatus()
C3D_API ShaderStatus castor3d::ShaderProgram::getObjectStatus (ShaderType p_target) const
Returns
The given object type status.
getSource()
C3D_API castor::String castor3d::ShaderProgram::getSource (ShaderType p_target) const
Retrieves the shader source.
Parameters
[in] p_target The shader object concerned.
Returns
The source code.
getStatus()
ProgramStatus castor3d::ShaderProgram::getStatus () const inline
Retrieves the program link status.
Returns
The value.
References m_status.
getUniforms() [1/2]
C3D_API PushUniformList& castor3d::ShaderProgram::getUniforms (ShaderType p_type)
Retrieves the frame variables buffer bound to one shader type.
Parameters
[in] p_type The shader type.
Returns
The list.
getUniforms() [2/2]
C3D_API PushUniformList const& castor3d::ShaderProgram::getUniforms (ShaderType p_type) const
Retrieves the frame variables bound to one shader type.
Parameters
[in] p_type The shader type.
Returns
The list.
hasFile()
C3D_API bool castor3d::ShaderProgram::hasFile (ShaderType p_target) const
Tells if the shader object has a source file.
Parameters
[in] p_target The shader object concerned.
Returns
true if the shader object has a source file.
hasObject()
C3D_API bool castor3d::ShaderProgram::hasObject (ShaderType p_target) const
Tests if the program has an object for given type.
Parameters
[in] p_target The shader object type.
Returns
true if the shader object exists.
hasSource()
C3D_API bool castor3d::ShaderProgram::hasSource (ShaderType p_target) const
Tells if the shader object has a source code.
Parameters
[in] p_target The shader object concerned.
Returns
true if the shader object has a source code.
initialise()
virtual C3D_API bool castor3d::ShaderProgram::initialise () pure virtual
Initialises the program.
link()
virtual C3D_API bool castor3d::ShaderProgram::link () pure virtual
Links all shader objects held by the program.
resetToCompile()
C3D_API void castor3d::ShaderProgram::resetToCompile ()
Resets compilation variables to be able to compile again.
setFile() [1/2]
C3D_API void castor3d::ShaderProgram::setFile (castor::Path const & p_pathFile)
sets all objects file.
Parameters
[in] p_pathFile The file name.
setFile() [2/2]
C3D_API void castor3d::ShaderProgram::setFile (ShaderType p_target, castor::Path const & p_pathFile)
sets the shader file.
Parameters
[in] p_target The shader object concerned.
[in] p_pathFile The file name.
setInputType()
C3D_API void castor3d::ShaderProgram::setInputType (ShaderType p_target, Topology p_topology)
sets the input primitives type.
Parameters
[in] p_target The shader object concerned.
[in] p_topology The input primitives type.
setOutputType()
C3D_API void castor3d::ShaderProgram::setOutputType (ShaderType p_target, Topology p_topology)
sets the output primitives type.
Parameters
[in] p_target The shader object concerned.
[in] p_topology The output primitives type.
setOutputVtxCount()
C3D_API void castor3d::ShaderProgram::setOutputVtxCount (ShaderType p_target, uint8_t p_count)
sets the output vertex count.
Parameters
[in] p_target The shader object concerned.
[in] p_count The count.
setSource() [1/2]
C3D_API void castor3d::ShaderProgram::setSource (ShaderType p_target, castor::String const & p_source)
sets the shader source.
Parameters
[in] p_target The shader object concerned.
[in] p_source The source code.
setSource() [2/2]
C3D_API void castor3d::ShaderProgram::setSource (ShaderType p_target, glsl::Shader const & p_source)
sets the shader source.
Parameters
[in] p_target The shader object concerned.
[in] p_source The source code.
setTransformLayout()
void castor3d::ShaderProgram::setTransformLayout (BufferDeclaration const & p_declaration) inline
sets the transform feedback layout.
Parameters
[in] p_declaration The layout.
References m_declaration.
unbind()
virtual C3D_API void castor3d::ShaderProgram::unbind () const pure virtual
Deactivates the program.
Friends And Related Function Documentation
castor::TextWriter< castor3d::ShaderProgram >
friend class castor::TextWriter< castor3d::ShaderProgram > friend
Member Data Documentation
Bitangent
C3D_API const castor::String castor3d::ShaderProgram::Bitangent static
Name of the bitangent attribute.
Bitangent2
C3D_API const castor::String castor3d::ShaderProgram::Bitangent2 static
Name of the bitangent attribute for per-vertex animations.
BoneIds0
C3D_API const castor::String castor3d::ShaderProgram::BoneIds0 static
Name of the first bones ID attribute.
BoneIds1
C3D_API const castor::String castor3d::ShaderProgram::BoneIds1 static
Name of the second bones ID attribute.
Colour
C3D_API const castor::String castor3d::ShaderProgram::Colour static
Name of the colour attribute.
Colour2
C3D_API const castor::String castor3d::ShaderProgram::Colour2 static
Name of the colour attribute for per-vertex animations.
Lights
C3D_API const castor::String castor3d::ShaderProgram::Lights static
Name of the lights frame variable.
m_activeShaders
std::vector< ShaderObjectSPtr > castor3d::ShaderProgram::m_activeShaders protected
The active shaders array.
m_atomicCounterBuffers
std::array< AtomicCounterBufferPtrList, size_t(ShaderType::eCount) > castor3d::ShaderProgram::m_atomicCounterBuffers protected
The atomic counter buffers map, ordered by shader type.
Referenced by getAtomicCounterBuffers().
m_atomicCounterBuffersByName
AtomicCounterBufferPtrStrMap castor3d::ShaderProgram::m_atomicCounterBuffersByName protected
The atomic counter buffers map, ordered by name.
m_declaration
BufferDeclaration castor3d::ShaderProgram::m_declaration protected
The transform feedback layout.
Referenced by setTransformLayout().
m_file
castor::Path castor3d::ShaderProgram::m_file protected
Array of files path, sorted by shader model.
m_listAtomicCounterBuffers
AtomicCounterBufferPtrList castor3d::ShaderProgram::m_listAtomicCounterBuffers protected
The atomic counter buffers map.
Referenced by getAtomicCounterBuffers().
m_shaders
std::array< ShaderObjectSPtr, size_t(ShaderType::eCount) > castor3d::ShaderProgram::m_shaders protected
The shaders array.
m_status
ProgramStatus castor3d::ShaderProgram::m_status { ProgramStatus::eNotLinked } protected
< The program status.
Referenced by getStatus().
MapAlbedo
C3D_API const castor::String castor3d::ShaderProgram::MapAlbedo static
Name of the albedo texture frame variable.
MapAmbientOcclusion
C3D_API const castor::String castor3d::ShaderProgram::MapAmbientOcclusion static
Name of the ambient occlusion texture frame variable.
MapBrdf
C3D_API const castor::String castor3d::ShaderProgram::MapBrdf static
Name of the BRDF texture frame variable.
MapDiffuse
C3D_API const castor::String castor3d::ShaderProgram::MapDiffuse static
Name of the diffuse texture frame variable.
MapEmissive
C3D_API const castor::String castor3d::ShaderProgram::MapEmissive static
Name of the emissive texture frame variable.
MapEnvironment
C3D_API const castor::String castor3d::ShaderProgram::MapEnvironment static
Name of the environment texture frame variable.
MapGloss
C3D_API const castor::String castor3d::ShaderProgram::MapGloss static
Name of the shininess texture frame variable.
MapHeight
C3D_API const castor::String castor3d::ShaderProgram::MapHeight static
Name of the height texture frame variable.
MapIrradiance
C3D_API const castor::String castor3d::ShaderProgram::MapIrradiance static
Name of the irradiance texture frame variable.
MapMetallic
C3D_API const castor::String castor3d::ShaderProgram::MapMetallic static
Name of the metallic texture frame variable.
MapNormal
C3D_API const castor::String castor3d::ShaderProgram::MapNormal static
Name of the emissive texture frame variable.
MapOpacity
C3D_API const castor::String castor3d::ShaderProgram::MapOpacity static
Name of the opacity texture frame variable.
MapPrefiltered
C3D_API const castor::String castor3d::ShaderProgram::MapPrefiltered static
Name of the prefiltered map texture frame variable.
MapRoughness
C3D_API const castor::String castor3d::ShaderProgram::MapRoughness static
Name of the roughness texture frame variable.
MapSpecular
C3D_API const castor::String castor3d::ShaderProgram::MapSpecular static
Name of the specular texture frame variable.
MapText
C3D_API const castor::String castor3d::ShaderProgram::MapText static
Name of the overlay text image frame variable.
MapTransmittance
C3D_API const castor::String castor3d::ShaderProgram::MapTransmittance static
Name of the transmittance texture frame variable.
Material
C3D_API const castor::String castor3d::ShaderProgram::Material static
Name of the instance material index attribute.
Normal
C3D_API const castor::String castor3d::ShaderProgram::Normal static
Name of the normal attribute.
Normal2
C3D_API const castor::String castor3d::ShaderProgram::Normal2 static
Name of the normal attribute for per-vertex animations.
Position
C3D_API const castor::String castor3d::ShaderProgram::Position static
Name of the position attribute.
Position2
C3D_API const castor::String castor3d::ShaderProgram::Position2 static
Name of the position attribute for per-vertex animations.
Tangent
C3D_API const castor::String castor3d::ShaderProgram::Tangent static
Name of the tangent attribute.
Tangent2
C3D_API const castor::String castor3d::ShaderProgram::Tangent2 static
Name of the tangent attribute for per-vertex animations.
Text
C3D_API const castor::String castor3d::ShaderProgram::Text static
Name of the text overlay texture attribute.
Texture
C3D_API const castor::String castor3d::ShaderProgram::Texture static
Name of the texture attribute.
Texture2
C3D_API const castor::String castor3d::ShaderProgram::Texture2 static
Name of the texture attribute for per-vertex animations.
Transform
C3D_API const castor::String castor3d::ShaderProgram::Transform static
Name of the instance transform attribute.
Weights0
C3D_API const castor::String castor3d::ShaderProgram::Weights0 static
Name of the first bones weight attribute.
Weights1
C3D_API const castor::String castor3d::ShaderProgram::Weights1 static
Name of the second bones weight attribute.
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Shader/ShaderProgram.hpp