Castor3D: castor3d::shader::LightsBuffer Class Reference
castor3d::shader::LightsBuffer Class Reference
#include <GlslLight.hpp>
Public Member Functions
C3D_API LightsBuffer (sdw::ShaderWriter &writer, uint32_t binding, uint32_t set, bool enable=true)
C3D_API DirectionalLight getDirectionalLight (sdw::UInt const &offset)
C3D_API PointLight getPointLight (sdw::UInt const &offset)
C3D_API SpotLight getSpotLight (sdw::UInt const &offset)
sdw::UInt getDirectionalsEnd () const
sdw::UInt getPointsEnd () const
sdw::UInt getSpotsEnd () const
sdw::UInt getClusteredGridScale () const
Public Member Functions inherited from castor3d::shader::BufferT< BufferData >
BufferT (sdw::ShaderWriter &writer, castor::MbString blockName, castor::MbString variableName, uint32_t binding, uint32_t set, bool enabled=true, ParamsT &&... params)
BufferData getData (sdw::UInt const &index, ParamsT &&... params) const
Public Member Functions inherited from castor3d::shader::BufferBase
BufferBase (sdw::ShaderWriter &writer, castor::MbString blockName, castor::MbString variableName, uint32_t binding, uint32_t set, bool enabled=true)
sdw::UInt getFirstCount () const
sdw::UInt getSecondCount () const
sdw::UInt getThirdCount () const
sdw::UInt getFourthCount () const
sdw::UInt getCount () const
bool isEnabled () const noexcept
sdw::ShaderWriter * getWriter () const noexcept
Additional Inherited Members
Protected Attributes inherited from castor3d::shader::BufferBase
sdw::ShaderWriter & m_writer
castor::RawUniquePtr< sdw::StorageBuffer > m_ssbo
castor::MbString m_variableName
Constructor & Destructor Documentation
LightsBuffer()
C3D_API castor3d::shader::LightsBuffer::LightsBuffer (sdw::ShaderWriter & writer, uint32_t binding, uint32_t set, bool enable = true)
Member Function Documentation
getClusteredGridScale()
sdw::UInt castor3d::shader::LightsBuffer::getClusteredGridScale () const inline
References castor3d::shader::BufferBase::getFourthCount().
getDirectionalLight()
C3D_API DirectionalLight castor3d::shader::LightsBuffer::getDirectionalLight (sdw::UInt const & offset)
getDirectionalsEnd()
sdw::UInt castor3d::shader::LightsBuffer::getDirectionalsEnd () const inline
References castor3d::shader::BufferBase::getFirstCount().
getPointLight()
C3D_API PointLight castor3d::shader::LightsBuffer::getPointLight (sdw::UInt const & offset)
getPointsEnd()
sdw::UInt castor3d::shader::LightsBuffer::getPointsEnd () const inline
References castor3d::shader::BufferBase::getSecondCount().
getSpotLight()
C3D_API SpotLight castor3d::shader::LightsBuffer::getSpotLight (sdw::UInt const & offset)
getSpotsEnd()
sdw::UInt castor3d::shader::LightsBuffer::getSpotsEnd () const inline
References castor3d::shader::BufferBase::getThirdCount().
The documentation for this class was generated from the following file:
Castor3D/Shader/Shaders/GlslLight.hpp