Castor3D: castor3d::PassMasksComponent Class Reference
castor3d::PassMasksComponent Class Reference
#include <PassMasksComponent.hpp>
Public Member Functions
C3D_API PassMasksComponent (Submesh &submesh)
Constructor.
C3D_API void gather (PipelineFlags const &flags, MaterialRPtr material, ashes::BufferCRefArray &buffers, std::vector< uint64_t > &offsets, ashes::PipelineVertexInputStateCreateInfoCRefArray &layouts, uint32_t &currentBinding, uint32_t &currentLocation) override
Gathers buffers that need to go in a vertex layout.
C3D_API SubmeshComponentSPtr clone (Submesh &submesh) const override
C3D_API void addDatas (PassMasks const *const begin, PassMasks const *const end)
Adds bone datas.
C3D_API void addDatas (std::vector< PassMasks > const &data)
Adds masks datas.
template<size_t Count>
void addDatas (std::array< PassMasks, Count > const &data)
Adds masks datas.
SubmeshFlags getSubmeshFlags (Pass const *pass) const override
bool hasData () const
void setData (std::vector< PassMasks > data)
std::vector< PassMasks > & getData ()
std::vector< PassMasks > const & getData () const
Public Member Functions inherited from castor3d::SubmeshComponent
C3D_API SubmeshComponent (Submesh &submesh, castor::String const &type, uint32_t id)
Constructor.
virtual C3D_API ~SubmeshComponent () noexcept=default
Destructor.
C3D_API bool initialise (RenderDevice const &device)
Initialises the submesh.
C3D_API void cleanup (RenderDevice const &device)
Cleans the submesh.
C3D_API void upload ()
Uploads data on VRAM.
virtual C3D_API void gather (PipelineFlags const &flags, MaterialRPtr material, ashes::BufferCRefArray &buffers, std::vector< uint64_t > &offsets, ashes::PipelineVertexInputStateCreateInfoCRefArray &layouts, uint32_t &currentBinding, uint32_t &currentLocation)=0
Gathers buffers that need to go in a vertex layout.
virtual C3D_API ProgramFlags getProgramFlags (Material const &material) const
virtual C3D_API SubmeshFlags getSubmeshFlags (Pass const *pass) const
virtual C3D_API VkBufferUsageFlags getUsageFlags () const
virtual C3D_API SubmeshComponentSPtr clone (Submesh &submesh) const =0
castor::String const & getType () const
void needsUpdate ()
Sets the component to be updated.
uint32_t getID ()
Static Public Attributes
static C3D_API castor::String const Name
static C3D_API uint32_t constexpr Id = getIndex(SubmeshFlag::ePassMasks) - 1u
Friends
class BinaryWriter< PassMasksComponent >
class BinaryParser< PassMasksComponent >
Constructor & Destructor Documentation
PassMasksComponent()
C3D_API castor3d::PassMasksComponent::PassMasksComponent (Submesh & submesh) explicit
Constructor.
Parameters
[in] submesh The parent submesh.
Member Function Documentation
addDatas() [1/3]
C3D_API void castor3d::PassMasksComponent::addDatas (PassMasks const *const begin, PassMasks const *const end)
Adds bone datas.
Parameters
[in] begin The bones data begin.
[in] end The bones data end.
Referenced by addDatas().
addDatas() [2/3]
template<size_t Count> void castor3d::PassMasksComponent::addDatas (std::array< PassMasks, Count > const & data) inline
Adds masks datas.
Parameters
[in] data The masks datas.
References addDatas().
addDatas() [3/3]
C3D_API void castor3d::PassMasksComponent::addDatas (std::vector< PassMasks > const & data)
Adds masks datas.
Parameters
[in] data The masks.
clone()
C3D_API SubmeshComponentSPtr castor3d::PassMasksComponent::clone (Submesh & submesh) const override virtual
Returns
Clones this component into given submesh.
Parameters
[in,out] submesh Receives the cloned component.
Implements castor3d::SubmeshComponent.
gather()
C3D_API void castor3d::PassMasksComponent::gather (PipelineFlags const & flags, MaterialRPtr material, ashes::BufferCRefArray & buffers, std::vector< uint64_t > & offsets, ashes::PipelineVertexInputStateCreateInfoCRefArray & layouts, uint32_t & currentBinding, uint32_t & currentLocation) override virtual
Gathers buffers that need to go in a vertex layout.
Parameters
[in] flags The pipeline flags.
[in] material The material.
[in,out] buffers Receives the buffers.
[in,out] offsets Receives the buffers offsets.
[in,out] layouts Receives the vertex layouts.
[in,out] currentBinding The current buffer binding.
[in,out] currentLocation The current attribute location.
Implements castor3d::SubmeshComponent.
getData() [1/2]
std::vector< PassMasks > & castor3d::PassMasksComponent::getData () inline
getData() [2/2]
std::vector< PassMasks > const & castor3d::PassMasksComponent::getData () const inline
getSubmeshFlags()
SubmeshFlags castor3d::PassMasksComponent::getSubmeshFlags (Pass const * pass) const inline override virtual
Returns
The submesh flags.
Reimplemented from castor3d::SubmeshComponent.
References castor3d::ePassMasks, and hasData().
hasData()
bool castor3d::PassMasksComponent::hasData () const inline
Referenced by getSubmeshFlags().
setData()
void castor3d::PassMasksComponent::setData (std::vector< PassMasks > data) inline
Friends And Related Function Documentation
BinaryParser< PassMasksComponent >
friend class BinaryParser< PassMasksComponent > friend
BinaryWriter< PassMasksComponent >
friend class BinaryWriter< PassMasksComponent > friend
Member Data Documentation
Id
C3D_API uint32_t constexpr castor3d::PassMasksComponent::Id = getIndex(SubmeshFlag::ePassMasks) - 1u static constexpr
Name
C3D_API castor::String const castor3d::PassMasksComponent::Name static
The documentation for this class was generated from the following file:
Model/Mesh/Submesh/Component/PassMasksComponent.hpp