Castor3D: castor3d::ProgressBar Class Reference
castor3d::ProgressBar Class Reference
#include <ProgressBar.hpp>
Public Member Functions
C3D_API ProgressBar (Engine &engine, OverlayResPtr parent, OverlayResPtr bar, TextOverlaySPtr title, TextOverlaySPtr label, uint32_t max)
C3D_API void setTitle (castor::String const &value)
C3D_API void setLabel (castor::String const &value)
C3D_API void step (castor::String const &label)
C3D_API void step ()
void setRange (uint32_t max)
void incRange (uint32_t mod)
uint32_t getIndex () const
void lock ()
void unlock ()
Constructor & Destructor Documentation
ProgressBar()
C3D_API castor3d::ProgressBar::ProgressBar (Engine & engine, OverlayResPtr parent, OverlayResPtr bar, TextOverlaySPtr title, TextOverlaySPtr label, uint32_t max)
Member Function Documentation
getIndex()
uint32_t castor3d::ProgressBar::getIndex () const inline
Referenced by castor3d::LoadingScreen::getIndex().
incRange()
void castor3d::ProgressBar::incRange (uint32_t mod) inline
References setRange().
Referenced by castor3d::LoadingScreen::incRange().
lock()
void castor3d::ProgressBar::lock () inline
setLabel()
C3D_API void castor3d::ProgressBar::setLabel (castor::String const & value)
setRange()
void castor3d::ProgressBar::setRange (uint32_t max) inline
Referenced by incRange(), and castor3d::LoadingScreen::setRange().
setTitle()
C3D_API void castor3d::ProgressBar::setTitle (castor::String const & value)
step() [1/2]
C3D_API void castor3d::ProgressBar::step ()
step() [2/2]
C3D_API void castor3d::ProgressBar::step (castor::String const & label)
Referenced by castor3d::LoadingScreen::step().
unlock()
void castor3d::ProgressBar::unlock () inline
The documentation for this class was generated from the following file:
Miscellaneous/ProgressBar.hpp