Castor3D: Castor3D::OneFrameVariable< T > Class Template Reference
Castor3D::OneFrameVariable< T > Class Template Reference
Single shader variable with variable type.
Public Member Functions
OneFrameVariable (ShaderProgram *p_program)
Constructor.
OneFrameVariable (ShaderProgram *p_program, uint32_t p_occurences)
Constructor.
OneFrameVariable (OneFrameVariable< T > const &p_object)
Copy constructor.
OneFrameVariable (OneFrameVariable< T > &&p_object)
Move constructor.
OneFrameVariable & operator= (OneFrameVariable< T > const &p_object)
Copy assignment operator.
OneFrameVariable & operator= (OneFrameVariable< T > &&p_object)
Move assignment operator.
virtual ~OneFrameVariable ()
Destructor.
T & GetValue ()
Retrieves the value.
T const & GetValue () const
Retrieves the value.
T & GetValue (uint32_t p_index)
Retrieves the value at given index.
T const & GetValue (uint32_t p_index) const
Retrieves the value at given index.
void SetValue (T const &p_value)
Defines the value of the variable.
void SetValue (T const &p_value, uint32_t p_index)
Defines the value of the variable.
void SetValues (T const *p_values, size_t p_size)
Defines the values of the variable.
template<size_t N>
void SetValues (T const (&p_values)[N])
Defines the values of the variable.
template<size_t N>
void SetValues (std::array< T, N > const &p_values)
Defines the values of the variable.
void SetValues (std::vector< T > const &p_values)
Defines the values of the variable.
virtual uint32_t size () const
Retrieves the byte size of the variable.
T & operator[] (uint32_t p_index)
Array subscript operator.
T const & operator[] (uint32_t p_index) const
Array subscript operator.
eVARIABLE_TYPE GetType () const
Retrieves the variable type.
eFRAME_VARIABLE_TYPE GetFullType () const
Retrieves the variable full type.
Castor::String GetFullTypeName () const
Gives the variable full type name.
Public Member Functions inherited from Castor3D::TFrameVariable< T >
TFrameVariable (ShaderProgram *p_program)
Constructor.
TFrameVariable (ShaderProgram *p_program, uint32_t p_occurences)
Constructor.
TFrameVariable (TFrameVariable< T > const &p_object)
Copy constructor.
TFrameVariable (TFrameVariable< T > &&p_object)
Move constructor.
TFrameVariable & operator= (TFrameVariable< T > const &p_object)
Copy assignment operator.
TFrameVariable & operator= (TFrameVariable< T > &&p_object)
Move assignment operator.
virtual ~TFrameVariable ()
Destructor.
Castor::String GetDataTypeName () const
Gives the variable data type.
virtual uint8_t const *const const_ptr () const
Retrieves a pointer to the variable data.
virtual void link (uint8_t *p_buffer)
Defines the buffer holding the frame variable.
Public Member Functions inherited from Castor3D::FrameVariable
C3D_API FrameVariable (ShaderProgram *p_program)
Constructor.
C3D_API FrameVariable (ShaderProgram *p_program, uint32_t p_occurences)
Constructor.
C3D_API FrameVariable (FrameVariable const &p_object)
Copy constructor.
C3D_API FrameVariable (FrameVariable &&p_object)
Move constructor.
C3D_API FrameVariable & operator= (FrameVariable const &p_object)
Copy assignment operator.
C3D_API FrameVariable & operator= (FrameVariable &&p_object)
Move assignment operator.
virtual C3D_API ~FrameVariable ()
Destructor.
virtual C3D_API bool Initialise ()=0
Initialises the variable.
virtual C3D_API void Cleanup ()=0
Cleans up the variable.
virtual C3D_API void Bind ()=0
Binds this variable to the shader.
virtual C3D_API void Unbind ()=0
Unbinds this variable from the shader.
virtual C3D_API void SetValueStr (Castor::String const &p_value)
Defines the value of the variable, from a string.
virtual C3D_API void SetValueStr (Castor::String const &p_value, uint32_t p_index)
Defines the value of the variable, from a string.
virtual void SetName (Castor::String const &p_name)
Defines the name of the variable, as it appears in the shader program.
Castor::String GetName () const
Gives the name of the variable, as it appears in the shader program.
Castor::String GetStrValue () const
Retrieves the variable string value.
Castor::String GetStrValue (uint32_t p_index) const
Retrieves the variable string value at given index.
const uint32_t & GetOccCount () const
Retrieves the occurences count.
ShaderProgram * GetProgram () const
Retrieves the parent program.
Static Public Member Functions
static eFRAME_VARIABLE_TYPE GetFrameVariableType ()
Gives the variable full type.
static Castor::String GetFrameVariableTypeName ()
Gives the variable full type.
static eVARIABLE_TYPE GetVariableType ()
Gives the full type of the variable.
Protected Types
typedef Castor::Policy< T > policy
Protected Types inherited from Castor3D::TFrameVariable< T >
typedef Castor::Policy< T > policy
Additional Inherited Members
Protected Member Functions inherited from Castor3D::TFrameVariable< T >
void DoCleanupBuffer ()
Protected Attributes inherited from Castor3D::TFrameVariable< T >
bool m_bOwnBuffer
Tells the variable owns it's buffer.
T * m_values
The buffer containing all values.
Protected Attributes inherited from Castor3D::FrameVariable
Castor::String m_name
The variable name as it appears in the shader program.
bool m_changed
Tells if the variable has changed since last execution of the shader.
uint32_t m_occurences
The array dimension if the variable represents an array.
Castor::StringArray m_strValue
The value of the variable.
ShaderProgram * m_program
The parent shader program.
Detailed Description
template<typename T>
class Castor3D::OneFrameVariable< T >
Single shader variable with variable type.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
14/08/2010
Member Typedef Documentation
policy
template<typename T> typedef Castor::Policy<T> Castor3D::OneFrameVariable< T >::policy protected
Constructor & Destructor Documentation
OneFrameVariable() [1/4]
template<typename T> Castor3D::OneFrameVariable< T >::OneFrameVariable (ShaderProgram * p_program)
Constructor.
Parameters
[in] p_program The program
OneFrameVariable() [2/4]
template<typename T> Castor3D::OneFrameVariable< T >::OneFrameVariable (ShaderProgram * p_program, uint32_t p_occurences)
Constructor.
Parameters
[in] p_program The program
[in] p_occurences The array dimension
OneFrameVariable() [3/4]
template<typename T> Castor3D::OneFrameVariable< T >::OneFrameVariable (OneFrameVariable< T > const & p_object)
Copy constructor.
Parameters
[in] p_object The object to copy
OneFrameVariable() [4/4]
template<typename T> Castor3D::OneFrameVariable< T >::OneFrameVariable (OneFrameVariable< T > && p_object)
Move constructor.
Parameters
[in] p_object The object to move
~OneFrameVariable()
template<typename T> virtual Castor3D::OneFrameVariable< T >::~OneFrameVariable () virtual
Destructor.
Member Function Documentation
GetFrameVariableType()
template<typename T> static eFRAME_VARIABLE_TYPE Castor3D::OneFrameVariable< T >::GetFrameVariableType () inline static
Gives the variable full type.
Returns
The type
Donne le type complet de la variable
Returns
Le type
Referenced by Castor3D::OneFrameVariable< T >::GetFullType().
GetFrameVariableTypeName()
template<typename T> static Castor::String Castor3D::OneFrameVariable< T >::GetFrameVariableTypeName () inline static
Gives the variable full type.
Returns
The type
Donne le type complet de la variable
Returns
Le type
Referenced by Castor3D::OneFrameVariable< T >::GetFullTypeName().
GetFullType()
template<typename T> eFRAME_VARIABLE_TYPE Castor3D::OneFrameVariable< T >::GetFullType () const inline virtual
Retrieves the variable full type.
Returns
The type
Implements Castor3D::FrameVariable.
References Castor3D::OneFrameVariable< T >::GetFrameVariableType().
GetFullTypeName()
template<typename T> Castor::String Castor3D::OneFrameVariable< T >::GetFullTypeName () const inline virtual
Gives the variable full type name.
Returns
The type
Donne le nom du type complet de la variable
Returns
Le type
Implements Castor3D::FrameVariable.
References Castor3D::OneFrameVariable< T >::GetFrameVariableTypeName().
GetType()
template<typename T> eVARIABLE_TYPE Castor3D::OneFrameVariable< T >::GetType () const inline virtual
Retrieves the variable type.
Returns
The variable type
Implements Castor3D::FrameVariable.
References Castor3D::OneFrameVariable< T >::GetVariableType().
GetValue() [1/4]
template<typename T> T& Castor3D::OneFrameVariable< T >::GetValue () inline
Retrieves the value.
Returns
A reference to the value
GetValue() [2/4]
template<typename T> T const& Castor3D::OneFrameVariable< T >::GetValue () const inline
Retrieves the value.
Returns
A constant reference to the value
GetValue() [3/4]
template<typename T> T& Castor3D::OneFrameVariable< T >::GetValue (uint32_t p_index) inline
Retrieves the value at given index.
Remarks
Check the index bounds
Parameters
[in] p_index The index
Returns
A reference to the value at given index
GetValue() [4/4]
template<typename T> T const& Castor3D::OneFrameVariable< T >::GetValue (uint32_t p_index) const inline
Retrieves the value at given index.
Remarks
Check the index bounds
Parameters
[in] p_index The index
Returns
A constant reference to the value at given index
GetVariableType()
template<typename T> static eVARIABLE_TYPE Castor3D::OneFrameVariable< T >::GetVariableType () inline static
Gives the full type of the variable.
Returns
The type of the variable
References Castor3D::eVARIABLE_TYPE_ONE.
Referenced by Castor3D::OneFrameVariable< T >::GetType().
operator=() [1/2]
template<typename T> OneFrameVariable& Castor3D::OneFrameVariable< T >::operator= (OneFrameVariable< T > const & p_object)
Copy assignment operator.
Parameters
[in] p_object The object to copy
Returns
A reference to this object
operator=() [2/2]
template<typename T> OneFrameVariable& Castor3D::OneFrameVariable< T >::operator= (OneFrameVariable< T > && p_object)
Move assignment operator.
Parameters
[in] p_object The object to move
Returns
A reference to this object
operator[]() [1/2]
template<typename T> T& Castor3D::OneFrameVariable< T >::operator[] (uint32_t p_index) inline
Array subscript operator.
Remarks
Doesn't check the index bounds
Parameters
[in] p_index The index
Returns
A reference to the value at given index
References Castor3D::TFrameVariable< T >::m_values.
operator[]() [2/2]
template<typename T> T const& Castor3D::OneFrameVariable< T >::operator[] (uint32_t p_index) const inline
Array subscript operator.
Remarks
Doesn't check the index bounds
Parameters
[in] p_index The index
Returns
A constant reference to the value at given index
References Castor3D::TFrameVariable< T >::m_values.
SetValue() [1/2]
template<typename T> void Castor3D::OneFrameVariable< T >::SetValue (T const & p_value) inline
Defines the value of the variable.
Parameters
[in] p_value The new value
SetValue() [2/2]
template<typename T> void Castor3D::OneFrameVariable< T >::SetValue (T const & p_value, uint32_t p_index) inline
Defines the value of the variable.
Parameters
[in] p_value The new value
[in] p_index The index of the value
SetValues() [1/4]
template<typename T> void Castor3D::OneFrameVariable< T >::SetValues (T const * p_values, size_t p_size) inline
Defines the values of the variable.
Parameters
[in] p_values The values buffer.
[in] p_size The values count.
Referenced by Castor3D::OneFrameVariable< T >::SetValues().
SetValues() [2/4]
template<typename T> template<size_t N> void Castor3D::OneFrameVariable< T >::SetValues (T const (&) p_values[N]) inline
Defines the values of the variable.
Parameters
[in] p_values The values buffer.
References Castor3D::OneFrameVariable< T >::SetValues().
SetValues() [3/4]
template<typename T> template<size_t N> void Castor3D::OneFrameVariable< T >::SetValues (std::array< T, N > const & p_values) inline
Defines the values of the variable.
Parameters
[in] p_values The values buffer.
References Castor3D::OneFrameVariable< T >::SetValues().
SetValues() [4/4]
template<typename T> void Castor3D::OneFrameVariable< T >::SetValues (std::vector< T > const & p_values) inline
Defines the values of the variable.
Parameters
[in] p_values The values buffer.
References Castor3D::OneFrameVariable< T >::SetValues().
size()
template<typename T> virtual uint32_t Castor3D::OneFrameVariable< T >::size () const virtual
Retrieves the byte size of the variable.
Returns
The size
Implements Castor3D::FrameVariable.
The documentation for this class was generated from the following files:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Castor3DPrerequisites_Shader.hpp
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/OneFrameVariable.hpp