Castor3D: castor::string::utf8 Namespace Reference
castor::string::utf8 Namespace Reference
Utf8 functions namespace.
Classes
class const_iterator
An iterator, to an UTF-8 string.
class iterator
An iterator, to an UTF-8 string.
Functions
template<typename IteratorType >
char32_t toUtf8 (IteratorType first, IteratorType end)
Retrieves an UTF-8 char32_t from a char array iterator.
template<typename CharT , typename StringT >
iterator< CharT, StringT > operator+ (iterator< CharT, StringT > it, size_t offset)
addition operator.
template<typename CharT , typename StringT >
iterator< CharT, StringT > operator- (iterator< CharT, StringT > it, size_t offset)
Subtraction operator.
template<typename CharT >
iterator< CharT, std::basic_string< CharT > > begin (std::basic_string< CharT > const &str)
template<typename CharT >
iterator< CharT, std::basic_string_view< CharT > > begin (std::basic_string_view< CharT > const &str)
template<typename CharT >
iterator< CharT, std::basic_string< CharT > > end (std::basic_string< CharT > const &str)
template<typename CharT >
iterator< CharT, std::basic_string_view< CharT > > end (std::basic_string_view< CharT > const &str)
template<typename CharT , typename StringT >
const_iterator< CharT, StringT > operator+ (const_iterator< CharT, StringT > it, size_t offset)
addition operator.
template<typename CharT , typename StringT >
const_iterator< CharT, StringT > operator- (const_iterator< CharT, StringT > it, size_t offset)
Subtraction operator.
template<typename CharT >
const_iterator< CharT, std::basic_string< CharT > > cbegin (std::basic_string< CharT > const &str)
template<typename CharT >
const_iterator< CharT, std::basic_string_view< CharT > > cbegin (std::basic_string_view< CharT > const &str)
template<typename CharT >
const_iterator< CharT, std::basic_string< CharT > > cend (std::basic_string< CharT > const &str)
template<typename CharT >
const_iterator< CharT, std::basic_string_view< CharT > > cend (std::basic_string_view< CharT > const &str)
Detailed Description
Utf8 functions namespace.
Function Documentation
begin() [1/2]
template<typename CharT > iterator< CharT, std::basic_string< CharT > > castor::string::utf8::begin (std::basic_string< CharT > const & str) inline
begin() [2/2]
template<typename CharT > iterator< CharT, std::basic_string_view< CharT > > castor::string::utf8::begin (std::basic_string_view< CharT > const & str) inline
cbegin() [1/2]
template<typename CharT > const_iterator< CharT, std::basic_string< CharT > > castor::string::utf8::cbegin (std::basic_string< CharT > const & str) inline
Referenced by cbegin().
cbegin() [2/2]
template<typename CharT > const_iterator< CharT, std::basic_string_view< CharT > > castor::string::utf8::cbegin (std::basic_string_view< CharT > const & str) inline
References cbegin().
cend() [1/2]
template<typename CharT > const_iterator< CharT, std::basic_string< CharT > > castor::string::utf8::cend (std::basic_string< CharT > const & str) inline
References cend().
Referenced by cend(), and cend().
cend() [2/2]
template<typename CharT > const_iterator< CharT, std::basic_string_view< CharT > > castor::string::utf8::cend (std::basic_string_view< CharT > const & str) inline
References cend().
end() [1/2]
template<typename CharT > iterator< CharT, std::basic_string< CharT > > castor::string::utf8::end (std::basic_string< CharT > const & str) inline
end() [2/2]
template<typename CharT > iterator< CharT, std::basic_string_view< CharT > > castor::string::utf8::end (std::basic_string_view< CharT > const & str) inline
operator+() [1/2]
template<typename CharT , typename StringT > const_iterator< CharT, StringT > castor::string::utf8::operator+ (const_iterator< CharT, StringT > it, size_t offset) inline
addition operator.
Parameters
[in] it The iterator.
[in] offset The offset to add.
Returns
A reference to this object.
operator+() [2/2]
template<typename CharT , typename StringT > iterator< CharT, StringT > castor::string::utf8::operator+ (iterator< CharT, StringT > it, size_t offset) inline
addition operator.
Parameters
[in] it The iterator.
[in] offset The offset to add.
Returns
A reference to this object.
operator-() [1/2]
template<typename CharT , typename StringT > const_iterator< CharT, StringT > castor::string::utf8::operator- (const_iterator< CharT, StringT > it, size_t offset) inline
Subtraction operator.
Parameters
[in] it The iterator.
[in] offset The offset to subtract.
Returns
A reference to this object.
operator-() [2/2]
template<typename CharT , typename StringT > iterator< CharT, StringT > castor::string::utf8::operator- (iterator< CharT, StringT > it, size_t offset) inline
Subtraction operator.
Parameters
[in] it The iterator.
[in] offset The offset to subtract.
Returns
A reference to this object.
toUtf8()
template<typename IteratorType > char32_t castor::string::utf8::toUtf8 (IteratorType first, IteratorType end) inline
Retrieves an UTF-8 char32_t from a char array iterator.
Parameters
[in] first The char iterator.
[in] end The end iterator.
Returns
The UTF-8 char32_t character.