Castor3D: castor3d::BonesComponent Class Reference
castor3d::BonesComponent Class Reference
#include <BonesComponent.hpp>
Public Member Functions
C3D_API BonesComponent (Submesh &submesh)
Constructor.
C3D_API void addBoneDatas (VertexBoneData const *const begin, VertexBoneData const *const end)
adds bone datas.
C3D_API SkeletonSPtr getSkeleton () const
C3D_API void gather (ShaderFlags const &shaderFlags, ProgramFlags const &programFlags, MaterialRPtr material, ashes::BufferCRefArray &buffers, std::vector< uint64_t > &offsets, ashes::PipelineVertexInputStateCreateInfoCRefArray &layouts, TextureFlagsArray const &mask, uint32_t &currentLocation) override
Gathers buffers that need to go in a vertex layout.
C3D_API SubmeshComponentSPtr clone (Submesh &submesh) const override
C3D_API void addBoneDatas (std::vector< VertexBoneData > const &boneData)
adds bone datas.
template<size_t Count>
void addBoneDatas (std::array< VertexBoneData, Count > const &boneData)
adds bone datas.
ProgramFlags getProgramFlags (MaterialRPtr material) const override
bool hasBoneData () const
VertexBoneDataArray const & getBonesData () const
Public Member Functions inherited from castor3d::SubmeshComponent
C3D_API SubmeshComponent (Submesh &submesh, castor::String const &type, uint32_t id)
Constructor.
virtual C3D_API ~SubmeshComponent () noexcept=default
Destructor.
C3D_API bool initialise (RenderDevice const &device)
Initialises the submesh.
C3D_API void cleanup (RenderDevice const &device)
Cleans the submesh.
C3D_API void upload ()
Uploads data on VRAM.
virtual C3D_API void gather (ShaderFlags const &shaderFlags, ProgramFlags const &programFlags, MaterialRPtr material, ashes::BufferCRefArray &buffers, std::vector< uint64_t > &offsets, ashes::PipelineVertexInputStateCreateInfoCRefArray &layouts, TextureFlagsArray const &mask, uint32_t &currentLocation)=0
Gathers buffers that need to go in a vertex layout.
virtual C3D_API ProgramFlags getProgramFlags (MaterialRPtr material) const =0
virtual C3D_API VkBufferUsageFlags getUsageFlags () const
virtual C3D_API SubmeshComponentSPtr clone (Submesh &submesh) const =0
castor::String const & getType () const
void needsUpdate ()
Sets the component to be updated.
uint32_t getID ()
Static Public Attributes
static C3D_API castor::String const Name
static C3D_API uint32_t constexpr BindingPoint = 3u
Friends
class BinaryWriter< BonesComponent >
class BinaryParser< BonesComponent >
Constructor & Destructor Documentation
BonesComponent()
C3D_API castor3d::BonesComponent::BonesComponent (Submesh & submesh) explicit
Constructor.
Parameters
[in] submesh The parent submesh.
Member Function Documentation
addBoneDatas() [1/3]
template<size_t Count> void castor3d::BonesComponent::addBoneDatas (std::array< VertexBoneData, Count > const & boneData) inline
adds bone datas.
Parameters
[in] boneData The bone datas.
References addBoneDatas().
addBoneDatas() [2/3]
C3D_API void castor3d::BonesComponent::addBoneDatas (std::vector< VertexBoneData > const & boneData)
adds bone datas.
Parameters
[in] boneData The bone datas.
addBoneDatas() [3/3]
C3D_API void castor3d::BonesComponent::addBoneDatas (VertexBoneData const *const begin, VertexBoneData const *const end)
adds bone datas.
Parameters
[in] begin The bones data begin.
[in] end The bones data end.
Referenced by addBoneDatas().
clone()
C3D_API SubmeshComponentSPtr castor3d::BonesComponent::clone (Submesh & submesh) const override virtual
Returns
Clones this component into given submesh.
Parameters
[in,out] submesh Receives the cloned component.
Implements castor3d::SubmeshComponent.
gather()
C3D_API void castor3d::BonesComponent::gather (ShaderFlags const & shaderFlags, ProgramFlags const & programFlags, MaterialRPtr material, ashes::BufferCRefArray & buffers, std::vector< uint64_t > & offsets, ashes::PipelineVertexInputStateCreateInfoCRefArray & layouts, TextureFlagsArray const & mask, uint32_t & currentLocation) override virtual
Gathers buffers that need to go in a vertex layout.
Parameters
[in] shaderFlags The shader flags.
[in] programFlags The program flags.
[in] material The material.
[in,out] buffers Receives the buffers.
[in,out] offsets Receives the buffers offsets.
[in,out] layouts Receives the vertex layouts.
[in] mask The textures mask.
[in,out] currentLocation The current attribute location.
Implements castor3d::SubmeshComponent.
getBonesData()
VertexBoneDataArray const & castor3d::BonesComponent::getBonesData () const inline
getProgramFlags()
ProgramFlags castor3d::BonesComponent::getProgramFlags (MaterialRPtr material) const inline override virtual
Returns
The shader program flags.
Parameters
[in] material The material.
Implements castor3d::SubmeshComponent.
References castor3d::eSkinning, and hasBoneData().
getSkeleton()
C3D_API SkeletonSPtr castor3d::BonesComponent::getSkeleton () const
Returns
The skeleton.
hasBoneData()
bool castor3d::BonesComponent::hasBoneData () const inline
Referenced by getProgramFlags().
Friends And Related Function Documentation
BinaryParser< BonesComponent >
friend class BinaryParser< BonesComponent > friend
BinaryWriter< BonesComponent >
friend class BinaryWriter< BonesComponent > friend
Member Data Documentation
BindingPoint
C3D_API uint32_t constexpr castor3d::BonesComponent::BindingPoint = 3u static constexpr
Name
C3D_API castor::String const castor3d::BonesComponent::Name static
The documentation for this class was generated from the following file:
Model/Mesh/Submesh/Component/BonesComponent.hpp