Castor3D: castor3d::RenderPipeline Class Reference
castor3d::RenderPipeline Class Reference abstract
The rendering pipeline.
Public Member Functions
C3D_API RenderPipeline (RenderSystem &renderSystem, DepthStencilState &&dsState, RasteriserState &&rsState, BlendState &&blState, MultisampleState &&msState, ShaderProgram &program, PipelineFlags const &flags)
Constructor.
virtual C3D_API ~RenderPipeline ()
Denstructor.
C3D_API void cleanup ()
Cleans up the pipeline.
virtual C3D_API void apply () const =0
Applies the pipeline.
C3D_API void addUniformBuffer (UniformBuffer &ubo)
adds a uniform buffer to the pipeline.
C3D_API GeometryBuffersSPtr getGeometryBuffers (Submesh &submesh)
Retrieves a GeometryBuffers for given submesh.
C3D_API GeometryBuffersSPtr getGeometryBuffers (BillboardBase &billboard)
Retrieves a GeometryBuffers for given billboard.
ShaderProgram const & getProgram () const
ShaderProgram & getProgram ()
BindingArray const & getBindings () const
PipelineFlags const & getFlags () const
uint32_t getTexturesCount ()
PushUniform1s & getDirectionalShadowMapsVariable ()
PushUniform1s & getSpotShadowMapsVariable ()
PushUniform1s & getPointShadowMapsVariable ()
PushUniform1s & getEnvironmentMapVariable ()
PushUniform1s & getIrradianceMapVariable ()
PushUniform1s & getPrefilteredMapVariable ()
PushUniform1s & getBrdfMapVariable ()
Static Public Attributes
static C3D_API const castor::String MtxTexture [C3D_MAX_TEXTURE_MATRICES]
Protected Attributes
DepthStencilState m_dsState
RasteriserState m_rsState
BlendState m_blState
MultisampleState m_msState
ShaderProgram & m_program
PushUniform1sSPtr m_directionalShadowMaps
PushUniform1sSPtr m_spotShadowMaps
PushUniform1sSPtr m_pointShadowMaps
PushUniform1sSPtr m_environmentMap
PushUniform1sSPtr m_irradianceMap
PushUniform1sSPtr m_prefilteredMap
PushUniform1sSPtr m_brdfMap
PipelineFlags m_flags
uint32_t m_textureCount { 0u }
BindingArray m_bindings
std::unordered_map< Submesh *, GeometryBuffersSPtr > m_meshGeometryBuffers
std::unordered_map< BillboardBase *, GeometryBuffersSPtr > m_billboardGeometryBuffers
Detailed Description
The rendering pipeline.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
03/01/2011
Remarks
Defines the various matrices, applies the transformations it can support.
Constructor & Destructor Documentation
RenderPipeline()
C3D_API castor3d::RenderPipeline::RenderPipeline (RenderSystem & renderSystem, DepthStencilState && dsState, RasteriserState && rsState, BlendState && blState, MultisampleState && msState, ShaderProgram & program, PipelineFlags const & flags) explicit
Constructor.
Parameters
[in] renderSystem The parent RenderSystem.
[in] dsState The depth stencil state.
[in] rsState The rateriser state.
[in] blState The blend state.
[in] msState The multisample state.
[in] program The shader program.
[in] flags The creation flags.
~RenderPipeline()
virtual C3D_API castor3d::RenderPipeline::~RenderPipeline () virtual
Denstructor.
Member Function Documentation
addUniformBuffer()
C3D_API void castor3d::RenderPipeline::addUniformBuffer (UniformBuffer & ubo)
adds a uniform buffer to the pipeline.
Remarks
Creates the binding for this uniform buffer, using the pipeline's program.
apply()
virtual C3D_API void castor3d::RenderPipeline::apply () const pure virtual
Applies the pipeline.
cleanup()
C3D_API void castor3d::RenderPipeline::cleanup ()
Cleans up the pipeline.
getBindings()
BindingArray const& castor3d::RenderPipeline::getBindings () const inline
Returns
The uniform buffer bindings.
References m_bindings.
getBrdfMapVariable()
PushUniform1s& castor3d::RenderPipeline::getBrdfMapVariable () inline
Returns
The BRDF map frame variable.
References m_brdfMap.
Referenced by castor3d::doFillShaderPbrMaps().
getDirectionalShadowMapsVariable()
PushUniform1s& castor3d::RenderPipeline::getDirectionalShadowMapsVariable () inline
Returns
The directional lights shadow maps frame variable.
References m_directionalShadowMaps.
Referenced by castor3d::doFillShaderShadowMaps().
getEnvironmentMapVariable()
PushUniform1s& castor3d::RenderPipeline::getEnvironmentMapVariable () inline
Returns
The reflection map frame variable.
References m_environmentMap.
Referenced by castor3d::doBindPass().
getFlags()
PipelineFlags const& castor3d::RenderPipeline::getFlags () const inline
Returns
The creation flags.
References m_flags.
Referenced by castor3d::doBindPass(), castor3d::doFillShaderShadowMaps(), and castor3d::doRenderNodeNoPass().
getGeometryBuffers() [1/2]
C3D_API GeometryBuffersSPtr castor3d::RenderPipeline::getGeometryBuffers (Submesh & submesh)
Retrieves a GeometryBuffers for given submesh.
Parameters
[in] submesh The submesh.
getGeometryBuffers() [2/2]
C3D_API GeometryBuffersSPtr castor3d::RenderPipeline::getGeometryBuffers (BillboardBase & billboard)
Retrieves a GeometryBuffers for given billboard.
Parameters
[in] billboard The billboard.
getIrradianceMapVariable()
PushUniform1s& castor3d::RenderPipeline::getIrradianceMapVariable () inline
Returns
The irradiance map frame variable.
References m_irradianceMap.
Referenced by castor3d::doFillShaderPbrMaps().
getPointShadowMapsVariable()
PushUniform1s& castor3d::RenderPipeline::getPointShadowMapsVariable () inline
Returns
The point lights shadow maps frame variable.
References m_pointShadowMaps.
Referenced by castor3d::doFillShaderShadowMaps().
getPrefilteredMapVariable()
PushUniform1s& castor3d::RenderPipeline::getPrefilteredMapVariable () inline
Returns
The irradiance map frame variable.
References m_prefilteredMap.
Referenced by castor3d::doFillShaderPbrMaps().
getProgram() [1/2]
ShaderProgram const& castor3d::RenderPipeline::getProgram () const inline
Returns
The shader program.
References m_program.
getProgram() [2/2]
ShaderProgram& castor3d::RenderPipeline::getProgram () inline
Returns
The shader program.
References m_program.
getSpotShadowMapsVariable()
PushUniform1s& castor3d::RenderPipeline::getSpotShadowMapsVariable () inline
Returns
The spot lights shadow maps frame variable.
References m_spotShadowMaps.
Referenced by castor3d::doFillShaderShadowMaps().
getTexturesCount()
uint32_t castor3d::RenderPipeline::getTexturesCount () inline
Returns
The count of textures used by the program.
References m_textureCount.
Referenced by castor3d::doBindPass().
Member Data Documentation
m_billboardGeometryBuffers
std::unordered_map< BillboardBase *, GeometryBuffersSPtr > castor3d::RenderPipeline::m_billboardGeometryBuffers protected
The GeometryBuffers used with this pipeline.
m_bindings
BindingArray castor3d::RenderPipeline::m_bindings protected
The uniform buffer bindings.
Referenced by getBindings().
m_blState
BlendState castor3d::RenderPipeline::m_blState protected
The blend state.
m_brdfMap
PushUniform1sSPtr castor3d::RenderPipeline::m_brdfMap protected
The BRDF map frame variable.
Referenced by getBrdfMapVariable().
m_directionalShadowMaps
PushUniform1sSPtr castor3d::RenderPipeline::m_directionalShadowMaps protected
The directional lights shadow maps frame variable.
Referenced by getDirectionalShadowMapsVariable().
m_dsState
DepthStencilState castor3d::RenderPipeline::m_dsState protected
The depth stencil state.
m_environmentMap
PushUniform1sSPtr castor3d::RenderPipeline::m_environmentMap protected
The environment map frame variable.
Referenced by getEnvironmentMapVariable().
m_flags
PipelineFlags castor3d::RenderPipeline::m_flags protected
The creation flags.
Referenced by getFlags().
m_irradianceMap
PushUniform1sSPtr castor3d::RenderPipeline::m_irradianceMap protected
The irradiance map frame variable.
Referenced by getIrradianceMapVariable().
m_meshGeometryBuffers
std::unordered_map< Submesh *, GeometryBuffersSPtr > castor3d::RenderPipeline::m_meshGeometryBuffers protected
The GeometryBuffers used with this pipeline.
m_msState
MultisampleState castor3d::RenderPipeline::m_msState protected
The muultisampling state.
m_pointShadowMaps
PushUniform1sSPtr castor3d::RenderPipeline::m_pointShadowMaps protected
The point lights shadow maps frame variable.
Referenced by getPointShadowMapsVariable().
m_prefilteredMap
PushUniform1sSPtr castor3d::RenderPipeline::m_prefilteredMap protected
The prefiltered environment map frame variable.
Referenced by getPrefilteredMapVariable().
m_program
ShaderProgram& castor3d::RenderPipeline::m_program protected
The shader program.
Referenced by getProgram().
m_rsState
RasteriserState castor3d::RenderPipeline::m_rsState protected
The rateriser state.
m_spotShadowMaps
PushUniform1sSPtr castor3d::RenderPipeline::m_spotShadowMaps protected
The spot lights shadow maps frame variable.
Referenced by getSpotShadowMapsVariable().
m_textureCount
uint32_t castor3d::RenderPipeline::m_textureCount { 0u } protected
The count of textures used by the program.
Referenced by getTexturesCount().
MtxTexture
C3D_API const castor::String castor3d::RenderPipeline::MtxTexture[C3D_MAX_TEXTURE_MATRICES] static
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Render/RenderPipeline.hpp