Castor3D: castor3d::GpuBufferOffsetT< DataT > Struct Template Reference
castor3d::GpuBufferOffsetT< DataT > Struct Template Reference
An offset and range of a GpuBuffer.
#include <GpuBufferOffset.hpp>
Public Member Functions
GpuBufferOffsetT () noexcept=default
void setPool (GpuBufferBase &pool)
operator bool () const
GpuBufferBase const & getPool () const
GpuBufferBase & getPool ()
ashes::Buffer< uint8_t > const & getBuffer () const
ashes::Buffer< uint8_t > & getBuffer ()
VkDeviceSize getCount () const
VkDeviceSize getSize () const
VkDeviceSize getOffset () const
castor::ArrayView< DataT > getData ()
void markDirty (VkAccessFlags dstAccessFlags, VkPipelineStageFlags dstPipelineFlags) const
void markDirty (VkDeviceSize size, VkAccessFlags dstAccessFlags, VkPipelineStageFlags dstPipelineFlags) const
VkDescriptorSetLayoutBinding createLayoutBinding (uint32_t index, VkShaderStageFlags stages) const
void createUniformPassBinding (crg::FramePass &pass, uint32_t binding, castor::String const &name) const
void createInputStoragePassBinding (crg::FramePass &pass, uint32_t binding, castor::String const &name) const
void createInOutStoragePassBinding (crg::FramePass &pass, uint32_t binding, castor::String const &name) const
void createOutputStoragePassBinding (crg::FramePass &pass, uint32_t binding, castor::String const &name) const
void createClearableOutputStorageBinding (crg::FramePass &pass, uint32_t binding, castor::String const &name) const
ashes::WriteDescriptorSet getUniformBinding (uint32_t binding) const
ashes::WriteDescriptorSet getStorageBinding (uint32_t binding) const
void createBinding (ashes::DescriptorSet &descriptorSet, VkDescriptorSetLayoutBinding const &binding) const
Public Attributes
GpuBufferBase * buffer {}
VkBufferUsageFlags target {}
VkMemoryPropertyFlags memory {}
MemChunk chunk {}
Detailed Description
template<typename DataT>
struct castor3d::GpuBufferOffsetT< DataT >
An offset and range of a GpuBuffer.
Constructor & Destructor Documentation
GpuBufferOffsetT()
template<typename DataT > castor3d::GpuBufferOffsetT< DataT >::GpuBufferOffsetT () default noexcept
Member Function Documentation
createBinding()
template<typename DataT > void castor3d::GpuBufferOffsetT< DataT >::createBinding (ashes::DescriptorSet & descriptorSet, VkDescriptorSetLayoutBinding const & binding) const inline
References castor3d::GpuBufferOffsetT< DataT >::getBuffer(), castor3d::GpuBufferOffsetT< DataT >::getOffset(), and castor3d::GpuBufferOffsetT< DataT >::getSize().
createClearableOutputStorageBinding()
template<typename DataT > void castor3d::GpuBufferOffsetT< DataT >::createClearableOutputStorageBinding (crg::FramePass & pass, uint32_t binding, castor::String const & name) const inline
References castor3d::createClearableOutputStorageBinding(), castor3d::GpuBufferOffsetT< DataT >::getBuffer(), castor3d::GpuBufferOffsetT< DataT >::getOffset(), and castor3d::GpuBufferOffsetT< DataT >::getSize().
createInOutStoragePassBinding()
template<typename DataT > void castor3d::GpuBufferOffsetT< DataT >::createInOutStoragePassBinding (crg::FramePass & pass, uint32_t binding, castor::String const & name) const inline
References castor3d::createInOutStoragePassBinding(), castor3d::GpuBufferOffsetT< DataT >::getBuffer(), castor3d::GpuBufferOffsetT< DataT >::getOffset(), and castor3d::GpuBufferOffsetT< DataT >::getSize().
createInputStoragePassBinding()
template<typename DataT > void castor3d::GpuBufferOffsetT< DataT >::createInputStoragePassBinding (crg::FramePass & pass, uint32_t binding, castor::String const & name) const inline
References castor3d::createInputStoragePassBinding(), castor3d::GpuBufferOffsetT< DataT >::getBuffer(), castor3d::GpuBufferOffsetT< DataT >::getOffset(), and castor3d::GpuBufferOffsetT< DataT >::getSize().
createLayoutBinding()
template<typename DataT > VkDescriptorSetLayoutBinding castor3d::GpuBufferOffsetT< DataT >::createLayoutBinding (uint32_t index, VkShaderStageFlags stages) const inline
References castor3d::makeDescriptorSetLayoutBinding().
createOutputStoragePassBinding()
template<typename DataT > void castor3d::GpuBufferOffsetT< DataT >::createOutputStoragePassBinding (crg::FramePass & pass, uint32_t binding, castor::String const & name) const inline
References castor3d::createOutputStoragePassBinding(), castor3d::GpuBufferOffsetT< DataT >::getBuffer(), castor3d::GpuBufferOffsetT< DataT >::getOffset(), and castor3d::GpuBufferOffsetT< DataT >::getSize().
createUniformPassBinding()
template<typename DataT > void castor3d::GpuBufferOffsetT< DataT >::createUniformPassBinding (crg::FramePass & pass, uint32_t binding, castor::String const & name) const inline
References castor3d::createUniformPassBinding(), castor3d::GpuBufferOffsetT< DataT >::getBuffer(), castor3d::GpuBufferOffsetT< DataT >::getOffset(), and castor3d::GpuBufferOffsetT< DataT >::getSize().
getBuffer() [1/2]
template<typename DataT > ashes::Buffer< uint8_t > & castor3d::GpuBufferOffsetT< DataT >::getBuffer () inline
References castor3d::GpuBufferOffsetT< DataT >::buffer, and castor3d::GpuBufferBase::getBuffer().
getBuffer() [2/2]
template<typename DataT > ashes::Buffer< uint8_t > const & castor3d::GpuBufferOffsetT< DataT >::getBuffer () const inline
References castor3d::GpuBufferOffsetT< DataT >::buffer, and castor3d::GpuBufferBase::getBuffer().
Referenced by castor3d::GpuBufferOffsetT< DataT >::createBinding(), castor3d::GpuBufferOffsetT< DataT >::createClearableOutputStorageBinding(), castor3d::GpuBufferOffsetT< DataT >::createInOutStoragePassBinding(), castor3d::GpuBufferOffsetT< DataT >::createInputStoragePassBinding(), castor3d::GpuBufferOffsetT< DataT >::createOutputStoragePassBinding(), castor3d::GpuBufferOffsetT< DataT >::createUniformPassBinding(), castor3d::GpuBufferOffsetT< DataT >::getStorageBinding(), and castor3d::GpuBufferOffsetT< DataT >::getUniformBinding().
getCount()
template<typename DataT > VkDeviceSize castor3d::GpuBufferOffsetT< DataT >::getCount () const inline
References castor3d::MemChunk::askedSize, and castor3d::GpuBufferOffsetT< DataT >::chunk.
Referenced by castor3d::GpuBufferOffsetT< DataT >::getData().
getData()
template<typename DataT > castor::ArrayView< DataT > castor3d::GpuBufferOffsetT< DataT >::getData () inline
References castor3d::GpuBufferOffsetT< DataT >::buffer, castor3d::GpuBufferOffsetT< DataT >::getCount(), castor3d::GpuBufferBase::getDatas(), castor3d::GpuBufferOffsetT< DataT >::getOffset(), and castor::makeArrayView().
getOffset()
template<typename DataT > VkDeviceSize castor3d::GpuBufferOffsetT< DataT >::getOffset () const inline
References castor3d::GpuBufferOffsetT< DataT >::chunk, and castor3d::MemChunk::offset.
Referenced by castor3d::GpuBufferOffsetT< DataT >::createBinding(), castor3d::GpuBufferOffsetT< DataT >::createClearableOutputStorageBinding(), castor3d::GpuBufferOffsetT< DataT >::createInOutStoragePassBinding(), castor3d::GpuBufferOffsetT< DataT >::createInputStoragePassBinding(), castor3d::GpuBufferOffsetT< DataT >::createOutputStoragePassBinding(), castor3d::GpuBufferOffsetT< DataT >::createUniformPassBinding(), castor3d::GpuBufferOffsetT< DataT >::getData(), castor3d::GpuBufferOffsetT< DataT >::getStorageBinding(), castor3d::GpuBufferOffsetT< DataT >::getUniformBinding(), and castor3d::GpuBufferOffsetT< DataT >::markDirty().
getPool() [1/2]
template<typename DataT > GpuBufferBase & castor3d::GpuBufferOffsetT< DataT >::getPool () inline
References castor3d::GpuBufferOffsetT< DataT >::buffer.
getPool() [2/2]
template<typename DataT > GpuBufferBase const & castor3d::GpuBufferOffsetT< DataT >::getPool () const inline
References castor3d::GpuBufferOffsetT< DataT >::buffer.
getSize()
template<typename DataT > VkDeviceSize castor3d::GpuBufferOffsetT< DataT >::getSize () const inline
References castor3d::GpuBufferOffsetT< DataT >::chunk, and castor3d::MemChunk::size.
Referenced by castor3d::GpuBufferOffsetT< DataT >::createBinding(), castor3d::GpuBufferOffsetT< DataT >::createClearableOutputStorageBinding(), castor3d::GpuBufferOffsetT< DataT >::createInOutStoragePassBinding(), castor3d::GpuBufferOffsetT< DataT >::createInputStoragePassBinding(), castor3d::GpuBufferOffsetT< DataT >::createOutputStoragePassBinding(), castor3d::GpuBufferOffsetT< DataT >::createUniformPassBinding(), castor3d::GpuBufferOffsetT< DataT >::getStorageBinding(), castor3d::GpuBufferOffsetT< DataT >::getUniformBinding(), castor3d::GpuBufferOffsetT< DataT >::markDirty(), and castor3d::GpuBufferOffsetT< DataT >::markDirty().
getStorageBinding()
template<typename DataT > ashes::WriteDescriptorSet castor3d::GpuBufferOffsetT< DataT >::getStorageBinding (uint32_t binding) const inline
References castor3d::GpuBufferOffsetT< DataT >::getBuffer(), castor3d::GpuBufferOffsetT< DataT >::getOffset(), and castor3d::GpuBufferOffsetT< DataT >::getSize().
getUniformBinding()
template<typename DataT > ashes::WriteDescriptorSet castor3d::GpuBufferOffsetT< DataT >::getUniformBinding (uint32_t binding) const inline
References castor3d::GpuBufferOffsetT< DataT >::getBuffer(), castor3d::GpuBufferOffsetT< DataT >::getOffset(), and castor3d::GpuBufferOffsetT< DataT >::getSize().
markDirty() [1/2]
template<typename DataT > void castor3d::GpuBufferOffsetT< DataT >::markDirty (VkAccessFlags dstAccessFlags, VkPipelineStageFlags dstPipelineFlags) const inline
References castor3d::GpuBufferOffsetT< DataT >::getSize(), and castor3d::GpuBufferOffsetT< DataT >::markDirty().
Referenced by castor3d::GpuBufferOffsetT< DataT >::markDirty().
markDirty() [2/2]
template<typename DataT > void castor3d::GpuBufferOffsetT< DataT >::markDirty (VkDeviceSize size, VkAccessFlags dstAccessFlags, VkPipelineStageFlags dstPipelineFlags) const inline
References castor3d::GpuBufferOffsetT< DataT >::buffer, castor3d::GpuBufferOffsetT< DataT >::getOffset(), castor3d::GpuBufferOffsetT< DataT >::getSize(), and castor3d::GpuBufferBase::markDirty().
operator bool()
template<typename DataT > castor3d::GpuBufferOffsetT< DataT >::operator bool () const inline explicit
References castor3d::GpuBufferOffsetT< DataT >::buffer, and castor3d::GpuBufferBase::hasBuffer().
setPool()
template<typename DataT > void castor3d::GpuBufferOffsetT< DataT >::setPool (GpuBufferBase & pool) inline
References castor3d::GpuBufferOffsetT< DataT >::buffer.
Member Data Documentation
buffer
template<typename DataT > GpuBufferBase* castor3d::GpuBufferOffsetT< DataT >::buffer {}
Referenced by castor3d::GpuBufferOffsetT< DataT >::getBuffer(), castor3d::GpuBufferOffsetT< DataT >::getBuffer(), castor3d::GpuBufferOffsetT< DataT >::getData(), castor3d::GpuBufferOffsetT< DataT >::getPool(), castor3d::GpuBufferOffsetT< DataT >::getPool(), castor3d::GpuBufferOffsetT< DataT >::markDirty(), castor3d::GpuBufferOffsetT< DataT >::operator bool(), and castor3d::GpuBufferOffsetT< DataT >::setPool().
chunk
template<typename DataT > MemChunk castor3d::GpuBufferOffsetT< DataT >::chunk {}
Referenced by castor3d::GpuBufferOffsetT< DataT >::getCount(), castor3d::GpuBufferOffsetT< DataT >::getOffset(), and castor3d::GpuBufferOffsetT< DataT >::getSize().
memory
template<typename DataT > VkMemoryPropertyFlags castor3d::GpuBufferOffsetT< DataT >::memory {}
target
template<typename DataT > VkBufferUsageFlags castor3d::GpuBufferOffsetT< DataT >::target {}
The documentation for this struct was generated from the following files:
Castor3D/Buffer/BufferModule.hpp
Castor3D/Buffer/GpuBufferOffset.hpp