Castor3D: castor3d::LpvGridConfigUbo Class Reference
castor3d::LpvGridConfigUbo Class Reference
#include <LpvGridConfigUbo.hpp>
Public Types
using Configuration = LpvGridConfigUboConfiguration
Public Member Functions
C3D_API LpvGridConfigUbo (LpvGridConfigUbo const &rhs)=delete
C3D_API LpvGridConfigUbo & operator= (LpvGridConfigUbo const &rhs)=delete
C3D_API LpvGridConfigUbo (LpvGridConfigUbo &&rhs)=default
C3D_API LpvGridConfigUbo & operator= (LpvGridConfigUbo &&rhs)=delete
C3D_API LpvGridConfigUbo (RenderDevice const &device)
C3D_API ~LpvGridConfigUbo ()
C3D_API castor::Grid const & cpuUpdate (castor::BoundingBox const &aabb, castor::Point3f const &cameraPos, castor::Point3f const &cameraDir, uint32_t gridDim, float indirectAttenuation)
C3D_API castor::Grid const & cpuUpdate (uint32_t gridLevel, float gridLevelScale, castor::Grid const &grid, castor::BoundingBox const &aabb, castor::Point3f const &cameraPos, castor::Point3f const &cameraDir, float indirectAttenuation)
UniformBufferOffsetT< Configuration > & getUbo ()
UniformBufferOffsetT< Configuration > const & getUbo () const
void createPassBinding (crg::FramePass &pass, uint32_t binding) const
void createSizedBinding (ashes::DescriptorSet &descriptorSet, VkDescriptorSetLayoutBinding const &layoutBinding) const
ashes::WriteDescriptorSet getDescriptorWrite (uint32_t dstBinding, uint32_t dstArrayElement=0u) const
Static Public Attributes
static C3D_API const std::string LpvGridConfig
static C3D_API const std::string LpvGridData
Member Typedef Documentation
Configuration
using castor3d::LpvGridConfigUbo::Configuration = LpvGridConfigUboConfiguration
Constructor & Destructor Documentation
LpvGridConfigUbo() [1/3]
C3D_API castor3d::LpvGridConfigUbo::LpvGridConfigUbo (LpvGridConfigUbo const & rhs) delete
LpvGridConfigUbo() [2/3]
C3D_API castor3d::LpvGridConfigUbo::LpvGridConfigUbo (LpvGridConfigUbo && rhs) default
LpvGridConfigUbo() [3/3]
C3D_API castor3d::LpvGridConfigUbo::LpvGridConfigUbo (RenderDevice const & device) explicit
~LpvGridConfigUbo()
C3D_API castor3d::LpvGridConfigUbo::~LpvGridConfigUbo ()
Member Function Documentation
cpuUpdate() [1/2]
C3D_API castor::Grid const & castor3d::LpvGridConfigUbo::cpuUpdate (castor::BoundingBox const & aabb, castor::Point3f const & cameraPos, castor::Point3f const & cameraDir, uint32_t gridDim, float indirectAttenuation)
cpuUpdate() [2/2]
C3D_API castor::Grid const & castor3d::LpvGridConfigUbo::cpuUpdate (uint32_t gridLevel, float gridLevelScale, castor::Grid const & grid, castor::BoundingBox const & aabb, castor::Point3f const & cameraPos, castor::Point3f const & cameraDir, float indirectAttenuation)
createPassBinding()
void castor3d::LpvGridConfigUbo::createPassBinding (crg::FramePass & pass, uint32_t binding) const inline
References castor3d::UniformBufferOffsetT< DataT >::createPassBinding().
createSizedBinding()
void castor3d::LpvGridConfigUbo::createSizedBinding (ashes::DescriptorSet & descriptorSet, VkDescriptorSetLayoutBinding const & layoutBinding) const inline
References castor3d::UniformBufferOffsetT< DataT >::createSizedBinding().
getDescriptorWrite()
ashes::WriteDescriptorSet castor3d::LpvGridConfigUbo::getDescriptorWrite (uint32_t dstBinding, uint32_t dstArrayElement = 0u) const inline
References castor3d::UniformBufferOffsetT< DataT >::getDescriptorWrite().
getUbo() [1/2]
UniformBufferOffsetT< Configuration > & castor3d::LpvGridConfigUbo::getUbo () inline
getUbo() [2/2]
UniformBufferOffsetT< Configuration > const & castor3d::LpvGridConfigUbo::getUbo () const inline
operator=() [1/2]
C3D_API LpvGridConfigUbo & castor3d::LpvGridConfigUbo::operator= (LpvGridConfigUbo && rhs) delete
operator=() [2/2]
C3D_API LpvGridConfigUbo & castor3d::LpvGridConfigUbo::operator= (LpvGridConfigUbo const & rhs) delete
Member Data Documentation
LpvGridConfig
C3D_API const std::string castor3d::LpvGridConfigUbo::LpvGridConfig static
LpvGridData
C3D_API const std::string castor3d::LpvGridConfigUbo::LpvGridData static
The documentation for this class was generated from the following file:
Shader/Ubos/LpvGridConfigUbo.hpp