Castor3D: castor3d::EnvironmentPrefilter Class Reference
castor3d::EnvironmentPrefilter Class Reference
#include <EnvironmentPrefilter.hpp>
Public Member Functions
C3D_API EnvironmentPrefilter (Engine &engine, RenderDevice const &device, castor::Size const &size, Texture const &srcTexture, SamplerObs sampler, bool isCharlie)
Constructor.
C3D_API ~EnvironmentPrefilter () noexcept
C3D_API void render (QueueData const &queueData) const
Generates the mipmap levels.
C3D_API crg::SemaphoreWaitArray render (crg::SemaphoreWaitArray signalsToWait, ashes::Queue const &queue) const
Generates the mipmap levels.
Texture const & getResult () const noexcept
ashes::Sampler const & getSampler () const noexcept
Constructor & Destructor Documentation
EnvironmentPrefilter()
C3D_API castor3d::EnvironmentPrefilter::EnvironmentPrefilter (Engine & engine, RenderDevice const & device, castor::Size const & size, Texture const & srcTexture, SamplerObs sampler, bool isCharlie) explicit
Constructor.
Parameters
[in] engine The engine.
[in] device The GPU device.
[in] size The render size.
[in] srcTexture The cube texture source.
[in] sampler The sampler used for the source texture.
[in] isCharlie true for Charlie distribution (for sheen), false for GGX.
~EnvironmentPrefilter()
C3D_API castor3d::EnvironmentPrefilter::~EnvironmentPrefilter () noexcept
Member Function Documentation
getResult()
Texture const & castor3d::EnvironmentPrefilter::getResult () const inline noexcept
name Getters.
Referenced by castor3d::IblTextures::getPrefilteredEnvironmentSheenTexture(), and castor3d::IblTextures::getPrefilteredEnvironmentTexture().
getSampler()
ashes::Sampler const & castor3d::EnvironmentPrefilter::getSampler () const inline noexcept
References CU_Require, and castor3d::Sampler::getSampler().
Referenced by castor3d::IblTextures::getPrefilteredEnvironmentSampler(), and castor3d::IblTextures::getPrefilteredEnvironmentSheenSampler().
render() [1/2]
C3D_API crg::SemaphoreWaitArray castor3d::EnvironmentPrefilter::render (crg::SemaphoreWaitArray signalsToWait, ashes::Queue const & queue) const
Generates the mipmap levels.
Parameters
[in] queue The queue receiving the render commands.
[in] signalsToWait The semaphores from the previous render pass.
Returns
The semaphores signaled by this render.
render() [2/2]
C3D_API void castor3d::EnvironmentPrefilter::render (QueueData const & queueData) const
Generates the mipmap levels.
Parameters
[in] queueData The queue receiving the GPU commands.
The documentation for this class was generated from the following file:
Castor3D/Render/PBR/EnvironmentPrefilter.hpp