Castor3D: castor3d::LoadingScreen Class Reference
castor3d::LoadingScreen Class Reference
#include <LoadingScreen.hpp>
Public Member Functions
C3D_API LoadingScreen (ProgressBar &progressBar, RenderDevice const &device, crg::ResourcesCache &resources, SceneRPtr scene, VkRenderPass renderPass, castor::Size const &size)
C3D_API ~LoadingScreen () noexcept
C3D_API void enable () noexcept
C3D_API void disable () noexcept
C3D_API void update (CpuUpdater &updater)
C3D_API void update (GpuUpdater &updater)
C3D_API void setRenderPass (VkRenderPass renderPass, castor::Size const &renderSize, VkFormat swapchainFormat)
C3D_API void upload (UploadData &uploader)
Uploads overlays GPU buffers to VRAM.
C3D_API crg::SemaphoreWaitArray render (ashes::Queue const &queue, ashes::FrameBuffer const &framebuffer, crg::SemaphoreWaitArray const &toWait, crg::Fence *&fence)
Renders the loading screen.
crg::SemaphoreWaitArray render (ashes::Queue const &queue, ashes::FrameBuffer const &framebuffer, crg::SemaphoreWait const &toWait, crg::Fence *&fence)
Renders the loading screen.
void initGlobalRange (uint32_t value)
void stepGlobal (castor::String const &globalTitle)
void initLocalRange (castor::String const &globalLabel, uint32_t value)
void stepLocal (castor::String const &label)
bool isEnabled () const
ProgressBar & getProgressBar ()
Static Public Attributes
static C3D_API castor::String const SceneName
Constructor & Destructor Documentation
LoadingScreen()
C3D_API castor3d::LoadingScreen::LoadingScreen (ProgressBar & progressBar, RenderDevice const & device, crg::ResourcesCache & resources, SceneRPtr scene, VkRenderPass renderPass, castor::Size const & size)
~LoadingScreen()
C3D_API castor3d::LoadingScreen::~LoadingScreen () noexcept
Member Function Documentation
disable()
C3D_API void castor3d::LoadingScreen::disable () noexcept
enable()
C3D_API void castor3d::LoadingScreen::enable () noexcept
getProgressBar()
ProgressBar & castor3d::LoadingScreen::getProgressBar () inline
initGlobalRange()
void castor3d::LoadingScreen::initGlobalRange (uint32_t value) inline
name Mutators.
References castor3d::ProgressBar::initGlobalRange().
initLocalRange()
void castor3d::LoadingScreen::initLocalRange (castor::String const & globalLabel, uint32_t value) inline
References castor3d::ProgressBar::initLocalRange().
isEnabled()
bool castor3d::LoadingScreen::isEnabled () const inline
name Getters.
render() [1/2]
crg::SemaphoreWaitArray castor3d::LoadingScreen::render (ashes::Queue const & queue, ashes::FrameBuffer const & framebuffer, crg::SemaphoreWait const & toWait, crg::Fence *& fence) inline
Renders the loading screen.
Parameters
[in] queue The queue receiving the render commands.
[in] framebuffer The framebuffer receiving the render.
[in] toWait The semaphore from the previous render pass.
[in] fence The fence to wait, nullptr to prevent waiting.
Returns
The semaphores signaled by this render.
References render().
render() [2/2]
C3D_API crg::SemaphoreWaitArray castor3d::LoadingScreen::render (ashes::Queue const & queue, ashes::FrameBuffer const & framebuffer, crg::SemaphoreWaitArray const & toWait, crg::Fence *& fence)
Renders the loading screen.
Parameters
[in] queue The queue receiving the render commands.
[in] framebuffer The framebuffer receiving the render.
[in] toWait The semaphores from the previous render pass.
[in] fence The fence to wait, nullptr to prevent waiting.
Returns
The semaphores signaled by this render.
Referenced by render().
setRenderPass()
C3D_API void castor3d::LoadingScreen::setRenderPass (VkRenderPass renderPass, castor::Size const & renderSize, VkFormat swapchainFormat)
stepGlobal()
void castor3d::LoadingScreen::stepGlobal (castor::String const & globalTitle) inline
References castor3d::ProgressBar::stepGlobal().
stepLocal()
void castor3d::LoadingScreen::stepLocal (castor::String const & label) inline
References castor3d::ProgressBar::stepLocal().
update() [1/2]
C3D_API void castor3d::LoadingScreen::update (CpuUpdater & updater)
update() [2/2]
C3D_API void castor3d::LoadingScreen::update (GpuUpdater & updater)
upload()
C3D_API void castor3d::LoadingScreen::upload (UploadData & uploader)
Uploads overlays GPU buffers to VRAM.
Parameters
[in,out] uploader Receives the upload requests.
Member Data Documentation
SceneName
C3D_API castor::String const castor3d::LoadingScreen::SceneName static
The documentation for this class was generated from the following file:
Castor3D/Miscellaneous/LoadingScreen.hpp