Castor3D: castor3d::TextureAnimation Class Reference
castor3d::TextureAnimation Class Reference
#include <TextureAnimation.hpp>
Public Member Functions
C3D_API TextureAnimation (Engine &engine, castor::String const &name=castor::cuEmptyString)
Constructor.
C3D_API void setAnimable (TextureUnit &unit)
C3D_API void initialiseTiles (TextureUnit const &unit)
C3D_API castor::Point3f getTranslate (castor::Milliseconds const &time) const
C3D_API castor::Angle getRotate (castor::Milliseconds const &time) const
C3D_API castor::Point3f getScale (castor::Milliseconds const &time) const
C3D_API bool isTransformAnimated () const
void addPendingAnimated (AnimatedObject &object) noexcept
TextureTranslateSpeed const & getTranslateSpeed () const noexcept
TextureRotateSpeed const & getRotateSpeed () const noexcept
TextureScaleSpeed const & getScaleSpeed () const noexcept
void setTranslateSpeed (TextureTranslateSpeed translate) noexcept
void setRotateSpeed (TextureRotateSpeed rotate) noexcept
void setScaleSpeed (TextureScaleSpeed scale) noexcept
void enableTileAnim () noexcept
bool isTileAnimated () const noexcept
void setTransformSpeed (TextureTranslateSpeed translate, TextureRotateSpeed rotate, TextureScaleSpeed scale) noexcept
C3D_API TextureAnimation (TextureAnimation &&rhs) noexcept=default
C3D_API TextureAnimation & operator= (TextureAnimation &&rhs) noexcept=delete
C3D_API TextureAnimation (TextureAnimation const &rhs)=delete
C3D_API TextureAnimation & operator= (TextureAnimation const &rhs)=delete
C3D_API ~TextureAnimation () noexcept override=default
Public Member Functions inherited from castor3d::AnimationT< Engine >
AnimationT (Engine &handler, AnimationType type, AnimableT< Engine > &animable, castor::String const &name=castor::cuEmptyString)
Constructor.
AnimationT (Engine &handler, AnimationType type, castor::String const &name=castor::cuEmptyString)
Constructor.
void addKeyFrame (AnimationKeyFrameUPtr keyFrame)
Adds a keyframe to the animation.
AnimationKeyFrameArray::iterator find (castor::Milliseconds const &time)
Finds a keyframe given a time index.
void findKeyFrame (castor::Milliseconds const &time, AnimationKeyFrameArray::iterator &prv, AnimationKeyFrameArray::iterator &cur) const
Finds a keyframe given a time index.
void updateLength ()
Updates the animation length.
bool isEmpty () const
size_t size () const
AnimationKeyFrameArray::const_iterator begin () const
AnimationKeyFrameArray::iterator begin ()
AnimationKeyFrameArray::const_iterator end () const
AnimationKeyFrameArray::iterator end ()
AnimationType getType () const
castor::Milliseconds const & getLength () const
AnimableT< Engine > * getAnimable () const
C3D_API AnimationT (AnimationT &&rhs) noexcept=default
C3D_API AnimationT (AnimationT const &rhs)=delete
C3D_API AnimationT & operator= (AnimationT &&rhs) noexcept=delete
C3D_API AnimationT & operator= (AnimationT const &rhs)=delete
virtual C3D_API ~AnimationT () noexcept=default
Public Member Functions inherited from castor::NamedBaseT< T >
NamedBaseT (T name) noexcept
Constructor.
T const & getName () const noexcept
Retrieves the name.
void rename (T name) noexcept
Public Member Functions inherited from castor::OwnedBy< Owner >
Owner * getOwner () const
Protected Attributes
TextureTranslateSpeed m_translate {}
TextureRotateSpeed m_rotate {}
TextureScaleSpeed m_scale {}
bool m_tileAnim {}
castor::Set< AnimatedObject * > m_pending
Protected Attributes inherited from castor3d::AnimationT< Engine >
AnimableT< Engine > * m_animable
AnimationType m_type
castor::Milliseconds m_length
AnimationKeyFrameArray m_keyframes
Protected Attributes inherited from castor::NamedBaseT< T >
T m_name
Friends
class BinaryWriter< TextureAnimation >
class BinaryParser< TextureAnimation >
class TextureAnimationInstance
Additional Inherited Members
Protected Member Functions inherited from castor::OwnedBy< Owner >
OwnedBy (Owner &owner)
Constructor.
Constructor & Destructor Documentation
TextureAnimation() [1/3]
C3D_API castor3d::TextureAnimation::TextureAnimation (TextureAnimation && rhs) default noexcept
name Copy / Move.
TextureAnimation() [2/3]
C3D_API castor3d::TextureAnimation::TextureAnimation (TextureAnimation const & rhs) delete
~TextureAnimation()
C3D_API castor3d::TextureAnimation::~TextureAnimation () override default noexcept
TextureAnimation() [3/3]
C3D_API castor3d::TextureAnimation::TextureAnimation (Engine & engine, castor::String const & name = castor::cuEmptyString) explicit
Constructor.
Parameters
[in] engine The engine.
[in] name The name of the animation.
Member Function Documentation
addPendingAnimated()
void castor3d::TextureAnimation::addPendingAnimated (AnimatedObject & object) inline noexcept
References m_pending.
enableTileAnim()
void castor3d::TextureAnimation::enableTileAnim () inline noexcept
References m_tileAnim.
getRotate()
C3D_API castor::Angle castor3d::TextureAnimation::getRotate (castor::Milliseconds const & time) const
getRotateSpeed()
TextureRotateSpeed const & castor3d::TextureAnimation::getRotateSpeed () const inline noexcept
References m_rotate.
getScale()
C3D_API castor::Point3f castor3d::TextureAnimation::getScale (castor::Milliseconds const & time) const
getScaleSpeed()
TextureScaleSpeed const & castor3d::TextureAnimation::getScaleSpeed () const inline noexcept
References m_scale.
getTranslate()
C3D_API castor::Point3f castor3d::TextureAnimation::getTranslate (castor::Milliseconds const & time) const
getTranslateSpeed()
TextureTranslateSpeed const & castor3d::TextureAnimation::getTranslateSpeed () const inline noexcept
References m_translate.
initialiseTiles()
C3D_API void castor3d::TextureAnimation::initialiseTiles (TextureUnit const & unit)
isTileAnimated()
bool castor3d::TextureAnimation::isTileAnimated () const inline noexcept
References m_tileAnim.
isTransformAnimated()
C3D_API bool castor3d::TextureAnimation::isTransformAnimated () const
operator=() [1/2]
C3D_API TextureAnimation & castor3d::TextureAnimation::operator= (TextureAnimation && rhs) delete noexcept
operator=() [2/2]
C3D_API TextureAnimation & castor3d::TextureAnimation::operator= (TextureAnimation const & rhs) delete
setAnimable()
C3D_API void castor3d::TextureAnimation::setAnimable (TextureUnit & unit)
setRotateSpeed()
void castor3d::TextureAnimation::setRotateSpeed (TextureRotateSpeed rotate) inline noexcept
References m_rotate.
Referenced by setTransformSpeed().
setScaleSpeed()
void castor3d::TextureAnimation::setScaleSpeed (TextureScaleSpeed scale) inline noexcept
References m_scale.
Referenced by setTransformSpeed().
setTransformSpeed()
void castor3d::TextureAnimation::setTransformSpeed (TextureTranslateSpeed translate, TextureRotateSpeed rotate, TextureScaleSpeed scale) inline noexcept
References setRotateSpeed(), setScaleSpeed(), and setTranslateSpeed().
setTranslateSpeed()
void castor3d::TextureAnimation::setTranslateSpeed (TextureTranslateSpeed translate) inline noexcept
References m_translate.
Referenced by setTransformSpeed().
Friends And Related Symbol Documentation
BinaryParser< TextureAnimation >
friend class BinaryParser< TextureAnimation > friend
BinaryWriter< TextureAnimation >
friend class BinaryWriter< TextureAnimation > friend
TextureAnimationInstance
friend class TextureAnimationInstance friend
Member Data Documentation
m_pending
castor::Set< AnimatedObject * > castor3d::TextureAnimation::m_pending protected
Referenced by addPendingAnimated().
m_rotate
TextureRotateSpeed castor3d::TextureAnimation::m_rotate {} protected
Referenced by getRotateSpeed(), and setRotateSpeed().
m_scale
TextureScaleSpeed castor3d::TextureAnimation::m_scale {} protected
Referenced by getScaleSpeed(), and setScaleSpeed().
m_tileAnim
bool castor3d::TextureAnimation::m_tileAnim {} protected
Referenced by enableTileAnim(), and isTileAnimated().
m_translate
TextureTranslateSpeed castor3d::TextureAnimation::m_translate {} protected
Referenced by getTranslateSpeed(), and setTranslateSpeed().
The documentation for this class was generated from the following file:
Castor3D/Material/Texture/Animation/TextureAnimation.hpp