Castor3D: castor::ConstPixelIterator< PF > Struct Template Reference
castor::ConstPixelIterator< PF > Struct Template Reference
Pixel buffer iterator.
#include <PixelConstIterator.hpp>
Public Types
using value_type = Pixel< PF >
using difference_type = std::ptrdiff_t
using pointer = Pixel< PF > const *
using reference = Pixel< PF > const &
using pixel_type = Pixel< PF >
using array_type = PxBufferBase::PxArray
using internal_type = array_type::const_iterator
using iterator_category = internal_type::iterator_category
Public Member Functions
~ConstPixelIterator () noexcept=default
ConstPixelIterator (array_type const &array, internal_type const &iter)
ConstPixelIterator (ConstPixelIterator const &iter)
ConstPixelIterator (ConstPixelIterator &&iter) noexcept
ConstPixelIterator & operator= (ConstPixelIterator const &it)
ConstPixelIterator & operator= (ConstPixelIterator &&it) noexcept
ConstPixelIterator & operator+= (size_t offset)
ConstPixelIterator & operator-= (size_t offset)
ConstPixelIterator & operator++ ()
ConstPixelIterator operator++ (int)
ConstPixelIterator & operator-- ()
ConstPixelIterator operator-- (int)
pixel_type const & operator* () const
pixel_type & operator* ()
bool operator== (ConstPixelIterator const &it) const
bool operator!= (ConstPixelIterator const &it) const
Static Public Member Functions
static difference_type diffIt (ConstPixelIterator const &lhs, ConstPixelIterator const &rhs)
static difference_type diffIt (ConstPixelIterator const &lhs, PixelIterator< PF > const &rhs)
static difference_type diffIt (PixelIterator< PF > const &lhs, ConstPixelIterator const &rhs)
Friends
template<PixelFormat PiF>
struct PixelIterator
Detailed Description
template<PixelFormat PF>
struct castor::ConstPixelIterator< PF >
Pixel buffer iterator.
Member Typedef Documentation
array_type
template<PixelFormat PF> using castor::ConstPixelIterator< PF >::array_type = PxBufferBase::PxArray
difference_type
template<PixelFormat PF> using castor::ConstPixelIterator< PF >::difference_type = std::ptrdiff_t
internal_type
template<PixelFormat PF> using castor::ConstPixelIterator< PF >::internal_type = array_type::const_iterator
iterator_category
template<PixelFormat PF> using castor::ConstPixelIterator< PF >::iterator_category = internal_type::iterator_category
pixel_type
template<PixelFormat PF> using castor::ConstPixelIterator< PF >::pixel_type = Pixel< PF >
pointer
template<PixelFormat PF> using castor::ConstPixelIterator< PF >::pointer = Pixel< PF > const *
reference
template<PixelFormat PF> using castor::ConstPixelIterator< PF >::reference = Pixel< PF > const &
value_type
template<PixelFormat PF> using castor::ConstPixelIterator< PF >::value_type = Pixel< PF >
Constructor & Destructor Documentation
~ConstPixelIterator()
template<PixelFormat PF> castor::ConstPixelIterator< PF >::~ConstPixelIterator () default noexcept
ConstPixelIterator() [1/3]
template<PixelFormat PF> castor::ConstPixelIterator< PF >::ConstPixelIterator (array_type const & array, internal_type const & iter) inline
ConstPixelIterator() [2/3]
template<PixelFormat PF> castor::ConstPixelIterator< PF >::ConstPixelIterator (ConstPixelIterator< PF > const & iter) inline
ConstPixelIterator() [3/3]
template<PixelFormat PF> castor::ConstPixelIterator< PF >::ConstPixelIterator (ConstPixelIterator< PF > && iter) inline noexcept
Member Function Documentation
diffIt() [1/3]
template<PixelFormat PF> static difference_type castor::ConstPixelIterator< PF >::diffIt (ConstPixelIterator< PF > const & lhs, ConstPixelIterator< PF > const & rhs) inline static
Referenced by castor::operator-(), castor::operator-(), and castor::operator-().
diffIt() [2/3]
template<PixelFormat PF> static difference_type castor::ConstPixelIterator< PF >::diffIt (ConstPixelIterator< PF > const & lhs, PixelIterator< PF > const & rhs) inline static
diffIt() [3/3]
template<PixelFormat PF> static difference_type castor::ConstPixelIterator< PF >::diffIt (PixelIterator< PF > const & lhs, ConstPixelIterator< PF > const & rhs) inline static
operator!=()
template<PixelFormat PF> bool castor::ConstPixelIterator< PF >::operator!= (ConstPixelIterator< PF > const & it) const inline
operator*() [1/2]
template<PixelFormat PF> pixel_type & castor::ConstPixelIterator< PF >::operator* () inline
References CU_Require.
operator*() [2/2]
template<PixelFormat PF> pixel_type const & castor::ConstPixelIterator< PF >::operator* () const inline
References CU_Require.
operator++() [1/2]
template<PixelFormat PF> ConstPixelIterator & castor::ConstPixelIterator< PF >::operator++ () inline
References castor::ConstPixelIterator< PF >::operator+=().
operator++() [2/2]
template<PixelFormat PF> ConstPixelIterator castor::ConstPixelIterator< PF >::operator++ (int) inline
operator+=()
template<PixelFormat PF> ConstPixelIterator & castor::ConstPixelIterator< PF >::operator+= (size_t offset) inline
Referenced by castor::ConstPixelIterator< PF >::operator++().
operator--() [1/2]
template<PixelFormat PF> ConstPixelIterator & castor::ConstPixelIterator< PF >::operator-- () inline
References castor::ConstPixelIterator< PF >::operator-=().
operator--() [2/2]
template<PixelFormat PF> ConstPixelIterator castor::ConstPixelIterator< PF >::operator-- (int) inline
operator-=()
template<PixelFormat PF> ConstPixelIterator & castor::ConstPixelIterator< PF >::operator-= (size_t offset) inline
Referenced by castor::ConstPixelIterator< PF >::operator--().
operator=() [1/2]
template<PixelFormat PF> ConstPixelIterator & castor::ConstPixelIterator< PF >::operator= (ConstPixelIterator< PF > && it) inline noexcept
operator=() [2/2]
template<PixelFormat PF> ConstPixelIterator & castor::ConstPixelIterator< PF >::operator= (ConstPixelIterator< PF > const & it) inline
operator==()
template<PixelFormat PF> bool castor::ConstPixelIterator< PF >::operator== (ConstPixelIterator< PF > const & it) const inline
Friends And Related Symbol Documentation
PixelIterator
template<PixelFormat PF> template<PixelFormat PiF> friend struct PixelIterator friend
The documentation for this struct was generated from the following files:
CastorUtils/Graphics/GraphicsModule.hpp
CastorUtils/Graphics/PixelConstIterator.hpp