Castor3D: Castor3D::Pass Class Reference
Castor3D::Pass Class Reference abstract
Base class of a material pass.
Classes
class TextWriter
Pass loader.
Public Member Functions
C3D_API void Initialise ()
Initialises the pass and all it's dependencies.
C3D_API void Cleanup ()
Cleans up the pass and all it's dependencies.
C3D_API void BindTextures ()
Binds the pass' textures.
C3D_API void UnbindTextures ()
Unbinds the pass' textures.
C3D_API void AddTextureUnit (TextureUnitSPtr p_unit)
Adds a texture unit.
C3D_API TextureUnitSPtr GetTextureUnit (TextureChannel p_channel) const
Retrieves the TextureUnit at wanted channel.
C3D_API void DestroyTextureUnit (uint32_t p_index)
Destroys a TextureUnit at the given index.
C3D_API TextureUnitSPtr GetTextureUnit (uint32_t p_index) const
Retrieves the TextureUnit at the given index.
C3D_API bool HasAlphaBlending () const
Tells if the pass needs alpha blending.
C3D_API void UpdateRenderNode (PassRenderNodeUniforms &p_node) const
Fills shader variables of given render node.
C3D_API void PrepareTextures ()
Reduces the textures.
C3D_API MaterialType GetType () const
C3D_API void SetOpacity (float p_value)
Sets the global alpha value.
TextureChannels const & GetTextureFlags () const
bool HasAutomaticShader () const
void SetTwoSided (bool p_value)
Sets the two sided status.
void SetAlphaBlendMode (BlendMode p_value)
Sets the alpha blend mode.
void SetColourBlendMode (BlendMode p_value)
Sets the colour blend mode.
uint32_t GetTextureUnitsCount () const
bool IsTwoSided () const
Tells if the pass is two sided.
float GetOpacity () const
BlendMode GetAlphaBlendMode () const
BlendMode GetColourBlendMode () const
auto begin () const
auto begin ()
auto end () const
auto end ()
Protected Member Functions
C3D_API Pass (Material &p_parent)
Constructor.
C3D_API ~Pass ()
Destructor.
C3D_API bool DoPrepareTexture (TextureChannel p_channel, uint32_t &p_index, TextureUnitSPtr &p_opacitySource, Castor::PxBufferBaseSPtr &p_opacity)
Prepares a texture to be integrated to the pass.
C3D_API Castor::PxBufferBaseSPtr DoPrepareTexture (TextureChannel p_channel, uint32_t &p_index)
Prepares a texture to be integrated to the pass.
C3D_API void DoPrepareOpacity (TextureUnitSPtr p_opacitySource, Castor::PxBufferBaseSPtr p_opacityImage, uint32_t &p_index)
Prepares the opacity channel.
C3D_API void DoUpdateFlags ()
Updates the texture flags depending on the texture units.
Detailed Description
Base class of a material pass.
Author
Sylvain DOREMUS
Version
0.1
Date
09/02/2010
Constructor & Destructor Documentation
Pass()
C3D_API Castor3D::Pass::Pass (Material & p_parent) protected
Constructor.
Parameters
[in] p_parent The parent material.
~Pass()
C3D_API Castor3D::Pass::~Pass () protected
Destructor.
Member Function Documentation
AddTextureUnit()
C3D_API void Castor3D::Pass::AddTextureUnit (TextureUnitSPtr p_unit)
Adds a texture unit.
Parameters
[in] p_unit The texture unit.
begin() [1/2]
auto Castor3D::Pass::begin () const inline
Returns
A constant iterator on the beginning of the textures array.
begin() [2/2]
auto Castor3D::Pass::begin () inline
Returns
An iterator on the beginning of the textures array.
BindTextures()
C3D_API void Castor3D::Pass::BindTextures ()
Binds the pass' textures.
Referenced by Castor3D::DoBindPass().
Cleanup()
C3D_API void Castor3D::Pass::Cleanup ()
Cleans up the pass and all it's dependencies.
DestroyTextureUnit()
C3D_API void Castor3D::Pass::DestroyTextureUnit (uint32_t p_index)
Destroys a TextureUnit at the given index.
Parameters
[in] p_index the index of the TextureUnit to destroy.
DoPrepareOpacity()
C3D_API void Castor3D::Pass::DoPrepareOpacity (TextureUnitSPtr p_opacitySource, Castor::PxBufferBaseSPtr p_opacityImage, uint32_t & p_index) protected
Prepares the opacity channel.
Parameters
[in] p_opacitySource The texture unit from which opacity comes.
[in] p_opacityImage The alpha channel from p_opacitySource.
[in,out] p_index The texture index.
DoPrepareTexture() [1/2]
C3D_API bool Castor3D::Pass::DoPrepareTexture (TextureChannel p_channel, uint32_t & p_index, TextureUnitSPtr & p_opacitySource, Castor::PxBufferBaseSPtr & p_opacity) protected
Prepares a texture to be integrated to the pass.
Remarks
Removes alpha channel if any, stores it in p_opacity if it is empty.
Parameters
[in] p_channel The texture channel.
[in,out] p_index The texture index.
[in,out] p_opacitySource Receives the texture unit if p_opacity is modified.
[in,out] p_opacity Receives the alpha channel of the texture.
Returns
true if there were an alpha channel in the texture.
DoPrepareTexture() [2/2]
C3D_API Castor::PxBufferBaseSPtr Castor3D::Pass::DoPrepareTexture (TextureChannel p_channel, uint32_t & p_index) protected
Prepares a texture to be integrated to the pass.
Remarks
Removes alpha channel if any.
Parameters
[in] p_channel The texture channel.
[in,out] p_index The texture index.
Returns
The original texture's alpha channel.
DoUpdateFlags()
C3D_API void Castor3D::Pass::DoUpdateFlags () protected
Updates the texture flags depending on the texture units.
end() [1/2]
auto Castor3D::Pass::end () const inline
Returns
A constant iterator on the end of the textures array.
end() [2/2]
auto Castor3D::Pass::end () inline
Returns
An iterator on the end of the textures array.
GetAlphaBlendMode()
BlendMode Castor3D::Pass::GetAlphaBlendMode () const inline
Returns
The alpha blend mode.
GetColourBlendMode()
BlendMode Castor3D::Pass::GetColourBlendMode () const inline
Returns
The colour blend mode.
GetOpacity()
float Castor3D::Pass::GetOpacity () const inline
Returns
The global opacity value.
GetTextureFlags()
TextureChannels const& Castor3D::Pass::GetTextureFlags () const inline
Returns
The texture channels flags combination.
GetTextureUnit() [1/2]
C3D_API TextureUnitSPtr Castor3D::Pass::GetTextureUnit (TextureChannel p_channel) const
Retrieves the TextureUnit at wanted channel.
Remarks
If more than one TextureUnits are found at given channel, the first one is returned.
Parameters
[in] p_channel The channel.
Returns
nullptr if no TextureUnit at wanted channel.
Referenced by Castor3D::DoBindPassOpacityMap(), and Castor3D::DoUnbindPassOpacityMap().
GetTextureUnit() [2/2]
C3D_API TextureUnitSPtr Castor3D::Pass::GetTextureUnit (uint32_t p_index) const
Retrieves the TextureUnit at the given index.
Parameters
[in] p_index The index of the TextureUnit to retrieve.
Returns
The retrieved TextureUnit, nullptr if none.
GetTextureUnitsCount()
uint32_t Castor3D::Pass::GetTextureUnitsCount () const inline
Returns
The texture units count.
GetType()
C3D_API MaterialType Castor3D::Pass::GetType () const
Returns
The material type.
HasAlphaBlending()
C3D_API bool Castor3D::Pass::HasAlphaBlending () const
Tells if the pass needs alpha blending.
Returns
true if at least one texture unit has an alpha channel.
HasAutomaticShader()
bool Castor3D::Pass::HasAutomaticShader () const inline
Returns
true if the pass shader is automatically generated.
Initialise()
C3D_API void Castor3D::Pass::Initialise ()
Initialises the pass and all it's dependencies.
IsTwoSided()
bool Castor3D::Pass::IsTwoSided () const inline
Tells if the pass is two sided.
PrepareTextures()
C3D_API void Castor3D::Pass::PrepareTextures ()
Reduces the textures.
SetAlphaBlendMode()
void Castor3D::Pass::SetAlphaBlendMode (BlendMode p_value) inline
Sets the alpha blend mode.
Parameters
[in] p_value The new value.
SetColourBlendMode()
void Castor3D::Pass::SetColourBlendMode (BlendMode p_value) inline
Sets the colour blend mode.
Parameters
[in] p_value The new value.
SetOpacity()
C3D_API void Castor3D::Pass::SetOpacity (float p_value)
Sets the global alpha value.
Parameters
[in] p_value The new value.
SetTwoSided()
void Castor3D::Pass::SetTwoSided (bool p_value) inline
Sets the two sided status.
Parameters
[in] p_value The new value.
UnbindTextures()
C3D_API void Castor3D::Pass::UnbindTextures ()
Unbinds the pass' textures.
Referenced by Castor3D::DoUnbindPass().
UpdateRenderNode()
C3D_API void Castor3D::Pass::UpdateRenderNode (PassRenderNodeUniforms & p_node) const
Fills shader variables of given render node.
Referenced by Castor3D::DoBindPass().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Material/Pass.hpp