name: Dependencies

on:
  workflow_dispatch

jobs:
  build-windows:
    strategy:
      matrix:
        os: [[windows-latest,x64-windows,msvc]]
        buildType: [Release]

    runs-on: ${{ matrix.os[0] }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v4
      with:
        vcpkgGitCommitId: '${{ secrets.VCPKG_COMMIT_ID }}'
        setupOnly: true

    - name: Install vcpkg packages
      shell: bash
      run: $VCPKG_ROOT/vcpkg install spirv-cross:${{ matrix.os[1] }} freetype:${{ matrix.os[1] }} zlib:${{ matrix.os[1] }} minizip:${{ matrix.os[1] }} vkfft:${{ matrix.os[1] }} convectionkernels:${{ matrix.os[1] }} meshoptimizer:${{ matrix.os[1] }} gli:${{ matrix.os[1] }} glslang:${{ matrix.os[1] }} assimp:${{ matrix.os[1] }}

  build-macos:
    strategy:
      matrix:
        os: [[macos-latest,x64-osx,clang]]
        buildType: [Release]

    runs-on: ${{ matrix.os[0] }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v4
      with:
        vcpkgGitCommitId: '${{ secrets.VCPKG_COMMIT_ID }}'
        setupOnly: true

    - name: Install vcpkg wxwidgets
      shell: bash
      run: $VCPKG_ROOT/vcpkg install wxwidgets:${{ matrix.os[1] }}

    - name: Install vcpkg packages
      shell: bash
      run: $VCPKG_ROOT/vcpkg install spirv-cross:${{ matrix.os[1] }} freetype:${{ matrix.os[1] }} zlib:${{ matrix.os[1] }} minizip:${{ matrix.os[1] }} vkfft:${{ matrix.os[1] }} convectionkernels:${{ matrix.os[1] }} meshoptimizer:${{ matrix.os[1] }} gli:${{ matrix.os[1] }} glslang:${{ matrix.os[1] }} assimp:${{ matrix.os[1] }}

  build-linux-gcc:
    strategy:
      matrix:
        os: [[ubuntu-latest,x64-linux,gcc]]
        buildType: [Release]

    runs-on: ${{ matrix.os[0] }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v4
      with:
        vcpkgGitCommitId: '${{ secrets.VCPKG_COMMIT_ID }}'
        setupOnly: true
  
    - name: Install necessary G++ version.
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends ccache gcc-10 g++-10
        echo "CC=gcc-10" >> $GITHUB_ENV
        echo "CXX=g++-10" >> $GITHUB_ENV

    - name: Install necessary packages
      shell: bash
      run: |
        sudo apt-get install -y --no-install-recommends libxi-dev libgl1-mesa-dev libglu1-mesa-dev mesa-common-dev libxrandr-dev libxxf86vm-dev libxaw7-dev libwayland-dev libxcb1-dev libx11-xcb-dev libassimp-dev libfreeimage-dev pkg-config libgtk-3-dev libsecret-1-dev libgcrypt20-dev libsystemd-dev

    - name: Install vcpkg wxwidgets
      shell: bash
      run: $VCPKG_ROOT/vcpkg install wxwidgets:${{ matrix.os[1] }}

    - name: Install vcpkg packages
      shell: bash
      run: $VCPKG_ROOT/vcpkg install spirv-cross:${{ matrix.os[1] }} freetype:${{ matrix.os[1] }} zlib:${{ matrix.os[1] }} minizip:${{ matrix.os[1] }} vkfft:${{ matrix.os[1] }} convectionkernels:${{ matrix.os[1] }} meshoptimizer:${{ matrix.os[1] }} gli:${{ matrix.os[1] }} glslang:${{ matrix.os[1] }} assimp:${{ matrix.os[1] }}

  build-linux-clang:
    strategy:
      matrix:
        os: [[ubuntu-latest,x64-linux,clang]]
        buildType: [Release]

    runs-on: ${{ matrix.os[0] }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v4
      with:
        vcpkgGitCommitId: '${{ secrets.VCPKG_COMMIT_ID }}'
        setupOnly: true

    - name: Install necessary Clang++ version
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends ccache clang-12 clang++-12
        echo "CC=clang-12" >> $GITHUB_ENV
        echo "CXX=clang++-12" >> $GITHUB_ENV

    - name: Install necessary packages
      shell: bash
      run: |
        sudo apt-get install -y --no-install-recommends libxi-dev libgl1-mesa-dev libglu1-mesa-dev mesa-common-dev libxrandr-dev libxxf86vm-dev libxaw7-dev libwayland-dev libxcb1-dev libx11-xcb-dev libassimp-dev libfreeimage-dev pkg-config libgtk-3-dev libsecret-1-dev libgcrypt20-dev libsystemd-dev

    - name: Install vcpkg wxwidgets
      shell: bash
      run: $VCPKG_ROOT/vcpkg install wxwidgets:${{ matrix.os[1] }}

    - name: Install vcpkg packages
      shell: bash
      run: $VCPKG_ROOT/vcpkg install spirv-cross:${{ matrix.os[1] }} freetype:${{ matrix.os[1] }} zlib:${{ matrix.os[1] }} minizip:${{ matrix.os[1] }} vkfft:${{ matrix.os[1] }} convectionkernels:${{ matrix.os[1] }} meshoptimizer:${{ matrix.os[1] }} gli:${{ matrix.os[1] }} glslang:${{ matrix.os[1] }}
