Castor3D: castor3d::RenderTechnique Class Reference
castor3d::RenderTechnique Class Reference
Public Types
using ShadowMapArray = std::vector< ShadowMapUPtr >
Public Member Functions
C3D_API RenderTechnique (castor::String const &name, RenderTarget &renderTarget, RenderSystem &renderSystem, Parameters const &parameters, SsaoConfig const &ssaoConfig)
Constructor.
virtual C3D_API ~RenderTechnique ()
Destructor.
C3D_API bool initialise (RenderDevice const &device, std::vector< IntermediateView > &intermediates)
Initialisation function.
C3D_API void cleanup (RenderDevice const &device)
Cleanup function.
C3D_API void update (CpuUpdater &updater)
Updates the render pass, CPU wise.
C3D_API void update (GpuUpdater &updater)
Updates the render pass, GPU wise.
C3D_API ashes::Semaphore const & render (RenderDevice const &device, ashes::SemaphoreCRefArray const &waitSemaphores, RenderInfo &info)
Render function.
C3D_API bool writeInto (castor::TextFile &file)
Writes the technique into a text file.
C3D_API void accept (RenderTechniqueVisitor &visitor)
Visitor acceptance function.
castor::Size const & getSize () const
TextureLayout const & getResult () const
TextureLayout const & getDepth () const
TextureLayoutSPtr getDepthPtr () const
MatrixUbo const & getMatrixUbo () const
MatrixUbo & getMatrixUbo ()
RenderTechniquePass const & getOpaquePass () const
RenderTechniquePass const & getTransparentPass () const
ShadowMapLightTypeArray const & getShadowMaps () const
ashes::Semaphore const & getSemaphore () const
RenderTarget const & getRenderTarget () const
bool isMultisampling () const
SsaoConfig const & getSsaoConfig () const
SsaoConfig & getSsaoConfig ()
DebugConfig const & getDebugConfig () const
DebugConfig & getDebugConfig ()
Friends
class RenderTechniquePass
Member Typedef Documentation
ShadowMapArray
using castor3d::RenderTechnique::ShadowMapArray = std::vector< ShadowMapUPtr >
Constructor & Destructor Documentation
RenderTechnique()
C3D_API castor3d::RenderTechnique::RenderTechnique (castor::String const & name, RenderTarget & renderTarget, RenderSystem & renderSystem, Parameters const & parameters, SsaoConfig const & ssaoConfig)
Constructor.
Parameters
[in] name The technique name.
[in] renderTarget The render target for this technique.
[in] renderSystem The render system.
[in] parameters The technique parameters.
[in] ssaoConfig The SSAO configuration.
~RenderTechnique()
virtual C3D_API castor3d::RenderTechnique::~RenderTechnique () virtual
Destructor.
Member Function Documentation
accept()
C3D_API void castor3d::RenderTechnique::accept (RenderTechniqueVisitor & visitor)
Visitor acceptance function.
Parameters
visitor The ... visitor.
cleanup()
C3D_API void castor3d::RenderTechnique::cleanup (RenderDevice const & device)
Cleanup function.
Parameters
[in] device The GPU device.
getDebugConfig() [1/2]
DebugConfig const& castor3d::RenderTechnique::getDebugConfig () const inline
getDebugConfig() [2/2]
DebugConfig& castor3d::RenderTechnique::getDebugConfig () inline
getDepth()
TextureLayout const& castor3d::RenderTechnique::getDepth () const inline
References castor3d::TextureUnit::getTexture().
getDepthPtr()
TextureLayoutSPtr castor3d::RenderTechnique::getDepthPtr () const inline
References castor3d::TextureUnit::getTexture().
getMatrixUbo() [1/2]
MatrixUbo const& castor3d::RenderTechnique::getMatrixUbo () const inline
getMatrixUbo() [2/2]
MatrixUbo& castor3d::RenderTechnique::getMatrixUbo () inline
getOpaquePass()
RenderTechniquePass const& castor3d::RenderTechnique::getOpaquePass () const inline
getRenderTarget()
RenderTarget const& castor3d::RenderTechnique::getRenderTarget () const inline
getResult()
TextureLayout const& castor3d::RenderTechnique::getResult () const inline
References castor3d::TextureUnit::getTexture(), and castor3d::TextureUnit::isTextured().
getSemaphore()
ashes::Semaphore const& castor3d::RenderTechnique::getSemaphore () const inline
getShadowMaps()
ShadowMapLightTypeArray const& castor3d::RenderTechnique::getShadowMaps () const inline
getSize()
castor::Size const& castor3d::RenderTechnique::getSize () const inline
name Getters.
getSsaoConfig() [1/2]
SsaoConfig const& castor3d::RenderTechnique::getSsaoConfig () const inline
getSsaoConfig() [2/2]
SsaoConfig& castor3d::RenderTechnique::getSsaoConfig () inline
getTransparentPass()
RenderTechniquePass const& castor3d::RenderTechnique::getTransparentPass () const inline
initialise()
C3D_API bool castor3d::RenderTechnique::initialise (RenderDevice const & device, std::vector< IntermediateView > & intermediates)
Initialisation function.
Parameters
[in] device The GPU device.
[out] intermediates Receives the intermediate views used by the whole technique.
Returns
true if ok.
isMultisampling()
bool castor3d::RenderTechnique::isMultisampling () const inline
render()
C3D_API ashes::Semaphore const& castor3d::RenderTechnique::render (RenderDevice const & device, ashes::SemaphoreCRefArray const & waitSemaphores, RenderInfo & info)
Render function.
Parameters
[in] device The GPU device.
[in] waitSemaphores The semaphores to wait for.
[out] info Receives the render informations.
update() [1/2]
C3D_API void castor3d::RenderTechnique::update (CpuUpdater & updater)
Updates the render pass, CPU wise.
Parameters
[in,out] updater The update data.
update() [2/2]
C3D_API void castor3d::RenderTechnique::update (GpuUpdater & updater)
Updates the render pass, GPU wise.
Parameters
[in,out] updater The update data.
writeInto()
C3D_API bool castor3d::RenderTechnique::writeInto (castor::TextFile & file)
Writes the technique into a text file.
Parameters
[in] file The file.
Friends And Related Function Documentation
RenderTechniquePass
friend class RenderTechniquePass friend
The documentation for this class was generated from the following file:
Render/Technique/RenderTechnique.hpp