Castor3D: castor3d::PrepassRendering Class Reference
castor3d::PrepassRendering Class Reference
#include <PrepassRendering.hpp>
Public Member Functions
C3D_API PrepassRendering (RenderTechnique &parent, RenderDevice const &device, QueueData const &queueData, crg::FramePassArray const &previousPasses, ProgressBar *progress, bool deferred, bool visbuffer)
Constructor.
C3D_API ~PrepassRendering ()
Destructor.
C3D_API void listIntermediates (std::vector< IntermediateView > &intermediates)
Lists the intermediate view used by the whole technique.
C3D_API void update (CpuUpdater &updater)
Updates the render pass, CPU wise.
C3D_API void update (GpuUpdater &updater)
Updates the render pass, GPU wise.
C3D_API void accept (RenderTechniqueVisitor &visitor)
Visitor acceptance function.
C3D_API Engine * getEngine () const
C3D_API crg::FramePass const & getLastPass () const
C3D_API crg::FramePass const & getDepthRangePass () const
C3D_API bool hasVisibility () const
Texture const & getDepthObj () const
Texture const & getVisibility () const
ashes::Buffer< int32_t > const & getDepthRange () const
bool needsDepthRange () const
void setNeedsDepthRange (bool value)
VisibilityPass const & getVisibilityPass () const
Static Public Member Functions
static C3D_API uint32_t countInitialisationSteps ()
Constructor & Destructor Documentation
PrepassRendering()
C3D_API castor3d::PrepassRendering::PrepassRendering (RenderTechnique & parent, RenderDevice const & device, QueueData const & queueData, crg::FramePassArray const & previousPasses, ProgressBar * progress, bool deferred, bool visbuffer)
Constructor.
Parameters
[in] parent The parent technique.
[in] device The GPU device.
[in] queueData The queue receiving the GPU commands.
[in] previousPasses The passes this pass depends on.
[in] progress The optional progress bar.
[in] deferred true to enable deferred rendering.
[in] visbuffer true to enable visibility buffer.
~PrepassRendering()
C3D_API castor3d::PrepassRendering::~PrepassRendering ()
Destructor.
Member Function Documentation
accept()
C3D_API void castor3d::PrepassRendering::accept (RenderTechniqueVisitor & visitor)
Visitor acceptance function.
Parameters
visitor The ... visitor.
countInitialisationSteps()
static C3D_API uint32_t castor3d::PrepassRendering::countInitialisationSteps () static
Returns
The number of steps needed for initialisation, to show progression.
getDepthObj()
Texture const & castor3d::PrepassRendering::getDepthObj () const inline
References castor3d::eDepthObj.
Referenced by castor3d::RenderTechnique::getDepthObj().
getDepthRange()
ashes::Buffer< int32_t > const & castor3d::PrepassRendering::getDepthRange () const inline
Referenced by castor3d::RenderTechnique::getDepthRange().
getDepthRangePass()
C3D_API crg::FramePass const & castor3d::PrepassRendering::getDepthRangePass () const
getEngine()
C3D_API Engine * castor3d::PrepassRendering::getEngine () const
name Getters.
getLastPass()
C3D_API crg::FramePass const & castor3d::PrepassRendering::getLastPass () const
getVisibility()
Texture const & castor3d::PrepassRendering::getVisibility () const inline
References castor3d::eVisibility, and hasVisibility().
Referenced by castor3d::RenderTechnique::getVisibilityResult().
getVisibilityPass()
VisibilityPass const & castor3d::PrepassRendering::getVisibilityPass () const inline
hasVisibility()
C3D_API bool castor3d::PrepassRendering::hasVisibility () const
Referenced by getVisibility(), and castor3d::RenderTechnique::hasVisibility().
listIntermediates()
C3D_API void castor3d::PrepassRendering::listIntermediates (std::vector< IntermediateView > & intermediates)
Lists the intermediate view used by the whole technique.
Parameters
[out] intermediates Receives the intermediate views.
needsDepthRange()
bool castor3d::PrepassRendering::needsDepthRange () const inline
setNeedsDepthRange()
void castor3d::PrepassRendering::setNeedsDepthRange (bool value) inline
Referenced by castor3d::RenderTechnique::setNeedsDepthRange().
update() [1/2]
C3D_API void castor3d::PrepassRendering::update (CpuUpdater & updater)
Updates the render pass, CPU wise.
Parameters
[in,out] updater The update data.
update() [2/2]
C3D_API void castor3d::PrepassRendering::update (GpuUpdater & updater)
Updates the render pass, GPU wise.
Parameters
[in,out] updater The update data.
The documentation for this class was generated from the following file:
Render/Prepass/PrepassRendering.hpp