Castor3D: castor3d::SpecularComponent Struct Reference
castor3d::SpecularComponent Struct Reference
#include <SpecularComponent.hpp>
Classes
struct ComponentsShader
struct MaterialShader
class Plugin
Public Member Functions
C3D_API SpecularComponent (Pass &pass, castor::RgbColour defaultValue=Default)
C3D_API void accept (ConfigurationVisitorBase &vis) override
ConfigurationVisitorBase acceptance function.
castor::RgbColour const & getSpecular () const
void setSpecular (castor::RgbColour const &v)
void setSpecular (castor::HdrRgbColour const &v, float gamma)
void setSpecular (castor::Coords3f const &v)
void setSpecular (castor::Point3f const &v)
Public Member Functions inherited from castor3d::BaseDataPassComponentT< castor::AtomicGroupChangeTracked< castor::RgbColour > >
BaseDataPassComponentT (Pass &pass, castor::String type, castor::StringArray deps={}, ParamsT &&... params)
Constructor.
void setData (DataU const &data)
void setData (ParamsT &&... params)
castor::AtomicGroupChangeTracked< castor::RgbColour > & getData ()
castor::AtomicGroupChangeTracked< castor::RgbColour > const & getData () const
Public Member Functions inherited from castor3d::PassComponent
C3D_API PassComponent (Pass &pass, castor::String type, castor::StringArray deps={})
Constructor.
virtual C3D_API ~PassComponent () noexcept=default
C3D_API PassComponentUPtr clone (Pass &pass) const
virtual C3D_API void onAddToPass () const
Called when the component is added to the pass.
C3D_API bool writeText (castor::String const &tabs, castor::Path const &folder, castor::String const &subfolder, castor::StringStream &file) const
Writes the component content to text.
C3D_API void fillBuffer (PassBuffer &buffer) const
Fills the pass buffer with this pass data.
virtual C3D_API void update ()
C3D_API void fillChannel (TextureConfiguration &configuration, uint32_t mask) const
Fills the texture configuration for use with this component.
virtual C3D_API void fillConfig (TextureConfiguration &config, ConfigurationVisitorBase &vis) const
ConfigurationVisitorBase acceptance function, for a specific texture configuration.
virtual C3D_API bool hasColour () const
virtual C3D_API castor::HdrRgbColour const & getColour () const
virtual C3D_API void setColour (castor::HdrRgbColour v)
virtual C3D_API PassComponentFlag getPassFlags () const
castor::String const & getType () const
castor::StringArray const & getDependencies () const
PassComponentPlugin const & getPlugin () const
PassComponentID getId () const
void setColour (castor::RgbColour const &v, float gamma=2.2f)
void setColour (castor::Coords3f const &v)
void setColour (castor::Point3f const &v)
Public Member Functions inherited from castor::OwnedBy< Pass >
Pass * getOwner () const
Static Public Member Functions
static PassComponentPluginUPtr createPlugin (PassComponentRegister const &passComponent)
Static Public Attributes
static C3D_API castor::String const TypeName
static float constexpr DefaultComponent = 1.0f
static C3D_API castor::RgbColour const Default
Additional Inherited Members
Protected Member Functions inherited from castor::OwnedBy< Pass >
OwnedBy (Pass &owner)
Constructor.
Protected Attributes inherited from castor3d::BaseDataPassComponentT< castor::AtomicGroupChangeTracked< castor::RgbColour > >
castor::AtomicGroupChangeTracked< castor::RgbColour > m_value
Protected Attributes inherited from castor3d::PassComponent
castor::String m_type
castor::StringArray m_dependencies
PassComponentID m_id
PassComponentPlugin const & m_plugin
std::atomic_bool & m_dirty
shader::PassMaterialShader * m_materialShader {}
Constructor & Destructor Documentation
SpecularComponent()
C3D_API castor3d::SpecularComponent::SpecularComponent (Pass & pass, castor::RgbColour defaultValue = Default) explicit
Member Function Documentation
accept()
C3D_API void castor3d::SpecularComponent::accept (ConfigurationVisitorBase & vis) override virtual
ConfigurationVisitorBase acceptance function.
Parameters
vis The ... visitor.
Reimplemented from castor3d::PassComponent.
createPlugin()
static PassComponentPluginUPtr castor3d::SpecularComponent::createPlugin (PassComponentRegister const & passComponent) inline static
getSpecular()
castor::RgbColour const & castor3d::SpecularComponent::getSpecular () const inline
References castor3d::BaseDataPassComponentT< castor::AtomicGroupChangeTracked< castor::RgbColour > >::m_value.
setSpecular() [1/4]
void castor3d::SpecularComponent::setSpecular (castor::Coords3f const & v) inline
References setSpecular().
setSpecular() [2/4]
void castor3d::SpecularComponent::setSpecular (castor::HdrRgbColour const & v, float gamma) inline
References setSpecular().
setSpecular() [3/4]
void castor3d::SpecularComponent::setSpecular (castor::Point3f const & v) inline
References setSpecular().
setSpecular() [4/4]
void castor3d::SpecularComponent::setSpecular (castor::RgbColour const & v) inline
References castor3d::BaseDataPassComponentT< castor::AtomicGroupChangeTracked< castor::RgbColour > >::m_value.
Referenced by setSpecular(), setSpecular(), and setSpecular().
Member Data Documentation
Default
C3D_API castor::RgbColour const castor3d::SpecularComponent::Default static
DefaultComponent
float constexpr castor3d::SpecularComponent::DefaultComponent = 1.0f static constexpr
TypeName
C3D_API castor::String const castor3d::SpecularComponent::TypeName static
The documentation for this struct was generated from the following file:
Castor3D/Material/Pass/Component/Lighting/SpecularComponent.hpp