Castor3D: castor3d::shader Namespace Reference
castor3d::shader Namespace Reference
Classes
class BackgroundModel
struct BillboardData
struct BlendComponents
struct BlendComponentsT
struct BlendComponentT
class BlinnPhongLightingModel
class BRDFHelpers
class BufferBase
class BufferT
class CookTorranceBRDF
struct CullData
struct DerivTex
struct DirectionalLight
class Fog
class GlobalIllumination
struct GpInfoData
struct HdrConfigData
class IblBackgroundModel
class ImgBackgroundModel
struct Intersection
struct LayeredLpvGridData
struct Light
struct LightData
class LightingModel
struct LpvGridData
struct LpvLightData
struct Material
class Materials
struct MatrixData
struct Meshlet
struct MicrofacetDistributionSample
struct ModelData
struct MorphingWeightsData
struct MorphTargetData
struct MorphTargetsData
class NoIblBackgroundModel
struct ObjectIds
struct ObjectsIds
struct OutputComponents
struct OverlayData
struct PassComponentsShader
struct PassMaterialShader
struct PassShader
class PassShaders
struct PayloadT
class PbrLightingModel
class PbrReflectionModel
class PhongLightingModel
class PhongReflectionModel
struct PipelineObjectsIds
struct PointLight
struct RasterizerSurfaceBase
struct RasterizerSurfaceT
struct Ray
class ReflectionModel
struct RsmConfigData
struct SceneData
class Shadow
struct ShadowMapData
struct ShadowOptions
class SheenBRDF
struct SkinningData
struct SpotLight
struct SsaoConfigData
struct SssProfile
class SssProfiles
class SssTransmittance
struct Surface
struct SurfaceBase
class TextureAnimations
struct TextureAnimData
struct TextureConfigData
class TextureConfigurations
class Utils
struct VertexSurfaceT
struct Voxel
struct VoxelData
struct VoxelSurfaceT
Typedefs
using PassComponentsShaderPtr = std::unique_ptr< PassComponentsShader >
using PassMaterialShaderPtr = std::unique_ptr< PassMaterialShader >
Functions
CU_DeclareCUSmartPtr (castor3d::shader, BufferBase, C3D_API)
Writer_Parameter (MicrofacetDistributionSample)
Writer_Parameter (CullData)
C3D_API castor::String getLightingModelName (Engine const &engine, PassTypeID passType)
Writer_Parameter (Meshlet)
C3D_API ast::expr::ExprList makeFnArg (sdw::ShaderWriter &shader, OutputComponents const &value)
template<typename LhsT , typename RhsT >
LhsT translateUV (LhsT const &translate, RhsT const &uv)
sdw::Vec2 rotateUV (sdw::Float const &rotateU, sdw::Float const &rotateV, sdw::Vec2 const &uv)
template<typename LhsT , typename RhsT >
LhsT scaleUV (LhsT const &scale, RhsT const &uv)
Writer_Parameter (Voxel)
template<ast::var::Flag FlagT>
static sdw::UInt getNodeId (sdw::Array< shader::ObjectsIds > const &data, shader::VertexSurfaceT< FlagT > const &surface, sdw::UInt pipelineID, sdw::UInt drawID, PipelineFlags const &flags)
C3D_API sdw::UInt getNodeId (sdw::Array< shader::ObjectsIds > const &data, sdw::UInt pipelineID, sdw::UInt drawID)
C3D_API sdw::UInt getNodeId (sdw::Array< shader::PipelineObjectsIds > const &data, sdw::UInt pipelineID, sdw::UInt drawID)
sdw::UInt getNodeId (sdw::Array< shader::ObjectsIds > const &data, sdw::Array< sdw::UVec4 > const &instances, sdw::UInt pipelineID, sdw::UInt drawID, PipelineFlags const &flags)
Writer_Parameter (BillboardData)
Writer_Parameter (GpInfoData)
Writer_Parameter (HdrConfigData)
Writer_Parameter (MatrixData)
Writer_Parameter (ModelData)
Writer_Parameter (ModelInstancesData)
Writer_Parameter (MorphTargetData)
Writer_Parameter (MorphTargetsData)
Writer_Parameter (MorphingWeightsData)
Writer_Parameter (OverlayData)
Writer_Parameter (PickingData)
Writer_Parameter (RsmConfigData)
Writer_Parameter (SceneData)
Writer_Parameter (ShadowMapData)
Writer_Parameter (SsaoConfigData)
Writer_Parameter (TextureData)
Sdw
template<ast::var::Flag FlagT>
using FragmentSurfaceT = RasterizerSurfaceT< sdw::Vec3, FlagT >
using RasterizerSurface = RasterizerSurfaceT< sdw::Vec3, ast::var::Flag::eNone >
using Vec3BlendComponents = BlendComponentsT< sdw::Vec3 >
using DerivFragmentSurface = RasterizerSurfaceT< DerivTex, ast::var::Flag::eNone >
template<typename TexcoordT >
using RasterSurfaceT = RasterizerSurfaceT< TexcoordT, ast::var::Flag::eNone >
using DerivBlendComponents = BlendComponentsT< DerivTex >
using VertexSurface = VertexSurfaceT< sdw::var::Flag::eNone >
using VoxelSurface = VoxelSurfaceT< sdw::var::Flag::eNone >
using LightingModelPtr = std::unique_ptr< LightingModel >
using ReflectionModelPtr = std::unique_ptr< ReflectionModel >
using LightingModelCreator = std::function< LightingModelPtr(sdw::ShaderWriter &writer, Materials const &materials, Utils &utils, BRDFHelpers &brdf, ShadowOptions shadowsOptions, SssProfiles const *sssProfiles, bool enableVolumetric) >
using LightingModelFactory = castor::Factory< LightingModel, castor::String, LightingModelPtr, LightingModelCreator >
using BackgroundModelPtr = std::unique_ptr< BackgroundModel >
using BackgroundModelCreator = std::function< BackgroundModelPtr(Engine const &engine, sdw::ShaderWriter &writer, Utils &utils, VkExtent2D targetSize, bool needsForeground, uint32_t &binding, uint32_t set) >
using BackgroundModelFactory = castor::Factory< BackgroundModel, castor::String, BackgroundModelPtr, BackgroundModelCreator >
Writer_Parameter (Intersection)
Writer_Parameter (Ray)
Writer_Parameter (BlendComponents)
Writer_Parameter (DirectionalLight)
Writer_Parameter (LayeredLpvGridData)
Writer_Parameter (Light)
Writer_Parameter (LpvGridData)
Writer_Parameter (LpvLightData)
Writer_Parameter (Material)
Writer_Parameter (PointLight)
Writer_Parameter (SpotLight)
Writer_Parameter (Surface)
Writer_Parameter (TextureAnimData)
Writer_Parameter (TextureConfigData)
Writer_Parameter (VertexSurface)
Writer_Parameter (VoxelData)
Writer_Parameter (VoxelSurface)
C3D_API uint32_t getSpotShadowMapCount ()
C3D_API uint32_t getPointShadowMapCount ()
C3D_API uint32_t getBaseLightComponentsCount ()
C3D_API uint32_t getMaxLightComponentsCount ()
C3D_API castor::String concatModelNames (castor::String lhs, castor::String rhs)
Writer_Parameter (DerivTex)
CU_DeclareSmartPtr (Material)
Typedef Documentation
BackgroundModelCreator
using castor3d::shader::BackgroundModelCreator = typedef std::function< BackgroundModelPtr(Engine const & engine , sdw::ShaderWriter & writer , Utils & utils , VkExtent2D targetSize , bool needsForeground , uint32_t & binding , uint32_t set) >
BackgroundModelFactory
using castor3d::shader::BackgroundModelFactory = typedef castor::Factory< BackgroundModel , castor::String , BackgroundModelPtr , BackgroundModelCreator >
BackgroundModelPtr
using castor3d::shader::BackgroundModelPtr = typedef std::unique_ptr< BackgroundModel >
DerivBlendComponents
using castor3d::shader::DerivBlendComponents = typedef BlendComponentsT< DerivTex >
DerivFragmentSurface
using castor3d::shader::DerivFragmentSurface = typedef RasterizerSurfaceT< DerivTex, ast::var::Flag::eNone >
FragmentSurfaceT
template<ast::var::Flag FlagT> using castor3d::shader::FragmentSurfaceT = typedef RasterizerSurfaceT< sdw::Vec3, FlagT >
LightingModelCreator
using castor3d::shader::LightingModelCreator = typedef std::function< LightingModelPtr(sdw::ShaderWriter & writer , Materials const & materials , Utils & utils , BRDFHelpers & brdf , ShadowOptions shadowsOptions , SssProfiles const * sssProfiles , bool enableVolumetric) >
LightingModelFactory
using castor3d::shader::LightingModelFactory = typedef castor::Factory< LightingModel , castor::String , LightingModelPtr , LightingModelCreator >
LightingModelPtr
using castor3d::shader::LightingModelPtr = typedef std::unique_ptr< LightingModel >
PassComponentsShaderPtr
using castor3d::shader::PassComponentsShaderPtr = typedef std::unique_ptr< PassComponentsShader >
PassMaterialShaderPtr
using castor3d::shader::PassMaterialShaderPtr = typedef std::unique_ptr< PassMaterialShader >
RasterizerSurface
using castor3d::shader::RasterizerSurface = typedef RasterizerSurfaceT< sdw::Vec3, ast::var::Flag::eNone >
RasterSurfaceT
template<typename TexcoordT > using castor3d::shader::RasterSurfaceT = typedef RasterizerSurfaceT< TexcoordT, ast::var::Flag::eNone >
ReflectionModelPtr
using castor3d::shader::ReflectionModelPtr = typedef std::unique_ptr< ReflectionModel >
Vec3BlendComponents
using castor3d::shader::Vec3BlendComponents = typedef BlendComponentsT< sdw::Vec3 >
VertexSurface
using castor3d::shader::VertexSurface = typedef VertexSurfaceT< sdw::var::Flag::eNone >
VoxelSurface
using castor3d::shader::VoxelSurface = typedef VoxelSurfaceT< sdw::var::Flag::eNone >
Function Documentation
concatModelNames()
C3D_API castor::String castor3d::shader::concatModelNames (castor::String lhs, castor::String rhs)
CU_DeclareCUSmartPtr()
castor3d::shader::CU_DeclareCUSmartPtr (castor3d::shader , BufferBase , C3D_API)
CU_DeclareSmartPtr()
castor3d::shader::CU_DeclareSmartPtr (Material)
getBaseLightComponentsCount()
C3D_API uint32_t castor3d::shader::getBaseLightComponentsCount ()
getLightingModelName()
C3D_API castor::String castor3d::shader::getLightingModelName (Engine const & engine, PassTypeID passType)
getMaxLightComponentsCount()
C3D_API uint32_t castor3d::shader::getMaxLightComponentsCount ()
getNodeId() [1/4]
sdw::UInt castor3d::shader::getNodeId (sdw::Array< shader::ObjectsIds > const & data, sdw::Array< sdw::UVec4 > const & instances, sdw::UInt pipelineID, sdw::UInt drawID, PipelineFlags const & flags) inline
References castor3d::PipelineFlags::enableInstantiation(), and getNodeId().
getNodeId() [2/4]
C3D_API sdw::UInt castor3d::shader::getNodeId (sdw::Array< shader::ObjectsIds > const & data, sdw::UInt pipelineID, sdw::UInt drawID)
getNodeId() [3/4]
template<ast::var::Flag FlagT> static sdw::UInt castor3d::shader::getNodeId (sdw::Array< shader::ObjectsIds > const & data, shader::VertexSurfaceT< FlagT > const & surface, sdw::UInt pipelineID, sdw::UInt drawID, PipelineFlags const & flags) static
References castor3d::PipelineFlags::enableInstantiation(), and castor3d::shader::VertexSurfaceT< FlagT >::objectIds.
Referenced by getNodeId().
getNodeId() [4/4]
C3D_API sdw::UInt castor3d::shader::getNodeId (sdw::Array< shader::PipelineObjectsIds > const & data, sdw::UInt pipelineID, sdw::UInt drawID)
getPointShadowMapCount()
C3D_API uint32_t castor3d::shader::getPointShadowMapCount ()
getSpotShadowMapCount()
C3D_API uint32_t castor3d::shader::getSpotShadowMapCount ()
makeFnArg()
C3D_API ast::expr::ExprList castor3d::shader::makeFnArg (sdw::ShaderWriter & shader, OutputComponents const & value)
rotateUV()
sdw::Vec2 castor3d::shader::rotateUV (sdw::Float const & rotateU, sdw::Float const & rotateV, sdw::Vec2 const & uv) inline
scaleUV()
template<typename LhsT , typename RhsT > LhsT castor3d::shader::scaleUV (LhsT const & scale, RhsT const & uv) inline
translateUV()
template<typename LhsT , typename RhsT > LhsT castor3d::shader::translateUV (LhsT const & translate, RhsT const & uv) inline
Writer_Parameter() [1/38]
castor3d::shader::Writer_Parameter (BillboardData)
Writer_Parameter() [2/38]
castor3d::shader::Writer_Parameter (BlendComponents)
Writer_Parameter() [3/38]
castor3d::shader::Writer_Parameter (CullData)
Writer_Parameter() [4/38]
castor3d::shader::Writer_Parameter (DerivTex)
Writer_Parameter() [5/38]
castor3d::shader::Writer_Parameter (DirectionalLight)
Writer_Parameter() [6/38]
castor3d::shader::Writer_Parameter (GpInfoData)
Writer_Parameter() [7/38]
castor3d::shader::Writer_Parameter (HdrConfigData)
Writer_Parameter() [8/38]
castor3d::shader::Writer_Parameter (Intersection)
Writer_Parameter() [9/38]
castor3d::shader::Writer_Parameter (LayeredLpvGridData)
Writer_Parameter() [10/38]
castor3d::shader::Writer_Parameter (Light)
Writer_Parameter() [11/38]
castor3d::shader::Writer_Parameter (LpvGridData)
Writer_Parameter() [12/38]
castor3d::shader::Writer_Parameter (LpvLightData)
Writer_Parameter() [13/38]
castor3d::shader::Writer_Parameter (Material)
Writer_Parameter() [14/38]
castor3d::shader::Writer_Parameter (MatrixData)
Writer_Parameter() [15/38]
castor3d::shader::Writer_Parameter (Meshlet)
Writer_Parameter() [16/38]
castor3d::shader::Writer_Parameter (MicrofacetDistributionSample)
Writer_Parameter() [17/38]
castor3d::shader::Writer_Parameter (ModelData)
Writer_Parameter() [18/38]
castor3d::shader::Writer_Parameter (ModelInstancesData)
Writer_Parameter() [19/38]
castor3d::shader::Writer_Parameter (MorphingWeightsData)
Writer_Parameter() [20/38]
castor3d::shader::Writer_Parameter (MorphTargetData)
Writer_Parameter() [21/38]
castor3d::shader::Writer_Parameter (MorphTargetsData)
Writer_Parameter() [22/38]
castor3d::shader::Writer_Parameter (OverlayData)
Writer_Parameter() [23/38]
castor3d::shader::Writer_Parameter (PickingData)
Writer_Parameter() [24/38]
castor3d::shader::Writer_Parameter (PointLight)
Writer_Parameter() [25/38]
castor3d::shader::Writer_Parameter (Ray)
Writer_Parameter() [26/38]
castor3d::shader::Writer_Parameter (RsmConfigData)
Writer_Parameter() [27/38]
castor3d::shader::Writer_Parameter (SceneData)
Writer_Parameter() [28/38]
castor3d::shader::Writer_Parameter (ShadowMapData)
Writer_Parameter() [29/38]
castor3d::shader::Writer_Parameter (SpotLight)
Writer_Parameter() [30/38]
castor3d::shader::Writer_Parameter (SsaoConfigData)
Writer_Parameter() [31/38]
castor3d::shader::Writer_Parameter (Surface)
Writer_Parameter() [32/38]
castor3d::shader::Writer_Parameter (TextureAnimData)
Writer_Parameter() [33/38]
castor3d::shader::Writer_Parameter (TextureConfigData)
Writer_Parameter() [34/38]
castor3d::shader::Writer_Parameter (TextureData)
Writer_Parameter() [35/38]
castor3d::shader::Writer_Parameter (VertexSurface)
Writer_Parameter() [36/38]
castor3d::shader::Writer_Parameter (Voxel)
Writer_Parameter() [37/38]
castor3d::shader::Writer_Parameter (VoxelData)
Writer_Parameter() [38/38]
castor3d::shader::Writer_Parameter (VoxelSurface)