Castor3D: castor3d::ChunkWriter< T > Class Template Reference
castor3d::ChunkWriter< T > Class Template Reference
Chunk data writer.
#include <ChunkWriter.hpp>
Static Public Member Functions
static bool write (T const *begin, T const *end, ChunkType type, BinaryChunk &chunk)
Writes a subchunk value into a chunk.
static bool write (T const &value, ChunkType type, BinaryChunk &chunk)
Writes a subchunk value into a chunk.
Static Public Member Functions inherited from castor3d::ChunkWriterBase
static bool write (uint8_t const *begin, uint8_t const *end, ChunkType type, BinaryChunk &chunk) noexcept
Writes a subchunk value into a chunk.
Detailed Description
template<typename T>
class castor3d::ChunkWriter< T >
Chunk data writer.
Member Function Documentation
write() [1/2]
template<typename T > static bool castor3d::ChunkWriter< T >::write (T const & value, ChunkType type, BinaryChunk & chunk) inline static
Writes a subchunk value into a chunk.
Parameters
[in] value The value
[in] type The subchunk type
[in] chunk The chunk
Returns
false if any error occured
References castor3d::getBuffer(), castor3d::getDataSize(), castor3d::prepareChunkDataT(), and castor3d::ChunkWriterBase::write().
write() [2/2]
template<typename T > static bool castor3d::ChunkWriter< T >::write (T const * begin, T const * end, ChunkType type, BinaryChunk & chunk) inline static
Writes a subchunk value into a chunk.
Parameters
[in] begin The values begin
[in] end The values end
[in] type The subchunk type
[in] chunk The chunk
Returns
false if any error occured
References castor3d::prepareChunkDataT(), and castor3d::ChunkWriterBase::write().
Referenced by castor3d::BinaryWriterBase< TWritten >::doWriteChunk(), castor3d::BinaryWriterBase< TWritten >::doWriteChunk(), castor3d::BinaryWriterBase< TWritten >::doWriteChunk(), castor3d::BinaryWriterBase< TWritten >::doWriteChunk(), castor3d::BinaryWriterBase< TWritten >::doWriteChunk(), and castor3d::BinaryWriterBase< TWritten >::doWriteChunk().
The documentation for this class was generated from the following file:
Castor3D/Binary/ChunkWriter.hpp