Castor3D: castor3d::BuffersNodesViewT< NodeT > Struct Template Reference
castor3d::BuffersNodesViewT< NodeT > Struct Template Reference
#include <PipelinesNodes.hpp>
Classes
struct BufferNodes
Public Types
using RenderedNode = RenderedNodeT< NodeT >
using NodesView = NodesViewT< NodeT >
Public Member Functions
auto emplace (ashes::BufferBase const &buffer)
RenderedNode * emplace (ashes::BufferBase const &buffer, RenderedNode node)
auto begin () noexcept
auto begin () const noexcept
auto end () noexcept
auto end () const noexcept
auto size () const noexcept
auto empty () const noexcept
size_t occupancy () const noexcept
Static Public Attributes
static uint64_t constexpr maxBuffers = 32ULL
static uint64_t constexpr maxCount = NodesView::maxCount * maxBuffers
Member Typedef Documentation
NodesView
template<typename NodeT > using castor3d::BuffersNodesViewT< NodeT >::NodesView = NodesViewT< NodeT >
RenderedNode
template<typename NodeT > using castor3d::BuffersNodesViewT< NodeT >::RenderedNode = RenderedNodeT< NodeT >
Member Function Documentation
begin() [1/2]
template<typename NodeT > auto castor3d::BuffersNodesViewT< NodeT >::begin () const inline noexcept
begin() [2/2]
template<typename NodeT > auto castor3d::BuffersNodesViewT< NodeT >::begin () inline noexcept
Referenced by castor3d::BuffersNodesViewT< NodeT >::emplace().
emplace() [1/2]
template<typename NodeT > auto castor3d::BuffersNodesViewT< NodeT >::emplace (ashes::BufferBase const & buffer) inline
References castor3d::BuffersNodesViewT< NodeT >::begin(), castor3d::C3D_EnsureNodesCounts, CU_Assert, CU_Exception, castor3d::BuffersNodesViewT< NodeT >::end(), castor3d::BuffersNodesViewT< NodeT >::maxBuffers, and castor3d::BuffersNodesViewT< NodeT >::size().
Referenced by castor3d::BuffersNodesViewT< NodeT >::emplace().
emplace() [2/2]
template<typename NodeT > RenderedNode * castor3d::BuffersNodesViewT< NodeT >::emplace (ashes::BufferBase const & buffer, RenderedNode node) inline
References castor3d::BuffersNodesViewT< NodeT >::emplace().
empty()
template<typename NodeT > auto castor3d::BuffersNodesViewT< NodeT >::empty () const inline noexcept
end() [1/2]
template<typename NodeT > auto castor3d::BuffersNodesViewT< NodeT >::end () const inline noexcept
end() [2/2]
template<typename NodeT > auto castor3d::BuffersNodesViewT< NodeT >::end () inline noexcept
Referenced by castor3d::BuffersNodesViewT< NodeT >::emplace().
occupancy()
template<typename NodeT > size_t castor3d::BuffersNodesViewT< NodeT >::occupancy () const inline noexcept
size()
template<typename NodeT > auto castor3d::BuffersNodesViewT< NodeT >::size () const inline noexcept
Referenced by castor3d::BuffersNodesViewT< NodeT >::emplace().
Member Data Documentation
maxBuffers
template<typename NodeT > uint64_t constexpr castor3d::BuffersNodesViewT< NodeT >::maxBuffers = 32ULL static constexpr
Referenced by castor3d::BuffersNodesViewT< NodeT >::emplace().
maxCount
template<typename NodeT > uint64_t constexpr castor3d::BuffersNodesViewT< NodeT >::maxCount = NodesView::maxCount * maxBuffers static constexpr
The documentation for this struct was generated from the following file:
Castor3D/Render/Node/PipelinesNodes.hpp