Castor3D: Castor3D::PointFrameVariable< T, Count > Class Template Reference
Castor3D::PointFrameVariable< T, Count > Class Template Reference
Point shader variable with variable type and dimensions.
Public Member Functions
PointFrameVariable (ShaderProgram *p_program)
Constructor.
PointFrameVariable (ShaderProgram *p_program, uint32_t p_occurences)
Constructor.
PointFrameVariable (PointFrameVariable< T, Count > const &p_object)
Copy constructor.
PointFrameVariable (PointFrameVariable< T, Count > &&p_object)
Move constructor.
PointFrameVariable & operator= (PointFrameVariable< T, Count > const &p_object)
Copy assignment operator.
PointFrameVariable & operator= (PointFrameVariable< T, Count > &&p_object)
Move assignment operator.
virtual ~PointFrameVariable ()
Destructor.
Castor::Coords< T, Count > GetValue ()
Retrieves the value.
Castor::Point< T, Count > GetValue () const
Retrieves the value.
Castor::Coords< T, Count > GetValue (uint32_t p_index)
Retrieves the value at given index.
Castor::Point< T, Count > GetValue (uint32_t p_index) const
Retrieves the value at given index.
void SetValue (Castor::Point< T, Count > const &p_ptValue)
Defines the value of the variable.
void SetValue (Castor::Point< T, Count > const &p_ptValue, uint32_t p_index)
Defines the value of the variable.
virtual uint32_t size () const
Retrieves the byte size of the variable.
Castor::Coords< T, Count > operator[] (uint32_t p_index)
Array subscript operator.
Castor::Point< T, Count > operator[] (uint32_t p_index) const
Array subscript operator.
eVARIABLE_TYPE GetType () const
Retrieves the variable type.
eFRAME_VARIABLE_TYPE GetFullType () const
Retrieves the variable full type.
Castor::String GetFullTypeName () const
Gives the variable full type name.
Public Member Functions inherited from Castor3D::TFrameVariable< T >
TFrameVariable (ShaderProgram *p_program)
Constructor.
TFrameVariable (ShaderProgram *p_program, uint32_t p_occurences)
Constructor.
TFrameVariable (TFrameVariable< T > const &p_object)
Copy constructor.
TFrameVariable (TFrameVariable< T > &&p_object)
Move constructor.
TFrameVariable & operator= (TFrameVariable< T > const &p_object)
Copy assignment operator.
TFrameVariable & operator= (TFrameVariable< T > &&p_object)
Move assignment operator.
virtual ~TFrameVariable ()
Destructor.
Castor::String GetDataTypeName () const
Gives the variable data type.
virtual uint8_t const *const const_ptr () const
Retrieves a pointer to the variable data.
virtual void link (uint8_t *p_buffer)
Defines the buffer holding the frame variable.
Public Member Functions inherited from Castor3D::FrameVariable
C3D_API FrameVariable (ShaderProgram *p_program)
Constructor.
C3D_API FrameVariable (ShaderProgram *p_program, uint32_t p_occurences)
Constructor.
C3D_API FrameVariable (FrameVariable const &p_object)
Copy constructor.
C3D_API FrameVariable (FrameVariable &&p_object)
Move constructor.
C3D_API FrameVariable & operator= (FrameVariable const &p_object)
Copy assignment operator.
C3D_API FrameVariable & operator= (FrameVariable &&p_object)
Move assignment operator.
virtual C3D_API ~FrameVariable ()
Destructor.
virtual C3D_API bool Initialise ()=0
Initialises the variable.
virtual C3D_API void Cleanup ()=0
Cleans up the variable.
virtual C3D_API void Bind ()=0
Binds this variable to the shader.
virtual C3D_API void Unbind ()=0
Unbinds this variable from the shader.
virtual C3D_API void SetValueStr (Castor::String const &p_value)
Defines the value of the variable, from a string.
virtual C3D_API void SetValueStr (Castor::String const &p_value, uint32_t p_index)
Defines the value of the variable, from a string.
virtual void SetName (Castor::String const &p_name)
Defines the name of the variable, as it appears in the shader program.
Castor::String GetName () const
Gives the name of the variable, as it appears in the shader program.
Castor::String GetStrValue () const
Retrieves the variable string value.
Castor::String GetStrValue (uint32_t p_index) const
Retrieves the variable string value at given index.
const uint32_t & GetOccCount () const
Retrieves the occurences count.
ShaderProgram * GetProgram () const
Retrieves the parent program.
Static Public Member Functions
static eVARIABLE_TYPE GetVariableType ()
Gives the full type of the variable.
static eFRAME_VARIABLE_TYPE GetFrameVariableType ()
Gives the variable full type.
static Castor::String GetFrameVariableTypeName ()
Gives the variable full type name.
Protected Types
typedef Castor::Policy< T > policy
Protected Types inherited from Castor3D::TFrameVariable< T >
typedef Castor::Policy< T > policy
Additional Inherited Members
Protected Member Functions inherited from Castor3D::TFrameVariable< T >
void DoCleanupBuffer ()
Protected Attributes inherited from Castor3D::TFrameVariable< T >
bool m_bOwnBuffer
Tells the variable owns it's buffer.
T * m_values
The buffer containing all values.
Protected Attributes inherited from Castor3D::FrameVariable
Castor::String m_name
The variable name as it appears in the shader program.
bool m_changed
Tells if the variable has changed since last execution of the shader.
uint32_t m_occurences
The array dimension if the variable represents an array.
Castor::StringArray m_strValue
The value of the variable.
ShaderProgram * m_program
The parent shader program.
Detailed Description
template<typename T, uint32_t Count>
class Castor3D::PointFrameVariable< T, Count >
Point shader variable with variable type and dimensions.
Author
Sylvain DOREMUS
Version
0.6.1.0
Date
14/08/2010
Member Typedef Documentation
policy
template<typename T, uint32_t Count> typedef Castor::Policy<T> Castor3D::PointFrameVariable< T, Count >::policy protected
Constructor & Destructor Documentation
PointFrameVariable() [1/4]
template<typename T, uint32_t Count> Castor3D::PointFrameVariable< T, Count >::PointFrameVariable (ShaderProgram * p_program)
Constructor.
Parameters
[in] p_program The program
PointFrameVariable() [2/4]
template<typename T, uint32_t Count> Castor3D::PointFrameVariable< T, Count >::PointFrameVariable (ShaderProgram * p_program, uint32_t p_occurences)
Constructor.
Parameters
[in] p_program The program
[in] p_occurences The array dimension
PointFrameVariable() [3/4]
template<typename T, uint32_t Count> Castor3D::PointFrameVariable< T, Count >::PointFrameVariable (PointFrameVariable< T, Count > const & p_object)
Copy constructor.
Parameters
[in] p_object The object to copy
PointFrameVariable() [4/4]
template<typename T, uint32_t Count> Castor3D::PointFrameVariable< T, Count >::PointFrameVariable (PointFrameVariable< T, Count > && p_object)
Move constructor.
Parameters
[in] p_object The object to move
~PointFrameVariable()
template<typename T, uint32_t Count> virtual Castor3D::PointFrameVariable< T, Count >::~PointFrameVariable () virtual
Destructor.
Member Function Documentation
GetFrameVariableType()
template<typename T, uint32_t Count> static eFRAME_VARIABLE_TYPE Castor3D::PointFrameVariable< T, Count >::GetFrameVariableType () inline static
Gives the variable full type.
Returns
The type
Donne le type complet de la variable
Returns
Le type
Referenced by Castor3D::PointFrameVariable< T, Count >::GetFullType().
GetFrameVariableTypeName()
template<typename T, uint32_t Count> static Castor::String Castor3D::PointFrameVariable< T, Count >::GetFrameVariableTypeName () inline static
Gives the variable full type name.
Returns
The name
Donne le nom du type complet de la variable
Returns
Le nom
Referenced by Castor3D::PointFrameVariable< T, Count >::GetFullTypeName().
GetFullType()
template<typename T, uint32_t Count> eFRAME_VARIABLE_TYPE Castor3D::PointFrameVariable< T, Count >::GetFullType () const inline virtual
Retrieves the variable full type.
Returns
The type
Implements Castor3D::FrameVariable.
References Castor3D::PointFrameVariable< T, Count >::GetFrameVariableType().
GetFullTypeName()
template<typename T, uint32_t Count> Castor::String Castor3D::PointFrameVariable< T, Count >::GetFullTypeName () const inline virtual
Gives the variable full type name.
Returns
The type
Donne le nom du type complet de la variable
Returns
Le type
Implements Castor3D::FrameVariable.
References Castor3D::PointFrameVariable< T, Count >::GetFrameVariableTypeName().
GetType()
template<typename T, uint32_t Count> eVARIABLE_TYPE Castor3D::PointFrameVariable< T, Count >::GetType () const inline virtual
Retrieves the variable type.
Returns
The variable type
Implements Castor3D::FrameVariable.
References Castor3D::PointFrameVariable< T, Count >::GetVariableType().
GetValue() [1/4]
template<typename T, uint32_t Count> Castor::Coords< T, Count > Castor3D::PointFrameVariable< T, Count >::GetValue () inline
Retrieves the value.
Returns
A Coords containing the value
GetValue() [2/4]
template<typename T, uint32_t Count> Castor::Point< T, Count > Castor3D::PointFrameVariable< T, Count >::GetValue () const inline
Retrieves the value.
Returns
A Point containing the value
GetValue() [3/4]
template<typename T, uint32_t Count> Castor::Coords< T, Count > Castor3D::PointFrameVariable< T, Count >::GetValue (uint32_t p_index) inline
Retrieves the value at given index.
Remarks
Check the index bounds
Parameters
[in] p_index The index
Returns
A Coords containing the value at given index
GetValue() [4/4]
template<typename T, uint32_t Count> Castor::Point< T, Count > Castor3D::PointFrameVariable< T, Count >::GetValue (uint32_t p_index) const inline
Retrieves the value at given index.
Remarks
Check the index bounds
Parameters
[in] p_index The index
Returns
A Point containing the value at given index
GetVariableType()
template<typename T, uint32_t Count> static eVARIABLE_TYPE Castor3D::PointFrameVariable< T, Count >::GetVariableType () inline static
Gives the full type of the variable.
Returns
The type of the variable
Referenced by Castor3D::PointFrameVariable< T, Count >::GetType().
operator=() [1/2]
template<typename T, uint32_t Count> PointFrameVariable& Castor3D::PointFrameVariable< T, Count >::operator= (PointFrameVariable< T, Count > const & p_object)
Copy assignment operator.
Parameters
[in] p_object The object to copy
Returns
A reference to this object
operator=() [2/2]
template<typename T, uint32_t Count> PointFrameVariable& Castor3D::PointFrameVariable< T, Count >::operator= (PointFrameVariable< T, Count > && p_object)
Move assignment operator.
Parameters
[in] p_object The object to move
Returns
A reference to this object
operator[]() [1/2]
template<typename T, uint32_t Count> Castor::Coords<T, Count > Castor3D::PointFrameVariable< T, Count >::operator[] (uint32_t p_index) inline
Array subscript operator.
Remarks
Doesn't check the index bounds
Parameters
[in] p_index The index
Returns
A reference to the value at given index
References Castor3D::TFrameVariable< T >::m_values.
operator[]() [2/2]
template<typename T, uint32_t Count> Castor::Point< T, Count > Castor3D::PointFrameVariable< T, Count >::operator[] (uint32_t p_index) const inline
Array subscript operator.
Remarks
Doesn't check the index bounds
Parameters
[in] p_index The index
Returns
A constant reference to the value at given index
References Castor3D::TFrameVariable< T >::m_values.
SetValue() [1/2]
template<typename T, uint32_t Count> void Castor3D::PointFrameVariable< T, Count >::SetValue (Castor::Point< T, Count > const & p_ptValue) inline
Defines the value of the variable.
Parameters
[in] p_ptValue The new value
SetValue() [2/2]
template<typename T, uint32_t Count> void Castor3D::PointFrameVariable< T, Count >::SetValue (Castor::Point< T, Count > const & p_ptValue, uint32_t p_index) inline
Defines the value of the variable.
Parameters
[in] p_ptValue The new value
[in] p_index The index of the value
size()
template<typename T, uint32_t Count> virtual uint32_t Castor3D::PointFrameVariable< T, Count >::size () const virtual
Retrieves the byte size of the variable.
Returns
The size
Implements Castor3D::FrameVariable.
The documentation for this class was generated from the following files:
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/Castor3DPrerequisites_Shader.hpp
Z:/Projets/C++/Castor3D/source/Core/Castor3D/Src/PointFrameVariable.hpp